### ISSUE TITLE
[Bug]:  Deleting History also delete some Youtube settings at youtube.com

### ISSUE THREAD

**Issue by softvision-raul-bucata** [mozilla-mobile/fenix#27106]
### Steps to reproduce

Deleting History or using Delete History and Site data will also delete;

- Prefered Video Quality settings (144p, 240p, 360p, so on).
- Youtube Light/Dark preference.
- Location preference. 

That Manual interference from us. Just let Firefox Mobile unused 3-6 hours or a whole day, the same effects as points above also achieved, aside from randomly got Logout from Youtube.

### Expected behaviour

History is deleted

### Actual behaviour

All site preferences are deleted.

### Device name

Google Pixel 3

### Android version

Android 12

### Firefox release type

Firefox

### Firefox version

Firefox Mobile 106.0

### Additional information

Originally reported here: https://github.com/webcompat/web-bugs/issues/111187

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21630)

**Comment by sum20156** [comment]
@softvision-raul-bucata I tried to reproduce the issue, but it is working fine at my end. Can you recheck is it still not working on your system.

**Comment by softvision-raul-bucata** [comment]
@sum20156 I can confirm that the issue is not reproducible anymore.




**Tested with:**

Browser / Version: Firefox Nightly 107.0a1 (2015910315-🦎107.0a1-20221016093143🦎)
Operating System: Samsung A51 (Android 11) -1080 × 2400 pixels 20:9 aspect ratio (~405 ppi density)
Operating System: Google Pixel 3 (Android 12) -1080 x 2160 pixels, 18:9 ratio (~443 ppi density)




[inv_42/2022]

**Comment by boek** [comment]
Closing as no longer able to reproduce.
