### ISSUE TITLE
Create telemetry to check if the device is rooted

### ISSUE THREAD

**Issue by kbrosnan** [mozilla-mobile/fenix#27109]
This has come up in https://github.com/mozilla-mobile/fenix/issues/27061 that we think this group of users are rooted but no way to check this currently. We would like to understand the population of rooted users that send telemetry. Our request is that we add a probe that detects if the data comes from a rooted device.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21631)

**Comment by telamon** [comment]
Why in the world would you want to try and track/understand a minority population that most likely doesn't want to be tracked/understood?

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1809327

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
