### ISSUE TITLE
Disable TCP and TCP CFR in Beta and Release channels

### ISSUE THREAD

**Issue by Left47** [mozilla-mobile/fenix#27111]
1. Disable TCP in Release & Beta 
2. Disable TCP CFR in Release & Beta (and remove from MR experiment plan)

These related features are pending organizational signoff.

Related to #26618

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21634)

**Comment by cpeterso** [comment]
We should leave TCP enabled in Nightly to continue user testing.

**Comment by cpeterso** [comment]
@Mugurell and I chatted on Slack. The current implementation uplifted to Beta 106 would not allow us to remotely enable TCP_FEATURE and TCP_CFR using Nimbus. We would need to uplift a code change.

@Mugurell is going to land new patches to remove the `isNightlyOrDebug` checks. TCP_FEATURE and TCP_CFR will be enabled by default in 107 and disabled in Beta 106 in a way that will allow us to enable the flags solely using Nimbus. If we decide that we don't want TCP to ride the trains in 107, we can uplift a new patch to Beta 107 that disables TCP (and leave it enabled in Nightly 108).

**Comment by cpeterso** [comment]
Fixed by #27168 and #27148

**Comment by LaurentiuApahideanSV** [comment]
I tested the issue on Firefox Beta 106.0b3 and the TCP CFR in no longer displayed and the Isolate cross-site cookies is not present in the Enhanced Tracking Protection menu.
### Devices used:
- Huawei MediaPad M3 (Android 7)
- Samsung Galaxy S22 Ultra (Android 12)
