### ISSUE TITLE
The transition between Private Browsing and Normal Browsing is not smooth when a wallpaper is set

### ISSUE THREAD

**Issue by delia-pop** [mozilla-mobile/fenix#27120]
### Steps to reproduce

1. Launch Fenix
2. Set a wallpaper from the Wallpapers Settings menu.
3. Return to the homepage and tap on the Private Browsing icon.
4. Tap again on the PB icon to return to homepage. Observe the toolbar color.

### Expected behaviour

The transition between Private Browsing and Normal Browsing is smooth, without visual defects.

### Actual behaviour

The transition between Private Browsing and Normal Browsing is slower, the toolbar is still displayed in the PB color for a split second after the Normal Browsing mode was entered and the wallpaper displayed.

### Device name

Google Pixel 6 

### Android version

Android 13

### Firefox release type

Firefox Nightly

### Firefox version

107.0a1 from 09/22

### Additional information

The issue was initially discussed over https://github.com/mozilla-mobile/fenix/issues/26644 .
Further testing revealed that the issues was introduced first in Nightly 106.0a1 from 09/14 after #26511 was fixed. 
Also reproducible in Beta 106.0b1.

https://user-images.githubusercontent.com/89388888/191927037-d4be34c0-221d-4208-b814-aa299d3ff316.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21638)

**Comment by cpeterso** [comment]
Not a blocker for MR.

@MatthewTighe - Do you know why switching from private browsing to normal browsing would be slower with a wallpaper?

**Comment by MatthewTighe** [comment]
Loading and displaying the wallpaper will have some impact on performance. The difference in the toolbar's color changing and the rest of the home screen rendering seems pretty annoying though. It's possible we could do something similar to what @Mugurell did in https://github.com/mozilla-mobile/fenix/pull/27105 to improve that, though I don't know for sure.

**Comment by cpeterso** [comment]
We don't need to fix this bug for MR v106. We can take a look in v108 (and maybe uplift to Beta v107).

**Comment by MatthewTighe** [comment]
Stepping through the video, it looks like we may just need to wait to apply the wallpaper until after the theme is applied to get a more visually consistent experience.

- Private browsing 

![Screen Shot 2022-09-23 at 1 01 57 PM](https://user-images.githubusercontent.com/10427470/192048070-6d20cac1-d248-4d1e-82b7-27a20226c888.png) 

- Wallpaper applied

![image](https://user-images.githubusercontent.com/10427470/192048123-6186a875-c40b-41d9-818a-4a7a3ec51f57.png) 

- Home screen content renders and theme applies 

![Screen Shot 2022-09-23 at 1 03 29 PM](https://user-images.githubusercontent.com/10427470/192048192-d6dd8406-e66e-433c-95ae-949fc40b489b.png)

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807530

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
