### ISSUE TITLE
[Bug]:[a11y] Talkback does not mention "Learn more" as a hyperlink in the Wallpapers section

### ISSUE THREAD

**Issue by AdinaPetridean** [mozilla-mobile/fenix#27128]
### Steps to reproduce

1. Turn TalkBack (or the available screen reader) on.
2. Launch the Firefox application.
3. Go to 3dot menu- Settings- Homepage- Wallpapers using TB gestures.
4. Tap on "Learn more" hyperlink and notice what talkback announces.

### Expected behaviour

"Learn more" is referred to as a hyperlink.

### Actual behaviour

Talkback does not mention "Learn more" as a hyperlink in the pockets section

### Device name

Xperia 10    

### Android version

  Android 12

### Firefox release type

Firefox Nightly

### Firefox version

Nightly 107.0a1 - 09/23

### Additional information

<img src="https://user-images.githubusercontent.com/108326843/191962693-57f5f72a-9753-42d2-812e-548158fde4be.JPEG" width="50%" />

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21646)

**Comment by cpeterso** [comment]
Not a blocker for MR v106, but we should fix soon.

**Comment by Alexandru2909** [comment]
For QA: Based on the discussion in [this slack thread](https://mozilla.slack.com/archives/C03KPTP37BN/p1664981102950999), the action label for the learn more button should be "open link to learn more about this collection".

**Comment by AdinaPetridean** [comment]
Verified on Nightly 107.0a1 - 10/07 with OnePlus 9 Pro (Android 12).
