### ISSUE TITLE
The Jump back in CFR overlaps the Messaging Banner 

### ISSUE THREAD

**Issue by delia-pop** [mozilla-mobile/fenix#27122]
### Steps to reproduce

1. With a clear profile launch Fenix and dismiss the onboarding tour.
2. From homepage, perform 2-3 restarts.
3. After restarting the app, open a webpage.
4. From the page opened in step 3, perform another restart.
5. Tap the home icon to return to homepage.
6. Observe the "Jump back in" CFR.

### Expected behaviour

All assets should be properly displayed on homepage. The "Jump back in" CFR should not overlap the messaging banner.

### Actual behaviour

The "Jump back in" CFR overlaps the messaging banner.

### Device name

Google Pixel 6 

### Android version

Android 13

### Firefox release type

Firefox Nightly

### Firefox version

Nightly 107.0a1 from 09/22

### Additional information

This is also reproducible for an upgrading user on Nightly and Beta 106.0b1

Preconditions:
On an older Fenix version make sure that:
- the default browser messaging banner is displayed on homepage;
- here is at least one webpage opened
- In Settings > Homepage the opening screen is set to Homepage;
- The "Jump back in CFR" was not already seen;

1. Update Fenix to the later version.
2. Dismiss the onboarding.
3. On Nightly, due to issue #27121 the app displays the homepage instead of opening the open tab. Perform a restart so that the open tab is displayed.
4. From the webpage opened, restart the app.
5. Tap the home icon to return to homepage.
6. Observe the "Jump back in" CFR.

The issue will not occur if the messaging banner was already seen before triggering the "Jump back in" CFR.

https://user-images.githubusercontent.com/89388888/191932772-feebc9eb-0887-4413-aa1c-3d0fdc25ec7a.mp4

https://user-images.githubusercontent.com/89388888/191932780-beef2893-150a-4e58-b8ea-552f0caa525e.mp4

https://user-images.githubusercontent.com/89388888/191932833-255c9339-605d-4af8-a7f3-ebd057bbcff6.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21640)

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812460

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
