### ISSUE TITLE
[a11y] Talkback does not mention "Learn more" as a hyperlink in the Pocket section

### ISSUE THREAD

**Issue by AdinaPetridean** [mozilla-mobile/fenix#27126]
### Preconditions:
Make sure the local is on US.

### Steps to reproduce

1. Turn TalkBack (or the available screen reader) on.
2. Launch the Firefox application and go on homepage.
3. Go to Pocket section using TB gestures. 
4. Tap on "Learn more" hyperlink and notice what talkback announces.

### Expected behaviour

"Learn more" is referred to as a hyperlink.

### Actual behaviour

Talkback does not mention "Learn more" as a hyperlink in the pockets section

### Device name

Xperia 10    

### Android version

Android 12

### Firefox release type

Firefox Nightly

### Firefox version

Firefox Nightly 107.0a1 - 09/23

### Additional information

<img src="https://user-images.githubusercontent.com/108326843/191952143-922c564c-2cee-40b7-a43a-e414f1866c8b.JPEG" width="50%" />

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21644)

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807369

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
