### ISSUE TITLE
The Jump back in CFR appears distanced from the Jump back in section when the user is signed in

### ISSUE THREAD

**Issue by delia-pop** [mozilla-mobile/fenix#27124]
### Steps to reproduce

1. Perform a clear data and launch Fenix.
2. Open a tab.
3. Go to Settings and sign in using a valid account with more than 4 top sites tiles displayed on homepage.
4. Wait for the sync to be performed then return to homepage.
5. Observe the position of the "Jump back in" CFR.

### Expected behaviour

The "Jump back in" CFR is displayed above the Jump back in section, but at a reasonable distance.

### Actual behaviour

The "Jump back in" CFR is displayed at a considerable distance from the Jump back in section when the user is signed in before seeing the CFR, since the second row on shortcuts takes up the space.

### Device name

Google Pixel 6 

### Android version

Android 13

### Firefox release type

Firefox Nightly

### Firefox version

Nightly 107.0a1 from 09/22

### Additional information

On tablet devices this is issue is more visible. 
Note that the space between the CFR and the section is event bigger when issue https://github.com/mozilla-mobile/fenix/issues/27122 occurs. 

![CFR](https://user-images.githubusercontent.com/89388888/191945454-8a4610d0-0b05-4498-b5d2-8d34bbf56de5.jpg)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21642)

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812459

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
