### ISSUE TITLE
[Bug]: The wallpaper selection tool is displayed in Private Browsing

### ISSUE THREAD

**Issue by delia-pop** [mozilla-mobile/fenix#27127]
### Steps to reproduce

Prerequisites:
The user has just installed the Firefox app for the first time.
The Tab Pickup and Jump Back In CFRs are not currently being displayed.
The user has not seen the wallpaper selection tool before.

1. Launch Fenix with a clean profile.
2. In Normal Browsing mode, visit a webpage.
3. Return to homepage.
4. Tap the Private Browsing icon.
5. Observe the PB screen.

### Expected behaviour

The wallpaper selection tool is not displayed in private mode.

### Actual behaviour

The wallpaper selection tool is displayed in private mode. Wallpapers can be loaded. 
After tapping the "Explore more wallpapers" link, the CFR for private shortcut is incorrectly displayed in the Wallpapers Setting screen, which also displayed in the private color.

### Device name

Google Pixel 6

### Android version

Android 13

### Firefox release type

Firefox Nightly

### Firefox version

Firefox Nightly 107.0a1 09/23

### Additional information

https://user-images.githubusercontent.com/89388888/191955394-4bcdca18-9a17-47f7-9d37-43d6df6bb666.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21645)

**Comment by cpeterso** [comment]
@mavduevskiy - Can you please take a look at this bug? This bug is a nice to have for MR v106.

We should not show the wallpaper selection tool in private browsing.

For any MR bug fixes to be included in the v106 release, they should be uplifted (and landed in the beta branch) by end of day 2022-09-30.

**Comment by AdinaPetridean** [comment]
Verified on Firefox Nightly 107.0a1 - 09/30 with Xperia 10 (Android 12).
Please note it is still repro on Firefox Beta 3 (106.b3) with Xperia 10 (Android 12).

**Comment by AdinaPetridean** [comment]
Verified also on Firefox Beta 106.0b4 with Xiaomi Pad5 (Android 12).
