### ISSUE TITLE
[Bug]:[a11y]Talkback does not mention the TopSites shortcuts as hyperlinks

### ISSUE THREAD

**Issue by AdinaPetridean** [mozilla-mobile/fenix#27135]
### Steps to reproduce

1. Turn TalkBack (or the available screen reader) on.
2. Launch the Firefox application and go on homepage.
3. Go to Pocket section using TB gestures.
4. Tap on a topsite shortcut hyperlink and notice what talkback announces.

### Expected behaviour

The TopSite shortcut is referred to as a hyperlink ( "Double tap to activate").

### Actual behaviour

The TopSite shortcut is  not referred to as a hyperlink ( not mentioned "Double tap to activate").

### Device name

Xperia 10      

### Android version

Android 12

### Firefox release type

Firefox Nightly

### Firefox version

Firefox Nightly 107.0a1 - 09/23

### Additional information

<img src="https://user-images.githubusercontent.com/108326843/191984327-7bcbc7c7-da14-442d-b4dc-d57f7fb4bc76.JPEG" width="50%" />

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21652)

**Comment by cpeterso** [comment]
Not a blocker for MR v106.

**Comment by AdinaPetridean** [comment]
Verified as fixed on Nightly 108.0a1 from 10/25 with Xperia 10 (Android 12). The 'TopSites' are mentioned as hyperlinks by Talkback.

**Comment by SoftVision-LorandJanos** [comment]
Verified as fixed on the latest Beta 108.0b1.
Device used: Google Pixel 4 (Android 12).
