### ISSUE TITLE
Add telemetry for bookmark search

### ISSUE THREAD

**Issue by rocketsroger** [mozilla-mobile/fenix#27147]
Add telemetry to bookmark search to determine when the user:

- Taps on the search icon
- Taps on the result from search

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21657)

**Comment by AdinaPetridean** [comment]
Verified as fixed on Nightly 107.0a1 from 10/10 with Xperia 10 (Android 12). The following events were generated:

1. The search icon is tapped.
{
          "timestamp": 5380,
          "category": "bookmarks_management",
          "name": "search_icon_tapped"
        },
2. The search result is taped.
        {
          "timestamp": 10619,
          "category": "bookmarks_management",
          "name": "search_result_tapped"
        },
3. The bookmark suggestion is clicked.
        {
          "timestamp": 10652,
          "category": "awesomebar",
          "name": "bookmark_suggestion_clicked"
        },
