### ISSUE TITLE
[Bug]: about:config buttons and options not visible

### ISSUE THREAD

**Issue by sheikh-azharuddin** [mozilla-mobile/fenix#27143]
### Steps to reproduce

In latest firefox nightly about:config buttons and options are not visible

### Expected behaviour

Should be visible 

### Actual behaviour

Not visible in both white and dark mode

### Device name

asus rog 3

### Android version

android 12

### Firefox release type

Firefox Nightly

### Firefox version

latest

### Device logs

![Screenshot_20220924-000317427](https://user-images.githubusercontent.com/58127841/192034904-b8025137-0af0-436d-ad29-fff81ffe4d38.jpg)

### Additional information

![Screenshot_20220924-000902623 (1)](https://user-images.githubusercontent.com/58127841/192035101-8eec60ed-2c8b-462c-a2a0-de76239654a5.jpg)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21654)

**Comment by kbrosnan** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1792258

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
