### ISSUE TITLE
Unexpectedly large section titles on home screen

### ISSUE THREAD

**Issue by cadeyrn** [mozilla-mobile/fenix#27144]
### Steps to reproduce

0. make sure that you have some sections enabled on the Firefox home screen
1. view the home screen

### Actual behaviour

The section title are really large.

The following screenshot shows the old font size on the left side and the new font size on the right side.

![comparison](https://user-images.githubusercontent.com/1100614/192039619-3ae75eae-608b-4fdf-8c66-fd4fc0556957.png)

### Expected behaviour

Smaller font size for the section titles. At least I think that the smaller font size looked much better.

### Device name

OnePlus 10 Pro

### Android version

Android 12

### Firefox release type

Firefox

### Firefox version

106.0b2

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21655)

**Comment by cadeyrn** [comment]
It looks like the section titles were changed in #26888. @gabrielluong Based on that PR, I guess it was an intentional change. But since Firefox 106 will be released very soon could you please confirm whether such large section title are expected or not?

I think the font size should be smaller, at least a bit. Please also note that the "Show all" links are no longer well aligned with the section title.

If it's all intended feel free to close this issue.

**Comment by gabrielluong** [comment]
The bigger section title are actually expected. I am not necessarily noticing the "Show all" links are no longer well aligned in the screenshots you attached. However, there is some ongoing work that could affect this in https://github.com/mozilla-mobile/fenix/pull/26885.

**Comment by cadeyrn** [comment]
> I am not necessarily noticing the "Show all" links are no longer well aligned in the screenshots you attached.

@gabrielluong Sorry for the delay. I changed the language to another one with a longer section title and zoomed the screenshot a bit:

<img width="1052" alt="Bildschirmfoto 2022-10-07 um 17 00 23" src="https://user-images.githubusercontent.com/1100614/196206507-c49c0ca8-bd45-4025-9c6c-e6bbc2822ae3.png">

Maybe it's technically correct aligned, I can't say. But it's at least my first impression that the link should be placed a little lower.

**Comment by Dunexus** [comment]
![image](https://user-images.githubusercontent.com/13906248/196362358-f7fa61c3-63aa-43cb-80d8-ef378955765c.png)

It looks like they are vertically aligned center to center but as the title is bigger, they don't share a common baseline.

**Comment by cadeyrn** [comment]
Thanks, @Dunexus. Then it's probably the common baseline what I expect, and it's not an alignment issue. It's one of those issues where I feel like something is wrong, but I'm not sure myself exactly what it is or how to describe it.

**Comment by gabrielluong** [comment]
Visually, it looks fine to me and y'all are right it will not share a baseline because the title can be multi-line and it is bigger - however that is intended. I am not sure if I am still missing something. However, I will still defer to #26885

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813869

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
