### ISSUE TITLE
Video progress/control bar off screen when in fullscreen mode

### ISSUE THREAD

**Issue by xenthm** [mozilla-mobile/fenix#27153]
### Steps to reproduce

1. Have a video playing in the foreground (multiple sites have this issue, but most notably Twitter mobile videos)
2. Go fullscreen with the video controls
3. Be in portrait orientation
4. Observe video progress/control bar

### Expected behaviour

Video progress/control bar fully visible and able to be interacted with. 

Here is a screenshot of a Twitter mobile video in landscape with the expected behaviour, ignore the blue battery indicator in the bottom left. 
![Screenshot_2022-09-24-21-51-28-42_3aea4af51f236e4932235fdada7d1643 1](https://user-images.githubusercontent.com/56202777/192101772-7f8ee7ef-5002-4629-865a-7c89139fb83f.jpg)

Here is a screenshot of a Youtube mobile video in portrait with the expected behaviour, with progress and control bar visible:
![Screenshot_2022-09-24-21-59-13-31_3aea4af51f236e4932235fdada7d1643 1](https://user-images.githubusercontent.com/56202777/192102363-4944c609-dc7a-4733-84f7-ef054ae934c9.jpg)

### Actual behaviour

Video progress/control bar partially off screen, unable to see or interact with controls (pause, mute) or scrub the progress bar. 

And here is a screenshot of the same video in portrait. Notice the progress bar is still visible, but it is unable to be scrubbed. 
![Screenshot_2022-09-24-21-51-15-33_3aea4af51f236e4932235fdada7d1643 1](https://user-images.githubusercontent.com/56202777/192101861-665ab4f1-f58f-42a2-a173-83893296449d.jpg)

### Device name

Oneplus 8

### Android version

Android 12

### Firefox release type

Firefox

### Firefox version

104.2.0

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21661)

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813871

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
