### ISSUE TITLE
Dynamic navbar leaves white space with fixed background image

### ISSUE THREAD

**Issue by Frank-Steiner** [mozilla-mobile/fenix#27155]
### Steps to reproduce

I have the navbar at the top and it hides when scrolling up and re-appears when scrolling down. Now visit a page with 
```
<style>
body {
  background: url(some_image.jpg) repeat fixed;
}
</style>
```
An example is here: [https://www.familiesteiner.de/test.shtml](https://www.familiesteiner.de/test.shtml)

### Expected behaviour

The background image should always fill the whole visible body and stay fixed while scrolling.

### Actual behaviour

When scrolling up, the background moves up together with the rest of the page until the navbar has vanished, then it stays fixed. While the background moves up a space with white background appears at the bottom of the page with exactly the size of the navbar.
When removing the "fixed" option for the background, the background image will always cover the whole visible body.

### Device name

Motorola G5s+, Realme 5G, ..

### Android version

Android 10 and 11

### Firefox release type

Firefox

### Firefox version

105.1.0

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21662)

**Comment by LaurentiuApahideanSV** [comment]
I can confirm the issue is reproducible on Fenix Nightly 107.0a1 2022-09-29.
### Devices used:
- Google Pixel 6 (Android 13)
- Samsung Galaxy S22 Ultra (Android 12)

**Comment by SoftVision-LorandJanos** [comment]
Hi @Frank-Steiner! Thank you for your report!
I've managed to reproduce your issue on the latest builds:
- Nightly 107.0a1 (2022-09-28T17...).
- Beta 106.0b2.
- RC 105.1.0.

Also tested on Chrome where the behavior was as expected.
Device used: Google Pixel 4 (Android 12).

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813873

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
