### ISSUE TITLE
Tapping in fullscreen videos don't register properly 

### ISSUE THREAD

**Issue by unomi-zan** [mozilla-mobile/fenix#27152]
### Steps to reproduce

1. Play any video on fullscreen.
2. Tap on the video and perform actions like play/pause, fast-forward.

### Expected behaviour

You should be able to perform things like play/pause, fast-forward, exit fullscreen without needing extra taps.

### Actual behaviour

While tapping in video, the status bar briefly shows up and the taps don't register in the video player.

### Device name

Xiaomi Redmi note 7 pro

### Android version

Android 11 custom rom

### Firefox release type

Firefox

### Firefox version

105.1.0

### Additional information

https://user-images.githubusercontent.com/79187956/192086348-2fd5e1b7-936f-43e6-bdca-1748a15ddc95.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21660)

**Comment by Alexey104** [comment]
Confirm the same issue on Redmi 5 Pro, Lineageos 18.1 (Android 11). Not only reproducible on Youtube, but other video players on other websites are also affected.

**Comment by unomi-zan** [comment]
I switched to 2 other custom roms and found out more information for this issue:
- it affects android 11 and higher. I used android 10 for a short period and everything was fine.
- it started from Firefox v105.

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813870

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Comment by BedroQuendo** [comment]
Same issue (still present, mind you) on my Motorola One Fusion, running Android 11. This new frustrating bug is such a deal breaker for a mobile browser that outperforms any Chromium based ones on so many levels 😔
