### ISSUE TITLE
[a11y] Consider making "Search engine" button from home screen, item larger

### ISSUE THREAD

**Issue by AdinaPetridean** [mozilla-mobile/fenix#27169]
### Steps to reproduce

1.Have the Accessibility scanner app installed and opened.
2.Launch Fenix.
3.Use the Accessibility Scanner and scan the Homepage. Observe the suggestion.

### Expected behaviour

The height of this touch target should be 48 dp or larger.

### Actual behaviour

This item's height is 40dp.

### Device name

Xperia 10 

### Android version

Android 12

### Firefox release type

Firefox Beta

### Firefox version

Firefox Beta 106.0b2

### Additional information

![Search engine](https://user-images.githubusercontent.com/108326843/192257474-32f5c7fe-5ae0-4be6-b131-d7dbc8f5b603.JPEG)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21667)

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1809814

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
