### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Jason7263** [mozilla-mobile/fenix#27164]
### Steps to reproduce

open firefox mobile
Home tab has history items on the home tab

### Expected behaviour

When customizing home, checking only "Shortcuts" I expect to see only "Shortcuts" on home tab

### Actual behaviour

all history pages are showing up on home tab even though it is turned off under home customization. 

### Device name

samsung s22 ultra

### Android version

android 12

### Firefox release type

Firefox

### Firefox version

105.1.0

### Additional information

this is a massive privacy issue that allows anyone looking at your phone to see your history.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21666)

**Comment by LaurentiuApahideanSV** [comment]
This is the intended behavior please see https://github.com/mozilla-mobile/fenix/issues/24271#issuecomment-1067149304 for further information.
