### ISSUE TITLE
[Bug]: Copy link from special tab

### ISSUE THREAD

**Issue by plwt** [mozilla-mobile/fenix#27163]
### Steps to reproduce

1. Open a link to an external site from the Slack app
2. Link opens in a special tab
3. Open hotdog menu, and select Copy link

### Expected behaviour

Notification that the link has been copied.
Link is pasted when paste is selected in another app (such as Fx)

### Actual behaviour

Nothing happens.

### Device name

Motorola Moto G30

### Android version

Android 12

### Firefox release type

Firefox Nightly

### Firefox version

107.0a1

### Additional information

User feedback - https://support.mozilla.org/en-US/questions/1390070

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21665)

**Comment by LaurentiuApahideanSV** [comment]
This is an issue with the Slack application and not Firefox see issue https://github.com/mozilla-mobile/fenix/issues/23438 for more details.
