### ISSUE TITLE
Allow Downloading of embedded Videos

### ISSUE THREAD

**Issue by trytomakeyouprivate** [mozilla-mobile/fenix#27161]
### What is the user problem or growth opportunity you want to see solved?
The Addon [VideoDownloadHelper](https://addons.mozilla.org/en-US/firefox/addon/video-downloadhelper/) doesnt work on mobile, probably because a lot of features in video playback are not supported.

### How do you know that this problem exists today? Why is this important?
The Addon extends the browsers ability to access and download locked web-content (not DRM). It doesnt work when used in a custom Addon collection in Fenix.

### Who will benefit from it?
All power-users wanting to archive and own media distributed in the Web.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21664)

**Comment by kbrosnan** [comment]
We don't keep issues open for individual extensions.

**Comment by trytomakeyouprivate** [comment]
> We don't keep issues open for individual extensions.

This is not about the addon, its about the general ability to do these things, which Firefox Desktop provides, Fenix doesnt.
