### ISSUE TITLE
[Bug]: [a11y] Logins and passwords- Saved logins - Consider making "Learn more about Sync" clickable item larger  

### ISSUE THREAD

**Issue by AdinaPetridean** [mozilla-mobile/fenix#27171]
### Steps to reproduce

1. Have Google Accessibility Scanner installed.
2. Go to Settings - Logins and passwords - Saved logins
3. Enter the device pattern and scan the "Saved logins" page.

### Expected behaviour

No suggestions are made.

### Actual behaviour

Consider making this clickable item larger. This item's height is 30 dp. Consider making the height of this touch target 48 dp or larger.

### Device name

Xperia 10 

### Android version

Android 12

### Firefox release type

Firefox Beta

### Firefox version

Firefox Beta 106.0b2

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21669)

**Comment by boek** [comment]
Issue moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812196
