### ISSUE TITLE
History - Consider making the URL icons from History page larger

### ISSUE THREAD

**Issue by AdinaPetridean** [mozilla-mobile/fenix#27179]
### Steps to reproduce

1. Have the Accessibility scanner installed and opened.
2. If needed, visit a couple of websites, to create History.
3. Open "History" from the three-dot menu.
4. Using the Accessibility Scanner, scan the "History" page.

### Expected behaviour

No suggestions are made.

### Actual behaviour

Consider making this clickable item larger. This item's height is 40 dp x 40dp. Consider making this touch target 48 dp wide and 48 dp high or larger.

### Device name

Xperia 10 

### Android version

Android 12

### Firefox release type

Firefox Beta

### Firefox version

Firefox Beta 106.0b2

### Additional information

<img src="https://user-images.githubusercontent.com/108326843/192314813-5c5fcf60-b33b-44f1-a7bf-3492fa260ca8.JPEG" width="50%" /><img src="https://user-images.githubusercontent.com/108326843/192314978-0ea5ca3f-60b4-488c-8d98-2e4d4de51048.JPEG" width="50%" />

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21675)

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813086

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
