### ISSUE TITLE
[a11y] URL bar - "Cancel"  button is recommended to be resized 

### ISSUE THREAD

**Issue by AdinaPetridean** [mozilla-mobile/fenix#27170]
### Steps to reproduce

1. Have the Accessibility scanner app installed and opened.
2. Open app and from the homescreen, tap on "Search or enter address".
3. Insert data at field level.
4. Scan the search screen.

### Expected behaviour

Consider making this clickable item larger. Consider making the height of this touch target 48 dp or larger.

### Actual behaviour

This item's height is 40dp.

### Device name

Xperia 10 

### Android version

Android 12

### Firefox release type

Firefox Beta

### Firefox version

Firefox Beta 106.0b2

### Additional information

![close](https://user-images.githubusercontent.com/108326843/192267081-a3bf69d9-d674-46b4-96f6-f3f2f6f7c110.JPEG)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21668)

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807589

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
