### ISSUE TITLE
The "Collections" placeholder text color flickers when the homepage is viewed

### ISSUE THREAD

**Issue by delia-pop** [mozilla-mobile/fenix#27178]
### Steps to reproduce

1. With a clean profile go to Wallpapers settings screen.
2. Select a wallpaper and tap on the "VIEW" button on the snackbar. 
3. On homepage, observe the "Collections" placeholder.

### Expected behaviour

After https://github.com/mozilla-mobile/fenix/issues/27026, the Collections placeholder adapts to the wallpaper adapted text color. This transition is smooth, without visual defects.

### Actual behaviour

The color transition on the "Collections" placeholder is not smooth when certain wallpapers are set on homepage. The flicker can be observed when changing the wallpaper, when returning on homepage from Settings and when the opening screen in set to homepage. 
Depending on the theme, there are certain wallpapers on which the issue in more visible:
- for Light theme: Visionary, Playmaker, Innovator, Activist (wallpapers with text color white)
- for Dark theme: Expressionist & Classic collection (wallpapers with text color black)

### Device name

Lenovo Yoga Tab 11

### Android version

Android 11

### Firefox release type

Firefox Nightly

### Firefox version

Nightly 107.0a1 from 09/26

### Additional information

Also reproducible on other devices.

https://user-images.githubusercontent.com/89388888/192311687-bf7af402-498b-4e6b-bee3-3ef43094e225.mp4

![TabCollectionsText](https://user-images.githubusercontent.com/89388888/192311145-db80a0f0-b7d4-476a-9c0e-118096a795a2.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21673)

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1809802

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
