### ISSUE TITLE
[Bug]:[a11y] 3 dot menu - Bookmarks -  Consider increasing "Add" and "Edit" buttons 

### ISSUE THREAD

**Issue by AdinaPetridean** [mozilla-mobile/fenix#27176]
### Steps to reproduce

1. Have Google Accessibility Scanner installed.
2. Navigate to any web page, and tap on the nav bar's three-dot menu.
3. Scan the 3 dot menu.
4. Observe the scan (Bookmarks - Add).
5. Go back to 3dot menu and tap on Add button.
6. Tap on 3dot menu and scan. 
7. Observe the scan (Bookmarks - Edit).

### Expected behaviour

No suggestions are made.

### Actual behaviour

Consider making this clickable item larger. This item's height is 24 dp. Consider making the height of this touch target 48 dp or larger.

### Device name

Xperia 10 

### Android version

Android 12

### Firefox release type

Firefox Beta

### Firefox version

Firefox Beta 106.0b2

### Additional information

<img src="https://user-images.githubusercontent.com/108326843/192309809-04cbd48b-273b-41a9-94ac-c03878210b31.JPEG" width="50%" /><img src="https://user-images.githubusercontent.com/108326843/192309825-6e92978b-983b-4058-9fd6-93dd9772eb46.JPEG" width="50%" />

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21672)

**Comment by bigConifer** [comment]
Duplicate of #24560

@AdinaPetridean there is also a ticket on AC covering this bug (https://github.com/mozilla-mobile/android-components/issues/11958).

**Comment by AdinaPetridean** [comment]
Based on the latest comments, I have set this issue as CLOSED.
