### ISSUE TITLE
[Bug] Tab Pickup CFR is not displayed on Beta

### ISSUE THREAD

**Issue by SoftVision-LorandJanos** [mozilla-mobile/fenix#27172]
### Steps to reproduce

1. Have a fresh install.
2. On the main device login in with a Firefox account and open a few tabs.
3. On a second device login with the same account, open a few tabs and wait for or perform a manual sync.
4. Observe the homepage on the main device.

### Expected behaviour

A Tab Pickup CFR is displayed above the "See all synced tabs" section.

According to https://github.com/mozilla-mobile/fenix/blob/main/app/src/main/java/org/mozilla/fenix/FeatureFlags.kt#L26-L29, the CFR is blocked to be shown only on Nightly though this is an MR feature that should be available across all releases - https://github.com/mozilla-mobile/fenix/issues/26489

### Actual behaviour

The Tab Pickup CFR is not displayed .

### Device name

Xiaomi Mi11 Lite

### Android version

Android 11

### Firefox release type

Firefox Beta

### Firefox version

106.0b2

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21670)

**Comment by AaronMT** [comment]
@SoftVision-LorandJanos title typo?

**Comment by cpeterso** [comment]
This bug fix should be in tomorrow's Fenix Beta 106.0b6 build.

**Comment by SoftVision-LorandJanos** [comment]
This issue is no longer reproducible on the latest Beta (106.0b3).
Device used: Google Pixel 4 (Android 12).
Closing the ticket as verified.
