### ISSUE TITLE
[Bug]: Can't paste non url text when url bar is empty

### ISSUE THREAD

**Issue by Timshel** [mozilla-mobile/fenix#27182]
### Steps to reproduce

1. Select some text to copy
2. Ensure that the url is empty
3. Ensure that the you are not editing the url bar field (keyboard is closed)
4. Long press on the url bar
5. If activated the phone will vribrate

### Expected behaviour

The paste option should appear.

### Actual behaviour

Nothing is displayed, you can't paste.

### Device name

Google Pixel 4a (5G) on CalyxOS

### Android version

Android 12

### Firefox release type

Firefox

### Firefox version

105.1.0

### Additional information

I don't know if initially the feature was supposed to support only url but I believe this is confusing / a bug because : 

1. The field combine search and urlbar and is labelled : `Search or enter address` 
2. If there is already an url then both option appear :  `Copy` and `Paste`
3. The phone give a vibrating feedback (an OS notification might appear #26564) but there is no change visible to the user.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21676)

**Comment by jonalmeida** [comment]
We are intentional with _not_ pasting from the clipboard if the contents are not a URL because it has security implications, if I recall correctly. This is in keeping with other browsers as well.

**Comment by Timshel** [comment]
@jonalmeida could you give more details on the security implications ? 

Because I find it surprising since : 
 - As I mentioned if there is text in the urlbar then it's possible to paste, is this a bug ? or is there different security concerns if we already have an url present ?
 - If I select the url bar itself then it's possible to paste since the handling is done by the OS I believe

**Comment by Mugurell** [comment]
Work around this was done in https://github.com/mozilla-mobile/fenix/issues/22271. Maybe @Amejia481 has more context.

**Comment by Timshel** [comment]
It appears at the time the `Paste` option was available only when there was an url but later on in https://github.com/mozilla-mobile/fenix/pull/24294 it was made possible to paste non-url content.

**Comment by Timshel** [comment]
Since I rewrote a significant part of the logic when fixing #26564 i included it in https://github.com/mozilla-mobile/fenix/pull/27351

**Comment by Amejia481** [comment]
> Work around this was done in #22271. Maybe @Amejia481 has more context.

👋🏽 
Sorry, I don't have context around this bug 😅 , the work on #22271 was more to address an issue on Android 12.

**Comment by jonalmeida** [comment]
> If I select the url bar itself then it's possible to paste since the handling is done by the OS I believe

Correct. We want to be careful about what we hint to the user should be copied to the clipboard. There are more nuanced reasons that the security team has more details on.

In general, we want to hint to our users to paste a URL because we can evaluate that safely and not recommend that they paste anything in their clipboard which might end up being a password or login details.

**Comment by Timshel** [comment]
Hi,  as I mentioned I would be interested in those details :). I can understand being cautious about the clipboard if we were in the context of a login/password form but it's not the case here.

Unless I misunderstood, the point of this functionality is to facilitate interaction with the awesome bar. The bar itself is named  `Search or enter address` and when selected allow to paste any content. With the `Search` part being mentioned first not supporting pasting non-url would seem a strange ux choice that as I user I do not understand.

Additionally the bug is not about adding the paste feature it's already present, it's about it not being possible when the field is empty. For security I see no reason for the differentiation and from an ux point of view it's even less understandable. 

From what I can see :
 - allowing to paste was initially supported https://github.com/mozilla-mobile/fenix/commit/0f0aee5e9749f0941ca896f3dc86b2ff35c5c6b8 
 - changed introduced in https://github.com/mozilla-mobile/fenix/commit/94a543a4032feac18a90e3d1449587631a9595fe made it available only for url but I see no mention of security reason in the associated issue https://github.com/mozilla-mobile/fenix/issues/22271 and the author @Amejia481 do not recall any.
 - Allowing pasting non-url text was brought back in https://github.com/mozilla-mobile/fenix/pull/24294 there is no mention of a specific requirement to paste only if the field is non empty, I believe the case was just missed and the short circuit `if (!copyVisible && clipboardUrl == null) return` which prevent it was not modified.

**Comment by Timshel** [comment]
Hey,
I would be interested on some feedback on my latest comment and the associated PR I created :).

**Comment by Timshel** [comment]
Ping

**Comment by Timshel** [comment]
Ping

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1810044

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Comment by cpeterso** [comment]
QA is not needed.
