### ISSUE TITLE
Menu item for adding link to launcher is not available when website provides an app

### ISSUE THREAD

**Issue by keynlotepan** [mozilla-mobile/fenix#27195]
Affected use case:
I would like to add a bookmark to a web page from FF to my Android launcher.

Observed behavior:
In situations where the currently loaded web site provides an app, the menu item for adding a link to the Android launcher (German: "Zum Startbildschirm hinzufügen") is not available, but replaced by an item for installing and linking the app (German: "Installieren"). 

Consequence:
Therefore it is not possible to bookmark such pages. A problem that arises from this is, that the provided app has quite different content and behavior than the page I wanted to bookmark, furthermore no URL input field exists in such apps.

Example URL:
https://www.wetteronline.de/regenradar?wrx=48.08,11.57&wrm=10

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21679)

**Comment by kbrosnan** [comment]
Duplicate https://github.com/mozilla-mobile/fenix/issues/15450
