### ISSUE TITLE
Image download fails on three.co.uk

### ISSUE THREAD

**Issue by Frivolous2** [mozilla-mobile/fenix#27198]
### Steps to reproduce

1. Go to https://www.three.co.uk/static/images/hBBJourney/banners/Existing_Customer_Desk_1x.jpg
2. Long press on image
3. Tap "Save image"

### Expected behaviour

The image is downloaded

### Actual behaviour

"Download failed"

### Device name

Samsung A52s on Android 12; S3 Neo on Lineage 19.1

### Android version

see above

### Firefox release type

Firefox

### Firefox version

105.1.0

### Additional information

The issue occurs on a clean install as well.  It doesn't occur on Samsung Internet

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21681)

**Comment by AdinaPetridean** [comment]
@Frivolous2 thank you for your report! I reproduced this issue on Firefox 105.1.0 and Firefox Nightly 107.0a1- 9/28 with Xperia 10 (Android 12).

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813874

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
