### ISSUE TITLE
[Bug]: pages reload after minimizing app

### ISSUE THREAD

**Issue by lordbob75** [mozilla-mobile/fenix#27208]
### Steps to reproduce

It doesn't happen everytime. 

Open Firefox Mobile and go to a website, wait for it to load.
Switch to a different app in Android without closing Firefox. 
Wait some time. Sometimes it's immediate, other times it takes longer. 
Switch back to Firefox, all open tabs are reloading as if you had closed the app and restarted it.

### Expected behaviour

Firefox maximizes back to your open and loaded tabs.  No reloading required.

### Actual behaviour

All tabs reload as if the app was closed instead of minimized.

### Device name

pixel 4

### Android version

Android 13

### Firefox release type

Firefox

### Firefox version

105.1.0

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21686)

**Comment by csadilek** [comment]
Thanks for filing. We're tracking this work in https://bugzilla.mozilla.org/show_bug.cgi?id=1752594.
