### ISSUE TITLE
Grey highlight on toolbar menu add button

### ISSUE THREAD

**Issue by Alexandru2909** [mozilla-mobile/fenix#27217]
### Steps to reproduce

1. Sign in on Fenix
2. Navigate to any non-bookmarked page
3. Click the three dot button from the toolbar
4. Observe the toolbar menu

### Expected behaviour

The toolbar menu should open, with no highlight.

### Actual behaviour

The toolbar menu opens and the `⭐ Add` button has a grey highlight on the end for a short time.

### Device name

Motorola Edge 30

### Android version

Android 12

### Firefox release type

Firefox Beta

### Firefox version

106.0b2

### Additional information

https://user-images.githubusercontent.com/35462038/192991859-d1740647-eb53-4ac3-b311-193831ab54b6.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21691)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1809250

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
