### ISSUE TITLE
FNX3-16532 ⁃ [Bug] [Onboarding] Automatic radio button isn't selected when tapped

### ISSUE THREAD

**Issue by softvision-miralobontiu** [mozilla-mobile/fenix#2721]
## Steps to reproduce
1. Install the latest build of Firefox Preview.
1. Scroll to "Choose your theme".
1. Tap on "Dark Theme", then on "Automatic".

### Expected behavior
The theme is darkened, then adapts to your device, and the "Automatic" radio button is checked.

### Actual behavior
The "Automatic" radio button is not checked but works as expected. A second tap resolves the problem. 

### Device information
* Android devices: Sony Xperia Z2 tablet (Android 6.0.1), HTC 10 (Android 8), Sony Xperia Z5 Premium (Android 7.1.1).
* Fenix version: 1.0.1921 (#11420606)

### Notes
Not reproducible on Android 9.
Not reproducible if "Automatic" is tapped after "Light Theme".

![2019](https://user-images.githubusercontent.com/40694158/58154441-45c67880-7c7a-11e9-8ac3-96321806c708.gif)UNITO-UNDERSCORE!05!UNITO-UNDERSCORE!22!

**Comment by ekager** [comment]
This should have been fixed by #2817 and unblock #2389, adding QA Needed for verification

**Comment by softvision-miralobontiu** [comment]
Verified as fixed on the latest build 1.0.1922 (#11490609), with Nexus 6P (Android 8.1.0), and Sony Xperia Z5 Premium (Android 7.1.1).
