### ISSUE TITLE
[Improvement]: Make the new onoarding screen swipeable or remove the 2 dots at the bottom

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#27219]
### Steps to reproduce

This is just a suggestion to improve the 2 new onboarding screens.
The onboarding dialog for upgrading users has 2 dots at the bottom of the screen, which usually make you think the screen is swipeable, but it turns out that it's not. 
For a smoother user experience I would recommend to either remove the dots or make the dialog a slide.
![image](https://user-images.githubusercontent.com/4037709/193024396-0287a6ec-f8ce-4f7b-8c4e-b756cb3329ea.png)

### Expected behaviour

As a user, I have developed some automatisms and expect the apps to behave uniformly.

### Actual behaviour

Trying to swipe on the dialog screens without success.

### Android version

any

### Firefox release type

Firefox Beta

### Firefox version

106

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21692)

**Comment by gabrielluong** [comment]
I worked with Kate and we made the decision during the implementation to not make this swipeable. Closing as WONTFIX. We're willing to revisit this in the future if there are more improvements necessary for the onboarding screen.
