### ISSUE TITLE
uBlock Origin: Importing does not work.

### ISSUE THREAD

**Issue by rahaaatul** [mozilla-mobile/fenix#27216]
### Steps to reproduce

- Open uBlock Origin Extension.
- Tap `Restore from file` button and import a backup file of uBo.
- Wait for it to import.
- Wait forever.

### Expected behaviour

- Should import the backups.
- Should not lag/stutter, while Importing.

### Actual behaviour

- Doesn't import backup.
- Stuck/hang/lags after Importing a backup file.

### Device name

Vivo Y20 2021

### Android version

Android 11

### Firefox release type

Firefox

### Firefox version

105.1.0 (Build #1051020)

### Device logs

No crash reports found in `About > Crashes`.

### Additional information

Oh, last time I tried to import and directly went to `about > crashes` to see if there's any crash reports but there was none, but then I exited from there and it take me directly to feneec home, and the uBlock page crashed.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21690)

**Comment by LaurentiuApahideanSV** [comment]
I can confirm the issue is reproducible on Fenix Nightly 107.0a1 (2022-10-05).
### Device used:
- Google Pixel 6 (Android 13)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812408

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
