### ISSUE TITLE
Firefox Android Remote Debugger Port Forwarding Fails

### ISSUE THREAD

**Issue by aquaductape** [mozilla-mobile/fenix#27215]
### Steps to reproduce

1. Open Firefox Nightly on Desktop (I use MacOS Monterey v12.6).
2. Open Firefox Nightly on Android device
3. On Android, enable `Remote debugging via USB` through Firefox browser settings
4. On Desktop Firefox, Enable USB Devices on `about:debugging#/setup` page
5. On Desktop Firefox, Connect device by clicking "Connect" button on device item (has smartphone icon, appears after connecting Android via USB and accepting RSA fingerprint)
6. On Desktop Firefox, Add `localhost:3000` on Network location under `about:debugging#/setup`
7. On Desktop Firefox, forward and connect localhost:3000 by clicking "Connect" button on `localhost:3000` item.

With `adb`
1. Open Firefox Nightly on Desktop (I use MacOS Monterey v12.6).
2. Open Firefox Nightly on Android device
3. On Android, enable `Remote debugging via USB` through Firefox browser settings
4. On Desktop Firefox, Enable USB Devices on `about:debugging#/setup` page
5. On Desktop Firefox, Connect device by clicking "Connect" button on device item (has smartphone icon, appears after connecting Android via USB and accepting RSA fingerprint)
6. On Desktop Firefox, Add `localhost:3000` on Network location under `about:debugging#/setup`
7. Open terminal and run adb command `adb forward tcp:6000 tcp:6000`
8. On Desktop Firefox, forward and connect localhost:3000 by clicking "Connect" button on `localhost:3000` item.

### Expected behaviour

For forwarding `localhost:3000` to work, when accessing `localhost:3000` page on Android device it should connect to Desktop localhost.

### Actual behaviour

On about:debugging#/setup, after clicking "Connect" button on `localhost:3000` item. After a couple seconds, a warning message is shown `Connection still pending, check for messages on the target browser`. Then after a couple seconds, warning message is replaced with error message `Connection timed out error`

### Device name

Galaxy S10e

### Android version

Android 12

### Firefox release type

Firefox Nightly

### Firefox version

107.0a1

### Additional information

I'm able to connect and interact pages on desktop Firefox from Firefox Android device.

However I'm not able to forward port (such as localhost:3000) to Firefox Android device.

I'm sure this is Android Firefox issue because I'm able remote debug Android Chrome and able to forward port (localhost:3000) to Android Chrome

adb version
```
Android Debug Bridge version 1.0.41
Version 33.0.3-8952118
Installed as /opt/homebrew/bin/adb
```
Desktop Firefox Nightly version
```
107.0a1 (2022-09-28) (64-bit)
```
<img width="775" alt="Screen Shot 2022-09-28 at 7 25 05 PM" src="https://user-images.githubusercontent.com/29286430/192941216-ca69cd17-6c43-4e65-b28a-242dc1542b0d.png">

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21689)

**Comment by kbrosnan** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1811879

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
