### ISSUE TITLE
FNX3-16533 ⁃ [Bug] Pages opened in new tabs have no favicon until they are active and fully loaded.

### ISSUE THREAD

**Issue by Lululalu** [mozilla-mobile/fenix#2722]
## Steps to reproduce
Go to theguardian.com
Open some news in new tabs

### Expected behavior
New tabs are shown with the same favicon as the home page.

### Actual behavior
New tabs don't have any favicon. The favicon is only loaded after switching to the tab. 
![Screenshot](https://user-images.githubusercontent.com/32398857/58154555-46461b80-7c48-11e9-996a-e38b324ca958.jpg)UNITO-UNDERSCORE!20190521-223109!UNITO-UNDERSCORE!Firefox Preview!

### Device information
* Android device: Galaxy A5 2017 8.0
* Fenix version: 1.0.1921

**Comment by NotWoods** [comment]
Potentially needs GeckoView to load the icons extension in the background.

**Comment by ekager** [comment]
I'm not reproducing this anymore and possibly fixed by #5808 (and related). Let's test and close if fixed

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **Nightly build #12880607 from 15/10** using the following devices:
• Google Pixel 3a (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

► Normal browsing
![20191015_151014](https://user-images.githubusercontent.com/51314259/66833323-48e13e80-ef64-11e9-916b-fafab109acbf.gif)

► Private browsing
![20191015_155101](https://user-images.githubusercontent.com/51314259/66833394-6f06de80-ef64-11e9-8e4f-588e571a128c.gif)

#### Notes:
Checked the following websites:
https://www.theguardian.com
https://www.theverge.com
https://www.espn.com
