### ISSUE TITLE
PWA & Custom Tabs: Status bar & Navigation Bar issue

### ISSUE THREAD

**Issue by rahaaatul** [mozilla-mobile/fenix#27221]
### Steps to reproduce

For PWA apps: (Could be any website, I'm choosing Twitter)
- Go to twitter.com.
- Tap 3 dot menu > Tap install.
- Open PWA Twitter app
- Observe.

For custom Tabs:
- Open links with Firefox browsers.
- Observe.

### Expected behaviour

Status Bar's & Navigation Bar's color should complement or sync with website's color.

### Actual behaviour

Status bar color is white all the time. Navigation Bar color isn't synced with website's color, it's default browser color and looks mismatched.
PWA app:
![Screenshot_20220929_194636](https://user-images.githubusercontent.com/86149861/193050097-3d2cdfaf-f766-41c3-bd29-073e192139d8.jpg)
Custom Tab:
![Screenshot_20220929_195649](https://user-images.githubusercontent.com/86149861/193052068-2b35a73b-e67e-4201-aa94-2201dce1b1bf.jpg)

### Device name

Vivo Y20 2021

### Android version

Android 11

### Firefox release type

Firefox

### Firefox version

105.1.0

### Device logs

No crash logs.

### Additional information

Default browsing experience isn't syncing with website's color:
![Screenshot_2022_0929_195449](https://user-images.githubusercontent.com/86149861/193050828-6b1660c3-c72c-478f-9618-a9d714b7b1a1.jpg)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21694)

**Comment by AdinaPetridean** [comment]
@rahaaatul thank you for your report! I was able to reproduce this issue on Firefox Nightly 107.0a1- 13/10 with moto g(9) plus (Android 11) and on Firefox 106.0b5.

**Comment by makotokato** [comment]
There is already same report such as https://github.com/mozilla-mobile/fenix/issues/22988 and etc. 
@iorgamgabriel is working on this on https://bugzilla.mozilla.org/show_bug.cgi?id=1795650.

But I guess that this is a bug of custom tab of Android framework with night mode.

**Comment by rahaaatul** [comment]
> But I guess that this is a bug of custom tab of Android framework with night mode.

Have you tried in chrome? I tried and It's black in dark mode, and white in white mode. It's Firefox problem.

**Comment by makotokato** [comment]
> Have you tried in chrome? I

Chrome doesn't set status bar is white with dark mode even if `theme_color` in `manifest.json` is white. I tested on Pixel 6a + Android 13.

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813875

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
