### ISSUE TITLE
[a11y] Focus jumps after interacting with items on homescreen

### ISSUE THREAD

**Issue by Mugurell** [mozilla-mobile/fenix#27230]
Scenarios:
- after interacting with a collection or the last tab from "Jump back in" focus jumps to the private browsing button
- after interacting with the last item from "Recently visited" focus jumpts to the toolbar

https://user-images.githubusercontent.com/11428869/193288616-db0b9c68-a8e9-415b-9a0d-55c5d684b918.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21698)

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1809813

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
