### ISSUE TITLE
[Bug]: Text size on some pages varies unexpectedly

### ISSUE THREAD

**Issue by bjherbison** [mozilla-mobile/fenix#27233]
### Steps to reproduce

1. Visit https://www.ibras.dk/montypython/episode14.htm on Android and Desktop.
2. Compare the size of text in various elements.

### Expected behaviour

Text with similar font sizes should be displayed the same size.
From Desktop:
![image](https://user-images.githubusercontent.com/4101902/193340610-f69f3f9d-d40f-49df-a4c4-ade614b0ad15.png)

### Actual behaviour

Some text is small and some is large. Note the purple, green, and black text is the same size on desktop, but the purple and some of the black is smaller on Android.
![Screenshot_20220930-122842](https://user-images.githubusercontent.com/4101902/193340523-1a201c13-f64a-43c5-8a26-378ef5536922.png)

### Device name

Google Pixel 6 Pro

### Android version

Android 13

### Firefox release type

Firefox Nightly

### Firefox version

94.2.1

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21699)

**Comment by kbrosnan** [comment]
Duplicate bz-786382. Better would be for the website to add `<meta name="viewport" content="width=device-width, initial-scale=1">`
