### ISSUE TITLE
Hold to open tab history item in duplicated tab

### ISSUE THREAD

**Issue by fice-t** [mozilla-mobile/fenix#27245]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### What is the user problem or growth opportunity you want to see solved?
A missing feature in Fenix that is present in desktop Firefox is the ability to open a tab history item in a new tab while preserving the tab history (i.e., duplicating the tab and navigating to the tab history URL).

This is accomplished on desktop by middle-clicking the tab history item, so on mobile the natural action is a hold event ("long click") on the tab history item.

### How do you know that this problem exists today? Why is this important?
This functionality is missing entirely in Fenix. Workflows that "branch" into new tabs frequently would be improved by having the tab history stack along with each tab, as described in #9956. This generalizes that issue by allowing the duplicated tab to start in a different history index than the current tab.

### Who will benefit from it?
As described in #9956 and above, various workflows would benefit from this, and this is a feature that is present in desktop Firefox that users may expect in the mobile version.

I've already implemented this and will link the PR shortly.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21707)

**Comment by gabrielluong** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1815636

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
