### ISSUE TITLE
Click events on SVG text nodes not working for touch

### ISSUE THREAD

**Issue by not-implemented** [mozilla-mobile/fenix#27244]
With the given example below, I would expect, that the ".container" receives click events regardless if I touch anywhere on the circle or directly on the text. But the click event is **only fired when NOT hitting the text.**

When uncommenting the second circle on top of the text, ".container" also receives click events for that inner circle (on touch-devices and with a mouse). So it seems to be a "text" specific issue.

Uncommenting the ".container .text" click handler shows that the text node does not receive click events at all on Firefox Mobile.

This seems to be a bug in Firefox Mobile. In Firefox Desktop (and in Chrome) this works as expected – regardless if using a touch device or a mouse.

I also noticed click-events on the text node when I touch anywhere completely outside of the circle ... but I can not reproduce this currently ... anyway it may be a hint, that the whole problem may be an offset/translate/coordinate issue?

```html
<!DOCTYPE html>

<svg viewBox="0 0 10 10" style="width: 600px">
    <g class="container">
        <circle cy="5" cx="5" r="5"/>
        <text class="text" x="0.7" y="6">TEXT</text>
        <!--<circle cy="5" cx="5" r="2" fill="#7f3f3f"/>-->
    </g>
</svg>

<style>
    .container {
        cursor: pointer;
        pointer-events: visiblePainted;
        fill: #3cad3c;
    }
    .text {
        font: bold 3px sans-serif;
        fill: #187e97;
    }
</style>

<script>
    document.querySelector('.container').addEventListener('click', (event) => {
        alert('container click');
    });
    /*
    document.querySelector('.container .text').addEventListener('click', (event) => {
        alert('text click');
    });
    */
</script>
```

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21706)

**Comment by makotokato** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1798303

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
