### ISSUE TITLE
[Bug] Privacy Policy tab stays in the background as a second app instance

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#2724]
## Steps to reproduce
1. Go to Settings>Privacy  Policy
1. Press back to return to the app homescreen.
1. View the task manager.
    1. Expected behavior
One Fenix window.
    1. Actual behavior
Two Fenix tasks running, one with the preview of the Privacy policy page. When you tap to open it, it will show just a blank page.
    1. Device information

* Android device: Galaxy Note 8(Android 9), P9 lite (Android 6)
* Fenix version: build 5/22
![20190522](https://user-images.githubusercontent.com/4037709/58155527-b7072b00-7c7c-11e9-842c-af226fffb776.gif)UNITO-UNDERSCORE!102915!

**Comment by boek** [comment]
Can you still reproduce this?

**Comment by vesta0** [comment]
Fixed.

**Comment by sv-ohorvath** [comment]
Yes, verified it's fixed.
