### ISSUE TITLE
Cannot search for addons

### ISSUE THREAD

**Issue by sryze** [mozilla-mobile/fenix#27249]
### Steps to reproduce

1. Open Addons menu
2. Try to search

### Expected behaviour

Expected to see a search bar or another way to find addons.

### Actual behaviour

The addon search function is missing. I can only install addons from the "recommended" list.

### Android version

11

### Firefox release type

Firefox

### Firefox version

105.1.0

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21708)

**Comment by gabrielluong** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813984

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
