### ISSUE TITLE
[Bug][a11y] "Double tap to link" Talkback readout in private mode

### ISSUE THREAD

**Issue by Mugurell** [mozilla-mobile/fenix#27252]
STRs:
- Have Talkback enabled
- Enter private mode
- Focus "Common myths about private browsing"

Actual:
- Talkback reads "Common myths about private browsing. Double tap to link".

Expected:
- UX input needed.

The action here is not "link" but maybe "open link to learn more" / "open documentation"?

https://user-images.githubusercontent.com/11428869/193542868-0663fc2f-60d1-4e8b-ad96-71815e70a9a4.mov

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21709)

**Comment by mcarare** [comment]
The text used for describing the action was previously used as defining the `role`, not the `action`, so I would say, currently, this is incorrectly used.

**Comment by ewachowiak** [comment]
@Mugurell I'm not super familiar with Talkback so I have a few questions. 

- It appears to me that "Common myths about private browsing" IS a link. It is a link to a support article. My hypothesis is that the word "open" was left out of the talkback text on accident.
-  Is it standard for Talkback to read the name of the link first before describing the available action to open it? I would assume the user would need to know that the text was a link before reading it. For example "Link: Common myths about private browsing. Double tap to open link."
- If the above is not true, I recommend updating the text to "Double tap to read the article."

**Comment by Mugurell** [comment]
> @Mugurell I'm not super familiar with Talkback so I have a few questions.
>  Is it standard for Talkback to read the name of the link first before describing the available action to open it? I would assume the user would need to know that the text was a link before reading it. For example "Link: Common myths about private browsing. Double tap to open link."

The standard is for TalkBack to read the content description and then the role of the widget.
Here hat was initially read was: "Common myths about private browsing, link. Double-tap to activate"
Seems like Jetpack Compose doesn't yet support a "Link" role - https://cs.android.com/androidx/platform/frameworks/support/+/androidx-main:compose/ui/ui/src/commonMain/kotlin/androidx/compose/ui/semantics/SemanticsProperties.kt;l=558-597?q=object%20SemanticsProperties%20 so we'll have to do without it.

>  If the above is not true, I recommend updating the text to "Double tap to read the article."

"Common myths about private browsing. Double-tap to read the article" is doable, thank you!

**Comment by ewachowiak** [comment]
Thanks @Mugurell. That sounds good to me!

**Comment by lime124** [comment]
@kbrosnan FYI this is really to be pulled into a sprint to fix. Thanks!

**Comment by SoftVision-LorandJanos** [comment]
Verified as fixed in the latest Nightly 108.0a1 (2022-11-07).
Talkback now reads: "Common myths about private browsing. Double-tap to read the article"
Device used: Oppo Find X5 (Android 12).
Closing the ticket as verified.

**Comment by SoftVision-LorandJanos** [comment]
Verified on the latest Beta 108.0b1.
Device used: Google Pixel 4 (Android 13).
