### ISSUE TITLE
Unable to save image if URL points directly to an .svg file

### ISSUE THREAD

**Issue by 40105** [mozilla-mobile/fenix#27258]
### Steps to reproduce

If you long press on an image, a menu opens where you can save (and share etc.) the image. This menu is not displayed if you open an image file saved as .svg directly (example url: https://upload.wikimedia.org/wikipedia/commons/d/d7/Scalable_Vector_Graphics_Ellipse2.svg ) and try to apply a long press to the image.
(If I am e.g. open a .png image directly or the .svg image is embedded in a website the menu will shows up.)

### Expected behaviour

I am able to save the image.

### Actual behaviour

The menu does not appear.

### Android version

Android 11

### Firefox release type

Firefox

### Firefox version

105.1.0

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21714)

**Comment by SoftVision-LorandJanos** [comment]
Hi @40105 ! Thanks for your report!
I managed to reproduce your issue on the latest builds: Nightly 108.0a1 (2022-10-27), Beta 107.0b3 and RC 106.1.0.
Tested on desktop as well where there is no option to save it as image file.
Also reproducible on Chrome mobile and desktop.

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812775

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
