### ISSUE TITLE
browser.tabs.create does not get the focus

### ISSUE THREAD

**Issue by chrmod** [mozilla-mobile/fenix#27263]
When creating an active tab with `browser.tabs.create` the tab gets created in the background instead of showing the browser windows.

Examples:
* when created while Home screen is shown, the tab gets listed in "Jump back in" but does not open 
* when created while Browser Action screen is shown, the tab opens in the background but the Browser Action is still shown

Expected behavior:
When an active tab is created by a webextension, Fenix should navigate to the browser fragment regardless which fragment is currently being shown (`navController.navigate(R.id.browserFragment)`).

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21715)

**Comment by chrmod** [comment]
I imagine there could be a selectedtab observer - something like this:
```kotlin
consumeFlow(store) { flow ->
  flow.map { state -> state.selectedTab?.content?.url }
    .ifChanged()
    .collect { url ->
      if (url != null && url.startsWith("moz-extension://")) {
        findNavController().navigate(R.id.browserFragment)
      }
    }
}
```

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1810841

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
