### ISSUE TITLE
FNX3-16537 ⁃ [Bug][Onboarding] "Start browsing" button must be double tapped to respond

### ISSUE THREAD

**Issue by softvision-miralobontiu** [mozilla-mobile/fenix#2726]
Prerequisites: Make sure it's a clean profile.

## Steps to reproduce
1. Go to "Start browsing" button, at the end of the onboarding tour.
1. Tap on it.

### Expected behavior
The onboarding tour should be dismissed.

### Actual behavior
Nothing happens. You have to double tap it. 

### Device information
* Android devices: Sony Xperia Z5 Premium (Android 7.1.1), Samsung Galaxy Note 8 (Android 9), Nexus 5 (Android 6.0.1).
* Fenix version: 1.0.1921 (#11420606)

### Note
Not reproducible on Sony Xperia Z2 tablet (Android 6.0.1), OnePlus 5T (Android 9)

**Comment by ekager** [comment]
Related to https://github.com/mozilla-mobile/fenix/issues/1454 ?

**Comment by boek** [comment]
@ekager yes

**Comment by bifleming** [comment]
@boek what is blocking this one?

**Comment by ekager** [comment]
It is a google bug see #1454

**Comment by bifleming** [comment]
@vesta0 what do you want to do with this one? Not something we can fix.

**Comment by boek** [comment]
It’s actually a dup of #1454, we don’t need both tickets open

**Comment by abodea** [comment]
Verified as fixed on the latest RC build **`1.0.0-rc.2(Build #11700147 68.0.20190611143747) 6/19.`** with Samsung Galaxy Note 9(Android 8.1.0).
