### ISSUE TITLE
Draw edge-to-edge content behind the status and navigation bars when scrolling

### ISSUE THREAD

**Issue by l3s2d** [mozilla-mobile/fenix#27274]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### What is the user problem or growth opportunity you want to see solved?

It would be great if Firefox could draw content behind the status and navigation bars when scrolling.

https://developer.android.com/develop/ui/views/layout/edge-to-edge

There are some examples of apps that hide one or both bars listed in this Reddit thread: https://www.reddit.com/r/Android/comments/i8rr6u/edge_to_edge_apps/

Implementation ideas:

The navigation bar should never be visible unless the bottom of the page is reached.

The status bar is trickier but I quite like the implementation in Infinity for Reddit, where the status bar is shown when scrolling down.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21719)

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813454

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
