### ISSUE TITLE
[Bug]: Autoplay blocking does not work on <video onload="this.play();" controls autoplay muted loop>

### ISSUE THREAD

**Issue by vinc17fr** [mozilla-mobile/fenix#27270]
### Steps to reproduce

1. Make sure that Settings → Site permissions → Autoplay has "Block audio and video" (without an exception for the site).
2. Open https://stackoverflow.com/q/64951616/3782797
3. Click on "Run code snippet".

Note: the code is
```
<video  onload="this.play();" controls autoplay muted loop>
  <source src="https://storage.googleapis.com/web-dev-assets/video-and-source-tags/chrome.webm" type="video/webm">
  <source src="https://storage.googleapis.com/web-dev-assets/video-and-source-tags/chrome.mp4" type="video/mp4">
  <p>Your browser cannot play the provided video file.</p>
</video>
```

### Expected behaviour

The video should be blocked.

### Actual behaviour

The video is played.

Note: I could check by tapping on the lock (left part of the address bar) that Autoplay is set to "Block audio and video" as expected.

### Device name

Samsung Galaxy Note10+

### Android version

Android 12

### Firefox release type

Firefox Beta

### Firefox version

106.0b3

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21718)

**Comment by kbrosnan** [comment]
I see the same behavior in desktop Firefox and Edge with (edge://flags show autoplay) with autoplay set to block audio/video.

**Comment by kbrosnan** [comment]
As designed. Autoplay is allowed if the user interacts with the page.

**Comment by vinc17fr** [comment]
With desktop Firefox (Linux), I can see that the video doesn't play: after clicking on "Run code snippet", I need to click on the video to play it. So what is said above is incorrect.

I don't know what you mean by "the user interacts with the page", but quite often, the user will interact with pages he opens, e.g. for copying contents or opening links in the background. This does not mean that the user wants to play videos.

Autoplay blocking seems to work quite well on desktop Firefox. Why not allowing the same behavior for Android?
