### ISSUE TITLE
[Experiment] The Existing Users onboarding is displayed after unenrolling from the Control branch of the Existing Users experiment

### ISSUE THREAD

**Issue by heres-maria-sv-inactive** [mozilla-mobile/fenix#27279]
**[Affected Versions]:**
- Firefox Nightly 107.0a1 (Build #2015908011), 49791c377+, AC: 107.0.20221004145201, 38287358b3, GV: 107.0a1-20221004094418, AS: 94.2.0
- Firefox Beta 106.0b4 (Build #2015907731), 4560430cd+, AC: 106.0.3, 8a0edee7d9 GV: 106.0-2022100218507 AS: 94.2.1

**[Affected Platforms]:**
- Android 9 - Samsung Galaxy S8

**[Prerequisites]:**
- Have Firefox 105 installed  (e.g. [this ftp build](https://ftp.mozilla.org/pub/fenix/nightly/2022/08/2022-08-22-17-03-32-fenix-105.0b1-android-arm64-v8a/)).
- If using Nightly, have the build installed >6 days ago (to avoid enrolling in the New Users experiment when unenrolling from the Existing Users experiment) - can be done by changing the device date and time.
- Be enrolled in the Control branch of the [[QA] Firefox Android Nightly MR Existing User Onboarding](https://experimenter.services.mozilla.com/nimbus/qa-firefox-android-nightly-mr-existing-user-onboarding) Prod Preview experiment (using the debug menu).

**[Steps to reproduce]:**
1. Update the Firefox build to version 106 or 107 (e.g. [this ftp build](https://ftp.mozilla.org/pub/fenix/nightly/2022/10/2022-10-05-05-01-00-fenix-107.0b1-android-arm64-v8a/)) by installing a new build over the old one.
2. Open Firefox.
3. Go to Settings > Data collection > Studies and unenroll from the study using the Remove button.
4. Restart the browser.
5. Observe the page displayed at the next startup.

**[Expected result]:**
- The Onboarding is not displayed after unenrolling from the experiment.

**[Actual result]:**
- The Onboarding is displayed after unenrolling from the Control branch.

**[Notes]:**
- This issue is also reproducible when disabling all studies or data collection.
- This issue is not reproducible for the Treatment A branch.
- Attached is a recording of the issue.

https://user-images.githubusercontent.com/53752296/194090368-c20df6ee-81fc-43ec-a025-840028056651.mov

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21720)

**Comment by Amejia481** [comment]
Thanks for filing this ticket @heres-maria! 
I think this is the expected result, please help me to clarify if I'm wrong.

Based on what we [have here](https://github.com/mozilla-mobile/fenix/blob/e81da189cd8097551026ab34eeb0d22292e3564f/nimbus.fml.yaml#L192), we defined that for existing users that are not enrolled in any experiments, they should see by default the Existing Users onboarding.

**Comment by heres-maria** [comment]
@Amejia481 The onboarding being displayed at a startup other than the first startup after an update seemed unusual (the CFRs are also displayed after users unenroll from the control branch). The iOS and desktop platforms display a different behavior, so this issue was logged based on this Android control branch being an outlier. 
Should this issue be closed as invalid?

**Comment by Amejia481** [comment]
Thanks for keeping an eye opened :slightly_smiling_face: . It think is OK to close it. Please feel free to re-open if needed!

**Comment by Amejia481** [comment]
Just to add some extra details to https://github.com/mozilla-mobile/fenix/issues/27279#issuecomment-1270637818, we made the features visible by default to make sure anyone that is not in-rolled into the experiments we will able to have the new functionality.

**Comment by cpeterso** [comment]
I don't know the expected behavior on desktop and iOS, but I think you are seeing the expected behavior on Android. We want to show the MR onboarding to all existing users so when existing users in the control branch unenroll from the experiment, they should then see the MR onboarding.
