### ISSUE TITLE
Wallpapers list should be cached to avoid blank settings page.

### ISSUE THREAD

**Issue by MatthewTighe** [mozilla-mobile/fenix#27283]
We aren't currently caching the list of wallpapers to disk. This means that network errors during app startup will cause the wallpaper list to be blank in the wallpaper settings page. This can be reproduced by starting the app with data and wifi turned off.

If we cache the list of wallpapers, we can use it as a fallback in the event of network failures. We may also look to add automatic retries to the fetching of metadata, which may be something to consider during the implementation of this. It may be worth waiting to do this until after https://github.com/mozilla-mobile/fenix/issues/26033

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21723)

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1809801

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
