### ISSUE TITLE
Remove glean test rule and Android test runner from `WallpaperUseCasesTest`

### ISSUE THREAD

**Issue by MatthewTighe** [mozilla-mobile/fenix#27288]
Now that metrics have been moved out of the use cases, we can remove the glean test rule from `WallpaperUseCasesTest`. This should also mean that we can stop running the class with the Android test runner and should result in significantly faster test startups.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21726)

**Comment by mbaimuratov** [comment]
This should be addressed in #27379

**Comment by MatthewTighe** [comment]
Hey there, thanks for helping out! We typically try to address issues in a one-to-one manner in this repo. That is, we would prefer if there was a separate PR to tackle this issue rather than bundling it into https://github.com/mozilla-mobile/fenix/pull/27379, which looks intended to address https://github.com/mozilla-mobile/fenix/issues/27282

**Comment by joc-a** [comment]
I can pick this up
