### ISSUE TITLE
Remove `WallpaperManager`

### ISSUE THREAD

**Issue by MatthewTighe** [mozilla-mobile/fenix#27282]
`WallpaperManager` is a leftover piece of tech debt from Wallpapers v1. It is time to remove it entirely. 

It looks like the only usage of the class is through `WallpaperManager.isDefaultTheCurrentWallpaper`, which can be moved and/or reworked into the companion of `Wallpaper`.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21722)

**Comment by mbaimuratov** [comment]
Can I work on this?

**Comment by MatthewTighe** [comment]
Definitely! Thanks for your contribution 🙂
