### ISSUE TITLE
Clean up coroutine usage in `WallpaperFileManager`

### ISSUE THREAD

**Issue by MatthewTighe** [mozilla-mobile/fenix#27289]
`WallpaperFileManager` ended up with inconsistencies in how coroutines are used, probably as a result of copying functionality from `LegacyWallpaperFileManager` (the v1 version).

Address the following issues:
- the `scope` variable is only used in one place and could be done inline
- the `withContext` calls use an explicit dispatcher instead of the one injected into the class
- `wallpaperImagesExist()` has an unnecessary explicit `return` keyword
- `clean()` does not need to be suspending, it can be launch-and-forget as we do not need to know whether it was successful.

This may require some updates to the tests' setup to get everything to behave correctly.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21727)

**Comment by sum20156** [comment]
@MatthewTighe I have fixed this ...all tests are working fine, should I raise PR

**Comment by MatthewTighe** [comment]
@sum20156 Sure, feel free to post the patch. Thanks for addressing this issue!

**Comment by sum20156** [comment]
@MatthewTighe Done. This is my first commit. I may have made mistakes, please review the PR and share feedback
