### ISSUE TITLE
Extract wallpaper logic from home fragment

### ISSUE THREAD

**Issue by MatthewTighe** [mozilla-mobile/fenix#27286]
See https://github.com/mozilla-mobile/fenix/issues/26555, https://github.com/mozilla-mobile/fenix/pull/26794, https://github.com/mozilla-mobile/fenix/pull/27105, https://github.com/mozilla-mobile/fenix/pull/27204 for some of the context surrounding the issues here.

It would be good to extract the wallpaper logic from the home fragment in order to reduce the fragment size and make the logic easier to test.

There are a couple important things to note here:
- the wallpaper needs to be applied (and various text, button, and card colors updated) before the view is shown to the user in order to avoid perceived flashes in the UI
- changes to the current wallpaper need to be observed from the app store and applied appropriately in case other areas of the app update the state (like the wallpaper onboarding tool or settings page)
- performance should not be degraded for users (though users with a wallpaper set will likely be slower than users without one)

Previously, we had some of this logic extracted into a `WallpaperObserver` class with functions exposed to update the views of the home fragment. Something like that could be a good first step.

Alternatively, we could look into potentially introducing a `WallpaperFeature` that was `ViewBoundFeatureWrapper`. However, that may require additions to that class. It appears to mostly revolve around the `Start` and `Stop` lifecycle events, but `Start` has appeared to be too late to update the view without UI jank.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21724)

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1809800

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
