### ISSUE TITLE
Figure out what to do with AboutLibrariesFragmentTest with oss-licenses-plugin 0.10.5+

### ISSUE THREAD

**Issue by rvandermeulen** [mozilla-mobile/fenix#27287]
I was recently looking at updating various Gradle dependencies to their latest releases and attempted to bump oss-licenses-plugin from the current 0.10.4 version to 0.10.5, but hit failures in AboutLibrariesFragmentTest.
`java.lang.IllegalArgumentException: No item found containing text "org.mozilla.geckoview:geckoview"`

I launched the APK locally to check with the Licenses screen looked like and the reason for the failure became apparent:
![license](https://user-images.githubusercontent.com/3661247/194115887-5c86981e-9002-4381-9bec-c0d45093e719.png)

This appears to be an intentional change made by upstream commit https://github.com/google/play-services-plugins/commit/138a15dc9209192c6a9397b341b0ef7ddc346af4

This is problematic for us because we only run these unit tests on debug builds, so we'd be left with no test coverage if we skipped the failing test and took the newer release. There isn't a pressing need to do so at this time anyway, but we probably do want to give it a think before we end up in a situation where there *is* a more urgent need to update and we're blocked on this.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21725)

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813452

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
