### ISSUE TITLE
Allow users to choose their own custom font (.ttf) in the browser

### ISSUE THREAD

**Issue by Prasanta-Hembram** [mozilla-mobile/fenix#27280]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### What is the user problem or growth opportunity you want to see solved?
* Allow users to be able to choose their own custom font in the Browser.
* By adding this feature users will have more options to customize the browser.
* It may help remove proprietary fonts from the browser.
* Users can select their custom font from the device itself.
* Some new language/other scripts which are released by Unicode org not supported by older devices, maybe by adding this feature solves the problem. 
### How do you know that this problem exists today? Why is this important?
• Everyone loves fonts, and many browsers don't give the option to change the fonts.
• Their are very few like Soul browsers that support this feature where users are able to change their browser fonts by either uploading their own .ttf font file or by selecting fonts from their device.
### Who will benefit from it?
• Benefits many users who wants to customize/change the looks of their browser web content.
• May help those people who just root their device for just changing their system font to customize their browser content looks, which is very dangerous and may brick their device.
• Newly added language scripts such as Warang Citi (used for writing Ho language) script which is supported from Android 11 system onward only, they have lots of web content in the internet. It leaves old Android version users in the dark, and are excluded from taking the benefit to look for the content in their native language. By giving users the option to choose their fonts, they can at least see their content in their native script in the browser.
• It may solve the pending 43 open issues which are related to fonts.

### Here user is given an option to select their own font named ComingSoon.ttf from the system.
![Screenshot_᱒᱐᱒᱒᱑᱐᱐᱕-᱒᱐᱐᱔᱑᱘_Soul](https://user-images.githubusercontent.com/51163799/194092668-795b6adf-d365-49f1-a790-6ebbf22af253.jpg)
### do
![Screenshot_᱒᱐᱒᱒᱑᱐᱐᱕-᱒᱐᱐᱕᱐᱔_Soul](https://user-images.githubusercontent.com/51163799/194092645-1f7ee589-fbb1-4bbb-9b19-f7185eb3dce7.jpg)

### Or User can select their own custom font from their local storage
![Screenshot_᱒᱐᱒᱒᱑᱐᱐᱕-᱒᱐᱐᱔᱕᱐_Soul](https://user-images.githubusercontent.com/51163799/194092674-2d34ec58-53ae-48d6-8ed6-f4b4e83edd9a.jpg)

### After the font applied
![Screenshot_᱒᱐᱒᱒᱑᱐᱐᱕-᱒᱐᱐᱕᱕᱗_Soul](https://user-images.githubusercontent.com/51163799/194092627-01c6ab3f-f041-4066-a1ac-2feaa4c9f493.jpg)

### After the font applied
![Screenshot_᱒᱐᱒᱒᱑᱐᱐᱕-᱒᱐᱐᱕᱓᱑_Soul](https://user-images.githubusercontent.com/51163799/194092657-d2bb2240-eab6-4107-bed8-12967e95e42a.jpg)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21721)

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813453

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
