### ISSUE TITLE
Refactor `DefaultLoadBitmapUseCase` to receive orientation as argument

### ISSUE THREAD

**Issue by MatthewTighe** [mozilla-mobile/fenix#27290]
The `WallpaperUseCases.DefaultLoadBitmapUseCase` currently accepts a `Context` as an argument. It then determines the current device orientation inline in order to load the correct (landscape/portrait) bitmap for a wallpaper. 

By removing the `Context` parameter and replacing it with the orientation, the function should be more testable and maintainable. It is also the only `Context`-dependent part of the updated Use Cases and is a copied holdover from the legacy versions, so it will mean we should be able to completely remove Context from `WallpaperUseCases` after https://github.com/mozilla-mobile/fenix/issues/26968

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21728)

**Comment by mbaimuratov** [comment]
Will be happy to contribute here!

One question:

I guess I also need to provide filesDir as a param, since we are getting it from context too:
val file = File(context.filesDir, path)
right?

**Comment by MatthewTighe** [comment]
Great, thanks for helping out!

> I guess I also need to provide filesDir as a param, since we are getting it from context too:
> val file = File(context.filesDir, path)
> right?

That's correct. The `filesDir` is already available to the top-level `WallpaperUseCases`, so it should just be a matter of passing it down.

**Comment by mbaimuratov** [comment]
> Great, thanks for helping out!
> 
> > I guess I also need to provide filesDir as a param, since we are getting it from context too:
> > val file = File(context.filesDir, path)
> > right?
> 
> That's correct. The `filesDir` is already available to the top-level `WallpaperUseCases`, so it should just be a matter of passing it down.

Then, I guess, I could contribute here :)

**Comment by oyeraghib** [comment]
@mbaimuratov are you still working on with this ?

**Comment by PrashantSaroj** [comment]
Hey @MatthewTighe, I would like to work on this issue. I have created this PR https://github.com/mozilla-mobile/fenix/pull/27730 . How do I test if my changes are correct?
