### ISSUE TITLE
[Bug]: Add-ons are only displayed in English

### ISSUE THREAD

**Issue by tesmite** [mozilla-mobile/fenix#27298]
### Steps to reproduce

1. Set the language of the device or Firefox to something other than English.
2. Add a multilingual add-on (e.g. uBlock Origin).
3. View the add-on's settings screen.

### Expected behaviour

If the add-on supports the selected language, it will be displayed in the selected language.

### Actual behaviour

Add-on settings are only displayed in English, no matter what language it is set to.
![Screenshot_20221006-154818](https://user-images.githubusercontent.com/111569199/194234813-99070ea9-c019-4f26-ac4c-05e932cc2d8e.png)

### Device name

Sharp AQUOS R3

### Android version

Android 11

### Firefox release type

Firefox Nightly

### Firefox version

107.0a1 (Build #2015908203)

### Additional information

A same issue has occurred pieviously in Fennec F-Droid.
In both cases, Application Settings in about:support page is only en-US.
![Screenshot_20221006-154841~2](https://user-images.githubusercontent.com/111569199/194235531-179f3e8c-aa8c-4975-9ae2-da9fead3aefb.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21736)

**Comment by hokonch** [comment]
The last good build: https://firefox-ci-tc.services.mozilla.com/tasks/index/mobile.v2.fenix.nightly.2022.09.30.revision.595d931dc04a01277cb83538437e61a57fd55efe/arm64-v8a
The first bad build: https://firefox-ci-tc.services.mozilla.com/tasks/index/mobile.v2.fenix.nightly.2022.10.01.revision.d70f8dec4fb250d8e31e4295dc436d81152beb11/arm64-v8a

https://github.com/mozilla-mobile/fenix/compare/595d931dc...d70f8dec4
https://github.com/mozilla-mobile/android-components/compare/10bd9b38bb...f38cd13c0d
https://github.com/mozilla/gecko-dev/compare/11cbd68fa5...3b13923820

**Comment by claudiu64** [comment]
This problem should be solved!

**Comment by kbrosnan** [comment]
This will be tracked in the Bugzilla bug.
