### ISSUE TITLE
[a11y] Consider increasing the contrast ratio on "Delete" and "Cancel" buttons from History deletion screen

### ISSUE THREAD

**Issue by amocirean** [mozilla-mobile/fenix#27306]
### Steps to reproduce

1. Have the Accessibility scanner app installed and opened.
2. Go to Home Page - Tap the three dot menu - History - Tap on the trash can icon.
Scan the dialogue.

### Expected behaviour

No suggestions are made.

### Actual behaviour

- Text contrast
android:id/button1
The item's text contrast ratio is 3.12. This ratio is based on an estimated foreground color of #AB71FF and an estimated background color of #42414D. Consider using colors that result in a contrast ratio greater than 4.50 for small text, or 3.00 for large text.

- Text contrast
android:id/button2
The item's text contrast ratio is 3.12. This ratio is based on an estimated foreground color of #AB71FF and an estimated background color of #42414D. Consider using colors that result in a contrast ratio greater than 4.50 for small text, or 3.00 for large text.

### Device name

Google Pixel 6

### Android version

Android 13

### Firefox release type

Firefox Nightly

### Firefox version

107.0a1

### Device logs

![image](https://user-images.githubusercontent.com/103257761/194328703-93147a06-6b13-460f-aede-d60abf9fce07.png)
![image](https://user-images.githubusercontent.com/103257761/194328717-5095a697-de32-44a3-a3f6-31520a1646da.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21743)

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813451

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
