### ISSUE TITLE
[Bug]: [a11y] Consider increasing the contrast ratio on the Saved logins' buttons

### ISSUE THREAD

**Issue by amocirean** [mozilla-mobile/fenix#27307]
### Steps to reproduce

1. Have the Accessibility scanner app installed and opened.
2. Go to Settings - Delete Browsing Data (under the Privacy and security section) 
3. Scan the dialogue.

### Expected behaviour

No suggestions are made.

### Actual behaviour

Text contrast
android:id/button1
The item's text contrast ratio is 1.54. This ratio is based on an estimated foreground color of #FF9AA2 and an estimated background color of #E0E0E5. Consider using colors that result in a contrast ratio greater than 4.50 for small text, or 3.00 for large text.

### Device name

Google Pixel 6

### Android version

Android 13

### Firefox release type

Firefox Nightly

### Firefox version

107.0a1

### Additional information

![image](https://user-images.githubusercontent.com/103257761/194330100-e0a1f2cd-0bd8-4652-aa71-e408baf19daf.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21744)

**Comment by mcarare** [comment]
@gabrielluong can you check if the `DestructiveButton` style uses the correct colors? TY!

**Comment by gabrielluong** [comment]
For reference, this is design system component for our warning buttons https://www.figma.com/file/ujdiReypSypu2GhRgzArea/Android-Components?node-id=1429%3A3084

**Comment by SoftVision-LorandJanos** [comment]
Manged to reproduce with the Nightly build from 2022-10-06 (107.0a1).
Verified as fixed on the latest Nightly 107.0a1 (2022-10-09T17...) build.
There is no text contrast ratio suggestion displayed.
Device used: Oppo Find X5 (Android 12).
Closing the ticket as fixed.
![Screenshot_2022-10-10-07-57-24-27_80a9469f53bfe75dbc6e8989be28e2f0](https://user-images.githubusercontent.com/48829350/194801524-91d4591b-7488-4223-9ea6-22f11707def9.jpg)
