### ISSUE TITLE
[Bug]: Blank tabs on theguardian.com

### ISSUE THREAD

**Issue by revad** [mozilla-mobile/fenix#27300]
### Steps to reproduce

1 open theguardian.com
2 open an article in a new tab and swich to it when the notification appears
3 switch back to the first tab
3 repeat 2 and 3 a few times

### Expected behaviour

each article should open quickly

### Actual behaviour

After 3 or 4 repeats the new tab displays blank and stays that way

### Device name

Samsung GT S6 lite

### Android version

Android 12

### Firefox release type

Firefox

### Firefox version

105.2.0

### Additional information

A report of this was posted on NG alt.comp.software.firefox:
"Open theguardian.com on my phone, with Android Firefox Focus (105.1) and open say three stories in new tabs. Each takes 30s to load, most of that a completely blank screen."

I read the guardian site so tried it in Fx (not focus) which I get from Moz releases. I see the same problem - hence this bug.

But I usually use nightly and use the guardian site a lot and I've never seen this. In nightly I use this addon which I wrote years ago for fennec:
https://addons.mozilla.org/en-US/firefox/addon/android_new_tabs_in_foreground/

If I disable that addon, the problem appears in Nightly.

So it seems related to tab switching

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21738)

**Comment by thomasgl-orange** [comment]
Similar behaviour here, with Firefox for Android (currently 108.1.0 on Pixel 6a / Android 13). It gets temporarily stuck when I try to open several tabs from **theguardian.com** homepage. I also often have to reload some of the opened background tabs to see their content once Firefox is unstuck. I would say it used to work just fine, and it started not working correctly a few months back, but I don't know when exactly. And navigation on this website without using multiple tabs is smooth, no problem.

I usually have uBlock Origin and Decentraleyes enabled, but when I disable them this issue with **theguardian.com**  persists, so I don't think this is related to my Firefox extensions.

**Comment by thomasgl-orange** [comment]
Thanks to a profile posted in https://bugzilla.mozilla.org/show_bug.cgi?id=1788530 which was showing a lot of time spent in one specific script, I've tried blocking `||assets.guim.co.uk/javascripts/commercial/` via UBlock Origin filters. No idea what I'm missing by doing this, but it seems to be an effective workaround, I can now open multiple tabs on The Guardian again, without any lag at all.
I'm so happy, I can read the news on my phone!

**Comment by cpeterso** [comment]
Sounds like this is a Firefox performance issue. We can track that in the existing Bugzilla bug about theguardian.com performance: https://bugzilla.mozilla.org/show_bug.cgi?id=1788530
