### ISSUE TITLE
Flicker is displayed when sending the app in background on Sony Xperia (Android 6.0.1)

### ISSUE THREAD

**Issue by AdinaPetridean** [mozilla-mobile/fenix#27303]
### Steps to reproduce

1. Have a fresh install and launch Firefox.
2. Send the app in background. Observe the flicker.

### Expected behaviour

The transition is done smoothly, without visual defects.

### Actual behaviour

When sending the app in background, a subtle flicker is displayed.

### Device name

Sony Xperia 

### Android version

Android 6.0.1

### Firefox release type

Firefox Nightly

### Firefox version

Nightly 107.0a1 - 10/06

### Additional information

Please note this issue is reproducible also on Firefox 106.0b4.

https://user-images.githubusercontent.com/108326843/194293927-5146d27d-86d3-449d-b867-1f7f2fa7396b.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21741)

**Comment by Mugurell** [comment]
Seems to be a device specific issue. Does it happen with other apps also?

**Comment by AdinaPetridean** [comment]
It is a reproducible only on Xperia (Android 6.0.1). Could not reproduce with Xiaomi Pad5 (Android 12).

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812399

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
