### ISSUE TITLE
[a11y]: Talkback does not say "Double tap to activate" when selecting a wallpaper

### ISSUE THREAD

**Issue by SoftVision-LorandJanos** [mozilla-mobile/fenix#27318]
### Steps to reproduce

1. Turn TalkBack (or the available screen reader) on
2. Open Settings > Homepage > Wallpapers
3. Select any wallpapaer and observe what talkback announces.

### Expected behaviour

After the description, Talkback announces "Double tap to activate".

### Actual behaviour

Talkback does not say "Double tap to activate".

### Device name

Google Pixel 4

### Android version

Android 12

### Firefox release type

Firefox Nightly

### Firefox version

107.0a1

### Additional information

https://user-images.githubusercontent.com/48829350/194405735-3d0291b7-8744-4862-967c-629d4e442e5a.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21753)

**Comment by Mugurell** [comment]
@SoftVision-LorandJanos Might it be a device specific issue? Maybe you have to wait a bit more for the action to be read?
For me the action is indeed read aloud. (latest Firefox Nightly, OnePlus 7T, Android 11)

https://user-images.githubusercontent.com/11428869/194497179-4ccc13e5-bf97-4142-9dd9-62d1db9efa9e.mp4

**Comment by SoftVision-LorandJanos** [comment]
@Mugurell it might be device specific, I didn't reproduce this issue on Oppo Find X5 (Android 12).

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1809799

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
