### ISSUE TITLE
[Bug]: [a11y] "Double tap to activate" is announced twice on "Try Again" with error page

### ISSUE THREAD

**Issue by SoftVision-LorandJanos** [mozilla-mobile/fenix#27311]
### Steps to reproduce

1. Turn TalkBack (or the available screen reader) on.
2. Launch Fenix and open a webpage with a wrong URL.
3. Tap on the "Try Again" button.

### Expected behaviour

Talkback announces: "Try Again button. Double tap to activate".

### Actual behaviour

"Double tap to activate" is announced twice.

### Device name

Google Pixel 4

### Android version

Android 12

### Firefox release type

Firefox Nightly

### Firefox version

107.0a1

### Additional information

https://user-images.githubusercontent.com/48829350/194353314-ee3656d0-ed81-4b07-aa23-98ce37f6cb5a.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21747)

**Comment by mcarare** [comment]
I cannot reproduce this on Pixel 4 with Android 13.

Can you reproduce it consistently?

**Comment by Mugurell** [comment]
This seems similar to https://github.com/mozilla-mobile/fenix/issues/27314

I see that tapping on page elements will not keep the green border but if navigating with swipes the border is shown.
Also if the "Try again" button is tapped then the action will be read twice but if navigating with swipes the description will be read only once.

https://user-images.githubusercontent.com/11428869/194510038-7914e0b8-e282-47ac-b213-3baa1e01fa62.mp4

**Comment by SoftVision-LorandJanos** [comment]
@Mugurell yes, I can confirm it is similar with the mentioned issue in 2 points: the green border doesn't say on when tapping on the elements, and "double tap to activate" is announced twice. The difference is that here the tapping area is correct.

**Comment by Mugurell** [comment]
Thank you.
Looks to be the same (or very close) to the issue from https://bugzilla.mozilla.org/show_bug.cgi?id=1794392.
Since this happens with an internal page I'll mark this as waiting for the Bugzilla issue to be fixed after which this can be assessed again.

**Comment by SoftVision-LorandJanos** [comment]
This issue is no longer reproducible with the latest Beta 109.0b4 and the latest Nightly 110.0a1 (2022-12-30) builds.
Device used: Google Pixel 4 (Android 13).
"Double tap to activate" is read once.
Closing the ticket as verified.
