### ISSUE TITLE
[Bug] Firefox Privacy Notice page is opened as a custom tab

### ISSUE THREAD

**Issue by softvision-miralobontiu** [mozilla-mobile/fenix#2731]
## Steps to reproduce
1. Go to Settings - Privacy Policy.
1. Tap on Privacy Policy.

### Expected behavior
The [page ](https://www.mozilla.org/en-Us/privacy/firefox/) is loaded in a tab..

### Actual behavior
The [page ](https://www.mozilla.org/en-Us/privacy/firefox/) is opened as a custom tab.

### Device information
* Android devices: all
* Fenix version: 5/22

### Note
The same behavior happens when tapping on "Your Privacy" from the onboarding tour.

![Screenshot](https://user-images.githubusercontent.com/40694158/58175511-f186bd00-7ca8-11e9-9f0d-a4fed5cd072d.png)UNITO-UNDERSCORE!20190522-152533!

**Comment by boek** [comment]
This is working as intended

**Comment by bifleming** [comment]
Working as intended.
