### ISSUE TITLE
[Bug]: Youtube interface cuts off title of video

### ISSUE THREAD

**Issue by Red-e-s** [mozilla-mobile/fenix#27319]
### Steps to reproduce

1. Open Youtube
2. Play a video
3. Scroll down and browse recommended videos
4. Scroll back up and the video title is cut-off
![Screenshot_20221007-035651~2](https://user-images.githubusercontent.com/102672783/194409108-1447051f-aee1-458e-961e-0f0bc793ed56.png)

### Expected behaviour

Video title shouldn't be cut-off
![Screenshot_20221007-040926](https://user-images.githubusercontent.com/102672783/194409160-1d110f40-18f0-47ec-a982-decd0c00e598.png)

### Actual behaviour

The video title is cut off
![Screenshot_20221007-035651](https://user-images.githubusercontent.com/102672783/194409224-5a69ec45-9d63-4fcc-ad87-c9ff9541b2dc.png)

### Device name

Google Pixel 6a

### Android version

Android 13

### Firefox release type

Firefox

### Firefox version

105.2.0

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21754)

**Comment by amocirean** [comment]
Hello @Red-e-s , thank you for submitting the issue.
I was not able to reproduce it on Nightly 107.0a1 nor Release 105.2.0. The video title is shown even after scrolling back up to the top. I've tested this in both portrait and landscape mode.
Could you tell us if the issue is still occuring on the latest Nightly on your device?

Devices Used: Huawei P40 Lite (Android 10), Google Pixel 6 (Android 13).

**Comment by Red-e-s** [comment]
Hi, thanks for reaching out. Yes the issue persists with v105.2.0. 

It seems to have something to do with this YouTube suggestions banner:
![Screenshot_20221010-173817](https://user-images.githubusercontent.com/102672783/194841229-7a924299-62b5-491a-a13b-08c67977b51a.png)

The suggestions banner sporadically disappears and reappears. When it does, the YouTube video title gets cut-off. You can see this phenomenon occur here:
https://user-images.githubusercontent.com/102672783/194841169-a3717b15-57ed-4d6d-b399-80b89e103ba4.mp4

However, the above video doesn't show an instance when the suggestion banner gets "stuck" and the video title gets permanently cut-off (even refreshing doesn't resolve it). It sometimes does that, but I can't figure out what exactly triggers that scenario.

One hypothesis I have is that uBlock Origin is causing the issue.

**Comment by jonalmeida** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813762

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
