### ISSUE TITLE
[a11y] Consider increasing the contrast ratio on "+" button from Tabs Tray

### ISSUE THREAD

**Issue by amocirean** [mozilla-mobile/fenix#27310]
### Steps to reproduce

1. Have the Accessibility scanner app installed and opened.
2. Go to Home Page - Tap the tab counter
3. Scan the opened Tabs Tray.

### Expected behaviour

No suggestions are made.

### Actual behaviour

Text contrast
org.mozilla.fenix:id/new_tab_button
The item's text contrast ratio is 2.47. This ratio is based on an estimated foreground color of #7542E5 and an estimated background color of #2B2A33. Consider using colors that result in a contrast ratio greater than 4.50 for small text, or 3.00 for large text.

### Device name

Google Pixel 6

### Android version

Android 13

### Firefox release type

Firefox Nightly

### Firefox version

107.0a1

### Additional information

![image](https://user-images.githubusercontent.com/103257761/194350657-f174c07b-9c01-42b4-8b3d-c21970a704f4.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21746)

**Comment by mcarare** [comment]
IMO the a11y scanner result is misleading, as the button is neither text nor a representation of text, so it does not need to meet the contrast requirement for text. 

Web Content Accessibility Guidelines for non-text contrast [state](https://www.w3.org/WAI/WCAG21/Understanding/non-text-contrast.html) that buttons that can be identified as such do not need to meet a strict contrast requirement.

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813449

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
