### ISSUE TITLE
Quicktime video is cropped strangely when played in FF for Android

### ISSUE THREAD

**Issue by grmblgrmbl** [mozilla-mobile/fenix#27327]
Open Quicktime video in FF for Android: https://www.mhohner.de/y/S.MOV

Video is cropped to a narrow strip, the rest of the video area is blank. See screenshot: https://www.mhohner.de/y/Screenshot_20221007-083011_Firefox.jpg

Happens with Galaxy S7 and Galaxy Tab S4.

Video plays just fine in FF for Windows.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21758)

**Comment by amocirean** [comment]
Hello  , thank you for submitting the issue.
I was able to reproduce it on both Nightly 107.0a1 and Release 105.2.0. 

Devices Used: Huawei P40 Lite (Android 10), Google Pixel 6 (Android 13).
