### ISSUE TITLE
Avoid specifying a version for the kotlin-dsl plugin

### ISSUE THREAD

**Issue by fice-t** [mozilla-mobile/fenix#27322]
The [Gradle Kotlin DSL page](https://docs.gradle.org/current/userguide/kotlin_dsl.html#sec:kotlin-dsl_plugin) states:
>Avoid specifying a version for the kotlin-dsl plugin
>
> Each Gradle release is meant to be used with a specific version of the kotlin-dsl plugin and compatibility between arbitrary Gradle releases and kotlin-dsl plugin versions is not guaranteed. Using an unexpected version of the kotlin-dsl plugin in a build will emit a warning and can cause hard to diagnose problems.

This leads to build warnings on every gradle invocation:

```
> Configure project :buildSrc
This version of Gradle expects version '2.3.3' of the `kotlin-dsl` plugin but version '2.4.1' has been applied to project ':buildSrc'. Let Gradle control the version of `kotlin-dsl` by removing any explicit `kotlin-dsl` version constraints from your build logic.
WARNING: Unsupported Kotlin plugin version.
The `embedded-kotlin` and `kotlin-dsl` plugins rely on features of Kotlin `1.6.21` that might work differently than in the requested version `1.7.10`.
```
Perhaps buildSrc/build.gradle should be converted to kotlin script and use the plugin in the recommended way? CC @mcarare

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21756)

**Comment by mcarare** [comment]
This is a known issue https://github.com/gradle/gradle/issues/13020 is one of the places it is reported.

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813448

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
