### ISSUE TITLE
Wallpapers - Add manual migration for Turning Red metadata colors

### ISSUE THREAD

**Issue by MozillaNoah** [mozilla-mobile/fenix#27331]
Dependency
- https://github.com/mozilla-mobile/fenix/issues/27330

Since the wallpaper text color and card colors were added after Turning Red's expiration, we need to add some manual migration so those colors are utilized for the two wallpapers.

**Mei**
| Light | Dark | 
| -- | -- |
| #FDE9C3 | #532906 |

**Panda**
| Light | Dark | 
| -- | -- |
| #FFEDF1 | #611B28 |

[Colors from figma](https://www.figma.com/file/d7l1iGabQYqnLcnQbHDGzM/Wallpaper-2.0-%2B-Onboarding-v106?node-id=7685%3A217334)

After this story lands, the turning red wallpapers should have backplating card colors that adapt to the user's light/dark theme preference.

E.G.
![image](https://user-images.githubusercontent.com/87384386/194621420-834154e9-1d73-41ef-9180-bf7055954332.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21761)

**Comment by delia-pop** [comment]
Verified as fixed on a custom build updated locally. The backplating on homepage items is displayed accordingly. 

![TR](https://user-images.githubusercontent.com/89388888/200342338-fa7884b1-71b0-4cb7-97a9-e39b82d8c468.png)

**Comment by delia-pop** [comment]
This is also verified as fixed on a locally created Beta 108 build with Motorola Moto G30 (Android 12).
