### ISSUE TITLE
Combine Google package name regex into a single one

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/fenix#27336]
> When `comGoogleAndroid` and `comGoogleFirebase` was originally added ([commit](https://github.com/mozilla-mobile/fenix/commit/f0464b9e72e0ea4dca94a46f8e0f05a285955c44#diff-75b31066e97e27961c3c9e9668c539a133d73c10398dc76552df3f0119810ac0R236)), I don't think it was possible (or at least easy) to generalize because `comGoogleAndroid` explicitly excluded some `com.google.android.*` deps that hadn't yet migrated from maven central to the google repo, i.e. it was defined as:
> ```kotlin
>     const val comGoogleAndroid = "com\\.google\\.android\\.(?!apps\\.common\\.testing\\.accessibility\\.framework).*"
> ```
> 
> Now that it's defined more generically (i.e. Google is hosting more packages on their repo), it might be possible. In that case, it'd also be preferable to reduce duplication (like the root cause of this issue).

_Originally posted by @mcomella in https://github.com/mozilla-mobile/fenix/issues/27321#issuecomment-1271843462_
      

1. We want to take the `comGoogleFirebase`, `comGoogleTesting`, and `comGoogleAndroid` defined [here](https://github.com/mozilla-mobile/fenix/blob/effc40dc3245f7077830bdb80ae482b61c1ba1f8/buildSrc/src/main/java/Dependencies.kt#L281) to be combined into a single `comGoogle` with the value: `com\\.google\\..*`.
2. We also need to update all the previous references to use just this one.
3. Remove [this comment](https://github.com/mozilla-mobile/fenix/blob/effc40dc3245f7077830bdb80ae482b61c1ba1f8/buildSrc/src/main/java/Dependencies.kt#L284-L289) as well.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21762)

**Comment by chetanmuliya** [comment]
can I fix this?

**Comment by jonalmeida** [comment]
Sure!

**Comment by chetanmuliya** [comment]
thanks
