### ISSUE TITLE
Show summary text for specified items in the top level settings view

### ISSUE THREAD

**Issue by fice-t** [mozilla-mobile/fenix#27338]
Similar to the settings summary for `Tabs` (e.g. `Close manually`), the summaries for the above should also contain option selected.

e.g. For HTTPS-Only: `On`/`Enable only in private tabs`/`Off`
For ETP: `On`/`Strict`/`Custom`

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21763)

**Comment by Mugurell** [comment]
Thank you for looking into this.
Please note that the UX is aligned between all platforms so any change in one app has a bigger impact and must be discussed with UX and product.
We might also need some new strings if wanting to offer more context about the current options.

Adding here also the video posted in the PR:

https://user-images.githubusercontent.com/13156601/194689943-564e6ae1-7f99-4c75-8fdc-f20b15b46ca2.mp4

**Comment by ewachowiak** [comment]
I'm looking into this issue and working on a solution that standardizes how we approach this across all settings, inclusive of iOS & Android. I opened a Jira task for this exploration: https://mozilla-hub.atlassian.net/browse/FXMUX-363

**Comment by cpeterso** [comment]
@Alexandru2909 - You have a work-in-progress PR up for review. Do you think you will be able to land your fix during the Fenix Nightly 111 cycle? If so, I will leave this GitHub issue here. If not, then I will need to move it to Bugzilla (as we prepare to move the Fenix code to the new firefox-android monorepo).

**Comment by Alexandru2909** [comment]
@cpeterso Thanks for checking! I'll land this during the 111 cycle.

**Comment by delia-pop** [comment]
Verified as fixed on latest Nightly from 01/27 with Google Pixel 6 (Android 13). The summary text is displayed in accordance with the document above for each option.

![summary](https://user-images.githubusercontent.com/89388888/215080504-8fc77b54-fe93-4717-9562-f5f8e6b82213.png)
