### ISSUE TITLE
[Bug]: Magnifier erroneously follows touch outside of text area

### ISSUE THREAD

**Issue by fice-t** [mozilla-mobile/fenix#27340]
### Steps to reproduce

1. Select a text box with text inside
2. Tap to bring up the handle.
3. Hold the handle to bring up the magnifier (API 28+) and drag outside of the text box.

### Expected behaviour

The magnifier is bound to a small area around the text box as it is in other apps (e.g. Chrome, Samsung Internet).

### Actual behaviour

The magnifier follows the user during dragging outside of the text box area.

### Device name

Google Pixel 3 XL (emulator)

### Android version

Android 10

### Firefox release type

Firefox Nightly

### Firefox version

106.0a1

### Additional information

https://user-images.githubusercontent.com/13156601/194691219-57ce2dbe-33c6-4ea9-8837-333b49b569b0.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21764)

**Comment by Mugurell** [comment]
Thank you for the report.
Moving to Bugzilla for more investigation.
