### ISSUE TITLE
Favicon fallback with display issues (pulling “og:image” instead of /favicon.ico)

### ISSUE THREAD

**Issue by j9t** [mozilla-mobile/fenix#27347]
### Steps to reproduce

1. Open a site like [meiert.com](https://meiert.com/) or [frontenddogma.com](https://frontenddogma.com/), where there’s no favicon markup, but a favicon at the root of the site
2. Bookmark the site, or switch to multi-tab view

### Expected behaviour

Absent any markup pointing to favicons, the favicon.ico at the root should be used (as [specified by the HTML standard](https://html.spec.whatwg.org/multipage/links.html#rel-icon), and as said to be fixed in [#20180](https://github.com/mozilla-mobile/fenix/issues/20180)).

### Actual behaviour

The Open Graph image is being pulled, ending up being displayed not to be recognizable at all.

![Screenshot_20221009-144610](https://user-images.githubusercontent.com/1700772/194757963-7ef1e629-54c1-47ec-8b02-e7416b8d38b7.png)

(Open Graph images are usually not only not square, but of entirely different dimensions—now leading to a worse experience than pulling a usually low-res favicon.ico.)

### Device name

Google Pixel 6a

### Android version

Android 13

### Firefox release type

Firefox

### Firefox version

105.2.0

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21768)

**Comment by rocketsroger** [comment]
I'll take a look at this.  Thanks

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813447

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
