### ISSUE TITLE
[Bug]: window inner height includes dynamic  toolbar height in mobile 

### ISSUE THREAD

**Issue by venkateshparihar** [mozilla-mobile/fenix#27344]
### Steps to reproduce

1. Go to tab
2 . Get window innerheight when application loads.
3. Window.innerheight also includes the height of dynamic toolbar.
4. Resize event not invoke on hide of toolbar

### Expected behaviour

Window.innerheight should not  includes the height of dynamic toolbar.

### Actual behaviour

Window.innerheight also includes the height of dynamic toolbar.

### Android version

Android 10

### Firefox release type

Firefox

### Firefox version

89.0.10

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21765)

**Comment by Mugurell** [comment]
Thank you for the report.
Moving to Bugzilla for more investigations.

**Comment by Mugurell** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1794357

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Comment by hiikezoe** [comment]
Can you please post an example or a link to the site in question? As far as I can tell window.innerHeight doesn't include the toolbar height if the toolbar is visible, it includes the height if the toolbar is invisible. I checked it on http://bokand.github.io/demo/urlbarsize.html now.
