### ISSUE TITLE
[Bug] Blank tab after opening tabs tray and returning straight to tab

### ISSUE THREAD

**Issue by pwd-github** [mozilla-mobile/fenix#2734]
## Steps to reproduce
1. Open tab
1. Navigate to a website (Mozilla.org)
1. Open tabs tray 
1. Select the (Mozilla) tab that's already open

### Expected behavior
The content of the tab is displayed in its previous state. 

### Actual behavior
The contents of the tab do not display. 

### Device information
* Android device: Android 8, LG G8
* Fenix version: 1.0.1921

**Comment by vesta0** [comment]
@pwd-github please let us know if you can still reproduce this bug.

**Comment by pwd-github** [comment]
Hi @vesta0

I can no longer produce this. It appears to be fixed.
