### ISSUE TITLE
[Bug]: problem with content security policy 

### ISSUE THREAD

**Issue by ale82to** [mozilla-mobile/fenix#27356]
### Steps to reproduce

Firefox after version 99 removed the ability to disable csp using about:config ,so the only solution as suggested  is to use a web request add on to manipulate (remove content-security-policy ),this work but not for all websites . having explained that both android and Mac desktop (nighly 107) for example fail to disable csp with web request addons for Twitter.com UNLESS I SET TO FALSE DOM.CACHES.ENABLED . can someone confirm this ?

### Expected behaviour

I should be able to modify csp

### Actual behaviour

csp is not disabled 

### Device name

poco f3

### Android version

android 

### Firefox release type

Firefox Nightly

### Firefox version

107

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21772)

**Comment by Mugurell** [comment]
Moving the ticket to Bugzilla for more investigation.

**Comment by Mugurell** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1794545

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
