### ISSUE TITLE
Allow for the removing of multiple tabs

### ISSUE THREAD

**Issue by pwd-github** [mozilla-mobile/fenix#2735]
### Why/User Benefit/User Problem
This is for tab management. 

### What/Requirements
Allow users to delete tabs in Multi-select view. 

### Acceptance Criteria (how do I know when I’m done?)
When a user selects multiple tabs, they should be given the option to either save the tabs or remove them from the tabs tray.

**Comment by s-ankur** [comment]
Hi, this works now, can be closed
