### ISSUE TITLE
[Bug]: push notifications not working for facebook Instagram reddit 

### ISSUE THREAD

**Issue by ale82to** [mozilla-mobile/fenix#27355]
### Steps to reproduce

let's try again I'll have more luck this time .
can please someone explain me why push notifications in fenix (both stable ,beta and nighlty )for some services (Facebook ,Instagram ,reddit ,tinder )are NOT working ?

### Expected behaviour

I should receive push notifications 

### Actual behaviour

for some website (not all )push notifications are not working 

### Device name

poco f3

### Android version

android 12

### Firefox release type

Firefox Nightly

### Firefox version

107

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21771)

**Comment by SoftVision-LorandJanos** [comment]
Hi @ale82to! This issue was already covered by #26998 which was about Facebook alone, but I think it's the same reason for Instagram ,reddit ,tinder. In the mentioned issue, there is a comment that should explain this: https://github.com/mozilla-mobile/fenix/issues/26998#issuecomment-1255383408

**Comment by ale82to** [comment]
I don't know if this might help but until version 96/97 push for both face /insta worked , reddit and tinder instead never worked
