### ISSUE TITLE
[Bug]: The PB icon is not displayed for devices with Android <= 6 after setting a wallpaper

### ISSUE THREAD

**Issue by AdinaPetridean** [mozilla-mobile/fenix#27366]
### Steps to reproduce

1. Launch the Firefox app.
2. Go to Settings- Homepage- Wallpapers and select a wallpaper.
3. From the snackbar tap on "View" button.
4. Observe that the PB icon  is not displayed on homepage.

### Expected behaviour

The PB icon is displayed on homepage when a wallpaper is set.

### Actual behaviour

The PB icon is not displayed on devices with Android <= 6 after setting a wallpaper. 
The icon is displayed for the default non-wallpaper option, when is set from Settings. However, note that when using the Wallpaper Selection Tool, the PB icon is not displayed, regardless of the wallpaper set, the default one included when the Light theme is used in combination with a previously set wallpaper on which the PB icon would be displayed in white color.

### Device name

Huawei MediaPad M2 

### Android version

Android 5.1.1

### Firefox release type

Firefox Nightly

### Firefox version

Firefox Nightly 107.0a1 from 10/11

### Additional information

This issue is also reproducible with Sony Xperia (Android 6.0.1). Not reproducible with Android >= 7.
Please note that the PB mode can be entered by tapping on the right corner, where the icon should be.
The issue seems to be a regression from #26644 in Nightly 107.0a1 from 09/27.
The issue was also uplifted to Beta 106 starting with Beta 3 and RC 106.1.0.

https://user-images.githubusercontent.com/108326843/195078362-747f12b2-a0dd-49eb-a662-787aad93f70d.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21776)

**Comment by Mugurell** [comment]
Seems like there is an issue with [VectorDrawableCompat.create](https://github.com/mozilla-mobile/fenix/blob/main/app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt#L1002) returning `null` on Android <= 23.

Given that the severity of this issue is much higher than of the one one for which the above call was added and that @Alexandru2909 is planning to soon refactor the private browsing button it seems like the best immediate solution would be to revert the https://github.com/mozilla-mobile/fenix/pull/27105 patch, and also uplift this change.

**Comment by MatthewTighe** [comment]
Thanks for the report, and the fix!

We have decided not to uplift the patch for 106, given the following:
- private browsing is still accessible through the tabs tray
- the affected population should be relatively small (low number of users on versions that old, and of those only affects people with wallpapers)
- today is already release candidate day

That said, prioritizing https://github.com/mozilla-mobile/fenix/issues/27120 would be good for 107.

I'm also curious as to whether `VectorDrawableCompat.create` should've been caught by a linter. I'll investigate that a bit today
