### ISSUE TITLE
[Bug] Fix Docker build error

### ISSUE THREAD

**Issue by rpappalax** [mozilla-mobile/fenix#2736]
Docker build is currently broken on error below.  Current Dockerfile was a WIP that got merged pre-maturely, but master was broken before so, per chat with @pocmo, I'll re-open a PR and continue address the issue here.
see: https://github.com/mozilla-mobile/fenix/pull/2489

@mitchhentges suggests running a completely clean build, which I'll attempt today

```
./gradlew clean
./gradlew --stop
./gradlew --no-daemon assembleDebug test lint
```

## Steps to reproduce
```
docker build .
```

### Expected behavior
Should gradle build without error

### Actual behavior
Gradle build fails on

```
> Task :app:compileArmDebugKotlin
Unable to clear jar cache after compilation, maybe daemon is already down: java.rmi.ConnectException: Connection refused to host: 127.0.0.1; nested exception is:
	java.net.ConnectException: Connection refused (Connection refused)
Could not connect to kotlin daemon. Using fallback strategy.
Compilation with Kotlin compile daemon was not successful
java.rmi.UnmarshalException: Error unmarshaling return header; nested exception is:
	java.io.EOFException
	at sun.rmi.transport.StreamRemoteCall.executeCall(StreamRemoteCall.java:236)
	at sun.rmi.server.UnicastRef.invoke(UnicastRef.java:161)
	at java.rmi.server.RemoteObjectInvocationHandler.invokeRemoteMethod(RemoteObjectInvocationHandler.java:227)
	at java.rmi.server.RemoteObjectInvocationHandler.invoke(RemoteOb
```

**Comment by npark-mozilla** [comment]
This issue is blocking putting the UI test on CI - it would be great if we can get dev's help on it.  We are also seeing docker instance running out of memory in TC as well.  @pocmo @boek if you have allocation, could you take a quick look please?

**Comment by rpappalax** [comment]
Summarizing findings here:

Summary of this issue....

1. Current Dockerfile in master was a (WIP) PR that was merged prematurely. DO NOT USE.
2. Dockerfile to master (prior to merge) no longer builds with Ubuntu 17.10 and fails with ubuntu repos missing release files: https://gist.github.com/rpappalax/3a0200270e0d200ec057d3cec54c994d
3. Upgrading Dockerfile to Ubuntu 18.04 fixes above issue but fails unless memory is increased to 4G.  This will give you enough memory to `gradlew assemble` but not `gradlew assemble lint`
4. gradlew will still fail without -PversionName=0.0. Replacing assemble with assembleDebug should in theory fix this, but it still fails without it.
4. If you add lint back to gradlew command, then linting is successful until it reaches "In configuration ':app:armDebugAndroidTestCompileClasspath': substituting megazord module 'org.mozilla.appservices:fenix-megazord:0.28.1' for component module 'org.mozilla.appservices:rustlog:0.28.1'" then will stalls for 25 minutes then ultimately fail:  https://gist.github.com/rpappalax/aaadcdd393c4545087ddc913e88e9a03
5. Increasing memory on the following also seems to have no effect
  - Docker Engine memory increased to 6G
  - gradle.properties jvmargs to 6411m 
  - ENV JAVA_OPTS="-Xmx6144m"

**Comment by npark-mozilla** [comment]
With #3281 closed, I have verified that the gradle build passes, and the docker image is successfully built.
