### ISSUE TITLE
WebGL Canvas rendering issue

### ISSUE THREAD

**Issue by fabry24** [mozilla-mobile/fenix#27365]
### Steps to reproduce

1. open OpenLayers example https://openlayers.org/en/latest/examples/webgl-sea-level.html
2. work with map 
3. after a while grey rectagle will appear

### Expected behaviour

Expected behaviour is correct displayed WebGL canvas

### Actual behaviour

Expected behaviour is correct displayed WebGL canvas
![image](https://user-images.githubusercontent.com/78112061/195070896-e04ddf36-f1fe-408e-bc83-98c0e8a06e55.png)

this problem was reported in https://github.com/mozilla-mobile/fenix/issues/24635.

### Device name

Galaxy Tab S7 FE

### Android version

Android 12

### Firefox release type

Firefox

### Firefox version

105.2.0

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21775)

**Comment by SoftVision-LorandJanos** [comment]
Hi @fabry24! Thank you for your report!
I've managed to reproduce your issue. I also as a workaround, after this grey screen is displayed, after further interaction it works as expected again.
However the previously reported same issue was transferred in bugzilla where it was labeled as wontfix after trying to fix it. Most probably the priority, the severity and the fact that it has a workaround helped in deciding so.
Based on this, I will close the ticket as not planned.
Tested on the latest Nightly 107.0a1 (2022-10-12) and latest RC (106.1.0).
Device used: Oppo Find X5 (Android 12).
