### ISSUE TITLE
[Bug] Amazon login doesn't work

### ISSUE THREAD

**Issue by Dandona100** [mozilla-mobile/fenix#27378]
Hello. 
In Firefox  browser,  

https://user-images.githubusercontent.com/115621706/195295583-41609b47-dbca-44ff-bc8b-4ace15cc3640.mp4

I try to log in to my account on Amazon's website, click on log in, enter my username (email, in this case) and instead of the page taking me to enter a password, the browser takes me nowhere.. Attached is a video of the bug.
Thank you

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21782)

**Comment by Mugurell** [comment]
The same message in english:
 
![image](https://user-images.githubusercontent.com/11428869/195298123-de4b95cf-886c-493a-8fe9-f91c0c2d7624.png)

Have you tried on other browsers and it works okay? Including Firefox desktop.
What would help for debugging would be to know the exact URLs at each step.

**Comment by Dandona100** [comment]
Through other browsers it works fine, and in Firefox it also works in desktop site mode.  But in normal mode, only in Firefox it doesn't work.
Below is the URL:
 1.   https://www.amazon.com/-/he/ap/signin?openid.pape.max_auth_age=0&openid.return_to=https%3A%2F%2Fwww.amazon.com%2F%3F_encoding%3DUTF8%26ref_%3Dnavm_hdr_signin&openid.identity=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&openid.assoc_handle=anywhere_v2_us&openid.mode=checkid_setup&openid.claimed_id=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&&dplnkId=a182a4ab-22ab-4bf3-86be-0653d5d303e8
 after tou inter your phone number/ email address
you inter in this URL:
 2. https://www.amazon.com/ap/signin?dplnkId=8387e6a8-04b7-4c4c-b3dd-d97cc1a4063b

**Comment by Mugurell** [comment]
I see this was reported before - https://support.cdn.mozilla.net/en-US/questions/1380658

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813446

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
