### ISSUE TITLE
[Bug] Touching a suggested emoji on the keyboard doesn't replace the previous typed word by the respective emoji on the search/address bar, if the word autocompletes an address. .

### ISSUE THREAD

**Issue by Lululalu** [mozilla-mobile/fenix#2737]
## Steps to reproduce
Enable emoji suggestion on your keyboard(I used SwiftKey) 
Type the name of an emoji that autocompletes an address on Fenix search bar (apple :green_apple: for example) 
Touch the suggested emoji

### Expected behavior
The word apple is replaced by the :green_apple: emoji

### Actual behavior
After touch the :green_apple: emoji, nothing happens. Touching the :green_apple: again adds the :green_apple: to the address bar, right after the word apple (not replacing it) 

## Device information
* Android device: Galaxy A5
* Fenix version: 1.0.1921

**Comment by mihai-adrian** [comment]
Same bug is reproducible in Fenec. Probably it's origin is in GeckoEditable from  geckoview.

**Comment by mcarare** [comment]
Actually, I cannot reproduce either of cases anymore. I have updated SwiftKey since then.
