### ISSUE TITLE
[Bug]: No video in https://with.in website

### ISSUE THREAD

**Issue by svillar** [mozilla-mobile/fenix#27371]
### Steps to reproduce

1. Go to https://www.with.in/watch/breathe-peace-world
2. Play the video

### Expected behaviour

A video is played

### Actual behaviour

Only sound is played, no video at all.

### Device name

Huawei Mate Pro 40

### Android version

Android 12

### Firefox release type

Firefox

### Firefox version

105.2

### Additional information

[Originally reported](https://github.com/Igalia/wolvic/issues/261) in Wolvic, but I found that it's a general Gecko issue as it does not work in fenix either.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21778)

**Comment by SoftVision-LorandJanos** [comment]
Hi @svillar! Thank you for your report!
I can reproduce the issue you described.
Tested on the latest Nightly 1070a1 (2022-10-12).
Device used: Oppo Find X5 (Android 12).

**Comment by Mugurell** [comment]
The playback is choppy on desktop also.
Moving to Bugzilla for more investigations.
