### ISSUE TITLE
[Bug]: Incorrect file extension in Android Firefox - .com and .tar.tar

### ISSUE THREAD

**Issue by Tuxilla** [mozilla-mobile/fenix#27383]
### Steps to reproduce

    go to link https://download-installer.cdn.mozilla.net/pub/firefox/releases/105.0.3/linux-x86_64/de/
    go to link https://download-installer.cdn.mozilla.net/pub/firefox/releases/105.0.3/win64/de/

It is not reporoducible on a BQ X5 Plus with LineageOS, only on two Samsung A52 4G.

### Expected behaviour

a .exe and tar.bz2 file should download / open

### Actual behaviour

a .com and tar.tar file is downloaded

### Device name

Samsung A52 4G

### Android version

Ansroid 12

### Firefox release type

Firefox

### Firefox version

105.2.0

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21854)

**Comment by RuthlessRuler** [comment]
Can reproduce the same behaviour for both files.

System:
Firefox 106.1.0
OS: Android 12 based MIUI 13
Device: Poco X3 Pro

**Comment by fice-t** [comment]
Looks the same as #18327. Likely LineageOS includes a mimetype definition for `tar.bz2` while others don't.
