### ISSUE TITLE
FNX3-16550 ⁃ [Bug] Sync settings button doesn't transition to logged in state properly

### ISSUE THREAD

**Issue by vladikoff** [mozilla-mobile/fenix#2739]
From https://github.com/mozilla-mobile/fenix/issues/2196#issuecomment-493157548
Google Groups: https://groups.google.com/forum/#!msg/fenix-nightly/H9kTciTLoBk/o81d81VOBQAJ

## Steps to reproduce
Login to Sync and open Fenix Settings

<img src=https://user-images.githubusercontent.com/128755/58187019-f84f0900-7c83-11e9-957c-dff83bb9371e.gif width=350 />

### Expected behavior
Should not show the Sign In button after the FxA close is complete

### Actual behavior
It takes 30 seconds or more (depends on server connection / amount of sync data?) to transition to logged in state

### Device information
* Android device: One Plus 6
* Fenix version: on `master` 5ec783f6e5e4f7b9cb7a246228f9f7e35fd7fb01

**Comment by dector** [comment]
If this issue is not taken I would like to work on it.

**Comment by softvision-miralobontiu** [comment]
Verified as fixed on the latest build 1.0.1921 (#11440614), with Sony Xperia Z5 PRemium (Android 7.1.1), Google Pixel (Android 9), Samsung Galaxy Note 8 (Android 9), Nexus 5 (Android 6.0.1), and Sony Xperia Z2 tablet (Android 6.0.1).
