### ISSUE TITLE
First-time inactive tabs tutorial dialogue can display in wrong tab of menu

### ISSUE THREAD

**Issue by vaguerant** [mozilla-mobile/fenix#27393]
### Steps to reproduce

1. Have a new Firefox install (haven't seen this tutorial dialogue before).
2. In normal mode, open and don't use a tab for almost two weeks.
3. Open a private tab.
4. Wait for the normal tab to become inactive (I did this part outside of the app, this wasn't planned).
5. Open tab menu *within private mode*.
6. See notification explaining that tabs which have not been used for two weeks have been moved "here", pointing at nothing because the inactive tab is not in private mode and that heading doesn't exist in this section.
7. Go to normal (non-private) tab menu, realize what has gone wrong, report a bug on GitHub (check for duplicates!).

### Expected behaviour

Firefox should only throw this notification when the user enters *the same section of the tab menu where the inactive tabs menu appears*.

### Actual behaviour

Firefox seems to throw this notification *whenever the user opens the tab menu*, regardless of whether the user is in the relevant mode.

### Device name

Ulefone Armor X7 Pro

### Android version

Android 10

### Firefox release type

Firefox

### Firefox version

105.1.0 (Build #2015904299), b1e7cbeeb+

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21793)

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813443

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
