### ISSUE TITLE
Refactor `SelectableChip` to be a top level `Chip` component 

### ISSUE THREAD

**Issue by MozillaNoah** [mozilla-mobile/fenix#27401]
The `SelectableChip` Composable is effectively a `Chip` that just handles re-colors based on the `isSelected` boolean. The component would be best served as a generic `Chip` component (similar to `TextButton`) that has a condensed list of parameters and uplifts any stateful logic (such as selected vs unselected) to the actual UI that uses it.

The contract should be something like:

``` @Composable
fun Chip(
    text: String,
    modifier: Modifier = Modifier,
    textColor: Color? = null,
    backgroundColor: Color? = null,
    onClick: (() -> Unit)? = null,
) {
```

The other Chip component use cases (such as having an optional icon) could be implemented as well.

The text & default colors should be double checked against their specs in [FIgma](https://www.figma.com/file/ujdiReypSypu2GhRgzArea/Android-Components?node-id=1808%3A7427).

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21795)

**Comment by gabrielluong** [comment]
Okay yea, the contract totally makes sense to me. Thanks for the thorough issue description.
