### ISSUE TITLE
Remove email address from 3 dot menu

### ISSUE THREAD

**Issue by sheikh-azharuddin** [mozilla-mobile/fenix#27406]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### What is the user problem or growth opportunity you want to see solved?
Based on the signed in account email address,
the width of the 3 dot menu is getting adjusted.if the email address is long, it is unnecessarily increasing the width. None of the chromium browsers add the email address in the 3 dot menu.
They have a fixed narrow width menu

Instead of the email address probably an account logo can be added which on clicking will behave same as clicking email address 

### How do you know that this problem exists today? Why is this important?
The width of the menu increasing

### Who will benefit from it?
All users

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21798)

**Comment by delia-pop** [comment]
Hi, @sheikh-azharuddin, thank for reporting!
Please note that a similar feature request to replace the e-mail address from the 3-dot menu was already opened under ticket https://github.com/mozilla-mobile/fenix/issues/20325. I will close this as duplicate but you can leave a comment with your suggestion in the mentioned ticket so we can have everything in one place. Thank you!
