### ISSUE TITLE
[Bug] Tapping the address bar yields a UI hang on x86 emulator

### ISSUE THREAD

**Issue by AaronMT** [mozilla-mobile/fenix#2740]
Build: 5ec783f6e5e4f7b9cb7a246228f9f7e35fd7fb01
Device: x86 debug Pixel 2 Emulator

* Launch Fenix
* Tap the address bar

**Comment by dector** [comment]
I have same issue. Discovered that ANR starts [here](https://github.com/mozilla-mobile/fenix/blob/e5f27a2e8d0edd2e72a1defc9bcc1a958fcfec4d/app/src/main/java/org/mozilla/fenix/settings/SettingsFragment.kt#L96).

**Comment by vesta0** [comment]
Will re-test when x86 is added

**Comment by ekager** [comment]
Is this still a problem @AaronMT ?

**Comment by AaronMT** [comment]
This seems fixed now.
