### ISSUE TITLE
the history  or recentVisits is displayed on the homepage

### ISSUE THREAD

**Issue by klcb2010** [mozilla-mobile/fenix#27402]
For Firefox Nightly98.0a1  above, the history or recentVisits is displayed on the homepage as a shortcut, and the title cannot be displayed completely.
![Screenshot_2022-10-14-07-37-05-406_com miui gallery](https://user-images.githubusercontent.com/32628414/195730353-830392ea-8a54-4837-b754-f553a8659a10.jpg)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21796)

**Comment by klcb2010** [comment]
Below Firefox Nightly107.0a1, the title can be fully displayed.
![Screenshot_2022-10-14-07-39-38-602_com miui gallery](https://user-images.githubusercontent.com/32628414/195731022-a78d74b2-7c6b-49ff-a511-6577fccbb99e.jpg)

**Comment by uok** [comment]
My suggestion is to use more of the vertical space that 99% of mobile devices offer and stack them vertically
- [favicon] [long title here]
- [favicon] [long title here]
- [favicon] [long title here]

**Comment by mcarare** [comment]
@klcb2010 Are the screenshots (after and before Nightl98.0a1) from the same device?

**Comment by klcb2010** [comment]
> @klcb2010 Are the screenshots (after and before Nightl98.0a1) from the same device?
yes,i use redmi K30pro，"title cannot be displayed completely" is a very serious problem, please pay attention to it，thx！

**Comment by klcb2010** [comment]
> @klcb2010 Are the screenshots (after and before Nightl98.0a1) from the same device?
where are you going ? i need you now

**Comment by kbrosnan** [comment]
Duplicate https://github.com/mozilla-mobile/fenix/issues/26159

**Comment by uok** [comment]
@kbrosnan, this is not a duplicate! 
As the issue opener describes the layout has changed (added padding) which causes smaller titles

**Comment by cadeyrn** [comment]
@uok 

The issue opener wrote:

> the history or recentVisits is displayed on the homepage as a shortcut

This *is* a duplicate of #26159

The issue opener also wrote:

> and the title cannot be displayed completely.

Restoring the previous tiles layout was already fixed in Firefox 107.
