### ISSUE TITLE
[Bug]: about:logo page showes the false logo

### ISSUE THREAD

**Issue by wheelseal** [mozilla-mobile/fenix#27417]
### Steps to reproduce

1. type about:logo in the url-bar and press enter

### Expected behaviour

Firefox for Android Logo should displayed

### Actual behaviour

If you see on my Screenshot the Logo of firefoyx Nightly is shown.
![firefoy nightly logo](https://user-images.githubusercontent.com/61382908/195937489-217b48a8-891c-4796-8634-1e8b076223fe.png)

### Device name

Sony Xperia 10lll

### Android version

Android 10

### Firefox release type

Firefox

### Firefox version

105.2.0 (Build #2015907747), 01fbfd637+

### Additional information

This bug is not important to keep Firefox running. But I read something about this side comes from Gecko and can not be removed. So I thing it looks much better it showes the right logo.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21804)

**Comment by kbrosnan** [comment]
This is an artifact of how Geckoview is built. It is not used for anything on Fenix. See bz-1610528 with some discussion about removing it.
