### ISSUE TITLE
[Bug]: Photo pixels on Google Pixel 7 Pro

### ISSUE THREAD

**Issue by INTRASERVER** [mozilla-mobile/fenix#27420]
### Steps to reproduce

1. This happen very in the xda-forum
2. When you look forum and open photos.
3.  Then comes random pixels (This happened on Pixel 6 Pro as well, but fixed with update from Mozila. (Bugfix: Fixed image and animation corruption on Pixel 6, 6 Pro and 6a devices running Android 13) this is now with Pixel 7 Pro. )
4. 
![PXL_20221015_013709465](https://user-images.githubusercontent.com/97578992/195963262-9788e6af-c850-42dc-8491-2d347033091d.jpg)

### Expected behaviour

Glitch random pixels, like gpu issue

### Actual behaviour

Ransom pixels when you watching photos 

### Device name

Google Pixel 7 Pro

### Android version

13

### Firefox release type

Firefox

### Firefox version

105.0

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21805)

**Comment by mooninite** [comment]
I also see similar graphic corruption on the reddit.com mobile site. It appears around the animated reddit logo on page loads and also on the award button logo on a page that lists posts. It goes away if I open an additional tab and then go back to the reddit tab.

Pixel 7 Pro
Firefox 105.2.0
October 2022 Android update

**Comment by kbrosnan** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1795614

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Comment by jamienicol** [comment]
@INTRASERVER @mooninite can you please go to about:support, click "copy text to clipboard", and attach the text to this bug

**Comment by jamienicol** [comment]
Brilliant, thank you. We should have this fixed soon.

**Comment by INTRASERVER** [comment]
> @INTRASERVER @mooninite can you please go to about:support, click "copy text to clipboard", and attach the text to this bug

Here is mine.
[aboutsupport.txt](https://github.com/mozilla-mobile/fenix/files/9803246/aboutsupport.txt)
