### ISSUE TITLE
Filter for listing up only modified settings in about:config

### ISSUE THREAD

**Issue by masayuki-nakano** [mozilla-mobile/fenix#27426]
Fenix's about:config does not have an ability to filter only modified prefs. 

### What is the user problem or growth opportunity you want to see solved?

It's necessary to check whether there is non-default value prefs when I found somthing which is reproducible only in specific device.

### How do you know that this problem exists today? Why is this important?

For smoother debugging a bug which I met in specific device.

### Who will benefit from it?

Nightly testers and developers including developers of Gecko.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21811)

**Comment by kbrosnan** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1800565

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Comment by kbrosnan** [comment]
about:config is provided by GV
