### ISSUE TITLE
[Bug]: Unable to login to wendy's website with Google

### ISSUE THREAD

**Issue by brij1234** [mozilla-mobile/fenix#27421]
### Steps to reproduce

1. Go to [wendys.com](https://order.wendys.com/rewards-store) and login with Google 
2.  Firefox asks if it's ok to pop up a window. Hit allow and then login with Google.

Here's the Firefox warning that pops up:
![image](https://user-images.githubusercontent.com/9251787/195963626-16ce3a87-6430-4d2f-b21f-6180260be678.png)

### Expected behaviour

successflully logging in to the Wendy's website with Google

### Actual behaviour

eturns to the wendy's page without logging me in.

### Device name

Pixel 6

### Android version

13

### Firefox release type

Firefox

### Firefox version

105.2.0

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21806)

**Comment by ksy36** [comment]
I did a bit of diagnosis in https://github.com/webcompat/web-bugs/issues/112353#issuecomment-1309439590 and it looks like the auth flow is not working because of a timing issue that needs to be addressed by the site/ library maintainers.

**Comment by kbrosnan** [comment]
Not a Fenix bug.
