### ISSUE TITLE
Web content cannot be interacted with using touch gestures; switching tabs shows no change

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/fenix#27427]
### Steps to reproduce

n/a, regular web browsing with tab and app switching.

Current device state: battery saving mode.

### Expected behaviour

- Web content is interactable.
- Next tab is rendered when tab switching.

### Actual behaviour

- Web content is frozen and unusable.
- Fenix Android UI is functional.
- Switching tabs shows the previous tab's web content with only toolbar changes.

(see video below)

### Device name

Google Pixel 3

### Android version

Android 12

### Firefox release type

Firefox Beta

### Firefox version

106.0b5 (Build #2015908379), acdaf02af+

### Device logs

Profile (Threads: GeckoMain, Compositor, Renderer, SwComposite, DOM Worker; Screenshots,JavaScript,Native Stacks,CPU Utilization,Java): https://share.firefox.dev/3CBEHx8

Profile (Nightly preset): https://share.firefox.dev/3CFJ6zf

[device_logs.txt](https://github.com/mozilla-mobile/fenix/files/9793444/device_logs.txt)

### Additional information

106.0b5 (Build #2015908379), acdaf02af+
AC: 106.0.4, 36dfe0d2d0
GV: 106.0-20221006191955
AS: 94.2.1

https://user-images.githubusercontent.com/1370580/196013986-db5dcee4-a5fa-470d-b43a-9e1ca9b1f8e2.mp4

https://user-images.githubusercontent.com/1370580/196013990-22d23d7b-bf84-4032-add9-a86fffea5d3e.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21812)

**Comment by jonalmeida** [comment]
There was a report about this bug on Matrix as well and I ran into it in the wild.

**Comment by jonalmeida** [comment]
Offline it was shared that this is a duplicate of https://github.com/mozilla-mobile/fenix/issues/24563. Leaving this open for now since there are useful profiles on it which someone might want to move to the other issue first.

**Comment by jonalmeida** [comment]
From the community member on Matrix:

> Interesting fact, today I get a slightly different behavior: the new tabs are still bugged, but they act as connected tabs, if I open a new website on one, all other tabs opened together with that one shows the same website.
> Before, like in my video, the new tabs only showed whatever was on screen on the previous tab. 
> Still happens only on duckduckgo when I open an image. And yes, it opens more than 1 tab. Like 3 or 4 together. Which act as a single tab but now they "work", they open a website. 
> 
> As for a profile: https://profiler.firefox.com/public/xjtf3kd0nrgqbh1dajh1tsr2y96wtm7gtgvk5n8
> 
> Device: Realme 3 Pro with Android 11. Model is RMX1851.

**Comment by jonalmeida** [comment]
cc: @mcarare ^

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813442

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
