### ISSUE TITLE
SCREEN ALWAYS ON

### ISSUE THREAD

**Issue by blakbin** [mozilla-mobile/fenix#27447]
## Steps to reproduce
Open any web page (ex. This page). Dont touch any. Screen not timeout after loading web page
### Expected behavior
Screen must off after set of time of the phone settings
### Device information

* Android device: Poco X3 android 12
* Fenix version: 105.2.0 (Build #2015907747), 01fbfd637

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21818)

**Comment by jluttine** [comment]
FWIW, I have the same issue.

Fennec F-Droid version: 105.1.0 (Build #1051020)
Android version: LineageOS 19-20221114-NIGHTLY, Android 12

To me this seems like a significant security issue.

**Comment by makotokato** [comment]
@jluttine @blakbin 

Could you provide exactly reproduce step?

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813441

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Comment by cpeterso** [comment]
If you can still reproduce this bug, please share in the Bugzilla bug tracking this issue: https://bugzilla.mozilla.org/show_bug.cgi?id=1813441
