### ISSUE TITLE
Add AD_ID Permission to AndroidManifest.xml for Android 13

### ISSUE THREAD

**Issue by ohall-m** [mozilla-mobile/fenix#27458]
For Android 13, we need to update the AD_ID Permission.

🚧 **NOTE: Need to coordinate before landing change.**

More info: 
* [Info on Google Play and Advertising ID](https://support.google.com/googleplay/android-developer/answer/6048248?hl=en)
* JIRA Issue [FNXV2-21091](https://mozilla-hub.atlassian.net/browse/FNXV2-21091)
* Bugzilla Issue [1791114](https://bugzilla.mozilla.org/show_bug.cgi?id=1791114)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21823)

**Comment by ohall-m** [comment]
Fenix Nightly now has the correct flag set in GPS that corresponds to this permission change.

**Comment by ohall-m** [comment]
This is ready for review now that Fenix Nightly has been updated. Should land before Android 13 updates.

**Comment by AdinaPetridean** [comment]
Hi @ohall-m!
What scenario need to be tested here?
Thank you!

**Comment by ohall-m** [comment]
Forgot to remove the tag, this doesn't need QA. Thanks!
