### ISSUE TITLE
"Sync now" button has no effect on specific device, unable to use sync feature.

### ISSUE THREAD

**Issue by dubiousfox** [mozilla-mobile/fenix#27471]
### Steps to reproduce

I expect this to only happen on some devices, but:

1. Connect Android and Desktop devices, either using QR code or email
2. On Android, go to Settings -> Account settings -> Synchronise now

### Expected behaviour

Some message indicating that synchronisation is happening would appear. After waiting for the action to finish, information between the two devices would be synchronised.

### Actual behaviour

Button looks like it is pressed (background changes to gray when tapped), but nothing happens. Waiting enough time on the same screen will change "Last synchronised: never" to "Last synchronised: 1 Jan 1970"

### Device name

Xiaomi Mi A2 Lite

### Android version

Android 10

### Firefox release type

Firefox

### Firefox version

105.2.0 (Build #2015907747)

### Device logs

https://gist.github.com/dubiousfox/e9b2b6236ae1ac8d7887cc14fe9b892b

I tried to use logcat, but every second it would write several lines and it would overwrite over the terminal space over and over. Eventually after trying multiple times, the messages slowed down enough that I could tap on "synchronise now" and see what was being written before it resumed with the previous messages. I tried to catch that. If I can give better logs just instruct me how and I will!

### Additional information

Have tried reinstalling the app. Have replicated the bug in Firefox Beta as well. 
Both devices show up properly in "Connected Services".
Tapping the "Sync" button in the Synchronised tabs section will change it to "Synchronising" for a long while, but then reverts back to normal and nothing happens.
Thing that _might_ be related or might be simple lag: I cannot replicate this super consistently, but very often when I re-open firefox after a while of inactivity, it will show "sign in to synchronise" instead of my email. Screencap of this:
https://user-images.githubusercontent.com/50632929/196806403-8d394144-5e55-4197-8f02-4ea32dd7488d.mp4

I will gladly provide any kind of info if needed. Thank you for your work!

Screenshot and screencap of main bug at hand:
![1 jan 1970](https://user-images.githubusercontent.com/50632929/196806705-8f909d7f-c31f-425e-8d78-4122bd7638e0.jpg)
https://user-images.githubusercontent.com/50632929/196806576-abdac9f4-55d3-4460-b544-57c6a0db84ea.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21833)

**Comment by Jurtaani** [comment]
Same issue, but with Xperia 1 running the latest official android 11 updates from Sony.
Also, i'm running the newest Nightly instead of stable.
other than that, my symptoms are the same.

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812111

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
