### ISSUE TITLE
Capture telemetry for Google Play Store Review prompts

### ISSUE THREAD

**Issue by amedyne** [mozilla-mobile/fenix#27472]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)
We currently occasionally ask our users to rate our app in the Play Store via a prompt. There have been some reports from our users that we repeatedly ask them to review the app and that the prompt appears at odd hours. 

### What is the user problem or growth opportunity you want to see solved?
We want to understand and capture actual data on this app feature and behavior to better understand what is happening in the wild. 
- We need data on when and how often we ask our users to rate the app
- How many people rate the app or ignore the prompt

### How do you know that this problem exists today? Why is this important?
User reports thru SUMO. 

### Who will benefit from it?
The data will help us validate user reports and make adjustments in our implementation.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21834)

**Comment by kbrosnan** [comment]
Is there some way we can track the time between prompts.

**Comment by t-p-white** [comment]
> How many people rate the app or ignore the prompt
I don't believe this particular requirement is possible due to the prompt being handled by com.google.android.play.core.review.ReviewManager. The function launchReviewFlow does not provide any return data to consume.
Perhaps this data is available from another source

**Comment by amedyne** [comment]
@t-p-white I think the following will be useful in understanding what our users experience: 
- attempt_prompt_display [boolean]
- prompt_was_displayed [boolean]
- prompt_was_not_displayed [boolean]
- number of times the app has been opened [quantity] : don't we already have this in telemetry?

Is there a way to connect the following time elements to the prompts being displayed to the user?
- current datetime of device [datetime]
- when the user was last prompted [datetime]

**Comment by t-p-white** [comment]
Ok, great, thanks for the info.
> number of times the app has been opened [quantity] : don't we already have this in telemetry?

I can't see this recorded in either Fenix or Focus, will confirm with @rocketsroger.

 >  current datetime of device [datetime]
    when the user was last prompted [datetime]
    
Will need to have a look into this further as intial attemp for an 'Event' item to include a datetime element as part of an extra key would not build

**Comment by onemahon** [comment]
> However, it is possible to determine whether the prompt was displayed or not.

@t-p-white out of curiosity, how do you go about determining that? I'm not super familiar with this API, but [the ReviewManager doc](https://developer.android.com/reference/com/google/android/play/core/review/ReviewManager#launchReviewFlow(android.app.Activity,%20com.google.android.play.core.review.ReviewInfo) seems ambiguous about whether you can tell it's successfully shown or not:

> Note: In some circumstances the review flow will not be shown to the user, e.g. they have already seen it recently, so do not assume that calling this method will always display the review dialog.

**Comment by rocketsroger** [comment]
> @t-p-white out of curiosity, how do you go about determining that?

We and @t-p-white had a short discussion and looks like we can't tell if it was shown to the user or not.
This is from doc and from some debugging answered the question.
    // The API does not indicate whether the user
    // reviewed or not, or even whether the review dialog was shown.

**Comment by t-p-white** [comment]
> seems ambiguous about whether you can tell it's successfully shown or not

@onemahon thanks for highlighting that, yes, I should have updated with a comment. It can only be determined whether there was an attempt to display the prompt or not. If the retrieval of ReviewInfo (from requestReviewFlow) is successful the app will attempt to prompt - if it is not successful it could also be captured in the telemetry.

Perhaps it would be useful to capture the following:
* requested_review_info [boolean] 
* prompt_was_attempted [boolean]
* prompt_was_not_attempted [boolean]

**Comment by kbrosnan** [comment]
One of the comments that lead use to ask for this is people saying that they are prompted too often to rate Firefox. I would like some way to track how much time elapses between our prompts.

**Comment by jr-johnson-support** [comment]
JR on the Customer Experience Team here:

We have been tracking complaints about the review prompt since Apr, 2022. 90 google play store reviews seen at this time with more added weekly. 

Due to the lack of back and forth questioning ability in Google Play Store it is a bit hard to investigate further on how often the prompt is showing up. Though from those reviews we see users note:

* Complaining about multiple requests for app reviews
* Complaining about the review popup showing up when they are typing or about to click on links.
