### ISSUE TITLE
F-Droid repository

### ISSUE THREAD

**Issue by maverick74** [mozilla-mobile/fenix#27473]
I would like to suggest Firefox having it's own F-Droid repo.

This would benefit F-droid users as they would be sure to be getting an official Mozilla product.

It would end with the need for non-oficial repos.

And would speed up the Firefox release (as opposed to playstore that keeps getting late by a few days)

Fennec does not provide the complete experience!

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21835)

**Comment by mitexleo** [comment]
Agreed 👍

**Comment by kbrosnan** [comment]
this needs bz-1811655

**Comment by maverick74** [comment]
@kbrosnan While i understand (and totally agree) your point at 1811655, i just don't get it why you actually closed this issue!

I understand it's not planned (like, say, 80% of FF requests...) but i really don't understand the reason for closing this...

**Comment by kbrosnan** [comment]
We are moving all bug/issue tracking to BugZilla. See the pinned issue at the top level of this issue tracker. More or less a duplicate of the bug I mentioned.
