### ISSUE TITLE
[Bug]: selecting text to the end of a paragraph moves the selection to the start of the section 

### ISSUE THREAD

**Issue by krijos** [mozilla-mobile/fenix#27482]
### Steps to reproduce

1. Go to: https://www.wowhead.com/news/odyns-manipulation-revealed-what-dont-we-know-about-the-black-empire-329383
2. Select some text from the content.
3. Drag the selection to the end of the paragraph.

### Expected behaviour

Text should be selected in a predictable and controllable manner.

### Actual behaviour

Text selection jumps to the start of the section.

### Device name

OnePlus 5

### Android version

Android 11 Lineage OS

### Firefox release type

Firefox

### Firefox version

106.1.0 (Build #2015909131), 71ca6c1f7+

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21838)

**Comment by kbrosnan** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1796622

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
