### ISSUE TITLE
File picker does not show all available apps e.g. NextCloud

### ISSUE THREAD

**Issue by mrleerkotte** [mozilla-mobile/fenix#27492]
### Steps to reproduce

1. Go to a site with a file upload button
2. Try to find for example NextCloud in the Open from dialog
3. Not available

### Expected behaviour

Expected behaviour would be being able to select files from NextCloud or other cloud storage apps. See for example Chromium based behaviour, where NextCloud & Termux are available.
![image](https://user-images.githubusercontent.com/9341709/197161827-edf30719-545d-4f5a-b325-87247f388321.png)

### Actual behaviour

The file picker only shows a small subset of apps.
![image](https://user-images.githubusercontent.com/9341709/197161853-e19d6c9c-9705-4efe-9075-69fdbc02dcc9.png)

### Device name

Samsung Galaxy S22 Ultra

### Android version

Android 12, OneUI 4.1

### Firefox release type

Firefox

### Firefox version

106.1.0

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21843)

**Comment by rickdoesdev** [comment]
Also having this issue on Android 13, Pixel 5, Firefox version 107.1.0 (Build #2015915067)

When using a standard file upload input on Firefox:

![Screenshot_20221121-223004](https://user-images.githubusercontent.com/4494839/203041040-a349b811-3617-4ed0-a025-2fc35c937358.png)

When using the same standard file upload on Chrome or even other non browser apps such as slack, or nextcloud itself:

![Screenshot_20221121-222839](https://user-images.githubusercontent.com/4494839/203041269-101fc944-e8be-4eff-8033-fca4be7ef0c2.png)

In apps other than Firefox the other apps tray scrolls and has various data sources including multiple google drive sources, the nextcloud account, and misc other data sources.

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812110

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
