### ISSUE TITLE
"source": "HOME" string is missing from the log when accessing "What's new"

### ISSUE THREAD

**Issue by SoftVision-LorandJanos** [mozilla-mobile/fenix#27495]
### Steps to reproduce

1. Launch Fenix and from the Homescreen tap on the Menu button (3dot) and tap on "What's new".
2. Send Fenix in background.
3. Check the https://debug-ping-preview.firebaseapp.com/ for the triggered pings or the Android Studio logcat;

### Expected behaviour

User is redirected to a support Mozilla webpage describing the latest Fenix updates.
An events type ping is generated:

"name": "whats_new_tapped",
"extra": {
"source": "HOME"
}

### Actual behaviour

The following log is shown:

{
          "timestamp": 3483,
          "category": "events",
          "name": "whats_new_tapped"
}

### Device name

Google Pixel 4

### Android version

Android 12

### Firefox release type

Firefox Beta

### Firefox version

107.0b2

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21845)

**Comment by Mugurell** [comment]
@SoftVision-LorandJanos According to https://dictionary.telemetry.mozilla.org/apps/fenix/metrics/events_whats_new_tapped there is no extra key expected.
Searching in git history it seems like the `source` extra key was removed more than two years ago in https://github.com/mozilla-mobile/fenix/pull/7793.
This does not seem like a recent regression. Are there any tickets you know of which asked to re-add the `source` details?

**Comment by Mugurell** [comment]
Since the telemetry was updated with no clear decision as for why the `source` extra key was removed or not I've opened https://mozilla-hub.atlassian.net/browse/DS-2298 to ask DS the extra key should be added back or the test plans should be updated.

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1809328

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
