### ISSUE TITLE
Bookmark/history search: search results limited to 20 entries

### ISSUE THREAD

**Issue by WebworkrNet** [mozilla-mobile/fenix#27509]
### Steps to reproduce

1. Bookmarks / History: Open the search
2. Run a search.

### Expected behaviour

All results found will be returned.

To increase transparency, the number of search results should be displayed to the user as a number.

### Actual behaviour

If more than 20 search results are returned, the result list terminates after the 20th position.
This makes it unclear to the user whether exactly 20 results were found or the list output was just aborted.

### Device name

Samsung Galaxy A13 5G (SM-A136B/DSN)

### Android version

Android 12

### Firefox release type

Firefox

### Firefox version

105.1.0 (Build #1051000), b1e7cbeeb+ AC: 105.0.7, e2aeb82d54 GV: 105.0-20220922015904 AS: 94.1.0

### Additional information

Fennec (F-Droid)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21853)

**Comment by SoftVision-LorandJanos** [comment]
Hi @WebworkrNet! Thanks for your report!
I can confirm the limit for search result in history/bookmark search is 20.
Tested on the latest RC (106.1.0) and on the latest Nightly 108.0a1 (2022-10-27).
Device used: Opo Find X5 (Android 12).

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807587

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
