### ISSUE TITLE
Firefox is freezing when openning about:config

### ISSUE THREAD

**Issue by pierreonthenet** [mozilla-mobile/fenix#27503]
When i try to open "about:config" in Firefox for Android 106.1.0 (Build #2015909131), 71ca6c1f7+, it freezes and I only can close it to make it working again.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21849)

**Comment by cadeyrn** [comment]
I can not reproduce the freeze. But please note that there is no about:config in stable releases of Firefox for Android. So it's expected to only see a white page.

**Comment by pierreonthenet** [comment]
OK, thank you for the info. That's too bad.
If it doesn't exists, it's a really little bug that doesn't need a fix, i guess.
Is there a ticket about adding "about:config" to Firefox for Android ? 

Maybe it's because of my really big number of opened tabs that it freezes.

**Comment by kbrosnan** [comment]
`about:config` is not enabled in release builds. duplicate https://github.com/mozilla-mobile/fenix/issues/7865
