### ISSUE TITLE
Awesomebar should display more than three history search results

### ISSUE THREAD

**Issue by lilydjwg** [mozilla-mobile/fenix#27504]
### Steps to reproduce

1. use for some time make a lot of history urls
2. type something to search for a specific but not recently/frequently used history urls
3. but it also matches other more recent history urls

### Expected behaviour

Several matches should be shown as long as they exist.

### Actual behaviour

Only three or less urls from history are shown.

I have a very good experience with Firefox on Desktop to search my visit history, but with Firefox on Android for the most of time I can't find my history urls because there are only three slots for them to show up (if I remember the exact url it can even autocomplete as I type). I can search and find them in the history listings but it takes too many touches to get there and is not the usual way Firefox has educated users to do things.

### Device name

Sony Xperia XZ2 Compact

### Android version

Android 10

### Firefox release type

Firefox Nightly

### Firefox version

108.0a1

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21850)

**Comment by csadilek** [comment]
This is by design. History suggestions were limited to 3 results: https://github.com/mozilla-mobile/fenix/blob/775258db6b6a764f73fd9739008baeb3d379799a/app/src/main/java/org/mozilla/fenix/search/awesomebar/AwesomeBarView.kt#L379

I will turn this into a feature request, because I think it's reasonable to increase this.

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812108

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
