### ISSUE TITLE
FNX3-16553 ⁃ [Bug] Tab collection constraints break when expanding a collection

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#2750]
I thought doing a `view.invalidate()` would be sufficient for fixing this problem, but I've noticed it happening again. 

See #2625 for more information.

![](https://user-images.githubusercontent.com/4400286/57961674-65018680-78c5-11e9-825f-d871f420895d.png)

I think this should be a bug we fix shortly after feature freeze due to how broken it can make the home view look.

## STR
1. Create several collections with many names
1. Open many tabs
1. Expand/Collapse collections, scroll to different locations in the list, repeat.

## Expected
1. The chevron stays close to the title of the collection

## Actual
1. The chevron has broken constraints

**Comment by sblatz** [comment]
This looks to have been fixed by @ekager's PR: https://github.com/mozilla-mobile/fenix/pull/2851

I'm going to remove the `invalidate` call since it's no longer needed 😄

**Comment by sv-ohorvath** [comment]
Cannot reproduce, looks like it's fixed. build:6/8
