### ISSUE TITLE
Allow filtering by file type in download manager

### ISSUE THREAD

**Issue by anotherus3r** [mozilla-mobile/fenix#27506]
### What is the user problem or growth opportunity you want to see solved?

Allow users to filter downloads by file type. This could be implemented through so-called [filter chips](https://m3.material.io/components/chips/overview#choice-chips), as it is in Chrome.

Filter chips in Chrome's download manager:
![Screenshot_20221023_153021.jpg](https://user-images.githubusercontent.com/20287690/197395275-55a12b51-69ed-47b6-8667-7ad87ec7e0d0.jpg)

### How do you know that this problem exists today? Why is this important?

Users might want to find a certain file based on its file type (e.g. if they don't know the name of the file, but can easily identify it by its file type). Firefox's download manager is too basic. It lacks basic filtering and sorting features, and it doesn't even show all downloads.

Somewhat related (and maybe even more important than this) are the following issues:

- #14894 - sorting downloads
- #14961 - showing active and failed downloads

### Who will benefit from it?

Users who often download files through Firefox.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21851)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1810838

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
