### ISSUE TITLE
Remove duplicate padding update code in allowUndo

### ISSUE THREAD

**Issue by fice-t** [mozilla-mobile/fenix#27511]
This padding update is already performed in `FenixSnackBar.make` when `isDisplayedWithBrowserToolbar` is true, and that variable has no other side-effects, so simply use that code.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21855)

**Comment by delia-pop** [comment]
Hi, @fice-t , is there something that QA should verify? If not, we can go ahead and close the ticket and remove the QA Needed label. Thank you!

**Comment by fice-t** [comment]
I'm not sure how much QA is needed here (I just left the QA box checked as it was the default), but the change involved the padding code for `allowUndo` snackbars, so QA could verify that snackbars for undoing tab closing is padded correctly with respect to the bottom toolbar.

**Comment by SoftVision-LorandJanos** [comment]
Verified on the latest Nightly 108.0a1 (2022-11-10) build.
There are no issues with the padding on the bottom toolbar on undoing closing tab snackbars.
Device used: Oppo Find X5 (Android 12).

**Comment by SoftVision-LorandJanos** [comment]
Verified on the latest Beta 108.0b1.
Device used: Google Pixel 4 (Android 13).
