### ISSUE TITLE
[Bug]: Tab crash when restoring google earth tab

### ISSUE THREAD

**Issue by ceisserer** [mozilla-mobile/fenix#27515]
### Steps to reproduce

1. Switch active tab to desktop mode
2. Load google earth (earth.google.com)
3. Close the tab
4. Restore the tab ("Undo"); also sometimes happens when browser was in background and is brought foreward
5. Tab crashed

### Expected behaviour

tab should restore as expected

### Actual behaviour

Tab crashes

### Device name

Xiaomi Poco F3

### Android version

Android 12

### Firefox release type

Firefox Nightly

### Firefox version

108.0a1

### Device logs

https://crash-stats.mozilla.org/report/index/837bfb0c-12e7-42ac-a427-d1a040221024

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21856)

**Comment by AdinaPetridean** [comment]
@ceisserer  thank you for your report! I was able to reproduce this issue on: Firefox Nightly 108.0a1 from 10/26 with One plus 9 Pro (Android 12).
