### ISSUE TITLE
[Bug]: Set as default browser doesn't get set to true

### ISSUE THREAD

**Issue by iorgamgabriel** [mozilla-mobile/fenix#27524]
### Steps to reproduce

1.Install a debug Firefox Fenix build 108 .
2.Go to settings.
3.Set Fenix as default browser.
4.Toggle remains the same , set to false.

### Expected behaviour

The toggle should be set to true.

### Actual behaviour

Toggle remains the same , set to false.

### Device name

Pixel 3Xl 

### Android version

android 12

### Firefox release type

Firefox

### Firefox version

108

### Additional information

https://mozilla-hub.atlassian.net/browse/FNXV2-21857

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21862)

**Comment by SoftVision-LorandJanos** [comment]
Verified as fixed on the latest nightly 108.0a1 (2022-10-31) build.
Device used: Oppo Find X5 (Android 12).
Closing the ticket as fixed.

**Comment by SoftVision-LorandJanos** [comment]
Verified as fixed on the latest Beta 108.0b1.
Device used: Google Pixel 4 (Android 13).
