### ISSUE TITLE
[Bug]: 没人处理反馈。

### ISSUE THREAD

**Issue by klcb2010** [mozilla-mobile/fenix#27526]
### Steps to reproduce

详情在这里，https://github.com/mozilla-mobile/fenix/issues/27402

每夜版106以上和目前发布的106都是这样

### Expected behaviour

不需要

### Actual behaviour

不需要

### Device name

K30pro

### Android version

安卓10

### Firefox release type

Firefox Beta

### Firefox version

106

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21863)

**Comment by mcarare** [comment]
@klcb2010 Thank you for the initial report. There is no need to open new issues just for referencing existing ones. 

Closing this as duplicate.
