### ISSUE TITLE
Middle mouse click to open link into a new tab

### ISSUE THREAD

**Issue by good2see** [mozilla-mobile/fenix#27520]
On **Dex** and **EMUI Desktop mode** middle scroller click on Firefox doesn't open links into new tab.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21860)

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813440

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
