### ISSUE TITLE
Upgrade Jetpack Compose to 1.3.0 

### ISSUE THREAD

**Issue by mcarare** [mozilla-mobile/fenix#27536]
A new stable version for Jetpack Compose has been released: [Release notes](https://developer.android.com/jetpack/androidx/releases/compose-foundation#1.3.0).

Note: Occurrence of [this](https://bugzilla.mozilla.org/show_bug.cgi?id=1792796) existing crash after the update should be tracked.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21865)

**Comment by cpeterso** [comment]
We hope that updating to Compose 1.3.0 will fix some recent Fenix crash regressions: https://bugzilla.mozilla.org/show_bug.cgi?id=1792796

**Comment by mcarare** [comment]
No specific QA for this change, just the regular app user testing (most of the Composables are on the home screen/ tabs tray/wallpaper settings).

**Comment by delia-pop** [comment]
Tested with Nightly 109.0a1 from 12/03 with Google Pixel 6 (Android 13). No issue encountered while using the app throughout the day.
