### ISSUE TITLE
Collect shim information about sponsored stories interactions

### ISSUE THREAD

**Issue by Mugurell** [mozilla-mobile/fenix#27549]
As a followup to the Pocket sponsored stories feature and the telemetry ticket - https://github.com/mozilla-mobile/fenix/issues/25401 we need to collect the shim parameter of each story the user interacts with, both when the story is shown and clicked.

Based on the discussions with @Dexterp37 on https://mozilla-hub.atlassian.net/browse/FNXV2-21791 for this we should:
- add a new custom ping
- create new metrics of type `text` in which to send the shim.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21870)

**Comment by Dexterp37** [comment]
@Mugurell it should be a [text type](https://mozilla.github.io/glean/book/reference/metrics/text.html), not a string type.

**Comment by Mugurell** [comment]
Testing the just landing code I see the shim data is sent immediately and contains the expected values - https://debug-ping-preview.firebaseapp.com/pings/spocShims.
