### ISSUE TITLE
Rename "Delete" to "Disable" for removing default search engines in settings

### ISSUE THREAD

**Issue by WebworkrNet** [mozilla-mobile/fenix#27559]
### What is the user problem or growth opportunity you want to see solved?
Currently, it is only possible to delete search engines that have already been stored.
Deactivation is currently not possible.

### How do you know that this problem exists today? Why is this important?
If I delete a search engine in the settings, I have to create it again, should I change my mind later.

### Who will benefit from it?
Everyone will benefit who uses multiple search engines.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21871)

**Comment by kbrosnan** [comment]
Delete moves the search engine to the add search engine view if it is a default. If it is a custom one it is deleted. Which type of search engine are you asking about?

**Comment by WebworkrNet** [comment]
I had asked in general because I assumed that the browser makes no difference there. In both cases the label of the button is "delete".

My suggestion would be the following after gaining knowledge:

***Predefined search engines**: 
Adjust caption to "disable".

**Custom search strings**: 
Implement disabling in addition to deleting.

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813439

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
