### ISSUE TITLE
[Bug] Bookmarks folders not synced

### ISSUE THREAD

**Issue by leobel96** [mozilla-mobile/fenix#2755]
## Steps to reproduce
Add android device to sync chain

### Expected behavior
All the bookmarks and the folders of bookmarks should appear in the library

### Actual behavior
Only the bookmarks not inside folders appear

### Device information
Nokia 7 plus

* Android device: 9
* Fenix version: 1.0.1921

**Comment by vesta0** [comment]
Addressed in #2252
