### ISSUE TITLE
Firefox does not switch automatically between Light <> Dark theme if it was closed when OS theme is changed

### ISSUE THREAD

**Issue by andreynering** [mozilla-mobile/fenix#27568]
### Steps to reproduce

1. Setup Firefox for Android to switch automatically between Light <> Dark theme according to the Android
2. Close Firefox
3. Switch to the other theme on Android (from Light to Dark or vice-versa)
4. Open Firefox again

### Expected behaviour

When opening, Firefox should detect which theme is being set on Android and switch accordingly.

### Actual behaviour

When Firefox opens, it won't automatically switch to the right theme as it should. For example, if it was in the Light theme the last time you opened, it won't automatically switch to the Dark theme, even if Android is on Dark theme and Firefox is setup to follow the OS.

When Firefox is kept open during the switch, it works as expected. But it doesn't work if Firefox was closed during the OS theme switch.

This bug happens independently of _how_ the theme was changed. If you change it manually, it happens. If you have you phone setup to automatically switch to Dark theme at night and back to Light during the day, this problem also happens.

### Device name

Samsung Galaxy S20 FE | SM-G780G/DS

### Android version

Android 12

### Firefox release type

Firefox

### Firefox version

106.1.0

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21873)

**Comment by andreynering** [comment]
I forgot to say that, if you closed and re-open Firefox a second time, it then switches the theme for some reason. But I find it annoying to have to do that. It should certainly switch on the first time it opens.

**Comment by fice-t** [comment]
I was able to reproduce this only on my Samsung device and with a ~2 weeks old Nightly version. Updating to the latest Nightly resolved this for me, so it's possible that this is another bug fixed by the recent AndroidX library updates.

@andreynering Could you try downloading the Firefox Nightly version from the Play Store to see if you can reproduce using that version?

**Comment by andreynering** [comment]
@fice-t I can confirm the bug does not happen with the nightly version 👍 

I'm happy to see this bug fixed after so long.

Thanks!

**Comment by andreynering** [comment]
Hi @fice-t, 👋 

It has been a while, but I still see this bug happening on stable, every single day.

Wasn't this patch released to stable yet? If it was, I kindly ask to reopen this issues because it didn't work for some reason.

Thanks!

**Comment by cpeterso** [comment]
> I still see this bug happening on stable, every single day.
> 
> Wasn't this patch released to stable yet? If it was, I kindly ask to reopen this issue because it didn't work for some reason.

I think Firefox Nightly was version 108 when you tested on 2022-10-27, but version didn't reach the stable release until 2022-12-13, seven days after you reopened this bug report. So I _think_ this bug should now be fixed. 

If you can still reproduce this bug, please file a new bug report on Bugzilla here: https://bugzilla.mozilla.org/enter_bug.cgi?product=Fenix

**Comment by andreynering** [comment]
Hi @cpeterso,

I use Firefox for Android daily so I'm sure it is still happening.

Opened bug report at: https://bugzilla.mozilla.org/show_bug.cgi?id=1813529
