### ISSUE TITLE
[Bug]: `contenteditable` with child behaves differently to Firefox desktop and Chrome

### ISSUE THREAD

**Issue by TastyPi** [mozilla-mobile/fenix#27569]
### Steps to reproduce

1. Have the following HTML:

```html
<div contenteditable="true">
  <div style="width:20px; height: 20px; border: solid"></div>
</div>
```

2. Click/tap on the box
3. Type a character

### Expected behaviour

In Firefox desktop, Chrome desktop, and Chrome for Android, the typed character is inserted in the child div. This is the behaviour I would expect.

### Actual behaviour

The typed character is inserted after the child div.

### Device name

Fairphone 4

### Android version

Android 11

### Firefox release type

Firefox

### Firefox version

106.1.0

### Device logs

No logs are produced.

### Additional information

I originally found this issue when testing a `contenteditable` that listens to `beforeinput` events to provide some custom behaviour. In other browsers (including Firefox for desktop) `event.getTargetRanges()` returns a range pointing at the child div, whereas Fenix returns a range that points at the parent div. I assume this inconsistency is related.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21874)

**Comment by kbrosnan** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1797796

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Comment by TastyPi** [comment]
@kbrosnan I filed it in GitHub because this page told me to, should the page be updated? Or is this being counted as a security issue? https://support.mozilla.org/en-US/kb/file-bug-report-or-feature-request-mozilla

**Comment by kbrosnan** [comment]
It is a core bug, the same behavior reproduces on Firefox desktop. This issue tracker only has work done by the Fenix team. https://github.com/mozilla-mobile/fenix/discussions/26566#discussioncomment-3449921

As I mention on the moved bug it seems like an invalid bug. The page tells Firefox to make the image have a height of 0. Which Firefox does. Chrome behavior seems broken to me.

**Comment by TastyPi** [comment]
@kbrosnan no, the same behaviour does not reproduce on Firefox desktop. Firefox desktop behaves the same way as Chrome, only Fenix behaves differently.
