### ISSUE TITLE
Inconsistent failure to load pages

### ISSUE THREAD

**Issue by samking** [mozilla-mobile/fenix#27576]
### Steps to reproduce

This is an inconsistent error.  It's only been happening since I updated to 106.1.0.  Sometimes (I would guess, around 10%-20% of the time?), when I open a new page, the page will be entirely blank.  The loading bar will continue to show on the bottom of the screen, but waiting forever won't do anything.  Reloading the page won't do anything.  Selecting the URL and pressing the return arrow usually makes it better.  Fully closing the tab and reopening it sometimes makes it better.

I notice this issue more when opening a new tab from another app (e.g., the Google app) than when browsing from page to page within Firefox.

Usually, when I try the same page later in the day, it works fine, and when I try the page in Chrome it works fine, which makes it seem like it's not an issue with the website itself or with my network or device, but rather with the Firefox app itself.  But it's inconsistent and I don't have a clear way to reproduce it.

### Expected behaviour

The page should either open correctly or display an error

### Actual behaviour

The page acts like it's loading forever

### Device name

Google Pixel 3a

### Android version

Android 12

### Firefox release type

Firefox

### Firefox version

106.1.0

### Additional information

I use uBlock Origin, but no other add ons.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21879)

**Comment by sheikh-azharuddin** [comment]
Interestingly I am facing this issue in nightly after today' update..pages showing black.if you click home button and come back again it is showing

**Comment by peci1** [comment]
I also see this issue on 106.1 (Android 11). When this happens once, further open pages have increased probability of also being stuck while loading. When this happens, I can't even force-stop the browser. Only rebooting the phone will return it to normal behavior.

I've noticed some addresses are more prone to this bug than others. The most prone (like 90%) is https://forum.fairphone.com/c/help/fairphone4/63 .

**Comment by peci1** [comment]
I've connected debugger to the mobile browser. When I open a new page and it gets stuck as reported here, even the debugger shows nothing - i.e. a blank page, not even the developer tools.

If I go to an open panel and enter one of these addresses that usually get stuck in the devtools address bar, loading of the page is aborted with NS_BINDING_ABORTED (forum.turris.cz in this case) and no error written in the console:

![obrazek](https://user-images.githubusercontent.com/182533/199346624-cc4174c0-f4fc-4ebb-a109-473d6e9dafaa.png)

**Comment by pjaap** [comment]
I can also confirm this.
It startet from version 106 on Android (Fennec from F-Droid) 

Can be worked around by going to home screen and back to Firefox.
Then pages are displayed instantaneously correct. It seems to happen most times when I open the first page after Firefox was unused for a while (a few minutes).

**Comment by fdotymoz** [comment]
I may be experiencing a similar issue on my Pixel 6 Pro, Firefox 107. When attempting to complete a google search or click a link from a google search the page load will hang (for 42 seconds in the attached profile). Clicking the X to stop the load and refreshing leads to the same issue. I need to do this several times in a row OR type an address directly into the awesome bar for a page load to complete. I can reproduce this fairly consistently. If this seems like a different issue, I will create a new ticket.

Attached Profile: https://profiler.firefox.com/public/dvpchza893r75h5acdst1zwfjcp794417gd4gg8/calltree/?globalTrackOrder=40w3&hiddenGlobalTracks=1&hiddenLocalTracksByPid=11050-0~14241-01~13378-2~14574-0w4&thread=9&v=8

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813433

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Comment by cpeterso** [comment]
If you can still reproduce this bug, please share in the new Bugzilla bug here: https://bugzilla.mozilla.org/show_bug.cgi?id=1813433
