### ISSUE TITLE
"Sign in with Google" login open wrong app

### ISSUE THREAD

**Issue by PMPiper** [mozilla-mobile/fenix#27572]
### Steps to reproduce

1. Install an app with "sign in with Google" option (in my case it was the NYC Ferry app https://play.google.com/store/apps/details?id=co.bytemark.nycf&hl=en_US&gl=US)
2. Open link in Firefox that points to a webpage with a Google log in (e.g. https://support.google.com/android/thread/new?hl=en)

### Expected behaviour

Link is opened in Firefox

### Actual behaviour

Another app opens (in my case it was the NYC Ferry app shopping cart)

### Device name

Google Pixel 6

### Android version

Android 13

### Firefox release type

Firefox

### Firefox version

106.1.0

### Additional information

I'm not sure if this is an issue specifically with the NYC Ferry app, but this doesn't happen when opening the same link in the Google Chrome app. This leads me to believe it can be address on the Firefox side of things.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21876)

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813438

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
