### ISSUE TITLE
Permission notification never disappears if the app is dismissed

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/fenix#27586]
### Steps to reproduce

1. Visit https://permission.site
2. Click on 'Camera'.
3. Accept all the permissions required to allow the camera.
4. Open and observe the notifications in the notification tray.
5. Swipe the Fenix app away.
6. Open and observe the notifications in the notification tray.

### Expected behaviour

- At step 4, you should see the 'Camera is on' notification.
- At step 6, you should no longer see the 'Camera is on' notification.

### Actual behaviour

- At 4 and 6 you can see the notification 'Camera is on'.
- The notification never leaves until app is force closed.

### Device name

Google Pixel 3

### Android version

Android 12

### Firefox release type

Firefox Beta

### Firefox version

107.0b3

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21884)

**Comment by jonalmeida** [comment]
Closing as already fixed.

**Comment by sv-ohorvath** [comment]
@jonalmeida I can still reproduce this with the latest from main, with Pixel 2 (on Android 9) and 3 (on Android 11).

**Comment by gabrielluong** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1814205

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
