### ISSUE TITLE
[Bug]: fenix-107.0b4 ，shortcut title cannot be displayed completely

### ISSUE THREAD

**Issue by klcb2010** [mozilla-mobile/fenix#27585]
### Steps to reproduce

the  shortcut title cannot be displayed completely,test on fenix-107.0b4

![IMG_20221028_122241](https://user-images.githubusercontent.com/32628414/198502817-67549a4d-d99e-48f4-a794-1836a9503a6e.jpg)

### Expected behaviour

onto

### Actual behaviour

onto

### Android version

Android 10

### Firefox release type

Firefox Beta

### Firefox version

fenix-107.0b4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21882)

**Comment by AdinaPetridean** [comment]
Hi @klcb2010  Thanks for your report!
I couldn't reproduce your issue on Firefox Beta 107.0b4 nor the latest Nightly 108.0a1 from 14/11.
Can you please provide more details on this issue?

**Comment by klcb2010** [comment]
It seems that the bug related to the file named QI.xml，Change the shortcut title to four character Chinese. you can find the bug，before 107.0b4 .Compared QI with different versions, you will find their differences，such as 107.0b4（Figure 1 ） and 108.0b1（Figure 2）, this bug seems to have been fixed since November 14 (108.0b1，Figure 3). However, the history is displayed on the homepage. like a shortcut, this bug has not been fixed（Figure 4）
![beta 2022 10 31 latest arm64-v8a--QI](https://user-images.githubusercontent.com/32628414/201935193-d9797cdb-1c41-4881-b691-821a3b2566df.jpg)
![beta 2022 11 14 latest arm64-v8a](https://user-images.githubusercontent.com/32628414/201935214-20012695-ee1f-4ee5-8d7a-1d1a36f3167a.jpg)
![beta 2022 11 14 latest arm64-v8a--QI](https://user-images.githubusercontent.com/32628414/201935215-b4cc5ac8-9f9a-433c-8094-177bbe50aabd.jpg)
![微信图片_20221115214235](https://user-images.githubusercontent.com/32628414/201935219-a5ee7cbc-f0d6-4704-8d38-6faa1dff1605.jpg)

**Comment by AdinaPetridean** [comment]
Thank you @klcb2010! After adding sites that are longer than 7 characters to shortcuts, I was able to reproduce this issue on Firefox-107.0b4 with OnePlus 9 Pro (Android 12).

**Comment by klcb2010** [comment]
> Thank you @klcb2010! After adding sites that are longer than 7 characters to shortcuts, I was able to reproduce this issue on Firefox-107.0b4 with OnePlus 9 Pro (Android 12).

the history is displayed on the homepage,as a shortcut,is wether as  a   issue？by the way，when  the Releases  version support custom add ons？

**Comment by gabrielluong** [comment]
We have since reverted the design. I imagine this shouldn't be a problem anymore. Let me know if it still persists. Thanks!
