### ISSUE TITLE
[Bug]: `position: sticky; bottom: 0` elements wobble when the address bar is shown/hidden

### ISSUE THREAD

**Issue by TastyPi** [mozilla-mobile/fenix#27592]
### Steps to reproduce

1. Load up the following HTML:

```html
<!DOCTYPE html>
<html lang="en" style="min-height: 100%; display: grid; place-items: stretch">
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  </head>
  <body style="display: flex; flex-flow: column; margin: 0px;">
    <div style="height: 200vh; background: linear-gradient(blue, white)"></div>
    <button>Adding this button makes the wobble more pronounced</button>
    <div style="position: sticky; bottom: 0; margin-top: auto; background: red">Hello</div>
  </body>
</html>
```

2. Do some scrolling

### Expected behaviour

The red `div` should be firmly glued to the bottom of the viewport at all times

### Actual behaviour

At the start of scrolling if the address bar is being collapsed/expanded the red `div` wobbles. It is more pronounced the faster you scroll.

### Device name

Fairphone 4

### Android version

Android 11

### Firefox release type

Firefox

### Firefox version

106.1.0

### Device logs

No logs

### Additional information

My assumption is when the address bar is collapsed/expanded it moves the `html` element up/down, displays that frame, then does a layout pass which recalculates the position of sticky elements. Ideally sticky elements would be repositioned before displaying the frame.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21887)

**Comment by TastyPi** [comment]
The wobbling also happens with `position: fixed`

**Comment by Mugurell** [comment]
Thank you for the report.
Moving to Bugzilla for more investigations, please follow the progress there.

**Comment by Mugurell** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1798525

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
