### ISSUE TITLE
Font-Weight get's messed up when using background-clip: text on Pixel 6/7

### ISSUE THREAD

**Issue by xdivby0** [mozilla-mobile/fenix#27595]
### Steps to reproduce

Visit this codepen on Firefox Mobile (looks alright on desktop or responsive design mode inside firefox desktop):

https://codepen.io/bengin_cetindere/pen/PoaqQZb

Chrome and Chrome Mobile are consistent with the firefox desktop behavior, only Firefox Android shows issue.

### Expected behaviour

Both divs should render the text with the same font weight. 

### Actual behaviour

Observed in Firefox Android Only: The first div renders the text, dismissing the `font-weight` attribute (text does not have increased font-weight like specified) but making up for it by ... I think increasing the tracking / letter-spacing or similar.

### Device name

Pixel 7 Pro

### Android version

Android 13

### Firefox release type

Firefox

### Firefox version

106.1.0

### Additional information

I tried to lookup why that could be (in the source code) but I got lost in the stuff that's partly here on github but gecko itself not being there... If someone more experienced could point me into the right direcition I'd also be glad to contribute myself :)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21890)

**Comment by kbrosnan** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1798036

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
