### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by amccoy23** [mozilla-mobile/fenix#27594]
logins and passwords menu aren't working properly

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21889)

**Comment by cadeyrn** [comment]
What does "aren't working properly" mean? Please provide steps to reproduce, the expected result, the actual result, the affected Firefox version and information about your device like vendor, model and Android version. Or short: Everything you are asked for in the [bug reporting template](https://github.com/mozilla-mobile/fenix/issues/new?assignees=&labels=%F0%9F%90%9E+bug%2Cneeds%3Atriage&template=---bug-report.yml&title=%5BBug%5D%3A+).

**Comment by amccoy23** [comment]
Hi,

It didn't prompt me to do any of that or give form. It wasn't very helpful explaining what to do, so i did my best. It can't be expected that people who aren't code writers will know how to opporate those types of sites.

The issue happens on both of my android phones (Samsung s 22 and and LG ThinQ)

When I go to any app or site to log in the suggested password and logins aren't there. It now asks me to "unlock Firefox", and when I do, no there is a search engine for logins when before it would recognize the site or app and suggest logins from a menu that are saved.

How do I get that function back?

Sent from Proton Mail mobile

-------- Original Message --------

**Comment by cpeterso** [comment]
@amccoy23 If you can still reproduce this bug, please file a new bug report on Bugzilla here: https://bugzilla.mozilla.org/enter_bug.cgi?product=Fenix

Did suggested logins and password work before and then stopped working?

**Comment by amccoy23** [comment]
Yes, it worked fine then there was an update and all of the sudden it stopped working.

Idk how to reporo

Sent from Proton Mail mobile

-------- Original Message --------
