### ISSUE TITLE
Save as PDF doesn't work for certain sites

### ISSUE THREAD

**Issue by topotropic** [mozilla-mobile/fenix#27593]
### Steps to reproduce

1. Open a Pocket recommended article, for example https://time.com/6211473/stopped-posting-photos-kids-social-media/
2. Open the share sheet and save it as PDF

### Expected behaviour

When I get the confirmation and tap on 'open' I see the article and I also see the article in Firefox > Downloads

### Actual behaviour

The article does not open, instead I get redirected to Firefox from the PDF viewer app. I also isn't listed in Firefox > downloads but shows up in the filer app.

### Device name

Google Pixel 3

### Android version

12

### Firefox release type

Firefox Nightly

### Firefox version

108.0a1

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21888)

**Comment by Mukuljangir372** [comment]
Hey @topotropic , Can you please tell me why I'm getting this error?
The `allowPullRequests` configuration for this repository (in `.taskcluster.yml` on the
default branch) does not allow starting tasks for this pull request.

**Comment by kbrosnan** [comment]
@Mukuljangir372 that is unrelated to this issue. If you want to discuss building Firefox please use our chat at https://chat.mozilla.org/#/room/#fenix:mozilla.org

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813432

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
