### ISSUE TITLE
[Bug] Google Images layout problems

### ISSUE THREAD

**Issue by AtzhiriCha-pat** [mozilla-mobile/fenix#27599]
What's going on with Google images?
![Screenshot_20221017-182915](https://user-images.githubusercontent.com/116861545/198686041-b5c7b304-7d85-48c6-96ba-e92879ea4e31.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21891)

**Comment by AtzhiriCha-pat** [comment]
@github-actions I don't know how to add a label to my comments. 
needs:triage

**Comment by kbrosnan** [comment]
Do you use the Google Search Fix extension?

**Comment by kbrosnan** [comment]
Duplicate bz-975444
