### ISSUE TITLE
[Share] Add the ability to disable send tab on share sheet

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/fenix#2759]
Parent: #331

This is a nice-to-have feature if we decide some share items shouldn't be allowed to send to other devices. (this is different from the build flag issue)

**Comment by jonalmeida** [comment]
This is an engineering task, not a feature; removed label.

**Comment by sblatz** [comment]
@jonalmeida do we have mocks for how this would look? Like a setting in the Settings Fragment?

**Comment by jonalmeida** [comment]
This is an engineering task, not a feature, i.e. a send tab API to show the share sheet without the send tab bit (programmatically). A nice to have, no priority.
