### ISSUE TITLE
Nimbus takes unexpectedly long to start up: 30% of FenixApplication.onCreate (92.3ms Moto G5)

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#27603]
In the 10/10 Nightly, [this start up profile on the Moto G5 samples FenixApplication.onCreate executing for 308ms](https://share.firefox.dev/3Wq5pC7). If we filter the method by "Nimbus", [the code takes 92.3ms to run](https://share.firefox.dev/3feAc3Q) – i.e. code with Nimbus in the stacktrace runs for ~30% of `FenixApplication.onCreate`.

It seems like this code is allocating memory and initializing data structures which doesn't seem like it should take this long, at least if the code was written for the JVM. I feel like we can do better. If the JNA cost is unavoidable, could we find ways to improve it? e.g. allocate fewer structures, initialize it on a background thread (the one-time synchronization should be cheap, right?), or perhaps defer it until after start up. fwiw, we see this with glean too but I don't think it looks as bad as it used to – I wonder what they may have done to address this. Perhaps there is a holistic solution we can take towards JNA overhead on start up (note: filtering app.onCreate by "com.sun.JNA" is 61.4ms).

Caveats:
- the sampling rate is 5ms so, if the samples were not taken consistently, we may measure a larger duration. However, we see a similar effect in this profile from 10/11: https://share.firefox.dev/3FosG12
- this is one device: maybe it just has problems with JNA or the OS has improved JNA handling in later versions. Can we reproduce on other devices? Maybe the A51?

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21892)

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807352

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
