### ISSUE TITLE
[Bug]: Audio stops playing in Firefox Nightly on Android when the tab loses focus (switching tabs, switching apps, turning off phone display)

### ISSUE THREAD

**Issue by notanewbie** [mozilla-mobile/fenix#27605]
### Steps to reproduce

1. Play audio
2. Switch tabs, switch apps, or turn off the phone display

### Expected behaviour

Audio should resume playing in the background

### Actual behaviour

The audio stops playing

### Device name

Samsung Galaxy S10e

### Android version

Android 12

### Firefox release type

Firefox Nightly

### Firefox version

108.0a1

### Additional information

This issue started early this week. I've been working on an internet radio website, to listen to radio on the internet through my phone (radio.ntnwb.cc), but now audio no longer plays in the background.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21894)

**Comment by notanewbie** [comment]
I'm not sure what happened, but it seems fixed now. Will monitor and close if it doesn't return in a day or two.
![Screenshot_20221029-164444_Firefox Nightly](https://user-images.githubusercontent.com/16856594/198851625-14a0d618-b25a-4220-9ae2-4bac795bdfd5.jpg)

**Comment by SoftVision-LorandJanos** [comment]
Hi @notanewbie! Thanks for your report!
I couldn't reproduce your issue, so as you said, will wait 1-2 days for you to close this ticket if the issue doesn't return.
If it does return, please provide with as much detail as you can. Thank you!

**Comment by notanewbie** [comment]
This got fixed 2-3 days ago and I forgot to close this, my bad

![Screenshot_20221102-013420_Firefox Nightly](https://user-images.githubusercontent.com/16856594/199406240-ec684840-f522-4443-a0fc-e3d89c2cc29c.jpg)
