### ISSUE TITLE
Investigate JVM main thread gap in a particular start up profile

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#27604]
In mcarare's cold start up profiles from https://github.com/mozilla-mobile/fenix/issues/27461#issuecomment-1292166105 on a Huawei, Android 6:
- https://share.firefox.dev/3D7urwV
- https://share.firefox.dev/3SxPFK0

We see a large gap where the main thread is not running for the Parent Process nor the JVM:
![image](https://user-images.githubusercontent.com/759372/198714633-23200e95-c0d2-4c73-9930-8b94cd35ba51.png)

Why is that? What are we blocked on? Could that be a source of performance improvements? Do we see this on other devices?

On the Moto G5, we see the main thread gap on the Parent Process but not the JVM:
- https://share.firefox.dev/3Dh2zpX
- https://share.firefox.dev/3DclUc5

![image](https://user-images.githubusercontent.com/759372/198715104-4493a5df-c64b-4b9a-9e85-432a952d7c6f.png)

---

@mcarare Do you know why this might be?

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21893)

**Comment by mcarare** [comment]
Note that I wasn't able to reproduce the occurrence of the JVM main thread gap on other devices ( Huawei - Android 9, Nokia - Android 10, Pixel 4 - Android 13) other than the Huawei with Android 6.

**Comment by mcomella** [comment]
Unless this particular Huawei device happens to have high usage in our user base, perhaps this isn't worth investigating then until we see it on other devices.

**Comment by MarcLeclair** [comment]
Triage: Close since it isn't happening on other devices. We can always reopen this in the future if we notice happening elsewhere.
