### ISSUE TITLE
[Bug]: Cursive font fallback is not applied

### ISSUE THREAD

**Issue by marcin-serwin** [mozilla-mobile/fenix#27609]
### Steps to reproduce

1. Go to https://en.wikisource.org/wiki/Template:Cursive
2. Look at example

### Expected behaviour

Text is displayed using Android cursive font (Dancing Script).

### Actual behaviour

Text is displayed in default sans serif font.

### Android version

Android 12.1

### Firefox release type

Firefox

### Firefox version

106.1.0

### Additional information

Firefox:
![image](https://user-images.githubusercontent.com/12128106/198819804-a65ca790-ddc0-47d5-ba69-7a6285449dd5.png)
Chrome:
![image](https://user-images.githubusercontent.com/12128106/198819816-7175bba6-8d24-421f-8e10-26b20d1a9ccd.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21895)

**Comment by Mugurell** [comment]
Thank you for the report.
It seems like the issue affects only mobile and is not reproducing on Desktop.
Moving the issue to GeckoView for more investigations there.

**Comment by Mugurell** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1798261

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
