### ISSUE TITLE
problem with noscript

### ISSUE THREAD

**Issue by mtsyns** [mozilla-mobile/fenix#27616]
Son gelen 2-3 güncellemeden beri noscript eklentisi düzgün çalışmıyor❗Noscript geçici izinli sekmelerde bazen kendiliğinden işlevsizleşiyor⚠️ Son açılandan bir önceki sekmeye geçtiğimde, ekranda yine son açılmış sayfa görünüyor ve gerçek adresin sayfası, yenilesemde bağlanmıyor⚠️ Diğer bir sorun ise uygulama ekranın bazen yarısı bazen tamamı siyah kalıyor❗[Redmi Note 8 MIUI v12 küresel kararlı sürüm] 

BİZ KULLANICILARIN GERİ BİLDİRİM ve HATA AYIKLAMA ÇIKTISI GÖNDEREBİLMEMİZİ KOLAYLAŞTIRILMALISINIZ! 
EN ÖNEMLİSİ BU❗❗❗ KULLANICILAR, UYGULAMA İÇİNDEN BUNU YAPABİLMELİ⚠️ DİĞER UYGULAMA GELİŞTİRİCİLERİN YAPTIĞI GİBİ ”AYARLAR/GERİ BİLDİRİM OLUŞTUR” YOLU OLMALI! HEM SİZLER HEM BİZ KULLANICILAR İÇİN BÜYÜK KOLAYLIK OLACAKTIR! 
DEĞİLSE, FORUMA GİT, ÜYE OL, FORUMU ÖĞREN, İNGİLİZCE BİL, vesaire vesaire... Sıradan Kullanıcı için çok çok çok ... uzun iş... EPEY ZAMAN ALAN, ŞU KADAR YAZDIĞIM ŞEY YERİNE , ÖNÜNÜZDE, 1-2 HAMLEDE GÖNDERİLMİŞ HATA AYIKLAMA ÇIKTISI İÇEREN BİR GERİ BİLDİRİM VERİSİ OLSA, DAHA ÇOK İŞİNİZE YARARDI SANIRIM❗
ŞİMDİDEN TEŞEKKÜR EDER, İYİ GÜNLER VE İYİ ÇALIŞMALAR DİLERİM. 
SEVGİ VE SAYGILARIMLA...🥰

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21898)

**Comment by mtsyns** [comment]
BİZ KULLANICILARIN GERİ BİLDİRİM ve HATA AYIKLAMA ÇIKTISI GÖNDEREBİLMEMİZİ KOLAYLAŞTIRILMALISINIZ! 
EN ÖNEMLİSİ BU❗❗❗ KULLANICILAR, UYGULAMA İÇİNDEN BUNU YAPABİLMELİ⚠️ DİĞER UYGULAMA GELİŞTİRİCİLERİN YAPTIĞI GİBİ ”AYARLAR/GERİ BİLDİRİM OLUŞTUR” YOLU OLMALI! HEM SİZLER HEM BİZ KULLANICILAR İÇİN BÜYÜK KOLAYLIK OLACAKTIR! 
DEĞİLSE, FORUMA GİT, ÜYE OL, FORUMU ÖĞREN, İNGİLİZCE BİL, vesaire vesaire... Sıradan Kullanıcı için çok çok çok ... uzun iş... EPEY ZAMAN ALAN, ŞU KADAR YAZDIĞIM ŞEY YERİNE , ÖNÜNÜZDE, 1-2 HAMLEDE GÖNDERİLMİŞ HATA AYIKLAMA ÇIKTISI İÇEREN BİR GERİ BİLDİRİM VERİSİ OLSA, DAHA ÇOK İŞİNİZE YARARDI SANIRIM❗
ŞİMDİDEN TEŞEKKÜR EDER, İYİ GÜNLER VE İYİ ÇALIŞMALAR DİLERİM. 
SEVGİ VE SAYGILARIMLA...🥰

**Comment by kbrosnan** [comment]
Noscript is not a supported extension.

**Comment by mtsyns** [comment]
Okey my friend 👍😞 Thank you for your answer. 
Best regards...🥰
