### ISSUE TITLE
[Bug]: Send tab to device - cannot see the full device names.

### ISSUE THREAD

**Issue by rbarte** [mozilla-mobile/fenix#27615]
### Steps to reproduce

1. Open a tab.
2. Click on share button.
3. Send to device menu is shown.
4. If there are many entries with longer description available then the name of those devices is cut. It is not possible to differentiate between devices.

### Expected behaviour

Show the full name of device.

### Actual behaviour

The device names are cut.

### Device name

Samsung Galaxy Note 9

### Android version

Android 10

### Firefox release type

Firefox

### Firefox version

106.1.0

### Additional information
![Screenshot_20221030-105208_Firefox](https://user-images.githubusercontent.com/31691084/198874233-6ab27518-2726-4708-9ab3-af56de22c887.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21897)

**Comment by kbrosnan** [comment]
Duplicate https://github.com/mozilla-mobile/fenix/issues/15170

See my comment about how sync device names are generated. You can edit them in your sync setting for the device. https://github.com/mozilla-mobile/fenix/issues/15170#issuecomment-863497684
