### ISSUE TITLE
High-contrast mode for web content

### ISSUE THREAD

**Issue by BlindMoon38** [mozilla-mobile/fenix#2761]
### Why/User Benefit/User Problem
As a low-vision user, it would be nice if there were an easy option in the accessibility settings to force-enable a high-contrast theme for web content, as well as a way for the user to customise what those colours would be.

### What/Requirements
Desktop Firefox has an option to specify the colours used when a high-contrast theme is active. And this is customisable on Firefox for Android via about:config and can be forced setting the "browser.display.document_color_use" preference to "2".
Also, since Android doesn't have a native high-contrast theme, there would need to be a setting to enable it without having to know the correct preferences to change or what about:config is

### Acceptance Criteria (how do I know when I’m done?)
There is a toggle in the accessibility settings to enable a high-contrast theme for web content.
There is a way to customise the colours that will be used when this setting is enabled.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-11661)

**Comment by DiegoARL38** [comment]
I'd suggest using as default colours those which Microsoft uses on Windows 10.

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1809978

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
