### ISSUE TITLE
Support for save as PDF and print 

### ISSUE THREAD

**Issue by Subbarao6338** [mozilla-mobile/fenix#27614]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### What is the user problem or growth opportunity you want to see solved?
Please add support for print and save as PDF features.
### Who will benefit from it?

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21896)

**Comment by cadeyrn** [comment]
Save as PDF is already implemented in Firefox Nightly. And printing should also not be a problem since you can print via your PDF app once you generated the PDF.

**Comment by Subbarao6338** [comment]
When this feature comes to beta and stable versions?

**Comment by cadeyrn** [comment]
> When this feature comes to beta and stable versions?

It looks like it will be part of Firefox 108.

**Comment by Subbarao6338** [comment]
Any ideas for built-in translation

**Comment by cadeyrn** [comment]
Translations are covered by #6133.
