### ISSUE TITLE
.exe extension becomes .com when downloading file

### ISSUE THREAD

**Issue by Fhokud** [mozilla-mobile/fenix#27621]
### Steps to reproduce

1.visit website [https://2.na.dl.wireshark.org/win64/Wireshark-win64-4.0.1.exe](https://2.na.dl.wireshark.org/win64/Wireshark-win64-4.0.1.exe)

### Expected behaviour

Downloaded Wireshark-win64-4.0.1.exe

### Actual behaviour

Downloaded Wireshark-win64-4.0.1.com

### Device name

MIUI12.6 

### Android version

andeoid 11

### Firefox release type

Firefox

### Firefox version

107.1.0 armv8 From github

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21900)

**Comment by AdinaPetridean** [comment]
@Fhokud thank you for your report! I was able to reproduce this issue also on  The issue is still reproducible on: Firefox Nightly 108.0a1- 10/31 with Motorola Moto g ( 9 plus) - Android 11.
.

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1810197

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
