### ISSUE TITLE
Use a lazyBooleanPreference as an alternative to lazyFeatureFlagPreference

### ISSUE THREAD

**Issue by Mugurell** [mozilla-mobile/fenix#27629]
An issue was seen in https://github.com/mozilla-mobile/fenix/issues/27627 with settings that need a lazy initialization.
Currently a `lazyFeatureFlagPreference` is used but the flag is just a formality.
If the flag is not used it should be removed and if that is removed we'll need support for a simpler `lazyBooleanPreference`.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21902)

**Comment by Mugurell** [comment]
With https://github.com/mozilla-mobile/fenix/pull/27554 removing some feature flags there will be more uses of `lazyFeatureFlagPreference` which don't actually check a flag so `lazyBooleanPreference` might help in more new cases.

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813431

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
