### ISSUE TITLE
Printing this website giving blank page pdf

### ISSUE THREAD

**Issue by JacenBridger** [mozilla-mobile/fenix#27620]
### Steps to reproduce

1. Go to [this website](https://linearalgebras.com/1c.html) 
2. Wait till rendering of the contents completed.
3. Now, try to print as pdf/save as pdf

### Expected behaviour

It should give the proper rendered content(including mathjax) of the website in a pdf file.

### Actual behaviour

It giving blank pdf.

### Device name

Redmi note 10

### Android version

Android 12

### Firefox release type

Firefox Nightly

### Firefox version

108.0a1

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21899)

**Comment by SoftVision-LorandJanos** [comment]
Hi @JacenBridger. Thanks for your report!
I believe this issue was covered in [this](https://github.com/mozilla-mobile/fenix/issues/27593) ticket.
Closing the ticket as duplicate.

**Comment by JacenBridger** [comment]
I think other case is different. This one generates pdf with blank page.

**Comment by SoftVision-LorandJanos** [comment]
Sorry for the confusion, you are right!
I was able to reproduce the issue as you described, with the latest Nightly 108.0a1 (2022-10-31) build.
Device used: Oppo Find X5 (Android 12).
Reopening the ticket.

**Comment by kbrosnan** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1798343

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
