### ISSUE TITLE
[Telemetry] Add telemetry for Save to PDF failures 

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/fenix#27635]
We know that 'Save to PDF' can fail for users for various technical reasons (page layout not ready, etc.). We should add telemetry events to know when a Save to PDF action fails by firing probes during the `SaveToPdfExceptionAction`.

_Originally posted by @jonalmeida in https://github.com/mozilla-mobile/fenix/pull/27525#discussion_r1003937178_

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21905)

**Comment by DreVla** [comment]
I would like to work on this when available.

**Comment by jonalmeida** [comment]
@DreVla for sure, please let me know if you have questions. Once this patch from @Amejia481 lands, you can use the middleware to record the new telemetry event.

Please have a look at [this wiki doc](https://github.com/mozilla-mobile/fenix/wiki/Implementing-Telemetry#procedure-to-follow-when-implementing-a-glean-telemetry-event) for more details on how to do that. 

Thanks!

**Comment by amocirean** [comment]
Verified as fixed on the latest Nightly (2022-03-10).
Device used: Google Pixel 6 (Android 13).
Closing the ticket as fixed.

**Comment by amocirean** [comment]
Verified as fixed on the latest Beta 108.0b1.
Device used: Google Pixel 6 (Android 13).

The following events were generated:

`{
          "timestamp": 51535,
          "category": "events",
          "name": "save_to_pdf_tapped"
        },
        {
          "timestamp": 51558,
          "category": "events",
          "name": "save_to_pdf_failure"
        }
      ]
    }`
