### ISSUE TITLE
Add telemetry for gesture navigation (tab switching)

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/fenix#27634]
We should better understand our users today and how well gesture navigation is used within the app.

(Work in progress) List of probes to add:
* Users that have gesture navigation turned on (default is currently on). (Settings > Customize > Swipe toolbar sideways to switch tabs)
* Users that toggle gesture navigation settings.
* Count how many times a gesture navigation is used in a session.
* Check how many users have system-level gesture navigation enabled too. A tri-state value: enabled, disabled, or not supported by the system.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21904)

**Comment by jonalmeida** [comment]
cc: @cpeterso @kbrosnan if there are more specific things we should learn. 

e.g. we could also check how many users have system-level gesture navigation enabled too.

**Comment by jonalmeida** [comment]
> Can we count page navigation by the system-level gesture navigation separately from Fenix's "Swipe toolbar sideways to switch tabs" gesture? They are different use cases and the system-level gestures might not be available on all devices (like, AFAICT, my Samsung Galaxy A32).

Since the swipe toolbar gesture is for tab switching, it would be tracked separately (in this ticket) from the system-level gesture navigation.

> That might be a tri-state value: enabled, disabled, or not supported by the system.

Thanks, I've updated the list in comment 0.

**Comment by DreVla** [comment]
I would like to work on this, but after investigation I found no reliable way of detecting if the device has system level gestures enabled. Found this which seems promising, but there seem to be many devices that have issues with it - https://stackoverflow.com/a/60733427/7312631 
@jonalmeida do you know a sure fire way to achieve this?

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1809329

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
