### ISSUE TITLE
Investigate a better UX for how to show a Save to PDF error

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/fenix#27649]
At the moment, we are showing an Android toast when an error happens while trying to generate a PDF from a website. This is due to some technical limitations that make it difficult to show our default Fenix Snackbar. 

Technical context, see: https://github.com/mozilla-mobile/fenix/pull/27525.

<img src="https://user-images.githubusercontent.com/773158/199344678-edf6d8b5-9d48-43c6-a546-758899df22ac.png" width=320 />

**For UX:** Does this solution suffice (see screenshot above with the toast "Unable to generate PDF")? Are there alternative solutions we could try? Is the Fenix Snackbar (below) the preferable solution?

<img width="584" alt="Screen Shot 2022-11-01 at 5 39 00 PM" src="https://user-images.githubusercontent.com/1370580/199347023-348ac6f9-61eb-4126-a1be-2f0037aa36ae.png">

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21910)
┆Link To Issue: https://mozilla-hub.atlassian.net/browse/FNXV2-21910

**Comment by Amejia481** [comment]
![image](https://user-images.githubusercontent.com/773158/199344678-edf6d8b5-9d48-43c6-a546-758899df22ac.png)

**Comment by jonalmeida** [comment]
(moved the screenshots up to the main post)

**Comment by ewachowiak** [comment]
@Amejia481 Do you have other examples of snackbars being used for errors like this? In my mobile component audit, I was only able to generate one error on Android [(this one)](https://miro.com/app/board/uXjVPVMf6O8=/?moveToWidget=3458764536137691025&cot=14). If possible, I'd like to use a component we are already using for errors so the pattern will be more familiar for users.

**Comment by ewachowiak** [comment]
@Amejia481 I was able to confirm that snackbars are used for errors, so it makes sense to use one here. I recommend using this copy: "Unable to create PDF"

FYI @Delphine to review this string for l10n.

**Comment by Delphine** [comment]
SGTM! thanks for flagging

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813428

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
