### ISSUE TITLE
website issue on firefox

### ISSUE THREAD

**Issue by ArejaZ** [mozilla-mobile/fenix#27659]
https://www.sportsdirect.com/outdoor-footwear/mens-outdoor-footwear/mens-walking-boots
This website crashing on firefox.
![Uploading Screenshot_20221102-095918_Firefox.jpg…]()

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21913)
┆Link To Issue: https://mozilla-hub.atlassian.net/browse/FNXV2-21913

**Comment by kbrosnan** [comment]
No crash report IDs submitted.
