### ISSUE TITLE
FNX3-16565 ⁃ Fenix should run places maintenance periodically

### ISSUE THREAD

**Issue by thomcc** [mozilla-mobile/fenix#2765]
@grigoryk indicated that it does not, which will result in worse perf, more disk usage, etc.

**Comment by sblatz** [comment]
@thomcc @grigoryk can you please clarify what this means? This ticket is not actionable for the fenix engineering team as it stands.

**Comment by thomcc** [comment]
There's a function call on writable places connections called runMaintenance: https://github.com/mozilla/application-services/blob/ce7652ddc1a8724d617bd187c6a08e996f329b96/components/places/android/src/main/java/mozilla/appservices/places/PlacesConnection.kt#L663-L677

This should be called once per day. I don't know how it's exposed through A-C's history adapters. I also don't have the ability to remove the waiting label.
