### ISSUE TITLE
Fix auto publish instructions for new Android Components location

### ISSUE THREAD

**Issue by fice-t** [mozilla-mobile/fenix#27652]
The README contains the following:

>In local.properties, specify a relative path to your local android-components and/or application-services checkouts. E.g.:
>
>    autoPublish.android-components.dir=../android-components

After the repo migration, using `../firefox-android` results in:

```
python: can't open file '...StudioProjects/firefox-android/automation/publish_to_maven_local_if_modified.py': [Errno 2] No such file or directory
```

Using `../firefox-android/android-components` results in:

```
Error: This only works if run from the repo root
```
CC @csadilek

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21911)
┆Link To Issue: https://mozilla-hub.atlassian.net/browse/FNXV2-21911

**Comment by jonalmeida** [comment]
@fice-t can you try `../firefox-android/android-components`? Does that still work?

**Comment by fice-t** [comment]
@jonalmeida That's the 2nd case above (`Error: This only works if run from the repo root`).

**Comment by fice-t** [comment]
This may be related (as the python script checks for existence of `LICENSE` file): https://github.com/mozilla-mobile/firefox-android/commit/f304fcb5c72dbbc3ef860291aff7ce4a6a89dc3f

**Comment by fice-t** [comment]
In any case, the `Fenix` README should be updated to `../firefox-android/android-components` to reflect the migration, assuming this repo stays separated for long enough.

**Comment by csadilek** [comment]
> Confirmed that reverting the above commit fixes this. Perhaps the [find_project_root](https://github.com/mozilla-mobile/firefox-android/blob/0aaaae127e78f89cc0ae73035ef3b75daf2f5ecd/android-components/automation/publish_to_maven_local_if_modified.py#L25) procedure should check for something else? Or just assume that the script is located in <android-components>/automation?

Thanks for filing, and good find @fice-t! If you have a working version locally, we'd appreciate a PR. If not, I will try to get to this soon. It's worth addressing before the repos are integrated.

**Comment by csadilek** [comment]
> Or just assume that the script is located in <android-components>/automation?

Yes, I like that better than looking for LICENSE. I don't see why the location has to be more flexible.

**Comment by csadilek** [comment]
See also https://github.com/mozilla-mobile/firefox-android/pull/79
