### ISSUE TITLE
Ensure`$ANDROID_NDK_HOME` is set in build environment, to strip native libs by default

### ISSUE THREAD

**Issue by rfk** [mozilla-mobile/fenix#2766]
Over in https://github.com/mozilla-mobile/fenix/issues/1374 I was a bit surprised to find that Fenix was shipping a copy of `libfenix.so` that contained many megabytes of debug symbols, because the android gradle plugin is supposed to strip these debug symbols by default (so much so that the top search result I see for "android strip native libraries" is an article on how to _disable_ this stripping!).

Over in [application-services](https://github.com/mozilla/application-services/issues/1107#issuecomment-491087035) we eventually discovered that the android-gradle-plugin expects to find the location of the [Android NDK](https://developer.android.com/ndk/) in the `$ANDROID_NDK_HOME` environment variable. Setting this correctly in our build scripts magically enabled stripping of debug symbols and reduced the size of our native library builds quite dramatically.

I suggest checking whether this environment variable is set correctly in the Fenix build environment, and enabling it if so. This could produce a modest size saving by ensuring that any third-party native libs (such as [this one](https://github.com/mozilla-mobile/fenix/issues/1374#issuecomment-479747655)) have their debug symbols stripped as well.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-11664)

**Comment by boek** [comment]
@mcomella Is this something that is easy to do?

**Comment by mcomella** [comment]
It sounds like we may be able copy the code from the `android-gradle-plugin`.

If that doesn't work, my understanding is that we'd need to fail the build if the `android_ndk_home` envvar is not set. I believe it should be relatively straight-forward in gradle to, on release builds, verify the environment variable is set and fail the build if not.

Feel free to sync up/pair with me on how to do this.

**Comment by mcomella** [comment]
If I misinterpreted and all we really want is to set ANDROID_NDK_HOME to an NDK on the builders, that's a different problem that JohanLorenzo might have context on.

**Comment by mcomella** [comment]
This could still be valuable so I want to keep this open.

**Comment by tudos4** [comment]
.

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807357

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
