### ISSUE TITLE
[Experiment] [TCP CFR] The tip of the TCP CFR message doesn’t point to the lock button from the Address Bar 

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [mozilla-mobile/fenix#27662]
### Steps to reproduce

**[Prerequisites]:**
- Have a local Beta build that is set-up to point to the Nimbus Prod server: [link](https://drive.google.com/file/d/1Ji1xRrZXbKVWeQFjI3bSeQ5wKI1o2UGW/view?usp=sharing)
- Have the local build installed on a device.

**[Steps to reproduce]:**
1. Open the local build from the prerequisites.
2. Navigate to the Firefox "Settings" menu.
3. Scroll down to the bottom of the list and tap the "About Firefox Beta" option.
4. Tap the "Firefox Browser" logo 5 times and go back to the "Settings" menu.
5. Scroll down to the bottom of the list and tap the "Secret Settings" option.
6. Enable the “Use Nimbus Preview Collection” option and restart the browser.
7. Navigate again to the Firefox "Settings" menu -> "About Firefox Beta" option.
8. Tap the "Firefox Browser" logo 5 times and go back to the "Settings" menu.
9. Scroll down to the bottom of the list and tap the "Nimbus Experiments" option.
10. Tap the "Firefox Android TCP CFR Experiment" experiment.
11. Tap the “treatment-a” branch and restart the browser.
12. Navigate to a website and observe the TCP CFR message.

### Expected behaviour

- The tip of the TCP CFR message points to the lock button from the Address Bar.

### Actual behaviour

- The tip of the TCP CFR message **does not point** to the lock button from the Address Bar.

### Device name

Samsung S9, One Plus 6, Samsung S8

### Android version

Android 9, Android 10, Android 11

### Firefox release type

Firefox Beta

### Firefox version

107.0b6

### Additional information

- The issue is also reproducible when the device is in landscape mode.
- The issue is reproducible with both the Address Bar being displayed to the bottom or to the top of the screen.
- Here are 2 screenshots of the issue:

![image_2022_11_02T10_19_53_354Z](https://user-images.githubusercontent.com/26000308/199500870-e859360a-d478-4ac2-a091-4634bb1501d5.png)

![1667382738274](https://user-images.githubusercontent.com/26000308/199500886-90bc5800-0897-43f2-930e-46ac326f4950.JPEG)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21914)
┆Link To Issue: https://mozilla-hub.atlassian.net/browse/FNXV2-21914

**Comment by cpeterso** [comment]
Good eye! Unfortunately, I don't think we have time to fix this bug for Fenix 107. But we should fix it for 108 so new users installing >= 108 will see the fixed CFR.

**Comment by sheikh-azharuddin** [comment]
Also the link is broken "learn more about total cookie protection"

**Comment by cpeterso** [comment]
> Also the link is broken "learn more about total cookie protection"

Yes. That's bug https://github.com/mozilla-mobile/fenix/issues/26956.

**Comment by cpeterso** [comment]
@Mugurell We'll probably ship TCP and its CFR in Fenix 112 (March 14 release date), so it would be nice to fix this TCP CFR bug in Fenix 111 or 112 before we ship the TCP CFR. But I also understand that you might have higher priorities than this bug that only affects some devices.

In the meantime, I'm going to move this issue to Bugzilla and Jira so we can track it in our Kanban board.

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813427

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
