### ISSUE TITLE
[Bug]: [Experiment] [TCP CFR] The “tcp_implicit_dismissal” telemetry event is not registered when the orientation of the device is changed

### ISSUE THREAD

**Issue by alicevarro** [mozilla-mobile/fenix#27663]
### Steps to reproduce

**[Prerequisites]:**
- Have a local Beta build that is set-up to point to the Nimbus Prod server: [link](https://drive.google.com/file/d/1Ji1xRrZXbKVWeQFjI3bSeQ5wKI1o2UGW/view).
- Have the local build installed on the device.
- Have the mobile device connected to the PC and Android Studio.

**[Steps to reproduce]:**
1. Start the app with the telemetry command (adb shell am start -n org.mozilla.firefox/mozilla.telemetry.glean.debug.GleanDebugActivity --ez logPings true --es sendPing events --es debugViewTag tcp_experiment)
2. Scroll down to the bottom of the list and tap the "About Firefox Beta" option.
3. Tap the "Firefox Browser" logo 5 times and go back to the "Settings" menu.
4. Scroll down to the bottom of the list and tap the "Secret Settings" option.
5. Enable the “Use Nimbus Preview Collection” option and restart the browser.
6. Repeat the first 3 steps.
7. Scroll down to the bottom of the list and tap the "Nimbus Experiments" option.
8. Tap the "Firefox Android TCP CFR Experiment" experiment.
9. Tap the “treatment-a” branch and restart the browser.
10. Navigate to a website and observe the TCP CFR message.
11. Change the orientation of the phone from portrait to landscape and observe the Address Bar.
12. Send the app to the background and observe the events displayed in the Logcat tab from Android Studio.

### Expected behaviour

- A “category” : “tracking_protection”, “name” : “tcp_implicit_dismissal” event is displayed.

### Actual behaviour

- The dismiss ping is not displayed in Logcat.

### Device name

One Plus 5, One Plus 6

### Android version

Android 10, Android 11

### Firefox release type

Firefox Beta

### Firefox version

107.0b6

### Additional information

- Attaching a screen recording of the issue [here](https://drive.google.com/file/d/1EKXF_PyiCVFpoUk_ARaiyqsEaH3uLs7G/view?usp=sharing).

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21915)
┆Link To Issue: https://mozilla-hub.atlassian.net/browse/FNXV2-21915

**Comment by cpeterso** [comment]
@SoftVision-CiprianMuresan Is the TCP CFR dismissed when you rotate the phone from portrait to landscape or when you send the app to the background?

**Comment by SoftVision-CiprianMuresan** [comment]
@cpeterso the TCP CFR is dismissed when the screen orientation is changed and the `implicit_dismissal` ping isn't sent.
As for the other scenario, the CFR is **not** dismissed when sending the app into background and it does __not__ generate additional `show` pings.

**Comment by Mugurell** [comment]
The scenarios described by @alicevarro and by @SoftVision-CiprianMuresan are the expected scenarios.

Specifically about the situation in which the screen is rotated we dismiss the CFRs (and most other popups in Fenix)  because of technical reasons (read more [here](https://github.com/mozilla-mobile/fenix/issues/27033)) not because the user intended to close the CFR. 
As such because we don't consider this as a user gesture to dismiss the CFR in the case of the TCP CFR and other such CFRs we are not recording any telemetry about the dismissal.

Based on this I'll close the ticket as working as intended.
Happy to revisit and help send the right telemetry if a decision is made to treat this scenario as one in which the user intended to dismiss the CFR by rotating the screen.

**Comment by SoftVision-CiprianMuresan** [comment]
@cpeterso I don't disagree with @Mugurell, but I think we should try to have a similar probe to the `tcp_cfr_implicit_dismissal` for _any_ scenario in which the CFR is dismissed as this would help us have a more clearer picture as to how many dismisses of any type we have.

**Comment by Mugurell** [comment]
Jeff recommended here - https://github.com/mozilla-mobile/fenix/issues/27033 trying to keep the CFRs after the screen is rotated, or at least showing that same CFR again which would make the issue discussed here obsolete.
