### ISSUE TITLE
[Telemetry] Send existing mobile search metric data in baseline ping

### ISSUE THREAD

**Issue by perrymcmanis144** [mozilla-mobile/fenix#27671]
## Description & Product Manager / Data Scientist User Story

Pursuant to: https://bugzilla.mozilla.org/show_bug.cgi?id=1797323

There are several existing metrics that are sent in the Metrics ping, I will be including them in the baseline ping.

No new data will be collected.

## What questions will you answer with this data?

This will reduce the latency of search data which is critical for modelling.

## Acceptance Criteria
- [ ] ENG files a [DS JIRA](https://jira.mozilla.com/projects/DO/issues/DO-228?filter=allopenissues) request outlining their methodology.
- [x] DS sign off on instrumentation methodology addressing product questions.
- [ ] Event pings can be queried via re:dash
- [ ] Event pings can be queried via amplitude
- [ ] We are sending telemetry events for the actions listed in the requirements
- [x] We have documented the telemetry
- [ ] We have asked a data steward to [review](https://github.com/mozilla/data-review/blob/master/request.md) the telemetry

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21919)
┆Link To Issue: https://mozilla-hub.atlassian.net/browse/FNXV2-21919

**Comment by rxumoz** [comment]
Is it possible to include _distribution_id_ into the baseline ping? So that we can have a more accurate DAU data for  MozillaOnline releases.
For  _distribution_id_ please see: https://github.com/mozilla-mobile/fenix/issues/16075

**Comment by perrymcmanis144** [comment]
> Is it possible to include _distribution_id_ into the baseline ping? So that we can have a more accurate DAU data for MozillaOnline releases. For _distribution_id_ please see: #16075

Adding it to the baseline ping mechanically would not require much effort; add ```- baseline``` to the send_in_pings section of the metrics.yaml and add 

```yaml
no_lint:
  BASELINE```

Whether this is something that _should_ happen, what is the intended work flow if we had it? Typically speaking, the metrics ping is a more appropriate place for this sort of measure since it appears that it was considered for inclusion in the built-ins, which should make up most of the baseline ping. We typically are recommending that only measures used for KPI calculations make it into the baseline ping.

Is there a derived table you're working with? I ask because you could potentially approximate having this as a filter via a join in the ETL.

**Comment by rxumoz** [comment]
> > Is it possible to include _distribution_id_ into the baseline ping? So that we can have a more accurate DAU data for MozillaOnline releases. For _distribution_id_ please see: #16075
> 
> Adding it to the baseline ping mechanically would not require much effort; add `- baseline` to the send_in_pings section of the metrics.yaml and add
> 
> ```yaml
> no_lint:
>   BASELINE
> ```
> 
> Whether this is something that _should_ happen, what is the intended work flow if we had it? Typically speaking, the metrics ping is a more appropriate place for this sort of measure since it appears that it was considered for inclusion in the built-ins but ultimately wasn't (builtns should make up most of the baseline ping). We typically are recommending that only measures used for KPI calculations make it into the baseline ping.
> 
> Is there a derived table you're working with? I ask because you could potentially approximate having this as a filter via a join in the ETL.

Yes currently we use join to calculate DAU, like this: https://sql.telemetry.mozilla.org/queries/81019
The **join_mo** column is what we have using join with _distribution_id_ , and the **build_id** column is more accurate data. However it is not guaranteed to have a different build_id of mozillaonline releases from global releases, thus in some versions we might have invalid data.
Adding _distribution_id_ can help us to get more stable & accurate DAU. But it's up to your estimation to see if it's appropriate.

**Comment by perrymcmanis144** [comment]
> > > Is it possible to include _distribution_id_ into the baseline ping? So that we can have a more accurate DAU data for MozillaOnline releases. For _distribution_id_ please see: #16075
> > 
> > 
> > Adding it to the baseline ping mechanically would not require much effort; add `- baseline` to the send_in_pings section of the metrics.yaml and add
> > ```yaml
> > no_lint:
> >   BASELINE
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Whether this is something that _should_ happen, what is the intended work flow if we had it? Typically speaking, the metrics ping is a more appropriate place for this sort of measure since it appears that it was considered for inclusion in the built-ins but ultimately wasn't (builtns should make up most of the baseline ping). We typically are recommending that only measures used for KPI calculations make it into the baseline ping.
> > Is there a derived table you're working with? I ask because you could potentially approximate having this as a filter via a join in the ETL.
> 
> Yes currently we use join to calculate DAU, like this: https://sql.telemetry.mozilla.org/queries/81019 The **join_mo** column is what we have using join with _distribution_id_ , and the **build_id** column is more accurate data. However it is not guaranteed to have a different build_id of mozillaonline releases from global releases, thus in some versions we might have invalid data. Adding _distribution_id_ can help us to get more stable & accurate DAU. But it's up to your estimation to see if it's appropriate.

It is appropriate in this case for you to add that data to the baseline ping if necessary, then.

Because this particular addition (mobile search metric data) is heading towards close, if you have further questions please feel free to ping me on slack or matrix, or if you like, open a new issue and tag me. Happy to provide continued support.

**Comment by perrymcmanis144** [comment]
> > > Is it possible to include _distribution_id_ into the baseline ping? So that we can have a more accurate DAU data for MozillaOnline releases. For _distribution_id_ please see: #16075
> > 
> > 
> > Adding it to the baseline ping mechanically would not require much effort; add `- baseline` to the send_in_pings section of the metrics.yaml and add
> > ```yaml
> > no_lint:
> >   BASELINE
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Whether this is something that _should_ happen, what is the intended work flow if we had it? Typically speaking, the metrics ping is a more appropriate place for this sort of measure since it appears that it was considered for inclusion in the built-ins but ultimately wasn't (builtns should make up most of the baseline ping). We typically are recommending that only measures used for KPI calculations make it into the baseline ping.
> > Is there a derived table you're working with? I ask because you could potentially approximate having this as a filter via a join in the ETL.
> 
> Yes currently we use join to calculate DAU, like this: https://sql.telemetry.mozilla.org/queries/81019 The **join_mo** column is what we have using join with _distribution_id_ , and the **build_id** column is more accurate data. However it is not guaranteed to have a different build_id of mozillaonline releases from global releases, thus in some versions we might have invalid data. Adding _distribution_id_ can help us to get more stable & accurate DAU. But it's up to your estimation to see if it's appropriate.

It is appropriate to add it to the baseline ping given the use case.

In general since the audience size won't be changing prior data reviews are sufficient, but given the elapsed time I would at least recommending checking in with a data steward just to confirm. 

Feel free to ping me in slack/matrix/the new github issue that covers that if you need me.

**Comment by rxumoz** [comment]
Okay, then I'll start an new issue about this next week. Thanks a lot! @perrymcmanis144
