### ISSUE TITLE
[Bug]: html video displays only parts of the video

### ISSUE THREAD

**Issue by davidspura** [mozilla-mobile/fenix#27685]
### Steps to reproduce

If you follow [this link](https://bibinoapp.com/en/activitylog/rfxUItSsCJgWU57h0xWh8S) and try playing any of the videos, only small portion of the video is visible.

There is nothing special or broken about the styling of the video, I checked it thoroughly through firefox remote debugging, all elements were correctly highlighted and the video works fine in other environments (iOS firefox, Android chrome, desktop...)

### Expected behaviour

Whole video should be displayed

### Actual behaviour

Only part of the video is visible

### Android version

Android 12

### Firefox release type

Firefox

### Firefox version

106.1.0

### Additional information

I tried playing the video on three different mobile devices, same result for all of them

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21921)
┆Link To Issue: https://mozilla-hub.atlassian.net/browse/FNXV2-21921

**Comment by kbrosnan** [comment]
duplicate bz-1794438
