### ISSUE TITLE
Cut URLs automatically when sharing them.

### ISSUE THREAD

**Issue by Lululalu** [mozilla-mobile/fenix#2769]
### Why/User Benefit/User Problem
Some URLs are needlessly long. They may occupy a whole screen on a chat app.

### What/Requirements
Cut non-crucial parts of URLs

### Acceptance Criteria (how do I know when I’m done?)
The feature is available on Chrome and ot is described here: https://www.ghacks.net/2018/02/20/chrome-64-for-android-cuts-urls-automatically-when-you-share-them/

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-11667)

**Comment by NotWoods** [comment]
Filed mozilla-mobile/android-components#4531

**Comment by amkcpu** [comment]
I'm very interested in this feature, and I think it doesn't just make sense from a UX perspective, cutting down URL length (as described above), but also from a privacy perspective: This would remove tracking parameters and prevent the people you share the link with from learning how you navigated to the site.

**Comment by amkcpu** [comment]
Related #9036.

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1809795

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
