### ISSUE TITLE
[Bug]: Firefox shows a black screen instead of website when I click on a link from another app

### ISSUE THREAD

**Issue by campfiresong69** [mozilla-mobile/fenix#27693]
### Steps to reproduce

Click on any like that will redirect to your default browser. With Mozilla Firefox being the default browser.

### Expected behaviour

The websites appears on screen as intended

### Actual behaviour

The page loads but displays a black screen

### Device name

Samsung Galaxy Note 20 Ultra

### Android version

One UI 4.1, Android 12

### Firefox release type

Firefox Beta

### Firefox version

107.0b5 (Build #2015913115), 86fae8990+ AC: 107.0.4, 3825163878 GV: 107.0-20221029133721 AS: 94.2.2

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21926)
┆Link To Issue: https://mozilla-hub.atlassian.net/browse/FNXV2-21926

**Comment by Theo-user** [comment]
This happens to me all the time on all Firefox version (- Focus). Drives me crazy.

**Comment by AdinaPetridean** [comment]
@campfiresong69 Thank you for your report!
 I tried to reproduce your issue on the Firefox Beta 107.0b5 and on the latest Nightly 108.0a1 from 09/11  with OnePlus 9 Pro (Android 12), and the website was correctly displayed. Could you please give us more details? Thanks!

**Comment by templeofninpo** [comment]
Happening to me intermittently. Workaround is opening new tab then returning and black screen disappears.

Maybe coincidental but seemed to start happening after installing the FB app. Have play services disabled.

(Moto g power 2021 running Lineage 19.1 GSI)

**Comment by kelleymccheese** [comment]
I can confirm that this is happening to me too. If I click on a link from the Google app, it seems to be an about 30-40% chance it properly loads. The rest of the time I need to go back and try again since it'll just load a black screen.

I'm using the Fennec version on F-Droid (Pixel 6, Android 12)

**Comment by cpeterso** [comment]
Do you have dark mode enabled? This bug sounds similar to dark mode https://github.com/mozilla-mobile/fenix/issues/27887.

We're tracking that bug on Bugzilla here: https://bugzilla.mozilla.org/show_bug.cgi?id=1813417

If you don't have dark mode enabled, please file a new bug report on Bugzilla here: https://bugzilla.mozilla.org/enter_bug.cgi?product=Fenix
