### ISSUE TITLE
Replace the Pocket word in all strings with a placeholder

### ISSUE THREAD

**Issue by Alexandru2909** [mozilla-mobile/fenix#27691]
We would like to replace the word "Pocket" in all our strings with a string placeholder which should be passed as parameter at runtime.

Based on [this](https://github.com/mozilla-l10n/android-l10n/pull/512#discussion_r1001207270) comment.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21925)
┆Link To Issue: https://mozilla-hub.atlassian.net/browse/FNXV2-21925

**Comment by SoftVision-LorandJanos** [comment]
Verified as fixed in the latest Nightly 108.0a1 (2022-11-07).
Device used: Oppo Find X5 (Android 12).
Closing the ticket as verified.

**Comment by SoftVision-LorandJanos** [comment]
Verified as fixed on the latest Beta 108.0b1.
Device used: Google Pixel 4 (Android 13).
