### ISSUE TITLE
DuckDuckGo Addon displays a blank settings page

### ISSUE THREAD

**Issue by rahaaatul** [mozilla-mobile/fenix#27690]
### Steps to reproduce

1. Add Duckduckgo Privacy Essential to custom collection.
2. Install the addon.
3. Got to DDG addon's settings
4. Observe

### Expected behaviour

Should show the interface.

### Actual behaviour

The page is all white/blank.

### Device name

Vivo

### Android version

Android 11

### Firefox release type

Firefox Beta

### Firefox version

107.0b5

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21924)
┆Link To Issue: https://mozilla-hub.atlassian.net/browse/FNXV2-21924

**Comment by SoftVision-LorandJanos** [comment]
Hi @rahaaatul! Thanks for your report!
As I observed, the mentioned addon doesn't seem to be compatible with Fenix.
As I tried to download to install the add-on, it sent me to the recommended ones.

**Comment by rahaaatul** [comment]
> Hi @rahaaatul! Thanks for your report! As I observed, the mentioned addon doesn't seem to be compatible with Fenix. As I tried to download to install the add-on, it sent me to the recommended ones.

As I said, you need to add it to custom add-on collection, and in Fenix you need to enter your custom add-on credentials to install it.

**Comment by SoftVision-LorandJanos** [comment]
Sorry for the confusion, I did reproduce your issue with the latest Nightly 108.0a1 (2022-11-10) build.
Device used: Oppo Find X5 (Android 12).

**Comment by rahaaatul** [comment]
> Sorry for the confusion.
It's fine.
> I did reproduce your issue.
What was the result?

**Comment by gabrielluong** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813915

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
