### ISSUE TITLE
Unified search delay in showing icon when switching between display mode and edit mode

### ISSUE THREAD

**Issue by rocketsroger** [mozilla-mobile/fenix#27697]
https://user-images.githubusercontent.com/6579541/199828530-48ff26b1-2a3e-461c-ba10-ab38d0e9192a.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21927)
┆Link To Issue: https://mozilla-hub.atlassian.net/browse/FNXV2-21927

**Comment by delia-pop** [comment]
Verified as fixed in Nightly 110.0a1 from 12/19 with Google Pixel 6 (Android 13). 

https://user-images.githubusercontent.com/89388888/208448356-ea4c6375-c2a4-4e28-93c8-83e75fe507c6.mp4
