### ISSUE TITLE
[Bug]: Deleted Url on History Page, Still shows up on suggestion

### ISSUE THREAD

**Issue by itsmecom** [mozilla-mobile/fenix#27720]
### Steps to reproduce

1. Delete a url from history page
2. after deleting, type the same url on url bar
3. it still shows up on suggestion list.

### Expected behaviour

Deleted url from history should not show up on suggestion

### Actual behaviour

Deleted url from history should shows up on suggestion

### Android version

All Android Versions

### Firefox release type

Firefox

### Firefox version

Latest version

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21935)
┆Link To Issue: https://mozilla-hub.atlassian.net/browse/FNXV2-21935

**Comment by AdinaPetridean** [comment]
@itsmecom Thank you for your report!
Using your example, I couldn't reproduce your issue on Firefox 106.1.0 and also on Nightly 108.0a1 from 09/11 with Motorola Moto G9 plus - Android 11. I made sure I closed that tab, deleted it from history and from recently closed, and also checked that I don't have that tab open on another device.

**Comment by itsmecom** [comment]
some url gets deleted and some url still shows in search bar. this occurs randomly and also when url gets redirected.

**Comment by cpeterso** [comment]
Sorry, without steps for QA to reproduce, this bug report is not actionable.
