### ISSUE TITLE
Add Drag and Drop to Rearrange Tabs

### ISSUE THREAD

**Issue by itsmecom** [mozilla-mobile/fenix#27721]
Currently there is no option to rearrange tabs position.
adding drag and drop to rearrange tabs could be useful for many users.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21936)
┆Link To Issue: https://mozilla-hub.atlassian.net/browse/FNXV2-21936

**Comment by cadeyrn** [comment]
It's already implemented in Firefox Nightly and will be included in the stable release of Firefox 108.

Duplicate of #10344.
