### ISSUE TITLE
[Bug]: *critical* m.youtube.com crashing 

### ISSUE THREAD

**Issue by sheikh-azharuddin** [mozilla-mobile/fenix#27725]
### Steps to reproduce

In the latest version available from playstore , m.youtube.com page is crashing..even I have uninstalled and freshly installed it but still same issue

Please fix soon 

### Expected behaviour

Page should load

### Actual behaviour

Page crashing

### Device name

asus rog 3

### Android version

android 12

### Firefox release type

Firefox Nightly

### Firefox version

latest

### Device logs

https://crash-stats.mozilla.org/report/index/8b1546a4-704a-488a-bea9-d059f0221105

### Additional information

![Screenshot_20221105-214716355](https://user-images.githubusercontent.com/58127841/200130496-0c7a6866-49fd-4106-b6cc-00b36c69045e.jpg)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21939)
┆Link To Issue: https://mozilla-hub.atlassian.net/browse/FNXV2-21939

**Comment by kbrosnan** [comment]
Duplicate bz-1799208

**Comment by levincoolxyz** [comment]
Are you sure this is a duplicate of bz-1799208 ? Website referenced in that post opens fine but YouTube still crashes.

**Comment by sheikh-azharuddin** [comment]
> Are you sure this is a duplicate of [bz-1799208](https://bugzilla.mozilla.org/show_bug.cgi?id=1799208) ? Website referenced in that post opens fine but YouTube still crashes.

Issue fixed now 😊
