### ISSUE TITLE
Implement HDR Playback on Firefox Android.

### ISSUE THREAD

**Issue by itsmecom** [mozilla-mobile/fenix#27723]
Implementing HDR support for videos could be useful. there are many hdr supported devices used by users.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21938)
┆Link To Issue: https://mozilla-hub.atlassian.net/browse/FNXV2-21938

**Comment by kbrosnan** [comment]
duplicate bz-1539685
