### ISSUE TITLE
Long press text to search

### ISSUE THREAD

**Issue by sayo-melu** [mozilla-mobile/fenix#2773]
### Why/User Benefit/User Problem
User can easily jump to search without copying and pasting.

### What/Requirements
When text is selected, it pops up a window with 'Copy' and 'Select all', there should also be a 'Search'.

### Acceptance Criteria (how do I know when I’m done?)
Jump to a new page with the default search engine of the selected text.

**Comment by buttercookie42** [comment]
Fennec has that already.

**Comment by Lululalu** [comment]
This is the same as #533
