### ISSUE TITLE
Firefox Nightly crashes when opening YouTube 

### ISSUE THREAD

**Issue by StSav012** [mozilla-mobile/fenix#27738]
### Steps to reproduce

1. Open a tab.
2. Go to https://m.youtube.com/ 
3. Watch the tab crash.

### Expected behaviour

The web page should load and remain loaded .

### Actual behaviour

The page loads, displays the content and than immediately crashes.

### Device name

Motorola moto g¹⁰⁰ (XT2125-4)

### Android version

Android 12

### Firefox release type

Firefox Nightly

### Firefox version

108.0a1

### Device logs

https://crash-stats.mozilla.org/report/index/3bf0d884-3cf5-4c60-b660-bd5b50221107

https://crash-stats.mozilla.org/report/index/6ace8c70-e7b2-4334-9f98-aa6ae0221106

https://crash-stats.mozilla.org/report/index/bp-346a9259-09fb-4e29-a8fa-31df60221107

### Additional information

Addons don't matter.

I first noticed the problem on Nov 6. On Nov 5, 09:00 UTC, the problem was not there (Firefox might not have been the most recent back then).

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21944)
┆Link To Issue: https://mozilla-hub.atlassian.net/browse/FNXV2-21944

**Comment by AdinaPetridean** [comment]
@StSav012 thank you for your report! The issue is reproducible on:  Firefox Nightly 108.0a1- 7/11 with One plus 9 Pro (Android 12).

**Comment by delia-pop** [comment]
The crash is also reproducible when attempting to enter https://vimeo.com/watch, on Nightly 108.0a1 from 11/06 with Samsung Galaxy Note10 (Android 12).
Not reproducible with soundcloud.com, or when attempting to play a video from twitter/facebook.

https://user-images.githubusercontent.com/89388888/200356761-3ad6e4a3-8f31-4b98-8db1-cde1da28d7cb.mp4

**Comment by kbrosnan** [comment]
duplicate bz-1799208
