### ISSUE TITLE
Make tab tray overflow menu background layer2 instead of layer1

### ISSUE THREAD

**Issue by fice-t** [mozilla-mobile/fenix#27734]
Using the color of layer2 results in a more readable menu IMO, particularly for the dark theme. It also makes the menu match with the toolbar overflow menu.

Before/After (light):
<img src="https://user-images.githubusercontent.com/13156601/200190690-27a4d4a8-db8d-4a7f-89f3-a82719372f9b.png" width=50%><img src="https://user-images.githubusercontent.com/13156601/200190800-af3d996f-14c7-49ec-819f-457f1bd629df.png" width=50%>

Before/After (dark):
<img src="https://user-images.githubusercontent.com/13156601/200190873-84794765-c072-447a-aa72-5287f258797e.png" width=50%><img src="https://user-images.githubusercontent.com/13156601/200190931-08dfda94-d490-46d6-8011-2f74f425a465.png" width=50%>

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21943)
┆Link To Issue: https://mozilla-hub.atlassian.net/browse/FNXV2-21943

**Comment by AdinaPetridean** [comment]
Verified as fixed on Nightly 108.0a1 from 11/10 with Motorola Moto G9 plus (Android 11). 

<img src="https://user-images.githubusercontent.com/108326843/201043152-accc66e6-8f62-43dc-9451-f85171cc11f2.JPEG" width="50%" /><img src="https://user-images.githubusercontent.com/108326843/201043174-d2549a0d-3e3c-4309-96d4-1267a8e4f5bd.JPEG" width="50%" />

**Comment by SoftVision-LorandJanos** [comment]
Verified on the latest Nightly 108.0a1 (2022-11-10) build.
Here are the differences between before and after:

Before

![Screenshot_20221110-103914](https://user-images.githubusercontent.com/48829350/201055756-6bb40ca8-5b38-4e08-ad95-6cb12692a0c7.png)
![Screenshot_20221110-104205](https://user-images.githubusercontent.com/48829350/201055758-691b6feb-ad53-4967-8468-975087ca0aac.png)


After

![Screenshot_20221110-104205](https://user-images.githubusercontent.com/48829350/201055819-22007375-d6cc-4426-a7fd-09914e7e2a32.png)

Closing the ticket as verified

**Comment by SoftVision-LorandJanos** [comment]
Verified on the latest Beta 108.0b1.
Device used: Google Pixel 4 (Android 13).
