### ISSUE TITLE
Move the text of Top Sites outside of the backplating

### ISSUE THREAD

**Issue by MozillaNoah** [mozilla-mobile/fenix#27746]
After https://github.com/mozilla-mobile/fenix/issues/26606, the two lines of text are being truncated, causing the Top Site's name and the `Sponsored` label to be ellipsized and sometimes indiscernible. The layout should be reverted and then design should be updated according to the following design changes:

- The title/sponsor name is colored to the wallpaper text color
- The pin is colored to the wallpaper text color
- The shadow along the top edge of each top site should be fully rendered (add a padding/margin of 4 to fix)

**Historical record**
- [Jira story](https://mozilla-hub.atlassian.net/browse/FNXV2-21923) (with linked slack thread and incident report)
- [Figma](https://www.figma.com/file/RlHwo5VqpEPAgYF1W4aisr/Mobile-Sponsored-Shortcuts?node-id=856%3A4351)
https://www.figma.com/file/RlHwo5VqpEPAgYF1W4aisr/Mobile-Sponsored-Shortcuts?node-id=2%3A4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21947)
┆Link To Issue: https://mozilla-hub.atlassian.net/browse/FNXV2-21947

**Comment by delia-pop** [comment]
Verified as fixed on the latest Nightly 108.0a1 from 11/08 with Google Pixel 6 (Android 13). The text of the Top Sites is displayed outside of the backplating, according to the wallpaper text color and the design.

![Shortcuts](https://user-images.githubusercontent.com/89388888/200633638-9320bc26-6aef-438c-9ffe-2dd2b2c52daf.png)

**Comment by delia-pop** [comment]
Tested with Google Pixel 6 (Android 13) on Release and Beta build variants build locally from the 107 branch, and  the text is correctly displayed under the shortcuts. The text color is also displayed according to the wallpaper text color, similar to Nightly.
I will re-test this tomorrow in the next official release as well.

![Incident_Top_Sites_Uplift](https://user-images.githubusercontent.com/89388888/201092950-031c6c48-7600-477c-9538-15d05bd3c9d3.png)

**Comment by delia-pop** [comment]
This is also verified as fixed on Firefox 107.1.0 build 2 with Samsung Galaxy Note10 (Android 12).

![1668174702424](https://user-images.githubusercontent.com/89388888/201355346-de03ad7c-be23-4413-9d17-bda51d28d4ae.JPEG)

**Comment by delia-pop** [comment]
This is also verified as fixed on Beta 108.0b1 with Motorola Moto G30 (Android 12).
