### ISSUE TITLE
push notifications work only on foreground

### ISSUE THREAD

**Issue by Shinryuken** [mozilla-mobile/fenix#27744]
### Steps to reproduce

I have already noticed other open issues regarding push notifications, this one maybe could be related but i think that is a different problem, notifications work when the app is on foreground, please see the "Additional info" section for more info.

Easy to reproduce:

1.  Go to the test site: h**ps://www.bennish.net/web-notifications.html (link checked with virustotal)
2. Click "Authorize" and then on "Show in 5s"
3. Quickly after step 2 minimize the browser app ( make sure that you accepted and enabled android notifications for the firefox app and push notifications for the web page )

### Expected behaviour

An android notification appears (with the notification sound)

### Actual behaviour

No notifications are displayed, the notification appears only when you put again the firefox app on foreground, (for some reason the notification sound is missing on firefox notifications, using other browsers with the same steps produce notifications with the common sound)

If you send a notification when firefox is on foreground ("Show" button on the web page) they work ( but notification sound is still missing )

### Android version

android 8, android 13

### Firefox release type

Firefox

### Firefox version

106.1.0

### Additional information

Using an older version of firefox ( v68 from h**ps://download.mozilla.org/?product=fennec-latest&os=android&lang=multi ) push notifications work as expected.

Notifications are working with other browsers on the same phone, tested on 3 different phones with android 8 and 13 with the same results.

As said before, there is a different behaviour between versions, on the latest version firefox notifications don't emit any sound ( on old firefox v68 and on other browsers they do ), this could mean that they are different implementations of push notifications/android notifications ???

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21946)
┆Link To Issue: https://mozilla-hub.atlassian.net/browse/FNXV2-21946

**Comment by AdinaPetridean** [comment]
@Shinryuken thank you for your report! I was able to reproduce this issue on: Firefox Nightly 108.0a1- 9/11 with Motorola Moto G9 plus - Android 11.

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1809287

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
