### ISSUE TITLE
Support Smart Text Selection

### ISSUE THREAD

**Issue by anyuzu99** [mozilla-mobile/fenix#2774]
### Why/User Benefit/User Problem
Open the App connected with the text in one tap.

### What/Requirements
When text is selected, the first item of Text Selection Menu should be with Smart Text Selection.

(Smart Text Selection is introduce on Android 9)

### Acceptance Criteria (how do I know when I’m done?)
Run the Smart Text Selection command.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-11672)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1809977

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
