### ISSUE TITLE
[Bug]: Youtube always crashes 

### ISSUE THREAD

**Issue by klint** [mozilla-mobile/fenix#27754]
### Steps to reproduce

Deactivate all add-ons in private mode
Open a tab in private mode
Go YouTube and try to watch a video 
The tab crashes 

Also happens in non private mode of course '

### Expected behaviour

Tab does not crash and video is played 

### Actual behaviour

Tab crashes and report is sent to Mozilla 

### Device name

Redmi note 7

### Android version

Android 9

### Firefox release type

Firefox Nightly

### Firefox version

Build #2015914347),

### Additional information

This has been happening in recent nightlies

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21951)
┆Link To Issue: https://mozilla-hub.atlassian.net/browse/FNXV2-21951

**Comment by sheikh-azharuddin** [comment]
The issue is fixed in the latest today' build

**Comment by klint** [comment]
It is indeed. I had missed the latest update because of a lack of disk space... Thanks
