### ISSUE TITLE
[Bug]: Search engines are not updated immediately after changing language

### ISSUE THREAD

**Issue by Mugurell** [mozilla-mobile/fenix#27753]
### Steps to reproduce

1. Change language from system language or app settings
2. Check the available search engines

### Expected behaviour

The list of available search engines is automatically updated for the newly selected locale

### Actual behaviour

An app restart is needed for the list of search engines to be updated.
The issues happens with or without unified search enabled.

### Firefox version

Seems like an old issue, happens in the current release also.

### Additional information

https://user-images.githubusercontent.com/11428869/200523702-ea08d843-a454-49e1-91a9-4246197008b7.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21950)
┆Link To Issue: https://mozilla-hub.atlassian.net/browse/FNXV2-21950

**Comment by SoftVision-LorandJanos** [comment]
Verified as fixed on the latest Nightly 109.0a1 (2022-12-07) build.
The search engines are updated immediately when switching for a different language.
Device used: Google Pixel 4 (Android 13).
Closing the ticket as fixed.

**Comment by AdinaPetridean** [comment]
Also verified implemented on Beta 109.0b1 with Poco M4 Pro (Android 12).
