### ISSUE TITLE
Move functionality defined in `MetricsMiddleware` to `TelemetryMiddleware`

### ISSUE THREAD

**Issue by MatthewTighe** [mozilla-mobile/fenix#27758]
We recently introduced `MetricsMiddleware`. However, there is an existing `TelemetryMiddleware` that has similar behavior. The functionality defined in `MetricsMiddleware` should instead be moved into `TelemetryMiddleware` so that there is not confusion between which to use.

- import `MetricController` to `TelemetryMiddleware`
- replicate behavior mapping `Action`s to `Event`s
- send `Event`s to `MetricController` as appropriate

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21952)
┆Link To Issue: https://mozilla-hub.atlassian.net/browse/FNXV2-21952

**Comment by DreVla** [comment]
I started working on this but I noticed that `MetricsMiddleware` and `TelemetryMiddleware` handle different states and actions (`AppState`, `AppAction` and `BrowserState`, `BrowserAction`). Should we consider making TelemetryMiddleware generic?

**Comment by MatthewTighe** [comment]
This should wait until we have a better idea of the direction we want for the growth data long term. There may end up being drastically different requirements for the next phase of design and implementation. I created this ticket before I really investigated the possibilities here and should not have marked it eng:ready.

AFAIK, we haven't really explored the pattern of generalized Middlewares. I believe we intend to rely on exhaustiveness checking of Action and State subtypes for correctness. Since the `BrowserStore` is defined in A-C, there are further complications in introducing an action similar to the `ResumedMetricsAction`.

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1809315

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
