### ISSUE TITLE
Setting top margin for SearchSelector in xml

### ISSUE THREAD

**Issue by mavduevskiy** [mozilla-mobile/fenix#27763]
Investigate if `SearchSelector` margin could be set through `xml` when it is used as part of the `SearchDialogFragment` and `HomeFragment`.

Follow up to [this](https://github.com/mozilla-mobile/fenix/pull/27647#discussion_r1014374484)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21955)
┆Link To Issue: https://mozilla-hub.atlassian.net/browse/FNXV2-21955

**Comment by cpeterso** [comment]
PR merged.
