### ISSUE TITLE
search icon scaling on the home might be not working

### ISSUE THREAD

**Issue by mavduevskiy** [mozilla-mobile/fenix#27764]
Investigate `search_icon` scaling in [HomeFragment](https://searchfox.org/mozilla-mobile/source/fenix/app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt#605). Changing parameters for the icon size has no effect on the icon, and `BitmapDrawable` has same `height` as the original icon,

Follow up to [this](https://github.com/mozilla-mobile/fenix/pull/27647#issuecomment-1301656042). The issue could be tested [here](https://github.com/mozilla-mobile/fenix/pull/27726#issuecomment-1305120483).

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21956)
┆Link To Issue: https://mozilla-hub.atlassian.net/browse/FNXV2-21956

**Comment by cpeterso** [comment]
PR merged.
