### ISSUE TITLE
material you theming

### ISSUE THREAD

**Issue by sheikh-azharuddin** [mozilla-mobile/fenix#27777]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### What is the user problem or growth opportunity you want to see solved?
I see all sections of the homescreen are utilising colors from the wallpapers..in the same way since android 12 and 13 has material you is it possible for firefox to pick system colors/system wallpapers colors and theme the homescreen of firefox like how Google apps are doing

### How do you know that this problem exists today? Why is this important?
The app theme will blend with the system

### Who will benefit from it?
A12 and A13 users

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21960)
┆Link To Issue: https://mozilla-hub.atlassian.net/browse/FNXV2-21960

**Comment by kbrosnan** [comment]
Duplicate https://github.com/mozilla-mobile/fenix/issues/20778
