### ISSUE TITLE
[webcontent] Regression: Display names containing Emoji on Nitter aren't bolded

### ISSUE THREAD

**Issue by sigmafn** [mozilla-mobile/fenix#27773]
## Site with issue and any steps to reproduce
https://nitter.snopyta.org/firefox

Load the Nitter link in Fenix Nightly and notice that unlike the display names not containing any Emoji the display name of the Firefox account isn't bolded.
This must have regressed somewhere between 106 and 107 because Fenix 106.1.0 is unaffected but 107.0b1 is already affected.

### Expected behavior
Screenshot from Fenix 106.1.0:
![Screenshot_20221104-134109](https://user-images.githubusercontent.com/107855363/200848946-79b550ae-79f2-462b-9059-b970a90ce146.png)

### Actual behavior
Screenshot from Fenix Nightly:
![Screenshot_20221104-133733](https://user-images.githubusercontent.com/107855363/200849023-8aab4db9-a6dd-456c-aed0-89cb9db7b5db.png)

### Does toggling Tracking Protection fix the issue? (Press the shield icon in the toolbar while on the site to see toggle)
No.

### Can you reproduce in Chrome (or other non-Mozilla browser)?
No Chrome behaves the same as Fenix 106.1.0.

### Device information

* Android device: Pixel 4a (5G)
* Android version: 13
* Fenix version: 108.0a1

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21959)
┆Link To Issue: https://mozilla-hub.atlassian.net/browse/FNXV2-21959

**Comment by kbrosnan** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1799942

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Comment by kbrosnan** [comment]
Could you check the behavior of https://play.google.com/store/apps/details?id=org.mozilla.firefox_beta

**Comment by kbrosnan** [comment]
No need to test beta, the devs on the core team know what versions are affected.
