### ISSUE TITLE
[Bug] Unable to load about:config

### ISSUE THREAD

**Issue by Seqularise** [mozilla-mobile/fenix#2778]
## Steps to reproduce
1. Write about:config in search tab and press enter
    1. Expected behavior
shows about:config page 
    1. Actual behavior
shows white page
    1. Device information
redmi note 4x
Android device: 9
Fenix version: 1.0.1921 (Build #11430615 68.0-20190520141152)

**Comment by Seqularise** [comment]
[logcat.txt](https://github.com/mozilla-mobile/fenix/files/3213572/logcat.txt)

**Comment by yilmzfurkan** [comment]
Have the same issue. 

[Photo](https://i.vgy.me/pJhlHz.jpg)

**Device information**
Samsung Galaxy S8+ (SM-G955F)
Android 9
Fenix Version: 1.0.1921 (Build #11431806 68.0-20190520141152)

**Comment by jonalmeida** [comment]
This was working for me on yesterday's nightly - I just updated to the one from today and it no longer works.

**Comment by buttercookie42** [comment]
Has Fenix switched to using Beta GeckoView? If yes, you'll need [bug 1540065](https://bugzilla.mozilla.org/show_bug.cgi?id=1540065) fixed.

**Comment by hakkikaancaliskan** [comment]
Yes they [updated](https://github.com/mozilla-mobile/fenix/commit/03d0ed9d6d450bf35e04080d8ad166628939ee3b) geckoview and [switched](https://github.com/mozilla-mobile/fenix/commit/c3ff7a1aba7ba7fd3af859866381d6d37396d977) to the beta.

**Comment by bifleming** [comment]
About page work will come later

**Comment by alexa-v2** [comment]
Why is this closed? 1.0.1925 it still doesn't work

It used to work if preview....

**Comment by robsmith11** [comment]
Shouldn't this stay open until about:config is restored?

**Comment by kbrosnan** [comment]
This is expected behavior from GeckoView. Fenix does not control access to it.
