### ISSUE TITLE
[Bug]Ads are not displayed in Nightly

### ISSUE THREAD

**Issue by tesmite** [mozilla-mobile/fenix#27785]
## Site with issue and any steps to reproduce
https://googleads.github.io/google-publisher-tag-samples/basic/display-test-ad/demo.html

### Expected behavior
Ads are displayed if you don't use AdBlock.

### Actual behavior
Ads are not displayed even if you don't use AdBlock.

### Does toggling Tracking Protection fix the issue? (Press the shield icon in the toolbar while on the site to see toggle)
Yes.
However in Firefox Beta, it doesn't happen with Tracking Protection.

### Can you reproduce in Chrome (or other non-Mozilla browser)?
It doesn't happen in Chrome and Firefox Beta.
Only happen in Firefox Nightly

### Device information

* Android device: Sharp AQUOS R3(Android 11)
* Fenix version: 108.0a1 (Build #2015914731)

**Comment by kbrosnan** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1800007

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Comment by tesmite** [comment]
It has been determined that this problem is due to a bug that causes Tracking Protection working in Strict mode regardless of the setting.
This report is inaccurate, so please report it elsewhere if necessary.
