### ISSUE TITLE
A compatibility issue in Android 5.1

### ISSUE THREAD

**Issue by rudmannn** [mozilla-mobile/fenix#27798]
I found compatibility issues in [toolbar_background.xml](https://github.com/mozilla-mobile/fenix/compare/main...rudmannn:fenix:main#diff-d87c72a21bcdb5c29833182f0741f37723a4a78c9524f2e9c9ffe4b7dd72ec61) and [toolbar_background_top.xml](https://github.com/mozilla-mobile/fenix/compare/main...rudmannn:fenix:main#diff-72f3586c8bf2651b5d60f11f01b2cf3a535fb38ebd873df89f81a741223680ed). 

You use android:gravity to draw the edge of the toolbar. However, android:gravity does not exist at Android < 6.0.
Therefore, the toolbar looks like this.

API Level 32
toolbar_background

![](https://user-images.githubusercontent.com/109571086/183243545-ad166709-8d4d-4da3-be23-22cad834d666.jpg)

API Level 22
toolbar_background

![](https://user-images.githubusercontent.com/109571086/183243571-852bbb6c-c02d-4926-a08f-558f27aeff16.jpg)

I sent a pull request in #26344.  You may consider my fix to this issue. It should work on both API levels 22 and 32.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21970)

**Comment by rudmannn** [comment]
There are still 2% of devices using Android 5.0+

<img width="1016" alt="image" src="https://user-images.githubusercontent.com/109571086/201466023-cba5c795-4ff2-42bf-9b6d-4f369fb0191b.png">

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813426

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Comment by cpeterso** [comment]
@rudmannn Thanks for diagnosing this bug and sharing a PR. I closed this GitHub issue because we're moving Firefox Android bug tracking to Bugzilla. I'll share a link to your PR in the new bug report tracking this problem: https://bugzilla.mozilla.org/show_bug.cgi?id=1813426
