### ISSUE TITLE
[Bug]: Allowed location site permission resets itself to blocked

### ISSUE THREAD

**Issue by zevelorgani** [mozilla-mobile/fenix#27802]
### Steps to reproduce

1. Open www.olg.ca
2. Allow location for the site
3. Navigate the site and refresh page several times
4. Check the site permissions

### Expected behaviour

Location permission for the site should be "allowed", as set by user.

### Actual behaviour

Location permission for the site is "denied"

### Device name

Moto G7 Play

### Android version

Android 10

### Firefox release type

Firefox

### Firefox version

106.1.0

### Additional information

It is impossible to use the site as it continually checks location, and the access permission is reset to denied when the site is navigated.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21973)

**Comment by kbrosnan** [comment]
This looks like a duplicate of https://github.com/mozilla-mobile/fenix/issues/25150
