### ISSUE TITLE
Firefox does not recognize the "fil" language tag, so add-ons who use "fil" instead of "tl" when localizing to Filipino will still be shown in English

### ISSUE THREAD

**Issue by IverCoder** [mozilla-mobile/fenix#27806]
### Steps to reproduce

1. Change Firefox's language to Filipino by going to Settings > Language and selecting "Tagalog" from the list.
2. Install add-ons that use the `fil` language tag to localize to Filipino, such as uBlock Origin and Dark Reader.
- Go to *Mga Add-on* > Add-on Manager
- Scroll down to the *Inirerekomenda* section; on a fresh install without add-ons you don't need to scroll down.
- Press the "+" button to the right of the extension of your choice, in our case uBlock Origin and/or Dark Reader.
3. Go to *Mga Add-on* > the add-on of your choice.

### Expected behaviour

The add-ons' UI should be in Filipino.

### Actual behaviour

The add-ons' UI was in English.

### Device name

Samsung Galaxy A03 (SM-A035F)

### Android version

Android 12 (One UI Core 4.1)

### Firefox release type

Firefox Beta

### Firefox version

107.0b6

### Additional information

This issue also occurs on [other platforms](https://bugzilla.mozilla.org/show_bug.cgi?id=1800155).

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21975)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812123

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
