### ISSUE TITLE
FNX3-16579 ⁃ [Bug] Button & icons colors on some android 5 & 6 devices

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#2780]
## Steps to reproduce
Similar to #1593.
On a Xiaomi Mi 4i (Android 5.0.2):
![Screenshot](https://user-images.githubusercontent.com/4037709/58262230-92957680-7d82-11e9-86c1-aacc5f2ccd81.png)UNITO-UNDERSCORE!2019-05-23-17-02-15-951!UNITO-UNDERSCORE!org mozilla fenix!
![Screenshot](https://user-images.githubusercontent.com/4037709/58262231-92957680-7d82-11e9-8376-c8789e7a92e4.png)UNITO-UNDERSCORE!2019-05-23-17-02-09-666!UNITO-UNDERSCORE!org mozilla fenix!
![Screenshot](https://user-images.githubusercontent.com/4037709/58262232-92957680-7d82-11e9-933c-0ebc35aa96d1.png)UNITO-UNDERSCORE!2019-05-23-17-36-32-269!UNITO-UNDERSCORE!org mozilla fenix!

* the QAB handler is not visible at all.

On Nexus 5 (Android 6) & Sony Xperia Z2 (Android 6.0.1):
![Screenshot](https://user-images.githubusercontent.com/4037709/58262395-e0aa7a00-7d82-11e9-8946-2b16f87de5d8.png)UNITO-UNDERSCORE!20190523-174650!

### Device information
* Android device: 
* Fenix version: 5/23 build.

**Comment by softvision-miralobontiu** [comment]
Verified as fixed with Xiaomi Mi4i (Android 5.0.2), Nexus 5 (Android 6), and Sony Xperia Z2 (Android 6.0.1), on the latest build 1.0.1922 (#11470614).
