### ISSUE TITLE
Set tab's GeckoSession priority based on existing form data

### ISSUE THREAD

**Issue by calumozilla** [mozilla-mobile/fenix#27803]
When a user switches tabs, Fenix should use GeckoView's containsFormData API (https://bugzilla.mozilla.org/show_bug.cgi?id=1764998) to check if the current GeckoSession has existing form data and set the tab's GeckoSession appropriately with setPriorityHint API: either PRIORITY_HIGH if there is form data or default if there isn't. This will tell Android's OOM killer to not kill processes and tabs that have form data the user is filling out. Fenix should also have a timeout of a few minutes in case the user does not intend to return to the tab with form data.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21974)

**Comment by cpeterso** [comment]
`GeckoSession.containsFormData` API: https://bugzilla.mozilla.org/show_bug.cgi?id=1777506

Fenix bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1800146

**Comment by cpeterso** [comment]
Bugzilla bug landed: https://bugzilla.mozilla.org/show_bug.cgi?id=1800146#c4
