### ISSUE TITLE
Use upstream android.R.string.{cancel, ok} and merge common string resources

### ISSUE THREAD

**Issue by fice-t** [mozilla-mobile/fenix#27812]
I've noticed that there are some strings that are duplicated several times in `strings.xml` where they don't have to be, including `Cancel`, `Ok`, `Delete`, `Edit`, `Close`, `Remove`, etc. Translation efforts would likely improve with merging the common uses together (I have noticed some languages miss translations of some instances of e.g. `Cancel`), and there is minor reductions in apk size associated with merging these resources (~`20 kB` with just changing all `Cancel` instances to `android.R.string.cancel`).

A PR will be linked shortly that tackles what I saw were the obvious cases.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21976)

**Comment by gabrielluong** [comment]
https://github.com/mozilla-mobile/fenix/pull/27813#issuecomment-1316080412

**Comment by cpeterso** [comment]
Closing this issue because the code landed back in November. This issue is still open because it was awaiting QA.
