### ISSUE TITLE
Make non-http(s) protocols invalid when adding new login

### ISSUE THREAD

**Issue by fice-t** [mozilla-mobile/fenix#27815]
Non-http(s) protocols are apparently not supported by Fenix at the moment (going by the `@string/add_login_hostname_invalid_text_3` hint), but the `AddLoginFragment` currently does not enforce this hint. A PR will be linked shortly that fixes this by upgrading the hint to a proper error.

At the same time, desktop Firefox auto-adds `https://` when adding a new login when no protocol is present, so I have implemented that for feature parity and a better user experience.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21977)

**Comment by gabrielluong** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1815632

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
