### ISSUE TITLE
PWA doesn't install

### ISSUE THREAD

**Issue by gdnzz** [mozilla-mobile/fenix#27818]
### Steps to reproduce

1. Open a site which has pwa support    e.g. twitch.tv
2. Press install from the menu

### Expected behaviour

It should create a pwa app on the homescreen

### Actual behaviour

Nothing happens when I press install

### Device name

Poco x3 nfc

### Android version

Android 12 SKQ1.211019.001

### Firefox release type

Firefox

### Firefox version

106.1.0

### Additional information

Same pwa works with chromium browsers

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21978)

**Comment by SoftVision-LorandJanos** [comment]
Hi @gdnzz! Thank you for your report!
I wasn't able to reproduce your issue on the latest Builds available.
Could you upgrade to 107.1.0, or maybe try it on the latest Nightly (108.0a1), and see if you can still reproduce it? Thank you!
Device used: Oppo Find X5 (Android 12)

**Comment by gdnzz** [comment]
Upgrade 107 isn't available for me. Tried it on Nightly, and it works.

**Comment by gdnzz** [comment]
@SoftVision-LorandJanos Also since you are here, ı want to add another thing. On chromium browsers, when I enable dark mode on the site, status bar and navigation bar also becomes black. However this is not the case on firefox, check pics
![IMG_20221115_174407](https://user-images.githubusercontent.com/76991571/201964387-4b69fd25-cb5d-4766-a6cb-14ca08c82082.jpg)
![IMG_20221115_174303](https://user-images.githubusercontent.com/76991571/201964392-72f066aa-9123-4938-bbda-e333beca6190.jpg)

**Comment by gdnzz** [comment]
site I tested is crypt.ee

**Comment by cpeterso** [comment]
> Upgrade 107 isn't available for me. Tried it on Nightly, and it works.

Thanks for testing. In that case, I'll close this issue as fixed.

> On chromium browsers, when I enable dark mode on the site, status bar and navigation bar also becomes black. However this is not the case on firefox, check pics

I think Bugzilla bug https://bugzilla.mozilla.org/show_bug.cgi?id=1807419 is the dark mode status bar issue.
