### ISSUE TITLE
[Bug]: Increase touch target for "Add bookmarks" entry in menu

### ISSUE THREAD

**Issue by topotropic** [mozilla-mobile/fenix#27827]
### Steps to reproduce

Go to a site an open the menu to add a bookmarks

### Expected behaviour

Bigger touch target

### Actual behaviour

Touch target is small

### Device name

Google Pixel 3

### Android version

Android 12

### Firefox release type

Firefox Nightly

### Firefox version

Most recent

### Additional information

See also https://connect.mozilla.org/t5/ideas/quot-add-quot-bookmark-button-android/idi-p/18986

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21983)

**Comment by kbrosnan** [comment]
Make the touch target the rest of the line that is not for the bookmarks view. See

https://connect.mozilla.org/t5/image/serverpage/image-id/2145i57F692493F9B2B3F/image-size/medium/is-moderation-mode/true?v=v2&px=400

https://connect.mozilla.org/t5/image/serverpage/image-id/2147i3539977087812BE0/image-size/medium/is-moderation-mode/true?v=v2&px=400

**Comment by DreVla** [comment]
Since this bug requires changes in Android Components I have created a ticket in bugzilla (https://bugzilla.mozilla.org/show_bug.cgi?id=1800885) for which I have just created a PR with changes that should fix this issue: https://github.com/mozilla-mobile/firefox-android/pull/164
