### ISSUE TITLE
Add snackbar to collection deletion

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#2783]
We had to remove the snackbar confirmation for collection deletion due to race condition bugs surrounding deleting in a background thread. It'd be great if we could, at some point, add the "undo" snackbar back.

Bugs caused by using the undo snackbar:

* #2730 
* #2727

**Comment by liuche** [comment]
If this is something that is waiting on AC, we should document that here - unclear to me what the dependency is.

**Comment by Djfe** [comment]
I would still love to see undo-functionality for collections. (in-case of an accident)

**Comment by SoftVision-LorandJanos** [comment]
Verified as implemented on the latest Nightly (94.0a1 - 2021-09-13T05:10:02.695825).

Devices used:

- Samsung Galaxy Tab S3 (Android 9).
- Huawei P30 (Android 10).
- Xiaomi Redmi 11 Lite (Android 11).

Closing the ticket as verified.
