### ISSUE TITLE
Add login: Wait for users to finish input before showing errors

### ISSUE THREAD

**Issue by Mugurell** [mozilla-mobile/fenix#27839]
When manually adding a login the application enforces certain rules about the URL.
There is a small issue in that these rules are enforced immediately after the user starts to write the URL and immediately showing an error that the not complete URL is invalid.

I propose validating the URL and potentially showing an error 
- after a small cooldown period of 3 seconds after the last typed character or
- after another field in the login form is focused (we infer that editing the URL is finished).

Current UX:

https://user-images.githubusercontent.com/11428869/201876273-15aae37c-ed26-4495-8099-2d4b0ec043f7.mov

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21988)

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813420

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
