### ISSUE TITLE
PlacesKt.placesApiNew blocks 3 DefaultDispatcher threads on start up (66ms during profiling, A51)

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#27831]
I took a start up trace using perfetto (which you can view by downloading it and "Open trace file" on https://ui.perfetto.dev): [startup.trace.zip](https://github.com/mozilla-mobile/fenix/files/10006156/startup.trace.zip)

In it, I found 3 DefaultDispatcher threads are blocked near activityResume: "monitor contention with owner" and "lock content on a monitor lock":

![image](https://user-images.githubusercontent.com/759372/201740355-81f00153-156b-427c-92d1-b011ccd1f56b.png)

The description for each is:
```
monitor contention with owner DefaultDispatcher-worker-1 (31) at 
mozilla.appservices.places.uniffi.PlacesApi
mozilla.appservices.places.uniffi.PlacesKt.placesApiNew(java.lang.String)(places.kt:1) 
waiters=2 blocking from java.lang.Object kotlin.SynchronizedLazyImpl.getValue()(LazyJVM.kt:10)
```

Putting long running work on the DefaultDispatcher is a potential problem because we have a limited number of DefaultDispatcher threads and, if they are all blocked, any other queued work cannot execute immediately. Devices generally have 1 defaultDispatcher thread per core so on devices with low core counts (e.g. 2, maybe 4), we may be blocking all the threads already.

I'm most concerned about low-end devices with lower specs than the A51. In particular, if there are fewer cores, we're more likely to be blocked. And if the device is slower, it'll take longer than 66ms.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21984)

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807354

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
