### ISSUE TITLE
Please add an option to stop adding shortcuts other than pinned shortcuts in homepage

### ISSUE THREAD

**Issue by shockergit** [mozilla-mobile/fenix#27848]
currently even when we turn of sponsored shortcuts firefox automatically add shortcuts from browser history to homepage when we turn of shorcuts. Please add an option to turn off this feature, I only want to see pinned shortcuts in my homepage nothing from history or bookmarks

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21991)

**Comment by kbrosnan** [comment]
Duplicate #24271
