### ISSUE TITLE
[Bug]: Tapping on "View" from Private browsing displays private home screen instead of the wallpaper - home screen

### ISSUE THREAD

**Issue by MozillaNoah** [mozilla-mobile/fenix#27852]
Steps to reproduce:
1. Open Private Browsing.
2. Go to Settings → Wallpapers → Change a wallpaper.
3. Tap on “View”.

Expected result: the new wallpaper is displayed/ normal browsing - homescreen.

Actual result: Private browsing homescreen is displayed. 

Environment:

Devices: all.

Original Jira Story: https://mozilla-hub.atlassian.net/browse/FNXV2-19463

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21992)

**Comment by delia-pop** [comment]
Also verified fixed on Beta 109.0b1 with Lenovo Yoga Tab 11 (Android 11).
