### ISSUE TITLE
How can I build Fenix Nightly version Mozilla Firefox?

### ISSUE THREAD

**Issue by mamunabcoder** [mozilla-mobile/fenix#27862]
There is no way to build the Nightly Fenix, Also there is no proper documentation to build the Nightly version Fenix. Please help me to build the Nightly version Fenix.

I am using macOS Monterey (12.6)
Device config: Apple M1 chip

 I had created bug but there is no proper answers and close the one.
 
 Please answer this questions properly if possible.
 
 Note: I am try to build in Android Device
 
 Another things, How can a developer understand the below document to understand Nightly build:
 
_

> [Building debuggable release variants
> 
> Nightly, Beta and Release variants are getting published to Google Play and therefore are not debuggable. To locally create debuggable builds of those variants, add the following to <proj-root>/local.properties:
> 
> debuggable

_

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21995)

**Comment by cadeyrn** [comment]
Same as #27825.

**Comment by kbrosnan** [comment]
Issues are not a good place to get help building. We have developers building on M1 on a daily basis. The real time element chat mentioned at https://github.com/mozilla-mobile/fenix/wiki#communication is a better place to ask such questions. Providing the end of your build log showing the error can be helpful.

In general clearing the Gradle cache can fix common build problems.
