### ISSUE TITLE
can't download file in Cloudflare page

### ISSUE THREAD

**Issue by hsoftxl** [mozilla-mobile/fenix#27870]
https://romspure.cc/download/under-defeat-hd-deluxe-edition-22829/1

can't download file in this link.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21998)

**Comment by kbrosnan** [comment]
This is a dangerous site. It did a drive by download of an APK when I clicked a wrong link. 

When I found the right link I was able to download the file on Firefox 108.0b1
