### ISSUE TITLE
[a11y] Consider making "Career" button from "Stories by topic" (home page) larger

### ISSUE THREAD

**Issue by AdinaPetridean** [mozilla-mobile/fenix#27876]
### Steps to reproduce

1. Have the Accessibility scanner app installed and opened.
2. Launch Fenix.
3. Use the Accessibility Scanner and scan the Homepage. Observe the suggestion.

### Expected behaviour

The height of this touch target should be 48 dp or larger.

### Actual behaviour

This item's height is 44 dp.

### Device name

OnePlus 9 Pro 

### Android version

Android 12

### Firefox release type

Firefox Beta

### Firefox version

Firefox 108.0b1

### Additional information

<img src="https://user-images.githubusercontent.com/108326843/202406450-07d3c9c1-1142-48fa-93bf-87a740063d55.JPEG" width="50%" /><img src="https://user-images.githubusercontent.com/108326843/202406462-707b5d69-9c72-4d96-8c2c-a0edeaa18a15.JPEG" width="50%" />

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-22001)

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1809812

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
