### ISSUE TITLE
Normalize search widget previews for all variants

### ISSUE THREAD

**Issue by Alexandru2909** [mozilla-mobile/fenix#27877]
In https://github.com/mozilla-mobile/fenix/pull/27480 we saw that there are differences between the search widget previews for each variant. Based on [this comment](https://github.com/mozilla-mobile/fenix/pull/27480#issuecomment-1309271978), we should check why the icons are different sizes.

Tagging UX to add the official designs for each search widget preview.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-22002)

**Comment by mavduevskiy** [comment]
@topotropic 
I am not sure who should we ask to review the icons but we need help :)

**Comment by topotropic** [comment]
> @topotropic I am not sure who should we ask to review the icons but we need help :)

@cwzilla here's an icon related question, can you have a look? Thanks!

**Comment by cwzilla** [comment]
Hi @mavduevskiy, I can look into this! What is the actual preferred size needed for the logo icons?

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813418

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
