### ISSUE TITLE
Fix bug 1799049

### ISSUE THREAD

**Issue by kbrosnan** [mozilla-mobile/fenix#27875]
https://bugzilla.mozilla.org/show_bug.cgi?id=1799049

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-22000)

**Comment by kbrosnan** [comment]
Addressing bz-1799043 at the same time may make sense.

**Comment by Alexandru2909** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1799049 was closed as verified, we can close this issue now.
