### ISSUE TITLE
[Bug]:[a11y] Consider making "Site", "Username" and "Password" fields from "Add new login" page larger

### ISSUE THREAD

**Issue by AdinaPetridean** [mozilla-mobile/fenix#27880]
### Steps to reproduce

1. Have Google Accessibility Scanner installed.
2. Go to Settings - Logins and passwords - Saved logins
3. Enter the device pattern and tap on the "Add login" button.
4. Scan the "Add new login" page.

### Expected behaviour

No suggestions are made.

### Actual behaviour

This items height is 43 dp. Consider making the height of this items target 48 dp or larger.

### Device name

OnePlus 9 Pro 

### Android version

Android 12

### Firefox release type

Firefox Beta

### Firefox version

Firefox 108.0b1

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-22004)

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812357

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
