### ISSUE TITLE
Dark mode causes links opened from Google news feed to look blank until you switch tabs

### ISSUE THREAD

**Issue by zl-zhou** [mozilla-mobile/fenix#27887]
### Steps to reproduce

1. Set phone and Firefox to dark mode 
2. Go to the Google news feed on the leftmost screen on Pixel devices
3. Click on web links

### Expected behaviour

Web page contents should display without needing to switch tabs

### Actual behaviour

Some links open what appear to be blank tabs. However, switching to another tab and then switching back will show that content has actually been loaded.

The same links that do not load in dark mode do not exhibit the same behavior if Firefox is changed to light mode.

### Device name

Google Pixel 6a

### Android version

Android 13

### Firefox release type

Firefox

### Firefox version

106.1.0

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-22008)

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813417

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
