### ISSUE TITLE
Update Time When Set To Default Notification is Sent 

### ISSUE THREAD

**Issue by kbrosnan** [mozilla-mobile/fenix#27885]
The Set to default notification should be sent 72 hours after installation. Currently it is set at 24 hours. Everything else related to the notification should stay the same.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-22007)

**Comment by delia-pop** [comment]
Verified fixed on latest Lightly 109.0a1 from 11/22 with Google Pixel 6 (Android 13) and Google Pixel 3a (Android 11). 
The notification is sent after 72 h of inactivity, and it is not sent if the user already has Fenix Nightly set as default browser or if the browser is set as default before the 72h of inactivity deadline.

https://user-images.githubusercontent.com/89388888/203353813-4ac5cda3-6d98-4e88-8a9c-ad98cab2709b.mp4

Furthermore, the telemetry events and metrics were correctly captured.

![Events_Metrics](https://user-images.githubusercontent.com/89388888/203353872-7cd0dbcb-6d3f-4d11-b335-0accc95ae294.png)
