### ISSUE TITLE
[Bug]: Adjust font weight in share sheet 

### ISSUE THREAD

**Issue by topotropic** [mozilla-mobile/fenix#27896]
### Steps to reproduce

Open share sheet

![Screenshot (Nov 11, 2022 1 53 59 PM)](https://user-images.githubusercontent.com/353960/202682454-cbd80449-96f4-4d36-962c-0d46e6c85910.png)

### Expected behaviour

Headers have the same font weight

### Actual behaviour

Headers have different font weights

### Android version

Android 12

### Firefox release type

Firefox Nightly

### Firefox version

-

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-22011)

**Comment by delia-pop** [comment]
Also verified fixed on Beta 109.0b1 with Lenovo Yoga Tab 11 (Android 11).
