### ISSUE TITLE
Review "Set Firefox to open links in apps" messaging

### ISSUE THREAD

**Issue by topotropic** [mozilla-mobile/fenix#27893]
When you have a fresh install and open Google or go to Twitter, you get a message asking you whether you want to open links in apps. The timing and context of the message doesn't seem ideal. We should revisit it and come up with a more apt behavior. Thanks!

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-22009)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1809288

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
