### ISSUE TITLE
FNX3-16587 ⁃ [Bug] Custom tabs is not covering the full screen size

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/fenix#2789]
## Steps to reproduce
Open a site in a custom tab.

### Expected behavior
The web contents covers the whole screen.

### Actual behavior
The bottom part is not covered

![Screenshot](https://user-images.githubusercontent.com/773158/58280247-2f014e00-7d6e-11e9-8fe7-7c4f4533d980.png)UNITO-UNDERSCORE!20190523-151622!

### Device information
* Android device: Pixel 3

**Comment by Amejia481** [comment]
I this this issue is related to this commit https://github.com/mozilla-mobile/fenix/commit/763c8be8150ff9c7585a7dfd3f096eebce58b246

**Comment by ReekyMarko** [comment]
Can confirm. This is even more pronounced if using a dark theme

![](https://i.imgur.com/LqHTx8h.png)

**Comment by sv-ohorvath** [comment]
Verified as fixed on the 5/29 build.
