### ISSUE TITLE
Firefox forgets pages' zoom level and scroll position when screen goes black or the phone is rotated

### ISSUE THREAD

**Issue by illcutyouin** [mozilla-mobile/fenix#27901]
### Steps to reproduce

open https://gamefaqs.gamespot.com/ps/197483-grandia/faqs/6812 scroll to any location  in the guide, flip phone to horizontal, let the phone go to a black screen from idle or keep firefox open but click the home button and or flip back to vertical, flip from vertical back to horizontal on open tab.

### Expected behaviour

open tabs should keep zoom level and location when resuming use

### Actual behaviour

zoom on current tab is maxed out and exact location of text is off and needs to be scrolled back up or down.

### Device name

Samsung Note10+

### Android version

Android 12

### Firefox release type

Firefox

### Firefox version

107.1.0

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-22013)

**Comment by illcutyouin** [comment]
ok a update just discovered that both issues seem to be caused by me holding the bottom and right side of the phone with my palm and thumb when bringing it back from the black screen not sure what changed in the latest update to do that or if it's worth fixing for the dev team but figured i would let you know.

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813415

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
