### ISSUE TITLE
Latent 302 redirect pages sticking around after opening in app

### ISSUE THREAD

**Issue by ehawman** [mozilla-mobile/fenix#27909]
### Steps to reproduce

1. Browse to a site with a link that you want to open in another app (eg a YouTube link or an Amazon link)
2. Click on the link, the app launches.
3. Later, return to Fennec, only to find that before you can start searching, the redirect triggers again and you're shunted out to the app

### Expected behaviour

When clicking on a link that opens in another app, Fennec should either close the 302 page or retain the page containing the link (perhaps it opens the redirect link in a new tab then immediately closes it)

### Actual behaviour

302 pages stick around until you close them.

When going through the list of open tabs, I've had three or four 302 pages that trigger each time if I don't remember to close them before they become the active tab.

### Device name

Galaxy S20+ Ultra

### Android version

Android 12

### Firefox release type

Firefox

### Firefox version

101.1.1 (Build #1011120), 8092b4e74+

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-22016)

**Comment by lm1baker** [comment]
I have also noticed this with Slack login, which redirects to the browser (Firefox), and from there back to Slack. This evicts Firefox from memory, and trying to reopen it causes a page reload, which again launches Slack. Setting "flight mode" is the only way out of this loop.

**Comment by csadilek** [comment]
> 101.1.1 (Build #1011120), https://github.com/mozilla-mobile/fenix/commit/8092b4e74c849a61df8a55b3367d1d13f52035e8+

This was fixed in version 105, see https://github.com/mozilla-mobile/fenix/issues/12113 for details. Please file a new issue if you still experience the 302 redirect pages.
