### ISSUE TITLE
[Bug]: home screen pages are closed apon restarting the app

### ISSUE THREAD

**Issue by ErikTheGrate** [mozilla-mobile/fenix#27905]
### Steps to reproduce

1. Have a new tab open.
Go to any website on that new tab(but it has to be a website)
2032.open another new tab
Stay on the homepage
.3 close the app from the recent apps menu
4 reopen firefox 

### Expected behaviour

You should see the homepage you opened

### Actual behaviour

Any homepage tabs opened before the app being closed will seize to exist and it will start loading the last tab (in this case the any website tab will be the only tab open and therefore load)
Witch wastes power. Crome doesn't do this but it doesn't work on my phone

### Device name

Samsum galaxy s3

### Android version

4.4.2

### Firefox release type

Firefox

### Firefox version

68.11.0

### Additional information

This isn't too inportant it just bothers me.
I use normal firefox but it won't let me select

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-22014)

**Comment by kbrosnan** [comment]
v68 has been out of support since September of 2020

**Comment by ErikTheGrate** [comment]
> v68 has been out of support since September of 2020

ok understood _but i dont like it_.
what happens in the latest version

**Comment by ErikTheGrate** [comment]
> v68 has been out of support since September of 2020

case closed i guess
