### ISSUE TITLE
Fenix crashes leave files behind which cannot be cleared and waste precious user storage space

### ISSUE THREAD

**Issue by KennethHeal** [mozilla-mobile/fenix#27907]
### Steps to reproduce

Have Fenix crash for whatever reason

### Expected behaviour

Any required crash data should be uploaded and then local files removed.

### Actual behaviour

As part of https://github.com/mozilla-mobile/fenix/issues/26420 we discoverd that crashes were leaving behind files:
/data/user/0/org.mozilla.firefox/files/mozilla/Crash Reports/pending/ 647585 debugger eval code:16:10
/data/user/0/org.mozilla.firefox/files/mozilla/4pllbj0b.default/minidumps/ 23662792 debugger eval code:16:10

And trhe about:crashes tab does not offer anyway to clear old crash files. (see dev comments in https://github.com/mozilla-mobile/fenix/issues/26420)
[console-export-2022-11-19_12-34-36.redacted.txt.gz](https://github.com/mozilla-mobile/fenix/files/10046952/console-export-2022-11-19_12-34-36.redacted.txt.gz)

### Device name

Samsung Galaxy Tab E SM-T560NU

### Android version

Android 7/1/1

### Firefox release type

Firefox

### Firefox version

106.1

### Device logs

https://crash-stats.mozilla.org/report/index/3e5961df-c432-4b2b-8621-af26f0221010

Going via about:support will sometimes give you this
![Screenshot_20221119-131854 1](https://user-images.githubusercontent.com/15162365/202850593-f8f2f934-b99c-4f81-b7f1-7768a779d083.jpg)

about:crashes gives this
![Screenshot_20221119-131926 1](https://user-images.githubusercontent.com/15162365/202850626-8be0af23-605e-49aa-8874-809089dfb1b2.jpg)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-22015)

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813414

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
