### ISSUE TITLE
When opening a new tab, open it after the current one, instead of at the end of the tab list

### ISSUE THREAD

**Issue by TheBrokenRail** [mozilla-mobile/fenix#27914]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### What is the user problem or growth opportunity you want to see solved?

Whenever a new tab is opened (whether because of "Recently closed tabs", the new tab button, or being opened by another app), it's added to the end of the tab list, instead of after the current tab. This is pretty annoying if I have a lot of tabs open. I'd prefer if the new tab was inserted after the current tab.

### How do you know that this problem exists today? Why is this important?

Because scrolling through all my tabs to get to my old tab is really annoyibg.

### Who will benefit from it?

Anyone with lots of tabs open.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-22019)

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813412

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
