### ISSUE TITLE
[Bug]: Android addons fail to install

### ISSUE THREAD

**Issue by Falcon9h** [mozilla-mobile/fenix#27918]
### Steps to reproduce

Go to addon page, I hit + to install addon, all I get is (xxxx) addon failed to install. 

### Expected behaviour

Damned addon should install

### Actual behaviour

Addons (all of them) won't install

### Device name

Samsung Note 20 ultra

### Android version

12

### Firefox release type

Firefox

### Firefox version

107.1.0

### Additional information

107.1.0 (Build #2015915067), a4c625827+
AC: 107.0.7, 7d69de3da4
GV: 107.0-20221110173214
AS: 94.2.2

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-22021)

**Comment by amocirean** [comment]
Hello @Falcon9h  , thank you for submitting the issue.
I was not able to reproduce it on the latest RC(107.1.0) or Nightly(109.0a1). Are you trying to install add-ons from the Firefox integrated Add-on Manager?
Could you tell us if the issue is still occuring on the latest Nightly on your device?

Devices Used: Huawei P40 Lite (Android 10), Samsung Galaxy S22 Ultra (Android 13)

**Comment by vehosah** [comment]
> Hello @Falcon9h , thank you for submitting the issue. I was not able to reproduce it on the latest RC(107.1.0) or Nightly(109.0a1). Are you trying to install add-ons from the Firefox integrated Add-on Manager? Could you tell us if the issue is still occuring on the latest Nightly on your device?
> 
> Devices Used: Huawei P40 Lite (Android 10), Samsung Galaxy S22 Ultra (Android 13)

Can you ever reproduce any issues at all?

**Comment by kbrosnan** [comment]
For supported extensions this works for me. If you are looking for general availability of extensions see https://blog.mozilla.org/addons/2022/12/15/new-extensions-available-now-on-firefox-for-android-nightly/ and https://connect.mozilla.org/t5/ideas/expand-add-on-compatibility-in-firefox-for-android/idi-p/191
