### ISSUE TITLE
Ability to rearrange tabs

### ISSUE THREAD

**Issue by TheBrokenRail** [mozilla-mobile/fenix#27915]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### What is the user problem or growth opportunity you want to see solved?

If you have lots of tabs open, you can't really organize them. It would be helpful if you could rearrange them in list view.

### How do you know that this problem exists today? Why is this important?

Because I'm affected by it and I imagine others are too.

### Who will benefit from it?

People with lots of open tabs.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-22020)

**Comment by kbrosnan** [comment]
This is in v108 currently on beta
