### ISSUE TITLE
Make pressing the back button *not* close the current tab when there's no history

### ISSUE THREAD

**Issue by TheBrokenRail** [mozilla-mobile/fenix#27913]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### What is the user problem or growth opportunity you want to see solved?

If I accidentally press the back button on a tab with no history (for instance, if it was created with "Oprn in new tab"), the tab closes. I'd prefer if this didn't happen because it's then pretty annoying to open the tab back up again.

### How do you know that this problem exists today? Why is this important?

Because I've accidentally hit the back button a few times, and it's quite annoying that it's so easy to close your current tab by mistake.

### Who will benefit from it?

Me and presumably other people who accidentally hit the back button.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-22018)

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813413

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
