### ISSUE TITLE
Consider displaying bookmark folders at the top of the list

### ISSUE THREAD

**Issue by grigoryk** [mozilla-mobile/fenix#2792]
Currently they're being displayed according to their order, but that doesn't work all that well on mobile. Navigating out of a folder takes you to the top of the list, which makes browsing multiple folders quite hard.

In Fennec, folders are pinned to the top, which makes things much more straightforward.

**Comment by ekager** [comment]
I agree that Fennec's pinning is better. I was able to get all folders at the top by doing some sorting, but I wasn't sure how to handle the bookmark separators between a bookmark and a folder... We may need some UX feedback here.

**Comment by mheubusch** [comment]
@AmyYLee Can you review this and point emily to any existing specs that address this if they exist? If not pls reassign to nicole so she can address with any other bookmark considerations.

**Comment by AmyYLee** [comment]
Assigning this to @topotropic a since she had worked on bookmarks.

**Comment by topotropic** [comment]
@ekager sounds good – can we sort the folders so that the latest created is at the top? 

Can you explain the issue with the separators – not sure if I understand it. Thanks!

**Comment by ekager** [comment]
On Desktop we allow users to create/move/edit separators that they can place between bookmarks in a specific place. We represent those in Fenix but don't allow users to add, move, or edit them. If we start sorting bookmark folders to the top, the separators could end up in strange places. 

like if the order was 
- bookmark
- folder
- separator
- folder
- separator

and we moved all the folders to the top you would end up with 
- folder
- folder
- bookmark
- separator
- separator

From quick testing I'm not sure Fennec shows separators. Maybe that's the direction we should take as well.

**Comment by lime124** [comment]
removed ux label as this is part of the q3 plans.

**Comment by topotropic** [comment]
@vesta0 this is related to https://github.com/mozilla-mobile/fenix/issues/2961 so we should either close it as well or give it a lower priority

**Comment by vesta0** [comment]
@topotropic this issue is about grouping the folders at the top before displaying the bookmarks (right now they are just added based on the order they are last created) so it's not the same issue but both issues are impacted by bookmark separators. @ekager says we can choose to not show that view type that include the separators. Would you look into the bookmarks separators and let us know if you think they add value from a user experience perspective, over the ability to sort folders and bookmarks?

**Comment by lime124** [comment]
@topotropic and @ekager to collaborate on it.

**Comment by grigoryk** [comment]
Okay, better late than never, I guess! Should be fixed by https://github.com/mozilla-mobile/fenix/pull/15213, and I'll deal with separators _separately_ in https://github.com/mozilla-mobile/fenix/issues/15214.

**Comment by ebalazs-sv** [comment]
I  had tested this on Nightly 200921 06:05 (Build #2015765171) GV 82.0a1 from 9/21 with Motorola Moto G6 (Android 8), Google Pixel 2 (Android 9), Nexus 5 (Android 6.0.1) and the results are:
- the new created bookmarks are displayed at the top of the list but the last created bookmark is added as the last folder and not the first folder: https://github.com/mozilla-mobile/fenix/issues/15261
- the existing bookmarks are displayed at the top of the list;

I will remove the qa:needed label and close this issue.
