### ISSUE TITLE
[Bug]: On home The address bar is still focused even though user has tapped outside of it

### ISSUE THREAD

**Issue by t-p-white** [mozilla-mobile/fenix#27926]
### Steps to reproduce

1. Open Firefox
2. On the 'homepage' clicked on the address bar
3. minimize the address bar
4. Click (non functional) area outside of address bar 
5. Observe the settings icon is no longer visible on the homescreen 

### Expected behaviour

Clicking on a non functional area outside of the address bar shoud remove focus from the keyboard and the settings icon should be displayed

### Actual behaviour

Clicking on a non functional area outside of the address bar does not remove focus from the keyboard and the settings icon is not displayed

https://user-images.githubusercontent.com/1833156/203099501-4d04ea05-21ce-4a60-a205-a2ebc1e1f192.mov

### Device name

Google Pixel 7

### Android version

Android 13

### Firefox release type

Firefox

### Firefox version

107.1.0

### Additional information

Also tested on Nightly with Unified search enabled. Same issue observed.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-22024)

**Comment by t-p-white** [comment]
This will likely be fixed by https://github.com/mozilla-mobile/fenix/pull/27262, thanks @Alexandru2909

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1810909

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
