### ISSUE TITLE
Orientation is not respected when loading wallpapers

### ISSUE THREAD

**Issue by MatthewTighe** [mozilla-mobile/fenix#27938]
### Steps to reproduce

1. Have a wallpaper selected
2. Rotate the device into landscape

### Expected behaviour

The landscape version of a wallpaper should be used

### Actual behaviour

The landscape version of a wallpaper is never used.

This is because `resources.configuration.orientation` does not seem to be updated during the orientation change in `DefaultLoadBitmapUseCase` which can be observed in debug mode. I would guess this is due to `HomeActivity` manually handling orientation changes. See the line: `android:configChanges="keyboard|keyboardHidden|mcc|mnc|orientation|screenSize|layoutDirection|smallestScreenSize|screenLayout"` is the Android Manifest for context. 

### Android version

Any

### Firefox release type

Firefox

### Firefox version

Any recent version

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-22028)

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1809798

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
