### ISSUE TITLE
Black unresponsive screen after returning to custom tab after some time

### ISSUE THREAD

**Issue by jamienicol** [mozilla-mobile/fenix#27947]
### Steps to reproduce

1. Open a custom tab in another app, eg opening a link in Slack.
2. Minimise Slack, and use several other applications until the OS decides to kill the gecko content process
3. (Or in a debug build you can run `adb shell ps | grep mozilla` to see the name of the content process, then `adb shell run-as org.mozilla.fenix.debug killall org.mozilla.fenix.debug:tabXX`
4. Re-open Slack 

### Expected behaviour

The page should load in the custom tab as expected

### Actual behaviour

The contents of the custom tab remains black and nothing loads. By running `adb shell ps | grep mozilla` I can see that a new content process is **not** started.

### Device name

Google Pixel 6A

### Android version

Android 13

### Firefox release type

Firefox Nightly

### Firefox version

109.0a1

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-22032)

**Comment by DiegoARL38** [comment]
This also applies to PWAs. There was an issue for it, but I can't find it.

**Comment by DiegoARL38** [comment]
Found it! It's #19157.

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812359

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
