### ISSUE TITLE
Consider increasing the checkboxes on the notification page

### ISSUE THREAD

**Issue by AdinaPetridean** [mozilla-mobile/fenix#27946]
### Steps to reproduce

1. Have Google Accessibility Scanner installed.
2. Go to Settings -Notifications
3. Scan the notifications page. Observe the scanned page.

### Expected behaviour

No suggestions are made.

### Actual behaviour

This items height is 24 dp. Consider making the height of this items target 48 dp or larger.

### Device name

OnePlus 9 Pro 

### Android version

Android 12

### Firefox release type

Firefox Beta

### Firefox version

Firefox 108.0b3

### Additional information

<img src="https://user-images.githubusercontent.com/108326843/203333755-0c8ab001-5ac9-4db1-bde6-c37ff021e537.JPEG" width="50%" />

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-22031)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1809289

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
