### ISSUE TITLE
Add option to prevent Sites Shortcut automatically adding to Browser Home Page

### ISSUE THREAD

**Issue by MayaBi7** [mozilla-mobile/fenix#27964]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can  #@
![IMG_20221124_105857](https://user-images.githubusercontent.com/96541364/203703030-aba1bacd-d9d0-4207-9b20-63b760761656.jpg)
keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### How do you know that this problem exists today? Why is this important?
I know because I use the Browser, After surfing on Facebook whenever I came back to home screen I see lots off Broken Facebook Shortcut in home screen plz fix this and also give a option where we can toggle ON or OFF Shortcut from automatically adding to home screen...
### Who will benefit from it?

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-22046)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812372

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
