### ISSUE TITLE
Tracking UI Tests disabled with frequent ANR

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#27966]
### Related tickets:
See: https://github.com/mozilla-mobile/fenix/issues/24047
See: https://github.com/mozilla-mobile/fenix/issues/25926
See: https://bugzilla.mozilla.org/show_bug.cgi?id=1764605

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-22048)

**Comment by AndiAJ** [comment]
`verifySponsoredShortcutsSponsorsAndPrivacyOptionTest` was disabled in #27967

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807267

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
