### ISSUE TITLE
[Bug]:  The application crashes after deleting the last inactive tab displayed in the list 

### ISSUE THREAD

**Issue by delia-pop** [mozilla-mobile/fenix#27975]
### Steps to reproduce

1. Have a few tabs opened.
2. Make them inactive. 
3. Go to tabs tray and expand the inactive tabs list.
4. Tap on the "X" button on the right of the last tabs from the list.
5. Observe that the application closes unexpectedly.  

### Expected behaviour

The application should remain stable. 

### Actual behaviour

The application crashes after deleting the last inactive tab displayed in the list. 
However, crash reports are created in About Firefox > Crashes.

### Device name

Google Pixel 6, Lenovo Yoga Tab 11

### Android version

Android 13, Android 11

### Firefox release type

Firefox Nightly

### Firefox version

Nightly 109.0a1 from 11/25

### Device logs

[108.0b4.txt](https://github.com/mozilla-mobile/fenix/files/10093665/108.0b4.txt)
[Nightly109.11.25.txt](https://github.com/mozilla-mobile/fenix/files/10093666/Nightly109.11.25.txt)
[Fenix_CrashReport.txt](https://github.com/mozilla-mobile/fenix/files/10093676/Fenix_CrashReport.txt)

### Additional information

Note that the issue does not have a 100% repro rate.
Reproducible on Beta 108.0b4 as well. 
Could not be reproduced on Release. 

https://user-images.githubusercontent.com/89388888/204013827-60e2d3f4-b13d-43ed-b38c-6855737ed786.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-22052)

**Comment by MozillaNoah** [comment]
Drive by: I was able to reproduce this, but only by:
1. Marking at least 2 tabs as inactive. One tab HAS to be the currently open tab and the last tab in the list.
2. Closing the very last tab in the inactive tabs list (e.g. the tab that is currently open)

So the key detail may be closing an inactive tab that is currently open.

I can confirm that the uncaught exception is: `PlacesApiException$UnexpectedPlacesException`, as listed in the above text files.

**Comment by MatthewTighe** [comment]
I will continue to investigate, but I'm curious about 2 things:

1. Is this reproducible if the last inactive tab is _not_ the selected tab? 
2. Is this reproducible if tabs become inactive naturally and are not forced to be inactive?

**Comment by MatthewTighe** [comment]
It looks like this is only reproducible if the last inactive tab is the currently selected tab. That state should not be reproducible in production channels as the selected tab will not become inactive even after the 2 week period has gone by. 

Since this is an edge case only reproducible on debug builds, I will close this as wont-fix for now. If there are reproducible steps I can follow for a release build, please feel free to re-open and we will continue investigation 🙂

**Comment by MatthewTighe** [comment]
For clarity, I tried the following things:

Using a release beta build, I opened several tabs and then changed the device time to be 4 months in the future. The last selected tab was still active, and the others were inactive. Closing the last inactive tab from that list did not reproduce the bug.

Using a debug build built from today's main, I forced several tabs to be inactive including the selected tab. I then opened a different, new tab. Closing the last inactive tab (the previously selected one) did not reproduce the bug.

**Comment by MatthewTighe** [comment]
It turns out this menu option is still accessible if the user has the secret settings menu available. Given that, I am re-opening for now in case Product would like to prioritize this

**Comment by delia-pop** [comment]
@DreVla explained how in normal conditions, an user will no longer be able to have all the tabs inactive. The last accessed tab will remained active, thus the scenario I mentioned above is no longer valid, since it involved using the debug feature to manually make all tabs inactive.
Closing this as verified fixed.
