### ISSUE TITLE
Collection expand/collapse chevron not displayed from a certain length of title

### ISSUE THREAD

**Issue by SoftVision-LorandJanos** [mozilla-mobile/fenix#27974]
### Steps to reproduce

1. Create a new collection of tabs (or use the existing ones).
2. Give the newly created collection (or rename the existing one with) a name with at least 19 characters.
3. Expand and collapse the collection.
4. Rename the collection with a word with at least 30 characters.
5. Expand and collapse the collection.

https://user-images.githubusercontent.com/48829350/204004973-edce88a1-f94d-40d5-bb47-716f0c983110.mp4

### Expected behaviour

The chevron is visible.

### Actual behaviour

3. The chevron is not visible with the expanded state.
5. The chevron is not visible.

### Device name

Google Pixel 4

### Android version

Android 12

### Firefox release type

Firefox Nightly 

### Firefox version

109.0a1

### Additional information

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-22051)

Also reproducible on the latest Beta 108.0b4 and the latest RC 107.1.0 as well.

**Comment by gabrielluong** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1815634

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
