### ISSUE TITLE
Bright media notification background on dark theme 

### ISSUE THREAD

**Issue by ale82to** [mozilla-mobile/fenix#27980]
### Steps to reproduce

on Android 12 media notification (eg YouTube )picks accent color for background wich in my case is yellow and produces a very annoying bright effect on global dark theme
screenshot : https://i.imgur.com/u4xLkIr.png

### Expected behaviour

background should be #ff424242 as previous android version 

### Actual behaviour

media notification background is annoying bright

### Device name

poco f3

### Android version

Android 12

### Firefox release type

Firefox Nightly

### Firefox version

109

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-22054)

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813881

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
