### ISSUE TITLE
[Bug]: Firefox Mobile Browser on Android does not display HTML Form Validation Error Messages

### ISSUE THREAD

**Issue by lsblsb** [mozilla-mobile/fenix#27986]
### Steps to reproduce

Its easy to provide an example, since the examples on the related MDN page do also does not work on the mobile browser (error messages are not shown) - they do work on desktop though:

https://developer.mozilla.org/en-US/docs/Learn/Forms/Form_validation

There is also an example on bootstrap, that does not work on mobile regarding the validation error messages:

https://getbootstrap.com/docs/5.2/forms/validation/#browser-defaults

### Expected behaviour

If client-side form validation is implemented with HTML5 and JavaScript, errors produced by invalid inputs should be shown on the mobile browser as well. Also the mobile browser should scroll to the first error within the form.

### Actual behaviour

Although client-side form validation is supported by the current Firefox Mobile Browser on Android (in my case its version 107), no error messages are shown and neither the browser scrolls to the  first erroneous field nor is the erroneous field focused.

All these things do work without problems on the Desktop Version.

Also see description on StackOverflow: [https://stackoverflow.com/questions/74585079/firefox-mobile-browser-on-android-does-not-display-html-form-validation-errors-m](url)

### Device name

OnePlus Nord (Model: AC2003)

### Android version

Android 12

### Firefox release type

Firefox

### Firefox version

107.1.0

### Additional information

Not any JavaScript errors appear (tested via Remote-Debugging).

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-22057)

**Comment by kbrosnan** [comment]
Duplicate bz-1510450
