### ISSUE TITLE
[bug] Fennec update doesn't show homepage wallpapers anymore

### ISSUE THREAD

**Issue by TheRealOne78** [mozilla-mobile/fenix#27987]
### Steps to reproduce

1. Update Fennec Fdroid to latest version (107.1.0)
2. Open up
3. Skip the update feature setup (A page with "what's new in firefox mobile", I can't remember the exact content since it displays one time)
4. See a blank wallpaper:
![Screenshot_20221127-132544_Fennec](https://user-images.githubusercontent.com/53640879/204132991-36c38805-de53-4ecb-afed-ea6741cbefcb.png)
5. Go to settings > Homepage > Wallpapers and notice there is only one option "Classic Fennec" wallpaper:
![Screenshot_20221127-132517_Fennec](https://user-images.githubusercontent.com/53640879/204133044-ea9f7f06-6883-4bd0-a5e2-5b0841a68ea8.png)

### Expected behaviour

I don't exactly know whether
a) the entire wallpapers menu is to be intentionally removed and the code for wallpapers menu was accidentally not entirely removed or
b) the wallpapers options were accidentally removed

If b), the menu should have 4 wallpapers including this one:
![Screenshot_20221126-174749_Fennec](https://user-images.githubusercontent.com/53640879/204133307-67552fd0-c36a-491d-af39-cd4447f322d9.png)

### Actual behaviour

There is only 1 default blank wallpaper called "Fennec classic":
![Screenshot_20221127-132517_Fennec](https://user-images.githubusercontent.com/53640879/204133364-6b5f615c-2b6d-4e66-a4be-1794ed7bc6cf.png)
![Screenshot_20221127-132544_Fennec](https://user-images.githubusercontent.com/53640879/204133366-25c81ade-f869-4cf7-a5f5-a0207bee16f3.png)

### Device name

SM A42 5G

### Android version

11

### Firefox release type

Firefox

### Firefox version

107.1.0

### Device logs

No logged crashes

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-22058)

**Comment by kbrosnan** [comment]
Fennec is not supported by Mozilla report this to the F-droid maintainers.
