### ISSUE TITLE
[Bug]: Accessibility: incorrect element activated while using magnification

### ISSUE THREAD

**Issue by davidbtc2009** [mozilla-mobile/fenix#27988]
### Steps to reproduce

Enable magnification gestures in android settings > accessibility > Magnification shortcut swipe up with 2 fingers

Open firefox

Go to a website

2 finger swipe up from the home bar and a green outline will appear along the border of the display

Tap with 1 finger to enable zoom

Swipe around with 2_fingers until an element (link, button, etc) you wish to click is in focus

Tap the desired element with 1 finger

### Expected behaviour

The element that was tapped should be activated

### Actual behaviour

A random element way down the page is activated instead of the desired one

### Device name

Motorola One 5G Ace

### Android version

Android 11

### Firefox release type

Firefox

### Firefox version

107.1.0

### Additional information

See old issue #25454

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-22059)

**Comment by kbrosnan** [comment]
duplicate https://github.com/mozilla-mobile/fenix/issues/25454

**Comment by davidbtc2009** [comment]
Uh yeah its a duplicate. Your system told me to reopen it as a new issue because of some new years reorg. So im doing what i was told
