### ISSUE TITLE
[Bug]:  Touches are not handled properly

### ISSUE THREAD

**Issue by aashishdamrait** [mozilla-mobile/fenix#27995]
### Steps to reproduce

1. Goto any website that has expandable menu either on left or right top corner. Like github.com
2. Tap 3 lines on top right side of screen.

https://user-images.githubusercontent.com/24826393/204227261-b80d0175-6400-451b-b02d-00787a1aced7.mp4

### Expected behaviour

Should open menu

### Actual behaviour

Sometimes open and sometimes don’t.
on further inspection using pointer location found out that touch is behaving weird, only works when it is touched on left side of the icon. Doesn’t work if touched on or on right side of icon

### Device name

Realme X2 Pro (RMX1931)

### Android version

Android 11

### Firefox release type

Firefox Nightly

### Firefox version

109.0a1 (all Firefox release types : Stable, Beta, Nightly, Focus)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-22061)

**Comment by kbrosnan** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1802848

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Comment by cpeterso** [comment]
@aashishdamrait , is this bug a regression? Did github.com menus work for you before Firefox Nightly 109.0a1?

We're tracking your bug in Bugzilla here: https://bugzilla.mozilla.org/show_bug.cgi?id=1802848
