### ISSUE TITLE
[Bug]: The video stream does not rotate with device of Android 13

### ISSUE THREAD

**Issue by Aux-lyk** [mozilla-mobile/fenix#27994]
### Steps to reproduce

- Create a video stream from the phone camera through getUserMedia and set the stream to the video tag
- Rotate the phone to the landscape screen

### Expected behaviour

Video stream is the size of landscape screen

### Actual behaviour

Video stream is still the size of portrait screen

### Device name

Google Pixel 6 Pro

### Android version

Android 13

### Firefox release type

Firefox

### Firefox version

96.1.0、105.1.0、107.1.0

### Device logs

There is nothing relevant (only my own logs) in Firefox console

### Additional information

We test some versions of Firefox (107.1.0, 105.1.0, 104.2.0, 96.1.0, 89.1.1) on Pixel 6 Pro Android13 and Pixel 6 Pro Android12. This issue will appear on these versions of Firefox on Android13, but Android12 is OK.

demo website: https://tommygaessler.com/vsdktest/
Enter `Your Name` and `Session Name` at will

Simple core code example:
<img width="637" alt="image" src="https://user-images.githubusercontent.com/35951115/204179859-b49cfd50-7b88-4dc8-ae11-12be80d74a5b.png">

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-22060)

**Comment by kbrosnan** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1802849

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Comment by tommygaessler** [comment]
Thanks for reporting @Aux-lyk , and thanks for taking a look @kbrosnan . 👍
