### ISSUE TITLE
[Bug]: The search engine selector should have a 4px padding top and left

### ISSUE THREAD

**Issue by DreVla** [mozilla-mobile/fenix#27998]
### Steps to reproduce

1. Open search selector menu from home fragment or search dialog
2. Check menu padding

### Expected behaviour

The menu should have 4dp padding left and bottom/top (depending on toolbar position)
![searchselectorexpected](https://user-images.githubusercontent.com/32488956/204260843-d77a5edf-a8d2-49b0-b0c6-6788bd453655.png)

### Actual behaviour

The menu is not placed correctly
In `SearchDialogFragment`
![searchselectorcurrent](https://user-images.githubusercontent.com/32488956/204260926-5a1f0f7d-df74-438d-b250-d25cfc8bda2c.png)

In `HomeFragment`
![Screenshot 2022-11-28 at 11 34 50](https://user-images.githubusercontent.com/32488956/204261718-39e3fed9-95e4-400c-a086-8e751254574c.png)

### Android version

11

### Firefox release type

Firefox Nightly

### Firefox version

109.0a1

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-22064)

**Comment by DreVla** [comment]
I have worked on this task for a while. During this time I realized there are multiple issues that make fixing this more difficult than it seems. There are four cases here:

When opened from `HomeFragment`

When toolbar at bottom
![image](https://user-images.githubusercontent.com/32488956/207808816-360ab58f-0a1f-4090-a947-387f1a57fdb2.png)

When toolbar at top
![image](https://user-images.githubusercontent.com/32488956/207808859-96531be8-b66c-4f31-b0f3-2b4f8428a675.png)

When opened from `SearchDialogFragment`

When toolbar at bottom
![image](https://user-images.githubusercontent.com/32488956/207808890-8068e96b-6514-4ec7-83c9-9b09de680266.png)

When toolbar at top

![image](https://user-images.githubusercontent.com/32488956/207808929-32ea1cac-4d8a-4274-a4aa-64721860a342.png)


After testing each of these, I noticed none of them had the right alignment, but case 2a was the closest. 

I supposed there was a problem witht the offsets. The menu that pops up is an element from Android Components, `PopupWindow`. It is displayed depending on orientation and screen space using two methods from android `showAsDropDown` and `showAtLocation` that can receive x and y offsets as parameters. It seemed nothing was wrong here.

After asking for help from Petru, he suggested we check the anchor for the menu. There are two views that act as anchors, identified by "@+id/search_selector”". We tried changing the anchor to the parent, which led to an improvement but not the expected result, therefore we figured that creating a new anchor and positioning it where we want would solve the issue. 

It did fix the problem, but only in case 1a:

![image](https://user-images.githubusercontent.com/32488956/207808960-2353f39e-0a67-4248-9b88-c3bb836ad00d.png)


But when the toolbar is at the top, because the constraint was bottom to bottom of parent it appeared as follows:

![image](https://user-images.githubusercontent.com/32488956/207808983-fdeda6dc-c4f5-4299-b85f-beaaf7310c88.png)


A solution is to programmatically change the constraint to top to top of parent

![image](https://user-images.githubusercontent.com/32488956/207809008-afbbe289-fe0c-4708-8e12-9b0ce310238a.png)


The current solution presented in the draft is only for case 1a,b. Arguably, this is a “hacky” implementation, but after many hours of trial and error, it is the only one we have reached for now. For now this will remain as a draft and if anyone can suggest a better implementation please do. Link to PR: https://github.com/mozilla-mobile/fenix/pull/27999

**Comment by mavduevskiy** [comment]
It appears we worked on that in parallel! I worked on adding the unified search icon to the HomeFragment, but missed the spacing requirement. working with @t-p-white on the [cutting the last item in half ](https://github.com/mozilla-mobile/fenix/pull/27895) made me realize that's an issue.

After digging into it, I realized that actually the anchoring works correctly, but we are passing the wrong anchor and also the menu itself has paddings from elevation that we don't account for.

If you look at this picture closely, you will see that the bottom edge of the popup aligns perfectly with the corner of the view we are passing – [search_selector](https://searchfox.org/mozilla-mobile/source/fenix/app/src/main/res/layout/fragment_home.xml#149). It has margins, so the x coordinate is shifted to teach the start of the margin of the view. Bottom aligns with the anchor bottom.

<img width="300" alt="unified_on_old" src="https://user-images.githubusercontent.com/92760693/208382558-a76e4d0e-b38b-4cd4-ad4b-639e433951c9.jpg">

My solution was to calculate the spacing between the menu and it's container, and offset the container accordingly.

The behavior of the old menu is the same, by the way. It is aligned over the anchor completely, but spacing between the container and menu "shifts" the menu a bit, creating spacing.

Btw, achieving right position is not possible without reducing elevation by at least 1dp – 8dp is too much to have enough space at the TOP orientation. But luckily the design has [updated elevation](https://www.figma.com/file/epu0Sj6mCPk7K282sNpHgI/Site?node-id=3754%3A51117&t=dfqPDyfJ9knECBVw-4).

**Comment by Mugurell** [comment]
Thank you for the update.
It seems like we have to treat this popup as an edgecase.  I was also thinking about a new `showAtLocation` method with event support for X and Y offsets.
Is just that there are many scenarios in which the same popup for unified search is positioned a little bit differently - depending on the toolbar position (and the popup orientation), depending on where it is opened from - the homescreen or from the browser and also depending on LTR/RTL and so any solution would have to account for all of these.

**Comment by Mugurell** [comment]
Synced with Michael Verdi about the status of unified search and this issue also.
As Mike saw there are issues with RTL also and generally many edgecases that would be hard to tackle separate from the current implementation we use as default for showing the menu popups.
The patch from https://github.com/mozilla-mobile/firefox-android/pull/386 would help alleviate some issues and then Michael Verdi agreed with the proposal to wait until moving the menus to Compose to place this popup with an exact 4px padding start/bottom.

**Comment by mavduevskiy** [comment]
changed the order to keep DataSync calm and tranquil on the Jira side

**Comment by gabrielluong** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1815548

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
