### ISSUE TITLE
[Bug/Feature Request]: Show more than 8 shortcuts on homepage if there's space

### ISSUE THREAD

**Issue by eylenburg** [mozilla-mobile/fenix#27997]
### Steps to reproduce

I'm not sure if this is a bug or a feature request but I'm leaning towards bug because I don't think there's any merit in the current behaviour.

In my Homepage settings I have disabled everything except for shortcuts. On the homepage I end up with 8 shortcuts at the top of the screen followed by a big empty space where the rest (like collections or recent bookmarks) would go but which I have disabled. Interestingly there is a _second_ group of additional 8 shortcuts when you swipe towards the right on the homepage. I have 10 shortcuts pinned, with the remaining 4 generated by Firefox.

### Expected behaviour

Instead of spreading the 16 shortcuts over two pages with 8 shortcuts each, while leaving a huge empty space below the shortcuts, they should just all fit on one page of the homepage. 

### Actual behaviour

Homepage has 8 shortcuts followed by large empty space where disabled items would have been shown, and another sub-page of the homepage (need to swipe to the side to see) with additional 8 shortcuts followed by a large empty space.

### Android version

Android 13

### Firefox release type

Firefox

### Firefox version

107.1.0

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-22063)

**Comment by kbrosnan** [comment]
Duplicate https://github.com/mozilla-mobile/fenix/issues/15474
