### ISSUE TITLE
[Bug]: "Open links in app" function open new tabs

### ISSUE THREAD

**Issue by Glareascum** [mozilla-mobile/fenix#28008]
### Steps to reproduce

1. Turn on "Open link in apps" feature;
2. Open any link which point to another website (not intercepted of any apps installed)

### Expected behaviour

The new page should open on the same tab

### Actual behaviour

The new page is opened on a new tab, which causes that by pressing the back button it closes the browser.

### Device name

Poco Phone X3 NFC

### Android version

Android 12

### Firefox release type

Firefox

### Firefox version

107.1.0

### Additional information

I'm using Fennec from F-Droid

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-22070)

**Comment by kbrosnan** [comment]
Duplicate https://github.com/mozilla-mobile/fenix/issues/27909

**Comment by Glareascum** [comment]
I'm sorry but that's not the same problem
