### ISSUE TITLE
Disable TCP and the TCP CFR in Fenix 108

### ISSUE THREAD

**Issue by cpeterso** [mozilla-mobile/fenix#28004]
We had hoped to finish the TCP rollout during the 107 cycle, so shipping with TCP and the TCP CFR enabled by default in 108 (2022-12-13) would be OK. Unfortunately, our rollout has been delayed at least a couple weeks, so we can't ship by default in 108.

108 is currently in the Beta channel, so we will need to uplift the patch to disable TCP to the Beta channel. We still want TCP and the TCP CFR enabled by default in 109+. If all goes well, we can ship TCP and the TCP CFR enabled by default in 109 (2023-01-17).

We previously disabled TCP and the TCP CFR in https://github.com/mozilla-mobile/fenix/issues/27111.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-22069)

**Comment by amocirean** [comment]
Hello,

I can confirm that the TCP is disabled by default in Firefox 108.0b6. 
The TCP CFR does not appear on browsing.
Tested on Google Pixel 6 (Android 13), Samsung Galaxy S22 Ultra (Android 13), Samsung Galaxy A32 (Android 12).

Thanks!

**Comment by delia-pop** [comment]
TCP and TCP CFR are also disabled in RC 108.1.0. build1/build2. Tested with Xiaomi Redmi Note 8T (Android 9).
