### ISSUE TITLE
Closed tabs reappear again automatically

### ISSUE THREAD

**Issue by jathri** [mozilla-mobile/fenix#28011]
### Steps to reproduce

1. Close tab
2. Wait for some time (I usually notice this after few hours) 
3. Tab reappears again (even multiple times)

### Expected behaviour

Closed tab remains closed.

### Actual behaviour

See Steps to reproduce.

### Device name

mototola moto e6 plus

### Android version

9

### Firefox release type

Firefox

### Firefox version

107.1.0

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-22072)

**Comment by kbrosnan** [comment]
Are you swiping Firefox closed using the OS right after closing the tabs?

**Comment by jathri** [comment]
I do not quite understand question. Can you please rephrase?
I just tap Close tab in this menu: https://i.imgur.com/QlfJnjn.png
And tab very often reappears later.
I am not aware of any swiping or other action.

**Comment by vehosah** [comment]
> Are you swiping Firefox closed using the OS right after closing the tabs?

Can you please speak more clearly, cause we didn't get a thing of what you said?

**Comment by vehosah** [comment]
> Are you swiping Firefox closed using the OS right after closing the tabs?

No Im not swiping Firefox closed using the OS right after closing tabs lol

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813884

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
