### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by vinzgg** [mozilla-mobile/fenix#28019]
![Screenshot_2022-11-29-19-12-45-708_org mozilla firefox](https://user-images.githubusercontent.com/65109480/204595652-e039f85c-8da9-4dac-a562-755c29a273f3.jpg)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-22075)

**Comment by kbrosnan** [comment]
Nothing explaining the report.
