### ISSUE TITLE
[Bug]: Tries to open search query with dot as hostname 

### ISSUE THREAD

**Issue by LinAGKar** [mozilla-mobile/fenix#28026]
### Steps to reproduce

1. Write a word with a dot in the location bar, e.g. "example.txt"
2. Tab "search engines
3. Choose a search engine, or leave it at default 
4. Press enter

### Expected behaviour

It searches for the given query

### Actual behaviour

It takes it as a hostname and tries to connect to it

### Device name

Oneplus 8t 

### Android version

Android 12

### Firefox release type

Firefox

### Firefox version

107.1.0

**Comment by kbrosnan** [comment]
Duplicate https://github.com/mozilla-mobile/fenix/issues/10516
