### ISSUE TITLE
[Bug]: Google Bug

### ISSUE THREAD

**Issue by TheZeqna** [mozilla-mobile/fenix#28028]
### Steps to reproduce

https://user-images.githubusercontent.com/112294205/204679221-0f122e27-d98d-4011-9f62-89fbfa11ee8a.mp4

### Expected behaviour

HELLO!
I'm report this UI Visual bug from google images, you can see in the video a post the description became transparent and its so annoying! i don't know if this is a add-on bug or actual bug from Firefox, i hope this fix soon..

### Actual behaviour

UI BUG WITH GOOGLE IMAGES
![IMAGE 2](https://user-images.githubusercontent.com/112294205/204679867-6791e6cb-b034-44a0-b2cf-848d38afe54c.jpeg)
![IMAGE1](https://user-images.githubusercontent.com/112294205/204679868-28c7a2de-dbb2-4c72-bff3-5612c2370c39.jpeg)

### Device name

Samsung Galaxy S21 5G

### Android version

Android 11

### Firefox release type

Firefox

### Firefox version

107.1.0

**Comment by kbrosnan** [comment]
Duplicate bz-975444
