### ISSUE TITLE
Move where marketing notifications are being scheduled

### ISSUE THREAD

**Issue by rocketsroger** [mozilla-mobile/fenix#28023]
Currently we check and schedules the default browser notification and the re-engagement notification when resuming (`onResume`) Home activity.  This seems to be overkill.  Look into moving this to a better location.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-22078)

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813885

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
