### ISSUE TITLE
History does not remember scroll position, back to top

### ISSUE THREAD

**Issue by marcel263** [mozilla-mobile/fenix#28020]
### Steps to reproduce

1. Have browsing history, including search history, spanning several pages
2. Tap a collection of search queries indicated with the icon
3. Navigate back

### Expected behaviour

Scroll position maintained

### Actual behaviour

Always back to top

### Android version

11

### Firefox release type

Firefox Nightly

### Firefox version

109.0a1 (Build #2015918379)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-22076)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812370

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
