### ISSUE TITLE
[Bug]: Pocket stories not appearing on homescreen

### ISSUE THREAD

**Issue by onemahon** [mozilla-mobile/fenix#28032]
### Steps to reproduce

(Reproduced on v107.2.0)

1. Clear app data
2. Open app
3. Scroll down & click "start browsing"

### Expected behaviour

Homescreen should show Pocket-provided "Thought provoking stories"
<img src="https://user-images.githubusercontent.com/1128945/204857422-ff8d3691-ec92-4b40-9049-a74c6100eeed.jpg" width="200" />

### Actual behaviour

Pocket stories are absent.
<img src="https://user-images.githubusercontent.com/1128945/204857265-f0471799-7061-40b4-b223-64800cca5309.jpg" width="200" />

### Device name

Samsung A51

### Android version

12

### Firefox release type

Firefox

### Firefox version

107.2.0

### Additional information

When I updated to v107.2.0 (from v105; this was on a test device I rarely use), the Pocket stories WERE there. It was only after clearing data and going through the initial onboarding that they disappeared. So I'm _guessing_ existing users' aren't affected, whereas new users are; though I didn't test that extensively.

Given the difference in versions that I tested, this regression may have appeared in v106, v107.1.0, or v107.2.0.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-22109)

**Comment by AndiAJ** [comment]
Reproducible on latest Nightly 109 12/7 using a Google Pixel 3a (Android 11) 

► Video 

https://user-images.githubusercontent.com/51314259/206120058-c06ce196-e508-4f52-82db-cff61e428c5b.mp4

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1809811

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
