### ISSUE TITLE
Having hundreds of inactive tabs causes severe lag when expanded.

### ISSUE THREAD

**Issue by Coffee-Toffee** [mozilla-mobile/fenix#28030]
## Steps to reproduce
Have hundreds of tabs open, which are inactive.
Expand inactive tabs.

### Expected behavior
The user is able to smoothly scroll through the inactive tabs

### Actual behavior
The app crawls to a halt, and the app not responding pop up shows.

### Device information
Google pixel 6

* Android device: Google pixel 6, Android 13, Verizon
* Fenix version: 107.1.0 (Build #2015915067)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-22116)

**Comment by MarcLeclair** [comment]
@Coffee-Toffee  could you grab a profile for us. It would be really helpful to help us understand the issue at hand. [Here's the link as to how to take the profile and share it.](https://profiler.firefox.com/docs/#/./guide-profiling-android-directly-on-device) 

Also,  is it possible for you to share with us the number of inactive tabs that you had. As well as the version of firefox that you have running and the phone that you have?

Thank you!

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807355

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
