### ISSUE TITLE
[webcontent]: codingnepalweb.com

### ISSUE THREAD

**Issue by iSmokeMid69** [mozilla-mobile/fenix#28031]
## Site with issue and any steps to reproduce
https://www.codingnepalweb.com/how-to-take-screenshot-vanilla-javascript/

Try To Copy The Code With Ublock/Adguard Active In FireFox Android Nightly Then Anti AdBlock Gets Triggered But Not With Desktop Mode Or With FireFox Beta,Legacy
### Expected behavior
Anti AdBlock Shouldn't Trigger
### Actual behavior
But It Gets Triggered 
### Does toggling Tracking Protection fix the issue? (Press the shield icon in the toolbar while on the site to see toggle)
No
### Device information
Poco X3 Pro
* Android device: A11
* Fenix version: 109.0a1

**Comment by kbrosnan** [comment]
This is not a Fenix bug.
