### ISSUE TITLE
VERİMLİLİK⚠️

### ISSUE THREAD

**Issue by mtsyns** [mozilla-mobile/fenix#28041]
BİZ KULLANICILARIN GERİ BİLDİRİM ve HATA AYIKLAMA ÇIKTISI GÖNDEREBİLMEMİZİ KOLAYLAŞTIRILMALISINIZ! 
EN ÖNEMLİSİ BU❗❗❗ KULLANICILAR, UYGULAMA İÇİNDEN BUNU YAPABİLMELİ⚠️ DİĞER UYGULAMA GELİŞTİRİCİLERİN YAPTIĞI GİBİ ”AYARLAR/GERİ BİLDİRİM OLUŞTUR” YOLU OLMALI! HEM SİZLER HEM BİZ KULLANICILAR İÇİN BÜYÜK KOLAYLIK OLACAKTIR! 
DEĞİLSE, FORUMA GİT, ÜYE OL, FORUMU ÖĞREN, İNGİLİZCE BİL, vesaire vesaire... Sıradan Kullanıcı için çok çok çok ... uzun iş... EPEY ZAMAN ALAN, ŞU KADAR YAZDIĞIM ŞEY YERİNE , ÖNÜNÜZDE, 1-2 HAMLEDE GÖNDERİLMİŞ HATA AYIKLAMA ÇIKTISI İÇEREN BİR GERİ BİLDİRİM VERİSİ OLSA, DAHA ÇOK İŞİNİZE YARARDI SANIRIM❗
ŞİMDİDEN TEŞEKKÜR EDER, İYİ GÜNLER VE İYİ ÇALIŞMALAR DİLERİM. 
SEVGİ VE SAYGILARIMLA...🥰

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-22082)

**Comment by kbrosnan** [comment]
We collect ideas about how to improve Firefox at https://connect.mozilla.org/.
