### ISSUE TITLE
[webcontent]

### ISSUE THREAD

**Issue by fatihsonmez** [mozilla-mobile/fenix#28040]
### Device information
xiaomi mi note 3
android 9

* Android device: 9 pkq1.181007.001
* Fenix version: 
107.1.0 (Build #2015915067), a4c625827+
AC: 107.0.7, 7d69de3da4
GV: 107.0-20221110173214
AS: 94.2.2

**Comment by kbrosnan** [comment]
Duplicate https://github.com/mozilla-mobile/fenix/issues/28028
