### ISSUE TITLE
[Telemetry] increase lifetime of customize_home.contile & send in an existing custom ping

### ISSUE THREAD

**Issue by perrymcmanis144** [mozilla-mobile/fenix#28042]
## Description & Product Manager / Data Scientist User Story
This data is currently on the default lifetime (ping) & as such does not work well for analysis, where it should be present on every metrics ping (lifetime: application).

This also sends it in the  ```topsites-impression``` custom ping, where the other data is sent

## What questions will you answer with this data?

Answers around sponsored tiles; this is an important metric for understanding. 

There is significant context in the office hours where this was discussed: https://docs.google.com/document/d/1FFabfi10og2P8esGrnp1mjJ4z_LbYZWhoZzTrKjgGdw/edit?usp=sharing

For acceptance; no new telemetry will be sent, instead existing data will be sent with a greater lifetime.

## Acceptance Criteria
- [ ] ENG files a [DS JIRA](https://jira.mozilla.com/projects/DO/issues/DO-228?filter=allopenissues) request outlining their methodology.
- [ ] DS sign off on instrumentation methodology addressing product questions.
- [ ] Event pings can be queried via re:dash
- [ ] Event pings can be queried via amplitude
- [ ] We are sending telemetry events for the actions listed in the requirements
- [ ] We have documented the telemetry
- [ ] We have asked a data steward to [review](https://github.com/mozilla/data-review/blob/master/request.md) the telemetry

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-22098)

**Comment by AdinaPetridean** [comment]
Verified as fixed on Nightly 109.0a1 from 12/07 with Xperia 10 (Android 12).

The first generated custom ping:

2022-12-07 14:53:06.709 15990-17441/? I/libglean_ffi: glean_core::upload: Glean ping to URL: /submit/org-mozilla-fenix/topsites-impression/1/72d98c65-865c-4cf4-9b17-385959c0d1ea
    {
      "ping_info": {
        "seq": 6,
        "start_time": "2022-12-13T14:35+02:00",
        "end_time": "2022-12-07T14:53+02:00"
      },
      "client_info": {
        "telemetry_sdk_build": "51.8.2",
        "device_model": "XQ-BT52",
        "locale": "en-GB",
        "architecture": "arm64-v8a",
        "app_build": "2015920111",
        "os_version": "12",
        "app_channel": "nightly",
        "android_sdk_version": "31",
        "app_display_version": "109.0a1",
        "os": "Android",
        "device_manufacturer": "Sony",
        "build_date": "2022-12-07T05:19:11+00:00",
        "first_run_date": "2022-12-13+02:00"
      },
      "metrics": {
        "boolean": {
          "customize_home.contile": true
        },
        "url": {
          "top_sites.contile_reporting_url": "https://imp.mt48.net/static?id=7RHzfOIXjFEYsBdvIpkX4QxW4plYfZlW4pbW1CbWfpbW7ReNxR3UIG8zInwYIFIVs9eYiGINHrwuJm7vJ%3DEkiFXwxYIZjF8XgClWfCDa7R4dHQ8zJnErj%3DcO7R4dHQfz4Z2ZfplnHG3Z5FwqgCfX1pDX4pbrfYINI9HuiF2z4Z2ZfplnHmcux%3DcvImauiF2zfQlWfpDX7ncqIr7VjGbuiF2zfCfk4Qxr4Qxnj9wWIBdvIpkY7n4YIFckiGIw5FwqgCLYfBIWJ%3DcQIFdwJR2uiF2zfCb%2B12yy"
        },
        "uuid": {
          "top_sites.context_id": "1c1cfdea-3b5e-4e6c-8625-4d441b9e13b7"
        },
        "string": {
          "top_sites.contile_advertiser": "amazon"
        },
        "quantity": {
          "top_sites.contile_tile_id": 74301
        }
      },
      "events": [
        {
          "timestamp": 0,
          "category": "top_sites",
          "name": "contile_impression",
          "extra": {
            "position": "2",
            "source": "newtab"
          }
        }
      ]
    }

The second generated custom ping:

2022-12-07 14:53:06.930 15990-17441/? I/libglean_ffi: glean_core::upload: Glean ping to URL: /submit/org-mozilla-fenix/topsites-impression/1/747e5409-16f7-4a8e-a4f9-6819f3da62d9
    {
      "ping_info": {
        "seq": 7,
        "start_time": "2022-12-07T14:53+02:00",
        "end_time": "2022-12-07T14:53+02:00"
      },
      "client_info": {
        "telemetry_sdk_build": "51.8.2",
        "os_version": "12",
        "first_run_date": "2022-12-13+02:00",
        "build_date": "2022-12-07T05:19:11+00:00",
        "app_channel": "nightly",
        "device_model": "XQ-BT52",
        "architecture": "arm64-v8a",
        "device_manufacturer": "Sony",
        "android_sdk_version": "31",
        "app_build": "2015920111",
        "locale": "en-GB",
        "app_display_version": "109.0a1",
        "os": "Android"
      },
      "metrics": {
        "string": {
          "top_sites.contile_advertiser": "michael kors"
        },
        "quantity": {
          "top_sites.contile_tile_id": 73804
        },
        "uuid": {
          "top_sites.context_id": "1c1cfdea-3b5e-4e6c-8625-4d441b9e13b7"
        },
        "boolean": {
          "customize_home.contile": true
        },
        "url": {
          "top_sites.contile_reporting_url": "https://imp.mt48.net/static?id=7RHzfOIXjFEYsBdvIpkX4QxW4plYfZlW4pbW1CbWfpbW7ReNxR3UIG8zInwYIFIVs9eYiGINHrwuJm7vJ%3DEkiFXwxYIZjF8XgClWfCDa7R4dHQ8zJnErj%3DcO7R4dHQfz4Zfafp2nHG3Z5FwqgCfX1pDX4pbrfYINI9HuiF2z4Zfafp2nHmcux%3DcvImauiF2zfQl%2B4Zla7ncqIr7VjGbuiF2zfCDkfCxZ1Clnj9wWIBdvIpkY7n4YIFckiGIw5FwqgCLYfYIWJ%3DcQIFdwJR2uiF2zfCb%2B12yy"
        }
      },
      "events": [
        {
          "timestamp": 0,
          "category": "top_sites",
          "name": "contile_impression",
          "extra": {
            "position": "3",
            "source": "newtab"
          }
        }
      ]
    }

**Comment by AdinaPetridean** [comment]
Also verified implemented on Beta 109.0b1 with Xperia 10 (Android 12).
