### ISSUE TITLE
images do not render in Firefox Mobile

### ISSUE THREAD

**Issue by sgri** [mozilla-mobile/fenix#28064]
Open this web site, https://thewatch.ua/shop/category/g_shock/filter/tip-muzhskie/ 
That is a web shop for wrist watches. 
Expected result: Every item on the list shows an image.
Actual result: images are not shown in Firefox,  however,  Google Chrome shows images properly.

Environment: Samsung Galaxy A71, Android version 12,  latest version of Forefox.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-22085)

**Comment by kbrosnan** [comment]
Works for me with Firefox 106 to 109.0a1. Do you have any extensions running? Try disabling them.

**Comment by sgri** [comment]
I can't reproduce this issue anymore.
