### ISSUE TITLE
Add scrollbar above certain page length

### ISSUE THREAD

**Issue by superbonaci** [mozilla-mobile/fenix#28068]
When browsing certain sites on mobile, they are quite large (like 100 pages mobile-equivalent) and can take quite some time to browse through. So my request, is to enlarge the scroll bar rectangle for a couple of seconds after dragging, then let it be so I can pinch it and move up and down for fast scrolling.

Currently the bar appears but can't be dragged. Example on this page browsing from mobile. The desired scroll bar in surrounded in red:
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/10916

![](https://i.imgur.com/0TcHB3r.jpg)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-22091)

**Comment by superbonaci** [comment]
Follow-up from https://github.com/mozilla-mobile/fenix/issues/23027

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813896

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
