### ISSUE TITLE
[Bug]: Problem Compiling fenix from github

### ISSUE THREAD

**Issue by ale82to** [mozilla-mobile/fenix#28061]
### Steps to reproduce

for over a year i m compiling fenix from github among the modification i apply ,i used to add extension(s) to the browser toolbar modifing BrowserFrgament.kt  by adding   :
1)import mozilla.components.feature.toolbar.WebExtensionToolbarFeature
and 
2)webExtToolbarFeature.set(
	            feature = WebExtensionToolbarFeature(
	                toolbar,
	                requireContext().components.core.store
	            ),
	            owner = this,
	            view = view
	        )
to the file ,staring from today (4 december ) even if fenix nighlty compile fine i cannot have extensions in the toolbar like before
Is it a bug or more probably i m doing something wrong after some code changes?

### Expected behaviour

fenix compiles fine with my modifications but extensions wont show up in the toolbar

### Actual behaviour

i should be able to add extension to the toolbar since fenix compiles just fine

### Android version

Android 12

### Firefox release type

Firefox Nightly

### Firefox version

109

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-22084)

**Comment by boek** [comment]
Hey @ale82to, none of the changes to the toolbar immediately jump out to me. You might have better luck [reaching out on Matrix ](https://chat.mozilla.org/#/room/#fenix:mozilla.org) :).

I'm not going to migrate this to Bugzilla as it is not a bug with Fenix but a question.
