### ISSUE TITLE
[Bug]: Popup player in certain sites appear along with bottom toolbar

### ISSUE THREAD

**Issue by S-Sajith** [mozilla-mobile/fenix#28067]
### Steps to reproduce

1.Open this video from this site https://www.dailymotion.com/video/x6irq7u?playlist=x5r0fc
2.Go to full screen mode
3.Go to homecreen of the phone
4.Popup player appears

### Expected behaviour

The popup player should appear normally without any toolbar which it does for every other site except dailymotion

### Actual behaviour

When popup player is opened in dailymotion site , toolbar appears along with the popup player.
![Screenshot_20221205-131013](https://user-images.githubusercontent.com/88919814/205580576-c9548b34-50b5-4564-b2ac-5a5e5e5dc442.png)

### Device name

Motorola Edge 20 Fusion

### Android version

12

### Firefox release type

Firefox Beta

### Firefox version

108.0b6 (Build #2015919115)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-22088)

**Comment by AdinaPetridean** [comment]
@S-Sajith thank you for your report! I was able to reproduce this issue on Firefox Nightly 109.0a1- 12/08 with Xperia 10 (Android 12).

**Comment by jonalmeida** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813761

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
