### ISSUE TITLE
.mp4 Download failed

### ISSUE THREAD

**Issue by Rrsus** [mozilla-mobile/fenix#28066]
### Steps to reproduce

1. Go to https://gogohd.net/download?id=MTk1NTc1 
2. Click on "DOWNLOAD 1080P - MP4" under "Link download" with Firefox android internal download manager

### Expected behaviour

The download should start within a sec

### Actual behaviour

Download does not start and says ".mp4 Download failed Try again". Trying again gives the same result

### Device name

POCO F1

### Android version

Android 10

### Firefox release type

Firefox

### Firefox version

107.2.0

### Additional information

![Screenshot_2022-12-05-07-21-10-488_org mozilla firefox](https://user-images.githubusercontent.com/119804650/205534306-b005ef51-5536-4023-800e-f1d7095af6df.jpg)
![Screenshot_2022-12-05-07-21-20-849_org mozilla firefox](https://user-images.githubusercontent.com/119804650/205534315-153bd91d-be8c-4718-9e2d-08be35f7a599.jpg)
![Screenshot_2022-12-05-07-21-27-065_org mozilla firefox](https://user-images.githubusercontent.com/119804650/205534329-573637d8-fec1-4540-8c6a-0f473e9a746d.jpg)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-22087)

**Comment by AdinaPetridean** [comment]
Hi @Rrsus  Thanks for your report!
I couldn't reproduce your issue on Firefox 107.2.0 nor the latest Nightly 109.0a1 from 08/12. Can you please verify if there is enough free space on your mobile device? 
Please also see if you still reproduce the issue with the latest Nightly build. Thank you!

**Comment by Rrsus** [comment]
Hello @AdinaPetridean 
> Can you please verify if there is enough free space on your mobile device?

Yes, I have more than 20 GB free space available

> Please also see if you still reproduce the issue with the latest Nightly build.

Just checked in the latest Firefox Nightly app, I found the same issue there too 
![IMG_20221208_183559](https://user-images.githubusercontent.com/119804650/206454113-c940096b-04c4-430b-b668-8de86596fb81.jpg)

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813894

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
