### ISSUE TITLE
FNX3-16593 ⁃ [Bug] Pressing Back on SearchFragment exits the app

### ISSUE THREAD

**Issue by ekager** [mozilla-mobile/fenix#2806]
## Steps to reproduce
1. Click on search from home
1. Press back 

### Expected behavior
Go to home 

### Actual behavior
Get kicked from app

### Device information
* Android device: ?
* Fenix version: ?

From my brief investigation I think this AC change is causing this because we then are calling activity.onBackPressed twice. I'm not sure why we do this at all so we should investigate if we can change the behavior. 
https://github.com/mozilla-mobile/android-components/pull/3067

**Comment by AndiAJ** [comment]
Hi, verified as fixed on the latest Fenix build (#11790617 from 28/6) using the following devices:

• Google Pixel 3XL (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7.0)
• Samsung Galaxy J7 (Android 6.0.1)
• Sony Xperia Z3 (Android 5.1.1)
