### ISSUE TITLE
search bar for download folder on mobile

### ISSUE THREAD

**Issue by marinee-b** [mozilla-mobile/fenix#28072]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### What is the user problem or growth opportunity you want to see solved?
Too many files in the download folder, and you want to find what you are looking for quickly on mobile.

### How do you know that this problem exists today? Why is this important?
I met with a Firefox Android user that wanted to show me something he had downloaded, and it took too long to find the file, so he gave to look for it.

### Who will benefit from it?
All users who want to search for a specific file in their download folder

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-22093)

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813897

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
