### ISSUE TITLE
[Bug]Loading about:config doesn't work

### ISSUE THREAD

**Issue by nojunpark** [mozilla-mobile/fenix#2807]
## Steps to reproduce
Open about:config,

### Expected behavior
Opens config page

### Actual behavior
shows blank page

### Device information
* Android device: Moto G5
* Fenix version: Tip of the master, 763c8be8150ff9c7585a7dfd3f096eebce58b246

It's a recurrence of  #1224

**Comment by Lululalu** [comment]
The same as #2778

**Comment by jonalmeida** [comment]
This was working for me on yesterday's nightly - I _just_ updated to the one from today and it no longer works.

@npark-mozilla did you manager to solve this (which is why you closed the issue?)

**Comment by npark-mozilla** [comment]
@jonalmeida no- I closed it because it's a dupe of #2778 as above
