### ISSUE TITLE
Implement the `formdata` event: Android

### ISSUE THREAD

**Issue by Blue3957** [mozilla-mobile/fenix#28074]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### What is the user problem or growth opportunity you want to see solved?
The [formdata](https://html.spec.whatwg.org/multipage/indices.html#event-formdata) event, as described in the HTML spec, should be fired when a form element is constructing the entry list.

### How do you know that this problem exists today? Why is this important?
According to [MDN](https://developer.mozilla.org/en-US/docs/Web/API/HTMLFormElement/formdata_event#browser_compatibility), the event isn't currently supported.

### Who will benefit from it?
A handful of developpers worldwide would probably love the opportunity to use this very niche but neat form event, either for validation purposes or to append data to a form on submit via javascript.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-22096)

**Comment by kbrosnan** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1804144

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
