### ISSUE TITLE
www.google.*

### ISSUE THREAD

**Issue by AroKol78** [mozilla-mobile/fenix#28076]
fenix 107.2.0
- the hamburger/tools menu `google` is not working properly on the pages `https://www.google.pl/` `https://www.google.com/`
- no dark theme on the pages `https://www.google.pl/` `https://www.google.com/`
- no favicon on `https://www.google.pl/` and on most websites

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-22099)

**Comment by amedyne** [comment]
Hi @AroKol78 Can you provide what device and what Android OS you have? Thanks!

**Comment by AroKol78** [comment]
> Can you provide what device and what Android OS you have?

think it doesn't matter much see: #24084 , #24083

**Comment by kbrosnan** [comment]
Google does not provide a dark theme for Chrome when the dark theme is set. Looks like requesting desktop site may provide dark mode.
