### ISSUE TITLE
links from google searches die

### ISSUE THREAD

**Issue by nickenzi** [mozilla-mobile/fenix#28085]
Do a Google search through the bar. Results come back. Click on a link and 70% of the time it works. The other 30% the progress bar just chugs until it dies multiple minutes later. Click on the link again and the site resolves.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-22101)

**Comment by amocirean** [comment]
Hello @nickenzi,
Please provide us some more details about your problem. We would need the following:
- Reproduction Steps (try to be more specific about the process)
- Device Model
- Android Version
Thanks!

**Comment by nickenzi** [comment]
Hi there,

Device is a OnePlus 8T, Android (OxygenOS) 12 with October 5, 2022 security update.

The bug is not 100% reproducible; it's intermittent but here's what I do to make it happen when it happens:

Open Firefox.
Search something on Google through the address bar.
Click on a result. 
The progress bar will sit at about 25% for a couple minutes and then disappear.
Click on the result again and the site loads.

I've tried things like cancelling the page load and closing all tabs and trying again but the bug seems to persist until it has at least one "full term" page load failure.

**Comment by amocirean** [comment]
Hello, 
I was not able to reproduce the issue on the latest Nightly (110.0a1). Tried around 10-15 times and nothing went wrong. Could you please tell me if the issue is still reproducible on the latest Firefox Nightly on your device?
Device used for testing: Google Pixel 6 (Android 13)
Thanks!

**Comment by boek** [comment]
Going to close as we were not able to reproduce. Please re-file on Bugzilla if you're still encountering the bug!
