### ISSUE TITLE
Firefox Freezes on Pixel 6a plus subsequent reboot

### ISSUE THREAD

**Issue by Mushoz** [mozilla-mobile/fenix#28086]
### Steps to reproduce

1. The issue itself manifests entirely randomly. It can happen while scrolling any page. I have not found a reliable way to trigger the issue.

### Expected behaviour

1. The page should remain scrollable.

### Actual behaviour

1. The page completely freezes, including any part of Firefox's UI. This will remain in a frozen state for quite a while, until I get Android's "Firefox has stopped responding" message. Eventually, the phone would hard reboot.

### Device name

Pixel 6a

### Android version

Android 13

### Firefox release type

Firefox

### Firefox version

107.2.0

### Device logs

I am unable to find the crash log within Firefox's settings. Furthermore, since I am unable to reliably reproduce the issue, I cannot create an ADB logcat. However, the issue seems to be affecting multiple people as can be seen in this Reddit topic with multiple recent posts as well: https://www.reddit.com/r/GooglePixel/comments/x56byt/any_pixel_6a_user_with_firefox/

### Additional information

I was unable to copy/paste these logs, and before I could make more screenshots the phone would reboot. I am hoping these screenshots are helpful. If not, please let me know how I can obtain more relevant information taking into account that I cannot reliably reproduce the issue and that the phone will reboot quite soon after this bug, leaving me with little time to get anything worthwhile.
![Screenshot_20221206-070341](https://user-images.githubusercontent.com/18422243/205879518-77a4cb50-7a67-43fc-bc36-2ebc37ccb036.png)
![Screenshot_20221206-070349](https://user-images.githubusercontent.com/18422243/205879527-7dd6e27d-3842-49a5-b05c-b7d23976f412.png)
![Screenshot_20221206-070406](https://user-images.githubusercontent.com/18422243/205879536-635b34d0-f151-4cee-98ea-ab02870cae8e.png)
![Screenshot_20221206-070435](https://user-images.githubusercontent.com/18422243/205879542-c111ec7d-b47b-499e-ab94-a4440ac728ba.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-22102)

**Comment by julescubtree** [comment]
I'm experiencing this as well, and would like to help debug however I can.

**Comment by kbrosnan** [comment]
Capturing a performance profile might be useful here. Using the networking or graphics sections. Directions at https://profiler.firefox.com/docs/#/./guide-profiling-firefox-android and the main profiler site is https://profiler.firefox.com/

**Comment by breslowday** [comment]
Also experiencing this issue. Scrolling briefly and quickly then touching the URL bar causes this.

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813899

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
