### ISSUE TITLE
Support Material 3.

### ISSUE THREAD

**Issue by rokejulianlockhart** [mozilla-mobile/fenix#28091]
### What is the user problem or growth opportunity you want to see solved?
I want the appearance (especially the colouration) of Fenix/Firefox Mobile to adhere adaptively and automatically to what the OS that it is invoked by specifies. Consequently, please support Android 12, 12L, and 13s' Material 3.

### How do you know that this problem exists today? Why is this important?
This is important for mere visual consistency and consequent ease of usability for most people, but for many, it supports accessibility, and [for OLED devices, the ability that it would gain to present #000000 backgrounds would provide significant improvement (reduction) to usage of power by Fenix](https://github.com/mozilla-mobile/fenix/issues/1938).

### Who will benefit from it?
Everyone, because implementation of this would not prevent Android versions before 12 using it.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-22104)

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813900

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
