### ISSUE TITLE
[Bug] Saving images from Google Images downloads an image.bin file

### ISSUE THREAD

**Issue by Lululalu** [mozilla-mobile/fenix#2809]
## Steps to reproduce
Search something on google.com
Touch "images" 
Touch an image
Long press the image
Select save image on the context menu

### Expected behavior
Fenix downloads the image with its actual name and file extension 

### Actual behavior
Fenix download an images.bin file

### Device information
* Android device: Galaxy A5 2017 8.0 
* Fenix version: 1.0.1921

**Comment by antonholmberg** [comment]
Same for me. The same happens on images downloaded from twitter. Interestingly enough, the same thing happen for me on focus 8.0.9 so this seems like a deeper issue than just a Fenix issue.

**Comment by ekager** [comment]
Thanks! Opened https://github.com/mozilla-mobile/android-components/issues/3516 in AC

**Comment by NotWoods** [comment]
Blocked by #1657

I landed a fix for this bug but it requires switching to the new Gecko DownloadManager.
