### ISSUE TITLE
[Bug]: The qr scanner button is shown just for the default search engine even if that is a topic specific one

### ISSUE THREAD

**Issue by DreVla** [mozilla-mobile/fenix#28090]
### Steps to reproduce

1. Have Unified Search on
2. Tap on search toolbar
3. Change search engine to any general or custom one except default (bing, duckduckgo, etc...)
4. Check if QR button is displayed

https://user-images.githubusercontent.com/32488956/205941160-8458fa7d-eed8-4f78-9cde-4d3180b60d19.mp4

### Expected behaviour

The qr scanner button should be shown for all general search engines (incl. custom ones added by the user) and should be hidden for topic specific search engines like amazon, ebay, wikipedia, etc.

### Actual behaviour

The qr scanner button is shown only for the default search engine - when using the new unified search feature.

### Android version

Android 10

### Firefox release type

Firefox Nightly

### Firefox version

109.0a1

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-22103)

**Comment by Mugurell** [comment]
Just a test

**Comment by AdinaPetridean** [comment]
Verified as fixed on Nightly 110.0a1 from 12/19 with Motorola Moto G9 plus (Android 11). The qr scanner button is shown for all general search engines (incl. custom ones added by the user) and is hidden for topic specific search engines like amazon, ebay, wikipedia.

https://user-images.githubusercontent.com/108326843/208450600-192b4da2-f3cc-4795-a6bd-bb7de3a535d1.mp4
