### ISSUE TITLE
Save as PDF text is missing in Private Mode when saving current tab as PDF

### ISSUE THREAD

**Issue by shtstorm** [mozilla-mobile/fenix#28106]
### Steps to reproduce

1. Open any site in a new Private tab
2. Touch three vertical dots, and then Share icon
3. A list of actions and apps to share the page with appears

### Expected behaviour

Below the action list at the bottom of the screen **Share as PDF** text should be shown.

### Actual behaviour

Below the action list at the bottom of the screen only white space is shown. **Save as PDF** text is missing.

![Screenshot_20221206-223834](https://user-images.githubusercontent.com/79124442/206092481-90f7f155-e980-46cd-9424-1a84cef6c874.png)

### Device name

LG V30

### Android version

Android 9

### Firefox release type

Firefox Nightly

### Firefox version

109.0a1 (Build #2015919915)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-22108)

**Comment by kbrosnan** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1804383

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Comment by Amejia481** [comment]
@shtstorm thanks for your report!
The fix landed in main https://github.com/mozilla-mobile/fenix/pull/28231,  it should be available in the next nightly update
