### ISSUE TITLE
[Bug]: Allows users to choose as defaults only general or custom search engines

### ISSUE THREAD

**Issue by DreVla** [mozilla-mobile/fenix#28111]
### Steps to reproduce

1. Go to Settings
2. Go to Search
3. Inspect default search engine options

### Expected behaviour

Only general or custom search engines should be available to be set as default search engine.
If users have a `topic specific` search engine set as default then the default should be automatically migrated to the first available `general` search engine. Only if no other general search engines are available then the user will remain with the current `topic-specific` engine set as default.

### Actual behaviour

Any search engine can be selected as default search engine, including topic specific engines (amazon, ebay, etc...).

<img width="466" alt="Screenshot 2022-12-07 at 16 22 06" src="https://user-images.githubusercontent.com/32488956/206203714-c965be75-b8ab-4597-a509-4587403bb604.png">

### Android version

Android 10

### Firefox release type

Firefox Nightly

### Firefox version

109.0a1

### Additional information

Because topic specific search engines - like amazon / ebay / wikipedia will only show results from those specific websites - a restricted scope they are not suited for general searches - all around the web.

We need to limit the user’s ability to set such engines as defaults.
Since these search engines come bundled with the app we have control over them and can manually split each list of search engines for a specific locale to general or topic specific (naming not necessarily following this scheme).

This will not apply to user added search engines. All custom search engines will be treated as general search engines.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-22112)

**Comment by cadeyrn** [comment]
> We need to limit the user’s ability to set such engines as defaults.

@DreVla Why do you see this need? I would argue that an user who sets a topic specific search engine as default search engine, for example Amazon, is well aware that they will only find products on Amazon. And if they use the browser very frequently for the search for products (or tweets or articles on Wikipedia or whatever), what is wrong with allowing the user to set that search engine as the default search engine? I don't get the point of this change. 🤔

**Comment by Mugurell** [comment]
This limitation will be part of the new unified search UX which will allow users to easily switch from the toolbar to another search engine - like Amazon or to another application source - like open tabs. 
There will be important differences between the UX for a general search engine like DuckDuckGo and the UX for a search engine like eBay.
Also the UX reasoning is that quick searches should show results from all over the internet - hence only search engines like DuckDuckGo, Google, Bing, can be set as default.
Will double check with UX and product.

**Comment by SoftVision-LorandJanos** [comment]
Verified as fixed on the latest Nightly 111.0a1 (2023-01-27) build.
Only general and custom search engines can be chosen as default.
Device used: Oppo Find X5 (Android 12).
Closing the ticket as verified.
