### ISSUE TITLE
Update CFR in Private Browsing Mode

### ISSUE THREAD

**Issue by t-p-white** [mozilla-mobile/fenix#28114]
Update CFR that currently says, “Add a shortcut to open private tabs from your home screen” to say “Launch next private tab in one tap.” The buttons should say, “Add to Home screen” and “No thanks”

![image-20221205-163404](https://user-images.githubusercontent.com/1833156/206232195-cf203555-d040-438b-8557-8dda7944c34b.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-22113)

**Comment by onemahon** [comment]
Note: if this (for some unexpected reason) requires anything beyond simple string changes, please focus on landing the necessary string changes as an individual ticket ASAP (if there are any functional changes needed, afterwards, those changes can be made and uplifted - but it’s important to get the strings in before the v109 string freeze, which is [December 9th](https://whattrainisitnow.com/release/?version=nightly)).

(I’m hoping this ticket is literally just string changes, though - if it’s more complicated than that, please make sure to bring that up here or in Slack!)

**Comment by SoftVision-LorandJanos** [comment]
Verified on the latest Nightly 109.0a1 (2022-12-08) build.
Device used: Oppo Find X5 (Android 12).
Closing the ticket as verified.

**Comment by AdinaPetridean** [comment]
Also verified implemented on Beta 109.0b1 with Poco M4 Pro (Android 12).
