### ISSUE TITLE
[UX] permission handeling on android 11+

### ISSUE THREAD

**Issue by mavduevskiy** [mozilla-mobile/fenix#28110]
We could consider rethinking permission handling for devices running android11+.

We need to handle "allow once" permission option [introduced](https://developer.android.com/about/versions/11/privacy/permissions) introduced in android11. Currently there is a bug that causes the app to treat "allow once" option as "denied" on the next run. Here is the video to demonstrate the problem:

https://user-images.githubusercontent.com/92760693/206191985-afa81cc1-771a-4346-b0b7-7fa23e22296c.mp4

Adding a rationale would helps us to comply with the latest [guidelines](https://developer.android.com/training/permissions/requesting) by google on permission handling:
<img width="600" alt="image" src="https://user-images.githubusercontent.com/92760693/206182464-7a594e7f-cc41-41b7-a63f-00a20cd54309.png">

However, the guidelines does not mention the [denied forever](https://developer.android.com/about/versions/11/privacy/permissions#dialog-visibility) state which we also should take into account. It happens after the user has denied the app permission twice in a row and the system will block permission options dialog from showing forever (at that point we should help the user to navigate to app settings to change the allow the permission manually).

API for permissions in not a straightforward one, and the majority of the apps (even the most popular ones) handle this flow differently (and most of the time, not by the guidelines and failing to handle all of use-cases consistently, even Chrome). The challenging parts of the flow are: when to show the rationale, how to react to a permission denial and to a blocked permission window (two "denied" permissions). There is also an option to tap outside of the window, which makes telling them apart not possible without very hacky solutions.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-22111)

**Comment by onemahon** [comment]
(mostly) note to self: Product & UX to start looking at this. Engineering should start with an audit of all places in the user flow where permissions (may) get requested.

https://permission.site/  is a good utility to do some investigation here.

This ticket may wind up getting reworked into more of an epic with multiple sub-tasks. But will soon be migrated to Bugzilla, anyway.

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1814472

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
