### ISSUE TITLE
The live audio/video stream is still running after the Firefox app has already been force closed

### ISSUE THREAD

**Issue by AdinaPetridean** [mozilla-mobile/fenix#28123]
### Steps to reproduce

1. Go to rockfm.ro.
2. Play the live audio stream.
3. Force close the Firefox app. Observe the behaviour.

### Expected behaviour

The Firefox app is closed and so is the live audio stream.

### Actual behaviour

The live audio stream is still running after the Firefox app has already been force closed.

### Device name

Xperia 10 

### Android version

Android 12

### Firefox release type

Firefox Nightly

### Firefox version

109.0a1 (Build 2015920107)

### Additional information

Please note this issue is reproducible only for LIVE audio/video streams. I was able to reproduce it with: rockfm.ro, kissfm.ro, mediafax.ro.

https://user-images.githubusercontent.com/108326843/206391946-38873116-e6d3-4305-9bcd-262002e9a2ee.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-22118)

**Comment by delia-pop** [comment]
Partially reproducible with Xiaomi Redmi Note 8T (Android 9) in RC 108.1.0. build 2. After force closing Fenix while streaming on rockfm.com, although the streaming stopped, the media notification remained displayed. Tapping the "pause button did not start the streaming, but tapping on the notification opened the rockfm.com as a blank page.

![1670588469484](https://user-images.githubusercontent.com/89388888/206730329-471d4777-6095-447f-a3c4-dbb843655523.JPEG)

**Comment by kbrosnan** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813287

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
