### ISSUE TITLE
[Bug]: The "Jump back in" CFR cannot be dismissed and is stuck to the screen after opening a new tab

### ISSUE THREAD

**Issue by Softvision-PatriciuPop** [mozilla-mobile/fenix#28126]
### Steps to reproduce

1. Open the browser and tap the "Start Browsing" button.
2. Tap the "Wikipedia" top site and open a new tab.
3. Tap the dismiss button from the "Jump back in" CFR and observe the behavior.

### Expected behaviour

- The CFR message is dismissed.

### Actual behaviour

- The CFR message remains displayed and remains stuck to the screen when scrolling.

### Device name

OnePlus 6T

### Android version

Android 11

### Firefox release type

Firefox

### Firefox version

107.2.0 (Build #2015918523)

### Additional information

- The issues is only reproducible on locales that do not have Pocket stories enabled on the homepage. (e.g English UK)
- The CFR can be dismissed by tapping the phone's back button or by rotating the device's orientation.
- Attached a screen recording of the issue:

https://user-images.githubusercontent.com/40393891/206419316-4a9f0018-39fa-425c-bd51-34323ea8d006.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-22119)

**Comment by Alexandru2909** [comment]
Hi @Softvision-PatriciuPop ! Thanks for submitting this issue, I believe this has already been submitted [here](https://github.com/mozilla-mobile/fenix/issues/26957), we have a patch ready for it which should land in 110.

**Comment by SoftVision-LorandJanos** [comment]
Hi @Softvision-PatriciuPop! Thanks for your report!
The issue is reproducible on the latest Nightly 109.0a1 (2022-12-12) build.
The above mentioned issue while has the same cause, it's about a different CFR.
I believe the cause is the active address/search bar (When the cursor is on the address/search bar).
Device used: Oppo Find X5 (Android 12).

**Comment by delia-pop** [comment]
Tested with Google Pixel 6 (Android 13) on Nightly 110.0a1 from 12/14. 
As Alex said, fixing https://github.com/mozilla-mobile/fenix/issues/26957 would also solve this issue. However, as on 26957's case, 2 taps on screen (or 1 on screen, 1 on the "X" button) are required to dismiss the CFR: 
the first tap makes the search bar inactive, and the second dismisses the CFR.

**Comment by delia-pop** [comment]
Similar to https://github.com/mozilla-mobile/fenix/issues/26957, this is also verified as fixed on the latest Nightly 110.0a1 from 12/24 with OPPO A15s (Android 10). The CFR can now be dismissed.
The behavior described above is intended: the first tap (or attempt to swipe on screen will make the search bar inactive, and the 2nd tap on screen will dismiss the CFR).
