### ISSUE TITLE
[Bug] My podcasts cut out/Mes podcasts se coupent (on my pixel 6a))

### ISSUE THREAD

**Issue by Jean-Sayrien** [mozilla-mobile/fenix#28129]
Hello,
I just upgraded to a pixel 6a smartphone, and I immediately installed Firefox which I am a loyal user. But here is the problem I am having:

I usually use a site for listening to my podcasts. But after 10min or less, even when I set the screen standby to 30min, the podcast cuts out. I tried from the google podcast site and the problem is the same. No worries since firefox on pc on the other hand.

I just did the test through the phone's google browser, and the podcast no longer cuts out. But I prefer Firefox!
Could the problem come from the Pixel, or from Firefox?
The Google forum advises me to turn to you.

Thanks in advance !

-----------------------
Bonjour,
Je viens de passer à un smartphone pixel 6a, et j'ai de suite installé Firefox dont je suis une fidèle utilisatrice. Mais voici le problème que je rencontre :

J'ai l'habitude d'utiliser un site pour l'écoute de mes podcasts. Or au bout de 10min voire moins, et ce même quand je règle la mise en veille de l'écran sur 30min, le podcast se coupe. J'ai essayé depuis le site google podcast et le problème est le même. Aucun soucis depuis firefox sur pc par contre.

Je viens de faire le test en passant par le navigateur google du téléphone, et le podcast ne se coupe plus. Mais je préfère Firefox !
Le problème pourrait-il venir du Pixel, ou de Firefox ?
Le forum Google me conseille de me tourner vers vous.

Merci d'avance !

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-22122)

**Comment by delia-pop** [comment]
Hi, @Jean-Sayrien , thanks for reporting. 
I will try to reproduce the issue you're experiencing with several websites streaming podcasts using Google Pixel 6 (Android 13).
 
In the meantime, I would much appreciate your input for the following: 
- what Firefox version are you experiencing the issue on? Is it Firefox 107.2.0?
- can you try reproducing the issue on the latest Firefox Nightly 109.0a1 / Beta 108.0b6? 
- can you provide a link to the exact website for the podcast? 
- what Android Version do you have on your Pixel device? 

Merci!

**Comment by kbrosnan** [comment]
No answer to the questions. If this bug still occurs please refile it at https://bugzilla.mozilla.org/enter_bug.cgi?product=Fenix
