### ISSUE TITLE
Back, Forward and Refresh buttons missing when launching Firefox in split screen

### ISSUE THREAD

**Issue by Rhaston** [mozilla-mobile/fenix#28142]
### Steps to reproduce

1. Make sure Firefox is closed and not running in the background. Open any Android app.
3. Launch Firefox in split screen (tested using Samsung's Edge Panel drag and drop method and by launching Firefox from Recents / Task List screen).
4. Navigate to any website on newly launched Firefox instance. Back, Forward and Refresh buttons that should appear next to the Home button in address bad will be missing.

There are no issues when Firefox is launched first in full screen and then another app is added into the split screen. The issue is present on Beta and Nightly as well.

### Expected behaviour

Firefox launched in split screen should have a fully functioning UI.

### Actual behaviour

Portion of UI is missing from the app when launched in split screen.

### Device name

Samsung Galaxy Tab S8

### Android version

Android 13 (One UI 5)

### Firefox release type

Firefox

### Firefox version

104.1.0, 107.2.0, Beta, Nightly

### Additional information

https://user-images.githubusercontent.com/120144641/206593797-82bedd8b-abf1-45c7-b9d9-6d2338fcd5ff.mp4

![Screenshot_20221208_190606_Firefox Beta](https://user-images.githubusercontent.com/120144641/206593803-856d110e-f51e-4033-8f07-1495e743d9bc.jpg)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-22125)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812363

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
