### ISSUE TITLE
Support showing Nimbus messages as they are updated 

### ISSUE THREAD

**Issue by Mugurell** [mozilla-mobile/fenix#28156]
As a followup to https://github.com/mozilla-mobile/fenix/pull/28147#discussion_r1044650102:

> I think it could be valid to also add the patch to the main branch too, as I think we only load experiments async on the first run, after that we try to fetch experiments that it's done sync.

> The only drawback is as we are dispatching twice the MessagingAction.Restore, in some cases we would be reducing the times that users will see a message, ideally we would improve that by observing the messages in MessagingFeature, and dispatching when they are updated.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-22132)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1809314

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
