### ISSUE TITLE
[Bug]: Tabs refresh after going out of Firefox (not closing)

### ISSUE THREAD

**Issue by Itemee123** [mozilla-mobile/fenix#28150]
### Steps to reproduce

1. Open a site
2. Go to the home screen, but do not clear Firefox from “Recently Used Apps”
3. Open another app
4. Go back to Firefox

### Expected behaviour

The site should stay opened and not be refreshed.

### Actual behaviour

The site is opened and Firefox refreshes it.

### Device name

Samsung Galaxy A32 4G

### Android version

Android 13

### Firefox release type

Firefox

### Firefox version

107.2.0

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-22127)

**Comment by vehosah** [comment]
This damn bug exists since Firefox 68

**Comment by csadilek** [comment]
Thanks for filing. We're working on and tracking this problem in https://bugzilla.mozilla.org/show_bug.cgi?id=1752594. Please follow along there.
