### ISSUE TITLE
Topic specific search engines: Tapping the toolbar after a search should show the search term with the cursor at the end

### ISSUE THREAD

**Issue by Mugurell** [mozilla-mobile/fenix#28154]
Currently the entire url is selected.
The desire is for users to be able to continue their search, maybe add more search term and so when the toolbar is focused it should show the search terms with the cursor at the end.

[Figma](https://www.figma.com/file/epu0Sj6mCPk7K282sNpHgI/Site?node-id=3850%3A59494&t=wWlnUtSAi0Azu4Tf-1)

![image](https://user-images.githubusercontent.com/11428869/206755110-419c74a9-d072-4af9-92c4-7bb371894e80.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-22130)

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807585

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
