### ISSUE TITLE
The brightness is strangely changed after connecting to a bluetooth keyboard

### ISSUE THREAD

**Issue by Iey4iej3** [mozilla-mobile/fenix#28158]
### Steps to reproduce

1. Connect to a bluetooth keyboard.
2. Open a new tab.
3. Open a webpage in this tab (e.g. perform a search)

### Expected behaviour

The brightness is not changed.

### Actual behaviour

The brightness of all tabs (including the previously opened tabs) is changed. It only affects the renderings, not the UI.

### Device name

Mi 10T Pro

### Android version

LineageOS 19

### Firefox release type

Firefox

### Firefox version

107.1.0

### Additional information

The brightness before connecting to the bluetooth keyboard:
![unchanged](https://user-images.githubusercontent.com/1880768/206849042-db2b4042-73b0-47d2-9657-5eae84ea1cb1.png)

The brightness after connecting to the bluetooth keyboard:
![changed](https://user-images.githubusercontent.com/1880768/206849034-92cbd9d0-197f-40af-8978-53ea4150c4f5.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-22133)

**Comment by marcel263** [comment]
Dear,  uncharacteristic issue. It is not reproducible on my Samsung device. Did you check it with other apps? Does the system react the same way, or only Firefox?

You say the UI is not affected, yet it seems brighter.

Does there exist some automatic contrast setting in your custom ROM?

**Comment by Iey4iej3** [comment]
It might be possible that the issue is related to the extension Dark Reader. I perform more tests: it can be temporarily solved by disabling and re-enabling Dark Mode, but the brightness is again changed after a refreshing.

My Internet is laggy now and I cannot download Nightly to test whether it is there.

> It is not reproducible on my Samsung device.

It is reproducible on my Samsung S6 Lite, also under LineageOS.

> Did you check it with other apps? Does the system react the same way, or only Firefox?

Yes to both, as far as I see.

> You say the UI is not affected, does it also count for tab tray and its thumbnails?

Yes, tab trays and thumbnails, including the initial page, are untouched.

**Comment by AdinaPetridean** [comment]
@raspin0 Thank you for reporting this issue. I cannot reproduce this issue on Firefox 108.1 nor the latest Nightly 109.0a1 from 12/12 with my Motorola Moto G9 plus (Android 11) device. Please see if you still reproduce the issue with the latest Nightly build.

**Comment by Iey4iej3** [comment]
Yes, I can, and it is reproduced under Firefox Nightly 110.0a1 (Build #2015921259), 2022-12-13T05:18:05.239380, along with extension "Dark Reader", and the same workaround (re-enabling Dark Reader) takes effect.

![firefox_nightly](https://user-images.githubusercontent.com/1880768/207410752-d606bb45-ed12-442e-a7e0-94917527e0a7.png)
![firefox_nightly2](https://user-images.githubusercontent.com/1880768/207410859-aed48a03-9ebc-4593-b504-6799cb071808.png)

**Comment by mimuki** [comment]
I have this same issue, except it happens randomly (unrelated to connecting any Bluetooth devices), and happens even with no extensions installed. my device is a Samsung S10e running stock android 12, and firefox 108.1.0. also observed on my Samsung tablet (I don’t know the exact model off the top of my head but can check if it helps debugging).

also, I’ve only observed it happening with firefox’s dark theme enabled, (though I have only done a small amount of testing in light mode, as my eyes are very sensitive) and I’ve been ripping my hair out for months trying to find out why its been happening. the issue temporarily goes away when opening certain menus like the add on manager screen- i thought it was extension related for me too at first, but the issue at least on my device continues with no extensions enabled.

**Comment by Iey4iej3** [comment]
It turns out to be irrelevant to the extension Dark Reader. I reproduced this under Firefox Nightly 110.0a1 (Build #2015924523), d9106ff1a+ version 2022-12-30T05:12:53.552470

See the screenshots below.

without bluetooth keyboard:
![nightly_wo_keybd](https://user-images.githubusercontent.com/1880768/210074159-7347ee1a-d024-45bf-b321-2549263e3ece.png)

with bluetooth keyboard
![nightly_with_keybd](https://user-images.githubusercontent.com/1880768/210074164-304d58c6-36ea-415e-8917-d0b961644242.png)

**Comment by mimuki** [comment]
I’ve done a few weeks of testing while only using firefox’s light mode, and couldn’t get it to happen once. switching back to dark mode immediately caused it to start happening again

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813902

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
