### ISSUE TITLE
General search engines: Tapping the toolbar after a search should show the search term with the cursor at the end

### ISSUE THREAD

**Issue by Mugurell** [mozilla-mobile/fenix#28153]
Currently the entire search term is selected.
The desire is for users to be able to continue their search, maybe add more search term and so when the toolbar is focused it should show the search terms with the cursor at the end.

![image](https://user-images.githubusercontent.com/11428869/206754398-f46be547-0f2c-4062-b2a1-c5691d3e3bc4.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-22131)

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807586

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
