### ISSUE TITLE
Add ClearURL extension

### ISSUE THREAD

**Issue by amalic** [mozilla-mobile/fenix#28163]
It would ve great if you could add the ClearURLs extension to remove tracking id's and unnecessary crap from URLs.

ClearURLs team is correctly forwarding it to the Firefox for Android team. -> https://github.com/ClearURLs/Addon/issues/247

This has already been requested in 2020 and nothing has happened since then. -> https://github.com/mozilla-mobile/fenix/issues/10943

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-22135)

**Comment by kbrosnan** [comment]
We don't keep requests for individual extensions open.

**Comment by KevinRoebert** [comment]
ClearURLs is now also available on Firefox for Android: https://blog.mozilla.org/addons/2022/12/15/new-extensions-available-now-on-firefox-for-android-nightly/

**Comment by amalic** [comment]
Thank you @KevinRoebert for the update!
