### ISSUE TITLE
[Bug]: Credit Card and Address Autofill features are partially working and misleading for the users outside the supported regions  

### ISSUE THREAD

**Issue by delia-pop** [mozilla-mobile/fenix#28173]
### Steps to reproduce

Precondition:
1. Use a VPN set to any region other than US, CA, GB, FR, DE (for Credit Cards)/US, CA (for Addresses).
2. Set the language in Firefox to en-US in order to have the Addresses Autofill feature available in Settings. 
3. Have some Credit Cards and Addresses saved in Firefox.
STR:
1. Access a website that has a Credit Card (e.g. https://checkout.stripe.dev/, https://www.instant-gaming.com/)/Address (e.g. https://www.spreadshirt.com/ Checkout page) input form.
2. Tap on the credit card number/credit card name field/any address field.
3. Select a saved credit card/address from the prompt.
4. Observe that the form is not autofilled.
5. Repeat Step 3 and observe if the prompt is displayed again. 

### Expected behaviour

Pending UX feedback.
The Credit card and Address autofill features should work properly or not be available at all to the users located in unsupported regions. 
A similar example in this direction is the availability of the "Address Autofill" section in Settings > Autofill screen: when a different language than en-US is set in Firefox, the section is no longer available and the "Autofill" section becomes "Credit Cards", where only the Credit card autofill feature is available.   

### Actual behaviour

For an user located in an unsupported region, the Credit Card and Address Autofill features are only partially working: after selecting a saved credit card/address from the prompt, the form is not autofilled and the prompt will not be displayed again, not even after refreshing or restarting Firefox, which can affect the user experience. 

Please note that although the user can manually change the "browser.search.region" and "extensions.formautofill.supportedCountries" to the supported regions in order to use the features as stated at https://support.mozilla.org/bm/questions/1345147, after repeatedly changing the prefs, the "Saved credit cards"/"Saved addresses" prompt can stop being displayed. 

### Device name

Google Pixel 6 (all devices)

### Android version

Android 13 (all Android versions)

### Firefox release type

Firefox Nightly

### Firefox version

109.0a1 from 12/11

### Additional information

Reproducible on Release and Beta channels as well.

https://user-images.githubusercontent.com/89388888/207125777-b65dd387-ca99-49ec-84f9-63e3f62433a6.mp4

https://user-images.githubusercontent.com/89388888/207125575-7f557115-dcf1-4c41-a4cb-9806bbf4b472.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-22139)

**Comment by kudlav** [comment]
CZ region is also affected

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1814185

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
