### ISSUE TITLE
[Bug]: Visiting 9gag bricks the browser

### ISSUE THREAD

**Issue by raspin0** [mozilla-mobile/fenix#28172]
### Steps to reproduce

1. Open browser 
2. Search for 9gag.com

### Expected behaviour

A website opens

### Actual behaviour

After a couple of seconds the loading bar freezes, network traffic stops and website isn't loading anymore.

### Device name

Huawei P10 lite 

### Android version

Android 8

### Firefox release type

Firefox

### Firefox version

107.2.0

### Additional information

App needs to be force-quitted in order to be functional again. 

https://user-images.githubusercontent.com/39202451/207122038-d5d5f060-2839-4587-9bc2-a78791c3d9ab.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-22138)

**Comment by AdinaPetridean** [comment]
@raspin0 Thank you for reporting this issue. It is not reproducible on my Motorola Moto G9 plus (Android 11) device. Does this issue reproduce with other websites? Can you reproduce this issue on the latest Nightly?

**Comment by raspin0** [comment]
> Does this issue reproduce with other websites? 

No

> Can you reproduce this issue on the latest Nightly?

No

**Comment by kbrosnan** [comment]
If this does not reproduce in nightly then it should be fixed in an upcoming release.
