### ISSUE TITLE
[UITests] Track ignored tests from #27262

### ISSUE THREAD

**Issue by Alexandru2909** [mozilla-mobile/fenix#28182]
In https://github.com/mozilla-mobile/fenix/pull/27262 we disabled some failing tests after changing the interaction with the homescreen from `SearchDialogFragment`.

Failing tests were ignored with:
`@Ignore("Failing after changing SearchDialog homescreen interaction. See: https://github.com/mozilla-mobile/fenix/issues/28182")`

cc @AndiAJ @sv-ohorvath

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-22142)

**Comment by AndiAJ** [comment]
Re-enabled `verifySearchEnginesWithRTLLocale` in #28220

**Comment by AndiAJ** [comment]
`verifySearchEnginesWithRTLLocale` got disabled again in #28224.

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807271

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
