### ISSUE TITLE
[Bug]: Can't add search engine, "Error connecting to ..."

### ISSUE THREAD

**Issue by arzyu** [mozilla-mobile/fenix#28184]
### Steps to reproduce

1. Go to "Search engine settings"
2. Click "Add search engine"
3. Select "Other"
4. Input "Name" field with: "Google translate page"
5. Input "Search string to use" field with: "https://translate.google.com/translate?sl=auto&tl=zh-CN&u=%s"
6. Click "Add" action
7. Display error message: "Error connecting to ..."
![WechatIMG894](https://user-images.githubusercontent.com/1270145/207316133-a7a930d4-81c2-411f-a12b-80ed29f0c72b.jpeg)

### Expected behaviour

Add search engine successfully.

### Actual behaviour

Add search engine failed.

### Android version

Android 12

### Firefox release type

Firefox

### Firefox version

107.2.0

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-22143)

**Comment by SoftVision-LorandJanos** [comment]
Hi @arzyu! Thanks for your report!
I've tried to add a search engine using your string and I wasn't successful either.
However, you might want to try "https://translate.google.com/?sl=auto&tl=en&text=%s" that works for me as google translate search engine (I got help from @Alexandru2909 to discover this).
Device used: Google Pixel 4 (Android 13).

**Comment by kbrosnan** [comment]
Works for me with a correct string.

**Comment by arzyu** [comment]
These are two different functions:
 * `...&text=%s` for translating text
 * `...&u=%s` for translating pages, eg. https://translate.google.com/translate?sl=auto&tl=zh-CN&u=https%3A%2F%2Fen.wikipedia.org%2Fwiki%2FMain_Page
 
I can add `...&text=%s` to firefox successfully, but not `...&u=%s`.
