### ISSUE TITLE
[Bug]: about:crashparent doesn't display the crash notification on Android 10+ Xiaomi devices 

### ISSUE THREAD

**Issue by delia-pop** [mozilla-mobile/fenix#28181]
### Steps to reproduce

1. Open a few tabs in Firefox..
2. Tap the URL bar and access about:crashparent.
3. Observe the Android notification bar.

### Expected behaviour

For Android >=10 devices, when about:crashparent is entered in the URL bar, the browser closes and the crash system notification is displayed in the Android status bar.

### Actual behaviour

When about:crashparent is entered in the URL bar, the browser closes, and no crash notification appears in the Android notification bar, not even after multiple attempts. 

### Device name

Xiaomi 12 Pro 

### Android version

(Android 13)

### Firefox release type

Firefox Nightly

### Firefox version

110.1.0

### Additional information

Tested and reproduced with: Xiaomi 12 Pro (Android 13), Xiaomi Pad5 (Android 12), Xiaomi Mi11 Lite (Android 11) & Xiaomi Mi 8 Lite (Android 10).
The issue is present on all Firefox versions: the latest Nightly 110.0a1 from 12/13, Beta 108.0b6 and Firefox RC 108.1.0.

As discussed in #26383, the workaround to display the crash dialog for Android <=9 Xiaomi devices is to allow the "Display pop-up windows while running in the background" permission from device's Settings.

[A13_Xiaomi.txt](https://github.com/mozilla-mobile/fenix/files/10215681/A13_Xiaomi.txt)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-22141)

**Comment by DiegoARL38** [comment]
I'm able to reproduce with my Xiaomi Redmi Note 8 running Android 11 (MIUI 12.5.2.0).

I haven't found any way to send crash reports at all.

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1805974

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
