### ISSUE TITLE
[webcontent] Some buttons are not clickable on Google Maps

### ISSUE THREAD

**Issue by Iey4iej3** [mozilla-mobile/fenix#28193]
## Site with issue and any steps to reproduce

1. Visit [Google Maps](google.com/maps),
2. Input a place then click "Directions" to navigate,
3. Input the starting point,
4. Select the public transport,
5. Click "Leave now".
----

Another case, maybe related: https://me-deplacer.iledefrance-mobilites.fr/fiches-horaires/bus/line%3AIDFM%3AC00074?direction=1

Click "Sélectionner un arrêt"

### Expected behavior

A dialog pops up to choose the time to leave.

For the other site: a drop-list shows up.

### Actual behavior

Nothing.

### Does toggling Tracking Protection fix the issue? (Press the shield icon in the toolbar while on the site to see toggle)

No.

### Can you reproduce in Chrome (or other non-Mozilla browser)?

No.

### Device information

* Android device: Lineage OS 19.1
* Fenix version:
Nightly 110.0a1 (Build #2015921259),
2022-12-13T05:18:05.239380
also reproducible on Stable 108.1.0 (Build #2015920443)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-22145)

**Comment by kbrosnan** [comment]
This does not sound like a Firefox bug. Google may be sending a different website to Firefox. You can followup with this at https://webcompat.com
