### ISSUE TITLE
Renew telemetry expiring in 111

### ISSUE THREAD

**Issue by MatthewTighe** [mozilla-mobile/fenix#28190]
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-22144)

**Comment by SoftVision-LorandJanos** [comment]
Hi @MatthewTighe! Could you tell me what exactly needs to be checked for this ticket?  Thank you!

**Comment by MatthewTighe** [comment]
Nothing, just forgot to uncheck the needs QA box. Thanks for bringing it to my attention!
