### ISSUE TITLE
Cookie banner disappears only after page refresh

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#28197]
### Steps to reproduce

1. Open `voetbal24.be` in a new tab
2. Enable the "cookie banner reduction" setting
3. Navigate back to the previously opened tab
4. Check if the cookie banner is displayed

### Expected behaviour

Cookie banner should not be displayed.

### Actual behaviour

Cookie banner remains displayed, the user needs to refresh the page to make it disappear.

### Device information

* Device vendor / model and Android version: 
► Google Pixel 2 (Android 9)
► Google Pixel 3a (Android 11)

### Firefox version: 
► Nightly 109.0a1

### Additional information
❗  Happens on other websites [from the list](https://github.com/mozilla/cookie-banner-rules-list/blob/main/cookie-banner-rules-list.json)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-22147)

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807440

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
