### ISSUE TITLE
Credit Card Autofill bug

### ISSUE THREAD

**Issue by zilvinastotp** [mozilla-mobile/fenix#28194]
### Steps to reproduce

1. Have NordPass, 1Password, BitWarden or any other password manager installed and native autofill enabled;
2. Go to any credit card form;
3. Press on any input;
4. There are no autofill suggestions.

### Expected behaviour

Native autofill service is triggered and autofill suggestions appear.

### Actual behaviour

Native autofill service is not triggered and autofill suggestions does not appear.

### Device name

Google Pixel 4a

### Android version

Android 12

### Firefox release type

Firefox

### Firefox version

108.1.0

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-22146)

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813903

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
