### ISSUE TITLE
[Bug] Expand/collapse a collection from the bottom of the list, jumps to the top

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#2820]
## Steps to reproduce
1. Create a few collections (~3).
1. Scroll down to the bottom of the collections list. Expand the last one.
1. collapse the last one.
    1. Expected behavior
The expanded/collapsed collection is displayed.
    1. Actual behavior
The list jumps to the top.
    1. Device information

* Android device: Note 8 (android 9), Mi4 (Android 5.0.2)
* Fenix version: 5/24

**Comment by IdmFoundInHim** [comment]
Reproduced on Android 7, Samsung Note5, Fenix 1.0.1921 (Build 1 68.0-20190520141152) built from GitHub.

The plot thickens: The best way I can describe this is that the scroll is reset to its 'original' position -- the position it was in when the app was brought to the foreground -- when a collection is expanded or collapsed AND whenever a tab is closed.

## STR
1. Create one or more collections and/or tabs
1. Go to Fenix home and scroll up until the logo is visible
1. Remove Fenix from the foreground (home button, recents, lock, etc.), but do not fully close it
1. Enter Fenix
1. From home, scroll down until the logo is gone
1. Close one of the tabs (swipe or button), or expand/collapse a collection
---THEN---
1. Scroll down again until the logo is gone
1. Remove Fenix from the foreground (home button, recents, lock, etc.), but do not fully close it
1. Enter Fenix again
At this point, home should still be scrolled down
1. Scroll up so the logo is visible
1. Close a tab or expand/collapse a collection

## Expected
No automatic scrolling at any point, except perhaps to bring the contents of an expanded collection into the viewport.

## Actual
After step 6, the viewport is scrolled to the top of the home page.
After step 11, the viewport is scrolled down so the logo is not visible.
At no point does this help the user see anything they interacted with.

**Comment by vesta0** [comment]
Will be addressed in #3004
