### ISSUE TITLE
[BUG] search engine touch rippple is misplaced

### ISSUE THREAD

**Issue by mavduevskiy** [mozilla-mobile/fenix#28205]
Steps to reproduce: 
1. Enable debug menu by tapping firefox logo icon
2. enable unified search
3. focus the edit text inside the toolbar
4. tap on the search engine icon

Expected behavior: ripple is centered around the search engine icon
Actual behavior: ripple has top margin.

https://user-images.githubusercontent.com/92760693/207787021-4df7be31-048d-4f09-8653-a0e94dc61755.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-22149)

**Comment by amocirean** [comment]
Hello!
Verified as fixed on the latest Nightly from 19th of November 2022 (110.0a1).
Tested on: Samsung Galaxy A32 5G (Android 12), Google Pixel 6 (Android 13).
Thanks!
