### ISSUE TITLE
Make a “@LightDarkPreview()” annotation that makes two previews from one annotation

### ISSUE THREAD

**Issue by HarrisonOg** [mozilla-mobile/fenix#28201]
Currently we use two annotations in Compose Preview functions in order to display previews with both dark mode on and off.

This task is for creating a multi-annotation class that wraps both of these annotations into a single annotation, helping with readability and any future extension of the multi-annotation so it will include other rendering options.

Tasks:
- [ ] Create multi-annotation for both dark mode on and off
- [ ] Replace all uses of the two annotations with the single multi-annotation

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-22148)

**Comment by Mugurell** [comment]
There was also https://github.com/mozilla-mobile/fenix/issues/25258 for including more configurations.
