### ISSUE TITLE
[Bug]: history pane opens twice when long pressing the back button

### ISSUE THREAD

**Issue by luca-e075e** [mozilla-mobile/fenix#28215]
### Steps to reproduce

1. visit few websites (more than one)
2. long press back navigation button

### Expected behaviour

One history pane appears, where:
- Selecting an entry will hide the history and go to the internet page
- Pressing the back button will hide the history and return to the actual page

### Actual behaviour

Two history panes are opened.
Any action on the top pane will work and close it, but it bring up the second pane on top and the user have to dismiss it (back button)

### Device name

Oppo CPH1931

### Android version

10

### Firefox release type

Firefox

### Firefox version

107.2.0

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-22155)

**Comment by amocirean** [comment]
Hello,
I was not able to reproduce the issue on the latest Nightly (110.0a1).
Could you please test this in the latest Firefox Nightly and tell us if the issue is still reproducible? Also, please provide a screenshot/screen recording if possible.

Thanks!

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812961

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
