### ISSUE TITLE
[Bug]: New logins with empty username can be saved

### ISSUE THREAD

**Issue by AdinaPetridean** [mozilla-mobile/fenix#28214]
### Steps to reproduce

1. Open the add login dialog
2. Fill in the Password field and leave the Username field blank.

### Expected behaviour

An error message is displayed with "Username required" text in red under the field.
The field line turns red.
An exclamation mark icon is displayed on the right end of the field.

### Actual behaviour

Login with an empty username can be added manually. No error message is displayed.

### Device name

Poco M4 Pro 

### Android version

Android 12

### Firefox release type

Firefox Nightly

### Firefox version

110.0a1

### Additional information

This issue is also reproducible on Firefox 109.0b1 and Firefox 108.1.0.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-22154)

**Comment by MicroBeast** [comment]
Is this just OK though? I could save DuckDuckGo password which didn't use UserName. And that Password only Autofill work on DDG.
