### ISSUE TITLE
Open current page in a new private tab

### ISSUE THREAD

**Issue by massimiliano-leoni** [mozilla-mobile/fenix#28216]
Nowadays most websites clutter the screen with banners to accept their cookies.
Currently I diligently go through the settings to disable as many as possible before I "accept" and can finally read the page.
Sometimes rejecting cookies doesn't work so I copy the link, open a new private tab, paste the link, accept all the cookies (which will be deleted when I leave private browsing), read the page.
This second method is even better than accepting only necessary cookies but it takes significantly longer.
The best of both worlds would be to have a quickly-accessible function to reopen the current tab in a new private tab. Then one could quickly accept all cookies and then be sure that they will be removed when closing the tab.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-22156)

**Comment by amocirean** [comment]
Hello! Thanks for submitting your request. I will mark this issue as a feature request.

**Comment by massimiliano-leoni** [comment]
The pleasure is all mine! Thanks for the support and the wonderful work.

**Comment by hakeem-gitstart** [comment]
@amocirean I am currently working on this, i'll like to ask if the tab that's opened in a `private mode` should be closed in the `normal mode` or both instance should stay

**Comment by massimiliano-leoni** [comment]
Hello, nice to see an update so soon :)
For the use case that I envisioned I would say that the tab in normal mode can be closed.

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812960

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Comment by hakeem-gitstart** [comment]
> Hello, nice to see an update so soon :) For the use case that I envisioned I would say that the tab in normal mode can be closed.

thanks for your response, will open a PR soon

**Comment by massimiliano-leoni** [comment]
> thanks for your response, will open a PR soon

Thanks to you! By the way, is my understanding of cookies and private browsing correct?
I'm referring to what I described in the issue description.

**Comment by hakeem-gitstart** [comment]
> which will be deleted when I leave private browsing

AFAIK, cookies are deleted when you exit incognito mode

**Comment by massimiliano-leoni** [comment]
Fantastic, then this whole thing does make sense :)
