### ISSUE TITLE
FNX3-16606 ⁃ [Bug] Crash when accessibility scale is changed to 100%

### ISSUE THREAD

**Issue by softvision-miralobontiu** [mozilla-mobile/fenix#2821]
## Steps to reproduce
1. Go to Settings - Accessibility
1. Change the scale from where it's at to 100%. (If it is to 100% move to a higher scale, then back to 100% - like in the attached short gif).

### Expected behavior
The app should not crash.

### Actual behavior
Crashes every time.

### Device information
* Android device: Google Pixel (Android 9)
* Fenix version: 5/24

[logcat.txt](https://github.com/mozilla-mobile/fenix/files/3215735/logcat.txt)

![2019](https://user-images.githubusercontent.com/40694158/58312225-860d2e80-7e13-11e9-9f13-a6379ff960c4.gif)UNITO-UNDERSCORE!05!UNITO-UNDERSCORE!24!

**Comment by buttercookie42** [comment]
Likely related to #2762.

**Comment by softvision-miralobontiu** [comment]
Verified as fixed on the latest build 1.0.1922 (#11490609) with Google Pixel (Android 9).
