### ISSUE TITLE
[Bug] Address/Search Bar not hiding anymore on scrolling down

### ISSUE THREAD

**Issue by vishwa-raj** [mozilla-mobile/fenix#2822]
## Steps to reproduce
Scroll down a page, then scroll up

### Expected behavior
Earlier Address/Search bar used to hide on scrolling down and then pop up when scrolled up.

### Actual behavior
Address/Search bar has become fixed and does not hide anymore.

### Device information
Nokia 6.1

* Android device: Android 9
* Fenix version: 1.0.1921

**Comment by cadeyrn** [comment]
This is intended, see #2689.

**Comment by vishwa-raj** [comment]
@cadeyrn Thanks for the update.
