### ISSUE TITLE
[Bug]: Browser crashes on reuters.com

### ISSUE THREAD

**Issue by shtstorm** [mozilla-mobile/fenix#28225]
### Steps to reproduce

1. Have a Private Browser tab opened with an article from Reuters site. Ex: [https://www.reuters.com/world/asia-pacific/pacifist-japan-unveils-unprecedented-320-bln-military-build-up-2022-12-16/](https://www.reuters.com/world/asia-pacific/pacifist-japan-unveils-unprecedented-320-bln-military-build-up-2022-12-16/) 
2. Scroll down to **Latest Updates** news section in the article 
![Screenshot_20221216-105113~2](https://user-images.githubusercontent.com/79124442/208148870-8e16a52f-b6c7-4758-a0d9-6a9943740874.png)
3. Long press on the first headline for menu to pop up and **Open link in private tab** 
![Screenshot_20221216-104152~2](https://user-images.githubusercontent.com/79124442/208149394-8f56059d-f284-480b-9f5c-ba1a2487ffcb.png)
4. Do **not** go to that tab
5. Continue on reading and slowly scrolling down the original article
6. A few seconds later browser crashes without crash reporter

### Expected behaviour

Browser should not crash while reading an article when another article is opened in a background tab

Enabled add-ons:
![Screenshot_20221216-104108](https://user-images.githubusercontent.com/79124442/208151532-ca1c3605-cb51-4d50-ad2c-ce1cd6fe5be5.png)

### Actual behaviour

Browser crashes while reading an article when another article is opened in a background tab

### Android version

Android 9

### Firefox release type

Firefox Nightly

### Firefox version

109.0a1 and 110.0a1

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-22157)

**Comment by kbrosnan** [comment]
Do you have a crash ID? https://github.com/mozilla-mobile/fenix/wiki/Logging-Crash-Information

**Comment by kbrosnan** [comment]
No crash IDs.
