### ISSUE TITLE
Unable to click private tab button while having something in clipboard 

### ISSUE THREAD

**Issue by Frunkh** [mozilla-mobile/fenix#28226]
### Steps to reproduce

1. Put a link in your clipboard
2. Click on the 3 dots top right
3. Click on + new tab

### Expected behaviour

I should be able to click on the private tab button immediately.

### Actual behaviour

The url bar focusses and the keyboard opens, so the "Fill link from clipboard" shows. This hoewever is right over the private window button. The button should move down or the "fill link from clipboard" button should be shorter and not full width.

![IMG_20221216_202751](https://user-images.githubusercontent.com/2933557/208174541-a28f72ba-ff27-4392-9973-57b2b33dd0c5.jpg)

### Device name

OnePlus 10T

### Android version

Android 11

### Firefox release type

Firefox Nightly

### Firefox version

107.2.0

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-22158)

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812959

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
