### ISSUE TITLE
Deleting history takes a very long time

### ISSUE THREAD

**Issue by icedrocket** [mozilla-mobile/fenix#28229]
## Steps to reproduce
Use Firefox for Android frequently, browsing the web for at least 3 weeks.

### Expected behavior
All search history will be deleted within 10 seconds.

### Actual behavior
Deleting history takes more than 2 minutes and is not responding.

### Device information
* Android device:  Samsung Galaxy A51 5G, Android 12
* Fenix version: 108.1.0 (Build <span>#</span>2015920443)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-22159)

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807356

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
