### ISSUE TITLE
After closing all private browsing tabs using the tab switcher to select a normal tab will take you to the home screen

### ISSUE THREAD

**Issue by marcel263** [mozilla-mobile/fenix#28235]
### Steps to reproduce

1. Both regular and private tabs open
2. Close all private tabs
3. Tap a regular tab that is already open

### Expected behaviour

Tab opens

### Actual behaviour

Returns to home screen, needs extra attempt at opening the tab

### Android version

Android 11

### Firefox release type

Firefox Nightly

### Firefox version

110.0a1 (Build #2015922219), b73b37329+

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-22160)

**Comment by marcel263** [comment]
https://user-images.githubusercontent.com/76437842/208293610-77d82eac-4a3f-4332-b9f4-0acbe032e251.mp4

**Comment by marcel263** [comment]
https://user-images.githubusercontent.com/76437842/208293932-2af27b0b-a924-4c64-b857-cc14445596f0.mp4

**Comment by AdinaPetridean** [comment]
Hello @marcel263 , thank you for submitting the issue.
I was able to reproduce the issue on the latest Nightly (110.0a1) from 03.01.2023 build.
Tested on: Motorola Moto G9 plus (Android 11).
Thanks!

**Comment by kbrosnan** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813286

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
