### ISSUE TITLE
Browser Menu should cover anchor view completely

### ISSUE THREAD

**Issue by mavduevskiy** [mozilla-mobile/fenix#28244]
Follow up to [unified search](https://github.com/mozilla-mobile/fenix/pull/27647) toolbar icon.

Menu should [overlap the icon](https://www.figma.com/file/epu0Sj6mCPk7K282sNpHgI/Site?node-id=3754%3A51117&t=dfqPDyfJ9knECBVw-4) completely.

Like this:
<img width="186" alt="Screen Shot 2022-12-19 at 5 05 42 PM" src="https://user-images.githubusercontent.com/92760693/208376934-2f21ebd2-e0af-4224-8261-36f53b47bde7.png">

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-22162)

**Comment by Mugurell** [comment]
This seems to be a duplicate of https://github.com/mozilla-mobile/fenix/issues/27998

**Comment by mavduevskiy** [comment]
@Mugurell oh that was a quick reply! thanks!
