### ISSUE TITLE
Engagement notifications do not appear if app remains active in background

### ISSUE THREAD

**Issue by onemahon** [mozilla-mobile/fenix#28242]
Follow up from Delia and Adina's comments in #27949. See Delia's summary [here](https://github.com/mozilla-mobile/fenix/issues/27949#issuecomment-1342486750).

Essentially: while testing this behavior, it's easy to leave the app active in the background in order to move the clock forward by 2 days. But, it's less likely that regular devices would keep the app active for 48 hours in the background; so as long as that's the reason for the bug, it may not be an urgent edge case to resolve.

* This will be exacerbated if we experiment with shorter notification windows (e.g. 12 or 24 hours)
* There's a chance my hunch about the reason behind this bug is wrong. I'm hoping we can use telemetry to observe real-world notification statistics to make sure we're not accidentally missing a large portion of the targeted population. Initial idea proposed [here](https://github.com/mozilla-mobile/fenix/issues/27949#issuecomment-1357166973).

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-22161)

**Comment by rocketsroger** [comment]
From my testing, when modifying system time, the app (Fenix in this case) has to be forced closed for it to work. If the app is not forced closed, I have to wait the full delay time even with system time modified. I don't think this is a bug but a difference in how Android OS determines when the delay time expires when the app is running vs app is closed.

With the way we're currently using system time to test the notification, Fenix will have to be forced closed for that to work. However, I did test (with a shorter delay) that without force closing the app, the notification will still show up.

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812958

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
