### ISSUE TITLE
FNX3-16609 ⁃ [Bug] Back button on search bar closes the app

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#2824]
## Steps to reproduce
1. Tap the search bar on the homescreen.
1. Tab the device back button.
    1. Expected behavior
Keyboard & search mode are collapsed. App homescreen is displayed.
    1. Actual behavior
The app is closed.
    1. Device information

* Android device: Samsung Galaxy Note 8 & S8 (both Android 9), Huawei Honor 8 (Android 7.0)
*Not reproducing on: Pixel (Android 9), Sony Xperia Z2 (Android 6.0.1), Mi 4i (Android 5.0.2)
* Fenix version: 5/24 (#11440149)

**Comment by vesta0** [comment]
I can't reproduce this. @sv-ohorvath please re-open if the issue persists.

**Comment by vesta0** [comment]
Just saw that it's specific to some devices :)

**Comment by ekager** [comment]
@sv-ohorvath could we retest this? I did fix an issue around 7 days ago related to this issue: https://github.com/mozilla-mobile/fenix/issues/2806

**Comment by sv-ohorvath** [comment]
Cannot reproduce on the 5/30 build..
