### ISSUE TITLE
FNX3-16610 ⁃ [Bug] Collection menu needs to expand when it's at the bottom of the screen

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#2825]
## Steps to reproduce
1. Create a few collections.
1. Open the menu of the bottom one.
    1. Expected behavior
The entire menu is visible.
    1. Actual behavior
Only one or two options are visible, there is no scroll bar visible to indicate there's more.
![Screenshot](https://user-images.githubusercontent.com/4037709/58316397-1ea7ac80-7e1c-11e9-9ce8-2ce39bf11e33.jpg)UNITO-UNDERSCORE!20190524-115808!UNITO-UNDERSCORE!Firefox Preview!

### Device information
* Android device: Sony Xperia Z2 (Android 6.0.1), Note 8 (Android 9)
* Fenix version: build 5/24 (#11440149)

**Comment by sblatz** [comment]
Blocked on: https://github.com/mozilla-mobile/android-components/issues/2916

**Comment by Amejia481** [comment]
@sblatz Could using `orientation = BrowserMenu.Orientation.UP` be an alternative? I achieved this using it.


![Screenshot_20190531-172253](https://user-images.githubusercontent.com/773158/58735590-df9fcb00-83c8-11e9-9467-640e4942f136.png)

**Comment by softvision-miralobontiu** [comment]
Verified as fixed on the latest build 1.0.1923 (#11561806), with Xiaomi Mi 8 Lite (Android 8.1), and Motorola Nexus 6 (Android 7.1.1).
