### ISSUE TITLE
[Tabs Tray Refactor] Refactor the `RemoveTabUseCaseWrapper`functionality to `TabsTrayController`

### ISSUE THREAD

**Issue by MozillaNoah** [mozilla-mobile/fenix#28268]
Meta issue:
- https://github.com/mozilla-mobile/fenix/issues/25722

All/most/some of this was already done as a part of https://github.com/mozilla-mobile/fenix/pull/25895, but is being split out so it can be more safely landed.

Notes for QA: This is a business logic refactor in the tabs tray, so the existing functionality should remain the same. Please validate that no there have been no regressions involving tabs + tabs tray.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-22168)

**Comment by kl3jvi** [comment]
I am taking this 👍🏻

**Comment by MozillaNoah** [comment]
Hi @kl3jvi, thanks for your interest in this and happy new year! I actually already have this issue in-progress and assigned to myself, as this is a part of a [much larger refactor](https://github.com/mozilla-mobile/fenix/issues/25722) that I'm responsible for. Thanks again for your willingness to take this on, and hopefully there's another issue that piques your interest.

**Comment by gabrielluong** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1814223

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
