### ISSUE TITLE
[Tabs Tray Refactor] Refactor the `SelectTabUseCaseWrapper` functionality to `TabsTrayController`

### ISSUE THREAD

**Issue by MozillaNoah** [mozilla-mobile/fenix#28267]
Meta issue:
- https://github.com/mozilla-mobile/fenix/issues/25722

All/most/some of this was already done as a part of https://github.com/mozilla-mobile/fenix/pull/25895, but is being split out so it can be more safely landed.

Notes for QA: This is a business logic refactor in the tabs tray, so the existing functionality should remain the same. Please validate that no there have been no regressions involving tabs + tabs tray.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-22169)

**Comment by gabrielluong** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1814224

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
