### ISSUE TITLE
[Tabs Tray Refactor] Remove `BrowserTrayInteractor` and `BrowserTrayController` and relocate the implemented functions to `TabsTrayInteractor` and `TabsTrayController`

### ISSUE THREAD

**Issue by MozillaNoah** [mozilla-mobile/fenix#28266]
Meta issue:
- https://github.com/mozilla-mobile/fenix/issues/25722

All/most/some of this was already done as a part of https://github.com/mozilla-mobile/fenix/pull/25895, but is being split out so it can be more safely landed.

Notes for QA: This is a business logic refactor in the tabs tray, so the existing functionality should remain the same. Please validate that no there have been no regressions involving tabs in the tabs tray. 

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-22170)

**Comment by delia-pop** [comment]
Verified as fixed on latest Nightly from 01/27 with Google Pixel 6 (Android 13). No regressions were observed.
