### ISSUE TITLE
Allow users to manually reorder private tabs

### ISSUE THREAD

**Issue by KWierso** [mozilla-mobile/fenix#28272]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### What is the user problem or growth opportunity you want to see solved?
Issue #10344 added the ability to drag and drop tabs in the tab tray to reorder them, but it doesn't seem to work for the private tab tray, as mentioned in recent comments in that issue. 

### How do you know that this problem exists today? Why is this important?
I tried to reorder tabs in the private tabs tray, but it didn't work. It's a break in muscle memory between the two tab trays, which could cause some tabs to be accidentally swiped away.

### Who will benefit from it?
Users who want to reorder their private tabs.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-22177)

**Comment by delia-pop** [comment]
Hi, @KWierso , thank you for your suggestion. I will mark this ticket as Feature Request.

**Comment by kbrosnan** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1811307

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
