### ISSUE TITLE
Cannot click&drag, click&hold, zoom, etc when using an otg mouse

### ISSUE THREAD

**Issue by userse31** [mozilla-mobile/fenix#28270]
## Description
I really hope this is the right category. I was thinking "bug report" but this issue feels less like a bug and more an "unattended consequence". Sorry!

Because the one phone I use has a dead digitizer I use it with a mouse.

This is hard to explain but easier to show so heres a like to a video showing it: https://youtu.be/S23t5J58owA

Basically, firefox recognizes that a mouse is being used and accommodates for it, but doesn't do so fully and means usability issues arise.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-22176)

**Comment by Mugurell** [comment]
Thank you for the video! It does show multiple issues.
Since the problems affect the browser experience I'll move the ticket to Bugzilla for more investigation by the GeckoView team.

**Comment by Mugurell** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1806782

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Comment by userse31** [comment]
Thank you
