### ISSUE TITLE
Themes (as implemented on Fennec) are extremely limited

### ISSUE THREAD

**Issue by IdmFoundInHim** [mozilla-mobile/fenix#2827]
From [Bug 1554028](https://bugzilla.mozilla.org/show_bug.cgi?id=1554028)

### Why/User Benefit/User Problem
The theming capabilities for Firefox for Android only allow for two customizations: an image in the background and the colors/frame attribute (which, I believe, changes the color of the notification bar, but the documentation is unclear). I would like to create a minimalistic theme that looks similar to the (old) Private Browsing persona.

### What/Requirements
The following properties need to be implemented:

* Color of the search bar (colors/toolbar_field)
* Color of search bar text (colors/toolbar_field_text)
* Color of icons next to the search bar (colors/icons) (colors/bookmark_text?)

(It may also be worth considering a specific "x_fennec" or "x_android" property for each of these to override the desktop version if desired. This would allow theme creators to distribute the same theme for Firefox and Fennec. On that note...)

The image/theme_frame property should not be required. The color/frame property should fill in any space behind the header that is not occupied by a background image, just as it does on desktop Firefox.

Other properties that I would recommend implementing:

* Color of the horizontal lines above the toolbar and icon tray (colors/toolbar_top_seperator) 
* Color and text color of hamburger menu (colors/popup and colors/popup_text, respectively) 

### Acceptance Criteria
Using the above, I should be able to download and use my [Material Gray](https://addons.mozilla.org/en-US/firefox/addon/material-gray-purple/) theme on Fenix. It would have a gray background on the UI elements and white icons/text, and separator lines would disappear/blend in with the other elements. 

Feel free to ask questions.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-11710)

**Comment by kbrosnan** [comment]
This has not revived any duplicates or other interactions since it was filed. We will not be moving this request to Bugzilla. The Material You issues/bugs are more relevant.
