### ISSUE TITLE
[Bug] Unified search: First homescreen search does not properly differentiate between search engines

### ISSUE THREAD

**Issue by Mugurell** [mozilla-mobile/fenix#28273]
Steps to reproduce:
- have unified search enabled
- have the homescreen showing
- tap on the unified search selector to choose a different search engine
- choose any other than the default (easier to see the issue with application engines like tabs/bookmarks/history)

Expected result:
- the next search show results particular to that search engine

Actual result:
- the next search shows are not correctly filtered

Issues affects all app versions.

Video showing the initially incorrect search results and then the expected search results after circling through search engines:

https://user-images.githubusercontent.com/11428869/208849770-10966532-5207-440b-8e10-25aba61c9edd.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-22178)

**Comment by SoftVision-LorandJanos** [comment]
This issue is no longer reproducible on the latest Nightly 110.0a1 (2022-12-24) build.
Device used: Oppo Find X5 (Android 12).
Closing the ticket as verified.
