### ISSUE TITLE
[Telemetry] Add telemetry for Form Data failures

### ISSUE THREAD

**Issue by calumozilla** [mozilla-mobile/fenix#28280]
Add telemetry events to know when Form Data action fails due to `ontentAction.CheckForFormDataExceptionAction`

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-22180)

**Comment by calumozilla** [comment]
### Request for data collection review form

All questions are mandatory. You must receive review from a data steward peer on your responses to these questions before shipping new data collection.

1. What questions will you answer with this data?
- This data will help us understand when form data failures occur.

2. Why does Mozilla need to answer these questions? Are there benefits for users? Do we need this information to address product or business requirements?
- Setting tab priority based on form data is new and any failures will help the engineers understand why Geckoview is unable to retrieve whether or not there is form data on a tab. The data will help make product decisions based on how often the failure happens.

3. What alternative methods did you consider to answer these questions? Why were they not sufficient?
- No other alternatives considered.

4. Can current instrumentation answer these questions?
- No

5. List all proposed measurements and indicate the category of data collection for each measurement, using the Firefox data collection categories found on the Mozilla wiki. Note that the data steward reviewing your request will characterize your data collection based on the highest (and most sensitive) category.


| Measurement Description  | Data Collection Category | Tracking Bug # |
| --------------------------- | ------------------------ | ---------------- |
| Form data failure: An event where the data of whether or not a tab has form data could not be collected and failed. | Category 1 - technical data | #28280 |

6. Please provide a link to the documentation for this data collection which describes the ultimate data set in a public, complete, and accurate way.
- https://dictionary.telemetry.mozilla.org/apps/fenix

7. How long will this data be collected? Choose one of the following:
- Until release version 122 with the option to renew at that point.

8. What populations will you measure?

- All channels, all locales, all countries 

9. If this data collection is default on, what is the opt-out mechanism for users?

- Default Glean SDK opt-out mechanism. 

10. Please provide a general description of how you will analyze this data.

- Glean and Amplitude. 

11. Where do you intend to share the results of your analysis?

- Only on Glean, Amplitude, and with mobile teams. 

12. Is there a third-party tool (i.e. not Telemetry) that you are proposing to use for this data collection?

- No third-party tools.

**Comment by Amejia481** [comment]
I think we normally add the data collection form as part of the PR ([example](https://github.com/mozilla-mobile/fenix/pull/27978#issuecomment-1327893828)), after adding the comment with the form, we ping @rocketsroger for data review which is our data steward  :)

**Comment by calumozilla** [comment]
> I think we normally add the data collection form as part of the PR ([example](https://github.com/mozilla-mobile/fenix/pull/27978#issuecomment-1327893828)), after adding the comment with the form, we ping @rocketsroger for data review which is our data steward :)

Ah okay thanks!

**Comment by Amejia481** [comment]
Glad to help!

**Comment by calumozilla** [comment]
Fenix bug on Bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1809937

**Comment by jonalmeida** [comment]
Closing as moved (see above).
