### ISSUE TITLE
I want an way to side load addons in stable version

### ISSUE THREAD

**Issue by MyBlueHorizon** [mozilla-mobile/fenix#28288]
### What is the user problem or growth opportunity you want to see solved?
side load addons in stable version
### How do you know that this problem exists today? Why is this important?
In some country, some addons couldn't be add from the "Addons Pages" successfully.
In desktop, I can download and install it from Github. However, I can do nothing because the limit.
### Who will benefit from it?
Users and developers

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-22183)

**Comment by sheikh-azharuddin** [comment]
Move to nightly or beta..they will never add to stable

**Comment by vehosah** [comment]
Or better yet, move to fennec f-droid

**Comment by vehosah** [comment]
And I'm wondering why they still didn't closed it yet :)

**Comment by vehosah** [comment]
It seems that someone doesn't want to have add-ons on stable 😂😂

**Comment by kbrosnan** [comment]
Duplicate https://github.com/mozilla-mobile/fenix/issues/11292

**Comment by vehosah** [comment]
@cadeyrn what's your damn exactly with the extensions and you downvote everything that has to do with them :)
