### ISSUE TITLE
Gate growth data by network instead of campaign

### ISSUE THREAD

**Issue by MatthewTighe** [mozilla-mobile/fenix#28283]
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-22181)

**Comment by gabrielluong** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1815630

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
