### ISSUE TITLE
 [UITests] Track ignored tests from #28112

### ISSUE THREAD

**Issue by DreVla** [mozilla-mobile/fenix#28293]
In https://github.com/mozilla-mobile/fenix/pull/28112 we disabled a failing test after changing the behavior of the default search engine list in settings. The new behavior does not allow deletion of the last general or custom search engine.

Failing test is `deleteAllSearchEnginesTest()` and was ignored with:
`@Ignore("Test failure caused by: https://github.com/mozilla-mobile/fenix/issues/28111")`

cc @AndiAJ @sv-ohorvath

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-22186)

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807298

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
