### ISSUE TITLE
Firefox always crashes on Bluestack Android Pie

### ISSUE THREAD

**Issue by Palloxin** [mozilla-mobile/fenix#28291]
### Steps to reproduce

just install and open firefox on Bluestack (very popular android emulator). The istance has android pie. After a few seconds firefox will crash by itself by doing nothing.

### Expected behaviour

not crash

### Actual behaviour

crashes for no reason or action i made since i did nothing (just opening it)

### Device name

Bluestack 5.10 

### Android version

Android 9

### Firefox release type

Firefox

### Firefox version

108

### Device logs

I would like to get them but the app crashes before i get them so too fast

### Additional information

If you have questions just ask me, i am avaiable

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-22184)

**Comment by csadilek** [comment]
I would be super helpful if you (or anyone who can reproduce this) could get as logs via adb: https://github.com/mozilla-mobile/fenix/wiki/Logging-Crash-Information#using-adb-logcat-to-get-crash-information.

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812365

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
