### ISSUE TITLE
[Breakdown Eng] Adjust SDK

### ISSUE THREAD

**Issue by bbinto** [mozilla-mobile/fenix#283]
Breakdown: https://github.com/mozilla-mobile/fenix/issues/106

**Comment by colintheshots** [comment]
It was a very simple breakdown as we're not using Adjust for telemetry.

**Comment by bbinto** [comment]
@colintheshots - we will use Adjust for campaign tracking and therefore this is a requirement for launch. Please work with @lwa-moz to get credentials, staging IDs etc.
