### ISSUE TITLE
Add Paste,Copy,Cut Functions In Search Bar

### ISSUE THREAD

**Issue by iSmokeMid69** [mozilla-mobile/fenix#28309]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### What is the user problem or growth opportunity you want to see solved?
![Screenshot_2022-12-25-01-46-34-501_com android chrome](https://user-images.githubusercontent.com/112684643/209449410-46dcfa11-c582-4968-8482-5ee87236bf57.jpg)

I Am Tired Of Long Pressing On Link To Copy,Paste Links This Feature Of Chrome Would Be Great For FireFox Too

### Who will benefit from it?
EveryOne

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-22193)

**Comment by delia-pop** [comment]
Hi, @iSmokeMid69 , thank for submitting this. Please note that this feature was previously requested in https://github.com/mozilla-mobile/fenix/issues/5152, where you can follow up on the topic. I will close this ticket as duplicate.
