### ISSUE TITLE
Decouple clearing site data from clearing history

### ISSUE THREAD

**Issue by mailinglists35** [mozilla-mobile/fenix#28314]
Cannot clear site data without losing history.

Abandoning firefox on Android because of this.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-22196)

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812955

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
