### ISSUE TITLE
[Bug]: Firefox for Android does not recognize literal IPv6 addresses

### ISSUE THREAD

**Issue by lm1baker** [mozilla-mobile/fenix#28315]
### Steps to reproduce

1. Open a new tab
2. Type an IPv6 address enclosed by []
  e.g. http://[2001:470:1:18::115]
4. press "go"/"enter"/"return"
5. see that you are directed to a search engine query.

1. Open a new tab
2. Type an IPv6 address without formatting
e.g. 2001:470:1:18::115
3. press "go"/"enter"/"return"
4. See an error page
Invalid Address

The provided address is not in a recognised format. Please check the location bar for mistakes and try again.

### Expected behaviour

Firefox should recognize a correctly formatted IPv6 address and attempt to contact the server.

### Actual behaviour

Firefox sends the correctly formatted string to a search engine.

### Device name

LG v30+

### Android version

Android 10

### Firefox release type

Firefox

### Firefox version

108.1.0

### Additional information

Firefox should understand IPv6 addresses per RFC 3986 https://www.ietf.org/rfc/rfc3986.txt Firefox desktop does understand them, so this appears to be a bug/regression in Firefox for Android.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-22197)

**Comment by cpeterso** [comment]
Thanks for reporting this bug. I think this is the same as https://github.com/mozilla-mobile/fenix/issues/4343.
