### ISSUE TITLE
[Bug]: [Experiment] Engagement notification is not triggered on specific devices until the Firefox app is opened 

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [mozilla-mobile/fenix#28328]
### Steps to reproduce

1. Install Firefox Beta 109.0b3 and open it.
2. Navigate to the secret menu (Settings -> About Firefox Beta -> Tap logo 5 times).
3. Tap the `Android Reengagement Notifications` experiment and ensure that the treatment branch is checked.
4. Fully close the app and then `Force close` the app.
5. Move the system date to 2 days into the future.
6. Wait 15-30s and observe the behavior.

### Expected behaviour

- A Firefox Notification is trigger and is displayed in the notifications tray.

### Actual behaviour

- No notification is triggered.

### Device name

OnePlus 5, OnePlus 6T, OnePlus 9 Pro

### Android version

Android 10, Android 11, Android 13

### Firefox release type

Firefox Beta

### Firefox version

109.0b3

### Additional information

- The notification is only displayed when Firefox is opened.
- The notification is also displayed if the user has used the app after 24h of starting it.
- The issue is NOT reproducible on the following devices: 
  - Motorola g(10), Android 11
  -  Google Pixel 2 XL, Android 11
  - Samsung S9, Android 10
  - LG K8 (2017), Android 7.0

- Attached a screen recording of the issue:
https://user-images.githubusercontent.com/18304511/209819889-7d7ebd32-33d3-4132-bac2-e2fe285d7b11.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-22204)

**Comment by rocketsroger** [comment]
This is only reproducible on OnePlus devices?  And consistently reproducible on all OnePlus devices?

**Comment by SoftVision-CiprianMuresan** [comment]
As far as we can tell, yes, this is consistently reproducible on the OnePlus devices we had available. Are there any logs I can add here that would help debug the issue?

**Comment by rocketsroger** [comment]
> As far as we can tell, yes, this is consistently reproducible on the OnePlus devices we had available. Are there any logs I can add here that would help debug the issue?

Unfortunately, no.  Workmanager behaviour is an OS behaviour that supposed to work the same across most devices.  It could be that on One Plus devices, moving system time doesn't work as well for testing.  Can we try after moving time 2 days into the future, open another app? (Not Fenix).  Or move time into 3-4 days into the future?  Thanks

**Comment by SoftVision-CiprianMuresan** [comment]
Sorry for taking so long to reply, I was on New Year holiday. 

Moving 2 days in the future and then opening a different app doesn't make the notification to appear.
Moving the device to an additional day (3rd), and then another (4th) didn't make the notification appear.

Other notifications:
- Google Calendar triggered as expected even with the date change
- Communication apps such as Slack and Skype successfully displayed notifications

I'll set up a OnePlus device and wait the 2 days naturally to see if the notification works that way.

**Comment by heres-maria** [comment]
I can reproduce the issue on Samsung Galaxy S8 - Android 9 using Firefox Beta109.0b4 and a local 109.0 Release build (d225be269+).

**Comment by SoftVision-CiprianMuresan** [comment]
@rocketsroger I have some good news. The notification was successfully displayed on my OnePlus 5 device that I had set up. I'll coordinate with Maria to set up the phone that she used and Carmen has one that should be getting the notification tomorrow.

**Comment by SoftVision-CiprianMuresan** [comment]
@rocketsroger It looks like we have a separate issue with some devices when closing the app (by swiping up from the recent apps drawer) and waiting 2 days. I'll close this out as it was specifically logged to OnePlus devices with time traveling and the scenario is not reproducible naturally. 
Carmen logged [a separate issue](https://github.com/mozilla-mobile/fenix/issues/28459) for the natural scenario.
