### ISSUE TITLE
Consume upstream CFRPopupFullscreenLayout

### ISSUE THREAD

**Issue by gabrielluong** [mozilla-mobile/fenix#28324]
Now that we have upstream [CFRPopupFullscreenLayout](https://searchfox.org/mozilla-mobile/source/firefox-android/android-components/components/compose/cfr/src/main/java/mozilla/components/compose/cfr/CFRPopupFullscreenLayout.kt) to AC. We should deprecate and migrate away from using Fenix's [CFRPopupFullscreenLayout](https://searchfox.org/mozilla-mobile/source/fenix/app/src/main/java/org/mozilla/fenix/compose/cfr/CFRPopupFullscreenLayout.kt). We saw issues from using `GeckoOrientation` in Fenix, but this has been mitigated in AC where it introduced its own system orientation helper.  See https://mozilla.slack.com/archives/CKM7DLL67/p1672157172991059

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-22201)

**Comment by gabrielluong** [comment]
The QA ask here is to retest the CFRs for Onboarding, Home screen and TCP since this is now using AC's CFR implementation which varied a little from the Fenix implementation that it was originally tested in. Thank you!

**Comment by cpeterso** [comment]
@gabrielluong We'll probably ship TCP and its CFR in Fenix 112 (March 14 release date). Would your changes in this issue have an impact on the TCP CFR's UX? Should we try to land your changes before we ship the TCP CFR?

**Comment by gabrielluong** [comment]
> @gabrielluong We'll probably ship TCP and its CFR in Fenix 112 (March 14 release date). Would your changes in this issue have an impact on the TCP CFR's UX? Should we try to land your changes before we ship the TCP CFR?

It shouldn't have any impact.

**Comment by gabrielluong** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1814232

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Comment by delia-pop** [comment]
Removing the QA needed label here since the ticket is opened in Bugzilla.
