### ISSUE TITLE
Refactor Onboarding to use NavHost

### ISSUE THREAD

**Issue by gabrielluong** [mozilla-mobile/fenix#28330]
In https://searchfox.org/mozilla-mobile/source/fenix/app/src/main/java/org/mozilla/fenix/onboarding/view/Onboarding.kt, we are maintaining 2 states to display various content when we should really be assuming each of the views as a separate screen. We can achieve this by using [NavHost](https://developer.android.com/jetpack/compose/navigation#create-navhost).

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-22205)

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812458

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
