### ISSUE TITLE
Deleted bookmarks keep showing on suggestions

### ISSUE THREAD

**Issue by LendrickKamar** [mozilla-mobile/fenix#28346]
### Steps to reproduce

1. Bookmark a page.
2. Website will appear in your suggested URLs.
3. Remove the bookmark.
4. Website will remain in your suggested URLs, even if no browser history or bookmark of it exists.

### Expected behaviour

Search bar should no longer suggest the website if no history or bookmark of it exists.

### Actual behaviour

Deleted bookmarks keep showing on the search bar suggestions even after deleting browser history and site data.

### Device name

Pocophone F1

### Android version

Android 11

### Firefox release type

Firefox Beta

### Firefox version

109.0b4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-22208)

**Comment by AdinaPetridean** [comment]
Hello @LendrickKamar , thank you for submitting the issue.
I was able to reproduce it on Firefox 109.0b4 and the latest Nightly (110.0a1 from 01/03).

Device Used: Motorola Moto G9 plus 
Android Version: 11

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812700

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
