### ISSUE TITLE
[Bug]: 'Customize homepage' button is missing on homepage when only Shortcuts are enabled

### ISSUE THREAD

**Issue by ris58h** [mozilla-mobile/fenix#28341]
### Steps to reproduce

1. Enable only Shortcuts in homepage settings (Jump back in, Recent bookmarks, Recently visited must be disabled).
2. Open homepage. 

### Expected behaviour

'Customize homepage' button should appear under homepage content. 

### Actual behaviour

No 'Customize homepage' button is present.

### Android version

Android 11

### Firefox release type

Firefox

### Firefox version

108

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-22206)

**Comment by amocirean** [comment]
Hello @ris58h , thank you for submitting the issue.
I was able to reproduce the issue on the latest Nightly (110.0a1) from 03.01.2023 build.
Tested on: Samsung Galaxy S22 Ultra (Android 13), Huawei P40 Lite (Android 10).
Thanks!

**Comment by ris58h** [comment]
@amocirean could you elaborate more on why it's not planned? Was it a decision of UX team to make it inconsistent with other homepage blocks?

**Comment by amocirean** [comment]
@ris58h this is the behaviour that is expected from Firefox for Android, ar per https://github.com/mozilla-mobile/fenix/issues/21662#issuecomment-933537051) .

**Comment by ris58h** [comment]
@amocirean thank you!
