### ISSUE TITLE
Enable biometric authentication per session on iOS/Android

### ISSUE THREAD

**Issue by dromatriptan** [mozilla-mobile/fenix#28349]
Similar feature request to  #14428 - this has been a feature request since August, 2020. I read through much of these threads and it's clear to me that Mozilla Firefox developers for Android and iOS are failing to understand the request.

What we are looking for is simple: trigger the mobile operating systems' default biometric authentication mechanism(s) when a Firefox sync login is about to be leveraged on some website form.

We understand that the passwords are safely encrypted and also protected from viewing, but we need these authentication mechanisms triggers to prohibit usage of these cached credentials within web forms.

Most engineered hacks aren't privy to the passwords themselves, but merely leverage hashes and credentials stored in memory, within a session, or abuse existing privileged tokens contained within a user account.

I've been a faithful Mozilla patron for years and I would like for this feature request to be taken seriously. Dismiss this request, by closing it, and I withdraw my support. This is a simple request from someone that has been an avid supporter since the code base was known as Netscape and before Mozilla switched to Matrix 🤓

If you need development support, IT advice, hit me up. I'll gladly be a part of the solution.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-22209)

**Comment by Rexogamer** [comment]
I do want to point out that the issue in question wasn't closed as declined, but was simply moved to Bugzilla (where it remains open)

**Comment by dromatriptan** [comment]
Oh, can you post the bugillza thread here? I'd like to review it.

**Comment by cadeyrn** [comment]
> Dismiss this request, by closing it, and I withdraw my support

Extortion as an argument? Sorry, that's not helpful…

> Oh, can you post the bugillza thread here? I'd like to review it.

See the last comment of #14428:

https://bugzilla.mozilla.org/show_bug.cgi?id=1807454
