### ISSUE TITLE
[BUG] change RTL/LTR languages doesn't update the UI until new launch

### ISSUE THREAD

**Issue by mavduevskiy** [mozilla-mobile/fenix#28342]
Issue that was mentioned [here](https://github.com/mozilla-mobile/fenix/issues/21306#issuecomment-1101778924).

`Switching from an RTL to an LTR locale (or vice versa) doesn't update the UI direction without restarting Fenix first`

### Steps to reproduce

Go to language screen and change the language to a language with the opposite direction from the one you are currently using.

### Expected behaviour

The layout of the app will change to accommodate the direction of the set language.
### Actual behaviour

The direction of the layout keeps the same until relaunching the app.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-22207)

**Comment by delia-pop** [comment]
Verified as fixed on Nightly 111.0a1 from 01/20 with Xiaomi 12 Pro (Android 13). The UI changes accordingly after switching between RTL/LTR languages. 

https://user-images.githubusercontent.com/89388888/213715061-4cbeec2c-5dca-40bc-bc04-73696ce533ec.mp4
