### ISSUE TITLE
[webcontent] WordPress.com/read not working

### ISSUE THREAD

**Issue by evilsoup** [mozilla-mobile/fenix#28355]
### Expected behavior

WordPress.com/read is an RSS feed aggregator. When logged in to WordPress.com, it should show a reverse-chronological list of posts from subscribed sites.

### Actual behavior

The site currently shows some placeholder blocks and an error. Googling the exact wording of the error doesn't bring up anything useful.

![Screenshot_20221231-095916](https://user-images.githubusercontent.com/1566658/210132564-0aae754d-415b-4412-88fe-1ec0032f7c27.png)

### Does toggling Tracking Protection fix the issue? (Press the shield icon in the toolbar while on the site to see toggle)

No. Neither does disabling add-ons (unlock origin & privacy badger)

### Can you reproduce in Chrome (or other non-Mozilla browser)?

No. The site works perfectly in Chrome on Android.

### Device information

* Android device: Moto g7 Power, android version 10
* Fenix version: 108.1.0 (last updated 8 dec 22)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-22211)

**Comment by amocirean** [comment]
Hello @evilsoup , thank you for submitting the issue.
I was not able to reproduce the issue on the latest Nightly (110.0a1) from 03.01.2023, latest Beta (109.0b4) or latest RC (108.1.1) builds.
Could you please tell us if the issue is still reproducible on the latest Nightly?
Tested on: Samsung Galaxy S22 Ultra (Android 13), Huawei P40 Lite (Android 10).
Thanks!

**Comment by evilsoup** [comment]
The website works perfectly in Firefox Nightly from the Google Play store. I'm still getting the same issue with my main firefox mobile (108.1.0). I guess I'll just have to wait for the update to 108.1.1 to reach my phone, I'll report back when I can confirm if this fixes the issue.

**Comment by evilsoup** [comment]
Firefox mobile is now on version 108.2.0 (Build #2015925643)and this site is still not working.

Strangely, it works fine if I go through a private browser tab and log in to my wordpress account.

**Comment by evilsoup** [comment]
By

**Comment by evilsoup** [comment]
Having uninstalled and reinstalled, including reinstalling the three add-ons I use on mobile (ublock origin, privacy badger, and video background play fix), and setting tracking protection to "strict", I now cannot recreate this error. Reinstalling fixed the problem for me.
