### ISSUE TITLE
Add Ctrl-L keyboard shortcut to go to address bar, like desktop firefox

### ISSUE THREAD

**Issue by stuaxo** [mozilla-mobile/fenix#28354]
On Android firefox on Planet computers astro slide Ctrl-L doesn't seem to focus the addess bar.

(I also couldn't seem to get to the address bar only using tab)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-22210)

**Comment by delia-pop** [comment]
Hi, @stuaxo , thanks for your suggestion. Please note that this was already requested in https://github.com/mozilla-mobile/fenix/issues/3729#issuecomment-559168316. 
I will close this ticket as duplicate.

**Comment by stuaxo** [comment]
Thanks
