### ISSUE TITLE
FNX3-16618 ⁃ [Bug] Quickly Deleting bookmarks -> Crash

### ISSUE THREAD

**Issue by jdragojevic** [mozilla-mobile/fenix#2835]
## Steps to reproduce
1. Visit your bookmarks list.
1. Quickly start selecting and deleting bookmarks 1x1
1. Repeat until crash

### Expected behavior
No crash - items deleted

### Actual behavior
As I was deleting the bookmarks the UI was a bit _janky_. Item I had deleted would briefly reappear as I was deleting them.  (Again, I was moving fast).  It made me uncertain whether or not items were being deleted.

### Device information
Sentry: https://sentry.prod.mozaws.net/operations/fenix/issues/5820642/events/30442889/

* Android device: Samsung S4 Tab
* Fenix version: 2019-05-24 nightly build 1.0.1921

**Comment by grigoryk** [comment]
I can't seem to replicate the crash, but the "janky" behaviour you're describing is certainly there.

Specifically, what I'm observing is:
- when deleting a bookmark, previously deleted bookmarks re-appear while the "undo toast" is visible. then they disappear again.

Looking at the code, it's not obvious why that'd happen; so, need to look a bit closer :)

**Comment by grigoryk** [comment]
Ah, didn't see the crash log. Yup, this may happen; deletions are ran in coroutines, no guarantee for fragment still being attached at the point those operations try to access `context`.

**Comment by grigoryk** [comment]
Patch is for a crash; filed a follow-up for the janky deletions: https://github.com/mozilla-mobile/fenix/issues/2960

**Comment by grigoryk** [comment]
@ekager my apologies, didn't see you were assigned to this!
