### ISSUE TITLE
[Experiment] The title of the Android Reengagment Notification is hard to read on dark themes

### ISSUE THREAD

**Issue by heres-maria** [mozilla-mobile/fenix#28369]
**[Affected Versions]:**
- Firefox 109.0 (Build #2015925331), d225be269+, AC: 109.0b4, 08153e16aa GV: 109.0-20221227225153, AS: 96.1.3 ([custom/local release build](https://drive.google.com/file/d/1xi7MhijG4OxFQXhvSln5a028FrWdAFSm/view?usp=sharing))
- [Firefox Beta 109.0b4](https://github.com/mozilla-mobile/fenix/releases/tag/v109.0b4) (Build #2015924275), 085aa77bd+ AC: 109.0ab4, 08153e16aa, GV: 109.0-20221227225153, AS: 96.1.3

**[Affected Platforms]:**
- Android 9 (Samsung Galaxy S8)

**[Prerequisites]:**
- Have the device set to a dark theme (e.g. have Settings > Display > Night mode enabled).

**[Steps to reproduce]:**
1. Open the build for the first time.
2. Navigate to the secret menu (Settings -> About Firefox (/Beta) -> Tap logo 5 times and then Settings > Nimbus Experiments).
3. Verify that the "treatment-notification" branch of the Android Reengagment Notifications (/Release) experiment is checked.
4. If it is not checked, tap the branch.
5. Close the app.
6. Move the system date to 2 days into the future.
7. Wait 15-30s and observe the notification received.

**[Expected result]:**
- The title of the notification uses a font color that is easy to read on dark backgrounds.

**[Actual result]:**
- The title of the notification uses a purple color that is hard to read on the dark background.

**[Notes]:**
- The issue is not reproducible for the light theme font color.
- Attached is a recording of the issue.

https://user-images.githubusercontent.com/53752296/210344496-61a64bb3-97da-4b51-8ee4-e4ab092a954d.mov

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-22217)

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812953

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
