### ISSUE TITLE
add an Android shortcut to go straight to the login and passwords page

### ISSUE THREAD

**Issue by datapaganism** [mozilla-mobile/fenix#28361]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### What is the user problem or growth opportunity you want to see solved?
It takes too long for a user to get their passwords and login by needing to hunt it down in a menu, a shortcut or a widget to the function would speed this up greatly 
### How do you know that this problem exists today? Why is this important?
Everyday I have to check passwords and have to keep going through the same steps when a single press from my homwscreen would suffice
### Who will benefit from it?
Everyone using FF as their password manager

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-22214)

**Comment by delia-pop** [comment]
Hi, @datapaganism , thank you for your suggestion. I will mark this ticket as a feature request.

**Comment by hmncube** [comment]
@datapaganism @delia-pop Are there any designs available for the widget icon? I would like to work on this issue.

**Comment by hmncube** [comment]
@datapaganism tried to use the `ic_lock` icon but it's not getting displayed. The issue is with the icon. We need one explicitly designed for this. Any idea how we can get that done?

![image](https://user-images.githubusercontent.com/2725300/212247200-04e97d98-4298-47c8-b61b-9b2717a2b3d8.png)

**Comment by datapaganism** [comment]
I'm sorry, I am not an android developer, so I don't know the intricacies,
hopefully you can get it work without the icon for the time being.

**Comment by jonalmeida** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1810629

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
