### ISSUE TITLE
网页返回重新载入问题

### ISSUE THREAD

**Issue by 90du** [mozilla-mobile/fenix#28379]
能不能搞一个开关，几分钟之内网页返回不用重新载入，现在返回一直重新载入很是浪费时间浪费流量啊

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-22222)

**Comment by csadilek** [comment]
This seems to be about pages reloading and providing a way to stop that. You can track progress on this issue here where we're investigating various reasons of unwanted tab reloads: https://bugzilla.mozilla.org/show_bug.cgi?id=1752594.
