### ISSUE TITLE
[Bug]: Firefox for Android crashes on Vodafone's speedtest page

### ISSUE THREAD

**Issue by GiantCrocodile** [mozilla-mobile/fenix#28377]
### Steps to reproduce

1. Go to https://speedtest.vodafone.de/ in Firefox's private mode on your Android smartphone
2. Execute a speedtest
3. Firefox just closes (looks like crashed; about:crashes shows no recent crash report)

### Expected behaviour

Speedtest is properly executed

### Actual behaviour

Firefox becomes a black window and closes/crashes

### Device name

Huawei P30 Pro

### Android version

11

### Firefox release type

Firefox

### Firefox version

108.1.1 (Build #2015922907)

### Device logs

No crash dump is written/created.

### Additional information

See #23307, was reported back then and still happens.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-22221)

**Comment by amocirean** [comment]
Hello @GiantCrocodile , thank you for submitting the issue.
I was not able to reproduce the issue on the latest Firefox Nightly from 11th of January (110.0a1). Could you please try to reproduce the issue on the latest Nightly and send a video if the issue is still occuring on your side? Thanks!

Devices used: Google Pixel 6 (Android 13), Samsung Galaxy S22 Ultra (Android 13), Huawei P40 Lite (Android 10), Oppo Find X3 Neo (Android 11).

**Comment by shamilovstas** [comment]
I also have this issue OnePlus 6T (Android 11). There is no crash logs in the adb, however these are the logs that are coming last before the app closes:
````2023-01-16 17:50:47.330 25786-25786 MemoryController        org.mozilla.fenix                    I  onTrimMemory(5)
2023-01-16 17:50:47.330 25786-25786 FenixApplication        org.mozilla.fenix                    I  onTrimMemory(), level=5, main=true
2023-01-16 17:50:47.680 25786-25786 MemoryController        org.mozilla.fenix                    I  onTrimMemory(10)
2023-01-16 17:50:47.680 25786-25786 FenixApplication        org.mozilla.fenix                    I  onTrimMemory(), level=10, main=true
2023-01-16 17:50:47.713 25786-25786 MemoryController        org.mozilla.fenix                    I  onTrimMemory(15)
2023-01-16 17:50:47.713 25786-25786 FenixApplication        org.mozilla.fenix                    I  onTrimMemory(), level=15, main=true
````

**Comment by GiantCrocodile** [comment]
> Hello @GiantCrocodile , thank you for submitting the issue. I was not able to reproduce the issue on the latest Firefox Nightly from 11th of January (110.0a1). Could you please try to reproduce the issue on the latest Nightly and send a video if the issue is still occuring on your side? Thanks!

I have no access to nightly builds on my mobile phone. I just tested this again: I face the same issue with 108.2.0 as well. Can you check whether it makes a difference for you when you try to use Private Browsing mode or when Adblock Plus is active?

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812952

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Comment by cpeterso** [comment]
@GiantCrocodile and @shamilovstas - Can you please share your Firefox's `about:support` information in the new Bugzilla bug? This bug sounds like an out of memory crash.

The Firefox Android team is moving bug tracking from GitHub to Bugzilla.

https://bugzilla.mozilla.org/show_bug.cgi?id=1812952

**Comment by GiantCrocodile** [comment]
@cpeterso Done. FYI: During uploading the file to your bugtracker at Mozillas side, I got some technical error complaining about some key not available/being not correct and thus having issues with upload. Contradicting to that message, the upload was done twice after I did it manually again so now it's there two times . . .
