### ISSUE TITLE
Setting address bar to not hide on scroll creates a blank space on installed pwa

### ISSUE THREAD

**Issue by nanaya** [mozilla-mobile/fenix#28378]
### Steps to reproduce

1. "install" a web page
2. disable hide address bar on scroll, position address bar at the top
3. open the installed web page

### Expected behaviour

full screen app

### Actual behaviour

almost full screen app with blank space sitting pretty at the top

![Screenshot_20230104-030958_Firefox_Nightly](https://user-images.githubusercontent.com/276295/210416050-d8e450ae-88c0-4a36-a0e1-697a34bbb404.jpg)

### Device name

asus Zenfone 9

### Android version

12

### Firefox release type

Firefox Nightly

### Firefox version

110.0a1

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-22220)

**Comment by nanaya** [comment]
apparently this doesn't happen if the address bar is positioned at the bottom

**Comment by SoftVision-LorandJanos** [comment]
Hi @nanaya, thanks for your report!
I managed to reproduce the issue on the latest Nightly 110.0a1 (2023-01-09).
Device used: Oppo Find X5 (Android 12).

**Comment by gabrielluong** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1815633

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
