### ISSUE TITLE
FNX3-16620 ⁃ [Bug] Inconsistent capitalization on settings page

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#2837]
On the settings page we sometimes capitalize each word and sometimes only capitalize the first word. We should be consistent:

![](https://user-images.githubusercontent.com/4400286/58348329-3e87a200-7e15-11e9-98e2-b33f730510ad.png)

**Comment by vesta0** [comment]
@mheubusch please add your recommendation and set UX priority :)

**Comment by mheubusch** [comment]
I am not sure why these are still appearing - the capitalization is correct (Tracking Protection is a feature name that we have traditionally capitalized and Firefox Preview and Google Play Store  are trademarks) but these don't match the designs - I can file a separate bug

**Comment by mheubusch** [comment]
Closing since capitalization is correct
