### ISSUE TITLE
Fenix not appearing on iOS devices

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla-mobile/fenix#2838]
## Steps to reproduce
1. Sign in to FxA.Sync on Fenix and iOS
1. On iOS view send tab from inside or outside Firefox

### Expected behavior
* Fenix appears

### Actual behavior
* Fenix does not appear

### Device information
* iPhone SE and Nexus
* Fenix version: today's
![IMG](https://user-images.githubusercontent.com/68213/58348363-86ff8980-7e2e-11e9-8a0d-2a32322be840.jpeg)UNITO-UNDERSCORE!30C1E2DC4BDE-1!

**Comment by jonalmeida** [comment]
I'm adding the a-s label since this is dependent on that.

**Comment by jonalmeida** [comment]
@jdragojevic do we want to close this and open an issue on iOS instead? I don't believe there's any work for us to do here.

**Comment by jdragojevic** [comment]
Let me try to reproduce, @jonalmeida

**Comment by sblatz** [comment]
@jdragojevic any updates? :)

**Comment by jdragojevic** [comment]
![image](https://user-images.githubusercontent.com/299270/61330124-ec4b7780-a7ec-11e9-9c3c-0f786ee26465.png)


I've got Fenix devices in iOS - guessing maybe a recent change to https://github.com/mozilla/application-services/issues/1125 resolved this.

**Comment by jonalmeida** [comment]
Closing this issue since there's nothing for our QA to test here. Thanks Janet! ✨
