### ISSUE TITLE
YouTube shortcut icon outdated

### ISSUE THREAD

**Issue by sheikh-azharuddin** [mozilla-mobile/fenix#28387]
### Steps to reproduce

In other browsers the YouTube shortcut icon is new one whereas in firefox it is still picking the old one.

### Expected behaviour

Should use latest icon

### Actual behaviour

Picking old icon

### Device name

Poco f4

### Android version

Android 12

### Firefox release type

Firefox Nightly

### Firefox version

latest

### Additional information

![Screenshot_2023-01-04-10-10-22-312-edit_com chrome canary](https://user-images.githubusercontent.com/58127841/210485762-cafcaa43-099d-4040-bcee-1338b8eff877.jpg)
![Screenshot_2023-01-04-10-10-35-784-edit_org mozilla fenix](https://user-images.githubusercontent.com/58127841/210485769-bf305813-649f-460d-8939-10259a5221a4.jpg)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-22223)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812831

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
