### ISSUE TITLE
Got a NullPointerException when using QR code scanning

### ISSUE THREAD

**Issue by Kobayashi-996** [mozilla-mobile/fenix#28389]
### Steps to reproduce

Tried but didn't know how to reproduce.
I remember that this happened when using QR code scanning below "Sync and save your data".
I saved the logcat output and hope it could help.

### Expected behaviour

Normal operation.

### Actual behaviour

Suddenly crashed.

### Device name

Google Pixel 2

### Android version

Android 9.0

### Firefox release type

Firefox Nightly

### Firefox version

110a1

### Device logs

01-04 08:28:28.220 13343 32405 E AndroidRuntime: FATAL EXCEPTION: CameraBackground
01-04 08:28:28.220 13343 32405 E AndroidRuntime: Process: org.mozilla.fenix, PID: 13343
01-04 08:28:28.220 13343 32405 E AndroidRuntime: java.lang.NullPointerException: null cannot be cast to non-null type android.view.Surface
01-04 08:28:28.220 13343 32405 E AndroidRuntime: 	at mozilla.components.feature.qr.QrFragment$createCameraPreviewSession$1.invoke(QrFragment.kt:531)
01-04 08:28:28.220 13343 32405 E AndroidRuntime: 	at mozilla.components.feature.qr.QrFragment$createCameraPreviewSession$1.invoke(QrFragment.kt:528)
01-04 08:28:28.220 13343 32405 E AndroidRuntime: 	at mozilla.components.feature.qr.QrFragment.handleCaptureException(QrFragment.kt:596)
01-04 08:28:28.220 13343 32405 E AndroidRuntime: 	at mozilla.components.feature.qr.QrFragment.createCameraPreviewSession$feature_qr_release(QrFragment.kt:528)
01-04 08:28:28.220 13343 32405 E AndroidRuntime: 	at mozilla.components.feature.qr.QrFragment$stateCallback$1.onOpened(QrFragment.kt:164)
01-04 08:28:28.220 13343 32405 E AndroidRuntime: 	at android.hardware.camera2.impl.CameraDeviceImpl$1.run(CameraDeviceImpl.java:143)
01-04 08:28:28.220 13343 32405 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:873)
01-04 08:28:28.220 13343 32405 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
01-04 08:28:28.220 13343 32405 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:193)
01-04 08:28:28.220 13343 32405 E AndroidRuntime: 	at android.os.HandlerThread.run(HandlerThread.java:65)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-22225)

**Comment by kbrosnan** [comment]
Is there a Sentry or Socorro crash URL to share?

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1810599

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
