### ISSUE TITLE
FNX3-16622 ⁃ Fenix tabs not arriving on iOS

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla-mobile/fenix#2839]
## Steps to reproduce
1. Sign in to Fenix and Firefox iOS
1. Send a tab from Fenix to iOS

### Expected behavior
* Tab appears

### Actual behavior
* Does not

**Comment by vesta0** [comment]
I believe this may be related to sync delay. @grigoryk ?

**Comment by vesta0** [comment]
@ryanfeeley please let us know if this bug is still happening.

**Comment by ryanfeeley** [comment]
@vesta0 Worked intermittently at the last Sync Fest. Could use some QA. It has to work reliablty or people will stop using it as soon as they believe it to be unreliable.

**Comment by abodea** [comment]
Hello @ryanfeeley please note the following:
I was able to reproduce this issue but only at the beginning when I just logged in and synced the accounts.(first ~1-5 minutes)
### I logged in on the following devices:
* Samsung Galaxy Note 9 (Android 8.1) 
* iPhone 8 (iOS 11.4.1)
* iPhone XS MAx(iOS 12.2)
* My desktop pc.
* Please note that after I synced all the devices and waiting ~5-10 minutes the `send tab` worked every time and I was able to open any tab send from `Fenix`.
So if the device sync is completely done, the sent tab works as expected.
During my tests I will try to keep an eye for this issue and add the information here in case I find something.
Maybe my time approximations are much lower but I think it depends on how many data do you have stored on your account until the sync is done. 

Thanks,
Andrei

**Comment by abodea** [comment]
@vesta0 I removed the `QA needed` based on my comment, if this issue needs mores testing/investigation, please let me know.

**Comment by ryanfeeley** [comment]
Sounds like it's related to the sync delay, yes. We want it to start working ASAP as it will become part of onboarding.

**Comment by vesta0** [comment]
@vladikoff FYI

**Comment by vladikoff** [comment]
ack! 

> Worked intermittently at the last Sync Fest.

I think I saw it work in the Sync Fest we did. @ryanfeeley was this after June 6 or before?

**Comment by jdragojevic** [comment]
I just did this now.  I'm using a testing build that has our a-s version
0.31.2 that Grisha built this morning.

-- janet

**Comment by AndiJoltan** [comment]
Hi, **verified as fixed** on the latest Fenix build (2019-06-14) using a `Google Pixel 3XL (Android 9)` to send the tabs to a `iPhone XS MAx(iOS 12.0) `& `iPhone 8 (iOS 11.4.1)`

Based on this comment I'll remove the QA needed label and close the ticket.
