### ISSUE TITLE
Crashed by IllegalStateException when using the camera

### ISSUE THREAD

**Issue by Kobayashi-996** [mozilla-mobile/fenix#28390]
### Steps to reproduce

Tried but didn't know how to reproduce.
Hope the saved logcat output could help.

### Expected behaviour

Normal operation.

### Actual behaviour

Crashed.

### Device name

Google Pixel 2

### Android version

Android 9.0

### Firefox release type

Firefox Nightly

### Firefox version

110a1

### Device logs

01-03 23:21:23.621 28415 29616 E AndroidRuntime: FATAL EXCEPTION: CameraBackground
01-03 23:21:23.621 28415 29616 E AndroidRuntime: Process: org.mozilla.fenix, PID: 28415
01-03 23:21:23.621 28415 29616 E AndroidRuntime: java.lang.IllegalStateException: buffer is inaccessible
01-03 23:21:23.621 28415 29616 E AndroidRuntime: 	at java.nio.DirectByteBuffer.get(DirectByteBuffer.java:232)
01-03 23:21:23.621 28415 29616 E AndroidRuntime: 	at java.nio.ByteBuffer.get(ByteBuffer.java:556)
01-03 23:21:23.621 28415 29616 E AndroidRuntime: 	at mozilla.components.feature.qr.QrFragment$Companion.readImageSource$feature_qr_release(QrFragment.kt:692)
01-03 23:21:23.621 28415 29616 E AndroidRuntime: 	at mozilla.components.feature.qr.QrFragment$imageAvailableListener$1.onImageAvailable(QrFragment.kt:219)
01-03 23:21:23.621 28415 29616 E AndroidRuntime: 	at android.media.ImageReader$ListenerHandler.handleMessage(ImageReader.java:800)
01-03 23:21:23.621 28415 29616 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
01-03 23:21:23.621 28415 29616 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:193)
01-03 23:21:23.621 28415 29616 E AndroidRuntime: 	at android.os.HandlerThread.run(HandlerThread.java:65)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-22226)

**Comment by kbrosnan** [comment]
Is there a Sentry or Socorro crash URL to share?

**Comment by Kobayashi-996** [comment]
@kbrosnan Thanks for your reply!
I have found that in http://crash-stats.mozilla.com/.
https://crash-stats.mozilla.org/signature/?product=Fenix&version=110.0a1&date=%3E%3D2023-01-03T15%3A20%3A00.000Z&date=%3C2023-01-03T15%3A30%3A00.000Z&_sort=-date&signature=java.lang.IllegalStateException%3A%20at%20java.nio.DirectByteBuffer.get%28DirectByteBuffer.java%29

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1810598

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
