### ISSUE TITLE
[Breakdown Eng] Glean SDK

### ISSUE THREAD

**Issue by bbinto** [mozilla-mobile/fenix#284]
Breakdown: https://github.com/mozilla-mobile/fenix/issues/105

**Comment by bbinto** [comment]
@boek, @sarentz do we further break this down or is this all already covered in user stories [here](https://github.com/mozilla-mobile/fenix/issues/105)

**Comment by st3fan** [comment]
I think we are down with "Integrate Glean SDK". The individual events for features are not part of this story but instead live in telemetry stories per feature/epic.
