### ISSUE TITLE
copy | search | select all | share menu not displayed in split screen

### ISSUE THREAD

**Issue by NishchayKQ** [mozilla-mobile/fenix#28407]
### Steps to reproduce

1. open firefox
2. use split screen (mine is samsung tab so the split screen is Left:Right instead of up:down)
3. try to copy something in firefox (any website)

### Expected behaviour

the copy | search | select all | share menu open up after selecting text

### Actual behaviour

it does not open, just the text stays selected

### Device name

Samsung Galaxy Tab A (2018, 10.5) SM T595

### Android version

Android 10

### Firefox release type

Firefox

### Firefox version

108.1.1

### Additional information

# important
if firefox is the second app selected in spilt screen this happens(ie app on right). Else it works as expected.

![Screenshot_20230105-084330_Firefox](https://user-images.githubusercontent.com/108711354/210695954-6e329030-0e00-4793-8b38-f8ea44ba9773.png)
![Screenshot_20230105-084357_Firefox](https://user-images.githubusercontent.com/108711354/210695982-bc68f00e-2c67-4315-a88a-c8f44979befb.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-22229)

**Comment by shtstorm** [comment]
I see the same issue on LG phone. If Fenix is the first app in the horizontal split screen, no action bar for selected text is shown:

![horizontal_split_FF_1st](https://user-images.githubusercontent.com/79124442/211213780-6fe08f21-a567-4be1-9bc5-c9caf8c3becb.png)

**Comment by kbrosnan** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1811658

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
