### ISSUE TITLE
Make a top-level Radio Button Composable component

### ISSUE THREAD

**Issue by HarrisonOg** [mozilla-mobile/fenix#28419]
Currently, we implement a Compose library RadioButton() composable when adding a line to separate visual elements. To streamline this, we should have a RadioButton and composable which incorporates our styles and makes the declaration of dividers a single line with optional modifiers.

Todo

- [ ] Top level Radio Button with our style applied (figma below)
- [ ] Any/all applicable previews

[Figma](https://www.figma.com/file/ujdiReypSypu2GhRgzArea/Android-Components?node-id=1808%3A4714&t=VELUM7NzGZTodrTY-1)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-22234)

**Comment by RotBolt** [comment]
Is this issue still open? Would like to take stab on this one?
