### ISSUE TITLE
Firefox Account sign in page - doesn't show full title in Firefox For Android 

### ISSUE THREAD

**Issue by mMARUF** [mozilla-mobile/fenix#28415]
### Steps to reproduce

1. Open Firefox for Android for the first time after installing
2. Navigate to page for signing in Firefox Account 
3. Observe the title of the page 

### Expected behaviour

Full title of the page should be visible

### Actual behaviour

The full title of the page is not visible

### Device name

Sony Pixel 5 ii

### Android version

Android 11

### Firefox Details

Build ID 20221215175817
User Agent Mozilla/5.0 (Android 11; Mobile; rv:108.0) Gecko/108.0 Firefox/108.0

### Firefox release type

Firefox

### Firefox version

108.0.1

### Attachment

![Screenshot_20230105-224714_2](https://user-images.githubusercontent.com/45368054/210836806-05b73c00-2565-4ec9-b329-1c54caa7d130.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-22232)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812185

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
