### ISSUE TITLE
Extension popups are leaked to the tabs API to other extensions, which enables tracking

### ISSUE THREAD

**Issue by artisticfox8** [mozilla-mobile/fenix#28421]
### Steps to reproduce

I found this issue while working on my extension [Tablet UI for Firefox](https://addons.mozilla.org/en-US/firefox/addon/tablet-ui-for-firefox/). The Firefox bug is easy to demo there.

1. Install Tablet UI for Firefox on Firefox Nightly for Android
2. Open any website (for example google.com)
3. You can see the list of loaded tabs in the tab bar the extension draws
4. Open the popup of say Dark Reader (three dot menu -> Addons -> Dark Reader)
5. Tap the back button to close the popup

### Expected behaviour

The Dark Reader "tab" doesn't appear as a normal tab in `browser.tabs.onUpdated.addListener` callback.
It sure does not do this on desktop.
Firefox extensions have no business in seeing what extension **popups** (which are private) are being opened. 
It does not even make sense from the standpoint of functionality. Why would a Firefox extension get access to that tab, if it is closed right after the user does anything else, including opening another tab or even that Firefox extension's popup.

### Actual behaviour

 Now there are two tabs in the tab bar: google.com and Dark Reader.
Different behaviour than desktop.

### Device name

Samsung Galaxy A52

### Android version

Android 12

### Firefox release type

Firefox Nightly

### Firefox version

110.0a1

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-22236)

**Comment by artisticfox8** [comment]
Here are the same steps on video: https://drive.google.com/file/d/1zR6IENRRlOAtTZsGu0vet-1j5dajN_1E/view?usp=share_link 
Link to Google Drive, because Github doesn't allow uploading videos

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812951

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
