### ISSUE TITLE
The `AboutFragment` misreports the app-services version when using the autoPublish workflow

### ISSUE THREAD

**Issue by MatthewTighe** [mozilla-mobile/fenix#28422]
When using the autoPublish workflow, the `AboutFragment` will report the A-S version used in A-C, instead of the custom version used by autoPublish. This can be verified by putting a breakpoint [here](https://searchfox.org/mozilla-mobile/rev/825ba5537cdc9901b5a62bd4e8f9016da29e7c9d/fenix/app/src/main/java/org/mozilla/fenix/settings/about/AboutFragment.kt#110) and inspecting `appServicesVersion`. However, clicking into 

1. `mozilla.components.Build.applicationServicesVersion`
2. `BuildConfig.APPLICATION_SERVICES_VERSION`

will show that the Fenix `BuildConfig` has the autoPublish version correctly. This means the `AboutFragment` is using the build config from A-C when it should be using its own.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-22237)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812398

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
