### ISSUE TITLE
is it possible to add features in the extension, for example, to make it universal, can it be via external storage and via an extension store like that, can you add the feature?

### ISSUE THREAD

**Issue by Mozzaru** [mozilla-mobile/fenix#28425]
is it possible to add features in the extension, for example, to make it universal, can it be via external storage and via an extension store like that, can you add the feature?

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-22238)

**Comment by kbrosnan** [comment]
Not clear what the request is. If you are looking for general ability to install extensions ser the last paragraph of https://blog.mozilla.org/addons/2022/12/15/new-extensions-available-now-on-firefox-for-android-nightly/
