### ISSUE TITLE
[Bug] Fenix periodically loses session information

### ISSUE THREAD

**Issue by mozillamarcia** [mozilla-mobile/fenix#2842]
## Steps to reproduce
* Open 5-6 tabs
* Close Fenix by swiping away

### Expected behavior
* When I reopen the app my previously open tabs would be there

### Actual behavior
* Tabs are all blank, see attached screenshot

### Device information
* Android device: Pixel 3
* Fenix version: 1.01921 (Build #11440615) 
![Screenshot](https://user-images.githubusercontent.com/2171777/58352480-a4862080-7e39-11e9-9e0a-e997901c9d04.png)UNITO-UNDERSCORE!20190524-153209!

**Comment by jonalmeida** [comment]
Duplicate: https://github.com/mozilla-mobile/fenix/issues/2814

**Comment by vesta0** [comment]
Will be addressed in #2814
