### ISSUE TITLE
'Customise homepage' - button text bit hidden at the bottom of the button

### ISSUE THREAD

**Issue by mMARUF** [mozilla-mobile/fenix#28420]
### Steps to reproduce

1. Open Firefox for Android 
2. Create a collection by adding some bookmarks 
3. Now open a new empty tab
4. Observe the 'Customise homepage' button

### Expected behaviour

The 'Customise homepage' button text should be at the center of the button and full text should be shown. 

### Actual behaviour

Button text is not fully shown. The text of the button is bit hidden from bottom.

### Device name

Sony Xperia 5 ii

### Android version

Android 11

### Firefox release type

Firefox

### Firefox version

108.0.1

### Firefox Details

Build ID 20221215175817
User Agent Mozilla/5.0 (Android 11; Mobile; rv:108.0) Gecko/108.0 Firefox/108.0

### Attachment 

![Screenshot_20230105-232828_2](https://user-images.githubusercontent.com/45368054/210852110-d99c2f81-a3d9-4e16-910a-83741e0946c8.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-22235)

**Comment by AdinaPetridean** [comment]
Tested on Firefox 108.0.1 with Xperia 10 (Android 12) and "Customise homepage" button is displayed correctly (uncut).
I also tried to reproduce this issue on the latest Nightly 110.0a1 (2023-01-12) but with no luck. 
@mMARUF can you test again using the latest Nightly to see if the issue is still reproducible on your side? Thanks!

**Comment by mMARUF** [comment]
I have tested in Firefox Nightly for Android 110.0a1 in Sony Xperia 5 ii and I can still reproduce the issue. 

**Firefox Build ID:** 20230111215657
**Firefox User Agent:** Mozilla/5.0 (Android 11; Mobile; rv:109.0) Gecko/110.0 Firefox/110.0

**Device:** Sony Xperia 5 ii
Android 11

**Attachment:**

![Screenshot_20230112-212919_2](https://user-images.githubusercontent.com/45368054/212110664-1223af62-9ce4-4c8a-86f3-3088c45c0781.png)

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813905

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
