### ISSUE TITLE
Twitter.com - stuttering and input lag - Caused by backdrop-filter 

### ISSUE THREAD

**Issue by twizzlebizzle** [mozilla-mobile/fenix#28436]
## Steps to reproduce
Visiting the mobile twitter site and scrolling around
### Expected behavior
Fast device and 120hz screen should provide smooth scrolling like other sites
### Actual behavior
The website is very stuttery and has input lag.  
If I view the desktop site it's fine.
It seems related to the backdrop-filter CSS performance.  If I block backdrop-filter on ublock origin to stop the blur effect on the Twitter mobile page it will work correctly and be very smooth.
### Device information

* Android device: 13 (2023-01-05 patch) - Pixel 7 Pro
* Fenix version: 108.1.1 - present in beta and nightly.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-22242)

**Comment by MarcLeclair** [comment]
Hey @twizzlebizzle !

Thanks for the report. Would it be possible for you to grab a profile to help us identify the problem?  You can use our profiler through firefox. Here's the [link](https://profiler.firefox.com/docs/#/./guide-profiling-android-directly-on-device) on how to do it.

Thanks!

**Comment by twizzlebizzle** [comment]
> Hey @twizzlebizzle !
> 
> Thanks for the report. Would it be possible for you to grab a profile to help us identify the problem? You can use our profiler through firefox. Here's the [link](https://profiler.firefox.com/docs/#/./guide-profiling-android-directly-on-device) on how to do it.
> 
> Thanks!

No problems.
  
https://profiler.firefox.com/public/2yxwrw3bsefqkncptpn45mn9r5p6qwn69d57eag
  
See that profile I opened twitter, scrolled where it was stuttering.

**Comment by twizzlebizzle** [comment]
Here's the profile after blocking backdrop-filter with ublock using.  
`twitter.com##*:style(backdrop-filter: none !important)`
  
  
https://profiler.firefox.com/public/gsfp9tqg9fgw704nzz3h2v0a9cqvv005wrvwyhg

**Comment by MarcLeclair** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1809738

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Comment by jrmuizel** [comment]
@twizzlebizzle does it work well in Chrome?

**Comment by twizzlebizzle** [comment]
> @twizzlebizzle does it work well in Chrome?

Yes
