### ISSUE TITLE
[Bug] Multiple taps needed to share a collection

### ISSUE THREAD

**Issue by mozillamarcia** [mozilla-mobile/fenix#2843]
## Steps to reproduce
* Create a collection
* Tap the share button to share it

### Expected behavior
* Tapping on the button opens a series of apps that I can choose from where I can share the content

### Actual behavior
* Multiple taps are needed to get the share button to work. It seems you have to be extremely precise with the touch event in order for it to work. Usually it takes me 3-4 tries

### Device information
* Android device: Pixel 3
* Fenix version: 1.011921 (Build #11440615)

**Comment by ekager** [comment]
We should expand the touch areas of these small icons

**Comment by ekager** [comment]
I expanded the touch area and cleaned up the constraint layout here a bit, but this is also impacted by https://github.com/mozilla-mobile/fenix/issues/1454

**Comment by topotropic** [comment]
Seems to be alright now, can we close it?

**Comment by mozillamarcia** [comment]
This seems to be better on my Pixel 3. I am ok with closing it out.
