### ISSUE TITLE
Unify bookmark hierarchy between different views

### ISSUE THREAD

**Issue by marco-eckstein** [mozilla-mobile/fenix#28448]
_This issue applies to Firefox for Android, but also to Firefox for Desktop and Firefox Sync, but it seems to me that mozilla-mobile/fenix is still the most appropriate place. Feel free to move this issue if you think otherwise._

Let's say these are my bookmarks on Firefox for Desktop:

- All Bookmarks/
  - Bookmarks Toolbar/
  - Bookmarks Menu/
  - Other Bookmarks/
  - Mobile Bookmarks/
    - My mobile bookmark A
    - My mobile bookmark folder/
      - My mobile bookmark B
  - _# Cannot have a bookmark directly in All Bookmarks/_

On Firefox for Android, these are my bookmarks when browsing them:

- Bookmarks
  - Desktop Bookmarks/
    - Bookmarks Toolbar/
    - Bookmarks Menu/
    - Other Bookmarks/
  - My mobile bookmark A
  - My mobile bookmark folder/
    - My mobile bookmark B

This is already a bit confusing, but OK, you can still grasp the idea of having everything "local" (not really when syncing, but you know what I mean) in the root folder and having everything "remote" in an additional dektop/mobile folder.

But it gets really confusing when selecting a bookmark folder while editing a bookmark on Firefox for Android, because now all bookmark folders and bookmarks are merged at the top level:

- Bookmarks
  - Bookmarks Menu/
  - Bookmarks Toolbar/
  - Other Bookmarks/
  - My mobile bookmark A _# Not displayed, but theoretically located here._
  - My mobile bookmark folder/
    - My mobile bookmark B _# Not displayed, but theoretically located here._

At least, please reduce the confusion by unifying the views on Firefox for Android.

Even better, please avoid the confusion by unifying all three views to the merged view. It is the simplest model, and because when syncing, there is not really a need for the distinction between "local" and "remote" bookmarks. If some users still want the distinction, they can easily create distinct folders themselves. Note however that for consistency, this would make it necessary to either allow bookmarks at the top level on Firefox for Desktoip or disallow them on Firefox for Android.

As a side note that I think the distinction between "local" and "remote" still makes sense for open tabs though, so please do not throw out the baby with the bathwater by unifying everything.

-----
Firefox for Android 108.1.1
Firefox for Windows 108.0.2

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-22244)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1810836

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
