### ISSUE TITLE
Rename target.apk

### ISSUE THREAD

**Issue by Sataur** [mozilla-mobile/fenix#28450]
Some users might be confused by name of target.apk(most likely they have app name of all other downloaded apps)
https://firefox-ci-tc.services.mozilla.com/tasks/index/mobile.v2.fenix.nightly.latest/armeabi-v7a

Hopefully, we can also rename this "bug" to deal with more serious one. It seems that default option to block autoplay of audio can cause tracks/commercials to skip like in case of livexlive.com

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-22245)

**Comment by kbrosnan** [comment]
There are a lot of scripts that expect target.apk. The build team set up builds to be moved to http://archive.mozilla.org/pub/fenix/nightly/ where they are renamed.

**Comment by klcb2010** [comment]
> There are a lot of scripts that expect target.apk. The build team set up builds to be moved to http://archive.mozilla.org/pub/fenix/nightly/ where they are renamed.

you are  here ，can you tell me it's really ？the history is displayed on the homepage,as a shortcut，you said " This was an intentional change. You can pin 8 sites to control what is displayed."
