### ISSUE TITLE
[Bug]: Add on icons truncated when Android font size increased

### ISSUE THREAD

**Issue by Cheap-Skate** [mozilla-mobile/fenix#28453]
### Steps to reproduce

In Firefox Nightly
1. Install an add-on which has a long title && shows icons in the Settings > Add-ons menu, for example
- Bypass Paywalls Clean (c)
- I don't care about cookies
2. Load a page
3. go Settings > Add-ons
You can probably see the little icons to the right of the text **expected behavior**
4. Go to Android Settings > Display > Font Size and Style and increase the font size as necessary
5. in Firefox Nightly go Settings > Add-ons
The little icons are truncated, see screen shot below **incorrect behavior**

I think the icons **should** be right justified whereas at the moment they are just appended to the Add-on title, when the add-on title grows too long the icons fall out of the window.

### Expected behaviour

Always see icons

### Actual behaviour

Icons can be truncated when font size and/or Add-on title are too long

### Device name

Galaxy M32

### Android version

Android 13

### Firefox release type

Firefox Nightly

### Firefox version

110.0a1 build 2015925483

### Additional information

![signal-2023-01-08-124908](https://user-images.githubusercontent.com/40568887/211197660-b487955b-e2a8-4425-af79-153620d38b0e.jpeg)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-22247)

**Comment by amocirean** [comment]
Hello @Cheap-Skate , thank you for submitting the issue.
I was not able to reproduce the issue on the latest Nightly from 16th of January (110.0a1).
Tested on: Google Pixel 6 (Android 13), Samsung Galaxy S22 Ultra (Android 13).
Thank you!

**Comment by Cheap-Skate** [comment]
Hmmm, I see this on both my A40 (Android 12) and M32 (Android 13).

If you increase the font size to its largest setting, can you still see the icons to the right of the Add-on's name? For example, uBlock Origin shows a counter icon. On both my phones as the font size increases the icons move right and then disappear.

Also try increasing the screen zoom maybe? 

If you really can't see it, let's close this issue. 

Thanks for your response!

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812949

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
