### ISSUE TITLE
Add notification permission prompt onboarding strings

### ISSUE THREAD

**Issue by rocketsroger** [mozilla-mobile/fenix#28469]
This is to add the strings needed for https://bugzilla.mozilla.org/show_bug.cgi?id=1808874

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-22254)

**Comment by SoftVision-LorandJanos** [comment]
Verified as fixed on the ltest Nightly 110.0a1 (2023-01-16) build.
All 4 events were logged.
Device used: Google Pixel 4 (Android 13).
![pre-prompt](https://user-images.githubusercontent.com/48829350/212623025-26ed4caa-26a7-45fb-b71e-d21fddc131fe.jpg)
