### ISSUE TITLE
Black Screen Firefox Nightly Samsung Labs feature

### ISSUE THREAD

**Issue by source-guilherme** [mozilla-mobile/fenix#28465]
### Steps to reproduce

Samsung Labs feature Swipe to pop-up view gives a black screen web browser, after resizing back to normal it doesnt solve and only by closing and reopening the app. It does have a inconsistency reproducing those steps.

1. Open any web page
2. Pop-up view with Samsung Labs feature
3. Black Screen with tabs normal
4. Resize back to normal
5. Same issue on step 3

### Expected behaviour

The web browser should resize without giving a black screen.

### Actual behaviour

The web browser is giving a black screen regardless of pop-up view size.

### Device name

Samsung S21 FE

### Android version

Android 13 One UI 5.0

### Firefox release type

Firefox Nightly

### Firefox version

110.0a1

### Additional information

Please bear with me, first time filling a issue on GitHub.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-22253)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812373

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
