### ISSUE TITLE
[Bug]: [Experiment] The engagement notification is not triggered naturally after Firefox was force closed 2 days in the past

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [mozilla-mobile/fenix#28460]
### Steps to reproduce

1. Install Firefox Release 109 ([custom build](https://drive.google.com/file/d/1gUk2RbLp1PkR8giPLj-tqsS72Xcq9Kgo/view?usp=sharing)) and open it.
2. Navigate to the secret menu (Settings -> About Firefox -> Tap logo 5 times).
3. Tap the Android Reengagement Notifications Release experiment and ensure that the treatment branch is checked.
4. Fully close the app and then Force close the app.
5. Don’t open/interact with Firefox for at least 49 hours.
6. Observe the behavior.

### Expected behaviour

- A Firefox Notification is triggered and is displayed in the notifications tray.

### Actual behaviour

- No notification is triggered.

### Device name

Samsung S9, Samsung S8, OnePlus 6, OnePlus 5, Motorola G10

### Android version

Android 10, Android 9, Android 11

### Firefox release type

Firefox

### Firefox version

109 (custom build)

### Additional information

- The notification is only displayed when Firefox is opened.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-22250)

**Comment by rocketsroger** [comment]
If you forced closed the app from settings, then Workmanager jobs are paused and will reschedule when the app is restarted (by the user).  In some OEM's the swipe up is also implemented incorrectly to force stop the app.  There's nothing we can do here since it's an OS issue.  Here's the [source](https://issuetracker.google.com/issues/110745313).

**Comment by SoftVision-CarmenFat** [comment]
Given that this is an OS limitation and there is nothing we can do about it, I will close this issue as Won't Fix.
