### ISSUE TITLE
Intermittent UI test failure - <HomeScreenTest.selectStoriesByTopicItemTest>

### ISSUE THREAD

**Issue by HarrisonOg** [mozilla-mobile/fenix#28472]
After changing `SelectableChip` to use Material `Chip` as a base class, the UI test has failed to assert `selected` state.

### Firebase Test Run:
[Firebase Test Run](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/5488612512823938606/executions/bs.5064b1d1c80221f3/testcases/6/errors)

### Tests ignored
 - selectStoriesByTopicItemTest

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-22255)

**Comment by AaronMT** [comment]
Is this on-going refactor work off branch? Tags applied but I don't see the reflection on `main` https://github.com/mozilla-mobile/fenix/blob/90269e65f766ec1f89923de47c91aad951fc96ed/app/src/androidTest/java/org/mozilla/fenix/ui/HomeScreenTest.kt#L303

**Comment by HarrisonOg** [comment]
@AaronMT yes this is ongoing, there was an UX issue that blocked progress but that has been rectified and I will be updating the PR shortly so it can land on `main`

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813906

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
