### ISSUE TITLE
Enable extension collections for Stable.

### ISSUE THREAD

**Issue by rokejulianlockhart** [mozilla-mobile/fenix#28473]
As the rational successor to https://github.com/mozilla-mobile/fenix/issues/26948#issue-1370585430 because of the support demonstrated by @vehosah's [comment](https://github.com/mozilla-mobile/fenix/issues/26948#issuecomment-1293475558).

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-22256)

**Comment by kbrosnan** [comment]
Duplicate https://github.com/mozilla-mobile/fenix/issues/28493
