### ISSUE TITLE
[Bug]: when you fix  the history is displayed on the homepage.,as a shortcut,

### ISSUE THREAD

**Issue by klcb2010** [mozilla-mobile/fenix#28476]
### Steps to reproduce

too old bug
some one said that This was an intentional change. You can pin 8 sites to control what is displayed

![Screenshot_2023-01-10-18-29-01-157_us spotco fennec_dos](https://user-images.githubusercontent.com/32628414/211531791-270e1ccf-1d1e-4032-b200-0e45813ef875.jpg)

**Comment by kbrosnan** [comment]
Duplicate https://github.com/mozilla-mobile/fenix/issues/25739
