### ISSUE TITLE
Request to set download location

### ISSUE THREAD

**Issue by jr-johnson-support** [mozilla-mobile/fenix#28488]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### What is the user problem or growth opportunity you want to see solved?

Feature Description:
Users are requesting the option to choose the location for the content they're downloading from Firefox for Android. 

Users request: 
- selecting the SD card for their downloads 
-choose a download folder 

### How do you know that this problem exists today? Why is this important?
24  Requests seen Since May 2022 and last updated Dec 2022. 

### Who will benefit from it?
This gives users more control when it comes to downloading

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-22260)

**Comment by kbrosnan** [comment]
Duplicate https://github.com/mozilla-mobile/fenix/issues/5764

**Comment by jr-johnson-support** [comment]
Thanks for the info on the original. Apologies for resubmitting a dubplicate
