### ISSUE TITLE
When does the release support custom add-ons

### ISSUE THREAD

**Issue by klcb2010** [mozilla-mobile/fenix#28493]
When does the release support custom add-ons? It turns out to be a good idea. It performs well in the beta and nightly versions.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-22263)

**Comment by kbrosnan** [comment]
The collection based extension will not be part of release Firefox. It will be several releases before wider extension support will be part of Firefox. 

https://blog.mozilla.org/addons/2022/12/15/new-extensions-available-now-on-firefox-for-android-nightly/

> we’re focused on implementing [Manifest version 3 (MV3)](https://extensionworkshop.com/documentation/develop/manifest-v3-migration-guide/) for Firefox desktop (i.e. wide ranging foundational changes to WebExtensions API). In 2023 we’ll begin work on the mobile adoption of MV3. Though we’re still early in planning

**Comment by vehosah** [comment]
Then another reason not to use stable :)

**Comment by klcb2010** [comment]
> The collection based extension will not be part of release Firefox. It will be several releases before wider extension support will be part of Firefox.
> 
> https://blog.mozilla.org/addons/2022/12/15/new-extensions-available-now-on-firefox-for-android-nightly/
> 
> > we’re focused on implementing [Manifest version 3 (MV3)](https://extensionworkshop.com/documentation/develop/manifest-v3-migration-guide/) for Firefox desktop (i.e. wide ranging foundational changes to WebExtensions API). In 2023 we’ll begin work on the mobile adoption of MV3. Though we’re still early in planning

what about "the history or mostVisitedSites is displayed on the homepage,as a shortcut" ？,did you will  not  change  forever ？
