### ISSUE TITLE
[Bug]: Misplaced empty tabs tray, history and downloads messages

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#28498]
### Steps to reproduce

1. Open the tabs tray
2. Check empty tabs tray message
3. Tap the private open tabs
4. Check empty private tabs tray message
5. Open "History" from the home screen ⋮ button
6. Check empty history list message
7. Open "Downloads" from the home screen ⋮ button
8. Check empty history list message

### Expected behaviour

The messages should be centered

### Actual behaviour

Misplaced messages

### Device name

Google Pixel 2, Pixel 3a 

### Android version

Android 11

### Firefox release type

Firefox Nightly

### Firefox version

110.0a1

### Additional information

► Video

https://user-images.githubusercontent.com/51314259/211844988-da3b04c2-0c21-4a4a-afe9-a1e094efd96d.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-22265)

**Comment by Alexandru2909** [comment]
This seems to have been unintentionally introduced by https://github.com/mozilla-mobile/fenix/pull/28340

cc @mavduevskiy

**Comment by Mugurell** [comment]
This should be fixed in both Nightly 111 and the next Beta 110 with the backout of https://github.com/mozilla-mobile/fenix/pull/28340.

**Comment by SoftVision-LorandJanos** [comment]
This issue is no longer reproducible with the latest Nightly 111.0a1 (2023-01-18) build.
Device used: Oppo find X5 (Android 12). - Device on which I was able to reproduce the issue on earlier build versions.
Closing the ticket as verified.

**Comment by SoftVision-LorandJanos** [comment]
Verified as fixed on the latest Beta 110.0b2 build.
Device used: Oppo find X5 (Android 12).
