### ISSUE TITLE
Implement reopening of recently closed tabs in Private Browsing Mode

### ISSUE THREAD

**Issue by shtstorm** [mozilla-mobile/fenix#28492]
Recently closed tabs list is always empty in the current session of the Private Browsing Mode. 
While `Recently closed tabs` is present in three vertical dots menu on the tabs tray, the *Recently closed tabs* list is permanently empty for private tabs. Original Fenix issue #2486 left this unimplemented for Private tabs.

3 dots menu                  | *Recently closed tabs* list
:-------------------------:|:-------------------------:
![3 dots menu](https://user-images.githubusercontent.com/79124442/211731474-85c5a710-f75c-4ee0-86d2-25210d6c8bd3.png) |  ![empty Recently closed tabs list](https://user-images.githubusercontent.com/79124442/211731920-abaf77a3-77d9-4f7e-a698-ad9bd851447f.png)

This can be considered as a regression. Fennec kept a list of closed session tabs in private mode. So does the desktop.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-22262)

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812948

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
