### ISSUE TITLE
[Experiment] [Viewpoint Survey (2023 Jan, Android)] The Viewpoint survey message is replaced by the "Set as default" message and vice versa each time Firefox is reopened from the background

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla-mobile/fenix#28510]
### Steps to reproduce

[Prerequisites]:
- Have the device’s language set to any of the following: 'de', 'en', 'es', 'fr', 'ja', 'pl', 'pt', 'ru', 'zh'.
- Have the Firefox 109 Release build installed on a device.

[Steps to reproduce]:
1. Open the 109 Release build from the prerequisites.
2. Navigate to the Firefox "Settings" menu.
3. Scroll down to the bottom of the list and tap the "About Firefox" option.
4. Tap the "Firefox Browser" logo 5 times and go back to the "Settings" menu.
5. Scroll down to the bottom of the list and tap the "Secret Settings" option.
6. Enable the “Use Nimbus Preview Collection” option and restart the browser.
7. Enable the Secret Settings menu again.
8. Scroll down to the bottom of the list and tap the "Nimbus Experiments" option.
9. Tap the "Viewpoint Survey (2022 Dec, Android)" experiment.
10. Tap the “treatment” branch and restart the browser.
11. Observe the message displayed in the top part of the screen.
12. Send the Firefox app to the background then reopen it.
13. Observe the message displayed in the top part of the screen.

### Expected behaviour

Step 11 & Step 13: The same message is displayed.

### Actual behaviour

Step 11: A message that asks the user to complete a survey is displayed on the Homepage.
Step 13: The "Set as default browser" message is displayed.

### Device name

Samsuns S9, Samsung Galaxy S8, Google Pixel 2XL

### Android version

Android 11, Android 10, Android 9

### Firefox release type

Firefox

### Firefox version

Firefox 109 Release, Firefox Beta 109, Firefox Nightly 110

### Additional information

- Each time the Firefox browser is sent to the background and reopened the two messages are switched.
- The issue is also reproducible when the device screen is turned off while the Firefox app is focused and then is turned on.
- The issue is NOT reproducible when the app is fully closed and reopened.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-22266)

**Comment by Softvision-PatriciuPop** [comment]
I have verified that this issue is no longer reproducible, the "Set as default browser" message is displayed only after the Viewpoint survey was interacted with/has expired. Tested on Android 11 (OnePlus 6T) using a copy of the Viewpoint experiment on Stage and a Stage build from the latest main. (Build #2015931139), 34e57c3f4+ AC: 111.0.20230201190227, 0f7deea290 GV: 111.0a1-20230201094356 AS: 96.4.0)
