### ISSUE TITLE
The width of the Firefox messages displayed on the Homepage is inconsistent when changing the orientation of the device 

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [mozilla-mobile/fenix#28511]
### Steps to reproduce

1. Install Firefox RC 109 and open it.
2. Navigate to the secret menu (Settings -> About Firefox -> Tap logo 5 times).
3. Go back to the Settings menu and tap the "Secret Settings" option.
4. Enable the “Use Nimbus Preview Collection” option and restart the browser twice.
5. Enable the Secret Settings menu again.
6. Scroll down to the bottom of the list and tap the "Nimbus Experiments" option.
7. Tap the "Viewpoint Survey (2023 Jan, Android)" experiment.
8. Tap the “treatment” branch and restart the browser.
9. Turn around the device in Landscape and Portrait mode several times.
10. Observe the Survey message.

### Expected behaviour

- The size of the Survey message is specific to the device's screen size in Portrait or Landscape mode and remains the same each time the device’s orientation is changed.

### Actual behaviour

- The width of the Survey message is inconsistent when the device’s orientation is changed.

### Device name

Samsung S9, Samsung S8

### Android version

Android 9, Android 10

### Firefox release type

Firefox

### Firefox version

RC 109, Nightly 110

### Additional information

- The issue is intermittent.
- This issue was also observed for the “Set as default browser” message.
- Here is a screenshot of the issue:

![messages width](https://user-images.githubusercontent.com/26000308/212075367-92824ec2-eedc-4048-b01a-2d91f16a0f8c.jpg)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-22267)

**Comment by Mugurell** [comment]
This issue affects all Compose views from the homescreen (collections, recent tabs, pocket etc).
Should be rechecked after the migration to Compose is finished.

**Comment by hakeem-gitstart** [comment]
@Mugurell I'll like to pick this up

**Comment by Mugurell** [comment]
> @Mugurell I'll like to pick this up

Thank you!
Might not be easy to solve now but even investigating it and gathering more details will help.

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812830

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
