### ISSUE TITLE
The “Active” text from the Studies menu is cut off when users are enrolled in studies while the system font is set to a larger size

### ISSUE THREAD

**Issue by heres-maria** [mozilla-mobile/fenix#28531]
**[Affected Versions]:**
- Firefox RC 109.1.0 (Build #2015926579), 7d00fc7f1+ AC: 109.1.0, 5294c37a47 GV: 109.0-20230109151414 AS: 96.1.3.
through
- Firefox Nightly 110.0a1 (Build #2015927211), 91a134b4c+ AC: 110.0.20230112190320, aa46c927d6 GV: 110.0a1-20230112093539 AS: 96.2.1

**[Affected Platforms]:**
- Android 9 (Samsung Galaxy S8)

**[Prerequisites]:**
- Have the font size of the device set to a larger option (e.g. from Settings > Display > Font size and style).

**[Steps to reproduce]:**
1. Open the app and restart it once.
2. Enable the Debug menu by tapping the Firefox icon from Settings > About Firefox 5 times.
3. Enroll in an experiment by tapping a branch from Settings > Nimbus Experiments > experiment name.
3. Go to Settings > Data collection > Studies.
4. Observe the “Active” section.

**[Expected result]:**
- The title of the “Active” section is correctly displayed.

**[Actual result]:**
- The title of the “Active” section is cut off when a larger font size is set.

**[Notes]:**
- Attached is a screenshot of the issue.

![1673888292246](https://user-images.githubusercontent.com/53752296/212378264-10b2afb8-e346-4a37-b3f4-ae011d4a71e9.JPEG)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-22269)

**Comment by gabrielluong** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1815631

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
