### ISSUE TITLE
[Bug]: Native video player visual bug

### ISSUE THREAD

**Issue by Palloxin** [mozilla-mobile/fenix#28537]
### Steps to reproduce

Find a video long 3 hours
then play it with fenix video player

### Expected behaviour

not visual bug

### Actual behaviour

https://user-images.githubusercontent.com/75091899/212475961-1ed06370-330a-4b49-8dbc-c7c43279e23f.mp4

### Device name

Huawei p8 lite 2017

### Android version

Android 8 miui 8

### Firefox release type

Firefox

### Firefox version

108.2.0

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-22270)

**Comment by kbrosnan** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1811656

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
