### ISSUE TITLE
Add option to disable in-app browser

### ISSUE THREAD

**Issue by Taknok** [mozilla-mobile/fenix#28539]
Some applications does not expose a settting to disable in app browser (also known a brower powered by Firefox). A settings allowing to disable this functionnality from Firefox (when FF is the default browser) to allow users to select the behavior of their favorite browser would be greatly appreciated.

All users asking the question "how disable in app browser ?" would be greatful. For exemple the youtube app has no settings to disable in app browser and automatically open all links in description with this in app browser:
https://forums.androidcentral.com/android-apps/1028695-how-disable-app-browser-youtube-app.html
https://www.reddit.com/r/Vanced/comments/ra2byz/question_any_way_to_disable_the_inapp_browser_of/

Could you add a setting allowing to disable this in app browser when powered by Firefox (enabled when Firefox is set ad the default browser) ?

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-22271)

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812947

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
