### ISSUE TITLE
[Bug]: Downloaded photos show up as green lines sometimes

### ISSUE THREAD

**Issue by juliloving** [mozilla-mobile/fenix#28544]
### Steps to reproduce

1. Download photo from a website (I used https://fakedetail.com/fake-iphone-text-messenger-generator last time this happened to make a meme)
2. Check the photo in your gallery
![iphone_text_message](https://user-images.githubusercontent.com/85190590/212653793-f89fc34e-d832-4d49-86df-3d78266f0324.png)
3. It should have green lines

### Expected behaviour

The photo should be regular

### Actual behaviour

It's green lines

### Device name

Samsung Galaxy S22

### Android version

Android 10 (OneUI 5)

### Firefox release type

Firefox

### Firefox version

It's the latest version now (I updated today) but when this happened yesterday I was at the version 108.1.1

### Additional information

Only works sometimes. Doesn't work with search engines, but every time if happens it's from when something starts downloading on another website

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-22273)

**Comment by kbrosnan** [comment]
You enabled privacy.resistfingerprinting.
