### ISSUE TITLE
no keyboard input after using the browser for some time

### ISSUE THREAD

**Issue by TheFrozenDuck** [mozilla-mobile/fenix#28545]
OS version: Lineage OS 20
Phone: OnePlus 9 Pro
FF version: 108.2.0
Keyboard: AOSP provided by LineageOS

I recently upgraded from LineageOS 19.1 to LineageOS 20, which seems to have started my problems with Firefox. After a while of using the browser, text input is not processed anymore by the browser. Special keys such as backspace, enter, etc. seem to work but everything else seems to be ignored. I looked into the ADB logs but did not find anything problematic. There seems to be some warnings and errors but nothing particularly pointing to an input error.

A quick fix for now seems to be closing the app and re-open it but this is rather problematic with private sessions, as this closes all the private windows.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-22274)

**Comment by raulvasquez** [comment]
I am also having this issue. Same device, but a different a13 build (stagos). Commenting to follow.

**Comment by kbrosnan** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1811657

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
