### ISSUE TITLE
Could you add compatibility with the malwarebytes extension ?

### ISSUE THREAD

**Issue by edersonmax21** [mozilla-mobile/fenix#28542]
Hello, I would like to ask you to add compatibility with the malwarebytes extension, as it is an extension that I currently use in the kiwi browser, as I want to switch to the firefox browser, but whenever I put a custom collection and try to install malwarebytes it says Failed to install addons.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-22272)

**Comment by marcel263** [comment]
There is tracking protection and malware protection in Firefox by default. Install an ad blocker if you need to block ads.

Feature requests should be directed at the creator of the software.

If you could kindly provide a [debug log](https://github.com/mozilla-mobile/fenix/wiki/Logging-Crash-Information) , more about the error would be known.

**Comment by cadeyrn** [comment]
Mozilla does not keep issues open for specific add-on requests. But they're working on a general availability of add-ons. Please read https://blog.mozilla.org/addons/2022/12/15/new-extensions-available-now-on-firefox-for-android-nightly/ for more information, especially the last paragraph.

**Comment by edersonmax21** [comment]
Ok, thank you.

**Comment by edersonmax21** [comment]
I will close as resolved.
