### ISSUE TITLE
Selection pop-up covers actual selectors

### ISSUE THREAD

**Issue by exec228** [mozilla-mobile/fenix#28558]
### Steps to reproduce

1. Open google.com and search for "shrug". Wait page to load. Actually, this bug is related to ALL pages.
2. Hold a finger for text selection pop-up

### Expected behaviour

Expected:
3. Selection pop-up is NOT blocking selection zone.

### Actual behaviour

Actually:
3. Pop-up is drawn over text, preventing normal selection operation
https://i.imgur.com/2YFmxC1.png
4. Extension of this pop-up (having another shape) demonstrates the screen area which had been blocked earlier
https://i.imgur.com/AjuVyWT.png
5. Display settings "text size" and "display size" has no effect, and pop-up location is the same: over the selection zone.

### Device name

Google Pizel 6a

### Android version

Android 13

### Firefox release type

Firefox

### Firefox version

108.2.0

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-22278)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812417

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
