### ISSUE TITLE
[Bug]: Misplaced site exceptions message and "About Firefox Nightly" options

### ISSUE THREAD

**Issue by delia-pop** [mozilla-mobile/fenix#28550]
### Steps to reproduce

1. Go to Settings > About Firefox Nightly 
2. Observe the section. 
3. Go to Settings > Site permissions > Exceptions 
4. Observe the empty site exceptions message.

### Expected behaviour

The options in the "About Firefox Nightly" section" should be centered. 
The "No site exceptions" message should be centered. 

### Actual behaviour

Similar to https://github.com/mozilla-mobile/fenix/issues/28498, the options and the message are misplaced. 

### Device name

Google Pixel 6

### Android version

Android 13

### Firefox release type

Firefox Nightly

### Firefox version

110.0a1 from 01.16

### Additional information

![misplaced_message_options](https://user-images.githubusercontent.com/89388888/212714172-3acbd93a-792a-4367-be64-b9d719f363fa.png)

The Add to home screen prompt is also affected: 

![processed-96ff31e9-ef63-48cf-8709-b9fa602bf5cd_1FMyLoXB](https://user-images.githubusercontent.com/89388888/213116361-0c48d51a-b9df-4e28-94bc-f2862c196998.jpeg)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-22280)

**Comment by Mugurell** [comment]
The issues shown in the above screenshot shoult be fixed in both Nightly 111 and the next Beta 110 with the backout of https://github.com/mozilla-mobile/fenix/pull/28340.

**Comment by delia-pop** [comment]
Verified as fixed in latest Nightly 111.0a1 from 01/18 with Lenovo Yoga Tab 11 (Android 11). The elements are now centered. 
![processed-9714a204-05a8-4cea-ba1c-e9f605bee9e8_gV4x6V8t](https://user-images.githubusercontent.com/89388888/213214456-fd9d6d26-4dfe-42de-8e02-ea60cebd7ad2.jpeg)

![processed-17ce6cfc-8466-4bc4-8a4b-9f392e9e5663_A0ihLFho](https://user-images.githubusercontent.com/89388888/213214635-f5f10e7e-6424-40fe-aaef-c1e8438341ee.jpeg)

![processed-9cdb4c44-9ede-4b5f-8878-6ec2d461f172_6A7iVesP](https://user-images.githubusercontent.com/89388888/213214653-5f592622-187a-4335-82d1-2b8b0ef219c3.jpeg)
