### ISSUE TITLE
Miscellaneous UI Issues in large font 

### ISSUE THREAD

**Issue by PrashantSaroj** [mozilla-mobile/fenix#28551]
### Steps to reproduce

1. Set large font size in system settings
2. "Continue" and "Not Now" button in notifications first run experience screen is truncated
3. "Light theme" and "Dark theme" text overlaps
4. "Bookmarks" and "Add" option overlap in 3-dot action menu

Attached screenshot for all three in the additional info section

### Expected behaviour

UI is rendered properly

### Actual behaviour

UI elements overlaps or get truncated

### Device name

Samsung galaxy S20

### Android version

Android 13

### Firefox release type

Firefox Nightly

### Firefox version

110.0.202 debug build compiled from source code

### Additional information

![Screenshot_20230116_213147_Firefox Fenix](https://user-images.githubusercontent.com/39155305/212722654-afeefc30-80aa-4c03-9c44-1d913cd5c021.jpg)
![Screenshot_20230116_213057_Firefox Fenix](https://user-images.githubusercontent.com/39155305/212722663-c62e7151-4f9c-4de5-8165-e65706a57e78.jpg)
![Screenshot_20230116_213115_Firefox Fenix](https://user-images.githubusercontent.com/39155305/212723038-c87fa059-2b0d-49e3-8aef-85852872fd0c.jpg)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-22277)

**Comment by PrashantSaroj** [comment]
It can be assigned to me, I can fix these

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812829

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
