### ISSUE TITLE
Tapping tabs overview does not show current tab V2

### ISSUE THREAD

**Issue by erglundar** [mozilla-mobile/fenix#28567]
### Steps to reproduce

Repeat a couple of times:
1. Click tab overview
2. Select a tab

Note that I have many tabs opened (100).

### Expected behaviour

The preselected tab is the current one and it is visible.

### Actual behaviour

About every five times the overview scrolls all the way up to the very first tab of the list. I have to scroll down a lot every time.

### Device name

Oneplus 7

### Android version

Android 11

### Firefox release type

Firefox

### Firefox version

Fennec 108.1.1

### Additional information

This has been going on for a year or so. I am annoyed. I might have to use another browser so I don't jump out of the window.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-22279)

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812946

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Comment by erglundar** [comment]
It seems to be a problem with archived tabs. If I disable archiving in the tabs settings the problem does not happen any more.
