### ISSUE TITLE
Tabs reappear after closing (from swipe) when closing app

### ISSUE THREAD

**Issue by BBBmau** [mozilla-mobile/fenix#28586]
### Steps to reproduce

1. Swipe on tabs that you want to remove
2. Swipe to view open apps
3. Swipe on Firefox app to end application
4. Reopen and view tabs, the tabs that were closed previously will reappear

### Expected behaviour

Tabs should not reappear when reopening the firefox app

### Actual behaviour

Tabs that were closed reappear after reopening the application

### Device name

Google Pixel 4a

### Android version

Android 13

### Firefox release type

Firefox Beta

### Firefox version

109.0b6

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-22282)

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812944

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
