### ISSUE TITLE
FNX3-16628 ⁃ [Bug] Switch to tab snack bar no longer appears

### ISSUE THREAD

**Issue by pwd-github** [mozilla-mobile/fenix#2858]
## Steps to reproduce
1. Open a webpage
1. Long press a link
1. Tap open in new tab

### Expected behavior
Fenix should display a snack bar notification that offers to switch to the new tab

### Actual behavior
Nothing

### Device information
* Android device: Android 8, LG G6
* Fenix version: 1.0.1921

**Comment by vesta0** [comment]
This seems to be a regression.

**Comment by softvision-miralobontiu** [comment]
Verified as fixed on build 1.0.1922 (#11530616), with Samsung Galaxy Tab S3 (Android 8(, Nokia 6 (Android 7.1.1), and Motorola Moto G6 (Android 8).
