### ISSUE TITLE
Remove all use of now-removed Glean events API

### ISSUE THREAD

**Issue by badboy** [mozilla-mobile/fenix#28588]
Ref #19967, #28587

This API is still references here: https://github.com/mozilla-mobile/fenix/blob/3e7d0bf8fbfbcb88eb447d63cf4b74beb14d88af/app/src/main/java/org/mozilla/fenix/components/metrics/GleanMetricsService.kt

[Further down the `EventWrapper` is set to `null` unconditionally](https://github.com/mozilla-mobile/fenix/blob/3e7d0bf8fbfbcb88eb447d63cf4b74beb14d88af/app/src/main/java/org/mozilla/fenix/components/metrics/GleanMetricsService.kt#L54-L55), and references in [`track`](https://github.com/mozilla-mobile/fenix/blob/3e7d0bf8fbfbcb88eb447d63cf4b74beb14d88af/app/src/main/java/org/mozilla/fenix/components/metrics/GleanMetricsService.kt#L98-L100).

That one is then used here:
https://github.com/mozilla-mobile/fenix/blob/3e7d0bf8fbfbcb88eb447d63cf4b74beb14d88af/app/src/main/java/org/mozilla/fenix/components/metrics/MetricsMiddleware.kt#L29-L30
and I think here: https://github.com/mozilla-mobile/fenix//blob/main/app/src/main/java/org/mozilla/fenix/components/metrics/MetricController.kt#L395

and I don't understand how that all still works together.
But I think this basically _doesn't_ track any events anymore because of the `event.wrapper = null` mentioned above.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-22283)

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812943

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
