### ISSUE TITLE
Enable notification pre permission prompt feature in Beta

### ISSUE THREAD

**Issue by rocketsroger** [mozilla-mobile/fenix#28597]
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-22286)

**Comment by delia-pop** [comment]
Tested on Beta 110.0b3 with Xiaomi 12 Pro (Android 13). The pre permission prompt is not available in the current Beta version, as expected.

**Comment by SoftVision-LorandJanos** [comment]
Verified in the latest Beta build (110.0b6).
The Pre-permission prompt is enabled and works as expected.
Android Pre-Permission Prompt Experiment needs to be set to Treatment branch in order for this feature to be active.
Verified on the following devices:
- Google Pixel 4 (Android 13).
- Samsung Galaxy A53 5G (Android 13).
Adding the verified label.
