### ISSUE TITLE
Black Screen When Switching to another app and return to firefox in custom tabs

### ISSUE THREAD

**Issue by jawadalkassim** [mozilla-mobile/fenix#28595]
### Steps to reproduce

1: Have a Tab open
2: Press the Homepage button in the phone Navigation bar (without closing Firefox), then open another app then reopen Firefox 

### Expected behaviour

Back to the page, I was viewing

### Actual behaviour

Black Page and I can't do anything unless I close the tab, And open a new one.

### Device name

Xiaomi Redmi Note 8

### Android version

Android 11

### Firefox release type

Firefox

### Firefox version

108.2.0

### Additional information

![photo_2023-01-19_23-42-27](https://user-images.githubusercontent.com/48631694/213555378-bfdd8a16-3358-4cef-ae85-9160f978047f.jpg)

Example: When I was singing into Firefox Account I Should open The 2FA App to get the codes to complete sign in
but it always give me black screen when returning to firefox so I can't complete sign inmy

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-22285)

**Comment by kbrosnan** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812691

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
