### ISSUE TITLE
Modify password field text to using Roboto monospace

### ISSUE THREAD

**Issue by cwzilla** [mozilla-mobile/fenix#28609]
Hello team,

We are looking to improve the user experience of the password field by changing the password field text style to using a monospace font so it is easier to read. This issue and a potential solution was brought up in a previous UX/Eng sync and we found that the system font (Roboto) has a monospace variation we can use, so a custom font is not needed.

There are 3 screens where the monospace should be implemented: **Add a login**, **View login**, and **Edit login**. I will attach some screenshots below of these screens.

### Add a login
![add-a-login](https://user-images.githubusercontent.com/87655586/213793905-c06cf04b-4506-44c8-9b3b-975a40c24ea0.jpg)
- Change password input font style to monospace
- For this screen, I think it is also missing the eye icon for revealing and hiding the password, as this behaviour exists on the edit login screen

### View login
![view-login](https://user-images.githubusercontent.com/87655586/213794248-b863c9a7-1a00-45a4-965d-587a1dd200e2.jpg)
- Change password font style to monospace

### Edit login
![edit-login](https://user-images.githubusercontent.com/87655586/213794364-4b6b7cb7-4e0e-4e61-8f10-5bcd53822999.jpg)
- Change password font style to monospace

Let me know if you have any questions. Thanks all!

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-22290)

**Comment by debojyoti452** [comment]
I want to work on this issue @cwzilla. is it available?

**Comment by cwzilla** [comment]
Hi @debojyoti452, yes I'm available!

**Comment by debojyoti452** [comment]
> Hi @debojyoti452, yes I'm available!

Great. Is there any constraints I need to keep in mind? When doing this task? Any pattern or something more information you want to be known to me?

**Comment by debojyoti452** [comment]
> @debojyoti452 Nothing in particular I can think of right now, other than the note I mentioned in the issue about applying the **Edit** screen password input behaviour/pattern to the **Add Login** screen.

Okay noted @cwzilla 
Thank you! will push a PR soon.
