### ISSUE TITLE
[Bug]: When you add a search engine, you don't get the default icon, but use Firefox's own letter icon

### ISSUE THREAD

**Issue by MrzeroY** [mozilla-mobile/fenix#28604]
### Steps to reproduce

1. Add search engine neva, and enter the string https://neeva.com/search?q=%s
2. Confirm the completion of the search engine icon for Firefox comes with the letter icon, rather than using the search engine icon

### Expected behaviour

Get the search engine default icon and use it

### Actual behaviour

After adding it, what you get is extremely ugly, incongruous letter solid color icons

### Device name

Oppo K10

### Android version

Android13

### Firefox release type

Firefox Beta

### Firefox version

109.0b6

### Additional information

Many custom search engines do not get the icon that should be there

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-22289)

**Comment by kbrosnan** [comment]
Duplicate bz-1807574
