### ISSUE TITLE
White webpage when rotating horizontally in Firefox Focus for Android

### ISSUE THREAD

**Issue by madcooki** [mozilla-mobile/fenix#28601]
The title pretty much says it all. I have an Android phone with Firefox Focus as my main web browser. Whenever I rotate the screen to horizontal from vertical, the entire webpage goes white (can't even see the Firefox UI, like the URL, trash bin icon, and hamburger menu icon).

If I rotate back to vertical, it returns to normal. I've been using this app for a long time, and it only started doing this a few days ago, which means it's most likely a very recent change in the code that caused this.

![Screenshot_20230119-194836](https://user-images.githubusercontent.com/75868154/213594323-4df008f0-ebbd-4e07-b063-faaabd1fed33.png)
![Screenshot_20230119-194840](https://user-images.githubusercontent.com/75868154/213594334-8ed864c0-6cfe-4d1f-9a72-14773e686560.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-22288)

**Comment by kbrosnan** [comment]
Focus bugs should be reported to https://bugzilla.mozilla.org/enter_bug.cgi?product=Focus
