### ISSUE TITLE
Don't expose unsupported bookmark types in the bookmarks UI

### ISSUE THREAD

**Issue by linabutler** [mozilla-mobile/fenix#2861]
`mozilla.components.concept.storage.BookmarkNodeType` can be an item, folder, or separator. Additionally, Sync supports queries (which are bookmarks with a special `place:` URL that Desktop parses and renders specially, kind of like a Windows shortcut) and livemarks (which are deprecated).

Let's consider filtering out queries and livemarks in folder lists, since it's a bit confusing to see them, and, unlike Desktop, they don't do anything special.

See mozilla/firefox-preview-bughunting-campaign#187.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-11728)

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812727

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
