### ISSUE TITLE
[Feature request] Sideload extensions

### ISSUE THREAD

**Issue by urain39** [mozilla-mobile/fenix#28610]
I know that Firefox has blocked all anti-advertising extensions in China for legal reasons in recent years, but as a Chinese user, I hope that the corresponding Firefox should open the sideload function to make it more free.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-22291)

**Comment by kbrosnan** [comment]
Duplicate https://github.com/mozilla-mobile/fenix/issues/11292
