### ISSUE TITLE
FNX3-16631 ⁃ [Bug] missing argument from About Firefox Preview page

### ISSUE THREAD

**Issue by pwd-github** [mozilla-mobile/fenix#2862]
## Steps to reproduce
1. Go to settings
1. Go to About Firefox Preview

### Expected behavior
You shouldn't see 1$s

### Actual behavior
You see 1$s

### Device information
* Android device: Android 8, LG G8
* Fenix version: 1.0.1921

**Comment by pwd-github** [comment]
Sorry, I have no idea how to explain this one with any detail.

**Comment by hakkikaancaliskan** [comment]
Looks like problem is [here](https://github.com/mozilla-mobile/fenix/blob/master/app/src/main/res/values/static_strings.xml#L14)

**Comment by pwd-github** [comment]
I'm guessing the problem is on this line 

https://github.com/mozilla-mobile/fenix/blob/884da93184141757f7da749f97761c127849ce32/app/src/main/java/org/mozilla/fenix/settings/AboutFragment.kt#L45

If not where the variable is being set.

**Comment by hakkikaancaliskan** [comment]
As I said before, problem is on string. Should be like '%1$s' but now '1$s'

**Comment by pwd-github** [comment]
Thanks for explaining it properly the second time around.

**Comment by hakkikaancaliskan** [comment]
Sorry, I said nothing to you. Just wanna say it should be like that.
