### ISSUE TITLE
Wrong web page render on Vnexpress.net

### ISSUE THREAD

**Issue by mrxyzl** [mozilla-mobile/fenix#28631]
Steps to reproduce
1: Have Zoom on all website option in Accessibility enable
2: Navigate to vnexpress.net 

Expected behaviour

Web page render correctly

Actual behaviour
Web page seem to use wrong view port, showing the hidden panel on the side

Device name
Xperia 1 IV

Android version
Android 13

Firefox release type
Firefox

Firefox version
108.2.0

Note:
this problem happens with all extension turn off and enhance protection off 
![photo_6233542382264104992_y](https://user-images.githubusercontent.com/91355555/214307782-7a3d3f6b-db38-4e87-984d-4db996bf4fde.jpg)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-22294)

**Comment by Mugurell** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812527

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Comment by Mugurell** [comment]
Thank you for the report!
Moved the ticket to Bugzilla for more investigation by the GeckoView team.
