### ISSUE TITLE
Implement about:compat

### ISSUE THREAD

**Issue by mcl21014** [mozilla-mobile/fenix#2864]
### Why/User Benefit/User Problem
With Firefox's small market share, a lot of sites ignore it and don't play nice with non-Chromium or non-WebKit browsers, meaning Firefox only. This results in breakage the user will blame on the application and Mozilla.

### What/Requirements
Another about: entry to he generated with flags for certain problematic sites (as planned in Firefox 68 on desktop).

### Acceptance Criteria (how do I know when I’m done?)
The about:compat entry can be loaded and flags customized by the user. This feature is set to land in Firefox 68 on the desktop. Since Fenix is currently based off GeckoView 68, work could theoretically be started at the time of writing this.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-11731)

**Comment by sblatz** [comment]
This seems like a feature request to me as this behavior is not currently within our specs.

**Comment by kbrosnan** [comment]
@miketaylr @wisniewskit would be the likely people to bring this to Fenix.

**Comment by wisniewskit** [comment]
We're actually beginning our work to port the basic web compat add-on to an Android Component this quarter, and will do what we can to get `about:compat` working as well (but it's not 100% clear if it will make it into the initial port/release).

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1809976

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
