### ISSUE TITLE
[Bug] Device name not included with Sync - could cause confusion for users with multiple devices

### ISSUE THREAD

**Issue by mcl21014** [mozilla-mobile/fenix#2865]
## Steps to reproduce
1) Sign in to Firefox sync
2) Go to Settings > Account header, your user name.
3) Tap your user name.

### Expected behavior
The device name should read "Fenix on x" where x where x is the device name. Such as "Fenix on Pixel 3 XL".

### Actual behavior
Notice the default device name is a generic "Fenix".

### Device information
* Android device: Pixel 3 XL
* Fenix version: 1.0.1921

**Comment by pwd-github** [comment]
Users should be able to set device name as we're able to do on some of the other apps.

**Comment by sv-ohorvath** [comment]
Also changing the device name will not save it on first try.
Edit and change the device name.
Exist and return to the accounts settings menu.
Observe the Device name.
Sync with other devices.

-device name is not replaced on the Account settings page. If you tap to edit it, you will see the name you've put last time.
-the device name is not updated on all devices that you sync with

**Comment by jonalmeida** [comment]
> Also changing the device name will not save it on first try.
> Edit and change the device name.
> Exist and return to the accounts settings menu.
> Observe the Device name.
> Sync with other devices.
> 
> -device name is not replaced on the Account settings page. If you tap to edit it, you will see the name you've put last time.
> -the device name is not updated on all devices that you sync with

Hey @sv-ohorvath , thanks for catching this issue. Could you file it as a separate bug since this is a different issue. I'll try and get both of them fixed soon. :)

**Comment by sv-ohorvath** [comment]
Sure, here it is: #2877.

**Comment by sblatz** [comment]
Should be fixed by https://github.com/mozilla-mobile/fenix/issues/3317
