### ISSUE TITLE
[Bug] Bug in about screen

### ISSUE THREAD

**Issue by mcl21014** [mozilla-mobile/fenix#2866]
## Steps to reproduce
1) Tap the overflow menu.
2) Go to Settings > About Firefox Preview

### Expected behavior
About screen says "Firefox Preview is produced by Mozilla".

### Actual behavior
About screen says "1$s is produced by Mozilla".

### Device information
* Android device: Pixel 3 XL
* Fenix version: 1.0.1921

**Comment by cadeyrn** [comment]
Duplicate of #2862.
