### ISSUE TITLE
FNX3-16636 ⁃ [Bug] External links open in private browsing if Fenix was left in a private browsing tab

### ISSUE THREAD

**Issue by pwd-github** [mozilla-mobile/fenix#2867]
## Steps to reproduce
1. Open a private browsing tab 
1. Go to another app (or notification) 
1. Open a link from that app (not a custom tab) 

### Expected behavior
The tab is opened as a normal Fenix tab.

### Actual behavior
The tab is opened as a private browsing tab. 

### Device information
* Android device: Android 8, LG G6
* Fenix version: 1.0.1921

**Comment by cadeyrn** [comment]
I don't understand why do you think the actual behaviour is wrong. What you're describing as "expected behaviour" is totally unexpected. When I leave the app in the private mode why should a link be opened in the non-private mode? I would call this a privacy violation. It's my explicit choice to either use the private or the regular mode and I expect that Fenix remembers my choice… 😳

**Comment by pwd-github** [comment]
Try that on desktop and Fennec and you'll see that it's not normal behaviour.

Just because I forget to close a private browsing tab, doesn't mean that private browsing should hijack my browser experience. 

Maybe Fenix is evolving the private browsing experience, to provide more permanence, however that's not expected behaviour and as such, it's probably worth explaining that. But in doing so, what are the impacts to other aspects, do custom tabs act the same? 

With such an implementation though, of essentially making private browsing an isolated tab group/container, how is it possible that you all dropped the ball and collections glorified bookmarks when they too could've been a tab group/container?

**Comment by cadeyrn** [comment]
> Try that on desktop and Fennec and you'll see that it's not normal behaviour.

There is no "normal" behaviour, you can argue for both behaviours. It's a decision made by the developers to use either the one or the other mode. And yes, there may be different opinions. But in my opinions the current behaviour of Fenix makes a lot of sense and I don't want the current behaviour changed.

Fenix has another UX than Firefox for Desktop or Fennec. The mask icon on the Fenix home screen acts as a kind of "permanent browsing mode toggle", Fenix remembers the choice. If I press the mask icon it's my explicit decision to use the private mode, also the next time when I start Fenix. Just try it without using an external app: Start Fenix, switch to private mode, exit Fenix via Android recent apps, start Fenix again. As you can see you're still in private mode. That's intended behaviour. So there is no reason why Fenix should behave differently when clicking a link in an external app.

And to be honest, being accidentally in the private mode is far less a problem than the other way around.

Funnily in #2868 you argued for privacy by default a few minutes ago so I don't understand why do you don't want the more private behaviour in this case, too.

**Comment by pwd-github** [comment]
> > Try that on desktop and Fennec and you'll see that it's not normal behaviour.
> 
> There is no "normal" behaviour, you can argue for both behaviours. It's a decision made by the developers to use either the one or the other mode. And yes, there may be different opinions. But in my opinion the current behaviour of Fenix makes a lot of sense and I don't want the current behaviour changed.

I disagree. Normal is legacy behaviour. To have browser traditionally act one way and then suddenly change that and is abnormal behaviour. It's confusing and bewildering.

> Fenix has another UX than Firefox for Desktop or Fennec. The mask icon on the Fenix home screen acts as a kind of "permanent browsing mode toggle", Fenix remembers the choice. If I press the mask icon it's my explicit decision to use the private mode, also the next time when I start Fenix. Just try it without using an external app: Start Fenix, switch to private mode, exit Fenix via Android recent apps, start Fenix again. As you can see you're still in private mode. That's intended behaviour. So there is no reason why Fenix should behave differently when clicking a link in an external app.
> 
> And to be honest, being accidentally in the private mode is far less a problem than the other way around.

I can totally see the benefits for such an approach, they don't fit how I use a browser's private mode, but then I've had years to learn my current behaviour model of wanting to open something privately and expecting my browser to treat everything else as normal browsing behaviour. I'm really not arguing against the change in browser behaviour, I just hope that users can be notified that there has been a change in behaviour and that desktop and mobile act the same. I would also, and this is the most important part, expect the UI to suggest that my actions entail a permanent change in state and thus I would like to advocate for switching out the button for a toggle.


> Funnily in #2868 you argued for privacy by default a few minutes ago but here you don't want the more private approach.

I advocated for an option, but you're ultimately right. That said, I continue to want users to be informed and in control. Also, once again I'd like to advocate for switching from a button to a toggle seeing that private browsing is a sticky mode now, I feel that the change should definitely be represented with a switch/toggle and not a button. That should allay some of the confusion that users are likely to feel.

**Comment by vesta0** [comment]
Thank you @pwd-github and @cadeyrn for the helpful feedback.

@mheubusch @shorlander would love your thoughts on user expectation here.

**Comment by sblatz** [comment]
The engineering work on this is blocked on a UX decision since it's currently working as intended. Please remove the blocked flag when it's ready for engineering.

**Comment by vesta0** [comment]
I agree that this is working as intended. Will leave it to UX to comment or close.

**Comment by topotropic** [comment]
It's intended behavior – I agree though that it could be more explicit by giving people the option to open a link in a normal tab if they want to w/o having to make them do any inconvenient workarounds to get the site into normal mode. Also the other way around, if I leave FF Preview in normal mode, tap on a link and would rather be in private mode is worth to consider. @vesta0 can we track this as part of https://github.com/mozilla-mobile/fenix/issues/419

**Comment by bull500** [comment]
An user option to open links from other apps by default in private mode would be a nice solution i feel.

**Comment by vesta0** [comment]
Will address remaining request in #419
