### ISSUE TITLE
FNX3-16637 ⁃ Option for custom tabs to be private browsing tabs

### ISSUE THREAD

**Issue by pwd-github** [mozilla-mobile/fenix#2868]
### Why/User Benefit/User Problem
Custom tabs shouldn't be privacy concerns by default, however as things stand, they kinda are. I would like to be able to mitigate that problem where possible and isolate cookies and all the other benefits that private browsing provides. 

### What/Requirements
Option within Settings for isolated custom tabs. 
Custom tabs always use private browsing mode.

**Comment by joebloggs7657** [comment]
Would love for this to also be expanded as an option to affect all tabs in firefox, making private browsing always on.

**Comment by NotWoods** [comment]
We now have an option to launch all links (including custom tabs) in private mode 😄
