### ISSUE TITLE
FNX3-16639 ⁃ [Bug] Keyboard is triggered in QR code scanner menu when opening Fenix from background

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/fenix#2870]
## Steps to reproduce
1.Tap the search bar, tap the Scan button.

1. Tap on the device home button.
1. Open/Resume Fenix.
    1. Expected behavior
The QR code scanner is displayed and there should be no keyboard displayed.
    1. Actual behavior
The keyboard pops-up after resuming Fenix.
    1. Device information

* Android device: **`Samsung Galaxy Note 9 (Android 8.1.0)`**
* Fenix version: **`1.0.1922(Build #11470614 68.0-20190520141152) 5/27`**
    1. Notes
Please note that after returning to QR code scanner while the keyboard is displayed, if tapping on the back button, QR code scanner menu is closed and the user is redirected to about:home.
![2019](https://user-images.githubusercontent.com/42831109/58411415-ebb02380-807c-11e9-86c0-93fb5ce39aff.gif)UNITO-UNDERSCORE!05!UNITO-UNDERSCORE!27!UNITO-UNDERSCORE!12!UNITO-UNDERSCORE!41!UNITO-UNDERSCORE!35!

**Comment by ekager** [comment]
Should we remove the QR Fragment and return to search when the app is paused? Does it make sense to keep the camera running? It may be resource intensive

**Comment by mcarare** [comment]
QA: Is this still an issue? Could not reproduce on 2 different devices TY

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **Nightly Build #13450608 from 12/11** using the following devices:
• Google Pixel 3a (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• Motorola G4 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

► Video
![20191212_113201](https://user-images.githubusercontent.com/51314259/70609306-3b65cf00-1c0a-11ea-9b67-f02351503f2b.gif)
