### ISSUE TITLE
[Bug] No app name is shown on About Firefox Preview page

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/fenix#2875]
## Steps to reproduce
1. Go to Settings
1. Go to About Firefox Preview

### Expected behavior
The name of the app should be shown instead of the character **1$**

### Actual behavior
![75681860](https://user-images.githubusercontent.com/773158/58421633-76355a80-805e-11e9-9ad7-8cfd2df749a9.png)

### Device information
* Android device: Pixel 3
* Fenix version: 1.0.1922

**Comment by cadeyrn** [comment]
Duplicate of #2862. :)

**Comment by Amejia481** [comment]
Thanks!
