### ISSUE TITLE
FNX3-16645 ⁃ [Bug] Device name change not saved instantly

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#2877]
## Steps to reproduce
Edit and change the device name.
Exit and return to the accounts settings menu.
Observe the Device name.
Sync with other devices.

### Expected behavior
Device name updated instantly on your device. New device name synced on all devices.

### Actual behavior
-the device name is not replaced on the Account settings page. If you tap to edit it, you will see the name you've put in last time.
-the device name is not updated on all devices that you sync with

### Device information
* Android device: 
* Fenix version: 5/27

**Comment by jonalmeida** [comment]
@grigoryk I was looking into this and it seems like that after we set the device name, the changes aren't persisted in the device constellation.

When we do:
```
accountManager.authenticatedAccount()?.let {
    it.deviceConstellation().setDeviceNameAsync(newValue)
}
```

We see the device name updated on a desktop device, but when querying:
```
accountManager.authenticatedAccount()?.constellation.currentDevice?.displayName
```

Is that expected? Do we not store the update, or do we wait for the `deviceConstellationObserver` to return for those changes to take place? (in which case this is blocked by the push component)

**Comment by jonalmeida** [comment]
This should be fixed in tomorrow's build of a-c/Fenix.

**Comment by sv-ohorvath** [comment]
Verified as fixed on the 6/5 build.
