### ISSUE TITLE
[Bug] massive black bar adorns custom tabs

### ISSUE THREAD

**Issue by pwd-github** [mozilla-mobile/fenix#2885]
## Steps to reproduce
1. Open a custom (embedded) tab

### Expected behavior
No black bar at the bottom

### Actual behavior
There's a massive black bar (about the size of the awesome bar) at the bottom

### Device information
* Android device: Android 8, LG G6
* Fenix version: 1.0.1921

**Comment by cadeyrn** [comment]
Duplicate of #2789.
