### ISSUE TITLE
FNX3-16653 ⁃ [Bug] [Share] Fenix devices registers as Desktop device instead of mobile

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/fenix#2887]
## Steps to reproduce
1. Login to an account on one device.
1. Login on another with the same account.
1. Attempt to share a tab with the first device.
1. Observe

### Expected behavior
* The Fenix device is registered as a mobile device and shows a mobile icon.

### Actual behavior
* The [device _is_ registered](https://github.com/mozilla-mobile/fenix/blob/master/app/src/main/java/org/mozilla/fenix/components/BackgroundServices.kt#L72) as a mobile device but it is showing up as a **desktop device**.
* Debugging with a break-point at `deviceConstellation?.state()?.currentDevice` shows the type as `DESKTOP`.

![](https://user-images.githubusercontent.com/1370580/58427895-ecda5400-806e-11e9-84f8-ea0aa7ce84a6.png)
![](https://user-images.githubusercontent.com/1370580/58427896-ed72ea80-806e-11e9-9ff5-2769c626925d.png)

**Comment by jonalmeida** [comment]
cc: @grigoryk if you might know what could be causing this.

**Comment by bifleming** [comment]
Tracked on A/S board: https://github.com/mozilla/application-services/issues/1163

**Comment by bifleming** [comment]
@vesta0 @st3fan AS team is hoping to have this fix done in AS by 6/7.  Given that, shall we add it to the sprint board?

**Comment by jonalmeida** [comment]
@bifleming FYI: when that fix lands, updating to the latest a-s is the only change required for this bug (that too has it's own complexity for QA to consider).

**Comment by kumarharsh** [comment]
I can't even see these options - are they shipped in Fenix? Here's a screenshot:

![Screenshot_20190629-104343](https://user-images.githubusercontent.com/760112/60379984-c2443800-9a2c-11e9-98eb-20aa96f2a78d.jpg)

**Comment by ekager** [comment]
Is this still an issue? I thought the device names were resolved

**Comment by jonalmeida** [comment]
Yes it is. Putting the qa label, but the fix was in fxa so there were no changes that needed go in here.

**Comment by sv-ohorvath** [comment]
Verified this is fixed on Nightly 190731, mobile devices have the proper icons now.
