### ISSUE TITLE
FNX3-16655 ⁃ Sign in and managing account settings

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#289]
[Design](https://mozilla.invisionapp.com/share/QSR2F8UD4PN#/screens/356831058_Main_Browser_-_Settings
) 

### User stories:
* As a user, I want to be notified if there was something wrong with the sync ([screen](https://mozilla.invisionapp.com/share/QSR2F8UD4PN#/screens/357472095) and [screen|[url](https://mozilla.invisionapp.com/share/QSR2F8UD4PN#/screens/357473105]))
**==> addressed in #3523** 
* As a user, when sync issues occur, I want an option to re-connect/login or remove my account to prevent any further warnings to pop up ([screen](https://mozilla.invisionapp.com/share/QSR2F8UD4PN#/screens/357473106))
**==> addressed in #3946**
* As a user, I want to option to disconnect my account from the device but want to be made aware of what that means for my data across other devices ([screen](https://mozilla.invisionapp.com/share/QSR2F8UD4PN#/screens/357695680))
**==> addressed in #3134** 

### Acceptance Criteria
* I can update their account settings and it persists (across devices)
* I know if/when if I am successfully logged in or out
* I can see any issues or warnings if sync failed

### Requirements
* Handle logic for updating [initial settings page|#288] if logged in
* Handle sign in logic from initial settings page
* Create logic for managing account
* Create UI for managing account

**Comment by sblatz** [comment]
@bbinto I recommend we move this out of the milestone 2 backlog, and instead tie it to whatever milestone https://github.com/mozilla-mobile/fenix/issues/212 will be in.

**Comment by lime124** [comment]
@ryanfeeley can eng get started on this task in this sprint?

**Comment by vesta0** [comment]
@lime124 will share mocks with team for feedback

**Comment by lime124** [comment]
@vesta0 shared with colin earlier today and i believe he's scheduling some time to review it tomorrow. i will post the UI in the ux issue.

**Comment by sblatz** [comment]
I think we need to get a size estimate on this, @vesta0.

**Comment by vesta0** [comment]
@bbinto please update the user stories and acceptance criteria to capture what we are doing in MVP :)

**Comment by bbinto** [comment]
@vesta0 and @lime124 can you please link me to the latest mocks so I can verify the AC and US.

As per my slack message with Vesta, that's what my assumptions are for now:

This to me is an issue about making sure 1) users can login/logout of their account via Fenix 2) and manage their synced data (turn off/on). Both things we need to provide for MVP. The confusing part is maybe that screenshot, we should remove this, it was posted very early on and lists all possible syncable data types - which we know have scoped down to only bookmarks and history. So I see the sync part of the accounts management piece, but the account settings UI should also manage login/logout of the account etc.

**Comment by bbinto** [comment]
@vesta0 - updated according to latest screens.

**Comment by ryanfeeley** [comment]
@bbinto @sblatz *Manage account* does what it does on every Firefox, it opens accounts.firefox.com/settings in a tab (or WebView, your choice for MVP), though there are some special parameters you will want to pass. @shane-tomlinson can provide those.

**Comment by irrationalagent** [comment]
So currently on Fennec the equivalent UI will open about:accounts?action=manage which displays a uri that is built using this https://searchfox.org/mozilla-central/source/mobile/android/chrome/content/aboutAccounts.js#181

I believe that will translate to `https://accounts.firefox.com/settings?service=sync&context=fx_fennec_v1`

furthermore, although we don't do it currently for fennec, we *should* be appending an entrypoint parameter that would tell us where the user entered from, e.g:

`https://accounts.firefox.com/settings?service=sync&context=fx_fennec_v1&entrypoint=sync-settings`

however, @shane-tomlinson or @vladikoff should weigh in to confirm all this (is the context parameter value staying the same for, for example? are there are other parameters that we need to handle the case of Fenix specifically?)

**Comment by vladikoff** [comment]
@irrationalagent Hm short answer would probably be - nothing is staying the same as Fennec. Fenix is using an OAuth flow for login. For manage account, I don't think we have anything setup yet from the UI. Once we have a "Manage Account" button we can add an entrypoint parameter to it.

**Comment by ryanfeeley** [comment]
@sblatz I didn't think device name was in for MVP, but was imagining we use standard Android.
![image](https://user-images.githubusercontent.com/68213/56064343-cb800b80-5d3f-11e9-9f7d-89086137e44a.png)

**Comment by bbinto** [comment]
@ryanfeeley @vladikoff - 
ok, so to recap, we can and should include "Manage Account" in MVP.

@ryanfeeley - what source do you reference that device name change is out of MVP?

@sblatz - can you please let us know if you are blocked/any further information you need?

**Comment by rfk** [comment]
The FxA component should provide a method to call to get the "manage account" URL, rather than requiring the application to construct it by hand, ref https://github.com/mozilla/application-services/issues/750

**Comment by ryanfeeley** [comment]
> @ryanfeeley - what source do you reference that device name change is out of MVP?

The first reference I've seen to device renaming was just added to this issue a few days ago.

Our other mobile apps lacked this feature for a very long time, so I would not prioritize it highly.

That said, above is a solution that can work if you choose to include device renaming.

**Comment by bifleming** [comment]
@ryanfeeley can you give me an update on this? Do we need a decision to be made?

**Comment by ryanfeeley** [comment]
@bifleming This is not my call, but as I stated above, I can't imagine device renaming is an MVP feature.

**Comment by grigoryk** [comment]
Device renaming is currently blocked by https://github.com/mozilla-mobile/android-components/pull/2670, which is going in the next few days. I just filed an issue to integrate device management URLs in a-c: https://github.com/mozilla-mobile/android-components/issues/2824

**Comment by vladikoff** [comment]
We might need a separate bug for this, but as a first step we should prioritize and build the UI from @ryanfeeley soon:  

<img src=https://user-images.githubusercontent.com/128755/56918773-e74c1700-6a8c-11e9-831b-1e7563b0d812.png width=300 />

(https://mozilla.invisionapp.com/share/QSR2F8UD4PN#/screens/357470305) cc @st3fan

**Comment by bifleming** [comment]
@grigoryk is this still blocked?

**Comment by linacambridge** [comment]
More things we need for a complete sync manager experience:

* New UI for signing in to emphasize pairing.
* "Choose what to sync" (mozilla-mobile/android-components#1584)

**Comment by vesta0** [comment]
Addressed in separate issues (see edited description)
