### ISSUE TITLE
FNX3-16656 ⁃ [Bug] [Share] Sending tab from another device shows empty title.

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/fenix#2890]
### Steps to reproduce
1. Have two devices with fenix on it.
1. Send a tab from one to the other.

### Expected
* The notification which eventually shows up (hit the sync now button for faster turn-around), should have a title.

### Actual
![](https://user-images.githubusercontent.com/1370580/58431564-69bffa80-807c-11e9-804c-7f8c927f597c.png)

**Comment by sv-ohorvath** [comment]
Verified as fixed on the 5/28 build.
