### ISSUE TITLE
FNX3-16657 ⁃ [Bug] Tab text is cut off in save to collections mode

### ISSUE THREAD

**Issue by AmyYLee** [mozilla-mobile/fenix#2891]
Steps to reproduce:

1. Open a new tab from homescreen with a long title (https://www.mallofberlin.de/en/stores/bestworschtintown)
1. Click on "Save to collection"
1. Select tab and hit "save"
1. In the next screen where it asks where to save the tab, the text in the tab is cut off (see screenshot)

![Screenshot](https://user-images.githubusercontent.com/5992746/58432317-b35e1480-807f-11e9-9c0c-1c9db1684c61.png)UNITO-UNDERSCORE!20190527-125324!

**Comment by AmyYLee** [comment]
@sblatz @ekager

**Comment by sv-ohorvath** [comment]
Verified as fixed on the 5/30 build. devices: Nexus 5, HTC Desire 820, Mi Pad 2 (Android 5.1)
