### ISSUE TITLE
FNX3-16661 ⁃ [Collections] "Select All" option should switch to "Deselect All" on tap

### ISSUE THREAD

**Issue by AmyYLee** [mozilla-mobile/fenix#2898]
Steps to reproduce 

1. Open several tabs from homescreen
1. Tap on "Save to collection" button on homescreen
1. Select "Select all" in top right corner in saving collection mode

Actual: 
Still shows "Select all"

Expected:
Text should switch to "Deselect all" where the user can deselect all tabs on tap

![](https://user-images.githubusercontent.com/5992746/58434203-72b6c900-8088-11e9-9159-791470228ff4.png)

**Comment by AmyYLee** [comment]
@sblatz

**Comment by sv-ohorvath** [comment]
Verified as fixed on the 5/30 build.
