### ISSUE TITLE
FNX3-16662 ⁃ [Collections] Animation is missing after saving a collection

### ISSUE THREAD

**Issue by AmyYLee** [mozilla-mobile/fenix#2899]
After the user goes through the saving a collections flow and returns to the homescreen, it should scroll down to where collections are located and there should be an animation to highlight the collection where the tabs are saved.

Animation reference:
https://drive.google.com/file/d/1mtg3KDfu5tQQpFPnKArVbvYNYfR4HVDo/view

Spec:
![](https://user-images.githubusercontent.com/5992746/58434781-5b2d0f80-808b-11e9-95e4-abebe6e0915c.png)

**Comment by AmyYLee** [comment]
@ekager @sblatz

**Comment by vesta0** [comment]
@AmyYLee why is this a UX P1?

**Comment by AmyYLee** [comment]
> @AmyYLee why is this a UX P1?

This animation is important because it's purpose is informative - to indicate where your collection is saved. Especially if you have a long list of opened tabs and the collections section is hidden from view.

**Comment by vesta0** [comment]
Thank you for explaining that @AmyYLee :)

**Comment by mheubusch** [comment]
@vesta0 just confirming with Amy that Yes, this should be an MVP blocker.

**Comment by ekager** [comment]
I have added an animation that will :
1. On a new collection: Scroll to collections, animate the selected ring in and out
2. On adding to an existing collection: Scroll to collections section of home screen

**Comment by sv-ohorvath** [comment]
@ekager 
1. Scrolls to the new collection but the ring animation is not always visible, or it happens too early while the create collection screen is still fading out: Nexus 5 (Android 6.0.1), Samsung Note 8 (Android 9). Visible on a tablet: Galaxy Tab S3 (Android 8)
2. Adding to an existing collection doesn't scroll down to it if it's out of view. Scrolls down to the last tab, the most: Nexus 5 (Android 6.0.1), Samsung Note 8 (Android 9), Galaxy Tab S3 (Android 8)

Gif from the Nexus 5:
![20190612_124113](https://user-images.githubusercontent.com/4037709/59340888-83657100-8d0f-11e9-8ff0-0d7bf848ac42.gif)

**Comment by ekager** [comment]
@AmyYLee I've implemented these animations. Please view in the latest version of Fenix to see and review!

**Comment by ekager** [comment]
And @sv-ohorvath I've improved the animation, it should scroll to any collection in the list now when created or added to and highlight!

**Comment by softvision-miralobontiu** [comment]
Verified as fixed with the latest build 1.0.1924 (#11650657) with Samsung Galaxy Note 8 (Android 9), Samsung Galaxy Tab S3 (Android 8), and Sony Xperia Z5 Premium (Android 7.1.1).
