### ISSUE TITLE
[Bug] Opening a Collection scrolls the view up

### ISSUE THREAD

**Issue by smaug----** [mozilla-mobile/fenix#2902]
## Steps to reproduce
Have several Collections, so that the viewport scrolls. Open the last one, viewport is scrolled up and the Collection isn't visible anymore (need to scroll down).

### Expected behavior
Viewport shouldn't scroll up

### Actual behavior
Viewport scrolls up

### Device information
* Android device: Honor 7, Android 6
* Fenix version: 1.0.1921

**Comment by vesta0** [comment]
We may have a duplicate bug for this but I couldn't find it.

**Comment by vesta0** [comment]
@mheubusch to look at this, thank you.

**Comment by mheubusch** [comment]
Closing - this is a duplicate of/will be addressed in https://github.com/mozilla-mobile/fenix/issues/3004
