### ISSUE TITLE
FNX3-16667 ⁃ [Bug] "Device name" dialog isn't behaving correctly

### ISSUE THREAD

**Issue by grigoryk** [mozilla-mobile/fenix#2905]
On a fresh install open sync settings, tap "device name". The dialog starts off as empty, but it should have the default name of the current device. (e.g. "Firefox Preview").

Then, change the name, e.g. to "Firefox TEST", and sign out. Now sign-in again (this creates a new device record), and open "device name" dialog. It will display "Firefox TEST", not the default name.

So, what needs to happen:
1) clear that pref's value on signout
2) set that pref's value in the device constellation observer, once we get a current device record

**Comment by vesta0** [comment]
@grigoryk is this A-C or Fenix work?

**Comment by jonalmeida** [comment]
> is this A-C or Fenix work?

Fenix. I can take a look at this since I'm aware of the issue.

**Comment by softvision-miralobontiu** [comment]
Cannot verify due to #3678

**Comment by abodea** [comment]
Verified as fixed on the latest build 6/27 with a Google Pixel XL(Android Q beta 4).
