### ISSUE TITLE
FNX3-16668 ⁃ [Bug] ibanez.com does not load on Fenix

### ISSUE THREAD

**Issue by smaug----** [mozilla-mobile/fenix#2906]
## Steps to reproduce
Try to load https://www.ibanez.com

### Expected behavior
The website should load (as it loads in Fennec).

### Actual behavior
Website's throbber keeps spinning.

### Device information
* Android device: Honor 7, Android 6
* Fenix version: 1.0.1921

**Comment by smaug----** [comment]
Aha, this happens only when tracking protection is on. (and it is on by default)

**Comment by vesta0** [comment]
@brampitoyo let's think of a creative solution for letting users know that a site may be breaking due to tracking protection.

**Comment by mheubusch** [comment]
@AmyYLee for your consideration as you design ETP.

**Comment by vesta0** [comment]
Let's track this solution here #2166
