### ISSUE TITLE
FNX3-16670 ⁃ [Bug] input lag on reddit

### ISSUE THREAD

**Issue by andreicristianpetcu** [mozilla-mobile/fenix#2909]
## Steps to reproduce
go to a reddit page like this one https://www.reddit.com/r/news/comments/bto8ni/maine_bars_residents_from_opting_out_of/
Type in a comment.

### Expected behavior
After each leter I type, I expect to see it on the screen.

### Actual behavior
There is a lag from time to time and letters do not get displayed immediatly.

### Device information
* Android device: ?
* Fenix version: ?

**Comment by vesta0** [comment]
@bifleming how do we tag the performance team here?

**Comment by ekager** [comment]
Have you still been seeing this in the latest builds @andreicristianpetcu ? :) We just updated to a new GV version

**Comment by andreicristianpetcu** [comment]
Seems fine now. Will open a new issue if I see it again. Thank you @ekager
