### ISSUE TITLE
[meta] Additional Settings Options

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#291]
Non-MVP Settings Options:

* Additional Sync options under accounts (Open Tabs, Passwords, Addresses, Credit Cards, Settings)
* Access to 3rd party password manager
* Saved Credit cards
* Saved Addresses
* Advanced tracking protection and cookie options
* Language

(Full design mock found [here](https://github.com/mozilla-mobile/fenix/issues/187#issuecomment-458372653))

**Comment by sblatz** [comment]
I think this should serve as another meta for these separate issues. It's too large to tackle in one ticket.

**Comment by ekager** [comment]
Just a UX note, material design guidelines recommend not having the toolbar title have to be cut off by "..." so for "Credit cards and addresses" we may have to be creative with this long title

**Comment by vesta0** [comment]
Tracked by `Feature:Settings` label
