### ISSUE TITLE
[Bug] Sign in via pairing doesn't work

### ISSUE THREAD

**Issue by softvision-miralobontiu** [mozilla-mobile/fenix#2910]
## Steps to reproduce
1. On mobile, Fenix, go to Settings - Sign in with a QR code (Pair with Firefox Desktop).
1. On desktop (Firefox), sign in with valid credentials.
1. On desktop (Firefox), go to account.firefox.com/pair and scan the QR code.

### Expected behavior
On desktop, the address account.firefox.com/pair is not valid. 

### Actual behavior
The user should be able to scan the QR code.

### Device information
* Android device: Huawei P9Lite (Android 6) / Windows 10
* Fenix version: 1.0.1922 (#11471807)
* Reference Browser version: 1.0.1922 (11471216)

![Screenshot](https://user-images.githubusercontent.com/40694158/58460996-62a9f280-8137-11e9-93eb-bf5b4929445c.png)UNITO-UNDERSCORE!1!

**Comment by TitanNano** [comment]
It works if you follow the instructions... Fenix asks the user to go to "firefox.com/pair" which redirects to "accounts.firefox.com/pair" and not "account.firefox.com/pair"

![Screenshot_20190528-204613](https://user-images.githubusercontent.com/4500858/58503994-03c19900-818a-11e9-8746-a561e868586d.png)

**Comment by kbrosnan** [comment]
Sounds like this is invalid. At best it is a accounts server bug. If we want to capture common typos open a bug in Bugzilla for the account server.
