### ISSUE TITLE
FNX3-16673 ⁃ [Bug] Image with page link opened in private tab, opens just the image

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#2911]
### Steps to reproduce
1. Go to cnn.com and long tap the image of the top news article.
1. Tap Open link in Private tab.
1. Verify the link opened in PB.
    1. Expected behavior
-The article URL should be loaded.

### Actual behavior
-The image URL is loaded.

### Device information
* Android device: LG Nexus 5 (Android 6.0.1), Pixel (Android 9)
* Fenix version: 5/28

**Comment by sblatz** [comment]
Sounds like this is blocked on the [a-c issue Emily filed](https://github.com/mozilla-mobile/android-components/issues/3434)

**Comment by sblatz** [comment]
I've submitted an [a-c patch](https://github.com/mozilla-mobile/android-components/pull/3450). We will get this fix for free once it lands :)

**Comment by softvision-miralobontiu** [comment]
This is not fixed yet.
Tested with the latest build 1.0.1926 (#11760617) with Nexus 5 (Android 6.0.1), and Samsung Galaxy S8 (Android 9).
I'll remove the "QA needed" flag and mark it as "in progress".
![2019_06_25](https://user-images.githubusercontent.com/40694158/60080515-bdd00480-9738-11e9-94bc-4ca2182f1297.gif)

**Comment by sblatz** [comment]
This is blocked and waiting for the next a-c release.

**Comment by AndiAJ** [comment]
Hi, I can still reproduce this issue  on the latest Fenix build (1.0.1926 Build #11771809 from 26/6) using the following devices:

• Google Pixel 3XL (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Sony Xperia Z5 Premium (Android 7.0)

**Based on this, I'll remove the "QA needed" label.**

**Comment by sblatz** [comment]
I'm confused. I'm unable to reproduce this on the latest nightly (6/27) on my Galaxy S9.

Here's a demo:

![switch bug](https://user-images.githubusercontent.com/4400286/60290037-b477a100-98cc-11e9-8a15-d561665d2ddc.gif)

@AndiAJ

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest Fenix build (#11790617 from 28/6) using the following devices:

• Google Pixel 3XL (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7.0)

►Video from Google Pixel 3XL
![2019_06_28_10_50_26](https://user-images.githubusercontent.com/51314259/60326956-61b4ec80-9993-11e9-8c6b-411bf2e7e56e.gif)
