### ISSUE TITLE
Tweak about pages need for mobile

### ISSUE THREAD

**Issue by pwd-github** [mozilla-mobile/fenix#2912]
### Why/User Benefit/User Problem
This is more of a polish request. Mobile has replaced desktop as the means by which most people access the Internet and without going into whether a modern application should be mobile first or not, the users of mobile should feel like first class citizens, the about pages have clearly been designed for desktop and thus could use some minor tweaking to make them feel like mobile was at least a consideration. 

### What/Requirements
New stylesheets
Fenix logo for about:logo

### Acceptance Criteria (how do I know when I’m done?)
All text legible, buttons pressable and all of the extraneous white space minimised.

**Comment by lime124** [comment]
hi @pwd-github - i believe this ticket address your concerns? #4776 . if that's the case can you please close this issue. if it doesn't, can you please clarify more and perhaps provide a screenshot? thanks!

**Comment by pwd-github** [comment]
Hi @lime124

You can check the likes of
about:firefox
about:config
about:support
about:profiles
about:about
Etcetera.

**Comment by lime124** [comment]
i apologize, i just want to clarify where/ how you are accessing those pages. it appears the STR you are doing:
1. open fenix
2. tap search bar
3. type about:firefox (or any of the others)
4. observe

am i following that correctly? if so, i believe those are webpages handled by a different team though i'll confess i don't actually know how they are made or who works on them. the ones i tried seemed to either not work or not be relevant to fenix. ping @liuche for advice!

the STR for the issue i referenced above is accessing the about page by navigating to settings in the fenix app. it appears you are referencing something else. sorry for the confusion!

**Comment by pwd-github** [comment]
That is indeed the correct STR.

**Comment by liuche** [comment]
Revisiting this bug, we should remove about:logo actually, will update comment 0.

We won't be supporting all the about:X pages, but let me highlight a few:

about:config is supported on Nightly and Beta
We don't support different profiles on Fenix yet - you can follow along in containers work though! #10581

Check out about:about for the items we support.
