### ISSUE TITLE
FNX3-16675 ⁃ [Bug] Fenix crashes when trying to allow "Persistent Storage" permission

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/fenix#2913]
## Steps to reproduce
1. Install and launch Fenix.
1. Access **`https://permission.site/`** website.
1. Scroll down until you find **`Persistent Storage`** permission option and tap on it.
    1. Expected behavior
A pop-up should be displayed asking for permission regarding **`Persistent Storage`.**
    1. Actual behavior
Fenix crashes when tapping on the **`Persistent Storage`** permission button.
    1. Device information

* Android device: Samsung Galaxy Note 9(Android 8.1.0), Google Pixel 3(Android 9).
* Fenix version:  **`1.0.1922 (#build11480607) 28/5`**
    1. Notes
For more details please see the attachments: [video](https://drive.google.com/file/d/1V9TBs6KCliKyXVCMx7BC_fO8VeE-n4NN/view?usp=sharing) and [logcat.txt](https://github.com/mozilla-mobile/fenix/files/3226689/logcat.txt).
Also, I noticed in adb that this is returned exactly when Fenix crashes:
{{ 9705-9705/? E/Zygote: isWhitelistProcess - Process is Whitelisted 9705-9705/? E/libpersona: scanKnoxPersonas 9705-9705/? E/libpersona: Couldn't open the File /data/system/users/0/personalist.xml - No such file or directory}}
* Note that on Google Chrome the pop-up permission is displayed.
* Reference Browser crashes too.
* Fennec RC doesn't display the pop-up permission but it didn't crashed.

**Comment by Amejia481** [comment]
Showing the **`Persistent Storage`** dialog will be covered after MVP on this issue https://github.com/mozilla-mobile/android-components/issues/3153. For now, we are avoiding the crash.

**Comment by sv-ohorvath** [comment]
No more crashing on the 5/31 build.
