### ISSUE TITLE
[Dev] Missing setup instructions for Windows users

### ISSUE THREAD

**Issue by MyIsaak** [mozilla-mobile/fenix#2914]
### Why/User Benefit/User Problem
* Windows users feel rather discriminated when reading the README with no setup instructions for using git hooks except for Mac/Linux.
* From the StackOverflow developer survey in 2019, the [majority of developers still use Windows as their primary OS](https://insights.stackoverflow.com/survey/2019#technology-_-developers-primary-operating-systems) so this issue should be addressed.

### Acceptance Criteria (Added by PM. For EPM to track when a Meta feature is done)
* Allowing a developer to successfully setup git-hooks on Windows

### What / Requirements (Added by PM and Eng Manager)
* A change to the README.md file that specifies a command to run for Windows

**Comment by MyIsaak** [comment]
I've included a pull request #2915

**Comment by sblatz** [comment]
Closing this as it was addressed by @MyIsaak's PR: #2915
