### ISSUE TITLE
FNX3-16681 ⁃ metrics.yaml: Request data review for probes or add URLs to file

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/fenix#2920]
Created this issue just so that it doesn't fall through the cracks. If there are issues for that already then just close please. :grinning:

@Dexterp37 mentioned on Slack:

> Hey folks, I just noticed that a few metrics in Fenix metrics.yaml file do not have a data review ( see https://github.com/mozilla-mobile/fenix/blob/06bf7a4da77a013a1fd822d5431ebd241e683a74/app/metrics.yaml#L86 ) : they are marked as TBD

**Comment by vesta0** [comment]
Coping @boek who is a data steward.
