### ISSUE TITLE
Fenix Beta Security Testing Results

### ISSUE THREAD

**Issue by ghost** [mozilla-mobile/fenix#2922]
Apologies to the community that this is a bit of a mystery bug without much detail. We are doing some security testing and we are not ready to publish the results yet, but we do want to keep track of it in the Fenix GitHub milestone.

The following bug tree lists the findings for Fenix Beta. They need to be triaged and tracked in Bugzilla.

https://bugzilla.mozilla.org/showdependencytree.cgi?id=1549190&hide_resolved=0

It is fine to lands patches, there is no way to hide that work.

**Comment by liuche** [comment]
@st3fan can you give me access to this bugzilla bug? And to any relevant people too who might need to understand what it is (vesta, eng, etc)

**Comment by sblatz** [comment]
@sarentz is there engineering action we can take on this or should we close it?

**Comment by kbrosnan** [comment]
@liuche You should have access to all the bugs on that dependency list

**Comment by colintheshots** [comment]
@kbrosnan Could I please get access to the bug tree as well?

**Comment by kbrosnan** [comment]
done

**Comment by colintheshots** [comment]
I'll spend some time this sprint triaging each of the issues, assessing if they're real, and what to do about them.

**Comment by colintheshots** [comment]
At this point, the remaining issues are either not actionable or are in the hands of our app sec team. I'll close this bug pending results from their investigations.
