### ISSUE TITLE
[Bug] Icons should be fetched for all tabs from the domain

### ISSUE THREAD

**Issue by pwd-github** [mozilla-mobile/fenix#2924]
Before I fill this out properly, let me state clearly that I'm unable as to how to reproduce this and so I'm kinda guessing.

## Steps to reproduce
1. Load five tabs from the same domain
1. Swipe the app from memory
1. Load one of the five tabs

### Expected behavior
Upon managing to fetch the icon for one of the tabs, all of the tabs should have the icon applied.

### Actual behavior
Only one of the tab icons are loaded.

### Device information
* Android device: Android 8, LG G6
* Fenix version: 1.0.1922

**Comment by NotWoods** [comment]
This is pretty tough to do since individual pages can have their own icons. Since May we've made the icon loading more consistent. I don't think this is needed anymore so I'm going to close the issue, feel free to respond if you disagree and I'll reopen it.
