### ISSUE TITLE
[Bug] Fenix never fetches the icon for GitHub

### ISSUE THREAD

**Issue by pwd-github** [mozilla-mobile/fenix#2925]
## Steps to reproduce
1. Load GitHub
1. Press tabs button

### Expected behavior
The tab should display the favicon for GitHub

### Actual behavior
You see a big G

### Device information
* Android device: Android 8, LG G6
* Fenix version: 1.0.1922

**Comment by pocmo** [comment]
Yeah, unfortunately GitHub doesn't give us good candidates. This should change with #2047.

**Comment by pwd-github** [comment]
You sure you meant #2047 @pocmo

**Comment by pwd-github** [comment]
So I had a quick look at the source, imagine an elephant in a labcoat.

But I saw
```
<link rel="fluid-icon" href="https://github.com/fluidicon.png" title="GitHub">
```

So my question/suggestion is, could Fenix do `icon = (fluid-icon) ? fluid-icon : icon;`? Or am I oversimplifying it?

**Comment by cadeyrn** [comment]
Fixed by https://github.com/mozilla-mobile/android-components/pull/3536.
