### ISSUE TITLE
FNX3-16686 ⁃ Vibrate phone upon successful pairing

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla-mobile/fenix#2928]
Stolen from Whatsapp behaviour as reported by @eoger.

Let's vibrate Fenix when sync pairing is successful.

**Comment by ekager** [comment]
This is pretty simple to add. Any idea of how long we want to vibrate for? The API I see we just pass in the MS.

**Comment by NotWoods** [comment]
I think 500 ms should be fine.

**Comment by anhanh11001** [comment]
Can I work on this ?

**Comment by NotWoods** [comment]
Go for it @anhanh11001!

**Comment by anhanh11001** [comment]
@NotWoods https://firefox.com/pair redirect me to an unsupported page. What should I do ?

**Comment by vladikoff** [comment]
@anhanh11001 hey, which browser are you opening that in?

![image](https://user-images.githubusercontent.com/128755/65908210-f57fc580-e393-11e9-8e85-0fa2a0339caa.png)

**Comment by anhanh11001** [comment]
I was using Chrome, do I need to use Firefox for that? @vladikoff

**Comment by vladikoff** [comment]
ye

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the **latest Nightly Build #13250607 from 11/21** using the following devices:
• Google Pixel 3a XL (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

✔ The devices vibrate once the QR pairing code is successfully scanned. 📳
