### ISSUE TITLE
FNX3-16687 ⁃ [Bug] date picker isn't styled correctly

### ISSUE THREAD

**Issue by pwd-github** [mozilla-mobile/fenix#2929]
## Steps to reproduce
1. Find a form where you need the date picker 
1. Open it

### Expected behavior
Things are aligned properly with proper uniform margins. 

### Actual behavior
Everything looks independent of one another. 

### Device information
* Android device: Android 8, LG G6
* Fenix version: 1.0.1922

**Comment by pwd-github** [comment]
Image: https://i.imgur.com/L6ZnMkz.jpg

**Comment by ekager** [comment]
@pwd-github are you still seeing this on your device? On my device it could certainly mathch the Fenix theme more closely, but it doesn't look as broken as the above imgur link

**Comment by darkwing** [comment]
I'm seeing the following:

<img width="413" alt="DatePicker" src="https://user-images.githubusercontent.com/46655/69442600-7911bf00-0d12-11ea-9f5b-c8bc3c173faf.png">

I feel like we could probably close this issue.

**Comment by NotWoods** [comment]
We updated the date and time picker a while back so this issue should be fine to close.
