### ISSUE TITLE
FNX3-16688 ⁃ About Settings Page

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#293]
Parent: #115 

* Link to rate Fenix
* Give feedback on Fenix
* Help pages

<img width=200 src=https://user-images.githubusercontent.com/51007/51877957-df6bd080-23d2-11e9-816a-e0e3356d2b2d.png>
<img width=200 src=https://user-images.githubusercontent.com/51007/51878025-104c0580-23d3-11e9-8f27-30c9ff2740f6.png>

(Full design mock found [here](https://github.com/mozilla-mobile/fenix/issues/187#issuecomment-458372653))

**Comment by sblatz** [comment]
@brampitoyo do we know how we want the "about" page to look?

 For reference, this is what we do for Focus:
<img width=300 src=https://user-images.githubusercontent.com/4400286/52575169-99e7d400-2dd2-11e9-9721-39796a5a1ea9.png>

**Comment by rtanglao** [comment]
@sblatz so you need a sumo article that is linked from "Learn more", is that right? if so please file a bugzilla bug product:support.mozilla.org component: knowledge base content and needinfo joni, thanks!

**Comment by jonisavage** [comment]
Here's an in-product URL you can use: https://support.mozilla.org/1/mobile/%VERSION%/%OS%/%LOCALE%/about-settings-page

We'll work on the content later on.

**Comment by brampitoyo** [comment]
@sblatz A very early first draft to give you an idea of what this page can look like.

<img width="360" src="https://user-images.githubusercontent.com/51007/52755124-b2b9e900-3061-11e9-9f90-92dffff86254.png">

**Comment by sblatz** [comment]
@rtanglao: To clarify we will need a "Help" article (linked from the about page). That "learn more" link will actually not exist. Is the link @jonisavage gave above the help one?

**Comment by jonisavage** [comment]
@sblatz In that case, let's change the URL to https://support.mozilla.org/1/mobile/%VERSION%/%OS%/%LOCALE%/firefox-android-help. 

I've edited my comment above to show this new URL too.

**Comment by jonisavage** [comment]
@sblatz Looking at the mocks, I'm guessing we need to link to the Help landing page with a list of articles for Fenix, right? Not a specific article? 

Either way, you can use the link I've provided.

**Comment by sblatz** [comment]
@jonisavage for reference, this is what our "Help" button links to on Focus: https://support.mozilla.org/en-US/kb/what-firefox-focus-android 😄

**Comment by jonisavage** [comment]
I think I should link it to the product landing page because Fenix will have more features than Focus (i.e. more articles). 

When Focus first launched, we didn't have enough articles to justify a landing page, so we created a single article. Let me know if you disagree. 

I can always change the target article, but your link will remain the same.

**Comment by sblatz** [comment]
I will need to add a few SUMO links to this per a conversation with Paul, so I'm moving this to next week's sprint. It is mostly done, though.

**Comment by sblatz** [comment]
Paul recommends we go with the following text:

> "Firefox is a faster web browser designed by Mozilla. Our mission is to foster a healthy, open internet."
Learn more (link to the Mozilla mission at https//www/mozilla.org/en-GB/about/manifesto)

I'm assuming we'll want to replace Firefox with Fenix, but this text seems reasonable to me. Can I get an "OK" on this @brampitoyo? 

Other notes: 
> One thing that is missing from this page is an embedded page within the app detailing the users open source rights and the open source license used.  This is really important from an open source perspective.  In Fennec there is a link to about:rights from the about:firefox screen.  Fx Lite has a Your Rights/license link in the About page and Focus has a Your Rights page all detailing the open source license used, a trademarks warning, where the code can be downloaded from and if there is tracking protection/turbo mode, separate license information for Disconnect.

**Comment by brampitoyo** [comment]
@sblatz The text looks okay for now.

I have engaged @mheubusch to review and suggest content before we release. Because the revised copy will mostly be text, any change we make should (hopefully) be simple.
