### ISSUE TITLE
[Bug] Unable to share text

### ISSUE THREAD

**Issue by pwd-github** [mozilla-mobile/fenix#2930]
## Steps to reproduce
1. Load this page 
1. Long press text 

### Expected behavior
Context menu should provide option to share text 

### Actual behavior
It's kinda bare-bones. 

### Device information
* Android device: Android 8, LG G8
* Fenix version: 1.0.1922

**Comment by shizunge** [comment]
I have the same problem.
When I select a text, I see "Copy" and "Select all" and other 5 entries from other apps.
(comparing to the stable firefox android release, I see "Copy" "Share" "Select All" and "Google Search", no entries from other apps. "Share" and "Google Search" are missing from Fenix.)

Android: 9, Pixel 3
Fenix: nightly 190719 06:03

**Comment by vesta0** [comment]
Will be addressed in #533
