### ISSUE TITLE
FNX3-16690 ⁃ [Bug] Snackbar appears over URL bar

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#2931]
When you save to collection (or otherwise trigger a snackbar) when in the browser fragment, it obscures the url bar, making it impossible to navigate away from your current page until it's dismissed.

![Untitled 2019-05-28 09](https://user-images.githubusercontent.com/4400286/58494742-a6e2c600-812a-11e9-93d3-ed8508b872a6.gif)UNITO-UNDERSCORE!26!UNITO-UNDERSCORE!12!

**Comment by sv-ohorvath** [comment]
Verified as fixed on the 5/31 build.
