### ISSUE TITLE
[Bug] Pixel 3 doesn't seem to get software updates

### ISSUE THREAD

**Issue by mozillamarcia** [mozilla-mobile/fenix#2936]
## Steps to reproduce
* Check the GPS for an update

### Expected behavior
* A software update is available

### Actual behavior
* My Pixel 3 running Android Pie is stuck on the build from 5-26
* My Pixel running Android Q received an update to the 5-28 build
* I think this has happened before. I followed the steps of joining the Google group, getting the build from GPS, etc.

### Device information
* Android device: Pixel 3
* Fenix version: 1.01921 (Build #11460616)

**Comment by kbrosnan** [comment]
Works for me on a Pixel 3 running Android 9 and a Nexus 10 running Android 5.1. There is not much we can do to affect Google Play update behavior.

**Comment by mozillamarcia** [comment]
![Screenshot_20190528-165056](https://user-images.githubusercontent.com/2171777/58511755-72dac580-8169-11e9-8932-fdaccdb71f00.png)

Here is a screenshot showing what happens when I go into Apps and check where it is installed from. As I said, I had this issue before on the Pixel 3 and I had to uninstall the app and start over again to get the latest version of the app. Not sure why it has happened 2x to me. On my Pixel device, the app shows corrected when I go to Apps | Settings and Notifications | Firefox Preview | Advanced | App Details.

**Comment by mozillamarcia** [comment]
It looks as if this happened again, as I am marooned on the 5/31 build.

**Comment by mozillamarcia** [comment]
I gave up on dogfooding on this device. I don't know why I was marooned on the build, but I hope it doesn't happen to other users.

**Comment by kbrosnan** [comment]
Did you leave the testing group? Are updates disabled? Open Google Play and tap on the three bar menu on the top left. Select settings check the `Auto update apps` value.  If it is not a primary device doing a factory reset may be another option.

Going to close this as there is nothing we can fix on the Fenix side. Happy to brainstorm other things that could be affecting this specific device.
