### ISSUE TITLE
FNX3-16694 ⁃ [Private Browsing Mode] Remove save to collection in PBM from chrome menu

### ISSUE THREAD

**Issue by AmyYLee** [mozilla-mobile/fenix#2938]
Please remove "save to collection" from the chrome menu when in PBM. It defeats the purpose of PBM if the user is able to save a site and it's associated history into a collection. 

![Screenshot](https://user-images.githubusercontent.com/5992746/58504511-c7297980-8158-11e9-911a-b47f271120c4.png)UNITO-UNDERSCORE!20190528-145437!

**Comment by vesta0** [comment]
Thanks for filing this @AmyYLee. I noticed it the other day and meant to file a ticket. It's an important one.

**Comment by softvision-miralobontiu** [comment]
Verified as fixed on the latest build 1.0.1922 (#11510609), with Motorola Moto G6 (Android 8.0), and Sony Xperia Z5 Premium (Android 7.1.1).
