### ISSUE TITLE
FNX3-16695 ⁃ [Share] Hide send tab on FxA error

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/fenix#2940]
Since we aren't adding error states to the share sheet just yet (see #2897), we need to hide the send tab section if we encounter an error.

(Added by Sawyer -- For QA)

## STR:
1. Sign in to sync on Fenix
1. Change your password on desktop
1. See an error in the settings page
1. Open a tab
1. Press the browser menu button 
1. Press the "share" button

## Expected
1. The "send tab" section does not appear

## Actual
1. The "send tab" section **does** appear

**Comment by softvision-miralobontiu** [comment]
It is not entirely fixed.
Tested with the latest build 1.0.1926 (#11760617) with Samsung Galaxy S8 (Android 9), Xiaomi mi4i (Android 5.0.2), Nexus 5 (Android 6.0.1).

On Xiaomi device, the "Send to device" button is displayed, not functional though - please see the attached screenshot.
On Samsung and Nexus, no such button is displayed.

![Xisomi-mi4i](https://user-images.githubusercontent.com/40694158/60082447-6c297900-973c-11e9-9591-d136cc689d04.png)

**Comment by jonalmeida** [comment]
Hmm.. we probably need to add the `account_header` visibility changes to the `else` block.

**Comment by sblatz** [comment]
Oops. On it :)

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest Fenix build (1.0.1926 Build #11780608 from 27/6) using the following devices:

• Google Pixel 3XL (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)

►Google Pixel 3XL video:
![2019_06_27_13_23_46](https://user-images.githubusercontent.com/51314259/60259631-4f2dab00-98e0-11e9-9592-3b865a49a7a9.gif)
