### ISSUE TITLE
FNX3-16696 ⁃ [Collections] Wrong colour and language used for confirmation dialogue text

### ISSUE THREAD

**Issue by AmyYLee** [mozilla-mobile/fenix#2941]
* [ ] Please rename "ok" to "clear"
* [ ] Dialogue text colours are incorrect

Light Theme
Please use Violet 70 (#592ACB)

Dark Theme
Please use Violet 40 (#AB71FF)

![Screenshot](https://user-images.githubusercontent.com/5992746/58507903-ceed1c00-8160-11e9-861f-6a8a9dffd2c7.png)UNITO-UNDERSCORE!20190528-140520!

![Screenshot](https://user-images.githubusercontent.com/5992746/58507974-f5ab5280-8160-11e9-9e80-c7e26b02e87c.png)UNITO-UNDERSCORE!20190528-134422!

**Comment by sv-ohorvath** [comment]
Verified as fixed on the 5/30 build.
deivces: Pixel (Android 9), Nexus 5 (Android 6), Mi Pad 2 (Android 5.1)

**Comment by sv-ohorvath** [comment]
The download confirmation dialog needs to be updated too: the Download button is purple.
![Screenshot_20190530-103405](https://user-images.githubusercontent.com/4037709/58640191-3a6def80-8301-11e9-904f-1820433d9c30.png)

**Comment by sv-ohorvath** [comment]
Clear site permissions dialog as well: 
![Screenshot_20190530-104709](https://user-images.githubusercontent.com/4037709/58641181-5d999e80-8303-11e9-8e30-c4b4ce0c40af.png)

**Comment by sv-ohorvath** [comment]
another dialog: Send tab - not devices connected:
![Screenshot_20190531-052108](https://user-images.githubusercontent.com/4037709/58695881-1c56cc80-839f-11e9-8954-d6af75754933.png)
