### ISSUE TITLE
FNX3-16699 ⁃ [Bug] Error when adding a tab to existing group from collections menu

### ISSUE THREAD

**Issue by AmyYLee** [mozilla-mobile/fenix#2948]
1. Create a collection
1. Tap on the options menu in the collections card
1. Select "Add tab"

Expected: Prompts add tab modal 
Result: Toast notification that says feature not implemented (see screenshot below)

![Screenshot](https://user-images.githubusercontent.com/5992746/58512971-64da7400-816c-11e9-8599-10a4676cc2d4.png)UNITO-UNDERSCORE!20190528-161632!

@sblatz

**Comment by sv-ohorvath** [comment]
Verified as fixed on the 5/30 build.
