### ISSUE TITLE
FNX3-16700 ⁃ [Bug] Deleting history/collections progress never completes

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/fenix#2951]
## Steps to reproduce
1. Open settings and try to delete browsing history or collections.

## Expected
* The progress bar on the top disappears after history data is removed

## Actual
* The progress bar never goes away but the data is actually removed.

![](https://user-images.githubusercontent.com/1370580/58515222-2a73d580-8172-11e9-8a6b-4f60a08a4591.png)

**Comment by jonalmeida** [comment]
To be clear, this looks to be a UI issue only with history and collections **not gv browsing data**.

**Comment by ekager** [comment]
This was a dupe closing

**Comment by jonalmeida** [comment]
@ekager what was this a dup of? I just filed https://github.com/mozilla-mobile/fenix/issues/3030 because now it's crashing.

**Comment by ekager** [comment]
Oops sorry thought this was addressed by one of @boek 's PRs today. Reopening

**Comment by boek** [comment]
Bug was filed in the user story @jonalmeida https://github.com/mozilla-mobile/fenix/issues/225

**Comment by sv-ohorvath** [comment]
Verified on 6/5 build.
