### ISSUE TITLE
[Bug] Flickering when selecting a tab to add to a tab collection

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#2958]
![disappearing on selection 2019-05-28 16](https://user-images.githubusercontent.com/4400286/58517951-2dff6080-8162-11e9-841e-fd617f6e803a.gif)UNITO-UNDERSCORE!03!UNITO-UNDERSCORE!30!

**Comment by sv-ohorvath** [comment]
dupe: #2577
