### ISSUE TITLE
FNX3-16703 ⁃ [Bug] Bookmark deletions are janky

### ISSUE THREAD

**Issue by grigoryk** [mozilla-mobile/fenix#2960]
Specifically, what I'm observing is:

* when deleting a bookmark, previously deleted bookmarks re-appear while the "undo toast" is visible. then they disappear again.

Looking at the code, it's not obvious why that'd happen; so, need to look a bit closer :grinning:

**Comment by AndiAJ** [comment]
Hi, I can still reproduce this issue on the latest Fenix build **(1.0.1926 Build #11771809 from 26/6**) on the following devices:
• Google Pixel 3XL (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Sony Xperia Z5 Premium (Android 7.0)

#### ►Video from the Google Pixel 3XL
![2019_06_27_10_16_34](https://user-images.githubusercontent.com/51314259/60245818-0a951600-98c6-11e9-9f7f-2bf6f4bff46b.gif)

**Comment by AndiAJ** [comment]
Hi, it seems that this is applicable for the **Bookmark folders** as well.
Tested it on the latest Fenix build (1.0.1926 Build #11771809 from 26/6) using the following devices:

• Google Pixel 3XL (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Sony Xperia Z5 Premium (Android 7.0)

►Video from the Google Pixel 3XL 
![2019_06_27_11_24_27](https://user-images.githubusercontent.com/51314259/60250181-cce8bb00-98ce-11e9-9dbb-d33e593eb087.gif)

**Comment by ekager** [comment]
Thanks @AndiAJ !! :)
