### ISSUE TITLE
[Bug] Reader mode blue dot notification doesn't appear all the time

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#2962]
## Steps to reproduce
1. Clear app data.
1. Open a webpage in one tab (e.g. google)
1. In a second tab, open a page that works with reader mode, e.g. huffpost. 
Or, open 2 pages without reader mode, open the 3rd tab and go to huffpost.
    1. Expected behavior
The reader mode icon has a blue dot the first time a page with reading mode available is opened.
    1. Actual behavior
The dot doesn't appear on the reader icon. devices: Galaxy Note 8 (Android 9), P20 lite (Android 8)
The dot doesn't appear at all on Android <7 devices like:
Nexus 5 (Android 6.0.1)
Sony Xperia Z2 (Android 6.0.1)
Mi 4i (Android 5.0.2)
    1. Device information

* Android device: 
* Fenix version: ?

**Comment by ekager** [comment]
Closing because we have removed the QAB and moved these functions into the browser menu
