### ISSUE TITLE
[Bug] Empty tab left after clearing browsing data

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#2963]
## Steps to reproduce
1. Create some tabs. Open one tab.
1. Go to Settings>Delete browsing data> select Open tabs.
1. Exit the settings menu
    1. Expected behavior
The empty homescreen is displayed.
    1. Actual behavior
An empty tab is left, tab counter shows 0.
    1. Device information

* Android device: S8 (Android 9), Nexus 5 (Android 6)
* Fenix version: 5/29

**Comment by AaronMT** [comment]
https://github.com/mozilla-mobile/fenix/issues/2980
