### ISSUE TITLE
[Bug] The ".www" button state is not changed to ".com" even if the email is added on login

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/fenix#2965]
## Steps to reproduce
1. Install and launch Fenix.
1. Go to settings and enter your email in order to login.
1. From the autocomplete tap on your email.
    1. Expected behavior
The email is auto completed and every button is correct displayed.
    1. Actual behavior
After auto completing the email the **`.com`** button doesn't change its state and is still displayed as **`www.`.**
    1. Device information

* Android device: **`Samsung Galaxy Note 9(Android 8.1.0), Google Pixel 3(Android 9).`**
* Fenix version:  **`1.0.1922 (#build 11481811) 29/5`**.
    1. Notes
For more details please see the [video](https://drive.google.com/file/d/1UG8dJ_R9Fi7iN2eTekn9neV0Klix2CYt/view?usp=sharing).

**Comment by ekager** [comment]
Closing because this seems to be keyboard specific
