### ISSUE TITLE
FNX3-16709 ⁃ [Bug] Bookmarks do not open after the program start

### ISSUE THREAD

**Issue by Baum55** [mozilla-mobile/fenix#2966]
## Steps to reproduce
1. Firefox Preview has opened tabs
1. The app is completely closed
1. Reopen the app
1. Open a bookmark directly in the firefox start page
1. The last opened tab reopens

### Expected behavior
The selected bookmark opens

### Actual behavior
The last opened tab reopens

### Device information
* Android device: Huawei P9 lite
* Fenix version: 5/29 @ 6:09 AM

**Comment by ekager** [comment]
Thanks! I think this may be an AC bug so I opened https://github.com/mozilla-mobile/android-components/issues/3166

**Comment by pocmo** [comment]
Assigning: I'll work on the linked AC issue.

**Comment by pocmo** [comment]
Blocked on: https://bugzilla.mozilla.org/show_bug.cgi?id=1557723

**Comment by Baum55** [comment]
Are the issue and bug still valid?

In the current version, the selected bookmark will be opened in a new tab. This also fits the to the behavior when using the search field.

From my perspective, the problem would be solved.

### Device information

* Android device: Huawei P9 lite
* Fenix version: 7/10 @ 6:17 AM
