### ISSUE TITLE
[Bug] Can't sign into Zoom via SSO in custom tab

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#2970]
## Steps to reproduce
* Install Zoom from the Play Store
* Open zoom
* Select "Log in with SSO" (there may be a screen before this)
* Try to log in using mozilla sso
* Arrive at "Open Zoom" screen

### Expected behavior
Zoom app opens automatically, or after pressing the "Open Zoom" button

### Actual behavior
Nothing happens when clicked or waiting. Sign in works correctly on Chrome.

I'm guessing they're using Android intent links - maybe they're not working correctly from custom tabs?

### Device information
* Android device: Pixel 2
* Fenix version: 1.0.1920

**Comment by jonalmeida** [comment]
Dupe of https://github.com/mozilla-mobile/fenix/issues/1570

**Comment by vesta0** [comment]
Will be addressed in #1570

**Comment by dholbert** [comment]
Or rather, per a comment on that issue ( https://github.com/mozilla-mobile/fenix/issues/1570#issuecomment-508614088 ):

It seems this will actually be addressed in #3177.
