### ISSUE TITLE
FNX3-16712 ⁃ [Bug] CustomTab back button doesn't navigate

### ISSUE THREAD

**Issue by agi90** [mozilla-mobile/fenix#2972]
## Steps to reproduce
* :star: Open Link in Fenix CustomTab
* Navigate from the custom tab to another page clicking on a link
* Press back button

### Expected behavior
* Page in :star: loads

### Actual behavior
* Custom tab closes and the app is brought back to the foreground

### Device information
* Android device: Samsung S10e
* Fenix version: 5/29/19 from Playstore

Works in: Fennec Nightly, Chrome Stable

**Comment by ekager** [comment]
@agi90 the system back button, correct?

**Comment by agi90** [comment]
Yep!

**Comment by jonalmeida** [comment]
Oops, this was my error when add the back pressed listener - thanks @ekager for fixing it!

**Comment by softvision-miralobontiu** [comment]
Verified that with the device's back button, the user can navigate back in custom tabs.
Tested with the latest build 1.0.1922 (#11500615), with Nokia 6 (Android 7.1.1), Xiaomi MiPad2 (Android 5.1), Google Pixel (Android 9), and Nexus 6P (Android 8.1.0).
