### ISSUE TITLE
[Bug] Deleting Browsing Data never completes

### ISSUE THREAD

**Issue by mozillamarcia** [mozilla-mobile/fenix#2974]
## Steps to reproduce
* Settings | Delete Browsing data
* Select Browsing history and site data. Click Allow

### Expected behavior
* Browsing history and site data is deleted

### Actual behavior
* The delete process never finishes and the progress bar continues moving

### Device information
* Android device: Pixel running Android Q
* Fenix version: 1.01922 (Build #11490610)
[logcatdehistory.txt](https://github.com/mozilla-mobile/fenix/files/3233605/logcatdehistory.txt)

**Comment by AaronMT** [comment]
https://github.com/mozilla-mobile/fenix/issues/2951
