### ISSUE TITLE
FNX3-16714 ⁃ [Collections] Update collections flow to have "Add new collection" clearer

### ISSUE THREAD

**Issue by AmyYLee** [mozilla-mobile/fenix#2977]
Right now the "Add new collection" action bar is easily missed due to how low to the bottom of the screen it sits. I've updated the spec to make it more viable as well as updating the collections list so it mimic's the design of the card on homescreen.

Added a new flow to indicate that if the user has no preexisting collection that we skip straight to create a collection keyboard screen.

Portion of spec to reference:
![Screen Shot 2019-05-29 at 1 05 46 PM](https://user-images.githubusercontent.com/5992746/58580429-16d07980-821b-11e9-929a-eafdbc0b7ed6.png)

Updated spec: https://mozilla.invisionapp.com/d/main#/console/16853870/359019534/preview

**Comment by sv-ohorvath** [comment]
Verified on the 6/3 build. Devices: Galaxy S8 (Android 9), Nexus 5(Android 6), Galaxy tab 3 (Android 8).
