### ISSUE TITLE
FNX3-16716 ⁃ [Bug] Crash occurs when quickly double tapping "Save to Collections" button.

### ISSUE THREAD

**Issue by vrudesai** [mozilla-mobile/fenix#2979]
## Steps to reproduce
1. Open Fenix
1. Quickly double tap on "Save To Collections"
1. Crash occurs

### Expected behavior
1. Select Tabs page opens

### Actual behavior
Fenix crashes.
![Save To Collections Crash](https://user-images.githubusercontent.com/50627998/58583895-015f4d80-8223-11e9-9834-8b878613c0cc.gif)

### Device information
* Android device: ONEPLUS A6003 [Android Version 9]
* Fenix version: 1.0.1922

**Comment by IdmFoundInHim** [comment]
This has been fixed for me in the latest build.
[Note5 Verizon, Android 7.0]

**Comment by softvision-miralobontiu** [comment]
Verified as fixed on the latest build 1.0.1922 (#11510609), with Motorola Moto G6 (Android 8.0), and Sony Xperia Z5 Premium (Android 7.1.1).
