### ISSUE TITLE
FNX3-16717 ⁃ [Bug] After Clearing Data, backing out Settings places user on blank tab

### ISSUE THREAD

**Issue by AaronMT** [mozilla-mobile/fenix#2980]
Build: 9022258b3ffd63c0a66703f038d7ae95a123e80e
Device: Pixel 2

* Open mozilla.org
* Clear tabs and browsing data
* Back out of settings

![Screen Shot 2019-05-29 at 3 43 40 PM](https://user-images.githubusercontent.com/102331/58586206-8c8f1200-8228-11e9-883f-83a1092ad88a.png)

Should probably open a new home tab automatically and focus it.

**Comment by softvision-miralobontiu** [comment]
I've got a crash, filed #3035

**Comment by softvision-miralobontiu** [comment]
Backing out after deleting browsing data, places the user now to homescreen.
Verified as fixed on the latest build 1.0.1922 (#11530616), with Google Pixel (Android 9), Motorola Moto G6 (Android 8), Nokia 6 (Android 7.1.1).
