### ISSUE TITLE
[Bug] Private Tab URLs leaked to Logcat

### ISSUE THREAD

**Issue by AaronMT** [mozilla-mobile/fenix#2982]
Build: 9022258b3ffd63c0a66703f038d7ae95a123e80e
Device: Pixel 2

* Visit a site in a private tab
* See logcat

```java 
2019-05-29 15:48:42.460 13304-14047/org.mozilla.fenix.debug D/BrowserIcons: Loaded icon (source = DOWNLOAD): https://www.cnn.com/

**Comment by jonalmeida** [comment]
This should only happen for debug builds, do you see it happening for release? That said, this issue should still be prioritized.

**Comment by AaronMT** [comment]
Not sure how to build a release, but I see it's a `logger.debug` https://github.com/mozilla-mobile/android-components/blob/master/components/browser/icons/src/main/java/mozilla/components/browser/icons/BrowserIcons.kt#L90 so it should be stripped.

**Comment by bifleming** [comment]
by design.
