### ISSUE TITLE
It's  possible to land on tabs when selecting a collection while using a screen reader [Bug]

### ISSUE THREAD

**Issue by DiegoARL38** [mozilla-mobile/fenix#2988]
## Steps to reproduce
1. Open Fenix with a screen reader on.
1. Open a few tabs.
1. Add them to a collection.
1. Explore via touch the collection-selecting screen.
    1. Expected behavior
It's not possible to land on a tab.
    1. Actual behavior
It's possible to land on a tab.
    1. Device information

* Android device: TP-Link Neffos C5 Max (Android 5.1)
* Fenix version: Build #11491818
    1. Notes
* Tested with both TalkBack and ShinePlus.

**Comment by ekager** [comment]
This will be fixed by #2977 new flow
