### ISSUE TITLE
FNX3-16722 ⁃ [Bug] Crash with malformed IDN domain name

### ISSUE THREAD

**Issue by pauljt** [mozilla-mobile/fenix#2994]
I filed this on bugzilla but its not really a security bug https://bugzilla.mozilla.org/show_bug.cgi?id=1555549, so Im closing that an opening this.

## Steps to reproduce
```
Open https://xn--vsb.com/
Click the link in the top left: (http://xn--jv8h.xn--vsb.com/)
```

### Expected behavior
Website loads (that link is :closed_lock_with_key:.ߔ.com )

### Actual behavior
Crashes after clicking link. I can see the problem in logcat - see the end of the attachment:

05-30 10:39:35.219 16625 16625 E AndroidRuntime: Caused by: mozilla.appservices.places.UrlParseFailed: Error parsing URL: invalid international domain name

### Device information
* Android device: Pixel 3, Android 9
* Fenix version: 1.0.1921

**Comment by AaronMT** [comment]
(CC @thomcc)

**Comment by thomcc** [comment]
Is this actually a well-formed domain name? (I'm guessing so?)

**Comment by colintheshots** [comment]
It seems to be producing a error while trying and failing to write the URL to history in PlacesHistoryStorage and to test the URL against bookmarks_get_all_with_url. I don't see it actually crashing though.

**Comment by thomcc** [comment]
This is actually an invalid URL (according to the URL spec https://url.spec.whatwg.org/) that firefox happens to accept as an extension, it would be nice to fix this, but I have to imagine it's pretty rare to come across outside of rare cases.

**Comment by reinhart1010** [comment]
I think this might be related to webcompat/web-bugs#32496, where TLDs with hyphens ("-") trigger HTTPS cert errors. The issue was forwarded to https://bugzilla.mozilla.org/show_bug.cgi?id=1557295

**Comment by thomcc** [comment]
Those look like they'd be separate issues to me, but I've been wrong before.

**Comment by ekager** [comment]
Are you still seeing this crashing? I'm not able to reproduce in master

**Comment by softvision-miralobontiu** [comment]
Verified that accessing 🔐.ߔ.com doesn't crash the app. It only opens an "Address not found" error page. Tested on the latest Nightly build 190806 (#12180610) with LG G7 Fit (Android 8.1).
