### ISSUE TITLE
[Bug] Onboarding page disappearing after going to Settings

### ISSUE THREAD

**Issue by airamify** [mozilla-mobile/fenix#2995]
## Steps to reproduce
1. Open app
1. From the onboarding page, tap the three-dots icon
1. Tap Settings
1. Tap Theme
1. Change Theme
1. Tap Back arrow until you are back to the main screen.

### Expected behavior
Onboarding screen will still be present since user has not yet tapped "Start Browsing".

### Actual behavior
Contents for the onboarding screen was not displayed. The "Open Tabs" and "Collections" sections were displayed.

### Device information
* Android device:  Huawei Nova 2 Lite
* Fenix version: 1.0.1922

**Comment by vesta0** [comment]
This is intended but I think we may want to revisit this @shorlander

**Comment by sblatz** [comment]
This is blocked on a UX decision as this is currently intended.

**Comment by mheubusch** [comment]
@apbitner wondering if we can reopen the conversation about how to allow users to access onboarding after first run.

**Comment by apbitner** [comment]
Our viewpoint has been that it's okay for onboarding to disappear when the user navigates away for a couple of reasons:

1) All of the features and functionality in the onboarding cards can easily be found in Settings.
2) Most all onboarding experiences in other apps can not be revisited after they've been completed.

When the user navigates away from the onboarding screen, it's the equivalent of them tapping 'Skip' in your normal onboarding experience.

**Comment by vesta0** [comment]
@airamify see comment above regarding this design.
