### ISSUE TITLE
[Bug] Sent tab opened in Fennec instead of Fenix

### ISSUE THREAD

**Issue by rfk** [mozilla-mobile/fenix#2996]
## Steps to reproduce
* Have Fennec installed as default browser on mobile, with the "tab queue" feature enabled
* Install Fenix as additional browser on the same device
* Sign in to Firefox Desktop
* Sign in to Fenix with the same account
* In desktop, visit a website and use 'send tab' to send it to Fenix
* In Fenix, go into settings and "sync now" to receive the tab

### Expected behavior
* The tab is received and opens as a new tab in Fenix

### Actual behavior
* The tab is received, but sent to the Fennec tab queue.
* I get the little pop-over from Fennec saying "tab opened in Firefox"

### Device information
* Android device: Samsung Galaxy S8
* Fenix version: 1.0.1922 (Build #11490610 :gecko-symbol: 68.0-20190520141152)

**Comment by grigoryk** [comment]
You should see the exact same behaviour in reverse, as well - with Fenix installed as a default browser, a tab sent to Fennec will open in Fenix.

When we're creating a "received tab" pending intent for the notification, we're essentially just saying - open this URL in the app that's most suitable. A default browser is quite suitable. Aso, if you send a google maps tab, we'll likely just open it google maps and not in one of our browsers.

So I'd say this functions as designed.
