### ISSUE TITLE
[Bug] App crashes on launch on a HTC Nexus 9

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#2999]
## Steps to reproduce
1. Install a build starting from 5/24 (either from Playstore or taskcluster)
1. Launch the app.
    1. Expected behavior
App opens.
    1. Actual behavior
App launched but unresponsive.
[nexus 9 logcat.txt](https://github.com/mozilla-mobile/fenix/files/3236170/nexus.9.logcat.txt)

### Device information
* Android device: HTC Nexus 9 (Android 7.1.1)
not reproducing on Nokia 6 (Android 7.1.1), Google Pixel (Android 9), Nexus 5 (Android 6.0.1), Mi Pad 2 (Android 5.1, x86) 
* Fenix version: 5/24 - 5/30

**Comment by colintheshots** [comment]
This looks like #2808. One of the two is a duplicate.

**Comment by sv-ohorvath** [comment]
> This looks like #2808. One of the two is a duplicate. I'll mark this one.

Probably they are, but just a note that on the Nexus tablet, the app doesn't function at all, it just launches a blank screen.
