### ISSUE TITLE
FNX3-16728 ⁃ [Not a bug] Replace deprecated `SearchEngineManager.load()` with `loadAsync()`.

### ISSUE THREAD

**Issue by dector** [mozilla-mobile/fenix#3000]
`SearchEngineManager.load()` is [deprecated now](https://github.com/mozilla-mobile/android-components/blob/77d384c/components/browser/search/src/main/java/mozilla/components/browser/search/SearchEngineManager.kt#L58). `SearchEngineManager.loadAsync()` should be used instead.

Occurrences:

* [Search](https://github.com/mozilla-mobile/fenix/blob/96b68948b5a868baecb2df2cf40b479a7c1c2860/app/src/main/java/org/mozilla/fenix/components/Search.kt#L27).

**Comment by a79014** [comment]
I would like to work on this issue
