### ISSUE TITLE
FNX3-16730 ⁃ [Bug] Keyword Search causes crash

### ISSUE THREAD

**Issue by pwd-github** [mozilla-mobile/fenix#3002]
## Steps to reproduce
1. Create some keyword searches on desktop
1. Sync your bookmarks
1. Attempt quick/keyword search in Fenix 

### Expected behavior
You get your search results

### Actual behavior
Crash! :boom: 

### Device information
* Android device: Android 8, LG G6
* Fenix version: 1.0.1922

**Comment by AaronMT** [comment]
Logcat?

**Comment by pwd-github** [comment]
I don't have one. I did press send when it crashed at both OS and app level though. Also I can consistently reproduce the crash with the following STR: 

1. Open Fenix
2. Open an existing tab
3. Press the 3 dot menu
4. Press new tab
5. Type "dict <any word>"*
6. Press enter

* dict is IIRC, tfd.com/$s. I can't recall, I set my quick searches years ago and they've followed me around with sync.

**Comment by vesta0** [comment]
Let's look at a solution to prevent the crash without introducing anything new.

**Comment by kbrosnan** [comment]
Adding the feature is #2497

**Comment by sblatz** [comment]
Of note, some older users will likely have these by default: http://kb.mozillazine.org/Using_keyword_searches

**Comment by sblatz** [comment]
I'm not able to reproduce this on the latest master. I have tried using the shortcuts listed in that wiki article as well as some of my own (that don't have parameters). @pwd-github can you still reproduce?

**Comment by pwd-github** [comment]
This appears to be fixed now @sblatz

**Comment by abodea** [comment]
I can confirm that I cannot reproduce this issue anymore on the latest build 6/27 using Google Pixel XL(Android Q Beta 4).
