### ISSUE TITLE
[Bug] Fullscreen mode is not full screen, leaves space for address bar

### ISSUE THREAD

**Issue by colintheshots** [mozilla-mobile/fenix#3006]
## Steps to reproduce
1. Visit a video on Youtube.
1. Press the fullscreen button on Youtube.

### Expected behavior
The video takes up the entire screen.

### Actual behavior
The video is smaller than the screen, leaving wasted space for the address bar, so it appears letterboxed at the top of the screen.

### Device information
* Android device: Pixel 3XL running Android Q
* Fenix version: 1.0.1922 (Build #11491818)

**Comment by vesta0** [comment]
Dup of #2794
