### ISSUE TITLE
Integrate push component

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/fenix#3015]
A tracking issue for integrating the push component that depends on #2356 for send tab.

**Comment by grigoryk** [comment]
This is marked as an `MVP Blocker` because it ensures proper functionality of the "receive" part of send tabs, and should be cheap to do - we already landed all of the required push functionality in `a-c`, so ideally we're looking at a very quick turn-around.

**Comment by jonalmeida** [comment]
Closing since this work is done and there isn't testable work for it yet.
