### ISSUE TITLE
Consider specifying device make/model as part of the default FxA device name

### ISSUE THREAD

**Issue by grigoryk** [mozilla-mobile/fenix#3018]
Currently we're using product name as the default FxA device name - so, "Firefox Preview".

Fennec appends a device name, e.g. "Firefox for Android on Galaxy S6". Consider doing the same here.

This is a follow-up to #2618.

**Comment by sebast889** [comment]
Is it really necessary to include device name? Can Firefox just get by with "Firefox for Android"?

**Comment by vesta0** [comment]
Dup of #3886
