### ISSUE TITLE
Open default Phone or Text app

### ISSUE THREAD

**Issue by AmyYLee** [mozilla-mobile/fenix#3022]
### User Story
As a user, I want my browser to launch Phone/Text app with the phone number populated when I tap on a phone number or press on "call/text" button, so I can easily make a phone call or send a text.

### Acceptance Criteria
-I can launch the phone app and make a call, when I tap on a phone number or press on "call" on a site.
-I can launch the text app and easily send a text, when I tap on a send a text intent on a site.

**Comment by vesta0** [comment]
I believe this is blocked on #1570

**Comment by jhugman** [comment]
This corresponds to [ac#3725][0].

[0]: https://github.com/mozilla-mobile/android-components/issues/3725
