### ISSUE TITLE
[Bug] After restarting from  crash that happened while typing on the address bar, Fenix is opened with they keyboard covering part of the screen

### ISSUE THREAD

**Issue by Lululalu** [mozilla-mobile/fenix#3033]
## Steps to reproduce
Make Firefox crash while typing on the address bar (it's happening to me sometimes, but I don't know what is causing it yet)

### Expected behavior
After the crash Firefox restarts without any unusable keyboard on the screen. 

### Actual behavior
![Screenshot](https://user-images.githubusercontent.com/32398857/58683893-9873f480-834c-11e9-8311-91975c31b70b.jpg)UNITO-UNDERSCORE!20190531-022411!UNITO-UNDERSCORE!Firefox Preview!

### Device information
* Android device: 1.0.1922
* Fenix version: Galaxy A5 2017 8.0

**Comment by kbrosnan** [comment]
Closing we have not seen any other reports of this and it is over a year old.
