### ISSUE TITLE
[Meta] What is the roadmap for Fenix feature parity with Fennec?

### ISSUE THREAD

**Issue by madb1lly** [mozilla-mobile/fenix#3034]
Existing request/discussion: https://groups.google.com/d/msg/fenix-nightly/99h3O3nuHJU/XacymGcAAwAJ

### Why/User Benefit/User Problem
Lots of people are using Fenix and would like to see various features added that already exist and they use in Fennec (the current Firefox for Android) - for evidence look at the discussion in the mailing list. I am aware of the GitHub projects which are the product team's technical roadmap but what about a "simple English" roadmap for the target audience which explains when existing Fennec features will be added to Fenix? I am making the assumption that this is a goal of the project, but maybe it is not? In which case it would be useful to know which Fennec features are not intended to be added to Fenix. Or maybe some features will be changed when implemented in Fenix? 

### Acceptance Criteria (Added by PM. For EPM to track when a Meta feature is done)
List of Fennec features and when they are planned to be added to Fenix (or if they will not be, state this explicitly). E.g. you can look at the list in my original post in the mailing list: https://groups.google.com/d/msg/fenix-nightly/99h3O3nuHJU/XacymGcAAwAJ

### What / Requirements (Added by PM and Eng Manager)
To be completed by the Mozilla product team for Fenix.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-11844)

**Comment by vesta0** [comment]
@madb1lly thanks for filing this request. Will be sure to post the roadmap here once it's been reviewed internally. In the meantime, please know that we reviewed all of your feedback (and responses to your feedback) and taking them into consideration. Keep them coming!

**Comment by madb1lly** [comment]
Hi @vesta0 !
Thanks for getting back to me, much appreciated. I also like the new label "Fennex Parity", that will help a lot! Do we need to every missing Fennec feature as an issue and add that label? I feel that should be unnecessary if the roadmap addresses the feature parity question... this is basically why I asked for a roadmap, so we wouldn't have to raise an issue for everything!
Cheers :)

**Comment by madb1lly** [comment]
Hi @vesta0, it's been a while, what's the ETA on this? The issues and projects here on Github are still difficult to navigate and see the big picture for feature parity (or not) with Fennec so I think a simple roadmap would still be useful.
Cheers :)

**Comment by vesta0** [comment]
Hi @madb1lly we have a WIP list going here: https://github.com/orgs/mozilla-mobile/projects/45

**Comment by madb1lly** [comment]
Hi @vesta0,
Thanks for the link. I have seen that project before, it is helpful. However it's still not a simple cross-check against Fennec to confirm which features will be implemented in Fenix and which won't. I have trawled through many issues on GitHub now and it seems that the Fenix team have not approached the overall project with feature-parity with Fennec in mind, as there are many issues raised for missing features which are not raised by the Fenix team but by the community. Have I understood correctly?
Cheers :)

**Comment by kbrosnan** [comment]
Closing out this. Fenix does not have parity with every Fennec feature. Individual bugs that have already been filed are in the process of being moved over to Bugzilla. This meta is not something that we want to move over.
