### ISSUE TITLE
FNX3-16752 ⁃ [Bug] Device name dialog looks funky when text selected

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/fenix#3047]
## Steps to reproduce
1. Sign in to sync
1. Click on Device Name dialog
1. Double-tap any test in the dialog

Probably need to use the support version of the UI component.

![](https://user-images.githubusercontent.com/1370580/58724937-dd7b4380-83ab-11e9-9b38-f1b35f1ba073.png)

* Android device: Pixel 2 (Android 9)

**Comment by softvision-miralobontiu** [comment]
Verified as fixed on the latest build 1.0.1923 (#11580610), with Samsung Galaxy S8 (Android 9), Motorola Moto G6 (Android 8), and Huawei P9 Lite (Android 6).
