### ISSUE TITLE
FNX3-16753 ⁃ [Settings] Update Sign in accounts icon

### ISSUE THREAD

**Issue by AmyYLee** [mozilla-mobile/fenix#3049]
Please update the sign in icon so it looks like below

![](https://user-images.githubusercontent.com/5992746/58726445-baeb2980-83af-11e9-8837-769eac6514d3.png)

SVG icon
[fx-accounts_avatar.svg.zip](https://github.com/mozilla-mobile/fenix/files/3242429/fx-accounts_avatar.svg.zip)

**Comment by boek** [comment]
this is done

**Comment by sv-ohorvath** [comment]
Verified as fixed on version 1.0.0 rc2.
