### ISSUE TITLE
FNX3-16756 ⁃ [Bug] Close all tabs undo snackbar bug

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#3056]
### STR
1. Close all tabs
1. While snackbar displays, open search fragment and navigate to a new page

### Actual
1. Page loads and the current tab is closed

### Expected
1. Page loads
![close tabs 2019-05-31 11](https://user-images.githubusercontent.com/4400286/58727478-545b1100-8399-11e9-8ba4-0e7c3f7eeafa.gif)UNITO-UNDERSCORE!43!UNITO-UNDERSCORE!30!

**Comment by softvision-miralobontiu** [comment]
Verified as fixed on the latest build 1.0.1922 (#11530616), with Nokia 6 (Android 7.1.1), and Google Pixel (Android 9).
