### ISSUE TITLE
FNX3-16758 ⁃ Create a Fenix Leanplum Attribute that tells us when a user signs into an FxA

### ISSUE THREAD

**Issue by ItsDevyani** [mozilla-mobile/fenix#3059]
## User Story - Marketing is the user.
* As a Marketer, I would like to know whether or not a user is signed into an FxA, so that I can do the following: send them an in-app message or push notification prompting them to sign into or create an FxA, or sign into Sync, or sign up with an account for Trailhead services like Send, Monitor etc. This will help me meet our organizational MAU and retention goals with Fenix.

## Dependencies
* Data pass through from the application services team? (Identify other dependencies with help from Vesta and Stefan.)

### Acceptance Criteria
* I (The marketer) can segment the users by whether or not they are signed into an account in Leanplum 
* I (The marketer)  can target the users with relevant messages delivered via Leanplum based on their sign in status
* I (The marketer) can measure the number of users who signed in to an account after seeing my campaign

**Comment by vesta0** [comment]
@boek FYI

**Comment by liuche** [comment]
One concern is that Fenix can't tell if a sign-in is a login or a creation (it's the same FxA flow). We need a hook from A-S to differentiate between whether it's a sign-in or registering. @vesta0 will file a bug for that.

**Comment by jonalmeida** [comment]
Engineering note:
 - Firebase messaging has already been added to Fenix.
   - Do **NOT** apply the `com.google.gms.google-services` plugin.
 - Leanplum should only need the dependency `leanplum-fcm`.

Misc notes:
 - Have we already provided the server keys from Firebase to Leanplum?

**Comment by liuche** [comment]
I don't think this needs the AC, AS labels for this specific bug.

**Comment by sblatz** [comment]
This will be covered by https://github.com/mozilla-mobile/fenix/pull/4626
