### ISSUE TITLE
[Bug] Full screen landscape has cut off engine view

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#3061]
This is happening because of the [newly updated fixed toolbar](https://github.com/mozilla-mobile/fenix/pull/2742). We need to detect if the user is in fullscreen mode and update the margins on the 1engineView`

![](https://user-images.githubusercontent.com/4400286/58733763-4497f880-83aa-11e9-93cd-e2ec4701cec1.png)

**Comment by Lululalu** [comment]
Similar to #2794

**Comment by jonalmeida** [comment]
@sblatz See my comment in the linked issue above if you're working on this. Will look into it next week otherwise. :)

**Comment by colintheshots** [comment]
This is fixed.
