### ISSUE TITLE
Add cast button to videos

### ISSUE THREAD

**Issue by leobel96** [mozilla-mobile/fenix#3068]
### Why/User Benefit/User Problem
As in Chrome or Brave browsers, a user can instantly cast a video to his Google Cast compatible device (i.e. Chromecast) simply tapping on the cast button.

### What/Requirements
Add Google Cast SDK support.

### Acceptance Criteria (how do I know when I’m done?)
A Cast button appears on any video.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-11860)

**Comment by orangesunny** [comment]
Hi, is it a problem to get inspired in, e.g. Kiwi? https://github.com/kiwibrowser/android
It works there, flawlessly. Is it in a part of the code that is not open source? Is there a problem in license?

**Comment by logos88** [comment]
I would not limit the option to cast to Chromecast, but to **DLNA** or **Dial** too, since this are open standards and are integrated in a lot of TVs by default.

Maybe **Fenix could make use of PipeCast library**, which is still at work. As it says in his page "PipeCast is a library for 'casting' a stream to a device, like a Chromecast. It's going to be used by NewPipe".

[https://github.com/TeamNewPipe/PipeCast](https://github.com/TeamNewPipe/PipeCast)

**Comment by liuche** [comment]
Looks like Kiwi browser does this but it uses WebView. May be a lot of work to handle on the GV side.

**Comment by Mugurell** [comment]
> Looks like Kiwi browser does this but it uses WebView. May be a lot of work to handle on the GV side.

Casting was working (with some hiccups) on Fennec.
So I'd think we just need the application code to wire up what already exists in GV.

Not sure whom to ask about the status of this on GV but maybe @liuche knows.

**Comment by jonalmeida** [comment]
>  So I'd think we just need the application code to wire up what already exists in GV.

The backing Presentation API in Gecko was removed since it wasn't supported very well and both, desktop and Fennec/GV, had it eventually disabled. See for details: https://bugzilla.mozilla.org/show_bug.cgi?id=1697680

**Comment by aaronwi** [comment]
3 years later, solution was to switch to Brave browser.

**Comment by ivoros** [comment]
It's baffling that in 2023 a major browser _still_ doesn't support casting.

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813920

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
