### ISSUE TITLE
[Bug] Tapping on embedded YouTube video title opens the video in Fenix rather than the YouTube app

### ISSUE THREAD

**Issue by pwd-github** [mozilla-mobile/fenix#3069]
## Steps to reproduce
1. Find a page with an embedded YouTube video (like a forum) 
1. Press the title

### Expected behavior
The YouTube app opens

### Actual behavior
You're taken to the webpage of the YouTube video and only when you press refresh, will the YouTube app open. 

### Device information
* Android device: Android 8, LG G8
* Fenix version: 1.0.1922

**Comment by stagedataloss1** [comment]
test123

**Comment by ekager** [comment]
We are still working on supporting external intents
