### ISSUE TITLE
Provide the user a way to launch apps associated with a website

### ISSUE THREAD

**Issue by pwd-github** [mozilla-mobile/fenix#3070]
### Why/User Benefit/User Problem
A user may want to switch to the native app associated with a website.

### What/Requirements
When a user has an app installed and visits a website that is associated with the app the user can press a button or choose a menu item that transfers the user to the app.

### Acceptance Criteria (how do I know when I’m done?)
Users can choose open apps associated with the website. 

Testing with the Wikipedia app is a good first start. Common Google apps such as YouTube or Maps should also be able to be switched to.

**Comment by kbrosnan** [comment]
Going to touch this up so it conforms to a feature request. Paul let me know if I missed something important.

**Comment by pwd-github** [comment]
Will do. The only concern is placement, whether to place it in the quick action bar or to mimic what Fennec did. I think the quick action bar makes more sense, but that's just my opinion.

**Comment by jhugman** [comment]
This is being tracked on the [Android Intent URLs board][0].

[0]: https://github.com/orgs/mozilla-mobile/projects/32
