### ISSUE TITLE
[noob question] How to set "versionName" property?

### ISSUE THREAD

**Issue by MasterGroosha** [mozilla-mobile/fenix#3071]
I'm really desperate now. Trying to build armBeta variant with **Android Studio** and I always get the same error:

> * What went wrong:
> Execution failed for task ':app:preArmBetaBuild'.
> Release builds require the 'versionName' property, e.g.: './gradlew -PversionName=<...> assembleNightly'

Things I've tried so far:

1. Setting versionName in Config.kt

```java
object Config {
    // Synchronized build configuration for all modules
    const val compileSdkVersion = 28
    const val minSdkVersion = 21
    const val targetSdkVersion = 28
    const val versionCode = 2             // added
    const val versionName = "2"           // added
```

1. Settings versionName in :app:Build.Gradle

```
android {
    compileSdkVersion 28
    defaultConfig {
        applicationId "org.mozilla.fenix"
        minSdkVersion Config.minSdkVersion
        targetSdkVersion Config.targetSdkVersion
        versionCode 1
        // versionName Config.generateDebugVersionName()
        versionName "beta"

    }
```

3.Setting versionName in productFlavors:

```
    productFlavors {
        arm {
            dimension "abi"
            ndk {
                abiFilter "armeabi-v7a"
            }
            versionName "beta"
        }
```

1. Praying to Cthulhu
1. adding versionName property in preBuild task:

```java
            prebuildTask.doFirst {
                project.setProperty("versionName", "beta") // added
                if (!project.hasProperty('versionName')) {
                    throw new RuntimeException("Release builds require the 'versionName' property, e.g.: './gradlew -PversionName=<...> assembleNightly'")
                }
            }
```

Obviously no approach worked for me, that's why I'm asking you, professionals, to explain, how the hell should I set this `versionName` property in Fenix code to finally build armBeta version?

**Comment by pwd-github** [comment]
I just had a quick read through a search of the repo, but it seems that it should be the Gecko version. Are you importing Android Components correctly? 

Also, just for the record, there is no beta snapshot as of yet.

**Comment by MasterGroosha** [comment]
I cloned git repo and opened it with the latest Android Studio. Any extra steps to perform?

**Comment by pwd-github** [comment]
Out of curiosity, why do you want to build it yourself as opposed to grab one of the readily available pre-built packages available?

**Comment by MasterGroosha** [comment]
@pwd-github the latest package on github releases is almost month old and 300+ commits behind head.
I don't see any other options to get the latest (or at least, "fresh") build of Fenix. I don't see Fenix on Play Store as well (maybe I'm blind?)

**Comment by pwd-github** [comment]
Builds are done at least once a day and released through the Play Store via a closed beta. Details on how to join that were widely disseminated. A quick search should point you in the right direction. If you're unwilling to join the beta officially, you can grab one of the nightly builds through Task Cluster. Links to the correct build are also available via a quick search.

**Comment by MasterGroosha** [comment]
I've found a taskcluster page, thank you!
Anyway, do you mean that beta version cannot be built from source as of now?

**Comment by pwd-github** [comment]
Off of Taskcluster, you want the v2.

And I just mean that beta isn't ready (finished) yet. Work is still very much ongoing in the bid to get Fenix to the point of being beta ready.

**Comment by ekager** [comment]
If you want to build locally, use any of the Debug variants.

**Comment by mitchhentges** [comment]
Hey @MasterGroosha, I agree that the error message is confusing, sorry! It's purpose is to ensure that release builds by Mozilla have a correctly-set version name. However, I've recently found that the error message (specifically `gradle`, grr) doesn't play well with IDEs.

How are you building Fenix?
* If on the command line, I'd recommend `./gradlew assembleDebug`. This will output a debug build in `app/build/outputs/apk/...`
* If you want a release build, I'd highly recommend grabbing a "nightly" from [this Taskcluster index](https://taskcluster-ui.herokuapp.com/tasks/index/project.mobile.fenix.v2.nightly/latest)
* If you _really_ want to build a Fenix beta locally on the command line, do `./gradlew assembleBeta -PversionName "master-groosha-version-its-the-best"`

**Comment by MasterGroosha** [comment]
@mitchhentges Hello, Mitchell. I just open project in Android studio and use "Build APK" option, nothing special.

**Comment by mitchhentges** [comment]
@MasterGroosha ok, that makes sense.
In Android, there's a concept called "build variants", which affects the kind of build we do, such as "should this be for aarch64 processors, or arm processors?" or "is this a debug build for developers, or a real beta build for end-users?".
When opening the project in Android Studio locally, you definitely want to use a "debug" build variant. _Unfortunately_, until later this year, it's not possible to set "debug" as a default! So, you need to change your build variant to something "debug"-y.

Here's how:
1. Open Android Studio
2. On the left, click "Build Variants"
3. In the window that opens, on the `app` row, change "Build Variant" to something like `armDebug`
4. Build that APK
5. "No big deal," but you did it! Nice work! :clap: :tada:

![Screenshot from 2019-06-06 13-00-23](https://user-images.githubusercontent.com/7784737/59028180-325f0400-885b-11e9-8ac9-6d2dd126219c.png)

**Comment by MasterGroosha** [comment]
@mitchhentges Thank you for your instructions! However, I have no problems building "Debug" version, I just wanted to build "Beta" since (in my thoughts) it should have no telemetry and doesn't spam to logs wasting battery. Luckily as far as I see "Debug" doesn't have telemetry, and it suits me for now.

**Comment by mitchhentges** [comment]
@MasterGroosha Ah, I understand. There currently isn't that big of a difference between the beta and debug version, though if you wish to build it, I'd recommend using the `assembleBeta` command from [above](https://github.com/mozilla-mobile/fenix/issues/3071#issuecomment-499201747)

It's annoying to set in the IDE, because Android Studio/IntelliJ doesn't allow gradle properties in run configurations (that I could find). FWIW, in the future, if you super duper totally wanted to do a Beta build from in-IDE, you'd have to edit `gradle.properties` and add the line `versionName=master-groosha-version-its-the-best`

**Comment by mitchhentges** [comment]
For future reference, instead of having to edit `gradle.properties`, you can add `--versionName=...` to Settings > Build, Execution, Deployment > Gradle-Android Compiler > Command-line Options.

![](https://user-images.githubusercontent.com/10008419/59921398-7e6b9480-9468-11e9-9df2-9f6c8f5c8c64.png)

**Comment by MasterGroosha** [comment]
@mitchhentges That's great! Thank you!
