### ISSUE TITLE
FNX3-16766 ⁃ [Bug] Find in Page Does Not Close When entering Fullscreen

### ISSUE THREAD

**Issue by ekager** [mozilla-mobile/fenix#3072]
## Steps to reproduce
1. Open FIP
1. Click on fullscreen video

### Expected behavior
FIP disappears (closes?) when full screen opened (Not sure the correct behavior here, note to check other browsers)

### Actual behavior
FIP still there in full screen

### Device information
* Android device: ?
* Fenix version: ?

**Comment by bifleming** [comment]
not reproducible
