### ISSUE TITLE
[Bug] 'Open in Firefox Preview' from custom tabs no longer opens it in main app

### ISSUE THREAD

**Issue by neekless** [mozilla-mobile/fenix#3073]
## Steps to reproduce
1. Open any custom tab. For the sake of testing, open Fenix main app, go to Settings>Privacy Notice, which should open in a custom tab.
1. Tap 3-dot button at the upper right corner, tap Open in Firefox Preview.

### Expected behavior
The custom tab opens in the main app.

### Actual behavior
The custom tab does not open in the main app.

### Device information
* Android device: Pixel 2XL, Android 9
* Fenix version: 1.0.1922 Build 11521808

This bug doesn't occur in Build 11511806.

**Comment by ekager** [comment]
This seems to have been caused by https://github.com/mozilla-mobile/fenix/pull/3062 cc @colintheshots

**Comment by neekless** [comment]
Fixed in Build 11541808.
