### ISSUE TITLE
[Bug] History disappears very quickly from library

### ISSUE THREAD

**Issue by buttercookie42** [mozilla-mobile/fenix#3075]
## Steps to reproduce
1. Don't use sync, so you don't have "foreign" history polluting the test setup.
1. Visit a few pages and verify they appear in the history library.
1. Don't use Fenix for a few days (my current build seems to be from the 29th and I did test some pages after updating, so definitively less than a week)
1. Open the history library.

### Expected behavior
My old history shows up.

### Actual behavior
The library is completely empty. The history is not completely gone, as typing in the URL bar gives appropriate results, but it's not showing up in the library.

### Device information
* Android device: Moto G4 Play, Android 6.0.1
* Fenix version: 1.0.1922 (Build #11491817)

**Comment by vesta0** [comment]
@buttercookie42 please re-test and let us know if you can reproduce this.

**Comment by buttercookie42** [comment]
Installing today's build (11621806, 68.0-20190604110028) alone didn't seem to make a difference. Created some fresh history, but have to check in a few days again.

**Comment by buttercookie42** [comment]
Still happens.

**Comment by ekager** [comment]
We fixed some history layout and list issues this sprint. Could you possibly report back if you're still seeing this in the latest builds?

**Comment by buttercookie42** [comment]
The library now shows some results for "This month" (actually they're from last month, but that's a separate issue, I guess), so things seem to have improved I guess.
