### ISSUE TITLE
[Bug] Lizard char in version info screen not properly displayed

### ISSUE THREAD

**Issue by buttercookie42** [mozilla-mobile/fenix#3076]
## Steps to reproduce
Open Settings -> About Firefox Preview

### Expected behavior
Apparently the version string uses what [is supposed to be](https://github.com/mozilla-mobile/fenix/blob/27d8c09def659b44027e977d49003ccefa885a64/app/src/main/java/org/mozilla/fenix/settings/AboutFragment.kt#L33) a lizard emoji (a "Gecko", I suppose?) to separate the Fenix and GeckoView-specific build IDs.

### Actual behavior
On my phone the lizard doesn't render and is replaced with an "unknown character" box instead.

### Device information
* Android device: Moto G4 Play, Android 6.0.1
* Fenix version: 1.0.1922 (Build 11491817)

**Comment by a79014** [comment]
I am seeing a gecko on mine
build #112606675

**Comment by cadeyrn** [comment]
I can't reproduce myself but I remember that I saw a screenshot from another user a few weeks ago where the gecko was missing.

The affected user has a Lenovo Tab 2 with Android 6.

**Comment by buttercookie42** [comment]
It seems the lizard is part of Unicode 9.0, and as far as I can tell, corresponding font were first included in Android N.
So older versions would either require a custom font or more simply, should just use some other separator char instead.

**Comment by a79014** [comment]
So after 2 mintues of google I would assign the geckto to a variable, then check if the version is less or equal than 6, change the var value ""

I have never tried kotlin so in a pseudo-codey way:

```
var maybeGecko = " \uD83E\uDD8E "
if (android.os.Build.VERSION.SDK_INT < android.os.Build.VERSION_CODES.NOUGAT) {
     maybegecko = " "
}
val geckoVersion = PackageInfoCompat.getLongVersionCode(packageInfo).toString() + maybeGecko +
                    GeckoViewBuildConfig.MOZ_APP_VERSION + "-" + GeckoViewBuildConfig.MOZ_APP_BUILDID
```

**Comment by a79014** [comment]
I created a pull request, you can check its status here: 
https://github.com/mozilla-mobile/fenix/pull/3115
