### ISSUE TITLE
FNX3-16771 ⁃ Display a "No devices connected" message when sending a tab

### ISSUE THREAD

**Issue by softvision-miralobontiu** [mozilla-mobile/fenix#3077]
## Steps to reproduce
1. Sign in on a single device. 
1. Share a tab on another device. 

### Expected behavior
Instead of showing the dialog (i.e. the gif below), show the new screen from the invision link, that includes the yellow "No devices connected" message.
https://mozilla.invisionapp.com/share/QSR2F8UD4PN#/screens/364885746

### Actual behavior
A pop-up is displayed.

### Device information
* Android device: Sony Xperia Z5 Premium (Android 7.1.1)
* Fenix version: 1.0.1922 (#11530616)

@jonalmeida 

![2019-05-31](https://user-images.githubusercontent.com/40694158/58781062-7e077880-85e3-11e9-9088-1f8e720dde17.gif)

**Comment by jonalmeida** [comment]
These new designs didn't exist when the feature was first implemented. We need to check if these states have been added already and then we launch the "No Device Connected" screen on the button click instead.

Thanks @softvision-miralobontiu !

**Comment by mheubusch** [comment]
Strings: 
Message: To send a tab, sign in to Firefox on at least one other device. 
Button/Action: GOT IT

**Comment by jonalmeida** [comment]
> Strings:
> Message: To send a tab, sign in to Firefox on at least one other device.
> Button/Action: GOT IT

To clarify for this ticket for engineering, this is the string currently used in the gif above and in the capture below.

cc: @mheubusch 

What we need is to make sure that [these user flows](https://user-images.githubusercontent.com/1370580/61322893-b69e9280-a7dc-11e9-9470-22d1d0435683.png) are still accurate to the [invision link](https://mozilla.invisionapp.com/share/QSR2F8UD4PN#/screens/364885746) posted above.

![58781062-7e077880-85e3-11e9-9088-1f8e720dde17](https://user-images.githubusercontent.com/1370580/61322799-83f49a00-a7dc-11e9-8cde-6b81fa872834.jpg)

**Comment by ryanfeeley** [comment]
This is correct, even though this dialog is currently AWOL from the Invision.

https://mozilla.invisionapp.com/share/QSR2F8UD4PN#/screens/374762782

To paginate through the Invision document, use the right-arrow on your keyboard.

To clarify the steps to reproduce:
> Sign in on a single device.

Should probably be:
> Register a new account to sync Fenix and do not connect a second device.

**Comment by ryanfeeley** [comment]
For reference, I'm trying to see how many users will ever be in a state that shows this. To be in this state that would have to create the account on Fenix and not sign in on another device. It looks like between 5-10% of existing Fenix sync users, so not very many.

**Comment by vesta0** [comment]
What is this ticket waiting on @bifleming ?

**Comment by jonalmeida** [comment]
There isn't any a-c work required here.

**Comment by liuche** [comment]
It looks like these mocks are ready and there are strings.

**Comment by vesta0** [comment]
@liuche @ryanfeeley during backlog grooming on Friday we thought there was overlap between this ticket and  #2897 but reading through it now I think they are different, and I can't see a "No Device Connected" screen on any of the mocks. Could you please clarify the ask?

**Comment by liuche** [comment]
Open questions for UX:

What do the two buttons below "No devices connected" do?  @AmyYLee will follow up on this w/ Ryan Feeley.

@jonalmeida is it possible to "Connect another device" w/ AC? Not clear on what that should do (so we don't have UX for it either).

**Comment by jonalmeida** [comment]
> What do the two buttons below "No devices connected" do? @AmyYLee will follow up on this w/ Ryan Feeley.

This goes to the sign-in page.

> @jonalmeida is it possible to "Connect another device" w/ AC? Not clear on what that should do (so we don't have UX for it either).

That's not really an action. What would it connect?

For a short time @ryanfeeley and I talked about this and we showed this link when you clicked it: https://accounts.firefox.com/connect_another_device

Right now, we show a dialog informing the user to go to another device: https://searchfox.org/mozilla-mobile/source/fenix/app/src/main/res/values/strings.xml#568

**Comment by boek** [comment]
@ryanfeeley Do you know where these buttons should send users?

**Comment by softvision-miralobontiu** [comment]
Verified as fixed on the latest Nightly build 190923 (#12661829) with Motorola Moto G6 (Android 8), Nokia 6 (Android 7.1.1), and Samsung Galaxy Tab A6 (Android 5.1).
