### ISSUE TITLE
[Bug] Full-screen notification reduces the full-screen size

### ISSUE THREAD

**Issue by cpeterso** [mozilla-mobile/fenix#3078]
## Steps to reproduce
1. go to https://kinoseed.com/
1. press [ ] to enter full screen

### Expected behavior
Entered full-screen without making space for a notification.

### Actual behavior
notification that the user is entering full-screen mode decreased the view at the bottom, and it never resized back to full-screen, even after the notification is gone. This is a recent regression.

### Device information
* Android device: ?
* Fenix version: ?

I have not actually tried to reproduce this bug myself. I am just filing this Fenix issue for a bug that was originally reported in Bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1556225

**Comment by jonalmeida** [comment]
PR #3063 fixes this issue.

**Comment by bifleming** [comment]
Dup of 2794
