### ISSUE TITLE
[Bug] tel: links not working

### ISSUE THREAD

**Issue by kaitk** [mozilla-mobile/fenix#3079]
## Steps to reproduce
1. Go to any site with a telephone link. E.g: 
`<a href="tel:+1-303-499-7111">+1 (303) 499-7111</a>`
https://developers.google.com/web/fundamentals/native-hardware/click-to-call/
1. press on the phone number (+1 (303) 499-7111 in this example)
    1. Expected behavior
It opens the phone app with the linked number pre-filled.
    1. Actual behavior
nothing happens
    1. Device information

* Android device: Oneplus 6 (running Android 9)
* Fenix version: 1.0.1922 (Build #11530617 68.0-2019527103257)

**Comment by kaitk** [comment]
Stumbled at it twice during the weekend. This is actually quite irritating, as it's a link, and therefore long-pressing on it also doesn't seem to copy the contents. It seemingly tries to do something (and fails) on click, but the bottom line is that one has to memorize and manually type in phone number, which is far from ideal

**Comment by bogas04** [comment]
Can confirm, couldn't call the delivery executive no matter how much I tap the button.

**Comment by vesta0** [comment]
Thanks for filing! Will be addressed in #3022
