### ISSUE TITLE
[Bug] Constant private switching issue

### ISSUE THREAD

**Issue by obitodarky** [mozilla-mobile/fenix#3082]
## Steps to reproduce
1.Keep switching private mode on and off quickly.
2.Wait after some time.

### Expected behavior
Smooth switching between private and normal mode.

### Actual behavior
Browser is blank and stops responding for a few seconds
![bugg](https://user-images.githubusercontent.com/21317964/58804297-2989ea80-862f-11e9-8c6c-5db9e9bfd76b.gif)

### Device information
* Android device: ASUS Zenfone Max Pro M1, arm-64, Android 9 (API 28)
* Fenix version: 1.0.1922

**Comment by vesta0** [comment]
Let's try to reproduce it with low end devices.

**Comment by softvision-miralobontiu** [comment]
STR:
1. Open Firefox Preview and tap on the Private browsing icon.
2. Tap again on the Private browsing icon to exit private browsing.
3. Repeat steps 1 & 2 as quickly as you can.

Tested with 1.0.1925 (#11720609) build, with Samsung Galaxy Tab A6 (Android 5.1.1), and HTC Desire 820 (Android 6.0.1), and there were no blanks, the app worked without stoppings.

https://github.com/obitodarky, can you still reproduce with the latest build?

**Comment by obitodarky** [comment]
@softvision-miralobontiu I can no longer update preview by going to Play Store, it does not appear in the Play Store for me.

**Comment by softvision-miralobontiu** [comment]
I'll file a bug for that. I cannot update either through Google Play.

**Comment by sblatz** [comment]
@obitodarky You should be able to see Firefox Preview on the play store either in the nightly channel or on the actual play store (now that it's a public release). Can you try again?

**Comment by obitodarky** [comment]
@sblatz Yes I updated preview from the PlayStore but I'm still getting this bug.

**Comment by liuche** [comment]
This is a pretty old bug, and I can't repro it anymore so I'm going to close it. Please reopen if it's still an issue.
