### ISSUE TITLE
FNX3-16776 ⁃ [Bug] Three dot menu have some irregular/bold icons

### ISSUE THREAD

**Issue by Scripterr** [mozilla-mobile/fenix#3083]
## Steps to reproduce
1.open web page.
2.click on three dot menu icon and observe.

### Expected behavior
It doesn't have any odd/bold icons.

### Actual behavior
It does have two odd/bold icons which are- save to collection and report site issue options icon.
![Screenshot](https://user-images.githubusercontent.com/42364681/58807122-021f2780-8607-11e9-95dd-177a54925c20.png)UNITO-UNDERSCORE!20190603-192312~2!

### Device information
* Android device: 8.0.0
* Fenix version: 1.0.1922 (Build #11530617 68.0-20190527103257)

**Comment by mheubusch** [comment]
@AmyYLee please review and close if these are implemented to spec.

**Comment by ekager** [comment]
These icons have already been updated, closing
