### ISSUE TITLE
FNX3-16779 ⁃ [Bug] Forward and back button don't have visually disabled state in Dark Theme

### ISSUE THREAD

**Issue by Scripterr** [mozilla-mobile/fenix#3087]
## Steps to reproduce
1.Open a page from search bar.
2.Click on the menu icon.

### Expected behavior
The menu do have a visually disabled state of forward and back button.

### Actual behavior
The menu don't have a visually disabled state of forward and back button

### Device information
* Android device: 8.0.0
* Fenix version: 1.0.1922 (Build #11530617 68.0-20190527103257)

**Comment by ekager** [comment]
In a specific theme? Dark, light, private? Or all themes?

**Comment by Scripterr** [comment]
> In a specific theme? Dark, light, private? Or all themes?

I'm using dark mode and I just have checked it's working well in light mode.

**Comment by pwd-github** [comment]
Unfortunately, the problem also exhibits in private tabs.

**Comment by LaurentiuApahideanSV** [comment]
I have verified the issue on a Samsung Galaxy Tab A (Android 7.0) and OnePlus 6T (Android 9) using the latest Firefox Preview 1.0.1924 (Build #11650657) 6/14 and the issue no longer occurs.
