### ISSUE TITLE
FNX3-16781 ⁃ Separate option for clearing the site data

### ISSUE THREAD

**Issue by Scripterr** [mozilla-mobile/fenix#3089]
### Why/User Benefit/User Problem
I would like to clear the site data while not deleting the browsing history because I would like to revisit the previous sites and don't need their site data to be saved which include the Cookies and site/image cache that takes up too much storage. It would be nice to be able to delete both things separately.

### What/Requirements
There should be different options present for deleting the browsing history and deleting the site data.

### Acceptance Criteria (how do I know when I’m done?)
There should be separate option for clearing the site data in delete browsing data fragment and can select and delete only site data.

**Comment by ekager** [comment]
It seems like we do have the APIs to delete these separately but are just bunching them together. CC @vesta0 for product decision.

https://github.com/mozilla-mobile/fenix/blob/04bbeb5ae69965d9f7276c3a77707866fe41affb/app/src/main/java/org/mozilla/fenix/settings/DeleteBrowsingDataFragment.kt#L227-L232

**Comment by vesta0** [comment]
Thanks @Scripterr and @ekager 

I have created a new issue #3106  to address this post-MVP as a fast follower.
