### ISSUE TITLE
FNX3-16782 ⁃ Define and consume Megazord build for app services libraries

### ISSUE THREAD

**Issue by csadilek** [mozilla-mobile/fenix#309]
Consuming megazord libraries will be important for minimizing APK size. Details can be found here: https://mozilla.github.io/application-services/docs/applications/consuming-megazord-libraries.html

We need to define the megazord, but it's likely going to be the same as for the Reference Browser.

**Comment by Sdaswani** [comment]
Whoever picks this up please talk to @csadilek and confirm the estimate (putting S for now).

**Comment by bbinto** [comment]
This should be done once the FxA integration into Fenix happens

**Comment by csadilek** [comment]
This landed as part of: https://github.com/mozilla-mobile/fenix/pull/548
