### ISSUE TITLE
FNX3-16786 ⁃ [Bug] Unable to see file suggestions when uploading a file on a site that uses file extensions filters (`accept` html property)

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/fenix#3097]
## Steps to reproduce
1. [Go to open an issue on the Fenix repo](https://github.com/mozilla-mobile/fenix/issues/new?assignees=&labels=%F0%9F%90%9E+bug&template=---bug-report.md&title=%5BBug%5D)
1. Tab the option **"Attach files by dragging & dropping, selecting or pasting them."**

### Expected behavior
Should show files with extensions **".gif,.jpeg,.jpg,.png,.docx,.gz,.log,.pdf,.pptx,.txt,.xlsx,.zip"** 

### Actual behavior
None files are shown, even when you have files with the supported extensions on your phone.

![image](https://user-images.githubusercontent.com/773158/58832322-b37c8800-861c-11e9-8b1b-c4e6a10d2759.png)

### Device information
* Android device: Pixel 3

**Comment by Amejia481** [comment]
a-c related issue: https://github.com/mozilla-mobile/android-components/issues/3227

**Comment by sv-ohorvath** [comment]
Verified as fixed on 6/5 on Pixel.
