### ISSUE TITLE
FNX3-16787 ⁃ [Bug] Unable to upload file on custom tabs

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/fenix#3098]
## Steps to reproduce
Try to upload a file on a custom tab.

### Expected behavior
The file browser app is shown and you can select files to be uploaded

### Actual behavior
The file browser app is not shown

### Device information
* Android device: Pixel 3

**Comment by Amejia481** [comment]
A-C Related issue: https://github.com/mozilla-mobile/android-components/issues/3228

**Comment by sv-ohorvath** [comment]
Verified as fixed on 6/5 on Pixel and Galaxy S8 (Android 9).
