### ISSUE TITLE
FNX3-16788 ⁃ As a user, I'm confused what "Save to Collection" would do, especially when looking to bookmark

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#3100]
As a user, I'm trying to figure out how to bookmark a site. I open the menu and see many options, none of which is "Bookmark". However, I see "Save to Collection": does this bookmark? What does it do?

When I click it, I enter to a "Add new collection" screen: weird, I'd expect to see bookmarks. When I click "Add new...", I'm asked to name it. Is this a bookmark folder? But I just want to add it to my general bookmarks list. Hitting enter says, "Tab saved". Great!

Now how do I access my bookmark? Unfortunately, there's no indication that I can find that this feature did anything.

Fenix version: 1.0.1920

**Comment by alexckwok** [comment]
I agree - it's strange how I can't add to an existing collection when I click "Save to Collection" in the menu; I have to create a new collection. Similarly, it's strange (and not as intuitive) how to add to an existing collection, I need to navigate back to the open tabs view, "save to collection", then selecting the tab I want to save to an existing collection & the collection I want to save it to.  

From what I've gathered Collections are essentially Bookmarks, though I've heard that they were also meant as a way to save sessions. If it was only a way to save sessions, it doesn't make sense to have it in the menu to save a single tab (assuming you have multiple tabs open) as a session. Similarly, if it's meant to be a new way to save Bookmarks, it would make more sense to have a way to add tabs to an already existing collection via the menu.

**Comment by mheubusch** [comment]
@topotropic please consider as you review collections and bookmarks.

**Comment by vesta0** [comment]
Will be addressed in #3894
