### ISSUE TITLE
FNX3-16789 ⁃ [Bug] Pressing back from Save to Collection enters an unexpected Select Tabs state

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#3101]
## Steps to reproduce
* Open menu
* Click Save to Collection
* Press back arrow at the top

### Expected behavior
Return to web page

### Actual behavior
Opens "Select Tabs" screen that I've never seen before

### Device information
* Android device: Pixe 2
* Fenix version: 1.0.1920

**Comment by softvision-miralobontiu** [comment]
Verified as fixed with the latest build 1.0.1923 (#11560607), with Google Pixel (Android 9), and Xiaomi Mi 8 Lite (Android 8.1).
