### ISSUE TITLE
FNX3-16790 ⁃ [Bug] Fullscreening video leaves gap at bottom

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#3102]
## Steps to reproduce
* Open a video on youtube
* Fullscreen

### Expected behavior
Video is fullscreened

### Actual behavior
Gap below fullscreened video. The gap seems to disappear sometimes, I think when the toolbar is scrolled off-screen.

![Screenshot](https://user-images.githubusercontent.com/759372/58836013-609ad480-860c-11e9-898b-31ff84904977.png)UNITO-UNDERSCORE!20190603-142338!

### Device information
* Android device: Pixel 2
* Fenix version: 1.0.1920

**Comment by ekager** [comment]
Can you update to the latest version, this may have been fixed by today's build?

**Comment by mcomella** [comment]
I can no longer reproduce.
