### ISSUE TITLE
FNX3-16791 ⁃ [Bug] Backgrounding app while video is fullscreen will break video controls & system navigation bar on foreground

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#3103]
## Steps to reproduce
* Open a youtube video
* Fullscreen
* Hit home to background app
* Foreground app again (e.g. recent apps)

### Expected behavior
Video is fullscreen and video controls are accessible OR video is no longer fullscreen

### Actual behavior
Video is fullscreen but video controls are blocked by the system navigation bar, which is incorrectly colored (white on white). Pressing back on this bar will close fullscreen but otherwise, the user is stuck.

![Screenshot](https://user-images.githubusercontent.com/759372/58836135-ba9b9a00-860c-11e9-92e8-6003ed70e4b0.png)UNITO-UNDERSCORE!20190603-142354!

### Device information
* Android device: Pixel 2
* Fenix version: 1.0.1920

**Comment by sv-ohorvath** [comment]
Verified that fullscreen is quit when minimizing the app. 
build 6/5
devices: Pixel, Galaxy S8 (Android 9), Nexus 5 (Android 6)
