### ISSUE TITLE
As a user, it is difficult to figure out how to bookmark

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#3104]
As a user, I wanted to bookmark a site. However, I really struggled to figure out how (despite being a fairly technical user). I looked in the obvious place – the 3-dot menu – and I saw "Save to Collection": does that do what I want? After clicking in, I realized it did not. I also tried to see if there was a link from, "Your library" – there wasn't, just the ability to view.

It took me a while to remember the slide-up drawer when browsing websites – where it's contained – and I'm concerned users will not discover this.

iirc, the drawer is expected to sit open for the first few times the user opens the app and then start closed. However, as a user, I never really looked at the contents of the drawer during this state (I was focused on the web content) so I didn't realize what functionality it contained. As such, when it came time to finally bookmark, several months into using the app, I couldn't figure out how to bookmark.

Overall, as a user, I currently find it difficult to figure out how to bookmark.

Fenix version: 1.0.1920

**Comment by mheubusch** [comment]
@topotropic FYI as you consider bookmarks.

**Comment by lime124** [comment]
removing ux label and unassigning nicole. we are in the process of collecting all bookmark issues to tackle in one effort

**Comment by lime124** [comment]
closing this as the QAB is going to be removed - see #5588
