### ISSUE TITLE
Granular options for clearing user data in Fenix

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/fenix#3106]
## User Story
* As a user, I want to have the option of clearing different types of personal data, so I can have more control over what I choose to keep or delete.

Types of personal data:

-Open Tabs
-Browsing history
-Search history
-Cookies and site data
-Cached images and files
-Site settings

### Requirements
* Behind a Feature Flag so QA can spend extra time testing

### Acceptance Criteria
* I can choose what type of user data to delete at any time

UX Spec (strings are done).
https://mozilla.invisionapp.com/share/63TIO0DPXTS

**Comment by lime124** [comment]
removing the ux label - this is on our radar already as it's part of Q3 plans.

**Comment by liuche** [comment]
Also look at #3700 because they seem like they'll be similar UI.

**Comment by liuche** [comment]
QA has said they'd like a little extra time to test this, so this should be ideally behind a feature flag.

**Comment by liuche** [comment]
Still some outstanding work, but should be resolved by 8/19.

**Comment by colintheshots** [comment]
Wait. The UX says "Site Permissions", but the user story says "Site Settings". Those are two, different things. We already have a screen that lets the user delete all site permissions. The new deletion options is Site Settings. I think we need to separate out that part of this story and get new strings to complete it properly. What should the new title and subtitle be? @mheubusch

**Comment by colintheshots** [comment]
I'll complete the story as written and we can update it later.

**Comment by jpfaller** [comment]
Verified the string as written (Site Permissions) is ok with @colintheshots

**Comment by colintheshots** [comment]
This is behind a feature flag in Nightly for now.

**Comment by andreicristianpetcu** [comment]
@colintheshots which flag?

**Comment by cadeyrn** [comment]
> @colintheshots which flag?

https://github.com/mozilla-mobile/fenix/blob/2b9efccfca4ef23a48e19c7934955a0bff32a409/app/src/main/java/org/mozilla/fenix/FeatureFlags.kt#L44

**Comment by neekless** [comment]
Will we eventually get even finer granularity i.e. Delete per site/domain?

**Comment by AndiAJ** [comment]
Hi, all **options work properly** from a functional point of view.

On the other hand, I've found a couple of minor issues on the latest Nightly Build #12590611 from 16/9 using a Google Pixel 3a (Android 9) as it follows:
• The delete browsing data is always enabled
• "Fenix" string placeholder %s is displayed in the confirmation pop-up message.

►Video
![20190916_171322](https://user-images.githubusercontent.com/51314259/64966189-036b1c00-d8a7-11e9-8e79-99140988aafd.gif)

I'll remove the QA needed label, until further clarifications.

**Comment by ekager** [comment]
Thanks @AndiAJ ! I opened https://github.com/mozilla-mobile/fenix/issues/5465 as a followup.
