### ISSUE TITLE
[Bug] Cannot update Firefox Preview from Taskcluster with command line

### ISSUE THREAD

**Issue by softvision-miralobontiu** [mozilla-mobile/fenix#3117]
## Steps to reproduce
1. Download the latest build from https://tools.taskcluster.net/index/project.mobile.fenix.v2.nightly/latest
1. Update Firefox Preview with the "adb install -r target.arm.apk" command.

### Expected behavior
Firefox Preview should update.

### Actual behavior
The app cannot be updated through command line. This message is displayed "C:\Users\mirabela.lobontiu>adb install -r target.arm.apk
adb: failed to install target.arm.apk: Failure [INSTALL_FAILED_UPDATE_INCOMPATIBLE: Package org.mozilla.fenix signatures do not match the previously installed version; ignoring!]"
Workaround: uninstall and reinstall works.

### Device information
* Android device: all
* Fenix version: 1.0.1923 (#11550608)

**Comment by sv-ohorvath** [comment]
No updates on Playstore either so far since the 6/4 build appeared 6hrs ago. Not sure how long it takes. The last one on the PS is the 6/3 build.

**Comment by pocmo** [comment]
@sv-ohorvath Nightly builds are currently signed with the wrong key (and therefore also do not appear on Google Play). @mitchhentges is working on fixing that.

**Comment by mitchhentges** [comment]
Hey, I was testing some key changes, but happened to time it incorrectly with the Fenix Nightly build.
As of [this build](https://taskcluster-ui.herokuapp.com/tasks/JdO8JZ3dRNCpTbVPnai8Sg) running, it should be fixed again.

Go ahead and follow the regular steps (download from the index, `adb install`), and it should be happy again now :)
