### ISSUE TITLE
Back press from Save to collection activity does nothing. [Bug]

### ISSUE THREAD

**Issue by SrikanthSd** [mozilla-mobile/fenix#3118]
## Steps to reproduce
1. Goto Menu
1. Click on Save to collection
1. Press back button on top left

### Expected behavior
It should go back!

### Actual behavior
Back press does nothing but animation. Have to close and re-open browser to comeback to home page.

### Device information
* Android device:  Redmi 6 pro (Pie 9.0)
* Fenix version: 1.0.1923

**Comment by ekager** [comment]
Fixed by #3113
