### ISSUE TITLE
FNX3-16803 ⁃ [Bug] Links opened in new tabs don't follow the most recent order

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#3124]
## Steps to reproduce
1. Go to wikipedia.com. 
1. Open links from the homepage in new tabs.
1. Check the tabs order in tabs view.
    1. Expected behavior
Tabs are ordered by most recent at the top.
    1. Actual behavior
When opening links in new tabs, the last ones opened are next to the parent tab.

    1. Device information

* Android device: Pixel (android 9)
* Fenix version: 6/4

**Comment by vesta0** [comment]
@mheubusch please confirm that this is expected behaviour.

**Comment by SeriousHoax** [comment]
If not by default then at least an option should be added to change the current behavior to the traditional one.

**Comment by sblatz** [comment]
This will likely need a-c work. I thought @pocmo worked on something regarding this recently 🤔 

### Demo
![Demooo 2019-07-19 17_21_31](https://user-images.githubusercontent.com/4400286/61571652-ae975a80-aa49-11e9-9588-537820edee46.gif)

**Comment by lime124** [comment]
@topotropic can you do some investigation and make a call as to what the expected ordering should be keeping in mind where we (firefox) want to be on as cross platform experience. 

once we know the answer, we can close the bug as won't fix, label it as ready for eng, or put it in the backlog if it needs more design work (e.g. setting route). thanks!

**Comment by topotropic** [comment]
This is expected behavior at the moment – we want to keep and display the relation between the tabs;
