### ISSUE TITLE
Add a Production build type to Fenix

### ISSUE THREAD

**Issue by ghost** [mozilla-mobile/fenix#3129]
We currently have no ~Release~ Production build type. This is a requirement for our 1.0 release.

**Comment by sarentz** [comment]
@mitchhentges would your recommend to name this 'Production' instead of 'Release' ?

**Comment by mitchhentges** [comment]
Yeah, I'd recommend "production" instead of "release" - some tooling (such as `gradle`) expects `release` to refer to any build that is user-visible (including `nightly` and `beta`). Using the term `production` allows us to side-step any ambiguity
