### ISSUE TITLE
[Bug] APK fails to install on BlackBerry 10

### ISSUE THREAD

**Issue by johnb-xp** [mozilla-mobile/fenix#3132]
## Steps to reproduce
Download APK from https://tools.taskcluster.net/index/project.mobile.fenix.signed-nightly.nightly/latest
Open file on BlackBerry 10 version 10.3.3.3216 (Android Runtime 4.3)

### Expected behavior
App installs and runs

### Actual behavior
Says "Unable to install this app"

### Device information
* Android device: BlackBerry Classic SQC100-2
* Fenix version: 1.0.1919

Yes, I still use a BlackBerry. I don't expect this to be fixed if it's a BlackBerry specific issue, but I won't "just buy a new phone". Firefox Android 67 is working perfectly. 
Is Android 4.3 supported?

**Comment by NotWoods** [comment]
Android 4.3 is not supported. We support Android 5 and up.

**Comment by kbrosnan** [comment]
Closing because of this.
