### ISSUE TITLE
FNX3-16810 ⁃ Add confirmation dialog to sign out of FxA

### ISSUE THREAD

**Issue by boek** [mozilla-mobile/fenix#3134]
### Why/User Benefit/User Problem
Make sure users actually want to sign out and disconnect Fenix from their FxA

### What/Requirements
![image](https://user-images.githubusercontent.com/1250545/58902350-c6906600-86b7-11e9-8e40-dc5f1a52c2fb.png)

### Acceptance Criteria (how do I know when I’m done?)
There is now a confirmation dialog to sign out

**Comment by softvision-miralobontiu** [comment]
This is not fixed yet. There is no confirmation dialog that the user had signed out of FxA.
Teste with a debug build 1.0.1928 GV 68.0-20190612114833 with Motorola Nexus 6 (Android 7,1,1), and Motorola Moto G6 (Android 8).

**Comment by softvision-miralobontiu** [comment]
Verified that there is a confirmation dialog when signing out.
Tested on the latest Nightly build 190717 (#11980613) with Sony Xperia Z5 Premium (Android 7.1.1), Samsung Galaxy Tab A6 (Android 5.1.1), and HTC 10 (Android 8), and on the latest Nightly build 190717 (#11980614) (aarch64) with Nexus 6P (Android 8.1.0).
