### ISSUE TITLE
FNX3-16811 ⁃ [Homescreen] Reduce sensitivity to swipe to delete gesture on Open tabs/collections

### ISSUE THREAD

**Issue by AmyYLee** [mozilla-mobile/fenix#3135]
Right now the swipe to delete gesture is pretty sensitive and it's easy to accidentally delete tabs when you're scrolling up and down the screen. 

Can we reduce the sensitivity?

**Comment by yoasif** [comment]
I have definitely seen this, especially on smaller screens like the Moto G I keep around for testing.

**Comment by yoasif** [comment]
Now it feels too hard to close. :/

Tested on Pixel 2 and Moto G.

**Comment by yoasif** [comment]
Had an idea... is it possible to use the same swipe sensitivity as is used in Android notifications? That is something people will be used to, and has probably had its own user testing.

**Comment by colintheshots** [comment]
I agree that it's now too hard to close a tab on swipe. We went a bit too far.

**Comment by softvision-miralobontiu** [comment]
Verified that the swipe for deleting the opened tabs is as smooth as swiping notifications.
Tested on the latest build 1.01926 (#11760617) with Nexus 5 (Android 6.0.1), Samsung Galaxy S8 (Android 9), and LG G7 Fit (Android 8.1).

**Comment by yoasif** [comment]
@softvision-miralobontiu please reopen this - I am on 1.0.1926 (Build #11780609 :lizard: 68.0-20190612114833) AC: 2.0.0 - and this is still an issue. Also seeing this feedback here: https://www.reddit.com/r/firefox/comments/c65ccq/firefox_preview_100_shipped/es6rd9o/

**Comment by kbrosnan** [comment]
Re-opening this bug is not the correct process. Code was checked in that resolves comment 0. The verification and closing is the last part of that change. We have new issues that track changing the behavior, I agree we made the springiness too heavy.

**Comment by tomasroaldsnes** [comment]
Springiness still to heavy. I want to flick it, but I need to swipe about 50% still.

**Comment by kbrosnan** [comment]
Are you using 1.0.1? Still changing the behavior would be a different issue.
