### ISSUE TITLE
[Bug] No media player controls on tagesschau.de

### ISSUE THREAD

**Issue by topotropic** [mozilla-mobile/fenix#3137]
## Steps to reproduce
1. go to tagesschau.de
1. tap on camera icon
1. go full screen

### Expected behavior
I see media controls to pause, exit fullscreen

### Actual behavior
There are no controls

### Device information
* Android device: Pixel 3
* Fenix version: 1.0.1923

**Comment by ekager** [comment]
Hi @topotropic I don't think I can access the media here based on where I am. Are you still seeing this?

**Comment by topotropic** [comment]
yes, still not seeing any controls in full screen – I don't think it's super urgent though, so if we have a webcompat list to put it on, that might be a good place.

**Comment by kbrosnan** [comment]
I see controls using Firefox Beta. Closing.
