### ISSUE TITLE
FNX3-16814 ⁃ [Bug] addons.mozilla.org favicon not appearing in bookmarks

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/fenix#3139]
## Steps to reproduce
1. Visit https://addons.mozilla.org
1. Bookmark page
1. view bookmark in library

### Expected behavior
I see the addons favicon. See how Bromite does it:

![signal-attachment-2019-06-04-142310](https://user-images.githubusercontent.com/152493/58904372-5bee2300-86d5-11e9-94d7-3b3a34d9c695.jpeg)UNITO-UNDERSCORE!001!

### Actual behavior
I see an "A" icon, not the actual favicon.

![signal-attachment-2019-06-04-135400](https://user-images.githubusercontent.com/152493/58904396-6b6d6c00-86d5-11e9-95c8-faeac1ab7836.jpeg)UNITO-UNDERSCORE!001!

### Device information
* Android device: Pixel 2
* Fenix version: latest from play store

**Comment by sblatz** [comment]
This will be fixed by https://github.com/mozilla-mobile/fenix/issues/3140.
