### ISSUE TITLE
FNX3-16815 ⁃  [Bug] addons.mozilla.org favicon not appearing in tab switcher

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/fenix#3140]
## Steps to reproduce
1. open addons.mozilla.org
1. tap tab switcher icon

### Expected behavior
I see the addons favicon. This is how bromite does it:

![signal-attachment-2019-06-04-142310](https://user-images.githubusercontent.com/152493/58904491-a374af00-86d5-11e9-8208-7bed377a5367.jpeg)UNITO-UNDERSCORE!002!

### Actual behavior
I see an "A" icon.

![signal-attachment-2019-06-04-135400](https://user-images.githubusercontent.com/152493/58904516-b12a3480-86d5-11e9-900d-0f9a73801e8b.jpeg)UNITO-UNDERSCORE!002!

### Device information
* Android device: Pixel 2
* Fenix version: latest from play store

**Comment by sblatz** [comment]
Will be addressed by https://github.com/mozilla-mobile/fenix/issues/4090
