### ISSUE TITLE
[Homescreen] Screen flashes when opening a tab from homescreen

### ISSUE THREAD

**Issue by AmyYLee** [mozilla-mobile/fenix#3141]
1. Open a new tab from homescreen and go to any URL
1. Return to homescreen
1. Tap on the tab again to open

Expected - Opens webpage with no screen flashing

Actual - Tab opens with screen flashing briefly beforehand 

See video for reference
https://cl.ly/29eec6d8dbe9

**Comment by vesta0** [comment]
@AmyYLee how is this different from #3142?

Looks like it was fixed when we removed the animation. Please re-open if you still see it.
