### ISSUE TITLE
[Homescreen] Screen flickers when opening a tab

### ISSUE THREAD

**Issue by AmyYLee** [mozilla-mobile/fenix#3142]
1. Open a new tab and go to any URL
1. Return to homescreen
1. Reopen the tab

Expected: Opens tab with no flickering 

Actual: Screen flickers briefly when tab opens

See video for reference
https://cl.ly/29eec6d8dbe9

**Comment by vesta0** [comment]
@AmyYLee it looks like this was fixed, please re-open if you notice it still.
