### ISSUE TITLE
Add UI test search bar reset when backgrounding app

### ISSUE THREAD

**Issue by dector** [mozilla-mobile/fenix#3143]
UI test for issue #1366 should be added.

`SearchFragment` is coupled with Activity and can't be tested in isolation. We should decouple fragment (requires some refactoring) or make some workaround (probably, test not-so-atomic-UI-scenario).

**Comment by sblatz** [comment]
We should definitely do this through a unit test :) I tried working on doing it with a UI test and ran into issues with UIAutomator not being able to resume our app after it's paused.

**Comment by dector** [comment]
@sblatz `FragmentScenario` should handle this case perfectly. Tbh I've did some job on this test but faced with huge refactoring because fragment itself is tightly coupled with the root activity. My idea was to be able to test fragment in a separate container (as `FragmentScenario` doing this).
