### ISSUE TITLE
Long press to bring up copy/paste/cut pop-ups not working sometimes.[Bug]

### ISSUE THREAD

**Issue by SrikanthSd** [mozilla-mobile/fenix#3144]
## Steps to reproduce
*Open any page contains text/input fields
*Try to copy/paste anything in text/input fields.

**Its not often.** Can't really mention when it is happening exactly. But its almost not possible to bring up those pop-ups sometimes.

### Expected behavior
Should bring up pop-ups such as copy/paste/cut/select all on long press on texts/input fields

### Actual behavior
No copy/paste/cut/select all options when trying to peform them on text/input fields.
Have to move cursor here&there to bring those pop-ups or sometimes have to reload the page to get the job done or sometimes impossible to perform copy/paste/cut/select-all.

### Device information
* Android device:  Redmi 6 pro (9.0)
* Fenix version: 1.0.1923 (Build #11551734 :lizard: 68.0-20190527103257)

**Comment by sv-ohorvath** [comment]
See: 
https://github.com/mozilla-mobile/fenix/issues/3530
https://github.com/mozilla-mobile/fenix/issues/3383
looks like it might be a duplicate.

**Comment by SrikanthSd** [comment]
Those two are duplicates.
