### ISSUE TITLE
FNX3-16821 ⁃ [Bug] Save to collection broken if only 1 tab is open

### ISSUE THREAD

**Issue by neekless** [mozilla-mobile/fenix#3156]
## Steps to reproduce
1. Open only 1 tab in Fenix.
1. Tap Save to collection.
1. Select existing collection or create new collection.

### Expected behavior
The tab is saved to collection.

### Actual behavior
The tab is not saved to collection. If user creates new collection, the new collection will be empty.

### Device information
* Android device: Pixel 2XL, Android 9
* Fenix version: 1.0.1923 (Build #11551859 :lizard: 68.0-20190527103257)

Possibly due to https://github.com/mozilla-mobile/fenix/pull/3113

**Comment by sv-ohorvath** [comment]
Verified as fixed on the 6/7 build. Devices: Pixel (Android 9), Nexus 5 (Android 6)
