### ISSUE TITLE
[Bug] Unexpected tab behaviour when try to Sign-in or Creating an account

### ISSUE THREAD

**Issue by SrikanthSd** [mozilla-mobile/fenix#3157]
## Steps to reproduce
1. Close all the tabs if opened any.
1. Navigate to Settings->Sign-in from three-dot menu.
1. Click on sign-in and also click on Create an account.

**I have attached video proof, please check that**

### Expected behavior
When clicked on sign-in and Create an account, respective pages should be opened without any problem.

### Actual behavior
When clicked on sign-in, Sign-in page isn't opening but tab is created to that respective sign-in page and minimized automatically. Same behaviour when clicked on Create An Account.
That behaviour can be seen often when no tabs are opened before.
Gdrive:  https://bit.ly/2HWZXlO 

### Device information
* Android device: Redmi 6 pro(Pie 9.0)
* Fenix version: 1.0.1923 (Build #11551734 :lizard: 68.0-20190527103257)

**Comment by sblatz** [comment]
This does not happen anymore as we're opening in custom tabs. Please re-open if you're still experiencing :)
