### ISSUE TITLE
[Bug] Sign in on first launch: tab not visible / the page not displayed

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#3158]
## Steps to reproduce
1. Launch a freshly installed app.
1. From the onboarding card, tap Sign in. Tap sign in in the Sync menu.
or
Go to Settings>Sign in and tap Sign in.
    1. Expected behavior
The sign in page is displayed in both cases.
    1. Actual behavior

* Opening the sign in page from the onboarding card, opens the tab behind the onboarding tour and it's not visible to the user.
* Opening it from the settings menu, opens a new visible tab on the homescreen, but it should display the webpage directly.

### Device information
* Android device: Pixel, Nexus 5
* Fenix version: 6/5

**Comment by SrikanthSd** [comment]
This is also happening with *create an account*.
This behaviour is rare if there are any tabs opened already.

**Comment by sblatz** [comment]
Looks like we're dismissing the onboarding when a user goes to Settings -> Turn on Sync and then closes the custom tab (and navigates back to the home view). I'm assuming this is unintentional. 

Is this the bug you're describing, @sv-ohorvath?

**Comment by sblatz** [comment]
Could be relevant to @apbitner's interests.

**Comment by sv-ohorvath** [comment]
@sblatz No, it was logged on the previous behavior, when the sign in page was opened in a homescreen tab, not in a custom tab. Not relevant anymore, I'm closing it.
