### ISSUE TITLE
FNX3-16824 ⁃ Animate the open tabs swipe to delete action

### ISSUE THREAD

**Issue by mythio** [mozilla-mobile/fenix#3159]
There is no animation when the user swipes to remove an open tab. 

Adding an animation or transition to the view (if recyclerView? then, notifyDataRemoved()) to animate the deleted part.

**Comment by NotWoods** [comment]
Fixed by #3233. We use a `ListAdapter` which internally calls `notifyDataRemoved`, and other items in the list animate to fill the space of the removed item.
