### ISSUE TITLE
Delete tab on home

### ISSUE THREAD

**Issue by topotropic** [mozilla-mobile/fenix#3160]
## Steps to reproduce
1. open a lot of tabs
1. scroll down on tab list (so that FF logo disappears)
1. delete a tab

### Expected behavior
View stays in place

### Actual behavior
View is re-loaded and jumps to top

**Comment by bifleming** [comment]
@topotropic can you still reproduce this?

**Comment by topotropic** [comment]
no it's fixed. Thanks!
