### ISSUE TITLE
Collections: Selected tab should be first in list

### ISSUE THREAD

**Issue by topotropic** [mozilla-mobile/fenix#3161]
## Steps to reproduce
1. Open a bunch of tabs
1. Longpress on first tab to select

### Expected behavior
I see the tab I selected as first element in the list and can scroll up or down to select more tabs

### Actual behavior
List starts with last tab and I have to scroll up to see my selected tab

**Comment by vesta0** [comment]
@AmyYLee to consider for user testing.

**Comment by vesta0** [comment]
@topotropic what do you think of this behaviour instead? #2627

**Comment by ekager** [comment]
Talked to @topotropic and she doesn't need this pulled into this sprint

**Comment by vesta0** [comment]
Waiting until after user testing the new tab tray.

**Comment by liuche** [comment]
@vesta0 any updates from the UR on tab tray? Or is there someone else that I can ask (to keep it off your plate)

**Comment by topotropic** [comment]
We had a delays in the test setup and need to re-evaluate the insights beginning of next week.

**Comment by topotropic** [comment]
We can close it, we'll revisit how we handle this.
