### ISSUE TITLE
Add support for trigger the Fenix production pipeline with a Github release

### ISSUE THREAD

**Issue by mitchhentges** [mozilla-mobile/fenix#3164]
* [x] Tagging with `1.0.0` or `1.0.0-rc.0` should both trigger Fenix production releases
* [x] The release should be deployed to the "Firefox Preview" app (`org.mozilla.fenix`) on the `internal` track

**Comment by sarentz** [comment]
@mitchhentges can we close this bug?

**Comment by mitchhentges** [comment]
Affirmative, this is complete, thanks!
