### ISSUE TITLE
Limit beta/production releases to the `releases/*` branches

### ISSUE THREAD

**Issue by mitchhentges** [mozilla-mobile/fenix#3165]
[Reference](https://mozilla.slack.com/archives/CK6TXNDQU/p1559736727000800)

We don't want to release beta/production from the `master` branch. By forcing the releaser to create a separate branch (e.g.: `releases/1.0.0`) first, we can increase confidence that we're releasing ready-to-ship code

**Comment by kbrosnan** [comment]
A lot has changed about our build infrastructure @JohanLorenzo is this still applicable?

**Comment by JohanLorenzo** [comment]
I still applicable as of today. But we've worked on https://bugzilla.mozilla.org/show_bug.cgi?id=1568466 to address that. I don't know whether this remains a priority after the layoff. Let's keep it open for now and I'll get back once I have more information.
