### ISSUE TITLE
FNX3-16830 ⁃ [Bug] "Feature not implemented" on site menu "Help"

### ISSUE THREAD

**Issue by topotropic** [mozilla-mobile/fenix#3167]
## Steps to reproduce
1. Go to a site
1. Open 3-dot menu and tap on "Help"

### Expected behavior
Help section opens

### Actual behavior
I see a "Feature not implemented" snackbar

**Comment by vesta0** [comment]
Let's make sure it's directed to the placeholder URL for Help.

**Comment by softvision-miralobontiu** [comment]
Verified as fixed with the latest build 1.0.1923 (#11580610), with Samsung Galaxy S8 (Android 9), and Huawei P9 Lite (Android 6).
