### ISSUE TITLE
FNX3-16831 ⁃ [Collections] No confirmation when tapping on "Open tabs" in Collection 3-dot leads people to press multiple times and end up with duplicates

### ISSUE THREAD

**Issue by AmyYLee** [mozilla-mobile/fenix#3168]
1. Create a collection
1. Go to the 3-dot menu in a collection and tab on "Open tabs"

Expected: When the user clicks on "Open tabs", automatically scroll to the open tabs section (see screenshot for anchor placement)

Result: Tabs are opened but they are outside the viewport of the screen so it doesn't look like anything has happened

![Screenshot](https://user-images.githubusercontent.com/5992746/58966996-4f270900-8781-11e9-9fb1-5cd09bbe9f0e.png)UNITO-UNDERSCORE!20190605-105910!

**Comment by AmyYLee** [comment]
Spec to show how it should scroll to "Open Tabs" header when opening tabs from a collection
https://mozilla.invisionapp.com/share/73SDGWMRDFS#/screens

**Comment by sblatz** [comment]
Looks like @ekager [already implemented this](https://github.com/mozilla-mobile/fenix/pull/3279)

**Comment by ekager** [comment]
I have added an action to scroll to the open tabs section of the home screen.

**Comment by sv-ohorvath** [comment]
Verified as fixed on the 6/12 build. Devices: Nexus 5, Galaxy Tab S3, Samsung Note 8.
