### ISSUE TITLE
[Bug] Spacing issue between Collection cards

### ISSUE THREAD

**Issue by topotropic** [mozilla-mobile/fenix#3169]
## Steps to reproduce
create 2 collections

### Expected behavior
there's 12dp spacing between the cards

### Actual behavior
cards are too close together

### Device information
* Android device: Pixel 3
* Fenix version: 1.0.1923

![Screenshot](https://user-images.githubusercontent.com/353960/58973047-4b19dc00-87bf-11e9-9ad9-d32aae6b7079.png)UNITO-UNDERSCORE!20190605-164231!

**Comment by bifleming** [comment]
@topotropic can you still reproduce this?

**Comment by topotropic** [comment]
no, fixed. Thanks!
