### ISSUE TITLE
FNX3-16833 ⁃ Consider new UX for crash handling

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#3170]
Since GV only has one engine process for each of our tabs, if one crashes, they all go down. 
If a user has multiple tabs, and one crashes, the rest turn into `about:blank` unless we forcibly restore them. We should create a new design that allows the user to select which tabs they want to restore (since currently they only have the ability to restore the one they're currently on.

~In the meantime, I would strongly urge us to iterate the session list and attempt a crash recovery on all of them except for the selected session (which will either close or recover based on user interaction on the crash fragment)~

(*NOTE: This is covered by #1809*)

![](https://user-images.githubusercontent.com/4400286/58973516-023d3580-8775-11e9-9259-e7a01e225465.png)

@vesta0 I believe that at least the temporary solution is something we'd want for MVP as leaving the user with tons of `about:blank` pages is something we often heard (understandable) complaints about in Focus

**Comment by vesta0** [comment]
@sblatz great suggestion. Is this similar to #1809 ?

**Comment by sblatz** [comment]
I think my "MVP suggestion" is the same as #1809. I think it'd be useful to keep this ticket open as a UX reconsideration as this could be confusing to users.

**Comment by pocmo** [comment]
Looking at #2814 I also wonder how we should represent crashed tabs in the home screen if that is the one you are on at the time of the crash (or when you resume the app).

**Comment by lime124** [comment]
@vesta0 this isn't really a feature request but more of an enhancement to current designs (which is probably why you removed the label). from our side it's going to take some more thinking and effort so we would want to add it to our other work and prioritize it. 

i'd like to remove the needs ux label as we won't put our attention to it until the team prioritizes it but i'm not sure what other label to apply. do we need a new "enhancements" label?

**Comment by vesta0** [comment]
@lime124 I like the idea of a new `enhancement` label since many things fall under that category.

**Comment by sblatz** [comment]
The UX currently is that all the tabs crash, then if a user presses "close tab" the user is sent back to home screen and the other tabs show "about:blank" for a split second before they're also restored

**Comment by liuche** [comment]
Once one tab crashes, since we don't have E10S multi-process, anything that shares that process will crash because we can't fix this until GV gets this in Q2 2020. So we'll close it for now.
