### ISSUE TITLE
FNX3-16835 ⁃ Search fragment editToolbar should grab focus after resuming

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#3175]
With https://github.com/mozilla-mobile/fenix/issues/1366 we made it so the text would restore when entering the search fragment. Because of this, we're no longer calling browserToolbar.editMode() each time, which means that the [focus is not getting set](https://github.com/mozilla-mobile/android-components/blob/master/components/browser/toolbar/src/main/java/mozilla/components/browser/toolbar/BrowserToolbar.kt#L514-L523)

We should update browserToolbar to have a `setFocus` function which just does this for editToolbar.

a-c issue: https://github.com/mozilla-mobile/android-components/issues/3274

**Comment by softvision-miralobontiu** [comment]
Verified as fixed, the focus remains on the search bar after resuming.
Tested on the latest Nightly build 190710 (#11910617) with Samsung Galaxy Tab A6 (Android 5.1.1), Huawei Honor 8 (Android 7), and HTC 10 (Android 8).
