### ISSUE TITLE
FNX3-16839 ⁃ [Bug] fenix about:telemetry crasher

### ISSUE THREAD

**Issue by bdekoz** [mozilla-mobile/fenix#3180]
## Steps to reproduce
checkout mozilla-mobile/fenix
build it
install fenix apk on android device
enable USB debugging, connect device to workstation

1) on workstation: enter 'adb devices' in terminal
(make sure connected, when device is continue...)
2) on workstation, enter in terminal:
adb shell am start ~~W~~ n org.mozilla.fenix.debug/org.mozilla.fenix.IntentReceiverActivity  ~~a android.intent.action.VIEW~~ d  https://www.theguardian.com/world/all 
3) on android device: wait for browser screen to come up
4) set timer for 2 minutes, after it has elapsed, continue
5) on workstation, enter in terminal:
adb shell am start ~~W~~ n org.mozilla.fenix.debug/org.mozilla.fenix.IntentReceiverActivity  ~~a android.intent.action.VIEW~~ d about:telemetry

6) on android device: new screen should have typical about:telemetry page. On right hand side, click on 'raw JSON', wait for that to come up
7) when that screen comes up, click on 'share' button and try to send as email, copy to clipboard, or sync with other devices

### Expected behavior
ping shared, glean metrics or baseline ping not gv main ping, etc

![fenix-at-1](https://user-images.githubusercontent.com/997439/58982723-f4de7600-8789-11e9-994a-bab5e92e2301.png)
![fenix-at-3-raw](https://user-images.githubusercontent.com/997439/58982724-f4de7600-8789-11e9-8d40-16439ee8d76e.png)
![fenix-at-4-kaboom](https://user-images.githubusercontent.com/997439/58982725-f4de7600-8789-11e9-9b62-eb8f76bde7c0.png)
![fenix-at-2](https://user-images.githubusercontent.com/997439/58982726-f4de7600-8789-11e9-8274-b8522d4ffae8.png)

, etc etc

### Actual behavior
8) KABOOM

### Device information
* Android device: pixel 2
* Fenix version: built from source 2019-06-05

**Comment by Dexterp37** [comment]
> ### Expected behavior
> 
> ping shared, glean metrics or baseline ping not gv main ping, etc
 
This is **not** the expected behaviour :) `about:telemetry` happens to be exposed, but doesn't really know about Glean. That's why we filed [bug 1558156](https://bugzilla.mozilla.org/show_bug.cgi?id=1558156). This page should probably not be exported in GeckoView, since it contains wrong and confusing data due to the fact that desktop telemetry is only partially enabled (the core recording mechanism is enabled, the application/ping logic is disabled).

**Comment by vesta0** [comment]
The crash cannot be reproduced. 

@liuche please confirm that we are displaying the correct information on this page.

**Comment by liuche** [comment]
Based on [bug 1558156](https://bugzilla.mozilla.org/show_bug.cgi?id=1558156) which is for GV to handle about: pages, and isn't a priority for GV right now.

about:telemetry is also exposed only on Nightly (and based on the bug, that info isn't really correct bc it doesn't include Glean). If we want to prioritize this, next steps would be to talk to GV/Glean about what we want (correct complete data? link to Glean docs?) and how to expose that.

**Comment by vesta0** [comment]
@liuche and if we don't want to prioritize exposing Glean data for now, then we should hide the page in Fenix right?

**Comment by liuche** [comment]
Yes, I think that's correct, so we stop showing incomplete data. We could either as GV team to hide it for us (more correct) or we could add in some code in Fenix itself to not show it.

**Comment by kbrosnan** [comment]
This crash does not reproduce. We should open up a different issue if we want to expose Glean data in Fenix somewhere.
