### ISSUE TITLE
Set up Sentry token for each channel

### ISSUE THREAD

**Issue by mitchhentges** [mozilla-mobile/fenix#3186]
We currently have two Sentry tokens: one for nightly and one for beta.
We need a Sentry token for production, as well.

Note: [Colin mentioned](https://mozilla.slack.com/archives/CG2FGG1ST/p1559764132045300?thread_ts=1559764051.044200&cid=CG2FGG1ST) that the "nightly" sentry dsn might actually be the "production" one? If so, how do we want to handle "old" crashes and pointing production to that DSN instead?

**Comment by colintheshots** [comment]
We opted to add a Sentry environment based on the Gradle build type, so this became moot. We get the same effect essentially.

**Comment by sv-ohorvath** [comment]
@colintheshots Does this need QA?
