### ISSUE TITLE
Consider continuing to play video content when app is backgrounded

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#3193]
### Why/User Benefit/User Problem
Sometimes users want to continue playing video content from the browser when the app is backgrounded. For example, they might be listening to music on YouTube. In Fennec, this was a differentiator from Chrome that users often spoke out about when it broke.

It appears this does not happen for audio content: that continues to play in the background even when the app is backgroudned.

### Acceptance Criteria (how do I know when I’m done?)
* [ ] Under some conditions, users can continue to play video content even when the browser is backgrounded (e.g. users may want to opt in)

**Comment by ekager** [comment]
We are planning on doing this, we just need to make sure it's done the correct way (with a notification so user can know where the content is coming from and stop when they want it to). See https://github.com/mozilla-mobile/fenix/issues/1112 and
https://github.com/mozilla-mobile/fenix/issues/1113

And more history about our current solution in https://github.com/mozilla-mobile/fenix/issues/1679

**Comment by vesta0** [comment]
Will address in #1113
