### ISSUE TITLE
FNX3-16846 ⁃ [Bug] Audio content continues to play after tab is closed, until undo snackbar disappears

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#3194]
## Steps to reproduce
* Open audio content (e.g. pick first item on soundcloud.com)
* Open tabs tray
* Swipe to close tab

### Expected behavior
Audio stops

### Actual behavior
Audio continues playing until "Undo" tab removal snackbar disappears.

This issue does not affect YouTube because YouTube appears to intentionally pauses audio content when the browser window goes to the background (e.g. behind the tabs tray).

### Device information
* Android device: Pixel 2
* Fenix version: 1.0.1920

**Comment by Eccenux** [comment]
Weird because in Firefox Preview audio stops playing as soon as I go to the tabs tray. Which is worse because I want podcasts to keep playing in background. This how it is in current Firefox for Android.

Related issue: Persistent notification when audio is playing in Fenix #2551

**Comment by mcomella** [comment]
> Weird because in Firefox Preview audio stops playing as soon as I go to the tabs tray.

I notice that behavior on YouTube.com but on other sites I notice my behavior: the audio continues playing in the background, including when the app is backgrounded.

**Comment by sv-sdeiac** [comment]
Hello, I can reproduce this issue using Google Pixel (Android Q) with the latest version of Firefox Preview Nightly 1/6 build #20060605.

My steps to reproduce are:
1. Go to rockfm.ro;
2. Start the radio music;
3. Open the tab tray;
4. close the media tab;

The actual results are the same as in the description.
For more investigations, please don't hesitate to ask for them, thanks.

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly Build #21060608 from 4/15`** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)

► Video
![20200415-145535](https://user-images.githubusercontent.com/51314259/79334914-cdb80f80-7f29-11ea-9eba-e876fb2b8317.gif)

✔️ The audio stops as soon as the user closes the tab.
PS. The notification is dismissed only after the confirmation disappears
