### ISSUE TITLE
FNX3-16849 ⁃ The collection-selecting screen doesn't appear if the only collection has been just created[Bug]

### ISSUE THREAD

**Issue by DiegoARL38** [mozilla-mobile/fenix#3199]
## Steps to reproduce
1. Have no collections.
1. Go to any site and add it to a collection via the 3-dot menu. Since no collections exist, create one.
1. Go to another site without navigating to the Home screen and try to add it to a collection.
    1. Expected behavior
The collection-selecting screen appears with the collection created on step 2.
    1. Actual behavior
The collection-selecting screen doesn't appear. Instead, the collection-naming screen is displayed, as if there were no collections already.
    1. Device information

* Android device: TP-Link Neffos C5 Max (Android 5.1)
* Fenix version: Build #11561807
    1. Notes
* This doesn't happen if one navigates to the Home screen between steps 2 and 3.

**Comment by sv-ohorvath** [comment]
This is reproducible even if there are other collections created. While creating the second, the first is not shown in the select collections list.

**Comment by ekager** [comment]
I cannot reproduce this anymore. Adding QA needed label to verify

**Comment by sv-ohorvath** [comment]
I can't reproduce either on Nightly 7/15. Devices:Nexus 5(Android 6.0.1), Galaxy S8 (Android 9).
