### ISSUE TITLE
FNX3-16850 ⁃ [Bug] Page opened in a new tab from a bookmarked page, appears bookmarked

### ISSUE THREAD

**Issue by softvision-miralobontiu** [mozilla-mobile/fenix#3201]
## Steps to reproduce
1. Go to a page that has multiple links (e.g. an article from wikipedia.org).
1. Bookmark the page.
1. Long tap on a linked text and select to open it in a new tab.
1. Tap on "Switch" and observe the QAB.

### Expected behavior
The newly opened page is not bookmarked.

### Actual behavior
The newly opened page is bookmarked. When tapping on counter tabs, then reopen the page, it is no longer bookmarked.

### Device information
* Android device: Xiaomi Mi 8 Lite (Android 8.1), Motorola Nexus 6 (Android 7.1.1), Huawei MediaPad M2 (Android 5.1.1)
* Fenix version: 1.0.1923 (#11561806)

![bookmarks](https://user-images.githubusercontent.com/40694158/59016836-ddb38d00-884a-11e9-8c15-da1750bb287f.gif)

**Comment by ekager** [comment]
I think we'll just have to add `updateBookmarkState(session)` to `onSessionSelected()`. @colintheshots are you still on this one?

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest Fenix Build **`#11850611 from 4/7`** using the following devices:
• Google Pixel 3XL (Android 9)
• Samsung Galaxy S8+ (Android 8)
• Samsung Galaxy S7 (Android 7.0)
• Samsung Galaxy S6 (Android 6.0.1)
• Sony Xperia Z3 (Android 5.1.1)

►Video from Google Pixel 3XL
![2019_07_04_12_24_35](https://user-images.githubusercontent.com/51314259/60656198-bd7dea80-9e57-11e9-97d8-790503328669.gif)
