### ISSUE TITLE
FNX3-16852 ⁃ [Bug] Desktop folders names don't match in edit mode

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#3203]
## Steps to reproduce
1. Create a bookmark.
1. Edit the bookmarks, tap the parent folder.
1. Observe the desktop folders names.
    1. Expected behavior
Folder names in bookmark edit view should match the default ones in the bookmarks library view.
    1. Actual behavior
![Screenshot](https://user-images.githubusercontent.com/4037709/59022591-b1057280-8856-11e9-92cc-47643ddcb765.png)UNITO-UNDERSCORE!20190606-122831!

### Device information
* Android device: Htc 10 (Android 8)
* Fenix version: 6/6

**Comment by vesta0** [comment]
Please also fix the text/icon alignment :)

**Comment by sblatz** [comment]
(I believe Vesta is referring to the vertical alignment, btw)

**Comment by abodea** [comment]
Verified as fixed on the latest build **`6/13`** using **`Samsung Galaxy Note 9(Android 8.1.10).`**

**Comment by sv-ohorvath** [comment]
see also: https://github.com/mozilla-mobile/fenix/issues/3426 & https://github.com/mozilla-mobile/fenix/issues/3427
