### ISSUE TITLE
Pressing on an email address link should launch the email app

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#3205]
## Steps to reproduce
1. Go to rpappalax.github.io/testapp. 
1. Tap the Email link. 
    1. Expected behavior
The default email app is launched with the email address filled in.
    1. Actual behavior
Nothing happens.

* Fenix version: 6/6

**Comment by Amejia481** [comment]
This behavior is implemented as part of [ac#3058](https://github.com/mozilla-mobile/android-components/pull/3058) but is blocked 🛑  by #3358. It can be seen working on sample browser.

**Comment by jhugman** [comment]
This corresponds to [ac#3725][0].

[0]: https://github.com/mozilla-mobile/android-components/issues/3725
