### ISSUE TITLE
FNX3-16861 ⁃ [Bug] Returning from bookmark edit mode, multi-select doesn't work

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#3213]
## Steps to reproduce
1. Go to Bookmarks.
1. Edit a bookmark. Return to bookmarks.
1. Long tap to select a bookmark.
    1. Expected behavior
Multi-selection mode is triggered.
    1. Actual behavior
Multiple-selection doesn't work.
    1. Device information

* Android device: HTC 10 (Android 8), Motorola Nexus 6 (Android 7.1.1)
* Fenix version: 6/6

**Comment by softvision-miralobontiu** [comment]
Verified as fixed on the latest build 1.0.1926 (#11770618) with Motorola Moto G6 (Android 8), and Nokia 6 (Android 7.1.1).

**Comment by sv-ohorvath** [comment]
Also verified on the RC 1.0.1 build. Nexus 9 (Android 7.1.1), Google Pixel 3 (Android 9).
