### ISSUE TITLE
FNX3-16862 ⁃ [Bug] History multi-selection aborted, the same item can't be selected again

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#3214]
## Steps to reproduce
1. Go to History.
1. Long tap to select an item. 
1. Press the back button to cancel.
1. Long tap again on the same item.
    1. Expected behavior
Re-select the item.
    1. Actual behavior
Can't select the item.
    1. Device information

* Android device: HTC 10 (Android 8), Motorola Nexus 6 (Android 7.1.1)
* Fenix version: 6/6

**Comment by AnutaLogigan** [comment]
I was able to reproduce this issue using the steps added by Oana. Looking into it.

**Comment by vesta0** [comment]
@sv-ohorvath @colintheshots was this fixed? I can't reproduce it but it doesn't have a QA needed label.

**Comment by ekager** [comment]
Looks like a commit referenced this 2 days ago @vesta0 . I added the QA needed label

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest Fenix build (**1.0.1926 Build #11780608from 27/6**) on the following devices:
• Google Pixel 3XL(Android 9)
• Huawei Mate 20 lite (Android 8.1)
• Samsung Galaxy S7 (Android 7)
• Samsung Galaxy J7 (Android 6.0.1)
• Sony Xperia Z3 (Android 5.1.1)

**Comment by sv-ohorvath** [comment]
Also verified on the RC 1.0.1 build. Nexus 9 (Android 7.1.1), Google Pixel 3 (Android 9).
