### ISSUE TITLE
FNX3-16863 ⁃ [Bug] Opening a tab that was saved to a collection should restore the history as well

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#3215]
@AmyYLee mentioned this to me. This is a quick fix and is fundamental to how collections work.

## STR
1. Open a page (e.g. mozilla.org)
1. Navigate to another page within that domain (click on a link)
1. Save to collection (new or existing)
1. Go to home page
1. Close the tab
1. Find the collection it was saved in, tap to expand it
1. Open the tab by tapping on it
1. Press the _back_ button

## Expected
1. The page loads the original domain (e.g. mozilla.org), showing that the history of the tab was maintained

## Actual
1. User is sent back to home screen showing that history is **not** maintained.

**Comment by sv-ohorvath** [comment]
@sblatz Can I please get some STR?

**Comment by sblatz** [comment]
@sv-ohorvath sorry about that--added STR!

**Comment by sv-ohorvath** [comment]
Thanks @sblatz! Verified as fixed on the 6/8 build.

**Comment by sblatz** [comment]
@vesta0 we are going to intentionally revert this bug. It's causing issues (and crashes) due to session id's no longer being unique. A long term solution [has been filed in a-c]() but I want to make sure we're not crashing in the meantime.

Bug caused by this ticket: https://github.com/mozilla-mobile/fenix/issues/3217#issuecomment-500395803

**Comment by vesta0** [comment]
Thank you @sblatz I chatted with Christian about it earlier too :)

**Comment by sblatz** [comment]
Re-opening this since this functionality has been reverted. We can now use [this a-c fix](https://github.com/mozilla-mobile/android-components/issues/3341)

**Comment by sblatz** [comment]
I'm assuming we don't want this as an MVP blocker anymore, @vesta0.

**Comment by vesta0** [comment]
@sblatz I don't think this should have been an MVP blocker to begin with :) Not 100% convinced that this is the desired functionality.

**Comment by vesta0** [comment]
Keeping it as a p1 so we can discuss next sprint :)

**Comment by softvision-miralobontiu** [comment]
Verified as fixed on the latest build 1.0.1926 (#11760617) with Nexus 5 (Android 6.0.1), and LG G7 Fit (Android 8.1).
