### ISSUE TITLE
[Collections] Needs a confirmation snackbar after deleting a collection

### ISSUE THREAD

**Issue by AmyYLee** [mozilla-mobile/fenix#3216]
1. Open the 3-dot menu from a collection and select "Delete collection"
1. Select "Delete" in the confirmation dialogue

Expected: snackbar notification with an "undo" button pop-ups and closes after time-out (same snackbar as when you delete a tab)

Actual:
No snackbar appears

**Comment by sblatz** [comment]
This is expected behavior for now, as we're having [lots of problems with undo snackbars](https://github.com/mozilla-mobile/fenix/issues/2784)

**Comment by sblatz** [comment]
This is a dup of https://github.com/mozilla-mobile/fenix/issues/2783
