### ISSUE TITLE
[Bug] Closing tab that's in a collection, then opening it quickly closes it again

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#3217]
After implementing #3215 we now are using the same session id's. This means that the delete function finds and deletes the restored tab.

We **should** be invoking the pending deletion jobs before restoring. Perhaps we should "wait" on that before restoring the new tabs?

![restore bug 2019-06-06 09](https://user-images.githubusercontent.com/4400286/59048399-932a1480-883a-11e9-92cd-752b243e4836.gif)UNITO-UNDERSCORE!06!UNITO-UNDERSCORE!07!

**Comment by sv-ohorvath** [comment]
The same if you open a tab from a collection twice, then close one of the duplicates. It will remove both and then restores one :)

**Comment by sblatz** [comment]
This will be closed by https://github.com/mozilla-mobile/fenix/pull/3320, as we're reverting a change that was causing this bug.
