### ISSUE TITLE
[Collections] Needs a snackbar confirmation after deleting a collection

### ISSUE THREAD

**Issue by AmyYLee** [mozilla-mobile/fenix#3218]
1. Open 3-dot menu on a collection and select "Delete collection"
1. Select "Delete" in the confirmation dialogue

Expected:
A snackbar notification pop-ups with "Collection deleted" an UNDO button (same as when you delete a tab).

Actual:
No snackbar notification.

**Comment by sblatz** [comment]
Dupe of #3216?
