### ISSUE TITLE
[Meta] Support Android Intents

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/fenix#3223]
## User Story
* As a user, I want my browser to interact with other applications on my phone (e.g. Google Play Store, other installed apps, Call and Email and Text apps, Maps, etc)

### Acceptance Criteria
* All user stories are closed

**Comment by snorp** [comment]
See the following for how Fennec handles these

https://searchfox.org/mozilla-central/source/mobile/android/geckoview/src/main/java/org/mozilla/gecko/util/IntentUtils.java#188

**Comment by vesta0** [comment]
Will be addressed [here](https://github.com/orgs/mozilla-mobile/projects/32/edit)
