### ISSUE TITLE
Change links to FxA login form to email first form

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla-mobile/fenix#3232]
The FxA email first form (action=email&style=trailhead) will have the ecosystem promo at the bottom, but the login form will not. We would like to replace links to signin with /action=email

Looks like it might be here:
https://github.com/mozilla-mobile/fenix/blob/master/app/src/main/java/org/mozilla/fenix/components/features/FirefoxAccountsAuthFeature.kt

**Comment by ryanfeeley** [comment]
See iOS: https://github.com/mozilla-mobile/firefox-ios/issues/5096

**Comment by vesta0** [comment]
@ryanfeeley please confirm that the FxA login form in Fenix matches the most recent designs.

**Comment by vesta0** [comment]
@ryanfeeley is this still an issue?

**Comment by ekager** [comment]
If this is still an issue, `FirefoxAccountsAuthFeature` lives in AC and would need updating there

**Comment by ekager** [comment]
I think we are now using the updated design for this login form. I am closing this issue.
