### ISSUE TITLE
FNX3-16873 ⁃ [Bug] "AccountSettingsFragment" shows up in Preferences title momentarily

### ISSUE THREAD

**Issue by grigoryk** [mozilla-mobile/fenix#3234]
I just saw "AccountSettingsFragment" momentarily show up in the title in Fenix Preferences while navigating, instead of a proper title. It goes away after a fraction of a second. Visually it looks like a strange flicker, I've seen this before but this time it was slow enough to read the wrong title.

**Comment by abodea** [comment]
Hello @grigoryk I couldn't reproduce this issue with the latest build from 6/12 with a Google Pixel 3Xl(Android 9), Samsung Galaxy Note 9(Android 8.1.), HTC M9(Android 6).
Are there any extra steps regarding this issue?
* Please note that there is a little flicker but that is when you enter **`Account Settings`** and tap on the back button for few times very fast, but this is not a normal user behavior and even with this flicker there is no **`AccountSettingsFragment`** displayed.
* Can you please re-check in the latest version and let us know about STR and device(android version) are you using? 
* Based on my comment I will remove the QA Needed and once we will have more information regarding this issue we can verify it.

Thanks,
Andrei

**Comment by abodea** [comment]
I synced up with @ekager and she confirmed that this was fixed and as I couldn't reproduce the issue I will verify it as fixed.
>I Oh yeah I think we can close this! The fix was straightforward

Based on this I will verify the issue as fixed.
