### ISSUE TITLE
Remove “Already have an account?” copy on Welcome page

### ISSUE THREAD

**Issue by vladikoff** [mozilla-mobile/fenix#3236]
Should we remove “Already have an account?” copy on Welcome page

@ryanfeeley to confirm?

![image](https://user-images.githubusercontent.com/128755/59068093-474e8e00-8881-11e9-8eac-5d042bd66e91.png)

**Comment by vesta0** [comment]
@mheubusch please advise.

**Comment by ryanfeeley** [comment]
We want copy to include prospective and existing users, so I don't think the _Already…_ line is necessary.

**Comment by ekager** [comment]
@vesta0 I don't think this is blocked? If it's just removing that line with no string substitute we can do that now

**Comment by vladikoff** [comment]
if @mheubusch agrees on this, then let's do it!

**Comment by vesta0** [comment]
I am good with removing it but I'd like to make sure @mheubusch is also ok with removing or whether she wants to re-word it. She has a high level overview of unified messaging across platforms.

**Comment by mheubusch** [comment]
We can remove it for now - the message was supposed to be part of the account sign in panel, but the design does not make this clear it is part of the message. I will ask @apbitner to  revisit if we do onboarding enhancements. Ok to remove and then close.

**Comment by ekager** [comment]
Closing because I will pick this up when completing #3772
