### ISSUE TITLE
FNX3-16875 ⁃ Implement the new pairing / fxa sign in screens based on user research

### ISSUE THREAD

**Issue by vladikoff** [mozilla-mobile/fenix#3237]
@ryanfeeley could you paste the new design here?

**Comment by vladikoff** [comment]
![image](https://user-images.githubusercontent.com/128755/59069143-5125c080-8884-11e9-86b1-376816826bd1.png)

**Comment by ryanfeeley** [comment]
@vladikoff SVG scanning illustration attached. 
[scan.svg.zip](https://github.com/mozilla-mobile/fenix/files/3286753/scan.svg.zip)

**Comment by vladikoff** [comment]
@ryanfeeley Thanks!

**Comment by ekager** [comment]
@ryanfeeley are these updated mocks? Do you have an invision link you could share with me for some sizing? Currently we are hiding the scan/camera setting when the device doesn't have a camera available. How will these mocks deal with that case?

**Comment by ryanfeeley** [comment]
@ekager I'm working on un-descoping the Invision doc but the "Use email instead" is intended for users without a camera. It goes to the Sync email-first screen (which precedes login or registration).

**Comment by ekager** [comment]
@ryanfeeley , sorry I'm not sure I 100% understand. You mean users without a camera wouldn't even see this screen? It would just put them right to email sign in?

**Comment by vesta0** [comment]
@mheubusch FYI

**Comment by ekager** [comment]
Closing in preference to #3772 with more information
