### ISSUE TITLE
FNX3-16878 ⁃ Dead end on "Connected to Sync"

### ISSUE THREAD

**Issue by vladikoff** [mozilla-mobile/fenix#3240]
cc @grigoryk 

<img src=https://user-images.githubusercontent.com/128755/59068839-58000380-8883-11e9-8ba6-abc221ae02cc.png width=300 />

**Comment by vladikoff** [comment]
back button also goes back in the form 

<img src=https://user-images.githubusercontent.com/128755/59068872-78c85900-8883-11e9-87a6-254c7652982a.png width=400 />

**Comment by grigoryk** [comment]
@boek we talked about automatically closing this flow on success. What do you think? For this, and other types of issues (like removing the kebab), we'll probably need a custom custom tabs activity.

**Comment by sblatz** [comment]
@grigoryk when a user hits this "You are now ready to use sync" screen, do we get a callback on the Fenix side?

**Comment by boek** [comment]
@grigoryk @vladikoff @vesta0  I spent some time trying to auto-close this on success but it looks like it will require a significant amount of work that won't be landed in time for code freeze.

**Comment by vesta0** [comment]
Thanks For investigating @boek. Will add this to the next sprint.

**Comment by sv-ohorvath** [comment]
Can't verify on Android 5& 6 devices for now because of: https://github.com/mozilla-mobile/fenix/issues/3997. I'll leave this here until the crash is fixed.
Otherwise, working fine on HTC10 (Android 8), Galaxy S8 (Android 9)

**Comment by sv-ohorvath** [comment]
Also verified on HTC Desire 820 (Android 6.0.1). This can be closed now.
