### ISSUE TITLE
FNX3-16880 ⁃ [Bug] Settings sync warning is not vertically centered

### ISSUE THREAD

**Issue by vladikoff** [mozilla-mobile/fenix#3242]
![image](https://user-images.githubusercontent.com/128755/59069533-6ea75a00-8885-11e9-95c4-a6991530f4ea.png)

**Comment by sblatz** [comment]
Filed an [ac issue](https://github.com/mozilla-mobile/android-components/issues/3837) for this

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **Nightly Build #13100629 from 6/11** using the following devices:
• Google Pixel 3a XL (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

![rsz_screenshot_20191106-105030](https://user-images.githubusercontent.com/51314259/68283432-35695500-0084-11ea-8915-0f8b57ab1a83.png)
