### ISSUE TITLE
[Bug] No yellow warning in the meatball menu after FxA password reset

### ISSUE THREAD

**Issue by vladikoff** [mozilla-mobile/fenix#3243]
cc @grigoryk 

This should have a yellow dot if Sync is failing to sync.

![image](https://user-images.githubusercontent.com/128755/59069572-9991ae00-8885-11e9-9cb8-740f49cc94bf.png)

**Comment by jonalmeida** [comment]
That [feature](https://github.com/mozilla-mobile/android-components/pull/3253) hasn't (won't?) land for MVP, but @vesta0 might be able to re-call that decision.

**Comment by sblatz** [comment]
Dup of https://github.com/mozilla-mobile/fenix/issues/2793
