### ISSUE TITLE
FNX3-16882 ⁃ [UX] Replace @ icon with the new head profile icon

### ISSUE THREAD

**Issue by vladikoff** [mozilla-mobile/fenix#3244]
![image](https://user-images.githubusercontent.com/128755/59069632-cba31000-8885-11e9-8d12-2bd3a1958c8c.png)

cc @grigoryk @ryanfeeley

**Comment by grigoryk** [comment]
Do we have that icon in the codebase already?

**Comment by ryanfeeley** [comment]
@grigoryk If not, here are all of them (different states) 
[Avatars.zip](https://github.com/mozilla-mobile/fenix/files/3272777/Avatars.zip)

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on on the latest Fenix build (#11790617 from 28/6) using the following devices:

• Google Pixel 3XL (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7.0)

►Screenshot from Google Pixel 3XL
![Screenshot_20190628-104133](https://user-images.githubusercontent.com/51314259/60326193-d555fa00-9991-11e9-8cf5-0f61312037bd.png)
