### ISSUE TITLE
[sync] Disabled checkboxes for datatypes should reflect true state of account level setting

### ISSUE THREAD

**Issue by vladikoff** [mozilla-mobile/fenix#3245]
Disabled checkboxes for datatypes should reflect true state of account level setting

![image](https://user-images.githubusercontent.com/128755/59069770-30f70100-8886-11e9-8438-3b070002fe60.png)

cc @grigoryk @ryanfeeley

**Comment by ekager** [comment]
Probably part of #5450 ?

**Comment by vladikoff** [comment]
Yes! ⛳️

**Comment by ryanfeeley** [comment]
Yeah, what is the latest here? Last I checked we couldn't let you choose what you're syncing, or even show you what you were syncing, only that what you *could* be syncing was limited to bookmarks and history.

**Comment by kbrosnan** [comment]
This looks to be fixed.
