### ISSUE TITLE
[Bug] Fenix performance test variant no longer works with `geckodriver` and/or `browsertime`

### ISSUE THREAD

**Issue by ncalexan** [mozilla-mobile/fenix#3247]
## Steps to reproduce
1. Install Fenix performance testing variant from

https://index.taskcluster.net/v1/task/project.mobile.fenix.v2.performance-test.latest.arm/artifacts/public/target.apk

1. Invoke `adb shell am start -W -n org.mozilla.fenix.performancetest/org.mozilla.fenix.browser.BrowserPerformanceTestActivity -d https://mozilla.org --es args -marionette\\ -profile\\ /mnt/sdcard/geckodriver-profile`

### Expected behavior
https://mozilla.org is displayed.

### Actual behavior
Gecko starts but https://mozilla.org is neither loaded nor displayed.  I determined this by trying to connect the remote debugger to Fenix.  It connects (so Gecko is running in some way) but only to the hidden window, not to an actual `geckoview.xul` window.  I imagine this is because the `GeckoSession` handling is evolving, and this entrypoint is no longer creating a default session.

**Comment by bifleming** [comment]
@ncalexan is this fix critical for MVP?

**Comment by ncalexan** [comment]
> @ncalexan is this fix critical for MVP?

I think so, 'cuz otherwise we have limited ability to run certain types of performance tests.  I don't actually understand how Raptor is targeting Fenix after these changes; I'll try to dig into that.

**Comment by kbrosnan** [comment]
@mcomella @mcarare should we keep this issue open?

**Comment by ncalexan** [comment]
Presumably note -- perf team must have some solution.
