### ISSUE TITLE
FNX3-16885 ⁃ [Bug] "Remove Account" doesn't do anything

### ISSUE THREAD

**Issue by mhammond** [mozilla-mobile/fenix#3249]
## Steps to reproduce
* Sign in to an account, quit fenix
* On another device delete the account.
* Restart Fenix, visit settings. It tells you to reconnect. On the "Reconnect to Sync" view press "Remove Account"

### Expected behavior
* Fenix returns to the "not signed in" state

### Actual behavior
* Fenix remains in the "Reconnect to resume syncing" state.

**Comment by bifleming** [comment]
@grigoryk can you please look at this one? not sure if it's on teh a-s side or Fenix side.

**Comment by sv-ohorvath** [comment]
It works now (the 6/12 nightly build) but the behavior is different than expected: https://github.com/mozilla-mobile/fenix/issues/3381
