### ISSUE TITLE
[Bug] App intent for Wikipedia appears on every tapped page

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/fenix#3250]
## Steps to reproduce
1. Install Wikipedia app
1. Visit any wikipedia article
1. tap any wikipedia article link
1. Fenix asks whether to open in Wikipedia or Fenix
1. Tap away onto page content
1. tap any wkipedia link

### Expected behavior
I go to the page without a prompt.

### Actual behavior
I get a prompt to choose between Wikipedia and Fenix.

### Device information
* Android device: pixel 2
* Fenix version: latest from play store

**Comment by sblatz** [comment]
Dup of https://github.com/mozilla-mobile/fenix/issues/3256
