### ISSUE TITLE
FNX3-16888 ⁃ [Bug] Cannot type in the search bar with shortcuts

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#3251]
## Steps to reproduce
1. Tap the search bar, tap shortcuts.
1. Select a different search engine. Type something.
    1. Expected behavior
Can search using the search shortcut.
    1. Actual behavior
Cannot type in anything.

### Device information
* Android device: Pixel, Nexus 5
* Fenix version: 6/7

**Comment by sblatz** [comment]
I believe this is an MVP blocker. May be due to edit mode changes here: https://github.com/mozilla-mobile/fenix/pull/2908

**Comment by softvision-miralobontiu** [comment]
Verified as fixed on the latest build 1.0.1923 (#11590615), with Samsung Galaxy S8 (Android 9), and Motorola Nexus 6 (Android 7.1.1).
