### ISSUE TITLE
FNX3-16889 ⁃ [Bug] Reader mode appearance buttons are not visible in PB

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#3252]
## Steps to reproduce
1. Switch to Private Browsing. Open an article on Wikipedia.
1. Switch to reader mode, open the Appearance menu.
    1. Expected behavior
Appearance customization buttons are visible.
    1. Actual behavior
The buttons are not visible.
![Screenshot](https://user-images.githubusercontent.com/4037709/59090104-7d891d80-8914-11e9-91dd-133623ad75d7.png)UNITO-UNDERSCORE!20190607-110518!

### Device information
* Android device: Pixel (Android 9), Nexus 5 (Android 6)
* Fenix version: 6/7

**Comment by sblatz** [comment]
@AmyYLee to provide colors for this

**Comment by sblatz** [comment]
@sv-ohorvath are you able to reproduce this on master? I tested on a pixel 3 and a galaxy s9 and can reproduce on only nightly but not master.

**Comment by kbrosnan** [comment]
Are you on the dark theme? This seems to require the light theme. I can reproduce with a build from master using the light theme but not the dark. @sblatz

**Comment by sv-ohorvath** [comment]
That's right, sorry I missed that detail. You need to be using the light theme.

**Comment by AmyYLee** [comment]
This is the correct colouring for Dark theme
#AB71FF - For purple highlight ring - this should be consistent across Fenix for dark theme and also highlighted text ("Serif").
Also noted here that the minus sign (-) should be the same width as the "+" sign. 

Thanks

<img width="563" alt="Screen Shot 2019-06-07 at 5 09 23 PM" src="https://user-images.githubusercontent.com/5992746/59205044-f33cf580-8b6f-11e9-8f1b-0b9352276c35.png">

**Comment by csadilek** [comment]
Fix to make the buttons visible and apply the new color landed in https://github.com/mozilla-mobile/fenix/pull/3362

**Comment by softvision-miralobontiu** [comment]
Verified that the appearance buttons are visible in PB on the latest build 1.0.1924 (#11630619) with Samsung Galaxy A 6 (Android 7.1.1), Google Pixel 3 (Android 9), and Huawei P9 Lite (Android 6).
