### ISSUE TITLE
[Bug] After closing a crashed tab, the other freeze (device specific)

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#3254]
## Steps to reproduce
1. Open 2 or more tabs.
1. In one tab go to about:crashcontent
1. Close the crashed tab from the crash reporter.
1. Tap other tabs from the homescreen.
    1. Expected behavior
Tabs are loaded.
    1. Actual behavior
The other tabs freeze until you switch views (tap the search bar, minimize/restore the app).
[logcat.txt](https://github.com/mozilla-mobile/fenix/files/3265678/logcat.txt)

### Device information
* Android device: Nexus 5 (Android 6), HTC Desire 820 (Android 6.0.1)
*Not reproducing on: P9 Lite (Android 6.0), Samsung Galaxy Tab A 6 (Android 5.1.1), Galaxy Note 8 (Android 9)
* Fenix version: 6/7

**Comment by sv-ohorvath** [comment]
See also: https://github.com/mozilla-mobile/fenix/issues/3257

**Comment by bifleming** [comment]
@vesta0 device specific. Haven't been able to reproduce. Still a blocker?

**Comment by vesta0** [comment]
@sv-ohorvath are you still able to reproduce this bug?

**Comment by sv-ohorvath** [comment]
This was caused by #3257 which is now fixed by #3358. So it's no longer reproducible. Closing.
