### ISSUE TITLE
FNX3-16891 ⁃ [Bug] Crash when opening youtube.com in PB, after opening youtube in normal browsing

### ISSUE THREAD

**Issue by softvision-miralobontiu** [mozilla-mobile/fenix#3255]
## Steps to reproduce
1. Make sure there is no tab opened.
1. Open youtube.com in normal browsing.
1. Open youtube.com in private browsing.

### Expected behavior
Youtube.com should load.

### Actual behavior
App crashes. 100% reproducible.

### Device information
* Android device: Samsung Galaxy Tab A6 (Android 5.1.1)
* Fenix version: 1.0.1923 (#11580610)

[logcat.txt](https://github.com/mozilla-mobile/fenix/files/3265676/logcat.txt)

![youtube](https://user-images.githubusercontent.com/40694158/59101574-12e6da80-8932-11e9-8fb9-549b4274a4a3.gif)

**Comment by ekager** [comment]
Probably related: I can reproduce this bug and on a pixel 3 when I first navigate to youtube.com in normal browsing, I don't see any popup and am immediately launched to the youtube app with no prompt.

**Comment by kbrosnan** [comment]
@ekager  That is semi-expected behavior. Fixing defining the behavior is #3256

**Comment by kbrosnan** [comment]
Sentry issue: [FENIX-1HK](https://sentry.prod.mozaws.net/operations/fenix/issues/5874306/)

**Comment by vesta0** [comment]
STR:

1- Open youtube.com in private browsing
2- Tap "open" on the "open in app" prompt.
3- Go back to Fenix and type youtube.com in the nav bar again
4- Fenix crashes

**Comment by softvision-miralobontiu** [comment]
Verified as fixed on the latest build 1.0.1924 (#11640609), with Samsung Galaxy Tab S3 (Android 8), and Huawei P9 Lite (Android 6).
