### ISSUE TITLE
[Bug] Closing a crashed tab, the "Open in" dialog is displayed (device specific)

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#3257]
## Steps to reproduce
1. Open 2 or more tabs.
1. In one tab go to Pinterest (mostly reproducible with this one)
1. In the same tab, go to about:crashcontent.
1. On the crash reporter, select Close tab. Observe the homescreen.
    1. Expected behavior
The homescreen with the other tabs are displayed
    1. Actual behavior
The "Open with" dialog is displayed on the homescreen.
    1. Device information

* Android device: Nexus 5 (Android 6), HTC Desire 820 (Android 6.0.1)
*Not reproducing on: P9 Lite (Android 6.0), Samsung Galaxy Tab A 6 (Android 5.1.1), Galaxy Note 8 (Android 9)
* Fenix version: 6/7

**Comment by bifleming** [comment]
Can we please re-test? Can't currently reproduce in Master. Not sure if fix for 1809 was in the build that experienced this. @sv-ohorvath

**Comment by sv-ohorvath** [comment]
I can still reproduce it on the 6/8 and 6/10 (debug) builds.
You need to crash the tab before the "open with" dialog appears on the tab you are loading: type pinterest.com/reddit/any webpage of an app you have installed and press go, and before the page loads, type in the about:crashcontent text. 
Then, on the homescreen, the "open with" dialog will show up for the last active tab restored: this also has to be one of the pages that trigger the "open with" dialog (see #3058)

**Comment by sv-ohorvath** [comment]
Not reproducing, this was fixed by #3358. Closing.
