### ISSUE TITLE
[Bug] Cannot enter text in search bar when using search shortcuts

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/fenix#3265]
## Steps to reproduce
1. Clear app data (to ensure a clean state for the default search engine).
1. Click search bar.
1. Click shortcuts, change engine to DDG.
1. Try to type something.

### Expected behavior
You see your entered text in the search bar.

### Actual behavior
You see the text being removed immediately after it shows up in the search bar.

### Device information
* Android device: Android 9 (Pixel 2)
* Fenix version: 7368a95d

**Comment by sblatz** [comment]
Dup of https://github.com/mozilla-mobile/fenix/issues/3251
