### ISSUE TITLE
[Collections] "Select collection" header is cut off before animating in

### ISSUE THREAD

**Issue by AmyYLee** [mozilla-mobile/fenix#3266]
"Select collection" header is cut off before animating in. See video for reference. 
Same thing happens when you go to 3-dot menu in collections and select "Rename collection".

Expected: Header is fully visible on loading of "Save to collection" screen.

https://cl.ly/47d2afd0e0c8

**Comment by sblatz** [comment]
Setting to p5 as it's not applicable to new design. Will close once we commit to it.

**Comment by NotWoods** [comment]
Closing since the header no longer animates
