### ISSUE TITLE
FNX3-16902 ⁃ [Bug] favicons should have smaller corner radius

### ISSUE THREAD

**Issue by myakura** [mozilla-mobile/fenix#3268]
## Steps to reproduce
1. open sites
1. look at the selected tab in the "open tabs" section in the home view

### Expected behavior
favicons have slightly smaller corner radius than the ones of outer box so that outer borders or inner negative space do not make thicker edges.

I cannot explain it well... these article should help understanding what I mean:

* Public Service Announcement: Careful With Your Nested Border-Radii | CSS-Tricks
https://css-tricks.com/public-service-announcement-careful-with-your-nested-border-radii/	
* Getting Inner Border Radius Just Right - Joshua Hibbert
https://joshnh.com/weblog/getting-inner-border-radius-just-right/

### Actual behavior
![screenshot](https://user-images.githubusercontent.com/413984/59124594-15c9e580-899b-11e9-99c7-933abd6959af.png)

it seems favicons have the same or larger corner radius.

### Device information
* Android device: Xiaomi Mi A1
* Fenix version: 1.0.1923

**Comment by ekager** [comment]
I agree this looks a bit strange. For reference here I have made it `favIconBorderRadiusInPx` cut in half to 4.

![127877](https://user-images.githubusercontent.com/25442310/59139299-23ee1680-8947-11e9-8487-fe83421566c8.png)

**Comment by myakura** [comment]
@ekager that looks great!

**Comment by mheubusch** [comment]
@AmyYLee can you review and approve this approach? If you are ok with it can you remove the Needs UX label and add the Ready for Eng label?

**Comment by AmyYLee** [comment]
> @AmyYLee can you review and approve this approach? If you are ok with it can you remove the Needs UX label and add the Ready for Eng label?

This looks good to me. @mheubusch
