### ISSUE TITLE
Save Address form Data

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/fenix#3277]
## User Story
* As a user, I want to have the option to save basic address data that I input on a web form, so I can re-use it later. 

## What
* [ ] GV work to expose address forms, will build off of #5542 login saving
* [ ] Include Addresses in doorhanger that will be created for #5542 login doorhanger

### Acceptance Criteria
* The browser will save my name as I enter it on a form, for later retrieval
* The browser will save the name of my organization as I enter it on a form, like a billing form, for later retrieval 
* The browser will save my address as I enter it on a form, like a billing form, for later retrieval 
* The browser will save my email address as I enter it on a form, like a billing form, for later retrieval
* The browser will save my phone number I enter it on a form, like a billing form, for later retrieval

**Comment by yoasif** [comment]
Is this the same as autofill on desktop? Will this be synced to autofill on desktop?

**Comment by sblatz** [comment]
We need a spike for this to determine:
- What Gecko desktop is doing (and align with it potentially in AC) based on how much extra work this is (let's make sure @vesta0 is okay with that time commitment)
- Sync up with GV to determine workload based on how item 1 goes.
- Touch base with AS to make sure they have a system for users who don't sync AND for sync users

**Comment by liuche** [comment]
Filed spike: #5492

**Comment by madb1lly** [comment]
Hi all,
I think some things are implemented but others aren't yet.
Cheers 🙂

**Comment by madb1lly** [comment]
Hi @gabrielluong,
I see you've raised a few issues for address form data. This Meta has been auto-closed, but should it be reopened as a catchall for this topic? Or is there another meta to follow now?
Cheers :)
