### ISSUE TITLE
FNX3-16907 ⁃ [Bug] Settings do not display correct content

### ISSUE THREAD

**Issue by mheubusch** [mozilla-mobile/fenix#3278]
## Steps to reproduce
open settings

### Expected behavior
settings match design comps
Should look like this:

![](https://user-images.githubusercontent.com/20115914/59135282-ff446f80-8943-11e9-9d3b-15bb163a120b.png)
Main Settings panel - 

* Second section should be labeled Privacy, not Advanced 
* Data choices should be Data collection
* :information_source: Privacy Notice should be Privacy notice (no icon, lower case n)
* Your rights should not appear on the panel - it is accessed via the Help link)
_Note that Delete browsing data should persist in the app - I will have the design comps updated to reflect this_
![](https://user-images.githubusercontent.com/20115914/59138267-cad7b000-8951-11e9-83ef-93cf7b217313.png)
Search settings should have the default setting, Google, at the top of the list.  All others can be alpha or random after that. 
![](https://user-images.githubusercontent.com/20115914/59138274-d32feb00-8951-11e9-9d62-d17909d06a15.png)

Crash reporting is no longer in this panel and I will get updated comps, but Telemetry label should be replaced with heading and description for Usage and technical data
![](https://user-images.githubusercontent.com/20115914/59138278-d6c37200-8951-11e9-83f1-d533798b998c.png)
Permissions panel should have heading Permissions between the exceptions section and the permission type

### Actual behavior
settings don't match design comps

### Device information
* Android device: Pixel 3
* Fenix version: 1.0.1923 #11581437

**Comment by kbrosnan** [comment]
The crash one was hard/impossible to implement see #1264 and #1003#issuecomment-478106992

**Comment by kbrosnan** [comment]
Data choices -> Data collection is part of #2273

**Comment by ekager** [comment]
Could you be more specific about what this bug is about? Is it just about data collection settings? 

For accessibility settings - you have to toggle "Automatic Font Sizing" off to see that text scaling setting.

**Comment by boek** [comment]
@vesta0 @mheubusch We can't change strings anymore due to string freeze. How do you want to move forward with this for the MVP?

**Comment by mheubusch** [comment]
@boek @vesta0 The only issue that may be critical is the labeling of Telemetry vs what we have  in the Data collection panel. I am meeting with legal in an hour to discuss. Will also reach out to Delphine to find out the earliest we can update strings after June 24.

**Comment by mheubusch** [comment]
Per a conversation with legal, these are P1 but not MVP blocking issues. I will update the labels and coordinate with Delphine to find out the soonest date we can do this.

**Comment by boek** [comment]
@mheubusch I did everything I could minus the string changes for now

**Comment by mheubusch** [comment]
Making a note that I have let Joni Chen know that when this change lands, SUMO will need to update their description of how to turn off data collection to read: Firefox Preview: Tap the menu button (three dots) at the top of the screen. Tap Settings, then select Data collection. On the next screen, toggle the switch next to Usage and technical data to turn it off or on. 
![Screenshot_20190718-102907](https://user-images.githubusercontent.com/20115914/61470986-99d29e00-a947-11e9-9038-50a0ddb3120e.png)

**Comment by SeburoSUMO** [comment]
Thank you for including SUMO in this work.  I will start drafting the change to the KB articles, but so that we can land them in a timely fashion, please can we have a weeks notice of this going to land (please drop me a note on Slack).

**Comment by softvision-miralobontiu** [comment]
So, on the latest Nightly build (190724 #12050609) on Samsung Galaxy Tab A6 (Android 5.1.1), the settings look like this:

![settings1](https://user-images.githubusercontent.com/40694158/61791555-fb50ac00-ae22-11e9-9726-d98abbba9b09.png)

![settings2](https://user-images.githubusercontent.com/40694158/61791556-fb50ac00-ae22-11e9-9c5e-af235a4de767.png)

Data collection look like this:
![datacollection](https://user-images.githubusercontent.com/40694158/61791552-fb50ac00-ae22-11e9-81d1-bbe3a1dedbc5.png)

Search engine like this:
![searchengine](https://user-images.githubusercontent.com/40694158/61791553-fb50ac00-ae22-11e9-83c7-f4898565de20.png)

Site permissions like this:
![sitepermission](https://user-images.githubusercontent.com/40694158/61791557-fbe94280-ae22-11e9-9927-e4fa52dcedad.png)


The only difference from Comment 0 is at "Data collection", where "Crash reporter" info and toggle are missing. @mheubusch is this expected?
