### ISSUE TITLE
FNX3-16909 ⁃ [Bug] Strange Behavior, Crashes when restoring collections

### ISSUE THREAD

**Issue by ekager** [mozilla-mobile/fenix#3280]
Currently we are restoring collections as sessions but this can lead to conflicting session IDs, multiple sessions being selected at once, and awesome bar crashes. We should consider reverting this change. Alternatively we could check if the session we are trying to restore already exists. 

## Steps to reproduce
1. Restore collections with clashing session ids (same session restored multiple times)

### Actual behavior
Seeing crashes and strange behavior

### Device information
* Android device: ?
* Fenix version: ?

**Comment by csadilek** [comment]
See also: https://github.com/mozilla-mobile/fenix/issues/3313

**Comment by sv-ohorvath** [comment]
Verified as fixed on the 6/11 build. Devices: Pixel (Android 9), Nexus 5 (Android 6)
