### ISSUE TITLE
[UX] Customizable QAB menu

### ISSUE THREAD

**Issue by rmbq** [mozilla-mobile/fenix#3282]
### Why/User Benefit/User Problem
As a user I'd like to a have a customizable menu, via settings, to add/remove icons next to private navigation icon on the home page. something like right click -> customize on top bar in firefox for desktop.
The goal is to have a rapid access to frequently used sections (bookmark, history, etc...) without using 3 dot menu (or 3 dot menu -> library) which is slow.

**Comment by vesta0** [comment]
@mheubusch @lime124 what do you think about QAB being customizable?

**Comment by lime124** [comment]
@vesta0 i linked this to #3927 for consideration.

**Comment by ekager** [comment]
We have removed the QAB. Closing
