### ISSUE TITLE
[Bug] Embedded Facebook video does not show on page

### ISSUE THREAD

**Issue by mozillamarcia** [mozilla-mobile/fenix#3285]
## Steps to reproduce
* Load https://www.popsugar.com/family/Viral-Video-Baby-Boy-Talking-His-Dad-46235433
* Observe video does not show

### Expected behavior
* Video is shown. Using latest Fennec nightly I can see the video

### Actual behavior
* Video is not shown

### Device information
* Android device: Pixel 3
* Fenix version: 1.0.1923 (Build #11581819)
![Screenshot](https://user-images.githubusercontent.com/2171777/59149218-c60e0d00-89e0-11e9-8595-a2528dda8a0a.png)UNITO-UNDERSCORE!20190607-214526(1)!

**Comment by mozillamarcia** [comment]
The first attachment is how it is shown in Fennec. This attachment shows the same site loaded in Fenix.
![Screenshot_20190608-113203](https://user-images.githubusercontent.com/2171777/59149255-42a0eb80-89e1-11e9-8487-093d49d4a2a7.png)

**Comment by kbrosnan** [comment]
Does disabling tracking protection in Fenix load the content? Tap on the lock icon and then toggle the tracking protection option (might need to reload the page).

**Comment by mozillamarcia** [comment]
Yes, if I turn off tracking protection the video loads.

**Comment by vesta0** [comment]
Closing this issue as this is currently expected behaviour. Will look into ways of informing user about turning off tracking protection when needed.
