### ISSUE TITLE
Reader mode follows the set theme

### ISSUE THREAD

**Issue by DiegoARL38** [mozilla-mobile/fenix#3289]
### Why/User Benefit/User Problem
It would be nice if the reader mode followed the user-selected theme by default. 

### What/Requirements
* If the user has selected the dark theme for the application, the reader mode automatically uses dark colours.
* If the user has selected the light theme, the reader mode uses light colours.
* If the user has selected one of the variable themes, the reader mode uses the appropriate colours.
* If the user manually sets the colour-scheme for the reader mode, it won't be affected by the application's theme or if it changes.
    1. Acceptance Criteria (how do I know when I’m done?)
Reader mode follows the app's theme unless the user specifies the colour-scheme they prefer.

┆Issue is synchronized with this [Jira Story](https://mozilla-hub.atlassian.net/browse/FNXV2-12013)

**Comment by LongJohn-Silver** [comment]
Since the P2 tag was removed does that mean it has more or less priority?

**Comment by erikw** [comment]
We need this!

If I get it right, it's already fixed for iOS in https://github.com/mozilla-mobile/firefox-ios/issues/4700
