### ISSUE TITLE
Crashes when switched between multiple tabs repeatedly[Bug]

### ISSUE THREAD

**Issue by arps18** [mozilla-mobile/fenix#3294]
![Screenshot](https://user-images.githubusercontent.com/47818179/59158485-7e6aac80-8ad8-11e9-97f9-328f324c2118.png)UNITO-UNDERSCORE!20190609-165757!

### Expected Behaviour
Should have been switched the tabs without crash

### Actual behavior
It crashes when the tabs are switched fast

### Device information
Mi A1

* Android device: 9
* Fenix version: 1.0.1923

**Comment by sblatz** [comment]
I am unable to reproduce this on my galaxy s9. @arps18 are you able to give a demo video of this happening? :)

**Comment by arps18** [comment]
> I am unable to reproduce this on my galaxy s9. @arps18 are you able to give a demo video of this happening? :)

Actually the crash is occuring occassionaly now i.e 1 in 10/12 times so.If possible i will surely send the video.But just try to open a like 5-6 tabs and rapidly switch between them.

**Comment by sblatz** [comment]
@arps18 I appreciate that. Are you also able to provide a log if you can reproduce as well as the date of the build? Should be in the "about fenix" setting.

**Comment by arps18** [comment]
@sblatz I am extremly sorry I didn't got you.

**Comment by arps18** [comment]
> I am unable to reproduce this on my galaxy s9. @arps18 are you able to give a demo video of this happening? :)

Also i am now facing another issue i.e once you switch between the tabs about sometimes and check another app and when you return all your collection tabs are shown blank.

**Comment by arps18** [comment]
> > I am unable to reproduce this on my galaxy s9. @arps18 are you able to give a demo video of this happening? :)
> 
> Also i am now facing another issue i.e once you switch between the tabs about sometimes and check another app and when you return all your collection tabs are shown blank.

![image](https://user-images.githubusercontent.com/47818179/59407237-401e0780-8dce-11e9-80ee-1becd6045045.png)

**Comment by kbrosnan** [comment]
The last two comments are about a separate issue, sounds like #3474. 

If you have a computer and some free time it would be a great help to get the logcat debugging information. The steps to get the information we need is at https://github.com/mozilla-mobile/fenix/wiki/Logging-Crash-Information

If you have any questions or run into any problems with the steps reply to this issue.

**Comment by ekager** [comment]
I think this was the animation crash. I'm going to close because there's no more information. We already have a bug for the about:blank tabs.
