### ISSUE TITLE
Unable to search the tab once the app crashes[Bug]

### ISSUE THREAD

**Issue by arps18** [mozilla-mobile/fenix#3295]
### Expected behavior
The search bar isn't allowing to search the keywords

### Actual behavior
The search engine should have enable the search

### Device information
Mi A1

* Android device: 9
* Fenix version: 1.0.1923

**Comment by sblatz** [comment]
If I'm understanding this correctly, it should be fixed by https://github.com/mozilla-mobile/fenix/pull/3271

Are you able to reproduce on the latest nightly?

**Comment by sblatz** [comment]
I'm going to close this as fixed. Please re-open if you're still experiencing this, @arps18!

**Comment by arps18** [comment]
> I'm going to close this as fixed. Please re-open if you're still experiencing this, @arps18!

yaa the issue seems to have sorted. Glad to have assist like you!
