### ISSUE TITLE
[Bug] Text Options for Reader Mode in Private Browsing need new color

### ISSUE THREAD

**Issue by malgamves** [mozilla-mobile/fenix#3297]
## Steps to reproduce
* Open Private browsing
* Select any website with text information
* Turn on reader mode

### Expected behavior
Colour of options is supposed to be lighter to make text visible
![Screenshot](https://user-images.githubusercontent.com/25641936/59158647-e9b57e00-8ada-11e9-9353-d54859b5f51b.png)UNITO-UNDERSCORE!20190609-171821!
![Screenshot](https://user-images.githubusercontent.com/25641936/59158651-f1752280-8ada-11e9-8e85-f9a5849deead.png)UNITO-UNDERSCORE!20190609-171903!

### Actual behavior
Colour of text options matches background and is not visible

### Device information
* Android device: Nokia 8.1, Android 9
* Fenix version: Fenix 1.0.1923 (Build #11590616 :lizard: 68.0-20190604110028)

**Comment by vesta0** [comment]
Thanks for filing! Will be addressed in #3252
