### ISSUE TITLE
[Bug] Images and Videos aren’t getting opened in Facebook.

### ISSUE THREAD

**Issue by pb-10** [mozilla-mobile/fenix#3300]
## Steps to reproduce:
Opened private browsing. Went to Facebook.com and tried to open images and videos.

### Device information
* Android device: Mi A1, Android Version 9
* Fenix version: 1.0.1923

**Comment by vesta0** [comment]
@pb-10 I can load images and play videos on facebook as expected. If you are still experiencing this bug, would you please provide more detail steps to reproduce it?

**Comment by sblatz** [comment]
@pb-10 any update on this? :)

**Comment by sblatz** [comment]
I'm going to close this as we're not able to reproduce. @pb-10 please re-open if you're still experiencing!

**Comment by softvision-miralobontiu** [comment]
I was not able to reproduce the issue on the latest Nightly build from 3/11 with Xiaomi Redmi Note 8T (Android 9). 
Removing the needs:STR label.
