### ISSUE TITLE
[Bug]Dark mode  when set to follow device theme doesn't work

### ISSUE THREAD

**Issue by DenDeMello** [mozilla-mobile/fenix#3302]
## Steps to reproduce
Settings ~~> Theme~~ > Follow device theme

### Expected behavior
Should go dark when system dark mode is enabled and vice versa.

### Actual behavior
Nothing happens

### Device information
Motorola G5 Plus
LineageOS 16.0

* Android device: 9
* Fenix version: 1.0.1923

**Comment by ekager** [comment]
Unfortunately follow device theme passes the management of light/dark theme to the system so I'm not sure what we can do here. Do you have battery saver mode available on your device?

**Comment by colintheshots** [comment]
Follow device theme depends upon the Android OS functionality provided by the very latest Android versions. I don't think anyone can promise to make it work for LineageOS.

**Comment by sblatz** [comment]
Closing this as it's not a Fenix issue. Please re-open if I'm mistaken :)
