### ISSUE TITLE
URL containing spaces are treated as search terms

### ISSUE THREAD

**Issue by glandium** [mozilla-mobile/fenix#3306]
## Steps to reproduce
* Open the search/address bar
* Type "http://example.com/foo bar"

### Expected behavior
* The page "http://example.com/foo bar" is opened

### Actual behavior
* A Google search for "http://example.com/foo bar" is made

You might wonder why the hell one would open an url with spaces in them. Well, originally here's what happened to me: I opened the search/address bar, and used the QR code scanner, to scan a QR code. The url the QR code decoded to contained spaces. So I was brought to a google search rather than what I was supposed to see.

### Device information
* Android device: Nexus 5
* Fenix version: 1.0.1923 (Build #11590615 68.0-20190604110028)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-12029)

**Comment by vesta0** [comment]
@glandium I assume you were expecting http://example.com/foo%20bar ?

**Comment by glandium** [comment]
I guess so, the url I got from the QR code does work if I replace the spaces with %20.

**Comment by colintheshots** [comment]
URLs cannot contain spaces. Spaces can only be URL-encoded as %20. https://www.ietf.org/rfc/rfc1738.txt

**Comment by kbrosnan** [comment]
Firefox, Chrome and Edge on desktop handle `http://example.com/foo bar` doing the %20 escaping for the user. We should add this user convenience

**Comment by ekager** [comment]
Looks like 
"google.com cats" is a search
but google.com/ cats" is treated as a URL.
This is probably something AC would have to implement through the toolbar

**Comment by mobd** [comment]
I might be in the minority but I prefer leaving the behaviour as it is. Right now using duckduckgo if I want to do a reverse image search I can just open an image and add !tineye or !yri to the url and search, there are probably other search queries that work similarly.

**Comment by lilydjwg** [comment]
> You might wonder why the hell one would open an url with spaces in them.

I was searching Wikipedia for X window when I met this issue. The keyword search feature has long gone and I'm relying on autofill to search specific sites without opening the site first (to save time and transmit).

Firefox usually escapes characters for users in the URL bar. The space is the only exception I've found so far.

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813919

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
