### ISSUE TITLE
FNX3-16933 ⁃ Send & Receive Tabs (Send Tab)

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#331]
As a user, I want to send my current tab to other FxA-Connected browsers, so I can access it on all my devices.

### Acceptance Criteria:
~~I can share my tab with other FxA~~Connected browsers on my other devices.

-I can see the option to send tab on the tabs 3 dot menu (on homescreen)

### Dependencies:
FxA [and android component](https://github.com/mozilla-mobile/fenix/issues/92#issuecomment-456951738).

<img src=https://user-images.githubusercontent.com/128755/57334721-8bb60500-70ee-11e9-92fb-bca32133f5ff.png width=200 />

Ref: https://mozilla.invisionapp.com/share/QSR2F8UD4PN#/screens/357470302

cc @grigoryk

**Comment by andreicristianpetcu** [comment]
this has a simple workaround: install fennec. you can share from fenix to fennec and send to device.

**Comment by sv-ohorvath** [comment]
@sblatz Started testing this and found some issues, please review when you can.

**Comment by sblatz** [comment]
I believe @jonalmeida was the one working on this actually

**Comment by sv-ohorvath** [comment]
Since #2887 (the only P1 blocking this) was moved to the Fenix 1.1 backlog, I assume this is not blocked for Beta anymore. No other P1s so I'm closing this.
