### ISSUE TITLE
[Bug] Buggy behavior on swipe to close tabs

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#3311]
## Steps to reproduce
1. Open a few tabs.
1. On the homescreen, swipe to close them one by one.
    1. Expected behavior
Tabs are removed.
    1. Actual behavior
The gray background behind a tab stays displayed longer than it should, until the snackbar disappears.
Some tabs slide back until the snackbar dissapears.
Swiping one tab removes the one beneath, then it re-appears.

![20190610](https://user-images.githubusercontent.com/4037709/59202152-8db72c00-8ba4-11e9-9f2d-a75c78e77211.gif)UNITO-UNDERSCORE!172049!

### Device information
* Android device: HTC 10 (android 8), Pixel (Android 9), Nexus 5 (Android 6)
* Fenix version: 6/8 & 6/10 (debug)

**Comment by ekager** [comment]
Dupe of #3275
