### ISSUE TITLE
FNX3-16937 ⁃ [Bug] Toolbar unresponsive after showing any the system permission dialog with site permissions Android 6

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/fenix#3314]
## Steps to reproduce
1. Go to http://permission.site/
1. Tap on camera.
1. Tap the Allow or Deny  button on the system permission dialog
1. Try to tap on the toolbar.

### Expected behavior
You can interact with the toolbar.

### Actual behavior
The toolbar is not responsive to any interactions

### Device information
* Android device: Nexus 5 Android 6
* Fenix version: Monday 6/10 @ 11:04 AM

**Comment by softvision-miralobontiu** [comment]
Verified as fixed on the latest build 1.0.1924 (#11640609), with Nexus 5 (Android 6), and Huawei P9 Lite (Android 6).
