### ISSUE TITLE
FNX3-16939 ⁃ [Bug] In Fenix settings, device name field should prepopulate with existing name/placeholder

### ISSUE THREAD

**Issue by dianehuang11** [mozilla-mobile/fenix#3317]
STEPS TO REPRODUCE

1. Open Firefox browser on Fenix
1. Navigate to Settings
1. Click on User Name
1. View "device name"

EXPECTED RESULTS

* Default device name should be an unique placeholder (i.e. Ryan's Samsung Galaxy S4)
* If edited, the field should be changed and sync across device list
* If left blank after user modification, placeholder value should re-populate

ACTUAL RESULTS

* Current placeholder name "Fenix Preview"
* On first edit, name field is blank (should be pre-populated)

Screenshot_20190605-152354
![image](https://user-images.githubusercontent.com/28498717/59216674-12e11780-8b8a-11e9-894f-1860831af6fa.png)

Screenshot_20190605-152442
![image](https://user-images.githubusercontent.com/28498717/59216681-17a5cb80-8b8a-11e9-950b-045c0a1d9da3.png)

**Comment by chiragmantri** [comment]
can i work on this issue?

**Comment by softvision-miralobontiu** [comment]
Verified that the "device name" filed cannot remain empty, and a pop-up is displayed informing the user about it.
Tested on the latest Nightly build 190717 (#11980613) with Sony Xperia Z5 Premium (Android 7.1.1), Samsung Galaxy Tab A6 (Android 5.1.1), and HTC 10 (Android 8), and on the latest Nightly build 190717 (#11980614) (aarch64) with Nexus 6P (Android 8.1.0).
![Screenshot_20190717-122650](https://user-images.githubusercontent.com/40694158/61364395-6b44bc80-a88e-11e9-83b2-b073a051f5f0.png)
