### ISSUE TITLE
FNX3-16945 ⁃ Remove open image in tab context menu

### ISSUE THREAD

**Issue by kbrosnan** [mozilla-mobile/fenix#3326]
### Why/User Benefit/User Problem
We want to prevent #2312 from happening.

### What/Requirements
Long pressing on an image does not give an option to open a new tab

### Acceptance Criteria (how do I know when I’m done?)
Visit several image types (PNG, JPEG, WEBP, GIF) and verify that there is not an option to open the image in a new tab.

**Comment by yoasif** [comment]
Fennec has "View Image", which seems to work fine. Chrome also has the Open image in new tab which also works fine. 

Isn't this just hiding a bug by removing a feature?

**Comment by ekager** [comment]
This will not be a long term fix, the root bug requires engine work that will not be completed by MVP so it's being deprioritized. But in the mean time, yes, we want to hide the broken feature.

**Comment by ekager** [comment]
@vesta0 I got the fix for this, should we put it in the board?

**Comment by vesta0** [comment]
Done :)

**Comment by softvision-miralobontiu** [comment]
Verified that long tapping on an image, the context menu triggered doesn't contain "Open image in a new tab" option. The available options are "Save" image" and "Copy image location".
Tested on the latest build 1.0.1924 (#11630619), with Samsung Galaxy Tab A 6 (Android 5.1.1), Google Pixel 3 (Android 9), and Huawei P9 Lite (Android 6).

![Screenshot_20190612-074218](https://user-images.githubusercontent.com/40694158/59348886-fcb98f80-8d20-11e9-87c5-55b833526246.png)
