### ISSUE TITLE
App intent exception for websites

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/fenix#3330]
## User Story
* As a user, I want an website (e.g. youtube.com) to open in Fenix (not launch an external app) but also have the option in the tab context menu to launch the app.

### Acceptance Criteria
* I can open a site in Fenix without launching an external app if there is one
* I have an option to launch the app in the tab context menu
* Tapping on an app deeplink will still directly launch an external app.

**Comment by jhugman** [comment]
This corresponds to [ac#3695][0].

[0]: https://github.com/mozilla-mobile/android-components/issues/3695

**Comment by st3fan** [comment]
I know this is closed but I clarified this ticket by renaming 'http site' to 'website'. To make sure we know this is not about http vs https. I think mozilla-mobile/android-components#3695 already reflects that.

**Comment by nahuhh** [comment]
One piece that is overlooked/missing from the acceptance criteria is:

When you tap-hold on a link: open in private tab, new tab, copy link, share link are available. Should also have an "open in..." menu listing
