### ISSUE TITLE
FNX3-16949 ⁃ [Bug] capitalisation of first letter for hosts in collections list

### ISSUE THREAD

**Issue by cadeyrn** [mozilla-mobile/fenix#3332]
### Steps to reproduce
1. save websites in collection
1. go to Fenix home screen

### Expected behavior
No capitalisation of first letter for hosts in collections list because it doesn't make sense to capitalise the first letter of a host. And in the list of tabs after expanding a collection and in the list of open tabs there is also no capitalisation of hosts, so current behaviour is not consistent.

### Actual behavior
Capitalisation of first letter for hosts in collections list.

![Screenshot](https://user-images.githubusercontent.com/1100614/59257986-652c4200-8c37-11e9-9b29-c8660dd8d9c6.png)UNITO-UNDERSCORE!20190611-105401!

### Device information
* Android device: HTC U11 / Android 8.0
* Fenix version: Fenix revision 4d82c297432e0f86d54e2d3496e0654bbb36a447

**Comment by mheubusch** [comment]
This should be all metadata - the case of text should come from metadata and Firefox Preview should not be altering any  metadata.
