### ISSUE TITLE
FNX3-16950 ⁃ [Bug] There is a "desktop bookmarks" folder even with sync never enabled

### ISSUE THREAD

**Issue by cadeyrn** [mozilla-mobile/fenix#3333]
### Steps to reproduce
1. Start Fenix with on a device where Fenix was never connected to Sync (or delete the app data before starting Fenix to make sure Fenix can't have any desktop bookmarks)
1. Open the bookmarks in your library

### Expected behavior
No folder for desktop bookmarks.

### Actual behavior
There is a folder for desktop bookmarks.

### Device information
* Android device: HTC U11 / Android 8.0
* Fenix version: Fenix revision 4d82c297432e0f86d54e2d3496e0654bbb36a447

**Comment by softvision-miralobontiu** [comment]
Verified as fixed on the latest build 1.0.1924 (#11640609), with Samsung Galaxy Tab S3 (Android 8), and Huawei P9 Lite (Android 6).
