### ISSUE TITLE
FNX3-16951 ⁃ [Bug] alignment of icons in collection cards

### ISSUE THREAD

**Issue by cadeyrn** [mozilla-mobile/fenix#3334]
Please check the alignment of the icons in the collection cards.

![fenix1](https://user-images.githubusercontent.com/1100614/59267757-43d55100-8c4b-11e9-9e0e-c9ce4ee45485.png)

### Device information
* Android device: HTC U11 / Android 8.0
* Fenix version: Fenix revision 4d82c297432e0f86d54e2d3496e0654bbb36a447

**Comment by andreiteslovan** [comment]
I think this should be closed because a fix landed yesterday:
https://github.com/mozilla-mobile/fenix/pull/3382

I forgot to add the closing keywords when committing. @colintheshots

**Comment by sblatz** [comment]
I just checked this and believe it's also fixed. 
<img width="350" alt="image" src="https://user-images.githubusercontent.com/4400286/59937429-44b67180-9407-11e9-87f5-aeb7f12876f3.png">

**Comment by softvision-miralobontiu** [comment]
Verified as fixed on the latest build 1.0.1926 (#11750611), with LG G7 Fit (Android 8.1).
