### ISSUE TITLE
FNX3-16952 ⁃ [Bug] (L10N) save to collection: missing spacing for save button

### ISSUE THREAD

**Issue by cadeyrn** [mozilla-mobile/fenix#3335]
## Steps to reproduce
1. use Fenix in German instead of English
1. save tabs to collection
1. select at least one tab

### Expected behavior
There is some spacing on the right side of the "SAVE" button.

### Actual behavior
Missing spacing. With the English translation there is no problem.

![Screenshot](https://user-images.githubusercontent.com/1100614/59268078-3a98b400-8c4c-11e9-8753-69351383161b.png)UNITO-UNDERSCORE!20190611-131923!

### Device information
* Android device: HTC U11 / Android 8.0
* Fenix version: Fenix revision 4d82c297432e0f86d54e2d3496e0654bbb36a447

**Comment by colintheshots** [comment]
We need a full test run with pseudolocales to catch all cases like this one.

**Comment by mheubusch** [comment]
@vesta0 I am going. to label this as blocked by UX pending resolution of 3355 - where someone did test with pseudolocales and found that this issue appears in several places in the UI. I'd like to solve it holistically in that issue.

**Comment by cadeyrn** [comment]
I'll close this issue because the reported issue is gone, instead #3843 happens.
