### ISSUE TITLE
FNX3-16954 ⁃ (L10N) split "browser_menu_report_issue" in two strings

### ISSUE THREAD

**Issue by cadeyrn** [mozilla-mobile/fenix#3337]
Currently the string "browser_menu_report_issue" is used for the main menu and the quick settings panel. I suggest to use two separate strings to support better translations.

Reason:

There is no problem with the English translation. It's "Report site issue" and it fits in both places. But not with the German translation. With the German translation the string in the main menu reads "Website-Problem m…" and it's totally unclear that "m…" means "melden". You still understand the menu item if it would be only "Website-Problem". But in the quick settings panel there is enough space to show the full "Website-Problem melden". Since the same string is used for both places you can't change the menu item without changing the string in the quick settings panel.

**Comment by cadeyrn** [comment]
@vesta0 Does this issue need an "UX feedback" label or what is needed to get a decision whether this change is wanted or not? :)

**Comment by vesta0** [comment]
@bifleming @mheubusch what is the process for addressing this issue? It seems like currently the German translation of the string "browser_menu_report_issue" is cut off in the main menu but not in the browser panel.

**Comment by cadeyrn** [comment]
@bifleming or @mheubusch There is an open question from August (and the request is even from June) - could you clarify if this should be addressed or if it's a WONTFIX?

**Comment by cadeyrn** [comment]
The AC part of #7157 landed so this is no longer needed.
