### ISSUE TITLE
FNX3-16956 ⁃ Remove AMO/SUMO workaround for GeckoView 68

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/fenix#3341]
For #1134 we're putting in a change to update our user-agent on those sites while we're still on GV 68. This should be removed when we upgrade to GV 69.

**Comment by bifleming** [comment]
@st3fan @cpeterso  is this the solution we want?

**Comment by cpeterso** [comment]
> is this the solution we want?

Yes. This issue asks to remove a temporary workaround that is only needed for "Fenix 68". This issue can be fixed after Fenix updates to GV 69 or later.

**Comment by jonalmeida** [comment]
We can do this now that https://github.com/mozilla-mobile/fenix/pull/4297 has landed!

What needs to be done:
 - Remove the `UserAgentRewriter`.
 - Remove all it's usages.

This is the PR that added the change (which now need to be removed): https://github.com/mozilla-mobile/fenix/pull/3342/

**Comment by jonalmeida** [comment]
For QA:
 - Testing this would be to open addons.mozilla.org and verify that addons _cannot_ be installed on Fenix.

**Comment by sv-ohorvath** [comment]
Verified as fixed on Nightly 190806, GV 69.
