### ISSUE TITLE
FNX3-16961 ⁃ Report Site Issue

### ISSUE THREAD

**Issue by bbinto** [mozilla-mobile/fenix#335]
### Why/User Benefit/User Problem
* As a tester and early adopter, I want to report any site issue I have with the app

### What / Requirements
* Ideally, within the app, a form that a user can submit to report for web compat issue including prep-populated info about their device, OS version etc.
* Easiest is to do what we did for Fennec Nighltly

### Acceptance Criteria (how do I know when I’m done?)
* Report is sent to compat team and can be triaged

Some notes from my meeting with Lucy:
If we want to engage the community, we should have this in the app for milestone 3

* to file bugs (where? separate website)
* test GV
* couple of thousand users
* 2-4 weeks prep time for Lucy's team
* web compat
* Prizes

**Comment by Sdaswani** [comment]
@bbinto for the time being this will point to GH, so we can triage issues, but upon shipment to world @st3fan notes it should point somewhere else.

**Comment by pocmo** [comment]
Like our other apps to https://webcompat.com/ ?

* https://github.com/mozilla-mobile/focus-android/blob/053d29652ff8ba9aae4f18fd6230f651c50ee5d3/app/src/main/java/org/mozilla/focus/fragment/BrowserFragment.kt#L1197-L1203
* https://searchfox.org/mozilla-central/source/browser/extensions/webcompat-reporter/background.js

**Comment by Sdaswani** [comment]
yeah good point @pocmo , @ekager we may as well point to webcompat so the team can test it against GV and get some web compat going.
