### ISSUE TITLE
FNX3-16966 ⁃ Empty state for TP exceptions

### ISSUE THREAD

**Issue by topotropic** [mozilla-mobile/fenix#3360]
### Why/User Benefit/User Problem
When a person taps on "Exeptions" in TP settings, they gets a view with a message telling them that they haven't disabled TP on any sites. We might want to add an educational blurb on how to whitelist a site here.

### What/Requirements
* figure out what message to use here
* allow people to tap on "Exceptions" link even if they haven't any site in the list
* show empty state message

**Comment by vesta0** [comment]
I think this is extremely important. Currently the user has no way of knowing how to add an exception if they haven't happened to try and disable the toggle on a site (which is also somewhat hidden)

**Comment by vesta0** [comment]
@lime124 FYI

**Comment by topotropic** [comment]
@mheubusch could you provide some copy to display on Settings/Tracking Protection/Exceptions when no exceptions are added? Currently it's not possible to go to the  "Exceptions" page when no exceptions are added and it seems broken.

**Comment by mheubusch** [comment]
Exceptions let you disable tracking protection for selected sites. <a href="https://support.mozilla.org/en-US/kb/tracking-protection-firefox-preview">Learn more </a>

Also, we should link  directly to this article from the Help nav under "Settings and preferences" hosted on SUMO

**Comment by lime124** [comment]
@ekager let us know if you need anything else! removing ux labels

**Comment by sv-ohorvath** [comment]
Verified on Fenix  Nightly 190724 Build #12050609.
