### ISSUE TITLE
[Bug] Broken UI after dismissing app link intent chooser

### ISSUE THREAD

**Issue by buttercookie42** [mozilla-mobile/fenix#3361]
## Steps to reproduce
1. Keep #3358 in mind.
1. Click a link leading to a page that triggers an app links intent chooser popup.
1. Dismiss the intent chooser.
3a. Click on  the URL bar.
3b. Try to open the library or the settings menu.

### Expected behavior
3a --> The URL bar goes into editing mode.
3b --> The library/settings menu opens.

### Actual behavior
Nothing happens.
Going to the tab screen and back, or momentarily putting the app into the background (e.g. by opening Android's task switcher) fixes things again, though.

### Device information
* Android device: Moto G4 Play, Android 6.0.1
* Fenix version: 1.0.1924 (11621806, 68.0-20190604110028)

**Comment by ekager** [comment]
@buttercookie42 is this still an issue with the new icon in the Quick Action Sheet to launch the app?

**Comment by kbrosnan** [comment]
I can't reproduce this on nightly using mailto: as the trigger.
