### ISSUE TITLE
FNX3-16968 ⁃ [Bug] Edit bookmarks launches directly to "desktop bookmarks"

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#3364]
We should likely launch to the root "Bookmarks" folder which has unfiled bookmarks as well as desktop bookmarks as the only choices:

### Library -> Bookmarks
![](https://user-images.githubusercontent.com/4400286/59306845-0de79b00-8c52-11e9-85b7-44512d32bf56.png)

### Edit Bookmark
![](https://user-images.githubusercontent.com/4400286/59306874-18099980-8c52-11e9-9fc6-7e4ac8cd9eae.png)

**Comment by sblatz** [comment]
We may need to mess with [this line]( https://github.com/mozilla-mobile/fenix/blob/master/app/src/main/java/org/mozilla/fenix/library/bookmarks/selectfolder/SelectBookmarkFolderFragment.kt#L108). Changing it to mobile, though breaks the `withOptionalDesktopFolders` functionality.

**Comment by AndiAJ** [comment]
Hi, I've bumped into an issue while testing this.
As per the attached video, after trying to edit a Bookmark from Root Bookmarks section (left it there) the "Desktop Bookmarks" gets transformed to "Bookmarks" and only after navigating and coming back from it the name is re-changed to "Desktop Bookmarks".
![2019_06_27_12_49_35](https://user-images.githubusercontent.com/51314259/60257336-efcd9c00-98db-11e9-9c68-13f0f60c9ccc.gif)

**Also, to have a better overview, could you please let us know how should the correct Bookmarks tree look like?**

**Comment by colintheshots** [comment]
It looks like setting the titles onAttach doesn't work when we return from the EditBookmarkFragment. I moved it to onResume and I'm submitting a PR. We need UX feedback on the correct bookmarks tree.

**Comment by softvision-miralobontiu** [comment]
@colin, I'm not sure how the correct bookmark tree should look like. 
On the latest Nightly build (#11840608), the Bookmarks section has no desktop folders:

![Screenshot_20190703-113256_Firefox Preview](https://user-images.githubusercontent.com/40694158/60576727-9e635800-9d86-11e9-8a7a-bae7373a4086.jpg)

Is this expected?
I will remove the QA needed flag until I'm sure.

**Comment by softvision-miralobontiu** [comment]
Verified that editing bookmarks don't launch "Desktop bookmarks".
Tested on the latest Nightly build 190710 (#11910617) with Samsung Galaxy Tab A6 (Android 5.1.1), Huawei Honor 8 (Android 7), and HTC 10 (Android 8).
