### ISSUE TITLE
Merge the codebases of BookmarkFragment and EditBookmarkFragment

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#3366]
Currently these codebases are largely the same with _lots_ of code duplication. Because of this, we have issues like #2252 being closed while #3203 isn't. This will likely cause more issues in the future if we don't merge these to use a singular component. The same goes for their usage of adapters.

**Comment by sblatz** [comment]
@NotWoods is this still something you're working on? :) I know you've been doing a lot of work to abstract out portions of bookmarks.

**Comment by NotWoods** [comment]
I've been putting in PRs related to this but I'm not sure when we should close the issue. Feel free to unassign me.
