### ISSUE TITLE
[Bug]The Search text not centered on Search field

### ISSUE THREAD

**Issue by sv-sdeiac** [mozilla-mobile/fenix#3374]
## Steps to reproduce
1. Open Firefox preview;
1. Tap on the search field bar;
1. Start to write something.

### Expected behavior
The text and the clear button are centered on the search field.

### Actual behavior
The text and the clear button are not centered.

### Device information
* Android device: Nokia 6 (Android 7.1.1) and Xiaomi Mi 8 Lite (Android 8.1)
* Fenix version: 1.0.1924

**Comment by vdrares** [comment]
Looking into it.

**Comment by sv-ohorvath** [comment]
duplicate: #3138
