### ISSUE TITLE
[Bug] Privacy Notice icon is missing

### ISSUE THREAD

**Issue by softvision-miralobontiu** [mozilla-mobile/fenix#3376]
### Steps to reproduce
Go to Settings and observe the "Privacy Notice" icon.

### Expected behavior
The icon should be displayed in front of the text.

### Actual behavior
The icon is missing.

### Device information
* Android device: Motorola Nexus 6 (Android 7.1.1), Huawei P9 Lite (Android 6), OnePlus 5T (Android 9)
* Fenix version: 1.0.1924 (#11630619)

![Screenshot](https://user-images.githubusercontent.com/40694158/59336454-47c6a900-8d07-11e9-8381-ff222645569b.png)UNITO-UNDERSCORE!20190612-113328!

**Comment by bifleming** [comment]
As intended.
