### ISSUE TITLE
[Bug]paste/select all dialog not showing

### ISSUE THREAD

**Issue by Hubfront** [mozilla-mobile/fenix#3378]
## Steps to reproduce
Try to paste data into an input/user name/passwords field on web.de

### Expected behavior
Should show dialog for select all/paste/copy

### Actual behavior
Nothing happens (but works as expected on computerbase.de. Fennec works on both sites as expected).

### Device information
Samsung S9 plus

* Android device: ?
* Fenix version: 1.0.1924 (Build #11630620 :lizard: 68.0-20190604110028)

**Comment by Hubfront** [comment]
Tested on web.de

But works as expected on computerbase.de

**Comment by kbrosnan** [comment]
Dupe of #2590
