### ISSUE TITLE
FNX3-16979 ⁃ [Bug] Extra border/margin is displayed under tabs after tapping on tab numbers button

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/fenix#3380]
## Steps to reproduce
1. Launch Fenix.
1. Open two tabs.
1. Reach home screen.
1. Minimize Fenix.
1. Resume Fenix and open a tab.
1. Tap on the tab numbers in order to reach the home screen.
    1. Expected behavior
Tabs are correctly displayed.
    1. Actual behavior
There is a extra border/margin displayed under tabs.
    1. Device information

* Android device:  Samsung Galaxy Note 9(Android 8.1), HTC M9(Android 6)
* Fenix version: 6/12
    1. Notes
Please note that I wasn't able to reproduce this issue on Google Pixel 3XL(Android P).
Also, note that this issue can be reproducible on `Private mode`.
* [video](https://drive.google.com/file/d/15QV0BVvjNz_us0G7j-OkvY54anAKDeMK/view?usp=sharing)

**Comment by ekager** [comment]
Are you still seeing this issue? I am unable to reproduce

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest Nightly **Build #11970610 from 16/7** using the following devices:
• Google Pixel 3a (Android 9)
• Samsung Galaxy Note 9 (Android 8.1)
• Samsung GalaxyS8+ (Android 8)
• Samsung Galaxy S7 (android 7)
• Samsung Galaxy S6 (Android 6.0.1)
• HTC One M9 (Android 6)
• LG Nexus 4 (Android 5.1.1)

► Video from Google Pixel 3a
![20190716_150413](https://user-images.githubusercontent.com/51314259/61293240-e9945680-a7db-11e9-83cf-e1db01742f45.gif)
