### ISSUE TITLE
FNX3-16980 ⁃ [Bug] After "Remove account" the app returns to homescreen

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#3381]
## Steps to reproduce
1. Sign in to an account on Fenix.
1. On another device delete the account.
1. Restart Fenix, visit settings. It tells you to reconnect. On the "Reconnect to Sync" view press "Remove Account"
    1. Expected behavior
Returns to Turn on Sync view, with the account signed-out and removed.
    1. Actual behavior
Exits the settings menu and returns to the homescreen.
    1. Device information

* Android device: Note 8 (ANdroid 9), Nexus 5 (Android 6.0.1)
* Fenix version: 6/12

**Comment by softvision-miralobontiu** [comment]
It is not entirely fixed: the behavior now is: the dialog "Firefox will stop syncing with your account, but won't delete any of your browsing data on this device" [Cancel] [Disconnect]. It is not going back to the settings page.

@sblatz is it expected?

**Comment by sblatz** [comment]
@softvision-miralobontiu yes that is expected. After pressing the "Disconnect" button, the user is brought back to the Settings screen (not the homescreen) which was the bug fix for this ticket.

I'm going to close as it is QA verified. Please re-open if you're still having an issue!
