### ISSUE TITLE
[Bug] The text selection toolbar & link context menu don't work properly

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#3383]
Prerequisites: Make sure you have a clean profile.

## Steps to reproduce
1. From the onboarding screen access "Read our privacy notice"
1. Select any word by long tap or double tap
1. Long tap on a hyperlink
1. Navigate to https://en.m.wikipedia.org/wiki/Main_Page
1. Select any word by long tap or double tap
1. Long tap on a hyperlink

### Expected behavior
After long tapping a word (or double tap) the text selection toolbar should appear as soon as a word is selected 
After long tapping a link the context menu should appear

### Actual behavior
After long tapping a word (or double tap) the word is highlighted but the text selection toolbar isn't appearing, for both:
•"Read our privacy notice" from the onboarding screen
• https://en.m.wikipedia.org/wiki/Main_Page
After long tapping a link the context menu isn't appearing in the "Read our privacy notice", but appears on https://en.m.wikipedia.org/wiki/Main_Page

### Device information
* Android device: 
Google Pixel 3XL (Android 9)
Samsung Galaxy S6 (Android 6.0.1)
* Fenix version: 1.0.1924 (Build#11630619) 

### Notes:
This issue happens after a fresh install.
Video - https://drive.google.com/open?id=1309lZvvtp_i9vNIkd4bdPSWS4k0NAFl9

**Comment by AndiAJ** [comment]
I was able to reproduce this issue on **1.0.1-rc.1 Build # 11851847 4/7** using a Google Pixel 3XL (Android 9) following this Alternative STR:
1. Visit wikipedia. org
2. Long tap on a word

**Actual behavior:**
After long tapping a word (or double tap) the word is highlighted but the text selection toolbar isn't appearing

**Comment by olsenme** [comment]
Does this still need worked on?

**Comment by ekager** [comment]
Text selection seems to work now and for the context menu I am going to close this ticket for https://github.com/mozilla-mobile/fenix/issues/5063
