### ISSUE TITLE
Sync settings should promote Lockwise and Monitor

### ISSUE THREAD

**Issue by mhammond** [mozilla-mobile/fenix#3384]
### User Story
As a user, I want to know what other Firefox products are available to me through signing into my Firefox account, so I know about the benefits of having an account and I can take advantage of other available privacy and security tools.

Also related: #5498 

Acceptance Criteria:
-When I am about to sign into my Firefox Account, I see other Firefox apps available to me.
-I can tap on any of the listed Firefox Apps to either open the app (if installed) or download them (from Google Play Store)

See sample iOS mocks:
![image](https://user-images.githubusercontent.com/42752644/61352878-73740c00-a83c-11e9-9c52-c529e16c21d7.png)

**Comment by vesta0** [comment]
@lime124 let me know if this needs UX or if the mocks that was done for iOS can be re-used. Thank you!

**Comment by AmyYLee** [comment]
@lime124 @vesta0 Hi, when you sign into sync via Fenix -> Settings using email, the email sign-up page is a URL so it's not native to the app. If there is already a design for that page existing we would need to link it to the new design.

**Comment by lime124** [comment]
@vesta0 and i guess maybe @st3fan - is there a way to make this page a bit dynamic and change the content depending on the context you are viewing it from? It seems a bit odd to mention Firefox (mobile?) to people who are in Preview. 

And if this goes in Fennec, then will people be stuck in a recursive loop?! (my bad attempt at dev humor) :D

/cc @mheubusch

**Comment by vesta0** [comment]
@lime124 @st3fan I agree that if we are just going to link to the URL with the new design, we want to hide the first option "Firefox for Android" as it will be confusing. Do we want to add Firefox for IOS in there though?

**Comment by lime124** [comment]
I'm not sure if iOS would have the most impact as people generally (yes I'm being very general) either have only one device (phone only) and/or live entirely in one ecosystem (apple vs android). We might have more impact if we instead promoted Desktop. But - I'm not sure what would happen when someone taps on it as it's supposed to either launch the app store or open the app. Worse case we just totally drop the mention of Firefox.

All that said I totally defer to @mheubusch for the best course of action here.

**Comment by vesta0** [comment]
This page has already been implemented.
