### ISSUE TITLE
FNX3-16986 ⁃ [Bug] There is no limit of characters on the "Device Name" option

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/fenix#3388]
## Steps to reproduce
1. Launch Fenix.
1. Login with a Firefox account.
1. Tap on the Device name.
1. Add as many characters as you want.
    1. Expected behavior
There should be a character limit on the `Device name` option.
    1. Actual behavior
There is no limit when adding characters on the `Device name`.
    1. Device information

* Android device: **`Samsung Galaxy Note 9(Android 8.1.0)`**
* Fenix version: **`6/12`**
* [Video](https://drive.google.com/file/d/1ihhtYVuugPYkPKiw_rUd6-pO8CV5f3mk/view?usp=sharing)

**Comment by csrapr** [comment]
Is the relevant file for this string `account_settins_preferences.xml`?
If so, according to [Documentation](https://developer.android.com/reference/android/widget/TextView.html#attr_android:maxLength) we can just add the line `android:maxLength="NUMBER"` under `androidx.preference.EditTextPreference`, like this:

```xml
<androidx.preference.EditTextPreference
                android:key="@string/pref_key_sync_device_name"
                android:title="@string/preferences_sync_device_name" 
                android:maxLengh="128"/> <!--here-->
```

Is this correct? If so I can fix this

**Comment by jonalmeida** [comment]
@jdragojevic would you happen to know if there is a character limit for device names?

**Comment by jdragojevic** [comment]
255 characters. @vladikoff  checked it.

**Comment by softvision-miralobontiu** [comment]
Verified that on Device name from Account only 128 characters are permitted.
Tested on the latest build 1.0.1924 (#11650657), with Sony Xperia Z5 Premium (Android 7.1.1), and Samsung Galaxy Note 8 (Android 9).
