### ISSUE TITLE
FNX3-16989 ⁃ [Bug] Indonesian domains are incorrectly entered in Fenix tab switcher

### ISSUE THREAD

**Issue by reinhart1010** [mozilla-mobile/fenix#3392]
Fenix tab switcher only lists [PANDI-reserved secondary level domains](https://pandi.id/en/domain/registration-requirements/) (`*.ac.id`, `*.biz.id`, `*.co.id`, `*.desa.id`, `*.go.id`, `*.mil.id`, `*.my.id`, `*.net.id`, `*.or.id`, `*.ponpes.id`, `*.sch.id`, and `*.web.id`) when the site does not have any subdomain (e.g. `<site>.co.id` instead of `<subdomain>.<site>.co.id` or `www.<site>.co.id`).

![Screenshot](https://user-images.githubusercontent.com/17312341/59370708-521b8e00-8d6d-11e9-9ba2-a532cd195d8c.jpg)UNITO-UNDERSCORE!20190612-235022!UNITO-UNDERSCORE!Firefox Preview!

1. https://go.com
1. https://kominfo.go.id
1. https://www.bi.go.id

Other sites for testcase:

![Screenshot](https://user-images.githubusercontent.com/17312341/59369022-afaddb80-8d69-11e9-9190-d66094937c44.jpg)UNITO-UNDERSCORE!20190612-232507!UNITO-UNDERSCORE!Firefox Preview!

1. http://www.penabur-inter.sch.id
1. https://almanar.ponpes.id
1. https://gunungrejo.desa.id
1. https://kominfo.go.id
1. http://rekrutmen-tni.mil.id
1. http://binus.ac.id
1. http://bpkpenaburjakarta.or.id
1. https://pandi.id - Official .ID registrar, site is without secondary level domain name

![Screenshot](https://user-images.githubusercontent.com/17312341/59369530-d6b8dd00-8d6a-11e9-9fc4-fec0d2b36a27.jpg)UNITO-UNDERSCORE!20190612-233519!UNITO-UNDERSCORE!Firefox Preview!

1. https://web.tunnel.my.id
1. https://good.biz.id
1. https://www.waroeng.web.id
1. https://www.indocyber.net.id
1. https://www.google.co.id

### Device information
* Android device: Samsung Galaxy A7 (2018), Android 8.0.
* Fenix version: 1.0.1921

**Comment by ekager** [comment]
Are you still seeing this issue? I tried a few of these domains and they looked better than the screenshots above now

**Comment by reinhart1010** [comment]
I can now confirm this is fixed, though I have not re-tested all the SLDs.

![Screenshot_20190801-133336_Firefox Preview](https://user-images.githubusercontent.com/17312341/62270881-5573f180-b461-11e9-96cd-f35a8c637ad7.jpg)

1. https://kominfo.go.id/
2 .http://binus.ac.id/ 
3. http://student.binus.ac.id/
4. https://kbbi.kemdikbud.go.id/
5. https://privy.id/

https://www.google.co.id/ now returns to "google" instead of "google.co".

**Comment by ekager** [comment]
Thanks! Closing

**Comment by AndiAJ** [comment]
Hi, verified as fixed on the latest **Nightly Build #12240720 from 12/8** using the following devices:
• Google Pixel 3a (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• OnePlus A3 (Android 6.0.1)
• LG Nexus (Android 5.1.1)

![Screenshot_20190812-150231](https://user-images.githubusercontent.com/51314259/62863785-80d4c700-bd12-11e9-96d6-ac47c2492c8a.png)
