### ISSUE TITLE
FNX3-16990 ⁃ [Bug] SessionsManager is not accurate when launching directly to browser

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#3401]
## Steps to reproduce
1. Have multiple sessions open
1. Force quit the app
1. Launch from external source **NOT a custom tab**

### Expected behavior
1. `SessionManager.sessions` has a list of all the sessions

### Actual behavior
1. `SessionManager.sessions` has a list containing only the tab opened

Wednesday 6/12 build

Very likely related to https://github.com/mozilla-mobile/fenix/issues/3346

## Demo
![session bug](https://user-images.githubusercontent.com/4400286/59386213-f2949280-8d1a-11e9-9e0d-179c335ca569.gif)

**Comment by sblatz** [comment]
@ekager looked at a fix for this. Basically, we're restoring our session manager sessions on the IO thread and they may not be ready by the time the browser fragment is loaded.

See: https://github.com/mozilla-mobile/fenix/blob/master/app/src/main/java/org/mozilla/fenix/components/Core.kt#L115

**Comment by ekager** [comment]
As @sblatz said above the fix to our tab counter issue is to launch the restoration on the main thread because our observers weren't getting called correctly. 

Unfortunately this doesn't fix the session list order because there seems to be a race condition that the new tab is added before the others are restored, so is considered "older" in the list. 

```
            // Restore the previous state.
            GlobalScope.launch(Dispatchers.Main) {
                withContext(Dispatchers.IO) {
                    sessionStorage.restore()
                }?.let { snapshot ->
                    launch(Dispatchers.Main) {
                        sessionManager.restore(snapshot, updateSelection = (sessionManager.selectedSession == null))
                    }
                }
```

**Comment by sblatz** [comment]
@jonalmeida and I chatted about this more, he agreed @ekager's solution works but he's going to see if there's a way they can make this clearer from the a-c side before we implement that :)

**Comment by sv-ohorvath** [comment]
Verified as fixed on the 6/14 build. Devices: Pixel (Android Q), HTC Desire 820 (Android 6.0.1)
