### ISSUE TITLE
FNX3-16991 ⁃ [Bug] cachedTabCollections is not accurate when launching directly to browser

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#3403]
## Steps to reproduce
1. Have multiple sessions open
1. Force quit the app
1. Launch from external source **NOT a custom tab**
1. Open the toolbar menu
1. "Save to Collection"

### Expected behavior
1. The collection list has all previous collections

### Actual behavior
1. The collection list forces you to create a new one since `cachedTabCollections` is null

This is happening because `cachedTabCollections` only gets set when we get a change emitted to us (which we're only listening to in HomeFragment). We could fix this by also listening in BrowserFragment.

**Comment by sblatz** [comment]
Related to #3401, #3346

**Comment by sv-ohorvath** [comment]
Verified as fixed on the 6/14 build. logged issue: #3474 3474
