### ISSUE TITLE
[Bug] Intermittently lose all tabs, URLs replaced with about:blank

### ISSUE THREAD

**Issue by Cheap-Skate** [mozilla-mobile/fenix#3414]
Don't know exact STR but this happens to me perhap once a day

* Using Fenix with several tabs open
* Bring Fenix out of background
* Navigate to "all tabs" Home screen (or Fenix starts there itself after being killed???)
* All tabs are replaced with about:blank

so e.g. I have 4 tabs open on different real URLs. Occasionally Fenix replaces them with 4 tabs all about:blank. I don't know how to reproduce.

I don't think this is the same as #1909, because my tabs are still shown, they just revert to about:blank.

This behavior has been around for days or weeks (I update Fenix quite often)

I'll continue to try to find STR.

Fenix: Monday 6/10 @ 6:07 pm
Galaxy S7, Android 8.0.0

**Comment by Cheap-Skate** [comment]
It just happened now. I downloaded a file from taskcluster using Fenix, then swapped to my file manager to check the file, then swapped back to Fenix (I think I just tapped on the Fenix icon on my home screen to swap back). All tabs replaced by about:blank. But it's not repeatable AFAIK.

![Screenshot_20190613-102813_Firefox Preview](https://user-images.githubusercontent.com/40568887/59421487-9424ee00-8dc6-11e9-825b-631e2011b998.jpg)

**Comment by PopeRigby** [comment]
Having the same issue.

**Comment by ekager** [comment]
And I'm assuming if you force kill the app and reopen the tabs are still about:blank?

**Comment by PopeRigby** [comment]
Yes. I've captured a screenshot of it happening 
![](https://i.imgur.com/6Id3pyo.png)

**Comment by ekager** [comment]
Could be related to: https://github.com/mozilla-mobile/fenix/issues/1577
If one tab process dies, all of them will die, and we currently can't restore them.

**Comment by Cheap-Skate** [comment]
@ekager 

Re Force Stop I'm not sure, I have tried swipe killing in the task manager and that doesn't bring tabs back. Also the "back" arrow button does nothing so I think my history has been nuked as well.

Re #1577 that sounds plausible, thanks for the link.

**Comment by Cheap-Skate** [comment]
@ekager, Force Stop doesn't help

**Comment by secrethash** [comment]
Happening quite a lot of times. Can't find any way to reproduce this issue. One thing I can tell is that my sync also turned off by signing out my Mozilla Account all on it's own. Didn't noticed until recently. Screenshot Shared.
![Screenshot-about:blank](https://i.imgur.com/CQI1fBy.png)
![Screenshot-sync](https://i.imgur.com/iiNYVxZ.png)

**Comment by marthinwurer** [comment]
I'm getting similar behaviour, but it's only some of my tabs turning into about:tab. It's similar to #519, but it's usually just the last tab that I had open.

**Comment by xcffl** [comment]
Same here.
Crashes may raise the probability of this behavior significantly.

**Comment by sblatz** [comment]
Closing this as a dup of #1577
