### ISSUE TITLE
[Bug] App intents are broken again

### ISSUE THREAD

**Issue by pwd-github** [mozilla-mobile/fenix#3416]
## Steps to reproduce
1. Go to Reddit

### Expected behavior
You're supposed to have the app chooser pop up, failing that, you should be able to press "use app"

### Actual behavior
Nothing

### Device information
* Android device: Android 8, LG G8
* Fenix version: 1.0.1924 (Build #11630620 :lizard: 68.0-20190604110028)

**Comment by ekager** [comment]
We purposefully reverted these in https://github.com/mozilla-mobile/fenix/pull/3359
We will revisit when we can improve the behavior
