### ISSUE TITLE
Set Fenix as default browser? Pop-up/Message should be displayed/more highlighted on settings

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/fenix#3417]
### Why/User Benefit/User Problem
Adding this to Fenix maybe will increase the users using Fenix as a default browser.

### What/Requirements
Adding a pop-up/message that is more highlighted regarding setting Fenix as a default browser.

### Acceptance Criteria (how do I know when I’m done?)
The  pop-up/message is added to the Fenix settings.

### Notes
Please note that `Samsung Browser` is using this method with a more clear message regarding the default browser.
Maybe editing our section regarding the default browser, highlighting it would help.
![Screenshot](https://user-images.githubusercontent.com/42831109/59432952-2f32bd80-8df1-11e9-8418-2497d8f11a0b.jpg)UNITO-UNDERSCORE!20190613-153606!UNITO-UNDERSCORE!Samsung Internet!

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-12095)

**Comment by ekager** [comment]
I think this is a good idea for the future! I added a similar graphic for ETP so maybe UX has more ideas about this

**Comment by lime124** [comment]
yep something we can take a look at in the future. removing ux label as it will require more design thinking. we can take a look when the team prioritizes it for a release.

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807110

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
