### ISSUE TITLE
FNX3-16999 ⁃ [Bug][a11y] Share and 3dots menu button from Collections are not correctly pronounced using Talkback

### ISSUE THREAD

**Issue by sv-sdeiac** [mozilla-mobile/fenix#3419]
## Prerequisites
1. You have a collection saved.
1. You have Talkback option enabled from your Android settings.

## Steps to reproduce
1. Open Firefox preview;
1. Tap on the share button or 3dots menu button from the Collections menu;

### Expected behavior
The share and 3dots menu button are correctly pronounced.

### Actual behavior
The share and 3dots menu button are not pronounced correctly. The Talkback read: 'Tab menu button' on both of the buttons.

### Device information
* Android device: LG G7fit (Android 8.1).
* Fenix version: 1.0.1924.

**Comment by ekager** [comment]
We will need new strings for this, but this is bad accessibility. @vesta0 can we prioritize this post MVP.

**Comment by vesta0** [comment]
Agreed @ekager we will address this in our next sprint.

**Comment by mauryat** [comment]
@sblatz , I'd like to work on this.

**Comment by sblatz** [comment]
@mauryat Go for it! 😄

**Comment by mauryat** [comment]
Thanks!

**Comment by sv-sdeiac** [comment]
Verified as fixed on Firefox Preview 1.2.0-rc.2 using Nexus 9 (Android 7.1.1) and LG G7fit (Android 8.1).
