### ISSUE TITLE
User should be able to change the "Scroll Bar" position or hide it

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/fenix#3420]
### Why/User Benefit/User Problem
It would be nice if `Scroll Bar` position could be changed or hided.

### What/Requirements
* If the user change the `Scroll Bar` to left, it should be displayed there while scrolling.
* If the user change the `Scroll Bar` to right, it should be displayed there while scrolling.
* If the user change the `Scroll Bar` to be hided, it should disappear while scrolling.

### Acceptance Criteria (how do I know when I’m done?)
Scroll bar position can be changed or hided.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-12098)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1809973

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
