### ISSUE TITLE
Disable recording the screen in private mode

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/fenix#3422]
### Why/User Benefit/User Problem
As a user, I want recording to be disabled while being in private mode due to security reasons.

### What/Requirements
When recording the screen in private mode, while watching the video, it should be displayed all black and the content from private browsing to be hided.

### Acceptance Criteria (how do I know when I’m done?)
After recording any video in private mode, the video should be black(exactly like in other browsers like Chrome, Samsung browser).

**Comment by abodea** [comment]
I was thinking that this maybe is related to #2768 but the recording issue requires a third party program to reproduce the issue.

**Comment by kbrosnan** [comment]
I believe disable screenshots also disables recording.
