### ISSUE TITLE
FNX3-17003 ⁃ [Bug] [a11y] Options from three-dot menu from the upper right corner are triggered even when double tapping outside the menu

### ISSUE THREAD

**Issue by softvision-miralobontiu** [mozilla-mobile/fenix#3423]
## Steps to reproduce
1. Enable Talkback.
1. Go to three-dot menu from the upper right corner. Double tap to activate.
1. "Settings" is highlighted. 
1. Tap outside the menu.
1. Double tap outside the menu.

### Expected behavior
Tapping once outside the menu highlights another area.
Double tapping outside the menu doesn't trigger the option selected.

### Actual behavior
Tapping once outside the menu doesn't make any effects.
If "Settings" is highlighted, tapping twice anywhere outside the menu triggers "Settings" page.
If "Your Library" is highlighted, tapping twice anywhere outside the menu triggers "Your Library" page.
The same with "Help".

### Device information
* Android device: OnePlus 5T (Android 9)
* Fenix version: 1.0.1924 (#11640609)

![talkback](https://user-images.githubusercontent.com/40694158/59434743-d2390680-8df4-11e9-851b-9ddeb159113f.gif)UNITO-UNDERSCORE!settings!

**Comment by DiegoARL38** [comment]
I think that's expected behaviour. You shouldn't be able to focus any element outside an expanded menu... As a regular screen reader user, I expect that behaviour.

**Comment by ekager** [comment]
@DiegoARL38 thanks for the input! Do you expect to not be able to dismiss the menu when you click somewhere else then?

**Comment by DiegoARL38** [comment]
@ekager Usually, the only two ways to close an expanded menu are pressing the back button or bypass-clicking outside the menu (clicking with two fingers to bypass the screen reader behaviour , which acts like a normal click). The current behaviour is what i would expect, although i'm not an expert, so i may very well just be used to it.

**Comment by mihai-adrian** [comment]
#3584 also addresses this.

**Comment by mcarare** [comment]
Closing this, as the reporting issue is an expected behaviour, and the related issue is tracked by #3584
