### ISSUE TITLE
FNX3-17005 ⁃ [Bug] "Share and Send" button from collections displays "Tab Menu" while hovering it with S-Pen

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/fenix#3425]
## Steps to reproduce
1. Launch Fenix.
1. Open more tabs.
1. Add them to a collection.
1. With the S-Pen hover the `Share and Send` button from Collections.
    1. Expected behavior
The `Share and Send` name should appear while hovering the button.
    1. Actual behavior
The `Tab Menu` name is displayed while hovering the `Share` button.
    1. Device information

* Android device: Samsung Galaxy Note 9(Android 8.1.0)
* Fenix version: 6/13
    1. Notes
Please note that I believe it takes the name from the nearby button aka `Tab Menu`.
* [video](https://drive.google.com/file/d/1rp820ysHubPcbiTxD_d2eOVafXyRLpQ8/view?usp=sharing)

**Comment by Mugurell** [comment]
Closing as per https://github.com/mozilla-mobile/fenix/issues/3425#event-2467222581
