### ISSUE TITLE
FNX3-17006 ⁃ [Bug]Desktop folders visible in edit mode, without being signed in

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#3426]
## Steps to reproduce
1. Not connected to sync, go to the Bookmarks menu.
1. Edit a bookmark, tap the parent folder to change it.
1. Observe the list of folders.
    1. Expected behavior
No desktop folders when not connected to sync: in the bookmarks menu and in the Select folder mode in Edit bookmark. 
Only mobile folders created on the current device are visible, without sync.
    1. Actual behavior
Desktop folders are visible in Edit mode. Plus, there's a "sign in to sync bookmarks" button.
    1. Device information

* Android device: Nexus 5 (Android 6.0.1), Note 8 (Android 9)
* Fenix version: 6/13 .

**Comment by sv-ohorvath** [comment]
This was reproducing before #3203.

**Comment by colintheshots** [comment]
This should be addressed by PR #3446.

**Comment by softvision-miralobontiu** [comment]
Verified as fixed on the latest Nightly build (#11840608) with HTC Desire 820 (Android 6,0,1), and Samsung Galaxy S8 (Android 9).
