### ISSUE TITLE
FNX3-17007 ⁃ [Bug] Mobile bookmarks folders not visible in edit mode

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#3427]
## Steps to reproduce
1. Create a bookmark, go to the Bookmarks menu.
1. Edit the bookmark, tap the parent folder to change it.
1. Tap the + button to create a new folder. Save. Return to the bookmarks menu.
1. Edit another bookmark, edit the folder and look for the one created before. 
    1. Expected behavior
The mobile folders are displayed in the "choose folder" menu.
    1. Actual behavior
No mobile folders in edit mode. 
    1. Device information

* Android device: Nexus 5 (Android 6.0.1), Note 8 (Android 9)
* Fenix version: 6/13

**Comment by sv-ohorvath** [comment]
Reproducing only after #3203.

**Comment by topotropic** [comment]
yes, I also see this; instead of the mobile folders I see the "Desktop Bookmarks" (Bookmarks Menu, Bookmarks Toolbar, Other Bookmarks)

**Comment by colintheshots** [comment]
PR#3446 addresses this.

**Comment by softvision-miralobontiu** [comment]
Verified as fixed on the latest build 7/2 with HTC Desire 820 (Android 6.0.1), Google Pixel (Android Q), and Motorola Moto G6 (Android 8).
