### ISSUE TITLE
FNX3-17012 ⁃ [Bug] Pinch zooming in on a picture from Amazon.de triggers the context menu

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#3431]
## Steps to reproduce
1. Navigate to : [Amazon.de link](https://www.amazon.de/Fintie-Samsung-Galaxy-Tab-9-7/dp/B013I1UO76/ref=sr_1_3?__mk_de_DE=%C3%85M%C3%85%C5%BD%C3%95%C3%91&keywords=Schutzh%C3%BClle+Samsung+Tab+S2&qid=1559065534&s=gateway&sr=8-3
)
1. Tap on the product picture
1. Pinch zoom in

### Expected behavior
Zoom in without triggering the image context menu

### Actual behavior
Zooms in triggering the context menu

### Device information
* Android device: Google Pixel 3 (Android 9), Samsung Galaxy S6 (Android 6.0.1), Xiaomi MiPad 3 (Android 7.0)
* Fenix version: 1.0.1924(Build#11640609) 13/06/19

### Note
[Video](https://drive.google.com/file/d/0B5fNEgl2UpNpb2VncGxzYi10NGgySm9rYndZV0hZOEJaTmww/view?usp=sharing)

**Comment by ekager** [comment]
This doesn't happen with Chrome but does happen with Fennec. I opened https://bugzilla.mozilla.org/show_bug.cgi?id=1570559

**Comment by cpeterso** [comment]
The GV bug was fixed in GV 71 Nightly last month. I will remove this issue's `needs:gv` and `waiting` labels and add `eng:qa:needed`.

https://bugzilla.mozilla.org/show_bug.cgi?id=1570559#c14

**Comment by sv-ohorvath** [comment]
Verified as fixed on latest Nightly 10/9. Devices: Pixel 3 (Android 9), Sony Xperia Z5 Premium (Android 7.1.1)
