### ISSUE TITLE
"Close private tabs" notification should be added to Android task bar when Fenix is closed or minimized

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/fenix#3432]
### Why/User Benefit/User Problem
As a user, I want to be able in case I minimize or close Fenix while being in `Private Mode` to close all the opened tabs from `Android Task bar`.

### What/Requirements
After browsing something in private mode and minimize Fenix or close it, a `Notification` bar should be displayed with `Close all private tabs` message. 

### Acceptance Criteria (how do I know when I’m done?)
The private tabs after Fenix is closed / minimized can be closed from Android Task bar notification.

    1. Notes
Please note that this option is available in Chrome and it is very useful when browsing a lot in private mode, this will help cleaning all the tabs

**Comment by NotWoods** [comment]
Focus also has this feature and we can probably copy the implementation from there.
