### ISSUE TITLE
Fenix doesn't show up in recent apps menu

### ISSUE THREAD

**Issue by PopeRigby** [mozilla-mobile/fenix#3434]
# Steps to reproduce
1. Open Fenix
1. Click home (circle) button
1. Click recent apps (square) button

# Actual behavior
Fenix isn't shown

# Expected behavior
Fenix should show up in recent apps menu

# App information
![](https://i.imgur.com/JZImAfB.png)

**Comment by AaronMT** [comment]
Which version of Android and launcher are you using?

**Comment by PopeRigby** [comment]
Android version: 8.1 Oreo
Launcher: Lawnchair

**Comment by PopeRigby** [comment]
It seems to come and go. It was happening earlier and now it's not. It'll probably happen again later.

**Comment by Terryvanderjagt** [comment]
I experience the same bug.
Android version: 9
Launcher: Oneplus Launcher

**Comment by sblatz** [comment]
I'm closing this as fixed as I'm not able to reproduce and neither can @Terryvanderjagt in the latest build.

@PopeRigby please re-open if you're still having issues 😄
