### ISSUE TITLE
[Bug]Duplicate devices on the share section

### ISSUE THREAD

**Issue by sv-sdeiac** [mozilla-mobile/fenix#3435]
## Prerequisites
You are connected with multiple devices on the same account

## Steps to reproduce
1. Perform a sync on all devices;
1. Reinstall the app on some devices;
1. Connect with the same account on the reinstalled apps;
1. Perform a sync on all devices;
1. Open the share section;

### Expected behavior
There are only the latest synced devices on the list.

### Actual behavior
There are duplicate devices.

### Device information
* Android device: LG G7fit (Android 8.1), Nokia 6(Android 7.1.1), Nexus 6 (Android 7.1.1).
* Fenix version:  1.0.1924.
* Notes: 
  * This issue is visible when you install a new version of the app and you reconnect with the same account.

**Comment by jonalmeida** [comment]
> 2. Reinstall the app on some devices;

Unfortunately, when an app is uninstalled, it's not possible to perform a "log out" to notify the sync server (since it could be that the device is offline instead of uninstalled). So for that reason you would continue to see duplicate devices there.

If you were to log out of sync first, then uninstall, that should no longer be an issue.

**Comment by tv-zkal** [comment]
@jonalmeida: This happens even if you remove/revoke device from Firefox Account, it doesn't remove the Send tab entry for the revoked Fenix device.

**Comment by jonalmeida** [comment]
> @jonalmeida: This happens even if you remove/revoke device from Firefox Account, it doesn't remove the Send tab entry for the revoked Fenix device.

Interesting, I'd start with @grigoryk to see if he knows what could cause the duplication but I'm fairly sure we remove old devices before a new sync so this might be an a-s issue once we verify that.

**Comment by sblatz** [comment]
@tv-zkal are you still seeing this?

**Comment by tv-zkal** [comment]
@sblatz After a quick test (connected, removed device from Manage Account and reconnected) device was properly removed from send tab list so looks like it's fixed 👍

**Comment by sblatz** [comment]
That's great news! 😄
