### ISSUE TITLE
Clean up variable declarations at top of file

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#3436]
Currently our variable declarations are very messy and inconsistent in sorting among files (some of the worst offenders are `HomeFragment` and `BrowserFragment`). We should sort them all using the same rule.

**Comment by NotWoods** [comment]
Personally I think the reverse is better - requireContext().components makes it more clear that context is relied on. If the component is optional when context isn't available `context?.components` is cleaner than `context?.let { requireComponents }`

**Comment by sblatz** [comment]
Labeling as p5 as this will likely cause quite a few merge conflicts and we currently have bigger fish to fry.
