### ISSUE TITLE
FNX3-17018 ⁃ [Dark Theme] Tab highlight colour is too dark

### ISSUE THREAD

**Issue by AmyYLee** [mozilla-mobile/fenix#3439]
The purple highlight around the currently open tab should be #AB71FF (Violet 40). Thanks!

![image](https://user-images.githubusercontent.com/5992746/59450595-87f55c80-8dd7-11e9-943e-2b3f99196d78.png)

**Comment by ekager** [comment]
Can you confirm that light theme should be #592ACB?

**Comment by AmyYLee** [comment]
> Can you confirm that light theme should be #592ACB?

@ekager That's correct!
