### ISSUE TITLE
Decide to use requireComponents or safe unwrap context

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#3440]
Currently we use the two interchangeably throughout the code base and it doesn't seem to have reasoning behind it (or at least reasoning that is transparent to other engineers). I'm of the mind that we should just be using `requireComponents` so we don't have silent failures.

**Comment by ekager** [comment]
there are still a few `context!!`s in our codebase that can be converted to `requireContext()`s so we can close out this ticket
