### ISSUE TITLE
[Bug] I can move bookmarks into folders I can't access (FxA disabled)

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#3448]
When I move a bookmark to a "sync" folder, it disappears from my bookmarks list because I'm not signed in :cry: 

![demo 2019-06-13 11](https://user-images.githubusercontent.com/4400286/59459004-9ab86300-8dd0-11e9-999a-21e7b2175e44.gif)UNITO-UNDERSCORE!44!UNITO-UNDERSCORE!24!

**Comment by colintheshots** [comment]
This is fixed, but I've been told not to merge it yet. https://github.com/mozilla-mobile/fenix/pull/3446

**Comment by sv-ohorvath** [comment]
dupe: #3426
