### ISSUE TITLE
In-app access to Release Notes

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/fenix#3450]
## User Story
* As a user, I want to be able to look up Release Notes from within the browser settings, so I know what was recently updated.

### Acceptance Criteria
* I can access the Release Notes by clicking on a link within the browser settings.

**Comment by ekager** [comment]
Do we know how we want to do this? Will there be a SUMO page like our other Settings links?

**Comment by vesta0** [comment]
@ekager I was thinking of something like [this](https://www.mozilla.org/en-US/firefox/android/67.0.3/releasenotes/) but not sure how we go about setting that up. @mheubusch would know :)

**Comment by NotWoods** [comment]
@sblatz @vesta0 Is this handled by the What's New option?

**Comment by vesta0** [comment]
This was meant to be different than What's new. What's new is an end-user facing support articles focused on features that are only published for major releases, however, our power users may also like access to detailed release notes (which bugs were fixed, etc). This is a feature in Fennec and we need to evaluate to see if there is value in adding this option to Fenix as well.

**Comment by vesta0** [comment]
This will be addressed in #4776
