### ISSUE TITLE
FNX3-17029 ⁃ [Settings] Missing button background in "clear permissions on all sites" button

### ISSUE THREAD

**Issue by AmyYLee** [mozilla-mobile/fenix#3453]
Settings ~~> Site Permissions~~ > Exceptions 

"Clear permissions on all sites" button is missing button background colour. 

Same for Light/Dark theme
Text Colour: Violet #312A65, 
Button Colour: Grey #E0E0E6

Spec:
![](https://user-images.githubusercontent.com/5992746/59463673-90a85b80-8df4-11e9-9cd5-7fcf83af3b4a.png)

Screenshot
![Screenshot](https://user-images.githubusercontent.com/5992746/59463801-c9e0cb80-8df4-11e9-9bd7-fb20a8be0112.png)UNITO-UNDERSCORE!20190613-154911(1)!

**Comment by sblatz** [comment]
@AmyYLee are we able to use a color that's already defined in the app that follows theming? I'm confused as to why we're introducing another color.

**Comment by AmyYLee** [comment]
@sblatz sorry I should have made this clearer. The button and text colour should be applied across light/dark themes. Right now we have 2 different greys for light and dark theme for this button.
