### ISSUE TITLE
FNX3-17031 ⁃ Add options to disable fonts, pictures and JavaScript

### ISSUE THREAD

**Issue by xerz-one** [mozilla-mobile/fenix#3457]
Just like the current Firefox for Android and Firefox Focus allow to block these resources, Fenix should offer the same options in order to provide more private and less resource-consuming browsing experiences. Additionally, you could allow users to choose if they want to enable these options only in private sessions.

**Comment by brampitoyo** [comment]
@ekager Clarifying question: will it be possible to enable/disable fonts/pictures/JS on a per-site basis, or can we only do this globally (for all sites)?

If per-site controls are possible, we can design this feature like we’ve done with the rest of our site permissions. You simply open the Site Information Panel to allow/block per site.

**Comment by AmyYLee** [comment]
@ekager for follow-up

**Comment by ekager** [comment]
yes AFAIK it's possible to change this per-site with a global default. The only difference is most of the other permissions (except autoplay) request the first time you need them on that site so these would be slightly different. 

We should maybe pull this ticket into #11460

**Comment by madb1lly** [comment]
Hi all,
Just to lend my voice to this, it's pretty frustrating to still have to go into about:config to avoid images being loaded.
Cheers 🙂

**Comment by brampitoyo** [comment]
Thanks for confirming, @ekager! With that, I will mock permissions for fonts, pictures and JS on #11460. Let’s now close this issue.
