### ISSUE TITLE
FNX3-17034 ⁃ [Bug] File downloads do not show up in notifications

### ISSUE THREAD

**Issue by edtamarin** [mozilla-mobile/fenix#3465]
## Steps to reproduce
1. Go to any web site offering a download of a file. Technical datasheets work best since they are easiest to get.
1. Initiate the download.

### Expected behavior
The file downloads and a notification is shown updating the user on the download progress and results.

### Actual behavior
No notification is shown, it is impossible to determine if the download has failed or succeeded unless the file is seen in any file manager.

### Device information
Notifications are enabled for both Firefox and the Files app. 

* Android device: Nokia 8, running Android 9 with May security patch.
* Fenix version: 1.0.1924, build 11641808

**Comment by techexo** [comment]
I can confirm this issue on my Oneplus3t Android 9 (LOS 16) phone.

My phone was vibrating without displaying any notification. I installed a notification logger and it showed me that download notifications were indeed generated by Firefox Preview, but were not persistent (i.e. there is no way for the user to see it).

There might be an issue with the time of display? Please don't hesitate to ask for more information if needed.

Cheers

**Comment by vesta0** [comment]
I had the same issue before and noticed that I had notifications disabled for Firefox Preview in my apps settings. @edtamarin and @techexo would you please confirm if you have notifications enabled for Firefox Preview?

**Comment by techexo** [comment]
@vesta0, yes I had enabled notifications for Firefox preview.

**Comment by pocmo** [comment]
Adding "a-c" label: This issue should be resolved after switching to our Gecko-based download manager. Project board:
https://github.com/orgs/mozilla-mobile/projects/34

And early version (including custom notification!) of that is already running in Reference Browser:
https://github.com/mozilla-mobile/reference-browser

**Comment by thewhitetulip** [comment]
I still can't see Download Progress, neither do I see a dedicated downloads tab
