### ISSUE TITLE
[Bug][a11y] The Talkback doesn't move to the Toolbar if you are at the bottom of the page

### ISSUE THREAD

**Issue by sv-sdeiac** [mozilla-mobile/fenix#3467]
## Prerequisites
You have Talkback option enabled from your Android settings.

## Steps to reproduce
1. Open a page(ex. Wikipedia.org);
1. Go to the bottom of the page; 
1. Tap on the last word to activate Talkback;
1. Swipe on screen to the right for changing the Talkback position;

### Expected behavior
The Talkback is moved to the Toolbar items.

### Actual behavior
The Talkback doesn't move to the toolbar items.

### Device information
* Android device: Nexus 6 (Android 7.1.1) and LG G7 fit (Android 8.1)
* Fenix version: 1.0.1924
* Notes: If you are on the toolbar and swipe to the left to make Talkback going to the page items it works.

**Comment by sblatz** [comment]
This is something we should fix and I will put on AC's radar. That being said, we're going to default screen reader users to having a top, fixed toolbar since swiping through a variable amount of content is bad anyway. See https://github.com/mozilla-mobile/fenix/issues/1718

**Comment by sblatz** [comment]
Lowering the priority on this since we have a bandaid fix for now and accessibility users will likely want the top fixed toolbar anyway.
