### ISSUE TITLE
[Bug] Getting old versions of pages after going back

### ISSUE THREAD

**Issue by djc** [mozilla-mobile/fenix#3470]
## Steps to reproduce
1. Navigate to Reddit (for example https://www.reddit.com/r/rust)
1. Click one of the links
1. Go back

### Expected behavior
See the same version of the page as before.

### Actual behavior
In some instances, I see an older version of the page (probably from some cache).

### Device information
* Android device: Pixel 2
* Fenix version: 1.0.1924 (Build #11630620 68.0-2019060411028)

Previously reported for Fennec as https://bugzilla.mozilla.org/show_bug.cgi?id=1500797.

**Comment by ekager** [comment]
Are you still seeing this @djc ?

**Comment by djc** [comment]
Yup.

**Comment by ernstp** [comment]
Also seeing this very often.

**Comment by djc** [comment]
Probably a dupe of #5869.
