### ISSUE TITLE
[Bug]The loading icon is not in the center of the page

### ISSUE THREAD

**Issue by sv-sdeiac** [mozilla-mobile/fenix#3472]
## Steps to reproduce
1. Open Firefox Preview;
1. Go to settings;
1. Tap on 'Turn on sync';
1. Choose 'Turn on Sync' from the list.

### Expected behavior
The login page is presented without any visual defects.

### Actual behavior
The loading icon from the page is not centered.

### Device information
* Android device: Nexus 6 (Android 7.1.1),  Sony Xperia Z5 Premium (Android 7.1.1) and LG G7 fit (Android 8.1);
* Fenix version: 1.0.1924;
* Notes: This issue is not so visible on all devices;
*Screenshot: 
![Screenshot](https://user-images.githubusercontent.com/40264165/59508488-d62d5d00-8eb6-11e9-9aca-854b67fdcc02.png)UNITO-UNDERSCORE!20190614-145224!

**Comment by ekager** [comment]
Will be fixed by FXA see https://github.com/mozilla/fxa/issues/1236

**Comment by ekager** [comment]
Closing because it was fixed in mozilla/fxa#2300
