### ISSUE TITLE
FNX3-17040 ⁃ [Bug] Select tabs for a collection screen contains a tab just removed (before the snackbar disappears)

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#3473]
## Steps to reproduce
1. Open a few tabs.
1. Close one tab.
1. Before the undo snackbar closes, tap save to collection.
1. Verify the tabs list on the "Select tabs" screen.
    1. Expected behavior
The tab removed doesn't appear in the list.
    1. Actual behavior
The tab is still shown if you try to save the collection before the undo snackbar disappears.
    1. Device information

* Android device: S8 (Android 9)
* Fenix version: 6/14

**Comment by ekager** [comment]
I'm not seeing this on master. Can you still reproduce?

**Comment by sv-ohorvath** [comment]
No, I can't reproduce this anymore on Nightly 7/16.
