### ISSUE TITLE
[Bug] With Don't keep activities on, the tabs/collection selection screen is empty after you switch tasks

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#3474]
## Steps to reproduce
Turn on "Don't keep activities" in Developer settings.

1. Open a few tabs.
1. Tap save to collection.
1. minimize and restore the app.
    1. Expected behavior
The "select tabs" screen still shows the tabs opened.
    1. Actual behavior
Tabs opened aren't displayed anymore.
*Same behavior if you continue until the Select collection screen and minimize the app. The existing collections aren't displayed.
    1. Device information

* Android device: Galaxy S8 (Android 9), Sony Xperia Z5 Premium (Android 7.1.1), HTC Desire 820 (Android 6.0.1) 
* Fenix version: 6/14

**Comment by olsenme** [comment]
Does this still need worked on? I am an outreachy participant, and I was recommended to look at a few of your issues here. Sorry for all the comments. Difficulty?

**Comment by dylmye** [comment]
bump for @olsenme

**Comment by KaairaGupta** [comment]
Hey @sv-ohorvath ! this doesn't reproduce on my mobile(Android 9). So. does this issue still need to be worked on?

**Comment by sv-ohorvath** [comment]
Hello all, I can't reproduce this on the latest builds so I will close this issue. Thank you!
