### ISSUE TITLE
[Bug][LG Keyboard] Erasing the autocomplete form dublicate the text

### ISSUE THREAD

**Issue by sv-sdeiac** [mozilla-mobile/fenix#3475]
## Prerequisites
You have the LG keyboard set on your device

## Steps to reproduce
1. Open Firefox preview;
1. Tap on the search bar;
1. Write 'wi' in the search bar;
1. Tap one time the backspace button to erase the autocomplete;

### Expected behavior
After erasing the autocomplete form, there is only 'wi' text.

### Actual behavior
After erasing the autocomplete form, there is a duplicate letter after 'wi'.

### Device information
* Android device: LG G7 fit (Android 8.1)
* Fenix version: 1.0.1924
* Notes: 
-The issue is reproducible with all text who have an autocomplete form. 
-Not reproducible on other keyboards.
![20190614](https://user-images.githubusercontent.com/40264165/59515111-05e46100-8ec7-11e9-87d3-06ab9f300ff3.gif)UNITO-UNDERSCORE!165752!

**Comment by sv-sdeiac** [comment]
This issue is still reproducible using the latest version of Firefox Preview Nightly 1/7 build #20070606 on LG G7 fit (Android 8.1).

**Comment by johancz** [comment]
I have this bug on my Samsung Galaxy S9 with both Samsung's and Google's keyboard.
Android version: 10
One UI: version 2.0
Firefox Preview version: 5.0.0 (Build #buildnmr) 39.0.1 ...
This bug has been around for many versions of Preview.

No other apps have this bug (including other browsers and the stable/normal version of Firefox on Android).

**Comment by kbrosnan** [comment]
@sv-sdeiac is this still reproducible on the LG phone?

**Comment by mobd** [comment]
I can also reproduce this with [openboard](https://f-droid.org/en/packages/org.dslul.openboard.inputmethod.latin/). It only started happening with openboard's recent update.

**Comment by s-ankur** [comment]
I can't see this anymore with openboard

**Comment by mobd** [comment]
I can still reproduce with the latest openboard and nightly
![output_0](https://user-images.githubusercontent.com/66154603/98866946-07280d80-246e-11eb-813f-0448e86455f8.gif)

**Comment by ebalazs-sv** [comment]
> @sv-sdeiac is this still reproducible on the LG phone?

This issue is still reproducible on Nightly 2/16 with LG G7 fit (Android 8.1).

Not reproducible with Motorola Moto G6 (Android 8).

**Comment by mobd** [comment]
This bug is still reproducible
