### ISSUE TITLE
FNX3-17044 ⁃ Tab sent snackbar missing

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla-mobile/fenix#3478]
When users send a tab from Fenix to another device, there should be this snackbar appearing. It was not showing during the most recent Sync Fest.

![](https://user-images.githubusercontent.com/68213/59516783-1cbb9100-8e90-11e9-8bba-77fc16f8656e.png)

**Comment by ekager** [comment]
Will be simple to add but requires string work so I won't be able to get it in today before cutting MVP :/

**Comment by ryanfeeley** [comment]
@ekager If possible, you can use the equivalent string from desktop which is **Sent!** https://transvision.mozfr.org/string/?entity=browser/chrome/browser/browser.properties:confirmationHint.sendToDevice.label&repo=gecko_strings

**Comment by vesta0** [comment]
Adding this to the [send tab board](https://github.com/orgs/mozilla-mobile/projects/19)

**Comment by softvision-miralobontiu** [comment]
Verified that the "Tab sent!" snackbar is displayed on the debug build 1.0.1928 GV 68.0-20190612114833, but on Motorola Nexus 6 (Android 7.1.1) is overlapping the URL bar:

![Screenshot_20190711-151758](https://user-images.githubusercontent.com/40694158/61050906-bc693200-a3f0-11e9-868d-551dce4d2099.png)

@ryanfeeley should I file a new issue for this reason?
Thank you!

**Comment by ekager** [comment]
Yeah let's close this and I will file a new issue, thanks!
