### ISSUE TITLE
[Telemetry] Bookmarks and history sync ping_types

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#3479]
## Steps to reproduce:
Sign in to Fenix Sync
Sync starts as soon as successfully logged in
Check the pings that are sent 

### Expected behavior
Don't know if this is the normal behavior 

### Actual behavior
Based on the attached logcat [items.txt](https://github.com/mozilla-mobile/fenix/files/3291116/items.txt) right after the first sync is performed we have the following:

## •"ping_type": "history_sync" 
Ping id: d9b61ab4-02e9-4e03-bf76-5ffd1dad751c
Lines 4640 - 4685 
{
      "metrics": {
        "labeled_counter": {
          "history_sync.outgoing": {
            "uploaded": 8
          }
        }

### 8 History items indeed ![History](https://user-images.githubusercontent.com/51314259/59516401-f1559800-8ec9-11e9-8bfd-6b6b14c8d3ed.png)
Again, "ping_type": "history_sync" - ping id: da1bf63c-9699-40fd-a0fb-4c2bebfcf1f5
Lines 4840 - 4896
{
      "metrics": {
        "counter": {
          "history_sync.outgoing_batches": 1
        }

## • "ping_type": "bookmarks_sync"
Ping id: 3d6ec5ab-ef8a-495b-a44d-695c64b30326
Lines 4968-5013
 {
      "metrics": {
        "labeled_counter": {
          "bookmarks_sync.outgoing": {
            "uploaded": 4
          }
        }
The only Bookmark present is the "Desktop Bookmarks" which contains 3 other folders "Bookmarks Manu", "Bookmarks Toolbar", "Other Bookmarks"
![Bookmarks](https://user-images.githubusercontent.com/51314259/59517043-51007300-8ecb-11e9-90b9-e6bb0e2b7f5f.png)
![DesktopBookmarks](https://user-images.githubusercontent.com/51314259/59517050-552c9080-8ecb-11e9-816d-6e76d83f9b66.png)

Afterwards again another "ping_type": "bookmarks_sync"
Ping id: 2002fe76-28ec-4923-ae65-d7d92fdff61d
Lines 5089-5127
{
      "metrics": {
        "counter": {
          "bookmarks_sync.outgoing_batches": 1
        }

### Device information
* Android device: Samsung Galaxy S6 (Android 6.0.1)
* Fenix version: 1.0.1924(14.06.2019)

**Comment by AndiJoltan** [comment]
I believe this topic is related to #1190 

@boek @sblatz - Please review and let us know if this is properly working?

**Comment by boek** [comment]
This does look good to me!

The four items are the four folders
