### ISSUE TITLE
Add Downloads section to the Library

### ISSUE THREAD

**Issue by boek** [mozilla-mobile/fenix#348]
### User Story
As a user, I want to have quick access to my downloads, so I can easily access them.

### Acceptance Criteria
-I can see the download section in the library and open the download section

![image](https://user-images.githubusercontent.com/42752644/66097090-1fd7ab80-e56b-11e9-888c-280f88f612d3.png)

**Comment by yoasif** [comment]
See also https://github.com/mozilla-mobile/fenix/issues/10463

**Comment by madb1lly** [comment]
Hi @vesta0,
Why was this closed? Does #10463 supersede it?
Thanks 🙂

**Comment by cadeyrn** [comment]
There is no longer a "library" and this issue is about integrating the downloads section into the library. There is still #349 for a UI to access downloads.
