### ISSUE TITLE
Split-Screen Tabs

### ISSUE THREAD

**Issue by vrudesai** [mozilla-mobile/fenix#3480]
### Why/User Benefit/User Problem
As a user, I want the ability to horizontally split-screen 2 tabs at once.

### What/Requirements
-UX Completed

### Acceptance Criteria (how do I know when I’m done?)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-12145)

**Comment by Neikon** [comment]
This is specially useful in long screen with Aspect Ratio: 19.5:9 or 21:9 like the new xperia. All new phones have screen longer than the old 16:9

**Comment by NotWoods** [comment]
I think we could show an option in the menu to open a new window if in multi-window mode.

[`Activity#isInMultiWindowMode()`](https://developer.android.com/guide/topics/ui/multi-window) returns true when in split-screen mode (phones, tablets) or when in multi-window mode (tablets, desktop). We could display an option in the overflow menu to open a new "window" when this function returns true.

Supporting split-screen will also let us support multiple windows on Chrome OS.

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807064

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
