### ISSUE TITLE
FNX3-17051 ⁃ Add back open image in new tab

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#3487]
This is blocked on https://github.com/mozilla-mobile/fenix/issues/2312

**Comment by sblatz** [comment]
I'm adding this back to group triage because for some reason this behavior was added back... I want to sync up on whether or not we should remove it again or try to prioritize fixing the GV bug.

**Comment by cpeterso** [comment]
The GV bug blocking #2312 was fixed in GV Nightly last week:

https://bugzilla.mozilla.org/show_bug.cgi?id=1551659#c24

**Comment by sblatz** [comment]
This should be fixed in GV nightly. Can we try adding this back now?

**Comment by softvision-miralobontiu** [comment]
Verified as fixed on the latest Nightly build  191002 (#12750607) with Samsung Galaxy Note 8 (Android 9), and Samsung Galaxy Tab A6 (Android 5.1.1).
