### ISSUE TITLE
[Regression] [Bug] Tapping shortcut button in Search Fragment does not clear previous URL

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#3488]
## Steps to reproduce
1. Navigate to a website
1. Press the url bar
1. Press the shortcut button
1. Select an engine

### Expected behavior
1. Search field is cleared

### Actual behavior
1. Search field remains with the url visited

**Comment by AaronMT** [comment]
Privacy leak if this happens with private tabs?

**Comment by AndiAJ** [comment]
Hi, I've still managed to reproduce this issue on the latest Fenix build (#11790617 from 28/6) using the following devices:

• Google Pixel 3XL (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7.0)

►Video from Google Pixel 3XL
![2019_06_28_10_19_50](https://user-images.githubusercontent.com/51314259/60325313-afc7f100-998f-11e9-8b1a-ab8c36001217.gif)

Based on this I'll remove the "QA needed" label.

**Comment by sblatz** [comment]
Ah whoops. This is still blocked on [this ac ticket](https://github.com/mozilla-mobile/android-components/pull/3447). Going to label it as such for now.

**Comment by sblatz** [comment]
I'm going to close this as it's actually in conflict with https://github.com/mozilla-mobile/fenix/issues/2067 which seems like the correct UX (we should persist information)
