### ISSUE TITLE
FNX3-17053 ⁃ [Bug] Blank collection names should be disabled

### ISSUE THREAD

**Issue by nikit19** [mozilla-mobile/fenix#3489]
## Steps to reproduce
1 Create a new collection
2 Press the space bar in the editText
3 Press enter in the keyboard

### Expected behavior
Blank names should be disabled

### Actual behavior
Collection with a Blank name is being created

I would like to work on this issue.

**Comment by AndiAJ** [comment]
Hi, verified as fixed on the latest Fenix build (#11790617 from 28/6) using the following devices:

• Google Pixel 3XL (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7.0)
• Samsung Galaxy J7 (Android 6.0.1) 
• Sony Xperia Z3 (Android 5.1.1)
