### ISSUE TITLE
FNX3-17057 ⁃ [Bug] ShareFragment doesn't dismiss when clicking outside content / on scrim

### ISSUE THREAD

**Issue by ekager** [mozilla-mobile/fenix#3496]
## Steps to reproduce
1. Open share fragment
1. Click on scrim

### Expected behavior
Dialog dismisses

### Actual behavior
Dialog only dimisses with X

### Device information
* Android device: ?
* Fenix version: ?

**Comment by nikit19** [comment]
I would like to work on this issue. 😄
