### ISSUE TITLE
[Bug] External launch, then switching tab, then "back" takes me home.

### ISSUE THREAD

**Issue by pwd-github** [mozilla-mobile/fenix#3504]
## Steps to reproduce
1. Open Fenix from another app. 
1. Long press a link to open it in a new tab. 
1. Press switch to tab on the snack bar. 
1. Press back

### Expected behavior
You're returned to the previous tab. 

### Actual behavior
Fenix is closed. 

### Device information
* Android device: Android 8, LG G8
* Fenix version: 1.0.1924 (Build #11660624 :lizard: 68.0-20190611143747)

**Comment by sblatz** [comment]
I think this is expected behavior given our implementation. When pressing the "back" button after switching normally takes you to the home view if you didn't launch from an external app.
