### ISSUE TITLE
[Bug] Sent tab for app opens in pop-up window.

### ISSUE THREAD

**Issue by agi90** [mozilla-mobile/fenix#3506]
Not totally sure this is a bug, but it really confused me. I suspect this is a Samsung-specific bug.

## Steps to reproduce
* Send tab from desktop, use website that you have an app for installed (I used twitter.com)
* Open tab from Notification pop-up

### Expected behavior
* Either App or Website opens in normal view

### Actual behavior
* Link opens in pop-up window instead of opening in normal app

### Device information
* Android device: Samsung S10e
* Fenix version: Latest from Playstore

![Screenshot](https://user-images.githubusercontent.com/4297388/59555995-1f5ed900-8fab-11e9-98a5-d6f590059493.jpg)UNITO-UNDERSCORE!20190615-132002!UNITO-UNDERSCORE!Twitter!

**Comment by agi90** [comment]
This might end up being a System bug. I've had this bug happen on a system notification too.

**Comment by ekager** [comment]
Have you continued to see this? @agi90 This is definitely a Samsung... feature ... :)

**Comment by agi90** [comment]
Can't see this anymore \o/!

**Comment by agi90** [comment]
Yep still there :(

**Comment by boek** [comment]
@agi90 Does this only happen while using Fenix?

**Comment by agi90** [comment]
I haven't seen it from any other app.
