### ISSUE TITLE
FNX3-17064 ⁃ [Bug] "Send crash report" checkbox is ignored

### ISSUE THREAD

**Issue by dector** [mozilla-mobile/fenix#3508]
"Send crash report" checkbox in `CrashReporterFragment` is displayed but changes nothing. Probably should be removed from UI?

**Comment by abodea** [comment]
Verified as fixed on the latest RC build **`1.0.0-rc.2(Build #11700147 68.0.20190611143747) 6/19.`** with Samsung Galaxy Note 9(Android 8.1.0).
Please note that now the `check box` can be selected/deselected without problems.
