### ISSUE TITLE
FNX3-17065 ⁃ Create home screen component for multitasking

### ISSUE THREAD

**Issue by colintheshots** [mozilla-mobile/fenix#351]
Related to #98 and #239.

Open tabs in the current session should appear above past sessions on the home screen. The user should be able to select any open tab in the current session by picking it from the home screen. That tab should open in the browser and should not reload unless the OS has killed our app process for memory pressure or the site headers dictate that it should.

Another issue may address saving the state of the current scroll position, form fields, and restoring without reload after getting killed by the OS.

**Comment by pocmo** [comment]
In AC we offer:

* `browser-tabstray`+ `feature-tabs` for displaying tabs and related functionality. Please let us know if that is helpful and how we can support customization options (like for the awesomebar).

* `SessionStorage` from from `browser-session` can save/restore a snapshot of the SessionManager. It's what we use in the reference browser. `feature-session-bundling` can do the same but save multiple snapshots ("bundles") with a lifetime. @boek used that in the prototype for user testing.

**Comment by colintheshots** [comment]
Sorry, I think there's confusion around the word "component." I was referring to our architecture shared with Netflix around componentization. I wasn't referring to creating new A-C components.
