### ISSUE TITLE
[Bug] No magnifier with selecting content text on Android P

### ISSUE THREAD

**Issue by tetsuharuohzeki** [mozilla-mobile/fenix#3510]
## Steps to reproduce
1. Select some text in content in some page.
1. Move a text selection cursor by finger.

### Expected behavior
Display [a magnifier](https://developer.android.com/guide/topics/text/magnifier) on moving a text selection cursor.

### Actual behavior
No magnifier.

### Device information
* Android device: Pixel 3 (Android P)
* Fenix version: 1.0.1924 (Build #11661810, 68.0-20190611143747)

**Comment by ekager** [comment]
For reference, the magnifier in gmail app
![Screenshot_20191028-180801](https://user-images.githubusercontent.com/25442310/67729344-f402e680-f9ad-11e9-8270-a2d716bb7e49.png)

**Comment by boek** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1639087

**Comment by SS1113** [comment]
Please add this feature this is such a standard feature on Android nowadays it is supported by vast majority of applications because when selecting the text the thumb covers the text selection thus making it a lot harder to select upto the exact point.

**Comment by black7375** [comment]
This is Samsung Internet's selection.

- Prevent your fingers from covering text.
- Zoom in on the area you are changing to make sure you select even small letters precisely.
- There is a natural animation by increasing the size of the cursor used during selection.
![SamsungInternet-Selection](https://user-images.githubusercontent.com/25581533/95771828-431f5580-0cab-11eb-941a-43554587ce4d.gif)


### Who will benefit from it?
- Those who want to select precisely
- Those who need to select small letters
- a person with low vision

**Comment by cleoold** [comment]
Wow can't believe Android 12 is about to come and this backlogged feature that seems to be pretty standard has no any updates yet..

**Comment by kbrosnan** [comment]
This is a platform feature. The Gecko bug will track any progress.

**Comment by gitblogman** [comment]
why such ignorance on adding this feature?

**Comment by cadeyrn** [comment]
> why such ignorance on adding this feature?

There is a nine days young work in progress patch in the linked Bugzilla ticket for this feature and you think it's the perfect time to talk about "ignorance on adding this feature"?
