### ISSUE TITLE
[Bug] No longer able to go back multiple pages

### ISSUE THREAD

**Issue by mattcoz** [mozilla-mobile/fenix#3514]
Long pressing on the system back button or the back button in the menu would bring up your back/forward history in the old Firefox. This does not happen in Fenix so there is no way to go back multiple pages. A related problem is that the new Android Q will not have a back button to long press. I submitted an issue report about adding a "long press" gesture by holding, but maybe we would have better luck getting this feature if the Mozilla developers would ask for it.

https://issuetracker.google.com/issues/132434424

**Comment by kumarharsh** [comment]
Atleast in Android P, pressing the back button can also be configured to bring up any app's menu (3 dots). This worked in Firefox too. The menu has the back button too, and long pressing the back button in the menu brought up the navigation history earlier. Even that feature is not supported. Please bring this back!

**Comment by ekager** [comment]
This feature is already being planned as part of https://github.com/mozilla-mobile/fenix/issues/176
