### ISSUE TITLE
[Bug] Audio is really low

### ISSUE THREAD

**Issue by pwd-github** [mozilla-mobile/fenix#3517]
## Steps to reproduce
1. Go to https://voice.mozilla.org/en/listen
1. Press Play 

### Expected behavior
You're able to hear clips 

### Actual behavior
The volume of clips is really low and requires users to use headphones. 

### Device information
* Android device: Android 8, LG G8
* Fenix version: 1.0.1925 (Build #11680610 :lizard: 68.0-20190611143747)

**Comment by sblatz** [comment]
@pwd-github I think some of these voice inputs are just quieter than others. I just listened to a few and only one was quiet. Please re-open if you're still encountering this!
