### ISSUE TITLE
Delete a download

### ISSUE THREAD

**Issue by boek** [mozilla-mobile/fenix#352]
**Part of Meta: #4417**

### User Story
As a user, I want to be able to delete a downloaded file once I no longer need it, so I can have control over the content I choose to save on my phone.

### Acceptance Criteria
* [ ] I can select and delete a downloaded files
* [ ] I can delete all downloaded files

**Comment by nigelh747** [comment]
In my opinion this is a bug as the previous version of Firefox for Android always deleted all files downloaded in the session on quoting if the setting was enabled

**Comment by KrasnayaPloshchad** [comment]
The panel should provide at least one way to delete a file, such as long press the item or glide the item to screen edge.

**Comment by sflorean** [comment]
Verified as fixed on Nightly 11/5 with the following devices:
- Pixel 3 (Android 11)
- Samsung Note 10(Android 10)
- Huawei MediaPad M2	(Android 5.1.1)

**Comment by sflorean** [comment]
@kglazko Tested again and after downloading the files and delete them from the menu-downloads, the files are still displayed in the device's storage. Is this expected?

**Comment by KrasnayaPloshchad** [comment]
I can also seen the problem with X-plore.

**Comment by Amejia481** [comment]
> @kglazko Tested again and after downloading the files and delete them from the menu-downloads, the files are still displayed in the device's storage. Is this expected?

I think for this is expected behaviour, as we are doing the same on Firefox desktop, and other browsers follow the same pattern, downloads are only deleted from the apps but not from the file system :)
