### ISSUE TITLE
[Bug] Canceled pairing from the mobile device should update automatically on the desktop side

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#3520]
## Steps to reproduce
1. Scan pairing code from a desktop Firefox.
1. On the mobile device, tap cancel on the approval screen.
1. Check the desktop approval screen.
    1. Expected behavior
The desktop page should show a "Pairing not successful" message automatically.
    1. Actual behavior
The screen doesn't update automatically, only after a refresh.
    1. Device information

* Android device: Galaxy Note 8 (Android 9)
* Fenix version: 1.0.0 RC 1

**Comment by bifleming** [comment]
@vladikoff can you pls take a look and advise?

**Comment by kbrosnan** [comment]
Sync website issues should be filed at https://bugzilla.mozilla.org/enter_bug.cgi?product=Cloud%20Services

**Comment by vladikoff** [comment]
We shall keep an eye on this issue! thank you for letting me know!

**Comment by bifleming** [comment]
@vladikoff do you have an issue filed in Bugzilla for this?  Can we close this one?

**Comment by vladikoff** [comment]
@bifleming filed in https://github.com/mozilla/fxa/issues/1657

feel free to close this one 👍
