### ISSUE TITLE
FNX3-17074 ⁃ [Bug] In landscape mode, the site info panel isn't displayed entirely

### ISSUE THREAD

**Issue by softvision-miralobontiu** [mozilla-mobile/fenix#3521]
## Steps to reproduce
1. Open a page.
1. Turn your device in landscape mode.
1. Tap on the site's lock icon and observe.

### Expected behavior
The site info panel is displayed fully.

### Actual behavior
The site info panel is displayed partially, the user has to scroll it to see the information.
In portrait mode is displayed entirely.

### Device information
* Android device: Google Pixel (Android Q), Samsung Galaxy Tab A 6 (Android 5.1.1)
* Fenix version: 1.0.0-rc.1 (#11660216)

![2019](https://user-images.githubusercontent.com/40694158/59664973-b6e64680-91ba-11e9-8f14-1416625bc6b6.gif)UNITO-UNDERSCORE!06!UNITO-UNDERSCORE!18!

**Comment by vesta0** [comment]
We should fix this :)

**Comment by softvision-miralobontiu** [comment]
Verified as fixed on the latest Nightly build 190718 (#11990608) with Samsung Galaxy Tab A6 (Android 5.1.1), Sony Xperia Z5 Premium (Android 7.1.1), HTC 10 (Android 8), and Nexus 6P (Android 8.1).
