### ISSUE TITLE
FNX3-17075 ⁃ [Bug] User email not displayed on the reconnect to sync error

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#3522]
## Steps to reproduce
1. Login on 2 devices with the same account.
1. On one device, change the password.
1. On the other device, force sync.
1. Verify the error displayed: "reconnect to resume syncing".
    1. Expected behavior
The user email address is displayed in the error message.
https://github.com/mozilla-mobile/fenix/issues/2327#issuecomment-499247432
    1. Actual behavior
The email address is not displayed.
    1. Device information

* Android device: Note 8 (Android 9)
* Fenix version: 1.0.0 RC 1

**Comment by sblatz** [comment]
I think this may not be possible after we lose the user's email (it should show at first, but if they force quit or something similar the email will no longer be cached). Is that correct? @grigoryk

**Comment by jdragojevic** [comment]
@grigoryk   - cc @bifleming  - we believe our work on this is done in a-s 0.35.0.

**Comment by jonalmeida** [comment]
Removed good first bug since the solution isn't clear, and no longer making it so.

**Comment by vesta0** [comment]
@liuche I think is was already addressed by A-S. Feel free to add the `eng:qa:needed` label if there is no Fenix work required, otherwise it can go on the Prioritized bug backlog. Thanks!

**Comment by liuche** [comment]
Sounds good, let me see if this is already fixed w/ a qa-needed label.

**Comment by softvision-miralobontiu** [comment]
Verified as fixed on the latest Nightly build 190731 (#12120612) with Google Pixel 3 (Android 9), and Sony Xperia Z5 Premium (Android 7.1.1).
