### ISSUE TITLE
FNX3-17076 ⁃ [Bug] Yellow error banner on the Settings menu is not displayed on the homescreen menu

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#3523]
## Steps to reproduce
1. Login on 2 devices with the same account.
1. On one device, change the password.
1. On the other device, force sync.
1. On the app home screen, tap the 3 dots menu icon.
    1. Expected behavior
The settings menu has a yellow background, to signal an error.
    1. Actual behavior
The home menu doesn't have a yellow background around Settings. The page menu has it.
    1. Device information

* Android device: Galaxy Note 8 (Android 9)
* Fenix version: 1.0.0 RC 1

**Comment by bifleming** [comment]
@sblatz can you provide a little more info on why this might be a-s?

**Comment by sblatz** [comment]
Sorry, @bifleming I just meant this is related to Application Services sync it's a sync issue.

That being said, this was not part of the original mocks. The mocks only called for the sync settings error to appear in the browser menu.

@ryanfeeley do you want it to appear on our homescreen menu too?

<img width="350" alt="image" src="https://user-images.githubusercontent.com/4400286/61495682-84bd3580-a96e-11e9-8b55-10124f2d990b.png">


[Original ticket for reference](https://github.com/mozilla-mobile/fenix/issues/2327)

**Comment by bifleming** [comment]
@sblatz Janet thinks the app is providing the information, it just needs to get displayed. @rfk can you confirm that we want this on the homescreen menu?

**Comment by rfk** [comment]
> @rfk can you confirm that we want this on the homescreen menu?

I think there should be *some* visible indicator of error state at higher menu levels, to guide the user to the thing that needs repairing. For example if you get into a similar state in Desktop, it will show:

* A little yellow exlamation-mark on the hamburger menu, to let you know something is wrong
* A yellow highlight over the account item if you activate the hamburger menu
* And so-on

But I'm not the right person to dictate all the details; @ryanfeeley what's your take, should yellow error indicator appear somewhere in the screen [linked above](https://github.com/mozilla-mobile/fenix/issues/3523#issuecomment-513008943)?

**Comment by sblatz** [comment]
For what it's worth, this is very small engineering effort. And it seems reasonable for it to match the behavior shown in the browser screen.

**Comment by jdragojevic** [comment]
@vesta0 @bifleming  - based on conversation above, I think we should remove the a-s label from this bug.

**Comment by ekager** [comment]
It sounds like nothing is blocking this technically, correct @sblatz ? We can mark it as eng-ready it sounds like?

**Comment by sblatz** [comment]
Correct, this is eng:ready.

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on **Debug Build from Master 1.0.1947 (Build # 1) 📦: 23.0.0, 9b8e27603 🦎: 72.0a1-20191119043902 from 11/22** using the following devices:
• Google Pixel 3a XL (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

► Screenshot
![rsz_screenshot_20191122-142645](https://user-images.githubusercontent.com/51314259/69425872-6e682180-0d34-11ea-8c13-f687b181333b.png)
