### ISSUE TITLE
[Bug] Overwriting bookmark folders when syncing 2 devices

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#3525]
## Steps to reproduce
1. Login on desktop FF and Fenix on a mobile device.
1. On desktop, see all bookmarks. In the mobile folder, create a new sub-folder and move a bookmark in it.
1. On mobile, edit a bookmark, move it to a new folder.
1. Sync on desktop. 
1. Sync on mobile.
1. Verify the 2 folders.
    1. Expected behavior
The 2 folders contain their specific bookmarks.
    1. Actual behavior
The last synced folder (the one created on mobile and synced after desktop) is empty, the bookmark from it is moved to the root folder.
The first synced folder (the one created on desktop in this case) contains the bookmark.
    1. Device information

* Android device: Note 8 (Android 9)
*Desktop: FF 67.0.2, 6b bit, Win10
* Fenix version: 1.0.0 RC 1

**Comment by linacambridge** [comment]
Thanks, @sv-ohorvath! Would you mind enabling [trace logging on Desktop](https://wiki.mozilla.org/CloudServices/Sync/File_a_desktop_bug#Get_detailed_Sync_logs) and capturing a log from `about:sync-log`?

**Comment by sv-ohorvath** [comment]
@linacambridge Here are the logs from today:
[aboutsync-logfiles.zip](https://github.com/mozilla-mobile/fenix/files/3305015/aboutsync-logfiles.zip)

**Comment by vesta0** [comment]
@colintheshots thoughts on why this is happening?

**Comment by colintheshots** [comment]
I would need to pore over the logs, but a decent guess is it's likely to be an order of operations issue. The root folder is often a good default if a destination folder doesn't exist yet.
