### ISSUE TITLE
FNX3-17080 ⁃ [Bug] There is no limit of characters on the "Collections Name" option

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/fenix#3527]
## Steps to reproduce
1. Launch Fenix.
1. Open more tabs.
1. Create a collection.
1. When selecting the name, add as many characters as you want.
    1. Expected behavior
There should be a character limit on the `Collection name` option.
    1. Actual behavior
There is no limit when adding characters on the `Collection name`.
    1. Device information

* Android device: **`Samsung Galaxy Note 9(Android 8.1.0)`**
* Fenix version: **`6/18` 1.0.0-rc.1** 
* [Video](https://drive.google.com/file/d/1NwgmOf8DaScPDPpIaGqyvLwIurdBDiti/view?usp=sharing)
![Screenshot](https://user-images.githubusercontent.com/42831109/59682859-bb712600-91df-11e9-9c74-51df131b1b78.jpg)UNITO-UNDERSCORE!20190618-153420!UNITO-UNDERSCORE!Firefox Preview!

**Comment by vmbaicu** [comment]
Set the max length to 128 characters, seems a bit generic but it's better than none
