### ISSUE TITLE
[Bug] Cannot login into slack app using Fenix

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#3528]
## Steps to reproduce
Regression of https://github.com/mozilla-mobile/fenix/issues/1213

### Expected behavior
Return to slack and log in.

### Actual behavior
Fenix gets stuck on a white page after dual auth is completed.

### Device information
* Android device: Galaxy Note 8 (Android 9), HTC 10 (Android 8)
* Fenix version: 1.0.0 RC 1

**Comment by vesta0** [comment]
@kbrosnan was this caused because we reverted the app intent work?

**Comment by kbrosnan** [comment]
Yes. This is a dupe of #1213. The code that was the fix was backed out. Should we reopen the older bug and move it out of Done and Sprint it was completed?

**Comment by vesta0** [comment]
Yes please. @bifleming ^^

**Comment by sblatz** [comment]
Closing as dupe of #1213.
