### ISSUE TITLE
[UX] Animations for Multitasking tasks

### ISSUE THREAD

**Issue by colintheshots** [mozilla-mobile/fenix#353]
There should be standard animations for the following multitasking tasks:

* [ ] Opening a new tab
* [ ] Closing a tab
* [ ] Opening an existing tab from the home screen
* [ ] Saving an existing session

**Comment by bbinto** [comment]
@lime124 to talk to Amy to get this in for the next sprint (4)

**Comment by AmyYLee** [comment]
@bbinto the animations here is already covered in https://github.com/mozilla-mobile/fenix/issues/167

Do we still need this issue?
