### ISSUE TITLE
FNX3-17084 ⁃ [Bug] First page in a custom tab, app not running, text selection doesn't work

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#3530]
## Steps to reproduce
1. Kill Fenix.
1. Open gmail, or other app. Open a page in a custom tab.
1. Lon-tap some text to select it.
    1. Expected behavior
The text selection toolbar is displayed.
    1. Actual behavior
The text can be selected but there's no toolbar.
![20190618](https://user-images.githubusercontent.com/4037709/59693180-29711980-91ef-11e9-97f5-26cfaca30e08.gif)UNITO-UNDERSCORE!171457!

### Device information
* Android device: Note 8 (Android 9), HTC 10 (Android 8)
* Fenix version: 1.0.0 RC 1

**Comment by WhoIsAndi** [comment]
Hi, I've encountered the same issue  on **Fenix 1.0.0-rc.2 (Build #11700147)** using two tablets:
• Lenovo TB3-850M (Android 6)
• Samsung Galaxy Tab A (Android 7)

#### :x: In addition to the text selection issue, I wasn't able to either paste text in custom tabs.

**Comment by sblatz** [comment]
@kbrosnan is there a GV bug filed for this?

**Comment by ekager** [comment]
Can't see this on master on Pixel 3, adding QA needed

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **Nightly Build #12130027 from 1/8** using the following devices:
• Google Pixel 3a (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)
