### ISSUE TITLE
[Bug] crash fenix

### ISSUE THREAD

**Issue by franco27** [mozilla-mobile/fenix#3533]
URL: None

Browser / Version: fenix 1.0.1924 (Build #11651812 :lizard: 68.0-20190611143747)
Operating System: Android 7.0
Tested Another Browser: Yes

with Firefox Preview /fenix 

this problem is still not solved. 

with the current version of Fenix 

1) when I close the tabs 
2) during the display of the "cancelled" button 
3) then successively, I click twice on the "back" button on the smartphone bar, to close the web browser 

4) there is a Fenix crash and an error report is displayed. (I sent this error report)

**Comment by franco27** [comment]
sorry for this multiple bug report, every time I tried to send it, I had this error message "405 Not Allowed"

**Comment by sv-ohorvath** [comment]
No problem, it's a GitHub issue. I closed the dupes.

**Comment by kbrosnan** [comment]
@franco27 If you have a computer and some free time it would be a great help to get the logcat debugging information. The steps to get the information we need is at https://github.com/mozilla-mobile/fenix/wiki/Logging-Crash-Information

If you have any questions or run into any problems with the steps reply to this issue.

**Comment by franco27** [comment]
With the latest version, there is no longer this problem. 
It's been fixed. Thank you.

**Comment by franco27** [comment]
kbrosnan thank
