### ISSUE TITLE
FNX3-17090 ⁃ [Bug] tabs are systematically restored

### ISSUE THREAD

**Issue by franco27** [mozilla-mobile/fenix#3537]
**URL**: None

**Browser / Version**: fenix 1.0.1924 (Build #11651812 :lizard: 68.0-20190611143747)
**Operating System**: Android 7.0
**Tested Another Browser**: Yes

**Problem type**: Something else
**Description**: the tabs are systematically restored
**Steps to Reproduce**:

1. tabs are open (several open tabs) 
1. via the menu, I request the closure of all tabs with a single click 
1. all tabs are closed (so far everything is OK) 
1. if I restart the application, or if I switch to the tab window or if I go to a web page and return to the tab window: the previously closed tabs reappear. 

this problem does not occur when closing the tabs one by one. 
(by not using the "close all tabs" menu).

**Comment by ekager** [comment]
Hi @franco27 ! Thanks for filing this. I'm not sure if you're using the most recent version. Could you try to update and let me know if you're still seeing this?

**Comment by franco27** [comment]
with the latest version, it's solved! I can not reproduce this problem anymore.
thanks @ekager

**Comment by yoasif** [comment]
@ekager close this again?
