### ISSUE TITLE
[Bug] Scrolling sometimes reacts late on touch input

### ISSUE THREAD

**Issue by Wasseranomalie** [mozilla-mobile/fenix#3546]
## Steps to reproduce
* Open https://github.com/mozilla-mobile/fenix/issues
* Switch to desktop version
* Scroll up and down the page at intervals of a few seconds

### Expected behavior
Scrolling happens immediately

### Actual behavior
Page scrolls with noticeable delay

https://www.youtube.com/watch?v=Pf5xt_fGQHE

### Device information
* Android device: Nexus 5X, Android 8.1
* Fenix version: 1.0.1925 (Build #11691815)

**Comment by sblatz** [comment]
@Wasseranomalie are you still able to reproduce this?

**Comment by Wasseranomalie** [comment]
@sblatz yes, it is still happening on Nightly 190719 (Build #12001827)

**Comment by kbrosnan** [comment]
Scrolling in content would be a GeckoView bug. @cpeterso do we have anything like this currently?

**Comment by kbrosnan** [comment]
@Wasseranomalie if you have some more time to investigate this are you able to reproduce the scrolling problems on [Reference Browser](https://github.com/mozilla-mobile/reference-browser/#test-channel-on-google-play-store)?

**Comment by Wasseranomalie** [comment]
Yes, it is also happening there.

Reference Browser 1.0.1929 (Build #12021213)

On old Firefox (nightly) there is no input lag, so it seems to be a new issue when using geckoview.

**Comment by cpeterso** [comment]
Thanks for reporting this bug, @Wasseranomalie. This does sound like a GeckoView problem, so I filed a GeckoView bug report: https://bugzilla.mozilla.org/show_bug.cgi?id=1567977

**Comment by Wasseranomalie** [comment]
Yes, I can still reproduce it. Unfortunately I don't have another available for further testing.

The only step to take is to request the desktop version of the website. It seems to become more frequent when zooming out completely to see the whole page width.

Another site I found was the desktop-version of YouTube (and if not done automatically zoomed out completely). There this scrolling problem appears on every try on my device, so maybe you have more luck there to reproduce this issue.

Tested on:
Firefox Preview:       Nightly 190827 06:04 (Build #12390613)
Reference Browser:  1.0.1935 (Build #12391232)

**Comment by Wasseranomalie** [comment]
On Firefox for Android 68 this issue only happens very rarely and when it happens the delay is very short. Scrolling is far worse on Firefox Preview with a delay of up to one second after touching the display (vs. maybe <0.2 seconds on Firefox for Android 68).
I've made another video showing this issue: https://youtu.be/UcqER9irdOo (the delay does not become shorter after all thumbnails have been loaded)
You can also see at the end of the video that after scrolling has started, there is no delay when changing direction anymore so there is just a huge delay when you want to start scrolling.

**Comment by cpeterso** [comment]
> I've made another video showing this issue: https://youtu.be/UcqER9irdOo (the delay does not become shorter after all thumbnails have been loaded)

Thanks for the screen capture. It clearly shows the slow response when you start scrolling.

**Comment by PranavBhattarai** [comment]
Mine is worse. 
This doesn't happen all the time. But I have noticed the **browser lag** while scrolling the web page.

I have also recorded screencast video as a proof when I was using m.facebook.com to see more stupid posts, I scrolled.

Firefox version: 4.3.0 (latest to the time of the comment).
Device: Oneplus 5
OS: Oxygen OS Android 9

Hope this helps.
