### ISSUE TITLE
FNX3-17096 ⁃ [Bug] The "x" from Send and Share page is barely visible (HTC device specific?)

### ISSUE THREAD

**Issue by softvision-miralobontiu** [mozilla-mobile/fenix#3547]
## Steps to reproduce
1. Open a webpage.
1. From QAB select Share.
1. Observe the closing "x" button from the Send and Share page.

### Expected behavior
The "x" should be visible.

### Actual behavior
The "x" is black and barely visible.

### Device information
* Android device: Google Pixel (Android Q), Lenovo TB3-850M (Android 6), Huawei MediaPad M3 Lite 10 (Android 7.0)
* Fenix version: 1.0.0-rc.2 (#11700147)

![Screenshot](https://user-images.githubusercontent.com/40694158/59749585-f7f75d00-9285-11e9-8f64-7cc830cb7143.png)UNITO-UNDERSCORE!20190619-112630!

**Comment by sblatz** [comment]
The "x" should match the primary text color of the theme.

**Comment by heyheydanhey** [comment]
Could _not_ reproduce this in either Light, Dark or Set by Battery Saver theme modes of Firefox Preview 1.0.0 (Build #11721514). Is it still an issue?

**Comment by sblatz** [comment]
Marking this as QA needed to see if it's still reproducible.

**Comment by Geojackson** [comment]
Greatly appreciate

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on Fenix `#11791805 from 28/6` for both light and dark themes using the following devices:
• Google Pixel 3XL (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7.0)
• Samsung Galaxy J7 (Android 6.0.1)
• Sony Xperia Z3 (Android 5.1.1)

**Comment by softvision-miralobontiu** [comment]
It is not fixed on HTC Desire 820 (Android 6.0.1). Tested on 7/2 build.

![Screenshot_20190702-172130](https://user-images.githubusercontent.com/40694158/60521035-26961e80-9cef-11e9-8c31-b0120bd0087f.png)

**Comment by ekager** [comment]
I tried a fix that more clearly tints the button, but I don't have an HTC device to test the fix on. Added QA needed label :)

**Comment by softvision-miralobontiu** [comment]
Verified as fixed on HTC Desire 820 (Android 6.0.1), on the latest build 7/9.

![Screenshot_20190709-110908](https://user-images.githubusercontent.com/40694158/60870819-40c58480-a23a-11e9-90fc-36ca524ac67a.png)
