### ISSUE TITLE
FNX3-17097 ⁃ [Bug]The 'X' button from Open Tabs section is not entirely visible

### ISSUE THREAD

**Issue by sv-sdeiac** [mozilla-mobile/fenix#3548]
## Steps to reproduce
1. Open Firefox Preview;
1. Open a page;
1. Press the tabs button to view the tabs;
1. Observe the 'Open Tabs' section.

### Expected behavior
There are no layout issues.

### Actual behavior
The 'X' button to close a tab is bigger and is not entirely visible.

### Device information
* Android device: Xiaomi MiPad 2 (Android 5.1) and Samsung Galaxy Tab A6 (Android 5.1);
* Fenix version: 1.0.0-rc.2
* Notes:
~~Not reproducible on Lenovo TB3~~850M (Android 6), Pixel 3XL (android 9), Samsung Galaxy Tab A (Android 7) and Huawei MediaPad M3 Lite 10 (Android 7.0).
-Screenshot: 
![Screenshot](https://user-images.githubusercontent.com/40264165/59752054-46a6f600-928a-11e9-8d6e-c8a986dbe05e.png)UNITO-UNDERSCORE!27!

**Comment by mauryat** [comment]
@sblatz , can I work on this?

**Comment by sblatz** [comment]
@mauryat looks like we [have a PR open for this already](https://github.com/mozilla-mobile/fenix/pull/3801). I'd recommend looking at another issue :)

**Comment by sblatz** [comment]
Updated: 

<img width="350" alt="image" src="https://user-images.githubusercontent.com/4400286/62148143-fe79eb00-b2ad-11e9-86bf-cfe316345675.png">

**Comment by sv-ohorvath** [comment]
Verified as fixed on nightly 190731, devices: Samsung Galaxy Tab A 6 (Android 5.1.1), Sony Xperia Z2 (Android 6.0.1), Xiaomi MiPad 2 (Android 5.1).
