### ISSUE TITLE
FNX3-17100 ⁃ [Bug] Tapping a bookmark/history from Library doesn't open it in a new tab

### ISSUE THREAD

**Issue by softvision-miralobontiu** [mozilla-mobile/fenix#3551]
## Steps to reproduce
1. Bookmark some pages.
1. Go to Settings - Your Library - Bookmarks and tap on a bookmarked page.

### Expected behavior
The page from step 2 should open in a new tab, according to [#1012](https://github.com/mozilla-mobile/fenix/issues/1012#issuecomment-479608509) .

### Actual behavior
The page from step 2 is not loading in a new tab.
The same behavior is encountered with History.

### Device information
* Android device: all
* Fenix version: 1.0.0-rc.2 (#11700147)

**Comment by vesta0** [comment]
The expected behaviour should be to open bookmark/history in a new tab. We discussed and decided on this a while back.

I am hesitant to make any new behaviour change now and introduce potential new bugs but let's do this in the next sprint.

**Comment by softvision-miralobontiu** [comment]
Verified as fixed on the latest Nightly build #11840608 with Samsung Galaxy S8 (Android 9), HTC Desire 820 (Android 6.0.1), and Huawei Honor 8 (Android 7).
