### ISSUE TITLE
FNX3-17101 ⁃ [Bug] Content crash reports unsubmitted in about:crashes

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#3552]
## Steps to reproduce
1. Open about:crashcontent.
1. Select the "send crash" checkbox. Restart tab.
    1. Expected behavior
The report is sent to https://crash-stats.mozilla.com
    1. Actual behavior
The report is unsubmitted in about:crashes. Tap submit there and then it will appear in https://crash-stats.mozilla.com

*about:crashparent crashes are submitted automatically.

### Device information
* Android device: Galaxy S8 (Android 9)
* Fenix version: 1.0.0. RC 2

**Comment by vesta0** [comment]
@sarentz FYI

**Comment by sblatz** [comment]
I thought about:crashes was not working properly and we were planning on removing the about page🤔 I think we removed them in a-c.

**Comment by sv-ohorvath** [comment]
The reports from about:crashcontent don't go to https://crash-stats.mozilla.com automatically. That's how I ended up checking about:crashes, to verify if they appear somewhere at least.

**Comment by sblatz** [comment]
This seems critical if users are actually unable to report crashes.

**Comment by sarentz** [comment]
We do get plenty content crashes reported so I think it is just `about:crashcontent` not working.

**Comment by dbolter** [comment]
Note this issue appears to be pertaining to about:crashes, which is useful for triaging dogfooder crashes. @snorp is this a GV bug?

**Comment by snorp** [comment]
`about:crashes` is not accurate. We should probably just remove it.

**Comment by snorp** [comment]
I should add: crash reporting is done at the app level, so we can't easily make `about:crashes` work. Some other `about:crashes`-like system in a-c would be great.

**Comment by st3fan** [comment]
Why don't we just turn this into something in the Settings? That is also much more discoverable. Does mean we need to write some UI though, so this is not trivial and should be planned as a new feature.

**Comment by pocmo** [comment]
A replacement for `about:crashes` landed in Fenix and is available via "Settings > About > Crashes". For now it also opens if you type `about:crashes` into the toolbar (but not for other ways of navigating to that URL).
