### ISSUE TITLE
FNX3-17103 ⁃ [Bug] When selecting multiple pages from History, unselected icons go blank

### ISSUE THREAD

**Issue by softvision-miralobontiu** [mozilla-mobile/fenix#3554]
## Steps to reproduce
1. Make sure you have some history.
1. Go to Settings - Your Library - History and select multiple pages.

### Expected behavior
The unselected icons remain as they were.

### Actual behavior
The unselected icons go blank.

### Device information
* Android device: all
* Fenix version: RC 1.0.0-rc.2 (#11700147)

![history](https://user-images.githubusercontent.com/40694158/59771877-571f9680-92b3-11e9-9dd9-7286055b1f06.gif)UNITO-UNDERSCORE!Trim!

**Comment by vesta0** [comment]
@AmyYLee is this a bug or working as designed?

**Comment by AmyYLee** [comment]
> @AmyYLee is this a bug or working as designed?

@topotropic Had worked on this. Nicole can you confirm?

**Comment by ekager** [comment]
Sorry @topotropic just assigning you so you see this! :)

**Comment by topotropic** [comment]
In bookmarks we keep the icons, so we should also keep them for history multi-select. Thanks!

**Comment by ekager** [comment]
Thanks!

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest Nightly Build **#11970610 from 16/7** using the following devices:
• Google Pixel 3a (Android 9)
• Samsung GalaxyS8+ (Android 8)
• Samsung Galaxy S7 (android 7)
• Samsung Galaxy S6 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

► VIdeo from Google Pixel 3a
![20190716_125056](https://user-images.githubusercontent.com/51314259/61291438-332e7280-a7d7-11e9-8e57-da4683fc8b67.gif)
