### ISSUE TITLE
FNX3-17104 ⁃ [Bug] Awesome bar(Scan and Shortcuts) disappear when swiping on the screen and reopening the keyboard

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/fenix#3555]
## Steps to reproduce
1. Launch Fenix.
1. Tap on search bar.
1. On the white space swipe with one finger(or tap on back button and then again on search bar).

### Expected behavior
The keyboard and awesome bar(scan and shortcuts) disappear.

### Actual behavior
The keyboard disappear but the awesome bar remains on the screen and when opening the keyboard again, the awesome bar is not displayed above the keyboard.

### Device information
* Android device: **`Samsung Galaxy Note 9(Android 8.1.0)`**
* Fenix version: **6/19 1.0.0-rc.2** 
* [Video](https://drive.google.com/file/d/1lYQFdd3pYPgOJoo_Pinp54uX-9PiPXx1/view?usp=sharing)

**Comment by sblatz** [comment]
Related: https://github.com/mozilla-mobile/fenix/issues/3690

**Comment by abodea** [comment]
Verified as fixed on the latest build **`6/27`** with **`Samsung Galaxy S7(Android 7), Huawei Mate 20 Lite(Android 8.1.0), Google Pixel 3 XL (Android 9), Google Pixel XL(Android Q Beta 4).`**
Please note that the fix from #3690 also fixed this issue. Everything works as expected.
