### ISSUE TITLE
FNX3-17109 ⁃ Allow the user to remove some, or all of their history

### ISSUE THREAD

**Issue by boek** [mozilla-mobile/fenix#356]
As a user, I want Fenix to delete items from my browsing history so that these items are not discoverable later on this browser.

### Acceptance criteria
-I can see a list of URLs I’ve visited in the history section of the Fenix library and delete one site from it. 
-I can see a list of every URL I’ve visited in the history section of the Fenix library and delete the entire list at once.
-I can leave the library and return to the library and I will not see the URL
-I do not see this URL when I begin typing an exact match on part of the URL in the awesome bar. 
-If I delete this URL from my history while the session window in which I accessed it originally is still active, I will not be able to access the URL using the browser’s back button.

**Comment by bbinto** [comment]
A/C team needs to build this first

**Comment by pocmo** [comment]
Depends on:
* https://github.com/mozilla-mobile/android-components/issues/1373
* https://github.com/mozilla/application-services/issues/621

**Comment by sv-ohorvath** [comment]
Verified that delete history works. Logged new issues separately. Closing this ticket.
