### ISSUE TITLE
Avoid calling `notifyDataSetChanged` in RecyclerView adapters

### ISSUE THREAD

**Issue by NotWoods** [mozilla-mobile/fenix#3563]
`notifyDataSetChanged` tells the recycler view that every single item should be updated. However, its usually called when only 1 item has changed. Our `RecyclerView.Adapter`s should be changed to only notify that the changed items should be updated.

The easiest way to do this is to just use [`ListAdapter`](https://developer.android.com/reference/kotlin/androidx/recyclerview/widget/ListAdapter) which does diffing automatically.

**Comment by sblatz** [comment]
This would be really nice to have but is probably not worth the ROI for us, would be great for a contributor :)

**Comment by dector** [comment]
I can work on this issue. Suppose that [DiffUtils](https://developer.android.com/reference/android/support/v7/util/DiffUtil) is what we actually need here.

**Comment by NotWoods** [comment]
Yeah, either using DiffUtils or ListAdapter (which uses DiffUtils automatically) will work 😄

**Comment by J6ey** [comment]
Keep in mind ListAdapter is deprecated. To notify a particular item has changed use  `notifyItemChanged` or `notifyItemRangeChanged`

**Comment by NotWoods** [comment]
I was referring to the (confusingly named) AndroidX [`ListAdapter`](https://developer.android.com/reference/kotlin/androidx/recyclerview/widget/ListAdapter), which builds ontop of the `RecyclerView.Adapter` and isn't deprecated.

**Comment by NotWoods** [comment]
Closing as we've addressed most of the cases, and the remaining ones aren't called frequently.
