### ISSUE TITLE
[Bug] Fenix hanging after autocompleting to Google News

### ISSUE THREAD

**Issue by Sdaswani** [mozilla-mobile/fenix#3566]
## Steps to reproduce
1) Open Fenix
2) Start opening a URL
3) start typing news.google.com

### Expected behavior
Fenix doesn't hang

### Actual behavior
Fenix hangs the F out 
see first video here https://photos.app.goo.gl/D4HevKvQESbLBfAy7

### Device information
* Android device: Samsung Galaxy S8 with Oreo
* Fenix version: a few nights ago

**Comment by kbrosnan** [comment]
Does this still happen after the system update completed?

**Comment by Sdaswani** [comment]
> Does this still happen after the system update completed?

will try @kbrosnan stay tuned.

**Comment by Sdaswani** [comment]
couldn't repro @kbrosnan will let you know if i see it again.
