### ISSUE TITLE
[Bug] SessionControlAdapter should reuse CollectionViewHolder

### ISSUE THREAD

**Issue by NotWoods** [mozilla-mobile/fenix#3567]
## Steps to reproduce
Expand and collapse a collection on the home fragment.

### Expected behavior
The collection should internally use the same view holder, which tells the animator to not run any animation since the item ID didn't change.

### Actual behavior
The collection uses a different view holder, causing a fade-in/fade-out animation when the collection is expanded and collapsed.

**Comment by sblatz** [comment]
If we implement this I believe we will lose the "swipe to delete" behavior that we currently get for free. Any ideas on how to get around that, @NotWoods?

**Comment by NotWoods** [comment]
There is a workaround with `ItemAnimator`, but I don't think we need different view holders for swipe to delete.
