### ISSUE TITLE
FNX3-17117 ⁃ [Bug] QR code scanner prompt has the wrong colors in light theme

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#3568]
## Steps to reproduce
1. On light theme, turn on the QR code scanner.
1. Scan the code, observe the prompt displayed.
    1. Expected behavior
The prompt has a light theme: light background, dark text. No screen overlay.
    1. Actual behavior
There's a gray screen overlay, the prompt is dark and the text barely visible.
![Screenshot](https://user-images.githubusercontent.com/4037709/59830051-7b2cb780-9347-11e9-9f8c-79ce2fd4c741.png)UNITO-UNDERSCORE!20190620-100924!

### Device information
* Android device: HTC 10 (Android 8), S8 (Android 9), Huawei MediaPad M3 Lite 10 (Android 7.0)
* Fenix version: 1.0.0-rc2

**Comment by AndiAJ** [comment]
I was able to reproduce this issue using a Samsung S8+ (Android 8) on the latest Nightly Build **`#11930609 from 12/7`**.

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly Build #11960610`** using the following devices:
• Google Pixel 3a (Android 9)
• Samsung Galaxy S8+(Android 8)
• Samsung Galaxy S7 (Android 7)
• Huawei Media Pad M3 Lite 10 (Android 7)
• Samsung Galaxy S6 (Android 6.0.1)
