### ISSUE TITLE
FNX3-17118 ⁃ [Bug] Dark mode: Barely visible folder icon in bookmark edit mode

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#3569]
## Steps to reproduce
1. Set the app to dark mode.
1. Edit a bookmark. Obverse the parent folder icon.
1. Create a new folder, observe the parent folder icon.
    1. Expected behavior
The icon is visible in dark mode.
    1. Actual behavior
The dark purple icon is barely visible.
![Screenshot](https://user-images.githubusercontent.com/4037709/59830294-01e19480-9348-11e9-843b-e08e7595a454.png)UNITO-UNDERSCORE!20190620-101126!
    1. Device information

* Android device: HTC 10 (Android 8), S8 (Android 9).
* Fenix version: 1.0.0-rc2

**Comment by softvision-miralobontiu** [comment]
I will reopen this issue because I was able to reproduce it again on Huawei P9 Lite (Android 6), and on Nexus 5 (Android 6.0.1), with the latest Nightly build 7/26 (#12070609).

**Comment by lime124** [comment]
@ekager is there something ux needs to give you or is it a regression that needs to be fixed? removing ux label. ping amy if you need something. thanks!

**Comment by ekager** [comment]
This seems to be a regression so we don't need anything from UX

**Comment by ekager** [comment]
@softvision-miralobontiu are you still seeing this on your device?
