### ISSUE TITLE
Create the history management UI

### ISSUE THREAD

**Issue by boek** [mozilla-mobile/fenix#357]

**Comment by sblatz** [comment]
This is blocked on #355.

**Comment by boek** [comment]
Questions for UX:

Is the delete button always visible?
Should we have a separate management UI? (To give a user the ability to select multiple items to delete, delete all etc)
Is there more than a "delete" item in the popover menu for a single history item?

cc: @shorlander @topotropic

**Comment by sblatz** [comment]
Does this include the [delete session](https://user-images.githubusercontent.com/51007/51957894-53c97100-24b2-11e9-8a3a-66f07f59b9d4.png) button found in private browsing or is that a different issue?

**Comment by topotropic** [comment]
@boek 

> * Is the delete button always visible?
Yes

> * Should we have a separate management UI? (To give a user the ability to select multiple items to delete, delete all etc)
- Yes – on long press we go into edit mode and people can select multiple items (https://material.io/design/interaction/selection.html#item-selection) 

> * Is there more than a "delete" item in the popover menu for a single history item?
- Good question, not at the moment, so we could also get rid of the menu and display the "x" right there

**Comment by boek** [comment]
@topotropic 
Awesome, thanks!

A couple of follow up questions:
- Should the delete button scroll with the history? Or be pinned to the top
- I'm actually ok with hiding a destructive action behind the menu. If we were to have just an "x" button would we want a confirmation dialog?

**Comment by topotropic** [comment]
> @topotropic
> Awesome, thanks!
> 
> A couple of follow up questions:
> 
>     * Should the delete button scroll with the history? Or be pinned to the top

scroll with the history

>     * I'm actually ok with hiding a destructive action behind the menu. If we were to have just an "x" button would we want a confirmation dialog?

let's go with hiding then

Thanks @boek
