### ISSUE TITLE
[Bug][a11y] The Accessibility TalkBack was disabled after a login

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/fenix#3573]
## Prerequisites
You have Talkback option enabled from your Android settings.

## Steps to reproduce
1. Launch Fenix.
1. Login with valid credentials.
1. Reach homescreen and wait until the sync is done

### Expected behavior
The home screen is displayed and **`Accessibility Talkback`** is still enabled and functional.

### Actual behavior
The **`Accessibility Talkback`** was disabled on Fenix after login.

### Device information
* Android device: **`Samsung Galaxy Note 9(Android 8.1.0).`**
* Fenix version: **`6/19 1.0.0-rc.2`** 
    1. Notes
* Please note that I was able to reproduce this issue only once and I couldn't catch any logcat or video.

**Comment by ekager** [comment]
Hm I am tempted to close this because you have only seen it once and that seems like a system bug possibly? I am going to close but feel free to reopen if you have seen it again or strongly disagree
