### ISSUE TITLE
FNX3-17125 ⁃ [Bug][a11y] There is no scroll functionality on the Bookmarks and History with Talkback

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/fenix#3575]
## Prerequisites
You have Talkback option enabled from your Android settings.

## Steps to reproduce
1. Launch Fenix.
1. Access the **`Bookmarks or History.`**
1. While having a lot of content on those two sections.
1. Swipe on screen to the right for changing the Talkback position until reaching the top or bottom of any of **`Bookmark or History`.**

### Expected behavior
The **`Bookmark or History`.** sections can be scrolled up and down if there are more elements on the section.

### Actual behavior
If there are more bookmarks of websites in those section when reaching the last element from the screen, the sections wont scroll down or up for next elements.

### Device information
* Android device: **`Samsung Galaxy Note 9(Android 8.1.0).`**
* Fenix version: **`6/19 1.0.0-rc.2`** 
    1. Notes
* [Video](https://drive.google.com/file/d/1TehUeD4SlcF3aG8l3z-9rsVNpReDFXtR/view?usp=sharing)
Please note that at the end of the video I scrolled manually in order to reach the top and show that those elements can be selected.

**Comment by ekager** [comment]
Let's check if this is still an issue, these layouts have been updated recently

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **Nightly Build #190724 from 24/7** using the following devices:
• Googe Pixel 3a (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy Note 9 (Android 8.1.0)

►History
![20190724_143302](https://user-images.githubusercontent.com/51314259/61790810-e410bf00-ae20-11e9-9be8-69bc692ae5a5.gif)
►Bookmarks
![20190724_143334](https://user-images.githubusercontent.com/51314259/61790716-a318aa80-ae20-11e9-811c-b228ee0bd3b6.gif)
