### ISSUE TITLE
[Bug] There is no error returned/displayed when reaching the maximum characters allowed on the Device Name option

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/fenix#3579]
## Steps to reproduce
1. Launch Fenix.
1. Login with valid credentials.
1. Select and access `Device Name` option.
1. Write until reaching the maximum characters allowed(128).
    1. Expected behavior
When reaching the limit of maximum characters allowed there should be displayed an error informing the user that he reached the maximum characters allowed. 
    1. Actual behavior
There is no error displayed when reaching the maximum characters allowed,
    1. Device information

* Android device: **`Samsung Galaxy Note 9(Android 8.1.0).`**
* Fenix version: **`6/19 1.0.0-rc.2`** 
    1. Notes
![Screenshot](https://user-images.githubusercontent.com/42831109/59840826-d36db480-935b-11e9-9f43-48f569286da1.jpg)UNITO-UNDERSCORE!20190620-125807!UNITO-UNDERSCORE!Firefox Preview!

**Comment by ValentinTimisica** [comment]
Hi,

I investigated and there is indeed a limit of 128 characters, but no error message when reaching the limit. Here we need the help of UX to tell us the error message we need to display.

**Comment by lime124** [comment]
@ValentinTimisica two questions - 1) is there a reason there is a limit? 2) can we show a character counter instead of an error message?

**Comment by ValentinTimisica** [comment]
1) Here is the task that led to this change -> #3388
2) The current API that we are using ([EditTextPreference](https://github.com/mozilla-mobile/fenix/blob/532e5313e91b86632e0eac624d6b5964a6c1a65b/app/src/main/res/xml/account_settings_preferences.xml#L27)) does not support this feature. To obtain this functionality a refactorization of the code is required.

**Comment by lime124** [comment]
The preferred method would be to warn the person before running in to a limit (e.g. character count). But I don't know how much effort the refactor would be. 

Would you be able to provide us with some options (e.g. char count, error msg, something else?) that are possible and how much effort it would take and we can take a look and provide feedback on direction? Thanks so much!

**Comment by ValentinTimisica** [comment]
The possibilities that I think of are the following:

1) `Show a Toast` when this dialog first appear to the user referring to the max char count that we support. This has the big drawback that we cannot expect the user to count the characters to know when he will hit the limit. Trivial to implement.
2) `Show a Snackbar` when the char limit is reached . This might be a better solution, the drawback would be that the user has no way of knowing beforehand. Trivial to implement.
3) `Show a char counter in the dialog`. This is probably the best solution but this would require us to implement our own custom view which I expect that would entail the work of one engineer over 4-5 days.

**Comment by lime124** [comment]
Thanks for the info @ValentinTimisica. While I think the best experience is the character counter, I don't think this bit of UI warrants that much effort. I also think this is not going to be a super common thing people will run into and I don't love the idea of custom view for this.

I would advise #2 but would love for @mheubusch to jump in to confirm and provide thoughts on the string. Thanks!

**Comment by mheubusch** [comment]
So, I don't think we need an error message as the system prevents the user from making the error, ie they can't type more than 128 characters and then submit and have it fail.
