### ISSUE TITLE
FNX3-17132 ⁃ [Bug]The 'Open tabs' button from the Colection 3dots menu doesn't work after deleting all tabs

### ISSUE THREAD

**Issue by sv-sdeiac** [mozilla-mobile/fenix#3581]
## Steps to reproduce
1. Open Firefox Preview;
1. Tap on 3dots menu from the collection line;
1. Choose 'Open Tabs'.

### Expected behavior
The tabs are opened without any issue.

### Actual behavior
The 'Open Tabs' button doesn't work from the first try.

### Device information
* Android device: OnePlus 5T (Android 9) and Xiaomi MiPad 2 (Android 5.1) - x86
* Fenix version: 1.0.0-rc.2
*Notes:
-Reproducible 4/5 tries;
-video with the issue:
![20190620](https://user-images.githubusercontent.com/40264165/59834393-9d770300-9350-11e9-868c-e7799d437f97.gif)UNITO-UNDERSCORE!113604!

**Comment by ekager** [comment]
I can reproduce after deleting all tabs.

**Comment by softvision-miralobontiu** [comment]
Verified as fixed on the latest build 1.0.1926 (#11770618) with Nexus 5 (Android 6.0.1), Samsung Galaxy Note 8 (Android 9), and Motorola Moto G6 (Android 8)
