### ISSUE TITLE
[Bug]Pressing the back button from your device after closing the keyboard from search bar it close the app.

### ISSUE THREAD

**Issue by sv-sdeiac** [mozilla-mobile/fenix#3587]
## Steps to reproduce
1. Open Firefox Preview;
1. Tap on the Search bar;
1. Swipe up or down to close the keyboard;
1. Tap the back button from the Phone.

### Expected behavior
After tapping the back button, the Home screen is displayed.

### Actual behavior
After tapping the back button, the app closes.

### Device information
* Android device: OnePlus 5T (Android 9) and Samsung Galaxy Tab S3 (Android 8.0).
* Fenix version: 1.0.0-rc.2
* Video:
![20190620](https://user-images.githubusercontent.com/40264165/59855893-8a7b2780-937e-11e9-80cb-2b8045d87c32.gif)UNITO-UNDERSCORE!171052!

**Comment by vesta0** [comment]
@sv-sdeiac can you still reproduce this?

**Comment by sv-sdeiac** [comment]
Hello, I tried to reproduce the problem using Samsung Galaxy Tab S3 (Android 8.0) and One Plus 5T (Android 9) on the latest Firefox Preview Nightly (2019-07-16) but I can't due to the fact that now the user can't close the keyboard after opening the Search bar: please read https://github.com/mozilla-mobile/fenix/issues/1211#issuecomment-511923368.

**Comment by ekager** [comment]
Going to close this and we will have to revisit why this was happening when we reimplement #1211
