### ISSUE TITLE
FNX3-17139 ⁃ [Bug] Fenix should preload the GV content process

### ISSUE THREAD

**Issue by agi90** [mozilla-mobile/fenix#3588]
Fenix does not preload the content process when starting Gecko. Doing this might help with the `GeckoProcessManager.start` crash.

See e.g. Focus here: https://searchfox.org/mozilla-mobile/source/focus-android/app/src/main/java/org/mozilla/focus/web/GeckoWebViewProvider.kt#99

**Comment by cpeterso** [comment]
The `GeckoProcessManager.start` crash is https://bugzilla.mozilla.org/show_bug.cgi?id=1557449.

**Comment by acreskeyMoz** [comment]
Is the content process still being preloaded?
It doesn't look like it to me -- see bug https://github.com/mozilla-mobile/fenix/issues/8291
