### ISSUE TITLE
Consider disabling DeviceMotionEvent and DeviceOrientationEvent events by default

### ISSUE THREAD

**Issue by cpeterso** [mozilla-mobile/fenix#359]
### Why/User Benefit/User Problem
Problem: The Tor browser considers the DeviceMotionEvent and DeviceOrientationEvent events a possible fingerprinting vector:

https://trac.torproject.org/projects/tor/ticket/21609

W3C discussion about requesting permission to receive device motion / orientation events:

https://github.com/w3c/deviceorientation/issues/57

### What / Requirements
Safari 12.1 on iOS added Motion & Orientation settings to enable the DeviceMotionEvent and DeviceOrientationEvent events. This setting is **disabled by default**.

https://developer.apple.com/documentation/safari_release_notes/safari_12_1_release_notes

https://twitter.com/rmondello/status/1091073298409160705

### Acceptance Criteria (how do I know when I’m done?)
DeviceMotionEvent and DeviceOrientationEvent are disabled by default. They can be enabled by a user setting like Safari 12.1.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-12238)

**Comment by bbinto** [comment]
Is this GV dependent? I see this not a must for MVP but rather as a could/after MVP.

Please indicate what teams are involved for this work and potential overall workload/t-shirt size.

**Comment by annevk** [comment]
It's GV-specific as we don't currently expose these features elsewhere (nor should we until we solve the issues mentioned in OP).

**Comment by cpeterso** [comment]
GV would need to add a new API. Fenix would presumably want to add UI for a user setting. IIUC, Safari 12.1 has a user setting that is off by default.

The GV and Fenix work would be small, but there could be additional webcompat and comms/support work.

**Comment by Sdaswani** [comment]
@bbinto to decide yay or nay on whether we do this.

**Comment by bbinto** [comment]
unless somebody has a strong opinion to have to do it for MVP, moving it to Post MVP

**Comment by kbrosnan** [comment]
As part of https://github.com/mozilla-mobile/fenix/issues/26855 this report is closed. I think we would want to do this differently. bz-1515780 covers throttling the event.
