### ISSUE TITLE
[Bug] Audio does not continue to play in soundcloud after screen is turned off

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/fenix#3591]
## Steps to reproduce
1. Navigate to https://m.soundcloud.com/polo-g/polo-g-feat-lil-tjay-pop-out
1. tap play
1. turn off screen

### Expected behavior
Audio keeps playing, like it does on Bromite. 

### Actual behavior
Audio pauses immediately. 

### Device information
* Android device: Pixel 2
* Fenix version: latest

**Comment by sblatz** [comment]
This is expected behavior. See https://github.com/mozilla-mobile/fenix/issues/1113

**Comment by yoasif** [comment]
It seems less like expected behavior than a known issue - thanks for duping.

**Comment by yoasif** [comment]
FYI still an issue today.

**Comment by yoasif** [comment]
@kbrosnan why was this closed? It is still an issue and https://github.com/mozilla-mobile/fenix/issues/1113 is already closed.
