### ISSUE TITLE
[Bug] Passwords not offering to fill

### ISSUE THREAD

**Issue by unixandria-xda** [mozilla-mobile/fenix#3598]
## Steps to reproduce
1. Go to a site with a password saved in normal FF for Android
1. See Firefox preview not offering to fill it
    1. Expected behavior
It offers to fill it
    1. Actual behavior
Nothing different than if I have no password saved
    1. Device information

* Android device: Moto z3 play, Android 9, arm64
* Fenix version: 1.0.1925

**Comment by sv-ohorvath** [comment]
The save/autofill logins feature is not implemented yet.
