### ISSUE TITLE
[Bug] Fenix opens the verge articles 2x as slow as Bromite

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/fenix#3600]
## Steps to reproduce
1. Navigate to https://www.theverge.com/2019/6/19/18681845/facebook-moderator-interviews-video-trauma-ptsd-cognizant-tampa

### Expected behavior
As fast as Chrome/Bromite.

### Actual behavior
Loads page 2x slower than Bromite. 

See [screen recording](https://github.com/mozilla-mobile/fenix/files/3312928/recording_20190620_114859.zip)

### Device information
* Android device: Pixel 2
* Fenix version: latest

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-12246)

**Comment by bogas04** [comment]
Is it due to 77 tabs on Fenix and 1 on chrome?

**Comment by yoasif** [comment]
Given that none of those pages, I would hope not. If it were, it would still be a bug, just a different one. I don't think it is, though.

**Comment by yoasif** [comment]
FWIW, I tried to reproduce this in GeckoView example and didn't see the same pause with a white screen before showing a rendered page, so this feels like it may be Fenix specific.

**Comment by bogas04** [comment]
Do you have web render enabled? I faced a lot of white screens coz of it.

https://github.com/mozilla-mobile/fenix/issues/3904

**Comment by ekager** [comment]
Are you still seeing this? We are on a newer version of GV now so this may be fixed

**Comment by AndiAJ** [comment]
Hi, I've just checked on Nightly Build #12700627 from 27/9 using a Google Pixel 3a (Android 9) and a Google Pixel 3 XL (Android 9) and the issue is still reproducible.

►Video Google Pixel 3a 
![20190927_152246](https://user-images.githubusercontent.com/51314259/65769478-4c8b5d80-e13c-11e9-9426-febe5316b6de.gif)

►Video Google Pixel 3 XL
![20190927_152535](https://user-images.githubusercontent.com/51314259/65769537-73e22a80-e13c-11e9-9d7d-d3a840287c63.gif)

**Comment by mcomella** [comment]
I raised with Bas in Matrix:

> Bas
> Is Fennec also slow?
> mstange
> Not sure if relevant, but theverge is known to be slow with TP on, https://bugzilla.mozilla.org/show_bug.cgi?id=1524122
> 
> 1524122 - Long delay before content appears on popular site theverge.com
> RESOLVED (nobody) in Firefox - Protections UI. Last updated 2019-02-01.
> Bas
> mstange: Oh, is that the good ol' 'we'll wait for certain stuff to come in or a nasty timeout before we uncover the content'? :)

**Comment by pslawless** [comment]
Also related: https://bugzilla.mozilla.org/show_bug.cgi?id=1516552

**Comment by mcomella** [comment]
Triage: @jeanygong will follow-up with greater perf team.

**Comment by jeanygong** [comment]
Follow up on whether this is issue is important to the Platform Perf team .. as per acreskey's comment... _This important because the delta is so pronounced and reproducible.
If it does turn out be Tracking Protection -- great: we can help prioritize the TP fix. If it's not TP, then there's another serious problem._

**Comment by jeanygong** [comment]
Open bugzilla https://bugzilla.mozilla.org/show_bug.cgi?id=1624959 to track Performance platform work that may address this issue.

**Comment by dholbert** [comment]
I duped that bug to https://bugzilla.mozilla.org/show_bug.cgi?id=1516552 (looks like this is just a version of that).

**Comment by mcomella** [comment]
Triage: @jeanygong will follow-up with team but as far as we can tell there's nothing actionable from the front-end side here so we're removing it from the project board.

**Comment by yoasif** [comment]
Please don't close this.

**Comment by mariansima** [comment]
This issue still occurs on Samsung A8 SM-A530F Android 9 Nightly 93.0a1 2021-08-30

**Comment by SoftVision-LorandJanos** [comment]
This issue is still reproducing with the latest Nightly 99.0a1 (2022-02-28).
Device used:  Oppo Reno 6 (Android 11).

**Comment by SoftVision-LorandJanos** [comment]
This issue is still reproducing with the latest Nightly 110.0a1 (2022-12-27).
Device used: Oppo Find X5 (Android 12).
Reopening the ticket.
