### ISSUE TITLE
[Bug] A jsfiddle page crashing the app

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#3601]
## Steps to reproduce
See https://github.com/mozilla/firefox-preview-bughunting-campaign/issues/379

1. Go to http://jsfiddle.net/DerekL/M45Cn/1/ and wait for it to load.
    1. Expected behavior
Page loads.
    1. Actual behavior
Page crashed.
    1. Device information

* Android device: le Eco 2,Samsung M20, Moto G6 (Android 8)
* Fenix version: nightly 6/21

**Comment by alexa-v2** [comment]
For me it doesn't just crash firefox

It crashed almost every other app on my phone too. Also used 523 mb RAM in the process

Device: Moto z3 play, Android 9
Firefox preview: 1.0.1925 (Build #11731824 🦎 68.0-20190611143747)

**Comment by ekager** [comment]
The page doesn't exist anymore. So I'm closing this ticket.
