### ISSUE TITLE
FNX3-17151 ⁃ [Bug] Closing a tab shows snackbar saying "Tab Deleted"

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/fenix#3604]
## Steps to reproduce
1. Visit a site
1. Go to home
1. Close tab.

### Expected behavior
Snackbar shows "Tab closed"

### Actual behavior
Snackbar shows "Tab deleted"

### Device information
* Android device: Pixel 2
* Fenix version: latest

**Comment by sblatz** [comment]
@mheubusch are you able to verify the copy of this?

**Comment by lime124** [comment]
moving to @jpfaller

**Comment by jpfaller** [comment]
Let's do

Tab closed

**Comment by mcarare** [comment]
@jpfaller I assume we should also change message for multiple tabs (currently it says _"tab deleted"_). Also, for private tabs, change from _deleted_ to _closed_ and add check for single private tabs message (currently for closing one private tab it says the same as for normal tab, and says _private_ only for multiple tabs closed)

**Comment by jpfaller** [comment]
@mcarare 

Just to make sure I'm following

Single tab - Tab closed
Multiple tabs - Tabs closed
Single Private tab - Private tab closed
Multiple private tabs - Private tabs closed

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **Nightly build #12880607 from 15/10** using the following devices:

• Google Pixel 3a (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

► Normal browsing 
![20191015_144027](https://user-images.githubusercontent.com/51314259/66829399-f6038900-ef5b-11e9-9d05-28e3655459eb.gif)

► Private browsing
![20191015_144118](https://user-images.githubusercontent.com/51314259/66829444-14698480-ef5c-11e9-9d6d-0da53d325b2d.gif)
