### ISSUE TITLE
FNX3-17154 ⁃ [Bug] Fenix should display an error page for unknown protocols

### ISSUE THREAD

**Issue by agi90** [mozilla-mobile/fenix#3608]
## Steps to reproduce
* Navigate to a page with an unknown protocol, e.g. htt://invalid

### Expected behavior
* Fenix displays an error page (Chrome navigates to a search page, Fennec displays an error page)

### Actual behavior
* Navigation is halted without any feedback and Fenix displays the page that was there before.

Note: this is pretty bad for pages that should work but don't like `about:config`.

### Device information
* Android device: Samsung S10e
* Fenix version: Nightly from playstore

**Comment by pocmo** [comment]
AC issue: https://github.com/mozilla-mobile/android-components/issues/3517

**Comment by cpeterso** [comment]
GV bug https://bugzilla.mozilla.org/show_bug.cgi?id=1563343

**Comment by Amejia481** [comment]
As soon as Fenix gets the latest ac version this will be fixed
![Screenshot_20191018-163151](https://user-images.githubusercontent.com/773158/67126597-74169880-f1c5-11e9-8cc2-c65894349a34.png)

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **Nightly Build #13040608 from 31/10** using the following devices:
• Google Pixel 3a XL (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)


![rsz_screenshot_20191031-110154](https://user-images.githubusercontent.com/51314259/67933537-a87b5300-fbce-11e9-895a-04f2b300da11.png)
