### ISSUE TITLE
FNX3-17156 ⁃ Opening an external link opens the home screen

### ISSUE THREAD

**Issue by colintheshots** [mozilla-mobile/fenix#361]
## Steps to reproduce
1. Set Fenix as default browser
1. Open a link in a Youtube description

### Expected behavior
The link opens in the browser.

### Actual behavior
The home screen opens.

### Device information
* Android device: Android emulator
* Fenix version: Milestone 1

**Comment by sv-ohorvath** [comment]
Verified as fixed.
