### ISSUE TITLE
Some improvements for specific functions.

### ISSUE THREAD

**Issue by BannedByAndroid** [mozilla-mobile/fenix#3610]
> I'm a long term Firefox user, having used the browser since the 3.0 days, and yeah, I still using the browser as my main in most of my platforms I use. However, I couldn't really use the browser in Android, since the old Firefox is, honestly, pretty laggy and slow to use compared to Chrome, which prevents me from using it. It was until, Fenix Nightly becomes a thing, and I tried out the browser, hoping for some changes.
> And now, I have been using the browser for like a week, and I can safely say that Fenix Nightly is a pretty nice browser to use compared to the stable FF. It's faster, lighter and more snappy than the old browser. I can't wait for the final version to release so I can safely ditch Chrome on my Android phone.

Despite the pleasant experience, I do have some issues while using this (unfinished) browser too. Well, time for some suggestions I guess.

**New tabs:**
![2019-06-23-14-55-44](https://user-images.githubusercontent.com/13704644/59973120-5a759380-95cd-11e9-8470-9cbce394beb5.png)
In the current version of Fenix I can only open a new tab by typing the address bar. Would it be ideal to also add an option to add bookmarks, history and previously closed tabs while opening new tabs? Typing does take some time.

**Downloads:**
As for managing downloads in the browser, I have some ideas for it.

1. Add an option to set a save location before downloading like Chrome have, to easily set the saved location for any file. (Chrome for reference)
![2019-06-23-15-02-32](https://user-images.githubusercontent.com/13704644/59973124-6b260980-95cd-11e9-9aa4-efa330e6a02f.png)
1. Mega downloads won't work well on Fenix, it always shows a message stating it can't download the file type. I know we have the Mega app on Android but could it be possible to fix this? Chrome and Firefox Android (standard one, not Fenix) can allow it but not this.
![image](https://user-images.githubusercontent.com/13704644/59973131-7a0cbc00-95cd-11e9-94ab-386fe8b63a76.png)
1. A download manager would be very useful for many situations. Sadly the current version of Fenix doesn't have one.

**Other ideas:**

1. Extension support? (I know, many people mentioned this, so I don't go too far on that)
1. Some performance optimizations to make it as smoother than what is it now? As I stated above, I know it's faster than Firefox Mobile but I do see some sluggishness on some cases. Maybe some implementation of hardware acceleration might work?
1. Custom wallpapers for welcome screen? Or better, theme customization for the browser? It's available on the Firefox desktop browser. That would be very cool and would also improve the user experience. 

(I know this post is pretty generic, but yeah, I'm here to say sorry if that causes any trouble with anyone here.)

**Comment by cadeyrn** [comment]
You should open separate issues for each feature request otherwise it will be difficult for Mozilla to label and track these requests…

Extension support is #574.

**Comment by ThatDAMNGuy** [comment]
> 
> 
> You should open separate issues for each feature request otherwise it will be difficult for Mozilla to label and track these requests…
> 
> Extension support is #574.

Okay, thanks.

**Comment by kbrosnan** [comment]
Closing as there are multiple issues here. Please open single issues.
