### ISSUE TITLE
[Bug] Hover state of icons in bottom bar hide behind URL bar

### ISSUE THREAD

**Issue by bogas04** [mozilla-mobile/fenix#3614]
## Steps to reproduce
Tap and hold tabs icon or padlock on the bottom bar.

### Expected behavior
The ripple should be in front/above of URL bar as it's of prime focus.

### Actual behavior
It hides behind/below the URL bar instead. Doesn't seem right.

![Screenshot](https://user-images.githubusercontent.com/6177621/59975696-600db200-95aa-11e9-8081-5ca94dbf92a1.jpg)UNITO-UNDERSCORE!20190623-165628~2!
![Screenshot](https://user-images.githubusercontent.com/6177621/59975697-600db200-95aa-11e9-9c53-a3bbb4bb0eff.jpg)UNITO-UNDERSCORE!20190623-165755~2!

### Device information
* Android device: OP3T, Android Pie
* Fenix version: 1.0.1925 (Build #11731824 :lizard: 68.0-20190611143747)

**Comment by ekager** [comment]
Closing for #1648
