### ISSUE TITLE
"Automatic" radio in Choose your theme not read aloud when accessed through Talkback

### ISSUE THREAD

**Issue by asadotzler** [mozilla-mobile/fenix#3620]
## Steps to reproduce
1) Install Fenix
2) Enable TalkBack
3) swipe to Automatic in Choose your theme section

### Expected behavior
Talkback should read "Automatic. Adapts to your device settings"

### Actual behavior
Talkback reads nothing

### Device information
* Android device: Galaxy S10e
* Fenix version:

**Comment by softvision-miralobontiu** [comment]
Verified as fixed on the latest build 1.0.1926 (#11760617) with Samsung Galaxy S8 (Android 9), and Nexus 5 (Android 6.0.2).
