### ISSUE TITLE
[Feature Request] Expanded media menu (sharing/saving)

### ISSUE THREAD

**Issue by BlackLotus** [mozilla-mobile/fenix#3621]
It's not possible to send/share media through the media menu.
Examples 1:
Graphics share menu only has save and send url, you can't share images out of the menu anymore. So right now you have to save, open and then share the image.
Example 2:
Videos can't be paused, fullscreened, saved, shared or opened with another app over the (non existent) long-press menu.

It would be nice to have at least feature parity with the mobile firefox.

**Comment by Adams880** [comment]
To add to this. On the current Firefox Mobile app, when you share an image, it automatically appends a link to any text fields that the app you are sharing with has available. If that could be turned off or given as an option to turn off that would be amazing.

I have to constantly delete links that I don't want when sharing to messages or Discord

**Comment by vesta0** [comment]
@BlackLotus would you please provide an example STR for each scenario?

**Comment by BlackLotus** [comment]
What does STR stand for?

**Comment by cadeyrn** [comment]
> What does STR stand for?

STR = steps to reproduce

**Comment by BlackLotus** [comment]
Merci.
# Use case 1:
**Steps to reproduce:**
* Open a website with images
* Long click on an image
* Try to select "share image with"

**What should happen:**
* Open a website with images
* Long click on an image
* Select "share image with"
* Select an application
* The image is loaded in the application and can be used by it

# Use case 2:
**Steps to reproduce:**
* Open a website with embedded videos
* Long click on a video
* No menu opens

**What should happen:**
* Open a website with embedded videos
* Long click on a video
* Have a menu with
  * Play/Pause
  * Fullscreen
  * mute
  * save video
  * open with app

**Comment by Mugurell** [comment]
For sharing images and not their links we have https://github.com/mozilla-mobile/fenix/issues/12414.

For more options in the contextual menu for a video I think we'd need some UX feedback regarding such options and then new GV APIs (already needed for https://github.com/mozilla-mobile/fenix/issues/1111, https://github.com/mozilla-mobile/fenix/issues/2011).
Please also keep in mind that the contextual menu would not appear for all videos - some websites might want to block sharing videos.

Asking @vesta0 to prioritize the work for this.
