### ISSUE TITLE
[Bug] Shortcut item list flickers when typing in search bar

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/fenix#3622]
## Steps to reproduce
1. Launch Fenix.
2. Tap on the URL bar.
3. Tap on the `Shortcuts` button.
4. Add any text on the URL bar.
### Expected behavior
The text is added and no graphical issues are displayed.
### Actual behavior
The `Shortcuts` list flickers when typing in the search bar.
### Device information

* Android device: **`Samsung Galaxy Note 9(Android 8.1.0).`**
* Fenix version: **`6/24 1.0.1926`** 
* [Video](https://drive.google.com/open?id=12F9e3mW0GlPaUyOALeriPjcWl6DhUscd)

**Comment by softvision-miralobontiu** [comment]
Tested with the latest build 1.0.1926 (#11760617), with Samsung Galaxy S8 (Android 9), LG G7 Fit (Android 8.1), Nexus 5 (Android 6.0.1), and Xiaomi mi4i (Android 5.0.2).

On Xiaomi it is not fixed yet, still flickers.

![flicker](https://user-images.githubusercontent.com/40694158/60085481-0fc95800-9742-11e9-8829-cfa33198c476.gif)

**Comment by ekager** [comment]
Does it flicker on any Android 5 device? Since it's fixed on the majority of devices, this doesn't seem high priority to me anymore. I am unassigning myself.

**Comment by softvision-miralobontiu** [comment]
It doesn't flicker anymore on the latest build 7/9 (#11901818) on Xiaomi Mi4i (Android 5.0.2), and on Samsung Galaxy Tab A6 (Android 5.1.1).
