### ISSUE TITLE
[Bug] Help button not working properly on OnePlus 6T

### ISSUE THREAD

**Issue by WhoIsAndi** [mozilla-mobile/fenix#3623]
## Steps to reproduce
Tap the help button from the 3 dot menu
Tap close all tabs from the open tabs
Tap again the help button from the 3 dot menu

### Expected behavior
The help button should work each and everytime it is tapped

### Actual behavior
After closing all tabs, it works only after the second attempt

### Device information

* Android device: OnePlus 6T (Android 9)
* Fenix version: **v1.0.0-rc.2** & **1.0.1926 (24/06)**

### Notes
[Video ](https://drive.google.com/file/d/1PTzMSvPSOK2RbSiVMe6szaKGgTQo4d1w/view?usp=sharing)

**Comment by ekager** [comment]
This should be fixed by #3594
