### ISSUE TITLE
[Bug] Downloaded images from twitter.com are .bin file format

### ISSUE THREAD

**Issue by softvision-miralobontiu** [mozilla-mobile/fenix#3624]
## Steps to reproduce
1. Go to twitter.com
2. Long tap on an image and save image.

### Expected behavior
The image has a .jpg file format.

### Actual behavior
The image has a .bin file format. A saved image from Wikipedia articles is saved with .jpg file format.

### Device information
* Android device: ?
* Fenix version: 1.0.1926 (#11750611)

### Note
Bug filed from https://github.com/webcompat/web-bugs/issues/33424.

![Screenshot_2019-06-24-15-59-59](https://user-images.githubusercontent.com/40694158/60021018-d5a47b80-9699-11e9-8ae6-3ac6237e6c32.png)

**Comment by ekager** [comment]
Thanks! Opened https://github.com/mozilla-mobile/android-components/issues/3516 in AC

**Comment by vesta0** [comment]
Will be addressed in #2809
