### ISSUE TITLE
[Bug] Phone reboots after launch of the app

### ISSUE THREAD

**Issue by avently** [mozilla-mobile/fenix#3628]
## Steps to reproduce

Don't know how you can reproduce it. I'm just launching the app and getting reboot of my phone every time.
### Expected behavior

I expect a normal start of fully working application
### Actual behavior

Shows initial screen with welcome message and theme chooser view and reboots the phone after 20s. Phone freezes after 1 second and I can't do anything. So UI just stucks on welcome page. No hardware buttons are working.
### Device information

* Android device: Lineage OS 14.1, Android 7.1.2
* Fenix version: 1.0.0 but this started to happen a half year ago. I tried maybe 10 different versions and sometimes I was able to use the app and sometimes this issue was present.

I connected my phone via USB and captured logs. The logcat just stopped working in the same moment as UI freezed.
 
[log.txt](https://github.com/mozilla-mobile/fenix/files/3321165/log.txt)

**Comment by kbrosnan** [comment]
06-24 16:39:55.843 22112 22175 W Settings: Setting animator_duration_scale has moved from android.provider.Settings.System to android.provider.Settings.Global, returning read-only global URI.
06-24 16:39:55.845 22112 22175 E GeckoLibLoad: Load sqlite start
06-24 16:39:55.855 22112 22112 E KeyFrames: unable to load
06-24 16:39:55.855 22112 22112 E KeyFrames: java.lang.NoSuchMethodException: <init> []
06-24 16:39:55.855 22112 22112 E KeyFrames: 	at java.lang.Class.getConstructor0(Class.java:2204)
06-24 16:39:55.855 22112 22112 E KeyFrames: 	at java.lang.Class.getConstructor(Class.java:1683)
06-24 16:39:55.855 22112 22112 E KeyFrames: 	at androidx.constraintlayout.motion.widget.KeyFrames.<clinit>(KeyFrames.java:2)
06-24 16:39:55.855 22112 22112 E KeyFrames: 	at androidx.constraintlayout.motion.widget.MotionScene.<init>(MotionScene.java:18)
06-24 16:39:55.855 22112 22112 E KeyFrames: 	at androidx.constraintlayout.motion.widget.MotionLayout.init(MotionLayout.java:6)
06-24 16:39:55.855 22112 22112 E KeyFrames: 	at androidx.constraintlayout.motion.widget.MotionLayout.<init>(MotionLayout.java:64)
06-24 16:39:55.855 22112 22112 E KeyFrames: 	at java.lang.reflect.Constructor.newInstance0(Native Method)
06-24 16:39:55.855 22112 22112 E KeyFrames: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:430)
06-24 16:39:55.855 22112 22112 E KeyFrames: 	at android.view.LayoutInflater.createView(LayoutInflater.java:645)
06-24 16:39:55.855 22112 22112 E KeyFrames: 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:787)
06-24 16:39:55.855 22112 22112 E KeyFrames: 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:727)
06-24 16:39:55.855 22112 22112 E KeyFrames: 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:858)
06-24 16:39:55.855 22112 22112 E KeyFrames: 	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
06-24 16:39:55.855 22112 22112 E KeyFrames: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:518)
06-24 16:39:55.855 22112 22112 E KeyFrames: 	at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
06-24 16:39:55.855 22112 22112 E KeyFrames: 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:334)
06-24 16:39:55.855 22112 22112 E KeyFrames: 	at android.view.LayoutInflater.inflate(Unknown Source)
06-24 16:39:55.855 22112 22112 E KeyFrames: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:426)
06-24 16:39:55.855 22112 22112 E KeyFrames: 	at org.mozilla.fenix.home.HomeFragment.onCreateView(HomeFragment.kt:2)
06-24 16:39:55.855 22112 22112 E KeyFrames: 	at androidx.fragment.app.Fragment.performCreateView(Fragment.java:4)
06-24 16:39:55.855 22112 22112 E KeyFrames: 	at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:88)
06-24 16:39:55.855 22112 22112 E KeyFrames: 	at androidx.fragment.app.FragmentManagerImpl.addAddedFragments(FragmentManagerImpl.java:6)
06-24 16:39:55.855 22112 22112 E KeyFrames: 	at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManagerImpl.java:54)
06-24 16:39:55.855 22112 22112 E KeyFrames: 	at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManagerImpl.java:11)
06-24 16:39:55.855 22112 22112 E KeyFrames: 	at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManagerImpl.java:4)
06-24 16:39:55.855 22112 22112 E KeyFrames: 	at androidx.fragment.app.FragmentManagerImpl.dispatchStateChange(FragmentManagerImpl.java:4)
06-24 16:39:55.855 22112 22112 E KeyFrames: 	at androidx.fragment.app.Fragment.performActivityCreated(Fragment.java:9)
06-24 16:39:55.855 22112 22112 E KeyFrames: 	at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:99)
06-24 16:39:55.855 22112 22112 E KeyFrames: 	at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:9)
06-24 16:39:55.855 22112 22112 E KeyFrames: 	at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:210)
06-24 16:39:55.855 22112 22112 E KeyFrames: 	at androidx.fragment.app.FragmentManagerImpl.dispatchStateChange(FragmentManagerImpl.java:2)
06-24 16:39:55.855 22112 22112 E KeyFrames: 	at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:9)
06-24 16:39:55.855 22112 22112 E KeyFrames: 	at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:1)
06-24 16:39:55.855 22112 22112 E KeyFrames: 	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1249)
06-24 16:39:55.855 22112 22112 E KeyFrames: 	at android.app.Activity.performStart(Activity.java:6701)
06-24 16:39:55.855 22112 22112 E KeyFrames: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2662)
06-24 16:39:55.855 22112 22112 E KeyFrames: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2766)
06-24 16:39:55.855 22112 22112 E KeyFrames: 	at android.app.ActivityThread.-wrap12(ActivityThread.java)
06-24 16:39:55.855 22112 22112 E KeyFrames: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1507)
06-24 16:39:55.855 22112 22112 E KeyFrames: 	at android.os.Handler.dispatchMessage(Handler.java:102)
06-24 16:39:55.855 22112 22112 E KeyFrames: 	at android.os.Looper.loop(Looper.java:154)
06-24 16:39:55.855 22112 22112 E KeyFrames: 	at android.app.ActivityThread.main(ActivityThread.java:6236)
06-24 16:39:55.855 22112 22112 E KeyFrames: 	at java.lang.reflect.Method.invoke(Native Method)
06-24 16:39:55.855 22112 22112 E KeyFrames: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:891)
06-24 16:39:55.855 22112 22112 E KeyFrames: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:781)
06-24 16:39:55.855 22112 22112 E KeyFrames: 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:102)

**Comment by avently** [comment]
In v1.1.0 after start the app freezes the phone immediately. I can see white screen only without any UI element.

**Comment by klausenbusk** [comment]
What phone do you have?

**Comment by avently** [comment]
@klausenbusk this issue happens on Meizu m2 (4 cores).

**Comment by klausenbusk** [comment]
I'm wondering if it is some sort of memory leak/out of memory situation How 
does the memory usage looks before starting the app?
Could you try running htop or free in a loop when starting the app and see 
if the memory usage explode before he phone freeze.

**Comment by avently** [comment]
>Could you try running htop or free in a loop

Tried but memory usage was ok. Since the phone was freezed after ~1 second I can't say anything useful about logs or memory.

**Comment by avently** [comment]
For the note. On the same phone with Android 9.0 Fenix runs and works without problems.
