### ISSUE TITLE
Clean up redundant Gradle build steps

### ISSUE THREAD

**Issue by colintheshots** [mozilla-mobile/fenix#3642]
I noticed that an ARM32 build was performing work involving an x86-64 GeckoView earlier. I want to perform a sanity check and ensure that per-target builds are not performing unnecessary build steps.

Some of this may be cleaned up by switching to fat AARs for GeckoView, but some of it won't. We have a long history of making calls which duplicate effort, like calling lint instead of the specific version for the current build target.

**Comment by ekager** [comment]
We switched to the fat AARs so is this done?

**Comment by boek** [comment]
@colintheshots bump^^

**Comment by kbrosnan** [comment]
Closing as there are not clear tasks.
