### ISSUE TITLE
[Bug] Fenix launches in broken state when opening external app (custom tab related?)

### ISSUE THREAD

**Issue by cadeyrn** [mozilla-mobile/fenix#3644]
### Steps to reproduce

Unfortunately I don't have good STR, but it happened two times in two days. After sleeping a few hours and then opening the Google Mail app (I didn't open Fenix!) Fenix launched in a broken state.

### Expected behavior

Either Fenix should not start at all or it should appear as a working custom tab if there was a custom tab opened before.

### Actual behavior

As you can see in the screenshots there is no content but the toolbar is on top and not on bottom and it's not the custom tab toolbar. Also the menu is not the custom tab menu but the regular menu. And the URL you can see in the address bar was definitively not opened in a custom tab, it's from a regular browsing session.

![Screenshot_20190625-073141](https://user-images.githubusercontent.com/1100614/60074031-47c0a300-9722-11e9-84a3-d79b2ff2738b.png)
![Screenshot_20190625-073151](https://user-images.githubusercontent.com/1100614/60074032-47c0a300-9722-11e9-8ea5-21f1db99970f.png)

### Device information

* Android device: HTC U11 / Android 8.0
* Fenix version: Fenix 1.0.0 (from GitHub releases) or from master branch built on 6/19. Both are installed and I forgot to have a look which version was used but both versions should be very similar because 1.0.0 got the last change also on 6/19.

**Comment by ekager** [comment]
Going to close for #2383
