### ISSUE TITLE
PatternSyntaxException: Syntax error in regexp pattern near index 4:

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/fenix#3652]
https://sentry.prod.mozaws.net/operations/fenix-nightly/issues/5986156/

```
PatternSyntaxException: Syntax error in regexp pattern near index 4:
(?<major>[0-9]+)\.(?<minor>[0-9]+)(?:\.(?<patch>[0-9]+))?(?<metadata>[^0-9].*)?
    ^
    at org.mozilla.fenix.components.Core$engine$2.invoke(Core.kt:10)
    at org.mozilla.fenix.components.Core.getEngine(Core.kt)
    at org.mozilla.fenix.components.Core$sessionManager$2.invoke(Core.kt:1)
    at org.mozilla.fenix.components.Core.getSessionManager(Core.kt)
    at org.mozilla.fenix.FenixApplication.onTrimMemory(FenixApplication.kt:3)
...
(18 additional frame(s) were not displayed)

Syntax error in regexp pattern near index 4:
(?<major>[0-9]+)\.(?<minor>[0-9]+)(?:\.(?<patch>[0-9]+))?(?<metadata>[^0-9].*)?
    ^
```

**Comment by pocmo** [comment]
AC issue: https://github.com/mozilla-mobile/android-components/issues/3545

This code was introduced in AC 1.0.0 - so at the moment it should only affect Nightly builds. We try to get a fix into AC 2.0.0. If that is too late for the next Fenix release then we can uplift this and cut a  1.0.x release.

**Comment by pocmo** [comment]
Fixed in AC 2.0.0.

**Comment by kbrosnan** [comment]
Another signature Sentry issue: [FENIX-NIGHTLY-5N](https://sentry.prod.mozaws.net/operations/fenix-nightly/issues/5986691/)

**Comment by kbrosnan** [comment]
This is fixed in master, crash rate on Sentry has dropped to near 0. 

releases/v1.0 branch is not affected.
