### ISSUE TITLE
[Bug] Unable to download files with extension .xpi

### ISSUE THREAD

**Issue by SeburoSUMO** [mozilla-mobile/fenix#3666]
## Steps to reproduce

In Fenix, visit https://github.com/mozilla-lockwise/lockwise-addon/releases and long press on a .xpi file found in any Assets section of each release.

### Expected behavior

File downloads

### Actual behavior

Nothing happens

### Device information

* Android device: Motorola Moto E5, Android 8.0.0
* Fenix version: 1.0.1926 (Build #11760617 Lizard 68.0-20190612114833) AC: 1.0.0

**Comment by NotWoods** [comment]
GeckoView doesn't seem to fire a download event for .xpi files. \
Filed [Bug 1571314](https://bugzilla.mozilla.org/show_bug.cgi?id=1571314)

**Comment by cpeterso** [comment]
Gecko might be short circuiting .xpi links or GV might be ignoring some XPI install event from Gecko. But downloading untrusted third-party extensions in Fenix is a very low priority since Fenix+GV doesn't even support installing extensions from AMO yet.

The GV bug is a P3.

**Comment by liuche** [comment]
@vesta0 what priority is downloading .xpi files? (.xpi is the file format for Mozilla addons, so I assume users are downloading them from sites and trying to install them in Fenix)

This looks like GV needs to add some extra APIs, so getting a priority from Fenix will help them prioritize against other work.

**Comment by Amejia481** [comment]
I tested on nightly and I was able to download `.xpi` files. At the moment, the only way to install add-ons is through the add-on manager UI.
![image](https://user-images.githubusercontent.com/773158/83032160-7ebec900-a003-11ea-9e32-9c00b5c65987.png)

**Comment by NotWoods** [comment]
Since @Amejia481 was able to download a .xpi file, lets verify with QA and close this issues. Other issues can track installing the file.

**Comment by abodea** [comment]
Verified as fixed on the latest **Nightly 8/21** with **Google Pixel 4 XL (11).**
Note that I was able to download `.xpi` without problems.

**Comment by abodea** [comment]
@NotWoods can we remove the `needs:gv` label too?
