### ISSUE TITLE
[Bug] Unexpected placement of overscroll glow on home

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/fenix#3673]
## Steps to reproduce

1. Open some tabs (not sure this is required, but I don't want to close my tabs to see)
2. Pull down on home screen.

### Expected behavior

Overscroll glow appears at top of screen.

### Actual behavior

Overscroll glow appears below addressbar. 

![signal-attachment](https://user-images.githubusercontent.com/152493/60139701-e8dc4780-977c-11e9-827f-a2fa2381e6a5.jpeg)

### Device information

* Android device: Pixel 2
* Fenix version: latest

**Comment by kbrosnan** [comment]
Overscroll glow is not part of the home screen any more.
