### ISSUE TITLE
First page load calls onLoadingStateChanged with loading=false twice

### ISSUE THREAD

**Issue by boek** [mozilla-mobile/fenix#3676]
QA noticed that there was a discrepancy between `uri_count` and `search_count` and after some further investigation it looks like [`onLoadingStateChanged`](https://github.com/mozilla-mobile/fenix/blob/master/app/src/main/java/org/mozilla/fenix/HomeActivity.kt#L301) from the session observer is getting called twice on the first load in a session.

This is causing an extra `Event.UriOpened` event to get tracked.

**Comment by mcomella** [comment]
This could be a good candidate for a regression unit test! 😁

**Comment by Baron-Severin** [comment]
I also noticed https://github.com/mozilla-mobile/fenix/issues/6126 while investigating this bug, which probably accounts for some of the discrepancy.  Note that #6126 only impacts `uri_count`, not `search_count`.

**Comment by Baron-Severin** [comment]
Verified this behavior on Reference Browser at https://github.com/mozilla-mobile/reference-browser/pull/926 and opened https://github.com/mozilla-mobile/android-components/issues/4795 against AC.  Opening a PR with a temporary fix from our side.

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on Nightly Build #12970607 from 24/10.

Ping **463e6ecc-0b48-4355-92b9-af151f6ac7e9** - 3 searches performed ✔️
Ping **d523cd31-b93e-4efd-aa41-aef8ed8ae956** - 5 searches performed ✔️
Ping **5ccb0c78-4401-47ee-9777-0542d52840a4** - 8 searches performed ✔️

[Logcat](https://github.com/mozilla-mobile/fenix/files/3768263/counting.txt)

Ping **0fc0f19c-15af-4502-9d16-868968b283a5** - 6 searches performed, (one with each search engine) ✔️
[counting2.txt](https://github.com/mozilla-mobile/fenix/files/3768301/counting2.txt)
