### ISSUE TITLE
Opening bookmarks is a really confusing experience

### ISSUE THREAD

**Issue by pwd-github** [mozilla-mobile/fenix#3677]
## Steps to reproduce
As a user, I want to open a bookmark in a new tab. 

I create a new tab

### Expected behavior

I should be able to access my bookmarks from there in order to open one. 

### Actual behavior

I get the search interface. 

So then I'm like how do I access my bookmarks in order to open them in a new tab? Oh I can't? It's impossible? Damn! 

### Device information

* Android device: N/A
* Fenix version: 1.0.1926 (Build #11761827 🦎 68.0-20190612114833)
AC: 1.0.0

**Comment by ekager** [comment]
If you start typing, the search suggestions in the awesome bar will search your bookmarks and give you a chance to open them. Does that not work for you?

**Comment by ekager** [comment]
See https://github.com/mozilla-mobile/fenix/issues/2037 for an issue about making it more clear that these are bookmark suggestions

**Comment by pwd-github** [comment]
It is possible to bring up the bookmarks via search, however at the time, I couldn't recall the name of the bookmark and hence just found it a frustrating experience.

**Comment by codlike** [comment]
Call me old fashioned but I find it very confusing. I dont want to type the address, I want to very quickly navigate to my bookmarks, and hit the one I want. Hitting the 3 dots, hitting My library, then hitting Bookmarks, then hitting Desktop bookmarks... then i'm there. I love Naked Browsers implementation, swipe right, there are my bookmarks.

**Comment by sblatz** [comment]
@mozilla-mobile/ux please take these comments into consideration :)

**Comment by sblatz** [comment]
Labeling this as a feature request as it's a request to change the current behavior to something that will require a bit of UX rethinking.

**Comment by lime124** [comment]
we are in the process of collecting bookmark related issues for consideration in one design effort - removing ux label

**Comment by rubcap** [comment]
> It is possible to bring up the bookmarks via search, however at the time, I couldn't recall the name of the bookmark and hence just found it a frustrating experience.

I concur with OP. What if you don't remember the bookmark, not even part of it?
Also, on the new tab page, I don't see any history nor frequently visited sites to start from.
It's the main gripe I have with this great new browser.

The current Firefox for Android 'new tab page' works wonderful in this respect, with Top Sites/Speed Dial, Highlights, Bookmarks, History ... all _easily_ accessible.

@lime124 I'd like to suggest to port the Firefox for Android 'new tab page' to Fenix. If it ain't broke, don't fix it ;-)  Thanks for reading.

**Comment by lime124** [comment]
#1487 should address this issue outlined here - accessing bookmarks from a new tab. closing. thanks!

**Comment by rubcap** [comment]
@lime124 How does #1487 solve accessing bookmarks (without remembering their names), _if you start by pressing the '+' button (new tab)_ ? That was the use case mentioned here?
