### ISSUE TITLE
[Bug] Crash when tapping on your account

### ISSUE THREAD

**Issue by softvision-miralobontiu** [mozilla-mobile/fenix#3678]
## Steps to reproduce
1. Go to Settings and sign in.
2. Go to your account.

### Expected behavior
Your account can be accessed.

### Actual behavior
App crashes.

### Device information
* Android device: Motorola Moto G6 (Android 8.1), Nokia 6 (Android 7.1.1), Nexus 5 (Android 6.0.1)
* Fenix version: 1.0.1926 (#11770618)

### Notes
It might be related to the fact that we have limited IP's and that might be in conflict with the app.
See also https://bugzilla.mozilla.org/show_bug.cgi?id=1558745

![crash](https://user-images.githubusercontent.com/40694158/60165019-41f0bd80-9807-11e9-8df5-1b07c39a5f55.gif)

 [logcat.txt](https://github.com/mozilla-mobile/fenix/files/3329019/logcat.txt)

**Comment by abodea** [comment]
Verified as fixed on the latest build 6/27 with **`Nokia 6 andro 7.1.1, Google Pixel 3 XL(Android P), Samsung Galaxy Note 9(Android 8,1,0), Google Pixel XL(Android Q Beta 4).`**
Please note that the login and everything about that section is working correctly.
