### ISSUE TITLE
[Bug] Three-dot menu is misplaced when turning the device from portrait mode to landscape mode

### ISSUE THREAD

**Issue by softvision-miralobontiu** [mozilla-mobile/fenix#3679]
## Steps to reproduce
1. Open a page with an input field with the device in portrait mode (i.e. google.com).
2. Tap on the three-dot menu.
3. Turn the device in landscape mode and observe.

### Expected behavior
The three-dot menu should be visible in the right-lower corner.

### Actual behavior
The three-dot menu is displayed in the middle, and the page behind it is zoomed.

### Device information
* Android device: Motorola Moto G6 (Android 8)
* Fenix version: 1.0.1926 (#11770618)

### Note
This issue was found in the campaign [#449](https://github.com/mozilla/firefox-preview-bughunting-campaign/issues/449)

![landscape_Trim](https://user-images.githubusercontent.com/40694158/60176472-082bb100-981f-11e9-9dae-c338b5ce2a5d.gif)

**Comment by vesta0** [comment]
Can't reproduce this on pixel 3.

**Comment by softvision-miralobontiu** [comment]
I was able to reproduce this issue with 10/18 Nightly build with:
- Motorola Moto G6 (Android 8),
- Sony Xperia Z5 Premium (Android 7.1.1),
- Nexus 6P (Android 8.1),
- Huawei Media Pad M2 (Android 5.1.1).

**Comment by softvision-miralobontiu** [comment]
This issue no longer reproduces on the latest Nightly 11/25 with Motorola Moto G6 (Android 8), Sony Xperia Z5 Premium (Android 7.1.1), and Huawei Media Pad M2 (Android 5.1.1).
I will close the issue.
