### ISSUE TITLE
[Fenix] Use Metropolis font for headers, buttons, and snackbars

### ISSUE THREAD

**Issue by AmyYLee** [mozilla-mobile/fenix#3687]
Since we are unable to use Sharp Sans, we will be using Metropolis instead for headers, buttons, and snackbars. Please see reference below @colintheshots 

Font location: https://github.com/chrismsimpson/Metropolis
![Screen Shot 2019-06-26 at 3 55 21 PM](https://user-images.githubusercontent.com/5992746/60210496-02d46380-982b-11e9-9630-3f70e070970d.png)
![Screen Shot 2019-06-26 at 3 54 26 PM](https://user-images.githubusercontent.com/5992746/60210505-0536bd80-982b-11e9-9430-2575c539e142.png)
![Screen Shot 2019-06-26 at 3 53 12 PM](https://user-images.githubusercontent.com/5992746/60210514-0a940800-982b-11e9-9538-9ee9269966fe.png)
![Screen Shot 2019-06-26 at 3 52 13 PM](https://user-images.githubusercontent.com/5992746/60210520-0c5dcb80-982b-11e9-8b46-79354a231d23.png)
![Screen Shot 2019-06-26 at 3 52 00 PM](https://user-images.githubusercontent.com/5992746/60210524-0ec02580-982b-11e9-843a-ad76fa18d121.png)

**Comment by kglazko** [comment]
<img width="346" alt="Screen Shot 2020-02-19 at 5 58 27 PM" src="https://user-images.githubusercontent.com/1676235/74893674-ca494300-5341-11ea-9550-9abc0c411614.png">
Here is an example of the updated headers. @brampitoyo @AmyYLee please let me know if there should be changes like thinner/bolder, etc. given the font change.

**Comment by abodea** [comment]
Verified as fixed on the latest **Nightly 4/3** with **Google Pixel 4 XL (10).**

Note that I verified everything on the Light, Dark and Following the device theme and PB on in portrait and landscape.
Also, I verified it with 3 Font Sizes from the device settings, default, large, largest and everything was correctly displayed.
| Section | Element |  Metropolis font? | Comments | 
| ------------- | :------------: | :-------------: | ------------- |
| **Onboarding elements**  | Welcome! |  ✅ |
| | Already have an account? |  ✅ |
| | Sing into Firefox |  ✅ |
| | See what's new |  ✅ |
| | Protect yourself |  ✅ |
| | Chose your theme |  ✅ |
| | Browse Privately|  ✅
| | Open Settings |  ✅ |
| | Take a position |  ✅
| | Your Privacy |  ✅
| | Read our privacy notice |  ✅
| | Start browsing |  ✅  | Should it be bold?
| **Home Page** |Top Sites |            ✅            |
| | Open tabs |           ✅           |
|  | New tab option|         ✅           |
| | Collections option |     ✅              | Should `Save to collection` be non bold?
| | URL bar text |           ✅            |
| | 3 dot menu |            ✅            |
| | ETP menu/elements |            ✅            |
| | 3 dot menu |            ✅            |
| | 3 dot menu |            ✅            |
| **Settings** | Turn on Sync  |            ✅            | Should `Use email instead` be non bold? Note that `Ready for scan` is bold.
| |    General        |           ✅           |
| |   Account name       |           ✅           | [Is it intended to be in bold?](https://github.com/mozilla-mobile/fenix/issues/9662)
| |    Privacy and security        |           ✅           |
| |   Advanced         |           ✅           |
| |      About      |           ✅           |

@kglazko @AmyYLee looking forward to the questions from comments section regarding the bold text. In case those needs to be bold, I can open a bug for them.

**Comment by brampitoyo** [comment]
Assigning @AmyYLee to this issue.

**Comment by AmyYLee** [comment]
@abodea Here's my feedback:
"Start browsing" - Semi Bold
"Collections option" - Semi Bold 
"Turn on Sync" - Semi Bold for both (Note: "Use email instead" letter spacing looks tight and "Use email instead" letter spacing looks too wide).
"Account name" - Yes it should be bold, but it should be Inter UI and not Metropolis. 

Basically all buttons should have the same weight (Metropolis Semi Bold). Thanks!
