### ISSUE TITLE
video background

### ISSUE THREAD

**Issue by jor1196** [mozilla-mobile/fenix#369]
Hello every time I go to YouTube to listen to music and change the application the video stops, in Firefox I achieve this with an extension called Video Background Fixer Could you implement this function in Fenix?

**Comment by colintheshots** [comment]
This feature will likely not make the initial MVP version. We want to err
on the side of not wasting anyone's 4G bandwidth if they intended to stop
watching. There's few worse experiences than racking up a thousand dollar
cellphone bill by accident.

**Comment by sblatz** [comment]
This should be fixed by https://github.com/mozilla-mobile/fenix/issues/1113. Closing as a dup :)
