### ISSUE TITLE
[Bug] Shorcuts and QR scanner bar doesn't appear sometimes

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#3690]
### Demo
![demo 2019-06-26 13_36_46](https://user-images.githubusercontent.com/4400286/60213025-766c7580-9817-11e9-98f4-7c9eddfbbcb9.gif)

**Comment by ekager** [comment]
I think this is also caused by the constraintlayout bug #3668 ... :(

**Comment by abodea** [comment]
Verified as fixed on the latest build **`6/27`** with **`Samsung Galaxy S7(Android 7), Huawei Mate 20 Lite(Android 8.1.0), Google Pixel 3 XL (Android 9), Google Pixel XL(Android Q Beta 4).`**

**Comment by sv-ohorvath** [comment]
Also verified on the RC 1.0.1. Nexus 9 (Andriod 7.1.1), Pixel 3 (Android 9)
