### ISSUE TITLE
[Bug] The tab/session you're currently in shows up as a suggestion and does nothing

### ISSUE THREAD

**Issue by ekager** [mozilla-mobile/fenix#3695]
<img width=375 src=https://user-images.githubusercontent.com/25442310/60217762-4d051700-9822-11e9-8498-781f97bd9a25.gif>

## Steps to reproduce
1. Open a tab
2. Go to search
3. Find search suggestion for the link you're currently on

### Expected behavior
- Tab you're currently on doesn't show up as a suggestion?

### Actual behavior
- Shows up but does nothing

### Device information

* Android device: ?
* Fenix version: ?

**Comment by Amejia481** [comment]
I'm also seeing the current URL being shown twice in the search results, the only differences between each other are that the first one has the URL as a title, and it's actionable, the second one is not actionable and have the title of the web site.

![image](https://user-images.githubusercontent.com/773158/60685803-2aeb4480-9e73-11e9-9aea-616b39d1abc9.png)

**Comment by ekager** [comment]
I think one of them is the history item maybe? It is if it opens in a new tab by loading that URL. We should probably continue looking into duplicate URL suggestions solutions as well

**Comment by ekager** [comment]
We are no longer waiting on the AC fix for this, and someone can pick this up. See discussion in https://github.com/mozilla-mobile/android-components/pull/3681 for more information about what we can do here

**Comment by colintheshots** [comment]
For QA, the expected behavior here is that the currently selected tab should not show up in results. However, other tabs should show up and if selected from search suggestions, should select that tab. I'm not sure how we should deal with the fact that both history and session suggestions suggest the same item twice. I think we need an A-C issue to de-dupe and only show the session/tab suggestion in that case.

**Comment by softvision-miralobontiu** [comment]
Verified that the current tab, when tapped on the URL bar, shows up as a search suggestion and a history entry. Also, the other suggestions open if tapped on.
Tested on the latest Nightly build 190729 (#12100610) with Motorola Nexus 6 (Android 7.1.1), and Huawei P6 Lite (Android 6).

**Comment by softvision-miralobontiu** [comment]
Verified as fixed also on the latest build of RC 1.2.0-rc.2 with Huawei P9 Lite (Android 6), and Motorola Moto G6 (Android 8).
