### ISSUE TITLE
Overflow menu implementation

### ISSUE THREAD

**Issue by Nxt3** [mozilla-mobile/fenix#3713]
### Why/User Benefit/User Problem

In Google Chrome (and other Android apps), when there is an overflow menu button, you can long press on the menu icon, and then drag down to the menu item you want to select. 

In both Firefox apps, you have to tap the menu button and then tap the menu item you want.

### What/Requirements

I believe it's because Firefox uses a custom implementation of the overflow menu. I'd love to see this follow how other Android apps work.

### Acceptance Criteria (how do I know when I’m done?)

When the overflow menu behaves like other Android apps.

**Comment by NotWoods** [comment]
Thanks for filing! We're moving this issue over to our [Android Components](https://github.com/mozilla-mobile/android-components/issues/3587) repo where the menu code lives.
