### ISSUE TITLE
Add Android button in URL like in Firefox Android Old

### ISSUE THREAD

**Issue by zbhoy** [mozilla-mobile/fenix#3718]
### Why/User Benefit/User Problem
In old firefox on android there would be an android icon in the URL bar when the link could be opened in an app. Like with a reddit link and 3rd party reddit app.

### What/Requirements
Implement the button to force app intents to open

**Comment by kbrosnan** [comment]
Dupe #3070

**Comment by zbhoy** [comment]
Thanks! Didn't see that issue
