### ISSUE TITLE
Unable to see lock icon or three dot menu

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#372]
We should change the colors we're using for these so they are easier to see against the URL bar.
<img width=300 src=https://user-images.githubusercontent.com/4400286/52220180-22a2c500-2853-11e9-9195-fe81f5a9569b.png>

**Comment by ekager** [comment]
While we could override all of the AC assets if necessary, we could also wait for [AC issue #1840](https://github.com/mozilla-mobile/android-components/issues/1840) that will give us color control of the security and menu icon.

**Comment by sblatz** [comment]
Looks like that [should be landing in 0.41.0](https://github.com/mozilla-mobile/android-components/issues/1840) 😄

**Comment by bbinto** [comment]
Would you mind giving an estimate for this?

**Comment by bbinto** [comment]
@sblatz and @Sdaswani - could we please have this one looked at as a P1?

Thanks

**Comment by Sdaswani** [comment]
@ekager is on it.

**Comment by bbinto** [comment]
Thanks for the quick turnaround @sdaswani and team.

**Comment by topotropic** [comment]
thanks for fixing it, looks better!  noticed that the home icon is missing – can you bring it back? Thanks!

**Comment by bbinto** [comment]
@topotropic please file a new bug if possible, also let me know if we are still blocked and we'll get this escalate again with @Sdaswani

**Comment by topotropic** [comment]
https://github.com/mozilla-mobile/fenix/issues/398
