### ISSUE TITLE
[Feature Request] Toggle position of navigation bar

### ISSUE THREAD

**Issue by dylmye** [mozilla-mobile/fenix#3721]
Hello! I've tried searching for this so sorry if it's a dupe. 

I prefer having the navigation bar at the top. It's more intuitive to me personally. This request is for a toggle in the settings for the position of the navigation bar, either top or bottom of screen. 

Thanks!

**Comment by Madis0** [comment]
#3704

**Comment by spandan888** [comment]
It should be given as a preference'.. requires a lot of recoding, but being open source, fenix should be the best...
