### ISSUE TITLE
Open searchbox when trigerring assistant

### ISSUE THREAD

**Issue by phileastv** [mozilla-mobile/fenix#3722]
### Why/User Benefit/User Problem

To search the web and avoid Google, i'm currently using the classical Firefox for Android and use it with the Assistant Button (which place the cursor on the searchbox and opens the keyboard), and make the app ready to search. This is very convenient.

Currently thanks to #390 Fenix can be mapped to the assistant button, but doesn't open the keyboard. It's __definitely__ polishing and not a top priority, but would be great if it's the same behavior as the old Firefox.

### Acceptance Criteria (how do I know when I’m done?)

Place the text cursor on the searchbox and open the keyboard when I open Fenix with the assistant button.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-12335)

**Comment by JoGarWeb** [comment]
One year later... Don't forget this feature !! I'm really miss this in Fenix 😭😭😭

**Comment by rozmansi** [comment]
> The rationale behind this is to get from the spark in your head to the online search results in as few clicks as possible. I believe this task is one of the most frequent tasks we do on our phones. Imagine: a second saved times number of uses you literally save a lifetime here! 😀

**Comment by madb1lly** [comment]
Hi all,

I fully agree. I really just want to be able access search quickly and mapping the assistant button with Fennec was a boon.

Cheers 🙂

**Comment by purpleyuan** [comment]
Are there any updates on this issue?

**Comment by delia-pop** [comment]
Verified as fixed on Nightly 110.0a1 from 01/04 with Google Pixel (Android 13). The keyboard is invoked and the search bar is focused when Fenix is set as digital assistant app. 

https://user-images.githubusercontent.com/89388888/210608720-05e0d8e0-19da-4272-80a6-8802922f3cff.mp4

**Comment by Otiel** [comment]
That is great news, thank you for fixing this! ❤️ 🥳
