### ISSUE TITLE
Quick share

### ISSUE THREAD

**Issue by buttercookie42** [mozilla-mobile/fenix#3726]
### Why/User Benefit/User Problem
If you have some share targets that you use much more frequently than others, it would be good to have a quicker way of accessing them than going through the full share sheet.

### What/Requirements
In Fennec, the two most frequently (possibly in combination with some recency factor, not sure?) used share items were directly accessible from the main menu without having to go through the full share sheet/list.

### Acceptance Criteria (how do I know when I’m done?)
The top N (at least two, and I guess there isn't the space for much more) share actions as sorted by frecency can be shared to directly without going through the full share sheet.

**Comment by vesta0** [comment]
@jonalmeida is this possible with the custom share sheet?

**Comment by jonalmeida** [comment]
> @jonalmeida is this possible with the custom share sheet?

Possible, and I've been meaning to do before folks noticed. :)

**Comment by liuche** [comment]
There's also a system share sheet (for Android-level share sheet) - it might be possible to add an Intent to the system share sheet #2819.

**Comment by jonalmeida** [comment]
> There's also a system share sheet (for Android-level share sheet) - it might be possible to add an Intent to the system share sheet #2819.

I've left a comment here regarding this: https://github.com/mozilla-mobile/fenix/issues/2819#issuecomment-512830330

**Comment by liuche** [comment]
This needs some UX to see what "quick share" in the main menu looks like.

**Comment by jonalmeida** [comment]
I created #4231 which can be implemented async to this so that we can see something working based on our technical constraints while UX looks into this.

**Comment by vesta0** [comment]
I am moving this issue out of the backlog as it didn't accurately captured the product requirement and chatted with @jonalmeida about capturing that in #4231 which I will move to the backlog.

**Comment by jonalmeida** [comment]
> This is a feature of Fennec which allows access to frequently used share options within 2 clicks, and the for anything else requires 3. In Fenix all share options require 3 clicks. I think that what @buttercookie42 requested is to provide what Fennec already has but this is not at all what has been discussed, is it?

You're right, this is separate from the internal share screen which is still being discussed.

**Comment by madb1lly** [comment]
So @jonalmeida what solution you are considering to address the feature request raised by the OP?

**Comment by jonalmeida** [comment]
@sblatz is working on share and things so he might have more comment.

I wonder if this is also on @vesta0's radar.

**Comment by vesta0** [comment]
Adding to group triage so we can discuss it. I think this is a good feature and I'd like to understand the effort + if implementation is depends at all on what kind of share sheet we are using.

**Comment by vesta0** [comment]
Discussed at group triage. This would be a new feature and not related to existing work or whether we use native or custom share sheet.

**Comment by vesta0** [comment]
Dup of #6537
