### ISSUE TITLE
Visible URL width

### ISSUE THREAD

**Issue by buttercookie42** [mozilla-mobile/fenix#3727]
On my phone, in Fenix there are around 380 px (190 dp) available for displaying the URL itself, whereas in Fennec this value is (depending how much of the fade out you count) approximately 460 - 470 px (230 - 235 dp). Fenix seems to partially compensate by using a smaller font size, but for the same amount of buttons in the URL bar, I can still see more of the URL in Fennec.

Fennec:
![fennec_url-width](https://user-images.githubusercontent.com/7611366/60299691-9b530c80-992d-11e9-959b-cf90be7c78e2.png)

Fenix:
![fenix-url_width](https://user-images.githubusercontent.com/7611366/60299693-9c843980-992d-11e9-88d3-e368f379e038.png)

**Comment by SubhamTyagi** [comment]
The usages of blank space between url bar, tab button, menu dots is excessive!


'https://' or 'http://' should be omitted from showing in url bar bcz these are redundant whenever a secure buttons is visible or there may be a preference for showing the url prefix.

**Comment by topotropic** [comment]
> The usages of blank space between url bar, tab button, menu dots is excessive!
We try to respect the 48x48dp touch target size to make it easier to navigate around.

> 'https://' or 'http://' should be omitted from showing in url bar bcz these are redundant whenever a secure buttons is visible
Yes, we can hide the protocol (http://, https://) to gain some space

**Comment by vesta0** [comment]
> > The usages of blank space between url bar, tab button, menu dots is excessive!
> 
> We try to respect the 48x48dp touch target size to make it easier to navigate around.

Fennec uses less blank space between tab button and 3-dot menu. Do we need all that space in order to have a usable touch target @topotropic ?

> > 'https://' or 'http://' should be omitted from showing in url bar bcz these are redundant whenever a secure buttons is visible
> 
> Yes, we can hide the protocol (http://, https://) to gain some space (cc @vesta0 does this sound ok to you?)

Yes or we can do what Fennec does = keep the http:// and https:// but keep it out of the visible URL area @topotropic

**Comment by topotropic** [comment]
@vesta0 yes, we need all that space to have usable touch targets, we might be able to make the touch target a tiny bit smaller but that won't do much to increase the visible URL part

What do you mean with "keep it out of the visible URL area"?

**Comment by buttercookie42** [comment]
That is referring to the fact that Fennec tries to scroll the URL such that the end of the host part aligns with the right edge of the URL bar, which means that for URLs where the host part doesn't fit within the width of the URL bar, it's the start of the URL (including the protocol) that gets pushed off the screen.

**Comment by Dunexus** [comment]
With the addition of the tracking shield icon, the url is even shorter than before. It uses less than half the width of the screen.

Fennec vs Fenix on OnePlus 5T (the red lines represent 25% and 75% of total width)
![image](https://user-images.githubusercontent.com/13906248/64864265-05c73f00-d637-11e9-9ab8-27367f9f842b.png)
![image](https://user-images.githubusercontent.com/13906248/64864487-7ec69680-d637-11e9-9be8-c760ae53c290.png)

**Comment by Amejia481** [comment]
Related https://github.com/mozilla-mobile/fenix/issues/4560

**Comment by nahuhh** [comment]
Posted #5302

**Comment by buttercookie42** [comment]
... and we don't even support webextension page actions yet, which would require space in the URL bar, too.

**Comment by vesta0** [comment]
We addressed this in #7077 7077
