### ISSUE TITLE
[Bug] Race Condition Crash in HomeFragment onPreDraw

### ISSUE THREAD

**Issue by colintheshots** [mozilla-mobile/fenix#3732]
## Steps to reproduce
1. Some combination of entering and exiting the HomeFragment very quickly.

### Expected behavior
The user correctly navigate back and forth without crashes.

### Actual behavior
The user crashes if the timing is just right with an IllegalStateException
https://sentry.prod.mozaws.net/operations/fenix-nightly/issues/5990843/

### Device information

* Android device: Pixel 2
* Fenix version: 1.0.0

**Comment by ekager** [comment]
All of this code was related to the shared element transitions and can be removed

**Comment by ekager** [comment]
Or commented out

**Comment by colintheshots** [comment]
Oh okay. I'd already changed the code to properly remove the listener, but I can comment or remove the dead code also.

**Comment by colintheshots** [comment]
Emily and I agreed that the onPreDraw listener is still being used to reset the UI, so I cannot comment out or remove any more than `startPostponedEnterTransition()` and `postponeEnterTransition()`.

**Comment by colintheshots** [comment]
This crash has stopped occurring and there are no STR for QA. Closing.
