### ISSUE TITLE
[Bug] Able to scroll home screen after tab long press 

### ISSUE THREAD

**Issue by Mardak** [mozilla-mobile/fenix#3734]
## Steps to reproduce
Long press a tab waiting for "collection" overlay and dragging more moves the tab (and if you drag to the side enough, it'll delete the tab behind the overlay).

Might be obsoleted by #2696

### Expected behavior
selected tab doesn't drag anymore

### Actual behavior
selected tab keeps moving

### Device information

* Fenix version: 1.0.0 / 68.0-20190611143747

**Comment by AndiAJ** [comment]
Hi, I wasn't able to delete the tab behind the overlay by swiping horizontally, on the other hand it offers the possibility to swipe up and down throughout the long tap, after releasing, no movements are possible.

I've used the latest Fenix Build ` #11850611 from 4/7` on the following devices:
• Google Pixel 3XL (Android 9)
• Samsung Galaxy S9 (Android 8)
• Samsung Galaxy S7 (Android 7.0)
• Samsung Galaxy S6 (Android 6.0.1)
• Sony Xperia Z3 (Android 5.1.1) 

►Video from Samsung Galaxy S9
![20190704_164803](https://user-images.githubusercontent.com/51314259/60672167-5b37e080-9e7d-11e9-857b-6c5eebefbff2.gif)

@ekager & @sblatz What is the desired behavior? no movement at all? or movement until the user stops long tapping ?
**I'll leave the ticket as it is until further clarifications.**

**Comment by ekager** [comment]
I think being able to scroll until you release is fine because there's no potential for data loss anymore. While it could still be considered a "bug", I'm going to unassign myself because I don't think the remaining issue is high priority.

**Comment by ekager** [comment]
And tagging @vesta0 to see if we just want to close this issue

**Comment by NotWoods** [comment]
@vesta0 should we close the issue?

**Comment by vesta0** [comment]
I agree with @ekager 's assessment and closing this.
