### ISSUE TITLE
[Bug] "search with" text is not aligned to anything 

### ISSUE THREAD

**Issue by Lululalu** [mozilla-mobile/fenix#3735]
### Expected behavior
The texting is aligned to something 

### Actual behavior
It looks like the text is just aligned to the left, or floating.
![Screenshot_20190627-182208_Firefox Preview](https://user-images.githubusercontent.com/32398857/60302024-2ec61680-9909-11e9-8b01-d77704f91391.jpg)

### Device information

* Android device: Galaxy A5 2017 8.0 
* Fenix version: 1.0.1926

**Comment by kbrosnan** [comment]
Looks to be aligned with the larger grey `Search or enter address` box

**Comment by sblatz** [comment]
This page was intentionally designed to align the search with text to the search box.

<img width="297" alt="image" src="https://user-images.githubusercontent.com/4400286/61572303-31bbaf00-aa50-11e9-9ba3-16f226e8d713.png">

Closing as expected behavior
