### ISSUE TITLE
DuckDuckGo as a globally available search provider

### ISSUE THREAD

**Issue by Seqularise** [mozilla-mobile/fenix#3736]
### Why/User Benefit/User Problem
i would like to use DDG in russian locale but i cannot choose it in settings or add it

**Comment by upsuper** [comment]
Same problem for Chinese locale.

Also if I switch to English locale, I can select DDG, but when I switch back to Chinese, the search engine is reset to Google again.

**Comment by cadeyrn** [comment]
> or add it

That's #1437.

**Comment by convoliution** [comment]
Based on half an hour of browsing around in the [`android-components`](https://github.com/mozilla-mobile/android-components/) repo, there does seem to be [a file that defines the default search engines for each locale](https://github.com/mozilla-mobile/android-components/blob/master/components/browser/search/src/main/assets/search/list.json), and we can see which locales don't include DuckDuckGo.

Side note, there seems to be a odd crisis deciding between ["ddg"](https://github.com/mozilla-mobile/android-components/blob/master/components/browser/search/src/main/assets/search/list.json#L196) and ["duckduckgo"](https://github.com/mozilla-mobile/android-components/blob/master/components/browser/search/src/main/assets/search/list.json#L206) ([ddg](https://github.com/mozilla-mobile/android-components/blob/master/components/browser/search/src/main/assets/searchplugins/ddg.xml) and [duckduckgo](https://github.com/mozilla-mobile/android-components/blob/master/components/browser/search/src/main/assets/searchplugins/duckduckgo.xml) have their own separate, _but identical_ xml plugin files) and I have no idea [what the plan is](https://github.com/mozilla-mobile/android-components/blob/master/components/browser/search/src/test/java/mozilla/components/browser/search/provider/AssetsSearchEngineProviderTest.kt#L219).

**Comment by kbrosnan** [comment]
There is a lot of process around shipping search engines. The path forward is custom search engines. Closing as a dupe of #1437
