### ISSUE TITLE
Faster way to delete a tab and open the next

### ISSUE THREAD

**Issue by Mardak** [mozilla-mobile/fenix#3738]
### Why/User Benefit/User Problem
Right now the steps in processing/finishing multiple tabs is to…
1) tap the tabs/multi icon
2) swipe the tab to delete (needing to drag more than 50% of the screen - really wide on landscape)
3) select the next tab

### What/Requirements
Maybe a swipe gesture on the tabs/multi icon with the usual "tab deleted [undo]" option in case that's not what the user wanted? I do see #176 has " swipe left/right on browser URL bar to go to previous/next open tab (P2)" which I suppose could help and then the user could mass close a bunch of tabs afterwards.

### Acceptance Criteria (how do I know when I’m done?)
Not needing many steps to do the equivalent of Firefox desktop's "close tab"

**Comment by devmedoo** [comment]
It's really inconvenient to swipe a tab to close it on my 5.5"(1080p) phone on both orientations.
You can detect the "momentum" of the swipe and go from there.

**Comment by vesta0** [comment]
@topotropic FYI :)

**Comment by topotropic** [comment]
Thanks for the feedback, we are looking into improving the tab switching experience as part of a bigger effort. I'll close the issue for now. Please feel free to re-open and add some additional context in case you disagree or have more feedback. Thanks again!
