### ISSUE TITLE
[Bug] Japanese introduction string is incomplete. Shows %s.

### ISSUE THREAD

**Issue by birtles** [mozilla-mobile/fenix#3741]
### Steps to reproduce
1. Open Firefox Preview on a Japanese device

### Expected behavior
Something sensible is displayed.

### Actual behavior
The string: "Firefox Preview へようこそ！%s を知ろう" is displayed
![Screenshot_20190628-080926](https://user-images.githubusercontent.com/1232595/60306867-1099fe00-997d-11e9-8968-f5791e6a667b.png)

### Device information

* Android device: Pixel 3
* Fenix version: 1.0.0 (Build #11721515 Gecko 68.0-20190611143747)

**Comment by kbrosnan** [comment]
When we released it was noted that there was one Japanese string that was not translated. Is this the problem that was called out @Delphine ?

**Comment by Delphine** [comment]
The placeholder '%s ' should be rendering as the app name. No idea why it's not in this case. Will poke around

**Comment by birtles** [comment]
Let me know if I can help with any additional information.

**Comment by flodolo** [comment]
CC @marsf

The string was [fixed 4 days ago](https://pontoon.mozilla.org/ja/android-l10n/all-resources/?search=を知ろう&string=199638), so it's not in the MVP. The original translation wasn't using `%s`, just something that looks like it `％s`, and breaks the replacement.

Note that we already fixed a bunch of these errors in Japanese when we enabled checks in Transvision ([example](https://github.com/mozilla-l10n/android-l10n/commit/ec762fcedcaadf7101bcfb2de2972721fd373459#diff-1c5587b0e94963296ae6c3030d6c8d62)), but this error was introduced after.

**Comment by divya21raj** [comment]
On it, will make a PR

**Comment by divya21raj** [comment]
Fixed, problem was ％ instead of % in the code for some reason.

**Comment by flodolo** [comment]
> On it, will make a PR

I don't think you should, because it's going to mess with automation (@pike would know for sure). 

Note that the string has already been fixed, we only need to export new translations to the repository. Also, that won't affected the current MVP, just next releases.

**Comment by Pike** [comment]
This is already in #3592, wating to merge.

**Comment by marsf** [comment]
It was introduced by my fault.
'％' is Japanese full-width character. It shouldn't be used in l10n.

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **Nightly Build #190724 from 24/7** using the following devices:
• Googe Pixel 3a (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• OnePlus 3 (Android 6.0.1)
• Sony Xperia Z3 (Android 5.1.1)

![Screenshot_20190724-140821](https://user-images.githubusercontent.com/51314259/61789359-2b954c00-ae1d-11e9-9027-9ff5d6f8859f.png)
