### ISSUE TITLE
Put onboarding flow in its own view

### ISSUE THREAD

**Issue by NotWoods** [mozilla-mobile/fenix#3743]
I think the onboarding cards should be in their own view rather than the recycler view for tabs and collections. It's items are always shown separate to the other recycler view items and the code would probably be simpler if it was a linear layout instead of a set of view holders.

**Comment by boek** [comment]
@NotWoods I do like the idea of taking this out, but we should talk with UX about this first. The initial idea with the cards is that new ones can be presented even after a new user was "onboarded". Kind of how we use them as "home screen tips" similar to what we did in Focus.

**Comment by NotWoods** [comment]
If we might want to show onboarding cards in the future let's not make this change. Thanks for the heads up :)
