### ISSUE TITLE
[Bug] Scrolling physics is way too fast on small swipes

### ISSUE THREAD

**Issue by fireph** [mozilla-mobile/fenix#3744]
The scrolling on Firefox mobile has been barely usable for me for a long time. It seems like it is the same way on fenix as well and I wanted to report the issue so that hopefully someday it can be fixed. I usually scroll with many small swipes and this behavior seems to have serious issues with the Firefox scrolling physics. I have posted a video of it in action (with touch overlays turned on).

## Steps to reproduce
Scroll on any page with small swipes back to back
Firefox fenix video: https://drive.google.com/file/d/19gAcB1Mk5gnalSL2yLW745jVZvKM5VUc/view?usp=sharing
Chromium Kiwi video: https://drive.google.com/file/d/1VA4FBdouq-oIhjbVbbU2DLAV2u_a_GSN/view?usp=sharing

### Expected behavior
Chromium scrolling physics

### Actual behavior
The scrolling moves crazy fast and scrolls down/up the entire page in a split second.

### Device information

* Android device: Pixel 2 XL
* Fenix version: 1.0.0

**Comment by cpeterso** [comment]
Is this bug still reproducible in Fenix Nightly?

https://play.google.com/store/apps/details?id=org.mozilla.fenix.nightly

**Comment by smartfonreddit** [comment]
> 
> 
> Is this bug still reproducible in Fenix Nightly?
> 
> https://play.google.com/store/apps/details?id=org.mozilla.fenix.nightly

It is still reproducible. 

To reproduce this, scroll the page down in short bursts while lifting your finger after each fling. Imagine you're browsing a page that has small images and you don't need to spend long periods on the screen after each fling, so you tend to make one tiny fling every 0.8 seconds.

Other browsers have it configured in a way that it doesn't accelerate the scrolling animation unless you fling more rapidly. This _"how often and how fast you fling before it accelerates"_ is what needs an adjustment in Firefox. 

I believe it started a year ago when Mozilla changed the scrolling animation to make it less slow. It used to be "sticky". That was solved a bit "too much". Now we have the reverse issue.

**Comment by DungFu** [comment]
Still reproducible on Fenix as well as regular Firefox

**Comment by cpeterso** [comment]
Botond says this issue is probably Gecko bug ("Two short flings can be faster on Fennec than Chrome"), which also affects Fennec: https://bugzilla.mozilla.org/show_bug.cgi?id=1458653.

**Comment by mcomella** [comment]
I added this issue to the Performance team's triage on Bugzilla: let's see how it gets prioritized for them.

**Comment by matteocontrini** [comment]
Has there been any progress on this issue? I find it quite annoying, it's the primary reason why I'm not using Firefox on Android.

**Comment by fireph** [comment]
I have given up on Firefox scrolling on Android. If this critical usability bug cannot be fixed in over a year, it will never be fixed.

I have moved on to just using Bromite as my privacy browser of choice.

**Comment by bmalin92** [comment]
Spent the past hour trying to figure out what was causing this. Currently the only browser on my phone that has this weird scrolling experience. Please try to resolve this before the Beta version release on the main app!

**Comment by cadeyrn** [comment]
> Please try to resolve this before the Beta version release on the main app!

I am not sure what do you mean. Firefox Beta was already migrated to Fenix and even the migration of the stable Firefox is already done in the first 27 countries and will be done in the other countries very soon.

**Comment by SebyakinAndrei** [comment]
I believe this issue is because of **apz.fling_accel_interval_ms** value is set too high. Setting its value to 150 solved this issue for me.
I think someone need to make a commit, because I believe that many users are annoyed by it.

**Comment by qeomash** [comment]
Thank you. I had had this fixed in the previous version by changing that `about:config` value (or a related ones), but since the Fenix rollout I have been unable to fix it thanks to `about:config` being locked out of stable.

**Comment by theres-waldo** [comment]
> Botond says this issue is probably Gecko bug ("Two short flings can be faster on Fennec than Chrome"), which also affects Fennec: https://bugzilla.mozilla.org/show_bug.cgi?id=1458653.

Note, this bug has recently been fixed in nightly (thanks @mstange !)

**Comment by mstange** [comment]
Yes, this issue can be closed. The bug is fixed in Firefox 84, currently on Beta.

**Comment by fireph** [comment]
The madlads actually did it and fixed this issue after 18 months!
