### ISSUE TITLE
[Bug] use sync credentials from Firefox for Android.

### ISSUE THREAD

**Issue by thewhitetulip** [mozilla-mobile/fenix#3745]
## Steps to reproduce

Install firefox preview after Firefox for Android

### Expected behavior

If preview is going to be a separate browser, please automatically log into my Firefox account.

If my original Firefox login exists, just detect it

### Actual behavior
Asks to login
### Device information

* Android device: ?
* Fenix version: ?

**Comment by grigoryk** [comment]
Most of the requirements to make this happen are under way or have already landed. Mostly, this is blocked on https://github.com/mozilla-mobile/android-components/issues/2775.

**Comment by cadeyrn** [comment]
> If preview is going to be a separate browser, please automatically log into my Firefox account.
>
> If my original Firefox login exists, just detect it

I don't have a problem with detecting a Firefox login and prefilling the login fields in Fenix. But an automatic login should never happen without user consent.

**Comment by thewhitetulip** [comment]
Well, we can ask, "We have detected that you've logged into firefox" just like Amazon prime does..

**Comment by vesta0** [comment]
We are addressing this in #2593
