### ISSUE TITLE
[Homescreen] Match Android notifications gesture to swipe to delete gesture on Open tabs

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/fenix#3747]
## Steps to reproduce

Swipe to close tabs. 

### Expected behavior

 Use the same swipe sensitivity as is used in Android notifications

### Actual behavior

Right now the swipe to delete gesture is is too hard to perform and it's hard to actually close tabs.

The change in  #3135 introduced this.

### Device information

* Android device: Pixel 2
* Fenix version: latest

**Comment by kbrosnan** [comment]
Dupe of #3738

**Comment by yoasif** [comment]
This isn't a dupe of #3738 -- that bug asks to be able to "close and next" - I'm simply asking for an improvement to the close gesture.
