### ISSUE TITLE
Prompt to save basic access authentication login details

### ISSUE THREAD

**Issue by nic0lette** [mozilla-mobile/fenix#3748]
### Why/User Benefit/User Problem

Currently the browser does not offer to save login details for basic authentication logins.

### What/Requirements

Firefox should offer to save the credentials of a basic authentication login and then pre-fill the fields when returning to the website.

Optional: Also include "auto-login" so the username/password are automatically sent on subsequent visits.

### Acceptance Criteria (how do I know when I’m done?)

The first time visiting a website with basic access authentication, the login prompt would be shown as it is today. The user fills in the username + password. Either in the dialog, or after the login was accepted, show a prompt (similar dialog or maybe a 'snackbar' on Android) asking if the password should be remembered.

At that time, or during the next visit, potentially prompt the user if they would like to automatically use the saved credentials to login in the future.

**Comment by vesta0** [comment]
Thanks @nic0lette ! We are planning to build this feature soon as part of #1284
