### ISSUE TITLE
[Bug] Crash when tapping "Blocked" on Google Maps after disabling location requests

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/fenix#3750]
## Steps to reproduce

1. Disable Fenix locations: Settings > Site Permissions > Location > Blocked
2. Navigate to https://maps.google.com
3. Tap lock icon in address bar
4. Tap "Blocked" near Location

### Expected behavior

Allow me to whitelist Google Maps (add an exception).

### Actual behavior

Fenix crashes

### Device information

* Android device: Pixel 2
* Fenix version: latest

**Comment by softvision-miralobontiu** [comment]
Verified with the latest Nightly build (#11840608) with Samsung Galaxy S8 (Android 9), and Google Pixel 3 (Android 9) - the app didn't crash.
