### ISSUE TITLE
Rearrange and rename items within a collection

### ISSUE THREAD

**Issue by kj** [mozilla-mobile/fenix#3751]
### Why/User Benefit/User Problem

As with bookmarks in the current Android app, I can't seem to rearrange items in a collection after they have been added. I also don't seem to be able to rename them.

### Acceptance Criteria (how do I know when I’m done?)

Can rearrange and rename items within a collection.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-12357)

**Comment by ekager** [comment]
You can rename a collection by pressing the three dot menu on that collection. You are correct you can't rearrange items within the collection

**Comment by kj** [comment]
I meant editing the name of items in the collection rather than the collection itself.

**Comment by venetian-ftaires** [comment]
This quickly jumped out at me as a missing feature. Definitely wouldike to see it.

**Comment by anotherus3r** [comment]
Also an option to rearrange the collections themselves.

**Comment by boek** [comment]
Dup of #8141
