### ISSUE TITLE
Collections UI uses a snackbar-like UI that feels out of place

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/fenix#3752]
## Steps to reproduce

1. Open some tabs
2. tap "Save to collection" button

### Expected behavior

A UI like the one displayed in Signal or Gmail when multi-selecting items -- or like appears in the Library UI. 

### Actual behavior

There is a purple snackbar-like widget at the bottom of the screen.

Issues:

* There is a "x" ghost button that exits the tab selection UI; this is ambiguous because users may believe this simply dismisses the "snackbar" instead of cancelling
* ghost button that appears when a tab is selected 
* this doesn't feel like Android 

### Device information

* Android device: Pixel 2
* Fenix version: latest

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-12358)

**Comment by mheubusch** [comment]
@topotropic as you review collections please review this and respond or close as appropriate.

**Comment by lime124** [comment]
removing ux label - we are collecting issues related to collections for a larger ux effort

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812767

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
