### ISSUE TITLE
Option to disable collections

### ISSUE THREAD

**Issue by sebast889** [mozilla-mobile/fenix#3753]
### Why/User Benefit/User Problem

For users who have no use for collections and won't be using it, takes up UI space

### What/Requirements

Option in settings to completely disable collections 

### Acceptance Criteria (how do I know when I’m done?)

Option in settings to completely disable collections

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-12359)

**Comment by NT20** [comment]
I've made a [poll on Reddit](https://www.reddit.com/r/firefox/comments/hxf8s6/add_an_option_to_completely_disable_collections/) to see what other think about this. Well it looks like I'm not the only one who doesn't like the Collections.

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812768

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
