### ISSUE TITLE
[Bug]Screen flickers when clicking a link from another app

### ISSUE THREAD

**Issue by TalibDota** [mozilla-mobile/fenix#3755]
## Steps to reproduce
Click a web link from another app (make sure Fenix is the default browser)
### Expected behavior
Transition to Fenix is smooth
### Actual behavior
Screen flickers
### Device information

* Android device: Google Pixel XL Android Pie
* Fenix version: 1.0.1926

Video - https://imgur.com/gallery/7dHUJKk

**Comment by sblatz** [comment]
This only happens after a cold boot if a user is in night mode. This is because we must re-create the activity after launching it to apply the dark theme. This is likely very difficult (or impossible) for us to fix without completely changing how we handle theming in the application.
