### ISSUE TITLE
Mark HTTP insecure (at least for password fields)

### ISSUE THREAD

**Issue by Madis0** [mozilla-mobile/fenix#3756]
### Why/User Benefit/User Problem
Users should be made aware that HTTP connections are not "normal", but unsecured. 
The desktop Firefox does it by showing [a broken padlock](https://design.firefox.com/icons/viewer/#secure%20broken) on the address bar of [HTTP sites with a password field](http://http-password.badssl.com/), and a warning popup on the password fields themselves.

It also has several relevant about:config options for enabling additional warnings, such as "Not secure" text and icon change on all or private windows. Current Fennec and Fenix lack all of that, placing users at a risk.

### What/Requirements
Implement the following about:config options from desktop Firefox:

- security.insecure_connection_icon.enabled
- security.insecure_connection_icon.pbmode.enabled
- security.insecure_field_warning.contextual.enabled
- security.insecure_password.ui.enabled

### Acceptance Criteria (how do I know when I’m done?)
- [ ] Default-enabled warnings on password fields
- [ ] Config options for private tabs
- [ ] Config options for all tabs

**Comment by NotWoods** [comment]
Thanks for filling this issue! I'm moving it to our [Android Components](https://github.com/mozilla-mobile/android-components) repository, where the relevant toolbar code lives.

mozilla-mobile/android-components#3647
