### ISSUE TITLE
[Bug] Login to Sync does not allow paste

### ISSUE THREAD

**Issue by guerda** [mozilla-mobile/fenix#3757]
## Steps to reproduce
1. Start Firefox Preview
2. Start Sync
3. Try to paste your mail address or password into the input field.

### Expected behavior
The Android context menu appears and you can select "Paste"
### Actual behavior
Currently, only the cursor appears, but no context menu at all. I can't paste my password into the password field.

### Device information

* Android device: Pixel 3
* Fenix version: Firefox Preview 1.0.0 Build #11721515 68.0-20190611143747

**Comment by ekager** [comment]
Related : https://github.com/mozilla-mobile/fenix/issues/3530

**Comment by guerda** [comment]
Thanks @ekager ! This does seem like the same issue.
I just tested it now and now the issue is gone. I was able to paste my mail address and my password into the Firefox Sync input fields. Thank you.
I'm still on the same version as above, which is weird.
