### ISSUE TITLE
Add the kabyle language 

### ISSUE THREAD

**Issue by SelyanKab** [mozilla-mobile/fenix#3763]
Please add the string.xml file and the values-kab, i would have Firefox preview in kabyle language and i am ready to translate the string file, i am a localizor in pontoon platforme but i don't see the localization project for preview there.

**Comment by kbrosnan** [comment]
@Delphine would you be able to give @S-AMIRI info on how to contribute a localization for Firefox Preview.

**Comment by Delphine** [comment]
@S-AMIRI We haven't opened up the project quite yet to more locales. I'm working on this and going to send an email on our dev-l10n mailing list very shortly about this. Localization will happen on Pontoon, as usual. Thanks!

**Comment by S-AMIRI** [comment]
Thank you somuch @Delphine and @kbrosnan

**Comment by ekager** [comment]
Going to close this specific language request
