### ISSUE TITLE
[Bug] Image slider issue

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#3764]
## Steps to reproduce
1. Navigate to https://m.emag.ro/

## Alternate STR
1. Navigate to https://m.emag.ro/
2. Request "Desktop site"

### Expected behavior
The images from the image slider aren't loaded

### Actual behavior
The images from the image slider are properly displayed

### Device information

* Android device: 
• Google Pixel 3XL (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7.0)
• Samsung Galaxy J7 (Android 6.0.1)
• Sony Xperia Z3 (Android 5.1.1)
* Fenix version: #11790617 from 28/6

#### ►Picture from Fenix
![Fenix](https://user-images.githubusercontent.com/51314259/60344297-e406d600-99be-11e9-8993-e0497f54ece6.jpg)

#### ►Picture from Firefox 67.0.3 (Playstore)
![Firefox](https://user-images.githubusercontent.com/51314259/60344301-e832f380-99be-11e9-8631-f021a1f23c76.jpg)

**Comment by sblatz** [comment]
@cpeterso is there a GV bug filed for this?

**Comment by ekager** [comment]
This is just a TP issue. With TP off these images load after a short delay. Closing
