### ISSUE TITLE
[Bug] Open website in App/Redirect to Google Play not working

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#3765]
## Steps to reproduce
1. Navigate to https://m.emag.ro/
2. Tap "Open in app" ("Deschide in aplicatie")
![apppppp (1)](https://user-images.githubusercontent.com/51314259/60346814-a60cb080-99c4-11e9-92ae-86fdfe5f4607.jpg)

### Expected behavior
The webpage will be opened in the app in case the user has it installed
In case the app ins't installed the user will be redirected to Google Play 

### Actual behavior
Nothing happens

### Device information

* Android device: 
• Google Pixel 3XL (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7.0)

* Fenix version: #11790617 from 28/6

### Notes
[Fenix behavior](https://drive.google.com/file/d/12J9CPuz1P49xzHjGgoYaLqDJCCVGbiO0/view?usp=sharing)
[ Firefox 67.0.3 behavior with installed app](https://drive.google.com/file/d/1PGmBmtfvTqMvKpC6q_ZeWxooO8T-Rfvq/view?usp=sharing)
[Firefox 67.0.3 behavior without installed app](https://drive.google.com/file/d/1D1hSHLRmpw9xRVzGN6fvMk7E3LXcRJk3/view?usp=sharing
)

**Comment by fotonmoton** [comment]
Can confirm, t.me links doesn't open in Telegram when opened by Fenix but work in Firefox for Android.

**Comment by kbrosnan** [comment]
Dupe #1570
