### ISSUE TITLE
[Bug] Twitch.tv app cannot be opened from Fenix

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/fenix#3766]
## Prerequisite
Install twitch app from the play store.
## Steps to reproduce
1. Launch Fenix.
2. Tap on the URL bar.
3. Access **`www.twitch.tv`**
4. From the top bar, tap on the **`Open in App`.**
### Expected behavior
Twitch app should open.
### Actual behavior
Nothing happens.
### Device information
* Android device: **`Samsung Galaxy Note 9(Android 8.1.0).`**
* Fenix version: **`6/28`**.
* [Video](https://drive.google.com/file/d/1BuB9SgEe2rF33ED6i-1kC_3w2oBP-bZU/view?usp=sharing)

**Comment by AaronMT** [comment]
https://github.com/mozilla-mobile/fenix/issues/3177

**Comment by abodea** [comment]
@AaronMT when I tap on that button using `Chrome` the `twitch app` is opened. On FF RC and Focus a custom tab is opened.
The thing is once I have the twitch app installed, maybe the best option is to be opened when I tap on that button and in case I don`t have it installed to open play store.

**Comment by sblatz** [comment]
@abodea I believe this should be fixed in the latest nightly due to https://github.com/mozilla-mobile/fenix/pull/4101
