### ISSUE TITLE
[Bug]At the search page, Fenix couldn‘t back to the main page

### ISSUE THREAD

**Issue by PowERGD** [mozilla-mobile/fenix#3767]
## Steps to reproduce
1. Launch Fenix.
2. Press "search" .
3. Close keyboard.
4. Press [back]button.

### Expected behavior
Back to the main page.
### Actual behavior
Close Fenix.
### Device information

* Android device: Xiaomi Redmi 4 Prime Android 9
* Fenix version: v1.0.0

**Comment by julKali** [comment]
I'll look into this 👍

**Comment by ekager** [comment]
closing as dupe of #3587
