### ISSUE TITLE
Consider changing swipe sensitivity on home screen tabs

### ISSUE THREAD

**Issue by FN2187fo** [mozilla-mobile/fenix#3768]
You need to swipe over 50% of the screen to close a tab by swiping, which is way too much. I usually don't even get to 25% and it works just fine with most browsers.

![ezgif-5-2d6918ad31bb](https://user-images.githubusercontent.com/48321566/60350329-9b055080-99c3-11e9-8345-bddef605dedb.gif)

**Comment by julKali** [comment]
I totally agree with you about this and it annoys me as well. It shouldn't be too much work to change this, I will take a look.

**Comment by sblatz** [comment]
@ekager has a PR open for this 😄 
https://github.com/mozilla-mobile/fenix/pull/3770

**Comment by julKali** [comment]
Welp, less work for me then ^^

**Comment by sblatz** [comment]
I will convert this to a UX review ticket so we can revisit the sensitivity after Emily's PR!

**Comment by yoasif** [comment]
I suggested "Use the same swipe sensitivity as is used in Android notifications" in #3747

**Comment by mheubusch** [comment]
@topotropic can you review emily's update and if the sensitivity is as you expect, please close this  issue.

**Comment by yoasif** [comment]
@ekager's update was just reverting the already problematic swipe sensitivity. That was less bad than before the revert, but it isn't "fixed" yet.

**Comment by vesta0** [comment]
Will be addressed in #3770
