### ISSUE TITLE
[Bug] Firefox Preview shows up as Firefox Sync on Devices and apps PC

### ISSUE THREAD

**Issue by miladmaz12** [mozilla-mobile/fenix#3769]
## Steps to reproduce

1. Go to devices and apps on Firefox PC under your account settings

### Expected behavior

Needs to show Firefox Preview on Mobile

### Actual behavior

Instead shows Firefox Sync

### Device information

* Android device: Pie 9.0.0
* Fenix version:  1.0.0

**Comment by grigoryk** [comment]
This is a known problem on the FxA service side of things, currently being worked on. I'll link to a relevant tracking issue.

**Comment by grigoryk** [comment]
Good issue for this with a discussion/links: https://github.com/mozilla-mobile/fenix/issues/2831

Closing as a duplicate.
