### ISSUE TITLE
[Bug] Unable to select DuckDuckGo as search engine on Firefox Preview

### ISSUE THREAD

**Issue by shellkr** [mozilla-mobile/fenix#3776]
### Why/User Benefit/User Problem
I wouldn't chose a privacy minded browser and then only have Google as a search provider. Will not be able to use this app until that is possible.

### Acceptance Criteria (how do I know when I’m done?)
Make DuckDuckGo available as search engine from start or at least make it possible to install.

**Comment by kbrosnan** [comment]
Dupe of #3736
