### ISSUE TITLE
Create pref to disable FIRST_RUN for UI tests

### ISSUE THREAD

**Issue by rpappalax** [mozilla-mobile/fenix#3777]
We run UI tests sharded on individual devices so each test will bring up a fresh install of fenix.  We'd like a way to disable the first-run experience via a pref to save time, similar to what we had for Focus android:  https://github.com/mozilla-mobile/focus-android/blob/master/app/src/androidTest/java/org/mozilla/focus/activity/BadURLTest.kt#L48-L51

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-12380)

**Comment by ekager** [comment]
@sblatz I see a PR referencing this, can this be closed or is this still something you're working on?

**Comment by sblatz** [comment]
QA felt the solution I implemented was not sufficient to close this ticket so let's keep it open for now.

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807308

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
