### ISSUE TITLE
[Bug] Unable to sign-in to Google account

### ISSUE THREAD

**Issue by spencergilbert** [mozilla-mobile/fenix#3779]
## Steps to reproduce
Might be similar to #3304, tested with and without tracking protection. Account has 2FA with a physical key

### Expected behavior
Sign in successfully

### Actual behavior
Recover account gets me into a loop there
![Screenshot_20190628-165221](https://user-images.githubusercontent.com/11903873/60371423-3815b880-99c7-11e9-9e56-bfc688c53975.png)
### Device information

* Android device: Pixel 3a, 
* Fenix version: 1.0.0

**Comment by NotWoods** [comment]
Is this still reproducible?

**Comment by spencergilbert** [comment]
It seems like at some point since reporting it's resolved. Don't appear to have any issues now.
