### ISSUE TITLE
[Meta] Basic Library UI

### ISSUE THREAD

**Issue by ekager** [mozilla-mobile/fenix#378]
See #177 for UI ticket

**Comment by mheubusch** [comment]
Engineering - please review the items on this spreadsheet - this is a punchlist showing fit and finish issues blocking feature completeness.

https://docs.google.com/spreadsheets/d/1UOoZLuZRSFK5y-03WLjNkruDTXt-sft-_aMkU8w1WHA/edit?usp=sharing

**Comment by vesta0** [comment]
@mheubusch the google doc has a few incomplete items, are there separate issues filed for those and can we close this meta?

**Comment by vesta0** [comment]
Closing this meta as this feature has been built. Any outstanding bugs and enhancements can be filed as separate issues.
