### ISSUE TITLE
[Bug] Lastpass password form fill not working

### ISSUE THREAD

**Issue by kbsletten** [mozilla-mobile/fenix#3781]
## Steps to reproduce
Install FF Preview & Lastpass
Save passwords for news.ycombinator.com and firefox.com
Visit news.ycombinator.com
Click "log in"
### Expected behavior
See password auto fill for news.ycombinator.com
### Actual behavior
See password auto fill for firefox.com
### Device information
Samsung Galaxy J3 V
Android 8.0.0
Patched May 1, 2019

* Android device: ?
* Fenix version: ?

**Comment by caesar** [comment]
Same problem with Keepass2Android.

Works in Fennec.

**Comment by sv-ohorvath** [comment]
duplicate: #87

**Comment by IndefiniteBen** [comment]
Fixed in the current Lastpass beta, see #87.

**Comment by skewty** [comment]
Mine hangs every time at mailbox decryption running Firefox 71.0 with LastPass 4.39.0.2.

Has there been a regression?

**Comment by cadeyrn** [comment]
@skewty: The current version of Fenix is 3.0.0 not 71.0. Also I don't think there are "right clicks" on a smartphone or tablet. Are you sure you're commenting in the correct issues tracker?

**Comment by skewty** [comment]
@cadeyrn yes, wrong issue tracker.  Removing previous, comment.
