### ISSUE TITLE
[Bug] Crash loading bookmarks while detached

### ISSUE THREAD

**Issue by colintheshots** [mozilla-mobile/fenix#3784]
## Steps to reproduce
Unclear steps to reproduce. Open bookmarks fragment and browse quickly to a massive folder and select one immediately.

### Expected behavior
Bookmarked page will load.

### Actual behavior
BookmarkFragment will crash as the fragment is detached and the coroutine will crash if the activity is null.

### Device information

* Android device: Moto X4
* Fenix version: 1.0.1926 Nightly

**Comment by ekager** [comment]
@colintheshots do we think this is resolved?

**Comment by colintheshots** [comment]
It hasn't been seen in Nightly since July 1st which corresponds to when it was fixed. It seems resolved.
https://sentry.prod.mozaws.net/operations/fenix-nightly/issues/5991083/?query=is:unresolved%20bookmark

**Comment by colintheshots** [comment]
Closing since there are no steps to reproduce for QA.
