### ISSUE TITLE
[Bug] Doesn't execute on install, instead returns an error

### ISSUE THREAD

**Issue by dmxt** [mozilla-mobile/fenix#3789]
## Steps to reproduce
Install app with almost all Mozilla apps installed and running just fine

### Expected behavior
Run an app

### Actual behavior
Returns error and doesn't open an app

```
Can't install Firefox Preview

Try again, and if it still doesn't work, see
common ways to fix the problem

SEND FEEDBACK

OK
```
### Device Information
OnePlus 5 on Oxygen 9 🥧 UNROOTED

* Android device: OnePlus 5
* Fenix version: _??_

![Screenshot of an error](https://i.imgur.com/7w7gxEN.png)

**Comment by AaronMT** [comment]
Try clearing Google Play store's cache. If that doesn't work, our APK is available here https://github.com/mozilla-mobile/fenix/releases
