### ISSUE TITLE
[Bug] Requesting desktop site on derstandard.at does not work

### ISSUE THREAD

**Issue by Wasseranomalie** [mozilla-mobile/fenix#3790]
## Steps to reproduce
https://youtu.be/ToCu76RaWSI
- Visit https://mobil.derstandard.at
- Click the hamburger menu on the top right corner
- Click "Versionen" on the top left
- Click "Vollversion" below the "Versionen" bar
- Confirm dialog by clicking "OK"

Using the "request desktop site" functionality of fenix also reloads into the mobile page

### Expected behavior

Site reloads showing the desktop version of the site

### Actual behavior

Nothing happens

### Device information

* Android device: LG Nexus 5X, Android 8.1
* Fenix version: 1.0.1926 (Build #11780609 68.0-20190612114833)

**Comment by julKali** [comment]
Can It actually works if you click on Vollversion again shortly after the first attempt. Nevertheless, it shouldn't take two clicks. So the bug still stands.

**Comment by ekager** [comment]
Using the Fenix toggle worked for me on the first try on latest build. Could you please retest?

**Comment by julKali** [comment]
Since the issue was opened derStandard updated their website and thereby completely changed their layout/design. You cannot reproduce this issue anymore.

**Comment by AndiAJ** [comment]
Hi, verified as fixed on the latest **Nightly Build #12240720 from 12/8** using the following devices:
• Google Pixel 3a (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• OnePlus A3 (Android 6.0.1)
• LG Nexus (Android 5.1.1)

►Video Pixel 3a
![20190812_144039](https://user-images.githubusercontent.com/51314259/62862978-2b97b600-bd10-11e9-974c-067b75029e82.gif)
