### ISSUE TITLE
Thank you for using GitHub as a distribution channel

### ISSUE THREAD

**Issue by arunsathiya** [mozilla-mobile/fenix#3796]
This is not a bug report/feature request.

I happened to come across Firefox Preview (Firefox Fenix) for the first time today, and the links on [this blog post](https://blog.mozilla.org/futurereleases/2019/06/27/reinventing-firefox-for-android-a-preview/) lead me to Google Play Store.

I do not have a Google account, which is a primary blocker for me to use Android apps. I took a look at [your releases page](https://github.com/mozilla-mobile/fenix/releases) and interestingly, the APKs were listed. Most products (even if they were developing in the open) do not list their APKs here. So, I was naturally surprised to see it.

Thank you for using open distribution channels like GitHub. Please feel free to close this GitHub issue.

**Comment by AaronMT** [comment]
Thanks.
