### ISSUE TITLE
Quicker access to currently opened sites

### ISSUE THREAD

**Issue by PiotrSss** [mozilla-mobile/fenix#3798]
### Why/User Benefit/User Problem

Quicker access to currently opened sites, when user don't need to look at page titles/urls, but can recognize desired site by looking at miniature. As an addition to current "Open tabs & Collections" page.

### What/Requirements

Swipe up to open panel with "Share", "Bookmark", "Read", swipe up even more to open another panel with gallery of sites. Scroll horizontally to see stuff on the left and right. Click miniature to open. Click, hold and swipe up to close (if it was currently opened page, open page on the right (or on the left, it depends how many pages there was and where was the current one located), and if it was the only page in stack, open "Open tabs & Collections" page). Maybe some additional popup menu after holding miniature a little bit longer: [close | duplicate | open new on left | open new on right].

### Acceptance Criteria (how do I know when I’m done?)

![](https://i.imgur.com/IvqNyMl.jpg)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-12393)

**Comment by smartfonreddit** [comment]
No other browser has this feature. It could revolutionize how we multitask. Swiping up and staying on the same screen to select tabs is more seamless than the disruptive process of navigating away onto a different window (current tab manager).  The tab thumbnails could be bigger than in the image above, and could have the title near the image. 
I'd love to see the Share and Bookmark buttons moved under the browser's menu button, and have the entire swipe-up panel dedicated for the proposed tab management. 
Or, swiping up from address bar could open the existing share/bookmark panel, while swiping up from the tabs button could open the proposed tab manager panel.

**Comment by cadeyrn** [comment]
My first thought was that a tab switcher doesn't belong there because the quick action bar is for page specific actions. But the longer I think about it, the more I like the idea. It would also make #3758 obsolete. Fenix can keep the current UI on the home screen which is not bad at all and this proposal brings an additional quick way for switching tabs with an "Opera like UI", but in a revolutionary way. This proposal allows to keep the best from both worlds.

**Comment by Madis0** [comment]
The previews should be larger or be replaced by favicons (but should clearly look like tabs, not bookmarks etc). 
The panel should definitely open in one go, not as two variants (with and without tabs). 
The tab bar needs a plus button on the right end for creating a new tab.

**Comment by panpiotrs** [comment]
Cool, I'll make additional and better mockups, I have many ideas of mixing those two functionalities, maybe some will be approved by the team and done one day.

**Comment by vesta0** [comment]
@topotropic FYI :)

**Comment by thecyberpope** [comment]
I saw this mock-up and hope it becomes reality! A nice swipe interface would improve browsing QoL by a huge margin. 

I took your idea and created some mock-ups of my own. 

1. Integrate the share/bookmark/reader buttons into each tab - button sizes might need to be adjusted.
2. Old tab button becomes a new tab button
3. Swipe up to close tab with undo button.

![screenshot1](https://user-images.githubusercontent.com/52714681/60912360-68204f80-a242-11e9-8912-7d6f82586310.png)
![screenshot2](https://user-images.githubusercontent.com/52714681/60912361-68204f80-a242-11e9-8df6-0302a25e4850.png)

**Comment by Madis0** [comment]
@thecyberpope 
Please elaborate on
>Integrate the share/bookmark/reader buttons into each tab - button sizes might need to be adjusted.

Right now on the mockups these are only shown on the tab previews - they are tiny and should not be visible at all IMO

**Comment by lime124** [comment]
added to a larger QAB effort - removing ux label.
