### ISSUE TITLE
Email and WhatsApp "share" links on Amazon does not work

### ISSUE THREAD

**Issue by paddg** [mozilla-mobile/fenix#3799]
## Steps to reproduce
Go to a Amazon product, klick "Share" and Email or whatsapp

### Expected behavior
Email or Whatsapp App starts

### Actual behavior
Nothing. Or FF claims there is no WhatsApp installed on this device.

### Device information

* Android device: OnePlus 6T
* Fenix version: Firefox mobile 1.0.0 preview

**Comment by kbrosnan** [comment]
This is two separate issues. #1570 for app intents and one for supporting common protocols such as mailto: or tel:
