### ISSUE TITLE
[UX] PWA + Private Mode

### ISSUE THREAD

**Issue by bbinto** [mozilla-mobile/fenix#380]
Design work on exploring PWA + privacy options

**Comment by brampitoyo** [comment]
Just a short status update:

1. We’ve met with @vesta0, Tanvi, Wennie and Arthur to discuss three possible approaches to this problem
2. My task is to mock up and provide user flows for these approaches, then present them in the next meeting
3. I’ve posted an alpha version of one user flow (out of three) to Fenix UX, for critique and feedback

**Comment by bbinto** [comment]
@brampitoyo - can you please size this for us

**Comment by brampitoyo** [comment]
Option 1 is the easiest in terms of UX. It will require nothing but changing favicon and adding an onboarding message for the feature.

Option 2 is the hardest. It will require shipping an entirely separate app on the Play Store.

Option 3 is medium effort. Much of that effort will be focused on engineering PWA support into the site ourselves – as the site doesn’t endorse or support PWA support, unlike Twitter for example.

In terms of UX, all three options have been mocked up and completed. It may be revised later on, but I don’t see it taking too long.

**Comment by bifleming** [comment]
@brampitoyo I'm learning... :) Does your comment mean that this issue is done? @bbinto Is the next step to create a related Engineering issue?

**Comment by colintheshots** [comment]
The options aren't linked here, so we don't have much to assess from an engineering standpoint.

**Comment by bbinto** [comment]
@colintheshots please work with @vesta0 on how to best break these tasks into issues and to keep confidentiality

**Comment by vesta0** [comment]
I sent an email to the team asking for feedback earlier this week. @colintheshots please take a look before sprint planning.

**Comment by vesta0** [comment]
Engineers will investigate dependencies and break down. Will also pull @pocmo into the discussion.

**Comment by bbinto** [comment]
@vesta0 if there is an eng / epic issue for this specific feature, we probably need to move this out of MVP as well.
