### ISSUE TITLE
Unable to download .zip file

### ISSUE THREAD

**Issue by FN2187fo** [mozilla-mobile/fenix#3800]
Trying to download a .zip file gives an error. Video is in german, but the error says "Firefox Preview can not download this fil format"
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/48321566/60387845-f873cd00-9aa9-11e9-8b40-021d834e3bbe.gif)

**Comment by AaronMT** [comment]
Triage: Feel free to dupe to appropriate already open issue

**Comment by kbrosnan** [comment]
Dupe #1657

**Comment by FN2187fo** [comment]
That was not the issue I had. My download didn't even start as you can see from the video.

**Comment by kbrosnan** [comment]
The changes in 1657 will dramatically change how downloads work. It should fix most issues with downloading when implemented. For now that is a good enough place to track your issue.
