### ISSUE TITLE
Add image blocking option

### ISSUE THREAD

**Issue by alois31** [mozilla-mobile/fenix#3802]
### Why/User Benefit/User Problem
Image blocking is one of the best ways, if not the best, to save data/page loading time.
### What/Requirements
Expose an option to block images in the settings. Ideally, this would be images on/only on wifi/blocked, with an option to selectively unblock (like in Fennec).
### Acceptance Criteria (how do I know when I’m done?)
When the aforementioned option is present and working.

**Comment by kbrosnan** [comment]
Dupe #3457
