### ISSUE TITLE
[Bug] Report Site Issue button should be positioned near help option

### ISSUE THREAD

**Issue by adamopenweb** [mozilla-mobile/fenix#3803]
## Steps to reproduce
1. Open Fenix
2. Press menu button (vertical meatballs)
3. Notice position of `Report site issue` in order

### Expected behavior
Position is close to the top of the list, near Help.

### Actual behavior
Position is second from the bottom.

### Device information

* Android device: Pixel 2
* Fenix version: 1.0

Minor issue.
The position of the button should not be in valuable one handed real estate on the screen. Hopefully it is a lesser used feature. IMO it makes send to have it positioned near the Help option.

![image](https://user-images.githubusercontent.com/6587558/60388642-9358b100-9a82-11e9-995b-4d34ca14c5c2.png)

**Comment by reinhart1010** [comment]
As what I've said in webcompat/webcompat.com#2214, the webcompat.com site should start redirect users to Google Safe Browsing report page for security issues (e.g. scams and viruses), especially for those who discovered the obscure, "Report Web Forgery" feature in desktop.

IMO the "Report site issue" label in Fenix doesn't clearly explain what type of issues the user is expected to report - so chances of `non-compat` (issues which are outside of the scope of Web Compatibility) reports could increase once Fenix is released into production.

**Comment by ekager** [comment]
Moving this makes sense to me, but tagging UX

**Comment by lime124** [comment]
collecting this as part of a bigger design effort to look at the items in the menu. removing label.

**Comment by apbitner** [comment]
'Report site issue' has been moved near the top of the list
