### ISSUE TITLE
[Bug] crash when opening collections

### ISSUE THREAD

**Issue by thewhitetulip** [mozilla-mobile/fenix#3807]
## Steps to reproduce

add a site to collection, click on it (create 2 collections at least)

### Expected behavior

clicking site should open it

### Actual behavior

crashes the browser

### Device information
Colour OS  
* Android device: android 8
* Fenix version: 1.0.0

**Comment by Geojackson** [comment]
How to delete

**Comment by Transfusion** [comment]
I don't seem to be able to replicate this, attached is a video of me creating two collections and using save to collection. I'm using Android 8.0.0 (MIUI 9.5 dev) on a Xiaomi Mi 6.

[transfusion_fenix_collections_test.mp4.zip](https://github.com/mozilla-mobile/fenix/files/3342650/transfusion_fenix_collections_test.mp4.zip)

**Comment by kbrosnan** [comment]
Please provide a crash log. See https://github.com/mozilla-mobile/fenix/wiki/Logging-Crash-Information for steps on how to do this.

**Comment by thewhitetulip** [comment]
I had sent a crash report the moment it had crashed, if it is of any help.

**Comment by thewhitetulip** [comment]
Even I can't recreate it now
