### ISSUE TITLE
[Meta] Make the domain URL more visible in the address bar

### ISSUE THREAD

**Issue by amkcpu** [mozilla-mobile/fenix#3809]
### User Story
As a user, I want to be able to easily review the entire URL (not just the top-level domain) when I look at the address bar, so I know that I am on the site I want to be on.

For UX/ENG: Perhaps we can either allow user to scroll the URL OR remove the http/https/www

### Acceptance Criteria

-I can see the domain URL of the site I am on.

### Notes
- There are potential security problems involved in shortening URLs.  [This doc](https://chromium.googlesource.com/chromium/src/+/master/docs/security/url_display_guidelines/url_display_guidelines.md) covers a lot of best practices for URL display.  [This one](https://url.spec.whatwg.org/#security-considerations) is denser, but has useful general information about URLs.

### Changelog
- @Baron-Severin 11-12: added Notes section

**Comment by kumarharsh** [comment]
Yeah, that was a nifty feature. Although I feel that it might conflict with the new UX where you can long oress to copy URL...

**Comment by buttercookie42** [comment]
Firefox/Fennec has a long press context menu on the URL bar, too, so that shouldn't be a problem.
The problem will rather be co-existing with a swipe-URL-bar-to-switch-tabs gesture, which apparently is a long sought-after feature for a number of other users.

**Comment by Madis0** [comment]
I would suggest simply showing the full URL on the page info popup, like Chromium.

**Comment by TinyBeard** [comment]
I second that. Ability to take a peek at entire URL would be very useful and convenient via horizontal swipe left/right gestures on the URL area. AFAIK the copy-on-long-press action has been pulled back so there's no conflict too (also it's not really a conflict since long press can be treated as a different input action than swipe).

**Comment by ekager** [comment]
The action we took for now in #6641 was to show the full URL in the security popup

**Comment by sv-ohorvath** [comment]
> The action we took for now in #6641 was to show the full URL in the security popup

Verified as fixed on Nightly 11/19.
