### ISSUE TITLE
Technical article promoting fenix

### ISSUE THREAD

**Issue by simonsteiner1984** [mozilla-mobile/fenix#3811]
### Why/User Benefit/User Problem

Help promote fenix

### What/Requirements

What low level changes were made so its faster than firefox (saying you switched to geckoview is not enough detail)

### Acceptance Criteria (how do I know when I’m done?)

I can read this somewhere

**Comment by sblatz** [comment]
This is not really an engineering ticket, and I'm not sure where it should live. @lwa-moz is this something you could file somewhere?

**Comment by sblatz** [comment]
@simonsteiner1984 this is something we'll look into, but we do have [some information about GV](https://hacks.mozilla.org/2019/06/geckoview-in-2019/) published if you're interested :)

**Comment by vesta0** [comment]
@liuche we chatted about this at group triage and it's definitely worth doing at some point so let's think about how/when.

**Comment by liuche** [comment]
Would SUMO be the right place for this? or possible the Mozilla Mobile Medium! https://medium.com/firefox-mobile-engineering

We should definitely get this out before Q4, but I'm also wondering who is the right person to write/collaborate on this. Gecko🦎 is definitely part of the answer though - could be a series (Gecko, UX based on user studies, etc).

**Comment by sblatz** [comment]
Going to hand this off to our dev relations team :)

**Comment by sblatz** [comment]
I've spoken with the dev relations team and they are willing to publish an article so long as we can provide the heavy content. Let's pull this into an upcoming sprint and publish on [Hacks](https://wiki.mozilla.org/Devrel/Hacks).

**Comment by simonsteiner1984** [comment]
How come this was closed
