### ISSUE TITLE
[Bug] The "Share" button icon is bigger than "⋮" icon

### ISSUE THREAD

**Issue by kkt-yu** [mozilla-mobile/fenix#3814]
## Steps to reproduce
firefox preview set default browser. And use feedly app at "settings -> Preferred Browser -> Built-in".
### Expected behavior
Share icon is same size as "⋮".
### Actual behavior
Share icon is bigger then "⋮".
### Device information

* Android device: Xperia 10
* Fenix version: Firefox Preview 1.0.0

**Comment by ekager** [comment]
Closing for mozilla-mobile/fenix#5330 and https://github.com/mozilla-mobile/android-components/issues/4457
