### ISSUE TITLE
[Bug] Bottom bar won't go back to its position when browsing open tabs

### ISSUE THREAD

**Issue by Bengaa** [mozilla-mobile/fenix#3815]
## Steps to reproduce
Go to the open tabs section, tap on the search field while the keyboard shows up, then try scrolling up or down without closing the keyboard yourself.
### Expected behavior
The keyboard is disappearing because of the scrolling and the bottom bar goes back to place.
### Actual behavior
The bottom bar won't go back to its original position.
![Screenshot_20190630-232430](https://user-images.githubusercontent.com/32507969/60425380-ac806f80-9bf2-11e9-9fc0-0aba33ae3d81.png)

![Screenshot_20190630-232438](https://user-images.githubusercontent.com/32507969/60425156-38de6280-9bf2-11e9-94f4-da9e044f87fe.png)

### Device information
Xiaomi Mi A2 Lite
* Android device: Android version 9
* Fenix version: 1.0.0 (Build #11721515 🦎 68.0-20190611143747)

**Comment by cadeyrn** [comment]
I can reproduce in Fenix 1.0.0, but it seems already to be fixed in master branch.

**Comment by ekager** [comment]
Yes! Fixed by https://github.com/mozilla-mobile/fenix/pull/3697
