### ISSUE TITLE
[Bug]Behaviour after full screen mode

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#3819]
## Steps to reproduce
1. Go to youtube
2. Open a video in full screen
3. Press the home button
4. Open Fenix again

### Expected behavior
Should Fenix resume in full screen with the video paused?

### Actual behavior
Video is resumed in normal view and is not paused 

### Device information

* Android device: 
• Google Pixel 3XL (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7.0)
• Samsung Galaxy J7 (Android 6.0.1)
• Sony Xperia Z3 (Android 5.1.1)

* Fenix version:   Fenix #11791805 from 28/6

### Notes
This is related to bug #1722 as we don't know how Fenix should resume from full screen mode

► Video from Samsung Galaxy J7 (Android 6.0.1)
![2019_06_28_14_26_43 (1)](https://user-images.githubusercontent.com/51314259/60434981-1740a380-9c11-11e9-8673-6defc87d4ccd.gif)

**Comment by ekager** [comment]
We had previously made a decision to exit fullscreen mode when the app is paused, but we can readdress this issue with UX and product.

**Comment by kbrosnan** [comment]
The current behavior is safer. Consider the following

* Have a web page that convinces you to go full screen
* Use JS onBlur() to substitute the full screen for a login page for bank, online service or fake the Fenix UI to phish the user's Firefox Account.

**Comment by mheubusch** [comment]
@vesta0 per Kevin's feedback I recommend we close. Are you ok with that?
