### ISSUE TITLE
'Set default browser' on Android 6 and older is missing functionality

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#382]
## Steps to reproduce
1. On a device running Android 5 or 6, go to Settings> Set default browser.
2. Turn the toggle on.
### Expected behavior
-to be determined. A SUMO page like on Focus (?).
### Actual behavior
The toggle is switched on but it has no effect for now. 
### Device information

* Android device: Android 5 & 6.
* Fenix version: 1.0

**Comment by kbrosnan** [comment]
We need to fix this for MVP or remove the menu item in versions where it will do nothing. On Fennec 20% of our user base is on Android 5.1 or Android 6. The engineering requirements are fairly small once SUMO provides us with a link to the support article.

**Comment by jonichan** [comment]
Here's the SUMO link you can use: https://support.mozilla.org/1/mobile/%VERSION%/%OS%/%LOCALE%/set-firefox-preview-default

**Comment by vesta0** [comment]
We already have this Sumo page to link to: https://support.mozilla.org/en-US/kb/how-set-firefox-preview-your-default-browser-android

**Comment by softvision-miralobontiu** [comment]
I confirm that the "Set default browser" option from Settings is removed from devices with Android 5&6.
