### ISSUE TITLE
replace Disconnect block list with custom adblock and tracking protection list choose by user

### ISSUE THREAD

**Issue by gpdevsoft** [mozilla-mobile/fenix#3821]
### Why/User Benefit/User Problem
improve security and tracking protection if a user can choose the source of blocklist like Steven Black'a Hosts instead Disconnect list
### What/Requirements
under tracking protection's option user can add one or more url blocklist that can be used by fenix to replace default Disconnect list
### Acceptance Criteria (how do I know when I’m done?)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-12413)

**Comment by kbrosnan** [comment]
This has not revived any duplicates or other interactions since it was filed. We will not be moving this request to Bugzilla.
