### ISSUE TITLE
[Bug] Browser toolbar not spaced properly

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#3824]
The left and right margins on the lock icon of `displayToolbar` are not even. 

<img width="350" alt="image" src="https://user-images.githubusercontent.com/4400286/60453147-2a3d7e80-9be5-11e9-8951-c52569336571.png">

**Comment by ibrahimAlii** [comment]
@sblatz I think lock icon margin is equal, maybe url itself has extra padding 2X lock icon size

https://github.com/mozilla-mobile/android-components/blob/cb458ca20b62d22772b178e52477ca65af425e5e/components/browser/toolbar/src/main/java/mozilla/components/browser/toolbar/display/DisplayToolbar.kt#L78

**Comment by ekager** [comment]
This was fixed in AC recent toolbar changes
