### ISSUE TITLE
[Bug] text in address bar is tiny

### ISSUE THREAD

**Issue by Mossop** [mozilla-mobile/fenix#3827]
## Steps to reproduce

Open Fenix. Start entering a URL.

### Expected behavior

Be able to read the text in the address bar.

### Actual behavior

Have to bring device close to my face to be able to read the address bar.

### Device information

* Android device: Moto G7
* Fenix version: 1.0.0

**Comment by lime124** [comment]
@Mossop can you include a screenshot for me so we can make sure we are seeing what you are seeing?

@colintheshots does UI match the spec that was designed?

**Comment by Mossop** [comment]
Looks like the url bar text matches the urls in the autocomplete. It would be much easier to read if it was the same size as the page titles from autocomplete. Seems like there is a lot of padding around the url so not sure why this shouldn't be larger.
![Screenshot_20190717-120833](https://user-images.githubusercontent.com/437326/61404596-9e864c00-a88c-11e9-9110-1b5c443f78aa.png)

**Comment by lime124** [comment]
@boek @topotropic can one of you check to see if what mossop is experiencing is to spec? if not, we should fix it. if it is, @topotropic we should revisit the size for accessibility improvements.

**Comment by topotropic** [comment]
I can't reproduce this on my device but the search term should have the same size as the page titles from the result list which isn't the case in the above posted screenshot.

**Comment by lime124** [comment]
as per #5435 it looks like this has been fixed. please reopen if that isn't the case!
