### ISSUE TITLE
Move input box for renaming collection to the top and add save button

### ISSUE THREAD

**Issue by wurstsemmel** [mozilla-mobile/fenix#3831]
### Why/User Benefit/User Problem
When renaming a collection, the input box to edit the name of the collection is displayed directly above the keyboard. I rather expect the input box at the top of the screen followed by a "Save" or "Accept" button. It is not easy to find the input box between the tabs in the collection and the keyboard, where it is close to the location where the typing suggestions appear.
After hiding the keyboard the input box is located at the bottom of the screen, this does not feel right.

### What/Requirements
- Move input box for renaming a collection to the top of the screen.
- Display a save/accept button next to the input box instead relying on the user to hit "OK" on the keyboard.

### Acceptance Criteria (how do I know when I’m done?)
- Input box to rename collection located at the top of the screen.
- Save/accept button displayed next to the input box.

**Comment by mheubusch** [comment]
@topotropic for your consideration

**Comment by lime124** [comment]
removing ux label - we are collecting issues related to collections/homescree to be tackled by ux in a larger effort.

**Comment by topotropic** [comment]
Thanks for the feedback! We will keep the input box as is for now but consider the feedback as part of our ongoing refinements.
