### ISSUE TITLE
[Bug] Invalid/Missing referer header causes Telegram login to fail

### ISSUE THREAD

**Issue by Steffo99** [mozilla-mobile/fenix#3836]
## Steps to reproduce

1. Visit https://core.telegram.org/widgets/login
2. Click the _Login with Telegram_ button
3. Complete all login steps.

### Expected behavior

Login should be successful, clicking the button again should open a "You're already logged in" alert.

(Tested on both Firefox Developer Edition 68.0b12 and Chrome on Android)

### Actual behavior

Login fails with a "Bot domain invalid" alert.

[![Screenshot Description](https://webcompat.com/uploads/2019/6/5273af8d-9ab9-443c-99e7-e0dd9a2647ae-thumb.jpg)](https://webcompat.com/uploads/2019/6/5273af8d-9ab9-443c-99e7-e0dd9a2647ae.jpg)

Telegram checks what domain the request is from by comparing the [referer header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Referer) in the login page request with a domain specified in [the bot configuration](https://t.me/BotFather).

Therefore, I suppose that Fenix breaks the referer header somehow during the login process...

### Device information

* Android device: Xiaomi Mi A1, Android Pie (9)
* Fenix version: 68.0-20190612114833

## Other info

[Same issue opened through WebCompat](https://github.com/webcompat/web-bugs/issues/33327)

**Comment by kbrosnan** [comment]
Dupe #1570

**Comment by Steffo99** [comment]
@kbrosnan It's not a duplicate. No intent urls are involved here...

**Comment by karlcow** [comment]
@kbrosnan This doesn't seem to be a duplicate of the previous issues. it seems also to be happening quite a lot.
https://duckduckgo.com/?q=bot+domain+invalid+telegram&t=ffab&ia=web

**Comment by cendyne** [comment]
This is still an issue, please reopen the ticket and consider it not a duplicate.
