### ISSUE TITLE
Add Hindi Locale

### ISSUE THREAD

**Issue by divya21raj** [mozilla-mobile/fenix#3842]
### Why/User Benefit/User Problem
It would be great to have the app in Hindi, a language used by almost 340 Million people of the world.

### What/Requirements
The app should have a Hindi locale

### Acceptance Criteria (how do I know when I’m done?)
When Hindi is an option to use the app, just like other already available locales.

I can volunteer to provide the Hindi locale translations, just give me a heads up!

**Comment by AaronMT** [comment]
@Delphine can you provide @divya21raj with contribution information?

**Comment by Delphine** [comment]
This project is not open yet to more localizations. Localization will happen on [Pontoon](https://pontoon.mozilla.org/projects/android-l10n/), and I will be sending out a message on the [Dev.l10n mailing list](https://lists.mozilla.org/listinfo/dev-l10n) this week about how to proceed.
In the meantime, you can get in touch with the existing Hindi localization community, by reaching out to [the managers listed here](https://pontoon.mozilla.org/hi-IN/contributors/).
Thanks for wanting to help out with this!
