### ISSUE TITLE
Remove redundant share option from either quick action sheet or BrowserMenu

### ISSUE THREAD

**Issue by pwd-github** [mozilla-mobile/fenix#3844]
### Why/User Benefit/User Problem
There are two shares. As a user, I don't need nor want two buttons to do the same thing in two different places. 

### What/Requirements
Add a pref to remove the one in the overflow menu.

**Comment by sblatz** [comment]
@pwd-github are you able to provide a screenshot of where you're seeing 2 share buttons?

**Comment by pwd-github** [comment]
@sblatz Here's the two share buttons in one screenshot.

![Screenshot_2019-07-25-09-41-38](https://user-images.githubusercontent.com/203217/61859722-93e93980-aec0-11e9-94dd-b824802d87b3.png)

**Comment by pwd-github** [comment]
I'm not sure if my opinion counts for anything, but in light of the new title, I'd personally much prefer to have the option from the BrowserMenu removed.

**Comment by sblatz** [comment]
This is super easy for us to change, just need a UX decision. 

I agree with @pwd-github, share is an action from this page it should just be in quick action sheet!

**Comment by kbrosnan** [comment]
See also #1957 where ux did not want to change this.

**Comment by sblatz** [comment]
@kbrosnan thanks for linking that. 

Odd that we chose to only have bookmarks available in the quick action sheet, but share is duplicated. Seems like either both should be duplicated or not right 🤔

**Comment by lime124** [comment]
i'm going to link this to the QAB effort and the effort around looking at the toolbar menu items/ordering.
