### ISSUE TITLE
[Bug] The snackbar message when deleting browsing data where is no content should be changed

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/fenix#3845]
## Steps to reproduce
1. Install and launch Fenix.
2. Make sure you have **0** **`Tabs, collections or browsing history and site data`.**
3. Check those 3 and tap on **`delete browsing data`.**

### Expected behavior
A messaged informing the user that there is nothing to delete should be displayed like **`There is nothing to delete, all the data is already cleared`.**
### Actual behavior
The **`Browsing data deleted`** message is displayed even if there is nothing to delete.
### Device information
* Android device: **`Samsung Galaxy Note 9(Android 8.1.0).`**
* Fenix version: **`latest build from 7/2 .`**
### Notes
[video](https://drive.google.com/open?id=1U2q0E9ySJSnUJu1nWpLd6c_YD_Iy5g1l)

**Comment by ekager** [comment]
Closing this in favor of https://github.com/mozilla-mobile/fenix/issues/4199 you will no longer be able to delete nothing
