### ISSUE TITLE
[Bug] No space between the search bar and the "Open tabs" section

### ISSUE THREAD

**Issue by softvision-miralobontiu** [mozilla-mobile/fenix#3849]
## Steps to reproduce
1. Open a few tabs (3-4).
2. From Homescreen, scroll down and observe the "Open tabs" section.

### Expected behavior
There should be a space between the search bar and the "Open tabs" section.

### Actual behavior
There is no space between the search bar and the "Open tabs" section.

### Device information
* Android device: Motorola Moto G6 (Android 8)
* Fenix version: 1.0.1926 (#11790618)

### Note
Not reproducible on HTC 10 (Android 8), Nexus 6P (Android 8.1.0), Google Pixel (Android Q), HTC Desire 820 (Android 6.0.1).

![Screenshot_1](https://user-images.githubusercontent.com/40694158/60521940-cb652b80-9cf0-11e9-9e9b-c4d928a4a1e2.png)

**Comment by sblatz** [comment]
@softvision-miralobontiu are you still seeing this on the latest nightly?

**Comment by sblatz** [comment]
p3/s3 since it seems to only affect a small number of devices

**Comment by softvision-miralobontiu** [comment]
@sblatz it is not reproducible on the latest Nightly build 190722 (#12030621) with Motorola Moto G6 (Android 8).
I will close this.
