### ISSUE TITLE
Consider reordering toolbar items

### ISSUE THREAD

**Issue by cronosun** [mozilla-mobile/fenix#3850]
### Why/User Benefit/User Problem

Over the last few years phones got bigger and bigger. It's hard to reach items in the top of the screen and on the right side of the screen. I appreciate placing the toolbar to the bottom, that's nice. I think you should also reorder the items in the toolbar a bit: things we don't use often should be moved to the right, things we use often should be moved to the left. The toolbar consists of those items:

 * Security Information
 * The URL
 * The tabs buttons.
 * The menu button ("...").

See also:
[https://www.lukew.com/ff/entry.asp?1927](url)
![large_smartphones1](https://user-images.githubusercontent.com/13786782/60522925-23e4fa80-9cea-11e9-9587-3faba6f1d1bc.png)

Security information and the right half of the URL usually do not need to be touched, so they should be moved to the right. Note: **right half of the URL**: why? To change the URL it's enough to touch the left half of the URL.

### Currently (2019-07-02) looks like this

![easy_to_reach_area](https://user-images.githubusercontent.com/13786782/60521738-0f076780-9ce8-11e9-8028-1818422aedc2.png)

![importance](https://user-images.githubusercontent.com/13786782/60521788-25adbe80-9ce8-11e9-89d7-4cb6f6c00e25.png)

### After reordering would look about like this

![reordered_controls](https://user-images.githubusercontent.com/13786782/60521831-32caad80-9ce8-11e9-98a5-8da87952ec14.png)

### Considerations

 * I don't know about people holding their phone in the right hand... maybe add an option to inverse ordering?

**Comment by cadeyrn** [comment]
I vote **against** your proposal. And the funny part is: Your image with the arrows and the "important things" / "less important things" shows why it shouldn't be changed in my opinion. 😉

The current implementation allows me to open the menu, reload the website and switch to the start screen with only one hand. With your proposal I would need two hands. And all of these features are more important for me than reaching the padlock icon.

**Comment by rubcap** [comment]
@cronosun, I assume you are left-handed, because as a right-hand person, your proposal is the opposite of what I find convenient. 

Maybe you should change the title to "Inverse toolbar ordering for left-handed"?

**Comment by mheubusch** [comment]
@apbitner please consider as you explore navigation bar.

**Comment by cronosun** [comment]
@rubcap  : My right hand is the dominant hand (the "writing" hand; the "mouse" hand); But I hold my phone in the left hand (like 57% according to the linked study) and use the thumb to navigate / touch (the phone is too wide to reach to outer right edge - to reach the outer right edge I need the second hand - the right one). 

Study: [https://tristandenyer.com/work/user-research-people-hold-interact-phone/](url)

![mobile-survey-graphics-hold-phone](https://user-images.githubusercontent.com/13786782/60544193-8c4ad080-9d18-11e9-8fe8-90e6318b4b34.gif)

**Comment by cadeyrn** [comment]
To be honest I don't believe that these numbers are representative. It's based on a survey (why there is no number of asked people?) and it doesn't match my experience at all. It's known that there are much more right-handed people in the world and I've never seen someone right-handing holding the phone in the left. While it's possible and I am sure that these people exist I can't believe the "57 percent". I can be wrong but I wouldn't change anything based on a survey that hides the number of participants.

Also the graphic with the "hard to reach" and "comfortable to reach" is not really true. As I already said, the buttons on the bottom right are very ease to reach for me (the graphic says only "okay") and the bottom left is not to reach at all for me (and the graphic says "easy" (!) to reach…

**Comment by cronosun** [comment]
@cadeyrn 

> I am still against a change of the default. 

I agree. The proposed reordering should be optional: for example on a smaller phone like the 5.8" Xiaomi MI A2 Lite the current toolbar layout is more convenient.

> I don't know other browsers with such a feature. So it would also be some kind of USP.

I tried several other browsers like Chrome, Opera, Samsung Internet, Edge and the Xiaomi Browser: All those browser AFAIK have about the same toolbar layout as the current version of Fenix. But: They can't be compared to Fenix, because I can't operate them with one hand anyway, because all these browsers have the toolbar (or at least the URL input) at the top. Even the URL input at the bottom is a great USP for Fenix.

**Comment by lime124** [comment]
removing @apbitner - he's focusing on related nav bar and QAB at the moment. removing UX label, i'm collecting these issues for ux to tackle at the same time.

**Comment by apbitner** [comment]
While the toolbar menu (3-dot menu) might be slightly easier to reach for right-handed users, once the menu is open those items would become more of a reach, so it makes sense to keep the menu on the right where it is.
