### ISSUE TITLE
[Bug] Frequent ANRs "Input dispatching timed out"

### ISSUE THREAD

**Issue by colintheshots** [mozilla-mobile/fenix#3851]
## Steps to reproduce
No known steps to reproduce yet. This may happen on page loads sometimes.

### Expected behavior
App handles page loads without Application Not Responding errors.

### Actual behavior
Sometimes page loads will result in Application Not Responding errors with various, but similar stack traces including "Input Dispatching timed out."

Here's a sample trace:
```
Input dispatching timed out (Waiting to send non-key event because the touched window has not finished processing certain input events that were delivered to it over 500.0ms ago. waitqueue length = 8, head.seq = 599618, Wait queue head age: 6602.4ms.)
```

### Device information

* Android device: Nokia 7 Plus
* Fenix version: 1.0.0

**Comment by colintheshots** [comment]
I believe this ANR is also fixed by PR#3854. The stack trace is different, but it has the same root cause.

**Comment by sv-ohorvath** [comment]
Checked this on a Nexus 9 tablet (Android 7.1.1) after #2945.
I got the ANR error on this webpage, after ~2hrs of browsing: https://edition.cnn.com/2019/05/08/asia/uyghur-xinjiang-china-kashgar-intl/index.html
[logcat](https://github.com/mozilla-mobile/fenix/files/3355289/ANR.txt)

build: Nightly 190703 (#11840608)

**Comment by ekager** [comment]
What do we think of this bug? Should we close it and reopen if we see similar bugs in the future?
