### ISSUE TITLE
Firefox Preview: confusing ways to create new bookmarks

### ISSUE THREAD

**Issue by edwintorok** [mozilla-mobile/fenix#3853]
## Steps to reproduce

Open a site, try to add a bookmark for it such that it shows up in your library and on other synchronized devices (e.g. your desktop).
This is a crucial part of my day-to-day usage (bookmarking interesting/important pages to be read later that works the same accross all devices, i.e. bookmarks)

### Expected behavior

I have something to click/tap/swipe that adds the currently open page as a bookmark.
I have a way to add bookmarks from other applications without loading the webpage, (share with firefox -> add bookmark on the non-preview version of Firefox). E.g. from 'materialistic' application (a HN reader) I can share the article link with firefox to read later.

### Actual behavior

There is no button/action to create a bookmark in the hamburger menu, but there is 'save to collection'.
My desktop browser doesn't know about collections, what are they?
It seems to be equivalent to a bookmark on the device itself, but it doesn't seem to be synchronized to my desktop browser, so in reality it is not.

Or maybe the functionality is there but so well hidden that I can't find it. I read the help page on the quick action bar, and find that there is a bookmark button there. Why hide it? 
I would expect that all actions for a page are part of the hamburger menu, "share" is there both in the quick action bar, and the hamburger menu, bookmark is not.

Solution: **Please add bookmark to the hamburger menu.**

There is also no 'add bookmark/save to collection' action when sharing something with 'Firefox Preview', instead I get the page open immediately. No doubt this can be useful too, perhaps **add a separate 'intent' in Android for adding a bookmark like the current version of Firefox does**.

### Device information

* Android device: Nokia 7 plus, Android 9
* Fenix version: Firefox Preview 1.0.0

**Comment by sblatz** [comment]
A great thing for @mozilla-mobile/ux to keep in mind 😄

**Comment by lime124** [comment]
we are in the process of collecting bookmark related issues for consideration in one design effort - removing ux label

**Comment by vesta0** [comment]
@topotropic please close this issue once you have reviewed and considered.

**Comment by lime124** [comment]
closing this as the QAB is going to be removed - see #5588 and #4281. thanks!
