### ISSUE TITLE
[Bug] missing a way to exit a private browsing session

### ISSUE THREAD

**Issue by edwintorok** [mozilla-mobile/fenix#3855]
## Steps to reproduce

Open 'Firefox Preview' and tap the private browsing mask icon at the top.
Get a message that says "Firefox Preview clears your search and browsing history when you close your private session"

### Expected behavior

Have a button to close the private session, like Firefox Focus did.
Albeit it was sometimes in inconvenient positions and I tapped on it by accident when I actually wanted to click something on the webpage, so I could understand why you removed it, but there also used to be an Android notification that I could use to close Firefox Focus.

### Actual behavior

No button to exit the application. What does 'close private session' refer to above? 
Is it considered exited when I swipe up form home and close all recent applications?
Do I have to force stop the application to close it?

Please add back at least the notification that has a button to close firefox, or provide something in the hamburger menu to close it.

### Device information

* Android device: Nokia 7+, Android 9
* Fenix version: Firefox Preview 1.0.0

**Comment by sblatz** [comment]
@edwintorok to clarify: you can press the private browsing button again to move to normal browsing. You can also tap the three dot menu and press "close all tabs".

We used to have a "delete session" button that would close all tabs too, but removed it. Are you wanting something like this?

**Comment by edwintorok** [comment]
Thanks for the suggestion about 'close all tabs' that worked (click on the [[1]] number of tabs, then hamburger menu and then close tabs). 

Up to you whether you could make that easier to reach, but please document how to do this in the message that gets displayed when you enter private browsing mode.
Having a 'delete session'/close session button would work for me.

Entering normal browsing mode didn't clear my private tabs, reentering private mode still had all of them available. Not sure what would be the best option here, but perhaps you could pop up something to ask the user whether they want to close the private session when switching back to normal mode or keep it (and remember the choice)

**Comment by SeriousHoax** [comment]
Hopefully this will solve another issue too. After using private mode and closing tabs if the app is closed by tapping back button then the next time it's open, it still remains in private window. Even if it's closed from the recent app menu the result is still the same. 
The expected behavior should be to open normal browsing window similar to the current Firefox.

**Comment by kbrosnan** [comment]
Private browsing persisting state is intentional currently.

**Comment by vesta0** [comment]
Will be addressed in #2560
