### ISSUE TITLE
Update to A-C 0.56.6

### ISSUE THREAD

**Issue by st3fan** [mozilla-mobile/fenix#3858]
Update to A-C 0.56.6 - This is the release what will contain the fixes for the token caching.

 * https://github.com/mozilla-mobile/android-components/pull/3579

This release does not exist yet.

**Comment by pocmo** [comment]
@st3fan As per https://github.com/mozilla-mobile/android-components/pull/3631 and https://github.com/mozilla-mobile/android-components/issues/3630 I assume we want to include AS 0.31.1 into 0.56.6 too, right? :)

**Comment by pocmo** [comment]
Preparing the release on AC side here:
https://github.com/mozilla-mobile/android-components/issues/3632
