### ISSUE TITLE
Add Ecosia as search provider

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/fenix#3859]
### Why/User Benefit/User Problem
As a user I'd like to set Ecosia as my default search engine, so I can have more choice.

### What/Requirements
Ecosia is available as a search provider on Desktop.

### Acceptance Criteria (how do I know when I’m done?)
I can set Ecosia as my default search provider on Fenix.

**Comment by kbrosnan** [comment]
All languages? The other path forward is #1437

**Comment by vesta0** [comment]
Sounds good! Will address this in #1437
