### ISSUE TITLE
Add empty state text for Description of Collections

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/fenix#3860]
### Why/User Benefit/User Problem
As a new user who isn't familiar with Collections, I want to have some explanation of what they are on the homescreen or during onboarding, so I can feel more inclined to try them out.

### What/Requirements
Strings + UX placement

### Acceptance Criteria (how do I know when I’m done?)
I can easily understand what Collections are without having to navigate to the help page.

**Comment by mheubusch** [comment]
@topotropic for your consideration as you look at collections.

**Comment by lime124** [comment]
removing the ux label - this is on our radar already as it's part of Q3 plans.

**Comment by liuche** [comment]
During discussion: open question, if this is being put on hold, what kinds of small pieces can be done immediately based on this research?
Also understanding what effort of work is involved for suggested work, and assuming that work won't be removed (unless it's really cheap/quick).

**Comment by topotropic** [comment]
The current placeholder text for no collections is "Your collections will be shown here."  As a very simple improvement, we could update it with something more descriptive, for example "Save open tabs to a Collection to keep track of things that are important to you" @mheubusch please help :-)

**Comment by mheubusch** [comment]
Collect the things that matter to you. To start, save open tabs to a new collection. 

@lime124 LMK if that works for you and then remove the needs strings label? thanks

**Comment by lime124** [comment]
works for me - thanks michelle!

**Comment by lime124** [comment]
before adding the eng label - @topotropic is there anything further that needs to be done for the ticket before handing off to eng? thanks!

**Comment by liuche** [comment]
Talking about this in the Fenix Leads meeting:
Let's get some dates on this, so we can plan better.
@topotropic could you add some dates here, for the timebox of deciding what the scope of next steps will be, and filing the next step UX/eng bugs?

**Comment by AndiAJ** [comment]
Hi @boek , I've just check the change on the latest **Nightly Build #12240720 from 12/8**, and it seems that the new empty state string "Collect the things that matter to you. To start, save open tabs to a new collection" **doesn't appear**.

![Screenshot_20190812-122901](https://user-images.githubusercontent.com/51314259/62856426-91c70d80-bcfd-11e9-8c51-93da51066765.png)

**Comment by ekager** [comment]
We added the new string but forgot to use it. I've opened #4739 to address this and we can pull it into this release
