### ISSUE TITLE
share menu improvements

### ISSUE THREAD

**Issue by nahuhh** [mozilla-mobile/fenix#3861]
### Why/User Benefit/User Problem
The share menu looks nice and (on my device) is faster to load than the built in share menu. 
My main issue with the menu is the 2 row, horizontal view.
Seems that the items in there are sorted randomly and hard to find.  

### What/Requirements
Either
A) 
- keep the 2 row layout
- add a search bar to the card
- launch "share" with the keyboard open and the search bar in focus (option)

B) 
- change from a 2 row horizontal scroll card to an expandable/expanded vertical scroll card
- add a search bar to the card  
- launch "share" with the keyboard open and the search bar in focus (option)

Or
C) an option to choose between A and B

Also, browser settings for:
- choose the sort order (frequently used, recently used, alphabetical)
- clear frequently used/recently used (under delete browsing data)
- choose whether or not to launch share with the keyboard open/search field in focus 
- option to disable the search bar altogether

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-12440)

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1809793

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
