### ISSUE TITLE
[Bug] No awesomebar completion after updating

### ISSUE THREAD

**Issue by mikeGolf08** [mozilla-mobile/fenix#3863]
## Steps to reproduce

1. Update Fenix
2. Open Fenix and **select omnibox**
3. **Write the first letters of one of your bookmarks**

### Expected behavior

**Fenix shows a completion** based on my typed chars and bookmarks:
iex. Typing "**git**" for GitHub and the **auto completion suggests "github.com"**

### Actual behavior

Fenix isn't showing a completion **unless I clear app and cached data.**

### Device information

* Android device: Android 9 on OnePlus 3T (A3003) Oxygen OS 9.0.3
* Fenix version: Nightly 190702 18:56 (Build #11831860)
📦: 2.0.0
🦎: 68.0-20190612114833

**Comment by ekager** [comment]
@mikeGolf08 by omnibox do you mean awesomebar? Did you have suggestions disabled in Settings -> Search?

**Comment by mikeGolf08** [comment]
@ekager Yes sorry FF = awesomebar - Will keep it in my mind now. No I haven't -> After the last update I decided to clear all known app data via settings and did the set-up process again. The result is that now I get the suggestions for the websites that didn't work before and for those which worked I am left with no suggestions again.

I don't have the time to contribute to code at the time but I'll try my best to offer you the necessary information - just tell me which you need!

**Comment by boek** [comment]
@mikeGolf08 can you reproduce this issue? Could you post a screenshot of your search settings?

**Comment by mikeGolf08** [comment]
@boek Yes I can reproduce it every time but didn't try another refresh since...

**Comment by mikeGolf08** [comment]
![Screenshot_20190806-201019__01](https://user-images.githubusercontent.com/52482050/62570255-c49d7b80-b88f-11e9-9efa-8ea2907589a4.jpg)
![Screenshot_20190806-201032__01](https://user-images.githubusercontent.com/52482050/62570256-c49d7b80-b88f-11e9-83e6-e4639bc2f2c8.jpg)
Only things I changed at the time

**Comment by mikeGolf08** [comment]
**I think it has something to do with the deletion of browsing data**. I had reinstalled Fenix and it was working like it is supposed to work but after I deleted the browsing data (3150 entries of "Browsing history and site data") it has been broken again... Since then no auto completion for any of my bookmarks

**Comment by mikeGolf08** [comment]
The issue still persists but just for a few bookmark I do not get auto completion whereas for the same I get it on the normal Firefox Mobile Browser.

Nightly 190906 18:03 (Build #12491815)
package: 12.0.0, 65df8e8a0
lizard: 71.0a1-20190905094317

**Comment by mikeGolf08** [comment]
Does not happen at the latest builds so I closed it.

**Comment by softvision-miralobontiu** [comment]
I was not able to reproduce this issue on the latest build of Nightly from 03/11 with Xiaomi Redmi Note 8T (Android 9).
Removing the needs:STR label.
