### ISSUE TITLE
 Add functionality to delete multiple "Collections" 

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/fenix#3867]
### Why/User Benefit/User Problem
As a user I want to be able to select more collections and delete them with 1 tap.
### What/Requirements
Adding functionality for `Collections` to be selected after long tap on a collection and then to be selected and eventually deleted.
### Acceptance Criteria (how do I know when I’m done?)
When more  `Collection`  can be selected and deleted at the same time.

**Comment by vesta0** [comment]
Closing this for now since it's an edge case. Will revisit when iterating on Collections.
