### ISSUE TITLE
[Bug] The Share/Bookmark drawer near the url bar hinder scrolling

### ISSUE THREAD

**Issue by robmv** [mozilla-mobile/fenix#3876]
## Steps to reproduce

1. Take the phone with only one hand, position the hand so you can scroll and use the Android navigations buttons easily.
2. Scroll a long page up and down frequently. The Share/Bookmark is to easy to open and close when this scrolling action is being done.

### Expected behavior

Page scrolling should not be interrupted by the drawer opening and closing.

### Actual behavior

It is too easy to open the drawer instead of performing the scroll. In order to avoid opening the drawer, I have to take the phone upper that normally do on other browsers, not allowing me to reach the Android navigations buttons easily with only one hand

### Additional Notes

The URL on the bottom may be the reason the drawer is hindering the scrolling action. I have not read about the advantages of the bottom URL bar for Fenix but let me add few disadvantages I have experienced to #2115.

### Device information

* Android device: Nexus 5
* Fenix version: 1.0.0

**Comment by sblatz** [comment]
Thanks for your feedback @robmv! This would be great for @mozilla-mobile/ux to take into consideration 😄

**Comment by lime124** [comment]
adding to the QAB ticket for consideration - removing ux label

**Comment by ekager** [comment]
This has been removed
