### ISSUE TITLE
[Bug] Logged out of Sync (second time)

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/fenix#3877]
## Steps to reproduce

No idea how to reproduce.

I have been running Fenix nightlies for months now, and logged into sync pretty much as soon as it was available. I was logged out of sync a few weeks ago and logged back in (using username and password, not QR code). 

Today, I noticed that I was once again logged out. 

### Expected behavior

Sync should not log out.

### Actual behavior

Sync is logged out, no notification.

Hoping I can provide some information to help diagnose why I am being logged out so it doesn't remain a persistent issue. 

### Device information

* Android device: Pixel 2
* Fenix version: latest from play store

**Comment by vladikoff** [comment]
@yoasif have you been switching WiFi / network connectivity in any way?

**Comment by rfk** [comment]
@grigoryk I wonder if this is hitting a network error when to refresh the sync token, and triggering https://github.com/mozilla-mobile/android-components/issues/3347

**Comment by krzyk** [comment]
I have similar bug, but I'm logged out of sync AFAIK after each Fenix update (so basically every second day, or sometimes daily) - this is really annoying.
And also Fenix appears multiple times in my devices, so when I want to send a tab to my mobile I don't know which "Fenix" is the right one - is it possible that each release has a different ID in devices list? (I didn't change the name there).

**Comment by yoasif** [comment]
I don't turn WiFi off or switch networks that often, but I do move away from my primary WiFi network and fall back to LTE data.

**Comment by djc** [comment]
I also keep being logged out of Sync on my phone. Based on my experience, I think the logout being triggered by updates feels more fitting than based on network conditions.

**Comment by krzyk** [comment]
And again, after update (actually I had two updates, one after another, I didn't check after the first one) I'm again logged out of sync so the reason is obvious - updated of the app.

**Comment by jcursiolf** [comment]
Every update logs me out. Also now it does  not even show my other Firefoxes to share. I have to use either KDE Connect on Linux or the My Phone app to my Widnows machine....

**Comment by rfk** [comment]
@ckarlof mentioned that this happened to him as well, being silently disconnected from his account; not clear if it was due to an update but based on feedback in this bug, it seems likely.

**Comment by yoasif** [comment]
I will say that I did not experience a logout every time I updated -- given that I was updating once a day (and sometimes more often) for a while, I would have noticed that a long time ago.

**Comment by ckarlof** [comment]
For me, it just happened once, and it was over the duration of the 1.0 release.

**Comment by jcursiolf** [comment]
So, happened once again. This time I just went to an area of my apartment where WiFi is poor, changed to LTE and saw that it was disconnected. Considering the time it happened and the time of the latest build, it might have been also just after the update, as happened lots if times now (I stopped counting). Uninstalling and reinstalling does not fix it. 

### Device information

* _Android device_: OnePlus 5 (model A500, Android version 9, OxygenOs version 9.0.6, no root, no ROM)
* _Fenix version_: Nightly 190709 18:02 Build # 11901819 (Note: this is the actual version, but it has been happening for at least 10 days)


![Screenshot_20190709-094021](https://user-images.githubusercontent.com/41722528/60957222-94040980-a304-11e9-9187-3247624596e3.jpg)
![Screenshot_20190709-094044](https://user-images.githubusercontent.com/41722528/60957223-94040980-a304-11e9-957f-248439d3cd94.jpg)

**Comment by grigoryk** [comment]
> @grigoryk I wonder if this is hitting a network error when to refresh the sync token, and triggering [mozilla-mobile/android-components#3347](https://github.com/mozilla-mobile/android-components/issues/3347)

This sounds like the most likely cause here! Let's tackle this first, and see if the problem goes away.

**Comment by ekager** [comment]
@yoasif have you seen this again? Do we think this has been resolved?

**Comment by yoasif** [comment]
I haven't seen this since I reported it. It may have been resolved.

**Comment by djc** [comment]
Yeah, this has been working for a while now.

**Comment by ekager** [comment]
Good to hear! Going to close it then :)
