### ISSUE TITLE
Add linting rule for adding a license

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#3880]
We should have a linting rule that triggers if a new file does not include the Mozilla license.

**Comment by Amejia481** [comment]
Similar issue on AC -> https://github.com/mozilla-mobile/android-components/issues/846

**Comment by sblatz** [comment]
While I'd love to have this, it's not the top of our priorities. Would love a contributor PR on this!

**Comment by dector** [comment]
Is header format defined in mozilla-mobile/android-components#4460 works in this project as well?

**Comment by NotWoods** [comment]
Yes, the same header format works here too 😄

**Comment by dector** [comment]
@NotWoods Cool. I'll make PR today.

**Comment by dector** [comment]
Should we publish `tooling-detekt` from AC or just copy-past license plugin? :smile:

**Comment by pocmo** [comment]
@dector Yes, can you try publishing and consuming it from `mavenLocal()`?

**Comment by dector** [comment]
@pocmo Sorry for late reply. Was bit busy.

If I got your proposal right - the idea is to publish module from AC project to local maven repository and reuse it in Fenix project? Isn't it adding explicit dependency on AC?

**Comment by pocmo** [comment]
@dector Oh, I meant only for testing if everything works. After that we'd actually publish it from AC to maven.mozilla.org

**Comment by dector** [comment]
@pocmo Ah, sure! Using rulesets from a maven repository works similarly to using rulesets from a separate module.

**Comment by pocmo** [comment]
> @pocmo Ah, sure! Using rulesets from a maven repository works similarly to using rulesets from a separate module.

Yeah, it should. But I am not sure whether our build/publish mechanism will work as expected. That's why I would love to try that with a local repository before enabling it in buildconfig.yml. If that works then yes, let's set it to publish: true and then test again with the snapshots. :)

**Comment by dector** [comment]
@pocmo Awesome! I tested `./gradlew :tooling-detekt:publishToMavenLocal` with `maven-publish` plugin.

I guess main publishing mechanism is implemented in `automation/taskcluster/decision_task.py`. If it's needed I can try to dig into it and try to publish components to local maven repository first. But I don't expect any troubles with it as other components are published to mozilla maven without any issue.

**Comment by eliserichards** [comment]
Closing in favor of https://github.com/mozilla-mobile/android-components/issues/6351
