### ISSUE TITLE
[Bug] Scan QR not working on some tablets 

### ISSUE THREAD

**Issue by softvision-miralobontiu** [mozilla-mobile/fenix#3889]
## Steps to reproduce
1. Sign in on Firefox on Desktop.
2. On Desktop go to firefox.com/pair.
3. On tablet, go to Settings - Turn on Sync - Scan pairing code in desktop Firefox.
4. Allow camera and try to scan the QR code displayed on Desktop.

### Expected behavior
The QR should be read instantly.

### Actual behavior
The QR code is not read, no matter how close or far the tablet is approached.

### Device information
* Android device: Huawei Media Pad M2 (Android 5.1.1), Samsung Galaxy Tab A6 (Android 5.1.1), Nexus 9 (Android 7.1.1), 
* Fenix version:  the latest Nightly build 190704 #11850611

### Notes
 - not reproducible on Sony Xperia Z2 (Android 6.0.1), and Samsung Galaxy Tab S3 (Android 8),
- reproducible also scanning from the Scan button displayed after tapping on the search bar.

I've attached a logcat, don't know if it helps.
[logcat.txt](https://github.com/mozilla-mobile/fenix/files/3358579/logcat.txt)

**Comment by vladikoff** [comment]
> Nexus 9 (Android 7.1.1)

I'll try the nexus 9 later this week

**Comment by vladikoff** [comment]
@csadilek ok i can confirm it doesn't scan on the Nexus 9 , maybe we can debug tomorrow and see what is going on..

**Comment by vladikoff** [comment]
Related: https://github.com/expo/expo/issues/1481

**Comment by csadilek** [comment]
This is fixed in A-C 5.0.0. We'll need to upgrade Fenix before this can be verified next week.

**Comment by csadilek** [comment]
@softvision-miralobontiu fixes landed in the latest Fenix Nightly. Could you verify this again?

**Comment by softvision-miralobontiu** [comment]
Verified as fixed on the latest Nightly build 190722 (#12031851) with Huawei Media Pad M2 (Android 5.1.1), Samsung Galaxy Tab A6 (Android 5.1.1), Nexus 9 (Android 7.1.1).
