### ISSUE TITLE
[Bug] Tapping Settings -> Help opens Google search (only affects nightly)

### ISSUE THREAD

**Issue by klausenbusk** [mozilla-mobile/fenix#3892]
## Steps to reproduce
Tap `Settings -> Help`

### Expected behavior
A help page opens

### Actual behavior
A Google search for `https://support.mozilla.org/1/mobile/Nightly 190704 06:06/Android/da-DK/faq-android` is opened.

### Device information

* Android device: Samsung S4 Mini (serranoltexx) - Android Pie
* Fenix version: Nightly ([190704 06:06](https://queue.taskcluster.net/v1/task/F5caWFM-S4qGj7W9Awc13A/runs/0/artifacts/public/target.arm.apk))

**Comment by neekless** [comment]
Reproduced on Nightly 190704 18:04 (Build #11851810), Pixel 2XL Pie

Opens a search page (in my case duckduckgo) for `https://support.mozilla.org/1/mobile/Nightly 190704 18:04/Android/en-US/faq-android`

The version name is affecting the url.

**Comment by mheubusch** [comment]
This also happens from the Help link on the home screen 3-dot menu, but not from the 3-dot menu in a tab

**Comment by sblatz** [comment]
This seems like a pretty bad experience. Let's pull this into a sprint ASAP.

**Comment by ekager** [comment]
IIUC this only happens in Nightly builds so still should be fixed but less of a big deal than P1

**Comment by softvision-miralobontiu** [comment]
Verified as fixed on the latest Nightly 190830 (#12420612) with Nokia 6 (Android 7.1.1), and Samsung Galaxy S8 (Android 9).
