### ISSUE TITLE
Rename apks on taskcluster to remove extra "."

### ISSUE THREAD

**Issue by mitchhentges** [mozilla-mobile/fenix#3893]
Due to:

> The default file manager is not understanding the file extension "target.aarch64.apk"

from [this bug](https://github.com/mozilla-mobile/fenix/issues/2109#issuecomment-508528688), we should change the output apk name format to avoid the "double-extension"

**Comment by sarentz** [comment]
@sarentz note to self to fix the nimbledroid scripts to pick up this name change

**Comment by andreicristianpetcu** [comment]
This did not fix my issue. I still need to open the APK from a filemanager. Glad I found this workaround :D

**Comment by mitchhentges** [comment]
@andreicristianpetcu which APK did you download? Which index did you download from?
I'd recommend using [`project.mobile.fenix.v2.nightly`](https://tools.taskcluster.net/index/project.mobile.fenix.v2.nightly/latest)

**Comment by andreicristianpetcu** [comment]
Yup. This is what I use.... https://tools.taskcluster.net/index/project.mobile.fenix.v2.nightly/latest
