### ISSUE TITLE
[Bug] Empty space on Netflix.com after closing the cookies banner

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#3897]
## Steps to reproduce
1. Navigate to netflix.com
2. View the Cookies banner
3. Tap the x button from the banner

### Expected behavior
The banner should be semi-transparent.
No empty space should be left after dismissing the banner.

### Actual behavior
The banner isn't semi-transparent.
Empty space left after dismissing the banner.

### Device information

* Android device: 
• Google Pixel 3XL (Android 9)
• Google Pixel 3 (Android 9)
• Pixel Xl (Android Q Beta 4)

* Fenix version: 1.0.1-rc.1 Build # 11851847 4/7

### Notes

[Fenix banner picture on Google Pixel3XL](https://drive.google.com/file/d/1gRvkO9sFjMsUedqW5ErRTVLn8lE5VqFB/view?usp=sharing)

[Chrome banner picture on Google Pixel3XL](https://drive.google.com/file/d/1j7Kp8U-9POaogxHw33CyJ9lN4ucd3oEa/view?usp=sharing)

[Fenix empty space after dismiss on Google Pixel3XL](https://drive.google.com/file/d/1qMT-CYF8fAKeiY86l5uamgGU0vRSN0Oc/view?usp=sharing)

**Comment by ekager** [comment]
I don't see a cookie banner in the US but if you can also try Reference Browser/Fennec we can know if it's a GV/Gecko bug that we should file in Bugzilla?

**Comment by boek** [comment]
@AndiAJ is this still an issue?

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly Build 200519 from 5/19`** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)

► Video
![20200519-092613](https://user-images.githubusercontent.com/51314259/82292488-af738280-99b3-11ea-9499-d3eb72ae4efb.gif)
