### ISSUE TITLE
[Bug] Taobao.com isn't displayed properly in landscape mode

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#3898]
## Steps to reproduce
1. Visit taobao.com
2. Rotate device to landscape view

### Expected behavior
The page is properly displayed, no UI defects.

### Actual behavior
The  page isn't properly displayed, everything seems to be cornered to the left

### Device information

* Android device: 
• Google Pixel 3XL (Android 9)
• Google Pixel 3 (Android 9)
• Pixel Xl (Android Q Beta 4)
• Samsung Galaxy S9 (Android 8)
• Nexus 9 (Android 7.1.1)

* Fenix version: 1.0.1-rc.1 Build # 11851847 4/7

### Notes
<details>
    <summary>Picture from Google Pixel 3XL</summary>

![Screenshot_20190705-115029](https://user-images.githubusercontent.com/51314259/60715535-e2d92a00-9f25-11e9-8281-dd6b409cce3a.png)

</details>

**Comment by TitanNano** [comment]
Same behavior in Fennec. It appears to be a webcompat issue. Layout is updated correctly when reloading the page. Chrome does not require a refresh to properly display the page. Might be a site issue.

**Comment by ekager** [comment]
Filed: https://bugzilla.mozilla.org/show_bug.cgi?id=1570566

**Comment by ekager** [comment]
The filed GV bug seems to have been fixed so let's test and close if resolved :)

**Comment by AndiAJ** [comment]
Hi, verified as fixed on Nightly Build #12621819 from 19/9 using the following devices:
• Google Pixel 3a (Android 9)
• Samsung Galaxy Note 9 (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

►Video
![20190920_150735](https://user-images.githubusercontent.com/51314259/65326219-a24e8b80-dbb9-11e9-8b08-0ea9a5e753ce.gif)
