### ISSUE TITLE
PWA installation via Ambient Badging - with UI proposal

### ISSUE THREAD

**Issue by benfrancis** [mozilla-mobile/fenix#3899]
### User Story
As a user I want to be made aware that the web page I'm currently using is part of a web app I can install and have an easy way to install it

I would like to:
* Have an unobtrusive and intuitive way to indicate that the current page is part of a web app I can install
* Have an easy way to install any web app (any website with a web app manifest) at any time without having to meet some arbitrary criteria
* Be educated about the feature at the point I might actually want to use it (e.g. when viewing app-like content that I use often), without frequently interrupting my workflow
* Feel that web apps are first class citizens on my my mobile device (i.e. appear like any other installed app, no clunky "add to home screen" terminology or special composite icons)

### UI Mockup
![fenix-pwa](https://user-images.githubusercontent.com/552417/60719475-b6baaa80-9f1f-11e9-9697-eab691fbcabc.png)

### Proposed User Experience (text from the UI mockup)
1. If a web app manifest is detected on the current page, an app icon is displayed in the URL bar as an "ambient badge" to indicate that this page is part of a web app which can be installed.
2. Clicking on the app icon displays the Control Center which includes a "web app" section with the web app's name and icon from its manifest and a button to install it.
3. If certain "installability criteria" are met (e.g. offline service worker + high frecency score), then the user is actively prompted to consider installing the web app. This helps educate the user that the app icon in the URL bar can be used to install a web app, but should not appear too frequently.
4. Once installed, an app icon appears on the home screen, and ideally should be indistinguishable from a native app (i.e. appears in the app tray, is not a special composite icon incorporating the Firefox icon, windows appear in the task manager like any other app).
5. Installed web apps which request standalone display mode in their manifest should open in their own app window, without a URL bar, but use the same Gecko runtime and profile as Firefox. Standalone display mode should respect the application scope defined in the manifest so that any URLs outside that scope open outside the web app's window (in the browser or another web app), and browser navigations to URLs inside that scope open in the web app's standalone window.

**Comment by Dunexus** [comment]
To show up Web Apps in the app launcher, Chrome generates WebAPKs.

> **I am a developer of another browser on Android, can I have this seamless install process?**
    We are working on it. We are committed to making this available to all browsers on Android and we will have more details soon. 

Source : https://developers.google.com/web/fundamentals/integration/webapks (Last updated June 20, 2019)

**Comment by vesta0** [comment]
Will be addressed in #768
