### ISSUE TITLE
As a user, I'd like to have Fenix available as an Assistant

### ISSUE THREAD

**Issue by colintheshots** [mozilla-mobile/fenix#390]
### Why/User Benefit/User Problem
The assistant button on most phones is the fastest way to access an app. Fennec and Focus support replacing the Google Assistant if the user wishes to.

### What / Requirements
It takes a trivial change to the Android manifest.

### Acceptance Criteria (how do I know when I’m done?)
The user can select Fenix as assistant and then Fenix appears when hitting the assistant button.

**Comment by buttercookie42** [comment]
> It takes a trivial change to the Android manifest.

https://dxr.mozilla.org/mozilla-central/rev/c2593a3058afdfeaac5c990e18794ee8257afe99/mobile/android/base/AndroidManifest.xml.in#140-154

> The user can select Fenix as assistant and then Fenix appears when hitting the assistant button.

Fennec also opens a new tab and puts the input focus on the URL bar, in case this might be worth considering here as well.

**Comment by colintheshots** [comment]
Oh, I know it's pretty trivial. I need issues to track the work, even if it's a one-line change. We have higher priority items, so I want to put this in the backlog for when anyone has time.

**Comment by sv-ohorvath** [comment]
Verified it works on Samsung Galaxy Note 8 (Android 8.0), Pixel (Android 9)

**Comment by buttercookie42** [comment]
Does that mean no special action in response to that Intent?
