### ISSUE TITLE
[Bug] After sharing a page from Fenix to Firefox Nightly the popup menu remains in the recent apps menu 

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#3900]
## Steps to reproduce
1. Open a page in Fenix
2. Tap the 3 dot menu button
3. Tap Share
4. Select "Add to Nightly" 
5. Select "Open in Nightly" from the popup menu

### Expected behavior
After opening the shared page in Nightly, the pop-up should disappear.

### Actual behavior
After opening the shared page in Nightly, the pop-up doesn't disappear, it remains in the recent apps menu

### Device information

* Android device: 
• Google Pixel 3XL (Android 9)
• Pixel Xl (Android Q Beta 4)
• Samsung Galaxy S9 (Android 8)
• Nexus 9 (Android 7.1.1)
• Xiaomi Mi Pad 2 (Android 5.1)

* Fenix version: 1.0.1-rc.1 Build # 11851847 4/7

### Notes
[Video Google Pixel 3XL](https://drive.google.com/file/d/1uEaMwpgKZ0LOsw905ZnCBPUK10XHx15r/view?usp=sharing)

**Comment by abodea** [comment]
Reproducible on **Fenix 3.1.0-beta  3(Build #20092354) GV 72** with **Google Pixel 3a XL(Android 10).**
