### ISSUE TITLE
Tracking Protection Visibility

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/fenix#3901]
## User Story
- As a user, I want to know that my browser is protecting me from intrusive trackers, so that I feel good about using the browser with TP on and trust that it's protecting me.

## Dependencies
GV APIs available
A-C work will be required

### Acceptance Criteria
- I can see that my browser has blocked trackers
- I can clearly notice/find TP toggle and disable/enable it

**Comment by liuche** [comment]
Decided not to add badge number.

**Comment by Amejia481** [comment]
Block on https://github.com/mozilla-mobile/android-components/issues/3824

**Comment by AmyYLee** [comment]
> ## User Story
> 
>     * As a user, I want to know that my browser is protecting me from intrusive trackers, so that I feel good about using the browser with TP on and trust that it's protecting me.
> 
> 
> e.g. permanent Shield Icon indicating # of trackers blocked to provide easy visible access per site information about tracking or disable protections
> ## Dependencies
> 
> GV APIs available
> A-C work will be required
> ### Acceptance Criteria
> 
>     * I can see that my browser has blocked trackers
> 
>     * I can clearly notice/find TP toggle and disable/enable it

We will not be showing the # of trackers being blocked in the shield icon. Research has shown that the numbers are confusing (i.e not sure if a high or low number is good/bad). In addition the space in the search bar is limited.

**Comment by vesta0** [comment]
Related A-C work: https://github.com/mozilla-mobile/android-components/issues/2350

**Comment by liuche** [comment]
QA Please test: 

    I can see that my browser has blocked trackers
    I can clearly notice/find TP toggle and disable/enable it

**Comment by softvision-miralobontiu** [comment]
Verified on the latest Nightly 190916 (#12591838) with Samsung Galaxy Note 8 (Android 9), Huawei MediaPad M2 (Android 5.1.1), Huawei P9 Lite (Android 6), that:
- the shield changes color when ETP blocks trackers,
- Tracking Content displays the blocked trackers,
- ETP toggle can be turned OFF/ON, it is visible, and it works.
