### ISSUE TITLE
[Bug] Soundcloud not loading visual content on first attempt

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#3902]
### Prerequisites
Clean profile

## Steps to reproduce
1. Navigate to Soundcloud.com
2. Search for a track
3. Play the track

### Expected behavior
Page is properly loaded, visuals and audio working.

### Actual behavior
The visuals aren't loaded, the audio plays.

### Device information

* Android device: 
• Google Pixel 3XL (Android 9)
• Pixel XL (Android Q Beta 4)
• Nexus 9 (Android 7.1.1)
* Fenix version:  1.0.1-rc.1 Build # 11851847 4/7

### Notes
► Video Google Pixel 3XL
![2019_07_05_15_38_44](https://user-images.githubusercontent.com/51314259/60723974-d82a8f00-9f3d-11e9-8342-9ea684fd4a87.gif)

**Comment by ekager** [comment]
Disabling TP displays the image content, closing
