### ISSUE TITLE
[Bug] YouTube doesn't switch back from desktop site

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#3903]
## Steps to reproduce
1. Load youtube.com
2. Switch Desktop site on.
3. Switch Desktop site off.
### Expected behavior
The mobile site is displayed.
### Actual behavior
The desktop site still displayed.
Other websites behave normally.
### Device information

* Android device: Pixel 3 (Android 9), Nexus 9 (Android 7.1.1)
* Fenix version: 1.0.1 rc1 (#11851847)

**Comment by sblatz** [comment]
This is happening because YouTube is actually changing the URL to `https://www.youtube.com?app=desktop`, so when we go to disable our desktop user agent and refresh we're still loading that desktop page. 

@cpeterso this sounds like a GV bug, is it one you're aware of?

**Comment by cpeterso** [comment]
I filed a new GV bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1570071

**Comment by cpeterso** [comment]
Requesting the desktop site works correctly in Chrome, Fennec, and Focus+GV. In these browsers, YouTube switches back and forth between https://m.youtube.com and https://www.youtube.com. When Fenix or R-B request the desktop site, YouTube redirects to https://www.youtube.com?app=desktop.

Fennec, Focus+GV, and Fenix should all have the same User-Agent string, so why does YouTube behave differently?

**Comment by cpeterso** [comment]
Randall says this is an app bug. He fixed a similar bug in FxR. Fenix will be able to fix this bug using the new `LOAD_FLAGS_REPLACE_HISTORY` flag added in https://bugzilla.mozilla.org/show_bug.cgi?id=1571088 (GV 70).

**Comment by cpeterso** [comment]
Removing the `needs:gv` label because this is an app bug, not a GV bug, according the Randall: https://bugzilla.mozilla.org/show_bug.cgi?id=1570071#c2

Fenix needs to check the `LOAD_FLAGS_REPLACE_HISTORY` flag and save the original URL https://m.youtube.com, not the redirect URL https://www.youtube.com?app=desktop.

**Comment by sblatz** [comment]
Thanks for your investigation, @cpeterso 😄

**Comment by ekager** [comment]
Here's the FXR implementation we should copy over to AC's toggling functions: 
https://github.com/MozillaReality/FirefoxReality/blob/d9ed84853eeb8ffcbfe645bd5460afa554dad271/app/src/common/shared/org/mozilla/vrbrowser/browser/engine/Session.java#L988-L991

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly Build 200810 from 8/10`** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 10)
• OnePlus A3 (Android 6.0.1)

► Video
![20200810-103816](https://user-images.githubusercontent.com/51314259/89761283-b6171f00-daf6-11ea-86b8-90d6e605fa90.gif)
