### ISSUE TITLE
[Bug] Switching tabs shows a white screen

### ISSUE THREAD

**Issue by bogas04** [mozilla-mobile/fenix#3904]
## Steps to reproduce
Open Fenix
Open some tabs
Switch between them

![Screencast of STR](https://thumbs.gfycat.com/ForsakenInsecureGemsbuck-size_restricted.gif)
### Actual behavior
No white screen should occur/ghosting of tabs idk.

### Device information

* Android device: OnePlus 3T, Android Pie
* Fenix version:
Nightly 190704 18:04 (Build #11851810)
📦: 3.0.0
🦎: 68.0-20190612114833

**Comment by vesta0** [comment]
@AmyYLee would #1289 address this bug?

**Comment by kbrosnan** [comment]
Closing as dupe of #1289
