### ISSUE TITLE
[Bug] tablet - "Go back" button too low on high risk error pages

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#3905]
## Steps to reproduce
1. Load http://testsafebrowsing.appspot.com/s/phishing.html
2. Check the "go back" button.
### Expected behavior
The button is visible.
### Actual behavior
The button is under the fold.
### Device information

* Android device: Tablet - Nexus 9 (Android 7.1.1)
* Fenix version: 1.0.1 rc1

**Comment by mcarare** [comment]
@sv-ohorvath Can you please check if the bug is still reproducing?

**Comment by sv-ohorvath** [comment]
Yes, still reproducing on Nightly 190730. Devices verified: Sony Xperia Z2 (Android 6.0.1), Samsung Galaxy Tab A 6 (Android 5.1.1)
![Screenshot_20190730-103140](https://user-images.githubusercontent.com/4037709/62110338-dcd13180-b2b6-11e9-991f-618f364c0ed0.png)

**Comment by AndiAJ** [comment]
Hi, **verified as fixed on Nightly Build #12112106 from 30/7** using the following devices:
• Google Pixel C (Android 8)
• Samsung Galaxy Tab A (Android 7)
• Huawei Media Pad M3 Lite 10 (Android 7)

![Screenshot_20190731-142945](https://user-images.githubusercontent.com/51314259/62209353-116de780-b3a2-11e9-8dca-1a27541b86d6.png)
