### ISSUE TITLE
[Bug] Clear permissions and Go to settings buttons are missing a background

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#3906]
## Steps to reproduce
1. From system settings>Apps>Firefox Preview>Permissions, block some permissions for the app.
2. Inside the browser, load permission.site, allow some exceptions.
3. Go to Settings>Site permissions. Verify the permission blocked at Step 1, observe the Go to Settings button.
4. Open the Exceptions list, open the permission.site, verify the Clear permissions button.
### Expected behavior
The buttons have a gray background as https://github.com/mozilla-mobile/fenix/issues/3453#issue-455928280
### Actual behavior
No background.
![Screenshot_20190705-100459](https://user-images.githubusercontent.com/4037709/60728003-f3020100-9f47-11e9-9783-666cfc050584.png)
![Screenshot_20190705-101242](https://user-images.githubusercontent.com/4037709/60728171-5f7d0000-9f48-11e9-9fcf-195f8beccccd.png)

### Device information

* Android device: Nexus 9 (Android 7.1.1), Pixel 3 (Android 9).
* Fenix version: 1.0.1 rc1

**Comment by ekager** [comment]
Hm these buttons weren't actually the ones mentioned in #3453 but I agree it's a bit weird they don't match. I will follow up with UX.

**Comment by ekager** [comment]
@AmyYLee should these buttons also have the theme-independent grey button theme?

**Comment by AmyYLee** [comment]
@ekager these should have the same styling as in bug #3453

**Comment by softvision-miralobontiu** [comment]
Verified as fixed on a today debug build 1.0.1928 GV 68.0-20190612114833 with Motorola Moto G6 (Android 8), HTC Desire 820 (Android 6.0.1), and Nexus 6 (Android 7.1.1).
