### ISSUE TITLE
[Bug] Go back button from malicious websites isn't redirecting to homescreen 

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#3907]
## Steps to reproduce
1. From the home screen navigate to https://expired.badssl.com/ or http://testsafebrowsing.appspot.com/s/phishing.html  
2. Tap the "Go back" button

### Expected behavior
Should redirect to Fenix home screen

### Actual behavior
Doesn't happen anything

### Device information

* Android device: 
• Google Pixel 3XL (Android 9)
• Nexus 9 (Android 7.1.1)

* Fenix version: 1.0.1-rc.1 Build # 11851847 4/7

### Notes
If you previously loaded another page before accessing the malicious web sites the "Go back" button works properly

**Comment by ekager** [comment]
The current fix is to hide the go back button in the error page if there's no history. The user will still be able to use the system back button to get back but at least there won't be a misleading button that does nothing :)

**Comment by softvision-miralobontiu** [comment]
Verified that, after loading https://expired.badssl.com/ or http://testsafebrowsing.appspot.com/s/phishing.html, and tapping on the devices back button, the user is redirected to the homepage.
Tested with a locally build from 8/5 master with LG G7 Fit (Android 8), and Sony Xperia Z5 Premium (Android 7.1.1).

**Comment by abodea** [comment]
Reproducible on **Fenix 3.1.0-beta  3(Build #20092354) GV 71** with **Google Pixel 3a XL(Android 10).**
