### ISSUE TITLE
Home button is not visible

### ISSUE THREAD

**Issue by colintheshots** [mozilla-mobile/fenix#391]
## Steps to reproduce
1. Open a web page from the search toolbar in-app (as opposed to custom tabs or external intents).

### Expected behavior
The home button should appear as it isn't a custom tab.

### Actual behavior
The home button does not appear, since the ToolbarIntegration is not aware of the session ID to check if it is a custom tab.

### Device information

* Android device: Android emulator, API 28 x86
* Fenix version: Milestone 1

**Comment by sv-ohorvath** [comment]
Verified as fixed on 2/10 build.
