### ISSUE TITLE
Should be allowed to to visit an insecure page anyway.

### ISSUE THREAD

**Issue by wisniewskit** [mozilla-mobile/fenix#3910]
## Steps to reproduce (as reported at https://webcompat.com/issues/34583)
Visit sistemas.anac.gov.br

### Expected behavior
Fennec, Chrome mobile and desktop browsers allow opting into visiting the site anyway, despite the security issue.

### Actual behavior
Fenix does not allow opting into visiting the page anyway.

### Device information

* Android device: Samsung Galaxy S7, Android 8.0.0
* Fenix version: Nightly 190704 18:03 (build #11851810)

**Comment by sblatz** [comment]
I filed an [ac issue](https://github.com/mozilla-mobile/android-components/issues/3960) for this as it will need to be addressed there. That being said, I agree and feel we should allow users to override our warning if wanted.

**Comment by cpeterso** [comment]
GV bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1553265

**Comment by vesta0** [comment]
Removed the bug label as this is a feature request

**Comment by vesta0** [comment]
We will track this request here: #6380
