### ISSUE TITLE
[Bug] auto refresh not working when app was closed

### ISSUE THREAD

**Issue by kolAflash** [mozilla-mobile/fenix#3915]
## Steps to reproduce
1. Open a page.
2. Close tab.
3. Stop Firefox Preview (e.g. via Android app properties ui).
4. Open Firefox Preview again, AFTER content has changed.
5. Open same page again.

If you have a website, use a simple HTML site for testing and just change something before step 4.
Else you may edit some content from ANOTHER BROWSER on GitHub. (e.g. create a project in your account and delete it again)

### Expected behavior
Up-to-date content is being displayed.

### Actual behavior
Cached page is being shown.

### Device information
* Samsung Galaxy S4 Mini (i9195 / serranoltexx)
  * OS: Android 8.1 (LineageOS-15.1)
  * Fenix version: 190705 18:03
* Fairphone 2
  * OS: Android 8.1 (LineageOS-15.1)
  * Fenix version: 190703 18:02

**Comment by sblatz** [comment]
Sounds like this is probably a GV or AC issue. Are you able to reproduce in Reference Browser?

**Comment by kolAflash** [comment]
Looks like the problem disappeared with one of the recent updates.
Also can't reproduce in the Reference Browser.

Thanks for the help!
