### ISSUE TITLE
[Bug] Load more comments js behaving strangely

### ISSUE THREAD

**Issue by force1164** [mozilla-mobile/fenix#3917]
## Steps to reproduce
1. go to mobilenet.cz
2. click on any article with more than 4 comments
3. scroll down to comment section (called DISKUZE KE ČLÁNKU)
4. click on "NAČÍST VŠECHNY KOMENTÁŘE" (load all comments)

### Expected behavior
more comments are loaded

### Actual behavior
Some code is displayed. (see screenshot)

### Device information
OnePlus 6

* Android device: yes, pie.
![Screenshot_20190706-180950](https://user-images.githubusercontent.com/2920574/60758676-3fb60c80-a01a-11e9-8747-8a099fee6799.jpg)

* Fenix version: build #11861807

**Comment by ekager** [comment]
Can reproduce in RB and not in Chrome so I filed a GV bug here: https://bugzilla.mozilla.org/show_bug.cgi?id=1563990

**Comment by ekager** [comment]
Can't repro anymore. Closing
