### ISSUE TITLE
[Bug] Intents don't open the default app when available

### ISSUE THREAD

**Issue by scjb** [mozilla-mobile/fenix#3920]
## Steps to reproduce
1.Install wikipedia Android App
2.Make sure the Wikipedia App is set to handle URLs from wikipedia by default
3.Go to wikipedia.org

### Expected behavior
Wikipedia app opens automatically and displays the article

### Actual behavior
Firefox opens the article itself, instead of respecting the system default app for the wikipedia.oeg URLs

### Device information

* Android device: Galaxy s7 edge
* Fenix version: Nightly 190705 18:03 (Build #11861807)

**Comment by Minabsapi** [comment]
Looks like an intent error.
Also, consider adding a proper title instead of just a tag, for readability.

**Comment by nahuhh** [comment]
Intents uses to work, although far too aggressively. #3349 refers to this and offers a different take on implementation

**Comment by neekless** [comment]
This is intentionally disabled temporarily https://github.com/mozilla-mobile/fenix/issues/3358, as it still needs to be worked on.

**Comment by jhugman** [comment]
This is being tracked on the [Android Intent URLs board][0].

[0]: https://github.com/orgs/mozilla-mobile/projects/32
