### ISSUE TITLE
[Bug] [a11y] "No history here" is not read after deleting all history 

### ISSUE THREAD

**Issue by softvision-miralobontiu** [mozilla-mobile/fenix#3922]
### Steps to reproduce
1. Turn Talkback on.
2. Visit at least a page.
3. Go to Settings - Your library - History and delete all history.

### Expected behavior
The voice assistant should read "No history here".

### Actual behavior
The voice assistant announces "List" instead of "No history here".

### Device information
* Android device: Motorola Moto G6 (Android 8), Sony Xperia Z2 tablet (Android 6.0.1)
* Fenix version: 1.0.1 RC build 1

**Comment by ekager** [comment]
Adding the good first issue label. Whomever picks this up will need to add an accessibility announcement here in `HistoryView`
https://github.com/mozilla-mobile/fenix/blob/master/app/src/main/java/org/mozilla/fenix/library/history/HistoryView.kt#L138

**Comment by ekager** [comment]
Reopening for QA needed

**Comment by softvision-miralobontiu** [comment]
Verified as fixed with the latest Nightly build 190807 (#12190609) with Motorola Moto G6 (Android 8), Huawei Media Pad M2 (Android 5.1.1), and Nokia 6 (Android 7.1.1).
