### ISSUE TITLE
[Bug] Turn on Sync & Create an account not working if a number less than 13 is entered in the Create Account wizard

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#3925]
## Steps to reproduce
1. Tap "Settings" 
2. Tap "Turn on Sync"
3. Tap "Create an account"
4. Enter valid email and passwords
5. For Age ("How old are you?") enter a number < 13

### Expected behavior
A simple and easy way for the user to be redirected to the create account wizard, without being needed to close, re-open Fenix and to restart the whole process 
Properly working "Turn on Sync" &  "Create an account" 

### Actual behavior
After entering a value < 13 in the Age section, a loop seems to created.
If taped "Turn on Sync" the "Cannot create account" screen is presented 
If taped "Create an account" the "Cannot create account" screen is presented again 

**The only way to make them work again is to close and re-open Fenix.**

### Device information

* Android device: 
• Google Pixel 3XL(Android 9)
• Samsung Galaxy S9 (Android 8)

* Fenix version: Nightly Build #11890607 from 8/7/2019

### Notes
► Video from Google Pixel 3XL
![2019_07_08_17_31_01](https://user-images.githubusercontent.com/51314259/60819873-052eaa00-a1a9-11e9-8f4f-c204a87c5f5a.gif)

**Comment by kbrosnan** [comment]
This is expected behavior. https://bugzilla.mozilla.org/show_bug.cgi?id=1553793
