### ISSUE TITLE
[spike] Re-evaluate the usability and discoverability Quick Action Bar

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/fenix#3927]
## User Story
- As a user, I want an intuitive way to add a bookmark or access frequent just-in-time actions without unwanted triggering of the Quick Action Bar when I am browsing and interacting with a site, so I can have a streamlined browsing experience. 

### Acceptance Criteria
- I know how to add a bookmark
- I don't accidentally trigger the Quick Action Bar

------------------------
User feedback:

- Adding a bookmark is somewhat hidden. Some users thought we didn't have bookmarks anymore and had replaced bookmarks with collections and wondering why collections don't sync with bookmarks.

- Quick action bar is triggered unintentionally when interacting with a website, yet hard to find when needed. 

Here's a comparative usage graph indicating frequency of "Share" through QAB vs tab menu, indicating that discoverability through QAB is low: https://sql.telemetry.mozilla.org/dashboard/fenix-share-events

Let's re-evaluate whether we want to keep the Quick Action Bar or how we can enhance it's usability and discoverability.

Reference Bugs:
https://github.com/mozilla-mobile/fenix/issues/3282#issuecomment-500534851
Add find in page: https://github.com/mozilla-mobile/fenix/issues/2056 
QAB interferes with scrolling: https://github.com/mozilla-mobile/fenix/issues/3876
menu and QAB: https://github.com/mozilla-mobile/fenix/issues/3852
include tab switching: https://github.com/mozilla-mobile/fenix/issues/3798
remove dup option #3844

**Comment by vesta0** [comment]
@shorlander FYI in Michelle's absence.

**Comment by beastdestroyer** [comment]
@vesta0 Perhaps Fenix could have one of those popups like a "tutorial" at first that shows where it is.

To make it seem more intuitive, perhaps the user could customise the actions in the bar? Or customise the address bar as a whole. This would definitely push Fenix to be more on board with the desktop versions, and with extensions (which could go inside the QAB too qe shortcuts), I see great potential.

Please let me know if you want a detailed issue 

(Lurker of the fenix repo)

**Comment by thecyberpope** [comment]
I think #3798 has huge potential to make the QAB a very powerful tool.

**Comment by lime124** [comment]
removed ux label -it's on our radar already as it's part of the Q3 plan

**Comment by liuche** [comment]
Also waiting on a decision that will come out of @apbitner's NavBar #3651 design work.

**Comment by cronosun** [comment]
> @vesta0 Perhaps Fenix could have one of those popups like a "tutorial" at first that shows where it is.

I think if you have to explain ("tutorial") the UI, there's something wrong with the UI.

**Comment by apbitner** [comment]
Turning this into an investigational task to determine next steps so that we can more accurately size

**Comment by vesta0** [comment]
@apbitner thanks for investigating. Maybe surfacing a contextual message (similar to what Amy built for Launch in private mode) about QAB as part of onboarding would work. Looking forward to your thoughts.

**Comment by lime124** [comment]
this is waiting on the final decisions regarding the navigation bars and auto-scrolling with GV.

**Comment by liuche** [comment]
@lime124 checking in since it's been a while - I mentioned Adam in another bug but did we reach any sorts of conclusions with this? Is this feasible with GV, or should we do some fallbacks, or should we just deprioritize this work until the future?

**Comment by apbitner** [comment]
QAB will be removed for now, and revisited once we're able to implement auto show/hide next year.

**Comment by liuche** [comment]
Context: UX wanted to do auto-hide on scroll, but this requires a ton of GV work and won't be ready until Q1.

Due to usability issues, and swiping affecting pull to refresh (?), we're going to remove the QAB, and add the option to have a top nav bar.
