### ISSUE TITLE
[Bug] Not using consistent wording when deleting history

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#3939]
We should either use "Delete" or "Clear" consistently
<img width="350" alt="Screen Shot 2019-07-08 at 1 23 10 PM" src="https://user-images.githubusercontent.com/4400286/60840182-c5090080-a183-11e9-8ddb-4f476187e5f6.png">
<img width="350" alt="Screen Shot 2019-07-08 at 1 23 12 PM" src="https://user-images.githubusercontent.com/4400286/60840185-c6d2c400-a183-11e9-8df4-87f514925a7a.png">

**Comment by yoasif** [comment]
Desktop uses Clear in the library toolbar entry and in the history menu, along with the dialog that appears once selected.

**Comment by lime124** [comment]
@mheubusch please confirm which we want to go with. thanks!

**Comment by mheubusch** [comment]
@sblatz **Please use Delete and make the delete history  delete browsing data patterns consistent - please note changes in the strings below. Also, I  could not find a string for a History deleted snackbar.  If there is one, can you point me to it?**

<string name="history_delete_all">Delete history</string>
    
    <string name="history_delete_all_dialog">This will delete your browsing history.</string>
    
    <string name="history_clear_dialog">Delete</string>
    
    

    <string name="preferences_delete_browsing_data_prompt_message">This will delete all of your browsing data.</string>
    
    <string name="preferences_delete_browsing_data_prompt_cancel">Cancel</string>
    
    <string name="preferences_delete_browsing_data_prompt_allow">Delete</string>

**Comment by ekager** [comment]
Let's pull these strings in today before string freeze and someone can pick up the changes in this sprint
