### ISSUE TITLE
Support Trusted Web Activity

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/fenix#394]
_QA team: steps to test are [outlined in a comment below](https://github.com/mozilla-mobile/fenix/issues/394#issuecomment-533738751)._

---

### Why/User Benefit/User Problem

Trusted Web Activities are a way to integrate your web-app content such as your PWA with your Android app using a protocol based on Custom Tabs.

### User Story
As a user I want Progressive Web Apps installed from the Google Play store to use my default browser.

### What / Requirements

https://docs.google.com/document/d/1XMMJNJO1VUEBn1jGGIf8b-lHZJuZUuZnjQoX5LSmq8c/edit#
https://developers.google.com/web/updates/2017/10/using-twa

### Acceptance Criteria (how do I know when I’m done?)

- [ ] I can download a TWA from the Google Play Store and run it in Fenix.

**Comment by pocmo** [comment]
Related A-C meta bug:
https://github.com/mozilla-mobile/android-components/issues/1819

**Comment by liuche** [comment]
I've added some more details about TWA in the AC bug.

**Comment by liuche** [comment]
After some discussion w/ the team, it sounds like TWAs are almost ready to ship. This allow users who download TWAs from the Google Play Store to use Fenix.

Things remaining:
- [ ] any remaining eng work (@NotWoods will be finishing this)
- [ ] AC to upgrade to alpha APIs*
- [ ] File a PI request to test some common TWAs (@liuche)
- [ ] Get UX Feedback (@NotWoods will share an apk link here, and add gif how TWAs work on Chrome + instructions on how to install)
- [ ] signoff from Product - Notifications won't work until we support Push (WebPush?) but we're in Preview, so I'm not too worried

* Most of the APIs that we're using are stable, but the mitigation plan is a) revert on AC, b) reach out to Google androidx team, who have been very responsive

**Comment by liuche** [comment]
@NotWoods question came up in triage, "what TWA features won't work?"
- Offline support (e.g. loading from offline
- Push
- what else?

Product says let's do this in Nightly only.

**Comment by NotWoods** [comment]
Splash screens also won't work yet. Both notifications and splash screens require APIs only present in the 1.2.0 library, and would make it harder to revert.

**Comment by NotWoods** [comment]
Updated the TODO list: We have an API key for TWAs ready but its not yet accessible in the codebase. @jonalmeida will be adding it in soon.

**Comment by NotWoods** [comment]
The TWA pull request (#5391) is ready for review from UX and QA. 

I've found an example of a Trusted Web Activity [opening in Chrome from Google I/O](https://youtu.be/6lHBw3F4cWs?t=432):
![ezgif-5-e18398b553f4](https://user-images.githubusercontent.com/1782266/65363360-43404500-dbc0-11e9-9b34-8868bfcf59ff.gif)

Here are some apps using Trusted Web Activities we can test with:
- https://play.google.com/store/apps/details?id=com.tigeroakes.insightfulenergy
- https://play.google.com/store/apps/details?id=com.appspot.pwa_directory
- https://play.google.com/store/apps/details?id=br.com.quintoandar.inquilinos

I'll post an APK link here when available. 

To test, install the APK and make sure that build of Firefox Preview is set as your default browser in your Android settings. Once set as default, open an app using Trusted Web Activities and it should open using Firefox Preview to render web content.

**Comment by liuche** [comment]
Tagging @apbitner, since I think he's done a lot of the work on PWAs.

Could you take a look and make sure this looks okay? We were discussing keeping this on Nightly, since I know UX is strapped for resources.

**Comment by sblatz** [comment]
I think we need follow-up from @liuche on the status of this ticket.

**Comment by apbitner** [comment]
I downloaded the first app along with the latest APK and launched the app. This work seems to be behind the scenes so I didn't notice anything that needs to be reviewed from a UX perspective, unless I'm missing something?

**Comment by NotWoods** [comment]
The UX would be very light, if any. All Chrome does here is display the "Running in Chrome" snackbar.

**Comment by apbitner** [comment]
If it's just staying on Nightly then it should be good for now. We may add a 'Running in Firefox' notification at some point.

**Comment by liuche** [comment]
Marking E2 for remaining review work, since there's no additional ask from UX.

**Comment by NotWoods** [comment]
@liuche Should we put QA needed on this issue?

**Comment by liuche** [comment]
Yes please! But also include a comment with clear "Steps to Reproduce" (including which build flavor or channel they should be on).

**Comment by NotWoods** [comment]
[**Steps to reproduce**](https://github.com/mozilla-mobile/fenix/issues/394#issuecomment-533738751)

**Comment by sv-ohorvath** [comment]
@NotWoods Using the apks and steps from https://github.com/mozilla-mobile/fenix/issues/394#issuecomment-533738751 I've found the following:
- The [Oyo lite](https://play.google.com/store/apps/details?id=com.oyo.consumerlite&hl=en) app doesn't launch on Fenix, returns an "App keeps stopping" error.
- Cannot open external links in any TWA, the links appear as visited in the browser history (i.e in PWA directory).
- In the [PWA directory app](https://play.google.com/store/apps/details?id=com.appspot.pwa_directory) the notification alert button doesn't prompt the permission request (probably the same for location, cam or mic permissions, I haven't found any TWA examples for these yet).
