### ISSUE TITLE
Undo Close Tab

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/fenix#3944]
### Why/User Benefit/User Problem

I'd like a way to undo closing a tab because sometimes I accidentally close tabs and miss the undo in the snackbar.

### What/Requirements

* New menu item in kebab menu near open tabs with option "Undo Close Tab" that reopens the last closed tab, exactly like the snackbar does. 

### Acceptance Criteria (how do I know when I’m done?)

I am able to use a persistent menu item to reopen the last closed tab. Ideally, this would work like desktop, and let me reopen a number of closed tabs if I select the menu item more than once.

**Comment by buttercookie42** [comment]
See also #2486 (it's not always the last tab I want to restore, so being able to choose that tab directly instead of having to sequentially restore all tabs until I reach the desired one would be a clear plus).

**Comment by yaomtc** [comment]
This is in now, isn't it?

**Comment by gabrielluong** [comment]
> This is in now, isn't it?

Thanks, this was fixed by @sblatz in https://github.com/mozilla-mobile/fenix/issues/2655. Closing the issue :)
