### ISSUE TITLE
[Bug] Fenix doesn't successfully complete login to Zoom (I suspect this is a more general problem with app logins that require Web logins)

### ISSUE THREAD

**Issue by ckarlof** [mozilla-mobile/fenix#3945]
## Steps to reproduce
Set Fenix as your default browser. Log into the Zoom app with your Mozilla account.

### Expected behavior
I get logged into Zoom.

### Actual behavior
Fenix gets stuck after I complete 2FA (it doesn't finish returning to Zoom). I had to set Fennec as my default browser to successfully complete. 

### Device information
* Android device: Pixel 3
* Fenix version: Nightly 190708 18:06

**Comment by kbrosnan** [comment]
dupe #1570
