### ISSUE TITLE
[Bug] Desktop site option from Turn on Sync custom tab doesn't work properly

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#3947]
## Steps to reproduce
1. Tap upper right 3 dot button
2. Tap Settings
3. Tap Turn on Sync
4. Tap upper right 3 dot button from the custom tab
5. Swipe to enable Desktop site

### Expected behavior
The requested Desktop version should be loaded without any issues

### Actual behavior
Continuously keeps loading

### Device information

* Android devices : 
• Google Pixel 3XL (Android 9)
• Samsung Galaxy S9 (Android 8)
• Samsung Galaxy S7 (Android 7.0)
• Samsung Galaxy S6 (Android 6.0.1)
• Nexus 5 Android  (6.0.1)
• Pixel XL (Android Q Beta 4)

* Fenix version: Nightly #11900609 from 9/7/2019

**Comment by ekager** [comment]
Cc @vladikoff is it expected that requesting the desktop version of the fxa sign in would never load?

**Comment by vladikoff** [comment]
It should load!

If we go to accounts.firefox.com directly in the browser and request desktop site, then it will also trigger this issue.

Filed https://github.com/mozilla/fxa/issues/2036

**Comment by ekager** [comment]
Cannot reproduce anymore. Closing
