### ISSUE TITLE
[Bug] Open in Firefox Preview option from Turn on Sync custom tab doesn't work properly

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#3949]
## Steps to reproduce
1. Tap upper right 3 dot button
2. Tap Settings
3. Tap Turn on Sync
4. Tap upper right 3 dot button from the custom tab
5. Tap Open in Firefox Preview

### Expected behavior
The tab is opened without any issues in Firefox Preview

### Actual behavior
Crash

### Device information

* Android device: 
• Google Pixel 3XL (Android 9)
• Samsung Galaxy S9 (Android 8)
• OnePlus 5T (Android 9)

* Fenix version: Nightly #11900609 from 9/7/2019

### Notes 
Could not reproduce on the following devices:
• Samsung Galaxy S7 (Android 7.0)
• Samsung Galaxy S6 (Android 6.0.1)
• Nexus 5 (Android 6.0.1)
• Pixel XL (Android Q Beta 4)

<details>
    <summary>Logcat & video from Samsung Galaxy S9</summary>

**Logcat**:[Logcat.txt](https://github.com/mozilla-mobile/fenix/files/3372792/Logcat.txt)

**Video**
![20190709_144721](https://user-images.githubusercontent.com/51314259/60885937-644bf780-a259-11e9-8a45-4ea7e8148336.gif)

</details>

**Comment by ekager** [comment]
I'm not seeing this auto-crash any more. That being said, we probably don't want people to open this internal custom tab in the normal browser. Should we remove the menu altogether for auth custom tabs? Do we really need to be able to find in page and request desktop site here?

**Comment by AndiAJ** [comment]
Hi, me neither, it doesn't crash anymore, on the latest Fenix Nightly Build #12190111 from 7/8.
I've used the following devices:
• Google Pixel 3a (Android 9)
• OnePlus 5T (Android 9)
• Samsung Galaxy S9 (Android 8)
• Samsung Galaxy S7 (Android 7.0)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

► Video Google Pixel 3a
![20190807_103538](https://user-images.githubusercontent.com/51314259/62604934-bbe58d80-b901-11e9-9ab1-9c2ff332b460.gif)
