### ISSUE TITLE
Pass sessionId to `ToolbarUIView` for Custom Tabs

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/fenix#395]
Follow up for https://github.com/mozilla-mobile/fenix/pull/333#discussion_r252859732

The [current fix](https://github.com/mozilla-mobile/fenix/pull/392) works only for the selected session but not for custom tabs.

It's also worth considering the toolbar styling and menu options done here would be different in a custom tab.

**Comment by pocmo** [comment]
Oh,  I didn't know this was filed already. Anyhow, I opened a PR for that today :)

#408

**Comment by boek** [comment]
This was fixed with #415
