### ISSUE TITLE
Clear private browsing data when closed in app switcher

### ISSUE THREAD

**Issue by joebloggs7657** [mozilla-mobile/fenix#3950]
### Why/User Benefit/User Problem
Feature parity with desktop Firefox.
Firefox is designed with privacy in mind and private browsing is a cornerstone for many users
Users should be able to browse the internet with the option of not having their every action being recorded
All open tabs will always be in private mode so no trace of them will be present on their closure.
Instead of having to open private tabs, some users prefer all tabs to be private by default.

### What/Requirements
User should not have to manually select the app exit button for this feature to function, rather the feature should always be functional even when the app is swiped to closure by the android app switcher
### Acceptance Criteria (how do I know when I’m done?)
When I can close Firefox from the app switcher and reopen with no trace of browsing data.
When my device can abruptly power off and upon restarting Firefox there is no browsing data traces.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-12498)

**Comment by cadeyrn** [comment]
Why do you give a _thumbs up_ and a _heart_ emoji to your own comment? 🤔

I don't know what exactly you want to be implemented because there is already a private mode and it is already the case that all private tabs are closed if you exit the app (for example via recent apps).

**Comment by joebloggs7657** [comment]
So I think it would be great to have an option in the settings for private browsing to be always on. It's literally in desktop Firefox btw so it's not something obscure and niche. Me liking my own comments perhaps is lol but I mean it's fairly common on Instagram and Reddit by default likes your own comments so...♥️

**Comment by cadeyrn** [comment]
> I think it would be great to have an option in the settings for private browsing to be always on. It's literally in desktop Firefox btw so it's not something obscure and niche.

Thanks. Now the request is much clearer to me.

**Comment by mcladyz** [comment]
Indeed. Desktop Firefox clears the data when closed and users probably don't remember to select "Exit" from the mobile version menu (At least I don't).

When you want to close a application in Android, you normally do it by removing the app/instance from the switcher list.

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807458

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
