### ISSUE TITLE
[Bug] Dependency errors when running UI tests with taskcluster

### ISSUE THREAD

**Issue by rpappalax** [mozilla-mobile/fenix#3952]
I'm trying to run a taskcluster build on a forked fenix branch to which I've added CI for UI tests.  Unfortunately, I'm running into some dependency errors and wondering if you might have any insight.  It looks similar to what we saw before w/ a-c and r-b.

The branch is here:
https://github.com/rpappalax/fenix/commit/e2d9b521202ed6f25758f881fc336183b3a1d44a

see dependency errors on UI test job here.  Suggestion is to add "desugaring" those compileOptions, but we already have those in place 🤔 so.... not sure.
https://tools.taskcluster.net/groups/M4Mn5m-RRtSnsY_mH9g4iA/tasks/IlNvgj2uTEGkkdEAo5PrtQ/runs/0/logs/public%2Flogs%2Flive_backing.log

Looks like @pocmo encountered this before
https://github.com/mozilla-mobile/android-components/issues/925

we already have these compile options in build.gradle:
https://github.com/mozilla-mobile/fenix/blob/master/app/build.gradle#L106-L109

```
> Task :architecture:checkDebugAndroidTestDuplicateClasses
> Task :architecture:mergeExtDexDebugAndroidTest FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':architecture:mergeExtDexDebugAndroidTest'.
> Could not resolve all files for configuration ':architecture:debugAndroidTestRuntimeClasspath'.
   > Failed to transform artifact 'autodispose-android-archcomponents.aar (com.uber.autodispose:autodispose-android-archcomponents:1.1.0)' to match attributes {artifactType=android-dex, dexing-is-debuggable=true, dexing-min-sdk=21}.
      > Execution failed for DexingTransform: /root/.gradle/caches/transforms-2/files-2.1/e686e5aecc5fd5d57274a6b72282652f/jars/classes.jar.
         > Error while dexing.
           The dependency contains Java 8 bytecode. Please enable desugaring by adding the following to build.gradle
           android {
               compileOptions {
                   sourceCompatibility 1.8
                   targetCompatibility 1.8
               }
           }
           See https://developer.android.com/studio/write/java8-support.html for details. Alternatively, increase the minSdkVersion to 26 or above.

   > Failed to t
```

**Comment by pocmo** [comment]
> we already have these compile options in build.gradle:
> https://github.com/mozilla-mobile/fenix/blob/master/app/build.gradle#L106-L109

but not in the `architecture` module and that seems to get build here (`architecture:mergeExtDexDebugAndroidTest`) - not sure if this is even right?

**Comment by pocmo** [comment]
There are two things here:

(1) Adding the `compileOptions` in `architecture/build.gradle` fixes your build error.

(2) You are running `assembleAndroidTest` which builds a test APK for ALL variants including the `architecture` module. This is a bit too much and it would be faster to just build what you need. `app:assembleAndroidTest` will only build the test artifacts for the `app` module. Even better would be to just build the variant you need, e.g. `assembleArmDebugAndroidTest`.

**Comment by rpappalax** [comment]
@pocmo (2) solved my issue.  Thank you!
