### ISSUE TITLE
Change default search engines for Russia

### ISSUE THREAD

**Issue by Zaotar** [mozilla-mobile/fenix#3953]
First of all, thank you for this great job - renewed Firefox for android.
So, I want to ask you to change default search engines for russian locale: Google, Yandex, Mail.ru, DuckDuckGo. Twitter and Wikipedia are popular projects in Russia, but aren't popular search engines.
Or at least add please DuckDuckGo as one of the default search engines.

**Comment by kbrosnan** [comment]
Dupe #1437

**Comment by Seqularise** [comment]
But this bug is not about adding a search engine manually, its about having it by default.
In desktop firefox with russian locale it is there.
What is the problem with this? DuckDuckGo didnt payed or what?

**Comment by kbrosnan** [comment]
Search engine default are not something that the Fenix team decides. In some cases the [localization (l10n) teams](https://wiki.mozilla.org/L10n:Home_Page) can have input on the default. I don't believe Russian is such a locale.  

The only part of the request that is actionable is allowing the adding DDG which is 1437.
