### ISSUE TITLE
Private URLs not leaked to Google

### ISSUE THREAD

**Issue by Mardak** [mozilla-mobile/fenix#3954]
## Steps to reproduce

1. Open a url (in private or not)
2. Tap address bar

### Expected behavior

Google doesn't get my URLs

### Actual behavior

Google suggests searches based on the current URL
![Screenshot_20190709-141442](https://user-images.githubusercontent.com/438537/60923744-68294b00-a254-11e9-9ed8-09a61728fb7d.png)

### Device information

Fenix version: 1.0.0

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-12501)

**Comment by amkcpu** [comment]
Addressed by #1019

**Comment by kbrosnan** [comment]
This is a bit more than #1019. It would be good to not send suggestion requests for things that look like URLs. Porting the work in [bug 1184960](https://bugzilla.mozilla.org/show_bug.cgi?id=1184960) and upcoming work in [bug 1551049](https://bugzilla.mozilla.org/show_bug.cgi?id=1551049)

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807753

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
