### ISSUE TITLE
Switch tabs using swipe gesture over toolbar (left/right)

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/fenix#396]
### Why/User Benefit/User Problem

* Switching between tabs is a "heavy" task, involving a trip to a new screen, then selecting an existing tab
* competitor browsers do this and it is well liked (Chrome) 

### What / Requirements

As a user, I would like to switch between opened tabs by swiping left or right over the location bar, to save a multi-tap process to switch to another tab.

### Acceptance Criteria (how do I know when I’m done?)

I can switch between the previous or next tab in the tab stack by swiping over any area of the toolbar (left or right) except for the hamburger menu. 

Unknown if this requires consideration to i18n for LTR languages.

**Comment by vesta0** [comment]
Thanks for the suggestion. Will be addressed here: #176
