### ISSUE TITLE
[UX] Improve hitbox margin for buttons on homepage

### ISSUE THREAD

**Issue by beastdestroyer** [mozilla-mobile/fenix#3961]
### Why/User Benefit/User Problem
With larger phone screens and Fenix's minimalistic design, it is ear that in order to alleviate the pain caused by attempting to reach across the screen, the hitbox for these buttons must be improved.

The "Tab" button ans the menu icon in the address bar are hit quite easily, and this can be told from the hover animation they produce - a plus. However, I feel the buttons on the homepage: the Private Tab, the Menu, New Tab, Share etc. could have larger hitboxes, especially since from holding on the left side of the phone, it can be hard to reach

### What/Requirements
Not much if anything at all. Simply make it easier to hit (this could be shown by a large hover animation like on the address bar?)

### Acceptance Criteria (how do I know when I’m done?)
Large hover animation/easier to reach

It's also possible that an alternative exploration could be used, but as is my first issue, I don't wish to go so overboard; plus I don't really have an alternative besides this.

**Comment by NotWoods** [comment]
We've since redesigned the home menu and reduced the number of buttons. In my opinion, the remaining buttons are easier to tap and have larger touch areas. If you disagree, let me know and I can reopen the issue. 😄
