### ISSUE TITLE
[Bug] Back on the Tab Page exits Fenix

### ISSUE THREAD

**Issue by beastdestroyer** [mozilla-mobile/fenix#3962]
## Steps to reproduce
- Enter tab page or start up Fenix
- Press back or use the equivalent gesture on your phone (mine is swipe from either side)
- App closes
### Expected behavior
Fenix should return to the tab I had on. "Back" means to go back one step to something previously - in this case a tab.
I've had many inconveniences with it suddenly closing when I swipe instead of returning to my tab (chrome implements this for example)

### Actual behavior
App closes
### Device information

* Android device: Mi 8 Lite; MIUI 10.3.2.0 GLOBAL STABLE; Android 9;
* Fenix version: Nightly 190709 18:02 (Build #11901819)
📦: 3.0.0
🦎: 68.0-20190612114833

**Comment by buttercookie42** [comment]
Already came up in #2484.

**Comment by beastdestroyer** [comment]
Ah thx, will close
