### ISSUE TITLE
[Bug] "Deleted null" shown when removing a separator from the Bookmarks list

### ISSUE THREAD

**Issue by isabelrios** [mozilla-mobile/fenix#3963]
## Steps to reproduce
Sync with an account which has different bookmarks and separators
Go to Library -> Bookmarks
Select three dot menu for a separator and tap on Delete

### Expected behavior
Either there is no option to remove the separator or the message when doing that action is correct

### Actual behavior
When removing the separator it shows: "Delete null" please see video: 
https://youtu.be/qlEQLbejgyM

### Device information

* Android device: Pixel 3
* Fenix version: 7/9 build

**Comment by colintheshots** [comment]
It seems we're removing the ability to delete separators in the app, so this issue will be moot.
