### ISSUE TITLE
[Bug] Empty folders' "No bookmarks" text should be vertically-centered

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#3966]
## Steps to reproduce
1. Open an empty bookmark folder. 
Or, Open the bookmarks root folder with no bookmarks created yet.
2. Observe the text placeholder.
### Expected behavior
"No bookmarks here" is vertically-centered.
### Actual behavior
![Screenshot_20190710-114453](https://user-images.githubusercontent.com/4037709/60954930-83ee2900-a308-11e9-843f-dd89a814c05b.png)
![Screenshot_20190710-113228_Firefox Preview](https://user-images.githubusercontent.com/4037709/60954932-851f5600-a308-11e9-9f4e-cb9ffd9850ff.jpg)

### Device information

* Android device: Nokia 6 (Android 7.1.1), Galaxy Note 8 (Android 9)
* Fenix version: Nightly 190710 (#11910617)

**Comment by ekager** [comment]
This seems to be fixed, closing!
