### ISSUE TITLE
[Bug] Deleted bookmark from a folder restored because of the undo snackbar

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#3967]
## Steps to reproduce
1. Create a bookmark folder, with some bookmarks.
2. Delete an item from the folder.  (Or multiple items)
3. Before the undo snackbar goes away, tap the back button.
4. Return to the folder and observe the deleted bookmark(s).
### Expected behavior
The items are deleted.
### Actual behavior
Deleted bookmarks are back in the folder.
### Device information

* Android device: Nokia 6 (Android 7.1.1), Galaxy Note 8 (Android 9)
* Fenix version: Nightly 190710 (#11910617)

**Comment by AndiAJ** [comment]
Hi @ekager , this is still reproducible on debug build 1.0.1934 from 22/8 using the following devices:
• Google Pixel 3a (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)

►Video from Google Pixel 3a (Android 9)
![ezgif com-video-to-gif (3)](https://user-images.githubusercontent.com/51314259/63522255-a7f47b00-c500-11e9-8e10-c17d050a1100.gif)

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on The latest Nightly Build #12380610 from 26/8 using the following devices:
• Google Pixel 3a (Android 9)
• Huawei Mate 20 lite (android 8.1.0)
• Samsung Glaxy S7 (Android 7)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (android 5.1.1)

► Video Google Pixel 3a 
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/51314259/63677501-be971c80-c7f5-11e9-92aa-7277c8960982.gif)
