### ISSUE TITLE
[Bug] [Onboarding] Switching themes displays the homescreen briefly 

### ISSUE THREAD

**Issue by softvision-miralobontiu** [mozilla-mobile/fenix#3968]
## Steps to reproduce
1. Make sure you have a clean profile.
2. Go to Theme card and switch themes.

### Expected behavior
Themes should change smoothly, no other pages should be displayed in between.

### Actual behavior
The homescreen is displayed very briefly while changing from light theme to dark, or vice-versa. Please see the slow motion short video.

### Device information
* Android device: Huawei Honor 8 (Android 7), Motorola Nexus 6 (Android 7.1.1), HTC 10 (Android 8)
* Fenix version: Nightly build 20190710 (#11910617)

![Trim_Slomo](https://user-images.githubusercontent.com/40694158/60956260-1f809900-a30b-11e9-9a9e-818be96a8bf1.gif)

**Comment by sblatz** [comment]
Dup of https://github.com/mozilla-mobile/fenix/issues/3379
