### ISSUE TITLE
[Bug]For some Media Markt online shops the content isn't loaded when tapping on promotional banners

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#3970]
## Steps to reproduce
1. Navigate to http://mediamarkt.com/
2. Tap "Visit other onlineshops"
3. Select "Austria"
4. Tap on promotional banner

### Expected behavior
Promotion info and products should be properly loaded.

### Actual behavior
Looking at Fenix page load bar it seems that nothing happens, only the MediaMarkt rotating load circle is presented.

### Device information

* Android device: 
• OnePlus 6T (Android 9)
• Samsung Galaxy S9(Android 8)
• Huawei Honor 8 (Android 7)

* Fenix version: Nightly Build #11910617 from 10/7

### Notes
I've encountered the same behavior for  Hungary, Turkey & Greece onlineshops.
For Germany it worked properly.

<details>
    <summary>Video for Austria onlineshop</summary>

![20190710_125002](https://user-images.githubusercontent.com/51314259/60961150-29f36080-a314-11e9-9165-9d291c9ecf9a.gif)

</details>

**Comment by ekager** [comment]
Could we retest? I can't reproduce

**Comment by AndiAJ** [comment]
Hi, **still reproducible** on the latest **Nightly Build #12130027 from 1/8** using the following devices:
• Google Pixel 3a (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
