### ISSUE TITLE
[Bug] Nike.com customize feature not working  

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#3973]
## Steps to reproduce
1. Navigate to https://m.nike.com/ro/en_gb/product/mercurial-superfly-6-academy-id/?piid=10000510&pbid=787514192
2. Notice the animation of the ![Screenshot_20190710-162344_2 (1) (1)111111111111](https://user-images.githubusercontent.com/51314259/60972951-e9a1db80-a32f-11e9-8632-9eea6ee16a09.png) "Edit design" sign and tap it

### Expected behavior
The "Edit design" sign should rotate and after taping it the user should be able to customize the selected item

### Actual behavior
No rotation animation happens and when tapping the "Edit design" sign seems to be triggering a selection of the products image.

### Device information

* Android device: 
• OnePlus6T (Android 9)
• Samsung GalaxyS9 (Android 8)
• Samsung Galaxy S6 (Android 6.0.1)

* Fenix version: Nightly Build #11910617 from 10/7

### Notes
Work properly on the following devices:
• Google Pixel 3XL (Android 9)
• Samsung Galaxy S7 (Android 7)

<details>
    <summary>Videos</summary>

   ###  ✅Video from Google Pixel 3XL:
![Pixel](https://user-images.githubusercontent.com/51314259/60973892-bfe9b400-a331-11e9-83e1-18f4a1863a74.gif)

   ###  ❌Video from OnePlus6T:
![OnePlus](https://user-images.githubusercontent.com/51314259/60974037-05a67c80-a332-11e9-8753-c00ca692569e.gif)

</details>

**Comment by ekager** [comment]
Can we retest? Works for me in current build

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **Nightly Build #12130027 from 1/8** using the following devices:
• Google Pixel 3a (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)
