### ISSUE TITLE
[Bug] Tumblr.com layout issue

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#3974]
## Steps to reproduce
1. Navigate to https://fallontonight.tumblr.com/
2. Check page layout

### Expected behavior
No layout issues, everything should be properly displayed.

### Actual behavior
Layout issues mostly regarding the display of the gifs. which aren't centered.

### Device information

* Android device: 
• OnePlus6T (Android 9)
• Samsung GalaxyS9 (Android 8)
• Samsung Galaxy S7 (Android 7)
• Samsung Galaxy S6 (Android 6.0.1)

* Fenix version: Nightly Build #11910617 from 10/7

### Notes
[Fenix video from OnePlus6T](https://drive.google.com/file/d/1haVGutfbFqBuUrsBB6DwW350sKFdtP7Z/view?usp=sharing)
[Chrome  video from OnePlus6T](https://drive.google.com/file/d/1uVvxp62XgJeoexSgUOLxuHEFRRhgY-j9/view?usp=sharing)

**Comment by sblatz** [comment]
Definitely a GV issue. [I filed](https://bugzilla.mozilla.org/show_bug.cgi?id=1571557).

**Comment by sblatz** [comment]
This will not require any Fenix work and is up to GV to decide the priority so I'm labeling this a p5 for us as we won't get a patch for this until someone prioritizes it there.

**Comment by dholbert** [comment]
> Definitely a GV issue. I filed.

I investigated, and in fact the issue is that Tumblr is relying on the [non-standard `zoom` property](https://developer.mozilla.org/en-US/docs/Web/CSS/zoom) in Chrome, and their standards-based fallback codepath (which Firefox gets) is not quite complete.  This is a webcompat bug -- we need to ask Tumblr to fix their code, and I suggested a fix on bugzilla.

**Comment by sblatz** [comment]
Thanks @dholbert!

**Comment by cpeterso** [comment]
Webcompat bug 1571557 was closed as a duplicate of webcompat bug https://bugzilla.mozilla.org/show_bug.cgi?id=1081494.

**Comment by cpeterso** [comment]
Tumblr WebCompat bug: https://github.com/webcompat/web-bugs/issues/41889

**Comment by ekager** [comment]
Looks like this might have been fixed on the site side and is ready to test

**Comment by kbrosnan** [comment]
This looks like it is good. Checked the site in comment 0 and there are several other people mentioning it working in the other issues.

**Comment by AndiAJ** [comment]
Hi, verified as fixed on the latest Nightly Build #21120610 from 4/21 using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)

► Video
![20200421-095810](https://user-images.githubusercontent.com/51314259/79835626-b066c380-83b7-11ea-85e0-1bf51b736f6d.gif)
