### ISSUE TITLE
[Bug] Missing tweets section from Wimbledon.com

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#3975]
## Steps to reproduce
1. Navigate to https://www.wimbledon.com/en_GB/interactive/index.html
2. Observe the section under the live video player

### Expected behavior
The latest Wimbledon channel Tweets section should be displayed and available for interaction

### Actual behavior
The latest Wimbledon channel Tweets section is missing

### Device information

* Android device: 
• Google Pixel 3XL (Android 9)
• OnePlus6T (Android 9)
• Samsung GalaxyS9 (Android 8)
• Samsung Galaxy S7 (Android 7)
• Samsung Galaxy S6 (Android 6.0.1)

* Fenix version: #11910617 from 10/7

### Notes
[Fenix video from Google Pixel 3XL](https://drive.google.com/file/d/1kUvAnS7KIPk3eeE3g7KBTueXabOhFkK-/view?usp=sharing)
 [Chrome video from Google Pixel 3XL](https://drive.google.com/file/d/1J7bkckjjQLMcNryhFs69I6zCS7PBrv5F/view?usp=sharing)

</details>

**Comment by ekager** [comment]
Correct. With TP disabled the tweets appear. Closing this
