### ISSUE TITLE
Home button is not visible 

### ISSUE THREAD

**Issue by topotropic** [mozilla-mobile/fenix#398]
## Steps to reproduce
Open a URL, home button is missing in bottom app bar.

### Device information

* Android device: Pixel 3
* Fenix version:  ? (Nightly from 07/02/2018)

**Comment by meecoffee** [comment]
where i can download nightly?

**Comment by topotropic** [comment]
We also want to replace the home icon with the tab icon. Please find attached the icon – might make sense to update it when you touch the code anyway. Also happy to open a new issue if that makes more sense. Thanks!

[Tab icon.zip](https://github.com/mozilla-mobile/fenix/files/2841068/Tab.icon.zip)

**Comment by colintheshots** [comment]
This is a consequence of the changes for custom tabs. I'm already have a solution in my multitasking branch.

**Comment by topotropic** [comment]
> where i can download nightly?

@meecoffee public beta will start in Q2. Thanks for your interest!

**Comment by boek** [comment]
Fixed with #392
