### ISSUE TITLE
Synchronize Nightly version with (upcoming) production version

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/fenix#3981]
The Nightly version is generated to be `1.0.yyww` and the version of the production version is based on the tag (e.g. `v1.0.1` -> `1.0.1`).

This means currently we have:
* Nightly: 1.0.yyww
* Production: 1.0.1

Soon that will be:
* Nightly 1.0.yyww
* Production 1.1.0

There's no relationship between the Nightly version and the (upcoming) production version. As it stands Nightly is basically always `1.0.yyww`.

In the Fennec model the Nightly version (68.0a1) would be the name of the next release (68.0).

The Fennec model probably doesn't work with Fenix because it (at the moment) doesn't have a predictable, fixed schedule. And manually keeping the versions in sync will not be sustainable. Another option may be to just pick a Nightly version name that has no relationship with the actual Fenix version numbers at all?

**Comment by pocmo** [comment]
@mitchhentges What do you think?

**Comment by mitchhentges** [comment]
A few weeks ago, Colin brought up that the old `1.0.yyww` naming scheme wasn't very useful (there's more than one nightly a week, and the versions were ambiguous), so the naming scheme [was changed](https://github.com/mozilla-mobile/fenix/pull/3742) to the format "Nightly 190627 16:19".
So, we won't need to synchronize the nightly versions with production versions any more :)

**Comment by pocmo** [comment]
> (there's more than one nightly a week, and the versions were ambiguous)

That was somewhat on purpose to have some kind of grouping in Sentry and avoid having thousands of versions with 0 issues (since they are very short lived).

**Comment by mitchhentges** [comment]
Is that Sentry grouping still valuable? I can make the nightly versions be based on the week again. @colintheshots
