### ISSUE TITLE
[Bug] Autocomplete incorrectly fills urls that contain a port number.

### ISSUE THREAD

**Issue by Mossop** [mozilla-mobile/fenix#3983]
## Steps to reproduce

1. Have a url in your history that contains a port number (e.g. localhost:3012).
2. Start typing the url into the address bar (e.g. loc)
3. See what autofills

### Expected behavior

localhost:3012

### Actual behavior

localhost/:3012

### Device information

* Android device: Moto G7
* Fenix version: 1.0.0 #11721515

**Comment by mihai-adrian** [comment]
@grigoryk I've investigated this, it has to do with matchSegment function in DomainMatcher from android components. Before I make a PR for changing the placement of '/' , I wanted to ask if the desired functionality should also offer suggestions for url containing paths (localhost:8080/manager/html)

**Comment by sv-ohorvath** [comment]
Verified on Nightly 190806 the "/" is in the right place.
