### ISSUE TITLE
Break out Architecture migration issues

### ISSUE THREAD

**Issue by liuche** [mozilla-mobile/fenix#3984]
TODO: file for these components (these can be filed on a per-need basis)
TODO: @boek will add the rest of the 12 components
- [x] Quick Action sheet
- [x] History
- [ ] Bookmarks
- [ ] Session Control
- [ ] Browser Toolbar
...

## User Story
As a dev I want testable components.

## Dependencies
None - AC work for LibState is already done.

### Acceptance Criteria
File the bugs for these different component migration
Each bug description needs proper acceptance criteria which includes:
* Tests (these are already represented in other bugs)

**Comment by sblatz** [comment]
I have filed issues for the rest of the components that are not collection/home screen based since those will be changing dramatically with the redesign. Let me know if you want me to file anyway :)

**Comment by sblatz** [comment]
@liuche Can we close this or do you want me to file collection ones?

**Comment by liuche** [comment]
Nope, we can close this, unless @boek has more Architecture Components to file.
