### ISSUE TITLE
Cleaning at Browser closure

### ISSUE THREAD

**Issue by mikeGolf08** [mozilla-mobile/fenix#3988]
### Why/User Benefit/User Problem

For people who like a clean browser experience everytime they start the browser it would be better to clean the history and site data when closing the browser.
I am working with a lot of bookmarks and some collections so there is no reason to keep history and data over the period of a session.

### What/Requirements

At closure the browser is able to delete selected data.

### Acceptance Criteria (how do I know when I’m done?)

-Browser can delete data with a button to exit or via a background service which is checking for active usage (RAM usage) or the presence in Recent Apps
-The user is able to select stuff he/she wishes to be deleted after a session and is able to exclude specific data or ie. collections

**Comment by yoasif** [comment]
Dupe of https://github.com/mozilla-mobile/fenix/issues/3700
