### ISSUE TITLE
any servo code in this fenix browser same thing or just two different projects?

### ISSUE THREAD

**Issue by meecoffee** [mozilla-mobile/fenix#399]
any servo code in this fenix browser same thing or just two different projects?

**Comment by colintheshots** [comment]
Fenix uses GeckoView as the engine, so I think that's correct?

**Comment by cpeterso** [comment]
Fenix uses Gecko (via [GeckoView](https://wiki.mozilla.org/Mobile/GeckoView)), not Servo. Gecko does include some Servo components, like Stylo CSS and (coming soon) WebRender).
