### ISSUE TITLE
Investigate Fenix Performance and prioritize areas for work

### ISSUE THREAD

**Issue by liuche** [mozilla-mobile/fenix#3992]
## User Story
As a developer, I want to know what areas have performance problems, and optionally some guidelines on how to fix them.

As Product, I want to understand what the impact of performance problems are, as well as how much work it takes to fix them.

## Dependencies
None

### Acceptance Criteria
This bug is to investigate and identify (**not fix!**) areas of poor performance in Fenix.
Output: A document with a prioritized list of performance bugs, each including:
* Description of user impact
* Rough location in code where this is a problem (if applicable)
* STR
* Quick summary of how to fix/hints (optional - spend only a proportional amount of time on this)
* Size estimation of fix required

**Comment by colintheshots** [comment]
Will Hawkins and I are meeting to look over Fenix performance tomorrow. I was hoping to develop areas for investigation. We've analyzed cold start a lot, but we should create issues related to custom tab and View intent startups.

**Comment by colintheshots** [comment]
I produced an initial report using static code analysis. Will and I will find more opportunities through tracing and profiling app performance directly. Here's the current report, which I'll create issues from: https://docs.google.com/document/d/17WNYoS-ucL6FR8bAM64NzH5CAT_v7wIYgdHN0mQL_r0/edit?usp=sharing

**Comment by yoasif** [comment]
@colintheshots can you open access to that Google Doc?

**Comment by liuche** [comment]
Waiting on Wil Hawkins.
