### ISSUE TITLE
Disable bitrise and switch to taskcluster only

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/fenix#3995]
After asking on Slack it seems like no one opposes shutting down bitrise and switching to taskcluster only - which is the same pipeline we use for releases etc.

- [x] Disable bitrise runs
- [x] Mark "taskcluster" as required check instead of bitrise.
- [ ] Update Docker image - for fast builds

**Comment by eliserichards** [comment]
@JohanLorenzo are there any TC improvements that still need to be made for Fenix?

**Comment by JohanLorenzo** [comment]
Hi there! Great news, the last checkbox will be checked once https://github.com/mozilla-mobile/fenix/pull/10316 lands 👍 

@pocmo told me we can cache gradle and the full android SDK. I plan to tackle that later on. So yeah, this issue can remain closed 😃
