### ISSUE TITLE
[Bug] Crash on Android 5 & 6 when trying to sign in

### ISSUE THREAD

**Issue by softvision-miralobontiu** [mozilla-mobile/fenix#3997]
## Steps to reproduce
Tap on "Turn on sync" from Settings or from Onboarding tour.

### Expected behavior
The user should be able to sign in.

### Actual behavior
App crashes.
Please see more details [here](https://gist.github.com/vladikoff/145d0b49917839ac8b86cc98b5c36c4c).

### Device information
* Android device: Samsung Galaxy Tab A6 (Android 5.1.1), Huawei P9 Lite (Android 6) and HTC Desire 820 (Android 6.0.1)
* Fenix version:  debug build 1.0.1928 GV 68.0-20190612114833

**Comment by ekager** [comment]
Oops overlooked this. Should be fixed now!

**Comment by softvision-miralobontiu** [comment]
Verified with Samsung Galaxy Tab A6 (Android 5.1.1), and Huawei P9 Lite (Android 6), on a debug build 1.0.1928 (GV 68.0-20190612114833) from 7/12.
It doesn't crash anymore.
