### ISSUE TITLE
[Bug] Tablet - Display the turn on Sync screen buttons at the bottom, in landscape

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#3999]
## Steps to reproduce
1. On a tablet, go to Settings>Turn on Sync
2. Rotate the device to landscape.
### Expected behavior
The 2 buttons: Ready to scan and Use email instead, should be at the bottom of the page.
### Actual behavior
The buttons are displayed right under the image, leaving too much empty space.
![Screenshot_20190711-155129_Firefox Preview](https://user-images.githubusercontent.com/4037709/61052619-76ae6880-a3f4-11e9-84bd-ea6c2d1b73e5.jpg)

### Device information

* Android device: Samsung Galaxy Tab 3 (Android 8.0)
* Fenix version: 1.0.1928, 7/11 Master debug build

**Comment by mcarare** [comment]
How about centering the layout? IMO it would look better on tablets and it will also provide more accessibility without large portions of empty screen between elements.
![screen2](https://user-images.githubusercontent.com/48995920/62356516-ee664380-b519-11e9-81e6-bbfd56512ba9.png)
![screen](https://user-images.githubusercontent.com/48995920/62356535-f625e800-b519-11e9-9e9b-212dd2e716bb.png)

**Comment by lime124** [comment]
hi @mcarare and @sv-ohorvath - thanks for taking the time to file this issue and provide feedback. We haven't optimized Fenix for tablet at all so that is why you're seeing this weirdness. I've created an issue to collect this for a larger effort. Thanks!
