### ISSUE TITLE
[Bug] Turn on Sync image switches it's position while rotating the device

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#4001]
## Steps to reproduce
1. Go to Settings>Turn On Sync.
2. Rotate the device multiple times, observe the image changing its position.
### Expected behavior
The image is always centered.
### Actual behavior
Image changes its position.
![Screenshot_20190711-155810_Firefox Preview](https://user-images.githubusercontent.com/4037709/61053007-4fa46680-a3f5-11e9-8c46-58857195ecaa.jpg)
![Screenshot_20190711-155842_Firefox Preview](https://user-images.githubusercontent.com/4037709/61053008-4fa46680-a3f5-11e9-8785-722e1a591a7c.jpg)
![Screenshot_20190711-155823_Firefox Preview](https://user-images.githubusercontent.com/4037709/61053009-503cfd00-a3f5-11e9-9cc0-5e9f6327ab05.jpg)

### Device information

* Android device: Galaxy S8 (android 9), Htc 10 (Android 8), Galaxy Tab 3 (Android 8)
* Fenix version: 1.0.1928, 7/11 Master debug build

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly Build #11960610`** using the following devices:
• Google Pixel 3a (Android 9)
• Samsung Galaxy S8+(Android 8)
• Samsung Galaxy S7 (Android 7)
• Huawei Media Pad M3 Lite 10 (Android 7)
• Samsung Galaxy S6 (Android 6.0.1)
