### ISSUE TITLE
Support for drag and drop from other apps

### ISSUE THREAD

**Issue by andinorthrop** [mozilla-mobile/fenix#4004]
### Why/User Benefit/User Problem
When filling in web forms/payment pages a user may want to use split screen mode and drag a text field from one app into the relevant field on the website.

For example dragging and dropping from 1Password, as shown on this page into Chrome:

![drag-and-drop](https://user-images.githubusercontent.com/41289768/61062747-ab232400-a3f6-11e9-8f07-4da0cf88b356.gif)

https://support.1password.com/getting-started-android/#drag-and-drop-to-fill-in-other-apps

(disclaimer, I work for 1Password)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-12541)

**Comment by NotWoods** [comment]
Filed [Bugzilla 1586471](https://bugzilla.mozilla.org/show_bug.cgi?id=1586471) for GeckoView support.

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1809991

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
