### ISSUE TITLE
Migrate Share Sheet to LibState

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/fenix#4007]
We don't need most of the stateful stuff in the current ShareFragment so we can start on removing this.

**Comment by jonalmeida** [comment]
Differing this ticket until we have consensus in https://github.com/mozilla-mobile/fenix/issues/4275.

**Comment by sblatz** [comment]
Labeling this as p5 until we have a decision :)

**Comment by sblatz** [comment]
We're sticking with this custom sheet!

**Comment by jonalmeida** [comment]
Engineering notes: the share sheet actually keeps no state at all, so this would really be a refactor to remove the old architecture stuff and follow the view/interactor patterns similar to other refactors.

Also consider taking out the old send tab code and make use of the [SendTabUseCases](https://github.com/mozilla-mobile/android-components/blob/master/components/feature/sendtab/README.md) which are much easier to deal with.

**Comment by jonalmeida** [comment]
@Mugurell are you actively working on this? If you aren't planning to work on it next week, do you mind if I steal this then? :)

**Comment by Mugurell** [comment]
> @Mugurell are you actively working on this? If you aren't planning to work on it next week, do you mind if I steal this then? :)

Got sidetracked a little but finishing it up right now with some tests.

**Comment by Mugurell** [comment]
> Also consider taking out the old send tab code and make use of the [SendTabUseCases](https://github.com/mozilla-mobile/android-components/blob/master/components/feature/sendtab/README.md) which are much easier to deal with.

Looked into using [SendTabUseCases](https://github.com/mozilla-mobile/android-components/blob/master/components/feature/sendtab/README.md) but found a few issues in doing so:
- it uses [TabData](https://github.com/mozilla-mobile/android-components/blob/be70b71c972f6a1b12f822b9f96d40c6eae45e4c/components/concept/sync/src/main/java/mozilla/components/concept/sync/DeviceEvents.kt#L28) which is not Parcelable. [This is a requirement](https://developer.android.com/guide/navigation/navigation-pass-data#supported_argument_types) if we [want it sent as an argument through Navigation arch component](https://github.com/mozilla-mobile/fenix/blob/master/app/src/main/res/navigation/nav_graph.xml#L468).
- The current [ShareTab](https://github.com/mozilla-mobile/fenix/blob/671727c3e8cd6128b88934ae8d74b327c586e72c/app/src/main/java/org/mozilla/fenix/share/ShareFragment.kt#L146) also contains a `sessionId` while `TabData` doesn't. Not sure about it's importance and if it can be ignored.

**Comment by boek** [comment]
For QA: Refactor of the share sheet implementation. Please smoke test sharing to different apps and send tab 👍

**Comment by jonalmeida** [comment]
@Mugurell 

>  it uses [TabData](https://github.com/mozilla-mobile/android-components/blob/be70b71c972f6a1b12f822b9f96d40c6eae45e4c/components/concept/sync/src/main/java/mozilla/components/concept/sync/DeviceEvents.kt#L28) which is not Parcelable. [This is a requirement](https://developer.android.com/guide/navigation/navigation-pass-data#supported_argument_types) if we [want it sent as an argument through Navigation arch component](https://github.com/mozilla-mobile/fenix/blob/master/app/src/main/res/navigation/nav_graph.xml#L468).

Feel free to map the `TabData` to a `ShareTab` if needed. The use cases give us better control of the send tab APIs for all the browser apps, so we should use them.

> The current ShareTab also contains a sessionId while TabData doesn't. Not sure about it's importance and if it can be ignored.

Any one point the sessionId may have been used, but I no longer see references to it so let's just nuke that from the data class.

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on **Fenix 2.0.0-rc.1**

Tested the following:

<details>
    <summary>Tested the following:</summary>

Quick Action bar - Share button
Page menu - Page menu
Bookmarks (Single and multi-select sharing)
History (Single and multi-select sharing)
Share tabs from the tabs view
Share a tab from the main menu
Share all tabs in a collection
Share using context menus
Send tabs
Custom tabs	


</details>
