### ISSUE TITLE
Animate enable/disable state of icons in quick settings popup

### ISSUE THREAD

**Issue by NotWoods** [mozilla-mobile/fenix#4012]
![strike_thru_the_heart](https://user-images.githubusercontent.com/1782266/61086137-132a3800-a400-11e9-8f0b-1b7973cc9f3b.gif)

Use `AnimatedStateListDrawable` & `AnimatedVectorDrawable` to transition between the enabled and disabled states for tracking protection and media permissions.

**Comment by sblatz** [comment]
This is literally my favorite animation in the app 😍

**Comment by boek** [comment]
same.
