### ISSUE TITLE
[Bug] Page load performance issues

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#4017]
## Steps to reproduce
1. Navigate to https://abarmo.com/en

## Alternative Steps to reproduce
1. Navigate to https://www.3m.com/3M/en_US/restyling-studio-us/

### Expected behavior
Websites are loaded and users can use the acordingly. 

### Actual behavior
Page isn't loaded

### Device information

* Android device: 
• Samsung Galaxy S8+(Android 8)
• Samsung Galaxy S7 (Android 7)
• Samsung Galaxy S6 (Android 6.0.1)

* Fenix version: Build #11930609 from 12/7

### Notes

<details>
    <summary>Video Firefox Preview VS Chrome</summary>

►Video Firefox Preview from Samsung S8+
![20190712_104412](https://user-images.githubusercontent.com/51314259/61112232-0d7e3200-a494-11e9-8cdb-67967ede17d6.gif)

►Video Chrome from Samsung S8+
![20190712_104548](https://user-images.githubusercontent.com/51314259/61112290-31da0e80-a494-11e9-94bd-b8b62a8e9b51.gif)

</details>

**Comment by ekager** [comment]
I can load `abarmo.com/en` on my device on latest master. Let's retest.

**Comment by AndiAJ** [comment]
Hi **verified as fixed** `https://abarmo.com/en` on **Nightly build #12651809** using the following devices:
• Google Pixel 3a (Android 9)
• Samsung Galaxy Note 9 (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

`https://www.3m.com/3M/en_US/restyling-studio-us/` doesn't work on Chrome either and based on this I'll close the ticket
