### ISSUE TITLE
When sharing a page, the page title is not shared, only URL

### ISSUE THREAD

**Issue by rmisev** [mozilla-mobile/fenix#4021]
## Steps to reproduce

1. Go to any web page which have title.
2. Press "Share" menu item and select "Gmail".

### Expected behavior

Populate a share subject with the page title.

### Actual behavior

A share subject is not populated. For example if sharing to e-mail client (Gmail), a subject field is empty.

### Device information

* Android device: Nexus 5X API 28 (emulated device)
* Fenix version: 1.0.1928

**Comment by lime124** [comment]
@ekager is this part of what was discussed during planning today? should this issue be closed if we go back to a native share sheet?

**Comment by quicoto** [comment]
Same behaviour is you share to Twitter or Mastodon, user would expect "meta title + url" to be shared.

Thank you in advance

**Comment by rmisev** [comment]
@ekager can You re-open https://github.com/mozilla-mobile/fenix/pull/4022 to solve this issue?

**Comment by kamran-12** [comment]
Hmm... Are you sure it is a bug? I prefer sharing only the URL, for example.

**Comment by quicoto** [comment]
Firefox stable for Android shares title + url.

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly Build #20290608 from 1/29`** using the following devices:
• Google Pixel 3a XL (Android 10)
• Google Pixel 3a (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)

► Video
![20200129_120740](https://user-images.githubusercontent.com/51314259/73348055-5f03d800-4291-11ea-9add-f12dab91b88e.gif)
