### ISSUE TITLE
[Bug] Open tabs from collections is under the existing tab

### ISSUE THREAD

**Issue by softvision-miralobontiu** [mozilla-mobile/fenix#4024]
## Steps to reproduce
1. Open several pages.
2. Save at least one page in a collection.
3. From the collection's menu select "Open tabs" and observe where are those opened.

### Expected behavior
The tabs are all opened above the existing tabs.

### Actual behavior
The tabs are all opened under the existing tabs.

### Device information
* Android device: all
* Fenix version: 7/12 Nightly build

**Comment by sblatz** [comment]
I'm not able to reproduce this on the latest nightly. Please verify this is still happening :)

**Comment by softvision-miralobontiu** [comment]
Cannot reproduce anymore with RC 1.2.0-rc.2 with Motorola Moto g6 (Android 8).
