### ISSUE TITLE
[Bug] Amazon.com grey rectangle displayed on top right corner

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#4025]
## Steps to reproduce
1. Navigate to amazon.com

### Expected behavior
Web page is properly displayed

### Actual behavior
Grey rectangle present on the upper right side

### Device information

* Android device: 
• Samsung S8+ (Android 8)
• Samsung Galaxy S6 (Android 6.0.1)
* Fenix version: Nightly Build #11930609 from 12/7

### Notes
Isn't happening on the following devices:
• Google Pixel 3a (Android 9)
• Samsung Galaxy S7 (Android 7)
• HTC Desire 820 (Android 6.0.1)

► Video from Samsung S8+ 
![20190712_154125](https://user-images.githubusercontent.com/51314259/61129708-a9706380-a4bd-11e9-8ff8-b0b662c4a7cc.gif)

**Comment by ekager** [comment]
Are you still seeing this? I am not able to reproduce on my device

**Comment by AndiAJ** [comment]
Hi @ekager , unfortunately yes, it's still happening on Fenix Nightly Build #12190111 from 7/8.

✅ No issues encountered on the following devices:
• Google Pixel 3a (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• OnePlus A3 (Android 6.0.1)
• Samsung Galaxy S6 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

❌ Still happening on:
• Samsung S8+ (Android 8)
• Samsung Galaxy S7 (Android 7.0)

**Seems odd that it doesn't happen anymore on Samsung Galaxy S6, instead it happens on Samsung Galaxy S7**

► Pic from Samsung S8+
![Screenshot_20190807-110848_Firefox Nightly](https://user-images.githubusercontent.com/51314259/62606557-2ea43800-b905-11e9-986d-7e14f0860b43.jpg)
