### ISSUE TITLE
[Bug] (regression) Bookmark changes are not updated instantly

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#4026]
## Steps to reproduce
1. Edit a bookmark, change the name or URL.
2. Return to the bookmarks list.
3. Observe the bookmark name & url.
4. Tap the bookmark to open it.
5. Return to bookmarks and observe the edited bookmark.
### Expected behavior
Name & url are updated instantly.
The new URL should be loaded.
### Actual behavior
Bookmark not updating. The initial URL is loaded.
Returning to the bookmarks list, the bookmark will be updated.
*Or, after Step 3 go to a different folder and return, will show the updated bookmark.

*Not reproducing on 1.0.1 rc build.

### Device information

* Android device: HTC Desire 820 (Android 6.0.1), OnePlus 5T (Android 9.0)
* Fenix version: Nightly 190712

**Comment by softvision-miralobontiu** [comment]
Verified as fixed on the latest Nightly build 190809 (#12210609) with Samsung Galaxy Note 8 (Android 9), OnePlus 5T (Android 9), and Nexus 5 (Android 6.0.1).
