### ISSUE TITLE
Don't show download complete notification when saving images

### ISSUE THREAD

**Issue by cannotbeblank** [mozilla-mobile/fenix#4034]
### Why/User Benefit/User Problem
Please cancel the notification bar‘s notification after Android saves the image.
This is a very very useless feature.
User need to specifically cancel this notification.

### What/Requirements
cancel the notification
you can Change to notice that disappears after 3 seconds.
(just like twitter download image)

**Comment by realTomorrow** [comment]
I can't believe it's been so long and great you guys haven't fixed this problem.
It is a very ridiculous function.
User needs to manually cancel Download complete notification each time(twice ! notice in the top notification bar and close button at the bottom) .
Use toast function to notification user Download complete! Replace two existing notifications.
[https://imgur.com/a/P1JM9L2](url)

**Comment by cannotbeblank** [comment]
Great, he's changed it back!
I'm glad you guys fixed this problem in 4.0.0 version. 
However, in the latest version 5.2.0, you have added this problem again!
This is ridiculous!

**Why do I need to click the close button twice to download one file?**

User needs to manually cancel Download complete notification each time(twice ! notice in the top notification bar and close button at the bottom) .
Use **toast function** to notification user Download complete! Replace two existing notifications.

![o9T8nLg](https://user-images.githubusercontent.com/30313284/85804298-dc1d7580-b77b-11ea-880a-e7e1606117c6.jpg)

**Comment by AmyYLee** [comment]
Assigned to @brampitoyo for feedback

**Comment by cannotbeblank** [comment]
![Screenshot_20200704-000934_Twitter](https://user-images.githubusercontent.com/30313284/86486443-dfbd8780-bd8d-11ea-98e7-0f9779da7ed1.png)
Oh, my God, 
Cancel the existing two notifications, **use the same toast as Twitter.** 
Feels like you guys don't have a product manager/UI.

**Comment by cannotbeblank** [comment]
Oh, my God,
Cancel the existing two notifications, **use the same toast as Twitter.**
Feels like you guys don't have a product manager/UI...
![Screenshot_Twitter](https://user-images.githubusercontent.com/30313284/86486870-10ea8780-bd8f-11ea-84cf-38a0f6a2ea78.png)

**Comment by Dunexus** [comment]
The download completed notification in a browser is an important notification and should not be a simple toaster. Most of the time, you want to open the file you just downloaded.

Also, please stay professional, there is no need to be rude.

**Comment by brampitoyo** [comment]
Let’s say that, if you take an action on our notification in any way (either tap “x” or “Open” – doesn’t matter which button), we will also dismiss the Android System notification shade. Would that solve your problem? Actually, I wonder if we can do this in the first place? Asking Engineering for comment.

We can also make our “Download complete” dialog more minimal and take up a lot less space. This is the same design pattern that we use in our pop-up blocking dialog:

<img width="360" src="https://user-images.githubusercontent.com/51007/86879308-ed349200-c13e-11ea-838f-5b59a0231f0b.png">

Thoughts?

**Comment by Amejia481** [comment]
> Let’s say that, if you take an action on our notification in any way (either tap “x” or “Open” – doesn’t matter which button), we will also dismiss the Android System notification shade. Would that solve your problem? Actually, I wonder if we can do this in the first place? Asking Engineering for comment.
> 
> We can also make our “Download complete” dialog more minimal and take up a lot less space. This is the same design pattern that we use in our pop-up blocking dialog:
> 
> <img alt="" width="360" src="https://user-images.githubusercontent.com/51007/86879308-ed349200-c13e-11ea-838f-5b59a0231f0b.png">
> 
> Thoughts?

Right now we don't have APIs to support theses operations, it would require some engineering work to create it, as we will need to communicate between the app to ac and back and forth to indicate if dialog has been dismissed or if the system notification has been dismissed.

I'm curious about why other browsers like Chrome has the same behaviour, the system notification behaves completely independent from the app dialog, if one is dismissed the other stays. I guess system notification could be easily dismissed and you could lost track of the download.

**Comment by cannotbeblank** [comment]
All right, thank you.
But... maybe... there's no need for a notice on the notification bar‘s? (at ①).
Hope fenix beats chrome.
Should I close this question?

**Comment by Amejia481** [comment]
I think we can close this issue, please feel free to reopen if need it
