### ISSUE TITLE
[Bug] Homescreen RTL menus open from the opposite corner of the menu icon

### ISSUE THREAD

**Issue by ekager** [mozilla-mobile/fenix#4036]
## Steps to reproduce
1. Force phone to be RTL (In Developer Options) 
2. Click any 3 dot menu on homescreen

### Expected behavior
Menu opens from corner where 3 dot menu icon is

### Actual behavior
Menu opens from opposite corner

(Notably this doesn't happen with the 3 dot menu in the toolbar in BrowserFragment so the different animation must handle this correctly)

### Device information

* Android device: ?
* Fenix version: ?

**Comment by mcarare** [comment]
@ekager Is this still reproducible? I tried to replicate this on a Nokia 7 Plus (Android 9) and the menus open from the corner where 3 dot menu icon is

**Comment by ekager** [comment]
Yes I can still see this on my Pixel 3. 
![ezgif com-video-to-gif(1)](https://user-images.githubusercontent.com/25442310/65530442-d45b3880-deac-11e9-941a-5ba3dcb18552.gif)

**Comment by softvision-miralobontiu** [comment]
Verified as fixed on the 10/25 Nightly build (#12980628) with Google Pixel (Android Q), and Google Pixel 3 (Android 9).
