### ISSUE TITLE
Add device icons for upcoming TV and VR device types

### ISSUE THREAD

**Issue by grigoryk** [mozilla-mobile/fenix#4037]
We display a device type icon when sending tabs right now, but currently there are only two types - mobile and desktop. We will soon have TV and VR (Firefox Reality) targets as well, so let's add icons for those new types.

**Comment by lime124** [comment]
@vesta0 @grigoryk are these required for the feature to ship? if so, when do we need to provide these icons?

**Comment by vesta0** [comment]
@lime124 the TV and VR icons are not required to ship the feature but we should have them by end of Q3 in time for skyline.

**Comment by lime124** [comment]
removing the ux label - this is on our radar already as it's part of Q3 plans.

**Comment by eoger** [comment]
Blocked on https://github.com/mozilla-mobile/android-components/pull/4114 riding the a-c train.

**Comment by eoger** [comment]
It's available by the way :)

**Comment by lime124** [comment]
@vesta0 are both icons required for Q4?  We'll size once we know if it's both or not. Thanks!

**Comment by vesta0** [comment]
@lime124 they are both `coulds`. If I had to pick one as the first one to tackle, I'd pick TV.

**Comment by lime124** [comment]
i spoke with @mheubusch and this can be picked up by the new design systems team. she's tracking the work on the team's trello board. i'll keep the ticket in our ux backlog so we don't lose track of it and work with the designer when it comes up  for them.
