### ISSUE TITLE
[Bug] progress bar is weird 

### ISSUE THREAD

**Issue by ekager** [mozilla-mobile/fenix#4039]
![Screenshot_20190712-144546](https://user-images.githubusercontent.com/25442310/61160850-0d8f2980-a4b6-11e9-91cc-a22c72ddb81b.png)

## Steps to reproduce
Load page
### Expected behavior
Progress bar has correct gradient

### Actual behavior
Progress bar gradient is broken

### Device information

* Android device: ?
* Fenix version: ?

**Comment by AndiAJ** [comment]
Hi, verified as fixed on the latest Nightly Build #190724 from 24/7 using the following devices:
• Googe Pixel 3a (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• OnePlus 3 (Android 6.0.1)
• Sony Xperia Z3 (Android 5.1.1)

►Video from Googe Pixel 3a 
Dark mode
![20190724_122515](https://user-images.githubusercontent.com/51314259/61782330-86737700-ae0e-11e9-85fd-6a13590f1bd3.gif)

Light mode
![20190724_122209](https://user-images.githubusercontent.com/51314259/61782420-b0c53480-ae0e-11e9-8d20-40fad7146997.gif)
