### ISSUE TITLE
[Bug] confirm() dialog sometimes returns wrong value

### ISSUE THREAD

**Issue by ashkitten** [mozilla-mobile/fenix#4042]
the `confirm()` dialog returns the inverse value when not offering to prevent the page from creating additional dialogs

## Steps to reproduce

1. navigate to a [test page]. this specific url is simply some encoded html containing a button and a `<pre>` tag to display the result of `confirm()`.
2. click the button
3. press "ok" on the dialog that pops up
4. repeat step 2 so that the dialog offers to prevent the page from creating additional dialogs
5. press "ok" again

### Expected behavior

after both steps 3 and 5, the text below the button should display `true`

### Actual behavior

after step 3 the text below the button displays `false`, after step 5 the text displays `true`.

### Device information

* Android device: Google Pixel XL, LineageOS 16.0 (Android 9)
* Fenix version: Nightly 190712 (Build #11930610)

[test page]: https://itty.bitty.site/#/data:text/html;charset=utf-8;bxze64,XQAAAAJ2AAAAAAAAAAAeGIqndZhgklgNkDwBBiKiCaf6XrLlXC9HVP42z+O2n+8s7PgYC4QqbHCXdu1yg9tSFJSuWBxzs0G0WprY8Q3L+DbYGxGMbsgSf9BMeVwmLlYk66YvQQ9a6nWh7Tvk98kEDldw1haRLwQuDZ/+CznA

**Comment by Amejia481** [comment]
It looks like it's been fixed on GeckoView `69.0.20190711090037` and above as soon Fenix update its GV dependency this issue will be gone. Since [AC 4.0.0 ](https://mozac.org/changelog/#400) apps will not need to specify a GeckoView  dependency as it will be part of AC.

**Comment by ashkitten** [comment]
as of today's switch to geckeview beta, this appears to be fixed on the play store
