### ISSUE TITLE
Fill the search/address bar by tapping on a suggested search/address suggestion

### ISSUE THREAD

**Issue by marthinwurer** [mozilla-mobile/fenix#4051]
### Why/User Benefit/User Problem
If you're trying to type a longer search, and you see a suggestion that is part of what you want to search but does not contain all your search terms (for example, you want to search for "houses in city for sale with pools", you've typed "houses in city" and "houses in city for sale" is suggested), you currently have to type the rest of the search until your full search is selected. This can also be nice with websites. You want to go to "website.com/shop/", you've typed in "web", and "website.com" is suggested. In both of these, just selecting the suggestion will just bring you to the bare selection without the extra stuff that you wanted ("with pools" and "/shop/").

### What/Requirements
Add something that I can tap on for each suggestion that will fill the search bar with its value.

### Acceptance Criteria (how do I know when I’m done?)
I can activate a suggestion in some way that sets the search bar to its value.

A picture of how chrome does it is in #2675. They have a diagonal arrow icon on the right side that points up to the bar, and if you hit it the bar is filled with the suggested value.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-12573)

**Comment by secrethash** [comment]
A Top-right facing arrow for inclusion of suggested term in the search field.

Currently (From - Firefox Preview):
![](https://i.imgur.com/eUUzJHA.png)

Should be (From - Brave Browser):
![](https://i.imgur.com/KGrGBzU.png)


`Just for better reference.`

**Comment by nahuhh** [comment]
Top-left* (north-west)

**Comment by secrethash** [comment]
@nahuhh opps sorry 😅

**Comment by officiallor** [comment]
Im confused why this is not already implemented. It's a must feature IMO

**Comment by kbrosnan** [comment]
This feature is in Fenix.
