### ISSUE TITLE
[Bug] Dispatchers.Main still has long cold start delay (Phase II)

### ISSUE THREAD

**Issue by colintheshots** [mozilla-mobile/fenix#4064]
## Steps to reproduce
Look at the latest Nimbledroid.com report OR run cold startup with Systrace running.

### Expected behavior
We should not block the main thread for hundreds of milliseconds to checksum the jar using FastServiceLoader or ServiceLoader classes.

### Actual behavior
Even with the latest fixes from Kotlin Coroutines, Dispatchers.Main still blocks the main thread for too long. It takes 200ms to run FastServiceLoader, only a ~60ms improvement.

This bug is initially marked "waiting" because we're waiting on the Android team to fix it using R8. If we can use upgrade to the future stable 2.5.0 Android Gradle Plugin and a new version of Kotlin Coroutines which no longer uses FastServiceLoader, we can perform cold startup in a substantially shorter time. This is because R8 will optimize out all ServiceLoader calls and Kotlin Coroutines will switch back to the built-in ServiceLoader calls so they get optimized out.

### Device information

* Android device: Pixel 3XL
* Fenix version: 1.0.1

**Comment by colintheshots** [comment]
I'm calling this P2. It has a major effect on performance, but we're waiting on Google to release Android Gradle Plugin and JetBrains to release a new Kotlin coroutines version.

**Comment by colintheshots** [comment]
This should be fixed in the latest master using a Dev version of R8. The results should appear in Nimbledroid in the next day or so.

**Comment by sblatz** [comment]
@colintheshots can we close this or put a qa needed label on it? :)

**Comment by colintheshots** [comment]
We have good news here that confirms the performance gains right after the commit landed. I think we can close this safely.

![Screenshot from 2019-09-03 12-50-21](https://user-images.githubusercontent.com/626405/64448149-a307fd80-d0a2-11e9-8b12-19c49907418a.png)

**Comment by colintheshots** [comment]
I removed the pre-release R8 version and replaced this with an improved Kotlin coroutines library instead.
