### ISSUE TITLE
[Meta] Unconditional inflation of Find in Page, Reader View, and Quick Action Sheet

### ISSUE THREAD

**Issue by colintheshots** [mozilla-mobile/fenix#4066]
## Steps to reproduce
Start Systrace and launch Fenix from a link in an external app.

### Expected behavior
Fenix should not spend ~70-100ms on the main thread inflating views that are marked GONE visibility initially.

### Actual behavior
Fenix spends ~70-100ms on the main thread inflating views that are initially marked GONE.

This bug is initially marked Waiting, since Find in Page and ReaderView should likely use ViewStubs inside the Android Component to resolve this.

### Device information

* Android device: Pixel 3XL
* Fenix version: 1.0.1

**Comment by jonalmeida** [comment]
The views mentioned are in the `fragment_browser` layout file so I don't believe they need a-c work to add stubs.

**Comment by colintheshots** [comment]
I suppose we can implement it as is. I was thinking it would be great to support this in the Android Components, but I can understand not wanting to add code that might be considered application-specific.

**Comment by liuche** [comment]
Reader View will go to AC, Find in Page already has a PR, Quick action sheet needs to be broken out.

We'll add Find in Page and Quick Action to this upcoming sprint. @colintheshots will take on breaking those out.

**Comment by sblatz** [comment]
Closing this in favor of the child tickets 😄
