### ISSUE TITLE
[Performance] Unnecessarily deep layout hierarchy on several screens

### ISSUE THREAD

**Issue by colintheshots** [mozilla-mobile/fenix#4067]
**Affected UI elements**:
Quick Action Bar
Share Sheet
Custom Snackbar
Tabs Header
Tab in Collection

Excess layout layers are used on these screens that contribute nothing to the UI. This will slow down layout passes and finding Views on important screens of our app.
https://android-developers.googleblog.com/2017/08/understanding-performance-benefits-of.html 

* Fenix version: 1.0.1

**Comment by jonalmeida** [comment]
Performance bugs are probably not good for first time contributors since they are sometimes folks that are new to android as well. :)

**Comment by CloudyDino** [comment]
I'd love to work on this and give it a try!
