### ISSUE TITLE
Investigate & file issues if there is main thread IO on non-app startup

### ISSUE THREAD

**Issue by colintheshots** [mozilla-mobile/fenix#4068]
This bug is for non-startup main thread IO: startup is higher priority than this so it is a separate issue: https://github.com/mozilla-mobile/fenix/issues/6547

### What
Main thread IO is an avoidable source of poor user experience: we should prevent it from happening.

### Impact
Main thread IO should be prioritized because it's one of the highest value performance tasks.

### Acceptance criteria
- File an issue for each instance of avoidable non-startup main thread IO w/ a rough estimate of how long it takes

---

Colin provided the additional comment:

**Affected libraries or methods**:
ThemeManager window.decorView.setSystemUiVisibility
LifecycleRegistry.addObserver() ToolbarIntegration
GeckoRuntime.init() DebugConfig.fromFile()
AppLinksUseCases findActivities()
ReaderViewFeature getSharedPreferences()
ExceptionDomains.load() getSharedPreferences()
SessionManager AutoSave.periodicallyInForeground() AutoSave.whenGoingToBackground()
ExperimentsKt.isInExperiment() getSharedPreferences()
PairFragment requestPermissions()

The blocking calls can vary from ten milliseconds to hundreds of milliseconds.

This performance issue would have been obvious throughout development, except Strict Mode was not enabled in Fenix early on.

A few cases here may be tricky to background, such as reading the GeckoView config, but we should investigate and decide whether a fix is worthwhile. Some of these fixes may require Android Components changes.

* Fenix version: 1.0.1

**Comment by mcomella** [comment]
Triage: this is an important source of perf wins but we're primarily concerned for startup. We broke https://github.com/mozilla-mobile/fenix/issues/6547 into a separate issue to focus on that case.

**Comment by mcomella** [comment]
We can just enable StrictMode everywhere, which we're tracking on JIRA: https://jira.mozilla.com/browse/FXP-1242
