### ISSUE TITLE
Rotate videos to appropriate orientation on fullscreen

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#4078]
### Why/User Benefit/User Problem
I have my phone in "locked" orientation mode (a standard Android feature): whatever the current orientation, rotating the device will not rotate the screen. However, after rotating the device, I can click a button to rotate the screen.

This makes watching fullscreen videos in Fenix tedious: after fullscreening videos, I have to rotate my device, wait for the dynamic "rotate screen button to show up" (which is often hidden due to fullscreen), and click it. To exit fullscreen, I have to do the same thing.

Instead, I think we should do what the YouTube app does: when a landscape video is fullscreened, the content is automatically rotated (e.g. most often to landscape) to take maximum advantage of the screen size. When unfullscreened, the content is rotated back.

**Comment by buttercookie42** [comment]
Fennec already does that, too, doesn't it?

> I can click a button to rotate the screen.

And other phones don't have even that, so you have to completely unlock the rotation, which is even more tedious.

**Comment by ekager** [comment]
Related #1343

**Comment by ekager** [comment]
Working on this, so closing for #1343
