### ISSUE TITLE
Add playback rate setting to video player

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#4079]
### Why/User Benefit/User Problem
I often watch videos at increased playback rates (1.5x, 2x, etc.): it'd be great if the Fenix video player supported this feature.

fwiw, this feature is important enough to me that it discourages me from using my phone (unless it's the YouTube app) or Fire TV to watch videos, instead pushing my towards my computer, despite the increased discomfort and inconvenience.

### Acceptance Criteria (how do I know when I’m done?)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-12585)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1809993

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
