### ISSUE TITLE
Move PublicSuffixList to a sub-component class

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/fenix#4089]
PublicSuffixList isn't a top-level component class and is probably better fit for the `Utilities.kt` sub-component instead (or any other that might make more sense).

```kotlin
val publicSuffixList by lazy { PublicSuffixList(context) }
```

**Comment by chiragmantri** [comment]
Hi jonalmeida,
I would like to take this up.

**Comment by jonalmeida** [comment]
@chiragmantri Definitely, go ahead! 🙂

**Comment by chiragmantri** [comment]
@jonalmeida so shall I move the PublicsuffixList class to utilities.kt?

**Comment by jonalmeida** [comment]
Yes

**Comment by chiragmantri** [comment]
@jonalmeida Please review the PR. Also, are the Tests and Android Tests have some test failures? or am I missing any configuration?
