### ISSUE TITLE
[Bug] IllegalStateException crashes during searches with new SearchStore

### ISSUE THREAD

**Issue by colintheshots** [mozilla-mobile/fenix#4096]
## Steps to reproduce
There aren't yet known steps to reproduce. The observer somehow lives too long until the context is invalid.

### Expected behavior
The app should not crash when updating search icons and other UI after the context is no longer valid.

### Actual behavior
The app crashes in various cases, such as when updating search icons and other UI, after the context is no longer valid.

This seems to be due to an observer that sticks around too long. `StoreExtensions.kt Store.observe()` says, "Once the View gets detached the Observer will be unregistered automatically." It seems there must be a case where the context goes away before the observer does.

https://sentry.prod.mozaws.net/operations/fenix-nightly/issues/6045620/?query=is:unresolved

### Device information

* Android device: Pixel 3
* Fenix version: Nightly 7/16/2019 6:02

**Comment by colintheshots** [comment]
BTW, if anyone needs steps to reproduce, virtually every pre-launch report is crashing with this stack trace using SearchFragment or one of the other fragment instances where context is needed, but gone. Using RoboTest seems to catch this bug repeatedly. This report had it occur three times:
https://play.google.com/apps/publish?account=7083182635971239206#PreLaunchReportPlace:p=org.mozilla.fenix&plrvc=11980614

**Comment by pocmo** [comment]
Sentry issue: [FENIX-NIGHTLY-8N](https://sentry.prod.mozaws.net/operations/fenix-nightly/issues/6045620/)

**Comment by liuche** [comment]
AC team working on a fix right now, and we have a PR.
