### ISSUE TITLE
[Bug] Update Fenix to Leanplum SDK 5.2.3

### ISSUE THREAD

**Issue by cpeterso** [mozilla-mobile/fenix#4102]
We should update Fenix to [Leanplum SDK 5.2.3](https://github.com/Leanplum/Leanplum-Android-SDK/releases/tag/5.2.3) or later. That SDK is supposed to fix a Leanplum issue that broke Leanplum notification's app deep links into Fennec. I don't know if Fenix is affected, but we should probably keep update to date.

Fenix is currently using Leanplum SDK 4.3.1 (from Fenix #891), though the latest SDKs I see in Leanplum's GitHub repository are 4.2.7 and 5.2.3. I don't see any 4.3.1.

https://github.com/Leanplum/Leanplum-Android-SDK/releases

More details about Fennec's Leanplum issue:

https://docs.google.com/document/d/1XLaUYBQxEBPsSZt3WBtSYY488evMg5h_hZC0rqzKhkw/edit

**Comment by ekager** [comment]
I'm not sure there's much risk here in updating (Version will be in `Dependencies.kt`). I've added the good first issue so a contributor can pick this up but if it needed immediate attention let me know

**Comment by mythio** [comment]
@ekager I have created a PR adressing this issue. Please review
