### ISSUE TITLE
Proxy Support

### ISSUE THREAD

**Issue by st3fan** [mozilla-mobile/fenix#4105]
It would be great if Firefox Preview had the same proxy settings as Firefox Desktop, including Socks support.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-12597)

**Comment by plwt** [comment]
User feedback:  https://support.mozilla.org/en-US/questions/1393317

**Comment by kbrosnan** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812896

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
