### ISSUE TITLE
Browser.EXTRA_APPLICATION_ID/EXTRA_CREATE_NEW_TAB support

### ISSUE THREAD

**Issue by buttercookie42** [mozilla-mobile/fenix#4106]
Apps wanting to open an URL in the browser can pass along a [`Browser.EXTRA_APPLICATION_ID` Intent extra](https://developer.android.com/reference/android/provider/Browser#EXTRA_APPLICATION_ID), meaning they'd like to re-use an already existing tab with the same ID if it already exists instead of opening a new tab.

They can also override that behaviour by also passing along `Browser.EXTRA_CREATE_NEW_TAB`, which means they'd like to use a fresh tab regardless of whether another tab matching the `EXTRA_APPLICATION_ID` supplied already exists or not.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-12598)

**Comment by buttercookie42** [comment]
One additional thing not to forget from the Fennec implementation:
Whenever the user opens some other URL in a tab through the browser UI, we clear any possibly stored `EXTRA_APPLICATION_ID` for that tab, so it can no longer be re-used (thereby overwriting the user's new URL) if another Intent containing an `EXTRA_APPLICATION_ID` arrives.
What's debatable (and I don't think Fennec does this right now) is whether the same thing might be worth doing if the user navigates by doing something *inside* the GeckoView, i.e. clicking a link or whatever we can detect as a user-triggered navigation.

**Comment by buttercookie42** [comment]
Requested in https://bugzilla.mozilla.org/show_bug.cgi?id=1620957.

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1809994

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
