### ISSUE TITLE
Modify the Status Bar color to match Fenix color while being in Private Mode

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/fenix#4107]
### Why/User Benefit/User Problem
Modifying the color of Status Bar in private mode will create a feeling of a full screen app while browsing. 
### What/Requirements
Modify the color for Status Bar.
### Acceptance Criteria (how do I know when I’m done?)
The Status Bar color matches the Fenix color in private mode.
### Notes
This change will make a difference for the newest devices with a small Notch.
Also, note that in normal browsing mode, it looks very good as everything is in the same color.
I will add 2 photos(not screenshots) to see the difference. 
Device: Samsung Galaxy S10+
![20190717_114418](https://user-images.githubusercontent.com/42831109/61361278-df7c6180-a888-11e9-9a55-729f7cf26c96.jpg)

**Comment by lime124** [comment]
@AmyYLee is this something we want to do? do we need to provide a color?

**Comment by boek** [comment]
I think we can make the status bar transparent? Notches are becoming quite popular so we should probably make sure it looks good 👍

**Comment by AmyYLee** [comment]
> @AmyYLee is this something we want to do? do we need to provide a color?
> 
> removing feature label - this is a small thing if we want to do it.

This sounds good to me. As @boek said, we can make it transparent so no new colour needs to be privided.

**Comment by lime124** [comment]
@abodea ^

**Comment by abodea** [comment]
I believe this is the best option. Even on Google Play the transparent Status Bar is used for phones with Notches.

**Comment by mythio** [comment]
I want to work this out, can I create a PR?

**Comment by NotWoods** [comment]
Go for it @mythio!

**Comment by abodea** [comment]
Hi, I want to add a quick update about this issue:
Can we make the navigation bar to be transparent too or to match this #1750
The browsing toolbar gradient was updated too and with the current colors on the side it's not looking very good.
![Screenshot_20190731-124752_Firefox Nightly (1)](https://user-images.githubusercontent.com/42831109/62202318-c0ee8e00-b391-11e9-8339-968a2f5e381e.jpg)
![Screenshot_20190731-125101_Firefox Nightly](https://user-images.githubusercontent.com/42831109/62202443-fabf9480-b391-11e9-899f-9cfa611abe97.jpg)

**Comment by lime124** [comment]
@abodea can you do me a huge favor and create a new issue for that request. let's keep this one just scoped to the status bar. thanks so much!

**Comment by mythio** [comment]
@NotWoods I am facing a problem. When I set the `android:statusBarColor` to `@android:color/transparent`, the status bar doesn't become translucent but if I change it to any other color, it works. Can you provide me any leads?

**Comment by NotWoods** [comment]
Try `<item name="android:windowTranslucentStatus">true</item>` along with `fitsSystemWindows`

**Comment by hakkikaancaliskan** [comment]
@NotWoods 
I've added windowTranslucentStatus and windowTranslucentNavigation to PrivateThemeBase, set statusBarColor and navigationBarColor to transparent and added fitsSystemWindows to activity_home.xml's LinearLayout but not working.

![Screenshot_20190807-120704](https://user-images.githubusercontent.com/17825767/62610319-226fa900-b90c-11e9-9779-1ef04809408c.png)

**Comment by abodea** [comment]
Hi @lime124 I added this #4682. Sorry for the delay.

**Comment by Charis1331** [comment]
HI, since this hasn't been solved yet, can I give it a shot?

**Comment by mcarare** [comment]
@AmyYLee do we also want to make navigation bar transparent, like in the sample below?
<img src =https://user-images.githubusercontent.com/48995920/65056726-11d63800-d97a-11e9-822f-3d05254adeb9.png width =50%>

**Comment by AmyYLee** [comment]
> @AmyYLee do we also want to make navigation bar transparent, like in the sample below?
> <img alt="" width="50%" src="https://user-images.githubusercontent.com/48995920/65056726-11d63800-d97a-11e9-822f-3d05254adeb9.png">

@mcarare  This looks good to me. Thanks!

**Comment by mcarare** [comment]
@AmyYLee Sorry, I realised the position of the _bottom bar_ has changed in meantime. The options would be:
- 1: transparent navigation bar
- 2: solid transparent bar
- 3:transparent bar + transparent bottom bar
<img src =https://user-images.githubusercontent.com/48995920/67205023-7ff99900-f417-11e9-8bca-3150d2c27405.png width = 30%>  <img src =https://user-images.githubusercontent.com/48995920/67205042-8720a700-f417-11e9-85f6-3f8d5ffe7c0d.png width = 30%> <img src =https://user-images.githubusercontent.com/48995920/67205371-45dcc700-f418-11e9-9152-922ac5b20a42.png width = 30%>

 Which one should we go with?

**Comment by NotWoods** [comment]
There's also the option to have the navigation bar match the gradient of the toolbar in case 1

**Comment by AmyYLee** [comment]
@mcarare Can we have the bottom bar adapt the gradient of the search bar like this?
![Screen Shot 2019-10-21 at 2 02 42 PM](https://user-images.githubusercontent.com/5992746/67230860-1d4ed000-f40c-11e9-9264-f5c1b0b2dc8e.png)

**Comment by mcarare** [comment]
![try](https://user-images.githubusercontent.com/48995920/67281731-c4993900-f4d8-11e9-8646-3cbdd2ea7e18.png)

@AmyYLee This is as close I can get, without tweaking the assets. I think it looks good, cause the gradient is continuous from bottom left corner (including the nav bar whereas in 3 the nav bar in transparent)
If you want to make an exact replica of your suggestion I can try to modify the assets. TY!

**Comment by AmyYLee** [comment]
> ![try](https://user-images.githubusercontent.com/48995920/67281731-c4993900-f4d8-11e9-8646-3cbdd2ea7e18.png)
> 
> @AmyYLee This is as close I can get, without tweaking the assets. I think it looks good, cause the gradient is continuous from bottom left corner (including the nav bar whereas in 3 the nav bar in transparent)
> If you want to make an exact replica of your suggestion I can try to modify the assets. TY!

@mcarare  This looks good to me. Thanks!

**Comment by Baron-Severin** [comment]
Hey @mcarare, is there still additional work on this one (and if so, would you mind assigning yourself?)?  I don't see a PR attached, but it looks like you've already fixed the problem based on the comments above.

**Comment by mcarare** [comment]
@Baron-Severin I still have to work out some issues when you navigate away from the screen.

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest Nightly Build #13440604 from 12/10 using the following devices:
• Samsung Galaxy S10 + (Android 9)
• Google Pixel 3a XL (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)

Comparison: **Fenix Nightly 12/10** VS **RC 2.3.0 10/30** from a Samsung Galaxy S10 +
![rsz_screenshot_20191210-101810_firefox_nightly](https://user-images.githubusercontent.com/51314259/70509423-9f6b9300-1b37-11ea-8c79-f495036b58be.jpg)

**Comment by boek** [comment]
@AndiAJ Does this break things in Android 5?

Getting some weird behavior on a simulator
<img width="647" alt="image" src="https://user-images.githubusercontent.com/1250545/70673494-a2e64380-1c37-11ea-8d94-1209025b6e61.png">

**Comment by boek** [comment]
cc: @mcarare

**Comment by mcarare** [comment]
@boek I think this does not happen with real devices. Emulators have a default skin and to not have Window Insets.

**Comment by AndiAJ** [comment]
Hi @boek , I wasn't able to reproduce this on on the latest Nightly Build #13460608 from 12/12 using the following devices:
• Motorola G4 (Android 6.0.1)
• OnePlusA3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)
• Asus Nexus 7 (Android 5.1.1)

The only issues regarding the overlapping matter that I'm aware off are  #7062 & #7111

**Comment by abodea** [comment]
Re-opening this issue based on the https://github.com/mozilla-mobile/fenix/pull/7152 PR.
Home screen full screen was reverted, I consider we should keep this open and re-verify it when the full screen will be added back.

**Comment by Mugurell** [comment]
I think this can be closed now, right @abodea ?

**Comment by abodea** [comment]
> I think this can be closed now, right @abodea ?

Agreed sorry for the late response, closing accordingly.
