### ISSUE TITLE
[Bug] There is a residual texture displayed on the top-left corner when tapping on Tracking Protection icon

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/fenix#4111]
## Steps to reproduce
1. Launch Fenix.
2. Reach any website.
3. Turn the device in landscape mode.
4. Tap on the Tracking Protection button.
### Expected behavior
The Tracking Protection pop-up animation is displayed correctly.
### Actual behavior
There is a residual texture displayed right when the Tracking Protection pop-up animation loads in the top-left corner.
### Device information

* Android device: **`Samsung Galaxy S10+(Android 9).`**
* Fenix version: **`Latest Nightly 7/17`**

[Video](https://drive.google.com/file/d/1C3swIeNYJ1UmDX5dG6x6kbR7rRo7v8Q6/view?usp=sharing)

**Comment by ekager** [comment]
Are you seeing this on every device? I am not seeing on my pixel on latest master

**Comment by abodea** [comment]
I rechecked the issue on the following devices but I couldn't reproduce it:
- Googe Pixel 3a (Android 9)
- Huawei Mate 20 Lite (Android 8.1.0)
- Samsung Galaxy S7 (Android 7)
- OnePlus 3 (Android 6.0.1)
- Sony Xperia Z3 (Android 5.1.1)
- Samsung Galaxy Tab A(Android 9)

The only device I can reproduce it, is Samsung Galaxy S10+ being with 6.4 inch screen.

**Comment by boek** [comment]
It looks like the shroud has a cutout for the display shape. Weird
