### ISSUE TITLE
[Bug] window.open and target=_blank seem to be broken

### ISSUE THREAD

**Issue by smaug----** [mozilla-mobile/fenix#4113]
## Steps to reproduce
Load http://mozilla.pettay.fi/moztests/new_win.html
Click either the button or the link. Both them should open a new tab and they
do in Fennec and mobile Chrome, and on desktop browser, but they don't on Fenix - 
the tab counter doesn't increase.

### Expected behavior
new tabs should be opened

### Actual behavior
The current page is just replaced? That is at least what the UI hints.

### Device information

* Android device: 6
* Fenix version: 190705 18:03

**Comment by cadeyrn** [comment]
Sounds like #3702 for window.open and #1486 for target=_blank.
