### ISSUE TITLE
[Bug] Text selection handler doesn't keep it's position in the search box

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#4115]
## Steps to reproduce
1. Navigate to merriam-webster.com
2. Tap on the upper right Search icon
3. Long tap on the text box (until the text selection handler shows up)
4. Swipe up 

### Expected behavior
The handler remains in the search text box when swiping up and down

### Actual behavior
The handler moves along with the swiping action, doesn't stay in the search box

### Device information

* Android device: 
Google Pixel 3a (Android 9)
Samsung Galaxy S8+ (Android 8)
Samsung Galaxy S7 (Android 7)

* Fenix version: Nightly build #11980613 from 17/7

#### Notes
[►Video Samsung Galaxy S8+](https://drive.google.com/open?id=1fEia4JpLXf5fu2AedaS4iZJZ3RIUsu4e)

**Comment by ekager** [comment]
Cannot reproduce on Chrome. Cannot reproduce on Firefox Desktop. Filed https://bugzilla.mozilla.org/show_bug.cgi?id=1571887

**Comment by ekager** [comment]
Filed https://bugzilla.mozilla.org/show_bug.cgi?id=1571890
Cannot reproduce on Chrome. Can reproduce on Fennec
