### ISSUE TITLE
[Bug] Video progress gets reset after 10 seconds of playback

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#4116]
## Steps to reproduce
1. Navigate to https://m.cricbuzz.com/cricket-videos/40839/cricbuzz-live-the-final-new-zealand-v-england-post-match-show
2. Play the video

### Expected behavior
The whole video content can be viewed

### Actual behavior
Video plays for approx.10 seconds and afterwards the progress gets reset

### Device information

* Android device: 
• Google Pixel 3a (Android 9)
• Samsung Galaxy S8+ (Android 8)
• Samsung Galaxy S7 (Android 7)
* Fenix version: Nightly Build #11980613

**Comment by ekager** [comment]
Cannot reproduce on Chrome. Cannot reproduce on Firefox Desktop. Filed https://bugzilla.mozilla.org/show_bug.cgi?id=1571887

**Comment by cpeterso** [comment]
This is probably a webcompat bug, so the Webcompat team is reaching out to the website:
https://bugzilla.mozilla.org/show_bug.cgi?id=1575184
https://webcompat.com/issues/38113

**Comment by boek** [comment]
Tracking progress: https://bugzilla.mozilla.org/show_bug.cgi?id=1566572

**Comment by cpeterso** [comment]
This looks like a webcompat bug, not a GV bug. The WebCompat team is reaching out to the site developer here: https://github.com/webcompat/web-bugs/issues/38113#issuecomment-524676349
