### ISSUE TITLE
Close tabs automatically after a certain amount of time passed

### ISSUE THREAD

**Issue by ekager** [mozilla-mobile/fenix#4118]
UX specs: https://share.goabstract.com/379f7d73-3332-4949-b104-12ef523c5127?mode=design&sha=168d3adc4b4cebd5f58bcebf1e564f589a5b874a

Banner copy:
> Set open tabs to close automatically that haven’t been viewed in the past day, week, or month. 
> DISMISS  |  VIEW OPTIONS

### Why/User Benefit/User Problem
On mobile tabs can stack up and make it hard to find what you're looking for.

### What/Requirements
Something like this that would allow users to define the amount of time before auto closing their tabs. From a recent Safari mobile version.
![Image from iOS (1)](https://user-images.githubusercontent.com/25442310/61393658-4d6b5d80-a876-11e9-9d0f-3a33cf522312.jpg)

- [ ] AC work to allow us to have a "last opened" value for tabs
- [ ] Fenix work to build up a Setting 
- [ ] Fenix work to add this Setting to an onboarding card
- [ ] AC/Fenix work to auto close tabs after user defined amount of time (or never)

### Acceptance Criteria (how do I know when I’m done?)
Users can define how much time should pass before tabs autoclose (or never). Users should be able to change this Setting at any time. Tabs should autoclose once they have expired by the users' definition. We may want to also look into adding #2486 if we work on this feature so users can find tabs that may have closed recently that they still want easily.

**Comment by SS1113** [comment]
I keep all my tabs open until I'm finished with them. So please **do not** implement such a feature! Why would anyone want to close their without being done with them. After they have done all their work with the specified tabs they'll close them manually. I'm unable imagine a use case where this feature would be useful.

**Comment by ekager** [comment]
It would be an optional setting for users who want an easy way to manage their list of tabs.

**Comment by SS1113** [comment]
This isn't going to be the default settings, right? 

If it is optional then it's great as It'll provide some customisation with the tab management. But the default behaviour should be to not close the open tabs.

**Comment by fschneidereit** [comment]
By the way, what happened to the option to close all tabs when I close the app? I think this should be part of this features as well.

**Comment by AndiAJ** [comment]
Hi @ekager , I've just checked this feature on both **`Nightly 200902`** and **`Beta 81.1.0-beta.1`** using the following devices:
• Google Pixel 3a (Android 10)
• OnePlus A3 (Android 6.0.1)

✔️ The Tabs are properly being deleted as per the option the user is selecting 
❓ The CFR isn't displayed (after you **open more than 6 tabs** or after **deleting in a row 6 or more tabs** )

Could you please review and advise? ☺️ 
I'll remove the QA needed label until further notice

**Comment by ekager** [comment]
Thanks for testing and sorry for any confusion! 
The CFR/banner is pulled out into https://github.com/mozilla-mobile/fenix/issues/14243 and is not a requirement
