### ISSUE TITLE
Add Telemetry to uses of Quick Action Bar App Links.

### ISSUE THREAD

**Issue by jhugman** [mozilla-mobile/fenix#4123]
As followup to #4101, we should add telemetry to when the user taps on the quick action bar for opening in an external app.

**Comment by sblatz** [comment]
@vesta0 to add telemetry request document :)

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **Nightly Build #12240720 from 12/8** using a Google Pixel 3a (Android 9).

✅ Youtube - Ping **5300ad6b-e6b2-4f74-9638-9a0d73832005**
✅ OLX - Ping **90ebc473-b06b-4f79-bbe6-c134e8ad316e**
✅ Pinterest - Ping **97329192-381d-4f69-b0ed-8ab71893308d**

[Logcat](https://github.com/mozilla-mobile/fenix/files/3492910/QABAppGG.txt)
[Glean Dashboard](https://debug-ping-preview.firebaseapp.com/pings/aj-120802)
