### ISSUE TITLE
Migrate BrowserToolbar to LibState

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#4124]
## User Story
As a developer I'd like Browser Toolbar to implement LibState.

See Search component #3985 for guidelines, or reach out to Christian, Sebastian, Jeff.

## Dependencies
None

### Acceptance Criteria
* BrowserToolbar implements LibState
* BrowserToolbar has tests

**Comment by boek** [comment]
For QA: We refactored the browser toolbar (URL input / menu). Could we just get a verification that we didn't cause any regressions? :+1:

**Comment by abodea** [comment]
Verified as fixed in **`1.2.0-rc.1 (Build #12130445)📦: 6.0.2🦎: 69.0-20190729080047`** using **`Google Pixel 3a XL(Android 9) and Samsung Galaxy Tab A(Android 9).`**
Note that I couldn't find any regression after this change.
