### ISSUE TITLE
Migrate Sign in to Sync to LibState

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#4125]
## User Story
As a developer I'd like Sign in to Sync to implement LibState.

See Search component #3985 for guidelines, or reach out to Christian, Sebastian, Jeff.

## Dependencies
None

### Acceptance Criteria
* Sign in to Sync implements LibState
* Sign in to Sync has tests

**Comment by sblatz** [comment]
This could potentially be a great ticket for @jyeontaek to look at if he's wanting to learn more about our new architecture :)

**Comment by boek** [comment]
@jyeontaek I can pair with you on it if you'd like :)

**Comment by sblatz** [comment]
This actually does not need a migration since it does not have a corresponding component and uiview file.

**Comment by jyeontaek** [comment]
Reopened, we decided it needs migration after all.

**Comment by boek** [comment]
For QA: We refactored the sync/account settings UI. Could we get a smoke test to verify we didn't introduce any regressions?

**Comment by sv-ohorvath** [comment]
No regressions found on RC 1.2-rc1 & rc2. Closing.

**Comment by jyeontaek** [comment]
> For QA: We refactored the sync/account settings UI. Could we get a smoke test to verify we didn't introduce any regressions?

Can we get a check for this again?

**Comment by sv-ohorvath** [comment]
Done some regression testing on the Sign-in UI and haven't found any new issues.
Nightly build: 190812
Devices: Pixel 3 (Android 9), Mi 4i (Android 5)
