### ISSUE TITLE
Migrate Bookmarks to LibState

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#4128]
## User Story
As a developer I'd like Bookmarks to implement LibState.

See Search component #3985 for guidelines, or reach out to Christian, Sebastian, Jeff.

## Dependencies
None

### Acceptance Criteria
* Bookmarks implements LibState
* Bookmarks has tests

**Comment by sv-ohorvath** [comment]
@colintheshots Could you please give us more details on what this is about?

**Comment by sblatz** [comment]
This ticket can't be QA verified since it's a code health ticket. I'm going to close as it's been finished.

**Comment by boek** [comment]
@sblatz It's a code health ticket, but feature code has been touched. We should definitely do a small smoke test with bookmarks to make sure we didn't cause any regressions :)

**Comment by sv-ohorvath** [comment]
No new bookmarks issues found on rc 1.2-rc2. Closing this issue.
