### ISSUE TITLE
[Bug] Unable to copy the current link anymore in an easy way

### ISSUE THREAD

**Issue by andreicristianpetcu** [mozilla-mobile/fenix#4133]
## Steps to reproduce
Open a new tab with some address from the browsing history or bookmark.
Try to share it with a friend on a social network in another Fenix tab.
### Expected behavior
Long press or menu or whatever to get the current link.
### Actual behavior
I need to click the address bar, click it then long press once it moves to the top of the screen and then copy.

**Comment by andreicristianpetcu** [comment]
A bit of context when this regression was added https://github.com/mozilla-mobile/fenix/issues/3615

**Comment by Dunexus** [comment]
https://github.com/mozilla-mobile/fenix/issues/4155 now covers this issue if i get it well.

**Comment by andreicristianpetcu** [comment]
@Dunexus then I will close this one and track the other
