### ISSUE TITLE
[Bug] If you have a ton of history/bookmarks - history/bookmarks crashes or times out when loading

### ISSUE THREAD

**Issue by ekager** [mozilla-mobile/fenix#4137]
## Steps to reproduce
Have a ton of history (I synced) and open History in Fenix

### Expected behavior
History loads in chunks, doesn't freeze

### Actual behavior
Fenix freezes and sometimes crashes

### Device information

* Android device: ?
* Fenix version: ?

**Comment by softvision-miralobontiu** [comment]
I was able to reproduce this freeze / ANR with the latest build of Nightly 7/26, with Huawei P9 Lite (Android 6).

STR:
1. Sign in with your account on desktop and mobile. 
2. Sync.
3. Open some tabs and go to Library - History. 

For a second or two History was blank and the app froze.

**Comment by softvision-miralobontiu** [comment]
Verified with the latest build of RC 1.2.0-rc.2 with Huawei P9 Lite (Android 6), and Motorola Moto G6 (Android 8). The app didn't freeze or crash.

**Comment by NotWoods** [comment]
This is still an issue for Bookmarks. Should we re-open this issue?

**Comment by kbrosnan** [comment]
Lets open a new issue for bookmarks and edit this one to be clear it is about history.
