### ISSUE TITLE
On tablet desktop mode should be permanently 

### ISSUE THREAD

**Issue by Chris01277** [mozilla-mobile/fenix#4140]
When using Fenix ​​on a tablet, it should be possible to set the desktop mode permanently. Requests of mobile sites should also be switched to desktop sites.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-12620)

**Comment by bergie** [comment]
This is also closely related to #3107. Ideally desktop (DeX etc) and tablet can be fixed the same way

**Comment by OllyHodgson** [comment]
This sounds very similar to how Safari works on iPad in the current version of iPadOS. Apple's description from https://www.apple.com/ca/safari/ says:

> **Desktop-class browsing on iPad.** Safari now shows you a website’s desktop version that’s scaled for the large iPad display and automatically optimized for touch input.

**Comment by gbil** [comment]
chrome stable on android supports this now via a flag:
chrome://flags/#request-desktop-site-for-tablets

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807151

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
