### ISSUE TITLE
[Bug]Entering full screen mode snackbar isn't displayed

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#4145]
### Prerequisites
Have a clean profile

## Steps to reproduce
1. Navigate to youtube.com
2. Play a video in full screen mode
3. Navigate to vimeo.com
4. Play a video in full screen mode
5.  Navigate to imdb.com
6. Play a video in full screen mode

### Expected behavior
"Entering full screen mode" snackbar is displayed each time playing a video in full screen. 

### Actual behavior
The snackbar isn't displayed.

### Device information

* Android device: 
• Googe Pixel 3a (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• OnePlus 3 (Android 6.0.1)
• Sony Xperia Z3 (Android 5.1.1)  

* Fenix version: Nightly Build #11990109 from 18/7

### Notes
[►Video Huawei Mate 20 Lite ](https://drive.google.com/file/d/10UekYAPMStflUQoTSkbqHB1pyHn2Myfk/view?usp=sharing)

**Comment by Dunexus** [comment]
Can't reproduce on build #11990608 (OnePlus 5t Android 9)

![Screenshot_20190718-201848](https://user-images.githubusercontent.com/13906248/61482148-39b91780-a99a-11e9-9a07-d0bf5f833547.jpg)

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **Nightly Build #190724** using the following devices:
• Googe Pixel 3a (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• OnePlus 3 (Android 6.0.1)
• Sony Xperia Z3 (Android 5.1.1)
