### ISSUE TITLE
[Bug] CSS styles are slow to load on 90min.com

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#4154]
## Steps to reproduce
1. Navigate to 90min.com

### Expected behavior
Flawless load

### Actual behavior
Hyperlinks from the menu buttons show up before properly loading the webpage

### Device information

* Android device: 
• Googe Pixel 3a (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• OnePlus 3 (Android 6.0.1)
• Sony Xperia Z3 (Android 5.1.1)  

* Fenix version: Nightly Build #11990109 from 18/7

### Notes 

<details>
    <summary>Video Firefox Preview VS Chrome</summary>

►Firefox Preview
![20190718_173624](https://user-images.githubusercontent.com/51314259/61468689-7d098b00-a986-11e9-9462-d3782a0c563d.gif)

►Chrome 
![20190718_173727](https://user-images.githubusercontent.com/51314259/61468748-a75b4880-a986-11e9-8207-7cf62fcdc908.gif)

</details>

**Comment by boek** [comment]
Works for me! Please re-test @AndiAJ

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly Build 200519 from 5/19`** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)

► Video
![20200519-094845](https://user-images.githubusercontent.com/51314259/82294192-6c66de80-99b6-11ea-93e1-8f9fdb8fbb5c.gif)
