### ISSUE TITLE
Quick actions when long-pressing on the nav bar

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/fenix#4155]
### Why/User Benefit/User Problem

As a user, I want a quick and easy way to copy or paste into the nav bar, so I can perform my tasks quicker.

### What/Requirements

In Fennec, long pressing on the nav bar brings up a context menu with following options (Paste & Go, Paste, Copy address, Add page shortcut). UX will investigate and design how to bring this feature to Fenix. 

### Acceptance Criteria (how do I know when I’m done?)
-I can quickly choose to copy the URL by long pressing on the URL bar
-I can quickly choose to paste a URL into the nav bar
-Long pressing on the URL bar will not automatically copy the URL or paste anything into the nav bar.

### Note
This is an experiment we'd like to run, but UX work should be timeboxed to ____, and then make a decision whether to continue.

---------

### UX spec

- Long press on URL bar shows context menu with "Copy", "Paste & Go" and "Paste" as entries. 
- When nothing is in the clipboard we still show the "Copy" menu item and people have to select it.
- When people select "Paste", clipboard is pasted in and search view with keyboard appears.

**Comment by liuche** [comment]
Talked about this issue - it's a Should, so if it's not too much work it'll be a nice benefit and UX should pick it up and timebox, but should be skipped if we're behind on UX work.

**Comment by Djfe** [comment]
I want "tap+hold -> copy to clipboard" back, atleast as an option, it was amazing! <3
it's way faster (one click instead of two)

I get that this can override users' clipboards, so it's good you're searching for an alternative.

my keyboard swiftkey has a clipboard history. therefore I can't accidentally loose my clipboard's content.

paste and paste & go can be placed in the menu that appears if you click the addressbar once.

if you ever add an option "add to home screen", then it doesn't need to be on tap&hold imo. there are more intuitive places for it. one example: the menu that appears when you click the lock/globe icon in the addressbar

**Comment by topotropic** [comment]
I'd suggest to show a standard context menu with: Cut, Copy, Paste and Share

We wouldn't support "Paste & Go" and "Add page shortcut" in this iteration. @vesta0 thoughts?

**Comment by vesta0** [comment]
@topotropic I am good with your suggestion but is there a reason why we don't want to support "Paste & Go" ?

**Comment by colintheshots** [comment]
@topotropic What would Cut do here? We're on the browser screen at this point. Would it first open the search page and then cut the entire URL to the copy buffer? It doesn't seem to make sense to Cut unless the user is on a screen where the URL is editable.

Likewise, Paste would seem to require changing to the search screen if it doesn't mean Paste & Go.

**Comment by flaki** [comment]
My feedback will echo that of @Djfe — the moment I installed Preview and realized it did the automatic copy on longpress I was startled a bit (I was used to a context menu popping up) but I almost instantly fell in love with the simplicity and usefullness of it. During my day-to-day workflow I want copy URLs _way_ more often than I want to paste-and-go to an URL. I understand this might not match _everyone_'s experience on the planet, but if I could choose I'd keep this in the settings as an option ( _"Enable quick URL copy"_ or something along those lines).

As for exposing "Paste & Go" I'd think exposing it as a contextual option after tapping into the URL bar would be a similarly workable solution (some other browsers show a "go to _[url]_ on clipboard" option underneath the URL editor bar, on top of the suggestions).

**Comment by andreicristianpetcu** [comment]
[On Firefox Preview, while browsing, long pressing the url bar doesn't auto-copy the url anymore](https://www.reddit.com/r/firefox/comments/cpev98/on_firefox_preview_while_browsing_long_pressing/)

**Comment by topotropic** [comment]
@colintheshots yeah, that makes sense, I kind of saw it as shortcut to the context menu that appears on the search screen. I'll look into it. 

@vesta0 can you point me to the feedback we got about long press to copy? thanks!

**Comment by topotropic** [comment]
@vesta0 I'd suggest to have "Copy" and "Paste & Go" assuming that people go to search view when they just want to paste, cut or edit an URL

**Comment by vesta0** [comment]
@topotropic I like your suggestion but I think we may also want to include just "Paste" to give users the option of modifying a URL or search term. What do you think?

Also here's the relevant [UR feedback](https://docs.google.com/document/d/1rFRqlHgDLztMvBBBpCQFSFsdkN7Zm2tC4GE4xi1m6-M/edit#) and the [UX decision](https://docs.google.com/document/d/1x0_t8kkg6q_pFfz6LfyrjY2h2nKM3RSnGPexdXwYOxo/edit#heading=h.3jjtrx4bpjfp
)

**Comment by topotropic** [comment]
I don't have a strong opinion here, my main concern about "Paste" is that we go to the search screen and the search box jumps to top and keyboard pops out. 

But let's add it, people might wonder how to get to "Paste" when "Paste & go" is in the menu. I'll update the root issue above with the spec.

**Comment by vesta0** [comment]
Sounds good @topotropic thank you!

**Comment by liuche** [comment]
@topotropic will add designs before Sprint Planning on Friday, and then we will add it in.

**Comment by sblatz** [comment]
I want to confirm this is the expected menu popup style: 

@topotropic 
<img width="350" alt="image" src="https://user-images.githubusercontent.com/4400286/64291009-0ca9cf80-cf1c-11e9-8f02-f3599698c47f.png">

This is what Fennec looks like:

<img width="350" alt="image" src="https://user-images.githubusercontent.com/4400286/64291055-29460780-cf1c-11e9-9c26-da64caf69ea4.png">

**Comment by cadeyrn** [comment]
> I want to confirm this is the expected menu popup style

I suggest to use the same border radius as for the other menus.

**Comment by sblatz** [comment]
@topotropic, @cadeyrn I now have it with rounded corners:
<img width="350" alt="image" src="https://user-images.githubusercontent.com/4400286/64379490-df285900-cfe3-11e9-9bb3-f4403e3ac27a.png">

**Comment by topotropic** [comment]
@sblatz we should use the same context menu we use when long pressing text or long pressing on URL field on search screen – sorry for not being more explicit right from the beginning.

![contextual-menu](https://user-images.githubusercontent.com/353960/64424751-2e38c180-d0aa-11e9-875e-cabd077fa269.png)

We could use this to start creating UI components; could be "Context menu" and 
have the following variables (completely made up the variable names --> with the dimensions, we would need to think it through a little more so that they are broad enough to cover for more cases but still be descriptive)

type.xml
- Body2 {fontFamily: InterUI-Regular; fontSize: 14sp}

dimens.xml
- cornerSize: 8dp
- marginLeft: 16dp
- marginRight: 16dp
- heightBox: 48dp
- paddingRightMenuText: 12dp
- paddingLeftMenuText: 12dp

also the current elevation for the context menu should be 8dp or so

**Comment by sblatz** [comment]
@topotropic 

This seems to be against the [material design standards for contextual menus](https://material.io/components/menus/#theming). And will require us to make a custom menu style. This type of menu is usually found only when a textfield is editable (and then this menu is displayed with "copy" and "paste" by default). Our browser toolbar is not editable when browsing, though, and thus would require us to do a lot of custom work here. 

Chrome handles this by sending you to edit mode when pressing and holding:
![edit mode 2019-09-06 09_54_57](https://user-images.githubusercontent.com/4400286/64445923-65987580-d08c-11e9-8404-76f53d72ef2a.gif)

Fennec simply inflates a vertical menu like I've shown above in my previous comment.

**Comment by sblatz** [comment]
After a conversation with @topotropic I'm going to timebox working on this newer UI to ~1 hour to see how hard it is to do custom.

**Comment by sblatz** [comment]
Updated to have this custom view:

<img width="350" alt="image" src="https://user-images.githubusercontent.com/4400286/64460679-e157e980-d0af-11e9-8931-0624f1c95a55.png">

**Comment by klint** [comment]
Hi
Not sure it is the right place to ask but in addition to future "Paste & Go" , could there also be a "Paste & Go Private" if we are in normal mode, or "Paste & Go Not Private" if we are in private mode. which IMHO could be more useful than a simple Paste & Go. This could also be an option *after* the "Paste & Go" with 2 choices : go as is, or go to Private/Non Private.
Thanks

**Comment by Djfe** [comment]
@klint what would happen to your tab's history then?
Should it be deleted? or kept? or moved to private/non-private?

it's a cool idea but the behavior needs to be consistent.

**Comment by klint** [comment]
@Djfe: I'm continuing the discussion in feature request #5170 if you don't mind :)

**Comment by sv-ohorvath** [comment]
Verified as fixed on build 2.0.0-rc2.

**Comment by nahuhh** [comment]
Paste and paste & go are only available when the clipboard contains a url

It should work regardless. If it is not a valid url, it should perform a search.

**Comment by sblatz** [comment]
@topotropic Can you verify if the behavior described in @nahuhh's comment is UX's expectation? 

Currently "paste" and "paste & go" only display if the clipboard has a URL copied to it. Do you want it to work with search terms as well?

**Comment by topotropic** [comment]
Yes, that makes sense. Thanks!
