### ISSUE TITLE
Remove "Firefox Preview" logo/text from tab management view

### ISSUE THREAD

**Issue by tom-james-watson** [mozilla-mobile/fenix#4159]
### Why/User Benefit/User Problem

The logo and "Firefox Preview" title on the tab management view seem unnecessary and I find the UX of the component quite annoying. For context I am talking about the following:

![image](https://user-images.githubusercontent.com/3852719/61476636-d1643900-a98d-11e9-919f-6a448fb0a70b.png)

It does look pretty, but as a user it just gets in the way of what I am trying to do - view and manage my tabs. If I a lot of tabs open, I first have to scroll down just to move the tabs to the top of the screen.

That step is a waste of the user's time and it means that to scroll down the tab list there are two separate components that are moving - the logo collapse and the tab scroll itself. I find this makes the app feel heavier and more visually confusing.

Also, if you only half collapse the logo, it will either autoscroll to being fully open or fully collapsed, depending on how far you scrolled. The app moving components around under you whilst you're trying to read your tabs list is annoying.

### What/Requirements

I suggest that if I have tabs open then the logo and "Firefox Preview" title should not be displayed at all.

Maybe you could still show the logo and title if the user has no open tabs.

### Acceptance Criteria (how do I know when I’m done?)

The following should be the default view when opening the tab management view:

![image](https://user-images.githubusercontent.com/3852719/61477063-bb0aad00-a98e-11e9-86da-e36ac8e9e13a.png)

**Comment by boek** [comment]
Hey @tom-james-watson, thank you for your feedback! I will take it back to the UX team. We're in the process of re-evaluating the current home screen. Keep an eye out for updates regarding this. I'm going to close this one for now

**Comment by Poopooracoocoo** [comment]
Firefox's largest competitor is Chrome and Chrome doesn't show it's own logo like this. I'm worried that because this is closed, this'll be forgotten about forever as I've seen that happen to many issues across GitHub.

**Comment by cadeyrn** [comment]
That Chrome doesn't do this is neither a reason to do this nor not to do this... I don't say there has to be the logo but it's totally okay to have a different design.

**Comment by Poopooracoocoo** [comment]
@cadeyrn uh. I think that what competitors do mean a load. Firefox moved to Web Extensions for security, privacy and to make it easier to port Chrome extensions as they have a similar design. Even the UI of Chrome and Firefox on desktop are similar. The themes of Chrome and Fenix are similar. I could go on and on but you get my point. 

That being said, it just takes up room :P
