### ISSUE TITLE
Use consistent coloring for grey buttons

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#4161]
We currently have two different button background colors and use caps for one button. Lets be consistent and not use all caps and use a consistent neutral background color

<img width="350" alt="image" src="https://user-images.githubusercontent.com/4400286/61474947-8b33b900-a93e-11e9-9d1a-b47282a3b2e5.png">

<img width="350" alt="image" src="https://user-images.githubusercontent.com/4400286/61479052-db634900-a947-11e9-9a1a-f58663ada204.png">

**Comment by ekager** [comment]
@AmyYLee should this "Sign in to see all bookmarks" button match the other theme independent grey buttons?

**Comment by AmyYLee** [comment]
> @AmyYLee should this "Sign in to see synced bookmarks" button match the other theme independent grey buttons?

yes please

**Comment by ValentinTimisica** [comment]
Hi, this seems interesting. I will start to work on it.

**Comment by AndiAJ** [comment]
Hi, verified as fixed on **RC 1.2.0-rc.1 from 1/8**
