### ISSUE TITLE
[Bug] Commiting URL with autocomplete in Search flashes just your entered text

### ISSUE THREAD

**Issue by ekager** [mozilla-mobile/fenix#4164]
This should be a fix in AC: https://github.com/mozilla-mobile/android-components/issues/3825

## Steps to reproduce
1. Open search
2. Type "a" (autocompletes to "mazon.com")
3. Press enter

### Expected behavior
Autocomplete text completes and then we navigate to browser

### Actual behavior
Navigates correctly, but autocomplete text disappears and we see a flash of just "a" in the edit toolbar.

### Acceptance Criteria
- [ ] Fix https://github.com/mozilla-mobile/android-components/issues/3825

**Comment by ekager** [comment]
Opened https://github.com/mozilla-mobile/android-components/issues/3825

**Comment by abodea** [comment]
Verified as fixed on the latest Nightly build **11/27 with Google Pixel 3a XL(Android 10).**
Note that everything works as expected as after adding `a` into the search bar and tapping enter, the entire URL `https://www.amazon.com` is displayed and the page is opened. 

@mcarare @ekager if you can confirm that this looks good to you, it would be awesome! 
Based on my comment I will close this issue.

**Comment by mcarare** [comment]
LGTM!
