### ISSUE TITLE
[Bug] Turn on Sync button is purple

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#4167]
With updating our private mode colors, our turn on sync page looks a bit off.

@AmyYLee how should we color this button?

<img width="350" alt="image" src="https://user-images.githubusercontent.com/4400286/61494702-b97bbd80-a96b-11e9-8fc0-af1e3fc43ab4.png">

### Light Mode
<img width="350" alt="image" src="https://user-images.githubusercontent.com/4400286/61494746-d9ab7c80-a96b-11e9-9bf0-0cc90bd9ac22.png">

**Comment by sblatz** [comment]
Labeling as p2 as this is a regression.

**Comment by AmyYLee** [comment]
> With updating our private mode colors, our turn on sync page looks a bit off.
> 
> @AmyYLee how should we color this button?
> 
> <img alt="image" width="350" src="https://user-images.githubusercontent.com/4400286/61494702-b97bbd80-a96b-11e9-8fc0-af1e3fc43ab4.png">
> ### Light Mode
> 
> <img alt="image" width="350" src="https://user-images.githubusercontent.com/4400286/61494746-d9ab7c80-a96b-11e9-9bf0-0cc90bd9ac22.png">

Please use #FBFBFE for the text in the "ready to scan" button for dark theme. This should be the same text colour as in light theme. Thanks!

**Comment by AndiAJ** [comment]
Hi, verified as fixed on the latest Nightly Build #190724 from 24/7 using the following devices:
• Googe Pixel 3a (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• OnePlus 3 (Android 6.0.1)
• Sony Xperia Z3 (Android 5.1.1)

<details>
    <summary>Pictures</summary>

•Light mode
![Screenshot_20190724-110324](https://user-images.githubusercontent.com/51314259/61776323-786c2900-ae03-11e9-8541-ad7524b7aa5f.png)

•Dark mode
![Screenshot_20190724-110335](https://user-images.githubusercontent.com/51314259/61776355-86ba4500-ae03-11e9-8068-c19ecb7474a0.png)


•Private Browsing
![Screenshot_20190724-110349](https://user-images.githubusercontent.com/51314259/61776368-8d48bc80-ae03-11e9-994d-8082886df5d3.png)
</details>

@AmyYLee could you also please take a look just in case?
