### ISSUE TITLE
Import/Export bookmarks to local fileystem 

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/fenix#417]
### Why/User Benefit/User Problem

* If a user is using Fenix alone (without synced accounts), there is no backup of bookmarks if a user removes Fefix
* Even if a user is using Sync, without a secondary machine "backing" up bookmarks, bookmarks will be lost if user removes Fenix
* Users don't want to lose bookmarks

### What / Requirements

As a user, I would like to be able to export bookmarks to my local filesystem and to later import them. 

### Acceptance Criteria (how do I know when I’m done?)

* User can export bookmarks
* User can import bookmarks, adding to existing bookmarks
* Ideally, if identical bookmarks are present in the source and destination, bookmarks are merged

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-12637)

**Comment by Poopooracoocoo** [comment]
this combined with #7325 would pretty much free you from your browser. It's the stuff of dreams 🤤

**Comment by Poopooracoocoo** [comment]
looks like moz wants to put all of these in #2080

**Comment by ratkiley** [comment]
This is an essential feature, because There seems to be no way to transfer mobile bookmarks to a file from the desktop version of firefox, nor from the firefox sync account page, nor from the mobile version of firefox.

**Comment by sheikh-azharuddin** [comment]
Any update? This is really a long pending feature...almost 3 years completed since this is opened!

**Comment by Poopooracoocoo** [comment]
I'd recommend switching to another browser like Bromite that isn't just a companion to the desktop app and achieves a bit more user freedom.

**Comment by locness3** [comment]
Please consider this feature. I believe it is essential to be able to export data from the browser to import it in another one or just use it in any other way. This is really the only thing making me stay on Bromite, and I'm surprised no other browser on Android has this feature.

**Comment by igorlogius** [comment]
4 years and still no local bookmark export ... funny in a sad kind of way.

**Comment by klint** [comment]
> I'm surprised no other browser on Android has this feature.
Wait... Maybe because this is not an essential feature on Android 😉, as there is an quite easy workaround with desktop and sync.

**Comment by ratkiley** [comment]
> > I'm surprised no other browser on Android has this feature.
> 
> Wait... Maybe because this is not an essential feature on Android 😉. And maybe because most of the browsers have that feature available on desktop, as a workaround (and sync of course)

This is false.  The desktop version of Firefox can not export the mobile bookmarks because of an old, unfixed bug.  The developers overlooked development and / or testing of exporting the mobile bookmarks folder which is separate from the desktop bookmarks.  There is no simple workaround to get the mobile bookmarks off of your device and onto another device / computer.

https://bugzilla.mozilla.org/show_bug.cgi?id=1419545

**Comment by igorlogius** [comment]
@ratkiley 
 nice leg-work digging that up  +1

**Comment by ratkiley** [comment]
I struggled with this problem for days when I had to abandon firefox fenix because of breaking changes that made my mobile browser unusable.  I switched to chrome, and I have to say that 95% of users will not be able to migrate / export their bookmarks from firefox mobile, because they are not software developers / IT support technicians.

I was surprised to find well documented issues / bugs / feature requests in both the mobile and desktop versions of firefox projects.   It seems that the developers that work on the mobile version are separate from the ones that work on the desktop version, because there is no overlap in understanding or testing across platforms, otherwise these problems wouldn't have been ignored so long.

**Comment by locness3** [comment]
> This is false. The desktop version of Firefox can not export the mobile bookmarks because of an old, unfixed bug. The developers overlooked development and / or testing of exporting the mobile bookmarks folder which is separate from the desktop bookmarks. There is no simple workaround to get the mobile bookmarks off of your device and onto another device / computer.

That's even worse then.

**Comment by mhammond** [comment]
> This is false.

*That* is false. JSON exports include mobile bookmarks. There also seems to be misinformation about Firefox Sync - it does sync all bookmarks, including mobile, between all devices.

**Comment by ratkiley** [comment]
Take a look for yourself.  Then, why are *both* of these issues still open?

**Comment by mhammond** [comment]
> Take a look for yourself. Then, why are *both* of these issues still open?

Far out, please take a breath and read things carefully. The bugzilla link is about *HTML* exports, and clearly says JSON exports does include them. I'm not sure what other issue you are referring to, but this issue as written is correct. The comment I replied to was not.

**Comment by hcet14** [comment]
I'm annoyed with firefox. I use it for a very long time. It's a very good GNU(!) browser. I like the addons to move in the Internet as anonymous as possible. 

This is my data and nobody should be allowed to access (GDPR https://en.wikipedia.org/wiki/General_Data_Protection_Regulation). 

In former versions there was the possibility to mess with "browser.db" to save your bookmarks. Gone! (I want to move to a new ROM on my phone and want to save my bookmarks before, no chance) 

Now you want to force me to use "Sync". I have no clue what you do with my data. So, I will never use it. Why is nobody telling us where the bookmarks are stored? I don't understand you! Why don't you give the users the option to save their(!) bookmarks?

I will not use firefox on my mobile in the future!

**Comment by MicroBeast** [comment]
Why doing many hoops digging into internal system for browser.db while we can just save everything externally (offline) from start?

I save my bookmarks in encrypted Markdown Text (Passworded Archive also will do). And use Keepass to save all my Passwords. This won't be a big problem compared to digging system partition and a database file. Yeah, I've done that database grabbing long time ago, not worth it if it continue to increase-decrease.

I just don't save anything in any browser, at least not for long. Synced them on my Cloud Drive if needed and under my own choice.

**Comment by hcet14** [comment]
> Synced them on my Cloud Drive

Thanks for the reply, but this is my wish:

I don't want to use any Internet storage, cloud, whatever you name it! 

Where are my bookmarks stored on my(!) storage of the phone?

**Comment by mhammond** [comment]
They are stored in a sqlite file named `places.db` in the app's directory.

**Comment by hcet14** [comment]
> They are stored in a sqlite file named `places.db

no, places.db is not existing here. 

> in the app's directory.

Which directory exactly? 
/data/app ?

I'm rooted, oneplus 7 pro oos10.0.15GM27BA, fennec fdroid 86.1.1

**Comment by mhammond** [comment]
My mistake, it is called `places.sqlite` in the app directory. I can't give you the exact directory name until I return next week from travel so have access to my emulator. The filename is specified at https://github.com/mozilla-mobile/android-components/blob/b827bd3c9c90a315001be415380e8d748894017d/components/browser/storage-sync/src/main/java/mozilla/components/browser/storage/sync/Connection.kt#L74

**Comment by jackyzy823** [comment]
Location is `/data/data/org.mozilla.fennec_fdroid/files/places.sqlite`  if you 're using f-droid's one.

And it is really weird that places.sqlite is outside of profile path ( `/data/data/org.mozilla.fennec_fdroid/files/mozilla/xxxx.default)
It will much hard to implement **switching profiles** like desktop's one in fenix (I know this feature is not on your roadmap)

There's a tool (https://github.com/mozilla-mobile/fennec-profile-manager)  for old fennec  which could export to/import from local filesystem. Android's sharedUserId and signing with the same key as Fennec make this tool work (so do not work for f-droid's one) . But its primary task is to make mozilla developer and tester  to test migration from fennec to fenix  easily.
It would be nice to have similar tool for fenix. (if we have no switching profiles feature , we could use this tool to do it manually )

**Comment by Someone-G** [comment]
This is all done on purpose so that people are dependent on the "ecosystem". And it doesn't matter which one. They are all connected in one way or another. Google's ruling hand is deep in Mozilla's dark place, so there's no point in asking and waiting.
Look for a browser that supports local import/export.

**Comment by kbrosnan** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1806482

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Comment by kbrosnan** [comment]
As part of https://github.com/mozilla-mobile/fenix/issues/26855 this report has been moved to Bugzilla
