### ISSUE TITLE
[Bug] Push notifications don't show up when the app is in the background

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/fenix#4171]
A send tab push message is delivered, but we don't see the notification show up for some reason. Only when the app is in the foreground.

**Comment by softvision-miralobontiu** [comment]
Verified as fixed on the latest RC build 1.2.0-rc.2 with Sony Xperia Z5 Premium (Android 7.1.1), Huawei P9 Lite (Android 6), and Motorola Moto G6 (Android 8).

**Comment by swiftSwathSee** [comment]
Still happening.
