### ISSUE TITLE
[Bug] Sudden incompatibility installation error on 7.1.2 Nexus 4

### ISSUE THREAD

**Issue by ptkovsky** [mozilla-mobile/fenix#4177]
## Steps to reproduce

1. Download apk
2. Try to install it.

### Expected behavior

Correct installation.

### Actual behavior

Incompatibility error upon installation.

### Device information

* Android device: Android 7.1.2 Nexus 4
* Fenix version: firefox_preview-1.1.0-rc.1.arm.apk

**Comment by sv-ohorvath** [comment]
I encountered the same issue installing the arm build on a Nexus 5 (Android 6.0.1): adb returns Failure [INSTALL_FAILED_NO_MATCHING_ABIS] 
Doesn't reproduce on  Samsung Galaxy S10+(Android 9), Nokia 6 (Android 7.1.1).

**Comment by ptkovsky** [comment]
@sv-ohorvath Thanks for the feedback about the taskcluster build. Can confirm the correct installation on my device. Downloaded it from here: https://tools.taskcluster.net/index/project.mobile.fenix.v2.production/latest

**Comment by boek** [comment]
@sv-ohorvath 🤦‍♂ I somehow got two of the architectures mixed up. The builds on the release page should be accurate now.
