### ISSUE TITLE
Hide the bar with buttons for share, bookmarks, read and others

### ISSUE THREAD

**Issue by Chris01277** [mozilla-mobile/fenix#4182]
The bar with the buttons for share, bookmark, read and others shouldn't be visible during normal use, it should only to be opened at a small overlay mark - a triangle for instance - and should be hidden after an adjustable time period.

**Comment by Chris01277** [comment]
An example of the overlay handle to open the Quick Action Bar could be the small triangular handle that opens the app drawer on the Nova Launcher.
![Screenshot_20190720_092723_com teslacoilsw launcher_1](https://user-images.githubusercontent.com/23335674/61576312-e0a3cd80-aad8-11e9-9cc7-b59ca16e7e5a.jpg)

**Comment by ekager** [comment]
We have removed the QAB. Closing
