### ISSUE TITLE
Decide on process for pulling eng tickets into the prioritized eng backlog

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#4186]
We need to decide how to do this. Perhaps I can own just pulling all p2's into the backlog (then p3, etc.) before sprint planning?

If we do this, it's critical **every** eng related ticket has a corresponding eng label of some kind.

Whatever is decided let's make sure it's documented somewhere :)

We should have a similar process defined for product to use (are they pulling in p1/p2 bugs?) I'd be happy to chat with @vesta0 and @liuche about this.

**Comment by liuche** [comment]
My thought here is that, the Prioritized Backlogs should be small staging areas, that allow us to understand what the most important work is. Functionally, we feed from here into Sprint Planning, so probably it should hold tickets that sum to about 1-2 sprints. If the prioritized eng backlog becomes too long, we lose the ability to mentally comprehend it, and we'll just have another list that is too big to be useful 😅 

I'm not sure what this looks like exactly, but I would suggest going through P1s and P2s and pulling the most important few into the Prioritized Backlog each time. I would strongly question if we want to put "all P2s" into this list.

When looking at issues, can people tell what issues seem most important for the next 1-2 sprints? As they triage, and also maybe go through the P1s/P2s right before pre-sprint planning.

@sblatz what do you think about this?

**Comment by sblatz** [comment]
@liuche I think that makes a lot of sense. I think we should probably have a soft cap of a # of items we feel comfortable having in the 'prioritized backlog'. I think something like 10 items would be a great start. Much more than that and it's a long scrolling list.

**Comment by sblatz** [comment]
I've sent out an email with the following process:

> As you’re triaging issues, be sure to label tickets with an “eng:” prefix when necessary, and assign priority as usual. These priorities should be relative to other engineering tickets. Before we do sprint planning, feel free to put tickets you feel are really critical into the “Prioritized Engineering Backlog.” Otherwise, I will pull the tickets with the highest priority in (until we have about 10 tickets in the backlog).
