### ISSUE TITLE
[Bug] Switching to tab list starts at top of page (shows Firefox logo), jittery animation

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/fenix#4189]
## Steps to reproduce

1. Open enough tabs so that the current tab is not present at the top of the tab switcher screen
2. From an open page, tap the tab switcher

### Expected behavior

Fenix should animate directly to where it ends up instead of taking a detour to the top of the tab switcher.

### Actual behavior

Fenix animates to the tab switcher *at the top of the switcher, showing the Fenix logo*, then jumps down to the correct place.

[signal-attachment-2019-07-19-141759.zip](https://github.com/mozilla-mobile/fenix/files/3412692/signal-attachment-2019-07-19-141759.zip)

### Device information

* Android device: Pixel2
* Fenix version: latest

**Comment by boek** [comment]
We're in the process of redesigning the homescreen/tab workflow. Will revisit this issue if it is still relevant.

**Comment by NotWoods** [comment]
Is this still reproducible after the redesign?

**Comment by sv-ohorvath** [comment]
I can't reproduce this on Pixel (Android 10), on Nightly 11/18.
