### ISSUE TITLE
[Bug] Distracting "waterfall" animation when typing into awesome bar

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#4190]
## Steps to reproduce
- Have a profile with a lot of history around a particular search query (e.g. I searched "star wars armada" and I have visited a lot of "star", "star wars", and "star wars armada" pages)
- Type that query into the search bar at decent speed (maybe 2 letters per second)

### Expected behavior
Search results animate but it is not jarring

### Actual behavior
Search results animate but it is jarring: there is a waterfall effect as content moves from added & removed Google search results

Here's a video: https://drive.google.com/file/d/1gtfDPWTlZRp5I7xNrhZ1nmgZm0s-VG2r/view?usp=sharing

### Device information
* Android device: Pixel 2
* Fenix version: Nightly 190719

**Comment by boek** [comment]
UX: What behavior is expected here?

**Comment by lime124** [comment]
@mcomella thank you thank you thank you for the video!!

@AmyYLee for design. removing ux label.

**Comment by AmyYLee** [comment]
@boek Can we remove the waterfall effect here? As the user types in the search and it repopulates it should be an instant update. Please see Firefox desktop as a guide. Let me know if you have any questions.

**Comment by sblatz** [comment]
Updated behavior:

![new behavior](https://user-images.githubusercontent.com/4400286/66406349-57e25280-e9a0-11e9-93d5-97877165a263.gif)

**Comment by sv-ohorvath** [comment]
Verified as fixed on Nightly 10/9.
devices: Pixel 3 (Android 9), Galaxy Tab A (Android 5.1.1),

**Comment by AmyYLee** [comment]
@sblatz Thanks for fixing this. This looks good to me.
