### ISSUE TITLE
[Bug] Tabs animate in over "no tabs" placeholder the first time tabs tray is opened per session

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#4191]
## Steps to reproduce
- Open at least one tab
- Swipe close the app
- Open the app

### Expected behavior
Firefox homepage opens, tabs are present OR tabs animate in in a comfortable way.

### Actual behavior
Firefox homepage opens but the tabs have to animate in. However, the existing animation is awkward:
- It displays the "No open tabs" placeholder for a split second before animating it away
- It translates the tabs down from the "Open tabs" header, pushing all of the other content on the page out of the way – it's very jarring

Here's a video: https://drive.google.com/file/d/1X55wgivB1jFVESdQVhhYR3MOt4-S5lh3/view?usp=sharing

Instead, I might expect:
- "No open tabs" placeholder is not inserted until we fetch the tabs and know there are none (i.e. we have an internal "first load" state)
- Perhaps: Entire tab/collection content area animates in all at once
- Perhaps: we use a placeholder style loading screen (something [like this](https://medium.com/anatomy-of-web-interface/placeholder-loading-ui-bbaf2222f95f))

### Device information

* Android device: Pixel 2
* Fenix version: Nightly 190719

**Comment by boek** [comment]
The HomeScreen is currently undergoing a UX refresh. Will revisit this issue if it is still relevant.

**Comment by ekager** [comment]
This still happens in the current home screen

**Comment by ekager** [comment]
Closing because made irrelevant by tabs tray
