### ISSUE TITLE
[Bug] Soft keyboard is not in private mode when using awesomebar

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#4192]
## Steps to reproduce
- Use a soft keyboard that indicates when it's in private mode (I'm using Google keyboard)
- Click private browsing button from homescreen
- click search box

### Expected behavior
Keyboard is in private mode

### Actual behavior
Keyboard is not in private mode

### Device information
* Android device: Pixel 2
* Fenix version: Nightly 190719

**Comment by kbrosnan** [comment]
Need to use [IME_FLAG_NO_PERSONALIZED_LEARNING](https://developer.android.com/reference/android/view/inputmethod/EditorInfo.html#IME_FLAG_NO_PERSONALIZED_LEARNING) in private mode.

**Comment by CloudyDino** [comment]
Could I take a stab at this?

**Comment by makotokato** [comment]
Find in page has same problem. Although user files an issue for Fennec as https://bugzilla.mozilla.org/show_bug.cgi?id=1561753, this occurs on Fenix too.

**Comment by CloudyDino** [comment]
If my pull request for this issue is accepted, I can do #3939 as well since it'll be very similar.

**Comment by ekager** [comment]
Thanks @CloudyDino we appreciate it! CC @vesta0 is this something you would want private mode to include? There is a contributor PR open.

**Comment by vesta0** [comment]
I assume this would only work when using Gboard and SwiftKey right? But yes let's do it!

**Comment by serovar** [comment]
> I assume this would only work when using Gboard and SwiftKey right? But yes let's do it!

It will work with every keyboard that support this feature, for example also AnySoftKeyboard.

**Comment by softvision-miralobontiu** [comment]
Verified as fixed on the latest build of RC 1.2.0-rc.2 with Sony Xperia Z5 Premium (Android 7.1.1), Huawei P9 Lite (Android 6), and Motorola Moto G6 (Android 8). I tested with Gboard, AnySoftKeyboard, and SwiftKey.
