### ISSUE TITLE
[Bug] Broken Firefox custom tab task remains in recent app switcher after closing custom tabs

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#4194]
## Steps to reproduce
- Open a custom tab (I clicked a link in Telegram)
- Click X to close custom tab
- Click recent app switcher

### Expected behavior
The Firefox custom tab is no longer in the recent app switcher.

### Actual behavior
The Firefox custom tab is in the recent app switcher. Clicking it brings the user to a state with the toolbar at the top of the screen and 0 open tabs:
![image](https://user-images.githubusercontent.com/759372/61567584-f069d600-aa34-11e9-9660-2912a7b98ec0.png)

Here's a video: https://drive.google.com/file/d/1_wGR7KmHbNGtfAzdm_o5v3iXj8MjNR5o/view?usp=sharing

### Device information

* Android device: Pixel 2
* Fenix version: Nightly 190719

**Comment by boek** [comment]
@mcomella are you seeing this with other applications like Slack?

**Comment by sblatz** [comment]
Neither Colin nor I could reproduce this. I even tried with Telegram. (On my Galaxy S9, latest nightly)

**Comment by mcomella** [comment]
> @mcomella are you seeing this with other applications like Slack?

I was unable to reproduce with Slack. The difference seems to be:
- The Slack custom tab in the recent app switchers shows the "Slack" logo
- The Telegram custom tab in the recent app switcher shows the Fenix logo (see screenshot). This will cause there to be two Fenix logos in the recent app switcher

![Screenshot_20190725-093919](https://user-images.githubusercontent.com/759372/61892264-3c4ace00-aec0-11e9-8dd2-855082accaa1.png)

Under the hood, I'm guessing Telegram opens Fenix in it's own task, rather than opening it as part of its own (like Slack).

**Comment by ReekyMarko** [comment]
I'm experiencing this too. The only app that has this issue for me is Telegram, so this makes me think it's an issue on their end. 

I would have reported this to them but I couldn't find any way to do it. The issues in the github repository are disabled.

**Comment by NotWoods** [comment]
Telegram explicitly sets `FLAG_ACTIVITY_NEW_TASK` in their [source code](https://github.com/DrKLO/Telegram/blob/28eb8dfd0ef959fd5ad7d5d22f1d32879707c0a0/TMessagesProj/src/main/java/org/telegram/messenger/browser/Browser.java#L294).

**Comment by mcomella** [comment]
I don't see any reason why this wouldn't be fixed so I'm reopening.
