### ISSUE TITLE
Use independent download manager

### ISSUE THREAD

**Issue by PowERGD** [mozilla-mobile/fenix#4197]
### Why/User Benefit/User Problem
System download manager always has bugs and slow speed. Using independent download manager can creat a better experience.
### What/Requirements
Independent download manager
### Acceptance Criteria (how do I know when I’m done?)
When I creat a Download, Fenix show the download imformation in its own view but not in system download manager.

**Comment by Amejia481** [comment]
We are already working on our own download manager https://github.com/mozilla-mobile/android-components/issues/1968. It will be introduced to Fenix after further testing cycles.
