### ISSUE TITLE
[Bug] After sharing link and going to homescreen on fresh profile, onboarding appears

### ISSUE THREAD

**Issue by lborgman** [mozilla-mobile/fenix#4198]
## Steps to reproduce
1. From another browser (Chrome) choose "Share" from the menus.

2. Click "Firefox Preview".

### Expected behavior
The same URL should open on Firefox Preview.

### Actual behavior
The home page in Firefox Preview is opened instead. 

(This of course makes it harder to test Firefox Preview! 😟)

### Device information

* Android device: Motorola One Vision.

* Fenix version: Android 9

**Comment by yoasif** [comment]
When I tried this, it did open the shared URL, but as a new unfocused tab. 

If Fenix was already open to a tab, it works as you would expect - opening a tab and switching focus to it.

**Comment by softvision-miralobontiu** [comment]
I was able to reproduce with the latest Nightly build 190730 (#12110609). The exact STR are:
1. Make sure Firefox Preview has a clean profile,
2. Go to Reference Browser / Firefox / Chrome etc and share a link to Firefox Preview.
3. Firefox PReview is opened, but the Onboarding tour is displayed, not the shared link.

Reproducible with Motorola Nexus 6 (Android 7.1.1), Huawei P9 Lite (Android 6).

**Comment by AndiAJ** [comment]
Hi, still happening on Nightly Build #12112106 from 30/7  using a OnePlus A3 (Android 6.0.1)

@ekager Could you please help me regarding another matter?
On other devices, e.g. Google Pixel 3a (Android 9) after sharing a tab from Chrome to Fenix the tab opens as is supposed to, but if I press the tab count icon the on-boarding screen shows up.
Should the on-boarding screen still be present?

► Video from OnePlus A3 
![20190731_123209](https://user-images.githubusercontent.com/51314259/62202302-b7652600-b391-11e9-936c-fdf15cbfd129.gif)

► Video from Google Pixel 3a (Android 9)
![20190731_123002](https://user-images.githubusercontent.com/51314259/62202452-014e0c00-b392-11e9-9e86-eb55183b6617.gif)

**Comment by ekager** [comment]
I think the onboarding should show the first time you visit the homescreen. Can we get a confirmation from UX?

**Comment by ekager** [comment]
@AndiAJ you're still seeing the shared link not open in browser? Or are you just seeing the onboarding when you go to home like the last comment above? ^

**Comment by lime124** [comment]
@apbitner for comment. he's at onboarding this week so he won't get to this until next week. thanks!

**Comment by ekager** [comment]
This has morphed into a different issue, so I have renamed it

**Comment by ekager** [comment]
We think this is expected behavior. We want to show onboarding the first time a user is on the homescreen. I'm closing this for now.
