### ISSUE TITLE
[Bug] Deletion of empty data shouldn't be allowed

### ISSUE THREAD

**Issue by nikit19** [mozilla-mobile/fenix#4199]
## Steps to reproduce
Open Delete browsing data fragment.
Delete any tyoe of data.
You will still be able to delete the data even though it says you have 0 collections.

### Expected behavior
Expected behaviour the checkbox should not be checkable if there is nothing to delete

### Actual behavior
You are able to delete data even though you have no data :P

I would like to work on this issue

**Comment by lime124** [comment]
Agreed - if there is nothing to delete then the item should not be selectable. 

@boek am i missing anything? is there data that's getting deleted that would also have the count at 0?

**Comment by lime124** [comment]
removing feature request - it's a bug. we didn't catch the empty state when implementing it.

**Comment by lime124** [comment]
forgot to remove ux label - please re-add if there's something further for us to respond to

**Comment by boek** [comment]
yes it's a bug!

**Comment by ValentinTimisica** [comment]
Hi, I will start to work on it.

**Comment by boek** [comment]
@ValentinTimisica awesome! Feel free to ask if you need any clarification :)

**Comment by boek** [comment]
@ValentinTimisica I forgot that there was already a PR open for this :disappointed:

**Comment by sv-ohorvath** [comment]
Verified as fixed on Nightly 190816 and Rc 1.3.0-rc1
