### ISSUE TITLE
Default browser preference gets toggled on even if I don't make it my default

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#420]
If you press enable default browser, but then don't make it your default, the toggle will still be enabled. We should confirm the user actually enabled as default (like we did in Focus).

**Comment by sblatz** [comment]
This is an easy fix and goes along with some of the changes I'm making in #293.

**Comment by sblatz** [comment]
This isn't as quick of a fix as I thought. It's definitely a small but may be a couple hours, so I'm moving it back to triage for correct prioritization!

**Comment by sblatz** [comment]
Let's pull the utils file from Focus into a-c to handle this.

**Comment by ekager** [comment]
[Opened an issue in AC](https://github.com/mozilla-mobile/android-components/issues/2078)
