### ISSUE TITLE
[Bug] URLs I've never visited are autocompleted

### ISSUE THREAD

**Issue by elcste** [mozilla-mobile/fenix#4207]
## Steps to reproduce

- (Optional) Clear data or erase/reinstall so there's no history.
- Focus the URL/search bar and start typing letters.

### Expected behavior

- Only URLs in my history are autocompleted.

### Actual behavior

- URLs I've never visited are autocompleted.
    - E.g. type **`c`** and it fills in **`cbssports.com`**, a website I've never visited.

This seems unrelated to search suggestions and search engine choice. I first noticed it with Duckduckgo and search suggestions off, but it seems to do the same thing with all DDG or Google and with either engine and search suggestions on or off. 

And not the same as https://github.com/mozilla-mobile/fenix/issues/2065 since these are sites I've never visited.

### Device information

* Android device: Alcatel w/ Android 5.1
* Fenix version: Nightly 190720 60:02 (Build #12010609)

**Comment by cadeyrn** [comment]
This is expected and no bug. As in Fennec (the old Firefox) there is a autocompletion for popular domains:

https://github.com/mozilla-mobile/android-components/blob/master/components/browser/domains/src/main/assets/domains/global

**Comment by elcste** [comment]
Ah, OK. I guess I never noticed it because my Fennec always was connected via sync to a very large history, while recently I was trying Fenix before starting sync.
