### ISSUE TITLE
Move address bar to bottom (when typing)

### ISSUE THREAD

**Issue by Poopooracoocoo** [mozilla-mobile/fenix#4209]
### Why/User Benefit/User Problem
This makes it easier to reach. I believe Kiwi browser does this and inverts the list.
### What/Requirements
Move address box to bottom when typing
Invert list
### Acceptance Criteria (how do I know when I’m done?)
When address box is on the bottom when typing, when the list is inverted and when it has been tested on tablets. (I imagine that Fenix has a top address bar on tablets/ChromeOS)

**Comment by kbrosnan** [comment]
Duping to #562 which is a more general statement of the problem
