### ISSUE TITLE
Focus 8.0/GV65 RelEng

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/fenix#421]
- [x] GV team update Focus 8.0 to GV 65 ([GeckoView API Changelog](https://mozilla.github.io/geckoview/javadoc/mozilla-central/org/mozilla/geckoview/doc-files/CHANGELOG.html))
- [x] Fenix team review/approve pull request and create a new build
- [x] Release notes
- [x] Release management promotes the build to 99% of release channel. Fretboard at 50/50.
- [x] Check whether there are new crashes (Vesta)
- [ ] After 4 days release management sets the roll out to 100%
- [ ] Tag the last and released RC version additionally with the tag of the release (v1.0-RC2 -> v1.0)
- [x] Upload signed APKs to the [release page](https://github.com/mozilla-mobile/focus-android/releases)
- [x] Upload the APK to http://archive.mozilla.org/pub/android/focus/ (S3 bucket) into a folder named like a release (e.g. /android/focus/2.2). Builds from the "latest" folder are linked from the mozilla.org website.

**Comment by vesta0** [comment]
Release Notes:

English: Performance improvements and a new homescreen tip to launch a quick survey!
German: Leistungsverbesserungen, und ein neuer Homescreen-Tipp um eine Umfrage zu starten

**Comment by cadeyrn** [comment]
I don't know why there is a ticket about Focus 8.0 in the Fenix issues tracker, but the German sentence should be:

> Leistungsverbesserungen und ein neuer Homescreen-Tipp, um eine Umfrage zu starten

instead of

> Leistungsverbesserungen, und ein neuer Homescreen-Tipp um eine Umfrage zu starten

(the position of the "," is wrong 🙃 )
