### ISSUE TITLE
Move share and bookmark to menu

### ISSUE THREAD

**Issue by Poopooracoocoo** [mozilla-mobile/fenix#4210]
### Why/User Benefit/User Problem
Having a sheet at the bottom for two items that aren't used  very often is quite annoying
### What/Requirements
Move share and bookmark to menu
### Acceptance Criteria (how do I know when I’m done?)
When the above is completed

**Comment by kbrosnan** [comment]
Functionally the same request as #4204

**Comment by Poopooracoocoo** [comment]
awesome this was done
