### ISSUE TITLE
[Bug] The slider of the Accessibility scale is misaligned

### ISSUE THREAD

**Issue by softvision-miralobontiu** [mozilla-mobile/fenix#4211]
## Steps to reproduce
1. Go to Firefox Preview - Settings - Accessibility and observe the slider of the scale.

### Expected behavior
The slider is on the scale line.

### Actual behavior
The slider is below the scale line.

### Device information
* Android device: Xiaomi MiPad2 (Android 5.1) - x86 architecture
* Fenix version: RC v1.1.0-rc.1

![Screenshot_2019-07-22-14-19-21](https://user-images.githubusercontent.com/40694158/61629235-fa861180-ac8c-11e9-92f0-1701adbc6910.png)

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on:
✔️ Build **#12400616  x86** architecture using a Xiaomi Mi Pad 2 (Android 5.1)
✔️ Build **#12400613** using the following devices:
• Google Pixel 3a (Android 9)
• Huawei Mate 20 lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

**Still reproducible** on ❌**RC v1.3.0-rc.3 x86** architecture using a Xiaomi Mi Pad 2 (Android 5.1)

Based on these findings, I'll mark this ticket as **qa:verified** .
