### ISSUE TITLE
[Bug] [L10N] More menu options are not translated in Swedish

### ISSUE THREAD

**Issue by softvision-miralobontiu** [mozilla-mobile/fenix#4213]
## Steps to reproduce
1. Set your device's language to Swedish.
2. Go to Firefox Preview and observe the translation of some settings options, like: save to collection, rename collection, add tab, sync, accessibility, site permissions, delete browsing data etc.

### Expected behavior
All settings options should be translated.

### Actual behavior
Not all settings options are translated.

### Device information
* Android device: Xiaomi MiPad2 (Android 5.1) - x86 architecture
* Fenix version: RC v1.1.0-rc.1 

![suedeza](https://user-images.githubusercontent.com/40694158/61631624-84d17400-ac93-11e9-96ac-cf038ce5693e.png)
![suedeza1](https://user-images.githubusercontent.com/40694158/61631625-84d17400-ac93-11e9-81b2-1f05da5adae7.png)
![suedeza2](https://user-images.githubusercontent.com/40694158/61631626-84d17400-ac93-11e9-8ad7-c3e5fabeeb28.png)
![suedeza4](https://user-images.githubusercontent.com/40694158/61631628-84d17400-ac93-11e9-99bb-ecd3b3966ec6.png)

**Comment by ekager** [comment]
I think this was just a delay in getting translations. These seem to be present in our translated files now, closing
