### ISSUE TITLE
[a11y][Bug] A blue rectangle remains displayed on the login approval screen

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/fenix#4214]
## Prerequisites
You have Talkback option enabled from your Android settings.

## Steps to reproduce
1. Launch Fenix.
2. Access settings.
3. Login with QR Code.
4. Tap on the `Confirm pairing` button.

### Expected behavior
The approval now required screen is displayed without any issue. 
### Actual behavior
A blue rectangle is still displayed after tapping on the `Confirm pairing` button

* Android device: **`Samsung Galaxy s10+(Android 9)`**
* Fenix version: **`RC v1.1.0-rc.1`**

![Screenshot_20190722-151151_Firefox Preview](https://user-images.githubusercontent.com/42831109/61632099-b39c1a00-ac94-11e9-9e3d-98f4eadbf1d0.jpg)
`**

**Comment by abodea** [comment]
Note that this issue is not reproducible all the time as sometimes after ~2-5 seconds the blue square disappears.

**Comment by kbrosnan** [comment]
Likely a GV bug. @cpeterso

**Comment by cpeterso** [comment]
I wasn't able to reproduce this bug after five times in Fenix on my Moto G5. Maybe this is a problem on Samsung devices?

From the screenshot, it looks like the button has retained the input focus ring after the button has been hidden.

@abodea - Do you have any more details or suggestions for the STR?

**Comment by boek** [comment]
I also wasn't able to reproduce on my Pixel

**Comment by liuche** [comment]
@npark-mozilla will try to repro and report back.

**Comment by npark-mozilla** [comment]
@abodea could you check whether it still repros on master with s10?  I tried remote testkit, but realized I need camera access. :( on moto g5 and pixel 2, I can't repro this issue after multiple tries. Thanks!

**Comment by abodea** [comment]
Sorry for the late response, I tried to reproduce it again but with not so much success, as I mentioned [here](https://github.com/mozilla-mobile/fenix/issues/4214#issuecomment-513772108) I couldn't reproduce the issue all the time using **`(Samsung Galaxy s10+ Android 9) on the latest nightly build from 7/31.`**
I noticed that while being in `Approval` screen after selecting the `Confirm pairing` button and zoom in and dragging the screen, the blue rectangle doesn't remain with the button.
![Screenshot_20190731-094057_Firefox Nightly](https://user-images.githubusercontent.com/42831109/62190982-43b81e80-b37b-11e9-9572-8eee2b8d72ef.jpg)
![Screenshot_20190731-094119_Firefox Nightly](https://user-images.githubusercontent.com/42831109/62190985-461a7880-b37b-11e9-809f-edabc0eb146e.jpg)

**Comment by abodea** [comment]
@npark-mozilla if you consider that the zoom issue described above is not related, I can close this issue.

**Comment by npark-mozilla** [comment]
@abodea I don't think it's the related issue - perhaps we can close this issue until it happens more frequently?

**Comment by abodea** [comment]
@npark-mozilla yes we can close it, it was a strange behavior. In case I will see it again/more frequently I will re-open the issue.
