### ISSUE TITLE
[Bug] [a11y] The tap area for Open tabs' new tab and 3 dot menu buttons is too small

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#4221]
## Steps to reproduce
Running the accessibility scanner on the Fenix homescreen.
### Expected behavior
Larger buttons/tap area for the New tab button and the 3 dots menu. Recommended by the A11y scanner: 48x48dp
### Actual behavior
The current item's size is 24dp. Persons with large thumbs having trouble touching the 2 buttons.
### Device information

* Android device: Pixel 3
* Fenix version: 7/22

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on **RC 1.2.0-rc.1 from 1/8** using a Google Pixel 3a (Android 9).
