### ISSUE TITLE
Upload Fenix Nightly to Nimbledroid

### ISSUE THREAD

**Issue by st3fan** [mozilla-mobile/fenix#4222]
Stefan runs the following script from a personal server. The request is that this be incorporated into our official build automation:

```
#!/bin/bash

APK="target.apk"

cd /tmp
rm -f "${APK}"

curl -L -O "https://index.taskcluster.net/v1/task/project.mobile.fenix.v2.nightly.latest/artifacts/public/build/arm/${APK}" || exit 1

curl -F apk="@${APK}" -F device_config="android5" -v -u STEFANS_NIMBLEDROID_KEY: https://nimble.app/api/v2/apks || exit 1

curl -F apk="@${APK}" -F device_config="android5" -v -u NOJUNS_NIMBLEDROID_KEY: https://nimble.app/api/v2/apks || exit 1
```

Nightly builds twice a day - I think it would be nice to do the upload twice too since it will give us shorter feedback cycles.

**Comment by npark-mozilla** [comment]
@kglazko maybe you can take this?

**Comment by st3fan** [comment]
Cc to @mozilla-mobile/releng

**Comment by kglazko** [comment]
Glad to!

**Comment by mitchhentges** [comment]
Since this is for performance testing, perhaps we'll want to use the `performanceTest` build, rather than the nightly one? This will ensure that nightly-specific config/credentials won't be affected by our performance tests (e.g.: Sentry associating perf-test crashes with `org.mozilla.fenix.nightly`, analytics showing info from per-tests, leanplum, etc).
This will mean that we'll need additional automation work, but IMHO it's worth the segregation

**Comment by kglazko** [comment]
This is done, Fenix is now being uploaded to Nimbledroid on Nightly TC. See latest here: https://nimbledroid.com/my_apps/org.mozilla.fenix?a=e1483f63-6d82-4f53-a660-12823ffd55f0#summary

**Comment by jeanygong** [comment]
Looks like this issue has been resolved and no longer need the attention of he Performance team so I will remove the label Needs:Performance.

**Comment by jeanygong** [comment]
@st3fan, @boek can you provide me the proper github edit access to this issue (or Fenix in general) to remove the needs:performance label as I triage the issue for the Performance team. It seems like I don't have the right access.

**Comment by kbrosnan** [comment]
@kglazko is there any other work here or can we close this issue?

**Comment by st3fan** [comment]
@kglazko Is this part of the automation now? Can i stop my own uploading scripts?

**Comment by kglazko** [comment]
@st3fan Yes it has been for 18 days as per the comment above https://nimbledroid.com/my_apps/org.mozilla.fenix?a=4d60f537-e006-4675-ab98-53c4038f087a#summary via No-Jun's account
