### ISSUE TITLE
[Crash] IncompatibleClassChangeError regression SelectTabUseCase

### ISSUE THREAD

**Issue by colintheshots** [mozilla-mobile/fenix#4223]
## Steps to reproduce
1. Open Fenix to a web page.
2. Long-press a link and choose Open in New Tab.

### Expected behavior
The app opens the link in a new tab.

### Actual behavior
The app fails to open the link and crashes. [This Sentry crash trace may appear](https://sentry.prod.mozaws.net/operations/fenix-nightly/issues/6071282/?query=is:unresolved). This appears to coincide with the Android Components 5.0.0 upgrade and [this PR changing SelectTabUseCase to an interface](https://github.com/mozilla-mobile/android-components/commit/c0cb482bbe827ad5d8413257129a5760b65236c8).

`IncompatibleClassChangeError: Found class mozilla.components.feature.tabs.TabsUseCases$SelectTabUseCase, but interface was expected (declaration of 'mozilla.components.feature.tabs.TabsUseCases$SelectTabUseCase' appears in base.apk)`

### Device information

* Android device: OnePlus
* Fenix version: Nightly 190702 06:02

**Comment by colintheshots** [comment]
I can't seem to reproduce this crash in the latest Nightly so far, but it was crashing over the weekend in the pre-launch reports consistently. Can someone else verify the STR or find an alternate version?

**Comment by st3fan** [comment]
Is this change relevant? https://github.com/mozilla-mobile/android-components/pull/3681

> Now that TabsUseCases.SelectTabUseCase is an interface we can provide your own implementation use case, using the same pattern as fenix is using with other suggestion providers like loadUrlUseCase, searchUseCase and shortcutSearchUseCase and get hooked when the item is selected.

**Comment by colintheshots** [comment]
I can not reproduce this crash trace and there aren't Sentry reports from any newer versions, so I'll mark this closed in the newest Nightly. I believe an older A-C snapshot was at fault.
