### ISSUE TITLE
[Bug] Google Chrome Icon when continue viewing in browser

### ISSUE THREAD

**Issue by j3soon** [mozilla-mobile/fenix#4227]
## Steps to reproduce

- Download Firefox Preview on Google Play Store.
- Open `reddit.com` in Firefox Preview.

### Expected behavior

In the `See Reddit in` section:
- The browser icon should be Firefox Preview's icon.
- Click `Open in Reddit App` should open the external Reddit app.

### Actual behavior

In the `See Reddit in` section:
- The browser icon is Google Chrome's icon.
- Click `Open in Reddit App` has no effect.

<img src="https://user-images.githubusercontent.com/20457146/61650859-3c43a600-ace7-11e9-8660-d2fcfa4b8821.png" width="200"/>

### Device information

* Android device: HTC U11 eyes, Android 7.1.2
* Fenix version: 1.0.1 (Build #11891918 🦎 68.0-20190611143747)

**Comment by Amejia481** [comment]
@j3soon the popup is shown by Reddit, Fenix doesn't have control over it.   You can take a look at it source using the [Dev tool.](https://developer.mozilla.org/en-US/docs/Tools)

``<img src="https://www.redditstatic.com/mweb2x/img/chrome.png" class="XPromoPopup__chrome"><span class="XPromoPopup__actionTitle">Chrome</span><span class="XPromoPopup__actionButton">CONTINUE</span>
``

**Comment by Amejia481** [comment]
We are working on opening native apps from web content you can follow the progress here:
https://github.com/mozilla-mobile/android-components/issues/3687

**Comment by j3soon** [comment]
Thank you for the explanation!

**Comment by Amejia481** [comment]
More than welcome! :)
