### ISSUE TITLE
[Bug] UI update loop in tracking protection panel

### ISSUE THREAD

**Issue by csadilek** [mozilla-mobile/fenix#4228]
## Steps to reproduce
- Load any page
- Turn off tracking protection
- Go to Settings->Tracking Protection->Exceptions
- Remove the site/exception
- Hit back, back to return to the loaded page
- Tap the lock icon and activate, then deactivate the Tracking Protection.

### Expected behavior
- Tracking Protection deactivated

### Actual behavior
- UI will be in a loop moving the slider back and forth indefinitely

### Device information
- Nexus 5

* Fenix version: Latest master, 1.0.1930

**Comment by ekager** [comment]
This should be outdated since we no longer can remove one exception at a time and there is a new panel UI/logic for this. Closing
