### ISSUE TITLE
[Battery Performance] Set up Fenix and Raptor

### ISSUE THREAD

**Issue by Sdaswani** [mozilla-mobile/fenix#423]
First, an engineer should evaluate [this proposal](https://docs.google.com/document/d/1ubK485rmRNwGlP1ezBFwVmJ12vd8QAGSaNJNU43zJFk/edit?ts=5c5df5d5#) (Mozilla login required) and describe to Product how hooking up Fenix and Raptor can help monitor battery usage. Then once product says go ahead the engineer can break this work down.

This ticket may be useful to start to understand how Raptor works and how it can help. https://bugzilla.mozilla.org/show_bug.cgi?id=1517462#c0

**Comment by colintheshots** [comment]
I'll chat with Christian about how he used Raptor in the reference browser.

**Comment by csadilek** [comment]
Support for testing Fenix landed in Raptor now:
https://bugzilla.mozilla.org/show_bug.cgi?id=1522100 (covered both R-B and Fenix)

There's a small enhancement required in Fenix to make this work: Raptor needs an Activity it can start and pass a few intent extras to. These extras can directly be forwarded to the `GeckoRuntimeBuilder`. Here's how we did this for R-B by providing a `BrowserTestActivity`:
https://github.com/mozilla-mobile/reference-browser/pull/460/files

Once that's completed here, pageload, speedometer and battery/power tests will work with Fenix.
