### ISSUE TITLE
Add 'n' recently used apps to share sheet

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/fenix#4231]
### User Story
As a user, when I want to share something, I want to see my most recently used apps first, so I can quickly and convincingly share something.

**UX feedback needed on the proposal below:**

We can implement a solution similar to Pocket where it stores the recently used apps and places the first 6 of those ahead of the alphabetised list of remaining apps after (value may need to be altered in the future).

Since https://github.com/mozilla-mobile/fenix/issues/3726#issuecomment-513380649 is waiting for feedback, we can do this now and UX can iterate over that, since it's a fairly safe change given the technical constraints (of not using the native share sheet).

I can provide some details on the Pocket implementation based on some previous discussions.

**UX update**
You'll find the spec here https://share.goabstract.com/e1a39a6b-2c3e-4fc4-b46c-0c78ec491112?mode=design&sha=f3bcad9f449216555fbf5cc31c3b9933b6538a96 
- "Sent to device" stays as is
- "Recently used" is first section in list 
- All others are sorted alphabetically under the label "All actions"

**Comment by vesta0** [comment]
Thanks @jonalmeida :) @liuche I am adding this to the backlog as it captures product requirement and moved #3726 out.

**Comment by liuche** [comment]
Question: is there any discussion on going back to Android System share sheet (to take advantage of Android's suggested actions, like text to contact)? There's no way that we can have some of these features with something custom.

Question for designers: is there a reason why we decided w/ custom rather than the system share sheet?

#2819 is the discussion about using the System Share Sheet.

One proposal: do a quick prototype of the Android System #4275 share sheet to figure out what is possible.

**Comment by liuche** [comment]
@ekager will follow up with this.

**Comment by bifleming** [comment]
Needs UX: Waiting for @topotropic

**Comment by lime124** [comment]
reviewing meeting today - should be on track to finish by end of sprint. @topotropic lmk if i misunderstood!

**Comment by vesta0** [comment]
@ekager @sblatz I don't suppose the effort would be different if we were to hypothetically show all the apps in an order of most recently used to least frequently used? 

@topotropic was that one of the options you explored?

**Comment by sblatz** [comment]
@vesta0 keeping a list of all the apps is basically the same effort as only keeping 6 :)

**Comment by vesta0** [comment]
Thanks for confirming @sblatz !

@topotropic what do you think about ordering all the apps in order of most recently used?

**Comment by jonalmeida** [comment]
> @vesta0 keeping a list of all the apps is basically the same effort as only keeping 6 :)

A fixed size is a lot less effort that trying to fix it for an known size.

FWIW, Google Photos holds ~12 recently used apps so I recommend just landing something for now that works to see if that benefits users. We don't need to over-engineer this if there are other (larger) apps that follow this behaviour as well.

**Comment by softvision-miralobontiu** [comment]
Verified that when sharing, the most recently used app is displayed first, separately, under the "Recently used" section. 
Tested with Google Pixel (Android 10), and HTC 10 (Android 8), on the latest Nightly build from 2/25.

![Screenshot_20200226-095307](https://user-images.githubusercontent.com/40694158/75323839-5ac1df00-587e-11ea-9bcf-306d625d0d65.png)
