### ISSUE TITLE
Change theme to look like Firefox for Windows

### ISSUE THREAD

**Issue by Poopooracoocoo** [mozilla-mobile/fenix#4235]
### Why/User Benefit/User Problem
It doesn't look like Firefox for Windows. This is more of a branding thing, consistency and appearance thing.

### What/Requirements
Change light theme:
Make the address box white to match desktop in light theme

Change dark theme:
Use Grey 70 of Photon Design System (PDS) for toolbar
Use Grey 60 of PDS for address bar

### Acceptance Criteria (how do I know when I’m done?)
When the above is completed

### related info
Fenix (light):
Toolbar: #f9f9fa (Grey 10 of PDS)
Address bar: #ededf0 (Grey 20 of PDS)

Desktop (light):
Toolbar: #f9f9fa (Grey 10 of PDS)
Address bar: #ffffff (White)

Fenix (dark): (please fill this with definite colours)
Toolbar:  (_probably_ Grey 90)
Address bar: (_probably_ Grey 70)

Desktop (dark):
Toolbar: #38383d (Grey 70 of PDS)
Address bar: #4a4a4f (Grey 60 of PDS)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-12691)

**Comment by brampitoyo** [comment]
@Poopooracoocoo I see what you mean!

Firefox for Desktop (Windows, Mac and Linux) has three themes:

* Default (light URL bar, dark toolbar)
* Light (light URL bar, light toolbar)
* Dark (dark URL bar, dark toolbar)

Whereas Firefox Preview has two themes:

* Light (light URL bar, light toolbar)
* Dark (dark URL bar, dark toolbar)

And what you propose is a theme that’s similar to our “Default” on Firefox for Desktop.

At the moment, we don’t have any plan on building and supporting a third theme. However, when we think about visual redesign, we will keep this issue in mind!

**Comment by Poopooracoocoo** [comment]
@brampitoyo I wasn't actually referring to the default theme. I'm asking for the address box to be light grey or white and for rest of the chrome to be grey

**Comment by Poopooracoocoo** [comment]
random snippets:
![image](https://user-images.githubusercontent.com/51363864/71304571-dc2f6800-241c-11ea-9efd-d712d53b6329.png)
![image](https://user-images.githubusercontent.com/51363864/71304579-f23d2880-241c-11ea-970e-cd917b0a5a59.png)
![image](https://user-images.githubusercontent.com/51363864/71304581-fec18100-241c-11ea-84d0-c7ba98e2ec70.png)

all of these are the light theme.

**Comment by Poopooracoocoo** [comment]
@cadeyrn Why the thumbs down?

**Comment by Poopooracoocoo** [comment]
@betsymi just in case you didn't see @Dunexus's comment

**Comment by Poopooracoocoo** [comment]
any updates on this?

**Comment by KrasnayaPloshchad** [comment]
This feature is available on Fennec builds, any themes from AMO works during the times before Firefox Daylight released.

**Comment by Poopooracoocoo** [comment]
This issue was opened before the new design, Proton, was released, to be clear.

**Comment by KrasnayaPloshchad** [comment]
No, I don’t think so, this should be labeled Feature:FennecTransition. I have used 68.x releases, so I have some experiences for this.

**Comment by Poopooracoocoo** [comment]
While I complete agree about the lack of theme support being important to transitioning from Fennec, this issue isn't related to themes.

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
Material You has been released, so most new software that is for Android is adapting to that. Hard-coding themes was already silly before-hand, but is ever-more silly now. Consequently, this should not be implemented. Also, if this is desired, surely this should be reported upstream, where brand is much more important.

**Comment by Poopooracoocoo** [comment]
>Consequently, this should not be implemented, and this issue should be closed that implementation of Material You...

Um. Android versions below 12 exist. And frankly Material You just seems to be a half-arsed fad of Google's. Google values its brand too much to not ditch it soon. Firefox similarly values its brand.

**Comment by Poopooracoocoo** [comment]
Update on this matter: Firefox for desktop seems to be changing its theme. [Source 1](https://bugzilla.mozilla.org/show_bug.cgi?id=1806945), [source 2](https://github.com/black7375/Firefox-UI-Fix/discussions/555)

**Comment by rokejulianlockhart** [comment]
@Poopooracoocoo, https://github.com/black7375/Firefox-UI-Fix/discussions/555 isn't an official repository. Surely it's irrelevant?

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1809996

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
