### ISSUE TITLE
[Bug] Add UNDO snackbar when deleting tabs from the collection

### ISSUE THREAD

**Issue by softvision-miralobontiu** [mozilla-mobile/fenix#4238]
## Steps to reproduce
1. Create a collection with a few tabs.
2. Delete one of the tabs from the created collection.

### Expected behavior
An UNDO snackbar should be displayed.

### Actual behavior
No snackbar is displayed.

### Device information
* Android device: all
* Fenix version: RC v1.1.0-rc.2

**Comment by sv-ohorvath** [comment]
duplicate of #2725
