### ISSUE TITLE
As a Developer I want to be able to import translated strings

### ISSUE THREAD

**Issue by Sdaswani** [mozilla-mobile/fenix#424]
### Why/User Benefit/User Problem

As a Developer I want to be able to import translated strings. Either via a documented process or in an automated manner.

### Acceptance Criteria (how do I know when I’m done?)

- When strings are updated (translated) on Pontoon, I know how to get those into the Fenix project.

**Comment by Pike** [comment]
https://github.com/mozilla-mobile/fenix/pull/894 opened to add l10n config.

**Comment by Pike** [comment]
I've done the MVP here, which I used to create the PR in https://github.com/mozilla-mobile/android-components/pull/2485.

The code doesn't do a whole lot of fancy yet, like removing obsolete message or the like.

I landed the l10n-specifics in the same module and docker image as the exports, https://github.com/mozilla-l10n/android-l10n-tooling.

**Comment by bbinto** [comment]
As per @pocmo 
- Manual exports are currently working (via Pike)
- Automated exports however depend on rel eng.

@mheubusch agreed to loop back with @Delphine and @st3fan to understand what the next actionable

**Comment by Pike** [comment]
@Callek and I can do this, so I'm marking this FIXED.
