### ISSUE TITLE
Add a close button for the Settings menu

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#4241]
### Why/User Benefit/User Problem
As a user, I want to close the menu as soon as I'm done with changing a setting, without the need to navigate all the way back through.
### What/Requirements
Add a close button, similar to the Library menu.

**Comment by lime124** [comment]
@topotropic @AmyYLee - i think bram may have been the original designer of settings. idk if we're reserving that space for a future action or have another reason to not add a close button. can one of you make a call here and either pass to eng for fixing or comment/close? thanks!

**Comment by AmyYLee** [comment]
I think we should follow android system's pattern of exiting with a back button instead of adding another “x” into the header - it seems a bit much to have 2 buttons that do a similar action in the header for settings which wouldn't be accessed regularly. @topotropic has been looped in as well.
