### ISSUE TITLE
[Bug] Create a bookmarks folder inside a new folder, doesn't add it

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#4242]
## Steps to reproduce
1. Create a new folder "A" in the mobile root.
2. Create a new folder "B", choose A as its parent while in the Add folder mode.
3. Open folder A and look for folder B.
### Expected behavior
B should be inside folder A.
### Actual behavior
Folder B is nowhere, doesn't get added to folder A.
### Device information

* Android device: Nexus 5 (Android 6.0.1)
* Fenix version: 1.1.0 rc2.

**Comment by mcarare** [comment]
@sv-ohorvath can you please reproduce this?

**Comment by sv-ohorvath** [comment]
Cannot reproduce this on Nightly 190731.
