### ISSUE TITLE
[Bug] Opened tabs turn into about:blank pages briefly after about:crashcontent

### ISSUE THREAD

**Issue by softvision-miralobontiu** [mozilla-mobile/fenix#4243]
## Steps to reproduce
1. Open a few tabs.
2. Open about:crashcontent in a new tab.
3. Select [Close tab].

### Expected behavior
The tab should close, but the other opened tabs should not be affected.

### Actual behavior
The tab closes, but the other opened tabs are affected - they turn in about:blank for a few seconds. Please see the attached logcat and GIF.

### Device information
* Android device: Samsung Galaxy Tab A6 (Android 5.1.1), LG Nexus 5 (Android 6.0.1)
* Fenix version: RC v1.1.0-rc.2

[logcat.txt](https://github.com/mozilla-mobile/fenix/files/3422098/1.txt)
![20190723Trim](https://user-images.githubusercontent.com/40694158/61713654-bb75c000-ad61-11e9-82ae-344969dc48cf.gif)

**Comment by boek** [comment]
Dup of #1577
