### ISSUE TITLE
[Bug] variant.getPackageLibrary() is obsolete fixed in Kotlin 1.3.40

### ISSUE THREAD

**Issue by AaronMT** [mozilla-mobile/fenix#4245]
Gradle Sync Issue (warning):

architecture/build.gradle

> WARNING: API 'variant.getPackageLibrary()' is obsolete and has been replaced with 'variant.getPackageLibraryProvider()'.
It will be removed at the end of 2019.
For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
To determine what is calling variant.getPackageLibrary(), use -Pandroid.debug.obsoleteApi=true on the command line to display more information.
Affected Modules: architecture

Resolved with Kotlin 1.3.40

https://youtrack.jetbrains.com/issue/KT-30784

Should be fixed with https://github.com/mozilla-mobile/android-components/issues/3534

**Comment by ekager** [comment]
We did this a long time ago. Closing
