### ISSUE TITLE
Long pressing tab switcher should open a new tab

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/fenix#425]
### Why/User Benefit/User Problem

* Opening a new tab is a "heavy" task, involving a trip to a new screen, then tapping a + icon
* Quickly open a new tab with my home page. 
* Makes my browser feel faster to use and fluid. 
* Competing browser (Kiwi) does this

### What / Requirements

As a user, I would like to open a new tab by long pressing the tab switcher instead of tapping the tab switcher, then tapping a new tab button. This lets me save time and feels fluid and fast. 

### Acceptance Criteria (how do I know when I’m done?)

Long pressing the tab switcher opens a new tab with the users's default new tab page.

**Comment by vesta0** [comment]
@lime124 will comment

**Comment by lime124** [comment]
apologies - I got way behind in my GH emails. I've added this to our UX triage board. Thanks!

**Comment by buttercookie42** [comment]
Personally I think the Fennec way (tab switcher button and new tab button are aligned such that tapping twice works to open a new tab) might feel even faster that pressing and holding, but that might be a matter of preference and muscle memory. Either way would be better than the current situation, though, I guess.

**Comment by boek** [comment]
Added it to our Gestures meta
