### ISSUE TITLE
back button during page load

### ISSUE THREAD

**Issue by nahuhh** [mozilla-mobile/fenix#4256]
### Why/User Benefit/User Problem
Stopping a page from loading. Currently you have to open the menu. 

### Acceptance Criteria (how do I know when I’m done?)
Pressing your device back button during page load should perform a "stop". Currently it goes back, even during a page load

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-12708)

**Comment by ekager** [comment]
This would be a fairly easy thing to implement. Probably would be better handled by AC if we decide to add it

**Comment by kbrosnan** [comment]
Works for me using current Fenix nightly.
