### ISSUE TITLE
Use system fonts in websites

### ISSUE THREAD

**Issue by PowERGD** [mozilla-mobile/fenix#4257]
### Why/User Benefit/User Problem
Many users set different fonts to adapt their devices to their habit. Use system fonts can improve the coherence of the system-application.
### What/Requirements
Add an alterable option which let user can choose using system fonts but not Fenix default fonts.
### Acceptance Criteria (how do I know when I’m done?)
Fenix can use system fonts to show websites.

**Comment by NotWoods** [comment]
Hi @PowERGD, could you elaborate on your request here? Is there a particular website that isn't using system fonts when it should? We generally use system fonts when requested by a site.
