### ISSUE TITLE
Document release process and create a release checklist

### ISSUE THREAD

**Issue by boek** [mozilla-mobile/fenix#4258]
We want to be able to share the responsibilities of release management. Let's document the process and create a checklist template that we can add to the sprint to account for the time spent.

We can take inspiration from the release checklist we had for Focus: https://github.com/mozilla-mobile/focus-android/blob/master/.github/ISSUE_TEMPLATE/release_checklist_template.md

**Comment by liuche** [comment]
Consider:
* Having a cut-off time for cutting the release (and release manager has final say, and should have no pressure)
* Curating the Milestone (this can be a pain) which goes to QA, GH release notes for a release
* Issue template for Release Manager (and we can size it)

**Comment by liuche** [comment]
@ekager will do the release for 1.3 w/ this checklist!
