### ISSUE TITLE
[Bug] Follow device theme option doesn't work

### ISSUE THREAD

**Issue by dannycolin** [mozilla-mobile/fenix#4259]
## Steps to reproduce

0. Open Android settings
0. Go to *Display > Style*
0. Set *Style* to *Dark* (According to @leobel96 the opposite bug also happens, setting it to *Light*)
0. Open Firefox Preview
0. Go to *Settings*
0. Set *Theme* to *Follow device theme*

### Expected behavior

Firefox Preview should set the theme to dark.

### Actual behavior

Firefox Preview set the theme to light

### Device information

@dannycolin specs (Works again since 12070609) :
* Device: Samsung Galaxy S5 (ktle) 
* OS: LineageOS 16.0 (Android 9)
* Fenix build: 12042111

@leobel96 specs:
* Device: Nokia 7
* OS: Android 9
* Fenix build: 12130633

**Comment by hakkikaancaliskan** [comment]
No problem on Xperia XZ1 Android 9
Nightly 190723 18:04 (Build #12041810)

**Comment by dannycolin** [comment]
> No problem on Xperia XZ1 Android 9
> Nightly 190723 18:04 (Build #12041810)

My build seems to be more recent than yours. So the bug could be a regression. Is there something similar to mozregression for fenix?

**Comment by hakkikaancaliskan** [comment]
> > No problem on Xperia XZ1 Android 9
> > Nightly 190723 18:04 (Build #12041810)
> 
> My build seems to be more recent than yours. So the bug could be a regression. Is there something similar to mozregression for fenix?

On latest nightly works too
Nightly 190724 18:05 (Build #12051811)

**Comment by leobel96** [comment]
I have the same but opposite problem: if I set the light theme it works but if I set "Follow device theme" (which is light) it is set to dark. Nightly 190725 on Nokia 7 Pie with Android Pie. Anyway I noticed this bug many updates ago...

**Comment by dannycolin** [comment]
Looks like it has been resolved in 12070609. Closing for now.

**Comment by leobel96** [comment]
@dannycolin I'm using 12130633 but It Is not resolved

**Comment by dannycolin** [comment]
> @dannycolin I'm using 12130633 but It Is not resolved

@leobel96 I've added your informations and reopened the issue.

**Comment by ekager** [comment]
So you're forcing the Android 9 "Dark Setting" here? I don't know if there's much we can do here, it seems like the system is passing us the wrong information.

**Comment by dannycolin** [comment]
> So you're forcing the Android 9 "Dark Setting" here? I don't know if there's much we can do here, it seems like the system is passing us the wrong information.

@ekager  If it was the system fault, I think it should still be broken in a newer build of Fenix. I'll be glad to do a mozregression but sadly fenix isn't supported yet.

Could someone on the team looks if something related to the theme has changed between 12042111 and 12070609? Thanks.

**Comment by umerf52** [comment]
I'm also facing this bug.
OnePlus 3T, Android 10 (LOS 17.1, 20200401)
org.mozilla.fenix.nightly, Nightly 200416 08:30

It's daytime (1:40pm) right now, so everything is in light mode
In Phone Settings > Display > Dark Theme = Will turn on automatically at sunset
Fenix is set to follow system theme, but it is currently following light theme.
All other apps that are supposed to follow light mode are in light theme, e.g. Slack etc

**Comment by purpleyuan** [comment]
If this ticket will be marked stale, perhaps it would be better to close as a duplicate of #11372.
