### ISSUE TITLE
[Bug] Homescreen elements theme has changed to dark font and highlights

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#4262]
## Steps to reproduce
1. Open a tab.
2. View the homesceen. Observe the Save to collection button.
3. Observe the current tab highlight.
### Expected behavior
The button's font is white.
The tab highlight is purple.
### Actual behavior
Text in black font.
Dark tab highlight.
### Device information

* Android device: Googe Pixel 3a (Android 9), Huawei Mate 20 Lite (Android 8.1.0), Samsung Galaxy S7 (Android 7), Sony Xperia Z3 (Android 5.1.1)
* Fenix version: Nightly 190724 Build #12050609

**Comment by sv-ohorvath** [comment]
@sblatz The tab highlight color still needs to be updated back to purple.

**Comment by sblatz** [comment]
@sv-ohorvath the private mode tab ring color is *supposed* to be pink. In dark mode it should be purple, in light mode it's blue. See #1750.

**Comment by softvision-miralobontiu** [comment]
Verified as fixed on the latest Nightly build 190729 (#12100610) with Motorola Nexus 6 (Android 7.1.1), and Huawei P6 Lite (Android 6).

**Comment by softvision-miralobontiu** [comment]
Verified as fixed on the latest RC build 1.2.0-rc.2 with Motorola Motos G6 (Android 8), and Huawei P6 Lite (Android 6).
