### ISSUE TITLE
[Bug] The repository description breaks the CoC

### ISSUE THREAD

**Issue by smonff** [mozilla-mobile/fenix#4263]
[Mozilla's Github repository for Fenix](https://github.com/mozilla-mobile/fenix) use an unacceptable description:

> Fenix is not your parent's Android browser

![image](https://user-images.githubusercontent.com/1219097/61780813-802bcd80-ae03-11e9-9db6-f1f1a5263a27.png)

It is against Mozilla's [Code of Conduct](https://www.mozilla.org/en-US/about/governance/policies/participation/) that clearly said:

> These guidelines aim to support a community where all people should feel safe to participate, introduce new ideas and inspire others, regardless of:
>  - [...]
>  - Age
>  - [...]

And also: 

> Hurtful or harmful language related to:
>  - [...]
>  - Age
>  - [...]
> is not acceptable. [ ... ] If you’re unsure if a word is derogatory, don’t use it. This also includes repeated subtle and/or indirect discrimination; when asked to stop, stop the behavior in question.

In no way this description is acceptable for a Mozilla project and it don't add any information about the aim of the project.

Please edit this with an informative description that don't contain slurs and remove any references to this anywhere.

**Comment by cadeyrn** [comment]
I guess you didn't understand the wordplay. Fenix is pronounced like Phoenix - the name of Firefox before it was called Firefox. So it's not the same browser your parents already used 17 years ago. Hurtful? Harmful? Really, you shouldn't take life so seriously…

**Comment by smonff** [comment]
> I guess you didn't understand the wordplay. 

Thanks for explaining, because really I didn't understood.

Again, from CoC:

> If you’re unsure if a word is derogatory, don’t use it. This also includes repeated subtle and/or indirect discrimination; when asked to stop, stop the behavior in question.

**Comment by cadeyrn** [comment]
> It means that if a person report this problem to you, you should think about it and not argue about it.

1. I didn't argued, I EXPLAINED it to you because you didn't knew what the sentence means.
2. You didn't report it _to me_. I am a user like you and I have the same right to share my opinion as you. You can't talk about "discrimination" because of a funny sentence but then complain about people with different opinions.

> What do you mean?

Phuh… I've said everything. I just wanted to explain it to you and give you the advice to take life not that seriouly. There are bigger problems in the world. You're welcome…

**Comment by smonff** [comment]
I dunno why you assumed in the beginning I didn't understand the sentence.

If a GitHub repository description needs an explanation, it's broken. It must be self explanatory.

**Comment by smonff** [comment]
So the description got finally removed? What was the process for this decision?

**Comment by mthld** [comment]
I definitely think there is a problem with this repo description. Even if it was not breaking the code of conduct, it's not clear and must be changed to reflect the real purpose of this project.
