### ISSUE TITLE
[Bug] Firefox Preview icon and name is displayed instead of Firefox Nightly

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/fenix#4270]
## Steps to reproduce
1. Install latest Nightly Fenix build.
2. Check the icon and name in homescreen.
### Expected behavior
Firefox Nightly icon(dark) and name should be displayed.
### Actual behavior
Firefox Preview icon and name is displayed.
### Device information

* Android device: **`Samsung Galaxy S10+(Android 9) and Huawei p20 lite A9`**
* Fenix version: **`Nightly 190724 06:02 (Build #12050609)📦: 6.0.0 🦎: 68.0-20190711090008`**

### Notes
Please note that I couldn't reproduce this bug on the following devices:
**• Googe Pixel 3a (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• OnePlus 3 (Android 6.0.1)
• Sony Xperia Z3 (Android 5.1.1)**

Also, note that I tried to delete cache / storage uninstall and reinstall the app.
For more details please see the [Video](https://drive.google.com/file/d/1hl4AG-PMpdsfN9HWrNxPhM_CG_mbLeqf/view?usp=sharing) and [log.txt](https://github.com/mozilla-mobile/fenix/files/3427005/log.txt).

**Comment by ekager** [comment]
Is this still happening?

**Comment by abodea** [comment]
Hi @ekager, with the latest builds I didn't encountered the issue anymore. The problem was with the builds from ~month ago. 
Now everything looks fine and the correct icon is displayed.
