### ISSUE TITLE
Allow users to opt into visiting a site with a certificate problem, as Fennec does.

### ISSUE THREAD

**Issue by wisniewskit** [mozilla-mobile/fenix#4273]
### Why/User Benefit/User Problem
Users currently cannot access some sites with certificate issues, such as `https://myonlineaccount.net`. They can at least opt into the visit in Fennec by tapping "i understand the risks".

### What/Requirements
Improve the "Secure Connection Failed" page so that it allows users to opt into visiting the site regardless of issues, as Fennec does.

### Acceptance Criteria (how do I know when I’m done?)
Users should be able to opt into visiting a site like `https://myonlineaccount.net` despite seeing the "Secure Connection Failed" page first.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-12723)

**Comment by liuche** [comment]
This is mostly fixed by #6380 . There is now an "Advanced" section in the site certificate error page that allows accepting the risk and continuing.

I just tried with myonlineaccount.net though, and it doesn't actually work.

**Comment by kbrosnan** [comment]
Desktop shows that myonlineaccount.net uses TLS 1.0 or 1.1 which are deprecated. https://observatory.mozilla.org/analyze/myonlineaccount.net#tls shows that it uses TLS 1.0 which is not accepted.

**Comment by swanknight** [comment]
> 
> 
> This is mostly fixed by #6380 . There is now an "Advanced" section in the site certificate error page that allows accepting the risk and continuing.
> 
> I just tried with myonlineaccount.net though, and it doesn't actually work. I've filed #8564 for handling the "pinned-test" failure on badssl.com.

The "Accept the Risk and Continue" does nothing. (Android 10, FF 83.1)

**Comment by SuperSpyTX** [comment]
I second that.  It was working but after a few times it is completely broken.  FF 86.1.1 Android 11

**Comment by majkinetor** [comment]
Not fixed at this date and latest ff on mobile. Button is there but cant be clicked.

**Comment by GuzTech** [comment]
I can confirm what @majkinetor said. Firefox 86.1.1 (Build #2015794883) on Android 10.

**Comment by capitalPSA** [comment]
Firefox 88.1.1 (Build #2015804891) also has the same problem.

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1809995

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
