### ISSUE TITLE
Switch to using new Social Tracking Protection list

### ISSUE THREAD

**Issue by liuche** [mozilla-mobile/fenix#4277]
## User Story
- As a user, I want to Social Tracking Protection to be part of the on-by-default Recommended TP settings so I can browse social sites (without it breaking sites).

Add Social Tracking protection to Recommended list (so it's on by default) ONCE we are using the new Social Tracking Protection lists that Desktop uses.

## Dependencies
- This is split off from #3571 and depends on GV bug https://bugzilla.mozilla.org/show_bug.cgi?id=1568295

### Acceptance Criteria
- GeckoView bug has landed, in AC, and added in Fenix
- Social Tracking Protection is part of Recommended list

**Comment by liuche** [comment]
@vesta0 to add any labels you want (like MUST, SHOULD, etc)

**Comment by Amejia481** [comment]
As https://github.com/mozilla-mobile/android-components/pull/4249 landed we don't need this issue anymore this behavior will be applied when Fenix uses 12.0.0 AC version that is covered on https://github.com/mozilla-mobile/fenix/pull/5100
