### ISSUE TITLE
Create a Fenix Leanplum Attribute that tells us when a user registers for FxA 

### ISSUE THREAD

**Issue by liuche** [mozilla-mobile/fenix#4284]
This is related to #3059 which covers sign-in, but currently that cannot be distinguished from registering/sign-up. 

## User Story - Marketing is the user.
- As a Marketer, I would like to know whether a user is registering for FxA, as opposed to signing in, so that I can

1. Attribution of new FxA Signups, accessible in the Leanplum interface. The availability of these data will allow for evaluation and optimization of notification campaigns that have FxA signup as their KPI. Note that a) UTMs are not currently a solution that is available in Fennec; b) UTMs would not solve for this need unless those UTMs collected by the FxA data store can be referenced in the Leanplum dashboard (such an integration is possible).

2. Triggering contextual notifications based on a sign-up, through Leanplum. While we currently use Leanplum solely as a means of providing notifications (both push and in product), Product and UX are planning to use the Leanplum framework to deliver dynamic UX treatments to users based on their actions and attributes. A new user signing up for an FxA would benefit from a different treatment than an existing user signing in, it is therefore important to be able to distinguish between these two discrete events.
[ @lwa-moz  to fill out and elaborate - this way FxA team can also understand if there is other data that can be used instead of adding a new event type ]

## Dependencies
- Potentially, depending on ^: Wil Clouser's FxA team will need to allow distinguishing between sign-in and registering

### Acceptance Criteria
Marketing confirms "FxA Signup" is correctly being generated from new sign-ups, is available in the Leanplum interface, and can be used to generate dynamic messaging.

**Comment by lwa-moz** [comment]
**User Story - Marketing is the user**
There are two critical areas that this work will inform:
1) 

1. Attribution of new FxA Signups, accessible in the Leanplum interface. The availability of these data will allow for evaluation and optimization of notification campaigns that have FxA signup as their KPI. Note that a) UTMs are not currently a solution that is available in Fennec; b) UTMs would not solve for this need unless those UTMs collected by the FxA data store can be referenced in the Leanplum dashboard (such an integration is possible).
2. Triggering contextual notifications based on a sign-up, through Leanplum. While we currently use Leanplum solely as a means of providing notifications (both push and in product), Product and UX are planning to use the Leanplum framework to deliver dynamic UX treatments to users based on their actions and attributes. A new user signing up for an FxA would benefit from a different treatment than an existing user signing in, it is therefore important to be able to distinguish between these two discrete events.

**Acceptance Criteria**
Marketing confirms "FxA Signup" is correctly being generated from new sign-ups, is available in the Leanplum interface, and can be used to generate dynamic messaging.

**Comment by amedyne** [comment]
Closing this as we no longer integrate with Leanplum.
