### ISSUE TITLE
[Bug]No clear distinction between bottom bar and Web content

### ISSUE THREAD

**Issue by Scripterr** [mozilla-mobile/fenix#4289]
There seems to be no clear distinction between the bottom bar and the web content sometimes. Like there is a drop shadow/elevation between the url bar and QAB, which doesn't help much but would be more helpful if it's between web content and QAB.
**This is how fenix displays-**

![Screenshot_20190802-081554~2](https://user-images.githubusercontent.com/42364681/62340656-d669d200-b4cf-11e9-9539-37a0880617ac.png)

**This is how brave displays-**

![Screenshot_20190723-184222~2](https://user-images.githubusercontent.com/42364681/61864357-ceeb6d00-aec0-11e9-8abc-97eafea9d3e9.png)

**Comment by lime124** [comment]
@AmyYLee do you happen to know if this is per spec or is it an unresolved item on the punch list?

**Comment by AmyYLee** [comment]
@lime124 @NotWoods Hi, there should be a 1dp drop-shadow behind the bottom bar. Please see the shadow we use for headers (referenced below). That same shadow should be applied above the bottom bar. ]]
<img width="461" alt="Screen Shot 2019-07-30 at 4 00 37 PM" src="https://user-images.githubusercontent.com/5992746/62161027-53842400-b2e3-11e9-81b0-250b70631c8e.png">

**Comment by boek** [comment]
There is now a shadow and 1dp border on the navbar. We also removed the QAB
