### ISSUE TITLE
[Bug] The Autofill feature doubles a partially entered email

### ISSUE THREAD

**Issue by LaurentiuApahideanSV** [mozilla-mobile/fenix#4292]
## Steps to reproduce
1. Go to www.washingtonpost.com/subscribe/signin or the login page from settings;
2. Start typing a valid email adress.
### Expected behavior
Typing the email address should be smooth without interruptions.
### Actual behavior
At one point the Autofill feature will activate and double the partially entered email address.
### Device information

* Android device: Samsung Galaxy S5 (Android 6.0.1) and Samsung Galaxy Tab Active (Android 5.1.1)
* Fenix version: Firefox Preview 1.1.0 7/23

### Notes
A user has reported that when this happens on a Samsung Note 4, the backspace key does not work anymore. See issue https://bugzilla.mozilla.org/show_bug.cgi?id=1568402 for further details.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/50983519/61878267-5ce34a00-aef9-11e9-8a7b-bc6c4a47c390.gif)
[logcat.txt](https://github.com/mozilla-mobile/fenix/files/3431775/logcat.txt)

**Comment by thesillypeanut** [comment]
I'm having the same problem on a OnePlus 5T device.

**Comment by softvision-miralobontiu** [comment]
Verified as fixed on the latest Nightly build from 6/12 with GV 79.0a1, using Samsung Galaxy Note 8 (Android 9), OnePlus 5T (Android 9), and Sony Xperia Z5 Premium (Android 7.1.1).
