### ISSUE TITLE
Create test for QuickActionSheetController

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#4303]
As we add logic to this controller instead of the interactor, we should add tests.

The previous tests can be found [here](https://github.com/mozilla-mobile/fenix/pull/4279/commits/c4a2f97c30459e6233f8caec1dd055d5dc5bdae4#diff-49f8b2e3435f9bb2d537af24361c5ad7)

**Comment by dragneelfps** [comment]
Created a PR  #4835 which adds tests for `DefaultQuickActionSheetController`(impl. of `QuickActionSheetController`)

**Comment by mcarare** [comment]
Tests were merged.
