### ISSUE TITLE
[Performance] Unconditional Inflation of Find in Page view

### ISSUE THREAD

**Issue by colintheshots** [mozilla-mobile/fenix#4307]
## Steps to reproduce
1. Start a SysTrace session.
2. Start Firefox Preview from an external application link with the app warmed up and no pages loaded.
3. End SysTrace session.

### Expected behavior
The Find in Page view should not get inflated until the user clicks the button to use the feature.

### Actual behavior
The Find in Page view is inflated on warm startup, taking ~75ms on a Nexus 5X and >20ms on a Samsung Galaxy S8. On every device, one or more frames are skipped.

[SysTrace output: output.html.zip](https://github.com/mozilla-mobile/fenix/files/3433402/output.html.zip)

### Device information

* Android device: Nexus 5X and Samsung S8
* Fenix version: 1.1.0

**Comment by sblatz** [comment]
@colintheshots can you please place a priority on this so we know if it's critical to work on

**Comment by colintheshots** [comment]
This should be fixed.
