### ISSUE TITLE
[Performance] Unconditional Inflation of Reader View Controls

### ISSUE THREAD

**Issue by colintheshots** [mozilla-mobile/fenix#4309]
## Steps to reproduce
1. Start a SysTrace session.
2. Start Firefox Preview from an external application link with the app warmed up and no pages loaded.
3. End SysTrace session.

### Expected behavior
The Reader View Controls should not get inflated until the user clicks the button to use the feature.

### Actual behavior
The Reader View Controls are inflated on warm startup, taking ~33ms on a Nexus 5X and >15ms on a Samsung Galaxy S8. On every device, one or more frames may be skipped.

[SysTrace output: output.html.zip](https://github.com/mozilla-mobile/fenix/files/3433402/output.html.zip)

### Device information

* Android device: Nexus 5X and Samsung S8
* Fenix version: 1.1.0

**Comment by hawkinsw** [comment]
According to my measurement, for Cold Start this accounts for approximately 6% of total startup time.

**Comment by hawkinsw** [comment]
[cpu-art-20190924T162731.zip](https://github.com/mozilla-mobile/fenix/files/3649309/cpu-art-20190924T162731.zip)

**Comment by sblatz** [comment]
@Baron-Severin do you know if this still happens even though we removed the QAB?

**Comment by Baron-Severin** [comment]
I didn't touch reader view control setup, so I'm fairly confident this will still be true.

**Comment by hawkinsw** [comment]
It is still true that the ReaderViewControlsBar unconditionally inflates. It is also still true that this has (at least some) impact on startup performance (applink case). See attached profile.
[unconditionalreaderviewinflation.zip](https://github.com/mozilla-mobile/fenix/files/3985843/unconditionalreaderviewinflation.zip)

**Comment by colintheshots** [comment]
This was merged with https://github.com/mozilla-mobile/android-components/pull/5494.
