### ISSUE TITLE
Scroll-down on the home screen messes up everything

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#431]
## Steps to reproduce
1. Tap the search bar and load one or more webpages.
2. Tap the home button.
3. Scroll down the Current sessions list.
### Expected behavior
The Fenix logo disappears. Search bar, session list scrolls up.
### Actual behavior
The scroll down doesn't work at first try, you need to keep sliding until it starts to work.
When the scrolling finally works, everything is misplaced.
[Recording](https://drive.google.com/file/d/18WD6BlLqsnQo3WbWWmLbFmV_w0SEn_Tm/view?usp=sharing)
### Device information

* Android device: Samsung Galaxy Note 8 (Android 8.0)
* Fenix version: 1.0

**Comment by sblatz** [comment]
![buggy 2019-02-12 08_01_14](https://user-images.githubusercontent.com/4400286/52649047-65d8e580-2e9c-11e9-926f-332f5bdc923c.gif)
