### ISSUE TITLE
[SPIKE]Toggle to enable and disable external app auto launch

### ISSUE THREAD

**Issue by Lululalu** [mozilla-mobile/fenix#4312]
### Why/User Benefit/User Problem
Some users want websites opening their respective apps, while other users dislike this behavior. A toggle would be appreciate by both sides. 

### What/Requirements
A toggle or check box like the following 

### Acceptance Criteria (how do I know when I’m done?)
![Screenshot_20190726-001526_Kiwi Browser](https://user-images.githubusercontent.com/32398857/61923540-d64f5c80-af3a-11e9-8fa2-ed09115a84af.jpg)

**Comment by ikurek** [comment]
+1, lack of this always kept me away from using Firefox on Android

**Comment by boek** [comment]
We need to investigate how difficult this would be.

**Comment by vesta0** [comment]
This is a good feature that will allow user more options and flexibility. I will investigate this and consult the GeckoView team to make sure all security aspects are considered, then tag UX for their feedback.

**Comment by vesta0** [comment]
Added this to the AC triage board to get an idea of what we need to build this.

**Comment by Leon422** [comment]
All I want to say is that this (and addons) is the only thing that is keeping me from switching from Chromium based browsers to Firefox Preview on my phone full-time. Not being able to *automatically* open Twitter, YouTube, Reddit etc links with their respective apps really, really gets on my nerves after a while. I understand that there are security concerns which means it has to be optional. I would even understand if the option had to be hidden so that only power users enable it. But I think I'm not alone in saying that this is an extremely important feature for a lot of users. I hope it gets implemented.

Thank you for all your hard work.

**Comment by vesta0** [comment]
Glad to see that this is only an E3 for A-C. I assume A-C is building exposing the preference and then the Fenix team will need to add it to the UI?

Tagging UX for feedback on the UI.

**Comment by vesta0** [comment]
Further clarification:

- We already provide users with the option to open a site in the app - the option is surfaced in the Quick Action Bar and not very visible. We are working on that!

- The goal of this spike is to determine whether we can make this a user choice (e.g. toggle in setting) so the user can choose to either keep the current setting (open sites in Fenix by default + surface option to open in app) or change their settings to default open in app.
- In future, we should also be able to give users the option to always open certain sites in app and not others.

Why not always default open in app?

We want our users to browse sites in Fenix so we can protect them from trackers and provide a safe browsing experience for them. We also know that many Firefox users prefer this behaviour. When we first launched Fenix and temporarily enabled default open in app, user feedback suggested that most users were not happy. Having said that, as Firefox, we always want to provide and respect user choice and allow users to customize their experience based on their needs and preferences.

**Comment by brampitoyo** [comment]
I’m removing the `needs-ux` label, because this issue is now ready for us to size, prioritise, etc.

**Comment by rocketsroger** [comment]
After investigation, though the feature is easy to enable, there are some issue surrounding how it works.  With just enabling the feature, a App will be launched but the browser also loads the URL at the same time.

To make this feature works correctly, it needs two things:
1. Do not load the page if an App is opened to handle the request.
2. Allow browser to pass in user preference so user can choose to launch 3rd party App by default or not.

**Comment by rocketsroger** [comment]
https://github.com/mozilla-mobile/android-components/issues/4950 created

**Comment by vesta0** [comment]
Re-opening this issue as it still requires UX feedback @brampitoyo @lime124

**Comment by rocketsroger** [comment]
@vesta0 I actually opened an issue to replace this one https://github.com/mozilla-mobile/fenix/issues/6438

**Comment by vesta0** [comment]
Thanks @rocketsroger :) You read my mind!
