### ISSUE TITLE
Enable the flash light when using the camera to scan QR codes. 

### ISSUE THREAD

**Issue by Lululalu** [mozilla-mobile/fenix#4313]
### Why/User Benefit/User Problem
Some places may be quite dark, and some phones may have lower quality cameras. An option to enable the lantern/flash light may help under these circunstances. 

### What/Requirements
A way to enable the flash light

### Acceptance Criteria (how do I know when I’m done?)
It's possible to enable the light

![Screenshot_20190726-001943_Samsung Internet](https://user-images.githubusercontent.com/32398857/61923754-73aa9080-af3b-11e9-824e-693724be90b4.jpg)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-12754)

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807391

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
