### ISSUE TITLE
Websites not finished loading sometimes[Bug]

### ISSUE THREAD

**Issue by mikeGolf08** [mozilla-mobile/fenix#4317]
## Steps to reproduce

1. Open a website like (https://aerotelegraph.com/)
2. Open some links of this website in new tabs
3. Open a new website on the first tab

### Expected behavior

Loaded websites on the other tabs are fully intialized and all pictures on the website are there.

### Actual behavior

No pictures are pre-loaded and a reload of the website is necessary.

### Device information

* Android device: 9 OOS 9.0.4 Onplus 3T
* Fenix version: Nightly 190725 18:03 (Build #12061813)
📦: 6.0.0
🦎: 68.0-20190711090008

**Comment by sv-ohorvath** [comment]
dupe: https://github.com/mozilla-mobile/fenix/issues/4321
