### ISSUE TITLE
Remember bookmark location

### ISSUE THREAD

**Issue by ghost** [mozilla-mobile/fenix#4318]
### Why/User Benefit/User Problem

Since it takes a few steps to get to the bookmarks toolbar folder, make an option to remember which bookmark folder the user last used.

### What/Requirements

If I open a bookmark in Bookmarks toolbar folder in library, next time I click on my library it should automatically take me to bookmark toolbar folder. 

### Acceptance Criteria (how do I know when I’m done?)

an option is added to replicate the above. 
thanks

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-12759)

**Comment by artella-coding** [comment]
@ghost absolutely would be nice if firefox implemented this. This feature has also been requested at https://github.com/mozilla-mobile/fenix/issues/10606

**Comment by artella-coding** [comment]
This feature was also requested for the ios version 4 years ago at https://github.com/mozilla-mobile/firefox-ios/issues/2144 and https://bugzilla.mozilla.org/show_bug.cgi?id=1309018

**Comment by mortee** [comment]
This would be nice, same for new bookmarks. I see absolutely no reason why I would add new items in the "Mobile Bookmarks" folder, just because I visited on my cellphone.

**Comment by boek** [comment]
Clsoing as a dup of #10606
