### ISSUE TITLE
Homescreen sessions placeholder should be removed when there is a current session active

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#432]
## Steps to reproduce
1. Open one or more tabs.
2. Tap the home button to see the current session.
### Expected behavior
When there are tabs opened, the sessions placeholder shouldn't be displayed anymore.
### Actual behavior
The sessions placeholder still displayed at the bottom.
![screenshot_20190211-155214_fenix](https://user-images.githubusercontent.com/4037709/52567626-77c37580-2e15-11e9-89be-83126456793b.jpg)

### Device information

* Android device: Samsung Galaxy Note 8 (Android 8.0)
* Fenix version: 1.0

**Comment by colintheshots** [comment]
The sessions feature isn't in the app yet. There is no bug because the placeholder is just a placeholder for a feature we don't have.
