### ISSUE TITLE
[Bug] Website not finished loading

### ISSUE THREAD

**Issue by mikeGolf08** [mozilla-mobile/fenix#4321]
## Steps to reproduce

1. Open a website like (https://aerotelegraph.com/) on the first tab
2. Open links of articles on new tabs
3. Switch to another website on first tab

### Expected behavior

Websites on other tabs are fully loaded.

### Actual behavior

Some pictures are not loaded and a refresh of the website is obligatory.

### Device information

* Android device: 9 OOS 9.0.4 Oneplus 3T
* Fenix version: Nightly 190725 18:03 (Build #12061813)
📦: 6.0.0
🦎: 68.0-20190711090008

**Comment by hakkikaancaliskan** [comment]
Just for info:
No problem on me with my own build based on latest changes. I've just changed gecko version.
📦: 6.0.0
🦎: 70.0a1-20190726094308

**Comment by mikeGolf08** [comment]
Info back:
No problems anymore
Android device: 9 OOS 9.0.4 Oneplus 3T
Fenix version: Nightly 190801 06:18 (Build #12130633)
📦: 6.0.2
🦎: 69.0-20190729080047
