### ISSUE TITLE
[Bug]l10n Spanish - Text in Adding tabs to Collection view is overlapped

### ISSUE THREAD

**Issue by isabelrios** [mozilla-mobile/fenix#4323]
## Steps to reproduce
Set the device in Spanish (this may affect other languages too)
Open one tab and save a Collection
Open more tabs
Tap on the Collection -> Add tabs
Tap on Select all
### Expected behavior
All the strings are shown fine
### Actual behavior
Select tabs and Unselect all strings are overlapped.
Please see screenshot:
![Unselect tabs](https://user-images.githubusercontent.com/1897507/61951163-7398a800-afb0-11e9-97ae-cc0b813f2529.png)

### Device information
* Android device: Pixel 3
* Fenix version: 26/7 build

**Comment by ValentinTimisica** [comment]
Hi, this seems interesting. I will start to work on it.

**Comment by ValentinTimisica** [comment]
I have two options to fix the overlapping issue and I need the UX approval.
1. Limit the text to one line and use `ellipsize="end"`.

![image](https://user-images.githubusercontent.com/52956363/62046655-2a935e80-b211-11e9-9449-57da4af7875a.png)

2. Don't limit the number of lines (there could be even 3 or more lines).

![image](https://user-images.githubusercontent.com/52956363/62046695-3d0d9800-b211-11e9-90f3-146ce7d09765.png)

**Comment by lime124** [comment]
we have an issue open for these fixes - adding it there.

**Comment by AmyYLee** [comment]
Please go with this direction but both text areas should be left aligned and not centered. 

<img width="570" alt="Screen Shot 2019-08-07 at 1 44 37 PM" src="https://user-images.githubusercontent.com/5992746/62645141-9f554f80-b919-11e9-8f83-35b291145c41.png">
