### ISSUE TITLE
[Bug]190726 06:03 update removed collections and reset settings

### ISSUE THREAD

**Issue by otede** [mozilla-mobile/fenix#4327]
## Steps to reproduce
1. Update
2. Launch the app
### Expected behavior
Collections and old settings intact.
### Actual behavior
Collections and old settings removed.
The Sync does not hook up to my "XT1562 PREVIEW" device upon logging in with my email. Instead the Sync gets set up with a blank space for the device name.
### Device information
* Android device: Moto X Play X1562, Android 7.1.x (LineageOS)
* Fenix version: Build 190726 06:03

**Comment by boek** [comment]
@otede Are you able to reproduce this with every update?

I'm going to close this for now. If you are able to reproduce I will re-open 👍
