### ISSUE TITLE
[Bug] DDG: Touching "more results" triggers a browser selection box. 

### ISSUE THREAD

**Issue by Lululalu** [mozilla-mobile/fenix#4332]
## Steps to reproduce
Search anything on DDG
Scroll down to the bottom
Touch More Results button 

### Expected behavior
More results are loaded and nothing else happens. 

### Actual behavior
![Screenshot_20190726-155911_Android System](https://user-images.githubusercontent.com/32398857/61975150-beb9b780-afbe-11e9-9301-1534c33bc286.jpg)

### Device information

* Android device: Galaxy A5 2017 8.0 
* Fenix version: 190725

**Comment by reinhart1010** [comment]
Reinhart from @webcompat here.

I couldn't reproduce this in Fenix 1.1.0 (Build #12042112), 📦 4.0.1 🦎 68.0-20190711090008
in Samsung Galaxy A7 (2018), Android 9.0.

Sampling from https://duckduckgo.com/?q=apple&t=fpas&ia=web

**Comment by julKali** [comment]
For me (Nokia 8, Fenix v1.1.0), a Javascript alert box pops up:

![Screenshot_20190727-160820](https://user-images.githubusercontent.com/17690423/61995438-e07f7100-b088-11e9-82e3-71861ee8c0f0.png)

This by the way happens on other sites too, f.e. when you click on "View x reply" on 9gag.com comment sections. [This issue](https://github.com/mozilla-mobile/fenix/issues/4266) is likely related.

**Comment by Dea1993** [comment]
i've a similar issue #4266 on some website with Xperia X (F5121) android 8.0, for example:
- amazon, when i search something, using the search box, then i click on X button (on the search box) to clear the search, automatically google chrome opens (and this isn't my default browser, infact my default browser is fenix).
- google groups, if you open a thread, and scroll down, to the bottom of the page, when you click on the link "Desktop" to get the desktop version of the page, chrome opens.
- instagram, i've the same problem (on click it opens chrome) on instagram, when i click on a video to play it.
this is a "recent" regression, time ago, there wasn't this issue.

this bug make fenix almost unusable, please investigate on it and fix.

**Comment by Dea1993** [comment]
reinstalling the spp solved my problem, have you tried?

**Comment by ekager** [comment]
This is no longer happening on master as far as I can tell. Are you all still seeing this problem?

**Comment by softvision-miralobontiu** [comment]
I was not able to reproduce this issue on a local build from 85/ master with LG G7 Fit (Android 8).
I tried with amazon.com, instagram.com, dar.org.
