### ISSUE TITLE
Align search results UI with other firefox products

### ISSUE THREAD

**Issue by lime124** [mozilla-mobile/fenix#4335]
## User Story
Create a cohesive experience across platforms for search results list 

## Dependencies
- List dependencies on other issues/teams etc.

### Acceptance Criteria
- I can do …  (e.g. add a bookmark)

### Reference
https://github.com/mozilla-mobile/fenix/issues/2037

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-12775)

**Comment by lime124** [comment]
@vesta

**Comment by cpeterso** [comment]
Closing this incomplete meta issue
