### ISSUE TITLE
[Bug] Some download file names truncated inappropriately

### ISSUE THREAD

**Issue by neekless** [mozilla-mobile/fenix#4336]
Trying to download files with periods in their name will have everything after the first period truncated.

## Steps to reproduce
Many ways to trigger this but for the sake of testing try downloading these 2 files:

1. https://www.apkmirror.com/apk/google-inc/messenger-google-inc/messenger-google-inc-4-7-056-release/messages-4-7-056-kraken_rc13_xxxhdpi-arm64-v8a-phone-android-apk-download/download/

2. https://download.msfjarvis.website/caesium/wahoo/beta/Caesium-wahoo-v3.6-b792615ced1b.zip

### Expected behavior
Actual file names are:

1. `com.google.android.apps.messaging_4.7.056_(Kraken_RC13_xxxhdpi.arm64-v8a.phone)-47056249_minAPI21(arm64-v8a)(560,640dpi)_apkmirror.com.apk`. 

2. `Caesium-wahoo-v3.6-b792615ced1b.zip`

These are also the file names when downloaded on other browsers (Chrome, Firefox desktop, etc).

### Actual behavior
In fenix the downloaded file names are: 

1. `com.apk`

2. `Caesium-wahoo-v3.zip`

### Device information

* Android device: Pixel 2XL Android 9
* Fenix version: Nightly 190726 06:03 (Build #12070610) 📦: 6.0.0 🦎: 68.0-20190711090008 (but has been happening for a few versions now)

Could https://github.com/mozilla-mobile/android-components/commit/b2a1f28277c91cfc2db0369d01b7572ccba8d001 be related?

This is a huge problem in my opinion as most apk downloads are named com.apk and files with version numbers in their name (e.g. v3.1.zip and v3.2.zip) also get the same name (v3.zip).

![Screenshot_Firefox_Preview_20190727-075729](https://user-images.githubusercontent.com/22426822/61987611-9a35fd80-b007-11e9-8664-f5b1a09be0ae.png)
![Screenshot_Firefox_Preview_20190726-094241](https://user-images.githubusercontent.com/22426822/61987612-9a35fd80-b007-11e9-85d6-92e6575753a5.png)

**Comment by NotWoods** [comment]
This will get fixed when we transition to the new Gecko download manager (#4296). I'll look into fixing it for the current download manager as well.

**Comment by NotWoods** [comment]
Fixed in Android Components 6.0.0
