### ISSUE TITLE
Integrate PDF Viewer

### ISSUE THREAD

**Issue by reinhart1010** [mozilla-mobile/fenix#4337]
One of my favorite workflows in Firefox for Android (Fennec) was the ability to view PDF files without permanently saving them in storage. There was an option to download the file, or open in another viewer.

![Image](https://i.imgur.com/tvXjEW2.jpg)

Sometimes passing the file directly to viewer apps (then delete from cache) is storage-efficient for mobile devices, as many PDF viewers do not have an option to delete the file (including the Drive viewer itself).

There are two possible ways to do this:
+ Pass the PDF file directly to PDF viewers (Google Drive, etc.)
+ Include pdf.js viewer into Fenix

I personally prefer the latter for advanced features (especially in viewing and navigation options), while there are some features that might be missing or broken in Fenix (such as zoom gestures and print).

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-12777)

**Comment by cadeyrn** [comment]
+1 for pdf.js in Fenix, that would be awesome!

By the way, there is https://addons.mozilla.org/de/android/addon/android-pdf-js/ for _Fennec_. Maybe it's helpful for the Fenix UX people because they can already test how it works on a smartphone.

**Comment by reinhart1010** [comment]
So far the default pdf.js UX does not integrate well with Photon, and things that are as rad as Fenix.

Oh yeah, I think it's nice to have a new light/dark theme for pdf.js to celebrate that new feature in Fenix.

**Comment by serovar** [comment]
This could also work via extensions, for example I used [this one](https://addons.mozilla.org/en-US/android/addon/android-pdf-js/) on Fennec.

**Comment by timawesomeness** [comment]
This is partially fixed by the "Open links in apps" option

**Comment by madb1lly** [comment]
Hi @timawesomeness,

That's one way of looking at it, but down that path also lies the fix for almost every feature related bug in this repo - "there's an app for that"! And there is, almost certainly another app for almost every feature which people are requesting - most of the time it's Chrome or another Google app. 

So is that really the solution? Use another app?

PDF.js is integrated into Firefox Desktop for a good reason and I think that reason applies on mobile too - there's nothing more frustrating than having a search result be a link to a PDF then have to download it and open it another app, it's incredibly frustrating, when there's a way to do this already, it just isn't implemented.

Cheers 🙂

**Comment by opusforlife2** [comment]
Life would be so great if all documents on the net were shared as ePUBs instead of PDFs. Those would be much lighter and easier to support in the browser, given they use the same Elements ( (☞ﾟヮﾟ)☞ ) as browsers. But this is just the wishful thinking of an open source enthusiast.

**Comment by madb1lly** [comment]
Hi all,

This would also massively reduce the number of files that I have saved in my downloads folder! In almost all cases I don't want to keep a copy of the PDF, I just want to read it. Currently I have to save it and view it in another application, but if I could just view it directly in Fenix without needing to save it that would be great!

Cheers 🙂

**Comment by opusforlife2** [comment]
@madb1lly Book Reader (Simple book reader) - https://f-droid.org/packages/com.github.axet.bookreader is a wonderful PDF reader you can use with "Open link in external app". It doesn't clutter your Downloads folder, and even has PDF Reflow and a Night Mode to invert colours.

It's a good compromise until Fenix gets a PDF Viewer.

**Comment by reinhart1010** [comment]
@timawesomeness Actually, there are certain cases where opening online 
PDFs on other Android apps would fail. For example, an internal website 
that I used always blocked file downloads without setting appropriate 
HTTP request headers and session cookies (for security reasons). As a 
result, the corresponding PDF app reported an error that the downloaded 
file was invalid or corrupted, as it was just downloading a plaintext 
response indicating that the request was rejected.

Fennec never passed these (request header and body, cookies, etc.) data 
through Android intents, and you might not want that to happen for 
privacy reasons (Hint: they can steal your logins just by using the 
session data!). According to my tests it only instructed the selected 
PDF app to open directly from the URL, instead of a temporary folder as 
used in desktop versions of Firefox.

So, while "Open links in apps" functionality partially solves the 
problem, it is still likely to have similar "file corruption" issues as 
found in Fenix. This would be a different case if Fenix temporarily 
saved the file before launching an Intent, or directly integrate a PDF 
viewer.

**Comment by madb1lly** [comment]
Thanks for the tip @opusforlife2 , I don't normally have Open links in external apps enabled but I've turned it on to give this a try. My viewer of choice is MuPDF but I had Book Reader too before my last reset.

All good points @reinhart1010, thanks for pointing out the technical limitations (and problems). Does Chrome include a PDF viewer? If not then this could be a bit of a USP for Firefox.

Cheers 🙂

**Comment by opusforlife2** [comment]
> I don't normally have Open links in external apps enabled but I've turned it on to give this a try.

You don't need it. Long press is the way to go. If you enable Open in App from Settings it tries to open every damn link in another app if it can. Very annoying.

**Comment by reinhart1010** [comment]
Chrome will ask the user to download the file first before opening it. 
So it currently has the same behavior as in Fenix.

**Comment by madb1lly** [comment]
Thanks @opusforlife2, I now have Book Reader installed for this because MuPDF doesn't support opening from links for some reason.
Thanks for the clarification @reinhart1010. 
Cheers 🙂

**Comment by cadeyrn** [comment]
To answer to two points from last year:

> So far the default pdf.js UX does not integrate well with Photon, and things that are as rad as Fenix.
> Oh yeah, I think it's nice to have a new light/dark theme for pdf.js to celebrate that new feature in Fenix.

The new design of pdf.js integrates well with Photon and has both, a light and a dark theme. :)

@vesta0 Since this feature is on no project board and has no labels (except the label for the feature request) yet - do you think this feature is worth an investigation spike at least to see how much effort this would be so it can be prioritised, based on the investigation?

**Comment by opusforlife2** [comment]
@cadeyrn You're talking about the Photon redesign for PDF.js that was merged just yesterday, aren't you?

**Comment by Poopooracoocoo** [comment]
Also see: https://github.com/mozilla/pdf.js/issues/6136 https://github.com/M-Reimer/android-pdf-js/issues/6

**Comment by reinhart1010** [comment]
I have recently tested https://addons.mozilla.org/en/android/addon/android-pdf-js/ on Nightly (via Debugging menu > Custom Addon collection) and it wprks pretty well. Except that printing does not work as it is unsupported in both Fenix and Fennec.

![Screenshot_20201030-084454_Firefox Nightly.jpg](https://user-images.githubusercontent.com/17312341/97650881-58f38f80-1a8d-11eb-8864-f52c9763073e.jpg)

The included PDF.js version might have been old too.

But, it still does not resolve the case when HTTP-based security measures (request params, session cookies, etc.) are taken place. The resulting webpage will be blank and there is no way to download the PDF.

**Comment by KrasnayaPloshchad** [comment]
PDF.js is now adopted Phantom UI.

**Comment by KrasnayaPloshchad** [comment]
Android PDF.js is already updated, and there is a way to download PDF via a menu on the viewer.

**Comment by binomnom** [comment]
just pinging this to show there is still desire for this feature.

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
If this is integrated, please allow disablement of it. I need not waste storage to integrate a viewer that shall without doubt be worse than its standalone competitors.

**Comment by opusforlife2** [comment]
I suspect this will only be added after Fission makes it into Fenix.

**Comment by kbrosnan** [comment]
This is in nightly at the moment, evaluating the quality and performance.
