### ISSUE TITLE
No text in settings when entered from private browsing

### ISSUE THREAD

**Issue by kbrosnan** [mozilla-mobile/fenix#434]
## Steps to reproduce
* Tap on the private browsing icon
* Tap on the 3 dot menu

### Expected behavior
* text from settings is displayed

### Actual behavior
* no text is displayed
![screenshot-fenix-settings](https://user-images.githubusercontent.com/250273/52582038-184b7280-2de1-11e9-91bb-7ab2cec59b32.png)

### Device information

* Android device: Pixel 3 and Galaxy S5
* Fenix version: ?

**Comment by sblatz** [comment]
Good catch. Quick fix--just need to swap out the colors :)

**Comment by sv-ohorvath** [comment]
Verified as fixed.
