### ISSUE TITLE
Support IPv6 addresses

### ISSUE THREAD

**Issue by ilango100** [mozilla-mobile/fenix#4343]
## Steps to reproduce
Try to access a site using its IPv6 address

Eg: `[2606:4700::6810:2902]` (IPv6 address for www.mozilla.org at the time of writing)

### Expected behavior
The browser connects to the IPv6 address and opens the webpage. This works perfectly on Firefox Android 68.0.

### Actual behavior
Starts google search with  `[2606:4700::6810:2902]` as query.

### Device information

Android device: Nokia 6.1 Plus (Android 9.0 Pie)
Fenix version: 1.1.0

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-12782)

**Comment by L-as** [comment]
Is there any work-around for this?

**Comment by 31415-hub** [comment]
Excuse me, this problem has not been fixed for so long, is it not going to be fixed?

**Comment by armujahid** [comment]
Still facing same issue with latest firefox mobile 84.1.1

**Comment by 31415-hub** [comment]
> 最新的firefox mobile 84.1.1仍然面临相同的问题

Yes, the latest version does not solve this problem. It seems that there is no plan to fix this problem, which is disappointing.

**Comment by aryadas98** [comment]
This is still not working on Firefox 85.1.3

**Comment by pmarks-net** [comment]
Firefox 86.1.1 for Android scores 10/10 on http://test-ipv6.com/, and I can even follow the link to [http://[2001:470:1:18::115]:80/ip/?callback=?](http://[2001:470:1:18::115]:80/ip/?callback=?).  It only fails (i.e. becomes a search query) when I try to edit the URL.

So this appears to be a user interface bug in the URL bar.

**Comment by 31415-hub** [comment]
> 适用于Android的Firefox 86.1.1在http://test-ipv6.com/上获得10/10的评分，我什至可以点击链接到[http：// [2001：470：1：18 :: 115]：80 / ip /？callback =？](http://%5B2001:470:1:18::115%5D:80/ip/?callback=?)。当我尝试编辑URL时，它只会失败（即成为搜索查询）。
> 
> 因此，这似乎是URL栏中的用户界面错误。



> 适用于Android的Firefox 86.1.1在http://test-ipv6.com/上获得10/10的评分，我什至可以点击链接到[http：// [2001：470：1：18 :: 115]：80 / ip /？callback =？](http://%5B2001:470:1:18::115%5D:80/ip/?callback=?)。当我尝试编辑URL时，它只会失败（即成为搜索查询）。
> 
> 因此，这似乎是URL栏中的用户界面错误。

Yes, the browser supports ipv6, but you cannot directly enter the ipv6 address in the search option.

**Comment by D4v1dH03** [comment]
It is unfortunately still not changed in Firefox Nightly Android v89.0a1

Any news or updates?

**Comment by grzchr15** [comment]
Can anybody explain why Firefox cannot have a UI where direct ipv6 addresses and ports can be used? Firefox on desktop does work fine with https://[ipv6]:port

**Comment by TownCube** [comment]
Looks like it's something more complicated then just the search bar, even bookmarks with IPv6 link local addresses don't work, they just take you to a blank page, not even an error message.

**Comment by t-m-w** [comment]
Accessing a site by IP address is a very basic feature, but this issue has been open for two years completely unaddressed. If one of us made a patch for it, would anyone even look at it? Is this not the right place to report bugs?

**Comment by t-m-w** [comment]
This got me thinking there could be a security issue if someone tries accessing https://user:pass@[ipv6], so I tried that and it actually took me to the page instead of searching it (good), but popped up and warned that the site doesn't require authentication.

So that is another workaround, apart from the bookmark workaround: access the site via something like http://user@[ipv6] even if there is not actually authentication, and you will get there. Thank goodness _that_ doesn't perform a search.

**Comment by L-as** [comment]
Wow, great workaround. Making a new issue might bring attention to the issue.

**Comment by WereCatf** [comment]
Seriously? Firefox can't do even this correctly? Jesus Motherf*cking Christ! They sure do spend a lot of time and effort on wanking with the UI and all, but can't be bothered to fix a basic god damn feature that definitely should be fixed!

**Comment by D4v1dH03** [comment]
> Seriously? Firefox can't do even this correctly? Jesus Motherf*cking Christ! They sure do spend a lot of time and effort on wanking with the UI and all, but can't be bothered to fix a basic god damn feature that definitely should be fixed!
> 
> It's no wonder IPv6-support worldwide hasn't gotten any more traction when even browsers can't do it correctly.

Cut your entitled attitude.
Open source developers owe you nothing.

**Comment by StarOnTheSky** [comment]
Still not fixed in Firefox Android 94.1.2. :(

**Comment by CT702-7** [comment]
It is such a pity that the question remains in version 96.1.1 .It makes me difficult to access some websites by cellphone via ipv6. However,  by adding the address into bookmark can temporarily solve this issue.

**Comment by Saiv46** [comment]
Version 106.1, here we go again

**Comment by WereCatf** [comment]
"We don't have a need for this, therefore no one can have a need for this"

**Comment by StarOnTheSky** [comment]
3 years later, still not fixed.

**Comment by StarOnTheSky** [comment]
https://github.com/mozilla-mobile/fenix/blob/adb9cfbb24ded739140b9290c2f0e226636da01a/app/src/main/java/org/mozilla/fenix/search/SearchDialogController.kt#L20
Seems that this module is outdated. I'm trying to find it. It's really weird to work with a language whose function definition cannot be found directly.

**Comment by StarOnTheSky** [comment]
I'm learning how to build it :)

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807752

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
