### ISSUE TITLE
[Bug] Links do not open in installed external apps

### ISSUE THREAD

**Issue by hugoh** [mozilla-mobile/fenix#4344]
## Steps to reproduce

1. Search for "maps" on Google
2. Follow result to Googlee Maps

### Expected behavior

Google Maps app opens. 

### Actual behavior 

https://www.google.com/maps/ opens in the browser, despite Maps app being set as default for those links. 

This is reproducible with Amazon, Instagram, and others. 

### Device information

* Android device: Samsung Galaxy Tab S5e 
* Fenix version: 1.1.0 (Build #12042112) /  📦: 4.0.1 / 🦎: 68.0-20190711090008

**Comment by IndefiniteBen** [comment]
Already reported in #3321, #3256 and #3349.

**Comment by hugoh** [comment]
Thanks @IndefiniteBen; missed those when searching for existing issues. I'm going to close it as a duplicate.
