### ISSUE TITLE
"recently bookmarked" section

### ISSUE THREAD

**Issue by cadeyrn** [mozilla-mobile/fenix#4347]
### Why/User Benefit/User Problem

Sometimes it can be difficult to find your newest bookmarks. I agree with the conclusion of #2961 that the newest bookmarks shouldn't be at top by default because as a user I expect my bookmarks structure to be unchanged.

However, there is not only a "recently bookmarked" section in Firefox for Desktop, this month Mozilla also introduced a "recently bookmarked" section in Firefox 18 for Apple iOS.

So it would be great for cross platform parity to bring this feature to Android, too. Otherwise Android is the only platform without this feature in Firefox.

**Comment by rafalopilowski1** [comment]
@cadeyrn #19835?
