### ISSUE TITLE
Change the UI for switching tabs

### ISSUE THREAD

**Issue by thewhitetulip** [mozilla-mobile/fenix#4351]
### Why/User Benefit/User Problem
Because current one is not the best way to discuss tabs
### Acceptance Criteria (how do I know when I’m done?)

When it's as easy to change tabs as on chrome/ff on android

**Comment by pampasdev** [comment]
I am not sure about a better way for tab switching but I think Chrome's slide to switch tab is really awesome feature. All you have to do is keep sliding on the URL bar and it will switch between next and previous tabs.

**Comment by thewhitetulip** [comment]
Or even firefox for android's way is better. In this version, you have collections and tabs on the same page. I have 10 collections and even if one of them is expanded, I can't switch tabs

**Comment by topotropic** [comment]
This will be addressed with https://github.com/mozilla-mobile/fenix/issues/1063

**Comment by topotropic** [comment]
Thanks for the feedback, will close this issue, see comment above.
