### ISSUE TITLE
[Bug] Set engine from Shortcuts>Search engine settings doesn't change immediately

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#4354]
## Steps to reproduce
1. Tap the search bar. Tap Shortcuts.
2. Tap Search Engine settings. 
3. Change the default search engine. Return.
4. Type a search and submit.
### Expected behavior
The engine selected at Step 3 is displayed in the search bar. The search is made on the selected engine.
### Actual behavior
The logo in the search bar is not updated immediately, and the search is made with the previous selection.
Closing the search edit mode after the change will update everything accordingly.
### Device information

* Android device: Galaxy S8 (Android 9).
* Fenix version: Nightly 190729

**Comment by ValentinTimisica** [comment]
Hi, this seems interesting. I will start to work on it.

**Comment by AndiAJ** [comment]
Hi, verified as fixed on the latest **Nightly Build #12240720 from 12/8** using the following devices:
• Google Pixel 3a (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• OnePlus A3 (Android 6.0.1)
• LG Nexus (Android 5.1.1)
