### ISSUE TITLE
Unable to add new search engine or edit existing ones

### ISSUE THREAD

**Issue by pampasdev** [mozilla-mobile/fenix#4357]
### Why/User Benefit/User Problem
Currently we cannot add new search engine nor can we edit the existing ones.
### What/Requirements

- User should be able to add new search engines when he clicks on the search box or any text box which supports get request

- User should be able to edit the existing search engines this is useful in case the default search engine is not configured for regional site of search engine.

**Comment by cadeyrn** [comment]
Duplicate of #1437.

**Comment by kbrosnan** [comment]
closing as dupe
