### ISSUE TITLE
[Bug] findBookmarkedUrl blocks the main thread causing ANRs on page loads

### ISSUE THREAD

**Issue by colintheshots** [mozilla-mobile/fenix#4359]
## Steps to reproduce
1. Using a slower device, open Fenix.
2. Press the search button and type a URL.
3. Wait for the URL to load while running SysTrace.

### Expected behavior
The page should load without blocking the main thread or causing an ANR.

### Actual behavior
The page blocks the main thread to query the bookmarks database to check if the current URL is bookmarked. It may even ANR in certain rare cases. According to Google Play, it seems to be our top ANR right now.

### Device information

* Android device: Moto G5
* Fenix version: 1.1.0

**Comment by abodea** [comment]
I did some testing but I couldn't identify any issues:
### Please note the following:
| Device | Internet connection |Status    |
| :---         |     :---:    |     ---: |
| **Samsung Galaxy S10+(Android 9)**   | Wi-Fi   | OK ✅   |
| **Samsung Galaxy S10+(Android 9)**   | Mobile data **2G only**    | OK ✅     |
| **Samsung Galaxy S10+(Android 9)**   | Mobile data **3G only**     | OK ✅     |
| **Samsung Galaxy S10+(Android 9)**   | Mobile data 3G/2G(auto connect)    | OK ✅     |
| **Samsung Galaxy S10+(Android 9)**   | Mobile data LTE/3G/2G(auto connect)    | OK ✅     |
| **Google Pixel 3a XL(Android 9**    | Wi-Fi   | OK ✅      |
| **Google Pixel 3a XL(Android 9**   | Mobile data **2G only**    | OK ✅     |
|**Google Pixel 3a XL(Android 9**    | Mobile data **3G only**     | OK ✅     |
| **Google Pixel 3a XL(Android 9**   | Mobile data 3G/2G(auto connect)    | OK ✅    |
| **Google Pixel 3a XL(Android 9**    | Mobile data LTE/3G/2G(auto connect)    | OK ✅    |
| **OnePlus A3000(Android 6.0.1)**     | Wi-Fi   | OK ✅      |
| **OnePlus A3000(Android 6.0.1)**    | Mobile data **2G only**    | OK ✅    |
|**OnePlus A3000(Android 6.0.1)**   | Mobile data **3G only**     | OK ✅     |
| **OnePlus A3000(Android 6.0.1)**   | Mobile data 3G/2G(auto connect)    | OK ✅      |
| **OnePlus A3000(Android 6.0.1)**    | Mobile data LTE/3G/2G(auto connect)    | OK ✅     |
| **Nexus 4(Android 5.1.1)**     | Wi-Fi   | OK ✅     |
| **Nexus 4(Android 5.1.1)**    | Mobile data **2G only**    | OK ✅    |
|**Nexus 4(Android 5.1.1)**    | Mobile data **3G only**     | OK ✅     |
| **Nexus 4(Android 5.1.1)**    | Mobile data 3G/2G(auto connect)    | OK ✅     |
| **Nexus 4(Android 5.1.1)**     | Mobile data LTE/3G/2G(auto connect)    | OK ✅     |

Note that I tried with the steps from the description + before that to sync.
Also, I tried to reproduce the issue while switching between internet connections but I couldn't reproduce ANRs on page loads.
@colintheshots if you consider ok this verification I can add the QA Verified label.

**Comment by colintheshots** [comment]
Given that the STR cannot be confirmed, we should consider lowering the ANR rate of incidence for this particular stack trace in the field to be success. Monitoring Sentry should show whether it worked. Thanks, @abodea! That was an impressive array of devices to test.

**Comment by boek** [comment]
@colintheshots Looks like this is fixed? Feel free to re-open if there is any follow up needed :)
