### ISSUE TITLE
[Bug] Share screen doesn't indicate it is horizontally scrolling

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/fenix#4360]
See [this tweet](https://twitter.com/followgryph/status/1154700716927266817) for context.

## Steps to reproduce
1. Open a page.
2. Click on the share button.

### Expected behavior
- There should be a bit of the next apps/devices in the horizontally scrolling list to indicate there are more items there. See first screenshot below for example.

### Actual behavior
- There is no indication. See second screenshot for current behaviour.

### Device information

* Android device: Android 9 (Pixel 2)
* Fenix version: 07/29/2019

![screenshot_20190729-160214](https://user-images.githubusercontent.com/1370580/62078532-d4c3b400-b21a-11e9-8099-400aa68e4c6d.png)

![screenshot_20190729-160846](https://user-images.githubusercontent.com/1370580/62078862-8662e500-b21b-11e9-9388-3187ea964e3a.png)

**Comment by Poopooracoocoo** [comment]
also, why a horizontally scrolling share sheet? it's annoying to use and even Windows 10 ditched the horizontal scrolling that Windows 8 introduced.
