### ISSUE TITLE
[Bug] tabs whose title have long non-latin characters expand favicon dimensions

### ISSUE THREAD

**Issue by myakura** [mozilla-mobile/fenix#4370]
## Steps to reproduce

1. open a page with long title containing non-latin characters (e.g. https://www3.nhk.or.jp/news/html/20190729/k10012012571000.html )
2. open another tab which doesn't have that characteristics (e.g. https://www.mozilla.org/ )
3. open a new tab page and look at the favicons of the two

### Expected behavior

favicons have the same dimension and title lines up

### Actual behavior

favicon of tab 1 is slightly larger than that of tab 2, causing title doesn't line up

### Device information

* Android device: Mi A1
* Fenix version:

**Comment by myakura** [comment]
(ugh. GitHub mobile web doesn't have image uploading and Fenix doesn't have switching to desktop option :-( )

here's the screenshot. 
![Screenshot_20190730-091042](https://user-images.githubusercontent.com/413984/62094389-f030cc80-b2b7-11e9-9dfa-378dfc3f1117.png)

**Comment by boek** [comment]
This will be fixed with the new tab tray #1063
