### ISSUE TITLE
The "Report issue" is zoomed when desktop site is requested

### ISSUE THREAD

**Issue by softvision-miralobontiu** [mozilla-mobile/fenix#4371]
@softvision-miralobontiu commented on [Tue Jul 30 2019](https://github.com/mozilla-mobile/reference-browser/issues/851)

### Steps to reproduce
1. Open Reference Browser - three-dot menu - "Report issue"
2. In the opened tab, go to the three-dot menu and turn ON "Request desktop site".

### Expected behavior
- The https://github.com/mozilla-mobile/reference-browser/issues/new is opened in desktop mode.

### Actual behavior
- The https://github.com/mozilla-mobile/reference-browser/issues/new is zoomed in.

### Note
**Also reproducible on Firefox Preview - Nightly build 190730 (#12110609).**

### Device information
* Android device: Motorola Nexus 6 (Android 7.1.1), Huawei P9 Lite (Android 6)
* Reference Browser version: 1.0.1931 (#12101214)

[logcat.txt](https://github.com/mozilla-mobile/reference-browser/files/3445554/logcat.txt)

![20190730](https://user-images.githubusercontent.com/40694158/62108124-e86e2980-b2b1-11e9-9a8d-ad1b7127ef30.gif)

**Comment by sblatz** [comment]
I'm confused. I'm not seeing this in Fenix. Is this a reference browser only issue? @softvision-miralobontiu

**Comment by softvision-miralobontiu** [comment]
No, it is reproducible in Fenix also.
If https://github.com/mozilla-mobile/reference-browser/issues/new is accessed in Fenix, and Desktop site is toggled to ON, the page is zoomed.

**Comment by mcarare** [comment]
This is not reproducible for me anymore. QA can you please check? TY!

**Comment by abodea** [comment]
I re-checked this issue on the latest Nightly 4/16 with Google Pixel 4 XL (10) but I couldn't reproduce the issue.
I believe the `Report site issue` page was changed since the bug was reported and following the steps from the description, the issue cannot be reproduced.
@mcarare @boek removing the `needs:gv` as the issue is no longer reproducible.
