### ISSUE TITLE
[Bug] High risk pages are loaded after a connection interruption 

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#4374]
## Steps to reproduce
1. Turn WIFI off.
2. Load http://testsafebrowsing.appspot.com/s/phishing.html
3. Turn WIFI on. Reload the page.
4. Load http://testsafebrowsing.appspot.com/s/malware.html
### Expected behavior
The malicious websites display an error page blocking the user to access them.
### Actual behavior
The malicious pages are loaded when the WIFI is back. This behavior is kept if you close tabs/reload pages. It will only show the error pages again if you restart the browser.
### Device information

* Android device: Galaxy S8 (android 9)
* Fenix version: Nightly 190739

**Comment by fluffyemily** [comment]
This issue needs a Bugzilla bug.

**Comment by ekager** [comment]
@fluffyemily I don't have much context on this but I opened https://bugzilla.mozilla.org/show_bug.cgi?id=1612782

**Comment by ekager** [comment]
Bugzilla was closed as expected behavior
