### ISSUE TITLE
[Crash] Crashes after deleting open tabs browsing data

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#4376]
## Steps to reproduce
1. Open one or more tabs.
2. Go to Settings>Delete browsing data.
3. Select Open tabs and delete data.
4. Tap back to return to the homescreen.
*Repeat if it doesn't crash on first try.
### Expected behavior
The homescreen is displayed, all tabs are deleted.
### Actual behavior
App crahses when returning to the homescreen.
[galaxy s8 logcat.txt](https://github.com/mozilla-mobile/fenix/files/3446688/galaxy.s8.logcat.txt)
[nexus 5 logcat.txt](https://github.com/mozilla-mobile/fenix/files/3446689/nexus.5.logcat.txt)

### Device information

* Android device: Galax S8(Android 9), Nexus 5 (Android 6.0.1)
* Fenix version: Nightly 190730

**Comment by csadilek** [comment]
@sv-ohorvath great catch! :) We've landed a fix for this today, so it should be fixed in the latest build.

**Comment by sv-ohorvath** [comment]
Doesn't crash on Nightly 190731. Verified on: Pixel (android Q), Galaxy S8 (android 9), Samsung Galaxy Tab A 6 (Android 5.1.1)
