### ISSUE TITLE
[Bug]Rotating the device to landscape while adding a tab to a collection breaks the UI

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#4377]
## Steps to reproduce
1. Long tap on a open tab
2. Rotate device to landscape 
3. Minimize the keyboard

### Expected behavior
No UI issues.

### Actual behavior
The "Name collection" section and the text box are cut of.

### Device information

* Android device: 
• Google Pixel 3a (Android 9 )
• Samsung Galaxy S8 (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)

* Fenix version: Nightly Build #12110609 from 30/7

#### Notes

<details>
    <summary>Pictures & video </summary>

Name collection
![rsz_namecollect](https://user-images.githubusercontent.com/51314259/62130082-e7a0bc00-b2e0-11e9-976d-b4e90dbfba8d.png)

Text box
![rsz_textbox](https://user-images.githubusercontent.com/51314259/62130158-13bc3d00-b2e1-11e9-9c59-7804ffd52e2d.png)

► Video Google Pixel 3a (Android 9) ![20190730_152822](https://user-images.githubusercontent.com/51314259/62129715-0e122780-b2e0-11e9-93bf-281338de608d.gif)

</details>

**Comment by pt2121** [comment]
:hand:
I'm interested in taking a stab at it over the weekend

**Comment by darkwing** [comment]
I cannot reproduce this on Galaxy 4:

<img width="1598" alt="WhatISee" src="https://user-images.githubusercontent.com/46655/74278516-f1b76480-4cde-11ea-9738-8f7b91b4eb33.png">

The textbox displays as it should.

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest `Nightly #20430607 from 2/12 `using the following devices:
• Google Pixel 3a XL (Android 10)
• Google Pixel 3a (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7.0.0)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

► Video
![20200212-100615](https://user-images.githubusercontent.com/51314259/74315342-e8ca9f80-4d7f-11ea-9160-34d3b8348a6b.gif)
