### ISSUE TITLE
[Bug] Search Widget Crash

### ISSUE THREAD

**Issue by jyeontaek** [mozilla-mobile/fenix#4384]
## Steps to reproduce
1. Phone should not have any sort of speech-to-text library installed.
2. Place the search widget in home screen.
3. Press the microphone icon to open the voice search.
### Expected behavior
User should be notified in some way that speech-to-text search is not available.
### Actual behavior
The application crashes.
### Device information

* Android device: Galaxy S9
* Fenix version: ?

**Comment by sblatz** [comment]
@jyeontaek I wonder if we could just hide the microphone if the user doesn't have one enabled. Is that possible?

**Comment by jyeontaek** [comment]
I believe it's possible. However, if the user installs the speech-to-text library and wants the icon to reappear, the user will need to readjust the widget size or wait at least 30 minutes for the app to check if the library is installed.

**Comment by sblatz** [comment]
@jyeontaek That seems fine to me tbh. 30 minutes isn't that long and uninstalling and installing a voice library is probably a rare case.

**Comment by sblatz** [comment]
https://github.com/mozilla-mobile/fenix/issues/4589 includes a stacktrace for this crash.

**Comment by andreicristianpetcu** [comment]
I can't see the microphone but I can't crash it either in latest nightly.

**Comment by abodea** [comment]
Verified as fixed in `Fenix 1.3.0-rc.3` with `Samsung Galaxy S10+(Android 9).`
Please note that the microphone wasn't displayed once the text-to-speech libraries were disabled/uninstalled.
No crash, everything worked as expected.
