### ISSUE TITLE
Search Widget feature discoverability through LeanPlum

### ISSUE THREAD

**Issue by jyeontaek** [mozilla-mobile/fenix#4386]
### Why/User Benefit/User Problem
As a user, it would be nice to know that Firefox Preview has a search widget available for use.

From the experimental perspective, we will add a basic search widget to Fenix that is discoverable by a segment of existing users (through LeanPlum) and collect usage data.
### What/Requirements
1. User can add the Fenix search widget to their home screen by one of the following: 
- From Fenix action shortcuts 
- Android Widget Menu
- By clicking on the just-in-time toast (first time they open the browser after an update)

2. In-app toast to add widget (LeanPlum)
3. Deep link to add widget intent
4. LeanPlum Event to indicate user has added the widget
5. Telemetry probe (unique source value) for the widget to be able to measure search initiated from the widget

**Comment by brampitoyo** [comment]
I wonder if we can deeplink to the add widget UI from a screen in the app?

For example: under Settings → Search, we can have a link that says:

> **Add search widget**
> One tap to search from the home screen

**Comment by vesta0** [comment]
Let's continue the discussion here: #9488
