### ISSUE TITLE
[Bug] Sign in to see bookmarks button not visible in landscape

### ISSUE THREAD

**Issue by ekager** [mozilla-mobile/fenix#4389]
The best solution I think is to make the Button an adapter item ViewHolder in the RecyclerView like History has.

## Steps to reproduce
1. Have more than 1 screen of bookmarks and don't be signed in
2. Turn device to landscape

### Expected behavior
Can scroll to end of bookmark list and still see button

### Actual behavior
Sign in to see bookmarks button cut off in landscape

### Device information

* Android device: ?
* Fenix version: ?

**Comment by AndiAJ** [comment]
Hi @ekager , I wasn't able to reproduce the above described issue on **Nightly Build #12112106** **from 30/7** using the following devices:
• Google Pixel 3a (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)

No issues regarding the Bookmarks button in landscape mode with or without being signed in.
I would kindly ask you to help us with a screen shot or a video to have a better overview of the problem. :)
