### ISSUE TITLE
Create LibState Controller for Bookmarks

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#4396]
We should create a controller for Bookmarks 

See `BrowserToolbarController.kt` (from #4279) for a good example or reach out to @sblatz or @csadilek for more clarification on the separation of responsibilities.

Note: this ticket also includes creating **tests** for this controller.

**Comment by Mugurell** [comment]
Isn't this the same as #4128 ?

**Comment by sblatz** [comment]
@Mugurell No, each libstate needs a controller too. This is specifically addressing that portion.

**Comment by AndiAJ** [comment]
Hi @boek , could you please let us know if we should run a smoke test on bookmarks ? or how should we test this issue?

**Comment by AndiAJ** [comment]
Hi @sblatz , while testing I've bumped into 3 new issues namely:
Multi-select deletion issues #4991 #4993 
Crash #4994 

Could these be related to the creation of the LibState controller?

**Comment by Mugurell** [comment]
> Could these be related to the creation of the LibState controller?

These are all reproducible on older builds which do not contain this patch, like [this one from Aug 17](https://treeherder.mozilla.org/#/jobs?repo=fenix&revision=d1aed157dd1836b001eaa0801cdf7b01b8839200&selectedJob=262089303).

**Comment by AndiAJ** [comment]
@Mugurell true story and thanks for your help! :)
No regressions found and based on this I'll mark this ticket **verified**
