### ISSUE TITLE
Create LibState Controller for History

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#4398]
We should create a controller for History

For #4395

See `BrowserToolbarController.kt` (from #4279) for a good example or reach out to @sblatz or @csadilek for more clarification on the separation of responsibilities.

Note: this ticket also includes creating **tests** for this controller.

**Comment by dragneelfps** [comment]
@Mugurell are you working on this ?

**Comment by Mugurell** [comment]
> @Mugurell are you working on this ?

I started to but if you want to work on it and are confident about the result I can reassign this to you.

**Comment by dragneelfps** [comment]
@Mugurell yes I would love to do it.

**Comment by dragneelfps** [comment]
Created PR #4837 for this.
