### ISSUE TITLE
Create LibState Controller for QuickSettings

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#4400]
We should create a controller for QuickSettings

For #4395

See `BrowserToolbarController.kt` (from #4279) for a good example or reach out to @sblatz or @csadilek for more clarification on the separation of responsibilities.

Note: this ticket also includes creating **tests** for this controller.

**Comment by sblatz** [comment]
Let's wait on this one until our ETP is merged in.

**Comment by NotWoods** [comment]
Should be fixed with the QuickSettingsFragmentStore
