### ISSUE TITLE
[Bug] No bookmark folder names in edit mode

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#4407]
## Steps to reproduce
1. Edit a bookmark or a bkm folder.
2. Tap the parent folder to choose a folder.
3. Observe the folders list.
### Expected behavior
Folders have names.
### Actual behavior
Folder names are not displayed
### Device information

* Android device: Galaxy S8 (Android 9), Samsung Galaxy Tab A 6 (Android 5.1.1)
* Fenix version: Nightly 190731

**Comment by ekager** [comment]
Ah this was fixed by #4464
