### ISSUE TITLE
[Bug] The tracking protection icon in Settings has the wrong color

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#4408]
## Steps to reproduce
1. Go to Settings
2. Observe the TP icon in the Settings panel and inside the TP setting panel.
### Expected behavior
The icon is black like the rest. 
### Actual behavior
The icon is light gray.
### Device information

* Android device: Nexus 5 (Android 6.0.1), Galaxy S8 (Android 9)
* Fenix version: Nightly 190731 (not reproducing on 7/30)

**Comment by jawadalkassim** [comment]
New icon is ugly with the the line btw, don't change Tracking Protection icon.

**Comment by ekager** [comment]
This should be fixed!
