### ISSUE TITLE
[Bug] Sending tabs between Fenix and Fennec doesn't work, the device list doesn't show the other app

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#4409]
## Steps to reproduce
1. Login with the same account on Fenix & Fennec (and desktop to check that they are connected).
2. Open a web page in Fenix and check the devices in Send to device.
3. Open a page in Fennec and tap Share>Send to other devices. Check the devices list.
### Expected behavior
Both show the devices connected in the other app. Can send tabs between the apps.
### Actual behavior
The devices connected in Fennec don't show up in Fenix and vice-versa. 
Each show only the devices with the same app.
Both show the desktop app.
Both appear as connected on desktop. 
Bookmarks and history sync works between them.
### Device information

* Android device: Galaxy S8 (Android 9), Nexus 5 (android 6.0.1)
* Fenix Nightly 190731, Fennec Nightly 68.1a1, Firefox Release 68.0.

**Comment by jonalmeida** [comment]
Unfortunately we don't support sending tabs to Fennec or vice-versa only To desktop and iOS.

**Comment by sv-ohorvath** [comment]
> Unfortunately we don't support sending tabs to Fennec or vice-versa only To desktop and iOS.

Ah, I wasn't aware of that. I can close this then. Thanks!
