### ISSUE TITLE
[Bug] Disable "Add tab" from the Collections section if there are no open tabs

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#4410]
## Prerequisites
Have a Collection created and no open tabs.

## Steps to reproduce
1. Tap the 3dot button from the created collection
2. Tap "Add tab"

### Expected behavior
Since there are no open tabs to be added to the existing collection, the "Add tab" button shouldn't be active or available.

### Actual behavior
After tapping the "Add tab" button, the Tabs Selection list pops up containing an empty list. 

### Device information

* Android device: Google Pixel 3XL (Android 9)
* Fenix version:  Nightly Build #12112106 from 31/7

#### Notes

► Video
![20190731_160526](https://user-images.githubusercontent.com/51314259/62215505-c5c23a80-b3af-11e9-969a-ae0e5f9c2e2f.gif)

**Comment by ekager** [comment]
Reopening for QA

**Comment by softvision-miralobontiu** [comment]
Verified as fixed on a locally build from 8/5 master with LG G7 Fit (Android 8), and Sony Xperia Z5 Premium (Android 7.1.1).
