### ISSUE TITLE
[Bug] Tabs sent to Google Pixel 3 are opened in Chrome

### ISSUE THREAD

**Issue by softvision-miralobontiu** [mozilla-mobile/fenix#4411]
## Steps to reproduce
1. Sign in with your account on two devices, one of them should be Google Pixel 3 (Android 9).
2. Send a tab from one device to another.

### Expected behavior
A notification is displayed, with the sent tab. When the notification is tapped, the sent tab is opened in Firefox Preview.

### Actual behavior
A notification is displayed, with the sent tab. When is tapped, the sent tab is opened in Chrome.

### Device information
* Android device: Google Pixel 3 (Android 9)
* Fenix version: Nightly 190731 (#12120612)

[logcat.txt](https://github.com/mozilla-mobile/fenix/files/3452087/logcat.txt)

![20190731_Trim](https://user-images.githubusercontent.com/40694158/62216669-dbd0fa80-b3b1-11e9-895f-2ee57c3eae46.gif)

**Comment by jonalmeida** [comment]
If your default browser is Chrome then this is expected behaviour.

**Comment by softvision-miralobontiu** [comment]
Thanks! After I set Firefox Preview as default, the sent tabs are opened in Firefox Preview.
I will close this.
