### ISSUE TITLE
[Bug] lateinit property browserInteractor has not been initialized

### ISSUE THREAD

**Issue by csadilek** [mozilla-mobile/fenix#4412]
We have a new crash in Sentry for the latest changes in `BrowserFragment`: https://sentry.prod.mozaws.net/operations/fenix-nightly/issues/6102361/

**Comment by sv-ohorvath** [comment]
Do we have any STR for this crash?

**Comment by csadilek** [comment]
@sv-ohorvath the STR for this one are actually the same as for https://github.com/mozilla-mobile/fenix/issues/4376. 

Another way to potentially hit it is to put the app in the background while a tab is open, use the device heavily and resume later. This would have also crashed it if the system freed up memory and we need to read the sessions from disk again. There's also a follow-up commit here which is about to land in Nightly and 1.2 (we didn't capture all potential crashes in the first commit).

Note that there's also https://github.com/mozilla-mobile/fenix/issues/4427 which we'll address later.

**Comment by sv-ohorvath** [comment]
No crash following the STR on RC 1.2-rc.
Devices: Galaxy S8 (Android 9) & Xiaomi Mi Pad 2 (Android 5.1) .
