### ISSUE TITLE
Approach the UI to the one of Firefox android and Firefox Focus android

### ISSUE THREAD

**Issue by 1known** [mozilla-mobile/fenix#4415]
Firefox for android currently has a better UI along with Firefox Focus, compared to Firefox Preview. Not only Preview feels cluttered and full of intrusive elements, the url bar on bottom makes things worse. 

Simpler and cleaner interface similar to the one of Firefox Focus and Firefox for Android

**Comment by vesta0** [comment]
Thanks for filing! We will address this in user research.
