### ISSUE TITLE
Generate notifications when UI tests fail on master

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#4418]
We should generate a notification and potentially automatically back out changes that fail UI tests on master.

**Comment by mitchhentges** [comment]
This sounds valuable! sblatz and I talked directly on Slack and clarified that:
* Ideally, this notification is a slack message for the team, perhaps pinging people as well
* This notification should only occur the first time the UI tests fail after having passed. So, if multiple `master` pushes happen that are all failing UI tests, the team should only be notified on the first failure.

A couple of notes:
* AFAIK, RelEng has tooling set up for sending emails, but not slack messages at the moment. Perhaps we should set up emailing as a stop-gap, then set up Slack in the future?
* Since we don't want to re-notify subsequent failed UI tests, we need to track them over time. @JohanLorenzo, do we have any tooling for that kind of status tracking?

**Comment by sblatz** [comment]
Let's not start on this *just yet*. I think it's important that explore the option of UI tests being a requirement for merging before we tackle this. I'll update this ticket when I have a final decision on that 😄

**Comment by JohanLorenzo** [comment]
Hey! I agree we should have a way to let people know a breakage happened and to track what happened over time.

To me, email notifications work in the short run, then people get used to it and they get ignored. This is exactly what happened with Raptor on Fenix over the past couple of months. The main reason was: it's hard to tell who's the right person to contact/what's the right process to follow. To me, someone has to first have a look at the logs to know the class of failure and report it to the right people. cc @jmaher @davehunt @rwood-moz 

We have treeherder set up already: https://treeherder.mozilla.org/#/jobs?repo=fenix. Let's do what we do on Fennec and Firefox desktop: have a sheriff team look at the result and ping the right people when it breaks.

I just noticed the UI jobs don't report on Treeherder https://github.com/mozilla-mobile/fenix/blob/master/automation/taskcluster/lib/tasks.py#L196-L205. @rpappalax, would you mind having these jobs report there? 

@jlund, who would be the point of contact to ask what the sheriffs think about covering Fenix?

**Comment by jmaher** [comment]
Personally I would vote for the Fenix developers to own the role of first
responders.  If this project were in mozilla-central there would be built
in sheriffs, instead we are asking engineers from the perf team to be
sheriffs for breakage.  Historically teams that decide to go their own way
on github have managed all their own test jobs, sheriffing, etc.

**Comment by rpappalax** [comment]
> Hey! I agree we should have a way to let people know a breakage happened and to track what happened over time.
> 
> To me, email notifications work in the short run, then people get used to it and they get ignored. This is exactly what happened with Raptor on Fenix over the past couple of months. The main reason was: it's hard to tell who's the right person to contact/what's the right process to follow. To me, someone has to first have a look at the logs to know the class of failure and report it to the right people. cc @jmaher @davehunt @rwood-moz
> 
> We have treeherder set up already: https://treeherder.mozilla.org/#/jobs?repo=fenix. Let's do what we do on Fennec and Firefox desktop: have a sheriff team look at the result and ping the right people when it breaks.
> 
> I just noticed the UI jobs don't report on Treeherder https://github.com/mozilla-mobile/fenix/blob/master/automation/taskcluster/lib/tasks.py#L196-L205. @rpappalax, would you mind having these jobs report there?
> 
> @jlund, who would be the point of contact to ask what the sheriffs think about covering Fenix?

I have a PR for this, but could use a little help from taskcluster team: 
https://github.com/mozilla-mobile/fenix/issues/4890
https://github.com/mozilla-mobile/fenix/pull/4891

**Comment by sblatz** [comment]
I'm closing this as it's no longer necessary now that UI tests run as a requirement on PR's.
