### ISSUE TITLE
[Bug] publicSuffixList.prefetch() should not block

### ISSUE THREAD

**Issue by hawkinsw** [mozilla-mobile/fenix#4425]
Currently we believe this method is reducing perf during startup: we should mitigate it.

## Acceptance Criteria
- See if this is reducing perf during startup. If not, deprioritize this issue
- Refactor `PublicSuffixList` so that `prefetch()` is not blocking (consider wrapping in `async { }`)

---

cc @csadilek @jonalmeida 

See #4420

**Comment by jonalmeida** [comment]
Some notes from an offline conversation:

Some concerns with moving the prefetch to run async, was that we may fire an async prefetch at startup, and entering a search term in  the search bar would trigger another prefetch for the `isUrl` check.

What we can try, is to put a [LazyThreadSafetyMode.SYNCHRONIZED][0] on the [PublicSuffixListData][1] class to ensure we only have sync access on the lazy data list.

Alternatively, a `Executors.newSingleThreadExecutor()` may work, but I'm unsure if access through kotlin is still sequential or any other overhead. 


[0]: https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/-lazy-thread-safety-mode/index.html
[1]: https://searchfox.org/mozilla-mobile/source/android-components/components/lib/publicsuffixlist/src/main/java/mozilla/components/lib/publicsuffixlist/PublicSuffixList.kt#31

**Comment by jeanygong** [comment]
> Some notes from an offline conversation:
> 
> Some concerns with moving the prefetch to run async, was that we may fire an async prefetch at startup, and entering a search term in the search bar would trigger another prefetch for the `isUrl` check.
> 
> What we can try, is to put a [LazyThreadSafetyMode.SYNCHRONIZED](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/-lazy-thread-safety-mode/index.html) on the [PublicSuffixListData](https://searchfox.org/mozilla-mobile/source/android-components/components/lib/publicsuffixlist/src/main/java/mozilla/components/lib/publicsuffixlist/PublicSuffixList.kt#31) class to ensure we only have sync access on the lazy data list.
> 
> Alternatively, a `Executors.newSingleThreadExecutor()` may work, but I'm unsure if access through kotlin is still sequential or any other overhead.

@jonalmeida Is there some follow up or action you need from the Performance team on this issue or is this is something that will be addressed on the Fenix engineering side?

**Comment by jonalmeida** [comment]
> @jonalmeida Is there some follow up or action you need from the Performance team on this issue or is this is something that will be addressed on the Fenix engineering side?

@hawkinsw mentioned that he wanted to look into the performance gains that would come making the prefetch async so I added the relevant labels on to the issue (maybe I got them wrong?).

The recommendations are from a conversation we were having while unblocking the Fenix team.

**Comment by emalysz** [comment]
publicSuffixList.prefetch() accounts for 0.19% of onCreate() for the Home Activity (1.43 ms), so it does not seem like an immediate concern

**Comment by mcomella** [comment]
Closing: we're addressing startup holistically and this doesn't appear to be a big concern.
