### ISSUE TITLE
[Bug] Resuming from BrowserFragment might land user on HomeFragment

### ISSUE THREAD

**Issue by csadilek** [mozilla-mobile/fenix#4427]
This is not a regression, but we have a bug / design issue here. If the OS decides to free up memory, before the app is resumed, users will end up on the `HomeFragment` instead of the `BrowserFragment`.

The reason is a race condition between restoring sessions from disk (which for performance reasons is done on an IO thread in Fenix) and creating the `BrowserFragment`. By the time the fragment's `onViewCreated` is executed, the sessions might not yet be restored. Without a session, the `BrowserFragment` will simply render as a white screen, which likely prompted the workaround described in https://github.com/mozilla-mobile/fenix/issues/4387 (to move on to the `HomeFragment`)?

One possible solution is to observe `onSessionsRestored` or better `onSessionSelected` in `BrowserFragment` and update the UI, but this needs more investigation.

### Edit by Sawyer
Let's also fix this as part of this ticket (originally filed as #4387)
> In `BrowserFragment` we're currently popping the fragment browser fragment if there's no current session. We should clean this up to never navigate to the browser fragment if possible.
This happens in this case: #4376
```if (getSessionById() == null) findNavController(this).popBackStack(R.id.homeFragment, false)```

**Comment by sblatz** [comment]
This is pretty critical to fix--we ran into a lot of crashes with this, and though we were able to cover up the symptoms, we should fix the underlying problem :)

**Comment by ekager** [comment]
@colintheshots how would QA test this? Is there a known STR to how this would happen?

**Comment by csadilek** [comment]
@ekager we used the following STR (on a Nexus 5X) when implementing/testing this:

- Load youtube.com and start a video
- Switch to the camera app
- Switch back to Fenix

Expected
- BrowserFragment (youtube.com tab) visible

Actual
- HomeFragment visible

So, with the fix we now properly land on the `BrowserFragment` and load youtube.com (where we left off).

**Comment by AndiAJ** [comment]
Hi, verified as fixed on the latest **Nightly Build #12240720 from 12/8** using the following devices:
• Google Pixel 3a (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• OnePlus A3 (Android 6.0.1)
• LG Nexus (Android 5.1.1)
