### ISSUE TITLE
Need to scroll up to see search suggestions/autocompletes 

### ISSUE THREAD

**Issue by topotropic** [mozilla-mobile/fenix#443]
## Steps to reproduce
search for something; look at search suggestions

### Expected behavior
first search suggestions start below search field

### Actual behavior
you need to scroll up to see first search suggestions/autocompletes 

### Device information

* Android device: Pixel 3 XL
* Fenix version:

**Comment by boek** [comment]
PR: https://github.com/mozilla-mobile/android-components/pull/1933

**Comment by Sdaswani** [comment]
Yeah I saw this too https://photos.app.goo.gl/qbX9gxUbfp47KbQJ6

**Comment by boek** [comment]
This is now working for me!

**Comment by sv-ohorvath** [comment]
Verified as fixed on Pixel. Build: master 3/11.
