### ISSUE TITLE
Integrate feature-media component

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/fenix#4431]
The AC work is tracked by the following board (issues above "MVP Boundary" cards):
https://github.com/orgs/mozilla-mobile/projects/26

Integrating this component will bring the following features to Fenix:
- Background playback without the app getting killed
- Media notification with play/pause controls
- Audio Focus handling (pausing/resuming in agreement with other media apps)
- Support for hardware controls to toggle play/pause (e.g. buttons on a headset)

This will fix at least the following Fenix issues:
- #2551 
- #1008
- #1113 
- #1753

**Comment by vesta0** [comment]
The integration has been completed.

**Comment by colintheshots** [comment]
My mistake. The sub-issues were verified by QA.
