### ISSUE TITLE
[Bug]Delete all history or individual history items snackbar missing

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#4432]
## Prerequisites
Have a couple of history items

## Steps to reproduce
1. Navigate to History
2. Tap 3dot button from any History item tap Delete from the overflow menu
3. Tap the upper " Delete history " button and tap clear

### Expected behavior
As per #2025 a delete confirmation dialuge was created for deleting Deleting all history.
In both cases a snack bar should be displayed confirming the deletion and an "Undo" button

### Actual behavior
Nothing is displayed after performing the deletion

### Device information

* Android device: Google Pixel 3XL (Android 9)
* Fenix version: 
• Nightly Build #12130027 from 1/8
• RC 1.2.0-rc.1 from 1/8

**Comment by abodea** [comment]
#2025

**Comment by AndiAJ** [comment]
**Not reproducible** anymore on the latest **`Nightly Build 201117`** using the following devices:
• Google Pixel 3a (Android 11)
• Huawei Mate 20 Lite (Android 10)
• OnePlus A3 (Android 6.0.1)
