### ISSUE TITLE
[Bug] Opening the support page from Help doesn't display the correct URL in the URL bar

### ISSUE THREAD

**Issue by softvision-miralobontiu** [mozilla-mobile/fenix#4433]
## Steps to reproduce
1. Open a random page.
2. Go to Settings - Help.
3. Observe the URL bar.

### Expected behavior
The URL should be https://support.mozilla.org/en-US/products/firefox-preview. 

### Actual behavior
The https://support.mozilla.org/en-US/products/firefox-preview is opened, but in the URL bar, the link from step 1 is displayed, even if you reload the page.

### Device information
* Android device: Motorola Moto G6 (Android 8), Huawei P9 Lite (Android 6)
* Fenix version: RC 1.2.0-rc.1 (#12130445)

[logcat.txt](https://github.com/mozilla-mobile/fenix/files/3455937/logcat.txt)

![20190801_Trim](https://user-images.githubusercontent.com/40694158/62282412-31f87900-b458-11e9-9e6a-f32470a15f01.gif)

**Comment by liuche** [comment]
Closing in favor of #4767
