### ISSUE TITLE
[Bug] [a11y] Delete Tab icon from collections is too small

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#4434]
## Prerequisites
You have a collection with a couple of tabs saved.
You have Talkback option enabled from your Android settings.

## Steps to reproduce
1. Expand the collection
2. Tap the 'x'(close) sign for a tab saved in that collection

### Expected behavior
The sign can be easily tapped

### Actual behavior
Difficult to tap it because of its size, could make an improvement as per #4221.

### Device information

* Android device: Google Pixel 3XL (Android 9)
* Fenix version:  RC 1.2.0-rc.1 from 1/8

**Comment by Djfe** [comment]
I agree, it's also not just the close button, but the text and the icon are smaller too, even though the overall size of the tab entry is the same.
![644364412](https://user-images.githubusercontent.com/5685512/62618393-62d32500-b914-11e9-8d75-f11db97dabd2.png)

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on **1.3.0-rc.1** using a Huawei Media Pad M3 Lite 10 (Android 7)

**Comment by softvision-miralobontiu** [comment]
Also verified as fixed on RC 1.3.0-rc.3 with Xiaomi Mi 8Lite (Android 9).

**Comment by Djfe** [comment]
should I open a new issue for the stuff I mentioned? because that's not fixed, yet.

**Comment by sblatz** [comment]
@Djfe yes, please open a separate ticket if you're still having issues :)
