### ISSUE TITLE
[Bug]The Account subsection is not aligned with the others subsections from Settings.

### ISSUE THREAD

**Issue by sv-sdeiac** [mozilla-mobile/fenix#4440]
## Prerequisites
Make sure you are logged on a valid account

## Steps to reproduce
1. Open settings;
2. Watch the alignment of the Account subsection;

### Expected behavior
The Account subsection is aligned with the other subsections;

### Actual behavior
The icon, name and email are not aligned with the other subsections;
### Device information

* Android device: Nexus 9 (Android 7.1.1)
* Fenix version: 1.2.0-rc.1 Thursday 8/1

### Notes
- photo:
![aligned](https://user-images.githubusercontent.com/40264165/62291891-b73a5880-b46d-11e9-90f4-67d5569491a3.png)

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest Nightly Build #12400613 from 28/8 using the following devices:

## Phones
• Google Pixel 3a (Android 9)
• Huawei Mate 20 lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

## Tablets
• Samsung Galaxy Tab A (Android 9)
• Nexus 9 tab (Android 7.1.1)
• Huawei MediaPad M3 Lite 10 (Android 7)
• Samsung Galaxy Tab Active (Android 5.1.1)

►Pics from Samsung Galaxy Tab A

![rsz_normal](https://user-images.githubusercontent.com/51314259/63854170-3b1c2d80-c9a5-11e9-9f67-0695cba2dd33.jpg)
![rsz_land](https://user-images.githubusercontent.com/51314259/63854204-4cfdd080-c9a5-11e9-8e5f-3dfcf6f2934d.jpg)
