### ISSUE TITLE
[Bug] History multi-select issue

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#4441]
## Prerequisites
Have some history

## Steps to reproduce
1. Navigate to the "History" section from "Your Library"
2. Long tap on the first history item
3. Tap on the other history items
4. Tap again on the first item
5. Tap again on the rest of the history items

### Expected behavior
Selection animation should be properly displayed next to the selected items

### Actual behavior
The animation not working properly.
The only way to actually know the number of items selected is by the top control bar.

### Device information

* Android device: 
• Xiaomi Mi Pad 2 (Android 5.1) 
• Nexus 9 (Android 7.1.1)
• Motorola Moto G6 (Android 8)
• Google Pixel 3a (Android 9)

* Fenix version: 1.2.0-rc.1 

### Notes
►Video Google Pixel 3a
![20190801_160228](https://user-images.githubusercontent.com/51314259/62296688-464c6e00-b478-11e9-82d5-b91939d8f64d.gif)

**Comment by sv-ohorvath** [comment]
Verified as fixed on Rc1.2-rc2.
