### ISSUE TITLE
[Bug] Deleting bookmarks is not working

### ISSUE THREAD

**Issue by softvision-miralobontiu** [mozilla-mobile/fenix#4444]
## Steps to reproduce
1. Make sure you have some bookmarks and some folders in the Library.
2. Delete one or more bookmarks.
3. Observe the Bookmark page.

### Expected behavior
The deleted bookmarks should not be displayed anymore.

### Actual behavior
The deleted bookmarks are displayed again. 
Even after the UNDO snack-bar disappeared, it still reproduced.

### Device information
* Android device: Motorola Moto G6 (Android 8)
* Fenix version: RC 1.2.0-rc.1 (#12130445)

[logcat.txt](https://github.com/mozilla-mobile/fenix/files/3457152/logcat.txt)

![20190801_171003](https://user-images.githubusercontent.com/40694158/62301046-8283cc80-b480-11e9-9e00-9d5b6290e9ec.gif)

**Comment by boek** [comment]
This bug exists in 1.1

**Comment by sv-ohorvath** [comment]
similar to https://github.com/mozilla-mobile/fenix/issues/3967 which didn't reproduce at the time if you waited for the snackbar to disappear.

**Comment by softvision-miralobontiu** [comment]
Still reproducing the issue with the latest Nightly build 10/9 with Samsung Galaxy Note 8 (Android 9).

**Comment by softvision-miralobontiu** [comment]
This issue is reproducible on the latest Nightly build from 11/29 on Huawei MediaPad M2 (Android 5.1.1).

**Comment by softvision-miralobontiu** [comment]
I could not reproduce this issue lately. Verified on RC 84.1.0-rc.2, on Beta 84.0.0-beta.4, and 12/11 Nightly with Samsung Galaxy Tab S6 (Android 10).
