### ISSUE TITLE
Sync pinned tabs into a collection automatically

### ISSUE THREAD

**Issue by dbolter** [mozilla-mobile/fenix#4446]
### Why/User Benefit/User Problem
Users might want pinned tabs handy on their mobile device.

### What/Requirements
When a user syncs their laptop pinned tabs are synced to an appropriately named collection in fenix.

### Acceptance Criteria (how do I know when I’m done?)
Pinned tabs sync with a fenix collection.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-12853)

**Comment by Djfe** [comment]
this sounds more like a workaround to me to make them accessible in Fenix.
I would prefer actual pinned tabs with an active session that allows notifications from these tabs.

**Comment by jonalmeida** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1810651

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
