### ISSUE TITLE
[Bug] The History share icon and menu are not displayed on toolbar

### ISSUE THREAD

**Issue by softvision-miralobontiu** [mozilla-mobile/fenix#4448]
## Steps to reproduce
1. Make sure you have some history.
2. Select multiple entries from Library-History and try to share them from the toolbar.

### Expected behavior
The user should be able to share the selected entries.

### Actual behavior
The share icon and the menu are not displayed in the toolbar.

### Device information
* Android device: Motorola Moto G6 (Android 8)
* Fenix version: RC 1.2.0-rc.1

[logcat.txt](https://github.com/mozilla-mobile/fenix/files/3457368/logcat.txt)

![20190801_Trim](https://user-images.githubusercontent.com/40694158/62304971-b57d8e80-b487-11e9-9c44-2d0d476f214a.gif)

**Comment by boek** [comment]
I think this was fixed, could it possibly be device specific? Please check again with the RC2

**Comment by softvision-miralobontiu** [comment]
I was not able to reproduce it on RC 1.2.0-rc.2 build, with Motorola Moto G6 (Android 8).
