### ISSUE TITLE
Ship Fenix x86_64 builds

### ISSUE THREAD

**Issue by cpeterso** [mozilla-mobile/fenix#445]
We need to publish 64-bit builds to the Google Play Store before Google's August 1 deadline requiring 64-bit support (for apps that include native code).

https://android-developers.googleblog.com/2019/01/get-your-apps-ready-for-64-bit.html

It looks like Fenix is only shipping 32-bit ARMv7 and x86 builds:
https://github.com/mozilla-mobile/fenix/blob/19dd46863980808c0832cd8172a33d36b1ac29d0/.taskcluster.yml#L92-L93

GeckoView publishes [x86_64 builds in Maven](https://maven.mozilla.org/?prefix=maven2/org/mozilla/geckoview/geckoview-nightly-x86_64/), _but_ we haven't actually shipped x86_64 builds to Fennec Nightly users yet. I'm working with Releng and Relman to ship x86_64 Fennec Nightly by the end of this week.

Fenix will need to ship x86_64 builds by Google's August 1 deadline (or take down our 32-bit x86 builds), but I recommend that you wait for Fennec Nightly users to dogfood x86_64 for a couple weeks before shipping x86_64 Fenix builds. The beginning of Fenix M3 (March) would probably be a good time.

(For shipping ARM64 Fenix builds, see issue #444.)

**Comment by vesta0** [comment]
Will wait a few weeks for Fennec Nightly users to test this. 1.5% of Fennec users have it.

**Comment by cpeterso** [comment]
@vesta0 and @pocmo - Fennec Nightly has been shipping x86_64 builds since February 13 ([Fennec bug 1505538](https://bugzilla.mozilla.org/show_bug.cgi?id=1505538#c8)) without any big problems. Thus Fenix and R-B can start shipping x86 and x86_64 builds whenever you like, so I am removing this issue's `blocked` label.

Admittedly, we don't have many x86 or x86_64 Fennec Nightly users. Based on telemetry, Fennec Nightly's architecture split is:
```
71.24% ARM64
27.95% ARM 32-bit
 0.76% x86 32-bit
 0.04% x86_64
```

**Comment by cpeterso** [comment]
Fenix x86_64 will need support from Application Services:
https://github.com/mozilla/application-services/issues/426

**Comment by cpeterso** [comment]
Removing `Needs GV work` label because x86_64 builds of GV already exist:
https://maven.mozilla.org/?prefix=maven2/org/mozilla/geckoview/geckoview-nightly-x86_64/

**Comment by kbrosnan** [comment]
This is done.

**Comment by cpeterso** [comment]
@kbrosnan When were Fenix x86_64 builds first available? I don't see them in the Google Play Store. For yesterday's Fenix and Reference Browser releases (both version 1.0.1918), I see only APKs for armeabi-v7a, arm64-v8a, and x86. Maybe we're building the x86_64 APKs but not uploading them to the Play Store yet?
