### ISSUE TITLE
total_uri_count should be added to the metrics ping

### ISSUE THREAD

**Issue by boek** [mozilla-mobile/fenix#4456]

**Comment by AndiAJ** [comment]
Hi, I've just checked  on the latest Nightly Build #13040608 from 31/10 using a Google Pixel 3a XL (Android 9) and noticed the following:

• Performed 3 searches
The baseline ping 294b7f7a-c381-483f-b7b8-9cdcc0a3a1c0 shows "events.total_uri_count": 4
The metrics ping shows bb9612e8-a4c9-4e85-9cee-caebc871798a shows "metrics.total_uri_count": "0"
[Logcat](https://github.com/mozilla-mobile/fenix/files/3794365/3searches.txt)
[Glean dashboard](https://debug-ping-preview.firebaseapp.com/pings/aj-test311002)

• Performed 6 searches
The baseline 6b6cf012-661e-4fd3-b505-452b8565a0cc ping shows "events.total_uri_count": 7
The metrics ping shows 5f94bcc1-9239-4ed9-bb99-57c3750d1330 shows "metrics.total_uri_count": "0"
[Logcat](https://github.com/mozilla-mobile/fenix/files/3794366/6searches.txt)
[Glean Dashboard](https://debug-ping-preview.firebaseapp.com/pings/aj-test311003)

@sblatz please help me out with the following:
Why is the total_uri_count = to the numer of searches + 1? in both cases
Why the "metrics.total_uri_count" isn't displayed in the logs from Android Studio?

To generate the metrics ping I've force stopped Fenix, set the date to T+1 (01/11) and set the time to 03:59AM.  At around 4AM the metrics ping is generated and sent.
Based on the "client_id" & the "first_run_date" in both cases the metrics is properly generated.

Please review the above. :blush:
I'll remove the QA needed label until further clarifications.

**Comment by sblatz** [comment]
>  Why is the total_uri_count = to the numer of searches + 1? in both cases

I think @Baron-Severin may be able to answer this better?

> Why the "metrics.total_uri_count" isn't displayed in the logs from Android Studio?

Investigating this one.

**Comment by Baron-Severin** [comment]
> > Why is the total_uri_count = to the numer of searches + 1? in both cases
> 
> I think @Baron-Severin may be able to answer this better?

I don't actually have any context on this one.  I noticed [a related bug](https://github.com/mozilla-mobile/fenix/issues/6126), but don't know anything else about this ping.

**Comment by sblatz** [comment]
@boek maybe? I think he was the one who added this :)

**Comment by sblatz** [comment]
I have addressed "metrics.total_uri_count": being 0 and marking this ready for qa needed again.

I'm not sure why the total_uri_count is one plus the search number, though. We can address that in another ticket?

**Comment by AndiAJ** [comment]
Hi, I've just re-tested on Nightly Build #13160607 from 12/11 using a Google Pixel 3a XL (Android 9) phone and learned the following:

Performed 3 searches and generated the metrics ping:
"metrics.total_uri_count": "4"

Performed 6 searches and generated the metrics ping:
"metrics.total_uri_count": "7"

[Logcat](https://github.com/mozilla-mobile/fenix/files/3836327/metric.uri.txt)
[Glean dashboard](https://debug-ping-preview.firebaseapp.com/pings/aj-test121100)

@sblatz I think we should first try to solve the mystery behind #6499 from the baseline pings and afterwards re-test this matter.
Please share your thoughts on this. :relaxed:

@Dexterp37 -  While testing this matter I've noticed that `"metrics.total_uri_count": ` is displayed only when checking the metrics pings in the Glean dashboard and not in the logcat from Android Studio. 
Do you know why is this happening? :relaxed:

I'll remove the QA needed label until further clarifications.

**Comment by Dexterp37** [comment]
> @Dexterp37 - While testing this matter I've noticed that `"metrics.total_uri_count": ` is displayed only when checking the metrics pings in the Glean dashboard and not in the logcat from Android Studio.
> Do you know why is this happening? ☺️

@AndiAJ what is the id of the specific ping that shows up on the dashboard but not in the logs? I randomly picked `52c2e975-6998-4ac2-bc94-46fcf189d0c0` from the debug view and it shows up in the logs.

**Comment by sblatz** [comment]
@AndiAJ can you tell me what steps you're performing to do these searches? I've tested locally and I seem to be getting the right number of total_uri_count (3 searches = 3 for total_uri_count).

**Comment by liuche** [comment]
Just a bump here @AndiAJ ^

**Comment by sblatz** [comment]
@liuche We're going to need to fix this bug mentioned by Glean team: https://github.com/mozilla-mobile/fenix/issues/6577

**Comment by boek** [comment]
Going to track in #6577
