### ISSUE TITLE
[Telemetry] Search widget telemetry

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#4457]
#### Description & Product Manager / Data Scientist User Story
As a product owner, I want to know how much search activity is initiated from the search widget.

#### Hypothesis
We believe this feature is useful to users by 
- Making Search more accessible
- Keeping all search history in Firefox (and not have it split between Firefox and native Google search widget)

We believe this feature is successful if more than 10% of searches are initiated from the search widget. 

#### What questions will you answer with this data?
- How many users have search widget on home screen (core ping) _unsure if this is possible_ (I like to track this but also not sure if it's possible. We did it through LeanPlum in Fennec)
- How often do users initiate search from the widget

#### Why does Mozilla need to answer these questions? Are there benefits for users? Do we need this information to address product or business requirements?
-To enhance user search experience

#### What probes (suggested, if applicable)
- Ping when search screen is launched from search widget
- Core ping notifying us if a user has the search widget on home screen (may not be possible)

### Dependencies (Added by PM and Eng)
- Glean

### Acceptance Criteria (Added by PM)
- Event pings can be queried via re:dash
- We are sending telemetry events for the actions listed in the requirements
- We have documented the telemetry
- We have asked a data steward to [review](https://github.com/mozilla/data-review/blob/master/request.md) the telemetry
- NOT an AC: Data science to create dashboard or further graphs (this will be a separate issue, this issue is only about hooking up the events described and that they can be queried in re-dash)

**Comment by boek** [comment]
👍 thanks for filing this @sblatz was definitely thinking about this when looking at the PR!

**Comment by boek** [comment]
@vesta0 How do you want us to surface these follow up tickets so we can get them into a sprint? :)

**Comment by vesta0** [comment]
I have reviewed/updated the description of this ticket. Let's review at backlog grooming.

**Comment by AndiAJ** [comment]
Hi, **verified as fixed**  on **1.3.0-rc.1** using a Google Pixel 3a (Android 9)

Tap on "**Search the web**" -  new_tab_button events Ping **056551c1-35ce-492a-999c-4b84a24ffaa5**
Tap on **Fenix Logo** - new_tab_button events Ping **410ff548-d272-49c3-aa89-a85df34e81ca**
Tap on **microphone sign** - voice_button events Ping **74295334-2499-4065-a8f2-9f00d9d65438**

[Logcat](https://github.com/mozilla-mobile/fenix/files/3510061/widget.txt)
[Glean](https://debug-ping-preview.firebaseapp.com/pings/aj-160801)
