### ISSUE TITLE
Reduce install size

### ISSUE THREAD

**Issue by amkcpu** [mozilla-mobile/fenix#4459]
## Steps to reproduce
Install Firefox Preview and install Firefox for Android.

### Expected behavior
Firefox Preview should have the same, preferably a significantly smaller install size.

### Actual behavior
On the Honor 7 (PLK-L01) running Android 6.0, Firefox Preview has an install size of 173 MB, whereas Firefox (Fennec) only has 165 MB. While not a big difference, I would like Fenix to have a very much smaller install size as to not use up to much space on low-end devices with limited storage.

### Device information

* Android device: Honor 7 (PLK-L01), running Android 6.0
* Fenix version: 1.1.0

**Comment by kbrosnan** [comment]
This is not directly actionable. Fennec is frozen at Gecko 68 and has a different design structure which makes it smaller.

**Comment by amkcpu** [comment]
Even though I know it could be hard, a reduced install size could be difficult to do, it is very desirable especially for low-end devices, seeing also where Mozilla is headed with Firefox Lite.
How about re-opening this as a feature request?
