### ISSUE TITLE
Notifications like "Tab closed" have the same text color for explanation and action

### ISSUE THREAD

**Issue by dglttr** [mozilla-mobile/fenix#4460]
## Steps to reproduce
Close a tab or open a new tab in the background.

### Expected behavior
The associated action (undo and switch, respectively), should have a different text color as to highlight that it is an action (similar to how this is done in Fennec, the explanation being white and the action being blue).

### Actual behavior
It's all white text and the action is hard to distinguish and visually jarring.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-12864)

**Comment by kbrosnan** [comment]
UX do we want to make any changes to our toast designs?

**Comment by lime124** [comment]
@topotropic can you take a look a make a call? then please either label "ready for eng" or close as won't fix. thanks!

**Comment by amkcpu** [comment]
@topotropic Would you mind weighing in? I still think that this is a UX issue making it harder to grasp where the action (colored) vs. information (toast text in  white or black) is. Having the action using a color would also follow virtually _all_ other Android apps.
I agree that it may not be the most pressing issue, but still think it is very valid.
See for example this pretty generic screenshot from Gmail:

![gmail1_082118082055](https://user-images.githubusercontent.com/46764284/85959939-e029dd00-b99f-11ea-8da7-b9b3f4fdc781.jpg)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1810001

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
