### ISSUE TITLE
[Bug] When re-entering Fenix, open tabs all change to "about:blank"

### ISSUE THREAD

**Issue by amkcpu** [mozilla-mobile/fenix#4461]
## Steps to reproduce
Open a few tabs in Fenix. Then leave app to do something else. Then re-enter Fenix through app switcher or launcher.

### Expected behavior
Open tabs remain unchanged.

### Actual behavior
While not happening all the time, sometimes the open tabs just turn into about:blank pages, which is of course extremely annoying because you lose all opened tabs. Note that apparently, I can "save" tabs by force-closing Fenix via the app switcher. When reopened, these tabs are saved in a way and do not turn into about:blank pages, even if other (more recently opened) tabs do.
This has affected me not only in version 1.1.0, but already in version 1.0.

### Device information

* Android device: Huawei Honor 7 (PLK-L01), running Android 6.0
* Fenix version: 1.1.0

**Comment by jacktose** [comment]
[I reported this in the Google group on May 20th][gg], against v. 1.0.1921, and it's still happening in 190802 18:05, Android 8.1.0, Moto G5+.

[gg]: https://groups.google.com/forum/m/#!msg/fenix-nightly/NL0dQbsdZCE/43kf6eQkBgAJ

**Comment by nate-anderson** [comment]
Affects me as well, same steps to reproduce. Very frustrating.

Samsung Galaxy S7 on Android 9
1.1.0 (Build #12042112)
📦: 4.0.1

**Comment by ekager** [comment]
Please see #1577 for progress on this bug
