### ISSUE TITLE
[Bug] Moving Bookmark Folder Selection Screen Does Not Display Text 

### ISSUE THREAD

**Issue by ekager** [mozilla-mobile/fenix#4462]
## Steps to reproduce
1. Go to a bookmark
2. Edit 
3. Click folder to change folder

### Expected behavior
Can see bookmark folder text

### Actual behavior
![Screenshot_20190801-111134](https://user-images.githubusercontent.com/25442310/62317238-1c7e5180-b44e-11e9-9873-a47d97464202.png)

### Device information

* Android device: ?
* Fenix version: ?

**Comment by sv-ohorvath** [comment]
Verified as fixed on Rc 1.2.0-rc2
