### ISSUE TITLE
Search widget implementation review

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#4468]
This ticket is a placeholder for UX's implementation review of the search widget feature.

For reference Fennec spec:
https://mozilla.invisionapp.com/share/UJQJP4IC7WN#/screens/349402550_Searchwidget

**Comment by liuche** [comment]
Timebox this to 1hr designer's time to file any follow-ups.

**Comment by Verdi** [comment]
We met today and agreed that the widget (pending the landing of the final changes) is ready to ship. We also agreed to investigate what it would take to update the voice search dialog ([Issue 4657](https://github.com/mozilla-mobile/fenix/issues/4657)) but that shouldn't block shipping.
