### ISSUE TITLE
[Bug] Fenix "Help" button links to a google search without SUMO results

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#4469]
## Steps to reproduce
- Click 3-dot menu
- Select "Help"

### Expected behavior
Brought to SUMO

### Actual behavior
Brought to a google search. There's one result: reddit

### Device information

* Android device: ?
* Fenix version: ?

**Comment by mcomella** [comment]
It looks like the URL may not be encoded so the spaces are not escaped (as `%20`) and it creates a search instead of a url.

**Comment by cadeyrn** [comment]
Sounds like #3892.

**Comment by sblatz** [comment]
Yep, closing as dup of #3892 and prioritizing that one :)
