### ISSUE TITLE
Let users know What's new!

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/fenix#4474]
## User Story
- As a user, when I update Fenix I want to know what new features/enhancements/bug fixes came with my update. 

### Acceptance Criteria
- I can open the app and know my app was updated and have a way of finding out what's new. 
- We need a What's new Sumo page created for every major release. cc @bifleming 

Some ideas:
-a homescreen card that appears on the homescreen (let's say above the tabs) that user can tap on and be directed to the "what's new" sumo page
-Red dot on the 3dot menu, and a menu option called "what's new" that takes the user the the "what's new" sumo page (like the Focus design)
-a new tab opened to the "what's new" sumo page, when the app is opened first time after install (least favourite)

### UX spec
https://share.goabstract.com/e6943d7b-9c94-44fa-a801-ff1186151654?mode=design&sha=a2a405536d06162d79dea486362f9ce857b0cb02

- after an update to a major version, there is a blue notification dot on the 3-dot menu on home
- in the home menu is a new item "What's new" with a blue notification dot
- tapping on "What's new" opens a new tab with the "What's new SUMO" page
- the dots disappear after 4 days or once people interact with it
- there's also a link to the "What's new" page in Settings > About
- Add "What's new" link to the (ugly) About page.

**EDIT (Sawyer)**: After speaking with @topotropic, we are going to hold off on the "notification icon" on the three dot menu on the homescreen. Instead, there will just be one once the menu expands.

**Comment by apbitner** [comment]
@vesta0 could we get a feature brief for this so that we can size it? Thank you

**Comment by lime124** [comment]
discussed during PM/UX about more requirements. let's keep it to MValuableP for this release and we can iterate in the future. action would link to a SUMO page.

**Comment by topotropic** [comment]
@vesta why don't we add a new section here https://www.mozilla.org/en-US/firefox/android/68.0beta/releasenotes/ and link to it?

**Comment by vesta0** [comment]
@topotropic that's a good idea but we don't have a page like that yet, so in the meantime let's link to the Sumo What's new page. Let me know once you have a recommended solution. See the issue description for some suggestions :)

**Comment by topotropic** [comment]
I'd suggest to put a notification dot on the 3-dot home menu and add "What's new" as last menu item. This links to a "What's new" page on SUMO. We can also link to is from Settings > About.

**Comment by vesta0** [comment]
Thanks @topotropic yes I am good with your proposal. Down the road I'd really love to explore what more we can do with homescreen cards as well but for now this is a good solution!

**Comment by sblatz** [comment]
I'll need a SUMO link I can point to with this button. Waiting for Joni to provide.

**Comment by vesta0** [comment]
@sblatz is it correct to assume that the SUMO link changes for every release, with the first one being the Fenix 1.4 release article?

**Comment by jonichan** [comment]
I gave the link to Sawyer on Slack. Here it is: https://support.mozilla.org/1/mobile/%VERSION%/%OS%/%LOCALE%/whats-new-firefox-preview

Fenix is equivalent to Fennec v.69 and above, is that correct? If so, the SUMO link won't change. We'll just set it up so it shows content that's appropriate to the user's version of Fenix. The caveat is that we can't detect dot releases (so no 69.1).

**Comment by vesta0** [comment]
@jonichan I am not sure what "Fenix being equivalent to Fennec v.69 and above" means but I do know that we'd want a "What's new page" for most dot releases since we will be releasing features when they are ready on a regular cadance. Maybe @liuche can provide some guidance here.

**Comment by jonichan** [comment]
@vesta0 In that case, since we're putting out a What's New page for dot releases, we will need a different What's New link for each release.

**Comment by sblatz** [comment]
Update: I am going to change the copy to "What's New" to follow "Your Library" having a capital "L".

@topotropic please let me know if you want me to change both of these to reflect the mocks (that should likely be filed as a separate ticket).

<img width="350" alt="image" src="https://user-images.githubusercontent.com/4400286/63896700-df5f9d80-c9c0-11e9-9585-23f8635d2ef8.png">

**Comment by sblatz** [comment]
@jonichan Can you help me understand what you mean by "we can't detect minor version numbers"? 

> In that case, since we're putting out a What's New page for dot releases, we will need a different What's New link for each release.

Is this really necessary? That's going to be another item of release criteria every sprint 😕

**Comment by vesta0** [comment]
@sblatz I have a proposal that I've run by @liuche and waiting to hear back: Continue releasing every 2 weeks but make every 3rd release a major one (going up a version every 6 weeks) and publish a What's New SUMO page listing all new features shipped as part of that release or since the previous release.

**Comment by sblatz** [comment]
@vesta0 I'm going to hold this feature on confirmation from @liuche then about this decision. That changes our implementation (checking for major vs. minor versions).

**Comment by jonichan** [comment]
@vesta0 I've drafted a SUMO article here. Please review by the EOD Thursday 9/5 to give the community enough time to localize it: https://docs.google.com/document/d/1Nd3fCsvem_2-bFQu2z_zdwMTPxTGoMIF7ReKORtVLI0/edit?usp=sharing

**Comment by sv-ohorvath** [comment]
> Since @topotropic mentioned we want to hold off on the highlighting of the three dot menu, we actually don't need the PR I mentioned [here](https://github.com/mozilla-mobile/fenix/issues/4474#issuecomment-524987750).

Verified the new menu entry, but without the dot highlight as I understand it was postponed. 
Verified the link in the about page.
build: Nightly 9/4.
