### ISSUE TITLE
[Bug] Send tab to device on desktop FF doesn't list Fenix device as a destination

### ISSUE THREAD

**Issue by staktrace** [mozilla-mobile/fenix#4477]
## Steps to reproduce
* Set up sync on a laptop (macOS, Firefox Nightly desktop) and on Fenix
* Try to "Send tab to device" from desktop to Fenix

### Expected behavior
The device with Fenix shows up in the "Send tab to device" list

### Actual behavior
My other devices are listed there, but not the Fenix one. I checked via the "Manage your devices" link on `about:preferences#sync` that the device with Fenix is properly registered. **I installed Fenix and set up FxA at least two weeks ago and have opened it a few times sporadically since then.**

### Device information

* Android device: Sony Xperia XZ1 Compact
* Fenix version: 1.1.0 (Build #12042112)

**Comment by ekager** [comment]
CC @jonalmeida

**Comment by jonalmeida** [comment]
This is not a bug - the first device you setup (desktop/mobile) won't know about the second device until the next sync.

I'd say this is more of a feature request: As a user, I want my devices to be immediately informed of new sync devices when they are setup.

**Comment by staktrace** [comment]
How long does it take for Fenix to sync? This wasn't immediate; I installed Fenix and set up FxA at least two weeks ago and have opened it a few times sporadically since then.

**Comment by jonalmeida** [comment]
> Fenix version: 1.1.0 (Build #12042112)

Ah that's the cause! We only have send tab enabled in the 1.2 release. :)
