### ISSUE TITLE
No way to access synced tabs from other devices

### ISSUE THREAD

**Issue by staktrace** [mozilla-mobile/fenix#4479]
## Steps to reproduce
Go to "Your Library"

### Expected behavior
There's some way to access synced tabs that I have open on other FxA devices

### Actual behavior
No way to access those tabs is apparent

### Device information

* Android device: Sony XPeria XZ1 Compact
* Fenix version: 1.1.0 (Build #12042112)

**Comment by staktrace** [comment]
(See also #4477, maybe FxA is just busted on Fenix in general?)

**Comment by staktrace** [comment]
Note that this is a regression compared to Fennec.

**Comment by madb1lly** [comment]
I use this feature a _lot_ on Fennec and miss it on Fenix.
Cheers :)

**Comment by topotropic** [comment]
This is covered here https://github.com/mozilla-mobile/fenix/issues/5762. Thanks for the feedback. I'll close the issue.
