### ISSUE TITLE
Homescreen scrolling buggy with multiple tabs open

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#448]
![buggy 2019-02-12 08_01_14](https://user-images.githubusercontent.com/4400286/52649047-65d8e580-2e9c-11e9-926f-332f5bdc923c.gif)

**Comment by sblatz** [comment]
This may be expected behavior at this point, but just wanted to document so we don't forget to fix!

**Comment by dbranham20** [comment]
I was also able to reproduce this same error with just one tab open.  
Steps:
click the search bar
back out of search bar
attempt to scroll

**Comment by boek** [comment]
Dup of #431
