### ISSUE TITLE
[Bug] url autocomplete reappears with gboard backspace swipe gesture

### ISSUE THREAD

**Issue by ashkitten** [mozilla-mobile/fenix#4481]
## Steps to reproduce

- visit any webpage
- using the backspace swipe gesture in gboard, delete part of the url

### Expected behavior

text is removed normally

### Actual behavior

the url reappears immediately as an autocomplete hint

### Device information

* Android device: Google Pixel XL, LineageOS 16.0 (Pie)
* Fenix version: Nightly 190801 18:01 (Build #12131808)

**Comment by kbrosnan** [comment]
This is in the search/address bar, correct?

**Comment by ashkitten** [comment]
@kbrosnan correct

**Comment by liuche** [comment]
I can't repro this on 2.3 - QA can you?

**Comment by ashkitten** [comment]
you're right, it appears to be fixed now

**Comment by abodea** [comment]
Hello @liuche please note that I was able to reproduce this issue on the latest **`Nightly build from 11/21 with Google Pixel 3a XL(Android 10).`**
#### I tried this on Fenix and Chrome to compare the behavior for more details check the following attachments:
- > **Chrome 
Note that the text from the URL is deleted and it doesn't reappear.**
![ezgif-1-5708aa500bad](https://user-images.githubusercontent.com/42831109/69338693-66dd4580-0c6c-11ea-8249-4e48aee98718.gif)

- > **Fenix
Note that the text from the URL is deleted but it reappears, there is a chance that the text doesn't reappear but very low.
The autocomplete text is highlighted in purple in the URL bar.** 
![ezgif-1-aab81e38cb38](https://user-images.githubusercontent.com/42831109/69339277-a3f60780-0c6d-11ea-9068-b1f8d4bf7059.gif)

**Comment by Baron-Severin** [comment]
This fix landed in AC today, we will move this into ready for QA as soon as the next snapshot is generated.

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **Nightly Build #13440604 from 12/10** using the following devices:
• Google Pixel 3a XL (Android 9)
• Samsung Galaxy S10 + (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)

►Video
![20191210_114649](https://user-images.githubusercontent.com/51314259/70518396-f460d680-1b42-11ea-8fab-011d179aa486.gif)
