### ISSUE TITLE
[Bug] I cannot see bookmark folder names in dark theme

### ISSUE THREAD

**Issue by andreicristianpetcu** [mozilla-mobile/fenix#4482]
## Steps to reproduce
use dark theme
bookmark
edit bookmark
### Expected behavior
should be able to see folder names
### Actual behavior
I cannot see the folder names
![Screenshot_20190802-093116_Firefox_Nightly](https://user-images.githubusercontent.com/922368/62349736-45175180-b509-11e9-9e0a-f3fde0860f61.png)

### Device information

* Android device: OnePlus 5t
* Fenix version: latest nightly
![android_version](https://user-images.githubusercontent.com/922368/62349761-595b4e80-b509-11e9-9030-e03a3f58ce4d.png)

**Comment by mcarare** [comment]
should be fixed along with #4462
