### ISSUE TITLE
[Bug]Flicker when deleting History items

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#4484]
## Prerequisites
Have 5 history items 

## Steps to reproduce
1. Tap the 3dot button next the **first** history item and tap delete
2. Tap the 3dot button next the **last** history item and tap delete

### Expected behavior
History items are deleted without any UI problems 

### Actual behavior
When deleting **the first** history item, the History section flickers
When deleting **the last** history item, there are no issues

### Device information

* Android device: 
• Google Pixel 3a (Android 9)
* Fenix version:  RC 1.2-rc2 

#### Notes
► Video
![20190802_113521](https://user-images.githubusercontent.com/51314259/62356877-b27fae00-b51a-11e9-91d9-72f9c67ccd56.gif)

**Comment by gouri-panda** [comment]
@AndiAJ Can I work on this issue?
