### ISSUE TITLE
[Bug]Deleting a bookmark from from edit mode doesn't bring up the snackbar

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#4488]
### Prerequisites
Have a couple of bookmarks saved.

## Steps to reproduce
1. Tap to edit one of the bookmarks
2. Delete the bookmark using the upper right trash bin icon ![62283301-ee067380-b459-11e9-831b-5378b571a01a](https://user-images.githubusercontent.com/51314259/62367211-9b988600-b531-11e9-92ed-3538963212c0.png)

### Expected behavior
The snackbar should show up, giving the user the possibility to undo the deletion.

### Actual behavior
The snackbar doesn't show up.

### Device information

* Android device: 
• Google Pixel 3a (Android 9)
• Moto G4 (Android 6.0.1)
• Xiaomi Mi Pad 2 (Android 5.1)

* Fenix version: 
• RC 1.2-rc2
• Nightly Build #12140610 from 2/8

### Notes
► Video 
![20190802_143244](https://user-images.githubusercontent.com/51314259/62367548-af90b780-b532-11e9-840d-4b1b285d7aa3.gif)

**Comment by shahsurajk** [comment]
@NotWoods  is anyone on this? I could give this a try.

**Comment by NotWoods** [comment]
Go for it!

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest Nightly Build #12410626 from 29/8 using the following devices:
• Google Pixel 3a (Android 9)
• OnePlus A3 (Android 6.0.1)

► Video
![Working](https://user-images.githubusercontent.com/51314259/63919617-c817c300-ca47-11e9-8423-aa6a96d91f75.gif)
