### ISSUE TITLE
[Bug] Tab icons in a collection are not aligned with the titles

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#4490]
## Steps to reproduce
1. Create a collection with some tabs.
2. Expand the collection and observe the tabs icons.
### Expected behavior
Vertically aligned on the center of the titles.
### Actual behavior
The icons are lower than the titles.
### Device information

* Android device: Galaxy S8 (android 9), Xiaomi Mi Pad 2 (Android 5.1) - x86
* Fenix version: RC 1.2-rc2.

![Screenshot_20190802-145049_Firefox Preview](https://user-images.githubusercontent.com/4037709/62368658-e74d2e80-b535-11e9-8a36-4c83b19c1efe.jpg)

**Comment by topotropic** [comment]
Thanks for the feedback, it's covered here https://github.com/mozilla-mobile/fenix/issues/8764. I'll close it.
