### ISSUE TITLE
[Bug] Text in dark mode bookmarks is gone

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#4499]
## Steps to reproduce
1. Navigate to a page
2. Press Bookmark
3. Press "Edit" in the Snackbar
4. Press "Folder"

### Expected behavior
1. Can see the text on my folders

### Actual behavior
1. Can't see the text on my folders

<img width="492" alt="image" src="https://user-images.githubusercontent.com/4400286/62385280-7d1e9480-b509-11e9-8f29-27497a2d55f8.png">

**Comment by ekager** [comment]
This has been fixed

**Comment by sblatz** [comment]
Looks like now this is happening :(

Did the fix cause this?
<img width="492" alt="image" src="https://user-images.githubusercontent.com/4400286/62483087-b6eed580-b76b-11e9-86d2-0288787909fb.png">
