### ISSUE TITLE
[Meta] Optimize landscape media playback

### ISSUE THREAD

**Issue by lime124** [mozilla-mobile/fenix#4502]
### User Story
As a user, I want Fenix to work well in landscape mode while I'm watching media, so I can use Fenix in landscape more on a tablet and watch fullscreen video content.

### Acceptance Criteria
- I can watch media in Fenix in landscape mode
- I can view and interact with media content in landscape mode

### Bugs to fix in Q1
- [ ] [Bug] Video is black when rotated while playing fullscreen #4249
- [ ] [Bug] Video control bar missing on Vimeo after switching to full screen mode #4269

### Other landscape related bugs
**[Filed bugs](https://github.com/mozilla-mobile/fenix/labels/b%3Alandscape)**

**Comment by lime124** [comment]
@vesta0

**Comment by sblatz** [comment]
Labeling as feature request because this feels like a product choice to prioritize these issues or not :)

**Comment by vesta0** [comment]
We did some investigation for tablets as part of #1631 a while back and the [`b:landscape'](https://github.com/mozilla-mobile/fenix/labels/b%3Alandscape) issues were filed as a result.

**Comment by cpeterso** [comment]
We should keep in mind the user experience of playing landscape video on devices with display cutouts (notches).

**Comment by vesta0** [comment]
We will tackle individual issues during polish sprints.
