### ISSUE TITLE
[Meta] Fenix Accessibility Audit

### ISSUE THREAD

**Issue by ekager** [mozilla-mobile/fenix#4503]
## Homescreen
- Homescreen currently has some strange a11y issues (see #2142, #3419) we should make sure the homescreen makes sense/works with TalkBack especially as we consider redesigning some of it
- issues with the 3 dot menu - #3584 

CC @topotropic because I know I saw your new mocks that may impact this, and we should probably loop in someone from a11y for further questions :)

**Comment by lime124** [comment]
after talking with emily, opening this up to be a ticket for a11y for the whole app. we'll group related issues here and we can tackle them all at one time to ensure we're coming up with holistic solutions that don't conflict.

also want to loop in eitan! would love some support from that team :)

**Comment by ekager** [comment]
Going to close because we never used this ticket
