### ISSUE TITLE
[Bug] Some redirects are filtered in history, others not

### ISSUE THREAD

**Issue by cadeyrn** [mozilla-mobile/fenix#4505]
### Steps to reproduce

1. enter some addresses with expected redirects into the address bar and press enter.

Examples: 

- google.com
- mozilla.org
- soeren-hentzschel.at
- ghacks.net

2. go to history

### Expected behavior

For each of these websites there should be only one entry in history.

### Actual behavior

I used these four websites as examples because it works for two of them and does not work for the other two.

For soeren-hentzschel.at and google.com it work as expected, there is only one entry in the history (the URL after the redirect). But for mozilla.org and ghacks.net there are two entries in the history (the URL from before AND after the redirect).

### Device information

* Android device: HTC U 11
* Fenix version: master branch revision ec96d134ff49cb0c97879e18ad740b33be341508

**Comment by boek** [comment]
@grigoryk Is this something that needs to be fixed on the A-S side?

**Comment by cadeyrn** [comment]
seems to be fixed.
