### ISSUE TITLE
Remove "do exhuastive when" if unecessary

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#4511]
@csadilek and I are unsure if this is necessary anymore.

**Comment by Mugurell** [comment]
There are tickets and a proposal for adding `sealed whens` in the language - https://youtrack.jetbrains.com/issue/KT-12380

There are some motives described there and I feel the most important one - ensuring that any later change will properly be treated in the when block is something that this project needs to enforce given the fast pace of development, constant refactoring and contributors being new to the project.

Maybe the construct `Do exhaustive when` is something new for most persons or even too verbose and could be changed with something simpler but I think it's an important sanity check and would be great if it could remain in the project, presented in our code-style documentation and enforced in reviews.

**Comment by csadilek** [comment]
Yes, Let's keep this until this finds its way into Kotlin. There's also https://github.com/cashapp/exhaustive which looks great, but we want to limit 3rd party deps.
