### ISSUE TITLE
Password autofill on Android 7 and below

### ISSUE THREAD

**Issue by ehsan** [mozilla-mobile/fenix#4514]
### Why/User Benefit/User Problem
I use an Android 7 phone.  The LockWise app on Android 7 doesn't support autofilling passwords, so on Fenix right now I have no way to autofill my passwords.  This prevents me from logging in to the websites for which I have a password saved to my Firefox Account.

### What/Requirements
Turn on the built-in Gecko password auto-fill support as a bare minimum password auto-fill feature.  This works well on Fennec today.

### Acceptance Criteria (how do I know when I’m done?)
Being able to save passwords on websites, and automatically fill them in, and connect it with Firefox Sync.

**Comment by ehsan** [comment]
If the data on [this page](https://fossbytes.com/most-popular-android-versions-always-updated/) is to be believed, Android 8+ where LockWise supports password autofill is about 38% of the market share.

**Comment by jancborchardt** [comment]
@vrudesai the "Account settings" page only shows Bookmarks and History in "Choose what to sync". Logins or open tabs are not listed, so I assume not implemented, which is the issue here. :)

**Comment by vesta0** [comment]
Thanks for the stats @ehsan ! We are building this in Fenix.
