### ISSUE TITLE
[Bug] search widget does not use the full width

### ISSUE THREAD

**Issue by cadeyrn** [mozilla-mobile/fenix#4516]
### Steps to reproduce

1. add the search widget to your home screen

### Expected behavior

I can set the width of the search widget to the full width because it doesn't look good otherwise. :)

### Actual behavior

There seems to be a maximum width. I can make it smaller but not larger. The screenshot shows both the search widgets of Fennec (expected width) and Fenix (too small)

![Screenshot_20190802-212550](https://user-images.githubusercontent.com/1100614/62394187-bfc58880-b56c-11e9-81f2-4157a409c32f.png)

### Device information

* Android device: HTC U11 / Android 8.0
* Fenix version: master branch revision 46b2d6f937f267137f7744256d829eb5d5d40550

**Comment by jawadalkassim** [comment]
This is kind of annoying and i thought we will got a beautiful dark search widget

**Comment by jyeontaek** [comment]
This is expected behavior defined by the UX team.

**Comment by cadeyrn** [comment]
wait, what? It's already possible to resize the widget. I can make it smaller (very small!) but not wider? I don't care about the default size but it should be possible to use the full width if that's how I want to use it. For me it looks weird (please see the screenshot) and feels like a regression compared to Fennec.

Can this issue cat a "UX feedback" label to get more opinions, please?

**Comment by jyeontaek** [comment]
@Verdi Instead of using specific sizes (256x50 dp, 360x50 dp) for 4x1 and 5x1, maybe we should make the widget occupy the entire 4x1 or 5x1 cells?

**Comment by Verdi** [comment]
> This is expected behavior defined by the UX team.
This is not the expected behavior. 

The expected behavior is that the Fenix widget should look/work like the Fennec widget in the screenshot above.

> @Verdi Instead of using specific sizes (256x50 dp, 360x50 dp) for 4x1 and 5x1, maybe we should make the widget occupy the entire 4x1 or 5x1 cells?

I don't know why it's not doing what we want and I don't know how/not the person to asses that proposal. Give it a try and see if it works?

**Comment by lime124** [comment]
removing need ux label as feedback has been give.

**Comment by sblatz** [comment]
Fix is landing vvvv soon :)

**Comment by cadeyrn** [comment]
> The expected behavior is that the Fenix widget should look/work like the Fennec widget in the screenshot above.

Since the changes in August it's possible to use the full width for the search widget (thank you!). But the default is still *not* the full width while the default of the Fennec search widget was to use the full width. @Verdi Is this expected?

If yes, this ticket should be closed or get a label for QA. If no - should I new ticket be created?

**Comment by sblatz** [comment]
@cadeyrn Given that other browsers (like Chrome) use a 4x1 as their default, I think it's perfectly reasonable for us to use that. 

Users can still expand the widget if they would like!

@Verdi please re-open if you disagree.
