### ISSUE TITLE
Show progress on Download Notification

### ISSUE THREAD

**Issue by cadeyrn** [mozilla-mobile/fenix#4525]
Fenix finally uses the new Gecko based download manager! It solves some issues but also regressed the functionality.

- [ ] You can no longer see the progress in the notification during the download
- [x] The download no longer opens after a click on the notification after the download

**Comment by NotWoods** [comment]
The second issue was fixed in the newest Android Components version so it should show up in nightly soon.

**Comment by sblatz** [comment]
@vesta0 When I was implementing the download notification, I found that we actually *could* add a progress bar to the notification. Is that something we want to prioritize as a must/should?

My *rough* engineering estimate is ~E5 for this :)

**Comment by vesta0** [comment]
Hey @sblatz that's great to know. Let's create a ticket for this and call it a SHOULD. Thanks!

**Comment by vesta0** [comment]
@sblatz can we close this?

**Comment by sblatz** [comment]
@vesta0 Not just yet. I am working on this in AC: https://github.com/mozilla-mobile/android-components/issues/5284

Hoping I can get it closed out this week 😄

**Comment by AndiAJ** [comment]
Hi, I've just checked the Download Notification progress bar on the latest **Nightly Build #13640626 from 12/30** using the following devices:

• Google Pixel 3a (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1) 

✔️ The download progress bar is displayed in the Android notification while downloading any content.

Compared to other browsers, I've noticed an inconsistency, namely, that it's not actually displaying the progress (Download percentage or progress from a file size point of view ) 

## **► Fenix (Continuously loading progress bar)**
![20191230_100044](https://user-images.githubusercontent.com/51314259/71573626-88dcaa00-2aed-11ea-8725-386705426bc9.gif)

## **► Fennec (Percentage)**
![20191230_095859](https://user-images.githubusercontent.com/51314259/71573569-38654c80-2aed-11ea-9a44-1321259315d7.gif)

## **► Chrome (File size progress)**
![20191230_095957](https://user-images.githubusercontent.com/51314259/71573603-6c407200-2aed-11ea-8607-954e862be743.gif)

## **► Brave (File size progress)**
![20191230_100247](https://user-images.githubusercontent.com/51314259/71573713-e2dd6f80-2aed-11ea-984e-46eed97de29d.gif)

@sblatz  - Please review, and advise ☺️ 
I'll remove the QA needed label until further notice

**Comment by AndiAJ** [comment]
Hi, **verified as fixed**, the progress bar is displayed, on the latest **Nightly Build #20070606 from 01/07** using the following devices:

• Google Pixel 3a (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

► Video
![20200107_090953](https://user-images.githubusercontent.com/51314259/71876066-8ce07b80-312e-11ea-81c8-b44cf736f49b.gif)

@sblatz  - Should we track the actual download progress in another issue? (Download percentage or progress from a file size point of view )

**Comment by sblatz** [comment]
@AndiAJ Sorry for the confusion on this. This ticket should be tracking the progress moving (not just an indeterminate bar). It seems that didn't make it into nightly. I'm going to re-open this and mark it as QA once it's in. Apoligies!

**Comment by sblatz** [comment]
This is now appearing on master so it should be ready to QA 😄

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **Nightly Build #20100616 from 01/10** using the following devices:
• Google Pixel 3a (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

► Video
![20200110_091016](https://user-images.githubusercontent.com/51314259/72133341-db3d8680-3389-11ea-9b6c-e02505b24db4.gif)

Great job @sblatz ☺️ !
