### ISSUE TITLE
[Bug] With pseudolocalization on, text overflows UI widgets

### ISSUE THREAD

**Issue by nyanpasu64** [mozilla-mobile/fenix#4526]
## Steps to reproduce

- In Android settings, enable pseudolocalization (en-xa). This replaces English strings with look-alike Unicode and makes them longer, to simulate languages taking up more space. `Test` is replaced by `[Tèƨƭ one two]` or similar.
- Install a debug build of Firefox Preview (by cloning and building the repo).

### Expected behavior

Text which overflows on-screen elements goes to the next line.

### Actual behavior

In some locations, text which overflows on-screen elements is cut off. Notice that the `one two three]` and closing bracket is missing.

- First-launch screen: [link to image](https://user-images.githubusercontent.com/913957/62416769-a1579f80-b5f5-11e9-931f-31d91bce96b1.png)
- Menu: [link to image](https://user-images.githubusercontent.com/913957/62416854-42932580-b5f7-11e9-8301-200cbec68dd3.png)
- Tab list menu: [link to image](https://user-images.githubusercontent.com/913957/62416927-83d80500-b5f8-11e9-82b0-7830d3e8023c.png)

### Device information

* Android device: Moto G5 Plus
* Fenix version: master 671727c3e8cd6128b88934ae8d74b327c586e72c

**Comment by colintheshots** [comment]
It looks like we either need text wrapping in some of these cases or we'll require wider menus. Simply using shorter words won't guarantee the text fits when translated.

**Comment by mcarare** [comment]
I have submitted a fix for the first issue (onboarding theme picker).
For the other ones, IMO this is a desired behaviour. I don't think it is a good design choice to allow menus with multiple lines or to make menus too wide so they could cover the whole screen. 
Can UX make a decision regarding this?

**Comment by lime124** [comment]
@jpfaller can you take a look and comment? thanks!

**Comment by jpfaller** [comment]
Of the options discussed, it feels like making the menus wider would be acceptable - I realize it isn't ideal but having critical instructional text cut off isn't either, and I agree that writing shorter menu items likely won't mitigate all of this risk. 

Is the only way to get out of the menu to tap outside the surface? If so, we may need to incorporate another way of dismissing the menu.

Some other options not discussed that may help solve this (but could open up other issues):
- Make the menu takeover the whole screen to maximize space, and add a dismissal option
- Decrease the size of the fonts

**Comment by jpfaller** [comment]
Per @shorlander and UX team - the menus should expand up to 80% of the width of the screen and then truncate.

**Comment by mcarare** [comment]
This was handled and fixed through specs in https://github.com/mozilla-mobile/fenix/issues/7157 .
