### ISSUE TITLE
Feature request: don't push 'send to device' icons up when populating share menu

### ISSUE THREAD

**Issue by PopeRigby** [mozilla-mobile/fenix#4528]
When the share menu is first opened after  a restart, the icons under  'send to device'  are above one empty row with a 'share a link' label. After the share menu is completely populated, the icons under 'send to device' are pushed up an extra row. This makes it annoying to click on one of those icons, because it moves before you can click on it. A good way to fix this would be to keep the icons under 'send to device' in place, and always have the 'share a link' section have two rows.

**Comment by boek** [comment]
@PopeRigby Thank you for the feedback. We’re actively thinking about how we want to improve the share sheet! I added this to the list on #4275 :)

Also tagging #2819

**Comment by PopeRigby** [comment]
No problem
