### ISSUE TITLE
[Bug] Crash on start on Android 5 & 6 devices

### ISSUE THREAD

**Issue by softvision-miralobontiu** [mozilla-mobile/fenix#4532]
## Steps to reproduce
Start the app.

### Expected behavior
The app should work.

### Actual behavior
App crashes and cannot be open.

### Device information
* Android device: Huawei P9 Lite (Android 6), Nexus 5 (Android 6), Huawei tablet MediaPad M2 (Android 5.1.1)
* Not reproducible on LG G7 Fit (Android 8)
* Fenix version: debug version build from 8/5 master

[logcat.txt](https://github.com/mozilla-mobile/fenix/files/3467279/logcat.txt)

**Comment by csadilek** [comment]
From logcat:

```
08-05 14:05:06.216  8114  8114 I mozac/CrashReporter: Received crash:
UncaughtExceptionCrash(throwable=java.lang.RuntimeException: Unable to create 
application org.mozilla.fenix.DebugFenixApplication:
java.lang.IllegalArgumentException: Unsupported argument type 
mozilla.appservices.rustlog.RustLogAdapter$Companion at parameter 1 of function
rc_log_adapter_create)

08-05 14:05:06.219  8114  8114 I mozac/CrashReporter: Showing prompt
```

/cc @thomcc

**Comment by kbrosnan** [comment]
@softvision-miralobontiu can you run the release Nightly Fenix builds on Android 5/6?

**Comment by colintheshots** [comment]
I cannot reproduce this with the latest master on an Android 5.x emulator. Also, the logCat refers to DebugFenixApplication, which only exists in developer builds. Please re-open this if you can reproduce it in Nightly or any release.

**Comment by softvision-miralobontiu** [comment]
It doesn't crash with the latest Nightly build from taskcluster.

**Comment by softvision-miralobontiu** [comment]
I will reopen this issue as I encountered the crash with the latest Nightly build 190806, on Huawei P9 Lite (Android 6), and Huawei tablet MediaPad M2 (Android 5.1.1).

[logcat.txt](https://github.com/mozilla-mobile/fenix/files/3471232/logcat.txt)

**Comment by boek** [comment]
How severe is this? Should we pull it into the current sprint?

**Comment by ekager** [comment]
It looks slightly different now? 

> 08-06 11:51:39.275 22700 22700 I mozac/CrashReporter: Received crash: UncaughtExceptionCrash(throwable=java.lang.IncompatibleClassChangeError: Class 'android.content.ContentProviderClient' does not implement interface 'java.lang.AutoCloseable' in call to 'void java.lang.AutoCloseable.close()' (declaration of 'mozilla.components.service.fxa.sharing.AccountSharing' appears in /data/app/org.mozilla.fenix.nightly-1/base.apk))

**Comment by thomcc** [comment]
Ugh, this feels like a classloading issue introduced by the megazord changes.

**Comment by csadilek** [comment]
Ah, thanks @ekager. Yes, that looks "better". @thomcc latest crash doesn't look related to `RustLogAdapter` / Megazord anymore.

It looks related to our new `AccountSharing`/`AccountMigration` functionality. /cc @grigoryk

**Comment by csadilek** [comment]
Sentry crash: https://sentry.prod.mozaws.net/operations/fenix-nightly/issues/6121009/

**Comment by thomcc** [comment]
@csadilek Yeah but it's still in app-services provided classes and is a IncompatibleClassChangeError which indicates an issue with classloading (or really class linking).

**Comment by thomcc** [comment]
That said, this might be fixed if we update some dependencies in a-s, which I was going to do after the next A-C release, but there's no real reason to wait for that.

**Comment by csadilek** [comment]
@thomcc this doesn't look like an a-c class to me. It's `mozilla.components.service.fxa.sharing.AccountSharing` which is in a-c?

**Comment by thomcc** [comment]
Oh, my bad! I saw fxa and assumed the type was coming from us, especially since 'weird classloader issue on early version of android' is the kind of bug that wouldn't surprise me for the megazord change.

**Comment by buttercookie42** [comment]
Side questions: Are there any plans for some at least some smoke tests automatically running on whatever the minimum supported API version is? With Firefox/Fennec at least we sort of had that by accident because the ARM emulator images running the bulk of tests are still stuck on Android 4.3, which is relatively close to Fennec's actual min API version of Android 4.1.

**Comment by grigoryk** [comment]
This is an issue in android-components; we're assuming that `ContentProviderClient` is always AutoCloseable, and it's not in earlier API versions. `a-c` patch incoming.

**Comment by grigoryk** [comment]
Fix should be in the next a-c 7.0.0 snapshot.

**Comment by grigoryk** [comment]
NB for reproducing this:
- make sure you have a recent version of Firefox for Android installed alongside Fennec. Affected codepath is only triggered if there's an installed Fennec which declares a certain content authority.

**Comment by softvision-miralobontiu** [comment]
The app didn't crash anymore with the latest Nightly build 190807 (#12190111). I had installed the latest versions of Firefox for Android, Firefox Beta, and Firefox Nightly.
Tested with Huawei P9 Lite (Android 6), Huawei MediaPad M2 (Android 5.1.1), HTC Desire 820 (Android 6.0.1).
