### ISSUE TITLE
open with an app

### ISSUE THREAD

**Issue by cup** [mozilla-mobile/fenix#4549]
I prefer to use "NewPipe" for watching YouTube. With Chrome for Android I can
set default and from then on YouTube pages will open with NewPipe with a single
tap.

With Firefox for Android, I can long press followed by "open with an app".

Firefox Preview seems to have no such option.

**Comment by hakkikaancaliskan** [comment]
I think you miss this, you can use this for open in app.
![Screenshot_20190806-160814](https://user-images.githubusercontent.com/17825767/62542511-92c2ef80-b864-11e9-9a21-694550602ff2.png)

**Comment by Dunexus** [comment]
Probably related to QAB discoverability issues : https://github.com/mozilla-mobile/fenix/issues/3927

**Comment by boek** [comment]
This landed here: https://github.com/mozilla-mobile/android-components/issues/3695. If you find any bugs with it please feel free to open a new issue!
