### ISSUE TITLE
Consider removing "private tab" or "new tab" options

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#455]
As a user I think it is a little confusing to have both menu options presented to me no matter what mode I'm in. Lots of browsers have the ability to make a new tab _just_ in the mode you are currently in. We could provide switching to private mode from the home menu still.

For reference:
<img width=300 src=https://user-images.githubusercontent.com/4400286/52667900-f88e7a00-2ec6-11e9-9636-2588a2280a16.png>

**Comment by lime124** [comment]
collecting for a bigger menu design effort - removing ux label.

**Comment by topotropic** [comment]
I discussed it with Adam, let's leave it as is for now. It's good to have a quick way into private mode – if we'd remove it, it would take more steps to open a private tab. Thanks!
