### ISSUE TITLE
top navigation

### ISSUE THREAD

**Issue by cup** [mozilla-mobile/fenix#4550]
open this issue as every other has been closed and refed as a duplicate of a
locked issue.

this is an important issue and should be open for discussion.

**Comment by cadeyrn** [comment]
Duplicate of #2115. If #2115 is locked it should not be circumvented by opening another issue...

**Comment by boek** [comment]
Hey @cup, rest assured this is something that we are thinking about. We locked the conversation to collaborators only as the discussion before hand was not constructive.
