### ISSUE TITLE
[Bug] Once you add an exception for a site, the other blocked permissions request access

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#4554]
## Steps to reproduce
1. Go to Settings>Site permissions
2. Block all except one (e.g. Microphone)
3. Go to permission.site. Check the site panel info.
4. Tap one of the blocked permissions: notification/camera/location.
5. Tap Microphone, add the exception for mic: check "don't ask again" and Allow access.
6. Check the site info panel.
7. Tap another one of the blocked permissions.
### Expected behavior
Blocked permissions don't ask for access again once an exception is added.
### Actual behavior
Step 3: The panel shows the blocked permissions.
Step 4: No access requests.
Step 6: Only the microphone exception is displayed. 
Step 7: The blocked permissions request access.
### Device information

* Android device: Galaxy S8 (android 9), Nexus 5 (Android 6.0.1)
* Fenix version: Nightly 190806

**Comment by vesta0** [comment]
@Amejia481 and I tested this and it seems like when user adds an exception, the default global permission settings apply to that domain. The correct behaviour should be to default to user-specified custom permissions settings.

**Comment by Amejia481** [comment]
This requires some AC work as we are not taking in consideration the custom users permissions settings when creating an exception. I created a ac issue for it  https://github.com/mozilla-mobile/android-components/issues/5616

**Comment by Amejia481** [comment]
This was fixed in https://github.com/mozilla-mobile/android-components/pull/6166, it should be on the next snapshot.

**Comment by Amejia481** [comment]
The fix should be in the latest nightly, @sv-ohorvath would you mind re-testing?

**Comment by sv-ohorvath** [comment]
Verified as fixed on Nightly 3/10.
Devices verified: Pixel (Android 10), HTC Desire 820 (Android 6.0.1)
