### ISSUE TITLE
Add @Before to reduce code duplication in tests

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#4556]
Lots of our test would benefit greatly from having an `@Before` function. It would make our testing code a lot easier to read. 

See [DefaultBrowserControllerTest](https://github.com/mozilla-mobile/fenix/pull/4493/files#diff-1144e67f32c3d338008db3149cbb1e60R57) for a good example.

**Comment by nikit19** [comment]
I can pick this up if nobody picks it in a few days.

**Comment by chiragmantri** [comment]
@sblatz I would like to pick this up.

**Comment by dragneelfps** [comment]
@sblatz can I pick this up? It will be my first issue in this repo and to Mozilla. Thanks.

**Comment by sblatz** [comment]
@chiragmantri are you working on this?

**Comment by usmanrafi** [comment]
@sblatz if nobody is working on this, I'd like to pick it up.

**Comment by sblatz** [comment]
@usmanrafi I don't think anyone is working on this, so go ahead!

**Comment by usmanrafi** [comment]
@sblatz I've created a pull request regarding this issue. Please review.

**Comment by olsenme** [comment]
Is there still work for more contributors?

**Comment by NotWoods** [comment]
Yes, any of the tests without `@Before` can be worked on 😄

**Comment by starkej2** [comment]
fwiw I checked all of the tests and don't think there's much code duplication left, so this issue might be almost complete.

**Comment by NotWoods** [comment]
Thanks @starkej2! Once #6367 is merged I'll close the issue.
