### ISSUE TITLE
[Bug] Bookmark Sign In Button Not Visible

### ISSUE THREAD

**Issue by ekager** [mozilla-mobile/fenix#4558]
We should do something similar to what @boek did with history and add this to view as part of the last bookmark item in the list?

## Steps to reproduce
1. Don't be signed in, go to bookmarks

### Expected behavior
See `SignInView`

### Actual behavior
No button to sign in

### Device information

* Android device: ?
* Fenix version: ?

**Comment by ekager** [comment]
Also it has a `ThemeIndependentMaterialGreyButtonDestructive` theme right now and it should be `ThemeIndependentMaterialGreyButton`

**Comment by obarzpaw** [comment]
I would like to work on this.

**Comment by obarzpaw** [comment]
@ekager Can you clarify which exactly change from the boek did you have on mind? I do not see sign in button in history library.

**Comment by ekager** [comment]
Hi @obarzpaw ! Thanks for picking this up. If the user is not signed into FxA there should be a button at the bottom of the bookmark list to prompt you sign in to see more bookmarks. As far as I can tell the [`SignInView`](https://github.com/mozilla-mobile/fenix/blob/master/app/src/main/java/org/mozilla/fenix/library/bookmarks/SignInView.kt) still exists, but is not showing properly (I think it might be behind the bookmark list which is taking up the whole screen). What @boek did in history was to make the [Delete History Button part of the list item layout which is only displayed on one of the history items](https://github.com/mozilla-mobile/fenix/blob/master/app/src/main/res/layout/history_list_item.xml), and [toggle it depending on the item position](https://github.com/mozilla-mobile/fenix/blob/master/app/src/main/java/org/mozilla/fenix/library/history/viewholders/HistoryListItemViewHolder.kt#L77) so it's always shown as the first item in the list.

See original mock here:
<img width="282" alt="Screen Shot 2019-10-19 at 11 56 30 AM" src="https://user-images.githubusercontent.com/25442310/67150049-8517e600-f267-11e9-9ab7-38293ba8e345.png">

Let me know if you have any other questions :)

**Comment by obarzpaw** [comment]
Ohh, thank you for your quick answer now everything is clear for me ! :)

btw. (cause of the missunderstanding)
You have on your mind the delete history button on history screen while i've tried to find button : "Sign in to see synced history", that doesn't exist.

**Comment by ekager** [comment]
Ah yeah, sorry for the confusion! I meant just the idea of a singular button living within the list.
Let me know if you have any other questions :)

**Comment by obarzpaw** [comment]
@ekager fixed
