### ISSUE TITLE
Custom tab app bar does not follow UX specs

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#4560]
This has been filed in AC for a while, but I want it to have visibility in the Fenix repo so we can get it prioritized properly.

https://github.com/mozilla-mobile/android-components/issues/1514

I had a PR for fixing this but it caused issues for other consumers of AC: https://github.com/mozilla-mobile/android-components/pull/3610

### Before

<img width="355" alt="Screen Shot 2019-07-01 at 10 38 45 AM" src="https://user-images.githubusercontent.com/4400286/60456403-07fc2e80-9bee-11e9-84a4-c5fd18426795.png">

### After
<img width="355" alt="Screen Shot 2019-07-01 at 10 43 27 AM" src="https://user-images.githubusercontent.com/4400286/60456395-06cb0180-9bee-11e9-8673-c98986f3ea84.png">

**Comment by cadeyrn** [comment]
I hope this will be addressed soon. With a Twitter custom tab it's even more worse as in the screenshot because there is also a "TWEET" button which takes space, but also other apps have an additional button in the toolbar. On my device there is maybe 50 percent of the screen width available for the page title / URL and since it's not possible to scroll the content of this area it would be good to have as much space available for the title / URL as possible.

**Comment by cadeyrn** [comment]
The custom tab toolbar in Firefox Preview is getting worse and worse. Now with the new shield icon there is almost no space left for the page title / URL.

Can that please be prioritized?

![Screenshot_20190912-082623](https://user-images.githubusercontent.com/1100614/64759531-a8989400-d537-11e9-9b4c-b2d291ffcfa5.png)

**Comment by nahuhh** [comment]
I suggest joining the shield and lock icon so there is only one icon and menu, like it was a few weeks ago

Also.. When you toggle off tracking for a website, it should not hide the tracking menu from the website. 

Don't need 2 menus: 

![Adobe_20190919_212312](https://user-images.githubusercontent.com/50635951/65292363-2145b480-db25-11e9-93f0-fb9bf46f49fa.png)

**Comment by NotWoods** [comment]
Seems to be fixed now by @Amejia481 😄

**Comment by sv-ohorvath** [comment]
Verified as fixed on Nightly 9/27.
Samsung Galaxy Tab 3 (Android 8.0), Samsung Galaxy S8 (Android 9), Sony Xperia Z2 (Android 6.0.1)
