### ISSUE TITLE
[Bug] Custom Tabs do not work on Gmail app

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/fenix#4561]
## Steps to reproduce
1. Set Fenix as default browser.
2. Click any link in Gmail.

### Expected behavior
- The link is opened in a custom tab.

### Actual behavior
- The link is opened in the main browser.

### Device information

* Android device: Pixel 2, Android 9
* Fenix version:
Nightly 190805 19:07 (Build #12172029)
📦: 7.0.0
🦎: 69.0-20190801042935

**Comment by sblatz** [comment]
@jonalmeida are you able to reproduce in Reference or Sample Browser?

**Comment by jonalmeida** [comment]
> @jonalmeida are you able to reproduce in Reference or Sample Browser?

@sblatz I wasn't able to reproduce this on r-b (today's nightly). I don't have a recent build of Sample Browser right now, but I'd imagine it would work as well since CT on it and r-b largely identical.

**Comment by sblatz** [comment]
That surprises me. Our implementation is basically just integrating AC  🤔 I wonder what we're doing differently

**Comment by NotWoods** [comment]
Related? #5034

**Comment by jonalmeida** [comment]
This is no longer an issue for me any more, so I'm going to close this. I suspect the same for #5034 as well.
