### ISSUE TITLE
[Bug] search engines shouldn't be shown by default when you're on a tab

### ISSUE THREAD

**Issue by cadeyrn** [mozilla-mobile/fenix#4566]
### Steps to reproduce

1. open a website
2. tap the address bar

### Actual behavior

There was a recent change to show all the search engines when tapping the address bar. Once you type something into the address bar the search engines disappear and you see suggestions from a search engine and from your history.

If you're not on the start screen but on a website and tap the address bar you also the the search engines and that's unexpected because:

a) On the start screen you start with an empty address bar. But if you're on a website the address bar is not empty. There should be the same behaviour in both cases for the non-empty address bar.
b) If you're on a website it's (almost?) sure that there is a URL in the address bar. I don't know why someone should search for the URL of the active tab in a search engine so there is not really a reason to show this screen _by default_ in this case.

### Expected behavior

You can see the search engines by default when tapping the address bar on the start screen but you don't see the search engines by default when tapping the address bar in a tab.

### Device information

* Android device: HTC U11 / Android 9.0
* Fenix version: master branch revision 3c1ce90f6f8ab6478b498ec9fdf5ab59831255bc

**Comment by ekager** [comment]
I think it could be fair that from a tab, the user could be clicking the search bar to complete a search and want to change the engine? Having it displayed doesn't seem to take anything away from the user?

**Comment by buttercookie42** [comment]
> I don't know why someone should search for the URL of the active tab in a search engine

Opening the current URL in the Wayback Machine for example.

**Comment by cadeyrn** [comment]
Fixed by #4736.
