### ISSUE TITLE
Set default "open in app"

### ISSUE THREAD

**Issue by ghost** [mozilla-mobile/fenix#4575]
previous issue was closed in error. a member directed me to:

1. load desired page
2. tap "open in app"
3. page loads again in app

compare to Chrome for Android, which allows you to set a default app for certain
links, then:

1. tap link to desired page
2. page loads in app

or Firefox for Android:

1. long press link to desired page
2. choose "open in app"
3. page loads in app

**Comment by Djfe** [comment]
like #3300 I would rather have the option.
Apps shouldn't automatically open in other apps unless I told Fenix to do so.
Fenix could ask you (open with fenix, open with app, checkbox: ask again (checked by default))

We would need a settingspage to set/reset these per app. (maybe even per domain, if that makes sense?)
is there a way to set them with a drop-down or is Firefox not able to ask the system which apps are installed? (just issue the OS to query the user manually)

the latter would be useful to set settings for installed apps before you even opened the first app link

**Comment by sblatz** [comment]
Our implementation currently is for security reasons. We chose to not default to sending users out of Fenix. That being said, giving the option to set a default seems reasonable.

**Comment by nahuhh** [comment]
@djfe I agree and had posted a similar request #3349

**Comment by kbrosnan** [comment]
This feature is in the Settings as `Open links in apps`
