### ISSUE TITLE
pin tab in collection

### ISSUE THREAD

**Issue by Djfe** [mozilla-mobile/fenix#4579]
### Why/User Benefit/User Problem
It would be nice if I would be able to pin one or several tabs inside a collection

for example: the YouTube subscription feed or the main page of a news website is pinned and below that are videos/articles I want to read later.
I open the pinned tab, if I want to explore more videos/articles or. I open one of the videos/articles to watch/read it and then remove it from my "watch later" collection.

This might be a contradiction to #4446 
the idea there is: sync open pinned tabs to mobile and make them available through one collection

But I'm also not sure if I like that approach, since you can't get notifications from such tabs. (collections have no session after all)

### Acceptance Criteria (how do I know when I’m done?)
Allow user to tab+hold tab in collection and then choose "pin" to pin it to the top of the collection (first entry, or one of the first if there are several pinned tabs)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-12943)

**Comment by vesta0** [comment]
@topotropic @boek something to consider :)

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812764

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
