### ISSUE TITLE
Automatically filter new or existing tabs into collections (similar to Thunderbird mail filter)

### ISSUE THREAD

**Issue by Djfe** [mozilla-mobile/fenix#4580]
### Why/User Benefit/User Problem
Depending on the implementation of collections it would be nice if Firefox could automatically sort new tabs into certain collection(s) depending on the domain or the app it was opened from (and not automatically download them in a tab, atleast when you let Fenix open tabs in the background without switching apps, like Firefox currently does)

For example Fenix would then add news urls from BBC into the news collection.
Urls that don't fall into any domain category should be sorted by the app they are opened from:
a collection for all links opened from the Facebook app that don't belong to a domain like the bbc
(I think, it makes sense to prioritize domain over app here, but it could be a setting)

If I surf on BBC and save an article, then Fenix should automatically add it to a collection if a filter applies else ask me which collection to choose.
Maybe give me the option to create a new filter for this type of url.
If I selected more than one tab and one filter doesn't apply to all tabs, then let the user choose.
Add a button that auto saves all selected tabs separately to the correct collection.

I know this is an advanced feature but quite useful imo.
It could be realized similarly to the mail filters in Thunderbird.

### Acceptance Criteria (how do I know when I’m done?)
* working tab filter system
* gui to configure filters
* auto filter tabs coming from other apps
* button to auto filter and save open tabs into collections

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-12944)

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812763

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
