### ISSUE TITLE
options for tabs in a collection (apart from opening)

### ISSUE THREAD

**Issue by Djfe** [mozilla-mobile/fenix#4581]
### Why/User Benefit/User Problem
I want an option like tab+hold on tabs in a collection that allows me to:

* open a tab in private tab (or the whole collection)
* save a tab to another collection
* move a tab to another collection

optional:
* copy link

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-12945)

**Comment by venetian-ftaires** [comment]
"Rename" and "Save as bookmark" would be great too.

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812762

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
