### ISSUE TITLE
collection custom icons

### ISSUE THREAD

**Issue by Djfe** [mozilla-mobile/fenix#4583]
### Why/User Benefit/User Problem
It would be nice to be able to choose a collection's icon.
Either one of the icons of the tabs (merged by icon url) or an icon of a list of default icons (like the ones from multi account containers https://addons.mozilla.org/de/firefox/addon/multi-account-containers/ )

### Acceptance Criteria (how do I know when I’m done?)
The menu for renaming a collection also allows the user to choose an icon for that collection.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-12946)

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812761

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
