### ISSUE TITLE
DNS over HTTPS

### ISSUE THREAD

**Issue by jawadalkassim** [mozilla-mobile/fenix#4584]
### Why/User Benefit/User Problem
As a user i want to Protect myself while browsing the web From Man-in-the-middle attack and make sure Attackers cannot trick users into visiting a fake website by manipulating DNS responses for domains that are outside their control.

### What/Requirements:
**Secure DNS**:
To ensure your DNS queries remain private, you should use a resolver that supports secure DNS transport such as DNS over HTTPS (DoH) or DNS over TLS (DoT).
**DNSSEC:**
DNSSEC allows a user, application, or recursive resolver to trust that the answer to their DNS query is what the domain owner intends it to be.
**TLS 1.3 :** is Supported In Firefox Fenix 👍
**Encrypted SNI:**
Encrypted SNI keeps the hostname private when you are visiting an Encrypted SNI enabled site on Cloudflare by concealing your browser’s requested hostname from anyone listening on the Internet.

### Acceptance Criteria (how do I know when I’m done?)
Dns-over-Https option in the settings or in about:config like Fennec browser.
You can test your browser here:
https://www.cloudflare.com/ssl/encrypted-sni/

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-12947)

**Comment by genodeftest** [comment]
Why not use DoT instead? It is less complex and has less overhead.

**Comment by finn0** [comment]
In Firefox Android, we do have support for DoH, but there is no UI to easily configure DoH settings like Firefox Quantum, we've to configure it from `about:config` settings which make things harder for novice FF users; although from Android 9 pie, we've support for [DoT](https://android-developers.googleblog.com/2018/04/dns-over-tls-support-in-android-p.html), but using DoH has its own pros like our DNS traffic is hidden inside HTTPS traffic. Do we've plan for implementing an UI in FF preview?

**Comment by vesta0** [comment]
@finn0 yes this is something we will be looking into later this year!

**Comment by dasolyn** [comment]
ESNI works well in latest Firefox Beta 75.0.0-beta.6

**Comment by SergeiFranco** [comment]
I would like the opposite (ability to turn off the DoT or DoH) as I pihole everything via VPN and my own VPS and I definitely do not trust cloudflare or whoever with my DNS data.

**Comment by hsaito** [comment]
As of 79.0.0 (Build #2015753875) even the ability to turn on this feature without guy is no longer available since about:config is no longer accessible, which is very unfortunate :-(

**Comment by yoasif** [comment]
Launching on Chrome in 85 https://blog.chromium.org/2020/09/a-safer-and-more-private-browsing.html

**Comment by madb1lly** [comment]
Hi all,

The settings are available in about:config, so is this just a UI thing or is there more to it? I have enabled it in about:config and according to about:networking#dns it's working.

Cheers 🙂

**Comment by andrew-aitchison** [comment]
hsaito is correct; this functionality is not available in v80 as about:config is no longer available.

madb1lly: As I understand it, this bug is abiut the UI.
https://github.com/mozilla-mobile/fenix/issues/14261 is _not_ a duplicate; it is a _regression_ - please reopen it.

**Comment by hsaito** [comment]
I'm bit surprised why they've decided to disable about:config, it's a very powerful feature that makes Firefox very flexible. Some of the other tuning including enterprise trust, etc., are currently only accessible through about:config. If that's not feasible, I would at least see prefs.js somewhere that users can edit, if it is the decision that about:config is no longer available.

**Comment by 0x391F** [comment]
> I'm bit surprised why they've decided to disable about:config, it's a very powerful feature that makes Firefox very flexible. Some of the other tuning including enterprise trust, etc., are currently only accessible through about:config. If that's not feasible to bring back about:config for any reason., I would at least want to see prefs.js somewhere that users can edit.

Yeah, I'm also couldn't understand why they dicide to disable about:config, what an awful decision!

**Comment by valenting** [comment]
> > I'm bit surprised why they've decided to disable about:config, it's a very powerful feature that makes Firefox very flexible. Some of the other tuning including enterprise trust, etc., are currently only accessible through about:config. If that's not feasible to bring back about:config for any reason., I would at least want to see prefs.js somewhere that users can edit.
> 
> Yeah, I'm also couldn't understand why they dicide to disable about:config, what an awful decision!

You can still use about:config on the Nightly channel.

**Comment by yoasif** [comment]
> You can still use about:config on the Nightly channel.

Or beta, if you prefer less possible breakage. :smile:

**Comment by 0x391F** [comment]
> > You can still use about:config on the Nightly channel.
> 
> Or beta, if you prefer less possible breakage. 😄

Hmm... How about stable release? Will about:config still exist?

**Comment by Oymate** [comment]
Come on we need to one up chrome! Ad this, please!

**Comment by cadeyrn** [comment]
see also https://bugzilla.mozilla.org/show_bug.cgi?id=1664878

**Comment by minutesinch** [comment]
cool

**Comment by lordgurke** [comment]
If you roll this out, please make it an optional Opt-In and not an Opt-Out feature!
I'm more concerned about privacy with using DoH with Cloudflare or Google as with using my provider's regular DNS (Germany has more strict rules about privacy as Cloudflare or Google could offer)

**Comment by andreicristianpetcu** [comment]
@lordgurke Mozilla made it opt-out for US and opt-in for everybody else. US ISPs are really bad with privacy. It's looking into adding more DoH providers. Currently nextdns is an option on desktop. https://wiki.mozilla.org/Security/DOH-resolver-policy

**Comment by sheikh-azharuddin** [comment]
There must be a UI option to configure secure dns or dns resolver like other chromium browser..
Esni feature is removed from about:config in latest nightly....not sure why😡😒

**Comment by valenting** [comment]
ESNI has been deprecated in favour of ECH: https://blog.cloudflare.com/encrypted-client-hello/

**Comment by sheikh-azharuddin** [comment]
> ESNI has been deprecated in favour of ECH: https://blog.cloudflare.com/encrypted-client-hello/

Thanks for the info... As per article the feature is still in testing and not ready to be deployed.. It also says esni will be supported by cloudflare till ech is ready.. So can you please enable the feature again till ech is fully ready?

![Screenshot_20201215-135831561~2](https://user-images.githubusercontent.com/58127841/102192187-70bd9080-3ee0-11eb-889d-814f7fd598d7.jpg)

**Comment by valenting** [comment]
This issue is not the proper place for these discussions.
https://bugzilla.mozilla.org/show_bug.cgi?id=1667743

**Comment by Snowden-rgb** [comment]
+1 need this

**Comment by MasterInQuestion** [comment]
&#xA0;&#xA0;&#xA0;&#xA0;[ Quote etanot @ CE 2019-12-23 01:37:34 UTC:
[https://github<i>.</i>com/mozilla-mobile/fenix/issues/4584#issuecomment-568064713](https://github.com/mozilla-mobile/fenix/issues/4584#issuecomment-568064713)
&#xA0;&#xA0;&#xA0;&#xA0;... have support for DoH, but there is no UI to easily configure DoH settings ... ]
<.>&#xA0;&#xA0;&#xA0;&#xA0;[ Quote cadeyrn @ CE 2020-09-09 10:52:39 UTC:
[https://github<i>.</i>com/mozilla-mobile/fenix/issues/4584#ref-issue-696705690](https://github.com/mozilla-mobile/fenix/issues/4584#ref-issue-696705690)
&#xA0;&#xA0;&#xA0;&#xA0;Add UI to turn on DNS over HTTPS support (TRR) ]
<^>&#xA0;&#xA0;&#xA0;&#xA0;A somewhat clumsy but working workaround:
&#xA0;&#xA0;&#xA0;&#xA0;.
&#xA0;&#xA0;&#xA0;&#xA0;Adding below to Bookmarks:
&#xA0;&#xA0;&#xA0;&#xA0;[
&#xA0;&#xA0;&#xA0;&#xA0;|&#x2A;| Name: &#x5C;..
&#xA0;&#xA0;&#xA0;&#xA0;|&#x2A;| URL: about:config?filter=^intl&#x5C;.accept_languages|network&#x5C;.trr&#x5C;.(?:mode|uri)%24 ]

&#xA0;&#xA0;&#xA0;&#xA0;Related:
&#xA0;&#xA0;&#xA0;&#xA0;|&#x2A;| [https://github<i>.</i>com/mozilla-mobile/fenix/issues/16287](https://github.com/mozilla-mobile/fenix/issues/16287)
&#xA0;&#xA0;&#xA0;&#xA0;|&#x2A;| https://regex101.com/

**Comment by sheikh-azharuddin** [comment]
This is there in all chromium browsers (Vivaldi, brave, kiwi etc) should be added in firefox!

**Comment by MasterInQuestion** [comment]
&#xA0;&#xA0;&#xA0;&#xA0;A few notes on the subject:
&#xA0;&#xA0;&#xA0;&#xA0;.
&#xA0;&#xA0;&#xA0;&#xA0;At the moment:
&#xA0;&#xA0;&#xA0;&#xA0;[ [https://www.cloudflare.com/ssl/encrypted-sni/](https://www.cloudflare.com/ssl/encrypted-sni/) ] seems to only support ESNI but not ECH.
&#xA0;&#xA0;&#xA0;&#xA0;[ [https://crypto.cloudflare.com/cdn-cgi/trace](https://crypto.cloudflare.com/cdn-cgi/trace) ] seems to be one of the very few (if not the only) sites that support ECH.

&#xA0;&#xA0;&#xA0;&#xA0;Additional info:
&#xA0;&#xA0;&#xA0;&#xA0;[
&#xA0;&#xA0;&#xA0;&#xA0;|&#x2A;| ECH / ESNI related (Firefox inclined) (in French)
&#xA0;&#xA0;&#xA0;&#xA0;|&#x2A;| [https://lafibre.info/cryptographie/encrypted-sni/24](https://lafibre.info/cryptographie/encrypted-sni/24)
&#xA0;&#xA0;&#xA0;&#xA0;|&#x2A;| Google Translate: [https://translate.google.com/translate?hl=en&sl=fr&tl=en&u=https://lafibre.info/cryptographie/encrypted-sni/24](https://translate.google.com/translate?hl=en&sl=fr&tl=en&u=https://lafibre.info/cryptographie/encrypted-sni/24) ]
&#xA0;&#xA0;&#xA0;&#xA0;,
&#xA0;&#xA0;&#xA0;&#xA0;[
&#xA0;&#xA0;&#xA0;&#xA0;|&#x2A;| [Question] Is such DoH (DNS over HTTPS) implementation a brilliant folly?
&#xA0;&#xA0;&#xA0;&#xA0;|&#x2A;| [https://github<i>.</i>com/curl/curl/issues/9160](https://github.com/curl/curl/issues/9160)
<.>&#xA0;&#xA0;&#xA0;&#xA0;|&#x2A;| Note: Similar behavior also in Chrome, Firefox, etc. . ]

**Comment by danyhm** [comment]
It seems the DoH and DoT are getting more important since some "countries" are now tampering the DNS results deliberatly. This is in addition to the privacy concerns already mentioned in this issue.

Using DoH with firefox desktop is straightforward but for android this option is not available. The about:config page is blocked and there's no way to enable DoH for android below 9 system-wide.

Chrome already has DoH option accessible. But I want to stick to firefox for nostalgic reasons.

Also enabling DoH system-wide has it's own disadvantages.

I agree with the people that say this is not a feature request any more. It's getting more like a reggresion.

Just like the HTTPs-everywhere was implemented and is important, DoH and DoT should be considered the same in matters of security and privacy

**Comment by MasterInQuestion** [comment]
I suppose Firefox without Nightly is unusable.

    And I'd suggest doing more research before making rash conclusions.

**Comment by 424344** [comment]
> The about:config page is blocked

you could switch to fennec from f-droid: it's compiled from firefox *stable* release, and enables about:config.
it also enables custom extension collections (so you can install any extension you want) and disables some mozilla telemetry.

https://f-droid.org/en/packages/org.mozilla.fennec_fdroid/

**Comment by cpeterso** [comment]
This bug is tracked in Bugzilla here: https://bugzilla.mozilla.org/show_bug.cgi?id=1664878

DoH is not enabled by default in Firefox on Android yet due to performance issues.

**Comment by sheikh-azharuddin** [comment]
> This bug is tracked in Bugzilla here: https://bugzilla.mozilla.org/show_bug.cgi?id=1664878
> 
> DoH is not enabled by default in Firefox on Android yet due to performance issues.

Sorry to say but that was updated literally 2 years ago! While all chromium browsers have it with no impact I don't understand why no one taking it on priority and fixing..seems for mozilla priority items are pocket stories, wallpapers, visual styles, search engines etc rather than important privacy features..another 2 items are push notifications and advance media notification!

And then there is stale bot deployed to close the cases if not taken care by anyone! So how come it is users fault if no one from mozilla is picking up the tickets!
