### ISSUE TITLE
[Bug]Inconsistent display of the "Find in page" bar in landscape mode

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#4587]
## Steps to reproduce
1. Navigate to https://en.wikipedia.org/wiki/Main_Page
2. Tap on the 3dot button and select "Find in page"
3. Enter a letter or a word and tap on the next button "v" 
4. Rotate the device in landscape mode

### Expected behavior
The "Find in page" bar is displayed properly in landscape mode (from side to side).

### Actual behavior
The "Find in page" bar keeps the aspect ratio from the portrait view.

### Device information
* Android device: 
• Google Pixel 3a (Android 9)
• Samsung Galaxy Tab A (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7.0)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

* Fenix version: Fenix Nightly Build #12190111 from 7/8

### Notes
► Video Google Pixel 3a 
![20190807_155057](https://user-images.githubusercontent.com/51314259/62624876-bea9a800-b92c-11e9-93ba-92cc447907d4.gif)

**Comment by sblatz** [comment]
Note: this is **not reproducible** in sample browser. This is a Fenix side issue.

**Comment by darkwing** [comment]
I can no longer reproduce this in Fenix:

<img width="1598" alt="WhatISee" src="https://user-images.githubusercontent.com/46655/74279437-879fbf00-4ce0-11ea-8fd5-e3b12628e8cd.png">

The Find in Page bar always displays the paging and result counts at the far right of the screen, even after many horizontal/vertical switches.

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest `Nightly #20430607 from 2/12` using the following devices:
• Google Pixel 3a XL (Android 10)
• Google Pixel 3a (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7.0.0)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

► Video
![20200212-095053](https://user-images.githubusercontent.com/51314259/74314244-cf285880-4d7d-11ea-943e-01abd1c46da4.gif)
