### ISSUE TITLE
[Bug] Non-global DNS entries are searched rather than opened 

### ISSUE THREAD

**Issue by Djfe** [mozilla-mobile/fenix#4588]
## Steps to reproduce
Open DNS entries that aren't valid globally like
fritz.box
speedport.ip

### Expected behavior
Fenix resolves the domain to the local ipv4 of your router
192.168.178.1
192.168.2.1

### Actual behavior
Fenix searches on Google instead of querying the DNS like it's supposed to

### Device information

* Android device: OnePlus 3T
* Fenix version: 69.0-20190805070043

**Comment by boek** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1639089

**Comment by Djfe** [comment]
I just retested both router pages, this is working by now ( I attached screenshots)
I'm going to close this issue now.

![Screenshot_20200519-081614_Firefox_Preview](https://user-images.githubusercontent.com/5685512/82291570-80581380-99a9-11ea-9030-89c0c13edc73.png)
![Screenshot_20200519-081624_Firefox_Preview](https://user-images.githubusercontent.com/5685512/82291581-864df480-99a9-11ea-87c1-c19a8d7ef961.png)

**Comment by Djfe** [comment]
Version info
![Screenshot_20200519-082318_Firefox_Preview](https://user-images.githubusercontent.com/5685512/82291868-11c78580-99aa-11ea-8b4f-5a53875c73e0.png)
