### ISSUE TITLE
[Bug][Tablet]"Entering full screen mode" snackbar isn't properly displayed 

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#4591]
## Steps to reproduce
1. Navigate to youtube.com
2. Play any video and enter full screen mode
3. Check the snackbar

### Expected behavior
"Entering full screen mode" snackbar should be displayed from side to side.
The String should be displayed on one line.

### Actual behavior
"Entering full screen mode" snackbar looks cramped, and the string is displayed on 2 lines.

### Device information

* Android device: 
• Samsung Galaxy Tab A (Android 9)

* Fenix version: Fenix Nightly Build #12190111 from 7/8

### Notes

►Video
![20190807_165323](https://user-images.githubusercontent.com/51314259/62629102-38459400-b935-11e9-9a2b-e9a8087cd640.gif)

**Comment by darkwing** [comment]
I can no longer reproduce this issue:

![rotate](https://user-images.githubusercontent.com/46655/74275698-02b1a700-4cda-11ea-8ed0-d806c44474ca.gif)

The snackbar always takes up the entire width before and after rotation.

@AmyYLee Do we want this to float in the center?  (i.e only as wide as its contents), or is the full width OK?

**Comment by AndiAJ** [comment]
Hi @darkwing , I've re-checked this matter on the latest `Nightly Build # 20440606 from 2/13 `using the following devices:
• Google Pixel 3a XL (Android 10)
• Google Pixel 3a (Android 9)
• Samsung Galaxy Tab A (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7.0)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

It seems to be a device specific issue, namely, on the Samsung Galaxy Tab A tablet the snackbar  doesn't take up the full width of the display neither in portrait nor in landscape view.


► Videos from Samsung Galaxy Tab A 
![20200213-093013](https://user-images.githubusercontent.com/51314259/74412106-65738180-4e45-11ea-907f-2d9614ae940d.gif)

![20200213-093108](https://user-images.githubusercontent.com/51314259/74412181-86d46d80-4e45-11ea-9de1-893780c5c0f2.gif)


► Videos from Google Pixel 3a
![20200213-093225](https://user-images.githubusercontent.com/51314259/74412516-488b7e00-4e46-11ea-99e9-bb4b3f874efe.gif)

![20200213-093255](https://user-images.githubusercontent.com/51314259/74412354-e763aa80-4e45-11ea-86a4-bcadf52994f8.gif)

I'll remove the QA needed label.

**Comment by AmyYLee** [comment]
> I can no longer reproduce this issue:
> 
> ![rotate](https://user-images.githubusercontent.com/46655/74275698-02b1a700-4cda-11ea-8ed0-d806c44474ca.gif)
> 
> The snackbar always takes up the entire width before and after rotation.
> 
> @AmyYLee Do we want this to float in the center? (i.e only as wide as its contents), or is the full width OK?

Hi, the snackbar should expand to the full width of the screen with the string on one line and to the left like in portrait mode. Thanks
