### ISSUE TITLE
Migrate Collections to LibState

### ISSUE THREAD

**Issue by liuche** [mozilla-mobile/fenix#4596]
## User Story
As a developer I'd like Collections to implement LibState.

See Search component #3985 for guidelines, or reach out to Christian, Sebastian, Jeff.

## Dependencies
None

### Acceptance Criteria
* Collections implements LibState
* Collections has tests

**Comment by liuche** [comment]
We shouldn't block on the Collections redesign - the full redesign isn't going to happen immediately, so it's more important to get the migration done, rather than having both architectures in-tree.

**Comment by boek** [comment]
Dup of #5574

**Comment by abodea** [comment]
I've checked the following but I haven't encountered any issues with `Nightly 191024 06:01 (Build #12970607)📦: 18.0.0, ef631b6df🦎: 71.0a1-20191021095628` from **24/10 using a Samsung Galaxy S10+(Android 9).**
- Select tabs for a new collection, using long tap
- Save open tabs from the overflow menu
- Create the first collection
- Create a new collection (others already exist)
- Can navigate back to each step of the collection creation process
- Expand to see tabs in a collection
- Rename collection
- Open all tabs in a collection
- Share all tabs in a collection
- Add a new tab to a collection
- Remove a tab from a collection
- Delete a collection
