### ISSUE TITLE
Migrate Home to LibState

### ISSUE THREAD

**Issue by liuche** [mozilla-mobile/fenix#4597]
## User Story
As a developer I'd like Home to implement LibState.

See Search component #3985 for guidelines, or reach out to Christian, Sebastian, Jeff.

## Dependencies
None

### Acceptance Criteria
* Home implements LibState
* Home has tests

**Comment by liuche** [comment]
We shouldn't block on the Homescreen redesign - the full redesign isn't going to happen immediately, so it's more important to get the migration done, rather than having both architectures in-tree.

**Comment by liuche** [comment]
Going to move this out of the sprint for now, to focus on prioritize feature work.

**Comment by boek** [comment]
Dup of #5574
