### ISSUE TITLE
Don't display installed search engines when opening the search screen

### ISSUE THREAD

**Issue by pwd-github** [mozilla-mobile/fenix#4609]
## Steps to reproduce
1. Open Fenix
2. Press "New Tab" 

### Expected behavior
I see my Top Sites or Recent History

### Actual behavior
I see a list of search engines I have installed

### Device information

* Android device: LG G6 (Android 8)
* Fenix version: Nightly 190807 19:14 (Build #12191938)
📦: 7.0.0
🦎: 69.0-20190805070043

**Comment by sblatz** [comment]
This is the current expected behavior outlined by @Verdi in https://github.com/mozilla-mobile/fenix/issues/1744. 

Putting a needs ux feedback on this to consider changing :)

**Comment by Verdi** [comment]
Yes this is the expected behavior but we could make the feature more understandable by using the copy that we'll be using in the new desktop design. I filed issue [4664](https://github.com/mozilla-mobile/fenix/issues/4664) for that.
