### ISSUE TITLE
DiffUtil.calculateResult should move off of the Main Thread

### ISSUE THREAD

**Issue by colintheshots** [mozilla-mobile/fenix#4620]
Currently, several screens in Fenix use DiffUtil to improve the performance of the RecyclerView updates on those screens. We should move the calculation of list diffs to a background thread to avoid lost frames and freezing of the UI.

The classes currently affected include BookmarkAdapter and CollectionCreationTabListAdapter. It appears that classes using the new RecyclerView ListAdapter along with DiffUtil do not have this problem. They already seem to background diff calculations.

**Comment by hawkinsw** [comment]
@colintheshots Does this happen on startup or periodically during execution?

**Comment by hawkinsw** [comment]
I do not see this being executed for 'Startup to Home Activity' nor 'Startup to Browser'. cc @colintheshots

**Comment by colintheshots** [comment]
This is used for calculating the differences between lists. So history and bookmarks would be the top pages and tabs and collections may be significant as well. I believe ListAdapter automatically does the right thing here, so tabs and collections may already be executing diff calculations off of the main thread.
