### ISSUE TITLE
Create unit tests for Extensions

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#4622]
We should write unit tests for the extension functions we use. This ticket will encompass writing tests for all of the extensions. If we feel this is too large for one ticket, let's break a larger component out. 

* Activity
* BookmarkNode
* BrowserIcons
* Context
* Drawable
* Fragment
* Log
* NavController
* Resources
* Session
* String
* TabCollection
* View

**Comment by Pheonix73** [comment]
I have not really worked with unit test before. But would love to assist in this issue. @sblatz

**Comment by sblatz** [comment]
Hey @Pheonix73 we have @kglazko working on this

If you're interested in adding some tests, tackling one of our [controller tickets](https://github.com/mozilla-mobile/fenix/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+controller) may be a good place to start 😄

**Comment by Pheonix73** [comment]
@sblatz Which of them in particular. And also is there a communication channel?

**Comment by sblatz** [comment]
@Pheonix73 any of those are up for grabs! You can reach me on IRC. I'm @sblatz in the #fenix channel: https://irccloud.mozilla.com/#!/ircs://irc1.dmz.mdc1.mozilla.com:6697/%23fenix

**Comment by Pheonix73** [comment]
@sblatz Alright. It seems I don't have permission to that irc channel.
