### ISSUE TITLE
Create a tip in Focus for launch in private mode 

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#4623]
We should utilize [homescreen tips](https://github.com/mozilla-mobile/focus-android/wiki/Homescreen-Tips) to create a tip in Focus that will tell users about our private mode in Fenix. 

We just need copy for what this string should say.

@mheubusch to provide that?

**Comment by sblatz** [comment]
Related to https://github.com/mozilla-mobile/fenix/issues/419

**Comment by sblatz** [comment]
@vesta0 to determine the priority of this messaging :)

**Comment by AmyYLee** [comment]
@mheubusch We will need copy for this "tip"

**Comment by vesta0** [comment]
Issue moved to [mozilla-mobile/focus-android #4329](https://github.com/mozilla-mobile/focus-android/issues/4329) via [**ZenHub**](https://www.zenhub.com/)
