### ISSUE TITLE
Delete browsing data string unclear

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#4625]
The string in the delete browsing data screen is unclear that I'm only deleting the one I selected. It sounds like it's going to destroy all of my history even though I only selected one :O 

I think this is because we're just currently using the same string as the one found after pressing "Clear browsing history" in the history library view.

<img width="350" alt="image" src="https://user-images.githubusercontent.com/4400286/62736419-2b32ae80-b9e2-11e9-920d-65417e187f7c.png">

**Comment by Pheonix73** [comment]
Would like to work on this @sblatz

**Comment by sblatz** [comment]
Hey @Pheonix73 let's get strings from @mheubusch and then go for it 😄

**Comment by Pheonix73** [comment]
Nice!

**Comment by mheubusch** [comment]
Hi @sblatz - I just want to check with @topotropic - do we think this prompt is necessary, or can we handle with with a snackbar saying "Selected data deleted" with an UNDO button? If a prompt is necessary, change to "This will delete the data you selected."

**Comment by sblatz** [comment]
@mheubusch a prompt is being used in place of a snackbar due to technical complexity of using an undo snackbar here (we've had lots of issues with them in the past, especially around deletion of data). 

@Pheonix73 let's go with @mheubusch's recommendation: "This will delete the data you selected."

Thanks @mheubusch!

**Comment by Pheonix73** [comment]
@sblatz Can I be assigned to this?

**Comment by Pheonix73** [comment]
@sblatz Can I be assigned to this?

**Comment by Pheonix73** [comment]
@sblatz  @mheubusch quick question before i update my PR. 
1. When changing the Strings, won't you also need to change the strings that were translated to other languages?
2. I notices that "delete_browsing_data_prompt_message" is not available in other languages also.

**Comment by ekager** [comment]
We have updated mocks for these screens, so I'm closing this bug
