### ISSUE TITLE
[Bug] Show 'Sync is on' toast only on first login

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/fenix#4633]
## Steps to reproduce
1. Sign into a Sync account.
2. Observe the 'Sync is on' toast.
3. Close and swipe away the app.
4. Re-open the app.

### Expected behavior
The toast is only seen once on the first login.

### Actual behavior
The toast is seen every time the app is cold booted.

### Device information

* Android device: n/a
* Fenix version: n/a

**Comment by jonalmeida** [comment]
To fix this, we can use the `newAccount` bool in [the account observer](https://searchfox.org/mozilla-mobile/source/fenix/app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt#754) to know if this is the first login and only then show the toast.

**Comment by dragneelfps** [comment]
@jonalmeida can I work on this?

**Comment by jonalmeida** [comment]
@dragneelfps I've mostly gone with intuition on what the fix should be. Let's wait for @vesta0 to confirm if this an issue first.

**Comment by dragneelfps** [comment]
@jonalmeida sure.

**Comment by vesta0** [comment]
This is definitely looks like a regression. The expected behavior is to see the 'Sync is on' toast on the first login as @jonalmeida pointed out.

**Comment by dragneelfps** [comment]
@vesta0 so should I raise a PR to fix this regression(using the `newAccount` bool as pointed out by @jonalmeida)?

**Comment by jonalmeida** [comment]
> @vesta0 so should I raise a PR to fix this regression(using the `newAccount` bool as pointed out by @jonalmeida)?

@dragneelfps yes, please do! :)

**Comment by vesta0** [comment]
Yes please @dragneelfps :+1:

**Comment by dragneelfps** [comment]
@vesta0 I have raised PR #4676 for this issue.

**Comment by sv-ohorvath** [comment]
Verified as fixed on RC 1.3.0-rc1
