### ISSUE TITLE
Add ability to set custom background for homescreen and URL bar

### ISSUE THREAD

**Issue by Scripterr** [mozilla-mobile/fenix#4638]
### Why/User Benefit/User Problem
Right now you can set the background for url bar in fennec through the AMO site but as in current there no way right now to use add-ons in fenix. It would be great to able to set a background image for homescreen and URL/bottom bar from local storage, as it would also give users a feel of customization and personalization.
This feature is available in yandex browser and UC browser where you can set a image for homescreen (in UC browser where it applies for all other browser pages like settings page).
**Screenshot from yandex browser homescreen**
![Screenshot_20190725-145842~2](https://user-images.githubusercontent.com/42364681/62757033-61674100-ba69-11e9-8928-65b6425b9549.png)
**Screenshot from fennec for URL bar**
![Screenshot_20190725-152645~2](https://user-images.githubusercontent.com/42364681/62757141-d175c700-ba69-11e9-96be-4c26949fec4b.png)

### What/Requirements
Add option to select an image from local storage for homescreen and a separate option to select an image for URL bar.

### Acceptance Criteria (how do I know when I’m done?)
Can see custom background for homescreen and URL bar set by the user.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-12981)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807084

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
