### ISSUE TITLE
[Bug]  mobile.twitter.com - The contextual menu for text "Copy/Select/Search" is displayed after tapping on an image

### ISSUE THREAD

**Issue by karlcow** [mozilla-mobile/fenix#4639]
As tested by @yaomtc 
initially reported on https://github.com/webcompat/web-bugs/issues/31197

URL: https://mobile.twitter.com/oh__honey__/status/1128688210874208256/photo/1

Browser / Version: Firefox Mobile 68.0
Operating System: Android
Tested Another Browser: Yes

Problem type: Something else
Description: When you tap the image in Firefox, the Copy/Select All/... menu appears
Steps to Reproduce:
Open a tweet with an image in it, tap the image to view it in twitter's image viewer, and then tap the image again. Though there is no text visible on the screen at this point, tapping the image brings up a text copying dialog.

Tested with:
Browser / Version: Firefox Nightly Mobile 68.0a1 (2019-05-16), Chrome Mobile 74.0.3729.157
Operating System: Huawei P10 (Android 8.0) - 1080 x 1920 pixels (~432 ppi pixel density)

**Comment by ekager** [comment]
I don't think I can repro anymore. But let's have QA verify

**Comment by abodea** [comment]
I couldn't reproduce this on the latest **Nightly build 14/10** with **Google Pixel 4 XL (11).**
I was able to copy and see the contextual menu without problems.
