### ISSUE TITLE
[Bug] about:support is empty

### ISSUE THREAD

**Issue by hakkikaancaliskan** [mozilla-mobile/fenix#4641]
## Steps to reproduce
Open about:support

### Expected behavior

Page is full with infos

### Actual behavior

No info :/

### Device information

* Android device: Xperia XZ1 Android 9
* Fenix version:
Nightly 190808 23:13 (Build #12202320)
📦: 8.0.0, 865feaf44
🦎: 69.0-20190808090046
![Screenshot_20190809-133113](https://user-images.githubusercontent.com/17825767/62773202-410ba680-baaa-11e9-947f-417d369313d7.png)

**Comment by staktrace** [comment]
Still happening on latest nightly

**Comment by ekager** [comment]
Closing for https://github.com/mozilla-mobile/fenix/issues/1353
