### ISSUE TITLE
[Bug] Delete browsing history discrepancies

### ISSUE THREAD

**Issue by mikeGolf08** [mozilla-mobile/fenix#4642]
## Steps to reproduce

1. Open any website
2. Head to settings
3. **Delete browsing history**
4. Select "**Open tabs**" (a minimum of one open tab is required for reproducing this bug)
5. Delete the selected data

### Expected behavior

It **stays on the delete browsing history site** like it does when selecting one of the other options (Collections, Browsing history and site data) only.

### Actual behavior

After deleting the "Open tabs" it **closes the settings** and shows the initial state (new tab).

### Device information

Oneplus 3T
* Android device: 9 OOS 9.0.5
* Fenix version: Nightly 190809 06:02 (Build #12210610)
package: 8.0.0, 865feaf44
lizard: 69.0-20190808090046

**Comment by sblatz** [comment]
I cannot reproduce this on master 😕

**Comment by mikeGolf08** [comment]
> I cannot reproduce this on master confused

After a reinstall I had deleted browsing data and the issue still persists but only if I select "Open Tabs" **and** "Browsing history and site data" ...

#4788 [Bug] Cleaning Open Tabs will brake Fenix

**Comment by mikeGolf08** [comment]
Since the current state is that the settings close in any case I have closed the ticket.
