### ISSUE TITLE
[Bug] Nightly freezes after signing in / out, then closes

### ISSUE THREAD

**Issue by softvision-miralobontiu** [mozilla-mobile/fenix#4644]
## Steps to reproduce
1. Go to Settings - Turn on Sync - Use email instead
2. Insert valid credentials and observe.

### Expected behavior
The user is signed in, the app doesn't freeze or close.

### Actual behavior
The app freezes then closes.

### Device information
* Android device: OnePlus 5T (Android 9), Samsung Galaxy Note 8 (Android 9), Nexus 5 (Android 6.0.1)
* Fenix version: 190809 (#12210609)
* The same behavior on signing out!

[logcat.txt](https://github.com/mozilla-mobile/fenix/files/3486381/logcat.txt)

The app freezes in this state a few seconds:
![Screenshot_20190809-153847](https://user-images.githubusercontent.com/40694158/62779668-86d16a80-babc-11e9-82ac-f2f34c3fed37.png)

**Comment by ekager** [comment]
I'm hoping this is fixed by #4651 . I just triggered a new nightly, let's retest as soon as that comes through

**Comment by softvision-miralobontiu** [comment]
This issue no longer reproduces on the latest Nightly build 190812 (#12240720) with Samsung Galaxy Note 8 (Android 9), Nexus 5 (Android 6.0.1).
I will close this issue.
