### ISSUE TITLE
[Bug] App closes after trying to create a Collection

### ISSUE THREAD

**Issue by softvision-miralobontiu** [mozilla-mobile/fenix#4645]
## Steps to reproduce
1. Open a few tabs.
2. Tap on "Save to collection".
3. Tap on "Select All" from the top right corner.
4. Tap on "Deselect All".

### Expected behavior
Tabs should be deselected.

### Actual behavior
The app closes.

### Notes
App closes also when selecting manually a tab and try to tap "Save".
Cannot create a collection.

### Device information
* Android device: all
* Fenix version: Nightly build 190809 (#12210609)

[logcat.txt](https://github.com/mozilla-mobile/fenix/files/3486418/logcat.txt)

**Comment by BranescuMihai** [comment]
Hey! Is this bug still reproducible? Tested on Samsung S10, works as expected

**Comment by softvision-miralobontiu** [comment]
This issue is no longer reproducible.
Verified with Nexus 6P (Android 8.1), and HTC Desire 820 (Android 6.0.1), on the latest Nightly build 10/24.
