### ISSUE TITLE
[Bug] Video preview broken if link is opened in a new tab

### ISSUE THREAD

**Issue by Dexterp37** [mozilla-mobile/fenix#4647]
## Steps to reproduce

- Open https:://www.repubblica.it ;
- Open a video shown anywhere on the home in a separate tab, but **don't go to the tab just now**;
- Open another video as did above, but **don't go to the tab just now**;
- Go to the tab selection page, open the tab of any of the two videos;

### Expected behavior

The video preview occupies the full width of the screen, fitting its parent DOM element.

### Actual behavior

The video preview will only be a few pixels large (e.g. 20x20) and will show in the top left of its parent container, which will be shown as black.

### Device information

* Android device: Samsung Galaxy A5
* Fenix version: nigthly 190808 23:13 (build #12202320)

Note: this is not a regression, it's been like this since the early beginning :)

**Comment by boek** [comment]
@Dexterp37 Are you still able to reproduce this?

**Comment by Dexterp37** [comment]
> 
> 
> @Dexterp37 Are you still able to reproduce this?

Yes, I can consistently reproduce this in the latest nightly.
