### ISSUE TITLE
[Bug] Fenix closes after turning the "Show visited sites and bookmarks" toggle ON/OFF

### ISSUE THREAD

**Issue by softvision-miralobontiu** [mozilla-mobile/fenix#4649]
## Steps to reproduce
1. Go to Settings - Search engine and toggle "Show visited sites and bookmarks" toggle OFF (or ON if it was OFF).

### Expected behavior
The app should continue to work.

### Actual behavior
The app closes.

### Device information
* Android device: Samsung Galaxy Note 8 (Android 9), Nexus 5 (Android 6.0.1)
* Not reproducible on Sony Xperia Z5 Premium (Android 7.1.1)
* Fenix version: Nightly 190809 (#12210609)

Logcat from Samsung Galaxy Note 8
[logcat.txt](https://github.com/mozilla-mobile/fenix/files/3486566/logcat.txt)

**Comment by ekager** [comment]
I'm hoping this is fixed by #4651 . I just triggered a new nightly, let's retest as soon as that comes through

**Comment by softvision-miralobontiu** [comment]
This issue doesn't reproduce on the latest Nightly build 190812 (#12240720) with Samsung Galaxy Note 8 (Android 9), Nexus 5 (Android 6.0.1).
I will close this issue.
