### ISSUE TITLE
[Bug] Crash/ANR when enabling/disabling Tracking protection

### ISSUE THREAD

**Issue by softvision-miralobontiu** [mozilla-mobile/fenix#4653]
## Steps to reproduce
1. Go to Settings - Tracking protection and enable or disable it.

### Expected behavior
The toggle should switch, no crash involved.

### Actual behavior
ANR, then crash.

### Device information
* Android device: Samsung Galaxy Note 8 (Android 9), Nexus 5 (Android 6.0.1)
* Fenix version: 190809 (#12210609)

[logcat.txt](https://github.com/mozilla-mobile/fenix/files/3486715/logcat.txt)

![20190809_171310_Trim](https://user-images.githubusercontent.com/40694158/62785747-f0a44100-bac9-11e9-8748-5ed15c240171.gif)

**Comment by ekager** [comment]
I'm hoping this is fixed by #4651 . I just triggered a new nightly, let's retest as soon as that comes through

**Comment by Pheonix73** [comment]
Alright. @ekager I sent you a DM on Twitter regarding contributing more to this repo.

**Comment by softvision-miralobontiu** [comment]
This crash doesn't reproduce on the latest Nightly build 190812 (#12240720) with Samsung Galaxy Note 8 (Android 9), Nexus 5 (Android 6.0.1).
I will close this issue.
