### ISSUE TITLE
[Bug] [L10N] Use quantity strings so that plurals appear correctly in different languages.

### ISSUE THREAD

**Issue by NotWoods** [mozilla-mobile/fenix#4655]
In some spots we have separate string resources such as: "Tab sent!" and "Tabs sent!". Rather than using an if statement based on the number of tabs, this should be a [quantity string](https://developer.android.com/guide/topics/resources/string-resource#Plurals). 

This is a bug in some locales where different quantities get special treatment.

### Strings to consolidate
These strings should be consolidated into a single quantity string, and are currently loaded with an if statement.
- sync_sent_tabs_snackbar & sync_sent_tab_snackbar
- create_collection_save_to_collection_tab_selected & create_collection_save_to_collection_tabs_selected
- create_collection_tabs_saved & create_collection_tab_saved
- snackbar_tabs_deleted & snackbar_tab_deleted
- tab_counter_content_description_one_tab
- tab_counter_content_description_multi_tab

### Strings to update
These strings should be replaced with a quantity string and currently are always plural, even in English.
- preferences_delete_browsing_data_tabs_subtitle
- preferences_delete_browsing_data_browsing_data_subtitle
- preferences_delete_browsing_data_collections_subtitle
- bookmarks_multi_select_title
- history_multi_select_title
- history_delete_some

**Comment by liuche** [comment]
@Pike @Delphine is this something that L10N can do? Or should we close this?

**Comment by NotWoods** [comment]
They've stated elsewhere that L10N currently can't support quantity strings. I'm mostly using this issue to catalogue what strings need changing for the future.

**Comment by Pike** [comment]
Yeah, this isn't supported now. We'd need to prioritize this across the various components involved.

**Comment by liuche** [comment]
Okay, I think keeping a reference to the strings is fine, but I'll close it for now and we can reopen when this gets prioritized in L10N's timeline. I think it's a good thing to keep in mind, but isn't really actionable right now.

@Pike this is something that we'd be interested in doing though, so please ping back here if you have updates!
