### ISSUE TITLE
Update voice search portion of search widget

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#4657]
Verdi mentioned that we could update the voice search screen of the search widget. Screenshot from him incoming :)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-12996)

**Comment by Verdi** [comment]
Just an example (2 min photoshop hack).
![voice](https://user-images.githubusercontent.com/107992/62797159-96db5100-baa0-11e9-940d-19f4e7bcf415.jpg)

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807581

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
