### ISSUE TITLE
[Telemetry] Private Mode Features

### ISSUE THREAD

**Issue by vrudesai** [mozilla-mobile/fenix#4658]
Owner: Product Manager Intern

Overall, this issue is for the new private mode features.

All under this meta: [Meta] Open In Private Browsing #4390:

Launcher Icon for PBM: #419
Allow user to always open 3rd party links in PBM + TP: #514 
Persistent notification to close private browsing tabs: #2053 
Delete all Private Tabs Redesign: #2834 

#### Description & Product Manager / Data Scientist User Story
As a product owner intern, I want to know if users find the above features usable and discoverable. The data will also help us prepare for the sunset of Focus and the best way to onboard users onto Fenix.

#### Hypothesis
We believe this feature is useful to users, and successful when:

- % of Fenix users adding Private Mode as Default Increases
- MAU increases as a result of Focus users hopping on Fenix
- % of Fenix users tapping on garbage icon increases 

#### What questions will you answer with this data?

- Whether or not users add Private Browsing Shortcut and/or use the Always Open in Private Browsing Feature
- Which system notification options users are interacting with the most
- Whether or not the garbage icon is discoverable and useful to users
- If users are tapping on the garbage icon accidentally with the use of the "undo" option on the snack bar

#### Why does Mozilla need to answer these questions? Are there benefits for users? Do we need this information to address product or business requirements?

Since Focus will be sunset, the initial data retrieved from Fenix users will help us understand if the private mode features are discoverable/useful. Going forward, if we detect discoverability issues, changes can be made for the onboarding on Focus users.

The benefits mostly revolve around our product being fast/private by design. Will promote safety when browsing the web and opening 3rd party links.

#### What probes (suggested, if applicable)

- Under Settings-> Privacy -> Private Browsing:
    1. Tap on the Add Private Browsing Shortcut -> Touch and Hold/Cancel/Add Automatically
    2. Toggle the "Always Open in Private Browsing" setting 
- Interact with the System Notification which includes:
   1. Tap on notification to delete private browsing history
   2. Tap Open button on notification
   3. Tap Delete and Open button
- Tap on the garbage can icon on the Private Browsing home page
- Tap on "undo" on the snackbar (after garbage icon is tapped)
- User added Firefox Preview (Private) as default browser (if feasible)

### Dependencies (Added by PM and Eng)

- Glean SDK (Event ping)

### Acceptance Criteria (Added by PM)
- Event pings can be queried via Amplitude
- We are sending telemetry events for the actions listed in the requirements
- We have documented the telemetry
- We have asked a data steward to [review](https://github.com/mozilla/data-review/blob/master/request.md) the telemetry

**Comment by sblatz** [comment]
QA can you please verify just the events added in https://github.com/mozilla-mobile/fenix/pull/4968

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **Nightly Build #12420612** using a Google Pixel 3a (Android 9)

Ping 8881a756-93eb-4a03-bbbd-d6660a48c1df
A user pressed the garbage can icon on the private browsing home page
A user pressed the "undo" button in the snackbar that is shown when the garbage icon is tapped

Ping 5de81e59-ffe9-4575-847f-a1fe024d5bde
A user pressed the private browsing mode notification itself

Ping e24f555b-6fcd-480d-8357-a70fc41b8f51
A user pressed the private browsing mode notification's "Open" button

Ping 53605e04-bf17-4dec-8f11-002c526efbb0
A user pressed the private browsing mode notification's "Delete and Open" button

### Notes
[PB.txt](https://github.com/mozilla-mobile/fenix/files/3559690/PB.txt)
[Glean Dashboard](https://debug-ping-preview.firebaseapp.com/pings/aj-300801)

@sblatz Please review and if I missed something reopen the issue. :)

**Comment by jyeontaek** [comment]
Reopened because #419 still needs to be completed.

**Comment by jyeontaek** [comment]
For QA: We just have #419 left to test.

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on Fenix 2.0.0-rc.2 using a Samsung Galaxy Tab A (Android 9).

**Ping - f37ef01e-49b4-4492-93bb-23c4a785a017**
✅ Tap on "Add private browsing shortcut" from settings
  
**Ping  - 02e2b339-10b6-4cbe-b78e-aa1f09226bc2**
✅ Tap on the previously created shortcut 

**Ping - 077314b2-0fc8-42e3-b694-06a3cedbf4c3**
✅ A user pressed the garbage can icon on the private browsing home page 
✅ A user pressed the "undo" button in the snackbar that is shown when the garbage icon is tapped


**Ping - 719eba10-3a3a-41dd-b6e1-ad2c1c8188a5**
✅ A user pressed the private browsing mode notification itself

**Ping  - b0a9911e-fc96-4a7f-87d7-dd7a2cdbcaea**
✅ A user pressed the private browsing mode notification's "Open" button 

**Ping - 52b34b8d-bbdc-4eda-bc0a-c0b8f84c5118**
✅A user pressed the private browsing mode notification's "Delete and Open" button
