### ISSUE TITLE
Ability to set the position of the search bar

### ISSUE THREAD

**Issue by Cheap-Skate** [mozilla-mobile/fenix#466]
As a user I would like to have the ability to set the position of the search bar.

### User problem:
URL bar is at bottom of screen
Tap URL bar to edit URL
URL bar moves to very very top of screen
Trying to move insertion cursor requires long reach upwards, can't do it one handed
Kind of defeats the idea of having URL bar at bottom of screen :) :)

Reference-browser does it correctly, during URL editing, URL bar stays at the bottom of the page content just above the keyboard

Please try to put as much of the user interaction as possible near the bottom of the screen

Galaxy S7
Android 8.0.0

**Comment by Cheap-Skate** [comment]
An example:
Google navigates me to https://mobile.reuters.com
I want to look at https://uk.mobile.reuters.com
I tap on the URL https://mobile.reuters.com with the intention of editing it
the URL moves to the very top of the screen
I want to move the insertion cursor to insert the uk. 

***Can't do it one handed, it's too far to reach*** . Which is a PITA.

reference-browser is better, I can do it one handed :)

Keep up the good work

**Comment by boek** [comment]
Hey @Cheap-Skate, thank you for the report!

This conversation has come up a couple of time and [we've added the code](https://github.com/mozilla-mobile/fenix/blob/master/app/src/main/java/org/mozilla/fenix/search/SearchLayouts.kt) to change the position of the search bar that is currently guarded by an A/B experiment.

I'm not sure what will end up being the default, but we should at least put a preference in to let a user customize the position :+1:

**Comment by Cheap-Skate** [comment]
Now that's service ;) Thanks. More search UI moans incoming, take cover!

**Comment by Lululalu** [comment]
As an user I like the way Fenix works, better than RB IMO. The toolbar on the bottom while typing makes me fell dizzy. Maybe it has something to do with the fact that I am affected by motion sickness.

**Comment by mheubusch** [comment]
@vesta0 Can we move this to post-MVP for now?

**Comment by vesta0** [comment]
Moved to post-mvp.

**Comment by lime124** [comment]
@apbitner for consideration while doing explorations of top nav/bottom nav stuff in #3651

**Comment by vesta0** [comment]
This will be addressed by #5694
