### ISSUE TITLE
ActivationPingTest fails unrelated tests

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/fenix#4662]
See here for the full issue details: https://github.com/mozilla-mobile/fenix/pull/4660#pullrequestreview-273319542

~~cc: @Dexterp37 @travis79~~ Not a Glean bug.

**Comment by Dexterp37** [comment]
@jonalmeida hey!

Please note that the `activation` ping is not owned by the Glean team: we supported the initial implementation work for helping the Fenix team on this. I think this is now owned and maintained [by the Fenix team](https://github.com/mozilla-mobile/fenix/blob/634ee184a6637dd0e2444a102231f4b396b08af3/app/pings.yaml#L20).
