### ISSUE TITLE
Add ability to opt out of sending data specifically to third parties data collection

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#4663]
### Why/User Benefit/User Problem
As a user, I may not want to get marketing notifications or communications nor have data sent to services like Leanplum and Adjust. 

### What/Requirements
I have a toggle to disable these marketing notifications in settings (likely under "data choices"?)

See https://github.com/mozilla-mobile/fenix/issues/4421#issuecomment-520047239 for suggestion.

**Comment by sblatz** [comment]
I think we'll want to fast follow this behind #4421 so users have a choice in the matter :)

**Comment by lnicola** [comment]
Please don't make this available only for marketing notifications. In Fennec I can prevent the browser from contacting third parties like Leanplum and Adjust. Leanplum does more than push notifications.

**Comment by sblatz** [comment]
From @lime124 on #373: 
> jennifer davidson did some awesome research on firefox desktop interruptions. i highly encourage people to watch the product club video and take this into consideration for this user story/feature.

https://vreplay.mozilla.com/replay/showRecordingExternal.html?key=HJI4gtp2yXDG8B3

**Comment by lime124** [comment]
perfect! /cc @mheubusch - she's been looking into this for all our products.

**Comment by mheubusch** [comment]
@sblatz @lime124 This issue conflates two separate issues - 1. notifications and 2. data collection For 1, I will create a new issue with a specific user story for notifications. For 2, currently a user can disable telemetry, and we no longer send data to anyone - mozilla or partners.  If  you think we need to create finer controls for who gets or doesn't get data, let's discuss and if needed open a new issue.  I will close this issue.

**Comment by sblatz** [comment]
@lnicola has filed https://github.com/mozilla-mobile/fenix/issues/4674 to cover that second point in @mheubusch's comment.
