### ISSUE TITLE
More descriptive instructions for search shortcuts

### ISSUE THREAD

**Issue by Verdi** [mozilla-mobile/fenix#4664]
## Steps to reproduce
1. Click into search field
2. Search shortcuts are displayed and preceded by the words, "Search with."

Let's try to make this feature more understandable and use the words that we're using in the new desktop design - "This time, search with:"

### New Expected behavior
1. Click into search field
2. Search shortcuts are displayed and preceded by the words, "This time, search with:"

**Comment by sblatz** [comment]
Adding "feature request" label so Vesta sees this in her triage!

**Comment by neekless** [comment]
I would rather have the option to turn this off completely. I set my search engine to a specific one for a reason and I don't need all these other search engines I'm never gonna use to show by default. If I want to use other search engines I'll tap the Shortcuts button myself.

**Comment by Baron-Severin** [comment]
> I would rather have the option to turn this off completely. I set my search engine to a specific one for a reason and I don't need all these other search engines I'm never gonna use to show by default. If I want to use other search engines I'll tap the Shortcuts button myself.

Hi @neekless, that option is available at `Settings -> Search -> uncheck "Show search shortcuts"`

**Comment by neekless** [comment]
@Baron-Severin yes I have noticed this and unchecked it since some versions ago, but thanks for letting me know!

**Comment by mcarare** [comment]
This seems a little verbose to me. Can we try another string? Maybe shorter but still sufficiently descriptive?

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **Nightly Build #13500610 from 12/16** using the following devices:
• Google Pixel 3a (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• OnePlus (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

► Screenshot
![rsz_screenshot_20191216-120729](https://user-images.githubusercontent.com/51314259/70898422-5024d700-1ffd-11ea-8e71-7a9a66ff8698.png)
