### ISSUE TITLE
File low-hanging fruit in Home Fragment creation

### ISSUE THREAD

**Issue by hawkinsw** [mozilla-mobile/fenix#4665]
Let's file actionable bugs to address the low-hanging fruit of so we can 1) prioritize them & ensure we're working on the most important things and 2) ensure our backlog has actionable works for devs.

### Acceptance criteria
- File bugs to address the low-hanging fruit (and some larger diminishing returns) in `HomeFragment` creation
- Notify Slack channel when issues are filed

---

Overall time to start (at this time) is around 900ms. It takes 250ms to create the Home Fragment (combination of `performCreate` and `performCreateView`). Inflation of the view itself takes more than 100ms. 

1. #7423
Inflation accounts fof 65% of `performCreateView`. 

@colintheshots @csadilek Would you mind tagging this appropriately? As a reporter I do not have that ability.

**Comment by hawkinsw** [comment]
[cpu-art-20190809T163149.zip](https://github.com/mozilla-mobile/fenix/files/3487963/cpu-art-20190809T163149.zip)

**Comment by hawkinsw** [comment]
Interesting: On an absolute basis, it takes the Nexus device hosted at ND about 1/2 the time to load the Home Fragment as it does the Pixel 2.

**Comment by emalysz** [comment]
The creation of the HomeFragment in `FragmentManager.moveToState` takes 13.66% of cold startup. 

Here's a breakdown of what percentage of `FragmentManager.moveToState` each method takes up. Each indent indicates a method that was called by the unindented method; the percentages of these methods is the percentage of `FragmentManager.moveToState` each method takes up. Some methods may be accidentally omitted: this was created by hand.

```
88.92% - FragmentStateManager.createView
  04.72% - HomeFragment.onViewCreated 
  84.20% - app.Fragment.performCreateView
    84.20% - HomeFragment.onCreateView
      47.48% - inflate
      14.40% - SessionControlView.init
      04.34% - components.StoreProvider$Companion.get
11.08% - FragmentStateManager.create
  11.08% - app.Fragment
    07.21% - HomeFragment.onCreate
      07.21% - TransitionInflater.inflateTransition
    03.86% - LifecycleRegistry.handleLifecycleEvent
```

**Comment by emalysz** [comment]
File all tractable issues >= 5% (and some smaller). These are ordered by priority recommendation:

- 47.48%: #7423 LayoutInflater.inflate
- 14.40%: #7465 SessionControlView.init
- 7.21%: #7466 TransitionInflater.inflateTransition
- 4.72%: #7467 ViewTreeObserver.init
