### ISSUE TITLE
File low-hanging fruit of HomeActivity creation

### ISSUE THREAD

**Issue by hawkinsw** [mozilla-mobile/fenix#4666]
Let's file actionable bugs to address the low-hanging fruit of so we can 1) prioritize them & ensure we're working on the most important things and 2) ensure our backlog has actionable works for devs.

### Acceptance criteria
- File bugs to address the low-hanging fruit (and some larger diminishing returns) in `HomeActivity` creation
- Notify Slack channel when issues are filed

---

Overall startup time is around 300ms (at this point and on a specific device). `HomeActivity.onCreate` takes 307ms. Layout inflation alone takes 126ms. `setupToolbarAndNavigation` takes 70ms.  

@colintheshots @csadilek can you tag appropriately? Thanks!

**Comment by hawkinsw** [comment]
[cpu-art-20190809T163149.zip](https://github.com/mozilla-mobile/fenix/files/3487961/cpu-art-20190809T163149.zip)

**Comment by hawkinsw** [comment]
Interesting: On an absolute basis, it takes the Nexus device hosted at ND about 1/2 the time to load the Home Activity as it does the Pixel 2.

**Comment by emalysz** [comment]
Profile taken with a Pixel 2.

The creation of the HomeActivity takes 11.13% of cold startup. 

Here's a breakdown of what percentage of `HomeActivity.onCreate` each method takes up. Each indent indicates a method that was called by the unindented method; the percentages of these methods is the percentage of `HomeActivity.onCreate` each method takes up. Some methods may be accidentally omitted: this was created by hand.

```
55.78% - AppCompatActivity.setContentView
  55.78% - AppCompatActivityDelegateImpl.setContentView
    46.39% - LayoutInflater.inflate
    9.39% - AppCompatDelegateImpl.ensureSubDecore 
      4.82% - ViewCompat.setOnApplyWindowInsertsListener
      4.57% - ViewUtils.makeOptionalFitsSystemWindows
26.21% - HomeActivity.setupToolbarAndNavigation
  26.21% - ToolbarActionBar.init
    26.21% - Toolbar.setTitle()
18.09% - FragmentActivity.onCreate
  18.09% - ComponentActivity.onCreate
    18.09% - FragmentManagerImpl.moveToState
```

**Comment by emalysz** [comment]
File all tractable issues >= 5%. These are ordered by priority recommendation:

- 46.39%: #7472 LayoutInflater.inflate
- 26.21%: #7473 HomeActivity.setupToolbarAndNavigation

**Comment by hawkinsw** [comment]
I have looked before at `Toolbar.setTitle()` and it just boggles my mind that it takes so long to execute :-)
