### ISSUE TITLE
Give users controls to opt out of product messages

### ISSUE THREAD

**Issue by mheubusch** [mozilla-mobile/fenix#4667]
## User Story
- As a Firefox Preview user, I want the ability to turn off product messages so that I can use my phone and Firefox without interruptions from messages I did not initiate.
- for example, I'd like to turn off Leanplum Product Messaging so I don't get Product messages.

### Dependencies
- [ ] Need UX specs (where to put in settings, string, icon)

### Acceptance Criteria
- I can access a setting to disable product messages
- If I disable messages, I will no longer have messages I do not initiate from Firefox appear in-app or via Push
- If I disable messages, I will still have messages I do initiate appear in-app and via Push (for example, Send Tabs)
- If I re-enable messages, I will be able to receive Push and in-app messages I do not initiate

**Comment by mheubusch** [comment]
Preferred label for the Android channel is "Firefox news" and if we do add this feature to our own settings should also use Firefox news for consistency.

**Comment by vesta0** [comment]
@mheubusch I believe this was already implemented as "Marketing data" about a month ago. Is this different or are you asking to change the label?

**Comment by mu22le** [comment]
I think users should be asked explicitly the first time thy run the browser if they want leanplum enabled. You cannot campaign on the slogan "we protect your privacy" and then enable marketing telemetry by default.
