### ISSUE TITLE
URL bar: make colors match when editing URL and not editig URL

### ISSUE THREAD

**Issue by Cheap-Skate** [mozilla-mobile/fenix#467]
When the URL bar is at the bottom of the screen it has a gray background
When it is being edited it moves to the top of the screen (issue  #466)
AND it gets a white background
For consistency I think URL bar should have the same colors whether I am editing URL or not
i.e. also have gray background when URL is being edited to match non-edit case.

Galaxy S7
Android 8.0.0

**Comment by lime124** [comment]
As per shorlander - It should be grey in both locations. The only time it is white is on the home screen before it scrolls.
