### ISSUE TITLE
Ability to disable third-party data collection

### ISSUE THREAD

**Issue by lnicola** [mozilla-mobile/fenix#4674]
### Why/User Benefit/User Problem

I trust Mozilla with my Telemetry data and want to help improving the browser, but I don't want any information to get to third parties (e.g. Leanplum, Adjust, Google Analytics).

This is a Fenix parity issue.

### What/Requirements

- I want a clear Privacy Policy stating which third parties Fenix talks to, when, and what data it's sending
- I want a separate option to disable data submission to third parties
- it's fine if this disables the marketing notifications; if I took the time to read the privacy policy, I can probably read the release notes to find out about new browser features
- Safe Browsing and other features can be configured separately

cc @sblatz @mheubusch @lime124

**Comment by mheubusch** [comment]
Thank you for creating this separate issue, @lnicola!

**Comment by liuche** [comment]
This will add complexity on the data handling side, however, this is something that Fennec provides, and it's good to provide more user choice.

**Comment by mheubusch** [comment]
Here is my proposed copy:
**Marketing data**
Shares data about what features you use in Firefox with Leanplum, our mobile marketing vendor.

(IIUC Adjust collects data upon install, so think that by the time you start your first browsing session and access the settings, all of the data that is sent to Adjust has already been sent. This is why I only mention Leanplum - @vesta0 and @boek can you confirm?)

**Comment by vesta0** [comment]
Thank you for the copy @mheubusch 

I will wait for @boek to respond re the data collection question.

**Comment by yoasif** [comment]
> IIUC Adjust collects data upon install, so think that by the time you start your first browsing session and access the settings, all of the data that is sent to Adjust has already been sent.

Will disabling telemetry also remove it from third party vendors? This is something that was announced on Desktop here: https://blog.mozilla.org/netpolicy/2019/12/31/bringing-californias-privacy-law-to-all-firefox-users-in-2020/

Actually, will disabling telemetry disable it on mobile (might need to be a new issue) for non third party telemetry? 

FWIW, I don't think Adjust data should be shared until the second start of Fenix so that users can actually opt out. Right now, the only way to prevent this is to install a firewall on your device.

**Comment by abodea** [comment]
Note that the `Usage and technical data, Marketing data and Experiments` are now displayed on the `Data collection` section in settings.
The toggles are working correctly, @boek should be verified the functionalities too for this bug?
I can toggle ON and OFF but how I will know for sure that the information is sent or not correct?
If only the verification that the options are added and can be turned on and off is enough I will close this bug.
I will remove the `eng:qa:needed` until further notice.

**Comment by betsymi** [comment]
Am removing `needs:strings` because it appears strings have already been provided.

**Comment by vesta0** [comment]
@boek can we close this issue?

**Comment by vesta0** [comment]
@boek please close this issue if this work has been verified (see @abodea 's note)

**Comment by liuche** [comment]
When we toggle data collection off for a metric Glean receives that and deletes the data, so I'll close this issue.
