### ISSUE TITLE
[Bug] The "Disconnect" button's UI is broken

### ISSUE THREAD

**Issue by softvision-miralobontiu** [mozilla-mobile/fenix#4679]
## Steps to reproduce
1. Sign in to your account.
2. Sign out from your account and observe the "Disconnect" button.

### Expected behavior
The "Disconnect" button has no UI issues.

### Actual behavior
The "Disconnect" button's UI is broken.

### Device information
* Android device: all
* Fenix version: 20190812 (#12240720)

![20190812_Trim](https://user-images.githubusercontent.com/40694158/62856576-f71afe80-bcfd-11e9-9479-7830a8ec8dea.gif)

**Comment by ekager** [comment]
Dupe of #4179
