### ISSUE TITLE
Library menu: can't exit using one hand

### ISSUE THREAD

**Issue by Cheap-Skate** [mozilla-mobile/fenix#468]
IIUC Fenix is targeting one-hand use with the toolbar at the bottom
I can get **into** the Library menu one-handed (3 dot menu > Your Library)
BUT 
I can't get **out of** the Library menu (or its sub menus) one handed. The X ("close") button is too high up to reach one handed

Please think about making as much of the UI as possible "one handed" i.e. interaction touch points near bottom of the screen not the top.

Galaxy S7
Android 8.0.0

**Comment by ekager** [comment]
Hi @Cheap-Skate thanks for your feedback! The system back button doesn't work for you in this scenario?

**Comment by Cheap-Skate** [comment]
Yes it works fine. I am an idiot.    Please ignore this issue [I have filed plenty more, perhaps not all so idiotic ;) ]

**Comment by boek** [comment]
:raised_hands:
