### ISSUE TITLE
[Bug] Long-tapping on a photo doesn't display the photo's source

### ISSUE THREAD

**Issue by softvision-miralobontiu** [mozilla-mobile/fenix#4684]
## Steps to reproduce
1. Open a page with at least a photo (like an article from wikipedia.org, or from cnn.com)
2. Long-tap on a non-linked photo.

### Expected behavior
The source link of the photo is displayed in the menu, then the options.

### Actual behavior
"about:blank" is displayed, then the options.

### Device information
* Android device: all
* Fenix version: 190812 (#12240720)

![Screenshot_20190812-164946_Firefox Nightly](https://user-images.githubusercontent.com/40694158/62870408-43783580-bd22-11e9-81e3-a7b7c32ab020.jpg)

**Comment by mkaply** [comment]
I was just about to report this. Note that Fennec does even better than the source - it shows the alt text. This can be seen on xkcd.com comics.

**Comment by kbrosnan** [comment]
Alt text should only be displayed when the image fails to load. Displaying title text is #580.

**Comment by softvision-miralobontiu** [comment]
It is no longer reproducible on RC 2.0.0-rc.2. Tested with Samsung Galaxy Tab S3 (Android 8), and OnePlus 5T (Android 9).
