### ISSUE TITLE
[Bug] Crash when editing a datetime-local widget

### ISSUE THREAD

**Issue by callahad** [mozilla-mobile/fenix#4685]
## Steps to reproduce

1. Visit https://www.translink.co.uk/
2. Tap on the datetime-local input:

![Screenshot](https://user-images.githubusercontent.com/24193/62876084-158ff280-bd1c-11e9-9d64-19a74f4fe877.png)

### Expected behavior

* A native datetime-local input widget appears

### Actual behavior

* Fenix crashes

### Device information

* Android device: Pixel 3a, running Android Q Beta 6
* Fenix version: Nightly 190811 06:05 (Build #12230729), :package: 8.0.0 8f87df870, :lizard:  69.0-20190808090046

**Comment by kbrosnan** [comment]
Sentry issue: [FENIX-NIGHTLY-13](https://sentry.prod.mozaws.net/operations/fenix-nightly/issues/5921693/)

**Comment by kbrosnan** [comment]
I can reproduce this on Reference Browser as well. [REFERENCE-BROWSER-62](https://sentry.prod.mozaws.net/share/issue/d1625298d387422591939f02599dddb9/)

**Comment by sblatz** [comment]
@cpeterso is this a known GV issue? Seems like GV given that it's happening in reference browser and Fenix, but unsure.

**Comment by cpeterso** [comment]
> is this a known GV issue? Seems like GV given that it's happening in reference browser and Fenix, but unsure.

I think this is an A-C bug, not a GV bug. The crash reports kbrosnan shared above point to a date parsing exception when A-C's `notifyDatePromptRequest` calls `toDate` here:

https://github.com/mozilla-mobile/android-components/blob/9d398129dc390d65f71d53cc8bcdb3e567f938d6/components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/prompt/GeckoPromptDelegate.kt#L363-L374

```
ParseException

Unparseable date: "2019-08-13"

    java.text.DateFormat in parse at line 362
    mozilla.components.support.ktx.kotlin.StringKt in toDate at line 47
    mozilla.components.support.ktx.kotlin.StringKt in toDate$default at line 44
    mozilla.components.browser.engine.gecko.prompt.GeckoPromptDelegate in notifyDatePromptRequest at line 392
    mozilla.components.browser.engine.gecko.prompt.GeckoPromptDelegate in onDateTimePrompt at line 192
    org.mozilla.geckoview.GeckoSession in handlePromptEvent at line 2751
    org.mozilla.geckoview.GeckoSession$Listener in handleMessage at line 1206
    org.mozilla.gecko.EventDispatcher$3 in run at line 368
    android.os.Handler in handleCallback at line 873
    android.os.Handler in dispatchMessage at line 99
    android.os.Looper in loop at line 193
    android.app.ActivityThread in main at line 6718
    java.lang.reflect.Method in invoke
    com.android.internal.os.RuntimeInit$MethodAndArgsCaller in run at line 493
    com.android.internal.os.ZygoteInit in main at line 858
```

**Comment by cpeterso** [comment]
@callahad - Is your phone in a non- en-US locale?

The exception indicates Kotlin's `toDate` doesn't like the ISO 8601 date string "2019-08-13". Perhaps Kotlin's `toDate` expects a localized data format by default or GV's `onDateTimePrompt ` delegate is supposed to pass a different date format.

**Comment by callahad** [comment]
I'm physically in the UK, but my phone was purchased in the States and is
set to `en-US` everywhere I'm aware of.

I do tell Android to display a 24-hour clock, but I can't imagine that
influences anything.

**Comment by callahad** [comment]
...and I can't repro this anymore.

Running "Nightly 190925 18:01" (Build #12681805)
📦: 14.0.1, 81385d712
🦎: 71.0a1-20190923094800

**Comment by cpeterso** [comment]
> ...and I can't repro this anymore.

It would still be helpful for an A-C engineer to review your exception stack trace and decide whether GV is buggy for sending an unexpected date format or A-C needs to be more forgiving in what it accepts for `toDate`.

**Comment by sv-ohorvath** [comment]
I am able to reproduce this on the 8/12 build when this was reported. Also, I can confirm it's not crashing anymore on the latest Nightly build (1/10), on Android Q. I'll leave this open if there's more investigation needed.
