### ISSUE TITLE
"Your Library" menu item:- move to bottom of list & change name to "My Library"

### ISSUE THREAD

**Issue by Cheap-Skate** [mozilla-mobile/fenix#469]
IIUC Fenix is targeting one-hand use with the toolbar at the bottom
The "Your Library" menu is likely to be used very often.
It could be near the bottom of the screen not the top to be easier to reach one handed
It's also kind of about navigation so it maybe makes sense for it to be near the navigation forward/back/reload buttons

Also, who is "You" in the menu title, should it be "**My** Library" not "**Your** Library"?   ;)

Galaxy S7
Android 8.0.0

**Comment by topotropic** [comment]
@Cheap-Skate makes sense, we'll explore thumb-friendlier options for the library – and good catch with the menu title. Thanks!

**Comment by topotropic** [comment]
sorry, closed it accidentely

**Comment by cadeyrn** [comment]
> Also, who is "You" in the menu title, should it be "My Library" not "Your Library"? ;)

Changing that would result in inconsistencies across the product.

In "About Fenix" you can read "Fenix puts _you_ in control", not "Fenix puts _me_ in control". In the home screen of a private session you can read "_You're_ in a private session" and "Fenix clears _your_ search and browsing history", not "_I'm_ in a private session" and "Fenix clears _my_ search and browsing history" and so on. It doesn't make sense to change the string "Your Library" to "My Library" and not changing all the other strings. To be honest if would be more confusing if we mix "I" and "You" across the product.

**Comment by topotropic** [comment]
Ah, sorry, I was more thinking of removing the pronoun altogether. So just going with "Library" – but don't have strong opinions on it. @mheubusch maybe you can chime in here. Thanks!

**Comment by Cheap-Skate** [comment]
Yes I see that there tends to be "you" not "me" in Fennec & Desktop. Fine. 

But I would suggest that **Your** Library is unnecessary, Fennec & Desktop just have History and Top Sites not **Your** History etc. And if Fenix is going down the Your route I would expect **Your** Favorites, **Your** Sessions **Your** Downloads etc which we don't have ?

So my suggestion would be get rid of **Your** as @topotropic suggested.

**Comment by cadeyrn** [comment]
Please note that there is a new mockup for Firefox for iOS with a "Your Library" label: https://mozilla.invisionapp.com/share/NVQNKFF2C7Z#/screens/348322247

Whatever you decide ("Your Library" or "Library"), maybe you could synchronisize the decision with the iOS team so that both products use the same wording. :)

**Comment by mheubusch** [comment]
@topotropic please remove Your from Your Library - any engineer can simply make this update to the menu and we don't need new designs

**Comment by ekager** [comment]
This string has been updated. Thanks @cadeyrn !

**Comment by shorlander** [comment]
> @topotropic please remove Your from Your Library - any engineer can simply make this update to the menu and we don't need new designs

Hi! Can we reopen this bug and change it back to "Your Library" please? One of the findings from our Photon research was that there was generally some confusion around what "Library" meant and where the content was coming from. The recommendation was to personalize so it was more clear that it is a collection of your things.

**Comment by ekager** [comment]
@shorlander do we want the menu text and the title when you're in the library to say "Your Library"? Or just the menu item?
