### ISSUE TITLE
[ux only] user flow for all search access points

### ISSUE THREAD

**Issue by lime124** [mozilla-mobile/fenix#4693]
this is a request from the Search telemetry group - Product Owner is mconnor.  _Due before October 1st._

The goal is to ensure we have hooks in all search access point so that we are collecting and attributing data properly. 

A Fenix designer needs to provide user flows and mockups for all the search access points in Fenix. This information should be passed to Emily Thompson who may have follow up questions.

UX - we need to be exhaustive and cover all possible points. This may include anything from the search widget, anything inside the app. Is voice a consideration here? Please timebox to no more than 1 day of work. We don't need any fancy deliverables just enough for Emily to understand the flows. Thanks!

**Comment by liuche** [comment]
@lime124 says this is done!
