### ISSUE TITLE
[Bug] Typing in the search box of f64.ro is hard

### ISSUE THREAD

**Issue by andreicristianpetcu** [mozilla-mobile/fenix#4696]
## Steps to reproduce
open f64.ro and type in the search field
https://vimeo.com/343310523
### Expected behavior
easy to type
### Actual behavior
had to type the same letter several times
### Device information

* Android device: ?
* Fenix version: latest nightly

**Comment by andreicristianpetcu** [comment]
@ekager was there anything wrong with my bug report? I see you closed it without any comment.

**Comment by cadeyrn** [comment]
You opened two identical reports and the other one is still open: #4697

**Comment by andreicristianpetcu** [comment]
sorry. I got 500 error from github
