### ISSUE TITLE
[Bug] The security level globe is broken on Android 5&6

### ISSUE THREAD

**Issue by softvision-miralobontiu** [mozilla-mobile/fenix#4702]
## Steps to reproduce
1. Go to an insecure page or turn off your internet connection and observe the security level icon - the globe.

### Expected behavior
The icon is displayed correctly.

### Actual behavior
The icon is broken.

### Device information
* Android device: Nexus 5 (Android 6.0.1), Huawei P9 Lite (Android 6), HTC Desire 820 (Android 6.0.1), Samsung Galaxy Tab A6 (Android 5.1.1)
* Fenix version: 190812 (#12241855)
* Reference Browser 1.0.1933 (#12241220)

![Screenshot_20190813-104539](https://user-images.githubusercontent.com/40694158/62924080-03fc2880-bdb8-11e9-9d78-c74101766e02.png)

**Comment by Amejia481** [comment]
@NotWoods is this related to https://github.com/mozilla-mobile/android-components/pull/4095?

**Comment by NotWoods** [comment]
Not sure what caused the issue, but tweaking the globe path fixes it. I guess 5/6 render vectors in a statelist drawable oddly.

**Comment by Amejia481** [comment]
Awesome thanks!

**Comment by sv-ohorvath** [comment]
@NotWoods Will this fix the TP icon as well? Hasn't landed in Fenix Nightly yet I guess. If not, then we can have a new issue opened:
![Screenshot_20190816-151544](https://user-images.githubusercontent.com/4037709/63167122-04572680-c039-11e9-958f-a22130a75dcf.png)

**Comment by NotWoods** [comment]
It's a new issue.

**Comment by sv-ohorvath** [comment]
> It's a new issue.

Thanks! Logged: https://github.com/mozilla-mobile/fenix/issues/4774
