### ISSUE TITLE
[Bug] [delete browsing data] disable checkboxes or hide items when there is no data to be cleared

### ISSUE THREAD

**Issue by Lululalu** [mozilla-mobile/fenix#4704]
#### Expected behavior
When I see several checkboxes I want to mark them all to delete everything, but if there is no content to be deleted, the checkbox remains the same. IMO these elements should have a more washes out color, indicating they are not available. 

### Actual behavior
![Screenshot_20190812-225414_Firefox Preview](https://user-images.githubusercontent.com/32398857/62953280-97872680-bdc3-11e9-83b1-4db26e17f913.jpg)

### Device information

* Android device: Galaxy A5 2017 8.0 
* Fenix version: 190813

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on The latest **Nightly Build #12380610 from 26/8** using the following devices:
• Google Pixel 3a (Android 9)
• Huawei Mate 20 lite (android 8.1.0)
• Samsung Glaxy S7 (Android 7)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (android 5.1.1)

<details>
    <summary>Washed out color examples from Google Pixel 3a </summary>

► **No browsing data**
![rsz_screenshot_20190826-142022](https://user-images.githubusercontent.com/51314259/63687987-c7e0b300-c80e-11e9-98ad-4c7df8990a86.png)


► **Open tabs**
![rsz_screenshot_20190826-141929](https://user-images.githubusercontent.com/51314259/63687834-50ab1f00-c80e-11e9-847c-ec9de5387532.png)

► **Browsing history and site data**
![rsz_screenshot_20190826-143407](https://user-images.githubusercontent.com/51314259/63688077-f2cb0700-c80e-11e9-8470-65545e22f8ae.png)

► **Collections**
![rsz_screenshot_20190826-141845](https://user-images.githubusercontent.com/51314259/63687958-b39cb600-c80e-11e9-8004-de88db71b267.png)


</details>
