### ISSUE TITLE
GeckoView engine flashes black when navigating away

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#4708]
This happens when navigating away from the GeckoSession. It occurs when we close a tab, open a settings fragment from BrowserFragment, etc. 

The GV team has said this is difficult for them to fix on their end and not a high priority. 

A workaround would be for us to screenshot the GV and animate that view (which is what we did in Focus) and seems like a reasonable solution for now. 

![sad 2019-08-09 13_20_19](https://user-images.githubusercontent.com/4400286/62806706-73b49f80-baa8-11e9-9692-07be8d7013a0.gif)

**Comment by KaenDagger** [comment]
I would like to work on this issue

**Comment by sblatz** [comment]
Closing in favor of #1901.
