### ISSUE TITLE
[Telemetry] Collect whether user has turned off notifications from Fenix

### ISSUE THREAD

**Issue by liuche** [mozilla-mobile/fenix#4712]
Owner: Product Manager

#### Description & Product Manager / Data Scientist User Story
- As a product owner, I want to know if people are annoyed by notifications, and use the Android settings to turn them off.

#### Hypothesis
- We believe that users may turn off notifications when presented with irrelevant notifications. We'll use the notifications state to measure whether our notifications are useful/not.

#### What questions will you answer with this data?
Whether users are turning off Fenix notifications.

#### Why does Mozilla need to answer these questions? Are there benefits for users? Do we need this information to address product or business requirements?
Android allows users to turn off notifications for apps, so we should keep track of whether our notifications are annoying to users, and whether they're turning them off.

#### What probes (suggested, if applicable)
- [NotificationManagerCompat.areNotificationsEnabled](https://developer.android.com/reference/android/support/v4/app/NotificationManagerCompat.html#areNotificationsEnabled()) API 19+

### Dependencies (Added by PM and Eng)
None

### Acceptance Criteria (Added by PM)
- Event pings can be queried via re:dash
- We are sending telemetry events for the actions listed in the requirements
- We have documented the telemetry
- We have asked a data steward to [review](https://github.com/mozilla/data-review/blob/master/request.md) the telemetry
- NOT an AC: Data science to create dashboard or further graphs (this will be a separate issue, this issue is only about hooking up the events described and that they can be queried in re-dash)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-13031)

**Comment by csadilek** [comment]
This landed for https://github.com/mozilla-mobile/fenix/issues/27795.
