### ISSUE TITLE
[Bug]Update SUMO content for how to disable data collection

### ISSUE THREAD

**Issue by mheubusch** [mozilla-mobile/fenix#4716]
Update existing SUMO copy linked from [Privacy Notice](https://support.mozilla.org/en-US/kb/share-data-mozilla-help-improve-firefox?redirectlocale=en-US&redirectslug=send-performance-data-improve-firefox) to include advice on how to disable data collection from Firefox Preview (should also include iOS). 

Current content:
How do I opt-in or opt-out of sending performance data?

You can turn this on and off at any time with these steps:

    Click the menu button Fx57Menu and choose Preferences.
    Select the Privacy & Security panel.
    Scroll down to the Firefox Data Collection and Use section.
    Check or uncheck the box next to Allow Firefox to send technical and interaction data to Mozilla. 

Proposed content: 
Firefox collects technical and usage data by default, but you can turn this off at any time.  

On Firefox for desktop:

    Click the menu button Fx57Menu and choose Preferences.
    Select the Privacy & Security panel.
    Scroll down to the Firefox Data Collection and Use section.
    Check or uncheck the box next to Allow Firefox to send technical and interaction data to Mozilla. 

On Firefox Preview:
Open the main menu and select Settings.
Open the Data collection section.
Turn off Usage and technical data by sliding the toggle to the left (it will change from purple to white when it is disabled). 

On Firefox for iOS:
Open the main menu and select Settings.
Turn off Send Usage Data by sliding the toggle to the left (it will change from blue to white when it is disabled). 

Then, also update this page https://support.mozilla.org/en-US/kb/firefox-preview-your-rights
So that the section on disabling cloud services reads:
To disable Firefox Cloud Service:

    Tap the menu button

    preview menu

    Tap Settings.
    Tap Data collection.
    Toggle the switch next to Usage and technical data to turn it on or off. 

Then create a new page at the same level in the IA as Your rights: 
 How to turn off data collection 
At Mozilla, we believe that privacy is fundamental to a healthy internet.

That’s why we build [shortname parameter], and all our products, to give you greater control over the information you share online and the information you share with us. Firefox Preview collects technical and usage data by default, but you can turn this off at any time.  
 Tap Settings.
    Tap Data collection.
    Toggle the switch next to Usage and technical data to turn it off. 

Also, a bit OT, but I think the Add search widget article should appear under Browsing, not Privacy and Security. Also, Send tab should move from Settings to Sync.

**Comment by jonichan** [comment]
We have a SUMO article specifically for telemetry on mobile. I wonder if it's more appropriate for this: https://support.mozilla.org/en-US/kb/send-usage-data-firefox-mobile-devices

**Comment by jonichan** [comment]
> Proposed content:
> Firefox collects technical and usage data by default, but you can turn this off at any time.
> 
> On Firefox for desktop:
> 
> ```
> Click the menu button Fx57Menu and choose Preferences.
> Select the Privacy & Security panel.
> Scroll down to the Firefox Data Collection and Use section.
> Check or uncheck the box next to Allow Firefox to send technical and interaction data to Mozilla. 
> ```
I've updated this on https://support.mozilla.org/en-US/kb/share-data-mozilla-help-improve-firefox


> On Firefox Preview:
> Open the main menu and select Settings.
> Open the Data collection section.
> Turn off Usage and technical data by sliding the toggle to the left (it will change from purple to white when it is disabled).
> 
> On Firefox for iOS:
> Open the main menu and select Settings.
> Turn off Send Usage Data by sliding the toggle to the left (it will change from blue to white when it is disabled).

Updated Firefox Preview and FIrefox for iOS instructions here: https://support.mozilla.org/en-US/kb/send-usage-data-firefox-mobile-devices


> Then, also update this page https://support.mozilla.org/en-US/kb/firefox-preview-your-rights
> So that the section on disabling cloud services reads:
> To disable Firefox Cloud Service:
> 
> ```
> Tap the menu button
> 
> preview menu
> 
> Tap Settings.
> Tap Data collection.
> Toggle the switch next to Usage and technical data to turn it on or off. 
> ```

I've updated this on https://support.mozilla.org/en-US/kb/firefox-preview-your-rights

> Then create a new page at the same level in the IA as Your rights:
> How to turn off data collection
> At Mozilla, we believe that privacy is fundamental to a healthy internet.
> 
> That’s why we build [shortname parameter], and all our products, to give you greater control over the information you share online and the information you share with us. Firefox Preview collects technical and usage data by default, but you can turn this off at any time.
> Tap Settings.
> Tap Data collection.
> Toggle the switch next to Usage and technical data to turn it off.

New page created (https://support.mozilla.org/en-US/kb/how-turn-data-collection-firefox-preview) in the same level as the "Your Rights" page.


> Also, a bit OT, but I think the Add search widget article should appear under Browsing, not Privacy and Security. Also, Send tab should move from Settings to Sync.

Woops, yes, those two articles were in the wrong categories. I've moved them.

**Comment by vesta0** [comment]
Thanks @jonichan :) @mheubusch is this request completed?

**Comment by liuche** [comment]
If we need to add this new "How to turn off data collection" item to settings at the same level as "Your Rights" in settings, we'll need:
* new string
* icon (potentially)

 @jpfaller can you take a look here, and let us know if we need an icon? or make a suggestion for what this would look like.

The updated pages will not need any new eng work.

**Comment by sblatz** [comment]
<img width="267" alt="image" src="https://user-images.githubusercontent.com/4400286/64882549-3648b200-d612-11e9-831c-0af35ee2a4ec.png">

We may just want to add it here right under "privacy notice"

**Comment by mheubusch** [comment]
This issue is not about in-product labeling, it is about SUMO only.  I've verified that a link to the requested article appears in the SUMO-hosted Fenix help section so we are good.
