### ISSUE TITLE
[Bug] touching back while the address bar is enabled navigates to the previous page, instead of just leaving the address bar to the current page.

### ISSUE THREAD

**Issue by Lululalu** [mozilla-mobile/fenix#4717]
## Steps to reproduce
Browse some pages
Touch the address bar
Touch the device's back button

### Expected behavior
Fenix leaves the address bar and goes back to the current page.

### Actual behavior
Fenix leaves the address bar and goes back to the previous page.

### Device information

* Android device: Galaxy A5 2017
* Fenix version: 190813

**Comment by ekager** [comment]
Could you clarify this a bit with maybe a video/gif? And is this always reproducible? I'm not quite sure what you mean

**Comment by Lululalu** [comment]
@ekager I recorded a video: https://streamable.com/hk13c

When I touch the back button on my device I shouldn't be sent back to the serp.

**Comment by topotropic** [comment]
@Lululalu could you briefly verify if this is still an issue? Unfortunately the recorded video isn't available anymore. Thanks!

**Comment by ekager** [comment]
@Lululalu please close this if you aren't seeing it anymore

**Comment by softvision-miralobontiu** [comment]
I was not able to reproduce the issue on the latest Nightly from 3/11 with Xiaomi Redmi Note 8T (Android 9), and HTC Desire 820 (Android 6.0.1).
Removing the needs:STR label.
