### ISSUE TITLE
[Bug]Improper position of the "Select Tabs", "Select collection" strings  

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#4720]
## Prerequisites
Have a couple of open tabs

## Steps to reproduce
1.  Tap "Save to collection"
2. Check the position of the upper left "Select Tabs" string 

### Expected behavior
The string should be properly displayed next to the **←**  sign 

### Actual behavior
Seems to be positioned higher

### Device information

* Android device: Huawei Media Pad M3 Lite 10 (Android 7)
* Fenix version: Debug version from Master 14/08

### Notes

 ►Improper display
![rsz_selecttabs](https://user-images.githubusercontent.com/51314259/63020094-d1c8f480-bea5-11e9-9e12-7b0bb1e3767e.png)
![rsz_selectcoll](https://user-images.githubusercontent.com/51314259/63020098-d4c3e500-bea5-11e9-8096-3c7e036c0359.png)

►Proper display
![rsz_seltabs](https://user-images.githubusercontent.com/51314259/63020234-37b57c00-bea6-11e9-9145-4ec3fa6f49c6.jpg)
![rsz_selcol](https://user-images.githubusercontent.com/51314259/63020195-1b194400-bea6-11e9-97d2-bee7dcd53136.jpg)

**Comment by cadeyrn** [comment]
Duplicate of #4680.

**Comment by AndiAJ** [comment]
Will close base on the above [comm](https://github.com/mozilla-mobile/fenix/issues/4720#issuecomment-521269230)
