### ISSUE TITLE
[Bug]Flicker when deleting tabs by swipe from a collection

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#4721]
###
Have a collection with a couple of tabs created

## Steps to reproduce
1. Delete the tabs from the collection by swiping

### Expected behavior
No animation issues

### Actual behavior
Flicker when deleting the tabs by swiping

### Device information

* Android device: Huawei Media Pad M3 Lite 10 (Android 7)
* Fenix version: Debug version from Master 14/08

► Video
![20190814_144915](https://user-images.githubusercontent.com/51314259/63020571-26b93a80-bea7-11e9-9936-472df39d1ade.gif)

**Comment by softvision-miralobontiu** [comment]
I was able to reproduce the flickers on HTC Desire 820 (Android 6.0.1), on the 10/21 Nightly build.

![20191021_Trim](https://user-images.githubusercontent.com/40694158/67191352-246ce280-f3fa-11e9-9ccf-cf8e1c17c709.gif)

**Comment by sflorean** [comment]
Reproducible also when the tabs are closed by tapping on "x". - Nightly 200331.

**Comment by Diana-Rus** [comment]
Reproducible with Google Pixel 3XL (Android 9) on Beta 5.0.0-beta.1 - 4/29
