### ISSUE TITLE
[Bug]URL bar animation lag

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#4724]
## Steps to reproduce
1. Navigate from the URL bar to a website
2. Check the animation of the URL bar

### Expected behavior
No UX issues

### Actual behavior
Animation lag 

### Device information

* Android device: Huawei Media Pad M3 Lite 10 (Android 7)
* Fenix version: Debug version from Master 14/08

►Video
![20190814_160836](https://user-images.githubusercontent.com/51314259/63023602-1eb0c900-beae-11e9-9775-51627ad56c55.gif)

**Comment by liuche** [comment]
Duping this to #6274
