### ISSUE TITLE
[Bug]Flicker when navigating to a website from the open tabs

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#4726]
## Prerequisites
Have a couple of open tabs 

## Steps to reproduce
1. Navigate to any website from the open tabs section

### Expected behavior
No UX issues

### Actual behavior
The selected tab flickers

### Device information

* Android device: Huawei Media Pad M3 Lite 10 (Android 7)
* Fenix version: Debug version from Master 14/08

► Video
![20190814_162210](https://user-images.githubusercontent.com/51314259/63024718-74867080-beb0-11e9-9f76-17d7b79376f6.gif)

**Comment by ekager** [comment]
@AndiAJ are you still seeing a flicker here?

**Comment by AndiAJ** [comment]
Yes, actually on most of the devices this occurs check on the latest **Nightly build #12870607 from 14/10**.
Not sure if this is the desired animation for this action or if it's a bug to be fixed ?

@ekager Please share your thoughts on this. :)

► Video Huawei Media Pad M3 Lite 10 (Android 7)

![20191014_101359](https://user-images.githubusercontent.com/51314259/66734829-51a31900-ee6d-11e9-8609-da66c82e2f3f.gif)

**Comment by boek** [comment]
Let's find out how often this happens and make a call to fix it

**Comment by AndiAJ** [comment]
Hi @boek , yes, still happening on the latest **`Nightly #20380605 from 2/7`** using the following devices:
• Google Pixel 3a XL (Android 10)
• Google Pixel 3a (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7.0.0)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

► Time lapsed video from Google Pixel 3a
![20200207_112519](https://user-images.githubusercontent.com/51314259/74017620-353b6700-499d-11ea-9bc0-c8764260ae22.gif)

**Comment by darkwing** [comment]
I'm seeing the very quick white flash as well; part of me wonders if the swipe-to-delete animation is affecting this, as it also turns the tab white upon swipe.

**Comment by sblatz** [comment]
There are two issues here I believe. One of them is GV is drawing a white page before it loads the session which is why you see the "flicker" of white. The other likely has to do with the animation we're using.

**Comment by sblatz** [comment]
This should be fixed by my new animation :)

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly Build #20650606 from 03/05`** using the following devices:
• Google Pixel 3a (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

►Video
![20200305-085559](https://user-images.githubusercontent.com/51314259/75957773-671fea80-5ec3-11ea-8f3e-43e460c478fc.gif)
