### ISSUE TITLE
[Bug]Selection handlers missing when tapping on "Select all" from the text selection floating bat

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#4729]
## Steps to reproduce
1. Navigate to a website and long tap on any plain text
2. Tap on "Select all" from the text selection floating bar

### Expected behavior
All text content is selected displaying the selection handlers

### Actual behavior
The selection handlers are missing

### Device information

* Android device: 
•  Samsung Galaxy S10 (Android 9)
•  Huawei Media Pad M3 Lite 10 (Android 7)

* Fenix version: Debug version from Master 14/08

►Video from Huawei Media Pad M3 Lite 10 (Android 7)
![20190814_172944](https://user-images.githubusercontent.com/51314259/63029574-7d2f7480-beb9-11e9-94c8-eb4b8cb06cfc.gif)

**Comment by kbrosnan** [comment]
This is Gecko behavior, the same issue is present in reference browser. Though I could see an argument that the selection handles are less likely to be needed as the user is expected to use copy as the next action.

Chrome has some odd behavior on Wikipedia with select all due to the hidden text on the 3 bar menu.

**Comment by bifleming** [comment]
@vesta0 Chris has asked for confirmation on the desired behavior for this.

**Comment by vesta0** [comment]
I just tested this with several sites. The behaviour in wikipedia is consistent across Fenix and Fennec. Many other sites (news sites, blogs, or sites opened in reader mode) do display the selection handlers in both Fennec and Fenix. I don't believe this is a bug.

On a different note, the responsiveness of selection handles in Fenix can be improved. I will file a separate bug for that.
