### ISSUE TITLE
[Bug] Search engines no longer display when entering search fragment

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#4732]
Looks like this was a merge conflict issue with: https://github.com/mozilla-mobile/fenix/pull/4406/files

**Comment by softvision-miralobontiu** [comment]
Verified as fixed on the latest Nightly 190821 (#12330640) with Sony Xperia Z5 Premium (Android 7.1.1), Huawei P9 Lite (Android 6), Sony Xperia Z2 Tablet (Android 6.0.1), OnePlus 5T (Android 9).
