### ISSUE TITLE
[Bug] White page some times. Need to refresh

### ISSUE THREAD

**Issue by andreiuipath** [mozilla-mobile/fenix#4734]
## Steps to reproduce
This does not happen often.
I open this link from history or from a collection
https://tools.taskcluster.net/index/project.mobile.fenix.v2.nightly/latest
### Expected behavior
The page should load like it always did until yesterday or two days ago since this is a recent issue.
It happens on other pages also, like on Reddit.
### Actual behavior
I get a white page. I need to refresh several times.
Some times I need to force quit Fenix Nightly from app permissions page.
![Screenshot_20190814-201935_Firefox_Nightly](https://user-images.githubusercontent.com/50407920/63041985-bbd12900-bed1-11e9-9bca-bf10a58d0b7c.png)

### Device information

* Android device: 
![android_version](https://user-images.githubusercontent.com/50407920/63041974-b378ee00-bed1-11e9-9882-19a663cae1b5.png)

* Fenix version: latest nightly

**Comment by boek** [comment]
@andreiuipath are you still experiencing this?

**Comment by andreiuipath** [comment]
@boek I haven't seen this in a while. Closing.
