### ISSUE TITLE
[Bug] Search shortcuts shouldn't be displayed when URL bar is tapped from browser

### ISSUE THREAD

**Issue by jyeontaek** [mozilla-mobile/fenix#4736]

**Comment by cadeyrn** [comment]
It's a duplicate of #4566 but since the commit references this issue I will close my issue…

**Comment by softvision-miralobontiu** [comment]
Verified as fixed on the latest Nightly 190819 (#12310612) and RC 1.3.0-rc.3 with Huawei P9 Lite (Android 6), and Xiaomi Mi 8 Lite (Android 9).

**Comment by PopeRigby** [comment]
This still isn't fixed for me
