### ISSUE TITLE
What's New Entry for 1.3 

### ISSUE THREAD

**Issue by ekager** [mozilla-mobile/fenix#4737]
This ticket tracks work for the SUMO page and Google Play release notes.

**Comment by vesta0** [comment]
Thanks @ekager :) We won't have a Sumo page for this release (starting with 1.4) but here are the release notes:

Thank you for testing Firefox Preview! This update includes major stability and bug fixes, and a brand new search widget that you can add to your Android home screen! Read more about it here: https://support.mozilla.org/en-US/kb/how-add-firefox-preview-search-widget-your-home-screen
