### ISSUE TITLE
[Bug] Left with blank session after clearing browsing data

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#4740]
I think we used to pop here, but now we're leaving users in a blank session.
![delete bug](https://user-images.githubusercontent.com/4400286/63055729-6b3ed900-be9b-11e9-9102-7747ef243ecd.gif)

Similar STR: https://github.com/mozilla-mobile/fenix/issues/4642

**Comment by sblatz** [comment]
I believe @colintheshots was working on fixes related to issues like this?

**Comment by boek** [comment]
I think this is fixed now @sblatz.

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **Nightly Build #13640626 from 12/30** using the following devices:

• Google Pixel 3a (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

► Video
![20191230_091256](https://user-images.githubusercontent.com/51314259/71572058-10261f80-2ae6-11ea-808b-b85b36ccbf0f.gif)
