### ISSUE TITLE
Refactor HomeFragment to be more testable

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#4744]
Currently there is a lot of code in HomeFragment that cannot be tested because it needs to be abstracted out. Let's refactor this code out and write some tests for it 😄

**Comment by NotWoods** [comment]
Some suggestions:
- [ ] Move `BrowserSessionsObserver` to its own file.
- [ ] Uplift getting only normal/only private sessions to Android Components.
- [ ] Move the search engine icon (in the search bar) to its own custom view, or move the entire search bar.
  - Maybe Android Components should have a search bar with icon component.
- [ ] Move `toolbarPaddingDp` to `dimens.xml`.
- [ ] Move the private browsing button to a custom view
- [ ] Move `preDrawListener` to a custom class that implements `LifecycleObserver`.
- [ ] `handleTabAction`/`handleCollectionAction` should be moved somewhere else, maybe an interactor.
- [ ]
