### ISSUE TITLE
Find in page text & text placeholder are black in private mode

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#475]
## Steps to reproduce
1. Open a webpage in private mode.
2. Open Find in page.
3. Verify the placeholder text and the text input.
### Expected behavior
The font should be white, following the PB theme.
### Actual behavior
The font is black, as it is in normal browsing.
### Device information

* Android device: Samsung Galaxy Note 8 (Android 8.0)
* Fenix version: 1.0

**Comment by ekager** [comment]
This is fixed in master

**Comment by sv-ohorvath** [comment]
Verified as fixed on Master.
