### ISSUE TITLE
[Bug] Intermittent crash when sending `fenix://enable_private_browsing`

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#4756]
This crash can happen when a user has the Fenix app open on the home screen, then sends the private browsing deep link event. This feels like a race condition. I can only reproduce every third or fourth try and it looks like it's related to lazy vars 😅 

Of note: I think this crash is hard to encounter in the real world.

In terminal:
```
adb shell
am android.intent.action.VIEW -d "fenix://enable_private_browsing"
``` 

<img width="1310" alt="image" src="https://user-images.githubusercontent.com/4400286/63116689-18bef480-bf4f-11e9-8efa-45523f8cb3ea.png">

**Comment by kbrosnan** [comment]
This intent does not launch a view any more.
