### ISSUE TITLE
[Bug] Private browsing history leaked to system through media playback notifications

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#4759]
For this same issue on Fennec, see: https://bugzilla.mozilla.org/show_bug.cgi?id=1431329

## Steps to reproduce
- Enter private browsing mode
- Visit a page with video content (e.g. https://www.w3.org/2010/05/video/mediaevents.html)
- Play the video

### Expected behavior
No notification appears in system tray.

### Actual behavior
Notification appears in system tray. At least historically, all information in notifications are leaked to the system, exposing the user's browsing history/media playback to the device, which is not okay in private browsing mode. See https://bugzilla.mozilla.org/show_bug.cgi?id=1431329 for additional details.

### Device information
* Android device: Pixel 2
* Fenix version: Nightly 190814 18:17

**Comment by mcomella** [comment]
The implementation appears to have been tracked as part of https://github.com/mozilla-mobile/fenix/issues/2551

**Comment by NotWoods** [comment]
Does mozilla-mobile/android-components#4103 address this?

**Comment by pocmo** [comment]
Note that this feature is only enabled in Nightly builds. 

Since https://github.com/mozilla-mobile/android-components/issues/3797 we no longer show any website specific information in the media notification when playing media in private mode.

**Comment by AndiAJ** [comment]
Hi @mcomella , the media playback notification **is till being displayed in PB** on the latest Fenix **Nightly Build #12380610 from 26/8**, used the following devices for testing:
• Google Pixel 3a (Android 9)
• Huawei Mate 20 lite (android 8.1.0)
• Samsung Glaxy S7 (Android 7)

@pocmo on the other hand as per [#3797](https://github.com/mozilla-mobile/android-components/issues/3797)  the media notification shows a very limited amount of information about the website.

►Video from Fenix
![ezgif com-video-to-gif (2)](https://user-images.githubusercontent.com/51314259/63681837-3ddd1e00-c7ff-11e9-8ec0-91a960a0c635.gif) 

►Video from Chrome
![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/51314259/63681786-1dad5f00-c7ff-11e9-9cd7-fd5904730134.gif)

**Comment by pocmo** [comment]
Correct. That's the intended behavior: Still showing the notification if media is playing, but do not show any details about the website.

**Comment by pocmo** [comment]
> Correct. That's the intended behavior: Still showing the notification if media is playing, but do not show any details about the website.

@topotropic Do you agree with that behavior?

**Comment by topotropic** [comment]
Yes, it's good that we still offer people to stop whatever is playing and still hide the details – @jpfaller can you please review the string "A site is playing media"
