### ISSUE TITLE
Restrict Report Site Issue link to non-release users

### ISSUE THREAD

**Issue by miketaylr** [mozilla-mobile/fenix#4760]
It seems like we can read this now: https://github.com/mozilla-mobile/fenix/blob/d03c15d15c36f005eab57b57a16920f6e5f12ad6/app/src/main/java/org/mozilla/fenix/FeatureFlags.kt#L6-L16

### Why/User Benefit/User Problem

The quality of fenix reports has been low, and more than our team can handle ATM. I'd like us to restrict Report Site Issue to nightly users at first, then we can decide if we move up to beta.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-13062)

**Comment by karlcow** [comment]
This should probably be closed. 
Report Site Issue is not available for release users and that's a good thing.

**Comment by csadilek** [comment]
Yes, this has been the case for a while. Feature is limited to Debug, Nightly and Beta builds:
https://github.com/mozilla-mobile/fenix/blob/cc666c8887e2758325cd0a4208e48c804f90b4bd/app/src/main/java/org/mozilla/fenix/components/Core.kt#L155
