### ISSUE TITLE
Enable GV logging in debug builds; disable GV logging in opt/production builds

### ISSUE THREAD

**Issue by cpeterso** [mozilla-mobile/fenix#4763]
### Why/User Benefit/User Problem

Fenix developers want to see debug logging in their debug builds. Users don't want their production browser builds to be slowed down by unnecessary debug logging.

### What/Requirements

GV 70 adds a new `debugLogging` API to enable or disable GV logging. Since GV logging is still enabled by default and GV doesn't know at runtime_ whether the _app_ is a debug or opt build, Fenix or A-C should call `debugLogging` API appropriately. For example, Fenix developer might want a local debug build _of Fenix_ to enable GV logging even though they are testing with an opt GV build.

### Acceptance Criteria (how do I know when I’m done?)

GV log output is seen in debug builds, but not in opt/production builds.

https://bugzilla.mozilla.org/show_bug.cgi?id=1573304

**Comment by cpeterso** [comment]
GV may disable its logging by default in production GV builds in https://bugzilla.mozilla.org/show_bug.cgi?id=1572540 but Fenix should always call the `debugLogging` API to be sure.

**Comment by ekager** [comment]
This sounds like a good thing to do when we are on GV70 in a few weeks :)
