### ISSUE TITLE
[Bug] Selecting a session while in BrowserFragment doesn't update UI

### ISSUE THREAD

**Issue by ekager** [mozilla-mobile/fenix#4767]
I was investigating https://github.com/mozilla-mobile/fenix/issues/4433 and realized this happens every time we select a new session while in BrowserFragment. 
1. Selecting Help in Browser Menu
2. Selecting report in Browser Menu
3. Long press a link -> Open in new tab -> Switch to tab

I'm not sure when we regressed here but there have a been a lot of Browser/Toolbar changes lately so it may take a bit of investigation

**Comment by ekager** [comment]
Because this is the root cause of #4433 and it is in the sprint, I'm pulling this in as well

**Comment by ekager** [comment]
Most likely caused by https://github.com/mozilla-mobile/android-components/issues/4141

**Comment by liuche** [comment]
This should be fixed by the fix in the AC issue in the comment above, which I think we're uplifting to 1.3.

**Comment by ekager** [comment]
Sorry updating! This should be fixed by https://github.com/mozilla-mobile/fenix/pull/4764 which we did uplift to 1.3
Tagging as QA needed and putting it in the milestone now

**Comment by softvision-miralobontiu** [comment]
Verified as fixed on RC 1.3.0-rc.3 with Xiaomi Mi 8 Lite (Android 9).
