### ISSUE TITLE
Home view animation issues

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#477]
When switching between private browsing and normal browsing on an actual device I no longer get the fading animation. On top of this, the "Current Session" text flashes on the screen for a brief moment before disappearing which is a bit jarring.

![animation](https://user-images.githubusercontent.com/4400286/52722967-8323b780-2f61-11e9-9c92-7bf93a17537c.gif)

### Device Information
Galaxy S9 Android 8.0

**Comment by boek** [comment]
this is fixed now
