### ISSUE TITLE
[Bug] Share tabs shares all tabs from private and normal browsing

### ISSUE THREAD

**Issue by LaurentiuApahideanSV** [mozilla-mobile/fenix#4771]
## Steps to reproduce
1. Open a few websites in normal and private browsing;
2. Tap the Open tabs menu, select "Share tabs" and select an app from the share dialog: e.g. gmail.
### Expected behavior
Only the tabs from the selected browsing mode should be shared. For example if the user is in normal browsing the tabs opened in private mode should not be shared.
### Actual behavior
All the tabs opened in private and normal browsing are shared.
### Device information

* Android device: Samsung Galaxy S8+ (Android 8.0.0)
* Fenix version: 1.3.0-rc. 1 Thursday 8/15

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on latest Nightly Build #12400613 28/8 using the following devices:
• Google Pixel 3a (Android 9)
• Huawei Mate 20 lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

► Sharing from NB
![20190828_141546](https://user-images.githubusercontent.com/51314259/63851919-ce526480-c99f-11e9-9bb1-3e4fa9f19654.gif)


► Sharing from PB
![20190828_141626](https://user-images.githubusercontent.com/51314259/63851980-eb873300-c99f-11e9-8f78-e66dc4763d7c.gif)
