### ISSUE TITLE
[Bug]Open a link in new private tab and switching should make transition to PB

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#4772]
## Steps to reproduce
1. Navigate to cnn.com
2. Long tap on a link
3. Select "Open link in private tab"
4. Tap switch from the snack bar
5. Tap on the tabs tray button

### Expected behavior
The transition to PB should be made after opening a link in a private tab.

### Actual behavior
No transition is made to PB.
By checking the navigation bar or by tapping the tabs tray button the user is still in Normal Browsing.

### Device information

* Android device: Huawei Media Pad M3 Lite 10 (Android 7)
* Fenix version: 
• Nightly Build #12280618 from 16/8
• 1.3.0-rc.1 from 15/8

► Video
![20190816_122432](https://user-images.githubusercontent.com/51314259/63158433-e92cec80-c021-11e9-8069-6cb592a24151.gif)

**Comment by sv-ohorvath** [comment]
This and https://github.com/mozilla-mobile/fenix/issues/5033 are the same, but I'll keep the other one opened because it illustrates better the current behavior (the opened tabs list shown when switching between browsing modes is incorrect).
