### ISSUE TITLE
[Bug] Weirdly drawn icons in the site security panel

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#4774]
## Steps to reproduce
1. Load a website with an insecure connection: eg. expired.badssl.com
2. Tap the lock icon in the toolbar.
### Expected behavior
TP icon and Insecure connection icons look normal
### Actual behavior
The icons are different and look weird on Android 5 & 6.
https://user-images.githubusercontent.com/4037709/63167122-04572680-c039-11e9-958f-a22130a75dcf.png
### Device information

* Android device: HTC Desire 820 (Android 6.0.1) & Xiaomi Mi Pad 2 (Android 5.1)
* Fenix version: Nightly 190816 & RC 1.3.0

**Comment by softvision-miralobontiu** [comment]
Verified as fixed on the latest Nightly 190821 (#12330640) with OnePlus 5T (Android 9), Huawei P9 Lite (Android 6.0.1), HTC Desire 820 (Android 6.0.1), Sony Xperia Z2 Tablet (Android 6.0.1), and Sony Xperia Z5 Premium (Android 7.1.1).
