### ISSUE TITLE
Redesign About page in Settings

### ISSUE THREAD

**Issue by lime124** [mozilla-mobile/fenix#4776]
pulling up Amy's comment from below:
> 
> Here is the updated mock with additional items we would like to include. Please note that this is a long list so please allow for page scrolling when adding additional items. Thanks!
> 
> What’s new in Firefox Preview (in current build) - https://support.mozilla.org/en-US/kb/whats-new-firefox-preview
> 
> Support - https://support.mozilla.org/en-US/products/firefox-preview
> 
> Privacy notice - https://www.mozilla.org/en-US/privacy/firefox/
> 
> Know your rights - about:rights
> 
> Licensing Information - about:license
> 
> GeckoView libraries we use (in current build)
> 
> Other open source libraries we use (in current build)
> 
> TBD **Release Notes** - need to confirm if we have these, @Tif will reach out to Joni Chan
> 
> ![Settings - About Firefox Preview@1x](https://user-images.githubusercontent.com/5992746/67527680-90af4680-f685-11e9-8023-f52606b875da.png)

**Comment by lime124** [comment]
@vesta0 this should be pretty small. it would be nice to get in if we have a bit of time.

**Comment by AmyYLee** [comment]
Let me know if there's anything else that needs to be added here:

![Settings - About Firefox Preview](https://user-images.githubusercontent.com/5992746/66350154-92a8a400-e928-11e9-891d-d447d798d2b1.png)

**Comment by NotWoods** [comment]
@AmyYLee Is this ready for eng?

**Comment by vesta0** [comment]
@lime124 please review Amy's design and let us know if this is ENG ready so we can size it during backlog grooming on Wednesday.

**Comment by lime124** [comment]
@AmyYLee for a few technical reasons, we need to call out gv libraries separately. Can you add a third row a the bottom under "Open source..." for this. Same layout and styling. 

Text suggestion: "GeckoView libraries we use"

let me ping michelle to see who jeff's back up is. once Amy updates and we have final string we can label ready for eng. thanks!

**Comment by lime124** [comment]
@mheubusch can confirm the copy suggested in my prior comment. thanks!

**Comment by mheubusch** [comment]
I recommend this order/text: 
What's new in Firefox Preview
GeckoView libraries we use  
Other open source libraries we use

**Comment by AmyYLee** [comment]
@lime124 @mheubusch I've updated the mock with the updated copy. This is ready for eng.

[Mock](https://share.goabstract.com/364d4712-f3b7-4934-86b0-28c915d31341?mode=design&sha=360871bf8307e573f4bc8aea173d8a7cbe8c904e)

![image](https://user-images.githubusercontent.com/5992746/67032089-e792aa00-f0e0-11e9-92e3-1e5f2efaa2d4.png)

**Comment by Amejia481** [comment]
@AmyYLee I think the section **"GeckoView libraries we use"** should be renamed to **"Mozilla libraries we use"**, as we use two major libraries from Mozilla Geckoview and Android Components

**Comment by vesta0** [comment]
Hey @AmyYLee sorry to add more requirements after you have already completed working on this ticket but I think it will be easier to do this in one go. Would you please take a look at the Fennec About page below and make sure you have considered all these options? I don't think we need to include all of them but want to make sure that you have considered them all.

![Screenshot_20191022-153327](https://user-images.githubusercontent.com/42752644/67324403-c6b3c580-f4e1-11e9-80fb-5879b26f3f57.png)

FYI @lime124

**Comment by AmyYLee** [comment]
@lime124 @vesta0 I reviewed what was in Fennec and either found a Preview equivalent or the same link if it applies to Preview as well and also open questions either one of you. Please see below:


FAQ - Do we have a page for Preview? I found Fennec but couldn't find one for Preview (Do we need one?) - I think if we have one it doesn't hurt to add it but if we don't we can leave this out.

Support - https://support.mozilla.org/en-US/products/firefox-preview (We should have this)

Privacy Policy - https://www.mozilla.org/en-US/privacy/firefox/ (We should have this)

Know your rights - about:rights (We should have this)

What’s new in Firefox Preview - https://support.mozilla.org/en-US/kb/whats-new-firefox-preview (We should have this)

Release Notes - I couldn't find Preview release notes, who should I reach out to find that? (We should have this)

Credits - Do we have a list? Do we need it? - I don't think we need this if we don't already have a list.

Licensing Information - about:license (We should have this)

**Comment by AmyYLee** [comment]
@lime124 @vesta0 Hi, I also noticed that the screenshot you posted is the "about:firefox" page and not the the "Mozilla Firefox" page that is in-app to Fennec. This is more equivalent I think

![Screenshot_20191023-121809](https://user-images.githubusercontent.com/5992746/67413787-d4278900-f58f-11e9-91ff-78f2176339eb.png)

**Comment by lime124** [comment]
@  joni chen - does fenix have release notes that we can point in the app?

@vesta0 - we don't have credit or an FAQ page. amy and i don't think a credit page is necessary at this point, but please feel free to file follow up bugs for either credits or FAQ and the ux team can figure out designs and where they go in the settings.

**Comment by AmyYLee** [comment]
Hi, 

Here is the updated mock with additional items we would like to include

![Settings - About Firefox Preview@1x](https://user-images.githubusercontent.com/5992746/67527680-90af4680-f685-11e9-8023-f52606b875da.png)

**Comment by lime124** [comment]
can this be picked up by a contributor? are there dependencies?

**Comment by lime124** [comment]
i reached out to joni. if release notes are required and depending on timing, we can either update the mock in this issue or create a follow up .

**Comment by NotWoods** [comment]
I think this can be picked up by contributors. Except for the bottom two items, all the links should open a new web page. We should probably open custom tabs similar to the support menu that already exists.

**Comment by lime124** [comment]
removing @AmyYLee and @Baron-Severin to signal this issue is free to be picked up.

**Comment by vesta0** [comment]
@lime124 @AmyYLee sorry for delay in responding. I agree with your recommendations. 

I will file a bug for FAQ or Credits page if needed.

**Comment by AmyYLee** [comment]
![Settings - About Firefox Preview@1x](https://user-images.githubusercontent.com/5992746/69173284-796d4880-0acd-11ea-960e-0b38719958ea.png)




> I'm working on this and I have a few questions:
> 
>     * I saw in the mock that the links are hardcoded but in the app [getSumoURLForTopic](https://github.com/mozilla-mobile/fenix/blob/c9e4303fa03b8dbcfc21c804571750d7be01ce6e/app/src/main/java/org/mozilla/fenix/settings/SupportUtils.kt#L39) is used to get a dynamic page URL, based on locale, app version etc.
>       For example, for `What's new in Firefox Preview` the new specifications say that we should use
>       "https://support.mozilla.org/en-US/kb/whats-new-firefox-preview"
>       but using [current method from AboutFragment](https://github.com/mozilla-mobile/fenix/blob/c9e4303fa03b8dbcfc21c804571750d7be01ce6e/app/src/main/java/org/mozilla/fenix/settings/AboutFragment.kt#L79) would get us
>       "https://support.mozilla.org/1/mobile/1.0.1947/Android/en-GB/whats-new-firefox-preview"
>       I don't think we should use the hardcoded links because this will impact users with different locales.



>       Should all the new provided links use the same schema (with locale, app version etc) from [SumoTopic](https://github.com/mozilla-mobile/fenix/blob/c9e4303fa03b8dbcfc21c804571750d7be01ce6e/app/src/main/java/org/mozilla/fenix/settings/SupportUtils.kt#L26)? In this case the new sumo pages will have to be created for
>       
>       * Support
>       * Privacy Notice

I agree we should be using links that support different locales. I’m not sure how we can go about getting links for Support and Privacy Notice. @NotWoods can you confirm?



> 
> 
> Please also note that the "about:rights" page also does not exists yet in the app.

We have “about:rights” and “about:license” in Fennec. How do we go about getting these for Fenix? @NotWoods 
> 
>     * For the last two items it's not clear what we should display.
>       
>       * For the `Other open source libraries we use` should we use the old link for `Open source libraries we use`?
>       * What we should display for `GeckoView libraries we use`?

@Amejia481 Do you know what libraries we should link to?
Also minor edit to the copy. Can you change "GeckoView libraries we use" to "Mozilla libraries we use"

Thanks

**Comment by Amejia481** [comment]
> @Amejia481 Do you know what libraries we should link to?

If we want to have a separate section for **Mozilla libraries** and for **non Mozilla Libraries**, we should have:

- **Mozilla libraries we use**: Android Components and GeckoView.
- **Third party libraries we use**: all third party libraries 

I think we can just have one section for all libraries **"Libraries that we use"**

**Comment by AmyYLee** [comment]
> > @Amejia481 Do you know what libraries we should link to?
> 
> If we want to have a separate section for **Mozilla libraries** and for **non Mozilla Libraries**, we should have:
> 
>     * **Mozilla libraries we use**: Android Components and GeckoView.
> 
>     * **Third party libraries we use**: all third party libraries
> 
> 
> I think we can just have one section for all libraries **"Libraries that we use"**

![Settings - About Firefox Preview@1x](https://user-images.githubusercontent.com/5992746/69175901-a5d79380-0ad2-11ea-8173-1518daba03e8.png)

I agree let's consolidate and use "Libraries that we use" - see mock above. @ValentinTimisica Also can you remove "Privacy notice" from the Settings page now that we are moving this into the About page. Thanks

**Comment by ValentinTimisica** [comment]
Thanks all for your responses!
There is still one questions about the ```Know your rights``` item:
- We already had in Settings page this link for 'Your Rights': https://support.mozilla.org/1/mobile/1.0.1947/Android/en-GB/your-rights
Should I use this instead of 'about:rights' which looks much too basic and also has to be implemented from scratch (right now "about:rights" page does not exists in the app )?

In Fennec the 'about:rights' page looks like this:

![device-2019-11-21-130916](https://user-images.githubusercontent.com/52956363/69333245-009ef580-0c61-11ea-8b9d-a088d0518a27.png)

**Comment by liuche** [comment]
Hi @Mugurell if you're working on this can you move it into the In-Progress column of the kanban? https://github.com/mozilla-mobile/fenix/projects/9

**Comment by AmyYLee** [comment]
> Thanks all for your responses!
> There is still one questions about the `Know your rights` item:
> 
>     * We already had in Settings page this link for 'Your Rights': https://support.mozilla.org/1/mobile/1.0.1947/Android/en-GB/your-rights
>       Should I use this instead of 'about:rights' which looks much too basic and also has to be implemented from scratch (right now "about:rights" page does not exists in the app )?
> 
> 
> In Fennec the 'about:rights' page looks like this:
> 
> ![device-2019-11-21-130916](https://user-images.githubusercontent.com/52956363/69333245-009ef580-0c61-11ea-8b9d-a088d0518a27.png)

@ValentinTimisica Hi, thanks for pointing this out. Please use 'Your Rights': https://support.mozilla.org/1/mobile/1.0.1947/Android/en-GB/your-rights

**Comment by ValentinTimisica** [comment]
In the current implementation I saw that the item click events are tracked (example for [Whats's new](https://github.com/mozilla-mobile/fenix/blob/18edad9e45e763c3cc190e1ad4fc111162331175/app/src/main/java/org/mozilla/fenix/settings/AboutFragment.kt#L76) item). Should I create a new task for adding telemetry to all the new introduced items?

**Comment by AmyYLee** [comment]
> In the current implementation I saw that the item click events are tracked (example for [Whats's new](https://github.com/mozilla-mobile/fenix/blob/18edad9e45e763c3cc190e1ad4fc111162331175/app/src/main/java/org/mozilla/fenix/settings/AboutFragment.kt#L76) item). Should I create a new task for adding telemetry to all the new introduced items?

@ValentinTimisica This would be great if it doesn't require a lot of additional effort. Thank you.

**Comment by nt1m** [comment]
FWIW, we do have a credits page: https://www.mozilla.org/credits/

**Comment by softvision-miralobontiu** [comment]
Hi all!
The design in Settings - About in the latest Nightly from 12/17 is:
![Screenshot_20191217-105900](https://user-images.githubusercontent.com/40694158/70986858-6d25dc80-20c7-11ea-90d1-8094497936f2.png)

I've encountered an [issue](https://github.com/mozilla-mobile/fenix/issues/7240) on Google Pixel (Android Q) regarding the "Privacy notice" page.
I'll remove the qa:needed label for now.
Thanks!
