### ISSUE TITLE
Investigate Toolbar Titles with long Title Strings

### ISSUE THREAD

**Issue by ekager** [mozilla-mobile/fenix#4778]
It came up in UX review of ETP and Delete Browsing Data that when we have a longer string as the title of a Settings category we should make a generic decision about how we want to deal those titles.
Material Design urges against wrapping title strings. 
But it should also be noted that in other languages very long strings could be truncated with less context than in English. 
We should come up with a plan/solution for how to deal with titles that will ellipsize by default and investigate how these our current strings look in other localizations.
@shorlander recommends continuing the default behavior of truncating the strings because the user has context from the Setting they clicked on to get to the next screen, but we want to continue the discussion and make a more generic decision.

**Comment by lime124** [comment]
adding @jpfaller perhaps you can help with some ideas and thoughts on this?

**Comment by jpfaller** [comment]
Per our discussion yesterday, I agree with @shorlander

**Comment by ekager** [comment]
Okay then I think we should close this ticket and follow that pattern in the future :)
