### ISSUE TITLE
Close button in the search bar is not visible

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#478]
## Steps to reproduce
1. Tap the search bar in normal browsing mode.
2. Oberve the "x" button.
3. Tap the search bar in private browsing mode.
4. Oberve the "x" button.
### Expected behavior
The button is visible in both modes.
### Actual behavior
In normal browsing, the "X" isn't visible at all.
In private mode, it's very small.
### Device information

* Android device: Samsung Galaxy Note 8 (Android 8.0)
* Fenix version: 1.0.1907

**Comment by ekager** [comment]
I filed an [AC issue for this](https://github.com/mozilla-mobile/android-components/issues/2054) since I don't think we have any control of this imageView currently

**Comment by ekager** [comment]
The small size part of this issue has been fixed by the AC team

**Comment by ekager** [comment]
There is a new attr in AC but we are blocked on updating to 44+ currently

**Comment by sv-ohorvath** [comment]
Verified as fixed.
