### ISSUE TITLE
Switch out of private mode when app is removed from memory

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#4780]
I'm opening this in response to https://github.com/mozilla-mobile/fenix/pull/4773. 

Currently it is **expected behavior** that we persist private mode when the app is paused. With the introduction of our "launch in private browsing" feature we should consider if we want to keep this behavior.

@AmyYLee commented on that PR: 
> @rushsteve1 We are in the process of implementing a private mode launcher shortcut option on homescreen. If the concern here is not wanting someone to know that you were in private browsing mode from Firefox Preview, having a separate launcher for private browsing mode allows the user to separate their public browsing vs. private browsing activities with a separate launcher. Hope this solves your issue.

Of note: our "normal" launcher will still launch in private mode if that's where the user left it, so I don't think it actually solves that case. We should just decide if we want this functionality.

**Comment by AmyYLee** [comment]
@sblatz Hi, with the introduction of PBM launcher I think we should modify the behaviour for when Firefox Preview is set in the background (swiped up off the screen). Right now, if the user was last in PBM with tabs opened and backgrounds the app, the private tabs are cleared but it is still set in PBM. The new behaviour would be when the app is in the background in PBM, upon opening the app again, it will default back to non-private browsing mode. Let me know if you have any questions
![2019_08_19__15_23_27_011_0](https://user-images.githubusercontent.com/5992746/63539915-19283400-c4e9-11e9-8d38-73547cb37d49.jpg)

**Comment by rushsteve1** [comment]
I apologize for not making this issue myself, and for the slightly late reply.

@AmyYLee Yes! This is exactly the functionality I was suggesting and the change is completed, in a basic manner, but the PR that I opened that started all this #4773.

**Comment by rushsteve1** [comment]
Following up on this since I has been a while. Has any decisions been made on this issue?

**Comment by sblatz** [comment]
@rushsteve1 I will bring this up in our next triage meeting since we are adding the ability to launch in default private mode soon :)

**Comment by vesta0** [comment]
@sblatz does switching out of private mode mean that users will lose their private tabs?

**Comment by sblatz** [comment]
@vesta0 No, it'd be equivalent to pressing the mask icon to switch back to normal browsing :)

**Comment by vesta0** [comment]
@sblatz great, thanks for confirming 👍

**Comment by sblatz** [comment]
To clarify: should we only show "normal mode" if the private mode tabs have been cleared (by the user force quitting the app or the system killing our process)? Or should it *always* show normal mode?

**Comment by rushsteve1** [comment]
In my patch at least, and in the main version of Firefox Android, it only switches back to Normal mode when the app is killed and the private mode tabs are destroyed.

I personally think that this is better UX, since applications that haven't been quit are thought of as still being in-use. Also it would be very counter-intuitive to switch modes while retaining the private tabs.

**Comment by sblatz** [comment]
@rushsteve1 https://github.com/mozilla-mobile/fenix/pull/4773/files would get us most of the way there but we'd need to make sure to *not* switch to normal mode if the user launched with the private browsing shortcut or has "always open links in private mode" enabled.

**Comment by rushsteve1** [comment]
That should be a simple matter of replacing the
```kotlin
setPrivateModeI(false)
```
with (I don't know the actual variables but the idea should be obvious)
```kotlin
setPrivateMode(privateBrowsingShortcut || alwaysOpenInPrivate)
```

**Comment by sv-ohorvath** [comment]
@sblatz Verified on latest Nightly 10/4: The default launcher (of normal browsing) keeps opening in PBM (where it was left) when the "Open links in private mode" setting is checked.

**Comment by Baron-Severin** [comment]
Thanks @sv-ohorvath, I'll work on a fix.

**Comment by sv-ohorvath** [comment]
Verified as fixed on Nightly 10/9.

**Comment by klint** [comment]
Hi. I have opend  a feature request #5883 to provide a way to open Fenix in normal mode in all cases, even if Fenix was previously used in PBM and has not been removed from the memory yet. 
Maybe I's only me and maybe I'm not understanding the design, but I must confess I'm rather lost in the transitions between PBM and normal modes :) IMHO, these modes should actually behave like 2 different browsers (with a few bridges), but the do not...

**Comment by Baron-Severin** [comment]
> Hi. I have opened a feature request #5883 to provide a way to open Fenix in normal mode in all cases, even if Fenix was previously used in PBM and has not been removed from the memory yet.
> Maybe it's only me and maybe I'm not understanding the design, but I must confess I'm rather lost in the transitions between PBM and normal modes :) IMHO, these modes should actually behave like 2 different browsers (with a few bridges), but they do not fully...

Thank you for opening the feature request!  We look at every new request, but we're a little backed up atm and it's taking us a while to get through to them.  FWIW, I think there's currently a lot of discussion around private mode with different options being discussed.  I'm not sure what we'll eventually land on, but the behavior in this PR won't **_necessarily_** be final.

**Comment by klint** [comment]
@Baron-Severin  Thanks a lot for the clarification. Looking forward to what's next :)

**Comment by opusforlife2** [comment]
Hi. I was thinking of opening a new issue but I found this in milestones.

The previous behavior was fine for me. I use desktop Firefox in private browsing mode permanently, and the Fenix toggle replicated that functionality on Android. With this feature gone, I have to open Fenix, switch to private browsing each time, and then continue. 

Can there be a toggle to use private browsing permanently, just like desktop Firefox?

**Comment by cadeyrn** [comment]
@opusforlife2: You can add a private shortcut to your home screen. You find this option on the settings screen.

**Comment by sblatz** [comment]
@opusforlife2 if you go to “set as default browser” in Fenix’s settings and enable “open links in private mode” as well as adding the private mode shortcut to your home screen you will effectively have an “always private mode” browser like on desktop :)

Let me know if this doesn’t cover your use case.

**Comment by opusforlife2** [comment]
@sblatz One minor nitpick with the current behavior: When you open Fenix using the private browsing shortcut, it takes you straight to the address bar in private browsing mode, but if you tap back, it switches to non private browsing.

But in general, I would prefer the private browsing shortcut to open Fenix not to the address bar with the keyboard automatically popping up, but to the home screen, like it normally does with the default launcher icon.

For complete feature parity with desktop Firefox, though, I would like a setting which makes it impossible to exit private browsing mode unless that setting is turned off.

**Comment by sblatz** [comment]
@opusforlife2 can you please file a separate issue for that and tag me on it? :)

**Comment by opusforlife2** [comment]
@sblatz Done!

**Comment by DatGrey** [comment]
> 
> 
> @sblatz Verified on latest Nightly 10/4 and found one issue: The default launcher (of normal browsing) keeps opening in PBM (where it was left) when the "Open links in private mode" setting is checked.

I'm still having this issue, can someone please confirm I'm not the only one? Thanks.

**Comment by sv-ohorvath** [comment]
@DatGrey this is now expected. More details here: https://github.com/mozilla-mobile/fenix/issues/7577

**Comment by DatGrey** [comment]
@sv-ohorvath thanks, I'm not sure I understand the reasoning behind it though... Wouldn't it be more logical for the browser to switch back to normal mode if there's no private tabs open anymore? Or just use whatever was the last used mode, ignoring links/custom tabs? Having different shortcuts (default/private mode) makes no sense otherwise, since simply turning on the "Open links in private mode" option overrides the default/private shortcut behavior.

Maybe I'm just misusing the "Open links in private mode" option? I thought its use was to not "pollute" the browser history with random links openend from different apps (WhatsApp, Reddit, etc), keeping them separated from normal browsing, but right now the option is not affecting only links... the current behaviour is more similar to "Always use private mode" than "Open links in private mode".

**Comment by sv-ohorvath** [comment]
@DatGrey 
"Open links in private mode"'s only function is to always open external links and homescreen page shortcuts in private, no matter on which browsing mode you are on.

The browser then keeps as default the mode which was last used when is backgrounded or killed (swiped out of recent tasks) - this functions independent of "Open links in private mode"
 So if you opened a link in private, then minimize, or kill the app, reopen it, it will keep private mode on (even with no tabs). 
If you switch back to normal browsing before, then it will open normal browsing on restart.

I hope this makes sense. 
Also please make sure to update to the latest version of Nightly.

**Comment by DatGrey** [comment]
@sv-ohorvath thanks for your patience, I've just realized (thanks to your explanation) that the issue I've been seeing happens only when opening links with Firefox in "Chrome Custom tabs" mode - everything works fine using Firefox normally, which I'm doing now.
I'm gonna check if that particular issue has already been reported and report it myself if needed.
