### ISSUE TITLE
Enhanced Tracking Protection needs Page Load Testing

### ISSUE THREAD

**Issue by colintheshots** [mozilla-mobile/fenix#4783]
## User Story
- As a member of the Fenix team, I would like performance measurements on the relative page load speeds of Tracking Protection versus the new Enhanced Tracking Protection feature.

## Dependencies
- This will require some assistance from the Performance Team to learn how to run comparative Raptor testing using Try with live loads and custom parameters and/or APKs.

### Acceptance Criteria
- We have accurate page load performance measurements of ETP vs. TP on the latest Fenix with enough runs to have reasonable certainty in the results.

**Comment by vesta0** [comment]
The goal of this experiment is to determine performance impact of switching from TP (current) to ETP, and based on the results make a decision on whether Fenix default/recommended setting should be Basic or Strict (see [here](https://mozilla.invisionapp.com/share/R8T6GDUDW3B#/screens))

Cohort a (ETP):
- Block Cross-site Tracking Cookies from Disconnect's Advertising, Analytics, and Social list

Cohort B (Current TP implementation):
- Blocking tracking scripts (not just the tracking cookies) from Disconnect's Advertising, Analytics, and Social list

@Amejia481 and @ekager would you please add the name of lists/prefs to be used for each cohort? Thank you!

**Comment by Amejia481** [comment]
**Cohort a (ETP):**

- `TrackingProtectionPolicy.recommended()`

**Cohort B (Current TP implementation):**

- `TrackingProtectionPolicy.strict()`

**Comment by liuche** [comment]
Remaining work E2.

**Comment by vesta0** [comment]
> **Cohort a (ETP):**
> 
>     * `TrackingProtectionPolicy.strict()`

I don't believe this is correct. ETP (#1749) is a new category and refers to blocking Cross-site Tracking Cookies from Disconnect's Advertising, Analytics, and Social list. It is less strict than what we currently block in Fenix, and corresponds to the new `standard` option in the [new UI](https://mozilla.invisionapp.com/share/R8T6GDUDW3B#/screens).
> 
> 
> **Cohort B (Current TP implementation):**
> 
>     * `TrackingProtectionPolicy.recommended()`

The current TP implementation (blocking tracking scripts/sub-resources, not just cookies) is more strict and corresponds to the `strict` option in the new UI.

**Comment by Amejia481** [comment]
The default policies on ac have been updated on `12.0.0` to be aligned with the mockups and what Desktop is using https://github.com/mozilla-mobile/android-components/issues/4349.

Now the cohorts should match as follow:

- **Cohort A:** (Standard on the mockups)

`    TrackingProtectionPolicy.recommended()`

- **Cohort B:** (Strict on the mockups)

`TrackingProtectionPolicy.strict()`

**Comment by mcomella** [comment]
Triage: waiting on any form of page load testing with visual metrics.

**Comment by mcomella** [comment]
From Eric on this issue:

> Yeah, please close. Testing has happened already at least twice that I'm aware of.
