### ISSUE TITLE
[Bug] Intermittent blank Fenix when returning to Custom Tab

### ISSUE THREAD

**Issue by agi90** [mozilla-mobile/fenix#4785]
## Steps to reproduce

* Sometimes when returning to CustomTab I get a blank Fenix (see screenshot). Usually it's when I haven't been using my phone for a while.

### Device information

* Android device: Samsung S10
* Fenix version: Latest Nightly Fenix from today

![Screenshot_20190816-160007_Firefox Preview](https://user-images.githubusercontent.com/4297388/63202630-76cb0500-c03f-11e9-8ae3-34dd3b5387df.jpg)

**Comment by agi90** [comment]
I still see this very frequently.

**Comment by ekager** [comment]
Dupe of https://github.com/mozilla-mobile/fenix/issues/5041?

**Comment by agi90** [comment]
Yep sounds like the same issue!

**Comment by ekager** [comment]
Okay gonna close this onefor #5041 then :)
