### ISSUE TITLE
[Bug] Tab logic broken

### ISSUE THREAD

**Issue by mikeGolf08** [mozilla-mobile/fenix#4789]
## Steps to reproduce

1. Open a new website
2. Enter a new website or just start a new search at awesomebar

### Expected behavior

It opens the website/search on the same tab.

### Actual behavior

It opens a new tab for the website/search.

### Device information

* Android device: Android 9 on OnePlus 3T (A3003) Oxygen OS 9.0.5
* Fenix version: Nightly 190817 06:05 (Build #12290612)
    package: 8.0.0, 78354bc12
    lizard: 69.0-20190812090043

**Comment by ekager** [comment]
Will be fixed by #4800

**Comment by softvision-miralobontiu** [comment]
Verified as fixed on the latest Nightly 190821 (#12330640) with OnePlus 5T (Android 9), Huawei P9 Lite (Android 6.0.1), and Sony Xperia Z5 Premium (Android 7.1.1).
