### ISSUE TITLE
Bring back the Awesomescreen!!

### ISSUE THREAD

**Issue by Cheap-Skate** [mozilla-mobile/fenix#479]
Why? Because it's AWESOME. Easily the best thing about Fennec (IMHO) 

Awesomescreen:- I can see e.g. ~4 x search autocomplete suggestions, ~2x search history suggestions AND 3 x page history suggestions AND have 4 or 5 search engines listed at the bottom of the screen. Fenix - just ~3 search autocomplete suggestions OR page history suggestions.  So, so much wasted space.  And with Fenix I can't type 3 letters and search Wikipedia, something I do a lot on Fennec.

reference-browser at least has the Google search suggestion grid which half way to Awesomeness.

IMHO it would be a tragedy to lose the Awesomescreen. Its absence might be a show-stopper for me, Fenix might just look like Brave/Samsung Internet only a bit slower and a bit less correct.

**Comment by boek** [comment]
Dup of #1161
