### ISSUE TITLE
Prevent malicious websites from adding duplicate history entries

### ISSUE THREAD

**Issue by daufinsyd** [mozilla-mobile/fenix#4796]
## User Story
- As a user, I don't want that a malicious website can prevent me from going back in my history so I can continue browsing the web from the page I was, before entering the malicious website.

Steps :
- goto a malicious website https://pcgamestorrents.com/
or https://phonewebadsprivate.pw/ea93c168-32cc-4fe5-8d55-25f9acd15c7f/?btd=dHJrLm1vYmlsZXRvcDIwMTh0ZWNoaWUueHl6&exptoken=MTU2NjEzODEyOTcwMg%3D%3D&lang=fr&r_brand=Generic&r_model=Android+8.0&td=dHJrLmNvb2stZ2lhbnQtdW5kZXItbGVnLnh5ei9wcmNlZWQ 
- the user is redirected to some other website
- the user cannot exit the malicious website using the go back key.

## Dependencies
- #3907 

### Acceptance Criteria
- I can navigate to whatever website and I can exit malicious one, without having to close the tab (thus losing my browing history).

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-13088)

**Comment by buttercookie42** [comment]
Might be solved if we finally get the session history fragment back (#3514)?

**Comment by daufinsyd** [comment]
yes I think so (when the complete history is displayed and not just the few last pages)

**Comment by kbrosnan** [comment]
This is fixed, we show a list of previous pages when long pressing on the back button. BZ-1644595 is fixed.
