### ISSUE TITLE
Sticky Reader Mode: Links opened in reading mode should also try to open in reader mode

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/fenix#4797]
### Why/User Benefit/User Problem

As a user who is already in reader mode, I'd like to remain in reader mode to enjoy the benefits of reader mode when navigating links while I am reading. 

Requested on reddit as well: https://www.reddit.com/r/firefox/comments/crzqwi/androidfeature_request_links_opened_in_reading

Referenced here: http://www.ianbicking.org/blog/2019/03/firefox-experiments-i-would-have-liked.html#sticky-reader-mode

Previously filed for Fennec in https://bugzilla.mozilla.org/show_bug.cgi?id=811462

### What/Requirements

* links tapped while in reader mode should try to load in reader mode, falling back to normal mode if not supported.

### Acceptance Criteria (how do I know when I’m done?)

1. Navigate to: https://www.cbsnews.com/news/capital-one-data-breach-2019-more-than-100-million-people-applying-for-credit-affected-today-2019-07-29/?ftag=CNM-00-10aab4i
2. Enable reader view
3. Tap first linked page -- it should be a cbsnews.com domain
4. The linked page will load in reader view

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-13089)

**Comment by hXtreme** [comment]
Hi,

I'm the person who requested this feature on reddit. If someone could point me to relevant part of code that handles hyperlink clicks, I would like to try to implement this myself.

Thanks,
Harsh

**Comment by vrudesai** [comment]
This feature does not exist on Firefox Android

**Comment by yoasif** [comment]
@hXtreme This may help you dig into how this works: https://github.com/mozilla-mobile/android-components/pull/2273

**Comment by issue-dispenser** [comment]
It would also be nice if there was an option to stay in reader mode if editing a URL in a reader mode page, for multi-page webpages without visible links (e.g. chapters in a web novel). This was possible in Fennec due to it supporting editable `about:reader?url=` URLs (#5190), though that's not the only way to support this feature.

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813949

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
