### ISSUE TITLE
[Bug] "Copy link" snackbar has bad copy

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/fenix#4798]
## Steps to reproduce

1. Navigate to https://www.cbsnews.com/news/capital-one-data-breach-2019-more-than-100-million-people-applying-for-credit-affected-today-2019-07-29/
2. Tap and hold on any link
3. select "Copy link"

### Expected behavior

copy that uses the text in the menu entry I picked, like "Link copied to clipboard" in the snackbar.

### Actual behavior

"Text copied to clipboard" snackbar appears.

### Device information

* Android device: Pixel 2
* Fenix version: latest nightly

**Comment by ekager** [comment]
@mheubusch do you want a new string in this case? If not please close this bug :)

**Comment by lime124** [comment]
waiting for Jeff to be added to the repo and then will @ mention. him. He is going to be taking over for Michelle.

**Comment by lime124** [comment]
@jpfaller

**Comment by jpfaller** [comment]
Let's go with "Link copied to clipboard"

This string also needs to get applied to the snackbar that appears when someone copies an image location. 

![Screenshot_20190821-130651](https://user-images.githubusercontent.com/50755458/63456496-0ea06880-c41d-11e9-9807-142183e685ee.png)

**Comment by ekager** [comment]
Merged in AC as https://github.com/mozilla-mobile/android-components/pull/4453 we should get this in the next snapshot

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on Nightly Build #12621819 from 19/9 using the following devices:
• Google Pixel 3a (Android 9)
• Samsung Galaxy Note 9 (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

►Video
![20190920_154440](https://user-images.githubusercontent.com/51314259/65327970-e3489f00-dbbd-11e9-8d86-f684b81f97df.gif)
