### ISSUE TITLE
[Bug] Wrong tab saved to collection when switching session in BrowserFragment

### ISSUE THREAD

**Issue by ekager** [mozilla-mobile/fenix#4799]
Related to #4767 

## Steps to reproduce
1. Open site 
2. Open menu -> Report Site
3. Menu -> add to collection

### Expected behavior
Report site is added to a collection

### Actual behavior
First site is added to a collection

### Device information

* Android device: ?
* Fenix version: ?

**Comment by softvision-miralobontiu** [comment]
Verified as fixed on RC 1.3.0-rc.3 with Huawei P9Lite (Android 6).
