### ISSUE TITLE
[Bug] URL wrong in the address bar opening in a new tab

### ISSUE THREAD

**Issue by maulonobile** [mozilla-mobile/fenix#4803]
## Steps to reproduce
I opened a link from duckduckgo ti another tab. Then i click on "passa a" (italian language) and the new tab is opened but the url not changed: the new tab url was wrong because there was the duckduckgo url yet if i try to share, didnt share the new tab url but duckduckgo url.

### Expected behavior
the new tab address bar would have the url of site i'm browsing

### Actual behavior
the address bar shows the address of the original site

### Device information

* Android device: Android 7.0
* Fenix version: Firefox Mobile 69.0
![url address wrong](https://user-images.githubusercontent.com/50904371/63242988-7f972300-c259-11e9-9663-de60c9ea98b0.jpg)

**Comment by ekager** [comment]
This was fixed by #4800
