### ISSUE TITLE
[Bug] History line items missing basic three-dot menu options

### ISSUE THREAD

**Issue by AaronMT** [mozilla-mobile/fenix#4817]
The three dot menu option for each history menu item in the library is missing basic options like: 

- Open in new tab
- Open in new private tab
- Copy
- Share

Currently, each bookmark line item has (in their associated three-dot menu) 

- Edit
- Copy
- Share
- Open in new tab
- Open in new private tab
- Delete

**Comment by buttercookie42** [comment]
#2597 and #2435.

**Comment by NotWoods** [comment]
Closing as duplicate, see above issues.
