### ISSUE TITLE
[Bug] Can't paste into fxa login password field

### ISSUE THREAD

**Issue by ekager** [mozilla-mobile/fenix#4818]
## Steps to reproduce
1. Settings -> Sign in
2. Try to paste into passwords field in FXA login 

### Expected behavior
Can paste

### Actual behavior
Cannot paste

Opened: https://bugzilla.mozilla.org/show_bug.cgi?id=1574987

**Comment by makotokato** [comment]
@ekager I cannot reproduce this using Fenix Nightly 191001 (GV 71.0a1-20190930095343).  Could you still reproduce this?

**Comment by ekager** [comment]
Nope can no longer reproduce. Closing!
