### ISSUE TITLE
Sending telemetry event for onboarding every app launch

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#4824]
Follow up from https://github.com/mozilla-mobile/fenix/pull/4753#discussion_r315338296

See https://github.com/mozilla-mobile/fenix/blob/master/app/src/main/java/org/mozilla/fenix/onboarding/FenixOnboarding.kt#L26 getting called always.

**Comment by tsimica** [comment]
Is this issue free to work on? If so I would like to work on this!
