### ISSUE TITLE
[Test] Add tests for FragmentPreDrawManager (#4827)

### ISSUE THREAD

**Issue by Mugurell** [mozilla-mobile/fenix#4828]
After the code refactoring from #4827 we need new tests for `FragmentPreDrawManager`

**Comment by obarzpaw** [comment]
I would like to work on this.

**Comment by obarzpaw** [comment]
@NotWoods @Mugurell 

Hey, as you notice I've created PR. But it isn't finished yet. I have some problem with the verify: 

`verify { fragmentMock.startPostponedEnterTransition() }`

Can you give me some guidance, how can verify that the startPostponedEnterTransition was called?

**Comment by NotWoods** [comment]
It's a little tricky to test because of the asynchronous callback. In this case it may be simpler to check that `fragment.view.addOnAttachStateChangeListener` is called. (see the implementation of `view.doOnPreDraw`.)

**Comment by obarzpaw** [comment]
@NotWoods , Thank you for yout help.

Test is now working and ready to merge.
