### ISSUE TITLE
[Bug] Opening a link from an external app opens on private mode

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/fenix#4831]
## Steps to reproduce [video demo](https://drive.google.com/file/d/1N3ztt6xymC7T5QrqdUefyw7uO4nerJFr/view?usp=sharing) 📹 

1. Open a site on private mode.
2. Go to Gmail or an other app and open a link

### Expected behavior
The site should be opened in normal mode

### Actual behavior
The site is shown in private mode 
### Device information

* Android device: Pixel 3
* Fenix version: Nightly 190820 11:47 (Build #12321201)
📦: 9.0.0, 3c8dd6f50
🦎: 69.0-20190819100044

**Comment by athomasmoz** [comment]
There is now a setting to choose whether to open in private or regular mode. Need to confirm that this has been fixed

**Comment by abodea** [comment]
Verified as fixed on the latest **Nightly build 11/26 with Google Pixel 3a XL(Android 10).**

Note that I tried more scenarios with many pages opened in private browsing, but when I opened a link from Gmail(or any external app), it was always opened in normal browsing.
Based on my comment I will close this issue.
