### ISSUE TITLE
[Bug] Dangerous subdomain elision

### ISSUE THREAD

**Issue by Madis0** [mozilla-mobile/fenix#4839]
## Steps to reproduce
1. Open [https://long-extended-subdomain-name-containing-many-letters-and-dashes.badssl.com/](https://long-extended-subdomain-name-containing-many-letters-and-dashes.badssl.com/) 
2. Watch the address bar

### Expected behavior
The subdomain gets elided, e.g. `...-many-letters-and-dashes.badssl.com/`

### Actual behavior
The domain gets elided, e.g. `https://long-extended-subdomain-name-...`

### Device information

* Android device: Android 9
* Fenix version: Nightly 190820 18:01 (Build #12321806)

**Comment by kbrosnan** [comment]
Closing as a dupe.

**Comment by Madis0** [comment]
Dupe to what?

**Comment by kbrosnan** [comment]
A security bug that has already been filed on Bugzilla.
