### ISSUE TITLE
[Meta] Componentize UI

### ISSUE THREAD

**Issue by lime124** [mozilla-mobile/fenix#4841]
This is to cover creating reusable UI components. The benefit of this work would be to reduce the amount of eng effort as bits of UI don't need to be recreated. It will also help ensure consistency in the UI of the app and make updating a bit easier. From the UX side, it will increase efficiency and delivery for some work. We no longer need to deliver high fid mockups for everything and can instead reference components and provide content/styling information.

This ticket is to cover the high-level, app wide effort. Designers and eng will break it down in to smaller pieces that can be delivered on a little at a time.

Components:
- CFR, https://github.com/mozilla-mobile/fenix/issues/5499
- List element, https://github.com/mozilla-mobile/fenix/issues/8765
- Favicon, https://github.com/mozilla-mobile/fenix/issues/7992
- Bottom sheets, https://github.com/mozilla-mobile/fenix/issues/9047

**Comment by liuche** [comment]
Moving this to UX backlog from triage. Please move somewhere else if it shouldn't be here!

**Comment by liuche** [comment]
@sblatz or @boek do you have in mind an issue/UI element that could be used to be the first iteration of this? Also, relatedly could be to come up with a plan for what UI Components looks like. 
This should be timeboxed.

**Comment by sblatz** [comment]
@liuche I think the "just in time" notifications we have throughout the app would be good. Another first one would be the buttons we use (we have: destructive, normal filled, neutral filled currently).

**Comment by olsenme** [comment]
Has anyone picked up this issue? Looks like there might be some work in progress on it.

**Comment by sblatz** [comment]
@olsenme This is a meta issue which we'll be breaking out into further tickets. #5499 is the one we're focusing on next :)

**Comment by topotropic** [comment]
cc @betsymi this is the component meta, there's a list of components in the initial comment
