### ISSUE TITLE
[Bug] Fix bug 1554984

### ISSUE THREAD

**Issue by kbrosnan** [mozilla-mobile/fenix#4844]
https://bugzilla.mozilla.org/show_bug.cgi?id=1554984

**Comment by st3fan** [comment]
Can the "URL Display" code please be moved to A-C? This sounds like something we need to get right in multiple products.

**Comment by Baron-Severin** [comment]
> Can the "URL Display" code please be moved to A-C? This sounds like something we need to get right in multiple products.

The more I look at this problem, the more I think we should go even further than that.  I've written a bandaid implementation for the worst edge cases that we _could_ base an A-C change on, but I think this is something we really need to be sharing with desktop.  It's very complex, there are _many_ ways it can go wrong, and it's a String -> String transformation.  I think this could be a really good candidate for a Rust component.

**Comment by liuche** [comment]
@Baron-Severin is this ready for QA? we should add the qa-needed label if so.

**Comment by softvision-miralobontiu** [comment]
The [bug 1554984](https://bugzilla.mozilla.org/show_bug.cgi?id=1554984) is not fixed yet, therefor I'll remove the qa-needed flag.

**Comment by Baron-Severin** [comment]
> The [[bug 1554984](https://bugzilla.mozilla.org/show_bug.cgi?id=1554984)](https://bugzilla.mozilla.org/show_bug.cgi?id=1554984) is not fixed yet, therefor I'll remove the qa-needed flag.

Hey @softvision-miralobontiu 👋 .  Could you elaborate on what is not yet fixed?  This code has been merged to master, but if a requirement is missing I'll be happy to fix it.

**Comment by softvision-miralobontiu** [comment]
@Baron-Severin I misinterpreted this issue, then. 
Could you help me with some STR, in order to verify it?
Thanks!

**Comment by Baron-Severin** [comment]
> @Baron-Severin I misinterpreted this issue, then.
> Could you help me with some STR, in order to verify it?
> Thanks!

Responded in BZ

**Comment by softvision-miralobontiu** [comment]
Based on your [comment](https://bugzilla.mozilla.org/show_bug.cgi?id=1554984#c15), I'll remove the qa-needed flag, and add the qa-not-needed one.

**Comment by ekager** [comment]
@Baron-Severin I merged #7036 but not sure if I should close this ticket

**Comment by Baron-Severin** [comment]
@ekager this is good to close, thanks for remembering!
