### ISSUE TITLE
[Bug] Default widget size should be 5x1, not 4x1

### ISSUE THREAD

**Issue by SeburoSUMO** [mozilla-mobile/fenix#4846]
The Firefox Preview has a default size of 4x1, whereas the default for Fennec is 5x1 (see attached screenshot)
![Screenshot_1566336507746~2](https://user-images.githubusercontent.com/31939113/63386293-a0b35d00-c39a-11e9-9a2b-3a673476e20d.jpg)

### Expected behavior

If the Firefox Preview widget was 5x1 it would appear better (resizing is possible but is a bit fiddly) and should resize down as required.

### Actual behavior

Appears small by default.

### Device information

* Android device: Motorola E5, Android 8
* Fenix version: Nightly 190820 18:01 (Build #12321805)📦: 9.0.0, 3c8dd6f50 🦎: 69.0-20190819100044

**Comment by brampitoyo** [comment]
Agreed. Firefox Preview’s default widget size should be 5x1, rather than 4x2 as shown.

<img width="360" src="https://user-images.githubusercontent.com/51007/75742162-ab02da80-5d71-11ea-82c5-ccb33a20f96a.png">

@SeburoSUMO My device (OnePlus One) shows 4x2, which is taller than it’s supposed to. Does your device show 4x1?

**Comment by SeburoSUMO** [comment]
Hi Bram.

By default, Fennec used 5x1, with Fenix using 4x1 (for me at least).  The first screenshot shows (going down the list), Fennec Beta, a migrated Fennec to Fenix Nightly and Fenix Nightly.

![Screenshot_1583275268726](https://user-images.githubusercontent.com/31939113/75827603-f92fd200-5da1-11ea-86ce-b32bc9b27bbb.jpg)

This second image is having selected the Fenix Nightly widget, then tapped it again to get the resizing grid - it is 4x1.  Unless you know to resize it, it looks a bit short.

![Screenshot_1583275251716](https://user-images.githubusercontent.com/31939113/75827707-2c726100-5da2-11ea-9477-930b60484bec.jpg)

My thinking is that if the widget was 5x1, like Fennec was, it will look better for users without having the need to resize.  When resized and moved to the top of the screen, it makes a great replacement for the Google bar.

**Comment by SeburoSUMO** [comment]
Looking at the latest Nightly, this issue appears to have been resolved.  In the image attached "Fennec paul" is a self-built Fennec for me to help users, the upper Firefox Nightly is a Fennec that has migrated to Fenix, with the lower Firefox Nightly being a standard Fenix Nightly.
  
![Screenshot_1588106381751](https://user-images.githubusercontent.com/31939113/80541535-316b1f80-89a3-11ea-8c85-d354f996dfc1.jpg)

For all three, most notably the standard Fenix Nightly, the default desktop app size is 5x1, better fitting the screen on mobile telephone devices.

I believe this issue to be resolved and can be closed.
