### ISSUE TITLE
[Bug] Crash when moving the cursor on a video

### ISSUE THREAD

**Issue by softvision-miralobontiu** [mozilla-mobile/fenix#4852]
## Steps to reproduce
1. Go to youtube.com or vimeo.com
2. Play a video and move the cursor forward.

### Expected behavior
The video should continue playing from that point on.

### Actual behavior
The app crashes.

### Device information
* Android device: OnePlus 5T (Android 9), Sony Xperia Z2 (Android 6.0.1) tablet, 
* Not reproducible on HTC Desire 820 (Android 6.0.1)
* Fenix version: Nightly 190821 (#12330640)

[logcat-crash.txt](https://github.com/mozilla-mobile/fenix/files/3524469/logcat-crash.txt)

![20190821_120152_Trim](https://user-images.githubusercontent.com/40694158/63418987-ab0e3f00-c40c-11e9-8725-bd73a5c4e90f.gif)

**Comment by ekager** [comment]
Could we retest this?

**Comment by softvision-miralobontiu** [comment]
Verified on the latest Nightly build 190910 (#12531817) with Sony Xperia Z5 Premium (Android 7.1.1), and OnePlus 5T (Android 9) and it is no longer reproducible.
I will close this issue.
