### ISSUE TITLE
[Bug] Bookmark selection overlay buttons disappear after the deletion snackbar disappears

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#4855]
### Prerequisites
Have a couple of saved bookmarks.

## Steps to reproduce
1. Navigate to the bookmarks section
2. Tap on the favicon of one of the bookmarks (The selection bar is activated)
3. For another bookmark from the 3 dot button tap on delete
4. Tap on the upper right 3dot button from the selection bar
5. Wait for the snackbar to disappear

### Expected behavior
The buttons from the upper right overlay remain displayed

### Actual behavior
After the deletion confirmation snackbar disappears the overlay buttons disappear as well

### Device information

* Android device: 
• Google Pixel 3a (Android 9)
• Sony Xperia Z2 tablet (Android 6.0.1)

* Fenix version: 
Nightly Build #12330640 from 21/8

### Notes

► Video from Google Pixel 3a
![20190821_170626](https://user-images.githubusercontent.com/51314259/63442455-cfcddb00-c43b-11e9-9d4f-94ec702ea0c1.gif)

**Comment by shahsurajk** [comment]
i could try this.

**Comment by mcarare** [comment]
After implementation of #2570 , the STR will not be possible anymore.

**Comment by AndiAJ** [comment]
Hi, as per Mihai's implementation from #2570 this can't be reproduced anymore on Nightly Build #12621819 from 19/9 using the following devices:
• Google Pixel 3a (Android 9)
• Samsung Galaxy Note 9 (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

►Video
![20190920_155127](https://user-images.githubusercontent.com/51314259/65328560-45ee6a80-dbbf-11e9-8799-656e795120ac.gif)

Based on this I'll mark it as verified and close it.
