### ISSUE TITLE
[Bug]After switching back to Fenix the "Find in page" bar can't be dismissed

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#4856]
## Steps to reproduce
1. Navigate to any website
2. From the lower right 3dot button select "Find in page"
3. Switch to the Gmail app
4. Switch back to Fenix
5. Tap the 'x' (close) button from the "Find in page"

### Expected behavior
After tapping the  'x' (close) the "Find in page" bar should be dismissed  

### Actual behavior
After tapping the  'x' (close) the "Find in page" bar isn't dismissed

### Device information

* Android device: 
• Google Pixel 3a (Android 9)
• Sony Xperia Z2 tablet (Android 6.0.1)

* Fenix version: Nightly Build #12330640 from 21/8

### Notes
► Video from Google Pixel 3a
![20190821_172947](https://user-images.githubusercontent.com/51314259/63442953-9f3a7100-c43c-11e9-950e-82d785ea6962.gif)

**Comment by mcarare** [comment]
This is not reproducible in sample browser. This is a Fenix implementation of FindInPage issue.

**Comment by jonalmeida** [comment]
Sorry, closed this bug in error.

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **Nightly Build #12520610 from 9/9** using the following devices:
• Google Pixel 3a (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

► Video
![20190909_172716](https://user-images.githubusercontent.com/51314259/64539631-7f091e00-d327-11e9-8063-25158da2ea46.gif)

**Comment by AndiAJ** [comment]
Hi, just as an FYI I've bumped in this issue while testing **RC 1.4.1** on a Samsung Galaxy Tab A (Android 9).
