### ISSUE TITLE
[Bug] pressing the [x] in bookmarks or history view makes two steps to start screen

### ISSUE THREAD

**Issue by cadeyrn** [mozilla-mobile/fenix#4863]
### Steps to reproduce

1. open the history or bookmarks view in your library
2. press the [x] button

### Expected behavior

The start screen of Fenix appears immediately.

### Actual behavior

You can see how Fenix makes two steps: It first opens the library screen and then in a second step the start screen.

### Device information

* Android device: HTC U11 / Android 9.0
* Fenix version: Fenix 1.3.0

**Comment by ekager** [comment]
I can reproduce and weirdly I *don't* see this if I go to Library -> History from the browser

**Comment by ekager** [comment]
Removing the delay seemed to have helped a bit, but I think the home screen is still a complex fragment that's fairly slow to startup and that's causing the small flash of Library

**Comment by mcarare** [comment]
I too think that. Maybe we should revisit this issue after the problems with the home fragment have been solved, and see if we still have issues with the transition.

**Comment by cadeyrn** [comment]
Is there already an issue filed for improving the home screen fragment?

**Comment by mcarare** [comment]
I think https://github.com/mozilla-mobile/fenix/issues/4665

**Comment by boek** [comment]
when #1063 lands we may try this again :)

**Comment by topotropic** [comment]
is this still an issue now that we removed the x to close with https://github.com/mozilla-mobile/fenix/issues/6523?

**Comment by cadeyrn** [comment]
No, this is no longer an issue!
