### ISSUE TITLE
[webcontent]No save button on Google preference page

### ISSUE THREAD

**Issue by shizunge** [mozilla-mobile/fenix#4872]
### Expected behavior
Expect a save button on Google preference page.
![Expected](https://user-images.githubusercontent.com/1281491/63493851-58b33980-c471-11e9-8d11-5c1a6556fb4a.jpg)

### Actual behavior
There is no save button on Google preference page
![Actual](https://user-images.githubusercontent.com/1281491/63493843-5224c200-c471-11e9-8501-0452039048fe.jpg)

### Does toggling Tracking Protection fix the issue? (Press the lock icon in the toolbar while on the site to see toggle)

I did not try.

### Can you reproduce in [Firefox for Android](https://play.google.com/store/apps/details?id=org.mozilla.firefox)?

Yes.
This may be a Google issue. In Firefox 68.0.2, I can change User-Agent to fix this problem (via Add-ons). 

### Can you reproduce in Chrome (or other non-Mozilla browser)?

I did not try. But I guess i cannot reproduce it in Chrome.

### Device information

* Android device: 9
* Fenix version: 190820 18:01

**Comment by ekager** [comment]
Can reproduce and toggling TP does not fix the problem

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Fenix Nightly Build 200713 from 7/13`** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)

► Video
![20200713-121127](https://user-images.githubusercontent.com/51314259/87287017-423b2400-c502-11ea-9dc6-e2fcadaec7e1.gif)
