### ISSUE TITLE
UI test task fails with gradle error

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/fenix#4875]
https://tools.taskcluster.net/groups/bRDWVRZFQzm32nvETBzy2g/tasks/WFFXcYWfSp-Dkn8Wvi8zGA/runs/0/logs/public%2Flogs%2Flive.log

`Task 'assembleArmDebug' not found in root project 'fenix'. Some candidates are: 'assembleDebug'.`

**Comment by AaronMT** [comment]
https://github.com/mozilla-mobile/fenix/blob/f2affcc6b4e58fc8b7eecffba4df3a2cc028e724/automation/taskcluster/lib/tasks.py#L179

`assembleDebug` and perhaps `assembleDebugAndroidTest`

@rpappalax

**Comment by rpappalax** [comment]
@pocmo I'm working on a fix for this:  https://github.com/mozilla-mobile/fenix/issues/4866

**Comment by pocmo** [comment]
@rpappalax Thanks! `assembleDebug` builds with GeckoView Nightly and Beta (two apks). You can also use `assembleGeckoBetaDebug` or `assembleGeckoNightlyDebug`.

**Comment by rpappalax** [comment]
Fixed by #4963 #5024 #4951
