### ISSUE TITLE
Enable UI tests on github-pull-request

### ISSUE THREAD

**Issue by rpappalax** [mozilla-mobile/fenix#4889]
We would like to enable UI tests to run on github-pull-request. Currently they are only activated for github-push:
https://github.com/mozilla-mobile/fenix/blob/master/automation/taskcluster/decision_task.py#L82

We can easily enable this in the decision_task, but will need some assistance from taskcluster team to ensure we have proper permissions/scopes.
@JohanLorenzo can you assist with this?

This is currently enabled on mozilla-mobile/firefox-tv and we'd like to also enable it for fenix.

Workflow would be:

1. I work on a patch
2. I submit a PR
3. Taskcluster runs unit tests and UI tests
4. Taskcluster must pass ALL of the tests for me to get a green check
5. I merge

If a contributor submits a patch, we will manually trigger step 3 as allowPullRequests will be restrictec to collaborators as in firefox-tv project:
https://github.com/mozilla-mobile/firefox-tv/blob/master/.taskcluster.yml#L6

**Comment by rpappalax** [comment]
@sblatz @npark-mozilla

**Comment by JohanLorenzo** [comment]
Some patches are also referenced under https://bugzilla.mozilla.org/show_bug.cgi?id=1577479

**Comment by rpappalax** [comment]
This has already been merged here:

@rpappalax rpappalax referenced this issue on 30 Aug
Bug 1577479 - Run UI tests on PRs #5011
