### ISSUE TITLE
String needs update to apostrophe

### ISSUE THREAD

**Issue by Delphine** [mozilla-mobile/fenix#4892]
I didn't block on this in quarantine, as it can be fixed in a follow-up commit:
preferences_delete_browsing_data_cookies_subtitle : string needs a curly apostrophe.

Note: no need to update string ID for this one :)
thanks!

**Comment by mcarare** [comment]
@Delphine how about sign_out_confirmation_message ?

**Comment by Delphine** [comment]
@mcarare Good catch, that seems to have fallen through the cracks 🤔
Absolutely!

**Comment by mcarare** [comment]
Fixed by #5062
