### ISSUE TITLE
[Bug]Fenix widget can't be added on Android 6 devices

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#4894]
## Steps to reproduce
1. Long tap on the home screen of your device
2. Select widgets
3. Touch and hold the Firefox Preview widget & move it to your home screen

### Expected behavior
Widget can be added to the home screen of the device and can be used properly

### Actual behavior
Instead of the actual Firefox Preview widgets a Black bar shows up saying "Problem loading the widget"
![rsz_screenshot_20190823-1124366666666](https://user-images.githubusercontent.com/51314259/63578515-53e9a500-c599-11e9-8d09-05cbe26557f3.png)

### Device information

* Android device: 
• Samsung Galaxy S6 (Android 6)
• OnePlus A3 (Android 6.0.1)
• Huawei P9 Lite (Android 6)

* Fenix version: 1.0.1934 (Build # 1) 📦: 10.0.0, 1c652634c GV: 70.0a1-20190822095439 from **23/8**

### Notes
►Video from  Samsung Galaxy S6

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/51314259/63578934-32d58400-c59a-11e9-9b78-63fc35dd3682.gif)

**Comment by DiegoARL38** [comment]
Same in TP-Link Neffos C5 Max, Android 5.1.0

1.0.1934 (Build #1)
📦: 10.0.0, 1548b663a
GV: 70.0a1-20190821095414

**Comment by mcarare** [comment]
@jyeontaek gradient is not supported for vector drawables below SDK 24. Do you have any solution besides adding a different vector for versions below 24?

**Comment by NotWoods** [comment]
@mcarare We can use vector drawable compat to load the icons with gradients. Replacing `android:background` with `app:srcCompat` should be sufficient.

**Comment by AndiAJ** [comment]
Hi, **verfied as fixed** on **Fenix Nighlty Build #12470611 from 4/9** using the following devices:
• Samsung Galaxy S6 (Android 6.0.1)
• OnePlus A3 (Android 6.0.1)

►Video
![20190904_125030](https://user-images.githubusercontent.com/51314259/64245133-09f6ac80-cf13-11e9-92f5-5f15f0c2d3fb.gif)
