### ISSUE TITLE
[Bug] The images don't get displayed on Ladbible.com homepage

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#4900]
## Steps to reproduce
1. Navigate to http://www.ladbible.com

### Expected behavior
The content from the page is properly displayed

### Actual behavior
None of the article images aren't displayed

### Device information

* Android device: Google Pixel 3a (Android 9)
* Fenix version: 1.0.1934 (Build # 1) 📦: 10.0.0, 1c652634c GV: 70.0a1-20190822095439 from 23/8

### Notes
►Video
![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/51314259/63597479-367f0000-c5c6-11e9-9d9b-c9de955dac49.gif)

**Comment by ekager** [comment]
Is this fixed by toggling TP? If so could you close this and add this issue to #5392?

**Comment by Amejia481** [comment]
It looks like a webcompat issue, this site doesn't work on FireFox desktop neither on geckoview_example

**Comment by ekager** [comment]
Closing because I'm not seeing this anymore
