### ISSUE TITLE
[Bug]Event selection check boxes aren't displayed properly on Flashcore.com 

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#4901]
## Steps to reproduce
1. Navigate to https://www.flashscore.com/

### Expected behavior
The page is properly loaded 

### Actual behavior
Some of the events selection boxes aren't properly displayed
![rsz_screenshot_20190823-1700555555](https://user-images.githubusercontent.com/51314259/63598619-9c6c8700-c5c8-11e9-934c-5ff315a473f2.png)

### Device information

* Android device: Google Pixel 3a (Android 9)
* Fenix version: 1.0.1934 (Build # 1) 📦: 10.0.0, 1c652634c GV: 70.0a1-20190822095439 from 23/8

### Notes

**► Fenix**
![Screenshot_20190823-165343](https://user-images.githubusercontent.com/51314259/63598368-13ede680-c5c8-11e9-8a67-20aeb5736886.png)

**► Chrome**
![Screenshot_20190823-165356](https://user-images.githubusercontent.com/51314259/63598349-0a647e80-c5c8-11e9-987c-6cb79f90d1ef.png)

**Comment by ekager** [comment]
Is this fixed by toggling TP? If so could you close this and add this issue to https://github.com/mozilla-mobile/fenix/issues/5392?

**Comment by boek** [comment]
@AndiAJ? ^^

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **Nightly Build #13640626 from 12/30** using the following devices:

• Google Pixel 3a (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

The website was changed since I reported the issue, the TP being enabled/disabled doesn't have any impact. ☺️ 

► Video
![20191230_125933](https://user-images.githubusercontent.com/51314259/71579433-2d1e1b00-2b05-11ea-81e3-ebd0550a3d6c.gif)
