### ISSUE TITLE
[Bug] Fill link from clipboard should be on top of shortcuts

### ISSUE THREAD

**Issue by hakkikaancaliskan** [mozilla-mobile/fenix#4902]
## Steps to reproduce
Press search bar on homescreen.
### Expected behavior
Link from the clipboard should be shown on top of the shortcuts
Like this: 
<img src="https://user-images.githubusercontent.com/17825767/63601106-7eedec00-c5cd-11e9-971d-2d2def096c35.png" width=25%>

### Actual behavior
Not shown unless closing shortcuts
Like this:
<img src="https://user-images.githubusercontent.com/17825767/63601336-e4da7380-c5cd-11e9-817e-b08d0be59b70.png" width=25%><img src="https://user-images.githubusercontent.com/17825767/63601289-d12f0d00-c5cd-11e9-8a3a-7d0a56b66a76.png" width=25%>

### Device information

* Android device: Xperia XZ1 Android 9
* Fenix version: 
Nightly 190823 12:10 (Build #12351219)
📦: 10.0.0, 1c652634c
🦎: 70.0a1-20190822095439

**Comment by raygervais** [comment]
I'd like to fix this, can someone point me to the right location to look at? I'm new to the project and would like to start contributing.

**Comment by hakkikaancaliskan** [comment]
#1744
