### ISSUE TITLE
[Bug] Pressing Back from External Links Opened In Fenix Doesn't Always Go Back to Other App

### ISSUE THREAD

**Issue by ekager** [mozilla-mobile/fenix#4904]
## Steps to reproduce
1. Have Fenix as default browser
2. Open Fenix and open a website
3. Go to another app and open a link that will open in Fenix (not custom tab)
4. Press back

### Expected behavior
Go back to app you clicked link from

### Actual behavior
Go to Fenix homescreen. 

This is because we currently check and put you on a browser fragment on the stack if it exists to avoid the "display already acquired" crash. We should investigate whether this is still necessary.

### Device information

* Android device: ?
* Fenix version: ?

**Comment by ekager** [comment]
The desired behavior here is that if you launch Fenix from an external app (not a custom tab though so Messages etc) and then immediately press back you should end up back on the other app and the tab should be closed in Fenix.

**Comment by ekager** [comment]
I think we should prioritize this because it is hurting usability for Fenix as a default browser

**Comment by Baron-Severin** [comment]
Unassigning myself and moving this to the backlog.  I'm working on another project this week.

**Comment by kglazko** [comment]
Seeing some different behaviors on the emulator (Pixel 2) as well. 
Pre- Set fenix as default
1. Download Audabon Society app
2. Open Fenix and go to reddit.com for example (don't go back to homescreen, leave it there)
3. Go to audobon -> MyAudobon -> (click) Give Now

Expected:
Audabon tab will open in Fenix 

Actual:
(About 1/2 of the time) 
Fenix will open with Reddit
Going to home screen will only show Reddit tab
Clicking hardware back will take you back to Audabon
Coming back to Fenix app will now show Audabon tab along with reddit

**Comment by sv-ohorvath** [comment]
Verified as fixed on v3.2.-beta1. 
Devices: Xiaomi Mi Pad 2 (Android 5.1), Galaxy Note 8 (Android 9)
