### ISSUE TITLE
[Bug] Cannot see video on nfl.com site

### ISSUE THREAD

**Issue by mozillamarcia** [mozilla-mobile/fenix#4905]
## Steps to reproduce
* Load http://www.nfl.com/videos/nfl-game-highlights/0ap3000001043485/Optical-illusion-or-TD-Raiders-score-in-unusual-fashion
* Observe the video is black

### Expected behavior
* I would be able to see the video.

### Actual behavior
* I can hear the video but not see it

### Device information
Pixel 3
* Android device: Android Q
* Fenix version: 1.30
![Screenshot_20190823-122337](https://user-images.githubusercontent.com/2171777/63608625-754f8e80-c5a3-11e9-9ae9-753bf6acd9fe.png)

**Comment by mozillamarcia** [comment]
I also tested using Firefox and Firefox nightly, and the video does display fine in those browsers.

**Comment by ekager** [comment]
If I turn TP off I can see the video. Can you confirm that works for you?

**Comment by mozillamarcia** [comment]
> If I turn TP off I can see the video. Can you confirm that works for you?

Yes it does. I guess I will have to turn off TP if I don't want this to happen for every site.

**Comment by ekager** [comment]
Closing but adding this to #5392 - meta for TP web issues
