### ISSUE TITLE
Consolidate OSS License Information for All Fenix Libraries

### ISSUE THREAD

**Issue by colintheshots** [mozilla-mobile/fenix#4910]
### Why/User Benefit/User Problem
Currently, our open source license display is spread out across the About Screen for JVM licenses, an about:license URL for GeckoView engine licenses, and somewhere internal for application-services libraries (https://mozilla.github.io/application-services/docs/applications/consuming-megazord-libraries.html#third-party-licenses).

### What/Requirements
Users need one place to track all licenses for all parts of the Fenix codebase. This is probably somewhere like the About screen.

### Acceptance Criteria (how do I know when I’m done?)
Users should have links available to see all open source licenses from one screen without knowing where to find multiple links or URLs.

**Comment by boek** [comment]
@colintheshots to add links to dependent issues

**Comment by colintheshots** [comment]
This PR was accepted to the Gradle plugin to allow multiple licenses in a POM file. This was a pre-requisite to getting application-services licenses ingested through the Gradle build. We don't have a new release available yet, but we could build our own, if needed.
https://github.com/google/play-services-plugins/pull/88/files

Here's the bug for application-services to include the licenses in the POM files:
https://bugzilla.mozilla.org/show_bug.cgi?id=1558789

Currently, GeckoView only includes the MPL license in the POM file. I'll see about creating an issue to include all relevant licenses in their POM, but they seem to have around 100 licenses in their about:license screen, so it may not be very practical.

**Comment by colintheshots** [comment]
We discussed this in #gv and it seems there are around 100 licenses included in GeckoView. I think it makes more sense to add a link to show about:license just for the engine licenses. It hardly seems practical to parse their license.html file into the POM file and keep it up-to-date.

I filed this issue: https://github.com/mozilla-mobile/fenix/issues/5536

**Comment by vesta0** [comment]
Hey @colintheshots can we close this issue now that you have filed #5536 ?

**Comment by colintheshots** [comment]
Yes. That seems fine. Closing.
