### ISSUE TITLE
Implement user permission prompt for ETP's Storage Access cookie API

### ISSUE THREAD

**Issue by cpeterso** [mozilla-mobile/fenix#4916]
When web content calls the [Storage Access cookie API](https://developer.mozilla.org/en-US/docs/Web/API/Storage_Access_API), GV will ask the app to show a Storage Access user permission prompt. The GV API is https://bugzilla.mozilla.org/show_bug.cgi?id=1543720.

Gecko has some internal shortcuts to automatically allow or deny Storage Access without showing a user prompt. In https://bugzilla.mozilla.org/show_bug.cgi?id=1573238, @ehsan asked for another shortcut based on domains visited in the last 24 hours ("getUniqueDomainsVisitedInPast24Hours"). Fenix, not GV, knows the user's browsing history, so Fenix should include this "getUniqueDomainsVisitedInPast24Hours" logic to automatically return ALLOW instead of showing the user prompt.

See Fenix's ETP meta issue #1749. Note that implementing these Storage Access prompts does *not* block enabling ETP in Fenix. (We're enabling ETP in Fennec ESR 68.1 and won't be implement these Storage Access prompts.) But it would be nice to implement the prompts soon after enabling ETP in Fenix.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-13155)

**Comment by cpeterso** [comment]
Focus implemented the Storage Access prompt in https://github.com/mozilla-mobile/focus-android/issues/6027.

**Comment by Amejia481** [comment]
Already covered on https://github.com/mozilla-mobile/android-components/issues/10739
