### ISSUE TITLE
[Bug] Selecting an item on m.aliexpres.com is not working

### ISSUE THREAD

**Issue by softvision-miralobontiu** [mozilla-mobile/fenix#4921]
## Steps to reproduce
1. Open m.aliexpres.com
2. Go through categories until you reach a product (i.e. "Home & Garden" -> "Home Decor" -> "Clocks" and select the first item from the list).

### Expected behavior
The selected product should be opened in a new tab (like in Fennec, or Chrome).

### Actual behavior
Nothing happens. On long-tap, the menu is displayed from which "Open in new tab" can be selected.

### Device information
* Android device: Motorola Moto G6 (Android 8), Huawei P9 Lite (Android 6)
* Fenix version: Nightly 190826 (#12380610)
* It works in Firefox for Android 68.0.2

[logcat-aliexpres.txt](https://github.com/mozilla-mobile/fenix/files/3540992/logcat-aliexpres.txt)

**Comment by softvision-miralobontiu** [comment]
Also reproducible on https://m.yahoo.co.jp/ when trying to open an article.

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest Nightly Build **#12400613** from 28/8 using the following devices:

• Google Pixel 3a (Android 9)
• Huawei Mate 20 lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

► Video from Google Pixel 3a
![20190828_105351](https://user-images.githubusercontent.com/51314259/63837740-ba4d3980-c984-11e9-8e4d-f3be8939b814.gif)
