### ISSUE TITLE
Sites can't fetch data from Reddit through their API when tracking protection is enabled[webcontent]

### ISSUE THREAD

**Issue by anotherus3r** [mozilla-mobile/fenix#4924]
## Site with issue and any steps to reproduce

Removeddit.com, a page that logs removed or deleted Reddit posts and comments, as well as other websites that fetch data from Reddit, are unable to connect to Reddit when tracking protection is enabled. Another example is http://reddit.dataoverload.de/karmastats/

### Expected behavior

Loads data fetched from Reddit. For example, Removeddit.com loads a list of removed posts and/or comments.

### Actual behavior

Site can't fetch data from Reddit. In the case of Removeddit.com, it gives a "Could not connect to Reddit" error.

### Does toggling Tracking Protection fix the issue? (Press the lock icon in the toolbar while on the site to see toggle)

Yes.

### Can you reproduce in [Firefox for Android](https://play.google.com/store/apps/details?id=org.mozilla.firefox)?

Same problem in Firefox Nightly when tracking protection is enabled.

### Device information

* Android device: 9.0 Pie
* Fenix version: 1.3.1 (Build #12341950)

**Comment by anotherus3r** [comment]
Seems like this also affects other websites that fetch data from Reddit through their API when tracking protection is enabled. I'll update the title and description.

**Comment by ekager** [comment]
Closing because I've added this issue to https://github.com/mozilla-mobile/fenix/issues/5392
