### ISSUE TITLE
[Bug] adress bar not scrolling

### ISSUE THREAD

**Issue by FN2187fo** [mozilla-mobile/fenix#4929]
## Steps to reproduce
Enter a search term longer than the address bat itself.

### Expected behavior
The text should scroll and the cursor should stay at the end, so you can always see, what you're typing and where you're typing.

### Actual behavior
The search bar doesn't scroll and you keep seeing only the first word. Also, the cursor seemingly stays there, though it actually moves.

### Device information

* Android device: Moto G5 Android 8.1
* Fenix version: 1.3.1

###Exampel  
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/48321566/63717429-79e8a100-c848-11e9-90e9-2cc285affccf.gif)

**Comment by sblatz** [comment]
I don't think this is an issue anymore. I cannot reproduce this on master on my Galaxy S9. 

QA can you please verify?

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **Nightly Build #13190606 from 11/15** using the following devices:
• Google Pixel 3a XL (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

► Video
![20191115_165917](https://user-images.githubusercontent.com/51314259/68954409-a0293780-07cc-11ea-97c9-3c91e57c619d.gif)
