### ISSUE TITLE
Crash on start using a Galaxy S5

### ISSUE THREAD

**Issue by kbrosnan** [mozilla-mobile/fenix#493]
## Steps to reproduce
* open fenix

### Expected behavior
* app opens

### Actual behavior
* crash

    02-13 14:44:23.234 I/mozac/CrashReporter(11459): Received crash: UncaughtExceptionCrash(throwable=java.lang.RuntimeException: Unable to start activity ComponentInfo{org.mozilla.fenix/org.mozilla.fenix.HomeActivity}: android.view.InflateException: Binary XML file line #19: Binary XML file line #19: Error inflating class fragment)
    02-13 14:44:23.234 I/mozac/CrashReporter(11459): Showing prompt
    02-13 14:44:23.234 I/Timeline(11459): Timeline: Activity_launch_request id:org.mozilla.fenix time:544929783
    02-13 14:44:23.264 D/CustomFrequencyManagerService(  915): releaseDVFSLockLocked : Getting Lock type frm List : DVFS_MIN_LIMIT  frequency : 1958400  uid : 1000  pid : 915  tag : ACTIVITY_RESUME_BOOSTER@10
    02-13 14:44:23.264 D/CustomFrequencyManagerService(  915): acquireDVFSLockLocked : type : DVFS_MIN_LIMIT  frequency : 1958400  uid : 1000  pid : 915  pkgName : ACTIVITY_RESUME_BOOSTER@10
    02-13 14:44:23.264 D/CustomFrequencyManagerService(  915): FrequencyrequestList.getNextCStateDisableRequest, index: 1
    02-13 14:44:23.264 D/ActivityManager(  915): mDVFSHelper.acquire()
    02-13 14:44:23.294 V/WindowManager(  915): addAppToken: AppWindowToken{e4c98b9 token=Token{c92ba80 ActivityRecord{a0ebb03 u0 org.mozilla.fenix/mozilla.components.lib.crash.prompt.CrashReporterActivity t96}}} to stack=1 task=96 at 1
    02-13 14:44:23.294 D/InputDispatcher(  915): Focused application set to: xxxx
    02-13 14:44:23.294 E/AndroidRuntime(11459): FATAL EXCEPTION: main
    02-13 14:44:23.294 E/AndroidRuntime(11459): Process: org.mozilla.fenix, PID: 11459
    02-13 14:44:23.294 E/AndroidRuntime(11459): java.lang.RuntimeException: Unable to start activity ComponentInfo{org.mozilla.fenix/org.mozilla.fenix.HomeActivity}: android.view.InflateException: Binary XML file line #19: Binary XML file line #19: Error inflating class fragment
    02-13 14:44:23.294 E/AndroidRuntime(11459):     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3253)
    02-13 14:44:23.294 E/AndroidRuntime(11459):     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3349)
    02-13 14:44:23.294 E/AndroidRuntime(11459):     at android.app.ActivityThread.access$1100(ActivityThread.java:221)
    02-13 14:44:23.294 E/AndroidRuntime(11459):     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1794)
    02-13 14:44:23.294 E/AndroidRuntime(11459):     at android.os.Handler.dispatchMessage(Handler.java:102)
    02-13 14:44:23.294 E/AndroidRuntime(11459):     at android.os.Looper.loop(Looper.java:158)
    02-13 14:44:23.294 E/AndroidRuntime(11459):     at android.app.ActivityThread.main(ActivityThread.java:7224)
    02-13 14:44:23.294 E/AndroidRuntime(11459):     at java.lang.reflect.Method.invoke(Native Method)
    02-13 14:44:23.294 E/AndroidRuntime(11459):     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
    02-13 14:44:23.294 E/AndroidRuntime(11459):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
    02-13 14:44:23.294 E/AndroidRuntime(11459): Caused by: android.view.InflateException: Binary XML file line #19: Binary XML file line #19: Error inflating class fragment
    02-13 14:44:23.294 E/AndroidRuntime(11459):     at android.view.LayoutInflater.inflate(LayoutInflater.java:551)
    02-13 14:44:23.294 E/AndroidRuntime(11459):     at android.view.LayoutInflater.inflate(LayoutInflater.java:429)
    02-13 14:44:23.294 E/AndroidRuntime(11459):     at android.view.LayoutInflater.inflate(LayoutInflater.java:380)
    02-13 14:44:23.294 E/AndroidRuntime(11459):     at androidx.appcompat.app.AppCompatDelegateImpl.c(:6)
    02-13 14:44:23.294 E/AndroidRuntime(11459):     at androidx.appcompat.app.AppCompatActivity.setContentView(:1)
    02-13 14:44:23.294 E/AndroidRuntime(11459):     at org.mozilla.fenix.HomeActivity.onCreate(:2)
    02-13 14:44:23.294 E/AndroidRuntime(11459):     at android.app.Activity.performCreate(Activity.java:6876)
    02-13 14:44:23.294 E/AndroidRuntime(11459):     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1135)
    02-13 14:44:23.294 E/AndroidRuntime(11459):     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3206)
    02-13 14:44:23.294 E/AndroidRuntime(11459):     ... 9 more
    02-13 14:44:23.294 E/AndroidRuntime(11459): Caused by: android.view.InflateException: Binary XML file line #19: Error inflating class fragment
    02-13 14:44:23.294 E/AndroidRuntime(11459):     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:794)
    02-13 14:44:23.294 E/AndroidRuntime(11459):     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:716)
    02-13 14:44:23.294 E/AndroidRuntime(11459):     at android.view.LayoutInflater.rInflate(LayoutInflater.java:847)
    02-13 14:44:23.294 E/AndroidRuntime(11459):     at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:810)
    02-13 14:44:23.294 E/AndroidRuntime(11459):     at android.view.LayoutInflater.inflate(LayoutInflater.java:527)
    02-13 14:44:23.294 E/AndroidRuntime(11459):     ... 17 more
    02-13 14:44:23.294 E/AndroidRuntime(11459): Caused by: androidx.fragment.app.Fragment$InstantiationException: Unable to instantiate fragment org.mozilla.fenix.home.HomeFragment: calling Fragment constructor caused an exception
    02-13 14:44:23.294 E/AndroidRuntime(11459):     at androidx.fragment.app.Fragment.a(:6)
    02-13 14:44:23.294 E/AndroidRuntime(11459):     at androidx.navigation.fragment.FragmentNavigator.a(:4)
    02-13 14:44:23.294 E/AndroidRuntime(11459):     at androidx.navigation.fragment.FragmentNavigator.a(:10)
    02-13 14:44:23.294 E/AndroidRuntime(11459):     at androidx.navigation.fragment.FragmentNavigator.a(:2)
    02-13 14:44:23.294 E/AndroidRuntime(11459):     at androidx.navigation.NavGraphNavigator.a(:17)
    02-13 14:44:23.294 E/AndroidRuntime(11459):     at androidx.navigation.NavGraphNavigator.a(:2)
    02-13 14:44:23.294 E/AndroidRuntime(11459):     at androidx.navigation.NavController.a(:139)
    02-13 14:44:23.294 E/AndroidRuntime(11459):     at androidx.navigation.NavController.a(:44)
    02-13 14:44:23.294 E/AndroidRuntime(11459):     at androidx.navigation.NavController.b(:21)
    02-13 14:44:23.294 E/AndroidRuntime(11459):     at androidx.navigation.NavController.b(:20)
    02-13 14:44:23.294 E/AndroidRuntime(11459):     at androidx.navigation.fragment.NavHostFragment.c(:13)
    02-13 14:44:23.294 E/AndroidRuntime(11459):     at androidx.fragment.app.Fragment.h(:11)
    02-13 14:44:23.294 E/AndroidRuntime(11459):     at b.m.a.o.a(:212)
    02-13 14:44:23.294 E/AndroidRuntime(11459):     at b.m.a.o.a(:385)
    02-13 14:44:23.294 E/AndroidRuntime(11459):     at b.m.a.o.onCreateView(:30)
    02-13 14:44:23.294 E/AndroidRuntime(11459):     at androidx.fragment.app.FragmentController.a(:3)
    02-13 14:44:23.294 E/AndroidRuntime(11459):     at androidx.fragment.app.FragmentActivity.a(:1)
    02-13 14:44:23.294 E/AndroidRuntime(11459):     at androidx.fragment.app.FragmentActivity.onCreateView(:1)
    02-13 14:44:23.294 E/AndroidRuntime(11459):     at org.mozilla.fenix.HomeActivity.onCreateView(:2)
    02-13 14:44:23.294 E/AndroidRuntime(11459):     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:766)
    02-13 14:44:23.294 E/AndroidRuntime(11459):     ... 21 more
    02-13 14:44:23.294 E/AndroidRuntime(11459): Caused by: java.lang.reflect.InvocationTargetException
    02-13 14:44:23.294 E/AndroidRuntime(11459):     at java.lang.reflect.Constructor.newInstance(Native Method)
    02-13 14:44:23.294 E/AndroidRuntime(11459):     at androidx.fragment.app.Fragment.a(:3)
    02-13 14:44:23.294 E/AndroidRuntime(11459):     ... 40 more
    02-13 14:44:23.294 E/AndroidRuntime(11459): Caused by: java.lang.IncompatibleClassChangeError: Couldn't find org.mozilla.fenix.mvi.ActionBusFactory.<init>[interface androidx.lifecycle.LifecycleOwner]
    02-13 14:44:23.294 E/AndroidRuntime(11459):     at libcore.reflect.AnnotationAccess.indexToMethod(AnnotationAccess.java:608)
    02-13 14:44:23.294 E/AndroidRuntime(11459):     at libcore.reflect.AnnotationAccess.getEnclosingMethodOrConstructor(AnnotationAccess.java:405)
    02-13 14:44:23.294 E/AndroidRuntime(11459):     at java.lang.Class.isLocalClass(Class.java:1339)
    02-13 14:44:23.294 E/AndroidRuntime(11459):     at java.lang.Class.getCanonicalName(Class.java:378)
    02-13 14:44:23.294 E/AndroidRuntime(11459):     at androidx.lifecycle.Lifecycling.a(:24)
    02-13 14:44:23.294 E/AndroidRuntime(11459):     at androidx.lifecycle.Lifecycling.a(:6)
    02-13 14:44:23.294 E/AndroidRuntime(11459):     at androidx.lifecycle.LifecycleRegistry$a.<init>(:2)
    02-13 14:44:23.294 E/AndroidRuntime(11459):     at androidx.lifecycle.LifecycleRegis
    02-13 14:44:23.314 D/RestrictionPolicy(  915): isGoogleCrashReportAllowed : ret=true userId =0

### Device information

* Android device: Galaxy S5
* Fenix version: ?

**Comment by colintheshots** [comment]
This definitely looks like a Proguard issue. It's good to catch these now.

**Comment by pocmo** [comment]
@kbrosnan Was this a Nightly build? Did the crash reporter dialog show up?

**Comment by kbrosnan** [comment]
Yes both the Android crash reporter and the Firefox on appear.

**Comment by ekager** [comment]
@kbrosnan are you still seeing this issue or was it only that day's master?

**Comment by kbrosnan** [comment]
This was happening for several days. This week I it it got fixed. @colintheshots mentioned fixing the top crash which this may have been it.

**Comment by ekager** [comment]
Thanks! :)
