### ISSUE TITLE
[Bug] App build Gradle error resolving symbol StyledTextOutput

### ISSUE THREAD

**Issue by AaronMT** [mozilla-mobile/fenix#4933]
`import org.gradle.internal.logging.text.StyledTextOutput.Style`

https://github.com/mozilla-mobile/fenix/blame/153af588af28a4cdf8b4a232c84219dfdfa7553f/app/build.gradle#L14

Added in https://github.com/mozilla-mobile/fenix/commit/e6487ba6093821237d27dcc11e8d6a56d518622d

CC @sblatz

**Comment by JorgeDLS** [comment]
[There's a bug in the JetBrains issue tracker](https://youtrack.jetbrains.com/issue/IDEA-216640) that could be related to this one.

**Comment by rpappalax** [comment]
I'm seeing the same issue

**Comment by boek** [comment]
Looks like this was fixed on the jetbrains tracker. Is this fixed now @rpappalax @AaronMT ?

**Comment by Anutrix** [comment]
I have this issue.
