### ISSUE TITLE
[Bug] Button "Sales of used items" doesn't work on m.price.com.hk

### ISSUE THREAD

**Issue by softvision-miralobontiu** [mozilla-mobile/fenix#4938]
## Steps to reproduce
1. Go to m.price.com.hk and select a product.
2. Tap on "Second-hand" icon.
3. Tap on the yellow "Sale of used items" button (i.e. https://m.price.com.hk/product.php?p=392583&gp=26&ct=trade).

### Expected behavior
The user should be redirected to a login page.

### Actual behavior
Nothing happens.

### Device information
* Android device: Motorola Moto G6 (Android 8), Nexus 9 tablet (Android 7.1.1)
* Fenix version: 190826 (#12380610)
* Works on Firefox for Android 68.0.2

[logcat.txt](https://github.com/mozilla-mobile/fenix/files/3544705/logcat.txt)

![20190827_Trim](https://user-images.githubusercontent.com/40694158/63748854-d54f7900-c8b2-11e9-897d-2a0ccd7a569d.gif)

**Comment by ekager** [comment]
Does this work with TP off?

**Comment by softvision-miralobontiu** [comment]
On the latest Nightly 190916 (#12591838) the button works with ETP off.
Tested with Sony Xperia Z2 (Android 6.0.1), and Motorola Moto G6 (Android 8).

**Comment by softvision-miralobontiu** [comment]
Still reproducible on 10/4 Nightly build with Xiaomi Mi 8 Lite (Android 9).

When ETP is disabled, buttons work.

**Comment by softvision-miralobontiu** [comment]
This issue is still reproducible on the latest Nightly build from 12/10, on Samsung Galaxy Tab S3 (Android 8).

**Comment by softvision-miralobontiu** [comment]
Reproducible on the 01/21 Nightly build with Google Pixel (Android 10).

**Comment by softvision-miralobontiu** [comment]
Still reproducible on the 3/2 Nightly build with HTC 10 (Android 8).
When ETP is turned OFF, the buttons redirect the user to the login page.

**Comment by softvision-miralobontiu** [comment]
I was not able to reproduce this issue on the 12/29 Nightly build with HTC 10 (Android 8).
I'll close this issue.
