### ISSUE TITLE
[Bug] Sign-in with social media buttons don't work on avito.ru

### ISSUE THREAD

**Issue by softvision-miralobontiu** [mozilla-mobile/fenix#4939]
## Steps to reproduce
1. Go to avito.ru.
2. Select a random product.
3. Select to send a message to the seller through Facebook, Google+, Twitter,, etc.

### Expected behavior
The user should be redirected to sign-in.

### Actual behavior
The buttons don't work. Nothing happens.

### Device information
* Android device: Motorola Moto G6 (Android 8), Huawei P9 Lite (Android 6), Nexus 9 Tablet (Android 7.1.1)
* Fenix version: 190826 (#12380610)

![Screenshot_20190827-112617](https://user-images.githubusercontent.com/40694158/63754515-a8549380-c8bd-11e9-9e5f-b60915233706.png)

**Comment by softvision-miralobontiu** [comment]
The same issue is encountered on wildberries.ru.

**Comment by kumarharsh** [comment]
Sign in/ Sign-up with Facebook is not working in major websites like Quora and Glassdoor either. The Sign in with Facebook button cannot be interacted with. Is Fenix intentionally doing this?

**Comment by ekager** [comment]
Does this work when TP is toggled off? If so could you close this issue and add it to #5392? Thanks!

**Comment by kumarharsh** [comment]
Oh, yeah that fixed it.

There is another issue that embedded Twitter card images don't load on any website, which got fixed by disabling Tracking Protection.

Fenix needs a better way to tell the user about this "bug" - people forget that they have TP on or that TP is the cause for stuff not working.

**Comment by ekager** [comment]
That's why we are starting to collect common site issues in #5392 and allowing users to choose which level of tracking protection they want to use #1749

**Comment by softvision-miralobontiu** [comment]
Tested again with the latest Nightly 190916 (#12591838) with Huawei P9 Lite (Android 6), Sony Xperia Z2 (Android 6.0.1), and Xiaomi Mi 8 Lite (Android 9) and this issue no longer reproduce.
On avito.ru and wildberries.ru, the ETP was enabled, and the social media buttons redirected me to the sign-in page.

**Comment by softvision-miralobontiu** [comment]
I was able to reproduce this issue again on 10/4 Nightly with GV 71.0a1-20191002033852 on Xiaomi Mi 8 Lite (Android 9).

**Comment by ekager** [comment]
@softvision-miralobontiu does it work with ETP turned off?

**Comment by softvision-miralobontiu** [comment]
Not reproducible on the latest Nightly build 1.0.1941 from 10/7 with Xiaomi Mi8 Lite (Android 9).
I was able to sign-in with social media buttons.
I will close this issue.
