### ISSUE TITLE
[Bug] Some buttons from yahoo.com don't work

### ISSUE THREAD

**Issue by softvision-miralobontiu** [mozilla-mobile/fenix#4941]
## Steps to reproduce
1. Go to yahoo.com.
2. Open a random article.
3. Tap on "Show more" or on any social media icon.

### Expected behavior
Tapped buttons should respond.

### Actual behavior
Nothing happens.

### Device information
* Android device: Motorola Moto G6 (Android 8), Huawei P9 Lite (Android 6)
* Fenix version: 190826 (#12380610)

The "Show more" button:
![button](https://user-images.githubusercontent.com/40694158/63767103-56b80300-c8d5-11e9-9fa0-95ad1dfc2503.gif)

The social media icons:
![socialmediabuttons](https://user-images.githubusercontent.com/40694158/63767122-66cfe280-c8d5-11e9-82a4-72adcc8dac4a.gif)

**Comment by ekager** [comment]
Does this happen with TP off? If so could you close this and add it to https://github.com/mozilla-mobile/fenix/issues/5392 ?

**Comment by softvision-miralobontiu** [comment]
Verified on the latest Nightly build 190916 (#12591838) with Motorola Moto G6 (Android 8) and:
- the "Show more" button works with ETP on,
- the social media buttons work with ETP on.
I will close this issue.
