### ISSUE TITLE
Beta/Nightly Logos

### ISSUE THREAD

**Issue by lwa-moz** [mozilla-mobile/fenix#4947]
We need appropriate logo treatments for the new Firefox Preview Beta and Nightly release tracks.

In the short term, the logos can follow the established convention of adding "Beta" and "Nightly" flag graphics to the extant Firefox Preview logo. Documentation on launcher icon specifications can be found here: https://material.io/design/iconography/#specs

In the long term, these logos will need to follow any brand updates. Additional differentiation in color and design could be considered at this later point. For the time being, significant graphic differentiation beyond beta/nightly flags doesn't seem to be a requirement given our goals.

**Comment by lwa-moz** [comment]
@shorlander can you provide an update on your progress?

@liuche is hoping we can release these development channels soon.

**Comment by shorlander** [comment]
Trying to wrap this up today. Getting some clarification on the needed icon assets for the device.

**Comment by shorlander** [comment]
Beta Launcher Assets:
[firefox-preview-beta-launcher.zip](https://github.com/mozilla-mobile/fenix/files/3579368/firefox-preview-beta-launcher.zip)

**Comment by shorlander** [comment]
Nightly Launcher Assets:
[firefox-preview-nightly-launcher.zip](https://github.com/mozilla-mobile/fenix/files/3579526/firefox-preview-nightly-launcher.zip)

**Comment by jplatte** [comment]
The new icon already shows up in the app store + system settings > apps. However, my launcher (KISS launcher) still shows the regular preview icon. Is that expected behaviour?

**Comment by liuche** [comment]
This is ready for QA.

The nightly logo launcher logo has already been in use for a month+ now, so this is mainly to test the beta logo.

Steps for testing would be:
- Build the `geckoBetaFenixBeta` build variant (which is the Beta build)
- Install on Android 21, 23, 26 (to test different SDK versions)
- Verify that the launcher icon is the Firefox Preview Beta logo (which is the same as FP, but with "Beta")

<img width="420" alt="Screen Shot 2019-10-22 at 3 57 45 PM" src="https://user-images.githubusercontent.com/1082253/67419719-12b64700-f582-11e9-97a8-d074533f8b8c.png">

This is only for the launcher icon - any in-app logos will just be the Firefox Preview logo.

**Comment by sv-ohorvath** [comment]
@liuche I think we need signed beta apks in order to test this. Could you please provide us the built apks?

**Comment by sv-ohorvath** [comment]
We've tried all builds types: x86, arm7, arm64 starting with API 21 up to API 29: the logo is correct.
Devices:
• Google Pixel (Android 10)
• Samsung Galaxy Note 8 (Android 9)
• Google Pixel 3a XL (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)
• LG Nexus 5 (Android 6.0.1)
• Xiaomi MiPad 2 (Android 5.1.)
• Samsung Galaxy Tab A6 (A 5.1.1) 
• Xiaomi Mi4i (A 5.0.2)
