### ISSUE TITLE
New Content Description for Tabs Icon

### ISSUE THREAD

**Issue by ekager** [mozilla-mobile/fenix#496]
We changed out the icon in #487, but we should decide if we want to change out the content description because it currently is "Home", which I guess is still accurate but we may want it to read as "Tabs", etc.

**Comment by boek** [comment]
UX will provide strings

**Comment by MeridelW** [comment]
@boek Can you provide me with a visual of this? Thank you.

**Comment by mheubusch** [comment]
Please change the label to Open Tabs

@MeridelW - I grabbed this since I had context.

**Comment by MeridelW** [comment]
@mheubusch Thanks!
