### ISSUE TITLE
Add telemetry for FxA sign up

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#4971]
This is waiting on AS work--we need more instrumentation to cover this event.

Once we have it, we'll want to revert https://github.com/mozilla-mobile/fenix/pull/4970

**Comment by liuche** [comment]
This is to differentiate between the FxA ping for **sign up** vs **sign in**. Could we use UTM parameters? this would need to be built out on the FxA side.

@vesta0 are there bugzilla bugs related to this work? Just so we can track what's going on, or what dependencies we have.

**Comment by vesta0** [comment]
This is pending the Sync Manager work that the Sync team is working on. FYI @jdragojevic

**Comment by grigoryk** [comment]
This is unblocked - a-c exposes a detailed `AuthType` API that helps here.

As I'm integrating webchannel work, I can land this telemetry as well. We can do more than what we had before.

e.g., currently I have:
```
when (authType) {
                // User signed-in into an existing FxA account.
                AuthType.Signin -> context.components.analytics.metrics.track(Event.SyncAuthSignIn)
                // User created a new FxA account.
                AuthType.Signup -> context.components.analytics.metrics.track(Event.SyncAuthSignUp)
                // User paired to an existing account via QR code scanning.
                AuthType.Pairing -> context.components.analytics.metrics.track(Event.SyncAuthPaired)
                // User signed-in into an FxA account shared from another locally installed app (e.g. Fennec).
                AuthType.Shared -> context.components.analytics.metrics.track(Event.SyncAuthFromShared)
                // Account Manager recovered a broken FxA auth state, without direct user involvement.
                AuthType.Recovered -> context.components.analytics.metrics.track(Event.SyncAuthRecovered)
                // User signed-in into an FxA account via unknown means. Exact mechanism identified by the 'action' param.
                is AuthType.OtherExternal -> context.components.analytics.metrics.track(Event.SyncAuthOtherExternal)
            }
```

**Comment by sblatz** [comment]
Thanks @grigoryk! Let me know if you need anything 😄
