### ISSUE TITLE
[Bug] pasting a link in the search bar is hidden

### ISSUE THREAD

**Issue by andreicristianpetcu** [mozilla-mobile/fenix#4972]
## Steps to reproduce
copy a link to clipboard
open a new tab and select the search field
### Expected behavior
![Screenshot_20190828-093625_Firefox_Nightly](https://user-images.githubusercontent.com/922368/63831446-57a17100-c977-11e9-84d1-7453d63d545b.png)

### Actual behavior
![Screenshot_20190828-093617_Firefox_Nightly](https://user-images.githubusercontent.com/922368/63831466-5cfebb80-c977-11e9-93d1-5ba86395b790.png)

### Device information

* Android device: 
![android_version](https://user-images.githubusercontent.com/922368/63831532-7f90d480-c977-11e9-84c9-94d3c40f8024.png)

* Fenix version: nightly and v1.3.1

**Comment by cadeyrn** [comment]
sounds like #4902.
