### ISSUE TITLE
Fennec migration: Inspect/compare default shared pereferences

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/fenix#4974]
> Settings of an application are by default saved in a SharedPreference file. It is possible that Fenix and Fennec may use the same keys with potentially conflicting values. Even in situations where the values are compatible this could cause Fenix to start with “unexpected” default values. This can be mitigated by carefully comparing the saved preferences of Fenix and Fennec (with legacy values). Alternatively this could be extensively tested by QA (partially).

**Comment by Mugurell** [comment]
Guess the Firefox Profile Manager could help here
And if it had backups of both Fennec and Fenix we could extensively test any problematic scenario.

**Comment by pocmo** [comment]
For local builds we could also look at device file explorer and/or print the tree to the log.
