### ISSUE TITLE
Fennec migration: Keep widget on home screen

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/fenix#4978]
> We have added a search widget to Fennec and would like users to keep the widget after upgrade to Fenix. We would need to make sure the Android system can find and access the widget the same way as before in Fenix.

**Comment by pocmo** [comment]
```
       <receiver
            android:name="org.mozilla.gecko.search.SearchWidgetProvider">

            <intent-filter>

                <action
                    android:name="android.appwidget.action.APPWIDGET_UPDATE" />
            </intent-filter>

            <meta-data
                android:name="android.appwidget.provider"
                android:resource="@ref/0x7f130012" />
        </receiver>
```

```
        <activity
            android:theme="@ref/0x7f1100e6"
            android:name="org.mozilla.gecko.search.SearchWidgetConfigurationActivity">

            <intent-filter>

                <action
                    android:name="android.appwidget.action.APPWIDGET_CONFIGURE" />
            </intent-filter>
        </activity>
```

**Comment by pocmo** [comment]
```
<?xml version="1.0" encoding="utf-8"?>

<!-- This Source Code Form is subject to the terms of the Mozilla Public
   - License, v. 2.0. If a copy of the MPL was not distributed with this
   - file, You can obtain one at http://mozilla.org/MPL/2.0/. -->

<appwidget-provider xmlns:android="http://schemas.android.com/apk/res/android"
    android:initialLayout="@layout/widget_search_default_col_layout"
    android:minWidth="360dp"
    android:minHeight="40dp"
    android:minResizeWidth="64dp"
    android:minResizeHeight="40dp"
    android:previewImage="@drawable/search_widget_preview"
    android:resizeMode="horizontal">
</appwidget-provider>
```

**Comment by ebalazs-sv** [comment]
@pocmo I had tested this on Relase, Beta, Nightly migration builds from 01/08 with Google Pixel 3 (Android Q), Samsung Galaxy S8 (Android 9), Huawei Honor 8 (Android 7.0):
- For Release the search widget is kept and functional;
- For Beta and Nightly the search widget bar is kept, but the Fenix icon is not displayed, also this can't be tested because of the start-up crash https://github.com/mozilla-mobile/android-components/issues/5276.

[Screenshot](https://drive.google.com/file/d/1tTU-sSQ4mnOw1zbFUKBb4MQaieQ9Jtl0/view?usp=sharing)

**Comment by ebalazs-sv** [comment]
Verified as fixed on Relase, Beta, Nightly migration builds from 01/10 with Samsung Galaxy S8 (Android 9), Huawei Honor 8 (Android 7.0), Xiaomi Mi4i (Android 5.0.2).
[Screenshot](https://drive.google.com/file/d/1fVOvDPoT4e-Wu9Uxz9LKW-cG3SDq3gZb/view?usp=sharing)
The search widgets are kept and functional. I will move this to Done. Thanks!
