### ISSUE TITLE
Fennec migration: Keep installed PWAs

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/fenix#4979]
Related to #4977

> In Fennec PWAs can be installed to the home screen. Like shortcuts and launcher icons those may disappear or become non-functional unless Fenix offers the same entry points.

**Comment by NotWoods** [comment]
Web App shortcut intents [in Fennec](https://searchfox.org/mozilla-esr68/source/mobile/android/base/java/org/mozilla/gecko/GeckoApplication.java#761):
- Action: `org.mozilla.gecko.WEBAPP`
- Component: `org.mozilla.gecko.LauncherActivity`
- Data: Start URL of website
- Extras:
  - `MANIFEST_PATH`: manifest file path
  - `MANIFEST_URL`: manifest online URL

**Comment by Mugurell** [comment]
@NotWoods I see you've unassigned yourself for this?
Is there any work left to be done that I could continue?

**Comment by NotWoods** [comment]
My work so far is in https://github.com/mozilla-mobile/fenix/pull/7011, which doesn't work fully. This ticket is being handed off to another team member but you're welcome to take a look too.

**Comment by pocmo** [comment]
I'll try to take this over and push it over the finish line. :)

**Comment by LaurentiuApahideanSV** [comment]
I have tested the issue on Firefox Preview Nightly 200207 (Build #20380606) GV: 74.0a1-20200206093813 2/7 and can confirm that PWA's are supported. When the next migration build will be released the issue will be retested in order to verify that PWA's installed in Fennec will be kept and function after migrating to Fenix.

**Comment by LaurentiuApahideanSV** [comment]
Verified as fixed on Migration Build 8: Firefox Preview Nightly (Build #2015722195) GV: 74.0a1-2020020703551 2/10 using Google Pixel XL (Android Q).
