### ISSUE TITLE
Fennec migration: Clarify if Gecko profile will be re-used

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/fenix#4982]
It is unclear whether the Gecko profile will be re-used after paving over Fennec. This may affect whether we continue to use data like:

- Cookies
- Website Cache
- about:config flags (We were consider nuking them since there's an endless combination of configurations that we may not be able to support correctly).

**Comment by snorp** [comment]
My gut feeling on this is that reusing the profile **should** be ok, with the exception of prefs. We should remove the prefs.js file in the profile directory.

**Comment by ebalazs-sv** [comment]
Hi!
I verified this on Fenix Nightly 191127 GV 71, with Pixel 2 (Android 9), Samsung Galaxy S8 (Android 9), Huawei Honor 8 (Android 7.0), Nexus 6P (Android 8.1.0), Xiaomi Mi Pad 2 (Android 5.1), ARM, ARM64 and x86 devices.

_For Cookies:_
- The items from the sportsdirect.com cart are available after the migration.
- The user is logged in on facebook.com after the migration.

_For Website Cache:_

In about:cache different values are available after the migration, for example:
**disk values**
- on Fennec  832 -> on Fenix 654
- on Fennec  530 -> on Fenix 409

**memory values**
- on Fennec 3 -> on Fenix 0
- on Fennec 5 -> on Fenix 0

@pocmo Is this behavior for Website Cache expected? Do you have other suggestion for testing the Cookies, Website Cache migration? The about:config is not available on these builds. Thanks!

**Comment by pocmo** [comment]
I assume this is fine. @snorp any concerns?

**Comment by ebalazs-sv** [comment]
Verified as fixed on today's Release, Beta, Nightly migration build 12/16 with Huawei Honor 8 (Android 7.0) the scenarios from the previous comment.
I will move this to Done.
