### ISSUE TITLE
Fennec migration: Keep installed add-ons

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/fenix#4983]
This depends on the add-on strategy. If we'll support (some) add-ons in Fenix then we may want to keep those (or enable those) when replacing Fennec.

**Comment by creesch** [comment]
There is a related issue for this. #574

**Comment by serovar** [comment]
> (some) add-ons

Just to be clear, are you referring to themes not being supported (since they are add-ons too) or also to extensions that are actually compatible with Fennec?

**Comment by pocmo** [comment]
See this issue as a placeholder meaning "If we replace Fennec with Fenix then think about how to deal with already installed add-ons based on whatever state add-on support in Fenix will have at that point".

**Comment by pocmo** [comment]
After talking to snorp and agi the current recommendation is to disable add-ons that are not supported (yet) during the migration phase. Supported add-ons can remain enabled to keep associated add-on data (e.g. custom settings in uBlock Origin).
Further more it would be up to the GV team to either provide the add-on management API in time (so that we can disable those add-ons in the migration phase) or disable those add-ons internally on startup.

**Comment by grigoryk** [comment]
This landed now.

**Comment by ebalazs-sv** [comment]
Verified as fixed on Nightly migration build 7 and build 8 with Google Pixel XL (Android Q) - ARM64, Samsung Galaxy Note 9 (Android 9) - ARM64, Nexus 6P (Android 8.1.0) - ARM, Sony Xperia Z5 Lite (Android 7) - ARM, LG K4 (Android 6.0.1) - ARM, Xiaomi Mi Pad 2 (Android 5.1) - x86 architecture.
The installed add-ons are kept. uBlock Origin is supported and the rest of the add-ons, are in the "Not yet supported" list.
I will move this to Done. Thanks!
