### ISSUE TITLE
[Bug] Cannot share link from reddit.com

### ISSUE THREAD

**Issue by softvision-miralobontiu** [mozilla-mobile/fenix#4984]
## Steps to reproduce
1. Go to reddit.com and sign in with valid credentials.
2. Open an article and select "Share".

### Expected behavior
When the pop-up is displayed with the "Copy link" button the user should be able to proceed by tapping on it.

### Actual behavior
The pop-up is displayed, but the "Copy link" button is inactive. Only X works from the pop-up.

### Device information
* Android device: Motorola Moto G6 (Android 8), Huawei P9 Lite (Android 6)
* Fenix version: 190828 (#12400613)

[logcat.txt](https://github.com/mozilla-mobile/fenix/files/3550133/logcat.txt)

![20190828](https://user-images.githubusercontent.com/40694158/63843501-246adc00-c98f-11e9-8335-638d97012a15.gif)

**Comment by ekager** [comment]
This seems to work with TP turned off

**Comment by softvision-miralobontiu** [comment]
Yes, when ETP is OFF I can share the article.
Tested again with 10/4 Nightly build, GV 71.0a1-20191002033852

**Comment by ekager** [comment]
Added this to the list of TP issues #5392. Closing
