### ISSUE TITLE
Enable users to switch search engine directly on page element

### ISSUE THREAD

**Issue by bbinto** [mozilla-mobile/fenix#499]
### Why/User Benefit/User Problem
This is a recommendation coming out of milestone 1 user testing

### What / Requirements
Quick switch of search engine on search icon on homescreen

**Comment by shorlander** [comment]
The current proposed solution for this task are the search shortcuts after you tap on the search field. I think we should pursue that first and revisit other solutions if necessary.

**Comment by lime124** [comment]
I believe this has been solved by the shortcuts work. Please reopen if I've misunderstood. #112 Shortcuts.
