### ISSUE TITLE
Directly access a website when it shows up in suggestions

### ISSUE THREAD

**Issue by julienw** [mozilla-mobile/fenix#4990]
### Why/User Benefit/User Problem

The goal is to quickly access a website that's not been visited yet. The user knows how the website's domain approximately look like but not completely. Or they know it but typing it completely is a bit painful on a mobile keyboard.
The goal is to access it in one click instead of more clicks.

### What/Requirements

The user types the start of a website's domain name, and the search suggestions proposes the full domain name. Clicking it should access the domain directly instead of going to the search engine.

This is the behavior of old Firefox.

### Acceptance Criteria (how do I know when I’m done?)

Here is a STR with duckduckgo:
1. type "hattrick"
=> duckduckgo proposes "hattrick.org"
2. tap "hattrick.org"
=> Firefox Preview goes directly to "hattrick.org". Instead of searching on duckduckgo.com.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-13205)

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807751

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
