### ISSUE TITLE
[Bug]Multi-selected bookmarks are restored after deletion

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#4991]
## Prerequisites
Have two bookmarks saved

## Steps to reproduce
1. Navigate to "Your Library"
2. Tap on "Bookmarks"
3. Tap the fav icon of the two listed bookmarks (the multi select bar is activated)
4. Tap the upper right 3dot button from the multi-select action bar 
5. Tap delete
6. While the undo snackbar is displayed, tap the device back button

### Expected behavior
Both selected bookmarks should be deleted

### Actual behavior
One out of the two bookmarks is deleted, the other one remains in the list

### Device information

* Android device: Google Pixel 3a (Android 9)
* Fenix version: Nightly Build #12400613 from 28/8

### Notes
Quite similar with #3967 the difference is the multi-select feature.
► Video
![20190828_155514](https://user-images.githubusercontent.com/51314259/63859300-c8647f80-c9af-11e9-9f3b-d4b453512c52.gif)

**Comment by sv-ohorvath** [comment]
See also: https://github.com/mozilla-mobile/fenix/issues/4993 (dupes?)

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on Nightly Build #12700627 from 27/9 using the following devices:
• Google Pixel 3a (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

►Video
![20190927_145700](https://user-images.githubusercontent.com/51314259/65767836-be14dd00-e137-11e9-9b8c-df6804834454.gif)
