### ISSUE TITLE
[Bug] accessing passwords for a HTTP Basic Authentication works very badly

### ISSUE THREAD

**Issue by julienw** [mozilla-mobile/fenix#4992]
## Steps to reproduce

I use passwords saved in Firefox, and have installed Lockwise on Android.

1. Access a website protected by basic auth, where passwords are saved in Firefox. In my personal example, this is https://everlong.org/calendrier/login.php

### Expected behavior

I get an easy access to my saved password. On Desktop and old Firefox, it's autofilled.

### Actual behavior

1. I get the authentication popup.
2. I click once in the "login" part
3. I click on "unlock lockwise".
4. I enter the lockwise code
5. then only passwords of the mozilla.org domain are shown. I can search for "everlong" to find my passwords.

For the step 5, this seems related to #4205. For 1 to 4, this may be a problem in lockwise where we need too many steps to access the saved passwords.
That said, the general UX is a big regression compared to Firefox Android, so I believe the Fenix team should own this.

### Device information

* Android device: Samsung S10E (Android 9)
* Fenix version: 1.3.1

**Comment by ekager** [comment]
Closing for #4205

**Comment by julienw** [comment]
hey @ekager, this issue was also related to the fact that I need a lot of clicks compared to Android, even for cases where it works. But maybe this is more a Lockwise issue (especially the fact it doesn't stay unlocked for a long time) ?

**Comment by ekager** [comment]
Ah okay! We can reopen. 
I will say if Lockwise does recognize the site then I believe it fills with less steps. The searching is if it doesn't have a match. 
Fenix autofill will also be available in the next few months and will (to start) just fill without input.

**Comment by yookoala** [comment]
I don't think it work at all. I don't get any password hint or dialog for a site with username / password I stored in Password Manager. (Of course I'm talking about HTTP Basic Authentication)

I'm using Fenix nightly 200214 (Build #2015722947) 32.0.0.

It works in Fennec. Please make it work on Fenix.

**Comment by julienw** [comment]
I think this works for me now, but of course you need lockwise.

**Comment by ekager** [comment]
@yookoala is your comment about the internal password manager or Lockwise?

**Comment by yookoala** [comment]
Password manager.

**Comment by ekager** [comment]
Okay, I'm going to close this and reopen #8642
