### ISSUE TITLE
[Bug]Multi-selected bookmarks folders are restored after deletion

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#4993]
## Prerequisites
Have three bookmarks **folders** saved

## Steps to reproduce
1. Navigate to "Your Library"
2. Tap on "Bookmarks"
3. Tap the fav icon of the listed bookmarks **folders** (the multi select bar is activated)
4. Tap the upper right 3dot button from the multi-select action bar 
5. Tap delete
6. While the undo snackbar is displayed, tap the device back button

### Expected behavior
The selected  bookmarks **folders** should be deleted

### Actual behavior
The **1st** created **bookmark folder** is deleted, the other two remain in the list

### Device information

* Android device: Google Pixel 3a (Android 9)
* Fenix version: Nightly Build #12400613 from 28/8

### Notes
Similar to #4991 

► Video
![20190828_155646](https://user-images.githubusercontent.com/51314259/63859956-f7c7bc00-c9b0-11e9-95ec-5717dfa7a597.gif)

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on Nightly Build #12700627 from 27/9 using the following devices:
• Google Pixel 3a (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

►Video
![20190927_150414](https://user-images.githubusercontent.com/51314259/65768110-ae49c880-e138-11e9-97c4-89ff5e0b9771.gif)

**Comment by softvision-miralobontiu** [comment]
I will reopen this issue since I was able to reproduce it again with the latest Nightly 10/9 with Samsung Galaxy Note 8 (Android 9), Samsung Galaxy tab A6 (Android 5.1).
