### ISSUE TITLE
[Bug]Crash when trying to create a new Bookmarks folder in the "Desktop bookmarks"

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#4994]
## Prerequisites
User should be sign in to FxA

## Steps to reproduce
1. Navigate to "Your Library"
2. Tap on "Bookmarks"
3. Tap on "Desktop bookmarks"
4. Tap on the "add folder" sign from the action bar![Webp net-resizeimage](https://user-images.githubusercontent.com/51314259/63861609-e03e0280-c9b3-11e9-8243-ed6370c14f18.jpg)
5. Choose a name and tap on the upper right check sign

### Expected behavior
The desired folder can be added to the "Desktop bookmarks"

### Actual behavior
Crash

### Device information

* Android device: Google Pixel 3a (Android 9)
* Fenix version:  Nightly Build #12400613 from 28/8

### Notes
[Logcat](https://github.com/mozilla-mobile/fenix/files/3551236/Crash.txt)

► Video
![20190828_1600521](https://user-images.githubusercontent.com/51314259/63862008-99044180-c9b4-11e9-926e-53d9c5961bd0.gif)

**Comment by cfsnsalazar** [comment]
I would like to try this one out

**Comment by hackertronix** [comment]
Since there have been no updates from @cfsnsalazar can I take this up?

**Comment by cfsnsalazar** [comment]
@hackertronix go ahead

**Comment by hackertronix** [comment]
Thanks @cfsnsalazar! :)

**Comment by liuche** [comment]
Any update @hackertronix, or can we open this bug up for someone else to work on?

**Comment by liuche** [comment]
unassigning for inactivity

**Comment by AfzalivE** [comment]
It looks like there shouldn't be an option to create a new folder at that place. 

Desktop Firefox doesn't have any option to create a folder or a new bookmark at that level (All Bookmarks).

Even here, there's a comment about throwing this exact error:
https://github.com/mozilla/application-services/blob/master/components/places/android/src/main/java/mozilla/appservices/places/Bookmarks.kt#L293 

Any thoughts?

**Comment by hackertronix** [comment]
Hey @liuche sorry about not being able to respond I was off for a while due to work. 

@AfzalivE is correct I had discussed the same a while back with @ekager and yes users should not be able to add folders to the root.

**Comment by AfzalivE** [comment]
@hackertronix if you don't have a fix ready to go, would you mind if I take a stab at this?

**Comment by hackertronix** [comment]
@AfzalivE, by all means, please go ahead :)

**Comment by ekager** [comment]
Reopening for QA!

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **Nightly Build #13500610 from 12/16** using the following devices:
• Google Pixel 3a (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• OnePlus (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

► Video
![20191216_105129](https://user-images.githubusercontent.com/51314259/70892963-d1c33780-1ff2-11ea-83e1-1ba2e353238d.gif)
