### ISSUE TITLE
[Bug]Share button from the 3dot button overlay doesn't work in custom tabs 

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#4997]
## Notes
Set Fenix as your default browser

## Steps to reproduce
1. Open Gmail
2. Open a link to a website
3. After the custom tab is loaded tap on the upper right 3dot button
4. Tap on the "Share" button from the overlay

### Expected behavior
Sharing options should pop up and you should be able share the custom tab 

### Actual behavior
Nothing happens

### Device information

* Android device: Google Pixel 3a (Android 9)
* Fenix version: Build #12400613 from 28/8

### Notes
► Video 
![20190828_174915](https://user-images.githubusercontent.com/51314259/63868965-16817f00-c9c0-11e9-84ac-f08cbf164225.gif)

**Comment by ekager** [comment]
I think this should be pulled into the current sprint @vesta0

**Comment by vesta0** [comment]
@ekager I agree. @bifleming can we see if this can be fixed before the code freeze?

**Comment by ekager** [comment]
Talked to @mcarare about this issue and they are on it!

**Comment by AndiAJ** [comment]
Hi, **verfied as fixed** on Fenix **Nighlty Build #12470611 from 4/9**  using the following devices:
• Google Pixel 3a XL (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• OnePlus A3 (Android 6.0.1)

►Video
![20190904_115130](https://user-images.githubusercontent.com/51314259/64240821-41615b00-cf0b-11e9-82ad-dcff97cc3016.gif)

**Comment by AndiAJ** [comment]
Hi, just as an FYI I've bumped in this issue while testing **RC 1.4.1** on a Samsung Galaxy Tab A (Android 9).
