### ISSUE TITLE
[Bug] Text fields on Slack invoke autofill

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/fenix#5006]
### Steps to reproduce
1. (Be a masocist and) open slack on mobile web.
2. Turn on desktop mode to allow Slack usage in the mobile browser.
3. Ensure cursor is not focused on text field.
4. Go to app switcher.
5. Focus back to Fenix and immediately click on text field.
6. Observe.

### Expected
1. You can enter text immediately.

### Actual
1. Password autofill is invoked every time and doesn't let you type so you turn to filling bugs instead.

**Comment by cpeterso** [comment]
I filed a GV bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1585869
