### ISSUE TITLE
[Bug] + button moves when closing last tab in tabs tray, making it awkward to open new tab

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#5015]
## Steps to reproduce
- Open a tab
- Close all open tabs by pressing the "x" button
- Attempt to hit the + button to open a new tab

### Expected behavior
The + button stays in the same place

### Actual behavior
The + button moves to the right. Since I saw the + button before, I started to move towards it to open a new tab and I end up hitting nothing.

### Device information

* Android device: Pixel 2
* Fenix version: Nightly 190829

**Comment by boek** [comment]
Functionality removed with #1063
