### ISSUE TITLE
Add bookmark through context menu

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/fenix#5016]
## User Story
- As a user, I want to be able to long press on a link on a website, and have the option to bookmark that link, so I can quickly bookmark a page and go back to it later without having to load the page

<Fennec Parity: this is not a common use case but it is used frequently by Fennec power users>

### Requirements
- [ ] Add "add a bookmark" to the link context menu (@jpfaller to provide exact strings)
- [ ] Add a telemetry probe to measure taps on "add a bookmark" through the context menu

### Acceptance Criteria
- I can add a bookmark through the context menu.

Please use Fennec UI as reference:

![1587772076](https://user-images.githubusercontent.com/42752644/65937156-f3962080-e3ec-11e9-8ac4-ae1ca87ffd6d.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-13219)

**Comment by vesta0** [comment]
@lime124 I propose that we skip UX for this issue and refer to the Fennec UI instead.

**Comment by vesta0** [comment]
@liuche this needs to be re-sized as I added telemetry to the requirements.

**Comment by lime124** [comment]
@jpfaller can we reuse bookmark link from fennec for our context menu? thanks!

**Comment by jpfaller** [comment]
Yep, I think it can be re-used.

**Comment by liuche** [comment]
adding triage label to re-size, and this now has additional telemetry requirements.

**Comment by vesta0** [comment]
We resized this from E2 to E5 during backlog grooming today.

**Comment by vesta0** [comment]
@lime124 should we also add a "add to collection" option to this menu? I am thinking maybe that is in fact more useful/relevant. I am thinking the only reason a user would bookmark a link they haven't opened is to have the option to come back to it later without interrupting their browsing activity.

**Comment by lime124** [comment]
Adding group triage -  does this have any dependencies? can a contributor pick it up?

@vesta0 Can we open that in a separate issue? I'd like to keep the scope on this one small/contained since it's ready for eng  - there may be some additional design decisions on the flow that need to be made.

**Comment by sblatz** [comment]
This is AC work we can do as Fenix engineers if we'd like.

Let's modify the `ContextMenuCandidate.kt` file

**Comment by jackyzy823** [comment]
The android part is not so hard to complete , see https://github.com/jackyzy823/android-components/tree/copy-link-text and 
https://github.com/jackyzy823/fenix/tree/context-menu-bookmark

The question is same as https://github.com/mozilla-mobile/fenix/issues/16582#issuecomment-1116284575

You can not get bookmark's link text (aka title) from `geckoview`


Ref: fennec's implment:
https://hg.mozilla.org/releases/mozilla-esr68/file/tip/mobile/android/chrome/content/browser.js#l1165

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812724

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
