### ISSUE TITLE
[Bug] Fenix appears in own "Open in app"

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#5017]
## Steps to reproduce
- Go to a page with "open in app" (like youtube.com)
- Click "open in app" (in quick action bar)

### Expected behavior
App opens in only relevant app (YouTube) or displays list of relevant apps without Fenix

### Actual behavior
Displays list of relevant apps, including Fenix (I only have one Fenix installed)

### Device information

* Android device: Pixel 2
* Fenix version: Nightly 190829

**Comment by liuche** [comment]
Think this has been fixed.
