### ISSUE TITLE
[Bug] Cannot get search engine selection back after typing

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#5018]
## Steps to reproduce
- Go to home screen
- Click URL bar (note the search engine selection)
- Type
- Backspace all typed text

### Expected behavior
Search engine selection returns

### Actual behavior
A blank page in the search results section.

By hitting back and clicking the URL bar again, the search engine selection returns.

### Device information

* Android device: Pixel 2
* Fenix version: Nightly 190829

**Comment by boek** [comment]
This has been verified as fixed
