### ISSUE TITLE
[Bug] Fix bug 1522829

### ISSUE THREAD

**Issue by kbrosnan** [mozilla-mobile/fenix#5019]
https://bugzilla.mozilla.org/show_bug.cgi?id=1522829

**Comment by liuche** [comment]
Talk to @csadilek before you pick this up.

**Comment by csadilek** [comment]
Patch is up in A-C. Once it lands, there should be no work required in Fenix.

**Comment by csadilek** [comment]
Latest A-C 18.0.0-SNAPSHOTs went out and have the fix. So, marking this as ready for QA.

**Comment by liuche** [comment]
I've added Ioana Chiorean in the bugzilla cc list because I couldn't find the bugzilla emails/accounts for @AndiAJ or @softvision-miralobontiu on phonebook. You can ping her to give access to that bug.

**Comment by ioana-chiorean** [comment]
CC'ed them in the bug. 👍

**Comment by softvision-miralobontiu** [comment]
Hi all!
I investigated the [1522829 bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1522829) from Bugzilla, but couldn't identify what exactly I need to test. The link from the STR is no longer available.
Please let me know some other STR to verify this issue.
Thanks!

**Comment by sv-ohorvath** [comment]
> Hi all!
> I investigated the [1522829 bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1522829) from Bugzilla, but couldn't identify what exactly I need to test. The link from the STR is no longer available.
> @kbrosnan please let me know some other STR to verify this issue.
> Thanks!

@csadilek Could you maybe help Mira with some STR, please?

**Comment by csadilek** [comment]
@sv-ohorvath OK, I will send you an email with instructions on how to test this. Thanks to @vladikoff we now have test endpoints, which I will share with you.

**Comment by softvision-miralobontiu** [comment]
Verified as fixed with the latest 10/31 Nightly build (#13040608) with OnePlus 5T (Android 9), and HTC Desire 820 (Android 6.0.1).
