### ISSUE TITLE
[Telemetry] What's New

### ISSUE THREAD

**Issue by vrudesai** [mozilla-mobile/fenix#5021]
Owner: Product Manager

#### Description & Product Manager / Data Scientist User Story
- As a product owner, I want to know if people tap on the What's New option under the triple dot menu

#### Hypothesis
- We believe this feature is useful to users, and successful when at least 30% of users tap on the What's New button

#### Why does Mozilla need to answer these questions? Are there benefits for users? Do we need this information to address product or business requirements?

- This feature provide users with transparency regarding new updates and what is included within the updates such as bugs, features, UI enhancements, etc.

#### What probes (suggested, if applicable)
Number of times What's New is tapped on

### Acceptance Criteria (Added by PM)
- Event pings can be queried via Amplitude
- We are sending telemetry events for the actions listed in the requirements
- We have documented the telemetry

**Comment by vesta0** [comment]
@sblatz thank you :)

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on Fenix **2.0.0-rc.2** using a Samsung Galaxy Tab A (Android 9).

[Logcat](https://github.com/mozilla-mobile/fenix/files/3609041/new.txt)
[Glean dashboard](https://debug-ping-preview.firebaseapp.com/pings/aj-130901)
