### ISSUE TITLE
"Clear permissions" pop-up dialog should have the "Fenix" UI specifics

### ISSUE THREAD

**Issue by softvision-miralobontiu** [mozilla-mobile/fenix#5030]
### Why/User Benefit/User Problem
I suggest the "Clear permissions" pop-up dialog have the same specifics like the rest of the pop-ups: OK should be purple.

![Screenshot_20190830-112550](https://user-images.githubusercontent.com/40694158/64005471-2a8cc400-cb19-11e9-8e62-b1a9619cca0e.png)

**Comment by NotWoods** [comment]
UX: Please confirm if the "CANCEL"/"OK" button color should be changed to match other dialogs

**Comment by lime124** [comment]
@softvision-miralobontiu @NotWoods are you asking about the button (what i hear is background white color) or the text color?

if text color - yes please update to match other dialogues.
if background button color - can you help me find examples of this? i'm not finding what you are seeing.

thanks!

**Comment by softvision-miralobontiu** [comment]
@lime124 I was referring only to the text color.
Thanks!

**Comment by lime124** [comment]
please update to match. thanks!

**Comment by ekager** [comment]
Reopening for QA

**Comment by sv-ohorvath** [comment]
Verified as fixed on Nightly 10/21
