### ISSUE TITLE
[Bug] App crashes when editing a bookmark

### ISSUE THREAD

**Issue by softvision-miralobontiu** [mozilla-mobile/fenix#5031]
## Steps to reproduce
1. Open a webpage.
2. Bookmark it and tap on Edit.

### Expected behavior
The app doesn't crash.

### Actual behavior
Crash!

### Device information
* Android device: Nokia 6 (Android 7.1.1), Samsung Galaxy S8 (Android 9)
* Fenix version: 8/30 Nightly build
* Crashes even when accessing Library - Bookmarks

[logcat.txt](https://github.com/mozilla-mobile/fenix/files/3559021/logcat.txt)

**Comment by softvision-miralobontiu** [comment]
The logcat for the crash when accessing Library - Bookmarks is [logcat1.txt](https://github.com/mozilla-mobile/fenix/files/3559056/logcat1.txt)

**Comment by colintheshots** [comment]
Related to #5055 and the fix is in the same PR.

**Comment by AndiAJ** [comment]
Hi, verified as fixed on **Fenix 1.4.0-rc.1** using a Google Pixel 3a XL (Android 9).
