### ISSUE TITLE
[Bug] Opening a private tab - "Switch" - doesn't take the user to private tabs

### ISSUE THREAD

**Issue by softvision-miralobontiu** [mozilla-mobile/fenix#5033]
## Steps to reproduce
1. Open a page in normal browsing.
2. Long-tap a hyperlinked text and select to open it in a private tab.
3. When the pop-up message is displayed "New private tab opened SWITCH" select to switch.

### Expected behavior
The private tab should be displayed.

### Actual behavior
The page selected to be opened in private tab is opened in normal browsing, replacing the previous page. In private browsing, the page selected is also opened.

### Device information
* Android device: Nokia 6 (Android 7.1.1), Samsung Galaxy S8 (Android 9)
* Fenix version: 8/30 Nightly build @6:12 AM

[logcat.txt](https://github.com/mozilla-mobile/fenix/files/3559612/logcat.txt)

![20190830_135915](https://user-images.githubusercontent.com/40694158/64016157-e9071380-cb2e-11e9-9ba9-5125c18b4674.gif)

**Comment by sv-ohorvath** [comment]
It looks like the opened tabs lists are mixed between browsing modes: PB tabs are shown in normal browsing and vice-versa.

**Comment by abodea** [comment]
Verified as fixed on the latest **Nightly** build from **9/9** using: **Samsung Galaxy S10+(Android 9), Samsung Galaxy S8+(Android 8), Samsung Galaxy S7(Android 7), OnePLus (Android 6), LG Nexus 4(Android 5).**
