### ISSUE TITLE
[Bug] Custom tab is not working on Nokia 6 (Android 7.1.1)

### ISSUE THREAD

**Issue by softvision-miralobontiu** [mozilla-mobile/fenix#5034]
## Steps to reproduce
1. Set Firefox Preview as the default browser.
2. Go to the Gmail app and tap on a link.

### Expected behavior
The tapped link should open in custom tab.

### Actual behavior
The tapped link opens in Firefox Preview app.

### Device information
* Android device: Nokia 6 (Android 7.1.1)
* Fenix version: 8/30 Nightly build
* Not reproducible on Samsung Galaxy S8 (Android 9)

[logcat.txt](https://github.com/mozilla-mobile/fenix/files/3559924/logcat.txt)

![20190830_154354](https://user-images.githubusercontent.com/40694158/64022176-4fdff900-cb3e-11e9-86d4-d7d3f19b7460.gif)

**Comment by jonalmeida** [comment]
@softvision-miralobontiu could you re-test to see if this is still happening? The linked issue is no longer reproducible any more, so I suspect this one is the same.

**Comment by sv-ohorvath** [comment]
@jonalmeida Works ok now on this device. Thanks!
