### ISSUE TITLE
Double tapping open tab indicator should switch between recent tabs

### ISSUE THREAD

**Issue by ARoomWithAMoose** [mozilla-mobile/fenix#504]
In Android 7.0, Google introduced a feature to rapidly switch between the most recently used apps by simply double tapping on the recent apps (square) menu.

With the reference browser moving the UI to the bottom of the screen, I instinctively found myself trying to do this with the open tabs indicator.

It seems that this would greatly accelerate tab switching and, at least for me, comes naturally.

**Comment by boek** [comment]
#176
