### ISSUE TITLE
[Bug] Custom Tab does not restore itself when recreated

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/fenix#5041]
## Steps to reproduce
1. (Optional for easy reproducibility) Set Developer options > Background process limit to 'No background processes'.
2. Open a custom tab (and don't close it at the next step).
3. Do other things, use other memory-intensive apps.
4. Return to the custom tab.

### Expected behavior
1. The custom tab is loaded (or it shows https://github.com/mozilla-mobile/fenix/issues/2383)

### Actual behavior
1. The custom tab shows a completely blank page with a greyed out section on the bottom where the BrowserToolbar was.

### Device information

* Android device: Android 9 (Pixel 2)
* Fenix version: 9b633f7f (master)

> 1.0.1935 (Build #1)
> 📦: 10.0.1, a573b4116
> 🦎: 69.0-20190824140027

**Comment by jonalmeida** [comment]
We have a fix for #2383 but I'm unable to verify if it works because of this other bug. The fix I'm trying to test: https://github.com/mozilla-mobile/reference-browser/pull/894

See this a-c issue for technical history of it: https://github.com/mozilla-mobile/android-components/issues/3773

This is also no related to #2383 since the Custom Tabs code never gets invoked when returning to the Custom Tab, so it seems to be something else unrelated to the lifecycle of the app.

**Comment by softvision-miralobontiu** [comment]
Verified on the latest Nightly build from 2/24, and, with:
- Samsung Galaxy Note 8 (Android 9), Nokia 6 (Android 7.1.1), Sony Xperia Z5 Premium (Android 7.1.1) - I could not reproduce the issue,
- however, with Google Pixel (Android 10), after step 4, the custom tab showed a completely blank page. I've opened a custom tab in gmail, minimized it, opened Reddit, went back to gmail.

Please see the attached logcat from Google Pixel:

[logcat.txt](https://github.com/mozilla-mobile/fenix/files/4245238/logcat.txt)

I'll remove the qa-needed label for now.
