### ISSUE TITLE
Starting a Custom Tab from cold-boot starts the world

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/fenix#5045]
When you start a custom tab[1], this also invokes your FxA account/sync, etc. which doesn't really need to be started since we just want to load the browser engine and auto-fill support (at most).

We should consider how to lazy/not load the rust components when in a Custom Tab.

This might mean making rust component services aware of the `sessionId` so that we can differ the loading to later.

[1]: While I refer to custom tabs, this affects TWAs and PWAs as well.

**Comment by jonalmeida** [comment]
Documenting some offline conversations with @colintheshots and @grigoryk :
 - Lazy loading is something we should try to do more often in general, although this can be harder as code is intertwined.
    - "We may get away with not initializing some native objects (e.g. FirefoxAccount rust one), but we're still loading the so files".
 - Having the megazord complicates what gets accessed.
 - Maybe anything that accesses a native object should be wrapped in a lazy initializer?
 - Today in Custom Tabs/TWAs/PWAs, we don't need to do any of this since we don't want those features. Tomorrow we might, so we could potentially differ the bigger problem to later and figure out the easy version: don't load native code in a CT/TWA/PWA.

**Comment by hawkinsw** [comment]
@jonalmeida Talk to me about this tomorrow? I'd love to hear more and see if there is something that I can do to help.
