### ISSUE TITLE
Customize the name of a shortcut

### ISSUE THREAD

**Issue by NotWoods** [mozilla-mobile/fenix#5047]
### Why/User Benefit/User Problem
Shortcuts and PWAs are similar but have some distinctions. 

- PWAs should run offline and must include a Web App Manifest. Their name is set by the manifest. They also have adaptive icons when pinned.
- Shortcuts are like a bookmark but on the home screen. Their name is based on the page title but could be editable, just like a bookmark.

### What/Requirements
-I can choose what the shortcut will be called ([InVision](https://mozilla.invisionapp.com/share/M4SBYCLJPQG#/screens/381294676_Add_To_Home_Screen_Dialog))

### Acceptance Criteria (how do I know when I’m done?)
Shortcuts can have custom names

**Comment by liuche** [comment]
@apbitner I think we could use some UX feedback here.

How should we differentiate between PWAs (with fixed names) vs homescreen shortctus to users?

**Comment by apbitner** [comment]
Here's what I have in my PWA designs, so it'd be a different dialog - https://mozilla.invisionapp.com/share/RGSCJEGJM8T#/366942530_Screens_-_PWA_-_Android_Add

**Comment by NotWoods** [comment]
Since that screen is displayed by the system, it would also appear for shortcuts. Users would see two dialogs: entering the name, then pinning the shortcut.

**Comment by apbitner** [comment]
Regular site shortcuts will have the custom renaming dialog followed by the system dialog. And then PWA's will just have the system dialog.

**Comment by liuche** [comment]
Okay, so it sounds like we'll just accept the confusion a user might encounter if they can't tell what situations they see a rename dialog, vs not.

**Comment by liuche** [comment]
If we want to turn off the feature, it'd be an E2.

UX wants the feature to ship complete, so the two options are:
- Turn off the feature, OR
- Fix this bug
