### ISSUE TITLE
Need a way to disable the Quick Action Sheet for visual metrics performance tests

### ISSUE THREAD

**Issue by acreskeyMoz** [mozilla-mobile/fenix#5048]
### Why/User Benefit/User Problem
The Quick Action Sheet menu, with the Share / Bookmark items appears automatically during a pageload.
Related to https://github.com/mozilla-mobile/fenix/issues/4308
This will cause problems for visual metrics performance tests since they effectively measure the time for the rendering to settle.

### What/Requirements
Some mechanism to disable the auto display of the Quick Action Sheet (intent argument?) for performance testing.

### Acceptance Criteria (how do I know when I’m done?)
When Fenix can be launched in a to-be-determined manner and no Quick Action Sheet will appear unless the user has clicked on it.

**Comment by colintheshots** [comment]
One may set a shared preference to prevent the Quick Action Sheet from bouncing automatically, as it does on the first few runs.

One should be able to ```
appContext.getSharedPreferences("fenix_preferences", MODE_PRIVATE).edit().putInt(
            appContext.getPreferenceKey(R.string.pref_key_bounce_quick_action),
            100 // or any large number really
        ).apply()
````

**Comment by ncalexan** [comment]
@colintheshots how would you feel about GV learning how to set _arbitrary_ Shared Preferences from its debug config file?  Would Gecko-startup time be early enough to impact the shared pref above?

This might provide a decent way forward for parts of [Bug 1547717](https://bugzilla.mozilla.org/show_bug.cgi?id=1547717).  It's an abstraction breaking thing, but the GV mechanism is principled and believed to be secure.  Thoughts?

**Comment by colintheshots** [comment]
It's just a flat XML file key-value store. Alternatively, you can simply create a file before first run with these contents at this location `/data/data/${app_id}/shared_prefs/fenix_preferences.xml`:

```
<?xml version='1.0' encoding='utf-8' standalone='yes' ?>
<map>
    <int name="pref_key_bounce_quick_action" value="100" />
</map>
``

**Comment by colintheshots** [comment]
Yes, GV startup is likely early enough unless perhaps the first thing the user does is hit an external link from cold startup. Then there's a possibility of a race.

**Comment by ncalexan** [comment]
> It's just a flat XML file key-value store. Alternatively, you can simply create a file before first run with these contents at this location `/data/data/${app_id}/shared_prefs/fenix_preferences.xml`:
> 
> ```
> <?xml version='1.0' encoding='utf-8' standalone='yes' ?>
> <map>
>     <int name="pref_key_bounce_quick_action" value="100" />
> </map>
> ```

It's not reasonable to achieve this without an `android:debuggable="true"` APK.  The GV mechanism will work, with appropriate limitations, even for release APKs.

Thanks for confirming that GV startup might achieve this, though!

**Comment by acreskeyMoz** [comment]
I put a `shared_pref` in `/data/data/org.mozilla.fenix.performancetest/shared_prefs/fenix_preferences.xml` with the bounce quick action set to 100.
But I'm still seeing the Quick Action sheet pop up when running this with browsertime.
Does creation of a new profile clear this file?
It's getting reset to this on first run:
```
<?xml version='1.0' encoding='utf-8' standalone='yes' ?>
<map>
    <boolean name="pref_key_fxa_has_synced_items" value="true" />
    <boolean name="pref_key_follow_device_theme" value="true" />
    <int name="pref_key_bounce_quick_action" value="2" />
</map>
```
Normally we do clear app data with `shell pm clear $appId` before browsertime runs, but I'm not doing that for Fenix.

**Comment by acreskeyMoz** [comment]
So I've disabled the Quick Action Sheet in code for the tests that I'm running.

But here's an idea: what if we disable it automatically for the `forPerformanceTest` build target?

**Comment by acreskeyMoz** [comment]
@colintheshots @ncalexan 
In doing some work with Fenix I noticed another feature that needs to be disabled for visual metrics -- the ETP blocking pop-up on the navigation bar.

Using the `forPerformanceTest` build variant this is automatically hidden by feature flag:
https://github.com/mozilla-mobile/fenix/blob/25db27e448922d13ed12dc6b18568b69d1302d3b/app/src/main/java/org/mozilla/fenix/FeatureFlags.kt#L43

So that gave me an idea for the QuickActionSheet:

What if I put it behind a FeatureFlag and disable it for the `forPerformanceTest` builds?

If other visual features come along, they can be similarly disabled.

**Comment by acreskeyMoz** [comment]
@colintheshots What do you think about the above -- disable the QuickActionSheet in `forPerformanceTest` builds?

**Comment by mcomella** [comment]
@acreskeyMoz The QuickActionSheet (or QuickActionBar) is in the process of being removed: https://github.com/mozilla-mobile/fenix/issues/4281 I'm going to pre-emptively close this bug – feel free to reopen if that doesn't fit your needs. :)

**Comment by acreskeyMoz** [comment]
That's great, thanks @mcomella
