### ISSUE TITLE
Properly theme autcomplete highlight color

### ISSUE THREAD

**Issue by Cheap-Skate** [mozilla-mobile/fenix#505]
Search bar autocomplete has a purple background. Black text + purple background I find hard to see. Could it be a lighter color?

![20190214_175645](https://user-images.githubusercontent.com/40568887/52806973-397ebe00-3082-11e9-982a-943c75a85cac.jpg)

**Comment by sblatz** [comment]
This is currently blocked on an [android component feature](https://github.com/mozilla-mobile/android-components/issues/20230)

**Comment by sblatz** [comment]
Ready, but blocked on https://github.com/mozilla-mobile/fenix/issues/581 for final feedback regarding light theme.

**Comment by bsurd** [comment]
Verified on:
 - 1.0.1910 (Build #10642115)

 Devices:
 - Nokia 6 (Android 7.1.1)
 - HTC Desire 820 (Android 6.0.1)
