### ISSUE TITLE
[Bug] Fix broken UI test - privateModeScreenItemsTest

### ISSUE THREAD

**Issue by rpappalax** [mozilla-mobile/fenix#5050]
This test was reviewed and merged with broken steps :\  Probably best to ensure all tests run sucessfully in Firebase before approval.

Working on a fix

**Comment by sblatz** [comment]
Failing on this line
`androidx.test.espresso.NoMatchingViewException: No views in hierarchy found matching: (with id: org.mozilla.fenix.debug:id/share_tabs_button and is displayed on the screen to the user) `
