### ISSUE TITLE
[Bug]Notice"Firefox Preview (Private)" couldn't be removed.

### ISSUE THREAD

**Issue by PowERGD** [mozilla-mobile/fenix#5052]
## Steps to reproduce
1. Open a private tab.
2. You can see notice "Firefox Preview (Private)".
3. Clean all the private tab.
4. Turn off private mode.
### Expected behavior
Notice"Firefox Preview (Private)" can be removed.
### Actual behavior
Produce a zombie notice, which couldn't removed normally
### Device information

* Android device: 9.0.0 Redmi 4 prime
* Fenix version: 2.0.0-rc.1

**Comment by ekager** [comment]
Dupe of #5075
