### ISSUE TITLE
[Bug] share menu, copy url crashes fenix on Android Q

### ISSUE THREAD

**Issue by raghur** [mozilla-mobile/fenix#5053]
## Steps to reproduce
Og pixel xl on Android Q beta 6
Open any site. Click share menu. Click copy url

### Expected behavior
Fenix does not crash

### Actual behavior
Fenix crashes

### Device information

* Android device: yes
* Fenix version: 2.0.0 rc1

**Comment by mcarare** [comment]
Issue is reproducible on Android P, and I suspect any Android device with recent updates to Google Maps.
@raghur Please check if you have in your share list multiple "copy to clipboard" items. The one causing the crash is actually an intent handler from Maps. The other one should work just fine.
I will submit a PR to handle the issue.

**Comment by raghur** [comment]
I have only one 'Copy to clipboard' Item in the share menu

![image](https://user-images.githubusercontent.com/516267/64251635-98c8f080-cf36-11e9-9103-f8471919e8f5.png)

**Comment by matfantinel** [comment]
I'm on Android P, Galaxy S10e.

I can reproduce the issue, but in my case it has two items in the share menu: "Copy to clipboard" and "Copy". The latter works just fine, while the first crashes the browser.

**Comment by ekager** [comment]
Closing for #4911
