### ISSUE TITLE
[Bug] Crash when opening bookmarks

### ISSUE THREAD

**Issue by Furax-31** [mozilla-mobile/fenix#5055]
## Steps to reproduce: 
Open bookmarks ===> Crash instantly

## Expected behavior: 
The list of bookmarks should open

## Actual behavior: 
The application crash when opening bookmarks

### Device information: 
A5 2017 - Android Pie

* Android device: A5 2017
* Fenix version: All the latest versions since a few days - Last Nightly 190831 06:04 Build: #12430613

**Comment by Bandito11** [comment]
This happens to me too.

Nightly 190831 06:04 (Build #12430613)
📦: 11.0.0, ee70ba733
🦎: 70.0a1-20190830093857

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on Fenix **1.4.0-rc.1** using a Google Pixel 3a XL (Android 9).
