### ISSUE TITLE
Add toggle for Download confirmation dialog

### ISSUE THREAD

**Issue by dragneelfps** [mozilla-mobile/fenix#5057]
### Why/User Benefit/User Problem
For every download, we are shown download confirmation dialog. It becomes intrusive if user wants to download many files in a short amount of time. 

### What/Requirements

- Add a "dont show again" option in the download confirmation dialog.
- When enabled user won't be shown download confirmation dialog for every download initiated.

### Acceptance Criteria (how do I know when I’m done?)

- The option is shown in the dialog.
- If turned on, user isn't shown download confirmation dialog from next download.
- User can disable/enable the option in the settings.

**P.S.**- I can try implementing this if this feature is given the green light.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-13251)

**Comment by Smackd7677** [comment]
Please unsubscribe me from your mailing list and your application.  I never
signed up for this and someone has hacked my account and is attempting to
steal my money out if my online account.
Thanks Dawn Martin 3144652148

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812816

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
