### ISSUE TITLE
Explain why mixed content sites are insecure

### ISSUE THREAD

**Issue by andreicristianpetcu** [mozilla-mobile/fenix#5060]
## Steps to reproduce
open https://m.hotnews.ro
### Expected behavior
Either say why it's insecure, or mark it as secure
### Actual behavior
marked as insecure
![Screenshot_20190901-132656_Firefox_Nightly](https://user-images.githubusercontent.com/922368/64075103-89d70980-ccbc-11e9-8f1d-f67e664d6907.png)

### Device information

* Android device: OnePlus5t
* Fenix version: latest nightly

**Comment by NotWoods** [comment]
The page is insecure because it loads various images over `http://`. I updated the title because I agree we should explain why its insecure, like Desktop.
![Screen Shot 2019-11-21 at 11 28 15 PM](https://user-images.githubusercontent.com/1782266/69406295-9d3fb280-0cb6-11ea-8c65-00dd19433622.png)

**Comment by marcinwiacek** [comment]
#7038 is about this, that page is not opened at all...

**Comment by andreicristianpetcu** [comment]
Chrome just started blocking mixed content. Firefox has a feature behind a feature flag, I'm guessing this will soon be rolled out. I don't need this feature anymore. Closing. Too many issues in github.
