### ISSUE TITLE
Page opened from homescreen shortcut is deleted without warning in some cases

### ISSUE THREAD

**Issue by klint** [mozilla-mobile/fenix#5061]
First, I am assuming the following behaviour is intended by design, please correct me if I'm wrong: 
- if a page was opened from the nav bar (either via a search or a direct URL), pressing the BACK button on the phone will go back to the list of tabs and a tab for this page will be logged and displayed
- on the contrary, if a page was opened from a shortcut on the homescreen, pressing the BACK button on the phone will close the page and send Fenix to the background.

Based on this assumption, I think there may be the following bug. I hope I'll describe it correctly with words :)

## Steps to reproduce
1) Create a homescreen shortcut for a webpage in Fenix 
Go to tabs list, remove the tab for this page and exit Fenix (close the app)
2) Click on the homescreen shortcut
3) Once the page is opened, go to the tabs list by pressing on the tabs pile icon
Check that tab for this webpage is displayed at the top of the list
Click on this tab
4) Let it display, and now press the BACK button of the phone
 

### Expected behavior
The list of tabs is displayed, and either of the 2 options should happen:
a) as page A has been logged and displayed to the user in the tabs list, it could now behave like a page that was open directly from the browser, ie tab A could just stay there at the top of the list.
b) or it could still be considered as a shortcut page and be deleted, but at least with a warning/undo message as for any other deleted tab in the list. And the deletion should be undoable.

### Actual behavior
The list of tabs is displayed.
Tab A is visually removed from the list of tabs (we can even see the animation) but no warning/undo message is displayed.

### Device information

* Android device: Redmi Note 7 Android 9
* Fenix version: 12440613

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-13253)

**Comment by boek** [comment]
putting this under #6694

**Comment by topotropic** [comment]
This might be addressed with https://github.com/mozilla-mobile/fenix/issues/6620. The idea is that we don't close open tabs unless they have a parent tab.

**Comment by topotropic** [comment]
This is not a bug but expected behavior at the moment. 

We'd need learn more about expected behavior here to make an informed design decision.

**Comment by jonalmeida** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813227

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
