### ISSUE TITLE
[Bug] Can't long press links to see context menu in Custom Tabs 

### ISSUE THREAD

**Issue by pwd-github** [mozilla-mobile/fenix#5063]
## Steps to reproduce
1. Load a site in a custom tab
2. Try and follow a link or long press a on link 

### Expected behavior
If you're leaving the site, you should be kicked over to the proper browser.

Users should be able to long press content and bring up the context menus like "Copy link location" 

### Actual behavior
A confusing nothing. Literally nothing happens. 

### Device information

* Android device: LG G6, Android 8
* Fenix version: Nightly 190902 06:05 (Build #12450613)
📦: 11.0.0, ee70ba733
🦎: 70.0a1-20190830093857

**Comment by ekager** [comment]
So there are a few issues here. 

1. Firstly, we are not passing in `customTabSessionId` to `ContextMenuFeature` in `BaseBrowserFragment`. If we do that, the context menu will show in a custom tab.
 
2. The second question though is what options do we want in that context menu? "Share Link" and "Copy Link" work as expected. "Open link in new tab" and "Open link in private tab" also 'work' but when the snackbar pops up and you press "Switch" it seems like it does nothing. (The switch action selects the tab)

My guess is the desired behavior here is customizing the snackbar action "Switch" for custom tabs to actually launch Fenix to see the new selected tab, but I'm going to add needs UX. 

For now we could do 1 which would slightly improve behavior just by showing the context menu at all.

**Comment by brampitoyo** [comment]
@ekager I like doing item 1 for now, as you’ve proposed.

As for item 2, while I can think of a few items that match your list, we should probably create a new issue to tackle it.

In my mind, on that issue, we’ll need to figure out:

1. What all these long press menu items should be on different situations (normal vs. private custom tab – is there a difference?)
2. The most logical order/arrangement
3. That these menu items don’t conflict with anything

**Comment by ekager** [comment]
This is a good first issue then if we're just doing number 1 for now - you'll just be doing bullet 1 which is passing `customTabSessionId` into `ContextMenuFeature` in `BaseBrowserFragment`.
