### ISSUE TITLE
Inform user about share tabs progress

### ISSUE THREAD

**Issue by Mugurell** [mozilla-mobile/fenix#5065]
### User Benefit
As a user I would like to know the status of the "Share Tab[s]" action.

### Acceptance Criteria (how do I know when I’m done?)
After tapping on a `Send to devices` option I am informed about the `In progress` / `Success` / `Failure` status.

[Original feature design mockups](https://mozilla.invisionapp.com/share/8ZQVRNUJW3H#/screens/352450246)

**Comment by Mugurell** [comment]
Currently the `In progress` and `Failure` statuses are not shown in any way to the user.
Upon pressing a device option she would automatically be presented with a "Tab[s] sent" message 
even though the operation is in progress, not completed (Tabs were not actually sent yet) and the whole process may even fail.

What I propose is:
- upon `pressing a device option`
the user would see an indication of the `in progress` status
	- refresh arrow over the just pressed option
	- snackbar with an appropriate message
	- another dialog
Important here is to inform and block users from tapping the same option multiple times while the previous operation has not yet completed.
- upon `tabs being sent successfully`
the user would see a snackbar with a success message. Currently "Tab[s] sent!" is used
- upon `failure in sending tabs`
the user would see a snackbar with an error message. The [original feature design mockups](https://mozilla.invisionapp.com/share/8ZQVRNUJW3H#/screens/352450246) show the "Unable to send" message and a `Retry` action in a snackbar.

Asking UX for the best course of action here, if and how are we going to support the `In progress` and `Failure` statuses.

**Comment by lime124** [comment]
There are success/failure toasts in the design doc you linked. Let me investigate what happened here.

**Comment by lime124** [comment]
Ok here where we are at:
1. In progress - It's not possible to show in progress type messaging
2. Success/Failure messaging can only be shown if the device (Fenix here) succeeds or fails in _sending the tab._ It is not possible to show that the receiving device (e.g. desktop) received the tab. I would argue this is ok b/c getting the tab on the receiving device (or not) is the success/fail message.
3. We currently show a toast that shows the tab was successfully _sent_ from Fenix (again note the distinction between knowing it was sent vs received).
4. Currently there is no toast shown if the tab failed to be sent from Fenix. (e.g. Fenix has no internet)

Number 4 is the bit that needs to be implemented - when Fenix fails to send the tab to another device.

/cc @jonalmeida who worked on send/share tabs.

**Comment by jonalmeida** [comment]
Filed follow-up work for this based on @lime124 's comment:
- [ ] [Bug] Show toast for send tab failure - https://github.com/mozilla-mobile/fenix/issues/5092
- [ ] ShareController should use SendTabUseCases - https://github.com/mozilla-mobile/fenix/issues/5067 (needed for above)

**Comment by lime124** [comment]
@jonalmeida i think this bug can be closed now? it looks like the follow up bugs are implemented?
