### ISSUE TITLE
[Bug]Broken UX caused by the addition to a collection of the only opened tab

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#5066]
## Prerequisites
Have only one opened tab

## Steps to reproduce
1. Navigate to the web page
2. Tap the 3 dot menu icon in the bottom right corner
3. Select "Save to collection"
4. Save the tab to a collection 

### Expected behavior
1. The user should be redirected to the home page considering the fact that the opened tab is moved to a collection

### Actual behavior
The web page remains displayed with broken UX, 

### Device information

* Android device: 
• Google Pixel 3a (Androi 9)
• Samsung Galaxy Tab A (Android 9)
• Samsung S8+ (Android 8.0.0)

* Fenix version: 
• 2.0.0-rc.1
• Nightly Build #12441810

### Notes
► Video  Samsung Galaxy Tab A
![20190902_122625](https://user-images.githubusercontent.com/51314259/64105816-983a2980-cd7f-11e9-8353-f27363314e6c.gif)

**Comment by mcarare** [comment]
should be fixed by #5086

**Comment by sv-ohorvath** [comment]
Verified as fixed with #5086.
