### ISSUE TITLE
[Bug] Browser stuck in landscape / fullscreen mode after being sent to the background

### ISSUE THREAD

**Issue by gabrielesvelto** [mozilla-mobile/fenix#5068]
## Steps to reproduce

1. Browse to http://www.rai.it/dl/RaiTV/programmi/media/ContentItem-3a26a9c1-30ea-49a4-ac90-46fdc923b73c-tg3.html#p=0
2. Start playing the video and set it to fullscreen
3. When the video is in fullscreen mode set the  tablet in landscape orientation
4. Press the home button to go back to Android's home screen
5. Turn the tablet so that it's in portrait mode again
6. Open Firefox Preview again

### Expected behavior

Firefox can be taken out of fullscreen mode

### Actual behavior

Firefox opens in fullscreen mode, landscape orientation but the video isn't maximized anymore, the page containing it is shown instead. It's also impossible to exit fullscreen mode, pressing the back button goes back but doesn't take the browser out of fullscreen mode.

### Device information

* Android device: Nvidia Shield Tablet K1
* Fenix version: Nightly 190831 18:06 (Build #12431812)

**Comment by BranescuMihai** [comment]
For me it doesn't reproduce. Tried it on Galaxy Tab A tablet and Oneplus 7T pro, we seem to exit fullscreen mode when pressing home button, so it looks ok when coming back in the app. Could be device-specific

Can someone please re-test this? Thanks!

**Comment by AndiAJ** [comment]
Hi, I've re-checked on the latest **`Nightly Build #20560606 from 02/25`** and **wasn't able to reproduce** this matter using the following devices:
• Google Pixel 3a XL (Android 10)
• Google Pixel 3a (Android 9)
• Samsung Galaxy Tab A (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• Huawei MediaPad M3 Lite 10 (Android 7)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

► Video
![20200225-113316](https://user-images.githubusercontent.com/51314259/75235070-6355df00-57c4-11ea-9ef5-32c8c6b6a2be.gif)

@gabrielesvelto -  In case you still encounter this problem on you tablet, feel free to re-open this issue. ☺️

**Comment by gabrielesvelto** [comment]
Just checked on my device and it also doesn't reproduce there either, seems like this if fixed for good, thanks!

**Comment by craitose** [comment]
Yes this is still a problem on custom Android ROMs. 
Device : Xiaomi redmi 7 pro
OS : miui 12 (android 11)
Browser : Firefox beta
The workaround is to Enable rotate on the device then in the browser - launch the video again while in landscape then hit the enter-full screen button then hit the exit-full screen button. Disable rotate on the device

**Comment by dkter** [comment]
This still seems to be unfixed. I just got stuck in landscape mode after watching a video on bbc.com. I'm running Android 11 on a Pixel 3a. Firefox was in the embedded/in-app browser mode in case that was the issue.

**Comment by jpodolski** [comment]
This is also happening to me with a Pixel 3 running LineageOS 18.1-20220315-microG-blueline and Firefox 98.2.0 (Build #2015868579). YouTube was accessed via Twitter immediately before this happened, and has not had the issue in the past until the picture-in-picture/"draw over other apps" feature was used. Interestingly, Firefox can switch landscape orientations when flipping the device, but cannot go back to portrait mode. 

Solution: force quit the app. Regularly killing the app in "active apps" view does not work.

Low priority obviously, but just letting someone know this still happens.
