### ISSUE TITLE
UI nit:- top search bar briefly turns into "full URL bar" when I hit enter key on keyboard

### ISSUE THREAD

**Issue by Cheap-Skate** [mozilla-mobile/fenix#507]
Type some search text into the search bar (not a known URL, an actual Google search)
Hit enter on your keyboard
The search bar at the top of the screen briefly (quarter of a second?) turns into the full URL bar with the Google search URL in it including globe icon, tabs icon, 3 dot menu before returning to the bottom of the screen.

Perhaps it could be stopped doing this, it's a bit ugly (but not a massive issue).

This is a single frame grab from the sequence, it only lasts a short period of time

<img width="405" alt="screenshot 2019-02-14 at 18 01 25" src="https://user-images.githubusercontent.com/40568887/52807652-05a49800-3084-11e9-8d6b-87a55216f2e3.png">

And here's a video from which the frame grab came

[searchbar.mov.zip](https://github.com/mozilla-mobile/fenix/files/2866294/searchbar.mov.zip)

Galaxy S7
Android 8.0.0

**Comment by ekager** [comment]
I can reproduce on Pixel 3 by adding a small delay in `transitionToBrowser()`. Currently in BrowserToolbar, it enters display mode when the url is entered: 

```
internal fun onUrlEntered(url: String) {
        displayMode()

        urlCommitListener?.invoke(url)
    }
```

**Comment by ekager** [comment]
Filed an issue to discuss with AC Team 
https://github.com/mozilla-mobile/android-components/issues/2077

**Comment by ekager** [comment]
@pocmo added more control to the toolbar urlCommitListener for this issue in AC so we will be able to update this next week. Thanks!!

**Comment by sv-ohorvath** [comment]
Could reproduce this and now it's verified as fixed.
