### ISSUE TITLE
[Bug] URL can't be copied in custom tab

### ISSUE THREAD

**Issue by SorinaFlorean** [mozilla-mobile/fenix#5070]
Steps to reproduce:
1. From Gmail open a link using custom tab;
2. Long tap the URL from the toolbar to copy it.

Expected behavior
* The URL is copied.

Actual behavior:
* The URL is not copied.

Android device: 
- Samsung S8+ (Android 8.0.0)
- Samsung Galaxy Tab A (Android 9)
- Xiaomi Mi Pad 2 (Android 5.1)

* Fenix version: 2.0.0 / build #12421509

**Comment by mcarare** [comment]
Following the discussion [here](https://github.com/mozilla-mobile/fenix/issues/4155), I think the auto-copy feature has been removed.

**Comment by AndiAJ** [comment]
Please see [#4252](https://github.com/mozilla-mobile/android-components/issues/4252)

**Comment by ekager** [comment]
We intentionally removed this behavior, do you want us to add it back for custom tabs @vesta0 ?

**Comment by vesta0** [comment]
@ekager thanks for the clarifying note and no we don't want to add it back. I was just confused by QA tagging it as a bug.
