### ISSUE TITLE
[Bug] Close all private tabs notification too persistent

### ISSUE THREAD

**Issue by neekless** [mozilla-mobile/fenix#5075]
Regarding: https://github.com/mozilla-mobile/fenix/commit/cc5408d7176b853e0b405b7c13ab931adde0ca50

## Steps to reproduce
Open private tabs. Observe notification. Close all private tabs. 

### Expected behavior
I would expect this notification to be more like chrome's, which would dismiss itself once there are no more private tabs. 

### Actual behavior
This notification persists even after all private tabs have been closed and cannot be swiped away. Only way to remove it is to remove fenix from recent apps. I hope this is not intended behavior? 

### Device information

* Android device: Pixel 2xl android 9
* Fenix version: 2.0.0-rc.1 (Build #12421507)
📦: 10.0.1, a573b4116
🦎: 69.0-20190824140027

**Comment by liuche** [comment]
We'll talk about whether this falls into the criteria for whether it should go into the sprint.

**Comment by neekless** [comment]
Another observation: if I have multiple private tabs open and I close one of them (manually), the notification will dismiss even though I still have other private tabs open.

**Comment by jyeontaek** [comment]
@liuche I think this should be pulled into this sprint. It should be a one-line fix, and it'll stop the app from draining user's battery unnecessarily.

**Comment by liuche** [comment]
It sounds like this should match Focus behavior: notification should be dismissed if and only if there are no more private tabs (and not dismissed if a PB tab is manually closed, or stay open if there are PB tabs open).

I don't think this falls into our criteria of what it takes to move into this sprint (and there's also the review to take into account), but I'll move this to the top of the bug backlog and put some labels on it. @jyeontaek if you have extra cycles (bc we don't track your work) feel free to pick it up.

**Comment by neekless** [comment]
Fixed in Nightly 190905 18:17 (Build #12481826)
📦: 12.0.0, 7c8561f15
🦎: 71.0a1-20190904094319

**Comment by sv-ohorvath** [comment]
Verified as fixed as well on Nightly 9/9.
