### ISSUE TITLE
[Bug]  [L10N] Improperly displayed addition of a tab to collection for Spanish

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#5076]
## Prerequisites
1. Device language and input is set to Spanish
2. Have at least one open tab

## Steps to reproduce
1. From the tabs view tap on "Save to collection" button
2. Create and save the tab to a collection
3. Check the confirmation snackbar

### Expected behavior
Properly displayed snackbar "string !"

### Actual behavior
Exclamation mark displayed before the string e.g. ! string !

### Device information

* Android device: Samsung Galaxy Tab A (Android 9)
* Fenix version: 2.0.0-rc.1

### Notes
► Video
![Spanishnotification](https://user-images.githubusercontent.com/51314259/64151405-f96f0500-ce32-11e9-831a-038eb1c153e3.gif)

**Comment by mcarare** [comment]
Actually, inSpanish the upside-down exclamation point (¡) is used at the beginning of all exclamatory sentences. This is the expected string.

**Comment by Delphine** [comment]
It's indeed correct this way :) this can be closed unless there's anything else

**Comment by gaby2300** [comment]
Yes, I can also confirm it's correct!

In Spanish we use the opening exclamation (¡) mark at the beginning of a
sentence, and the closing one (!) at the end.

**Comment by AndiAJ** [comment]
Many thanks @Delphine & @gaby2300 ! :)
I'll go ahead and close this issue.
