### ISSUE TITLE
[Bug][L10N] Improperly displayed Fenix Private session description, Sync section & Accessibility for Korean

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#5079]
## Prerequisites
Device language and input is set to Korean

## Steps to reproduce
1. Open Fenix
2. Switch to PB (check the private session description)
3. Tap the upper right 3dot button and select Setting
4. Tap on "Turn on Sync" (check the page)
5. Tap back
6. Tap on "Accessibility" and disable the "automatic Font Sizing"
7. Check the String "The quick brown fox ..."

### Expected behavior
All of the above should be translated to Korean

### Actual behavior
Private session description, Sync section & Font Sizing example should be translated.

### Device information

* Android device: Samsung Galaxy Tab A (Android 9)
* Fenix version: 2.0.0-rc.1

### Notes
► Pics

• Private session description
![Screenshot_20190903-091003_Firefox Preview](https://user-images.githubusercontent.com/51314259/64153133-d7778180-ce36-11e9-80d5-0d55ebcd611d.jpg)

• Sync section 
![Screenshot_20190903-091036_Firefox Preview](https://user-images.githubusercontent.com/51314259/64153140-da727200-ce36-11e9-8034-9df360b348bd.jpg)

• Font Sizing example 
![Screenshot_20190903-091053_Firefox Preview](https://user-images.githubusercontent.com/51314259/64153151-e100e980-ce36-11e9-9f0e-12859e3258a0.jpg)

**Comment by mcarare** [comment]
related issue: #4212

**Comment by Baron-Severin** [comment]
The most likely scenario here is that those strings simply haven't yet been translated to Korean.  We should check in Pontoon to verify that this is the case, and if so ping someone on the localization team to see if anyone might be available to help on it.

**Comment by boek** [comment]
https://github.com/mozilla-l10n/android-l10n/blob/master/mozilla-mobile/fenix/app/src/main/res/values-ko/strings.xml

Looks like this string hasn't been translated into Korean yet. cc: @Delphine

**Comment by softvision-miralobontiu** [comment]
Verified this issue on the latest 5/27 Nightly build, and on Beta 5.1.0-beta.2 build, and this issue is fixed:
* private browsing:
![korean](https://user-images.githubusercontent.com/40694158/83025951-cfe8b000-a037-11ea-8e6e-aafabefae6d7.png)
* sync menu:
![korean1](https://user-images.githubusercontent.com/40694158/83026938-1fc77700-a038-11ea-8bd0-e601bdc8627b.png)
* accessibility:
![korean2](https://user-images.githubusercontent.com/40694158/83026965-2950df00-a038-11ea-96a9-e47569e29d16.png)
