### ISSUE TITLE
[Bug]Improperly displayed Site permission Exceptions for a couple of languages

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#5080]
## Prerequisites
Device language and input is set to Japanese

## Steps to reproduce
1. Tap on the upper right 3dot button and select "Settings"
2. Tap on "Site permissions"
3. Tap exceptions 
4. Check the "No site exception" string

### Expected behavior
The string should be displayed in Japanese as per the case where we have empty lists of Bookmarks & History 

### Actual behavior
The string is displayed in English.

### Device information

* Android device: Samsung Galaxy Tab A (Android 9)
* Fenix version: 2.0.0-rc.1

### Notes

<details>
    <summary>Other affected languages</summary>
• German 
• Spanish
•French 
• Italian
• Swedish
• Russian 
• Korean 

</details>

<details>
    <summary>Comparison Empty list of  Site exceptions VS Bookmarks & History</summary>

► Site exceptions Japanese
![Screenshot_20190903-110646_Firefox Preview](https://user-images.githubusercontent.com/51314259/64155272-20c9d000-ce3b-11e9-93c0-12dc47d524fa.jpg)

► Bookmarks
![Screenshot_20190903-092756_Firefox Preview (1)](https://user-images.githubusercontent.com/51314259/64154879-5f12bf80-ce3a-11e9-9a81-9d6b8fa035ee.jpg)

► History
![Screenshot_20190903-092749_Firefox Preview](https://user-images.githubusercontent.com/51314259/64154971-95e8d580-ce3a-11e9-9865-7f8f953afd51.jpg)

</details>

**Comment by vesta0** [comment]
@Delphine @boek is this happening because those strings haven't been localized yet?

**Comment by boek** [comment]
@vesta0 Hmm, it looks like these strings were put into their own strings file. I think we may only be translating strings in strings.xml. We have to move them on our side first

**Comment by Delphine** [comment]
I confirm we never got those strings on our side
