### ISSUE TITLE
[Bug] Bookmarks sync is very slow

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#5084]
## Steps to reproduce
1. Connect an Android device with a desktop app on which there are some bookmarks saved.
2. Sync.
3. Leave the Bookmarks menu opened after the sync is triggered.
### Expected behavior
Bookmarks appear almost immediately.
### Actual behavior
On Fenix, bookmarks don't appear at all for a long time. They will eventually appear if you leave the bookmarks menu open and check again in 1 min or so. The desktop folders are loaded slowly.
[sync-log.txt](https://github.com/mozilla-mobile/fenix/files/3569407/sync-log.txt)

### Device information

* Android device: HTC Desire 820 (Android 6.0.1), Pixel 3A (Android 9)
* Fenix version: RC 2.0

**Comment by ekager** [comment]
Closing for #4513
