### ISSUE TITLE
[Bug] Window _blank links do not work in Custom Tabs

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/fenix#5085]
## Steps to reproduce
1. Go to this [ZDNet article](https://www.zdnet.com/article/upcoming-firefox-update-will-decrease-power-usage-on-macos-by-up-to-three-times/).
2. Click on a link in the article (like the "HackerNews" one).
3. Observe.

### Expected behavior
Click the link opens up that page.

### Actual behavior
Nothing happens.

### Device information

* Android device: Android 9 (Pixel 2)
* Fenix version: (03/09/2019)

**Comment by jonalmeida** [comment]
A-C issue: https://github.com/mozilla-mobile/android-components/issues/4296

**Comment by jonalmeida** [comment]
Adding the group triage label so that a-c can know next sprint planning how important this issue to fix.

**Comment by jonalmeida** [comment]
I left a UX request on the a-c ticket, but feel free to move the conversation here: https://github.com/mozilla-mobile/android-components/issues/4296#issuecomment-529595147

> **UX question:** In a Custom Tab/PWA/TWAs, when a site requests to open a link in a new tab, how should we handle that?
> 
> From what I can tell, we may have two options here:
>  - Load the request in the same window, which might break some pages like login sites that close after you login to go back to the original content. We could try to "go back" in this case but it seems complicated to handle engineering-wise having not looked into the code yet.
>  - We switch the user to the main browser window to handle the request there. This might also be awkward since we've lost context for the user.
> 
> For reference, Chrome follows the first pattern.

**Comment by lime124** [comment]
sorry dropped the ball on this one. @apbitner can you take a look?

**Comment by apbitner** [comment]
@jonalmeida is this bug still happening for you? I just tried to reproduce and it opened the link in the same window (option 1). I'm on the latest build, Pixel 3, Android 10.

**Comment by jonalmeida** [comment]
@apbitner Were you in a custom tab? I can still see the issue happening. 

If you set your browser default to be Fenix, then send the link to yourself and try to open it in the Gmail or the Slack app, the link will open in [a custom tab](https://developer.chrome.com/multidevice/android/customtabs). When you link on the links that have `target="_blank"` you should see nothing happen.

There are some examples on how it works, and good recommendations for web developers here: https://css-tricks.com/use-target_blank/

As a browser app, we need to be able to handle those links (which we do), however in Custom Tabs and TWAs this doesn't work and I'm not sure how it should (but I'm leaning more to my first recommendation).

**Comment by jonalmeida** [comment]
Spoke with @apbitner offline: both sides have their pros and cons, but we should try to follow what Chromium-based engines have done for now.

i.e. option 1: Load the request in the same window.

**Comment by lime124** [comment]
looks like this has been resolved from our side - removing ux label. please reach out again if you need something further!

**Comment by NotWoods** [comment]
Reopening for QA

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **Nightly Build #13240608 from 20/11** using the following devices:
• Google Pixel 3a XL (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

► Video
![20191120_111505](https://user-images.githubusercontent.com/51314259/69225711-89e1f980-0b87-11ea-83e7-c8cb5528b635.gif)
