### ISSUE TITLE
Remove "temporaryStorage" vars from ThemeManager and BrowserModeManager

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#509]
We are currently using a temporaryStorage var that outlives the activity life cycle. We should work towards a better persistence method.

@colintheshots any thoughts on how we can tackle this?

[ThemeManager](https://github.com/mozilla-mobile/fenix/blob/d543d776b1240283585363fe470ca22c4538806f/app/src/main/java/org/mozilla/fenix/ThemeManager.kt#L34)

**Comment by boek** [comment]
This was done with a7d5cdcb9dbebcf26623561990b8ecbc18cbfd37 and #2733
