### ISSUE TITLE
[Bug] Show toast for send tab failure

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/fenix#5092]
## Steps to reproduce
1. Try to send a tab without internet.

### Expected behavior
1. A toast is seen as per some of [the original designs][0] (image below as well).

### Actual behavior
1. Nothing is seen.

### Device information

* Android device: n/a
* Fenix version: n/a

This was filed as follow-up work for https://github.com/mozilla-mobile/fenix/issues/5065#issuecomment-527577240

<img width="362" alt="Screen Shot 2019-09-03 at 2 23 43 PM" src="https://user-images.githubusercontent.com/1370580/64198753-d8b8a680-ce56-11e9-943d-b4db0c37f927.png">

[0]: https://mozilla.invisionapp.com/share/8ZQVRNUJW3H#/screens/352450246

**Comment by jonalmeida** [comment]
Today, we have the success toast, but it does not say "Send to MacBook" instead "Tab Sent!"

@mheubusch would you know if the strings for the failure toast are still accurate?

**Comment by jonalmeida** [comment]
Engineering notes:
- We need to look at the `Deferred<Boolean>` result of the `sendTabUseCases.sendToDeviceAsync` et al calls so that we can show the success/failure.

**Comment by softvision-miralobontiu** [comment]
Verified that the toast "Unable to send    RETRY" is displayed when the tab cannot be sent.
Tested on the latest Nightly build 190927 (#12700627) with Xiaomi Mi 8 Lite (Android 9), and Huawei Media Pad M2 (Android 5.1.1).

![Screenshot_2019-09-27-14-20-41-401_org mozilla fenix nightly](https://user-images.githubusercontent.com/40694158/65766530-f61a2100-e133-11e9-8300-5f2d367419d7.png)
