### ISSUE TITLE
Add telemetry for suggestion toggles

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#5094]
#### Description & Product Manager / Data Scientist User Story
- As a product owner, I want to know if users choose to disable various types of awesomebar suggestions so we can improve its usability in future iterations.

#### What questions will you answer with this data?
- Do users want to see suggestions from search provider??
- Do users want to see suggestions from their clipboard?
- Do users want to see suggestions from their browsing history?
- Do users want to see suggestions from their bookmarked sites?

#### What probes (suggested, if applicable)
- Enable/Disable search suggestions (this already exists)
- Enable/Disable clipboard suggestions
- Enable/Disable search browsing history
- Enable/Disable search bookmarks

### Acceptance Criteria (Added by PM)
- Event pings can be queried via re:dash
- We are sending telemetry events for the actions listed in the requirements
- We have documented the telemetry
- We have asked a data steward to [review](https://github.com/mozilla/data-review/blob/master/request.md) the telemetry
- NOT an AC: Data science to create dashboard or further graphs (this will be a separate issue, this issue is only about hooking up the events described and that they can be queried in re-dash)

**Comment by abodea** [comment]
#### Hello, I tried to check all the options from the Search menu, for more details please see the table below:


| Name | preference_key | false | true |
| --- | --- | --- | --- |
| Show search suggestions | pref_key_show_search_suggestions | ✔️ | ✔️
| Show search shortcuts |  Nothing was displayed | ❌ | ❌
| Show clipboard suggestions | pref_key_show_clipboard_suggestions | ✔️ | ✔️
| Search browsing history | pref_key_search_browsing_history | ✔️ | ✔️
| Search bookmarks | pref_key_search_bookmarks | ✔️ | ✔️
| Enhanced Tracking Protection | Show file differences that haven't been staged | ✔️ | ✔️
| TP Strict | etp_setting_changed with "etp_setting": "Standard" | ✔️ | ✔️
| TP Standard | etp_setting_changed with "etp_setting": "Strict" | ✔️ | ✔️

I added in the table Tracking protection toggles to ask if it's everything fine or need something to be changed there.

Based on my comment I will remove the `qa:needed` until the `Show search shortcuts` is fixed.
I know that is not mentioned in the description but it's a button on the search menu among the others.
@sblatz, @vesta0 do we want to track the `Show search shortcuts`?

Here you can find the full events:
```Kotlin
{
      "events": [
        {
          "timestamp": 0,
          "category": "tracking_protection",
          "name": "etp_setting_changed",
          "extra": {
            "etp_setting": "STANDARD"
          }
        },
        {
          "timestamp": 303178,
          "category": "tracking_protection",
          "name": "etp_settings"
        },
        {
          "timestamp": 335001,
          "category": "events",
          "name": "preference_toggled",
          "extra": {
            "preference_key": "pref_key_show_search_suggestions",
            "enabled": "true"
          }
        },
        {
          "timestamp": 335885,
          "category": "events",
          "name": "preference_toggled",
          "extra": {
            "preference_key": "pref_key_show_clipboard_suggestions",
            "enabled": "true"
          }
        },
        {
          "timestamp": 336336,
          "category": "events",
          "name": "preference_toggled",
          "extra": {
            "preference_key": "pref_key_search_browsing_history",
            "enabled": "true"
          }
        },
        {
          "timestamp": 336821,
          "category": "events",
          "name": "preference_toggled",
          "extra": {
            "preference_key": "pref_key_search_bookmarks",
            "enabled": "true"
          }
        }

**Comment by sblatz** [comment]
Thanks @abodea, yes that toggle was added after this ticket was finished. I can add it, though, since we're tracking the other toggles on that screen and it makes sense as it equally impacts the search experience.

**Comment by vesta0** [comment]
Good idea @sblatz and @abodea

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest debug build from Master 1.0.1941 11/10 using a google Pixel 3a (Android 9).


✔️ Enable/Disable search suggestions
Ping 38afbc67-f626-4082-852c-e34ea0470630

✔️ Enable/Disable Search_shortcuts 
Ping f10fd5f1-87c7-4e31-94cd-f03c429ac29a

✔️ Enable/Disable clipboard suggestions 
Ping 84f82d09-6516-49f7-9b7c-e2d40a999a76

✔️ Enable/Disable search browsing history 
Ping 917b903f-e829-4be3-a90a-8959d2d35b3e

✔️ Enable/Disable search bookmarks 
Ping 041d59b8-63c1-4cab-a2b6-9ab00d9ea0bc

[Logcat](https://github.com/mozilla-mobile/fenix/files/3717800/setto.txt)
[Glean dashboard](https://debug-ping-preview.firebaseapp.com/pings/aj-1110111)
