### ISSUE TITLE
[Bug] Text for search providers in search engine fragment is not `primaryText` color

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#5095]
<img width="343" alt="image" src="https://user-images.githubusercontent.com/4400286/64204311-5aee9e00-ce4a-11e9-913c-d4fb24174cb0.png">

We should make this match the rest of the text on the screen.

**Comment by sblatz** [comment]
Nevermind, apparently this is intentional.

**Comment by sblatz** [comment]
In `search_engine_radio_button.xml` we're setting the `textAppearance` to `?android:attr/textAppearanceListItem`. We'll want to set the color to `?primaryText` if we want this changed.

**Comment by sv-ohorvath** [comment]
Verified as fixed on 2.0.0-rc2.
