### ISSUE TITLE
Add hyperlink to "Common myths about private browsing"

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#510]
Breakout of #347.

We will need a new SUMO article to hyperlink to.

<img width=600 src=https://user-images.githubusercontent.com/51007/51957894-53c97100-24b2-11e9-8a3a-66f07f59b9d4.png>

Engineering effort should be fairly small as we just need to plug the URL in once it's ready.

**Comment by mheubusch** [comment]
Here is the link:   https://support.mozilla.org/1/firefox/%VERSION%/%OS%/%LOCALE%/private-browsing-myths

**Comment by jonisavage** [comment]
This is the right link, but I recommend using "mobile" instead of "firefox", so it would be:

https://support.mozilla.org/1/mobile/%VERSION%/%OS%/%LOCALE%/private-browsing-myths

**Comment by bsurd** [comment]
Verified on:
 - 1.0.1910 (Build #10642115)

 Devices:
 - Nokia 6 (Android 7.1.1)
 - HTC Desire 820 (Android 6.0.1)
