### ISSUE TITLE
[Bug]Improperly displayed about crashcontent after rotation

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#5103]
## Steps to reproduce
1. Navigate to about:crashcontent
2. After the crash page shows up rotate the device to landscape view
3. Rotate the device back to portrait view

### Expected behavior
The crash page is properly displayed.

### Actual behavior
The content gets shifted after each rotation.

### Device information

* Android device: 
• OnePlus 6T (Android 9)
• Google Pixel 3a XL (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

* Fenix version:  Nighlty Build #12470611 from 4/9

### Notes

► Video
![20190904_083315](https://user-images.githubusercontent.com/51314259/64255224-97dd9200-cf29-11e9-8394-f53e0796964e.gif)

**Comment by boek** [comment]
😱

**Comment by abodea** [comment]
Reproducible on Fenix 3.1.0-beta 3(Build #20092354) GV 72 with Google Pixel 3a XL(Android 10).
