### ISSUE TITLE
Create a dashboard to see the crash ratio for Crashes per Active Devices

### ISSUE THREAD

**Issue by st3fan** [mozilla-mobile/fenix#5113]
When https://github.com/mozilla-mobile/fenix/issues/235 has landed we should have a crash count field in the Glean metrics ping that we can use to start showing a crash ratio for _Crashes per Active Devices_

This bug is to ask for a dashboard to visualize that metric.

**Comment by liuche** [comment]
@fbertsch should we file a Bugzilla bug for this?

**Comment by liuche** [comment]
Opened https://bugzilla.mozilla.org/show_bug.cgi?id=1584351

**Comment by liuche** [comment]
Update: the team doesn't have capacity for this crash measurement dashboard for work unrelated to Skyline, for the time being. I'll figure out the relative priority of this compared to other dashboard requests fenix has.

**Comment by liuche** [comment]
https://trello.com/b/yxe1bwjL/mobile-learning-requests

**Comment by boek** [comment]
@liuche Based on the bugzilla ticket it looks like this has been resolved? If so can we close?
