### ISSUE TITLE
[Bug]Shifted Play sign on Bing after rotation

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#5129]
## Prerequisites
Set Bing as your default search engine

## Steps to reproduce
1. Search for e.g. "gods plan drake"
2. Rotate the device to landscape view
3. Check the play sing from the featured youtube video

### Expected behavior
The featured youtube video should be displyed properly

### Actual behavior
The play sign is shifted after rotation

### Device information

* Android device: Google Pixel 3a XL (Android 9)
* Fenix version: 1.4.0-rc.1

### Notes
► Video
![20190905_141148](https://user-images.githubusercontent.com/51314259/64337543-45af7600-cfe8-11e9-83ed-85aee4022995.gif)

**Comment by AndiAJ** [comment]
Reproducible on RC 1.4.1 in portrait mode using a Samsung Galaxy Tab A (Android 9)

**Comment by boek** [comment]
Is this also reproducible in Chrome?

**Comment by AndiAJ** [comment]
Hi @boek , yes, this is happening on **Chrome**, **Brave** and on the latest **Fenix Nightly Build #13640626 from 12/30**
I've re-checked this using the following devices:

• Google Pixel 3a (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

## **► Fenix**
![20191230_132645](https://user-images.githubusercontent.com/51314259/71580453-635d9980-2b09-11ea-8f57-a891f4432726.gif)

## **► Chrome**
![20191230_132515](https://user-images.githubusercontent.com/51314259/71580504-9ef86380-2b09-11ea-900c-db717028dde3.gif)

## **► Brave**
![20191230_132554](https://user-images.githubusercontent.com/51314259/71580610-13cb9d80-2b0a-11ea-9101-4924df0063e8.gif)

Please advise on how should we proceed. ☺️

**Comment by kbrosnan** [comment]
Sounds like a website bug then. It would be up to Bing devs to fix this.
