### ISSUE TITLE
[Bug]Featured Google images aren't opened, white screen presented

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#5130]
## Prerequisites
Have Google set as your default search engine

## Steps to reproduce
1. Tap on the search bar and search "images"
2. Tap on any of the featured images

### Expected behavior
Image is opened
 
### Actual behavior
White screen presented
### Device information

* Android device: 
• Google Pixe 3a XL (Android 9)

* Fenix version: 1.4.0-rc.1

### Notes
►Video
![20190905_144942](https://user-images.githubusercontent.com/51314259/64339895-9d041500-cfed-11e9-80d8-39a078dd5409.gif)

**Comment by AndiAJ** [comment]
Seems to be happening on Fennec as well https://bugzilla.mozilla.org/show_bug.cgi?id=1582453

**Comment by abodea** [comment]
Verified as fixed on the latest **Nightly 14/10** with **Google Pixel 4 XL (Android 11).**
![20201214-095155](https://user-images.githubusercontent.com/42831109/102055984-54442a00-3df4-11eb-8ba2-1428ce046b9c.gif)
[Note that I added a new bug as when opening an image, is not following the behavior from Google Chrome (opening the image correctly as it opened from the images) ](https://github.com/mozilla-mobile/fenix/issues/17013)
