### ISSUE TITLE
[Bug] Android 5&6 - Tabs not visible when you open history/bookmarks in new tabs

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#5131]
## Steps to reproduce
1. Go to history/bookmarks.
2. Select some items.
3. Tap the 3 dot menu and select "open in new tab"/ "open in private tab".
4. Observe the homescreen. 
5. Scroll the homescreen.
### Expected behavior
The tabs created are visible on the normal/private homescreen.
### Actual behavior
The tabs are not visible at first, only after yyou scroll the homescreen a little.
Similar to https://github.com/mozilla-mobile/fenix/issues/2874
### Device information

* Android device: Huawei P9 Lite (Android 6.0), Xiaomi Mi Pad 2 (Android 5.1)
* Fenix version: Nightly 9/5 & RC 1.4.0

**Comment by softvision-miralobontiu** [comment]
Verified as fixed on the latest Nightly 190927 (#12700627) with Huawei P9 Lite (Android 6), Samsung Galaxy Tab A6 (Android 5.1.1), Huawei Media Pad M2 (Android 5.1.1).
