### ISSUE TITLE
Integrate APIs to discover if there are cached files and cookies to delete

### ISSUE THREAD

**Issue by colintheshots** [mozilla-mobile/fenix#5139]
### Why/User Benefit/User Problem
Currently, the Delete Browsing Data screen gives the impression that there are always cookies and cached files to delete. This makes the screen a placebo after the user has already cleared data. It would be easier to tell at a glance if user data is being stored if we had APIs to tell.

### What/Requirements
If we intend to solve this, we need GV APIs. This may not be worthwhile in the grand scheme of things, but we should experiment with the new screen to decide.

### Acceptance Criteria (how do I know when I’m done?)
The Delete Browsing Data screen has the ability to disable checkboxes of items that have already been deleted.

**Comment by vesta0** [comment]
Closing for now and will re-open if this becomes a priority based on feature usage.
