### ISSUE TITLE
Allow user to always open 3rd party links in PBM + TP on

### ISSUE THREAD

**Issue by bbinto** [mozilla-mobile/fenix#514]
### Why/User Benefit/User Problem
As a user, I want the option to always open 3rd party links in Fenix private browsing mode with TP on.

### Acceptance Criteria (how do I know when I’m done?)
I can click on a link in another app and have it open in Fenix private browsing mode with TP on.
I can enable/disable this setting.

**Comment by SimonSapin** [comment]
I’d like this as well, to replace Firefox Focus (which if I understand correctly won’t be developed further?)

**Comment by cadeyrn** [comment]
> I’d like this as well, to replace Firefox Focus (which if I understand correctly won’t be developed further?)

The development of Firefox Focus is on hold while the big focus is on Fenix , but the project is still alive.

**Comment by SimonSapin** [comment]
Oh ok, that’s good to know. Still, it seems that Fenix could take over this use case without the need for an entirely separate app/product.

**Comment by joebloggs7657** [comment]
Hi please can you make this also as a feature for all tabs rather than just third party links? 
Like others have said Bromite achieves this well however their drawback is that you cannot take screenshots while the feature is active. Thanks.

**Comment by lime124** [comment]
removed ux label as this is part of q3 plans

**Comment by Spinus1** [comment]
Hello,
let me add my humble opinion: to further improve this feature a button to re-open the current tab in "normal mode" could be added.

Let me give you an example: currently I'm using Firefox Focus as default browser, so every link that I open from external apps is opened in a private session. Sometimes I want to login to that site, so I copy the link and paste in Firefox (in Firefox I've previously logged in that site).

Having a button to re-open tab and ability to open external links in private mode will greatly improve my workflow...

BR,
Alessio

**Comment by vrudesai** [comment]
Set as acceptance criteria for Launch icon for private browsing #419

**Comment by sblatz** [comment]
Not working see: https://github.com/mozilla-mobile/fenix/issues/5396

**Comment by klint** [comment]
Side effect of this feature (a bug IMHO):  #5518
