### ISSUE TITLE
[Bug] Navigating to search widget, then opening Fenix shows search panel instead of home

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/fenix#5140]
## Steps to reproduce

1. Add search widget to desktop
2. tap search widget
3. tap home navigation button
4. open Fenix

### Expected behavior

I see my tabs (home).

### Actual behavior

I am still in search mode, and it is not obvious how to get back to home (I can tap back).

### Device information

* Android device: Pixel 2
* Fenix version: latest nightly

**Comment by boek** [comment]
Fixed with #6666
