### ISSUE TITLE
[Bug] can't access learn more link for tracking protection exceptions with talkback.

### ISSUE THREAD

**Issue by asadotzler** [mozilla-mobile/fenix#5141]
## Steps to reproduce
Launch Fenix with Talkback active. 
Navigate to menu -> Settings -> Tracking Protection -> Exceptions
Swipe to focus Learn more link. 

### Expected behavior
Learn more link should get focus.

### Actual behavior
Container containing description of Exceptions and Learn more link gets focus and activating it does not activate the link. 

### Device information

* Android device: Samsung Galaxy S10e running Android 9
* Fenix version: 190905

**Comment by mcarare** [comment]
You could use local context menu (swipe up then right to activate it) and select links menu so you can browse to that link. Do you find this flow to be acceptable, or we should consider making the link focusable?

**Comment by asadotzler** [comment]
I think we need to do something more here and not rely on users work around the issue. Talkback reads the paragraph and the link and says double-tap to activate but double-tap does nothing.

**Comment by mcarare** [comment]
Same issue with _"Common myths about private browsing"_ link when starting private mode.

**Comment by softvision-miralobontiu** [comment]
Verified that the support page from Settings - ETP - Exceptions can be accessed when Talkback is on.
Tested with the latest Nightly 9/22 with Nokia 6 (Android 7.1.1), and Motorola Moto G6 (Android 8).
