### ISSUE TITLE
[Bug] Search engine selection is awkward with Talkback

### ISSUE THREAD

**Issue by asadotzler** [mozilla-mobile/fenix#5142]
## Steps to reproduce
Launch Fenix with Talkback running. 
Navigate to menu -> Settings -> Search engine
Swipe through search engine list
### Expected behavior
One "activate" option for each search engine listed. 
### Actual behavior
For each search engine there is a button and a radio button that can both be focused and used to activate that engine
### Device information

* Android device: ? Samsung Galaxy S10e running Android 9
* Fenix version: ? 190905

**Comment by softvision-miralobontiu** [comment]
Verified as fixed on RC 2.0.0-rc.2 with Samsung Galaxy Tab S3 (Android 8), and OnePlus 5T (Android 9).
