### ISSUE TITLE
[Bug] org.mozilla.appservices dependencies do not appear in list of OSS libraries

### ISSUE THREAD

**Issue by rfk** [mozilla-mobile/fenix#5147]
### Steps to reproduce

* Go to settings -> "About Firefox Preview" -> "Open source libraries we use"
* Scroll down the list to find libraries in the "org.mozilla.*" namespace

### Expected behavior

I see either no Mozilla-published components (because we don't consider them third-party code) or all of the Mozilla-published components in the dependency tree.

### Actual behavior

There are a small number Mozilla-published libraries, such as "org.mozilla.components:browser-engine-gecko-beta".  But there are many other dependencies that do not appear in this list, such as "org.mozilla.appservices:fxaclient".

### Device information

* Fenix version: Nightly 190904 18:02 (Build #12471814)

### Additional info

I see the same behaviour when building Fenix locally.

If I look in `./app/build/generated/third_party_licenses/dependencies.json` I see only the same small subset of Mozilla-published libraries. So I guess the `oss-licenses-plugin` is not finding the rest, or is filtering them out.

Any tips on how I could get the "org.mozilla.appservices" dependencies included in the list?

**Comment by rfk** [comment]
Ah, interesting, if I add one of our components as `geckoNightlyImplementation` rather than just `implementation` then it gets included in the list of OSS dependencies. Like this:

```
diff --git a/app/build.gradle b/app/build.gradle
index 71f61a46..47183366 100644
--- a/app/build.gradle
+++ b/app/build.gradle
@@ -326,6 +326,7 @@ dependencies {
 
     geckoNightlyImplementation Deps.mozilla_browser_engine_gecko_nightly
     geckoBetaImplementation Deps.mozilla_browser_engine_gecko_beta
+    geckoNightlyImplementation Deps.mozilla_service_firefox_accounts
 
     implementation Deps.kotlin_stdlib
     implementation Deps.kotlin_coroutines
```

**Comment by ekager** [comment]
CC @colintheshots could you help here?

**Comment by boek** [comment]
#5536

**Comment by mcarare** [comment]
This seems to have been fixed. QA for confirmation. Thank you!

**Comment by sflorean** [comment]
Verified as fixed on Nightly 9/28.
