### ISSUE TITLE
Switch to playing tab when clicking on media notification

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/fenix#5148]
Follow-up feature request from #2551:

> is it possible to send people to the tab where the audio/video is coming from when they tap on the notification? atm we just open the latest tab people where on.

The following change is coming to AC and we can start integrating it into Fenix:
* Issue: https://github.com/mozilla-mobile/android-components/issues/4244
* PR: https://github.com/mozilla-mobile/android-components/pull/4333

When the media notification is clicked we invoke the [launch intent for the app](https://developer.android.com/reference/android/content/pm/PackageManager#getLaunchIntentForPackage(java.lang.String)). After the change above lands we additionally set the following values on the `Intent`:
* action = `MediaFeature.ACTION_SWITCH_TAB` (value = `mozac.feature.media.SWITCH_TAB`)
* extra for the tab id: `MediaFeature.EXTRA_TAB_ID` (value = `mozac.feature.media.TAB_ID`)

In the launch activity we need to handle this intent coming in via `onCreate()` and via `onNewIntent()` (if the activity is already being displayed).

**Comment by ekager** [comment]
Reopening for QA

**Comment by sflorean** [comment]
Verified as fixed on Nightly 6/12 and 6/11 with the following devices:
- Samsung Galaxy Note 10 (Android 10)
- LG G7 FIT (Android 8)
- Huawei MediaPad M2 (Android 5.1.1)
