### ISSUE TITLE
[Bug] Media keeps playing in the background when the app is killed

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#5151]
## Steps to reproduce
1. Go to leparisien.fr, rockfm.ro or other media websites and play a video/audio stream.
2. Kill the app from the task tray.
### Expected behavior
Media playback stops.
### Actual behavior
Media playback continues. 
### Device information

* Android device: Pixel (Android 10), Galaxy Note 8 (Android 9), HTC Desire 820 (Android 6.0.1)
* Fenix version: Nightly 9/6

**Comment by pocmo** [comment]
Oh, I did this kind of purpose (since you can go back to the app via the notification) - but I see how other browsers (Chrome) will stop playback and remove the notification.

@topotropic Can you confirm that the desired UX behavior is to stop and remove the notification?

**Comment by pocmo** [comment]
Tentatively filed in AC: https://github.com/mozilla-mobile/android-components/issues/4335

**Comment by topotropic** [comment]
Yes, if the app is killed please remove the notification and stop the audio

**Comment by pocmo** [comment]
Thanks! Nominated the AC issue for our triage to work on that in the next sprint.

**Comment by pocmo** [comment]
A patch for this landed in AC and should start rolling out with the next 14.0.0-SNAPSHOT builds.

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on Nightly Build #12621819 from 19/9 using the following devices:
• Google Pixel 3a (Android 9)
• Samsung Galaxy Note 9 (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

Check websites:
► Rockfm.ro
► Soundcloud.com
