### ISSUE TITLE
copy and paste shortcuts on url input

### ISSUE THREAD

**Issue by nahuhh** [mozilla-mobile/fenix#5152]
### Why/User Benefit/User Problem
Simplify copy and pasting urls
### What/Requirements
Add buttons to the url input screen (see screenshot)
### Acceptance Criteria (how do I know when I’m done?)
Something like this: 
![Screenshot_20190906-081050](https://user-images.githubusercontent.com/50635951/64426993-10edfe00-d07e-11e9-8d76-70c2bd720e35.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-13307)

**Comment by ekager** [comment]
We are adding these actions to long pressing the toolbar in #4155. Will those make your experience better? :)

**Comment by nahuhh** [comment]
@ekager 
#4155 is now closed and it looks like that implementation only works when the url bar is at the bottom (ie, doesn't work on the url input page in my mockup) 

So yes, while #4155 was a nice addition, I think this is an even more efficient workflow (with the buttons right above the keyboard) 

If adding, note that "copy" should hidden in instances where the url bar is empty (specifically "tab page > url bar" and "menu > new tab/newprivatetab" ) 
And that the keyboard needs to close after pressing "paste and go"

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813149

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
