### ISSUE TITLE
[Feature Request] Menu closes when selecting on screen forward button 

### ISSUE THREAD

**Issue by nahuhh** [mozilla-mobile/fenix#5153]
## Steps to reproduce
Open menu
Select forward

### Expected behavior
The menu should remain open - to perform multiple forward requests

### Actual behavior
The menu closes after you make your selection 

### Device information
BlackBerry KeyOne 
* Android device: ? 8.1.0 
* Fenix version: ? Nightly 190905 12:42 (Build #12481253)
📦: 12.0.0, 62ec2845b
🦎: 71.0a1-20190904094319

**Comment by cadeyrn** [comment]
I disagree, your proposed behaviour would be totally annoying for me. And neither the old Firefox nor Chrome does what you suggest.

**Comment by nahuhh** [comment]
How do you go forward on your device? I find it super annoying 

I could live with it only remaining open during forward presses

**Comment by TitanNano** [comment]
Going back more than one page should be handled with the history sheet, which already has a bug [here](https://github.com/mozilla-mobile/fenix/issues/3514).

**Comment by nahuhh** [comment]
@titannano
According to that issue, android q +the device back button or lackthereof makes the implementation different

They suggest long pressing the on screen, in menu back button to bring up recent history of the current tab

I still think a forward press shouldnt minimize the menu. I *may* have been overreaching by including back, stop and refresh.
