### ISSUE TITLE
"save link as..." in context menu

### ISSUE THREAD

**Issue by nahuhh** [mozilla-mobile/fenix#5155]
### Why/User Benefit/User Problem
Chrome, Firefox etc all include an option to "save link as" or "download link" when long pressing on a link.

### What/Requirements
Add the feature to Fenix.

### Acceptance Criteria (how do I know when I’m done?)
I believe "download link" should be available when you tap hold on any link. 
Neither of these options should discriminate against file type etc. 

These options should save the page/file to hard drive

I'm going to post another request that may be required for this to work 
#349
A ui for the downloader (within menu > library) where you can view current and past downloads, along with the ability to pause/resume/cancel

**Comment by yoasif** [comment]
This was asked on the Firefox sub-reddit here: https://www.reddit.com/r/firefox/comments/e7c6qc/hey_im_still_curious_as_to_why_firefox_didnt_show/

There is good STR provided:

1. Navigate to https://player.fm/series/heavyweight/ep-29-elyse
2. Long press on "MP3"

Expected result:

"Download link" option that downloads the MP3 to disk.  This option is missing in Fenix and Fennec. 

This is also documented on Chrome's help pages: https://support.google.com/chrome/answer/95759?co=GENIE.Platform%3DAndroid&hl=en

**Comment by NotWoods** [comment]
Since we already have #219 I'm going to edit the issue to just focus on "Save link as".

**Comment by s-ankur** [comment]
Hi we have this feature now

**Comment by Amejia481** [comment]
@s-ankur thanks!
