### ISSUE TITLE
Additional user options for blocking autoplay

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/fenix#5163]
### User Story
As a user, I want to be able to disable autoplay for audio or both video and audio on my browser depending on whether on I am on wifi or mobile data, so I can save data and battery and have control over how I consume content.

### Acceptance Criteria
- I can choose to allow autoplay for video and audio on WiFi only
- I can choose to block audio autoplay only
- I can choose to block both video and audio (Recommended) 
- When autoplay is disabled, audio and video content will not start playing unless I have initiated it.

https://share.goabstract.com/cdba1651-670e-4412-8721-4d70ca025ffd?collectionLayerId=35603d5c-263c-4c70-b3fe-1ae23bd449c8&mode=design

### Dependencies:
https://bugzilla.mozilla.org/show_bug.cgi?id=1577596

**Comment by Iey4iej3** [comment]
I second this and I wish that muted autoplay could also be manually disabled. It is important when the Internet fee is proportional to the data usage.

**Comment by cpeterso** [comment]
GV will need some Gecko changes to support these autoplay options. Randall is coordinating with the Gecko Media team.

**Comment by Djfe** [comment]
I would love it too, if this got implemented.
You can use this API for the Android setting and to see whether the user is on a metered network (even wifi SSIDs can be marked as metered nowadays):
https://developer.android.com/training/basics/network-ops/data-saver

This is essentially the same bug as #255

**Comment by fluffyemily** [comment]
GV issue resolved on 19th December

**Comment by vesta0** [comment]
@ekager I think this may be done, could you confirm?

**Comment by ekager** [comment]
The only remaining work I can find for this ticket is to add the first radio button "Allow audio and video" and as far as I can tell that is blocked on https://bugzilla.mozilla.org/show_bug.cgi?id=1621825
Do we still care about that, @vesta0 ?

**Comment by vesta0** [comment]
@ekager yes I do but it's not a high priority. I updated the acceptance criteria and created #10464 for the remaining option so we can circle back to it later. I also added `eng:qa:needed` to this issue.

Looking at the mocks, remind me did we decide not to implement the doorhanger UI for permissions and autoplay?

**Comment by softvision-miralobontiu** [comment]
Hi all,

I've verified that the user can select any of the following options: to allow autoplay for video and audio on WiFi only, to block audio autoplay only, and to block both video and audio.

However, I've filed #10485 because the first option is deselected once the user exits the Autoplay page. @vesta, should I leave this issue open until this is fixed?
I'll remove the qa-needed for now.

Thanks!

**Comment by vesta0** [comment]
Yes please. #10485 means that this feature is not done.

**Comment by vesta0** [comment]
@ekager looking at the mocks, remind me did we decide not to implement the doorhanger UI for permissions and autoplay?

**Comment by ValentinTimisica** [comment]
@vesta0 should we close this since #10485 was verified as fixed? Is there anything left to do on this ticket?

**Comment by liuche** [comment]
@ekager did we have the video/audio controls in the toolbar bottom sheet?

![Screen Shot 2020-06-04 at 7 35 46 PM](https://user-images.githubusercontent.com/1082253/83830715-a9abbb80-a69a-11ea-84df-7adacead3f49.png)

**Comment by ekager** [comment]
No this was never added to the quick settings sheet because we don't currently control this on a site by site basis AFAICT.

**Comment by ekager** [comment]
cc @Amejia481 do you maybe remember if that was the reason we didn't add this to the quick settings?

**Comment by Amejia481** [comment]
As you mentioned, right now we don't have API on AC to support that feature. To do so, we need new APIs to notify Fenix when a site is requesting auto-play permissions, and let it control what to do with the request.

**Comment by vesta0** [comment]
Closing this issue and filed a follow up here: #11325 11325
