### ISSUE TITLE
[Bug] Private session notification discrepancies

### ISSUE THREAD

**Issue by mikeGolf08** [mozilla-mobile/fenix#5164]
## Steps to reproduce

1. Open any website
2. Open a link in private tab
(**Case 1**) 3. Click on "Open" in the notification
(**Case 2**) 3. Click on "Delete and Open" in the notification

### Expected behavior

**Case 1** It opens the private session and shows the tab.
**Case 2** It stays on the website I am currently at

### Actual behavior

**Case 1** It does not open the private tab and stays on current website.
**Case 2** It closes the private session, deletes the tab but goes to "tab list" instead of staying on website. (->Misleading translation "Delete and **Open**" - I think there is no intention to open an empty private session at that moment)

### Device information

* Android device: Android 9 Oxygen OS 9.0.5 on OnePlus 3T (A3003)
* Fenix version: Nightly 190906 18:03 (Build #12491815)
package: 12.0.0, 65df8e8a0
lizard: 71.0a1-20190905094317

**Comment by Brandon-Davison** [comment]
Could I take a look at this?

**Comment by ekager** [comment]
I think this is more of a UX feedback issue than a bug? I believe those are the intended behaviors currently

**Comment by mikeGolf08** [comment]
> I think this is more of a UX feedback issue than a bug? I believe those are the intended behaviors currently

You're right - will change header.

**Comment by lime124** [comment]
@AmyYLee to follow up when she's back from PTO. thanks!

**Comment by AmyYLee** [comment]
@ekager Hi, yes this is the intended behavior. We are providing 2 options for the user. Open (opens the app in it's current state). Erase and Open (Erases opened tabs and shows homescreen). This provides privacy for the user if they don't want to show their last opened tabs upon opening the app.

**Comment by mikeGolf08** [comment]
> @ekager Hi, yes this is the intended behavior. We are providing 2 options for the user. Open (opens the app in it's current state). Erase and Open (Erases opened tabs and shows homescreen). This provides privacy for the user if they don't want to show their last opened tabs upon opening the app.

This makes sense - closing the ticket now.
