### ISSUE TITLE
widget should search for local apps

### ISSUE THREAD

**Issue by Sdaswani** [mozilla-mobile/fenix#5167]
### Why/User Benefit/User Problem
The home screen widget is awesome but it only searches the web. It would benefit the user if it also surfaces local apps. Not doing so makes it harder to switch from the default Google widget.

### What/Requirements
The widget should also show results from your local apps.

### Acceptance Criteria (how do I know when I’m done?)
The widget will search and surface results from the users local apps.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-13314)

**Comment by boek** [comment]
This has not revived any duplicates or other interactions since it was filed. We will not be moving this request to Bugzilla.
