### ISSUE TITLE
Menu item or other ui to take users to Bugzilla so that they can create a report

### ISSUE THREAD

**Issue by hildjj** [mozilla-mobile/fenix#5168]
## Steps to reproduce
I would like to file a bug in Firefox Preview. 

### Expected behavior
There is a button to click on in the UI that brings me here. 

### Actual behavior
Asa had to give me a link to get here. 

### Device information
N/A

* Android device: ?
* Fenix version: ?

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-13315)

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813151

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
