### ISSUE TITLE
[Bug] Custom tab Open in Firefox Preview url bar bug

### ISSUE THREAD

**Issue by neekless** [mozilla-mobile/fenix#5169]
## Steps to reproduce
1. Open a link in a custom tab. Settings > Privacy notice used in this example.
2. Tap 3 dots > Open in Firefox Preview.

### Expected behavior
The url bar should have the correct information.

### Actual behavior
There is no url in the url bar and the lock icon is wrong. Tapping the bar shows the correct url for editing but go back and the url is missing again. Even after navigating to a different page the url is still missing. Please see attached video.
https://drive.google.com/open?id=1dYN4nGLZGeDjGMOfS5zaJz0jDwW_AciA

### Device information

* Android device: Pixel 2xl android 9
* Fenix version: Nightly 190907 18:04 (Build #12501814)
📦: 12.0.0, f5158da6d
🦎: 71.0a1-20190906094324

**Comment by sblatz** [comment]
I just encountered this as well. Agreed that this is a P1 as it has security risks.

**Comment by ekager** [comment]
This is in AC - see @pocmo 's [comment here](https://github.com/mozilla-mobile/fenix/issues/5025#issuecomment-529507738)
> I can reproduce this in Reference Browser and assume that this is related to our `feature-toolbar` refactoring that has happened just recently. I filed the following AC issue to track that:
> [mozilla-mobile/android-components#4348](https://github.com/mozilla-mobile/android-components/issues/4348)

**Comment by ekager** [comment]
This should be fixed with the first build with 13.0.0-SNAPSHOT from AC

**Comment by ekager** [comment]
For QA - that build should be our next nightly build

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest Nightly Build #12590611 from 16/9 using the following devices:
• Google Pixel 3a (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• OnePlus A3 (Android 6.0.1)
