### ISSUE TITLE
[Bug]Find in page makes the QAB buttons visible 

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#5174]
## Steps to reproduce
1. Navigate to any webpage 
2. From the 3dot menu button tap on "Find in page"
3. Observe the QAB

### Expected behavior
QAB is fully closed the buttons aren't visible

### Actual behavior
QAB is crack open making the buttons partially visible

### Device information

* Android device: 
• Google Pixel 3a (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

* Fenix version: Nightly Build #12520610 from 9/9

### Notes
Quite similar with [#2245](https://github.com/mozilla-mobile/fenix/issues/2245)

►Video
![20190909_171309](https://user-images.githubusercontent.com/51314259/64540399-d1970a00-d328-11e9-946f-fa0296b70325.gif)

**Comment by ekager** [comment]
We could probably hide the QAB while the user is using FIP

**Comment by AndiAJ** [comment]
Hi, verified as fixed on Nightly Build #12621819 from 19/9 using the following devices:
• Google Pixel 3a (Android 9)
• Samsung Galaxy Note 9 (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

►Video
![20190920_144713](https://user-images.githubusercontent.com/51314259/65324793-e50e6480-dbb5-11e9-8ff1-28166370303e.gif)
