### ISSUE TITLE
[Bug] Home screen shows "No Title" when Fenix is playing a video

### ISSUE THREAD

**Issue by mozillamarcia** [mozilla-mobile/fenix#5177]
## Steps to reproduce
* Load Fenix and play a video from nfl.com. 
* A speaker icon shows in the device status bar indicating media is playing
* Press the device power button to show the notification screen

### Expected behavior
* Something should show which indicates there is active media playing. Fennec, for example, displays a Firefox icon

### Actual behavior
* "No title" shows below the active device time, but there is no Fenix icon.

### Device information

* Android device: Pixel 3 running Android 10
* Fenix version: 1.4.0

**Comment by ekager** [comment]
Filed https://github.com/mozilla-mobile/android-components/issues/4431

**Comment by pocmo** [comment]
Fixed in AC 15.0.0.

**Comment by pocmo** [comment]
Fixed in latest Nightly.

**Comment by sv-ohorvath** [comment]
Verified as fixed on master 10/7. Devices: Pixel (android Q), Pixel (android 9)
