### ISSUE TITLE
[Bug] options for clearing user data are truncated

### ISSUE THREAD

**Issue by cadeyrn** [mozilla-mobile/fenix#5178]
### Steps to reproduce

open the new screen for clearing the user data

### Expected behavior

no truncated options

### Actual behavior

truncated options.

![Screenshot_20190909-215146](https://user-images.githubusercontent.com/1100614/64562089-78d96880-d34c-11e9-8a0b-b18b9afd832e.png)

(And maybe the checkboxes should be aligned with the back arrow?)

### Device information

* Android device: HTC U11 / Android 9.0
* Fenix version: master branch revision 4c2a7ac10e33305bcb71fd33c03a7ed7ae3921ef

**Comment by sv-ohorvath** [comment]
This is only fixed in Nightly 9/13. The new options are not yet visible in 2.0.0-rc2
Devices verified: Pixel (Android 9), Nokia 6 (Android 7.1.1)
