### ISSUE TITLE
Add an option to configure disk cache size

### ISSUE THREAD

**Issue by birdie-github** [mozilla-mobile/fenix#5179]
### Why/User Benefit/User Problem

For security reasons it's often inadvisable to have a disk cache enabled since it leaves traces which can be easily sniffed out. It would be great to have an option to configure its size or disable it completely by setting disk cache size to 0.

If we had about:config it would be trivial to configure but #2778 is closed and there's no way to do that manually.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-13325)

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813153

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
