### ISSUE TITLE
Can't enter Your Library a second time 

### ISSUE THREAD

**Issue by Cheap-Skate** [mozilla-mobile/fenix#518]
1. View page content in Fenix
2. Tap 3 dot Settings menu in toolbar
3. Tap Your Library
4. Quit by pressing X top right
Repeat steps 2 and 3
Can't get into Your Library - this is not expected behavior
Expected behavior: can always enter Your Library.

**Comment by Cheap-Skate** [comment]
I think same is true with other menu items eg Settings. 
PS sorry about formatting/indenting above!

**Comment by colintheshots** [comment]
I guess #541 is technically the duplicate, but I'll close this bug as I already fixed that one.
