### ISSUE TITLE
Remove fretboard to improve startup performance

### ISSUE THREAD

**Issue by hawkinsw** [mozilla-mobile/fenix#5182]
`ExperimentsInternalAPI.initialize` and `FenixApplication.loadExperiments` are called from within the `FenixApplication.SetupApplication` function. `SetupApplication` takes 290ms and the two experiment-related functions take 45ms (approximately 15%).

There are also StrictMode violations that come from loading experiments on the main thread.

It would appear that we have regressed somehow from #1616 where we moved experiment loading off the main thread. I'm not sure if this was intentional, but we need to look at it.

**Comment by hawkinsw** [comment]
@csadilek or @colintheshots Can you add the eng:performance label to this? Thank you!

**Comment by colintheshots** [comment]
I was looking at fixing this by removing Fretboard in favor of our new services-experiements framework to do less work. However, I believe the new services-experiments A-C code is not ready. As written, the new library code appears to statically load only a single experiment at one time within the call to `Experiments.initialize()`. If we cannot support multiple experiments with services-experiments, this performance fix is not possible. In fact, the new library seems fundamentally flawed in its implementation.

Instead, I could maybe look at using Fretboard exclusively until the new library is fixed. As for migrating work to a background thread, I need to be sure experiments have reasonable defaults if experiments have not yet been loaded.

**Comment by colintheshots** [comment]
At a minimum, we should probably remove Fretboard. FxA is the last consumer and it's no longer being used to host any experiments.

**Comment by mcomella** [comment]
@colintheshots Are there any next steps here or can this be closed?

**Comment by colintheshots** [comment]
Fretboard was removed. We should file a new issue if `Experiments.initialize` needs optimizations as well.

**Comment by mcomella** [comment]
Addressed in https://github.com/mozilla-mobile/fenix/pull/7510.

**Comment by mcomella** [comment]
@Baron-Severin Would you mind writing a QA note for this issue? I assume we should at least test that the FxA features are enabled/disabled properly. tbh, I'm a little confused about the phrasing of the landed code – `Disabled = false` – so I wonder if there's a bug lurking there.

**Comment by Baron-Severin** [comment]
> @Baron-Severin Would you mind writing a QA note for this issue? 

Note to whoever from QA picks this up, would you mind verifying that App Services web channels, login sync, and pairing still work as they did previously?

> tbh, I'm a little confused about the phrasing of the landed code – `Disabled = false` – so I wonder if there's a bug lurking there.

Agreed that the names are a bit misleading, but I'm less concerned about bugs there as the properties were moved from an existing file (`Experiments.kt`), and they haven't otherwise changed.

**Comment by sv-ohorvath** [comment]
Done some testing around signup, login, sync and pairing and haven't noticed anything suspicious. I'll mark this as verified.
