### ISSUE TITLE
Initializing megazord in application start is slow

### ISSUE THREAD

**Issue by hawkinsw** [mozilla-mobile/fenix#5183]
`setupMegazord()` being called from `FenixApplication.setupApplication` blocks startup and is slow. `FenixApplication.setupApplication` takes 290ms and `setupMegazord` itself takes 43ms (14.8%)

Within `setupMegazord`, `RustHttpConfig.setClient` is _the_ slow function. I have worked with a-c in the past on this issue and I _think_ that they already have a solution -- we will just need to incorporate it. See PR https://github.com/mozilla-mobile/fenix/pull/4391

**Comment by mcomella** [comment]
@hawkinsw It looks like this merged: should this issue be closed?

**Comment by hawkinsw** [comment]
Code merged.
