### ISSUE TITLE
Add DNS over HTTPS option for fenix browser.

### ISSUE THREAD

**Issue by stevenleeS0ht** [mozilla-mobile/fenix#5185]
### Why/User Benefit/User Problem

Protecting privacy. 
Be consistent with Firefox for desktop.

### What/Requirements

add option for DNS over HTTPS (DoH).

### Acceptance Criteria (how do I know when I’m done?)

providing an option in system preference -> general. (Same as firefox for desktop).

**Comment by cadeyrn** [comment]
Duplicate of #4584.
