### ISSUE TITLE
[Bug] "Open in App" opens Chrome from Amazon.com

### ISSUE THREAD

**Issue by topotropic** [mozilla-mobile/fenix#5187]
## Steps to reproduce
Go to Amazon.com, pull up QAB, tap on "Open in App"

### Expected behavior
When Amazon app is installed, open in app; when app is not installed hide option to "Open in App"

### Actual behavior
Amazon.com opens in Chrome

### Device information

* Android device: ?
* Fenix version: ?

**Comment by softvision-miralobontiu** [comment]
I was able to reproduce this issue with instagram.com on the latest Nightly from 9/10 using HTC 10 (Android 8).
I've enabled the "Open links in apps" from Settings - Advanced, opened instagram.com, signed in, tapped on a link and I was redirected to Chrome.

**Comment by topotropic** [comment]
This is fixed.
