### ISSUE TITLE
Add "Search for selected text" to context menu

### ISSUE THREAD

**Issue by crabel** [mozilla-mobile/fenix#5188]
### Why/User Benefit/User Problem
It is a very common usecase for me to search for terms I find on webpages. Currently I have to select the text, copy it and paste it into the address bar or a search box.

I believe that it would be a really useful feature to be able to search directly.

### Acceptance Criteria (how do I know when I’m done?)
The user selects a text and the context menu shows a menu entry "search for ...". Clicking the menu entry opens a new tab (same tab?) with the url of the search provider. The selected text is used as the search term.

**Comment by Brandon-Davison** [comment]
Could I work on this?

**Comment by Lululalu** [comment]
I believe it's the same as #5695

**Comment by NotWoods** [comment]
Yup, duplicate of #5695
