### ISSUE TITLE
[Telemetry] Expired `search_counts` metric

### ISSUE THREAD

**Issue by Dexterp37** [mozilla-mobile/fenix#5189]
This is not a feature request.

We noticed that [a few metrics](https://github.com/mozilla-mobile/fenix/blob/16115f57d1decd8bd492d415fa53fe0af4ff72ab/app/metrics.yaml#L360-L408) have expired as of September the 1st. `search_count` is among them.

**Comment by boek** [comment]
fixed with https://github.com/mozilla-mobile/fenix/commit/215e66fb080f75a7965ba430ad17fc1f31c1b5a3
