### ISSUE TITLE
[Telemetry] Media controls

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/fenix#5197]
#### Description & Product Manager / Data Scientist User Story
As a product owner, I want to know how often users are interacting with media controls in the browser. 

#### Hypothesis
We believe this feature is useful to users, and successful when it is addressing user needs. 

#### What questions will you answer with this data?
How often users interact with media controls?

#### Why does Mozilla need to answer these questions? Are there benefits for users? Do we need this information to address product or business requirements?
This helps us learn a few things:
- Usefulness of media controls
- How often users use the browser to play media? This helps us prioritize media related bugs and features?
- How often users have multiple open tabs playing media

#### What probes (suggested, if applicable)
- Pause/Play interaction on each tab
- Pause/Play interaction on the notification

### Acceptance Criteria (Added by PM)
- Event pings can be queried via re:dash
- We are sending telemetry events for the actions listed in the requirements
- We have documented the telemetry
- We have asked a data steward to [review](https://github.com/mozilla/data-review/blob/master/request.md) the telemetry
- NOT an AC: Data science to create dashboard or further graphs (this will be a separate issue, this issue is only about hooking up the events described and that they can be queried in re-dash)

**Comment by pocmo** [comment]
I'm about to put up a PR with the following `Fact`s being emitted from the component:

| Action | Item            |  Description                              |
|--------|-----------------|-------------------------------------------|
| PLAY   | state           | Media started playing.                    |
| PAUSE  | state           | Media playback was paused.                |
| STOP   | state           | Media playback has ended.                 |
| PLAY   | notification    | Play action of notification was invoked   |
| PAUSE  | notification    | Pause action of notification was invoked  |

**Comment by sblatz** [comment]
Thanks @pocmo! Please tag me for review on that so I get notified when it's merged and can implement in Fenix.

**Comment by sblatz** [comment]
I will add these events as soon as they land in the snapshot 😄

**Comment by abodea** [comment]
As the [v2.1.0-rc.1](https://github.com/mozilla-mobile/fenix/releases/tag/v2.1.0-rc.1) couldn't be installed, I used a build from [taskcluster](https://tools.taskcluster.net/index/project.mobile.fenix.v2.production/latest).
#### Please note the following:

| Action | Item            |  Description                              | Works?  |
|--------|-----------------|-------------------------------------------|------|
| PLAY   | state           | Media started playing.                    |       ❌     |
| PAUSE  | state           | Media playback was paused.                |     ❌    |
| STOP   | state           | Media playback has ended.                 |     ❌      |
| PLAY   | notification    | Play action of notification was invoked   |     ✅   |
| PAUSE  | notification    | Pause action of notification was invoked  |     ✅ |

Note that I was able to trigger the Event pings only for the notification bar.
For the Play, Pause, Stop I couldn't trigger the events. 
@sblatz the events should trigger if I Play / Pause any video from YouTube right? 
Is the `item: Notification` referring to the media control bar?
Is the `item: State` referring when I play/pause a video in normal browsing on YT for example?
Also, note that I tried for the stop, to let a video until it disappears and after that to trigger the event but with 0 success.
##### Note the following:
```Kotlin 
{
      "events": [
        {
          "timestamp": 0,
          "category": "media_notification",
          "name": "pause"
        },
        {
          "timestamp": 1085,
          "category": "media_notification",
          "name": "play"
        }
      ],
      "ping_info": {
        "ping_type": "events",
        "seq": 8,
        "start_time": "2019-09-30T08:34-04:00",
        "end_time": "2019-09-30T08:36-04:00"
      },
      "client_info": {
        "telemetry_sdk_build": "14.0.1",
        "first_run_date": "2019-09-30-04:00",
        "os": "Android",
        "android_sdk_version": "28",
        "os_version": "9",
        "device_manufacturer": "Google",
        "device_model": "Pixel 3a XL",
        "architecture": "arm64-v8a",
        "app_channel": "release",
        "app_build": "12701924",
        "app_display_version": "Unknown",
        "client_id": "9d29dbf9-a19c-482e-aec7-b528ba3db822"
      }
    }
Second event 
{
      "events": [
        {
          "timestamp": 0,
          "category": "media_notification",
          "name": "pause"
        },
        {
          "timestamp": 853,
          "category": "media_notification",
          "name": "play"
        },
        {
          "timestamp": 1620,
          "category": "media_notification",
          "name": "pause"
        },
        {
          "timestamp": 2337,
          "category": "media_notification",
          "name": "play"
        }
      ],
      "ping_info": {
        "ping_type": "events",
        "seq": 5,
        "start_time": "2019-09-30T08:30-04:00",
        "end_time": "2019-09-30T08:31-04:00"
      },
      "client_info": {
        "telemetry_sdk_build": "14.0.1",
        "first_run_date": "2019-09-30-04:00",
        "os": "Android",
        "android_sdk_version": "28",
        "os_version": "9",
        "device_manufacturer": "Google",
        "device_model": "Pixel 3a XL",
        "architecture": "arm64-v8a",
        "app_channel": "release",
        "app_build": "12701924",
        "app_display_version": "Unknown",
        "client_id": "9d29dbf9-a19c-482e-aec7-b528ba3db822"
      }
    }

**Comment by sblatz** [comment]
@vesta0 do you care to track the following telemetry events?

| Action | Item            |  Description                              | Works?  |
|--------|-----------------|-------------------------------------------|------|
| PLAY   | state           | Media started playing.                    |       ❌     |
| PAUSE  | state           | Media playback was paused.                |     ❌    |
| STOP   | state           | Media playback has ended.                 |     ❌      |

I intentionally did not record them, but we have hooks if you think they're necessary. We have events for the user pressing the play/pause button on both the tab and the media notification which was the original acceptance criteria for this ticket :)

**Comment by abodea** [comment]
@sblatz also, if you can tell me `STOP` should be also present for the media notification?
I can say for example open media notification and let a video until the end, the notification will disappear, in this case we should have the `media notification` stop?

**Comment by sblatz** [comment]
@abodea I intentionally do not track that right now :) 

Going to see if Vesta wants that or not 😄

**Comment by abodea** [comment]
Oh, ok thank you @sblatz.

**Comment by vesta0** [comment]
@sblatz we don't need the other probes at this time, thanks for checking!

**Comment by sblatz** [comment]
@abodea I think this can be closed then. Please re-open if you disagree 😄

**Comment by pocmo** [comment]
Just FYI: I added those `fact`s to answer this question:
> How often users use the browser to play media? This helps us prioritize media related bugs and features?
The `state` ones will be the only ones that tell you that someone is playing/pausing/stopping media in ALL cases.

**Comment by vesta0** [comment]
Great point @pocmo :) Since Autoplay is supposed to be by default, I figured we can measure how often users use the browser to play media by how often they interact with the media controls. But I see what you mean about media usage in general. I think it's a good idea to add those. I will create another issue for it @sblatz
