### ISSUE TITLE
Setup testing track on Google Play

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/fenix#52]
Build, sign and upload Nightly builds to Google Play testing track.

**Comment by pocmo** [comment]
This should build and upload:
* nightlyArmRelease
* nightlyAarch64Release
* nightlyX86Release

**Comment by JohanLorenzo** [comment]
That's also tracked at https://bugzilla.mozilla.org/show_bug.cgi?id=1478220

**Comment by pocmo** [comment]
> What Google Play track would you like to use, @pocmo? The custom one "nightly", like the one we have on Focus?

Yeah, exactly the same setup like Focus Nightly (with access via google group).
