### ISSUE TITLE
Crash when there is no internet connection

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#520]
[connectionerror-logcat.txt](https://github.com/mozilla-mobile/fenix/files/2869226/connectionerror-logcat.txt)
## Steps to reproduce
1. Turn off the internet connection.
2. Open Fenix and tap the search bar, start typing.
### Expected behavior
Can type in a URL and get a Connection error page.
### Actual behavior
App crashes.
### Device information

* Android device: HTC 10 (Android 8.0)
* Fenix version: 1.0

**Comment by pocmo** [comment]
```
 E  Process: org.mozilla.fenix, PID: 8203
 E  org.mozilla.geckoview.WebRequestError: Request failed, error=37, category=5
 E      at org.mozilla.gecko.mozglue.GeckoLoader.nativeRun(Native Method)
 E      at org.mozilla.gecko.GeckoThread.run(GeckoThread.java:81)
```

That's for AC to pick up.

**Comment by ekager** [comment]
AC closed this in https://github.com/mozilla-mobile/android-components/issues/2086 so it should be resolved with newest builds with AC

**Comment by ekager** [comment]
Closing, this seems to be resolved in master now

**Comment by sv-ohorvath** [comment]
Fix confirmed on the latest build.
