### ISSUE TITLE
[Bug] Build Instruction in README is out-of-date

### ISSUE THREAD

**Issue by orionlee** [mozilla-mobile/fenix#5200]
The build instruction in `README` is out-of-date
- `./gradlew clean app:assembleArmDebug` - task `app:assembleArmDebug` no longer exists
- build variant instruction for Android Studio is similarly outdated
- it'd be nice to call out Android NDK is required, in addition to SDK

The following is a strawman changes to build instructions, with open issues marked with _OPEN_

## Build Instructions

Note: Both Android SDK **and NDK** are required.

1. Clone or Download the repository:

  ```shell
  git clone https://github.com/mozilla-mobile/fenix
  ```

2. Import the project into Android Studio **or** build on the command line:

  ```shell
  # OPEN: For newbie to the project should it use app:assembleDebug, app:assembleGeckoBetaDebug, or app:assembleGeckoNightlyDebug
  ./gradlew clean app:assembleDebug
  ```

3. Make sure to select the correct build variant in Android Studio:
**geckoNightlyDebug** for app module (_OPEN:_ or should it be geckoBetaDebug)

**Comment by sblatz** [comment]
@colintheshots should this actually be in the done column?
