### ISSUE TITLE
Browser behaviour when tapping on a homescreen icon multiple times

### ISSUE THREAD

**Issue by grigoryk** [mozilla-mobile/fenix#5201]
## Steps to reproduce
Add a website to home screen. Tap on the home screen item multiple times.

### Expected behavior
Tapping on the home screen item opens the existing session (tab) for that item, if it exists, and creates a new tab otherwise.

### Actual behavior
A new tab is always created.

**Comment by grigoryk** [comment]
https://sentry.prod.mozaws.net/operations/fenix-nightly/issues/6248916/ here we see a user OOMing with 55mb of session data. The current behaviour could definitely contribute to these kinds of crashes.

**Comment by ekager** [comment]
What does it mean to have an existing session (tab) for that item? If the user has navigated at all would that mean it's no longer the same tab?

**Comment by grigoryk** [comment]
That's right, yeah. I think that's a reasonable iterative improvement though. E.g. it probably won't work great for something like the angry orange website, but would work quite well for homescreened weather websites, for example.

**Comment by NotWoods** [comment]
I think it'd be good to have UX weigh in here. 

Current behavior is that tapping a website shortcut on the home screen opens a new tab 100% of the time.

Suggested behavior is that tapping a website shortcut will re-use a tab with the exact same URL, if present. Otherwise a new tab is opened.

**Comment by brampitoyo** [comment]
@NotWoods your suggestion sounds great:

> [T]apping a website shortcut will re-use a tab with the exact same URL, if present.
> 
> Otherwise a new tab is opened.

Let’s go with that.

**Comment by mcarare** [comment]
waiting on https://github.com/mozilla-mobile/android-components/issues/6399

**Comment by liuche** [comment]
Closed by https://github.com/mozilla-mobile/android-components/pull/7054
