### ISSUE TITLE
[Bug] Selection Handlers are low in responsiveness

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/fenix#5204]
## Steps to reproduce
-Open a site that contains text
-Long press to select/highlight part of the text
-Try to move the selection handlers to expand or narrow down the selection 

### Expected behavior
-Selection handlers are responsive

### Actual behavior
-Selection handlers are jumpy

### Device information

* Android device: Pixel 3
* Fenix version: Latest nightly

**Comment by ekager** [comment]
Dupe of #5037
