### ISSUE TITLE
[Bug] Opening a tab that was saved to a collection should restore the history as well

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#5208]
## Steps to reproduce
This is a regression, the initial functionality was added in #3215.
Same STR.
### Expected behavior
When restoring a tab with history, you can navigate back/forward to previously visited pages.
### Actual behavior
Can't navigate back/forward in the restored tab from a collection.
### Device information

* Android device: Pixel (Android 10)
* Fenix version: RC 1.4.1, Nightly 9/11

**Comment by obarzpaw** [comment]
I would like to do some investigation.

**Comment by darkwing** [comment]
Can confirm this is still a problem.

**Comment by ekager** [comment]
Filed https://github.com/mozilla-mobile/android-components/issues/5529

**Comment by topotropic** [comment]
@ekager is the AC part done here?

**Comment by Diana-Rus** [comment]
Hi, issue fixed verified on Firefox Preview Nightly 200327 (Build #20870627) GV: 76.0a1-20200325093457 with:
- Google Pixel 3 XL (Android 9) ✔️
GIF:
![20200327-111620](https://user-images.githubusercontent.com/49859863/77741108-03e62b80-701d-11ea-9c60-9652436597de.gif)
- Samsung Galaxy S9 (Android 8) ✔️
- Sony Xperia Z5 (Android 7) ✔️
