### ISSUE TITLE
[Bug] Black edit button on bookmarks multi-selection toolbar

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#5213]
## Steps to reproduce
1. Go to bookmarks.
2. Long tap a bookmarked page.
3. Observe the edit button in the multi-selection toolbar.
### Expected behavior
The button is visible.
### Actual behavior
The button is not visible due to its color (black).
### Device information

Android device: Pixel (Android Q), Pixel 3 (Android 9), Sony Xperia Z5 Premium (Android 7.1.1)
Fenix version: RC 1.4.1, Nightly 9/10

**Comment by sv-ohorvath** [comment]
This is still reproducing on Nightly 9/28 and RC 2.1.0.

**Comment by sv-ohorvath** [comment]
note: The other buttons are also black during the rest of the edit flow: the delete button, add folder button, save folder.

**Comment by sv-ohorvath** [comment]
> note: The other buttons are also black during the rest of the edit flow: the delete button, add folder button, save folder.

@NotWoods Once you tap the edit button, the rest of the buttons in the toolbar are still black. Would you prefer a new issue for that or could you fix those in this one as well?

**Comment by NotWoods** [comment]
I'd prefer a new issue because the toolbar color should change, rather than the icon color

**Comment by sv-ohorvath** [comment]
Ok, I've created #5848 for the rest.
