### ISSUE TITLE
[Bug] GradleException – Cannot find a version of 'androidx.test:core' that satisfies the version constraints

### ISSUE THREAD

**Issue by AaronMT** [mozilla-mobile/fenix#5217]
Master (4485b7f6475218149fdd0eb3f4a676849005f513) (geckoNightlyDebug)

On attempt to run UI tests:

```Caused by: org.gradle.internal.resolve.ModuleVersionResolveException: Could not resolve androidx.test:core:1.2.1-alpha02.```

```Caused by: org.gradle.api.GradleException: Cannot find a version of 'androidx.test:core' that satisfies the version constraints: 
   Dependency path 'fenix:app:unspecified' --> 'androidx.test:core:1.2.1-alpha02'
   Constraint path 'fenix:app:unspecified' --> 'androidx.test:core:{strictly 1.1.0}' because of the following reason: geckoNightlyDebugRuntimeClasspath uses version 1.1.0
   Dependency path 'fenix:app:unspecified' --> 'androidx.fragment:fragment-testing:1.2.0-alpha02' --> 'androidx.test:core:1.1.0'```

**Comment by AaronMT** [comment]
(@rpappalax, @npark-mozilla) do you see this too?

**Comment by AaronMT** [comment]
Possibly: 

https://github.com/android/android-test/issues/294#issuecomment-506994394

```
implementation ("androidx.fragment:fragment-testing:1.1.0-beta01",         
   exclude group: 'androidx.test', module: 'core'
})
```

_Originally posted by @cheskos in https://github.com/android/android-test/issues/294#issuecomment-506994394_

**Comment by rpappalax** [comment]
> (@rpappalax, @npark-mozilla) do you see this too?

yep
