### ISSUE TITLE
[Bug] Tracking protection is not working

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#5218]
## Steps to reproduce
- Visit rottentomatoes.com

### Expected behavior
No banner ad

### Actual behavior
Banner ad

### Device information

* Android device: pixel 2
* Fenix version: Nightly 190910

**Comment by Amejia481** [comment]
@mcomella could we close this?

**Comment by ekager** [comment]
I'm going to close this because we should be back on Strict now.

**Comment by Amejia481** [comment]
👍
