### ISSUE TITLE
[Bug] YouTube website not recognize for open in app

### ISSUE THREAD

**Issue by nahuhh** [mozilla-mobile/fenix#5222]
## Steps to reproduce
- go to https://docs.google.com/spreadsheets/d/12-NAoBPPV_nNBqaY1vt7Gke8bthPYqnG0tMLeSDrIKI/htmlview
- scroll to the right where there are YouTube links
- click on a YouTube link
- slide open drawer where you find share, bookmark etc  

### Expected behavior
Open in app should be there as well, and should work
### Actual behavior

On the final YouTube page, "Open in app" is not there and if it is it either tries to open Google sheets or does nothing at all

Going to the website directly or switching tabs makes it work. 

### Device information

* Android device: BlackBerry KeyOne 
* Fenix version: Nightly 190910 18:03 (Build #12531808)
📦: 12.0.0, 9fecd17d3
🦎: 71.0a1-20190909095540

**Comment by nahuhh** [comment]
Give me a second. Those steps aren't reproducible

**Comment by nahuhh** [comment]
The issue seems to be that somewhere during the redirects, fenix "open in app" feature failed to notice the change in url, which is why Iasasume it is stil trying to open the previous page in Google sheets. Ie, it seems that itis reading the old url from memory, instead of the current url on demand

I think this could be fixed by changing it to read the url on demand.
(I also think the "open in app" button should be persistent. Fenix shouldn't have to do any backend checks to see if there are associations before offering the button. The button should be shown on every website and when you press it,  THEN you should be shown a list of available apps.)

**Comment by NotWoods** [comment]
With the updated open in app system this may work now.

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **Nightly Build #13570608 from 12/23** using the following devices:

• Google Pixel 3a (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

► Video
![20191223_115746](https://user-images.githubusercontent.com/51314259/71351489-7659f200-257c-11ea-93b0-c3003f975137.gif)
