### ISSUE TITLE
[Bug] Should not add tracking protection exception while in Private Mode

### ISSUE THREAD

**Issue by nahuhh** [mozilla-mobile/fenix#5227]
## Steps to reproduce
1. Go to a website in private mode
2. Turn off tracking 
3. Close private mode

### Expected behavior
Private tracking exception should not be stored in the browser settings
### Actual behavior
It is 
### Device information

* Android device: BlackBerry KeyOne 8.1.0 
* Fenix version: Nightly 190910 18:03 (Build #12531808)
📦: 12.0.0, 9fecd17d3
🦎: 71.0a1-20190909095540

**Comment by topotropic** [comment]
@AmyYLee can you have a look? Thanks!

**Comment by AmyYLee** [comment]
Hi, I agree it shouldn't store ETP exceptions when in Private browsing and the user switches to non-private and goes to the same site. We should treat whatever choice the user makes for ETP as separate between Private and Non-private. If the user turns off ETP in private mode for a site, we remember that choice until the user quits the browser.

**Comment by sblatz** [comment]
Per conversation in group triage, let's also verify as part of this ticket that **other permissions** are not shared (camera, location, etc.) from private -> normal mode.

**Comment by eamsen** [comment]
This is not reproducing with GV 74. GV should be consistent with desktop behavior on this, if not, please file a GV bug.

**Comment by ekager** [comment]
thanks @eamsen let's have QA verify and then close this :)

**Comment by sv-sdeiac** [comment]
Verified as fixed using the latest version of Firefox Preview Nightly 2/7 #20380605.

Devices:
- Huawei Honor 8 (Android 7.0);
- Samsung Galaxy S8 (Android 9).
