### ISSUE TITLE
[Bug] visual issues with new tracking protection panel

### ISSUE THREAD

**Issue by cadeyrn** [mozilla-mobile/fenix#5228]
### Steps to reproduce

1. open a website
2. press the shield icon

### Expected behavior

no issues with tracking protection panel.

### Actual behavior

Panel appears in the middle of the screen with truncated content. After interacting the panel moves to the bottom and hides the address bar.

![Screenshot_20190911-213417](https://user-images.githubusercontent.com/1100614/64729129-cb498f00-d4dc-11e9-8d7d-359b2c1024ed.png)
![Screenshot_20190911-214001](https://user-images.githubusercontent.com/1100614/64729177-e3211300-d4dc-11e9-8e15-fb34dddc6873.png)

### Device information

* Android device: HTC U11 with Android 9.0
* Fenix version: Master branch revision bafbea1512f36b7c8771bf865ac234d8e411e608

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on Nightly Build #12621819 from 19/9 using the following devices:
• Google Pixel 3a (Android 9)
• Samsung Galaxy Note 9 (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

►Video
![20190920_153151](https://user-images.githubusercontent.com/51314259/65327482-ba73da00-dbbc-11e9-8cb9-395caf78f1aa.gif)
