### ISSUE TITLE
[Bug] new tracking protection panel can't be closed with back button

### ISSUE THREAD

**Issue by cadeyrn** [mozilla-mobile/fenix#5229]
### Steps to reproduce

1. open a website
2. press the shield icon
3. press the back button of your device

### Expected behavior

Tracking protection panel closes.

### Actual behavior

Tracking protection panel stays open. For comparison: The panel which appears after pressing the lock icon can be closed with the back button.

### Device information

* Android device: HTC U11 with Android 9.0
* Fenix version: Master branch revision bafbea1512f36b7c8771bf865ac234d8e411e608

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on Nightly Build #12621819 from 19/9 using the following devices:
• Google Pixel 3a (Android 9)
• Samsung Galaxy Note 9 (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

►Video
![20190920_153810](https://user-images.githubusercontent.com/51314259/65327624-25bdac00-dbbd-11e9-9162-e873e822a528.gif)
