### ISSUE TITLE
Multitasking is unpressable after HOME button and reopen

### ISSUE THREAD

**Issue by colintheshots** [mozilla-mobile/fenix#523]
## Steps to reproduce
1. Open a new browser session and return to the Fenix home screen.
2. Press the Home soft button on the device to return to the Android home.
3. Reopen Fenix to its home screen.

### Expected behavior
The tab buttons should be interactable.

### Actual behavior
The tab buttons are not interactable.

### Device information

* Android device: Samsung Galaxy S8, Oreo
* Fenix version: Latest Master, Built Friday 2/15 @ 10:42 AM

**Comment by colintheshots** [comment]
This is a regression I caused by trying to aggressively free memory by disposing subscriptions earlier. I'm going to back out the change.

**Comment by sv-ohorvath** [comment]
Verified as fixed.
