### ISSUE TITLE
[Bug] (regression) options for clearing user data are not display properly

### ISSUE THREAD

**Issue by cadeyrn** [mozilla-mobile/fenix#5230]
### Steps to reproduce

1. open the new screen for clearing the user data

### Expected behavior

looks good. ;-)

### Actual behavior

![Screenshot_20190911-213755](https://user-images.githubusercontent.com/1100614/64729562-ad305e80-d4dd-11e9-9e2f-d39eb620cd19.png)

### Device information

* Android device: HTC U11 with Android 9.0
* Fenix version: Master branch revision bafbea1512f36b7c8771bf865ac234d8e411e608

**Comment by ekager** [comment]
Should be fixed by #5247

**Comment by ekager** [comment]
I'm just going to keep #5178 open because it's a similar issue
