### ISSUE TITLE
[Bug] private browsing shortcut changes state of default shortcut

### ISSUE THREAD

**Issue by cadeyrn** [mozilla-mobile/fenix#5232]
### Steps to reproduce

1. add private browsing shortcut to home screen
2. press the regular shortcut and make sure you are *not* in private mode
3. go back to the Android home screen and press the private browsing shortcut
4. go back to the Android home screen and press the regular shortcut

### Expected behavior

Fenix opens in regular mode. If the private browsing shortcut changes the state of the regular shortcut there is no reason to have separate shortcuts.

### Actual behavior

Fenix opens in private mode.

### Device information

* Android device: HTC U11 with Android 9.0
* Fenix version: Master branch revision bafbea1512f36b7c8771bf865ac234d8e411e608

**Comment by klint** [comment]
I agree with this. It makes the private shortcut quite hard to use as there is no easy way to go back to non-private mode after using the private shortcut.

**Comment by mcarare** [comment]
Could not reproduce this. Can QA please check if this is still reproducible?

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **Nightly Build #13300628 from 11/26** using the following devices:
• Google Pixel 3a XL (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

► Video
![20191126_113015](https://user-images.githubusercontent.com/51314259/69617324-b642bd80-1040-11ea-8845-f65d6a87c7ae.gif)
