### ISSUE TITLE
remove "add private browsing shortcut" from settings if already on home screen

### ISSUE THREAD

**Issue by cadeyrn** [mozilla-mobile/fenix#5233]
I don't know if it's possible at all. But after adding a private browsing shortcut to the Android home screen there is no longer a need to have the "add private browsing shortcut" item in the settings. It's a item you use once and for all but it stays permanently visible on the first level of the settings.

**Comment by bswe** [comment]
I don't think the "Add private browsing shortcut" should be thought of as a "once and for all" operation.  If the user happens to delete the shortcut (either intentionally or by accident) there would be no way to add it back if the entry in the settings is removed.

**Comment by NotWoods** [comment]
Agreed, uit should only be hidden if we detect that the shortcut present on the homescreen.

**Comment by cadeyrn** [comment]
> I don't think the "Add private browsing shortcut" should be thought of as a "once and for all" operation. If the user happens to delete the shortcut (either intentionally or by accident) there would be no way to add it back if the item in the settings is removed.

well, this is totally clear, that why I didn't mention it explicitly. Of course the menu item has to reappear if there the shortcut will be removed. ;-)

**Comment by bswe** [comment]
Sounds like we agree then that it isn't an "item you use once and for all".

**Comment by cadeyrn** [comment]
Sorry, that's splitting hairs…

**Comment by bswe** [comment]
Clarity in describing a feature is essential and necessary, and not "splitting hairs" at all.   My original comment did contribute usefully to clarifying what needed to be implemented for this issue.  Your follow up comment was not necessary and sounded rather defensive and dismissive.

**Comment by bswe** [comment]
Just noticed that the PrivateShortcutCreateManager method gets called within both SettingsFragment and HomeFragment, so it seems like the fix for the settings menu should be added to the home also.

I would be happy to take on implementing this feature.

**Comment by bswe** [comment]
Tiger,

 

I implemented this new feature, but as you pointed out the use of the
getPinnedShortcuts method required API 25.  I had to bumped the
minSdkVersion  from 21 to 25 in Config.kt and build.gradle to get it to
compile.
 
Is there a better way to handle this more localized to the new code.  Maybe
only doing the check for the shortcut if firefox is running on API 25 or
later?
 
    Thanks, Bill

**Comment by NotWoods** [comment]
Hi Bill, as you mentioned you can just check if the shortcut is present in API 25 and above. You can see examples of this where we have `if` statements checking the `SDK_INT` field compared to a constant version number.

**Comment by olsenme** [comment]
My name is Meagan, and I am applying for outreachy.Has anyone been assigned this issue?

**Comment by olsenme** [comment]
@cadeyrn

**Comment by NotWoods** [comment]
Hi Meagan, bwse has already been assigned to this issue. 

Here are some other issues that we need help with:
- #5366 
- #4556
- [more](https://github.com/mozilla-mobile/fenix/issues?q=is%3Aopen+label%3A%22help+wanted%22+sort%3Aupdated-desc+no%3Aassignee)

**Comment by olsenme** [comment]
Thanks so much @NotWoods

**Comment by bswe** [comment]
Tiger,

 

I submitted PR #5775 to close issue #5233.  I wasn't sure how to add a
reviewer to the PR, or if that should be you or not.

 

    Thanks, Bill

 

  _____  


 
<https://home.mcafee.com/utm_medium=email&utm_source=link&utm_campaign=sig-e
mail&utm_content=emailclient?utm_medium=email&utm_source=link&utm_campaign=s
ig-email&utm_content=emailclient>
https://secureimages.mcafee.com/common/affiliateImages/mfe/logo.png

Scanned by McAfee
<https://home.mcafee.com/utm_medium=email&utm_source=link&utm_campaign=sig-e
mail&utm_content=emailclient?utm_medium=email&utm_source=link&utm_campaign=s
ig-email&utm_content=emailclient>  and confirmed virus-free.
