### ISSUE TITLE
SelectableItemBackground does not work properly with play/pause button

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#5242]
The play/pause button showing on tabs has a weird issue where the selectableItemBackground does not display over the favicon (it displays under it) even though the elevation is set on the play/pause button. It's possible this is an android library bug.

https://github.com/mozilla-mobile/fenix/pull/5165

![image](https://user-images.githubusercontent.com/4400286/64740880-9ffa7c00-d4ab-11e9-8ec8-dd0d17580bb0.png)

**Comment by boek** [comment]
This will be fixed with #1063
