### ISSUE TITLE
[Bug] Toolbar Tracking Protection Icon looks strange in custom tabs

### ISSUE THREAD

**Issue by ekager** [mozilla-mobile/fenix#5250]
![Screenshot_20190911-183536](https://user-images.githubusercontent.com/25442310/64747433-e0fe8a80-d4c3-11e9-9ed0-db4ba5aab36a.png)

## Steps to reproduce
Open page in custom tab from Gmail with ETP on

### Expected behavior
I'm actually not sure. Should we just show a static TP icon while in a custom tab with no animation? Probably? 

### Actual behavior
Can't see TP icon depending on the app which custom tab was opened from 

### Device information

* Android device: ?
* Fenix version: ?

**Comment by Amejia481** [comment]
This is fixed in ac https://github.com/mozilla-mobile/android-components/pull/4456 as soon as the new snapshot is available it will be on Fenix

**Comment by NotWoods** [comment]
Should be working now since that was two AC versions ago.

**Comment by abodea** [comment]
Verified as fixed using the latest Nightly build **`10/15(build #12880607)`**.
