### ISSUE TITLE
[Bug]Transition to PB isn't made after sharing a page from normal to private browsing 

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#5254]
## Steps to reproduce
1. Navigate to any webpage
2. From the QAB tap on Share
3. Select "Firefox Preview (Private)"![rsz_screenshot_20190912-104555_fireaaaaaaaaaaaaaaaaaaaaafox_preaaaaview](https://user-images.githubusercontent.com/51314259/64771328-74cd6680-d557-11e9-8c86-a3bdb45e3738.jpg)

### Expected behavior
After sharing the transition to Private Browsing should be made

### Actual behavior
No transition to PB, the user remains in Normal browsing

### Device information

* Android device: Samsung Galaxy Tab A (Android 9)
* Fenix version: 2.0.0-cr.2 (Build #12550444)

### Notes
Similar with #5033 & #4772 

►Video
![20190912_104814 (1)](https://user-images.githubusercontent.com/51314259/64771591-ea393700-d557-11e9-8464-13848f95da55.gif)

**Comment by softvision-miralobontiu** [comment]
This issue might be related: [5375](https://github.com/mozilla-mobile/fenix/issues/5375).

**Comment by abodea** [comment]
Verified as fixed on the **Fenix v2.0.0-rc3** using `OnePlus 6T(Android 9), Samsung Galaxy S10+(Android 9), Google Pixel 3a (Android 9), Google Nexus 7 II(Android 5.1.1), OnePlus 3(Android 6.0.1).`
