### ISSUE TITLE
[Bug] The mic/camera indicators should be removed when a temporary permission is blocked

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#5256]
## Steps to reproduce
1. Go to permission.site
2. Tap the camera / mic, allow it to run, but don't check "Don't ask again".
3. Observe the cam/mic indicator in the status bar.
4. Tap the cam/ mic button again. Select Deny this time.
5. Observe the cam/mic indicator in the status bar.
### Expected behavior
The cam/mic running indicator should be hidden when the permission is blocked, without refreshing the page.
### Actual behavior
The cam/mic running indicator is not hidden without refreshing the page.
### Device information

* Android device: Sony Xperia Z5 Premium (Android 7.1.1)
* Fenix version: 2.0-rc2

**Comment by vesta0** [comment]
Chatted with Arturo, he will investigate and determine whether this is A-C

**Comment by Amejia481** [comment]
This is a GeckoView bug I filed a bug on Bugzilla for it
https://bugzilla.mozilla.org/show_bug.cgi?id=1609779

**Comment by fluffyemily** [comment]
Attached Bugzilla bug closed as invalid. Please see [comment #2](https://bugzilla.mozilla.org/show_bug.cgi?id=1609779#c2) for explanation and [comment #3](https://bugzilla.mozilla.org/show_bug.cgi?id=1609779#c3) for recommendations.

**Comment by Amejia481** [comment]
Requires https://github.com/mozilla-mobile/android-components/issues/6173
