### ISSUE TITLE
[Bug] Send tab - reconnect actions: After you remove the account, redirect to the tab

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#5258]
## Steps to reproduce
1. Connect with the same account on Fenix and on desktop.
2. Change the password on desktop.
3. Load a tab, open the Send & Share  overlay.
4. Tap the Reconnect to sync message.
5. Tap remove account.
### Expected behavior
Disconnects the account and returns to the tab.
### Actual behavior
Disconnects the account but stays on the same "reconnect to sync" view.
### Device information

* Android device: Sony Xperia Z5 Premium (Android 7.1.1), Samsung Galaxy Tab S3 (Android 8)
* Fenix version: 2.0-rc2

**Comment by sblatz** [comment]
@ekager looks like this was filed against #2897. Are you able to take a look? 😄

**Comment by sv-ohorvath** [comment]
Verified as fixed on Nightly 9/19.
