### ISSUE TITLE
Search bar does not always show current URL, sometimes it ? uses a favorite from History ?

### ISSUE THREAD

**Issue by Cheap-Skate** [mozilla-mobile/fenix#526]
https://www.bbc.co.uk/news is a favorite of mine

If I navigate to https://www.bbc.co.uk [without /news] then I tap the URL bar to eg do a search, the search bar appears but https://www.bbc.co.uk/news appears in the search bar.

The same occurs with reddit:- I most frequently look at https://www.reddit.com/r/firefox  but if I am on the homepage https://www.reddit.com and tap the URL bar, I get ... /r/firefox in the searchbar not the homepage.

Sometimes the whole URL in the searchbar is a single color, sometimes the suffix /news is purple while the rest is green.

I think Fenix is autocompleting in the search bar based on my top sites.  But I find it confusing.

Expected behavior (I think???):- the URL in the search bar should always exactly match the URL in the URL bar at the moment I tapped it.

**Comment by pocmo** [comment]
I think that is a bug in AC where we perform autocomplete before the user starts typing.

> https://www.bbc.co.uk
> https://www.bbc.co.uk/news

In this situation is the first URL selected and the "/news" part colored as autocomplete suggestion?

**Comment by Cheap-Skate** [comment]
Sounds plausible

BBC:
Tap www.bbc.co.uk in toolbar. In search bar, for a fraction of a second the /news has purple background (autocomplete?) but then it all changes to pale green and stays that way.

reddit:
Starting with www.reddit.com. Similar but it ends up with www.reddit.com/r/ with green background but firefox/ has purple background.

**Comment by vesta0** [comment]
I believe this has been fixed. @sv-ohorvath please verify.

**Comment by sv-ohorvath** [comment]
I caught this twice as described. Doesn't happen frequently.
Devices: Nexus 5(Android 6), Huawei P20 lite (Android 8):
![Screenshot_20190404-170115](https://user-images.githubusercontent.com/4037709/55562213-2a200680-56fc-11e9-8527-bddf65936dae.jpg)

On Nexus 5, following after what is described here,
1. Replace the suggestion with your own text.
2. Clear the entire url and type something new.
This happens:

![20190404_173652](https://user-images.githubusercontent.com/4037709/55564710-2b9ffd80-5701-11e9-8688-aafe76680c86.gif)

*the issue only happens in this case. If you go to reddit.com home. Then add to the url: /r/ (wait for a suggestion to autocomplete here), then do the steps described, it won't reproduce.

**Comment by kbrosnan** [comment]
Going to close this. Cheap-skate if you are still seeing this please comment and we can reopen.
