### ISSUE TITLE
Fennec migration: push subscriptions

### ISSUE THREAD

**Issue by grigoryk** [mozilla-mobile/fenix#5260]
Either carry them over, or re-register anything pertinent. We're currently lacking WebPush support in Fenix, so that's a thorn we need to deal with somehow.

**Comment by jonalmeida** [comment]
> re-register anything pertinent.

We should consider that when we migrate push subscriptions. We notify the consumers that the subscription has changed. 

It seems, from offline conversations, that FxA servers are capable of handling the registration renewals.

However, we will also have push subscriptions from web content (e.g. facebook, reddit, etc.) where we would be re-registering (autopush), and notifying all those sites via GeckoView that the push subscription changed ([`onpushsubscriptionchange`](https://developer.mozilla.org/en-US/docs/Web/API/ServiceWorkerGlobalScope/onpushsubscriptionchange)).

Which would mean `fennec users` x `number of webpush subscriptions` would all go through the AutoPush servers and the site's servers. This could end up DDOS-ing our and their servers.

What would be nice, is if we could bulk import the Fennec subscriptions (which are written to disk that we can read from), and validate them on device with the minimal amount of subscription changes that are needed (`PushManager.verifyConnection()`?).

> We're currently lacking WebPush support in Fenix, so that's a thorn we need to deal with somehow.

WebPush support is landing soon™ (before migration takes place), so this should be a valid concern.

**Comment by st3fan** [comment]
@jonalmeida is https://github.com/mozilla/application-services/issues/2048 a dependency for this bug?

**Comment by jonalmeida** [comment]
> @jonalmeida is [mozilla/application-services#2048](https://github.com/mozilla/application-services/issues/2048) a dependency for this bug?

@st3fan Yes, this is the a-c equivalent for the a-s work.

**Comment by jdragojevic** [comment]
@grigoryk @jonalmeida @st3fan @vesta0  - Lina added a pretty detailed comment regarding the complexity involved in migrating the push notifications here: https://github.com/mozilla/application-services/issues/2048#issuecomment-572798531

We may want to consider passing on this and letting the users start fresh and resubscribe.  It could potentially turn out to be a boost to our retention???

![image](https://user-images.githubusercontent.com/299270/72112635-1f8a4180-330c-11ea-9857-14d43fd7c27b.png)
ref: http://info.localytics.com/blog/push-notification-survey-2018

**Comment by grigoryk** [comment]
Closing this as WONTFIX. Added a note to our board to validate that re-subscription happens.

**Comment by ebalazs-sv** [comment]
This was closed as WONTFIX, so I will move it to Done. Thanks!
