### ISSUE TITLE
[Bug] Opening TP Settings from Custom Tab and then clicking learn more crashes app

### ISSUE THREAD

**Issue by ekager** [mozilla-mobile/fenix#5263]
## Steps to reproduce
1. Open a custom tab
2. Click on TP icon
3. Click on Settings
4. Click on learn more

### Expected behavior
Can't get to settings from custom tab

### Actual behavior
App crashes

### Device information

* Android device: ?
* Fenix version: ?

**Comment by softvision-miralobontiu** [comment]
Verified that the link to Settings is no longer displayed in the ETP panel in custom tab.
Tested on the latest Nightly build 190919 (#12621819) with Nexus 9 tablet (Android 7.1.1), and Xiaomi Mi 8 Lite (Android 9).
