### ISSUE TITLE
[Bug] Grey text on delete browsing data on quit pref

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#5270]
<img width="492" alt="image" src="https://user-images.githubusercontent.com/4400286/64810833-fff72e00-d550-11e9-8c6f-f5caa4fe87a4.png">

**Comment by softvision-miralobontiu** [comment]
Verified as fixed on the latest Nightly build 190919 (#12621819) with Nexus 9 tablet (Android 7.1.1), and Xiaomi Mi 8 Lite (Android 9).
