### ISSUE TITLE
[Bug] Delete all browsing data text

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#5277]
## Steps to reproduce
1. Open "delete browsing data" setting
2. Select some options but not all
3. Press "delete browsing data

### Expected behavior
1. Popup confirms you want to delete the **selected** data

### Actual behavior
1. Popup confirms you want to delete **all** of your browsing data

<img width="350" alt="image" src="https://user-images.githubusercontent.com/4400286/64819781-e6131680-d563-11e9-95ee-c9c1472a411b.png">

**Comment by jpfaller** [comment]
This is the string we'd aligned to in the Invision

<img width="243" alt="Screen Shot 2019-09-13 at 9 24 30 AM" src="https://user-images.githubusercontent.com/50755458/64870163-63906280-d608-11e9-84c5-ad9f88dc8f45.png">

**Comment by AndiAJ** [comment]
Hi, verified as fixed on Nightly Build #12621819 from 19/9 using the following devices:
• Google Pixel 3a (Android 9)
• Samsung Galaxy Note 9 (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

► Pic
![rsz_screenshot_20190920-143004](https://user-images.githubusercontent.com/51314259/65324113-eccd0980-dbb3-11e9-91ec-b57c2d15da52.png)
