### ISSUE TITLE
[Bug] Deletion on quit renders app is not responding message

### ISSUE THREAD

**Issue by mikeGolf08** [mozilla-mobile/fenix#5279]
## Steps to reproduce

//Make sure you have many bookmarks on your Firefox-Account

1. Complete reinstall of Fenix (Clear storage before uninstall app)
2. Launch Fenix
3. Sign-in for sync
4. Go to settings
5. Setup deletion of browsing data on quit
6. Verify that the sync has finished and there is a high number of browsing history (entries depend on number of bookmarks)
7. Open a website
8. Click on menu dots
9. Click on quit

### Expected behavior

**Option 1** Regardless of browsing data Fenix closes and will delete in background ... I think that isn't possible due to Android limitations because Firefox Mobile Stable is always closing AFTER deletion is complete (message is visible before closure for a very short time)

**Option 2** Fenix will close after deletion is complete without triggering the Android "App is not responding" message

### Actual behavior

Because of the high number of browsing history entries which are caused by the synced bookmarks it takes such a long time as to render Android's "App is not responding message"

### Device information

* Android device: Android 9 on OnePlus 3T (A3003) Oxygen OS 9.0.5
* Fenix version: 
Nightly 190912 11:48 (Build #12551154)
package: 13.0.0, f5ab632eb
lizard: 71.0a1-20190910095613

**Tied with #3863 No awesomebar completion after updating**

**Comment by softvision-miralobontiu** [comment]
Verified as fixed on the latest Nightly build 190919 (#12621819) with Nexus 9 tablet (Android 7.1.1), and Xiaomi Mi 8 Lite (Android 9).
