### ISSUE TITLE
Improve ETP Panel Lists of Trackers, Align with Desktop

### ISSUE THREAD

**Issue by ekager** [mozilla-mobile/fenix#5281]
Debug/Nightly currently has the new ETP panel with lists of trackers blocked behind a feature flag. 

We will have better reporting of these lists (aligned with desktop) with 
https://bugzilla.mozilla.org/show_bug.cgi?id=1580201

**Comment by sv-ohorvath** [comment]
@ekager Not really sure what there is to test here, as far as I can understand the change involves only some lists of trackers. Is there anything that should stand out?

**Comment by ekager** [comment]
Good point. Closing :)
