### ISSUE TITLE
[Bug] Cold Startup time regression on 2019-09-06

### ISSUE THREAD

**Issue by cpeterso** [mozilla-mobile/fenix#5285]
On either 2019-09-05 or 2019-09-06, Fenix's Cold Startup time (on Nimbledroid's Nexus 5 test devices) regressed from 1.5 to 2.63 seconds:

![image](https://user-images.githubusercontent.com/629193/64830095-cab80380-d583-11e9-8593-94784bfbf5e9.png)

https://health.graphics/android

Did Fenix update from GV 69 to GV 70 Beta at that time? We no longer have Cold Startup test results for GeckoView Example, Reference Browser, or Chrome, so it's hard to say whether this is a regression in Fenix, GV, or the test runner.

**Comment by mcomella** [comment]
Triage: closing. We believe this regression was a one-off issue – potentially bustage in the ND heuristic – and don't feel it's still an issue. If it comes up again, we can revisit.
