### ISSUE TITLE
media.autoplay.default value is reset[Bug]

### ISSUE THREAD

**Issue by gbil** [mozilla-mobile/fenix#5288]
## Steps to reproduce
In about:config change the media.autoplay.default value to something other than 0

### Expected behavior
After restarting Firefox preview the value should stay as other changed about:config values do

### Actual behavior
The value is reset to 0 whenever the app is restarted

### Device information
Samsung s10e

* Android device: 9
* Fenix version: latest from play store

**Comment by lindongbin** [comment]
#7322

**Comment by kbrosnan** [comment]
Closing as a duplicate
