### ISSUE TITLE
[Bug]Shortcut search options flicker when populting the search bar

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#5289]
## Steps to reproduce
1. Tap on the search bar
2. Select the Shortcuts button
3. Input in the search bar

### Expected behavior
No UI issues

### Actual behavior
The Shortcut suggestions are flickering

### Device information

* Android device: Samsung Galaxy Tab A (Android 9)
* Fenix version: 2.0.0-rc.2

### Notes
Seems to be a regresion off [#3622](https://github.com/mozilla-mobile/fenix/issues/3622)
►Video 
![20190913_090654](https://user-images.githubusercontent.com/51314259/64841979-5c1d8900-d609-11e9-993f-10b397121d0f.gif)

**Comment by boek** [comment]
I believe this has been fixed.. Please re-open if you can reproduce

**Comment by AndiAJ** [comment]
Hi @boek , since [#6018](https://github.com/mozilla-mobile/fenix/issues/6018) the STR isn't valid anymore, just re-checked this matter on the latest **Nightly Build #13640626 from 12/30** using a Google Pixel 3a (Android 9)
