### ISSUE TITLE
[Bug] The same page appears in the History section multiple times

### ISSUE THREAD

**Issue by LaurentiuApahideanSV** [mozilla-mobile/fenix#5298]
## Steps to reproduce
1. Open the same page multiple times;
2. Go to Your Library -> History.
### Expected behavior
The page that was opened multiple times should only show up once in the History section.
### Actual behavior
The same page appears in the History section multiple times.
### Device information

* Android device: Samsung galaxy S8+ (Android 8.0.0)
* Fenix version: 2.0.0-rc.2 9/12
![Screenshot_20190913-140632_Firefox Preview](https://user-images.githubusercontent.com/50983519/64858509-496a7a80-d630-11e9-87b6-792997acc30b.jpg)

**Comment by nahuhh** [comment]
Confirmed on Nightly 190912 20:44 (Build #12552054)
📦: 13.0.0, ccf305cea
🦎: 71.0a1-20190910095613

**Comment by SubhrajyotiSen** [comment]
@sv-ohorvath What would be the approach for this? Show unique items by default or have a toggle for that?

**Comment by sv-ohorvath** [comment]
@vesta0 would be more suitable to answer this.

**Comment by ekager** [comment]
When we redid history with pagination we must have clipped this fix. See
https://github.com/mozilla-mobile/fenix/pull/4122 for previous solution

**Comment by vesta0** [comment]
@ekager can we add it back in?

**Comment by boek** [comment]
@vesta0 no, not easily. We will probably need this filtered from application services.

**Comment by codrut-topliceanu** [comment]
@ekager @boek Hey, do we have a decision on how we should proceed here?

**Comment by softvision-miralobontiu** [comment]
This is reproducible on Beta 5.2.0-beta.1 using Samsung Galaxy Tab S6 (Android 9).

**Comment by softvision-miralobontiu** [comment]
I was able to reproduce this issue on 83.0.0-beta 1 build with Samsung Galaxy Tab S6 (Android 10).

**Comment by ebalazs-sv** [comment]
This issue is reproducible on Beta 88.0.0-beta.1 with Samsung Galaxy Tab S3 (Android 8).

**Comment by lobontiumira** [comment]
Reproducible on Beta 89.0.0-beta.1 with Samsung Galaxy Note 8 (Android 9).

**Comment by Amejia481** [comment]
This should be available in the next nightly @LaurentiuApahideanSV could you please help us to verify? Thanks in advance!

**Comment by LaurentiuApahideanSV** [comment]
I tested the issue on the latest Firefox Preview Nightly 2021-11-24 and found the following:
If the same link is opened several times after a fresh install after deleting all history it will still appear multiple times in the history section (see attached screenshot bellow). If the same link is accessed multiple times using it's full URL (pasting from clipboard, tapping on a bookmark or top site) it will not create duplicates, however if the link is accessed by using the name of the site it will appear multiple times in the history (see attached video below).
![history (2)](https://user-images.githubusercontent.com/50983519/143230905-dd337d1b-f1cd-4f6e-9f9c-62ab3e0d2a6f.JPEG)


https://user-images.githubusercontent.com/50983519/143230911-2bf5fad8-c912-49df-b4e7-cd4361039b5f.mp4


### Devices used:
- Oppo Find X3 (Android 11)
- OnePlus 6T (Android 9)

**Comment by Amejia481** [comment]
👋🏽 thank for testing @LaurentiuApahideanSV.

#### Duplicate items at the end of the list. If users have an empty history and navigate to the same site multiple times we are unable to de duplicate the items in the history page.

This is a known edge case, that we think it's acceptable, as most of the user wont hit it. **Other items that are not at the end of the list will be de-duplicate.** 

In the video, shown above sites are different as the protocol is different **HTTPS** VS **HTTP**.

![image](https://user-images.githubusercontent.com/773158/143256241-e766284b-a9d4-4feb-abda-cda24a616436.png)

**Comment by Amejia481** [comment]
@LaurentiuApahideanSV are items that are not the last one on the list de-duplicated ? If so I think we can close the ticket, as will be fixing almost all duplicates except for this edge case.

**Comment by LaurentiuApahideanSV** [comment]
Considering  that the websites at the end of the list are considered and edge case and the different protocol issue is caused by https://github.com/mozilla-mobile/fenix/issues/14172 I will mark this issue as closed.
