### ISSUE TITLE
[Bug] Fenix doesn't render Korean bold font properly.

### ISSUE THREAD

**Issue by ted1117** [mozilla-mobile/fenix#5299]
## Steps to reproduce
1. Enter any website that includes bold texts.
[Mozilla Korean forum](http://forums.mozilla.or.kr/viewtopic.php?p=49374#p49374) 
### Expected behavior
render Korean bold font nicely.
### Actual behavior
Bold texts look pretty rough. It just makes normal font bold.
Top: Samsung Internet Beta
Bottom: Fenix
![Screenshot_20190913-200009](https://user-images.githubusercontent.com/24566481/64858172-9581e300-d661-11e9-85cb-f4eac3ebe9ba.jpg)

![Screenshot_20190913-200000](https://user-images.githubusercontent.com/24566481/64858486-83547480-d662-11e9-9cc6-03a38945614f.jpg)

### Device information
* Android device: Google Pixel 3 (Android10)
* Fenix version: Nightly 190912 20:44 (Build #12552054)

**Comment by boek** [comment]
@ted1117 Is this still an issue for you?

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly Build #200619 from 6/19`** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)

► Video
![20200619-143656](https://user-images.githubusercontent.com/51314259/85128881-d20aec80-b23a-11ea-9e8a-b9474c04d081.gif)
