### ISSUE TITLE
[Bug] Add to homescreen doesn't have a constant behavior on some devices

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#5301]
## Steps to reproduce
1. Load different webpages and add them to the homescreen using the 3 dot menu>Add to homescreen option.
### Expected behavior
The name editor should pop-up and a shortcut should be placed on the homescreen with a default icon (the first letter of the name on a colored plate) or the website logo (if available).
### Actual behavior
The name editor doesn't always come up. When it doesn't, the shortcut icon is ok.
When the name editor appears, the shortcut's icon will be broken. See the video when I add the rockfm.ro shortcut: https://drive.google.com/file/d/1AT8Ac7pIQIsUaXHJVgFBYHxr6edm6j1z/view?usp=sharing
### Device information

* Android device: I could easily reproduce this, but not 100% on Android 7.1 devices: Sony Xperia Z5 Premium (Android 7.1.1), Nokia 6 (Android 7.1.1).
Can't repro on other devices that I've tried: Pixel (Android 9), P9 lite (Android 6).
* Fenix version: 2.0.0-rc2

**Comment by ekager** [comment]
Could we retest this?

**Comment by sv-ohorvath** [comment]
Re-tested on some Android 7 devices and we couldn't reproduce the issue. 
Devices checked:
Nokia 6 (Android 7.1.1)
Sony Xperia Z5 (Android 7)
Nexus 9 (Android 7.1.1)
Huawei P9 Lite (Android 7.0)
Samsung S6 (Android 7)
Closing.
