### ISSUE TITLE
new tracking menu improvements 

### ISSUE THREAD

**Issue by nahuhh** [mozilla-mobile/fenix#5302]
### Why/User Benefit/User Problem
The shield and padlock icons are take up too much space. 
 
## What/Requirements
With the new etc controls came changes to the address bar.
- Etp was previously combined with the padlock menu, now itis separated. I like having separate icons but I think having 2 menus is a bit much.

Would work well imo to have the "🔐 secure connection" shown in the same menu as the tracking.

- when you add an exception (turn tracking for a website) you should be able to turn it back on from the same (padlock)

-the icons (shield and padlock) are too far apart. 
### Acceptance Criteria (how do I know when I’m done?)
 
I believe it is meant to be roughly symmetrical spacing to the tab button and menu, if so, please slightly reduce the padding between the menu and tab buttons as well.

**Comment by Amejia481** [comment]
Related https://github.com/mozilla-mobile/fenix/issues/4560

**Comment by ekager** [comment]
Going to close this for #4560 and #3727
