### ISSUE TITLE
[Bug] The 'What's New' and 'Add private browsing shortcut' buttons are not localized

### ISSUE THREAD

**Issue by LaurentiuApahideanSV** [mozilla-mobile/fenix#5303]
## Steps to reproduce
1. Change the language of the device to any supported language except English;
2. Press the 3 dots button in order to bring up the Main Menu;
3. Go to the Settings section.
### Expected behavior
The 'What's New' and 'Add private browsing shortcut' buttons should be translated in the selected language.
### Actual behavior
The 'What's New' and 'Add private browsing shortcut' buttons are not translated in the selected language.
### Device information 

* Android device: Samsung Galaxy S8+ (Android 8.0.0)
* Fenix version: 2.0.0-rc.2 9/12

**Comment by liuche** [comment]
This was probably just not translated at the time, I see translations for these features now.
