### ISSUE TITLE
[Bug] Shield info box is mis-positioned (covers up the shield)

### ISSUE THREAD

**Issue by dholbert** [mozilla-mobile/fenix#5304]
## Steps to reproduce
1. Visit some site that triggers tracking protection, e.g. a https://www.nytimes.com/ article in my case.
2. Observe the info-box that appears (probably just the first time?) to tell you about the shield icon colors.

### Expected behavior
The box should not cover the shield. Its arrow should be pointing at the shield icon.

### Actual behavior
The box/arrow cover up the shield icon, so you can't tell what it's describing.

### Device information
* Android device: Pixel 3
* Fenix version: Nightly 190912 20:44 [...] 71.0a1, built Thursday 9/12 at 8:53 PM

**Comment by dholbert** [comment]
Here's a screenshot. The info-box is at the bottom left (and so is the shield, though you can't see it) because it's covered up, per this bug).
![screenshot](https://user-images.githubusercontent.com/426803/64875316-b0bd0600-d601-11e9-9281-4d6a9050c9b9.png)

**Comment by dholbert** [comment]
CC @ekager who I think has been working on fenix ETP stuff.

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on Nightly Build #12621819 from 19/9 using the following devices:
• Google Pixel 3a (Android 9)
• Samsung Galaxy Note 9 (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

►Pic
![rsz_screenshot_20190920-143924](https://user-images.githubusercontent.com/51314259/65324473-fe62e100-dbb4-11e9-9d3e-80d6408acbb0.png)
