### ISSUE TITLE
Pin down flank.jar to stable version in Dockerfile

### ISSUE THREAD

**Issue by rpappalax** [mozilla-mobile/fenix#5305]
Per the recommendation of the flank team we always download the latest flank.jar to get bug fixes, etc.  The most recent flank version v7.0.2 has a breaking change so, going forward, we'd like pin down the version instead.

@pocmo is there a place we can specify a version number outside the Dockerfile (and pass that in as an env var) that way we don't have to push a new Docker image, should we wish to upgrade?

**Comment by pocmo** [comment]
> @pocmo is there a place we can specify a version number outside the Dockerfile (and pass that in as an env var) that way we don't have to push a new Docker image, should we wish to upgrade?

Maybe we could add this as a parameter that we pass to the script?

https://github.com/mozilla-mobile/fenix/blob/7d023fefc9cabd19ef952adb9afa255338e6c593/automation/taskcluster/lib/tasks.py#L185

> The most recent flank version v7.0.2 has a breaking change so, going forward, we'd like pin down the version instead.

In this case I think its Firebase that changed and our flank version cannot handle that change.

**Comment by rpappalax** [comment]
The firebase team accidentally rolled out some breaking changes to physical devices (which they are in the process of rolling back atm).  Closing this issue.
