### ISSUE TITLE
Run raptor performance tests against Fenix beta

### ISSUE THREAD

**Issue by davehunt** [mozilla-mobile/fenix#5306]
### Why/User Benefit/User Problem
We're running raptor performance tests against the Fenix nightly build, which is now using geckoview nightly. This helps to identify performance issues and to confirm performance improvements soon after they are introduced. In addition to this, we want to be able to run performance tests against the upcoming release of Fenix, to be used as a comparison point, and to measure against our release criteria.

### What/Requirements
Run raptor performance tests against both Fenix nightly (gv nightly) and Fenix beta (gv beta), reporting results to Treeherder/Perfherder in a way that can be discerned by consumers of these tools (including dashboards such as health.graphics).

### Acceptance Criteria (how do I know when I’m done?)
Results are available in Treeherder/Perfherder and can be distinguished based on the version of the application under test.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-13416)

**Comment by davehunt** [comment]
Tests for beta and nightly should run once a day, as the nightly tests do currently.

**Comment by mitchhentges** [comment]
Thanks for creating this ticket!
To confirm, _every_ test that currently runs for `geckoNightly` should run for `geckoBeta`? So we should have twice the raptor tasks, correct?

**Comment by davehunt** [comment]
Yes, that's correct @mitchhentges

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813154

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
