### ISSUE TITLE
[Bug] Scrolling on Twitch.tv's game page is unusable (perf)

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#5307]
## Steps to reproduce
- Visit twitch.tv
- Select a game
- Scroll the page

### Expected behavior
Page scrolls smoothly

### Actual behavior
Page scrolls choppily at first. After a while, if you make a fling scroll gesture, the page will fling choppily for a very long time.

### Device information
* Android device: Pixel 2
* Fenix version: Nightly 190912

I was unable to reproduce in desktop Nightly's responsive design mode.

---

@hawkinsw This is a GV perf bug: should it be filed here or do we need to file it somewhere else to track it?

**Comment by hawkinsw** [comment]
Sorry for the delay in responding to this; the best place to file this is
in Bugzilla as part of GeckoView. Anything that we track in this queue is
related to the "wrapper" of Fenix. Does that make sense?

**Comment by mcomella** [comment]
@hawkinsw I don't know if bugs filed in GeckoView actually go through perf triage so I added `needs:performance` which seems to for [the QF triage process](https://mana.mozilla.org/wiki/display/PM/Performance+Triage).

**Comment by smaug----** [comment]
qf:? bugs in Bugzilla get triaged.

**Comment by mcomella** [comment]
This appears to have been fixed, maybe by https://bugzilla.mozilla.org/show_bug.cgi?id=1586909
