### ISSUE TITLE
[Bug] Cannot access search engine selection when clicking URL bar from tab

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#5308]
## Steps to reproduce
- Open a tab
- Click URL bar

### Expected behavior
Search engine selection is available, like if you clicked url bar from homescreen

### Actual behavior
Search engine selection is not available. Due to #5018, search engine selection is inaccessible from this screen

### Device information

* Android device: Pixel 2
* Fenix version: Nightly 190912

**Comment by nahuhh** [comment]
You can tap the "shortcuts"  the bottom to access the search engines. 

Poorly named, should be "search with.." 
Also should be able to tap the search engine icon in the address bar to perform the same function

**Comment by boek** [comment]
Dup of #5979, since there were two issues I will bump to group triage to decide if this is actually a bug 👍

**Comment by sblatz** [comment]
@Verdi Just to confirm: we don't want to show search shortcuts when the user goes from Browser Screen -> Search Screen (URL is selected) correct?

**Comment by Verdi** [comment]
> @Verdi Just to confirm: we don't want to show search shortcuts when the user goes from Browser Screen -> Search Screen (URL is selected) correct?

No. We DO want to show the search shortcuts here.

**Comment by sblatz** [comment]
@Verdi is that the case even when the URL from the website is selected? When I go from browser -> search, the URL from the website I'm on is shown in the URL bar, highlighted, with no suggestions currently. Are you wanting shortcuts to appear "enabled" in this state or only after the user backspaces the URL?

**Comment by sblatz** [comment]
Fixing this will also fix the "flicker" of "this time search with" showing then disappearing.

**Comment by brampitoyo** [comment]
@sblatz wrote:

> Are you wanting shortcuts to appear "enabled" in this state [when the URL from the website is selected] or only after the user backspaces the URL?

We should show the shortcuts only after the user modifies the text. To do this, they can backspace or just start typing to enter a new query.

**Comment by nahuhh** [comment]
My view:

A. 
Only show shortcuts after user modifies text 

Vs

B. 
Show shortcuts when user taps the address bar 
And
Show suggestions when user modifies text

A.
1 - user modifies text
2 - shortcuts appear
3 - suggestions are lost? Flicker remains?

B.
1 - user taps address bar
2 - shortcuts appear
3 - user modifies text
4 - shortcuts disappear and suggestions appear

Personally, I'd go B.

Also IMO
- "shortcuts" should be renamed to "search with.."

**Comment by brampitoyo** [comment]
@nahuhh Great point.

When user taps the address bar, there’s nothing else to show below it, except maybe “Pasted text”. So your thinking is “Why not show search shortcuts?”:

Scenario 1: I want to search with the default search engine, or go to another URL
- Tap address bar
- Shortcuts appear
- Modifies text
- Suggestions from default search engine are shown

Scenario 2: I want to search with other search engines
- Tap address bar
- Shortcuts appear
- Select another search engine
- Modify text
- Suggestions from the other search engine are shown

This makes search engine selection directly accessible every time the user taps the address bar, no matter which page the address bar belongs to.

I wonder if there are any unintended consequences of doing this?

**Comment by brampitoyo** [comment]
@nahuhh I’ve just consulted with Verdi, and am in full agreement with your proposal.

The behaviour that we should implement is exactly as you wrote:

- When user taps the address bar (and the full URL is highlighted), show search shortcuts
- When the text is modified, show search suggestions

**Comment by AndiAJ** [comment]
Hi, I've checked this matter on the latest **`Nightly Build #20630607 from 03/03`** using the following devices:
• Google Pixel 3a (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)
 
| Status  | Requirement|
| ------------- | ------------- |
| ✔️ | Show search shortcuts - When user taps the address bar to start a new search session |
| ✔️ | Show search shortcuts - When user taps the address bar (and the full URL is highlighted) |
| ✔️ | When the URL text is modified, show search suggestions |
| ❓  | When user taps the address bar after performing  a search using a suggestion |

❓ What should be displayed after the user performs a a search using a suggestion and taps the address bar ?

► Video
![20200303-105931](https://user-images.githubusercontent.com/51314259/75759727-b12b9380-5d3e-11ea-828c-cee5b11470e5.gif)


@brampitoyo - Could you please review and advise? ☺️

**Comment by sblatz** [comment]
I'm pretty sure we're wanting to show the search shortcuts in those cases too. I will dig into this.

**Comment by brampitoyo** [comment]
Agreed with @sblatz. We should show search shortcuts in that case.

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly Build #20650606 from 03/05`** using the following devices:
• Google Pixel 3a (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

| Status  | Requirement|
| ------------- | ------------- |
| ✔️ | Show search shortcuts - When user taps the address bar to start a new search session |
| ✔️ | Show search shortcuts - When user taps the address bar (and the full URL is highlighted) |
| ✔️ | When the URL text is modified, show search suggestions |
| ✔️  | When user taps the address bar after performing  a search using a suggestion |

►Video
![20200305-110022](https://user-images.githubusercontent.com/51314259/75965864-182d8180-5ed2-11ea-8beb-c7185c32cf70.gif)
