### ISSUE TITLE
Change EditToolbar cancelView behavior to clear text instead of cancel 

### ISSUE THREAD

**Issue by ekager** [mozilla-mobile/fenix#531]
### Why/User Benefit/User Problem
- "X" beside your toolbar text can confuse users because other browsers (including Focus) use it to clear the current text and personally I also find myself confused by the behavior. Also discussed in M1 UR study results.

### What / Requirements
- X button changed behavior ([with AC team](https://github.com/mozilla-mobile/android-components/issues/2054)) 

### Acceptance Criteria (how do I know when I’m done?)
- Button clears current toolbar search text

**Comment by ekager** [comment]
Closed by migrating to 45 in #697

**Comment by sv-ohorvath** [comment]
Verified as fixed.
