### ISSUE TITLE
[Telemetry] Tracking Protection

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/fenix#5312]
## Description & Product Manager / Data Scientist User Story
- As a product owner, I want to know how users interact with tracking protection settings

#### Hypothesis
- We believe this feature is useful to users so they have the choice and freedom of deciding how much they want to be protected. 

#### What probes (suggested, if applicable)
- User changing default `strict` to `basic` or `off` on the TP settings page
- User changing Tracking Protection ON to OFF through the panel.

Interacting with the settings:
- User opening Tracking Protection settings through the settings menu
- User opening Tracking Protection settings through the panel
- User tapping on the tracking protection shield icon
- User tapping on Tracking content

**Note that we already have this: events.preference_toggled**

### Acceptance Criteria (Added by PM)
- Event pings can be queried via re:dash
- We are sending telemetry events for the actions listed in the requirements
- We have documented the telemetry
- We have asked a data steward to [review](https://github.com/mozilla/data-review/blob/master/request.md) the telemetry
- NOT an AC: Data science to create dashboard or further graphs (this will be a separate issue, this issue is only about hooking up the events described and that they can be queried in re-dash)

**Comment by sblatz** [comment]
@vesta0 Are you wanting to send the tracking protection setting in the core ping too? `strict` `basic` or `off`?

**Comment by AndiAJ** [comment]
Hi, I've just checked on **Nightly Build#12671258 from 24/9** using a Google Pixel 3a (Android 9) .

1. User tapping on the tracking protection shield icon  ✅
Ping 7ea6747c-89d8-4102-ac9c-25e3f6a465d8

2. User changing Tracking Protection ON to OFF through the panel

OFF ❓ - Ping 57359168-d5e1-48a1-9a1b-11f38409e1d8
ON ❌ - No ping generated

3. User opening Tracking Protection settings through the panel ✅
Ping - cba4cac7-c775-43ba-b22b-eb4b6f3fb953

4. User opening Tracking Protection settings through the settings menu ✅
Ping - 160e16df-6f2f-428f-b861-7cc0e1596ea6

5. User changing in the TP settings page

• Change to Basic ❌ - No ping generated
• Change to Strict (Default) ❌ - No ping generated

• OFF ✅ - Ping 722d80d1-d9d8-4631-b6bd-5518d4949c0d
• ON ✅ - Ping 89a57694-623d-43ab-80f4-f04a7d2eb30a

@ekager - I kindly ask you to review the above mentioned issues.

I've also noticed that when the user **changes Tracking Protection OFF through the panel (marked with ❓)** the pings is generated like this:
"category": "tracking_protection",
"name": "exception_added"

On the other hand when setting it to **OFF in the TP settings page** the ping is generated like this:
"name": "preference_toggled",
"extra": {
      "preference_key": "pref_key_tracking_protection",
      "enabled": "false"}

Given the fact that in the **Tracking Protection panel** the change is also made by using a toggle button wouldn't it be better to add the preference_key and the Boolean value to what is already implemented? 

[Logcat](https://github.com/mozilla-mobile/fenix/files/3652914/track.txt)
[Glean Dashboard](https://debug-ping-preview.firebaseapp.com/pings/aj-250925)

**Comment by ekager** [comment]
Thanks @AndiAJ ! I've fixed number 5 and I think that's the only bug. The panel toggle only adds or removes a site from the exceptions list (it doesn't turn TP on/off globally) and the original spec only asked for an event for when a site is added.

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on **Nightly Build #12700627 from 27/9** using a Google Pixel 3a (Android 9) device.
1. User tapping on the tracking protection shield icon ✅
Ping 92b4f594-68e0-4408-88f8-f0bc767eff26

2. User changing Tracking Protection ON to OFF through the panel ✅
OFF - Ping 12641182-e983-40a1-b965-055ec650289d

3. User opening Tracking Protection settings through the panel ✅
Ping - 48c79613-426c-47e1-b2fa-903e3545457b

4. User opening Tracking Protection settings through the settings menu ✅
Ping - 8cdad14d-881b-4cdd-8da4-d67fa51b81c4

5. User changing in the TP settings page ✅

• Change to Standard ✔️ - Ping 0d378ed1-7388-45c4-b65b-c678ae0b0516
• Change to Strict (Default) ✔️ - Ping 32626bcf-e145-4bdb-8054-1989ebeeebbd

• OFF ✔️ - Ping 63300697-8a61-4a22-9b57-f9494a7e27b5
• ON ✔️ - Ping d680d9fa-5167-4b77-81cd-6015775a4096

#### Notes
[Logcat](https://github.com/mozilla-mobile/fenix/files/3662472/etp.txt)
[Glean Dashboard](https://debug-ping-preview.firebaseapp.com/pings/aj-270901)
