### ISSUE TITLE
[Bug] Firefox Preview is consuming send tabs sent to Fire

### ISSUE THREAD

**Issue by Sdaswani** [mozilla-mobile/fenix#5313]
## Steps to reproduce
1. Install Fenix and log into sync
2. Install firefox beta and log into sync
3. Send a tab to the firefox beta from another firefox

### Expected behavior
Firefox beta gets the tab

### Actual behavior
Firefox preview gets the tab

### Device information

* Android device: note 10
* Fenix version: any

**Comment by liuche** [comment]
hey @Sdaswani thanks for the bug report! 😛 

I'm not able to repro this, so I'm going to close it for now. Feel free to re-open if you're still seeing it!
