### ISSUE TITLE
[SPIKE] Investigate moving home screen 3 dot menu to bottom

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#5314]
Criteria:
- Evaluate risks (broken UI tests, etc.)
- Do a design review
- Estimate size of the ticket

**Comment by sblatz** [comment]
After further conversation with @boek & @liuche we're just going to move ahead with the original ticket :)

**Comment by nahuhh** [comment]
If you're still interested in doing this I think it would be a good idea. *opens up a can of worms*

Kinda ends up being a bunch of feature requests in one. Some of these are doable on their own and ones I would request regardless, others are specific to the implementation. 

*1. On the homescreen/tabs screen, the 3 dot menu at the top left, remove that and make it just a settings gear. (Too many menus on one screen)
2. Remove the address bar from the top
3. Add the address bar to the bottom. The full address bar (same you see when browsing) fixed at the bottom of the homepage
*4. While browsing, a tap of the tabs button goes to the tabs screen, scrolled to the current tab.
4.1 tap again goes back to the open tab
5. If no tabs are open hide the tabs button, tracking shield and secured icon, keeping only the menu on address bar and show the default search engine icon. Should function how the current one does (opens a new tab) 
*6. Move "help" out of the menus. Only needs to be in the settings beside "about" 
*7. Add the tabs icon beside the wording "open tabs" 
*7.1 then add "library" and the library icon beside it.
*7.2 switch between library and open tabs views on the onscreen 
*8. Allow swiping to delete history items
*9. Tap hold let's you save specific tabs or all tabs to a collection. But you can only share all tabs or one. 
On the multi select screen, istead of "save" you should have the options to save/share/close 
 
I'm sure there more improvements that could be made and I might have to make some (amateur) mockups if anything doesn't sound right. 

Items marked with an asterisk are the features that can be implemented before even moving the the menu to the bottom of the onscreen.

**Comment by sblatz** [comment]
@nahuhh Thanks for your suggestions! It'd be a lot easier for us to go through these feature requests if they were filed as separate tickets. 

That being said, we did decide to move ahead with implementing this ticket, and you can track progress here: https://github.com/mozilla-mobile/fenix/issues/561 😄
