### ISSUE TITLE
[Bug] Fenix shows a broken-lock icon while HTTPS websites are loading (giving the mistaken impression of security issues)

### ISSUE THREAD

**Issue by dholbert** [mozilla-mobile/fenix#5316]
## Steps to reproduce
 1. (optional) Be on a slow cell connection -- I think that helps make this issue visible for longer.
 2. Open a new tab, and type e.g. "https://hg.mozilla.org" into the URL bar (or any secure URL) and hit enter.
 3. Watch the location bar as the site loads.

### Expected behavior
No broken-lock icon should display.

### Actual behavior
For a noticeable amount of time (less than a second), there is a broken lock icon visible. It then changes to a lock icon.

### Device information
* Android device: Pixel 3
* Fenix version: Nightly 190912 20:44 [...] 71.0a1, built Thursday 9/12 at 8:53 PM

**Comment by cadeyrn** [comment]
Duplicate of #5002 where @NotWoods said:

> Duplicate of [mozilla-mobile/android-components#4156](https://github.com/mozilla-mobile/android-components/issues/4156)
> 
> We'll add a 3rd "default" state for loading pages

**Comment by dholbert** [comment]
Thanks!
