### ISSUE TITLE
[Bug] No user feedback in delete and quit when data is deleting

### ISSUE THREAD

**Issue by ekager** [mozilla-mobile/fenix#5323]
## Steps to reproduce
1. Have a lot of history 
2. Turn on delete and quit 
3. Quit app from menu

### Expected behavior
Some sort of feedback that the data is being deleted before the app quits

### Actual behavior
No user feedback, looks like nothing is happening

### Device information

* Android device: ?
* Fenix version: Nightly/Debug have this feature

**Comment by lime124** [comment]
after chatting with emily - the big problem here is that the app can take a few seconds before all the data is deleted so the app can appear frozen as the task is completed. 

@AmyYLee - thanks!

**Comment by AmyYLee** [comment]
@ekager So my understanding is that the screen that is frozen is the chrome/website view. Is the 3-dot menu still opened when the deleting is in progress? I'm thinking a snackbar could work in this instance with "Deleting browsing data..."

**Comment by ekager** [comment]
Yep, that's correct, and with #5442 we'll need to show it there as well. Do we need any further string work/review or should we go ahead with showing a snackbar with that string?

**Comment by AmyYLee** [comment]
> @ekager So my understanding is that the screen that is frozen is the chrome/website view. Is the 3-dot menu still opened when the deleting is in progress? I'm thinking a snackbar could work in this instance with "Deleting browsing data..."

Hi @jpfaller can you review the suggested copy above for the snackbar above and let me know if this works?

**Comment by jpfaller** [comment]
Let's do 

"Deleting browsing data..."

**Comment by lime124** [comment]
oops - @AmyYLee can you add eng;ready if it's ready to go? thanks!

**Comment by sv-ohorvath** [comment]
Verified as fixed on RC 2.3.0.
