### ISSUE TITLE
[Bug] PromptDialogFragments aren't closed automatically after a new page is loaded.

### ISSUE THREAD

**Issue by Lululalu** [mozilla-mobile/fenix#5326]
## Steps to reproduce
Go to: http://datomatic.no-intro.org
Touch the "Nintendo - Nintendo DS" spinner at the top of the page
Choose any option
Touch the spinner again, before Fenix finishes loading the new page

### Expected behavior
When the URL changes, the dialog is dismissed

### Actual behavior
The dialog remains even after the new URL has loaded. Selecting any option closes the menu without any other effects

### Device information

* Android device: Galaxy A5 2017 8.0
* Fenix version: nightly 190912

### Video
![prompt-dialog-doesnt-close](https://user-images.githubusercontent.com/13170306/72195525-90dafa80-33c7-11ea-815a-49ba22c71afd.gif)

NOTE: @Baron-Severin investigated then edited this comment to use Android / AC terminology on 1-10-20

**Comment by ekager** [comment]
So to clarify you're talking about a menu that exists in the web content and not in the Fenix UI?

**Comment by nahuhh** [comment]
Pretty sure this is what they are talking about 
1. Tap on a drop down box and make selection
2. Tap on a drop down box while the page is loading
3. Page finishes loading and box is still open
4. Selecting in that box does nothing

I'm assuming the op the asking for the box to close once the new page loads

**Comment by Lululalu** [comment]
@ekager, I was referring to the same thing as @nahuhh 😀

**Comment by vesta0** [comment]
We will coordinate with A-C to fix this.

**Comment by Baron-Severin** [comment]
`PromptFeature#handleDialogsRequest` in AC _looks_ like a reasonable place to attach a `Session.Observer`, but `feature-prompts` doesn't have a dependency on `browser-session` (and that's a dependency I'd rather not add).  I've reached out to the AC team to see if there's a better alternative.

**Comment by Baron-Severin** [comment]
QA note: this just merged into master in AC, it may not be verifiable until the next nightly is cut.

**Comment by abodea** [comment]
Verified as fixed on the latest Nightly build from **1/28** using **Google Pixel 3a XL(Android 10).**
Note that the box disappears and everything works as expected. 
Based on my comment I will close this issue.
