### ISSUE TITLE
Add "Search" to the context menu when a word is selected

### ISSUE THREAD

**Issue by Lululalu** [mozilla-mobile/fenix#533]
This is something very helpful, that most browsers already offer.

**Comment by pwd-github** [comment]
I just came to report this, but also to report that in the absence of this, on my device at least, I'm seeing an option for "Search Privately" which takes me over to Opera.

**Comment by Lululalu** [comment]
@pwd-github this is expected. Opera itself adds this feature on the context menu.

Also, I test sometime ago, and this feature is also missing in the Reference Browser.

**Comment by pwd-github** [comment]
@lululalu this doesn't happen in Fennec and shouldn't happen in Fenix either. No user expects to try and search for a word and then be made to have their browsing experience hijacked by another browser.

**Comment by Lululalu** [comment]
@pwd-github This is an Opera Mobile feature. You can tell them what you think, and hopefully they will listen.

If this doesn't happen is fennec, it's because fennec is the one doing something wrong. Several apps add functions to the context menu, e.g Google Translator, and you can use the GT app through any other browser or app, by selecting text, except fennec. The same is the case for the "search privately" option that Opera adds. Edge mobile does this too, it adds "search in Edge" on the context menu. Fennec is missing the third party apps entries on the context menu. Fenix on the other hand is doing it right.

As someone who simultaneously uses more than only one language, I miss this on fennec very much.

**Comment by pwd-github** [comment]
@lululalu I'll leave it up to people far smarter and more well informed to handle such a decision.

**Comment by Lululalu** [comment]
@pwd-github Am I misunderstanding something here, or you are calling dumb?

**Comment by pwd-github** [comment]
@lululalu what? No! I was not calling you dumb in the slightest, such a thought never crossed my mind. In hindsight, I can see that by failing to include "than myself", I inadvertantly may have made you feel targeted and I can assure you it wasn't my intention. Sorry for any offence that I may have caused and I look forward to seeing you again as we continue to file bugs in a bid to make Fenix the best browser it can be.

**Comment by Lululalu** [comment]
@pwd-github Thank you for clarifying that. And sorry for the misunderstanding.

**Comment by lime124** [comment]
@jpfaller - what sort of string would we want? 

i noticed if you have duckduckgo installed it says "search duckduckgo" in the context menu of fenix. idk if that stays there if we add our own fenix search or if there would then be two search options. maybe someone from eng has an answer to that...? i'll ping in slack.

**Comment by ekager** [comment]
I think we can not replace other options that other apps have set. We have this feature in Focus. The string there was "Search Privately"

**Comment by pwd-github** [comment]
@ekager it's probably worth mentioning that said "search privately" option, from Opera, is blocked in Fennec.

**Comment by jpfaller** [comment]
Search privately works!

**Comment by sblatz** [comment]
Ux will dig into this more

@ekager to drop a screenshot here :)

**Comment by vesta0** [comment]
@Lululalu is this issue specific to adding a "search in Fenix" entry to the 3rd party browser context menu, similar to the implementation in Focus, Opera, and DuckDuckGo ?

**Comment by Lululalu** [comment]
@vesta0 although that's a good idea that's is not what am talking about. What I am talking about is the ability to search a word, in a new tab, inside Fenix itself.
