### ISSUE TITLE
workflow for back button on new tabs

### ISSUE THREAD

**Issue by nahuhh** [mozilla-mobile/fenix#5331]
### Why/User Benefit/User Problem
1. Tap a link that opens in a new tab
2. After the page loads, press the back button
3. The "tabs" page is shown, with the current tab selcted
4. Press back again
5. The browser is closed*
6. Reopen the browser 
7. The tab pageis shown, scrolled to the top*
8. Scroll down and the "current" tab still selected

 ### What/Requirements
5. Back should cycle back to the previous tab of the current session. After reaching the root/oldest history of the first used tab in the current session, the tab page should be shown. Pressing back from there should then close the browser. 

Doesn't have to jump straight from one tab to another. Could still be "new tab > back > tab page > back > previous tab" (vs "new tab > back > previous tab" )

7. When reopening the browser, there should be a hotlink to open the current tab. 

### Acceptance Criteria (how do I know when I’m done?)
Step 5. 
I'll open a separate issue for step 7. 

The YouTube links on the right of this spreadsheet open in new tabs, used for testing. 
https://docs.google.com/spreadsheets/d/12-NAoBPPV_nNBqaY1vt7Gke8bthPYqnG0tMLeSDrIKI/htmlview

**Comment by nahuhh** [comment]
Related #2484

**Comment by buttercookie42** [comment]
Also #2483

**Comment by ekager** [comment]
Closing because our tabs flow and entry points have changed a lot since this was opened. Please open a new issue for any current tabs issues.
