### ISSUE TITLE
[Bug] inconsistent touch areas on "delete browsing data on quit" screen 

### ISSUE THREAD

**Issue by nahuhh** [mozilla-mobile/fenix#5338]
## Steps to reproduce
1. Go to Menu > Settings > Delete Browsing Data on quit
2. Tap on an item and view the touch area
![20190915_115030](https://user-images.githubusercontent.com/50635951/64924133-1f8b9200-d7af-11e9-8cda-74398d4d4afd.gif)

### Expected behavior
Touch area should continue as far as the on off toggle (span the width of the screen) for all items
### Actual behavior
Touch area spans the width of the screen for the main "on/off" toggle, but for the selections the any space to the left of the checkbox is dead space. 
### Device information

* Android device: 8.1.0 
* Fenix version: Nightly 190915 06:04 (Build #12580614)
📦: 13.0.0, 946a4254f
🦎: 71.0a1-20190913092859

**Comment by NotWoods** [comment]
One solution is to entirely remove the padding on the left side. Since that would be a UI change let's wait until the UX team responds to #5339 with the design for the delete data screens.

**Comment by nahuhh** [comment]
I think it looks very good with the padding on the left and overall spacing. Clean, easy on the eyesight.
Better than the other (older) delete browsing data screen. 

My vote would be to leave the overall appearance alone and stretch the touch area to match up with the boundaries of "on off" switch touch area. 

But yes, as #5339 is related, let's wait
