### ISSUE TITLE
[Bug] menu placement of save to collection

### ISSUE THREAD

**Issue by nahuhh** [mozilla-mobile/fenix#5340]
## Steps to reproduce
By default, it is below the "report site issue" button. Weird placement for library management
Now, if you enable "delete browsing data on quit" it is between "report site issue" and "quit" 

### Expected behavior
Should be in a better place.
I think between "library" and "desktop site" might be a place to think about moving it to

### Actual behavior
![Screenshot_20190915-120654](https://user-images.githubusercontent.com/50635951/64924365-d4bf4980-d7b1-11e9-9a6a-f839ab23b1e4.png)

### Device information

* Android device: 8.1.0 
* Fenix version: Nightly 190915 06:04 (Build #12580614)
📦: 13.0.0, 946a4254f
🦎: 71.0a1-20190913092859

**Comment by lime124** [comment]
thanks! i'm collecting related issues to the menu so that we can tackle them all at the same time. removing ux label as this will get prioritized with other work.

**Comment by apbitner** [comment]
'Add to collection' has been moved next to 'Add to Home screen' to form a more logical grouping.
