### ISSUE TITLE
[Bug] A page shortcut created in Private Mode should open in Private Mode and reflect this visually.

### ISSUE THREAD

**Issue by klint** [mozilla-mobile/fenix#5341]
## Steps to reproduce
Open Fenix in Private Mode (either directly by the new Private Mode Shortcut on homescreen, or by switching from Non-Private mode on Fenix home page).
Visit a page
Create a page shortcut on the homescreen by "Add to homescreen"

### Expected behavior
The pop-ups to create the page shortcut should display the Private mode application icon.
The page shortcut on homescreen should display a small Private mode application icon in the corner.
The shortcut should open the page in Private mode, whatever mode was active previously

### Actual behavior
The pop-ups to create the page shortcut display the Non-Private mode application icon.
The page shortcut on homescreen displays a small Non-Private mode application icon in the corner.
The shortcut opens the page in Non-Private mode if the applications was last open in Non-Private mode.

### Device information
* Android device: Redmi Note 7
* Fenix version: Build 12580614

**Comment by liuche** [comment]
For now, to both minimize confusion (a user needs to remember which state they saved it in) and technical maintenance of another branch state, I'm going to say that we're not doing this feature, because we've added a way for users to choose:
a) whether to open all links in Private Mode
b) if no default browser is set, to open in private or non-private in #5742 and #514

**Comment by klint** [comment]
Thanks for the answer. It is true that the "open all links in PM" brings much more consistency to the matter (even if I still find it a bit strange from a user perspective to be able to create a shortcut from a page in PM, and yet to see the shortcut open itself in non-PM... or vice-versa :) )

Actually, I would now solve this issue in a simpler manner, functionnally speaking, by splitting the single 'open all links in PM' into 2 different settings:
 - Setting #1: 'open all 3rd party links in PM' (which would open all links from other applications, but not Fenix shortcuts)
- Setting #2: 'open all Fenix shortcuts in PM' that would apply to Fenix shortcuts only, obviously.

As I use shortcuts similarly to PWA for sites that are not PWA-enabled but that need session/cookie context, and  I would set the first to ON and the second to OFF.

For the record :)
