### ISSUE TITLE
[Bug] A page shortcut created in Non-Private Mode should open in Non-Private Mode 

### ISSUE THREAD

**Issue by klint** [mozilla-mobile/fenix#5342]
## Steps to reproduce
Open Fenix in Non-Private Mode (either directly by the new Non-Private Mode Shortcut on homescreen, or by switching from Private mode on Fenix home page).
Visit a page
Create a page shortcut on the homescreen by "Add to homescreen"
Check that the pop-ups to create the page shortcut displays the Non-Private mode application icon.
Check that the page shortcut on homescreen displays a small Non-Private mode application icon in the corner.

### Expected behavior

The shortcut should open the page in Non-Private mode, whatever mode was active previously

### Actual behavior
The shortcut opens the page in Private mode if the applications was last open in Private mode.

### Device information
* Android device: Redmi Note 7
* Fenix version: Build 12580614

**Comment by nahuhh** [comment]
I'm having a different issue. No matter how the shortcut if created (private or not), it opens in non-private. 

Either way, the issue is that the shortcuts should be stored/launched in the same mode they were created.

**Comment by liuche** [comment]
@NotWoods does PWA have a concept of private vs non-private opening? And how does that affect the PWA (for offline storage, etc).

If not, and this only refers to homescreen shortcuts, in order to minimize confusion, we're only going to allow users to control links globally, rather than per-shortcut.

**Comment by NotWoods** [comment]
They don't right now, but eventually we want to have the option to use PWAs with containers.

**Comment by jeroen7s** [comment]
I'm having the same issue. If the default for external links is set to private mode, all saved webapps/homescreen shortcuts also open in private mode.

So there's 2 options for users: 
stop saving shortcuts to homescreen
Disable opening links in private mode

Neither option is preferable.
