### ISSUE TITLE
Custom Tabs shows incorrectly styled toolbar

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/fenix#535]
## Steps to reproduce
1. Set Fenix as default browser.
2. Open custom tab.

### Expected behavior
- The toolbar looks styled according to the app's specficied colour and behaviour.

### Actual behavior
- There is the url bar outline and background that shouldn't be there.

### Device information

* Android device: Android 9 (Pixel 2)
* Fenix version: ?

We probably want to hold back most default customizations to allow the CT toolbar feature to apply the appropriate one.
<img width="898" alt="screen shot 2019-02-15 at 4 05 00 pm" src="https://user-images.githubusercontent.com/1370580/52884269-7c509c80-313b-11e9-9c3c-a73c2fc7e617.png">

**Comment by vesta0** [comment]
Should be fixed by #668

**Comment by bsurd** [comment]
Verified on a Pixel and Galaxy S8. With the new style, everything can be clearly read.
