### ISSUE TITLE
Google looks bad

### ISSUE THREAD

**Issue by kamran-12** [mozilla-mobile/fenix#5350]
### Site with the issue and any steps to reproduce
google.*
Search something, then maybe open settings at the bottom page.

### Expected behavior
Seeing the normal Google like on ~90% Android browsers.

### Actual behavior
Google is weird. Layout it unusual and for some pages it is like from 10 years ago. Some parts of its Settings page (including "Save" button) is gone.

### Does toggling Tracking Protection fix the issue? (Press the lock icon in the toolbar while on the site to see toggle)
No

### Can you reproduce in [Firefox for Android](https://play.google.com/store/apps/details?id=org.mozilla.firefox)?
Yes, it has the same problem. But it can be fixed using "Chrome UA on Google for Firefox Android" extension. Normal site layout should be default in all browsers. Unusual layouts should be triggered by extensions or non-default settings.

### Can you reproduce in Chrome (or other non-Mozilla browser)?
Maybe it is possible adding info about Firefox UA to the address bar, I haven't tried. By default, it never happens.

### Device information
* Android device: Samsung Galaxy S6, Android 7.0
* Fenix version: 1.4.1

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-13444)

**Comment by NotWoods** [comment]
Sadly Google serves an old version of its site to everyone that's not Chrome. I think mozilla-mobile/android-components#4409 includes code to change the user agent automatically.

**Comment by kamran-12** [comment]
> Sadly Google serves an old version of its site to everyone that's not Chrome. I think [mozilla-mobile/android-components#4409](https://github.com/mozilla-mobile/android-components/pull/4409) includes code to change the user agent automatically.

I wouldn't say non-Chrome. It only happens with Firefox. Even UC Browser where some websites look differently doesn't have this problem.

**Comment by nahuhh** [comment]
Fenix looks fine as well..

**Comment by nahuhh** [comment]
Fenix: 

![Screenshot_20190916-215752](https://user-images.githubusercontent.com/50635951/65005202-15f84c00-d8cd-11e9-828a-184aacf464b6.png)
![Screenshot_20190916-215644](https://user-images.githubusercontent.com/50635951/65005250-39bb9200-d8cd-11e9-8c7b-daed73098c5e.png)
![Screenshot_20190916-214848](https://user-images.githubusercontent.com/50635951/65005260-42ac6380-d8cd-11e9-94f8-64c9d22f01a0.png)

**Comment by vesta0** [comment]
This is the difference between the version of Google search served to browsers using GeckoView vs WebView. Note that 10% of Focus users are still on WebView.

**Comment by yaakovfeldman** [comment]
Spoofing UA can cause drastic increase in reCaptcha. Eg reCaptcha v3 score changes from 0.9 to 0.1. See https://bugzilla.mozilla.org/show_bug.cgi?id=1620883

**Comment by sheikh-azharuddin** [comment]
@andreicristianpetcu how you got these add ons? These are not showing in add on section?

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813763

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
