### ISSUE TITLE
[Bug] Page title and favicon are not shown.

### ISSUE THREAD

**Issue by kamran-12** [mozilla-mobile/fenix#5351]
### Steps to reproduce
I could reproduce it only in Wikipedia. Open one Wikipedia page, then open another in a new tab. (I did this by "Open in new tab")

### Expected behavior
Favicons and site titles for all tabs.

### Actual behavior
![image](https://user-images.githubusercontent.com/46045997/64952687-00b1fc00-d892-11e9-80b5-c5592789d69c.png)

### Device information

* Android device: Samsung Galaxy S6 Android 7.0
* Fenix version: 1.4.1

**Comment by sblatz** [comment]
Likely related to #3846.

**Comment by pt2121** [comment]
I will look into this

**Comment by ekager** [comment]
Reopening for QA

**Comment by sv-ohorvath** [comment]
Verified as fixed on latest Nightly (10/8).
