### ISSUE TITLE
Migrate "release locales" mechanism from Focus to Fenix

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/fenix#5355]
In Focus we had this mechanism for defining "release locales". Only those locales would go into release versions. All other locales would only be used in Nightly builds.

This mechanism allows us to start the translation (and review) process for a new locale without shipping it to our users immediately. In order to add/verify RTL support this allows us to adds those languages to Nightly and ship them once we are confident that our RTL support is sufficient.

**Comment by boek** [comment]
dup of #3088
