### ISSUE TITLE
[Bug] TP icon broken - Android 5 & 6 devices.

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#5359]
## Steps to reproduce
1. Load a webpage.
2. Observe the TP icon in the url bar (for secure connections)
3. Observe the ETP icon in the security panel.
### Expected behavior
The icon is rendered correctly.
### Actual behavior
The icon is broken.
### Device information

* Android device: Xiaomi MiPad 2 (Android 5.1), Nexus 5 (A 6.0.1), Samsung Tab A6 (Android 5.1.1)
* Fenix version: Nightly 9/16
![screencap](https://user-images.githubusercontent.com/4037709/64960925-0a8d2c80-d89d-11e9-99ce-7a5acb0d252d.png)
![Screenshot_20190916-154831](https://user-images.githubusercontent.com/4037709/64960931-0cef8680-d89d-11e9-8b55-611cd0bcd625.png)

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on Nightly Build #12621819 from 19/9 using the following devices:
• OnePlus A3 (Android 6.0.1)
• Samsung Galaxy S6 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

**►Browser**
![rsz_screenshot_20190920-120348](https://user-images.githubusercontent.com/51314259/65314496-221b2c80-db9f-11e9-95ca-29ff6395157b.png)

**►Custom tabs**
![rsz_screenshot_20190920-121226](https://user-images.githubusercontent.com/51314259/65315119-3b70a880-dba0-11e9-9d76-2804512d4b47.png)
