### ISSUE TITLE
[Bug] Fenix crashes on Android 5 & 6 when Settings-Enhanced Tracking Protection is accessed

### ISSUE THREAD

**Issue by softvision-miralobontiu** [mozilla-mobile/fenix#5360]
## Steps to reproduce
1. On a device with Android 5 or 6, go to Settings - Enhanced Tracking Protection.

### Expected behavior
The user cand access the tracking protection section.

### Actual behavior
Fenix crashes.

### Device information
* Android device: Xiaomi Mi4i (Android 5.0.2), Nexus 5 (Android 6.0.1),  Xiaomi MiPad 2 (Android 5.1)
* Fenix version: Nightly 190916 (#12590611)

[logcat.txt](https://github.com/mozilla-mobile/fenix/files/3616532/logcat.txt)

**Comment by Amejia481** [comment]
@ekager

**Comment by softvision-miralobontiu** [comment]
Verified as fixed on RC 2.0.0-rc.3 with Xiaomi Mi4i (Android 5.0.2), and Xiaomi MiPad 2 (Android 5.1).
