### ISSUE TITLE
[Bug] Opening a Custom Tab prompts you choose between multiple Fenix options

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/fenix#5364]
## Steps to reproduce
1. Attempt to open a Custom Tab from another app (e.g. Gmail, **not Slack**).

### Expected behavior
 - The tab opens in the appropriate default browser state.

### Actual behavior
 - You have to choose from the system app chooser where you want that tab to open up in.

### Device information

* Android device: Pixel 2 (Android 10)
* Fenix version: 

> Nightly 190916 06:04 (Build #12590612)
> 📦: 13.0.0, 946a4254f
> 🦎: 71.0a1-20190913092859

![Screenshot_20190916-104925(1)](https://user-images.githubusercontent.com/1370580/64968863-de5bb680-d870-11e9-86fe-707576727b7e.png)

**Comment by sblatz** [comment]
@jonalmeida Is this a bug? We now intentionally have a "private" launcher that was added in #419.

**Comment by jonalmeida** [comment]
@sblatz yes, you shouldn't have to stop in your app when clicking to choose the mode. The app should know which one was set/chosen. The private launcher shouldn't interfere with Custom Tabs.

**Comment by sblatz** [comment]
This issue is also pointing to a deeper problem: if a user selects "always" they are never able to change their default browser back to private/normal. The "Firefox Preview (Private)" option does not show in the "default apps" page. I could have sworn it did at one point?

**Comment by neekless** [comment]
@sblatz You can do it by clearing defaults in Settings for the app. 
![Screenshot_20190918-091550](https://user-images.githubusercontent.com/22426822/65095827-3f3ed800-d9b2-11e9-94e8-c23529018144.jpg)

**Comment by sblatz** [comment]
I believe this was fixed by https://github.com/mozilla-mobile/fenix/pull/5398. QA please confirm 😄

**Comment by softvision-miralobontiu** [comment]
Verified as fixed. Opening a page in custom tab doesn't trigger the dialog to choose between multiple Firefox Preview apps.
Tested with Nexus 9 tablet (Android 7.1.1), and Xiaomi Mi 8 Lite (Android 9) with the latest Nightly build 190919 (#12621819).
