### ISSUE TITLE
VectorDrawableCompat all the things

### ISSUE THREAD

**Issue by NotWoods** [mozilla-mobile/fenix#5366]
We've been having issues with vector drawables on Android SDK 21-24 due to issues that have since been fixed in newer Android versions. We should start using the compat library everywhere we use vector icons so it handles those older devices for us.

[Using vector assets in Android apps](https://medium.com/androiddevelopers/using-vector-assets-in-android-apps-4318fd662eb9)

Related:
- #5359
- #5316
- #4702

**Comment by NotWoods** [comment]
We'll accept PRs that update some icons, you don't need to find every single spot in one go. 😄

**Comment by icenine457** [comment]
I'd like to take a stab at this if it's alright.

**Comment by NotWoods** [comment]
@icenine457 Go for it!

**Comment by icenine457** [comment]
FYI I'll be trying to work on this tomorrow.

**Comment by darkwing** [comment]
@NotWoods Is there a good way to know where else this needs to be applied?  I'd love to finish this if #6376 didn't fix all cases.

**Comment by NotWoods** [comment]
I'll do another check when I get home, but in general:

- Replace all `android:src` with `app:srcCompat` in XML layouts.
- Replace `android:drawableStart` with `app:drawableStartCompat`, same for `drawableEnd`, `drawableTop`, `drawableBottom`.
- Replace `context.getDrawable` with `AppCompatResources.getDrawable`
