### ISSUE TITLE
[Bug] Tracking Protection sheet floats above the toolbar

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/fenix#5368]
## Steps to reproduce
1. Click the TP icon in regular browsing.

### Device information

* Android device: Pixel 2 (Android 10)
* Fenix version: 
> Nightly 190916 06:04 (Build #12590612)
> 📦: 13.0.0, 946a4254f
> 🦎: 71.0a1-20190913092859

<img width="634" alt="Screen Shot 2019-09-16 at 3 43 09 PM" src="https://user-images.githubusercontent.com/1370580/64988622-debc7780-d899-11e9-949a-a5b098d25eb7.png">

**Comment by nahuhh** [comment]
Not floating on 
Nightly 190919 18:00 (Build #12621820)
📦: 14.0.0, 0681a1e65
🦎: 71.0a1-20190916093313

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on Nightly Build #12621819 from 19/9 using a Pixel XL (Android 10)
![rsz_screenshot_20190920-130028](https://user-images.githubusercontent.com/51314259/65318750-e7b58d80-dba6-11e9-9b3c-ddb09d7eb8ed.png)
