### ISSUE TITLE
[Bug] Consider changing "Search Engine" setting to "Search"

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#5371]
Currently our "Search engine" setting (under the "Basics" heading) links to a page that controls more than just the Search engines. We should get new copy for this string and update it.

<img width="350" alt="image" src="https://user-images.githubusercontent.com/4400286/64996639-53d87e80-d893-11e9-925e-daaf3f9ffbbb.png">

<img width="350" alt="image" src="https://user-images.githubusercontent.com/4400286/64996650-62bf3100-d893-11e9-81cf-11ab6bda74f3.png">

@jpfaller for string on this :)

**Comment by jpfaller** [comment]
Let's call it

"Search"

and then remove the subtext where we show the search engine they've picked (In this screenshot, Google)

**Comment by sblatz** [comment]
I'm pulling this in since it's a very easy fix and was related to a feature I did in 2.0 (new issue introduced)

**Comment by sblatz** [comment]
@jpfaller When I change it to just say "search" it's not clear that you're selecting a default engine:

<img width="300" alt="image" src="https://user-images.githubusercontent.com/4400286/65077433-c7d85c80-d94f-11e9-953b-27b7210a151c.png">

Because of that I've updated it to look like this: 
<img width="300" alt="image" src="https://user-images.githubusercontent.com/4400286/65077861-acba1c80-d950-11e9-8102-c4dab386fdc6.png">

**Comment by jpfaller** [comment]
Can it say "Default search engine" ? If not I think this is OK

**Comment by nahuhh** [comment]
Looks good

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on Nightly Build #12621819 from 19/9 using the following devices:
• Google Pixel 3a (Android 9)
• Samsung Galaxy Note 9 (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

►Pics
![rsz_screenshot_20190920-124926](https://user-images.githubusercontent.com/51314259/65318112-bc7e6e80-dba5-11e9-88b6-41f8d7a7134b.png)

![rsz_screenshot_20190920-124933](https://user-images.githubusercontent.com/51314259/65318052-abcdf880-dba5-11e9-829a-623c0eabe0ac.png)
