### ISSUE TITLE
[Bug] [Android 5&6] Opening a tab in normal browsing takes the user to private browsing and vice-versa

### ISSUE THREAD

**Issue by softvision-miralobontiu** [mozilla-mobile/fenix#5375]
## Prerequisites
Make sure to have a clean profile.

## Steps to reproduce
1. Open a page in normal browsing.
2. From the page opened at step 1, long-tap on a hyper-link text and select to open in a new private tab.
3. Select "Switch". The user is in private browsing now, in the newly opened tab.
4. Exit private browsing and open the tab from step 1.

### Expected behavior
The user should be able to open the page opened in normal browsing in normal browsing.

### Actual behavior
After step 4, the user is redirected to private browsing's opened page.

### Note
If the user is in private browsing and opens the page from step 2, is redirected to the page opened in normal browsing.

### Device information
* Android device: Xiaomi Mi Pad 2 (Android 5.1), Huawei P9 Lite (Android 6), Huawei MediaPad M2 (Android 5.1.1)
* Fenix version: RC 2.0.0-rc.3

[logcat.txt](https://github.com/mozilla-mobile/fenix/files/3620571/logcat.txt)

![20190917_Trim](https://user-images.githubusercontent.com/40694158/65031955-e556f780-d94a-11e9-8591-be61f81bc200.gif)

**Comment by ekager** [comment]
Mm I can reproduce this and it is related to #5131 . Looks like when you switch the mode the homescreen tabs don't update until you scroll the page, meaning the tabs are for the opposite mode

**Comment by softvision-miralobontiu** [comment]
Verified as fixed on the latest Nightly build 190927 (#12700627) with Samsung Galaxy Tab A6 (Android 5.1.1), Huawei Media Pad M2 (Android 5.1.1), and Huawei P9 Lite (Android 6).
