### ISSUE TITLE
Current Session on Home: Show most recent tab first 

### ISSUE THREAD

**Issue by topotropic** [mozilla-mobile/fenix#538]
### Why/User Benefit/User Problem
As a user, I want to quickly get to my most recent tab without having to scroll on home.

### Acceptance Criteria (how do I know when I’m done?)
- I can see my tabs listed are in chronological order with the most recent tab on top.

**Comment by colintheshots** [comment]
@pocmo Is this something the SessionManager will provide or should the app sort them?

**Comment by vesta0** [comment]
@topotropic is this not how sessions behave today?

**Comment by topotropic** [comment]
> @topotropic is this not how sessions behave today?

this is about tabs in the current session, they are sorted by oldest to newest and it would be helpful to have the newest tab first

**Comment by vesta0** [comment]
We should do this!

**Comment by ekager** [comment]
We reversed the tabs in the list so the most recent freshly opened tab is now at the top.

**Comment by sv-ohorvath** [comment]
Verified on the latest build. No issues found.
