### ISSUE TITLE
[Bug] ETP settings UI with larger font setting

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/fenix#5383]
## Steps to reproduce
Go to Enhanced Tracking Protection settings page

### Expected behavior
Margins should look like this:

![Screenshot_20190917-132453](https://user-images.githubusercontent.com/42752644/65064529-a9259600-d94e-11e9-84c4-776188a0cd89.png)

### Actual behavior
With a larger font setting it looks like this:

![Screenshot_20190917-132409](https://user-images.githubusercontent.com/42752644/65064517-a2971e80-d94e-11e9-9584-a1a34d7aaf89.png)

### Device information

* Android device: Pixel 3
* Fenix version: Recent nightly

**Comment by Amejia481** [comment]
cc @ekager

**Comment by ekager** [comment]
@vesta0 could you be specific about what you think looks wrong with this? When you increase text size, I think we can expect it to look slightly different.

**Comment by neekless** [comment]
I think she expects the top margin (above the 'browse without being followed' line) to be consistent. When the text size is increased the text should be pushed down while keep that margin unchanged.

**Comment by mcarare** [comment]
Also, with an even larger font the "Learn more" is being cut-off: 
<img src=https://user-images.githubusercontent.com/48995920/65145663-c0ce4e80-da22-11e9-9090-b538f4a7b42d.png width=50%>

**Comment by softvision-miralobontiu** [comment]
Verified as fixed on the latest Nightly build 190924 from Play Store, with Motorola Moto G6 (Android 8), and Samsung Galaxy Tab A6 (Android 5.1).
