### ISSUE TITLE
[Bug] app drawer shortcuts don't work

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/fenix#5385]
## Steps to reproduce

Long press on the Fenix app icon and tap on "open new private tab" or "open new tab"

### Expected behavior

new tab opens

### Actual behavior

![Screenshot_20190913-031843](https://user-images.githubusercontent.com/42752644/65064816-2ea94600-d94f-11e9-92b9-2b5c00c9192b.png)

### Device information

* Android device: Pixel 3
* Fenix version: Latest nightly

**Comment by boek** [comment]
Going to verify the status of this bug on the 2.0 release candidate.

**Comment by boek** [comment]
This is working in 2.0, so it must have been a regression that landed this week

**Comment by boek** [comment]
Fixed in Nightly!
