### ISSUE TITLE
Biometric authentication for private mode

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#5387]
We should consider adding biometric authentication for private mode. This would help us with Focus parity.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-13472)

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807553

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
