### ISSUE TITLE
Decide behavior for private browsing persistence

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#539]
If a user (or the system) force-quits Fenix, how should we handle private sessions? Right now private tabs are erased if you force quit, but non-private ones stay.

**Comment by brampitoyo** [comment]
@sblatz Similar to https://github.com/mozilla-mobile/reference-browser/issues/447:

I agree with your proposal that private tabs should be erased when the user force quits. Non-private tabs stay intact, of course.

Additional proposal: once the user has entered private browsing mode, even if the app is force quit or has crashed, the next time it starts, it should open private browsing mode again.

This way, by simply setting Fenix to private browsing mode, it will behave like Focus: persistently private, and with auto-cleared private tabs.

Thoughts?

**Comment by sblatz** [comment]
Thanks for the clarification, @brampitoyo! This is how it currently works and the way I think makes sense 😄
