### ISSUE TITLE
[Meta] Collection of Web Content Issues Related to Tracking Protection

### ISSUE THREAD

**Issue by ekager** [mozilla-mobile/fenix#5392]
- https://github.com/mozilla-mobile/fenix/issues/4905
- https://github.com/mozilla-mobile/fenix/issues/4924
- https://github.com/mozilla-mobile/fenix/issues/4984
#6960 #7055 #6528

**Comment by yoasif** [comment]
Seeing an issue loading pages on Google news.

1. Navigate to https://news.google.com/?hl=en-US&gl=US&ceid=US:en
2. tap a link, eg: https://news.google.com/articles/CAIiELNMiaMbsbSp-BowGxmEbKoqGQgEKhAIACoHCAow2Nb3CjDivdcCMJ_d7gU?hl=en-US&gl=US&ceid=US%3Aen

Page never loads. Disabling TP allows the page to load.
