### ISSUE TITLE
PBM "Always launch in private mode" issues

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#5396]
Issues with the current implementation:

1. Selecting to "always" launch in private mode does **not actually set the app to always launch privately.** The first link you open will be in private mode, but after that they'll launch in normal browsing mode.

![always broken 2019-09-17 14_37_50](https://user-images.githubusercontent.com/4400286/65081563-bfd0ea80-d958-11e9-9ec5-929265e67c27.gif)

2. Currently if a user selects that they "always" want to launch in private mode, they have no way of undoing this selection (same for always launching in normal mode) since the separate launching modes **do not show up as separate apps in the default browser settings**. We likely want a setting in app to handle this (e.g. a toggle under "Privacy" that says "Always launch in private mode")

<img width="350" alt="image" src="https://user-images.githubusercontent.com/4400286/65081600-d24b2400-d958-11e9-8b92-acac7069b522.png">

**Comment by sblatz** [comment]
These fixes should land with #5386

**Comment by sblatz** [comment]
My recommendation here is to simply add a SwitchPreference in settings under Privacy to "Always launch in private mode"

**Comment by softvision-miralobontiu** [comment]
Might be related to #5375 and #5131.

**Comment by sblatz** [comment]
This is a demo of my proposed solution. Basically all external links would switch the user to private mode and then open the link.

<img width=350 src=https://user-images.githubusercontent.com/4400286/65171589-0d546280-da00-11e9-8c83-93c38e980422.gif>

**Comment by sblatz** [comment]
cc @vesta0 and @topotropic for your thoughts on pulling this in to 2.1?

**Comment by sblatz** [comment]
@jpfaller could you provide official strings for the "Open links in private mode"?  I tried "Open external links in private mode" (which is a bit more accurate, but it takes up two lines and looks bad).

**Comment by jpfaller** [comment]
What about:

Launch links in a private tab

**Comment by sblatz** [comment]
Updated with string @jpfaller requested.

Touched base with @topotropic and her feedback was to just move the preference toggle down a slot which I have also done.

**Comment by joebloggs7657** [comment]
Thank you for some common sense in regards to this issue...
How did it seriously take so long for developers to implement a home screen shortcut which doesn't even provide the same feature parity as permanent private browsing (as in desktop Firefox)?
For God's sake just put a simple toggle in the settings to allow permanent private browsing🤦

**Comment by sblatz** [comment]
For QA: the new expected behavior here is:
0) Be in normal browsing mode
1) Enable the toggle in settings
2) Open a link from another app (with Fenix as your default browser)

Then: link opens in private mode

Also:
0) Be in normal browsing mode
1) Disable the toggle in settings
2) Open a link from another app (with Fenix as your default browser)

Then: link opens in normal mode

**Comment by softvision-miralobontiu** [comment]
Verified that when the toggle "Launch links in a private tab" is on, all the links opened through external apps are opened in private mode.
Tested with the latest Nightly build 190923 (#12661829) with Motorola Moto G6 (Android 8), Nokia 6 (Android 7.1.1), and Samsung Galaxy Tab A6 (Android 5.1).
