### ISSUE TITLE
[Bug] When the system switches to Dark mode, pages refresh and content is lost

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/fenix#5397]
## Steps to reproduce
1. Enable battery saving mode to turn on dark mode OR enabled adaptive system themes based on time of day.
2. Open a page with user content filled in (e.g. a google form, play a video).
3. Wait for the system to switch modes (by plugging in your low battery device to power or waiting until mid-day for the mode to be enabled).

### Expected behavior
1. Nothing should happen when the system turns to dark mode.

### Actual behavior
1. The activity is recreated and the browser content is refreshed.

### Device information

* Android device: Android 10 (Pixel 2) I've seen this in Android 9 as well.
* Fenix version: 
> Nightly 190916 18:01 (Build #12591814)
> :package:: 13.0.0, 4e4b23627
> :lizard:: 71.0a1-20190915093655

This is quite infuriating when you're in-between a task, however, I've seen this happen to other apps as well that observe the adaptive theme. This doesn't affect reference browser either in my tests.

**Comment by ekager** [comment]
From the [official Android DayNight article](https://medium.com/androiddevelopers/appcompat-v23-2-daynight-d10f90c83e94)

> Activity recreations
> Both of the methods mentioned above will recreate your Activity if a Configuration change is required, so that the new theme can be applied. This is a good opportunity to test whether your Activity + Fragments save their instance state correctly.
>

**Comment by jonalmeida** [comment]
Not the most ideal of solutions, but maybe change the theme the next time the activity needs to be re-created? 

I was playing a mobile game around evening time, then the theme changed and I lost all progress in it. Feels like I'm being trained to not use my phones at sundown and when battery is low. 😅

**Comment by boek** [comment]
@jonalmeida not a bug, a feature! 😂
