### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by Nimitay** [mozilla-mobile/fenix#5399]
![Screenshot_20190917-171228](https://user-images.githubusercontent.com/25124711/65089088-d04d8900-d989-11e9-8c33-e578cd46706f.png)
## Steps to reproduce
Go to Google.com
Try typing anything that brings up automatic search suggestions. 
See the difference in fonts. 

### Expected behavior
I expect it to have the same font between what I type and the search suggestions And have the suggestions be bolded. 
### Actual behavior
What I type is one font and search suggestions are a cursive font. 
### Device information
Moto g6 plus on Android 8
* Android device: yes
* Fenix version: 68.2b2

**Comment by Nimitay** [comment]
I figured this issue out. It was because I had an module from magisk manager called Ubuntu font. Disabling it returned things to normal. Although I still would like to know why exactly.

**Comment by neekless** [comment]
It's highly likely that the module did not handle fonts.xml properly

**Comment by neekless** [comment]
That looks like fennec not fenix

**Comment by Nimitay** [comment]
What exactly is the difference, sorry for my ignorance.

**Comment by cadeyrn** [comment]
> What exactly is the difference, sorry for my ignorance.

It's a different browser. Your screenshot shows the old "Firefox" (code name "Fennec"). But this is the repository of "Fenix", currently branded as "Firefox Preview", which will replace the old Firefox in a few months.

This is the correct place for reporting bugs in the old Firefox:
https://bugzilla.mozilla.org/enter_bug.cgi?product=Firefox%20for%20Android

**Comment by Nimitay** [comment]
Ok thank you. I actually did reproduce the issue in Firefox preview. But next time I have an issue I will make sure I post in the correct place.
