### ISSUE TITLE
[Suggestion] Tab management buttons 

### ISSUE THREAD

**Issue by neekless** [mozilla-mobile/fenix#5402]
### Why/User Benefit/User Problem
Currently in private tabs the New tab, Share tabs, and Close all tabs buttons are all shown. 
![Screenshot_20190918-111348](https://user-images.githubusercontent.com/22426822/65105093-5639f600-d9c3-11e9-9e60-c336b0b4ca93.jpg)

In regular tabs, only the New tab button is shown, with the rest hidden behind a 3-dot menu. 
![Screenshot_20190918-111344](https://user-images.githubusercontent.com/22426822/65105184-a0bb7280-d9c3-11e9-9669-3724360f1308.jpg)
![Screenshot_20190918-111353](https://user-images.githubusercontent.com/22426822/65105198-afa22500-d9c3-11e9-8b09-d5aa26c317e7.jpg)
The only difference is that there is an additional Save to collection button in the 3-dot menu. But we also have a huge Save to collection button below the tabs. So the one in the 3-dot menu is redundant. 

### What/Requirements
I propose removing the 3-dot menu and let regular tabs have the same layout as private tabs (all 3 buttons shown) and removing the additional Save to collection button that was in the 3-dot menu. Benefits are: 1) More consistent layout, 2) Less redundancy

### Acceptance Criteria (how do I know when I’m done?)
When the layout changes are implemented I guess. I know the layout might get more changes in the future so who knows if this is a good idea. 🤷‍♂️

**Comment by s-ankur** [comment]
This is no longer applicable
