### ISSUE TITLE
Indicate that the entered address is direct URL or search query

### ISSUE THREAD

**Issue by kostrse** [mozilla-mobile/fenix#5403]
### Why/User Benefit/User Problem

When entering URL into the "Search or enter address" control, it's unclear whether the entered address will be opened directly as an URL or will be sent as a search query to the selected search engine.

Sometimes the user intention is to enter the website address directly into the address bar, but due to accidental error (space, comma instead of dot etc.) the address becomes invalid and being handles as a free text query for the selected search engine. As result user gets the search results instead of navigation to the desired page.

Opposite situation, when user wants to search a simple query but it's being handled as URL instead.

### What/Requirements

As user types the address, the search engine icon should change from logo of selected search engine to generic URL icon to indicate the user whether the address is going to be opened directly or sent to search engine.

### Acceptance Criteria (how do I know when I’m done?)

When search engine icon changes on user input in the "Search or enter address" control.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-13481)

**Comment by brampitoyo** [comment]
This issue was also mentioned by a participant in one of our search user study session.

Before we change any behaviour, let’s first discuss and consult with @Verdi.

**Comment by strugee** [comment]
One issue to consider here: URLs with spaces, while invalid, are still URLs used on the web platform. I most often hit this when searching Bugzilla using `bugzil.la/search term` - it's impossible to do this without manually writing out `%20`. There needs to be some way to override and insist that you're typing a URL.

**Comment by strugee** [comment]
Ack, looks like there's already #3306 filed for that - sorry for the noise

**Comment by AmyYLee** [comment]
@brampitoyo @Verdi for follow-up

**Comment by brampitoyo** [comment]
Hi @Verdi, I’m sure we’ll get to talk about this on our weekly meeting.

The behaviour that @kostrse proposes is something along the lines of Opera Touch, where the 🔍 icon would change to a 🌐 whenever the text entered into the address bar matches a URL.

Do you think that the usability win (ie. knowing exactly whether you’re about to search for something or go to a web address) outweighs the usability cost (ie. it’s sometimes less clear that you can search, because the icon keeps changing)?

<img width="300" src="https://user-images.githubusercontent.com/51007/84108583-a2a6f380-aa74-11ea-9d92-6f5de2fe3d4a.gif">

**Comment by AmyYLee** [comment]
@Verdi for follow-up

**Comment by Verdi** [comment]
Bram and I talked about this. I don't think the current behavior is confusing for people and the suggested solution will introduce flickering that will be difficult for people to decipher the cause of. We think we should leave it as is.

**Comment by kostrse** [comment]
@Verdi The current behavior is confusing. It's annoying to be unintentionally sent to Google when copy/pasting URLs with spaces or typos.

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807750

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
