### ISSUE TITLE
[Bug] The site title is using a font that is too small in custom tabs

### ISSUE THREAD

**Issue by ReekyMarko** [mozilla-mobile/fenix#5404]
![Screenshot of the problem](https://i.imgur.com/z9mIb4r.png)

This happens on every site I tested

```
Nightly 190916 18:01 (Build #12591814)
```

**Comment by NotWoods** [comment]
Duplicate of #5344. This just got fixed 😄

**Comment by ReekyMarko** [comment]
Wonder why I could not find it. Well thanks anyway!
