### ISSUE TITLE
[Bug] Two OK button are displayed on the Confirmation pop-up

### ISSUE THREAD

**Issue by softvision-sergiulogigan** [mozilla-mobile/fenix#5405]
**Browser / Version**
Firefox Fenix (Preview) 1.4.1

**Operating System**
OnePlus 6 (Android 9) - 1080 x 2280 pixels, 19:9 ratio (~402 ppi pixel density)

**Prerequisites:**
Login with a GitHub account that has unread notifications.

**Steps to reproduce:**
1. Navigate to: https://github.com/notifications
2. Tap on the "Mark as read" button.

**Expected Behavior:**
A confirmation pop-up with <Cancel> and <OK> buttons is displayed.

**Actual Behavior:**
A confirmation pop-up with two <OK> buttons is displayed.

**Notes:**
1. The issue is not reproducible on Chrome.
2. The issue is not reproducible on Nightly.
3. Screenshot attached.

![image](https://user-images.githubusercontent.com/16573771/65143976-ee18fd80-da1e-11e9-9764-a7d66e62f6fb.png)

**Comment by ekager** [comment]
Hm if it's not happening on Nightly or 2.0 then we can probably close this because we are releasing 2.0 now :)

**Comment by softvision-sergiulogigan** [comment]
Yup... it's fixed.

![image](https://user-images.githubusercontent.com/16573771/65225034-08111980-dacd-11e9-9baa-6358f5d86e7f.png)
