### ISSUE TITLE
[Bug]Fenix rendering different fonts when the System Font is changed.

### ISSUE THREAD

**Issue by thanuj10** [mozilla-mobile/fenix#5417]
## Steps to reproduce
1. Change system fonts
2. Open Fenix
3. Browse Google search or any website

### Expected behavior
Fenix renders different, weird looking fonts

### Actual behavior
Fenix renders the correct fonts.

### Device information

* Android device: Nokia 6.1 Plus/Android 9.0
* Fenix version: 2.0.0

![GT1](https://user-images.githubusercontent.com/43717642/65211546-bfe9fb00-dabc-11e9-8284-ea9004a06978.png)

**Comment by buttercookie42** [comment]
See [bug 1505650](https://bugzilla.mozilla.org/show_bug.cgi?id=1505650#c10).

**Comment by ekager** [comment]
See also #5628 : with non default emoji set on user's phone, certain emojis did not display properly

**Comment by neekless** [comment]
@thanuj10 I have a workaround for this

1. Go to `about:config`
2. Search for `font.name-list.sans-serif.x-western`
3. Add the font-family of the font you're using as your system font
![Screenshot_20200113-170405_1](https://user-images.githubusercontent.com/22426822/72243419-ce1bd400-35e3-11ea-8563-3cfd4bd5aaf5.jpg)
E.g. I'm using Inter and InterCondensed as my system font so I had to add them in.

This also works for the Emoji problem in #5628
![Screenshot_20200113-170642](https://user-images.githubusercontent.com/22426822/72243540-1d620480-35e4-11ea-86e6-591e32d50aff.jpg)
I'm using JoyPixels as my system Emoji and after appending it to the config the country flags show properly again.

**Comment by yoasif** [comment]
Had previously filed a dupe here https://github.com/mozilla-mobile/fenix/issues/14840, FYI.

**Comment by makotokato** [comment]
No way to get system font if using Android 9 or old version.

https://bugzilla.mozilla.org/show_bug.cgi?id=1677671 will be one of improvements if changed new system font isn't generic Android fonts such as Noto Sans and using Android 10+.

**Comment by vrindavan** [comment]
Why is this closed with WON'T FIX?
