### ISSUE TITLE
Sessions-unclickable after navigating away

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#542]
## STR
1. Search anything
2. Press tabs button to go home
3. Tap menu
4. Open settings
5. Press Back
6. Try to tap on your session or close it

## Expected
Session opens in browser fragment

## Actual
No action is taken

## Device Info
Samsung Galaxy S9 8.0.0

I wonder if we're stopping the observation of these button presses when we navigate away and not starting them again onResume?

Likely related: #541

**Comment by boek** [comment]
This was fixed with #525 and that caused #541
