### ISSUE TITLE
[Bug] Tests are broken on Windows

### ISSUE THREAD

**Issue by Dexterp37** [mozilla-mobile/fenix#5420]
## Steps to reproduce
Run any test that's run with `RobolectricTestRunner` (e.g. `BookmarkAdapterTest`)

### Expected behavior
The test executes and passes.

### Actual behavior
The test breaks with an obscure `Resources$NotFoundException` exception .

Fenix is using Robolectric 4.2, while Android Components is using Robolectric 4.1. Version 4.2 is known to be broken on Windows. [Version 4.2.1 fixes this](https://github.com/robolectric/robolectric/releases/tag/robolectric-4.2.1)

**Comment by mawen7** [comment]
Since fenix is now on robolectric 4.3.1 tests pass on Windows.
Last remaining failure (unrelated to robolectric) will be fixed once https://github.com/mozilla-mobile/android-components/pull/9209 makes it into fenix.
