### ISSUE TITLE
[Bug]share sheet doesn't hide when touched on translucent area

### ISSUE THREAD

**Issue by Scripterr** [mozilla-mobile/fenix#5421]
## Steps to reproduce
1. Open a webpage.
2. Select share option from QAB.
3. Now click on the translucent area, from where you can see webpage.
### Expected behavior
The share sheet hide out of view and web page can be full seen.
### Actual behavior
Share sheet doesn't hide from clicking on the translucent area.
### Device information

* Android device: 8.0.0
* Fenix version: Nightly 190918 18:01 (Build #12611806)
📦: 13.0.0, 3cb2ac19c
🦎: 71.0a1-20190916093313
### Note:
This look like a regression because before you can use this feature.

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on Nightly build #12651809 from 22/9 using the following devices:
• Google Pixel 3a (Android 9)
• Samsung Galaxy Note 9 (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

► Video
![20190923_124926](https://user-images.githubusercontent.com/51314259/65416796-4d9d5180-de01-11e9-8026-e45fb637af16.gif)
