### ISSUE TITLE
[Bug] Search engines not synchronized

### ISSUE THREAD

**Issue by vicanfon** [mozilla-mobile/fenix#5423]
## Steps to reproduce

Writing a shortcut of already created search engine on firefox desktop doesn't work on firefox preview.
For instance "u music" doesn't for launching a search on youtube with the search engine "https://www.youtube.com/results?search_query=%s". I can see that the bookmark is properly synchronized.

### Device information

* Android device: ?
* Fenix version: Nightly 190918

**Comment by AaronMT** [comment]
I don't believe search engines syncing is planned at the moment.

**Comment by NotWoods** [comment]
Blocked by #5489

**Comment by liuche** [comment]
Dupe of #2497
