### ISSUE TITLE
[Bug] Play icon on open tab 

### ISSUE THREAD

**Issue by topotropic** [mozilla-mobile/fenix#5428]
## Steps to reproduce
1. Open ableton.com
2. Long press on one of the featured stories, for example "A Personal Take: Erin Barra...."  and open in new tab
3. Go to home

### Expected behavior
No play icon on open tab I just opened in background

### Actual behavior
There's a play icon on open tab

### Device information

* Android device: ?
* Fenix version: ?

**Comment by sblatz** [comment]
@pocmo is this an AC issue? We're just listening for the notification that media state has changed, so it doesn't feel like this is on the Fenix side.

That being said, it's possible https://github.com/mozilla-mobile/fenix/pull/5273 will fix this?

**Comment by ekager** [comment]
Not fixed by #5273 still seeing weird behavior following STR

**Comment by sblatz** [comment]
I'm going to open an issue in AC about this.

**Comment by pocmo** [comment]
What's interesting about this is that only the tabs tray shows the "play" icon but we are not showing any media notification.. 🤔

**Comment by pocmo** [comment]
Fixed in AC 15.0.0. Fenix is not using that snapshot just yet:
https://github.com/mozilla-mobile/fenix/blob/master/buildSrc/src/main/java/Dependencies.kt#L38

**Comment by pocmo** [comment]
@boek @sblatz I assume this would need to be added to the 2.2 milestone (since it's in AC 15.0.0). But this milestone does not exist yet. :)

**Comment by sblatz** [comment]
@pocmo that's correct. Let me just make that right now 😄

**Comment by AndiAJ** [comment]
Hi, I've just check on **Nightly Build #12681804 from 25/9** using the following devices:
• Google Pixel 3a (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

Not sure to what extent, the actual behavior is the expected one.
On all the bove mentioned devices, after navigating to the home screen the play icon is visible for a couple of seconds and afterwards disappears. 

► Video
![20190926_115334](https://user-images.githubusercontent.com/51314259/65675250-913cc900-e056-11e9-814b-e2aa8d3ff530.gif)

@pocmo , could you please review and advise? :)

**Comment by pocmo** [comment]
@AndiAJ Sorry, I should have been more clear: The change is only in AC right now and has not made it to Fenix builds just yet. It depends on Fenix updating to the latest AC version, which should happen with this PR: https://github.com/mozilla-mobile/fenix/pull/5578

**Comment by AndiAJ** [comment]
Will re-test once the [AC update will be merged ](https://github.com/mozilla-mobile/fenix/pull/5578#issuecomment-535430383)

Based on this I'll remove the QA needed label.

**Comment by sblatz** [comment]
Merged 15.0 SNAPSHOT. Should be good to test this in the next nightly / on master.

**Comment by AndiAJ** [comment]
Hi, verified as fixed on **Nightly Build #12700627 from 27/9** using the following devices:
• Google Pixel 3a (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

► Video
![20190927_111232](https://user-images.githubusercontent.com/51314259/65754229-3fa94280-e119-11e9-8c69-3f7424f1a433.gif)
