### ISSUE TITLE
Allow swipe to close tab

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#543]
It'd be nice if, on the home screen, I could swipe to the left or right to kill a tab I have open instead of pressing the "X" button.

**Comment by bonjour81** [comment]
Hello,
It may be also applied to saved sessions, just "swipe" left or right to delete instead of pressing "⋮" and then delete.
The list may be long to delete after some time...

**Comment by lime124** [comment]
sorry forgot to close - i added it to the gestures bug
