### ISSUE TITLE
Switch between tabs by sliding over the address bar

### ISSUE THREAD

**Issue by Bak840** [mozilla-mobile/fenix#5434]
### Why/User Benefit/User Problem
I would like to be able to change tabs rapidly while I'm browsing by simply making my finger slide over the address bar. 
### What/Requirements
Left and right sliding gesture detection on the address bar.
### Acceptance Criteria (how do I know when I’m done?)
When I make my finger slide to the left on the address bar the browser switches to the first tab to the left of the current opened tab and same with the right gesture and the first tab to the right.

**Comment by ekager** [comment]
Closing for #3481
