### ISSUE TITLE
[Bug] tiny font in address bar input area

### ISSUE THREAD

**Issue by IlgazC** [mozilla-mobile/fenix#5435]
## Steps to reproduce
Tap address field to enter new URL/search
### Expected behavior
Input area moving to top and show characters typed in
### Actual behavior
Displays dot like tiny text, impossible to read in address bar

### Device information

* Android device: Nokia 5.1 plus running latest Android 9
* Fenix version: ?
![Screenshot_20190919-222648](https://user-images.githubusercontent.com/19528613/65274693-9d8fc600-db2c-11e9-966a-0f0390cf702e.png)

**Comment by AaronMT** [comment]
Reminds me of https://github.com/mozilla-mobile/fenix/issues/3827 but this is drastically miniscule. Is this only in the address-bar and only in Fenix? What would cause this?

**Comment by IlgazC** [comment]
I just got the current update and the issue is gone. Current build info:
Nightly 190919 18:00 (Build #12621820)
📦: 14.0.0, 0681a1e65
🦎: 71.0a1-20190916093313
