### ISSUE TITLE
Display build number on logo

### ISSUE THREAD

**Issue by dector** [mozilla-mobile/fenix#5437]
### Why/User Benefit/User Problem

Build version/number can be shown on "Firefox Preview" logo at least for Preview/nightly builds. It would be easier to get build info - now it requires few clicks with non obvious step to open "Settings".

### Acceptance Criteria (how do I know when I’m done?)

Build version number is displayed on the bottom right corner of "Firefox Preview" logo.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-13501)

**Comment by boek** [comment]
This has not revived any duplicates or other interactions since it was filed. We will not be moving this request to Bugzilla.
