### ISSUE TITLE
Smoother animation for session menu

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#544]
After pressing the three dot option on a session, the menu to take action on it appears. This animation is a bit laggy/jittery and we should improve it so it is smoother for the final product.

**Comment by AmyYLee** [comment]
@sblatz Hi, I see this marked as needs UX feedback. Do you mean the animation needs to be changed or is this a performance improvement bug?

**Comment by sblatz** [comment]
@AmyYLee This does not need UX feedback, and is in fact a performance concern. I will update the label to reflect this!
