### ISSUE TITLE
Show clear private data on quit menu item from Home Screen

### ISSUE THREAD

**Issue by ekager** [mozilla-mobile/fenix#5442]
### Why/User Benefit/User Problem
We added the option to [clear user data on quit from the browser screen](https://github.com/mozilla-mobile/fenix/issues/3700), but we should add the option to the home screen menu as well

### What/Requirements
- Need UX decision for if we want to add this menu item on home. 
- See #5323 for discussion of displaying some sort of progress/feedback to user while the deletion is happening

### Acceptance Criteria (how do I know when I’m done?)
- User is able to select "Quit" from home screen menu and launch deletion (list of what is deleted is set in settings)

**Comment by lime124** [comment]
@topotropic are you able to provide input while @AmyYLee is on PTO? thanks!

**Comment by topotropic** [comment]
Yes, makes sense to also put it in the home menu. Thanks!

**Comment by vesta0** [comment]
Why do we want to do this @ekager ?

**Comment by ekager** [comment]
This is about having it in the menu on Home and on BrowserFragment so the user can "Quit" from both of these places.

**Comment by vesta0** [comment]
OK so this is about adding "Quit" (not "Clear private data") to the homescreen menu.

**Comment by ekager** [comment]
Right same as #3700 but the action is "Quit"

**Comment by sv-ohorvath** [comment]
Verified as fixed on master (10/7).
