### ISSUE TITLE
[Bug] disabled history suggestions toggle not functional

### ISSUE THREAD

**Issue by nahuhh** [mozilla-mobile/fenix#5445]
![Screenshot_20190919-194723](https://user-images.githubusercontent.com/50635951/65289004-0d935180-db17-11e9-9da2-4f83f637fd93.png)
![Screenshot_20190919-194738](https://user-images.githubusercontent.com/50635951/65289012-1421c900-db17-11e9-8c05-8e74bed737bf.png)

## Steps to reproduce
- Setting > search  > turn off searching browsing history
- open a new tab and type  
### Expected behavior
No history is suggested
### Actual behavior
History is suggested
### Device information

* Android device: 8.1.0 
* Fenix version: Nightly 190919 18:00 (Build #12621820)
📦: 14.0.0, 0681a1e65
🦎: 71.0a1-20190916093313

**Comment by neekless** [comment]
Can't reproduce in Android 9 with the same fenix version

Search browsing history on
![Screenshot_20190920-111215](https://user-images.githubusercontent.com/22426822/65296677-b1e7b900-db54-11e9-9fbb-9ce33a1247a3.jpg)

Search browsing history off
![Screenshot_20190920-111229](https://user-images.githubusercontent.com/22426822/65296682-b613d680-db54-11e9-9930-b409f862e8a8.jpg)

**Comment by nahuhh** [comment]
If it's of any consequence, I have 8000+ items in history.

**Comment by darkwing** [comment]
I also cannot reproduce this on current master.

**Comment by nahuhh** [comment]
I am still able to reproduce this

1. Disabled all toggles under settings > search
2. Closed browser (optional)
3. Open browser and type the letter f
Result: I'm presented with 8 results from my history

This is running the latest nightly
