### ISSUE TITLE
[Bug] tracking toggle disappears when an exceptions is made  

### ISSUE THREAD

**Issue by nahuhh** [mozilla-mobile/fenix#5446]
## Steps to reproduce
1. Enable global tracking protection toggle
2. Go to a website, tap the shield and turn off tracking for that website
3. When the  website reloads, tap outside of the tracking popup to dismiss it

### Expected behavior
Shield icon disappears but tapping the padlock will allow you to turn tracking protection back on (mockup below) 
- Tapping either icon should bring up the same menu and the tracking toggle should be persistent. 
-  if the global setting is turned off it should be greyed out in the menu as per #2422 (it shouldn't disappear)

### Actual behavior
Toggle disappears and you have to go to settings > enhanced tracking protection > exceptions >  and delete the exception 
![20190919_220620](https://user-images.githubusercontent.com/50635951/65295200-a2557980-db2e-11e9-857f-063b65e5250d.gif)

### Device information

* Android device: 8.1.0 
* Fenix version: Nightly 190919 18:00 (Build #12621820)
📦: 14.0.0, 0681a1e65
🦎: 71.0a1-20190916093313

New mockup:
![Adobe_20190919_212312](https://user-images.githubusercontent.com/50635951/65292864-11c76b00-db27-11e9-804c-8234d408af36.png)

Old styling from #2422
![Site Information Panel - TP off in Settings@2x](https://user-images.githubusercontent.com/353960/57619994-c2c16600-7587-11e9-8d38-ae1df0c91f16.png)

**Comment by Amejia481** [comment]
This will be covered on https://github.com/mozilla-mobile/android-components/issues/3264

**Comment by julienw** [comment]
This seems fixed on my side (latest nightly).

**Comment by Amejia481** [comment]
It should be fixed

**Comment by ekager** [comment]
Oops didn't mean to close. Yes let's QA this but should be fixed

**Comment by nahuhh** [comment]
Appears to be fixed

**Comment by softvision-miralobontiu** [comment]
Verified as fixed with the latest Nightly build 11/25 with Huawei P9 Lite (Android 7), and Google Pixel 3 (Android Q).
