### ISSUE TITLE
overflow menu for multitasking mixes regular and private sessions

### ISSUE THREAD

**Issue by cadeyrn** [mozilla-mobile/fenix#545]
## Steps to reproduce

1. open a website A in a non-private session
2. switch to the private mode
3. open a website B in a private session
4. switch between private and non-private mode
5. click the button for the "current session" overflow menu
6. delete the sesion

### Expected / Actual behavior

Step 4: As expected: the non-private session shows only website A, the private session shows only website B.

Step 5: Unexpected: The dialog shows both website A and website B under the "current session" headline

Step 6: Deleting the session closes both the private as well as the non-private tab.

### Device information

* Android device: HTC U11 w/ Android 8.0.0
* Fenix version: Fenix revision 8293f6a7a71b139316fcc52bf6a8443785c2a6e7

**Comment by colintheshots** [comment]
At the time I started building this, private mode was not implemented yet. I'm on it.

**Comment by cadeyrn** [comment]
For the record: [0382665](/mozilla-mobile/fenix/commit/03826651dd0c4c84e7db7a4f38eae3340d3d80d1) fixed step 5 but not step 6. The "delete" button still deletes sessions from both modes.

**Comment by sv-ohorvath** [comment]
Verified as fixed.
