### ISSUE TITLE
Write more tests for IntentReceiverActivity

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#5458]
In the process of this we will need to rip lots of our code out of the overriden lifecycle functions.

**Comment by NotWoods** [comment]
Most of the core functionality has been put inside `IntentReceiverActivity#processIntent` so tests can just call that method and verify that the `intent` was adjusted properly.

**Comment by obarzpaw** [comment]
I would like to work on this.

**Comment by obarzpaw** [comment]
Can I use and add to dependencies espresso-intents? (https://developer.android.com/training/testing/espresso/intents#include-in-project)

**Comment by obarzpaw** [comment]
I've added PR to review, please check it. @NotWoods @sblatz
