### ISSUE TITLE
[Bug] Missing spacing between input and search engine selection on search view

### ISSUE THREAD

**Issue by boek** [mozilla-mobile/fenix#5460]
![image](https://user-images.githubusercontent.com/1250545/65352767-49bec480-dba0-11e9-8993-fc457bb3051f.png)

**Comment by ekager** [comment]
cc @sblatz did you mess with the margin here when adding the clipboard item?

**Comment by sblatz** [comment]
Yes, this is my bad!

**Comment by AndiAJ** [comment]
Hi **verified as fixed** on Nightly build #12651809 from 22/9 using the following devices:
• Google Pixel 3a (Android 9)
• Samsung Galaxy Note 9 (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

► Normal view
![rsz_screenshot_20190923-122422](https://user-images.githubusercontent.com/51314259/65416320-3e69d400-de00-11e9-960c-0dea9399616a.png)


► Fill link from clipboard
![rsz_screenshot_20190923-122458](https://user-images.githubusercontent.com/51314259/65415096-b682ca80-ddfd-11e9-9891-aca27ca81a86.png)
