### ISSUE TITLE
[Bug] Fix intermittent UI tests failures

### ISSUE THREAD

**Issue by rpappalax** [mozilla-mobile/fenix#5462]
Issue for tracking flaky tests that have been disabled  and/or need monitoring/investigation

disabling for now

shortcutSearchEngineSettingsTest
* fails on API 28
* fails on API 25
https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/5301034281545099442

firstRunHomeScreenItemsTest
* fails on API 28 
* pass on API 25
https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6144238044488467407

findInPageTest

createBookmarkFolderTest
* intermittent fails on API 25
* https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6875615479379426992/executions/bs.6e76b4dfcf000244/testcases/1

deleteMultipleSelectionTest
* intermittent fails on API 25
https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7989050493809544523/executions/bs.5923a059b9269db7/testcases/1

settingsPrivacyItemsTest
* occasional fails on both APIs
https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/5710036906344507291/executions/bs.ae85ed1a843bc612/testcases/1
```
 androidx.test.espresso.NoMatchingViewException: No views in hierarchy found matching: with text: is "Add private browsing shortcut"
View Hierarchy:
+>DecorView{id=-1, visibility=VISIBLE, width=1440, height=2560, has-focus=true, has-focusable=true, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=WM.LayoutParams{(0,0)(fillxfill) sim=#10 ty=1 fl=#8181
```
settingsDeveloperToolsItemsTest
*test not disabled, only one intermittent fail on API 28
```
 androidx.test.espresso.NoMatchingViewException
androidx.test.espresso.NoMatchingViewException: No views in hierarchy found matching: with text: is "Remote debugging via USB" 
```
deleteAllHistoryTest
- https://github.com/mozilla-mobile/fenix/issues/6859

HistoryTest: shareButtonTest():
- https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7805327148334262662/executions/bs.fc499129de0ccbd/test-cases

visitedUrlHistoryTest()
- https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6702892283514936613/executions/bs.3dddfdd786618673/testcases/1/test-cases

**Comment by AaronMT** [comment]
testDownloadNotification()

* intermittent fail on API 28 
https://console.firebase.google.com/u/1/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/8780279402119153460/executions/bs.e7261e4c00726c9e/testcases/1/test-cases

**Comment by AaronMT** [comment]
I don't think we need a meta anymore. Feel free to re-open if you disagree.
