### ISSUE TITLE
[Bug] Delete browsing data button is always enabled even when no checkboxes checked

### ISSUE THREAD

**Issue by ekager** [mozilla-mobile/fenix#5465]
## Steps to reproduce
- Uncheck all options

### Expected behavior
- There is nothing to selected, so button is disabled

### Actual behavior
►Video
![20190916_171322](https://user-images.githubusercontent.com/51314259/64966189-036b1c00-d8a7-11e9-8e79-99140988aafd.gif)

### Acceptance criteria
- [ ] When no checkboxes are checked, the delete button is disabled

This does NOT need to check for whether the checked items have no delete-able content (e.g. Tabs is checked, but there are no open tabs).

**Comment by julKali** [comment]
I would like to work on this! Or is anyone else on it already?

**Comment by ekager** [comment]
Yes you can work on this! @julKali

**Comment by julKali** [comment]
It seems like this is intentional. Since we do not have the necessary Gecko APIs yet to properly determine if there is data to be deleted for each category, the disabled state was disabled by @colintheshots in https://github.com/mozilla-mobile/fenix/commit/2b9efccfca4ef23a48e19c7934955a0bff32a409

**Comment by liuche** [comment]
@julKali that's only for the initial state, where the checkboxes are all checked initially. https://github.com/mozilla-mobile/fenix/commit/758f4c13ec001b7735c42d65e22b359cc3c9d4e5#diff-72f1508822a7515db9a70c2034b4af60R65

However, we can tell if all the checkboxes in the UI have been unchecked, and then disable the delete button.

**Comment by julKali** [comment]
I think it's not only about disabling the button when nothing is checked but to also disable it if f.e. only "Open Tabs" is selected but no open tabs are currently open. Or did I misread this?
In any case, I'm currently a bit busy so feel free to assign someone else!

**Comment by obarzpaw** [comment]
I would like to try fixing this one out.

**Comment by liuche** [comment]
For a first pass, we want to disable the delete button if no checkboxes are selected. @julKali you're correct that we'd ideally want to also do that if there are no tabs open, but this is at least a step in the right direction!

**Comment by shangeethsivan** [comment]
I have added a PR for this please check it out. @liuche @ekager

**Comment by obarzpaw** [comment]
That's great, but this issue was assigned to me ;/

**Comment by shangeethsivan** [comment]
Sorry I saw that there was not interaction for past 11 days and it seemed to be a small fix.

**Comment by ekager** [comment]
Reopening for QA

**Comment by sv-ohorvath** [comment]
Verified as fixed on Nightly 10/21.
