### ISSUE TITLE
[Bug] Long Press on Toolbar in Custom Tab Only Copies Host 

### ISSUE THREAD

**Issue by ekager** [mozilla-mobile/fenix#5468]
## Steps to reproduce
Open GitHub link from slack
Long press on custom tab toolbar
Select copy 

### Expected behavior
Have the GitHub Issue in my clipboard 

### Actual behavior
Have "GitHub.com" in my clipboard 

### Device information

* Android device: ?
* Fenix version: ?

**Comment by AndiAJ** [comment]
Hi, this is **still reproducible** on Nightly Build #12671258 from 24/9 using the following devices:
• Google Pixel 3a (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• OnePlus A3 (Android 6.0.1)

#### Note
I've used Gmail to check the above described issue.
► Video
![20190925_110824](https://user-images.githubusercontent.com/51314259/65582542-4bb0cb00-df86-11e9-8f4e-45dab879ca87.gif)

**Comment by AndiAJ** [comment]
I've just had a chat with @mcarare and will retest on the next nightly build.

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on Nightly Build #12681804 from 25/9 using the following devices:
• Google Pixel 3a (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

► Video
![20190926_121612](https://user-images.githubusercontent.com/51314259/65676260-3dcb7a80-e058-11e9-8c94-563ffeae4f60.gif)
