### ISSUE TITLE
[Bug] Private window stays open after you open a site in private mode and close fenix

### ISSUE THREAD

**Issue by thewhitetulip** [mozilla-mobile/fenix#5469]
## Steps to reproduce
1.open a private tab
2. Close the browser

### Expected behavior
Private mode should be disabled

### Actual behavior

Private mode is still on, although the tab itself is closed.

### Device information

* Android device: ?
* Fenix version: 1.4.1

**Comment by athomasmoz** [comment]
Thank you for logging. We believe this has been fixed as part of another story. We're unable to reproduce, please re-open if you still experience the issue.

**Comment by thewhitetulip** [comment]
Can't recreate.
