### ISSUE TITLE
PAC file support

### ISSUE THREAD

**Issue by AndriiZ** [mozilla-mobile/fenix#5470]
Firefox for Android supports PAC file, so I can use same approach on desktopn and mobile. I can not find any settings in Fenix toset up pac file. Is it poosible?

**Comment by AaronMT** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1525486

**Comment by AndriiZ** [comment]
It is possible to create proxy rule per site using supported FoxyProxy addon
But creating rules for more than 3 sites is extremely hard.
