### ISSUE TITLE
Support viewing XML files

### ISSUE THREAD

**Issue by BeeeWall** [mozilla-mobile/fenix#5473]
It would be a nice feature to be able to view an XML file in the browser, rather than immediately downloading it. I could swear Fennec could do this but when I try it just downloads it so I guess not.

**Comment by buttercookie42** [comment]
https://hg.mozilla.org/mozilla-central/raw-file/9136070a0561cb169b01569b2346a1e3aad387dd/mobile/android/app/src/main/res/xml/preferences_advanced.xml
works for me in all browsers (Fennec and Fenix), so maybe you just happened to pick XML files where the server uses `Content-Disposition: attachment` or something like that?

**Comment by BeeeWall** [comment]
Works for me too, I guess that must be it.
