### ISSUE TITLE
[Bug] There is too much space between ETP shield and security icon

### ISSUE THREAD

**Issue by softvision-miralobontiu** [mozilla-mobile/fenix#5480]
## Steps to reproduce
1. Open a webpage in normal or private browsing.
2. Observe the navigation bar, more precisely, the ETP shield and the security lock icon.

### Expected behavior
There shouldn't be so much space between the two icons.

### Actual behavior
There is too much space between the two icons. This behavior is also displayed in custom tabs.

### Device information
* Android device: all
* Fenix version: Nightly build 9\22

![Screenshot_20190923-113231](https://user-images.githubusercontent.com/40694158/65412438-e62ed400-ddf7-11e9-8a0c-bb25f1be3aa9.png)

![Screenshot_20190923-113221](https://user-images.githubusercontent.com/40694158/65412136-440eec00-ddf7-11e9-987b-265b925366ce.png)

**Comment by cadeyrn** [comment]
should be improved by https://github.com/mozilla-mobile/android-components/pull/4478

**Comment by NotWoods** [comment]
Duplicate of #4560. Should be fixed now.
