### ISSUE TITLE
[Bug] Crash when opening tab from collection

### ISSUE THREAD

**Issue by csadilek** [mozilla-mobile/fenix#5486]
New crash in Nightly that needs investigation:
https://sentry.prod.mozaws.net/operations/fenix-nightly/issues/6326356/

Happens quite frequently, but can not reproduce yet.

**Comment by csadilek** [comment]
STR:
- Open a page
- Open a link using the context menu (e.g. open in new tab) to open a "child" tab
- Switch to home fragment and store child tab in a collection
- Close the parent tab

From here on, Fenix will crash every time the child tab is (re-)opened from its collection, as it is stored with the ID of its parent, which doesn't exist anymore.

In A-C, we update the parent ID of all tabs when the parent is deleted, but this does not apply to the collection state (which is a copy).

Possible solutions:
- Be tolerant when adding session and ignore the fact that the parent could no longer be there
- Update the collection state to remove the parent ID if it was deleted

**Comment by csadilek** [comment]
This is fixed in A-C and should no longer be reproducible in the next Nightly.

**Comment by softvision-miralobontiu** [comment]
Verified as fixed with the latest Nightly build from Play Store 190925 (#12681805) with Huawei Honor 8 (Android 7), and Samsung Galaxy Note 8 (Android 9). The app didn't crash, following the steps provided.
