### ISSUE TITLE
Fennec migration: Figure out adjust and leanplum tokens

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/fenix#5490]
Follow-up from: #4873

We need to figure out whether we want to use Fennec / Fenix or new tokens for Leanplum and Adjust.

**Comment by st3fan** [comment]
I added a release engineering label here because I think this is mostly a decision to be made by the Product / Marketing / Growth teams and then a matter of setting up the right API keys?

**Comment by pocmo** [comment]
For the other tokens I updated the secrets service. I have a mail thread with Loren about picking a token. There's no decision yet.

**Comment by pocmo** [comment]
The recommendation from Loren is to use the Fennec tokens for Adjust/Leanplum in the Fenix production release.
