### ISSUE TITLE
[SPIKE] Save page offline

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#5494]
Please investigate this feature and identify dependencies. 

For UX and Product: Let's assess how widely this feature is used before designing it. 

[Feature Brief](https://docs.google.com/document/d/1_lbVYHouBVqYBrt41MDA8L1PqUNJQNNyD2nRAu8o9oc/edit#)

[Meta](https://github.com/mozilla-mobile/fenix/issues/219)

**Comment by vesta0** [comment]
Closing for now, not a requirement for Q1
