### ISSUE TITLE
If Lockwise not installed, point out that people can use Lockwise as a Login Manager

### ISSUE THREAD

**Issue by liuche** [mozilla-mobile/fenix#5498]
### Why/User Benefit/User Problem
As a user, I want to know about advanced password management features that are available to me through my Firefox Account, so I can better protect my privacy and identity. 

### What/Requirements
* Identify cross-promotion points for Lockwise
* UX for suggesting Lockwise and Monitor in Fenix

### Acceptance Criteria
- I can learn about Lockwise and monitor when I sign into my Firefox account.
- I can learn about Lockwise and monitor as a benefit of having a Firefox account.
- I learn about lockwise when I am poking around my logins in Fenix settings.

**Comment by liuche** [comment]
Breaking this out of #550

**Comment by boek** [comment]
@vesta0 will sync up with @liuche

**Comment by AmyYLee** [comment]
@vesta0 @lime124 I'm reviewing the Acceptance Criteria and want to ensure it's appropriately assigned for UX. 

• I can learn about Lockwise and monitor when I sign into my Firefox account. - This seems to belong more to the FxA team?

• I can learn about Lockwise and monitor as a benefit of having a Firefox account. - This seems to belong more to the FxA team?

• I learn about lockwise when I am poking around my logins in Fenix settings. - Fenix UX (Amy)

**Comment by mheubusch** [comment]
@liuche @lwa-moz Can we consider building an event in leanplum for this banner in the login manager workstream? That would allow us to A/B test different messaging approaches.

**Comment by AmyYLee** [comment]
This is waiting on Fenix login manager to be completed before we can work on this.
