### ISSUE TITLE
Please Include Build Instructions

### ISSUE THREAD

**Issue by ryanleesipes** [mozilla-mobile/fenix#55]
Excited to play around with this and make contributions. Please provide build instructions (going to try and build this evening anyway).

**Comment by pocmo** [comment]
This is a pretty standard Android app when it comes to building it. Checkout and open the root folder in Android Studio. Pick a "nightly...Debug" build variant that matches the architecture of your device/emulator (arm, x86, aarch64).

There's not much to contribute here yet. This app is mostly assembled from our Android Components:
- https://github.com/mozilla-mobile/android-components

Contributing to the Android Components project is a good way to contribute to this project here and other Mozilla Android projects (Focus/Klar, Firefox for Fire TV, Notes by Firefox, Rocket, ...)

* Good first issues: https://github.com/mozilla-mobile/android-components/labels/good%20first%20issue
* Help Wanted: https://github.com/mozilla-mobile/android-components/labels/help%20wanted

**Comment by justyntemme** [comment]
@ryanleesipes the current Docker build file work great. Simply run `sudo docker build . -t fenix` then `sudo docker -it fenix --entrypoint /bin/bash`
