### ISSUE TITLE
[Bug] resindrake.net Stops Loading

### ISSUE THREAD

**Issue by Krutonium** [mozilla-mobile/fenix#5501]
## Steps to reproduce
Open Fenix, and Load https://resindrake.net/

### Expected behavior
Site loads and functions, including fancy color changing effects, text, and links.

### Actual behavior
Image Loads slowly, Fancy Color Changing effects run at 1/10 of 1 FPS at best, text never loads, background dots somtimes animate, but usually do not.

If left for an extended period, (Like when I went to get the screenshot for the version), the site will load, and be visible, but then break again as soon as I try to use it)

### Device information
LG G5 on Android 8
LG G3 on Android 8.1

Both running the appropriate builds from this page https://github.com/mozilla-mobile/fenix/wiki/Fennec-migration (32 and 64 bit versions)

![Screenshot_2019-09-23-20-55-13](https://user-images.githubusercontent.com/3945538/65473204-c2de4600-de44-11e9-910e-daf1dcfedb28.png)

**Comment by NotWoods** [comment]
This might be a Gecko issue, since the site is slow to load on Firefox desktop as well.

**Comment by Krutonium** [comment]
It loads decently fast on my Desktop Firefox.

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Fenix Nightly Build 200713 from 7/13`** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)

► Video
![20200713-122746](https://user-images.githubusercontent.com/51314259/87289330-2c7b2e00-c505-11ea-8c50-f43bec17cd1a.gif)
