### ISSUE TITLE
File low-hanging fruit in FenixApplication.onCreate

### ISSUE THREAD

**Issue by hawkinsw** [mozilla-mobile/fenix#5506]
Let's file actionable bugs to address the low-hanging fruit of so we can 1) prioritize them & ensure we're working on the most important things and 2) ensure our backlog has actionable works for devs.

### Acceptance criteria
- File bugs to address the low-hanging fruit (and some larger diminishing returns) in `FenixApplication.onCreate`
- Notify Slack channel when issues are filed

Old issue summary below.

---

This is a meta-issue that tracks the areas that we can optimize to speed up creation of the `FenixApplication` (`FenixApplication.onCreate`). 

1. #5183 
Initializing HTTP components within megazord takes a significant amount of time. This problem has already been solved upstream (https://github.com/mozilla/application-services/issues/1066), but the solution needs to be integrated into `FenixApplication`. Initializing megazord takes about fifteen percent of all the time required by `FenixApplication.onCreate`.
2. #5182 
Loading experiments (`loadExperiments` and `ExperimentsInternalAPI.initialize`) takes about one quarter of all the time required by `FenixApplication.onCreate`. 

@csadilek Can you change the label on this to eng:performance? Thank you!

**Comment by mcomella** [comment]
FenixApplication.onCreate takes 28.80% of cold startup time.

Here's a breakdown of what percentage of `FenixApplication.onCreate` each method takes up. Each indent indicates a method that was called by the unindented method; the percentages of these methods is the percentage of `FenixApplication.onCreate` each method takes up.
```
35.54% - ReleaseMetricController.start
  28.87% - LeanplumMetricsService.start
    13.92% - MozillaProductDetector.getMozillaBrowserDefault / getInstalledMozillaProducts
      Browsers
    11.21% - Leanplum.start()
15.04% - Core.getEngine
  09.23% - GeckoProvider.getOrCreateRuntime
  03.83% - DebugConfig.fromFile - DEBUGGABLE BUILDS ONLY
  02.48% - GeckoEngine.init
09.98% - Application.setupPush
  06.99% - BackgroundServices.init
  03.90% - Core.getSecureAbove22Preferences()
    SHARED WITH Components.getCore
09.13% - Components.getCore
  05.76% - SecureAbove22Preferences.getString()
  03.90% - Core.getSecureAbove22Preferences()
    SHARED WITH setupPush
07.37% - Core.getSessionManager()
  01.67% - getIcons()
04.86% - Application.setupMegazord()
04.77% - Analytics.getCrashReporter()
03.16% - ExperimentsInternalAPI.initialize
02.17% - Application.loadExperiments
02.65% - Application.setDayNightTheme()
```

**Comment by mcomella** [comment]
Filed all tractable issues >= 5% (and some smaller). These are ordered by priority recommendation:

- 13.92%: https://github.com/mozilla-mobile/fenix/issues/7425 Browsers.all
- 9.66% https://github.com/mozilla-mobile/fenix/issues/7450 `SecureAbove22Preferences`
- 9.98% https://github.com/mozilla-mobile/fenix/issues/6730 delay Push (already filed & in progress)
- 5%+: https://github.com/mozilla-mobile/fenix/issues/5182 Combined experiments init (already filed)
- 1.6%: https://github.com/mozilla-mobile/fenix/issues/7441 getLogger
- 7.37%: https://github.com/mozilla-mobile/fenix/issues/7451 Core.getSessionManager investigation

- 11.21%: https://github.com/mozilla-mobile/fenix/issues/7448 Leanplum.start() explorations
  - #7442 intermittent Leanplum startup issues (outside Application.onCreate)
  - https://github.com/mozilla-mobile/fenix/issues/6679 Old issue wrt Leanplum init

- 5.67%: https://github.com/mozilla-mobile/fenix/issues/7452 setupCrashReporting (though 1.55% is #7441)
