### ISSUE TITLE
Cropped Sessions Info Box

### ISSUE THREAD

**Issue by Sdaswani** [mozilla-mobile/fenix#551]
## Steps to reproduce
I believe you have to change your display's font size (I make it bigger) and then launch Fenix.

### Expected behavior
No cropping of the display text.

### Actual behavior
See screenshot.
![screenshot_20190216-080625_fenix](https://user-images.githubusercontent.com/4879954/52902184-6c2fd000-31c2-11e9-816f-8f06e9f79ece.jpg)

### Device information

* Android device: Galaxy S8
* Fenix version: Nightly from today

I showed this to @sblatz already, he says it should be a quick fix.

**Comment by Cheap-Skate** [comment]
I see this too with default font size on a Galaxy S7 Android 8.0.0
