### ISSUE TITLE
Always select full URL when tapping the address bar

### ISSUE THREAD

**Issue by djc** [mozilla-mobile/fenix#5512]
### Why/User Benefit/User Problem

When I load Hacker News, it automatically redirects to https://news.ycombinator.com/news. However, when I then tap the address bar in order to navigate somewhere else, I get this weird dual selection of the origin (grey background) and path-after-initial-slash (purple background). If I then start typing in order to navigate to another site, only the path-after-initial-slash gets replaced, which means I then have to manually remove the entire URL before I type a new one.

### What/Requirements

Make navigating in this case easier, and better aligned with desktop Firefox.

### Acceptance Criteria (how do I know when I’m done?)

When tapping the address bar, the full URL should always be selected. Starting to type in that state should always replace the full URL.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-13553)

**Comment by s-ankur** [comment]
Hi, this is what happens currently, can you please check if it is satisfactory?

**Comment by csadilek** [comment]
This seems to be outdated and fixed a while ago. Closing, but please re-open if you still experience problems.
