### ISSUE TITLE
[Bug] Page shortcuts on homescreen open in private mode when "Launch links in a private tab" is ON

### ISSUE THREAD

**Issue by klint** [mozilla-mobile/fenix#5518]
## Steps to reproduce
Set "Launch links in a private tab" to ON in Fenix settings
Open a page (in normal mode), create a shortcut for it on the phone's homescreen
Click on the homescreen page shortcut

### Expected behavior
The page should open in normal mode as it was created in normal mode.
The ""Launch links in a private tab" should only apply to links opened by other applications, not to Fenix page shortcuts, shouldn't they?

### Actual behavior
The page opens always in a private tab
### Device information

* Android device: Redmi Note 7
* Fenix version: 12661843

**Comment by sblatz** [comment]
@AmyYLee can you please confirm if this is the expected behavior? This seems correct to me given our current implementation.

**Comment by AmyYLee** [comment]
The current behavior is correct. "Launch links in a private tab" should apply to all links and not only 3rd party apps.

**Comment by sblatz** [comment]
Closing as expected behavior

**Comment by klint** [comment]
Thanks for the clarification (even if I'm not satisfied with the current behaviour ;) )
If you don't mind : on a broader perspective, the way page shortcuts on homescreen behave seems to be lacking of some consistency for the moment: to sum up, shouldn't we be able to create shortcuts in private mode and expect them to always open in private mode on one hand, and create shortcuts in public mode and expect them to always open in public mode on the other hand?  Thanks
