### ISSUE TITLE
[Bug] BrowserFragment URL extends outside background box in RTL

### ISSUE THREAD

**Issue by ekager** [mozilla-mobile/fenix#5524]
![Screenshot_20190924-092044](https://user-images.githubusercontent.com/25442310/65530772-682d0480-dead-11e9-88d3-c90c515b8775.png)

**Comment by mcarare** [comment]
@ekager I can reproduce this without RTL
![out](https://user-images.githubusercontent.com/48995920/65881471-1e0bbd80-e39c-11e9-9057-ff0d715c4ab9.png)

**Comment by pocmo** [comment]
> CC @pocmo / @Amejia481 I know you had been working on refactoring the toolbar. Adding RTL languages is in our upcoming plans and I assume we'll need to flip the entire toolbar layout to look "normal" in RTL layouts? Do you have an issue already for this? Happy to file one.

Yeah, correct, we are refactoring the internals and will start to use `ConstraintLayout` internally - which should hopefully fix RTL issues too.

Nevertheless, please feel free to file those in AC and we will check against the refactoring and either close or fix. :)

**Comment by pocmo** [comment]
This is btw. how the current state of the refactoring looks like when forcing RTL mode. Looks better but not right yet. Let's definitely file. :)

![Screenshot_1569854718](https://user-images.githubusercontent.com/89638/65889584-c96b4100-e3a1-11e9-97bd-6e64e794bf65.png)

**Comment by ekager** [comment]
Closing because this looks better !
