### ISSUE TITLE
Fennec migration: Migrate telemetry setting

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/fenix#5525]
When migrating from Fennec to Fenix we want to retain the telemetry setting. Fenix uses a unified telemetry setting (like Firefox desktop), while Fennec still has two: FHR and telemetry. We are going to map those two values to a single value when migrating - with the FHR setting taking precedence.

**Comment by ebalazs-sv** [comment]
Verified as fixed on Release, Beta, Nightly migration build 12/16 with Huawei Honor 8 (Android 7.0), Samsung Galaxy S8 (Android 9).
The Fennec Firefox Health Report setting Enabled/Disabled is migrated on Fenix Data Collection -> Usage and technical data as Enabled/Disabled.
I will move this to Done.

**Comment by pocmo** [comment]
Great. Thank you!

**Comment by ebalazs-sv** [comment]
This was verified in the previous comment. 
I will move this to Done. Thanks!
