### ISSUE TITLE
Fennec migration: Add Fennec metrics

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/fenix#5526]
Fennec uses its own telemetry system and Fenix uses Glean. This means that some "telemetry values" may get reset (specifically: telemetry id and profile date). Instead of reusing the Fennec values in Glean, we want to add new metrics that record those Fennec values. In addition to that we may want to save those Fennec values to a "safe space" where they do not get lost once we remove some old Fennec files.

**Comment by pocmo** [comment]
Duplicate of #https://github.com/mozilla-mobile/android-components/issues/5114

**Comment by ebalazs-sv** [comment]
Moving this to Done, since this is a Duplicate.
