### ISSUE TITLE
[Bug] Background media not working

### ISSUE THREAD

**Issue by mcladyz** [mozilla-mobile/fenix#5527]
## Steps to reproduce
Open a page playing audio/video, i.e. Youtube and change application (Firefox goes background).

### Expected behavior
The audio still plays and a notification is displayed.

It's said [here](https://support.mozilla.org/en-US/kb/whats-new-firefox-preview?as=u&utm_source=inproduct ) that this should work
> A notification that audio/video is playing with the option to pause or play it. 

### Actual behavior
Audio stops

### Device information

* Android device: Google Pixel XL, Android version 9
* Fenix version: 2.0.0

**Comment by pocmo** [comment]
It should work with any page but YouTube. YouTube detects if its in the background and it completely stops playback in that situation.

**Comment by Dunexus** [comment]
@mcladyz 
When WebExtensions support will be added to Fenix, you will be able to use this addon : [Video Background Play Fix](https://addons.mozilla.org/fr/firefox/addon/video-background-play-fix/) to block the Page Visibility API and the Fullscreen API and enjoy background media even on YouTube.

**Comment by mcladyz** [comment]
Ok. Tested to work ok on Wikipedia.
