### ISSUE TITLE
[Bug] Sort tabs newest to oldest when creating a Collection

### ISSUE THREAD

**Issue by topotropic** [mozilla-mobile/fenix#5528]
## Steps to reproduce
1. Open a few tabs
2. Save open tabs to Collection

### Expected behavior
Tabs are in the same order when in Collection as under "Open tabs" sorted newest to oldest

### Actual behavior
Tabs are sorted oldest to newest when added to a Collection

### Device information

* Android device: ?
* Fenix version: ?

**Comment by mcarare** [comment]
@topotropic This will also imply that new tabs added in a collection will be on top of the old ones. Following the same principle as in opened tabs list and collections list. 
I think this should always have been the order of tabs inside a collection (newest on top), but please confirm this. TY!

**Comment by topotropic** [comment]
@mcarare yes, makes sense – newly added sites appear on top of old one. Thanks!

**Comment by sv-ohorvath** [comment]
Verified as fixed on Nightly 10/21
