### ISSUE TITLE
[Bug] Show WebRender status in about:support

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/fenix#5532]
## Steps to reproduce

1. Navigate to ```about:support```
2. Look for "WebRender" or compositor

### Expected behavior

Some reference to WebRender

### Actual behavior

No reference to WebRender.

### Device information

* Android device: Pixel 2
* Fenix version: 

"Nightly 190924 12:53" (Build #12671259)
📦: 14.0.0, 186fa2396
🦎: 71.0a1-20190923094800

**Comment by yoasif** [comment]
Blocked on https://bugzilla.mozilla.org/show_bug.cgi?id=1583336

**Comment by boek** [comment]
Looks like the bugzilla was fixed. Is this still an issue @yoasif?

**Comment by kbrosnan** [comment]
This looks good on Nightly and a Pixel 3.

**Comment by yoasif** [comment]
Yeah, it looks fine.
