### ISSUE TITLE
[Bug] Open thumbnailed image in new tab

### ISSUE THREAD

**Issue by bubi-luka** [mozilla-mobile/fenix#5535]
## Steps to reproduce
Go to a web page with thumbnail image gallery (https://www.w3schools.com/howto/howto_css_thumbnail.asp). Press and hold an thumbnailed image until a menu appears. Click Open link in new tab.

### Expected behavior
Image in new tab openes with width or height 100% according to screen size.

### Actual behavior
The image is virtually invisible. On extreme zoom you notice a small version of the image. The tab page display the tab with an image as scalled 0%. 

### Device information

* Android device: Huawei P20 Lite, Android 9.1
* Fenix version: Nightly 190919 18:00 (build #12621820)

Images:
![01-webpage](https://user-images.githubusercontent.com/1206048/65535236-51180200-df01-11e9-9cd1-71b2acb3d6b6.jpg)
![02-link-menu-on-image](https://user-images.githubusercontent.com/1206048/65535237-51180200-df01-11e9-949a-fb6ae53a6062.jpg)
![03-new-tab-no-zoom](https://user-images.githubusercontent.com/1206048/65535238-51180200-df01-11e9-8f18-3696d7a7daf6.jpg)
![04-new-tab-max-zoom](https://user-images.githubusercontent.com/1206048/65535239-51180200-df01-11e9-8e35-f0b661a1036b.jpg)
![05-tab-info](https://user-images.githubusercontent.com/1206048/65535240-51b09880-df01-11e9-92d6-1f60ac779ecd.jpg)
![06-browser-info](https://user-images.githubusercontent.com/1206048/65535241-51b09880-df01-11e9-96af-2e6cf72574c7.jpg)

**Comment by sblatz** [comment]
Closing as dup of #2312.
