### ISSUE TITLE
View GeckoView licenses next to other OSS licenses

### ISSUE THREAD

**Issue by colintheshots** [mozilla-mobile/fenix#5536]
## User Story
- As a user, I want to see all open source licenses in one place. I shouldn't need to know about a hidden about:license link to find the engine licenses.

## Dependencies
- None if we provide a second link from the about screen.

### Acceptance Criteria
- I can find GeckoView licenses alongside other OSS licenses in Fenix.

**Comment by liuche** [comment]
@colintheshots could you describe where we could put this? It actually seems straightforward enough that a contributor could pick it up!

**Comment by colintheshots** [comment]
The current link is in the About page. We could add a second link if needed. I added comments to the most recent About screen redesign about including a second link.
