### ISSUE TITLE
Enhanced offline handling when there is no network connection 

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/fenix#5540]
## User Story
- As a user, I want to know when my tab content is no longer available because I don't have a network connection, so I know why I am unable to browse content.

Some sites offer their own version but most sites do not
- I know that my web content is unavailable because I am offline
- I know that I can reload the page when I am back online

### Acceptance Criteria
- [x] Follow the current template that exists.
- [x] The "offline error" page should have the following changed strings:

(Should follow Category: low risk template)
Headline: No internet connection
Copy: Check your network connection or try reloading the page in a few moments.

Button: Reload

Instead of the current screen (which says "Address Not Found" and has a bunch of text)

### NOT part of this issue
- Update templates is #5892

**Comment by vesta0** [comment]
Further clarified during UX/product meeting that this issue is just about showing a different error page with there is no network connection.

**Comment by jpfaller** [comment]
Headline: No internet connection
Copy: Check your network connection or try reloading the page in a few moments.

Button: Reload

**Comment by lime124** [comment]
please use the same background image as for tab crashes.  see #5892 for the template/design

**Comment by lime124** [comment]
please ping @brampitoyo for a UI review - he worked on the previous alert pages and check provide feedback as jeff will be out on pto.

**Comment by brampitoyo** [comment]
For the “No internet connection” scenario, let’s refer to this document (also referred to in #5892):
https://docs.google.com/spreadsheets/d/1SIAm3XZz5uGOm39rAR1hcCje7XYOfqqfSkxnXWttBeU/edit#gid=1453201767 – specifically on cell J11.

Let me consult @jpfaller and get back on this issue.

**Comment by sblatz** [comment]
This will require us to add to `ErrorPages.kt` in AC. This is work we can do though :)

**Comment by jpfaller** [comment]
@brampitoyo and I spoke, and we are aligned on using this string:

Headline: No internet connection
Copy: Check your network connection or try reloading the page in a few moments.

Button: Reload

**Comment by Baron-Severin** [comment]
PR up at https://github.com/mozilla-mobile/android-components/pull/5068

**Comment by Baron-Severin** [comment]
This PR requires changes, but I'm allocated to FFTV this week.  Unassigning and moving to backlog.  If someone picks up this change, please see https://github.com/mozilla-mobile/android-components/pull/5068

**Comment by sv-sdeiac** [comment]
Hello, I can confirm that this issue is fixed on the latest version of Firefox Preview Nightly 12/2 (build #13361807).

Devices:
- Nokia 6 (Android 7.1.1);
- Motorola Moto G6 (Android 8.0);
- Samsung Galaxy S8 (Android 9);
- Google Pixel 2 (Android 9).
