### ISSUE TITLE
AC API for integrating GV Login Autofill Delegate with Logins Storage

### ISSUE THREAD

**Issue by ekager** [mozilla-mobile/fenix#5543]
### Why/User Benefit/User Problem
When a user goes to a site with a login, it can be cumbersome to login on mobile. GV has provided the interface for the GV APIs to start working against.

### What/Requirements
In AC (will be done by Fenix team):
- [ ] Need a delegate on GeckoSession that will fill from the Logins Sync Storage (or secure storage from #5550?) (GV doesn't want to touch storage formats). GeckoView has provided the following [GV API for autofill](https://docs.google.com/document/d/1VrYeAASErlT7FwagxPmMzDnRewCUVnp-CVND8zOO5hw/) that we should use.
- [ ] Behind a Fenix Nightly flag

### Acceptance Criteria (how do I know when I’m done?)
- AC wrapper around GV Login APIs, while GV is working on finishing implementation

### Dependencies
- [x] TextInputDelegate public (so we don't have to override the whole class) https://bugzilla.mozilla.org/show_bug.cgi?id=1577018
- [x] Remove 26+ check & make GeckoSession autofill API available to API levels 21-25 https://bugzilla.mozilla.org/show_bug.cgi?id=1577019
- [x] Make a custom SessionTextInput ViewStructure to support 21+ (instead of Android ViewStructure 23+) https://bugzilla.mozilla.org/show_bug.cgi?id=1577003

No AS work bc we can already store/access logins.

### **Not** part of this ticket:
- Choosing which login to autofill for a site if multiple matches, but needs to support in the future
- Accessing secure storage #5550 
- Integrating finished GV APIs for logins, which is #6696 

### Risks
** Needs lots of QA to try out different sites, look at user-reported issues

* ~~The APIs requested of GV might not cover all the login field detection and autofill, and we won't know until we try it out~~
** ~~GV uses the same detection as Desktop, so in theory should be good enough. But we won't know until we try it out.~~
** ~~Desktop heuristics might not work well on Mobile pages - mitigation to ask Desktop/MattN to update heuristics~~
* ~~GV might have to also support #550 login experience for existing Lockwise users, which might have bad behavior of GV interaction between Fenix and LW login autofilling~~
** ~~Need to talk to UX and get some UX guidance~~
** ~~Technical limitations: GV will only allow one or the other. If we need to support both, we need to get back to GV to make changes~~
* ~~Creating a component from scratch to android-components quality~~

**Comment by liuche** [comment]
According to GV this is unblocked bc https://bugzilla.mozilla.org/show_bug.cgi?id=1577003 has landed on Nightly. We still will not be able to save, but we can start autofilling from existing logins.

**Comment by liuche** [comment]
After a discussion w/ GV, they're going to use more Gecko Toolkit code to do more of the autofill work. That means this is no longer ready to be worked on (but the remaining work should be much less).

**Comment by cpeterso** [comment]
The GV bug has been added to GV's November sprint.

https://bugzilla.mozilla.org/show_bug.cgi?id=1577005#c13

**Comment by vesta0** [comment]
We will be able to size this by Fridayl

**Comment by liuche** [comment]
I'll work w/ Emily to break this into the GV and AC parts.

**Comment by liuche** [comment]
@Baron-Severin and @ekager landed this in AC on 1/10 with https://github.com/mozilla-mobile/android-components/pull/5316/files

I'm going to close this, because this can't be QA-verified until #6696 is done to use the AC APIs.
