### ISSUE TITLE
Bare minimum View saved logins

### ISSUE THREAD

**Issue by liuche** [mozilla-mobile/fenix#5544]
### Why/User Benefit/User Problem
I want to be able to view my saved login and password, so I can use them in places where auto-fill does not work.

### Dependencies
- [ ] Sync Logins #5074 

### Acceptance Criteria
- [ ] I can view my logins (default alphabetical order)
- [ ] I can choose to show/hide my password
- [ ] This is behind a Nightly flag because it will still be in development
- [ ] Login Sync engine is off by default *for a new account created on Fenix* (since this is the bare minimum) (e.g., create the FxA account on fenix using the email option, but not an account created elsewhere and then paired)

This does **not** include:
- Biometric support #5547 
- Secure storage #5550 #5938 
- #5774 Search, sort by recent, search, delete, **copy** #5891 
### UX Spec
See #1284 for mocks

**Comment by liuche** [comment]
@vesta0 will think about this a little more, and where it fits into our overall logins strategy - for now, removing from MUSTs.

**Comment by liuche** [comment]
We want to get the logins work started early, so this will be scoped to the smallest this can be.

**Comment by liuche** [comment]
What strings do we need @ekager @boek, and can you pass that on to @jpfaller?

**Comment by boek** [comment]
@liuche Sorry, I know this is confusing. This is the label that @bifleming is using on her report for Delphine and the l10n team. We should probably separate `needs:strings` and `has:strings`.

**Comment by lime124** [comment]
oh yes needs:strings is to flag content strategy for help.

**Comment by ekager** [comment]
Sycning logins (the only way to get logins populated for now) turned out to depend on https://github.com/mozilla-mobile/android-components/issues/4741 which @grigoryk is working on.

We should be able to get a fix in for the next AC release

**Comment by liuche** [comment]
@ekager just to refresh my memory, we discussed landing this as soon as it's done and not blocking on mozilla-mobile/android-components#4741, with it preffed off so it can go through the review process, etc and be landed right?

**Comment by ekager** [comment]
Without mozilla-mobile/android-components#4741 there will be no logins to see. But I can pref everything off and put up the changes for review.

**Comment by liuche** [comment]
Yep, that reflects what I remember us talking about! Let's get it landed.

**Comment by liuche** [comment]
All the pieces are ready and landed, just waiting on #5074

**Comment by AndiAJ** [comment]
Hi, I've just checked this on the latest **Nightly Build Nightly Build #13240608 from 20/11** using a Google Pixel 3a XL (Android 9).

✔️ This is behind a Nightly flag because it will still be in development - "Passwords" animation when opening "Settings"
❓ Login Sync engine is off by default (since this is the bare minimum) - I've used a newly created account, the **Login Sync engine is OFF for a couple of seconds** right after signing in. 
Afterwards the sync starts automatically and the **Login Sync engine is ON**.
![20191120_142132](https://user-images.githubusercontent.com/51314259/69243974-cd9b2a00-0bac-11ea-82cb-fe25dd99465f.gif)


✔️ I can view my logins (default alphabetical order) - Due to #5542 we currently can't save passwords using Fenix.
Because of this I've **synced my logged passwords** from desktop and **Fenix sorted them in alphabetical order**
✔️ I can choose to show/hide my password - Using the show/mask password icon the password is displayed/masked and the icon is updated accordingly.

@ekager & @liuche - Please review and let me know if the Login Sync engine should remain  OFF and if I missed any other aspect while testing.  :relaxed:

**Comment by liuche** [comment]
> ❓ Login Sync engine is off by default (since this is the bare minimum) - I've used a newly created account, the **Login Sync engine is OFF for a couple of seconds** right after signing in.
> Afterwards the sync starts automatically and the **Login Sync engine is ON**.
> ![20191120_142132](https://user-images.githubusercontent.com/51314259/69243974-cd9b2a00-0bac-11ea-82cb-fe25dd99465f.gif)
> 

Hi @AndiAJ ! Thanks for testing, I just updated the acceptance criteria that this should be off for new FxA users. For existing users signing into Sync, the sync state will match whatever Login Sync preference they have chosen for their account. The implementation of Sync does not allow for per-device settings.

**Comment by AndiAJ** [comment]
Hi @liuche I've logged #6737 regarding the Login Sync engine issue.
I'll remove the **QA needed label** until it'll get fixed and afterwards re-test.

**Comment by liuche** [comment]
@AndiAJ just to be clear, "Newly created account" should be "account created through Fenix", not pairing an account newly created on Desktop. Let me update the AC to be more clear, sorry for the confusion.

Could you retest with that condition?

**Comment by AndiAJ** [comment]
@liuche indeed, the account was created and accessed **exclusively through Fenix**

I've re-tested on today's **Nightly Build #13261307** and as you can see, after creating the account, I've entered the verification code and afterwards the **first sync** kicked in automatically. (**Last synced:never**)
During the sync the "Logins" check box isn't checked, on the other hand after the first sync is completed it gets checked and the Sync logins is set to ON.

► Video from 
![20191122_161251](https://user-images.githubusercontent.com/51314259/69433067-8f843e80-0d43-11ea-8e3b-b713c6fa5b71.gif)

**Comment by liuche** [comment]
Is there a bug filed for this @ekager and can you link it?

**Comment by ekager** [comment]
Yes looks like #6737

**Comment by Baron-Severin** [comment]
> Is there a bug filed for this bug found by QA @ekager and can you link it?

Looks like it's tracked in https://github.com/mozilla-mobile/fenix/issues/6737

**Comment by liuche** [comment]
Closing this because there is a follow-up filed here and everything else is working. That way we can get it off our board!
