### ISSUE TITLE
In settings, I can choose whether I want my browser to remember my logins

### ISSUE THREAD

**Issue by ekager** [mozilla-mobile/fenix#5545]
### Why/User Benefit/User Problem
As a user I want to choose whether Fenix saves my logins for all sites.

### What/Requirements
- Depends on #5542 
- Settings page to give users the choice to save or not save logins on all sites.

### Acceptance Criteria (how do I know when I’m done?)
- A user can choose to save or not save logins globally within Fenix. See #1284 for mocks.

**Comment by sv-sdeiac** [comment]
Verified as fixed using the latest version of Firefox Preview Nightly 1/16 build #20160806.

Devices: 
- Nokia 6 (Android 7.1.1);
- Motorola Moto G6 (Android 8.0);
- Samsung Galaxy Note 8 (Android 9);
- Google Pixel (Android Q).
