### ISSUE TITLE
Add setting inside login management to sync logins

### ISSUE THREAD

**Issue by liuche** [mozilla-mobile/fenix#5546]
### Why/User Benefit/User Problem
When in my login management settings, I can choose to sync my logins directly without having to go into Sync settings.

### What/Requirements
- Depends on #5074 Login Sync and #5450 choose what to sync work
- Setting that links to Sync Settings "Choose what to Sync"

### Acceptance Criteria (how do I know when I’m done?)
Setting in Login Management settings that links to sync settings page, where user can choose to turn on login syncing.

**Comment by vesta0** [comment]
@liuche is this the same as #5074

**Comment by liuche** [comment]
Not exactly - this one is inside the login management, so this could be done after (or at the same time as) #5074, but requires the login management screen.

**Comment by ekager** [comment]
Will QA once the FeatureFlag shows this in Nightly/Debug by Monday Nov 4

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **Nightly Build #13220606 from 11/18** using the following devices:
• Google Pixel 3a XL (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

► Video 
![20191118_171217](https://user-images.githubusercontent.com/51314259/69064998-aa933d80-0a27-11ea-8eca-916530d3468c.gif)
