### ISSUE TITLE
Select from multiple logins for a website for autocompletion

### ISSUE THREAD

**Issue by liuche** [mozilla-mobile/fenix#5551]
### Why/User Benefit/User Problem
I might have more than one login for a site, and I would like to select the correct one.

### What/Requirements
* GV APIs for showing multiple logins for a text field
* TBD

### Acceptance Criteria (how do I know when I’m done?)
I can select a login from several I have for a website and it will autofill correctly.

**Comment by liuche** [comment]
Could be done in webcontent with an extension, but this is really difficult.

Alternatively, we could create some other native Android UI.

**Comment by mnoorenberghe** [comment]
[GV bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1618058)

Nit: Could someone replace "autofilling" with "filling" or "autocompletion" in the issue title?

**Comment by ekager** [comment]
Tracking AC work in https://github.com/mozilla-mobile/android-components/issues/7134

**Comment by Hubfront** [comment]
This functionality should be a must have for fenix too like it is already the case with desktop firefox. Its very annoying, and even more annoing with new fenix to navigate for login credentials to fenix credentials. It was annoying with fennec already, but with new fenix UI far more clicks are needed for simple task of getting login credentials because fenix isnt detecting and displaying them or if one has multiple accounts (e.g. email accounts) and fenix hasnt the functionality to offer a dropdown menue for them.

**Comment by Serega124** [comment]
Firefox Android 79 reached to release, but if multiple logins are saved for any site, autocomplete for this site does not work. This is frustrating 🙁

**Comment by liuche** [comment]
Login autofill will appear broken if:
- have 2+ logins for a site
- sync logins with desktop and autofill the same domain (m.github.com vs github.com)

**Comment by liuche** [comment]
We want to share UX ideas earlier so we can address the feasibility (from chatting w/ @mheubusch )

Is this a viable MVP @vesta0: "autofill the first login" even if it's the wrong one? (assuming we can correct the login username, and the password will just fill correctly)

**Comment by vesta0** [comment]
@liuche if anything, the second or last login is probably the more accurate/recent one so I don't think that would be a viable MVP.

**Comment by AmyYLee** [comment]
cc @violasong

**Comment by ekager** [comment]
This has landed in Nightly

**Comment by Hubfront** [comment]
Thank you, nice work.

**Comment by LaurentiuApahideanSV** [comment]
Verified as fixed on Firefox Preview Nightly 200827 (Build #2015760379).

### Devices used:
- OnePlus 6T (Android 9)
- Huawei MediaPad M3 (Android 7.0)
