### ISSUE TITLE
[Bug] Fenix crashes on es locales

### ISSUE THREAD

**Issue by boek** [mozilla-mobile/fenix#5552]
https://github.com/mozilla-mobile/fenix/pull/5482/commits/2886b0d31e44066f5c2ddaa94c201b03513512d6#diff-30eefb34d3cd95f1e83b7ca91d80dcb0R213

is causing: https://sentry.prod.mozaws.net/operations/fenix-nightly/issues/6326356/

@Pike @Delphine What is the process to get this fixed in the l10n repo? :)

**Comment by Pike** [comment]
That's part of https://github.com/mozilla-l10n/android-l10n/pull/86, which is coming back here in #5562. Sorry for the trouble.

The general way to fix this is for you to request Delphine to go in and fix or unapprove (remove) the string on Pontoon, and then also get it here by the way of the import step.

**Comment by ekager** [comment]
@boek did we ever get this resolved on the Pontoon side or did we just reintroduce the same crash with latest string exports 😆

**Comment by boek** [comment]
I think we fixed it on both. We’ll want to take out the temporary fix though!

-j

**Comment by sv-ohorvath** [comment]
This was verified on Nightly 1/20.
devices: Nexus 5 (android 6.0.1), Galaxy Note 8 (android 9)
