### ISSUE TITLE
[Bug] "Open in App" button on every website

### ISSUE THREAD

**Issue by agi90** [mozilla-mobile/fenix#5555]
## Steps to reproduce
- Have multiple browsers (not sure if that's the cause but)
- Visit any website, e.g. Google Search, theguardian.com, etc

### Expected behavior
- Open in App is only visible when there's an app associated to the website

### Actual behavior
- Open in App is always visible, clicking on it re-opens the website in a new tab

### Device information

* Android device: Samsung S10
* Fenix version: Firefox Nightly (latest from playstore)

![Screenshot_20190924-191633_Firefox Nightly](https://user-images.githubusercontent.com/4297388/65564105-bddecc80-df00-11e9-8391-bcc3c187aa1f.jpg)

**Comment by ekager** [comment]
We have removed the QAB and I'm not seeing the same behavior in the browser menu on master. Closing!
