### ISSUE TITLE
[Bug] Nightly build from Play Store has quotation marks in its name

### ISSUE THREAD

**Issue by softvision-miralobontiu** [mozilla-mobile/fenix#5558]
## Steps to reproduce
1. Install Firefox Preview Nightly build from Play Store.
2. Go to Settings - About Firefox Nightly and observe the name of the build.

### Expected behavior
The name should be without quotation marks.

### Actual behavior
The name of the build is between quotation marks.

### Device information
* Android device: all
* Fenix version: Nightly 190924 from Play Store

![picturemessage_4tp3wkh5 gqb](https://user-images.githubusercontent.com/40694158/65587187-1dcf8480-df8e-11e9-9ad3-a5c142375880.png)

**Comment by softvision-miralobontiu** [comment]
The quotation marks are displayed also in the presentation of the app in Play Store:

![Screenshot_20190926-102811_Google Play Store](https://user-images.githubusercontent.com/40694158/65677543-7c623480-e05a-11e9-83db-7eb8a67d0e89.jpg)

**Comment by pocmo** [comment]
CC @mitchhentges

**Comment by mitchhentges** [comment]
Oh, I didn't see this in app badging last time I looked, but downloading the most recent one shows it. This definitely _is_ on the automation side.

**Comment by mitchhentges** [comment]
@JohanLorenzo I'm going to rope you in here. I think this is due to a broader issue with shell-quoting.
For example, the build task command generated for a release build is:

```
"command": [
  "/usr/local/bin/run-task",
  "--mobile-checkout=/builds/worker/checkouts/src",
  "--task-cwd",
  "/builds/worker/checkouts/src",
  "--fetch-hgfingerprint",
  "--",
  "bash",
  "-cx",
  "echo '\"--\"' '>' .adjust_token && echo '\"\"' '>' .digital_asset_links_token && echo '\"-:-\"' '>' .leanplum_token && echo '\"https://fake@sentry.prod.mozaws.net/368\"' '>' .sentry_token && ./gradlew clean assembleGeckoBetaFenixProduction"
],
```
Note how the `>` symbols seem to be quoted as well

**Comment by JohanLorenzo** [comment]
Thank you for filing this bug, @softvision-miralobontiu ! It's a fallout of [bug 1580778](https://bugzilla.mozilla.org/show_bug.cgi?id=1580778). You're right, @mitchhentges, shell quoting is broken in this case. I found the root cause and tested the patch in #5635
