### ISSUE TITLE
[Bug] Share function on slide-up menu provides old url after switching tab via notification

### ISSUE THREAD

**Issue by hwinnemoe** [mozilla-mobile/fenix#5568]
## Steps to reproduce
1. Open a website, e.g. https://www.mozilla.org/en-GB/.
2. Long-press on a link, e.g. https://www.mozilla.org/en-GB/firefox/accounts/, and choose "Open link in new tab".
3. Switch to the new tab using "SWITCH" on the "New tab opened" notification.
4. Share the link using the share function in the slide-up menu. 

### Expected behavior
The current tab's url is shared, in this case https://www.mozilla.org/en-GB/firefox/accounts/.

### Actual behavior
The previous tab's url is shared, in this case https://www.mozilla.org/en-GB/. This might be the same or related to issue #5032.

### Device information

* Android device: Sony Xperia Z2, Android 6.0.1
* Fenix version:
"Nightly 190924 12:53" (Build #12671258)
📦: 14.0.0, 186fa2396
GV: 71.0a1-20190923094800

**Comment by ekager** [comment]
Possibly related: #5187 
The `DefaultQuickActionSheetController` uses a passed in `Session` that must not be updating correctly.

**Comment by AndiAJ** [comment]
Hi, **verified as fixed on Nightly Build #12700627 from 27/9** using the following devices:
• Google Pixel 3a (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

► Video
![20190927_115741](https://user-images.githubusercontent.com/51314259/65756742-5bfbae00-e11e-11e9-8761-5c1c80730756.gif)
