### ISSUE TITLE
Selected tab should appear with selected theme

### ISSUE THREAD

**Issue by colintheshots** [mozilla-mobile/fenix#557]
## Steps to reproduce
1. Open multiple tabs.
2. Switch between tabs.

### Expected behavior
The currently selected tab should have a border to indicate it's selected.

### Actual behavior
All tabs appear in the selected state.

### Device information

* Android device: Samsung Galaxy S8, Oreo
* Fenix version: Master, built on 2/15

**Comment by bsurd** [comment]
Only the currently selected tab is now displayed with the selected theme, all other being displayed normally.

Verified on:
 - 1.0.1910 (Build #10642115)

 Devices:
 - Nokia 6 (Android 7.1.1)
 - HTC Desire 820 (Android 6.0.1)
