### ISSUE TITLE
[Bug] two ways of creating a private shortcut both create a different icon

### ISSUE THREAD

**Issue by cadeyrn** [mozilla-mobile/fenix#5572]
### Steps to reproduce

1a) open Firefox Preview
1b) press "Add private browsing shortcut"

2a) go to Android home screen and long press on the Firefox Preview shortcut (regular or private, doesn't matter)
2b) long press on "Open new private tab" and drag it to an empty space on the home screen

### Actual behavior

shortcut from 1) purple icon with "Firefox Preview (pr…)" as text
shortcut from 2) white icon with "Open new private tab" as text

![Screenshot_20190925-203308](https://user-images.githubusercontent.com/1100614/65629903-a07b3280-dfd4-11e9-8868-24d19c4a1094.png)

### Expected behavior

Similar looking shortcuts in both cases because both shortcuts do the same.

I don't know if both shortcuts can / should have the same text because of the different way both are created but at least the colors should be the same.

### Device information

* Android device: HTC U11 / Android 9.0
* Fenix version: master branch revision b0b60aa27d9ccf4443aa85eef66522cce71a353f

**Comment by brampitoyo** [comment]
@cadeyrn 

I guess these shortcuts do practically the same thing:

If created from “Add private browsing shortcut”
Shortcut will open Private Mode.

If created from long-press
Shortcut will first open Private Mode, then it will press the “+” button to add a new private tab.

However, the new Private Tab start page is identical to the Private Mode start page!

Because the page opened is identical, the two shortcuts practically do the same thing.

If they do the same thing, then **we should make the shortcut text and icon identical**.

**Comment by mcarare** [comment]
@brampitoyo  As per https://github.com/mozilla-mobile/fenix/issues/5231, the shortcut from "Add private browsing shortcut" will not do the same thing, cause it will only open Fenix in private mode, not open a new tab. As they are now, the distinct text and icon colour will be important to differentiate between this.

**Comment by brampitoyo** [comment]
@mcarare Ok. Our situation here isn’t ideal, but as soon as we fix #5231, we will automatically fix this issue, as well.

So, let’s close this issue in favour of fixing #5231. Sounds good?

**Comment by mcarare** [comment]
Sounds good to me!

**Comment by cadeyrn** [comment]
#5231 and this one are totally different issues and not related at all. 🤔

- #5231 is about the opening behaviour of the normal and private mode shortcut.
- This one is about the shortcut design of the two different private mode shortcuts and has nothing to do with the normal shortcut.
- Fixing #5231 will not fix this one.

**Comment by mcarare** [comment]
@cadeyrn After #5231 the icons will do different things, IMO it's expected also to look differently.

**Comment by klint** [comment]
With #5231 latest design confirmation, the 2 different private mode shortcuts will have the same effect actually, which is opening a new tab in private mode, won't they?
