### ISSUE TITLE
harmonize spacing between radio buttons

### ISSUE THREAD

**Issue by cadeyrn** [mozilla-mobile/fenix#5573]
STR:

1. open different setting pages and look at the radio buttons.

Expected:

consistent spacing between radio buttons

Actual:

no consistent spacing - the following screenshot shows three settings pages. The "Theme" page has way too much spacing between the options.

![screenshot](https://user-images.githubusercontent.com/1100614/65631077-11234e80-dfd7-11e9-98b9-02a2a7c45157.png)

**Comment by NotWoods** [comment]
I'm gonna try and channel the UX team and say we should align with the padding in the first two images.

**Comment by vipulasri** [comment]
Hey,
I would like to work on this.

**Comment by vipulasri** [comment]
@NotWoods In order to be sure, I should follow [Material Design List Specs](https://material.io/components/lists/#specs) for the all 3 screens right?

**Comment by cadeyrn** [comment]
> for the all 3 screens

I suggest to go through all settings pages and check if the spacings are okay. There are more settings pages with radio buttons. The three screens in the original report were only examples.

**Comment by brampitoyo** [comment]
I agree with @NotWoods:
> …we should align with the padding in the first two images, following [Android design specs for lists](https://material.io/components/lists/#specs).

I also agree with @cadeyrn:
> …go through all settings pages and check if the spacings are okay. There are more settings pages with radio buttons. The three screens in the original report were only examples…

@vipulasri:

* Yes, please follow the Material Design List Specs
* And when implemented, please go through all Settings pages to make sure that the spacing looks ok
* If there are pages that don’t align or look odd, post it here so we can help you diagnose the issue

**Comment by vipulasri** [comment]
@brampitoyo @NotWoods 

- I fixed the theme settings radio button
- Enhanced tracking protection settings also have radio-buttons, I have attached before and after post-change. Please tell me which one to keep for these settings.

**Before:**

![Screenshot_20191002-183334](https://user-images.githubusercontent.com/7822179/66046836-36b6d780-e544-11e9-8dd2-4f6338a27e0b.png)

**After:**

![Screenshot_20191002-183229](https://user-images.githubusercontent.com/7822179/66046896-53eba600-e544-11e9-99af-6bed1972d73b.png)

**Comment by brampitoyo** [comment]
@vipulasri For Enhanced Tracking Protection, let’s use the “before” state.

Thanks!

**Comment by vipulasri** [comment]
@brampitoyo 
Please review PR: https://github.com/mozilla-mobile/fenix/pull/5765
