### ISSUE TITLE
questionable animation on tracking protection settings page

### ISSUE THREAD

**Issue by cadeyrn** [mozilla-mobile/fenix#5575]
STR:

1. open the tracking protection settings

Actual:

There is a "sliding animation" for the two options (standard / strict).

Expected:

Is this animation really needed? No other settings page has such an animation and Fenix _feels_ slower because of this animation because it _looks_ like a performance problem. I am not against animations in user interfaces at all but this specific animation feels out of place. I propose to remove the animation.

**Comment by ekager** [comment]
It's not an "animation" it's just dynamically showing/hiding those settings based on a feature flag for Nightly. Once we remove the feature flag, there won't be any "animation", so I'm going to close this :)
