### ISSUE TITLE
[Bug] Send Tab (push) is broken on latest nightly

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/fenix#5576]
Send tab works when polling, but push support seems to no longer work. 

### Device information

* Android device: Android 10 (Pixel 2)
* Fenix version: 

Real Nightly app:

> "Nightly 190924 12:53" (Build #12671259)
> 📦: 14.0.0, 186fa2396
> 🦎: 71.0a1-20190923094800
> 

Release app:

> "Nightly 190924 12:53" (Build #12671259)
> 📦: 14.0.0, 186fa2396
> 🦎: 71.0a1-20190923094800

**Comment by sblatz** [comment]
@jonalmeida Are you still seeing this on the latest nightly?

**Comment by jonalmeida** [comment]
Yes.

**Comment by sblatz** [comment]
@grigoryk are you aware of any changes on the AS side that may have caused this?

**Comment by liuche** [comment]
This is probably a change in AS, so we should work w/ @jonalmeida and @grigoryk on this.

**Comment by jonalmeida** [comment]
I didn't want to wait for triage, so we fixed this with the help of @jrconlin. :)
