### ISSUE TITLE
[Bug] Can't open target=_blank links in a PWA

### ISSUE THREAD

**Issue by apbitner** [mozilla-mobile/fenix#5580]
## Steps to reproduce

- Go to twitter.com and install as a PWA
- Launch Twitter PWA
- Tap on a link in the footer, e.g. About, Help Center, etc

### Expected behavior
- Link should open
### Actual behavior
- Link does not open
### Device information

* Android device: Android 10, Pixel 3
* Fenix version: 1.0.1939 (Build #1)

**Comment by NotWoods** [comment]
Those links have `target="_blank"` to open in a new window, which currently doesn't work in PWAs and custom tabs. See mozilla-mobile/android-components#1562

**Comment by NotWoods** [comment]
Duplicate of #5085
