### ISSUE TITLE
[Bug] Fix bugs related to being able to download a file

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/fenix#5581]
## User Story
As a user, I want to be able to download web content and web files, including files on authenticated sites, so I can have access to the content I need. 

### Acceptance Criteria
- Downloads behind authenticated sites should work
- Fix all download related P2 bugs
- [x] mozilla-mobile/android-components#1159
- [ ] #3666
- [x] ~~#2579~~ duped to blob file type bug ^

**Comment by liuche** [comment]
Can we rename this to "Fix remaining download bugs", and have "walkthrough and list bugs" as an acceptance criteria?

**Comment by liuche** [comment]
I believe this is waiting on #5582, and then we can do a walkthrough and file any remaining bugs.

**Comment by vesta0** [comment]
@liuche this shouldn't be waiting on anything. This is about fixing issues with the actual download. There are a large number of downloads that are not working.
Example:
#5601 
#3703
#3666
#2579

**Comment by NotWoods** [comment]
A lot of the download issues are waiting on GeckoView (`blob:` URLs, `.xpi` files)

**Comment by sblatz** [comment]
QA: can we verify these bugs are still being encountered?

**Comment by sv-ohorvath** [comment]
I can verify #3666 and #2579 and both are still reproducing. Don't have the know-how to test mozilla-mobile/android-components#1159.

**Comment by NotWoods** [comment]
I'll add steps to reproduce to the last bug, although right now it's definitely still failing as we are still waiting on GeckoView.

**Comment by sv-ohorvath** [comment]
@NotWoods Yup, mozilla-mobile/android-components#1159 still reproducing. Thanks!

**Comment by sblatz** [comment]
> A lot of the download issues are waiting on GeckoView (blob: URLs, .xpi files)

@NotWoods do you have a link to this issue in bugzilla 🤔

**Comment by vesta0** [comment]
Closing as the remaining issues are tracked in other places.
