### ISSUE TITLE
[Telemetry] Download notifications

### ISSUE THREAD

**Issue by liuche** [mozilla-mobile/fenix#5583]
#### Description & Product Manager / Data Scientist User Story
- As a product owner, I want to know if users interact with download notifications and status, so I can optimize the experience based on what users use the most.

#### What probes (suggested, if applicable)
- User pauses a download
- User resumes a download
- User cancels a download
- User taps on retry when a download fails
- User opens a downloaded file by tapping on the link in system notification
- User opens a downloaded file by tapping on the in-app notification link
- User taps on retry when a download fails on the in-app notification link

### Acceptance Criteria (Added by PM)
- Event pings can be queried via re:dash
- We are sending telemetry events for the actions listed in the requirements
- We have documented the telemetry
- We have asked a data steward to [review](https://github.com/mozilla/data-review/blob/master/request.md) the telemetry
- NOT an AC: Data science to create dashboard or further graphs (this will be a separate issue, this issue is only about hooking up the events described and that they can be queried in re-dash)

**Comment by AndiAJ** [comment]
Hi **verified as fixed** on the latest **Nightly Build #13230608 from 11/19** using a Google Pixel 3a XL (Android 9)

✔️ User pauses a download - Ping d7a54dae-ab4a-400e-b685-b01ad44714d7
✔️ User resumes a download - Ping 55f51505-5011-4c54-8f41-0733b62b9e82
✔️ User cancels a download - Ping 4f155d55-67ee-4e3a-8d0c-b69538d53996
✔️ User taps on retry when a download fails - Ping b2f8d1ec-e0c3-467e-8d87-a9edfe13b84f
✔️ User opens a downloaded file by tapping on the link in system notification - Ping f31bcb63-827e-40ac-a416-ebedd7202729
✔️ User opens a downloaded file by tapping on the in-app notification link - Ping 05410b35-05b7-489f-9238-5ee82adb0fdc
✔️ User taps on retry when a download fails on the in-app notification link - Ping 33299957-d673-4eda-89b0-a56d377bca76

[Logcat](https://github.com/mozilla-mobile/fenix/files/3864655/download.txt)
[Glean dashboard](https://debug-ping-preview.firebaseapp.com/pings/aj-t191111)
