### ISSUE TITLE
Look into if latest androidx update fixes our ViewModel issue, remove workaround

### ISSUE THREAD

**Issue by ekager** [mozilla-mobile/fenix#5589]
https://developer.android.com/jetpack/androidx/versions/all-channel#september_18_2019

See for history:
#4888 
#5055
#5036

**Comment by ekager** [comment]
@colintheshots do you feel like you could look into this? I'm not sure I have enough context of the original crashes and workaround?

**Comment by colintheshots** [comment]
The crashes were reasonable common edge case race conditions we found in Sentry. I feel like running RoboTest is the best STR we have.

**Comment by ekager** [comment]
Removed in https://github.com/mozilla-mobile/fenix/pull/16290
