### ISSUE TITLE
Home screen search box styling (shadow, border) looks out of place

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/fenix#559]
## Steps to reproduce

Open Fenix

### Expected behavior

Subtle styling for search box, like how it appears in private mode. No shadow, color inside to offset it from the background of the page. 

### Actual behavior

The styling of the search box looks weird and out of place with the shadow and border around it.

### Device information

* Android device: ?
* Fenix version: ?

**Comment by shorlander** [comment]
Hi! Thanks for the feedback. It is intentionally more obvious in that state. But will keep this in mind :)
