### ISSUE TITLE
"What's New" and "Help" menu item performing a search in Nightly builds

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/fenix#5595]
The "What's New" menu item is performing a search in Nightly builds. Probably because the version name is pretty long and contains spaces.

**Comment by neekless** [comment]
I think it may be due to the build name having quotations now. Previously it worked even if the names were long.

**Comment by neekless** [comment]
Related: https://github.com/mozilla-mobile/fenix/issues/5558

**Comment by softvision-miralobontiu** [comment]
"Help" is performing the same search.

**Comment by Mozinet-fr** [comment]
"Help" in settings has the same behavior.

**Comment by pocmo** [comment]
CC @mitchhentges: I assume that the quotation marks should not actually end up in the version name? That looks like we mess up passing in a parameter somewhere. :)

**Comment by mitchhentges** [comment]
The quotes in the version name will be fixed in https://github.com/mozilla-mobile/fenix/pull/5635

**Comment by NotWoods** [comment]
Seems to be fixed now, I can't reproduce.

**Comment by pocmo** [comment]
Yep!

**Comment by abodea** [comment]
Verified as fixed on the latest Nightly build from **11/29** with **Google Pixel 3a XL(Android 10).**
