### ISSUE TITLE
Fennec migration: Integrate "open tabs" migration code from AC.

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/fenix#5596]
First iteration implemented in:
https://github.com/mozilla-mobile/android-components/issues/4241

Integration may depend on:
https://github.com/mozilla-mobile/android-components/issues/4464

**Comment by ebalazs-sv** [comment]
Verified as fixed on Google Pixel (Android Q), Samsung Galaxy S8 (Android 9), Nexus 6P (Android 8.1.0), Sony Xperia Z5 Premium (Android 7.1.1).
