### ISSUE TITLE
Jarring transition when tapping in search on home

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/fenix#560]
[recording_20190216_100152.zip](https://github.com/mozilla-mobile/fenix/files/2872628/recording_20190216_100152.zip)
## Steps to reproduce

1. Open Fenix
2. Tap inside search box

### Expected behavior

There should be a smooth (but fast) animation transitioning from the search box to the top of the screen where users can input a query. The search box should *move* to its new position on the screen instead of a new search box appearing. 

### Actual behavior

Upon tap, a new screen appears, replacing the previous content. 

Edge does a pretty good job of how I picture this looking given the current design of the home screen. See attached. 

### Device information

* Android device: ?
* Fenix version: ?

**Comment by bbinto** [comment]
Will be addressed here: https://github.com/mozilla-mobile/fenix/issues/167

**Comment by AmyYLee** [comment]
This has been addressed in https://github.com/mozilla-mobile/fenix/issues/167

**Comment by vesta0** [comment]
Closing as per Amy's comment.
