### ISSUE TITLE
[Bug]Firefox Preview Nightly version from Play Store isn't up to date

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#5600]
## Steps to reproduce
1.  Installed Firefox Preview v2.0.0-rc.3 from Github
2. Installed Firefox Preview Nightly from Play Store
3. Check Firefox Preview Nightly version.

### Expected behavior
Firefox Preview Nightly version is up to date (latest version installed)

### Actual behavior
Pixel 3a (Android 9) - Firefox Preview Nightly Build #11821259 from 1/7 got installed
Huawei Mate 20 Lite (Android 8.1.0) - Firefox Preview Nightly Build #12671259 from 24/9  got installed

### Device information

* Android device: 
• Google Pixel 3a (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)

* Fenix version:

**Comment by ReekyMarko** [comment]
My Aurora Store said the update failed to install. I opted to uninstall and then install again, now I get 

`"Nightly 190925 18:01" (Build #12681805)`

This might be an Aurora Store specific thing though

**Comment by AndiAJ** [comment]
The above mentioned issue occurred only once on both deices.

**Comment by boek** [comment]
Feel free to re-open if this is still an issue
