### ISSUE TITLE
[Bug] ETP panel above the toolbar and logo highlight

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#5606]
## Steps to reproduce
1. Open a page that has ETP enabled.
2. Open the ETP panel.
### Expected behavior
According to the [mockups](https://mozilla.invisionapp.com/share/8ZQVRNUJW3H#/screens/375991493), the ETP logo is highlighted, with a purple background, when the panel is opened.
Also, the toolbar is visible in this state.
### Actual behavior
Toolbar and ETP icon are not visible.
### Device information

* Android device: Pixel 3 (Android 9)
* Fenix version: Nightly 9/25

**Comment by Amejia481** [comment]
cc: @ekager

**Comment by ekager** [comment]
I talked this over with @AmyYLee while we were implementing and we decided having a custom dialog behavior here showing the dialog above the toolbar with a new custom toolbar state was not worth the large engineering effort. I'm going to close this ticket for now, but we should update the mocks to reflect the true state.
