### ISSUE TITLE
[Bug] Fenix Nightly doesn't use channel colours for graphics

### ISSUE THREAD

**Issue by pwd-github** [mozilla-mobile/fenix#5608]
### Expected behavior
Fenix Nightly has a blue/purple launcher icon, but uses orange within the app, whereas it should use blue/purple

My guess is that the icon is hardcoded and should actually be using a variable.

**Comment by liuche** [comment]
Nightly is mainly for the channel, we might change the colors in-app but can revist if UX decides to.

**Comment by pwd-github** [comment]
@liuche how do I get UX to look at this issue?
