### ISSUE TITLE
Move home screen 3 dot menu to bottom

### ISSUE THREAD

**Issue by Cheap-Skate** [mozilla-mobile/fenix#561]
on normal web content, 3 dot menu button is at bottom of screen as part of URL bar.  But on Home screen 3 dot menu button is at top of screen alongside private browsing icon.  I find it confusing, I have to look in 2 different places depending on browser context.   Could 3 dot menu button (and private browsing button?) be at bottom of Home screen to match normal page content?

-------

UX update:

Ok, let's move the 3-dot menu to the bottom as well as the new tab (+) icon and the search. 
Would it be possible to launch that as A/B test against the current version?

![home-3dot](https://user-images.githubusercontent.com/353960/65309789-16bf0580-db8d-11e9-9fc0-d20edfa67432.png)

- animation stays as is 
- menu moves to bottom bar from top right corner
- plus moves to bottom bar from open tabs section

Additional acceptance criteria: 
- Include fixing all UI tests broken by this change.

**Comment by topotropic** [comment]
@vesta0 here's a design for moving the 3-dot menu and private mode to the bottom and also restructuring the home and site menus so that they align and people can rely on motor memory – access to history and bookmarks is also added as shortcut to the home screen menu (bottom row). I discussed this with @shorlander and we feel moderately confident about it and would love to monitor how it performs in the beta 
https://mozilla.invisionapp.com/share/QSRWREJMV9D#/372970523_Latest

**Comment by yoasif** [comment]
@topotropic I like it -- had a question/feedback though -- why can't we also have the addressbar in the usual place instead of the whitespace between the mask and the new tab buttons?

If the addresbar was there, the user could simply open a new tab by typing instead of tapping the search or enter address input towards the top of the screen.

There is prior art for this in desktop -- open a private browsing window on desktop, and the address bar is present along with the search box in the viewport.

**Comment by vesta0** [comment]
@topotropic love the new design. Do we also want to move the Fenix logo higher (too much white space at top and make it smaller to make more room for tab visibility?

**Comment by Cheap-Skate** [comment]
Love the new design, makes more sense. Thanks

I like yoasif's idea, there's now a nice space in the bottom row for the search box. Advantages
(1) the search box and the + new tab icon do exactly the same thing, the search box is arguably redundant, but is a useful hint about how best to do a search
(2) the search box moves around the screen based on scroll offset, which I find irritating, I can't use muscle memory.
(3) when the search box is at the top of the screen it's hard to reach one handed, I have to scroll it down which is an extra step.

(I can file a separate issue on this if you like)

**Comment by lime124** [comment]
collecting homescreen related things into a single place for ux to take a look at. removing ux label.

**Comment by liuche** [comment]
Launching a UR test week of 8/19, should have more insights by 8/21.

**Comment by topotropic** [comment]
@lime124 @vesta0 @liuche this is ready to be pulled into the next sprint if you want to, I updated the initial comment with the specs

**Comment by liuche** [comment]
This is a lot of changes on the eng side, with a lot of areas for behavioral edge cases.
We'll also need to update UI tests.

Should we have a spike to investigate the risks/issues/sizing.

**Comment by topotropic** [comment]
@boek I added the private mode view to the initial issue https://github.com/mozilla-mobile/fenix/issues/561#issue-411172797

**Comment by nahuhh** [comment]
Tapping the + symbol and tapping the address bar behave identically (new tab)  

I suggest:
- keep the tabs screen address bar behavior (new tab)
- remove the "+" and
- add the "tabs" button
- Tapping the "tabs" button from the "tabs" screen should take you back to the currently selected tab 
- if no tabs are open, it should only show the address bar

Example
1.Browse the web
2. Tap "tabs" button (takes you to tabs screen)
3. On tabs screen:
3a. tap "tabs" button (takes you back to your open tab) 
or
3b. type into the address bar (opens new tab. Current behavior)

**Comment by topotropic** [comment]
Thanks for the feedback @nahuhh; I agree, that it seems redundant – the advantage of having the plus there is that you can quickly go from browsing the web to a new tab by tapping twice in the same area (first tab on "Tabs" button, then on plus). 
This is also part of a bigger effort to re-work new tab, home, open tabs and will most likely change in the near future. Thanks again for your feedback!

**Comment by abodea** [comment]
Verified as fixed in the latest Nightly build from **`9/25`** using Samsung Galaxy S10+(Android 9).
Please note that the navigation bar works as expected.
Based on my comment I will close this issue.
