### ISSUE TITLE
Releases don't have a versionName

### ISSUE THREAD

**Issue by mitchhentges** [mozilla-mobile/fenix#5615]
Spotted in automation testing, release builds don't have `-PversionName` provided to them - here's what my `gradle` command looks like when testing locally:
```
./gradlew clean assembleGeckoBetaFenixProduction
```

@JohanLorenzo are you able to take a look at this?

**Comment by JohanLorenzo** [comment]
Good eye! I embedded the fix in #5635. It was a silly omission of mine.
