### ISSUE TITLE
Revisit Privacy Settings items

### ISSUE THREAD

**Issue by liuche** [mozilla-mobile/fenix#5619]
### Why/User Benefit/User Problem
There are now a lot of settings in the Privacy settings section, and maybe they aren't in the optimal order.

![Screenshot_1569525672](https://user-images.githubusercontent.com/1082253/65718406-52a80e00-e058-11e9-94b3-fddbe6a0952e.png)

### What/Requirements
UX revisit the settings menu order and items, icons, etc.

### Acceptance Criteria (how do I know when I’m done?)
- [ ] UX has looked at the Privacy settings menu and made suggestions
- [ ] These issues are listed here, prioritized, and fixed, or filed as follow-ups

**Comment by sblatz** [comment]
Most recent screen:
<img width="350" alt="image" src="https://user-images.githubusercontent.com/4400286/67320643-58600a80-f4c3-11e9-810d-fcbd3c8530d4.png">

**Comment by vesta0** [comment]
No A-C dependencies for this ticket. Will re-confirm once we have UX design.

**Comment by apbitner** [comment]
UX is planning on taking a look at the entire Settings screen, not just privacy - https://github.com/mozilla-mobile/fenix/issues/5905

**Comment by vesta0** [comment]
This will be covered under #5905
