### ISSUE TITLE
[Bug] unlabeled buttons in Enhanced Tracking Protections settings

### ISSUE THREAD

**Issue by asadotzler** [mozilla-mobile/fenix#5621]
## Steps to reproduce
Open Fenix Nightly with Talkback on
Navigate to Settings
Navigate to ETP settings
Navigate to the "i" information buttons for Standard and Strict

### Expected behavior
Buttons have a label like "Details for Standard Tracking Protection" or similar

### Actual behavior
Unlabeled buttons

### Device information

* Android device: Samsung Galaxy S10e
* Fenix version: Nightly 120926 18:01

**Comment by ekager** [comment]
Can we get confirmation for content description strings for the info buttons in ETP settings? CC @jpfaller

**Comment by jpfaller** [comment]
What's blocked by <insert Standard or Strict> tracking protection

**Comment by ekager** [comment]
So we should add 2 strings here: 
"What's blocked by strict tracking protection"
and "What's blocked by standard tracking protection"

And use these as the content descriptions of the info buttons.

**Comment by nianjack** [comment]
Hi, first time contributing in Hactoberfest. Mind if I have a go at this issue?

**Comment by chiragmantri** [comment]
hi @asadotzler and @ekager, can I pick this up?

**Comment by NotWoods** [comment]
Sorry @chiragmantri, @nianjack got to this one first. [Here are some other issues we need help with](https://github.com/mozilla-mobile/fenix/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3A%22good+first+issue%22).

**Comment by nianjack** [comment]
@NotWoods, @chiragmantri does anyone want to pick up this issue instead?

**Comment by matthewcmckenna** [comment]
I can take this on!

**Comment by liuche** [comment]
unassigning for inactivity

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on **Debug Build from Master 1.0.1947 (Build # 1) 📦: 23.0.0, 9b8e27603 🦎: 72.0a1-20191119043902 from 22/11** using the following devices:
• Google Pixel 3a XL (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)
