### ISSUE TITLE
Allow granularity in Mozilla (Glean) telemetry collection

### ISSUE THREAD

**Issue by liuche** [mozilla-mobile/fenix#5626]
### Why/User Benefit/User Problem
As a privacy-conscious user, I want to have finer control over the types of data that Mozilla is collecting. For instance, I might not want my sync patterns to be collected.

This is also a differentiator, and allows users to meaningfully control their data. This also isn't something that other apps provide. Telemetry is really all-or-nothing, which tends to give a "yes it's good to help this company" vs "no data collection is evil" dichotomy.

### What/Requirements
- [ ] Granularity in telemetry settings (and maybe an explanation why it's helpful)

### Acceptance Criteria (how do I know when I’m done?)
User can choose what types telemetry they want to send to Mozilla.
User can understand why different telemetry is being collected.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-13635)

**Comment by mdboom** [comment]
This may have implications that make analysis much more complicated.  For example, when correlating measurements that may or may not have been collected, will we have a way of telling whether something isn't there because it didn't happen or because the user opted out?  I am not a data science, but I'd strongly encourage getting some in the loop on this.

**Comment by Dexterp37** [comment]
The Glean SDK team is tracking this [in this bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1598247). This is more of an SDK design problem :)

**Comment by liuche** [comment]
Also see #4667 #4674 for granularity in non-Mozilla telemetry controls.

**Comment by kbrosnan** [comment]
Looks like glean went with a different solution. With the issues mentioned in the previous comment fixed I don't believe we will be doing further work here.
