### ISSUE TITLE
[Telemetry] Add opt-out ping

### ISSUE THREAD

**Issue by liuche** [mozilla-mobile/fenix#5627]
Owner: Product Manager

#### Description & Product Manager / Data Scientist User Story
- As a product owner, I want to know if people are opting out of telemetry. That way, we can also understand if people are dropping off of usage, or choosing to not send telemetry anymore.

#### Hypothesis
- We believe this feature is useful to users, and successful when Product has a better understanding of how much users care about telemetry collection.

#### What questions will you answer with this data?
If a lot of users opt-out of telemetry, we get a signal that Firefox Preview users care about telemetry collection.
We can also understand if people are dropping off (vs just turning off telemetry and possibly continuing to use Fenix)

#### What probes (suggested, if applicable)
- Opt-out ping

### Dependencies (Added by PM and Eng)
Need Glean to implement [opt-out ping](https://bugzilla.mozilla.org/show_bug.cgi?id=1546947) (this is currently in their backlog)

### Acceptance Criteria (Added by PM)
- Event pings can be queried via re:dash
- We are sending telemetry events for the actions listed in the requirements
- We have documented the telemetry
- We have asked a data steward to [review](https://github.com/mozilla/data-review/blob/master/request.md) the telemetry
- NOT an AC: Data science to create dashboard or further graphs (this will be a separate issue, this issue is only about hooking up the events described and that they can be queried in re-dash)

**Comment by Dexterp37** [comment]
Note that this was added in [the Glean SDK 21.3.0](https://github.com/mozilla/glean/blob/master/CHANGELOG.md#v2130-2019-12-03) and will automatically be available to Fenix once it updates to the latest Android Components version.

**Comment by vesta0** [comment]
Not sure how this will be implemented but it's better if we just receive an event ping when user opts out than get pinged regularly. Let’s not measure more than we need to.

**Comment by Dexterp37** [comment]
As mentioned in the comment from December 4th, this is already implemented and available in Fenix. It's the [`deletion-request`](https://mozilla.github.io/glean/book/user/pings/deletion_request.html) ping.

**Comment by ValentinTimisica** [comment]
Talked to @Dexterp37 and confirmed that the [deletion-request](https://mozilla.github.io/glean/book/user/pings/deletion_request.html) ping is automatically sent when the user disables Glean ([here](https://github.com/mozilla-mobile/fenix/blob/b85673acac601b7bc1c2976bf466af5980ba23ac/app/src/main/java/org/mozilla/fenix/settings/DataChoicesFragment.kt#L31)) and there is nothing left to do in Fenix. @liuche should we close the ticket?

**Comment by liuche** [comment]
Great! That's good to know, we can close this ticket then if there's nothing else to do.
