### ISSUE TITLE
[Bug][Performance] Scrolling performance on Twitter's notification page

### ISSUE THREAD

**Issue by bogas04-swiggy** [mozilla-mobile/fenix#5629]
## Steps to reproduce
1. Open Twitter's PWA and login
2. Visit notification page
3. Scroll by pulling to refresh
4. Observe performance

### Expected behavior
Should be smooth

### Actual behavior
Isn't

![Comparison with Chrome](https://thumbs.gfycat.com/ThosePracticalJuliabutterfly-size_restricted.gif)
### Device information

* Android device: RealmeX, Android Pie
* Fenix version: Nightly 190925 18:01" (Build #12681805) 📦: 14.0.1, 81385d712 🦎: 71.0a1-20190923094800

**Comment by boek** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1586438

Closing as a dup of #5789
