### ISSUE TITLE
Update UX for history management

### ISSUE THREAD

**Issue by TitanNano** [mozilla-mobile/fenix#563]
## Steps to reproduce
Go into Fenix history management

### Expected behavior
On android list actions are usually in the page header. When a list item is selected the header switches into edit mode, providing special editing actions.

### Actual behavior
The current history management is very unandroidy. There is a delete-history-button right below the header which changes into "delete x Items" when a history entry is selected. I attached a screenshot of how Google Messages does it. The X on the right side of the header is also very strange.

### Device information

* Android device: 7.1.1
* Fenix version: 1.0

![screenshot_20190217-151747](https://user-images.githubusercontent.com/4500858/52914322-417b6f80-32c7-11e9-9dfb-59b662457d31.png)
![screenshot_20190217-145929](https://user-images.githubusercontent.com/4500858/52914484-214cb000-32c9-11e9-9bec-579a9411e4dd.png)

**Comment by yoasif** [comment]
FWIW, Bromite/Kiwi have a more "Android" UI around history management that replicates Fenix's features in a nicer way. 

![screenshot feb 17 2019 1_30_43 pm](https://user-images.githubusercontent.com/152493/52917354-66b4b180-32b8-11e9-9d9b-4812a8116648.png)

A couple of things: 

* No three dot menu in Bromite; as the only option is delete, they use an icon for it
* They also have the "X" in the header to exit this view

![screenshot feb 17 2019 1_35_29 pm](https://user-images.githubusercontent.com/152493/52917403-fa867d80-32b8-11e9-8d4d-54b063b78dbc.png)

The selection of multiple items is just as undiscoverable as on Fenix, (hold on favicon) but that seems to be an Android-ism. 

As the reporter noted, once selected, the header changes to show options to perform with the selected items; interestingly, the options inside the three dot menu include opening the history entries in new tabs (either normal or private). The header text also updates to show the number of selected items.

**Comment by bbinto** [comment]
Some of these issue have been discussed with UX, will review once the Library UI is done

**Comment by topotropic** [comment]
@boek could you update history so that selections matches the spec here https://mozilla.invisionapp.com/share/8KRF5PW9Q6Z ?

**Comment by topotropic** [comment]
@vesta0 @bifleming Is this still blocked?

**Comment by vesta0** [comment]
@topotropic no I think it's ready for engineering.

**Comment by sblatz** [comment]
This ended up being quite a bit more work than a quick restyle (as you can see in [my PR](https://github.com/mozilla-mobile/fenix/pull/2378). I'm going to resize this as a 5 as that's a more accurate estimate of the time it took me, @bifleming.

**Comment by bsurd** [comment]
The checkmark when selecting history elements does not match the one from the design specs in invision. Bookmark items are displayed as the design specs.
![screen](https://user-images.githubusercontent.com/17178945/57622339-0c18b200-7596-11e9-8a38-d75266b2bcbc.jpg)


There are also inconsistencies between bookmarks and history elements. The bookmarks are displayed with a circle and history ones have a square that turns into a circle when long tapping to select multiple elements.
![screen](https://user-images.githubusercontent.com/17178945/57622158-b2b08300-7595-11e9-8e23-f5e92237c784.jpg)

@sblatz Could you take a look at this?

**Comment by cadeyrn** [comment]
See also #2435.

**Comment by sblatz** [comment]
@topotropic for the fav icons in bookmarks and history, do we want them to be the rounded square or the square inside the circle?

**Comment by topotropic** [comment]
@sblatz circles

**Comment by cadeyrn** [comment]
@topotropic Then the favicons in the "open tabs" section on the home screen should also be changed because it doesn't make much sense to have different favicon styles across the product. Now just one inconsistency has been swapped for another inconsistency.

_By the way, in my opinion it looks much cleaner without the circle and the design without the circle has also the advantage of bigger icons._

**Comment by yoasif** [comment]
FWIW, Bromite, Kiwi, Opera all use circles for bookmarks on Android. Edge does not, but it also doesn't seem to care about looking like an Android app. 

I think  #2132 is a bigger issue as compared to other Android apps, but I don't have *much* of an opinion about the circles.

**Comment by cadeyrn** [comment]
I've never heard of Kiwi and Bromite but in Fennec there are also no circles. ;-) But it's a design decision and therefore not important what others do. Fenix as a whole must look coherent. So I can live with both styles but only one style should be used for all places. ;-)

**Comment by yoasif** [comment]
Sad. I forgot to check Fennec, and I like the Fennec design the most, upon review.

**Comment by topotropic** [comment]
Thanks for your feedback! I can see where you are coming from. The idea behind using squares on start screen and circles on history/bookmarks is that the context is a different one: on start screen images are embeded in cards, on history/bookmarks we use list elements.  The placeholders on start screen are also slightly bigger and this format allows room for using other source material then favicons, for example images. Hope that helps.

**Comment by bsurd** [comment]
Verified on the latest build (5/15) on a Nexus 5 and OnePlus 5T.
