### ISSUE TITLE
[Bug] [Android5] ETP shield is not visible on nav bar

### ISSUE THREAD

**Issue by softvision-miralobontiu** [mozilla-mobile/fenix#5632]
## Steps to reproduce
1. Open a page and observe the ETP shield icon.

### Expected behavior
The ETP shield is visible.

### Actual behavior
The ETP shield is half-visible or not displayed at all on Android 5 devices.

### Device information
* Android device: Xiaomi Mi Pad 2 (Android 5.1.1) - x86 architecture, Huawei Media Pad M2 (Android 5.1), Samsung Galaxy Tab A6 (Android 5.1), and LG Nexus 4 (Android 5.1.1).
* Fenix version: Nightly 190927 (#12700629)

![Screenshot_2019-09-27-08-58-27](https://user-images.githubusercontent.com/40694158/65754953-cdd1f880-e11a-11e9-898e-2d53e4ab7a9b.png)

![e](https://user-images.githubusercontent.com/40694158/65754917-c01c7300-e11a-11e9-9b7f-d53a4123a593.png)

**Comment by ekager** [comment]
Filed https://github.com/mozilla-mobile/android-components/issues/4537 in AC

**Comment by ekager** [comment]
Should be fixed with the next Nightly with latest AC (there have been some AC release issues so may take a day or two)

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on **Nightly Build #13190606 from 11/15** using the following devices:
• Samsung Galaxy Tab Active (Android 5.1.1)
• LG Nexus 7 (Android 5.1.1)
• LG Nexus 4 (Android 5.1.1)

► Screenshot from LG Nexus 7 
![rsz_screenshot_2019-11-15-12-48-03](https://user-images.githubusercontent.com/51314259/68939081-66463a00-07a8-11ea-831c-8d00b07fee19.png)
