### ISSUE TITLE
[Bug]Android media notification & Open tabs play icon is displayed without any media being actually played on CNN.com 

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#5634]
## Steps to reproduce
1. Navigate to CNN.com
2. Tap on the tabs counter
3. Check the CNN open tab 
4. Swipe down the Android task-bar

### Expected behavior
No media playback notification should be displayed on the opened tab nor on the Android task-bar

### Actual behavior
Media playback notification is displayed on the opened tab and on the Android task-bar

### Device information

* Android device: 
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• OnePlus A3 (Android 6.0.1

• LG Nexus 4 (Android 5.1.1)

* Fenix version: Nightly Build #12700627 from 27/9

### Notes:
Not reproducible on Google Pixel 3a (Android 9)

►Video
![20190927_121439](https://user-images.githubusercontent.com/51314259/65759169-0675d000-e123-11e9-907b-f4bef272bbde.gif)

**Comment by sblatz** [comment]
@pocmo any idea what's going on here? This looks like an AC issue with the MediaPlayer.

**Comment by yoasif** [comment]
I am also seeing this issue on https://www.dallasnews.com/news/courts/2019/10/01/amber-guyger-convicted-of-murder-for-killing-botham-jean/

on my Pixel 2:

"Nightly 190930 18:01" (Build #12731805)
📦: 15.0.0, 8562fc768
🦎: 71.0a1-20190928211735

**Comment by pocmo** [comment]
I've seen something like this on a different page too. I'll nominate this for the next AC sprint.

**Comment by ekager** [comment]
Not seeing this on either of the mentioned sites above. QA- could we verify with those two sites on a few devices and close if not happening anymore?

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on my Nightly debug **`Build #21040820 39.0.20200410130104, 464e3038d
GV: 77.0a1-20200409095500 AS: 0.55.0 from Monday 4/13`** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)

►Video
![20200413-084329](https://user-images.githubusercontent.com/51314259/79096108-db706800-7d64-11ea-8814-022c599b1314.gif)
