### ISSUE TITLE
UX feedback: 3 dot menu on Home screen disappears on scroll

### ISSUE THREAD

**Issue by Cheap-Skate** [mozilla-mobile/fenix#564]
I would like to be able to access the 3 dot menu after I have scrolled the Home screen. Particularly to get at Your Library. 

At the moment the 3 dot menu disappears as I scroll the Home page up. 

[edit - I guess it disappears when I scroll the normal Web content page too, so close this issue if you like. But it's all terribly terribly confusing. On one screen it's at the top and fades out, on the other it's at the bottom and slides out]

**Comment by ekager** [comment]
Especially since we added collections and the list could get fairly large, I think we should revisit this because the user would have to scroll fairly long to get to Settings.

**Comment by sblatz** [comment]
Tagging this as low priority since we're likely doing a [redesign](https://mozilla.invisionapp.com/share/7PSR7KCSW6Z#/372749649_Latest) that would address this.
