### ISSUE TITLE
Enable punycode

### ISSUE THREAD

**Issue by Erroneuz** [mozilla-mobile/fenix#5640]
### User Problem
By default fenix shows unicode domains and not the punycode domain, which is problematic due to phishing. Right now, there is no way to turn on punycode.

Example site: https://www.xn--80ak6aa92e.com

### Acceptance Criteria
By default punycode should be turned on or at least there should be an option to turn it on.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-13647)

**Comment by Erroneuz** [comment]
Anyway to get some eyes on this? This is quite a huge oversight in Firefox Preview. In Firefox for desktop it can be adjusted with IDN_show_punycode = true

**Comment by JoGarWeb** [comment]
Please don't forget thes feature... 
Can enable in about:config but is not for all users. We need this option implemented in Settings menu for more security in some countries. 

![image](https://user-images.githubusercontent.com/7904563/89698920-73342c00-d8e9-11ea-8162-be355f4af10b.png)

![image](https://user-images.githubusercontent.com/7904563/89698922-78917680-d8e9-11ea-8c66-363a1c1097b3.png)

**Comment by s-ankur** [comment]
This seems more like a serious security vulnerability than a feature request. It should be prioritized. 

Note that on chrome it shows the punycode by default

**Comment by s-ankur** [comment]
People can easily craft malicious urls like mozillа.org (its not really mozilla.org, you can see it in chrome or desktop firefox)

**Comment by gcp** [comment]
Firefox desktop doesn't display punycode by default either. Some of the discussion that went into that decision is here; https://bugzilla.mozilla.org/show_bug.cgi?id=1332714

**Comment by gcp** [comment]
>People can easily craft malicious urls like www.mozillа.org (its not really mozilla.org, you can see it in chrome or desktop firefox)

If you visit that link in Fenix, you get the punycode URL because it triggers the heuristics (if the URL has mixed scripts, which is unlikely to happen in normal use, we do switch to punycode). Is that not what you're seeing?

**Comment by gcp** [comment]
>Note that on chrome it shows the punycode by default

I think it is more complicated than this, they don't default to punycode by default. They have a heuristic for popular websites, something similar to: https://bugzilla.mozilla.org/show_bug.cgi?id=1507582, and that triggers because apple.com is well known.

**Comment by s-ankur** [comment]
> If you visit that link in Fenix, you get the punycode URL because it triggers the heuristics

I actually dont see the punycode url. It redirects to some random site but at no point does firefox display punycode
this is not what happens on desktop

**Comment by s-ankur** [comment]
On desktop, when I paste the link it immediately enters punycode. Maybe this is a different bug then?

**Comment by gcp** [comment]
>On fenix (latest nightly) it enters "mozilla.com".

Ah, I get what you are doing now. If you paste the URL in the address bar, it will say mozilla.org. If you actually visit it, you will get the punycode URL in the address bar.

**Comment by gcp** [comment]
The pasting behavior is the same on desktop (Linux). We won't actually translate to punycode until you hit enter.

**Comment by andreicristianpetcu** [comment]
This is what chromium is doing
![image](https://user-images.githubusercontent.com/922368/96903743-e556ee80-149e-11eb-8ecf-7a5601de504e.png)

**Comment by gcp** [comment]
>This is what chromium is doing

You are actually hitting a special case, see previous comments: https://github.com/mozilla-mobile/fenix/issues/5640#issuecomment-680967535

**Comment by andreicristianpetcu** [comment]
@gcp can Fenix include that special case?

**Comment by gcp** [comment]
>@gcp can Fenix include that special case?

See the linked Gecko bug.

**Comment by s-ankur** [comment]
I think the more relevant bug would be https://bugzilla.mozilla.org/show_bug.cgi?id=1332714, but that has been wontfixed long ago (with what appears to be rather flimsy reasoning, at least to me)

**Comment by gcp** [comment]
>I think the more relevant bug would be

It depends on whether you want to discuss the general policy, or what happens if you try popular sites such as "apple.com". As explained, the latter is handled separately so using it to argue about this bug or parity with other browsers (which is what I replied to) does not work.

**Comment by gcp** [comment]
>i don't see why it shouldn't be possible to only enable punycode for hostnames that can appear to be written in different scripts

That's what Fenix already does: https://github.com/mozilla-mobile/fenix/issues/5640#issuecomment-680963521

**Comment by oakkitten** [comment]
> That's what Fenix already does: [#5640 (comment)](https://github.com/mozilla-mobile/fenix/issues/5640#issuecomment-680963521)

i don't mean mixed scripts, i mean when when the hostname can appear to be written, as in case of this fake apple website, in either latin or cyrillics. i understand that it's not as simple as treating “a” and «а» as the same letter; ideally you'd have to account for different fonts and ligatures and stuff like that, but it seems doable?

**Comment by PeopleInside** [comment]
Visiting https://www.xn--80ak6aa92e.com/ from Firefox for Android open a fake apple.com website.
Seems on Firefox stable for Android there is no way to enable punycode to be showed?

about:config is no more available so how can I secure my Firefox on Android?

**Comment by nbmrjuhneibkr** [comment]
This issue is more than 2 years old. I guess no one at Mozilla cares about privacy anymore.

**Comment by PeopleInside** [comment]
I'm really shocked and I know. This is not only privacy but is security: I feel not safe when the browser show to me an address and a certificate that looks to be apple but is not apple.

**Comment by regs01** [comment]
Enabling punnycode will make non-latin domains unreadable. It shouldn't be an optio. Either codes for everyone or for noone.

The right way is the way of Internet Explorer used to be - show an icon in addressbar if domain name uses scripts that are not assigned to locale.

Also, it's primarily ICAAN to blame to mismanagement. Second and top level domains should have been single and same script only. So as third, if they are up for public registration.

**Comment by cpeterso** [comment]
The question of whether to enable Punycode (in Firefox desktop and/or Android) is up to the Firefox Security team. They are tracking that decision in Bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1507582. We don't need to track the Android decision separately here on GitHub.
