### ISSUE TITLE
UX feedback: Your Library tap targets are in different places on Home screen vs Page View screen, plus, menu items in different order, PS it takes 3 taps vs 2 on Fennec

### ISSUE THREAD

**Issue by Cheap-Skate** [mozilla-mobile/fenix#565]
From Page View screen
- tap 3 dot menu at bottom of screen, **order is Help / Settings / Your Library**
- tap Your Library which is _around the middle of my screen_, six menu items from the bottom
- tap History

From Home screen
- tap 3 dot menu at top of screen (also see #561), **order is Settings / Your Library / Help**
- tap Your Library which is now _perhaps an inch from the top of the screen_ 
- tap History 

It would be great if the menu item order and the absolute X Y screen coordinates of Your Library could be in the same in both cases, less hunting around.

PS
takes 3 taps on Fenix vs 2 on Fennec (tap URL bar, tap History tab).  Progress? ;)

**Comment by mheubusch** [comment]
@vesta0 we will close this issue and visit as part of addressing page action menu for landscape

**Comment by mheubusch** [comment]
@vesta0 we will close this issue and visit as part of addressing page action menu for landscape
