### ISSUE TITLE
Automatically use private mode depending on the app

### ISSUE THREAD

**Issue by NotWoods** [mozilla-mobile/fenix#5650]
### Why/User Benefit/User Problem
Users may want to use private mode for links opened from certain apps (such as Twitter and Reddit) but not other apps (such as email or GitHub). We currently have an all-or-nothing approach and per-app (or alternatively, per-domain) would allow for more configuration.

### What/Requirements
- Users should be able to configure which apps or domains open private mode by default.

Possible UI: Prompt the first time a new app/domain is opened.

<img height="500" src="https://user-images.githubusercontent.com/1782266/65793167-15a45000-e11a-11e9-9152-53a99097062f.png">

Later on the apps/domains could be configured in settings, similar to how Tracking Protection and Site Permissions is configured.

I'm not sure if we can even detect which app fired an intent, so we might only be able to do this per-domain.

**Comment by brampitoyo** [comment]
@NotWoods @AmyYLee I’ve worked on a proposal for automatic private mode upgrade for Firefox desktop.

The problem we had in 2015 is still true today and applies to all white/blacklist:

1. For automatic private mode to happen, Firefox needs to keep track of domains/apps that should open in normal and private modes.
2. To keep track, Firefox needs to maintain some sort of a list and allow the user to modify it.
3. An adversary interested to learn which domains/apps the user opens privately, can simply view the list by going into Firefox Settings.

So, how can we let users select modes while simultaneously keeping link opening fast (ie. not having too many options/decisions)?

There are a few paths to take, and we can choose to implement any/all of them:

1. The system share dialogue should have **2 icons that belong to Fenix**. One for Normal Mode. One for Private Mode. The user picks which one they want, before the link is even shared to Fenix.

2. Some third-party apps open their links in a custom tab. It may be possible for Fenix to be a Custom Tab provider.
    * Whenever this is the case, we should make it so that **our custom tab is always private mode**.
    * When the user chooses to open the link in a Fenix Browser Tab (using the menu), we will give them a selection: normal or private mode.

3. Many third-party apps open their link in a normal browser tab. This can be our policy:

    * Whatever mode Fenix is currently on, it’s the mode that the link will open in

        * Link opens in normal mode. The user is concerned about privacy. **There will be an option to “convert” a normal tab into a private one**. The history, cookies, site storage, permissions, etc. of this tab will be purged during conversion.

        * Link opens in private mode. The user wants to save this link in their history. **There will also be an option to “convert” a private tab into a normal one**.

    * When user shares the second link, they’ll know what mode it will open in.

Thoughts?

**Comment by NotWoods** [comment]
We had an implementation where there was a separate private entry in the share sheet, but this system was flawed because there is no way to switch once the "Always" option is checked.

Fenix already is a custom tab provider and many links from other apps open in custom tabs. I don't think we should always force private mode because part of the benefit of custom tabs is that you're already logged in and don't need to sign back into accounts.

Personally I think option 3 is best. We can keep the existing switch then let the user "transfer" tabs from normal to private. (We may have to do something similar for container tabs anyways.)

Thank you for the whitelist explanation. Makes sense that a storing a list isn't very private.

**Comment by brampitoyo** [comment]
@NotWoods 

> We had an implementation where there was a separate private entry in the share sheet […] there is no way to switch once the "Always" option is checked.

This sounds like a tricky problem to solve. Having two icons is convenient, but there’s no easy way to change your option once it’s been set permanently. (There is, but it may be buried under Settings?)

> I don't think we should always force private mode because part of the benefit of custom tabs is that you're already logged in and don't need to sign back into accounts.

Agreed. Thanks for explaining your reasoning here.

Part of my initial reasoning for keeping custom tabs in private mode was “users mostly utilise custom tabs when opening one-off links”. These links rarely require any sort of log in, and in fact may have all sorts of things (like trackers) that can “infect” your browsing history if not managed carefully. Maybe that’s a bit too paranoid – this coming from an adversarial security mindset!

> We can keep the existing switch then let the user "transfer" tabs from normal to private.

One of the big challenges here may be the fact that the UX isn’t that complicated, but the engineering will be. Nevertheless, it’s a happy path forward :-)

**Comment by AmyYLee** [comment]
"We had an implementation where there was a separate private entry in the share sheet, but this system was flawed because there is no way to switch once the "Always" option is checked."

@brampitoyo @NotWoods I wanted to chime in on the above comment. I've been working with @sblatz on implementing PBM shortcut on homescreen. If the user has a shortcut for PBM on homescreen, in the share sheet they are able to specify opening links in Fenix - PBM and they can set it to "always" - Before we didn't have a way for the user to undo this selection but we will be implementing an option in Settings where you can uncheck this selection (see below). If the user selects "Always"  for opening links in Fenix PBM from the share share sheet then in Settings the "Set as default browser and "Open links in private tab" will be enabled.  

![Set as default browser](https://user-images.githubusercontent.com/5992746/66141087-2731a000-e5d1-11e9-89ef-6dedcb59a54c.png)

**Comment by brampitoyo** [comment]
That’s brilliant, @AmyYLee. Sorry I took you off the assignee list without checking or waiting first for your reply!

Sounds like this is a much lighter way forward than having to build a system to turn a normal session into a private session (and vice versa).

**Comment by GingerPlusPlus** [comment]
>     3\. An adversary interested to learn which domains/apps the user opens privately, can simply view the list by going into Firefox Settings.

Why are you concerned about this @brampitoyo? There's a multitude of other, more sensitive things an adversary can learn after obtaining access to a device.
