### ISSUE TITLE
[Bug] Crash when opening settings from HomeFragment

### ISSUE THREAD

**Issue by csadilek** [mozilla-mobile/fenix#5656]
Crash in latest Nightly (190927 18:00):

This happens when we're trying to parse the `WhatsNewVersion.majorVersionNumber` which causes a `NumberFormatException` (for input string ""Nightly 190927 18:00"").

See Sentry:
https://sentry.prod.mozaws.net/operations/fenix-nightly/issues/6374297/?environment=fenixNightly

**Comment by sv-ohorvath** [comment]
Started crashing after switching to private browsing. Verified as fixed now on Nightly 10/1.
