### ISSUE TITLE
[Bug] Firefox Preview v2.1.0-rc.1 install failure

### ISSUE THREAD

**Issue by wh0isit** [mozilla-mobile/fenix#5657]
## Steps to reproduce
adb install firefox_preview_2.1.0_arm64-v8a.apk

### Actual behavior
Performing Streamed Install
adb: failed to install firefox_preview_2.1.0_arm64-v8a.apk: Failure [INSTALL_PARSE_FAILED_NO_CERTIFICATES: Package /data/app/vmdl1860331153.tmp/base.apk has no certificates at entry AndroidManifest.xml]

### Device information

* Android device: Moto X4
* Fenix version: 2.1.0-rc.1

**Comment by kzwr** [comment]
I also encountered this problem.

**Comment by gaby2300** [comment]
Could you please provide the github link to be able to download and try?


Many thanks!
Gabriela
QA Mozilla Hispano Team Responsible

**Comment by wh0isit** [comment]
https://github.com/mozilla-mobile/fenix/releases/download/v2.1.0-rc.1/firefox_preview_2.1.0_arm64-v8a.apk

**Comment by sblatz** [comment]
I believe this is because the TC for `push-apk-production` is failing: https://tools.taskcluster.net/groups/Jjj8o6OjS5COgLvpFE2alQ

@mitchhentges any thoughts?

**Comment by mitchhentges** [comment]
Linking to [slack thread for future reference](https://mozilla.slack.com/archives/CG2FGG1ST/p1569862250386300)

**Comment by ildar** [comment]
Can it be fixed just this time manually?

**Comment by sblatz** [comment]
Should be fixed by https://github.com/mozilla-mobile/fenix/pull/5683. 

We will publish a RC2, let's verify we don't have issues with that. 😄

**Comment by kbrosnan** [comment]
@mitchhentges slack threads will expire. If we want to save the info it should be added here or a wiki.

**Comment by mitchhentges** [comment]
Good call - the TL;DR of the thread is:
* We needed to merge [this PR](https://github.com/mozilla-mobile/fenix/pull/5635)
* The release had to be re-created

**Comment by sv-ohorvath** [comment]
v2.1.0-rc3 built and installed successfully.

**Comment by gaby2300** [comment]
Could you please add the github link for me to try?

**Comment by sv-ohorvath** [comment]
@gaby2300 

https://github.com/mozilla-mobile/fenix/releases/tag/v2.1.0-rc.3

**Comment by gaby2300** [comment]
@sv-ohorvath Thanks!
