### ISSUE TITLE
[Bug] Login behaviour on privat tabs

### ISSUE THREAD

**Issue by n1-n0** [mozilla-mobile/fenix#5658]
## Steps to reproduce
Open Amazon on a private tab of FF Preview (or FF Preview Nightly) and log in. Now you can browse Amazon as long you stay on this tab. If you open any amazon-page link in a new private tab or a new tab and go to Amazon on your own, you are not logged in to Amazon. When refreshing the first tab, you are logged out there also.

### Expected behavior
To be logged in (keep the cookies) until the private mode or all private tabs are closed.

### Actual behavior
Logged out.

### Device information
* Android device: Pixel 2XL - Android 10 - Built QP1A.190711.020
* Fenix version:  Nightly 190927 18:00
This happens since I use FF preview two month ago.

**Comment by buttercookie42** [comment]
#609
