### ISSUE TITLE
Can't access web user manual on Samsung Galaxy smartphones [webcontent]

### ISSUE THREAD

**Issue by imchau** [mozilla-mobile/fenix#5659]
## Site with issue and any steps to reproduce
Samsung Galaxy smartphones with Android 9 include a built-in web "user manual" for the phone. It is accessible from the bottom of the Settings app and opens the following URL in the default web browser:

https://www.samsung.com/m-manual/common/

This page deduces the device's exact model and used language by some means and then redirects to the appropriate user manual page with a custom URL. This webpage's redirection works fine in Chrome and Samsung Internet. It does not work in Firefox stable, Firefox Preview stable and Fenix Nightly.

On Firefox, it displays a page with the message "The user manual is not available in your selected language", the same message one sees when accessing this URL from a non-Samsung device. If one takes the final URL from another browser where this works and visits that URL in Firefox, the manual displays and works correctly.

### Expected behavior
Firefox opens the appropriate web user manual.

### Actual behavior
Firefox fails to open the web user manual and shows "The user manual is not available in your selected language."

### Does toggling Tracking Protection fix the issue? (Press the lock icon in the toolbar while on the site to see toggle)
No.

### Can you reproduce in [Firefox for Android](https://play.google.com/store/apps/details?id=org.mozilla.firefox)?
Yes.

### Can you reproduce in Chrome (or other non-Mozilla browser)?
No.

### Device information
* Android device: Samsung Galaxy A40
* Fenix version: latest Nightly as of 28 September

**Comment by kbrosnan** [comment]
This site requires the browser to leak the device model and user locale in the user agent. This is not something Gecko wants to do. The site supports a dozen or so Samsung devices from 2014/2015. Affected users should use the system browser to view the support documentation.

```
var docUrl = document.location.href;
if(docUrl.match(/\/m-manual\//)){
 if(docUrl.match(/\/m-manual\/cmccSM-N9108V$/)){
  window.location = '/m-manual/cmcc';
 }else if(docUrl.match(/\/m-manual\/cmccSM-N9108V$/)){
  window.location = '/m-manual/cmcc';
 }else if(docUrl.match(/\/m-manual\/cmccSM-N9108V$/)){
  window.location = '/m-manual/cmcc';
 }else if(docUrl.match(/\/m-manual\/chcSM-A5000$/)){
  window.location = '/m-manual/chc';
 }else if(docUrl.match(/\/m-manual\/chcSM-G8508S$/)){
  window.location = '/m-manual/chc';
 }else if(docUrl.match(/\/m-manual\/cmccSM-T2558$/)){
  window.location = '/m-manual/cmcc';
 }else if(docUrl.match(/\/m-manual\/cmccGT-I9508$/)){
  window.location = '/m-manual/cmcc';
 }else if(docUrl.match(/\/m-manual\/cmccGT-I9508V$/)){
  window.location = '/m-manual/cmcc';
 }else if(docUrl.match(/\/m-manual\/chcSM-A7000$/)){
  window.location = '/m-manual/chc';
 }else if(docUrl.match(/\/m-manual\/chcSM-N9150$/)){
  window.location = '/m-manual/chc';
 }else if(docUrl.match(/\/m-manual\/cmccSM-G9008W$/)){
  window.location = '/m-manual/cmcc';
 }else if(docUrl.match(/\/m-manual\/cmccSM-N9008$/)){
  window.location = '/m-manual/cmcc';
 }else if(docUrl.match(/\/m-manual\/cmccSM-N9008V$/)){
  window.location = '/m-manual/cmcc';
 }else if(docUrl.match(/\/m-manual\/chcSM-N9008S$/)){
  window.location = '/m-manual/chc';
 }else if(docUrl.match(/\/m-manual\/chcSM-G7508Q$/)){
  window.location = '/m-manual/chc';
 }else if(docUrl.match(/\/m-manual\/chcSM-E7000$/)){
  window.location = '/m-manual/chc';
 }else if(docUrl.match(/\/m-manual\/cmccSM-G9008V$/)){
  window.location = '/m-manual/cmcc';
 }else if(docUrl.match(/\/m-manual\/chcSM-N9100$/)){
  window.location = '/m-manual/chc';
 }else if(docUrl.match(/\/m-manual\/cmccSM-C1158$/)){
  window.location = '/m-manual/cmcc';
 }
```
