### ISSUE TITLE
When tapping "Search" box on Home screen, Search page should instantiate blank or with "Search the Web or enter..."

### ISSUE THREAD

**Issue by Cheap-Skate** [mozilla-mobile/fenix#566]
On Home screen
Tap middle box "Search the Web or enter address"
Search box appears top of screen
Search box contains ?? URL of last page viewed ?? which I find confusing, I haven't typed anything yet

Expected behavior
Search box should be blank or have a hint in gray eg "Search the Web or enter address"

**Comment by yoasif** [comment]
> Search box contains ?? URL of last page viewed ?? which I find confusing, I haven't typed anything yet

This has been bothering me for a bit; couldn't figure out why, thank you for capturing it. 

You may also want to see  #560

**Comment by thanuj10** [comment]
I agree with that. It should start serving related queries instead of the last visited URL.

**Comment by sv-ohorvath** [comment]
Verified as fixed.
