### ISSUE TITLE
Fenix should not allow screenshots to be taken in private mode

### ISSUE THREAD

**Issue by shahsurajk** [mozilla-mobile/fenix#5660]
### Why/User Benefit/User Problem
People use private mode for a variety of reasons, most of them is to exclude it being shown in their history by any means. 
If the screen/ activity is not excluded from taking screenshots the android framework will generate something called as a "backstack image" which is a png image of the screen as it was last seen by the user. This is then visible in the back stack and can have bad implications. 

I first discovered this in chrome, later read [this](https://tech.michaelaltfield.net/2018/11/09/android-security-auditing-investigating-unauthorized-screenshots/) article by an independent researcher. 

### What/Requirements
Block the private mode activity from taking screenshots at the manifest level. 

### Acceptance Criteria (how do I know when I’m done?)
Screenshots are not allowed in private mode and the system notification for security policy is shown.

**Comment by shahsurajk** [comment]
I can work on this if this gets approved.

**Comment by shahsurajk** [comment]
we can even have a settings option to enable/disable screenshots in private more.

**Comment by vesta0** [comment]
Thanks for filing this! We are planning to address this in #2768

**Comment by shahsurajk** [comment]
Oh. Sorry for the duplicate issue.
