### ISSUE TITLE
Add Inbuilt Secure Password Generator 

### ISSUE THREAD

**Issue by ghost** [mozilla-mobile/fenix#5661]
### Why/User Benefit/User Problem
When Users Make Registering in a site they need password and may they save a weak one so the password generator help them a lot.
### What/Requirements
secure algorithms to make sure passwords are safe for example:

Format based on Chromium:
i. 15 characters long
ii. At least one of each of:
  "abcdefghijkmnpqrstuvwxyz"; // no 'l' or 'o'                                                                                                                                      
  "ABCDEFGHJKLMNPQRSTUVWXYZ"; // no 'I' or 'O'                                                                                                                                      
  "23456789"; // no '1' or '0'
iii. Then fill the remaining 11 characters with a random selection of the 4 categories above.
iv. Randomly shuffle the order of the characters we’ve chosen

### Acceptance Criteria (how do I know when I’m done?)
you must open a site for example wikipedia or bugzilla then fill user name and when you click on password textbox an option must visible on top of the keyboard like Suggest strong password and must create a unique password.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-13666)

**Comment by zaina1986** [comment]
I am interested in this

**Comment by kbrosnan** [comment]
We don't have any designs for this feature. It is not a good first issue.

**Comment by sheikh-azharuddin** [comment]
Any progress on this feature?

**Comment by minutesinch** [comment]
> Any progress on this feature?

idk maybe they working on it

**Comment by ranjan-purbey** [comment]
Very essential feature which will help prevent users from using weak passwords

**Comment by Nitin529** [comment]
I hope the password generation feature is added to Firefox mobile and/or Lockwise soon.

**Comment by ameaninglessname** [comment]
> 
> 
> I hope the password generation feature is added to Firefox mobile and/or Lockwise soon.

Could Mozilla make these two apps combined or work together efficiently?

**Comment by Nitin529** [comment]
> 
> 
> > I hope the password generation feature is added to Firefox mobile and/or Lockwise soon.
> 
> Could Mozilla make these two apps combined or work together efficiently?

It's possible and even likely that they might get rid of Lockwise and add all it's functionality to the mobile browser.

**Comment by minutesinch** [comment]
Is there any work?

**Comment by derjudge** [comment]
Some site recquires at least one special character in the password ```@ []^_!"#$%&\'()*+,-./:;{}<>=|~?``` .
I think the passwords generated by the firefox password generator must fullfill this recquirement.

**Comment by plwt** [comment]
User feedback: https://support.mozilla.org/en-US/questions/1384319

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813156

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
