### ISSUE TITLE
Add to home screen shortcut should use favicon

### ISSUE THREAD

**Issue by blazingkin** [mozilla-mobile/fenix#5665]
### Why/User Benefit/User Problem

Home screen shortcuts are currently generic and are not unique per application. This makes it harder to identify and application at a glance

### What/Requirements

Set the shortcut icon as the websites favicon

### Acceptance Criteria (how do I know when I’m done?)
When a shortcut is added and it has a unique icon

**Comment by NotWoods** [comment]
They're already supposed to use favicons, so this is a bug :)

**Comment by blazingkin** [comment]
Ah, interesting. The page was everythingabouthere.com
Works just fine in the main version of Firefox

**Comment by NotWoods** [comment]
everythingabouthere.com uses a small favicon, which we currently discard as it becomes blurry when displayed in the launcher. mozilla-mobile/android-components#3814 tracks adding support for small icons.

The website can fix this by adding a larger icon.
