### ISSUE TITLE
[Bug] Crash on imgur.com

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#5668]
## Steps to reproduce
Load imgur.com
### Expected behavior
Page loads.
### Actual behavior
Tab crashed: 
[logcat.txt](https://github.com/mozilla-mobile/fenix/files/3669645/logcat.txt)

### Device information

* Android device: Galaxy Tab 3 (Android 8.0), Xiaomi Mi 8 Lite (Android 9)
* Fenix version: Nightly 9/28

**Comment by ekager** [comment]
Did you do anything on imgur.com or it just insta-crashes? Not seeing this on latest Nightly on pixel 3

**Comment by sv-ohorvath** [comment]
I didn't do anything else at the time, just opened the app and went to imgur. Can't reproduce it anymore though on the same build or latest...

**Comment by ekager** [comment]
Not sure how to continue here so I'm going to close this and hope it was just a weird build 🤷‍♀ Please reopen if we see this again!
