### ISSUE TITLE
[Bug] "null" version number on RC 2.1.0

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#5669]
## Steps to reproduce
Install the latest Production build from Taskcluster.
Verify the version number on the about page.
### Expected behavior
RC 2.1.0
### Actual behavior
null
### Device information

* Android device: any
* Fenix version: RC 2.1.0 (from 9/27)

**Comment by sblatz** [comment]
This should be fixed by https://github.com/mozilla-mobile/fenix/pull/5683

**Comment by sv-ohorvath** [comment]
Verified as fixed on v2.1.0-rc3, on all build types.
