### ISSUE TITLE
[Bug] Slow transition while switching back from private browsing

### ISSUE THREAD

**Issue by ebalazs-sv** [mozilla-mobile/fenix#5670]
## Steps to reproduce
1. Navigate to any website
2. Tap the 3dot button
3. Tap Private tab
4. Tap minimize keyboard to return to normal browsing
### Expected behavior
Flawless switch to normal browsing
### Actual behavior
Slow and incorrect transition
### Device information

* Android device: Huawei Honor 8 (Android 7.0)
* Fenix version: Firefox Preview RC 2.1.0-rc1
### Notes
* [Video](https://drive.google.com/file/d/11T5YI0IP71vl08PC3fveAq36pwFTq2ix/view?usp=sharing)

**Comment by sblatz** [comment]
I cannot reproduce this on my Galaxy S9. Is this Huawei specific? @ebalazs-sv

**Comment by ekager** [comment]
I also can't repro on Pixel. Could we get a few devices tested for SDK level and manufacturer? Thanks!

**Comment by LaurentiuApahideanSV** [comment]
I have retested the issue on Firefox Preview 2.1.0-rc.4 (Build #12752003) 10/2 and managed to reproduce the issue on the following devices Huawei MediaPad M3 (Android 7), Huawei Honor 8 (Android 7.0) and Galaxy S10+(Android 9).
