### ISSUE TITLE
[Bug] Main menu's yellow signal for sign-in errors is misplaced 

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#5671]
## Steps to reproduce
Connect on 2 devices.
1. Change the password on one connected device.
2. Check the page main menu on the 2nd connected device.
### Expected behavior
The 3 dot menu has a yellow background.
### Actual behavior
The yellow background is displayed in the bottom corner, not centered.
![Screenshot_20190930-153759_Firefox Preview](https://user-images.githubusercontent.com/4037709/65880680-d5073980-e39a-11e9-848c-1f0a61039c8f.jpg)

### Device information

* Android device: Galaxy Tab 3, Pixel 3 
* Fenix version: RC 2.1.0 (9/27)

**Comment by sblatz** [comment]
@Amejia481 Is this change related to your modifications to the browser toolbar in AC?

**Comment by Amejia481** [comment]
> @Amejia481 Is this change related to your modifications to the browser toolbar in AC?
> Looks like an issue with MenuButton

I'm not quite sure, we are working on reorganizing the toolbar. We can verify this issues too.
https://github.com/mozilla-mobile/android-components/issues/1514

**Comment by jonalmeida** [comment]
> > @Amejia481 Is this change related to your modifications to the browser toolbar in AC?
> > Looks like an issue with MenuButton
> 
> I'm not quite sure, we are working on reorganizing the toolbar. We can verify this issues too.
> [mozilla-mobile/android-components#1514](https://github.com/mozilla-mobile/android-components/issues/1514)

This is related to the left padding work that went in. When we enabled layout bounds during testing, we were seeing the off-center ripple then.

**Comment by pocmo** [comment]
Fixing this as part of mozilla-mobile/android-components#1514

**Comment by sblatz** [comment]
We will get this for free when AC fixes :)

**Comment by ekager** [comment]
Looks like this fix has been merged in AC. We can verify now
