### ISSUE TITLE
[Bug] "learn more about sending tabs" returns a Page not found

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#5672]
## Steps to reproduce
1. Create a new account.
2. Open a page, tap share, tap Connect another device.
3. Tap " learn more about sending tabs..."
![Screenshot_20190930-163442_Firefox Preview](https://user-images.githubusercontent.com/4037709/65884080-dd627300-e3a0-11e9-9340-cc99a5b9984b.jpg)

### Expected behavior
A support page is opened.
### Actual behavior
Page not found.
### Device information

* Android device: Galaxy Tab 3 (Android 8).
* Fenix version: RC 2.1.0 (9/28)

**Comment by jonichan** [comment]
We've just created a link you can use in the codebase: https://support.mozilla.org/1/firefox/%VERSION%/%OS%/%LOCALE%/send-tab-preview

It will automatically redirect to the SUMO article: https://support.mozilla.org/en-US/kb/send-tab-firefox-preview-another-device

**Comment by sv-ohorvath** [comment]
Verified this is fixed on Nightly 10/1. Will check on the RC build as well.

**Comment by sv-ohorvath** [comment]
@sblatz This didn't make it into 2.1.0-rc3

**Comment by sv-ohorvath** [comment]
Verified as fixed on v2.1.0-rc4.
