### ISSUE TITLE
[Bug][L10N] The "Search" button is not localized in several languages

### ISSUE THREAD

**Issue by LaurentiuApahideanSV** [mozilla-mobile/fenix#5675]
## Steps to reproduce
1. Change the language of the device to French, Italian, Korean and Japanese;
2. Press the 3 dots button in order to bring up the Main Menu;
3. Go to the Settings section.
### Expected behavior
The "Search" button should be translated in the selected language
### Actual behavior
The "Search" button is not translated
### Device information

* Android device: Huawei MediaPad M3 Lite 10 (Android 7.0)
* Fenix version: 2.1.0 rc-1 Build #12701925 9/27

**Comment by ekager** [comment]
This is a new string that was only added 12 days ago in https://github.com/mozilla-mobile/fenix/pull/5393 
We will get more translations imported as soon as they are ready and those will be uplifted into the release branch
