### ISSUE TITLE
[Bug] [Crash] Selected session may be rendered in ExternalAppBrowserActivity

### ISSUE THREAD

**Issue by csadilek** [mozilla-mobile/fenix#5678]
We've fixed different bugs causing this crash in the past, but it is still happening (although at a lower rate than before). Definitely needs investigation and STRs:

https://sentry.prod.mozaws.net/operations/fenix-nightly/issues/6170288/?environment=fenixNightly

https://sentry.prod.mozaws.net/operations/fenix-nightly/issues/6191212/?environment=fenixNightly

It seems to happen for both regular and custom tabs (looking at the breadcrumbs). The root cause is always that we're trying to set the same session on multiple views. See:

https://github.com/mozilla-mobile/fenix/issues/360
https://github.com/mozilla-mobile/fenix/issues/575
https://github.com/mozilla-mobile/fenix/issues/897
https://github.com/mozilla-mobile/fenix/issues/4438
https://github.com/mozilla-mobile/fenix/issues/4486

**Comment by csadilek** [comment]
Assigning to me for investigation. @kbrosnan, it would be great if we could get help from QA to find STRs, which helped us tracked down other cases of this last time:

https://github.com/mozilla-mobile/fenix/issues/4438
https://github.com/mozilla-mobile/fenix/issues/4486

**Comment by sv-ohorvath** [comment]
@csadilek I've tried anything I could think of: sharing from external apps, from custom tabs, using private launcher, using pwa's, sending tabs, but can't get a crash :) If I encounter something I'll make sure to get a log.

**Comment by csadilek** [comment]
Thank you @sv-ohorvath for investigating. Same here. I've tried it all as well. Only thing I found is a different crash: https://github.com/mozilla-mobile/fenix/issues/6029

Since this is a top crash let's keep it open and investigate more. Will post an update once I have news.

**Comment by csadilek** [comment]
Interestingly one of the two variants of this crash appear to be fixed since last weeks GV upgrade: https://sentry.prod.mozaws.net/operations/fenix-nightly/issues/6191212/

For the other we'll add additional information to the exception as part of:
https://github.com/mozilla-mobile/android-components/issues/4829

**Comment by csadilek** [comment]
The additional exception details helped us understand the problem. We're running into cases where the `customTabSessionId` [1]  (which we get from the intent [2]) is `null` i.e. because the process was killed.

Consequently, we're trying to open the selected session (instead of the custom tab session) in a custom tab and two things can happen:
- If the selected session is already rendered, opening the custom tab will crash: https://sentry.prod.mozaws.net/operations/fenix-nightly/issues/6170288/?environment=fenixNightly

- If the selected session isn't rendered, opening a custom tab will work, but it will show the selected session (and a whole browser view incl. the tab counter). Switching back to Fenix will then lead to this crash: https://sentry.prod.mozaws.net/operations/fenix-nightly/issues/6191212/?environment=fenixNightly

[1] https://github.com/mozilla-mobile/fenix/blob/master/app/src/main/java/org/mozilla/fenix/customtabs/ExternalAppBrowserActivity.kt#L49
[2] https://github.com/mozilla-mobile/fenix/blob/master/app/src/main/java/org/mozilla/fenix/customtabs/ExternalAppBrowserActivity.kt#L37

**Comment by sv-ohorvath** [comment]
@csadilek Do you have some reliable STR for this crash, for QA?

**Comment by csadilek** [comment]
@sv-ohorvath Unfortunately, we never found reliable STRs, so we had to simulate the crashes by setting the intent to null. However, after we landed the fixes, the crashes went away (you can see in the two Sentry links above). Both crashes stopped happening.

**Comment by sv-ohorvath** [comment]
Ok, thank you then :)

**Comment by abodea** [comment]
Removing the `needs:STR` as there is no need for STR and both crashes were fixed.
