### ISSUE TITLE
Crash on custom tabs menu if no other tabs are open

### ISSUE THREAD

**Issue by colintheshots** [mozilla-mobile/fenix#568]
## Steps to reproduce
1. Swipe away Fenix if opened.
2. Open a custom tab from Slack.
3. Press 3 dots overflow menu.

### Expected behavior
Menu opens.

### Actual behavior
App crashes because selectedSession is null in selectedSessionOrThrow.

### Device information

* Android device: Samsung Galaxy S8
* Fenix version: Master, built Feb 15th

**Comment by bsurd** [comment]
Verified by opening custom tabs from different applications following the steps provided, Fenix did not crash.

Verified on:
 - 1.0.1910 (Build #10642115)

 Devices:
 - Nokia 6 (Android 7.1.1)
 - HTC Desire 820 (Android 6.0.1)
