### ISSUE TITLE
[Bug] If I tap the end of an autocompleted URL, it extends the autocompletion instead of placing cursor

### ISSUE THREAD

**Issue by dholbert** [mozilla-mobile/fenix#5680]
## Steps to reproduce
1. Have some history to be able to autocomplete (e.g. github.com URLs in my example)
2. Start typing "github" into URLbar, and notice it autocomplete to `github.com/`
3. Tap the end of that current URL, with the intention of typing the next bit of the URL.

(e.g. suppose you want to go to `github.com/dholbert/` , a site you haven't yet visited, and so you want to move the cursor to the end of the current `github.com/` autocompletion so that you can start typing `dholbert/`.)

### Actual behavior
The autocompleted URL visually extends by one directory level (in my case, to `github.com/mozilla-iot/`, and then if I tap again, to `github.com/mozilla-iot/wiki/`, and eventually `github.com/mozilla-iot/wiki/wiki/Supported-Hardware` which is a frequently-visited URL in my history).

### Expected behavior
The contents of the URLbar should not change.  The cursor should simply move to where you tapped (just after the "/" of `github.com/`), and should not autocomplete further (until you type an additional character).

### Device information

* Android device: Pixel 3
* Fenix version: Nightly 190928 18:00

**Comment by dholbert** [comment]
Screencast: https://www.dropbox.com/s/9fvb65l54yldxrd/fenix-autocomplete3.mp4?dl=0

In this screencast, I'm just repeatedly tapping the URLbar (expecting to place my cursor at the end of the URL and to be able to type after the URL that has been autocompleted so far).

It occurs to me that I *could* just start typing after tapping, and it would overwrite the unexpectedly-appearing-bonus-autocompletion, but this is non-obvious.

**Comment by codrut-topliceanu** [comment]
Will be fixed in AC by https://github.com/mozilla-mobile/android-components/issues/7043 and it's PR https://github.com/mozilla-mobile/android-components/pull/7058 .

**Comment by softvision-miralobontiu** [comment]
Verified as fixed on the latest Nightly build from 5/29 with:
* OnePlus 5T (Android 9),
* Samsung Galaxy Tab A6 (Android 5.1.1),
* Google Pixel (Android 10), and
* Sony Xperia Z5 Premium (Android 7.1.1).
