### ISSUE TITLE
Make website checkboxes/tickboxes easier to select

### ISSUE THREAD

**Issue by SpitFire-666** [mozilla-mobile/fenix#5693]
### Why/User Benefit/User Problem
A site I regularly visit uses checkboxes - often many of them. If I use Brave browser, it's smart enough that I can use my thumb to easily and reliably select the checkboxes. Using Fenix, I need to be very precise - even if I zoom in the webpage it's still quite difficult to activate them. Example webpage below with arrows pointing to the types of checkboxes:
![image](https://user-images.githubusercontent.com/38451588/65932324-8f0cad00-e450-11e9-8985-d9ba33bec943.png)

### Acceptance Criteria (how do I know when I’m done?)
Checkboxes will be easier to tick/select - or be on par with how Brave browser behaves.

Thanks!

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-13689)

**Comment by asadotzler** [comment]
geckoview issue?

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813246

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
