### ISSUE TITLE
Option to choose a top nav bar

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/fenix#5694]
## User Story
- As a user who is used to a top nav bar, I want the option to move the nav bar to the top, so I can interact with my browser easily and comfortably.

This user story is the result of UX research, design discussions, and recommendations that took place in Q3. 

Added benefit: top nav bar can auto-hide when scrolling

## Dependency:
#4281  Need to remove QAB first

### Acceptance Criteria
- [ ] I can do go into settings and choose to move the nav bar to the top (default is bottom nav)
- [ ] Once I have changed my setting, the nav bar moves to the top
- [ ] Navbar will auto-hide when scrolling (this used to be possible when we had this at the top)
- [ ] Make sure nav bar is still pinned (doesn't autohide) and works properly when using Custom Tabs

### UX
Abstract: Screens 13 & 14 - https://share.goabstract.com/7cd59d53-ad3a-4b33-8131-74703c1859a2

**Comment by tom-james-watson** [comment]
It sounds like choosing a top nav bar would make the nav bar auto-hide. I personally want a top nav bar but without auto-hiding. Can we make the nav bar position and whether or not to auto-hide two different options? Thanks!

**Comment by imchau** [comment]
Is there a reason why the bottom nav bar can't auto-hide as well?

**Comment by pwd-github** [comment]
@imchau they're working on it. It needs some GeckoView work.

**Comment by dylmye** [comment]
@tom-james-watson perhaps auto-hiding would be a separate option from the position of the nav bar.

Either way a definite +1 for this PR so I can use fenix :)

**Comment by monreal** [comment]
I wondered about the auto hiding of the bottom navbar as well initially. Then I realized the constantly shown bar is what I like about Fenix. That is because the bar is needed for tab management.

**Comment by lime124** [comment]
designs being wrapped up and should be finished by end of sprint tomorrow (Friday).

**Comment by abatishchev** [comment]
@lime124 how the final design looks like? Does it include two separate options: position and whether to auto-hide?

**Comment by lime124** [comment]
@abatishchev the scope of this ticket was limited to selecting the position of the nav bar. thanks!
<img width="363" alt="Screen Shot 2019-10-24 at 3 33 41 PM" src="https://user-images.githubusercontent.com/287322/67530354-b6335480-f673-11e9-9cc4-1aec723595a1.png">

**Comment by martinlanger90** [comment]
can I already use a dev .apk :-)???

**Comment by softvision-miralobontiu** [comment]
Verified as fixed on the latest Nightly builds from 11/27 (#13310607, #13310606) with Samsung Galaxy Note 8 (Android 9), and HTC Desire 820 (Android 6.0.1).
Verified that:
- the user can move the navigation bar to the top (default is bottom nav) from Settings - Toolbar,
- once the setting is done, the navigation bar moves to the top,
- the navigation bar will auto-hide when scrolling,
- the navigation bar is still pinned (doesn't autohide) and works properly when using custom tabs.

**Comment by tom-james-watson** [comment]
Nice to see great progress being made on this. There does, however, seem to be a pretty big flaw with the current implementation.

I have set the toolbar to show at the top, which works as expected:

![image](https://user-images.githubusercontent.com/3852719/69742709-80373380-113d-11ea-8492-e650768caf5e.png)

However, the nav bar still appears at the bottom in the tab overview page:

![image](https://user-images.githubusercontent.com/3852719/69742752-95ac5d80-113d-11ea-80d9-142205302c1d.png)

This is obviously quite inconsistent and jarring. Seems like hopefully quite an easy fix?

**Comment by cadeyrn** [comment]
@tom-james-watson that's #6820.
