### ISSUE TITLE
Add "Share" to the text selection context menu

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/fenix#5696]
### User Story
As a user, I want to be able to share a selected text through the context menu, so I can get to where I need in as few steps as possible.

### Requirements
-Add "share" to the context menu (@jpfaller to provide exact string)
-Add telemetry probe to measure taps on "share"

### Acceptance Criteria

- [ ] When I select a text on a webpage, I see a "share" option in the context menu (see example from Fennec below)
- [ ] When I select a text and tap on "share", the share sheet opens allowing me to share the text with another app.

![image](https://user-images.githubusercontent.com/42752644/66095602-18fa6a00-e566-11e9-8dc3-5d1f5a27a7c2.png)

**Comment by vesta0** [comment]
@lime124 I propose that we skip UX for this issue and refer to the Fennec UI if needed.

**Comment by lime124** [comment]
@jpfaller please let us know if we should using something other than "Share". Thanks!

**Comment by liuche** [comment]
This context menu is in GeckoView (because it's in web content), and we'd be able to use the [BasicSelectionActionDelegate](https://mozilla.github.io/geckoview/javadoc/mozilla-central/org/mozilla/geckoview/BasicSelectionActionDelegate.html) to override the actions created.

We might need to do this in AC.

**Comment by liuche** [comment]
This should be done after #5695

**Comment by vesta0** [comment]
Looks like we already had UX mocks for this from [early](https://mozilla.invisionapp.com/share/8ZQVRNUJW3H#/screens/350752250) in the project so I updated the description and removed the Fennec mocks.

**Comment by jpfaller** [comment]
Let's just go with "Share"

**Comment by vesta0** [comment]
@liuche @bifleming I just noticed that it was removed from the prioritized backlog 8 days ago but there is no comment as to why that happened. Would you mind adding a note here?

**Comment by mcarare** [comment]
Waiting on https://github.com/mozilla-mobile/fenix/issues/5695

**Comment by ekager** [comment]
Work will be done in https://github.com/mozilla-mobile/android-components/pull/6037

**Comment by softvision-miralobontiu** [comment]
Verified that the "Search" option is present in the context menu (and it works) when selecting text, with Google Pixel (Android 10), and HTC 10 (Android 8).

**Comment by madb1lly** [comment]
Hello @softvision-miralobontiu,
This bug is for **share** _not_ **search**. Did you really intend to close this bug?
Cheers :)

**Comment by softvision-miralobontiu** [comment]
@madb1lly thanks for the heads up! I've edited the comment. I meant "Share", not "Search".
