### ISSUE TITLE
UX feedback:- Fenix mixes Home and Tabs tray functionality, I find confusing

### ISSUE THREAD

**Issue by Cheap-Skate** [mozilla-mobile/fenix#570]
On most (all) Android browsers there are four screens:-

1. main content screen
2. search screen
3. Home screen (eg shortcuts, news stories)

and

4. Tabs screen

The first three manipulate content on the currently selected tab only.

The fourth one allows manipulation of tabs (create/delete/rearrange) but never allows manipulation of content of any individual tab.

That seems clear to me at least.

Fenix mixes the two with a kind of HomeTab screen which I find confusing:-

- the bottom half of the HomeTab screen is like the Tabs screen, create/delete/rearrange Tabs (or sessions).
- the top half (search box and 3 dot menu) allow manipulation of content within tabs. Which begs the question... _which tab gets manipulated in what circumstances_.

The rules seem complicated and opaque.

If I tap the big central search box on the HomeTab screen, I think it secretly creates a new tab and then moves to the big blank scary Search screen. But it doesn't make the new tab creation clear. If I type search text and press enter it appears in a new tab. But if I abort the search by pressing Back I end up dropped into the new secretly-created tab which is blank. Not going back to the HomeTab screen.

On the other hand if from the HomeTab screen I go three dot menu > Library > History and tap a history entry I think it overwrites the content of a pre-existing tab rather than creates a new one. Which tab gets overwritten. errrrrr I think it's the most recently used? 

So I think I have two problems:-

- When I am on the HomeTab screen it's not clear what the outcome of some activities will be - will they create a new tab or modify "my last tab" whichever that one is?
- If I move to the big scary blank search screen I have no idea what happens when I press "enter" or "
back", it depends on the context of how I entered it (from the URL bar or from the HomeTab screen)

I got this insight from looking at Kiwi browser which has a nice search page - the search box appears over the content of the current tab, I can still see the content, so it's clear that if I search I will modify the content of the tab underneath the search box. Always. Simples.

(This is really a restatement of #562. Lots of words eh? That's me all over)

**Comment by Cheap-Skate** [comment]
OK if you will indulge me in another long post I think I understand my issue and perhaps I can make more constructive comments about it? Even make some suggestions ;) I realise I’m taking up lots of your time.

Most browsers I use (desktop and mobile) make it very clear that Search and Home/Top Sites take place within the current tab. And then there is a separate metaphor for dealing with the array of tabs I have open at any time (e.g. a tabs tray). The two are distinct:- actions in Search and Home/Top Sites clearly only affect content in the current tab, whereas actions in the tabs tray only add/delete/rearrange tabs, they don’t affect content within tabs.

The browsers I like give strong visual cues that Search and Top Sites act only on my current tab. Kiwi is a good example, with a bottom URL bar. Samsung Internet works much the same with a top URL bar, ditto Chrome, Edge, Fennec blah blah.

In Kiwi the Content view has a strong URL bar at the bottom. When I move to Home/Top Sites the URL bar is unchanged:- Home/Top Sites is clearly just a different Web page in the same tab. And when I move to Search I get some more visual clues:- the URL bar remains (roughly) the same, albeit higher up because of the keyboard. Also, the search suggestions appear in a window floating over that tab’s Web content, just like on a desktop browser. The topmost Web content of the tab is still visible as a hint that tapping a search suggestion will change the contents of the current tab. And then there’s an entirely separate tabs tray. Which only adds, deletes, rearranges tabs. There is a 3-dot menu in the tabs tray but it doesn’t allow me to see eg History.  So I can’t change the contents of a tab from within the tabs tray.  I have to select or create a tab and then change it using Search, Home/Top Sites or 3 dot menu > History.

<img width="671" alt="picture 1" src="https://user-images.githubusercontent.com/40568887/52970181-d60ace00-33aa-11e9-945f-d714a3cd2e10.png">

In Fenix it’s different and that’s where my confusion comes from. 

Search is not clearly tied in with the current tab. Search is just a blank box with the URL bar in a very different position & with different styling to Content view. So it’s not entirely clear that if I Search, I will affect the content of the current tab. I guess I will learn in time but it's not super slick. Similarly there is a (so far non functional) Shortcuts button which I assume will also affect the content in the current tab. Again, learnable but not super slick. Search gets even more disjointed if I reach Search by pressing the big Google box on the HomeTabs screen:- I move to the Search page, but in a new tab of which I am not aware.

HomeTabs is a hybrid. The bottom half of HomeTabs is a tabs tray which works much like Kiwi/Samsung/Fennec. I can’t alter the contents of a tab by using it. Fine. The middle part of HomeTabs is actually a ginormous Create New Tab and Move To Search button. But the action on pressing that button is not clear, see previous paragraph. Why’s it there? It seems a bit out of place in a tabs tray. And finally the top of the HomeTabs tray is the 3 dot menu which, if I go 3 dot menu > Library > History I can alter the content of a tab. But which tab ??? To me it's very confusing to be able to modify the contents of a tab from the tabs tray.

<img width="676" alt="picture 5" src="https://user-images.githubusercontent.com/40568887/52970980-a610fa00-33ad-11e9-84fb-28ac2e31b6a2.png">


So my suggestions would be, break the screens down into something more conventional

- tie the Search page into the current tab with visual cues. Make sure the Search bar has the same styling as the URL bar (roundrect, shading etc). But I think it needs more, perhaps a bottom toolbar, perhaps hinting at the Web content from the current tab with transparency or peeking from behind?

- split the HomeTabs tray into a Home page and a tabs tray. Tie Home page clearly into the current tab with a URL bar. Ensure Tabs tray does not allow change to any tab’s content. i.e. remove Your Library from 3 dot menu.

- move the ginormous Google search box onto the Home page. Ensure that it doesn’t open a new tab, it just moves to the Search screen on the current tab. Or, if you keep it on the tabs tray, make it clearer that it’ll open a new tab and move to it ( a + icon?). Or, just make it much much smaller say a + with a magnifying glass icon, or ditch it altogether some might argue it's just a waste of screen ;)

- move Shortcuts into the Home page, because now you’ve got a whole empty Home page with just a big Google search box on it :)   

That’s more or less what the other Android browsers I use do.  

And there are fringe benefits:-

- one tap access to Shortcuts. Just tap the Home button. (ATM Fenix requires two taps:- URL bar, Shortcuts)
- the tabs tray can now show "lots of tabs” without scrolling (ATM Fenix only shows … one and a half  tabs ... perhaps less than ideal)

Just some suggestions, sorry to be so long winded. Hope some is helpful & keep up the good work.

**Comment by colintheshots** [comment]
We appreciate the feedback. I'll leave it up to our UX team to decide what to make of it.

Our aim is not to replicate existing Android web browsers. Fenix is built around a hypothesis that users use browsers differently on mobile and that existing mobile browsers have been desktop browsers simply transplanted to fit on a smaller screen. I believe that 100%. Why was the URL bar ever on the top? It's like when programming languages added mandatory line numbers just because that's how they worked on punch cards.

The home screen is built around short-lived tabs and long-lived sessions. Your tabs vanish into an archived session after ten minutes away from the browser. If your whole session is usually a single tab, it would seem to limit the usefulness of that session when you restore it. So we have different behaviors from the home screen and the URL bar. Make of it what you will. We may need to iterate, but why copy?

All of this is to say-- it's a user research hypothesis that mobile browsing UX could be better in this way and we could turn out to be totally wrong. One thing is for certain-- none of us will accept the argument that it has always been done a certain way, so it should always be. We intend to learn a better way even if we make mistakes along the way.

**Comment by Cheap-Skate** [comment]
Yep, I agree you need to do something different. I'm Intrigued to see where the tab/session thing goes. I'm aware you're pushing the boundaries and that I am a curmudgeon stick in the mud. But I thought feedback worth giving, even if it's pretty early. Thanks for your time!

**Comment by lime124** [comment]
Hello we are in the process of re-examining the session UI which is why i'm going to put in the icebox for now and we can re visit once those designs are done to see if the concerns are still there.

**Comment by Cheap-Skate** [comment]
Thanks, I'll be intrigued to see how things evolve. If you look on reddit you'll see that some people seem to like the session UI... So I may be a vocal minority ;)

**Comment by simonvanderveldt** [comment]
Would be nice if there's an option to always open/restore the previous session (or better yet, simply don't archive the open tabs at all) like all browsers do.
That's what I'd expect from a browser, irrespective of on which device it's used.

**Comment by cadeyrn** [comment]
@simonvanderveldt The session concept was removed from Fenix, opened tabs won't automatically be "archived".

**Comment by simonvanderveldt** [comment]
Awesome! Thanks for the good news :)

**Comment by sblatz** [comment]
Closing this as it will be changed in our [redesign](https://mozilla.invisionapp.com/share/7PSR7KCSW6Z#/372749649_Latest). 

@topotropic please keep these comments in mind 😄
