### ISSUE TITLE
[Bug] "new tabs being opened" animation makes Fenix seems slower than it actually is.

### ISSUE THREAD

**Issue by Lululalu** [mozilla-mobile/fenix#5703]
## Steps to reproduce
Search something on the web
Open 4 or 5 links in new tabs
Touch the tab icon

### Expected behavior
The links opened in new tabs are just there

### Actual behavior
It takes 1 or 2 seconds to see the new tabs once you touch the tab icon, because the animation is taking time.

### Device information

* Android device: Galaxy A5 2017 Android 8.0
* Fenix version: 190930 nighty

**Comment by darkwing** [comment]
I cannot reproduce this; on my Pixel 4, the tabs display immediately without animation.  

@Lululalu Could you have another look?

**Comment by AndiAJ** [comment]
Hi, **verified as fixed ** on the latest **`Nightly Build # 20440606 from 2/13`** using the following devices:
• Google Pixel 3a (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7.0)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

► Videos from Huawei Mate 20 Lite 
![20200213-110225](https://user-images.githubusercontent.com/51314259/74418223-b9d02e80-4e50-11ea-9aab-f25f0889b452.gif)


@Lululalu - In case you still encounter this problem, please re-open this issue and attach a video to have a better overview of what's actually happening. ☺️
