### ISSUE TITLE
[Telemetry] Media usage

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/fenix#5705]
#### Description & Product Manager / Data Scientist User Story
- As a product owner, I want to know how often the browser is used to play media, so I can prioritize media related bugs accordingly. 

#### What probes 

New probes to track the following states:

| Action | Item            |  Description                              | Works?  |
|--------|-----------------|-------------------------------------------|------|
| PLAY   | state           | Media started playing.                    |       ❌     |
| PAUSE  | state           | Media playback was paused.                |     ❌    |
| STOP   | state           | Media playback has ended.                 |     ❌      |

### Acceptance Criteria
- Event pings can be queried via re:dash
- We are sending telemetry events for the actions listed in the requirements
- We have documented the telemetry
- We have asked a data steward to [review](https://github.com/mozilla/data-review/blob/master/request.md) the telemetry
- NOT an AC: Data science to create dashboard or further graphs (this will be a separate issue, this issue is only about hooking up the events described and that they can be queried in re-dash)

**Comment by sblatz** [comment]
Re-opening for QA to verify

**Comment by AndiAJ** [comment]
Hi, I've just checked this on the latest Nightly Build #13230608 from 11/19 using a Google Pixel 3a XL (Android 9).

[Logcat](https://github.com/mozilla-mobile/fenix/files/3864491/media.txt)
[Glean dashboard](https://debug-ping-preview.firebaseapp.com/pings/aj-t191110)

Youtube - Ping e0f5b53e-5a3c-44bd-9044-2c5903da2fa1
✔️ Play
✔️ Pause
✔️ Stop by putting the app in background

Twitch - Ping 1a62e362-d0e8-4ed0-ad8c-b851a4aa3048
✔️ Play
✔️ Pause
✔️ Stop by closing the tab (Media Playback continues to play even if Fenix is put in background)


Vimeo - Ping 517fc32b-0bc9-4184-b4cf-1f0e605c4b5e
✔️ Play
✔️ Pause
✔️ Stop by leaving the media playback to end 

❓ Play/Pause from the open tabs section - Ping 5ef667d2-b9ec-47da-8239-d4876c925295

**Aren't correctly generated** (seem to be inverted,  when pressing **pause** a "media_play" "tab" category ping is generated and vice versa) the correlation with the "media_state" category is done properly.

E.g.
**1.** Tap **pause** from the Open tabs
"events": [
        {
          "category": "tab",
          "name": "**media_play**",
          "timestamp": 0
        },
        {
          "category": "media_state",
          "name": "**pause**",
          "timestamp": 135
        }
      ]

**2.** Tap **play** from the Open tabs
"events": [
        {
          "category": "tab",
          "name": "**media_pause**",
          "timestamp": 0
        },
        {
          "category": "media_state",
          "name": "**play**",
          "timestamp": 127
        }
      ]

@vesta0 & @gabrielluong - Not sure if the Media usage from the Open tabs was also covered or should have been covered.
Please and let me know how should we proceed. :relaxed:

**Comment by AndiAJ** [comment]
I'll remove the QA needed label until further notice.

**Comment by gabrielluong** [comment]
Hi @AndiAJ, only media_state pings were covered in this fixed. Seeing that tab.media_play and tab.media_pause are pinged incorrectly, can you open a new issue on that and we will look into that.

**Comment by AndiAJ** [comment]
Hi @gabrielluong , thanls for clarifying this! :relaxed:
I've re-tested this on **Fenix Nightly Build #13391806 from 12/5** and it **works properly**.

Youtube - Ping 6e8cf0ee-4a3c-4a23-bb8e-5c2e09ae5023
✔️ Play
✔️ Pause
✔️ Stop by putting the app in background

Twitch - Ping 1c6ed89b-9b1c-42ef-9cda-4b6bf553178f
✔️ Play
✔️ Pause
✔️ Stop by closing the tab (Media Playback continues to play even if Fenix is put in background)

Vimeo - Ping 34d7e3e2-2ffd-457a-a132-8a9c4f8c6d3f
✔️ Play
✔️ Pause
✔️ Stop by leaving the media playback to end

[Logcat](https://github.com/mozilla-mobile/fenix/files/3932782/med.txt)
[Glean Dashboard](https://debug-ping-preview.firebaseapp.com/pings/aj-test061201)
