### ISSUE TITLE
[Fenix] Enhanced Tracking Protection UI Review

### ISSUE THREAD

**Issue by AmyYLee** [mozilla-mobile/fenix#5709]
Hi, 

This is a UI review bug for ETP. Please let me know if you have any questions

![Edits to ETP](https://user-images.githubusercontent.com/5992746/65986003-fd516f80-e450-11e9-92d5-01b8d8afb7a2.png)

**Comment by AmyYLee** [comment]
Also, is there a way we can have the toggle already switched to ON for ETP in the panel rather than have it animate to ON when the user taps the icon to open the panel? It seems to be a bit distracting when you see a flash of animation of the toggle and icon animating when you open the panel. Also at 0:20 mark, the content of the panel seems to load in 2 parts with "tracking content"
having a delay when loading. This makes it feel janky. Is there a way we can fix this? Thanks

Video for reference
https://cl.ly/79379452546a

**Comment by mcarare** [comment]
@AmyYLee For # 6 : Do you want the radio buttons aligned with header, or the text? TY

**Comment by jawz101** [comment]
I think the strict/standard buttons look better either aligned with the ETP shield (centers of buttons aligned with the center of the shield) or indented right more as in your screenshots in the 1st post.

**Comment by AmyYLee** [comment]
> @AmyYLee For # 6 : Do you want the radio buttons aligned with header, or the text of the radiobuttons? Please also check the other change requierments in screenshot below! TY
> 
> <img alt="" width="50%" src="https://user-images.githubusercontent.com/48995920/66316621-a9e39380-e920-11e9-922a-fcc051bece27.png">

The radio buttons should be aligned to the "Enhanced Tracking Protection" header like this

![ETP](https://user-images.githubusercontent.com/5992746/66668206-ac950000-ec22-11e9-9097-343d636f0934.png)

**Comment by softvision-miralobontiu** [comment]
Verified as fixed that the Standard/Strict radio-buttons are aligned with the title and the ETP UI, with the latest Nightly 11/25 with Google Pixel 3 (Android Q), and Huawei P9 Lite (Android 7).
