### ISSUE TITLE
[Bug] Fill link from clipboard text hard to read in dark mode

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#5712]
We should use `accentUsedOnDarkBackground` attr instead.

<img width="492" alt="image" src="https://user-images.githubusercontent.com/4400286/65989913-73e57180-e43f-11e9-96a6-498a3fa4b104.png">

Pulling this in since it's an accessibility concern for a feature we shipped in 2.1

**Comment by sv-ohorvath** [comment]
Verified as fixed on latest master (10/7).
