### ISSUE TITLE
[Bug] There is too much space under the address bar (or too little above it)

### ISSUE THREAD

**Issue by Lululalu** [mozilla-mobile/fenix#5715]
### Actual behavior
![Screenshot_20191001-004033_Firefox Preview](https://user-images.githubusercontent.com/32398857/65994252-431a3200-e469-11e9-8b1d-71af71f2dfc9.jpg)

### Device information

* Android device: Galaxy A5 2017 Android 8.0
* Fenix version: 191001 nightly

**Comment by ekager** [comment]
@boek do you know if this is supposed to be vertically centered?

**Comment by topotropic** [comment]
Yes, 8dp top and bottom https://share.goabstract.com/7ebb1753-4b09-4f1e-a39e-550ac17f00a7?collectionLayerId=5b343ddc-788e-42cf-bdb7-6919086e89ff&mode=build

**Comment by VMadalin** [comment]
@topotropic Thank you for share the definition, after review the code I saw an incoherence values having 8dp for top and 10dp for bottom . I just created the PR.
