### ISSUE TITLE
Reverse Image Search

### ISSUE THREAD

**Issue by Lululalu** [mozilla-mobile/fenix#5718]
### Why/User Benefit/User Problem
Holding an image and then having "search image" in the context menu is just, useful. Other browsers already offer this feature natively and through extensions. 

### What/Requirements
Reverse image search

### Acceptance Criteria (how do I know when I’m done?)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-13705)

**Comment by s-ankur** [comment]
We now have an extension that does this

**Comment by Poopooracoocoo** [comment]
for any searchers out there, this is also referred to as search by image

**Comment by boek** [comment]
This has not revived any duplicates or other interactions. We will not be moving this request to Bugzilla.
