### ISSUE TITLE
[webcontent] No context menu while holding images on Google Images

### ISSUE THREAD

**Issue by Lululalu** [mozilla-mobile/fenix#5720]
## Site with issue and any steps to reproduce
Search anything on Google
Touch "images"
Touch any image to enlarge
Hold the image

### Expected behavior
 The context menu is exhibited

### Actual behavior
Nothing happens

### Does toggling Tracking Protection fix the issue? (Press the lock icon in the toolbar while on the site to see toggle)
No

### Can you reproduce in [Firefox for Android](https://play.google.com/store/apps/details?id=org.mozilla.firefox)?
Yes
### Can you reproduce in Chrome (or other non-Mozilla browser)?
No

### Device information

* Android device: Galaxy A5 2017 Android 8.9
* Fenix version: 191001 nightly

**Comment by Lululalu** [comment]
The same is happening on duckduckgo

**Comment by ekager** [comment]
Closing for #9484
