### ISSUE TITLE
[Bug] Search widget icon is pixelated

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#5722]
<img width="500" alt="image" src="https://user-images.githubusercontent.com/4400286/65999745-e0b63700-e452-11e9-807d-b68e5840a325.png">

**Comment by sblatz** [comment]
I didn't get around to this last polish sprint. Going to unassign :)

**Comment by mcarare** [comment]
For me it doesn't look pixelated on all devices, just some, but with same Android version (9).

**Comment by darkwing** [comment]
Is this an image issue?  What generally causes image distortion between devices?  Size assignment?

**Comment by sblatz** [comment]
Hmmm. @mcarare I'm still seeing it as pixelated on my Galaxy S9:

<img width="350" alt="image" src="https://user-images.githubusercontent.com/4400286/72098838-2b5a1180-32d4-11ea-9f48-32b379db28b6.png">

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **Nightly Build #20100616 from 01/10** using the following devices:
• Google Pixel 3a (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

► Screenshot
![rsz_screenshot_20200110-090148](https://user-images.githubusercontent.com/51314259/72132728-5bfb8300-3388-11ea-8e52-16383b5e9123.png)

**Comment by sblatz** [comment]
I'm still seeing this as pixelated on my Galaxy S9 (nightly 1/12/20)

I've removed and re-added the widget just to make sure it wasn't an old one.

<img width="492" alt="image" src="https://user-images.githubusercontent.com/4400286/72370477-3091d480-36b7-11ea-9081-4f9d114618df.png">

@mcarare

**Comment by mcarare** [comment]
@sblatz I've tested on latest master 6 or 7 devices (physical devices) and I do not see any pixelation. 
This includes a Galaxy S9 (Android 9), see screenshot below.
![widget](https://user-images.githubusercontent.com/48995920/72415423-19b5b580-377d-11ea-9d78-4dee505953a1.png)

**Comment by mcarare** [comment]
@sblatz do you still have this issue?

**Comment by sblatz** [comment]
I do, even on the latest nightly. Galaxy S9, Android 9, OneUI 1.0, Fenix Nightly 1/22.

<img width="350" alt="image" src="https://user-images.githubusercontent.com/4400286/72922756-7b889900-3d02-11ea-9b6e-2003b5c96c50.png">

**Comment by mcarare** [comment]
@sblatz that is puzzling. I've tried on the same device as yours and with all screen resolutions available. And I don't have any pixelation.

**Comment by AndiAJ** [comment]
Hi, re-checked this matter on the latest **`Nightly Build #20290608 from 1/29`** using the following devices and **on all of them the icon is properly displayed**:

• Google Pixel 3a XL (Android 10)
• Google Pixel 3a (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S9 (Android 8)
• Samsung Galaxy S8+(Android 8)
• Samsung Galaxy S7 (Android 7)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

► Screenshot from Samsung Galaxy S9
![rsz_3screenshot_20200129-142518_samsung_experience_home](https://user-images.githubusercontent.com/51314259/73357139-73050500-42a4-11ea-89d8-8d1783b4663d.jpg)

@sblatz do you still have issues on your Galaxy S9? ☺️

**Comment by mcarare** [comment]
As per the comment above, I am closing this. @sblatz let us know if there any issue still comes up.
