### ISSUE TITLE
[Downloads] Full featured Downloads

### ISSUE THREAD

**Issue by liuche** [mozilla-mobile/fenix#5724]
### Why/User Benefit/User Problem
As a user, I want to have control over the status of my downloads, such as pausing or cancelling a download.

### What/Requirements
(This is summarizing the Phase 2 Downloads plan from @lime124 )
In native Fenix UI, we want to manage downloads so that:
- [ ] Starting download will be in notification bar
- [ ] Download progress is shown (not an indeterminate)
- [ ] Download can be cancelled
- [ ] Shortcut shown to file location
- [ ] Download can be removed #352 
- [ ] Error handling (e.g. showing status for failed download)

### Acceptance Criteria (how do I know when I’m done?)
Downloads can be controlled as described above.

**Comment by vesta0** [comment]
@liuche how is this issue different than #5582 ?

**Comment by liuche** [comment]
Sorry, let me dupe this, I didn't see the other issue.
