### ISSUE TITLE
[Bug] Crash when accessing https://github.com/mozilla/tracking-test on Play Store Nightly

### ISSUE THREAD

**Issue by softvision-miralobontiu** [mozilla-mobile/fenix#5729]
## Steps to reproduce
1. Upload Nightly from Play Store
2. Go to https://github.com/mozilla/tracking-test.

### Expected behavior
The page should load, without issues.

### Actual behavior
The app crashes.

### Device information
* Android device: Samsung Galaxy Note 8 (Android 9)
* Fenix version: 191002 (#12750608)
* Not reproducible on Nightly 191002 (#12750607)
* Not reproducible on RC 2.1.0-rc.3

[logcat.txt](https://github.com/mozilla-mobile/fenix/files/3680655/logcat.txt)

**Comment by ekager** [comment]
Could we retest this? Maybe related to weird crash we were also seeing in #5668

**Comment by softvision-miralobontiu** [comment]
I cannot reproduce it with the latest Nightly build from Play Store, 191004 (#12771805) with Samsung Galaxy Note 8 (Android 9), Xiaomi Mi 8 Lute (Android 9), and Samsung Galaxy Tab A6 (Android 5.1.1).
I'm closing this issue.
