### ISSUE TITLE
Determine research plan for proxy

### ISSUE THREAD

**Issue by topotropic** [mozilla-mobile/fenix#5731]
Collect hypothesis and discuss quan and qual research options with user research team

### Acceptance Criteria
- [x] Identify hypothesis
- [x] Discuss with user research team and identify next steps

**Comment by topotropic** [comment]
I discussed the hypothesis with Elisabeth and Alice and filed a bug on bugzilla (1585785)

**Comment by lime124** [comment]
@topotropic can this be close based on your comment above? can you open some new issues to cover what you're working on during the next sprint (or put them in the "in design" column for visibility). thanks!!
