### ISSUE TITLE
Create flow based on desktop requirements for proxy

### ISSUE THREAD

**Issue by topotropic** [mozilla-mobile/fenix#5732]
Map out a flow based on desktop requirements

### Acceptance Criteria
- [x] UX flow discussed with ENG
- [x] user stories based on flow
- [x] high-level mocks

**Comment by topotropic** [comment]
Colin and I created a bunch of user stories https://github.com/orgs/mozilla-mobile/projects/46

**Comment by lime124** [comment]
i know this isn't totally following the fenix sprints,  but just cleaning up thing in preparation for sprint planning tomorrow...

i think you, @topotropic, delivered this today? can this issue be closed?
