### ISSUE TITLE
[Bug] Open from private mode notification should always open the private mode homescreen

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#5733]
## Steps to reproduce
1. Open a tab in private browsing.
2. Switch to normal browsing home.
3. Minimize the app.
4. On the private tabs notification, tap Open.
### Expected behavior
The private mode home is displayed showing the private tabs.
### Actual behavior
The normal browsing mode is displayed.
### Device information

* Android device: Galaxy Tab 3 (Android 8)
* Fenix version: Nightly 10/2, 2.1.0-rc3.

related issue: #6470

**Comment by AndiAJ** [comment]
Hi, I've just checked on the latest Nightly Build #13010606 using the following devices:
• Google Pixel 3a XL (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4(Android 5.1.1)

✔️ Tap Open from the notification works.
❌ Tap on Delete and Open doesn't work. The open PB tabs are closed, on the other hand the user isn't redirected to PB.

► Video
![20191028_104456](https://user-images.githubusercontent.com/51314259/67664577-92705700-f970-11e9-9d11-6ea94e6d0ddc.gif)


@NotWoods & @BranescuMihai - I would kindly ask you to review the above. :blush:
I'll remove the QA needed label until further clarifications.

**Comment by AndiAJ** [comment]
Reproducible on  v 2.3.0-rc.2 using a Huawei MediaPad M3 Lite 10 (Android 7)

**Comment by BranescuMihai** [comment]
@AndiAJ Yes, for some reason, I thought of the behaviour as in Chrome, where delete also closes the incognito mode. But for us, the button says Delete and Open, so you're right. Will add a fix for it!

**Comment by mcarare** [comment]
related issue: #6470

**Comment by brampitoyo** [comment]
As @AmyYLee wrote in https://github.com/mozilla-mobile/fenix/issues/6470#issuecomment-558324237:

> …here is the updated Notification menu. With one action only on tap: Close private tabs.

This makes the “Open” action no longer relevant.

**Comment by AndiAJ** [comment]
In this case I'll go ahead and close this issue.
Thx @brampitoyo ! :relaxed:
