### ISSUE TITLE
[Bug] The incognito icon looks out of place/misaligned

### ISSUE THREAD

**Issue by Lululalu** [mozilla-mobile/fenix#5735]
![Screenshot_20191002-115359_Firefox Preview](https://user-images.githubusercontent.com/32398857/66057581-5a135f80-e50f-11e9-99f5-a4bd8ccf4569.jpg)

**Comment by NotWoods** [comment]
UX team: Should we adjust this icon as shown below?
![](https://user-images.githubusercontent.com/18151158/66116151-86dc7b00-e5d2-11e9-8fcb-24623739bab1.png)

**Comment by brampitoyo** [comment]
@NotWoods Thanks for the super helpful mockup. Yes. We should adjust the icon as shown.

**Comment by NotWoods** [comment]
The screenshot is from an implementation by contributor @VMadalin 😄

**Comment by brampitoyo** [comment]
Then a big thank you to @VMadalin!
