### ISSUE TITLE
[Bug] Pop to home screen after deleting tabs in settings

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#5736]
Currently we pop to the home screen if the user deletes their open tabs. This is intentional (see `popAfter` in `DeleteBrowsingDataFragment`) because when a user went Browser -> Settings -> Delete open tabs, we need to get them out of BrowserFragment. 

However, this causes buggy behavior when the user did this from Home -> Settings -> Delete and can be surprising.

To improve this, we should probably handle the "popping" on `BrowserFragment`. 

![popping 2019-10-02 09_06_49](https://user-images.githubusercontent.com/4400286/66061361-2b3bc000-e4f4-11e9-91a5-8a04c4d59096.gif)

[Update by Tif Oct 24th 19] 
Pulling up tl;dr decision from Bram's comment:

1. In the case of Open Tab → Settings → Delete open tabs, pop users back to the homescreen.
2. In the case of Homescreen → Settings → Delete open tabs, we will move users one level up back to Settings

cc @ekager

**Comment by brampitoyo** [comment]
Hi @sblatz, just to clarify. Is there a difference between going to:

> Browser -> Settings -> Delete open tabs

And going to:

> Home -> Settings -> Delete

In the behaviour you’ve shown in the GIF, things look good to me – but perhaps I’m wrong because I haven’t worked on Fenix for a while!

Did you propose not to pop to home screen?

**Comment by sblatz** [comment]
@brampitoyo Currently the behavior of both of those steps are the same: pressing "delete open tabs" in both of those cases pops you to the home screen.

I think when you do 
> Browser -> Settings -> Delete open tabs

it should not pop at all since the user isn't currently in a browsing session. It seems disorienting to me that we pop the user up two levels (back to settings, back to home) when pressing "delete open tabs"

**Comment by brampitoyo** [comment]
Thanks heaps, @sblatz, for patiently going over this issue with me.

We’ve met earlier today, and agreed that:

1. In the case of Open Tab → Settings → Delete open tabs, we have to pop users back to the homescreen, because the _only way_ to close this open tab is to exit it, and the _only place_ to exit is to the homescreen.
2. In the case of Homescreen → Settings → Delete open tabs, we will move users one level up (back to Settings – where the user just was moments ago), instead of all the way back to the homescreen (which would be disorienting).

**Comment by lime124** [comment]
for group triage - are there any dependencies? can this be worked on by a contributor?

**Comment by sv-sdeiac** [comment]
Verified as fixed using the latest version of Firefox Preview Nightly 1/16 build #20160806.

Devices:
- Nokia 6 (Android 7.1.1);
- Motorola Moto G6 (Android 8.0);
- Samsung Galaxy Note 8 (Android 9);
- Google Pixel (Android Q).
