### ISSUE TITLE
[Telemetry] "Launch links in private tab" toggle

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#5737]
#### Description & Product Manager / Data Scientist User Story
- As a product owner, I want to know how often users choose to open links in a Fenix private tab, to understand whether this is a popular use case. 

#### Hypothesis
- We believe this feature is useful to users since this was a key benefit of Firefox Focus. 

#### What questions will you answer with this data?
-How many users enable the Launch in private tab toggle
-How often users launch a link in private tab

#### What probes (suggested, if applicable)
-User enables "Launch links in private tab" toggle in settings
-User opens a link in private browsing (can we measure this?)

### Acceptance Criteria (Added by PM)
- Event pings can be queried via re:dash
- We are sending telemetry events for the actions listed in the requirements
- We have documented the telemetry
- We have asked a data steward to [review](https://github.com/mozilla/data-review/blob/master/request.md) the telemetry
- NOT an AC: Data science to create dashboard or further graphs (this will be a separate issue, this issue is only about hooking up the events described and that they can be queried in re-dash)

**Comment by vesta0** [comment]
@sblatz Will do! I assume this wasn't already done when Vrushank worked on this feature?

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest Nightly Build #13010606 using a Google Pixel 3a XL (Android 9).

✔️ Disable Open link in a private tab: Ping f6b4cc84-432e-4dfb-aaa9-e5b984b9b99c
✔️ Enable Open link in a private tab: Ping 871bdb4e-2cf0-4919-9841-88648128e05d

✔️Long tap + Open in Browser from Gmail: Ping 15455381-895a-4fa3-866b-4523de2d20da
✔️Action button from a custom tab: Ping 8667eca2-f5a2-4d80-94df-001543540a27
✔️Playstore link: Ping 81dc6bbb-3118-4d42-b90c-e1d264b44cb7

[Logcat](https://github.com/mozilla-mobile/fenix/files/3778727/PBlink.txt)

[Glean dashboard](https://debug-ping-preview.firebaseapp.com/pings/aj-test281000)

@sblatz - Please review and re-open if I missed something. :blush:
