### ISSUE TITLE
Web Extensions Support

### ISSUE THREAD

**Issue by TitanNano** [mozilla-mobile/fenix#574]
### Why/User Benefit/User Problem
1. Like on desktop, users want to add individual features and extend their browser beyond what Mozilla provides. 
2. Users want to use the same extensions on their phone, they use on their desktop machine.
3. Users will want to continue using the extensions they are currently using in Fennec.

### What / Requirements
Feature parity with Firefox for Android (Fennec) / macOS / Windows / Linux / etc.

### Acceptance Criteria (how do I know when I’m done?)
I think feature parity with Fennec would be acceptable for a start.

**Comment by bbinto** [comment]
Not for MVP, will look at it for further versions

**Comment by hackfix** [comment]
That is really bad news...
I feel like most people use Firefox (Android) because of web extesions. No other browser on Android supports web extensions - so it would be the most important USP.
Fenix without Web Extensions will not be very popular.

**Comment by TitanNano** [comment]
@bbinto when exactly is fenix supposed to replace fennec as Firefox for Android? Once the MVP is done, or when it reaches feature parity?

**Comment by bbinto** [comment]
@TitanNano - We are currently finalizing the transition plan, however we know that Fennec will not be replaced for the MVP, we will make sure our existing users will get the experience they expect later in the year.

**Comment by jawz101** [comment]
@TitanNano can you change the wording in this statement to include Firefox for Android (Fennec).  Since the current Android browser already supports web extensions I wouldn't want to imply that a new browser for Android would be adding something the current browser for Android already has as well.

> ### What / Requirements
> 
> Feature parity with Firefox for macOS / Windows / Linux / etc.

**Comment by yoasif** [comment]
FYI, Kiwi browser now supports Chrome extensions on Android -- so the competition for a browser with extensions on Android is heating up. 

https://www.xda-developers.com/kiwi-browser-google-chrome-extensions-android/

**Comment by hjyoung1** [comment]
This is actually main feature for me. I hope we will get this sooner.

**Comment by sblatz** [comment]
Product is looking into feasibility

**Comment by cpeterso** [comment]
Tentatively adding `needs:gv` label until we know what additional GV work will be needed to support general purpose extensions.

**Comment by vesta0** [comment]
Thanks for filing! This feature will be explored here #5315
