### ISSUE TITLE
Ability to zoom in on a video

### ISSUE THREAD

**Issue by kuba-orlik** [mozilla-mobile/fenix#5740]
It would be a killer feature if Firefox Preview had the ability to zoom in a video file during full-screen playback, like Telegram on Android does

### User Benefit

Multiple benefits. It'd be easier to show a particular element of a video, for example. Also, it'd be another feature to draw new users

### Acceptance Criteria (how do I know when I’m done?)

When video is played back at full-screen, one can pinch to zoom in on a video and pan around.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-13721)

**Comment by kbrosnan** [comment]
This has not revived any duplicates or other interactions since it was filed. We will not be moving this request to Bugzilla.
