### ISSUE TITLE
Update "launch links in private tab" functionality

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#5742]
After some more investigation and discussions with @AmyYLee we're deciding to move forward with the original UX found in #514

We need to bring the activity-alias back and update the default browser pref:

![image](https://user-images.githubusercontent.com/4400286/66071414-f46fa500-e507-11e9-854e-2449aadfb9f0.png)

**Comment by sv-ohorvath** [comment]
@sblatz I think this has caused https://github.com/mozilla-mobile/fenix/issues/5784

**Comment by sv-ohorvath** [comment]
Found 2 new issues on the latest Nightly 10/4. I've set them as blockers to this issue and I'm removing the "qa needed" label until they are fixed.

**Comment by sv-ohorvath** [comment]
@sblatz The crash is now fixed, but Android 5&6 users won't be able to use this feature as long as it's hidden. Do we want to keep it this way?

**Comment by sblatz** [comment]
@sv-ohorvath on Android 5&6 are you able to ever see the "Open with..." "(Private) Firefox Preview"?

**Comment by sv-ohorvath** [comment]
> @sv-ohorvath on Android 5&6 are you able to ever see the "Open with..." "(Private) Firefox Preview"? (before a default browser is set and you're opening a link)

@sblatz Yes, you can use the "Open with Private FP" function that way. The downside is you can't switch back to open in NBM unless you clear the app data/preferences from system settings.

**Comment by sblatz** [comment]
@sv-ohorvath I'm going to file a follow-up ticket for those cases, so this ticket doesn't rot, and since it will work for most of our users. We will need UX to design a way for it to work on those other versions.

**Comment by sblatz** [comment]
I filed https://github.com/mozilla-mobile/fenix/issues/5870. 

@sv-ohorvath I'm closing this since we have that to track the 5&6 issue. Let's file follow-ups for any future bugs on this :)
