### ISSUE TITLE
Site permissions 3rd party cookies option

### ISSUE THREAD

**Issue by runboy93** [mozilla-mobile/fenix#5744]
3rd party cookies option is missing, could be added to "site permissions" options tab.

Many other privacy browsers either have 3rd party cookies disabled by default or have cookies options, Firefox Focus have options too, but Fenix so far doesn't have. We should have right to choose from!

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-13723)

**Comment by Amejia481** [comment]
By default Fenix is blocking 3rd party cookies when you have tracking protection ON on both **Standard** or with **Strict** options.

**Comment by runboy93** [comment]
"Strict"? what is that, I don't see one?

**Comment by Amejia481** [comment]
Tap the shield icon -> **Protection Settings**

By default Fenix comes with tracking protection enabled (strict)

**Comment by runboy93** [comment]
https://www.whatismybrowser.com/detect/are-third-party-cookies-enabled

Why does this still says "yes", 3rd party cookies enabled?

**Comment by Amejia481** [comment]
I will investigate further, I will get back to you!

**Comment by runboy93** [comment]
I don't seem to get that shield shown up, despite visited numerous webpages that should have got some tracking, does protection work at all?

**Comment by Amejia481** [comment]
The shield only shows up on Nightly builds, if you are on Beta you are not going to see the shield, but tracking protection is working alike.

**Comment by Amejia481** [comment]
@runboy93 my bad: By default, we are accepting **only first-party and non-tracking third-party cookies**  as blocking completely **3rd party cookies** could cause breakage in some pages. 

For this reason it says "yes" on 3rd party cookies enabled, as we are accepting **non-tracking third-party cookies**.

Your feature request is still valid as Fenix doesn't have a way to change it, like FireFox desktop and other browsers do.

![image](https://user-images.githubusercontent.com/773158/66080511-37477200-e534-11e9-8a9e-f17fad200a6f.png)

**Comment by Amejia481** [comment]
@runboy93 you could install Firefox Preview Nightly for Developers. Where you will get the latest features. https://play.google.com/store/apps/details?id=org.mozilla.fenix.nightly

**Comment by runboy93** [comment]
Thanks, went for Nightly build, I like now when icon is shown.

**Comment by jawz101** [comment]
fwiw, I've blocked 3p cookies by default for years w/ only one recent hiccup.  CapitalOne Eno extension wants them enabled for some reason.

It also looks like Google is beginning to take steps and [block 3p cookies by default](https://blog.chromium.org/2019/05/improving-privacy-and-security-on-web.html)- at least in their Incognito Mode in [Canary builds](https://techdows.com/2019/09/google-tests-improved-cookie-controls-ui-for-chrome-in-incognito-mode-blocks-third-party-cookies-by-default.html).

**Comment by Kezxo** [comment]
Any news on this? Just making sure this request for a very basic feature isn't forgotten.

**Comment by jonalmeida** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813932

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
