### ISSUE TITLE
WebRTC leaks information

### ISSUE THREAD

**Issue by runboy93** [mozilla-mobile/fenix#5746]
https://browserleaks.com/webrtc

WebRTC information is leaked by Fenix, device identification is more likely when this happens :(

Could something be done to prevent this leaking?

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-13725)

**Comment by kbrosnan** [comment]
Duplicate https://github.com/mozilla-mobile/fenix/issues/15071
