### ISSUE TITLE
Enable and disable proxy

### ISSUE THREAD

**Issue by topotropic** [mozilla-mobile/fenix#5747]
## User Story
As a user, I want to enable and disable proxy so that I can browse securely.

### Acceptance Criteria
- I can tap on the proxy icon on the Fenix home screen that opens Settings/Proxy 
- On Settings/Proxy, I can enable (or disable) proxy by tapping on a switch 
- Once I enabled it, proxy is active

**Comment by kbrosnan** [comment]
We did not end up perusing this and if we do something similar in the future a new set of issues would be best.
