### ISSUE TITLE
Show that proxy is enabled

### ISSUE THREAD

**Issue by topotropic** [mozilla-mobile/fenix#5748]
## User Story
As a user, I want to know that proxy is active so that I know that I'm protected.

### Acceptance Criteria
- There's an indicator on the proxy icon on home (similar to what we have on desktop)
- There's an indicator on the lock on site level
- I get a system notification

**Comment by grigoryk** [comment]
Called it E8 because we may need to consolidate our foreground notifications. With the Secure Proxy, we'll have up to three at once - private mode, secure proxy and media.

**Comment by grigoryk** [comment]
Or - this could be a good follow-up :-)

**Comment by kbrosnan** [comment]
We did not end up perusing this and if we do something similar in the future a new set of issues would be best.
