### ISSUE TITLE
[Fenix] Copy update for Enhanced Tracking Protection

### ISSUE THREAD

**Issue by AmyYLee** [mozilla-mobile/fenix#5749]
This is a request for a copy edit to the tool tip component for ETP

New copy:
"Firefox is blocking trackers on this site when the shield is purple. Tap it to see what's blocked."

Existing copy:
"When the shield changes colors, Firefox Nightly is blocking trackers on a website. Tap it open to see what's being blocked."

Reference:
![Screenshot_20191001-130611](https://user-images.githubusercontent.com/5992746/66079628-69f06b00-e532-11e9-8351-bb8254554cad.png)

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **Nightly Build #13080607 from 4/11** using the following devices:
• Google Pixel 3a XL (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

![rsz_screenshot_20191104-165025](https://user-images.githubusercontent.com/51314259/68130484-18b60b80-ff24-11e9-95a8-f9439f8771fe.png)
