### ISSUE TITLE
Proxy prompt on public WIFI

### ISSUE THREAD

**Issue by topotropic** [mozilla-mobile/fenix#5751]
## User Story
As a user, I want to be protected when on a "public" WiFi. 

## Dependencies
Research how to determine whether a WiFi is “public”. Either open access or captive portal callback? Based on WPA/encryption strength?

### Acceptance Criteria
- I see a prompt that informs me about the privacy risks of using a public WIFI and points me to enable proxy

**Comment by kbrosnan** [comment]
We did not end up perusing this and if we do something similar in the future a new set of issues would be best.
