### ISSUE TITLE
Onboarding blurb after update

### ISSUE THREAD

**Issue by topotropic** [mozilla-mobile/fenix#5755]
## User Story
As a user, who just updated Firefox, I want to know that network protection is a new feature 

### Acceptance Criteria
- I see an onboarding blurb on Fenix home screen below the proxy icon

**Comment by grigoryk** [comment]
Depends on the card already existing (see https://github.com/mozilla-mobile/fenix/issues/5754).

**Comment by grigoryk** [comment]
Also: we'll need to expand our existing persisted state for the onboarding UI. Currently, it's "have user this onboarding? yes/no". We need it to be: "which parts of the onboarding has the user seen?".

**Comment by kbrosnan** [comment]
We did not end up perusing this and if we do something similar in the future a new set of issues would be best.
