### ISSUE TITLE
Move or remove "Scan" button from Search screen to give more space for search results

### ISSUE THREAD

**Issue by Cheap-Skate** [mozilla-mobile/fenix#5756]
(Original comment in #5567)

Now the Shortcuts button has been removed from the Search screen, could the Scan button be removed or placed elsewhere?

That way we'd all win back a bit of vertical space to fill with search results. The small number of search results is IMHO a big step back from Fennec, see eg #1161, #479.

eg
- put it where it is in Fennec, on the right hand side of the URL bar?
or
- leave it where it is, but make it disappear as soon as I start typing in the URL bar and give the vertical space back to search results (I'm unlikely to want to Scan after I have started typing???)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-13736)

**Comment by hakkikaancaliskan** [comment]
>     * put it where it is in Fennec, on the right hand side of the URL bar?
I think this is great.

**Comment by beigos** [comment]
Leave it be.
Fennec's button location makes it hard to reach it using one hand in portrait mode, it is too high.

I find myself using scan button more often, now that it is easily reachable.

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807748

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
