### ISSUE TITLE
Option to disable swipe up menu with "share" and "bookmark"

### ISSUE THREAD

**Issue by runboy93** [mozilla-mobile/fenix#5757]
Would there be an way to disable that sharing and bookmark swipe up menu on top of url bar?

It takes a little space from my eyes, and my fingers already done too many miss touches to it, and it raised. Goingfor minimal usage with no sharing or using bookmarks.

**Comment by lindongbin** [comment]
The same to me.

**Comment by cadeyrn** [comment]
The _QAB_ [will be removed](https://github.com/mozilla-mobile/fenix/issues/4281#issuecomment-535102592).

**Comment by ekager** [comment]
We have removed it. Closing
