### ISSUE TITLE
Prefer desktop version of websites!

### ISSUE THREAD

**Issue by lindongbin** [mozilla-mobile/fenix#5761]
![Screenshot_2019-10-03-09-30-12-328_com kiwibrowse](https://user-images.githubusercontent.com/3154109/66093107-72dc4d80-e5c1-11e9-9464-0b4c6e58c236.jpg)

Kiwi Browser!

**Comment by lindongbin** [comment]
https://github.com/mozilla-mobile/fenix/issues/5471
https://github.com/mozilla-mobile/fenix/issues/5725

**Comment by AaronMT** [comment]
One issue is enough.
