### ISSUE TITLE
Open downloaded file through notification

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/fenix#5763]
### User Story
As a user, I want to have quick access to opening my downloaded file right after it has finished downloading, so I can get to it right away.

### Acceptance Criteria
-The download completed notification includes a link to the downloaded file
-I can tap on this link to open the file

**Comment by sblatz** [comment]
I'm confused--this is already possible to do. Can you explain what different behavior you want here, @vesta0?

**Comment by NotWoods** [comment]
Currently the notification opens the Files app, not the file itself.

**Comment by vesta0** [comment]
Thanks @NotWoods

**Comment by vesta0** [comment]
Added the acceptance criteria to #5959 after consulting with @sblatz

**Comment by liuche** [comment]
> Currently the notification opens the Files app, not the file itself.

This might be something that we need to revisit @vesta0.  #4049 documents the decision to not handle opening downloaded files (even ones that a browser could open) for security reasons.

**Comment by NotWoods** [comment]
Note that the notification should delegate to some other app (like Google Photos for .jpg) and that this doesn't include Fenix opening files in Gecko.
