### ISSUE TITLE
Refactor Downloads for Android 11 Storage + Change download path

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/fenix#5764]
**Part of Meta: #4417**

### User Story
As a user, I want to be able to choose where my downloads are saved in my phone's storage, so I can have control and flexibility over my downloaded content. 

### Acceptance Criteria
[ ] I can see the default download location/file path
[ ] I can change the default download location

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-13743)

**Comment by Poopooracoocoo** [comment]
this is also great on devices with not much storage and SD cards

**Comment by eliserichards** [comment]
Chrome only shows this setting if you alter the flag (`chrome://flags/#enable-downloads-location-change`). This may need to live in our Advanced Settings, with some regex to guarantee that any change is valid & reversible

**Comment by Poopooracoocoo** [comment]
Google says that they want to get rid of flags after some time (but Google says a lot of things lol). I think they'll eventually turn it on by default and remove it.

**Comment by eliserichards** [comment]
There will be [major changes in Android 11](https://github.com/mozilla-mobile/fenix/pull/14121#issuecomment-683151556) to the way that they are allowing us to access storage. If we continue with this card, we will have to do a pretty big refactor on the AC side to use the new Android 11 storage, and this card would block additional work on downloads bugs. 

Confirmed with @vesta0 that this should go back into the backlog for now.

**Comment by Imerion** [comment]
This would be very useful indeed. Does it include an option to always choose where to save a file? That is something I'm really missing! Could open another issue for that otherwise.

**Comment by Poopooracoocoo** [comment]
and something Chrome's been testing out is _when_. Like waiting until there is a WiFi connection, for example.

**Comment by Amejia481** [comment]
> This would be very useful indeed. Does it include an option to always choose where to save a file? That is something I'm really missing! Could open another issue for that otherwise.

Yes, this includes the default path where files will be saved.

**Comment by Imerion** [comment]
@Amejia481 Right, but I mean choosing the desired location for every initiated download, not just having one folder where everything gets dumped.

**Comment by Amejia481** [comment]
Got it, that's a different feature!

**Comment by cadeyrn** [comment]
This is still a valid feature request (comment for bot).

**Comment by Chaz6** [comment]
This bug is almost 2 years old but it represents a major usability problem. Is there any ETA for when this will be fixed?

**Comment by Chaz6** [comment]
I will commit to a £25 bounty when this is fixed.

**Comment by SeburoSUMO** [comment]
User feedback: https://support.mozilla.org/en-US/questions/1358981

**Comment by plwt** [comment]
User feedback: https://support.mozilla.org/en-US/questions/1359728

**Comment by plwt** [comment]
User feedback: https://support.mozilla.org/en-US/questions/1365600

**Comment by plwt** [comment]
User feedback: https://support.mozilla.org/en-US/questions/1367443

**Comment by cox34** [comment]
The default "Download" folder on Android does not allow a user to use ".nomedia" files (they are automatically deleted by the system). 

Therefore, the Download folder always shows up in apps when selecting a file to upload/share (Signal, for example). Usually my download folder has a thumbnail/files I do not want to be visible when someone is selecting files to share. On the Gallery app that I use (Simple Gallery), folders can be excluded entirely (hiding uses .nomedia), so there is less of an issue. 

My point is that a feature to download in another location would be most welcome.

**Comment by Noob729** [comment]
Hello @cox34,  
As you may have noted, this issue was reported 3 years ago.  
At this point, it seems (to me) that the only reasonable solution for people who want to run FF on Android is to use FF Beta. AFAIU, that version does not disable about:config, which means several settings may be changed even when the Fenix devs don't have time to build an UI for it.

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812815

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
