### ISSUE TITLE
[Bug] talky.io - Cam & mic access denied when the mic is granted permission

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#5769]
## Steps to reproduce
1. Allow cam & mic permissions from App's system settings.
2. Go to talky.io/<a chat room name>, e.g. talky.io/me
3. Before entering the chat room, grant access to Camera.
4. Grant access to the microphone.

*Block all permissions from the system settings.
Go to talky.io/me. Observe the camera setting.

### Expected behavior
Permission requests are displayed and the camera and mic can be turned on.
### Actual behavior
After step 3, the access is denied for both, but the camera notification indicates that it's still on.

When the app's permission are blocked from system settings, talky.io sees the camera as blocked and won't ask for permission anymore.

### Device information

* Android device: Samsung Galaxy Note 8 (Android 9), Sony Xperia Z5 Premium (Android 7.1.1)
* Fenix version: RC 2.1.0rc4, Nightly 10/3

**Comment by Diana-Rus** [comment]
Hi, I can reproduce this issue with Samsung Galaxy S10 Plus (Android 9) on build Firefox Preview  Nightly 191218 (Build #13520612) with Gecko View 73.0a1-20191216095052.

Note:
The only difference is that I don't block the permissions from system settings for Firefox Preview Nightly app.

**Comment by Amejia481** [comment]
@Diana-Rus or @sv-ohorvath could you help me to clarify on step 3, where should I grant access to Camera? When I go to talky.io I don't get any permission prompt. Could you help me to clarify please?

**Comment by sv-ohorvath** [comment]
> To get any permission prompt I have to enter to the chat room and click one the buttons "Allow camera access" or "Allow camera access".

That should be it. Sorry I wasn't clear enough.
@Amejia481 here is a video: https://drive.google.com/file/d/1Spy6YXwz7bVEPIj8SNX68ZdSSaUhi7Jt/view?usp=sharing

**Comment by Amejia481** [comment]
I was able to replicated this issue on the GeckoView Sample app, I created a bug on Bugzilla for it 
https://bugzilla.mozilla.org/show_bug.cgi?id=1609959

![Screenshot_20200117-104220](https://user-images.githubusercontent.com/773158/72625277-7d271b00-3916-11ea-9832-b4dac2a78c4b.png)

**Comment by Diana-Rus** [comment]
Hi, I managed to reproduce the issue with Samsung Galaxy S8+ (Android 8) on Firefox Preview Beta 4.1.0-beta.1 (Build #20720029) GV: 75.0-20200309155231.
