### ISSUE TITLE
[BUG] Can't watch videos in portrait mode while in full screen

### ISSUE THREAD

**Issue by ReekyMarko** [mozilla-mobile/fenix#5771]
This makes it so that there is no way to watch video that was filmed vertically in portrait mode fullscreen. 

Also a related thing: The video does not rotate when in fullscreen landscape mode and the device is turned 180° with rotation locked in the OS settings. It rotates like this in most other media players on Android when rotation is locked so I think we should follow suit.

**Comment by ekager** [comment]
See https://github.com/mozilla-mobile/fenix/issues/4346 for another issue with landscape/portrait fullscreen video

**Comment by ekager** [comment]
We added requesting landscape mode for videos in https://github.com/mozilla-mobile/fenix/pull/4100

**Comment by buttercookie42** [comment]
Test page with some true vertical videos, which Fenix rotates into landscape regardless: http://www.exit109.com/~dnn/clips/VerticalVideo.html

Fennec on the other hand looked at the actual aspect ratio of the video in question to decide whether to force landscape or portrait orientation when in fullscreen mode.

> Also a related thing: The video does not rotate when in fullscreen landscape mode and the device is turned 180° with rotation locked in the OS settings.

#6652 as a dedicated issue for that.

**Comment by ekager** [comment]
Opened https://bugzilla.mozilla.org/show_bug.cgi?id=1600962

**Comment by yaomtc** [comment]
Does closing mean it's been fixed?

**Comment by boek** [comment]
@yaomtc no, sorry! I had the wrong tab open! ...now to find the issue I meant to close..

**Comment by kbrosnan** [comment]
The ability to watch videos in portrait is fixed in Firefox Preview 3.1. Auto-rotating the video to the correct orientation is not fixed. @boek it seems odd that this issue is covering both changes.

**Comment by ekager** [comment]
Opened #7602 to track the auto-rotation and I think we can close this one now
