### ISSUE TITLE
Automatically switch to PWA as long as web app is installed

### ISSUE THREAD

**Issue by NotWoods** [mozilla-mobile/fenix#5772]
### Why/User Benefit/User Problem
When we navigate to the Twitter website, if the Twitter Android app is installed we can be prompted to open in app instead. It would be nice to open in PWA if installed.

### What/Requirements
As long as a PWA is installed, automatically open the session in a PWA activity - similar to opening a custom tab in the full browser.

### Acceptance Criteria (how do I know when I’m done?)
PWAs automatically open corresponding links after installation.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-13747)

**Comment by TitanNano** [comment]
It would be great to be able to choose, though. I sometimes find myself wanting to open multiple instances if the same PWA.

**Comment by TitanNano** [comment]
Copy of the duplicate I filled recently:

> ## Why/User Benefit/User Problem
> 
> Similar to native apps, users want to view links which point to content in the scope of a standalone PWA inside standalone mode and not the browser.
> ## What/Requirements
> 
> Launch the PWA activity when the user navigates to a URL which falls into the scope of a PWA. The best solution would be if this would behave like it does with native apps. (same settings entries and main menu options).
> ## Acceptance Criteria (how do I know when I’m done?)
> There is a way for users to automatically transition a PWA into standalone mode.

**Comment by TitanNano** [comment]
@NotWoods would it be possible for me to work on this?

**Comment by NotWoods** [comment]
We're not certain if we want to implement this feature yet. 

However, it shares dependencies with some other features we do want. We want to be able to open a PWA for some scope if its installed. For example, notifications should open in the PWA. You're welcome to work on that component if you would like 😄

**Comment by TitanNano** [comment]
@NotWoods yes sure, can you point me to the right issue?

**Comment by NotWoods** [comment]
https://github.com/mozilla-mobile/android-components/issues/5667

**Comment by vesta0** [comment]
@NotWoods FYI

**Comment by liuche** [comment]
@NotWoods can you give an estimate on how much work this is? Or point to where someone might look to implement this? We should include this in release, and having some more steps would make it easier for people to pick up.

**Comment by TitanNano** [comment]
@liuche @NotWoods I'd love to work on this, if it's available.

**Comment by NotWoods** [comment]
The feature implementation should be straightforward as we already have code to switch from external apps to the main browser. However, this feature is blocked on https://github.com/mozilla-mobile/android-components/issues/3986 because being able to open a specific external app session with intents might be a security issue.

**Comment by NotWoods** [comment]
This work is now unblocked. @TitanNano are you interested in taking it on?

**Comment by TitanNano** [comment]
@NotWoods yes definitely.

**Comment by TitanNano** [comment]
@liuche @NotWoods I opened PRs for both AC and Fenix.

**Comment by NotWoods** [comment]
I think the wording of "when" in the request has caused some confusion. 

My intent was to switch just *when the PWA is first installed*.

But it could also be read as switch on *any navigation as long as the PWA is installed*.

We've talked about both possible features previously. @vesta0 can you clarify which of the two you'd like to have implemented?

**Comment by TitanNano** [comment]
@NotWoods how do we proceed with this?

**Comment by dlecan** [comment]
Any news of this?

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807437

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
