### ISSUE TITLE
[Bug] Toolbar 3 dot menu ripples clips behind toolbar counter - not the same circular effect

### ISSUE THREAD

**Issue by miladmaz12** [mozilla-mobile/fenix#5781]
## Steps to reproduce

https://streamable.com/udfv5

### Expected behavior

Ripple should have circular effect - like others

### Actual behavior

Ripple has a weird square effect

### Device information

* Android device: Android Pie, OnePlus 3T
* Fenix version: 2.1.0

**Comment by ekager** [comment]
Filed https://github.com/mozilla-mobile/android-components/issues/4639

**Comment by miladmaz12** [comment]
@ekager This issue has since been fixed on the recent build update today (10/11) on the Play Store.

Firefox Preview 2.1.0
