### ISSUE TITLE
[Meta] Web Share Target

### ISSUE THREAD

**Issue by NotWoods** [mozilla-mobile/fenix#5783]
Related Meta: #328

### Why/User Benefit/User Problem
PWAs may want to receive data from other apps, such as sharing a URL to Twitter or sharing an image to Squoosh. Web Share Target lets installed PWAs show up as entries in the Android share sheet.

### What/Requirements
PWAs that define a ShareTarget in their web app manifest will show up as entries in the Android share sheet. 

We can use Sharing Shortcuts to display entries in the share sheet dynamically. Note that this is different to Chrome's WebAPKs, since those are signed APK files that can create static share entries. We can use Direct Share (normally used to let users share to a specific person) to support Web Share Target on Android 6 and above.

- [1586158](https://bugzilla.mozilla.org/show_bug.cgi?id=1586158): Parse ShareTarget in web app manifest in Gecko
- mozilla-mobile/android-components#4636: Add ShareTarget to WebAppManifest
- mozilla-mobile/android-components#4637: Display Sharing Shortcuts for PWAs
- mozilla-mobile/android-components#4638: Support share targets in Trusted Web Activities
- [1586157](https://bugzilla.mozilla.org/show_bug.cgi?id=1586157): Support opening pages with a POST request in GeckoView

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-13754)

**Comment by cpeterso** [comment]
Web Share Target may require both GV and Gecko work.

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807436

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
