### ISSUE TITLE
[Bug] [Android 5&6] Crash when accessing Settings

### ISSUE THREAD

**Issue by softvision-miralobontiu** [mozilla-mobile/fenix#5784]
## Steps to reproduce
1. Install Firefox Preview Nightly from https://tools.taskcluster.net/index/project.mobile.fenix.v2.nightly/latest - the armeabi-v7a build.
2. Open the app and tap on the three-dot menu - Settings.

### Expected behavior
Settings should be opened.

### Actual behavior
The app crashes.

### Device information
* Android device: HTC Desire 820 (Android 6.0.1), Samsung Galaxy Tab A6 (Android 5.1.1)
* Fenix version: 10/4 Nightly

[logcat.txt](https://github.com/mozilla-mobile/fenix/files/3689577/logcat.txt)

**Comment by ekager** [comment]
@mcarare I think the only fix we need here is to stop using `DefaultBrowserPreference` within that version check and just use `Preference` instead.

**Comment by sv-ohorvath** [comment]
Verified as fixed on the latest master (10/7), on Android 5 & 6 devices.
