### ISSUE TITLE
[Bug] Sharing an article on Facebook opens a new blank page

### ISSUE THREAD

**Issue by lobontiumira** [mozilla-mobile/fenix#5786]
## Steps to reproduce
1. Go to a site with many articles (i.e. yahoo.com, cnn.com, bbc.com).
2. Open an article and share it from the Facebook icon.
3. Enter valid credentials and post it on Facebook.

### Expected behavior
After the article is posted, the user is on the site from step 1 again.

### Actual behavior
After the article is shared, the user is redirected to new a blank page.

### Device information
* Android device: Xiaomi Mi 8 Lite (Android 9), HTC Desire 820 (Android 6.0.1)
* Fenix version: 10/4 Nightly GV 71.0a1
* Not reproducible on Firefox for Android 68.1.1

![20191004_Trim](https://user-images.githubusercontent.com/40694158/66206108-c8932180-e6b7-11e9-8fd5-dc5ef3079438.gif)

[logcat.txt](https://github.com/mozilla-mobile/fenix/files/3690415/logcat.txt)

**Comment by boek** [comment]
I think this is trying to open a new tab and then facebook is trying to close the tab?

**Comment by boek** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1639091

**Comment by softvision-miralobontiu** [comment]
I'm still able to reproduce this issue with the 12/29 Nightly build with Google Pixel (Android 10).

**Comment by lobontiumira** [comment]
I was not able to reproduce this issue anymore.
Tested on the 6/29 Nightly build, with Google Pixel (Android 10), Samsung Galaxy Note 8 (Android 9), and OnePlus 5T (Android 10).
