### ISSUE TITLE
[Meta] Odd scrolling behavior in geckoview

### ISSUE THREAD

**Issue by andreicristianpetcu** [mozilla-mobile/fenix#5789]
## Steps to reproduce
open https://metrics.mozilla.com/webrender/dashboard_intel.html
wait for it to finish loading
scroll up and down
### Expected behavior
should scroll smooth
### Actual behavior
jumps up and down
https://vimeo.com/364318784

### Device information

* Android device: OnePlus 5t
* Fenix version: latest nightly

---
## List of other scrolling related issues
- [ ] https://github.com/mozilla-mobile/fenix/issues/4834

**Comment by ekager** [comment]
Could reproduce this on latest Nightly with Pixel 3 on Q

**Comment by ekager** [comment]
Could not reproduce on Chrome. 
Could not reproduce on Fennec (Although it didn't seem as "smooth" as Chrome)

**Comment by ekager** [comment]
Opened https://bugzilla.mozilla.org/show_bug.cgi?id=1586438

**Comment by andreicristianpetcu** [comment]
Might be a duplicate of https://github.com/mozilla-mobile/fenix/issues/6176

**Comment by andreicristianpetcu** [comment]
I can barely notice this in nightly. Closing.
