### ISSUE TITLE
[Breakdown Eng] Bookmarks

### ISSUE THREAD

**Issue by bbinto** [mozilla-mobile/fenix#579]
Epic: https://github.com/mozilla-mobile/fenix/issues/90
UX: https://github.com/mozilla-mobile/fenix/issues/242

**Comment by bbinto** [comment]
@colintheshots can we close this since I've created user stories: https://github.com/mozilla-mobile/fenix/issues?q=is%3Aissue+is%3Aopen+label%3AFeature%3ABookmarks

**Comment by colintheshots** [comment]
Sure.
