### ISSUE TITLE
Investigate MVI Architecture Options

### ISSUE THREAD

**Issue by colintheshots** [mozilla-mobile/fenix#58]
We should decide how we want to implement our application architecture in the new Fenix browser. We have discussed using an MVI architecture as a team, but we should investigate the best options to implement this on Android and we must decide if this is the right solution.

We should examine libraries like Mosby, Reductor, and MvRx as well as just implementing our own solution to bind changing data to the view using RxJava, LiveData, or Kotlin Coroutine Channels. There may be value in developing something in-house if no existing implementation is simple or succinct enough.

**Comment by bbinto** [comment]
dup
