### ISSUE TITLE
Full title text on image context

### ISSUE THREAD

**Issue by mcnesium** [mozilla-mobile/fenix#580]
For a new Android browser I would like to see something, that I would call xkcd-feature, since it is propably the most obvious example, why we want it: **the full title text in the context menu of an image**

| current Firefox for Android: |  while in Safari on iOS: |
|----------------------|--------------------------------|
|  ![firefox](https://user-images.githubusercontent.com/476060/53024561-8fc37680-345f-11e9-93d0-0dd044be7266.jpg) | ![safari](https://user-images.githubusercontent.com/476060/53024635-abc71800-345f-11e9-9541-e1a641a5a093.jpg) |

If this is already being worked on, feel free to ignore this.

**Comment by pocmo** [comment]
Some Fennec history:
https://bugzilla.mozilla.org/show_bug.cgi?id=768291

**Comment by buttercookie42** [comment]
In principle the same issues applies to links, too, as either the raw URL or a "title" if available (e.g. on Bugzilla) can easily be longer than the space available by default, too.

**Comment by buttercookie42** [comment]
Currently doesn't seem to work at all (#2496).

**Comment by lime124** [comment]
I think I'm getting a bit turned around, so I'm going to try to summarize some things so we can understand what actions we need to take.

1. It appears #2496 is a dup (in that alt text is missing) and we should close one of them?
2. between these two issues, it's not clear to me if this is something new or if it's not there b/c of a bug. i'm going to ping @boek who may be able to help and add qa:needed label.

Once we have that info, we can determine what (if anything) is needed from my team and if this should be slotted as a feature request or a bug fix. Removing ux label until there is a more concrete ask from us.

**Comment by kbrosnan** [comment]
Fenix shows the path to the image or the link on long press. Firefox for Android shows two rows of title text. Most other browsers will show the title text in a scrollable text box. Though this is only true on image elements. For link elements they just show the href. The more I think about this the less I want to fix the `<a href=` case. Consider `<a href="https://evil.example.com" title="https://accounts.google.com">`.

For a consistent look UX input on the text size, how many rows of text to show by default and margins of the dialog would be helpful. 

I have a testcase at https://www.kevinbrosnan.net/testcases/absurdly-long-title-text.html

According to AC the GV work is done. See https://github.com/mozilla-mobile/android-components/issues/1444

**Comment by kbrosnan** [comment]
That does bring up the question should we treat `<a href="https://evil.example.com"><img src="someimg.png" title="https://accounts.google.com">` differently?

**Comment by lime124** [comment]
@apbitner can you take a look and comment?  and consider kevin's comment above about the two cases. if this ends up requiring a bigger design task let me know.

> For a consistent look UX input on the text size, how many rows of text to show by default and margins of the dialog would be helpful.

**Comment by marcinwiacek** [comment]
my 6065 was closed, but in the same I will say one thing:

In Chrome there were three context menus:

    classical - one tab, expandable URL or text (depends on object)
    tabbed - one or more tabs, AFAIR expandable URL, not available anymore in Canary
    revamped - one tab, short non-expandable text + expandable URL

I highly suggest to go into tabbed menu + expandable text+expandable URL in link tab in header + expandable text in other tabs (for example with title for picture)

**Comment by ajayyy** [comment]
My implementation, based of Chromium on Android:

https://user-images.githubusercontent.com/12688112/121604350-5a6c3980-ca18-11eb-8b7c-0dd0bd2b859b.mp4

https://github.com/mozilla-mobile/android-components/pull/10450
