### ISSUE TITLE
[Bug] Favicons in History and Bookmarks are too small for long-sighted users

### ISSUE THREAD

**Issue by Cheap-Skate** [mozilla-mobile/fenix#5803]
The favicons in History and Bookmarks are tiny, hardly bigger than a capital letter O in the normal font. 

I'm pretty long-sighted (getting old). At a distance where I can read the URL text the favicons mostly look like coloured squares to me, can't see much detail inside them. 

Particularly a problem with the dark theme where I find the circles really "pop" and I mostly see a white circle with a small coloured square inside & some indistinct graphics.

Aesthetically as well I dislike the circles around the favicons, it seems unnecessary & isn't used elsewhere in Fenix or in other Mozilla browsers?

Could the favicons on History and Bookmarks be the same size as the favicons in my Collections?

**Comment by brampitoyo** [comment]
@Cheap-Skate Your core question is:

> Could the favicons on History and Bookmarks be the same size as the favicons in my Collections?

Let’s ping our designer @topotropic who has most recently worked on this feature.

**Comment by Dunexus** [comment]
Seems related to https://github.com/mozilla-mobile/fenix/issues/2435

**Comment by Cheap-Skate** [comment]
This issue is a duplicate of https://github.com/mozilla-mobile/fenix/issues/563#issuecomment-492404393 and the discussion around it

(I personally dislike the circles + very small favicons but it seems to have been discussed at length already)

**Comment by brampitoyo** [comment]
@Cheap-Skate Let’s close this issue, then. I hope you don’t mind?
