### ISSUE TITLE
[Bug] Tabs stop responding to navigation when Fission is enabled

### ISSUE THREAD

**Issue by emmyemi** [mozilla-mobile/fenix#5809]
## Steps to reproduce

- Enable `fission.autostart` through about:config
- Search or go to any web page
- Attempt to tap a link, go back/forward, reload the page, or enter a new address/search

### Expected behavior

- Navigation works as expected: the new page is loaded, or the current page is reloaded

### Actual behavior

- The tab doesn't respond to navigation, but otherwise still works
- Opening a new tab, or opening the link in a new tab, works around the issue

### Device information

* Android device: Pixel 3, Android 10
* Fenix version: Nightly 191004 18:00 (Build #12771805)

**Comment by boek** [comment]
This is not supported behavior in Firefox Preview yet.

**Comment by kbrosnan** [comment]
To provide a little more context. Fission work will be in Gecko. There is little work that this team can do to fix the issue you are seeing. Reporting this on [Bugzilla](https://bugzilla.mozilla.org) may be useful to the Fission team.
