### ISSUE TITLE
Decide on highlight color for suggestions

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#581]
We currently have UX for private browsing suggestions (`#ad3bff`), but none for normal mode. I'm assuming we want it to be similar to the darker blue we uses as a primary color elsewhere: `#2b20c1`

### Private Mode Example

<img width=900 src="https://user-images.githubusercontent.com/51007/51957216-9473bb00-24af-11e9-8608-9fe522bd1e57.png">

**Comment by sblatz** [comment]
Any progress on this?

**Comment by lime124** [comment]
@AmyYLee ^

**Comment by AmyYLee** [comment]
@sblatz The highlight colour should be blue 50 (#0060DF). Thanks!

**Comment by ekager** [comment]
Thanks @AmyYLee ! @sblatz is on PTO today, so I will be adding this to his PR #582

**Comment by bsurd** [comment]
Verified on:
 - 1.0.1910 (Build #10642115)

 Devices:
 - Nokia 6 (Android 7.1.1)
 - HTC Desire 820 (Android 6.0.1)
