### ISSUE TITLE
[Bug] The thumbnails from twitch.tv change when scrolling

### ISSUE THREAD

**Issue by softvision-miralobontiu** [mozilla-mobile/fenix#5812]
## Steps to reproduce
1. Go to twitch.tv and scroll the page.

### Expected behavior
The page should scroll without issues.

### Actual behavior
The page flickers and changes the thumbnails.
The same behavior when the ETP is disabled.

### Device information
* Android device: Xiaomi Mi 8 Lite (Android 9), Samsung Galaxy S6 (Android 7)
* Fenix version: Nightly 191004 (#12771804)

![20191007_Trim](https://user-images.githubusercontent.com/40694158/66296028-5871df00-e8f5-11e9-9ac5-d31033282af9.gif)

**Comment by boek** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1610948

**Comment by softvision-miralobontiu** [comment]
I was not able to reproduce the issue anymore on the latest Nightly build from 3/2 with Sony Xperia Z5 Premium (Android 7.1.1), and HTC 10 (Android 8).
I will close this.
