### ISSUE TITLE
Split the single 'open *all* links in PM' pref into 2 settings: one for 3rd party, one for shortcuts

### ISSUE THREAD

**Issue by klint** [mozilla-mobile/fenix#5815]
### Why/User Benefit/User Problem

_Note: this was originally expressed as a post-closure comment in #5341, which was not the right place. It may also be related to #5742 and #514_

First, here are 2 assumptions that make sense to me (at least ;) ):

1) Shortcuts to websites on phone's homescreen are a very powerful feature to avoid cluttering the phone with applications, either for PWA-enabled sites or for non PWA-enabled sites.
This request deals with non PWA-enabled sites only: in this case, and in order to emulate "PWA"-like behaviour, sites are often in a persistent context, login/session/cookie-wise. Therefore they **cannot** be opened in Private mode, where all initial context would be lost.
(Yet I understand that some users may want to have their shortcuts always open in Private mode, although that is not my way).

2) On the contrary, there is a need to be able to open 3rd party links in Private mode, as they usually don't need any login/session/cookie context and do not need to be recorded.
My understanding is that also includes custom tabs, does'nt it?

The problem is that there is only **one** setting that defines the mode 3rd party links and shortcurt are opened in:  "open all links in private mode".

### What/Requirements
The requirement is to split the single 'open all links in PM' preference into 2 different settings:

    Setting A: 'open all 3rd party links in PM' (which would open all links from other applications, but not Fenix shortcuts)
    Setting B: 'open all Fenix shortcuts in PM' that would apply to Fenix page shortcuts on the phone's homescreen only, obviously.

### Acceptance Criteria (how do I know when I’m done?)
When setting A is ON and setting B is OFF, a page/custom tab opened by a 3rd party will open in private mode, whereas a page shortcut will open in non-private mode, in full logged in context.
Etc
Etc

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-13777)

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807435

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
