### ISSUE TITLE
[Bug] Desktop site on/off switcher ripple is cut off

### ISSUE THREAD

**Issue by miladmaz12** [mozilla-mobile/fenix#5820]
## Steps to reproduce

https://streamable.com/bhz1i

### Device information

* Android device: OnePlus 3T, Android Pie 9
* Fenix version: 2.1.0

**Comment by kbrosnan** [comment]
Screenshot of the issue with desktop toggle button being cut off on the right side.

![Annotation 2019-10-07 093606](https://user-images.githubusercontent.com/250273/66330975-5d7b6200-e8e6-11e9-84ac-6dbcd24a1752.png)

**Comment by ekager** [comment]
Opened https://github.com/mozilla-mobile/android-components/issues/4672

**Comment by miladmaz12** [comment]
@ekager The issue has been fixed on my end with the recent build update today (10/11)

**Comment by miladmaz12** [comment]
This issue has sprung up in 2.2.0 update I received today on the Play store.
