### ISSUE TITLE
Hide http(s):// from the address bar

### ISSUE THREAD

**Issue by Lululalu** [mozilla-mobile/fenix#5821]
### Why/User Benefit/User Problem
Currently https:// takes almost half of the space available to show the actual website address and Fenix already has a secure connection icon.

![20191007_134706](https://user-images.githubusercontent.com/32398857/66331455-f6bb7000-e908-11e9-891e-9a2fbd681a71.jpg)

### What/Requirements
No more https:// on the address bar

### Acceptance Criteria (how do I know when I’m done?)

**Comment by A6GibKm** [comment]
I would argue that the lock should be hidden in https and a crossed red lock should be displayed for http connections.

**Comment by s-ankur** [comment]
Hi, we already have this now
