### ISSUE TITLE
[Bug] Buttons on toolbar have weird touch ripples

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#5822]
Nearly every button on the browser toolbar has some sort of weird touch target animation. We should improve these so they look as expected.

I think the three dot menu used to work, but changed with @Amejia481's recent toolbar changes. Not sure if the rest of these can be looped into that work :)

![Button presses look weird on toolbar 2019-10-07 09_46_08](https://user-images.githubusercontent.com/4400286/66331432-63257780-e8e7-11e9-9979-ef5aa47cfb47.gif)

**Comment by ekager** [comment]
3 dot menu is tracked in #5782

**Comment by sblatz** [comment]
Closing in favor of #1648
