### ISSUE TITLE
Proxy UI telemetry

### ISSUE THREAD

**Issue by colintheshots** [mozilla-mobile/fenix#5824]
Create telemetry probes for the Secure Proxy feature in Fenix and have data review performed on them.

**Comment by colintheshots** [comment]
Here's what desktop has implemented for telemetry:
https://github.com/mozilla/secure-proxy/blob/master/docs/metrics.md

**Comment by kbrosnan** [comment]
We did not end up perusing this and if we do something similar in the future a new set of issues would be best.
