### ISSUE TITLE
Always on private browsing

### ISSUE THREAD

**Issue by SeburoSUMO** [mozilla-mobile/fenix#5828]
### Why/User Benefit/User Problem

Users like the always-on private browsing of Fx Focus

### What/Requirements

Ability to toggle private browsing on, and for it to also apply to custom tabs when Fx Preview is used to view a link from another app.

### Acceptance Criteria (how do I know when I’m done?)

Fx Preview has a "Focus mode", when having flipped a toggle setting, the browser is in Private Browsing mode until flipped back.

Request submitted further to SUMO question:

https://support.mozilla.org/en-US/questions/1269989

**Comment by NotWoods** [comment]
This is actually a feature we recently added! Look for the "Launch links in private mode" option in settings. 

I'm not sure if this is in the stable version yet. (@sblatz do you know?) If not, it'll show up soon!

**Comment by sblatz** [comment]
@SeburoSUMO Yes, you can find this feature under Settings > Set as default browser 😄
