### ISSUE TITLE
Create performance dashboard for product owners: "release criteria"/"product maturity"

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#5832]
### Why/User Benefit/User Problem
In order to ensure we're hitting our goals and remaining a competitive product, the product owner needs insights into how the app's performance is doing over time and how it may have changed in recent releases. The solution to this problem often comes in the form of a dashboard, which we should consider creating.

Note: this was a request from Eric, that Vesta supported.

### Acceptance Criteria (how do I know when I’m done?)
- Identify requirements by coordinating with Vesta and Eric
  - Note: Eric created a release criteria dashboard for desktop so we should leverage that existing solution
  - Vesta mentioned Fenix releases every 2 weeks so Vesta wondered if we should define release criteria only for major releases (every 6 weeks), in addition to the release criteria for the upcoming milestone
- Create dashboard based on requirements

**Comment by mcomella** [comment]
esmyth is working on this.

**Comment by ecsmyth** [comment]
Power and page load visualizations are blocked on [1610609](https://bugzilla.mozilla.org/show_bug.cgi?id=1610609).

**Comment by ecsmyth** [comment]
No further changes anticipated before GA. Dashboard available [here](https://sql.telemetry.mozilla.org/dashboard/performance-fenix-release-criteria).
