### ISSUE TITLE
[Bug] Launch app using page shortcut, can't open another shortcut

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#5842]
## Steps to reproduce
1. Open 2 pages. Add them to the homescreen as page shortcuts.
2. Kill Fenix.
3. Tap one of the 2 shortcuts to launch it in Fenix.
4. Tap the other shortcut. 
5. Close the tabs and try to launch the pages shortcuts again.
### Expected behavior
The webpages should load by tapping the shortcut on the screen.
### Actual behavior
If you launch the app using these shortcuts, they won't open the second time. Tapping them just shows the browser with the existing tabs.
### Device information

* Android device: Pixel (Android 9), Galaxy Tab A (android 5.1.1)
* Fenix version: Nightly 10/8

**Comment by sv-ohorvath** [comment]
Actually it also happens with links from other apps.

**Comment by BranescuMihai** [comment]
This is quite old, tried it out and it didn't reproduce. Could we please retest it and close it if it's the case?

**Comment by softvision-miralobontiu** [comment]
This is still reproducible.
Opening the pages the second time just shows the browser with the existing tabs.
Tested with HTC 10 (Android 8), on the latest Nightly build from 6/12, with GV 79.0a1-20200610130052, AS 60.0.0.
