### ISSUE TITLE
[Bug] Taps are not registered if tapping too fast

### ISSUE THREAD

**Issue by LaurentiuApahideanSV** [mozilla-mobile/fenix#5844]
## Steps to reproduce
1. Go to https://www.cosarara.me/jaume/ff.html.
2. Tap on the first box and then quickly on the second one.
### Expected behavior
The counter should increment every time a box is tapped.
### Actual behavior
If tapping is done too fast the counter does not increment
### Device information

* Android device: Pixel 3 XL (Android 9)
* Fenix version: 2.1.0 (Build #12761514) Thursday 10/3

**Comment by NotWoods** [comment]
GeckoView bug: [1586496](https://bugzilla.mozilla.org/show_bug.cgi?id=1586496)

**Comment by cpeterso** [comment]
The GV bug has been fixed in GV 72 Nightly:

https://bugzilla.mozilla.org/show_bug.cgi?id=1586496#c15
