### ISSUE TITLE
[Bug] Setting default browser app shows 2 instances of Firefox Preview Nightly

### ISSUE THREAD

**Issue by brs17** [mozilla-mobile/fenix#5845]
## Steps to reproduce
- Go to:
  Settings -> Apps & Notifications -> Advanced -> Default apps
- Select `Browser app`
- Notice that there are two instances of Firefox (Preview) Nightly

![fenix2](https://user-images.githubusercontent.com/7460774/66400427-b1e21880-e99e-11e9-8219-bb268d552cd5.png)
![fenix1](https://user-images.githubusercontent.com/7460774/66400430-b3134580-e99e-11e9-8925-e021164e88a2.png)

### Expected behavior
Only one selection for Firefox (Preview) Nightly should be available

### Actual behavior
Multiple Firefox (Preview) Nightly options are shown

### Device information
* Android device: Nexus 5x on 8.1.0
* Fenix version: Nightly 191008 06:01 (Build #12810613)

**Comment by boek** [comment]
dup of #6735
