### ISSUE TITLE
[Spike] Determine process for handling visual locale issues

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/fenix#5855]
ENG and UX will meet for an hour to discuss and determine next steps before breaking out and sizing the main issue #3355 

e.g., do we want to open an issue for every single locale-specific problem? or file a single bug? (or accept the problem)

## Acceptance Criteria
- [x] UX / Eng discuss locale issues for 1 hour (eg how to handle problems like strings too long)
- [x] Update #3355 with Acceptance Criteria for next steps

**Comment by liuche** [comment]
*Problem tl;dr: string is too long for UI and getting cut off*

### A few questions I will pass on to L10N:
- Are we sending screenshots of translated versions to the localizers (and then they can iterate if strings can be shortened)?
- Do localizers work off of the untranslated Fenix app for context?
- Does L10N have advice on ways that UX/Content/Engineering can help with this ahead of time, guidelines, etc? (e.g. is it helpful to include UI constraints in the localization notes?)

### How to file these problems?
- One issue covers a single UI piece (e.g. context menu, where all strings are too long) ~1 screenshot per issue.
- Use L10N label
- Include severity of comprehension (P1 - don't understand, P3 can reasonably be guessed)

During development, engineers should flag UX if something is already truncated in English (e.g. "Add to Home scr...") so we can file a follow-up.

**Comment by liuche** [comment]
TODO: liuche will break out the parts of #3355 into separate issues by category.

**Comment by liuche** [comment]
Broke #3355 into individual issues and filed them, so closing this now.
