### ISSUE TITLE
[Bug] Gecko used outdated cache upon pressing the back button

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#5869]
## Steps to reproduce
This happened once and I can't reproduce this reliably. Roughly:
- (maybe) Open Fenix from the device homescreen
- (the current tab is opened - I think I was on nytimes.com) click the URL bar, enter a search, hit return
- Press back

### Expected behavior
nytimes reopens the current tab with the content I just saw

### Actual behavior
nytimes reopens the current tab with even older content (i.e. the articles were from yesterday rather than today)

### Device information

* Android device: Pixel 2
* Fenix version: Nightly 191008

**Comment by agashlin** [comment]
I've been seeing this as well, mostly with Hacker News, for at least a few days of updates, but also intermittently. I tried clearing my cache but that didn't help, haven't tried anything more drastic yet.

**Comment by fbertsch** [comment]
For me, this happens 100% of the time for both [nyt](https://www.nyt.com) and [hn](https://news.ycombinator.com).

Steps are the same:
1. Open webpage
2. Click on a link which redirects (even to same TLD)
3. Press back button

Expect: Version of page I just saw
Actual: Previous cached version

I will note that I've seen versions of this happening for a _long_ time, I used to see it on Fennec. Now it's consistent though.

Android Pixel 3
Nightly 191010 06:01
GV 71.0a1-20191004094656

**Comment by ekager** [comment]
This is likely a Gecko bug and is maybe this bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1545909

**Comment by ernstp** [comment]
Is there any progress on this? Happens to me every day on sites like arstechnica.com for example.

**Comment by djc** [comment]
It's probably more useful to comment on the Gecko bug mentioned above.

**Comment by fluffyemily** [comment]
Original issue resolved, but it looks like we are still seeing echoes of this on cnn.com. Tracked as https://bugzilla.mozilla.org/show_bug.cgi?id=1630000

**Comment by fluffyemily** [comment]
Issue resolved 15th May 2020. Fix should be available in GV 78.
