### ISSUE TITLE
Settings menu theme and background in private mode

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#587]
We are using a darker theme for private mode. It's a bit jarring to see settings be so bright and the browser menu to be bright as well. We should decide on a color scheme that better matches the private mode.

Currently:

<img width=300 src=https://user-images.githubusercontent.com/4400286/53054582-a8309280-3459-11e9-9cf7-227bd18fea0a.jpg>
<img width=300 src=https://user-images.githubusercontent.com/4400286/53054583-a8309280-3459-11e9-8597-4c8546159a20.jpg>

**Comment by ekager** [comment]
When we were doing some private mode styling, we did update the settings, library, etc background to a dark blue (see below for updated coloring) but it would be great to get an official UX word on these pages. 

![screenshot_20190228-110020](https://user-images.githubusercontent.com/25442310/53591185-47cfde00-3b48-11e9-89a6-2d253feb1948.png)
![screenshot_20190228-110006](https://user-images.githubusercontent.com/25442310/53591190-4999a180-3b48-11e9-875d-3c3b50811239.png)

**Comment by vesta0** [comment]
@lime124 Do you have an official UX direction on this ticket?

**Comment by lime124** [comment]
not yet - it's on our list.

**Comment by mheubusch** [comment]
@brampitoyo Did you reach a final decision on this? If so, can you post the results here and unblock/remove the Needs UX label?

**Comment by brampitoyo** [comment]
@mheubusch @sblatz For Private Browsing settings, we have decided against theming that page, and to follow whatever theme Fenix already uses.

If Fenix uses a light theme, then Private Browsing settings should also have a light theme. Same if Fenix uses dark theme.

This is to emphasise the fact that Private Browsing is a mode that only influences a part of Fenix – PBM doesn’t turn the whole app into a private browser.

**Comment by sblatz** [comment]
After some further discussion, this actually is not that difficult to do. @vesta0 we can pull this into a sprint whenever necessary.

**Comment by AmyYLee** [comment]
To echo what Bram had mentioned above:
The logic is that private browsing theming is applied to screens that affect PBM - For example Settings shouldn’t be themed as PBM because changing items in settings applies to the app and not PBM exclusively. Search screens should be PMB theme because the search is done within PMB. If the user goes into the Library in PBM, the theming should be either light/or dark because the Library isn’t exclusive to PMB (i.e it displays all your bookmarks in the app and not just PBM).

Happy to answer any further questions.

**Comment by sblatz** [comment]
I worked on this for a couple hours today, and after some more investigation, I determined that we cannot theme the Settings page one color and the other menus in private mode something different. Amy, Bram and I are in a discussion about how to resolve this.
