### ISSUE TITLE
"Always open in private mode" cannot be toggled off in Android 6

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#5870]
Related to https://github.com/mozilla-mobile/fenix/issues/5742

Currently, we hide the "Set as default browser" settings option on devices 5/6 since we cannot send users to the default apps settings screen (it doesn't exist on those versions of android). 
Because of this, users on 5 & 6 cannot currently reach the "open links in private mode" to disable it.

@AmyYLee how should we handle this?

**Comment by AndiAJ** [comment]
Hi, I've check on the latest debug build from Master 1.0.1941 11/10 using the following devices:
• Samsung Galaxy S6 (Android 6.0.1)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)
• Samsung Galaxy Tab Active (Android 5.1.1)

✔️ Works on the Android 6 devices.
►Video
![20191011_152839](https://user-images.githubusercontent.com/51314259/66651873-d1966c80-ec3c-11e9-92a6-6d518e1194f1.gif)


❌ On the Android 5 devices the toggle doesn't get enabled, meaning that there's no possibility to check/uncheck the "Always open in private mode"  
![20191011_152439](https://user-images.githubusercontent.com/51314259/66652315-21296800-ec3e-11e9-93bd-b52487a997e1.gif)

@sblatz - I kindly ask you to review the above.
I'll remove the QA needed label until further clarifications.

**Comment by sblatz** [comment]
I have updated this ticket to just address Android 6. Since Android 5 seems to have a deeper problem as documented in #5972.
