### ISSUE TITLE
[Bug] When adding a/deleting all tabs, "Open tabs"/"Private session" text unnecessarily animates upwards

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#5872]
## Steps to reproduce
- Open a private tab
- Click tabs tray
- Click trash can to delete private tabs

### Expected behavior
Private session text stays still

### Actual behavior
Private session text animates half its height upwards. This also occurs:
- when adding the first tab.
- In normal browsing, with the "Open tabs" text

[Video of the behavior](https://drive.google.com/file/d/1sSZYfN00AMQxVFTO0dmuGfXmu4Epb1V1/view?usp=sharing)

Note: my device text is set to "Large", which might affect this

### Device information

* Android device: Pixel 2
* Fenix version: Nightly 191008

**Comment by mcarare** [comment]
related issue: https://github.com/mozilla-mobile/fenix/issues/6075

**Comment by sv-ohorvath** [comment]
Verified as fixed on Nightly 10/21.
