### ISSUE TITLE
Add On/Off indicator in Settings for Clear browsing data on exit

### ISSUE THREAD

**Issue by AmyYLee** [mozilla-mobile/fenix#5873]
Please add an On/Off indicator for Clear browsing data on exit. Thanks!

<img width="438" alt="Screen Shot 2019-10-08 at 5 00 44 PM" src="https://user-images.githubusercontent.com/5992746/66432959-3ce9ff80-e9ed-11e9-85ea-b003e8634751.png">

**Comment by AmyYLee** [comment]
@vesta0 to add to the backlog

**Comment by mcarare** [comment]
@AmyYLee Should we stick just to  an _On/Off indicator_  or should we consider _Partially on_ when not all options are selected?

**Comment by AmyYLee** [comment]
@mcarare We should stick to On/Off here since this addresses the toggle switch being On/Off and not user prefs of what is deleted when it is on.

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the **latest Nightly build #12880607 from 15/10** using the following devices:

• Google Pixel 3a (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

►Video
![20191015_103415](https://user-images.githubusercontent.com/51314259/66810387-d8bcc380-ef37-11e9-813a-576a1f1cb4cd.gif)
