### ISSUE TITLE
Remove @ObsoleteCoroutinesApi in tests

### ISSUE THREAD

**Issue by NotWoods** [mozilla-mobile/fenix#5876]
We have various roboletric tests that use `TestApplication`. [`TestApplication` used to have a `@ObsoleteCoroutinesApi` annotation](https://github.com/mozilla-mobile/fenix/pull/5810), resulting in all roboletric also needing the annotation. We can now remove it where unnecessary.

Note: Android Studio will complain if it is necessary and you remove the annotation, so it's easy to check 😄

**Comment by shldhll** [comment]
@NotWoods I would like to work on this issue.
