### ISSUE TITLE
[Bug] Not selecting the last open tab after ending private session

### ISSUE THREAD

**Issue by mikeGolf08** [mozilla-mobile/fenix#5877]
## Steps to reproduce

1. Open more than **2** tabs
2. Stay on the **second** (lower in list) tab
3. Open private session
4. Open a tab in private session
5. Click on tab overview
6. Delete open private tab by pressing **trash icon**
7. Close private session

### Expected behavior

It shows the tab overview and my last open tab is selected.

### Actual behavior

The first tab on tab overview is selected.

### Device information

* Android device: Android 9 OOS9.0.5 OnePlus 3T A3003
* Fenix version: Nightly 191008 18:01 (Build #12811817)
📦: 16.0.0, ab2555b20
🦎: 71.0a1-20191004094656

**Comment by Mugurell** [comment]
After talking with Sebastian about this it seems like we should postpone what seems like an important refactorization to after the related code is migrated to `BrowserStore`.

Until then we would need UX feedback about how should the app behave:
Other browsers (including Fennec) also seem to use the same mental model of one selected tab and when you switch to the other list you'll have to reselect a tab to mark as "active".
Should we also keep this behavior or implement a way in which normal / private tabs would always have their own "active" tab?

**Comment by AmyYLee** [comment]
@topotropic Not sure if this is still relevant since we moving tabs into the tab tray

**Comment by topotropic** [comment]
> Until then we would need UX feedback about how should the app behave:
> Other browsers (including Fennec) also seem to use the same mental model of one selected tab and when you switch to the other list you'll have to reselect a tab to mark as "active".
> Should we also keep this behavior or implement a way in which normal / private tabs would always have their own "active" tab?

There's one selected tab but the bug description of comment 0 is valid: when you close all private tabs we select the last viewed tab in non-private mode.
