### ISSUE TITLE
night mode please

### ISSUE THREAD

**Issue by zaonie** [mozilla-mobile/fenix#5879]
### Why/User Benefit/User Problem
night mode wanted, please.
### What/Requirements
when we use Firefox Fenix at night in a dark room, it hurts eyes a lot.   so we want a night mode.

I'll keep using latest Firefox Fenix. Thanks so much for creating such a fantastic APP.

**Comment by Dunexus** [comment]
You can change theme to "Dark" in the settings.

**Comment by zaonie** [comment]
no, It's not the theme. Actually, I changed the theme to Dark. But It don't change the webpage itself (browsing area).  It's the webpage (browsing area)  that hurts when you in dark room.

**Comment by Dunexus** [comment]
[WebExtensions support](https://github.com/mozilla-mobile/fenix/issues/5315) is in Q4 backlog. When this work will be done, you should be able to use addons like [Dark Reader](https://addons.mozilla.org/fr/firefox/addon/darkreader/).

**Comment by zaonie** [comment]
thanks a lot for all of this.
