### ISSUE TITLE
[Bug] unable to add Google Maps as PWA

### ISSUE THREAD

**Issue by TitanNano** [mozilla-mobile/fenix#5881]
## Steps to reproduce
1. visit https://maps.google.com
2. choose "Add to Home screen"

### Expected behavior
Google Maps will be added to the home screen in standalone mode since it has a web manifest and it works in Fennec.

### Actual behavior
Fenix adds a simple shortcut with the wrong icon which just opens a new tab.

### Device information

* Android device: Sony Xperia Z3+ 7.1.1
* Fenix version: Nightly 191009 96:01 (Build #12820612) 📦: 16.0.0.ab2555b20

**Comment by NotWoods** [comment]
In Nightly this is adding the shortcut and opening as a PWA, but using the wrong icon.

**Comment by TitanNano** [comment]
Just downloaded the latest nightly (built 3 hours ago) and I'm still not able to add it as a PWA. I'm getting the basic shortcut dialog:

![4723](https://user-images.githubusercontent.com/4500858/66739270-a5633180-ee70-11e9-95e9-430e03985fb0.jpg)


Fenix version: Nightly 191014 06:01 (Build #12870608) 📦: 16.0.0, ab2555b20

**Comment by boek** [comment]
@NotWoods, is this still an issue?

**Comment by NotWoods** [comment]
@boek Yes, I'm still able to reproduce the issue.

**Comment by TitanNano** [comment]
In the latest fenix nightly build it's now possible to add Google Maps as a PWA. The icon is still wrong, though. 
I investigated the cause of the wrong icon and it appears that the TIPPY_TOP icon for google is always chosen, no matter what.
https://github.com/mozilla-mobile/android-components/blob/b38a2d024a4b5f6a873f09049ae7a5abab65b0c4/components/browser/icons/src/main/java/mozilla/components/browser/icons/pipeline/IconResourceComparator.kt#L46-L48

This is unexpected for PWAs, as they are already only installable if they have a proper icon.

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly Build #20310607 from 1/31`** using the following devices:

• Google Pixel 3a (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

► Video
![20200131_090642](https://user-images.githubusercontent.com/51314259/73519777-a06bc300-440a-11ea-8818-b0c4ad6a7c42.gif)
