### ISSUE TITLE
Provide a way to open Fenix in non-private mode (whatever the previous mode was)

### ISSUE THREAD

**Issue by klint** [mozilla-mobile/fenix#5883]
### Why/User Benefit/User Problem

Today, Chrome, Fenix and Edge do not have any way to open the browser directly in non-private mode, even if the previous browsing was done in private mode, and to open it to the last page that was displayed in non-private mode (or the browser home page with tabs).
Yes, there is a shortcut to open a new tab in non-private mode, but that doesn't fulfill the need.

This feature would be quite helpful to provide consistency in the navigation between private and non-private mode (along with another request, #5170, which is to open the currently viewed page in the other mode).

Having that capability in Fenix could be a nice differentiator in favour of Fenix.

### What/Requirements
Provide a second shortcut almost similar to the one used to open Fenix in private mode, that would open Fenix is non-private mode, and land on the last browsed page by keeping non-private browsing history of course (or on the tabs home page if history was lost) - the latter is different from the private shortcut that opens per design on a new private tab.

### Acceptance Criteria (how do I know when I’m done?)
After opening Fenix in private mode, pressing the non-private shortcut takes the user to the last page displayed in non-private mode, by keeping non-private browsing history.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-13825)

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807551

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
