### ISSUE TITLE
[Telemetry] Adding user-specified search engines

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/fenix#5884]
#### Description & Product Manager / Data Scientist User Story
- As a product owner, I want to know if people type use feature X so I can..

I can add a custom search engine in Fenix.
I can remove a custom search engine from my list of search engines

#### What questions will you answer with this data?
How often user add or use other search engines not listed?

#### Why does Mozilla need to answer these questions?
Determine how to better integrate frequently used features within the product. 

#### What probes (suggested, if applicable)
- User adding a new custom search engine (we don't want to track the name of the search engine)
- User deleting a custom search engine
- Searches performed with a custom search engine

### Acceptance Criteria (Added by PM)
- Event pings can be queried via re:dash
- We are sending telemetry events for the actions listed in the requirements
- We have documented the telemetry
- We have asked a data steward to [review](https://github.com/mozilla/data-review/blob/master/request.md) the telemetry
- NOT an AC: Data science to create dashboard or further graphs (this will be a separate issue, this issue is only about hooking up the events described and that they can be queried in re-dash)

**Comment by AndiAJ** [comment]
Hi, I've just checked this matter on the latest **Fenix Beta 3.2.0-beta. 2 #20230233 from 01/23** using a OnePlus A3 (Android 6).

✔️User adding a new custom search engine - Ping **7f01f061-7c25-4c78-9b8c-0bfda6f13cec**

#### Searches performed with a custom search engine.
► Set Custom Search Engine as Default
✔️Baseline ping after performing a search - Ping **a1b344af-706e-4dd4-9201-f7b9a0fe8170**
✔️Baseline ping after performing a search using a suggestion - Ping **12cb6787-b924-418e-9713-b6fe6e30e7ee**

► Using the Custom Search Engine from the Shortcuts section.
✔️ Event type ping after performing a search - Ping **83198118-0d46-4b41-b47b-3c70186e92b8**
✔️ Baseline ping after performing a search - Ping  **cc597e31-0b5b-452b-a3be-6a05e4831f8f**

✔️ Event type ping after performing a search using a suggestion - Ping **c4f11088-c226-43eb-8abe-9387822b9b44**
✔️Baseline ping after performing a search using a suggestion  - Ping **a2302f58-ba53-482e-8ae1-d1bda3a66ee7**

❌ User deleting a custom search engine - **NO ping is generated**

[Logcat](https://github.com/mozilla-mobile/fenix/files/4101872/Csearch.txt)
[Glean dashboard](https://debug-ping-preview.firebaseapp.com/pings/aj-t230102)

@vesta0 & @liuche  - When performing a search (default.action or default.suggestion) using the default search engine, the event type ping doesn't contain any information about used search engine.

On the other hand, when the user uses a search engine from the shortcuts section, the engine name is displayed in the events type ping.

**Wouldn't it be better to also include the search engine name in the event type ping when a user performs a search using the default search engine?**

E.g. 
• Event type ping after performing a search with the default search engine
```
{
          "category": "events",
          "extra": {
            "source": "default.action"
          },
          "name": "performed_search",
          "timestamp": 7841
        }
```

• Event type ping after performing a search using a suggestion with the default search engine
```
  {
          "category": "events",
          "extra": {
            "source": "default.suggestion"
          },
          "name": "performed_search",
          "timestamp": 7741
        }
```

**I'll remove the QA needed label until further notice.**

**Comment by ValentinTimisica** [comment]
@AndiAJ note that this issue is tied to #7751 (which is a follow up to this telemetry task) and you should test the build generated after 7751 was merged because there I removed the "Searches performed with a custom search engine" telemetry (see explanation in all the comments from [here](https://github.com/mozilla-mobile/fenix/pull/6918#discussion_r362045048)).

So actually these 2 tasks only register events for adding and deleting a custom search engine (not for searching with it).

Regarding the deletion event not being send, it is indeed a bug and I created a new issue for it (#7881).

**Comment by AndiAJ** [comment]
Hi, based on @ValentinTimisica 's comment, I'll mark this issue **verified as fixed.**

1. The user adding a new custom search engine **work properly**
2. The user deleting a custom search engine will be tracked in #7881
