### ISSUE TITLE
Offer a quick settings tile for open in private mode

### ISSUE THREAD

**Issue by NotWoods** [mozilla-mobile/fenix#5887]
### Why/User Benefit/User Problem
Users may want to browse primarily in private mode or normal mode, but occasionally switch without the need to dig into the Settings page. An optional [quick settings tile](https://medium.com/androiddevelopers/quick-settings-tiles-e3c22daf93a8) could let users toggle if links will open in private mode or not.

### What/Requirements
<img alt="Quick Settings Tile mock" src="https://user-images.githubusercontent.com/1782266/66502133-8e3fd080-ea79-11e9-877b-2bfd7557c612.png" height="500">

The Quick Settings Tile should toggle between opening links in private mode and normal mode when tapped. The active state should reflect the current mode.

### Acceptance Criteria (how do I know when I’m done?)
- Users can add a tile for private browsing mode
- The active state reflects current mode
- Pressing and holding the tile should open Firefox Preview (I think this part is automatic)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-13827)

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807550

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
