### ISSUE TITLE
Fennec migration: Add telemetry probes to measure success/failure rate of migration

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/fenix#5888]
details tbd.

**Comment by magorlick** [comment]
@pocmo Do we have more details here on what telemetry will be implemented?  Could you keep me in the loop to help validate?

**Comment by jdragojevic** [comment]
FYI latest a-s version (3-Jan, 0.48.0) has our initial data for logins, history and bookmarks - https://github.com/mozilla/application-services/releases/tag/v0.48.0

**Comment by AndiAJ** [comment]
Related verified issue [#5114](https://github.com/mozilla-mobile/android-components/issues/5114)

**Comment by ebalazs-sv** [comment]
@pocmo Can you please give details about what telemetry probes to measure success/failure rate of migration were added in this issue, so we can verify it? Thanks!

**Comment by ebalazs-sv** [comment]
Since this was verified in #5114, I will move this to Done. Thanks!
