### ISSUE TITLE
Create an animation for Home -> Settings (or Browser -> Settings)

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#5890]
Currently we're just popping the user into settings. Both Chrome and Fennec animate the settings up from the bottom (as seen here):

![settings animation 2019-10-09 10_01_34](https://user-images.githubusercontent.com/4400286/66503271-c9db9a00-ea7b-11e9-8d23-33b960724f2b.gif)

Is it possible we could include this animation as well?

**Comment by ekager** [comment]
Tracked here https://github.com/mozilla-mobile/fenix/issues/2273
