### ISSUE TITLE
Don't hide "set as default browser" on Android 5 & 6

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#5898]
In https://github.com/mozilla-mobile/fenix/issues/382 we hid the default browser toggle on these lower versions for MVP. 

As suggested by Vesta, we should unhide this toggle and use it to link to the sumo article (which is what we did in Focus): https://support.mozilla.org/en-US/kb/how-set-firefox-preview-your-default-browser-android 

This would also deal with https://github.com/mozilla-mobile/fenix/issues/5870 as users could access that toggle.

**Comment by sblatz** [comment]
Updated behavior:

![new behavior on lower api](https://user-images.githubusercontent.com/4400286/66587956-551e6380-eb40-11e9-8acd-68e9dcd879b5.gif)

**Comment by AndiAJ** [comment]
Hi, I've check on the latest debug build from Master 1.0.1941 11/10 using the following devices:
• Samsung Galaxy S6 (Android 6.0.1)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)
• Samsung Galaxy Tab Active (Android 5.1.1)

The **"Set as default browser" section is indeed displayed** on the other hand there is **no redirecting made to the newly opened page** (sumo article).
You need to check and navigate t it from the Open tabs section. 

Similar behavior trying to "disable" the toggle.

► Enable 
![20191011_120733](https://user-images.githubusercontent.com/51314259/66641037-a141d480-ec22-11e9-98a5-acbc77d9d717.gif)

► Disable
![20191011_122306](https://user-images.githubusercontent.com/51314259/66640940-7b1c3480-ec22-11e9-9a57-2f13cdd43639.gif)

@sblatz Please review and let us know if the user should automatically redirected to the sumo article.
**Until then I'll remove the QA needed label.**

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **Nightly build #12880607 from 15/10** using the following devices:

• Samsung Galaxy S6 (Android 6.0.1)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)
• Samsung Galaxy Tab Active (Android 5.1.1)

► Enable
![20191015_104041](https://user-images.githubusercontent.com/51314259/66811164-4b7a6e80-ef39-11e9-9d19-481bc704ba15.gif)

► Disable
![20191015_104234](https://user-images.githubusercontent.com/51314259/66811272-7b297680-ef39-11e9-85e3-fadef4aa6366.gif)
