### ISSUE TITLE
Intuitive Library

### ISSUE THREAD

**Issue by mikeGolf08** [mozilla-mobile/fenix#5906]
### Why/User Benefit/User Problem

For users with many bookmarks in a lot of folders it would be a pleasure if the list is sorted alphabetically or in a custom order with clear seperations between.
It would be easier to find a specific folder for saving a new bookmark in it.

### What/Requirements

New library layout and more options for the user.

### Acceptance Criteria (how do I know when I’m done?)

* Library can be sorted alphabetically
( * Edit option for custom order in Library )
* Separators between folders
* Margin-left for subfolders in comparison to the parentfolder

**Comment by ratkiley** [comment]
The current format / display of bookmarks is completely unusable and confusing. The folder tree display is too subtle to understand / navigate. Too confusing and unusable.  Uninstalled firefox and switched to a better browser after 79.0.5 upgrade's breaking changes to the UI.

**Comment by kbrosnan** [comment]
Duplicate https://github.com/mozilla-mobile/fenix/issues/4348
