### ISSUE TITLE
Track changes to APK size over time

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#5916]
### Why/User Benefit/User Problem
If the APK grows too large, users will download the app less. We should had persistant monitoring (and later regression testing) of APK size to our performance dashboards to measure changes over time.

### Acceptance Criteria (how do I know when I’m done?)
- Performance dashboard includes changes to APK size over time
  - I wonder how this interacts with [delta-style app updates](https://android-developers.googleblog.com/2016/07/improvements-for-smaller-app-downloads.html) (i.e. what users actually download for updates rather than the actual APK size): "Chrome found that initial download size remained the same by not compressing the native library in their APK, while the APK size increased, because Google Play already performs compression for downloads. They also found that the update size decreased, as deltas are more effective with uncompressed files, and disk size decreased as you no longer need an compressed copy of the native library. However, please note, native libraries should only be uncompressed when the minimum SDK version for an APK is 23 (Marshmallow) or later. "
- Performance dashboard includes _installed size of APK_ size over time, or a follow-up is filed to add this

**Comment by mcomella** [comment]
The Google Play dashboard has this data: I wonder if we can export it so we can centralize the data within our own dashboards.

**Comment by kbrosnan** [comment]
We've done studies and the size is not a strong factor of usage when you are talking about 40 - 50 mb apks. 

If we track this what are we going to do with the gentle increase over time? I had tracked a similar metric and libxul increased by a few kb a month. Most of the other cases were fundamental changes in Gecko features such as supporting a new media codec.

**Comment by mcomella** [comment]
Nimbledroid also has this data (for download size but not installed size). We're able to export other data from ND so maybe we can export APK size too.

**Comment by mcomella** [comment]
Tracking on JIRA: https://jira.mozilla.com/browse/FXP-465
