### ISSUE TITLE
[Bug] No feedback when pressing items on the copy/patse menu

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#5917]
We should probably add a snackbar "URL copied" when a URL is copied. The other two items (paste, paste & go) both change the UI visibly so we probably don't need anything there.

Can @topotropic confirm that we should add a snackbar? 

Would probably need string confirmation from @jpfaller too. I think "URL copied" seems reasonable, but let me know what you think!

Here's a GIF of the current behavior:
![copy feedback 2019-10-09 17_47_48](https://user-images.githubusercontent.com/4400286/66530518-f06df500-eabc-11e9-8d6b-574f5338e8dc.gif)

**Comment by topotropic** [comment]
Ok, we can do that. When you long press on an image or link on a site and copy it, we show a snackbar saying "Link copied to clipboard". Can we re-use that?

**Comment by jpfaller** [comment]
If it's not too big of a deal, I think "URL copied to clipboard" is more clear, in this case.

**Comment by ekager** [comment]
Reopening for QA

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **Nightly Build #13050627 from 1/11** using the following devices:
• Google Pixel 3a XL (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

► Video
![20191101_093023](https://user-images.githubusercontent.com/51314259/68009433-9f4fbc00-fc8a-11e9-8938-bdfc7628c7d5.gif)
