### ISSUE TITLE
[Bug] Inconsistent icon spacing & icon to text spacing in URL bar

### ISSUE THREAD

**Issue by Cheap-Skate** [mozilla-mobile/fenix#5923]
Latest version has Tracking Protection shield icon and padlock icon.

(1) spacing between shield and padlock icon is larger than between tabs and 3 dot menu icon. It looks funny.

(2) spacing from padlock icon to URL text is larger than between the search favicon and the search text on the Search screen. It should be the same in both cases.

Spacings should be consistent between icons on the URL bar, and between text spacing in the normal URL bar and the Search text bar.

IMHO the narrower spacing should be used in both cases, to win back some room for the URL text.

![icon spacing 1](https://user-images.githubusercontent.com/40568887/66568450-5e6bf800-eb61-11e9-9516-e7ca05889558.png)

**Comment by Dunexus** [comment]
Related https://github.com/mozilla-mobile/fenix/issues/3727

**Comment by brampitoyo** [comment]
@Cheap-Skate Our design contains these measurements:

<img src="https://user-images.githubusercontent.com/51007/69506888-72df4500-0f95-11ea-9f6f-6e9b40dca607.png" width="360">

It does seem like the spacing between shield and padlock is indeed larger, as you noted.

Let’s make sure that we fix this according to the measurements above.

**Comment by Cheap-Skate** [comment]
Part of the problem was that I was using Dark mode. Until recently, in Dark mode the vertical divider between shield and padlock was not visible on my Galaxy S7 so the spacing looked odd. Now the vertical divider is much more visible in Dark mode and the spacing does not look so strange.

**Comment by brampitoyo** [comment]
@Cheap-Skate Thanks for confirming! Since everything now seems to look okay, I will go ahead and close this issue.
