### ISSUE TITLE
Redesign the URL bar 

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/fenix#5924]
### Why/User Benefit/User Problem
As a Fenix user, I want to be well informed when a page is secured or not.
A color should be added for `https://` - green and `http://` - red for secure and not secure connections.
Also there is a lot of space between TP icon and Secure connection button.
### What/Requirements
To redesign the URL bar.
### Acceptance Criteria (how do I know when I’m done?)
The URL bar is redesigned.

### Notes
For more details please see the attachment:
![fenixd](https://user-images.githubusercontent.com/42831109/66569682-bd873800-eb74-11e9-989a-bbb4f4d3eaf6.jpg)
 - On the first picture I tried to rearrange the TP, Secure connection and URL position making more space for the text url and I added the green color for `https://`
 - On the second picture it's the same as actual but added the red color for the `http://` insecure connection.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-13857)

**Comment by abodea** [comment]
@vesta0 note that the colors maybe are not the right ones(i'm sure there are some other better options for green and red).

**Comment by cadeyrn** [comment]
Firefox for desktop will change the green padlock to a grey one with Firefox 70. Fenix should **not** go into the opposite direction.

**Comment by AaronMT** [comment]
Why is the HTTPS protocol even needed when a secure lock is shown? There's already minimal space in the address-bar.

**Comment by Cheap-Skate** [comment]
My uninformed suggestions...

Please avoid color in the URL bar, or check with users with poor eyesight first. I am pretty long sighted now, with phone at arms length I can see white text but red is really hard. 

Check your competitors, Android Chrome & Samsung Internet hide the https and the www and just show "mozilla.org" or whatever. 

My experience with casual users is they just look for the padlock icon, they have no idea what https means. If power users want to see the alphabetti spaghetti prefix "https://www." then make it an option which is off by default?

**Comment by Cheap-Skate** [comment]
I talked to a very smart but non-geeky friend of mine, an iOS (Safari) user

- she has no idea what difference between https:// and http:// means, looking for the "s" character (http**S**) to determine site safety seemed absurd.
- she has no idea what www means and doesn't particularly want to see it
- she knows the padlock icon is very important
- she is aware that the url ending should be .com, .org etc and if it's .ru or something it might be sketchy

Just one person so poor statistics, have you guys done any research into this?

My suggestions are to remove the http[s]:// and rely on the padlock, remove the www. where it's safe to do so, and do the Fennec thing of scrolling long urls to show the .com, .org ending

That's what Chrome Android Beta seems to do:-

Chrom, short URL, padlock plus basics of the URL

<img width="442" alt="short url" src="https://user-images.githubusercontent.com/40568887/66648387-507eab80-ec23-11e9-843e-1385ad0df408.png">

Chrome, long URL, no padlock (site is not secure) and URL scrolled to show the .com ending

<img width="443" alt="long url" src="https://user-images.githubusercontent.com/40568887/66648402-56748c80-ec23-11e9-9ce3-43a74984f76c.png">

Fenix at the moment shows all the alphabetti spaghetti and virtually none of the useful bit
 
<img width="441" alt="Screenshot 2019-10-11 at 12 40 27" src="https://user-images.githubusercontent.com/40568887/66648787-56c15780-ec24-11e9-9586-69f2d629028c.png">

**Comment by Cheap-Skate** [comment]
Some of the other Android browsers (Chrome Beta, Samsung Internet, more?) seem to be adopting a two row UI as default, one row just padlock & URL, the other row of buttons home/share etc. 

Maybe Fenix needs to accept that you just can't fit everything into one row and have two rows e.g. URL bar with shield & padlock and nothing else + second row with open in app; share; reader; tabs button; 3 dot menu???

**Comment by sheikh-azharuddin** [comment]
Add the preference item to firefox android to get a green padlock icon similar to desktop version

security.secure_connection_icon_color_gray

**Comment by mohe2015** [comment]
I also agree with the other people that www., http:// and https:// should be hidden and that the url should be scrolled to the right of the top level domain if it is too long.

Also I propose to use a lock icon which is open or strike-through for an unsafe connection (if that is not already the case)

**Comment by nikunjbhatt** [comment]
I don't think one should do the same whatever others are doing just because some standards they have defined for their products. First of all, it just seems illogical and irrational to display everything in monochrome! When we had monochrome displays, we were waiting for colors, and now we have wide range of colors and we are showing elements in monochrome! Complete stupidity and non-sense.

First we started showing lock icon to show whether a site is secure or not. Then we applied red color to the lock icon when showing insecure sites, and green lock icon when showing secure sites. We taught to the not-so-tech-savvy users to look for red and green icons. And now we are not showing these icons in colors! How counter-intuitive is this! Why aren't we not using colors when we have them? How much I remember, this kind of stupidity was started by Microsoft in Visual Studio. Why developers are not understanding that people more easily recognize things in proper colors?

In the below image, the first bar is showing what Firefox already has. The second bar is for what I suggest for secure sites (HTTPS) and tracking protection enabled (green icons). And third bar is for what I suggest for insecure sites (HTTP) and tracking protection disabled (red icons).
![Screenshot_20210212-144201](https://user-images.githubusercontent.com/4369071/107756011-91bc2980-6d49-11eb-9190-cecf6d22f128.png)

However, the lock icon may be grayed or completely hidden if site is secure.

Also, I suggest to merge the shield and lock icons in single button (to allow more space for URL) and merge their popup menus too. Their popup menus have very less items and can be combined in a single menu. Or, instead of showing the options in a popup menu, they may be showed in a popup dialog.

**Comment by sheikh-azharuddin** [comment]
Another thing they can do is truncate the url to show just the domain like in yandex.. This will shorten the address bar and allow more space for add on button or any other button

**Comment by mohe2015** [comment]
> Another thing they can do is truncate the url to show just the domain name like in yandex.. This will shorten the address bar and allow more space for add on button or any other button

Please don't do this. This is the an important reason why I keep using firefox. IMHO it's super annoying to have to click to get the full url.

**Comment by nikunjbhatt** [comment]
> Another thing they can do is truncate the url to show just the domain name like in yandex.. This will shorten the address bar and allow more space for add on button or any other button

This is also counter-intuitive. Address bar should display the URL as much as possible. As titles of pages are not shown on screen, users can quickly know that on which page they are by looking at the URL.

**Comment by sheikh-azharuddin** [comment]
> > Another thing they can do is truncate the url to show just the domain name like in yandex.. This will shorten the address bar and allow more space for add on button or any other button
> 
> Please don't do this. This is the an important reason why I keep using firefox. IMHO it's super annoying to have to click to get the full url.

LOL but this is not the desktop.. After the domain name you will hardly see a word or two not full url which can be viewed by clicking lock icon.. Why waste space in showing the half url

**Comment by mohe2015** [comment]
> > > Another thing they can do is truncate the url to show just the domain name like in yandex.. This will shorten the address bar and allow more space for add on button or any other button
> > 
> > Please don't do this. This is the an important reason why I keep using firefox. IMHO it's super annoying to have to click to get the full url.
> 
> LOL but this is not the desktop.. After the domain name you will hardly see a word or two not full url which can be viewed by clicking lock icon.. Why waste space in showing the half url

But why hide it if it doesn't matter because it just gets truncated if it doesn't fit? I don't like it because it removes information for no reason and it also discourages the average user to know about such things (URIs). I think this is pretty important as such knowledge can potentially prevent phishing.

**Comment by sheikh-azharuddin** [comment]
> > > > Another thing they can do is truncate the url to show just the domain name like in yandex.. This will shorten the address bar and allow more space for add on button or any other button
> > > 
> > > 
> > > Please don't do this. This is the an important reason why I keep using firefox. IMHO it's super annoying to have to click to get the full url.
> > 
> > 
> > LOL but this is not the desktop.. After the domain name you will hardly see a word or two not full url which can be viewed by clicking lock icon.. Why waste space in showing the half url
> 
> But why hide it if it doesn't matter because it just gets truncated if it doesn't fit? I don't like it because it removes information for no reason and it also discourages the average user to know about such things (URIs). I think this is pretty important as such knowledge can potentially prevent phishing.

But by showing only the domain one can focus more clearly.. Isn't it? Plus saving the space other items can be added such as add on icon or reload button

**Comment by nikunjbhatt** [comment]
> But why hide it if it doesn't matter because it just gets truncated if it doesn't fit?

It is possible that full or most part of a URL gets visible in landscape mode.

> But by showing only the domain one can focus more clearly.. Isn't it? Plus saving the space other items can be added such as add on icon or reload button

For those who demand like you, a setting may be provided to show or hide full URL and which buttons to show in the tool bar.

**Comment by kbrosnan** [comment]
Coloring the urlbar is not something we intend to do see bz-512684 and other Firefox desktop bugs. There are other things like highlighting the domain that seem possible and have open bugs for. Not moving this over to Bugzilla.
