### ISSUE TITLE
image sharing and opening

### ISSUE THREAD

**Issue by kolAflash** [mozilla-mobile/fenix#5930]
Classic Firefox for Android provides two context menu entries regarding images, which are still missing in Fenix.

1. Long press an image on a website to open the context menu.

Then there should be options to share the image with another app.
E. g. to send the image via a messenger.
(not sharing the URL, but the actual image)

Second is an option to show only the image. (so the image without the surrounding webpage gets displayed)

Related: #5696

**Comment by NotWoods** [comment]
Part 1: Duplicate of #3621. (See also: mozilla-mobile/android-components#3648)

Part 2: We already have an option to show only the image using "Open image in new tab"
