### ISSUE TITLE
Add a visual to the Toolbar setting

### ISSUE THREAD

**Issue by apbitner** [mozilla-mobile/fenix#5931]
In order to help users clearly understand how the Toolbar setting works, we can take advantage of the open screen real estate to include a visual. 

E.g. - https://drive.google.com/file/d/1cgE0hlV6JgZiXpVRlUnXs0jqNv4J2XLe/view?usp=sharing

**Comment by lime124** [comment]
2 options - 1) flipping between static images 2) animating it

let's go with 1 for the first pass and then revisit.

**Comment by vesta0** [comment]
Changed this to a COULD based on sizing.

**Comment by mcarare** [comment]
Are there any mocks/ resources for this?

**Comment by apbitner** [comment]
@mcarare No, thank you for removing eng:ready. UX needs to re-evaluate this ticket in part because the toolbar setting is no longer on its own screen.

**Comment by AmyYLee** [comment]
@apbitner Is this issue still valid?

**Comment by apbitner** [comment]
@AmyYLee I don't think it makes sense now that this setting isn't on its own screen. I'll close this.
