### ISSUE TITLE
Use Android secure storage (for 23+, or earlier if possible) for FxA state

### ISSUE THREAD

**Issue by liuche** [mozilla-mobile/fenix#5938]
### Why/User Benefit/User Problem
As an Android 23+ user, Android provides secure storage for keys, and I want my sync key to be stored safely in this manner.

### Dependencies
- [ ] [encrypted Firefox Account Storage](https://github.com/mozilla-mobile/android-components/issues/2229) (AC) 

### What/Requirements
Use `AndroidKeyStore` to manage Sync keys.

See Lockwise [documentation](https://github.com/mozilla-lockwise/lockwise-android/blob/master/docs/architecture/sec-apis.md) and [implementation](https://github.com/mozilla-mobile/android-components/blob/master/components/lib/dataprotect/src/main/java/mozilla/components/lib/dataprotect/Keystore.kt)

### Acceptance Criteria (how do I know when I’m done?)
- [ ] Sync keys are stored securely in Android 23+ in Android secure storage.

**Comment by liuche** [comment]
Wait it actually looks like `AndroidKeyStore` is 18+! @jhugman do you know if there's anything specific to the 23+ version of the API that Lockwise is using in the LW library (that we wouldn't 
https://developer.android.com/training/articles/keystore

**Comment by liuche** [comment]
@ekager will talk to @linuxwolf about what is possible with AndroidKeyStore, and give an update and then we'll size it.

**Comment by linuxwolf** [comment]
will discuss with @ekager.

My understanding is `AndroidKeyStore` was added in API 18, but only supporting `RSA` keys; API 23 added support for symmetric keys (e..g, `AES`).

**Comment by ekager** [comment]
FYI I think this is a prerequisite for #5544 to land because once we set an encryption key for logins we would have to worry about moving users forward if we change the key which could get messy.

**Comment by liuche** [comment]
It sounds like there are 2 keys here: sync key and login encryption key. Is the login key dependent in some way on how we store the sync key?

Why can't we a) store the sync key normally until we figure what our sync key storage story is, and then b) encrypt it, and decrypt it when we pass that into AS?

**Comment by grigoryk** [comment]
This is indeed a per-requisite for securely storing logins data.

FxA state contains everything you'd need to fetch logins from a sync server. So, encrypting logins storage at rest is moot if you store FxA state in plaintext.

**Comment by grigoryk** [comment]
Secure storage support for FxA state is tracked in https://github.com/mozilla-mobile/android-components/issues/3982

**Comment by liuche** [comment]
@ekager I just talked to grisha and going to summarize here - this does **not** need to block #5544 as long as we actually get this in place before we ship (but ideally, much sooner than that!).

Our plan here is, generate a key and store it in #5544, and then encrypt it once we get this issue fixed.

**Comment by ekager** [comment]
Opened #6066 to track the similar issue for securely storing the logins db key.

AC issue here to track lowering the min API for dataprotect
https://github.com/mozilla-mobile/android-components/issues/4758

**Comment by liuche** [comment]
@ekager when you summarize the approach and discussion you had w/ @linuxwolf can you also give an update in https://bugzilla.mozilla.org/show_bug.cgi?id=1587993 ?

**Comment by liuche** [comment]
Sizing as E2 because this should primarily be done in AC.

**Comment by ekager** [comment]
This was merged in https://github.com/mozilla-mobile/android-components/pull/5053
and we can close this ticket now

**Comment by grigoryk** [comment]
Support for this merged, but we still need to flip the flag in Fenix.

**Comment by liuche** [comment]
@grigoryk i'm going to close this bc it looks like your change landed.
