### ISSUE TITLE
Galaxy S7: tap on URL bar doesn't register after task switch

### ISSUE THREAD

**Issue by Cheap-Skate** [mozilla-mobile/fenix#595]
On my Galaxy S7 / Android 8.0.0

Get Fenix showing a Web page
switch to another app using the Android task switcher
switch back to Fenix using the Android task switcher
tap the URL in the URL bar
nothing happens
I can still tap the tabs icon or the 3 dot icon, but not the URL
If I go to Fenix tabs view and then back to the web view, tapping the URL now works

The same issue occurs if I have Fenix frontmost, then lock the phone, then unlock it.

I have tried reinstalling but it makes no difference

Expected behavior:- tapping the URL bar moves me to the Search page.

The issue does _not_ occur on my Sony Xperia X Compact / Android 8.0.0 or my BQ Aquaris X5 / Android 7.1.2

I wonder if it could be something to do with the hardware home button on the Galaxy?

**Comment by colintheshots** [comment]
Are Settings and Library working on the S7?

I think we may be finding the NavController from a UI element that isn't onscreen yet.

**Comment by Cheap-Skate** [comment]
Settings & library don't work either

**Comment by colintheshots** [comment]
@Cheap-Skate I cannot reproduce this on my Samsung Galaxy S6 or S8 and I do not own an S7. If I produce a proposed fix, could you test it for us please?

**Comment by Cheap-Skate** [comment]
Yes of course, just send me the apk or ping me when it makes it into the Nightly.

**Comment by Cheap-Skate** [comment]
Fixed. Thanks!

**Comment by colintheshots** [comment]
Glad to hear it!
