### ISSUE TITLE
System Download Notification 

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/fenix#5959]
### User Story
As a user, I want to know the status of my download and have the ability to manage the download process so I can have control and visibility over my download activity.

[Mocks](https://miro.com/app/board/o9J_kw9q71A=/)
[Deck](https://docs.google.com/presentation/d/11uYWSauJcqp89yCZcPoG6HBf0vJuyAMkxkXELSg0Nfo/edit#slide=id.g635b335255_3_130)

### Acceptance Criteria

- [ ] I see that my download is in progress
- [ ] I can pause my download
- [ ] I can resume my paused download
- [ ] I can cancel my download
- [ ] I know when my download is completed
- [ ] I know when my download fails
- [ ] I can try again on a failed download
- [ ] The download completed notification includes a link to the downloaded file
- [ ] I can tap on this link to open the file 
- [ ] I can manage multiple downloads simultaneously

**Comment by Baron-Severin** [comment]
@sblatz do you know if the strings for this story have already been landed?  If not, do you have a list of what needs to go in so I can get them in before string freeze?

**Comment by softvision-miralobontiu** [comment]
I've tested with today Nightly build from Play Store 11/4 (#13080608) with Google Pixel (Android Q), and Nokia 6 (Android 7.1.1), and these are the results:
- the download progress is visible on Nokia 6, but not on Google Pixel:
![download-progress](https://user-images.githubusercontent.com/40694158/68129944-2a4ae380-ff23-11e9-91b6-53dc942ab8aa.png)

- I was able to pause my download on both devices;
- I was NOT able to resume my paused download when I downloaded an .apk file and resumed it, the download failed - please see the attached logcat from the Nokia device:
[logcat.txt](https://github.com/mozilla-mobile/fenix/files/3804526/logcat.txt)

- I was able to cancel my download on both devices;
- I know when that the download is completed, but I don't have the "Open" option:
![download completed](https://user-images.githubusercontent.com/40694158/68130736-882bfb00-ff24-11e9-8cd7-42028f088b4d.png)


- I know when my download fails;
- I can try again on a failed download;
- the completed downloads notifications does NOT include a link to the downloaded file;
- I cannot tap on this link to open the file - there is no "Open" option in the notification;
- I can manage multiple downloads simultaneously.

**Comment by sblatz** [comment]
@MihaiTabara 

Thanks for testing this. A couple things:

> the completed downloads notifications does NOT include a link to the downloaded file;
I cannot tap on this link to open the file - there is no "Open" option in the notification;

We decided to forego the "open" button. I think @brampitoyo has just not updated the mocks to include this change. If you tap **anywhere** on the notification, it will open the file for you.

> I was NOT able to resume my paused download when I downloaded an .apk file and resumed it, the download failed - please see the attached logcat from the Nokia device:

Is this device specific? Were you able to pause APK's on certain websites but not others?

**Comment by softvision-miralobontiu** [comment]
@sblatz I tried on Nokia 6 (Android 7.1.1), Motorola Moto G6 (Android 8), Huawei P9 Lite (Android 7), and Google Pixel (Android Q), and all gave the same result. After I resumed the .apk download, the download failed. After tapping on "Try again", the download restarted.

**Comment by sblatz** [comment]
@softvision-miralobontiu Did this happen on multiple websites or just one? I am able to get this to work properly on Github, for example. I wonder if it's an issue with a specific website.

**Comment by sblatz** [comment]
Essentially: we know that **downloads will fail when trying to resume on some sites**. This is expected behavior, and as long as the try again button works in those cases, this ticket is complete :)

**Comment by brampitoyo** [comment]
@softvision-miralobontiu 

@sblatz is totally right:
> We decided to forego the "open" button. I think @brampitoyo has just not updated the mocks to include this change.

The mocks on the board has now been updated. Sorry about that.

**Comment by softvision-miralobontiu** [comment]
@sblatz I could reproduce only on downloading from the taskcluster page, the Reference-Browser apk.
Thanks!
