### ISSUE TITLE
List of search shortcuts, not clear that top line is default

### ISSUE THREAD

**Issue by Cheap-Skate** [mozilla-mobile/fenix#5962]
When entering search screen I'm presented with "Search With:" and a list of search shortcuts

It's not clear that the first one (Google in my case) is the default and I don't need to do anything to select it. I can just start typing.

I know there is a G icon top left but that's probably easy to miss for a new user when presented with the big list front & center and an instruction "Search with"

would it make sense to have something in the list to indicate that Google is the default? Otherwise you could end up with users thinking they need to tap Google before every search?

Suggestions:-

- Add text "(Default)" after the first line might be enough? Or have Google emboldened some way
or
- don't show Google in the list of search shortcut, only show the alternates to the currently selected search provider

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-13886)

**Comment by seydouba95** [comment]
i 'm ready to work on this bug

**Comment by seydouba95** [comment]
the add button with the plus icon, I think it's not necessary to put it because it does the same thing as when you click on SearchView(search or enter adresss)

**Comment by Cheap-Skate** [comment]
See also #5987.  Maybe there is a short term fix for the default search engine issue, to be followed long term by a better search experience?

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807747

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
