### ISSUE TITLE
Going back from opening a story on digg should go back to digg, not Firefox Home

### ISSUE THREAD

**Issue by mkaply** [mozilla-mobile/fenix#5963]
## Steps to reproduce

Go to digg.com.
Click a link on a story.
Notice that your number of tabs increased.
Click the back button.
You go back to the Fenix Home

### Expected behavior

Back should have taken you to digg.com and closed the tab that was opened for the story.

### Actual behavior

The tab was left open and you are back at the Fenix homepage

This is inconsistent with every mobile browser including Fennec.

### Device information

* Android device: Moto G6
* Fenix version: 2.1.0 (Build #12821600)

**Comment by mkaply** [comment]
When I say back button, I mean the back button on the android device. The back button in the browser is not enabled in this case.

**Comment by ekager** [comment]
See #2483 and #2629

**Comment by topotropic** [comment]
@ekager this is fixed, no?

**Comment by ekager** [comment]
Yes this is fixed! Closing
