### ISSUE TITLE
[Bug] Android Lint is not running on CI for the `app` module

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#5964]
The current CI behavior appears to be to run `lintDebug`: https://searchfox.org/mozilla-mobile/rev/2a57cc10d768832199bfd755d1e08fd9630baccc/fenix/taskcluster/ci/lint/kind.yml#55

However, the `lintDebug` task only exists in `architecture` (because there is no debug build variant in the `app` module) so running `./gradlew lintDebug` will only run that task in the architecture module.

To run Android Lint on the `app` module, I did `./gradlew app:lintgeckonightlydebug` and the build fails because an Android Lint warning is tripped. To fix this issue, we need to:
- Chooose which lint command should be representative of the app module
- Fix the current lint warnings, or suppress them
- Add this lint command to CI

### Impact
Android Lint runs various checks that optimize our apps for users, like notifying us of unused resources that increase our APK size or flags we can set to optimize our app, and to catch common bugs before we ship them to production. We _really_ should be running this.

**Comment by NotWoods** [comment]
Any PRs fixing lint errors are greatly appreciated.

**Comment by tharun208** [comment]
I want to work on this

**Comment by NotWoods** [comment]
For this issue these are the needed steps:
1. Update CI file to include app:lintgeckonightlydebug
2. Update baseline file to suppress all existing errors

I'll start breaking out follow up issues to fix the different errors.
- #6145

**Comment by tharun208** [comment]
Hi @NotWoods, I have trouble finding the ci file, Is there any README with all details or can you help me with this

**Comment by mawen7** [comment]
The ci file for lint is mentioned at the top of this issue, on github it is located at https://github.com/mozilla-mobile/fenix/blob/885e81699e0e945048c9aebe6a455aea4032ceac/taskcluster/ci/lint/kind.yml#L55.

**Comment by mawen7** [comment]
Would like to do this

**Comment by hakkikaancaliskan** [comment]
@NotWoods fixed?

**Comment by NotWoods** [comment]
Closing as fixed, thanks!
