### ISSUE TITLE
Tab groups

### ISSUE THREAD

**Issue by mikeGolf08** [mozilla-mobile/fenix#5967]
### Why/User Benefit/User Problem

I really like the idea of Collections but I've seen Chrome's Tab groups today and I think they are pretty handy.

The user would be able to quickly jump between tabs in a Collection because the present solution forces the user to open the tab view and to scroll all the way down to the specific Collection.

### What/Requirements

I got 2 ideas in mind:

1. Nearly the same look like Chrome (can be seen at the pictures)
2. Bring a **Collection button** to the "slide up menu of the awesomebar" (**preferred solution** & unique one & probably the easiest one)

### Acceptance Criteria (how do I know when I’m done?)

Number 2:

* There is an extra button besides Share, Bookmarks, Reading Mode to open the Collection the **current tab is within**
* By clicking on this button all other tabs from the Collection are displayed ontop of the awesomebar inside the "slide up menu" in an horizontally scrollable area
* By clicking on a tab the user can open it

Chrome tab groups: https://t.co/tzwHkE9CTT

![Screenshot_20191011-215232__01](https://user-images.githubusercontent.com/52482050/66681914-07a31300-ec74-11e9-8f8b-98f2c673b640.jpg)
![Screenshot_20191011-215256__01](https://user-images.githubusercontent.com/52482050/66681915-07a31300-ec74-11e9-9b14-53ae8b39eb82.jpg)
![Screenshot_20191011-215221__01](https://user-images.githubusercontent.com/52482050/66681917-083ba980-ec74-11e9-8d33-655bb0afd30f.jpg)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-13891)

**Comment by Octoton** [comment]
That would be so usefull as currently with lot of tab open is it easy to be lost

**Comment by yoasif** [comment]
I kind of ended up duplicating this request (didn't see it) in https://github.com/mozilla-mobile/fenix/issues/10372

**Comment by fallaciousreasoning** [comment]
This would be great, I'm always a little jealous of the tab groups feature on Chrome.

**Comment by dabat** [comment]
sadly, the ability to rename the groups was removed a short while ago 😢 
on the upside, enabling this in Firefox would give it a +1 over Chrome/Brave/et al 💯

**Comment by rahaaatul** [comment]
> sadly, the ability to rename the groups was removed a short while ago 😢 

You can still do it by enabling #enable-tab-groups-continuation flag.

**Comment by rahaaatul** [comment]
> sadly, the ability to rename the groups was removed a short while ago 😢 

You can still do it by enabling `#enable-tab-groups-continuation` flag.

**Comment by clampy** [comment]
Hey there!

I would like to formally show my interest in this issue, for what it's worth. I am a Chrome user, and this is honestly one feature that is stopping me from swapping to Firefox as I use them so commonly that it is a feature that I am not willing to lose in the transition.

Upon opening Firefox I learnt about collections, which I think is a fantastic way to organise a group of tabs that are "inactive". It would be nice if collections and group tabs were sort of combined, so you could "activate" a collection, which would pull it into your tab tray like a named tab group.

I typically have a bunch of groups for different things.
- Speakers that I am researching
- Reviews on guitars etc

Some of these groups naturally become inactive as I use them less, which ends up with quite a busy tab tray on Chrome. However, if tab groups could be integrated with the collections in some way, that would mean you could easily move less active tab groups back into your inactive collections (or whatever the names are) and clean up your active tab tray.

Anyway, love this feature request!

Cheers

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812760

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
