### ISSUE TITLE
Set background color of browser menu in private mode

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#597]
Currently blocked on:
- UX decision: #587
- AC: https://github.com/mozilla-mobile/android-components/pull/2136

**Comment by mheubusch** [comment]
@brampitoyo Can you also review this - once you unblock 587 can you remove the Needs UX Feedback label

**Comment by brampitoyo** [comment]
@mheubusch I’ve unblocked #587.

**Comment by bifleming** [comment]
@sblatz is this still blocked?

**Comment by vesta0** [comment]
Dup of #587
