### ISSUE TITLE
[Bug] Some In-app links 'Open with' shows duplicate options

### ISSUE THREAD

**Issue by vjba** [mozilla-mobile/fenix#5978]
## Steps to reproduce

Tap on link within an app

### Expected behavior

Link is opened in a custom tabs (as configured)

### Actual behavior

Intermittently receive an 'open with' menu that shows duplicate 'Private Firefox Preview' items. **See image at the bottom**

### Device information

* Android device: Samsung Galaxy Note 9, Android 9, latest build
* Fenix version: Nightly 191012 06:21 (Build #12850628)

![fxfenix](https://user-images.githubusercontent.com/21375278/66697348-4b256d80-ecc4-11e9-90cd-0eed1f0a1371.jpg)

**Comment by sblatz** [comment]
@vjba do you have multiple versions of Firefox Preview installed? Each version (nightly, debug, and release) will each show their own private launcher.

**Comment by vjba** [comment]
@sblatz Just the nightly version is installed on my device

**Comment by vjba** [comment]
Issue resolved in an unknown updated version
