### ISSUE TITLE
[Bug] Search shortcuts don't appear if enter Search screen from tab with active URL

### ISSUE THREAD

**Issue by Cheap-Skate** [mozilla-mobile/fenix#5979]
## Steps to reproduce
Go to a tab. Navigate to any site. Tap the URL to enter the Search screen

### Expected behavior
The list of search shortcuts should show up under the Search text box regardless of whether I enter by tapping the Search box on the Tabs tray or the URL on an individual tab.

### Actual behavior
If I enter the Search screen from a tab with an active URL, no search shortcuts are shown, I think because the URL is highlighted in the search text box. I have to delete the URL using the x button at the right of the search text box to get my search shortcuts.
 
### Device information

* Android device: Galaxy S7
* Fenix version: 11 Oct 2019

**Comment by boek** [comment]
This is working as intended. There is also a button at the bottom of the screen called shortcuts that you can tap to bring that menu up.
