### ISSUE TITLE
Apk unavailable Firefox Preview v2.2.0-rc.1

### ISSUE THREAD

**Issue by franco27** [mozilla-mobile/fenix#5980]
Hello
The APK is not available for this version. I can't download and install it. 

In other previous versions, there is an APK for my device under Android. 

I don't know. Maybe an omission or a desire not to distribute it?

**Comment by gaby2300** [comment]
Could you please provide the link?

**Comment by colintheshots** [comment]
This isn't a desired thing. It's a manual step in the process and often gets missed, especially as we have multiple people delivering releases.

**Comment by gaby2300** [comment]
Will the apk be available soon then?

**Comment by franco27** [comment]
I also went to:
https://www.apkmirror.com/apk/mozilla/

There is still no APK.

**Comment by gaby2300** [comment]
The link should look like 
https://github.com/mozilla-mobile/fenix/releases/tag/v2.1.0, but for v2.2.0-rc.1

**Comment by franco27** [comment]
@gaby2300 yes, I know about the Github links. But the APK can also be found at this address. 

Unfortunately version 2.2.0 rc1 is not downloadable from both websites.

**Comment by gaby2300** [comment]
Sometimes the apks are loaded later, try checking in a while. 
Do you have the github link, even without the apks?

**Comment by franco27** [comment]
Yes, I noticed it a day or two later. No, I didn't find the APK link for this version. Tanpis, we'll wait. Otherwise rc2 may be available with an APK

**Comment by boek** [comment]
This has been fixed!
