### ISSUE TITLE
[Bug] Autocomplete for a url sends me to google

### ISSUE THREAD

**Issue by Mossop** [mozilla-mobile/fenix#5986]
Similar to #3983 though I'm not sure if the port is relevant.

## Steps to reproduce

1. Start typing a url such that it autocompletes and shows the full url in the input box.
1. Press the go button or whatever that is called on the keyboard.

### Expected behavior

Goes to the url that was autofilled.

### Actual behavior

Goes to a google search for the url.

### Device information

* Android device: Moto G7
* Fenix version: 2.1.0 #12821601 14.0.1, 81385dd712 70.0-20190923100040

**Comment by ekager** [comment]
I think this an old regression that has now been fixed. Closing, please reopen if you're still seeing this!
