### ISSUE TITLE
Suggestion: redesign Search screen using a drawer like the main Tab page, gives room for Top Sites and access to alternate search engines after typing

### ISSUE THREAD

**Issue by Cheap-Skate** [mozilla-mobile/fenix#5987]
I’ve whinged a lot about how I dislike the Fenix search experience. I thought I might do something more constructive and sketch a suggestion for improvements, I’ve mocked up a few pics at the bottom. Maybe you'll find it useful?

My current problems with Fenix search page

- text entry bar hard to reach one handed (text bar is at top of screen)
- search shortcuts list appears when enter search screen, uses screen space which may be required for Top Sites
- search shortcut can only be selected before entering text - shortcuts get replaced by search suggestions when typing
- Scan button is a bit of an orphan
- Scan button uses a whole row of screen space for one button
- Shortcuts button was not liked by users (I don’t know why)

Suggestion
- move text entry bar to bottom (controversial I know)
- use the “drawer” metaphor as in a normal Fenix tab
- put all the extra stuff in the drawer:- scan; paste from clipboard; search shortcut icons

Advantages
- same metaphor as normal tabs:- text entry is at bottom, pull up drawer for extra stuff
- when opening a new tab or moving to the Search screen, there is plenty of empty screen space to show Top Sites - because search shortcuts are now in the drawer
- search shortcuts can be selected at any time (before or during text entry) by opening the drawer
- saves screen space because Scan button is in the drawer
- open drawer covers a History suggestion not a search suggestion, which is fine because opening the drawer means user is interested in scan, paste or alternate search engines not History

Mock up

(1) on entering the Search screen see Top Sites in thumb friendly vertical position, an empty text entry field, and the closed drawer

![Search bar 1](https://user-images.githubusercontent.com/40568887/66713289-a167de80-eda0-11e9-8d34-6729791a0648.jpg)

(2) open the drawer at any time to scan, paste or select an alternate search engine

![Search bar 2](https://user-images.githubusercontent.com/40568887/66713275-7ed5c580-eda0-11e9-81f8-1e8f099c9f59.jpg)

(3) when typing with the drawer open, it obscures a History suggestion, not a search suggestion, which is fine

![Search bar 3](https://user-images.githubusercontent.com/40568887/66713279-84331000-eda0-11e9-9259-53b046284b33.jpeg)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-13905)

**Comment by BeeeWall** [comment]
I feel like, if the text bar is at the bottom, the search suggestions probably should be as well, I just feel like it's better for them to be right by the bar.

**Comment by Cheap-Skate** [comment]
@BeeeWall I'd like that. But the question is, how do you scroll to see more History suggestions? Does Fenix become like an SMS app where the most recent/important stuff is at the bottom of the screen with older/less important stuff off the top of the screen? I think I would like that, but it might be controversial - the direction of scrolling Web page content (less important stuff off the bottom of the screen) would be opposite to the direction of scrolling menus & lists (less important stuff off the top). Hmmmm

**Comment by BeeeWall** [comment]
@Cheap-Skate I didn't think of that. Hmmm. I agree that personally that sounds fine to me, but others may disagree. This is why I don't design things lol. But with the search bar at the bottom of the screen that would make the most sense.

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807746

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
