### ISSUE TITLE
[Bug] No haptic feedback on text selection

### ISSUE THREAD

**Issue by KazaHesto** [mozilla-mobile/fenix#5988]
## Steps to reproduce
Make sure touch vibration is enabled in Android settings
Select text in url bar
Select text in webpages

### Expected behavior
Text selection in url bar and webpages both have haptic feedback

### Actual behavior
Only url text selection has haptic feedback

### Device information

* Android device: Essential PH-1 (Android 10)
* Fenix version: Nightly 191013

**Comment by KazaHesto** [comment]
Typo in title, meant haptic feedback. Also somehow posted a duplicate

**Comment by KazaHesto** [comment]
@cpeterso Sounds like the right setting, on my phone it's called "Touch vibration".

![Screenshot_20191024-001311](https://user-images.githubusercontent.com/19279387/67396373-336ab500-f5f3-11e9-965d-32ec34a968aa.png)

**Comment by cpeterso** [comment]
Removing the `needs:gv` label because snorp says haptic feedback should be the app's or A-C's responsibility. GV sends a text selection notification to the app, so it can then trigger haptic feedback if it wants.

**Comment by fluffyemily** [comment]
This should be the app's or A-C's responsibility. GV sends a text selection notification to the app, so it can then trigger haptic feedback.

**Comment by Keavon** [comment]
This is the reason I switched back to Chrome after giving a very serious attempt for a whole month to switch to Firefox on mobile. It's just too painful to type on websites without native-feeling text entry. It's subtle but truly a massive pain point that, important enough that I traded going back to Chrome a month later for Ublock Origin which I greatly enjoyed getting to use on mobile Firefox.
