### ISSUE TITLE
[Bug] Tapping on ETP from Settings closes the app

### ISSUE THREAD

**Issue by softvision-miralobontiu** [mozilla-mobile/fenix#5991]
## Steps to reproduce
1. Install the latest Nightly 10/14
2. Go to Settings - Enhanced Tracking Protection and wait 1-2 seconds.

### Expected behavior
The ETP page should be displayed, nothing else should happen.

### Actual behavior
The app closes.

### Device information
* Android device: Nexus 6P (Android 8.1), Pixel 3 (Android 9), HTC Desire 820 (Android 6.0.1)
* Fenix version: 10/14 (#12870608)

[logcat.txt](https://github.com/mozilla-mobile/fenix/files/3723600/logcat.txt)

**Comment by softvision-miralobontiu** [comment]
The same behavior when enabling/disabling "Remote debugging via USB".

**Comment by softvision-miralobontiu** [comment]
Exits also:
* when you finish or cancel the login flow and you return to main Settings menu,
* in Site permissions settings,
* in Accessibility, if you turn off the toggle,
* Delete browsing data on quit, if you turn on the toggle,
* Data collection if you turn one toggle on/off.

**Comment by ekager** [comment]
This looks like https://github.com/mozilla-mobile/fenix/issues/4650 and downgrading our library version fixes the issue.

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **Nightly build #12880607 from 15/10** using the following devices:

• Google Pixel 3a (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• Samsung Galaxy S6 (Android 6.0.1)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)
• Samsung Galaxy Tab Active (Android 5.1.1)

►Video
![20191015_102442](https://user-images.githubusercontent.com/51314259/66810055-2dac0a00-ef37-11e9-8f3e-323a5f17544a.gif)
