### ISSUE TITLE
[Bug] Tapping on ETP from Settings closes the app

### ISSUE THREAD

**Issue by softvision-miralobontiu** [mozilla-mobile/fenix#5992]
## Steps to reproduce
1. Install the latest Nightly 10/14
2. Go to Settings - Enhanced Tracking Protection and wait 1-2 seconds.

### Expected behavior
The ETP page should be displayed, nothing else should happen.

### Actual behavior
The app closes.

### Device information
* Android device: Nexus 6P (Android 8.1)
* Fenix version: 10/14 (#12870608)

[logcat.txt](https://github.com/mozilla-mobile/fenix/files/3723600/logcat.txt)

**Comment by sv-ohorvath** [comment]
Exits also:
- when you finish or cancel the login flow and you return to main Settings menu.
- in Site permissions settings
- in Accessibility, if you turn off the toggle
- Delete browsing data on quit, if you turn on the toggle
- Data collection if you turn one toggle on/off. 
etc
