### ISSUE TITLE
[Bug] Autocomplete with dynamic suggestions doesn't work

### ISSUE THREAD

**Issue by kuba-orlik** [mozilla-mobile/fenix#5998]
## Steps to reproduce

1. Open https://pkp.kuba-orlik.name/
2. Type in "Sz" in any of the text fields

### Expected behavior

Suggestions ("Szczecin", "Szamotuły" etc) injected into the DOM via JS should appear 

### Actual behavior

The suggestions are not visible

### Device information

* Android device: LG Nexus 5X
* Fenix version: 2.1.0

**Comment by makotokato** [comment]
This is https://bugzilla.mozilla.org/show_bug.cgi?id=1535985
