### ISSUE TITLE
provide easy access to profile

### ISSUE THREAD

**Issue by TitanNano** [mozilla-mobile/fenix#6002]
### Why/User Benefit/User Problem
Google is very good at making it hard for users to transfer data between two smartphones.
It would be great if Fenix would provide a way to easily access the gecko profile. This could be done via some of the following options:

- let users import and export a zip of the gecko profile
- let users store the gecko profile on the internal storage or a SD card

### What/Requirements
- users can look into their gecko profile
- users can reuse an existing gecko profile 

### Acceptance Criteria (how do I know when I’m done?)
Both requirements are implemented.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-13921)

**Comment by tukusejssirs** [comment]
I’ve just wanted to transfer my data from Firefox for Android (Fenix) from OnePlus 6T to Samsung Galaxy Note 10+ using backup made by Titanium Backup, but after data restoration, FF would crash. I tried to restore app+data and also tried to install FF from Google Play and restore data only, however, the result is the same.

I wish I could either sync _everything_ (all preferences, installed plugins, bookmarks, collections, open tabs, etc; this I would like to be the case on the desktop Firefox too) via Firefox Sync with an option in the initialisation to import them from a particular device; **OR** to be able to export the data device-independently and import them in the same or different device.

**Comment by kbrosnan** [comment]
Duplicate bz-1809963
