### ISSUE TITLE
[webcontent] Firefox preview read mode renders blank page

### ISSUE THREAD

**Issue by reinouts** [mozilla-mobile/fenix#6005]
Forwarded from bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1587720

## Site with issue and any steps to reproduce
1) Open https://www.ad.nl/rotterdam/telecomreus-swisscom-opent-it-afdeling-in-rotterdam-want-dat-is-gemakkelijker-dan-in-zwitserland~a3151da7/
2) Drag context drawer up from the bottom and select Read mode

### Expected behavior
Be able to see the Reader view of said page

### Actual behavior
I get a blank page

### Does toggling Tracking Protection fix the issue? (Press the lock icon in the toolbar while on the site to see toggle)
No.

### Can you reproduce in [Firefox for Android](https://play.google.com/store/apps/details?id=org.mozilla.firefox)?
No.

### Can you reproduce in Chrome (or other non-Mozilla browser)?

N/A

### Device information

* Android device: Sony Xperia XA2
* Fenix version: Firefox Preview 2.0.0 (build #12610151) 12.0.0, 9fecd17d3 70.0-20190909055931.

**Comment by csadilek** [comment]
Blocked on: https://github.com/mozilla-mobile/android-components/issues/2985

**Comment by csadilek** [comment]
This is fixed now as of Nightly 200506 06:01. I've verified that this page now opens in reader mode and looks the same as in Fennec.
