### ISSUE TITLE
Home page scrolls without animation to top when released without movement

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#601]
## Steps to reproduce
- Open home page
- Scroll down and keep finger on screen
- Release finger without scrolling up or down (those will gently cause the home page to scroll to the right position): this is tricky to do properly

### Expected behavior
Scroll gently moves in one direction or the other

### Actual behavior
Scroll instantly jumps to top of the screen. Here's a video (the first two times I miss the target and am unable to repro):
https://drive.google.com/file/d/1ZyGCXtLx5iRoyTLWL0Z1dR09BkgZ3PVV/view?usp=sharing

### Device information
* Android device: Pixel 2
* Fenix version: 1.0.1908

**Comment by Cheap-Skate** [comment]
I see this too on my Galaxy S7 / Android 8.0.0, as you say not easy to reproduce

**Comment by vesta0** [comment]
Fixed :)
