### ISSUE TITLE
[Bug] "Fill link from clipboard" link icon is truncated half off-screen in RTL mode

### ISSUE THREAD

**Issue by cpeterso** [mozilla-mobile/fenix#6011]
## Steps to reproduce

1. Enable "Force RTL layout direction" in Android's Developer options.
2. Copy a URL to your clipboard.
3. Open Fenix.
4. Tap "Search or enter address" bar.

### Expected behavior

The "Fill link from clipboard" link icon is should not be truncated.

### Actual behavior

The "Fill link from clipboard" link icon is truncated half off-screen.

### Device information

* Android device: Moto G5 Plus (Android 8.1)
* Fenix version: Nightly 19104 06:01 (Build #1287067) AC: 16.0.0, ab2555b20, GV: 71.0a1-21091004094656

RTL meta issue: https://github.com/mozilla-mobile/fenix/issues/5497

**Comment by cpeterso** [comment]
Screenshot:
![RTL_clipboard_screenshot](https://user-images.githubusercontent.com/629193/66777071-d77a9080-ee7c-11e9-9f45-1160487fa560.png)

**Comment by sv-ohorvath** [comment]
Verified as fixed on Nightly 10/21.
