### ISSUE TITLE
Re-add Search Shortcuts Button

### ISSUE THREAD

**Issue by brampitoyo** [mozilla-mobile/fenix#6018]
### Why/User Benefit/User Problem

In https://github.com/mozilla-mobile/fenix/issues/5567#issue-498404153, @colintheshots wrote about reasons for removing the Search Shortcuts button:

> The Shortcuts button now does nothing, since it's the default UX behavior for the search screen. It's always activated.
> 
> Some users find this annoying: https://www.reddit.com/r/firefox/comments/d7ak8s/does_anyone_know_how_can_i_disable_the_shortcuts/

I responded to the issue on https://github.com/mozilla-mobile/fenix/issues/5567#issuecomment-537318950 without thinking very much about it:

> * Let’s remove the Shortcuts button
> * Let’s add a new item under Settings → Search called “Show search shortcuts”, that allows users to turn off search shortcuts. It defaults to ON

After talking to @Verdi, I realised that my snap decision was lacking in context and foresight. **The Search Shortcuts button is useful for everyday users**, and for multiple reasons:

1. Search Shortcuts button allows users to change search engine while typing keywords
    * User types “washing ma…” and realised that they want to search with Amazon.
    * User types “chicago marath…” and realised that they want to search with Wikipedia.
    * Without the button, changing search engines will only be possible by erasing the keyword and retyping it from scratch.
    * With the button, the user can select a search engine and simply continue typing
2. Search Shortcuts button allows users to reuse part of the URL in an existing tab as a search keyword:
    * The user is currently on a Wikipedia article for Spacewalk. They want to search for “Spacewalk” using DuckDuckGo. They tap the address bar.
    * Without the button, the only way to search DuckDuckGo would be to erase the URL and retype the keyword.
    * With the button, the user can select DuckDuckGo and then erase part of the Wikipedia URL, leaving only the “Spacewalk” bit, then hit “Enter”.

For these reasons, we propose to re-add the Search Shortcuts button. And in the future, let’s consult with @Verdi on all things search-related.

### What/Requirements

Re-add the Search Shortcuts button that was removed by @sblatz on #5739.

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **Nightly Build #12960607** using a Google Pixel 3a (Android 9) phone.
