### ISSUE TITLE
After deleting a tab, scrolling causes stuttering on Fenix home page

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#602]
## Steps to reproduce
- Open Fenix
- Open two tabs
- Go to home page
- Scroll to bottom
- Click X to remove second tab
- Gently scroll up

### Expected behavior
Scroll works smoothly

### Actual behavior
Page stutters up and down. It looks like the position of the Today box is moving up and down quickly. Here's a video: https://drive.google.com/open?id=1OU5Y0XZZLXh1F9qUDnYvIqnEkDRgtnjN

### Device information
* Android device: Pixel 2
* Fenix version: 1.0.1908

**Comment by vesta0** [comment]
Fixed :)
