### ISSUE TITLE
[Bug] Redesign the share menu/dialog

### ISSUE THREAD

**Issue by giannissc** [mozilla-mobile/fenix#6023]
This a UX bug that I have encountered with firefox preview an it has a very simple solution. 

For the share dialog there are two main sections:
1. Send to device
2. Share link

I would like to request the you reorder those to:
1. Share link
2. Send to device

The reason for requesting this change is that share link takes a while to populate and if a user want to just send a link to device will have the send to device move upwards as soon as the share link is populated resulting in an erroneous touch to usually share link with Bluetooth

**Comment by NotWoods** [comment]
Related: #4528

The alternative solution described there is to make the "share link" row the same size when loading and loaded, so there's no change in height.

**Comment by giannissc** [comment]
That could also works just fine!

**Comment by NotWoods** [comment]
Since #4528 has been implemented I'm going to close this issue too :)
