### ISSUE TITLE
SandBox For FireFox Preview 

### ISSUE THREAD

**Issue by minutesinch** [mozilla-mobile/fenix#6027]
### Why/User Benefit/User Problem
some sites access user information in other or access other page while they are in other page.
### What/Requirements
isolate firefox tabs to avoid access and maybe other option idk
### Acceptance Criteria (how do I know when I’m done?)
idk!

**Comment by NotWoods** [comment]
I think [containers](https://support.mozilla.org/en-US/kb/containers) (#1481) solves this problem so I'm going to mark this issue as a duplicate for now. If you disagree, comment and I'll reopen.

**Comment by cadeyrn** [comment]
How is this different? I think containers address exactly the problem you described. If it's not what you want it could be a good idea to explain your idea in more detail.
