### ISSUE TITLE
Bookmark in custom tabs

### ISSUE THREAD

**Issue by ghost** [mozilla-mobile/fenix#6028]
### Why/User Benefit/User Problem
when click a link in other app for example email that redirect Firefox preview in page app browse and everything is ok but need a bookmark button.
### What/Requirements
just a button that bookmarks page
### Acceptance Criteria (how do I know when I’m done?)
on your email app click on a link and when redirect app to Firefox preview, click 3 dot in right and saw the bookmark app

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-13936)

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812722

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
