### ISSUE TITLE
Allow editing of site settings in custom tabs

### ISSUE THREAD

**Issue by st3fan** [mozilla-mobile/fenix#6034]
This bug was taken from the following Fennec feature request:

> https://bugzilla.mozilla.org/show_bug.cgi?id=1395573

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-13941)

**Comment by s-ankur** [comment]
Hi this can be done in fenix. Tested in latest nightly
