### ISSUE TITLE
[Bug]Enhanced tracking protection missing from the URL bar

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#6042]
## Steps to reproduce
1. Navigate to any website
2. Check the URL bar.

### Expected behavior
ETP icon is displayed in the URL bar

### Actual behavior
ETP icon isn't displayed in the URL bar

### Device information

* Android device: 
• Google Pixel (Android Q)
• OnePlus A3 (Android 6.0.1)

* Fenix version:  **2.2.0-rc.2**

### Notes:
✔️Works properly on the latest **Nightly Build #12890611 from 16/10**

► Video from **Fenix 2.2.0-rc.2**
![20191016_113344](https://user-images.githubusercontent.com/51314259/66903145-99ab7280-f00a-11e9-9593-271d0e4c2f49.gif)

► Video from **Fenix Nightly #12890611**
![20191016_114009](https://user-images.githubusercontent.com/51314259/66903240-c3fd3000-f00a-11e9-891b-54f70ebe1058.gif)

**Comment by cadeyrn** [comment]
According to https://github.com/mozilla-mobile/fenix/blob/releases/v2.2/app/src/main/java/org/mozilla/fenix/FeatureFlags.kt#L46 the icon should only be visible in nightly and debug builds.

**Comment by ekager** [comment]
Should be fixed with the next Nightly with latest AC (there have been some AC release issues so may take a day or two)

**Comment by AndiAJ** [comment]
H @ekager , I've reported this without knowing that the ETP is blocked for the moment on RC builds.
As described, it previously worked on nightly builds (only wanted to make a comparison between them)

I'll go ahead and close this issue, sorry for the confusion created. :)
