### ISSUE TITLE
Build of 2.2.0-RC2 failed with build errors

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/fenix#6044]
A lot of errors in BaseBrowserFragment. Probably a failed merge?

https://tools.taskcluster.net/groups/GUgXQ-_qTkqAloMP6mrb3A/tasks/ETZYzv-fSKe4gFkI-5SE2g/runs/0/logs/public%2Flogs%2Flive.log

**Comment by boek** [comment]
Fixed!
