### ISSUE TITLE
[Bug] Sign-in via email is broken on Android Q

### ISSUE THREAD

**Issue by softvision-miralobontiu** [mozilla-mobile/fenix#6045]
## Steps to reproduce
1. Go to Settings - Turn on Sync - Use email instead.
2. Sign-in with valid credentials.

### Expected behavior
The user can sign-in via email without issues.

### Actual behavior
The sign-in page is continuously loading, even though the user is signed in. Opening the sign-in custom tab in browser, displays the "Syncing..." snack-bar. If the sign-in page is closed, on Settings, the user can see that it is signed in.

### Device information
* Android device: Google Pixel (Android Q)
* Fenix version: 10/16 Nightly build

[logcat.txt](https://github.com/mozilla-mobile/fenix/files/3733485/logcat.txt)

![Screenshot_20191016-122100](https://user-images.githubusercontent.com/40694158/66906351-345a8000-f010-11e9-9797-74ea6125fed3.png)

**Comment by vesta0** [comment]
@softvision-miralobontiu please confirm this is still a bug.

**Comment by softvision-miralobontiu** [comment]
Hi Vesta!
No, this issue is no longer reproducible on the latest Nightly from 12/17 on google Pixel (Android Q).
I will close it.
