### ISSUE TITLE
The location bar contents should not spill into private mode or vice versa

### ISSUE THREAD

**Issue by st3fan** [mozilla-mobile/fenix#605]
Steps to reproduce:

- Switch to private mode and search for cheese
- Go back to the home screen and switch back to normal mode
- Tap the search bar

Expected:

- Location bar is empty

Actual:

- Location bar contain the cheese search that was done in private mode

The reverse is also true - the last contents of the location bar from normal mode spills over into private mode. The two browsing modes should not share any data.

**Comment by sblatz** [comment]
This was closed by 83aa3f22b78fea02366e713c12ae69614851a4b5
