### ISSUE TITLE
[Bug] select dialog reopens when restoring closed tab

### ISSUE THREAD

**Issue by staktrace** [mozilla-mobile/fenix#6051]
## Steps to reproduce
1. Go to https://atap.google.com/soli/
2. Scroll down to the end and click on the "select affiliation" dropdown
3. Dismiss the dropdown by hitting the back button
4. Go to tab switcher and swipe to close the tab
5. Hit undo to restore the tab
6. Open the tab

### Expected behavior
Page is shown without drop-down dialog

### Actual behavior
Dropdown dialog is shown on top of the page.

The bug is actually worse than this because you can trigger the dropdown on an unrelated page. My original STR involved clicking on Soli link from Hacker News, and going back to HN before closing and reopening the tab. In that scenario the dropdown from the Soli page appears on top of the reopened HN page.

### Device information

* Android device: sony xperia xz1c with Android 9
* Fenix version: Nightly 191014 18:01 (Build #12871824)
📦: 16.0.0, ab2555b20
🦎: 71.0a1-20191004094656

**Comment by staktrace** [comment]
![Screenshot_20191016-131328](https://user-images.githubusercontent.com/485789/66942305-c9607780-f016-11e9-93e9-387b81d9c80b.png)

Showing the dropdown from the Soli page on top of HN

**Comment by staktrace** [comment]
Closed by accident

**Comment by ReekyMarko** [comment]
I would like to add that this happens consistently with _any_ page

**Comment by ekager** [comment]
I think this was resolved by https://github.com/mozilla-mobile/android-components/pull/5578

**Comment by Amejia481** [comment]
Let's ask QA to double check!

**Comment by ReekyMarko** [comment]
Yeah I haven't seen this happen in a long while

**Comment by sflorean** [comment]
Verified as fixed on Nightly 4/22. Devices: Nokia 6 (Android 7.1.1) and Xiaomi Redmi Note 8T (Android 9).
