### ISSUE TITLE
[Spike] Authentication edge cases for accessing Logins

### ISSUE THREAD

**Issue by liuche** [mozilla-mobile/fenix#6055]
### Why/User Benefit/User Problem
Users might have different preferences for tradeoffs between protection vs convenience of accessing their logins. Things like biometrics might also not work, so users want to have a fallback in these situations.

### What/Requirements
This is a spike to answer the following questions:
- [ ] Define experience for lower API devices (Should we create a manual PIN? Should we not have any authentication?)
- [ ] Fallback from biometrics to backup, so users don't get locked out if biometrics fail (incl limitations on different API levels, like auto-fallback only being higher APIs)
- [ ] What if users don't want to have protection for their passwords? Do we force/suggest any experience?
- [ ] Is there a way for users to control their authentication settings? What is the default behavior?
- [ ] When existing users log into Sync, Fenix will start syncing whatever data choices they have made on other devices (they are global). For instance, if a user who syncs History and Logins signs into Sync on Fenix, on completion of sync setup, Fenix will automatically start syncing Logins and History.
- [ ] Any other edge cases?

### Acceptance Criteria (how do I know when I’m done?)
- [ ] Answer all these questions, and add P1/P2/P3 for each
- [ ] File a follow-up issue with action items

**Comment by lime124** [comment]
looping in @AmyYLee - are you able to start thinking and collaborating with @ekager  (@liuche to confirm) about these? @liuche is concerned this may require some security review so we should start that process sooner than later. 

does this impact current sprint work at all?

**Comment by AmyYLee** [comment]
1. Define experience for lower API devices (Should we create a manual PIN? Should we not have any authentication?). 

**System PIN is required to access "Saved logins" screen. If a user doesn't have a system PIN set up, we provide a warning dialogue recommending the user to do so (see UI mock).** 

Fallback from biometrics to backup, so users don't get locked out if biometrics fail (incl limitations on different API levels, like auto-fallback only being higher APIs). 

**The fallback for biometrics is PIN authentication (Emily to confirm)**

What if users don't want to have protection for their passwords? Do we force/suggest any experience?

**We are providing a warning dialogue to users that don't have a device authentication set up and are advising them to set one up in their system settings (see UI mock).**

Is there a way for users to control their authentication settings? What is the default behavior?

**Default is requiring biometrics or PIN authentication to access their logins (see UI mock).**

When existing users log into Sync, Fenix will start syncing whatever data choices they have made on other devices (they are global). For instance, if a user who syncs History and Logins signs into Sync on Fenix, on completion of sync setup, Fenix will automatically start syncing Logins and History.

**This is correct**

Any other edge cases?
Not at the moment on my part. @ekager do you see any additional potential edge cases?

**Comment by AmyYLee** [comment]
> looping in @AmyYLee - are you able to start thinking and collaborating with @ekager (@liuche to confirm) about these? @liuche is concerned this may require some security review so we should start that process sooner than later.
> 
> does this impact current sprint work at all?

@lime124 Unless there are additional edge cases that come up, I don't think so.

**Comment by liuche** [comment]
@AmyYLee sorry, I guess there wasn't a question here so let me add it:
> When existing users log into Sync, Fenix will start syncing whatever data choices they have made on other devices (they are global). For instance, if a user who syncs History and Logins signs into Sync on Fenix, on completion of sync setup, Fenix will automatically start syncing Logins and History.

Do we warn people as soon as they sign into sync that they should set a PIN? I see the mock for "when you turn on Logins" but the case outlined here isn't when they "turn on logins" but when "users log in to Sync for the first time" (using an existing account with Logins preferences).

Is the idea that before people sign into sync, we also show the same "type" of warning? We'll probably want a different string.

Use case:
1. Existing FxA user downloads Fenix, clicks onboarding for "sign in with FxA" (or does it through the QR code)
2. User goes through and completes sync setup
3. (Unbeknownst to the user, their logins are syncing because they enabled login sync on their desktop. What if they don't have a PIN set?)

My question would be, where (if at all in this case) do we tell users that they should set a PIN? Do we only show that warning if they are syncing logins? Is it okay to show the warning after their logins have already started syncing (at the end of step 2)?

**Comment by AmyYLee** [comment]
@liuche My thoughts were we warn users if they checked off syncing logins (either only syncing logins, or syncing logins plus bookmarks and/or history). I don't want a warning message to pop-up BEFORE syncing as this might create an unnecessary barrier for users to sign into sync. If they have logins selected for sync (can be if they selected it on their desktop or mobile device). We show the warning dialogue AFTER they completed the sync flow and we only show this once.

**Comment by ekager** [comment]
While implementing #6339 I looked into these APIs a bit more and think we have covered all of these cases. 
1. User has biometric
	- We prompt via system for required biometric auth
	- Can use PIN as backup
	- Impossible to have biometric without a PIN set up
2. User does not have biometric (either no hardware, or not set up)
	- We prompt via system for required PIN/password auth
3. User does not have biometric or PIN
	- Warnings appear first time viewing logins and first time if enabling syncing logins
	- Warning allows users to go set a PIN in system settings
