### ISSUE TITLE
[Secure Proxy] Ability to turn-on sync after authentication

### ISSUE THREAD

**Issue by grigoryk** [mozilla-mobile/fenix#6056]
For Secure Proxy, we'll have a way to sign-into FxA without enabling sync. This ticket tracks UI work around enabling sync once user is signed-in. E.g. some kind of a "enable sync" button in Account Settings with an explanation.

Also, this tracks changing Account Settings UI so that doesn't assume sync is enabled.

We need UX for the "sync isn't enabled" Account Settings UI.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-13960)

**Comment by grigoryk** [comment]
cc @topotropic

**Comment by AmyYLee** [comment]
@brampitoyo for follow-up

**Comment by brampitoyo** [comment]
@grigoryk When users have signed into FxA to access Secure Proxy, will Fenix be able to show the user’s avatar and email on top of Settings?

If that’s the case, then here’s how I envision a solution that’s both effective and easy to deploy:

1. Keep showing the user’s avatar and email in Settings
2. At the same time, keep showing “Turn on Sync” on top of Settings, above the user’s avatar
    - If tapped, then go to the Account Settings sub-page and check all the boxes
    - This is the primary path that I think most users will access. It’s visible, it’s very clear that they’re signed in but that sync hasn’t been turned on, and it’s actionable. One tap to turn Sync on.
3. If users manually go into the Account Settings sub-page, show the same “Turn on Sync” call to action on top of this page. It’s not elegant to show the same banner in 2 places, but it’s going to make sure that users don’t miss their synced data and think that something is wrong.
    - If tapped, then check all the boxes below, then the “Turn on Sync” call to action disappears
    - Users can also manually choose what to synchronise. When any one of the box is manually checked, then the “Turn on Sync” call to action disappears.
