### ISSUE TITLE
Secure Proxy "first time user" onboarding

### ISSUE THREAD

**Issue by grigoryk** [mozilla-mobile/fenix#6057]
## User Story
As a user who enables Secure Proxy for the first time, I want to know what Secure Proxy is and how it works etc, prior to displaying FxA auth flows (if not already signed-in), or prior enabling proxy (if already signed-in).

Similar to https://github.com/mozilla-mobile/fenix/issues/5754 but not just for the Fenix onboarding.

### Acceptance Criteria
- I see an onboarding (modal) UI when I enable Secure Proxy for the first time

**Comment by grigoryk** [comment]
cc @topotropic

**Comment by AmyYLee** [comment]
@apbitner to review

**Comment by topotropic** [comment]
@apbitner no need to look into this right now

**Comment by kbrosnan** [comment]
We did not end up perusing this and if we do something similar in the future a new set of issues would be best.
