### ISSUE TITLE
Links visited in Private Mode should not be shown as visited in normal mode

### ISSUE THREAD

**Issue by st3fan** [mozilla-mobile/fenix#606]
Steps to reproduce:

- In normal mode, go to news.ycombinator.com (site does not matter, it is easy to observe on HN)
- Open a link that you have not visited before
- Hit back to back to news.ycombinator.com
- Observe that the link you visited is now grey (visited)

- Go back to the home view and switch to private mode
- Visit news.ycombinator.com

Expected:

- The link that you visited in private mode is not rendered in grey (visited)

Actual:

- The link that you visited in private mode is rendered in grey

Asking @grigoryk if anything special needs to happen to make this work. I thought this separation of normal/private mode would happen automatically. Also maybe this is related to bug #604

**Comment by sblatz** [comment]
Closed by https://github.com/mozilla-mobile/fenix/pull/667

**Comment by sv-ohorvath** [comment]
Verified as fixed on latest build (3/6)
