### ISSUE TITLE
[webcontent] JetStream 2 - Script terminated by timeout

### ISSUE THREAD

**Issue by marcinwiacek** [mozilla-mobile/fenix#6060]
## Site with issue and any steps to reproduce
1. open https://browserbench.org/JetStream/
2. click Start Test

### Expected behavior
There is visible any progress in tests

### Actual behavior
0 tests are completed

### Does toggling Tracking Protection fix the issue? (Press the lock icon in the toolbar while on the site to see toggle)
no

### Can you reproduce in [Firefox for Android](https://play.google.com/store/apps/details?id=org.mozilla.firefox)?
not tried

### Can you reproduce in Chrome (or other non-Mozilla browser)?
Chrome Canary ends all test correctly

### Device information

* Android device: Pixel / S7
* Fenix version: 2.1.0

**Comment by marcinwiacek** [comment]
Hi @boek ,

just q.q. - one of more important benchmarks doesn't give any results, will be done something about this? This issue can mean potentially issues on other pages too.

**Comment by kbrosnan** [comment]
```
Error: Script terminated by timeout at:
visit@https://browserbench.org/JetStream/WSL/Node.js:42:13
visitCallExpression@https://browserbench.org/JetStream/WSL/Visitor.js:352:14
visitCallExpression@https://browserbench.org/JetStream/WSL/ConstexprFolder.js:34:15
visit@https://browserbench.org/JetStream/WSL/Node.js:33:37
visit@https://browserbench.org/JetStream/WSL/Node.js:43:25
visitCallExpression@https://browserbench.org/JetStream/WSL/Visitor.js:342:18
visitCallExpression@https://browserbench.org/JetStream/WSL/ConstexprFolder.js:34:15
visit@https://browserbench.org/JetStream/WSL/Node.js:33:37
visitIfStatement@https://browserbench.org/JetStream/WSL/Visitor.js:257:26
visit@https://browserbench.org/JetStream/WSL/Node.js:33:37
visitBlock@https://browserbench.org/JetStream/WSL/Visitor.js:73:23
visit@https://browserbench.org/JetStream/WSL/Node.js:33:37
visitFuncDef@https://browserbench.org/JetStream/WSL/Visitor.js:56:19
visit@https://browserbench.org/JetStream/WSL/Node.js:33:37
visitProgram@https://browserbench.org/JetStream/WSL/Visitor.js:31:23
visit@https://browserbench.org/JetStream/WSL/Node.js:33:37
foldConstexprs@https://browserbench.org/JetStream/WSL/FoldConstexprs.js:29:13
prepare</<@https://browserbench.org/JetStream/WSL/Prepare.js:42:23
buildStdlib@https://browserbench.org/JetStream/WSL/Test.js:6579:9
@https://browserbench.org/JetStream/:10:27
```

**Comment by kbrosnan** [comment]
Talked with Snorp. Looks like this fails when the slow script dialog should appear. Firefox for Android handles this. Fenix/A-C might be dropping this info from GV.

**Comment by kbrosnan** [comment]
Broken in reference browser as well.

**Comment by marcinwiacek** [comment]
OK, if you don't have window, please answer "don't stop". It can happen on other pages too.

I've opened it on Oct 17 and it would be good to see, that at least engine is not failing.

**Comment by marcinwiacek** [comment]
Just for reference and note: the shortest fix is connected with adding "GeckoResult.fromValue(SlowScriptResponse.CONTINUE)" inside onSlowScript.

Example: https://github.com/marcinwiacek/true-android-components/commit/5d0da76e838b25715738cdea7f22086db3ffe24c

**Comment by kbrosnan** [comment]
This is still valid.
