### ISSUE TITLE
[Enhanced Tracking Protection] Header copy is wrong "Standard (recommended)

### ISSUE THREAD

**Issue by AmyYLee** [mozilla-mobile/fenix#6063]
Since we are testing out "Strict" as the default the header "Standard (recommended)" doesn't make sense anymore

Please update the headers for ETP

Standard
Strict (recommended)

![Screenshot_20191016-175354](https://user-images.githubusercontent.com/5992746/66962636-8070e900-f03f-11e9-9c1c-a21033962f32.png)

**Comment by ekager** [comment]
Good catch! These will have to be updated to the new strings without `(recommended)`. See `tracking_protection_preferences.xml` to match those strings in `TrackingProtectionBlockingFragment`

**Comment by sv-ohorvath** [comment]
@ekager Checked on Nightly 10/21, now it says Strict (default), not Strict (Recommended). Is that expected?

**Comment by ekager** [comment]
Yes it should match the copy from the previous TP setting page! Closing because this is the correct behavior
