### ISSUE TITLE
Redesigning context menu to use tabs for link/image

### ISSUE THREAD

**Issue by marcinwiacek** [mozilla-mobile/fenix#6064]
### Why/User Benefit/User Problem
Current context menu on web pages (available after longer pressing link/image) is displaying menu options + URL. 

This is not very user friendly. In this menu we have many options and this is distracting.

### What/Requirements
Context menu should be splitted into tabs (see how it was done in Chrome longer time ago - https://bugs.chromium.org/p/chromium/issues/detail?id=793580#c1) 

### Acceptance Criteria (how do I know when I’m done?)
Menu is splitted into tabs.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-13967)

**Comment by NotWoods** [comment]
Split out the title feature requests into #580 and #6065. I'll edit this issue to focus on the tabs.

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1809291

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
