### ISSUE TITLE
Use Android secure storage (for 23+, or earlier if possible) for securely storing/generating encryption key for logins db

### ISSUE THREAD

**Issue by ekager** [mozilla-mobile/fenix#6066]
Related to #5938 but specifically about the logins db key, not the FxA state

Current plan is to generate a key and store it in #5544, and then encrypt it once we get this issue fixed.

**Comment by liuche** [comment]
@ekager could you size this? This is the "best case scenario" so this is something that we could start working on in the next sprint. I"ll move it to the top of the feature backlog.

**Comment by ekager** [comment]
Done as part of #6444
