### ISSUE TITLE
View installed WebExtensions

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/fenix#6069]
### User Story
As a user, I want to be able to view my installed WebExtensions, so I know which add-ons I have installed, what they are, and which version. (management UI)

### Dependencies
[A-C project board](https://github.com/orgs/mozilla-mobile/projects/44)

### Acceptance Criteria

- I can see my installed WebExtensions in Fenix
- I can see a brief description under each WebExtensions
- I can see the WebExtensions version (latest updated version)

### Design tasks

- [ ] Show recommended WebExtensions
- [ ] Install recommended WebExtensions
- [ ] View detailed information relevant to installed WebExtensions

**Comment by brampitoyo** [comment]
Added design tasks.

**Comment by brampitoyo** [comment]
Progress report:

* I’ve designed a way that recommended WebExtensions are shown
    * They’re shown in the Add-ons Manager page – everything seems to be all good here
    * Ideally, we’d like recommended WebExtensions to be shown prominently whenever they’re relevant. For example: through a CFR banner. **I need more time to design and figure out how the CFR interacts with the Add-ons Manager**.
* I’ve designed a way to install recommended WebExtensions
    * Install dialogues are shown as bottom modals similar to Site Information Panels – everything seems to be all good here
* I’ve designed various pages within the Add-ons Manager that shows detailed information about installed WebExtensions
    * Everything also seems all good here
    * Just to note that we have to get this detailed information from _somewhere_ (AMO), so that involves a little more work than hardcoding values.

**Comment by brampitoyo** [comment]
Progress report:
* We now know that all installable WebExtensions must:
    * Comply with Add-on Policies, and more importantly, pass [security review](https://extensionworkshop.com/documentation/publish/add-on-policies-2019-12/#security-vulnerabilities)
    * Be Recommended by the Add-ons Editorial team
    * This ensures that all installable add-ons on Fenix won’t compromise security or performance and have a great user experience.
* The add-on permission dialog is now displayed ahead of the download/verify step. This means a higher level of security. Users will know what an add-on will do, before downloading its file.

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly Build #20360606 from 2/5`** using the following devices:
• Google Pixel 3a XL (Android 10)
• Google Pixel 3a (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7.0.0)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

► Video
![20200205_123351](https://user-images.githubusercontent.com/51314259/73835102-86205380-4815-11ea-9224-6c5835efe079.gif)


► ✔️Recommended WebExtensions are shown in the Add-ons Manager page 
► ✔️Add-on permission dialog is displayed ahead of the download/verify step
► ✔️Download and verification process 
► ✔️Confirmation snackbar "Successfully installed uBlock Origin"
► ✔️After successful installation/verification the Add-on is moved from the "Recommended" section to the "Installed "section from the Add-ons manager
► ✔️Brief description under the WebExtension
• Rating 
• Number of users
► ✔️Tapping the "Details" button will show detailed and relevant information's about the Add-on.
• Short description
• Useful links
• Version number, last updated, rating etc.
► ✔️The installed and running add-on is displayed in the nav bar's 3dot button overlay. 

@brampitoyo - Please review and let me know if I missed something. ☺️ 
If that's the case please re-open this issue.

**Comment by brampitoyo** [comment]
@AndiAJ All looks good to me. Thank you kindly, QA!
