### ISSUE TITLE
History in the Library is shown in reverse order

### ISSUE THREAD

**Issue by st3fan** [mozilla-mobile/fenix#607]
History in the Library is shown in reverse order, with the most recent at the bottom. Our other browsers, Desktop and Mobile, render most recent history item first. Looping in UX to ask if this is intended.

Cc @lime124

**Comment by lime124** [comment]
added to ux feedback board for triage. thanks stefan!

**Comment by topotropic** [comment]
> render most recent history item first
That's what we want to have here as well. Thanks!

**Comment by vesta0** [comment]
This is fixed.
