### ISSUE TITLE
[Bug] QR pairing page freezes on Android Q on Nightly & Beta builds

### ISSUE THREAD

**Issue by softvision-miralobontiu** [mozilla-mobile/fenix#6071]
## Steps to reproduce
1. Sign-in on Desktop with a valid account.
2. On Desktop, go to firefox.com/pair - Show code.
3. On Firefox Preview Nightly go to Turn on Sync - Ready to scan.
4. Scan the QR code and approve the device on Desktop and confirm the pairing on mobile.

### Expected behavior
The user is signed in.

### Actual behavior
Confirm pairing page freezes. If this page is closed, the user can see that the pairing worked, sync starts. The user is signed in.

### Device information
* Android device: Google Pixel (Android Q)
* Fenix version: Nightly build 191017 (#12900613)

[logcat.txt](https://github.com/mozilla-mobile/fenix/files/3738080/logcat.txt)

**Comment by abodea** [comment]
I was able to reproduce this issue on the **`v2.3.0-rc2(GV 70) using Google Pixel 3a XL(Android 10).`**

**Comment by ekager** [comment]
Could we retest this on Nightly? I was just able to sign in via pairing

**Comment by softvision-miralobontiu** [comment]
Hi Emily,
It is still reproducible on the latest Nightly build 11/01 (#13050628) from Play Store.
Device: Google Pixel (Android Q)

**Comment by sv-ohorvath** [comment]
It's getting stuck on the confirm sign in page using email as well.

**Comment by softvision-miralobontiu** [comment]
Verified as fixed on the latest Nightly build from 4/22, and on Beta 4.3.0-beta.2, with Google Pixel (Android 10), and Samsung Galaxy Note 10 (Android 10).
