### ISSUE TITLE
Import/export for bookmarks

### ISSUE THREAD

**Issue by marcinwiacek** [mozilla-mobile/fenix#6074]
### Why/User Benefit/User Problem
Desktop Firefox allows for importing/exporting bookmarks, mobile version needs account - Mozilla is speaking a lot about privacy and it would be good to be able to export/import bookmarks to/from file like in desktop.

I don't know if any other Android browser has got it, but it could be killer feature.

### What/Requirements
Menu option for import/export for bookmarks to file (format like in desktop FF)

### Acceptance Criteria (how do I know when I’m done?)
Menu option for import/export for bookmarks to file (format like in desktop FF)

**Comment by yoasif** [comment]
Dupe of #417

**Comment by kbrosnan** [comment]
Closing as dupe
