### ISSUE TITLE
[Bug] "Open tabs" is moving up / down on main page

### ISSUE THREAD

**Issue by marcinwiacek** [mozilla-mobile/fenix#6075]
## Steps to reproduce
1. open Firefox without any tabs
2. open any tab
3. switch to main page
4. click "x" and close opened tab

### Expected behavior
"Open tabs" is not moving

### Actual behavior
"Open tabs" is moved up few pixels, because hamburger icon is removed from layout.

This doesn't look nice for people, who are taking care about details (and this is main page which is like business card).

### Device information

* Android device: S7/Pixel
* Fenix version: 2.1.0

**Comment by sv-ohorvath** [comment]
Verified as fixed on Nightly 10/21.
