### ISSUE TITLE
[Bug]Open tabs section flickers when opening multiple history items in new tabs

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#6079]
## Prerequisites
Have a couple history items

## Steps to reproduce
1. Select some of the listed history items
2. Tap on the 3dot button from the selection toolbar
3. Tap on "Open in new tab"
4. Check the "Open tabs section" 

### Expected behavior
Tabs are properly opened without any animation issues.

### Actual behavior
The "Open tabs" section flickers after opening the desired history items

### Device information

* Android device:  OnePlus 3A (Android 6.0.1)

* Fenix version: 
• 2.2.0-rc.2
• Nightly Build #12900612 from 17/10

### Notes

Video Normal browsing
![20191017_114158](https://user-images.githubusercontent.com/51314259/66996517-8d421b00-f0d9-11e9-94f1-695d63aa74ce.gif)

Video Private browsing
![20191017_114340](https://user-images.githubusercontent.com/51314259/66996588-ab0f8000-f0d9-11e9-9ca6-9db28c4bbef0.gif)

**Comment by boek** [comment]
With #1063 landing this isn't as big of an issue. It does present a new one though!

**Comment by darkwing** [comment]
Judging by the GIFs provided, it appears the re-renders could be triggered by title changes.  I'll investigate

**Comment by darkwing** [comment]
I don't think this is an issue any longer since we rewrote the HomeFragment for performance.  Would like QA to check it out.

**Comment by AndiAJ** [comment]
Hi @darkwing , I've re-checked this matter on the latest `Nightly Build # 20440606 from 2/13 `using the following devices:
• Google Pixel 3a XL (Android 10)
• Google Pixel 3a (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7.0)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

Seems to be **reproducible only on the OnePlus A3** phone.

► Videos from OnePlus A3 
![20200213-103355](https://user-images.githubusercontent.com/51314259/74416116-51338280-4e4d-11ea-85ff-f1ce3c42f53f.gif)

► Videos from Google Pixel 3a
![20200213-103148](https://user-images.githubusercontent.com/51314259/74416267-9061d380-4e4d-11ea-98e9-a9c38c1e135d.gif)

**I'll remove the QA needed label.**

**Comment by softvision-miralobontiu** [comment]
This is still reproducible on the 4.3.0-beta.1 build with Samsung Galaxy Tab A6 (Android 5.1.1).

**Comment by topotropic** [comment]
@softvision-miralobontiu @AndiAJ is this still an issue with the dedicated tab tray or can we close it? Thanks!

**Comment by softvision-miralobontiu** [comment]
Hi @topotropic!
I wasn't able to reproduce it on the latest Nightly build from 7/8 (#21900619) with Samsung Galaxy Tab A6 (Android 5.1.1).

**Comment by AndiAJ** [comment]
Hi @topotropic , no issues with the Tabs Tray on **`Nightly Build 200708 from 7/8`** using a OnePlus A3 (Android 6.0.1)

► Video
![20200708-122441](https://user-images.githubusercontent.com/51314259/86902264-67045580-c116-11ea-8bf3-0351de53529e.gif)
