### ISSUE TITLE
Private tabs are shown in normal mode

### ISSUE THREAD

**Issue by st3fan** [mozilla-mobile/fenix#608]
Steps to reproduce:

- Open Fenix
- Switch to Private Mode
- Search for cheesecake
- Open the *cheesecake bites* result
- Observe that the page is loaded in a private tab
- Hit the home button

Expected:

- The tab with the *cheesecake bites* page is shown there

Actual:

- No tabs are shown
- When you hit the Private Mode button to switch back to normal mode, the *cheesecake bites* tab is shown there.

🍰

**Comment by sblatz** [comment]
Closed by https://github.com/mozilla-mobile/fenix/pull/667

**Comment by sv-ohorvath** [comment]
Verified as fixed in the latest build (3/6)
