### ISSUE TITLE
Minify resources in assets to reduce APK size

### ISSUE THREAD

**Issue by marcinwiacek** [mozilla-mobile/fenix#6080]
### Why/User Benefit/User Problem
Current APK files contain various resources in assets in non-minified form - it would be convenient, that production version will have them compressed (which should help a little bit in faster rendering it and decreasing APK size).

### What/Requirements
All json, js and jsm files inside apk are minified.

### Acceptance Criteria (how do I know when I’m done?)
All json, js and jsm files inside apk are minified.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-13984)

**Comment by kbrosnan** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813115

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
