### ISSUE TITLE
Redesigned tab-switcher which is separate from home button

### ISSUE THREAD

**Issue by tonmoygoswami** [mozilla-mobile/fenix#6083]
### Why/User Benefit/User Problem
The current design leads the user to the homepage where tabs and collections are stacked top to bottom defeating the purpose of bottom accessibility. Moreover, you lose the context of your current page.

### What/Requirements
1. On tapping on the tab-switcher icon, a window will slide-up from the bottom of the awesome bar revealing the open tabs and collections as rows stacked on the top of each other (latest tabs to oldest sorted bottom to top) without the user leaving the current page.

The current page can be blurred/overlay/clear behind the slider.

![Image of mockup](https://tonmoygoswami.com/wp-content/uploads/2019/10/tab-switcher-mockup.jpg)

2. The bottom-most row will have an address field to open a new tab directly thus saving another tap. The address of the current page can be greyed out to clearly maintain the difference.

3. Collection rows will have a down-arrow icon to indicate that it has more content collapsed within it. User can tap it to reveal the tabs under each collection just like an accordion.

![Image of mockup expand](https://tonmoygoswami.com/wp-content/uploads/2019/10/tab-switcher-expand-mockup.jpg)

It will also show the number of tabs within it numerically. Each tab within a Collection can also have a close button. (not shown in my mockup above)

Users can tap on the name of the collection to edit its name.

**Comment by indramegit** [comment]
Awesome. Please implement this!

**Comment by s-ankur** [comment]
Hi, does the current tabs tray address most of these suggestions ?

**Comment by ekager** [comment]
I believe the current tabs tray is very similar to this idea. Please file new issues for other changes you'd still like to see!
