### ISSUE TITLE
Easier Collection access from the nav bar

### ISSUE THREAD

**Issue by tonmoygoswami** [mozilla-mobile/fenix#6085]
### Why/User Benefit/User Problem
Items within a collection should be easily accessible requiring the minimum effort.

### What/Requirements
If a tab within a Collection is open, give the user a quick way to move to other tabs within the Collection.

There can be two ways to achieve this. Both can be implemented together or individually.

1. An arrow-up indicator in the Nav Bar tapping which will reveal the other tabs in the current Collection. (similar behaviour as mentioned in open tabs feature request https://github.com/mozilla-mobile/fenix/issues/6083)

![Image of Collection mockup](https://tonmoygoswami.com/wp-content/uploads/2019/10/collection-swticher-mockup.jpg)

2. Swiping left/right on the webpage open to move to next/prev tab in the Collection. The left/right chevron in the mockup above is just a swipe indicator, it won’t actually be visible on screen.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-13987)

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812759

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
