### ISSUE TITLE
[Bug] Search suggestions multiply for non-default providers

### ISSUE THREAD

**Issue by BranescuMihai** [mozilla-mobile/fenix#6087]
## Steps to reproduce
Click on search bar
Have Google as default, choose Amazon or any other provider than Google from 'Search with' list
Start typing (or removing letters)

### Expected behavior
You see the suggestions from the selected provider once

### Actual behavior
Each time you type a letter, all suggestions appear multiple times (the number of suggestions increases every time)

### Device information

* Android device: Samsung S10, Android 9
* Fenix version: 17/10 dev build

[**Video link to bug reproduction**](https://drive.google.com/file/d/16xlqPmLN3aWafDDE7nzHoBDP8xrqhbFW/view)

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **Nightly Build #13110606 from 7/11** using the following devices:
• Google Pixel 3a XL (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

► Video
![20191107_111733](https://user-images.githubusercontent.com/51314259/68376204-e3dacc00-0150-11ea-88e5-469d224777bb.gif)
