### ISSUE TITLE
[Bug] reproducible full browser crash

### ISSUE THREAD

**Issue by staktrace** [mozilla-mobile/fenix#6089]
## Steps to reproduce
Go to https://staktrace.github.io/moz-pages/fenix6089.html  and click the link.

### Expected behavior
No crash

### Actual behavior
Crash

Normally I would find the crash report on socorro and file a bug but about:crashes doesn't list the crash in Fenix. So I don't know what to do here.

### Device information

* Android device: sony Xperia xz1c
* Fenix version: Nightly 191016 18:01 (Build #12891805)
📦: 16.0.0, ab2555b20
🦎: 71.0a1-20191004094656

**Comment by staktrace** [comment]
Here is a reduced test case: https://gist.github.com/staktrace/e310827753ce057005de36c450d16344

Clicking the link on the page will crash Fenix

**Comment by staktrace** [comment]
Here's a hosted version for easier access: https://staktrace.github.io/moz-pages/fenix6089.html

**Comment by boek** [comment]
This should be fixed now!

**Comment by kbrosnan** [comment]
No longer crashes. Do get a message that `Firefox Nightly can't download the file type`.

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **Nightly Build #20080616 from 01/08** using the following devices:
• Google Pixel 3a (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

► Video
![20200108_113523](https://user-images.githubusercontent.com/51314259/71967154-8aa01f00-320b-11ea-8d04-c175caa56aa1.gif)
