### ISSUE TITLE
Hide whitespace for blocked display ads

### ISSUE THREAD

**Issue by tonmoygoswami** [mozilla-mobile/fenix#6096]
### Why/User Benefit/User Problem
Saves precious mobile real-estate while reading an article/news etc.

### What/Requirements
1. In pages where display ads are blocked, currently it replaces the ad with just white space. Hence, if you're reading a news (say), you get empty blocks of whitespace while you scroll. 

2. In browsers like Edge, they remove the whitespace completely to give the article a uniform look. 

### Acceptance Criteria (how do I know when I’m done?)
When end-user won't even realize that there were ads inside the content of the webpage. The blocking should work behind the scenes, without disturbing the user's flow/scroll.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-13996)

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813244

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
