### ISSUE TITLE
[Telemetry] `activation` ping metrics are expired

### ISSUE THREAD

**Issue by Dexterp37** [mozilla-mobile/fenix#6097]
The [`activation` ping](https://github.com/mozilla-mobile/fenix/blob/master/docs/metrics.md#activation) implemented in #1028 is not being sent anymore as the metrics it should contain have [expired](https://github.com/mozilla-mobile/fenix/blob/f41783c4b3b7c93eaf2e14ebb16c979129de97de/app/metrics.yaml#L640-L672).

**Comment by fbertsch** [comment]
It looks like we set this initially to 6-months collection, but we certainly need more than that. I'll file a data collection request.
