### ISSUE TITLE
The tap area for the close tab button is too small

### ISSUE THREAD

**Issue by st3fan** [mozilla-mobile/fenix#610]
Very often when I try to hit the little X in the top right corner of a tab, I miss it and instead open the tab. The recommended tap area is 24dp but recommended is 48dp with padding. Maybe we can simply put a larger button on top of the whole top right corner?

See also [Touch target size](https://support.google.com/accessibility/android/answer/7101858?hl=en)

Asking @lime124 for feedback

**Comment by thanuj10** [comment]
Swipe to close tabs would be nicer to have.

**Comment by lime124** [comment]
added to the UX triage board. thanks stefan!

**Comment by buttercookie42** [comment]
In Fennec we've used a TouchDelegate (respectively our [own copy](https://dxr.mozilla.org/mozilla-central/rev/c2593a3058afdfeaac5c990e18794ee8257afe99/mobile/android/base/java/org/mozilla/gecko/widget/TouchDelegateWithReset.java) because of a bug that was only fixed for Android P, so we'd have to re-use that for the foreseeable future) to extend the clickable area of the close button without increasing its visual size (which eats into the space available for the tab title).

We also did the same thing for [hover events](https://dxr.mozilla.org/mozilla-central/rev/c2593a3058afdfeaac5c990e18794ee8257afe99/mobile/android/base/java/org/mozilla/gecko/widget/HoverDelegateWithReset.java) to handle explore-by-touch, too.

**Comment by colintheshots** [comment]
I created an extension function for generating TouchDelegates. We just need to be sure to leave enough room in the layout so it works.

**Comment by topotropic** [comment]
Can we define a touch area or do we need to have a button in that size? I think the layout allows for 48 ✕ 48. Let me know if you need any assets. Thanks!

**Comment by vesta0** [comment]
@st3fan can we define a touch area?

**Comment by colintheshots** [comment]
A TouchDelegate resolves the problem by increasing the touch area of the button. This works, provided another button is not right next to the button whose touch area you want to increase. This allows the user to touch a margin area and still manage to press the button.

**Comment by sv-ohorvath** [comment]
Still an issue on the new tabs design.

**Comment by ekager** [comment]
How are we feeling about the size/touch size of this close button now? At some point someone added a 12dp touch size increase. It visually looks pretty small to me, but up to UX

**Comment by nahuhh** [comment]
Either needs to be larger or maybe it just needs to look more like a button?

**Comment by lime124** [comment]
> Can we define a touch area or do we need to have a button in that size? I think the layout allows for 48 ✕ 48. Let me know if you need any assets. Thanks!

^^ This was Nicole's suggestion, but based on what @colintheshots says it isn't clear to me if he's just providing information or saying we can't implement Nicole's suggestion b/c the buttons are too close. 

> A TouchDelegate resolves the problem by increasing the touch area of the button. This works, provided another button is not right next to the button whose touch area you want to increase. This allows the user to touch a margin area and still manage to press the button.

Please clarify. Thanks!

**Comment by lime124** [comment]
perhaps @boek can chime in? please re-add ux label if we need to come up with another solution. thanks!

**Comment by sv-ohorvath** [comment]
Can we consider this fixed with: https://github.com/mozilla-mobile/fenix/issues/4193 ?

**Comment by topotropic** [comment]
Looks like this is fixed. Going to close it.
