### ISSUE TITLE
[Bug] Text in Enhanced Tracking Protection screen overlaps image graphics

### ISSUE THREAD

**Issue by mcarare** [mozilla-mobile/fenix#6100]
## Steps to reproduce
 - Enable "Force RTL layout direction" in Android's Developer options.
 - Open Enhanced Tracking Protection screen from Settings.
### Expected behavior
Text should be readable.
### Actual behavior
Text is difficult to read, because it overlaps the graphics part of the Image.
### Device information

* Android device: all
![etprtl](https://user-images.githubusercontent.com/48995920/67092633-6c042c00-f1b8-11e9-87d3-b43b55b5b54b.png)

**Comment by sv-ohorvath** [comment]
Verified as fixed on nightly 10/21
