### ISSUE TITLE
about:experiments page listing active experiments

### ISSUE THREAD

**Issue by liuche** [mozilla-mobile/fenix#6119]
### Why/User Benefit/User Problem
Users could be interested to know what kinds of experiments they're in, and this is information they could provide to us if they are seeing some issue. This would also help us QA, as well.

### What/Requirements
Somewhere users can see what experiments they're in, can be an about: page or something.

### Acceptance Criteria (how do I know when I’m done?)
Can see in-app what experiments Fenix is in.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-14011)

**Comment by jonalmeida** [comment]
@liuche I imagine this would be similar to `about:studies` on desktop?

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1810822

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
