### ISSUE TITLE
Enable/Disable WebExtensions

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/fenix#6124]
### User Story
As a user, I want to be able to disable a WebExtension (without uninstalling) so I have control over when I use each WebExtension.

### Dependencies
[A-C project board](https://github.com/orgs/mozilla-mobile/projects/44)

### Acceptance Criteria
- I can choose to disable a WebExtension
- I can choose to enable a WebExtension

**Comment by brampitoyo** [comment]
Progress report:
* This one is fairly straightfoward. We’ve decided that this control should take the form of an ON/OFF toggle.
* We also acknowledge the fact that this feature is important for Fennec to Fenix migration. Migrated add-ons from Fennec can be automatically installed on Fenix, but we may choose to turn them OFF by default.

**Comment by AndiAJ** [comment]
Hi, I've just checked this matter on the latest **`Fenix Nightly #20360606 from 2/5`** using the following devices:
• Google Pixel 3a XL (Android 10)
• Google Pixel 3a (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7.0.0)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

On all devices I've noticed that if you consecutively enable/disable 3x the Ublock Addon will generate and endless (enable/disable) loop. 

► Video
![20200205_102423](https://user-images.githubusercontent.com/51314259/73826863-2de25500-4807-11ea-9c05-3cdd56c0f0f1.gif)

Another worth mentioning matter is the **Crash on the LG Nexus 4 (Android 5.1.1) filled in** #8097  wich seem to be occurring quite randomly.

@csadilek & @brampitoyo  - Please review and share your thought on how should we proceed with this matter. ☺️ 

I'll remove the QA needed label until further notice.

**Comment by brampitoyo** [comment]
@AndiAJ Thanks for catching this issue. No. The endless loop shouldn’t happen.

@csadilek I wonder what’s causing this issue?

**Comment by csadilek** [comment]
> Another worth mentioning matter is the Crash on the LG Nexus 4 (Android 5.1.1) filled in #8097 wich seem to be occurring quite randomly.

@AndiAJ @brampitoyo We've landed a fix for this crash today, but the infinite loop when toggling multiple time quickly is likely not fixed by that. We'll put a fix up tomorrow /cc @Amejia481 (I think we fixed that one before).

**Comment by Amejia481** [comment]
Sure, I'm taking a look at it!

**Comment by csadilek** [comment]
@AndiAJ the infinite loop when toggling should no longer happen. Can you re-verify, please?

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly #20380605 from 2/7`** using the following devices:
• Google Pixel 3a XL (Android 10)
• Google Pixel 3a (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7.0.0)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

► Video
![20200207-122745](https://user-images.githubusercontent.com/51314259/74022155-9ebf7380-49a5-11ea-9869-3cfdae24393b.gif)
