### ISSUE TITLE
[Bug] total_uri_count not incremented for existing tabs

### ISSUE THREAD

**Issue by Baron-Severin** [mozilla-mobile/fenix#6126]
## Steps to reproduce
- Navigate to any website in Fenix
- Leaving the tab open, swipe close Fenix
- Reopen Fenix
- Select your previous tab
- Select the nav bar
- Navigate to a new site

### Expected behavior
- `total_uri_count` event should be sent when the site finishes loading

### Actual behavior
- `total_uri_count` event is never sent
(NOTE that the event works from tabs created during the current session)

### Device information

* Android device: Pixel 2 on Android 10. Reproduced on Pixel 2 emulator, API 28
* Fenix version: Current head of master (ba086a8c2dd627f9760602b52d5fd959f889a983)

### Verification notes
Verified by logging in `UriOpenedObserver#onLoadingStateChanged`, which is currently the only place `total_uri_count` events are sent

### Investigation notes (engineering)
- When navigating to an existing tab then clicking links without searching, `UriOpenedObserver` is never instantiated
- When navigating to an existing tab then searching, `UriOpenedObserver` is instantiated, but it does not appear that `UriOpenedObserver.singleSessionObserver` is ever registered

**Comment by codrut-topliceanu** [comment]
Might be fixed by https://github.com/mozilla-mobile/fenix/issues/6577 pending QA verification.

**Comment by BranescuMihai** [comment]
Even though the actual total_uri_count count might be fixed by #6577, the underlying issue with the `UriOpenedObserver` remains, and I detailed the problem here: #9816

**Comment by AndiAJ** [comment]
Hi @Baron-Severin I've just re-checked this matter on **`Nightly Build 200611 from 6/11`** using a Google Pixel 3a (Android 10)

Since you've reported this matter the "events.total_uri_count" is now displayed only in the metrics ping

As per your STR, I've:
1. Navigated to theverge.com
2. Swipe closed Fenix having the tab opened
3. Resumed Fenix and navigated to cnet.com

The Metrics Ping **2b9472e4-7e2f-45fd-9c75-cbbbc54d3060**
```
"counter": {
          "events.total_uri_count": 2
```
[Logcat](https://github.com/mozilla-mobile/fenix/files/4769611/uricount.txt)
[Glean dashboard](https://debug-ping-preview.firebaseapp.com/pings/aj-test12061111)

@BranescuMihai could you please review and share your thoughts ? ☺️

**Comment by BranescuMihai** [comment]
@AndiAJ I think it should have been 3: 2 because you navigated twice to theverge.com and 1 for cnet.com.

From engineering perspective, the init of the sessionObserver is not called from the `TabTrayDialogFragment`, I'll add a fix for that

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly Build 200625 from 6/25`** using a Google Pixel 3a (Android 10)

✔️ **1st scenario**
1. Navigated to theverge.com
2. Swipe close Fenix 
3. Resume Fenix select the previous tab (theverge.com)
4. Tap the Nav bar navigate to cnet.com 

Ping  - **21c39440-c85f-4ed9-93c3-d40fe704ecbb**

```kotlin
"counter": {
          "events.total_uri_count": 3

```
[3.txt](https://github.com/mozilla-mobile/fenix/files/4831246/3.txt)
[Glean dashboard](https://debug-ping-preview.firebaseapp.com/pings/aj-test2506)


✔️  **2nd scenario**
1. Navigated to theverge.com
2. Swipe close Fenix 
3. Resume Fenix select the previous tab (theverge.com)
4. Swipe close Fenix 
5. Resume Fenix select the previous tab (theverge.com)
6. Tap the Nav bar navigate to cnet.com 
7. Swipe close Fenix 
8. Resume Fenix select the previous tab (cnet.com)
9. Swipe close Fenix 
10 Resume Fenix select the previous tab (cnet.com)

Ping  - **e56b5aed-78da-415a-bdf1-17ede7b67870**

```kotlin
"counter": {
          "events.total_uri_count": 6
```

[6.txt](https://github.com/mozilla-mobile/fenix/files/4831398/6.txt)
[Glean dashboard](https://debug-ping-preview.firebaseapp.com/pings/aj-test25063)
