### ISSUE TITLE
Add a translator option

### ISSUE THREAD

**Issue by rache59** [mozilla-mobile/fenix#6133]
Add page translation option in the app, this feature is available in various chromium based browsers but it's not available in Firefox without extension.
And also add better download management system with percentage of download,time left etc.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-14022)

**Comment by amitkumarrathore** [comment]
Hey @rache59  i want to work on it....

**Comment by rache59** [comment]
Sure.

**Comment by sheikh-azharuddin** [comment]
Kiwi supports 4 translation engine and is now open source. Is it not possible to use the code and implement the feature in firefox too?

**Comment by Poopooracoocoo** [comment]
you guys should check out #15458. it's a request for an extension to be added

**Comment by gaul** [comment]
Could Mozilla just approve the [Translate Web Pages](https://addons.mozilla.org/en-US/firefox/addon/traduzir-paginas-web/) addon?

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813760

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
