### ISSUE TITLE
Latest Firefox Focus causes Android system reboot

### ISSUE THREAD

**Issue by asquartz** [mozilla-mobile/fenix#6135]
## Steps to reproduce
Open Firefox Focus 8.0.23 and wait a few seconds, or alternatively click on any web link in another app (Focus is set to handle web links)

### Expected behavior
 Firefox Focus opens and displays webpage

### Actual behavior
Focus opens briefly, then Android immediately reboots.

### Device information
* Android device: Nexus 7 2013, Android 9 (unofficial LineageOS 16)
* Fenix version: 8.0.23 from Play Store

I can't get any info from about:crashes, since the browser doesn't stay open.
This occurred directly after I updated my app to the latest version in the Play Store, and did not happen beforehand.  I have tried deleting and re-installing Focus, and clearing data and cache.

**Comment by ReekyMarko** [comment]
I think you filed this in the wrong repository. This repository contains Firefox Preview, codename Fenix, which will replace Firefox for Android. Firefox Focus is a completely different project.

**Comment by asquartz** [comment]
Oh, my bad, sorry. I'll repost in the correct place.
