### ISSUE TITLE
Double-tap screen in video player to skip backwards/forwards

### ISSUE THREAD

**Issue by anotherus3r** [mozilla-mobile/fenix#6136]
### Why/User Benefit/User Problem

This would make it easier for users to quickly skip parts of a video they are not interested in.

### What/Requirements

- the option to double-tap the left portion of the video player screen to go a few seconds (5 to 10?) backwards
- the option to double-tap the right portion of the video player screen to go a few seconds (5 to 10?) forwards

The amount of seconds could also increase with the amount of taps.

### Acceptance Criteria (how do I know when I’m done?)

When the feature works as described above. Basically, how this feature works in the YouTube app.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-14024)

**Comment by Dunexus** [comment]
Related to https://github.com/mozilla-mobile/fenix/issues/2011

**Comment by mortenfc** [comment]
3 years later and no sight of this in Firefox Nightly. This missing feature is the only reason I am not using Firefox Mobile.
The base video player many sites fall back on is so bare-bone and minimum it's horrible for longer videos.

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813759

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
