### ISSUE TITLE
[UX] Private Browsing should look and feel distinct from normal browsing

### ISSUE THREAD

**Issue by brampitoyo** [mozilla-mobile/fenix#614]
This is a visual design bug to visually distinguish Fenix’s private browsing mode by building a unique theme for it.

Having light and dark themes will be important for the upcoming Android Q release, where user will be able to freely switch themes. Our Private Browsing theme will not only need to look totally distinct from normal browsing. It will also need to play well alongside both light and dark themes.

**Comment by lime124** [comment]
@brampitoyo we're closing this b/c we have that now. feel free to reopen if i misunderstood.
