### ISSUE TITLE
Replace android:drawableTint

### ISSUE THREAD

**Issue by NotWoods** [mozilla-mobile/fenix#6145]
This property in XML layout files doesn't work on older Android devices, so we should switch to the appcompat version (`app:drawableTint`).

There may be corresponding `Drawable#setTint` calls that are made redundant after this change. They should be ideally removed as well.

**Comment by ekager** [comment]
Looks like we're just missing one item here in the `search_pill` style. Not sure if it's impacting the look of the search pills on older devices, but we should probably just replace it there as well for continuity.

**Comment by ValentinTimisica** [comment]
@ekager Because the patch for this ticket was already merged by the time I saw your comment I created a new issue (#6268) for which I already have a pull request.

**Comment by NotWoods** [comment]
I'll close this issue since the remaining work has been spun out into another issue.
