### ISSUE TITLE
Entry points to install WebExtensions

### ISSUE THREAD

**Issue by brampitoyo** [mozilla-mobile/fenix#6147]
From Fennec-to-Fenix Transition user research:

> Recommendation
> Determine how to introduce a range of add-on options during the experience
> 
> Rationale
> Add-ons were front of mind when users were asked about “customization”; create vivid entry points to educate and promote value in the experience.

Entry point means more than onboarding content. It can mean in-product messaging and making features visible within the experience (e.g. private tabs, search shortcuts).

Keep in mind that one of the research recommendations is:

> Introduce new features within the experience instead of stacking the menu.
> 
> Most features related to customizing either the home screen view or the user’s session and tasks were invisible to them, **buried in a complex menu** that discouraged proactive exploration and discovery.
> 
> The search and navigation focus of the participants’ usage scenarios also meant that **little time was spent lingering on the home screen**. Browser controls that followed the experience (the tab stack icon, the URL bar) were more familiar and useful for their goals.

**Comment by sv-ohorvath** [comment]
@gabrielluong Could you post some requirements for QA to verify, please?

**Comment by csadilek** [comment]
Ah, this is a UX / research ticket. @brampitoyo can you advise? Do you want to keep this open? :)

**Comment by brampitoyo** [comment]
Thanks, @csadilek. I’ve taken this into account when designing WebExtensions. With support shipping in product, we can consider this issue finished, and can close it.
