### ISSUE TITLE
[Bug] Unable to copy magnet links

### ISSUE THREAD

**Issue by lokesh-krishna** [mozilla-mobile/fenix#6149]
## Steps to reproduce
Long press on a magnet link in order to bring up the menu to copy the link

### Expected behavior
Menu pops up with option to copy link to the clipboard

### Actual behavior
No matter how long you press on a magnet link, the menu to copy the link doesn't appear

### Device information

* Android device: Redmi Note 4 running Android 9
* Fenix version: Version Nightly 191020 18:01

**Comment by boek** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1610951

**Comment by kbrosnan** [comment]
Do we really need Geckoview here? Seems like we could just copy whatever is in the anchor element similar to what was done in https://github.com/mozilla-mobile/android-components/issues/7933

**Comment by clientenq** [comment]
Any URI should fall under copy link. Not just specific schema. This was P2 and now open for almost 9 months as low as P3. This is removed long time existing functionality should have higher priority to show we care about user needs.

**Comment by SinTan1729** [comment]
It seems to have been fixed.
Redmi K20 (Android 10)
Nightly 200905 06:01
![Screenshot_2020-09-05-14-29-08-792_org.mozilla.fenix.jpg](https://user-images.githubusercontent.com/35728385/92301789-3741c480-ef84-11ea-8cf6-71c5c224e505.jpg)

**Comment by evilpie** [comment]
Should have been fixed by https://github.com/mozilla-mobile/android-components/issues/8297 by @rocketsroger. :+1:

**Comment by simonbru** [comment]
I confirm that I can successfully "Long press => Copy" on a magnet link on Fennec 86.1.1.
