### ISSUE TITLE
[Bug] A website is not rendered correctly 

### ISSUE THREAD

**Issue by LaurentiuApahideanSV** [mozilla-mobile/fenix#6150]
## Steps to reproduce
1. Go to https://www.idokep.hu/hirek/halo-melleknap-zenit-koruli-iv-es-mellekhold-is-jutott-hetfore
### Expected behavior
The page is rendered correctly
### Actual behavior
The site constantly being refreshed.
### Device information

* Android device: Samsung Galaxy S8+ (Android 8.0.0)
* Fenix version: 2.2.0 (Build #12901947)

**Comment by boek** [comment]
@LaurentiuApahideanSV is this still an issue?

**Comment by kbrosnan** [comment]
Working for me in Preview Nightly build #20070607

**Comment by AndiAJ** [comment]
Hi, **verified as fixed**on the latest **Nightly Build #20080616 from 01/08** using the following devices:
• Google Pixel 3a (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

► Video
![20200108_085314](https://user-images.githubusercontent.com/51314259/71956913-0b075580-31f5-11ea-87a6-511dd9ea6a3a.gif)
