### ISSUE TITLE
Display silent Running in Firefox notification in TWA

### ISSUE THREAD

**Issue by NotWoods** [mozilla-mobile/fenix#6153]

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **Nightly Build #13050627 from 1/11** using the following devices:
• Google Pixel 3a XL (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

► Video
![20191101_100349](https://user-images.githubusercontent.com/51314259/68011885-24d66a80-fc91-11e9-87b1-0ce192dda91d.gif)

@NotWoods - I've also noticed that the refresh & copy URL are available and work properly #204 . :smiley:
