### ISSUE TITLE
[Bug] Dismissing QAB by tapping the pill in middle taps the action as well

### ISSUE THREAD

**Issue by bogas04-swiggy** [mozilla-mobile/fenix#6154]
## Steps to reproduce
1. Open Quick Action Bar by tapping the middle pill
2. Dismiss it by tapping the pill again

### Expected behavior
Should dismiss normally

### Actual behavior
Dismisses as well as taps the action (bookmark or share)

![Screencast](https://thumbs.gfycat.com/QuarterlyHealthyFinnishspitz-size_restricted.gif)
### Device information

* Android device: RealmeX, Android 9, ColorOS
* Fenix version: Nightly 191020 18:01 (Build #12931810) 📦: 18.0.0, d40f5a40d 🦎: 71.0a1-20191018095340

**Comment by BranescuMihai** [comment]
Our QuickActionSheet looks like is designed as a Modal BottomSheet, and the material design guidelines suggest that we should not collapse the modal on tap. Maybe UX can confirm this.
Resources:
[Go to control section for the modal bottom sheet](https://material.io/components/sheets-bottom/#modal-bottom-sheet)
[Merged pull request from flutter removing this exact functionality to be in line with material design](https://github.com/flutter/flutter/pull/32528)

**Comment by brampitoyo** [comment]
@BranescuMihai is correct:

> …the material design guidelines suggest that we should not collapse the modal on tap

Specifically, the modal should not close when the pill is tapped.

Instead, what should happen is… nothing. In the demo video you posted, @bogas04-swiggy, you clearly didn’t tap on Bookmarks. So the Bookmarks page shouldn’t show up, either.

Only when you tap the area outside of the modal, then it will close.

**Comment by brampitoyo** [comment]
I would say that this issue is WONTFIX. What _does_ need to be fixed is the fact that tapping the pill shouldn’t tap any other button in the Quick Action Bar.

**Comment by ekager** [comment]
Closing because we removed the QAB
