### ISSUE TITLE
[webcontent] LinkedIn job submit form not working

### ISSUE THREAD

**Issue by Waqar144** [mozilla-mobile/fenix#6159]
## Site with issue and any steps to reproduce
Site: https://linkedin.com/
1. Go to job search and find any job with the option to **"Easy Apply"**
2. Click **Easy Apply Button**, (A form will open)
3. Click **Submit**, Nothing happens.

### Expected behavior
On clicking **Submit** the form should submit itself.
### Actual behavior
On clicking **Submit** the form doesn't submit itself and it seems as the submit button isn't working.

### Does toggling Tracking Protection fix the issue? (Press the lock icon in the toolbar while on the site to see toggle)
No.

### Can you reproduce in [Firefox for Android](https://play.google.com/store/apps/details?id=org.mozilla.firefox)?
Haven't checked.

### Can you reproduce in Chrome (or other non-Mozilla browser)?

No. It works in chrome and firefox desktop.

### Device information

* Android device: Google Pixel 1.
* Android version: Android 10
* Fenix version: 2.2.0 (installed using playstore, last updated Oct 17, 2019)

**Comment by boek** [comment]
I wonder if ETP is causing this?

**Comment by Waqar144** [comment]
It seems to be working now, so I wonder if it's okay to close this.
