### ISSUE TITLE
Today's History Shows All History

### ISSUE THREAD

**Issue by Sdaswani** [mozilla-mobile/fenix#616]
## Steps to reproduce
Go to your history screen

### Expected behavior
History is broken down into correct time periods

### Actual behavior
'Today' history seems to be showing my lifetime history

### Device information

* Android device: Galaxy S8
* Fenix version: 1.0.1908

This work may still be in progress, just filing in case not.

![screenshot_20190220-200626_fenix](https://user-images.githubusercontent.com/4879954/53143743-325a2300-354e-11e9-86db-5d6c9443e046.jpg)

**Comment by boek** [comment]
Blocked by  https://github.com/mozilla-mobile/android-components/issues/2016

**Comment by boek** [comment]
Fixed with #1176
