### ISSUE TITLE
[ETP] Update exceptions icon

### ISSUE THREAD

**Issue by AmyYLee** [mozilla-mobile/fenix#6168]
Please update the Exceptions icon. I've attached a screenshot for reference. Swapping out the "i" icon for a globe. Globe icon attached as well. Thanks!
<img width="370" alt="Screen Shot 2019-10-21 at 4 28 44 PM" src="https://user-images.githubusercontent.com/5992746/67241229-0a92c600-f421-11e9-94da-0c7bf239ef90.png">

[Globe Icon.svg.zip](https://github.com/mozilla-mobile/fenix/files/3752795/Globe.Icon.svg.zip)

**Comment by ekager** [comment]
We already have this icon in the project as `ic_internet` so whomever picks up this issue please use that icon as the new icon for the `pref_key_tracking_protection_exceptions` preference in `tracking_protection_preferences.xml` 💫

**Comment by ardlank** [comment]
Can I take up this issue?

**Comment by ardlank** [comment]
@AmyYLee @ekager PR is raised: #6234

**Comment by darkwing** [comment]
Closing since the PR was merged.
