### ISSUE TITLE
[webcontent] Browser recognition is off

### ISSUE THREAD

**Issue by rpsu** [mozilla-mobile/fenix#6175]
## Site with issue and any steps to reproduce
Browse page "How to clear browsing history in Firefox Preview" https://support.mozilla.org/en-US/kb/how-clear-browsing-history-firefox-preview using Firefox Preview complains me using older mobile browser. In other words that page is not able recognize I am using Firefox preview -browser.

https://pbs.twimg.com/media/EHGJyLZWwAAEWGC?format=jpg&name=4096x4096
https://twitter.com/firefox/status/1186207598565044224

### Does toggling Tracking Protection fix the issue? (Press the lock icon in the toolbar while on the site to see toggle)
no
### Can you reproduce in [Firefox for Android](https://play.google.com/store/apps/details?id=org.mozilla.firefox)?
Have not tested  this.
### Can you reproduce in Chrome (or other non-Mozilla browser)?
Have not tested this.
### Device information

* Android device: Samsung S8
* Fenix version: 2.1.0, build 12821601

**Comment by darkwing** [comment]
Thank you for the report @rpsu!  I've reported this to MDN https://github.com/mdn/kuma/issues/6100

**Comment by atopal** [comment]
Perttu, would you mind filing this under https://github.com/mozilla/kitsune? That way you'll get updates as things get fixed.

**Comment by rpsu** [comment]
Will do, thanks!
