### ISSUE TITLE
[Bug] Fenix jumps up while scrolling

### ISSUE THREAD

**Issue by andreicristianpetcu** [mozilla-mobile/fenix#6176]
## Steps to reproduce
Open https://mobile.twitter.com/jensimmons/status/1186639878169251840
Scroll down slowly
### Expected behavior
Continuous scroll down
### Actual behavior
From time to time it jumps up
https://vimeo.com/367964926
### Device information

* Android device: OnePlus5t
* Fenix version: latest nightly

**Comment by andreicristianpetcu** [comment]
it happens in twitter also

it started a few days ago

**Comment by andreicristianpetcu** [comment]
here is a long thread to test on twitter https://mobile.twitter.com/jensimmons/status/1186639878169251840

**Comment by softvision-miralobontiu** [comment]
I was able to reproduce the jumping on twitter on Samsung Galaxy Tab S3 (Android 8), on the 12/09 Nightly build.

**Comment by andreicristianpetcu** [comment]
cannot reproduce on pocket anymore, only on twitter

**Comment by andreicristianpetcu** [comment]
I can see something similar on bugzilla https://bugzilla.mozilla.org/show_bug.cgi?id=567039

It works fine in Fennec

![recording_20200122_074451_1](https://user-images.githubusercontent.com/922368/72868812-c814aa00-3ceb-11ea-88a6-d8f33849d773.gif)

**Comment by andreicristianpetcu** [comment]
Might be a duplicate of https://github.com/mozilla-mobile/fenix/issues/5789

**Comment by boek** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1610952

**Comment by vesta0** [comment]
This should be a higher priority.

**Comment by reyis4402** [comment]
When you open the answer given to comments while using Twitter, the page goes to the top

**Comment by yoasif** [comment]
I see this all of the time in a Twitter PWA on a Pixel 2. Glad there was a bug filed already. :)

**Comment by andreicristianpetcu** [comment]
This seems fixed. There is this followup bug https://bugzilla.mozilla.org/show_bug.cgi?id=1615562

Should I create a new bug on github also?

**Comment by Mattwo7** [comment]
I have this issue on regular Firefox when I reach my reply on a post.
