### ISSUE TITLE
[Bug] Privacy notice in settings opens in custom tab

### ISSUE THREAD

**Issue by mcarare** [mozilla-mobile/fenix#6178]
Should _Privacy notice_ open in a custom tab? _Help_ in Settings and _learn more_ from ETP open in normal browser.
Also, the _Privacy notice_ is the only item in Settings that does not have an icon.

**Comment by brampitoyo** [comment]
@mcarare Let’s ask @AmyYLee.

My initial thinking is that _Privacy Notice_ is similar to _About_ page, in that it’s supposed to be a native in-app page – not a website.

**Comment by AmyYLee** [comment]
> @mcarare Let’s ask @AmyYLee.
> 
> My initial thinking is that _Privacy Notice_ is similar to _About_ page, in that it’s supposed to be a native in-app page – not a website.

I checked Fennec and the privacy notice is also the same webpage. What would be the work required to make it an in-app page? Is it worth it? Also I'm wondering if we need the Privacy notice in the settings screen? I'm working on the "About Firefox Nightly" page in settings and I think we can move it in there. Thoughts?

**Comment by mcarare** [comment]
@AmyYLee  I think it would be a good idea to have the link for privacy notice inside the "About Firefox Preview Page", along with "open source libraries..." and "what's new..."

**Comment by AmyYLee** [comment]
> @AmyYLee I think it would be a good idea to have the link for privacy notice inside the "About Firefox Preview Page", along with "open source libraries..." and "what's new..."

Sounds good to me. We are in the process of updating the About Firefox Review page here https://github.com/mozilla-mobile/fenix/issues/4776

**Comment by mcarare** [comment]
waiting on https://github.com/mozilla-mobile/fenix/issues/4776

**Comment by mcarare** [comment]
Closing this as Privacy notice has been moved to the About page.
