### ISSUE TITLE
[Bug] Private session icons position moved

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#6179]
## Steps to reproduce
1. Open a private tab.
2. Go to homescreen. Observe the share and trash icons.
### Expected behavior
They are aligned on the right side.
### Actual behavior
They moved more to the center.
![Screenshot_20191022-151353](https://user-images.githubusercontent.com/4037709/67286530-3aee6900-f4e2-11e9-9381-a023f6a39d54.png)

### Device information

* Android device: Pixel 3, HTC Desire 820
* Fenix version: Nightly 10/21

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **Nightly Build #13090608** from 5/11 using the following devices:
• Google Pixel 3a XL (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

► Video
![20191105_144006](https://user-images.githubusercontent.com/51314259/68208975-0f3baa80-ffdb-11e9-98dc-05ef57a9ac51.gif)
