### ISSUE TITLE
Some Elements are hidden on some sites when the address bar is not collapsed.

### ISSUE THREAD

**Issue by thanuj10** [mozilla-mobile/fenix#618]
On some sites like reddit, When the URL bar is not collapsed, some elements are hidden or not properly aligned with the URL bar.

Check image for reference.

https://ibb.co/12h3SLW

**Comment by sblatz** [comment]
There is an a-c ticket for this: https://github.com/mozilla-mobile/android-components/issues/1959 which we are waiting on.

**Comment by vesta0** [comment]
Dup of #552
