### ISSUE TITLE
[Bug] Align the ETP radio buttons to the left in RTL mode

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#6180]
## Steps to reproduce
1. Enable "Force RTL layout direction" in Android's Developer options.
2. Go to Settings> Enhanced Tracking Protection
3. Observe the Standard & Strict radio buttons
### Expected behavior
Radio buttons on the left, like the toggle, labels on the right.
### Actual behavior
Radio buttons on the right, labels on the left. opposite as the ETP toggle.
### Device information

* Android device: any
* Fenix version: Nightly 10/21

meta: https://github.com/mozilla-mobile/fenix/issues/5497

![Screenshot_20191022-155134](https://user-images.githubusercontent.com/4037709/67287515-f368dc80-f4e3-11e9-9869-59f9c7921127.png)

**Comment by brampitoyo** [comment]
@sv-ohorvath Yes. This sounds like a good change to me.

Question: I see that the text on “Enhanced Tracking Protection” is still left-aligned. Do we need to right-align the text (for RTL languages), or will Android take care of that for us?

**Comment by ItielMaN** [comment]
> 
> 
> @sv-ohorvath Yes. This sounds like a good change to me.
> 
> Question: I see that the text on “Enhanced Tracking Protection” is still left-aligned. Do we need to right-align the text (for RTL languages), or will Android take care of that for us?

No, actually the current state of the radiobuttons is fine, they are placed on the opposite side compared to LTR.
This article may be of help when testing RTL:
https://developer.mozilla.org/en-US/docs/Mozilla/Developer_guide/RTL_guidelines

As for the “Enhanced Tracking Protection”, yes, it should be aligned to the right, and this will happen automatically once the text is localized into a real RTL language.
Whether to align it to the right anyway is a different question, which I think the answer to would be yes, align it anyway.

**Comment by brampitoyo** [comment]
@ItielMaN wrote:

> As for the “Enhanced Tracking Protection”, yes, it should be aligned to the right, and this will happen automatically once the text is localized into a real RTL language.

That sounds good. Thanks!

There are a few more things that will need to be changed slightly:

1. “Browse without being followed” and “Keep your data to yourself…” should be aligned right
2. Learn more arrow should be reversed
3. Make sure the padding and margin matches LTR, but reversed

Inspect: https://share.goabstract.com/feec4732-3ec4-4ed1-a17b-c967083c2433?collectionLayerId=2f0c7f74-d809-425a-912f-9be8063f7de3&mode=compare

<img src="https://user-images.githubusercontent.com/51007/74690501-38a7db80-5244-11ea-9377-dd2fda3efea0.png" width="360">

**Comment by liuche** [comment]
might be a good first bug for @person808

**Comment by person808** [comment]
Seems like the layoutDirection for all views is set to rtl, but for some reason the TextViews aren't respecting that

**Comment by sflorean** [comment]
Verified as fixed on Nightly from 6/9 with Google Pixel 3 (Android 10) and Nokia 6 (Android 7.1.1), got the same result as [here](https://github.com/mozilla-mobile/fenix/issues/6180#issuecomment-587181890).
