### ISSUE TITLE
[Fenix] Tab switching doesn't work from gmail to Nightly

### ISSUE THREAD

**Issue by AmyYLee** [mozilla-mobile/fenix#6187]
1. Open gmail (github with image email)
2. Click on the image to view full screen
3. Long press and select "open image in new tab"
4. Tap on the snackbar notification that says "SWITCH"

Expected behavior
It will switch to Firefox Preview and show image in new tab

Actual behavior
Does not switch to Firefox Preview, new tab with image is opened in Firefox Preview in the background

See screencap for reference
https://cl.ly/03367e76a0d0

### Device information
Pixel 3

Firefox Preview Nightly

**Comment by boek** [comment]
Looks like this was fixed when we fixed #6229 with this commit fb17ae2258db912bbcf3a760ef6a5778ac0b4671
