### ISSUE TITLE
Initialization of metrics unexpectedly takes 70ms

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#6196]
### User problem
Colin noticed the initialization of our metrics – Glean & Leanplum – takes about 70ms (on which device?) and that there may be wins to be had here.

### Impact
If we don't do this, we may be leaving behind <= 70ms of perf improvements on startup (cold, warm?).

### Acceptance criteria
TODO

**Comment by hawkinsw** [comment]
I am resolving this as a result of @csadilek merge above. However, I am going to open a related issue for the performance problem of starting the Leanplum metrics.
