### ISSUE TITLE
Update copy and graphic on QR scanning screen

### ISSUE THREAD

**Issue by lime124** [mozilla-mobile/fenix#6198]
Pulled from A/C:
https://github.com/mozilla-mobile/android-components/issues/4261

Please update graphic ([zip file](https://github.com/mozilla-mobile/android-components/files/3560022/reticle.zip) in above A/C issue). We've also dropped the https for legibility.

**Comment by KMaragh** [comment]
@lime124 @NotWoods Mind if I pick this up? :)

**Comment by NotWoods** [comment]
Hi @KMaragh, unfortunately this ticket has already been picked up in the Android Components repository and I don't think there will be much additional work. Check out our [Hacktoberfest issues](https://github.com/mozilla-mobile/fenix/issues?q=is%3Aopen+label%3AHacktoberfest+no%3Aassignee) for other options 😄

**Comment by KMaragh** [comment]
@NotWoods I will! Thanks :)

**Comment by boek** [comment]
Waiting on https://github.com/mozilla-mobile/android-components/pull/4845

**Comment by mcarare** [comment]
Should we also lock screen orientation like it was suggested here: https://github.com/mozilla-mobile/fenix/issues/7132 ?

**Comment by vesta0** [comment]
@mcarare I don't think so - is there a reason we'd want to do that?

**Comment by LaurentiuApahideanSV** [comment]
Verified as fixed on Firefox Preview Beta 5.1.0-beta.2 and Nightly 200529 (Build #21500608) 5/29 using a OnePlus 6T (Android 9) and Huawei MediaPad M3 lite (Android 7.0). The QR code screen is according to the one found in https://github.com/mozilla-mobile/android-components/issues/4261.

**Comment by mcarare** [comment]
Closing as per comment above.
