### ISSUE TITLE
Top toolbar flashes "fragment_browser" when exiting Settings menu after scroll

### ISSUE THREAD

**Issue by Cheap-Skate** [mozilla-mobile/fenix#620]
From normal Web content page
3 dot menu
Settings
Scroll Settings page to e.g. view bottom-most items
Leave Settings page in scrolled position
Hit "back" button
Top toolbar flashes "fragment_browser" as return to normal Web content

I see this on Galaxy S7 / Android 8.0.0 and Sony Xperia X Compact / Android 8.0.0

**Comment by thanuj10** [comment]
I dont have the "fragment_browser" flash when returning to the normal web content. However, i have a very jarring animation when pressing back from the settings menu.

Device - Nokia 6.1 Plus

**Comment by Cheap-Skate** [comment]
Hmmm I don't see it now either. I think the STR are more complicated than I posted. Will see if I can work out how to do it reliably. And yes, the transition is abrupt.
