### ISSUE TITLE
Cannot access the "Network ID" section through "about:networking#networkid" search

### ISSUE THREAD

**Issue by Diana-Rus** [mozilla-mobile/fenix#6202]
## Steps to reproduce
1. Open Fenix application.
2. Tap in the URL bar and insert "about:networking#networkid".
3. Make a search after it.
### Expected behavior
After searching "about:networking#networkid" the section is displayed.
### Actual behavior
After searching "about:networking#networkid" a search through default engine is made.

NOTE:
- When testing on Fennec/Firefox Nightly 71.0a1 (2019-09-25) from treeherder build the issue was not present and I could access the section by having the searched after "about:networking#networkid".
- Issue is related to Feature - Network ID.

### Device information

* Android device: Google Pixel 3a XL (Android 9)
* Fenix version: Fenix Nightly 191021 (Build #12940608) - Gecko View Version 71.0a1-20191018095340

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-14072)

**Comment by valenting** [comment]
This seems related to #3306 and #1681 in the sense that URLs not understood by the URL bar are treated as search terms.

**Comment by Diana-Rus** [comment]
Hi, I rechecked the issue and now when making a search in URL bar after:
- "about:networking#networkid"
- "about:networking#dns"
the about pages are correctly displayed. 
In case the user wants to search after a different section, only a refresh of the page will display the result.
Please check.
![20200205_180209](https://user-images.githubusercontent.com/49859863/73859612-f85b5d00-4842-11ea-9b49-4f0781a140c2.gif)

Note:
Checked with Google Pixel 3 XL(Android 9) on:
- Firefox Preview beta 3.2.0-beta.3 (Build #20250043) GV: 73.0-20200123180644
- Firefox Nightly Preview 200204 (Build #20350606) GV: 74.0a1-20200203085242

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813242

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
