### ISSUE TITLE
[Bug]Instagram media notification issue

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#6211]
## Prerequisites
The devices Media volume should not be muted

## Steps to reproduce
1. Navigate to any Instagram account
2. Tap on one of the video items and play it
3. Tap the back button (device hardware back or 3dot button>back)
4. Check the android notification bar and tap play
5. Navigate back to the previously opened and played video item

### Expected behavior
The notification should be dismissed once leaving the video content page.

### Actual behavior
The media notification is still displayed.
By taping the play button, the video content seem to be playing in background (the sound of the video is played)
After revisiting the previously opened page the video isn't actually playing.

### Device information

* Android device: Google Pixel 3 XL (Android 9)
* Fenix version: Nightly Build #12960607 from 23/10

### Notes
► Video 
![20191023_143948](https://user-images.githubusercontent.com/51314259/67393255-b287cb00-f5aa-11e9-84b5-3d67f9b482d7.gif)

**Comment by rocketsroger** [comment]
Looks like this is related to https://bugzilla.mozilla.org/show_bug.cgi?id=1631907.  Will retest when fix is in.

**Comment by liuche** [comment]
Oh this linked to the same bug as #6454, where Agi suggested using the new media apis.

**Comment by rocketsroger** [comment]
Not reproducible with the new `MediaSession` API.  Put back to backlog till the new `MediaSession` API is integrated in Fenix.

**Comment by rocketsroger** [comment]
With Dec 9th nightly this is fixed.  Please verify

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly 201210`** using the following devices:
• Google Pixel 3a (Android 11)
• Huawei Mate 20 Lite (Android 10)
• OnePlus A3 (Android 6.0.1)
