### ISSUE TITLE
[Bug]Facebook Stories playback issue

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#6213]
## Prerequisites
The devices Media volume should not be muted

## Steps to reproduce
1. Tap on one of the featured Facebook Stories

### Expected behavior
The stories should be played one by one automatically.
By tapping the left side, the previous story should be displayed and automatically played
By tapping on the right side the next story should be displayed and automatically played .

### Actual behavior
The first story isn't actually starting to play. 
Whereas, the Stories progress bar shows progression.  

The play button is displayed and by tapping it both video playback and media notification work as expected.

When tapping on the right side of the story, the next story isn't starting to play automatically.
On the other hand, the pause button is displayed in the media notification (which should mean that the video is being played), but it's not the case, there's no audio output.  

### Device information

* Android device: Google Pixel 3a XL (Android 9)
* Fenix version: Nightly Build #12960607 from 23/10

### Notes
Autoplay isn't blocked

► Video
![20191023_144742](https://user-images.githubusercontent.com/51314259/67396507-650e5c80-f5b0-11e9-8b8c-ba36c6df0acf.gif)

**Comment by rocketsroger** [comment]
Seeing couple of issues here:
1. Media notification is not working as expected.  (Related to https://github.com/mozilla-mobile/reference-browser/issues/942)
2. Auto play is not working as expected.  Within a Facebook story, every single page requires user to manually tap on play to start.  Seeing the same issue in Instagram as well.

**Comment by rocketsroger** [comment]
Created the GeckoView issue to track the second issue above:
https://bugzilla.mozilla.org/show_bug.cgi?id=1637713

**Comment by rocketsroger** [comment]
This issue is a site issue.  Chrome behaves the same.  GeckoView issue has been closed.
