### ISSUE TITLE
[Bug]The characters are changed with a black line using LG keyboard

### ISSUE THREAD

**Issue by sv-sdeiac** [mozilla-mobile/fenix#6217]
## Prerequisites
Make sure you have LG keyboard set on your device

## Steps to reproduce
1. Go to any page with a text field(ex. facebook login page);
2. Start to type characters on the email field; 

### Expected behavior
All characters are visible on the field.

### Actual behavior
The characters are changed with a black line.

### Device information

* Android device: LG g7 fit (Android 8.1)
* Fenix version: Nightly v.191023 10/23 6:07 AM.

## Notes
* Not reproducible with QWERTY keyboard;
* Not reproducible on Firefox preview RC 2.2.0
* video: 
![blackline](https://user-images.githubusercontent.com/40264165/67400554-7a868500-f5b6-11e9-803f-f63f5e62e636.gif)

**Comment by sv-sdeiac** [comment]
After my previous investigation, I found that the issue is reproducible using the RC build of Firefox Preview 3.0.1 build #13502256 on LG G7 fit (Android 8.1).
Also, I can't reproduce the issue with the latest version of Firefox Preview Nightly 1/7 build #20070606.

**Comment by kbrosnan** [comment]
Since this is working on nightly lets close this.
