### ISSUE TITLE
[Bug] Crash when opening new tab in CustomTab

### ISSUE THREAD

**Issue by csadilek** [mozilla-mobile/fenix#6229]
The context menu for custom tabs now shows A-Cs default candidates including "open in new tab" and "open in private tab", which will crash:
https://sentry.prod.mozaws.net/operations/fenix-nightly/issues/6520064/

I don't think we should be showing these options for CustomTabs.

**Comment by sv-ohorvath** [comment]
Verified as fixed on Nightly 10/28.
