### ISSUE TITLE
Change android:text to tools:text in layout_percentage_seek_bar

### ISSUE THREAD

**Issue by NotWoods** [mozilla-mobile/fenix#6237]
This causes a lint issue and the text should get overriden later.

**Comment by psy0ch** [comment]
Hi there!
Inside layout_percentage_seek_bar.xml there are multiple cases of android:text used. Which ones do need to be changed to tools:text?
From my understanding it should only be

- android:text="@string/accessibility_text_size_sample_text"

**Comment by NotWoods** [comment]
Sorry! The correct one to change is `android:text="200%"`. It current causes a lint issue because it's not using a string resource, but it doesn't get used anyways so we should make it tools-only.
