### ISSUE TITLE
[Bug]Last opened tabs isn't closed on first attempt using device back button on Cnet.com

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#6239]
## Steps to reproduce
1. Navigate to Cnet.com
2. Open links from the homepage in new tabs
3. Using the snackbar switch to the last link
4. Repeatedly pres device back button until you close all previous links

### Expected behavior
The last listed page from the "Open Tabs" section is closed on first attempt

### Actual behavior
The last listed page from the "Open Tabs" section is closed only after second attempt

### Device information

* Android device: 
• Google Pixel 3a XL (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• OnePlus A3 (Android 6.0.1)

* Fenix version:  Nightly Build #12970607 from 24/10

### Notes
Noticed while checking #2629 
Not reproducible on • LG Nexus 4 (Android 5.1.1)

► If you have >=3 open tabs in order to close the last tab you have to tap 2x on the back button
![20191024_112517](https://user-images.githubusercontent.com/51314259/67469081-54afbd80-f654-11e9-9b76-459a64ab6495.gif)

► If you have <=2 open tabs the last tab is properly closed on first attempt
![20191024_112437](https://user-images.githubusercontent.com/51314259/67468982-229e5b80-f654-11e9-8534-8de910f0fe5d.gif)

**Comment by boek** [comment]
#6694

**Comment by topotropic** [comment]
@AndiAJ can you verify this bug? I think it got fixed. Thanks!

**Comment by softvision-miralobontiu** [comment]
Verified as fixed on the latest Nightly build from 2/14 with Sony Xperia Z2 (Android 6.0.1), Google Pixel 2 (Android 10), and Sony Xperia Z5 Premium (Android 7.1.1).
