### ISSUE TITLE
[Bug]Closing links opened in new tabs creates parent-child inconsistency

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#6247]
## Steps to reproduce
1. Navigate to any website
2. Open at least 3 links in new tabs
3. Tap 3x the device back button 

### Expected behavior
The links should be opened in order.
When starting to delete them one by one the last tab left to be deleted should be the parent tab

### Actual behavior
Due to [#3124](https://github.com/mozilla-mobile/fenix/issues/3124): when starting to delete the tabs one by one using the device back button, the order is messed up.

The tab containing the last open link will be deleted (Child # 3)
The tab containing the parent website will be deleted (Parent)
The tab containing the penultimate link will be deleted (Child # 2)
The tab containing the first link will be deleted (Child # 1)

### Device information

* Android device: 
• Google Pixel 3a XL (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

* Fenix version: Nightly Build #12970607 from 24/10

► Video
![20191024_143115](https://user-images.githubusercontent.com/51314259/67485345-79b32900-f672-11e9-80d6-164c2e27b0cd.gif)

**Comment by boek** [comment]
Let's add this to #6694

**Comment by topotropic** [comment]
@AndiAJ is this fixed? 

To me it seems it behaves as expected – when I use Android back button the current (child) tab is closed and I land on the parent one.

**Comment by AndiAJ** [comment]
Hi @topotropic , since I've logged this issue, [#6620](https://github.com/mozilla-mobile/fenix/issues/6620) was implemented.

For instance, If you have 4 tabs opened (1 parent & 3 child tabs) and switch to the last child tab (child # 3) you will not be able to close child tab # 1 & child tab # 2 using the device back button, due to the fact that the links opened in new tabs don't follow the most recent order (this is the main aspect because of which I've filled this issue). 

► Video
![20200212-172100](https://user-images.githubusercontent.com/51314259/74351170-6feb3800-4dbf-11ea-9b63-3f82503d6bcf.gif)

Please review and share your thoughts. ☺️

**Comment by mcarare** [comment]
@topotropic I think this is the expected behaviour. Opening links in new tab does not navigate to them, if you don't hit _switch_ on the snackbar. So, when pressing back you should just close the child tab and then after another back press close the parent. Childs opened but not navigated to should remain opened. 
Please let us know if we can close this, or what should be the expected behaviour. TY!

**Comment by topotropic** [comment]
This is expected behavior, I'll close the issue.
