### ISSUE TITLE
Bug 1590995

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/fenix#6248]
https://bugzilla.mozilla.org/show_bug.cgi?id=1590995

**Comment by pocmo** [comment]
CC @NotWoods

**Comment by ekager** [comment]
Hey @jonalmeida you're mentioned in the (closed) bugzilla ticket linked. Can we close this?

**Comment by jonalmeida** [comment]
I know we had a linked issue here. Yeah, we can close this now. Thanks!
