### ISSUE TITLE
[Bug] Selection and dragging of text is buggy

### ISSUE THREAD

**Issue by Sgt-Miller** [mozilla-mobile/fenix#6252]
## Steps to reproduce
Go to any website with text. Long press to select text. Now drag one of the two pointers to extend selection.
### Expected behavior
Smoothly follow where I drag the pointer.
### Actual behavior
Pointer moves erratically most of the time.
### Device information
Lenovo k8 note 
* Android device: Android 
* Fenix version : 2.1.0 (Build #12821601)
📦: 14.0.1, 81385d712
🦎: 70.0-20190923100040.      

Issue doesn't occur in Firefox for Android, Chrome or any other app. It is exclusive with Firefox preview.  
If my description isn't clear enough, do say so. I'll add a video.

**Comment by makotokato** [comment]
> 🦎: 70.0-20190923100040.

@Sgt-Miller could you update to the latest version of Fenix from Google Play store? I guess that this issue is https://github.com/mozilla-mobile/fenix/issues/5037.

**Comment by Sgt-Miller** [comment]
@makotokato thank you, update fixed this.
