### ISSUE TITLE
[Bug] Beta round icon is square

### ISSUE THREAD

**Issue by NotWoods** [mozilla-mobile/fenix#6255]
Related to #2059. The roundIcon asset in fenixBeta needs to be switched with a round image.

[Icon assets](https://github.com/mozilla-mobile/fenix/files/3579368/firefox-preview-beta-launcher.zip)

**Comment by daphliu** [comment]
I would like to take on this!

**Comment by sv-ohorvath** [comment]
@NotWoods @daphliu I can't build a beta version locally due to this error: https://www.screencast.com/t/r2yJWWBZ

**Comment by pfieffer** [comment]
@sv-ohorvath Like the error suggests, you can not use **-** (hyphen character) in your resource name. You have named the icon `ic_launcher-round`. It should have been `ic_launcher_round`

**Comment by sv-ohorvath** [comment]
> @sv-ohorvath Like the error suggests, you can not use **-** (hyphen character) in your resource name. You have named the icon `ic_launcher-round`. It should have been `ic_launcher_round`

I didn't do that :)  I'm just trying to build the apk to test this and this is blocking me.

**Comment by NotWoods** [comment]
Whoops, looks like the files in the zip had the wrong naming. I'll follow up and fix the file names.

**Comment by sv-ohorvath** [comment]
@NotWoods I installed the beta app on a Nexus 5, API 22 emulator and the launcher icon is still square, same for Nightly. https://www.screencast.com/t/kLuLJ7AxHIRZ
What am I doing wrong?

**Comment by NotWoods** [comment]
@sv-ohorvath Round icons only appear on Android 7.1

**Comment by sv-ohorvath** [comment]
@NotWoods This is from a Nokia 6 (Android 7.1.1)
![Screenshot_20191120-144711](https://user-images.githubusercontent.com/4037709/69240279-c8d27800-0ba4-11ea-8e35-131ec14fd5e7.png)

**Comment by NotWoods** [comment]
Can you test on a Pixel device with Android 7.1? It seems that round icons are dependent on the manufacturer, as nightly is also displayed with a square icon here. I know that Pixels use round icons but I'm not sure what other phones do.

**Comment by sv-ohorvath** [comment]
> Can you test on a Pixel device with Android 7.1? It seems that round icons are dependent on the manufacturer, as nightly is also displayed with a square icon here. I know that Pixels use round icons but I'm not sure what other phones do.

Pixel with 7.1 has a round icon. @NotWoods I'll close this if that's all.
