### ISSUE TITLE
Collections Product Quality - gradient

### ISSUE THREAD

**Issue by lime124** [mozilla-mobile/fenix#6263]
Pulling from the checklist here: #2896

Need a gradient background on top and bottom to remove hard edge when scrolling through tabs. See bottom of spec image for implementation details. 

![image](https://user-images.githubusercontent.com/287322/67527048-e3c7d000-f66a-11e9-81e2-c3924b1ee06e.png)

**Comment by lime124** [comment]
@AmyYLee can you confirm this is still relevant and the information is still correct?  thanks!

**Comment by lime124** [comment]
once this has been confirmed by amy, does this have any dependencies? can this by picked up by a contributor?

**Comment by NotWoods** [comment]
This can be picked up by a contributor, I'm pretty sure there's no dependencies.

**Comment by AmyYLee** [comment]
> @AmyYLee can you confirm this is still relevant and the information is still correct? thanks!

Yes! This is still relevant.

**Comment by matthewcmckenna** [comment]
I'd like to take on this task!

Is there a dp equivalent of 102px that can be used for the height of the gradient?

**Comment by NotWoods** [comment]
Try 102dp and see how it goes, possibly divided by 2

**Comment by matthewcmckenna** [comment]
Alright, will do. I'll post some images for comparison as well later today.

**Comment by gabrielluong** [comment]
I was also working on this a couple of days ago. In case this is useful in anyway you can reference my approach in https://github.com/gabrielluong/fenix/commit/4e88a952b1048f521bd2e4f9bc7f8f8603991b1d. 

Other than that I wanted to add the spec for the top gradient that I got from @AmyYLee on slack:
0E0D1A 12% Opacity
Blur 1, offset 1

**Comment by liuche** [comment]
unassigning for inactivity

**Comment by liuche** [comment]
sorry for the churn! I didn't see the PR, and was trying to clear up some issues for new contributors.

**Comment by softvision-miralobontiu** [comment]
Verified as fixed with the latest Nightly build from 11/26 with Huawei MediaPad M2 (Android 5.1.1), and Samsung Galaxy Note 8 (Android 9).

![Screenshot_20191126-112345_Firefox Nightly](https://user-images.githubusercontent.com/40694158/69618416-88f70f00-1042-11ea-8697-355f65d8896a.jpg)
