### ISSUE TITLE
[Bug]"Search with" and "Search or enter address" strings improperly positioned in RTL 

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#6269]
## Prerequisites
Have RTL enabled in Developer options

## Steps to reproduce
1. Tap on the search bar
2. Check the position of the "Search or enter address" from the search bar
3. "Search with" above the search shortcuts

### Expected behavior
Should be properly positioned 

### Actual behavior
"Search or enter address" string to close to the left edge of the search box
"Search with" to close to the right edge of the display

### Device information

* Android device: 
• Google Pixel 3a XL (Android 9)
• Samsung Galaxy Note 9 (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• LG Nexus 4 (Android 5.1.1)

* Fenix version:  Nightly Build #12980627 from 25/10

### Notes
Related to #5497 

![rsz_rsz_screenshot_20191025-143102](https://user-images.githubusercontent.com/51314259/67572721-72a61c80-f73f-11e9-8e2b-b9f4799b40d8.png)

![rsz_1rsz_screenshot_20191025-143102](https://user-images.githubusercontent.com/51314259/67572922-de888500-f73f-11e9-8228-a50837b97c73.png)

**Comment by brampitoyo** [comment]
Thanks for reporting, @AndiAJ. You’re right that this is a bug.

We also know exactly what to do in order to fix this issue. The amount of padding should be identical to the padding on LTR layout.

**Comment by AndiAJ** [comment]
Hi, check on the latest **Nightly Build #13110606 from 7/11** using the following devices:
• Google Pixel 3a XL (Android 9)
• Samsung Galaxy S7 (Android 7)
• LG Nexus 4 (Android 5.1.1)

1. "Search with" ✔️
![rsz_screenshot_20191107-105819](https://user-images.githubusercontent.com/51314259/68375020-b12fd400-014e-11ea-8640-26fc950ce11b.png)
![rsz_screenshot_20191107-105719](https://user-images.githubusercontent.com/51314259/68375120-e63c2680-014e-11ea-8fce-76566b7d6c8c.png)

2.  "Search or enter address" ❌
![rsz_1screenshot_20191107-105819](https://user-images.githubusercontent.com/51314259/68375367-65c9f580-014f-11ea-9d8e-0943da909b61.png)
![rsz_1screenshot_20191107-105719](https://user-images.githubusercontent.com/51314259/68375274-3a470b00-014f-11ea-83f2-0751a2f3974e.png)

@BranescuMihai - I would kindly ask you to review the remaining issue. 😊
I'll remove the QA needed label until further clarifications.

**Comment by mcarare** [comment]
waiting on https://github.com/mozilla-mobile/android-components/issues/4907

**Comment by darkwing** [comment]
@BranescuMihai How is this coming along?  Any update you can provide?

**Comment by darkwing** [comment]
Hello @BranescuMihai!  I see you have a PR merged in AC but I'm seeing this in Fenix today:

![Screenshot_20200224-221821](https://user-images.githubusercontent.com/46655/75197547-21755c00-5724-11ea-8043-304fe7594f8d.png)

Should this be part of your AC patch?  Anything more we need to do on our side?

**Comment by BranescuMihai** [comment]
@darkwing I think that is the expected UI. If you're on a language with no translation for 'Search or enter address' string, it will show up in English, but now it has some padding.

**Comment by Diana-Rus** [comment]
Hi, for "Search or enter address"- the padding looks good verified as fixed on Firefox Preview Nightly 200325 (Build #20850608) GV: 76.0a1-20200323092419 with:
**RTL:**
- Google Pixel 3 XL (Android 9)
![Screenshot_20200325-150811-Pixel](https://user-images.githubusercontent.com/49859863/77541345-3b35ca80-6ead-11ea-84ef-50a523c37d32.png)

- Samsung Galaxy S9 (Android 8)
![20200325_140423](https://user-images.githubusercontent.com/49859863/77542815-720ce000-6eaf-11ea-8cbb-81164c7cdb04.jpg)

- Sony Xperia Z5 (Android 7)

The issue has been verified:
- in Normal mode
- in Private mode
- and with Dark theme applied
