### ISSUE TITLE
[Meta] Web Content Dark Mode

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/fenix#627]
### Why/User Benefit/User Problem

Users want a dark mode that changes web page contents and will switch browsers to get it. 

See: 

* https://9to5google.com/2019/02/19/android-chrome-webview-web-dark-mode/ 
* and responses in https://www.reddit.com/r/Android/comments/asi470/dark_mode_in_chrome_for_android_will_also_darken/

### What / Requirements

* Option in Fenix UI to change page contents to dark mode. 
* Ideally, it would use prefers [color scheme ](https://bugzilla.mozilla.org/show_bug.cgi?id=1494034)
* falling back to something closer to provided by [Dark Background and Light Text](https://addons.mozilla.org/en-US/firefox/addon/dark-background-light-text/) or the modes in Kiwi or Samsung browsers

### Acceptance Criteria (how do I know when I’m done?)

User can select a enable "night mode" in settings and have page contents changed based on this preference.

May be a dupe of #252 - unclear whether that is for theming or page contents.

This is possibly being introduced in Chrome: https://chromium-review.googlesource.com/c/chromium/src/+/1478106

**Comment by DiegoARL38** [comment]
I was thinking about requesting this as an accessibility feature. In desktop Firefox, if a high-contrast theme is active on Windows, Firefox acts accordingly and displays web content in high contrast. Since Android doesn't provide this option, an add-on is needed to emulate the feature in current Firefox for Android, which generates some quite inconvenient disadvantages...

**Comment by cpeterso** [comment]
GeckoView will need a new API for Fenix's dark mode setting to tell Gecko to enable CSS dark mode:
https://bugzilla.mozilla.org/show_bug.cgi?id=1529972

**Comment by bbinto** [comment]
As per [comment](https://github.com/mozilla-mobile/fenix/issues/240#issuecomment-473414507), we might pull this back into a Battery saving story after MVP.

Out of scope for MVP.

**Comment by ekager** [comment]
We are now using the PreferredColorScheme feature in GV when in Fenix dark mode. Is there an action item for this bullet?
- falling back to something closer to provided by Dark Background and Light Text or the modes in Kiwi or Samsung browsers

**Comment by ekager** [comment]
A good website to test the reactive dark theme in action is https://kevinchen.co/blog/support-macos-mojave-dark-mode-on-websites/

**Comment by kbrosnan** [comment]
This is complete. Opening a feature request for forcing a dark mode as #2139.
