### ISSUE TITLE
[Bug] No Search Shortcuts shown if tap on URL

### ISSUE THREAD

**Issue by Cheap-Skate** [mozilla-mobile/fenix#6284]
## Steps to reproduce

Open a new tab
The Search screen shows a blank text box and a list of search shortcuts ie **the Shortcuts button is depressed**
(expected behavior)

Instead
Navigate to any URL
Tap the URL to enter the Search screen
Search shortcuts are **not** shown ie **the Shortcuts button is NOT depressed**  <<< NOT EXPECTED

Tap the "Shortcuts" button
The "SEARCH WITH" text appears but **the list of Search Shortcuts is empty**  << NOT EXPECTED

### Expected behavior

IMHO the behavior should always be the same however I enter the Search screen
- the Shortcuts button should always be depressed, and
- the correct list of search shortcuts should always be shown until I start typing

### Device information

* Android device: Galaxy S7
* Fenix version: Today's

(I'll say it again, I think the Shortcuts button is a kludge, it's weird to move to a screen where a button is depressed by default but un-depresses itself when I start typing. I find it weird & confusing.)

**Comment by softvision-miralobontiu** [comment]
Verified as fixed on the latest Nightly build 11/07 (#13110607) with Nexus 9 tablet (Android 7.1.1), Nexus 5 (Android 6.0.1), Google Pixel (Android Q), and OnePlus 5T (Android 9).

**Comment by Cheap-Skate** [comment]
Not completely fixed for me on Fenix 191108 18:00 build #13121810 on Galaxy S7 Android 9.0.0. 

Tap the URL to enter the Search screen
Search shortcuts are not shown ie **the Shortcuts button is NOT depressed** <<< NOT EXPECTED & STILL BROKEN

Tap the "Shortcuts" button
The "SEARCH WITH" text appears, **the list of Search Shortcuts is populated** << EXPECTED & FIXED

**Comment by sblatz** [comment]
> Search shortcuts are not shown ie the Shortcuts button is NOT depressed <<< NOT EXPECTED & STILL BROKEN

I believe this is the expected behavior. We only want to show the search shortcuts by default when going from Home -> Search:

https://github.com/mozilla-mobile/fenix/issues/4736

**Comment by Cheap-Skate** [comment]
Weird. But then, Fenix is pretty weird all round. 

I just tap on the bar at the bottom of the screen when I want to search. Sometimes I get search shortcuts, sometimes I don't, depending on a fairly obscure context in which I do the tap. Same gray bar, same Google favicon, same position on screen, same tap, different outcome.

But I wonder if all this Search Shortcuts stuff changes radically when Top Sites comes along, so I'll wait and see.

cheers

**Comment by Cheap-Skate** [comment]
A more useful comment:-

Perhaps you guys at Mozilla see a much stronger distinction between the Home page (with the Firefox logo) and a normal Tab page than Joe Averageuser (me). If that were true it would explain why you see it as OK to have "special" behaviors from Home (Firefox logo) page e.g. 
- showing the Search shortcuts (or not) when tapping the gray bar with the Google logo
- back button takes me out of Fenix to my Android Home screen.

I suspect that Joe Averageuser doesn't see such a strong distinction, they're used to spending time in a Tab and using the Home screen as a tab switcher. Joe Averageuser might instead think
- the gray bar with the Google logo is always a search bar, it should always do the same thing regardless of the context in which I tap it, Search shortcuts should always be shown, or not
- the back button should undo my last action e.g. take me from the Home page back to tab from which I entered it (#2484)

You might be able to educate J. Averageuser to the special behaviors but you might just cheese them off??
