### ISSUE TITLE
[Bug]Back button works inconsistently in Search screen

### ISSUE THREAD

**Issue by Cheap-Skate** [mozilla-mobile/fenix#6285]
## Steps to reproduce

Close all tabs
Kill Fenix
Relaunch Fenix
Open a new tab
navigate to mozilla.org & wait for it to load
tap the URL bar to move to the Search screen
enter a Google search phrase e.g. "cheese" and hit enter
Get a page of Google search results for cheese
Tap the URL bar to move to the Search screen
The Search text box contains the search term "cheese"
Tap the Android "Back" button
Sometimes (not always) **the browser loads mozilla.org** <<< NOT EXPECTED

Then
Tap the URL (mozilla.org) to move to the Search screen
Sometimes (not always) **the text "cheese" appears in the URL bar** <<< NOT EXPECTED 

### Expected behavior

- The Android "Back" button should return me to where I came from i.e. to the page of Google search results for "cheese", and
- tapping on a URL should always show the URL in the Search text field, not a previously entered search term

### Actual behavior

I see the NOT EXPECTED behavior more than half the time, but not always.

I can usually force the NOT EXPECTED behavior by, on the Google search results page, repeatedly tapping the URL to show "cheese" in the search box then tapping Android "Back" to go to the Google search results page. Eventually it fails to go to the Google search results page and instead goes back to mozilla.org.

(I'm happy to fiddle around to get better STR if you can't see it)

### Device information

* Android device: Galaxy S7
* Fenix version: Today's

**Comment by ekager** [comment]
This sounds like it will be fixed by #11871

**Comment by ekager** [comment]
Closing for #11866
