### ISSUE TITLE
[Bug] Can't double tap 3 dot menu to reload page because reload icon is offset horizontally

### ISSUE THREAD

**Issue by Cheap-Skate** [mozilla-mobile/fenix#6291]
## Steps to reproduce

Tap 3 dot menu with index finger
Without moving your finger, tap again as though to reload
It usually doesn't work, the reload icon is offset too far to the left & a bit upwards
Have to move your finger to the left or mash a big area with your thumb

(details probably depend on your finger size & phone screen width)

### Expected behavior

Should always be able to tap-tap same point on the screen to get a reload without moving finger between taps.  3 dot icon and reload icon should overlap more.

Fennec does it better, the 3 dot and reload icons overlap almost perfectly & a tap-tap on 3 dot menu always works for me.

### Device information

* Android device: Galaxy S7
* Fenix version: Today's

**Comment by topotropic** [comment]
https://share.goabstract.com/a5d9621b-02f7-4630-8606-f277664a7688?mode=build&sha=da46a88094f3d52d2808be3c1968ed80507258a8

Please see above file and update the margins to match it. This should address the issue described here.

**Comment by mcarare** [comment]
@Cheap-Skate I have recently made some changes that increased the touch target for those action buttons. Can you please retest and let us know if this is still an issue for you? Thank you!

**Comment by Cheap-Skate** [comment]
Maybe it's better.... a little?

(I am probably still biased by the fact that the 3 dot menu & reload/stop icons are significantly displaced from each other. Which I dislike on principle!)

**Comment by mcarare** [comment]
@Cheap-Skate based on your comment I will close this. Note that the menu could never completely overlap it's anchor, IMO this is not expected or desired. The question was if you can easily complete your described action. Please feel free to reopen this if you feel this could be further improved. Thank you for your feedback!
