### ISSUE TITLE
Copy and paste text in Facebook Post

### ISSUE THREAD

**Issue by yamamashakaa** [mozilla-mobile/fenix#6292]
## Steps to reproduce
Open Firefox preview
open Facebook.com and log in
open click on the post to fully open it
Press and hold on a text 

### Expected behavior
A menu that contains (select all, copy, past , cut) should appear.
Like the one appear on other websites.
(Attached photo)
![Fenix](https://user-images.githubusercontent.com/16443315/67631300-f6295000-f89c-11e9-8c60-8e3de27aebad.jpg)

### Actual behavior
Nothing happens. And I did not find a way to copy text from posts or coments
### Device information
* Android device: ?
Hawaii Android version 9
* Fenix version: ?
70-0-20191007080030

**Comment by sflorean** [comment]
@yamamashakaa this is still reproducible for you? Thank you! Tested on Twitter and couldn't reproduce it.
