### ISSUE TITLE
[Bug] Single tab doesn't get saved to collections

### ISSUE THREAD

**Issue by liuche** [mozilla-mobile/fenix#6294]
## Steps to reproduce
Open 1 tab
Click "Save to Collection"
Either create new collection or add to existing collection (doesn't matter)

### Expected behavior
Tab is saved to collection

### Actual behavior
Tab is not saved to collection

### Device information

* Android device: ?
* Fenix version: ?

**Comment by AndiAJ** [comment]
Hi, verified as fixed on both **Fenix v2.3.0-rc.2** and latest **Nightly Build #13030619 from 30/10** using the following devices:
• Google Pixel 3a XL (Android 9)
• Samsung Galaxy Note 9 (Android 8.1.0)
• Huawei MediaPad M3 Lite 10 (Android 7)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

► Video
![20191030_105637](https://user-images.githubusercontent.com/51314259/67844387-540ca080-fb06-11e9-80b4-38e37c28cbb1.gif)
