### ISSUE TITLE
Can't bypass TLS 1.0/1.1 error as in Desktop

### ISSUE THREAD

**Issue by julienw** [mozilla-mobile/fenix#6296]
### Why/User Benefit/User Problem
STR is:
1. Go to https://www.lesfruitsetlegumesfrais.com/

=> In Fenix, there's a generic error that we can't bypass (this is #4273).

However in Desktop we see what the error is specifically: `SSL_ERROR_UNSUPPORTED_VERSION`, along with an explanation that TLS 1.0 and 11 are disabled, and we can enable them if we want.

I filed this separately from #4273 because this seems slightly different.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-14144)

**Comment by julienw** [comment]
This happens in https://forge.univ-artois.fr as well.

**Comment by NotWoods** [comment]
Related: #1168

**Comment by jcristau** [comment]
This is super confusing as there's a generic "certificate issuer is unknown, the certificate is self-signed, or the server is not sending the correct intermediate certificates" message (none of those options are true), and there's a "accept the risk and continue" button that does not actually do anything.

**Comment by andreasbovens** [comment]
@vesta0 putting this on your radar.

**Comment by fluffyemily** [comment]
This would need GeckoView work to expose the correct prefs to consumers. Then Fenix will need to do some work to hook up their TLS error page to the GV API.

**Comment by liuche** [comment]
Chatted with @fluffyemily, this my require no UX work if in involves using an existing(?) TLS error page.

**Comment by krystian3w** [comment]
No need in 79 (completly disable tls 1.0 & 1.1)?

**Comment by evilpie** [comment]
This still seems to be happening: https://www.reddit.com/r/firefox/comments/j9qsxt/pressing_the_bottom_2_buttons_does_nothing_have/

Can also use https://tls-v1-0.badssl.com:1010/ for testing.

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813241

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
