### ISSUE TITLE
Collections should be live/dynamic and should not need to be stored again to update

### ISSUE THREAD

**Issue by madb1lly** [mozilla-mobile/fenix#6298]
### Why/User Benefit/User Problem
My main problem with collections at present is that I cannot work within them; they are not "live". If I open a collection and use it then the collection doesn't remember what I've done. If I save the resulting set of tabs it is saved as a new collection, not as an update to an existing collection, so I need to save and then delete my old collection. This is a cumbersome way to work with this generally good idea.

### What/Requirements
Rather than them being snapshots of a current tab set they need to be live, or dynamic. i.e if I work within a collection, navigate tabs to new pages, open links in new tabs, close tabs etc, the collection should remember this. When I've finished (or run out of time!) I should not need to save the tabs back to a collection, the collection should just remember where I was. This is how I expected the old sessions concept to work. 

Another way of thinking about this is to think of each collection as a separate firefox device. When I close my browser it remembers my tabs state; I want my collections to remember my tabs state when I close them.

### Acceptance Criteria (how do I know when I’m done?)
I think the last paragraph captures my vision best. Ultimately I just want collections to be less cumbersome to use as they have a lot of potential.

Cheers :)

PS - I've looked at a _lot_ of issues but didn't see one which was like this one, but if there is one then please mark mine as duplicate and link. :)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-14145)

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812758

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
