### ISSUE TITLE
New tab could create a new collection/session

### ISSUE THREAD

**Issue by madb1lly** [mozilla-mobile/fenix#6299]
Summary: When a new tab is opened, start it in a new collection. Note I know this doesn't fit the current workflow.

### Why/User Benefit/User Problem
I've been struggling to understand the real benefit of collections, mainly because of how they're implemented. The concept of sessions was clearer to me (even if the implementation is the same) - I start a new session on a new topic, open links in new tabs, surf, see where I end up, but all tabs which are opened are still part of that session because they are part of that topic.

If I open a new tab without following a link then it will probably (possibly? that's for telemetry and surveys to tell you) be unrelated to the current "session" and can therefore be kept separate.

Note I know that my last assumption is not always the case, but for me it often is.

### What/Requirements
First I think that the current workflow for collections needs to change: #6298 

When I open a new tab I want it to open in a new session/collection and preserve the state of my existing session/collection so I can come back to it later.

Probably this behaviour should be optional as it's a big change from the way that all (?) browsers currently work.

### Acceptance Criteria (how do I know when I’m done?)
When collections are dynamic snapshots of a browsing session (rather than just static collections of bookmarks) and it's easy to create new sessions on new topics and come back to the previous session later.

Cheers :)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-14146)

**Comment by tukusejssirs** [comment]
Alternatively, I would be happy if there would be a button near the location/URL bar to create a new collection AND a possibility to use collections as tab groups, i.e. users could _open_ tabs _in_ a collection (as opposed to _adding_ tabs to a collection, which is currently the only option to add a tab into a collection).

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812757

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
