### ISSUE TITLE
Improve quality of tabs

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#630]
Currently the tabs border just becomes white when a tab is not selected. This makes the tab look taller than the "selected" tab. We should instead not have any border. 

![image](https://user-images.githubusercontent.com/4400286/53203012-d5f21480-35dc-11e9-93f2-628ee0ee1450.png)

**Comment by bsurd** [comment]
With the new design, there is a clear distinction between different tabs with all of them having the same size. 

Verified on:
 - 1.0.1910 (Build #10642115)

 Devices:
 - Nokia 6 (Android 7.1.1)
 - HTC Desire 820 (Android 6.0.1)
