### ISSUE TITLE
What's New Entry for 3.0

### ISSUE THREAD

**Issue by Baron-Severin** [mozilla-mobile/fenix#6300]
This ticket tracks work for the SUMO page and Google Play release notes.

**Comment by liuche** [comment]
(Tentative release date: Nov 12)

Welcome to Firefox Preview 3.0. This release comes with the following features to make browsing and bookmarking safer and easier:

Enhanced Tracking Protection protects you from ad, analytics, cryptomining and fingerprinting trackers. 
Open links in private tabs by default
Option to clear browsing information on exit
Choose what types of browsing information to sync across devices
Set an autoplay or background behavior for playing audio/video (ENG to confirm if this will ship in 3.0)

NEW:

New system download notifications 
We are removing Quick Action Bar and revising the browser menu (confirm with ENG if this will ship in 3.0)
Remove existing article on Quick Action Bar
Update existing article on how to bookmark a page 
Update existing article on how to access Reader Mode)
Update existing article on what the browser menu looks like
Add more search engines 
Choose to move your nav bar to the top
Force enable zoom (doesn’t need separate article)

**Comment by liuche** [comment]
Sent a confirmation to SUMO that the items on their list of what is shipping looks good (their articles have been completed for a while now).
