### ISSUE TITLE
Web Notification Channel Name

### ISSUE THREAD

**Issue by rocketsroger** [mozilla-mobile/fenix#6303]
### Why/User Benefit/User Problem
Current A-C implementation is using "Site notifications" as the notification channel name for any web notification coming from websites.

### What/Requirements
Need approved string for the notification channel name.

### Acceptance Criteria (how do I know when I’m done.
Have the approved string so it can be updated through A-C.

**Comment by rocketsroger** [comment]
![device-2019-10-28-144842](https://user-images.githubusercontent.com/6579541/67708779-1c311c00-f993-11e9-8584-30cb4b009be8.png)

**Comment by rocketsroger** [comment]
@mheubusch Thanks!

**Comment by mheubusch** [comment]
Site notifications is approved. Thanks, @rocketsroger

**Comment by rocketsroger** [comment]
Thanks, I'll close this issue.

**Comment by rocketsroger** [comment]
This is implemented in https://github.com/mozilla-mobile/android-components/pull/4768
