### ISSUE TITLE
Session UI on home view

### ISSUE THREAD

**Issue by boek** [mozilla-mobile/fenix#631]
Parent #111

Questions for UX:
- Do we show `n` number of recent sessions, or a time range?

**Comment by yoasif** [comment]
Automatically disappearing/deleting sessions sounds like a bad idea.

Unless you are talking about showing a few and then a "see more..." link or something. But destroying a session after saving it would be bad, imo.

**Comment by boek** [comment]
@yoasif I’m not sure I quite understand. I believe the current idea is to only show a recent subset of your overall session list with a button at the end to view all sessions which would I assume take you to the “Session” list in your library.

**Comment by yoasif** [comment]
Yep, sorry -- missed the "View all sessions (could be elapsed shown general history)" bullet in  #111 
Ignore my last comment.
