### ISSUE TITLE
Add search engine by long-press in search text entry box (opensearch)

### ISSUE THREAD

**Issue by madb1lly** [mozilla-mobile/fenix#6315]
### Why/User Benefit/User Problem
Currently on Fennec a search engine can be added by long-pressing in the search engine webpage's text entry box:

1. Go to search engine's page
2. Select the text input box
3. Long press
4. Press on "Add search engine" in the pop-up menu.

And the engine is added to the list in settings and options to use whenever typing in the address bar.

### What/Requirements
Add this feature to Fenix.

### Acceptance Criteria (how do I know when I’m done?)
Can add supported search engines to Fenix by this method. Note that not all search engines support this, as noted here: https://github.com/mozilla-mobile/fenix/issues/5577#issuecomment-547187644.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-14160)

**Comment by critical-bug** [comment]
I've been using this feature in Fennec to add Japanese ebook sites.

**Comment by madb1lly** [comment]
Hi all,
I don't think this is on any project backlog yet nor is it marked for Fennec parity.
Cheers 🙂

**Comment by return42** [comment]
Hi, I am one of the maintainer of [SearXNG](https://github.com/searxng/searxng) (a metasearch engine), we do support the [OpenSearchDescription](https://developer.mozilla.org/en-US/docs/Web/OpenSearch) in our [templating](https://github.com/searxng/searxng/blob/master/searx/templates/__common__/opensearch.xml) (including autocompletion what matters most IMO).

I wanted to ask if there is a chance to get [Autodiscovery of search plugins](https://developer.mozilla.org/en-US/docs/Web/OpenSearch#autodiscovery_of_search_plugins) into Firefox for Android like we know from Firefox for Desktop, Chrome and other browser.

Any informations on this topic are welcome ... if I can help in any matter, don't hesitate too ask for.  Thanks for paying attention on ..

**Comment by return42** [comment]
@Amejia481, @MickeyMoz, @Mugurell .. does anyone of you know if it is possible to support [Autodiscovery of search plugins](https://developer.mozilla.org/en-US/docs/Web/OpenSearch#autodiscovery_of_search_plugins)? (see https://github.com/mozilla-mobile/fenix/issues/6315#issuecomment-929117425). I am grateful for any advice, even if it is only that it is not possible in the near future ..

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813240

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
