### ISSUE TITLE
[Bug] - UI design - rationalise different kinds of pop up menu 

### ISSUE THREAD

**Issue by Cheap-Skate** [mozilla-mobile/fenix#6316]
When tapping Fenix buttons I can get one of three different kinds of menu appearing

1. Android floating menu about 2/3 screen width with underlying content normal brightness (3 dot menu button), or
2. full screen width "windowshade" up from bottom of screen with underlying content dimmed (shield, padlock buttons), or
3. list of inline text (Shortcuts button)

Nit picks but I find it inelegant, particularly the difference between types 1 and 2.

I know you are working to rationalise the QAB and 3-dot menu e.g. #4281 and #6310, would it be worth rationalising the three different kinds of menus particularly 1 and 2?

Advantages

- more width to put the icons which are currently in the QAB horizontally at the bottom of the 3 dot menu, if that's the way you want to go, maybe could put Open In App, Reader, Share, Bookmark, Back, Forward, Reload across bottom of 3 dot menu whole screen width???

- it would help with #6291 because Reload icon would be pushed to bottom right corner of screen and would overlay 3 dot menu icon.

- more consistency between menu types looks a nicer IMHO

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-14161)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1809228

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
