### ISSUE TITLE
[Bug]- nit - font size differences between menus a bit inelegant

### ISSUE THREAD

**Issue by Cheap-Skate** [mozilla-mobile/fenix#6317]
3 dot menu uses a fairly big font, Android system size I guess

BUT Tracking Protection (Shield) menu uses a mix of that font size and a smaller one, and Security (Padlock) menu uses just the smaller font size

I find the difference a bit jarring between menus and within menus, in particular

- the URL is in the smaller font size but the Enhanced Tracking Protection button is in the larger font size
- the Protection Settings shortcut with its gearwheel at the bottom of the Enhanced Tracking Protection menu is in a different font size to the normal Settings gearwheel menu item in the 3 dot menu
- the smaller menu font size is (obviously) harder to see, particularly for us with less than perfect vision.

Fenix seems to have plenty of screen real estate in the Tracking Protection and Security windowshade menus, is there any particular problem with using the system font size throughout? I think there is enough indentation to show what is subordinate text in the various lists (eg of tracker types)

**Comment by AmyYLee** [comment]
Hi, 

@boek Here are some adjustments to the font sizes and padding to have this more consistent. Let me know if you have any questions. 

![Screen Shot 2020-01-20 at 5 07 07 PM](https://user-images.githubusercontent.com/5992746/72760720-bc1fcf80-3ba7-11ea-971c-3e2e036c181a.png)

**Comment by softvision-miralobontiu** [comment]
Verified as fixed on the latest Nightly build from 3/24, and on Beta 4.2.0-beta.1, with OnePlus 5T (Android 9), and on Sony Xperia Z5 Premium (Android 7.1.1).
