### ISSUE TITLE
[Bug]Saving only one tab to a collection creates an empty collection

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#6318]
## Prerequisites
Have only one open tab. 

## Steps to reproduce
1. Tap on the "Save to collection" button
2. Create and save the tab to a collection
3. From the "Open tabs" section tap on the 3dot button and tap on "Save to collection"
4. Create a new collection and save the tab
 
### Expected behavior
The tab should disappear from the open tabs section and the created collection should contain the desired tab.

### Actual behavior
Empty collections are created and the tab isn't removed from the open tabs section.

### Device information

* Android device:  
Samsung Galaxy Tab A (Android 9)

* Fenix version: 
• 2.3.0-rc.1 from 28/10
• Nightly #13020608 from 29/10

### Notes
► Video
![20191029_120128](https://user-images.githubusercontent.com/51314259/67759049-6f64a680-fa47-11e9-8dcb-2fdc60fad37e.gif)

**Comment by liuche** [comment]
Ah I have a PR for this in this issue #6294
