### ISSUE TITLE
Automatically archive your current session

### ISSUE THREAD

**Issue by boek** [mozilla-mobile/fenix#632]
Parent #111

**Comment by pocmo** [comment]
I recently landed `autoClose` support, is that what you are looking for here?
https://mozac.org/api/mozilla.components.feature.session.bundling/-session-bundle-storage/auto-close.html

**Comment by boek** [comment]
@pocmo This was just a reminder of a piece of work that needs to be done. But I will definitely use autoClose as well

**Comment by boek** [comment]
Fixed with ` [c0340f5](/mozilla-mobile/fenix/pull/707/commits/c0340f5a07db8afa2bbe10fd056004935c98f9ab)`
