### ISSUE TITLE
[Bug] Incorrect flow for creating first collection from a tab

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#6323]
## Steps to reproduce
1. Make sure there is no existing collection, go to a website.
2. Open the menu and go to Save to collection.
### Expected behavior
When there's no collection, the Select collection screen is skipped and the creation of Collection 1 is shown by default.
### Actual behavior
An empty Select Collection screen is displayed.
### Device information

* Android device: Sony Xperia Z5 Premium (Android 7.1.1), Xiaomi Mi Pad 2 (Android 5.1)
* Fenix version: RC 2.3.0

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **Nightly Build #13250607 from 11/21** using the following devices:
• Google Pixel 3a XL (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

► Video
![20191121_102602](https://user-images.githubusercontent.com/51314259/69320596-25d43980-0c4a-11ea-9b58-df0b46da215e.gif)
