### ISSUE TITLE
[Bug]Tracking protection not working

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#6325]
## Prerequisites
Have tracking protection turned on globally and set to Strict mode

## Steps to reproduce
1. Navigate to https://mozilla.github.io/tracking-test/ads.html
2. Navigate to https://senglehardt.com/test/trackingprotection/test_pages/ and select one by one the featured test pages. 

### Expected behavior
For 1. Confirmation that advertising resources are blocked should be displayed.
For 2. Having ETP set to Strict a confirmation saying Blocked on each test webpage  

### Actual behavior
For 1. Advertising resources are not blocked.
For 2. Only the Referrer Policy test page is blocked  

### Device information

* Android device: 
Samsung Galaxy Tab A (Android 9)

* Fenix version: 
• 2.3.0-rc.1 from 28/10
• Nightly #13020608 from 29/10

### Notes

►Video 1. https://mozilla.github.io/tracking-test/ads.html
![20191029_145156](https://user-images.githubusercontent.com/51314259/67769030-63371400-fa5c-11e9-935e-abd581384934.gif)

►Video 2. https://senglehardt.com/test/trackingprotection/test_pages/
![20191029_154634](https://user-images.githubusercontent.com/51314259/67773215-0b041000-fa64-11e9-9d39-009b114e81b9.gif)

**Comment by Amejia481** [comment]
Thanks for the report I'm taking a look at!

**Comment by Amejia481** [comment]
I'm unable to reproduce the issue on `releases/v2.3 `branch? Could please verify? In **standard** the tracker shouldn't be blocked but in **strict** the tracker must be blocked

**Comment by ekager** [comment]
@AndiAJ both of these videos are from Nightly it looks like? Because in v2.3 you shouldn't be able to see the TP shield in the toolbar.

**Comment by ekager** [comment]
This issue should be fixed for Nightly users with the next build since the AC changes were merged ~3 hours ago

**Comment by AndiAJ** [comment]
@ekager - Yes, indeed the videos were from the Nightly build.

Due to the fact that on RC builds the shield and the 2 ETP settings options (Standard & Strict) aren't displayed I wanted to highlight that while having it set to Strict nothing is blocked.

**Comment by Amejia481** [comment]
To see the fix Fenix nightly has to use `20.0.0-SNAPSHOT` as right now is using `19.0.0-SNAPSHOT`

**Comment by Amejia481** [comment]
Now, this should be fixed

**Comment by AndiAJ** [comment]
Hi, I've just checked on the latest **Nightly Build #13040608 from 31/10** using a Google Pixel 3a XL (Android 9) and noticed the following:

1. ✔️ https://mozilla.github.io/tracking-test/ads.html  
![20191031_143014](https://user-images.githubusercontent.com/51314259/67948726-0029b680-fbef-11e9-924f-a74ed5409485.gif)

2. ✔️ Checked ETP on different websites
![20191031_142613](https://user-images.githubusercontent.com/51314259/67948790-23ecfc80-fbef-11e9-9f92-556198b1870d.gif)

3.  ❓ https://senglehardt.com/test/trackingprotection/test_pages/
![20191031_150502](https://user-images.githubusercontent.com/51314259/67949884-3ff19d80-fbf1-11e9-9e1b-12d88096944b.gif)

**• Fingerprinting ONLY** ✔️

**• Cryptomining ONLY** ✔️    

**• Fingerprinting and Cryptomining** ✔️
 
**• Fingerprinting and Cryptomining and Trackers** ❓
Basic Tracking Protection List (base-track-digest256):
NOT BLOCKED

**• Fingerprinting and Cryptomining and Cookies** ✔️

**• Fingerprinting and Trackers** - ❓
Basic Tracking Protection List (base-track-digest256):
NOT BLOCKED

**• Cryptomining and Trackers** ❓
Basic Tracking Protection List (base-track-digest256):
NOT BLOCKED

**• Trackers and Cookies (Level 1 & Level 2)** ❓
Level 1 (Basic) List -- Combined
Level 1 Tracker blocking with combined list (base-track-digest256)
base-track-digest256:
NOT BLOCKED

Level 2 (Strict List) Tracker Blocking
content-track-digest256:
NOT BLOCKED

Cookie blocking
NOTE: If tracker blocking is enabled, these tests might not run
Level 1 (Basic) List -- Combined
* Advertising, Analytics, and Social - `base-track-digest256`: 
Cookies not blocked

**• Social Tracking Protection** ❓
Tracker blocking (social-tracking-protection-digest256)
NOT BLOCKED
Cookie blocking (social-tracking-protection-digest256)
Result: Cookies not blocked

**• Social Tracking Protection and Fingerprinting** ❓
STP Tracker blocking (social-tracking-protection-digest256)
NOT BLOCKED
STP Cookie blocking (social-tracking-protection-digest256)
Result: Cookies not blocked

**• Social Tracking Protection and Cryptomining** ❓
STP Tracker blocking (social-tracking-protection-digest256)
NOT BLOCKED
STP Cookie blocking (social-tracking-protection-digest256)
Result: Cookies not blocked

**• Social Tracking Protection and Fingerprinting and Cryptomining** ❓
STP Tracker blocking (social-tracking-protection-digest256)
NOT BLOCKED
STP Cookie blocking (social-tracking-protection-digest256)
Result: Cookies not blocked

@ekager , @Amejia481  -  As you can see there are some Trackers and cookies that are not blocked.
Could you please review? I'm not sure if they should/shouldn't be blocked.

**Comment by Amejia481** [comment]
I will send some print screens to clarify how each page should look like per tracking protection policy (**Standard** and **Strict**)

**Comment by Amejia481** [comment]
# Standard (We are only blocking cookies + CRYPTOMINING)

## Fingerprinting ONLY (We are not blocking Fingerprinting in Standard)
![Screenshot_20191031-094247](https://user-images.githubusercontent.com/773158/67951968-e70b1080-fbc2-11e9-959c-5f399583b897.png)

##  Cryptomining ONLY
![Screenshot_20191031-094437](https://user-images.githubusercontent.com/773158/67952111-25083480-fbc3-11e9-9e61-d3e3abc1b0e0.png)

##  Fingerprinting and Cryptomining (We are not blocking Fingerprinting in Standard)
![Screenshot_20191031-094652](https://user-images.githubusercontent.com/773158/67952332-892af880-fbc3-11e9-8bce-388aac68aeb2.png)

##  Fingerprinting and Cryptomining and Trackers (We are not blocking Fingerprinting in Standard)
![Screenshot_20191031-094919](https://user-images.githubusercontent.com/773158/67952570-e32bbe00-fbc3-11e9-8cc3-db41fa984057.png)

##  Fingerprinting and Cryptomining and Cookies (We are not blocking Fingerprinting in Standard)
![screenshot-1572533459769](https://user-images.githubusercontent.com/773158/67957854-9dbfbe80-fbcc-11e9-9acb-4cb5da8b67ff.jpg)

##  Fingerprinting and Trackers (We are not blocking Fingerprinting in Standard)
![screenshot-1572533778238](https://user-images.githubusercontent.com/773158/67958170-1888d980-fbcd-11e9-8511-e57a72007612.jpg)

##  Cryptomining and Trackers
![screenshot-1572533865707](https://user-images.githubusercontent.com/773158/67958261-4c63ff00-fbcd-11e9-9f37-d3610138255c.jpg)

##  Trackers and Cookies (Level 1 & Level 2)
![screenshot-1572533989022](https://user-images.githubusercontent.com/773158/67958435-94832180-fbcd-11e9-85d8-9e7b642f8d22.jpg)

![screenshot-1572534005319](https://user-images.githubusercontent.com/773158/67958505-a795f180-fbcd-11e9-9964-cd2ce9474fde.jpg)

##  Social Tracking Protection
![screenshot-1572534176818](https://user-images.githubusercontent.com/773158/67958742-09565b80-fbce-11e9-8708-745e5071fb9c.jpg)

##  Social Tracking Protection and Fingerprinting (We are not blocking Fingerprinting in Standard)
![screenshot-1572534239625](https://user-images.githubusercontent.com/773158/67958827-2a1eb100-fbce-11e9-859a-fa7157f9ec0e.jpg)

##  Social Tracking Protection and Cryptomining
![screenshot-1572534292612](https://user-images.githubusercontent.com/773158/67958895-4ae70680-fbce-11e9-96de-78da3142e398.jpg)

##  Social Tracking Protection and Fingerprinting and Cryptomining (We are not blocking Fingerprinting in Standard)
![screenshot-1572534385994](https://user-images.githubusercontent.com/773158/67959034-81248600-fbce-11e9-9989-1b37b19103fd.jpg)

**Comment by Amejia481** [comment]
# STRICT (We are  blocking content from loading + AD+ ANALYTICS+ SOCIAL + CRYPTOMINING+ FINGERPRINTING )

## Fingerprinting ONLY
![screenshot-1572535330550](https://user-images.githubusercontent.com/773158/67960472-b500ab00-fbd0-11e9-8aad-d1f4139cf12e.jpg)

##  Cryptomining ONLY
![screenshot-1572535408374](https://user-images.githubusercontent.com/773158/67960598-e9746700-fbd0-11e9-8294-b15ced9e96b7.jpg)

##  Fingerprinting and Cryptomining
![screenshot-1572535553903](https://user-images.githubusercontent.com/773158/67960836-3d7f4b80-fbd1-11e9-8333-f5490cfeedb1.jpg)

##  Fingerprinting and Cryptomining and Trackers
![screenshot-1572535674351](https://user-images.githubusercontent.com/773158/67961019-83d4aa80-fbd1-11e9-8137-aaf2466cee03.jpg)

##  Fingerprinting and Cryptomining and Cookies (We are not blocking Fingerprinting in Standard)
![screenshot-1572535793103](https://user-images.githubusercontent.com/773158/67961219-cac2a000-fbd1-11e9-8e9f-a2c240fb30e3.jpg)

##  Fingerprinting and Trackers 
![screenshot-1572535892029](https://user-images.githubusercontent.com/773158/67961370-02c9e300-fbd2-11e9-8353-80b7269ed8fc.jpg)


##  Cryptomining and Trackers
![screenshot-1572535990388](https://user-images.githubusercontent.com/773158/67961565-40c70700-fbd2-11e9-8863-00d2cd845dcc.jpg)


##  Trackers and Cookies (Level 1 & Level 2)
![screenshot-1572536185084](https://user-images.githubusercontent.com/773158/67961914-c2b73000-fbd2-11e9-92e1-6a76d2affb0b.jpg)
![screenshot-1572537022612](https://user-images.githubusercontent.com/773158/67963285-b9c75e00-fbd4-11e9-9722-c1e76a847d0e.jpg)


##  Social Tracking Protection
![screenshot-1572538278747](https://user-images.githubusercontent.com/773158/67964968-918d2e80-fbd7-11e9-93e0-567c591c4e62.jpg)


##  Social Tracking Protection and Fingerprinting 
![screenshot-1572538351516](https://user-images.githubusercontent.com/773158/67965100-c6998100-fbd7-11e9-8528-e3ec70377bcb.jpg)

##  Social Tracking Protection and Cryptomining
![screenshot-1572538423317](https://user-images.githubusercontent.com/773158/67965165-e761d680-fbd7-11e9-865c-705feab40298.jpg)

##  Social Tracking Protection and Fingerprinting and Cryptomining (We are not blocking Fingerprinting in Standard)

![screenshot-1572538074441](https://user-images.githubusercontent.com/773158/67964709-162b7d00-fbd7-11e9-91d4-8b6096d58509.jpg)

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **Nightly Build #13050627 from 1/11** using a Google Pixel 3a XL (Android 9)

► Standard
![20191101_111853](https://user-images.githubusercontent.com/51314259/68015185-4ab43d00-fc9a-11e9-88f6-bbded2d38823.gif)

► Strict
![20191101_112037](https://user-images.githubusercontent.com/51314259/68015278-7b947200-fc9a-11e9-9d73-822bae1e50f8.gif)

@Amejia481 - Many thanks for helping me out ! :smiley:

**Comment by Amejia481** [comment]
You are welcome @AndiAJ !
