### ISSUE TITLE
Release pipeline: Ensure metadata is sane when a push happens on the master branch

### ISSUE THREAD

**Issue by JohanLorenzo** [mozilla-mobile/fenix#6327]
### Why

In the taskgraph migration, I regressed twice the version name of the release APK. More precisely, I first fixed it in https://github.com/mozilla-mobile/fenix/pull/5635, then I fixed it again in https://github.com/mozilla-mobile/fenix/pull/5811.

We can prevent the issue from being visible at the very end of the pipeline, on the day we ship Fenix. 

### What/Requirements

The version name is encoded in `AndroidManifest.xml`. Despite what its name tells, it's a binary file. We need a special tool like `apktool` (included in the Android `build-tools`, if I remember correctly) or [androguard](https://pypi.org/project/androguard/).

We actually had a similar situation in Fennec ([bug 1540152](https://bugzilla.mozilla.org/show_bug.cgi?id=1540152)) We chose to run the checks done in the push-apk task also right after the APK was generated. Why the push-apk task in particular? It uses androguard to get the APK metadata. 

I think we should do the same. Moreover, this project can leverage one of the taskgraph features: [graphs that depend on other graphs](https://johanlorenzo.github.io/blog/2019/10/24/taskgraph-is-now-deployed-to-the-biggest-mozilla-mobile-projects.html#other-features-i-like). In other words, we can generate the nightly/production APKs on push to master, validate their metadata, and then **promote** these APKs to be published. 

This way, we fail fast and we ship even faster.

cc @liuche @jlund

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-14172)

**Comment by csadilek** [comment]
@JohanLorenzo do you want to keep this ticket? Deciding if I should move to Bugzilla. :)

**Comment by JohanLorenzo** [comment]
Hey! Thanks for reaching out to me. I'm the fence about this one. One the one hand, I understand the regression I introduced back then and it might happen again. On the other hand, we definitely have bigger fish to fry.

Let's close it. Worst case scenario, I'll open a bugzilla ticket when the time comes 🙂
