### ISSUE TITLE
[Bug/Missing critical feature] Long press refresh button to do a hard reset

### ISSUE THREAD

**Issue by madb1lly** [mozilla-mobile/fenix#6329]
### Why/User Benefit/User Problem
Currently I don't think there's a way to do a hard refresh in Fenix is there? If there is I haven't found it.

### What/Requirements
In Fennec long-press on the refresh icon will force hard refresh a page. I suggest that the same method is used in Fenix.

### Acceptance Criteria (how do I know when I’m done?)
Provide a way to hard refresh a page.

**Comment by buttercookie42** [comment]
Duplicate of #2681.

**Comment by madb1lly** [comment]
Thanks @buttercookie42. I honestly _did_ try to see if this bug was already raised, but I presume that GitHub's search function hid it from me!
