### ISSUE TITLE
[Bug] After you delete a collection the default title numbering goes back one position

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#6330]
## Steps to reproduce
1. Create 2 collections.
2. Delete collection 1.
3. Create a new collection. Observe the default name suggested.
### Expected behavior
Collection 3 is suggested because 2 was already used.
### Actual behavior
The default title is back to Collection 2 if you delete one.
### Device information

* Android device: any
* Fenix version: Nightly 10/29, RC 2.3.0

**Comment by brampitoyo** [comment]
@BranescuMihai Approach 2 looks like it will give the better user experience. Let’s double-check with @topotropic, since she handles all things Collections-related.

@topotropic, what do you think about the default collection naming approach suggested by @BranescuMihai above?

**Comment by topotropic** [comment]
Sounds good to me (Option 2, regex). Thanks!

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **Nightly Build #13450608 from 12/11** using the following devices:
• Google Pixel 3a (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• Motorola G4 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

► Video
![20191212_113837](https://user-images.githubusercontent.com/51314259/70610070-95b35f80-1c0b-11ea-9a9f-4e1938788faf.gif)
