### ISSUE TITLE
Pausing videos/audio on tab-change, like Chrome mobile.

### ISSUE THREAD

**Issue by wisniewskit** [mozilla-mobile/fenix#6337]
Chrome will send a pause event to the actively playing video/audio element when the user changes to another tab (and resume it similarly when they return to the tab). It might be worth considering adding this feature (perhaps even as an option), since users are [reporting this](https://webcompat.com/issues/42321) as a web compatilbiity/interop issue.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-14180)

**Comment by buttercookie42** [comment]
> perhaps even as an option

If this isn't made optional (and perhaps also non-default), then I am certain that there will be complaints in the other direction, too, as listening to audio (or the audio track of a video) from a background tab is a popular use case too.

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813278

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
