### ISSUE TITLE
[Bug] Long tapping on a tab does not check it when creating a Collection

### ISSUE THREAD

**Issue by LaurentiuApahideanSV** [mozilla-mobile/fenix#6341]
## Steps to reproduce
1. Open several tabs;
2. On the home screen, long tap a tab in order to bring up the Collection selection screen.
### Expected behavior
The tab that was long tapped should be selected.
### Actual behavior
The tab is not selected.
### Device information

* Android device: OnePlus 6T (Android 9)
* Fenix version: 2.3.0-rc.2 (Build #13030519) 10/30

**Comment by AndiAJ** [comment]
Also happening on the latest **Nightly Build #13030619 from 30/10** using the following devices:
• Google Pixel 3a XL (Android 9)
• Samsung Galaxy Note 9 (Android 8.1.0)
• Huawei MediaPad M3 Lite 10 (Android 7)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1) 

► Video
![20191030_143413](https://user-images.githubusercontent.com/51314259/67858963-241fc600-fb23-11e9-8a73-5bf01dc78228.gif)

**Comment by ekager** [comment]
Reopening for QA

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **Nightly Build #13050627 from 1/11** using the following devices:
• Google Pixel 3a XL (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

► Video
![20191101_091619](https://user-images.githubusercontent.com/51314259/68008803-c86f4d00-fc88-11e9-9959-9877ed7324ab.gif)
