### ISSUE TITLE
[Bug] Onboarding remains displayed if you open tabs using the "+" button

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#6342]
## Steps to reproduce
1. Clear app data.
2. On the homescreen, while the onboarding tour is displayed, tap the + button in the nav bar.
3. Navigate to a webpage.
4. Return to homescreen and check if the tabs list is displayed.
### Expected behavior
Tabs list is displayed.
### Actual behavior
Onboarding tour still displayed, the tabs are not visible.
### Device information

* Android device: any
* Fenix version: RC 2.3.0-rc2, Nightly 10/30. Also reproducible on RC 2.1.0

**Comment by AndiAJ** [comment]
Hi, I've just checked on the latest Nightly Build #13050627 from 1/11 using the following devices:
• Google Pixel 3a XL (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

1. The open tabs list is displayed ✔️
2. On all devices I've noticed that for a slight time frame the Onboarding is displayed when returning to the homescreen ❓

►Video
![20191101_0901551](https://user-images.githubusercontent.com/51314259/68008466-b7720c00-fc87-11e9-88a3-a81d1f53f04a.gif)


@mcarare - Please review and let me know if I should file a new bug for the transition matter or keep this one open? :blush:
I'll remove the QA need label until further updates.

**Comment by AndiAJ** [comment]
As discussed with @mcarare we'll file a new bug for the transition issue.
Based on this I'll close this ticket as **verified** on the latest **Nightly Build #13050627 from 1/11** using the following devices:
• Google Pixel 3a XL (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)
