### ISSUE TITLE
[Bug]Set as default browser not working on Huawei/Xiaomi devices

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#6347]
## Steps to reproduce
1. Navigate to settings
2. Tap on "Set as default browser"
3. Enable set as default browser
4. Once redirected to the devices Settings select "Firefox Preview"
5. Return to  Firefox Preview and check the "Set as default browser" toggle

### Expected behavior
Toggle should be enabled

### Actual behavior
Toggle isn't enabled

### Device information

* Android device: Huawei MediaPad M3 Lite 10 (Android 7)
* Fenix version: 
• Fenix v2.3.0-rc.2 
• Nightly Build #13030619 from 30/10

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-14186)

**Comment by ebalazs-sv** [comment]
This is reproducible on Nightly 201020 05:03 (Build #2015770729) GV 83.0a1 from 10/20 with Huawei P9 Lite (Android 7).

**Comment by ebalazs-sv** [comment]
This issue is reproducible on Nightly 201215 05:02 (Build #2015781481) GV 85.0a1 from 12/15 with Huawei P9 Lite (Android 7).

**Comment by opusforlife2** [comment]
Coming here from #14073. This doesn't work on LineageOS either.

**Comment by SoftVision-LorandJanos** [comment]
This is reproducible on latest Beta (89.0.0-beta.2) with HTC Nexus 9 (Android 7.1.1).

**Comment by delia-pop** [comment]
This is still reproducible on 95.0.0-beta 5 with Huawei MediaPad M2 (Android 5.1.1).

**Comment by delia-pop** [comment]
This is still reproducible on RC 100.1.2 with Huawei MediaPad M2 (Android 5.1.1).

**Comment by lobontiumira** [comment]
This issue still reproduces on Xiaomi Mi8 Lite (Android 10) on the latest Fenix Nightly build 105.0a1 from 8/11.

**Comment by SoftVision-LorandJanos** [comment]
This issue reproducible with Oppo Find X5 (Android 12) on the latest Fenix Nightly 107.0a1 build from 10/11, on the latest Beta (106.0b5) build, and on the latest RC (106.1.0) build.

**Comment by opusforlife2** [comment]
Interesting: I was facing this on both LOS 16 (Android 9) and LOS 17 (Android 10). But now I'm on LOS 19 (Android 12) on the very same Xiaomi device, and the toggle is enabled.

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807130

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
