### ISSUE TITLE
As a user I would like to restore an archived session

### ISSUE THREAD

**Issue by boek** [mozilla-mobile/fenix#635]
In the prototype, the ask was to combine your archived session tabs with your current session. There were a couple of problems that I ran into with this approach

1. It could just be me, but whenever I attempted to restore a session my expectation is that it would take me right where I left off. Even potentially opening my active tab at the time. (The thought here is restoring my most recent session after it expires)
2. It was very easy to accidentally restore a session, potentially adding a ton of tabs to your current session

My thoughts are leaning more towards potentially swapping your current session with one you select, giving the user a menu option to merge sessions?

**Comment by pocmo** [comment]
The flow described in this very large image seems to match your expectations:
https://github.com/mozilla-mobile/fenix/issues/185#issuecomment-464127541

It seems like in this flow the current session will be *replaced* with the restored one.

**Comment by boek** [comment]
@pocmo oh yep, You're right! I guess some good did come out of the prototype :+1:
