### ISSUE TITLE
Prevent Fenix from using large amounts of data when the app is backgrounded without the user's consent

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#6355]
### Why/User Benefit/User Problem
A user reported on Slack:
> Is it expected right now that Firefox Preview will use data indefinitely when in the background? ... I was reading a news article last night which apparently had an embedded video. I backgrounded the browser and went to bed. Woke up to 7GB of mobile data used  while Firefox just kept dutifully playing the video

The core issue is that normal Fenix use may **spend users' money (on their data connection) without their consent.** We should put in safeguards to prevent this from happening when users don't intend it to.

Note that we need to be concerned about the app deliberately downloading while the app is backgrounded (e.g. when playing a video like this case) and when the app isn't deliberately downloading, i.e. due to a GV bug (this may have been a cause of the Fennec bugs mentioned below).

We've had similar issues on Fennec ([bug 1389499](https://bugzilla.mozilla.org/show_bug.cgi?id=1389499), [bug 1022569](https://bugzilla.mozilla.org/show_bug.cgi?id=1022569), & there may be others).

### Acceptance Criteria (how do I know when I’m done?)
- Fenix doesn't use large amounts of data when the app is backgrounded without the user's consent
  - (Should we file a follow-up to cover GV bugs using data instead of covering it here?)
  - (Should we file a follow-up to make Fenix not use large amount of data when the app is foregrounded too?)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-14191)

**Comment by NotWoods** [comment]
For the video use case, mozilla-mobile/android-components#4253 should help.

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813238

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
