### ISSUE TITLE
NetworkID-The "Link is up" column is not updated per enabled/disabled connection when device is restarted

### ISSUE THREAD

**Issue by Diana-Rus** [mozilla-mobile/fenix#6356]
Pre-requisites:
Have Wi-fi or mobile data connected and set it to auto-reconnect.
Have Fenix Nightly installed on the device.
## Steps to reproduce
1. Restart device.
2. Open Fenix/Firefox Preview browser.
3. Tap on the URL bar and search after "about:networking".
4. Tap on the "NetworkID" section.
5. Refresh the page.
5. Disconnect from network and refresh page.
### Expected behavior
The "Link is up" column is updated correctly when a network of type like Wi-Fi, mobile data or similar, is enabled/disabled. 
Link is up - set to true when network is enabled.
Link is up - set to false when network is disabled.
### Actual behavior
The "Link is up" column is not updated correctly when a restart of a device is made.
The "Link is up" column display a "True" statement in which ever state the network is, after a restart. 

NOTE:
- An action of "Clear Data" from device's "Settings"/"Apps"/"Fenix Nightly"/"Storage" will have the "Link is up" column correctly updated. As per how it is before making a restart of the device.
- An action of closing and opening the device again will have the "Link is up" column correctly updated.
- A refresh of the page won't update the "Link is up" with the correct status.
- A close of the browser won't update the "Link is up" with the correct status.
- In case no restart of the device is made after installation or after an action of clear data from device's settings only in those circumstances will the "Link is up" column display the correct status for network.

This issue is related to the Feature Network ID - bugzilla ticket id: https://bugzilla.mozilla.org/show_bug.cgi?id=1567627 .

### Device information

* Android device: Samsung Galaxy S9 (Android 8.0.0)
* Fenix version: Fenix/Firefox Preview Nightly 191029 (Build #13020608) and Gecko View 72.0a1-20191025095546

**Comment by Diana-Rus** [comment]
Update checked the issue with Sony Xperia Z5 (Android 7.0) and it reproduces on this device as well.

**Comment by Diana-Rus** [comment]
Update [video](VID_20191031_190356.zip](https://github.com/mozilla-mobile/fenix/files/3796891/VID_20191031_190356.zip) with outcome attached. As a zip file.

**Comment by Diana-Rus** [comment]
Hi, verified as fixed on app build Firefox Preview Nightly 191120 (Build #13240608) and Gecko View 72.0a1-20191118093852 with Samsung Galaxy S9 (Android 8.0.0) and Google Pixel 3a (Android 9)
Scenarios checked:
- disable/enable wi-fi -> the "Link is up" data is updated correctly based on the state of the network 
- have wi-fi enabled and restart device - the "Link is up" data is updated correctly based on the state of the network
- disable/enable mobile data  - the "Link is up" data is updated correctly based on the state of the network
- have mobile data enabled and restart device - the "Link is up" data is updated correctly based on the state of the network
- have both Wi-fi and mobile data enabled and restart device  - the "Link is up" data is updated correctly based on the state of the network

**Comment by boek** [comment]
Looks like this is fixed? Feel free to re-open if there is more left to do!
