### ISSUE TITLE
[Bug] Download notifications no longer dismissable

### ISSUE THREAD

**Issue by neekless** [mozilla-mobile/fenix#6357]
## Steps to reproduce
Download any file

### Expected behavior
Completed download notifications used to be dismissable, and should still be so

### Actual behavior
![ScreenRec_20191031_170834](https://user-images.githubusercontent.com/22426822/67933878-a1e4df80-fbbe-11e9-8f59-f9cab9e8ba99.gif)

### Device information
* Android device: Pixel 2 XL Android 9
* Fenix version: Nightly 191031 06:00 (Build #13040609)
📦: 20.0.0, 09f861ac2
🦎: 72.0a1-20191029093803

Likely due to https://github.com/mozilla-mobile/android-components/commit/340356408f5df62e8b7ecd0769dae289dcc30605

**Comment by sblatz** [comment]
This should be fixed by an AC patch I submitted : https://github.com/mozilla-mobile/android-components/pull/4909

😄

**Comment by sblatz** [comment]
I will set this to QA needed as soon as we have that merged in.

**Comment by sblatz** [comment]
Should be fixed now :)

**Comment by neekless** [comment]
Confirm fixed on Nightly 191102 06:01 (Build #13060607)
📦: 20.0.0, 8f0f6dc12
🦎: 72.0a1-20191031095309

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **Nightly Build #13080607 from 4/11** using the following devices:
• Google Pixel 3a XL (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

► Video
![20191104_095654](https://user-images.githubusercontent.com/51314259/68106621-e0460b80-feea-11e9-9ab6-0587ff9eb507.gif)

The only issue encountered is the one as per #6390 while checking on the LG Nexus 4 (Android 5.1.1)
