### ISSUE TITLE
[Bug] Pixel 2 - Flashes when switching animated slides 

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#6362]
## Steps to reproduce
I've had the default setting for webrender.
Then I toggled gfx.webrender.force-disabled to true and restarted.
This is reproducing in both cases, so maybe webrender isn't switched off by gfx.webrender.force-disabled?
1. Go to http://www.playmag.fr/heroesoftomorrow and click the arrows at the top to go through the slides.
### Expected behavior
No visual issues.
### Actual behavior
The video slides are flashing while transitioning from one to the other.
### Device information

* Android device: Pixel 2 (Android 9)
Not reproducing on Pixel 3 (Android 9) or Galaxy S8 (Android 9)
* Fenix version: Nightly 10/31

**Comment by jbonisteel** [comment]
I was able to reproduce this with WebRender on but not off, filed: https://bugzilla.mozilla.org/show_bug.cgi?id=1593311 to track

**Comment by ekager** [comment]
Bugzilla was closed a year ago. Closing this as well
