### ISSUE TITLE
[Bug] Protection settings has no startPadding 

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#6369]
<img width="350" alt="image" src="https://user-images.githubusercontent.com/4400286/67988196-78db4380-fbec-11e9-9ff7-98ea47417e99.png">

**Comment by Baron-Severin** [comment]
@ekager does this require QA verification?  If so, would you mind labeling it?

**Comment by ekager** [comment]
Don't think so. It was just a revert
