### ISSUE TITLE
Choose to always open selected domains in reader mode

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/fenix#6377]
## User Story
As a user, I want to choose to always open content from select domains in reader mode, so I don't have to load the content to start with before the “clean” version of the page can be shown.

### For UX
UX to recommend whether this should be a global toggle (always open in reader mode when available) or at the domain level whereby the user can specify to always load specific domains in reader mode.

### Acceptance Criteria
- I can choose to always open a domain in reader mode when available
- I can disable the setting

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-14205)

**Comment by Poopooracoocoo** [comment]
also see #11460

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813280

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
