### ISSUE TITLE
Form Data Management

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/fenix#6379]
## User Story
- As a user, I want to be able to edit or delete my form data, in case they are incorrect or out of date.

### Acceptance Criteria
- I can delete my saved address data directly in browser settings
- I can clear my address data as one of the "clear data" options in my browser settings
- I can edit my saved address data directly in browser settings (P3 - not in Q1)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-14206)

**Comment by madb1lly** [comment]
Hi all,
I don't see these being tested yet in Nightly so I presume it's still open.
Cheers 🙂

**Comment by Iey4iej3** [comment]
This does not seem to be supported even on desktop Firefox. There is a plugin https://github.com/stephanmahieu/formhistorycontrol-2 which does not use the `formhistory.sqlite` (due to the restriction of WebExtension) but maintains its own data.

**Comment by madb1lly** [comment]
Still to do.

**Comment by madb1lly** [comment]
Not fixed.

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813288

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
