### ISSUE TITLE
[Bug]Onboarding fragment is displayed for a couple of seconds when returning to the homescreen

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#6388]
## Prerequisites
Have a clean profile

## Steps to reproduce
1. Tap the + sign from the navbar
2. Navigate to any webpage
3. Return to the home screen

### Expected behavior
The user is redirected to the homescreen without showing the onboarding fragment

### Actual behavior
The onboarding fragment is displayed for a couple of seconds while performing the transition

### Device information

* Android device: 
• Google Pixel 3a XL (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

* Fenix version: Nightly Build #13050627 from 1/11

### Notes
Noticed this while checking #6342 
►Video
![68008466-b7720c00-fc87-11e9-88a3-a81d1f53f04a](https://user-images.githubusercontent.com/51314259/68012849-de363f80-fc93-11e9-98a2-5f658ba8ab16.gif)

**Comment by KaairaGupta** [comment]
@boek is it still an issue? Because i don't seem to be able to reproduce it on my device(android 9)

**Comment by mcarare** [comment]
@AndiAJ Can you still reproduce this?

**Comment by AndiAJ** [comment]
Hi @mcarare , I've re-checked this matter and **wasn't able to reproduce it anymore** on the latest **`Nightly #20420611 from 2/11`** using the following devices:
• Google Pixel 3a XL (Android 10)
• Google Pixel 3a (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7.0.0)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

► Video
![20200211-175149](https://user-images.githubusercontent.com/51314259/74253881-58954780-4cf8-11ea-8078-6049ab78a2db.gif)
