### ISSUE TITLE
[Bug] "Download" button's UI should have the Fenix specifics

### ISSUE THREAD

**Issue by softvision-miralobontiu** [mozilla-mobile/fenix#6390]
## Steps to reproduce
1. Acces https://file-examples.com/ and select a file to download.
2. Observe the "Download" button from the pop-up displayed.

### Expected behavior
The "Download" button should have the Fenix 's UI specifics.

### Actual behavior
The button has a different UI.

### Device information
* Android device: Google Pixel (Android Q), Sony Xperia Z5 Premium (Android 7.1.1)
* Fenix version: 11/01 (#13050628)

![Screenshot_20191101-122712](https://user-images.githubusercontent.com/40694158/68019246-d8485a80-fca3-11e9-9d9d-f24f74e51a70.png)

**Comment by AndiAJ** [comment]
Reproducible on the latest **Nightly Build #13080607 from 11/4** using a LG Nexus 4 (Android 5.1.1)

**Comment by softvision-miralobontiu** [comment]
Verified as fixed on the latest Nightly build from 11/07 (#13110607) with Google Pixel (Android Q), OnePlus 5T (Android 9), and Nexus 9 Tablet (Android 7.1.1).
