### ISSUE TITLE
Button Ripples not Visible in Private Mode on Click

### ISSUE THREAD

**Issue by ekager** [mozilla-mobile/fenix#640]
## Steps to reproduce
- Switch to Private Mode 
- Click on Menu Button

### Expected behavior
- Clickable button ripple

### Actual behavior
- Ripple not visible in private mode. 
Private Mode should inherit from a Dark Theme in order to see these ripples.

**Comment by sblatz** [comment]
I believe there is a ripple it just has *very little* contrast with the darker background--perhaps we can find a better color to use?

 The one ripple that's slightly different (and should definitely be fixed) is the private browsing button which only ripples if you drag your finger off of it.

**Comment by sblatz** [comment]
Per conversation with @ekager--we can inherit from dark mode to avoid this. I don't think we need UX work.

**Comment by ekager** [comment]
Closed by #648
