### ISSUE TITLE
Get AC + SV Team Access to Fenix Firebase UI Test Reports

### ISSUE THREAD

**Issue by ekager** [mozilla-mobile/fenix#6406]
Since AC works in Fenix often, we should make sure their team has Firebase report access for our UI test suite. It can be even more difficult to get a patch through when you don't even know which tests are failing 💃 

Also want to give acess to SV contributors. 

Getting the failing tests to show in the PR would also be helpful!

@rpappalax I forget how we all originally got access? Do you have access somewhere to manage the users?

**Comment by rpappalax** [comment]
@ekager I've been managing the users individually, but I'm reaching out to ops today to see how to enable a team.  Also, for test result reports, see:  https://github.com/mozilla-mobile/fenix/issues/6760

**Comment by rpappalax** [comment]
@ekager A-C folks reached out last week and I've added them. I believe everyone that needs access to Firebase should now have it.  For posting test results as PR comments there's a separate issue #6760.  did you still want to keep this open or close?

**Comment by rpappalax** [comment]
I believe everyone who requested access should now have it.  closing
