### ISSUE TITLE
[Bug] Close button not working on Bookmarks and History

### ISSUE THREAD

**Issue by hakkikaancaliskan** [mozilla-mobile/fenix#6408]
Also back arrow is redundant if opened from homescreen.

## Steps to reproduce
Open history or bookmarks from homescreen.
Press x.

### Expected behavior
Bookmarks/history closed.
### Actual behavior
Not closing.
![sketch-1572704461461](https://user-images.githubusercontent.com/17825767/68072285-d60dfb00-fd8c-11e9-96d8-52e5f674cca8.png)

### Device information
Nightly 191102 06:01 (Build #13060607)
📦: 20.0.0, 8f0f6dc12
🦎: 72.0a1-20191031095309
XZ1 Android 9

**Comment by shahsurajk** [comment]
The same is valid for the "History" component as well. Problem with the `close` function in `LibraryPageFragment` probably.

**Comment by ekager** [comment]
Reopening for QA

**Comment by hakkikaancaliskan** [comment]
Verified as fixed on
Nightly 191108 06:01 (Build #13120608)
📦: 21.0.0, 09da19708
🦎: 72.0a1-20191105095755

Should I open a separate issue for the first sentence of this issue? @ekager

**Comment by ekager** [comment]
Sure open a new issue please! Thank you!
