### ISSUE TITLE
Redundant + button on homescreen

### ISSUE THREAD

**Issue by hakkikaancaliskan** [mozilla-mobile/fenix#6409]
Same behavior between search bar and + button. All of them open awesome bar. + button is redundant.
![1658138980](https://user-images.githubusercontent.com/17825767/68072374-b0cdbc80-fd8d-11e9-9861-c1eb3fe47f57.png)

### Device information
Nightly 191102 06:01 (Build #13060607)
📦: 20.0.0, 8f0f6dc12
🦎: 72.0a1-20191031095309
XZ1, Android 9

**Comment by hakkikaancaliskan** [comment]
This isn't bug, just an idea 🤷

**Comment by cadeyrn** [comment]
To be honest I think it's a good thing to have this _new tab_ button because the button makes the option to open a new tab more explicit. _Could_ be important for less experienced users - maybe an interesting topic for user research?

**Comment by hakkikaancaliskan** [comment]
> maybe an interesting topic for user research?
I think like you too.
Also I think everybody can understand to press search bar. This two doing same thing, this thing can confuse people.

**Comment by brampitoyo** [comment]
As this feature is search-related, I’m paging @Verdi to get his feedback.

**Comment by darkwing** [comment]
Do we have any metrics on how often users use bookmarks; I could see the bookmarks menu being really nice in this spot.

**Comment by brampitoyo** [comment]
@darkwing Interesting question!

As far as I’m aware, other browsers (including Fennec) solve this problem by:

1. Putting bookmarks on the start screen
2. Separating start screen (contains search bar + bookmarks) from tab manager (may/may not contain search bar + open tabs)

I know that @topotropic has been thinking a lot about this, so let me assign this issue to her.

**Comment by topotropic** [comment]
Thanks for the feedback! 

We'll introduce a dedicated tab tray and replace the plus icon with the multi-task icon to go to the tab tray. https://github.com/mozilla-mobile/fenix/issues/1063
I'll close this issue.
