### ISSUE TITLE
[Meta] Send and Share to nearby devices

### ISSUE THREAD

**Issue by bbinto** [mozilla-mobile/fenix#641]
### Why/User Benefit/User Problem
Share tool: Share information on the web

- As a user, I want to share information I find on the web with myself so that I can retrieve it later
- As a user, I want to share information I find on the web with others so they can access it

### What / Requirements
I don’t need to sign up for an account to send share web content with other devices nearby

### Acceptance Criteria (how do I know when I’m done?)
- Nearby Devices: on your network

**Comment by vesta0** [comment]
No longer required.
