### ISSUE TITLE
[Bug] Snackbar messages cover address bar

### ISSUE THREAD

**Issue by bxtom** [mozilla-mobile/fenix#6413]
Message placement is inconsistent. On the left screenshot is ok, on the right message covers address bar. I think message placement should be corrected (moved up).

![MessagePlacement](https://user-images.githubusercontent.com/29851015/68085018-fba60d80-fe3b-11e9-990f-c5609aced67e.png)

* Android device: android 9
* Fenix version: 2.2.0 (Build #12901947)

**Comment by sblatz** [comment]
This one is a bit complicated since the ShareFragment is a separate fragment from BrowserFragment and cannot access the browserToolbar as an anchor. I'm digging into this.

**Comment by sblatz** [comment]
Note: this also happens with "Syncing"

**Comment by sblatz** [comment]
Have a fix up for review now; I believe I fixed this is all locations 😄

**Comment by AndiAJ** [comment]
Hi, I've just checked this matter on the latest **Nightly Build #13650606 from 12/31** using a Google Pixel 3a (Android 9)

| Status  | Description|
| ------------- | ------------- |
| ✔️ | Close a tab from the Home screen - Open tabs section  |
| ✔️ | Close all tabs from the Home screen - Open tabs section  |
| ✔️ | Create a new Collection  |
| ✔️ | Rename a collection |
| ✔️ | Save a page to a collection from the Navigation bar (3dot button overlay)  |
| ✔️ | Add a bookmark |
| ✔️ | Delete a bookmark  |
| ✔️ | Send tab |
| ✔️ | Delete browsing data on quit (from the home screen)  |
| ❌ | Delete browsing data on quit while having a website opened (from the Navigation bar- 3dot button overlay) |
| ❌ | Delete browsing data  |
| ❓ | Syncing (After the user successfully logs in and the auto sync kicks in)|

#### ►Full run video
![20191231_100910](https://user-images.githubusercontent.com/51314259/71615369-9e1f0a80-2bb9-11ea-8a34-bfd4302457ca.gif)


#### ❌ Delete browsing data on quit while having a website opened (from the Navigation bar- 3dot button overlay) 

![20191231_101357](https://user-images.githubusercontent.com/51314259/71615734-5d27f580-2bbb-11ea-9fcb-880bd98fb467.gif)

#### ❌ Delete browsing data
![20191231_101524](https://user-images.githubusercontent.com/51314259/71615847-f3f4b200-2bbb-11ea-9c18-565983e2d448.gif)

#### ❓  Syncing (After the user successfully logs in and the auto sync kicks in)
**Seems to be miss-positioned**
![20191231_103929](https://user-images.githubusercontent.com/51314259/71615888-2ef6e580-2bbc-11ea-9716-7a2905aedeee.gif)

@sblatz  - Please review the above and share your thoughts. ☺️ 
I'll remove the QA needed until further notice.

**Comment by sblatz** [comment]
Ah looks like there were a few more cases! Thanks @AndiAJ digging into these now.

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **Nightly Build #20030608 from 1/3** using a Google Pixel 3a (Android 9)

| Status  | Description |
| ------------- | ------------- |
| ✔️  | Close a tab from the Home screen - Open tabs section  |
| ✔️  | Close all tabs from the Home screen - Open tabs section  |
| ✔️  | Create a new Collection  |
| ✔️  | Rename a collection  |
| ✔️  | Save a page to a collection from the Navigation bar (3dot button overlay)  |
| ✔️  | Add a bookmark  |
| ✔️  | Delete a bookmark  |
| ✔️  | Send tab  |
| ✔️  | Delete browsing data on quit (from the home screen)  |
| ✔️  | Delete browsing data on quit while having a website opened (from the Navigation bar- 3dot button overlay)  |
| ✔️  | Delete browsing data  |
| ✔️  | Syncing (After the user successfully logs in and the auto sync kicks in)  |

►Video
![20200103_100838](https://user-images.githubusercontent.com/51314259/71713630-306e1b00-2e13-11ea-8a5d-cdb068cc9a3f.gif)

@sblatz  - Great job! ☺️
