### ISSUE TITLE
Introduce Pocket stories in Fenix

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/fenix#6416]
### User Story
As a user, I want to discover interesting content in the browser in a way that is not intrusive to my core browsing experience.

Dependencies
- [x] [UX discovery and mocks](https://www.figma.com/file/ZjgR9WfXC09CtfFvRJrveM/Pocket?node-id=8%3A18)
- [ ] Finalize copy 
- [ ] Update the pocket client API in AC to support stories (currently it only supports fetching videos)
- [ ] Build the UI in Fenix
- [ ] Telemetry #16495

### Acceptance Criteria

- [ ] We have built the capability to fetch pocket stories in AC
- [ ] User will see a pocket opt-in card on the homescreen and have the choice to enable pocket stories
- [ ] Users can dismiss the card and have it removed from homescreen 
- [ ] If users enable the card, then they will see 3 top articles and 1 discover more card on their homescreen. 
- [ ] Users will be able to turn off pocket stories after having enabled them
- [ ] Users will be able to enable pocket stories after having dismissed them

![image](https://user-images.githubusercontent.com/42752644/97599050-fa230d00-19dd-11eb-9d42-74d710196912.png)

**Comment by liuche** [comment]
Remaining spec work would be:
- Talking to Pocket for API endpoint
- content to review 
- edge cases?

will also file a telemetry ticket

**Comment by Mugurell** [comment]
Regarding adding Pocket to the app's homescreen, there was a recent issue https://github.com/mozilla-mobile/fenix/issues/19099 about cleaning up how that homescreen is accessed.
If a user would want to go to homescreen to interact with top sites / collections / pocket articles, pressing the "plus" button in tabs tray would open the homescreen but also the keyboard for better supporting the user opening a new tab. 
If she just wanted to check on Pocket articles this flow migh be too cumbersome.
So if this new feature is added to homescreen maybe this is a good time to think about giving these homescreen features priority and not to search.
@vesta0  @channingcarter

**Comment by vesta0** [comment]
Totally agree with you @Mugurell and yes that's a problem we want to solve before surfacing Pocket on homescreen.
