### ISSUE TITLE
Save a collection as homescreen shortcuts

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/fenix#6417]
## User Story
- As a user, I want to be able to open a collection of sites directly from my homescreen, so I have a convenient way of opening sites that I view regularly.

### Acceptance Criteria
- I can save a collection as a homescreen shortcut
- I can open a collection by tapping on a homescreen shortcut
- [Telemetry] Opening a collection from a homescreen shortcut

**Comment by mcarare** [comment]
@vesta0 Do we have any UX specs for this? Icon, title for shortcut, etc.
I suppose the dialog for adding shortcut will be the same as for a single tab. TY!

**Comment by vesta0** [comment]
@mcarare no this ticket has not been reviewed by UX yet :)

**Comment by AmyYLee** [comment]
@topotropic to review
