### ISSUE TITLE
Custom tabs allow you to enter HomeFragment

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#642]
## EDIT

Sounds like we shouldn't be able to enter the home fragment at all when in a custom tab, so that's the bug tracked here.

~~Steps to Reproduce~~
~~1. Open a custom tab~~
~~2. Press the tab button~~
~~3. Press private mode~~

~~Expected~~
~~The home fragment just switches to private mode~~

~~Actual~~
~~I am put into browser fragment of the previous tab I was in but now *with a private theme*~~

**Comment by pocmo** [comment]
Sounds like getting into this state is already a "bug" (or a not implemented part): In custom tabs you shouldn't have a tab button.

**Comment by sblatz** [comment]
Ah, that makes sense--I didn't know the UX for this. I'll change this ticket to reflect it!

**Comment by sblatz** [comment]
This is **expected behavior** at this point as [custom tabs are not supported](https://github.com/mozilla-mobile/fenix/issues/222) yet.

**Comment by sblatz** [comment]
After a conversation with @boek this appears to be a regression.
