### ISSUE TITLE
[Bug] Backspace unreliable to canvas with focus

### ISSUE THREAD

**Issue by CendioOssman** [mozilla-mobile/fenix#6420]
## Steps to reproduce
1. Make a canvas focus:able by setting `tabIndex` to `-1`
2. Click the canvas to focus it
3. Type `abc`
4. Press backspace

### Expected behavior
The canvas gets four `keydown` events, one for each key press.

### Actual behavior
The canvas gets three `keydown` events, only for `abc`. If you keep pressing backspace then the events finally go through. The number of times matches the number of characters previously entered, so there is some buffer magic happening behind the scenes.

### Device information

* Android device: Pixel C using a physical keyboard
* Fenix version: 2.2.0

**Comment by CendioOssman** [comment]
Test case:

```html
<html>
<head>
<title>Backspace test</title>
<style>
#canvas {
    border: 2px solid black;
}
#canvas:focus {
    border: 2px solid red;
}
</style>
</head>
<body>
<p id="output">
  Please press the canvas and then a key
</p>
<canvas id="canvas" width="100px" height="100px"></canvas>

<script>
let canvas = document.getElementById("canvas");
// Make sure it can have focus
canvas.tabIndex = -1;
canvas.addEventListener("keydown", (e) => {
    let output = document.getElementById("output");
    output.textContent = e.key + " / " + e.code;
});
</script>
</body>
</html>
```

**Comment by CendioOssman** [comment]
The same issue exists in the current Firefox for Android. Should I report the issue in bugzilla as well, or is it abandoned at this point? :)

**Comment by makotokato** [comment]
@CendioOssman Could you reproduce this even if Chorme?  Also, what IME/keybaord are you using?  GBoard?

**Comment by CendioOssman** [comment]
Yes, Chrome also sees this bug. So it seems to be something fundamental.

This is only possible to reproduce on a physical keyboard AFAIK since I cannot get Firefox to activate the virtual keyboard on the canvas.

I've tested with the keyboard that's included with Pixel C, as well as a Logitech bluetooth keyboard.

**Comment by CendioOssman** [comment]
Sorry, I retested and I incorrectly assumed that the configured keyboard was only relevant for the on screen virtual keyboard and not for the physical.

After switching from Swiftkey to GBoard it works fine.

**Comment by boek** [comment]
GV bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1610954
