### ISSUE TITLE
[Bug] Quick Action Bar confusing

### ISSUE THREAD

**Issue by Cheap-Skate** [mozilla-mobile/fenix#6421]
I find QAB confusing, some items are in the QAB and some are in the 3-dot menu, not clear what lives where and some are duplicates

(1) First time I've tried to bookmark something in Fenix. Natural place to look is 3 dot menu. Bookmark is not there. It's in the QAB. It actually took me quite a while to work out how to do it. QAB is just a little line above the URL

(2) Share is in both the QAB and in the 3 dot menu - duplication.

I think my problem is this:- the QAB has so few items in it I very rarely use it. So I easily forget it's there.

Re (1) and (2) perhaps the QAB should duplicate a subset of entries in the 3 dot menu, i.e. Share and Bookmark should be in 3 dot menu AND in QAB. Or perhaps, QAB should **never** duplicate 3 dot menu items, Share and Bookmark are only in the QAB not in the menu.

(I believe you have plans to nuke the QAB so perhaps this issue is redundant).

**Comment by cadeyrn** [comment]
QAB will be removed in #6310.

**Comment by NotWoods** [comment]
Closing since we're removing the bar (#4281).
