### ISSUE TITLE
[Bug] Why does a bookmark always open in a new tab?

### ISSUE THREAD

**Issue by Cheap-Skate** [mozilla-mobile/fenix#6422]
## Steps to reproduce
From any tab
Go Your Library > Bookmarks & select a bookmark

### Expected behavior
Bookmark opens in current tab i.e. bookmark overwrites content of current tab. Typical browser behavior

### Actual behavior
Bookmark opens in a new tab. Unique to Fenix? Other browsers tend not to do this.

Confusing!

### Device information

* Android device: Galaxy S7
* Fenix version: Today's

**Comment by Cheap-Skate** [comment]
Sounds like a feature, #3551. (but I don't like it much)

**Comment by NotWoods** [comment]
Current intended behaviour is to open a new tab as stated in #3551. @vesta0 has anything changed here?

**Comment by vesta0** [comment]
Thanks for filing this @Cheap-Skate ! This feature is currently behaving as intended but we will consider your feedback in mind for the next round of milestone user testing.
