### ISSUE TITLE
[Bug] Media Focus Changes Without Playing Video

### ISSUE THREAD

**Issue by nathansgithub** [mozilla-mobile/fenix#6424]
## Steps to reproduce
* Play media using another Android app (for example PowerAmp or similar music player).
* Browse to a webpage with autoplaying videos (ex: https://www.nbcnews.com/tech/tech-news/apple-firefox-browsers-aim-thwart-facebook-google-tracking-n909671)

### Expected behavior
The music/media in the other app should continue playing. The notification for the webpage media should also probably not show up unless I actively play the video.

### Actual behavior
Media is paused in the browser, but it still takes away the media focus from the other app, usually pausing it. The webpage video shows a notification even though I didn't play the video, and it is paused by default.

### Device information
* Android device: Motorola Z3 Play, Android Pie

* Fenix version: 2.3.0 (Build #13031728)

**Comment by ekager** [comment]
Couldn't reproduce with the comment 0 STR using Spotify app to play music and navigating to nbcnews.com/tech/tech-news/apple-firefox-browsers-aim-thwart-facebook-google-tracking-n909671 in Fenix

QA please verify that you can't reproduce and close. Thanks!

**Comment by AndiAJ** [comment]
Hi @ekager , I've re-checked this matter using the Soundcloud app to play music and Nightly debug **`Build #21040820 39.0.20200410130104, 464e3038d GV: 77.0a1-20200409095500 AS: 0.55.0 from Monday 4/13`** using a Google Pixel 3a (Android 10) and noticed the following:

## ✅  1. Having enabled "Block audio and video" in Fenix's site permissions.
#### Note:
•  **No media playback notification gets displayed after navigating to the web page** (Soundcloud continues to play) only after manually playing the featured video the notification gets displayed.

► Video
![20200413-115724](https://user-images.githubusercontent.com/51314259/79109952-16cd5f80-7d82-11ea-8a44-39257e40ad3b.gif)

## ❓ 2. Having enabled "Block audio and video in cellular data only" in Fenix's site permissions.
#### Notes and observations:
**• ❌ The media playback notification is displayed after navigating to the page and Soundcloud is automatically paused even if the video doesn't start to play**.
• ❌ Tapping pause/play from Fenix's notification doesn't have any effect (the video doesn't start to play)
• ✔️  I've tapped **play from Soundcloud's notification** and afterwards **played the video from the web view** and everything seems to be properly working. (the media playback is correctly switching between the 2 apps)

► Video
![20200413-121552](https://user-images.githubusercontent.com/51314259/79111254-d7544280-7d84-11ea-9470-279e7c97512f.gif)

## ❓ 3. Having enabled "Block audio and video in cellular data only" in Fenix's site permissions.
#### Notes and observations:
**• ❌ The media playback notification is displayed after navigating to the page and Soundcloud is automatically paused even if the video doesn't start to play**.
• ❌ Tapping pause/play from Fenix's notification doesn't have any effect (the video doesn't start to play)
• ❌ After playing the video from the web view, Fenix's media notification disappeared.
• ❗  While the video was still playing, I've tapped **play from Soundcloud's notification** and the song also started to play.
**I've ended up having both the video and soundcloud playing at the same time.**

► Video
![20200413-130819](https://user-images.githubusercontent.com/51314259/79113360-69f6e080-7d89-11ea-8629-e6da19c5d078.gif)

**Comment by nathansgithub** [comment]
Thank you! This is awesome.
