### ISSUE TITLE
Create a changelog

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#643]
Lets adopt a changelog similar to a-c. This will allow our testers to have an easier time figuring out what may have broken.

Perhaps we could cut "versions" each week to group the changes together?

**Comment by alexa-v2** [comment]
Not done I got a 54 mb update and as far as I can tell nothing changed

No changelog available in app or in play store

**Comment by cadeyrn** [comment]
@alexa-v2 This issue is about the changelog file in this repository: https://github.com/mozilla-mobile/fenix/blob/master/CHANGELOG.md
