### ISSUE TITLE
Firefox Focus is draining your battery

### ISSUE THREAD

**Issue by StuartHaire** [mozilla-mobile/fenix#6435]
**Steps to reproduce**

1. Open application and use as desired
2. Close application and erase browsing history

**Expected behavior**

The application should close

**Actual behavior**

The application closes and after a few minutes android notifies "Firefox Focus is draining your battery" and allows me to force stop. Happens every time.

**Device information**

Android device: OnePlus 6
Have noticed on other devices however

**Comment by hakkikaancaliskan** [comment]
Sorry but this is fenix github, not focus.

**Comment by StuartHaire** [comment]
Sorry not sure how I ended up here. Closed.
