### ISSUE TITLE
Open bookmarked page from new tab page

### ISSUE THREAD

**Issue by jacktose** [mozilla-mobile/fenix#6437]
### Why/User Benefit/User Problem
You want to open a bookmarked page in a new tab.
If you open a new tab and look around, there is no way to access a bookmark.

### What/Requirements
UX for opening a new tab and then selecting a bookmark.

### Acceptance Criteria (how do I know when I’m done?)
I can open a new tab (from menu, or + on home screen) and then load a bookmarked page in it.

UX suggestion:
In space on new tab page currently given to search engines (or below, or replacing search engines when keyboard is closed), there would be a UI for selecting a bookmark (or other library item). The selected item would open in the new tab (without going through Menu > Open in new tab).

**Comment by jacktose** [comment]
This was mozilla/firefox-preview-bughunting-campaign#313, which was closed as a duplicate of #1487. That's now closed as fixed, but does not address this concern/request.

**Comment by rubcap** [comment]
I created a mock-up with a possible solution for this issue:
![Mock-up_Fenix_newtab](https://user-images.githubusercontent.com/26146350/68624051-3d872180-04d6-11ea-8789-bcce6d7b6506.png)

1. In the menu bar containing "Scan" and "Shortcuts", additional menu items are added: "Bookmarks" and "History". Users who want to open a bookmark from the new tab page, simply tap "Bookmarks" to show the bookmarks panel above. "Bookmarks" is highlighted to show the selected menu item.
2. When none of the menu items is selected and no text was entered in the search/address bar (as can be seen in the mock-up), a speed dial is shown where the user can pin frequently visited websites. Below, highlights or recommendations can be shown. Upon entering text, search suggestions and history items are shown.
3. The menu bar is scrollable in the horizontal direction. Through settings, the user can customize the order in which the menu items appear. A user who frequently uses the "Bookmarks" function can decide to move the "Bookmarks" item more to the left.

**Comment by maverick74** [comment]
I suppose this would also be available when we select the URL bar, while on a web page, as a way to substitute the current page where we are at by a bookmarked or pinned one.

If so, this would be of tremendous use for me because, as of now, I have to close the current tab, go to the bookmarks or to the tab center just to open a specific page in the same place I had the previously closed tab.

In short it's kind of a pita to discard and substitute the current tab by a bookmarked or pinned one...

**Comment by maverick74** [comment]
@vesta0 is there any work on this feature or plans to include it (or something similar) in Fenix?

What's your position about this?

**Comment by vesta0** [comment]
@maverick74 our UX team is working on solving this problem here: #12065

**Comment by maverick74** [comment]
Would just like to update that there is an ongoing vote for this at:

https://connect.mozilla.org/t5/ideas/on-firefox-mobile-make-home-page-links-open-in-current-tab/idi-p/15672
