### ISSUE TITLE
[Meta] Toggle to enable and disable external app auto launch

### ISSUE THREAD

**Issue by rocketsroger** [mozilla-mobile/fenix#6438]
### Why/User Benefit/User Problem
Some users want websites opening their respective apps, while other users dislike this behavior. A toggle would be appreciated by both sides.

### User Story
As a user, I want to choose whether a site will open in my browser or in its respective 3rd party native app if available, so I can customize my browser in a way that fits my preferences. 

### What/Requirements
A toggle or check box like the following
![61923540-d64f5c80-af3a-11e9-8fa2-ed09115a84af](https://user-images.githubusercontent.com/6579541/68146702-95d28800-ff06-11e9-97cc-f67775b4f4dc.jpg)

### Acceptance Criteria
- [ ] When toggle is on, some URLs will launch in 3rd party native apps.  When off, the URL will load in my browser.
- [ ] Telemetry Ticket TBD

**Comment by rocketsroger** [comment]
Needs to talk to UX designer to confirm the design

**Comment by rocketsroger** [comment]
Needs https://github.com/mozilla-mobile/android-components/issues/4950

**Comment by mheubusch** [comment]
Recommended strings:
[label] Open links in apps
[microcopy] Use external apps (like Maps or YouTube) when possible

**Comment by vesta0** [comment]
This issue will be addressed in #7099
