### ISSUE TITLE
In Search bar, tapping "invisible X" leads to full URL bar in search bar's place (regression?)

### ISSUE THREAD

**Issue by Cheap-Skate** [mozilla-mobile/fenix#644]
In today's build
Navigate to a page
tap the URL bar to move to Search
Tap the "invisible X" button at the right hand side of Search bar
Full URL bar shown at top of page, 

Expected:- should revert to URL bar at bottom with Web content

I think this is a regression, it worked OK a couple of days ago. Perhaps I shouldn't be using the "invisible X" button yet :)

I see it on Galaxy S7/Android 8 and BQ Aquaris X5/Android 7

**Comment by ekager** [comment]
This will be fixed by the same change as #531, currently blocked on AC45+

**Comment by ekager** [comment]
Closed by migrating to 45 in #697
