### ISSUE TITLE
Add option in Settings to open website "in app" directly

### ISSUE THREAD

**Issue by Sav22999** [mozilla-mobile/fenix#6446]
### Why/User Benefit/User Problem
It can improve the navigation experience
If the website supports the feature "open in app" give the choice to open directly in the app, instead of the browser.

### What/Requirements
Websites have to support the "open in app" feature.

### Acceptance Criteria (how do I know when I’m done?)
Now the steps are: open website (e.g. Wikipedia), then open QAB (quick action bar) and press "open in app"

**Comment by sempasha** [comment]
#6397

**Comment by NotWoods** [comment]
Duplicate of #7099

**Comment by Sav22999** [comment]
@NotWoods actually #7099 is a duplicate of this, but it doesn't matter

**Comment by NotWoods** [comment]
Very true, but usually I pick the issues filed by Mozilla staff to keep open. Perhaps I should say "superseded by".
