### ISSUE TITLE
[Bug] Release 2.3.0 does not include an APK

### ISSUE THREAD

**Issue by Vinnl** [mozilla-mobile/fenix#6451]
## Steps to reproduce

Visit https://github.com/mozilla-mobile/fenix/releases/tag/v2.3.0

### Expected behavior

For there to be six assets, adding four APKs for different architectures.

### Actual behavior

There are just two assets, labelled "Source code".

### Device information

N/A

Related: #6312?

**Comment by boek** [comment]
Thank you!
