### ISSUE TITLE
[Bug] Experiments are applied to non-Mozilla browser forks

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/fenix#6456]
The crash in https://github.com/mozilla-mobile/fenix/issues/6441 can be seen on non-Mozilla browsers that forked from either Fenix or Reference Browser. Our experiments code (or the underlying system that causes this), should only be running for app IDs we own.

**Comment by Baron-Severin** [comment]
@jonalmeida would you mind adding a note about why this was closed?  Is the problem being tracked somewhere else?

**Comment by jonalmeida** [comment]
This was a dupe created when github blipped and I hit the 'resend request' button because the page load was taking too long. The same issue is open and linked correctly, see: https://github.com/mozilla-mobile/fenix/issues/6455
