### ISSUE TITLE
[Bug] fenix 2.3.0 [ 20191014032640 ] crash on tapping browse for file

### ISSUE THREAD

**Issue by leela52452** [mozilla-mobile/fenix#6459]
## Steps to reproduce

https://achecker.ca/checker/index.php
select html file upload
browse

### Expected behavior

select file

### Actual behavior

browser crashes

### Device information

* Android device: ls-4001
* Fenix version: 2.3.0 [ 20191014032640 ]

![20191105_214202-1](https://user-images.githubusercontent.com/52065244/68227280-5336ab80-ffeb-11e9-9f73-31f562598ebc.gif)

**Comment by NotWoods** [comment]
Fixed in Nightly: #6279

Should we uplift the change to stable? Fixed with A-C 19.0.0.

**Comment by Amejia481** [comment]
This should be fixed

**Comment by softvision-miralobontiu** [comment]
Verified as fixed on the latest Nightly build 11/25 with Huawei P9 Lite (Android 7), and Google Pixel 3 (Android Q).
