### ISSUE TITLE
Upgrade forPerformanceTest to "first class variant"

### ISSUE THREAD

**Issue by liuche** [mozilla-mobile/fenix#6464]
### Why/User Benefit/User Problem
Performance tests must be run on builds that are as close as possible to release with the debuggable flag set.

The performance build variant was added because the debug variant does not have telemetry enabled (#6447 for enabling it). However, e.g. if we complete that issue, we may be able to remove the variant: let's investigate!

If we can't remove it, we should make sure it's treated as a proper build variant, e.g. by making code using it exhaustive.

### Impact
When making changes, the performance build variant is a special case and can be confusing, especially for non-performance engineers. For example, this may have caused a crash:

> it's because when we changed the build types we missed updating the build names somewhere else.
>
> (because the string was using old build variants)

That's `Config.channel`: https://github.com/mozilla-mobile/fenix/blob/master/app/src/main/java/org/mozilla/fenix/Config.kt#L40

### Acceptance Criteria (how do I know when I’m done?)
- Decide if the performance variant should be removed. Consider:
  - Should perf builds be minified/proguarded? If not, we may be able to use the debug variant
  - That non-Android perf eng should be able to easily make a build without modifying source code
- If we decide to remove it:
  - Ensure replacement variant is capable of doing perf runs
  - Remove perf variant
  - Provide instructions for perf eng to make a build without modifying source code (can be as simple as specifying a build variant in the readme)
- If we decide to keep it:
  - Ensure all uses of BuildConfig are exhaustive. See below for an example
  - Ensure [`Config.channel`](https://github.com/mozilla-mobile/fenix/blob/master/app/src/main/java/org/mozilla/fenix/Config.kt#L40) is exhaustive (i.e. perf is included and the `else` case is a crash).

---

Note: [this was the patch](https://github.com/mozilla-mobile/fenix/pull/6462/files) that fixed the issue.

**Comment by mcomella** [comment]
I did an analysis into our build variants (https://github.com/mozilla-mobile/fenix/issues/6931) and we decided to keep `forPerformanceTest`: repurposing this bug to make it a first class variant. This includes:
- Disable StrictMode logging in forPerformanceTest builds
- Fix captured Exception for “invalid” variant forPerformanceTest (i.e. the issue described in comment 0)
- Investigate if further work is needed

**Comment by mcomella** [comment]
Raising priority as a follow-up to my recommendations on build variants: https://github.com/mozilla-mobile/fenix/issues/6931

**Comment by mcomella** [comment]
I submitted a PR for my code changes: https://github.com/mozilla-mobile/fenix/pull/7319

Once that lands, I'll send out the email.

**Comment by mcomella** [comment]
PR merged: no more dev work needed.

**Comment by mcomella** [comment]
QA not needed: no user facing changes & a straight refactor. If we were to QA, we should check:
- Gecko logging still only in debug mode
- Strict mode logging still only in debug mode

**Comment by sblatz** [comment]
@AndiAJ are you please able to verify the logs as mentioned in [Mike's comment](https://github.com/mozilla-mobile/fenix/issues/6464#issuecomment-569759219) 😄

**Comment by AndiAJ** [comment]
Hi, I've just checked the following:

1. Debug build (used variant **geckoNightlyDebug** ) 
Checked for violations using `adb logcat -d | findstr "StrictMode policy violation"` and **resulted in this output.**
[StrictMode.txt](https://github.com/mozilla-mobile/fenix/files/4026865/StrictMode.txt)

2. Production build (**Nightly Build #20060605 from 01/06**)
Checked for violations using `adb logcat -d | findstr "StrictMode policy violation"` - **no output was generated.**

❔ Still, not quite sure how to properly check the **Gecko debug logging**.

@mcomella - Please review the above, and many thanks for helping me out  . ☺️

**Comment by mcomella** [comment]
@AndiAJ Your steps look good to me (assuming `findstr` is like `grep`) – thanks for verifying!
