### ISSUE TITLE
[Bug] Alt sent for AltGraph with physical keyboard

### ISSUE THREAD

**Issue by CendioOssman** [mozilla-mobile/fenix#6471]
## Steps to reproduce
1. Attach physical keyboard
2. Configure Swedish layout
3. Go to https://dvcs.w3.org/hg/d4e/raw-file/tip/key-event-test.html
4. Click the input field
5. Press AltGr

### Expected behavior
A `keydown` event with `key` set to `AltGraph`.

### Actual behavior
A `keydown` event with `key` set to `Alt`.

### Device information

* Android device: Pixel C
* Fenix version: 2.3.0

**Comment by CendioOssman** [comment]
Also seen in Chrome:

https://bugs.chromium.org/p/chromium/issues/detail?id=1021856

**Comment by boek** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1639090

**Comment by CendioOssman** [comment]
This is even worse now. Alt presses aren't seen at all, instead they seem to open some emoji keyboard. Other keys (like `ö`) are also behaving very oddly, generating composition events.

Tested with the same Pixel C, but with Firefox 85.1.3.

Please reopen.
