### ISSUE TITLE
Update proxy designs based on learnings from UR

### ISSUE THREAD

**Issue by topotropic** [mozilla-mobile/fenix#6473]
Update designs based on insights from https://github.com/mozilla-mobile/fenix/issues/5941

Explore ways to 
- show that proxy is working (IP,...)
- make it clear what people get right from the get-go ("it's free and it's useful in this situation" --> align with real world use cases)
- simplify the welcome screen and separate two key messages: protection and passes

**Comment by kbrosnan** [comment]
We did not end up perusing this and if we do something similar in the future a new set of issues would be best.
