### ISSUE TITLE
Microphone/Camera notification: Show which site is using device

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/fenix#6477]
### Why/User Benefit/User Problem
When a website is using the camera or the microphone we show an ongoing notification to make the user aware. In a discussion on Slack it came up that it would be helpful to mention which site/tab is currently using this device.

This is implemented in AC and I checked that we know which site(s) are using the device(s). Filing this here in Fenix so that it can get a product priority.

### Acceptance Criteria (how do I know when I’m done?)
- Notification mentions which site is using the device (URL, title, ..?)
- Notification adapts if multiple sites are using device(s).
- Notification does not reveal site URL, title etc. if a private tab is using the device(s) (Show same notification as we do now?)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-14281)

**Comment by kbrosnan** [comment]
This seems to be done?

**Comment by pocmo** [comment]
Oh, do we? I can't find anything in the AC code that exposes the URL or website title. I think?

**Comment by kbrosnan** [comment]
Hm, now I am not seeing it. Maybe I got confused with notifications from testing Fennc.

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1795388

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
