### ISSUE TITLE
Offline access to previously open tab content (after restart or refresh)

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/fenix#6478]
Why/User Benefit/User Problem

As a user, I want to be able to retrieve my previously open tabs when I don't have a network connection so I can continue consuming content without interruption.

[Feature Brief](https://docs.google.com/document/d/1_lbVYHouBVqYBrt41MDA8L1PqUNJQNNyD2nRAu8o9oc/edit#)

### Acceptance Criteria

- [ ] If I lose my connection, I can still restart my browser and access all previously open tabs.
- [ ] If I lose my internet connection, I can still refresh an existing open tab and view the site content.

Current state:

![Screenshot_20200329-153829](https://user-images.githubusercontent.com/42752644/77858915-7a795980-71d4-11ea-923d-2a6d7c901d57.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-14282)

**Comment by liuche** [comment]
Action here is to file a Bugzilla ticket (already discussed with Emily Toop) with GV from engineering perspective to explain what GV APIs we need to accomplish restoring previously loaded tabs when there's no internet connection.

**Comment by vesta0** [comment]
As part of this investigation we first need to first define the bounds of what we want to save (how many tabs, how much content on the page, media, etc) before filing the GV bug. For example: our MVP for this could be (1) recent tabs only from the past 24 hours) and (2) text pages only

**Comment by re-hub** [comment]
Is mhtml a feasible solution?

**Comment by madb1lly** [comment]
Since this is a Spike the Fenix team should confirm if it was implemented.
Cheers 🙂

**Comment by madb1lly** [comment]
Hi Fenix team, @vesta0,
From my testing last night this is still not implemented.
Cheers 🙂

**Comment by madb1lly** [comment]
Yep, still not working well, at least not as well as Fennec.
Cheers 🙂

**Comment by madb1lly** [comment]
Not fixed.

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1809311

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
