### ISSUE TITLE
[Bug] Choice of private/non-private open not respected in Android sharing dialog

### ISSUE THREAD

**Issue by flaki** [mozilla-mobile/fenix#6481]
## Steps to reproduce

* Fenix Nightly is `Set as default browser`, also ☑ `Open links in private tab`.
* Open any other app (here: Twitter)
* Open tweet, choose Share, in the sharing dialog choose `Firefox Nightly` as a share target (as opposed to the `Firefox Nightly (Private Firefox)` target

### Expected behavior

* The shared link opens in a **non-private** tab

### Actual behavior

* The shared link opens in a private browsing tab

### Device information

* Android device: Google Pixel 3, Android 10
* Fenix version: Nightly 191106 06:21 (Build #13100630)

### Detailed description

I use Fenix as a "Firefox Focus"-replacement, that is, it is my default browser on my phone and I expect websites (e.g. article links I click on in the Twitter app) to open in private browsing mode.

However, I use the Twitter app with many accounts on my phone, and part of my workflow involves sharing individual tweets to the browser. I have two usecases with Fenix for this, one is for sending the tweet to another device, and the other being reopening the tweet in my browser to interact with it. In my browser I am signed in to Twitter with my personal account and using it as a progressive webapp. While I switch often between accounts in the Twitter app, I can always be sure that by reopening tweets in the browser I'm interacting with them using my private account.

The above behavior makes my normal workflow quite a hassle, as no matter which target I click in the sharing dialog, the tweet always opens in a private tab. For tweets that I want to interact with, then I have to copy the URL, go into the tab view, switch out of private mode, tap the URL bar and paste the link again to be able to interact with my logged-in persona. This is cumbersome and counter-intuitive (why offer a "private" share target if the one not labelled with "private" is also private?). I understand that the "Open links in private tab" setting might confuse some, but I expect that sharing explicitly to the browser should not trigger the private tab functionality unless it is explicitly selected from the sharing targets.

![photo5915704906755453304](https://user-images.githubusercontent.com/2089432/68336985-dafde200-00df-11ea-8503-150dd77e7abf.jpg)

**Comment by boek** [comment]
So this _was_ actually working as intended. The behavior you would have wanted would have been to uncheck the open links in a private tab and then use the appropriate launcher. Though, due to some difficulties getting this feature to actually work (#5972) we've had to remove this option for now :(

**Comment by flaki** [comment]
@boek I'm not sure what you meant here by _"working as intended"_, based on your comment.

> The behavior you would have wanted would have been to uncheck the open links in a private tab and then use the appropriate launcher.

I believe this is not true (unless I misunderstand something about the feature's intended usage). Quoting from my original report:

> I use **Fenix** as a "Firefox Focus"-replacement, that is, it **is my default browser** on my phone and **I expect websites** (e.g. article links I click on in the Twitter app) **to open in private browsing mode.**

Meaning, that I explicitly want the toggle to be toggled on, since many apps don't give you the launcher option when you click links in them, that point outside of the app. The Twitter native app is a good example but there's a myriad of others. I want these links to always open in private browsing mode in Firefox, hence I set it to default browser and expect links to open in private browsing whenever handling these URL opens.

The launcher (and thus, choice of normal and private-browsing Firefox) option is only offered upon a "share" intent, and is not the default action for most link opens in apps.
