### ISSUE TITLE
Current Session Header Showing Up

### ISSUE THREAD

**Issue by Sdaswani** [mozilla-mobile/fenix#649]
## Steps to reproduce
1) Clear all sessions and restart fenix
2) Try to open a url
3) abort that attempt
4) click around of screen

### Expected behavior
You can't open the current session header without a webpage loaded

### Actual behavior
![screenshot_20190223-072033_fenix](https://user-images.githubusercontent.com/4879954/53289183-9b58bb00-3747-11e9-996f-5fad63a1bf99.jpg)

Video: https://photos.app.goo.gl/DGupkDy7k4yYy8sP7

### Device information

* Android device: Galaxy S8
* Fenix version: Build 10531210

**Comment by Sdaswani** [comment]
This is also easy to repro in private mode.

**Comment by vesta0** [comment]
Fixed :)
