### ISSUE TITLE
[Bug] Private browsing session notification no longer showng

### ISSUE THREAD

**Issue by neekless** [mozilla-mobile/fenix#6491]
## Steps to reproduce
1. Switch to private mode. 
2. Launch a private tab. 

### Expected behavior
Private browsing session notification (with 'open' and 'delete and open' shows. 

### Actual behavior
The notification has stopped showing. I did not turn off the notification channel in app settings. 
![Screenshot_20191107-093057](https://user-images.githubusercontent.com/22426822/68352443-59697c80-00fe-11ea-8d7b-724be675cc7b.jpg)

### Device information
* Android device: Pixel 2xl Android 9 
* Fenix version: Nightly 191106 18:00 (Build #13101805)
📦: 20.0.0, 1bae81951
🦎: 72.0a1-20191103094618
But it actually started a couple of nightlies ago.

**Comment by mcarare** [comment]
Could not reproduce. 
Tested on Huawei P10 (Android 9) with Nightly 191107 (Build #13110607)

**Comment by neekless** [comment]
My bad I had accidentally enabled background battery restrictions. Will close.
