### ISSUE TITLE
[Bug] Outdated page shows when pressing back

### ISSUE THREAD

**Issue by ktaeleman** [mozilla-mobile/fenix#6495]
## Steps to reproduce

Not 100% reproducible.
Got to engadget.com, navigate away from engadget to random site like cbc.ca, navigate back to engadget.com, click an article midway page, press back.

### Expected behavior
Page returns to up to date content of digg.com

### Actual behavior
Page is out of date with content from your first visit to digg.com

### Device information

* Android device: Pixel 3 XL with webrender enabled
* Fenix version: 20191103094618

**Comment by AaronMT** [comment]
#6493
