### ISSUE TITLE
If no open tabs in current session, should delete button be disabled?

### ISSUE THREAD

**Issue by Sdaswani** [mozilla-mobile/fenix#650]
## Steps to reproduce
1) clear all sessions and restart fenix
2) Get the current session header to appear (see bug https://github.com/mozilla-mobile/fenix/issues/649)
3) click the three dot menu

### Expected behavior
Delete button should be disabled

### Actual behavior
Delete button can be selected
![screenshot_20190223-075035_fenix](https://user-images.githubusercontent.com/4879954/53289233-6436d980-3748-11e9-855c-8100ecc566a0.jpg)

### Device information

* Android device: S8
* Fenix version: Same version from https://github.com/mozilla-mobile/fenix/issues/649

Perhaps if 649 is fixed this issue is moot .

**Comment by vesta0** [comment]
This is fixed :)
