### ISSUE TITLE
Add ability to select Webpage Content Language

### ISSUE THREAD

**Issue by liuche** [mozilla-mobile/fenix#6502]
### Why/User Benefit/User Problem
Some sites might have different language options, and this would allow users to express their choice in webcontent language.

### What/Requirements
- [ ] User can select language for web content

**Mocks**: https://miro.com/app/board/o9J_kwN9u-I=/

GV honors the system language by default (i.e. Gecko's HTTP requests set the `Accept-Language` HTTP header to match the system language, issue #940). Fenix can override Gecko's list of preferred languages using the `GeckoRuntimeSettings#setLocales` API:

https://mozilla.github.io/geckoview/javadoc/mozilla-central/org/mozilla/geckoview/GeckoRuntimeSettings.html#setLocales-java.lang.String:A-

### Acceptance Criteria (how do I know when I’m done?)
- [ ] Add "Webpage content" screen

### Does NOT include
- Language picker for browser UI #220

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-14298)

**Comment by argymeg** [comment]
Seeing as there's been very little activity on this bug, I'd like to restate my privacy concerns as stated in my related bug that was closed as a duplicate, above. This is has extremely severe privacy implications for speakers for minority languages. In many cases a user's real IP + system languages are enough to identify a user to within a few hundred people, to every single website they use. As far as I can tell Fenix currently offers no workable way around this.

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813236

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
