### ISSUE TITLE
Define and measure Fenix cold start to homescreen perf test

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#6507]
Blocked by?:
- cold/warm/hot definitions: https://github.com/mozilla-mobile/fenix/issues/5910

### Why/User Benefit/User Problem
Our key P1 metric for our release criteria is cold startup to homescreen: we need to have a test we can rely on to measure it.

Currently, we are running Nimbledroid's default cold startup test: we should determine if this is appropriate. If not, we should write a new test.

### Impact
Without this, we cannot measure our proposed release criteria.

### Acceptance Criteria (how do I know when I’m done?)
- Use Nimbledroid default cold startup test OR implement our own cold startup test
- Remove https://github.com/mozilla-mobile/fenix/issues/6307 from Waiting column

**Comment by mcomella** [comment]
mconley mentioned desktop's automation tests use the same metrics as their telemetry (e.g. cold startup automation just prints the cold startup probe; our cold start telemetry in #5912). This feels like a good idea to me and suggests to me that we should write our own test.

However, it will make it more work for us to measure ourselves against other products (e.g. Fennec 68, Chrome) because each test will need to be uniquely written.

We could also consider a hybrid approach of using the default cold start test in the short term and switching to telemetry in the long term.

**Comment by hawkinsw** [comment]
@mcomella http://docs.nimbledroid.com/androidUserGuide.html#cold-startup-measurement-exit-point

**Comment by mcomella** [comment]
We did this as much as we need to.
