### ISSUE TITLE
Landscape Mode Can't Scroll Through All Sessions

### ISSUE THREAD

**Issue by Sdaswani** [mozilla-mobile/fenix#651]
## Steps to reproduce
1) Get a couple of tabs in current session going
2) Flip to landscape mode

### Expected behavior
You can scroll through all sessions in landscape mode

### Actual behavior
One cannot. https://photos.app.goo.gl/bYyPykmg6y2MBicRA

### Device information

* Android device: Galaxy S8
* Fenix version: Same version as #649

**Comment by boek** [comment]
This is now fixed
