### ISSUE TITLE
What's new card after app update

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/fenix#6510]
## User Story
- As a user, I want to know what changes I should expect in my browser after an update, so I know what's been fixed and which new features to check out.

### Acceptance Criteria
- I effortlessly learn about new features and bug fixes after app update
- In select cases, I can interact with the what's new card (e.g. to enable a new add-on)

**Comment by vesta0** [comment]
@apbitner I remember you demoing this 2 weeks ago, is it `eng:ready` ?

**Comment by apbitner** [comment]
@vesta0 that was concept work so there hasn't been anything done on it since then. I think it should continue to be worked on as part of the feature discoverability meta #9684

**Comment by lime124** [comment]
Agree with Adam -  I believe that was shown during UX office hours and was just early explorations/work in progress. This should be kept as part of feature discovery work so we make sure all our surfaces are working together and we avoid over-messaging. Thanks Vesta!

**Comment by apbitner** [comment]
As with #9328, this work should be considered with home screen redesign exploration.
