### ISSUE TITLE
User knows when data migration is completed

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/fenix#6511]
## User Story
- As a Fennec user who just upgraded to Fenix, I want to know that my data is being migrated ad when the migration is completed, so I have transparency into the process and know when my new browser is ready to use. 

## Dependencies
-Work with Android Components team to determine requirements (how long data migration will take, what should the user expect during and after?_

### Acceptance Criteria
- When I first run Fenix, I see a prompt/dialogue letting me know that my data is being migrated.
- I know how long I need to wait before I can use my browser. 

**This is part of [Meta] Fennec -> Fenix Migration User Experience #879**

**Comment by liuche** [comment]
This is basically a combination of two issues - notification, and progress, so I'm going to close this. Notifications will be done by AC.
