### ISSUE TITLE
[Bug] Crash when tapping on "Read our privacy notice" from the onboarding tour

### ISSUE THREAD

**Issue by softvision-miralobontiu** [mozilla-mobile/fenix#6514]
## Steps to reproduce
1. Install Firefox Preview.
2. Scroll down the onboarding tour to "Your privacy" card and tap on "Read our privacy notice".

### Expected behavior
A new page is opened: https://www.mozilla.org/en-US/privacy/firefox/ in a custom tab.

### Actual behavior
The app crashes.

### Device information
* Android device: Samsung Galaxy Note 8 (Android 9)
* Not reproducible on Google Pixel 3A XL (Android Q), Xiaomi Mi Pad 2 (Android 5.1), Samsung Galaxy Tab A (Android 9)
* Fenix version: 3.0.0-beta.1 (#13112229), and 11/08 Nightly build (13120608)

[logcat.txt](https://github.com/mozilla-mobile/fenix/files/3823923/logcat.txt)

![crash](https://user-images.githubusercontent.com/40694158/68466345-e145a880-021c-11ea-8711-d70799a2f3e5.gif)

**Comment by BranescuMihai** [comment]
De-assigned myself because I couldn't reproduce it. Tried on: OnePlus3, Samsung S9 (android 9), Samsung S10 (android 9)

**Comment by sblatz** [comment]
I cannot reproduce this on master. Galaxy S9 (Android 9)

**Comment by ekager** [comment]
I also cannot reproduce. Could we retest this in the latest nightly since it seems like no one can reproduce it?

**Comment by softvision-miralobontiu** [comment]
Hi all!
I was able to reproduce it again today with Samsung Galaxy Note 8 (Android 9), with 11/21 @6:06 AM Nightly build, with 3.0.0-beta.1 build, and with 2.3.0 RC build.

Not reproducible on Huawei P9 Lite (Android 7, Google Pixel 3 (Android Q), and Samsung Galaxy S8 (Android 9).

**Comment by boek** [comment]
Hmm.. I'm not seeing a crash in that logcat either :(

**Comment by sv-sdeiac** [comment]
Hello, I am able to reproduce the crash with Samsung Galaxy Note 8 (Android 9), with 12/30 @6:26 AM nightly build and 3.0.0-beta.3 build.
There is a logcat with the error from the Nightly and beta build. I hope it helps you guys.
[crash_nightly.txt](https://github.com/mozilla-mobile/fenix/files/4009366/crashprivacynightly.txt)
[crash_beta.txt](https://github.com/mozilla-mobile/fenix/files/4009367/crashprivacybeta.txt)
If I can help with anything else, please let me know.

**Comment by ekager** [comment]
Can we retest on the affected device to see if this is still happening?

**Comment by sv-sdeiac** [comment]
Hi, I can confirm that this crash is not reproducible using the latest version of Firefox Preview Nightly 5/13 #21340609.

Device: Samsung Galaxy Note 8 (Android 9).
