### ISSUE TITLE
[Bug]Wrong PB icon displayed on Android 10 devices when sharing a link 

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#6515]
## Steps to reproduce
1. Navigate to theverge.com
2. Long tap on one of the featured articles or images
3. Select "Share link" from the context menu
4. Observe the Fenix PB icons from the list 

### Expected behavior
The specific Private Firefox Preview icon should be displayed in the sharing list ![rsz_screenshot_20191109-205837](https://user-images.githubusercontent.com/51314259/68468061-f53ed980-021f-11ea-985e-e49c7abc0bc6.png)

### Actual behavior
The default Firefox preview icon is displayed for the Private Firefox Preview option![rsz_screenshot_20191108-113424](https://user-images.githubusercontent.com/51314259/68468128-1273a800-0220-11ea-9fa0-6baf861dea21.png)

### Device information

* Android device: 
• Google Pixel (Android 10)
• Google Pixel 3a XL (Android 10)

* Fenix version: 
• RC 2.3.0 Build #13031728 from 30/10
• Beta 3.0.0-beta.1  Build #13112229 from 7/11
• Nightly Build #13120608 from 8/11

### Notes
Not reproducible on:
• Google Pixel 3a XL (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

► Screenshot from Google Pixel 3a XL (Android **9**) ✔️
![Screenshot_20191109-205837](https://user-images.githubusercontent.com/51314259/68468393-9f1e6600-0220-11ea-9f6e-d4981aacddf4.png)

► Screenshot from Google Pixel 3a XL (Android **10**) ❌
![Screenshot_20191108-114229](https://user-images.githubusercontent.com/51314259/68468597-01776680-0221-11ea-9748-4a2d389c3e24.png)

**Comment by boek** [comment]
due to some difficulties getting this feature to actually work (#5972) we've had to remove this option for now :(
