### ISSUE TITLE
[Bug]Open image in new tab outputs a 0% scaled image.

### ISSUE THREAD

**Issue by Sgt-Miller** [mozilla-mobile/fenix#6518]
## Steps to reproduce
Long press an image and choose open image in new tab. Now go to the new tab.
### Expected behavior
![Screenshot_20191108-160009](https://user-images.githubusercontent.com/17806210/68469807-ce2ddb00-0212-11ea-9904-86c0b2d6645e.png)

### Actual behavior
Temporarily, I just reload the tab to make the image appear properly. Before reloading, this is how it looks.
![Screenshot_20191108-160019](https://user-images.githubusercontent.com/17806210/68469813-d38b2580-0212-11ea-922a-30857cd9be96.png)

Comparison of scale(don't know what that exactly means). Look at the tab titles.   
![Screenshot_20191108-160024](https://user-images.githubusercontent.com/17806210/68470082-48f6f600-0213-11ea-99f9-cbbe8edda417.png)

### Device information 
2.3.0 (Build #13031728)
📦: 18.0.0, ef631b6df
🦎: 70.0-20191014032640
Android 8

**Comment by cadeyrn** [comment]
Duplicate of #2312. Will be fixed once Fenix uses GV 71.

**Comment by Sgt-Miller** [comment]
Sorry! It seems I'm really bad at searching.
