### ISSUE TITLE
[Bug]Saved images are not properly names (can't open from in app notif, no name in notif)

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#6519]
## Steps to reproduce
1. Navigate to theverge.com
2. Long tap on one of the featured articles or images
3. Select "Save image" from the context menu
4. From the Android taskbar tap on the download confirmation to open the downloaded image 

### Expected behavior
The image should be opened after tapping the notification

### Actual behavior
The downloaded image isn't opened after tapping the notification

### Device information

* Android device: 
• Google Pixel 3a XL (Android 10)
• Google Pixel 3a XL (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)

* Fenix version: 
• Beta 3.0.0-beta.1 Build #13112229 from 7/11
• Nightly Build #13120608 from 8/11

### Notes
► Video
![20191108_124622](https://user-images.githubusercontent.com/51314259/68471301-8ca72b00-0226-11ea-98c5-fb858f38913b.gif)

**Comment by sblatz** [comment]
This is effectively the same issue as https://github.com/mozilla-mobile/fenix/issues/6576. Something is going wrong when downloading with "save image" that is causing both of these symptoms.

**Comment by sblatz** [comment]
So two things I've discovered: 
1) The "open" fails because it's not pointing to the correct file name. 
2) The download notification will open the image when tapped, so it **is** properly downloading, it's just not getting its file name properly set.

**Comment by sblatz** [comment]
Will be fixed by https://github.com/mozilla-mobile/android-components/pull/5151

**Comment by AndiAJ** [comment]
> So two things I've discovered:
> 
> 1. The "open" fails because it's not pointing to the correct file name.
> 2. The download notification will open the image when tapped, so it **is** properly downloading, it's just not getting its file name properly set.

@sblatz - You are right! :relaxed:

I've re-checked this matter and it is **still reproducible** on the latest **Nightly Build #13310607 from 11/27** using the following devices:
• Google Pixel 3a XL (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)

► Video from Samsung S7 using Fenix
![20191127_122500](https://user-images.githubusercontent.com/51314259/69716113-12294700-1112-11ea-9cc4-6d2d75cec36a.gif)

► Video from Samsung S7 using Fennec
![20191127_122704](https://user-images.githubusercontent.com/51314259/69716214-4bfa4d80-1112-11ea-88e1-77fb1f890ba8.gif)

**Comment by sblatz** [comment]
Hi sorry about that, the AC version hadn’t been updated yet. It should be good to test in the next nightly!

**Comment by sv-ohorvath** [comment]
See https://github.com/mozilla-mobile/fenix/issues/6615#issuecomment-559784673

**Comment by sblatz** [comment]
Looks to be fixed 🎉 

![Untitled 2019-12-10 08_55_14](https://user-images.githubusercontent.com/4400286/70550593-d7200e00-1b2a-11ea-9574-3c647b855ff8.gif)


QA it should be in nightly tomorrow or working on master :)

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **Nightly Build #13450608 from 12/11** using the following devices:
• Google Pixel 3a (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• Motorola G4 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

► Video
![20191212_124950](https://user-images.githubusercontent.com/51314259/70615665-7faa9c80-1c15-11ea-8213-ce48013018f3.gif)
