### ISSUE TITLE
homescreen shows two tabs in the current session for "About Fenix" page

### ISSUE THREAD

**Issue by cadeyrn** [mozilla-mobile/fenix#652]
## Steps to reproduce

1. Start Fenix
2. press menu button
3. press settings button
4. press "About Fenix" button
5. press tabs button in address bar

### Expected behavior

there is only one tab below the "Current Session" caption

### Actual behavior

Two tabs are shown in the current session.

### Device information

* Android device: HTC U11 / Android 8.0
* Fenix version: revision 3ccce1b4d264362f6043f662ea5639c5a2d879bd

**Comment by ekager** [comment]
This seems to be fixed in master, please reopen if you're still seeing it!
