### ISSUE TITLE
[Bug]Setting Fenix Beta as the default browser app doesn't open by default the TWAs

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#6522]
## Prerequisites
Set Fenix Beta as you default browser app.
Have installed also Fenix Nightly

## Steps to reproduce
1. Install one of the bellow TWAs
https://play.google.com/store/apps/details?id=com.tigeroakes.insightfulenergy
https://play.google.com/store/apps/details?id=com.appspot.pwa_directory
https://play.google.com/store/apps/details?id=br.com.quintoandar.inquilinos
https://play.google.com/store/apps/details?id=com.myntra.android
https://play.google.com/store/apps/details?id=com.bookinglokal
https://play.google.com/store/apps/details?id=webgears.com.dead.trails

2.  Open the TWA
 
### Expected behavior
The TWA should be opened by default in Fenix Beta

### Actual behavior
The TWA is opened in Chrome. (Even if the default browser is Fenix Beta)
If you disable Chrome, The TWA will be opened in Fenix Nightly (Even if the default browser is Fenix Beta)

### Device information

* Android device: 
Google Pixel 3a XL (Android 9)
Google Pixel 3a XL (Android 10)

* Fenix version: Beta 3.0.0-beta.1 Build #13112229 from 7/11

**Comment by NotWoods** [comment]
TWA support is currently staying in Nightly while we experiment with it. We'll revisit this later on.
