### ISSUE TITLE
Redundant back button on history/bookmarks

### ISSUE THREAD

**Issue by hakkikaancaliskan** [mozilla-mobile/fenix#6523]
## Steps to reproduce
Open history/bookmarks from homescreen.

Back button is redundant because back button and close button doing same thing, throws us to homescreen.

![68072285-d60dfb00-fd8c-11e9-96d8-52e5f674cca8](https://user-images.githubusercontent.com/17825767/68486923-098fd000-023a-11ea-8de9-c4582e1fed8a.png)

### Device information
Nightly 191108 06:01 (Build #13120608)
📦: 21.0.0, 09da19708
🦎: 72.0a1-20191105095755
Xperia XZ1, Android 9

**Comment by NotWoods** [comment]
UX team: Should we remove the back button, the close button, or keep both?

**Comment by topotropic** [comment]
We can remove the x (close button). Thanks!

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on **Debug Build from Master 1.0.1947 (Build # 1) 📦: 23.0.0, 9b8e27603 🦎: 72.0a1-20191119043902 from 11/22** using the following devices:
• Google Pixel 3a XL (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

► Video
![20191122_151207](https://user-images.githubusercontent.com/51314259/69429165-a2931080-0d3b-11ea-8904-5d53896d5916.gif)
