### ISSUE TITLE
[webcontent] janky scrolling at https://m.angeloni.com.br/eletroMobile/

### ISSUE THREAD

**Issue by miketaylr** [mozilla-mobile/fenix#6524]
Originally filed at https://github.com/webcompat/web-bugs/issues/41423.

## Site with issue and any steps to reproduce

1. go to https://github.com/webcompat/web-bugs/issues/41423
2. scroll

The scrolling is jankier in Fenix than in Chrome Mobile.

**Comment by ekager** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1681873

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
