### ISSUE TITLE
[webcontent] graphics issue when scrolling steamcommunity.com

### ISSUE THREAD

**Issue by miketaylr** [mozilla-mobile/fenix#6525]
Originally reported @ https://github.com/webcompat/web-bugs/issues/43635

## Site with issue and any steps to reproduce

1. go to https://steamcommunity.com/games/593110/announcements/detail/1666821776739358716 and scroll down

### Expected behavior

It works

### Actual behavior

Either tiles will fail to be painted, or everything will end up blurry for a second or two on my Pixel 3 until it "pops" into normal resolution.

### Can you reproduce in [Firefox for Android](https://play.google.com/store/apps/details?id=org.mozilla.firefox)?

No

### Can you reproduce in Chrome (or other non-Mozilla browser)?

No

### Device information

* Android device: Pixel 3
* Fenix version: 2.3.0

**Comment by boek** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1610956
