### ISSUE TITLE
[Bug] Can't tap on "Sign into Google" button with Tracking Protection enabled

### ISSUE THREAD

**Issue by liuche** [mozilla-mobile/fenix#6528]
## Steps to reproduce
Go to www.safelanes.org > "Try it now" > 3-dot menu in top left > click user account circle
On account sign-in page, click "Sign in with Google"

### Expected behavior
Allows signing in from Google

### Actual behavior
Button text can be highlighted, button text can't be clicked

Turning off Tracking Protection will allow clicking on Google sign-in button.
If **"Standard"** tracking protection is selected (instead of **strict**), can click Facebook sign-in button (but still not Google one).

![Screenshot_20191108-155927](https://user-images.githubusercontent.com/1082253/68518857-be2def80-0242-11ea-9fe8-6797c18159e9.png)

### Device information

* Android device: Pixel 3
* Fenix version: 191108 Nightly

**Comment by abodea** [comment]
Verified as fixed on Nightly 4/28 with Google Pixel 4 XL (10).
Note that I was able to login with the following settings:
 - ETP On -> set to **Standard**
- ETP On -> set to **Strict**
- Etp On -> set to **Custom**
- **ETP Off** 

Note that I added https://github.com/mozilla-mobile/fenix/issues/10262.
