### ISSUE TITLE
bad performance of "About Fenix" page

### ISSUE THREAD

**Issue by cadeyrn** [mozilla-mobile/fenix#653]
## Steps to reproduce

1. Start Fenix
2. press menu button
3. press settings button
4. press "About Fenix" button

### Expected behavior

Since it's an internal page and not a website it's expected that the page loads instantly because there is nothing Fenix has to load from network. It's a small amount of text and a logo, nothing else. The "About Firefox" page in Fennec looks more complex and it loads loads instantly.

### Actual behavior

Takes ~ two seconds.

### Device information

* Android device: HTC U11 / Android 8.0
* Fenix version: revision [3ccce1b](https://github.com/mozilla-mobile/fenix/commit/3ccce1b4d264362f6043f662ea5639c5a2d879bd)

**Comment by sblatz** [comment]
This is because we're down-scaling a rather high-quality image and injecting it into the GV page. On my S9 it loads almost instantaneously but on some devices performance may be worse. 

Seems like this is likely a low priority issue

**Comment by colintheshots** [comment]
I think most of the issue is the I/O of writing and reading BASE64 back to PNG. It shouldn't be more than 20KB, but it's still a file write, read, and decoding. Scaling down further would decrease the size by a square function, but the logo starts to get blurry.

**Comment by ekager** [comment]
We could do a bit of a hack and include a native Android ImageView for the logo with the same background color as the page. If this is the only issue with this page, that could be a fine solution?

**Comment by Sdaswani** [comment]
This is also slow on my S8 https://photos.app.goo.gl/fjM8DWJqr89GLb9y8 which is a fairly speedy device. I agree most folks won't hit this screen but it detracts from the story of Fenix as being fast.

**Comment by cadeyrn** [comment]
"About Fenix" was already a bit faster the last weeks and it's really fast now (I guess since https://github.com/mozilla-mobile/fenix/commit/379875a62a12c504ae0f48a5a6638e6e46f9d582). Feel free to reopen if you disagree.
