### ISSUE TITLE
[Bug] Browser crashes when camera is opened on instagram.com

### ISSUE THREAD

**Issue by andreasbovens** [mozilla-mobile/fenix#6534]
## Steps to reproduce
Log in on instagram.com
Tap on the camera icon in the top left corner

### Expected behavior
Camera / camera permission prompt is shown.

### Actual behavior
Browser crashes

### Device information

* Android device: OnePlus 5
* Fenix version: Nightly 72

**Comment by julienw** [comment]
Could be #6279 ?

**Comment by sblatz** [comment]
This seems to be fixed now. I think @julienw was right here :)

**Comment by sv-sdeiac** [comment]
Verified as fixed using the latest version of Firefox Preview Nightly 12/30 #13640626.

Devices:
- LG g7 fit (Android 8.1);
- Samsung Galaxy S8 (Android 9);
- OnePlus 5T (Android 9);
- Google Pixel (Android Q).
