### ISSUE TITLE
[UX] Easy access to top share app

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/fenix#6537]
## User Story
- As a user, I want a quick easy way of sharing to the app I most frequently use for sharing, so I can save time.

In both Chrome and Fennec, the top share app shows up as an icon in the browser toolbar menu.

### Acceptance Criteria
- I can quickly share a page to the app I most frequently use for sharing.
- [Telemetry Ticket] Track how often users choose to tap on the top share app.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-14324)

**Comment by BranescuMihai** [comment]
@vesta0 Isn't this the same as [#4231](https://github.com/mozilla-mobile/fenix/issues/4231)?

**Comment by vesta0** [comment]
Not exactly but related! This is about quick access to the top share app only - which we may not need if we re-design the share sheet. 

Example from Fennec (Pocket being my top share app):

![Screenshot_20200213-144909](https://user-images.githubusercontent.com/42752644/74472660-4dfdbe00-4e70-11ea-960f-618992a963ed.png)

**Comment by AmyYLee** [comment]
Assigning to @topotropic

**Comment by madb1lly** [comment]
This is still valid.
Cheers 🙂

**Comment by tjkirch** [comment]
Not stale.

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1809792

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
