### ISSUE TITLE
Option to disable swipe on collections

### ISSUE THREAD

**Issue by yaomtc** [mozilla-mobile/fenix#6538]
### Why/User Benefit/User Problem
Several times I've accidentally swiped away an item in a collection when I was meaning to scroll down. (Also, the "undo" option didn't appear last time this happened. Isn't it supposed to, or is that just tabs?)

### What/Requirements
An option in a menu somewhere, or in about:config (once that gets added back in) to disable swipe-to-remove on Collections.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-14325)

**Comment by yaomtc** [comment]
Can confirm that the "undo" prompt still does not appear when swiping away collection items. Too many times I've accidentally swiped something away without realizing, and I can't remember what was there.

**Comment by boek** [comment]
Dup of #12408
