### ISSUE TITLE
back and forward buttons don't have a (visual) disabled state

### ISSUE THREAD

**Issue by cadeyrn** [mozilla-mobile/fenix#654]
## Steps to reproduce

1. open a website in Fenix
2. press the menu button

### Expected behavior

The back and the forward button should be disabled because you can't navigate back and you can't navigate forward until you navigate to another page. Alternatively, only the forward button should be disabled if - like in Fennec - the back button brings you back to the homescreen but that's not the current behaviour of Fenix.

### Actual behavior

The back and the forward button always look enabled.

### Device information

* Android device: HTC U11 / Android 8.0
* Fenix version: revision [3ccce1b](https://github.com/mozilla-mobile/fenix/commit/3ccce1b4d264362f6043f662ea5639c5a2d879bd)

**Comment by ekager** [comment]
@vesta0 I assume you reopened this because the menu items do not respond while the menu is open to changes in the browser? 
This will depend on A-C work, specifically https://github.com/mozilla-mobile/android-components/issues/170
