### ISSUE TITLE
[Bug] Overwriting files with the same name

### ISSUE THREAD

**Issue by xxkfqz** [mozilla-mobile/fenix#6541]
## Steps to reproduce

Download same and/or different files with the same name (e.g. `0.jpg`) multiple times.

### Expected behavior

Some enumerated files with same name:
* `0.jpg`
* `0.jpg (1)`
* `0.jpg (2)`

### Actual behavior

Overwriting original file. Only last downloaded file will be saved.

### Device information

* Android device: Xiaomi Redmi 6A, Android 8.1
* Fenix version: 2.3.0

**Comment by sblatz** [comment]
QA, can you verify this is happening? 

I believe this should already be working: https://github.com/mozilla-mobile/android-components/pull/4759/files#diff-1afe9814d5a6a01d2409ea692e25e725R99-R107

**Comment by BranescuMihai** [comment]
Will be fixed by this: [5046](https://github.com/mozilla-mobile/android-components/issues/5046), please retest afterwards

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **Nightly Build #13290608 from 11/25** using the following devices:
• Google Pixel 3a XL (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

► Video
![20191125_122509](https://user-images.githubusercontent.com/51314259/69538524-33abf680-0f8b-11ea-9d89-98c8798dc5c3.gif)

► Video
![20191125_122835](https://user-images.githubusercontent.com/51314259/69538594-59d19680-0f8b-11ea-8835-31cb4041bf82.gif)
