### ISSUE TITLE
[Bug] The keyboard remains displayed after creating a new folder

### ISSUE THREAD

**Issue by sv-sdeiac** [mozilla-mobile/fenix#6543]
## Steps to reproduce
1. Create a new bookmark folder and tap on the name field;
2. Write a name and tap on the create button.

### Expected behavior
When you exit from the creation mode, the keyboard is hidden.

### Actual behavior
The keyboard remains on top when you exit the creation mode.

### Device information

* Android device: Xiaomi Mi Pad 2 (Android 5.0.1), Samsung Galaxy Note 8 (Android 9), Samsung Galaxy tab A(Android 9);
* Fenix version: 3.0.0-beta.1 (#13112229), and RC 2.3.0 (#13031730)

**Comment by sv-ohorvath** [comment]
This is verified as fixed on Nightly 11/13.
I have 2 new related bugs: #6593, #6594
