### ISSUE TITLE
[Bug] Fenix not offered as handler for browser keyboard shortcut

### ISSUE THREAD

**Issue by callahad** [mozilla-mobile/fenix#6545]
## Steps to reproduce

* Connect Bluetooth keyboard to Android device
* Press <kbd>Search</kbd> + <kbd>b</kbd>

### Expected behavior

* Fenix is offered as a handler for the system-wide Browser shortcut

### Actual behavior

* Fenix is not present in the list of suggested apps. Chrome and Fennec are listed:

    ![android-search-b-shortcut](https://user-images.githubusercontent.com/24193/68597593-22e08880-0495-11ea-8ee6-e822e6fb1dbc.png)

### Device information

* Android device: Pixel 3a
* Fenix version: Nightly 191109

**Comment by sblatz** [comment]
Is this an accessibility concern? @MReschenberg

**Comment by MReschenberg** [comment]
I'm not super confident either way; I think its an a11y issue in that it breaks a well-established pattern (users will expect to see fenix reflected in that list). As far as "is this a problem specifically for users with assistive tech" probably not, or at least, not any more than it is for users who aren't using assistive tech.

**Comment by MReschenberg** [comment]
@eeejay unsure if you're on holiday leave or officially back, but would love another opinion

**Comment by eeejay** [comment]
Hey! I think it's a11y related in the sense hardware keyboard hookups in Android are relied on a lot by users with disabilities. So yeah, I would keep an a11y label, as to priority I can't speak.
