### ISSUE TITLE
Settings header disappears after navigating to about

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/fenix#655]
## Steps to reproduce

1. Open Fenix
2. Tap three dot menu
3. Tap Settings
4. Tap About Fenix
5. Press back
6. Scroll to top of settings page

### Expected behavior

Settings header appears with backwards facing arrow.

### Actual behavior

Settings header is gone.

### Device information

* Android device: Pixel 2
* Fenix version: 1.0.1908 (Build #10531209 :lizard: 67.0a1-20190213102848)

**Comment by sv-ohorvath** [comment]
Verified as fixed.
