### ISSUE TITLE
Investigate if we can reduce app installed size (currently 169 MB)

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#6552]
### What/user problem
The installed size of v2.3.0 is 169 MB on my Pixel 2 (N.B.: this _excludes_ user data and cache): this seems rather large, especially compared to the ~57 MB download size.

### Impact
I'm concerned users will be more likely to uninstall the app if it takes up a lot of space on their devices, especially for older devices with less storage.

### Acceptance criteria
- ?

---

I notice we don't set the `extractNativeLibs` flag ([explanation](https://stackoverflow.com/a/44704840)) so it defaults to true. This means the native libraries are copied & decompressed out to disk on installation, a little more than doubling the size they take up on device: I wonder if this could make up the entire difference.

We could also consider Android App Bundles to reduce the size.

**Comment by sblatz** [comment]
FWIW: Fennec is 174MB after installing.

**Comment by mcomella** [comment]
FWIW: Chrome is 27 MB after installing on my Pixel 2. Perhaps they use app bundles and `extractNativeLibs` to reduce their APK size.

**Comment by kbrosnan** [comment]
I don't think that is realistic comparison. Is the Blink/WebView engine counted in the 27 MB?

**Comment by mcomella** [comment]
> I don't think that is realistic comparison. Is the Blink/WebView engine counted in the 27 MB?

I verified the engine is not included in the APK and I agree that from a dev perspective it's not a realistic comparison.

However, this is what users will compare the apps :\ so we should take that into account.

**Comment by hakkikaancaliskan** [comment]
> FWIW: Chrome is 27 MB after installing on my Pixel 2. Perhaps they use app bundles and `extractNativeLibs` to reduce their APK size.

![Screenshot_20191113-110205](https://user-images.githubusercontent.com/17825767/68744191-ebd0bb00-05eb-11ea-88b0-8aea74df08f3.png)

It's 267 MB for me.

![Screenshot_20191113-110256](https://user-images.githubusercontent.com/17825767/68744218-03a83f00-05ec-11ea-9ce6-2090c112c833.png)

And latest nightly is 180 MB.

Xperia XZ1, Android 9

**Comment by oplik0** [comment]
Galaxy S7, Android 8. Chrome also takes much more than 27MB:
 ![Chrome size](https://i.imgur.com/mKZbhgZ.jpg)
Fresh install of Chrome Beta is a little bit smaller, but still >150MB
![Chrome Beta size](https://i.imgur.com/9LZ6qg3.jpg)

**Comment by kbrosnan** [comment]
Thank you all for screenshots from your devices. There is no need to add more of them. The Chrome size on your device will depend on the Android version. For [Android 10 they broke Chrome and the Webview](https://chromium.googlesource.com/chromium/src/+/HEAD/android_webview/docs/channels.md#Trichrome-Android-Q) into separate parts. Users on Android 10 would need to sum the Webview and Chrome sizes to compare to Firefox.

**Comment by hakkikaancaliskan** [comment]
> Thank you all for screenshots from your devices. There is no need to add more of them. The Chrome size on your device will depend on the Android version. For [Android 10 they broke Chrome and the Webview](https://chromium.googlesource.com/chromium/src/+/HEAD/android_webview/docs/channels.md#Trichrome-Android-Q) into separate parts. Users on Android 10 would need to sum the Webview and Chrome sizes to compare to Firefox.

Got it. I updated my phone to 10 and size is 24+78=102MB.

**Comment by mcomella** [comment]
Perf triage: Eric will do a brief investigation into how much installed size affects retention rates.

**Comment by ecsmyth** [comment]
We can defer further investigation into installed app size for now. Prioritization as P3 is appropriate. I may file a separate ticket for user data and cache size as we have some signal there regarding churn.

**Comment by kbrosnan** [comment]
Temp files not being deleted is a good example of cache blowing up to an unexpected size. [1555115](https://bugzilla.mozilla.org/show_bug.cgi?id=1555115)

**Comment by mcomella** [comment]
The perf team is tracking high level work on JIRA:
- APK size: https://jira.mozilla.com/browse/FXP-465
- user data size: https://jira.mozilla.com/browse/FXP-1202

Please open a new issue if you're having a specific problem we can address.
