### ISSUE TITLE
[Bug] CWTS looks buggy when checkboxes are pressed quickly

### ISSUE THREAD

**Issue by ekager** [mozilla-mobile/fenix#6553]
## Steps to reproduce
1. Change selection of which checkbox options you want to sync 

### Expected behavior
Checkboxes are either greyed out if they shouldn't be changed or the checks work

### Actual behavior
Sometimes clicking checkbox will not change the value if another checkbox has just been checked
![ezgif com-video-to-gif(4)](https://user-images.githubusercontent.com/25442310/68628518-aa2dfc00-0495-11ea-9c9e-1d65f0e182ac.gif)

### Device information

* Android device: ?
* Fenix version: ?

**Comment by sv-ohorvath** [comment]
Now you can only pick one setting at a time. Verified as fixed on v3.2-beta1.
