### ISSUE TITLE
Ad click attribution counts

### ISSUE THREAD

**Issue by liuche** [mozilla-mobile/fenix#6558]
As part of search attribution parity with Desktop, we also need to collect
- Count of partner search pages w/ ads
- Count of ad clicks

### Acceptance Criteria
- [ ] Telemetry type ~~created that is similar to the [desktop browser.search Scalar](https://searchfox.org/mozilla-central/source/toolkit/components/telemetry/Scalars.yaml#4305), or a similar data format cleared by Frank Bertsch (Data Engineering)~~ This should be `labeled_counter`
- [ ] Request list of partner urls from Mike Connor @mconnormoz
- [ ] Data review (Desktop data review request [here](https://bugzilla.mozilla.org/show_bug.cgi?id=1495548#c8))
- [ ] Count of pages loaded that match partner search provider pages (that are assumed to have ads) `browser.search.with_ads`
- [ ] Count of ad clicks `browser.search.ad_clicks` (like a redirect)

#### Helpful context
- Desktop [ad detection implementation](https://searchfox.org/mozilla-central/source/browser/components/search/SearchTelemetry.jsm#477) (see SEARCH_ADD_CLICKS_SCALAR and SEARCH_WITH_ADS_SCALAR)
- Desktop [tests](https://searchfox.org/mozilla-central/source/browser/components/search/test/unit/test_urlTelemetry.js) for `browser.search.ad_clicks` code
- Blog post explaining [Desktop ad display/click + organic search](https://blog.mozilla.org/data/2018/08/20/effectively-measuring-search-in-firefox/)

**Comment by liuche** [comment]
I'm in the process of asking mconnor for these lists, if someone picks up this issue and the info isn't ready yet, please ping me!

**Comment by BranescuMihai** [comment]
@liuche, when the list of partner urls is available, please let me know :)

**Comment by Standard8** [comment]
>     * Desktop [tests](https://searchfox.org/mozilla-central/source/browser/components/search/test/unit/test_urlTelemetry.js) for `browser.search.ad_clicks` code

There is also https://searchfox.org/mozilla-central/source/browser/components/search/test/browser/browser_searchTelemetry.js

**Comment by liuche** [comment]
Hi @BranescuMihai, you should have access to the docs and links, I added you to an email thread and doc.

**Comment by BranescuMihai** [comment]
Hey @liuche, yep, I just noticed that, somehow it was lost between emails, thank you!

**Comment by vesta0** [comment]
Spoke to mconnor about this issue. This is not a MUST for the launch but should be a fast follower.

**Comment by dbolter** [comment]
Given the strategy shift in launch, @liuche do we have time to get this in?

**Comment by liuche** [comment]
Hi @BranescuMihai is this something you can pick up again?

**Comment by BranescuMihai** [comment]
Sure @liuche , I'll restart work on it!

**Comment by BranescuMihai** [comment]
Status update:

The code for the telemetry part is done form dev perspective, however, there are issues concerning the urls that we monitor:
- **google**: all ad links on mobile are on http protocol instead of https like on FF web (you can search for `aclk` on this Fennec source: https://docs.google.com/document/d/1DFasTKPLh4Hm4ObuGhCPvQULoPqB-h0Ndk6_-u92nOc/edit?usp=sharing)
- **baidu**: The search on mobile adds the `/from=844b/s`action instead of `/s` like on web, so we need to take that into account for the ads regex

Also, until [this issue](https://github.com/mozilla-mobile/fenix/issues/9816) is resolved, we won't be able to track the ad_clicks metric for already opened tabs.

@liuche @mconnormoz It looks like the providers are differentiating some actions between mobile and web. Those were the issues I found, but there may be others. Is there someone I could talk to to make sure my assumptions are correct?

**Comment by liuche** [comment]
Hi @BranescuMihai, thank you for pinging me on this! I'm glad to hear the dev part of this telemetry is done :)

I sent an email regarding the first part about desktop/mobile differences. For the second part, will the telemetry for ad clicks work once those telemetry bugs have been fixed? If so, I'm fine with this fix landing if @mconnormoz doesn't have objections, and then we can fix those (perhaps you could pick up some of them once you are done with search attribution?).

**Comment by mikedeboer** [comment]
@BranescuMihai 

>     * **google**: all ad links on mobile are on http protocol instead of https like on FF web (you can search for `aclk` on this Fennec source: https://docs.google.com/document/d/1DFasTKPLh4Hm4ObuGhCPvQULoPqB-h0Ndk6_-u92nOc/edit?usp=sharing)

Well, this blows my mind, but okay, let's modify the regexes to allow for non-secure http too. I guess.

>     * **baidu**: The search on mobile adds the `/from=844b/s`action instead of `/s` like on web, so we need to take that into account for the ads regex

Also here, please feel free to change the regex to accommodate for this difference. We'll backport any changes you need to make to desktop, so that we stay in sync _until_ both desktop and Fenix are getting their updates from remote settings.

**Comment by BranescuMihai** [comment]
@mikedeboer I think there might be an issue with `Bing`. First i thought it's only a mobile issue, but then I checked the console on FF web. It seems like there are NO urls of ads when I search for `phones`, while on Chrome there are plenty. 
Could this be a regional problem (they are not showing ads because they're not targeted for Eastern Europe - where I'm at), or is this a bug targeting the FF browser itself?

**Comment by BranescuMihai** [comment]
> Hi @BranescuMihai, thank you for pinging me on this! I'm glad to hear the dev part of this telemetry is done :)
> 
>  For the second part, will the telemetry for ad clicks work once those telemetry bugs have been fixed?

@liuche yes, right now it works for new tabs, but once that bug is fixed, it will work everywhere

**Comment by Diana-Rus** [comment]
Hi, verified this issue with the following scenarios:
A). Searches without ads - no tracking is done as there are no ads
- Google -> Ping - a6658f57-30a3-4ef6-89a6-60726137b865
- Bing -> Ping - 336e141d-f4ca-4145-acf7-c889547d8000
- Duckduckgo -> Ping - b2a8e7f0-7aa7-42e6-a7e0-0034bf177b14
B). Searches with ads & Ads clicked from searches
1. Google Engine - count of one search with ads. Ping- 9fc93a95-4e11-49b4-8282-9921192eb75a
2. Google Engine - count two searches with ads. Ping- 78202251-b51c-47e9-86db-d178dcfcb66e
3. Google Engine - count of clicked ads. Ping- fadba36e-7ea5-4e53-8310-53ce31093b8a
4. Bing Engine - count of one search with ads. Ping- 477f17cd-934d-43d5-9fa4-4087fab877c0
5. Bing Engine - count two searches with ads. Ping- b0b53ad8-b54a-4bce-b9ae-2d45d3a60035
6. Bing Engine - count of clicked ads. Ping-477f17cd-934d-43d5-9fa4-4087fab877c0
7. Duckduckgo Engine - count of one search with ads. Ping-a2ac5c05-8ac4-4149-b811-7d956e8d6e88
8. Duckduckgo Engine - count two searches with ads. Ping - af15d27a-90bd-4c12-992f-966490d6747d
9. Duckduckgo Engine - count of clicked ads. Ping - af15d27a-90bd-4c12-992f-966490d6747d
10. Combination of searches and ads made on different search engines through search shorcuts. Baseline Ping - a28db793-1180-40a5-910c-8c0a81484f12
[Glean dashboard] - https://debug-ping-preview.firebaseapp.com/pings/ad-clicks-dr1
6558-Ads Clicked - Google Search engine-Clicked&Deleted actions.txt
**Note:**
- labeled_counter
- browser.search.with_ads -> the number o searches
- browser.search.ad_clicks -> number of clicked ads
- Needs to be taken into consideration that browser.search.with_ads increments each time you are on a page with ads.
**Devices:**
- Google Pixel 3 XL (Android 9)
**Example of telemetry**:

**Comment by Diana-Rus** [comment]
Hi, verified this issue with the following scenarios on Nightly 4/28 and Beta 5.0.0-beta.1 -  4/29:

**A). Searches without ads - no tracking is done as there are no ads**
Google -> Ping - a6658f57-30a3-4ef6-89a6-60726137b865
Bing -> Ping - 336e141d-f4ca-4145-acf7-c889547d8000
Duckduckgo -> Ping - b2a8e7f0-7aa7-42e6-a7e0-0034bf177b14

**B). Searches with ads & Ads clicked from searches**
1. Google Engine - count of one search with ads. Ping- 9fc93a95-4e11-49b4-8282-9921192eb75a
2. Google Engine - count two searches with ads. Ping- 78202251-b51c-47e9-86db-d178dcfcb66e
3. Google Engine - count of clicked ads. Ping- fadba36e-7ea5-4e53-8310-53ce31093b8a
4. Bing Engine - count of one search with ads. Ping- 477f17cd-934d-43d5-9fa4-4087fab877c0
5. Bing Engine - count two searches with ads. Ping- b0b53ad8-b54a-4bce-b9ae-2d45d3a60035
6. Bing Engine - count of clicked ads. Ping-477f17cd-934d-43d5-9fa4-4087fab877c0
7. Duckduckgo Engine - count of one search with ads. Ping-a2ac5c05-8ac4-4149-b811-7d956e8d6e88
8. Duckduckgo Engine - count two searches with ads. Ping - af15d27a-90bd-4c12-992f-966490d6747d
9. Duckduckgo Engine - count of clicked ads. Ping - af15d27a-90bd-4c12-992f-966490d6747d
10. Combination of searches and ads made on different search engines through search shorcuts. Baseline Ping - a28db793-1180-40a5-910c-8c0a81484f12

**[Glean dashboard] - Nightly** - https://debug-ping-preview.firebaseapp.com/pings/ad-clicks-dr1
**[Glean dashboard] - Beta** - https://debug-ping-preview.firebaseapp.com/pings/ad-clickdr2

**Note:**
- labeled_counter
- browser.search.with_ads -> the number of searches
- browser.search.ad_clicks -> number of clicked ads
- Needs to be taken into consideration that browser.search.with_ads increments each time you are on a page with ads, including when you go back to the same page.

**Devices:**
Google Pixel 3 XL (Android 9)

**Beta Baselines:**
[6558-Beta - Google Baseline- Search with ads and clicked ads.txt](https://github.com/mozilla-mobile/fenix/files/4552922/6558-Beta.-.Google.Baseline-.Search.with.ads.and.clicked.ads.txt)
[6558-Beta - Bing Baseline - Search with ads and clicked ads.txt](https://github.com/mozilla-mobile/fenix/files/4552925/6558-Beta.-.Bing.Baseline.-.Search.with.ads.and.clicked.ads.txt)
[6558- Beta - Duckduckgo Baseline- Search with ads and clicked ads.txt](https://github.com/mozilla-mobile/fenix/files/4552926/6558-.Beta.-.Duckduckgo.Baseline-.Search.with.ads.and.clicked.ads.txt)
[6558-Beta - Google,Bing,Duckduckgo Baseline- Search with ads and clicked ads.txt](https://github.com/mozilla-mobile/fenix/files/4552927/6558-Beta.-.Google.Bing.Duckduckgo.Baseline-.Search.with.ads.and.clicked.ads.txt)

**Example of telemetry:**
"labeled_counter": {
"browser.search.ad_clicks": {
"bing": 1,
"duckduckgo": 1,
"google": 1
},
"browser.search.in_content": {
"bing.in-content.sap.mozb": 1,
"duckduckgo.in-content.sap.fpas": 1,
"google.in-content.sap-follow-on.firefox-b-m": 1,
"google.in-content.sap.firefox-b-m": 1
},
"browser.search.with_ads": {
"bing": 1,
"duckduckgo": 1,
"google": 1
},
"metrics.search_count": {
"bing.action": 1,
"google-b-m.action": 1
}

**Comment by liuche** [comment]
Hi @BranescuMihai ! I was talking to the Glean team, and they were looking at the pings today. They wanted to know if these ad click attribution telemetry needs to be in the Baseline ping (since it is also in the Metrics ping).

I don't remember what the reasons were here for choosing both pings - was there a conversation you had with mconnor or Mike de Boer that we needed to have it in both? Did someone from Data Science need it in both?

If it isn't necessary in both, could you remove it from the baseline ping, and keep it in the metrics ping? (Feel free to ping me for clarification on slack too)

**Comment by liuche** [comment]
Talked to @BranescuMihai and it sounds like we had some miscommunication very early on about what the [baseline vs metrics ping](https://github.com/mozilla-mobile/fenix/issues/1158#issuecomment-498199848) means.

We decided that it makes sense to take these search events out of the `baseline` ping, and Mihai will open a PR to remove it.

**Comment by liuche** [comment]
@psymoon filed this issue to track this: https://github.com/mozilla-mobile/fenix/issues/10599 please attach your PR to that issue!
