### ISSUE TITLE
[Bug] border of active tab has a different size than the tab

### ISSUE THREAD

**Issue by cadeyrn** [mozilla-mobile/fenix#6560]
### Steps to reproduce

1. look at your open tabs on the start screen

### Expected behavior

The border of the active tab has the same size as the tab itself.

### Actual behavior

The tab size is larger than the border.

![Screenshot_20191112-081712](https://user-images.githubusercontent.com/1100614/68650551-8f0acd00-0525-11ea-848c-d7d24b18bc1d.jpg)

### Device information

* Android device: OnePlus 7T Pro McLaren Edition with Android 10
* Fenix version: master branch revision f0468f8099244095351753e897bc77e772a6609d

**Comment by cadeyrn** [comment]
Additional information: the bug does not always appear. Sometimes it looks okay but after switching between an open tab and the start screen a few times the bug suddenly appears.

**Comment by darkwing** [comment]
I just saw this momentarily on my Pixel 4.  It was there for a moment then disappeared.  It's almost as though an animation stuttered.  Like I said, it went away fairly quickly though.

**Comment by boek** [comment]
Closing this as it gets removed with #7115

**Comment by cadeyrn** [comment]
@boek should this been re-opened since new tab tray will not happen in the short term? It still happens.
