### ISSUE TITLE
Font Poor Contrast, Require Accessibility Function: Bold

### ISSUE THREAD

**Issue by designhubby** [mozilla-mobile/fenix#6567]
## Steps to reproduce
Firefox Preview: Font Poor Contrast, Require Accessibility Function: Bold
On hi-res E ink devices like Boox Max 2, the font display is very Faint. The native browser has been customized to bold all text. On Firefox Preview I tried using the Accessibility setting to increase font size but it is still hard to read because the text is thin. Please improve readability by implementing an accessibility feature to bold all text.

### Expected behavior
Text should have been Bolded and become readable

### Actual behavior
Text is hard to read

### Device information
Onyx Boox Max 2
* Android device: 6.0
* Fenix version: 2.3

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-14349)

**Comment by fluffyemily** [comment]
Issue requires Bugzilla issue.

**Comment by boek** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1639081

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813233

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
