### ISSUE TITLE
[Bug] Can't pause or cancel a download if you close the app

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#6570]
## Steps to reproduce
1. Start to download a large file.
2. Kill the app from the task manager.
3. Drag down the notification panel and try to cancel or pause the ongoing download.
### Expected behavior
The download is stopped.
### Actual behavior
Once you kill the app, the download doesn't make any progress but neither gets paused/canceled.
### Device information

* Android device: Pixel (Android 10), Sony Xperia Z5 (Android 7.1.1)
* Fenix version: Nightly 11/12

**Comment by sblatz** [comment]
@sv-ohorvath 

> Kill the app from the task manager.
Is this when you force close the app from the app switcher or in settings pressing "force stop"?

**Comment by sv-ohorvath** [comment]
@sblatz The first one: swipe to close it from the app switcher.

**Comment by sblatz** [comment]
I spoke with @csadilek this sounds like this would be a bigger chunk of work and is likely related to something I'm doing wrong with keeping the service alive.

**Comment by sblatz** [comment]
This ticket will just cover dismissing the notification when the app is force quit. 

https://github.com/mozilla-mobile/fenix/issues/6790 can cover matching Fennec's behavior here.

**Comment by pocmo** [comment]
This was fixed in AC and should be in Fenix Nightly.

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** when the app on the latest **Nightly Build #13440604 from 12/10** using the following devices:
• Google Pixel 3a XL (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

►Dismissing the notification using Android App Settings to Force Stop Fenix  &  Closing the app using  the recent applications menu 

![20191210_091327](https://user-images.githubusercontent.com/51314259/70504616-c1ace300-1b2e-11ea-908b-477314f0cd2c.gif)
