### ISSUE TITLE
[Bug] No acknowledgement of link opened in a new tab

### ISSUE THREAD

**Issue by concastinator** [mozilla-mobile/fenix#6573]
## Steps to reproduce

Long press on any link and choose "Open link in new tab".

### Expected behavior

The link should open in a new tab and, as in Fenix 2.3.0, the user should be presented with the text "New tab opened    SWITCH".

### Actual behavior

The link indeed opens in a new tab but, unlike in Fenix 2.3.0, the user is NOT presented with the text "New tab opened    SWITCH", so that inexperienced users may wonder where that newly opened tab has gone.

### Device information

* Android device: Nokia 5 (model TA-1024) with up-to-date Android 9
* Fenix version: Nightly 191112 18:00 (Build 13161807)

**Comment by ekager** [comment]
I think the snackbar still shows, but is maybe showing behind the toolbar now?

**Comment by concastinator** [comment]
> I think the snackbar still shows, but is maybe showing behind the toolbar now?

Indeed, this is what happens, and you can check it as follows:
1) open any page containing links;
2) tap on "Find in page" in the settings menu: this will replace the bottom address bar with the search field;
3) open any link on the page in a new tab: the "New tab opened    SWITCH" message will be visible at the bottom, as it should.

So yes, the message is displayed, but hidden beneath the address bar.

**Comment by concastinator** [comment]
It seems fixed in Fenix 191123 06:01 (build 13270608), working as expected in both portrait and landscape mode. Thank you.

**Comment by abodea** [comment]
Verified as fixed on the latest Nightly build from **11/29** with **Google Pixel 3a XL(Android 10).**
