### ISSUE TITLE
[Bug] With "Save image" filenames are not shown in notifications

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#6576]
## Steps to reproduce
1. Go to wikipedia, cnn or other images, long click and Save image.
2. Check the filename in the download notification.
### Expected behavior
The file name is displayed.
### Actual behavior
(null) is displayed instead of the filename.
### Device information

* Android device: Pixel (Android 10), Sony Xperia Z5 (Android 7.1.1)
* Fenix version: Nightly 11/13

**Comment by sblatz** [comment]
This might be fixed by: https://github.com/mozilla-mobile/android-components/issues/5046

**Comment by AndiAJ** [comment]
Hi @sblatz , this is **still reproducible** on the latest **Nightly Build #13290608 from 11/25** using the following devices:
• Google Pixel 3 (Android Q)
• Google Pixel 3a XL (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• Huawei P9 Lite (Android 7)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

► Video
![20191125_115945](https://user-images.githubusercontent.com/51314259/69530916-a1e8bd00-0f7b-11ea-95c7-473342603b25.gif)

**Comment by sblatz** [comment]
Closing this in favor of #6519 as they are two symptoms of the same underlying issue.
