### ISSUE TITLE
Add a "your rights" page

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#658]
As a user, I want to know more about the open source license used for Fenix and my rights as a user. 

### Acceptance Criteria:
-I can see a link in the settings menu to "your rights" (UX)
-I can click on the link 

Example from Firefox Focus:

![Screenshot_20190518-132217](https://user-images.githubusercontent.com/42752644/57973024-44423b00-7970-11e9-91d1-40b182acd6d2.png)
to read about my rights as a user (Sumo article)

**Comment by thomcc** [comment]
See also https://bugzilla.mozilla.org/show_bug.cgi?id=1548663 (I'm guessing this means that Fenix currently has no page listing licenses?)

**Comment by vesta0** [comment]
@mheubusch what is the status on this ticket?

**Comment by vesta0** [comment]
@jonichan just making sure this ask is on your radar :)

**Comment by jonichan** [comment]
Here's the in-product link: https://support.mozilla.org/1/mobile/%VERSION%/%OS%/%LOCALE%/your-rights

**Comment by topotropic** [comment]
Can we have a separated page for "Licenses" and "Your rights" and link to them from the "About Firefox Preview" page?

**Comment by vesta0** [comment]
@topotropic are you suggesting creating 2 separate pages for Licenses and Your rights? If so, what are the user benefits? cc @mheubusch

**Comment by topotropic** [comment]
Yes, that's correct, 2 separate pages. "Licenses" and "Your rights" are two very separate things. 
And, this might come in handy in case we have a cross-plattform (desktop, iOS) shared resource we can use for "Your rights".

**Comment by mheubusch** [comment]
I believe the links to licenses are embedded in the your rights page.

**Comment by vesta0** [comment]
Let's just have one page for now and re-evaluate post-mvp if they can be separated. 

@bifleming I believe you estimated this with the team, can we add the settings option before code freeze and link to where the final content will reside?  https://support.mozilla.org/1/mobile/%VERSION%/%OS%/%LOCALE%/your-rights

**Comment by bifleming** [comment]
@vesta0 sorry, not sure what you're asking --if it's a question of getting it done before code freeze, yes the content can follow, but we should put the link in to a placeholder page. we don't want to put it in QA until it links to the correct content though.

**Comment by vesta0** [comment]
@bifleming that is exactly what I was asking: add the option to settings with a link to the placeholder page (link provided above).

**Comment by mheubusch** [comment]
Please label this Your rights and add to the bottom of the settings list beneath Privacy notice

<img width="232" alt="Screen Shot 2019-05-24 at 11 21 23 AM" src="https://user-images.githubusercontent.com/20115914/58342533-44ca4e00-7e16-11e9-835a-48bbad9216bd.png">

**Comment by bifleming** [comment]
Unblocking to get the link and label in. Please block again when that is done and we are waiting for the content.

**Comment by sblatz** [comment]
@mheubusch Should the string say "Privacy notice" or "privacy policy"? It currently says "policy" and I want to confirm we're intentionally changing it.

**Comment by mheubusch** [comment]
It should say notice - thanks for *noticing* that.  The destination is to our Firefox privacy notice

**Comment by topotropic** [comment]
Please remove the "Your rights" page from Settings home and link to it from the "About..." page.

**Comment by jonichan** [comment]
The SUMO article has been published (accessed via link only). The in-product link I gave you (https://support.mozilla.org/1/mobile/%VERSION%/%OS%/%LOCALE%/your-rights) will automatically redirect to the SUMO article: https://support.mozilla.org/kb/firefox-preview-your-rights

Let me know if we need to do anything else with this page.

**Comment by sv-ohorvath** [comment]
@topotropic @mheubusch The page is a desktop page and has a "tap here for the mobile site" banner.
Is this an acceptable form?:
![Screenshot_20190605-092106](https://user-images.githubusercontent.com/4037709/58959773-70521e80-87ae-11e9-89ba-90216e608190.png)
![Screenshot_20190605-092120](https://user-images.githubusercontent.com/4037709/58959775-70eab500-87ae-11e9-8c13-53974eb4f763.png)

**Comment by softvision-miralobontiu** [comment]
This is how it is displayed on the latest build 1.0.1923 (#11570615) on Xiaomi Mi 8 Lite (Android 8.1), and Nexus 5 (Android 6.0.1):
![Screenshot_2019-06-06-12-41-24-926_org mozilla fenix](https://user-images.githubusercontent.com/40694158/59024203-0ee78980-885a-11e9-81ff-ab0a6896b794.png)
