### ISSUE TITLE
[Bug] Audio/Video media restarts from background after silencing alarm

### ISSUE THREAD

**Issue by colintheshots** [mozilla-mobile/fenix#6586]
## Steps to reproduce
1. Start an audio/video source website that can play in the background.
2. Pause that stream from pause button on the webpage.
3. Press Home.
4. Set an alarm for one minute later.
5. Snooze that alarm.

### Expected behavior
Paused audio remains paused.

### Actual behavior
The paused audio continues in the background.

### Device information

* Android device: Pixel 3 XL
* Fenix version: Fenix Nightly 191112 18:00 (Build #13161807)
📦: 21.0.0, 09da19708
🦎: 72.0a1-20191105095755

**Comment by ekager** [comment]
closing for #6880
