### ISSUE TITLE
[Bug] Pinch-and-zoom gesture not enforced despite configured so

### ISSUE THREAD

**Issue by concastinator** [mozilla-mobile/fenix#6596]
## Steps to reproduce

1) In "Settings > Accessibility" activate the option "Zoom on all sites".
2) Open lwn.net, arstechnica.com, hongkongfp.com and osnews.com.
3) Try the pinch-and-zoom gesture on each of the above.

### Expected behavior

The pinch-and-zoom gesture should (forcefully) work on all the 4 sites.

### Actual behavior

The pinch-and-zoom gesture works only on LWN and ArsTechnica.

### Device information

* Android device: Nokia 5 (model TA-1024) with up-to-date Android 9 (Android One program)
* Fenix version: 191113 06:00 (Build 13170607)

**Comment by concastinator** [comment]
The problem seems fixed now, at least on the two sites mentioned above on which pinch-and-zoom was not working. Could anyone please confirm that the issue has been resolved and the bug report can be closed?

**Comment by ekager** [comment]
cc @boek did something land to fix this in Fenix/AC/GV?

**Comment by concastinator** [comment]
@ekager, have you found out the answer? If not, how many days is it polite to wait for before pinging a user again?

**Comment by boek** [comment]
@concastinator Thank you for your patience! Bumping this to the geckoview board 👍

**Comment by kbrosnan** [comment]
Works for me using a Pixel 3 / Android 10
