### ISSUE TITLE
[Bug] Reader view mode not always available

### ISSUE THREAD

**Issue by concastinator** [mozilla-mobile/fenix#6597]
## Steps to reproduce

1) Open arstechnica.com or hongkongfp.com.
2) Try to choose "Reader view" from the settings menu.

### Expected behavior

Reader view mode should be available.

### Actual behavior

Reader view mode is not available.

Notice, though, that this seems to happen only on the "top level" (or main page) of these sites. As soon as one chooses any article linked from the main page, the reader view mode is available on the pages containing these articles.

### Device information

* Android device: Nokia 5 (model TA-1024) with up-to-date Android 9 (Android One program)
* Fenix version: 191113 06:00 (Build 13170607)

**Comment by cadeyrn** [comment]
It depends on the markup of the website if reader mode is available or not. There is also no reader mode on the homepage of arstechnica.com in Fennec, so it's not a Fenix bug.

**Comment by sblatz** [comment]
Closing this as it doesn't appear to be a bug on our end :)
