### ISSUE TITLE
Launching app from external link crashes if Fenix isn't open

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#660]
## Steps to Reproduce
0. Force quit Fenix from memory
1. Open a link from an external app (I use Samsung Messages for this example)

**Comment by sblatz** [comment]
Stack-trace

<img width="1327" alt="image" src="https://user-images.githubusercontent.com/4400286/53352511-c07c3380-38d7-11e9-9940-0f2c12797a90.png">

**Comment by sblatz** [comment]
Perhaps related to https://github.com/mozilla-mobile/fenix/issues/575? Though this was closed last week.

**Comment by colintheshots** [comment]
I can't reproduce on the latest build with those steps to reproduce. Clearly, the steps are missing something important.

I don't have Samsung Messages, but based on the other issue, it does not appear to use custom tabs. I tried Signal and no such crash occurred.

**Comment by sblatz** [comment]
My bad, I was accidentally on a branch that hadn't pulled these changes. I'm not able to repro on master--closing!
