### ISSUE TITLE
Browse while watching a video in PIP mode

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/fenix#6600]
### Why/User Benefit/User Problem
This is an extension of https://github.com/mozilla-mobile/fenix/issues/2818#issuecomment-553555577 that adds the ability to browse other sites while watching a video.

### What/Requirements
 - Add support for watching video content and browsing other tabs.

### Acceptance Criteria (how do I know when I’m done?)
 - Be able to watch a video in PIP mode and then switch and browse a different tab.
 - (Optional) Be able to browse the _current tab_ playing video content on the same page in PIP-mode.

GV API needed: https://bugzilla.mozilla.org/show_bug.cgi?id=1625012

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-14374)

**Comment by plwt** [comment]
User feedback - https://support.mozilla.org/en-US/questions/1379256

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813289

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
