### ISSUE TITLE
[Bug] Select all is continually appearing after tapping select all

### ISSUE THREAD

**Issue by darkwing** [mozilla-mobile/fenix#6605]
## Steps to reproduce

1.  Select a portion of text on a page
2.  Tap "select all", wait for all content to be selected
3.  Tap "select all"
4.  Tap "select all"
5.  Tap "select all"
....

### Expected behavior

If all text is selected already, don't show "Select All", or show a disabled state for that item text

### Actual behavior

The "Select All" item can be tapped all day with seemingly no feedback to the user.

![pull-over](https://user-images.githubusercontent.com/46655/68890613-dbe8d200-06e4-11ea-89d0-aca63462720a.jpeg)

### Device information

Discovered using the Android emulator / Pixel XL

**Comment by boek** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1610957
