### ISSUE TITLE
Suggestion: Provide "open tab" within the "No open tabs" pane

### ISSUE THREAD

**Issue by darkwing** [mozilla-mobile/fenix#6607]
### Why/User Benefit/User Problem
We currently show a "No open tabs" block when the user hasn't opened any tabs, but there's nothing actionable with that message.  I think it would be nice for usability to show an "open a tab" icon, button, or text in that space so the user can act while their attention is focused there.

### What/Requirements
_Update from UX (@topotropic) Feb 18, 2020:_

- When a user doesn't have any open tabs we show a button with "New tab" below the empty state message. 
- Once a user tabs on the button, we launch the search view. 
- See attached screenshot for specs

<img width="539" alt="grafik" src="https://user-images.githubusercontent.com/353960/74726681-2c218400-5240-11ea-88ad-87ece59cfe71.png">

**Comment by brampitoyo** [comment]
@darkwing do you have a screenshot of what this pane looks like, and where we can find it?

@topotropic do you think we need to provide an “open a tab” action if the pane says “No open tabs”?

**Comment by brampitoyo** [comment]
@darkwing Sorry, I now realise that this pane exists in our homescreen. I wonder @topotropic whether this problem will be solved when we have the new tab tray?

**Comment by mcarare** [comment]
We already have an "open tab" button that is next to the menu button in the home screen.
And, as I remember, there was a "+" button in the open tabs section, but it was intentionally moved to the bottom bar according to https://github.com/mozilla-mobile/fenix/issues/561

**Comment by topotropic** [comment]
@mcarare I have a design proposal for this, will update the issue once it's ready.

**Comment by KazaHesto** [comment]
The text colour becomes white when the theme is set to dark yet the button colour doesn't change, is this intentional?
![Screenshot_20200302-080126](https://user-images.githubusercontent.com/19279387/75633881-ac8ab080-5c54-11ea-846e-336d189df79b.png)

**Comment by brampitoyo** [comment]
@KazaHesto This is unintentional. The button style should be similar to other buttons in dark theme. Not the bright purple ones, but the ones in slightly lighter grey.

**Comment by sv-sdeiac** [comment]
Verified as fixed using the latest version of Firefox Preview Nightly 3/2 #20620607.

Devices: 
- Motorola Moto G6 (Android 8);
- Samsung Galaxy Note 8 (Android 9);
- Google Pixel 3 (Android Q).

**Comment by ekager** [comment]
I don't think this is fixed yet on my device 🤔

**Comment by sv-sdeiac** [comment]
Verified as fixed on the latest version of Firefox Preview Nightly 3/4 #20640606. 

Devices: Samsung Galaxy Tab S3 (Android 8). Due to that, I'll close this ticket, thanks.
