### ISSUE TITLE
Opening link from external app causes weird switching to private mode

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#661]
When I open a link from Samsung messages, it opens the normal Fenix app (not as a custom tab) inside Messages. This leads to some weird behavior like as seen below. Is this due to our custom tab implementation not being completed? 

![no transition](https://user-images.githubusercontent.com/4400286/53353337-595f7e80-38d9-11e9-985e-2cfeaa4c2ce7.gif)

**Comment by colintheshots** [comment]
Not every app uses custom tabs. It's actually quite a limited set of apps that do.

How are you getting it to switch to private mode? It would be easier to see if you added steps to reproduce or enabled Show Taps.

**Comment by sblatz** [comment]
Here is an updated gif:

![switch bug](https://user-images.githubusercontent.com/4400286/53354344-68dfc700-38db-11e9-89a6-b23d3c50380f.gif)

**Comment by colintheshots** [comment]
I see, the issue seems to be that pressing the private mode toggle is reverting back to the first fragment that had been open when it recreates the HomeActivity. It's not recreating itself with the current HomeFragment visible.

**Comment by sblatz** [comment]
Ah, in HomeActivity we have `        if (intent?.extras?.getBoolean(OPEN_TO_BROWSER) == true) {` navigating to browser if the flag is set. We just need to unset this when we recreate the theme :)

**Comment by sv-ohorvath** [comment]
Verified as fixed on the latest build (3/6)
