### ISSUE TITLE
Update Fenix Branding to match Firefox before launch

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/fenix#6610]
This ticket is a reminder to update all instances of the official app name in Fenix (and remove PREVIEW) before replacing Fennec.

### Dependencies
- [x] UX assets linked, by 1/31

### Acceptance Criteria
- [x] Firefox beta will have the Firefox beta branding and icon at the time of launch
- [ ] Firefox release will have the final Firefox branding and icon at the time of launch
- [ ] QA will need to verify the strings and branding throughout the app
- [ ] Version: We will match Firefox versioning: release will be Firefox for Android 75

**Comment by liuche** [comment]
cc @lwa-moz about question on whether Marketing would be okay releasing the branding with Beta test upgrade.

**Comment by lwa-moz** [comment]
@liuche no concern there - we will essentially be maintaining a consistent branding with "Firefox for Android Beta".

**Comment by liuche** [comment]
@lime124 I've added a date here, that we need the final assets by 1/31 so that this can land by Beta migration (because that will be our last sprint).

**Comment by shorlander** [comment]
Updated branding assets for Release, Beta, and Nightly. I included a launcher_background but not sure if we need it. The background-color is #20123a.

[Branding-Firefox.zip](https://github.com/mozilla-mobile/fenix/files/4093046/Branding-Firefox.zip)
[Branding-Firefox-Beta.zip](https://github.com/mozilla-mobile/fenix/files/4093048/Branding-Firefox-Beta.zip)
[Branding-Firefox-Nightly.zip](https://github.com/mozilla-mobile/fenix/files/4093049/Branding-Firefox-Nightly.zip)

**Comment by liuche** [comment]
@vesta0 since we want to update the branding for Fenix, do we need to wait to add the Firefox Release branding changes, until our final sprint? Or should we just update all the branding now, and ship Firefox Preview with the new Firefox branding?

**Comment by vesta0** [comment]
We should wait until our final sprint, thanks for checking!

**Comment by pocmo** [comment]
> Or should we just update all the branding now, and ship Firefox Preview with the new Firefox branding?

I wonder... shouldn't we only ship the `fennec` build types with the new branding? Just so that we do not end up with multiple apps having that branding..

**Comment by sblatz** [comment]
Branding-Firefox-Beta.zip is missing the SVG for beta icon. @shorlander can you please provide this when you get a chance? :)

**Comment by liuche** [comment]
@pocmo I vaguely remember seeing some other AC bugs float by about updating branding - are they the same as this bug, or are they doing different things? Could you link to them as well?

**Comment by pocmo** [comment]
* fennecBeta: https://github.com/mozilla-mobile/fenix/issues/8277
* fennecProduction: https://github.com/mozilla-mobile/fenix/issues/8278

**Comment by kglazko** [comment]
So what we have left remaining is that we need 2 separate PRs for:
- One to update org.mozilla.fenix (fenixProduction) to have the New Nightly branding (Needs to be timed - Stefan et al. are meeting about this today) 

- One to update org.mozilla.firefox (fennecProduction) -> New Production branding (Can land any time) As mentioned above there's already an issue for this https://github.com/mozilla-mobile/fenix/issues/8278
 
@sblatz @liuche

**Comment by ebalazs-sv** [comment]
Hello! On Fennec Nightly Migration Build 9 from 02/14, we did not have the branding from https://github.com/mozilla-mobile/fenix/issues/6610#issuecomment-576825543 on the onboarding screen, the homescreen UI and on the About Firefox Nightly page.
On Beta Migration build from 02/19 the mentioned branding is available.

**Comment by pocmo** [comment]
> Updated branding assets for Release, Beta, and Nightly. I included a launcher_background but not sure if we need it. The background-color is #20123a.
> 
> [Branding-Firefox.zip](https://github.com/mozilla-mobile/fenix/files/4093046/Branding-Firefox.zip)
> [Branding-Firefox-Beta.zip](https://github.com/mozilla-mobile/fenix/files/4093048/Branding-Firefox-Beta.zip)
> [Branding-Firefox-Nightly.zip](https://github.com/mozilla-mobile/fenix/files/4093049/Branding-Firefox-Nightly.zip)

@shorlander Is it expected that the wordmark is the same for release and beta?

**Comment by shorlander** [comment]
> @shorlander Is it expected that the wordmark is the same for release and beta?

@pocmo Yes, the wordmark should be the same.

**Comment by pocmo** [comment]
Great, thank you!

**Comment by liuche** [comment]
This looks like it's already done for Fennec Beta, and there's no point in having this bug so long-lived. We can file again for release.
