### ISSUE TITLE
Fenix FAQ page

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/fenix#6611]
The purpose of this ticket is to track the following work:

- [x] Creating an FAQ page for the migration
- [x] Linking to the page from the app, on the About page

**Comment by jonichan** [comment]
Hi Vesta, is this for a general Fenix FAQ or is it for a specific feature? Here's a link you can use in the UI. When will we need the content (en-us and localized)?

https://support.mozilla.org/1/mobile/%VERSION%/%OS%/%LOCALE%/fenix-faq

**Comment by jonichan** [comment]
Hi Vesta, is this for a general Fenix FAQ or is it for a specific feature? Here's a link you can use in the UI. When will we need the content (en-us and localized)?

https://support.mozilla.org/1/mobile/%VERSION%/%OS%/%LOCALE%/preview-faq

**Comment by AmyYLee** [comment]
> Hi Vesta, is this for a general Fenix FAQ or is it for a specific feature? Here's a link you can use in the UI. When will we need the content (en-us and localized)?
> 
> https://support.mozilla.org/1/mobile/%VERSION%/%OS%/%LOCALE%/preview-faq

This is for a general Fenix FAQ. I'm not sure about the timing for when we need the content (en-us and localized). Vesta is out for the next few weeks. @lime124 @liuche?

**Comment by liuche** [comment]
Since we wouldn't be uplifting this into 3.0, the earliest that we'd need it localized by would be Dec 9, which is when our 3.1 release goes out.

**Comment by AmyYLee** [comment]
> Since we wouldn't be uplifting this into 3.0, the earliest that we'd need it localized by would be Dec 9, which is when our 3.1 release goes out.

@jonichan ^^

**Comment by liuche** [comment]
We'll wait for @vesta0 to come back and fill out some more details on what this would look like.

And since we're cutting 3.1 today, this will have at least 3 more weeks for localization, and wouldn't go out before Jan 2020 at the earliest.

**Comment by vesta0** [comment]
The content and structure of the FAQ page was discussed with Sumo, Marketing, UX, and ENG. @jonichan has now drafted the FAQ page accordingly.

For the Nightly and Beta migration, I recommend linking “What’s new” to this FAQ page since (1) that's what will be NEW for migrated users, and (2) it’s more prominent and discoverable VS an FAQ that would live on the About page

For the main launch, we may want to:

1 - Link to the FAQ page directly from the app
2 - Include a link to the FAQ page on the "What’s New" sumo page
3 - Include a link to the FAQ page on the “What’s New” onboarding card

@lime124 @apbitner @mheubusch

**Comment by jonichan** [comment]
Here's the direct link to the FAQ page: https://support.mozilla.org/kb/firefox-preview-upgrade-faqs. Feel free to use this URL format when linking from other web pages.

Use https://support.mozilla.org/1/mobile/%VERSION%/%OS%/%LOCALE%/preview-faq when linking from the UI.

**Comment by mheubusch** [comment]
Thanks @vesta0! I'm confused about the difference between item 1 and item 3:

> 1 - Link to the FAQ page directly from the app
> 2 - Include a link to the FAQ page on the "What’s New" sumo page
> 3 - Include a link to the FAQ page on the “What’s New” onboarding card

For 3 do you mean the What's New card on desktop?

Also, re the FAQ - I reviewed the copy and it seems to suggest the pave over will be called Firefox Preview.  We should be positioning this as "how do I get the completely redesigned Firefox?" vs "how do I replace Firefox for Android with Firefox Preview?", yes?

**Comment by cadeyrn** [comment]
There is a mistake in the SUMO article:

> Ublock add-on (other add-ons will be disabled) 

"Ublock" should be "uBlock Origin" because uBlock and uBlock Origin are different add-ons and according to #5630 uBlock Origin will be supported.

**Comment by vesta0** [comment]
@mheubusch 

item 1 refers to essentially having an FAQ menu item in the app that all users can see and access (I was being careful to not provide a solution earlier) 

item 2 refers to including a link on the "What's new" onboarding card that only new users will see the first time.

**Comment by ValentinTimisica** [comment]
Talked to @pocmo and confirmed that the remaining work should have already been done in issue: #5481 and PRs: #7592, #7787.
@liuche is there anything left to work here?

**Comment by liuche** [comment]
Yes, I see it now on the About page! Thank you.
![Uploading Screenshot_20200122-105944.png…]()
