### ISSUE TITLE
[Bug] Download notifications missing some file names

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#6615]
## Steps to reproduce
On http://thinkbroadband.com/download, or file-examples.com
1, Download a file and pause it.
2. Cancel a download.
3. Complete a download.
### Expected behavior
Filenames appear in the system and in-app notifications
### Actual behavior
Downloads notifications are missing filenames.
![Screenshot_20191115-122253](https://user-images.githubusercontent.com/4037709/68937108-7c51fb80-07a4-11ea-8cca-ab27ac48e287.png)

### Device information

* Android device: Nexus 5 (Android 6.0.1), Mi 4i (Android 5.0.2), HTC Desire 820 (Android 6.0.1), Pixel (Android 10)
* Fenix version: Nightly 11/15

**Comment by sblatz** [comment]
I believe https://github.com/mozilla-mobile/android-components/pull/5047 fixes this :)

**Comment by sblatz** [comment]
My AC PR got merged, let's test this again 😄

**Comment by AndiAJ** [comment]
Hi @sblatz , this is **still reproducible** on the latest **Nightly Build #13290608 from 11/25** using the following devices:
• Google Pixel 3a XL (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

► Video
![20191125_121125](https://user-images.githubusercontent.com/51314259/69532323-36541f00-0f7e-11ea-9569-ef20a811cf11.gif)

**Comment by sblatz** [comment]
Will be fixed by https://github.com/mozilla-mobile/android-components/pull/5151

**Comment by AndiAJ** [comment]
Hi, this **is still reproducible** on the latest  **Nightly Build #13310607 from 11/27** using the following devices:
• Google Pixel 3a XL (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

► Video
![20191127_124152](https://user-images.githubusercontent.com/51314259/69717135-29693400-1114-11ea-9884-49a7fcb060cc.gif)

**Comment by sblatz** [comment]
Hi sorry about that, the AC version hadn’t been updated yet. It should be good to test in the next nightly!

**Comment by sv-ohorvath** [comment]
@sblatz The titles appear in the system notification, but not always on the in-app notification.
For e.g. downloading a file from thinkbroadband.com, the in-app completed download notification doesn't show the file name. The system notification does. 
*Same thing on "Save image" from Wikipedia.
When downloading a file from https://unsplash.com, it will show the title in both places.

**Comment by sblatz** [comment]
I believe this will **finally** be fixed by my PR here: https://github.com/mozilla-mobile/android-components/issues/5264

**Comment by sblatz** [comment]
Should work in the next nightly :)

**Comment by sblatz** [comment]
Looks to be fixed 🎉 
![Untitled 2019-12-10 08_55_14](https://user-images.githubusercontent.com/4400286/70550593-d7200e00-1b2a-11ea-9574-3c647b855ff8.gif)

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **Nightly Build #13450608 from 12/11** using the following devices:
• Google Pixel 3a (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• Motorola G4 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

► Video
![20191212_115441](https://user-images.githubusercontent.com/51314259/70612770-399f0a00-1c10-11ea-88a1-696bfdac94aa.gif)

**Comment by return42** [comment]
from https://github.com/mozilla-mobile/fenix/issues/21883#issuecomment-942641574 ..
> If we want autodiscovery to work it would require #8889 first and could be part of the initial work.

Are there any efforts or plans to support OpenSearch in the near future?

Sorry for insist on this topic, but for me OpenSearch support is a mandatory to give users back the freedom to select the search engine they trust .. forgive me, I am one of the [SearXNG (a free internet metasearch engine)](https://github.com/searxng/searxng) developer :-)

I don't want to offend anyone, I have a very high appreciation for this project, but in the manifesto I read things like ...

> Principle 2: The internet is a global public resource that must remain open and accessible.
>
> Principle 4: Individuals’ security and privacy on the internet are fundamental and must not be treated as optional.

https://www.mozilla.org/en-US/about/manifesto/

Even if think this topic is not paid the needed attention, I want to thanks all contributors for offering us a great mobile browser :+1:
