### ISSUE TITLE
[Bug] pwa does not open fullscreen

### ISSUE THREAD

**Issue by creesch** [mozilla-mobile/fenix#6616]
## Steps to reproduce
2. Go to https://demo.thelounge.chat/
2. Add site to homescreen
3. Open the website from the homescreen icon.
3. 
### Expected behavior

As #770 is closed with #4914 I except the application to open in fullscreen/standalone as it also does in Fennec.

### Actual behavior

It does not open in fullscreen, it opens as a regular browser.

### Device information

* Android device: Nokia 7 plus android 9
* Fenix version: Firefox Preview v2.3.0  ua_header: Mozilla/5.0 (Android 9; Mobile; rv:70.0) Gecko/70.0 Firefox/70.0

**Comment by creesch** [comment]
- [Screen recording of Fennec behavior](https://creesch.com/dump/vid/vid_5dce921586a8d.mp4), this is the expected behavior.
- [Screen recording of Fenix behavior](https://creesch.com/dump/vid/vid_5dce91da9473f.mp4).

**Comment by darkwing** [comment]
I cannot reproduce this on current master on Pixel 4 -- the item is added to the home screen and is in full screen.

![Screenshot_20191118-142426](https://user-images.githubusercontent.com/46655/69091121-42d0f880-0a0f-11ea-957e-fd5cced50253.png)

**Comment by NotWoods** [comment]
@creesch it looks like you're using the stable builds. Currently PWA support is Nightly-only, but I'm hoping to move it to stable soon.

**Comment by creesch** [comment]
@NotWoods would this have landed in the latest 3.0 release? As it isn't working properly there either.

**Comment by NotWoods** [comment]
PWA support is currently behind a flag and won't be moving to the upcoming stable release.
