### ISSUE TITLE
[Bug] There is a drop-down/expanded animation when accessing Settings for Passwords section

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/fenix#6619]
## Steps to reproduce
1. Launch Fenix.
2. Access the settings menu.
### Expected behavior
The `Passwords` menu section should already be there as the other sections.
### Actual behavior
There is a drop-down/expanded animation when accessing Settings for `Passwords`.
### Device information

* Android device: **`Google Pixel 3a XL(Android 10).`**
* Fenix version: **`Nightly 11/15`**

![ezgif-1-0d71991231c8](https://user-images.githubusercontent.com/42831109/68947575-85e85d00-07be-11ea-8153-26651a909f8a.gif)

**Comment by cadeyrn** [comment]
The passwords feature is behind a feature flag and I guess the same as in https://github.com/mozilla-mobile/fenix/issues/5575#issuecomment-540253487 applies here as well.

**Comment by abodea** [comment]
@cadeyrn thanks, I saw that, but being on the Settings where all the menus are displayed, I was thinking that his one should look the same, and this was recently added. 
I wanted to make sure we got everything covered.

**Comment by ekager** [comment]
Yes thanks for filing but I'm going to close this because it's just the feature flag as mentioned above :)
