### ISSUE TITLE
[Bug] The Saved Logins section and passwords can be recorded

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/fenix#6621]
## Steps to reproduce
1. Launch Fenix.
2. Login with valid credentials.
3. Access the `Passwords` section.
4. Enter the Saved Logins section to see all the synced passwords.
5. Start recording the screen(I used Az Recorder).
### Expected behavior
The video should be black hiding the Saved Logins section and all the passwords.
### Actual behavior
The Saved Logins and passwords can be recorded.
### Device information

* Android device: **`Google Pixel 3a XL(Android 10).`**
* Fenix version: **`Nightly 11/15`**
 
Note that in the GIF below, you can see that for a small-time black screen, that is because I had to add the pattern that I set as an unlocking method.

![ezgif-1-3ca4445e1300](https://user-images.githubusercontent.com/42831109/68948195-ffcd1600-07bf-11ea-8e1a-9159d04ed0be.gif)

**Comment by ekager** [comment]
Hey @abodea I added the secure window flag so these fragments will be obscured in the app switcher now. Let me know if it also fixes the recording issue :)

**Comment by abodea** [comment]
Verified as fixed using the latest Nightly build from 11/19 with Google Pixel 3a XL(Android 9).
Note that the `Saved Logins` section cannot be recorded anymore as everything is displayed black.
