### ISSUE TITLE
Fennec migration: Setup build type for Fennec Beta

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/fenix#6622]
Like #4873 created a `fennecProduction` build type, this issue is about creating a build type for Fennec Beta so that this new build type can replace a Fennec Beta installation.

# Build config

- [x] Create a `fennecBeta` build type
- [x] Reuse `sharedUserId` from Fennec Beta
- [x] Re-use versionCode mechanism of Fennec
- [x] Reuse Fennec package names

### RelEng

- [ ] Reuse Fennec Beta signing keys for `fennec` build.

### Tokens

- [ ] Adjust: TBD (Separate issue filed)
- [ ] Leanplum: BD (Separate issue filed)
- [ ] Sentry: For production we use `fenix-fennec` currently. Do we need `fenix-fennec-beta`?
- [ ] Firebase

**Comment by pocmo** [comment]
Token work continues in  #6899.

**Comment by ebalazs-sv** [comment]
Hello!
Are there any builds available for replacing Fennec Beta? The builds from https://github.com/mozilla-mobile/fenix/wiki/Fennec-Migration are replacing Fennec Release.

**Comment by ebalazs-sv** [comment]
Verified as fixed on Beta 12/10 GV 71; Nightly 191210 GV 72 with Samsung Galaxy S8 (Android 9) - ARM64; Motorola Nexus 6 (Android 7.1.1); Xiaomi Mi Pad 2 (Android 5.1) - x86.
Fennec Beta is replaced by Fenix Beta migration build.
I will move this to Done.
