### ISSUE TITLE
[Bug] Saved Logins cannot be deleted even after logging out

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/fenix#6623]
## Steps to reproduce
1. Launch Fenix.
2. Login with valid credentials.
3. Sync the passwords.
4. Logout.
### Expected behavior
There should be an option to delete the passwords/content from the `Saved Logins` section if there is no FF account used.
### Actual behavior
The passwords remain displayed on the `Saved Logins` section after logout and cannot be deleted.
### Device information

* Android device: **`Google Pixel 3a XL(Android 10).`**
* Fenix version: **`Nightly 11/15`**
![ezgif-1-ddc87f4bc800](https://user-images.githubusercontent.com/42831109/68951889-97823280-07c7-11ea-823f-b1d1d92264c5.gif)

**Comment by ekager** [comment]
We are going to have to add a way to delete logins. With the way sync works, logging out isn't enough to remove logins. Technically this was part of #5774 , but we should land this bit before release.
CC @vesta0 
@AmyYLee I believe there is already a mock for deleting a login? Could you link that piece here? I think just having the singular delete on the individual login info screen is okay for first iteration.

**Comment by ekager** [comment]
QA: There should now be a trash can button on the individual login info screen to delete a login individually, which is a start to solving this problem!

**Comment by sv-sdeiac** [comment]
Verified as fixed using the latest version of Firefox Preview Nightly 2/14 #20450606.

Devices:
Nokia 6 (Android 7.1.1);
Google Pixel (Android Q).
