### ISSUE TITLE
[Bug] The user is not warned when accessing Saved Logins if no biometrics or pin is set

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/fenix#6624]
## Steps to reproduce
1. Launch Fenix.
2. Login with valid credentials.
3. Perform a sync.
4. Access Passwords section.
5. Enter the `Saved Logins` section.
### Expected behavior
There should be a warning, informing the user that no biometrics or pin is set when accessing the section.
### Actual behavior
The user is not warned when no biometrics or pin is not set.
### Device information

* Android device: **`Google Pixel 3a XL(Android 10).`**
* Fenix version: **`Nightly 11/15`**

![ezgif-1-dbd950245e7d (1)](https://user-images.githubusercontent.com/42831109/68956190-40349000-07d0-11ea-8bdf-132dac17d744.gif)

**Comment by ekager** [comment]
Sorry I should have clarified this in the bug, but the desired UX behavior was that the warning is shown 1 time. Had you already seen the warning before?

**Comment by AndiAJ** [comment]
Hi, **authentication set up prompt warning** is displayed one time when trying to access the "Saved logins" without having any screen lock or biometrics set on latest Nightly Build #13220606 from 11/18 using the following devices:
• Google Pixel 3a XL (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

►Video
![20191118_164941](https://user-images.githubusercontent.com/51314259/69063057-8124e280-0a24-11ea-89fc-95bffb4317e8.gif)
