### ISSUE TITLE
[Bug] Press back in search mode,when the keyboard is hidden, navigates back or closes the app

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#6625]
## Steps to reproduce
1. From the homescreen tap the search bar and type something. Scroll the search suggestions.
2. Tap the device back button.
3. Open a webpage, navigate through links, tap the nav bar, type something, scroll the search suggestions.
4. Tap the device back button.
### Expected behavior
pressing back with the keyboard hidden exits the search screen.
### Actual behavior
If you are on the homescreen, the back press will close the app.
If you are in a tab, back press will close the tab (if there's no history in that tab), or it will navigate to the previous page.
### Device information

* Android device: any
* Fenix version: Nightly 11/15

**Comment by ekager** [comment]
cc @mcarare I think this is a possible regression from #6474? Do you mind taking a followup look?

**Comment by softvision-miralobontiu** [comment]
Verified as fixed with the latest Nightly from 11/26 with Samsung Galaxy Note 8 (Android 9), and Huawei MediaPad M2 (Android 5.1.1).
