### ISSUE TITLE
[Bug] Pattern, Pin or Password screen lock types are always displayed over Biometrics(Face recognition and Fingerprints) when unlocking Saved Logins section

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/fenix#6630]
## Steps to reproduce
1. Set Face Recognition or Fingerprint as security unlock(note that by default you have to pick Pattern, Pin or Password as a second option).
2. Launch Fenix.
3. Login with valid credentials.
4. Access Password and the Saved Logins section.
### Expected behavior
If Face Recognition or Fingerprint is set as a security unlock option, it should be displayed when unlocking Saved Logins.
### Actual behavior
The Pattern, Pin or Password is always displayed over Biometrics(Face Recognition or Fingerprints).
### Device information

* Android device: **`Samsung Galaxy S10+(Android 9).`**
* Fenix version: **`Nightly 11/15`**

![ezgif-1-20ce705a5308](https://user-images.githubusercontent.com/42831109/68959393-999fbd80-07d6-11ea-96ab-ac54d6ad6b5f.gif)

**Comment by ekager** [comment]
We can easily add this with a window flag and I think it was part of the original mocks.

**Comment by sflorean** [comment]
Verified as fixed on Nightly 12/15 with Pixel 3 (Android 11).
