### ISSUE TITLE
Reader mode icon in address bar

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/fenix#6639]
### Why/User Benefit/User Problem

As a user, I would like to know that I can access reader mode for a page without opening a menu, like I can on Firefox desktop or other Android browsers. 

### What/Requirements

Please close if a dupe. 

An reader mode or book icon within the address bar, which when clicked opens the reader view. Clicking this icon again should take me back to the normal page. 

This is all the more important with #4281 (which I support) since reader mode is now less discoverable (and this is by far the most useful and my oft-used qab option).

This exists in Edge and Samsung Internet - examples:

![signal-attachment-2019-11-15-143130](https://user-images.githubusercontent.com/152493/68970201-b925ee80-07b4-11ea-9311-2d211decd3b9.png)

![signal-attachment-2019-11-15-143124](https://user-images.githubusercontent.com/152493/68970213-bc20df00-07b4-11ea-9c8a-e186ea30782a.png)

### Acceptance Criteria (how do I know when I’m done?)

Users see a read icon whenever reader mode can be activated on a page.

**Comment by Cheap-Skate** [comment]
I agree with the idea of having the Reader mode icon more accessible. I dislike the latest Reader menu item with the switch, it seems very clumsy and makes the menu list even taller! Hopefully just a temporary fix

But...

The Fenix toolbar is already very cluttered with buttons:- Tracking Protection; padlock; URL; [open in app?]; [Reader mode?]; Tabs; 3 dot menu. Not much room for the URL and it's a bit intimidating

The two example browsers you give move Tabs & 3 dot menu buttons off the URL bar onto a new toolbar at bottom of screen, and have no more than 4 icons in the URL bar. And for Samsung Internet (maybe Edge too?) the padlock icon is very small and not clickable except in URL edit mode. so more like 3.5 icons in width. Fenix could have 5 or 6 icons full width icons. Too many IMHO.

UI rethink going on I guess? #6350

**Comment by jorgman1** [comment]
You could reduce the space between the shield and the padlock. Or give the users the choice over the buttons they want to include.
Personally, I seldomly change the tracking protection and I am constantly using the reader mode. In fact, I probably use it on 90% of the pages where it is available.

Is there a possibility to have it enabled by default?

**Comment by Sgt-Miller** [comment]
Agree, reader mode should be in address bar. And tracking protection could be placed where reader button exists now.

**Comment by RuthlessRuler** [comment]
I think we could combine the tracking and padlock icon into one entity with Tracking Protection as the main Icon. It would be in green if the website HTTPS and Red if HTTP,as I think the pad lock sign have already served its purpose and given the small width of the smartphones compared to desktops, its just taking up space which could have been used for Other Purpose like integrating the reader mode Button in the address bar itself.

**Comment by yoasif** [comment]
Just realized this also exists in Fennec and Reference Browser.

**Comment by ekager** [comment]
Closing for  #11045
