### ISSUE TITLE
Tab launched from external app does not respect private mode

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#664]
If I leave the app in private mode, then open the a link with Fenix the tab is opened with the private *theme* but is not actually in private mode.

**Comment by sblatz** [comment]
Looks like this is related to #626. Since we're doing the load logic inside of SearchFragment and not BrowserFragment, opening directly to BrowserFragment avoids the decision tree of making it a private or normal tab.

**Comment by sblatz** [comment]
So this actually needs some a-c work as well. It turns out that the IntentProcessor is creating a session for us, but not asking if it should be in private mode or not. We need to change IntentProcessor to handle this check.

**Comment by sblatz** [comment]
[A-c work done](fbce345e653903d4fbbd24dba8555bb97aa20eed) but blocked on upgrading due to 0.44 introducing breaking changes

**Comment by sv-ohorvath** [comment]
Verified as fixed on 3/5 build.
