### ISSUE TITLE
Handle advanced URL shortening cases

### ISSUE THREAD

**Issue by severinrudie** [mozilla-mobile/fenix#6642]
### Why/User Benefit/User Problem
There are several known URL formatting cases that were considered to be out of scope for #4844.  Some of these can present usability problems with specific inputs, others open up small security risks.  We should handle these problems as much as possible.

### What/Requirements
- Handle all known URL shortening edge cases
- If additional cases are discovered, they should be added to a new story for sizing/prioritization purposes

### Acceptance Criteria (how do I know when I’m done?)
- [ ] Handle IDN/punycode display according to [Mozilla guidelines](https://wiki.mozilla.org/IDN_Display_Algorithm)
- [ ] Decode / display DWORD IP addresses*
- [ ] Decode / display octal IP addresses*
- [ ] Decode / display hex IP addresses*

\* there is one ignored test in `StringTest.kt` for this, although more may be required for further edge cases

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-14407)

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813232

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
