### ISSUE TITLE
Items selected from AwesomeBar do not respect private mode

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#665]
When I switch to private mode and then select an item it loads it with the private theme but not as a private tab.

Related to #664.

**Comment by sblatz** [comment]
I [did the a-c work for this](fbce345e653903d4fbbd24dba8555bb97aa20eed) but we can't currently upgrade due to 0.44 breaking all browsing.

**Comment by sv-ohorvath** [comment]
Verified as fixed on the latest build (3/6).
