### ISSUE TITLE
[Bug] Opening downloaded PDF file doesn't work.

### ISSUE THREAD

**Issue by emilio** [mozilla-mobile/fenix#6656]
## Steps to reproduce

Go to any PDF file, like http://cepr.net/images//stories/reports/bolivia-elections-2019-11-spanish.pdf

Have Adobe Acrobat Reader as your default app for PDF files.

The file will download, and when it finishes you get a toast to open it.

However clicking that toast, while it will launch the PDF reader, wont open the file and it'll go back to Fenix with an error.

Doing the same on Firefox for Android, or on Chrome, works just fine.

### Expected behavior

 * File opens

### Actual behavior

 * Errors, see screenshot: 
![Screenshot_20191117-193804_Firefox Nightly](https://user-images.githubusercontent.com/1323194/69012143-cb4d8b80-0972-11ea-9db7-c8c0796b089e.jpg)

### Device information

* Android device: Samsung Galaxy A20, I think
* Fenix version: Current Nightly

**Comment by beastdestroyer** [comment]
Can confirm this has been happening for quite some builds now.

Device: Mi 8 Lite; Android Pie: MIUI 11 (happened on MIUI 10 too)
Fenix:
Nightly 191117 18:01 (Build #13211807)
📦: 22.0.0, b385878f2
🦎: 72.0a1-20191115095319

**Comment by marthinwurer** [comment]
This started happening to me recently. Before the download dialog changed, it worked fine, but that might just be because I'm on the play store build.

Device: S8, Android 9

3.0.0 (Build #13431956)
📦: 24.0.0, 968f858c1
🦎: 71.0-20191125115111

**Comment by boek** [comment]
@sblatz any idea?

**Comment by sblatz** [comment]
Downloading & opening this file works for me on nightly

Galaxy S9 9(Nightly 191230 6:21)

![pdf works](https://user-images.githubusercontent.com/4400286/71591328-c7b83300-2ae0-11ea-809b-bd750041bc94.gif)

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **Nightly Build #13650606 from 12/31** using the following devices:
• Google Pixel 3a (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

► Video
![20191231_092409](https://user-images.githubusercontent.com/51314259/71613565-f3eeb500-2baf-11ea-9b1e-77b39ad11ba9.gif)

**Comment by emilio** [comment]
This does indeed work now, but at least on my device there's another issue, see #7443.
