### ISSUE TITLE
[Bug] Too much padding between collection title and items after opening a link

### ISSUE THREAD

**Issue by lindongbin** [mozilla-mobile/fenix#6660]
## Steps to reproduce

Open a link in a collection, close and return.

### Expected behavior

![Screenshot_2019-11-18-12-16-18-410_org mozilla fe](https://user-images.githubusercontent.com/3154109/69024907-d0a4e780-09ff-11ea-9a56-2f1151629eb4.jpg)

### Actual behavior

![Screenshot_2019-11-18-12-16-13-117_org mozilla fe](https://user-images.githubusercontent.com/3154109/69024918-d8fd2280-09ff-11ea-9940-c9d63448b6cf.jpg)

### Device information

* Android device: ?
* Fenix version: 72.0a1-20191115095319

**Comment by cadeyrn** [comment]
Please describe the bug. I don't see a difference.

**Comment by lindongbin** [comment]
> 
> 
> Please describe the bug. I don't see a difference.

![4D)9G@RJY~4QNMQY D)8@RH](https://user-images.githubusercontent.com/3154109/69031370-e8d33180-0a14-11ea-970f-8243ca0c71c0.png)

**Comment by topotropic** [comment]
Thanks for the feedback, we'll address this here https://github.com/mozilla-mobile/fenix/issues/8764.  I'll close it.
