### ISSUE TITLE
[Bug] Private session heading and text don't align

### ISSUE THREAD

**Issue by darkwing** [mozilla-mobile/fenix#6665]
![Screenshot_20191118-090718](https://user-images.githubusercontent.com/46655/69065581-a0504f80-09e5-11ea-998e-4f398ce4cb88.png)

## Steps to reproduce

Enter private mode

### Expected behavior

Title and text have same left position

### Actual behavior

The text appears to be indented

### Device information

* Android device: Pixel 4 XL
* Fenix version:

**Comment by mcarare** [comment]
Issue tracked in: https://github.com/mozilla-mobile/fenix/issues/6629
