### ISSUE TITLE
[Bug] Browser crashes if I try to upload an image in GitHub issues

### ISSUE THREAD

**Issue by Sgt-Miller** [mozilla-mobile/fenix#6668]
So I was about to file another issue (no "open in app option for m.youtube.com" but then this happened when I tried to post the issue.
## Steps to reproduce
Create new issue on GitHub from Firefox preview
Try to upload image
### Expected behavior
Show the image selection window.
### Actual behavior
Firefox crashes.
### Device information

* Android device: 8
* Fenix version: 2.3.0 (Build #13031728)
📦: 18.0.0, ef631b6df
🦎: 70.0-20191014032640

**Comment by cadeyrn** [comment]
probably the same crash  as in #6459.

**Comment by Sgt-Miller** [comment]
Looks like it. Just downloaded nightly and that does not have this issue.
