### ISSUE TITLE
[Bug]QR code scanner has very low quality video and fps compared to in built camera.

### ISSUE THREAD

**Issue by Sgt-Miller** [mozilla-mobile/fenix#6672]
## Steps to reproduce
Start searching
Tap scanner icon
### Expected behavior
High fps, good adaptive exposure
Android camera : 
![Screenshot_20191119-001139](https://user-images.githubusercontent.com/17806210/69081163-53946500-0a35-11ea-9e04-88df99679846.png)

### Actual behavior
Super low fps, bad exposure
Fenix scanner : 
![Screenshot_20191119-001155](https://user-images.githubusercontent.com/17806210/69081118-3eb7d180-0a35-11ea-89b9-a8d2b100cf5e.png)

### Device information

* Android device: Lenovo k8 note, Android 8
* Fenix version : 
Nightly 191118 06:00 (Build #13220607)
📦: 22.0.0, b385878f2
🦎: 72.0a1-20191115095319

**Comment by mcarare** [comment]
Question for UX: Do we think that this is something important to the user. Afterall, the screen is used to scan a QR-code, not to preview things in camera. TY!

**Comment by brampitoyo** [comment]
@mcarare My opinion: ideally, our QR code scanner should work as well other apps/browsers with secondary scanner functionality: 1Password, Opera, Brave, etc.

However, I do acknowledge the fact that QR code isn’t something frequently used by mobile users outside of China (https://technode.com/2018/03/16/qr-codes-nfc-china/).

If I were to label this issue, I wouldn’t label it a “Must”. It would be a “Should” or a “Could”.

**Comment by Sgt-Miller** [comment]
@brampitoyo fwiw QR codes are common here in India too (300 million smartphone users!).

**Comment by brampitoyo** [comment]
@Sgt-Miller Thanks for your on-the-ground observation!

I’d be curious to know whether QR code in India is used mainly for URL input (which is the use case on Fenix), or for payment (in that case, would users use the Paytm app to scan – or does scanning still happen in the browser?)

**Comment by Sgt-Miller** [comment]
For payments, yes they happen in paytm/google pay, not Fenix.  
But I would say other QRs are quite popular here,like in news paper advts (scan to know more), posters(scan to register), etc.      

Anyways, if it's too much work to add exposure adjustment in the initial release, I hope at least the fps issue is fixed. Because it looks very sluggish otherwise!

**Comment by brampitoyo** [comment]
Thanks again @Sgt-Miller. It’s very important for us to learn that QR code has widespread usage in India. We only have limited time and resource to fix issues, and want to make sure that the issues we fix will have the most impact for most number of users.

@mcarare do you think it’s easier and quicker for us to fix the FPS issue just to start, and add smart exposure later?

**Comment by mcarare** [comment]
@brampitoyo We will try to get a fix for this, but we don't want to impact the main functionality of this QR code scanner, and that is to scan a code. The scanner is not intended for any other use, thus it does not need a high fps or image quality, it just needs to correctly and easily scan a code. TY for your input!

**Comment by brampitoyo** [comment]
Agreed, @mcarare. I would not label this issue as a “Must”, and if fixed, then the FPS gets the priority over image quality.

As you said, a scanner isn’t a camera – so it’s ok if it doesn’t perform like a amera.

**Comment by SwampertX** [comment]
Hello, I have been using Fenix for a while, and think the use case for QR codes are not as low as we might perceive. In my university, I scan QR codes on a daily basis to take attendance for classes, get linked to feedback forms during a talk and many other activities.

On the other hand, I was using [andOTP](https://github.com/andOTP/andOTP) their QR scanning solution seems very speedy and well-built. The library they are using is [ZXing](https://github.com/journeyapps/zxing-android-embedded), which is a barcode scanner which will be helpful.

Hopefully this helps, or spurs the discussion a bit!
