### ISSUE TITLE
Search and sort bookmarks/history

### ISSUE THREAD

**Issue by Sgt-Miller** [mozilla-mobile/fenix#6674]
### Why/User Benefit/User Problem
Im sure lot of us have got hundreds of bookmarks. An option to search for them and sort them will be very useful. 
Should be there for history too.

### What/Requirements
Search bar and sort options for bookmarks and history.
### Acceptance Criteria (how do I know when I’m done?)
For both bookmarks and history(separately)
-Option to search
-Sort by name (ascending/descending)
-Sort by date
-Sort by popularity(number of times user has visited the link)

**Comment by cadeyrn** [comment]
Sorting bookmarks is #4348.
Searching bookmarks and history is #6232.
