### ISSUE TITLE
Store collections as folders in bookmarks so that it can be accessed from Desktop

### ISSUE THREAD

**Issue by supersonic71** [mozilla-mobile/fenix#6676]
### Why/User Benefit/User Problem
First off, collections is a very useful feature and I really like using it on mobile. But looks like it doesn't sync with desktop.   
### What/Requirements
So to fix this, whenever I save a collection, Firefox will create a folder in bookmarks with folder name as collection name and store the list of websites in that collection in that folder.
### Acceptance Criteria (how do I know when I’m done?)
Save collections as folders in bookmarks.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-14428)

**Comment by yoasif** [comment]
Personally, I don't think they should be saved as bookmarks, but should be available as synced tabs/collections like have worked for Fennec.

**Comment by venetian-ftaires** [comment]
Rather than automatically storing them as folders, I think there should be the option to "open bookmark folder as collection", and "save collection as bookmark folder".

I understand currently each page in a collection is a little more than just a bookmark, given it stores the page history, but I'm not sure that's of too much benefit to anyone.

This idea gained some good traction and discussion when I posted it on r/firefox: https://www.reddit.com/r/firefox/comments/h7kzp4/collections_in_firefox_preview_for_android_great/

My other point when posting there was that it would be good for collections to be a more defined browsing container, where the collection's tabs remained grouped when open, and new tabs from clicking links still open within the collection, as well as blank new tabs when desired.

**Comment by klint** [comment]
> My other point when posting there was that it would be good for collections to be a more defined browsing container, where the collection's tabs remained grouped when open, and new tabs from clicking links still open within the collection, as well as blank new tabs when desired.

What you describe looks more like Panorama-style groups in Desktop Firefox (implemented with the "Simple Tab Groups" addon for instance). I'm not sure that collections are really the same concept. They still look more like folders on the mobile app that are more easily reachable than nested within the bookmarks themselves.

**Comment by venetian-ftaires** [comment]
> > My other point when posting there was that it would be good for collections to be a more defined browsing container, where the collection's tabs remained grouped when open, and new tabs from clicking links still open within the collection, as well as blank new tabs when desired.
> 
> What you describe looks more like Panorama-style groups in Desktop Firefox (implemented with the "Simple Tab Groups" addon for instance). I'm not sure that collections are really the same concept ported to the mobile app. They still look more like folders there that are more easily reachable than nested within the bookmarks themselves.

This sort of illustrates my main problem with them, no one's really sure what they are conceptually. If they're easily accessible bookmark folders as you describe they should really be linked to actual bookmark folders in some way, being completely separated doesn't really make sense to me. This ignores the fact however, that they're sort of groups of saved sessions, given that you can click back to navigate to previously visited pages when opening a tab from one. I'm not too sure what the use of this is, but it makes them even more different to bookmarks and harder to link up. They're a little bit of a few different things, and as such struggle to be a defined thing in themself. 

What you quoted was only secondary to my main point and is something I'd like to see, but it's more a nice-to-have than a direct issue that they lack that feature. That coupled with save as/load from bookmark folder (and no session-ness) would be my ideal implementation of them, but it depends on exactly what they're meant to be in the first place.

**Comment by klint** [comment]
You definitely have a point.  We don't know what collections are exactly. The fact that they just capture sessions is also rather disturbing. Maybe "page snapshots" would be a better way of describing for what is being collected there.

**Comment by Dunexus** [comment]
Based on this comment https://github.com/mozilla-mobile/fenix/issues/11967#issuecomment-649780809 clarifying what collections are is something UX team is considering.

I agree with you guys that as long as there is no clear statement about what collections are, it will be hard to tell how they should behave regarding to keeping tab history, keeping a cached version of the page, where it should be synced, etc.

**Comment by Poopooracoocoo** [comment]
#7325

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813758

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
