### ISSUE TITLE
Update Custom Tabs to Match UX

### ISSUE THREAD

**Issue by colintheshots** [mozilla-mobile/fenix#668]
Custom tabs were restyled in #203 to have a top app bar with developer-provided actions and to appear substantially different from the normal Fenix browser fragment. A complete restyling of our browser fragment will be required for custom tabs.

**Comment by jonalmeida** [comment]
When working on this, work may need to be done in a-c as well, so feel free to have a look around the project board to see if it's already been filed or in-progress: https://github.com/orgs/mozilla-mobile/projects/7

Work has already been done in r-b to have custom menu for Custom Tabs for integrating the feature. The [`CustomTabsIntegration.kt`](https://github.com/mozilla-mobile/reference-browser/blob/master/app/src/main/java/org/mozilla/reference/browser/browser/CustomTabsIntegration.kt) is worth peeking at too.

**Comment by bbinto** [comment]
@mheubusch - let's create some user stories for this tomorrow.

**Comment by sblatz** [comment]
This will require some a-c work to customize the `DisplayToolbar` so that it can show description and title, as well as adding room for a custom icon.

**Comment by sblatz** [comment]
This is done, but blocked on [this a-c change I made](https://github.com/mozilla-mobile/fenix/issues/668) to land.

**Comment by vesta0** [comment]
Will be ready for QA as soon as the [A-C issue](https://github.com/mozilla-mobile/android-components/issues/2615) lands.

**Comment by bsurd** [comment]
This has been verified by QA, Closing as there are no blockers for this and all other issues will be resolved separately.

**Comment by cadeyrn** [comment]
> This has been verified by QA, Closing as there are no blockers for this and all other issues will be resolved separately.

#1727 should be considered as a blocker because it doesn't match the UX defined in #203 and it's a major issue which makes Fenix unusable as default browser because of the fact that content of websites is not visible.
