### ISSUE TITLE
Blocking redirections to some servers

### ISSUE THREAD

**Issue by marcinwiacek** [mozilla-mobile/fenix#6682]
### Why/User Benefit/User Problem

When I do for example some searches from Google, after opening URL it's opened, but later I'm immediately redirected to other page (in this concrete case this is some spam/advertising/trolling URL)

### What/Requirements

When page is redirecting the whole tab to other URL in different server, user is asked:

You're redirected from ... to the ...
Do you want to:
a. open new URL
b. block new URL ?

When user is selecting option b, browser doesn't show this popup, but just blocks direction at all.

### Acceptance Criteria (how do I know when I’m done?)

After opening page with redirection other page (for example with Java Script changing document.url.location) user is asked, if want to open new URL or block it. After selecting blocking browser is adding new server url to blocking list and instead of redirection is displaying some error message.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-14433)

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813214

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
