### ISSUE TITLE
The "Share" menu is a bit messy

### ISSUE THREAD

**Issue by julienw** [mozilla-mobile/fenix#6687]
I know there are a few other bugs related to this topic (#6023 #3861), so feel free to close this one. But I tried to capture my frustations with the current sharing menu here.

The things displayed in the share menu seem to be roughly alphabetically sorted, from the english names (even if the localized titles would sort the items differently).
My main issue is that I never use the things that appear first for me (Bluetooth, Facebook (4 times!), LinkedIn), and I use a lot more often the ones that appear further right, that I need to scroll to access (copy, messages, whatsapp).

Ideally I'd like that:
1. the items are sorted from their localized names
2. the most commonly used items are available more easily, for example they could be displayed separately as well, next to / below the part "send to a device".

As a reference, the old Firefox/Android had the last used item readily available in the main menu. This wasn't perfect because I was switching between 2 or 3 items often, but still better.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-14436)

**Comment by cassidyjames** [comment]
Honestly, I feel pretty strongly that the browser should use the OS’s built in share menu and not try to invent its own thing. Sending to another one of my own devices is very distinct from sharing to a friend, but mixing them in one UI means I miss out on all the features of the Android 10 share menu like predicting which conversations and as are most relevant.

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1809791

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
