### ISSUE TITLE
Fennec migration: Setup build type for Fennec nightly.

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/fenix#6688]
Like #4873 created a `fennecProduction` build type and #6622 is creating a `fennecBeta` build type, this issue is about creating a build type for Fennec Nightly so that this new build type can replace a Fennec Nightly installation.

# Build config

- [x] Create a `fennecNightly` build type
- [x] Reuse `sharedUserId` from Fennec Nightly
- [x] Re-use versionCode mechanism of Fennec
- [x] Reuse Fennec Nightly package name

### RelEng

- [ ] Reuse Fennec Nightly signing keys for `fennecNightly` build.

### Tokens

- [ ] Adjust
- [ ] Leanplum
- [ ] Sentry: For production we use `fenix-fennec` currently. Do we need `fenix-fennec-nightly`?
- [ ] Firebase

**Comment by emdemir** [comment]
Please tell me if I have to open another issue for this, but it seems "Fennec F-Droid" (the build of Fennec provided by F-Droid doesn't seem to be detected for a migration.

**Comment by pocmo** [comment]
Token work continues in #6898.

**Comment by pocmo** [comment]
> Please tell me if I have to open another issue for this, but it seems "Fennec F-Droid" (the build of Fennec provided by F-Droid) doesn't seem to be detected for a migration. Does it have to be an official build of Fennec to be detected for migration?

This heavily depends on the build configuration F-Droid uses to build Fennec. It is definitely possible to build a compatible Fenix version following the same approach - adapting the package name, sharedID etc.

**Comment by ebalazs-sv** [comment]
Hello!
Are there any builds available for replacing Fennec Nightly? The builds from https://github.com/mozilla-mobile/fenix/wiki/Fennec-Migration are replacing Fennec Release.

**Comment by ebalazs-sv** [comment]
Verified as fixed on Nightly 191210 GV 72 with Samsung Galaxy S8 (Android 9) - ARM64; Motorola Nexus 6 (Android 7.1.1); Xiaomi Mi Pad 2 (Android 5.1) - x86.
Fennec Nightly is replaced by Fenix Nightly migration build.
I will move this to Done.
