### ISSUE TITLE
[Bug] Dismiss the Download failed in-app notification when Try again from the system notification is pressed

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#6689]
## Steps to reproduce
1. Download a file.
2. Cut the wifi. Download fails.
3. Turn on Wifi. Press Try again in the system notification.
4. Observe the in-app notification.
### Expected behavior
The failed download in-app notification is dismissed as well.
### Actual behavior
The failed download in-app notification still displayed.
### Device information

* Android device: Pixel (Android 10), OnePlus 5T (Android 9.0)
* Fenix version: Nightly 11/19

**Comment by sblatz** [comment]
> The failed download in-app notification still displayed.

The download may have failed again. When I was testing this, it would take about 10 seconds for my WiFi to go back online, so pressing in that first 10 seconds would just immediately create another download failed notification.

Can you try waiting and pressing to see if this still happens? :)

**Comment by AndiAJ** [comment]
Hi @sblatz I've just check on the latest **Nightly Build #13240608 from 20/11** and **this is still reproducible** on the following devices:
• Google Pixel 3a XL (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• OnePlus A3 (Android 6.0.1)

► Video
![20191120_095448](https://user-images.githubusercontent.com/51314259/69220423-9e20f900-0b7d-11ea-90b9-50fe46afc0f3.gif)

**Comment by sblatz** [comment]
@AndiAJ This is expected based on the steps you're taking. If you press "try again" from the **in-app** notification, the behavior will be correct. We did not implement it so that the notification and the in app notification are tied together in the steps you're taking here. 

If this is something we're wanting to do it should be an additional feature request.

**Comment by softvision-miralobontiu** [comment]
Verified as fixed with Google Pixel 3 (Android Q) on the latest Nightly 11/25.
