### ISSUE TITLE
Make Custom Tabs Handle Incoming Intent Flags

### ISSUE THREAD

**Issue by colintheshots** [mozilla-mobile/fenix#669]
Fenix custom tabs should handle incoming intent flags for using the theme color of the app, showing custom menu items from the app, showing custom action buttons from the app, letting the app define animations, and letting the app define the close button drawable.

Here is a list of all the customizations we should aim to support:
https://developer.android.com/reference/android/support/customtabs/CustomTabsIntent.Builder

**Comment by vesta0** [comment]
@colintheshots how come this was moved to Milestone 3?

**Comment by jonalmeida** [comment]
I spoke to @colintheshots and this is a duplicate of work already done in https://github.com/mozilla-mobile/fenix/pull/333

Only the UX requirements (https://github.com/mozilla-mobile/fenix/issues/203) need to be implemented, core functionality already exists.

**Comment by colintheshots** [comment]
I created this from a breakdown ticket in Milestone 2. It seems this half of the work has actually already been done. The UX half is not done yet.

**Comment by vesta0** [comment]
@colintheshots @jonalmeida understood, thank you for clarifying!
