### ISSUE TITLE
[Bug] Some trackers are not blocked despite reported so

### ISSUE THREAD

**Issue by concastinator** [mozilla-mobile/fenix#6693]
## Steps to reproduce

This happens somewhat randomly, so that I cannot trigger it at will. Please see the screenshot.
![Screenshot_20191119-200337](https://user-images.githubusercontent.com/57685970/69173737-0da8d100-0b09-11ea-855b-68701638921c.png)

Sometimes an add delivered from icorpadro.hit.gemius.pl slips through the tracking protection, despite this tracker being reported to be blocked (notice that the shield is blue, and ETP is set to "strict" with no exceptions allowed).

### Expected behavior

The add should not get displayed.

### Actual behavior

The add gets displayed.

### Device information

* Android device: Nokia 5 (model TA-1024) with up-to-date Android 9 (Android One program)
* Fenix version: 191119 06:00 (build 13230608)

**Comment by eliserichards** [comment]
Closing as fixed :)
