### ISSUE TITLE
[Bug] URL bar / history contains wrong titles for pages

### ISSUE THREAD

**Issue by marcinwiacek** [mozilla-mobile/fenix#6701]
## Steps to reproduce
1. open page A
2. start opening page B and fast go into page C
3. try to enter URL for page B again in URL bar

It works only sometimes and looks like race condition

### Expected behavior

URL bar contains suggestion for page B with title from correct page (B) - it (title) should be updated every time when you load some URL

### Actual behavior

![Screenshot_20191119-201012_Firefox Nightly](https://user-images.githubusercontent.com/24834168/69194028-6fc4fe80-0b28-11ea-8f19-2ea2b141816c.jpg)

On the example you can see dobreprogramy.pl (page B) with title from other page lenovo.pl (page A)

### Device information

* Android device: S7 / Android 8
* Fenix version: Nightly 191119

**Comment by marcinwiacek** [comment]
Wrong title I see also in history...

**Comment by ekager** [comment]
Hmm looks like `HistoryStorage` is recording titles that don't match the session URL. The suggestions are being pulled from history. This will need AC work

**Comment by mcomella** [comment]
FYI: this is still an issue. I reproduced this issue during regular usage (not necessarily following the STR) on Nightly 200219 using fivethirtyeight.com and rockpapershotgun.com:

![Screenshot_20200219-151122](https://user-images.githubusercontent.com/759372/74885460-767f2f80-532a-11ea-8003-a1e9ca9912f7.png)

I noticed there may be something related to http and https going on here.

**Comment by marcinwiacek** [comment]
Just for reference and note: it seems, that Gecko engine is returning title for wrong page.

One of possible fixes: https://github.com/marcinwiacek/true-android-components/commit/4bcb11f71dee40ff51eb0ad8ffdce79d17a2f955
