### ISSUE TITLE
Enable FxA state encryption for release

### ISSUE THREAD

**Issue by grigoryk** [mozilla-mobile/fenix#6704]
https://github.com/mozilla-mobile/fenix/issues/5938 enabled account state encryption for nightly users.

Things to watch out for in Sentry:
- instances of `AbnormalFxaEvent`, specifically `MissingExpectedAccountAfterStartup`
- instances of `AbnormalAccountStorageEvent@UnexpectedlyMissingAccountState`

If we don't see a spike in these after a few weeks, let's consider flipping encrypted storage for the release channels.

### Acceptance Criteria
- [x] Look on Sentry and verify that there are not a lot of the highlighted issues. If there are, file and prioritize them.
- [ ] Enable FxA state encryption on release

**Comment by grigoryk** [comment]
Note that there's currently _some_ volume of `MissingExpectedAccountAfterStartup`. I expect those to drop to zero once https://github.com/mozilla-mobile/android-components/pull/5103 makes its way to nightly users.

**Comment by grigoryk** [comment]
There was a non-zero volume of Android KeyStore related crashes in Sentry. This needs more investigation.

**Comment by liuche** [comment]
Still seeing [a lot of crashes](https://crash-stats.mozilla.org/signature/?product=Fenix&signature=%5BINFO%5D%20org.mozilla.fenix.components.AbnormalFxaEvent%24MissingExpectedAccountAfterStartup%3A%20at%20org.mozilla.fenix.components.AccountAbnormalities%24accountManagerInitializedAsync%241.invokeSuspend%28AccountAbnormalities.kt%3A18%29&version=74.0a1&date=%3C2020-01-18T03%3A59%3A41%2B00%3A00&date=%3E%3D2020-01-11T03%3A59%3A41%2B00%3A00) for `AbnormalFxaEvent$MissingExpectedAccountAfterStartup`

**Comment by ValentinTimisica** [comment]
Based on this [comment](https://github.com/mozilla-mobile/fenix/blob/e25ee98d7de743fe4ac86eaf5ef3d5284383462c/app/src/main/java/org/mozilla/fenix/components/BackgroundServices.kt#L76) I understand that FxA state encryption needs to be enabled for all channels. So I made a [PR](https://github.com/mozilla-mobile/fenix/pull/7858) where I set ```secureStateAtRest = true```. Is this correct?
If it needs to be enabled just for Nightly and Release I will change it accordingly.

**Comment by ekager** [comment]
Closing this because we've decided to wait a bit longer to enable for all channels see #8324

**Comment by ekager** [comment]
Didn't mean to close the issue

**Comment by liuche** [comment]
We'll do this after release, based on some concerns about a low number of crashes #8324 and how this would affect Fennec Release population devices. This is probably low because the Fenix release population is already using the system keystore, but to be safe we'll turn this on as an experiment rollout after our release.

**Comment by liuche** [comment]
@grigoryk do we still care about this bug
