### ISSUE TITLE
[Bug] a removed search engine does not immediately appear in "Add search engine"

### ISSUE THREAD

**Issue by cadeyrn** [mozilla-mobile/fenix#6709]
### Steps to reproduce

1. remove a search engine
2. press "Add search engine"
3. go back
4. repeat step 2

### Expected behavior

The removed search engine appear in the list of search engines after step 2.

### Actual behavior

The removed search engine appear in the list of search engines after step 4, but not after step 2.

### Device information

* Android device: OnePlus 7T Pro McLaren Edition / Android 10
* Fenix version: master branch 607c3d4c873aaf2fb646e50588329a42f324cf01

**Comment by mcarare** [comment]
waiting on #6849

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **Nightly Build #13540607from 12/20** using the following devices:
• Google Pixel 3a (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

► Video
![20191220_095804](https://user-images.githubusercontent.com/51314259/71239724-f16aa080-230f-11ea-857e-8932cde12909.gif)
