### ISSUE TITLE
[Bug] favicons of new search engines are very low quality

### ISSUE THREAD

**Issue by cadeyrn** [mozilla-mobile/fenix#6710]
### Steps to reproduce

1. open search settings
2. press "Add search engine"

### Expected behavior

High quality favicons of the new search engines.

### Actual behavior

The new search engines have very pixelated favicons.

![Screenshot_20191120-073137](https://user-images.githubusercontent.com/1100614/69214736-ffd66880-0b67-11ea-9c3b-c04c05296ac0.jpg)

### Device information

* Android device: OnePlus 7T Pro McLaren Edition / Android 10
* Fenix version: master branch 607c3d4c873aaf2fb646e50588329a42f324cf01

### Design Work
- [x] Request for Comments from UX team
- [ ] ~Usability testing if a new pattern or potentially confusing UI~
- [ ] ~Request for Comments from Fenix team and/or A/C, GV, Sync, etc as needed~
- [ ] ~Interaction details included~
- [x] Accessibility ~- is this a review by someone,~ just keeping it in mind?
- [ ] ~For existing UI changes, deltas are highlighted~
- [ ] ~Strings/content reviewed and approved~
    - [ ] ~Are they too long for the component in other locales~

### Deliverable
- [x] Assets uploaded to Google Drive
- [x] Links to deliverables (spec, assets) posted in comment 0

### Deliverable Links
- Assets: https://drive.google.com/drive/folders/1-ROxk1MvHar13wxFYWYYvoJRxTKd7uI_?usp=sharing

**Comment by mcarare** [comment]
Question for UX: Can we receive new xml assets for the search plugins? Or should we modify the images for the existing ones (we will still need images to encode them)? TY!

**Comment by brampitoyo** [comment]
@mcarare I wasn’t able to generate XML, but have managed to convert all assets into SVGs.

They’re located in this folder: https://drive.google.com/drive/folders/1-ROxk1MvHar13wxFYWYYvoJRxTKd7uI_?usp=sharing

Would you be able to encode them?

**Comment by mcarare** [comment]
Yes! I will try to see what image quality those provide and get back to you! Thanks

**Comment by brampitoyo** [comment]
Hi @mcarare, do you prefer PNGs at @2x resolutions? No problem, I can generate them. I just thought that having SVGs would be more scaleable.

The PNGs have been generated at @2x resolution. They’re located in the same folder. Let me know if you’d like any other size!

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **Nightly Build #13460608 from 12/12** using the following devices:
• Google Pixel 3a (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• Motorola G4 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

► Screenshot comparison
![rsz_screenshot_20191213-122004](https://user-images.githubusercontent.com/51314259/70704431-a67ed680-1cda-11ea-8188-83dbe70351b4.png)

► Video
![20191213_115736](https://user-images.githubusercontent.com/51314259/70703569-0ffde580-1cd9-11ea-9c93-ae3239ae2ee5.gif)
