### ISSUE TITLE
[Bug] No site icons in the main page / history

### ISSUE THREAD

**Issue by marcinwiacek** [mozilla-mobile/fenix#6716]
## Steps to reproduce

Issue is random - after switching to/from Firefox it stops displaying icons for sites in the main page / history.

### Expected behavior

Icons are visible.

### Actual behavior

Icons for the same sites are sometimes displayed sometimes not.

### Device information

* Android device: Galaxy S7 / Android 8
* Fenix version: Nightly 191120

![Screenshot_20191120-091738_Firefox Nightly](https://user-images.githubusercontent.com/24834168/69239316-388f3580-0b9a-11ea-81dc-69f9907d9e44.jpg)
![Screenshot_20191120-104759_Firefox Nightly](https://user-images.githubusercontent.com/24834168/69239317-3927cc00-0b9a-11ea-8b14-abe88fffe4de.jpg)

**Comment by marcinwiacek** [comment]
Note: in previous nightly builds I have observed, that for example on opening history window it was fine, after scrolling down and up icons were removed

Restarting browsers many times helped.

**Comment by ekager** [comment]
@marcinwiacek has this been better for you? I think we've made improvements here

**Comment by marcinwiacek** [comment]
Issue still irregularly happens in latest Nightly from Google Play (200320) -> maybe a little less often, but it's still visible.

**Comment by marcinwiacek** [comment]
Update to my last comment: I've opened https://github.com/mozilla-mobile/fenix/issues/10129 because my Nightly was not updated from Google Play. Right now haven't seen it so far with April version.

**Comment by marcinwiacek** [comment]
for reference: I've seen this with 200422 version today.
