### ISSUE TITLE
Implement a way to sort the Saved Logins/Accounts Alphabetically or by Recently used

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/fenix#6719]
### Why/User Benefit/User Problem
As a user, I want to sort my Saved logins(for the new section) Alphabetically or by Recently used.
### What/Requirements
Adding a button that can sort the Saved logins/accounts Alphabetically or by Recently used.
### Acceptance Criteria (how do I know when I’m done?)
The Saved logins can be sort Alphabetically or by Recently used.

**Comment by ekager** [comment]
Closing for #9505
