### ISSUE TITLE
[Bug] Pinch to zoom doesn't override other touch events in GV

### ISSUE THREAD

**Issue by boek** [mozilla-mobile/fenix#6723]
## Steps to reproduce
1. Enable force zoom accessibility setting 
2. Go to an instagram gallery post
3. Pinch to zoom on the photo

### Expected behavior
Page zooms

### Actual behavior
Gallery tries to swipe to next photo

**Comment by boek** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1639083

**Comment by ekager** [comment]
bugzilla closed as invalid. closing
