### ISSUE TITLE
[consultation] Investigate the impact of glean-core on Fenix performance

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#6725]
### What
The Glean team wants to measure how their new Rust integration has affected the performance of the Glean library in Fenix: see https://bugzilla.mozilla.org/show_bug.cgi?id=1594431 for details.

### Impact
This work may affect startup - one of our key metrics - and it's good to provide assistance quickly so folks think about how quick and easy it was to work with us and think about performance more often.

Giving this a high priority so we can make a good impression. :)

### Acceptance criteria
- Measure the impact of the change on startup in the proposed period: specifically, the call to  `Glean.initialize()`
  - We should understand the implementation to know which kind of startup we need to look at: cold/warm/app link/etc.
  - Consider whether Nimbledroid's methodology is sufficient to determine the impact
- Investigate `org.mozilla.fenix.GleanMetrics.*` calls: report changes to these calls in the proposed period
- Look for other potential perf impacts of change (e.g. apk size, page load): understanding the implementation may help here
- Given ^, identify gaps in test coverage or telemetry to add to the backlog
- **Results are reported to the Glean team.** mcomella heard the FxR team may also be interested: ask the Glean team if they want to forward the information to them.

Where the proposed period is before and after Oct 24 (when the Rust changes landed).

**Comment by emalysz** [comment]
Link to public doc: https://docs.google.com/document/d/1GlqkaAKMcij0RLPs9aWyPmscR8eXgRn_xxy8JSc0CdU/edit#

Initialization of GleanMetricsService.start has undergone a 84.45% improvement between the two profiled versions of Fenix. Before the improvement, GleanMetricsService.start() accounted for roughly ~28% of FenixApplication.onCreate() but now currently accounts for only ~5.9%. 

The performance of GleanMetricsService’s shouldTrack has undergone a 5.54% improvement and Track has regressed by 306.13%.

Again, Fenix startup is blocked by these methods. Between October and December, the performance improvement of GleanMetricsService.start more than compensated for the regression in GleanMetricsService.track and the changes to the code resulted in a significant 116.172 ms overall improvement in the time it takes to start Fenix.
