### ISSUE TITLE
Determine if we should avoid telemetry upload to canonical servers during performance testing

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#6727]
This issue comes tangentially from the discussion in https://bugzilla.mozilla.org/show_bug.cgi?id=1594433#c4.

### Why/User Benefit/User Problem
On both Nimbledroid and Raptor, we test, or will eventually test, unmodified Fenix Nightly and release APKs. By default, these record and upload telemetry. Since these are unmodified, afaik the telemetry will upload by default.

### Impact
If we don't do this, the Fenix telemetry numbers might be skewed by our performance tests.

### Acceptance Criteria (how do I know when I’m done?)
- Define how skewed the telemetry would be from our performance tests
  - FYI: ND runs tests (or just cold startup?) 10 times to get the final timing
  - Is storage reset between tests? How does that affect telemetry client IDs and other things?
- Determine if we want to prevent telemetry upload to our canonical servers during perf testing, including the trade-offs
  - We may have to rewrite the cold startup test for ND
- If so, prevent telemetry from uploading to our canonical servers during perf testing

---

Alessio has some solution suggestions:
> There are two approaches, I think, we could follow:
>
> * Best option: Is the Fenix build used for ND using the same application id as the one on the play store, i.e. org.mozilla.fenix? If so, would you consider using a build with a different application id? e.g. org.mozilla.fenix.perf.nd? This would guarantee, without changing anything in the code, that the telemetry goes to a different place, without polluting other data. Moreover, this would allow to analyse the performance telemetry that we get from both ND and Glean.
>
> * The debug activity could be used to launch Fenix, tagging pings so that they go to the debug view and can be told apart from normal pings. This is quirky as it pollutes the dashboard used by QA. The first option is cleaner and does not require any hack at all.

**Comment by mcomella** [comment]
@Dexterp37 For our prioritization, do you feel this is a high priority to investigate? If so, when should this be done by? ASAP or for the Fennec -> Fenix release?

**Comment by Dexterp37** [comment]
@mcomella I think this is worth investigating sooner, rather than later. There's a very low hanging fruit type of question we could answer, though: Is the Fenix build used for ND using the same application id as the one on the play store, i.e. `org.mozilla.fenix`?

**Comment by mcomella** [comment]
> Is the Fenix build used for ND using the same application id as the one on
> the play store, i.e. org.mozilla.fenix?
>
Yes: we test release builds with that app ID (though uploads are currently
broken: https://github.com/mozilla-mobile/perf-frontend-issues/issues/21)
and we test Nightly builds with `org.mozilla.fenix.nightly`.

**Comment by Dexterp37** [comment]
> 
> Is the Fenix build used for ND using the same application id as the one on the play store, i.e. org.mozilla.fenix?
> Yes: we test release builds with that app ID (though uploads are currently broken: [mozilla-mobile/perf-frontend-issues#21](https://github.com/mozilla-mobile/perf-frontend-issues/issues/21)) and we test Nightly builds with `org.mozilla.fenix.nightly`.

@mcomella I think this should definitely be investigated sooner, rather than later, if only to quantify the impact of the numbers.

The *end* solution to this would be to use an APK with a different application id, as suggested [here](https://bugzilla.mozilla.org/show_bug.cgi?id=1594433#c4). See the bug for the discussions of the implications.

Before fixing this, though, it would be good to have a sense of how much stuff was being sent, to annotate dashboards/data so that analysts will not be surprised in the future. (cc @fbertsch)

**Comment by mcomella** [comment]
Triage notes:
* Raptor may not have outgoing network connections
* We don't want to omit collection or startup code, which can affect perf.

**Comment by liuche** [comment]
@mcomella is the fix for this to make a different app id using a different build? Or are there more things would be necessary here (if we can't get that done).

**Comment by mcomella** [comment]
> @mcomella is the fix for this to make a different app id using a different build? Or are there more things would be necessary here (if we can't get that done).

I haven't discussed with Alessio but I'd be concerned that we aren't testing our actual production builds but instead builds built alongside them.

**Comment by liuche** [comment]
What if you made them with the same gradle config as Release? fwiw that's what we're doing with Fenix Beta, and we're trying to keep Beta and Release as close as possible.

**Comment by mcomella** [comment]
> What if you made them with the same gradle config as Release? fwiw that's what we're doing with Fenix Beta, and we're trying to keep Beta and Release as close as possible.

[We are currently doing that](https://searchfox.org/mozilla-mobile/rev/e9a4a4de0e221189a8a3b6df98aa11b91731a347/fenix/app/build.gradle#52) but it does not guarantee the builds will not diverge in the future (e.g. someone adds a runtime check that excludes `forPerformanceTest`). Also, it's possible there is a bug in the build system that produces different builds despite identical configurations so it's ideal to test on the actual release build.

**Comment by boek** [comment]
We decided this is not something we want to do due to low impact on our telemetry numbers. Feel free to comment if you disagree.

**Comment by Dexterp37** [comment]
Note for the devs: the bug in which ping tagging is getting implemented is [this one](https://bugzilla.mozilla.org/show_bug.cgi?id=1634064).

**Comment by mcomella** [comment]
Moving high-level bugs, such as this one, to JIRA for easier month-to-month planning: https://jira.mozilla.com/browse/FXP-1251 Let me know if this is an issue for anyone.
