### ISSUE TITLE
Create Fenix Crash/ANR Monitoring Process

### ISSUE THREAD

**Issue by ekager** [mozilla-mobile/fenix#6729]
As our releases get closer to replacement date, we need to decide how we will continue to monitor crash reports in a consistent way to make sure we're catching important crashes as soon as possible and filing to the right teams.

Questions 
- What is the current crash monitoring process? 
- What are the sources? - Sentry dash/GP/Glean/Crash-Stats (Socorro)
- How do we decide what is an acceptable crash rate?
- What about ANRs? (and ANR rate?)

Outcomes
- Someone(s) reliably monitors nightly crash reports (release crashes handled by release manager)
- Crashes get filed (triage/prioritization) for correct team
- Document crash filing process (maybe add template for faster filing)
- Communicate responsibilies to team (if rotating)

**Comment by ekager** [comment]
CC @csadilek I know you've been doing most of the filing of crashes, do you have any thoughts here or questions? I think I want to make sure it's not just you looking at Sentry.

**Comment by csadilek** [comment]
@ekager Thank you for working on this! App crashes are now also sent to Soccorro (in addition to Sentry) which should make it easier for release management to help us spot problems e.g. https://github.com/mozilla-mobile/android-components/issues/5050

However, I think, that we (the dev team(s)) also need to play a role in monitoring Nightly. As we're landing new features, it's much easier for us to detect problems early and fix them before they hit a wider audience. I think we need to decide whether this is a dedicated smaller team (self-coordinating) or a rotating role in the bigger team. I agree though that more people need to be involved though :).

**Comment by liuche** [comment]
@mcomella ^ here's our crash bug, that we could consider adding ANR monitoring to (bc it's also in the Google Play dashboard).

**Comment by liuche** [comment]
Some [notes](https://docs.google.com/document/d/1fAt1Ek72_cFkVn7VCjgM2sbLd9pWp3hGy8AOR4j_U5I/edit)

**Comment by liuche** [comment]
Closing for #9560 9560
