### ISSUE TITLE
[Bug] When bookmark folders are deleted consecutively, the folder list becomes buggy

### ISSUE THREAD

**Issue by cesarabreu** [mozilla-mobile/fenix#6731]
![bookmark_folder_delete](https://user-images.githubusercontent.com/36203921/69292198-410c5e00-0be4-11ea-92a3-d96392fcc3e1.gif)

## Steps to reproduce
- navigate to Bookmarks
- create some folders (if you don't have at least a couple of them)
- delete consecutively at least two folders
### Expected behavior
- deleted folders should desapear for good
### Actual behavior
- deleted folders may come back, letting the folders list inconsistent and buggy
### Device information

* Android device: Mi9T Pro - Android 9
* Fenix version: 1.0.1947 debug

**Comment by ekager** [comment]
Reopening for QA

**Comment by sv-sdeiac** [comment]
Hi, I can confirm that the issue is not anymore reproducible on the latest Firefox Preview Nightly 12/2 (build #13361807).
Devices:
- Nokia 6 (Android 7.1.1);
- Motorola Moto G6 (Android 8.0);
- Samsung Galaxy S8 (Android 9);
- Google Pixel 2 (Android 9).
