### ISSUE TITLE
Exception when unbinding service org.mozilla.fenix/.customtabs.CustomTabsService android.os.DeadObjectException

### ISSUE THREAD

**Issue by miketaylr** [mozilla-mobile/fenix#6743]
Originally reported @ https://github.com/webcompat/web-bugs/issues/44583

In Fenix Preview Nightly (but not "regular" Fenix Preview) Firefox Preview Nightly 191118 (🦎: 72.0a1-20191115095319) and 191118, visit https://www.microsoftedgeinsider.com/en-us/whats-new and before loading the site will crash the browser.

**Comment by ValentinTimisica** [comment]
I investigated and I could reproduce the crash on Fennec, Fenix, Firefox Focus, Reference Browser and GeckoView Example. As such I think the issue stems from GV.

### Device information

* Android device: Samsung Galaxy Note 10 (Android 10).
* Fennec, Reference Browser and Focus versions: Latest from store.
* GeckoView Example: from latest central.

### Videos with the crash
* [Fennec](https://drive.google.com/file/d/1ZVIQJQZIDkbSodgBfMl8k7NkIHMTBy_j/view?usp=sharing)
* [Firefox Focus](https://drive.google.com/file/d/1AhQ7iWSmylnIFdA-YGiCfH5Da0flxjAN/view?usp=sharing)
* [Reference Browser](https://drive.google.com/file/d/1i0rJOyKkscl5LqrUzdv-1P6-IwouyPtV/view?usp=sharing)
* [GeckoView Example](https://drive.google.com/file/d/1CZPVSjtU0Hdbswyiurx-0jjFOrJlpGpp/view?usp=sharing)

<details><summary>StackTrace</summary>
<p>

```
android.os.DeadObjectException
        at android.os.BinderProxy.transactNative(Native Method)
        at android.os.BinderProxy.transact(BinderProxy.java:526)
        at android.view.IWindow$Stub$Proxy.windowFocusChanged(IWindow.java:797)
        at com.android.server.wm.WindowState.reportFocusChangedSerialized(WindowState.java:3591)
        at com.android.server.wm.WindowManagerService$H.handleMessage(WindowManagerService.java:5136)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:237)
        at android.os.HandlerThread.run(HandlerThread.java:67)
        at com.android.server.ServiceThread.run(ServiceThread.java:44)
```
</p>
</details>

**Comment by ValentinTimisica** [comment]
I filed a [issue](https://bugzilla.mozilla.org/show_bug.cgi?id=1617139) for this in bugzilla.

**Comment by abodea** [comment]
#### Hello, note that I tried to reproduce this issue for more information please check the following:
| Browser  | Device |  Android version |  Crash? | 
| :-------------:| :-------------: | :-------------: | :-------------: |
|  **Fenix Nightly 2/21**          |   **Google Pixel 3a XL**  |    **10**        |       ✔️           |
|       **Fenix Nightly 2/21**         |        **Samsung Galaxy S10+**     |       **9**     |        ❌             | 
|     **Fenix Nightly 2/21**           |       **Samsung Galaxy S8+**      |         **8**   |       ✔️           |
|     **Fenix Nightly 2/21**     |            **Samsung Galaxy S7**       |      **7**      |         ✔️           |
|      **Fenix Nightly 2/21**          |     **OnePlus A3**        |        **6**    |         ❌         |
|    **Fenix Nightly 2/21**            |      **Nexus 4**       |        **5**    |        ❌         |
|          |       |            |              |
|  **Fennec RC**          |   **Google Pixel 3a XL**  |    **10**        |       ✔️           |
|   **Fennec RC**          |        **Samsung Galaxy S10+**     |       **9**     |       ✔️             | 
|  **Fennec RC**          |       **Samsung Galaxy S8+**      |         **8**   |       ✔️         |
|    **Fennec RC**       |            **Samsung Galaxy S7**       |      **7**      |        ✔️          |
|      **Fennec RC**           |     **OnePlus A3**        |        **6**    |           ❌         |
|   **Fennec RC**            |      **Nexus 4**       |        **5**    |        ❌         |
|          |       |            |              |
|  **R-B latest**          |   **Google Pixel 3a XL**  |    **10**        |       ❌           |
|   **R-B latest**            |        **Samsung Galaxy S10+**     |       **9**     |       ❌             | 
|  **R-B latest**           |       **Samsung Galaxy S8+**      |         **8**   |       ✔️         |
|    **R-B latest**         |            **Samsung Galaxy S7**       |      **7**      |        ✔️          |
|     **R-B latest**             |     **OnePlus A3**        |        **6**    |           ❌         |
|   **R-B latest**             |      **Nexus 4**       |        **5**    |        ❌         |

#### Notes
There is also a Bugzilla bug, added recently regarding this issue, for more details please check it [here](https://bugzilla.mozilla.org/show_bug.cgi?id=1617139).

**Comment by abodea** [comment]
I retested this issue on the latest Nightly from 3/10 for more details please check the following:

| Browser  | Device |  Android version |  Crash? | 
| :-------------:| :-------------: | :-------------: | :-------------: |
|  **Fenix Nightly 3/20**          |   **Google Pixel 4 XL**  |    **10**        |       ❌           |
|    **Fenix Nightly 3/20**         |        **Samsung Galaxy S10+**     |       **10**     |        ❌             | 
|     **Fenix Nightly 3/20**          |       **Huawei Mate 20 Lite**  |         **8.1.0**   |       ✔️           |
|    **Fenix Nightly 3/20**         |        **OnePlus A**     |       **6.0.1**     |        ❌             | 
|    **Fenix Nightly 3/20**         |        **Samsung Galaxy S7**     |       **7**     |        ✔️             | 
|    **Fenix Nightly 3/20**         |        **Google Pixel 3a XL**     |       **9**     |        ❌             | 
|    **Fenix Nightly 3/20**         |        **Nexu 4**     |       **5**     |        ❌             | 

Here you can find the [logcat](https://www.codepile.net/pile/Mzq61QAx).
Removig the `eng:qa:needed` as the issue still occurs.

**Comment by atranel** [comment]
Crashing on my Honor 8x, Android 10 (Firefox Preview 5.2 tested)
