### ISSUE TITLE
Adding history on Back button

### ISSUE THREAD

**Issue by marcinwiacek** [mozilla-mobile/fenix#6744]
### Why/User Benefit/User Problem
Desktop browsers have list of last pages under <- button and sometimes it's very useful (you can return fast to concrete previous page)

### What/Requirements
Adding popup menu displayed after long pressing Back button

### Acceptance Criteria (how do I know when I’m done?)
Menu with last history entries is displayed for page after long pressing Back button

**Comment by ekager** [comment]
Tracked as part of https://github.com/mozilla-mobile/fenix/issues/176
