### ISSUE TITLE
[Bug] Move custom engine is in Address Bar preference category

### ISSUE THREAD

**Issue by mcarare** [mozilla-mobile/fenix#6748]
![new](https://user-images.githubusercontent.com/48995920/69436710-906c9e80-0d4a-11ea-9946-0b96873e448b.png)

**Comment by mcarare** [comment]
For QA: Please test in next Nightly.

**Comment by softvision-miralobontiu** [comment]
Verified as fixed on the latest Nightly build 191202 with Google Pixel3 (Android Q), Huawei MediaPad M2 (Android 5,1,1), and Nexus 5 (Android 6,0,1).

![Screenshot_20191202-120751](https://user-images.githubusercontent.com/40694158/69951423-e6390780-14fd-11ea-8658-014e2de414b1.png)
