### ISSUE TITLE
Integrate Adjust SDK

### ISSUE THREAD

**Issue by colintheshots** [mozilla-mobile/fenix#675]
Integrate Adjust SDK for install referrer performance.

As we're now using Glean for telemetry, we will no longer need Adjust for this purpose. We'll want to integrate Adjust similarly to other products, but possibly using a more recent version. It should be possible to toggle off the Adjust integration by setting a shared preference for whether telemetry is enabled.

**Comment by bbinto** [comment]
@colintheshots we will need Adjust for campaign tracking, please work with Loren to get Adjust API keys etc.

This should actually also land in Milestone 2 as per milestone board.
