### ISSUE TITLE
[Bug] Regression cannot open in app

### ISSUE THREAD

**Issue by andreicristianpetcu** [mozilla-mobile/fenix#6750]
## Steps to reproduce
open https://mobile.twitter.com/bundyo/status/1195722678012911617
or anny web site with a mobile app

### Expected behavior
![Screenshot_20191122-183728_Firefox_Preview](https://user-images.githubusercontent.com/922368/69443584-5d7cd780-0d57-11ea-8ff6-a77ace38eb65.png)
should be able to open tweet in twitter app
### Actual behavior
![Screenshot_20191122-183735_Firefox_Nightly](https://user-images.githubusercontent.com/922368/69443606-71283e00-0d57-11ea-9e51-022f23201faf.png)
no way of openning in twitter app
### Device information

* Android device: 7
* Fenix version: latest nightly

**Comment by rocketsroger** [comment]
This is by design, but more fixes will be coming soon.  I'll self assign this one.

**Comment by andreicristianpetcu** [comment]
I was using this feature with tons of apps. twitter, reddit, maps, mastodon and a few others. Sad I have no way to do that anymore. What issues should I follow on this topic? @rocketsroger

**Comment by andreicristianpetcu** [comment]
when QAB was removed, this feature was moved to 3 dot menu. It was removed recently.

**Comment by rocketsroger** [comment]
The A-C change is now in Fenix nightly.  Please verify this is fixed.  Thanks!

**Comment by andreicristianpetcu** [comment]
fixed
