### ISSUE TITLE
Access top visited sites on homepage

### ISSUE THREAD

**Issue by boek** [mozilla-mobile/fenix#6757]
### User Story
As a user, I want to easily access my top visited sites on my homepage, so I can get to the information I need faster.

### What/Requirements
- [x] Space on the homescreen to display `n` number of top sites
- [x] The ability to open a new tab based on a top site item
- [x] We gracefully handle the case where there are no top sites
- [x] We give users a good first run experience

### Acceptance Criteria (how do I know when I’m done?)
- [x]  I can see my top sites
- [x] I can open a new tab based on a top site
- [x] I can measure how often people use top sites

**Comment by boek** [comment]
Parent: #6190

**Comment by sv-sdeiac** [comment]
Hello, I can confirm that the Top Sites can be accessed from the Homepage using the latest build of Firefox Preview Nightly 1/31 #20310607.

Devices:
- Nokia 6 (Android 7.1.1);
- LG G7 fit (Android 8.1);
- Google Pixel (Android Q).
