### ISSUE TITLE
Add a favorite sites to the homescreen

### ISSUE THREAD

**Issue by boek** [mozilla-mobile/fenix#6758]
### User Story
As a user, I want to be able to explicitly add one of my favorite sites to the homescreen, so I can get to my frequently used sites faster. 

### What/Requirements
- [x] I can add a new website to my top sites

### Acceptance Criteria (how do I know when I’m done?)
- [x] I can successfully add a new top site or know why I am unable to
- [x] I can measure how often people try to add new top sites

---

Estimation may change after we come up with a solution to replacing existing top sites.

**Comment by boek** [comment]
parent: #6190

**Comment by liuche** [comment]
Adding waiting label, as the UX is pretty much done.

**Comment by gabrielluong** [comment]
This is currently blocked by https://github.com/mozilla-mobile/android-components/issues/5315, which will be landing soon. The added top sites storage in AC allows us to add and remove pinned top sites.

**Comment by liuche** [comment]
how's this looking @boek @gabrielluong can we get it landed this week?

**Comment by boek** [comment]
@liuche got the branch all fixed up to land just trying to get CI to pass now 👍

**Comment by liuche** [comment]
oh my god so excited

**Comment by sv-sdeiac** [comment]
Verified as fixed using the latest version of Firefox Preview Nightly 1/28 #20280606.
Devices:
- Nokia 6 (Android 7.1.1);
- OnePlus 5T (Android 9).
