### ISSUE TITLE
Remove a top site

### ISSUE THREAD

**Issue by boek** [mozilla-mobile/fenix#6759]
### User Story
As a user, I would like to be able to remove a top site I no longer want to see, so I can customize my homepage the way it fits my needs. 

### What/Requirements
- [ ] The ability to remove a top site

### Acceptance Criteria (how do I know when I’m done?)
- [ ] When a top site is removed it is not longer shown as a top site
- [ ] We can measure how often top sites have been removed
- [ ] We handle the case where the last top site is removed

**Comment by boek** [comment]
Parent: #6190

**Comment by gabrielluong** [comment]
I am also fixing this in #6758

**Comment by topotropic** [comment]
@gabrielluong can we show an undo snackbar when someone removes a pinned site? Thanks!

**Comment by gabrielluong** [comment]
> @gabrielluong can we show an undo snackbar when someone removes a pinned site? Thanks!

Will file a new issue for this.

**Comment by sv-sdeiac** [comment]
Hello, I can confirm that this issue is fixed using the latest build of Firefox Preview Nightly 1/31 #20310607.

Devices:
- Nokia 6 (Android 7.1.1);
- LG G7 fit (Android 8.1);
- Google Pixel (Android Q).
