### ISSUE TITLE
Show UI test results in taskcluster task

### ISSUE THREAD

**Issue by rpappalax** [mozilla-mobile/fenix#6760]
### Why/User Benefit/User Problem
Currently UI test results are returned from Firebase and only exposed as links at the end of the ui-test job log.  To access these results requires 10-15 clicks and scrolls which is not user-friendly.

### What/Requirements
We have a script that will parse the ui-test job log with a UI test summary report of passes/fails and links out to Firebase to drilldown more easily on failures.

### Acceptance Criteria (how do I know when I’m done?)
UI test reports will be logged in a markdown file and accessible via a taskcluster task (always sorted to top for easy discoverability)

**Comment by owlishDeveloper** [comment]
👾

**Comment by rpappalax** [comment]
update: rather than using MickeyMoz or github actions, @owlishDeveloper will be adding our script directly to taskcluster so we can do same for any of our mobile projects

**Comment by owlishDeveloper** [comment]
https://github.com/taskcluster/taskcluster/pull/2477
