### ISSUE TITLE
Potential origin spoofing because address bar truncates "facebook.com.evil.com" to "facebook.com..." instead of "...evil.com"

### ISSUE THREAD

**Issue by cpeterso** [mozilla-mobile/fenix#6762]
## Steps to reproduce

1. Open http://facebook.com.facebook.com.evil.com/
2. Look at the portion of the URL visible in the address bar.

I originally filed this bug against desktop Firefox. On desktop, Firefox, Chrome, Edge, and Safari all do the wrong thing (show "facebook.com"):

https://bugzilla.mozilla.org/show_bug.cgi?id=1598175

### Expected behavior

The [URL standard says](https://url.spec.whatwg.org/#url-rendering-elision):

> When the full host cannot be rendered, browsers should elide domain labels starting from the lowest-level domain label. For `example, examplecorp.com.evil.com` should be elided as `...com.evil.com`, not examplecorp.com...`.

Fennec and Chrome on Android do the right thing: they show `...ook.com.facebook.com.evil.com` and `facebook.com.evil.com`, respectively.

### Actual behavior

Fenix shows `http://facebook.com.facebook...` without showing `evil.com`.

### Device information

* Android device: Moto G5
* Fenix version: 2.3.0

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-14488)

**Comment by liuche** [comment]
@kglazko is this addressed in the urlbar work you were doing in #7077 ? Or is it a follow-up?

**Comment by kglazko** [comment]
Thank you for filing this! Yes, this is a follow-up to 7077.

**Comment by kglazko** [comment]
We will use this issue to verify in Fenix, but the logic will be landed in AC and then auto-consumed by Fenix since we are already using the displayUrl pref to load shortened urls from AC.

**Comment by Mugurell** [comment]
@kglazko @pocmo Do you have cycles to work on this?
I could also take a look.

**Comment by Mugurell** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1685152 could possibly help with this.

**Comment by Mugurell** [comment]
![image](https://user-images.githubusercontent.com/11428869/104214865-b1a5b800-5440-11eb-9c9b-f085ad267f9e.png)

Opera resolves this interestingly. The domain is shown but the subdomains and pages are elided.

**Comment by fm-sys** [comment]
Sorry, but this issue is a big security bug. Can someone please disable stale bot for this issue?

**Comment by alesandroortiz** [comment]
Still a security issue, per https://bugzilla.mozilla.org/show_bug.cgi?id=1731181

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813212

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
