### ISSUE TITLE
[Bug] Cannot see the text when renaming collection

### ISSUE THREAD

**Issue by clitetailor** [mozilla-mobile/fenix#6769]
## Steps to reproduce

Create a collection and rename it. Collection name cannot be seen as the text color is the same as background color.

### Expected behavior

I'm able to see the text color when renaming collection.

### Actual behavior

![Screenshot_20191123-215307_Firefox Nightly](https://user-images.githubusercontent.com/16368559/69481143-1cf98880-0e41-11ea-975e-90914b272cde.jpg)

### Device information

* Android device: Samsung Galaxy J7 Pro
* Fenix version: Nightly 191123 06:11

**Comment by ebalazs-sv** [comment]
Hi!
This is also reproducible when creating a collection on Fenix Nightly 191127 with Pixel 2 (Android 9).

**Comment by neekless** [comment]
Fixed in nightly 191128

![Screenshot_20191128-222637](https://user-images.githubusercontent.com/22426822/69814009-44f33e00-11eb-11ea-9cd4-f3d46d7288d8.jpg)
![Screenshot_20191128-222651](https://user-images.githubusercontent.com/22426822/69814014-4886c500-11eb-11ea-9e19-aa66226e2e98.jpg)

**Comment by softvision-miralobontiu** [comment]
Verified as fixed on the latest Nightly build 191202 with Google Pixel 2 (Android 9), Google Pixel 3 (Android Q), Nexus 5 (Android 6.0.1), and Huawei MediaPad M2 (Android 5.1.1).
