### ISSUE TITLE
bring back bottom swipe up gesture

### ISSUE THREAD

**Issue by sheikh-azharuddin** [mozilla-mobile/fenix#6774]
Earlier in preview version there was the option to swipe up on webpages and it was displaying some options like bookmark, open in app,read,share...in new nightly preview this is removed...please enable the feature

**Comment by cadeyrn** [comment]
It was intentionally removed. These items are integrated in the main menu now.

**Comment by NotWoods** [comment]
Yup, we removed the bar intentionally. See #4281. Currently there are no plans to bring it back as the functionality has been integrated elsewhere.

**Comment by willfs84** [comment]
They were right to remove it, please read through the below issue for why there cannot be a swipe-up gesture https://github.com/mozilla-mobile/fenix/issues/1021
