### ISSUE TITLE
please support scaling websites

### ISSUE THREAD

**Issue by djdisodo** [mozilla-mobile/fenix#6777]
### What/Requirements
support scaling websites like pc browsers
(Ctrl+mouse wheel)

### Acceptance Criteria (how do I know when I’m done?)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-14497)

**Comment by NotWoods** [comment]
Could you elaborate on what you're looking for? Do you want Ctrl+mouse wheel to work in the mobile browser? We already support scaling websites via pinch-to-zoom, or double-tap and drag.

**Comment by djdisodo** [comment]
Scaling in pc
100%:
![Screenshot_2019-11-24_16-30-31](https://user-images.githubusercontent.com/17721656/69550479-692dff80-0fde-11ea-8624-05beaa01a563.png)

110%:
![Screenshot_2019-11-25_23-49-47](https://user-images.githubusercontent.com/17721656/69550510-764aee80-0fde-11ea-969f-043fbed9ecb9.png)

Scaling in mobile
100%:
![Screenshot_20191125-235006_Firefox_Nightly](https://user-images.githubusercontent.com/17721656/69550580-94185380-0fde-11ea-9cf9-bcf0d1b031a3.png)

pinched:
![Screenshot_20191125-235011_Firefox_Nightly](https://user-images.githubusercontent.com/17721656/69550601-a09cac00-0fde-11ea-8d6c-1b1a72de9ff0.png)
(some of page is being cropped out)

and there is no way to make websites smaller in mobile

**Comment by djdisodo** [comment]
i mean..
zoom in mobile is not the same with pc's Ctrl + wheel
scale is bonded with mobile / desktop site state
desktop mode's scale is not small enough for some sites

adding a option to scale will solve that
(i just wanna use vscode codeserver on my phone :))

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813211

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
