### ISSUE TITLE
Hide session while in private mode

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#678]
Currently the text of a session is hard to read in the darker mode of private browsing.
<img width=300 src=https://user-images.githubusercontent.com/4400286/53428398-97bf7100-399f-11e9-8ad9-c87cfa36e701.jpg>

**Comment by boek** [comment]
:+1: beat me to it!

**Comment by bsurd** [comment]
Sessions are no longer displayed in Private Mode.

Verified on:
 - 1.0.1910 (Build #10642115)

 Devices:
 - Nokia 6 (Android 7.1.1)
 - HTC Desire 820 (Android 6.0.1)
