### ISSUE TITLE
[Bug]The camera can't be accessed by the Firefox app on a fresh install

### ISSUE THREAD

**Issue by sv-sdeiac** [mozilla-mobile/fenix#6787]
## Prerequisites
You need to have a fresh install of the FF app.

## Steps to reproduce
1. Go to talky.io;
2. Create a new room;
3. Try to share the camera.

### Expected behavior
The user can share the camera.

### Actual behavior
The user can't share the camera.

### Device information

* Android device: Nokia 6 (Android 7.1.1), Samsung Galaxy Note 8 (Android 9), Google Pixel (Android Q).
* Fenix version: Nightly 11/25 #13290608;

### Notes
- This issue can be fixed if we enable the Camera permission from the Android settings and refreshing the site;
- This issue can be reproduced also on the RC build of Firefox Preview 2.3.0 and Nightly Firefox for Android 68.3a1 (2019-11-22) and Firefox for Android RC 68.2.1;
![Screenshot_20191125-171500](https://user-images.githubusercontent.com/40264165/69553787-5fd67000-0fa9-11ea-8456-741fc53b2860.png)

**Comment by kbrosnan** [comment]
This looks like a website bug. If I use https://mozilla.github.io/webrtc-landing/pc_test.html I can request camera access.

**Comment by sv-sdeiac** [comment]
Hello, I don't think this is a website issue because I can reproduce the problem also with the whereby.com website. 
In my opinion, is that the app doesn't know to trigger the camera permission for some kind of pages.

**Comment by vesta0** [comment]
@fluffyemily does this seem like a GeckoView bug?

**Comment by Amejia481** [comment]
I was able to reproduce the issue on a fresh installation of Fenix nightly and also on the GeckoView example app.

```
Nightly 200107 06:01 (Build #20070607)
27.0.0, 707874f68
GV: 73.0a1-20200106092427
Tuesday 1/7 @ 6:06 AM
```

**Comment by mcarare** [comment]
I can reproduce this on any browser with GV ("_no camera detected_" message), and it works fine for any browser with webview. IMO it is a bug in GV.

**Comment by darkwing** [comment]
Has this been opened on GV?  What's our process for passing this on and tracking progress?

**Comment by vesta0** [comment]
Added this to the GV board for triage

**Comment by boek** [comment]
GV bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1610939

**Comment by darkwing** [comment]
I pinged GV in the Bugzilla issue.  Hopefully hear back on progress today.

**Comment by sv-sdeiac** [comment]
Hi, this issue is fixed on the latest version of Firefox Preview Nightly 4/9 #21000923.

Devices:
- Google Pixel 3 (Android 10);
- Samsung Galaxy Note 8 (Android 9).
