### ISSUE TITLE
[Bug] Page title when audio active not refreshed to system

### ISSUE THREAD

**Issue by vandys** [mozilla-mobile/fenix#6789]
## Steps to reproduce

Start playing a track, player sets the page title to the track name
Switch out to, say, lock screen.  Notice that the page title is displayed along with the active audio.
Audio ends, player selects new track and starts, page title is updated.
Tab list will show updated page title; lock screen still shows old title.

### Expected behavior

The system displayed title (in status bar pulldown, lock screen, etc.) should track the
page title, even if it changes.

### Actual behavior

Currently, it appears to update only if a completely
idle audio element is started.

### Device information

* Android device: Nextbit Robin, LineageOS Pie
* Fenix version: 2.3.0 (Build #13031728)

**Comment by ekager** [comment]
Which website playing media are you reporting about? I attempted to reproduce with iheart.com in our latest build and the title updated to the currently playing track in the tabs tray.

**Comment by vandys** [comment]
When the problem presents, it's what you would see on the LOCK screen; the tab display was always correct.

That said, on 4.2 preview I can't reproduce it.  I'll revisit this if I come across a way to tickle it.
Sorry!

**Comment by ekager** [comment]
No worries, if you see it again, feel free to reopen with the site it's happening on. Thanks!

**Comment by vandys** [comment]
Hi!  I came across a way which hopefully can let you see it.  I have a player at:

  http://vsta.org:8110

So click down to the mp3 folder (don't worry, it's my wife's music, no piracy) and play a track.
Look at your tab display and page title.  Now turn off your screen, then turn it back on to see
the lock screen.  It's not showing the title.  Back to page, click next track, then >next, and
still not seeing track label updates.

I'm hoping this is something you can see too?

**Comment by ekager** [comment]
Thank you for a site to test on/STR! 

On my Pixel 3 running Q I was not able to reproduce :/ I believe you that it happens though - so maybe it's device/SDK dependent.

I followed the STR and my lock screen is showing the title on the first song, and then when I play the next track, it reflects the second song correctly.
![Screenshot_20200413-102654](https://user-images.githubusercontent.com/25442310/79143155-93a40d80-7d71-11ea-82e4-e9857dda493b.png)
![Screenshot_20200413-102627](https://user-images.githubusercontent.com/25442310/79143159-94d53a80-7d71-11ea-9385-d2974505c2c8.png)

**Comment by vandys** [comment]
Thanks for checking!  Ok, I'm going to call it maybe a LineageOS issue, possibly even a race.
