### ISSUE TITLE
Match download behavior of Fennec when force quitting

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#6790]
When a user force quits Fenenc, the download notification sticks around. We should consider matching this behavior in Fenix. 

@vesta0 to decide if this is important for Fenix download management.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-14504)

**Comment by s-ankur** [comment]
Related https://github.com/mozilla-mobile/fenix/issues/11190

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812814

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
