### ISSUE TITLE
Detailed Testing of Private Mode

### ISSUE THREAD

**Issue by athomasmoz** [mozilla-mobile/fenix#6792]
Review the feature from the perspective of the user and log anything that feels off
* Confirmed happy path & error states
* Test in both portrait and landscape
* Tickets logged for any bugs & polish issues
  * Does anything feel jarring?
  * Tag with Feature:PrivateMode and add to Feature Polish board

Everyone to go through
- [x] Severin
- [ ] Jeff
- [x] Mihai

**Comment by Baron-Severin** [comment]
Opened https://github.com/mozilla-mobile/fenix/issues/6801 as a meta of polish issues found.
