### ISSUE TITLE
Detailed Testing for Search Feature

### ISSUE THREAD

**Issue by athomasmoz** [mozilla-mobile/fenix#6793]
Review the feature from the perspective of the user and log anything that feels off
* Confirmed happy path & error states
* Test in both portrait and landscape
* Tickets logged for any bugs & polish issues
  * Does anything feel jarring?
  * Tag with Feature:Search and add to Feature Polish board

Everyone to go through
- [x] Severin
- [x] Jeff
- [x] Mihai

**Comment by cadeyrn** [comment]
Related: #6709 and #6710.
