### ISSUE TITLE
[Bug] Add back "force expand" to dynamic top toolbar

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#6795]
Because we're now allowing a [dynamic top toolbar](https://github.com/mozilla-mobile/fenix/issues/5694) again, we should add functionality to `forceExpand` the toolbar when the page is loading to prevent security vulnerabilities. 

The reason this is not currently supported is because we're using an `AppBarLayout` instead of a `CoordinatorLayout` (as using `CoordinatorLayout` had issues when switching between bottom, top fixed, and top dynamic I discussed with @pocmo).  

We should create a `TopBrowserToolbarBehavior` (similar to [this](https://github.com/mozilla-mobile/fenix/blob/master/app/src/main/java/org/mozilla/fenix/browser/BrowserToolbarBottomBehavior.kt)) and add its [`forceExpand` function](https://github.com/mozilla-mobile/fenix/blob/master/app/src/main/java/org/mozilla/fenix/browser/BrowserToolbarBottomBehavior.kt#L46-L50)

**Comment by sblatz** [comment]
Note: I started on this, but will not be able to finish it before going on PTO. Please take a look at my draft PR (which currently has bugs) for a good starting point: https://github.com/mozilla-mobile/fenix/pull/6816

**Comment by liuche** [comment]
If we don't get this done by the end of this sprint (12/6) we should feature-flag the dynamic toolbar.

**Comment by AndiAJ** [comment]
Hi, I've just tested this issue on the latest **Nightly Build #13470611 from 12/13** using the following devices:
• Google Pixel 3a (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• OnePlus (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

❌ It seems that the URL Bar doesn't get displayed after tapping a redirect link.

#### STR :
1. Navigate to https://www.cnet.com/news/xbox-one-s-all-digital-edition-vs-xbox-one-x/
2. Swipe down the page until you reach the "See Xbox One X on Amazon" button ([actually a redirect link ](https://assoc-redirect.amazon.com/g/r/https://www.amazon.com/s/ref=as_li_ss_tl?k=xbox+one+x&ref=nb_sb_noss_1&linkCode=ll2&tag=cnet-buy-button-20&linkId=fe06d7c7a278bcf94a2eb4c46d01b932&ascsubtag=ag%3Ab2988900-4766-402a-b92c-77d76601ca0a%7Cvg%3A7c4385e0-1e48-11ea-9ce8-53d27c8ec2eb%7Cst%3Amwb))
3. User is redirected to Amazon

► Video
![20191214_100510](https://user-images.githubusercontent.com/51314259/70785019-9b877d00-1d92-11ea-9931-41c9a4e39ab8.gif)

@sblatz  - Please review and advise . :relaxed:
I'll remove the QA needed label until further notice.

**Comment by Baron-Severin** [comment]
Closed by https://github.com/mozilla-mobile/fenix/pull/6955

**Comment by Baron-Severin** [comment]
@AndiAJ the previous solution didn't work when a link opened a new tab.  We just merged a fix for that, would you mind retesting?

**Comment by sv-sdeiac** [comment]
Hello, I can confirm that this issue is fixed using the RC version 3.0.1 #13502255 12/16.

Devices:
- Nexus 5	(Android 6.0.1);
- Nexus 9	(Android 7.1.1);
- Xiaomi Mi 8 Lite (Android 9);
- Google Pixel (Android Q).
