### ISSUE TITLE
[Bug] Tabs briefly have incorrect colors while switching browsing mode

### ISSUE THREAD

**Issue by Baron-Severin** [mozilla-mobile/fenix#6796]
## Steps to reproduce
- Open several tabs in normal mode
- Open no tabs in private mode
- Change from normal mode to private mode

### Expected behavior
- Tabs should (somehow) disappear
- Colors should change

### Actual behavior
- Tabs change to the color of the new mode
- Tabs then fade out

15% speed video
![wrong-color-tabs](https://user-images.githubusercontent.com/13170306/69589196-28af9100-0fa0-11ea-9276-32ee0c430d4a.gif)

**Comment by ekager** [comment]
Closing because of tabs tray work
