### ISSUE TITLE
[Bug] Home title text overlaps during normal/private transition

### ISSUE THREAD

**Issue by severinrudie** [mozilla-mobile/fenix#6797]
## Steps to reproduce
- Have the same number (0 or more) of normal tabs as private tabs
- Switch between normal and private mode

### Expected behavior
- Previous title text ("Open tabs” or “Private session) fades out
- New title text fades in

### Actual behavior
- Previous and new title text fade simultaneously, and overlap

<img width="366" alt="overlapping-text" src="https://user-images.githubusercontent.com/13170306/69589286-775d2b00-0fa0-11ea-8630-42367047e228.png">
15% speed video

![n0-to-p0](https://user-images.githubusercontent.com/13170306/69589303-893ece00-0fa0-11ea-8e3c-a37d79669d02.gif)

**Comment by Baron-Severin** [comment]
We could quickly fix this by speeding up both the fade out and fade in of the title text, and making sure the previous value is completely gone before fading in the new one.
