### ISSUE TITLE
[Bug] "No open tabs”/private mode explanation is briefly shown when tabs exist

### ISSUE THREAD

**Issue by Baron-Severin** [mozilla-mobile/fenix#6798]
## Steps to reproduce
- Have 0 normal tabs
- Have 1+ private tabs
- Transition from normal mode to private mode

### Expected behavior
- Private mode should never show "no private tabs" text

### Actual behavior
- Private mode briefly flashes "no private tabs" text before updating
(note that this is also reproducible on reverse, with 0 private tabs and 1+ normal tabs)

15% speed video

![n0-to-p5](https://user-images.githubusercontent.com/13170306/69589722-df604100-0fa1-11ea-997f-cbdee4f6bae9.gif)

**Comment by NotWoods** [comment]
We probably need some "loading" flag to disable animations while the tab list is getting loaded in.

**Comment by Baron-Severin** [comment]
I believe if we refactored the home screen state to look something like below, then we might be able to fix this bug, #6796, and possibly some other display flicker at the same time.

```kotlin
HomeState(
  ...
  val normalTabs: List<Tab>,
  val privateTabs: List<Tab>,
  val displayedMode: DisplayMode
)

enum class DisplayMode { NORMAL, PRIVATE, TRANSITIONING }
```

**Comment by NotWoods** [comment]
There's also the state between opening the app and the tabs being loaded. I think a new 'transitioning' Boolean separate from the displayed mode would be better.

**Comment by darkwing** [comment]
I couldn't reproduce this on current master.

**Comment by lime124** [comment]
fixed according to @boek
