### ISSUE TITLE
Browser crashes on *any* page load

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#680]
Currently trying to load any page fails and just leads to a white page followed by a crash.

**Comment by sblatz** [comment]
Reverting https://github.com/mozilla-mobile/fenix/commit/49d527d0dd63d04370cef9adb73bd1510a222979 fixes this.

**Comment by sblatz** [comment]
Closed by https://github.com/mozilla-mobile/fenix/commit/4aa2030ab1f6c0a2d769addfa5b3e55f24ad9046

**Comment by bsurd** [comment]
Navigated to several different sites, all of them loaded without any kind of issues and there were no crashes. 

Verified on:
 - 1.0.1910 (Build #10642115)

 Devices:
 - Nokia 6 (Android 7.1.1)
 - HTC Desire 820 (Android 6.0.1)
