### ISSUE TITLE
[Bug] normal->private and private->normal transition animations don't feel consistent

### ISSUE THREAD

**Issue by Baron-Severin** [mozilla-mobile/fenix#6800]
- During normal to private mode transitions, tabs fade out and then back in.  
- During private to normal mode transitions, tabs fade out, collections translate down, and then tabs fade in.

As a user, this feels inconsistent to me (before speeding the video down, I actually thought tabs unrolled out when transitioning to normal mode).

15% speed video of normal tab entrance

![n5-to-p0](https://user-images.githubusercontent.com/13170306/69590190-7c6fa980-0fa3-11ea-9917-34f99d1e200d.gif)

15% speed video of private tab entrance

![n0-to-p5](https://user-images.githubusercontent.com/13170306/69590192-7f6a9a00-0fa3-11ea-9a81-2edfc4c5324b.gif)

**Comment by sblatz** [comment]
We're currently just using the default animations here, so Android is trying to be "smart" about how to transition. I think changing this would require re-working the animations with custom behavior. Aren't we planning a redesign for this screen soonish with the tab redesign? Wonder if this should wait on that.

**Comment by Baron-Severin** [comment]
> We're currently just using the default animations here, so Android is trying to be "smart" about how to transition. I think changing this would require re-working the animations with custom behavior. Aren't we planning a redesign for this screen soonish with the tab redesign? Wonder if this should wait on that.

I wasn't aware of the tab tray move when I wrote this issue 🤷‍♂ .  We'll still need to take a careful look at its animations, but yes, [this whole meta](https://github.com/mozilla-mobile/fenix/issues/6801) is blocked on #1063 and #6651.

**Comment by sblatz** [comment]
I'm not seeing this on my device anymore. @Baron-Severin do you still see this?

**Comment by Baron-Severin** [comment]
Nope, this looks fixed to me.  Thanks!
