### ISSUE TITLE
[Bug] Top toolbar - reload icon & 3 dot menu displaced

### ISSUE THREAD

**Issue by Cheap-Skate** [mozilla-mobile/fenix#6809]
In today's Nightly
Select Top Toolbar
Tap the 3 dot menu
The 3 dot menu is displaced down and left from the top corner of the screen
This means the "reload" icon is not on top of the 3-dot menu icon making it very difficult to reload the page with a tap-tap
See also #6291

Galaxy S7
Today's Fenix Nightly

**Comment by ekager** [comment]
Closing for #6291
