### ISSUE TITLE
Option to hide Android status bar in landscape mode

### ISSUE THREAD

**Issue by lightfire-nyan** [mozilla-mobile/fenix#6814]
In Android browsers such as the Samsung Browser the top status bar (that shows system notifications) is hidden in landscape mode, allowing much more space to view content while browsing. This is a good feature for all mobile browsers and would be great to see an option on Firefox to support this.

Firefox should allow an option to hide it in landscape mode only, as in portrait mode the status bar does not take up as much space. An additional option could be to allow the status bar to stay locked in the portait mode orientation even when rotating rest of the browser screen, for this same reason, if feasible in Android's API.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-14525)

**Comment by artchizhov** [comment]
This is need feature.

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813209

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
