### ISSUE TITLE
[Bug] Custom tabs crash

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#6821]
## Steps to reproduce
Try using a custom tab

### Expected behavior
They work

### Actual behavior
They crash

This is due to us casting toolbar to `coordinatorlayout` instead of `appbarlayout`.

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **Nightly Build #13310607 from 11/27** using the following devices:
• Google Pixel 3a XL (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

► Video Toolbar set to **Bottom
![20191127_111454](https://user-images.githubusercontent.com/51314259/69711777-544e8a80-110a-11ea-9b09-c7dffcf6bd1e.gif)
**

► Video Toolbar set to **Top**
![20191127_111841](https://user-images.githubusercontent.com/51314259/69712134-fc645380-110a-11ea-9383-ff032a1dddce.gif)
