### ISSUE TITLE
[Bug] no error message when adding a search engine with invalid URL

### ISSUE THREAD

**Issue by cadeyrn** [mozilla-mobile/fenix#6823]
### Steps to reproduce

Add a custom search engine with an not existing URL.

### Expected behavior

There is an error message.

### Actual behavior

Nothing happens, no error message, no user feedback at all. In Firefox Focus there is an error message.

![screen](https://user-images.githubusercontent.com/1100614/69665881-8bca2200-108b-11ea-8176-91088f5d6edc.png)

### Device information

* Android device: OnePlus 7T Pro McLaren Edition / Android 10
* Fenix version: master branch revision 33b49ff7fd8a5e4ac42feaef2afa6f7acaded887

**Comment by mcarare** [comment]
Waiting on #7149 landing to retest the issue.

**Comment by mcarare** [comment]
This should also be fixed with https://github.com/mozilla-mobile/fenix/pull/7149.

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **Nightly Build #13500610 from 12/16** using the following devices:
• Google Pixel 3a (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• OnePlus (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

► Screenshot
![rsz_screenshot_20191216-112733](https://user-images.githubusercontent.com/51314259/70895373-7cd5f000-1ff7-11ea-8cea-749d7028be71.png)

► Video
![20191216_112629](https://user-images.githubusercontent.com/51314259/70895420-98d99180-1ff7-11ea-94ee-83d691492e2b.gif)
