### ISSUE TITLE
[Bug] (regression) "Open in Firefox Preview" has a too small font size

### ISSUE THREAD

**Issue by cadeyrn** [mozilla-mobile/fenix#6830]
### Steps to reproduce

1. make Firefox Preview your default browser
2. open a link in an external app with custom tab support
3. press the "three dots" button

### Expected behavior

"Open in Firefox Preview" has the same font size as all other menu items.

### Actual behavior

Font size is too small in Fenix Nightly. In Fenix 2.3.0 it has the correct font size.

![screen](https://user-images.githubusercontent.com/1100614/69710299-7262bd80-10ff-11ea-8bbd-d03ca3ffbedc.png)

### Device information

* Android device: OnePlus 7T Pro McLaren Edition / Android 10
* Fenix version: master branch revision 5f7b3bd4d71dd8ad597b2401eb4a1a3131d766de

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **Nightly Build #13470611 from 12/13** using the following devices:
• Google Pixel 3a (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• OnePlus (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

► Video
![20191214_094120](https://user-images.githubusercontent.com/51314259/70782067-02a33280-1d8f-11ea-98ca-91d1290cfa16.gif)

**Comment by sv-sdeiac** [comment]
Hello, I can confirm that this issue is not reproducible on the latest RC build 3.0.1 #13502255 12/16.

Devices:
- Motorola Moto G6 (Android 8);
- Xiaomi Mi 8 Lite (Android 9);
- Google Pixel (Android Q).
