### ISSUE TITLE
[Bug] Crash when accessing Settings-Passwords-Saved logins

### ISSUE THREAD

**Issue by softvision-miralobontiu** [mozilla-mobile/fenix#6831]
## Steps to reproduce
1. Sign in with valid credentials.
2. Go to Settings -> Passwords -> Saved logins and tap on it.

### Expected behavior
The Saved logins page is displayed.

### Actual behavior
Nightly crashes.

### Device information
* Android device: Samsung Galaxy Note 8 (Android 9), and HTC Desire 820 (Android 6.0.1)
* Fenix version: 11/27 build (#13310607 and #13310606)

[logcat.txt](https://github.com/mozilla-mobile/fenix/files/3896277/logcat.txt)

**Comment by daniluk4000** [comment]
Same

**Comment by softvision-miralobontiu** [comment]
This is a dupe of #6628.
