### ISSUE TITLE
[Telemetry] About Firefox Preview

### ISSUE THREAD

**Issue by ValentinTimisica** [mozilla-mobile/fenix#6834]
#### Description & Product Manager / Data Scientist User Story
- As a product owner, I want to know if users go to the About page. 

#### What questions will you answer with this data?
- How often users go to the About page. 

#### What probes (suggested, if applicable)
- User opening the "About Page"

### Acceptance Criteria (Added by PM)
- Event pings can be queried via re:dash
- We are sending telemetry events for the actions listed in the requirements
- We have documented the telemetry
- We have asked a data steward to [review](https://github.com/mozilla/data-review/blob/master/request.md) the telemetry
- NOT an AC: Data science to create dashboard or further graphs (this will be a separate issue, this issue is only about hooking up the events described and that they can be queried in re-dash)

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly Build #20350605 from 2/4`** using a Google Pixel 3 XL (Android 9)

✔️ What's new in Firefox Nightly - Ping **dafa5981-b493-4728-884c-3387ff1c52e8**
✔️ Support - Ping **a4ca7ca0-f6b2-4c53-b5e9-265b3e91b968**
✔️ Privacy notice - Ping **d5da9eed-b0b6-4a05-906c-1c48ccb3fb47**
✔️ Know your rights - Ping **9d43f269-68bc-4fa4-bd9f-e1318cf78323**
✔️ Licensing information - Ping **f1e803b2-b31c-4987-acae-8c593b619194**
✔️ Libraries that we use - Ping **1968f95f-f2ad-4f05-8ebb-aaa10503e46b**

[Logcat](https://github.com/mozilla-mobile/fenix/files/4153216/about.txt)
[Glean dashboard](https://debug-ping-preview.firebaseapp.com/pings/ajtest0402000)
