### ISSUE TITLE
[Bug] Home and site toolbar are slightly misaligned

### ISSUE THREAD

**Issue by topotropic** [mozilla-mobile/fenix#6835]
## Steps to reproduce
Home and site toolbar are slightly misaligned – see image.
![misaligned-toolbars](https://user-images.githubusercontent.com/353960/69725360-4571d300-111e-11ea-8700-7d3793455c07.png)

### Expected behavior
Please find the relevant specs here:
- Site toolbar: https://share.goabstract.com/96720d2e-3daa-432f-ad8a-7f69a3aa16e0?mode=design&sha=3c5aec179c0415867549531cdf4d1e712f3d2111
- Home toolbar: https://share.goabstract.com/a5d9621b-02f7-4630-8606-f277664a7688?mode=design&sha=3c5aec179c0415867549531cdf4d1e712f3d2111

### Actual behavior
See above image, app menu, tab action and awesome bar are slightly misaligned

**Comment by cadeyrn** [comment]
see also #6260 and #6410.

**Comment by sv-sdeiac** [comment]
Verified as fixed using the latest version of Firefox Preview Nightly 12/2 (build #13361807).
Devices:
- Nokia 6 (Android 7.1.1);
- Motorola Moto G6 (Android 8.0);
- Samsung Galaxy S8 (Android 9);
- Samsung Galaxy Note 8 (Android 9).
