### ISSUE TITLE
Fenix inserting text unexpectly into text input

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla-mobile/fenix#6839]
## Steps to reproduce

1. Install Fenix on a fresh Samsung Galaxy S5 phone
2. Go to any web form on Fenix, like FxA sign in
3. Type an email address

### Expected behavior
* Email address can be typed

### Actual behavior
* On the second character after the @ symbol, the previously entered characters are pasted. This is strange because this is a fairly fresh Android install and the keyboard preferences were reset.
<img width="251" alt="image" src="https://user-images.githubusercontent.com/68213/69739099-1c911400-1105-11ea-9884-a7396c4db193.png">

I could reproduce this on other websites, but not in the other Samsung "Internet" browser.

### Device information

* Android device: Samsung Galaxy S3
* Fenix version: Latest

**Comment by makotokato** [comment]
@ryanfeeley what keyboad/IME do you use?
