### ISSUE TITLE
Clipboard quick actions don't appear when long pressing nav bar from tab overview

### ISSUE THREAD

**Issue by tom-james-watson** [mozilla-mobile/fenix#6846]
Long pressing the navbar with a tab open brings up the clipboard quick actions implemented in https://github.com/mozilla-mobile/fenix/issues/4155.

However, if you long press the navbar whilst on the tab overview page, nothing happens. Once you let go, it treats it as a click and takes you to the search view.

Long pressing the navbar from the tab overview page should work in the same was as it does from a regular tab. A normal quick should still take you to the search view.

**Comment by sblatz** [comment]
This is expected behavior as it currently stands and sounds more like a feature request. 

@topotropic I believe you're the one that worked with me on the "quick actions." Do you think this behavior makes sense?

**Comment by topotropic** [comment]
Would make sense to offer "Paste" and "Paste & Go" on home if something's in the clipboard;

**Comment by eye942** [comment]
Hi, I'd like to help with this issue.
Just to rehash, I think the issue is that we want to add quick actions to the toolbar in home_fragment

**Comment by eye942** [comment]
I've implemented the paste&go functionality.
As an aside, is there some place that has clearer instructions about testing?
Currently, I'm failing ~86% of the unit tests in the pre-push hook.

Doing the paste functionality will need a bit of work because 
there should be a new nav, either
* home_fragment->browser_fragment
* home_fragment -> search_fragment

**Comment by liuche** [comment]
It looks like there has already been a PR open for this for a while #9573

**Comment by AndiAJ** [comment]
Hi @ekager , I've just checked this matter on the latest **`Nightly Build 200729 from 7/29`** using the following devices:
• Google Pixel 4XL (Android 11)
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• HTC 10 (Android 8)
• Sony Xperia Z5 Premium (Android 7.1.1)
• OnePlus A3 (Android 6.0.1)
• HTC Desire 820 (Android 6.0.1)
• Samsung Galaxy Tab A6 (Android 5.1.1)
• Xiaomi Mi4i (Android 5.0.2)

| Status | Device | Clipboard quick actions  |
| ------------- | ------------- | ------------- |
| ✔️  | Google Pixel 4XL (Android 11) | **Paste** and **Paste & Go** |
| ✔️  | Google Pixel 3a (Android 10) | **Paste** and **Paste & Go** |
| ✔️  | Huawei Mate 20 Lite (Android 9) | **Paste** and **Paste & Go** |
| ❓ | HTC 10 (Android 8) | **Paste** and **Paste as Plain Text** |
| ❓ | Sony Xperia Z5 Premium (Android 7.1.1)  | Only the **Paste** option is displayed |
| ❓ | Samsung Galaxy Tab A6 (Android 5.1.1)  | Only the **Paste** option is displayed |
| ❓ | Xiaomi Mi4i (Android 5.0.2) | Only the **Paste** option is displayed |
| ❌ | OnePlus A3 (Android 6.0.1) | Nothing gets displayed |
| ❌ | HTC Desire 820 (Android 6.0.1) | Nothing gets displayed |

Not sure why clipboard quick actions don't appear on the Android 6 devices.
Should  **Paste** and **Paste & Go** be displayed in all cases? or is something Android specific?

Please review and share your thoughts. ☺️

**Comment by ekager** [comment]
@AndiAJ I noticed another bug where an empty popup menu could appear on home so I just fixed that. I'm a bit confused how you're getting options like "Paste as Plain Text" 🤔 You're long pressing on the toolbar view on the homescreen and seeing that?

**Comment by AndiAJ** [comment]
Hey @ekager , yes, long tap on the homescreen toolbar view.
Re-checked again on the latest **`Nightly 200804`** 

| Status | Device | Clipboard quick actions  |
| ------------- | ------------- | ------------- |
| ✔️  | Google Pixel 4XL (Android 11) | **Paste** and **Paste & Go** |
| ✔️  | Google Pixel 3a (Android 10) | **Paste** and **Paste & Go** |
| ✔️  | Huawei Mate 20 Lite (Android 9) | **Paste** and **Paste & Go** |
| ✔️ | Samsung Galaxy Tab S6 (Android 9) | **Paste** and **Paste & Go**  |
| ✔️ | HTC 10 (Android 8) | **Paste** and **Paste & Go** |
| ✔️ | Sony Xperia Z5 Premium (Android 7.1.1)  | **Paste** and **Paste & Go** |
| ❌ | OnePlus A3 (Android 6.0.1) | **Nothing gets displayed** |
| ❌ | HTC Desire 820 (Android 6.0.1) | **Nothing gets displayed** |
| ❌ | Xiaomi Mi4i (Android 5.0.2) | **Nothing gets displayed**  |
| ❌ | Samsung Galaxy Tab A6 (Android 5.1.1)  | **Nothing gets displayed**  |

It looks like the Clipboard quick actions aren't displayed Android 6 & 5 devices. 
Please review and advise.

**Comment by AndiAJ** [comment]
Hey @ekager I've opened #13794 to follow up the remaining Android 5 & 6 issues.
