### ISSUE TITLE
[Bug] Selected search engine changes place when undo-ing a search engine deletion

### ISSUE THREAD

**Issue by softvision-miralobontiu** [mozilla-mobile/fenix#6847]
## Steps to reproduce
1. Go to Settings - Search and select a randomly chosen search engine.
2. Delete a non-selected search engine from the three-dot menu next to it.
3. Tap on "Undo" from the snackbar and observe your selected search engine.

### Expected behavior
Your selected search engine is not affected.

### Actual behavior
Your selected search engine jumps on top of the search engine list. Tapping back, then returning to the search list, your selected search engine moves back to its original place.

### Device information
* Android device: Samsung Galaxy Tab S3 (Android 8), Google Pixel (Android Q)
* Fenix version: 11/27 (#13310607)

![20191128_Trim](https://user-images.githubusercontent.com/40694158/69795156-511fd100-11d4-11ea-885f-50143ee68e24.gif)

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **Nightly Build #13440604 from 12/10** using the following devices:
• Google Pixel 3a XL (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

►Video
![20191210_105736](https://user-images.githubusercontent.com/51314259/70514598-a3e67a80-1b3c-11ea-86f3-58ef6a429872.gif)
