### ISSUE TITLE
[Bug] The newly added search engine is not arranged alphabetically

### ISSUE THREAD

**Issue by softvision-miralobontiu** [mozilla-mobile/fenix#6848]
## Steps to reproduce
1. Go to Settings - Search - Add search engine - Custom.
2. Manually introduced imgur as a search engine.
3. Observe where imgur search engine is displayed.

### Expected behavior
the "imgur" search engine is displayed alphabetically.

### Actual behavior
The "imgur" search engine is displayed at the end of the list. Reproducible with all new custom search engines added.

### Device information
* Android device: Google Pixel (Android Q), Samsung Galaxy Tab S3 (Android 8)
* Fenix version: 11/27 (#13310607)

![Screenshot_20191128-115157](https://user-images.githubusercontent.com/40694158/69796139-2767a980-11d6-11ea-86db-4f96d9c222d4.png)

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **Nightly Build #13440604 from 12/10** using the following devices:
• Google Pixel 3a XL (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

►Video
![20191210_110900](https://user-images.githubusercontent.com/51314259/70515805-9f22c600-1b3e-11ea-9344-ba4d35fa76b9.gif)
