### ISSUE TITLE
[Bug] After deleting the selected search engine, the next one selected is chosen randomly

### ISSUE THREAD

**Issue by softvision-miralobontiu** [mozilla-mobile/fenix#6849]
## Steps to reproduce
1. Go to Settings - Search and delete the selected search engine.
2. Observe the next search engine that is automatically selected.

### Expected behavior
The next search engine under the one deleted is automatically selected - as in the https://miro.com/app/board/o9J_kwAuqu4=/
![Screenshot_1](https://user-images.githubusercontent.com/40694158/69797856-19ffee80-11d9-11ea-8d27-01e228b1c6ba.png)

### Actual behavior
The search engine selected skips the next search engine and selects randomly.

### Device information
* Android device: Google Pixel (Android Q), Samsung Galaxy Tab S3 (Android 8)
* Fenix version: 11/27 (#13310607)

![20191128_Trim](https://user-images.githubusercontent.com/40694158/69797972-41ef5200-11d9-11ea-8915-9b2c7f5c567f.gif)

### Design Work
- [x] Request for Comments from UX team
- [ ] ~Usability testing if a new pattern or potentially confusing UI~ Not required, this is a minor behaviour change
- [ ] ~Request for Comments from Fenix team and/or A/C, GV, Sync, etc as needed~ The behaviour change came from Fenix Engineering, UX is confirming it
- [x] Interaction details included
- [x] Accessibility ~- is this a review by someone,~ just keeping it in mind?
- [ ] ~For existing UI changes, deltas are highlighted~ No UI change, this is behaviour-only
- [ ] ~Strings/content reviewed and approved~ No new string
    - [ ] ~Are they too long for the component in other locales~

### Deliverable
- [ ] ~Assets uploaded to Google Drive~
- [ ] ~Links to deliverables (spec, assets) posted in comment 0~
- [x] Behaviour

### Deliverable Links
- [ ] ~User flow: (link to e.g. Abstract artboard, LucidChart, Whimsical, Miro, etc.)~
- [ ] ~Spec: (link to e.g. Abstract artboards)~
- [ ] ~Assets: (link to Google Drive folder)~

### Behaviour

After a search engine is deleted from the list, the search engine listed on the very top of the list should be selected next.

**Comment by mcarare** [comment]
Question for UX: The recent changes from @boek result in that when the the selected engine is deleted the first one in the list will be selected. 
IMO it actually makes more sense than selecting the next one in the list.
Should we keep this behaviour or implement the one suggested in the mocks?
TY!

**Comment by brampitoyo** [comment]
@mcarare Your and @boek’s proposal makes sense to us:

> […] when the the selected engine is deleted the first one in the list will be selected.

I will update comment 0 and my Miro specs with this decision.

**Comment by softvision-miralobontiu** [comment]
@brampitoyo just to be clear on the expected behavior: when the selected search engine is deleted, the first one in the list is selected automatically? I saw the new Miro specs:

![searchengine](https://user-images.githubusercontent.com/40694158/70539131-ea9f9900-1b6b-11ea-8efd-636392a90733.png)

**Comment by brampitoyo** [comment]
@softvision-miralobontiu Correct. As @mcarare wrote:

> The recent changes from @boek result in that when the the selected engine is deleted the first one in the list will be selected.

I think this behaviour makes sense.

**Comment by brampitoyo** [comment]
Updated comment 0 with UX behaviour.

**Comment by AndiAJ** [comment]
Hi, I've just checked this matter on the latest **Nightly build #13530608 from 12/19** using the following devices:
• Google Pixel 3a (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

It seems that when deleting search engines from the middle of the list or from Bottom :arrow_right: Top the second listed search engine is selected, and after the confirmation snackbar disappears it jumps to the first one.

✔️ Deleting the search engines Top :arrow_right: Bottom
![20191219_122634](https://user-images.githubusercontent.com/51314259/71167098-be1b0980-225c-11ea-9636-5ac86576254d.gif)

❌ Deleting the search engines from the Bottom :arrow_right: Top 
![20191219_122920](https://user-images.githubusercontent.com/51314259/71167431-55805c80-225d-11ea-9443-63503600a74b.gif)

❌ Deleting search engines located in the Middle of the list
![20191219_121526](https://user-images.githubusercontent.com/51314259/71166889-4baa2980-225c-11ea-9103-0d1d6dd6b86b.gif)

@mcarare - Please review. ☺️

**Comment by mcarare** [comment]
@AndiAJ please retest with the next Nightly.

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **Nightly Build #13540607from 12/20** using the following devices:
• Google Pixel 3a (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

✔️ Deleting the search engines Top ➡️ Bottom
![20191220_093921](https://user-images.githubusercontent.com/51314259/71239005-28d84d80-230e-11ea-8096-b5e19249ad30.gif)

✔️ Deleting the search engines from the Bottom ➡️ Top
![20191220_094001](https://user-images.githubusercontent.com/51314259/71239118-6f2dac80-230e-11ea-94a1-a1d1f3a50b9f.gif)

✔️ Deleting search engines located in the Middle of the list
![20191220_094053](https://user-images.githubusercontent.com/51314259/71239234-b61ba200-230e-11ea-8a49-2473bf599e97.gif)
