### ISSUE TITLE
[Bug] [Add search engine] "Custom" instead of "Other"

### ISSUE THREAD

**Issue by softvision-miralobontiu** [mozilla-mobile/fenix#6851]
## Steps to reproduce
1. Go to Settings - Search, tap on "Add search engine" and observe the page.

### Expected behavior
The option to add a different search engine from the ones displayed is through the "Other" radio button (like in the mocks https://miro.com/app/board/o9J_kwAuqu4=/).

### Actual behavior
The option to add a different search engine from the ones displayed is through the "Custom" radio button.

### Device information
* Android device: all
* Fenix version: 11/28 Nightly build (#13321152)

![custom](https://user-images.githubusercontent.com/40694158/69810761-475a9580-11f5-11ea-88b6-a7754ce47fc9.png)

**Comment by boek** [comment]
Let's fix this in 3.1. It's too late to update strings for 3.0 👍

**Comment by abodea** [comment]
Verified as fixed on the latest **Nightly** build from **1/8** with **Samsung Galaxy S10+(A 9).**
