### ISSUE TITLE
Remove the New Tab and Private Tab options from the menu

### ISSUE THREAD

**Issue by CharoSW** [mozilla-mobile/fenix#6862]
### Why/User Benefit/User Problem

They are superfluous options.  There are other quite obvious ways to create new tabs that fit in with how the browser does tab management so they just serve to take up menu space.  

### What/Requirements

The removal of the two menu items

### Acceptance Criteria (how do I know when I’m done?)

the items aren't in the menu

**Comment by avently** [comment]
I disagree with this idea. It's super easy to open new tab from a menu now and usability will degrade if the issue will be approved.

**Comment by cadeyrn** [comment]
> and usability will degrade if the issue will be approved.

That's not true at all. You need two steps to open a new tab from the menu and you need two steps to open a new tab without the menu. I see no difference. If you say "usability will degrade" then please explain why do you think so.

**Comment by avently** [comment]
@cadeyrn try to open a private tab with two steps. Did it? I don't think so.
Also to open a new non-private tab you need to load on screen all tabs you have. It is slower than to just open a menu and to click on new tab from there.

Also developers can make all menu items work with one long tap:
1. Long tap on three dots button
2. Menu opens, a finger is not released 
3. Move the finger on an item you need
4. Release the finger
5. Item is selected. 

This is not implemented yet but could be. And it is much better thing than "remove useful menu items".

**Comment by topotropic** [comment]
I'll close the issue, it's covered here https://github.com/mozilla-mobile/fenix/issues/8834
