### ISSUE TITLE
[Bug] Fenix is not reliably opening in-app in contrast to Chrome WebView

### ISSUE THREAD

**Issue by iamthekings5** [mozilla-mobile/fenix#6863]
## Steps to reproduce
1) Download any launcher that supports "Google Feed", or use a pixel device.
2) Open Google Feed from the homescreen of launcher.
3) Click on any website.

### Expected behavior
1) An in-app browser opens the link (Fenix). Upon pressing back, Fenix is closed and the user is returned to the Google Feed. (At least this is how Google did it.)

### Actual behavior
1) The link is opened in the Fenix browser. The user needs to press back once (rarely) or twice (most of the time [this is a separate issue])to get back to the Google Feed. Occassionally the feed might have resetted.

### Device information

* Android device: S10+ on Android 9 Pie (Custom Rom: Project Pixel 1.0)
* Fenix version: Nightly 191129 06:00

**Comment by boek** [comment]
Dup of #4904
