### ISSUE TITLE
[Bug] "Learn more" from "Add search engine" page is not found

### ISSUE THREAD

**Issue by softvision-miralobontiu** [mozilla-mobile/fenix#6866]
## Steps to reproduce
1. Go to Settings - Search - Add search engine and select Custom/Other.
2. Tap on the "Learn more".

### Expected behavior
A SUMO custom page is opened.

### Actual behavior
"Page not found" custom tab is opened. Every time in a different language.

### Device information
* Android device: all
* Fenix version: 11/29 Nightly build (#13330608)

![20191129_090555](https://user-images.githubusercontent.com/40694158/69857881-7c202880-1299-11ea-91d0-b2e5df48d545.gif)

**Comment by sblatz** [comment]
SUMO team: what link should we use here? We originally had `custom-search-engines` as the `escapedTopic` but that leads to a dead site. 

I've found [this article](https://support.mozilla.org/en-US/kb/how-manage-search-engines-firefox-preview#w_manually-add-search-engines) but it does not match our string format of: ` https://support.mozilla.org/1/mobile/$appVersion/$osTarget/$langTag/$escapedTopic`. 

Maybe we just need 
`https://support.mozilla.org/1/mobile/$appVersion/$osTarget/$langTag/$custom-search-engines` to point there?

**Comment by sblatz** [comment]
Spoke with Paul and he said that `https://support.mozilla.org/en-US/kb/how-manage-search-engines-firefox-preview` is the correct link. We just need sumo to set `https://support.mozilla.org/1/mobile/$appVersion/$osTarget/$langTag/custom-search-engines` to redirect to this :)

**Comment by jonichan** [comment]
I've set https://support.mozilla.org/1/mobile/$appVersion/$osTarget/$langTag/custom-search-engine to redirect to https://support.mozilla.org/kb/how-manage-search-engines-firefox-preview

Please let me know if that worked.

**Comment by sblatz** [comment]
That works! Thanks @jonichan 😄

**Comment by softvision-miralobontiu** [comment]
Verified as fixed on the latest Nightly build from 12/29 (#13631806), with Nexus 6P (Android 8.1), and Nexus 5 (Android 6.0.1).
