### ISSUE TITLE
[Bug] Unable to create a second collection

### ISSUE THREAD

**Issue by softvision-miralobontiu** [mozilla-mobile/fenix#6867]
## Steps to reproduce
1. Browse a few pages.
2. Create a collection with a few pages.
3. Create a second collection.

### Expected behavior
The user can create a second collection.

### Actual behavior
The user cannot create a second collection.

### Device information
* Android device: Google Pixel 2 (Android 9), Huawei MediaPad M2 (Android 5.1.1), and HTC Desire 820 (Android 6.0.1)
* Fenix version: 11/29 Nightly build

[logcat.txt](https://github.com/mozilla-mobile/fenix/files/3905153/logcat.txt)

**Comment by sv-sdeiac** [comment]
Hello, I can't reproduce the issue using Firefox Preview Nightly 12/30 @6:26 AM build.

Devices:
- Huawei MediaPad M2 (Android 5.1.1);
- HTC Desire 820 (Android 6.0.1);
- Google Pixel 2 (Android 9).

Due to that, I'll close this ticket, thanks.
