### ISSUE TITLE
[Bug] Cannot add private shortcut on Huawei MediaPad M2 (Android 5.1.1)

### ISSUE THREAD

**Issue by softvision-miralobontiu** [mozilla-mobile/fenix#6870]
## Steps to reproduce
1. Go to Settings and tap on Add private browsing shortcut.

### Expected behavior
A private Fenix shortcut is created on the device's homescreen.

### Actual behavior
The user is redirected to the device's homescreen, but no shortcut is displayed.

### Device information
* Android device: Huawei MediaPad M2 (Android 5.1.1)
* Not reproducible on Nexus 4 (Android 5.1.1), Xiaomi Mi4i (Android 5.0.2), HTC Desire 820 (Android 6.0.1)
* Fenix version: 11/29 Nightly build 

[logcat.txt](https://github.com/mozilla-mobile/fenix/files/3905482/logcat.txt)

**Comment by sflorean** [comment]
Not reproducible anymore on Nightly 12/31 on the affected devices. Closing this issue based on the test results.
