### ISSUE TITLE
Communicate No Connectivity to Users When Pairing/Syncing

### ISSUE THREAD

**Issue by marshvee** [mozilla-mobile/fenix#6875]
### Why/User Benefit/User Problem
To provide better feedback for the user when there's no internet connection.

### What/Requirements
Add visual elements (like snackbars or dialogs) that let the user know what went wrong and even let them retry the same action.

### Acceptance Criteria (how do I know when I’m done?)
For each network petition, there's a revision of network status. In case of failure, there's an informative message to the user.

### Design Work

- [x] Request for Comments from UX team
- [ ] ~Usability testing if a new pattern or potentially confusing UI~ Not required – this is a behaviour change
- [x] Request for Comments from Fenix team and/or A/C, GV, Sync, etc as needed
- [x] Interaction details included
- [x] Accessibility ~- is this a review by someone,~ just keeping it in mind?
- [ ] ~For existing UI changes, deltas are highlighted~ No UI – this is a behaviour change
- the[ ] ~Strings/content reviewed and approved~ No string – this is a behaviour change
    - [ ] ~Are they too long for the component in other locales~

### Deliverable

- [ ] ~Assets uploaded to Google Drive~
- [ ] ~Links to deliverables (spec, assets) posted in comment 0~

### Deliverable Links

- ~User flow: (link to e.g. Abstract artboard, LucidChart, Whimsical, Miro, etc.)~
- ~Spec: (link to e.g. Abstract artboards)~
- ~Assets: (link to Google Drive folder)~

### Behaviours

Communicate connectivity status subtly by **enabling/disabling the Sync button based on sync process completion and availability of internet connection**:

1. Ensure that the sync process can only be requested once, until it finishes running.
    - IF the user taps the “Sync Now” button
    - THEN disable “Sync Now” button, until the sync process has finished

2. If sync is interrupted, we should keep trying without overtly communicating our status.
    - IF the user taps the “Sync Now” button
    - AND the internet suddenly cuts off
    - THEN keep trying to sync.
This means that the “Sync Now” button is disabled until internet is restored and the sync process has finished. Through the disabled “Sync” button, the user will realise that something happens with the internet.

3. If sync has the potential to fail, disable it before it can happen
    - IF the phone has no internet
    - AND the user has not tapped the “Sync Now” button
    - THEN disable “Sync Now” button
This means that we’ll prevent users from manually syncing, unless their internet is working.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-14571)

**Comment by ekager** [comment]
To clarify, this is about when a user is trying to pair or sync and there is not internet connection. We can detect that state and add dialogs or icons to communicate that status to the user.

**Comment by brampitoyo** [comment]
@ekager @mrodriguez21 I wonder if, instead of communicating a failure state, we do this:

1. Ensure that the sync process can only be requested once, until it finishes running.
Behaviour:
    - IF the user taps the “Sync Now” button
    - THEN disable “Sync Now” button, until the sync process has finished
2. If sync is interrupted, we should keep trying without overtly communicating our status.
    - IF the user taps the “Sync Now” button
    - AND the internet suddenly cuts off
    - THEN keep trying to sync.
This means that the “Sync Now” button is disabled until internet is restored and the sync process has finished. Through the disabled “Sync” button, the user will realise that something happens with the internet.
3. If sync has the potential to fail, disable it before it can happen
    - IF the phone has no internet
    - AND the user has not tapped the “Sync Now” button
    - THEN disable “Sync Now” button
This means that we’ll prevent users from manually syncing, unless their internet is working.

The intention is to communicate our warnings subtly, if the message isn’t critical. Do you think that enabling/disabling the button based on sync process completion and availability of internet connection would solve this issue?

**Comment by brampitoyo** [comment]
@ekager @mrodriguez21 Let me know whether the above proposal solves the issue? TL;DR – let’s not show any dialog/icon, and disable the Sync menu item instead.

**Comment by ekager** [comment]
Yes I think this makes sense!

**Comment by brampitoyo** [comment]
Updated comment 0 with behaviours.

Nothing has changed from my comment up above. The comment 0 update is done so anybody who read this issue can see the solution without wading through heaps of text.

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1810824

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
