### ISSUE TITLE
Fenix video is getting trigger by google translate without user interaction

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/fenix#6880]
## Steps to reproduce [Video](https://drive.google.com/file/d/1sJ3Z4f2InJPbWhS0pUBzXt4lPnf6DmL6/view?usp=sharing)
1. Open a site with a video.
2. Play the video.
3. Pause de video.
4. Open Google Translate.
5. Tap voice icon and say something to translate.

### Expected behavior
Fenix doesn't the play the video, without the user interaction. 

### Actual behavior
Fenix starts playing video without any interaction from the user.

### Device information

* Android device: 
 Pixel 3. Android 10
* Fenix version: 
Nightly 191201 18:00 (Build #13351808)ac 24.0.0, cf9d95c05
GV 72.0a1-20191129094247

The same thing can be seen using Google assistant.

**Comment by Amejia481** [comment]
cc: @pocmo

**Comment by ekager** [comment]
Can still reproduce this.

**Comment by ekager** [comment]
@rocketsroger so should https://github.com/mozilla-mobile/android-components/pull/6649 resolve this when we get the newest AC version?

**Comment by rocketsroger** [comment]
> @rocketsroger so should [mozilla-mobile/android-components#6649](https://github.com/mozilla-mobile/android-components/pull/6649) resolve this when we get the newest AC version?

Yes, it will.  I will retest when AC version is updated and close when confirmed fixed.

**Comment by rocketsroger** [comment]
Confirmed with AC `39.0.20200416130123` this is now fixed.   Closing.
