### ISSUE TITLE
Custom settings for history like Firefox desktop

### ISSUE THREAD

**Issue by kamran-12** [mozilla-mobile/fenix#6884]
### Why
I hate browsing history. I mostly prefer browsing in private mode, especially on mobile. Always. By default.
When I used Fenix first time, private mode stayed activated even after closing the browser. I was looking for a browser with such property on Android so I started to use it as my main browser. But now that thing is gone.

### What I want
I think adding history settings identical to Desktop Firefox would be the best solution with highest acceptance among users. After all, those settings are a reason why I use Firefox instead of a Chromium-based browser on desktop. Another (but probably worse) option I would accept is making private mode disabling/enabling process like on Safari on iOS.
<img width="701" alt="image" src="https://user-images.githubusercontent.com/46045997/69944959-f8b54000-1501-11ea-9b05-68b6bc9a2fbc.png">

### Problems in current solutions
I will explain part-by-part what are problems with current private mode options.
1. **Open in private tab.** It doesn't work. Even if I explicitly select Fenix private mode in "open with" menu, custom tabs are not private, they get recorded in history.
2. **Clear data when quit.** It is actually "clear data when user presses quit". It is just a shortcut to clear history, not what I wanted.
3. **Shortcut to open private mode.** 1) It is too geeky; 2) it doesn't work if your launcher doesn't support widgets, or you don't want to add complexity to home screen; 3) it actually opens private mode's address bar, not private mode itself. Single touch on "back" button (for example, to access bookmarks) opens non-private browsing.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-14577)

**Comment by dfsdfsdfsdfsfsdf** [comment]
Thank you for this post!
Private browsing as you've described is common sense and it's what Firefox Mobile should have... But for some reason it still doesn't.
I suspect what's happened with this new app is that some indiviudals in the team thirsty to do something "innovative" have put forward their (half-baked) take on private browsing through the ridiculous method of using home screen shortcuts.
Not only does no one use home screen shortcuts for the core functionality in apps but MIUI's default launcher for example doesn't even support app shortcuts!
This app's development needs to go back to the basics and stop trying to be something special, just get the core functionality like private browsing and extensions done right and stop all the convulated non-sense.

**Comment by 894-572** [comment]
Personally I don't use the private browsing mode by default, but browsing history has been disabled for as long as I've used the desktop Firefox, and so was [on Fennec](https://android.stackexchange.com/questions/157768/how-to-disable-browsing-history-in-android-firefox).

**Comment by facadeproof** [comment]
I support this feature, or at least parsing the `about:config` setting `places.history.enabled` to disable history like in Fennec and Firefox Desktop.

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807549

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
