### ISSUE TITLE
Android <9 only: create smoother animation between private and regular mode

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#689]
Currently switching between the mode just happens immediately. We should create a nice fade so it's less jarring.

**Comment by sblatz** [comment]
Apparently this is only an issue on my Galaxy S9. The animation works properly on Pixel devices.

**Comment by sblatz** [comment]
For QA: does this animation work on all other devices?

**Comment by TitanNano** [comment]
It doesn't work on my Sony Z3+ AOSP 7.1.1 device.

**Comment by bsurd** [comment]
Managed to reproduce this on several devices.

Unaffected devices:
 - Google Pixel (A9)
 - OnePlus 5T (A9)

Affected devices:
 - Samsung Galaxy S8 (A8)
 - Samsung Galaxy Note 8 (A8)
 - Nokia 6 (Android 7.1.1)
 - HTC 10 (A8)
 - Nexus 6P (A8.1)

**Comment by sblatz** [comment]
This issue was resolved for me when my Galaxy S9 was updated to Android 9.0.

**Comment by sblatz** [comment]
@bsurd are you able to verify that this still happens and also post a video of what it looks like on your device(s)?

**Comment by bsurd** [comment]
I have checked, all of the devices have the same Android version as mentioned above. This is no longer reproducible for the Samsung devices, altho I was able to still reproduce this on the Nexus 6P and Nokia 6.

[Galaxy S8 video](https://drive.google.com/open?id=1Opi1Pn6RyhSC2446PU-i6Y24mWe5lgVA)
[Nexus 6P video](https://drive.google.com/open?id=1aXHXfQvbMMdg4_9KelMhs1mxnukYc9M6)

**Comment by bsurd** [comment]
This now works as expected on all devices, except for the HTC.  It's exactly the same as before. I've reopened #1533 for that.
