### ISSUE TITLE
[Bug] 3 Dot menu is displayed in TP menu under some specific steps

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/fenix#6897]
## Steps to reproduce
1. Launch Fenix.
2. Open any webpage.
3. Tap and hold at the same time on TP and 3 Dot menu buttons.
4. Release the TP and 3 Dot menu buttons.
5. While both menus are displayed, tap on `Protection Settings` option.
### Expected behavior
Only one from TP or 3 Dot menu is opened.
### Actual behavior
TP menu is opened but the 3 Dot menu is also displayed.
### Device information

* Android device: **Google Pixel 3a XL(Android 10).**
* Fenix version: **Latest Nightly from 12/2.**

### Notes
The 3 Dot menu can be dismissed without problems while being in TP section.
![ezgif-6-12287c4d84ae](https://user-images.githubusercontent.com/42831109/69973359-0da6c900-152c-11ea-954d-9eda8594e2cf.gif)

![ezgif-6-b29c54e8f730](https://user-images.githubusercontent.com/42831109/69973349-07b0e800-152c-11ea-95a3-bec4fdf5294a.gif)

**Comment by AndiAJ** [comment]
Reproducible on 3.0.0-beta.2 Build #13390410 from 12/5 using a Google Pixel 3a (Android 9)

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest Nightly Build **#13540607from 12/20** using the following devices:
• Google Pixel 3a (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

► Video
![20191220_090458](https://user-images.githubusercontent.com/51314259/71236776-794cac80-2308-11ea-8e0f-0457b0dea396.gif)
