### ISSUE TITLE
Setup tokens for fennecNightly builds

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/fenix#6898]
Follow-up from: #6688

- [x] Adjust
- [x] Leanplum
- [x] Sentry
- [x] Firebase
- [x] Digital Asset Links

**Comment by pocmo** [comment]
Johan added the Leanplum token for me. Now we only need a way to test that. 🤔 Hopefully the marketing team can help with that.

**Comment by pocmo** [comment]
If I read those Fennec docs correctly then there's no Adjust integration for Nightly. We could try to set up the build in a way so that without the secret key we do not use Adjust (Maybe that's already the case?).

https://firefox-source-docs.mozilla.org/mobile/android/adjust.html

**Comment by pocmo** [comment]
Added the Nightly Firebase token. This should be the last step now.

**Comment by ebalazs-sv** [comment]
The issue https://github.com/mozilla-mobile/fenix/issues/6688 is verified as fixed and Fennec Nightly is replaced by Fenix Nightly migration build. I will move this to Done. Thanks!
