### ISSUE TITLE
Setup tokens for fennecBeta builds

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/fenix#6899]
Follow-up from: #6622 

- [x] Adjust
- [x] Leanplum
- [x] Sentry
- [x] Firebase
- [x] Digital Asset Links

**Comment by pocmo** [comment]
All tokens are setup for the beta build.

**Comment by ebalazs-sv** [comment]
The issue #6622 is verified as fixed and Fennec Beta is replaced by Fenix Beta migration build. I will move this to Done. Thanks!
