### ISSUE TITLE
[Bug] Bottom fixed content is hidden outside of viewport when Fenix toolbar is set to top.

### ISSUE THREAD

**Issue by ekager** [mozilla-mobile/fenix#6900]
![top](https://user-images.githubusercontent.com/25442310/69976294-a33c5b80-1520-11ea-873d-d244c9257fd1.jpg)

Scenario 1
Open Fenix
Load https://m.standaard.be/
Site's own bottom navigation bar is shown

Scenario 2
Open Fenix, set toolbar to top.
Load https://m.standaard.be/
Site's own bottom navigation is hidden and requires panning for it to be shown.

Scenario 3
Open Chrome or Fennec (both with a top nav bar)
Load https://m.standaard.be/
Site's own bottom navigation bar is shown

**Comment by ekager** [comment]
Removed the GV label because removing the scroll flags that we set dynamically on the top toolbar fixes this issue. This is likely a Fenix issue with those scroll flags

**Comment by ekager** [comment]
Mmm I tested this with an old Focus WV build and it happens there as well. It looks like the scrolling away toolbar behavior cuts off the height of the web content that it scrolls away. Someone else may know more about this behavior.

**Comment by hiikezoe** [comment]
I am pretty sure this is the same issue what I reported. It's https://github.com/mozilla-mobile/fenix/issues/6940

**Comment by liuche** [comment]
I'll move the screenshot over and dupe-closing this.
