### ISSUE TITLE
[Bug] Changing Locale Does Not Update Search Engines

### ISSUE THREAD

**Issue by ekager** [mozilla-mobile/fenix#6907]
## Steps to reproduce
1. Have phone in 1 locale
2. Open search engine settings, observe default "installed" engines
3. Change locale
4. Observe search engine settings

### Expected behavior
Default installed engines (and default?) are updated with locale 

### Actual behavior
First locale "locks" in search engines in our saved file

### Device information

* Android device: ?
* Fenix version: ?

**Comment by sv-ohorvath** [comment]
@ekager I saw something related but I'm not sure it matches your description:
changing from EN to RU, for e.g, I'm left only with Twitter (all the others are removed)... I should get Google and Yandex at the very least. 
Changed to DE: I only got Bing, DuckDuckGo and Twitter.
Is that a different issue or is it the same?

**Comment by mcarare** [comment]
related issue: https://github.com/mozilla-mobile/fenix/issues/6981

**Comment by kglazko** [comment]
Investigated this a bit deeper: it appears that on the emulator, changing the language will change the local after a restart of the application.

**Comment by kglazko** [comment]
Unassigning myself because there are other priorities in polish to work on now.

**Comment by ekager** [comment]
Closing as dupe of #6981
