### ISSUE TITLE
[Bug] Bookmark saved snackbar not displaying with top toolbar

### ISSUE THREAD

**Issue by ekager** [mozilla-mobile/fenix#6908]
## Steps to reproduce
1. Change toolbar to top
2. Bookmark a page

### Expected behavior
See snackbar

### Actual behavior
Don't see snackbar

### Device information

* Android device: ?
* Fenix version: ?

**Comment by ekager** [comment]
Also likely impacts onCannotOpenFile, tab saved to collection snackbars

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **Nightly Build #13430607 from 12/9** using the following devices:
• Google Pixel 3a (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

► Add/remove bookmark
![20191209_161449](https://user-images.githubusercontent.com/51314259/70443895-ac3da780-1aa1-11ea-954d-80e0dbc03dc1.gif)

► Tab saved to collection
![20191209_161756](https://user-images.githubusercontent.com/51314259/70444098-09d1f400-1aa2-11ea-8168-941259ca472b.gif)

► Could not open file
![20191209_161852](https://user-images.githubusercontent.com/51314259/70444248-456cbe00-1aa2-11ea-9c6f-0bbb3e8839ad.gif)
