### ISSUE TITLE
[Bug] Bottom margin for shortcut onboarding looks too large

### ISSUE THREAD

**Issue by ekager** [mozilla-mobile/fenix#6910]
![Screenshot_20191203-001058](https://user-images.githubusercontent.com/25442310/70005738-7a3cba80-1562-11ea-88cc-319980112869.png)

It's fine before you start typing, but once you have suggestions it looks a bit strange

**Comment by brampitoyo** [comment]
Hi @ekager, referring to our search suggestions onboarding design: https://share.goabstract.com/ccf6360e-529b-4a94-96af-7e67845a6dc1

It looks as if there’s a horizontal divider between the shortcut onboarding and the line of text below it. I wonder, when this divider is put in, if the bottom margin would look OK? It may still be too large – if that’s the case, we can reduce it.

**Comment by mcarare** [comment]
@ekager : I am curious on which build you had this screen, cause it should not appear on normal browsing. And maybe a STR? TY!

@brampitoyo : Actually the mock is wrong, cause you cannot have search suggestions or engine list while having the suggestions onboarding on screen. That shows up only after you type (that is when the engine list disappears) and only if you have show suggestions in private disabled (that means no suggestions will appear). This being said, would a divider line make sense? It would look like this: 

<img src = https://user-images.githubusercontent.com/48995920/70042031-e5b87380-15c6-11ea-8aff-3abb9ffa930c.png width = 30%>
Notice we have 2 dividers and nothing in between them. If we decide to keep a divider, should it be like in this screenshot, or full width, like in the mocks? TY!

**Comment by brampitoyo** [comment]
@mcarare Interesting. I didn’t know that the search suggestions onboarding box _cannot appear together_ alongside search shortcuts list.

We were working under the assumption that users can switch search engines without making a decision to show suggestions.

In the scenario you’ve screenshot – where search suggestions onboarding is shown alone – the divider under the onboarding doesn’t make sense to show.

The divider only makes sense to show when there are items underneath. But now I wonder whether there’s any situation where this is true? Maybe the onboarding box is always shown by itself?

When shown, the divider should be full width as shown in the mocks. Thanks!

**Comment by abodea** [comment]
Verified as fixed in the latest **Nightly build 12/9** with **Google Pixel 3a XL(Android 10)**.
Note that everything looks fine in portrait and landscape mode.
