### ISSUE TITLE
[Bug] Video Notification Play/Pause icon is misleading

### ISSUE THREAD

**Issue by Djfe** [mozilla-mobile/fenix#6913]
The video is muted by default (but autoplay).
The icon that indicates play/pause is a speaker icon which is misleading.
It looks like the video isn't muted even though it is, when it is playing.
![Screenshot_Firefox_Preview_20191203-012558](https://user-images.githubusercontent.com/5685512/70015213-f8a65600-157c-11ea-8553-763caeb070bc.png)
![Screenshot_Firefox_Preview_20191203-032904](https://user-images.githubusercontent.com/5685512/70015312-4458ff80-157d-11ea-86c3-990a884af4f0.png)

I would suggest to either switch to
▶ ⏸
or indicate mute/unmute with it instead :)

EDIT:
I'm not sure how videos without an audio track should be handled. (gif/animation -> video)

### Device information

* Android device: OnePlus 3T
* Fenix version: 2.3.0 (Build #13031728)

**Comment by ekager** [comment]
@Djfe does the fix for #8497 help your problem? We are no longer showing a notification for muted media content.

**Comment by Djfe** [comment]
@ekager 4.2.1 on playstore doesn't seem to include the fix, yet. But it sounds like it would
