### ISSUE TITLE
[Bug] (regression) tabs on startscreen disappear

### ISSUE THREAD

**Issue by cadeyrn** [mozilla-mobile/fenix#6917]
### Steps to reproduce
Signed into Sync
1. make sure you have some open tabs
2. close Fenix via recent apps menu
3. start fenix
4. switch to Android home screen
5. start Fenix again

### Expected behavior

You can see your open tabs after step 3.

### Actual behavior

You see your open tabs after step 3 only for a short moment, then all tabs disappear. After step 5 the open tabs stay visible.

This is a recent regression.

### Device information

* Android device: OnePlus 7T Pro McLaren Edition
* Fenix version: master branch revision 85d222d2b19c515d42208bebbaee45c062367d09

**Comment by ekager** [comment]
Possibly a regression from #6784?

**Comment by cadeyrn** [comment]
I can confirm that #6784 is the cause.

@mcarare Could you have a look? Your change broke the tabs view on the start screen.

**Comment by mcarare** [comment]
@ekager @cadeyrn The change in #6784 only impacts situations when you change the browsing mode from private to normal or vice versa. From the STR I do not see that part of the code triggering. Also, with the latest master I cannot reproduce this.

**Comment by cadeyrn** [comment]
@mcare It's definitively caused by #6784. It's reproducible for me in 100% and it only happens with this change and no longer happens if I remove this change.

**Comment by abodea** [comment]
Hello @cadeyrn @mcarare I also tried to reproduce this issue but I couldn't for more details please check the following:

| Build | Device |  Works as expected? |
| --- | --- |:---:|
| Nightly 12/3 | Google Pixel 3a XL(Android 10) |  ✅  |
| Nightly 12/4  | Google Pixel 3a XL(Android 10) |✅   | 
| Nightly 12/3 | Samsung Galaxy S10+(Android 9)|  ✅  |
| Nightly 12/4  | Samsung Galaxy S10+(Android 9) |  ✅  | 
| Nightly 12/3 | Samsung Galaxy S10+(Android 9)| ✅   |
| Nightly 12/4  | Samsung Galaxy S10+(Android 9) | ✅   | 
| Nightly 12/3 | Motorola G4(Android 6)|   ✅ |
| Nightly 12/4  | Motorola G4(Android 6) | ✅   | 

#### Note that I tried 2 cases based on your steps from the description:
1. This is a video trying to reproduce the issue following the exact steps from the description:
![1](https://user-images.githubusercontent.com/42831109/70127971-bff1a400-1684-11ea-95f2-a2c857138c03.gif)
2. This is a video trying to reproduce the issue following the exact steps from the description but with **delete browsing data on quit** enabled.
![2](https://user-images.githubusercontent.com/42831109/70128032-db5caf00-1684-11ea-810f-ba9239aef99f.gif)

**Comment by Dunexus** [comment]
I can reproduce on OnePlus 5T, Nightly 191203 10:27.

**Comment by mcarare** [comment]
@cadeyrn @Dunexus Can you please attach a video with the reproducing of the bug? TY!

**Comment by cadeyrn** [comment]
Yes, I can attach a video later today or tomorrow - I use a build without this change at the moment and will be late at home today.

@Dunexus and I we both use a OnePlus smartphone. Maybe that's one important thing we have in common.

**Comment by Dunexus** [comment]
@mcarare 

![ezgif-4-981ee02fb61e](https://user-images.githubusercontent.com/13906248/70141404-47481300-1697-11ea-8722-096e2f836e77.gif)

**Comment by AndiAJ** [comment]
Hi, I've manage to reproduce this issue on a Google Pixel 3a (Android 9).

► Video
![20191204_165604](https://user-images.githubusercontent.com/51314259/70154469-36a89480-16b9-11ea-88a5-c481b0a229c7.gif)

►[Logcat](https://github.com/mozilla-mobile/fenix/files/3922524/tabz.txt)

#### It seems to be happening only when you are logged in to sync.
#### Didn't manage to reproduce once I've logged out.

**Comment by mcarare** [comment]
@AndiAJ Thanks, this info is very helpful!

**Comment by Dunexus** [comment]
I've logged out and retried, I didn't manage to reproduce.

**Comment by LittleAngelwings** [comment]
I can confirm this issue only when I connected with Sync. I have this issue on all my devices and it's no matter if  I use the devices in portrait or landscape view and different Android versions. ( >8.1.0).

**Comment by AndiAJ** [comment]
Reproducible on **3.0.0-beta.2 Build #13390410 from 12/5** using a Google Pixel 3a (Android 9)

**Comment by sv-sdeiac** [comment]
Also, this issue is reproducible if you make a manual crash by using the "about:crashparent" command on the URL bar.
Device: LG g7 fit (Android 8.1).
Build: Beta Beta 3.0.0-beta.2 (12/5);

**Comment by beastdestroyer** [comment]
Noticed this statted happening only after I cleared the cache from the app. Everytime I open the app it will show and then disappear, but reappears after I go to a new screen or tab

Android 9 MIUI 11 Mi 8 Lite, Nightly 191205 18:01 (Build #13391806)
📦: 25.0.0, 48b092bde
🦎: 72.0a1-20191202091209

And has occured since I cleared cache, so about 2 - 3 builds ago too.

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **Nightly Build #13450608 from 12/11** using the following devices:
• Google Pixel 3a (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• Motorola G4 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

► Restart while the user is signed in to Sync
![20191212_111107](https://user-images.githubusercontent.com/51314259/70608594-0c9b2900-1c09-11ea-9cf6-45323b651b4f.gif)

► Restart after forcing a crash
![20191212_111209](https://user-images.githubusercontent.com/51314259/70608695-37857d00-1c09-11ea-8b50-dc67dce3d792.gif)

► Restart after clearing the apps cache
![20191212_111421](https://user-images.githubusercontent.com/51314259/70608838-7c111880-1c09-11ea-94d9-d6c36f5e91a8.gif)

**Comment by cadeyrn** [comment]
This bug is now in the stable Firefox Preview 3.0 release, that's bad… Why did the fix not land in the 3.0 branch?

**Comment by cadeyrn** [comment]
@boek I saw you're creating a 3.0.1 release. Could you include this fix as well? It's not ideal that all open tabs disappear after a second when starting Fenix…

**Comment by boek** [comment]
@cadeyrn great catch! I I thought I did cherry-pick this but it failed 😱

**Comment by sv-sdeiac** [comment]
Hello, I can confirm that the issue is not reproducible using the steps from the description, https://github.com/mozilla-mobile/fenix/issues/6917#issuecomment-562142686, and https://github.com/mozilla-mobile/fenix/issues/6917#issuecomment-562822488.

Devices:
- LG g7 fit (Android 8.1);
- Xiaomi Mi 8 Lite (Android 9);
- Motorola Moto G6 (Android 8).
Build:
- RC 3.0.1 #13502255 12/16.
