### ISSUE TITLE
[Bug]Error presented if you want to create a custom search engine on yandex.com

### ISSUE THREAD

**Issue by sv-sdeiac** [mozilla-mobile/fenix#6919]
## Steps to reproduce
1. Stop internet connection.
2. Go to Settings -> Search -> Add search engine.
3. Select Custom.
4. Type a name and the search string (in my example I used yandex.com/search/?text=%s).
5. Press the icon from the top right of the screen to add the custom search engine.

### Expected behavior
The custom search engine is added.

### Actual behavior
An error is presented under the 'Search string to use' field.

### Device information

* Android device:  Nokia 6 (Android 7.1.1) and Google Pixel (Android 9).
* Fenix version: Nightly 12/3 ( #13371032);

#### Notes: 
![Screenshot_20191203-162205](https://user-images.githubusercontent.com/40264165/70059511-99325f80-15e9-11ea-9b87-a720c4d41957.png)

**Comment by ekager** [comment]
You can't add a search engine without internet connection because we need to verify that the search string is valid

**Comment by sv-sdeiac** [comment]
My bad about this issue. I'll close it as being an Invalid issue, thanks.
