### ISSUE TITLE
Show guiding toast message to help user set Fenix as default browser

### ISSUE THREAD

**Issue by andreasbovens** [mozilla-mobile/fenix#6920]
### Why/User Benefit/User Problem

As a user, I am confused when tapping "Set as default browser" and arriving on the "Default apps" setting. I'd appreciate guidance explaining what I should do in this view.

### What/Requirements

When a user flicks the "Set as default browser" toggle (or taps on the text) in settings, and Fenix is not set as default, we should show a 5 second toast message that says "Tap Browser app & select Fenix" (where Fenix is "Firefox Preview", etc.).

### Acceptance Criteria (how do I know when I’m done?)

See Fennec for reference implementation.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-14600)

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813205

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
