### ISSUE TITLE
[Bug] Awesomebar suggests only for every other typed character (highlight)

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#6935]
## Steps to reproduce
- Click URL bar
- Type "g" (observe highlight in toolbar)
- Type "o" (observe no highlight in toolbar)
- Type "o" (highlight)
- Type "g" (no highlight)
- etc.

### Expected behavior
Autocomplete highlight always so user can press enter to visit the page

### Actual behavior
Autocomplete highlight appears on every other character, preventing user from searching until they type another letter.

I'm using Google keyboard, afaik.

### Device information

* Android device: Pixel 2
* Fenix version: Nightly 191202 18:01

**Comment by neekless** [comment]
Reproduced using SwiftKey keyboard as well.

**Comment by djc** [comment]
I have the same problem with SwiftKey, so this doesn't depend on GKeyboard. I also have a Pixel 2, and this is most definitely a regression from before.

**Comment by rocketsroger** [comment]
This is a A-C issue, https://github.com/mozilla-mobile/android-components/issues/5505

**Comment by rocketsroger** [comment]
Please verify this issue has been fixed on nightly.  Thanks,

**Comment by djc** [comment]
Yup, fixed for me on latest Nightly Fenix! Thanks!

**Comment by rocketsroger** [comment]
Thanks I'll close this issue.
