### ISSUE TITLE
[Bug] SQLITE_BUSY during fennec migration - overlapping runMaintenance call

### ISSUE THREAD

**Issue by grigoryk** [mozilla-mobile/fenix#6937]
In application's `onCreate`, we sometimes call `runMaintenance`. Currently, we'll definitely call it on first launch. Once that code runs, depending on timing of the migration logic, we may try to lock the underlying database concurrently.

**Comment by ebalazs-sv** [comment]
@grigoryk Hello! Can you please provide steps to reproduce this so I can verify this? Thank you!

**Comment by st3fan** [comment]
@ebalazs-sv I think this is very hard to verify so I will move this to Done.
