### ISSUE TITLE
Add a setting to allow opening links in native app by default

### ISSUE THREAD

**Issue by rtg500** [mozilla-mobile/fenix#6939]
### Why/User Benefit/User Problem
Most services have better performance on app compared to browser.  Also, if a user has an app installed, he is likely to prefer using it.  Currently, it takes multiple clicks or long press to open in app which might be wasting the user's time.

### What/Requirements
A setting in the Fenix app to choose whether you want to open the link in native app, whenever possible.  This is already present in most Android browsers like Chrome, Edge.

### Acceptance Criteria (how do I know when I’m done?)
When a link is opened directly in a native app without clicking on extra buttons.

**Comment by reinhart1010** [comment]
Android has actually implemented this (since Lollipop), while it might also a good idea to provide option for users on whether to open links in new tab, or follow system settings.

![](https://i.imgur.com/HSThzvd.jpg)

**Comment by rtg500** [comment]
I think you misunderstood.  On Edge/Chrome Android, if I google Effiel Tower and click on Maps, it will automatically open "Maps" app, if installed.  In Firefox Preview, it will open the maps tab in Browser and give an option to open in app.  I am requesting a feature similar to Edge/Chrome, where you can select in browser settings if you want links to be opened in app when app is installed.

**Comment by NotWoods** [comment]
Superseded by #7102
