### ISSUE TITLE
[webcontent] viewport size with top dynamic toolbar looks wrong

### ISSUE THREAD

**Issue by hiikezoe** [mozilla-mobile/fenix#6940]
## Site with issue and any steps to reproduce

Open http://bokand.github.io/demo/urlbarsize.html
### Expected behavior

The size of bars containing "percentage-based" should be bit shorter than visible content area.

### Actual behavior

Those bars are covered by the bottom edge.

We need at least to call setDynamicToolbarMaxHeight and need a new API similar to setVerticalClipping.

CC @sblatz, @pocmo, @snorp and @theres-waldo

and also: 

![top](https://user-images.githubusercontent.com/25442310/69976294-a33c5b80-1520-11ea-873d-d244c9257fd1.jpg)

Scenario 1
Open Fenix
Load https://m.standaard.be/
Site's own bottom navigation bar is shown

Scenario 2
Open Fenix, set toolbar to top.
Load https://m.standaard.be/
Site's own bottom navigation is hidden and requires panning for it to be shown.

Scenario 3
Open Chrome or Fennec (both with a top nav bar)
Load https://m.standaard.be/
Site's own bottom navigation bar is shown

**Comment by boek** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1610959

**Comment by hiikezoe** [comment]
@sblatz could you make the top toolbar _real_ dynamic?  This issue is pretty important in terms of the _Web_.

I've put a change https://github.com/hiikezoe/fenix/commit/ffa236ec7eb1e8ef4a69718ba313a088b2e94f3c for references, I am pretty sure you can fix this.

**Comment by heycam** [comment]
Just to reinforce Hiro's comment, I have been encountering a number of sites with broken layout due to positioning of elements at the bottom of the viewport when I have the address bar on top, such as this "how much you've read through the article" progress bar on this page:

<img src="https://user-images.githubusercontent.com/1484434/75739563-4c316700-5d59-11ea-8a37-ac40fd828803.png" width="270" height="540">

**Comment by liuche** [comment]
According to the GV team, the APIs to fix this should be available now.

**Comment by liuche** [comment]
@sblatz should we dupe this and #8765?

**Comment by jan-ivar** [comment]
🎉 ❤️ 🙏

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly Build #21130610 from 4/22`** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)

► Screenshot url bar size
![rsz_screenshot_20200422-143138](https://user-images.githubusercontent.com/51314259/79978561-c7d1a980-84a8-11ea-876a-74106e38fa0a.png)

► Video https://m.standaard.be/

![20200422-150845](https://user-images.githubusercontent.com/51314259/79980890-72979700-84ac-11ea-97af-77d50bd74807.gif)

► Video https://www.scientificamerican.com/
![20200422-145623](https://user-images.githubusercontent.com/51314259/79981118-cbffc600-84ac-11ea-8892-ba1a05c12480.gif)

**Comment by hiikezoe** [comment]
\o/  Thank you sblatz!
