### ISSUE TITLE
[Bug] tmall.com isn't displayed properly in landscape mode

### ISSUE THREAD

**Issue by Diana-Rus** [mozilla-mobile/fenix#6941]
## Steps to reproduce
1. Visit tmall.com
2. Rotate device to landscape view.
### Expected behavior
The page is displayed correctly in landscape mode. 
### Actual behavior
The page remains in portrait mode.
### Device information

* Android device: Google Pixel 3 XL (Android 9)
* Fenix version: Fenix Nightly 191204 (Build #13380608) and GeckoView: 72.0a1-20191202091209

Note:
- Layout is updated correctly when reloading the page. 
- This issue is similar to the one described in: https://github.com/mozilla-mobile/fenix/issues/3898

**Comment by boek** [comment]
Looks like this is a bug with tmall.com. Behavior is the same in every browser I tried
