### ISSUE TITLE
[Bug] "Settings" header is displayed in homescreen after deleting browsing data 

### ISSUE THREAD

**Issue by softvision-miralobontiu** [mozilla-mobile/fenix#6943]
## Steps to reproduce
1. Go to Settings - Delete browsing data and tap on the "Delete browsing data" button.
2. Accept to delete the data.
3. Observe the homescreen's header.

### Expected behavior
No header is displayed in the homescreen.

### Actual behavior
"Settings" header is displayed. Tapping on the back arrow from it, exits the app.

### Device information
* Android device: HTC Desire 820 (Android 6.0.1), Xiaomi Mi 8 Lite (Android 9), LG G7 Fit (Android 8.1.0)
* Fenix version: 191204 Nightly build (#13380608)

![20191204_Trim](https://user-images.githubusercontent.com/40694158/70147538-25598b00-16ad-11ea-80a3-e5ebeb77c46f.gif)

**Comment by abodea** [comment]
Verified as fixed in the latest **Nightly build 12/9** with **Google Pixel 3a XL(Android 10)**.
