### ISSUE TITLE
[Bug]The zoom jump on the top-left part of the site if pinch-zoom a plain text

### ISSUE THREAD

**Issue by sv-sdeiac** [mozilla-mobile/fenix#6945]
## Steps to reproduce
1. Open Firefox Preview; 
2. Go to a page with text(ex. wikipedia.org/wiki/Main_Page);
3. Select any plain text; 
4. Start to pinch-zoom but don't leave the fingers from the screen.

### Expected behavior
The page will zoom in.

### Actual behavior
The page will zoom in but jump on the top-left part of the site.

### Device information
* Android device: LG G7 fit (Android 8.1), Xiaomi Mi 8 Lite (Android 9);
* Fenix version: 191204 Nightly build (#13380608);
![20191204_164109](https://user-images.githubusercontent.com/40264165/70152647-4672a980-16b6-11ea-976e-0eff8bb1ed37.gif)

**Comment by sv-sdeiac** [comment]
After my previous investigation, I found that if you pinch-zoom and after the jump, you're releasing the fingers, the focus is replaced in the right place of the page.

#### Build:
- Firefox Preview Nightly 1/7 build #20070606.

#### Device:
- LG G7 fit (Android 8.1).

**Comment by boek** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1610960

**Comment by sv-sdeiac** [comment]
This issue it seems to be fixed using the latest version of Firefox Preview Nightly debug build 4/9 #21000923. 

Device:
- LG g7 fit (Android 8.1).

Due to that, I'll close this ticket, thanks.

**Comment by fluffyemily** [comment]
Bugzilla issue resolved 19th Feb 2020
