### ISSUE TITLE
UX Nit: Home screen - Google search bar "snaps" slowly to endpoints making it hard to tap on second tab in list

### ISSUE THREAD

**Issue by Cheap-Skate** [mozilla-mobile/fenix#695]
(I'm aware this is probably standard Android behavior and probably something that you can't fix even if you wanted to)

There is very little friction when scrolling in the list of tabs on the Home screen.   If I have many tabs open, do a gentle fling to find another tab, the list "drifts" slowly for many many seconds with almost no friction. This means I often have to tap twice to select a tab:- once to stop it drifting upwards and once more to tap the (now stationary) tab. Irritating.

The scroll friction in the tabs list seems much lower than for actual web content. 

I think this is standard Android scroll view behavior but it's bugging me.

**Comment by Cheap-Skate** [comment]
I understand my issue better now.

There are two mechanisms for slow scrolling on the Home screen:-
(a) "snap" scrolling where the Google search box slowly snaps to one or other of its endpoints when I position it in the middle of its travel and then release my finger 
(b) normal inertia scrolling - I instigated a very slow fling with my finger and the tabs are drifting

Case (a) and (b) look exactly the same. But they behave differently when I tap a moving tab.

In Case (a) the tap registers and I move to the tab. In Case (b) the first tap causes the fling inertia scroll to stop and moving to the tab requires a second tap.

When I see the Home screen scrolling slowly, I can't tell whether a single tap on a tab will move me to my tab, or if a single tap will stop the inertia scroll and a second tap will move me to my tab.

I would be less confused if the case (a) behavior didn't happen so that the only scrolling of tabs was user instigated. Then it would always be one tap to stop the inertia scroll, second tap to move to tab.


I see on today's Fenix Nightly &
Galaxy S7 / Android 8.0.0 &
BQ Aquaris X5 / Android 7.1.2

**Comment by Cheap-Skate** [comment]
Same as or similar to #2357?

**Comment by sblatz** [comment]
Closing this in favor of https://github.com/mozilla-mobile/fenix/issues/2357 which is addressed by https://github.com/mozilla-mobile/fenix/pull/3878
