### ISSUE TITLE
[Bug] Not all the elements from "wetelo.com" page are displayed correctly.

### ISSUE THREAD

**Issue by Diana-Rus** [mozilla-mobile/fenix#6951]
Prerequisites:
- Have "gfx.webrender.all= true"
- Have "gfx.webrender.force-disabled= false"

## Steps to reproduce
1. Open Fenix Nightly and go to https://wetelo.com/ and inspect all elements from the page after the animation loads.
2. Scroll down.
3. Scroll up.
4. Inspect the elements from the first page.
### Expected behavior
The static elements from the page are correctly displayed.
### Actual behavior
The static elements from the page are set on the left side of the page.
### Device information

* Android device: Google Pixel 3 XL (Android 9)
* Fenix version: Fenix Nightly 191204 (Build #13380608) and GeckoView: 72.0a1-20191202091209

Note: Please view [video](https://drive.google.com/file/d/1VhgCINjTxQDVggGov6MpfQmOsAWdKtGd/view?usp=sharing).

**Comment by sv-ohorvath** [comment]
Not an issue, that's how it looks like on Chrome as well.
