### ISSUE TITLE
[Bug] There appears a blank at buttom when I exit fullscreen.(When top toolbar is selected.)

### ISSUE THREAD

**Issue by adth03** [mozilla-mobile/fenix#6952]
Set toolbar position as top. Watch a video in fullscreen mode. After exiting fullscreen, there appears a blank at the buttom of browser (while swiping page).

**Comment by ekager** [comment]
Probably needs an adjustment in `getEngineMargins()`

**Comment by sblatz** [comment]
This seems like a easily reproducible and annoying bug. I think we should pull this in.

**Comment by kbrosnan** [comment]
Did this get fixed? There is no associated pull request.

**Comment by ekager** [comment]
Assuming it was fixed by #7126
