### ISSUE TITLE
Migration fennec* build variants need to use corresponding Fennec push keys

### ISSUE THREAD

**Issue by grigoryk** [mozilla-mobile/fenix#6954]
- [ ] Get Firebase keys for Fennec Nightly from RelMan. We have prod/beta but not nightly for some reason.
- [ ] Add Firebase keys for Fennec prod/beta/nightly to the build variants.
  - Consider using the [build variants structure](https://firebase.google.com/docs/projects/multiprojects#support_multiple_environments_in_your_android_application) to place the keys which seem most ideal.

**Comment by grigoryk** [comment]
Impact without these keys is that we currently crash if an affected build receives a push message it was never expecting to receive.

**Comment by grigoryk** [comment]
A short-term work-around is to disable push support on fennecProduction build variants, until we land the keys.

**Comment by pocmo** [comment]
* Nightly: https://github.com/mozilla-mobile/fenix/issues/6898
* Beta: https://github.com/mozilla-mobile/fenix/issues/6899

**Comment by ebalazs-sv** [comment]
Issue https://github.com/mozilla-mobile/android-components/issues/5041 is verified and fixed on Release migration builds so I will move this to Done.
