### ISSUE TITLE
Items at the top of the homescreen are hidden on scroll up

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#696]
## Steps to reproduce
1. Open a webpage.
2. Tap the tabs button to see the homescreen.
3. Scroll up (drag the page down). Or, just tap the Fenix logo.
### Expected behavior
Nothing happens.
### Actual behavior
Logo, menu and PB icons are hidden.
### Device information

* Android device: HTC 10 (Android 8.0)
* Fenix version: 1.0.1909, 2/26 build.

**Comment by vesta0** [comment]
This is fixed.
