### ISSUE TITLE
[Bug] "Try again" button from "Unable to connect" page is not centered on tablets

### ISSUE THREAD

**Issue by Diana-Rus** [mozilla-mobile/fenix#6965]
Prerequisites:
- Have wi-fi network connection enabled

## Steps to reproduce
1. Open Fenix app.
2. In URL bar insert "bugzilla.mozilla.org".
3. Disable wi-fi network connection.
4. Inspect the "Unable to connect" page for button "Try again".

### Expected behavior
The "Try Again" button is centered and has the same length as of the text from the top of the page.

### Actual behavior
The "Try Again" button is not centered.

### Device information
* Android device: Xiaomi Mi Pad3 (Android 7.0), Sony Xperia Z5 (Android 7.0)
* Fenix version: Fenix Beta 3.0.0-beta2 (Build #13390410) and Gecko View 71.0-20191125115111

Note:
- On mobile phones the "Try Again" button is centered in portrait mode.
- The length of the "Try Again" button on mobile phones is the same as for the text.
- The same behavior as for tablets is encountered for mobile phones in landscape mode.

* Is this the intended outcome for tablets whether it is in portrait or landscape mode. And for mobile phones in landscape mode?

Please view the attached 
![Screenshot_2019-12-05-12-23-40-464_org mozilla fenix beta](https://user-images.githubusercontent.com/42831109/70227643-9b1c3000-175b-11ea-8c59-aabebf4dd3e8.png)

**Comment by liuche** [comment]
This should be centered, is probably something wrong with the html page.

**Comment by KaairaGupta** [comment]
May i be assigned this issue?
Also, how should i proceed with it?

**Comment by liuche** [comment]
@sblatz is this going to be affected by #5892 ?

**Comment by sblatz** [comment]
Yes, @liuche. This should be covered by that :)

**Comment by sblatz** [comment]
This should've been fixed by my error page updates.

**Comment by abodea** [comment]
Verified as fixed on the latest Nightly from 2/10 using Xiaomi Mi Pad3 (Android 7.0), Samsung Galaxy S10+(Android 9).
Note that now the button is centered.
