### ISSUE TITLE
[Bug] Fingerprint Auth is not working on One UI 2.0 (Android 10)

### ISSUE THREAD

**Issue by daniluk4000** [mozilla-mobile/fenix#6966]
## Steps to reproduce

- Update Galaxy S10 to One UI 2.0 with Android 10
- Add fingerprint in settings
- Try to view your passwords 

### Expected behavior
- Nothing happens after I auth
https://youtu.be/WO3YJPphgko

### Actual behavior
- I can see my passwords (feature is working in another application)

### Device information

* Android device: Galaxy S10 SM-G937F, firmware G973FXXS3BSL4, Android 10
* Fenix version: Nightly 200112 06:01 (build #20120607)

**Comment by daniluk4000** [comment]
I see error after I've been returned to App:
`E/BufferQueueProducer: [com.android.settings/com.android.settings.password.ConfirmDeviceCredentialActivity$InternalActivity$_20729#0] disconnect: not connected (req=1)`

Sometimes I randomly being able to login, and when I do it, I don't see this error.

And lots of: `E/WindowManager: Unknown window type: 2617`

**Comment by ekager** [comment]
@daniluk4000 are you still seeing this on latest nightly?

**Comment by daniluk4000** [comment]
> 
> 
> @daniluk4000 are you still seeing this on latest nightly?

Hello! Authorization still opens in poor white window, but I'm able to view my passwords now. I have tried 20 times and not succeeded to reproduce the bug. 

If "poor white window" is a bug, and not a known one, I can open another ticket.
