### ISSUE TITLE
[Bug] Tracking protection not working properly on latest Beta build 3.0.0- beta.2

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#6967]
## Prerequisites
Have tracking protection turned on globally and set to Strict mode

## Steps to reproduce
1. Navigate to https://senglehardt.com/test/trackingprotection/test_pages/ and select one by one the featured test pages. 

### Expected behavior
Having ETP set to Strict Fenix should block content from loading, ads, analytics, social, cryptomining, fingerprinting

### Actual behavior
Nothing is blocked

### Device information

* Android device: Google Pixel 3a (Android 9), Xiaomi MiPad 2 (Android 5.1)
* Fenix version:  3.0.0-beta.2 Build #13390410 from 12/5 

### Notes
► **Standard mode is also affected** ❌
► Works on Fenix latest Nightly Build #13390609 from 12/5 ✔️
► Similar behavior as the one encountered approx. a month ago on 2.3.0-rc.1 from 28/10 [#6325](https://github.com/mozilla-mobile/fenix/issues/6325)

**Comment by Amejia481** [comment]
Tracking protection is working as expected is just the test pages that are not working correctly, go to www.ccn.com or any other sites and you will be able to see trackers getting blocked :) .

[The patch](https://bugzilla.mozilla.org/show_bug.cgi?id=1590788) that updates the list that geckoview uses for the test pages is not on GeckoView beta `"71.0.20191125115111"` that is the version that Fenix is using on beta/stable, for this reason the test pages works on nightly but not in beta also see https://github.com/mozilla-mobile/fenix/issues/6606#issuecomment-554384582.

**Comment by liuche** [comment]
@Amejia481 is there another way you'd suggest testing this, while those test cases are being updated?

(I pinged Se Yeon in that bug, so hopefully a fix will show up soon to the test pages.)

**Comment by AaronMT** [comment]
> @Amejia481 is there another way you'd suggest testing this, while those test cases are being updated?
> 
> (I pinged Se Yeon in that bug, so hopefully a fix will show up soon to the test pages.)

These pages are used in a couple mozilla projects https://github.com/mozilla/tracking-test

**Comment by AndiAJ** [comment]
Hi, actually I thought that this has to do with the AC Snapshot version.
I've checked the version on 3.0.0-beta.2 and it was listed as **25.0.0. 48b092bde** same as in the Nightly build.

► About Fenix Beta 3.0.0-beta.2 from 12/5
![image](https://user-images.githubusercontent.com/51314259/70306714-38d13700-1810-11ea-8f89-6dfd7592995b.png)

► About Fenix Nightly Build #13390609 from 12/5
![image](https://user-images.githubusercontent.com/51314259/70306860-8c438500-1810-11ea-892e-f9c9d1bcbff7.png)


Nevertheless,as per @Amejia481 & @AaronMT suggestions I've re-tested on 3.0.0-beta.3 and it seems to be working properly.

► Cnn.com & Theverge.com
![20191206_095804](https://user-images.githubusercontent.com/51314259/70308582-45578e80-1814-11ea-864a-e251a990abb9.gif)

► [Mozilla tracking test page](https://github.com/mozilla/tracking-test)
![20191206_103328](https://user-images.githubusercontent.com/51314259/70308664-6cae5b80-1814-11ea-97f1-9c860d9139b1.gif)

Many thanks for helping me out, and sorry if any inconvenience created. :relaxed:
I'll go ahead and close ticket.

**Comment by liuche** [comment]
@AndiAJ just to follow up here, Se Yeon has told me that the bug with the testing sites has been fixed! See bugzilla here: https://bugzilla.mozilla.org/show_bug.cgi?id=1590788

So I think that means you can start using those sites to test on again.
