### ISSUE TITLE
[Bug] Can't save custom engine with new name without changing the url

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#6968]
## Steps to reproduce
1. Go to Settings>Search>Add a custom search engine.
2. Tap the Edit option for the custom engine.
3. Change it's name. Tap Save.
### Expected behavior
Custom engine name is saved and returns to search engines list.
### Actual behavior
Can't edit and just the name, you need to change the URL too in order to apply the changes.
### Device information

* Android device: Nexus 5 (Android 6)
* Fenix version: Nightly 12/5, Beta 3.0.0

**Comment by mcarare** [comment]
Question for UX: Can we receive new xml assets for the search plugins? Or should we modify the images for the existing ones (we will still need images to encode them)? TY!

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** o **Fenix Beta 3.0.0-beta.3 from 12/5** using the following devices:
• Google Pixel 3a (Android 9)
• OnePlus A3 (Android 6.0.1)
• Motorola (Android 6.0.1)

► Video
![20191206_150707](https://user-images.githubusercontent.com/51314259/70325400-8e223e00-183a-11ea-9531-3e89ac59be31.gif)

**Comment by AndiAJ** [comment]
Seems to be reproducible when trying to edit the second time the custom search engine on **Fenix Beta 3.0.0-beta.3 from 12/5** using a Nexus 5 (Android 6.0.1) and a Motorola (Android 6.0.1)
Based on this I'll re-open the issue.

**Comment by AndiAJ** [comment]
Hi, **verified as fixed ** on the latest Nightly Build #13520613 from 12/18 using the following devices:

• Google Pixel 3a (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

► Video
![20191218_122519](https://user-images.githubusercontent.com/51314259/71087069-f7437300-21a3-11ea-9dca-27b3563904ad.gif)
