### ISSUE TITLE
[Bug]Flicker when you return to the Homescreen from History 

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#6969]
## Prerequisites
Have a couple of Open tabs
Have a couple of History items

## Steps to reproduce
From the Homescreen tap on the 3dot menu button
Tap on History
Tap the device back button (or upper left back button from History) 

### Expected behavior
No UX issues

### Actual behavior
Flicker when you exit the History screen - content shifts up right before homescreen is shown.

### Device information

* Android device: Google Pixel 3a (Android 9)

* Fenix version: 
• Beta 3.0.0-beta.2 Build #13390410 from 12/5
• Nightly Build #13390609 from 12/5

### Notes
► Video
![20191205_135050](https://user-images.githubusercontent.com/51314259/70234089-85f9ce00-1768-11ea-8cbf-0694f712fcdb.gif)

**Comment by boek** [comment]
@AndiAJ This may have

**Comment by boek** [comment]
We are no longer able to reproduce this issue.
