### ISSUE TITLE
[Bug]History and Bookmark icons flicker when using multi-select feature

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#6970]
## Prerequisites
Have a couple of History items

## Steps to reproduce
1. Tap the icon of the first listed history item
2. Tap the icon of the third listed history item
3. Tap the icon of the fifth listed history item

### Expected behavior
No UX issues regarding the icons of the history items that weren't selected.

### Actual behavior
The icons of the history items that weren't selected flicker.

### Device information

* Android device: Google Pixel 3a (Android 9)
* Fenix version: 
• Beta 3.0.0-beta.2 Build #13390410 from 12/5
• Nightly Build #13390609 from 12/5

### Notes
► Video
![20191205_141838](https://user-images.githubusercontent.com/51314259/70235173-06213300-176b-11ea-8ff1-1ad269b2d741.gif)

**Comment by s-ankur** [comment]
This also happens with other library items including bookmarks

**Comment by BMEduard** [comment]
While investigating this issue, I was unable to reproduce this bug on the latest master build with Samsung Galaxy S8 (Android 9).

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly Build 200624 from 6/24`** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)

► Video
![20200624-101732](https://user-images.githubusercontent.com/51314259/85514242-82df0600-b604-11ea-9a92-162c5edf6375.gif)
