### ISSUE TITLE
[Bug] Custom tab is not working on LG G7 fit (Android 8.1)

### ISSUE THREAD

**Issue by sv-sdeiac** [mozilla-mobile/fenix#6971]
## Steps to reproduce
1. Set Firefox Preview as the default browser.
2. Go to the Gmail app and tap on a link.

### Expected behavior
The tapped link should open in custom tab.

### Actual behavior
The tapped link opens in Firefox Preview app.

### Device information

* Android device: LG G7 fite (Android 8.1); 
* Fenix version: Nightly 12/4, Beta 3.0.0-beta.2 (12/5);
* Notes: 
- Not reproducible on Google Pixel 3A (Android 9) and Xiaomi MiPad 2 (Android 5.1) - x86 arch.
Gif:
![20191205_151754](https://user-images.githubusercontent.com/40264165/70238846-ccecc100-1772-11ea-8908-bf3b88f574d7.gif)

**Comment by sv-sdeiac** [comment]
Hello, after previous investigation I was not able to reproduce anymore the issue with the Firefox Preview Nightly 1/7 build #20070606.
The issue is still reproducible for the RC build of Firefox Preview 3.0.1 build #13502256.

**Comment by kbrosnan** [comment]
Since this is working on nightly lets close this.
