### ISSUE TITLE
[Bug] Pop-ups are not blocked

### ISSUE THREAD

**Issue by concastinator** [mozilla-mobile/fenix#6972]
## Steps to reproduce

Open any page that attempts to open pop-ups. Try http://www.popupcheck.com/advanced-pop-up-test.asp and http://www.popuptest.com/.

Fenix will present the message "Prevent this site from opening a pop-up window?" followed by the URL of the page and the buttons "DENY" and "ALLOW".

Press "DENY".

### Expected behavior

The pop-ups should be blocked.

### Actual behavior

If you take a look at the list of open tabs (or even at their counter at the bottom right), you will see that a new tab has been opened, corresponding to the pop-up that should have been blocked.

### Device information

* Android device: Nokia 5 (model TA-1024) with Android One version 9.
* Fenix version: 191205 06:01 (build 13390609)

**Comment by sipher123** [comment]
I have used https://webbrowsertools.com/popup-blocker/ of which is the recommended by the "pop-up blocker (strict)" add-on. Worrying that all forms of pop-ups are not being blocked at all in the 80.1.0-beta or 80.1.3. Stable releases are already out…
