### ISSUE TITLE
[Bug]Current Bookmark folder shouldn't be displayed as a root folder option while editing 

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#6974]
## Prerequisite
Have one Bookmarks folder created. (for e.g. folder A)

## Steps to reproduce
1. From the Bookmarks section tap the 3dot button to edit Bookmark folder A
2. While in edit mode, tap on the root folder
3. Check the displayed folder lists

### Expected behavior
Folder A should not be displayed

### Actual behavior
Folder A is actually displayed.

### Device information

* Android device: Google Pixel 3a (Android 9)
* Fenix version: 
• Beta 3.0.0-beta.2 Build #13390410 from 12/5
• Nightly Build #13390609 from 12/5

### Notes
► Video
![20191205_163630](https://user-images.githubusercontent.com/51314259/70246410-64a4dc00-1780-11ea-94d3-678d08dcb185.gif)

Seems that this inconsistency is causing: #6975 & #6977

**Comment by grigoryk** [comment]
This should have been fixed by https://github.com/mozilla-mobile/fenix/pull/15203

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly Build 200922`** using the following devices:
• Google Pixel 3a (Android 11)
• Huawei Mate 20 Lite (Android 10)
• OnePlus A3 (Android 6.0.1)
