### ISSUE TITLE
[Bug]Bookmarks folder can't be renamed (following #6974)

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#6975]
## Prerequisites
Have one Bookmarks folder created. (for e.g. folder Z)

## Steps to reproduce
1. From the Bookmarks section tap the 3dot button to edit Bookmark folder Z
2. While in edit mode, tap on the root folder
3. Tap and select folder Z
4. Tap back button to exit to the Bookmarks list
5 Tap the 3dot button to edit Bookmark folder Z
6. Change the folder name 
7. Tab the back button
8. Check if the folder was renamed

### Expected behavior
The folder should be renamed.

### Actual behavior
The folder isn't renamed.

### Device information

* Android device: Google Pixel 3a (Android 9)
* Fenix version: 
• Beta 3.0.0-beta.2 Build #13390410 from 12/5
• Nightly Build #13390609 from 12/5

### Notes
This seems to be caused by #6974 
► Video
![20191205_170807](https://user-images.githubusercontent.com/51314259/70248615-d3cfff80-1783-11ea-9b6d-fab9be509c35.gif)

**Comment by grigoryk** [comment]
This shouldn't be possible anymore following https://github.com/mozilla-mobile/fenix/pull/15203

**Comment by AndiAJ** [comment]
Hi @grigoryk , I've found another inconsistency and filled #15296 
I'll close this in favor of the new issue.
