### ISSUE TITLE
[wiki] nightly apk url on wiki home is outdated

### ISSUE THREAD

**Issue by leela52452** [mozilla-mobile/fenix#6987]
when i tapped nightly apk url it displays message **This deployment of Taskcluster has been shut down as of November 9.**.

i have cloned your repo and updated required changes in wiki as given in [gist](https://gist.github.com/larrybotha/10650410).

i dont have access to desktop or laptop, hence this issue.

my forked wiki repo with updated changes : https://github.com/leela52452/fenix.wiki.git

**Comment by AaronMT** [comment]
Thanks. I've corrected this.
