### ISSUE TITLE
[Bug] Can't install fennec-nightly on MIUI 11

### ISSUE THREAD

**Issue by lindongbin** [mozilla-mobile/fenix#6991]
![Screenshot_2019-12-06-15-08-58-820_com miui packa](https://user-images.githubusercontent.com/3154109/70306865-d9d8e580-1842-11ea-8864-5818dc29c6a6.JPG)

* Android device: 
Mi Note3 MIUI 11 Android 9
* Fenix version: 
https://firefox-ci-tc.services.mozilla.com/tasks/index/project.mobile.fenix.v2.fennec-nightly/latest

**Comment by AaronMT** [comment]
Did you enable installation from unknown sources on your phone? @lindongbin

**Comment by lindongbin** [comment]
> Did you enable installation from unknown sources on your phone? @lindongbin

latest version fixed
