### ISSUE TITLE
[Bug] Find in page bar hidden behind custom tab toolbar

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#6992]
## Steps to reproduce
1. Open a custom tab.
2. Open Find in page from the overflow menu.
3. Observe the Find in page toolbar is not visible.
### Expected behavior
Find in page bar is visible
### Actual behavior
Not visible, can't use the next/previous buttons.
### Device information

* Android device: Nexus 5 (Android 6.0.1)
* Fenix version: Nightly 12/6, 3.0.0-beta 2

**Comment by AndiAJ** [comment]
Hi, **still reproducible, the find in page bar isn't displayed** on the latest **Nightly Build #20060605 from 01/06** using the following devices:

• Google Pixel 3a (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

► Video
![20200106_085951](https://user-images.githubusercontent.com/51314259/71801290-2f332d00-3063-11ea-89d4-a27c77d95be5.gif)

**Comment by Baron-Severin** [comment]
This is likely the same problem as https://github.com/mozilla-mobile/fenix/issues/7184.  Let's make sure to test both cases when we fix.

**Comment by mcarare** [comment]
For UX: This is an easy fix, but I have a question: When toolbar is set to bottom, we hide it and show find in page bar. We do the same when toolbar is at top, even though they are not in the same place (find in page always displays at bottom). Should we keep this behaviour, or we should not hide toolbar when is at top? TY!

**Comment by topotropic** [comment]
> For UX: This is an easy fix, but I have a question: When toolbar is set to bottom, we hide it and show find in page bar. We do the same when toolbar is at top, even though they are not in the same place (find in page always displays at bottom). Should we keep this behaviour, or we should not hide toolbar when is at top? TY!

Yes, keep the behavior and hide the top address bar as well. Thanks!

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **Nightly Build #20100616 from 01/10** using the following devices:
• Google Pixel 3a (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

► Video 
![20200110_102905](https://user-images.githubusercontent.com/51314259/72139924-2e1e3a80-3398-11ea-97f1-ba645a0a7cbd.gif)

► Video PB
![20200110_105727](https://user-images.githubusercontent.com/51314259/72140058-8fdea480-3398-11ea-85df-3428e61ee841.gif)

Side:
#4587 is happening in custom tabs as well..
