### ISSUE TITLE
[Bug] Unclear what to do to complete editing a bookmark

### ISSUE THREAD

**Issue by Cheap-Skate** [mozilla-mobile/fenix#6996]
Navigate to a URL
Hit the 3 dot menu then "star" to bookmark the page
Hit the EDIT text in the toast message
I move to the edit bookmark screen

When I have completed the edit, what do I do??? There is no "Save bookmark" icon to tap. How do I save the edited bookmark?

The actual answer is press <- at the top left which is counter-intuitive, <- should undo the last action not save???

I suggest the options at the top of the screen should be CANCEL or SAVE as text or appropriate icons (eg tick/check mark).

**Comment by topotropic** [comment]
dupe of https://github.com/mozilla-mobile/fenix/issues/3813
