### ISSUE TITLE
[Telemetry] Inverted media usage event type pings from Open tabs section

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#7000]
## Steps to reproduce
1. Open Twitch.tv and play any video
2. Exit to the homescreen
3. Tap the pause button from the open tabs view
4. Tap the play button from the open tabs view

### Expected behavior
The "tab" & "media state" category event type pings should be properly correlated

### Actual behavior
When pressing pause a "media_play" "tab" category ping is generated and vice versa

### Device information

* Android device: Google Pixel 3a (Android 9)
* Fenix version: Fenix Nightly Build #13391806 from 12/5

### Notes
Discovered while checking [#5705](https://github.com/mozilla-mobile/fenix/issues/5705)

1. Tap **pause** from the Open tabs
"events": [
{
"category": "tab",
"name": "media_play",
"timestamp": 0
},
{
"category": "media_state",
"name": "pause",
"timestamp": 135
}
]

2. Tap **play** from the Open tabs
"events": [
{
"category": "tab",
"name": "media_pause",
"timestamp": 0
},
{
"category": "media_state",
"name": "play",
"timestamp": 127
}
]

**Comment by sblatz** [comment]
Good catch!

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **Nightly Build #13640626 from 12/30** using a Google Pixel 3a (Android 9)

✔️ Tap pause from the Open tabs - Ping **24826523-0859-48ac-acf6-b31752cc6a8a**
✔️ Tap play from the Open tabs - Ping **d987d473-bf01-49ac-a435-998fb7ce3343**

[Logcat](https://github.com/mozilla-mobile/fenix/files/4009574/PausePlayOpenTabs.txt)
[Glean dashboard](https://debug-ping-preview.firebaseapp.com/pings/aj-t301200)
