### ISSUE TITLE
[Bug] Back button is hard to see on light mode custom tab

### ISSUE THREAD

**Issue by Baron-Severin** [mozilla-mobile/fenix#7002]
## Steps to reproduce
- Select light theme
- Open custom tab

### Expected behavior
- Back button is easy to see

### Actual behavior
- Back button is difficult to see (offwhite on an offwhite background)

### Screenshot
<img width="468" alt="Screen Shot 2019-12-06 at 10 51 11 AM" src="https://user-images.githubusercontent.com/13170306/70347957-7f299480-1816-11ea-87b2-e53de5d9f1a2.png">

### Device information

* Android device: Pixel 2
* Fenix version: 9feb0480bf54037f564b83cbe16d39cf8a8facba (current head of master)

**Comment by KaairaGupta** [comment]
Can i work on this?
Also, since this is my first time with open source, can you please guide me with how to begin?

**Comment by Baron-Severin** [comment]
@KaairaGupta sure!  I'll assign you to the issue.

[The readme](https://github.com/mozilla-mobile/fenix#firefox-preview) covers some FAQs about contributing, and there's also a Slack link under `getting-involved` where you can reach us directly.  The basic process is that you'll want to fork the project, write a fix, push it up to your fork, then open a pull request into this repo.  If you have more specific questions feel free to ask (either here or on Slack) and we'll do our best to help!

**Comment by KaairaGupta** [comment]
@Baron-Severin is this problem only on the nexus device?
My device is RedmiK20 with android 9, and this is how it looks on it:
![light](https://user-images.githubusercontent.com/45488611/71543498-89fcc280-2999-11ea-868e-42bc91752786.jpeg)
![dark](https://user-images.githubusercontent.com/45488611/71543500-8cf7b300-2999-11ea-8851-2d77a41775c5.jpeg)

**Comment by KaairaGupta** [comment]
@Baron-Severin here is the screenshot. I am unable to reproduce the bug. It's working fine on my phone  
![mozzila](https://user-images.githubusercontent.com/45488611/71545656-f2589d80-29b3-11ea-8979-dab1be280634.jpeg)
model:RedmiK20

**Comment by Baron-Severin** [comment]
I'm not able to reproduce it anymore either @KaairaGupta, so I'm going to close the issue.  Thank you for looking into the problem, and I'm sorry there wasn't more there for you to do.  We have [a few more](https://github.com/mozilla-mobile/fenix/issues?q=is%3Aopen+no%3Aassignee+label%3A%22good+first+issue%22) good first issues if you would like to try tackling another one!
