### ISSUE TITLE
[Bug] Homescreen shortcuts disappeared in latest Nightly

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#7006]
## Steps to reproduce
I don't know if this is reproducible but I noticed all my homescreen shortcuts were gone this morning.

This is very destructive to user data: is it possible to **write a regression test to prevent this from happening again?**

### Device information

* Android device: Pixel 2
* Fenix version: Nightly 191205

**Comment by kbrosnan** [comment]
Wontfix. This is fallout from #4976
