### ISSUE TITLE
[Bug] Long tap on images, share not working as expected

### ISSUE THREAD

**Issue by nullvalue1** [mozilla-mobile/fenix#7016]
## Steps to reproduce
On a Samsung S10 device, in the Nightly/Preview build perform a Google Image Search. Long tap on an image. Surrounding text and image is selected, as if it doesn't see the image but thinks you are just selecting text. 

In the current release version of Android Firefox, a popup does appear which allows you to share. However when sharing with Gmail it attaches the image as a .bin file. When sharing with SMS, it places a bunch of (what looks like) base64 data in the message box. This works as would expect on my previous device (Samsung S7) but fails on the S10.

### Expected behavior
A popup menu should appear, allowing you to share the image in other apps (SMS, gmail, email) and treats or like an actual image object.

### Actual behavior
Selection is treated like text or encoded data, rather than an image object.

### Device information
Samsung S10

### Why this is important
I'm converting my wife from Chrome to Firefox, but she needs to be able to share dank memes.

**Comment by ekager** [comment]
That does sound important! We want everyone to be able to share dank memes easily :) 

AC work tracked by https://github.com/mozilla-mobile/android-components/issues/3648

**Comment by ekager** [comment]
Closing for #7458
