### ISSUE TITLE
[Bug] Cannot display full web page

### ISSUE THREAD

**Issue by lindongbin** [mozilla-mobile/fenix#7022]
https://imgur.com/dg6mPaH

Occurs sometimes, it cannot be reproduced 100%, it will be displayed after zooming

* Android device: ?
* Fenix version: latest nightly

**Comment by boek** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1610965

**Comment by boek** [comment]
@lindongbin What device are you experiencing this on?

**Comment by lindongbin** [comment]
> 
> 
> @lindongbin What device are you experiencing this on?

Mi Note3
It happened when webrender disabled

**Comment by fluffyemily** [comment]
Needs confirmation that issue is no longer present.

**Comment by lindongbin** [comment]
fixed on release 85.1.1
