### ISSUE TITLE
[Bug] "Start browsing" from the onboarding tour is not responding

### ISSUE THREAD

**Issue by softvision-miralobontiu** [mozilla-mobile/fenix#7026]
## Steps to reproduce
1. Make sure you have a clean profile.
2. Open Fenix and scroll to the "Start browsing" button and tap on it.

### Expected behavior
The search page is opened.

### Actual behavior
The page jumps and takes the user to the top of the onboarding page.

### Device information
* Android device: Samsung Galaxy Tab S3 (Android 8), Nexus 6P (Android 8.1), Huawei P9 Lite (Android 7), Nexus 5 (Android 6), Google Pixel 3 (Android Q)
* Fenix version: 191209 (#13430607)

![20191209_121248_Trim](https://user-images.githubusercontent.com/40694158/70427870-2ceaac80-1a7e-11ea-83ef-992a04a800b6.gif)

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **Nightly Build #13440604 from 12/10** using the following devices:
• Google Pixel 3a XL (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

►Video
![20191210_090347](https://user-images.githubusercontent.com/51314259/70503839-06d01580-1b2d-11ea-9773-16348396d7d8.gif)

**Comment by AndiAJ** [comment]
Reproducible on **Fenix 3.0.2 Build #20081833** from 1/8 using a OnePlus A3 (Android 6)
