### ISSUE TITLE
[Bug] Ambiguous button name "Start browsing"

### ISSUE THREAD

**Issue by mcarare** [mozilla-mobile/fenix#7029]
After pressing "Start browsing", Onboarding cards disappear, but no other action is taken.
Shouldn't "Start browsing" also trigger another action, like opening a new tab or selecting search field?

**Comment by brampitoyo** [comment]
Since @apbitner is working on onboarding, I’m paging him for advice.

My initial assessment:

- It’s fine for “Start browsing” to show about:newtab without triggering any other action
- Showing about:newtab will allow users to check out places other than search, like Private Browsing

**Comment by apbitner** [comment]
The original onboarding spec took the user to the search screen - https://share.goabstract.com/d61d05c2-de61-49c3-a839-42495393e2b7?

@boek do you know if it was implemented this way or if this is a new bug?

**Comment by boek** [comment]
I can't remember! But it's a bug so lets fix it :D

**Comment by topotropic** [comment]
@boek I re-installed Fenix Preview (3.0.1) and when I tap on "Start browsing" it stays on home, scrolls to top, keeps all the onboarding cards, doesn't do anything else, doesn't got to search as spec'd out here https://github.com/mozilla-mobile/fenix/issues/7029#issuecomment-564218727. Looks like a bug.

**Comment by sv-ohorvath** [comment]
- Verified on v3.2-beta1.
- Verified with TalkBack, logged one new issue: #7851 
- Devices: Pixel 3 (Android 10), Galaxy Note 8 (Android 9)
