### ISSUE TITLE
[Bug] The Private Browsing shortcut icon should be changed

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/fenix#7033]
## Steps to reproduce
1. Launch Fenix.
2. Reach the settings menu.
3. Tap on `Add private browsing shortcut`.
4. Observe the PB icon.
### Expected behavior
The PB shortcut icon should be PNG with an invisible background.
### Actual behavior
The PB shortcut icon is displayed with a white background.
### Device information

* Android device: **Google Pixel 3a XL(Android 10), OnePlus 6T(Android 9)**
* Fenix version: **Latest Nightly 12/9.**

### Notes
Note that when adding the PB shortcut icon to the home screen it's displayed correctly.
Also, note that the example icon is different from the icon on the home screen.
>Actual
![Screenshot_20191209-162832 (1)](https://user-images.githubusercontent.com/42831109/70446820-591a2380-1aa6-11ea-9486-7385d06d491d.png)

>Expected
![Screenshot_20191209-162832 (1)](https://user-images.githubusercontent.com/42831109/70447495-7a2f4400-1aa7-11ea-983d-5874ea74386b.png)

**Comment by boek** [comment]
I don't think this is something we can fix 😢

**Comment by boek** [comment]
Yeah, this is controlled by the system. Closing it as CANTFIX
