### ISSUE TITLE
Fenix startup time increases with the number of open tabs

### ISSUE THREAD

**Issue by hawkinsw** [mozilla-mobile/fenix#7035]
### Why/User Benefit/User Problem
The more tabs that a user carries over between browser sessions, the longer it takes to start Fenix. As evidence of this behavior, consider the following two graphs:

![launchtimes2](https://user-images.githubusercontent.com/8715530/70368118-1a515700-1875-11ea-83e8-1f6fe8f7e666.png)
![launchtimes](https://user-images.githubusercontent.com/8715530/70368119-1a515700-1875-11ea-8f78-9d01fce626b8.png)

Along the y axis are start times and along the x axis are the number of open tabs restored from a previous browser session. 

### Impact
For a user who keeps a large number of open tabs, this means an unacceptable user experience.

### Acceptance Criteria (how do I know when I’m done?)
Startup time will remain constant no matter how many open tabs are carried over between sessions.

**Comment by mcomella** [comment]
Triage: we need to know how many tabs users keep open to prioritize. @ecsmyth is getting numbers for this in https://github.com/mozilla-mobile/fenix/issues/7191#issuecomment-566248848

**Comment by mcomella** [comment]
Action item: determine how bad this is on the G5 (e.g. by taking a run with no tabs, 10 tabs, 20 tabs, 50 tabs, 100 tabs and comparing). If it's bad, consult team and prioritize accordingly.

**Comment by mcomella** [comment]
Note: tabs are not currently instrumented in fenix startup so, assuming it has no impact on Displayed time, we may not be able to measure until https://github.com/mozilla-mobile/fenix/issues/7781 lands – in our experience, top sites will always load after tabs so by instrumented top sites, we'll be able to observe the difference on tabs from "fully drawn" time

**Comment by MarcLeclair** [comment]
As of early March, with all the changes we've had, this is what I've noticed on a G5+ with 10 runs for each # of tabs:
![image](https://user-images.githubusercontent.com/16614353/76340774-827b6300-62d2-11ea-8087-f34a328fdf42.png)

As of now, I think we should focus on the weird spike that can be seen when the first tab is opened.
