### ISSUE TITLE
[Bug] Search bar allows text stylization from copied HTML

### ISSUE THREAD

**Issue by cpeterso** [mozilla-mobile/fenix#7037]
This bug was originally reported for Fennec (https://bugzilla.mozilla.org/show_bug.cgi?id=1602238), but it also affects Fenix and R-B.

## Steps to reproduce

1.  Copy a HTML with stylization made with HTML tags:
`<h1><u><font size="1px" face="monospace" color="green">hello<br><br><br>copy me!</font></u></h1>`
2. Paste it in Fenix's address bar.

### Expected behavior

The text should be pasted as plain text (a option that Android give when trying to paste the copied text in the search bar) by default, just like the alternative browser do.

### Actual behavior

Paulo reports: "The search bar text is styled. I noticed it when copying/pasting a Wikipedia title. Then I tried some HTML tags to see what can be done using it. The result I had (attached in the screenshot) have a green text with an underline with the "monospace" font and a broke suggestion (by `<br>` tags)."

https://bug1602238.bmoattachments.org/attachment.cgi?id=9114374
![image](https://user-images.githubusercontent.com/629193/70463270-6ec12600-1a71-11ea-9f75-2d7bd5777c47.png)

### Device information

* Android device: ?
* Fenix version: Firefox Preview 2.3.0 (Build # 13031728) with GeckoView (70.0-20191014032640) and Reference Browser 1.0.1950 (Build #13431207) with GeckoView 72.0a1-20191202091209.

**Comment by ekager** [comment]
Related to but slightly different https://github.com/mozilla-mobile/fenix/issues/1833

**Comment by kbrosnan** [comment]
This is a duplicate
