### ISSUE TITLE
Setting to request desktop sites by default

### ISSUE THREAD

**Issue by PyvesB** [mozilla-mobile/fenix#7039]
_This issue is similar to #5725, #5471 and #5761. However, those three issues were confusingly created by the same user, are lacking a lot of detail and are quite poorly written. I'm hoping to start a discussion on a clean slate._

### Why/User Benefit/User Problem

With mobile screens getting larger and connectivity speeds improving, I've increasingly been wanting to use desktop versions of most websites I visit. Additionally, some mobile sites simply don't work properly or are missing content, observations echoed in #233.

"Always request desktop mode" was a popular feature requested for the old Android browser, Fennec. See [Bug 790954](https://bugzilla.mozilla.org/show_bug.cgi?id=790954) and at least half a dozen other ones. It led to quite a lot of discussions at the time, and as far as I can tell from the Play Store reviews, it's still something that is requested regularly nowadays.

There used to be an extension for this, [desktop-by-default](https://addons.mozilla.org/android/addon/desktop-by-default), but it no longer exists.

### What/Requirements

Two potential solutions were discussed for Fennec:
* saving the preference on a per website basis. This proved hard due to redirections amongst other problems (see [this comment](https://bugzilla.mozilla.org/show_bug.cgi?id=790954#c15)). It was dismissed.
* a global setting allowing users to load desktop versions of websites by default. This seems to have been the preferred solution, but was never implemented (maybe because extensions provided this back then?).

### Acceptance Criteria (how do I know when I’m done?)

Based on past discussions, I'm suggesting to add a global setting "Request desktop sites by default", possibly in the _Accessibility_ section. Would this be an acceptable approach?

I may be able to give this a shot and contribute a PR once we agree on a solution.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-14685)

**Comment by Imerion** [comment]
Agreed this is a very important feature. Definitely the main thing I would look for on a smartphone browser, for many reasons. It really needs to be possible to set it as default though. Saving for each site would be cumbersome and result in loads of reloads and menu presses as many pages when browsing around are only visited once.

**Comment by Imerion** [comment]
For reference, the browser Brave has a very good and useful implementation of this.

**Comment by lindongbin** [comment]
https://www.reddit.com/r/firefox/search/?q=desktop%20site&restrict_sr=1

**Comment by notJerl** [comment]
I pretty much *never* want the mobile version of a site.  I was able to avoid 100% of them in Fennec by changing general.useragent.override to a current desktop Firefox useragent and layout.css.devPixelsPerPx to set a suitable viewport to disable all adaptive mobile sites I ran into.  Having to tap the desktop site slider every time I open a tab or migrate to a new domain is going to get annoying very quickly.

**Comment by Imerion** [comment]
@notJerl Wow, that worked! Awesome! I can even set layout.css.devPixelsPerPx so low I don't get hamburger menus on pages where the normal manual-toggle desktop mode still forces them on me. Now for a options menu setting for this and all will be well!

**Comment by notJerl** [comment]
Chances are they won't put in an options menu setting for devPixelsPerPx, since it's a setting whose usable value range varies wildly across different devices and they have no way of knowing for sure that users aren't going to accidentally make their about:config too small to use.  There's a chance that they'll expose the useragent switcher as an "always request desktop versions of sites" toggle, and it's possible that they'd expose browser.viewport.desktopWidth, which behaves in a similar (but not quite the same) way to change the size when requesting desktop sites, which would hopefully be always be applied with the aforementioned toggle, but devPixelsPerPx is one of those where users can make their browser unusable, especially if they don't toggle on always allowing pinch zooming first.

**Comment by Imerion** [comment]
@notJerl Yep, it doesn't need to be that specific setting. An option that combines a desktop user agent with browser.viewport.desktopWidth should suffice. That is, just an option to have that existing temporary toggle active at all times.

**Comment by CalcProgrammer1** [comment]
Throwing in my support for this issue.  I had user agent switcher installed on the old Firefox for Android and never had issues with annoying mobile sites.  Now this unfinished beta release is pushed out without full addon support and I have to constantly click the Desktop Page toggle, which infuriatingly does not save, to see the non-garbage versions of many sites.  Why was this released without a good way to change the user agent to something useful?  I really like the new Firefox otherwise, but it's horrible if it keeps defaulting to mobile sites.

**Comment by mzso** [comment]
[**@notJerl**](https://github.com/notJerl) commented on [2020. júl. 30. 09:26 CEST](https://github.com/mozilla-mobile/fenix/issues/7039#issuecomment-666187071 "2020-07-30T07:26:59Z - Replied by Github Reply Comments"):
> I pretty much _never_ want the mobile version of a site. I was able to avoid 100% of them in Fennec by changing general.useragent.override to a current desktop Firefox useragent and layout.css.devPixelsPerPx to set a suitable viewport to disable all adaptive mobile sites I ran into. Having to tap the desktop site slider every time I open a tab or migrate to a new domain is going to get annoying very quickly.

On 68.11 it doesn't work for me with google. Somehow the website can still tell.

**Comment by PeterKW** [comment]
I ended up adding the UA extension to my Android Collection to pretend to be a desktop device for the equivalent result of desktop mode.
https://addons.mozilla.org/en-GB/firefox/addon/user-agent-string-switcher/  
Seems to be working quite well 🙂

**Comment by notJerl** [comment]
If you're using Nightly to be able to use a custom collection, you might as well just change your useragent in `about:config`

**Comment by KOLANICH** [comment]
AFAIK it won't change the viewport and other CSS-related stuff, will it?

**Comment by Imerion** [comment]
No, for that you need to change the "layout.css.devPixelsPerPx" setting in about:config. In regular Firefox for mobile that can't be accessed, but in forks like IceRaven it works great. If I set it to 1.06 I don't get a single stupid mobile layout (on my phone at least, the settings might vary) and instead get full wide pages where I can have a total overview. It even works better than the temporary desktop mode Firefox has today, which isn't wide enough and rather gives a tablet-view than a desktop one.

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807150

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
