### ISSUE TITLE
Discourage the use of the default Coroutine Dispatcher

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#7040]
### What
From Colin on Slack:

> I think it would be valuable to enforce a blanket restriction on the use of Kotlin coroutines Dispatchers.Default in our projects. I had to clean up a mess earlier where older phones with only two CPUs would freeze for over five seconds because too much dependent work ended up queued in the pool. I intend to write a blog about this soon, but the idea is simply: Dispatchers.Default is intended only for CPU-bound work which needs one thread per CPU. The problems are that: 1. The oldest, cheapest devices end up with an impractically-small pool which leads to deadlocks. 2. Having it as a default of sorts implies that it's okay to put I/O bound work there. 3. When work is truly CPU-bound, it should ideally have its own thread pool to avoid contention with other processes.

Colin suggests we write a lint rule to prevent this.

### Impact
If we don't do this, users on older devices may run into performance issues that are not reproducible on developer devices and thus likely to get closed.

This is likely to impact areas where we dispatch a large number of jobs, such as **startup**.

### Acceptance criteria
- Developers are discouraged from using the default dispatcher

**Comment by boek** [comment]
Could we add a lint rule for this?

**Comment by mcomella** [comment]
> Could we add a lint rule for this?

FYI: I'm not sure how challenging it is to integrate with our existing linters but it's fairly easy to spin up a gradle task that runs a shell script to accomplish the same task. Here's [an example](https://github.com/mozilla-mobile/firefox-echo-show/blob/699e47a96326ed50f1cfdb3b13bb999308d09838/buildSrc/src/main/kotlin/org/mozilla/gradle/tasks/VerifyWebViewCount.kt#L35) I wrote for FFES.

**Comment by mcomella** [comment]
Tracking on JIRA: https://jira.mozilla.com/browse/FXP-1262
