### ISSUE TITLE
Opening history items and bookmarks doesn't respect current mode

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#7041]
If you're in private mode and open links, they will open in normal mode. 

Reported in https://github.com/mozilla-mobile/fenix/issues/6472#issuecomment-563400287

**Comment by shahsurajk** [comment]
Can i try this?

**Comment by NotWoods** [comment]
Go for it!

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **Nightly Build #13580607 from 12/24** using the following devices:
• Google Pixel 3a (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

► Video
![20191224_103442](https://user-images.githubusercontent.com/51314259/71404134-67397980-263a-11ea-8b7c-5ecf33b4f88f.gif)
