### ISSUE TITLE
[Bug] Cannot be smoothly zoomed when focus in search box

### ISSUE THREAD

**Issue by lindongbin** [mozilla-mobile/fenix#7042]
https://imgur.com/bJ0GGCI

* Android device: ?
* Fenix version: latest nightlt

**Comment by lindongbin** [comment]
https://imgur.com/Kkx1SZw

**Comment by boek** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1610960

**Comment by fluffyemily** [comment]
@boek in [this comment](https://bugzilla.mozilla.org/show_bug.cgi?id=1610968#c1) @snorp suggests that you try `CompositorController.setClearColor()` that we expose through GV. Did you give that a try?
