### ISSUE TITLE
Migrate from deprecated NetworkInfo

### ISSUE THREAD

**Issue by NotWoods** [mozilla-mobile/fenix#7048]
[`NetworkInfo`](https://developer.android.com/reference/kotlin/android/net/NetworkInfo) is deprecated in Android Q so we should migrate away from it. Currently its used in `AppRequestInterceptor` and `ShareViewModel`.

Meta: #7047

**Comment by shahsurajk** [comment]
I can pick this up.

**Comment by shahsurajk** [comment]
Would be good to have tests for the same. Filling #7316
