### ISSUE TITLE
Homescreen context menu text is cut off

### ISSUE THREAD

**Issue by liuche** [mozilla-mobile/fenix#7049]
Seems like the context menu could be too narrow. Some menu items may be confusing because they are truncated (even in English, like "Add to homescreen").

| Text      | Type       | Displayed ok?       |
| ------------- |:-------------:|:-------------:|
| Save to collection     | **XA and XB** |  ❌     |
|  Delete collection  | **XA and XB**    |  ❌    |  
| What's new | **XA and XB**     |   ❌|
| Open new tab(from bookmarks menu) | **XA and XB**     |   ❌|
|  Desktop site, Add to home screen(3 dot menu) | **XA and XB**     |  ❌|
|   Report site issue, Save to Collection(3 dot menu) | **XA and XB**     |   ❌|

![Screenshot_20191209-171511](https://user-images.githubusercontent.com/1082253/70486780-e7db7000-1aa7-11ea-924d-e00c9045b61e.png)

 - While a tab is open, tap on 3 dot menu, the `Save to collection` spills out of its designated area.

![Screenshot_20191008-122641](https://user-images.githubusercontent.com/42831109/66391494-f5a44480-e9d5-11e9-8f01-cd703d24f153.png)

 - When trying to delete a collection the text spills out of its designated area.
![Screenshot_20191008-122722](https://user-images.githubusercontent.com/42831109/66391565-1e2c3e80-e9d6-11e9-98f4-f7bfcf5567b4.png)

 - Tap on 3 dot menu and the `What's New` text spills out of its designated area.
![Screenshot_20191008-122729](https://user-images.githubusercontent.com/42831109/66391636-487dfc00-e9d6-11e9-97bc-9c1d90a3d415.png)

Copying from #3355

**Comment by liuche** [comment]
@mheubusch what should we do about strings that are too long, even in English? Can we get a different string, or is this something for UX to handle? In this case, the Add to Homescreen text looks like "Add to Home scr..."

**Comment by sblatz** [comment]
This will be fixed when we implement https://github.com/mozilla-mobile/fenix/issues/7157. I'm going to try to get this prioritized in AC sprint planning :)

**Comment by boek** [comment]
Waiting on the fix that will land in #7157
