### ISSUE TITLE
[Bug] TP Settings header text gets ellipsized/cut off

### ISSUE THREAD

**Issue by liuche** [mozilla-mobile/fenix#7051]
Header text for Tracking Protection Settings is too long, even in english.

![Screenshot_20191008-142143](https://user-images.githubusercontent.com/42831109/66392469-9d227680-e9d8-11e9-99e5-6bf6219f8c87.png)

From #3355

**Comment by ekager** [comment]
We made a decision in https://github.com/mozilla-mobile/fenix/issues/4778 that we don't care about this because the user has context from previous screen
