### ISSUE TITLE
[Bug] Private Browsing mode shortcut text cut off

### ISSUE THREAD

**Issue by liuche** [mozilla-mobile/fenix#7052]
Add PB mode shortcut text is cut off, even in English. This is probably worse in other languages.

![Screenshot_20191209-172405](https://user-images.githubusercontent.com/1082253/70487051-dcd50f80-1aa8-11ea-9288-6eab9b9534e0.png)

from #3355

**Comment by ekager** [comment]
I think the system handles this dialog so unless we want to change the name of the shortcut, I'm not sure there's anything we can do here

**Comment by mcarare** [comment]
@liuche This could be fixed only if we implement a custom shortcut activity. We don't have any control on the placement (see #7114) or sizes in the system shortcut dialog. Though I haven't seen many apps to implement a custom shortcut dialog and I don't know if it is worth the work. Maybe this should be decided by product/UX.

**Comment by AmyYLee** [comment]
> @liuche This could be fixed only if we implement a custom shortcut activity. We don't have any control on the placement (see #7114) or sizes in the system shortcut dialog. Though I haven't seen many apps to implement a custom shortcut dialog and I don't know if it is worth the work. Maybe this should be decided by product/UX.

I don't think it's worth making a custom shortcut dialog to solve for strings in this context.

**Comment by liuche** [comment]
All right, I think that's fine, let's just keep it the way it is then. I'm sure other apps have this problem too.
