### ISSUE TITLE
Support 4.4.4 Kit-Kat

### ISSUE THREAD

**Issue by KOLANICH** [mozilla-mobile/fenix#7053]
### Why/User Benefit/User Problem

It is impossible to update some devices to Lollypop.

### What/Requirements

Support Android 4.4.4 Kit-Kat.

### Acceptance Criteria (how do I know when I’m done?)

Should work on Kit-Kat.

**Comment by cadeyrn** [comment]
Duplicate of #2100.

**Comment by abodea** [comment]
Thanks @cadeyrn closing it accordingly.
