### ISSUE TITLE
[Bug] Videos on bbc.com don't start with ETP on

### ISSUE THREAD

**Issue by softvision-miralobontiu** [mozilla-mobile/fenix#7055]
Meta #6375

## Steps to reproduce
1. Go to bbc.com to an article that contains a video.
2. Start the video.

### Expected behavior
The video starts.

### Actual behavior
The video loads without starting. when turning ETP off, the video starts. I had two scenarios: the first, I had about 27 tabs opened, the second, I had a clean profile.

### Device information
* Android device: Samsung Galaxy Tab S3 (Android 8)
* Fenix version: 12/09 Nightly build

**Comment by ekager** [comment]
Just tried to reproduce on this article and wondering if it has been fixed https://www.bbc.com/news/world-us-canada-52821090

**Comment by softvision-miralobontiu** [comment]
Verified as fixed on the latest Nightly build from 5/29 with:
* Samsung Galaxy Tab A6 (Android 5.1.1),
* OnePlus 5T (Android 9),
* Google Pixel (Android 10), and
* Sony Xperia Z5 Premium (Android 7.1.1).
