### ISSUE TITLE
[Bug] Intelligent Scan is still displayed as the unlock method even if it's deactivated

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/fenix#7057]
## Preconditions
Intelligent scan(Face recognition + Iris unlocking methods should be on).
## Steps to reproduce
1. Launch Fenix.
2. Login with valid credentials.
3. Multitask to device settings and deactivate the Intelligent scan(unlock the phone using combined face and iris scanning)
4. Reach the settings menu.
5. Tap on the `Passwords` section.
6. Tap on the `Saved Logins` in order to unlock the section with Face recognition.
### Expected behavior
The face recognition unlocks method is displayed as the first unlock method.
### Actual behavior
 Intelligent Scan is still displayed as an unlock method even if it is deactivated.
### Device information

* Android device: **Samsung Galaxy Note 9(Android 8.1.0), Samsung Galaxy Note 9(Android 9)**
* Fenix version: **Latest Nightly 12/10.**

### Notes
The issue is only for the devices with an[ Iris scanner available.](https://webcusp.com/list-of-all-eye-scanner-iris-retina-recognition-smartphones/)
While having iris scanning as unlock method I was able to unlock the device with face recognition.
[video](https://drive.google.com/file/d/1s2aUBQmuUfiHrLveP4L-dLxXi2PgrB54/view?usp=sharing)

**Comment by softvision-miralobontiu** [comment]
This issue is no longer reproducible.
Tested on the 12/16 Nightly build with Samsung Galaxy S10+ (Android 10), and Samsung Galaxy Note 8 (Android 9).
