### ISSUE TITLE
[Bug] Search engines(and settings) cannot be accessed in landscape mode if there is a link copied to the clipboard

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/fenix#7059]
## Steps to reproduce
1. Copy any link.
2. Launch Fenix and access PB mode.
3. Tap on the URL bar.
4. Rotate the device in landscape mode.
### Expected behavior
There should be a dismiss button for the `Fill link from clipboard` or the section should be scrollable.
### Actual behavior
The Search engines(and settings) cannot be accessed in landscape mode if there is a link copied to the clipboard.
### Device information

* Android device: **Google Pixel 3a XL(Android 10).**
* Fenix version: **Latest Nightly 12/10.**

![ezgif-6-0abb972da177](https://user-images.githubusercontent.com/42831109/70537155-afe83180-1b68-11ea-8e12-f76f3ae12ea3.gif)

### Design Work

- [x] Request for Comments from UX team
- [ ] ~Usability testing if a new pattern or potentially confusing UI~ Not required – it’s a bugfix
- [x] Request for Comments from Fenix team and/or A/C, GV, Sync, etc as needed
- [x] Interaction details included
- [x] Accessibility ~- is this a review by someone,~ just keeping it in mind?
- [ ] ~For existing UI changes, deltas are highlighted~ No UI – this is a behaviour change
- the[ ] ~Strings/content reviewed and approved~ No string – this is a behaviour change
    - [ ] ~Are they too long for the component in other locales~

### Deliverable

- [ ] ~Assets uploaded to Google Drive~
- [ ] ~Links to deliverables (spec, assets) posted in comment 0~

### Deliverable Links

- ~User flow: (link to e.g. Abstract artboard, LucidChart, Whimsical, Miro, etc.)~
- ~Spec: (link to e.g. Abstract artboards)~
- ~Assets: (link to Google Drive folder)~

### Behaviours

**Make the search results scrollable**. This will allow users to scroll down in order to access the rest of the items in the search screen.

**Comment by mcarare** [comment]
Should we add a close button or a dismiss button. IMO a close button should to the trick, without cluttering the view.

**Comment by brampitoyo** [comment]
@mcarare I think that the solution is to allow users to scroll down in order to access the rest of the menu items. What do you think?

I’m aware that this issue may conflict with #6666. The keyboard should still _not_ be dismissable, even on landscape orientation. If users can scroll down, it will allow others items on the search page to be accessible _without_ dismissing the keyboard.

**Comment by mcarare** [comment]
@brampitoyo I understand your proposal, and I think it is the best approach, because there are too many items in that screen to keep it static.
Just a note: the hiding keyboard behaviour is intentional, requested in https://github.com/mozilla-mobile/fenix/issues/1211.

**Comment by brampitoyo** [comment]
@mcarare Great. Then let’s allow users to scroll down this page.

The keyboard should still be hidden, as decided in #1211. #6666 will respect that decision, and propose another solution.

**Comment by darkwing** [comment]
The pull request by @hackertronix was meant to fix this issue but I cannot scroll in horizontal with a copied link on my Pixel 4.  @kglazko Can you test this with your device to see if you can reproduce?

**Comment by kglazko** [comment]
For reference, the PR is here and is still open:  https://github.com/mozilla-mobile/fenix/pull/7339

**Comment by Diana-Rus** [comment]
Hi verified issue on Firefox preview Nightly 200331 (Build #20910606) with Google Pixel 3 XL (Android 9), Samsung Galaxy S9 (Android 8) and Sony Xperia Z5 (Android 7)
Verified the issue in both normal and private mode with a copied link and without "Fill link from clipboard" option:
- The section is scrollable, the available search engines and "Search engine settings" can be accessed
- Suggestions are shown
- No issue encountered after enable/disable the "Shortcuts" option.
- No issue encountered after adding a new search engine nor after removal of searched engines.

GIF:
![20200331-145602](https://user-images.githubusercontent.com/49859863/78026470-5d739080-7364-11ea-98e6-583716d21136.gif)

Note:
There is a minor regression problem about overlapping elements for which i am going to create a different issue.
