### ISSUE TITLE
[Bug] Home bottom bar layout is extended when rotating the device in landscape mode

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/fenix#7063]
## Steps to reproduce
1. Launch Fenix.
2. While the home screen is displayed, rotate the device to the right in landscape mode.

### Expected behavior
The Home bottom bar remains at the same size.
### Actual behavior
Home bottom bar layout is extended when rotating the device in landscape
### Device information

* Android device: **Samsung Galaxy S10+(Android 9).**
* Fenix version: **Latest Nightly 12/10.**

### Notes
This issue is specific for the devices with a notch/camera on the top.

![ezgif-6-fd250d518d09](https://user-images.githubusercontent.com/42831109/70545996-25f39500-1b77-11ea-8d8c-7033e089aa0e.gif)

**Comment by mcarare** [comment]
Closed by reverting the fullscreen home: #7152
