### ISSUE TITLE
[Settings] Improve layout consistency across settings screens

### ISSUE THREAD

**Issue by AmyYLee** [mozilla-mobile/fenix#7065]
Looking at our settings screens there are some inconsistency with alignments (mostly how we left align body copy).

Layout edits: https://share.goabstract.com/54f2c91a-46b3-4658-bd81-91c73a5c3ca4?mode=design&sha=db55e95ad5e27dbb1a5ad787a091fb7b60b5b416

**Comment by liuche** [comment]
Ask @brampitoyo for UI review (since Bram will be taking over for Settings)

**Comment by brampitoyo** [comment]
@liuche Just to be aware that we’re also improving layout consistency of Add-ons Manager and its sub-pages in #8520.

**Comment by hakkikaancaliskan** [comment]
@brampitoyo Comparing with specs a little hard. Could you please point me where is the problems?

**Comment by hakkikaancaliskan** [comment]
@brampitoyo could you please share settings -> search ux mock. I can't see widths and margins etc with this one.
https://app.abstract.com/share/54f2c91a-46b3-4658-bd81-91c73a5c3ca4?mode=design&selected=root-7DABD5EE-63A3-4045-B948-6E46E62D6136&sha=dd9e41fa2585a001a7311514820066f6527db6fd

**Comment by brampitoyo** [comment]
@hakkikaancaliskan I completed the layout edits for all sub-pages under the sections “Account” and “General”.

https://share.goabstract.com/2e7f2625-24e4-41e9-bb9b-5e78c31dbbbe?mode=design&sha=62825ec262f4d071a8acae25bec9180f84bf4d3d

I will finish the rest of the pages under the sections “Privacy and security”, “Advanced” and “About”. But note that all my fixes follow practically the same guideline: **all list items have a keyline value of 72dp**.

At the moment, you’ll note that our list items sometimes follow the keyline, and they sometimes don’t. Ideally, they all should.

Demonstration:

<img src="https://lh3.googleusercontent.com/Z4ViFg5sBrSdePmPokknAZWzG3-NKHnSf5EpbIP4JCj9wkvF2B6JwQ2ZKa3QFcpWjWmI1Sh0pEUNK8FfW_eDJVz_JWYmyPQVGC1t5Q=w1064-v0">

For further information, follow this link https://material.io/design/layout/spacing-methods.html#spacing and search for "keylines".

**Comment by hakkikaancaliskan** [comment]
@brampitoyo There is just https://github.com/mozilla-mobile/fenix/pull/12691 left. I think we can close this issue after you check everything again.

**Comment by hakkikaancaliskan** [comment]
@brampitoyo Everything done.

**Comment by brampitoyo** [comment]
@hakkikaancaliskan I just finished reviewing #12691. Looks like our settings alignment work is all complete!

**Comment by hakkikaancaliskan** [comment]
@NotWoods this issue is done
