### ISSUE TITLE
Space below show search suggestions in private sessions feels a bit cramped

### ISSUE THREAD

**Issue by mcarare** [mozilla-mobile/fenix#7066]
![Screenshot_20191210-103724_Firefox Nightly](https://user-images.githubusercontent.com/8226605/70543929-3a18a180-1b39-11ea-93f4-1f804e8600ef.jpg)
(Uncropped screenshot, scrolled down as far as I could)
Ive noticed the spacing for this features setting is a bit cramped.

Didn't know if this should go in a new issue or not.

Model: Samsung S10+ (SM-G975U)
Nightly build id: 72.0a1 20191202091209

_Originally posted by @bepvte in https://github.com/mozilla-mobile/fenix/issues/1019#issuecomment-564093377_

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **Nightly Build #13460608 from 12/12** using the following devices:
• Google Pixel 3a (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• Motorola G4 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

► Screenshot
![rsz_screenshot_20191213-105024](https://user-images.githubusercontent.com/51314259/70697214-cbb91800-1ccd-11ea-8c9f-25c0677f93fa.png)

►Video
![20191213_104415](https://user-images.githubusercontent.com/51314259/70697339-fdca7a00-1ccd-11ea-98fb-b5d601f5a5a9.gif)
