### ISSUE TITLE
[Bug] Settings "Passwords" item

### ISSUE THREAD

**Issue by liuche** [mozilla-mobile/fenix#7075]
Chatted with @AmyYLee about this, and a few changes here:
- This string should actually be "Logins and Passwords" to match the Settings header.
- The settings item animates in, after the rest of the settings load

![Screenshot_20191210-125537](https://user-images.githubusercontent.com/1082253/70568660-2b3bea00-1b4d-11ea-8285-5a05a84e9cd7.png)
![Screenshot_20191210-113945](https://user-images.githubusercontent.com/1082253/70568661-2b3bea00-1b4d-11ea-8d0a-ac1dc083eb1a.png)

**Comment by AndiAJ** [comment]
Hi I've just checked this matter on the latest **Nightly Build #13520613 from 12/18** using the following devices:

• Google Pixel 3a (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

✔️ Updated Strings

❌ Feature flag animation 

Comparison **Nightly Build #13520613 from 12/18** VS **Nightly Build #13300628 from 11/26**
 
 ► Nightly Build #13520613 from 12/18
![20191218_105531](https://user-images.githubusercontent.com/51314259/71073777-ade62a00-2189-11ea-9e6b-eeeef30afb7a.gif)


► Nightly Build #13300628 from 11/26
![20191218_105413](https://user-images.githubusercontent.com/51314259/71073669-7d05f500-2189-11ea-8a89-a5dbe3747247.gif)

I would kindly ask @mcarare to review the above.  :relaxed:
