### ISSUE TITLE
[Bug] Cannot update multiple 'what to sync' settings at the same time

### ISSUE THREAD

**Issue by Baron-Severin** [mozilla-mobile/fenix#7078]
## Steps to reproduce
- Log into Fenix
- Settings -> Passwords -> Sync Logins
- Under "choose what to sync", rapidly change multiple values

### Expected behavior
- Whatever values I set are retained

### Actual behavior
- Only the first changed value from each sync is retained. Syncing overwrites any following values

### Video
![change-sync-settings](https://user-images.githubusercontent.com/13170306/70579597-ff792e00-1b65-11ea-9cd6-c70326bcf809.gif)

### Device information

* Android device: Pixel 2, Android 10
* Fenix version: de6469e19889a89ad0505c5855941ddbea4e721c (current tip of master)

**Comment by ekager** [comment]
Closing for #6553
