### ISSUE TITLE
[Bug] [Crash] File Selection results in crash

### ISSUE THREAD

**Issue by Division7** [mozilla-mobile/fenix#7079]
## Steps to reproduce
Using any website, look for an input type file:
```<input type="file" />```
Ex. On a [meme deep fryer](deepfriedmemes.com/index.html).
Attempt to browse for an image. The browser crashes immediately and further attempts will elicit the same response. I switched phones recently, and it occurred on both.
### Expected behavior
Firefox preview is to open a menu for file selection.
### Actual behavior
The browser crashes out, with an option to send the report to Mozilla.
### Device information

* Android device: OnePlus 7 Pro, Android 9 / OxygenOs 9.5.13.GM21AA; Also tried: Sony Xperia XA2 Ultra, Android 9 
* Fenix version: 2.3.0

**Comment by Division7** [comment]
Photos can be attached if requested.

**Comment by cadeyrn** [comment]
It's a known issue in Firefox Preview 2.3.0 and will be fixed in Firefox Preview 3.0.0.

**Comment by boek** [comment]
Fixed in 3.0!
