### ISSUE TITLE
[Bug] Pausing & Resuming a download changes its filename

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#7080]
See https://github.com/mozilla-mobile/android-components/issues/5283

**Comment by AndiAJ** [comment]
Hi, I've just check this issue on the latest Nightly Build #13460608 from 12/12 using the following devices:
• Google Pixel 3a (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• Motorola G4 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

The filename isn't changed, on the other hand it seems that with each resume the same file is downloaded again and again.

❌  Managed to reproduce this on:
• Google Pixel 3a (Android 9)
• Samsung Galaxy S7 (Android 7)
• Motorola G4 (Android 6.0.1)

► Video from Google Pixel 3a
![20191213_140943](https://user-images.githubusercontent.com/51314259/70712177-e00c0d80-1ceb-11ea-8267-77c72b413be8.gif)

✔️ Doesn't happen on:
• Huawei Mate 20 Lite (Android 8.1.0)
• LG Nexus 4 (Android 5.1.1)

► Video from Huawei Mate 20 Lite
![20191212_142827](https://user-images.githubusercontent.com/51314259/70712242-02059000-1cec-11ea-921f-0fb71620fb1d.gif)

@sblatz - Please review and advise if the file multiplication matter should separately. :relaxed:
I'll remove the QA needed label until further notice.

**Comment by sblatz** [comment]
@AndiAJ this seems to be a different issue. I'm also not able to reproduce on my Galaxy S9 on Android 9. 😕 

Are you able to verify that this is happening on the latest master?

**Comment by AndiAJ** [comment]
Unfortunately yes, still reproducible on the latest **Nightly Build #13520613 from 12/18** :worried:

@sblatz , as per your suggestions I've opened #7267 .

As for the file name issue, I'll mark it **verified as fixed** and close it.
