### ISSUE TITLE
Logins should be searchable

### ISSUE THREAD

**Issue by Hubfront** [mozilla-mobile/fenix#7087]
### Why/User Benefit/User Problem
The password display feature is almost useless without the ability to search for a specific string like for website/user mame/email, if a user has 1000+ login credentials displayed
### What/Requirements
Search field for string on login data page within settings

### Acceptance Criteria (how do I know when I’m done?)
If one can search for website/ username/email etc. within login data

**Comment by Hubfront** [comment]
Why cant i search within passwords? Actually, this isnt a feature missing, but a bug.

**Comment by softvision-miralobontiu** [comment]
Verified that the user can search for a saved login on the latest Nightly build from 3/11, and on Beta v4.1.0-beta.1, with Xiaomi Mi4i (Android 5.0.2), and Samsung Galaxy Tab S6 (Android 9).
