### ISSUE TITLE
Edit the Navigation Bar (in PB) color to match the Simplified toolbar color when a website is open in 

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/fenix#7088]
### Why/User Benefit/User Problem
Modifying the Navigation Bar color to match the Simplified toolbar color(to be exactly like it's in home screen).
### What/Requirements
Modify the color for the Navigation Bar.
### Acceptance Criteria (how do I know when I’m done?)
The Navigation Bar color matches the Simplified toolbar color.

>Actual
![Screenshot_20191211-161008_Firefox Nightly](https://user-images.githubusercontent.com/42831109/70632913-56e7ce80-1c38-11ea-8e7b-2992d5684fc1.jpg)

>Possible example
![Screenshot_20191211-161017_Firefox Nightly](https://user-images.githubusercontent.com/42831109/70632923-594a2880-1c38-11ea-89c9-1be752b1ad7b.jpg)

### Design Work

- [x] Request for Comments from UX team
- [ ] ~Usability testing if a new pattern or potentially confusing UI~ Not required – minor UI tweak
- [x] Request for Comments from Fenix team and/or A/C, GV, Sync, etc as needed
- [x] Interaction details included
- [x] Accessibility ~- is this a review by someone,~ just keeping it in mind?
- [x] For existing UI changes, deltas are highlighted
- [ ] ~Strings/content reviewed and approved~ Not required – minor UI tweak
    - [ ] ~Are they too long for the component in other locales~

### Deliverable

- [ ] ~Assets uploaded to Google Drive~
- [x] Links to deliverables (spec, assets) posted in comment 0

### Deliverable Links

- ~User flow:~
- Spec: see below
- ~Assets:~

#### Current
The Android System navigation bar is coloured differently from the browser address bar:

<img src="https://user-images.githubusercontent.com/51007/70954978-1d99dd80-20d4-11ea-9271-80ebe8058b5b.png" width="360">

#### Proposed
The Android System navigation bar and browser address bar both **share the same gradient**:

<img src="https://user-images.githubusercontent.com/51007/70955174-c3e5e300-20d4-11ea-9688-5ebd5382e6af.png" width="360">

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-14725)

**Comment by brampitoyo** [comment]
Hi @abodea. Actually, the colour shade of the navbar already matches the spec when a site is open (ie. not in about:privatebrowsing).

The navbar doesn’t need to be modified to match the simplified colour.

**Comment by brampitoyo** [comment]
@abodea I’ve misunderstood your request a bit. Sorry about that.

Our original spec didn’t dictate identical colour for system navbar and browser address bar, because we _thought_ that we can’t control the system navbar colour.

You’re saying that the system navbar colour may be controllable?

If that’s the case, then yes – absolutely. Let’s modify the navbar colour to match the address bar.

**Comment by abodea** [comment]
Hello @brampitoyo sorry for the late response.
>You’re saying that the system navbar color may be controllable?
>If that’s the case, then yes – absolutely. Let’s modify the navbar color to match the address bar.

Yes, this was exactly what I was referring to. It will create the full-screen feeling exactly how it is now on the home screen when no web page is open(see my attachments).

**Comment by brampitoyo** [comment]
@abodea I’ve updated comment 0 with UX decision, as mentioned above.

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807548

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
