### ISSUE TITLE
Migration screen

### ISSUE THREAD

**Issue by liuche** [mozilla-mobile/fenix#7092]
### Why/User Benefit/User Problem
As a user I'd like to see information as my Firefox upgrades to Fenix/new browser.

### Context
From Firefox, we'll receive a store that state about the migration, that Fenix can observe.

### Dependencies
- [x] Final copy
- [x] AC API for migration store state, to observe when migration is complete https://github.com/mozilla-mobile/android-components/issues/5509
- Minor UX changes, if at all

### Acceptance Criteria (how do I know when I’m done?)
- [x] Conditionally display screen if Migrating vs new user
- [x] Handle all different entry points into Firefox (e.g. View Intents, Search widget?, PB, homscreen shortcuts, etc)
- [x] Lock user during migration, do not expose browsing capability (database lock) - otherwise, Firefox might hang with multiple writes to the db
- [x] ~~(Mocks TBD) Handle error states (e.g. failed bookmarks) and display to user~~
- [x] Link to "Learn more/FAQ" on "Start browsing" screen - Clicking this link will **NOT** skip onboarding
- [x] Make sure this check ("did the user migrate?") doesn't check affect cold startup (cc @mcomella can talk to @pocmo about measuring this effect) - we might take this out after X months if it's a big impact?

### Mocks
Relevant is the **Data Migration** section of https://miro.com/app/board/o9J_kw1CGow=/

**Comment by vesta0** [comment]
@liuche is this similar to existing #6511

**Comment by liuche** [comment]
Checking on the dependencies:
@apbitner are there any additional changes to the UI, that came out of the user study?
@mheubusch are there final strings for this? String freeze for migration strings in 1/15, so we need to have those string so @sblatz can pre-land them.

**Comment by liuche** [comment]
Sorry @sblatz there was some miscommunication here - @jonalmeida will actually be doing this piece, just needed a Fenix-by-AC label.

**Comment by pocmo** [comment]
@jonalmeida will help us push that into a functional, "good enough" state for Nightly. There will likely still be follow-up for Beta/Production migration (which may need a Fenix owner). :)

**Comment by apbitner** [comment]
@liuche The UI and strings in the Data Migration section are final

**Comment by liuche** [comment]
@jonalmeida could you go through the checklist in comment 0, and check off all the parts that you finished with that PR? if they're mostly done and there's no value in keeping this bug open bc the only remaining work is polish or something, could you file another bug listing off what still needs to be done?

**Comment by jonalmeida** [comment]
> @jonalmeida could you go through the checklist in comment 0, and check off all the parts that you finished with that PR?
> 
> If they're mostly done and there's no value in keeping this bug open bc the only remaining work is polish or something, could you file another bug listing off what still needs to be done, and link it here?

@liuche I've updated the checklist. I'm not sure what the error states are and the learn more stuff are, but those don't sound like polish. :)

**Comment by jonalmeida** [comment]
Un-assigning myself since I'm not working on this anymore.

**Comment by liuche** [comment]
@apbitner are the error states (when part of migration fails, say, bookmarks didn't import) part of the mocks? I didn't see them in the Fenix section.

@jonalmeida are the error states exposed by the migration store state? e.g. bookmarks didn't fully migrate.

**Comment by jonalmeida** [comment]
> @jonalmeida are the error states exposed by the migration store state? e.g. bookmarks didn't fully migrate.

Yes.

**Comment by apbitner** [comment]
@liuche I wasn't aware of any error states that were needed. Is there a list of all potential errors? What options will the user have after receiving an error?

**Comment by apbitner** [comment]
Per today's check-in, we're currently not informing users of errors because there is no action for them to take. We also may not be able to tell exactly what data was affected when an error occurs as well.

**Comment by pocmo** [comment]
For Nightly migration we implemented a simple version of this screen. Softvision filed the following issues (mostly things were we are not really following the mocks):

- https://github.com/mozilla-mobile/android-components/issues/5628
- https://github.com/mozilla-mobile/fenix/issues/7955
- https://github.com/mozilla-mobile/fenix/issues/7890
- https://github.com/mozilla-mobile/fenix/issues/7978
- https://github.com/mozilla-mobile/android-components/issues/5694
- https://github.com/mozilla-mobile/fenix/issues/7975

**Comment by ekager** [comment]
Besides the follow up issues linked above it seems like the only remaining bullet item in comment 0 is `Link to "Learn more/FAQ" on "Start browsing" screen - Clicking this link will NOT skip onboarding`. 

I don't see this as part of the Miro mocks could you clarify what this means @apbitner ?

**Comment by apbitner** [comment]
I presume this is referring to the new onboarding card (below). @vesta0 can you confirm?

<img width="400" alt="image" src="https://user-images.githubusercontent.com/22176302/73755429-9eb43f00-472b-11ea-9daa-fe5397b0ab24.png">

**Comment by ekager** [comment]
That new onboarding card was added with #7952 
I think this ticket may be completed then besides the follow up visual issues?

**Comment by apbitner** [comment]
So far as I can tell, yes

**Comment by vesta0** [comment]
@liuche created this ticket so I can't speak to what she was referring to. 

My understanding is that the migration screen is done but needs to align with UX mocks visually (fonts, alignment, etc).

**Comment by vesta0** [comment]
This ticket is done and we have follow-up bugs filed.
