### ISSUE TITLE
Don't prompt user to login if they select "Never Save" in password prompt

### ISSUE THREAD

**Issue by liuche** [mozilla-mobile/fenix#7094]
### Why/User Benefit/User Problem
As a user, if I don't want to save a login, I don't want to be prompted again.

Breaking this out of #5542 

### Dependencies
- [x] UX to provide context between "Don't save" and "Never save"

### Acceptance Criteria (how do I know when I’m done?)
- [x] Clicking "Don't Save" on the logins prompt does not show the prompt again
- [x] Exceptions list for managing logins exceptions

**Comment by liuche** [comment]
Hey @AmyYLee bringing this up from chatting with MattN, that on Desktop, there's a difference between "Don't save" and "Never save", specifically in how that gets saved in exceptions.

Since we're taking this out of the MVP, we have some more time to think about this. If you have some ideas about this, please let us know - but we probably should get some priority on this so we can prioritize the UX work.

<img width="405" alt="Screen Shot 2019-12-11 at 2 07 58 PM" src="https://user-images.githubusercontent.com/1082253/70664713-c8ffe980-1c1f-11ea-8ef6-9dc962f07623.png">

**Comment by liuche** [comment]
This will require some UX, because we don't distinguish between the user intending "don't save password this time" vs "never save this password and don't prompt me again" @AmyYLee

**Comment by AmyYLee** [comment]
Hi @liuche, we should have "Never save" as the option here instead of "Don't save". The assumption is that if the user doesn't want to save a password that they want it to stay that way and not be asked again. If they do change their minds they can remove it from the exceptions list in Settings. This matches Fennec and also in our options for "Save passwords" is either Always ask or Never save.

See below for reference:
![Website - Save Login Dialogue@2x](https://user-images.githubusercontent.com/5992746/71099780-d538f900-2181-11ea-988c-b3cdc91ad2bb.png)

**Comment by mnoorenberghe** [comment]
In this design, is there any other way to close the prompt and keep using the webpage without choosing Never Save if I don't want to Save? On desktop, "Never Save" adds **website** to a list to not save passwords for, it's not specific to the username. If you don't provide the option for a user to not save this specific submission then they won't have the option to save a different username for the site. Of course, you could instead have "Never Save" be specific to the combination of username+website but that's different than desktop.

**Comment by AmyYLee** [comment]
> In this design, is there any other way to close the prompt and keep using the webpage without choosing Never Save if I don't want to Save? On desktop, "Never Save" adds **website** to a list to not save passwords for, it's not specific to the username. If you don't provide the option for a user to not save this specific submission then they won't have the option to save a different username for the site. Of course, you could instead have "Never Save" be specific to the combination of username+website but that's different than desktop.

@mnoorenberghe if the user taps outside the prompt panel, the prompt disappears without you needing to choose and it prompt will appear the next time you go to the website.

**Comment by softvision-miralobontiu** [comment]
The prompt is still displayed after selecting "Don't save".
Tested on the latest Nightly build from 3/24 (#20840606), and on Beta 4.2.0-beta.1 with OnePlus 5T (Android 9).

**Comment by vesta0** [comment]
Also `Don't save` should be changed to `Never save`

**Comment by liuche** [comment]
Taking this out because we don't have a "Don't save" yet, for MVP.

**Comment by ekager** [comment]
This came up again in some Reddit feedback I was reading. User story was a user used a 3rd party password manager and wasn't an FxA user and did not want to keep being asked for the same website (seemed like they logged into the same sites often maybe an always in private mode user). If we manage the exceptions list storage ourselves (probably in AC), this is actionable now.

**Comment by mnoorenberghe** [comment]
> This came up again in some Reddit feedback I was reading. User story was a user used a 3rd party password manager and wasn't an FxA user and did not want to keep being asked for the same website (seemed like they logged into the same sites often maybe an always in private mode user). If we manage the exceptions list storage ourselves (probably in AC), this is actionable now.

Does that user save some logins in the Firefox password manager? If not then wouldn't they want the global toggle instead?

**Comment by liuche** [comment]
Could surface the global toggle, in Feature Discoveribility.

**Comment by ekager** [comment]
The UX was in the original mocks for logins: https://share.goabstract.com/46b9d737-fcde-434f-bc6a-5b23b574fe5e?collectionLayerId=7d248eb9-de9d-4304-8d9c-e2034778f682&mode=design so this is eng ready AFAICT

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly Build 200716 from 7/16`** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)

►Video
![20200716-153233](https://user-images.githubusercontent.com/51314259/87673200-d57f8e00-c77c-11ea-91f4-64eb6ddf0bfb.gif)
