### ISSUE TITLE
 Reminder about intent handling preference

### ISSUE THREAD

**Issue by bifleming** [mozilla-mobile/fenix#7100]
## User Story
- As a user, if I have prevented Fenix from opening 3rd party applications I would want some sort of feedback explaining why no action was taken, so I know that my browser is not broken.

### Acceptance Criteria
- I know why my browser does not open an app link intent inside a 3rd party application.

### Dependencies
There's a whole chain of dependencies, actually
- [x] #7099 preference
- [x] #5664 infinite reload & GV https://bugzilla.mozilla.org/show_bug.cgi?id=1600704

Meta: #3177

**Comment by liuche** [comment]
Work with @AmyYLee on coming up with the solution for this.

**Comment by sblatz** [comment]
This is waiting on https://github.com/mozilla-mobile/fenix/issues/7099 as we don't have this preference in yet. We do have one in settings but it looks different and seems to have the opposite behavior? 

"Open links in apps" under Privacy.

**Comment by rocketsroger** [comment]
> This is waiting on #7099 as we don't have this preference in yet. We do have one in settings but it looks different and seems to have the opposite behavior?

Yes, looks like the new design is the opposite behavior.  I'm starting https://github.com/mozilla-mobile/fenix/issues/7099 to change the behavior to match the design.  Once that's done hopefully this issue will be unblocked.

**Comment by vesta0** [comment]
I am de-prioritizing this issue. Let's just focus on making sure all the acceptance criteria for #7099 is met.
