### ISSUE TITLE
[Bug] Search bar jumps when animating back

### ISSUE THREAD

**Issue by Baron-Severin** [mozilla-mobile/fenix#7103]
## Steps to reproduce
- From home screen
- Click on "Search or enter address" to enter search fragment
- Click on back button

### Expected behavior
- Toolbar animates smoothly down

### Actual behavior
- Toolbar jumps upward before animating down

### Video (15% speed)
![search-bar-jump-short](https://user-images.githubusercontent.com/13170306/70674205-2a34b680-1c3a-11ea-8912-a215dbb5853e.gif)

### Device information

* Android device: Pixel 2, Android 10
* Fenix version: 1c9c8f590a5106058dcfbff2ffcddbc0bd312b9b (current head of master)

**Comment by Baron-Severin** [comment]
Just a hunch, but this could be related to the full screen change in #4107.

**Comment by mcarare** [comment]
I've noticed the bar changing size before, but the moving to top is definitely related to #4107. The screen is adjusted in `HomeFragment` in `onResume` and I think it's interfering with the animation.

**Comment by boek** [comment]
This is fixed from reverting #6925
