### ISSUE TITLE
[Bug] "Add to Home screen?" floating menu is displayed at the bottom of the screen

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/fenix#7110]
## Steps to reproduce
1. Launch Fenix.
2. Reach the settings menu.
3. Tap on the ` "Add to Home screen?"`
### Expected behavior
The "Add to Home screen?" floating menu should be displayed in the middle of the screen.
### Actual behavior
"Add to Home screen?" floating menu is displayed at the bottom of the screen
### Device information

* Android device: **Samsung Galaxy S10+(Android 9)**, **Huawei Mate 20 lite(Android 8.10)**
* Fenix version: **Nightly 12/12.**

![Screenshot_20191212-173546](https://user-images.githubusercontent.com/42831109/70727039-aba64a80-1d07-11ea-889d-2e7cfbb0c53c.jpg)
![Screenshot_20191212-174136_One UI Home](https://user-images.githubusercontent.com/42831109/70727105-c8db1900-1d07-11ea-8b9a-fa68de108d7d.jpg)

![Screenshot_20191213-174102](https://user-images.githubusercontent.com/42831109/70727042-ac3ee100-1d07-11ea-91a9-e6bd82b763ac.png)

**Comment by mcarare** [comment]
These are framework dialogs that we cannot control. Closing this, as no improvement is possible.
