### ISSUE TITLE
[Bug]The collections context menu overlaps with the device buttons

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#7111]
## Prerequisite
Have at least 3 collections created.

## Steps to reproduce
1. Tap on the 3 dot button of the firstly created Collection
2. Tap on delete collection

### Expected behavior
The context menu shouldn't overlap with the device buttons, and the user should be able to delete the desired collection.

### Actual behavior
The context menu overlaps with the device buttons, making it impossible to delete the desired collection.

### Device information

* Android device: Google Pixel 3a (Android 9)
* Fenix version: Nightly Build #13460608 from 12/12

### Notes
► Video
![20191213_174658](https://user-images.githubusercontent.com/51314259/70727790-f2e10b00-1d08-11ea-911c-48435415376a.gif)

► Screenshot
![rsz_screenshot_20191213-175234](https://user-images.githubusercontent.com/51314259/70727680-b9100480-1d08-11ea-8e2f-3a1eff1eb215.png)

**Comment by mcarare** [comment]
Closed by reverting the fullscreen home: https://github.com/mozilla-mobile/fenix/pull/7152
