### ISSUE TITLE
Create Splash Screen

### ISSUE THREAD

**Issue by ekager** [mozilla-mobile/fenix#712]
### Why/User Benefit/User Problem
When a user opens Fenix, there is currently a white flash on startup. If the user is using private browsing, the transition can be a bit jarring. We believe a themed splash screen would help
(See #625 for white flash)

**Comment by agi90** [comment]
Note: Chrome uses an image with fake UI controls to avoid the white flash.

**Comment by mheubusch** [comment]
@AmyYLee I know we've talked about this and  the issue of solving for light theme introduces issues for dark theme.   can you weigh  in on this?

**Comment by vesta0** [comment]
This looks like a dup of #599 please close one of them.

**Comment by lime124** [comment]
as per vesta's comment above closing this in favor of #599
