### ISSUE TITLE
[Settings] Saved logins - icons in Dark theme have jagged edges

### ISSUE THREAD

**Issue by AmyYLee** [mozilla-mobile/fenix#7122]
Steps to reproduce:

1. Set theme to Dark theme in Settings
2. Go to Settings -> Passswords -> Saved logins -> Site info

Expected:
Icons appear smooth with correct line weight

Actual:
Icons appear jagged with thick line weights

![Screen](https://user-images.githubusercontent.com/5992746/70745772-92df6a00-1cf2-11ea-88c7-7498fcbdd727.png)

**Comment by mcarare** [comment]
@AmyYLee Can you please help me with the assets for this? I cannot find them in the mocks. Thank you!

**Comment by liuche** [comment]
from Amy: the assets look fine for Light mode, but look wrong on Dark mode.

**Comment by mcarare** [comment]
Although it is not so noticeable like with a dark background, they have the same jagged edges in light theme.

**Comment by liuche** [comment]
@AmyYLee ^

**Comment by AmyYLee** [comment]
@mcarare 

Here are the icons. Let me know if these work for you

copy.svg
https://drive.google.com/file/d/1u0H3gvA5Dou43ZMzpzWpoH3fvieKCnlk/view?usp=sharing

password-show.svg
https://drive.google.com/file/d/1tTAG_Sa9tr1J8TZJgEIR3wE5rhvxFSd9/view?usp=sharing

password-hide.svg
https://drive.google.com/file/d/1tz6vDm06Xv4VSJQ6wgq6aOgjADnquiUf/view?usp=sharing

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **Nightly Build #13580607** from 12/24 using the following devices:

• Google Pixel 3a (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

►Pic
![rsz_1rsz_00100lportrait_00100_burst20191224095744467_cover](https://user-images.githubusercontent.com/51314259/71402420-7ec23380-2635-11ea-891a-09b6c7a80fb4.jpg)
