### ISSUE TITLE
Share tabs under open tabs should let the user choose which tabs to share

### ISSUE THREAD

**Issue by colintheshots** [mozilla-mobile/fenix#7123]
### Why/User Benefit/User Problem
The user may not want to share every tab that is open. Some tabs may be unrelated or too private. The open tabs overflow option Share Tabs only shares all tabs currently and that could be too much sharing.

### What/Requirements
The user should be able to select which tabs to share.

### Acceptance Criteria (how do I know when I’m done?)
- It will be possible to select a list of tabs to share.
- If none is selected, we should handle that appropriately.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-14756)

**Comment by s-ankur** [comment]
Hi, we have this via the select tabs functionality. And the menu item is changed to share all tabs which is appropriate. I think this can be closed
