### ISSUE TITLE
[Bug] When Toolbar is on bottom, panels opens on top in custom tabs (ETP + secure)

### ISSUE THREAD

**Issue by ekager** [mozilla-mobile/fenix#7124]
## Steps to reproduce
1. Have toolbar config set to bottom
2. Open custom tab
3. Open security or ETP panel 

### Expected behavior
Panel opens where buttons were clicked

### Actual behavior
Panels open from top

### Device information

* Android device: ?
* Fenix version: ?

**Comment by ekager** [comment]
It looks like the opposite might be true for regular browsing because we are passing in a hard coded gravity for `getAppropriateLayoutGravity`

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **Nightly Build #13500610 from 12/16** using the following devices:
• Google Pixel 3a (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• OnePlus (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

► Video
![20191216_110715](https://user-images.githubusercontent.com/51314259/70894075-f7e9d700-1ff4-11ea-8f3d-6b71eb5ac286.gif)
