### ISSUE TITLE
[Bug] Page dies when switching Light/Dark theme

### ISSUE THREAD

**Issue by liuche** [mozilla-mobile/fenix#7125]
## Steps to reproduce
1. Load cnn.com
2. (while loading) change dark/light theme

### Expected behavior
Page loads normally

### Actual behavior
(Intermittent, ~1/4 time) Tab dies, page never loads, can't reload/X
Additional info: this is more reproducible with WebRender turned on, but has been repro-ed without.

### Device information

* Android device: Pixel 3
* Fenix version: Nightly 12/12

**Comment by ekager** [comment]
Just tried 4x and couldn't repro. Let's QA this

**Comment by LaurentiuApahideanSV** [comment]
I tried to reproduce the issue on Firefox Preview Nightly 200611 (Build #21630608) but was unable to.

### Device information
- OnePlus 6T (Android 9)
- Huawei MediaPad M3 lite (Android 7.0)
