### ISSUE TITLE
Scan screen should use different string for non-URL results, show 2D reticle

### ISSUE THREAD

**Issue by colintheshots** [mozilla-mobile/fenix#7133]
### Why/User Benefit/User Problem
Scanning a QR code without a URL result shows a confusing message. It should make sense.

### What/Requirements
Instead of "Allow Firefox Nightly to open 739871283751987" we should show a string that indicates we'll search for that value.

### Acceptance Criteria (how do I know when I’m done?)
Change the string if the value seems not to be a URL.
Optionally, it would be nice to have a 2D reticle hinted at for scanning barcodes/ISBNs?

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-14765)

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807390

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
