### ISSUE TITLE
[Sycn] Focus hairlines look low resolution

### ISSUE THREAD

**Issue by AmyYLee** [mozilla-mobile/fenix#7134]
Steps to reproduce:
1. Go to Settings -> Turn on Sync
2. Tap "Ready to scan"

Expected:
Focus hairlines look sharp and high resolution

Actual: 
Focus hairlines are fuzzy and appear low resolution

See screenshot:

![Screenshot_20191212-162353](https://user-images.githubusercontent.com/5992746/70755856-042a1780-1d09-11ea-8baa-e8e11af4f1ae.png)

**Comment by ekager** [comment]
Closing for #2432
