### ISSUE TITLE
[Bug] The TP doorhanger is displayed on the top of the site using custom tab

### ISSUE THREAD

**Issue by sv-sdeiac** [mozilla-mobile/fenix#7135]
### Prerequisites
Firefox Preview is your default browser

### Steps to reproduce
1. Open a link on the custom tab;
2. Tap on the "Tracking Protection" or "security" icon;

### Expected behavior
A doorhanger is displayed on the bottom of the screen.

### Actual behavior
The doorhanger is displayed on the top part of the screen.

### Device information

* Android device: Nexus 9 (Android 7.1.1);
* Fenix version: Friday 12/13 build #13470610
* Notes:
There is the doorhanger displaying in normal tab
![Doorhangernormaltab](https://user-images.githubusercontent.com/40264165/70799359-1a3fe280-1db2-11ea-8449-8d8bef9c4742.png)

There is the doorhanger displayed in custom tab
![Doorhangercustomtab](https://user-images.githubusercontent.com/40264165/70799375-262ba480-1db2-11ea-8acf-374a32c9f063.png)

**Comment by ekager** [comment]
Closing for #7124
