### ISSUE TITLE
[Bug] Share tab&collection and Save to collection screens are not fully displayed on Samsung Galaxy S10+

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/fenix#7150]
## Steps to reproduce
1. Launch Fenix.
2. Access any of the following: `Share tab&collection and Save to collection`.
3. Rotate the device in landscape mode.
### Expected behavior
The `Share tab&collection and Save to collection` should be fully displayed in landscape mode.
### Actual behavior
Share tab&collection and Save to collection screens are not fully displayed on Samsung Galaxy S10+
### Device information

* Android device: **Samsung Galaxy S10+(Android 9).**
* Fenix version: **Nightly 12/13.**

### Notes
I also tried with the following devices but I couldn't:
 • Google Pixel 3a (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• OnePlus (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

![Screenshot_20191213-171634_Firefox Nightly](https://user-images.githubusercontent.com/42831109/70811820-140c2f00-1dcf-11ea-9991-c7ec3b44ee18.jpg)
![Screenshot_20191213-171607_Firefox Nightly](https://user-images.githubusercontent.com/42831109/70811829-166e8900-1dcf-11ea-9c89-91b2d097c50c.jpg)

**Comment by boek** [comment]
Another notch bug?

**Comment by abodea** [comment]
@boek yes 😨 but this was only on S10+(I guess).
I'm able to reproduce this issue even after the full screen was reverted https://github.com/mozilla-mobile/fenix/pull/7152 .

**Comment by darkwing** [comment]
When I try to share in horizontal mode, I basically can't see anything on my Pixel 4:

<img width="1597" alt="ShareHorizontal" src="https://user-images.githubusercontent.com/46655/74288889-47960780-4cf3-11ea-9b4f-cbcd5dcd286e.png">

@AmyYLee Any idea for what we want to do here?  @boek From a technical perspective, is there anything we can do about the height of the share block?

**Comment by AmyYLee** [comment]
> When I try to share in horizontal mode, I basically can't see anything on my Pixel 4:
> 
> <img alt="ShareHorizontal" width="1597" src="https://user-images.githubusercontent.com/46655/74288889-47960780-4cf3-11ea-9b4f-cbcd5dcd286e.png">
> 
> @AmyYLee Any idea for what we want to do here? @boek From a technical perspective, is there anything we can do about the height of the share block?

Hi, from the screenshot and checking on my Pixel 3, it looks like there's adequate room to display the "Share" header here and have it horizontally aligned to the "X" icon. This looks like a technical bug that it's cut off.
