### ISSUE TITLE
Bring back the Quick Action Bar (QAB)

### ISSUE THREAD

**Issue by sarilouis** [mozilla-mobile/fenix#7151]
### Why/User Benefit/User Problem
Sharing a page and opening in Reader view are hands down the 2 features I use the most on the phone. Having them so handily, quickly, and discretely available in the QAB was brilliant.

### What/Requirements
Bring back the QAB. I saw a bug was filed because people were confused by having more than one location (the QAB and the menu bar) to look for a feature. But I suggest the solution to be to have what's in the QAB be in the menu bar for consistency, but having quicker access to feature in the QAB is not contradictory or confusing.

### Acceptance Criteria (how do I know when I’m done?)
The QAB feature is enabled.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-14784)

**Comment by yoasif** [comment]
One idea I saw recently that the QAB would have been more useful had it been customizable -- like putting add-on actions there (for example).

Personally, one thing I didn't like was that the QAB could not be disabled; the feature was fine, it was just annoying to look at visually.

**Comment by yoasif** [comment]
Was thinking out loud in #1048 and stumbled upon the idea of putting a meatball menu into the address bar to enable a QAB-alike for additional functionality.

I booted up my Windows 10 Mobile device and discovered that there is some prior art for  that idea there:

![signal-attachment-2020-05-07-021827](https://user-images.githubusercontent.com/152493/81261491-30bd3380-900a-11ea-8018-bf67cbeae536.png)

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813199

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
