### ISSUE TITLE
[Custom tabs] Match menu item location in custom tabs to non-custom tabs

### ISSUE THREAD

**Issue by AmyYLee** [mozilla-mobile/fenix#7155]
We should keep the location of items consistent between custom and non-custom tabs. Please attached spec.

![Custom Tab - Spec](https://user-images.githubusercontent.com/5992746/70831552-dbfdef80-1dc0-11ea-8331-6d7a18173cdc.png)

Edit - Amy: 
> Also, can we include the icon for "Desktop site" toggle? We have an icon for it in the 3-dot menu in Preview.

**Comment by chenaaron3** [comment]
Hi, I am new to contributing to open source in general. May I take on this issue? If so, what should be my first steps? Thanks.

**Comment by mcarare** [comment]
@AmyYLee Would it look better with the "powered by" text center aligned?

<img src= https://user-images.githubusercontent.com/48995920/71581437-e84ab200-2b0d-11ea-97d0-3ce6ec985eeb.png width= 40% img>

**Comment by AmyYLee** [comment]
@mcarare No, please keep it left aligned. 

Also, can we include the icon for "Desktop site" toggle? We have an icon for it in the 3-dot menu in Preview. 
<img width="319" alt="Screen Shot 2019-12-30 at 12 41 31 PM" src="https://user-images.githubusercontent.com/5992746/71593377-c3e8d880-2b01-11ea-810e-fb543084b8fc.png">

Thanks!

**Comment by mcarare** [comment]
@AmyYLee Thank you for your response. I have another question regarding the item order. I see that in a normal tab the order of the menu items is reversed when the navigation toolbar is at the top. Should we do the same for custom tabs? 

Also, I should note that IMO the reversing of menu items is very confusing. When I opened the menu with toolbar on top for the first time it took me a while to find what I was searching, and it still confuses me every time I test something with the toolbar position changed.

**Comment by AmyYLee** [comment]
> @AmyYLee Thank you for your response. I have another question regarding the item order. I see that in a normal tab the order of the menu items is reversed when the navigation toolbar is at the top. Should we do the same for custom tabs?
> 
> Also, I should note that IMO the reversing of menu items is very confusing. When I opened the menu with toolbar on top for the first time it took me a while to find what I was searching, and it still confuses me every time I test something with the toolbar position changed.

Yes we should do the same for custom tabs (reverse order if the toolbar is set to the top). The idea is that items are ordered in most frequently used. The assumption is that most users aren't going to be flipping back and forth between top and bottom nav and they will stick to one or the other. @apbitner worked on the top toolbar so I'll let him comment on this as well.

**Comment by apbitner** [comment]
Yes, they should be reversed, and agree that users are not going to be constantly switching the toolbar position.

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **Nightly Build #20100616 from 01/10** using the following devices:
• Google Pixel 3a (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

► Screenshot
![rsz_rsz_screenshot_20200110-153911](https://user-images.githubusercontent.com/51314259/72159415-fc6f9880-33c4-11ea-86f3-25938dcd0ed5.png)
