### ISSUE TITLE
[Menu] App Menu - Left and Right margins should be 16dp (need dynamic width)

### ISSUE THREAD

**Issue by AmyYLee** [mozilla-mobile/fenix#7157]
App Menu: Left and Right margins should be 16dp

Originally reported in [implementation checklist](https://github.com/mozilla-mobile/fenix/issues/4538) 

[Reporter: AmyYLee] [Date: 05/01/19]
[Edit: Sawyer][Date: 08/05/19]: This will require a lot of work, unfortunately. The fix is to make the browser menu work with wrap_content, but that is pretty difficult. We should get this prioritized in AC if we care about it.
This checkbox is related to [#1871](https://github.com/mozilla-mobile/fenix/issues/1871).

### Acceptance Criteria

Expand the menu width up to a certain max_width we determine (314dp) & truncate items that don't fit.

**Comment by boek** [comment]
QA will want to verify that this also fixes #7049

**Comment by sblatz** [comment]
UX: how should we handle these longer menu items? If we make the margins a static 16dp, menu items that have really long names will make the menu take up the whole screen.

Should the menu have a fixed width? Should it expand up to a certain width and then wrap the menu items?

### Potential Solutions
1. Fix the menu width (what we do now)
2. Expand the menu width up to a certain max_width we determine (potentially larger than what we have now) & **truncate items that don't fit**
3.  Expand the menu width up to a certain max_width we determine (potentially larger than what we have now) & **wrap to next line items that don't fit**

@AmyYLee How would you like us to proceed?

**Comment by AmyYLee** [comment]
@sblatz Hi, can we go with Opt 2 "Expand the menu width up to a certain max_width we determine (potentially larger than what we have now) & truncate items that don't fit"

Can we also ensure that "Add to Home screen" doesn't get truncated? There's a screenshot between Nightly and Release where in the Release version it's truncated but there's enough space for all the words to fit. 

Is there's a "worse case" example to determine max width? (i.e German?) so we can figure what the max width should be. 
<img width="411" alt="Screen Shot 2020-01-14 at 16 32 07" src="https://user-images.githubusercontent.com/5992746/72384604-ccd5ce80-36eb-11ea-993b-4d2cc014adc4.png">

**Comment by TheoChevalier** [comment]
French is quite impacted, here are the full labels:

Version ordinateur
Ajouter à l’écran d’accueil
Rechercher dans la page
Signaler un problème sur ce site
Ajouter à une collection

![Screenshot_20200115-110511](https://user-images.githubusercontent.com/1294206/72429279-803fd100-3787-11ea-86ac-d10a7e8dc1c1.png)

**Comment by AmyYLee** [comment]
![Screen Shot 2020-01-15 at 3 00 04 PM](https://user-images.githubusercontent.com/5992746/72466870-c016b080-37a7-11ea-8225-b27e352e33a5.png)

@sblatz Can we keep our current menu width and if strings are longer can we set max width to 314px? - Any string longer than that will get truncated. Thanks

**Comment by cadeyrn** [comment]
@sblatz This is not yet QA ready because https://github.com/mozilla-mobile/android-components/issues/6499 did not land yet.

**Comment by Mugurell** [comment]
Indeed, thank you Sören.
Will work on updating the A-C patch and afterwards will update this as needed.

**Comment by Mugurell** [comment]
I see this added for verification in Beta.
It only added the dynamic width values that will be used for the menu.
But the actual dynamic width menu is still in review in a-c - https://github.com/mozilla-mobile/android-components/issues/6499 so atm this patch doesn't have any effect for Fenix.

**Comment by Mugurell** [comment]
With https://github.com/mozilla-mobile/android-components/issues/6499 having landed this can also be verified.

The menu can now expand to at most 314dp if necessary to accomodate long menu option title.

**Comment by TheoChevalier** [comment]
The menu is now expanding on my phone, however while "Signaler un problème sur ce site" was supposed to fit according to the mockup above, it’s truncated on my build.

![image](https://user-images.githubusercontent.com/1294206/81544646-b4ab4e80-936f-11ea-8fec-ebc9f9d4cef9.png)

**Comment by Mugurell** [comment]
@TheoChevalier Thanks for chiming in!
The menu can now be wider to accommodate wider text and according to https://github.com/mozilla-mobile/fenix/issues/7157#issuecomment-574832372 it now can have a width up to 314dp. 
The image from that comment is just a mockup though.
Users can for example get the result from that image by having a smaller font size (set in device settings) or can have the text truncated much earlier by having a larger font size set.

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly Build 200511 from 5/11`** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)

► Screenshots from Google Pixel 3a
![overlay](https://user-images.githubusercontent.com/51314259/81574052-f65aea00-93ad-11ea-8b76-a77b49cb2442.png)
