### ISSUE TITLE
[Search] Search bar animation on homescreen edit

### ISSUE THREAD

**Issue by AmyYLee** [mozilla-mobile/fenix#7158]
Now that the search bar on homescreen is at the bottom, I don't think we should have the search bar move upwards to the top since it makes it feel laggy. Can we copy the transition of the search bar when a user is on a website and they tap on the search bar? The transition has the keyboard sliding up and the search bar instantly appears at the top.

Homescreen search bar animation:
https://cl.ly/8efffd09d561

Please copy this (bottom chrome search bar animation)
https://cl.ly/6d4be1692d5b

**Comment by abodea** [comment]
Verified as fixed on the latest **Nightly build 3/9** with **Google Pixel 4 XL (Android 10).**
Note that the animation is correctly displayed in normal and private browsing for top and bottom search bar.

**Comment by Diana-Rus** [comment]
Hi, verified as fixed on Firefox Beta Preview 4.1.0-beta.1 (Build #20720029) GV: 75.0-20200309155231 with Samsung Galaxy S8+ (Android 8)
Scenarios:
- Search bar/Toolbar bottom - Normal Mode - Homescreen
- Search bar/Toolbar bottom - Private Mode - Homescreen
- Search bar/Toolbar top - Normal Mode - Homescreen
- Search bar/Toolbar top - Private Mode - Homescreen
- Executing back action from search bar to homescreen.
The transition from homescreen to toolbar and back to homescreen is smoother than the one from description.

GIF - Homescreen->Search bar:
![20200312-153609](https://user-images.githubusercontent.com/49859863/76527241-914f4a80-6477-11ea-981f-0a2a9169ecf5.gif)
