### ISSUE TITLE
[Bug] screen.mozLockOrientation() not working

### ISSUE THREAD

**Issue by lindongbin** [mozilla-mobile/fenix#7159]
Then I cannot use some script like this:

`document.addEventListener('fullscreenchange', function(){
screen.mozLockOrientation('landscape');
});`

But it works on Fennec

* Android device: ?
* Fenix version: 
Nightly 191213 18:00 (Build #13471807)
26.0.0, e29cc1990
GV: 73.0a1-20191211094640

**Comment by boek** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1610967
