### ISSUE TITLE
Open context menus off of hamburger buttons on touch down rather than up

### ISSUE THREAD

**Issue by ehsan** [mozilla-mobile/fenix#7166]
### Why/User Benefit/User Problem
Chrome's hamburger menu in its UI is opened when the touch down event is received, whereas in Firefox Preview we open the menu when the touch up event is processed. This results in the menu opening feel snappier on my phone in Chrome compared to Firefox Preview.

You can test this by putting your finger on the hamburger button and touch and hold the screen and don't lift. In Chrome the menu pops up immediately after the touch is initiated, whereas Firefox Preview doesn't open the menu until the finger is lifted.

### What/Requirements
The menu should be opened when the touch down event is received. We should also handle the touch-hold-lift gesture somehow, for example by closing the menu if you lift your finger after holding it down with a delay.

### Acceptance Criteria (how do I know when I’m done?)
When the menu opening animation feels snappier compared to before.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-14797)

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813188

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
