### ISSUE TITLE
[Bug]Disable Autoplay Not Visible

### ISSUE THREAD

**Issue by Will-Sys** [mozilla-mobile/fenix#7168]
Block autoplay feature as described in https://support.mozilla.org/en-US/kb/media-controls-firefox-preview

## Steps to reproduce
    Tap the menu button.
    Tap Settings.
    Tap Site Permissions.

### Expected behavior
Block video and audio preference is present.

### Actual behavior
Block video and audio preference is absent.
![Screenshot_20191213-224737_Firefox Preview](https://user-images.githubusercontent.com/58870763/70843249-32891f00-1dfd-11ea-8373-3652231054c9.jpg)

* Fenix version: 3.0.0

site_permissions_preferences.xml the autoplay preference has isPreferenceVisible set to false?

**Comment by cadeyrn** [comment]
It's not a bug. This option is only available in Fenix Nightly so far, it's behind a feature flag:

https://github.com/mozilla-mobile/fenix/blob/releases/v3.0/app/src/main/java/org/mozilla/fenix/FeatureFlags.kt#L27-L30

**Comment by Will-Sys** [comment]
Its listed in the What's New for preview 3.0:
https://support.mozilla.org/en-US/kb/whats-new-firefox-preview-30

**Comment by boek** [comment]
@Will-Sys Good catch. This feature should not have made it onto that list! We're still waiting on one bug fix before we can ship it

**Comment by mklopp** [comment]
It is also on the support page which is quite misleading. 
https://support.mozilla.org/en-US/kb/media-controls-firefox-preview
Took me a while to find this issue and why it was not available on my phone.
Thank you though for the amazing work on the browser.

**Comment by liuche** [comment]
Autoplay now in release.
