### ISSUE TITLE
URLs in session bundles should be truncated

### ISSUE THREAD

**Issue by cadeyrn** [mozilla-mobile/fenix#717]
## Steps to reproduce

1. open the "About Fenix" page
2. press the tabs icon
3. look at the session bundle

### Expected behavior

There should be a length limit for the URL.

### Actual behavior

Please see the attached screenshot.

![screenshot_20190227-221114](https://user-images.githubusercontent.com/1100614/53523340-da3a9800-3adc-11e9-85b4-d73f71946366.png)

### Device information

* Android device: HTC U11 / Android 8.0
* Fenix version: Fenix revision 59c514996b4a6f677f623cbae12372d53c51a189

**Comment by boek** [comment]
Will be expanded with #532

**Comment by bsurd** [comment]
Verified on:
 - 1.0.1910 (Build #10642115)

 Devices:
 - Nokia 6 (Android 7.1.1)
 - HTC Desire 820 (Android 6.0.1)
