### ISSUE TITLE
Missing icons at About Firefox [Bug]

### ISSUE THREAD

**Issue by LittleAngelwings** [mozilla-mobile/fenix#7177]
![Screenshot_20191215-062827_Firefox Nightly](https://user-images.githubusercontent.com/44252450/70858625-b3cbd900-1f05-11ea-950b-766399c9a37f.jpg)
## Steps to reproduce

Go to settings - about firefox nigthly

### Expected behavior

You see the icons for a-c, GV 

### Actual behavior

No icons are shown

### Device information

Samsungs Galaxy Tab SM-T580 (8.1.0)
Huawei P Smart (9.0.0)

* Android device: ?

* Fenix version: ?

Nightly 191214 18:00 (Build #13481808)
26.0.0, d06f59e53
GV: 73.0a1-20191212095326

**Comment by cadeyrn** [comment]
The icons were intentionally removed:
https://github.com/mozilla-mobile/fenix/pull/6781#issuecomment-558702373

**Comment by LittleAngelwings** [comment]
@cadeyrn 
thanks for this info. But with icons it will be looks smarter, IMHO.
