### ISSUE TITLE
User should be able to exit from startup crashes

### ISSUE THREAD

**Issue by kbrosnan** [mozilla-mobile/fenix#718]
When the user encounters a startup crash we should be able to recover without the user clearing the application cache.

Provide user with the option to start with a clean state without losing cache (history, etc)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-14812)

**Comment by buttercookie42** [comment]
Nitpick: Losing the *cache* wouldn't actually be that terrible, it's the application *data* that shouldn't be lost.

> Provide user with the option to start with a clean state without losing cache (history, etc)

Something like the desktop UI, i.e. mainly the ability to (possibly selectively for certain tabs only) disable session restore?
