### ISSUE TITLE
[Bug] Misaligned hints about toolbar when it's placed on top

### ISSUE THREAD

**Issue by ixti** [mozilla-mobile/fenix#7181]
## Steps to reproduce

- start fresh install of firefox preview
- configure it to have toolbar on top
- visit website with trackers

### Expected behavior

Hint about purple shield should have pointing edge touching shield icon and hint bubble should be below shield icon.

### Actual behavior

Hint bubble is placed over the shield icon with pointing edge downwards pointing to nowhere.

### Device information

* Android device: Samsuns Galaxy S10 5G
* Fenix version: 3.0.0 (Build #13431956)
* 📦: 24.0.0, 968f858c1
* 🦎: 71.0-20191125115111

**Comment by sv-sdeiac** [comment]
I can reproduce this issue using the latest version of RC 3.0.2 #20081834 on Nokia 6 (Android 7.1.1).
Also, using Xiaomi MiPad 2 (Android 5.1 - arch x86) the ETP tooltip is cut.
![Screenshot_2020-01-09-15-40-00](https://user-images.githubusercontent.com/40264165/72069245-6ae22700-32ef-11ea-9cd4-98b43d12a450.png)

**Comment by ixti** [comment]
@sv-sdeiac Why closing this issue if it's not fully fixed? Just curious.

**Comment by sv-sdeiac** [comment]
> @sv-sdeiac Why closing this issue if it's not fully fixed? Just curious.

@ixti, since the latest Nightly is verified as fixed, the next build of beta/RC will take this fix.

**Comment by ixti** [comment]
@sv-sdeiac Oh, sorry. Somehow I've totally skipped the rest of the message after the first screenshot... Got it now. Thank you!
