### ISSUE TITLE
[Bug] hints about top  toolbar elements are misaligned

### ISSUE THREAD

**Issue by ixti** [mozilla-mobile/fenix#7182]
## Steps to reproduce

- start fresh install of firefox preview
- configure it to have toolbar on top
- visit website with trackers

### Expected behavior

Hint about purple shield should have pointing edge touching shield icon and hint bubble should be below shield icon.

### Actual behavior

Hint bubble is placed over the shield icon with pointing edge downwards pointing to nowhere.

### Device information

* Android device: Samsuns Galaxy S10 5G
* Fenix version: 3.0.0 (Build #13431956)
* 📦: 24.0.0, 968f858c1
* 🦎: 71.0-20191125115111

**Comment by cadeyrn** [comment]
Duplicate of #7181.

**Comment by ixti** [comment]
Sorry, overlooked existing bug report. Closing this now.

**Comment by ixti** [comment]
Oh. This duplicate happened due to network labs. (( sorry about this
