### ISSUE TITLE
[Bug] PWA has unnecessary bottom margin

### ISSUE THREAD

**Issue by emilio** [mozilla-mobile/fenix#7183]
## Steps to reproduce

Open a PWA like Twitter.

### Expected behavior

Full screen app.

### Actual behavior

There's an ugly bottom margin suspiciously of the same size as the custom tab margin :)

I think this is a regression from https://github.com/mozilla-mobile/fenix/pull/7126, cc @ekager 

### Device information

* Android device: Galaxy A20
* Fenix version: Nightly

**Comment by emilio** [comment]
Screenshot: ![Screenshot_20191215-161133_Firefox Nightly](https://user-images.githubusercontent.com/1323194/70864769-a5a5a900-1f55-11ea-92d2-435fc0f6b670.jpg)

**Comment by emilio** [comment]
cc @NotWoods

**Comment by creesch** [comment]
Can confirm that this is also the behavior for PWAs on other domains.

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **Nightly Build #13540607from 12/20** using the following devices:
• Google Pixel 3a (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

► Video
![20191220_115149](https://user-images.githubusercontent.com/51314259/71246540-8628ca80-231f-11ea-9bf5-663a3b57dd1f.gif)
