### ISSUE TITLE
[Bug] fenix bottom bar covers up Reddit "open in browser" button, when opened in custom tab

### ISSUE THREAD

**Issue by dholbert** [mozilla-mobile/fenix#7184]
## Steps to reproduce
1. Make fenix be the system webview for other apps to use for web content (I forget how I did this - maybe it's just making it the default browser?)
2. Open the Twitter Android app and view a tweet with a link to a Reddit post. E.g. 
https://twitter.com/rabimba/status/1206192610177511424?s=19
3. Tap the Reddit link to open in-twitter-app Fenix webview.
4. Look at the buttons at the bottom of the Reddit page.

### Expected behavior
The "See this post in... Browser" button should be visible.

### Actual behavior
The button is covered by the URL bar.

### Device information

* Android device: Pixel 3
* Fenix version: 3.0.0 (Build #13431956)
📦: 24.0.0, 968f858c1
🦎: 71.0-20191125115111

This only affects the in-another-app webview experience. If I perform the STR entirely in Fenix itself (using the Twitter website instead of Twitter app), then I get expected results.

**Comment by dholbert** [comment]
Screenshot of Actual Behavior (the bug):
![Screenshot_20191215-121103](https://user-images.githubusercontent.com/426803/70868772-daefce00-1f38-11ea-9868-5b40322edc6d.png)

**Comment by dholbert** [comment]
Screenshot of expected results (when performing STR entirely in Fenix with Twitter website instead of app):
![Screenshot_20191215-124109](https://user-images.githubusercontent.com/426803/70868792-fce95080-1f38-11ea-803d-c62641a4ea9f.png)

**Comment by dholbert** [comment]
Another simpler affected site (not Reddit): https://heximal-clock.glitch.me/


When loaded from the Twitter Android app via e.g. this tweet, the numeric time at the bottom gets covered by the Fenix custom-tab location bar:
https://twitter.com/tabatkins/status/1209969194843828224?s=19

Screenshot:
![Screenshot_20191225-170057](https://user-images.githubusercontent.com/426803/71452263-29227f80-2738-11ea-8547-27af45f0ecd1.png)

**Comment by mcarare** [comment]
This should have been fixed by https://github.com/mozilla-mobile/fenix/commit/686facffc6ca21c1c38765306507f2269f5314b5.
QA, can you please check? TY!

**Comment by abodea** [comment]
Verified as fixed on the latest version of Nightly from **1/7** using **Samsung Galaxy S10+(Android 9).**

Note that I tried with both websites(with the twitter app): `reddit` and `/heximal-clock.glitch.me/` following the same scenario from the description.
Also, note that I verified this issue on **`Fenix Private-Browsing`** **`Custom Page`** and it worked as expected, the bottom was displayed correctly.

Based on my comment I will close this issue.
