### ISSUE TITLE
[Bug] Displaying prompt from other page

### ISSUE THREAD

**Issue by marcinwiacek** [mozilla-mobile/fenix#7187]
## Steps to reproduce

1. google.com -> will open browser
2. click on Settings on bottom -> will open settings screen
3. click on "region for current search" -> will open list of countries
4. click back button -> it will close list of countries
5. enter any other url in url bar and open new page -> page is opened with list of countries from 3

### Actual behavior

There is opened new page in step 5 without list of countries

### Device information

* Android device: S7/Android 8
* Fenix version: nightly

**Comment by ekager** [comment]
Just was able to reproduce this with the STR.

**Comment by sflorean** [comment]
I was able to reproduce this issue following the STR provided on Beta 80.0.0-beta.2, but not on Nightly 8/4.
Devices: Samsung Galaxy Note 10(Android 10), Huawei MediaPad M2	(Android 5.1.1).

**Comment by ekager** [comment]
This fix in AC didn't make it into the current Beta. cc @liuche if you think this is an important fix to pull into our stable AC version?

**Comment by liuche** [comment]
We won't take this in 80.0.0, but we'll get it in 81.
