### ISSUE TITLE
Adding page title in page info

### ISSUE THREAD

**Issue by marcinwiacek** [mozilla-mobile/fenix#7189]
### Why/User Benefit/User Problem

User can feel more comfortable, when will have more info about opened page - currently can see for example URL (which is many times coded and long).

### What/Requirements

Please add page title to this screen above URL

![Screenshot_20191215-195638_Firefox Nightly](https://user-images.githubusercontent.com/24834168/70873100-4a52d580-1fac-11ea-863d-a59bf08dcad6.jpg)

**Comment by NotWoods** [comment]
Approved by UX in #7255.

**Comment by marcinwiacek** [comment]
Note: this was implemented and this issue can be closed.
