### ISSUE TITLE
Device name resets after device reboot when there's no network connection

### ISSUE THREAD

**Issue by SL-Lee** [mozilla-mobile/fenix#7199]
# Steps to reproduce

1. Login to Firefox Sync.
2. Change the device name to something else and perform a manual sync.
3. Close the application, disconnect from wifi / mobile data and reboot the device.
4. Open Firefox Preview again, and check the device name.

# Expected behavior

The device name doesn't change after a reboot.

# Actual behavior

The device name resets to the default "Firefox Preview on..."

# Device information

* Android device: Oppo Reno 2
* Fenix version: 3.0.0

**Comment by mcarare** [comment]
Not reproducible on a Huawei P10 - Android 9 (Fenix version: 3.0.0 and latest master)

**Comment by boek** [comment]
I am also unable to reproduce on a Pixel. What version of Android are you using @SL-Lee?

**Comment by SL-Lee** [comment]
I'm on Android 9. I have noticed that this behavior seems to occur only when you disconnect from wifi / mobile data before performing a reboot, could you please try reproducing this again? (I have also edited the "Steps to Reproduce" section to include this step I missed out.)

**Comment by pwd-github** [comment]
I'm seeing this happen randomly, though I always have a connection, so I don't think the connection bit is a factor.

**Comment by soumya92** [comment]
Related to #6565?

**Comment by 532910** [comment]
> Related to #6565?

No!

**Comment by 532910** [comment]
This is the most anoning bug for me!
