### ISSUE TITLE
[Bug] Still see parts of bottom app bar for PWA

### ISSUE THREAD

**Issue by topotropic** [mozilla-mobile/fenix#7201]
## Steps to reproduce
1. Go to twitter.com
2. Add to home screen
3. Open twitter.com

### Expected behavior
twitter.com opens in full screen w/o browser chrome

### Actual behavior
still see the grey background of the bottom app bar

### Device information

* Android device: Pixel 3
* Fenix version: Nightly 191216

![Screenshot (Dec 16, 2019 1_58_10 PM)](https://user-images.githubusercontent.com/353960/70908999-d5fc4e80-200c-11ea-8ca5-861bf868eca4.png)

**Comment by creesch** [comment]
Seems to be the same issue as #7183  

Can confirm the behavior for other PWAs

**Comment by topotropic** [comment]
Thanks @creesch !

Closed as dupe of https://github.com/mozilla-mobile/fenix/issues/7183
