### ISSUE TITLE
Update branding of fennecNightly build type

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/fenix#7203]
Currently a build of `fennecNightly` will look just like any other "Firefox Preview" build. That's probably not our intention and can be quite confusing.

My assumption (!) is that we want to:
- Name it "Firefox Nightly" like the existing app
- Use the same (updated) icon as the existing app
- Update the big "Firefox Preview" banner on the home screen with something else (?)
- Update any other "Firefox Preview" references - are there any?

**Comment by cadeyrn** [comment]
@pocmo Is it intended that you added the old Firefox Nightly logo and not the current one?

**Comment by ebalazs-sv** [comment]
I had tested this on Nightly migration build 01/15 with Samsung Galaxy S8 (Android 9), Huawei Honor 8 (Android 7.0), Xiaomi Mi4i (Android 5.0.2) and as mentioned in the previous comment, the Fennec Nightly logo is displayed.

**Comment by cadeyrn** [comment]
> and as mentioned in the previous comment, the Fennec Nightly logo is displayed.

To be clear: What I meant was that the **_wrong_** Fennec Nightly logo is used.

![logo](https://user-images.githubusercontent.com/1100614/72434192-4973b600-379b-11ea-8d46-d27682dc9d06.png)

**Comment by sv-ohorvath** [comment]
The 1/16 migration build still has the old Fennec icon.

**Comment by pocmo** [comment]
Yes, it is intended to continue using the old Fennec app icon for now (same as before the migration). We will switch to the new icon once we consolidate our channels (firefox preview vs. firefox for android).

**Comment by ebalazs-sv** [comment]
Verified as fixed on Fennec Migration Nightly build 1 with Samsung Galaxy S8 (Android 9) - ARM64, Xiaomi Mi Pad 2 (Android 5.1) - x86, OnePlus 6T (Android 9.0) - ARM.
I will move this to Done. Thanks!
