### ISSUE TITLE
Support the ACTION_SEARCH Android intent

### ISSUE THREAD

**Issue by georgelemental** [mozilla-mobile/fenix#7204]
### Why/User Benefit/User Problem
Allows searching in Firefox from apps that use the Android search intent, like Moon+ Reader. Otherwise, searching from these apps launches the Google or Bing apps, or another browser that does support the intent.
### What/Requirements
Support the https://developer.android.com/reference/android/content/Intent#ACTION_SEARCH intent.
### Acceptance Criteria (how do I know when I’m done?)
Broadcasting the Search intent from an app launches a web search in Firefox.

**Comment by NotWoods** [comment]
I think we could add this action the manifest and write an intent processor for it.

**Comment by salpiras** [comment]
Hi! Is this still up for grabs? I can work on it. I was planning to route it through the IntentReceiverActivity and write an IntentProcessor similar to the TabIntentProcessor in the components layer

**Comment by NotWoods** [comment]
@salpiras Yes, this is still available! Your approach sounds good.

**Comment by salpiras** [comment]
Should be addressed by PRs [Fenix](https://github.com/mozilla-mobile/fenix/pull/7406) and [Components](https://github.com/mozilla-mobile/android-components/pull/5426)

**Comment by hakkikaancaliskan** [comment]
@NotWoods this is already fixed.
