### ISSUE TITLE
[Settings] About Firefox - Link colour is wrong in dark theme

### ISSUE THREAD

**Issue by AmyYLee** [mozilla-mobile/fenix#7207]
1. Set Fenix to Dark theme (Settings -> Theme)
2. Go to Settings -> About Firefox

Expected:
Links are visible and passes contrast test - Text link colour should be Violet 40 #AB71FF

Actual: 
Links are too dark to see and fail contrast test

![Screenshot_20191216-113940](https://user-images.githubusercontent.com/5992746/70925464-4305e900-1ff9-11ea-9884-b8d378be8798.png)

**Comment by tvenissat** [comment]
May I be assigned this issue?

**Comment by boek** [comment]
@tvenissat yes of course! Are you still interested in working on this?

**Comment by KaairaGupta** [comment]
@boek can i work on this?

**Comment by tvenissat** [comment]
@boek Yes. I am still interested. Can you assign it to me, please?

**Comment by KaairaGupta** [comment]
@boek isn't the color of the links in the screenshot provided by @AmyYLee visible too? I mean what exactly is this color to be changed to?

**Comment by AmyYLee** [comment]
>     1. Set Fenix to Dark theme (Settings -> Theme)
> 
>     2. Go to Settings -> About Firefox
> 
> 
> Expected:
> Links are visible and passes contrast test - Text link colour should be Violet 40 #AB71FF

@KaairaGupta - The link colour should be Violet 40 #AB71FF in Dark theme. Right now it fails contrast tests for accessibility. Thanks!

**Comment by tvenissat** [comment]
@AmyYLee Where are the contrast/accessibility tests and how do I run them? The only tests I have found check the visibility (Visible, Invisible, or Gone) or font size of the links and not their color.

**Comment by AmyYLee** [comment]
> @AmyYLee Where are the contrast/accessibility tests and how do I run them? The only tests I have found check the visibility (Visible, Invisible, or Gone) or font size of the links and not their color.

I use this https://webaim.org/resources/contrastchecker/

**Comment by KaairaGupta** [comment]
@AmyYLee please review my PR for this issue

**Comment by cadeyrn** [comment]
@KaairaGupta It's great that you contribute to Fenix but did you notice that both this issue and also #7414 were already assigned to another contributor? Maybe you could check this the next time because it's not fair for the others and there are still enough issues without assignee…

**Comment by KaairaGupta** [comment]
@cadeyrn i am really sorry for this. I am new to opensource, these two being my first PRs, and i wasn't aware of this. Thanks for correcting me. I'll keep this in mind the next time.

**Comment by tvenissat** [comment]
@AmyYLee Thank you for the link. Also, I am new to git and not sure on how to proceed. Changing the value of `accent_bright_dark_theme` will affect more than just the `about_list_item.xml` text color. At the very least, it will break the `onboarding_card_background_dark.xml` and `fenix_snackbar.xml` since both of those layouts use the same color value when the dark theme is active. So, should I commit multiple times in the same pull request, handling not only this issue but the resulting issues as well? Or just fix this issue alone and file/document the others that I find?

**Comment by AmyYLee** [comment]
> @AmyYLee Thank you for the link. Also, I am new to git and not sure on how to proceed. Changing the value of `accent_bright_dark_theme` will affect more than just the `about_list_item.xml` text color. At the very least, it will break the `onboarding_card_background_dark.xml` and `fenix_snackbar.xml` since both of those layouts use the same color value when the dark theme is active. So, should I commit multiple times in the same pull request, handling not only this issue but the resulting issues as well? Or just fix this issue alone and file/document the others that I find?

@sblatz Hi, can you help with answering this question? Thanks
