### ISSUE TITLE
[Bug] Menu is heavily truncated on localized builds

### ISSUE THREAD

**Issue by flodolo** [mozilla-mobile/fenix#7209]
cc @Delphine 

I'm currently using the Italian version. Often the menu is so heavily truncated that I have no clue what the menu does, even if the string has been translated as short as possible.

Is there any chance to display more content?

![Screenshot_20191216-180024](https://user-images.githubusercontent.com/3644868/70926857-27690580-202e-11ea-9530-d6efc01e16cf.jpg)

**Comment by mcarare** [comment]
Related issue: https://github.com/mozilla-mobile/fenix/issues/7049.

**Comment by boek** [comment]
I'm going to close this as a dup of #7049. I added it to group triage to see if we can get it prioritized.
