### ISSUE TITLE
Tabs UI has incorrect shadow on Galaxy S9

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#721]
I'm only able to see this on my S9 and cannot reproduce on a Pixel device. We need to test more to see if this is a screen size/dimension issue or a Samsung specific one.

<img width=300 src=https://user-images.githubusercontent.com/4400286/53449518-d3bdfa80-39ce-11e9-8161-498a8cc85942.jpg>

**Comment by bsurd** [comment]
Tried on several devices but the issue didn't reproduce on my end. 

Devices:
 - Google Pixel (A9)
 - Samsung Galaxy S8 (A8)
 - Samsung Galaxy Note 8 (A8)
 - HTC 10 (A8)
 - Nokia 6 (A7.1.1)

**Comment by cadeyrn** [comment]
I couldn't reproduce the issue with the HTC U11 but with today's changes from master the _session bundles_ (not the tabs) has an incorrect shadow (similar to the shadows in comment 0) on HTC U11.

**Comment by sblatz** [comment]
@cadeyrn are you able to provide a screenshot? It'd be super helpful in diagnosing this!

**Comment by cadeyrn** [comment]
It's already fixed by https://github.com/mozilla-mobile/fenix/commit/abd225463a3870d158015f818f565c34557aaeb3. :)
