### ISSUE TITLE
Add tests to check for straight quotes in strings

### ISSUE THREAD

**Issue by flodolo** [mozilla-mobile/fenix#7210]
I know very little of the current technical infrastructure, but I couldn't help noticing that sometimes strings land with the wrong apostrophe, and that's manually caught by Delphine during review.

Would it be possible to automate that kind of checks via tests?

CC @Delphine @Pike

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-14841)

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813186

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
