### ISSUE TITLE
Investigate possible dropped frames alerts from systrace on Fenix start up 

### ISSUE THREAD

**Issue by MarcLeclair** [mozilla-mobile/fenix#7216]
### Why/User Benefit/User Problem
When running systrace tool, Fenix start up gets alerts from (1) doing too much work animation wise and onMeasure. This leads to some small jank that could (possibly) help create a smoother and faster start up.

### Impact
Opening the app seems to be janky at times with the Moto g5. From regular trace, one can notice a long calls to onMeasure. On top of that, systrace results shows alerts on the RenderThread. Fixing those could create a smoother feeling on launche.

### Acceptance Criteria (how do I know when I’m done?)
Alerts are gone from the systrace file, and operations shown on the UI thread are continuous at a regular interval with no large "dropped" sections.

**Comment by mcomella** [comment]
Triage: we want to make concrete progress on known cold startup issues before doing more investigation. Also, this may uncover more UI problems than all problems so, given it focuses on a subset of the issues, it's less important.

**Comment by mcomella** [comment]
Tracking dropped frames analyses on JIRA: https://jira.mozilla.com/browse/FXP-1254
