### ISSUE TITLE
[Bug] truncated text in tracking protection info screens

### ISSUE THREAD

**Issue by cadeyrn** [mozilla-mobile/fenix#7217]
### Steps to reproduce

0. use your phone in a language with larger words than in English, for example German
1. open Menu > Settings > Enhanced Tracking Protection
2. press one of the two (i) buttons 

### Expected behavior

No truncated text.

### Actual behavior

The cryptomining text is truncated.

![Screenshot_20191216-212657](https://user-images.githubusercontent.com/1100614/70940935-af113d00-204b-11ea-9c4e-0e05ab3dfc03.jpg)

### Device information

* Android device: OnePlus 7T Pro McLaren Edition with Android 10
* Fenix version: Firefox Preview 3.0.0 and master branch revision 90c77519a60a4f742d20d644a40d047dfd63093d

**Comment by ekager** [comment]
For whoever picks this up: 
[We will want to make sure the title in this xml file can wrap correctly with large text. ](https://github.com/mozilla-mobile/fenix/blob/master/app/src/main/res/layout/tracking_protection_category.xml)

Also, let's refactor those ids to something that actually matches the layout. `trackingProtectionCategoryIcon` etc

**Comment by sim031999** [comment]
I am new to open source but I have understood the issue. Can I work on this?

**Comment by ekager** [comment]
Reopening for QA

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **Nightly Build #20100616 from 01/10** using the following devices:
• Google Pixel 3a (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

► Screenshot
![rsz_screenshot_20200110-094716](https://user-images.githubusercontent.com/51314259/72135355-f4950180-338e-11ea-8de6-176e3fb2cdfa.png)
