### ISSUE TITLE
[Bug] missing padding in download button, inconsistent button styling

### ISSUE THREAD

**Issue by cadeyrn** [mozilla-mobile/fenix#7219]
### Steps to reproduce

1. download a file

### Expected behavior

same styling for download and open button.

### Actual behavior

The download button has no padding on the left and the right, also the download button has a different color than the open button after the download.

![Screenshot_20191212-235041](https://user-images.githubusercontent.com/1100614/70942308-aec67100-204e-11ea-99c4-ad8bfd92aac6.jpg)
![Screenshot_20191212-235031](https://user-images.githubusercontent.com/1100614/70942316-b2f28e80-204e-11ea-82b8-2b79ed940473.jpg)

### Device information

* Android device: OnePlus 7T Pro McLaren Edition with Android 10
* Fenix version: Firefox Preview 3.0.0 and master branch revision 90c77519a60a4f742d20d644a40d047dfd63093d

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **Nightly build #13530608 from 12/19** using the following devices:
• Google Pixel 3a (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

►Screenshots
![black](https://user-images.githubusercontent.com/51314259/71164645-2ca99880-2258-11ea-8bf4-d8e9d7c93062.png)

![white](https://user-images.githubusercontent.com/51314259/71164658-3206e300-2258-11ea-9f8e-25faebe598ab.png)

@ekager - Seems like the "Download completed" context menu is larger than the "Download" confirmation context menu.
Please review and let me know if I should open a new issue. ☺️

**Comment by cadeyrn** [comment]
@AndiAJ 

> verified as fixed

In your screenshots the padding of the download button is still missing, only the color is changed. 🤔

**Comment by AndiAJ** [comment]
As per @cadeyrn 's remark I'll re-open this issue.

Sorry for the inconvenience.

**Comment by cadeyrn** [comment]
It's fixed in the current build. I guess https://github.com/mozilla-mobile/android-components/pull/5328 was not yet included the last time.
