### ISSUE TITLE
Add delete session button to private browsing

### ISSUE THREAD

**Issue by boek** [mozilla-mobile/fenix#722]
On the mocks we have a delete session button. We should add it

**Comment by sblatz** [comment]
I totally blanked this 😅 thanks for filing.

**Comment by sblatz** [comment]
For reference:

https://user-images.githubusercontent.com/51007/51957894-53c97100-24b2-11e9-8a3a-66f07f59b9d4.png

**Comment by sv-ohorvath** [comment]
Verified as fixed.
