### ISSUE TITLE
Enable more aggressive StrictMode penalties on startup in debug builds

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#7225]
See #7226 for aggressive StrictMode being enabled everywhere.

### What
StrictMode allows us to identify performance issues where users do IO on the main thread. Since we're making improvements to startup, we don't want it to regress: we should enable more advanced penalties such as a blocking dialog or crashing the app to ensure we don't regress the behavior. Note that devs can override the behavior for a single operation if the main thread IO is necessary.

### Impact
Without this, we may suffer from unintentional regressions as users do main thread IO, esp. from SharedPreferences calls, on startup. With this, devs will be more aware and may think of alternative solutions.

### Acceptance criteria
- StrictMode with more aggressive penalties is enabled for startup and disabled after startup
  - Is realistic? detekt rule instead?
- Violations are either fixed or ignored. If they are ignored but fixable, we should file an issue on our project board to address them

**Comment by mcomella** [comment]
Here's some notes on accessing `SharedPreferences` on the main thread, from 9 years ago: https://stackoverflow.com/a/4371883

**Comment by hawkinsw** [comment]
I do not believe that we can do this detection offline. I don't think that detekt has enough context when it executes to determine whether a) the method cannot be called on MT and/or b) the method is invoked in a context that actually moves it off the MT (e.g., a `CoroutineScope`).
