### ISSUE TITLE
Enable StrictMode everywhere

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#7226]
#7225 implemented StrictMode penalty death for start up. We should also enable penalty death at all times to catch performance regressions, particularly main thread IO, for all interactions in the app.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-14852)

**Comment by mcomella** [comment]
Tracking on JIRA: https://jira.mozilla.com/browse/FXP-1242

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807358

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
