### ISSUE TITLE
[Bug] music played in background stops when videos started on another site

### ISSUE THREAD

**Issue by karlcow** [mozilla-mobile/fenix#7236]
## Steps to reproduce
1. Having a Spotify song playing in the background on Firefox Preview Nightly, 
2. reaching a video on the Twitter website

### Expected behavior
Not sure but the user expected the sound to continue
see https://github.com/webcompat/web-bugs/issues/46619

### Actual behavior
makes the audio from the Spotify app stop.

### Device information

* Android device: Huawei P10 (Android 9.0) - 1080 x 1920 pixels (~432 ppi pixel density)
* Fenix version: Firefox Preview Nightly 191216 (🦎: 72.0a1-20191212095326), Chrome Mobile 78.0.3904.108

The issue is not reproducible on Firefox Release 68.3.0.

**Comment by sblatz** [comment]
Closing as dup of #6146
