### ISSUE TITLE
[Bug] Release 3.0.1 does not include an APK

### ISSUE THREAD

**Issue by Vinnl** [mozilla-mobile/fenix#7237]
## Steps to reproduce

Visit https://github.com/mozilla-mobile/fenix/releases/tag/v3.0.1

### Expected behavior

For there to be six assets, adding four APKs for different architectures.

### Actual behavior

There are just two assets, labelled "Source code".

### Device information

N/A

Related: #6451

**Comment by cadeyrn** [comment]
I don't think you have to open an issue for every new release (2.3.0, 3.0.0, 3.0.1). In #7082 @AaronMT said:

> APK will be published when we reach full roll-out (100% of population).

And since I didn't 3.0.1 via Google Play Store I would say there is no full roll-out yet.

**Comment by Vinnl** [comment]
Ah sorry @cadeyrn, in #6451 I was given the impression that it was simply an oversight. Thanks for the update!
