### ISSUE TITLE
[Bug] m.youtube.com don't play in background

### ISSUE THREAD

**Issue by survivor303** [mozilla-mobile/fenix#7238]
## Steps to reproduce
Open mobile version of the YouTube (m.youtube.com) go to any video page and press the play button. Going out of the browser, like to launcher home screen.
### Expected behavior
The video should continue to play in background, like it do in desktop version of the site (youtube.com).
### Actual behavior
Immediately after i got to home screen of the launcher, video stop playing.
### Device information

* Android device: Asus Zenfone 6
* Fenix version: Nightly 191217 06:01 (Build #13510607)

**Comment by Dunexus** [comment]
Youtube uses Page Visibility API to disable background video.

See https://github.com/mozilla-mobile/fenix/issues/5527 for more information

**Comment by survivor303** [comment]
Well yes, like you self linked to https://github.com/mozilla/video-bg-play. It is possible to add this behavior to the browser itself to prevent these annoyances to happen for end users. Browsers don't need to respect these kind of artificial limits who make end users experience bad and promotes whatever site $$$ features. Mozilla want to fight against these kind of web designs. (free and safe).

**Comment by survivor303** [comment]
@cadeyrn it is very important that you also say what you have in mind?

**Comment by cadeyrn** [comment]
> browsers don't need to respect

You demand that Mozilla ignores web standards… It is perfectly legitimate for websites to use the Page Visibility API. To disable the API is something add-ons can provide but it would be totally inappropriate to do this by default.

> it is very important that you also say what you have in mind?

a little impatient? I takes some time to write a comment…

**Comment by survivor303** [comment]
It is better to be in browser itself, it not needed to be enabled by default but have it in the browser settings is better than without it. Yes addons can do these kind of things but then we need to trust that addon keep itself updated and working order all the time. Better is if Firefox devs can add these valuable features to the browser itself, so users don't need to find everything from addons. what can also  be even a security risk, why companies have disabled addons installs from the end users.

Gnome way of doing things, isn't the best one ;)

**Comment by mcarare** [comment]
I agree with @cadeyrn , I don't think any browser should enforce disregarding legitimate websites settings.

**Comment by boek** [comment]
Closing as a dup of #5527. Like https://github.com/mozilla-mobile/fenix/issues/5527#issuecomment-534989831 explained this will most likely be an option when Extensions land :)

**Comment by survivor303** [comment]
These guys just ignore the first problem what i trying to explain . I say that New Firefox doesn't background play media when it comes to mobile site of any player included site. and asking that if Firefox devs can just make a option to the settings that allow users to get background player working. It isn't that we need to broke anything from the standard but we can offer better experiences and options for end users.

**Comment by Dunexus** [comment]
Background media works. You can test by going to https://www.w3schools.com/html/html5_video.asp, play the video, press home, the audio is still playing in background with a notification.
If you are talking about PiP, it is tracked in this issue https://github.com/mozilla-mobile/fenix/issues/2818
