### ISSUE TITLE
Audit & consolidate color choices

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#724]
Currently we have *lots* of different hex values in our colors.xml that are just slightly different variations of each other since we've had to use a color picker to get values (which is prone to error).

It'd be super helpful if we had a color palette to work off that had all the values we needed for the different themes and what they're supposed to apply to, that way we can achieve the pixel perfect design we've spent so long creating!

**Comment by sblatz** [comment]
On top of the comments mentioned above: some of the colors/designs have changed since we implemented the features. We should do an audit of _all designs_ and see where things don't match up as part of this ticket.

I would argue this is a requirement for MVP. Are we able to prioritize this? cc: @vesta0

**Comment by shorlander** [comment]
@sblatz Are we mapping the values to keywords? E.g. ui_grey = #fbfbfe, accent = #0060DF etc. 

Would it help to talk about how we are using them in the design? Using similar patterns might make it easier to maintain and to change in the future.

**Comment by sblatz** [comment]
@shorlander yes, I think that'd be really helpful. You can find the naming conventions we're using for the colors we have [here](https://github.com/mozilla-mobile/fenix/blob/master/app/src/main/res/values/colors.xml). I'd be happy to meet about this, as I think having a similar "language" for these values would reduce a lot of friction.

**Comment by sblatz** [comment]
We should also take font styles/weights into consideration in this [e.g. this style](https://github.com/mozilla-mobile/fenix/pull/882/files#diff-c88f525159e9f49227dae6bdd37841fdR52)

**Comment by shorlander** [comment]
@sblatz is there anything for UX to do here after our conversation?

**Comment by sblatz** [comment]
@shorlander I think for now, no. That being said, when we do put this into a sprint, it'd be great for some of the engineering team and UX to sit down and actually go through the app to confirm that elements look correct, as well as solidify the (small) number of colors/styles we want to use.

**Comment by sblatz** [comment]
@shorlander I think for now, no. That being said, when we do put this into a sprint, it'd be great for some of the engineering team and UX to sit down and actually go through the app to confirm that elements look correct, as well as solidify the (small) number of colors/styles we want to use.

**Comment by sblatz** [comment]
Emily, Stephen, Amy and I all met to discuss over [this document](https://docs.google.com/document/d/1EyFqVkR31iz4Cy4QTMlmN_O4rY_5ChCwJO4pMdCxpUw/edit). 

Action items:
* UX will verify the hex values given for the different attributes
* UX will defined additional attributes as they are needed
* Engineering will send UX updated screenshots once they have these values

**Comment by sblatz** [comment]
I'm going to close this as the color audit is done. Any additional UX/UI changes can be filed as follow-ups :)
