### ISSUE TITLE
[Bug] "Privacy notice" opens in russian on Google Pixel (Android Q)

### ISSUE THREAD

**Issue by softvision-miralobontiu** [mozilla-mobile/fenix#7240]
## Steps to reproduce
1. Go to Settings - About Firefox Nightly
2. Tap on Privacy notice link.

### Expected behavior
A different page opens in a custom tab - in English.

### Actual behavior
A different page opens in a custom tab but in Russian.

### Device information
* Android device: Google Pixel (Android Q)
* Fenix version: 191217 (#13510607)

![Screenshot_20191217-russian](https://user-images.githubusercontent.com/40694158/70986025-cb51c000-20c5-11ea-91bd-5a6ae4d78ac4.png)

[rusa.txt](https://github.com/mozilla-mobile/fenix/files/3972628/rusa.txt)

**Comment by boek** [comment]
@softvision-miralobontiu Hmm.. I'm not able to reproduce.

The page loads based on the locale of the device, looking on the device it looks like it's initially loading `https://www.mozilla.org/ru/privacy/firefox/` so it doesn't look like it redirected.

**Comment by AndiAJ** [comment]
Hi, @boek is right, the loaded page depends on the locale.
I've checked this matter, and **could't reproduce** on the latest **Nightly build #13530608 from 12/19** using the following devices:
• Google Pixel 3a XL (Android 10)
• Google Pixel 3a (Android 9)

► Video
![20191219_111449](https://user-images.githubusercontent.com/51314259/71161452-084abd80-2252-11ea-8914-54ebaa8e4448.gif)

@softvision-miralobontiu Please review and re-open the issue in case you manage to reproduce the issue. ☺️

**Comment by softvision-miralobontiu** [comment]
I will reopen this issue since I'm still reproducing it on the latest Nightly build from 12/23 (#13570608).
The only device affected is Google Pixel (Android Q), and it is reproducible 100%.

**Comment by boek** [comment]
@softvision-miralobontiu what is your device locale set to?

**Comment by sv-sdeiac** [comment]
The local is set to English and I tested with other SUMO pages to see the difference and the issue.

![20191230_100527](https://user-images.githubusercontent.com/40264165/71573971-271d3f80-2aef-11ea-8fb3-77def1678941.gif)

**Comment by sv-sdeiac** [comment]
Using Google Pixel (Android Q) with Firefox Preview 1/6 @6:05 AM, the language is changed to Deutsch for privacy notice.

**Comment by softvision-miralobontiu** [comment]
Apparently, the issue reproduces only on Google Pixel (Android 10), and the "Privacy notice" page opens in the second language set in Settings-Languages.
I've set French the second language, and the "Privacy notice" page opened in french.
Reproduced on Beta 3.2.0-beta.1.

**Comment by softvision-miralobontiu** [comment]
I was not able to reproduce the issue anymore on Google Pixel (Android 10) on the latest Nightly build from 12/15.
I'll close this issue.
