### ISSUE TITLE
Attach with synced account failes on fenix using QR-Code

### ISSUE THREAD

**Issue by Hubfront** [mozilla-mobile/fenix#7241]
Signing in to firefox account to sync data using email/password login both fennec and fenix state: "password incorrect". Even after i deleted/disconnected my firefox account on Firefox on PC and registered it again with same password on mobile it states password incorrect.

So i tried next to sign in to the sync account with fenix using the new QR-code method. After surfing to https://firefox.com/pair with firefox PC, fenix did read the QR code successfully, following an error message on firefox on PC stating: "Oh dear, something went wrong there. We've been notified and will get working on a fix."

**Comment by boek** [comment]
@Hubfront I think you may have gotten unlucky with trying to pair during some planned downtime with sync! If you're still able to reproduce please re-open filling out the [bug report template](https://github.com/mozilla-mobile/fenix/issues/new?assignees=&labels=%F0%9F%90%9E+bug&template=---bug-report.md&title=%5BBug%5D) :)
