### ISSUE TITLE
[Bug] Collection size change after expand/compress them

### ISSUE THREAD

**Issue by sv-sdeiac** [mozilla-mobile/fenix#7242]
## Steps to reproduce
1. Open Firefox Preview;
2. Create multiple collections;
3. Expand/compress some collections.

### Expected behavior
All collections have the same size.

### Actual behavior
The collection's size is changing after expanding/compressing them.

### Device information

* Android device: Motorola Moto G6 (Android 8) and Nexus 9 (Android 7.1.1);
* Fenix version: RC version 3.0.1 #13502255 12/16.
* Notes: This issue is not 100% reproducible and doesn't have exact steps to trigger the problem.
* Screenshot
![Screenshot_20191217-151054](https://user-images.githubusercontent.com/40264165/70998546-43c57a80-20e0-11ea-9605-7a02ce185c9a.png)

**Comment by topotropic** [comment]
https://github.com/mozilla-mobile/fenix/issues/8764 is going to solve this
