### ISSUE TITLE
Replace anko.dimen

### ISSUE THREAD

**Issue by NotWoods** [mozilla-mobile/fenix#7250]
Meta: #7085

- Replace all uses of `context.dimen()` with `context.resources.getDimensionPixelSize()`
- Replace all uses of `context.dimen().toFloat()` with `context.resources.getDimension()`

**Comment by kumarrus** [comment]
Hi, I am new to contributing to OSS. Can I please take on this issue?

**Comment by NotWoods** [comment]
Go for it!

**Comment by kumarrus** [comment]
@NotWoods There's a single instance of anko.px2dip that can be replaced with (context.resources.getDimension(id) / context.resources.displayMetrics.density). Should I include this in the same PR or file a separate issue for it?

**Comment by kumarrus** [comment]
@NotWoods Made the changes in PR #7279
