### ISSUE TITLE
Dark theme could have dark loading screen

### ISSUE THREAD

**Issue by aha999** [mozilla-mobile/fenix#7256]
When the dark theme is applied, the loading screen could be dark as well, instead of flashing white, when users press a search button.

**Comment by boek** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1610968

**Comment by nt1m** [comment]
I think https://bugzilla.mozilla.org/show_bug.cgi?id=1408122 might already have fixed this on the GeckoView side. It landed in Firefox 75.

**Comment by ekager** [comment]
Can reproduce on Nightly with GV76
STR:
1. Be in dark mode
2. Launch search screen, select DDG as search engine, and search something

**Comment by robsmith11** [comment]
According to he Gecko bug, a function to solve this already exposed.  Has anyone tried it on the Fenix side?

**Comment by ekager** [comment]
Yeah see https://github.com/mozilla-mobile/fenix/issues/6313
Closing this for that ticket now
