### ISSUE TITLE
[Bug] Cannot disable webrender

### ISSUE THREAD

**Issue by lindongbin** [mozilla-mobile/fenix#7262]
https://imgur.com/2HfriPe

when I enable webrender
all page zooming slowly
but it caannot be disabled any more
checked on about:support

* Android device: 
Mi Note3
* Fenix version: 
Nightly 191217 18:00 (Build #13511817)
26.0.0, 8b955ae06
GV: 73.0a1-20191216095052

**Comment by lindongbin** [comment]
I disable webrender by gfx.webrender.force-disabled

**Comment by kbrosnan** [comment]
This is working as intended then.
