### ISSUE TITLE
[Bug] Remove line between URL bar and Android gesture bar

### ISSUE THREAD

**Issue by ai** [mozilla-mobile/fenix#7266]
## Steps to reproduce

1. Open Firefox Preview on Android 10 with [`Settings > Display > Navigation bar > Full screen gestures`](https://android.gadgethacks.com/how-to/enable-android-10s-new-gestures-your-samsung-galaxy-with-one-ui-2-0209206/) enabled.
2. *There is no line between “Search on enter address” and Android gesture bar on the bottom.* It looks clean. ✅

![Screenshot_20191217-231541](https://user-images.githubusercontent.com/19343/71055534-0387eb80-2124-11ea-818a-888756a916f5.png)

3. Open any website
4. *There is a line between the URL bar and Android gesture bar on the bottom.* It looks not clear. ❎

![Screenshot_20191217-231240](https://user-images.githubusercontent.com/19343/71055521-f5d26600-2123-11ea-9166-8f1188e80f81.png)

### Expected behavior

I think we do not need this extra line between the URL bar and the Android gesture bar. It will be nice if on step 4 we do no have the line as well as we do not have it on step 2.

### Actual behavior

There is a line between the URL bar and Android gesture bar

### Device information

* Android device: Pixel 4 XL
* Fenix version: 3.0.0 (Build 13431956)

**Comment by boek** [comment]
@AmyYLee @topotropic Is this a bug?

**Comment by ai** [comment]
I checked other popular Android applications with the bottom bar, and most of them don’t have a line between the bottom bar and the Android gesture bar. Most of them use a black background for a gesture bar. But some of them use the same color for bottom bar and system gesture bar without line between them.

* Yandex Browser: black gesture bar.
* WhatsApp: black gesture bar.
* WeChat: gesture bar has the same color, no line between the text field and gesture bar.
* Telegram, VK chat: black gesture bar.

**Comment by AmyYLee** [comment]
> @AmyYLee @topotropic Is this a bug?

In the original mocks we had hairlines on the top and bottom. I'm okay with removing the hairline between the URL bar and the gesture bar. We are doing this in PBM. @topotropic What do you think?

**Comment by AmyYLee** [comment]
I spoke with @topotropic about this. Can you please set the the android gesture nav bar to black on Light/Dark themes. Thanks

**Comment by ai** [comment]
What is the next step for this issue?

**Comment by AmyYLee** [comment]
> I spoke with @topotropic about this. Can you please set the the android gesture nav bar to black on Light/Dark themes. Thanks

@ai Please see last comment. Can you set the android navigation bar to black for Light/Dark themes. Please leave Private browsing as is since it's already a dark purple. Thanks.

**Comment by ai** [comment]
Sure. Here is the latest stable Firefox Preview on Pixel 4 XL

![Screenshot_20200317-133644](https://user-images.githubusercontent.com/19343/76884728-8409d580-6854-11ea-8011-4c15b4776071.png)
![Screenshot_20200317-133654](https://user-images.githubusercontent.com/19343/76884737-8704c600-6854-11ea-9d54-0b9e9ba4eb41.png)
![Screenshot_20200317-133726](https://user-images.githubusercontent.com/19343/76884744-88ce8980-6854-11ea-921e-073b5dbd44bc.png)

**Comment by AmyYLee** [comment]
@ai I mean the bottom navigation bar. See below. Thanks

Dark/Light theme

<img width="376" alt="Screen Shot 2020-03-17 at 15 57 42" src="https://user-images.githubusercontent.com/5992746/76896441-2ed7bf00-6868-11ea-804d-655308a52136.png">

**Comment by ai** [comment]
@AmyYLee Google Pixel 4 doesn’t have this navigation bar by default. By default, it uses gesture navigation (similar to iOS) instead of 3-button navigation.

Gesture navigation draws only small navbar with a single dash in the middle.

Do you want me to switch to 3 buttons navigation to show the current Firefox Preview with this mode? (Firefox looks good with 3 buttons mode, the issue only about UX in gesture mode)

**Comment by AmyYLee** [comment]
> @AmyYLee Google Pixel 4 doesn’t have this navigation bar by default. By default, it uses gesture navigation (similar to iOS) instead of 3-button navigation.
> 
> Gesture navigation draws only small navbar with a single dash in the middle.
> 
> Do you want me to switch to 3 buttons navigation to show the current Firefox Preview with this mode? (Firefox looks good with 3 buttons mode, the issue only about UX in gesture mode)

@ai Hi, yeah I think we should still have the navigation bar coloured black (even in gesture mode it will still show a narrower version as shown in the screenshot).

**Comment by ai** [comment]
@AmyYLee yeap, it is a nice idea. Most apps with bottom panel do the same black gesture bar (WhatsApp, WeChat).

**Comment by Dunexus** [comment]
> @ai Hi, yeah I think we should still have the navigation bar coloured black (even in gesture mode it will still show a narrower version as shown in the screenshot).

It will be weird to have the status bar translucent (ie, showing app theme color) and the navigation bar black.
Also having the navigation translucent makes the app more integrated and web browsing more immersive.

**Comment by ai** [comment]
Another way is remove a line between bottom navbar and gestures bar. We already have it in Firefox Preview homepage

![Screenshot_20200318-192653](https://user-images.githubusercontent.com/19343/77016723-e2b37a00-694e-11ea-9135-1bd51bc9045d.png)

And many Google’s apps integrated gestures bar to their UI

![Screenshot_20200318-192827](https://user-images.githubusercontent.com/19343/77016751-f6f77700-694e-11ea-809a-e16372a5ae40.png)
![Screenshot_20200318-192802](https://user-images.githubusercontent.com/19343/77016757-fced5800-694e-11ea-9668-f21430b39bdd.png)
![Screenshot_20200318-192737](https://user-images.githubusercontent.com/19343/77016762-05de2980-694f-11ea-9608-87b938cac2a8.png)

**Comment by AmyYLee** [comment]
> Another way is remove a line between bottom navbar and gestures bar. We already have it in Firefox Preview homepage

@ai Works for me. Thanks

**Comment by ai** [comment]
@AmyYLee what is the next step? I’d like to help, but not sure that I know the righr programming language

**Comment by ekager** [comment]
So reading this thread it sounds like the action item here is to remove the bottom hairline from the homescreen toolbar? Is that correct @AmyYLee ?

**Comment by AmyYLee** [comment]
> So reading this thread it sounds like the action item here is to remove the bottom hairline from the homescreen toolbar? Is that correct @AmyYLee ?

Yes. I'm looking at Nightly right now and it seems it's already removed.

**Comment by ekager** [comment]
@AmyYLee it looks like on the browser screen it is still there in light and dark theme. Should we also remove it there?

**Comment by AmyYLee** [comment]
> @AmyYLee it looks like on the browser screen it is still there in light and dark theme. Should we also remove it there?

Oh I see it now. Yes please!

**Comment by ekager** [comment]
Our intern will be working on this bug, please don't pick this up

**Comment by abodea** [comment]
Verified as fixed on Nightly 5/18 with Google Pixel 4 XL (10).
Note that the bottom hairline is no longer displayed in the home screen or browser screen for light and dark themes.

![Screenshot_20200518-135149](https://user-images.githubusercontent.com/42831109/82205731-adf07e80-990f-11ea-93fc-c3abd4afdd0b.png)
