### ISSUE TITLE
[Bug] threejs example using WEBGL is not working

### ISSUE THREAD

**Issue by LaurentiuApahideanSV** [mozilla-mobile/fenix#7269]
## Steps to reproduce
1. Go to: https://threejs.org/examples/?q=gpu#webgl_gpgpu_protoplanet

### Expected behavior
Particles should be seen orbiting each other.
### Actual behavior
The canvas remains black.
### Device information

* Android device: Pixel 3 XL
* Fenix version: 
Firefox Preview 3.0.1 (Build #13502256) 12/16
Firefox Preview Beta 3.0.0-beta.3 (Build #13392157) 12/5
Firefox Preview Nightly 191218 (Build #13520613) 12/18
Firefox Release 68.3.0, Beta 68.4b2 see issue https://bugzilla.mozilla.org/show_bug.cgi?id=1604622

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **Nightly Build #20080616 from 01/08** using the following devices:
• Google Pixel 3a (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

► Video
![20200108_085749](https://user-images.githubusercontent.com/51314259/71957121-8e28ab80-31f5-11ea-88e0-41f7cf12bb1c.gif)
