### ISSUE TITLE
Highlighted text cannot be unselected by clicking elsewhere

### ISSUE THREAD

**Issue by colintheshots** [mozilla-mobile/fenix#727]
## Steps to reproduce
1. Open a page in the browser.
2. Long press to highlight text.
3. Tap on a blank area of the page.

### Expected behavior
Text should become unselected.

### Actual behavior
Text remains selected with the context menu open.

### Device information

* Android device: Pixel 3 XL, 9.0
* Fenix version: 1.0.1909 (Build #10571232 🦎 67.0a1-20190213102848)

**Comment by ekager** [comment]
@colintheshots Are you still seeing this today? I can't reproduce on latest Nightly

**Comment by vesta0** [comment]
This is fixed.
