### ISSUE TITLE
[Bug] Login entry fields do not seem to have chars limit - text overlapping if one of the details is long

### ISSUE THREAD

**Issue by isabelrios** [mozilla-mobile/fenix#7270]
## Steps to reproduce
Go to Settings -> Logins and Passwords -> Saved logins
### Expected behavior
The login entry is shown correctly
### Actual behavior
The long website overlaps all the other fields
### Device information
* Android device: Pixel 3, Android 10
* Fenix version: master 1a739db

Please see screenshot:
![Untitled](https://user-images.githubusercontent.com/1897507/71088149-17703380-219e-11ea-83a9-76ff4c45c3d6.png)

**Comment by softvision-miralobontiu** [comment]
Verified as fixed on the latest Nightly build from 3/16 with Sony Xperia Z5 Premium (Android 7.1.1), and OnePlus 5T (Android 9).
