### ISSUE TITLE
[Bug] No information shown in Saved logins view when user has not signed in yet or the list is empty

### ISSUE THREAD

**Issue by isabelrios** [mozilla-mobile/fenix#7272]
## Steps to reproduce
Go to Settings -> Logins and passwords -> Saved logins 
### Expected behavior
There is information letting user know that he needs to sing in 
### Actual behavior
White screen is shown 
### Device information

* Android device: Pixel 3, Android 10
* Fenix version: master 1a739db

Please see screenshot:
![IMG_4730](https://user-images.githubusercontent.com/1897507/71089293-d299cc00-21a0-11ea-8946-82cb6166cffb.JPG)

**Comment by isabelrios** [comment]
Same screen is shown if the login list is empty

**Comment by liuche** [comment]
@AmyYLee is there an empty state for this?

**Comment by AmyYLee** [comment]
> @AmyYLee is there an empty state for this?

We will need some copy for the empty state. I'm posting sample copy of what we have for Exceptions when it's empty for reference for @mheubusch to help with copy here.

<img width="377" alt="Screen Shot 2019-12-19 at 14 22 51" src="https://user-images.githubusercontent.com/5992746/71202966-253fba80-226b-11ea-8e21-c8ac0a79c99f.png">

**Comment by liuche** [comment]
@mheubusch could you get us some strings for the Logins empty state?

**Comment by mheubusch** [comment]
The logins you save or sync to Firefox will show up here. Learn more about [Sync](https://support.mozilla.org/en-US/kb/how-set-firefox-sync-firefox-preview).

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly Build #20290608 from 1/29`** using the following devices:

• Google Pixel 3a XL (Android 10)
• Google Pixel 3a (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

► Video
![20200129_101933](https://user-images.githubusercontent.com/51314259/73339717-ffea9700-4281-11ea-81c6-dc5e5f826dc4.gif)
