### ISSUE TITLE
settings: tracking protection options. meaninfull name

### ISSUE THREAD

**Issue by Wetterwolke** [mozilla-mobile/fenix#7285]
## Steps: 
go to the menue. To the tracking protection section

### Expected behavior: 
each option should have a unique meaningfull name.
For example rename the first option to : _Basic_ / _Einfach_ in geman

### Actual behavior: 
both are "standard" in german

### Device information

* Android device: ?
* Fenix version: 3.0.1
![Screenshot_20191219-021831_Firefox Preview](https://user-images.githubusercontent.com/54358393/71147129-884b3600-2206-11ea-98a4-ae4d9c0c722f.jpg)

**Comment by cadeyrn** [comment]
Unfortunately it's not that simple.

- In English the two options are "Standard" and "Strict (Default)".
- In German "Standard" is "Standard" and "Default" is "Standard", too. That's bad and I agree this should be solved.
- But in the German Desktop Firefox the first options is also named "Standard", so changing the name of this option in Fenix would introduce an inconsistency with the Desktop Firefox which is also bad.

🤔

**Comment by nilshg** [comment]
(Default) could be translated as "Voreinstellung" or "Standardeinstellung". IMHO "Normal" would probably be a better name than "Standard" for the less strict option, although I appreciate that consistency is important here - you might want to think about renaming the desktop option as well.

**Comment by ekager** [comment]
Looks like this is obsolete.
