### ISSUE TITLE
[Telemetry] App intent handling

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/fenix#7288]
#### Description & Product Manager / Data Scientist User Story
- As a product owner, I want to know how users interact with app link intents, so I have insight on how to improve this feature to address user needs, and better understand user preferences in terms of integration with other apps.

#### What questions will you answer with this data?
- What behaviour do users prefer: opening a link inside the browser or within the 3rd party app?

### Acceptance Criteria

- DS sign off on instrumentation methodology addressing product questions.
- Event pings can be queried via re:dash
- Event pings can be queried via amplitude
- We are sending telemetry events for the actions listed in the requirements
- We have documented the telemetry
- We have asked a data steward to review the telemetry

**Comment by sblatz** [comment]
@vesta0 do we need to create a data science request doc for this one?

**Comment by vesta0** [comment]
Here is the [doc](https://docs.google.com/document/d/175jLvjDCUnO7_IkVgiC17xOg3fF0AbYhG5Uc2F-ZYcE/edit#heading=h.xfssmg6frdu4)

Next step is to [create a JIRA request](https://jira.mozilla.com/browse/DS-191?jql=project%20%3D%20DS%20AND%20resolution%20%3D%20Unresolved%20ORDER%20BY%20priority%20DESC%2C%20updated%20DESC) outlining the Dev proposal for DS review.

**Comment by sblatz** [comment]
Filed a JIRA ticket with the dev proposal [here](https://jira.mozilla.com/browse/DS-619)

**Comment by sblatz** [comment]
This is already tracked by the `open links in apps` metrics ping I recently added 😄
