### ISSUE TITLE
[Telemetry] Dark Theme

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/fenix#7289]
#### Description & Product Manager / Data Scientist User Story
- As a product owner, I want to know how often users choose dark mode, in order to better prioritize feature optimizations.

#### What probes (suggested, if applicable)
- How often users choose Dark Theme
- Where do users make this choice from (settings or onboarding)

### Acceptance Criteria (Added by PM)
- Event pings can be queried via re:dash
- We are sending telemetry events for the actions listed in the requirements
- We have documented the telemetry
- We have asked a data steward to [review](https://github.com/mozilla/data-review/blob/master/request.md) the telemetry
- NOT an AC: Data science to create dashboard or further graphs (this will be a separate issue, this issue is only about hooking up the events described and that they can be queried in re-dash)

**Comment by Poopooracoocoo** [comment]
Just out of curiosity, would what times dark theme is enabled be measured?

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly Build #20350605`** from 2/4 using a Google Pixel 3 XL (Android 9)

✔️ Select Dark theme from the Onboarding screen  - Ping **2a8d54b9-d3de-46d1-a745-bb375cb8f487**
✔️ Select Dark theme from Settings- Ping **1f8fb39f-26a0-41dc-9845-3747f66f8fdd**

[Logcat](https://github.com/mozilla-mobile/fenix/files/4153270/dark_theme.txt)
[Glean dashboard](https://debug-ping-preview.firebaseapp.com/pings/ajtest0402001)
