### ISSUE TITLE
Settings that are web pages don't handle back button presses correctly

### ISSUE THREAD

**Issue by Sdaswani** [mozilla-mobile/fenix#729]
## Steps to reproduce
See video: https://photos.app.goo.gl/cqTksaK8NsfbXTwj6

### Expected behavior
Pressing back gets me back to settings

### Actual behavior
Pressing back takes me out of Fenix

### Device information

* Android device: Galaxy S8
* Fenix version: Tonight's Nightly (sorry I'm being lazy)

**Comment by ekager** [comment]
Related to #513 , having an InfoFragment that would go back to Settings on back press to separate these settings pages from opening as a normal tab would fix this.

**Comment by ekager** [comment]
Fixed by #753

**Comment by sv-ohorvath** [comment]
Verified as fixed.
