### ISSUE TITLE
[Bug][Webrender]"available by user: Qualified enabled by pref" is missing from Webrender section for Samsung devices

### ISSUE THREAD

**Issue by Diana-Rus** [mozilla-mobile/fenix#7290]
## Steps to reproduce

1. Open Firefox Preview Browser and go in "about:support".
2. Search after "Webrender" section.
### Expected behavior

The WebRender feature has the following status:

- opt-in by default: WebRender is an opt-in feature
- available by user: Qualified enabled by pref
### Actual behavior

Information "available by user: Qualified enabled by pref" is missing.
### Device information

 Android device: 
- Samsung Galaxy S10 Plus(Android 9)-Adreno 640
- Samsung Galaxy S9 (Android 8.0.0)-Adreno 630
- Samsung Galaxy Note 8 (Android 9)-Adreno 540.

 Fenix version: Firefox Preview nightly 191219 (Build #13530607) and Gecko View 73.0a1-20191216095052.

Note:
- The issue does not reproduce with OnePlus 6T/A6013 (Android 9)-Adreno 630, OnePlus 5T (Android 9)-Adreno 540.

**Comment by ktaeleman** [comment]
Hey Diana,

Would you be able to attach an about:support for one of these devices?

Thanks!

**Comment by Diana-Rus** [comment]
Hi, please check [screenshot](https://drive.google.com/file/d/1egjOCE0six-CvONK9i5VdMJqdCD4GE-4/view?usp=sharing).

**Comment by ktaeleman** [comment]
Thanks for this Diana, that explains why!
This is a Samsung Galaxy phone with a MALI GPU instead of an Adreno GPU.

We have not enabled webrender for Mali GPU's yet, can you invalidate the bug?

Thanks! (And happy holidays!)

**Comment by ktaeleman** [comment]
Another question: Are any of the Samsung Galaxy devices Adreno versions? It would be good if we can do a test on a Samsung Galaxy Adreno device.

**Comment by sv-sdeiac** [comment]
Hello @ktaeleman, 

Making a check on Samsung Galaxy Tab S3 (Android 8) with Adreno 530, we found that this issue who caused the status YELLOW is not a valid one.

Due to that, I'll close this issue, thanks. 
Happy Holidays!
