### ISSUE TITLE
[Bug] The game from https://proxx.app/ does not load in Private Browsing

### ISSUE THREAD

**Issue by LaurentiuApahideanSV** [mozilla-mobile/fenix#7293]
## Steps to reproduce
1. Switch to Private Browsing;
2. Go to https://proxx.app/;
3. Fill all the rquired fields and tap the Start button;

### Expected behavior
A game similar to minesweeper should start. 
### Actual behavior
The page remains in infinite loading.
### Device information

* Android device: Samsung Galaxy Note 9 (Android 9)
* Fenix version: 
Firefox Preview 3.0.1 (Build #13502256) 12/16
Firefox Preview 3.0.0-beta.3 (Build #13392157)
Firefox Preview Nightly (Build #13530608) 12/19

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-14900)

**Comment by darkwing** [comment]
I think this *might* be a Gecko issue or a coding issue.  The game never loads properly in desktop Firefox in private mode either.  I see service workers and other others, so you may want to look into that.

**Comment by NotWoods** [comment]
I think PROXX relies on IndexedDB and doens't work when its not present (such as in private mode). Filed https://github.com/GoogleChromeLabs/proxx/issues/511

**Comment by LaurentiuApahideanSV** [comment]
The issue still occurs on Firefox Preview Nightly 5/19.
### Devices used:
- Pixel 3 XL (Android 9)
- OnePlus 6T (Android 9)

**Comment by SoftVision-LorandJanos** [comment]
This issue is still reproducible.
Verified on the latest Nightly 96.0a1 (2021-11-19).
Device used: Xiaomi Mi11 Lite (Android 11).

Verified on Chrome, where the app works as expected in "Incognito tab".

**Comment by kbrosnan** [comment]
bz-78198 tracks fixing indexdb in private browsing
