### ISSUE TITLE
[Bug] "Error connecting to '%s'" in custom search engine

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#7294]
## Steps to reproduce
1. Try to add an incorrect custom search engine

### Expected behavior
1. User is notified: "Error connecting to ENGINE_NAME"

### Actual behavior
1. User is notified: "Error connecting to '%s'"

Fenix version 12/19/19

<img width="350" alt="Screen Shot 2019-12-19 at 10 27 30 AM" src="https://user-images.githubusercontent.com/4400286/71185915-4e9c1e80-224a-11ea-87e9-8ff713f291ae.png">

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **Nightly Build #13570608 from 12/23** using the following devices:

• Google Pixel 3a (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

► Screenshot
![Screenshot_20191223-110622](https://user-images.githubusercontent.com/51314259/71348575-828e8100-2575-11ea-96e9-8b6652560a10.png)

► Video
![20191223_110523](https://user-images.githubusercontent.com/51314259/71348636-a225a980-2575-11ea-9623-81413545820c.gif)
