### ISSUE TITLE
[Bug] The 3D models are not correctly displayed

### ISSUE THREAD

**Issue by Diana-Rus** [mozilla-mobile/fenix#7296]
Pre-requisites:
gfx.webrender.all=true

## Steps to reproduce
1. Open Firefox Preview Browser and go to "https://sketchfab.com/".
2. Play a video.

### Expected behavior
The 3D Models are loaded correctly.

### Actual behavior
The 3D models are not displayed correctly.

### Device information

Android device: 
- Samsung Galaxy S10 Plus(Android 9)-Adreno 640
- Samsung Galaxy S9 (Android 8.0.0)-Adreno 630
- Samsung Galaxy Note 8 (Android 9)-Adreno 540
* Fenix version: Firefox Preview nightly 191219 (Build #13530607) and Gecko View 73.0a1-20191216095052.

Note:
- The issue does not reproduce with OnePlus 6T/A6013 (Android 9)-Adreno 630, OnePlus 5T (Android 9)-Adreno 540.
- Please check [video](https://drive.google.com/file/d/1TPBCfwjiwB6BAW9nkilassEnxpVj4NoI/view?usp=sharing).

**Comment by kbrosnan** [comment]
Do we have a Bugzilla bug on this?

**Comment by softvision-miralobontiu** [comment]
I was able to reproduce this issue on the latest Nightly build from 9/29 using a Samsung Galaxy Note 8 (Android 9) [SM-N950F, Mali G71], and a Samsung Galaxy S8 (Android 9) [SM-G950F Mali G71]. 
I have to add that this is reproducible regardless of the state of gfx.webrender.all configuration.

Not reproducible with Xiaomi Mi8 Lite (Android 9) [Andreno 512].
The Bugzilla bug is https://bugzilla.mozilla.org/show_bug.cgi?id=1638347.

The link is https://sketchfab.com/3d-models/polygon-city-pack-preview-5a16f543d1054fbc9ce1cb17a2ba412e


![Untitled](https://user-images.githubusercontent.com/40694158/94554757-38a09d00-0263-11eb-9f56-a62d30891ebd.png)

**Comment by softvision-miralobontiu** [comment]
This issue is still reproducible on the 11/26 Nightly build with GV 85.0a1, and on Beta 84.0.0-beta.2 with GV 84.0a1.
Tested with Samsung Galaxy Note 8 (Android 9).

**Comment by lobontiumira** [comment]
The issues is reproducible on the 5/26 Nightly build with Samsung Galaxy Note 8 (Android 9).

**Comment by SoftVision-LorandJanos** [comment]
This issue is not reproducible on the latest builds:
- Release (94.1.2).
- Beta (95.0.0beta5).
- Nightly 96.0a1 (2021-11-24).

Devices used:
- Xiaomi Mi11 Lite (Android 11).
- Samsung Galaxy Tab S3 (Android 9).

Closing the ticket as fixed.
