### ISSUE TITLE
Allow "always zoom websites" to work in in fullscreen YouTube

### ISSUE THREAD

**Issue by st3fan** [mozilla-mobile/fenix#7299]
> This was taken from https://bugzilla.mozilla.org/show_bug.cgi?id=1604975

Steps to reproduce:

Enabled the setting "always enable zoom".

Actual results:

Zoom is still disabled in youtube fullscreen.

Expected results:

I should be able to zoom.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-14905)

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813178

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
