### ISSUE TITLE
Opening a session in private mode opens the session in normal mode

### ISSUE THREAD

**Issue by Sdaswani** [mozilla-mobile/fenix#730]
## Steps to reproduce
See this video: https://photos.app.goo.gl/iYck1ybPzpAMekte6

### Expected behavior
The session tabs are opened in private mode

### Actual behavior
The session tabs are opened in normal mode

### Device information

* Android device: Galaxy S8
* Fenix version: Tonight's Nightly

May be related to https://github.com/mozilla-mobile/fenix/issues/608 ?

**Comment by boek** [comment]
Fixed in #688
