### ISSUE TITLE
Dec 13 - Dec 14 Performance Change

### ISSUE THREAD

**Issue by hawkinsw** [mozilla-mobile/fenix#7300]
There is a significant change in performance between the Nightly version on Dec 13 and the Nightly version on Dec 14. On the 'Nightly' rig, there is a performance _improvement_. On Nimbledroid, there is a performance _regression_. Nimbledroid says that the regression is the result of a long-running method to instantiate "Rx plugins". My gut says that this is related to the change that @colintheshots introduced on Friday w.r.t. the production version of coroutines vs the beta version. https://github.com/mozilla-mobile/fenix/commit/a8f895cb5c76a1a87298c4a55d76770257726197. 

The profile gathered using the automated system _does_ compare reasonably with _the startup time of the nightly production build of Fenix_. However, because the version the automated profiling system builds _is not comparable_ to that version, the results cannot be compared. (I will add a feature to the automated profiling system to add  a comment to results posted to the PR comment stream that indicates that. My fault!) However, when contrasting comparable versions, the regression exists there, too.

**Comment by mcomella** [comment]
I believe this was addressed by https://github.com/mozilla-mobile/fenix/pull/7218

@colintheshots @hawkinsw Please close if so.

**Comment by hawkinsw** [comment]
Bingo!
