### ISSUE TITLE
[Bug] My two most used search engines disappeared from Firefox Preview 

### ISSUE THREAD

**Issue by LeoniePhiline** [mozilla-mobile/fenix#7309]
## Steps to reproduce
Use Nightly of about a week ago.
Add custom search engines Startpage (privacy! With incomparably higher search result quality than duckduckgo) and Ecosia (ecology!) and kick out the data leeches Google, Bing, Amazon,... 

### Expected behavior
The best available search engines stay available as I update to the following Nightlies.

### Actual behavior
My most important search engines disappeared from Firefox Preview when updating nightly two or three days ago. 
The two best search engines out there were intentionally or accidentally removed. 

### Device information

* Android device: Huawei P20
* Fenix version: Nightly from Play Store

**Comment by cadeyrn** [comment]
> The two best search engines out there were intentionally or accidentally removed.

intentionally in #7213.

**Comment by boek** [comment]
@LeoniePhiline We removed the handful of search engines pending coming up with the final list. For now you can always re-add them yourself by selecting "Custom" and pasting in the query and replacing the query text with %s :)

**Comment by LeoniePhiline** [comment]
Hi @boek 
Thanks for your reply! 

What is the reasoning for having less search engines, and especially having privacy centered choices removed - against what Mozilla usually claims to stand for?

Is this a result of force by Google? (I am unaware of the current default search engine provider deals, which, AFAIK, are a central source of income for Mozilla.)

The entire removal smells a little fishy and I would wish for maximum transparency. :)
