### ISSUE TITLE
[Headers] Dark theme header colour is wrong

### ISSUE THREAD

**Issue by AmyYLee** [mozilla-mobile/fenix#7313]
All dark theme headers should be #32313C. Please see mock below

<img width="762" alt="Screen Shot 2019-12-20 at 11 39 22 AM" src="https://user-images.githubusercontent.com/5992746/71269479-760feb80-231d-11ea-8304-9fd6e8a3657d.png">

**Comment by mcarare** [comment]
@AmyYLee Can you also please check (or link to the mocks) what should actionbar color should be for light and private themes? Thank you!

**Comment by AmyYLee** [comment]
> @AmyYLee Can you also please check (or link to the mocks) what should actionbar color should be for light and private themes? #FFF and #291D4F ? Thank you!

Do you mean the android toolbar? 
<img width="504" alt="Screen Shot 2019-12-30 at 3 06 21 PM" src="https://user-images.githubusercontent.com/5992746/71598715-03212480-2b16-11ea-9f98-1f55feaa2ab7.png">

**Comment by mcarare** [comment]
@AmyYLee Sorry, I mean the header. That is the actionbar.

**Comment by AmyYLee** [comment]
The current light theme is correct. 
Private theme is attached:

<img width="739" alt="Screen Shot 2019-12-31 at 11 53 10 AM" src="https://user-images.githubusercontent.com/5992746/71628092-476afe00-2bc4-11ea-91e4-a6091a31269b.png">

**Comment by sv-sdeiac** [comment]
Verified as fixed using the latest version of Nightly 1/10 #20100616.

Devices:
- OnePlus 5T (Android 9);
- LG G7 fit (Android 8.1).
