### ISSUE TITLE
Add mitigation for improper usage of BuildConfig.DEBUG

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#7318]
### What
BuildConfig.DEBUG represents whether or not the build is debuggable. However, most developers take it to mean, "Is this a debug build?" They should be using specific release variants to identify debug vs. release rather than using the BuildConfig.DEBUG flag, which is much less common. We should prevent folks from using it unintentionally, e.g. via static analysis.

### Impact
Without this, folks may use BuildConfig.DEBUG to modify runtime behavior but that behavior may show up in our `forPerformanceTest` builds, impacting our performance analyses.

### Acceptance criteria
- Improper usage of BuildConfig.DEBUG is mitigated (e.g. in favor of build variant use)

**Comment by hawkinsw** [comment]
I'd propose adding a custom rule to Detekt to detect use of BuildConfig.DEBUG and ban it. What do you think, @mcomella?

**Comment by mcomella** [comment]
> I'd propose adding a custom rule to Detekt to detect use of BuildConfig.DEBUG and ban it. What do you think, @mcomella?

I think there are three options:
- Detekt
- Android Lint
- Custom static analysis, e.g. through a gradle task

I don't understand the trade-offs of each tool – particularly how hard it is to maintain and write rules (are their rule APIs stable?) but I imagine detekt is the ideal final destination: it runs quickly, it doesn't require re-reading all the files (like custom rules will probably do until we hook them into version control), and it looks at symbols in an intelligent way (unlike custom rules).

**Comment by hawkinsw** [comment]
So, you agree?

**Comment by mcomella** [comment]
Yes – from my limited knowledge, detekt sounds ideal. However, my biggest
concern with detekt is how much time it might take to write (and maintain –
are the APIs stable?) a custom rule.

**Comment by hawkinsw** [comment]
See #7454

**Comment by mcomella** [comment]
Addressed by https://github.com/mozilla-mobile/fenix/pull/7454.
