### ISSUE TITLE
Let's work more with contributors!

### ISSUE THREAD

**Issue by NotWoods** [mozilla-mobile/fenix#7323]
With the recent decision to move [Mozilla’s messaging to Matrix](https://discourse.mozilla.org/t/synchronous-messaging-at-mozilla-the-decision/50620), we want to take this opportunity to better work with our amazing contributors and encourage multiple contributions. Let’s start discussing what we can do in early 2020!

# Communicating with contributors
## Meetings
We have two cross team meetings every week on Tuesday and Thursday at 10am PST/1pm EST. The Tuesday meeting could be opened up to all contributors, and give us an opportunity to work more closely with the great community here. DevTools also has a weekly contributor meeting on [Whereby](https://whereby.com/), where they give an overview of the state of the project and have a standup with the contributors. Contributors can demo what they’ve worked on and ask questions. It also helps us make sure that people aren’t stuck.

## Messaging
Currently, we have various IRC channels with limited activity, a Slack workspace for Fenix, a Gitter chat room for Android Components, and our internal Slack. We want to consolidate these various spaces into Matrix channels on the upcoming messaging system. 

Our team communication should also happen in Riot/Matrix by default, and just use our internal Slack for private issues (ie: security issues). Most of our engineering communication should be able to move to Riot/Matrix. We’ll shut down the contributor Slack and Gitter chat room and direct people into Riot/Matrix.

We can also take another idea from DevTools and ping contributors on Riot about once a week to see how they’re doing and if they have questions. This helps by giving people another avenue to chat with us, although sometimes people will apologize if they’ve been busy. (It’s fine if you haven’t had a chance to contribute recently!)

# GitHub
## Issues
We’ve started marking lots of issues as “help wanted”/”good first issue” to indicate they’ve been left for contributors. I think we’ve done a decent job providing as much info as we can in the issues so that contributors can work off of it. 

We’ve had some comments that the massive issue list is daunting, but that number also includes feature requests, completed issues waiting for QA, and issues blocked by other libraries like GeckoView. Perhaps we could add a sticky issue that points to a filtered issue view only showing bugs.

I’m interested to hear any feedback for what we can improve here to make the issues easier to work with.

## Pull Requests
Our pull request list is pretty big, thanks to active contributors and lots of teams adding code to Fenix. It’s difficult for our team to stay on top of all the PRs, so it would be great if we could encourage contributors to help out here. We currently have a couple contributors who do reviews but more would be great! 

Again, a link to a filtered view may be helpful here. We may want to filter out work-in-progress and do-not-land PRs, or PRs that have already been reviewed.

# Larger projects
Let’s start setting up some larger projects that a contributor can take on. Having everyone helping out is great, and we should encourage larger contributions if people are interested. We can try to identify projects that don’t have a strict timeline and open them up for anyone to work on.

---

We're making this an open discussion on GitHub so anyone can chime in. If you have ideas, leave a comment!

**Comment by shahsurajk** [comment]
I think one small step towards this direction could simply be adding more "Help Wanted" labels, I personally look for issues under this label as I mostly look for projects to contribute on in an ad-hoc way. 

Again, this could be a very subjective opinion.
