### ISSUE TITLE
Bookmark all open tabs to a folder (like desktop)

### ISSUE THREAD

**Issue by Poopooracoocoo** [mozilla-mobile/fenix#7325]
### Why/User Benefit/User Problem
Collections don't fit all use cases. I'm sure you can imagine some. I for one am a massive tab hoarder! This would be great with #10878 ;)
### What/Requirements
"Bookmark all tabs" item below "Save to collection" in tab switcher menu

Once you tap on Bookmark all tabs, Firefox should ask you what you'd like to name the folder and where you'd like to put it. **This would be similar to the collection flow, the share all tabs flow and the bookmark all tabs flow on desktop.** 

### Acceptance Criteria (how do I know when I’m done?)
when the above has been implemented

### Note
No idea what tapping and holding on tabs should do 
Edit: found it! #2487

Edited to remove my rant about the mixed homescreen and tab switcher which have been separated.

This would be really useful for private browsing as well as regular browsing.

#12065

Edit: here's a screenshot from Google. People have searched for this before: 
![image](https://user-images.githubusercontent.com/51363864/94711849-0474cb80-038c-11eb-882d-5f966871c809.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-14920)

**Comment by yoasif** [comment]
No easy way to do this forced me to open all tabs on desktop instead and bookmark them there. Also relevant is https://github.com/mozilla-mobile/fenix/issues/6512

**Comment by Poopooracoocoo** [comment]
also worth noting that you can do this on safari for iOS/iPadOS.

**Comment by Poopooracoocoo** [comment]
#11967 #5652 are collection related issues that other people may want to look at.

**Comment by Poopooracoocoo** [comment]
@vesta0 I noticed you closed the Feature Discovery project that this issue was in. I'm a bit confused about what that meant. Could you please explain?

**Comment by vesta0** [comment]
Hey @Poopooracoocoo that's just because we are now tracking our themes/EPICS in JIRA.

**Comment by Poopooracoocoo** [comment]
@vesta0 ah. thanks for the explanation. is this issue in a theme/epic? 🥺

**Comment by KitezhGrad** [comment]
Any updates on implementing this feature? 
Thank you.

**Comment by Poopooracoocoo** [comment]
Firefox will NOT be the first Android browser to implement bookmark all tabs. Bromite is now the first ever browser on Android to let you bookmark all tabs!

**Comment by Poopooracoocoo** [comment]
@eliserichards hey are there any updates on the priority of this FR?

**Comment by AndreRH** [comment]
Would need this feature right now...
