### ISSUE TITLE
[Bug] Grey line below (or above) toolbar outside of homepage, search, fullscreen pages, etc

### ISSUE THREAD

**Issue by Poopooracoocoo** [mozilla-mobile/fenix#7326]
## Steps to reproduce
N/a
### Expected behavior
No white line
### Actual behavior
![image](https://user-images.githubusercontent.com/51363864/71304391-19462b00-241a-11ea-9e44-4443df837808.png)
(more noticeable with dark theme but also present with light theme)
### Screenshot

* Android device: ?
* Fenix version: Nightly 191220 18:00 (Build #13541809)
27.0.0, 081e6851f
GV: 73.0a1-20191219095006

**Comment by cadeyrn** [comment]
Duplicate of #7266.

**Comment by Poopooracoocoo** [comment]
Thanks. GitHub's search isn't perfect
