### ISSUE TITLE
Change search engines mid-search by tapping on search engine icon

### ISSUE THREAD

**Issue by Poopooracoocoo** [mozilla-mobile/fenix#7327]
### Why/User Benefit/User Problem
it's convenient and easy. someone might not remember to change search engines and after completing the search, they might change the URL like google.com/?q=... to duckduckgo.com/?q=... which doesn't actually work. 
### What/Requirements
Can change search engines mid-search by tapping on search engine icon
### Acceptance Criteria (how do I know when I’m done?)
When you can tap on search engine icon to change search engines mid-search
When a small triangle has been added to the search engine icon

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-14922)

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807744

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
