### ISSUE TITLE
Opening a tweet in a new tab (in the background) doesn't load the entire thread

### ISSUE THREAD

**Issue by moizahmed97** [mozilla-mobile/fenix#7329]
## Steps to reproduce
Go to Twitter.com
open any tweet thread by long pressing on the open thread and then  "Open in new tab" 
### Expected behavior
The entire thread with all the replies and the tweet itself should load
### Actual behavior
only the first tweet is shown, none of the other tweets in the threads or in the replies can be seen
only a refresh fixes it
### Device information
* Android device: ?
Nokia 8.1 runnnig Android 10
* Fenix version: ?
3.0.1

**Comment by boek** [comment]
@moizahmed97 Can you still reproduce? Looks like the replies come in async with Javascript. It took a second to load but the replies came in for me.

**Comment by moizahmed97** [comment]
@boek  oddly enough it works at times and doesn't at others 
Even for the same thread it isn't consistent
I've tested on Samsung Internet and it seems to be consistent
![Screenshot_20191228-142748](https://user-images.githubusercontent.com/44170860/71542966-8ad42b00-297e-11ea-93f0-41177af207c6.png)

**Comment by djc** [comment]
This doesn't seem to work for me most of the time. Definitely an annoying paper cut.
