### ISSUE TITLE
[Bug] Google images, maps and deezer fail with unknown protocol

### ISSUE THREAD

**Issue by andreicristianpetcu** [mozilla-mobile/fenix#7331]
## Steps to reproduce
Open https://images.app.goo.gl/ZQzHfQaLtWvTntNo8

### Expected behavior
Show the page like fennec
![Screenshot_20191221-153157_Firefox_Beta](https://user-images.githubusercontent.com/922368/71308586-1988fb00-2407-11ea-869f-fcbf23d54bc7.png)

### Actual behavior
Shows unknown protocol
![Screenshot_20191221-153145_Firefox_Nightly](https://user-images.githubusercontent.com/922368/71308590-2ad20780-2407-11ea-80ad-35d527efcfbf.png)

### Device information

* Android device: OnePlus 5t
* Fenix version: Nightly

**Comment by boek** [comment]
Hmm.. Are you still able to reproduce?

<img width="772" alt="image" src="https://user-images.githubusercontent.com/1250545/71529556-1a53de00-289a-11ea-8538-151d88c185ff.png">

**Comment by andreicristianpetcu** [comment]
@boek  I can still reproduce in Nightly, not in Beta.
Your link is www.google.com while mine is https://images.app.goo.gl/ZQzHfQaLtWvTntNo8

**Comment by andreicristianpetcu** [comment]
Same with Deezer https://deezer.page.link/?link=https%3A%2F%2Fwww.deezer.com%2Fchannels%2Fexplore&apn=deezer.android.app&amv=6190600&ibi=com.deezer.Deezer&isi=292738169&imv=7.11.0&ifl=https%3A%2F%2Fwww.deezer.com%2Fus%2Fchannels%2Fexplore%3FdeferredFl%3D1&ofl=https%3A%2F%2Fwww.deezer.com%2Fus%2Fchannels%2Fexplore%3FdeferredFl%3D1&afl=https%3A%2F%2Fwww.deezer.com%2Fus%2Fchannels%2Fexplore%3FdeferredFl%3D1&utm_source=deezer&utm_campaign=mobileweb&utm_medium=dynamiclink&utm_content=channels

![Screenshot_20200103-212742_Firefox_Nightly](https://user-images.githubusercontent.com/922368/71744478-072fa800-2e70-11ea-94dd-8d693ae92529.png)

Google maps https://maps.app.goo.gl/wo4BX7DFdFqoyk5y5

![Screenshot_20200103-212932_Firefox_Nightly](https://user-images.githubusercontent.com/922368/71744528-39d9a080-2e70-11ea-886d-55935330cb00.png)
Both work fine in Chromium and Fennec beta

**Comment by julienw** [comment]
Same issue when trying to register a Nintendo account from an app (like Super Mario Run). The end of the process uses a custom scheme, presumably to come back to the app with the right information.

**Comment by mhammond** [comment]
Same issue with the "dexcom" app - we end up on a page with the "decom://" protocol, and instead of following an existing "app link" (or whatever mechanism is actually used) we get the "unknown protocol" page. FWIW, this works fine on Fennec (and copy/pasting the URL from Fenix into Fennec still works today)

**Comment by sv-ohorvath** [comment]
Can reproduce this on Beta 3.1.0 now, any custom scheme link from http://rpappalax.github.io/testapp returns unknown protocol. The reddit "open in app" button doesn't respond either (no response or error).

**Comment by softvision-miralobontiu** [comment]
Same issue with bilibili://video/84021218?h5awaken=cHZpZD1udWxsXzg0MDIxMjE4XzE1Nzk1OTkwNDU0NTUmdWE9TW96aWxsYSUyRjUuMCUyMChBbmRyb2lkJTIwMTAlM0IlMjBNb2JpbGUlM0IlMjBydiUzQTc0LjApJTIwR2Vja28lMkY3NC4wJTIwRmlyZWZveCUyRjc0LjAmaXNBdXRvT3Blbj10cnVlJmJzb3VyY2U9dW5kZWZpbmVk&page=0 on the 1/20 Nightly build (#20201806).

**Comment by rocketsroger** [comment]
Most of the issues here can be resolved with two solutions:
1. Turn on `Open links in apps` in settings.
2. Fixing https://bugzilla.mozilla.org/show_bug.cgi?id=1600704

**Comment by rocketsroger** [comment]
I'll mark this blocked by the GV issue and retest when the issue is fixed.

**Comment by andreicristianpetcu** [comment]
No, open link in app does not fix it! I don't have apps for any of them. Why would I install a deezer, maps, or google images just to visit a page?
It works fine in Fennec

**Comment by rocketsroger** [comment]
> No, open link in app does not fix it! I don't have apps for any of them. Why would I install a deezer, maps, or google images just to visit a page?
> It works fine in Fennec

Yes, not all are fixed with just turning on `Open links in apps`.  There is an on going issue in GV that it tries to open an intent without passing it to AC.  Since an intent is unsupported in GV, we see the unsupported protocol.

That said, the image issue is fixed by turning on `Open links in apps`.  (Though there's a crash issue I'm looking into related to this)

Unfortunately, until GV's fix is in, I can't retest and confirm which issue requires a fix.  This is why I set it blocked and will revisit when GV's fix is merged.

**Comment by julienw** [comment]
One important thing to note is that sometimes we're just prevented from doing an action. For example some links in mails from amazon don't work when opened in Fenix, because we got redirected to an intent. I don't know why that happens, especially that I don't have the Amazon app. But I know that this works fine when opened in Fennec, but doesn't when opened in Fenix.

**Comment by rocketsroger** [comment]
> One important thing to note is that sometimes we're just prevented from doing an action. For example some links in mails from amazon don't work when opened in Fenix, because we got redirected to an intent. I don't know why that happens, especially that I don't have the Amazon app. But I know that this works fine when opened in Fennec, but doesn't when opened in Fenix.

This is related to  https://bugzilla.mozilla.org/show_bug.cgi?id=1600704.  But can you please open an issue for us to track it?  The intent should have fallback URL in it so we can open in the browser if no app can open the intent.  This can't be tested until the GV fix is in.

**Comment by andreicristianpetcu** [comment]
same on google earth https://earth.app.goo.gl/?link=https://earth.google.com/web/?fdl%3D1&apn=com.google.earth&ibi=com.google.b612&isi=293622097&ius=googleearth

![Screenshot_20200226-204959_Firefox_Nightly](https://user-images.githubusercontent.com/922368/75376983-a05fc580-58d9-11ea-99eb-1d63cd45b5d6.png)

**Comment by rocketsroger** [comment]
confirmed all links in this issue is now working correctly.  Adding QA to verify.

**Comment by andreicristianpetcu** [comment]
Works for me also.
Since I reported, I guess it's no need to waste qa time on this.
