### ISSUE TITLE
[Bug] While watching a video on fullscreen, user can slide the video at a limited range.

### ISSUE THREAD

**Issue by adth03** [mozilla-mobile/fenix#7333]
Set the toolbar to top. While watching a video on fullscreen, user can slide the video at a limited range.
While browsing normally, when user slide the webpage the toolbar disappears. But when the toolbar appears, the website seems as if it is moved a bit down. I think that this may cause the problem.

**Comment by kbrosnan** [comment]
Duping to #8252 as it has a better description of the problem. It is not related to the top navbar it happens when the video aspect ratio and the screen aspect ratio do not match.

**Comment by juggler37** [comment]
In my experience, this describes the problem better than #8252 does. It's hard to be sure whether resolution has something to do with it, but I can verify that the problem occurs when the toolbar is set to the top (even when the resolution appears to be correct), and it never occurs when the toolbar is set to the bottom.
