### ISSUE TITLE
[Bug] Crash on startup

### ISSUE THREAD

**Issue by CDGDVD** [mozilla-mobile/fenix#7336]
## Steps to reproduce
I don't how to reproduce it :/
### Expected behavior
opening the app and installing addons
### Actual behavior
Crash on startup with no error whatsoever
### Device information
lineageos 14.1 with gapps (pico)
* Android device: Galaxy Tab E
* Fenix version: Normal, beta, nightly

**Comment by cadeyrn** [comment]
> opening the app and installing addons

There is no add-on support yet. How do you do that? 🤔

**Comment by CDGDVD** [comment]
> There is no add-on support yet. How do you do that? 🤔

opps I posted this in fenix not mobile, I'm retarded 👌

**Comment by CDGDVD** [comment]
you know may as well reopen since fenix is also on mobile

**Comment by boek** [comment]
I'm going to close this as we don't have support in Fenix yet.
