### ISSUE TITLE
A search widget should actually act as a widget, instead of as a shortcut...

### ISSUE THREAD

**Issue by aha999** [mozilla-mobile/fenix#7337]
### User Problem

- The search widget is currently acting just as a shortcut to the program that selects a search feature...
- That's no different if we had a 1x1 shortcut icon to do that...

### Solution
- It would be awesome, when you pressed the search widget, you could type directly into it and the suggestions would expand the widget over other elements...
- Pressing the search would then bring up the same kind of window as the google search widget has (still on desktop but expanded, with the button to open the results in the browser (or a setting in Preview to modify the behaviour).
- The widget should be interactive

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-14931)

**Comment by NotWoods** [comment]
For option 1, we can't have the widget expand without the user manually resizing it.

For option 2, I'm not sure if we can show a window with transparency over the home screen. When I tested the Google Search widget on a custom launcher, it opens a new opaque window similar to the Firefox and Chrome search widgets.

**Comment by tomato73** [comment]
It would be nice if there was more of a transition animation, to give the impression that you're interacting with the same control.

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807580

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
