### ISSUE TITLE
[Enhancement]The same search engine is presented in the  search bar and the shortcut list

### ISSUE THREAD

**Issue by sv-sdeiac** [mozilla-mobile/fenix#7340]
## Steps to reproduce
1. Open Firefox Preview;
2. Tap on the search bar;
3. Watch the search engine shortcut list;

### Expected behavior
A list of additional search engines is presented.

### Actual behavior
The shortcut for the same search engine as in the search bar is presented on the list.

### Device information

* Android device: OnePlus 5T (Android 9), LG g7 fit (Android 8.1).
* Fenix version: Firefox Preview Nightly 12/23 #13570607, Firefox Preview RC 3.0.1
 #13502256,
* Screenshot
<img width="259" alt="vdv" src="https://user-images.githubusercontent.com/40264165/71347441-0eeb7480-2573-11ea-946d-c5353cc1aa1a.png">

**Comment by shahsurajk** [comment]
I can try doing this, should i?
