### ISSUE TITLE
[Bug] Elements from table/section are partially visible

### ISSUE THREAD

**Issue by Diana-Rus** [mozilla-mobile/fenix#7345]
## Steps to reproduce
1. Open Firefox Preview browser.
2. Go to "https://www.color-blindness.com/coblis-color-blindness-simulator/".
3. Tap on the "Menu".
4. Enable the "Desktop Site" option.
5. Inspect the "Drag and drop or paste your file in the area below or" section/table.

### Expected behavior
The "Drag and drop or paste your file in the area below or:" section/table elements are visible and accesible.

### Actual behavior
Because the font size is large:
- the "Browse" button is only partially visible.
- not all radio buttons are available for the user

### Device information

* Android device: Google Pixel 3a XL (Android 10), Samsung Galaxy S10 Plus (Android 9)
* Fenix version: Firefox Preview Nightly 191223 (Build #13570608) and GV: 73.0a1-20191220095035

Screenshots:
 Firefox Release 68.3.0 - 
![Screenshot_20191223-170810](https://user-images.githubusercontent.com/49859863/71366791-bc7a7a00-25ab-11ea-8e0c-cdb854e32853.png)

 Firefox Preview Nightly191223 (Build #13570608) and GV 73.0a1-20191220095035
![Screenshot_20191223-170821](https://user-images.githubusercontent.com/49859863/71366800-c308f180-25ab-11ea-8bf2-dfe882712279.png)

**Comment by sflorean** [comment]
Verified as fixed on Nightly 10/22 and 83.0.0-beta.1 with Google Pixel 3 (Android 11).
