### ISSUE TITLE
[Bug] Search toolbar background in search screen is wrong

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#7347]
When I was working on the back button for search screen, I noticed we have a rectangle outline around the search field that should not be there. I'm not sure how long it's been there but I see it on master 🤷‍♂ 

It's really faint, but it's definitely there.

<img width="565" alt="Screen Shot 2019-12-23 at 12 07 11 PM" src="https://user-images.githubusercontent.com/4400286/71370757-e4061e00-257c-11ea-848e-2d890be3f7d8.png">

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **Nightly Build #13580607 from 12/24** using the following devices:

• Google Pixel 3a (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

► Screenshots
![rsz_screenshot_20191224-090333](https://user-images.githubusercontent.com/51314259/71399673-17a08100-262d-11ea-9920-363780d4dc66.png)

![rsz_screenshot_20191224-090400](https://user-images.githubusercontent.com/51314259/71399730-43bc0200-262d-11ea-832b-b1b00dc1d1e1.png)
