### ISSUE TITLE
Fenix crashes after filling a link from Clipboard and open more tabs

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/fenix#735]
## Steps to reproduce
1. Copy any website link to clipboard.
2. Install and launch Fenix.
3. Tap on the **`Fill link from Clipboard`**  option.
4. Tap on tabs icon.
5. On the **`Today`** panel tap on any link displayed there.
### Expected behavior
When tapping on any link, a new one is opened and Fenix works as expected.
### Actual behavior
When tapping on any link from **`Today`** panel Fenix open duplicate number of actual tabs opened and after tapping more than 6 times on the links, Fenix crashes.
### Device information

* Android device: Google Pixel 3XL (Android P/9).
* Fenix version: 1.0.1909

### Notes
Sometimes only after 1 tap, Fenix open 600+ tabs and no other actions are required in order to reproduce the crash.
Also, note that the crash disappears only after clearing all storage and cache or reinstall the Fenix.
For more details please see the attachments:
 [Video](https://drive.google.com/file/d/1TnMu2rKtyXZc8NaRzZj-3dROk7FXZWxg/view?usp=sharing)
[logcat.txt](https://github.com/mozilla-mobile/fenix/files/2915817/logcat.txt)

**Comment by colintheshots** [comment]
This appears to have been fixed incidentally in the last day.
