### ISSUE TITLE
Create add-ons section to the settings page

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/fenix#7350]
This section should be under the **advanced** sub-category, when this section is clicked is should take the user to the add-ons screen

![image](https://user-images.githubusercontent.com/773158/71378849-4d932600-2597-11ea-8faf-4bad62efd6b3.png)

**Comment by Amejia481** [comment]
![image](https://user-images.githubusercontent.com/773158/71379078-17a27180-2598-11ea-971c-208bf3c60788.png)

**Comment by psymoon** [comment]
This is covered and part of the WIP branch.
