### ISSUE TITLE
Integrate highlightable menu button changes from A-C

### ISSUE THREAD

**Issue by Baron-Severin** [mozilla-mobile/fenix#7352]
Make browser menu items highlightable as designed in https://github.com/mozilla-mobile/fenix/issues/4281.  This AC was originally pushed out due to complications with the menu API which have since been resolved.

#### Acceptance Criteria
- [ ] Reader Mode, Reader Mode Appearance, PWA, and Open in App buttons should all be highlighted in the menu bar whenever they are visible
- [ ] The three dot button that opens the menu bar should be highlighted any time any of the above buttons are available

#### Engineering notes
- We should use BrowserMenuHighlightableSwitch ([added by this AC PR](https://github.com/mozilla-mobile/android-components/issues/5022)) to highlight Reader Mode

**Comment by softvision-miralobontiu** [comment]
Hi all!

I've verified that "Reader Mode", "PWA", and "Open in App" buttons are highlighted in the menu bar whenever they are visible. The three-dot button that opens the menu bar is highlighted any time any of the above buttons are available.
However, the "Reader Mode Appearance" is not highlighted in the Settings menu (as seen in the screenshot below). @Baron-Severin Is this expected? 
Tested on the latest Nightly build from 01/06 (#20060606) with Google Pixel 3 (Android 10), and HTC Desire 820 (Android 6.0.1).

![Screenshot_20200106-105714](https://user-images.githubusercontent.com/40694158/71807394-e8016800-3073-11ea-8679-e14576037b4e.png)

I'll remove the qa-needed flag for now.

**Comment by topotropic** [comment]
@Baron-Severin can we also have a blue dot on the "new tab / home" menu whenever we have a release and a blue dot next to "What's new"? Thanks!

**Comment by Baron-Severin** [comment]
My apologies @softvision-miralobontiu, after demo UX requested that the dot be removed from `Appearance`, but I neglected to update the ACs.  Updating them now.  I'm going to close the story, please feel free to reopen if you have any other issues with it.

@topotropic I opened https://github.com/mozilla-mobile/fenix/issues/7506 to track that change, would you mind taking a look at it and making sure I understood correctly?
