### ISSUE TITLE
[webcontent]Unable to stop autoplay

### ISSUE THREAD

**Issue by edentw** [mozilla-mobile/fenix#7354]
## Site with issue and any steps to reproduce
https://tw.news.yahoo.com/video/%E6%99%BA%E6%85%A7%E5%9E%8B%E9%9B%BB%E8%A6%96%E5%8A%9F%E8%83%BD%E5%A4%9A-fbi-%E6%81%90%E9%81%AD%E9%A7%AD%E5%AE%A2%E7%9B%A3%E6%8E%A7-091945604.html

### Expected behavior
He should want to stop playing automatically.
Note: This site uses .ts format.

### Actual behavior
Automatically play video.
I hope to be able to step up the issue of stopping autoplay.

### Does toggling Tracking Protection fix the issue? (Press the lock icon in the toolbar while on the site to see toggle)
No.

### Can you reproduce in [Firefox for Android](https://play.google.com/store/apps/details?id=org.mozilla.firefox)?
N/A

### Can you reproduce in Chrome (or other non-Mozilla browser)?
N/A

### Device information

* Android device: 9.0
* Fenix version: 3.0.1

**Comment by boek** [comment]
This should be fixed with https://github.com/mozilla-mobile/fenix/issues/255 which should land soon in Nightly :)
