### ISSUE TITLE
[Bug] Unable to perform webpage inspection through remote debugging via USB

### ISSUE THREAD

**Issue by siddharths2710** [mozilla-mobile/fenix#7355]
## Steps to reproduce
This issue seems to occur for only one of my personal devices.
* Connect the mobile device via USB for remote debugging
* After a successful connection, open a webpage in the device
* Click on the inspect tab that shows up in the Firefox browser on the development machine

![fenix_bug1-min](https://user-images.githubusercontent.com/13200018/71398797-a621fc00-2647-11ea-898b-744032c3ebf4.png)

### Expected behavior
Web inspector shows up with the required functionality.
### Actual behavior
A blank page appears instead, and I'm not able to open the web Console on the dev m/c to view any possible errors.

![fenix_bug2-min](https://user-images.githubusercontent.com/13200018/71398809-ae7a3700-2647-11ea-9a69-a30d82c2265e.png)

### Device Info

* Android device: version 5.0.2
* Fenix version: 3.0.1_13502256
* Dev Machine: Ubuntu 18.04

**Comment by boek** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1610963

**Comment by digitarald** [comment]
@siddharths2710 could you check Browser Console for any related logs?

It's recommended that you match your Firefox version with Fenix's Gecko version (aka Fenix Nightly would need Firefox Nightly), can you try that?

**Comment by siddharths2710** [comment]
@digitarald Seems like more of a Linux browser support issue instead of the mobile side since I'm able to successfully inspect the navigated webpage on the latest Windows install of Firefox.

As I wish to proceed with my development using Windows, I think its best to close this issue.
