### ISSUE TITLE
[Bug] Tapping tabs overview does not show current tab

### ISSUE THREAD

**Issue by mikeGolf08** [mozilla-mobile/fenix#7356]
## Steps to reproduce

1. Open a new tab
2. Start a search
3. Open many results in new tab (**more than the tab overview can show without scrolling**)
4. Than click **Switch**
5. Tap on the tab overview button

### Expected behavior

The preselected tab is the current one and it is scrolled down to it.

### Actual behavior

The current tab is preselected but you cannot see it because it's on the top of the list.

![20191224_114040](https://user-images.githubusercontent.com/52482050/71409713-d5823a00-2642-11ea-93a6-47db17e90e8c.jpg)
![20191224_114113](https://user-images.githubusercontent.com/52482050/71409715-d5823a00-2642-11ea-90fa-5d6de232c4e1.jpg)

### Device information

* Android device: OnePlus 3T OOS 9.0.6 Android 9
* Fenix version: Nightly 191224 06:00 (Build #13580608) 27.0.0, 11653be8e GV: 73.0a1-20191220095035

**Comment by boek** [comment]
@topotropic Is this something we want to do in the new tab tray?

**Comment by topotropic** [comment]
We want to show the tab people came from when navigating back to tab overview. Can we scroll the selected tab into view?

**Comment by mcarare** [comment]
@boek Should we work on this after the new tab tray is implemented?

**Comment by topotropic** [comment]
It seems that the "scroll to tab you where just on" is a behavior we want – no matter where it happens (home or maybe in a future iteration on tab tray).

**Comment by mcarare** [comment]
@topotropic Should we implement the scrolling to selected tab in any flow? Or just when you tap on the tabs overview? I am asking because you can scroll in the home screen to some position that does not show the selected tab, navigate away(for example to settings) and then go back. 
Also, there is this issue: https://github.com/mozilla-mobile/fenix/issues/8561. 
Do we want to scroll to selected tab or to top on app start?

**Comment by topotropic** [comment]
For the scenario you described (scroll on home, go to settings, go back to home) we preserve the scroll state, so don't scroll to selected tab.

On cold start, we render from top and display top sites addressing https://github.com/mozilla-mobile/fenix/issues/8561.

Let me know if that doesn't answer your questions or if there's something I missed. 

Thank you!

**Comment by sblatz** [comment]
@topotropic this now has odd behavior with top sites & newly added tips. If I come back from a tab, I do not see "top sites" and don't have any visual indicator that they're even there. Same goes for tips.

Maybe if the top tab is the one selected, we try to also show top sites & tip?

Demo: 
![scroll to tab 2020-04-09 16_40_51](https://user-images.githubusercontent.com/4400286/78949609-e4211f80-7a80-11ea-8553-0c12332f3707.gif)

**Comment by mikeGolf08** [comment]
> 
> 
> @topotropic this now has odd behavior with top sites & newly added tips. If I come back from a tab, I do not see "top sites" and don't have any visual indicator that they're even there. Same goes for tips.
> 
> Maybe if the top tab is the one selected, we try to also show top sites & tip?
> 
> Demo:
> ![scroll to tab 2020-04-09 16_40_51](https://user-images.githubusercontent.com/4400286/78949609-e4211f80-7a80-11ea-8553-0c12332f3707.gif)

Yes this behavior is kinda odd and does not represent the newest FF75 awesomebar integration.
I think there are 3 possible solutions:

- Showing **Top-Sites everytime** (showing the top and not the currently selected tab at all)
- Showing **Top-Sites in "awesome-bar" window** after clicking on it and remove them after the first typed char **&** still at the top of the Tab-Overview but with a little **Top-Sites button to the left of the Incognito Window button**
- Showing **the top** everytime but the **selected tab moves to the top of the list**

**I for one prefer the second solution**

@sblatz @boek @topotropic

**Comment by erglundar** [comment]
This problem still persists for me on Fennec 108.1.1  I can not express in words how annoying it is. Can this be reopened or should I create a new issue?
