### ISSUE TITLE
[Bug] Closing the browser shows saved bookmark icon

### ISSUE THREAD

**Issue by mikeGolf08** [mozilla-mobile/fenix#7357]
## Steps to reproduce

1. Open a tab you have not marked as bookmark
2. Close the browser by tapping (Quit (Delete browsing data on Quit enabled))

### Expected behavior

Browser is quitting without showing any different stuff.

### Actual behavior

For a short time a "saved bookmark" icon is visible in awesomebar.

![20191224_114058](https://user-images.githubusercontent.com/52482050/71409966-b0da9200-2643-11ea-940c-0642be9df049.jpg)

### Device information

* Android device: OnePlus 3T OOS 9.0.6 Android 9
* Fenix version: Nightly 191224 06:00 (Build #13580608) 27.0.0, 11653be8e GV: 73.0a1-20191220095035

**Comment by Cipher358** [comment]
For me the message in the bar is "Deleting browsing data" (which makes sense), but sometimes the animation happens really fast and no frames with the text are visible.

<img width="431" alt="Screenshot 2019-12-25 at 17 02 52" src="https://user-images.githubusercontent.com/13125782/71448773-769eec80-2738-11ea-9d5e-2904b17b0b0b.png">

### Device information
- Emulator on API 29, targetting Android 10.0
- Fenix version: current master (1.0.1952)

**Comment by mikeGolf08** [comment]
> For me the message in the bar is "Deleting browsing data" (which makes sense), but sometimes the animation happens really fast and no frames with the text are visible.
> 
> <img alt="Screenshot 2019-12-25 at 17 02 52" width="431" src="https://user-images.githubusercontent.com/13125782/71448773-769eec80-2738-11ea-9d5e-2904b17b0b0b.png">
> ### Device information
> 
>     * Emulator on API 29, targetting Android 10.0
> 
>     * Fenix version: current master (1.0.1952)

That's right and it is the message which I see as well but for a very short time you can see that the bookmark icon is filled and visible until the "Deleting browsing data..." message will pop up.

I see no reason to render a bookmark icon when Closing especially if the website is not marked as a bookmark.
