### ISSUE TITLE
[Bug] Scrolling screenshot feature behavior

### ISSUE THREAD

**Issue by mikeGolf08** [mozilla-mobile/fenix#7358]
## Steps to reproduce

1. Open many tabs (as many as it needs to be scrollable)
2. Open the tab overview
3. Make a scrolling screenshot

### Expected behavior

It stops the screenshot when the bottom of the list is reached.

### Actual behavior

It keeps making screenshots unless you tap on it.

![20191224_114130](https://user-images.githubusercontent.com/52482050/71410165-850bdc00-2644-11ea-84fd-4beadc7bad95.jpg)

### Device information

* Android device: OnePlus 3T OOS 9.0.6 Android 9
* Fenix version: Nightly 191224 06:00 (Build #13580608) 27.0.0, 11653be8e GV: 73.0a1-20191220095035

**Comment by kbrosnan** [comment]
This sounds like something the OS provides. Doubt there is much we can do to  resolve this.
