### ISSUE TITLE
Blue dot at menu bar

### ISSUE THREAD

**Issue by mikeGolf08** [mozilla-mobile/fenix#7359]
### Why/User Benefit/User Problem

I think it is not useful showing a blue dot with every website you can download as Web app.

An user sees it and usually clicks on it which gives him no information at all.

### What/Requirements

No information dots which can distract the focus on browsing.

### Acceptance Criteria (how do I know when I’m done?)

- Fenix shows no blue dots in awesomebar
- There is a short information explaining the function of the "Install-button"

![Screenshot_20191224-105606__01](https://user-images.githubusercontent.com/52482050/71410438-84277a00-2645-11ea-9902-3679aa0d38bd.jpg)

**Comment by apbitner** [comment]
We plan on revisiting in https://github.com/mozilla-mobile/fenix/issues/6350

**Comment by ekager** [comment]
Closing since this has been changed in #6350
