### ISSUE TITLE
[Bug] Fenix crash on the intercept

### ISSUE THREAD

**Issue by andreicristianpetcu** [mozilla-mobile/fenix#7362]
## Steps to reproduce
open https://theintercept.com/2019/12/24/mike-bloomberg-2020-prison-labor/
### Expected behavior
opens link
### Actual behavior
crashes
### Device information

* Android device: OnePlus 5t
* Fenix version: nightly

**Comment by andreicristianpetcu** [comment]
Both beta and stable are not affected

**Comment by LittleAngelwings** [comment]
Crashes also at GitHub Fenix Project Page

Nightly 191226 06:01 (Build #13600606)
27.0.0, 9cb4c261d
GV: 73.0a1-20191224041100

[2019-12-26-14-37-02.txt](https://github.com/mozilla-mobile/fenix/files/4002632/2019-12-26-14-37-02.txt)

**Comment by snorp** [comment]
Looks like I caused this in GV. Filed https://bugzilla.mozilla.org/show_bug.cgi?id=1605991

(I don't know how to do the magical github/bugzilla integration)

**Comment by andreicristianpetcu** [comment]
I see the bugzilla issue was closed

**Comment by LittleAngelwings** [comment]
I don't have any more crashes since this nightly:

Nightly 191228 18:01 (Build #13621813)
27.0.0, d10c36024
GV: 73.0a1-20191227094418

**Comment by andreicristianpetcu** [comment]
Fixed on my phone also. Thank you!
