### ISSUE TITLE
about:crashes doesn't work

### ISSUE THREAD

**Issue by jrmuizel** [mozilla-mobile/fenix#7363]
Fenix crashes (it seems to crash both through an Android reporting system and a dialog that asks to submit the crash to Mozilla). Neither of these seems to show up in about:crashes.

**Comment by cadeyrn** [comment]
about:crashes is not supported in GV apps.

Some related issues:

- https://github.com/mozilla-mobile/fenix/issues/1221
- https://github.com/mozilla-mobile/fenix/issues/2295
- https://github.com/mozilla-mobile/android-components/issues/1705

**Comment by boek** [comment]
Dup of #2295
