### ISSUE TITLE
[Bug]  incorrect behaviour on setting firefox preview as an assist app

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#7365]
## Steps to reproduce
Set Preview as the assist app (the app which is launched when you long-press the Home button)
from device settings.
Open preview normally and go to any website say www.example.com
Long press the home button to launch Preview.
### Expected behavior
In fennec, this results in opening a new tab and pacing the cursor on the address bar (thus opening the keypad), regardless of whether you navigated away from the app or if you have closed it. Also the firefox logo shows up at the home button.

This is useful because the assist app is supposed to be a quick way to search something at any time.
### Actual behavior
In fenix however, this results in no change. If you navigated away from the app then you will be brought back to example.com . There is no new tab and the cursor is not placed in the address bar.
Moreover, the firefox preview icon does not show up.
<p float="left">
<img src="https://user-images.githubusercontent.com/33252312/71451050-eb534480-2793-11ea-9ae3-b60513948081.png" width="300"/>
vs
<img src="https://user-images.githubusercontent.com/33252312/71451172-7df4e300-2796-11ea-8c04-37bedb6cac3a.png"  width="300"/>
</p>

### Device information

* Android device: Asus Zenfone Max 1
* Fenix version: 3.0.1

**Comment by s-ankur** [comment]
related to #7013

**Comment by kbrosnan** [comment]
This does not sound different enough to be a separate bug from 7013
