### ISSUE TITLE
[Bug] Failure to build with autopublish.android-components.dir nested, relative directories on Linux

### ISSUE THREAD

**Issue by hawkinsw** [mozilla-mobile/fenix#7366]
## Steps to reproduce
On Linux, set `autoPublish.android-components.dir` to use a relative directory that is not immediately "adjacent" to the cwd. For example

`autoPublish.android-components.dir=../ac/android-components/`

will not work, but 

`autoPublish.android-components.dir=../android-components/`

does. 

Patch incoming.

### Expected behavior

Both should compile.

### Actual behavior

gradle compilation fails in `runCmd` on settings.gradle line 7.

### Device information
N/A

**Comment by Rob--W** [comment]
PR #7367 has been merged. Is there any reason for this bug still being open?
