### ISSUE TITLE
[Bug]Soundcloud doesn't play in the background anymore

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#7369]
## Steps to reproduce
1.  Navigate to Soundcloud.com
2. Play any track
3. Put Fenix in background

### Expected behavior
The desired track should continue playing in the background

### Actual behavior
The media playback is stopped once you put Fenix in background

### Device information

* Android device: Google Pixel 3a (Android 9)
* Fenix version: Nightly Build #13610606 from 12/27

### Note
In Chrome the media playback isn't stopped after you put the app in background

GeckoView bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1554297

**Comment by ekager** [comment]
Assuming this is related to having no notification as well #4793

**Comment by Diana-Rus** [comment]
Hi, issue still reproduces on Samsung Galaxy S9 (Android 8) with a Nightly debug build  39.0.20200412130044, d433836f0 GV: 77.0a1-20200410095419 AS: 0.55.0 .

I can also confirm that for soundcloud when playing a track there is no notification when Fenix is put in background.

**Comment by jonalmeida** [comment]
Added the dependant GV bug to the opening comment.

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly 201210`** using the following devices:
• Google Pixel 3a (Android 11)
• Huawei Mate 20 Lite (Android 10)
• OnePlus A3 (Android 6.0.1)
