### ISSUE TITLE
[Bug]No media playback notifiction displayed for Hot97 FM radio station

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#7370]
## Steps to reproduce
1. Navigate to [HOT97 FM ](https://www.hot97.com/listen-to-hot97)
2. Play the radio station

### Expected behavior
A media playback notification should be displayed

### Actual behavior
No media playback notification is displayed

### Device information

* Android device: Google Pixel 3a (Android 9)
* Fenix version: Nightly Build #13610606 from 12/27

### Note
Chrome displays the media notification for this radio station

**Comment by abodea** [comment]
Reproducible on **Fenix 3.1.0-beta  3(Build #20092354) GV 72** with **Google Pixel 3a XL(Android 10).**

**Comment by ekager** [comment]
Can still reproduce. Probably related to #4793 and root Gecko cause
