### ISSUE TITLE
PWA is always loaded again even if it's already running

### ISSUE THREAD

**Issue by ReekyMarko** [mozilla-mobile/fenix#7373]
This one is kind of hard to explain but if I have a PWA running, go back to my home screen and open it again, it loads the page again even though it's already loaded and ready in the app drawer.

**Comment by sblatz** [comment]
@ReekyMarko are you still experiencing this? Please give me your device info too if possible 😄

**Comment by ReekyMarko** [comment]
Hi! I'm running Android 10 on a Xiaomi Mi A3 (laurel sprout). This was also happening on my previous device, which was OnePlus 3T. 
Also, I'm not sure my original description of the problem was very clear. I will record a screen capture this evening and attach here.

**Comment by TitanNano** [comment]
@sblatz yes this is still happening. If a PWA activity is already open and then relaunched from the launcher, the page is reloaded. Also, the remote debugger then shows two open sessions for that page.

**Comment by TitanNano** [comment]
@sblatz this got fixed by recent session handling changes for PWAs in AC.

**Comment by ReekyMarko** [comment]
Can confirm, this is fixed now!
