### ISSUE TITLE
Investigate performance of data migration

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#7378]
Migration UX meta: https://github.com/mozilla-mobile/fenix/issues/879

(partially) Blocked on:
- the migration being implemented
- the UX of the migration being defined

### What
We want to ensure the performance of the migration is acceptable. Note that it looks like the Fenix team is coming up with a UX that will hide the true performance of the migration so this will probably be more perceived performance than pure migration speed.

### Impact
Without this, the UX of the data migration from a performance perspective may be unacceptable.

### Acceptance criteria
- Define me!

**Comment by mcomella** [comment]
Triage: waiting on the implementation to get further along before prioritizing.

**Comment by mcomella** [comment]
I sent [an email](https://groups.google.com/a/mozilla.com/d/msg/perf-android-fe/riH9TTq0dWc/ug_ZFYUVBAAJ) to the team with answers to a few open questions we have had.

### Proposed action items
- (now) Validate assumptions: is migration really < 2s? Is the UX sufficient or should we request changes?
- (Jan. 15 or when ready) Validate perf of final data migration code
- (Feb. 18 or when ready) Validate perf & experience w/ UX
- (ongoing) If changes are made to migration code, revalidate performance

**Comment by mcomella** [comment]
Triage: we're focusing on startup & the data migration team seems to have perf in mind so we put this lower in the list but it'd be good to address the first action items sooner rather than later.

**Comment by ecsmyth** [comment]
[Visualization for nightly migration times](https://sql.telemetry.mozilla.org/queries/67891#171699). We have gaps in our understanding since timing data is only available for some parts of the migration, not the experience as a whole. Fenix UX and migration teams have been informed. I'll monitor the upcoming migrations but I don't anticipate any further work on this issue.
