### ISSUE TITLE
[Bug] Pressing back on DeviantArt will prevent additional content from loading (& will not restore scroll position)

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#7382]
This is likely a GV issue so I filed https://bugzilla.mozilla.org/show_bug.cgi?id=1606128. Info below is copied from BZ issue.

I wonder if this is related to back caching: #5869.

---

This reproduces maybe 90% of the time for me.

### STR
- Visit deviantart.com (note: deviantart has less safe for work content: typical art stuff)
- Scroll down a lot, triggering multiple async JS content loads (typical endless scrolling pattern)
- Click an image to open the detailed view
- Press back button to return to overview page. Note when content loads, scroll position is not restored
- Scroll down

### Expected
Scrolling down continues to load additional content. Scroll position was restored. 

### Actual
Two issues:
1. Any content loaded after the initial page load is not visible (i.e. appears as empty space). Additional content does not load asynchronously
1. Scroll position is not restored. This makes it practically impossible to use the browser to view deviantart because you cannot click into entries without losing your place

These issues may be related (e.g. this might be related to using an invalid back cache bug 1545909) so I only filed one bug: feel free to split them.

### Info
- Device: Pixel 2
- Version: Fenix Nightly 191226

**Comment by fluffyemily** [comment]
I have contacted the team dealing with this issue and they are discussing potential solutions to prioritise for GV 75.

**Comment by ekager** [comment]
Seems to be resolved. Closing
