### ISSUE TITLE
[Bug] Unable to disable tracking protection on error page

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#7383]
## Steps to reproduce
- Visit a website that will return an error page (e.g. http://deviantarrrrrrrrrrrrrrt.com/)
- Clicking tracking protection icon

### Expected behavior
Able to disable tracking protection

### Actual behavior
Unable to disable tracking protection. This may be a problem if content on the site is unable to load (i.e. you didn't follow my STR above and hit an error page on a real site) and you suspect tracking protection may be causing this problem.

### Device information

* Android device: Pixel 2
* Fenix version: Nightly 191226

**Comment by s-ankur** [comment]
Hi, this works now

**Comment by mcomella** [comment]
Confirmed.
