### ISSUE TITLE
[Bug] open_links_in_a_private_tab metric implementation is incorrect

### ISSUE THREAD

**Issue by emalysz** [mozilla-mobile/fenix#7384]
## Steps to reproduce
open_links_in_a_private_tab is defined in https://github.com/mozilla-mobile/fenix/blob/master/app/metrics.yaml as a "preference key for the boolean (true/false) preference the user toggled." There are two issues:
1. The user is not setting this preference. This is currently handled in processIntent each time an intent is received.
2. The metric is being recorded incorrectly. When any intent is processed and we are not the default browser, the metric will be fired, but perhaps that should happen when the preference is actually toggled.

Implementation of metric has not changed, but we became aware of it working on https://github.com/mozilla-mobile/fenix/pull/7246

**Comment by boek** [comment]
@emalysz I agree. If we want to record the state of this toggle we should make it a metric, not an event.

**Comment by liuche** [comment]
Duping to #11118 which fixes this!
