### ISSUE TITLE
[Bug] Unclear when the "Reader view" toggle is available after pageload

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#7385]
## Steps to reproduce
- Visit nytimes.com
- Click an article
- Click 3-dot menu (quickly) to enable Reader View. Notice it's not there. Close menu and repeat until it's available.

### Expected behavior
Reader View toggle is available when page starts loading or I can sit around and wait for a prompt to appear

### Actual behavior
Reader View toggle does not appear each time menu is clicked until several seconds after progress bar completes page load. This makes it very tedious to try to engage reader mode for a page I know I want to use it on.

### Device information

* Android device: Pixel 2
* Fenix version: Nightly 191226

**Comment by liuche** [comment]
We added a menu-highlight (blue dot) in #7352, which while doesn't fix the issue of Reader Mode taking a while to load, does mean you don't have to keep toggling the menu button.

If this is work beyond eng:perf issue, I would drop it down to a P3.

**Comment by mcomella** [comment]
> We added a menu-highlight (blue dot) in #7352, which while doesn't fix the issue of Reader Mode taking a while to load, does mean you don't have to keep toggling the menu button.

@liuche To be fair, it's unintuitive that this blue dot is intended to indicate "reader mode is available." For example, I thought the blue dot might be an onboarding feature for reader mode that might disappear once I activated reader mode. Maybe we should change the dot to a blue reader mode icon or something?

After speaking with Christian, we came to the conclusion that this is a purely UX issue: the reader mode toggle relies on the DOM being loaded which we can't make faster. The solution is purely UX, e.g. by making it intuitive when reader mode is available.

**Comment by mcomella** [comment]
Removing eng:perf because I don't think it's actionable by our group.

**Comment by Dunexus** [comment]
Also this blue dot is used to indicate PWA is available for this website which makes it even more unclear

**Comment by csadilek** [comment]
This has been fixed in https://github.com/mozilla-mobile/fenix/issues/11045 which moved the toggle to the toolbar and made it visible without having to check the 3-dot menu. So, we can close this now. :)
