### ISSUE TITLE
Look into whether or not some part of Glean initialization can be done separately, or later after start up to reduce start up time.

### ISSUE THREAD

**Issue by MarcLeclair** [mozilla-mobile/fenix#7386]
### Why/User Benefit/User Problem
Current Glean implementation takes a big chunk of start up time ( ~10-20% at times). I think we should try to see if we can offload some of it to after initialization, or maybe some to a worker thread. I am aware that Glean needs to register observers on the UI thread, but I think it would be worthwhile to investigate for a bit.
### Impact
Faster start up time means better quality of use

### Acceptance Criteria (how do I know when I’m done?)
Glean still behaves as expected but app start up is faster.

**Comment by MarcLeclair** [comment]
Most of the Glean initialization is quick but the two "bottlenecks" were the AC Migration and the GLean Scheduler which was mostly a string manipulation error. Here are the two bugzilla tickets that address those issues:

1) [AC migration](https://bugzilla.mozilla.org/show_bug.cgi?id=1605114)
2)[String manipulation](https://bugzilla.mozilla.org/show_bug.cgi?id=1604819)

@mcomella   I'll close this since the first issue takes ~25% and the second ~37%. Fixing those two could  reduce Glean start up by more than 50%. It might be hard to play more with Glean initialization since the rest has to be done on the MT ( most of it at least) and might only gain us an extra few % of Glean initialization. I think this would be too risky for the rewards we'd get.

**Comment by mcomella** [comment]
@MarcLeclair Thanks for investigating: I'm happy to close this issue.

I noticed 2 was closed: has it made it into Nightly? I'm curious if it has impacted our performance numbers, e.g. ND or FNPRMS. ND looks a little too noisy to tell though.

Would you mind filing issues in Fenix for 1 (linking to the Bugzilla tickets) and adding them to our project board so we can remember to monitor for changes in ND/FNPRMS? I assume it should go in the Waiting column.

**Comment by mcomella** [comment]
Moved to Done: I assume this can be closed.
