### ISSUE TITLE
[CFR] Contextual Feature Recommender disappears right away while scrolling

### ISSUE THREAD

**Issue by AmyYLee** [mozilla-mobile/fenix#7387]
Steps to reproduce:

1. Have a fresh install of Fenix
2. Open a website that activates Enhanced Tracking Protection (CNN.com)
3. Scroll down the page

Expected:
Contextual feature recommender (CFR) appears for Enhanced Tracking Protection (ETP)
and stays there while you scroll. Tapping on the "x" will close the CFR. 

Actual: 
CFR disappears right away while scrolling.

**Comment by ekager** [comment]
After discussing with @AmyYLee on Slack the changes we want to make here are:
- User cannot scroll page while CFR is displayed (on first page load with trackers). CFR should take screen focus and only be dismissable via the X button.
- Dialog should now only be shown once on first page load with trackers blocked (currently shown twice, in 2 distinct sessions)

**Comment by sv-sdeiac** [comment]
Hi, I can confirm that the CFR notification is displayed and can be dismissed only by tapping on the "X" button from the dialog.

Devices:
- Huawei MediaPad M2 (Android 5.1.1);
- LG G7 fit (Android 8.1);
- Samsung Galaxy Note 8 (Android 9);
- Google Pixel 3 (Android 10).

Build: 
- Firefox Preview Nightly 4/24 #21150607.
