### ISSUE TITLE
[Bug] UI Settings About test - assert date failure

### ISSUE THREAD

**Issue by rpappalax** [mozilla-mobile/fenix#7388]
Looks like time mismatch on build date when running in firebase
```
androidx.test.espresso.base.DefaultFailureHandler$AssertionFailedWithCauseError: 'with text: is "Friday 12/27 @ 8:23 PM"' doesn't match the selected view. 
```

https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7676691115745540948/executions/bs.7282f4e3b1ca6bc9/testcases/1/test-cases

**Comment by boek** [comment]
@rpappalax is this still a problem?

**Comment by AaronMT** [comment]
Don't think I've seen this recently
