### ISSUE TITLE
[FxA] Log into FxA using QR code gets you a 500 error

### ISSUE THREAD

**Issue by AmyYLee** [mozilla-mobile/fenix#7389]
Log into your FxA account using the QR code option

Expected:
You are successfully logged in.

Actual:
500 Error screen

Note: This was during FxA maintenance work so this issue might have been resolved.

![Screenshot_20191212-125418](https://user-images.githubusercontent.com/5992746/71532965-22c10e80-28c4-11ea-9eae-a172cfaf3370.png)

**Comment by boek** [comment]
Looks like it's working again
