### ISSUE TITLE
Make "save session" button float at bottom of the screen

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#739]
Instead of just appending the "save session" and "erase session" (for normal and private modes respectively) to the bottom of the current session list, it'd be great if the button floated on the bottom of the screen.

Original inspiration [found here](https://github.com/mozilla-mobile/fenix/issues/181#issuecomment-460085945)

**Comment by sblatz** [comment]
If we decide to go with a floating button solution, let's make sure it's applied to both buttons. Some start work can be found [here](https://github.com/mozilla-mobile/fenix/compare/master...sblatz:delete-session?expand=1).

**Comment by lime124** [comment]
removing ux label - we are in the process of collecting homescreen/collections related issues to tackle in a later ux effort.

**Comment by vesta0** [comment]
Discussed this with Nicole and this no longer applies to the new designs.
