### ISSUE TITLE
[Bug][Crash] Crash on multiple sites - sometimes even just after opening

### ISSUE THREAD

**Issue by marcinwiacek** [mozilla-mobile/fenix#7391]
## Steps to reproduce

Open https://forums.anandtech.com/threads/gainward-gtx-750-obnoxious-noisy-fan.2421268/ and wait 

OR

open spidersweb.pl, pcworld.pl, wait and scroll

### Expected behavior

browser doesn't crash

### Actual behavior

12-27 22:33:14.643 17224 17224 E AndroidRuntime: java.lang.IllegalArgumentException: Invalid color format
12-27 22:33:14.643 17224 17224 E AndroidRuntime: 	at org.mozilla.geckoview.GeckoSession.rgbaToArgb(GeckoSession.java:3)
12-27 22:33:14.643 17224 17224 E AndroidRuntime: 	at org.mozilla.geckoview.GeckoSession.fixupManifestColor(GeckoSession.java:1)
12-27 22:33:14.643 17224 17224 E AndroidRuntime: 	at org.mozilla.geckoview.GeckoSession.fixupWebAppManifest(GeckoSession.java:1)
12-27 22:33:14.643 17224 17224 E AndroidRuntime: 	at org.mozilla.geckoview.GeckoSession.access$000(GeckoSession.java:1)
12-27 22:33:14.643 17224 17224 E AndroidRuntime: 	at org.mozilla.geckoview.GeckoSession$2.handleMessage(GeckoSession.java:36)
12-27 22:33:14.643 17224 17224 E AndroidRuntime: 	at org.mozilla.geckoview.GeckoSession$2.handleMessage(GeckoSession.java:1)
12-27 22:33:14.643 17224 17224 E AndroidRuntime: 	at org.mozilla.geckoview.GeckoSessionHandler.handleMessage(GeckoSessionHandler.java:2)
12-27 22:33:14.643 17224 17224 E AndroidRuntime: 	at org.mozilla.gecko.EventDispatcher$3.run(EventDispatcher.java:1)
12-27 22:33:14.643 17224 17224 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:789)
12-27 22:33:14.643 17224 17224 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:98)
12-27 22:33:14.643 17224 17224 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:164)
12-27 22:33:14.643 17224 17224 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6944)
12-27 22:33:14.643 17224 17224 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
12-27 22:33:14.643 17224 17224 E AndroidRuntime: 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
12-27 22:33:14.643 17224 17224 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)

### Device information

* Android device: S7 / Android 8
* Fenix version: nightly

**Comment by boek** [comment]
Dup of #7371
