### ISSUE TITLE
[Bug]Can't prohibit autoplay

### ISSUE THREAD

**Issue by edentw** [mozilla-mobile/fenix#7393]
## Steps to reproduce
Website where the problem occurred:
https://m.ettoday.net/news/20191228/1612205.htm

### Expected behavior
Autoplay should be disabled.

### Actual behavior
The video below this website will have autoplay problems and cannot be banned. Can you fix the problem, thank you.

### Device information

* Android device: Android 9.0
* Fenix version: Firefox Mobile 73.0

**Comment by boek** [comment]
Dup of #255
