### ISSUE TITLE
[Bug] Firefox crashes on creating a new folder in the "Desktop Bookmarks" Bookmarks Folder

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#7396]
## Steps to reproduce
Go to Bookmarks
Open Desktop Bookmarks folder
Tap the "add folder button"
Name the new folder
tap the tick mark button
### Expected behavior
No Crash
### Actual behavior
Firefox Crashes
### Device information

* Android device: Asus Zenfone Max Pro M1
* Fenix version: 3.0.1

**Comment by masi456** [comment]
Hey,

seems like a duplicate of #4994? For me it is not reproducible in current master.

**Comment by s-ankur** [comment]
@masi456 Yes I think this is the same issue.
