### ISSUE TITLE
Browser crashes after loading certain sites [Bug]

### ISSUE THREAD

**Issue by eyalyoli** [mozilla-mobile/fenix#7397]
## Steps to reproduce
Go-to the site and load it fully, sites such as: 
https://github.com
https://forum.utorrent.com
Never mind what page you load. When fully loaded the browser crashes. Happens with the 3+ latest updates. I've sent the crash reports several times. Restarting the browser, clearing cache and storage doesn't help. 
### Expected behavior
Doesn't crash. 
### Actual behavior
Crashes and asks to send crash report. 
### Device information
Huawei p20 lite
* Android device: 9.0
* Fenix version: 
Nightly 191228 06:01 (Build #13620609)
27.0.0, d10c36024
GV: 73.0a1-20191224041100

**Comment by boek** [comment]
Dup of #7371
