### ISSUE TITLE
[Bug] Normal mode tab is minimized unnecessarily when closing private tabs via the close private browsing session notification 

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#7398]
## Steps to reproduce
Open a private mode tab.
Without closing this tab, open the normal mode.
Open a normal mode tab.
Close the private mode session using the notification.
### Expected behavior
Private session is closed without affecting the current tab
### Actual behavior
Private session is closed but the current normal tab is minimized unnecessarily
### Device information

* Android device: Asus Zenfone Max Pro M1
* Fenix version: 3.0.1

**Comment by sblatz** [comment]
I'm able to reproduce this on the latest nightly.

**Comment by s-ankur** [comment]
I can still see this in nightly

**Comment by s-ankur** [comment]
Seems to be fixed now, can someone verify it?
