### ISSUE TITLE
[Bug] Moving default bookmark folders in Firefox desktop into the Mobile Bookmarks folder will show up as place:parent=menu______

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#7400]
## Steps to reproduce
1. In firefox desktop library menu, move the Bookmarks Menu/Other Bookmarks/Bookmarks Toolbar into the mobile bookmarks folder (it will be copied instead of being moved)
2. sync account on desktop
3. sync account on fenix 
4. Open bookmarks library on fenix 

### Expected behavior
The Bookmarks Menu/Other Bookmarks/Bookmarks Toolbar  folders show up and you can use them normally and nothing bad happens
### Actual behavior
<img src="https://user-images.githubusercontent.com/33252312/71547520-fa6e0880-29c6-11ea-8a2e-756bf564c4f6.png" width="400" align="center" />
Opening these folders just opens a google search for place:parent=menu_____ / place:parent=unfilled_____ / place:parent=toolbar_____ respectively. 

### Device information
* Android device: Asus Zenfone Max Pro M1
* Fenix version:
Nightly 191228 06:01 (Build #13620609)
27.0.0, d10c36024
GV: 73.0a1-20191224041100

**Comment by pepve** [comment]
#2861 would prevent these folders from showing up.
