### ISSUE TITLE
[Bug] Webrender not scroll or zooming smooth on Chinese website.

### ISSUE THREAD

**Issue by lindongbin** [mozilla-mobile/fenix#7401]
e.g. https://www.cnbeta.com/

* Android device: ?
* Fenix version: ?

**Comment by liuche** [comment]
Will surface to GV team to pass on to WR team. WR will also only ship default on for Pixel devices, until after 75 release.

**Comment by boek** [comment]
GV bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1610946

**Comment by lindongbin** [comment]
https://i.imgur.com/4sjRcrU.mp4
This is a comparison video

**Comment by boek** [comment]
@lindongbin Which device are you seeing this on?

**Comment by lindongbin** [comment]
> 
> 
> @lindongbin Which device are you seeing this on?

xiaomi mi note 3
https://www.gsmarena.com/xiaomi_mi_note_3-8707.php

**Comment by fluffyemily** [comment]
@boek This [comment](https://bugzilla.mozilla.org/show_bug.cgi?id=1610946#c2) from Kris is asking for more information about whether this with webrender enabled or disabled? He can see some delays without webrender, but webrender on seems fine. Can you add an about:support?

**Comment by lindongbin** [comment]
> @boek This [comment](https://bugzilla.mozilla.org/show_bug.cgi?id=1610946#c2) from Kris is asking for more information about whether this with webrender enabled or disabled? He can see some delays without webrender, but webrender on seems fine. Can you add an about:support?

![Screenshot_2020-04-21-23-18-00-404_org mozilla firefox](https://user-images.githubusercontent.com/3154109/79883684-d0819b80-8426-11ea-93ec-2c2dc93b3e57.jpg)
![Screenshot_2020-04-21-23-17-41-018_org mozilla firefox](https://user-images.githubusercontent.com/3154109/79883698-d2e3f580-8426-11ea-80ca-ccc3c8c947ec.jpg)
![Screenshot_2020-04-21-23-18-21-122_org mozilla firefox](https://user-images.githubusercontent.com/3154109/79883704-d37c8c00-8426-11ea-82ea-0f88ec9e5d2c.jpg)
![Screenshot_2020-04-21-23-18-13-054_org mozilla firefox](https://user-images.githubusercontent.com/3154109/79883708-d4adb900-8426-11ea-94f8-641ec9bd13e3.jpg)
![Screenshot_2020-04-21-23-18-37-699_org mozilla firefox](https://user-images.githubusercontent.com/3154109/79883709-d5464f80-8426-11ea-941c-63a2daa8b6e1.jpg)
![Screenshot_2020-04-21-23-18-29-351_org mozilla firefox](https://user-images.githubusercontent.com/3154109/79883714-d5dee600-8426-11ea-8375-c919ce51be09.jpg)
![Screenshot_2020-04-21-23-18-45-387_org mozilla firefox](https://user-images.githubusercontent.com/3154109/79883717-d7101300-8426-11ea-8700-54e58814ab9b.jpg)
![Screenshot_2020-04-21-23-19-07-152_org mozilla firefox](https://user-images.githubusercontent.com/3154109/79883721-d7a8a980-8426-11ea-90b0-6841ae062057.jpg)
![Screenshot_2020-04-21-23-18-54-739_org mozilla firefox](https://user-images.githubusercontent.com/3154109/79883727-d8d9d680-8426-11ea-906b-32bfa2572c1e.jpg)
![Screenshot_2020-04-21-23-19-14-337_org mozilla firefox](https://user-images.githubusercontent.com/3154109/79883731-d9726d00-8426-11ea-9951-59f8d458d9c9.jpg)

**Comment by lindongbin** [comment]
It should be because the phone performance is too poor
