### ISSUE TITLE
[Bug] "Close private tab" notification does not work with embedded "Powered by Firefox" browser

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#7405]
## Steps to reproduce
1. Set firefox preview as default browser.
2. Check "Open links in a private tab" option in this menu.
3. Go to the reddit app. 
4. Open any web link url (Assuming that the "open web links in app" reddit setting is on)
5. Click on the Close private tab notification
### Expected behavior
The embedded browser should close and you should return to the host app (reddit)
### Actual behavior
The embedded private tab is not closed. Firefox opens up in the default homepage (very unexpected)
### Device information

* Android device: Asus Zenfone Max Pro M1
 * Fenix version:
    Nightly 191228 06:01 (Build #13620609)
    27.0.0, d10c36024
    GV: 73.0a1-20191224041100

**Comment by cadeyrn** [comment]
The notification for private custom tabs was disabled in #7392 so this should no longer be an issue with the next update.

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **Nightly Build #13650606 from 12/31** using the following devices:
• Google Pixel 3a (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

► Video
![20191231_084936](https://user-images.githubusercontent.com/51314259/71612871-cef84300-2bab-11ea-8edc-c4aaf85a1b26.gif)
