### ISSUE TITLE
[Bug] The onboarding tour is not dismissed after opening the "Privacy notice" page

### ISSUE THREAD

**Issue by softvision-miralobontiu** [mozilla-mobile/fenix#7407]
## Steps to reproduce
1. Make sure you have a clean profile.
2. Scroll down the onboarding tour, until you reach Your privacy card, and tap on "Read our privacy notice".
3. Choose to  "Open in Firefox Nightly" the opened custom page.
4. Tap on the counter tabs. 

### Expected behavior
After step 4, the Homescreen is displayed with 1 tab opened.

### Actual behavior
The user is redirected to the onboarding tour. Tapping on the "Start browsing" button leads to the empty Homescreen. After a couple of minutes, the tab is displayed.

### Device information
* Android device: Nexus 6P (Android 8.1), Nexus 5 (Android 6.0.1), and Google Pixel 3A (Android 9), OnePlus 5T (Android 9), Samsung Galaxy S8 (Android 9), Google Pixel (Android Q)
* Fenix version: 12/30 build (#13640626)

[logcat.txt](https://github.com/mozilla-mobile/fenix/files/4009340/Mira.txt)

**Comment by kbrosnan** [comment]
There are cases where we want to preserve the onboarding screen and viewing the privacy notice was one of them as I recall.

**Comment by boek** [comment]
@kbrosnan that is correct. The only two ways to dismiss the onboarding screen are:
1. Tapping on the search bar
2. Tapping "Start browsing"

It might make sense to make the privacy notice open in a custom tab so your only action is to close it and end up back at the home screen.

**Comment by boek** [comment]
@apbitner What do you think?

**Comment by apbitner** [comment]
@boek I think we should consider the privacy notice as part of the onboarding, therefore it should **not** dismiss the onboarding cards.

**Comment by kbrosnan** [comment]
We already do this. The question was should we treat the Privacy Notice as a custom tab so that pressing the back button would take the user back to onboarding.

**Comment by apbitner** [comment]
Sorry I misunderstood. Yes, a custom tab seems to make sense to solve this issue.

**Comment by softvision-miralobontiu** [comment]
Hi guys!
Maybe I was not clear on the steps: the privacy notice page opens in a custom tab. But the users have the option to open the page in a tab. Maybe this option should be disabled (just a thought :)).
Thank you,

**Comment by apbitner** [comment]
I'm unable to reproduce, for me it just opens in a custom tab. It probably would be a good idea to eliminate any choice for the user and force open in a custom tab.

**Comment by boek** [comment]
@apbitner I think they mean once you open the custom tab, since it is a custom tab, you can open the 3 dot menu and there is a “Open in Fenix” button that will move it to a regular tab

**Comment by apbitner** [comment]
@boek Ahh, okay. My first preference would be to hide the 3-dot menu entirely, otherwise disable that option as they recommended.

**Comment by kbrosnan** [comment]
* fresh install
* Scroll down to the privacy notice and tap on it
* In the custom tab tap the three dots menu
* Select open in Firefox

This is an involved enough set of steps that I don't think we should special case this. Suggest closing this as working as intended.

**Comment by softvision-miralobontiu** [comment]
Based on Kevin's comment, I'll close this issue.
