### ISSUE TITLE
increase in session bundles when clicking on a session bundle

### ISSUE THREAD

**Issue by cadeyrn** [mozilla-mobile/fenix#741]
_I already filed a similar report (#716) which was fixed but now something similar happens with the session bundles._

### Steps to reproduce

1. open a website
2. press the tabs button
3. press on the session bundle below the "Today" caption
4. repeat step 3
5. repeat step 3

### Expected behavior

no increase in session bundles

### Actual behavior

after step 3: two session bundles instead of one
after step 4: three session bundles
after step 5: four session bundles

### Device information

* Android device: HTC U11 / Android 8.0
* Fenix version: Fenix revision 84a2b24554079dac6e69b1a8d3fe6ed6fc23358f

**Comment by cadeyrn** [comment]
Now it requires more steps to reproduce but the issue is still there. ;-)

1. open a website
2. press the tabs button
3. press the "Save Session" button
4. press on the session bundle
5. repeat step 4

=> now there are two session bundles. Repeat again and there are three session bundles.

**Comment by boek** [comment]
@cadeyrn this is as expected as bundles are read only. When you restore a bundle it's actually creating a new session. We should bring it up with product and UX though

**Comment by cadeyrn** [comment]
I understand that logic and it makes sense until step 4. I click on the session bundle, Fenix starts a new session and I see my tab from step 1 below "Current Session".

With step 5, it starts to get confusing. From a technical POV this still makes sense. The same logic applies as in the previous step. Fenix creates a new session, so there are two bundles now. But from my "stupid user"'s POV I see that Fenix duplicates the bundle _for no good reason_. My expection as a user is that the bundle will not be duplicated.

It would be great if you could discuss this with product and UX. Should this ticket be reopened until the discussion has taken place so that it is not forgotten? If product and UX decide against a change it can still be closed again. What do you think?

**Comment by boek** [comment]
@cadeyrn Sorry I missed your comment! I totally agree. I tried to fix it up to the best of my ability. We're passing the prototype off to user-research to get some research so we can get some feedback and iterate 🙌
