### ISSUE TITLE
Remove RxJava dependency for potential build times & APK size improvements

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#7410]
According to [GH search](https://github.com/mozilla-mobile/fenix/search?q=io.reactivex&unscoped_q=io.reactivex), RxJava is only used in `EditBookmarkFragment`: we should remove it. Potential benefits:
- Improved build times saving devs time every day :)
- Decreased APK size (at max RxJava appears to be 1.9 MB)

Since we're using a small subset of Rx, the effect of these changes may be negligible: it's hard to say for sure without additional research (at which point we may wish to just remove it).

**Comment by mcomella** [comment]
I pulled down Severin's PR #7426 locally: 671 methods were removed between my proguarded build yesterday and Severin's patch but the APK size increased (presumably for unrelated reasons) by .4 MB. I don't know where exactly the HEAD of each PR is.

**Comment by mcomella** [comment]
In hindsight, we could have used the Analyze APK feature to see the size in the APK and method count these tools took up.

**Comment by liuche** [comment]
No qa needed, removing unused code for perf.
