### ISSUE TITLE
[Bug] Crash with IllegalArgumentException: Invalid color format (github.com)

### ISSUE THREAD

**Issue by liuche** [mozilla-mobile/fenix#7411]
Sentry crash: https://sentry.prod.mozaws.net/operations/fenix-nightly/issues/6951696/

Looks like fallout from #5585 and BZ-1604917

## Steps to reproduce
(Specific site with color problems): https://github.com/mozilla-mobile/fenix/

### Expected behavior
Page loads

### Actual behavior
Page starts loading, crashes

### Device information

* Android device: Pixel 3
* Fenix version: Nightly 12/28, AC 27

**Comment by kbrosnan** [comment]
Sentry is showing this crash trending down. Updating your Firefox Preview should stop the crash.
