### ISSUE TITLE
[Bug] Pressing back in BrowserFragment causes session to disappear

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#7412]
## Steps to reproduce
1. Load any site
2. Press back

### Expected behavior
1. Taken back to home screen with session showing as selected

### Actual behavior
1. Taken back to home screen and **session is gone**

### Device information

* Android device: Galaxy S9 Android 9
* Fenix version: Master and nightly 191230 (Build #13640627)

**Comment by sblatz** [comment]
Throwing this in group triage because this seems like a pretty bad bug 😬

**Comment by sblatz** [comment]
Looks to be related to https://github.com/mozilla-mobile/fenix/commit/1e813a96094dcceed699e8e8492db8fe32ea360f

Or at the very least to the `removeSessionIfNeeded` func

**Comment by sblatz** [comment]
Based on what I can tell this is **intended behavior**. I just found it really surprising. I'm going to have UX confirm this is what should happen.

**Comment by mawen7** [comment]
Related to #6620 which is waiting on ux feedback as well, see last comment from @ekager

**Comment by sblatz** [comment]
Thanks for linking that @mawen7 I wasn't aware of that discussion.

I found this behavior confusing as the back button is not usually a destructive action 😅

**Comment by sblatz** [comment]
Closing as dup
