### ISSUE TITLE
[Bug] Can't read text on about screen when in private mode

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#7414]
If you go to the "About Fenix" page in private mode, the text cannot be read. We're probably just using the wrong attribute color here.

<img width="350" alt="image" src="https://user-images.githubusercontent.com/4400286/71592933-ec170e00-2ae6-11ea-98cc-31b487fe8066.png">

**Comment by obitodarky** [comment]
@boek I would like to work on this Issue. Can you help me out with a few things?

**Comment by boek** [comment]
Yes, for sure!

How can I help?

**Comment by obitodarky** [comment]
I would like to know which build variant should I work on and where can I find the file which mentions the text color.

**Comment by KaairaGupta** [comment]
@boek I have worked a bit on this issue, and i needed some help with it.  Is there a difference between how the private mode theme works in dark and light modes? If so, then where in the code can i find it because this problem persists just in the light mode

**Comment by KaairaGupta** [comment]
@boek i have fixed the bug and am making a PR. Are there any guidelines that i have to follow for the same? It's my first time with open source

**Comment by KaairaGupta** [comment]
@boek @ekager please review my PR

**Comment by ekager** [comment]
Reopening for QA

**Comment by KaairaGupta** [comment]
@ekager can you please let me know why this issue is reopened? Was there any mistake in my PR, and how should i proceed if there was?

**Comment by ekager** [comment]
No issue! Our process is just to keep issues open until our QA team can verify that they've been fixed.
In the future, you can use the keyword "For #7414" instead of "Closes #7414" to help me out :)

**Comment by tvenissat** [comment]
@ekager The [shared documentation](https://github.com/mozilla-mobile/shared-docs/blob/master/android/CONTRIBUTING_code.md#creating-a-pull-request) states that:

> An example commit message summary looks like, Closes #5: Upgrade gradle to v1.3.0.". 

Yet, most commits to this repository (as well as other Mozilla repositories) mainly use the `For` or `Fixes` [keywords](https://help.github.com/en/github/managing-your-work-on-github/closing-issues-using-keywords) instead. Also, I can't find a reference to the `For` keyword anywhere. Do we just use `For` when we don't want to automatically close the linked issue and `Closes` when we do?

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **Nightly Build #20100616 from 01/10** using the following devices:
• Google Pixel 3a (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

► Screenshot
![rsz_screenshot_20200110-085717](https://user-images.githubusercontent.com/51314259/72132467-ad574280-3387-11ea-9e40-8d5ee2bdc992.png)
