### ISSUE TITLE
[PWA] Can add multiple icons for the same PWA

### ISSUE THREAD

**Issue by AmyYLee** [mozilla-mobile/fenix#7418]
Steps to reproduce:

1. Go to a website that supports PWAs (i.e Twitter)
2. Install a PWA using "add automatically"
3. Close Fenix and open it again and install another PWA using "add automatically"
4. Add another PWA using "manual"

Expected:
Only allow one stance of PWA to be installed 

Actual:
You can install multiple instances of a PWA if you close the app and reopen and also if you use automatic and manual.

**Comment by NotWoods** [comment]
We can't restrict this on the OS level but we could hide/change the menu option if we detect that the PWA is installed.

**Comment by TitanNano** [comment]
@AmyYLee @NotWoods as I discussed with @NotWoods in https://github.com/mozilla-mobile/android-components/issues/5667#issuecomment-577188547 even Android 8+ does not give us reliable information on whether a shortcut is currently present in the users launcher or not. But with the new installation state exposed by AC the menu option could be made less prominent.

**Comment by sflorean** [comment]
This is still reproducible on Nightly, Beta and RC builds with Pixel 3 (Android 11).
