### ISSUE TITLE
[Search] Need more contrast between dark search favicons on dark theme

### ISSUE THREAD

**Issue by AmyYLee** [mozilla-mobile/fenix#7419]
Can we adapt icons for light/dark mode? (i.e is there a Light/Dark version of the amazon favicon?)
@mconnor 

![Screenshot_20191230-153239](https://user-images.githubusercontent.com/5992746/71599688-e4bd2800-2b19-11ea-8819-9126d8227541.png)

If the answer is no, can we add a hairline around the favicons? 

Dark theme #FBFBFE 12% opacity 
Light theme #15141A 125 opacity

This should be the same colouring as the hairlines we use as separators.

**Comment by lime124** [comment]
caught up with mconnor and we should use the light versions of amazon and wikipedia. desktop assets can be found here: https://searchfox.org/mozilla-central/source/browser/components/search/extensions 

@boek do these work or do we need something else?

**Comment by LaurentiuApahideanSV** [comment]
I tested the issue on Firefox Preview Nightly 200703 (Build #21850624) and the search engine icons are still dark when using Dark Theme.
### Devices used
- OnePlus 6T (Android 9)
- Huawei MediaPad M3 (Android 7)
![Screenshot_20200703-115032](https://user-images.githubusercontent.com/50983519/86451747-08109c00-bd24-11ea-9759-be6b3e732d39.jpg)
