### ISSUE TITLE
[Share] Not enough contrast in copy to clipboard icon

### ISSUE THREAD

**Issue by AmyYLee** [mozilla-mobile/fenix#7420]
Can we update the copy to clipboard icon so there's higher contrast? It should be the same colour as our icons on light/dark theme.

<img width="520" alt="Screen Shot 2019-12-30 at 3 48 16 PM" src="https://user-images.githubusercontent.com/5992746/71600182-dcfe8300-2b1b-11ea-9ee6-1667d482c192.png">

**Comment by ekager** [comment]
I believe that is an action provided by another app, so I'm not sure we can modify this icon

**Comment by Mugurell** [comment]
We could hardcode a tint for a specific Activity if we are sure the activity and it's icon would not change.
OR we could just roll our own icon, again hardcoded for a specific share to Activity.

**Comment by AmyYLee** [comment]
> We could hardcode a tint for a specific Activity if we are sure the activity and it's icon would not change.
> OR we could just roll our own icon, again hardcoded for a specific share to Activity.

"Copy to clipboard" doesn't seem to appear in the share sheet anymore.

**Comment by Mugurell** [comment]
As Emily said, this functionality is provided through another application that the user has installed.
She could have none or even more applications installed that would support "copy to clipboard".

Thinking about this.. gathering a list of such apps is not really feasible time wise.
Then we would not have any kind of control in how/when those apps change their "copy to clipboard" icon.

We could go the other route of excluding other apps from providing this functionality and use our own "Copy to clipboard" over which we have total control, but in this case also we would need to know exactly what activities to exclude or we could try our luck with fuzzy matching based on the activity name.
