### ISSUE TITLE
[Settings] Remove "Collections" from delete browsing data

### ISSUE THREAD

**Issue by AmyYLee** [mozilla-mobile/fenix#7421]
This is a recommendation to remove "Collections" from Delete browsing data. I would treat collections like bookmarks where the user has proactively saved items. It's pretty destructive if the user isn't paying attention and accidentally clears their Collections. 

### Acceptance Criteria
- [ ] Collections is no longer on this list

![Screenshot_20191230-154626](https://user-images.githubusercontent.com/5992746/71600491-30bd9c00-2b1d-11ea-92d2-480ba61bbb73.png)

**Comment by evilpie** [comment]
Best of both worlds: Make Collections unchecked by default.

**Comment by liuche** [comment]
Amy will check w/ shorlander about the decision behind this, and next steps. Is pretty easy to destroy data that is time-consuming to curate.

**Comment by AmyYLee** [comment]
Hi @liuche 

I spoke to @shorlander about this and he's okay with us removing "Collections" from this screen.

**Comment by KaairaGupta** [comment]
@AmyYLee can be assigned this issue? Also, will i have to remove the 'collections' from this screen or keep it unchecked by default?

**Comment by AmyYLee** [comment]
> @AmyYLee can be assigned this issue? Also, will i have to remove the 'collections' from this screen or keep it unchecked by default?

@KaairaGupta - Hi, please remove "collections" entirely from this screen. @liuche to confirm about assigning this issue

**Comment by KaairaGupta** [comment]
@AmyYLee i have made the PR, please review it

**Comment by AmyYLee** [comment]
> @AmyYLee i have made the PR, please review it

@KaairaGupta Can you attach a screenshot of the update? Thanks

**Comment by KaairaGupta** [comment]
![collections_removed](https://user-images.githubusercontent.com/45488611/72280676-e4b34100-365e-11ea-8fa6-3440d24a9dac.jpeg)
 

i have added the screenshot in the PR as well

**Comment by sv-sdeiac** [comment]
Verified as fixed using the latest version of Firefox Preview Nightly 1/28 #20280606.
Devices:
- OnePlus 5T (Android 9);
- Nokia 6 (Android 7.1.1).
