### ISSUE TITLE
Improve inflate performance in HomeFragment.onCreateView()

### ISSUE THREAD

**Issue by emalysz** [mozilla-mobile/fenix#7423]
### Why/User Benefit/User Problem
It is slow to create the HomeFragment (#4665). 
A significant amount of time (952.658 ms) is spent in HomeFragment's onCreateView(). Of this, 56.38% is spent in inflate.

### Acceptance Criteria (how do I know when I’m done?)
-The time it takes to inflate the home fragment has been reduced.

________________________

**Comment by emalysz** [comment]
One potential solution could be using an AsyncLayoutInflater. See Marc's implementation of an AsyncLayoutInflater here for reference: https://github.com/MarcLeclair/fenix/commits/issue_6274_asynclayoutinflater_for_toolbar

**Comment by mcomella** [comment]
We've done some work in a related view/inflation performance issue and this is too general to remain actionable: closing.
