### ISSUE TITLE
Bookmark archival

### ISSUE THREAD

**Issue by cbcaron15** [mozilla-mobile/fenix#7429]
Option to archive a page when adding a bookmark. i.e. send link through archive.org/archive.is/self-hosted upon bookmarking, and bookmark the archived link. Dead links are only going to increase, and exponentially so.

See third-party projects Archiveror, ArchiveBox, and Pinboard for similar, but distinct features.

Archiveror:

> Archive webpages on archive.is, archive.org and more or on your own computer in MHTML format. Automatically archive your bookmarks.

> Archiveror archives webpages online by submitting them to archive.is, archive.org, perma.cc, webcitation.org or locally by saving a copy in MHTML format on your computer. The online archives are publicly available, so you then have a backup that you can refer to in case the original falls prey to link rot.

> It preserves your bookmarks by automatically archiving them in the background. Its icon changes when you visit a bookmark it has archived, clicking on it shows the archive links. Archiving of bookmarks happens when you make a new bookmark and when you open an old bookmark. This can be disabled.

> Archiveror also makes local copies of webpages. It saves one web page in a single MHTML file. Save pages manually by either clicking the button or by pressing Ctrl+Shift+S. The filenames end with the UTC date and time of when the archive was made.

ArchiveBox:

> ArchiveBox takes a list of website URLs you want to archive, and creates a local, static, browsable HTML clone of the content from those websites (it saves HTML, JS, media files, PDFs, images and more).

> You can use it to preserve access to websites you care about by storing them locally offline. ArchiveBox imports lists of URLs, renders the pages in a headless, authenticated, user-scriptable browser, and then archives the content in multiple redundant common formats (HTML, PDF, PNG, WARC) that will last long after the originals disappear off the internet. It automatically extracts assets and media from pages and saves them in easily-accessible folders, with out-of-the-box support for extracting git repositories, audio, video, subtitles, images, PDFs, and more.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-15010)

**Comment by Poopooracoocoo** [comment]
should this be left up to extensions?

**Comment by JNavas2** [comment]
My **[Share2Archive extension](https://play.google.com/store/apps/details?id=com.navasgroup.share2archive&hl=en_US)** for Android does this quickly and easily.

![unnamed (Custom)](https://user-images.githubusercontent.com/14850792/84620885-03c43200-ae8e-11ea-940e-09cacda3bd39.png)

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813603

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
