### ISSUE TITLE
[Bug] Close private tab notification not present even when "Open in Firefox"ing custom tabs 

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#7430]
Related to #7392 and #7405 
## Steps to reproduce
1. Set firefox preview as default browser.
2. Check "Open links in a private tab" option in this menu.
3. Go to the reddit app. 
4. Open any web link url (Assuming that the "open web links in app" reddit setting is on)
5. Click on Open in Firefox Nightly in 3 dot menu
### Expected behavior
Opens private tab in Firefox and the Close private tab notification should appear
### Actual behavior
Opens private tab in Firefox but no  Close private tab notification  appears
### Device information

* Android device: Asus Zenfone Max Pro M1
 * Fenix version:
    Nightly 191230 18:01 (Build #13641809)
    27.0.0, 202f6d4f8

**Comment by sblatz** [comment]
@s-ankur are you still seeing this?

**Comment by s-ankur** [comment]
Yes, as of Nightly 200519 06:00 (Build #21400607)

**Comment by s-ankur** [comment]
Hi, this issue is fixed on Nightly. Closing
