### ISSUE TITLE
Enable `UnusedResources` lint check to decrease APK size

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#7436]
Our `res` dir is 718.9 KB & our `resources.arsc` (the compiled resources) is 2.1 MB: of these 213 resources are marked as "Unused" by lint. Removing these unused resources may save us a non-trivial amount of APK size.

It's easy to enable UnusedResources to prevent further regressions though one challenge we may face is that Strings may be added by string imports that are not yet used.

It's also easy to remove unused resources: run "Analyze" -> "Run Inspection by name" & type in "Unused Resources" in Android Studio. When it completes, click to remove the unused resources.

### Acceptance criteria
- Enable `UnusedResources` lint check
  - N.B.: we need to consider what will happen to String imports. Should we add a blanket, "Keep unused" to them? But then how will we know when they're unused and when we can remove them? Perhaps we should add the blanket and add a follow-up to address later
- Remove all `UnusedResources` or update baseline (so there are no failures) & file a follow-up to do so
  - Consider whether all unused strings should actually be removed

**Comment by mcomella** [comment]
I think this is still a valuable change (not sure if I undid the stale bot correctly).

**Comment by RotBolt** [comment]
Hello @mcomella 
This issue seems to be long pending may I take this issue to work on :) ?
Seems an interesting issue to me

**Comment by mcomella** [comment]
@RotBolt Yes you may work on this – that'd be really helpful for us! Sorry for the late response – I was away from the computer last week.

**Comment by RotBolt** [comment]
Hello @mcomella, 
Thanks for confirming
Just a quick question
[here](https://github.com/mozilla-mobile/fenix/blob/7975309952b317b222c10dd93462537716e2a253/app/lint.xml#L53) I could see currently `UnusedResources` is set `warning`, by enabling do you mean set to `error`? Isn't setting it to `error` kinda too strict?

Let me know WDYT?

**Comment by mcomella** [comment]
> here I could see currently UnusedResources is set warning, by enabling do you mean set to error? Isn't setting it to error kinda too strict?

@RotBolt That's correct: it's currently set to warning and we want it to be set to error. Warnings are only useful if someone looks at them and I've generally found that no one looks at them for enough time to make a significant impact (to be fair, it's tedious and time consuming). I prefer to explicitly fail such that for each issue, when they're implemented, someone is forced to either fix the issue or ignore it (e.g. because it's not worth the time to address).

The general principle here is "fail fast": if we don't fail fast, we may find ourselves in a situation that requires so many changes that is difficult to get out of (e.g. a really large APK with thousands of resources to remove if removing them automatically doesn't work) but if we fail fast, individual developers are forced to categorize the issues as important or not as they happen, hopefully avoiding the difficult situation and being less work in the long run.

---

If we change this to error now, however, we're going to have to have a lot of failures because we haven't been removing unused resources. So you have two options:
- Fix the new "UnusedResources" errors so there are no more failures
- Update the baseline file to ignore the new "UnusedResources" errors and file a follow-up bug to fix them (that someone else can address)

Or you can do some combination of that, e.g. remove the top 10 largest unused resources and put the rest in the baseline.

**Comment by RotBolt** [comment]
Ok fine @mcomella . I will try to fix all issues at first. If it seems impossible then I will switch to removing largest bottlenecks of these resources

**Comment by mcomella** [comment]
Thanks @RotBolt! Assuming the IDE can't just remove the unused resources, I'd guess there are enough of these errors that it will be challenging to fix them all. fwiw, to make the most progress my attack strategy would be:
- Set warnings to errors, add the baseline file, open a PR, and land it. This prevents backsliding 
- Locally, remove the baseline and start fixing errors one-by-one, opening a PR when I'm tired of fixing errors

**Comment by RotBolt** [comment]
@mcomella there seem to be 365 errors due to lint 

![image](https://user-images.githubusercontent.com/24780524/126596874-729efe24-2e11-47fb-b85c-74c0f6012c6e.png)

**Comment by RotBolt** [comment]
@mcomella , so should I add all these 365 errors in `lint-baseline.xml` and then increamenlty fix these errors in subsequent PRs ?

**Comment by mcomella** [comment]
@RotBolt Yep! That's what I'd recommend. :)

**Comment by RotBolt** [comment]
Woah, adding 365 errors would be huge. I would try to file the first errors. While adding those errors to `lint-baseline`, If I think I could fix it easily would fix that too. Nice task for weekends I guess :P

**Comment by mcomella** [comment]
I filed https://github.com/mozilla-mobile/fenix/issues/20634 as a follow-up to remove the suppressions in the lint baseline file.
