### ISSUE TITLE
[Bug] Download Completed notification infinitely spammed after Saving Image 

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#7437]
## Steps to reproduce
Long press on any image to open save image menu
save image
### Expected behavior
Image downloads and notifies at most once
### Actual behavior
Download completed notification repeatedly appears

![2019_12_31_18_3-1577800514772](https://user-images.githubusercontent.com/33252312/71625509-18628580-2be0-11ea-8184-b72e09d8b2e0.gif)

### Device information

* Android device: 
Asus Zenfone
* Fenix version: 
Nightly 191230 18:01 (Build #13641809)
27.0.0, 202f6d4f8
GV: 73.0a1-20191227094418

**Comment by boek** [comment]
@sblatz looks like also images 👍

**Comment by sblatz** [comment]
Closing as dup of #7443
