### ISSUE TITLE
Long press to share link should have the option to send to device

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#7438]
### Why/User Benefit/User Problem
Currently Long press to share link on any webpage opens up the native share sheet. While this is useful, it does not include all the features that the custom firefox share sheet has (#4275), importantly the Send to Device option which is what you normally want to share links for.
### What/Requirements
 Long press to share link should open the custom firefox share sheet.

**Comment by Arnvidr** [comment]
Now that fenix rolled out to more users and this gets noticed, hopefully this will get fixed soon? Maybe add the bug label, as on #13248?

**Comment by da2x** [comment]
This is a bug. Long-pressing and choosing Share should open the same Sahre dialog as Firefox Menu: Share, and the WebShare API does.

**Comment by toupeira** [comment]
@s-ankur @amkcpu only project members can change the labels, but https://github.com/mozilla-mobile/fenix/issues/13248 already has the correct ones from the issue template, so if we reopen that and close this one we're more likely to get some attention :wink:

**Comment by amkcpu** [comment]
Prompted by your comment, I did a little digging and found this issue: #2933. Note that it's also already triaged and an issue in Android Components has been filed to add this functionality: https://github.com/mozilla-mobile/android-components/issues/4614.

Hence, both #7438 as well as #13248 are duplicates and can be closed.

**Comment by toupeira** [comment]
@amkcpu ah that's even better, thanks for digging!

**Comment by s-ankur** [comment]
Closing as duplicate of #2933
