### ISSUE TITLE
[Bug] Downloading file opens a gazillion "Open" prompts that crash the browser

### ISSUE THREAD

**Issue by emilio** [mozilla-mobile/fenix#7443]
## Steps to reproduce

Same as #6656. Now it does work (if you're fast enough...), but see below. 

### Expected behavior

Just one dialog.

### Actual behavior

If you're not fast enough, then eventually a ton of dialogs appear and eventually crash the process.

### Device information

* Android device: Same as in the other issue
* Fenix version: Current nightly.

**Comment by emilio** [comment]
![20191231_184607](https://user-images.githubusercontent.com/1323194/71629478-0bed2580-2bfe-11ea-82eb-7211113293cf.gif)

Video of the issue.

**Comment by emilio** [comment]
(cc @sblatz / @AndiAJ, it'd be good to know if this happens on other devices too)

**Comment by sblatz** [comment]
@emilio does this happen for you with other files? Or just PDFs?

**Comment by emilio** [comment]
I don't know, I'll check. I don't download files all that often :-)

**Comment by emilio** [comment]
Happens also long-tapping on the GIF above and pressing "Save image". So not pdf-specific.

**Comment by sblatz** [comment]
It's happening on download files :) I'm working on it

**Comment by emilio** [comment]
Sweet, thanks @sblatz!

**Comment by sblatz** [comment]
Omg thank you so much for filing this @emilio! I was having a weird out of memory exception in my tests on AC and this is definitely that issue. I was trying to track it down for several days 😅

**Comment by emilio** [comment]
Nice! Happy to help :D

Thanks for all your work in AC / Fenix, it's pretty cool ^.^

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **Nightly Build #20030608 from 1/3** using the following devices:

• Google Pixel 3a (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

► Video
![20200103_092101](https://user-images.githubusercontent.com/51314259/71711829-71623180-2e0b-11ea-9e50-0d33d85a47c8.gif)

@emilio -  Please re-check and if you still encounter this issue, please re-open. ☺️
