### ISSUE TITLE
[Bug] Send to all devices lags, clicking twice during this crashes firefox

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#7447]
## Steps to reproduce
Have firefox account with multiple devices(>3)
Click on share, send to all devices
There is some lag
click on send to all devices again
### Expected behavior
no change 
### Actual behavior
crash
### Device information

* Android device: Asus Zenfone M1
* Fenix version: 
Nightly 191230 18:01 (Build #13641809)
27.0.0, 202f6d4f8
GV: 73.0a1-20191227094418

**Comment by sv-sdeiac** [comment]
Closed as a duplicate of #7343, if you have additional information regarding this issue, please fill them on the ticket #7343, thanks.
