### ISSUE TITLE
[Bug] Report site issue in private mode opens in normal mode

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#7449]
It is quite serious as it leaks the private url into history through the webcompat tab url
## Steps to reproduce
Open a private tab
Report site issue
### Expected behavior
opens webcompat in private mode
### Actual behavior
Opens in normal mode.
### Device information

* Android device:  Asuz Zenfone
* Fenix version: 
Nightly 191230 18:01 (Build #13641809)
27.0.0, 202f6d4f8
GV: 73.0a1-20191227094418

**Comment by kbrosnan** [comment]
@adamopenweb is this a bug for the Fenix team or the webcompat team?

**Comment by adamopenweb** [comment]
Hey, I think this is a Fenix team bug as we didn't implement this AFAIK.

But I also know @wisniewskit is working on replacing the current implementation with better hooks into the browser, similar to on desktop. He might have some insight here.

Lastly, webcompat.com isn't working at the moment for anonymous reports. We're working on getting that back up in the near future.

**Comment by s-ankur** [comment]
Seems to be correctly working right now in Nightly

**Comment by kbrosnan** [comment]
Confirmed.
