### ISSUE TITLE
The Splash animation for Address Bar objects is bugged

### ISSUE THREAD

**Issue by thanuj10** [mozilla-mobile/fenix#7455]
## Steps to reproduce
1. Open Fenix
2. Tap on any object on Address Bar (Eg - Https padlock)

### Expected behavior
The animation should be on the proper surface i.e the same surface as the object and render properly.

### Actual behavior
The splash animation is rendered behind the object creating a weird looking animation.

### Device information

* Android device: Nokia 6.1 Plus
* Fenix version: Latest Fenix Nightly Preview

**Comment by thanuj10** [comment]
https://photos.app.goo.gl/Ne3pzQMPJqKbUj8F8
Adding Video for reference.

**Comment by kbrosnan** [comment]
@thanuj10  Please provide a screenshot or video of what you are describing.

**Comment by ekager** [comment]
Looks like #1648?

**Comment by thanuj10** [comment]
@kbrosnan It's the same issue as @ekager mentioned.

**Comment by ekager** [comment]
Okay closing as dupe of #1648
