### ISSUE TITLE
[Headers] Top header is disconnect from status bar wich is a shame

### ISSUE THREAD

**Issue by Octoton** [mozilla-mobile/fenix#7456]
The old firefox header bar was cleaner because it was one with the status bar.

To get the same visual appeal, the loading bar should be at the bottom and the dark one pixel line at the top of the header bar should be remove.

**Comment by Octoton** [comment]
Old firefox: 
![Screenshot_20200102-193826_Firefox~2](https://user-images.githubusercontent.com/56130419/71685330-48548900-2d98-11ea-81db-f0e56594a7dd.png)

New firefox loading:
![Screenshot_20200102-193841_Firefox_Preview~2](https://user-images.githubusercontent.com/56130419/71685364-5efae000-2d98-11ea-93b2-e410f4aa7408.png)

New firefox dark one pixel line:
![Screenshot_20200102-193938_Firefox_Preview~2](https://user-images.githubusercontent.com/56130419/71685399-7b971800-2d98-11ea-9287-cc92d34cc874.png)

**Comment by sv-sdeiac** [comment]
@pocmo Can you take a view on this issue and let your opinion on it?

**Comment by Dunexus** [comment]
The one pixel line is also visible at the bottom of the screen when using bottom toolbar even if it is less noticeable.

**Comment by brampitoyo** [comment]
Sorry. This is an issue that somehow we’ve overlooked.

When the toolbar is on top:

- The loading bar should appear below the toolbar – same with Fennec
- The one pixel line above the toolbar should not appear

When the toolbar is on the bottom, the current design is already correct.

**Comment by Dunexus** [comment]
@brampitoyo When the toolbar is on the bottom, there is still a one pixel grey line above and under the toolbar.
![onepxlines](https://user-images.githubusercontent.com/13906248/73833347-22445d80-480a-11ea-8286-74d79fe804ff.jpg)
I highlighted the left part of these grey lines in red.
I don't think bottom one is intended.

Also, this might be related to some alignment issues between the toolbar on webpage and homepage (see https://github.com/mozilla-mobile/fenix/issues/8087)

**Comment by sv-sdeiac** [comment]
Verified as fixed using the latest version of Firefox Preview Nightly 2/6 #20370604.

Devices:
- Nokia 6 (Android 7.1.1);
- Samsung Galaxy (Android 9);
- Google Pixel 3 (Android Q).
