### ISSUE TITLE
Some GBoard functions and text highlights are bugged or don't work.

### ISSUE THREAD

**Issue by thanuj10** [mozilla-mobile/fenix#7457]
## Steps to reproduce
> For Cursor Navigation exclusive to Gbaord
1. Open a textfield of Fenix or Current stable Nightly Firefox
2. Type a sample para
3. Make sure to enable the 'Swipe on Keyboard for cursor navigation' feature on Gboard
4. Try swiping on the keyboard now. 

> Text highlight that is native on Android
1. Open a textfield
2. Type a sample para
3. Long press on text to highlight
4. Basic highlight appears
 
### Expected behavior
> Gboard
The cursor moves along with the swipe

> Text Highlight
Text magnification is shown and Firefox needs to properly detect if I am highlighting.

### Actual behavior
> Gbaord
Works sometimes, Sometimes very laggy but most of the times doesn't work at all

> Text Highlight
No Image magnification, The detection of highlighting is poor. Sometimes a long press is need amd sometime a ½ second press is enough to enter highlight mode.
Text input in general is laggy.

### Device information

* Android device: Nokia 6.1 Plus
* Fenix version: Latest Fenix and Firefox

**Comment by Poopooracoocoo** [comment]
#4208

it's also strange that double tapping selects a word on Android. Overall, manipulating is so clunky and slow, it's obvious it isn't native. Chromium doesn't use the native Android textviews iirc either but it feels like it.

**Comment by makotokato** [comment]
> For Cursor Navigation exclusive to Gbaord

This is https://bugzilla.mozilla.org/show_bug.cgi?id=1593683, not #4208 and #7342
