### ISSUE TITLE
[Bug] en.m.wikipedia.org not recognized as PWA

### ISSUE THREAD

**Issue by TitanNano** [mozilla-mobile/fenix#7462]
## Steps to reproduce
1. Navigate to https://en.m.wikipedia.org
2. Open main menu

### Expected behavior
Wikipedia has a web mainifest and is recognized by Fennec to be an installable PWA. I expect Fenix to also let me install this PWA.

### Actual behavior
The Site is not recognized as an PWA and can not be "installed" to the homescreen.

### Device information

* Android device: SONY XPERIA 10
* Android version: 9
* Fenix version: Nightly 191229 18:06 Build #13631807

**Comment by NotWoods** [comment]
Wikipedia's manifest uses a browser display mode, so its not installable as a standalone app. However, we should use the manifest to create the icon.
