### ISSUE TITLE
[Bug] github.com is not recognized as PWA

### ISSUE THREAD

**Issue by TitanNano** [mozilla-mobile/fenix#7463]
## Steps to reproduce
1. Navigate to https://github.com
2. Open main menu

### Expected behavior
GitHub has a web manifest and is recognized by Fennec to be an installable PWA. I expect Fenix to also let me install this PWA.
### Actual behavior
The Site is not recognized as an PWA and can not be "installed" to the homescreen.

### Device information

* Android device: SONY XPERRIA 10
* Android version: 9
* Fenix version: 191229 18:01 Build #13631807

**Comment by sv-sdeiac** [comment]
Closing as a duplicate of #7462
