### ISSUE TITLE
BackgroundServices constructor inits passwordStorage, which touches disk during cold startup (7.76ms perfTest)

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#7464]
This might be related to:
- https://github.com/mozilla-mobile/fenix/issues/5487 (I'm not sure what needs to be done for this issue)
- #6730

---

There's a StrictMode violation during startup:

```
12-31 14:51:11.507 D/StrictMode(13806):         at android.content.ContextWrapper.getFilesDir(ContextWrapper.java:243)
12-31 14:51:11.507 D/StrictMode(13806):         at org.mozilla.fenix.components.Core$passwordsStorage$2.invoke(Core.kt:188)
12-31 14:51:11.507 D/StrictMode(13806):         at org.mozilla.fenix.components.Core$passwordsStorage$2.invoke(Core.kt:56)
12-31 14:51:11.507 D/StrictMode(13806):         at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
12-31 14:51:11.507 D/StrictMode(13806):         at org.mozilla.fenix.components.Core.getPasswordsStorage(Unknown Source:8)
12-31 14:51:11.507 D/StrictMode(13806):         at org.mozilla.fenix.components.Components$backgroundServices$2.invoke(Components.kt:23)
12-31 14:51:11.507 D/StrictMode(13806):         at org.mozilla.fenix.components.Components$backgroundServices$2.invoke(Components.kt:16)
12-31 14:51:11.507 D/StrictMode(13806):         at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
12-31 14:51:11.507 D/StrictMode(13806):         at org.mozilla.fenix.components.Components.getBackgroundServices(Unknown Source:7)
```

where `BackgroundServices` is getting initialized, causing one of the initializers arguments, `passwordStorage` to get initialized, which touches the disk to get `context.filesDir`:

https://github.com/mozilla-mobile/fenix/blob/42d6915699a72f558b59f5745acbb6dce444bc15/app/src/main/java/org/mozilla/fenix/components/Core.kt#L184-L190

We should see if we can avoid call `context.filesDir`: e.g. can `passwordsStorage` be delayed further (e.g. pass in a getter func instead of the actual reference) or `context.filesDir` be delayed further (e.g. it seems to be setting a dbPath: can that be delayed until later?).

**Priority recommendation:** this takes 7.76ms on my Pixel 2 which isn't too significant: I suggest lower priority.

**Comment by jonalmeida** [comment]
> #5487 (I'm not sure what needs to be done for this issue)

For this one, there are observers like the Telemetry ones that live in the same class and therefore need to made testable. If we did these outside of that, we can make the BackgroundServices.kt (similar to other component classes) only perform initialization of those components.

I'll copy this comment to that issue as well.

**Comment by mcomella** [comment]
Closing: we're addressing startup holistically.
