### ISSUE TITLE
Improve performance of TransitionInflater.inflateTransition (12.02ms perfTest)

### ISSUE THREAD

**Issue by emalysz** [mozilla-mobile/fenix#7466]
It is slow to create the HomeFragment (#4665).`TransitionInflater.inflateTransition` takes up 7.21% of `FragmentManager.moveToState` which creates the HomeFragment.

We should see what we can do to improve performance, if possible. 

### Impact
Impact:
- perfTest: 12.02ms

### Questions
- What does the transition do? Is it still used?
- Can we inflate it after startup? Inflate it on a background thread?

**Comment by mcomella** [comment]
I think whatever animation is happening here may be obscured by the closing animation of the BrowserFragment because it's an "enter" transition and presumably is shown when opening the HomeFragment (and I don't think we transition between many other fragments).

**Comment by mcomella** [comment]
Reach out to ekager when doing this bug: they may know what the animation is for and if it's necessary to inflate on startup.

**Comment by jimporter** [comment]
@ekager Do you know what this animation is for? Any thoughts on what we could to to improve things here?

**Comment by mcomella** [comment]
Triage: I want to close this because it doesn't seem largely impactful in the short term. However, sblatz is rejiggering the animations currently so we should ask if the `sharedElementEnterTransition`s are no longer used and if not, remove them. If so, close the issue and do nothing.

**Comment by sblatz** [comment]
While I'm working on animations, we do currently use this to animate the browser toolbar on the home screen and search screen (both to and from). Modifying this animation is not high on my priority list given my other tasks before code freeze, but is something we can look at sooner if we need this to improve performance.

**Comment by mcomella** [comment]
I don't think it's significant enough. I also noticed this no longer occurs on the startup to homescreen path but may affect app link (it's in BrowserFragment & SearchFragment) so this is hard to measure locally. I'm going to mark unimportant for GA.

**Comment by mcomella** [comment]
I mean I'll close it and we can reopen if we find this becomes a significant issue to fix.
