### ISSUE TITLE
[Bug]After the "@" character on the registration page, the characters are written in the wrong place

### ISSUE THREAD

**Issue by sv-sdeiac** [mozilla-mobile/fenix#7479]
## Steps to reproduce
1. Open "settings" from the 3dot menu;
2. Tap on "Turn on Sync" button and select "use email instead";
3. Start to write an email than write the "@" character;
4. After the "@" start to write the main of the email;

### Expected behavior
The email is written without any issues.

### Actual behavior
After the first character from the "@", the other characters are written behind the first one.

### Device information

* Android device: LG G7 fit (Android 8.1);
* Fenix version: Firefox Preview Nightly 1/3 @ 6:07 AM;
* I can reproduce this issue also with the Reference browser build 1.0.2001 #20021205 GV 73.0a1.
* I can't reproduce the issue using the Firefox Preview RC build 3.0.1
* Can't reproduce the problem using: Nokia 6 (Android 7.1.1), Motorola Moto G6 (Android 8) and Google Pixel (Android Q).
* 
![20200103_113237](https://user-images.githubusercontent.com/40264165/71716342-0ae60f00-2e1d-11ea-80b2-cb6ccb13be3c.gif)

**Comment by sv-sdeiac** [comment]
This issue is still reproducible using the latest version of Firefox Preview Nightly 200204 2/4.
Devices: LG g7 fit (Android 8.1)

**Comment by fluffyemily** [comment]
This issue should be fixed when https://bugzilla.mozilla.org/show_bug.cgi?id=1596920 lands

**Comment by sflorean** [comment]
Verified as fixed on Nightly 12/16 with LG G7 (Android 8.1).
