### ISSUE TITLE
[Bug] Scroll position is incorrect when opening links which redirect to URLs with fragments in the background

### ISSUE THREAD

**Issue by aroskuski** [mozilla-mobile/fenix#7492]
## Steps to reproduce
1. Navigate to a page that contains a link that will redirect to a URL that contains a fragment
    * For example https://www.resetera.com/threads/active-staff-roster.7164/post-1191462 which will redirect to https://www.resetera.com/threads/active-staff-roster.7164/#post-1191462 when navigated to.  You could generate whatever examples you want with a link shortener, though.
2. Long press the link and select "Open link in new tab"
3. Wait long enough for the tab to finish loading in the background.  The issue does not seem to occur the tab is in the foreground when it finishes loading.
4. Switch to the newly opened tab
### Expected behavior
The new tab is correctly scrolled to the location indicated by the URL fragment.
### Actual behavior
The new tab is scrolled to an incorrect location.  Seemingly always somewhere well below where it should be scrolled to.
### Device information

* Android device: Google Pixel 3
* Fenix version: Nightly 200104 18:20 (Build \#20041826)

Edited to replace link with one that should demonstrate the issue better.

**Comment by aroskuski** [comment]
Okay, so for some reason even opening the non-redirect version of the example link from this GitHub issue seems to reproduce the behavior.  Not sure if that means that a redirect isn't necessary or if GitHub is just messing with the link.  This is the first time I've managed to reproduce it without a redirect involved, so I'm kinda leaning towards the latter, but it's also possible that the conditions that triggered this bug are just more complicated than they initially appeared.

**Comment by johnny88** [comment]
I am able to reproduce this by going to [hackernews](https://news.ycombinator.com/) and clicking on any link.

**Comment by aroskuski** [comment]
So, recently I've tried attaching a debugger to see what's happening, but with limited success, as I haven't really been able to figure out what's happening in the native code.  What I have been able to determine is that the GeckoSession object doesn't seem to ever be told what its dimensions should be until the first time the tab becomes active, which seems potentially significant, but I'm definitely a bit out of my depth with this codebase.

**Comment by aroskuski** [comment]
This issue is still reproducible on the latest Nightly:

Nightly 210210 17:03 (Build #2015792523)
AC: 73.0.20210209203620, fbf61006d
GV: 87.0a1-20210209092956
AS: 69.0.0

If I have some free time in the next day or two, I'll try to clean up the bug description a bit to better reflect what I think the actual issue is after having to put up with it for a while.

**Comment by aroskuski** [comment]
Actually, reading the issue the bot linked a bit closer, it sounds like it would probably be better to resubmit this issue with the new template, so I'll try to do that, and close this one once I'm done with that.

**Comment by aroskuski** [comment]
After searching, looks like someone else filed this issue recently as #17404, so I guess that bug will probably do.
