### ISSUE TITLE
Remove menu presenter

### ISSUE THREAD

**Issue by rocketsroger** [mozilla-mobile/fenix#7497]
### Why/User Benefit/User Problem
Currently the menu is built every time the user click on the menu button.  Therefore, invalidating the menu using menu presenter is not needed anymore.

### What/Requirements
Remove menu presenter

### Acceptance Criteria (how do I know when I’m done?)
No change in menu behavior after removing menu presenter

**Comment by NotWoods** [comment]
The presenter is still needed for changes while the menu is open (ie stop/refresh) and for displaying changes on the menu button itself (ie highlights)

**Comment by rocketsroger** [comment]
> The presenter is still needed for changes while the menu is open (ie stop/refresh) and for displaying changes on the menu button itself (ie highlights)

I see.  I've close the PR and will update this issue and investigate how we can handle this better.  You're right that removing the menu presenter is not the way to go.

**Comment by rocketsroger** [comment]
With the fix in https://github.com/mozilla-mobile/android-components/issues/5661, there's no performance gain removing menu presenter.  Closing.
