### ISSUE TITLE
PWA: in private browsing

### ISSUE THREAD

**Issue by 0xTyagi** [mozilla-mobile/fenix#7499]
### Why/User Benefit/User Problem
if user installed the PWA from private tab then PWA must not store any history in browser and remove every data related to this PWA when user quit PWA.
i am calling this PWA as 'Private PWA'
### What/Requirements
A separate 'private PWA' is installed for private browsing if user want to do this. 
### Acceptance Criteria (how do I know when I’m done?)
History/cache doesn't stored in browser if private PWA is accessed.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-15057)

**Comment by 0xTyagi** [comment]
This may be temporarily fix if fenix provide a way to clear all data for a particular site as firefox desktop does.

**Comment by 0xTyagi** [comment]
any update regarding this

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807434

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
