### ISSUE TITLE
[Bug] ETP CFR breaks with a top toolbar

### ISSUE THREAD

**Issue by apbitner** [mozilla-mobile/fenix#7501]
## Steps to reproduce

- Fresh install of Nightly
- Go to a website, such as cnn.com

### Expected behavior

- ETP tooltip (CFR) shows beneath the address bar with the arrow pointing to the shield icon

### Actual behavior

- CFR shows on top of the toolbar and the arrow is not pointing toward the shield

![image](https://user-images.githubusercontent.com/22176302/71828445-f8134a80-3067-11ea-80e1-6e4544f4ed4d.png)

### Device information

* Android device: 10
* Fenix version: Nightly 200105 18:00

**Comment by Amejia481** [comment]
cc @ekager

**Comment by ekager** [comment]
Dupe of #7181
