### ISSUE TITLE
Validate open + close tabs tray performance

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#7512]
We're moving the tabs to a separate TabsTray: #7071. As part of implementing this new feature, we should:
1. Ensure there are no performance issues in the feature by testing and meeting the release criteria (N.B.: criteria to be set by @ecsmyth)
2. Ensure there are no performance regressions to cold startup to homescreen (where the tabs are currently located). N.B.: our cold startup test runs without any open tabs so we may see minimal impact to the results.

I'm happy to work with whoever is working on this bug to determine runtimes of various parts of the code for 1) and run our cold startup tests locally (unfortunately, it's a little of a pain right now) for 2.

---

### Adapted release criteria by ecsmyth
I extrapolated this from RC defined on a previous design by ecsmyth on Slack. Italic text written by ecsmyth, non-italic by mcomella:
- [x] Opening tabs tray: _Target 250ms from input to UI rendered. RC recommended because of previously observed timing variance depending on number of open tabs and potential for this experiance to be subject to perf regressions_
  - 2x: entry points from browser and home screen are different
- [x] Closing tabs tray (with back): _I'm a little unsure of this one. I think that it may be needed since I think the top sites and/or collections could change requiring reload. If so, it should have a same/similar RC as_ opening tabs tray
- [ ] Opening private tabs: ~~_Needs same/similar RC as opening tabs tray_~~ 100ms. This is no longer a screen transition but a swipe drag so I changed it
- [ ] Opening a new tab to homescreen: 250ms because it's a new screen & defined by "Open new tab" RC
- [ ] Tab switching: 250ms, as defined by "Tab Switch" release criteria
- [x] We have reason to believe tab closing is slow with a large number of open tabs: https://github.com/mozilla-mobile/fenix/issues/11352

Checklist is what I've investigated so far.

Though the tabs tray is now an overlay, when opened it essentially fills the screen, so I'm comfortable using the "opening a screen" perf RC for this feature rather than "opening a context menu".

**Comment by mcomella** [comment]
The tabs tray is happening again in https://github.com/mozilla-mobile/fenix/issues/1063: let's ensure 1) using it is performant and 2) analyze the impact of removing tabs from the homescreen.

**Comment by mcomella** [comment]
From ecsmyth, off the cuff:

> release criteria will need to be updated. AIUI the expectation should be that the tab tray view takes < 250ms to render

**Comment by mcomella** [comment]
@ecsmyth Can you identify release criteria for the tabs tray?

**Comment by jeanygong** [comment]
Jean to follow up with @ecsmyth on release criteria.

**Comment by liuche** [comment]
@mcomella will take this back to the perf team due to release timeline pressuers.

**Comment by mcomella** [comment]
> @mcomella will take this back to the perf team due to release timeline pressuers.

To be explicit, we're going to look into this.

**Comment by mcomella** [comment]
I added PRs with measurements for opening the tabs tray: https://github.com/mozilla-mobile/fenix/pull/11398 & https://github.com/mozilla-mobile/android-components/pull/7314

Unfortunately, they do not include the animation timings but these can be discovered statically: they are defined in the android framework.

**Comment by mcomella** [comment]
Preliminary results for tabs opening – patches are not yet reviewed. The variables we have are:
- Device: Pixel 2 vs. Galaxy S5
- number of tabs open: 1 vs 8
- Screen: open tabs tray on homescreen vs. browser
- When pressed: first click in process vs. subsequent clicks
- Which measurement: tabs tray initially appearing, tabs finish loading async

Some data will be omitted: I now realize how ridiculous it is to try to measure all of these combinations and I should have just picked one. :) I'll list what data I have.

### Time to tabs tray appearing (no tabs yet)
| Device | Tab Count | Screen | Click | Duration |
|---|---|---|---|---|
| P2 | 1 | home | first | 111ms |
| P2 | 8 | home | first | 100ms |
| P2 | 8 | home | subsequent | 45.8ms |
| P2 | 1 | browser | first | 83.667ms |
| GS5 | 1 | home | first | 153ms |
| GS5 | 8 | home | first | 144.667ms |
| GS5 | 8 | home | subsequent | 109.5ms |

**All of our times meet the RC of 250ms.** However:
- we still don't have the tabs yet
- this timing excludes the timing of the animation, whose duration I was unable to find in the time I spent on it. Tabs typically appear after the animation completes, however, so we can probably just use tab timing

We may note:
- the 1 browser run appears marginally faster than the homescreen on the P2 and that holds true below.
- Adding tabs does not appear to significantly impact this measurement

### Time to tabs appearing (final state)
| Device | Tab Count | Screen | Click | Duration |
|---|---|---|---|---|
| P2 | 1 | home | first | 211ms |
| P2 | 8 | home | first | 280.67ms |
| P2 | 8 | home | subsequent | 198.9ms |
| P2 | 1 | browser | first | 158ms |
| GS5 | 1 | home | first | 359.333ms |
| GS5 | 8 | home | first | 462ms |
| GS5 | 8 | home | subsequent | 441.2ms |

**Only the P2 meets our RC with 1 tab open.** The P2 fits in the wiggle room (of 300ms) of 8 tabs but the GS5 is 100+ ms outside of our RC.

We may note:
- Having 8 tabs vs. 1 tab has a non-trivial impact on performance (103ms on G5, 69ms on P2)

**Comment by mcomella** [comment]
Speculation: perhaps the tabs take so long to appear because they're blocking on getting the tab previews before loading the tabs. If not, I'd expect loading tabs to be fast because it's just a bunch of strings.

If so, this is a problem: it'll get very unperformant with a large number of open tabs. We should load the tabs and asynchronously fetch the tab when they're needed.

**Comment by mcomella** [comment]
Opened a PR for results below: https://github.com/mozilla-mobile/fenix/pull/11494/

### Preliminary results for Closing tabs tray (with back), first click (3 runs), 11 tabs
| device | Run count| Measurement |
| --- | --- |
| P2 | 3 | 10.67ms |
| GS5 | 5  | 65.6ms |

These measurements include animation time. It appears the tray animates away irrespective of what's inside it so I'm not concerned about performance here.

**Comment by mcomella** [comment]
We have higher priorities than investigating the remaining tabs tray RC (we don't believe there are any problems) so I'm going to close this and open a follow-up for the remaining RC.

**Comment by mcomella** [comment]
I filed https://github.com/mozilla-mobile/fenix/issues/11662 to follow-up: closing this.
