### ISSUE TITLE
[Bug] unable to close popup

### ISSUE THREAD

**Issue by leela52452** [mozilla-mobile/fenix#7514]
## Steps to reproduce
visit https://www.mercuriocalama.cl/impresa/2016/12/08/full/cuerpo-principal/21/
opens a popup
### Expected behavior
able to close popup
### Actual behavior
unable to close popup
### Device information

* Android device: ls-4001
* Fenix version: 3.0 [ Build #13431955 ]

screenshot:
![Screenshot_2020-01-07-08-11-34](https://user-images.githubusercontent.com/52065244/71864814-dada8c80-30f8-11ea-99b3-f7a1eec7f7e4.png)

**Comment by s-ankur** [comment]
Seems to be a problem with the website itself (or maybe even  intentional design). Works the same way on both fennec and chrome

**Comment by kbrosnan** [comment]
Agreed. This is intentional design by the website owner.
