### ISSUE TITLE
[Bug] Back button does not work when fenix is launched using search widget, clicking makes browser completely unresponsive

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#7519]
## Steps to reproduce
Place fenix search widget in device home navigation
launch fenix using this
click on the back button

![WhatsApp Image 2020-01-07 at 4 24 01 PM](https://user-images.githubusercontent.com/33252312/71890380-27aa7b80-316a-11ea-9584-77f13135a8a2.jpeg)
### Expected behavior
I'm not sure whether it should just close firefox or open the tab overview.
### Actual behavior
Does nothing. Browser is unresponsive afterwards
### Device information

* Android device: Asus Zenfone 1
* Fenix version: 

Nightly 200106 18:01 (Build #20061807)
27.0.0, 402cef2c5
GV: 73.0a1-20200105094728

**Comment by kbrosnan** [comment]
This seems poor for the primary entry point from the search widget.

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **Nightly Build #20100616 from 01/10** using the following devices:
• Google Pixel 3a (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

► Video
![20200110_144028](https://user-images.githubusercontent.com/51314259/72153756-700aa900-33b7-11ea-8000-547f7ad84555.gif)
