### ISSUE TITLE
[Bug] Tabs opened during onboarding tour are "hidden", activating reader mode crashes firefox

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#7521]
## Steps to reproduce
Follow steps in #7503 , but wait for the page to be fully loaded
Firefox will not crash
Press the tabs/home button
![2020_01_07_21_3-1578412941759](https://user-images.githubusercontent.com/33252312/71909564-355f0180-3168-11ea-8f99-9967cd19c8b1.gif)
### Expected behavior
?
### Actual behavior
onboarding page opens but instead of displaying one tab in the bottom bar it shows the plus icon. the tab isnt actually gone and can be seen if you leave onboarding. moreover if you press reading mode on the tab(before pressing home) the browser crashes

### Device information

* Android device: Asus zenfone
* Fenix version: 
Nightly 200106 18:01 (Build #20061807)

**Comment by kbrosnan** [comment]
Could be a dupe of #7503

**Comment by s-ankur** [comment]
Closing as it seems to be fixed
