### ISSUE TITLE
[Telemetry] Top Sites

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/fenix#7525]
#### Description & Product Manager / Data Scientist User Story
- As a product owner, I want to know how often users interact with top sites, so I can better prioritize related features and bugs based on user need. 

#### What probes (suggested, if applicable)
- User pins a site
- User removes a site
- User opens a top site in regular mode
- User opens a top site in private mode

### Acceptance Criteria (Added by PM)
- Event pings can be queried via re:dash
- We are sending telemetry events for the actions listed in the requirements
- We have documented the telemetry
- We have asked a data steward to [review](https://github.com/mozilla/data-review/blob/master/request.md) the telemetry
- NOT an AC: Data science to create dashboard or further graphs (this will be a separate issue, this issue is only about hooking up the events described and that they can be queried in re-dash)

**Comment by gabrielluong** [comment]
Parent: #6190

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly Build #20290608 from 1/29`** using a OnePlus A3 (Android 6.0.1)

✔️ User pins a site - Ping **59093c80-d8dc-4851-9f23-c265a4a9e620**
✔️ User opens a top site in regular mode - Ping **c4cf7ce9-d26d-4d3f-b96c-04c5be2b13f1**
✔️ User opens a top site in private mode - Ping **e54d1898-c4b2-4c72-b7bc-c6447c0b526e**
✔️ User removes a site - Ping **009c2704-9de3-4562-b80c-4696890cf112**

[Logcat](https://github.com/mozilla-mobile/fenix/files/4128385/topsites.txt)
[Glean dashboard](https://debug-ping-preview.firebaseapp.com/pings/aj-t290100)
