### ISSUE TITLE
Investigate useage of Shared Pref on cold start

### ISSUE THREAD

**Issue by MarcLeclair** [mozilla-mobile/fenix#7530]
Shared Pref could preferably be done on an IO Dispatcher instead of on the MT. Have to investigate whether or not its worthwhile / low-risk to move all of those calls (if any)

### Acceptance Criteria (how do I know when I’m done?)

Find all the useage of SharedPref on cold start.

**Comment by MarcLeclair** [comment]
This issue can be unassigned I think. The only thing now is that with experiments staying, the number above might change a tiny bit 😄

**Comment by mcomella** [comment]
Closing: we're addressing startup holistically.
