### ISSUE TITLE
[Bug] light theme back and home buttons are invisible when overlays are shown

### ISSUE THREAD

**Issue by kbrosnan** [mozilla-mobile/fenix#7532]
## Steps to reproduce

* Open a secure website or one that triggers tracking protection
* tap the lock icon or the tracking protection icon 

### Expected behavior

* back button and home button are visible

### Actual behavior

* back button and home button are invisible

### Device information

* Android device: Pixel 3 w/ Android 10
* Fenix version: Nightly

**Comment by kbrosnan** [comment]
### Light theme
![Screenshot_20200107-203257](https://user-images.githubusercontent.com/250273/71950839-a238c280-318d-11ea-97b4-71ffdce363dc.png)

### Dark theme
![Screenshot_20200107-203326](https://user-images.githubusercontent.com/250273/71950867-b7155600-318d-11ea-88f3-743f12b11573.png)

**Comment by mcarare** [comment]
I cannot reproduce this on 2 other devices with Android 9.

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly Build 200716 from 7/16`** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)

►Video
![20200716-100156](https://user-images.githubusercontent.com/51314259/87638240-19a66a80-c74c-11ea-9fbf-c9b1ebade783.gif)
