### ISSUE TITLE
Clicking Back on Browser Should Not Open Search

### ISSUE THREAD

**Issue by ekager** [mozilla-mobile/fenix#754]
## Steps to reproduce
1. Search something to open webpage
2. Click back

### Expected behavior
Go to home screen

### Actual behavior
Go back to search

### Device information

* Android device: pixel2 
* Fenix version: nightly

@sblatz when you moved this navigation logic into HomeActivity using the global browser action (https://github.com/mozilla-mobile/fenix/commit/e57aa67d606ac1886c71b2b275da9fbc6fc960be), we lost the navigation logic from action_searchFragment_to_browserFragment, where we popped the SearchFragment on navigate. 
https://github.com/mozilla-mobile/fenix/blob/1b1a9e0d115f13599d44a40eb460bc3ac7c12721/app/src/main/res/navigation/nav_graph.xml#L36-L39

Is there any way we can use the correct directions here and still maintain the private mode logic the way you added? Or maybe we have to repeat some logic for SearchFragment specific navigating?

**Comment by bsurd** [comment]
Verified on:
 - 1.0.1910 (Build #10642115)

 Devices:
 - Nokia 6 (Android 7.1.1)
 - HTC Desire 820 (Android 6.0.1)
