### ISSUE TITLE
[Bug]Backgrounded custom tab is lost when opening Fenix

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#7540]
## Prerequisites
Gmail, Reddit, Twitter, Cnet app's are opened.
Fenix is set as the default browser app.

## Steps to reproduce
1. Open a custom tab using Reddit.
2. Exit to the home screen and open Fenix.
3. Open a custom tab using Gmail
4. Exit to the home screen and open Fenix
5. Open a custom tab using Cnet
6. Exit to the home screen and open Fenix
7. Open a custom tab using Twitter
8. Exit to the home screen and open Fenix

### Expected behavior
The custom tabs shouldn't be lost. Fenix browsing session should be opened separately, not in each of the native apps'.

### Actual behavior
The custom tab is lost and a new Fenix browsing session seems to be opened in the native app's.

### Device information

* Android device: 
• Google Pixel 3a (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

* Fenix version:  Nightly Build #20080616 from 01/08 

### Notes
❗  **Not reproducible on yesterday's Nightly Build #20070606 from 1/7**
Reproducible with Custom tabs in Private Mode.

► Video
![20200108_143953](https://user-images.githubusercontent.com/51314259/71979087-87199180-3225-11ea-8620-da06bdd4656c.gif)

**Comment by sv-ohorvath** [comment]
Also reproducing on Beta 4.0-beta 1

**Comment by liuche** [comment]
We should get this fixed by end of week to get uplifted to Beta Migration in a subsequent build, but we won't block 4.0 release/first beta migration build on this.

**Comment by liuche** [comment]
@Baron-Severin if you could take a look

**Comment by liuche** [comment]
Actually, jon mentioned this might be a dupe of #5041, so QA, could you verify and see if it is already fixed?

**Comment by jonalmeida** [comment]
> Actually, jon mentioned this might be a dupe of #5041, so QA, could you verify and see if it is already fixed?

Sorry for the confusion, it's definitely *not* fixed according to that bug, but it's just duplicate issue so I mentioned it to avoid duplicate tracking. Feel free to close either one. #5041 has some more [technical details and potential fixes](https://github.com/mozilla-mobile/fenix/issues/5041#issuecomment-526671424) in r-b that Fenix might be able to use.

**Comment by Baron-Severin** [comment]
@liuche @jonalmeida I believe this is actually a different (although quite possibly related) bug.  There are two broken flows in the above report/gif, and neither is quite the same as #5041.

--- 

Open third party app -> open custom tab -> tap home button -> tap Fenix shortcut
EXPECTED: opens Fenix normal session
ACTUAL: opens to third party custom tab (or blank home, when combined with the below flow)

Reproducible for me on Release v3.2.1, but **not** reproducible on Nightly 200222 18:21 (Build #20531827) 

--- 

Open third party app -> open custom tab -> tap home button -> open recently used list -> select third party app
EXPECTED: custom tab
ACTUAL: appears as third party app on recently used list, but shows Fenix home

Not reproducible for me on Release 3.2.1 or Nightly 200222 18:21 (Build #20531827)

**Comment by AndiAJ** [comment]
Hi, **verified as fixed**,  on the latest **`Nightly Build #20560606 from 02/25`** using the following devices:

• Google Pixel 3a (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• OnePlus A3 (Android 6.0.1)

► Video
![20200225-160912](https://user-images.githubusercontent.com/51314259/75256282-e6d6f680-57eb-11ea-9ab8-db160e91995f.gif)
