### ISSUE TITLE
Pin site from home

### ISSUE THREAD

**Issue by topotropic** [mozilla-mobile/fenix#7543]
### Why/User Benefit/User Problem
I want to be able to pin sites from home so that I can quickly add a site. 
This also helps discoverability of the feature.

### What/Requirements
- plus icon on home
- when people tap on it they can enter a URL (same UI as when people create a new collection and choose a name)
- when site is added, show a "Added to Firefox home" snackbar 
- display placeholder for favicon on home and use (part of) URL as title
- once people visit the site, favicon and title are fetched

https://app.goabstract.com/share/f9ae2c95-4a95-4b0e-917c-d87b9854a600?mode=design&sha=2fac94ac7fd2676633043e1967dc696c5071a8da

**Comment by topotropic** [comment]
@vesta0 In the current implementation, we just offer the option to add a site to Firefox home from the home menu. This would help discoverability of the feature. Can you please prioritize it?  Thanks!

**Comment by Baron-Severin** [comment]
Little work has been done on this.  Some early investigation into the problem can be found at https://github.com/mozilla-mobile/fenix/pull/9288/files, maybe that will help whoever follows up here.

**Comment by mcarare** [comment]
@topotropic Does UX feel strongly about using the same UI as when creating a new collection? In that use case it makes sense, cause you can have the list of opened tabs in that empty space above, but in this case it will always be empty.
Can we try using a dialog similar to "add to home screen "one?https://mozilla.invisionapp.com/share/M4SBYCLJPQG#/screens/381294676_Add_To_Home_Screen_Dialog

**Comment by topotropic** [comment]
> @topotropic Does UX feel strongly about using the same UI as when creating a new collection? In that use case it makes sense, cause you can have the list of opened tabs in that empty space above, but in this case it will always be empty.
> Can we try using a dialog similar to "add to home screen "one?https://mozilla.invisionapp.com/share/M4SBYCLJPQG#/screens/381294676_Add_To_Home_Screen_Dialog

Yes, sounds good to me. Thanks for the feedback!

**Comment by mcarare** [comment]
Note: As Top Sites are currently implemented, the updating of the top site icon is not working as expected. This issue should be handled separately from this one.

**Comment by liuche** [comment]
Could you give a quick update here? I'm a little confused with which issue should be handling the "+" on the home screen, and what this issue is covering that is different (since it is moved from the Planned to Done column).

**Comment by mcarare** [comment]
@liuche The adding a top site part is covered in this issue, but the current implementation of top sites list does not allow them to update the favicon after they have been added.
