### ISSUE TITLE
Redirected page not shown in history

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#7544]
## Steps to reproduce
open facebook.com (or any site that redirects)
redirected to m.facebook.com
### Expected behavior
m.facebook.com shows up in history
this is fennec behaviour.
### Actual behavior
facebook.com in history
### Device information

* Android device: Asus Zenfone M1
* Fenix version: 
Nightly 200107 18:01 (Build #20071807)
27.0.0, 707874f68
GV: 73.0a1-20200106092427

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-15089)

**Comment by ekager** [comment]
This is likely because we are excluding[`REDIRECT_PERMANENT` when we fetch history results. ](https://github.com/mozilla-mobile/fenix/blob/master/app/src/main/java/org/mozilla/fenix/components/history/PagedHistoryProvider.kt#L45)

**Comment by Rodze** [comment]
Is this the same bug that causes pages browsed from Google search not to appear in history?

Just search for anything, click any search result, wait for the new site to load and check history. The news site is not there.

**Comment by s-ankur** [comment]
@Rodze correct

**Comment by Mugurell** [comment]
An interesting point was raised in review: If we are to also show redirect type urls the history might seem polluted with the entire chain of addresses.

Looking on Fennec, after https://bugzilla.mozilla.org/show_bug.cgi?id=949104 it waited until the redirects are finished and only then save the destination url.

GV and desktop don't behave like this, they make to record every visit in the chain.
For example on desktop accessing `m.youtube.com` gets to show in history `m.youtube.com` and then `youtube.com/?app=desktop`.

Asked on the GV channel, maybe there will be a platform change to only inform about the destination url, change that would ensure the same behavior on both mobile and desktop.

**Comment by Mugurell** [comment]
Agi helped with filing a ticket for the above - https://bugzilla.mozilla.org/show_bug.cgi?id=1670279

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1810167

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
