### ISSUE TITLE
Open local html files in Fenix

### ISSUE THREAD

**Issue by liuche** [mozilla-mobile/fenix#7546]
### Why/User Benefit/User Problem
Users might want to open html files on Fenix in the mobile browser.

### What/Requirements
- Handle the intent filters for filetypes
- Can talk to @snorp for any questions about Gecko

### Acceptance Criteria (how do I know when I’m done?)
- [ ] can open a local html file without "unknown protocol error"

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-15091)

**Comment by Dunexus** [comment]
Does this mean https://github.com/mozilla-mobile/fenix/issues/4049 isn't won't fix anymore ? 😃

**Comment by buttercookie42** [comment]
Hooray indeed, although sadly the direction Google has been moving in (apps should only use content://-URIs when launching other apps, meaning for us that you [cannot open any of the other local resources](https://issuetracker.google.com/issues/144182682) possibly referenced by the HTML file pointed to by the received Intent, and now the deprecation of conventional file system access in Android 10 on top) is still endangering the long-term viability of being able to properly access local HTML files.

**Comment by rbrule** [comment]
Browsing local files and opening HTML files works on my machine, with a small twist.

Write `file:///storage/emulated/0/` on your address bar and notice the `///`. If you don't write the `///` your address bar will display it for you but it will show an error, even if you refresh the page. So make sure to have the `///` on the first try, or else open a new tab.

Furthermore, once you have an HTML file opened, if you add it to your home screen, it won't be able to open it.

I use the lastest standard Firefox Preview from the Play Store on a Pixel 2 with Android 10.

Can anyone else confirm this behaviour on their device?

**Comment by AgentOak** [comment]
@rbrule Yes thank you! That URL works for me on the current stable 79.0.5 release (on Android 9). You just saved me from a very boring train ride with nothing to read. As a usability tip, after visiting `file:///storage/emulated/0/` add it to the top sites so you can access it quickly and don't have to type the URL. It will show up as "Index of..." and icon only showing the letter "S".

I'm using this workaround for now, even though it is inconvenient that I cannot use my usual file manager app to browse.
There are a lot of UX issues as well, e.g. the lock icon showing insecure connection and the file list clearly not being intended for touch use.

**Comment by richardp345** [comment]
I've read through the associated bug reports and the upstream issues filed with Google and understand the difficulty.  However, although it will fail to properly load local HTML files with local child content using the content:// scheme, Chrome still shows up as a viewer on Android for local HTML files and if the file has no child content it will load just fine.  Since FF 80 on Android, FF doesn't even show up as a viewer.  The content scheme was supported before, following https://bugzilla.mozilla.org/show_bug.cgi?id=1406903.  Could we please have what we had before?

**Comment by rolfausohnder** [comment]
> 
> 
> I've read through the associated bug reports and the upstream issues filed with Google and understand the difficulty. However, although it will fail to properly load local HTML files with local child content using the content:// scheme, Chrome still shows up as a viewer on Android for local HTML files and if the file has no child content it will load just fine. Since FF 80 on Android, FF doesn't even show up as a viewer. The content scheme was supported before, following https://bugzilla.mozilla.org/show_bug.cgi?id=1406903. Could we please have what we had before?

I fail to understand the underlying issue that Google seems to have - could somebody explain that with not too much technical argot ? Is this a browser-security-issue ?

**Comment by Mugurell** [comment]
This could be reconsidered in the future but for now Fenix will not support loading `file://` anymore.
Let's keep this feature request open to reconsider the opportunity of this later.

**Comment by lollita** [comment]
I would like too this feature.

**Comment by Kakitoru** [comment]
> This could be reconsidered in the future but for now Fenix will not support loading `file://` anymore.

Fenix was released long before it had feature parity with Fennec. It still doesn't, several releases later.

There are outstanding bugs in fundamental, basic browser functions like, say, downloading -- look at the list of issues there, I'm hit myself with one that I've been reporting with logs for months and can't download without a browser crash since version 82.x ... No one has even looked at the issue months later. Why report anything ? This is not an obscure issue -- I even suggested how to fix it, was ignored, meanwhile for months I have to turn to Chromium or terminal to download anything on Android, it's absurd.

With this last move removing in 85 the file:/// workaround for local browsing, me and my co-workers can't test offline documents on Android devices before moving them to production, open any local media files, or use our company's local wiki in-device.

I have been preaching for and promoting Firefox since it exists, but at this poiny it's clear I'm in denial.

Why are you doing all this ? I ask in earnest, do any of the current developers even use Fenix for anything other than browsing Facebook or Instagram these days ?

**Comment by Crandel** [comment]
This was last point for me to switch to vivaldi. I have a great collection of local html files. I see no point to use firefox anymore. Your product management total sucks

**Comment by mohibo** [comment]
that's why with firefox 68.12

**Comment by pphotography** [comment]
I got several HTML documents on my phone which are bookmarked using file:///... links. Since today I cannot access these files anymore with Firefox mobile. 
This workaround using file:///... link instead of showing a "open with Firefox" from the file manager was cumbersome, but now even this workaround is gone without any notification.

**Comment by mohibo** [comment]
> 
> 
> I got several HTML documents on my phone which are bookmarked using file:///... links. Since today I cannot access these files anymore with Firefox mobile.
> This workaround using file:///... link instead of showing a "open with Firefox" from the file manager was cumbersome, but now even this workaround is gone without any notification.

just go back to firefox 68.Its more usable than fenix

**Comment by pphotography** [comment]
How can I do that?

**Comment by Kakitoru** [comment]
> How can I do that?

Don't. Running a two year old browser is out of the question. You're putting yourself and others at risk.

If you need a functional browser, use a Chromium-based one ( Vivaldi, Bromite, Ungoogled Chromium ... ) until Fenix works.

**Comment by theres-waldo** [comment]
> Don't. Running a two year old browser is out of the question. You're putting yourself and others at risk.

You could use latest Fenix for regular browser and an older Firefox version for file:// URLs.

**Comment by mohibo** [comment]
> 
> 
> How can I do that?
go to fdroid and search fennec

**Comment by robsmith11** [comment]
What's the status of opening local files?

It's clearly an issue with significant community interest, but Mozilla seems to be ignoring it without providing any rationale.

**Comment by rolfausohnder** [comment]
> 
> 
> What's the status of opening local files?
> 
> It's clearly an issue with significant community interest, but Mozilla seems to be ignoring it without providing any rationale.

Good point. There surely is a rationale, and there surely are people who know it. Could someone please explain ?

**Comment by lnicola** [comment]
"There one was a security bug related to this which is now fixed, but let's remove a feature in the name of security theatre since our users don't need much else from a browser other than loading Facebook"?

**Comment by bk322** [comment]
Found a hack which allows one to open local html files in latest stable firefox (86.x as of now).

One need to save a link a local html file in collection. This was possible in Firefox 80.x: https://github.com/mozilla-mobile/fenix/releases/tag/v80.1.3

So the hack is to

1. remove firefox via play market
2. install firefox 80.x: https://github.com/mozilla-mobile/fenix/releases/tag/v80.1.3 (in my case that was https://github.com/mozilla-mobile/fenix/releases/download/v80.1.3/firefox_v80.1.3_arm.apk)
3. grant storage access to firefox: android settings -> apps -> firefox -> permissions -> storage
4. open local html file (in my case it is links.html which contains links to other local html files) - the file should open
5. save that local html file to a collection
6. upgrade firefox to the latest version
7. link to a local html file accessed via collection still works; links to all other local html files found in the one stored under collections work too. Updating the file contens does not break it.

**Comment by Kakitoru** [comment]
> Found a hack ...

This does not work for me. The collection and links in it survives the upgrade, sure. And with root file managing rights it's also easy enough to get the files and move them to any new device / install ( fixing rights appropriately ) but Firefox won't load a local file, it stays blank.

Not sure how or why it would work for you since loading local files is blocked, no matter from where.

**Comment by wymiatacz** [comment]
There still seems to be a way to open local files in Fenix 86.1.1.
If you setup remote debugging via USB, you can enter local URL (like file:///storage/emulated/0) in devtools toolbox's address bar (at PC) and Fenix opens it :)
Of course practical usability of this workaround is close to none, but it shows that not everything has been secured...

**Comment by MartyLake** [comment]
A workaround is to access those local html files via a local webserver. https://play.google.com/store/apps/details?id=jp.ubi.common.http.server (from https://android.stackexchange.com/questions/220400/local-files-revisited-opening-local-html-files-file-path-to-file-in-chrome )
Life would be a bit easier without having to do so.

**Comment by rolfausohnder** [comment]
> 
> 
> A workaround is to access those local html files via a local webserver. https://play.google.com/store/apps/details?id=jp.ubi.common.http.server (from https://android.stackexchange.com/questions/220400/local-files-revisited-opening-local-html-files-file-path-to-file-in-chrome )
> Life would be a bit easier without having to do so.

Thank you ! In the link they say that the concept of "scoped storage" was the reason for chrome to implement these restrictions - but why is this a reason ? I mean, we don't want to access each and every file all over the place, but just files from a certain location ! What's the problem with that in scoped storage ?

**Comment by Oymate** [comment]
Reminder: You can long press a link and download that HTML file in fenix

**Comment by artisticfox8** [comment]
> 
> 
> Browsing local files and opening HTML files works on my machine, with a small twist.
> 
> Write `file:///storage/emulated/0/` on your address bar and notice the `///`. If you don't write the `///` your address bar will display it for you but it will show an error, even if you refresh the page. So make sure to have the `///` on the first try, or else open a new tab.
> 
> Furthermore, once you have an HTML file opened, if you add it to your home screen, it won't be able to open it.
> 
> I use the lastest standard Firefox Preview from the Play Store on a Pixel 2 with Android 10.
> 
> Can anyone else confirm this behaviour on their device?
> 
> (Might be relevant for #4049 that is currently closed)

This almost works. When navigating to file:///storage/emulated/0/Documents/ it shows a blank folder, although there is an htm file there (accessible with the phones file manager). I'm on Samsung Galaxy A52, Android 11.

**Comment by artisticfox8** [comment]
> 
> 
> This could be reconsidered in the future but for now Fenix will not support loading `file://` anymore.
> Let's keep this feature request open to reconsider the opportunity of this later.

Could you perhaps base your opinion or reconsider it?

**Comment by n8chz** [comment]
We've gone from the UNIX philosophy "everything is a file" to the Android philosophy "nothing is a file" (or alternatively, "the filesystem is invisible") and I am not a happy camper.

The social engineering MO (according to #4049) for a hypothetical(?) malware infection through local HTML file seems to require persuading the mark to (1) save a file and then (2) open it from the filesystem. It would seem to me that a mark capable of acting on (2) would be sophisticated enough not to fall for (1), but who knows?

**Comment by n8chz** [comment]
For now I've found Kamran Zafar's [kWS Android Web Server](https://play.google.com/store/apps/details?id=org.xeustechnologies.android.kws) to be a usable workaround. Interestingly, found the following in one of the reviews of that app:

> I used this to access local html files from the browser which is no longer allowed in Android 10.

So it's not just a Firefox problem.

**Comment by artisticfox8** [comment]
> For now I've found Kamran Zafar's [kWS Android Web Server](https://play.google.com/store/apps/details?id=org.xeustechnologies.android.kws) to be a usable workaround. Interestingly, found the following in one of the reviews of that app:
> 
> > I used this to access local html files from the browser which is no longer allowed in Android 10.
> 
> So it's not just a Firefox problem.

You're wrong. I can open local html files on my Samsung Galaxy A52 (Android 11) just fine.

**Comment by testyac** [comment]
A workaround using netcat as a lightweight webserver to serve a single plaintext html file or a resource encoded html saved using [singlefile](https://addons.mozilla.org/en-US/firefox/addon/single-file/) desktop addon. Requires a terminal app. I am using Jackpal's Android [terminal](https://play.google.com/store/apps/details?id=jackpal.androidterm) app.

`while true; do echo -n -e "HTTP/1.1 200 OK\n\n" | cat - /sdcard/Download/filename.html | toybox nc -l -s 127.0.0.1 -p 8080; done`

This creates a loop for webserver serving the one file specified on localhost port 8080. Ensure the port is above 1024 as below it is restricted. Now just point firefox to http://127.0.0.1:8080/ to hit the nc server. Ctrl-c (VolDn+c) on the terminal app to kill the server. Additional HTTP headers can be added to the echo string as needed.

Other than terminal app, no other apps are needed. Toybox already has nc, and toybox is bundled with Android. Tested on my old Android 7.1. If toybox nc is bundled with your version of android this should work.

Hope this helps.

**Comment by testyac** [comment]
A workaround using netcat as a lightweight webserver to serve a single plaintext html file or a resource encoded html saved using [singlefile](https://addons.mozilla.org/en-US/firefox/addon/single-file/) desktop addon. Requires a terminal app. I am using Jackpal's Android [terminal](https://play.google.com/store/apps/details?id=jackpal.androidterm) app.

`while true; do echo -n -e "HTTP/1.1 200 OK\n\n" | cat - /sdcard/Download/filename.html | toybox nc -l -s 127.0.0.1 -p 8080; done`

This creates a loop for webserver serving the one file specified on localhost port 8080. Ensure the port is above 1024 as below it is restricted. Now just point firefox to http://127.0.0.1:8080/ to hit the nc server. Ctrl-c (VolDn+c) on the terminal app to kill the server. Additional HTTP headers can be added to the echo string as needed.

Other than terminal app, no other apps are needed. Toybox already has nc, and toybox is bundled with Android. Tested on my old Android 7.1. If toybox nc is bundled with your version of android this should work.

Hope this helps.

**Comment by agi** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1743195

**Comment by karam72** [comment]
Is there any update for this issue?

**Comment by serj-kzv** [comment]
See workaround https://github.com/fork-maintainers/iceraven-browser/issues/281#issuecomment-1088010840

**Comment by serj-kzv** [comment]
> See workaround [fork-maintainers#281 (comment)](https://github.com/fork-maintainers/iceraven-browser/issues/281#issuecomment-1088010840)

What is a point to hide my comment? There are a lot of such comment above including comments with ways to avoid the Firefox restriction. And they are not hidden. And also there are a lot of not very useful comments.   Sorry if it is a result of some github algorithm, I am not aware about such github functionality.

**Comment by robsmith11** [comment]
> What is a point to hide my comment?

It's pretty clear that Mozilla no longer believes in open discussion.  They have their agenda and don't care if the community disagrees with them.

**Comment by bowknot** [comment]
> A workaround is to access those local html files via a local webserver. https://play.google.com/store/apps/details?id=jp.ubi.common.http.server (from https://android.stackexchange.com/questions/220400/local-files-revisited-opening-local-html-files-file-path-to-file-in-chrome ) Life would be a bit easier without having to do so.

This software is very easy to use. Thank you, but arm will not support 32-bit applications in the future. This software has not been updated for a long time. What should we do when arm only supports 64 bit applications in the future?

**Comment by RFDAJE** [comment]
> > A workaround is to access those local html files via a local webserver. https://play.google.com/store/apps/details?id=jp.ubi.common.http.server (from https://android.stackexchange.com/questions/220400/local-files-revisited-opening-local-html-files-file-path-to-file-in-chrome ) Life would be a bit easier without having to do so.
> 
> This software is very easy to use. Thank you, but arm will not support 32-bit applications in the future. This software has not been updated for a long time. What should we do when arm only supports 64 bit applications in the future?

- install termux nix on android
- install python in termux nix
- run `python -m http.server --directory /any/dir/` in termux nix
- open http://0.0.0.0:8000 in browser

**Comment by karam72** [comment]
This is unacceptable. Not opening local files... At least it can be a config on about:config.

**Comment by JJRcop** [comment]
I am on the "Fennec F-Droid" build of Fenix, so I was able to install this lovely extension to translate web pages directly in the DOM since I am learning another language, but sometimes need the extra help https://addons.mozilla.org/en-US/firefox/addon/traduzir-paginas-web/

It's quite a shame that I can't use it directly on offline webpages since I have to use the Android HTML viewer, and not Fenix.

I am very supportive of this feature returning to fenix.

**Comment by Manuel-K** [comment]
I'd never have thought that this was possible in my wildest dreams. I just bought a tablet to view local html files in firefox with lots of custom programming and now I feel that I have wasted my money. 

It is very disappointing that there isn't even a hidden toggle in `about:config` to mitigate this issue.

**Comment by artisticfox8** [comment]
> I'd never have thought that this was possible in my wildest dreams. I just bought a tablet to view local html files in firefox with lots of custom programming and now I feel that I have wasted my money.
> 
> It is very disappointing that there isn't even a hidden toggle in `about:config` to mitigate this issue.

As others have said, you can at least view the files using a local server for now

**Comment by Manuel-K** [comment]
> As others have said, you can at least view the files using a local server for now

Unfortunately the tablet uses Android 12, so Termux does not work correctly due to its processes getting killed.

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
The `file://` URI scheme is entirely unavailable for me via Fennec.

**Comment by artisticfox8** [comment]
> > As others have said, you can at least view the files using a local server for now
> 
> Unfortunately the tablet uses Android 12, so Termux does not work correctly due to its processes getting killed.

I use Android 12 too and the Fdroid build works

**Comment by Manuel-K** [comment]
> I use Android 12 too and the Fdroid build works

Good to know. There were so many discouraging reports that I didn't want to try it after the many disappointments and the constant jumping through an ever increasing number of hoops. In the meantime, I was able to return the tablet and have received my money back.

**Comment by OmlineEditor** [comment]
add the ability to open links directly from the drive:  `file:///storage/emulated/0/temp/index.html`
all good browsers are able to do this. your browser is good and should do it too. it has already been 2 years since the ticket was opened. please implement this.

**Comment by bowknot** [comment]
> 

I suspect that Firefox has Google's insiders, and Android Software is getting worse, just like Nokia had Microsoft's insiders at the beginning

**Comment by robsmith11** [comment]
It really is strange that Mozilla won't at least give a reason why they refuse to implement this popular feature.  So much for an "open" organization. Their silence is only going to encourage suspicion.

**Comment by karam72** [comment]
I can not say anything if Mozilla is decided to not open local files as default. But it is not acceptable that they not allowed to advanced user (with an about:config setting).

Please everyone use "Fennec F-droid" and other alternatives (especially from here: [privacyguides.org](https://www.privacyguides.org/browsers/)). So maybe Mozilla can see why people are leaving it... There is nothing I can do.

**Comment by bk322** [comment]
Another workaround is to keep an outdated version of firefox just to read local html files.

For this:

1. uninstall firefox via google play
2. download apk of outdated firefox which allows to open local html files:

   * most recent version which still supports openning local html files is 84.1.4, you can download apk from https://github.com/mozilla-mobile/fenix/releases/tag/v84.1.4
   * if you are also interested in old extensions you may use https://ftp.mozilla.org/pub/mobile/releases/68.11.0/

   (in both cases you probably want aarch64 version)
   
3. install apk by clicking on it for example via file manager
   
4. grant firefox access to storage: Android Settings -> Apps -> Permissions -> Storage

5. turn off auto-update of firefox via google play

6. Bonus: install "Fennic F-Droid" from F-Droid to use as your default web browser

**Comment by Anutrix** [comment]
Still waiting for this

**Comment by vehosah** [comment]
And two years later and no updates at all

**Comment by pgorod** [comment]
After investing in Firefox, designing company processes, add-ons, etc., a couple of years ago we saw that Firefox had been crippled and had to pull back to Firefox 68 to keep the work going on as normal. 

No explanation was given, to this day. No estimate of when (or if) this will be fixed so that Firefox can adequately be called a "Browser" again.

This was a spectacularly wrong decision by someone at Mozilla, and it seems there is no ability to backtrack on a spectacularly wrong decision at Mozilla, which is a shame.

This is done in the name of security, but real-world security is necessarily a trade-off between practicality and risks; so, in practice, right now it's about a work-force (I won't say which company) all riddled with insecure Firefox 68 (for ever?). We could take the costs and redo the whole thing differently. And then on the next day Mozilla could wake up, solve this blunder and we would look like idiots.

How wrong I was, years ago, when I explained to management that this would surely be solved quickly because it was incredibly wrong and inconsistent...

**Comment by Mugurell** [comment]
> Oh, and the list of allowed add-ons for mobile Firefox has never been updated since it was introduced three years ago.

Firefox Beta will get support for more addons starting with the next version - 107 - https://github.com/mozilla-mobile/fenix/issues/26948.

**Comment by pgorod** [comment]
Why is this labeled as a "Feature request"? This is a bug, and a nasty one. Basic browser functionality that was there was broken in a carelessly considered "security" decision. Countless users have been complaining that their legitimate Firefox uses have been crippled by this decision. 

Nobody is asking for new features here. To fix this, nobody will have to produce new code, they'll just have to remove the code that was introduced to block the pre-existing feature. Firefox v0.1 could browse local files...

I respectfully request the people with the required permissions to re-label this correctly. Thanks!

**Comment by mortyobnoxious** [comment]
This issue has been open for:
![image](https://user-images.githubusercontent.com/42044258/198158591-862ce0ba-da16-4050-93d0-22c6036cf840.png)

**Comment by kbrosnan** [comment]
As part of https://github.com/mozilla-mobile/fenix/issues/26855 this report has been moved to Bugzilla as bz-1806171

**Comment by Rangtian** [comment]
Alas... How I wish I could view SVG files on Android with Firefox...

**Comment by Anutrix** [comment]
> Alas... How I wish I could view SVG files on Android with Firefox...

Forget SVG. If they at least allowed basic HTML, which is supported on most mobile browsers. I wonder if the devs realize what message, a browser that says it can't support basic web stack bits locally, sends to general public.
