### ISSUE TITLE
Access Devtools within the browser

### ISSUE THREAD

**Issue by RangerMauve** [mozilla-mobile/fenix#7549]
### Why/User Benefit/User Problem

Mobile devices are becoming more prevalent and more and more people are using them exclusively rather than laptops or desktops.

One of the cool features of web browsers, for me, has been the ability to inspect and mess around with them and see how they work under the hood. It helped get me into web development, and I've heard similar stories from a lot of people in the industry.

It'd be nice if we could start seeing dev tools within phones and get the current generation of web-users to have the same experience.

### What/Requirements

- Ability to open dev tools as a tab
- A mobile-friendly-ish UI for dev tools (The desktop version is good enough for tablets)
- An "open dev tools button" in the hamburger menu somewhere
- An "inspect element" option in the context menu when right clicking an element.
- Ability to dock dev tools while viewing the page in addition to the tab? (probably harder to get right)

### Acceptance Criteria (how do I know when I’m done?)

- People will be able to debug issues with web pages / mess around with them.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-15092)

**Comment by darkwing** [comment]
Have you tried remote debugging in Firefox: https://developer.mozilla.org/en-US/docs/Tools/about:debugging ?

I'd imagine screen real estate to get DevTools and the page on the same screen, in some fashion, would be very difficult.

**Comment by RangerMauve** [comment]
Remote debugging is great when you're already using a laptop or desktop, and I've been pretty comfortable doing that for years for mobile web app development.

However this makes mobile devices second class citizens and prevents regular people (who mostly use mobile devices these days) from being able to tinker with this stuff they way they could in the past.

I agree that screen real estate will likely require some extra UX work, but I think that the benefits it'd give people are worth it.

**Comment by blogmangit** [comment]
+1 I also support this of ff having devtool integrated inside it so that we can inspect elements.

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813604

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
