### ISSUE TITLE
[webcontent] Spotify webplayer mobile don't work

### ISSUE THREAD

**Issue by marker10** [mozilla-mobile/fenix#7552]
3.0.1 (Build #13502256)
📦: 24.0.0, 968f858c1
GV: 71.0-20191125115111

**Comment by kbrosnan** [comment]
This looks broken on Spotify's side. Tapping launch web player briefly displays https://open.spotify.com before redirecting the user back to https://www.spotify.com/us/

**Comment by ekager** [comment]
Closing because I can access open.spotify.com now. (It just keeps popping me to the app, but it shows up). Reopen if this is still an issue
