### ISSUE TITLE
Show App Services version on About Pages

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/fenix#7554]
Similar to https://github.com/mozilla-mobile/fenix/issues/3055 - show the app services version used in the build on the About Page.

**Comment by joshvocal** [comment]
Is there a screenshot on what this should look like?

**Comment by jonalmeida** [comment]
> Would adding the app services version under GV be alright?
> 

@joshvocal Most probably along with `AS: ` prepended, but I would also wait until the Fenix team triages this.

**Comment by harshlele** [comment]
Can I work on this issue?

**Comment by harshlele** [comment]
uhhh doesn't the commit mentioned above solve the issue?

**Comment by joshvocal** [comment]
@harshlele Do you mind if I take this one? 😅I was clarifying where `AS` should be placed and I didn't see your message before you asked to be assigned.

**Comment by harshlele** [comment]
well yeah I guess since you've already made the commit haha

**Comment by jonalmeida** [comment]
@joshvocal your change looks good to me, when you make the PR, ping me and I can approve it. :)

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **Nightly Build #20650606 from 03/05** using the following devices:
• Google Pixel 3a (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

►Screenshot
![asv](https://user-images.githubusercontent.com/51314259/75958468-f8439100-5ec4-11ea-9ef7-73cd6ca867c6.png)
