### ISSUE TITLE
Clicking Awesome Bar URL suggestion is not triggering navigation or page load

### ISSUE THREAD

**Issue by ekager** [mozilla-mobile/fenix#756]
## Steps to reproduce
1. Open search
2. Type a few characters
3. Click a URL suggestion

### Expected behavior
Launches URL

### Actual behavior
Nothing happens

### Device information

* Android device: Pixel
* Fenix version: Master

**Comment by colintheshots** [comment]
Looks like a new regression with the suggestions from History.

**Comment by ekager** [comment]
Not seeing this anymore in master, closing
