### ISSUE TITLE
[Bug] Fenix currently does not support High Refresh Rate

### ISSUE THREAD

**Issue by beatbrot** [mozilla-mobile/fenix#7560]
## Steps to reproduce

1. Open [testufo.com](http://testufo.com)
2. Set "Count of UFOs" to 1

### Expected behavior

Get 90FPS on a 90Hz Screen

### Actual behavior

Getting 60FPS while Chrome gets 90

### Device information

* Android device: OnePlus 7T (OxygenOS 10.0.7 EU)
* Fenix version: 3.0.2
* Fenix version: Nightly 200107 06:01

**Comment by beatbrot** [comment]
I did some further investigation.

Only Chrome stable gets 90FPS. Both Chrome Canary and Bromite get just 60FPS. Maybe OnePlus has some kind of whitelist?

**Comment by beatbrot** [comment]
After even more investigation, I found out that I can force 90Hz with the app [Auto90](https://play.google.com/store/apps/details?id=com.arter97.auto90&hl=en_US). I could not find any visual glitches after enabling it.

It truly seems like OnePlus would have to approve the app for the official 90Hz mode

**Comment by kbrosnan** [comment]
Sounds like there is nothing we can do to advance this issue. Closing.

**Comment by yoasif** [comment]
@kbrosnan It looks like Fenix can support this using the frame pacing library: 

https://developer.android.com/games/sdk/frame-pacing
https://source.android.com/devices/graphics/frame-pacing

Can you reopen this bug? 

It is probably also worth looking into how upstream Chromium achieves this, since high refresh rate displays will likely go up in use.

**Comment by kbrosnan** [comment]
This sounds like GeckoView and/or Android components work.

**Comment by yoasif** [comment]
Sure, but Fenix doesn't yet support it. I don't know where it belongs, is that something a team member can do once they evaluate the request? I fear it will get lost if the bug remains closed.

**Comment by mugna91** [comment]
+1 on realme X2 pro we have the same ploblem. Firefox preview don't work at 90hz refresh rate. Also, Auto90 it's not working on Realme's devices. Maybe this issue should be reopened.

**Comment by bshandley** [comment]
Oneplus 7T user here. Firefox preview and nightly only achieve 60 fps on the UFO test. Standard Firefox hits 90 fps without issue.
