### ISSUE TITLE
[Bug] Switch to tab snackbar is not visible with top toolbar

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#7565]
## Steps to reproduce
1. Set the Toolbar to be at the top.
2. Open a link in a new tab.
3. Watch the switch tab snackbar.
### Expected behavior
The snackbar is displayed.
### Actual behavior
The switch to tab snackbar is not displayed with top toolbar.
### Device information

* Android device: Pixel 3
* Fenix version: Rc 3.0.2

**Comment by sv-sdeiac** [comment]
I can reproduce this issue using Xiaomi Mi Pad 2 (Android 5.1). 
Also, when you copy the link from URL bar, still doesn't display the snackbar.

**Comment by mcarare** [comment]
This seems to have been fixed since. Can QA please recheck? Thank you!

**Comment by sflorean** [comment]
@mcarare I wasn't able to reproduce the issue on Nightly 9/25 with Pixel 3 (Android 11).

**Comment by mcarare** [comment]
Closing as per above comment: https://github.com/mozilla-mobile/fenix/issues/7565#issuecomment-698968436
