### ISSUE TITLE
[Bug] Some websites are not displayed on about:debugging Service Workers section

### ISSUE THREAD

**Issue by st3fan** [mozilla-mobile/fenix#7569]
> Taken from https://bugzilla.mozilla.org/show_bug.cgi?id=1605847

**Environment:**
Device: Nexus 6P (Android 8.1), Google Pixel (Android Q), Windows 10
Build: Firefox Preview Nightly 191224 (#13580608), Gecko 73.0a1

**Steps to reproduce:**
1. On Fenix, go to about:config and activate dom.serviceWorkers.parent_intercept pref to "true".
2. On Fenix, load these [pages](https://docs.google.com/document/d/1-NdKZVPHNebJT8-NqcGGvc4BA1DucXbSDM0I3JbFnHg/edit) in different tabs.
3. Connect your device to the PC, and make sure the Remote debugging via USB toggle is ON.
4. On Desktop, on Firefox Nightly go to:
- about:config and set workers.parent to "true";
- about:debugging - tap on "This Nightly" from the upper left corner, and scroll the page until you reach the "Service Workers" section.

**Expected result:**
The connected device is visible. "Service Workers" displays all the opened tabs from the device.

**Actual result:**
The connected device is visible. "Service Workers" doesn't display the following opened tabs:
- mail.google.com,
- reddit.com,
- news.google.com,
- backcountry.com.

**Notes:**
* On Firefox RC 68.3.0 the news.google.com site is displayed in the Service Workers list, but the other 3 aren't.
* It reproduces with dom.serviceWorkers.parent_intercept pref enabled, and disabled.

---

(In reply to miralobontiu from comment #0)
> - about:debugging - tap on "This Nightly" from the upper left corner, and scroll the page until you reach the "Service Workers" section.

I think this step might be incorrect.  If you tap "This Nightly", I think you end up listing the Service Workers for the desktop browser, not the connected device (Nexus 6P) where the ServiceWorkers would have been installed.  You'd want to click on the "Nexus 6P" option beneath the "USB Enabled" header, like in the image at https://media.prod.mdn.mozit.cloud/attachments/2019/10/21/16915/f27759083e3a123ce527cb7415f7e14d/device_information.png from https://developer.mozilla.org/en-US/docs/Tools/about:debugging#Setup_tab.

Also, it's necessary to restart Fenix after enabling the "dom.serviceWorkers.parent_intercept" preference.  (And Step 4 bullet 1 I think is also saying to make sure that pref is enabled on the desktop, but that should only be necessary if you're testing parent-intercept on the desktop nightly browser.)

---

Hi Andrew!

You are right, I've omitted a step. So, the ***STR*** are:
1. On Fenix, go to about:config and make sure the dom.serviceWorkers.parent_intercept pref is set to "true" (it is set to true by default).
2. On Fenix, load these [pages](https://docs.google.com/document/d/1-NdKZVPHNebJT8-NqcGGvc4BA1DucXbSDM0I3JbFnHg/edit) in different tabs.
3. Connect your device to the PC, and make sure the Remote debugging via USB toggle is ON.
4. On Desktop, on Firefox Nightly go to:
- about:config and set workers.parent to "true";
- about:debugging - tap on "This Nightly" from the upper left corner, and scroll the page until you reach the "Service Workers" section.
5. Tap on your device, in this case, Nexus 6P option beneath the "USB enabled" and observe the "Service Workers" section and if the pages opened at step 2 are displayed.

***Actual result:***
The connected device is visible. "Service Workers" doesn't display the following opened tabs:
- mail.google.com,
- reddit.com,
- backcountry.com.

On the latest Nightly build from 01/07 (#20070607), the news.google.com is now displayed in the service workers section, with both devices: Nexus 6P (Android 8.1), and Google Pixel (Android 10).

**Comment by softvision-miralobontiu** [comment]
I've retested with the latest Nightly from 1/29 with Huawei P10 (Android 9), and Google Pixel (Android 10) and here are the results:
- mail.google.com, and reddit.com are still not displayed in the "Service Workers" section.
- with VPN on, backcountry.com is visible in the "Service Workers" section.
