### ISSUE TITLE
[Bug] Location is not displayed in https://daleharvey.github.io/testapp/ even if "Don't ask again" is selected

### ISSUE THREAD

**Issue by lobontiumira** [mozilla-mobile/fenix#7571]
## Steps to reproduce
1. Make Fenix your default browser.
2. In custom tab, open https://daleharvey.github.io/testapp/ and tap on the "Get location" button.
3. Check the "Don't ask again" checkbox and allow permission.

### Expected behavior
The location's coordinates are displayed.

### Actual behavior
The location's coordinates are not displayed. There is no action.

### Device information
* Reproducible also in browser.
* Android device: Nokia 6 (Android 7.1.1), Samsung Galaxy Note8 (Android 9)
* Fenix version: RC 3.0.2, Nightly 01/09 (#20090616)

![20200109_Trim](https://user-images.githubusercontent.com/40694158/72080338-4a24cc00-3305-11ea-8727-6d3467141999.gif)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-15107)

**Comment by kbrosnan** [comment]
Works for me on a Pixel 3 running Android 10.

**Comment by Diana-Rus** [comment]
Hi, I can reproduce the issue, does not matter whether the "Don't ask again" checkbox is checked or not. The location isn't displayed.

Device: Google Pixel C (Android 8.0.0)
Build:Firefox Preview Beta 4.0.0-beta.1

Gif:
![20200220-103155](https://user-images.githubusercontent.com/49859863/74916485-9f590080-53ce-11ea-9625-0c32868568a6.gif)

**Comment by Diana-Rus** [comment]
Hi, the same issue is present for Nexus 9(Android 7.1.1) with Firefox Preview Beta 4.0.0-beta.2.

**Comment by softvision-miralobontiu** [comment]
This issue reproduces with 6/9 Nightly with Google Pixel (Android 10).

**Comment by softvision-miralobontiu** [comment]
I was able to reproduce this issue with 12/29 Nightly build with Google Pixel (Android 10).

**Comment by lobontiumira** [comment]
I was able to reproduce this issue on the 6/29 Nightly build with Google Pixel (Android 10).

**Comment by lobontiumira** [comment]
I was able to reproduce this issue on the 11/2 Nightly build with Google Pixel (Android 10).

**Comment by SoftVision-LorandJanos** [comment]
This issue is still reproducible with the latest Nightly 102.0a1 (2022-05-09) build.
Device used: Google Pixel 4 (Android 12).
