### ISSUE TITLE
Change PWA behavior for out-of-scope navigation

### ISSUE THREAD

**Issue by snorp** [mozilla-mobile/fenix#7575]
Currently, if you click an "external" link while in a PWA, it navigates in the same "tab", but then shows the custom-tab-like location bar. Hitting the back button navigates back. This is okayish, but I have a couple problems with it:

1) There is no feedback when the navigation starts. We could consider showing the urlbar as soon as we detect that there will be a new out-of-scope page coming.

2) If you go further into the history (by clicking more links), it takes a lot of taps to get back to the PWA.

Fennec just used a normal custom tab for out-of-scope navigations. This avoided 1) by having an immediate Activity transition, and avoids 2) because you have a close button for going back to the app.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-15109)

**Comment by NotWoods** [comment]
We actually took out the close button because people were confused, as it only closed the tab and not the whole app. The custom tab is a new activity so we could add some transition there.

**Comment by snorp** [comment]
Yeah, I think the activity transition would help people realize what's going on.

Another issue -- if you have Fenix set to open links in private mode, you'd want that to happen for these links as well. So if we just use a custom tab, we get that for free. IMO, external links from a PWA should behave exactly as if you clicked it from inside an actual app (which would likely use a custom tab).

**Comment by andreasbovens** [comment]
> We actually took out the close button because people were confused, as it only closed the tab and not the whole app. 

That is expected behavior for Custom Tabs. We want to load external content from PWAs in a similar fashion as we'd load content from native apps (calling a CT).

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807433

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
