### ISSUE TITLE
Hide private tabs after a certain amount of time

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#7576]
### Why/User Benefit/User Problem
I'd like my private tabs to be hidden if I've forgotten they even exist! (Sometime after ~30minutes? Just enough that we think the user has context switched to something else)

### Acceptance Criteria (how do I know when I’m done?)
- I can toggle this preference on in settings ("hide private tabs after X minutes")
- When enabled, Fenix opens to a "normal" session instead of a private one when I resume it (we should set `lastKnownMode = normal` after X minutes... we already have a persistent notification so this shouldn't be too complex 🤔 )

We could also consider a "close private tabs after X minutes" or "on close" 

Flagging @liuche, @AmyYLee on this so they can add additional thoughts :)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-15110)

**Comment by Poopooracoocoo** [comment]
I don't think "hide" is the best word for the setting. Maybe "Switch to normal session" would be better.

**Comment by Poopooracoocoo** [comment]
just referencing #7577 just because it hasn't been already

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807546

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
