### ISSUE TITLE
Do not switch users out of private mode to normal mode (persist the mode instead)

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#7577]
This is a decision that came out of https://github.com/mozilla-mobile/fenix/issues/6304#issuecomment-571301380

**Comment by sblatz** [comment]
New desired behavior: 
![private persisting 2020-01-09 11_28_38](https://user-images.githubusercontent.com/4400286/72098378-319bbe00-32d3-11ea-8b22-70a5f3729bb9.gif)

**Comment by sv-sdeiac** [comment]
Verified as fixed using the latest version of Nightly 1/10 #20100616.

Devices:
- OnePlus 5T (Android 9);
- Xiaomi Mi 8 Lite (Android 9);
- LG G7 fit (Android 8.1).
