### ISSUE TITLE
[Bug] language settings: alignment of RTL languages

### ISSUE THREAD

**Issue by cadeyrn** [mozilla-mobile/fenix#7583]
### Steps to reproduce

1. open Menu > Settings > Language

### Expected behavior

I am not a RTL expert so I don't know if RTL languages on this page should be left aligned or right aligned. But *both* lines should be left aligned or *both* lined should be right aligned.

### Actual behavior

The first line is right aligned, the second line is left aligned, see for example Hebrew. This looks very odd.

![Screenshot_20200109-233456](https://user-images.githubusercontent.com/1100614/72110922-af92b000-3339-11ea-9276-57a779e3105d.jpg)

For reference: In Chrome both lines are left aligned.

### Device information

* Android device: OnePlus 7T Pro McLaren Edition / Android 10
* Fenix version: master branch revision 0a412a1a6ae218e3ea0e9f67604c37c5355eb61c

**Comment by sv-sdeiac** [comment]
Hello, I can confirm that this issue is fixed using the latest version of Firefox Preview Nightly 1/13 #20130605.

Devices:
- Nokia 6 (Android 7.1.1);
- Motorola Moto G6 (Android 8);
- Samsung Galaxy Note 8 (Android 9);
- Google Pixel 2 (Android 9);
- Google Pixel (Android Q).
