### ISSUE TITLE
[Bug] wrong header bar background color for libraries screen

### ISSUE THREAD

**Issue by cadeyrn** [mozilla-mobile/fenix#7584]
### Steps to reproduce

1. Open Settings > About Firefox Preview > Libraries that we use

### Expected behavior

The header bar has the same background color as every other screen in Firefox Preview (white).

### Actual behavior

The header bar is black.

![Screenshot_20200109-233559](https://user-images.githubusercontent.com/1100614/72111178-4cede400-333a-11ea-8df6-c381077f7116.jpg)

### Device information

* Android device: OnePlus 7T Pro McLaren Edition / Android 10
* Fenix version: master branch revision 0a412a1a6ae218e3ea0e9f67604c37c5355eb61c

**Comment by mcarare** [comment]
This has another issue, i.e., the `OssLicensesActivity` also changes the colour for navigation and status bar.  The more direct approach is to create a custom fragment for this, instead of relying on the system one.  The work for this was supposed to be done in AC.

**Comment by darkwing** [comment]
@mcarare Is there an AC issue open for this?  Could your provide a link?

**Comment by mcarare** [comment]
@darkwing I am not aware of any issue already opened in AC.

**Comment by cadeyrn** [comment]
@liuche Can you re-open the issue? I just checked this. The color of the header bar is no longer black but it's still the wrong color. I am not sure if the new color of the header bar is used anywhere else in Fenix, the color does not look familiar to me.

**Comment by liuche** [comment]
That's definitely weird! @gilbsgilbs is that something that you had fixed in your PR?

**Comment by gilbsgilbs** [comment]
My PR fixed the light toolbar in dark mode (see screenshots), but I didn't notice it wasn't the exact same color as the rest of the app. It's probably because the screen is a different activity which uses the global theme.
