### ISSUE TITLE
Create shortcuts.xml override for fennecNightly build type

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/fenix#7587]
We are overriding shortcuts.xml in different build types because it contains the package name. We need to do the same for the fennecNightly flavor.

**Comment by ebalazs-sv** [comment]
@pocmo Hi! Can you please provide details to reproduce so it can be verified? Thanks!

**Comment by ebalazs-sv** [comment]
Verified as fixed on Fennec Nightly migration build 2, 01/17 with OnePlus 5T (Android 9), the "New tab" and "New private tab" options are available when long pressing the Fenix icon. These can also be added to the home screen.
Due to that I will move this to Done. Thanks!
