### ISSUE TITLE
[Bug] "AboutFragment" title is briefly displayed when opening About Firefox Preview from Settings

### ISSUE THREAD

**Issue by mcarare** [mozilla-mobile/fenix#7593]
"**AboutFragment**" title is briefly displayed when opening About Firefox Preview from Settings.

**Comment by sv-sdeiac** [comment]
Hello, I can confirm that this issue is fixed on the Firefox Preview Nightly 1/13 #20130605.

Devices:
- Nokia 6 (Android 7.1.1);
- Motorola Moto G6 (Android 8);
- Samsung Galaxy Note 8 (Android 9);
- Google Pixel 2 (Android 9);
- Google Pixel (Android Q).
