### ISSUE TITLE
[Bug] Hint on main page can be displayed in two lines

### ISSUE THREAD

**Issue by marcinwiacek** [mozilla-mobile/fenix#7594]
## Steps to reproduce

Setup big fonts in the system + open FP

### Expected behavior

Hint is displayed in one line

### Actual behavior

![Screenshot_1578665476](https://user-images.githubusercontent.com/24834168/72165919-971da680-33c8-11ea-8d6b-7d639a50b208.png)

### Device information

* Android device: ?
* Fenix version: ?

**Comment by ekager** [comment]
Reopening for QA

**Comment by sv-sdeiac** [comment]
Verified as fixed using the latest version of Firefox Preview NIghtly 1/16 build #20160806.

Devices:
- Nokia 6 (Android 7.1.1);
- Motorola Moto G6 (Android 8.0);
- Samsung Galaxy Note 8 (Android 9);
- Google Pixel (Android Q).
