### ISSUE TITLE
[Bug] Weird behaviour of some websites on zoom

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#7599]
### Steps to reproduce
open freetype.org
zoom in
### Expected behavior
sidebar scrolls with the rest of the page, like fennec and chrome do
### Actual behavior
![2020_01_10_23_2-1578678904148](https://user-images.githubusercontent.com/33252312/72174959-d81ab880-33d2-11ea-8ecd-5c6d2c8b533c.gif)

### Device information

* Android device: Asus zenfone m1
* Fenix version:
 Nightly 200109 18:00 (Build #20091807)
28.0.0, a53f8eaba
GV: 74.0a1-20200107215758

**Comment by kbrosnan** [comment]
Zooming with `position: fixed` elements will have this behavior.

**Comment by s-ankur** [comment]
This is how it works in fennec and chrome , though
![2020_01_11_12_3-1578726444441](https://user-images.githubusercontent.com/33252312/72200418-341c2600-3441-11ea-9049-b083ea6a9bdb.gif)

**Comment by ktaeleman** [comment]
Related gecko bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1569339

**Comment by s-ankur** [comment]
Hi this issue seems to be fixed now

**Comment by s-ankur** [comment]
Closing as fixed
