### ISSUE TITLE
[Bug] "No site exceptions" not exposed to translators

### ISSUE THREAD

**Issue by cadeyrn** [mozilla-mobile/fenix#7612]
### Steps to reproduce

1. use Fenix in a non-English language
2. open Settings > Site permissions > Exceptions
3. make sure you have no exceptions

### Expected behavior

"No site exceptions" string is translated.

### Actual behavior

"No site exceptions" string is English. Since it's not a new feature at all and I can't find the string on Pontoon it seems that this string was forgotten to expose to the translators.

**Comment by ekager** [comment]
This string is in the `permissions_settings_strings.xml` file. I'm not sure how to make sure additional string resource files are included in our translation files. @boek do you know?

The easiest solution is to copy these strings over to the main `strings.xml` file.

**Comment by cadeyrn** [comment]
Duplicate of #5080.
