### ISSUE TITLE
[Onboarding] Spacing is uneven around radio buttons

### ISSUE THREAD

**Issue by AmyYLee** [mozilla-mobile/fenix#7613]
The spacing is uneven around the radio buttons in the Onboarding card. Thanks!

![Screen Shot 2020-01-10 at 5 30 40 PM](https://user-images.githubusercontent.com/5992746/72191043-08f8ee80-33cf-11ea-9569-11340ab50082.png)

**Comment by ekager** [comment]
IIRC this is more difficult than it looks. I implemented this with a radio button with a circular constraint with angle and radius relative to the theme image. The angle is currently 298 and the radius is currently 66dp. AFAICT you can't use a half angle of 298.5, and 299 has the same not quite even problem but on the other edge. This will take some trial and error.

**Comment by mcarare** [comment]
Maybe it's just me, but it doesn't look to me like the empty space in the PNGs used for the card are perfect circles. 
![onboarding_dark_theme](https://user-images.githubusercontent.com/48995920/72256544-2073e980-3612-11ea-9a8c-53b1e568df24.png)

**Comment by boek** [comment]
Eng will work with Amy to get an image that fits around the radio button

**Comment by sv-sdeiac** [comment]
Verified as fixed using the latest version of Firefox Preview Nightly 2/6 #20370604.

Devices:
- Nokia 6 (Android 7.1.1);
- Samsung Galaxy S8 (Android 9);
- Google Pixel 3 (Android Q).
