### ISSUE TITLE
[Bug] Unable to resolve any web pages when enabling DNS-over-HTTPS

### ISSUE THREAD

**Issue by pwd-github** [mozilla-mobile/fenix#7615]
## Steps to reproduce
1. Open Fenix
2. Type webpage address

### Expected behavior
Page loads

### Actual behavior
Address Not Found

### Device information

* Android device: Pixel 4XL
* Fenix version: Nightly 200110 22:30 (Build 20102234)

### Other Information
Suspected that it's due to something happening in Gecko. See here [1] for more info.

[1] https://www.reddit.com/r/firefox/comments/emqxqf/firefox_nightly_does_not_resolve_any_web_pages/

**Comment by sv-ohorvath** [comment]
@pwd-github can you still reproduce?
I can't on a Pixel 3.

**Comment by pwd-github** [comment]
With network.trr.mode set to 3 yes. With it set to 0, no.

**Comment by KrasnayaPloshchad** [comment]
> With network.trr.mode set to 3 yes. With it set to 0, no.

What can I do for this? My work around is to use [Intra](https://github.com/Jigsaw-Code/Intra).
