### ISSUE TITLE
[Bug] Option to "Add to Homescreen" or "Install" missing from installations

### ISSUE THREAD

**Issue by pwd-github** [mozilla-mobile/fenix#7616]
## Steps to reproduce
Navigate to a site like twitter.com
Open menu

### Expected behavior
Option to add to homescreen is in menu

### Actual behavior
N/A

### Device information

* Android device: Pixel 4XL, LG G6, Nvidia Shield
* Fenix version: Nightly

**Comment by sv-sdeiac** [comment]
Hello @pwd-github, I am not able to reproduce your issue using the latest version of Firefox Preview Nightly 1/13 #20130605.
Can you retry please with the latest version of NIghtly and come with an update?

Devices:
 - Google Pixel (Android Q);
- Samsung Galaxy Note 8 (Android 9);
- LG G7 fit (Android 8.1);
- Motorola Moto G6 (Android 8);
- Nokia 6 (Android 7.1.1).

**Comment by pwd-github** [comment]
I'm still seeing this issue. Is it hidden behind a pref or is it region locked? 

Pixel 4XL
LG G6

**Comment by sv-sdeiac** [comment]
@pwd-github I used a clear build without any changes.

**Comment by pwd-github** [comment]
I cleared data on the Snapshot build ```(3.0.2 (Build #20081833)
📦: 24.0.1, ee4587f74
🦎: 71.0.1-20200108003105)```

And neither option (Add to Install or Add to Homescreen) is there still.

![Screenshot_20200113-174614](https://user-images.githubusercontent.com/203217/72278888-da784f00-362c-11ea-8658-2382f40eea78.png)

**Comment by NotWoods** [comment]
Are you using a custom launcher?

**Comment by pwd-github** [comment]
T9 Launcher (https://play.google.com/store/apps/details?id=se.dw.rocketlauncher) on both devices.

**Comment by NotWoods** [comment]
I'll investigate. My hypothesis is that T9 Launcher does not report that it supports shortcuts, and we hide the menu option in that case.

**Comment by pwd-github** [comment]
Hi @NotWoods , any news on this? Is it indeed a launcher issue? Is there any way to override that from Fenix? Is there something I should send to the launcher developer to ensure proper support for future releases?

**Comment by TitanNano** [comment]
@pwd-github you can try setting your default Launcher to the stock Launcher of your device. If the options appear after restarting Fenix then it is indeed an issue with the launcher. I'm also fairly certain that it is an issue with the launcher as I experienced the same problem myself before.

**Comment by NotWoods** [comment]
Apologies for taking a while. I confirmed T9 Launcher doesn't support shortcuts at all. I recommend using a different launcher or filing a feature request with the T9 devs.
