### ISSUE TITLE
Cold startup regression in `Glean.initialize`: method regressed 100%

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#7617]
Being addressed by Glean team in https://bugzilla.mozilla.org/show_bug.cgi?id=1609052#c1.

---

In my profile from 12/31, Glean.initialize takes 51ms on my Pixel 2. In two profiles I've taken today – Jan 10. – Glean.initialize takes 108ms and 110ms. Most of the time is spent in `flushQueuedInitialTasks` (69.64ms in the larger profile) which calls `joinBlocking`. In my previous profile, `joinBlocking` only takes 4ms.

![Screen Shot 2020-01-10 at 18 35 30](https://user-images.githubusercontent.com/759372/72197606-00f17c80-33d8-11ea-8e71-699e0541cc31.png)

---

@Dexterp37 Were there any recent changes to Glean that could have caused this?

**Comment by Dexterp37** [comment]
> 
> 
> In my profile from 12/31, Glean.initialize takes 51ms on my Pixel 2. In two profiles I've taken today – Jan 10. – Glean.initialize takes 108ms and 110ms. Most of the time is spent in `flushQueuedInitialTasks` (69.64ms in the larger profile) which calls `joinBlocking`. In my previous profile, `joinBlocking` only takes 4ms.

Before the Glean SDK is initialize, if something attempts to record a value in a Glean metric, we [enqueue the measurement](https://mozilla.github.io/glean/book/user/general-api.html#behavior-when-uninitialized). The `flushQueuedInitialTasks` function is called right after the Glean SDK is initialized to execute any previously enqueued operation.

If that's getting slow, some component is probably trying to accumulate a bunch of things before the Glean SDK initializes.

Are you able to consistently reproduce this locally? Maybe we can check what's being enqueued.

> @Dexterp37 Were there any recent changes to Glean that could have caused this?

Not that I can think of, no. @mdboom , clues?

**Comment by mdboom** [comment]
I agree with @Dexterp37 that nothing has changed here, but maybe Fenix is now doing more metric recording prior to initialization than it used to?

**Comment by mcomella** [comment]
@Dexterp37 It has occurred in 5 of the profiles I took today: at minimum, it was ~80ms and at maximum 386ms but usually around 100ms.

Do you think your team can look into this? My team can assist you with using the profiler, if it's helpful. In `flushQueuedInitialTasks`, it looks like we are blocking the main thread waiting for async tasks to complete: instead of blocking, can we do the work following the `join()` on a background thread or reacquire the main thread when needed? If not, maybe we can do all of this work after startup?

**Comment by Dexterp37** [comment]
> 
> 
> @Dexterp37 It has occurred in 5 of the profiles I took today: at minimum, it was ~80ms and at maximum 386ms but usually around 100ms.
> 
> Do you think your team can look into this? My team can assist you with using the profiler, if it's helpful. In `flushQueuedInitialTasks`, it looks like we are blocking the main thread waiting for async tasks to complete: instead of blocking, can we do the work following the `join()` on a background thread or reacquire the main thread when needed? If not, maybe we can do all of this work after startup?

I just filed https://bugzilla.mozilla.org/show_bug.cgi?id=1609052 to look into that. It will be my priority.

**Comment by mcomella** [comment]
I'm going to dupe this investigation to #7746 because the upstream issue this was tracking was closed. However, after this patch and few others landed, `Glean.initialize` seems to take more time overall. However, this may not be affected by the upstream patch and this could be confounded by:
* `Glean.initialize` was moved much earlier in App.onCreate
* I assume we received many changes when Glean was bumped to SDK 24: there may have been other regressions

**Comment by Dexterp37** [comment]
>     * I assume we received many changes when Glean was bumped to SDK 24: there may have been other regressions

Not really :-) However the changelog is available [here](https://github.com/mozilla/glean/releases).
