### ISSUE TITLE
[Bug] Fenix does not give option of Adobe Acrobat on downloading a pdf

### ISSUE THREAD

**Issue by Cheap-Skate** [mozilla-mobile/fenix#7619]
(Possibly related  #6656?)

## Steps to reproduce
1) Install Adobe Acrobat
2) In Fenix, navigate to https://www.volkswagen.co.uk/assets/common/pdf/pricelists/up-pricelist.pdf and download the pdf. 
3) After download, tap Fenix's "open file" dialog or whatever it's called

### Expected behavior
Fenix should show Adobe Acrobat as one of the apps which can open pdf files, along with "Just Once" or "Always" options.

### Actual behavior
Fenix does not show Adobe Acrobat as one of the apps which can open pdf files, on my phone it just shows Nova Launcher and WPS Office, but not Acrobat

### Device information
Galaxy S7, Android 9.0
* Fenix version: Today's

![Screenshot_20200111-121530_Firefox Nightly](https://user-images.githubusercontent.com/40568887/72204121-62632b00-346c-11ea-988e-9119c212f617.jpg)

![Screenshot_20200111-121537_Android System](https://user-images.githubusercontent.com/40568887/72204126-6c852980-346c-11ea-87a8-ad7f79fc2539.jpg)

**Comment by sv-sdeiac** [comment]
Hello @Cheap-Skate , I tried to reproduce this issue but I wasn't able. The Adobe Acrobat reader is on the "open with" list. Can you retry with the latest version of Firefox Preview Nightly? 
Also, if you have some specific options on your Firefox, let us know. 

Build: Firefox Preview Nightly 1/13 #20130605.
Devices:
- Nokia 6 (Android 7.1.1);
- Motorola Moto G6 (Android 8);
- Samsung Galaxy Note 8 (Android 9);
- Google Pixel (Android 9).

**Comment by Cheap-Skate** [comment]
Seems fixed for me too in today's nightly thanks!
