### ISSUE TITLE
[Bug] If you enter reader mode and switch apps, scroll position jumps upwards

### ISSUE THREAD

**Issue by nyanpasu64** [mozilla-mobile/fenix#7623]
## Steps to reproduce
- Visit https://kyren.github.io/2018/09/14/rustconf-talk.html
- Enter reader mode and scroll to bottom.
- Open Android recent apps menu, return to Firefox Preview

Note that in reader mode, this particular page overflows the right side of the screen and causes the entire page to scroll to the right. Some pages do this in regular mode, reader mode, or both. Is this a bug?

### Expected behavior
No change in page rendering, nor change to scroll position.

### Actual behavior
Rendering is paused for 2 seconds. Portions of the page outside of the current viewport, and possibly the bottom half of the screen, contain no text and only the background color. If you scroll the page during this time period:

- Off-screen part of the screen is blank for the remainder of 2 seconds.
- Page jumps upwards to around 40% of the way down.
- If you went into Settings/Accessibility and enabled "Zoom on all websites", then zoomed out on reader mode before reproducing this bug, the page will momentarily return to 100% zoom (same time as jumping upwards) before reverting to zoomed out.

### Device information

* Android device: Moto g5 plus, Android 8.1.0
* Fenix version: Firefox Preview Nightly, 200111 18:21, Build #2011111826, Saturday 1/11 @ 6:26 PM

**Comment by igalic** [comment]
this only happens for me if Firefox crashes or is otherwise restarted

**Comment by nyanpasu64** [comment]
Seems to no longer occur.
