### ISSUE TITLE
Bottom URL Bar that minimizes itself when scrolling down.

### ISSUE THREAD

**Issue by ClemGame** [mozilla-mobile/fenix#7626]
Bottom URL Bar that minimizes itself when scrolling down.
When the position of the bar is set to top, this feature is already implemented.
However, it would be really great, if there were an option to get the same affect when the position is set bottom, too.

**Comment by cadeyrn** [comment]
Duplicate of #4383.

**Comment by ClemGame** [comment]
Oh, sorry.
