### ISSUE TITLE
[Bug] Crash when entering sync password

### ISSUE THREAD

**Issue by andreicristianpetcu** [mozilla-mobile/fenix#7629]
## Steps to reproduce
https://vimeo.com/384360861
### Expected behavior
not crash
### Actual behavior
crash
### Device information
OnePlus 5t

* Android device: ?
* Fenix version: ?

**Comment by xscd** [comment]
I guess this is a duplicate of https://github.com/mozilla-mobile/fenix/issues/7625

**Comment by sv-ohorvath** [comment]
Closing as dupe. If it's not, please reopen.
