### ISSUE TITLE
[Bug]Multiple taps are needed to open an article on https://mobile.reuters.com/

### ISSUE THREAD

**Issue by softvision-sergiulogigan** [mozilla-mobile/fenix#7635]
**Browser / Version**
Firefox Preview Nightly 200112 (🦎 74.0a1-20200110095023)

**Operating System**
Samsung Galaxy S8 (Android 9) - 1440 x 2960 pixels, 18.5:9 ratio (~570 ppi density)

**Steps to reproduce:**
1. Navigate to: https://mobile.reuters.com/
2. Tap on an article link from a section (eg. Featured section).

**Expected Behavior:**
The article is opened.

**Actual Behavior:**
Nothing happens.

**Notes:**
1. Screenshot attached.
2. Taping multiple times on the article, opens it.

**Watchers:**
@softvision-oana-arbuzov
@softvision-sergiulogigan
@cipriansv

![Screen capture](https://user-images.githubusercontent.com/16573771/72242994-59509600-35f3-11ea-8bea-cf45700aa111.gif)

**Comment by softvision-sergiulogigan** [comment]
This doesn't seem to be related to ETP, since the issue is reproducible winth ETP Strict, Standard and Off.

**Comment by LaurentiuApahideanSV** [comment]
Verified as fixed on Firefox Preview Nightly 201215 (Build #2015781483) using a Samsung Galaxy S9 (Android 8.0.0).
