### ISSUE TITLE
[Bug]The page is no longer loaded when switching from ETP Strict to Standard and viceversa

### ISSUE THREAD

**Issue by softvision-sergiulogigan** [mozilla-mobile/fenix#7636]
**Browser / Version**
Firefox Preview Nightly 200112 (🦎 74.0a1-20200110095023)

**Operating System**
Samsung Galaxy S8 (Android 9) - 1440 x 2960 pixels, 18.5:9 ratio (~570 ppi density)

**Steps to reproduce:**
1. Navigate to: https://mobile.reuters.com/
2. Tap the Shield button.
3. Tap the Protection Settings option.
4. Tap the Standard radio button.
5. Tap Back.

**Expected Behavior:**
The page is refreshed and loaded.

**Actual Behavior:**
The page is refreshed, but never fully loads.

**Watchers:**
@softvision-oana-arbuzov
@softvision-sergiulogigan
@cipriansv

**Comment by Amejia481** [comment]
The same happens with other sites like cnn.com, it looks like the issue happens with sites that have trackers blocked

**Comment by Amejia481** [comment]
This is `GeckoView` issue I opened a bug on Bugzilla for it. 
https://bugzilla.mozilla.org/show_bug.cgi?id=1609701

**Comment by Amejia481** [comment]
I tested on the latest Nightly, it looks is fixed. Let's wait for QA verification to be sure.

![image](https://user-images.githubusercontent.com/773158/73760838-ecd13e80-473b-11ea-85b2-a417398c594a.png)

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **Nightly Build #20360606 from 2/5** using the following devices:

• Google Pixel 3a XL (Android 10)
• Google Pixel 3a  (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7.0.0)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

► Video
![20200205_091930](https://user-images.githubusercontent.com/51314259/73820059-86aaf100-47f9-11ea-90a0-32d3973629c5.gif)
