### ISSUE TITLE
Fenix not reporting correct web site to OS

### ISSUE THREAD

**Issue by RichyHBM** [mozilla-mobile/fenix#7638]
Fenix doesn't seem to report the current website, which leads to password managers not being able to correctly determine which login to use without user input

**Comment by kbrosnan** [comment]
Which password manager do you use? If it is lastpass we have [1491989](https://bugzilla.mozilla.org/show_bug.cgi?id=1491989) which will be fixed when Fenix uses Gecko 73.

**Comment by RichyHBM** [comment]
Yes, it is lastpass that I'm using

**Comment by RichyHBM** [comment]
I just looked and I'm using Fenix Nightly (from play store) version 200114 06:01 that includes Gecko 74.0a1 and it is still occurring

**Comment by ekager** [comment]
Could you possibly give us more exact STR so we can investigate this? Which website/login URL? So we can try to reproduce this

**Comment by RichyHBM** [comment]
It happens on twitter if thats any help? To mention, lastpass can input email/password into the fields, but it doesn't recognise that I am on twitter.com

**Comment by ekager** [comment]
@RichyHBM I can reproduce and seems to only be a problem with LastPass and only a problem with Nightly :/ I can try reaching out to their eng team, thanks for alerting us!

**Comment by RichyHBM** [comment]
If it's just a nightly issue then I'm not as worried! Though hopefully it won't make it into "stable"

**Comment by sv-ohorvath** [comment]
I also noticed Dashlane not recognizing the website and not suggesting any auto-fill options on Nightly and Beta 4.0, on a Nexus 9 (Android 7.1.1)
