### ISSUE TITLE
[Bug] The product specification selection menu at colorel.ca requires double tap

### ISSUE THREAD

**Issue by LaurentiuApahideanSV** [mozilla-mobile/fenix#7640]
## Steps to reproduce
1. Go to https://colorel.ca;
2. Select any product that has specifications such as https://colorel.ca/collections/sachets-pochettes/products/sacs-satin;
3. Tap the Color or Size.
### Expected behavior
Tapping once should open the selection menu
### Actual behavior
A double tap is required to open the selection menu
### Device information

* Android device: OnePlus 6T (Android 9)
* Fenix version: 
Firefox Preview Nightly 200113 (Build #20130606) GV: 74.0a1-20200110095023
Firefox Release 68.4.1 Beta 68.5b1 see issue https://bugzilla.mozilla.org/show_bug.cgi?id=1608675

**Comment by ekager** [comment]
Can't repro. Closing
