### ISSUE TITLE
Improve performance of HomeActivity.setupToolbarAndNavigation

### ISSUE THREAD

**Issue by emalysz** [mozilla-mobile/fenix#7642]
### Why/User Benefit/User Problem
It is slow to create the HomeActivity. 
8.7% of `HomeActivity.onCreate` is spent in `HomeActivity.setupToolbarAndNavigation`. 

### Acceptance Criteria (how do I know when I’m done?)
-The time it takes to set up the toolbar is reduced.

________________________
The majority is spent in ThemeManager.ApplyStatusBarTheme

**Comment by mcomella** [comment]
@emalysz Will this issue be invalidated by your work in #7473? If so, please close!

**Comment by emalysz** [comment]
Closing as a duplicate of #7473
