### ISSUE TITLE
[Bug] No checkbox in language settings

### ISSUE THREAD

**Issue by marcinwiacek** [mozilla-mobile/fenix#7643]
## Steps to reproduce

1. Settings
2. Language
3. select smth other than "follow device language" (for example Polish)
4. click back arrow
5. language

### Expected behavior

in menu visible in step 5 there is displayed checkbox on option select in step 3

### Actual behavior

checkbox is not displayed

### Device information

* Android device: pixel (android 10), s7 (android 8)
* Fenix version: nightly 13 jan

**Comment by cadeyrn** [comment]
see also https://github.com/mozilla-mobile/fenix/issues/220#issuecomment-571490295.

**Comment by marcinwiacek** [comment]
ok, here you're right, my bad. Do we want to have separate bug or not?
