### ISSUE TITLE
Disable Push support when Fennec is migrating

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/fenix#7645]
Stop push when migrating.

### QA testing STR:
1. Ensure Send Tab is working on Fennec.
2. Migrate to Fenix.
3. Send another tab.

### Expected:
At 3, the tab should be delivered.

**Comment by st3fan** [comment]
@jonalmeida can we close this or move it to QA? (Is it verifiable by QA?)

**Comment by jonalmeida** [comment]
Add the label as soon as the patch lands. 👌

**Comment by ebalazs-sv** [comment]
@jonalmeida I had tested this on Release, Beta, Nightly migration builds 01/15 with Samsung Galaxy S8 (Android 9), Huawei Honor 8 (Android 7.0), Xiaomi Mi4i (Android 5.0.2), following the steps:
1. On Fennec Release open a page and go to Menu -> Settings -> Share -> Fennec Nightly;
2. Replace Fennec Nightly with Fenix Nightly;
3. On Fennec Release open a page and go to Menu -> Settings -> Share -> Fenix Nightly;
4. Observe the tab received on Fenix Nightly.

The tab sent from Fennec to Fenix is received.
I had tested this also from sending tabs from Nightly to Release.

Is this the required testing scenario? Thanks!

**Comment by jonalmeida** [comment]
@ebalazs-sv 

At step 4, did you have to open the app to see the tab appear?

If the app is in the background or in foreground already, you should see the tab appear. If it appears by switching between the two then that would mean we didn't receive the tab from push, but by a sync when the app is in the foreground.

**Comment by ebalazs-sv** [comment]
At step 4 the tab appear, I don't have to switch between the apps. Is this correct?

**Comment by jonalmeida** [comment]
> At step 4 the tab appear, I don't have to switch between the apps. Is this correct? Thank you!

To clarify, the tab should appear without having to bring Fenix to the foreground after the tab is sent.

**Comment by ebalazs-sv** [comment]
> To clarify, the tab should appear without having to bring Fenix to the foreground after the tab is sent.
Yes, the tab appear without having to bring Fenix to the foreground after the tab is sent.
I will move this to Done. Thanks!

**Comment by jonalmeida** [comment]
Closing since this is verified.

**Comment by ebalazs-sv** [comment]
This was verified as fixed in my previous comment, so I will move this to Done. Thanks!
