### ISSUE TITLE
[Bug] Theme is not updated after resuming app

### ISSUE THREAD

**Issue by marcinwiacek** [mozilla-mobile/fenix#7646]
## Steps to reproduce

1. open Firefox and setup theme "according to device theme"
2. switch to system Settings (Android Settings app)
3. change Theme (dark to white or white to dark)
4. switch to Firefox

### Expected behavior

theme is updated

### Actual behavior

it's required to kill and start Firefox again

### Device information

* Android device: 10 on Pixel
* Fenix version: Nightly 13 jan

**Comment by ekager** [comment]
@marcinwiacek can you still repro this?
