### ISSUE TITLE
[Bug] Browser engine list is not updated without restarting FP

### ISSUE THREAD

**Issue by marcinwiacek** [mozilla-mobile/fenix#7648]
## Steps to reproduce
1. change language in Settings from "follow device language" to some other
2. go into settings for browser engines
3. kill FP
4. open again FP and settings for browser engines

### Expected behavior
list in 2 == list in 4
### Actual behavior
list is updated after full app restart
### Device information

* Android device: Android 10 / Pixel
* Fenix version: nightly 13 jan

**Comment by ekager** [comment]
Can repro
