### ISSUE TITLE
Add to homescreen icon will not be consistent with Firefox Desktop

### ISSUE THREAD

**Issue by NotWoods** [mozilla-mobile/fenix#7653]
### Why/User Benefit/User Problem
Originally reported by @FluorescentHallucinogen:

Since the add to homescreen icon depicts a phone, it will not be consistent with the icon we eventually use on Firefox Desktop when PWA support is added.

### Acceptance Criteria (how do I know when I’m done?)
- Display an icon that can be consistent across platforms

**Comment by NotWoods** [comment]
cc @apbitner

**Comment by apbitner** [comment]
@shorlander You okay with this?

**Comment by FluorescentHallucinogen** [comment]
Here's the icon I propose:

![pwa-install-icon](https://user-images.githubusercontent.com/7892779/72325980-502cfb00-36bf-11ea-9ca9-76e6b299e0e8.png)

What do you think about it?

This icon is platform agnostic. Please take a look at https://crbug.com/977943 to learn more what's wrong with A2HS/Install icons in various browsers (including Firefox).

**Comment by shorlander** [comment]
> @shorlander <https://github.com/shorlander> You okay with this?
> 
Potentially.

For some context behind the current icon: the reason for including the device is to add context that installing a PWA will put it on your device home screen, not your browser home screen. We’ve seen some confusion around what installing a PWA means, and where they will end up.

I don’t think we know what PWA support will look like in Desktop Firefox yet, so it’s hard to say if the same metaphor will work in all cases. For example on macOS a possible place for the PWA icon to end up is the Dock and on the Taskbar on Windows, which are not the same as a phone home screen grid.

**Comment by brampitoyo** [comment]
Based on the facts that:

- The macOS dock, Windows taskbar and Firefox homescreen all look different than the Android homescreen
- We don’t yet know the shape of PWA in Firefox for Desktop

I recommend keeping our existing icon.

When we implement PWA in Firefox for Desktop, we will have another look at our Android icon and see whether it needs to be updated.
