### ISSUE TITLE
[Bug] Settings descriptions are not updated after changing language (without app reboot)

### ISSUE THREAD

**Issue by marcinwiacek** [mozilla-mobile/fenix#7654]
## Steps to reproduce
1. settings
2. change language to other (in my case Polish)
3. change language to "follow device language" (in my case English)

### Expected behavior

strings in settings are updated

### Actual behavior

updating info in Theme and Toolbar needs app restart

on the example visible screen after step 3 (two strings in Polish)

![Screenshot_20200113-201552 1](https://user-images.githubusercontent.com/24834168/72284945-6ba5f080-3642-11ea-878c-90154674cd1a.png)

### Device information
* Android device: Pixel / Android 10
* Fenix version: nighlty 13 jan

**Comment by cadeyrn** [comment]
This is also #7559, see https://github.com/mozilla-mobile/fenix/issues/7559#issuecomment-572774124.

**Comment by marcinwiacek** [comment]
@cadeyrn , hmmm, you're right - should we have separate bugs or not?
