### ISSUE TITLE
Use UTF-8 strings instead of percent encoded strings for URLs in the link menu and URL bar and other places

### ISSUE THREAD

**Issue by marcinwiacek** [mozilla-mobile/fenix#7657]
## Steps to reproduce

1. search for "łąka" in Google

### Expected behavior

URLs are displayed in nice Unicode decoded form (human-friendly) like in desktop

![ff1](https://user-images.githubusercontent.com/24834168/72286901-62b71e00-3646-11ea-872e-0789b2404e36.png)
![ff2](https://user-images.githubusercontent.com/24834168/72286907-65197800-3646-11ea-8457-de0985854c61.png)

### Actual behavior

![Screenshot_20200113-203239 1](https://user-images.githubusercontent.com/24834168/72286929-6f3b7680-3646-11ea-8b80-b390d473e4cd.png)
![Screenshot_20200113-203224 1](https://user-images.githubusercontent.com/24834168/72286939-76fb1b00-3646-11ea-8b17-75f8b738dcb3.png)

### Device information

* Android device: android 10/pixel
* Fenix version: nightly 13 jan

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-15173)

**Comment by marcinwiacek** [comment]
The same happens in URL bar, I've modified title, thx.

**Comment by mcarare** [comment]
Note: Firefox & Chrome have the same behaviour.

**Comment by marcinwiacek** [comment]
I don't agree with last comment - just double checked between FP and Canary.

**Comment by marcinwiacek** [comment]
![Screenshot_20200114-113740_Chrome Canary](https://user-images.githubusercontent.com/24834168/72337216-7acc8300-36c2-11ea-96d0-ff835a7006b9.jpg)
![Screenshot_20200114-113805_Firefox Nightly](https://user-images.githubusercontent.com/24834168/72337219-7d2edd00-36c2-11ea-8478-41b7ee78505d.jpg)

URL bar behaves the same (differently), please be more careful in checking.

**Comment by marcinwiacek** [comment]
jan 13 - info about link menu

jan 13 - The same happens in URL bar, I've modified title, thx.

jan 14 - Firefox & Chrome have the same behaviour (comment is generic)

jan 14 - here are screenshots showing some diffs (info in url bar component area is different)

@mcarare - you're not right, although screens show something opposite.

**Comment by Keritial** [comment]
Any progress? Chrome is displaying in the decoded form now.

![Screenshot_2022-10-03-13-30-28-25_984e1414ae90666a90f12ff17ec14a7f](https://user-images.githubusercontent.com/50075277/193510403-93c123dd-800c-477a-b7f1-a0b02952f059.jpg)
![Screenshot_2022-10-03-13-30-57-63_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/50075277/193510406-688c2395-206b-4432-8815-19ae79980ba9.jpg)
![Screenshot_2022-10-03-13-52-49-64_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/50075277/193510412-7db47da0-686a-4c11-a31c-32068a82fa96.jpg)
![Screenshot_2022-10-03-13-53-09-62_984e1414ae90666a90f12ff17ec14a7f](https://user-images.githubusercontent.com/50075277/193510414-54d65a7b-3648-40ec-b983-82a8fdb556d0.jpg)

**Comment by kisaragi-hiu** [comment]
The URL in the address bar is supposed to be human-readable. This issue affects not just `Feature:ContextMenu`, but also `Feature:Toolbar`.

"Save link as" already uses the decoded form. This should be applied to the address bar and the context menu.

<details>
<summary>Firefox on Linux</summary>
<img src="https://user-images.githubusercontent.com/11722318/205116244-593397c5-01cf-41c1-8909-2a71aac0f035.png">
</details>

<details>
<summary>GNOME Web (Epiphany)</summary>
<img src="https://user-images.githubusercontent.com/11722318/205116218-ac1534f2-48f2-4720-bf2c-b3e16a0d755b.png">
</details>

<details>
<summary>Chromium on Linux</summary>
<img src="https://user-images.githubusercontent.com/11722318/205116233-ab284222-bcc9-4124-8fc9-0d1e3bfb8722.png">
</details>

<details>
<summary>Chrome 103 on Android</summary>
<img src="https://user-images.githubusercontent.com/11722318/205117713-93c53131-aea1-4856-9e21-fc8156937c9b.png">
</details>

The context menu in Chrome, as [Keritial](https://github.com/Keritial) has noted, is also now human-readable.

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1809292

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
