### ISSUE TITLE
[Bug] Using blue dot only in special occassions

### ISSUE THREAD

**Issue by marcinwiacek** [mozilla-mobile/fenix#7659]
## Steps to reproduce

Open FP and open various sites

### Expected behavior

Use "blue dot" notification only in very rare occasions - for example, when new feature is added.

### Actual behavior

Currently many times there is displayed blue dot on the hamburger menu icon - the same blue dot it displayed for "add to home screen" or "reader view" menu options.

Blue dot normally is used for important warnings or new features - if it's used for almost every occassion, user is not reacting on it or it's annoying for user.

### Device information

* Android device: s7/android 8
* Fenix version: nightly 13 jan

**Comment by vesta0** [comment]
This was addressed in #8474. Thanks for filing @marcinwiacek
