### ISSUE TITLE
[Bug] Don't propose "add to home screen" when it was done already

### ISSUE THREAD

**Issue by marcinwiacek** [mozilla-mobile/fenix#7660]
## Steps to reproduce

1. do "add to home screen" for some url
2. try to do "add to home screen" again for the same url

### Expected behavior

menu option is not displayed, when url was added already. if detecting is not possible, please at least don't display blue dot info for such menu option...

### Actual behavior

blue dot notification for this menu option (add to home screen).

### Device information

* Android device: 10/pixel
* Fenix version: hightly 13 jan

**Comment by liuche** [comment]
If a user has already added a site as a PWA, the correct thing to do would be to not show that notification anymore.

Do we have a bug explaining when the blue dot should show, or whether this was a short-term solution?

**Comment by apbitner** [comment]
@liuche I don't believe we planned on hiding this menu option if the PWA is already installed, similar to how we don't hide 'Add to Home screen' if the site has been already saved. However, the latter doesn't surface the blue dot, so it probably would be a good idea to hide 'Install' if the PWA has already been installed.
