### ISSUE TITLE
[Bug] Loading about:config on android Andreno3xx causes browser to crash

### ISSUE THREAD

**Issue by ktaeleman** [mozilla-mobile/fenix#7662]
Copied from original bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1608906

## Steps to reproduce
Enable webrender through about:config (gfx.webrender.enabled = true). 
Also gfx.webrender.compositor is also set to true.

Navigate to about:config

### Expected behavior
Does not crash

### Actual behavior
Crashes

### Device information

* Android device: Lg phoenix plus android phone running android 9 gpu Adreno308.
* Fenix version: nightly

**Comment by ktaeleman** [comment]
User that originally reported the issue says that the issue was fixed with the latest update, might not be related to webrender.

**Comment by ekager** [comment]
Closing because this sounds like it could have been resolved and the Bugzilla bug is the right place to discuss this
