### ISSUE TITLE
[Bug] Internal page(s) are marked as insecure

### ISSUE THREAD

**Issue by marcinwiacek** [mozilla-mobile/fenix#7663]
## Steps to reproduce

open about:config

### Expected behavior

internal page is marked as secure

### Actual behavior
![Screenshot_20200113-231237_Firefox Nightly](https://user-images.githubusercontent.com/24834168/72296690-87b58c00-365a-11ea-8ca7-ee637b77890e.jpg)

### Device information

* Android device: android 8 / s7
* Fenix version: nightly 13jan

**Comment by cadeyrn** [comment]
Duplicate of https://github.com/mozilla-mobile/android-components/issues/4156 (there are also already some duplicates in the Fenix repository but these are all marked as duplicate of https://github.com/mozilla-mobile/android-components/issues/4156).
