### ISSUE TITLE
[Bug] [a11y] Text contrast - consider increasing contrast ratio

### ISSUE THREAD

**Issue by softvision-miralobontiu** [mozilla-mobile/fenix#7669]
## Prerequisites
1. Make sure you have Google Accessibility Scanner installed.
2. Have a freshly installed build or a clean profile.

## Steps to reproduce
1. Launch Fenix.
2. Using the Accessibility Scanner scan the Onboarding page.

### Expected behavior
There are no suggestions to make any changes.

### Actual behavior
There is a suggestion to consider increasing the "Adapts to your device settings" item's text foreground to background contrast ratio - as seen in the screenshot below.

### Device information
* Android device: Samsung Galaxy Tab S3 (Android 8)
* Fenix version: RC 3.0.2, Beta build 3.1.0-beta 3, Nightly build from 01/14

![Screenshot_20200114-112302_Accessibility Scanner](https://user-images.githubusercontent.com/40694158/72331367-c41bd300-36c0-11ea-9429-66be8e446fe1.jpg)

**Comment by sblatz** [comment]
UX: Can we get a color that works for high contrast.

**Comment by sblatz** [comment]
@apbitner should this just be the "primary text" color?

**Comment by apbitner** [comment]
The background of the onboarding cards will be changing to white which should resolve this issue - https://github.com/mozilla-mobile/fenix/issues/7606

**Comment by brampitoyo** [comment]
With the onboarding card background changing to white, this issue can now be closed. If that’s incorrect, feel free to reopen it.
