### ISSUE TITLE
The "Sign In" icon is displayed when switching between "Private" and "Normal" browsing

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/fenix#767]
## Steps to reproduce
1. Install and launch Fenix.
2. Observe the **`sign in`** icon after first launch below **`Today`** word.
3. Open few websites on normal browsing and private browsing.
4. Tap on the switch button to navigate between normal and private browsing.
### Expected behavior
The current session is displayed correctly with all opened websites and no extra elements are displayed while switching from normal to private browsing.
### Actual behavior
The first page is displayed under currently opened websites while switching from **`normal`** to **`private`** browsing.
### Device information

* Android device: **`Samsung Galaxy Note 9 (Android 8.1.0), Google Pixel 3(Android 9/P)`**.
* Fenix version:  **`1.0.1909 (Build #10591638 🦎 67.0a1-20190227104426)`**.

### Notes
For more details please see the attachments:
[video](https://drive.google.com/file/d/1kSxKA58lpQvxxAsgo45_3HJnEi1odOls/view?usp=sharing)
![download](https://user-images.githubusercontent.com/42831109/53642974-9d38e780-3c3b-11e9-8024-1d430fdd2442.png)

**Comment by levisacal** [comment]
(fire) (fire) (fire) (fire) (fire)

**Comment by sblatz** [comment]
I believe this is fixed now! Please re-open if you're still encountering it.
