### ISSUE TITLE
[Bug] Firefox crashes on login to sync

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#7671]
## Steps to reproduce
(On a fresh install)
Click Sign in to Firefox
Use Email instead
Enter email and password 
### Expected behavior
login to sync
### Actual behavior
crash
### Device information

* Android device: Asus Zenfone M1
* Fenix version: Nightly 200112 18:01 (Build #20121807)

**Comment by s-ankur** [comment]
Difficult to replicate but does happen a few times

**Comment by kbrosnan** [comment]
It would be helpful to get a crash log when this happens. https://github.com/mozilla-mobile/fenix/wiki/Logging-Crash-Information

**Comment by ekager** [comment]
QA - does this sound familiar or do we think we can close?

**Comment by AndiAJ** [comment]
Hi, a more recent Sync crash that I'm aware of was regarding the sign out #6663 but wasn't reproduced lately on the Nightly builds.

Nevertheless, I re-check the above mentioned issue on the latest **`Nightly Build #20310607 from 1/31`** using the following devices:

• Google Pixel 3a (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

Signed in 3x on each device and didn't encounter any crash.
**I'll go ahead an close this issue.**
