### ISSUE TITLE
[Bug] 'Reconnect to Sync' doesn't reconnect despite successful login

### ISSUE THREAD

**Issue by DobaKung** [mozilla-mobile/fenix#7674]
## Steps to reproduce
1. Open _Settings_ page
2. Tap _Reconnect to resume syncing_
3. Tap _Sign in to reconnect_
4. Enter valid credentials
5. Tap _Sign in_ button
6. Tap X (close) button

### Expected behavior
Firefox Preview is connected to my account and resumes syncing

### Actual behavior
Firefox Preview doesn't connect to my account. 'Reconnect to resume syncing' notice persists.

### Device information

* Android device: Huawei P10 with Android 9.0
* Fenix version: 3.0.2 (Build 20081833)

**Comment by ekager** [comment]
Are you still seeing this issue @DobaKung ?

**Comment by DobaKung** [comment]
I haven't experienced the issue again since I completely signed it out. The synchronisation, though, is quite slow. I'm not sure if I should close this issue 🙋‍♂️
