### ISSUE TITLE
GeckoSession is resumed before keyboard is hidden after URL bar has been focused

### ISSUE THREAD

**Issue by jamienicol** [mozilla-mobile/fenix#7675]
I recently fixed #7338 (https://bugzilla.mozilla.org/show_bug.cgi?id=1588581). This was where when opening a page in a new tab in Fenix with webrender enabled, the portion of the screen where the keyboard used to be would remain black until the first paint (this could last a few seconds for the page to load).

The problem was that when the URL bar is focused (either by clicking on it directly from a page, or from the tab switcher) Fenix shows a full-screen view (for eg search suggestions). This means the GeckoSession is paused. Then, when either dismissing the keyboard with the back button, or hitting enter to go to a new URL, the GeckoSession seems to be resumed whilst the keyboard is still visible. Then a split-second later the keyboard gets hidden.

This meant that webrender would do a render at half screen-size upon Resume, then the window would be resized to full screen almost immediately, leaving a black gap where the keyboard was, but we wouldn't render again until after the page had loaded. I fixed this by forcing a render immediately upon the resize, which helps a lot. But we still render a frame at half-size first, which causes a slight flicker effect. This remaining part of the bug affects both webrender and non-webrender.

I suspect it might be possible to fix this on Fenix's end. If it is possible to delay resuming the GeckoSession until *after* the keyboard has been hidden, then we would only have to render once at full-screen when resuming. Happy to have a go at implementing this myself, but would appreciate any pointers on where to get started.

**Comment by jamienicol** [comment]
Note when I talk about GeckoSession being paused/resumed, I'm not 100% sure if that's exactly the relevant thing. GeckoSession.onSurfaceChanged() is the function that I know is being called too early, as that leads directly to rendering. This is called from the SurfaceView listener. So maybe I should actually be saying "the SurfaceView becomes visible before the keyboard is hidden" which might be subtly different than the GeckoSession being resumed.

**Comment by ekager** [comment]
@jamienicol I think we can close this issue now?

**Comment by jamienicol** [comment]
Yep, this no longer seems to be an issue.
