### ISSUE TITLE
[Bug] Selecting the current device language from the language list, moves the selection to Follow system language

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#7679]
## Steps to reproduce
1. Set device language to EN-US/or Spanish (Espana), for example.
2. In Fenix, go to Settings>Language and select  EN-US/or Spanish (Espana) from the list.
3. Exit and return to the language menu.
4. Observe the selection.
### Expected behavior
The selection of EN-US/or Spanish (Espana) language is marked as selected.
### Actual behavior
The default Follow device language is selected again. The app should keep the specific selection in case the device language is changed.
### Device information

* Android device: Nexus 9 (Android 7.1.1)
* Fenix version: Beta 3.1.0 beta3

**Comment by alexandru-io** [comment]
Guys, this is [failing fenix ](https://treeherder.mozilla.org/#/jobs?repo=fenix&searchStr=rap&fromchange=8a7c7fd06f16c9610b056e971f467de6b91af2ad). Could you back this out or fix ASAP? Thanks! @BranescuMihai @sv-ohorvath

**Comment by BranescuMihai** [comment]
After discussing with @alexandru-io, it seems the problem is fixed. So this bug is good to be picked up for testing:)

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly Build #20310607 from 1/31`** using the following devices:

• Google Pixel 3a (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

► Video
![20200131_150007](https://user-images.githubusercontent.com/51314259/73542788-2bb27c00-443e-11ea-9297-643a88398e32.gif)
