### ISSUE TITLE
[Bug] What's new page for 3.1 opens the 3.0 one

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#7681]
## Steps to reproduce
1. Open the What's new link from the homescreen menu.
### Expected behavior
What's new in 3.1 page.
### Actual behavior
What's new in 3.0 page.
### Device information

* Android device: ?
* Fenix version: Beta 3.1.0-beta3

**Comment by cadeyrn** [comment]
The described actual behaviour is the same behaviour as with previous releases - there was always only a SUMO page for major releases which also contains the enhancements of the previous minor releases.

**Comment by liuche** [comment]
Yes, we only update the "What's new" SUMO page for major versions, but searching on SUMO should show pages for major features that have shipped, or might be nightly-only.
