### ISSUE TITLE
[Bug] (regression) Can't download a new file after a canceled one

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#7682]
## Steps to reproduce
1. Download a medium-large file, to be able to cancel it.
2. Open the notification drawer and cancel it.
3. Try to download a new file.
### Expected behavior
The second download starts. 
### Actual behavior
The second download doesn't start. You need to restart the app.
### Device information

* Android device: Nexus 9 (Android 7.1.1), Nexus 5 (Android 6.0.1)
* Fenix version: Nightly 1/14, Beta 3.1.0-beta3

**Comment by sblatz** [comment]
Downloads why won't you just **let me be** 😠

**Comment by sblatz** [comment]
I'm able to reproduce in sample browser. My first guess (without digging in yet) is that this has something to do with the progress bar I added. I'm guessing the notification system is broken for some reason because of that.

**Comment by sblatz** [comment]
Should be fixed by https://github.com/mozilla-mobile/android-components/pull/5635 in the next nightly.

**Comment by sv-ohorvath** [comment]
Verified as fixed on Nightly 1/20. 
devices: Galaxy S8 (Android 9), Nexus 5 (Android 6.0.1)
