### ISSUE TITLE
[Bug] The error messages have different colors in three-dot menu

### ISSUE THREAD

**Issue by softvision-miralobontiu** [mozilla-mobile/fenix#7684]
## Steps to reproduce
1. Sign into FxA on Firefox Preview on your device. Verify your email, if necessary.
2. Sign in with the same account on Desktop.
3. Change your password on the desktop account.
4. Go to Settings - account on your device and force sync.

### Expected behavior
The three-dot menu turns yellow with a highlighted dot. In the three-dot menu, "Settings" option is displayed on a yellow label. An error message is displayed "Reconnect to resume syncing xxx@yyy" on a yellow label.

### Actual behavior
The three-dot menu turns purple with a highlighted dot. In the three-dot menu, "Settings" option is displayed on a purple label. 
An error message is displayed "Reconnect to resume syncing xxx@yyy" on a yellow label.

### Device information
* Android device: Samsung Galaxy Tab S3 (Android 8), Nokia 6 (Android 7.1.1)
* Fenix version: Beta 3.1.0-beta 3

![Untitled](https://user-images.githubusercontent.com/40694158/72357417-9e5bf180-36f3-11ea-8e44-a4e1f0863ee7.png)

**Comment by sflorean** [comment]
The issue is not reproducible anymore on Nokia 6 (Android 7.1.1) and latest Nightly build.
