### ISSUE TITLE
Freeze (deprecate) the UA string, leading to its removal

### ISSUE THREAD

**Issue by thecodingdude** [mozilla-mobile/fenix#7690]
### Why/User Benefit/User Problem

In line with [Google's intent to freeze the UA string](https://groups.google.com/a/chromium.org/forum/m/#!msg/blink-dev/-2JIRNMWJ7s/yHe4tQNLCgAJ) Firefox Preview should do the same thing

### What/Requirements

Align with Google's timeline for removing the UA string

### Acceptance Criteria (how do I know when I’m done?)

UA strong gone.

**Comment by kbrosnan** [comment]
GeckoView controls the user agent.
