### ISSUE TITLE
[Bug] Unexpected delays in Sync (pointed to spanner)

### ISSUE THREAD

**Issue by tublitzed** [mozilla-mobile/fenix#7695]
## Steps to reproduce

I thought that Sync was broken this AM; looks like it's not, just seems very slow (even to fetch a single bookmark). I'm not seeing an obvious way to force a sync in Fenix (tried pull to refresh, etc), so it's possible that this is simply user error....but I wanted to file a bug anyways as it's something that I could see being easily mistaken for "sync is broken".

To repro:

1. Use an account pointed to spanner (I have _not_ tested against a regular account, so might not matter).
2. Add a bookmark on desktop
3. Sync in desktop
4. Restart Fenix. Still no bookmark. (Mine appeared 30+ mins later)

I _think_ this is new. I have tested (while pointed to spanner) previously and did not see this happening. Bookmarks/etc appeared quickly.

### Expected behavior

1. Sync does not take 30+ mins to transfer a bookmark.
2. Pull to refresh should sync? Or, is there another way we could make it easier to manually sync?

### Actual behavior

1. Sync data does not appear.
2. No clear way to manually sync.

### Device information

* Android device: Tracfone ZTE Blade T2 (Z559DL), android v8.1.0
* Fenix version: 3.0.2

**Comment by rfk** [comment]
> I'm not seeing an obvious way to force a sync in Fenix (tried pull to refresh, etc)

If you go into settings and click on your account, it should show the sync options page with checkmarks for whether to sync bookmarks/history/whatever, and at the top of the page a "sync now" option.

**Comment by tublitzed** [comment]
Thanks, @rfk - manual sync appears to not be delayed either; my test with a bookmark appeared quickly. I'll close this one.
