### ISSUE TITLE
[Bug] Back button should animate to the left before search screen disappears

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#7698]
## Steps to reproduce
1. Open the search screen
2. Press back

### Expected behavior
1. The back button animates to the left (off of the screen) while the rest of the screen transitions

### Actual behavior
1. The back button stays in place while the rest of the screen transitions and then flickers out.

### Device information
* Android device: Galaxy S9 Android 9
* Fenix version: 1/14/20 nightly

**Comment by sblatz** [comment]
Updated animation:

![back_button_animation](https://user-images.githubusercontent.com/4400286/72846363-496d2d80-3c55-11ea-9ebb-b62d6232f8a6.gif)

**Comment by sv-sdeiac** [comment]
Verified as fixed using the latest version of Firefox Preview Nightly 1/28 #20280606.
Devices:
- Nokia 6 (Android 7.1.1);
- OnePlus 5T (Android 9).
