### ISSUE TITLE
Open installed PWAs in fullscreen / standalone mode

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/fenix#770]
### User Story
As a user, I want my installed PWAs to open in fullscreen/standalone mode, so I can enjoy an app-like experience. 

### Dependencies:
https://github.com/mozilla-mobile/android-components/issues/1830

### Acceptance Criteria
- My installed PWAs open in fullscreen/standalone mode.

**Comment by NotWoods** [comment]
A-C supports this, so once PWA support is merged we can close the issue.
