### ISSUE TITLE
MotionLayout home screen performance is very slow on cold startups

### ISSUE THREAD

**Issue by colintheshots** [mozilla-mobile/fenix#7700]
It appears from Marc Leclair's recent SysTrace results that our home screen is loading significantly more slowly in part due to the use of MotionLayouts for hiding the Firefox Preview wordmark image and private browsing mode button. Given the very simple behavior currently being used, we can instead produce this animation using stock CoordinatorLayout behaviors instead. This should also reduce the depth of the layout hierarchy, which already had a CoordinatorLayout parent.

In addition, the bottom bar layout uses a nested ConstraintLayout that could trivially be converted to a LinearLayout or RelativeLayout for an additional speedup.

**Comment by mcomella** [comment]
@MarcLeclair The associated PR was merged: please don't forget to update the bug status!

**Comment by MarcLeclair** [comment]
closed with #8085
