### ISSUE TITLE
Check impact of "is migrated" check on cold startup performance

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#7703]
The data migration will add a temporary check to see if users are already migrated during startup: we should verify this doesn't have a significantly negative impact on startup performance.

**Comment by emalysz** [comment]
After implementing @mcomella 's instrument for tracking startup, the "is migrated" check does not appear to have an impact on cold start performance. This check is within the IntentReceiverActivity's `migrationIntentProcessor`.

To complete this investigation, I collected measurements from 3 startups on a Pixel2, with and without the migration check. The averages for each method (as well as APP_ON_CREATE) all fell within +-15ms. Here were the differences 

+: indicates it took longer with the check
-: indicates it took less time with the check

    APP_ON_CREATE: -5.67ms
    HOME_ACTIVITY_ON_CREATE: +11.33ms
    HOME_ACTIVITY_ON_RESUME: -1.33ms
    HOME_FRAGMENT_ON_CREATE: +2.67ms
    HOME_FRAGMENT_ON_CREATE_VIEW: -6ms
    HOME_FRAGMENT_ON_VIEW_CREATED: -10ms
    HOME_FRAGMENT_ON_START: -3.66ms
    HOME_FRAGMENT_ON_RESUME: 0ms

Given that some methods "improved," I am attributing this to noise and conclude "is migrated" does not have a significant impact on cold startup performance.

**Comment by mcomella** [comment]
@emalysz As of this morning, I believe the migration check is moving from `IntentReceiverActivity` in this PR: https://github.com/mozilla-mobile/fenix/pull/7917

Additionally, the instrumentation I added does not instrument `IntentReceiverActivity` so it might be missing in those notes (except, perhaps, in the "Total elapsed" time because `IntentReceiverActivity` is called between).

I would propose we wait for https://github.com/mozilla-mobile/fenix/pull/7917 to land, see if it is the final change in this direction, and then re-evaluate the performance (if we didn't already do so in #7917). i.e. it's possible we're already chasing the performance of the check by trying to fix #7818 so this could get duped. Unfortunately, I don't understand the check well enough to know if it's the same.

**Comment by mcomella** [comment]
That PR landed today. In my analysis for the review https://github.com/mozilla-mobile/fenix/pull/7917#pullrequestreview-348304730, I noticed it has ~40ms decrease on startup performance.

Additionally, I discovered there is more code that runs for migrations such as https://github.com/mozilla-mobile/android-components/blob/master/components/support/migration/src/main/java/mozilla/components/support/migration/FennecMigrator.kt. @emalysz Was this code path one that you had analyzed previously? I'm not sure where it gets called from (App.onCreate?). After we look at that (and any other related code) and determine the impact, I think we can close this issue.

**Comment by emalysz** [comment]
@mcomella I was just removing https://github.com/mozilla-mobile/fenix/blob/master/app/src/main/java/org/mozilla/fenix/IntentReceiverActivity.kt#L55. Which in turn calls into https://github.com/mozilla-mobile/android-components/blob/master/components/support/migration/src/main/java/mozilla/components/support/migration/MigrationIntentProcessor.kt#L30. Is this what you mean?

**Comment by mcomella** [comment]
There is [a directory hierarchy of code](https://github.com/mozilla-mobile/fenix/tree/master/app/src/migration) that only runs during migration builds, including an AndroidManifest (due to [this configuration](https://github.com/mozilla-mobile/fenix/blob/be7bd527f68a4a128be5f3f27f93650da0fc6f3e/app/build.gradle#L161-L172)). This code will replace even replace our `FenixApplication` class with [`MigratingFenixApplication`](https://github.com/mozilla-mobile/fenix/blob/master/app/src/migration/java/org/mozilla/fenix/MigratingFenixApplication.kt). The only way to access this code is to use one of the build variants defined by the configuration above: `*fennecProduction/Beta/Nightly`.

That being said, thinking about it more, I believe my analysis for https://github.com/mozilla-mobile/fenix/pull/7917#pullrequestreview-348304730 determined the change between the migration version of the code and the code we're running so I don't think any more work needs to be done here (sorry I accidentally usurped this analysis 😞). I'd like to move `forPerformanceTest` to the migration version of the code anyway so we'll see the impact of this on every run. @emalysz Do you agree? If so, can you close?

**Comment by emalysz** [comment]
@mcomella Took a look at this a bit more, and I agree with your analysis here/in #7917. Closing the issue.
