### ISSUE TITLE
[Bug] desktop bookmarks not shown

### ISSUE THREAD

**Issue by 532910** [mozilla-mobile/fenix#7705]
## Steps to reproduce
I don't know. It just doesn't work and never worked.

### Actual behavior
I'm logged in:
![image](https://user-images.githubusercontent.com/14617699/72403848-8bcdd080-3764-11ea-8677-7068d9a28447.png)
and bookmarks syncs is on:
![image](https://user-images.githubusercontent.com/14617699/72403891-ad2ebc80-3764-11ea-9c35-4df0f0590651.png)
but I don't see desktop bookmarks
![image](https://user-images.githubusercontent.com/14617699/72403908-b61f8e00-3764-11ea-9b1c-98ada6e65f3f.png)

### Expected behavior
![image](https://user-images.githubusercontent.com/14617699/72404065-23332380-3765-11ea-90ad-f299da59a46c.png)

### Device information

* Android 9 (LineageOS 16.0) OP3T
* Fenix version:  3.0.2 (Build #20081833)

**Comment by jimgregory** [comment]
I'm also unable to sync my bookmarks on the Nightly build #200211, while syncing on the stable 28.0.3 build (#20250349) works.

**Comment by 532910** [comment]
Looks like it works now
