### ISSUE TITLE
[Bug] Long delay between browsing to URL and page starting to display

### ISSUE THREAD

**Issue by hawkinsw** [mozilla-mobile/fenix#7707]
This is a follow-up bug for additional work not covered in #7143 

## Steps to reproduce
1. Click on the URL bar
1. Enter `cnn.com`, e.g.,
1. Click "->"

### Expected behavior
1. Click on the URL bar
1. Enter `cnn.com`, e.g.,
1. Click "->"
1. Page begins to render

### Actual behavior

1. Click on the URL bar
1. Enter `cnn.com`, e.g.,
1. Click "->"
1. Wait
1. Page begins to render

### Device information
* Android device: Pixel 2
* Fenix version: Nightly

**Comment by hawkinsw** [comment]
It appears that the remaining delay comes from

1. Initializing a session: `SessionManager.getOrCreateEngineSession` takes ~130ms on a Pixel 2. For reference, that is ~4x as long as it takes to initialize Gecko
1. (Depending on when this happens and it's effect on when the user sees the page start to render), there is (yet another) `BrowserToolbarView.<init>` that takes > 200ms. 

Trace attached. 
[7707.trace.gz](https://github.com/mozilla-mobile/fenix/files/4063645/7707.trace.gz)

**Comment by mcomella** [comment]
Triage: Eric will try to see if this is still a perceptible problem and prioritize accordingly.

**Comment by ecsmyth** [comment]
Confirmed this still reproduces on Fenix Nightly 200225 and Release 3.2.0. I'm not sure if there are other sites affected, but I tested 6 and CNN was the only site with an issue. In addition to Will's original STR entering the URL in the address bar, I can also reproduce when clicking on the link to cnn.com from search results. It does not appear to matter if the page load is cold or warm.

**Comment by ecsmyth** [comment]
Cold page load [profile](https://perfht.ml/3a0MDrO) for cnn.com
Also reproduces on https://www.saccounty.net ([cold page load profile](https://perfht.ml/3a1zXAR))

**Comment by ecsmyth** [comment]
Issue no longer reproduces in Fenix Nightly 200304
