### ISSUE TITLE
[Bug]Can't use the Navigation toolbar while the deleted bookmark pop-up is displayed

### ISSUE THREAD

**Issue by sv-sdeiac** [mozilla-mobile/fenix#7709]
#### Prerequisites
- You have some bookmarks saved in your App.

### Steps to reproduce
1. Open a bookmarked page;
2. Edit the bookmark page by tapping on the star from 3dot menu;
3. Delete the bookmark;
4. While the Deleted bookmark pop-up is displayed, try to open the 3dot menu.

### Expected behavior
The 3dot menu is opening over the pop-up menu;

### Actual behavior
The 3dot menu is not responsive while the pop-up is displayed.

### Device information
Android device: 
- OnePlus 5T (Android 9);
- Google Pixel 3a XL (Android 10).

Fenix version:
- Firefox Preview Beta 3.1.0-beta 3 #20092354;
- Firefox Preview Nightly 1/15 #20150607;

Notes:
- The issue is not reproducible When you bookmark a page;
- The issue is different on the latest version of Firefox Preview RC build 3.0.2 since the pop-up is displayed over the Navigation toolbar and you can't do anything till the pop-up disappear.
- 
![20200115_111355](https://user-images.githubusercontent.com/40264165/72420944-3e635a80-3788-11ea-9d2c-d9c016dec27b.gif)

**Comment by mcarare** [comment]
Question for UX: 
If you delete a bookmark from the edit screen you get a confirmation dialog and then a snackbar without undo.
If you delete a bookmark from the context menu you do not get a confirmation dialog, but then you get a snackbar with undo.

Shouldn't the flow be the same? If so, which one? TY!

**Comment by sv-sdeiac** [comment]
Hi @mcarare. The right behavior is displayed when you delete a bookmark from the "Bookmark" option at the 3dot menu. There is a snackbar who informs the user about deleting the latest bookmark and also the "Undo" button.

**Comment by brampitoyo** [comment]
@mcarare This behaviour is intended, but perhaps @topotropic will be able to double-check:

1. When you delete bookmark from the “Edit bookmark” screen
    - We show a confirmation dialogue before you delete
    - Because a dialogue was shown, the snackbar doesn’t need to have an “Undo” action
2. When you delete bookmark from the “Library → Bookmarks” page
    - We don’t show any confirmation dialogue – the user can delete in one tap
    - Because a dialogue was not shown, the snackbar needs to have an “Undo” action

**Comment by topotropic** [comment]
Let's keep "UNDO" in the snackbar. 

What Bram wrote is correct but that said, it feels like there's a misalignment in how we handle deletion in general in the app. 
@betsymi paging you in here, it would be great if we could review all delete cases and try to align them to follow the same pattern

**Comment by betsymi** [comment]
> @betsymi paging you in here, it would be great if we could review all delete cases and try to align them to follow the same pattern

On the case! Will follow up. Thanks for flagging.

**Comment by betsymi** [comment]
This string can read: `Allow screenshots in private tabs`. And to confirm, should be OFF by default.

**Comment by brampitoyo** [comment]
@betsymi I’ve posted your response about screenshots in private tabs to #2768.
