### ISSUE TITLE
Web Push Notifications 

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/fenix#771]
### User Story:
As a user I want to receive web notifications from Fenix, so I can have an interactive app-like experience with my browser.

**This** is a requirement for PWA implementation.
Site developers can prompt users of their website or PWA to accept web push notifications. If accepted, the service in question can send notifications to the end user, pretty much at any chosen time, and irregardless of whether the browser is running or not. This technology consists of two parts: "web notifications" which allows pages to send notifications to users, and "web push", which involves hooking into Firebase Cloud Messaging, and is arguably more complex to set up. We need to support both for PWA. One notable annoyance is that because "classic" PWAs don't really have deep system integration (unlike WebAPKs), web push notifications open in the browser, rather than in the PWA. 

### Dependencies:

Push Support [GV API:](https://bugzilla.mozilla.org/show_bug.cgi?id=1343678) Provided Fenix with ability to push messages to users , whether or not Fenix is in the foreground or currently loaded, on a user agent, we can provide notifications and updates to users that opt in, resulting in better engagement with timely new content.

Web Notification [GV API:](https://bugzilla.mozilla.org/show_bug.cgi?id=1533057): Fenix can send notifications (at the system level) when Fenix is idle or in the background. 

### Acceptance Criteria:
-I am asked whether I'd like to receive web push and I have the option to allow or disable.
-I can receive web notifications in Fenix
-I can receive web push on my installed PWAs

**Comment by vandys** [comment]
Please note that the HTML5 "Notification" API (i.e., "new Notification(msg, opts)") is useful on plain old web pages.  Because of privacy concerns, I keep a tab open to my own source of notifications using long polling.  The Notification API lets me thus get real time notifications without going through a centralized service.  So long as you tell Android to disable "battery optimizations" on the browser, it works quite well.

**Comment by vesta0** [comment]
What is the status of this work?

**Comment by vesta0** [comment]
@jonalmeida is this where you are tracking your work?

**Comment by jonalmeida** [comment]
> @jonalmeida is this where you are tracking your work?

I've been tracking the work on the WebPush board: https://github.com/orgs/mozilla-mobile/projects/42

**Comment by jonalmeida** [comment]
Since the feature has been implemented, shall we close this @vesta0 ? We can file any new follow-up bugs.

**Comment by jonalmeida** [comment]
I'm actually going to close it, we can always re-open. :)

**Comment by vesta0** [comment]
Thanks for implementing this feature @jonalmeida 👍
