### ISSUE TITLE
[Bug] [a11y] Security pop-up overlays password tool-tip pop-up when creating an account

### ISSUE THREAD

**Issue by softvision-miralobontiu** [mozilla-mobile/fenix#7710]
## Steps to reproduce
1. Turn Talkback or Voice Assistant on.
2. Go to Settings - Turn on Sync and create a new account.
3. Fill in a valid email account, a valid password and then repeat the password.

### Expected behavior
The user can see all the pop-ups presented, both the security "You need this password to access any encrypted data you stored with us." one, and the password tool-tip pop-up "Must be at least 8 characters..." one.

### Actual behavior
The user can see only one pop-up presented, the security "You need this password to access any encrypted data you stored with us." one.
The password tool-tip pop-up "Must be at least 8 characters..." one is under the security one, unreachable, the user is not able to see it.

### Device information
* Android device: Samsung Galaxy Tab S3 (Android 8)
* Fenix version: Beta 3.1.0-beta 3

![Untitled](https://user-images.githubusercontent.com/40694158/72423971-e7608400-378d-11ea-8a10-c805d898d3e6.png)

**Comment by sblatz** [comment]
Another FxA issue. I'll reach out to them.
