### ISSUE TITLE
[Bug]3dot menu from Default search engine list overlaps the search engine name

### ISSUE THREAD

**Issue by sv-sdeiac** [mozilla-mobile/fenix#7714]
## Steps to reproduce
1. Set the Android "Language and Input" to Hebrew;
2. Open Firefox Preview;
3. Go to: 3dot menu->Settings -> Search.

### Expected behavior
No visual artifacts are presented in Hebrew.

### Actual behavior
The 3dot menu from the "Default search engine" options are over the search engine name;

### Device information
Android device:
- OnePlus 5T (Android 9);
- Samsung Galaxy Tab S3 (Android 8.0).

Fenix version: 
- Firefox Preview Nightly 1/15 #20150607;
- Firefox Preview Beta 3.1.0-beta 3 #20092354;
- Firefox Preview RC build 3.0.2 #20081833.

Notes:
![bugsearch](https://user-images.githubusercontent.com/40264165/72436504-441d6800-37a9-11ea-9bf8-9c28c04a8b4f.png)

**Comment by sv-ohorvath** [comment]
- Verified on v3.2-beta1.
- Devices: Xiaomi Mi Pad 2 (Android 5.1),  Galaxy Note 8 (Android 9)
