### ISSUE TITLE
[Bug] (regression) Private search suggestions don't appear as soon as you tap Allow

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#7715]
## Steps to reproduce
1. Go to private browsing and type in the search bar to trigger the "allow search suggestions" doorhanger.
2. Tap Allow on showing search suggestions in private mode.
3. continue typing in the search bar to see search suggestions.
### Expected behavior
Search suggestions come up as soon as you allow them.
### Actual behavior
The suggestions don't show up immediately. You need to exit search mode and type in again to see suggestions.
### Device information

* Android device: Nexus 9 (Android 7.1.1), Samsung S8 (Android 9)
* Fenix version: Beta 3.1.0, Nightly 1/15

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly Build #20570604 from 02/26`** using the following devices:
• Google Pixel 3a (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

► Video
![20200226-095146](https://user-images.githubusercontent.com/51314259/75323623-ef780d00-587d-11ea-9c3d-1ef64556d08c.gif)
