### ISSUE TITLE
[Bug] [a11y] Consider increasing some elements from the page's menu

### ISSUE THREAD

**Issue by softvision-miralobontiu** [mozilla-mobile/fenix#7721]
## Prerequisite
Make sure you have Google Accessibility Scanner installed.

## Steps to reproduce
1. Launch Fenix and go to a webpage.
2. Open the page's menu.
3. Using Accessibility Scanner, scan the page.

### Expected behavior
No suggestions are made.

### Actual behavior
The same suggestion regarding the forward arrow, bookmark, share and refresh items is displayed: "The item's height is 24dp. Consider making the height of this touch target 48dp or larger."

### Device information
* Android device: Samsung Galaxy Tab S3 (Android 8), Samsung Galaxy Note 8 (Android 9)
* Fenix version: RC 3.0.2, Beta build 3.1.0-beta 3, Nightly build from 01/15

![reader view_Accessibility Scanner](https://user-images.githubusercontent.com/40694158/72440721-0c66ee00-37b2-11ea-9a95-de5e66f53946.jpg)

**Comment by sblatz** [comment]
Going to have https://github.com/mozilla-mobile/fenix/issues/7756 cover both of these!
