### ISSUE TITLE
[Bug] [a11y] Increase some elements from the "Sign in" page

### ISSUE THREAD

**Issue by softvision-miralobontiu** [mozilla-mobile/fenix#7722]
## Prerequisite
Make sure you have Google Accessibility Scanner installed.

## Steps to reproduce
1. Launch Fenix and go to Settings - Turn on Sync.
2. Enter a valid email and scan the page.

### Expected behavior
No major discrepancies are displayed.

### Actual behavior
We have 2 major suggestions:
- "Terms of Service" and "Privacy Notice" are suggested to be increased from 15dp to 48dp or larger,
- "Use a different account" and "Forgot password?" are suggested to be increased from 19dp to 48dp or larger.

### Device information
* Android device: Samsung Galaxy Tab S3 (Android 8), Samsung Galaxy Note 8 (Android 9)
* Fenix version: RC 3.0.2, Beta build 3.1.0-beta 3, Nightly build from 01/15

![sync](https://user-images.githubusercontent.com/40694158/72442220-c8291d00-37b4-11ea-87d1-0d79b5b5f6b2.png)

**Comment by sblatz** [comment]
This is something FxA needs to handle. I will touch base with them about this and get it filed in the correct place.
