### ISSUE TITLE
[Bug] The account sync doesn't start automatically when the app is brought to the foreground

### ISSUE THREAD

**Issue by sflorean** [mozilla-mobile/fenix#7723]
## Prerequisites
Connect to Sync on 2 devices.

## Steps to reproduce
1. On the mobile device, create a new bookmark.
2. Minimize and restore the app.
3. Go to Settings>Account and verify if sync works automatically.

### Expected behavior
The account sync starts automatically when the app is brought to the foreground.

### Actual behavior
Sync doesn't start automatically. 

### Device information
* Android device: Xiaomi MiPad 2 (Android 5.1), OnePlus 5T (Android 9), Samsung Galaxy Tab S3 (Android 8).
* Fenix version: 3.1.0 - beta 3

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-15227)

**Comment by Diana-Rus** [comment]
Hi, i can reproduce the issue with Samsung Galaxy S8+ (Android 8) with Firefox Preview Beta 4.1.0-beta.2 .
No sync is being made-> There is no snackbar present nor after making a sync on the second device does the new bookmark be displayed.
Note: The account has been created with all Sync options checked/synced: Bookmark, History and Logins and Password.

**Comment by softvision-miralobontiu** [comment]
Still reproducible on Beta 4.2.0-beta.2 with OnePlus 5T (Android 9).

**Comment by sflorean** [comment]
The issue is still reproducible on 86.1.0 RC build.

**Comment by lobontiumira** [comment]
Reproducible on Beta 90.0.0-beta.1 with Samsung Galaxy Tab A6 (Android 5.1.1).

**Comment by mariansima** [comment]
This issue still occurs on Firefox beta 96.0.0-beta.1 with Samsung Galaxy A8 (Android 9)
