### ISSUE TITLE
[Bug] [a11y] Consider increasing the "Info" icon items from the ETP page

### ISSUE THREAD

**Issue by softvision-miralobontiu** [mozilla-mobile/fenix#7725]
## Prerequisite
Make sure you have Google Accessibility Scanner installed.

## Steps to reproduce
1. Launch Fenix and go to Settings - ETP.
2. Scan the page.

### Expected behavior
No major discrepancies are suggested.

### Actual behavior
The suggestion is to increase the item's size from 24dp x 24dp to 48dp x 48dp or larger - as seen in the screenshot below.

### Device information
* Android device: Samsung Galaxy Tab S3 (Android 8), Samsung Galaxy Note 8 (Android 9)
* Fenix version: RC 3.0.2, Beta build 3.1.0-beta 3, Nightly build from 01/15

![Screenshot_20200115-173342_Accessibility Scanner](https://user-images.githubusercontent.com/40694158/72447474-0e36ae80-37be-11ea-9d38-b83c4e968e4e.jpg)

**Comment by sflorean** [comment]
Verified as fixed on Nightly 6/9 with LG G7 FIT (Android 8). No suggestions are made for ETP page.
