### ISSUE TITLE
As a User I want to be able to create a shortcut to a website on my phone's homescreen

### ISSUE THREAD

**Issue by st3fan** [mozilla-mobile/fenix#773]
Unclear what the possibilities here are. Is there a new Android API that lets Chrome do this? Can applications create new shortcuts or applications? Would this be for any website or only for PWAs?

Is *Shortcut* the right terminology here?

**Comment by suoko** [comment]
Having an apk generated for any website added to homescreen should be an option, i find it nice when you switch launcher so that you dont loose them, but default behaviour should be just a link on the currently used launcher.

**Comment by reinhart1010** [comment]
Duplicate: https://groups.google.com/forum/m/?utm_medium=email&utm_source=footer#!topic/fenix-nightly/y0s-eiLwA0o

**Comment by reinhart1010** [comment]
Duplicate: https://groups.google.com/forum/m/?utm_medium=email&utm_source=footer#!topic/fenix-nightly/IKPTCvQ3ErM

**Comment by espectalll** [comment]
Any news on WebAPK? Is it implemented, if not is there any open ticket that takes care of it?

**Comment by NotWoods** [comment]
We're not able to use WebAPK 😔

We are exploring Trusted Web Activities, which let web developers create their own WebAPK equivalent.

**Comment by reinhart1010** [comment]
@espectalll The issue with WebAPKs is discussed in https://twitter.com/Not_Woods/status/1179368438923444224

**Comment by espectalll** [comment]
@reinhart1010 if the issue is having a popup warning of installing a package from an "unknown source", couldn't there be a way to make it user friendly by asking to enable it before a system warning pops up, and just install as browser shortcuts if the permission wasn't given?

**Comment by reinhart1010** [comment]
@espectalll It's possible, so when Fenix detects that the downloaded file is an APK that notice could be triggered (and only shown once) to user while the file is being downloaded. So there would be less installation issues when the user opens up the APK into the Android Package Installer.
