### ISSUE TITLE
[Bug] Add PB shortcut disappears from settings after use

### ISSUE THREAD

**Issue by topotropic** [mozilla-mobile/fenix#7730]
## Steps to reproduce
1. Go to settings
2. Tap on "Add private browsing shortcut" and add it
3. Check settings for "Add private browsing shortcut"

### Expected behavior
Menu entry is still there

### Actual behavior
Menu entry disappears

### Device information

* Android device: ?
* Fenix version: ?

**Comment by cadeyrn** [comment]
This was implemented this way in #5233.

**Comment by NotWoods** [comment]
The intention here was to only show the settings option if the shortcut hasn't been added. If the shortcut is removed the setting returns.

**Comment by topotropic** [comment]
Ok, I understand the reasoning but I'm concerned about people who add the shortcut and then forget that they added it, read or hear about it, try to find it in setting but can't because they already added it once. I'd strongly recommend to NOT hide it.

There's also a re-organisation of the setting screen planned and the shortcut option will be moved to a dedicated section, in case you're worried about clutter in the settings  screen https://share.goabstract.com/ee40800d-4b36-49d5-8a5b-a89f8ab21141?mode=design&sha=6e82c52070e76eb62b1e8511710296a22ed87cd7.

**Comment by cadeyrn** [comment]
> There's also a re-organisation of the setting screen planned and the shortcut option will be moved to a dedicated section, in case you're worried about clutter in the settings screen

FWIW, as opener of #5233 I would be ok with reverting the behaviour after the settings reorganisation. My main concern was the clutter of the settings screen. :)

**Comment by topotropic** [comment]
@cadeyrn ok, sounds good! I don't think we should introduce a dependency here by waiting for the settings re-org to be implemented though – the issues it generates when people can't find it outweighs the concern of a cluttered screen from UX perspective.

**Comment by sv-sdeiac** [comment]
Verified as fixed using the latest version of Firefox Preview Nightly 1/28.
Devices:
- Nokia 6 (Android 7.1.1);
- OnePlus 5T (Android 9).
