### ISSUE TITLE
Reword "Install" string for sites with a manifest as "Install as app" 

### ISSUE THREAD

**Issue by andreasbovens** [mozilla-mobile/fenix#7732]
### Why/User Benefit/User Problem

Just the word "Install" doesn't give a whole lot of context or information. "Install as app" better conveys what is going on. 

### What/Requirements

Change the string "Install" in the threedot-menu to "Install as app".

### Acceptance Criteria (how do I know when I’m done?)

When navigating to a site with a valid manifest, the threedot-menu should have a menu item that says "Install as app" instead of just "Install".

**Comment by NotWoods** [comment]
Prior discussion: https://github.com/mozilla-mobile/fenix/pull/6882#issuecomment-561281312

**Comment by brampitoyo** [comment]
Thanks @NotWoods for pointing out the prior discussion point.

Based on that decision, I’d be happy to keep the word “Install” and close this issue.

**Comment by grigoryk** [comment]
Closing as per @brampitoyo
