### ISSUE TITLE
[Bug] Some PWA icons are misshaped when installed

### ISSUE THREAD

**Issue by andreasbovens** [mozilla-mobile/fenix#7733]
## Steps to reproduce

1. Go to https://pwa.rocks/ 
2. Tap "Install"

### Expected behavior

A modal "Add to Home screen" dialog featuring a square icon is shown (like in Fennec).

### Actual behavior

A modal "Add to Home screen" dialog with a modified circular icon is shown. 
![Screenshot_20200115-165644](https://user-images.githubusercontent.com/613077/72454211-5b178680-37b8-11ea-9bc4-4ccfa727b0c6.jpg)

### Device information

* Android device: OnePlus 5
* Fenix version: Fenix Nightly

**Comment by NotWoods** [comment]
Which Android version are you using? Currently we save all icons as adaptive icons to match with the system.

**Comment by andreasbovens** [comment]
Android Pie.
