### ISSUE TITLE
[Collections] Header text is cut off before animating in when adding to collection

### ISSUE THREAD

**Issue by AmyYLee** [mozilla-mobile/fenix#7734]
Steps to reproduce:

1. Open a tab 
2. Go to homescreen
3. Long-press tab to select
4. Tap save to collection

Expected:
The "Select collection" header is already visible, same for when people don't have a collection and see the "Name collection" screen

Actual:
The "Select collection"/ "Name collection" header is partially cut off and then the rest of the text animates in.

See video for reference:
https://share.getcloudapp.com/geurEbeP

**Comment by sflorean** [comment]
Verified as fixed on Fenix Nightly 200330 with Samsung Galaxy Note10 (Android 10) and Xiaomi Mi Pad 2 (Android 5.1).
