### ISSUE TITLE
[Private Browsing] Add private browsing shortcut shouldn't disappear after adding shortcut

### ISSUE THREAD

**Issue by AmyYLee** [mozilla-mobile/fenix#7735]
Steps to reproduce:

1. Go to Fenix Homescreen -> Settings
2. Tap on "Add private browsing shortcut"
3. Tap "Add automatically"

Expected:
When I go back to the Settings menu the "add private browsing shortcut" should still be there and allow the user to add multiple shortcuts on their android homescreen.

Actual:
When I go back to the Settings menu the "add private browsing shortcut" menu item is gone.

**Comment by mcarare** [comment]
Same as https://github.com/mozilla-mobile/fenix/issues/7730
