### ISSUE TITLE
Add mitigation to prevent use of WebURLFinder

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#7736]
It takes a long time to compile (493ms on a P2), wasting users battery life and potentially blocking UI operations for something that we often have faster and better ways of solving.

### Acceptance criteria
- Devs cannot add WebURLFinder to the fenix code base
- WebURLFinder is not used in the a-c code used by Fenix

---

`WebURLFinder` is actually an a-c class: can we just remove it?

**Comment by mcomella** [comment]
We might be removing it in a-c in https://github.com/mozilla-mobile/android-components/issues/5594

**Comment by ekager** [comment]
Can we close this @mcomella ?

**Comment by mcomella** [comment]
It looks like `WebURLFinder` still exists in a-c with large regex which may become performance bottlenecks: https://searchfox.org/mozilla-mobile/rev/2a012f357f443dd6e9721b8e2f431fe21f25b102/android-components/components/support/utils/src/main/java/mozilla/components/support/utils/WebURLFinder.kt#83

@csadilek What do you think about removing `WebURLFinder` from a-c?

**Comment by csadilek** [comment]
@mcomella `WebURLFinder` is used by the `ClipboarSuggestionProvider` and I think it would makes sense to keep. I think you would want to deprecate the large regex fields and its consumers such as `String.isUrlStrict` which are currently not used. The question is if these methods might become useful at some point where they are not performance sensitive? At the very least, we could document and add a warning in big letters that these methods are very expensive and shouldn't be used.

I don't feel strongly either way. Also up for deprecating and ultimately removing.

**Comment by mcomella** [comment]
> I think you would want to deprecate the large regex fields and its consumers such as String.isUrlStrict which are currently not used.
>
> The question is if these methods might become useful at some point where they are not performance sensitive?

I'd prefer to remove them because:
1) unused code should generally be removed because it's more likely to break
1) if the APIs exist and fulfill someone's needs, they'll use them. However, if they had to write their own, they may be able to come up with a simpler, alternative implementation that would better fit their needs and, in this case, be much more performant.
1) On a mobile device with limited battery, we shouldn't be unnecessarily compiling a regex for a second or more if it's not necessary, especially if a simpler implementation is viable
1) This hard-coded list of TLDs (from 2015) is already out-of-date and liable to cause problems: more TLDs are getting all the time so, if keeping a hard-coded list of TLDs is actually a need, we should find an alternative implementation that lends itself to getting frequent updates like our public suffix list

I feel pretty strongly about removing these large, underperformant regexes. @csadilek What are the next steps to go about doing that?

**Comment by csadilek** [comment]
> I feel pretty strongly about removing these large, underperformant regexes. @csadilek What are the next steps to go about doing that?

@mcomella In general, I am all for deleting unused code. We usually deprecate (and remove in a subsequent release), but all it takes is to open a PR :). We have a ticket for it too: https://github.com/mozilla-mobile/android-components/issues/5680

So, feel free to open a PR, or otherwise we can schedule it in as perf. work in the next Sprint.

**Comment by mcomella** [comment]
Sounds good to me, will do: dupe https://github.com/mozilla-mobile/android-components/issues/5680
