### ISSUE TITLE
[Bug] Laggy typing performance on Canada Strong donation page

### ISSUE THREAD

**Issue by ehsan** [mozilla-mobile/fenix#7738]
## Steps to reproduce
This doesn't happen every time, but in order to reproduce, go to https://torontofoundation.ca/canadastrongcampaign#donate-now and try to fill out the donation form.  I sometimes experience a typing lag of tens of seconds.

### Expected behavior
No typing lag.

### Actual behavior
Typing lag.

### Device information
HTC One m9.

* Android device: Android 7
* Fenix version: 3.0.1

**Comment by hakkikaancaliskan** [comment]
No problem on XZ1 Android 10 LOS 17 with Gboard.
Nightly 200116 06:00 (Build #20160604)
28.0.0, 852d955d6
GV: 74.0a1-20200114094410

**Comment by AndiAJ** [comment]
Hi, The form @ehsan mentioned isn't available anymore, it seems that the CANADA STRONG CAMPAIGN ended.

However, I've managed to find another fundraiser https://torontofoundation.ca/listings/Vital_Toronto_Fund/ and **haven't encountered any lag** while filling the form on the latest **`Nightly Build #21130610 from 4/22`** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)

► Video
![20200422-133255](https://user-images.githubusercontent.com/51314259/79975898-5b54ab80-84a4-11ea-895a-f42eafe151d3.gif)
