### ISSUE TITLE
[Bug] With external password manager there are two "save login" dialogs

### ISSUE THREAD

**Issue by cadeyrn** [mozilla-mobile/fenix#7739]
### Steps to reproduce

1. make sure an external password manager is installed. I use Firefox Lockwise and didn't test with other password managers.
2. make sure the feature to save logins is enabled in Fenix.
3. open a website and log into the website.

### Expected behavior

There is only one "save login" dialog.

### Actual behavior

There are both the dialog of the external password manager and the dialog of Fenix itself and both overlap.

![Screenshot_20200115-214754](https://user-images.githubusercontent.com/1100614/72470878-e0636100-37e1-11ea-840a-1395d608f4f8.jpg)

### Device information

* Android device: OnePlus 7T Pro McLaren Edition / Android 10
* Fenix version: master branch revision 0777fb3bbeea9e3fb5b64365027b965951d2cb00

**Comment by cadeyrn** [comment]
@ekager Since you worked on the logins feature - may I ask you a) what the expected behaviour is (Show only the Fenix dialog? Show only the Lockwise dialog?) and b) if this is something that needs to be fixed in Fenix or if I have to report this to the Lockwise team?

**Comment by ekager** [comment]
This is currently intentional behavior. 
In the future, we want to integrate better with Lockwise specifically and not show two dialogs (since it's all the same backend)
Fenix will handle this in the future.

**Comment by ekager** [comment]
Closing for #550

**Comment by cadeyrn** [comment]
@ekager:

Since you closed it for #550 - Does Fenix not have the same problem with other password managers, too? It's a serious question because I don't have another password manager installed and I don't know but my guess is:

- If other password managers are also affected then this issue is not about better integrating with Lockwise but about a bug on the Fenix side
- If only Lockwise is affected then it seems to be a Lockwise bug

Or am I missing something?

I tested with Fennec a few moments ago and Fennec does not have this problem.

I am not very happy about the "currently intentional behavior" part because it should not cause such problems to use two products, both developed by Mozilla. That reminds me of the inability to use Firefox Send with Firefox Preview (#3336). Mozilla has great products - but you can't use these together. :-(
