### ISSUE TITLE
As a User I want to be notified when a website I visit is available as a PWA that I can save to the home screen

### ISSUE THREAD

**Issue by st3fan** [mozilla-mobile/fenix#774]
Chrome show a banner when you visit a website that is recognized as PWA compatible. Here is an example for mobile.twitter.com

![screenshot_20181103-112214](https://user-images.githubusercontent.com/28052/47953987-16108700-df5b-11e8-89ad-2d5a3eea5cf8.png)

**Comment by vesta0** [comment]
Will be addressed in #768
