### ISSUE TITLE
Reduce RecyclerView.layoutManager inflation time on Cold Start up

### ISSUE THREAD

**Issue by MarcLeclair** [mozilla-mobile/fenix#7740]
Currently, our RecyclerView.LayoutManager inflation is costing us a lot (~3% of start up time just for a few items). It's also affecting our `doTraversal` methods that is handled by the android framework. So, this issue is to address #7488 but with a bit more fine grained details and actionable items.

**Comment by mcomella** [comment]
@MarcLeclair Can this issue be closed? Please also close when moving issues to Done (unless they need QA).

Did we expend effort to complete this issue? If not, can you remove this from the project board? It's nitty but I'm trying to only keep items in the Done column that we actually put time into.

**Comment by MarcLeclair** [comment]
Ah I forgot to close this. we didn't have any tickets per se regarding this but should refer to #7700  since we moved the recyclerview to the `fragment_home.xml` and it removed the `.inflate` from `sesessionControlView`. Although, we should maybe revisit our numbers once #8085 lands
