### ISSUE TITLE
[Bug] Autofill not shown on Turkish with Bitwarden

### ISSUE THREAD

**Issue by hakkikaancaliskan** [mozilla-mobile/fenix#7742]
No difference between changing language system-wide and in-app settings.
Not just for Spotify, for **All** websites.
Works perfectly on chrome.

**Logs**:
[success_on_eng.txt](https://github.com/mozilla-mobile/fenix/files/4841022/success.txt)
[failed_on_tr.txt](https://github.com/mozilla-mobile/fenix/files/4841023/failed.txt)

**Video**:
https://imgur.com/a/xcVBvWB

On English:
<img src="https://user-images.githubusercontent.com/17825767/72473788-1c9dbe00-37f0-11ea-96f8-e9e632556465.png" width="300">
On Turkish:
<img src="https://user-images.githubusercontent.com/17825767/72473803-23c4cc00-37f0-11ea-87a7-7f192c281d65.png" width="300">

Xperia XZ1, Android 10
Nightly 200627 06:01 (Build #2015748659)
AC: 48.0.20200626213814, 55bca70c8
GV: 79.0a1-20200626094540
AS: 61.0.6

**Comment by hakkikaancaliskan** [comment]
Problem still persist.
When I change the language to other than Turkish on "in-app" or system-wide, autofill works.

**Comment by hakkikaancaliskan** [comment]
I don't know who to tag but this issue needs label :)
@sblatz sorry :/

**Comment by hakkikaancaliskan** [comment]
[success_on_eng.txt](https://github.com/mozilla-mobile/fenix/files/4841022/success.txt)
[failed_on_tr.txt](https://github.com/mozilla-mobile/fenix/files/4841023/failed.txt)

cc @ekager please at least properly label this issue because this is really deal breaker. People will want autofill and if its not working they will just use chrome.

**Comment by hakkikaancaliskan** [comment]
https://imgur.com/a/xcVBvWB

**Comment by abodea** [comment]
I was able to reproduce this issue on the latest **Nightly 8/4** with **Google Pixel 4 XL (Android 11).**
For some reason when the language was set on Turkish the autofill didn't pop-up. 
I will investigate this issue with more languages bug so far I tried other 5 and it worked well.

**Comment by hakkikaancaliskan** [comment]
@abodea any progress?

**Comment by abodea** [comment]
Hi, @hakkikaancaliskan I'm sorry for the delay.
Nothing changed since my last comment, I do believe this is only Turkish bug related. 
I tried again on the latest Nightly from 8/19 with Google Pixel 4 XL (11) and I can still reproduce it.
@vesta0 is something we can do regarding this? Bitwarden is not working for the Turkish language, the auto-fill pop-up is not displayed.

**Comment by vesta0** [comment]
@abodea can we look into opening a bug report with Bitwarden?

**Comment by hakkikaancaliskan** [comment]
I've created bug report https://github.com/bitwarden/mobile/issues/1050

**Comment by hakkikaancaliskan** [comment]
I've installed Android 11 and also inline autofill not working with Turkish.

**Comment by hakkikaancaliskan** [comment]
Absolutely no response from bitwarden. Are you guys sure root of the problem is not firefox?

**Comment by abodea** [comment]
Hello @hakkikaancaliskan thank you for getting back to us, I will try in the next few days to submit a ticket to bitwarden regarding this issue!

**Comment by hakkikaancaliskan** [comment]
@abodea I've tried again today and it's working fine now. What did you guys did :)

IDK which change is fixed this but could you please try again, is it also working on your side?

Xperia XZ1, Android 11

Nightly 210220 17:00 (Build #2015794443)
AC: 73.0.20210218143118, 525591d8b
GV: 87.0a1-20210218092411
AS: 70.0.0

**Comment by hakkikaancaliskan** [comment]
![Screenshot_20210221-093344_Firefox_Nightly](https://user-images.githubusercontent.com/17825767/108617506-f3eeeb80-7427-11eb-88f6-877b26250d24.png)

**Comment by hakkikaancaliskan** [comment]
It's been 3 days and running flawlessly, I'm closing this issue as fixed.
