### ISSUE TITLE
[Bug] Instant battery drain

### ISSUE THREAD

**Issue by otede** [mozilla-mobile/fenix#7743]
## Steps to reproduce
1. Install
2. Log in to Sync
3. Visit any website
4. Use other apps from now on

### Expected behavior
Normal battery usage

### Actual behavior
Heavy battery usage

### Device information
Moto X Play X1562 with LineageOS Android ROM 14.1 (Android 7.1.x)

* Android device: yes
* Fenix version: the bug report has been observed since pre-3.0 release and the issue is still present with the latest app version as of today, i.e. 3.0.2 (Build #20081832)

Some battery usage statistics:
old https://www.evernote.com/l/ANgwPfQGHLNFpbrnMonVCyEnu477rKP7zhg/
new https://www.evernote.com/l/ANjk3-hMEI1CrLEM2fsdAbe7bfokKmVHkQI/

**Comment by gaby2300** [comment]
Hello @otede Could you please tell me how to download today's 3.0.2? I would greatly appreciate it as I have a week old version!

**Comment by otede** [comment]
> Hello @otede Could you please tell me how to download today's 3.0.2? I would greatly appreciate it as I have a week old version!

Google Play. Automatic updates do work.

**Comment by otede** [comment]
Firefox to Firefox Preview update/migration begins soon. It would really be bad if this bug gets carried over without addressing. Please let me know if you need any more info.

**Comment by otede** [comment]
Sadly, nothing has changed after the last two updates. Even though the changelog mentions the bug specifically.

**Comment by ghoppaccia** [comment]
I also have this problem, had to (sadly) uninstall fenix because of this. Without it my battery usage is much more regular and normal...

**Comment by otede** [comment]
> 
> 
> I also have this problem, had to (sadly) uninstall fenix because of this. Without it my battery usage is much more regular and normal...

The problem is gone on my configuration. The app got stuck on January 3.2.1 build and wouldn't update. I did a clean re-installation, the app updated to 4.x and the problem is gone for me. Here's the report
https://support.mozilla.org/en-US/questions/1281624
