### ISSUE TITLE
[webcontent] TfNSW Trip Planner not accepting keyboad input

### ISSUE THREAD

**Issue by KazaHesto** [mozilla-mobile/fenix#7745]
## Site with issue and any steps to reproduce
https://transportnsw.info/trip#/
Attempt to type into the From and To fields
### Expected behavior
Can type text
### Actual behavior
Text doesn't input
### Does toggling Tracking Protection fix the issue? (Press the lock icon in the toolbar while on the site to see toggle)
No
### Can you reproduce in [Firefox for Android](https://play.google.com/store/apps/details?id=org.mozilla.firefox)?
Yes
### Can you reproduce in Chrome (or other non-Mozilla browser)?

No
### Device information

* Android device: 10
* Fenix version: Nightly 200115 18:00

**Comment by kbrosnan** [comment]
This works for me using Firefox for Android Beta and Firefox Preview Nightly on a Pixel 2XL running Android 10.
