### ISSUE TITLE
[Bug] [a11y] Consider making the "Close tab" and "Restore tab" buttons larger (about:crashcontent)

### ISSUE THREAD

**Issue by softvision-miralobontiu** [mozilla-mobile/fenix#7753]
## Prerequisite
Make sure you have Accessibility Scanner installed and turned on.

## Steps to reproduce
1. Launch Fenix, open a website.
2. In the same tab, go to about:crashcontent.
3. Scan the page using Accessibility Scanner.

### Expected behavior
No major discrepancies are reported.

### Actual behavior
The "Close tab" and "Restore tab" buttons are suggested to be increased from 36dp to 48dp or larger.

### Device information
* Android device: Huawei Honor 8 (Android 7), Samsung Galaxy Tab S3 (Android 8)
* Fenix version: 01/16 Nightly build

![Screenshot_20200116-110216_Accessibility Scanner](https://user-images.githubusercontent.com/40694158/72512887-29083200-3855-11ea-801b-bd4622be0ed9.jpg)

**Comment by sblatz** [comment]
This is something I'm already planning to fix in my error page updates. I'll confirm that I make these large enough 😄

**Comment by softvision-miralobontiu** [comment]
This is not fixed yet on the latest Nightly from 2/11. Verified with Samsung Galaxy Tab S3 (Android 8), and OnePlus 5T (Android 9). I'll remove the qa:needed label for now.

![Screenshot_20200211-112213](https://user-images.githubusercontent.com/40694158/74225804-15b97c80-4cc4-11ea-826c-ad8ae06b38ae.jpg)

**Comment by Diana-Rus** [comment]
Hi, this outcome is still present for "Close tab" and "Restore tab" buttons on Nightly 04/07 (Build #20980610) with Samsung Galaxy S9 (Android 8)

**Comment by sflorean** [comment]
Verified as fixed on Nightly 6/9 with LG G7 FIT (Android 8) and Google Pixel (Android 10). No suggestions are made for the buttons "Close tab" and "restore tab".
