### ISSUE TITLE
[Bug] [a11y] Suggestions regarding download's context menus

### ISSUE THREAD

**Issue by softvision-miralobontiu** [mozilla-mobile/fenix#7754]
## Prerequisite
Make sure you have Accessibility Scanner installed and turned on.

## Steps to reproduce
1. Launch Fenix, open https://www.thinkbroadband.com/download.
2. Select to download the smallest file - 5MB.
3. Using the Accessibility Scanner, scan the "Download" context menu.

### Expected behavior
No major discrepancies are reported.

### Actual behavior
It is suggested to increase the "x" button from the context menus (when asking the user to confirm the download, and when informing the user the file can be opened), from 24dp x 24dp to 48dp x 48dp or larger.

### Device information
* Android devices: Huawei Honor 8 (Android 7), Samsung Galaxy Tab S3 (Android 8)
* Fenix version: 01/16 Nightly build

![download](https://user-images.githubusercontent.com/40694158/72514275-1131ad80-3857-11ea-9278-39043a32adad.png)

**Comment by sblatz** [comment]
Let's increase the size of this close button as recommended 😄

**Comment by Diana-Rus** [comment]
Hi, still reproducible with Samsung Galaxy S9 (Android 8) on Nightly 4/7 (Build #20980610)

**Comment by mcarare** [comment]
This was fixed in https://github.com/mozilla-mobile/fenix/commit/7feae9894409291d99f4090f2e4455779b2daa10.
