### ISSUE TITLE
Open PWAs in a container

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/fenix#776]
### User Story
As a user, I want my PWA to have a separate cookie jar than the browser, so that my logged-in sessions and browsing activity won't leak over to and from the PWA.

### Acceptance Criteria:
I can keep my PWA activity separate and private from the rest of my browsing experience.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-15256)

**Comment by liuche** [comment]
Removing the waiting label since the GV bug is closed. Will need to put that code into AC, when we want to implement this feature - but unless AC is definitely doing that, it could also be done as part of this bug.

**Comment by NotWoods** [comment]
AC bug for container API: mozilla-mobile/android-components#4735

**Comment by astarq** [comment]
This would be a great privacy feature for sites like Instagram, twitter etc

**Comment by kbrosnan** [comment]
As part of https://github.com/mozilla-mobile/fenix/issues/26855 this report is closed. I think we would want to do this differently.
