### ISSUE TITLE
Glean initialization follow-up

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/fenix#7762]
Follow-up from #7717.

See: https://github.com/mozilla-mobile/fenix/pull/7717#pullrequestreview-343354760

We may want to get back to a state where Glean can buffer events pre-initialization (but also not over buffer like before) and work nicely with the migration that determines the state of telemetry "a bit later".

**Comment by Dexterp37** [comment]
> We may want to get back to a state where Glean can buffer events pre-initialization (but also not over buffer like before) and work nicely with the migration that determines the state of telemetry "a bit later".

The ideal state would be the following:

- Load the correct telemetry setting
- Initialize Glean (which means calling `Glean.initialize` not `GleanMetricsService.start()`!) as soon as possible with that value.

If that's not possible, we should still try to call `Glean.initialize` ASAP, and not too late during startup. We risk, otherwise, of overflowing the pre-init buffer due to components (e.g. GV) who send lots of metrics.

**Comment by liuche** [comment]
Feel free to close if there is nothing that QA can verify.

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on **Nightly Migration Build # 5** using a Google Pixel 3a XL (Android 10). 
The Fenix "client_id" values are generated and displayed properly. (No new values are assigned after force stopping and re-opening Fenix).

[Logcat](https://github.com/mozilla-mobile/fenix/files/4117529/B5.txt)
[Glean dashboard](https://debug-ping-preview.firebaseapp.com/pings/aj-test2701000)

**Comment by Dexterp37** [comment]
> 
> 
> Hi, **verified as fixed** on **Nightly Migration Build # 5** using a Google Pixel 3a XL (Android 10).
> The Fenix "client_id" values are generated and displayed properly. (No new values are assigned after force stopping and re-opening Fenix).
> 
> [Logcat](https://github.com/mozilla-mobile/fenix/files/4117529/B5.txt)
> [Glean dashboard](https://debug-ping-preview.firebaseapp.com/pings/aj-test2701000)

Does this result in a fresh client id in older builds?

**Comment by AndiAJ** [comment]
> Does this result in a fresh client id in older builds?

Yes, for instance, on Migration Build # 4 a new "client_id" was assigned after force stopping and resuming Fenix.

**Comment by Dexterp37** [comment]
> 
> 
> > Does this result in a fresh client id in older builds?
> 
> Yes, for instance, on Migration Build # 4 a new "client_id" was assigned after force stopping and resuming Fenix.

Great, thanks, this is exactly what I was looking for! Great job!

**Comment by ebalazs-sv** [comment]
Since this is verified, I will move it to Done. Thanks!
