### ISSUE TITLE
[Logins] Tapping on "Don't Save" doesn't respond

### ISSUE THREAD

**Issue by AmyYLee** [mozilla-mobile/fenix#7768]
Steps to reproduce: 

1. Go to gap.com (or any sign-in page that you haven't saved your credentials in yet)
2. Type in your credentials
3. Tap "Don't save" when Fenix asks if you want to save this login

Expected:
Login panel closes 

Actual:
Login panel stays open

**Comment by ekager** [comment]
Opened https://github.com/mozilla-mobile/android-components/pull/5636

**Comment by sv-sdeiac** [comment]
Verified as fixed using the latest version of Firefox Preview Nightly 1/28 #20280606.
Devices:
- Nokia 6 (Android 7.1.1);
- OnePlus 5T (Android 9).
