### ISSUE TITLE
[Logins] Keyboard blocks panel so you can't save after editing credientials

### ISSUE THREAD

**Issue by AmyYLee** [mozilla-mobile/fenix#7769]
Steps to reproduce:

1. Go to a website and enter your credentials (i.e amazon.com) and tap sign-in
2. When Fenix logins pops up asking to if you want to save this login, tap on the text field under "Username"

Expected:
After I edit my login name and tap Enter on the keyboard, the keyboard should close so I can tap "Save" in the panel.

Actual:
After I edit my login name and tap enter, it goes to a second line in the text field. I can't close the keyboard and save my edited login.

**Comment by sv-sdeiac** [comment]
Hello, I can confirm that this issue is fixed using the latest version of Firefox Preview Nightly 1/21 #20210606.

Devices:
- Nexus 5 (Android 6.0.1);
- Nokia 6 (Android 7.1.1);
- Motorola Moto G6 (Android 8);
- Samsung Galaxy Note 8 (Android 9).
