### ISSUE TITLE
[Bug] difficult to tap on small touch areas such as EU cookie banners 

### ISSUE THREAD

**Issue by MikeCheque** [mozilla-mobile/fenix#7771]
## Steps to reproduce
visit any website that has eu cookie warnings (this isn't limited to sites that have cookie warnings. this is easiest way to reproduce the bug).

### Expected behavior
unable to close small pop-up windows

### Actual behavior
unable to close small pop-up windows

[Link to gif](http://imgur.com/a/Sm8Fj87) 

### Device information
* Android device: ?
tmo v30, android 9
* Fenix version: ?
Nightly 200116 08:01 (Build #20160807)
28.0.0, efaf48680
GV: 74.0a1-20200115093807

**Comment by kbrosnan** [comment]
BZ-1542381
#4147
