### ISSUE TITLE
[Bug] can access ftp:// urls via sync

### ISSUE THREAD

**Issue by kbrosnan** [mozilla-mobile/fenix#7775]
## Steps to reproduce
* have a sync account
* On desktop bookmark
* ftp://ftp.osuosl.org
* ftp://ftp.suse.com
* Sync both devices
* Search the address bar for ftp or use library to access the bookmark

### Expected behavior
* URL does not load

### Actual behavior
* URL loads

I tried doing the same with data: URIs and got the expected behavior. 

### Device information

* Android device:  Xoami Mi4 Android 6
* Fenix version: Nightly 2015717377

**Comment by softvision-miralobontiu** [comment]
I reproduced the issue on the latest Nightly build from 11/2 with Samsung Galaxy Tab S6 (Android 10).
