### ISSUE TITLE
[Logins] Password "eye" icon is fuzzy

### ISSUE THREAD

**Issue by AmyYLee** [mozilla-mobile/fenix#7779]
Hi, 

The icon is fuzzy in the text field. It's more noticeable in Dark theme. There was a related issue that was filed and fixed in #7122 for the icon in Settings -> Logins

<img width="409" alt="Screen Shot 2020-01-16 at 7 13 12 PM" src="https://user-images.githubusercontent.com/5992746/72573609-48727f80-3894-11ea-8239-233807d4c9ca.png">
<img width="421" alt="Screen Shot 2020-01-16 at 7 13 54 PM" src="https://user-images.githubusercontent.com/5992746/72573646-6213c700-3894-11ea-858a-dfc53c6e7a58.png">

**Comment by ekager** [comment]
Opened https://github.com/mozilla-mobile/android-components/pull/5618 for updating those icons in AC

**Comment by sv-sdeiac** [comment]
Hello, I can confirm that this issue is fixed using the latest version of Firefox Preview Nightly 1/21 #20210606.

Devices:
- Nexus 5 (Android 6.0.1);
- Nokia 6 (Android 7.1.1);
- Motorola Moto G6 (Android 8.0);
- Samsung Galaxy Note 8 (Android 9).
