### ISSUE TITLE
Install a PWA to my home screen

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/fenix#778]
### User Story
As a user, I want to be able to install a PWA to my home screen, so I can launch it later directly from my homescreen similar to a standalone app.

#Acceptance Criteria
-I can install a PWA to my homescreen
-The launcher icon uses the PWA's icon (web app manifest)

**Comment by bennypowers** [comment]
I'm looking forward to WebAPK support in a Mozilla browser

**Comment by reinhart1010** [comment]
Duplicate: https://groups.google.com/forum/m/#!topic/fenix-nightly/y0s-eiLwA0o
