### ISSUE TITLE
[Bug] Confusing sync state for an old account

### ISSUE THREAD

**Issue by sflorean** [mozilla-mobile/fenix#7784]
## Steps to reproduce
1. Go to Settings -> Account;
2. Observe the sync state.

### Expected behavior
"Syncing"/"Sync now" is displayed and "Last synced: x minutes ago" on the second row.

### Actual behavior
- The sync state is "never".  If it's forced manually, last synced is Jan 1, 1970.
- Tapping on the "back" arrow, then back to step 2, the sync state is again on never.

### Note
- Not reproducible on Fennec and with newer accounts. 

### Device information
* Android device: Google Pixel (Android Q), Xiaomi Mi Pad 2 (Android 5.1) - x86 architecture.
* Fenix version: Nightly 01/16.

![20200117_102543](https://user-images.githubusercontent.com/58466444/72596117-01c46a00-3914-11ea-8bdb-b18e6a718cd9.gif)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-15269)

**Comment by softvision-miralobontiu** [comment]
I was able to reproduce this issue on the latest Beta 8.0.0-beta.2 with Samsung Galaxy Tab S6 (Android 10).
If forced sync manually displays: Last synced: 1 Jan 1970.

**Comment by delia-pop** [comment]
This is still reproducible on Firefox Beta 103.0.0-beta.1 with tablet Huawei MediaPad M2 (Android 5.1.1).
