### ISSUE TITLE
Show blocking Migration UI when Search Widget is clicked.

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/fenix#7788]
Taken from https://github.com/mozilla-mobile/android-components/issues/5509#issuecomment-573504035

In Fenix's [`SearchWidgetProvider`][0], it creates an intent to go straight to the `HomeActivity` and therefore by-passing our Intent Processor. 

What we should do, is refactor that code so that it does go through the intent processor and make a `SearchWidgetIntentProcessor` to handle this intent mutation.

We need to make this change in:
 1. [`createTextSearchIntent`][1]
 2. [`createVoiceSearchIntent`][2]

[0]: https://github.com/mozilla-mobile/fenix/blob/master/app/src/main/java/org/mozilla/gecko/search/SearchWidgetProvider.kt
[1]: https://github.com/mozilla-mobile/fenix/blob/master/app/src/main/java/org/mozilla/gecko/search/SearchWidgetProvider.kt#L106
[2]: https://github.com/mozilla-mobile/fenix/blob/master/app/src/main/java/org/mozilla/gecko/search/SearchWidgetProvider.kt#L116

**Comment by jonalmeida** [comment]
This turned out to be a smaller change than expected since the voice search activity re-directs to the IntentProcessorActivity already which is great.

I've filed [a follow-up](https://github.com/mozilla-mobile/fenix/issues/7791) to re-evaluate the intent processors in different places to see if they should all be set in the `IntentReciverActivity`. That work is outside the scope of this ticket, so I'm doing the minimal required in order to fix that.

**Comment by LaurentiuApahideanSV** [comment]
@jonalmeida Hello! Can you please provide steps to reproduce this? Thanks!

**Comment by jonalmeida** [comment]
@LaurentiuApahideanSV 

## STR:
1. Set a Fennec search widget on the homescreen.
2. Start a migration build.
3. While migrating, go to the homescreen and click on the search widget.

## Expected:
1. Click on the search widget should bring up the migration UI only.

## Actual:
1. The search widget opens the search UI in Fenix (therefore evading the migration UI).

**Comment by LaurentiuApahideanSV** [comment]
Verified as fixed on Migration Build 8: Firefox Preview Nightly (Build #2015722195) GV: 74.0a1-2020020703551 2/10 using OnePlus 6T (Android 9) and Samsung Galaxy S8+ (Android 8.0.0)
