### ISSUE TITLE
Refresh the currently displayed page in a PWA

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/fenix#779]
### User Story
As a user, I want to be able to refresh the currently displayed page in a PWA, so I can see updated content. 

Since there's no browser chrome in most display modes there is no way to refresh the current page. In Chrome this is done by using the pull-to-refresh gesture.

### Acceptance Criteria
I can refresh my currently displayed page in PWA

**Comment by NotWoods** [comment]
A-C supports this via the site controls notification, so once PWA support is merged this issue can be closed.
