### ISSUE TITLE
Pageload experiment: -O2, -Oz build flags

### ISSUE THREAD

**Issue by liuche** [mozilla-mobile/fenix#7795]
_edit: see https://github.com/mozilla-mobile/fenix/issues/7795#issuecomment-861569546 for what the next steps for this issue are._

### Why/User Benefit/User Problem
Switching to the -O2 flag has [pageload perf improvements](https://bugzilla.mozilla.org/show_bug.cgi?id=1591725#c36), but increases apk size by ~6MB.

Need this experiment to measure tradeoffs.

### What/Requirements
- [x] Stability experimentation on 3.2 1/22-1/27 w/ GV 74 Nightly
- [ ] A/B test on Firefox Preview Release (pending Phase 1): 1/27-2/14 w/ GV 73 Beta
- [ ] Decide which version of GV to use for upcoming releases
- [ ] Update GV version in AC right before 3.3 goes out

This experiment would be run in staged rollout through Google Play, because Mako doesn't have this capability. Johan is assisting with this.
Corey from the Data Science team is involved in analyzing the results for retention.

### Acceptance Criteria (how do I know when I’m done?)
Data Science has results that allow us to make a perf decision.

[Meeting notes](https://docs.google.com/document/d/1JN-t5wr5fi1PLvzKMBtS_XMCd8Hd6gAXBF7SIDFnieQ/edit)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-15275)

**Comment by yoasif** [comment]
Don't want to spam here, but I think this is a no-brainer - if it actually results in pageload performance, a larger apk size pays for itself in terms of marketshare and people willing to try the browser because of the page load performance. 

I guess the unknown data point here (that feels very significant) is what the actual tradeoff here is -- how much larger is the apk?

**Comment by liuche** [comment]
https://crash-stats.mozilla.org/report/index/c0845347-0e97-4402-ae61-6cb020200125

**Comment by liuche** [comment]
New crashes on 73b: https://crash-stats.mozilla.org/topcrashers/?product=Fenix&version=73.0b0

**Comment by ecsmyth** [comment]
Updated pre-experimental impact [analysis](https://iodide.telemetry.mozilla.org/notebooks/345/?viewMode=report). Initial phase 2 experiment results expected o/a Feb 18

**Comment by ecsmyth** [comment]
Initial analysis of phase 2 data found no statistically significant difference in crash rates and a statistically significant improvement in page load performance.

**Comment by ecsmyth** [comment]
[Plan for phase 3](https://docs.google.com/document/d/17bi7QeqlusbBVTBrAoIDACc0lQC78JEnv6Vh-IfZdvw/edit#)

**Comment by liuche** [comment]
Update here: We'll be rolling out 4.2 with GV Beta 75, which does not have the experiment enabled.

**Comment by lnicola** [comment]
This still sounds like it might be worth doing?

**Comment by acreskeyMoz** [comment]
We didn't find enough evidence of performance improvement in the experiment to justify the increase in APK size.

That being said, this strategy, choosing build optimization that favors speed, still has future potential.
• We may be able to better measure performance in the wild at a future date
• We may be able to reduce the APK size and thus "pay for" the increase in size that this change leads to
• There is another build option `-Os`, that's also faster than what we use now, but leads to a smaller increase in APK size that `-O2`

**Comment by lnicola** [comment]
Ah, I just read through the discussion in https://bugzilla.mozilla.org/show_bug.cgi?id=1670948. I still think the measured improvements like in https://bugzilla.mozilla.org/show_bug.cgi?id=1591725#c46 are more relevant than the A/B testing results (if Firefox got 2x faster, most the I know wouldn't use it more), but at least it was tried.

**Comment by acreskeyMoz** [comment]
Yes, I'm also in favor of exploring this change again.
I just brought it up with my manager to consider for future mobile projects.

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807359

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
