### ISSUE TITLE
[Bug] Slower menu opening animation than Fennec

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/fenix#7797]
Reported on https://www.reddit.com/r/firefox/comments/epy3qn/a_brand_new_browsing_experience_arrives_in/feoo307/

## Steps to reproduce

1. Tap on meatball menu button

### Expected behavior

Same speed/fluidity as on Fennec.

### Actual behavior

7 frames slower than Fennec.

Firefox for Android 68:

>Time from touch to menu visible: ~12 frames

Firefox Preview

> Time from touch to menu visible: ~19 frames

>The long animation on Preview makes it feel even slower than it is, but it's definitely much slower than FF68.

See screencast here: https://gateway.ipfs.io/ipfs/QmbVPQaeNMXwZmFE6bXjJqBfmDFRJ3NBis975F5BjygdhD/bug.mp4

**Comment by mcomella** [comment]
Dupe #14340 – these issues serve the same purposes and that issue has more recent debug info.

Sorry we missed this one 😓
