### ISSUE TITLE
Share from my installed PWA to other installed (native) apps

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/fenix#780]
### User Story
As a user, I want to share from my installed PWA to other installed (native) apps, so I can have a seamless share experience between apps.

### Acceptance Criteria
-I can share from my installed PWA to other installed native apps.

### Dependencies
Web Share API: https://developers.google.com/web/updates/2016/09/navigator-share
Android Components bug: mozilla-mobile/android-components#3486
GeckoView bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1402369

**Comment by NotWoods** [comment]
Android Components bug: mozilla-mobile/android-components#3486
GeckoView bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1402369

**Comment by AndiAJ** [comment]
Hi @NotWoods ,not sure what is the proper way to test this, and would really appreciate your help. :relaxed:

I've checked this matter on the latest Nightly Build #13450608 from 12/11 using a Google Pixel 3 a (Android 9) and noticed the following while Trying to share from the 9GAG PWA:

►By tapping one by one on each of the featured 9GAG sharing options, a Fenix custom tab is opened
![20191212_163902](https://user-images.githubusercontent.com/51314259/70633931-03768000-1c3a-11ea-8846-028ccbf530e2.gif)


►By tapping the "More button" the Android sharing options context menu shows up and sharing seems to be working to:
![20191212_164004](https://user-images.githubusercontent.com/51314259/70633636-88ad6500-1c39-11ea-9161-6b899521b383.gif)


►By long tapping on content (this is applicable only for pictures in this case, no Fenix context menu is opened for GIF's or Videos)
![20191212_164320](https://user-images.githubusercontent.com/51314259/70633794-c7dbb600-1c39-11ea-9c53-e9efad72bc53.gif)

Please review and let me know how should I check this matter.

**Comment by NotWoods** [comment]
1. Open a site that uses the Web Share API, such as https://web-share.glitch.me/.
2. Initiate a share through the website, not browser UI (Use the "Share" button on that site).
3. Depending on the share target,
a. It should successfully share the text and URL when sent to an Android app (Check out this great poem about a Jabberwocky. https://en.wikipedia.org/wiki/Jabberwocky).
b. It shoudl successfully share the title and URL when sending a tab.

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **Nightly Build #13470611 from 12/13** using the following devices:
• Google Pixel 3a (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)

✔️ Twitter - Tweet
✔️ Twitter - DM
✔️ Facebook Messenger
✔️ Skype
✔️ WhatsApp

► Video
![20191214_112708](https://user-images.githubusercontent.com/51314259/70790781-6e40cc00-1d9e-11ea-8cae-1a529a108b58.gif)

@NotWoods Thanks for helping me out! :relaxed:
