### ISSUE TITLE
[Bug] (regression) using autocompleted domains opens search engine instead of website

### ISSUE THREAD

**Issue by cadeyrn** [mozilla-mobile/fenix#7800]
### Steps to reproduce

1. open the address bar
2. start typing a domain
3. select an autocompleted domain

### Expected behavior

The website opens.

### Actual behavior

A search in the default search engine will performed.

It does not happen with all domains. I does happen with camp-firefox.de but not with mozilla.org. 

This has to be a relatively recent regression.

### Device information

* Android device: OnePlus 7T Pro McLaren Edition / Android 10
* Fenix version: master branch revision ffb2e72b97b1d066c040087dca2d2035f7e7e9b0

**Comment by cadeyrn** [comment]
Probably an AC issue because the Reference Browser is also affected…

**Comment by cadeyrn** [comment]
@hawkinsw: Changing the following line:

https://github.com/mozilla-mobile/fenix/blob/ffc441f12a350e8fc3f02f445af22166044f9c19/app/src/main/java/org/mozilla/fenix/HomeActivity.kt#L324

from `searchTermOrURL.isUrl()` to `searchTermOrURL.isUrlStrict()` fixes the issue so I guess it's a regression from https://github.com/mozilla-mobile/android-components/pull/5384.

Could you please have a look? It's a really annoying regression.

**Comment by hawkinsw** [comment]
I will absolutely take a look!

**Comment by hawkinsw** [comment]
Fix is ready. I will PR tonight. Sorry!

**Comment by cadeyrn** [comment]
Fixed in Fenix Nightly. Thank you!

**Comment by hawkinsw** [comment]
Glad to hear it! Sorry again about causing the problem! Thank you for reporting!
