### ISSUE TITLE
[Bug] Open Bookmark in private tab

### ISSUE THREAD

**Issue by rome-legacy** [mozilla-mobile/fenix#7801]
## Steps to reproduce
start firefox preview
switch to private browsing
open bookmarks menu
select bookmark

### Expected behavior
bookmark is opened in private tab

### Actual behavior
bookmark is opened in regular tab
Ps:same behavior also on my tablet

### Device information
samsung galaxy s8+
android 9
ff preview
dark mode
3.0.2 (Build #20081833)
📦: 24.0.1, ee4587f74
🦎: 71.0.1-20200108003105

**Comment by cadeyrn** [comment]
This already works as expected in Fenix Nightly (not yet in the stable Fenix 3.0 release).

**Comment by kbrosnan** [comment]
Closing as working on Nightly builds. This will be fixed on the release builds in a few weeks.
