### ISSUE TITLE
[Bug] Crashes with an established VPN connection

### ISSUE THREAD

**Issue by ilativ** [mozilla-mobile/fenix#7803]
## Steps to reproduce
If I open a VPN Connection with Wirequard for Andtroid (v0.0.20191220) Fenic crashes immediately.
After I close the VPN connection I can open Fenix with out crashes.

Please let me now if you need additional information from me.

### Device information
* Android device: Nokia 8, Android Version 9
* Fenix version: 3.0.2

**Comment by bthylafh** [comment]
I am having this trouble as well, which I believe started with version 3.0 of Fenix.  I'm using the ProtonVPN 2.0 app for VPN.  logcat, dmesg, and device info log attached.

[logs-2020-01-18-19-51-40.zip](https://github.com/mozilla-mobile/fenix/files/4082139/logs-2020-01-18-19-51-40.zip)

**Comment by bthylafh** [comment]
Focus has an identical problem, #4458.

**Comment by bthylafh** [comment]
This bug seems to have been fixed with Fenix v3.2.0.

**Comment by softvision-miralobontiu** [comment]
Verified with ExpressVPN version 7.9.2 on the latest Nightly from 3/2, and on RC 3.2.1, and no crash.
I'll close this issue.

**Comment by ilativ** [comment]
I don't have that problem with the current version.
Thanks
