### ISSUE TITLE
[Bug] Unknown protocol page displayed when accessing an article from zhihu.com

### ISSUE THREAD

**Issue by softvision-miralobontiu** [mozilla-mobile/fenix#7809]
## Steps to reproduce
1. Open https://www.zhihu.com/
2. Tap on an article.

### Expected behavior
The selected article is opened in the same tab. No errors are displayed.

### Actual behavior
The article is opened in the same tab but after a few seconds, an "Unknown protocol" page is displayed. Reproducible even with ETP off.

### Device information
* Android device: Google Pixel (Android 10), HTC Desire 820 (Android 6.0.1)
* Fenix version: 1/17 Nightly build, Fennec RC 68.4.1
* Not reproducible on Chrome

[unknown protocol.txt](https://github.com/mozilla-mobile/fenix/files/4086215/unknown.protocol.txt)

![20200120_143657_Trim](https://user-images.githubusercontent.com/40694158/72727914-c4bada80-3b94-11ea-9851-5c644fa55342.gif)

**Comment by cadeyrn** [comment]
Related: #7331.

**Comment by kbrosnan** [comment]
Seems like a dupe
