### ISSUE TITLE
Visual feedback when a PWA is starting

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/fenix#781]
### User Story
As a user, I want to get visual feedback that a PWA is starting, so I can differentiate between a regular tab and a PWA.

### Acceptance Criteria
-When I tap on a PWA shortcut, I know that a PWA is starting.
-I can differentiate between a regular tab, a homescreen shortcut, and a PWA

https://developer.mozilla.org/en-US/docs/Web/Manifest#Splash_screens

**Comment by colintheshots** [comment]
This should be as simple as setting a theme with a window background on the PWA container in the AndroidManifest and then changing the theme after we're loaded to avoid either overdraw or seeing the splash screen through any screens.

**Comment by pocmo** [comment]
Closing in favor of #2294
