### ISSUE TITLE
[Bug] Buggy typing when replacing text in the email field on accounts.firefox.com 

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#7810]
## Steps to reproduce
1. Go to Settings>Sync> Use email.
2. In the email field, type something, then move the text cursor somewhere in the middle and try to add or replace characters. 
### Expected behavior
Can type, delete or replace text on text fields.
### Actual behavior
Characters are typed in at the wrong position, or the wrong chars are being deleted.
![20200120_173159](https://user-images.githubusercontent.com/4037709/72738886-39007880-3bab-11ea-8ec5-701cee14afee.gif)

Can't reproduce on other text fields like on amazon/facebook login pages, or on the Fenix search bar.
### Device information

* Android device: HTC (Android 9), Nexus 5 (Android 6)
* Fenix version: Nightly 1/20

**Comment by softvision-miralobontiu** [comment]
I was able to reproduce this issue on the 11/2 Nightly build with Samsung Galaxy Tab S6 (Android 10).
