### ISSUE TITLE
[Logins] Update button and text Link colours in login capture panel

### ISSUE THREAD

**Issue by AmyYLee** [mozilla-mobile/fenix#7813]
Hi, 

Can you please update the colour of the text link and button ##9059FF and verify that it's 14pt bold. Also text size in the text input field should be the same size as the headline. Thanks!
![Screen Shot 2020-01-20 at 12 49 44 PM](https://user-images.githubusercontent.com/5992746/72747702-646f6d00-3b83-11ea-9a8f-e7d1f95afaf8.png)

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly Build #20760607 from 3/16`** using a Google Pixel 3a (Android 9)

► Username input field size same as  the headline
![16uzr](https://user-images.githubusercontent.com/51314259/76766849-50ba3e80-67a1-11ea-9b74-3e5647c60b5a.jpg)

► Button text size
![14sv](https://user-images.githubusercontent.com/51314259/76766721-19e42880-67a1-11ea-9178-2875219091a9.jpg)
![14dnt](https://user-images.githubusercontent.com/51314259/76766727-1b155580-67a1-11ea-9843-00ae78c95500.jpg)

► Button colors
![Save](https://user-images.githubusercontent.com/51314259/76766601-ec977a80-67a0-11ea-8789-14d8ee0763cd.png)
![Don'tSave](https://user-images.githubusercontent.com/51314259/76766603-ee613e00-67a0-11ea-850e-f41c8e0666a0.png)
