### ISSUE TITLE
[ETP] Shield icon colour needs updating

### ISSUE THREAD

**Issue by AmyYLee** [mozilla-mobile/fenix#7814]
Hi, 

The shield icon colour is using the Light theme palette on Dark theme. Please see reference below for correct colour for icon in Dark theme. It should be the same colour as the shield in Private browsing. Thanks

![Screen Shot 2020-01-20 at 12 52 49 PM](https://user-images.githubusercontent.com/5992746/72747952-08f1af00-3b84-11ea-8151-f763024779fa.png)

**Comment by ekager** [comment]
@AmyYLee It is using the same Lottie file as private mode. Is it possible there are transparencies in the icon that are displaying differently on the black background? 
You can see here when I force the background in dark theme to white it looks correct:
![Screenshot_20200121-104253](https://user-images.githubusercontent.com/25442310/72833081-e79fca00-3c3a-11ea-9601-0f397ebea178.png)

We will probably need a new lottie json file with flat colors and no transparency

**Comment by AmyYLee** [comment]
@ekager 
Hi, can you test this asset out and see if it works? If it does then can you swap out the shield in Dark them and Private browsing? Thanks!

https://drive.google.com/file/d/1u3ZL4lvCU5UqzOpfrDkzqMigITgCptbQ/view?usp=sharing

**Comment by ekager** [comment]
Yep that looks better! Updating the dark icon now
