### ISSUE TITLE
[Bug] Tab closed does not dissapear

### ISSUE THREAD

**Issue by andreicristianpetcu** [mozilla-mobile/fenix#7816]
## Steps to reproduce
Close a tab
### Expected behavior
Close tab notification appears and then it goes away
### Actual behavior
Tab closed stays on the screen
![Screenshot_20200121-013626_Firefox_Nightly](https://user-images.githubusercontent.com/922368/72763940-9ff35100-3bee-11ea-8072-e57cf93faeb8.png)

### Device information

* Android device: OnePlus 5t
* Fenix version: Nightly

**Comment by cadeyrn** [comment]
Duplicate of #7799.
