### ISSUE TITLE
Improve startup perf of SessionManager.restore & enclosing func (35.88ms perfTest)

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#7819]
We're trying to move everything non-essential until after visual completeness in order to improve startup time. SessionManager.restore runs a blocking operation on the main thread during startup. In theory, it's preferable to:
- ~~Run this operation on a background thread to avoid blocking startup but having the data available when needed (assuming it's actually restoring the tabs)~~!
  - Christian looked into this:  SessionManager is not thread safe so we shouldn't do this now.
- If that's not possible, run this after the first frame is drawn to improve perceived performance.

`SessionManager.restore` runs inside a coroutine but I'm not sure where this coroutine gets launched.

In the same coroutine, AutoSave.periodicallyInForeground is also launched: I assume it should be straightforward to move them together.

---

_old comment 0_

`SessionManager.restore` runs inside a coroutine but I'm not sure where this coroutine gets launched.

In the same coroutine, AutoSave.periodicallyInForeground is also launched: I assume it should be straightforward to move them together.

`SessionManager.restore` takes 23.75ms (P2 perfTest) and the function that calls it takes 35.88ms. I'm not sure why this needs to happen on the main thread.

### Priority
Difficulty: 3. Discussion with a-c, may not be easy to call async.

Impact:
- perfTest: 23.75ms; 35.88ms for enclosing function

### Questions
* Is there some work that can be done here _after_ startup?
* Why can't SessionManager.restore be called from a background thread, e.g. while the UI is inflating?

**Comment by jimporter** [comment]
@mcomella Is the idea here to change the implementation of `SessionManager.restore`, or just use it in a smarter way? Is there anyone in particular I should ping on the a-c (android components?) team?

**Comment by mcomella** [comment]
@jimporter I added some proposals to the top of comment 0. I'm not sure who would be a good person to work with – maybe there's something in blame.

**Comment by mcomella** [comment]
Christian says the sessionManager will go away when the lib state refactoring is complete in a-c but let's make small wins now.

**Comment by mcomella** [comment]
Triage: we think this may be too complicated to address – and it may solve itself later as per the previous comment – so waiting to triage for later if it's still an issue.

**Comment by csadilek** [comment]
We looked into this and confirmed it's a non-trivial fix. While `restore` is thread-safe it notifies its observers on the calling thread. Since all observers expect to update UI state this will cause various issues. In the new `bowser-state` module (which will replace `browser-session` and the `SessionManager`) this has already been taken care of and all observer will be notified on the main thread.

**Comment by mcomella** [comment]
Closing: we're addressing startup holistically.
