### ISSUE TITLE
[Bug] beta fennec bustage 

### ISSUE THREAD

**Issue by Archaeopteryx** [mozilla-mobile/fenix#7826]
https://treeherder.mozilla.org/logviewer.html#?job_id=285659523&repo=fenix

This is from #7806 / https://github.com/mozilla-mobile/fenix/commit/02b4582c8d2c425b1bcf83fd0956d17425d5c7e0

[task 2020-01-20T18:09:00.228Z] > Task :app:processGeckoBetaFennecBetaResources
[task 2020-01-20T18:09:30.228Z] > Task :app:compileGeckoBetaFennecBetaKotlin
[task 2020-01-20T18:09:34.828Z] e: /builds/worker/checkouts/src/app/src/migration/java/org/mozilla/fenix/MigratingFenixApplication.kt: (58, 35): No value passed for parameter 'store'
[task 2020-01-20T18:09:34.828Z] 
[task 2020-01-20T18:09:34.828Z] > Task :app:compileGeckoBetaFennecBetaKotlin FAILED

**Comment by kbrosnan** [comment]
Did this get resolved in recent betas?
