### ISSUE TITLE
[Bug] The "Save password" dialogue is not dismissed when user chooses to save

### ISSUE THREAD

**Issue by softvision-miralobontiu** [mozilla-mobile/fenix#7828]
## Steps to reproduce
1. Make sure you have a clean profile.
2. Open a page that requires to sign in.
3. After entering valid credentials, and asked if you want Firefox to save your password, tap on "Save".

### Expected behavior
The credentials are saved and the dialogue is dismissed.

### Actual behavior
The credentials are saved but the dialogue is not dismissed. The only way the user knows the credentials were saved is going to Settings - Logins and passwords - Saved logins.

### Device information
* Android device: Google Pixel (Android 10)
* Fenix version: 1/21 Nightly build (#20210607)

[logcat-save.txt](https://github.com/mozilla-mobile/fenix/files/4091224/logcat-save.txt)

![20200121_151330_Trim](https://user-images.githubusercontent.com/40694158/72808404-27c67300-3c62-11ea-8739-509e3601d286.gif)

**Comment by ekager** [comment]
Should be fixed by https://github.com/mozilla-mobile/android-components/pull/5659https://github.com/mozilla-mobile/android-components/pull/5659

**Comment by sv-sdeiac** [comment]
Verified as fixed using the latest version of Firefox Preview Nightly 1/28 #20280606.
Devices:
- Nokia 6 (Android 7.1.1);
- OnePlus 5T (Android 9).
