### ISSUE TITLE
[Bug] Profile_created_date is sent in local time (instead of UTC)

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#7830]
profile_created_date metric is getting sent in local time. This means we can't compare dates/times created since they're not normalized over UTC.

**Comment by magorlick** [comment]
In analytics we need to know when profile creation occurs in local time as well as UTC.  I don't mind that profile_created_date is derived from local time, however I need the time to be included with the date.  If we have the timestamp we are enabled to transform profile_created_date into either timezone depending on our use case.  Thanks!

**Comment by Dexterp37** [comment]
@sblatz ,what's `profile_created_date` here? Is this something glean reports?
