### ISSUE TITLE
[Bug] Enable about:config in debug geckoBeta builds

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#7831]
Currently about:config is set to false in our [debug builds](https://github.com/mozilla-mobile/fenix/blob/master/app/src/geckoBeta/java/org/mozilla/fenix/engine/GeckoProvider.kt#L43-L48) compared to true in our [nightly builds](https://github.com/mozilla-mobile/fenix/blob/master/app/src/geckoNightly/java/org/mozilla/fenix/engine/GeckoProvider.kt#L48-L54). 

I'm wondering if this is because our `GeckoBeta` provider gets used for release as well? If that's the case it would be nice to check the buildConfig flag if we're on debug and enable it just for debug builds as this can be really useful for testing!

**Comment by ekager** [comment]
@sblatz do you still care about this?

**Comment by sblatz** [comment]
This is a small change and I think we should just do it tbh

**Comment by kbrosnan** [comment]
Do we even have this build variant any more? We enabled about:config for beta in q2 or so.
