### ISSUE TITLE
Use and tint mozac version of password icons (hide and reveal)

### ISSUE THREAD

**Issue by ekager** [mozilla-mobile/fenix#7836]
I recently added the password hide and reveal icons to AC (as mozac_ic_password_reveal and mozac_ic_password_hide), so we should use their versions and delete ours so we don't have duplicate resources.

We'll need to add a primaryColor tint where we use it in `SavedLoginSiteInfoFragment` and `fragment_saved_login_site_info`

**Comment by KMaragh** [comment]
Hey! I can take this :)
