### ISSUE TITLE
After a sleep period, the app opens with a black screen

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#784]
## Steps to reproduce
1. Open a tab, e.g. google.com
2. Leave the device at least ~15-20 min in sleep mode.
3. Unlock the device and check the app.
note:  The device I used has sleep set after 30 seconds and a lock screen.
### Expected behavior
The app is displayed normally.
### Actual behavior
The app's page view is black, the URL bar is empty.
![1551453653662](https://user-images.githubusercontent.com/4037709/53648098-ba73b300-3c47-11e9-8122-e382d8e15488.JPEG)

### Device information

* Android device: Huawei P20 lite (Android 8.0), 
* Fenix version: 1.0.1909 (Build #10601230)

**Comment by abodea** [comment]
Hello, I was able to reproduce this issue on the following devices: **`Google Pixel 3XL(Android P) and Samsung Galaxy Note 9 (Android 8.1.0)`** on  **`Fenix version: 1.0.1909 (Build #10601230)`**.

**Comment by sv-ohorvath** [comment]
Verified this doesn't reproduce anymore on Nexus 5 (Android 6.0.1), Samsung S8 (Android 9). Master build 3/22.
