### ISSUE TITLE
Add a PWA button to the location bar

### ISSUE THREAD

**Issue by bbinto** [mozilla-mobile/fenix#785]
- technical description where needed, some details on how to do it
- eng task doesn't need to be assigned to a milestone

**Comment by Cheap-Skate** [comment]
Please can you make this optional in about:config?  I dislike the PWA button & I think am not alone:- some like/some hate.

If you search r/firefox for PWA you'll see there are posts about adding a custom uBlock Origin filter to Fennec to prevent the PWA button appearing, and 
https://bugzilla.mozilla.org/show_bug.cgi?id=1420065

Thanks!

**Comment by vesta0** [comment]
Will be addressed in #768
