### ISSUE TITLE
[Bug] Beta 3.2.0-beta.1 froze while browsing

### ISSUE THREAD

**Issue by softvision-miralobontiu** [mozilla-mobile/fenix#7852]
## Steps to reproduce
1. Open Fenix Beta and start browsing.
2. Had about 6 tabs opened.

### Expected behavior
Fenix doesn't freeze.

### Actual behavior
Fenix Beta froze. Closing and reopening the app, doesn't fix the problem. Deleting data when quitting doesn't solve the problem.

### Device information
* Android device: Google Pixel (Android 10)
* Fenix version: Beta 3.2.0-beta.1

[logcat.txt](https://github.com/mozilla-mobile/fenix/files/4096423/logcat.txt)

![freeze_Trim](https://user-images.githubusercontent.com/40694158/72884610-138c7f80-3d0f-11ea-8ffa-93715c9a8d75.gif)

**Comment by liuche** [comment]
That's pretty bad! I can't seem to repro this though. Is there any other information @softvision-miralobontiu that you have found about what could be causing this?

**Comment by sv-ohorvath** [comment]
@liuche We couldn't reproduce it either, with reliable steps. It happened today once on a Samsung Galaxy Tab 3 (Android 8.0). The only thing the 2 had in common was browsing through tabs, no sync accounts, no changes on ETP. We'll continue to investigate.

**Comment by kbrosnan** [comment]
The logcat only shows an ANR with Facebook. Not clear if there is anything useful to do here.

`2020-01-22 11:52:44.567 26552-26552/? E/ACRA: Initializing ANR detector for process: com.facebook.katana`

**Comment by softvision-miralobontiu** [comment]
Hi!
I've tried reproducing this issue on Beta 3.2.0-beta.3 with Sony Xperia Z5 Premium (Android 7.1.1), and Google Pixel (Android 10), but with no luck.
I'll close this issue.
