### ISSUE TITLE
[Bug] Bookmark's edited name is not saved after selecting in which folder to save

### ISSUE THREAD

**Issue by softvision-miralobontiu** [mozilla-mobile/fenix#7854]
## Steps to reproduce
1. Open a page and bookmark it.
2. Tap on "Edit" from the snackbar.
3. Edit the "Name", then tap on the folder to select where to save the new bookmark.
4. After selecting in which folder to save, tap the back arrow and observe.

### Expected behavior
The edited name is still displayed.

### Actual behavior
The edited name is not saved. If the page had a name, that one is displayed, if it didn't, the "Name" section is blank.

### Device information
* Android device: Google Pixel (Android 10), Google Pixel 3A (Android 9)
* Fenix version: Beta 3.2.0-beta.1, 01/22 Nightly build

![20200122](https://user-images.githubusercontent.com/40694158/72886396-6ca9e280-3d12-11ea-83fb-1251b0dc814a.gif)

**Comment by sv-sdeiac** [comment]
The same issue is reproducible also editing the bookmark folder name using the same steps as in the description.

Device:
- Samsung Galaxy Tab S3 (Android 8).
- Fenix version: Beta 3.2.0-beta.1

**Comment by juan-goncalves** [comment]
I'd like to work on this issue, is it still available?

**Comment by ekager** [comment]
Yep! Go for it @juan-goncalves

**Comment by juan-goncalves** [comment]
As the `EditBookmarkFragment` `onViewCreated` method loads the bookmark data from a `PlacesBookmarkStorage`, when we navigate to another screen and return, the view is recreated and the `onViewCreated` method is triggered once again, querying the bookmark storage and updating the fragment's `EditText`s with the saved values, losing the user's input.

A simple fix would be to compare the bookmark node from storage with the one that the fragment already had a reference to (in the `bookmarkNode` attribute), updating the `EditText`s only if they are effectively different

**Comment by sflorean** [comment]
Verified as fixed on Nightly 5/19 and 5.1-beta.1 builds.
Devices: Nokia 6 (Android 7.1.1), Samsung Galaxy Note 10 (Android 10), Xiaomi Mi Pad 2 (Android 5.1).
