### ISSUE TITLE
[Bug] Download links doesn't work

### ISSUE THREAD

**Issue by xxkfqz** [mozilla-mobile/fenix#7855]
## Steps to reproduce
Tap on any download link and then tap on "Download" button

### Expected behavior
File will be downloaded

### Actual behavior
Fail immediately after starting download. "Try again" caughts the same bug

### Device information
* Android device: Lenovo A2010 (Android 5.1.1)
* Fenix version: v3.1.0

![1](https://user-images.githubusercontent.com/52203435/72891376-e99a8380-3d35-11ea-99d7-ae4f5d1d62d7.png)

**Comment by Sparky93** [comment]
Hello, I'd like to work on this issue. Can somebody assign me please?

**Comment by Sparky93** [comment]
Sorry, I'm going to focus my work on migration tickets rather than this.

**Comment by kglazko** [comment]
@Amejia481 Do we currently support downloading APK files, or would this be a functionality we need to implement?

**Comment by Amejia481** [comment]
We currently support them, I did a test on nightly and it worked as expected!

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly Build 200515 from 5/15`** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)

► Video
![20200515-115052](https://user-images.githubusercontent.com/51314259/82032508-fb68b380-96a3-11ea-9dca-5163f1e1d5e5.gif)
