### ISSUE TITLE
UX nit:- on Home screen, Google search box sometimes "snaps" to endpoints but not always

### ISSUE THREAD

**Issue by Cheap-Skate** [mozilla-mobile/fenix#786]
Open several tabs
Move to Home screen
Drag scroll up about an inch until Google search box is in the center of its travel 
release finger
Typically the Google search box "snaps" under its own power back to one or other endpoint (middle or top of screen)
but not always - sometimes it sticks in its center position.

Fool around with drag scrolling like this on the Home screen, I hope you see the Google search bar switch between the two behaviors:- 
(a) snap to endpoint when finger is released
(b) remain in middle position when finger is released
I don't know what causes the transition between behavior (a) and (b)

I much prefer behavior (b) as explained in #695

**Comment by Cheap-Skate** [comment]
I think I understand the two behaviors:- If the Google search bar stops in the middle of its travel as the result of a DRAG SCROLL, I get case (a). If it stops in the middle of its travel because of a FLING, I get case (b). 

There is a knack to it, you need a really really gentle fling to get it to come to rest in the middle of its travel.

**Comment by Cheap-Skate** [comment]
Same as or similar to #2357?

**Comment by sblatz** [comment]
Closing this in favor of https://github.com/mozilla-mobile/fenix/issues/2357 which is addressed by https://github.com/mozilla-mobile/fenix/pull/3878
