### ISSUE TITLE
[Bug][RTL] Find in page's close button has wrong padding

### ISSUE THREAD

**Issue by fluffyemily** [mozilla-mobile/fenix#7860]
Moved over from bug filed under GeckoView https://bugzilla.mozilla.org/show_bug.cgi?id=1608208. Screenshot attached on original bug.

**Comment by ekager** [comment]
This will need to be updated in AC -> `mozac_feature_findinpage_view.xml`

![rtlissue](https://user-images.githubusercontent.com/25442310/72926212-e937c380-3d08-11ea-9248-4dd395ef3935.png)

**Comment by ayushi1998** [comment]
Hey what do i need to do for this issue?

**Comment by FoxDie12x** [comment]
Isn't this issue resolved already? I guess the padding has been fixed already... (see screen below on my device; Fenix language set to Arabic)

![Screenshot_20200311-215343](https://user-images.githubusercontent.com/1681771/76462973-e3925c00-63e2-11ea-970c-06124b2bfc51.png)

**Comment by ekager** [comment]
Looks like it has been fixed. Closing! Thanks for verifying. Please reopen if anyone is still seeing issues
