### ISSUE TITLE
Do not reload all the tabs after switching tracking protection settings

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/fenix#7867]
### Why/User Benefit/User Problem
It consumes a lot of the device resources, we may think to do something similar as how desktop is handling this use case. They have a **"reload all tabs"** button, tabs gets reload only when the button is clicked.

<img width="682" alt="image" src="https://user-images.githubusercontent.com/773158/72924972-e6949880-3d1f-11ea-84e3-bd049a76643c.png">

For more context around this suggestion please see the [bug #1609701]( https://bugzilla.mozilla.org/show_bug.cgi?id=1609701#c12).

cc: @vesta0

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-15330)

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807564

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
