### ISSUE TITLE
"Sign in" shows old content for a few seconds

### ISSUE THREAD

**Issue by cadeyrn** [mozilla-mobile/fenix#787]
### Steps to reproduce

1. open settings
2. press "Give Feedback" menu item
3. press the back button of your device
4. press the "Sign in" menu item

### Expected behavior

Firefox Account login appears immediately.

### Actual behavior

You see the "About Fenix" page for a few seconds before the Firefox Account login appears.

### Device information

* Android device: HTC U11 / Android 8.0
* Fenix version: Fenix revision c4fe44529ae9c48846f57e6fdf174e7d5ce33fda

**Comment by ekager** [comment]
Related to #513, having an InfoFragment that would go back to Settings on back press to separate these settings pages rather than opening them as a normal tab would make this cleaner. We could also open them each in a new tab

**Comment by cadeyrn** [comment]
It no longer happens.

**Comment by cadeyrn** [comment]
Still happens if you open "Give Feedback" instead of "About Fenix" before pressing the "Sign in" item.

**Comment by sv-ohorvath** [comment]
Reproducing. STR:
1. Open a webpage.
2. Close the browser and restart.
3. Go directly to Settings>Sign in. 
You can see the previous tab for a second, or at least the URL.

**Comment by sblatz** [comment]
I believe this no longer happens since we're using custom tabs to handle sign in to sync now.

**Comment by softvision-miralobontiu** [comment]
Following the STR from the above comment, I can no longer see the previous tab.
Tested with 1.0.1926 (#11750611) with LG G7 Fit (Android 8.1), and OnePlus 5T (Android 9).
