### ISSUE TITLE
[webcontent] render differ between fenix and firefox desktop and other browsers

### ISSUE THREAD

**Issue by nanake** [mozilla-mobile/fenix#7879]
## Site with issue and any steps to reproduce
1. https://indy-theme.tumblr.com/ (no need to enable desktop site) or 
   https://sweetoothgirl.tumblr.com/ (need to enable desktop site)
2. scroll to the bottom
3. click at down arrow button ↓

### Expected behavior
animate in full circle

### Actual behavior
not animate in full circle

### Does toggling Tracking Protection fix the issue? (Press the lock icon in the toolbar while on the site to see toggle)
nope

### Can you reproduce in [Firefox for Android](https://play.google.com/store/apps/details?id=org.mozilla.firefox)?
nope! legacy firefox works fine ✔️✔️✔️

### Can you reproduce in Chrome (or other non-Mozilla browser)?

I can't. all work fine
✔️ firefox desktop
✔️ chrome desktop
✔️ edge desktop
✔️ chrome mobile
✔️ edge mobile
❌ fenix

### Device information
Nokia 6.1 Plus

* Android device: 10
* Fenix version: 
Nightly 200122 20:49 (Build #20112054)
29.0.0,e1d27a294
GV: 74.0a1-20100122094859

**Comment by ekager** [comment]
@nanake I just tested these on the latest nightly, and I'm not sure what I'm looking for. Both sites seem to load when I scroll down and don't need desktop mode? Can you verify that this is fixed or provide screenshots?

**Comment by nanake** [comment]
@ekager here comes screencast.

1. open https://indy-plus-theme.tumblr.com and swipe to the bottom
2. observe at loading animation at the bottom of page
3. compare to firefox desktop.

![gifgif](https://user-images.githubusercontent.com/467392/79624318-1e5a8300-814b-11ea-9413-08dd117eb4ca.gif)

**Comment by kbrosnan** [comment]
This animates correctly for me. What device (model numbers are helpful) and Android version are you using?

**Comment by nanake** [comment]
Nokia 6.1 plus 
Android 10

**Comment by nanake** [comment]
@st3fan close without reason? why?

**Comment by nanake** [comment]
No answer 😣, I file issue 15177
