### ISSUE TITLE
stray menu item separator in settings overview (for logged out users)

### ISSUE THREAD

**Issue by cadeyrn** [mozilla-mobile/fenix#788]
### Steps to reproduce

1. open the settings
2. make sure you're not logged in

### Expected behavior

No menu item separator below the "Sign in".

### Actual behavior

There is a menu item separator below the "Sign in". You can see it on the left and on the right edge.

![screenshot_20190301-181304](https://user-images.githubusercontent.com/1100614/53654593-63251100-3c4e-11e9-8b90-86e2420981d3.png)

### Device information

* Android device: HTC U11 / Android 8.0
* Fenix version: Fenix revision c4fe44529ae9c48846f57e6fdf174e7d5ce33fda

**Comment by ekager** [comment]
Closed this in #2548
