### ISSUE TITLE
[Bug] Telemetry event for deleting a custom search engine is not sent

### ISSUE THREAD

**Issue by ValentinTimisica** [mozilla-mobile/fenix#7881]
## Steps to reproduce
- Navigate to `Settings` -> `Search`
- Have a custom search engine added
- Tap on 3 dots icon from a custom search engine -> Select `Delete`

### Expected behavior
- Telemetry event (`CustomEngineDeleted`) should be send.

### Actual behavior
- No telemetry event is sent when a custom engine is deleted.

This is a follow up to #5884.

**Comment by ValentinTimisica** [comment]
Reopen for QA.

**Comment by ValentinTimisica** [comment]
### Testing notes
@AndiAJ for this you need to verify that the "deleting a custom search engine" telemetry event (created in #5884) is sent properly.

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly Build #20280607 from 1/28`** using a OnePlus A3 (Android 6.0.1)

✔️ Delete IMDB Custom search engine - Ping **342bbdb8-2e45-4262-bb12-e4b1cf65163f**
✔️ Delete Twitch Custom search engine - Ping **305f5059-ad97-49d5-8ffa-402b09cfac18**
✔️ Delete Vimeo Custom search engine - Ping **890b2260-c7b6-429a-8455-ecf23eb917dc**

[Logcat](https://github.com/mozilla-mobile/fenix/files/4122302/deletecustom.txt)
[Glean dashboard](https://debug-ping-preview.firebaseapp.com/pings/aj-t28010)
