### ISSUE TITLE
how to set default of Fenix to open google.com when load

### ISSUE THREAD

**Issue by nakinthorn** [mozilla-mobile/fenix#7882]
how to set default of Fenix to open google.com when loaded

**Comment by NotWoods** [comment]
Hi @nakinthorn, could you provide more info and fill out the issue template?

```
### Why/User Benefit/User Problem

### What/Requirements

### Acceptance Criteria (how do I know when I’m done?)

```

**Comment by ekager** [comment]
If you're talking about changing your default search engine, it should be in Settings -> Search (and you can add a custom search engine if needed). Closing.
