### ISSUE TITLE
The amazon username/email is not filled in on the Save login pop-up 

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#7885]
## Steps to reproduce
1 Go to amazon sign in page.
2. Type in the username/email, password. Submit.
### Expected behavior
The username and password are filled-in on the save login pop-up 
### Actual behavior
Only the password is filled-in. The username is empty.
### Device information

* Android device: any
* Fenix version: Nightly 1/21.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-15340)

**Comment by SoftVision-LorandJanos** [comment]
This issue is still reproducible on the latest Nightly 101.0a1 (2022-04-29) build.
Device used: Google Pixel 4 (Android 12).

**Comment by delia-pop** [comment]
Reopening since this is still reproducible on Nightly 109.0a1.

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812064

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
