### ISSUE TITLE
[Bug] White icons on light theme, on the Save login pop-up (specific devices only)

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#7886]
## Steps to reproduce
1. Login on a website.
2. Check the left side icons next to the web address and the "Do you want..." header.
### Expected behavior
Black icons on light theme.
### Actual behavior
While icons on light theme, almost invisible.
### Device information

* Android device: LG Nexus 5, HTC Desire 820 ( both Android 6.0.1) 
* not reproducing on other OS's
* Fenix version: Nightly 1/21

**Comment by ekager** [comment]
Closing for #8577
