### ISSUE TITLE
Fennec migration - Landscape Mode - Overlapping elements on the migration onboarding screen

### ISSUE THREAD

**Issue by Diana-Rus** [mozilla-mobile/fenix#7890]
## Preconditions:
- Have Fennec installed and logged in. Have the app open.

## Steps to reproduce:
1. Replace Fennec with Fenix using a build from [here](https://firefox-ci-tc.services.mozilla.com/tasks/index/project.mobile.fenix.v2.fennec-nightly.2020.01.17.revision/e4eba42b93d58586b2afb6e13d3e57b37a5209c3).
2. Rotate the device to have the app in landscape mode.
3. Observe the migration screen UI.

## Expected Result:
The elements from the bottom half of the migration screen overlap each other, when in landscape mode.

## Actual Result: 
The elements from migration screen are correctly displayed.

## Notes:
[Screenshot](https://drive.google.com/open?id=1aNYZJgFyj9eGsVXFawUmTqrxXQu_KGMR)

## Device information:
Android device: Pixel XL (Android Q), Samsung Galaxy S8(Android 9), Motorola G4 (Android 6.0.1), 
Fenix version: Nightly migration build 01/17

**Comment by liuche** [comment]
This is a migration fix and can't be verified in Fenix Nightly, so I'm not adding the qa-needed label. Feel free to add that though it if is helpful!

**Comment by ebalazs-sv** [comment]
Verified as fixed on Nightly migration builds 5 with Motorola Moto G6 (Android 8) - ARM, Xiaomi Mi Pad 2 (Android 5.1) - x86 architecture.

**Comment by ekager** [comment]
Closing because verified as fixed

**Comment by LaurentiuApahideanSV** [comment]
Verified as fixed on Migration Build #7 on Samsung Galaxy Tab A SM-T515 (Android 9) and Sony Xperia Z5 (Android 7)
