### ISSUE TITLE
Set up Fennec-typed Fenix builds including proper keys

### ISSUE THREAD

**Issue by colintheshots** [mozilla-mobile/fenix#790]
Currently, Adjust is set up only for Greenfield-flavored Fenix builds and Fenix Nightly is running from the Greenfield flavor. We may provide versions of Fenix for Fennec users with our existing Google Play Store entries for Fennec. If so, we will need the TaskCluster scripts defined to build these flavors, including pulling the Adjust keys into the build.

**Comment by vesta0** [comment]
Will re-open if Fennec transition strategy changes.
