### ISSUE TITLE
Investigate if nav_graph performance can be improved

### ISSUE THREAD

**Issue by emalysz** [mozilla-mobile/fenix#7900]
### Why/User Benefit/User Problem
When creating the homeActivity, the setContentView uses R.layout.activity_home. This eventually calls into the nav_graph. Investigate if we should consider using more than one nav graphs and nesting them. 

There is a chance that this does not have significant performance improvements and should just be left as a single navigation graph. 

### Acceptance Criteria
HomeActivity.onCreate() performance will improve.
________________________

**Comment by NotWoods** [comment]
For what its worth, I have a PR for subgraphs up: https://github.com/mozilla-mobile/fenix/pull/7023

**Comment by mcomella** [comment]
Closing: we're addressing startup holistically.
