### ISSUE TITLE
[Bug] Login prompts are closed on page load

### ISSUE THREAD

**Issue by Baron-Severin** [mozilla-mobile/fenix#7902]
## Steps to reproduce
- Enable saving logins
- Login to website

### Expected behavior
- Login prompt is shown and is usable

### Actual behavior
- Login prompt is shown before being immediately closed

### Device information

* Android device: ?
* Fenix version: ?

**Comment by liuche** [comment]
Can you link to the AC PR in this bug?

**Comment by Baron-Severin** [comment]
> Can you link to the AC PR in this bug?

https://github.com/mozilla-mobile/android-components/pull/5704

**Comment by Baron-Severin** [comment]
QA note: this just landed in AC and won't show up until we get the next snapshot.

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest `Nightly Build #20310607 `**`AC 30.0.0, f7d2a4648`** `from 1/31`using the following devices:
• Google Pixel 3a (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

On the following websites:
• goo.gl/vi7z6
• twitter.com
• facebook.com
• google.com/gmail
• mail.yahoo.com

✔️ The login prompt **is now dismissed only after the users interaction.**

► Video
![20200131_123208](https://user-images.githubusercontent.com/51314259/73534570-192e4780-442a-11ea-9f3f-0102a21e0585.gif)
