### ISSUE TITLE
Long pause until page finishes loading when clicking a Google search result (GeckoLoginDelegateWrapper.onLoginFetch?)

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#7903]
STR from Vesta (I have no seen this locally):
- Open Firefox
- Click the url bar
- Type in a query, hit enter
- Google search doesn’t take that long
- Tap on a result
- The page takes 50-60 seconds to load. For the first 10 seconds you still see the search results screen, and for the next 40-50 seconds you see a blank page, and the destination page appears all at once (if the user hasn’t given up at this point aready). See screenshot below for page user is stuck on:

![Screenshot_20200121-031505](https://user-images.githubusercontent.com/759372/73028192-e660cf80-3de9-11ea-8a37-0f307718aef0.png)

Device: Pixel 3
Release channel: Nightly, updated every night
Usually on wifi

**Comment by mcomella** [comment]
This may be investigated in https://bugzilla.mozilla.org/show_bug.cgi?id=1613473

**Comment by mcomella** [comment]
> This may be investigated in https://bugzilla.mozilla.org/show_bug.cgi?id=1613473

This issue was closed.

@vesta0 Are you still able to reproduce this issue on the latest Nightlies?

**Comment by mcomella** [comment]
> > This may be investigated in https://bugzilla.mozilla.org/show_bug.cgi?id=1613473
> 
> This issue was closed.

Though it was closed due to an issue that seems unrelated to this STR: https://bugzilla.mozilla.org/show_bug.cgi?id=1613473#c11

@ecsmyth Do we have telemetry on page load duration? I wonder if we could see this happening in the wild.

**Comment by mcomella** [comment]
Agi is also able to reproduce this and pulled a profile: https://perfht.ml/32odSK9 Collectively, they've reproduced on P2, P3, S10e, S9. From the profile, we've found:
* `GeckoLoginDelegateWrapper.onLoginFetch` blocks the main thread for 7-8s. mattwoodrow guesses there's sampling error (because there are no main thread samples) and the delegate is taking even longer than that
* 2s waiting for the socket thread, which is related to uBlock origin. "For the uBlock bits, it's hard to be entirely sure, but it looks like the load request gets to the parent, and we hold it while we let extensions inspect/modify it, and that initializes uBlocks, which takes 2 seconds
Not obvious that we can do much about that", "Seems like that would impact fennec as well.", "I would assume so! Doesn't look like it would be affected by e10s at all"

The reason I've been unable to reproduce is probably because I don't have sync enabled and don't store any logins.

@ecsmyth Any thoughts on priority given this may only affect users with logins? Seems extremely high impact for an unknown (to me) portion of the userbase so I'd lean P1 responsiveness issue.

**Comment by mcomella** [comment]
> GeckoLoginDelegateWrapper.onLoginFetch blocks the main thread for 7-8s.

@ekager Any thoughts on a solution to this? Is it possible to make `onLoginFetch` occur asynchronously?

**Comment by ekager** [comment]
@mcomella just worked with @Baron-Severin to make this PR in AC and hopefully this should improve the performance here 
https://github.com/mozilla-mobile/android-components/pull/6059

**Comment by ecsmyth** [comment]
I split out an [issue](https://github.com/mozilla-mobile/perf-frontend-issues/issues/73) for creating a dashboard to visualize page load telemetry.

Given @ekager's fix, I'm going to keep this assigned to me and review once the fix hits Nightly.

**Comment by mcomella** [comment]
Agi can no longer reproduce but will update us if that changes.

**Comment by ekager** [comment]
mozilla-mobile/android-components#6059 has landed and is in Nightly @ecsmyth

**Comment by ekager** [comment]
This is ready to retest @ecsmyth !

**Comment by ecsmyth** [comment]
Confirmed that I can no longer reproduce on general search results or search results leading to login pages.
