### ISSUE TITLE
As a User I want to have access to search shortcuts when I type in the search bar

### ISSUE THREAD

**Issue by st3fan** [mozilla-mobile/fenix#791]
### Why/User Benefit/User Problem

Using a search shortcut is a three step process:

1. Press the `@Shortcuts` button above the keyboard
1. Select the search provider that you want to use
1. The search field now contains for example `@google |` and you can use the keyboard to type a search query after that

### Acceptance Criteria (how do I know when I’m done?)

- A `@Shortcuts` button is shown above the keyboard when the search bar has focus
- When you press the `@Shortcuts` button, the awesomebar will show a selection of search engines
- If you already had typed a query in the search bar, the existing awesomebar results are replaced with the search suggestions
- If you had already typed a query in the search bar, the query is prepended with the `@engine` shortcut and the cursor is positioned at the end of the query
- Only those search shortcuts that are relevant for your locale are shown
- The `@Shortcuts` button is not shown when the keyboard is active for any other textfield than the search bar

**Comment by sblatz** [comment]
Seems like this will be blocked on [adding search engine switching](https://github.com/mozilla-mobile/fenix/issues/528)

**Comment by sblatz** [comment]
Questions for UX:
- Should the prepended text of `@google |` be editable? That is, if I backspace a bunch can I remove it (like on desktop)?
- When I'm doing a shortcut search should we disable suggestions from history, clipboard, etc. and _only_ show from the engine requested?

@shorlander, @topotropic

**Comment by bsurd** [comment]
All acceptance criteria for this have been verified and working as intended.
