### ISSUE TITLE
[Bug] Italicized link in Mozilla blog post is showing as white in reader mode

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/fenix#7910]
## Steps to reproduce

1. Visit https://blog.mozilla.org/futurereleases/2020/01/17/a-brand-new-browsing-experience-arrives-in-firefox-for-android-nightly/
2. Enter reader mode

### Expected behavior

Italicized links should have blue link text like the surrounding text. 

### Actual behavior

Text in italics, eg:

made _Strict Mode_ the default in Firefox Preview Beta, while Firefox for Desktop comes with _Standard Mode_.

is shown in white text.

![signal-attachment-2020-01-24-001514](https://user-images.githubusercontent.com/152493/73046186-18505100-3e3f-11ea-9b96-42fa908944a3.png)

I cannot reproduce this issue in Fennec. 

### Device information

* Android device: Pixel 2
* Fenix version: latest nightly

**Comment by sflorean** [comment]
I am able to reproduce this on Nightly 20/10 with Samsung Galaxy Note10(Android 10).
