### ISSUE TITLE
Reader mode appearance options should appear as an overlay, like Focus trash and Fennec "Aa"

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/fenix#7912]
### Why/User Benefit/User Problem

As a user, I would like easy access to appearance options in reader mode without having to open a menu (where I might not even realize the option exists).

### What/Requirements

The appearance options should appear as a circle overlay button upon scroll. See Fennec for prior art.

### Acceptance Criteria (how do I know when I’m done?)

It looks and works like it does in Fennec. 

![signal-attachment-2020-01-24-003641](https://user-images.githubusercontent.com/152493/73046934-e1c80580-3e41-11ea-9747-a4bf0590cca0.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-15358)

**Comment by yoasif** [comment]
This also exists in reference browser and used to be in QAB. 

There is currently no way to customize reader view that I can find.

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813923

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
