### ISSUE TITLE
Tabbed tab switcher

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/fenix#7913]
### Why/User Benefit/User Problem

As a user, I would like to be able to quickly switch between normal, and private tabs, and also to easily access synced and recently closed tabs directly from the same UI that I use to manage tabs generally. 

### What/Requirements

A tabbed tab switcher with tabs for normal, private, synced, closed tabs.
Some of this exists in bits and pieces inside of Fennec -- the normal and private tab switcher is tabbed. Recently closed and synced tabs existed inside of a tab inside of "history" on the Fenix home page. 

### Acceptance Criteria (how do I know when I’m done?)

The tab switcher is tabbed and looks something like:

![image](https://user-images.githubusercontent.com/152493/73054409-560da380-3e58-11ea-94cb-945900352915.png)

This has previously been mentioned https://github.com/mozilla-mobile/fenix/issues/3758#issuecomment-508610437 and I made a couple of comments around support for this for recently closed tabs: https://github.com/mozilla-mobile/fenix/issues/2486#issuecomment-578003913 and synced tabs: https://github.com/mozilla-mobile/fenix/issues/5762#issuecomment-578029453

**Comment by kbrosnan** [comment]
Dupe #1063

**Comment by yoasif** [comment]
@kbrosnan can we reopen this? Tab switcher doesn't do this, unfortunately.

**Comment by cadeyrn** [comment]
The tabs tray is not yet finished yet. Quickly switching between regular and private tabs is already implemented, closed tabs is #2486, synced tabs is covered by #5762.
