### ISSUE TITLE
[Bug] 'Tab closed Undo' toast menu does not disappear after a few seconds

### ISSUE THREAD

**Issue by isabelrios** [mozilla-mobile/fenix#7915]
## Steps to reproduce
Open several sites 
On Homescreen tap on 'x' to close one of the open Tabs
### Expected behavior
After a few seconds the menu is automatically discarded
### Actual behavior
The toast menu stays and can be seen after going to different screens. See screenshot attached. 
![Screenshot_20200124-141002](https://user-images.githubusercontent.com/1897507/73071776-f6dd7c80-3eb3-11ea-8932-836efd028ede.png)

### Device information

* Android device: Pixel 3 Android 10
* Fenix version: master 2e6ffec

**Comment by cadeyrn** [comment]
Duplicate of #7799.

**Comment by isabelrios** [comment]
Sorry about that, closing as dup
