### ISSUE TITLE
As a user I want to start a search by tapping a search shortcut

### ISSUE THREAD

**Issue by st3fan** [mozilla-mobile/fenix#792]
### Acceptance Criteria (how do I know when I’m done?)

- you can start a search with one of the available search providers by tapping the provider's name in the list

Needs UX feedback:

- if you have already typed some text, like `windmills` and you then select the Wikipedia search shortcut, the query should turn into `@wikipedia windmills` with the cursor positioned at the end. So you can just hit Go and start your search.

(I made up the last requirement but I think that will be a really nice shortcut shortcut)

**Comment by sv-ohorvath** [comment]
Verified the acceptance criteria has been met. 
Devices: Pixel (Android 9), Nexus 9 (Android 6.0.1)
