### ISSUE TITLE
Show an undo snackbar when a pinned site is removed

### ISSUE THREAD

**Issue by gabrielluong** [mozilla-mobile/fenix#7924]
## Acceptance criteria
1. Have pinned site(s)
2. Be on home screen
3. Remove pinned site

**Expected**
See an undo snackbar with "Site removed" as the text and the pinned site is removed, with the ability to add it back when "undo" is pressed.

**Actual**
Pinned site is removed and no snackbar is shown.

Context:
> @gabrielluong can we show an undo snackbar when someone removes a pinned site? Thanks!
https://github.com/mozilla-mobile/fenix/issues/6759#issuecomment-576425110

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-15366)

**Comment by mheubusch** [comment]
Strings:
Site removed
UNDO

**Comment by gabrielluong** [comment]
@topotropic I assume we still want to implement this?

**Comment by topotropic** [comment]
> @topotropic I assume we still want to implement this?

Yes, thanks!

**Comment by eliserichards** [comment]
Tagging this with `Outreachy`, but note that it is more complicated than other features.

**Comment by priyanka0906** [comment]
> Tagging this with `Outreachy`, but note that it is more complicated than other features.

@eliserichards can  I work on this

**Comment by priyanka0906** [comment]
![Screenshot (54)](https://user-images.githubusercontent.com/56197993/113863667-904a3300-97c7-11eb-829d-cfd7b2f220ed.png)
@gabrielluong @eliserichards  please confirm line no. 107 is correctly written or not .I guess it should be onRemoveTopSiteClicked. correct me if I am missing something
In all functions order  of functions in the comment is somewhat confusing.

**Comment by gabrielluong** [comment]
Yes, you're looking for onRemoveTopSiteClicked

**Comment by priyanka0906** [comment]
> Yes, you're looking for onRemoveTopSiteClicked

@gabrielluong in the function it is written  onRemovedCollectionTapped

**Comment by gabrielluong** [comment]
I don't know if I follow, I didn't see a onRemovedCollectionTapped

**Comment by priyanka0906** [comment]
> I don't know if I follow, I didn't see a onRemovedCollectionTapped

In the comment of function  fun handleRemoveTopSiteClicked(topSite: TopSite)

    /**
     * @see [CollectionInteractor.onRenameCollectionTapped]
     */

**Comment by SoftVision-LorandJanos** [comment]
Verified as implemented on the latest Nightly 109.0a1 (2022-12-07) build.
Device used: Google Pixel 4 (Android 13).
Closing the ticket as verified.

**Comment by AdinaPetridean** [comment]
Also verified implemented on Beta 109.0b1 with Poco M4 Pro (Android 12).
