### ISSUE TITLE
Improve IntentReceiverActivity (perceived?) performance by no yield UI thread, activity background (cold app link?)

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#7926]
We noticed some performance, and perceived performance, issues from Sebastian's work in https://github.com/mozilla-mobile/fenix/issues/7818#issuecomment-578140495 (details in https://github.com/mozilla-mobile/fenix/pull/7917#pullrequestreview-348304730). We noticed:
* If an Activity calls `finish()` in `onCreate()` without yielding the UI thread (i.e. never returns from `onCreate`), we may avoid an unecessary layout & draw call, improving startup time (e.g. we should ensure any suspend functions are run in a blocking fashion)
* If an Activity has a window background, perceived performance improves because apps respond immediately when touching the app icon. We should probably add a window background. We should ensure this window background works like HomeActivity for dark mode users

These issues particularly impacted cold startup from the homescreen: we should evaluate if these issues impact cold startup from app link and other cases where `IntentReceiverActivity` is used (it's no longer used in the homescreen case).

These items may be parallelizable for devs to implement but I wasn't sure if they needed to be implemented together to make an impact so I filed them together.

**Comment by mcomella** [comment]
I did a quick PR, surrounding `IntentReceiverActivity` with `runBlocking`, to see what impact it made and it actually appeared to make startup worse on my P2. However, I didn't spend long enough on it to find out why. My guess is that `runBlocking` may prevent some concurrency so, even though we may avoid a drawn frame, it may take longer.

We should be careful as we investigate this to find out why this is slow – maybe it's not drawing the frame but the code that's actually running – and address it.

**Comment by jonalmeida** [comment]
We can re-test this once https://github.com/mozilla-mobile/android-components/issues/7217 us fixed - it removes the concurrency requirements of the `IntentReceiverActivity`.

**Comment by mcomella** [comment]
Dupe: we're trying to remove IntentReceiverActivity instead https://github.com/mozilla-mobile/fenix/issues/11608
