### ISSUE TITLE
[Bug] Clearing an exception for enhanced protection does not reload that page

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#7929]
## Steps to reproduce
Add an exception for enhanced protection by disabing the sheild toggle
go to protection setting-> exceptions 
clear that exception
### Expected behavior
page is reloaded,
both the icon and the protection overlay say that protections are on for the site
### Actual behavior
There is no reload but the overlay says that the protections are on
![Screenshot_20200125-140336](https://user-images.githubusercontent.com/33252312/73118539-79fee100-3f4d-11ea-84f8-49074ced2336.png)
At the same time, the sheild icon is broken
![Screenshot_20200125-140340](https://user-images.githubusercontent.com/33252312/73118544-8daa4780-3f4d-11ea-96d5-07c559bf7ce4.png)

### Device information

* Android device: Asus Zenfone m1
* Fenix version: 
Nightly 200124 06:01 (Build #20240607)
29.0.0, ae1ba0f02
GV: 74.0a1-20200122094859

**Comment by softvision-miralobontiu** [comment]
Hi @s-ankur 
I was not able to reproduce this issue on the latest Nightly build from 11/2 with Samsung Galaxy Tab S6 (Android 10).
Could you, please, retest on your device?
Thank you!

**Comment by s-ankur** [comment]
@softvision-miralobontiu can you try it on this page https://senglehardt.com/test/trackingprotection/test_pages/fingerprinting.html

**Comment by softvision-miralobontiu** [comment]
Yes, after deleting the page from exceptions, going back to the tab doesn't reload the page.

**Comment by s-ankur** [comment]
Closing as duplicate of  #6824
