### ISSUE TITLE
[Bug] Top Sites: can't have two instances of same favicon

### ISSUE THREAD

**Issue by Cheap-Skate** [mozilla-mobile/fenix#7932]
## Steps to reproduce
navigate to arstechnica.com
Hit "add to Firefox home" to create a Top Site of arstechnica.com home page
A top site is created with the correct favicon
tap a story on Ars Technica to move to a different page on the same site
Hit "add to Firefox home" to create a Top Site of the story
A Top Site is created with a dummy favicon

### Expected behavior
Should be able to have multiple Top Sites with the same correct favicon

### Actual behavior
Can't, second Top Sites instance gets a dummy favicon

### Device information

* Android device: Galaxy A40, Android 9
* Fenix version: Today's (20250609)

**Comment by bubi-luka** [comment]
I get the same bug on Phoronix web site. I added two sites as Top Sites in Firefox Preview Nightly:
- https://www.phoronix.com/scan.php?page=search&q=fedora
- https://www.phoronix.com/scan.php?page=search&q=gnome

When I start Firefox Preview Nightly I get two generic icons (letter P on blue background). When I open one link and return to Tabs/Home screen that link gets proper icon. When I click the other link and return to Tabs/Home screen the firstly opened link still has the correct favicon, the second still has generic one.

After closing the browser, clearing the phones cache and reopening the browser both links has the generic favicon again. On desktop Firefox all pages have the correct icon.

### Device information

Android device: Huawei P20 Lite, Android 9
Firefox Preview Nightly (200304 06:01, build #20640607)

**Comment by softvision-miralobontiu** [comment]
Hi all!
I wasn't able to reproduce this issue on the 11/2 Nightly build with Samsung Galaxy Tab S6 (Android 10):

![Untitled](https://user-images.githubusercontent.com/40694158/97854881-b5131980-1d02-11eb-9e58-a0dbe3d860de.png)

@Cheap-Skate could you retest this on your device on the latest Nightly?
Thank you!

**Comment by Cheap-Skate** [comment]
I think you are right. Closing.
