### ISSUE TITLE
[Bug] Tapping on https://www.bbc.co.uk URL to enter a new URL results in incorrect behavior

### ISSUE THREAD

**Issue by Cheap-Skate** [mozilla-mobile/fenix#7934]
## Steps to reproduce
delete History & close all tabs
open a single tab
type "bbc.co.uk" in URL bar and Enter
type "bbc.co.uk/news" in URL bar and Enter
type "bbc.co.uk" in URL bar and Enter

Tap URL bar as though to enter another URL
https://www.bbc.co.uk/ is highlighted but news is appended
-> incorrect behavior, news is not part of the current URL
Start typing, the https://www.bbc.co.uk part remains and the typing is appended
-> incorrect behavior - the highlighted text should be erased

(Something to do with search suggestions???)

### Expected behavior
The existing URL should be completely highlighted and completely erased when typing begins

### Actual behavior
the https://www.bbc.co.uk part of the URL is highlighted, but remains  when typing starts and text gets appended to it.

### Device information
* Android device:  Galaxy A40, Android 9
* Fenix version: Today's

**Comment by Cheap-Skate** [comment]
The same happens with thetimes.co.uk and telegraph.co.uk and argos.co.uk

Maybe it's a problem with all .co.uk sites.

**Comment by sflorean** [comment]
Couldn't reproduce the issue on the latest Nightly 6/12 with Samsung Galaxy Note10 (Android 10), following the steps provided. 
@Cheap-Skate this is still reproducible for you (given the fact that 6290 is verified)?

**Comment by Cheap-Skate** [comment]
I think this is the same as the other bug about autocomplete when using Swiftkey (I can't remember the issue number). 

So I'll close it.
