### ISSUE TITLE
[Bug] Fenix does not show BBC homepage favicon

### ISSUE THREAD

**Issue by Cheap-Skate** [mozilla-mobile/fenix#7935]
## Steps to reproduce
navigate to www.bbc.co.uk
move to the tab/home tray and look at the tab

### Expected behavior
BBC favicon should be in the tab (transparent background, 3 BBC letters white text on black)

### Actual behavior
dummy favicon is present

(Fennec does show the correct favicon in the tabs tray)

### Device information

* Android device:  Galaxy A40, Android 9
* Fenix version:  Today's

**Comment by kbrosnan** [comment]
I'm in the US so bbc.co.uk redirects to bbc.com. With that caveat this works for me using bbc.com and a current Firefox Preview Nightly

**Comment by Cheap-Skate** [comment]
Works for me now too. Must have been a site glitch.
