### ISSUE TITLE
Sync Top Sites

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/fenix#7936]
### User Story

As a user, I want to be able to see my top sites across my Firefox connected devices, making it convenient to use the browser on any device. 

### Acceptance Criteria (how do I know when I’m done?)

- [ ] My top sites are the same across all devices.
- [ ] When I add or delete a top site on one device, it is also added or deleted on other devices
- [ ] I see a sync option for top sites
- [ ] The top sites stay in sync only if the sync option is checked

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-15379)

**Comment by gaul** [comment]
It would be nice if the top sites were actually a bookmark folder.

**Comment by madb1lly** [comment]
Hi @gaul that's a good solution 🙂

**Comment by anotherus3r** [comment]
Would this also include syncing with desktop versions of Firefox or just on mobile devices? Personally, I have different top sites on desktop than on mobile and don't think they should necessarily be synced.

Example:
On desktop, I want Whatsapp Web and Spotify to be a top site. On the other hand, I don't need them to be top sites on mobile devices because I use native apps for these services there.

**Comment by cadeyrn** [comment]
This is still a valid feature request (comment for bot).

**Comment by soredake** [comment]
Not stale.

**Comment by smammy** [comment]
The issue with syncing top sites is that some users want their top sites identical on every device while others use different devices for different things and want different items in their top sites list. So then you have to come up with a GUI to control whether top sites or synced, or whether to accept the synced sites from the server, or some way to super-double-pin a top site locally so it won't get overwritten, or whatever. So it's not really as simple as adding a few config keys to the sync list.

**Comment by madb1lly** [comment]
Both Fenix and desktop have options on what to sync so it can't be that difficult to add one more.

**Comment by jonalmeida** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1810650

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
