### ISSUE TITLE
Add / plus button to Top Sites to add new top site

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/fenix#7937]
### Why/User Benefit/User Problem

As a user, I would like an easy way to add a site to my home screen that increases my discovery and usage of the feature (menus aren't obvious).

### What/Requirements

- [ ] Plus symbol somewhere near where the top sites appear
- [ ] symbol opens a modal that allows me to add a site name and address

### Acceptance Criteria (how do I know when I’m done?)

I can tap a button near the home screen to add a new home screen tile. 

This is how Opera and Kiwi do it:

![signal-attachment-2020-01-25-143439](https://user-images.githubusercontent.com/152493/73126377-e0045c00-3f7f-11ea-9571-bc7a7141a393.png)
![signal-attachment-2020-01-25-143442](https://user-images.githubusercontent.com/152493/73126378-e0045c00-3f7f-11ea-811f-2c2e6a820e54.png)

**Comment by gabrielluong** [comment]
Thanks for the feature request! This is actually already tracked in #7543. Gonna close this to avoid duplicates.
