### ISSUE TITLE
Allow the user to enable fingerprinting mitigations (eg. privacy.resistFingerprinting)

### ISSUE THREAD

**Issue by thecodingdude** [mozilla-mobile/fenix#7944]
### Why/User Benefit/User Problem

Visit 
https://amiunique.org/fp 
or
https://fingerprintjs.com/demo

 to see a fingerprint of your browser

### What/Requirements

Ideally, in Mozilla's quest to enhance privacy it would be nice to think about what can be done to make browsers more generic. Integration with an API that reveals just how unique your browser is would be a good start, as well as making changes to make browsers/users less identifiable. 

Valve has a repo called [Fingerprint2](https://github.com/Valve/fingerprintjs2) and you can see a demo [here](https://fingerprintjs.com/demo).

I feel calling it "Enhanced Tracking Protection" is a bit misleading if you can still be identified using a simple JS script.

### Acceptance Criteria (how do I know when I’m done?)

Educating users on how their browser makes them "unique"

Afford users a way of making their browser more 'generic' to blend in with the 'crowd' so to speak.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-15387)

**Comment by kbrosnan** [comment]
Tracking protection is about blocking scripts and resources from known trackers such as doubleclick, not about making the browser uniform. 

You are describing fingerprinting, on desktop this is controlled by the `about:config` pref `privacy.resistFingerprinting`

**Comment by crisalis2** [comment]
Setting privacy.resistFingerprinting in about:config on Fenix Beta does work, judging by the results in https://panopticlick.eff.org/ , except for the language parts. The related privacy.spoof_english about:config entry is what doesn't work.

About privacy.spoof_english :
>Whether to spoof user locale to English (used as part of Resist Fingerprinting). 
0 - will prompt 
1 - don't spoof 
2 - spoof

Even if you set it to 2, it doesn't change HTTP accept headers. I think this should be fixed.

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807457

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
