### ISSUE TITLE
[Bug] Back button broken on Twitter

### ISSUE THREAD

**Issue by djc** [mozilla-mobile/fenix#7947]
## Steps to reproduce

1. Tap the back button to go back from a Twitter thread to my Twitter feed

### Expected behavior

1. Go back (I think this worked yesterday)

### Actual behavior

1. Does nothing apparently

### Device information

* Android device: Pixel 2
* Fenix version: latest Nightly

**Comment by softvision-miralobontiu** [comment]
Hi @djc 
I was not able to reproduce this issue on the 11/2 Nightly build with Google Pixel (Android 10).
Could you please retest?
Thank you!

**Comment by djc** [comment]
Seems to be working now, I'll just close it.
