### ISSUE TITLE
[Bug] Share button is inactive in Custom Page

### ISSUE THREAD

**Issue by klint** [mozilla-mobile/fenix#7948]
## Steps to reproduce
Open any Custom Page (I did it via the Feedly app, and "Visit website" button

### Expected behavior
In the Custom Page that is opened, the share button should be active and allow to share the page

### Actual behavior
The Share button is displayed, but inactive as nothing happens when pressing on it

### Device information
Redmi Note 7

* Android device: 9
* Fenix version: #20270607

**Comment by Monakiel** [comment]
Reproduced it : settings / preffered browser / built-in 

Here is the screenshot 
![Screenshot_2020-01-31-03-29-59-430_org mozilla fenix~2](https://user-images.githubusercontent.com/35536198/73508038-12c4af00-43db-11ea-8b7e-eadf3baa3c20.jpg)

The shared button is weird.

The one in the 3dots menu works well though.

**Comment by ekager** [comment]
Closing for #5330
Tracked in AC by https://github.com/mozilla-mobile/android-components/issues/4457
