### ISSUE TITLE
[Bug] Firefox Preview title and logo are overlapping the open tabs

### ISSUE THREAD

**Issue by ebalazs-sv** [mozilla-mobile/fenix#7949]
## Steps to reproduce
1. Clear data for Firefox Preview;
2. Send 3-4 tabs on Firefox Preview;
3. After the last tab was sent, press the back button;
4. Launch Firefox Preview;
5. Tap Start Browsing from the onboarding screen;
### Expected behavior
The open tabs that were received at step 2 are displayed in the Open tabs list;
### Actual behavior
The Firefox Preview title and logo are overlapping the Open tabs list.

### Notes
[Video](https://drive.google.com/file/d/1ToJhy4nlmToNfKmfelsE5nVNwWDxydBo/view)
### Device information

* Android device: Motorola Moto G6 (Android 8);
* Fenix version: Firefox Preview Nightly 200123.

**Comment by topotropic** [comment]
@ebalazs-sv is this still relevant? Thanks!

**Comment by ebalazs-sv** [comment]
I had tested this on Nightly 200708 GV 80 from 7/8 with Motorola Moto G6 (Android 8) and this is not relevant anymore, since the open tabs are now in the Tabs tray.
I will close this issue. Thanks!
