### ISSUE TITLE
As a User I want the search shortcut to use the search engine rules for my locale

### ISSUE THREAD

**Issue by st3fan** [mozilla-mobile/fenix#795]
### Why/User Benefit/User Problem

We have strict rules about to which specific URL a search is directed. For example there is no such thing as a "Google Search" - instead we have country and locale specific variants. If you are in Canada, your Google search will default to a google.ca URL and in Germany that request will go to google.de

Search shortcuts should follow this same logic by using the rules that were defined for regular searches. These are currently abstracted away in the Android Components search component so there is a chance that we need to add additional API there.

### Acceptance Criteria (how do I know when I’m done?)

- Search shortcuts should use the country or locale specific version of the specific search provider

**Comment by sv-ohorvath** [comment]
Google doesn't change its domain based on IP location or locale. But that's not the case in Chrome either.
Search engines list is updated based on locale. Some engines, like Amazon & wikipedia use the local domains. I think this can be considered as done.

devices verified on: Nexus 5 (Android 6.0.1), Pixel (Android 9)
