### ISSUE TITLE
[Bug] Top toolbar hidden if the app is minimized while in full-screen

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#7951]
## Steps to reproduce
1. Set toolbar to top.
2. Open a video and go to full-screen mode.
3. Tap the device home button.
4. Re-open Fenix from recent apps/home screen
5. Check the toolbar.
### Expected behavior
The toolbar is there, still displayed.
### Actual behavior
The toolbar is missing from the tab view and home screen.
### Device information

* Android device: Nexus 5 (Android 6.0.1), Samsung Galaxy Note 8 (A 9)
Doesn't reproduce on: Nokia 6 (android 7.1.1), Huawei P20 lite (Android 9)
* Fenix version: Nightly 1/27, Beta 3.2.0
![20200127_155446](https://user-images.githubusercontent.com/4037709/73181007-175d3f00-411f-11ea-88a4-3e8a2ddd5112.gif)

**Comment by ekager** [comment]
Should be fixed by same fix for #9703

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly Build #21130610 from 4/22`** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)

► Video
![20200422-114709](https://user-images.githubusercontent.com/51314259/79961679-ba5bf580-848f-11ea-8ef4-23b3e1f73e13.gif)
