### ISSUE TITLE
[Bug] Error 0/0 displayed when double tapping on Find in page toolbar

### ISSUE THREAD

**Issue by sflorean** [mozilla-mobile/fenix#7953]
## Steps to reproduce
1. Visit  Wikipedia, youtube.
2. Tap on 'Find in Page'.
3. Enter a word to search (that exists in more than one place).
4. Double-tap up and down.

### Expected behavior
The match order/number of matches is updated.

### Actual behavior
0/0 is displayed.

### Device information
* Android device: Samsung Galaxy Note8(Android 9), Xiaomi Mi Pad 2 (Android 5.1.1).
* Fenix version: Beta 3.2.0-beta3, Release 2.3.1, Nightly - 1/27.

![20200127_Trim](https://user-images.githubusercontent.com/58466444/73188218-306bed00-412b-11ea-8ce5-fbf028329c57.gif)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-15395)

**Comment by AaronMT** [comment]
Believe this is https://github.com/mozilla-mobile/android-components/issues/4704

**Comment by Diana-Rus** [comment]
Hi, I still reproduce the issue with Samsung Galaxy S8+ (Android 8) on Firefox Preview Beta 4.1.0-beta.1 (Build #20720029) GV: 75.0-20200309155231.

**Comment by Diana-Rus** [comment]
Hello, issue is still reproducible with Google Pixel 3 XL (Android 9) on Beta 5.0.0-beta.1 - 4/29.

**Comment by AaronMT** [comment]
Yeah this seems to happen commonly, even when re-enabling a Find in Page UI test that is currently disabled (off branch).

**Comment by csadilek** [comment]
This is https://bugzilla.mozilla.org/show_bug.cgi?id=1587856, also tacked in mozilla-mobile/android-components#4704.

**Comment by softvision-miralobontiu** [comment]
I was able to reproduce this on the latest RC build 84.1.0-rc.1 with Samsung Galaxy Tab S6 (Android 10).
Now, the "Find in page" toolbar displays also negative numbers:

<img src="https://user-images.githubusercontent.com/40694158/101609981-48312480-3a10-11eb-9d10-b9486cbf7459.png" width="300" height="550" />

**Comment by sflorean** [comment]
Reproducible on 85.1.3 RC with Pixel 3 (Android 11).

**Comment by sflorean** [comment]
This is still reproducible on Fenix builds.

**Comment by amocirean** [comment]
Reopened as the issue is still reproducible on Beta 109.0b1

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807147

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
