### ISSUE TITLE
Fennec migration: The migration screen text font is different than in the specifications

### ISSUE THREAD

**Issue by ebalazs-sv** [mozilla-mobile/fenix#7955]
## Preconditions:
Have Fennec installed.
## Steps to reproduce
1. Replace Fennec with Fenix using a build from [here](https://firefox-ci-tc.services.mozilla.com/tasks/index/project.mobile.fenix.v2.fennec-nightly.2020.01.16.revision/9c25d274d0d3c6549f607ce1298471ca6627a8d4).
2. Observe the migration screen text font;
### Expected behavior
The migration screen is displayed as in the [abstract](https://app.abstract.com/share/b1b9f719-fbb5-4c94-b45d-556232a3cd52?collectionLayerId=41a90258-2dbf-434a-9cb2-b6b28e7b5fbc&present=true&preview=false&sha=abfe4a5d2df1d032690e4b5e693a5213cb78f064).
### Actual behavior
The text font is different than in the specifications. Also the text is not justified.
### Notes:
[Screenshot](https://drive.google.com/file/d/1bJ7ZBaHDjC1nQkTG69-JUY5F33XUHIuK/view?usp=sharing)
### Device information

* Android device:  Samsung Galaxy S8 (Android 9) - ARM64; Motorola Moto G6 (Android 8) - ARM
* Fenix version: Nightly migration build 4, 01/22.

**Comment by codrut-topliceanu** [comment]
Started working on this issue.

**Comment by brampitoyo** [comment]
@ebalazs-sv When we fix #3687 and #8089 by using Metropolis and Inter on the app, it will also apply both fonts to the migration screen.

Note that the font used in migration should be the same as the font used on the rest of the app.

**Comment by pocmo** [comment]
Alright. In this case lets close this migration specific issue and leave it to the Fenix team to decide when to integrate the fonts.

**Comment by ebalazs-sv** [comment]
I will leave this in Ready for QA to be tested after the two related Fenix issues will be fixed. Thanks!

**Comment by ebalazs-sv** [comment]
This is still reproducible on Beta Migration build 4, 3/24, with Huawei P9 Lite (Android 7).

**Comment by codrut-topliceanu** [comment]
@ebalazs-sv Yep, just checked, my changes were overwritten.

**Comment by ebalazs-sv** [comment]
This is reproducible on Beta Migration 75.0.0-beta.3, 4/1 with Pixel 2 (Android 9).
One of the issues mentioned in https://github.com/mozilla-mobile/fenix/issues/7955#issuecomment-582188987 is fixed.

**Comment by ebalazs-sv** [comment]
This is reproducible on Beta Migration 75.0.0-beta.5, from 4/14, with Huawei P9 Lite (Android 7), Motorola Moto G6 (Android 8).
@brampitoyo Since the issue https://github.com/mozilla-mobile/fenix/issues/3687 is fixed, when will this also be applied on the Migration screen UI as well? Thanks!

**Comment by brampitoyo** [comment]
@ebalazs-sv Shouldn’t this be automatic? Any font we set as default for the app will “cascade downwards” and also be applied to the migration screen. I thought this won’t involve any more work.

If this process isn’t automatic, sorry for my misunderstanding!

**Comment by ebalazs-sv** [comment]
Verified as fixed on the latest Nightly Migration build 200427 (Build #2015736947) with Pixel 2 (Android 9), Nexus 5 (Android 6.0.1), Samsung Galaxy Tab S3 (Android 8). The text font from the Migration screen UI, is the same as the app's font.
