### ISSUE TITLE
Enable Login management preference

### ISSUE THREAD

**Issue by ValentinTimisica** [mozilla-mobile/fenix#7957]
Enable Login management preference (View Logins) by removing Nightly flag.

**Comment by cadeyrn** [comment]
Please not that the feature isn't working at all for users of devices from OnePlus: #7603. This should be solved before shipping in a stable release.

**Comment by ValentinTimisica** [comment]
@liuche is #7603 a problem (should it be fixed first?), or we can go on with this task?

**Comment by vesta0** [comment]
@ekager will add a check for impacted devices which will solve the underlying issue.

**Comment by cadeyrn** [comment]
Thanks for solving #7603. Should #7739 also be prioritised before the login management will be enabled in a stable release?

**Comment by liuche** [comment]
This should be ready to go - we are no longer waiting on #6704 based on some investigation @ekager and @grigoryk did into crashes.

**Comment by ekager** [comment]
@liuche @ValentinTimisica we are still waiting on #8324 's fixes to land first so we don't lose user data switching between secure/insecure storage

**Comment by sv-ohorvath** [comment]
Verified that saved logins management and autofill are enabled on Beta 4.0.
