### ISSUE TITLE
Fennec migration: The widget's icon is not updated

### ISSUE THREAD

**Issue by ebalazs-sv** [mozilla-mobile/fenix#7959]
## Preconditions:
Have widget added to Fennec Nightly.
## Steps to reproduce
1. Replace Fennec with Fenix using a build from [here](https://firefox-ci-tc.services.mozilla.com/tasks/index/project.mobile.fenix.v2.fennec-nightly.2020.01.16.revision/9c25d274d0d3c6549f607ce1298471ca6627a8d4).
2. Observe the widget's icon.
### Expected behavior
The widget's icon is changed to Firefox Nightly icon.
### Actual behavior
The widget's icon is Fenix RC icon.

### Device information

* Android device:  Samsung Galaxy S8 (Android 9) - ARM64;
* Fenix version: Nightly migration build 01/16.

**Comment by vmbaicu** [comment]
Seems like a minor change, but we are missing the nightly and beta icons for the widget. I've tried using the launcher icons but they do not respect the proportions of ic_logo_widget nor can I export them in order to modify them myself. 

Can somebody from UX help out with the needed assets?

**Comment by brampitoyo** [comment]
The expected behaviour is correct. When Fenix replaces Firefox Nightly, we don’t want the Firefox Preview icon. We want the Firefox Nightly icon to show up instead.

**Comment by ebalazs-sv** [comment]
@brampitoyo Thanks for your comment. Based on this I will change the expected result.

**Comment by pocmo** [comment]
This should be fixed for the Beta migration build. For production this will get fixed automatically once the new branding lands (#8278). We will not retroactively fix this for Nightly.

**Comment by ebalazs-sv** [comment]
I had tested this on Fennec Beta Migration 02/18 from https://github.com/mozilla-mobile/fenix/wiki/Fennec-Migration with Samsung Galaxy Note 8 (Android 9) and the widget's icon is updated.
I will leave this on Ready for QA until it will be verified on the official Beta Migration build.

**Comment by ebalazs-sv** [comment]
Verified as fixed on Fennec Beta Migration Build 1 with LG G7 fit (Android 8.1) and the widget's icon is updated after migration. 
I will move this to Done. Thanks!
