### ISSUE TITLE
As a User I only want to see search shortcuts that are relevant for my locale

### ISSUE THREAD

**Issue by st3fan** [mozilla-mobile/fenix#796]
### Why/User Benefit/User Problem

Not all search shortcuts are available in every country or locale. 

### Acceptance Criteria (how do I know when I’m done?)

- The shortcuts bar only shows shortcuts relevant for the user's country or locale.

**Comment by bsurd** [comment]
Verified in the latest Fenix, the available search engines update according to the set locale.
