### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by reyis4402** [mozilla-mobile/fenix#7962]
### Device information

When you open the answer given to comments while using Twitter, the page goes to the top

* Android device: ?

Lenovo K6 Note
* Fenix version: ?

**Comment by cadeyrn** [comment]
Could you please fill out the title field of the issue? Otherwise it's not possible to know what the issue with the title "[Bug]" is about in the list of issues. Thank you…

**Comment by NotWoods** [comment]
Duplicate of #7974. Please edit your existing issue in the future
