### ISSUE TITLE
[Bug] When closing tab (Pop-Up)

### ISSUE THREAD

**Issue by J41319** [mozilla-mobile/fenix#7963]
## Steps to reproduce

Just keep opening and closing tabs, so the bug may appear.

### Expected behavior

When closing the tab, the pop-up to undo the action have to disappear after a few seconds.

### Actual behavior

The pop-up sometimes doesn't disappear

### Device information

Xiaomi Mi A3

* Android device: 9.0
* Fenix version: 3.2.0

Video: https://imgur.com/a/NzcyyG8

**Comment by cadeyrn** [comment]
Duplicate of #7799.
