### ISSUE TITLE
[Bug] Accessibility updates for snackbar (increase time)

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#7970]
Currently our snackbars are hard for users with talkback enabled to use (they appear and disappear before they can even interact with them)

Let's increase the time to 15 seconds.

**Comment by sv-sdeiac** [comment]
Verified as fixed using Firefox Preview Nightly 2/6 #20370604.

Devices:
- Samsung Galaxy S8 (Android 9);
- Google Pixel 3 (Android Q).
