### ISSUE TITLE
[Bug] Error in Twitter Comments

### ISSUE THREAD

**Issue by reyis4402** [mozilla-mobile/fenix#7974]
When you open the answer given to comments while using Twitter, the page goes to the top.

* Android device: ?

Lenovo k6 Note
* Fenix version: ?
Firefox Preview & Nightly OLD versiyon.

**Comment by reyis4402** [comment]
> When you open the answer given to comments while using Twitter, the page goes to the top.
> 
>     * Android device: ?
> 
> 
> Lenovo k6 Note
> 
>     * Fenix version: ?
>       Firefox Preview & Nightly OLD versiyon.

**Comment by reyis4402** [comment]
Error video

https://mobile.twitter.com/acikveozgur/status/1221156809702039552

**Comment by reyis4402** [comment]
@NotWoods    Will there be a fix for the error?

**Comment by yoasif** [comment]
Dupe of #6176
