### ISSUE TITLE
Fennec migration: Loading circle not displayed on the "Updating Firefox ..." button

### ISSUE THREAD

**Issue by ebalazs-sv** [mozilla-mobile/fenix#7975]
## Preconditions:
Have Fennec installed and logged in. Have the app open.
## Steps to reproduce
1. Replace Fennec with Fenix using a build from [here](https://firefox-ci-tc.services.mozilla.com/tasks/index/project.mobile.fenix.v2.fennec-nightly.2020.01.16.revision/9c25d274d0d3c6549f607ce1298471ca6627a8d4).
2. Observe the migration screen A UI;
### Expected behavior
The inactive button is displayed as in the [abstract](https://app.abstract.com/share/b1b9f719-fbb5-4c94-b45d-556232a3cd52?collectionLayerId=41a90258-2dbf-434a-9cb2-b6b28e7b5fbc&present=true&preview=false&sha=abfe4a5d2df1d032690e4b5e693a5213cb78f064).
### Actual behavior
The loading circle is missing from the "Updating Firefox..." button. 
### Notes:
[Screenshot](https://drive.google.com/file/d/1lXzr26Q6XGq_ac5mamdERyBmxvOJZVJw/view)
### Device information

* Android device:  Samsung Galaxy S8 (Android 9) - ARM64;
* Fenix version: Nightly migration build 01/16.

**Comment by pocmo** [comment]
Landed and should be available in the next build.

**Comment by ebalazs-sv** [comment]
This is verified as fixed on Nightly Migration Build 9 with Samsung Galaxy S8 (Android 9). I will move this to Done. Thanks!
A follow-up issue was filed https://github.com/mozilla-mobile/android-components/issues/5906.
