### ISSUE TITLE
Fennec migration: The migration screen steps area has scrollable sides

### ISSUE THREAD

**Issue by ebalazs-sv** [mozilla-mobile/fenix#7978]
## Preconditions:
Have Fennec installed.
## Steps to reproduce
1. Replace Fennec with Fenix using a build from [here](https://firefox-ci-tc.services.mozilla.com/tasks/index/project.mobile.fenix.v2.fennec-nightly.2020.01.16.revision/9c25d274d0d3c6549f607ce1298471ca6627a8d4).
2. Scroll up and down the migration screen area;
### Expected behavior
The migration screen area is not scrollable.
### Actual behavior
The migration screen steps area has scrollable sides.
### Notes:
[Video](https://drive.google.com/file/d/14tgmtZNQCnDifERBOhwI-BEPu94kBuM4/view)
### Device information

* Android device: Motorola Moto G6 (Android 8) - ARM, Xiaomi Mi Pad 2 (Android 5.1) - x86 architecture;
* Fenix version: Nightly migration build 5, 01/26.

**Comment by pocmo** [comment]
Landed and should be available in the next build.

**Comment by ebalazs-sv** [comment]
This is still reproducible on Nightly Migration Build 9 with Samsung Galaxy S8 (Android 9).
[Video](https://drive.google.com/file/d/1Q1QiccodH2DGy2sI4bLbLrte1eXV3BaY/view)

**Comment by codrut-topliceanu** [comment]
@ebalazs-sv Apologies, I thought that the whole screen was scrollable to be the problem. In the commits for [this PR](https://github.com/mozilla-mobile/fenix/pull/7993) I removed the scrollview that was at the root of the layout and edited the constraints of the views in order to fit on any screen. To accommodate usage in landscape mode on small screened devices I made the steps list to be scrollable. 

As far as I can tell this activity needs something scrollable in order to fit on small screened devices in landscape mode.

I'm unsure how to proceed from here. Should I maybe try to remove the "scroll shadow" you see when dragging the steps list? Or just revert the changes and leave the whole view scrollable?

**Comment by ebalazs-sv** [comment]
@apbitner Hello! This issue is about the migration onboarding screen. The list of migration steps has "scroll shadow". Please see the [video](https://drive.google.com/file/d/1Q1QiccodH2DGy2sI4bLbLrte1eXV3BaY/view). Could you please point to the right direction to take on this issue?

- Remove the "scroll shadow" for portrait mode and keep them for landscape mode, because in order to see all the migration steps the list must be scrollable in landscape mode;
- Leave all the page scrollable in landscape mode and remove the "scroll shadow" from portrait and landscape mode;
- A different approach.

Note that https://github.com/mozilla-mobile/fenix/issues/8422 is in progress and it will change the list view.

Thank you!

**Comment by apbitner** [comment]
@ebalazs-sv Are you able to show me what it looks like in landscape?

**Comment by ebalazs-sv** [comment]
@apbitner Hi! Here is the recording in landscape mode on:
- Huawei P9 Lite (Android 7), resolution 1080 x 1920 pixels (~432 ppi pixel density) [Video](https://drive.google.com/file/d/1E4n44h9Zr_nXN7nSLIhxF-9NwAJwOtuk/view);
- Samsung Galaxy Note 8 (Android 9), resolution 1440 x 2960 pixels, (~521 ppi density) [Video](https://drive.google.com/open?id=1UTbebPhKrS20i2qpeu7nitACv2WcPRFI);

**Comment by apbitner** [comment]
@ebalazs-sv Thanks for sharing. Let's go with option 1: Remove the "scroll shadow" for portrait mode and keep them for landscape mode, because in order to see all the migration steps the list must be scrollable in landscape mode

**Comment by ebalazs-sv** [comment]
@apbitner Thank you!

**Comment by Dunexus** [comment]
@apbitner Don't forget that Fenix can be used in split screen mode so portrait can be half-height of the screen and may need scroll.

**Comment by ebalazs-sv** [comment]
@Dunexus Thanks! 
I tested this on split screen mode and this is the [result](https://drive.google.com/file/d/1qSfCEHMH6zyDhL0MmCQg_Ru-CSq78Pe4/view) with Huawei P9 Lite (Android 7), resolution 1080 x 1920 pixels (~432 ppi pixel density). 
I also noticed a new issue, that the migration steps are overlapping the text in landscape mode. I will file a new issue for that.

**Comment by ebalazs-sv** [comment]
@apbitner Having in mind the split view testing scenario, should we leave the "scroll shadow" in landscape and portrait mode as well? Thank you.

**Comment by apbitner** [comment]
@ebalazs-sv The "scroll shadow" seems to be making the layout of this screen more challenging with small screen sizes, such as split view portrait. Can we just keep the button fixed to the bottom of the screen and all of the text above it can scroll? Let me know if you need mockups to illustrate.

**Comment by ebalazs-sv** [comment]
@apbitner Yes, mockups to illustrate that would be really useful. Thank you.

**Comment by apbitner** [comment]
@ebalazs-sv Here are the various views of the migration screen. In Landscape and Split, the button should remain fixed at the bottom while the rest of the screen scrolls behind it.

https://share.goabstract.com/ba32614d-6407-4f37-94a6-0f25f7719fae?

**Comment by ebalazs-sv** [comment]
This is reproducible on Beta Migration Build 3, 3/4 with Huawei P9 Lite (Android 7).

**Comment by ebalazs-sv** [comment]
This is reproducible on Beta migration build 75.0.0-beta.2, from 3/26 with Huawei P9 Lite (Android 7).
I see that Codrut created a patch with the changes from the specs received in the comment https://github.com/mozilla-mobile/fenix/issues/7978#issuecomment-591512513. 
@pocmo Can you please point to the right person for reviewing this? Thanks!

**Comment by ebalazs-sv** [comment]
I tested this issue on Release migration build 4.0.0-beta.2 GV 76 4/8 with Motorola G6 (Android 8), Huawei P9 Lite (Android 7) and it is not reproducible.
I will verify it also on the next migration build. Thanks!

**Comment by ebalazs-sv** [comment]
Verified as fixed on the latest Nightly Migration build 200427 (Build #2015736947) with Pixel 2 (Android 9), Nexus 5 (Android 6.0.1), Samsung Galaxy Tab S3 (Android 8), Huawei P9 Lite (Android 7).
I will close this issue and move it to Done. Thanks!
