### ISSUE TITLE
As a User I want my default search provider to be based on my country or locale

### ISSUE THREAD

**Issue by st3fan** [mozilla-mobile/fenix#798]

**Comment by st3fan** [comment]
Asking @mconnormoz for feedback on specifics about the *country or locale* part here. We do _something_ in Android Components that I think we are happy with for Focus, but I'd like to confirm that.

**Comment by mconnormoz** [comment]
At a high level, we're looking to move to country > locale for a bunch of reasons.  But we can handle that on the AC side here: https://github.com/mozilla-mobile/android-components/issues/1720

**Comment by ekager** [comment]
As of now, we will get search engines using the locale from the system for free using the AC SearchEngineManager. If we want to discuss more accurate location, I think this should be on the AC side for the future.

**Comment by bbinto** [comment]
@mconnormoz - can you please let us know if that works for MVP (see Emily's last comment)?

**Comment by mconnormoz** [comment]
Yes, @st3fan added our regional testing requirements to the epic (#226 )

**Comment by sv-ohorvath** [comment]
I've verified the Russian, Turkish and Chinese locales. The default search engine is changed only on the TR locale, to Yandex. On the other locales, the search engines list is updated but the Google default is kept.
devices: Pixel (Android 8), Samsung S8 (Android 8), Nexus 5(Android 6)

**Comment by mconnormoz** [comment]
@sv-ohorvath If you're getting Google for Russia but Yandex for Turkish, something isn't quite right.

@pocmo how can a tester see what region is being detected by AC?  is that currently possible?

**Comment by ekager** [comment]
As discussed in Slack, we need to update the list.json and use the new searchDefault field for these all to be correct. This work will be completed in AC and will not require work on the Fenix side. 
https://github.com/mozilla-mobile/android-components/issues/2371

**Comment by sv-ohorvath** [comment]
Closing this issue if there is no more work to be done here. Thanks @ekager !
