### ISSUE TITLE
Fennec migration: Migration onboarding UI dismissed if you minimize the app

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#7980]
STR: 
1. Install the Fenix migration build over Fennec. Open the updating app.
2. Wait for the "migration complete" screen, with the Start browsing button.
3. Minimize the app by pressing the home button, don't close the app entirely.
4. Tap the home screen launcher to return to the app. Or, from recent apps, tap the second instance of the app, that doesn't show the migration onboarding screen.

Expected results:
The migration complete onboarding screen is still shown.

Actual results:
The migration onboarding is dismissed when you return to the app and the Fenix onboarding screen is displayed. (the home launcher is opening the second instance of the app, that didn't have the migration screen on it)

Note: if you select from the recent apps the instance that has a snapshot with the migration onboarding, it will show the migration onboarding screen.

Build: Nightly Migration build#2
Devices: HTC 10 (Android 8), Samsung S8 (Android 9)

**Comment by pocmo** [comment]
Landed and should be available in the next build.

**Comment by abodea** [comment]
Verified as fixed on **Migration Build #9 (Build #2015722947)** **2/14** using a Samsung Galaxy S8+(Android 8).
Note that the `Migration onboarding UI` was not dismissed after minimizing the app, I tried at least 10 times.
Based on my comment I will move this issue to the `Done` column.
