### ISSUE TITLE
建议地址栏上面的分割线取消掉 (Cancel the dividing line above the address bar)

### ISSUE THREAD

**Issue by 90du** [mozilla-mobile/fenix#7982]
建议地址栏上面的分割线取消掉，现在这样难看的要死，你们只兼顾地址栏在下面，没想过地址栏在上面的情况和下面的ui冲突吗

> It is recommended to cancel the dividing line above the address bar. It is so ugly to die now. You only care about the address bar below. Have you never thought that the address bar above and the ui below conflict?

**Comment by sblatz** [comment]
<img width="565" alt="image" src="https://user-images.githubusercontent.com/4400286/73442153-8f607a80-4354-11ea-83ba-83a12c177359.png">

I think this is in reference to the loading bar being on top of the top toolbar.

**Comment by 90du** [comment]
另外建议把设置移动到左边，做到左右对称

**Comment by Octoton** [comment]
Duplicate as #7456

**Comment by NotWoods** [comment]
Closing as duplicate. The 3-dot menu button will stay to be consistent with Android design guidelines, like other apps.
