### ISSUE TITLE
[Bug] Although I succesfully log into ff acount, ff preview won't connect to it.

### ISSUE THREAD

**Issue by cassepipe** [mozilla-mobile/fenix#7987]
By the time I write this message, I have made sure, I have latest Firefox Preview

## Steps to reproduce
Change you firefox account password.
Try to sync Firefox Preview from inside the app and enter your new password.

### Expected behavior
The app should start syncing once logged into firefox account.

### Actual behavior
Although you are successfully logged, the app won't take it into account. The yellow stripes indicating that you are not connected to ff account does not go away.

### Device information
* Android device: Samsung Galaxy S7
* Fenix version: Please tell me where I can find that information

**Comment by cassepipe** [comment]
It works in ff Preview Nightly with the QR code though.

**Comment by ekager** [comment]
You can find the version in Settings -> About. Are you still seeing this issue in your release build?

**Comment by cassepipe** [comment]
The problem has gone in newer versions. Thanks.
