### ISSUE TITLE
[Bug] Reader view switch does not appear for tabs loaded in background

### ISSUE THREAD

**Issue by einstein95** [mozilla-mobile/fenix#7989]
## Steps to reproduce
From https://m.fanfiction.net/anime/Naruto/ open a story in a new tab

### Expected behavior
Opening the 3dot menu shows Reader view toggle

### Actual behavior
Reader view toggle does not appear until tab is refreshed

### Device information

* Android device: Nokia 6.1; Android 9
* Fenix version: 3.0.2 (Build #20081833)

**Comment by ekager** [comment]
I'm not seeing this on master anymore. Let's test this.

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly Build #21130610 from 4/22`** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)

► Video
![20200422-095311](https://user-images.githubusercontent.com/51314259/79950478-cb046f80-847f-11ea-9909-74ae6d39dcfb.gif)
