### ISSUE TITLE
As a User I want to be able to change the default search provider

### ISSUE THREAD

**Issue by st3fan** [mozilla-mobile/fenix#799]
### Why/User Benefit/User Problem

As a User I want to be able to change the default search provider.

### What / Requirements

The UX designs for the Search Provider settings are part of https://github.com/mozilla-mobile/fenix/issues/291

TODO Is there a better links to the designs, I am unable to find the proper document.

A user should be able to change the default search provider in the 

Available search providers are based on the user's country or locale. What this means is that a user in Canada sees a different list of available search providers than a user in The Netherlands.

### Acceptance Criteria (how do I know when I’m done?)

-

**Comment by sv-ohorvath** [comment]
Verified as fixed on: Pixel (Android 9) & Nexus 5 (Android 6). build: master 3/13
