### ISSUE TITLE
Unify the design of all favicon icons in Fenix

### ISSUE THREAD

**Issue by sv-sdeiac** [mozilla-mobile/fenix#7992]
We want to update favicons of top sites, bookmarks, history and search to have a unified design. 
The favicon is 24x24dp centered in a 40x40dp box with 4dp corner radius.

Spec for top sites:
![fav-home](https://user-images.githubusercontent.com/353960/74059066-9e47cc80-49e7-11ea-8bb5-705feea25388.png)

Spec for all list items (bookmarks, history, search results):
![List element](https://user-images.githubusercontent.com/353960/75386235-9b067900-58e1-11ea-9696-5e2487217fef.png)

**Comment by gabrielluong** [comment]
I am gonna edit this issue description since we actually have updated mockups for the icons from what was originally linked.

**Comment by gabrielluong** [comment]
@topotropic I know we have discusses more specs regarding these icons. I was looking at them in our slack, and I also saw some were deleted. Can you post the latest specs for these icons? Thanks!

**Comment by topotropic** [comment]
@AmyYLee I just put this on the polish board – feel free to prioritize. Thanks!

**Comment by mcarare** [comment]
@topotropic Can we also get some color specs on this? I'm referring mainly to the card outline. TY!

**Comment by topotropic** [comment]
Please use   <color name="inset_light_theme">#E0E0E6</color>

**Comment by NotWoods** [comment]
What colors should be used for the icon background in private mode? For example, when showing a list of tracking protection exceptions in Settings when private mode is flipped on.

**Comment by AmyYLee** [comment]
> @AmyYLee What colors should be used for the icon background in private mode? For example, when showing a list of tracking protection exceptions in Settings when private mode is flipped on.

@NotWoods 

Please use:
Ink 50 (#291D4F) for private theme (border/fill)
Dark Grey 50 (#32313C) for dark theme (border/fill)

**Comment by NotWoods** [comment]
QA please confirm there are no regressions with the favicon visual for logins list and top sites in light, dark, and private themes.

**Comment by sflorean** [comment]
> QA please confirm there are no regressions with the favicon visual for logins list and top sites in light, dark, and private themes.

Verified as fixed on Nightly 8/4 with Samsung Galaxy Note 10 (Android 10), Huawei MediaPad M2 (Android 5.1.1); scenarios covered: logins & top sites in light, dark, private themes.

@NotWoods the favicons for bookmarks and history, aren't the same as the ones mentioned above, but the mocks are available in the description of this issue: this is expected and will be covered in another issue?

**Comment by NotWoods** [comment]
Yes, that work will be covered later.
