### ISSUE TITLE
[Bug] Fenix Nightly crashes after clearing Cookies and reloading the page 

### ISSUE THREAD

**Issue by ebalazs-sv** [mozilla-mobile/fenix#7997]
## Steps to reproduce
1. Go to sportsdirect.com and add a product to the cart;
2. Go to Settings -> Delete browsing data and delete Cookies;
3. Go to sportsdirect.com and reload the page;
### Expected behavior
The page is displayed.
### Actual behavior
Fenix Nightly crashes.

### Notes
[Logcat](https://drive.google.com/file/d/1CJSxVajWHEdsZtKwLfu2LT3EQBaMLWzD/view?usp=sharing)
All the other tabs are reloaded as blank after the crash.
### Device information

* Android device: Motorola Moto G6 (Android 8)
* Fenix version: Nightly 200130

**Comment by ValentinTimisica** [comment]
Cannot reproduce this. After I clear the cookies the page reloads successfully. Can someone else try?
### Device information
- Oneplus 7T Pro (Android 10)
- Samsung Galaxy J7 Prime (Android 7)
- Samsung Galaxy Note 10 (Android 10)

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly Build #20570604 from 02/26`** using the following devices:
• Google Pixel 3a (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

► Video
![20200226-121741](https://user-images.githubusercontent.com/51314259/75335782-b9915380-5892-11ea-84cb-8618879f8eec.gif)
