### ISSUE TITLE
[Bug] Sending true default for fxaSignedIn and fxaHasSyncedItems

### ISSUE THREAD

**Issue by ekager** [mozilla-mobile/fenix#7999]
We are sending true by default for Leanplum metrics `fxaSignedIn` and `fxaHasSyncedItems` which seems incorrect. These should be false by default AFAICT.

**Comment by ekager** [comment]
@AndiAJ I took this from your comment here: https://github.com/mozilla-mobile/fenix/issues/7425#issuecomment-580166336

Could you check that these defaults are resolved now?

**Comment by AndiAJ** [comment]
Hi @ekager , I've just checked this matter on the latest **Nightly #20380605 from 2/7** using a Google Pixel 3 (Android 9) Leanplum User ID **cbaf1ee6-bf87-4e25-af0d-8876699cad3e**

fxa_signed_in - seems to be fixed ✔️
fxa_has_synced_items - is still set to TRUE ❌

![Capturea](https://user-images.githubusercontent.com/51314259/74040917-587e0a80-49cd-11ea-86d4-7192846ca820.JPG)

I'll remove the QA needed label, and **many thanks for logging this issue!** ☺️

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest `Nightly #20430607 from 2/12` using a Google Pixel 3 (Android 9), Leanplum User ID **f96d227f-409d-48c8-a2d0-9ee47b3a551a**

✔️ fxa_signed_in = False
✔️ fxa_has_synced_items = False 

![Captuuuuuure](https://user-images.githubusercontent.com/51314259/74315539-537bdb00-4d80-11ea-9191-aee8df068824.JPG)
