### ISSUE TITLE
Delay the initialization of NotificationSessionObserver

### ISSUE THREAD

**Issue by emalysz** [mozilla-mobile/fenix#8002]
The NotificationSessionObserver, which helps notify the user a private tab is open, is currently initialized in FenixApplication.onCreate. We should move this away from startup and initialize later.

**Comment by mcomella** [comment]
This is in the backlog, not in progress, so it should be inactive: unassigning.

**Comment by mcomella** [comment]
Closing: we expect to go through startup line-by-line more or less and these will be addressed in time.
