### ISSUE TITLE
[Bug] www.denizbank.com page is not redirected properly

### ISSUE THREAD

**Issue by ozgearslan83** [mozilla-mobile/fenix#8004]
## Steps to reproduce
Below website can not be opened in Firefox  Preview.
www.denizbank.com

### Expected behavior
www.denizbank.com website functions well with other browsers like chrome or safari.
### Actual behavior
Page does not load and it gets error: "The page isn't redirecting properly"
![image](https://user-images.githubusercontent.com/53610296/73478750-b7c59480-43a7-11ea-9e68-fde5dfd311f3.png)

### Device information

* Android device: 
Huawei Mate 20 Pro LYA-L09 
Android Version 9

* Fenix version: 
3.2.0 (Build #20250236)
28.0.2, 1deaef19a
GV: 73.0-20200123180644

**Comment by ozgearslan83** [comment]
Same problem exist for https://www.kariyer.net/ website.

**Comment by reyis4402** [comment]
Bende bugün Twitter'daki yorumları açtığımızda sayfanın yukarıya kaymasını iletmiştim. Farklı bir Türk görmek güzel :)

Tarayıcı baya buglu ve mozillanın sinir eden yavaş çözümünü beklemek gerekiyor.

**Comment by kbrosnan** [comment]
Duplicate denizbank -> https://github.com/webcompat/web-bugs/issues/47882

Duplicate kariyer -> https://github.com/webcompat/web-bugs/issues/48086
