### ISSUE TITLE
When user selects "Open link in new tab", do not load tab in background

### ISSUE THREAD

**Issue by willfs84** [mozilla-mobile/fenix#8005]
When a user selects "Open link in new tab", the tab should not actually load unless the user taps the "SWITCH" button that appears. The benefits are less resource usage (RAM, CPU etc), which is so important on smartphones, especially older and lower end smartphones. I believe Safari for iPhone already does this. 
I think this should be the default behaviour but users should be given the option to turn it off (at least in about:config).

There are other reasons too. For example, sometimes I've opened a new tab (and not switched to it) and it's playing a video in the background. This is not ideal.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-15433)

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813605

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
