### ISSUE TITLE
[Bug] Fatal Exception: java.lang.IllegalStateException

### ISSUE THREAD

**Issue by ozgearslan83** [mozilla-mobile/fenix#8008]
We get below crash in the Yaani application which is based on Firefox Fenix open source code. Users hit this crash too many times:

Stack Trace:
GeckoSession.java line 2389
org.mozilla.geckoview.GeckoSession.acquireDisplay

Fatal Exception: java.lang.IllegalStateException
ATTACH VIEW: Current activity: HomeActivity Other activity: HomeActivity
mozilla.components.browser.engine.gecko.GeckoEngineView$currentGeckoView$1.onAttachedToWindow (GeckoEngineView.java:39)
android.view.View.dispatchAttachedToWindow (View.java:14607)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:616)
Caused by java.lang.IllegalStateException
Display already acquired
org.mozilla.geckoview.GeckoSession.acquireDisplay (GeckoSession.java:2389)
org.mozilla.geckoview.GeckoView.onAttachedToWindow (GeckoView.java:453)
mozilla.components.browser.engine.gecko.GeckoEngineView$currentGeckoView$1.onAttachedToWindow (GeckoEngineView.java:32)
android.view.View.dispatchAttachedToWindow (View.java:14607)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:616)
GleanAPIPool

### Device information
Model: Galaxy S10+
Orientation: Portrait
RAM free: 4 GB
Disk free: 55.97 GB
Operating System
Version: 10
Orientation: Portrait
Jailbroken: No

**Comment by liuche** [comment]
This looks like a dupe of #6812 which has been fixed and went out with 3.2.0. Please reopen if you are still seeing this.
