### ISSUE TITLE
[Bug] Back button can return us to older version of previous page

### ISSUE THREAD

**Issue by lars-t-hansen** [mozilla-mobile/fenix#8013]
## Steps to reproduce

This is in some sense not hard to reproduce but it has a timing component.  It occurs most often on newspaper sites; I see it frequently on theguardian.com and newyorker.com, for example, but also on many other sites.

Go to the site's front page.  Leave the tab open overnight and then reload it to get new content.  Press on an article link.  Then go back.  The old content of the front page is shown.

This usually is only a problem once: if the front page is reloaded again, and we repeat the go-to-article-then-go-back, we get the new front page.

I see this frequently.  I have talked to another person at Mozilla that has observed the same behavior.   The problem has been there for a long time; it was also a problem with Fennec.

### Expected behavior

We should come back to the reloaded front page.

### Actual behavior

We come back to to the old front page.

### Device information

* Android device: Nokia 5.1 plus, Android 9
* Fenix version: Nightly

**Comment by kbrosnan** [comment]
dupe #5869
