### ISSUE TITLE
[Bug] Crash from Top Sites Room

### ISSUE THREAD

**Issue by liuche** [mozilla-mobile/fenix#8014]
We're seeing a new crash with Room, which is likely a regression from Top Sites. This isn't extremely common yet, however, the feature is mostly hidden away right now, and this is showing up in Nightly so we should fix it.

Sentry [crashes](https://crash-stats.mozilla.org/signature/?product=Fenix&version=74.0a1&signature=java.lang.IllegalStateException%3A%20at%20androidx.room.RoomOpenHelper.onOpen%28RoomOpenHelper.java%29&date=%3E%3D2020-01-30T10%3A15%3A00.000Z&date=%3C2020-01-31T10%3A15%3A00.000Z&_columns=date&_columns=product&_columns=version&_columns=build_id&_columns=platform&_columns=reason&_columns=address&_columns=install_time&_columns=startup_crash&_sort=-date&page=1#graphs)

[Socorro graph and reports](https://crash-stats.mozilla.org/signature/?product=Fenix&version=74.0a1&signature=java.lang.IllegalStateException%3A%20at%20androidx.room.RoomOpenHelper.onOpen%28RoomOpenHelper.java%29&date=%3E%3D2020-01-30T10%3A15%3A00.000Z&date=%3C2020-01-31T10%3A15%3A00.000Z&_columns=date&_columns=product&_columns=version&_columns=build_id&_columns=platform&_columns=reason&_columns=address&_columns=install_time&_columns=startup_crash&_sort=-date&page=1#graphs)

* Android device: ?
* Fenix version: ?

**Comment by TitanNano** [comment]
@liuche pretty sure it's this: https://github.com/mozilla-mobile/android-components/pull/5764

**Comment by TitanNano** [comment]
@liuche was fixed in `Nightly 200201 18:00 (Build #20321807)`

**Comment by gabrielluong** [comment]
> @liuche was fixed in `Nightly 200201 18:00 (Build #20321807)`

Closing the issue since it's fixed.
