### ISSUE TITLE
Fix UI Test failure API 25 verifyContextCopyLink test

### ISSUE THREAD

**Issue by ekager** [mozilla-mobile/fenix#8015]
This seems to be failing on PRs from yesterday

>  androidx.test.espresso.base.DefaultFailureHandler$AssertionFailedWithCauseError: 'with text: a string containing "http://localhost:59725/pages/generic3.html"' doesn't match the selected view.
Expected: with text: a string containing "http://localhost:59725/pages/generic3.html"
Got: "TextView{id=2131296904, res-name=mozac_browser_toolbar_url_view, visibility=VISIBLE, width=834, height=140, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=true, is-enabled=true, is-focused=false, is-focusable=true, is-layout-requested=false, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@5c03d55, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, text=http://localhost:59725/pages/generic4.html, hint=Search or enter address, input-type=0, ime-target=false, has-links=false}"

**Comment by ekager** [comment]
CC @AaronMT

**Comment by AaronMT** [comment]
Ran this test on API 25 Nexus 6 (7.1.1) (AVD) locally looped 100 times and could not get it to fail. Let's try a different object to wait on and see if that does anything.
