### ISSUE TITLE
Avoid duplicate domains in collection listing

### ISSUE THREAD

**Issue by darkwing** [mozilla-mobile/fenix#8016]
When a collection features multiple pages from a single domain, we probably don't need to repeat the domain:

![Screenshot_20200131-103404](https://user-images.githubusercontent.com/46655/73532061-204e5900-441c-11ea-9e89-86793b2357fa.png)

Just a minor polish idea.

**Comment by darkwing** [comment]
Simple fix is here:  https://github.com/darkwing/fenix/commit/755735c7d84a39cd7fd154885129b6ced2d7c082

Not opening PR to prevent unwanted noise during our push to code freeze.

**Comment by darkwing** [comment]
Before:

![Screenshot_20200131-115927](https://user-images.githubusercontent.com/46655/73534918-a7063480-4422-11ea-81dd-33e290876beb.png)


After:



![Screenshot_20200131-120021](https://user-images.githubusercontent.com/46655/73534913-a4a3da80-4422-11ea-9745-cf3a24ed7399.png)

**Comment by sv-sdeiac** [comment]
Verified as fixed using the latest version of Firefox Preview Nightly 2/11 #20420610.

Devices:
- Motorola Moto G6 (Android 8);
- Samsung Galaxy S8 (Android 9);
- Google Pixel 3 (Android Q).
