### ISSUE TITLE
[Bug] Map navigation is jittery on https://www.deutschepost.de/de/s/standorte.html

### ISSUE THREAD

**Issue by LaurentiuApahideanSV** [mozilla-mobile/fenix#8018]
## Steps to reproduce
1. Go to https://www.deutschepost.de/de/s/standorte.html
2. Pan around the map, zoom in and out.
### Expected behavior
Map exploration should be smooth
### Actual behavior
Map exploration is jittery 
### Device information
* Android device:
Pixel 3 XL (Android 9)
Samsung Galaxy S9 (Android 8.0.0)
* Fenix version: ?
Firefox Preview Nightly 200131 (Build #20310608) GV: 74.0a1-20200129093157
Firefox Release 68.4.2, Beta 68.5b5 see issue: https://bugzilla.mozilla.org/show_bug.cgi?id=1612365

**Comment by mcomella** [comment]
I suspect this is a platform issue so I refiled here: https://bugzilla.mozilla.org/show_bug.cgi?id=1616445

@sblatz How do we track things that need to change upstream? Do we keep the issue open or close it?

**Comment by mcomella** [comment]
Closing: we're tracking at the platform level (and it looks like that bug is closed anyway).
