### ISSUE TITLE
Add paged view in reading mode (vs scrolling)

### ISSUE THREAD

**Issue by echeoquehaii** [mozilla-mobile/fenix#8019]
### Why/User Benefit/User Problem
This is a issue that concerns me since a long time. Many researches show that reading in paged view has many benefits (for example: https://www.researchgate.net/publication/221342423_Eye_movement_study_of_reading_text_on_a_mobile_phone_using_paging_scrolling_leading_and_RSVP).

First of all it is less demanding for our eyes, it reduces eye strain and provides us better eye muscles movements. It also showed better and easier understanding of the text in many cases, especially for long text and articles, in which it helps highlighting and understanding paragraphs and text structure.

I think this should be default in reading mode, but it could also be added just as an option. Reading mode is mostly used for long texts, so it should provide us with the best tools to make reading as pleasing as possible and paged view is a core feature in this regard.

### What/Requirements
Add an option in reading mode to switch between paged view and scrolling.

### Acceptance Criteria (how do I know when I’m done?)
When in the reading mode options there will be a switch to activate paged view instead of scrolling.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-15444)

**Comment by jonalmeida** [comment]
This has not revived any duplicates or other interactions since it was filed. We will not be moving this request to Bugzilla.
