### ISSUE TITLE
Desktop site should also automatically remove "m." portaint of the link

### ISSUE THREAD

**Issue by McMakr0** [mozilla-mobile/fenix#8020]
### Why/User Benefit/User Problem
When i switch to desktop mode on site which link is starting with "m.", (eg. m.facebook.com) i will end up in desktop mode but the site remains in mobile version.
### What/Requirements
Remove the "m." from link when switched to desktop site mode.
### Acceptance Criteria (how do I know when I’m done?)
When I switch to desktop site, browser will automatically remove "m." from link and show me the desktop version of that site without the need of manually removing the "m." myself.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-15446)

**Comment by s-ankur** [comment]
Afiak no other browser does this currently. At least chrome does not.
Also the desktop versions of many m. websites differ quite a lot from their mobile counterparts.
So I suppose a case could be made for showing m. websites as they are in the desktop mode.

**Comment by McMakr0** [comment]
Chrome version 79.0.3945.136 on my Pixel 3 does it, and i'm afraid i do not fully understand your suggestion. I mean what's the point of desktop mode when it would just show mobile sites just zoomed out, if i get it correctly. Other sites that have same links for mobile and desktop versions are switching between them when switched to desktop mode, it is just that some sites are differring these versions by adding "m." to the link.

**Comment by s-ankur** [comment]
Ok so i tried to do this on the same version of chrome and i couldnt get it to work the same way. does it work with m.facebook.com for you?

**Comment by McMakr0** [comment]
![Screenshot_20200202-195457](https://user-images.githubusercontent.com/45382482/73613460-3879d000-45f6-11ea-92c3-799dd5e63709.png)
![Screenshot_20200202-195440](https://user-images.githubusercontent.com/45382482/73613463-3a439380-45f6-11ea-9895-67afcd967e81.png)
Yes it does and i have tried other sites aswell and it does seem to work everywhere, but strangely, when i autofill wikipedia link from suggestions on some irelevant topic, then it does not remove it, and even if I search wikipedia from that link on other topic and then switch to desktop mode, it will show me that previous link with m. part not removed but in "desktop mode", so maybe it doesn't work dor you because it is some kind of autofill feature?

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807149

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
