### ISSUE TITLE
[Bug] PWA: using a PWA shortcurt or creating one crashes Fenix

### ISSUE THREAD

**Issue by klint** [mozilla-mobile/fenix#8022]
## Steps to reproduce
Open a site that is PWA enabled and press "Install"
resp.
Press a already added PWA shortcut on the device's homescreen

### Expected behavior
The shortcut is added 
resp.
The site is launched in PWA mode

### Actual behavior
Fenix crashes

### Device information

* Android device: Xiami Redmin Note 7 with MIUI 10
* Fenix version: Build 20310608

**Comment by TitanNano** [comment]
Same as https://github.com/mozilla-mobile/fenix/issues/8014

**Comment by kbrosnan** [comment]
Closing as a duplicate
