### ISSUE TITLE
[Bug] Logins is unchecked for the first sync from Account settings

### ISSUE THREAD

**Issue by sv-sdeiac** [mozilla-mobile/fenix#8023]
## Steps to reproduce
1. Connect with a valid account;
2. Open the "Account settings" section while the sync is performed;
3. Pay attention to the "Choose what to sync" list.

### Expected behavior
All three options (bookmarks, history, logins) are greyed and checked by default till the first sync is finished.

### Actual behavior
Logins option is not checked while the first sync is finished.

### Device information

* Android device: Nokia 6 (Android 7.1.1), LG g7 fit (Android 8.1).
* Fenix version: Firefox Preview Nightly 1/31 #20310607.
### Notes
* This issue is always reproducible with the first sync after login. 
![Screenshot_20200131-165035](https://user-images.githubusercontent.com/40264165/73549307-04ae7700-444b-11ea-9ce1-1db80abef07c.png)

**Comment by softvision-miralobontiu** [comment]
Verified as fixed on the latest Nightly build from 3/16 with OnePlus 5T (Android 9), and Sony Xperia Z5 Premium (Android 7.1.1).
