### ISSUE TITLE
Restore add-on support to Firefox Nightly

### ISSUE THREAD

**Issue by jdrch** [mozilla-mobile/fenix#8028]
### Why/User Benefit/User Problem

Users shouldn't have to suffer from lack of extensibility just because they're on mobile. 

### What/Requirements

Restore add-on support to Firefox Nightly.

### Acceptance Criteria (how do I know when I’m done?)

When uBlock Origin works in Firefox Nightly again.

**Comment by cadeyrn** [comment]
Duplicate of #5315.

Firefox Preview/GeckoView Add-ons Support:
https://blog.mozilla.org/addons/2019/10/23/fx-preview-geckoview-add-ons-support/
