### ISSUE TITLE
Restore ability to open tabs in the background to Firefox Nightly

### ISSUE THREAD

**Issue by jdrch** [mozilla-mobile/fenix#8029]
### Why/User Benefit/User Problem

Can open links from another app without interrupting experience in that app. The *status quo* has seriously broken my newsreading workflow on Android.

### What/Requirements

Restore ability to open tabs in the background to Firefox Nightly

### Acceptance Criteria (how do I know when I’m done?)

When the user can open tabs in Firefox without the browser opening over the app they're currently in.

**Comment by cadeyrn** [comment]
Duplicate of #470.
