### ISSUE TITLE
Add "Open with App" option in the long-press link context menu

### ISSUE THREAD

**Issue by jdrch** [mozilla-mobile/fenix#8031]
### Why/User Benefit/User Problem

Users should be able to open *selected* links directly in their corresponding apps from the browser.

### What/Requirements

Restore the "Open with App" option in the long-press menu in Firefox Nightly on Android

### Acceptance Criteria (how do I know when I’m done?)

When it is once again possible to open *selected* links directly in their corresponding apps from the browser.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-15455)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1809258

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
