### ISSUE TITLE
[Bug] reader view zoom level stuck

### ISSUE THREAD

**Issue by MichaelDemeyer** [mozilla-mobile/fenix#8032]
## Steps to reproduce
Open a website, zoom in. 
Switch to "reader view" 
### Expected behavior
The reader view should open at standard zoom level OR zoom level should be adjustable. 
### Actual behavior
Reader view open with same level of zoom and can't be adjusted in any way. 

### Device information

* Android device: Honor 10
* Fenix version: Firefox Mobile 73.0

**Comment by csadilek** [comment]
Closing as dupe. Please track https://github.com/mozilla-mobile/fenix/issues/2633.
