### ISSUE TITLE
Allow jobs to run after visual completeness

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#8034]
This will allow us to prevent initialization of some non-essential components from blocking startup.

Will has a WIP: https://github.com/mozilla-mobile/fenix/pull/7901

**Comment by mcomella** [comment]
We discussed that we may not want to spend too much time on this in the short term so we should consider **doing something simple**. For example, we can create an abstraction for "visual completeness" that has a dumb implementation: e.g. scheduling a delay after the first frame is drawn. Some notes:
* How does Google determine visual completeness in their apps (e.g. to register `reportFullyDrawn`)?
* We could identify the last view we expect to be drawn (assuming there is only one async draw event) and call post on it.
* To address the problem that other Activities can open without HomeActivity, other Activities can opportunistically try to start these things on the main thread in their `onCreate` methods (if they're not already started) and HomeActivity can use the delayed approach. This is okay because HomeActivity (or similar), according to telemetry, is the most common thing to open (according to csadilek).
* I've used `getViewTreeObserver` + pre-draw listener and Marc mentioned the `Choreographer` API as options to find when frames are drawn.

**Comment by emalysz** [comment]
I found this very useful blog post: https://developers.google.com/web/fundamentals/performance/user-centric-performance-metrics

Google these identified 3 important topics in measuring load performance:
1. **Is it happening?** 
       -First paint: first point at which we render anything that is different than previous screen
       -First contentful paint: first DOM content is rendered 
2. **Is it useful?**
       -First meaningful paint: time when hero elements (most important elements) are rendered
3. **Is it usable?** 
       -Visually rendered and usable. JS loaded and main thread is idle

They also use APIs like the `Performance observer` where you can subscribe to performance events and respond asynchronously. A polyfill also has a `getConsistentlyInteractive` method that tracks the time to interactive.

**Comment by emalysz** [comment]
QA testing:
Ensure that startup is possible by navigating through various activities. 
Launches through IntentReceiverActivity, IntentReceiverActivity, and OSSLicenses (when passed a proper intent) should all be verified. 

Additionally, navigate to activities again to ensure the second time the activity is rendered we don't crash.

**Comment by sv-ohorvath** [comment]
Verified this on Nightly 3/3, with 2 devices: Motorola Moto G6 (Android 8.0), Mi 4i (Android 5.0.2)
Areas covered:
- launch app from PlayStore
- homescreen launcher  
- private browsing launcher 
- close private tab notification (known issue: https://github.com/mozilla-mobile/fenix/issues/8590) 
- pages from settings that open in a custom tab: sign in, about/support pages 
- open from history, bookmarks: in normal mode & private 
- open links from external apps: in normal mode & private 
- open custom tabs from apps: normal mode & private 
- open PWA & custom tabs in PWA: normal mode & private (known issue: https://github.com/mozilla-mobile/fenix/issues/8929)
- open new private tab from 3 dot menu 
- open new tab from 3 dot menu 

@emalysz This is what I could think of from so far, please let me know of other scenarios if you think I missed any. Thanks!

**Comment by emalysz** [comment]
Thanks @sv-ohorvath! That seems to be a sufficient analysis. Going to close out this issue.
