### ISSUE TITLE
[Bug] widget not working

### ISSUE THREAD

**Issue by leolivier** [mozilla-mobile/fenix#8036]
Firefox preview was updated automatically yesterday night (January 31) to the latest version on my honor 8x.
The widget disappeared after this update and when I add it again, I get an initialization error (in French, says something like "error when loading").
Removing and recreating the widget does not solve the issue.

### Device information

* Android device: honor 8x
* Fenix version:  3.2.0 (Build #20250236)
28.0.2, 1deaef19a
GV: 73.0-20200123180644

**Comment by kbrosnan** [comment]
Are you using a custom home screen or launcher?

**Comment by leolivier** [comment]
No, everything standard. I have also the "usual" Firefox installed.

**Comment by leolivier** [comment]
Actually, I meant standard Honor launcher, not the Android one, not sure if it was clear...

**Comment by Ruin0x11** [comment]
Also happens for me. It says the widget cannot be displayed.

![Cropped_image_20200202_141753_6066931680453605398](https://user-images.githubusercontent.com/6700637/73616330-d9e92d80-45c6-11ea-93a3-f5ebba52effc.png)

**Comment by AaronMT** [comment]
Does clearing the application's cache resolve this?

**Comment by leolivier** [comment]
Just tried: no, it doesn't...

**Comment by leolivier** [comment]
Fixed, I don't know how... :flushed: but I just can see the widget now with no error
