### ISSUE TITLE
[Bug] Play Store page for Firefox Preview Nightly has missing links

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#8040]
## Steps to reproduce
Open play store 
go to the firefox preview nightly page

### Actual behavior
> Firefox Nightly automatically sends feedback to Mozilla. You can read more about telemetry privacy here.

But there is no link for here.

**Comment by kbrosnan** [comment]
Looks like a bug in the Google Play app. The link is present in the website and there is a more prominent link to the privacy policy in the `Developer contact` section of the app.
