### ISSUE TITLE
CRASH App requires INTERACT_ACROSS_USERS_FULL permission to run

### ISSUE THREAD

**Issue by SerhanYavuz** [mozilla-mobile/fenix#8041]
App gives error after first running or debugging attempt. 

# Steps to reproduce

1. delete the application from device
2. click to `run` or `debug` in android studio 

# Expected behavior

# Actual behavior
App crashes

# Notes 
[Logcat](https://drive.google.com/file/d/16EO-uRVU-jpIkYggkFPsQb6TY17H1MsT/view?usp=sharing)
```
    java.lang.SecurityException: Permission Denial: broadcast from android asks to run as user -1 but is calling from user 0; this requires android.permission.INTERACT_ACROSS_USERS_FULL or android.permission.INTERACT_ACROSS_USERS

```
# Device information
- Samsung Galaxy Grand Prime+
- Fenix version: current master branch

**Comment by pocmo** [comment]
Related:
https://sentry.prod.mozaws.net/share/issue/f49d2f796a134cfc83887df8bcfac104/

**Comment by kbrosnan** [comment]
No instances of this crash on 78 or 79 betas, closing. Reporter if you are still able to reproduce this crash on an up to date beta please provide a crash ID. Information on that process is at https://github.com/mozilla-mobile/fenix/wiki/Logging-Crash-Information
