### ISSUE TITLE
Use search suggestions without searching

### ISSUE THREAD

**Issue by Octoton** [mozilla-mobile/fenix#8043]
### Why/User Benefit/User Problem
When i do a search, searh suggestions are great but sometime i want to add other term to it

### What/Requirements
Be able to copy/paste the search suggestions into the searchbar without loading it.
![Screenshot_20200203-101742_Firefox_Nightly](https://user-images.githubusercontent.com/56130419/73640477-9a761c00-466e-11ea-90a9-22571ac93bad.png)

### Acceptance Criteria (how do I know when I’m done?)
I can click on a visible button to put the search suggestions into the searchbar and continue to add word to it

**Comment by ernstp** [comment]
Could also use long press.

**Comment by Octoton** [comment]
It is not as easy to know the feature exist, but yep

**Comment by cypressious** [comment]
I went ahead and created an issue in the android-components repo since the functionality actually lives there: https://github.com/mozilla-mobile/android-components/issues/6813

**Comment by cypressious** [comment]
I've created a PR https://github.com/mozilla-mobile/android-components/pull/6824

**Comment by jonalmeida** [comment]
There was some UX feedback on Focus for this request that's worth referencing here: https://github.com/mozilla-mobile/focus-android/issues/3646

**Comment by AmyYLee** [comment]
Assigning to @brampitoyo

**Comment by brampitoyo** [comment]
@Octoton your idea makes a lot of sense!

Let’s add a prefill arrow (↖︎) icon to the side of each search suggestion, that can be used to append keywords.

<img width="360" src="https://user-images.githubusercontent.com/51007/84110279-aa689700-aa78-11ea-9f98-59af8519d379.png">

Asset: https://share.getcloudapp.com/z8u87yKE

**Comment by cypressious** [comment]
@brampitoyo Could you possibly take a look at my PR https://github.com/mozilla-mobile/android-components/pull/6824?

**Comment by brampitoyo** [comment]
@cypressious Feedback added. Thanks!

**Comment by brampitoyo** [comment]
@jonalmeida @cypressious Sorry. I didn’t know that there’s copy involved in this issue.

It would be fine to follow the same copy that Fennec or Firefox for iOS uses for this icon.

**Comment by cypressious** [comment]
@brampitoyo 
I don't think Fennec has that functionality. I don't have an iPhone to test Firefox for iOS

**Comment by brampitoyo** [comment]
@jonalmeida @cypressious For accessibility/screen reader/TalkBack purpose, the label for this button should be `Refine`.

**Comment by brampitoyo** [comment]
@jonalmeida @cypressious I’d like to add a small correction to PR https://github.com/mozilla-mobile/android-components/pull/6824

The first search suggestion is meant to track with the user’s keyboard and typing speed, so it shouldn’t have the Refine (↖︎) action. All other search suggestions, which come from the search provider’s server, should have this action.

**Comment by jonalmeida** [comment]
> The first search suggestion is meant to track with the user’s keyboard and typing speed, so it shouldn’t have the Refine (↖︎) action.

This makes sense but is hard to implement because we currently don't distinguish the first entry from the rest of the suggestions.

**Comment by brampitoyo** [comment]
As mentioned by @ShatteredPixel in https://github.com/mozilla-mobile/fenix/issues/12050#issuecomment-660557463, we should remember to pop the keyboard back up after the user has tapped the Refine (↖︎) action – just in case the page was scrolled down and the keyboard was minimised.

**Comment by cypressious** [comment]
@brampitoyo I've added the suggestion to the PR https://github.com/mozilla-mobile/android-components/pull/6824

**Comment by sflorean** [comment]
Verified as fixed on Nightly 8/12 with the following devices:
- Samsung Galaxy Note 10 (Android 10)
- Google Pixel 3 (Android 11)
- Huawei MediaPad M2	(Android 5.1.1)

@jonalmeida Filled issue #13520 for the prefill arrow that is displayed for the first suggestion.
