### ISSUE TITLE
[Bug] Custom tab toolbar truncates ipv4 hostnames to the last two dot-separated parts

### ISSUE THREAD

**Issue by trupples** [mozilla-mobile/fenix#8048]
My guess is that this is an edge case of the eTLD+1 parsing/extraction.

## Steps to reproduce

1. Start a local HTTP server, or find a HTTP server which does not redirect from its ipv4 address to an actual hostname.
2. Access any page served by that server from an app which uses Custom tab. I tried Discord and Telegram.
3. Look at the hostname in the toolbar.

### Expected behavior

Toolbar shows the entire IP in the hostname field. (e.g. 192.168.100.107)

The Firefox Preview app properly shows the whole IP in the URL bar:
![correct-firefox](https://user-images.githubusercontent.com/5314253/73659013-0de35200-469e-11ea-851a-ae4bb77c4850.jpg)

### Actual behavior

Toolbar only shows the last two parts of the IP address. (e.g. 100.107)
![incorrect-webview](https://user-images.githubusercontent.com/5314253/73659014-0de35200-469e-11ea-91be-bbcccdc5281c.jpg)

### Device information

* Android device: OnePlus 7 Pro GM1910
* Fenix version: 3.2.0 (Build #20250236)
28.0.2, 1deaef19a
GV: 73.0-20200123180644

**Comment by trupples** [comment]
Possibly relevant: #5818

**Comment by kbrosnan** [comment]
We should make sure we are using the same algorithm in the Custom tab view as in the NavBar
