### ISSUE TITLE
[Bug] Tab closed popup won't disappear

### ISSUE THREAD

**Issue by MishterKirby** [mozilla-mobile/fenix#8051]
## Steps to reproduce
Close a tab
### Expected behavior
Tab closed popup should appear, then disappear after a while
### Actual behavior
Tab popup appears, and stays there until "Undo" is pressed.
### Device information

* Android device: LG Stylo 2 (LS775)
* Fenix version: 3.2.0

**Comment by cadeyrn** [comment]
Duplicate of #7799.
