### ISSUE TITLE
Mitigate impact of setDayNightTheme on startup for GA

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#8053]
To make startup as fast as possible, we want to move as much as we can after visual completeness. The perf group is not sure what setDayNightTheme does (add a comment or make a clearer title please! :)) but we're wondering if this can wait until visual completeness. So...

Investigate what this does, determine if it can be moved, and if so, move it! Since we're trying to move anything that is not essential, even if setDayNightTheme has some effect on the appearance at the time of visual completeness, we should consult product/design on whether the change in visual appearance is worth the impact on performance.

**Comment by emalysz** [comment]
@mcomella I discussed setDayNightTheme with @ekager, and it does not make sense to move it to after visual completeness. iiuc this method has to recreate the entire activity, and its placement helps avoid unnecessary recreations. If it is called after we create host components, then the config will change and the activity will be recreated again. Fenix thinks the earlier the better, and even if we were to move it away from FenixApplication, then HomeActivity would take a performance hit.

I think we should close out this issue and focus on other items.

**Comment by ekager** [comment]
From the Android team blog post:
https://medium.com/androiddevelopers/appcompat-v23-2-daynight-d10f90c83e94

```
The value you set is not persisted across process starts though, therefore you need to set it every time your app process is started. I recommend setting it in your application class (if you have one) like so:

public class MyApplication extends Application {
    
    public void onCreate() {
        super.onCreate();        
        AppCompatDelegate.setDefaultNightMode(AppCompatDelegate.MODE_NIGHT_YES);
    }
}
```

**Comment by mcomella** [comment]
That makes sense to me. Quickly looking this over on an old profile, `setDayNightTheme` doesn't seem hugely impactful on startup time so this is probably okay. Looking at the code, there doesn't seem to be much we can optimize here either.

@emalysz Would you mind confirming the startup time on a release build and, if it's trivial, closing the issue? Thanks.

nit: one thing we could also improve is that `setDayNightTheme` is unintuitive to me as a name because I've only heard to it referred to as "dark mode". I'd prefer if this was called something like, `setDarkOrLightMode`, but the current name makes sense because Android unintuitively refers to dark mode in the SDK as "night mode" (🙄). If we keep the name the same, maybe we can add a clarification kdoc to the method. Up to you if you want to make the change!

**Comment by emalysz** [comment]
I have confirmed on release builds that setDayNightTheme has a trivial impact on startup times. In fact, I saw an 2.14 ms gain on average with a Pixel2 when the method was commented out, which can be attributed to noise.
