### ISSUE TITLE
Mitigate impact of Experiments.initialize on startup, if impact is non-trivial

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#8056]
We're trying to move everything non-essential until after visual completeness in order to improve startup time. Experiments.initialize is used by Gecko for the WebRender experiment so, in the current implementation, must run before Gecko starts and before visual completeness.

We should check if Experiments.initialize is slow and, if so, do one of:
- Ask the experiments team how much improvement they expect they can make by GA. If it seems reasonable, ask them to work on it immediately
- If this isn't possible, consult the Gecko product team about removing the WebRender experiment and remove Experiments.initialize.

Note: the profiler for this code includes some parts of Gecko/Core init so it isn't a useful tool to determine the impact of this code.

**Comment by emalysz** [comment]
Experiment initialization was removed by https://github.com/mozilla-mobile/fenix/pull/8396

**Comment by mcomella** [comment]
@emalysz Can you apply a QA label? If it needs QA, remember that the issue needs to stay open.

**Comment by emalysz** [comment]
We removed experiments from startup to improve performance. 

QA testing:
-Ensure no crashes in Cold startup (remove application from recently used)

**Comment by sv-ohorvath** [comment]
No crashes encountered today while testing Beta 4.0. I think we can close this. Please reopen if any new reports appear.
