### ISSUE TITLE
Take app link profile and determine if there are any trivial wins

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#8061]
afaik, we haven't recently taken a profile to see if we're doing anything dumb. In particular, we want to ensure:
- Gecko is started as early as possible
- The page starts loading in Gecko as early as possible
- We drawn the first frame as early as possible (after page load begins?)

Let's take a profile and see what improvements we can make.

**Comment by emalysz** [comment]
Attached is a profile that links to apple.com
[AppLink.trace.zip](https://github.com/mozilla-mobile/fenix/files/4247106/AppLink.trace.zip)

I believe Gecko is initialized as early as possible, as `GeckoSession.createEngine` happens immediately after `FenixApplication.onCreate`. 

One thing I did notice is that TrackingProtectionOverlay methods are called throughout the load. Similarly to how we are trying to find a VisualCompleteness stage, I wonder if we can find a point at which the Page is fully loaded, and then invoke the TrackingProtectionOverlay methods to ensure we don't call them multiple times.

I am investigating if we can improve any of the BrowserFragment methods like `onViewCreated` or `initializeUI`.

**Comment by emalysz** [comment]
All numbers were taken on a Pixel2 using performance variant.

Here is a breakdown of `BrowserFragment.initializeUI`, which took 257.95 ms with signifcant methods (that took > 5ms).
```
BaseBrowserFragment.initializeUI: 96.84%
  BrowserToolbarView<init>: 68.58
    LayoutInflater.inflate(): 47.36%
    DefaultToolbarIntegration<init>: 13.63%
    DefaultToolbarMenu<init>: 2.48%
  AppLinksFeature<init>: 3.87%
  UseCases.getDownloadedUseCases(): 2.72%
  ViewBoundFeatureWrapper.set(): 2.64%
  BrowserFragment.getContextMenuCandidates(): 2.16%
  DownloadsFeature<init>: 2.12%
```

**Comment by emalysz** [comment]
Filed https://github.com/mozilla-mobile/fenix/issues/8827 and https://github.com/mozilla-mobile/fenix/issues/8826

**Comment by mcomella** [comment]
Closing: emalysz already filed some issues and we are already improving many things in app link so this issue isn't a focus right now.
