### ISSUE TITLE
[Bug] "Accept the Risk" button on "no internet connection" error page

### ISSUE THREAD

**Issue by cadeyrn** [mozilla-mobile/fenix#8065]
### Steps to reproduce

1. make sure you're **offline**
2. try to load a website

### Expected behavior

No "Advanced" / "Accept the Risk" button on the "No internet connection" error page because it doesn't make sense at all.

### Actual behavior

There is an "Advanced" button on the "No internet connection" error page. After clicking the button you can press a "Accept the Risk" button.

![Screenshot_20200203-215726](https://user-images.githubusercontent.com/1100614/73690585-f83b5000-46d0-11ea-9496-bdc9d45fbdeb.jpg)

### Device information

* Android device: OnePlus 7T Pro McLaren Edition / Android 10
* Fenix version: master branch revision ae445abff398a3b8273d6dfd5468b75815cd62b8

**Comment by NotWoods** [comment]
cc @sblatz

**Comment by cadeyrn** [comment]
This is fixed now.

**Comment by sv-sdeiac** [comment]
Verified as fixed using Firefox Preview Nightly 2/7 #20380605.

Device:
- Huawei Honor 8 (Android 7.0);
- Nokia 6 (Android 7.1.1);
- Samsung Galaxy S8 (Android 9).
