### ISSUE TITLE
[Bug] The cursor jumps around while trying to select the text

### ISSUE THREAD

**Issue by ghost** [mozilla-mobile/fenix#8072]
## Site with issue and any steps to reproduce
Go to the Website: 
1. https://www.animesonglyrics.com/tate-no-yuusha-no-nariagari/kimi-no-namae
2. Try to copy the text (In this case the Lyrics)
3. See the cursor jump around while trying to select the text

### Expected behavior
The cursor shouldn't jump around, I have tried the same in Chrome and it works without any problem.

### Actual behavior
The cursor jumps around while trying to select text

### Does toggling Tracking Protection fix the issue? (Press the lock icon in the toolbar while on the site to see toggle)
No

### Can you reproduce in [Firefox for Android](https://play.google.com/store/apps/details?id=org.mozilla.firefox)?
No

### Can you reproduce in Chrome (or other non-Mozilla browser)?
No

### Device information

* Android device: Motorola One Power Running Android 10 January security patch
* Fenix version: 3.2.0 (Build #20250236)

**Comment by SS1113** [comment]
This can still be reproduced on the Nightly 200420 06:01 (Build #2015735603)

**Comment by sflorean** [comment]
I was able to reproduce on the latest Nightly 4/23.

**Comment by ShatteredPixel** [comment]
Hi, I am the reporter of this issue. Please let me know if I can provide you any more information.

Thank you! :)

**Comment by AndiAJ** [comment]
Not reproducible anymore on the latest Nightly Build 201103 using the following devices:
• Google Pixel 3a (Android 11)
• Huawei Mate 20 Lite (Android 10)
• OnePlus A3 (Android 6.0.1)
