### ISSUE TITLE
[Bug] Pressing back button from url bar also performs a navigate back

### ISSUE THREAD

**Issue by tom-james-watson** [mozilla-mobile/fenix#8073]
## Steps to reproduce

1) Open new tab
2) Navigate to mozilla.org and wait for it to load
2) Navigate to example.com and wait for it to load
3) Press url bar
4) Press back
5) Repeat steps 4) and 5) a few times as necessary

### Expected behavior

Url bar closes and you stay on example.com

### Actual behavior

Url bar closes and you also navigate back to mozilla.org

### Device information

* Android device: Samsung S7 Android 8.0
* Fenix version: 3.2.1

**Comment by tom-james-watson** [comment]
This does not happen 100% of the time, though it doesn't seem to be dependent on how fast I press back after opening the url bar. I would say in my experience this happens maybe 50% of the time, though.

**Comment by tom-james-watson** [comment]
Can confirm that this is still happening on `Nightly 200309 Build #20691807`

**Comment by tom-james-watson** [comment]
This now seems to happen 100% of the time.

**Comment by sflorean** [comment]
@tom-james-watson since some "back button" issues have been fixed, this is still reproducible for you? I am not able to reproduce it on latest Nightly.

**Comment by tom-james-watson** [comment]
Ah, no, I think this has been fixed for a few months now actually! Forgot to close the issue out.
