### ISSUE TITLE
Fennec migration: Beta/Nightly migration icon is displayed as Fenix Release

### ISSUE THREAD

**Issue by ebalazs-sv** [mozilla-mobile/fenix#8077]
## Preconditions:
Have Firefox Beta/Nightly installed.
## Steps to reproduce
1. Replace Fennec Beta/Nightly with Fenix using a Beta/Nightly build from https://github.com/mozilla-mobile/fenix/wiki/Fennec-Migration;
2. Observe the homescreen icon.
### Expected behavior
Fenix Beta/Nightly icon is displayed on homescreen.
### Actual behavior
Fenix Release icon is displayed on homescreen.

### Device information

* Android device: Samsung Galaxy S8 (Android 9) - ARM64; Motorola Nexus 6 (Android 7.1.1) - ARM; Xiaomi Mi Pad 2 (Android 5.1) - x86.
* Fenix version: Beta 12/10 GV 71; Nightly 191210 GV 72

**Comment by pocmo** [comment]
Closing: For Nightly this should be fixed. The beta icon will be updated as part of https://github.com/mozilla-mobile/fenix/issues/8277

**Comment by ebalazs-sv** [comment]
This is fixed on Nightly migration builds and for Beta migration will be updated on #8277. Due to that I will move this to Done. Thanks!
