### ISSUE TITLE
 Option to wrap text to screen width (rather than container width)

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/fenix#808]
### Why/User Benefit/User Problem

This is a feature [desired by users](https://www.reddit.com/r/firefox/comments/argotb/screenshots_of_fenix_build_101907/egntrur/).

Port of [Bug 578179](https://bugzilla.mozilla.org/show_bug.cgi?id=578179)

>WebKit on Android has an option to wrap text so that lines of text are no wider than the screen width.  This means that text reflows to fit the screen as the user zooms in and out.  The width of block-level elements does not change - the overall layout of the page stays the same, and only the text wrapping is altered.

>We want this option for Fenix, since (a) it makes many web pages much easier to read on small screens, especially in portrait orientation, and (b) we want to convince Android users to switch from the default browser, where many of them rely on this feature.

### What / Requirements

Option in accessibility for "text wrap"

### Acceptance Criteria (how do I know when I’m done?)

Enabling this option makes it so that if a user zooms in, text is wrapped to the viewport.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-15492)

**Comment by kbrosnan** [comment]
Gecko bug is https://bugzilla.mozilla.org/show_bug.cgi?id=1547181

**Comment by reinhart1010** [comment]
SeeAlso: https://groups.google.com/forum/m/#!topic/fenix-nightly/qoxzOpEySDk

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1809953

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
