### ISSUE TITLE
[Bug] The floating pop-up is not positioned correctly when scrolling 

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/fenix#8080]
## Steps to reproduce
1. Launch Fenix and reach the home screen.
2. Add a website to Firefox home.
3. Reach the Firefox home.
4. Tap and hold on the recently added top site and scroll slowly 

### Expected behavior
When releasing the button, the floating pop-up should be displayed near the recently added top site.
### Actual behavior
The floating pop-up remains in the same place.
### Device information

* Android device: **Huawei 20 Mate(Android 8.1.1).**
* Fenix version: **Latest Nightly from 2/4.**

![ezgif-5-5b3e218f61d0 (1)](https://user-images.githubusercontent.com/42831109/73761786-fc6e7880-4777-11ea-8eb0-4678e5372c18.gif)

**Comment by ekager** [comment]
Looks like these menus get dismissed now before scrolling but let's test

**Comment by AndiAJ** [comment]
Hi, **still reproducible** on the latest **`Nightly Build #21130610 from 4/22`** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)

►Video
![20200422-092501](https://user-images.githubusercontent.com/51314259/79947912-837be480-847b-11ea-9d19-08066e84536e.gif)

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **Nightly Build 200625 from 6/25** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)

► Video
![20200625-113959](https://user-images.githubusercontent.com/51314259/85686943-141fac80-b6d9-11ea-938f-0dc6e7f13bdc.gif)
