### ISSUE TITLE
[Bug] on nightly new menu top bar is not align with awsomebar

### ISSUE THREAD

**Issue by Octoton** [mozilla-mobile/fenix#8087]
When comparing the position of the search bar in those 3 images (problem in the last one), we can see a alignment problem and a coloring mismatch.

![Screenshot_20200204-235400_Firefox_Nightly](https://user-images.githubusercontent.com/56130419/73795245-715aa600-47aa-11ea-90d7-e3985d9b838b.png)

![Screenshot_20200204-235332_Firefox_Nightly](https://user-images.githubusercontent.com/56130419/73795241-70297900-47aa-11ea-8267-bdfbb7e22940.png)
![Screenshot_20200204-235354_Firefox_Nightly](https://user-images.githubusercontent.com/56130419/73795243-70c20f80-47aa-11ea-91e2-a63f079db9fd.png)

Android version: 9
Fireox version: nightly from 5/02/20

**Comment by Octoton** [comment]
Same in bottom bar mode

**Comment by Octoton** [comment]
New home page bar seems to be missing some top and bottom margin, this make the bar strange looking as the left/right margin are not the same size. All margin should follow the left/right one.

**Comment by Dunexus** [comment]
![compare](https://user-images.githubusercontent.com/13906248/73833188-d7c2e100-4809-11ea-9104-01ff92469b48.jpg)
Screenshots from nightly 04/02/2020 on OnePlus 5T
