### ISSUE TITLE
Use Inter font for body text

### ISSUE THREAD

**Issue by brampitoyo** [mozilla-mobile/fenix#8089]
In #3687, we proposed using the Metropolis font family for headers, buttons and snackbars. That issue is not yet complete, because we haven’t changed the body text font.

We propose setting all body text font using Inter: https://github.com/rsms/inter/

**Comment by jonalmeida** [comment]
Keeping this offline discussion logged here: 

We want this to land with Fenix UI styled as well as the BrowserToolbar in AC at the same time. For this, we need to make the BrowserToolbar styleable (ac work) and use the font in the Fenix UI (fenix work).

**Comment by amedyne** [comment]
@topotropic @brampitoyo Do we still think that we need to pursue this change? Asking in connection to @topotropic's topic on the last Work Week re carbon footprint.

**Comment by gabrielluong** [comment]
Closing this since I don't believe there's a plan to use Inter.
