### ISSUE TITLE
Ability to keep the last viewed tab "warm" and available even after ten minute session time-out

### ISSUE THREAD

**Issue by Cheap-Skate** [mozilla-mobile/fenix#809]
I'm starting to understand how the Fenix workflow works. Hmmmm.

A request...

IIUC, after ten minutes with Fenix in the background,  my tabs get crunched down into a session and when I next bring Fenix to the foreground I go to its Home screen and can see my crunched-down session.

But quite often I just want to go back to the last page I was viewing. At the moment I have to tap the Session to open it up, tap the tab at the top of the list to go back to that tab. And then _wait while the tab reloads_. This wait can be a pain on a slow phone - it can take many seconds to reload the tab. On a more conventional browser this issue doesn't exist - the browser can be in the background indefinitely and the last used tab still remains open.

Would it be possible for Fenix to hold the last viewed tab fully loaded in memory but hidden even after the ten minute timeout and so when I tap sessions -> last tab it's already loaded and rendered, I don't have the _wait_

i.e. workflow at the moment
- read half of newspaper article in Fenix
- get distracted by e.g. email & leave Fenix in background for a while
- return to Fenix to continue reading
- Session timeout has elapsed! Tabs have been crunched into a Session! Go to Home screen
- tap Session then topmost tab (most recently opened)
- _wait while tab reloads, many seconds_      <----- **inconvenient**
- continue reading newspaper article

If Fenix kept the last viewed tab "open but hidden" the inconvenient italicised wait could disappear, the tab could just automagically re-appear in the state it last was.

**Comment by Cheap-Skate** [comment]
In fact, I think there is a very high probability that when I return to Fenix after using other apps I will want to "pick up where I left off" and go back to my last session & its tabs.

Could you keep all the tabs in just the most recent session "hot" so that I can instantly switch to them without a reload?

I think at the moment Fenix kills the tabs and reclaims the memory after 10 (?) minutes when it crunches my tabs down to a session. Instead why not keep the tabs "hot" in memory and wait to see if I re-open my previous session, or start a new session.

**Comment by buttercookie42** [comment]
Personally, I think I'd very likely prefer to turn session crunching off, too- I definitively turned on session restoring even when it isn't (on Desktop) or wasn't (a while ago on mobile) the default.

Though I guess you might want to initially ship it like that to gather more feedback...

**Comment by buttercookie42** [comment]
Is this still relevant now that session crunching has been turned off?

**Comment by Cheap-Skate** [comment]
No longer relevant to me. Fenix much nicer now crunching is off. Thanks!
