### ISSUE TITLE
Release the Fenix apk file here on GitHub

### ISSUE THREAD

**Issue by USB3-2-10Gbit** [mozilla-mobile/fenix#8090]
Hello thank you for the great app.

When you release a new version. Can you add the apk file under GitHub releases?
https://github.com/mozilla-mobile/fenix/releases

**Comment by kbrosnan** [comment]
Neither are at 100% which is a requirement for posting the builds. You can get them from automation if you want https://firefox-ci-tc.services.mozilla.com/tasks/index/project.mobile.fenix.v2.production/latest
