### ISSUE TITLE
[Bug] uBlock Origin takes a long time loading in Add-ons page

### ISSUE THREAD

**Issue by softvision-miralobontiu** [mozilla-mobile/fenix#8100]
## Steps to reproduce
1. Go to Settings - Add-ons.

### Expected behavior
The Add-ons page opens and displays the uBlock Origin add-on.

### Actual behavior
The Add-ons page opens but is blank for a 3-4 seconds like there is no add-on to be displayed.

### Device information
* Android device: all
* Fenix version: 200205 (#20360607)

![20200205](https://user-images.githubusercontent.com/40694158/73830133-caf3bc80-480c-11ea-8e95-cf2b8777ace7.gif)

**Comment by ekager** [comment]
@brampitoyo should we show some sort of progress bar here while we query for addon information?

**Comment by brampitoyo** [comment]
@ekager I didn’t realise that we query for add-ons information remotely – I had thought it was hardcoded.

In that case: yes. Let’s add the same progress bar as bookmarks, history, etc.

@Amejia481 Thanks for working on this! Can you send screenshot of what it would look like (compared to how it looks like in other pages)?

**Comment by Amejia481** [comment]
Sure!

**Comment by Amejia481** [comment]
@brampitoyo This is how it looks like [video](https://drive.google.com/file/d/1ELE4C0lNq-JN_vXs_xButDnUucs4Ig_E/view?usp=sharing)

**Comment by Amejia481** [comment]
@softvision-miralobontiu the fix is on master, could you re-test please?

**Comment by brampitoyo** [comment]
@Amejia481 It looks good to me!

**Comment by softvision-miralobontiu** [comment]
Verified as fixed on the latest Nightly build from 2/6 with Huawei Honor 8 (Android 7), OnePlus 5T (Android 9), Nexus 5 (Android 6.0.1),  and Google Pixel (Android 10).
Indeed, if the connection is slower, a progress bar is displayed.
