### ISSUE TITLE
[Bug] The same site can be added multiple times to Firefox home

### ISSUE THREAD

**Issue by sflorean** [mozilla-mobile/fenix#8105]
## Steps to reproduce
1. Browse any site(wikipedia.com).
2. Tap on 3dot menu and select "Add to Top Sites".
3. Tap again on the 3dot menu and select "Add to Firefox home".

### Expected behavior
The option is greyed out for the pages that are already added to The Firefox home. 

### Actual behavior
The same page can be added multiple times to the Firefox home. 

### Device information
* Android device: Sony Xperia Z5 Premium (Android 7.1.1), Samsung Note 8 (Android 9.0)
* Fenix version: Firefox Nightly 2/5 #20360607

**Comment by cadeyrn** [comment]
same as #8108.

**Comment by AndiAJ** [comment]
Closing in favor of #8108
