### ISSUE TITLE
[Bug] The same site can be added multiple times to the top sites

### ISSUE THREAD

**Issue by sflorean** [mozilla-mobile/fenix#8108]
Depends on three-dot menu redesign: https://github.com/mozilla-mobile/fenix/issues/17796

## Steps to reproduce
1. Browse any site(wikipedia.com).
2. Tap on 3dot menu and select "Add to Home screen".
3. Tap again on the 3dot menu and select "Add to Home screen".

### Expected behavior
The "add to home screen" item will say "Remove from home screen" if the site has already been added.
~The option is greyed out for the pages that are already added to the home screen /or a message is displayed that the page is already added.~

### Actual behavior
The same page can be added multiple times to the home screen. 

### Device information
* Android device: Sony Xperia Z5 Premium (Android 7.1.1), Samsung Note 8 (Android 9.0)
* Fenix version: Firefox Nightly 2/5 #20360607

**Comment by sflorean** [comment]
Reproducible also for Private browsing shortcut, from settings and from the private browsing pop-up.

**Comment by sv-sdeiac** [comment]
Notes:
- If you have multiple Top Sites from the same page, one of those shortcuts can't be deleted. 
![20200207_170407](https://user-images.githubusercontent.com/40264165/74040368-45b70600-49cc-11ea-8b80-483bf4621cbb.gif)

**Comment by mcarare** [comment]
@topotropic How do we want to handle this? 
Should we not show the option to add or should we notify that it already exists (text on the Snackbar instead of the confirmation one). IMO the last one is more user friendly. TY!

**Comment by brampitoyo** [comment]
@mcarare – @topotropic will make the final decision, but another potential solution would be to rename the menu item to “Remove from Top Sites”.

(Another question: will it be possible to do the same for the home screen, so we have a menu item called “Remove from Home screen”?)

**Comment by mcarare** [comment]
@brampitoyo There already is a "Remove" menu option for a top site, if that is what you are referring to. 
I like your idea with renaming the menu option in the browser! 👍

**Comment by brampitoyo** [comment]
@mcarare Correct. Each top site, when long-pressed, shows a context menu with “Remove” in it. This is replicating the same functionality inside the main menu, when the top site is open.

Instead of removing the list item “Add to top sites”, or greying it out, we can rename it to “Remove from top sites”.

I’ll leave the decision to @topotropic :-)

**Comment by AmyYLee** [comment]
@topotropic to follow-up

**Comment by topotropic** [comment]
Yes, to what Bram said. Thanks!

**Comment by chrishernan** [comment]
Hello. Could I work on this issue please?

**Comment by nick-morhun** [comment]
Hello. Why is this a bug? I tested Chrome, and it does the same thing.

**Comment by Alexandru2909** [comment]
Can I work on this issue?

**Comment by nick-morhun** [comment]
@mcarare @Alexandru2909 Hello. Sorry, I'm not a part of this project or anything, just want to help. I still believe that the report is about the OS Home screen, not the Top Sites inside the browser. So you cannot fix the original issue.

**Comment by gabrielluong** [comment]
> @mcarare @Alexandru2909 Hello. Sorry, I'm not a part of this project or anything, just want to help. I still believe that the report is about the OS Home screen, not the Top Sites inside the browser. So you cannot fix the original issue.

This seems sensible. I opened https://github.com/mozilla-mobile/fenix/issues/23202 to track Home Screen.

**Comment by sflorean** [comment]
Verified as fixed on latest Nightly build (98.0a1) with OnePlus 9(Android 11).
"Remove from top sites" is displayed in Settings, for websites already added to Top Sites.
