### ISSUE TITLE
[Bug] uBlock Origin's icon is crooked

### ISSUE THREAD

**Issue by softvision-miralobontiu** [mozilla-mobile/fenix#8109]
## Steps to reproduce
1. Go to Settings - Add-ons and observe the uBlock Origin's icon.

### Expected behavior
The icon looks good.

### Actual behavior
The icon looks bad. It is "forced" in a grey circle and it doesn't completely fit.

### Device information
* Android device: all
* Fenix version: 2/5 Nightly build

![Untitled](https://user-images.githubusercontent.com/40694158/73846348-10c07d00-482d-11ea-98e4-722e5ae0587a.png)

**Comment by gabrielluong** [comment]
This should be fixed from AC in https://github.com/mozilla-mobile/android-components/pull/5827 to make it conform with the designs.

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly #20380605 from 2/7`** using the following devices:
• Google Pixel 3a XL (Android 10)
• Google Pixel 3a (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7.0.0)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

@gabrielluong - Just a QQ, do you know why the shape of the icon is different from one device to another?
For E.g. on the **Pixel devices the icon is round** whereas on **the other devices it looks "diamond shaped"**.

► Screenshot from Google Pixel 3a (Android 9)
![rsz_screenshot_20200207-153613_1](https://user-images.githubusercontent.com/51314259/74034472-046d2900-49c1-11ea-8890-4a22119be0ea.png)


► Screenshot from OnePlus A3 (Android 6.0.1)
![rsz_screenshot_20200207-153213](https://user-images.githubusercontent.com/51314259/74034277-a17b9200-49c0-11ea-8637-3b113b1c01df.png)
