### ISSUE TITLE
Toolbar styling changes to private style for normal tabs after entering private browsing mode

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/fenix#811]
## Steps to reproduce

1. Open page
2. Tap tab switcher icon
3. Tap Private browsing mask
4. Tap "back" 

### Expected behavior

Toolbar should be white. 

### Actual behavior

Toolbar is purplish. 

### Device information

* Android device: Pixel 2
* Fenix version: 1.0.1909 (Build #10601903 :lizard: 67.0a1-20190227104426)

**Comment by ekager** [comment]
Related to #1012, this is partly because we maintain the entire backstack and partly because we set the theme for the whole app when switching to private browsing

**Comment by sv-ohorvath** [comment]
Still reproducing on Nightly 3/14 build. 
devices: Nexus 5 (Android 6), Samsung S8 (Android 9)

**Comment by callahad** [comment]
Another path that surfaces this bug, while browsing:

* Menu → Private Tab → Back

**Comment by sblatz** [comment]
@vesta0 I believe this should be an "MVP Bug" considering it gives the user an incorrect understanding of whether or not they're in private mode.

**Comment by vesta0** [comment]
UX working on a related bug #1012

**Comment by ekager** [comment]
This is no longer an issue
