### ISSUE TITLE
[Bug] about:networking - Application creates empty log file

### ISSUE THREAD

**Issue by Diana-Rus** [mozilla-mobile/fenix#8110]
Pre-requisites:
- Have the device connected to PC.
- Have the USB debugging option enabled from developer tools for android device.
- Have the Android System Setting option "USB file transfer option" enabled.

## Steps to reproduce
1. Go to "about:networking".
2. Tap on the "Logging" section.
3. Insert the needed modules to set.
4. Insert the path to where the file needs to be saved on the device.
5. Inspect the info from "Current log file" for the generate number of the file.
6. Tap on the "Start logging" button.
7. Make a search after a site.
8. Go back to the about:networking#logging section.
9. Tap on the "Stop logging" button.
10. Check on PC for the generated file at path from Step 4.

### Expected behavior
The file is available at the path from "Set Log File" field and contains data.

### Actual behavior
An empty file is generated at the path from step 4. No information is saved in the log.

### Device information

* Android device: Google Pixel 3 XL (Android 9)
* Fenix version: Firefox Preview Beta 3.2.0-beta.3 (Build #20250043) GV:73.0-20200123180644.

Note:
* File generation configuration:
         - Path: /sdcard/Android/data/org.mozilla.fenix.beta/files/log.txt
         - Modules: sync,timestamp,nsHostResolver:5
* On Firefox Preview Nightly 200204 (Build #20350606) GV: 74.0a1-20200203085242 with the same device the file is generated and contains data.

**Comment by valenting** [comment]
This seems related to https://bugzilla.mozilla.org/show_bug.cgi?id=1263197

**Comment by softvision-miralobontiu** [comment]
@Diana-Rus could you retest on the latest Nightly build?
The [Bugzilla 1263197](https://bugzilla.mozilla.org/show_bug.cgi?id=1263197) bug was fixed.
