### ISSUE TITLE
[Bug]Tapping the Android back button while having as current tab a uBlock link closes the tab

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#8113]
## Prerequisites
Have Fenix set as your default browser.
Don't have any opened tabs.

## Steps to reproduce
1. Tap the 3dot button and open "Settings"
2. From the "Advanced section" tap and open "Add-ons"
3. Tap on the uBlock Origin Add-on
4. Swipe down, tap on one of the listed links
5. Tap the device back buton

### Expected behavior
As per [#6620](https://github.com/mozilla-mobile/fenix/issues/6620#issuecomment-573036239) the current tab **should not be closed,** as it doesn't have a parent tab.

### Actual behavior
The current tab is closed.

### Device information

* Android device: 
• Google Pixel 3a XL (Android 10)
• Google Pixel 3a (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7.0.0)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

* Fenix version: Nightly Build #20360606 from 2/5

### Notes
► Video
![20200205_164825](https://user-images.githubusercontent.com/51314259/73853281-48cdbd00-4839-11ea-8b1c-a3419511f8c9.gif)

**Comment by gabrielluong** [comment]
This isn't actually a bug with WebExtensions, but actually a default Android behaviour. The link in the gif is inside of a TextView so this will perform an ACTION_VIEW on the Intent and open the default browser. This is also reproducible if you share a URL to Fenix from Fennec.

@AndiAJ are we able to close this?

**Comment by AndiAJ** [comment]
Sure thing! ☺️ 
Thx @gabrielluong
