### ISSUE TITLE
[Bug]Purple color for settings background title after opening multiple history tabs

### ISSUE THREAD

**Issue by sv-sdeiac** [mozilla-mobile/fenix#8114]
## Steps to reproduce
1. Go to the History section;
2. Select multiple pages;
3. Tap on 3dot menu;
4. Tap on "Open in new tab";
5. Open the settings from the 3dot menu.

### Expected behavior
No visual defects are displayed

### Actual behavior
The top part of the settings is different colored than the expected

### Device information

Android device
- Nokia 6 (Android 7.1.1);
- Samsung Galaxy Note 8 (Android 9);
- Google Pixel 3 (Android Q).

* Fenix version: Firefox Preview Nightly 2/5 @20360606.
![purple](https://user-images.githubusercontent.com/40264165/73853863-386a1200-483a-11ea-9144-59a105ff2041.png)

**Comment by mcarare** [comment]
Same issue occurs for bookmarks section.

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly Build #200619 from 6/19`** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)

► Video
![20200619-104308](https://user-images.githubusercontent.com/51314259/85111108-8f3a1c00-b21c-11ea-9a19-b89f9a503508.gif)
