### ISSUE TITLE
[Bug]Save the login pop-up is displayed even if you write the wrong password

### ISSUE THREAD

**Issue by sv-sdeiac** [mozilla-mobile/fenix#8115]
## Steps to reproduce
1. Open a page that has login flow(ex. amazon.com);
2. Log in using a valid email and an invalid password.

### Expected behavior
The log-in is not performed and the pop-up to save the login is not displayed.

### Actual behavior
The login is not performed but the pop-up to save the login is displayed.

### Device information

Android device:
- Nokia 6 (Android 7.1.1);
- Samsung Galaxy Note 8 (Android 9);
- Google Pixel (Android Q).

* Fenix version: Firefox Preview Nightly 2/5 #20360606.
![q](https://user-images.githubusercontent.com/40264165/73855649-073f1100-483d-11ea-8f1d-539849c3cf59.png)

**Comment by mnoorenberghe** [comment]
This is expected behaviour (from the Toolkit side) until we fix https://bugzilla.mozilla.org/show_bug.cgi?id=558178 in Toolkit but it's a very hard problem and not a priority. Users can tap outside the prompt when they see the error from the site.

**Comment by ekager** [comment]
Closing as expected behavior
