### ISSUE TITLE
[Bug]uBlock confirmation snackbar isn't displayed is you exit the Add-ons Manager view

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#8116]
## Prerequisites
Don't have any Add-on installed
Have an open tab

## Steps to reproduce
1. From the open tab tap on the ⋮ Main menu button
2. Tap and open the "Add-ons Manager"
3. Install uBlock Origin
4. While the installation and verification is performed tap the Device back button.

### Expected behavior
The "Successfully installed uBlock Origin" should be displayed even if the user exits the "Add-ons Manager" view.

### Actual behavior
No confirmation snackbar is displayed.

### Device information

* Android device: 
• Google Pixel 3a XL (Android 10)
• Google Pixel 3a (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7.0.0)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

* Fenix version:  Nightly Build #20360606 from 2/5

## Notes
► Video
![20200205-172049](https://user-images.githubusercontent.com/51314259/73856178-baa80580-483d-11ea-98ec-64e086b0cfda.gif)

**Comment by psymoon** [comment]
@AndiAJ no confirmation snackbar displayed when you press back during the installation is an expected behaviour.

What's fixed and can be confirmed, however, is once the confirmation Snackbar is displayed, pressing back should not dismiss the snackbar.

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly Build #20620607 from 03/02`** using the following devices:
• Google Pixel 3a (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

► Video
![20200302-095818](https://user-images.githubusercontent.com/51314259/75656825-81f92180-5c6d-11ea-9f6d-f1421ecf683d.gif)
