### ISSUE TITLE
[Bug] Switching tabs prompts to save password each time

### ISSUE THREAD

**Issue by moztcampbell** [mozilla-mobile/fenix#8121]
## Steps to reproduce
- Visit https://pto.mozilla.org/ and log in as moz staff.
- When prompted to save password, select "Don't Save"
- Create a new tab (eg for a google search)
- Switch back to the PTO tab

### Expected behavior
- Return to the tab as it was left

### Actual behavior
- Returns to tab, but password prompt appears again.

### Device information

* Android device: Pixel 3 (Android 10)
* Fenix version: Firefox Nightly 20200203085242

**Comment by mTwTm** [comment]
Still reproducable on Nightly 20021606:01 on my Android 9 SH-Z10

**Comment by marthinwurer** [comment]
Also happening on 4.2.1 (Build #20941431) on my Andriod 9 S8

**Comment by ekager** [comment]
Should be fixed by https://github.com/mozilla-mobile/android-components/pull/6586

**Comment by ekager** [comment]
mozilla-mobile/android-components#6586 has landed and this can be tested after the next AC nightly update

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly Build #21060608 from 4/15`** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)

► Video
![20200415-173123](https://user-images.githubusercontent.com/51314259/79349803-5b522a00-7f3f-11ea-8377-c3d14a120404.gif)
