### ISSUE TITLE
[Bug] Latest Firefox Preview causes Android system reboot

### ISSUE THREAD

**Issue by acidrums4** [mozilla-mobile/fenix#8123]
## Steps to reproduce

Install Firefox Preview (stable/nightly) from Google's Play Store and open it, or set Preview as the default web browser and open any web link from another app.

### Expected behavior

Firefox Preview opens and displays web pages as it's supposed to do.

### Actual behavior

Preview tries to open (there's just a blank screen, no UI is shown) and after some seconds crashes and makes the phone to reboot. If you have Preview installed (but don't open it) but open Gmail app instead, it makes the phone to freeze and reboot. If you uninstall it, Gmail works without issues.

### Device information

* Android device: Sony Xperia Z1 (6903), Android 9 (Unofficial LineageOS 16.0.20200101)
* Fenix version: Nightly 200205 06:00 (updated 4 feb 2020)

I can't get any info from about:crashes, since the browser doesn't stay open.
This occurred directly after I updated my app to the latest version in the Play Store, and did not happen beforehand. I have tried deleting and re-installing Focus, and clearing data and cache.

I just copied/adapted this from [this invalid bug report](https://github.com/mozilla-mobile/fenix/issues/6135) which was intended for Focus, but the same thing is happening for Nightly since a few months - I tried Preview stable and nightly, and Focus, and all of them made my phone to reboot while trying to open them.

Guess is something related to LineageOS, I guess a critical crash wouldn't make it to a stable release and the aforementioned report lists LineageOS too, but my near-to-null technical Android knowledge doesn't make me have a word on that.

**Comment by csadilek** [comment]
This seems to be the same problem with LineageOS described here: https://github.com/mozilla-mobile/fenix/issues/5663

**Comment by acidrums4** [comment]
> This seems to be the same problem with LineageOS described here: #5663

You're absolutely right, thank you. Closing and sorry for the noise.
