### ISSUE TITLE
Back button just reloads page after closing/reloading app

### ISSUE THREAD

**Issue by kit299** [mozilla-mobile/fenix#8124]
I'm sure this happens in other situations as well, but these were the reliable repro steps for me:

1. Open Firefox Preview and go to a website, e.g.: en.wikipedia.org
2. Click a link, e.g. today's featured article "mosaics of Delos" (I doubt it matters what link)
3. After the page loads, press the Android "Recents" button and swipe away Firefox Preview.
4. Press "Home" (to get rid of the "Recents" view)
5. Open Firefox Preview to see list of open tabs (i.e. the page we opened earlier)
6. Click the tab to open the tab and view the webpage.
7. Press Android "Back" button.
8. Expected result: Navigates back (e.g. to Wikipedia Main Page)
9. Actual result: Page just reloads.

At this point, pressing Android "Back" a second time will actually take you back as expected.

Using Firefox Preview Build #20360607 f42641b48 from today on Android Q (Samsung device)

**Comment by ekager** [comment]
@kit299 I can't reproduce. Can you still?

**Comment by kit299** [comment]
No, I've retested using build #21610607 8ec16f840 from today and the issue is no longer present.

**Comment by ekager** [comment]
Thanks!
