### ISSUE TITLE
[Telemetry] Default top sites

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/fenix#8125]
#### Description & Product Manager / Data Scientist User Story
- As a product owner, I want to know if users find default top sites useful.

#### What questions will you answer with this data?
- How often users interact with default top sites?
- How often users tap on pocket stories? 

#### What probes (suggested, if applicable)
- User taps on any default top site (not tracking URLs)
- User taps on pocket stories icon

### Acceptance Criteria (Added by PM)
- Event pings can be queried via re:dash
- We are sending telemetry events for the actions listed in the requirements
- We have documented the telemetry
- We have asked a data steward to [review](https://github.com/mozilla/data-review/blob/master/request.md) the telemetry
- NOT an AC: Data science to create dashboard or further graphs (this will be a separate issue, this issue is only about hooking up the events described and that they can be queried in re-dash)

**Comment by ecsmyth** [comment]
The performance team would like request that the probes for add/remove a top site include an extra key with the number of top sites that users have.

**Comment by vesta0** [comment]
@ecsmyth I assume you are looking to see if there is correlation between page load speed and total number of top sites?

**Comment by ekager** [comment]
And @ecsmyth I'm assuming this is for any top site (not just the defaults)

**Comment by ecsmyth** [comment]
@vesta0 we've seen a correlation between startup time and the number of top sites in local testing. We're working on a possible fix for 4.0, however, knowing quantities will better inform both technical and UX-based solutions.

@ekager, yes, for any top site.

**Comment by gabrielluong** [comment]
I am wondering if we should do a metrics ping instead of adding the extra key to the existing add/remove top sites. Metrics ping would send a ping once a day and can report the number of top sites for an user.

**Comment by ecsmyth** [comment]
@gabrielluong, nod. That would make time-series analysis easier.

**Comment by liuche** [comment]
@ekager if you have time this week or next, could you wrap this up? This sounds like something that has been on the perf team's radar for a while.

**Comment by ekager** [comment]
Yep for the non defaults I can add what @ecsmyth was describing. For the defaults @gabrielluong and I are working on https://github.com/mozilla-mobile/fenix/issues/9286 which will make default telemetry much easier.

**Comment by vesta0** [comment]
Is this still in progress?

**Comment by ekager** [comment]
Yes. Waiting for https://github.com/mozilla-mobile/fenix/issues/9286 to add remaining default top site telemetry.

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly Build 200529 from 5/29`** using a Google Pixel 3a (Android 10)

#### Open the top sites
✔️ Youtube - Ping **a6e51160-7b69-465b-be3c-aa874006b10e**
```kotlin
      "events": [
        {
          "category": "top_sites",
          "name": "open_in_new_tab",
          "timestamp": 0
        },
        {
          "category": "top_sites",
          "name": "open_default",
          "timestamp": 1
        }
      ]
```

✔️ Wikipedia - Ping 3**92dc64b-731e-48ae-af70-e02136613b1e**
```kotlin
"events": [
        {
          "category": "top_sites",
          "name": "open_in_new_tab",
          "timestamp": 0
        },
        {
          "category": "top_sites",
          "name": "open_default",
          "timestamp": 0
        }
      ]
```

✔️ Pocket - Ping **da6c404e-ccae-4888-92eb-9ebe9394d723**

 "events": [
        {
          "category": "top_sites",
          "name": "open_in_new_tab",
          "timestamp": 0
        },
        {
          "category": "top_sites",
          "name": "open_default",
          "timestamp": 0
        },
        {
          "category": "pocket",
          "name": "pocket_top_site_clicked",
          "timestamp": 1
        }

####  Remove 2 out of the 3 default top sites
✔️Wikipedia & Pocket - Ping **ccfc3415-aebe-4739-8b4d-d02415b059b6**

```kotlin
"events": [
        {
          "category": "top_sites",
          "name": "remove",
          "timestamp": 0
        },
        {
          "category": "pocket",
          "name": "pocket_top_site_removed",
          "timestamp": 2
        },
        {
          "category": "top_sites",
          "name": "remove",
          "timestamp": 5103
        }
```

#### Metrics ping 
✔️ Number of top sites that users have. - Ping **f5ee135b-7792-4426-8033-25b5aea9a4a1**
```kotlin
"metrics.top_sites_count": 1
```

[Log](https://github.com/mozilla-mobile/fenix/files/4700536/defaultop.txt)
[Glean dashboard](https://debug-ping-preview.firebaseapp.com/pings/aj-t290500)
