### ISSUE TITLE
Default Top Sites

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/fenix#8126]
## User Story
- As a user, I want to see a short-list of Top Sites so I can explore the web and trending stories.

### Acceptance Criteria
- I can tap on a default top site. There will be 3 default top sites per locale based on the alexa 500 list (excluding social media (for now), search engines, web portals, and adult categories)
- I see an icon for Pocket Top Articles (EN locale only) that goes to https://getpocket.com/fenix-top-articles

Note: Default top sites can be removed the same way as pinned sites. Since removing a top site is a deliberate action, we won't add a separate clear/restore default settings toggle for default top sites for this initial iteration, and wait until we have feedback from users.

Parent: [Meta] Top Sites #6190

**Comment by ekager** [comment]
QA:
Default Top Sites should be Wikipedia and YouTube for all locales, additionally all English locales should also get the Pocket "Top Articles" Top Site
Thank you!!

**Comment by Diana-Rus** [comment]
Hi, the following scenarios have been checked:
✔️ Top sites (Pocket, Wikipedia, YouTube) are by default displayed and can be tapped
✔️ Default top sites can be opened in private mode
✔️ Default top sites can be removed
✔️ Link to Pocket is redirecting the user to "Trending on Pocket" articles (URL: https://getpocket.com/explore/trending?src=ff_android&cdn=0)
✔️ Default top sites can be added to collection
❌ Pocket Top Articles (EN locale only) - bug created #8480 
✔️ Click on Pocket top site - Ping 3ec85d8b-88b4-4039-82d4-8cfbe8e59622 
✔️ Delete Pocket top site - Ping a59d46f4-06d0-4c99-b104-1e77725db1f1
[Glean dashboard]https://debug-ping-preview.firebaseapp.com/pings/DR-TopSites

Devices:
- Samsung Galaxy Note9 (Android 9)
- Samsung Galaxy S8+ (Android 8.0.0)
- Sony Xperia Z5 (Android 7.0.0)
- One Plus A3000 (Android 6.0.1)

Build ID: Firefox Preview Nightly 200218 (Build #20490607) GV: 75.0a1-20200217095003
[8126-Pocket List-Clicked&Deleted actions.txt](https://github.com/mozilla-mobile/fenix/files/4219748/8126-Pocket.List-Clicked.Deleted.actions.txt)
