### ISSUE TITLE
[Bug] Unable to interact with the browser toolbar while 'Add to Firefox Home' SnackBar is visible

### ISSUE THREAD

**Issue by AaronMT** [mozilla-mobile/fenix#8128]
Ran into this while writing a UI test for Top Sites. 

While the SnackBar is visible that shows `snackbar_added_to_firefox_home` is visible, one is unable to interact with the Browser Toolbar while it is visible. I tested this with other SnackBar usage and am able to interact with the Browser Toolbar while they are present (e.g, Undo and Copy Link). Not sure what's special about this SnackBar (https://github.com/mozilla-mobile/fenix/blob/64a4a7f422b692c77fdd7957b7b80357ff02b348/app/src/main/java/org/mozilla/fenix/components/toolbar/BrowserToolbarController.kt#L153).

You can reproduce this by:

-> mozilla.org
-> menu -> 'Add to Firefox home'
-> Attempt to tap the tab count box or the address bar (while the SnackBar is visible)

**Comment by AaronMT** [comment]
Thanks! WFM.

**Comment by abodea** [comment]
Verified as fixed using the latest **Nightly build from 2/7** with the following devices: 
**• Google Pixel 3a XL (Android 10)
• Google Pixel 3a (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7.0.0)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)**
Note that I was able to access the browser toolbar every time and it works correctly now.
Based on my comment I will close this issue.
