### ISSUE TITLE
Discuss unassigned features on MVP board

### ISSUE THREAD

**Issue by bbinto** [mozilla-mobile/fenix#813]
https://github.com/orgs/mozilla-mobile/projects/5#card-16782575

* "Web Extension Support" - this is the A-C project to allow web extensions to be used. It is the foundation for those Epics that we think we need WE for, like Reader Mode, Ad Blocking and Website Icons.

 * "Website Icons" - this is a rather large A-C project to get support for website icons. Aka Favicons. (This could be a should if we decide to show simple placeholders instead of icons in MVP)

**Comment by vesta0** [comment]
Discussed and moved out of MVP.
