### ISSUE TITLE
As a user, when I choose to restore an old session, the home screen should snap up top after chosen

### ISSUE THREAD

**Issue by Sdaswani** [mozilla-mobile/fenix#814]
This is actually a feature request.
Check out the video https://photos.app.goo.gl/hjeQdqR7Rf5p1TbU6

It would be great that after I choose a older session, the home screen snaps up to the recently restored session. You can see in my video that I'm just confused whether my sessions was restored or not.

* Android device: Galaxy S8
* Fenix version: This weekend's :)

**Comment by sv-ohorvath** [comment]
Verified the changes made and logged #939 as a follow-up.
