### ISSUE TITLE
[Bug]uBlock settings freeze after tapping the "Reset to default settings" button

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#8143]
## Prerequisites
Have uBlock Origin installed.

## Steps to reproduce
1. From the Add-ons manager tap on uBlock Origins
2. Tap and open "Settings"
3. Swipe down Settings section tap the  "Reset to default settings" button

### Expected behavior
A confirmation prompt asking the user to confirm the reset of Ublock to factory settings should be displayed.
After the user confirms the reset, he should be able to access the other Settings sections (e.g. "File lists, "My filters" etc.)  

### Actual behavior
After tapping the button you can't access the other Settings sections (e.g. "File lists, "My filters" etc.)  

### Device information

* Android device: 
• Google Pixel 3a XL (Android 10)
• Google Pixel 3a (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7.0.0)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

* Fenix version: Nightly #20370604 from 2/6

### Notes
<details>
    <summary>Video comparison between Fennec VS Fenix (dropdown)</summary>

► Fenix
![20200206-095821](https://user-images.githubusercontent.com/51314259/73918725-d4dbf500-48ca-11ea-8675-d07741be1f68.gif)

►Fennec
![20200206_095550](https://user-images.githubusercontent.com/51314259/73918671-b70e9000-48ca-11ea-95cf-5b5cfa198ff8.gif)

</details>

**Comment by csadilek** [comment]
Removing needs:gv for now. The first step here is displaying a prompt triggered by `window.confirm`. The popup fragment needs to use our prompt feature to provide this functionality.

**Comment by csadilek** [comment]
@AndiAJ We landed a fix for this, can you verify, please? You should now see the confirmation dialog.

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly Build # 20450607 from 2/14`** using the following devices:
• Google Pixel XL (Android 10)
• Google Pixel 3a (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7.0)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

► Video
![20200214-163557](https://user-images.githubusercontent.com/51314259/74542690-b7eb9580-4f4c-11ea-9de6-02616c355839.gif)
