### ISSUE TITLE
[Bug]uBlock ON/OFF button flicker

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#8145]
## Prerequisites
1. uBlock Origin Add-on installed.
2. Have a tab opened.
3. Disable uBlock for that particular website. 

## Steps to reproduce
1. Tap the nav bar's  ⋮ menu button
2. Tap uBlock origin (off) 
3. Check the ON/OFF sign

### Expected behavior
No UI issues, the button should be grayed out.

### Actual behavior
For a couple of seconds the button flickers.

### Device information

* Android device: 
• Google Pixel 3a XL (Android 10)
• Google Pixel 3a (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7.0.0)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

* Fenix version: Nightly #20370604 from 2/6

### Notes

►Video
![20200206-114055](https://user-images.githubusercontent.com/51314259/73926132-d364f980-48d7-11ea-9ae7-24d3026a274f.gif)

**Comment by csadilek** [comment]
@AndiAJ I don't think this is actionable by us. We have the same behaviour in Fennec, assuming you mean the button going from blue to gray when the page loads. It may be possible to improve this in the add-on itself...

**Comment by csadilek** [comment]
This would also need to be addressed in the add-on itself //cc @brampitoyo @kewisch

**Comment by csadilek** [comment]
I am closing after discussion with @softvision-miralobontiu as this needs to be improved by the add-on developer (Fennec has the same behaviour).
