### ISSUE TITLE
[Bug] Make ETP options from onboarding screen selectable

### ISSUE THREAD

**Issue by sv-sdeiac** [mozilla-mobile/fenix#8146]
### Prerequisites
Make sure that you have a fresh install.

## Steps to reproduce
1. Go to the "Protect yourself" card;
2. Tap on the Strict/Standard text.

### Expected behavior
The Strict/Standard option is selected when tapping on the text

### Actual behavior
The Strict/Standard option is not selected when tapping the text, only using the radio buttons.

### Device information
Android device:
- Nokia 6 (Android 7.1.1);
- Samsung Galaxy S8 (Android 9);
- Google Pixel 3 (Android Q).

* Fenix version: Firefox Preview Nightly 2/6 #20370604.
![20200206_120710](https://user-images.githubusercontent.com/40264165/73927139-7f5b1480-48d9-11ea-81d6-f7eee04e4b42.gif)

**Comment by abodea** [comment]
Verified as fixed using the latest **Nightly from 2/7** with **Samsung Galaxy S10+(Android 9).**
Note that when tapping on the ETP options strict/standard text everything it's working as expected and the option is selected.
Based on my comment I will close this issue.
