### ISSUE TITLE
Session Doesn't Always Restore

### ISSUE THREAD

**Issue by Sdaswani** [mozilla-mobile/fenix#815]
## Steps to reproduce
See this video https://photos.app.goo.gl/hjeQdqR7Rf5p1TbU6

As you can see I'm often clicking a session but when I scroll back up it hasn't restored. Generally I've seen a lot of lag trying to restore sessions, usually on cold start. Maybe some DB work needs to be done?

### Expected behavior
Session restores upon click

### Actual behavior
Session doesn't restore

### Device information

* Android device: Galaxy S8
* Fenix version: This weekend's

**Comment by Sdaswani** [comment]
This video shows it more succintly https://photos.app.goo.gl/TxHn1qNnW1gKaBsSA

**Comment by sv-ohorvath** [comment]
I was able to reproduce this on a Galaxy s8 (Android 9). Saved 2-3 sessions, tapped any of them and it wouldn't open until a few seconds later. Can't reproduce on huawei P20 lite (Android 8) or Nexus 5 (Android 6).
