### ISSUE TITLE
[Bug]Crash after tapping “Add-ons” while not being connected to the Internet 

### ISSUE THREAD

**Issue by acornestean** [mozilla-mobile/fenix#8150]
##Prerequisites
- uBlock Origin is not installed in Fenix.
- The mobile device is not connected to the Internet (wi-fi is turned off)
## Steps to reproduce
1. Launch Fenix
2. Tap the three-dot menu
3. From the menu select “Settings”
4. Scroll down and tap on “Add-ons”
5. Observe that the browser crashes
### Expected behavior
Users should be able to access the Add-ons listing page even when the device is not connected to the internet.
### Actual behavior
The browser crashes when tapping on “Add-ons”.
### Device information
* Samsung Galaxy S7 (Android 8.0.0)
* Samsung Galaxy S7 Edge (Android 8.0.0)

* Fenix version: #20370605 02/06/2020

### Notes
Very high chance of reproducibility. Only several attempts did not cause the browser to crash.

### Archived video of the issue
[Browser crash tapping Add-ons no wifi.zip](https://github.com/mozilla-mobile/fenix/files/4165207/Browser.crash.tapping.Add-ons.no.wifi.zip)

**Comment by ekager** [comment]
@brampitoyo similar to #8100 since we are querying for these addons we should probably have some empty / can't fetch add-ons state in this case?

**Comment by Amejia481** [comment]
> @brampitoyo similar to #8100 since we are querying for these addons we should probably have some empty / can't fetch add-ons state in this case?

@ekager I added something for it yesterday :)
https://github.com/mozilla-mobile/fenix/blob/f5715df10476523b8ee1de0ec4d0ff0b2c3887b9/app/src/main/java/org/mozilla/fenix/addons/AddonsManagementFragment.kt#L90

![Screenshot_20200206-095912](https://user-images.githubusercontent.com/773158/73948926-a14b9b80-48c7-11ea-8a01-efdb1bab3d00.png)


![Screenshot_20200206-095518](https://user-images.githubusercontent.com/773158/73948590-2d10f800-48c7-11ea-86c7-3daed9ff57e3.png)

**Comment by ekager** [comment]
Oh nice! So we can close this

**Comment by Amejia481** [comment]
I think the crash is been caused by trying to fetch the icon while getting offline, my yesterday patch just address the case when we are not able to fetch the add-ons but I believe is related to fetching the icon.

**Comment by Amejia481** [comment]
@acornestean  this should be fixed by now, would you mind re-testing?

**Comment by acornestean** [comment]
Verified the fix on the latest build #20410606 from 02/10/2020 on Samsung Galaxy S7 (Android 8.0.0), Samsung Galaxy S7 Edge (Android 8.0.0) and Nexus 9 (Android 7.1.1).

With uBlock not installed and the devices not connected to the internet, the browser no longer crashes when accessing the add-ons manager.

**Comment by brampitoyo** [comment]
@Amejia481 Just a small tweak to this page.

Assuming that users will only see this error message after seeing the progress circle:

1. We don’t need to show a snackbar. The progress circle already indicated a process completing.
2. Change the copy on the page to point users toward a solution: “Connect to the internet to get add-ons”
