### ISSUE TITLE
[Bug] The dashboard requested in private mode, opens in normal mode

### ISSUE THREAD

**Issue by softvision-miralobontiu** [mozilla-mobile/fenix#8153]
## Prerequisites
Make sure uBlock Origin is installed.

## Steps to reproduce
1. Open a page in private mode.
2. Tap on the three-dot menu.
3. On the uBlock Origin custom tab, tap on the "Open the dashboard" button:
![ublok](https://user-images.githubusercontent.com/40694158/73941850-a6740f00-48f6-11ea-852c-f7f687f9b57e.png)

### Expected behavior
The new "Dashboard" tab opens in private mode.

### Actual behavior
The new "Dashboard" page opens in normal mode.

### Device information
* Android device: all
* Fenix version: 2/6 Nightly buiild

![20200206_Trim](https://user-images.githubusercontent.com/40694158/73941421-eab2df80-48f5-11ea-9765-c9b246e2d4b4.gif)

**Comment by psymoon** [comment]
@softvision-miralobontiu The fix has landed, can you please verify?

**Comment by softvision-miralobontiu** [comment]
Verified as fixed on the latest Nightly build from 2/13 (#20440605) with Sony Xperia Z2 (Android 6.0.1), and Samsung Galaxy Note 8 (Android 9).
