### ISSUE TITLE
[Bug] No search option on highlighted text

### ISSUE THREAD

**Issue by fiorenza2** [mozilla-mobile/fenix#8154]
## Steps to reproduce
* Highlight text on page
* Menu pops up, offering to `Copy`, `Select All` or `Translate`
### Expected behavior
* There should be the option to `Search` (i.e., with the default search engine)
### Actual behavior
* No option shown for `Search`
### Device information
* Android device: Pixel XL on Android 10
* Fenix version: 3.2.1

**Comment by ekager** [comment]
Currently being worked on and tracked by #5695
