### ISSUE TITLE
[Bug] uBlock Origin settings in Nightly cannot save or restore settings

### ISSUE THREAD

**Issue by jgoguen** [mozilla-mobile/fenix#8155]
## Steps to reproduce
- Install Firefox Nightly Preview and uBlock Origin as an add-on
- Open uBlock Origin settings
- Click "Back up to file"
- Click "Restore from file..."

### Expected behavior
- "Back up to file" downloads a file with current settings
- "Restore from file" allows selecting a file to "upload" to the extension

### Actual behavior
Neither button does anything. Some searching suggests this may be related to removing local file access in #4049.

### Device information
* Android device: Pixel 3 and Pixel 4, Android 10
* Fenix version: Nightly 200206 06:01

**Comment by 3j9fkyahunqoxwqu** [comment]
I tested again with latest nightly version and it crashes after importing and choosing file. 

And after going again to ublock settings, non of config file imported.

**Comment by csadilek** [comment]
Filed in GV: https://bugzilla.mozilla.org/show_bug.cgi?id=1618349

**Comment by Offerel** [comment]
It seems that this bug is also present in the final Firefox Preview in Google Play Store. Are there any timeline, when this will be fixed?

**Comment by csadilek** [comment]
Restore should work now in latest Fenix Nightly (200318 06:01). "Back up to file" / Save is blocked on https://github.com/mozilla-mobile/android-components/issues/6314.

**Comment by jgoguen** [comment]
Confirmed restore working in Fenix Nightly 200318 18:01.

**Comment by csadilek** [comment]
"Back up to file" is now also working in latest Nightly (200408 06:01). @jgoguen thanks for filing! Please re-open if this still doesn't work for you.
