### ISSUE TITLE
Display addons menu via about:addons

### ISSUE THREAD

**Issue by Dunexus** [mozilla-mobile/fenix#8157]
### Why/User Benefit/User Problem
Most Fenix users are Firefox desktop users too and are used to about:xxx pages, in this case about:addons.

### What/Requirements
Display the addons menu when going to `about:addons`.

### Acceptance Criteria (how do I know when I’m done?)
* Enter `about:addons` as url
* The addons menu is visible

**Comment by softvision-miralobontiu** [comment]
Hi all,
Entering about:addons in the URL bar opens the Addons page.
Tested on the latest Nightly build from 8/31 with Samsung Galaxy Tab s6 (Android 9), Google Pixel (Android 10), and Sony Xperia Z5 Premium (Android 7.1.1).
