### ISSUE TITLE
[Bug]Enable/disable uBlock button flicker

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#8158]
## Prerequisites
Have uBlock Origin installed.
uBlock Origin should be disabled globally.

## Steps to reproduce
1. Open the "Add-on manager"
2. Tap and open uBlock Origin
3. Check the enable disable button

### Expected behavior
No UI issues, having uBlock disabled the button should remain grayed out.

### Actual behavior
For a couple of seconds the button flickers. 

### Device information

* Android device: 
• Google Pixel 3a XL (Android 10)
• Google Pixel 3a (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7.0.0)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

* Fenix version: Nightly #20370604 from 2/6

### Notes
► Video
![20200206-160344](https://user-images.githubusercontent.com/51314259/73944876-00c39e80-48fc-11ea-9e43-1f1ee17aca83.gif)

Related to #6124

**Comment by csadilek** [comment]
@AndiAJ this should be fixed now. :)

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly #20380605 from 2/7`** using the following devices:
• Google Pixel 3a XL (Android 10)
• Google Pixel 3a (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7.0.0)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

► Video
![20200207-113740](https://user-images.githubusercontent.com/51314259/74018670-f9090600-499e-11ea-9132-59530ae1a833.gif)
