### ISSUE TITLE
Three dot menu not expanding, and then session disappears

### ISSUE THREAD

**Issue by Sdaswani** [mozilla-mobile/fenix#816]
## Steps to reproduce
See this video https://photos.app.goo.gl/4C3mYD1FwUcEv1U27

### Expected behavior
Three dot menu works, and session doesn't go bye bye after trying to open a new page.

### Actual behavior
First, the three dot menu isn't expanding. Second, when I try to open a new URL, the whole session has gone bye bye.

### Device information

* Android device: Galaxy S8
* Fenix version: This weekend's

**Comment by ekager** [comment]
Fixed in master
