### ISSUE TITLE
[Bug] Cannot install uBlock Origin from addons.mozilla.org

### ISSUE THREAD

**Issue by softvision-miralobontiu** [mozilla-mobile/fenix#8160]
## Steps to reproduce
1. Open Fenix and go to https://addons.mozilla.org.
2. Search for uBlock Origin add-on and try to install it.

### Expected behavior
The uBlock Origin can be installed.

### Actual behavior
The "+Add to Firefox" is disabled and the "This add-on is not compatible with Firefox for Android." banner is displayed.

### Device information
* Android device: all
* Fenix version: 2/6 Nightly (#20370605)

![Screenshot_20200206-164843](https://user-images.githubusercontent.com/40694158/73947979-0079d200-4901-11ea-8e18-a049c784f173.jpg)

**Comment by csadilek** [comment]
@softvision-miralobontiu This was intentional and a product decision to start with a curated set of add-ons via the native UI only. So, we deactivated this for now.

**Comment by softvision-miralobontiu** [comment]
@csadilek should I close this? Or label it as a feature request?

**Comment by csadilek** [comment]
@softvision-miralobontiu I think we can close, afaik, current plan is to keep using the native UI for the foreseeable future.

**Comment by csadilek** [comment]
@softvision-miralobontiu verified with @vesta0, closing :).
