### ISSUE TITLE
Create shortcuts.xml override for fennecBeta build type

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/fenix#8162]
Like https://github.com/mozilla-mobile/fenix/issues/7587 for Nightly.

We are overriding shortcuts.xml in different build types because it contains the package name. We need to do the same for the `fennecBeta` flavor.

**Comment by ebalazs-sv** [comment]
I had tested this on Fennec Beta migration build 02/19 with LG g7 fit (Android 8.1), the "New tab" and "New private tab" options are available when long pressing the Fenix icon. These can also be added to the home screen.
I will leave this on Ready for QA until we will test it on the official Beta Migration build.

**Comment by ebalazs-sv** [comment]
Verified as fixed on Fennec Beta Migration Build 1, 02/24 with LG G7 fit (Android 8.1), Google Pixel 2 (Android 9). I will move this to Done. Thanks.
