### ISSUE TITLE
[Bug] Desktop specific controls displayed in uBlock Origin menu

### ISSUE THREAD

**Issue by acornestean** [mozilla-mobile/fenix#8166]
## Prerequisites
uBlock Origin is installed and enabled in Fenix.
## Steps to reproduce
1. Access any webpage
2. Tap on the three-dot menu
3. Scroll to the top of the menu list and tap on the uBlock Origin icon
4. Notice that a menu page will open
5. Tap on the following buttons: On/Off button at the top; block popups button, block large media elements button, cosmetic filtering button, remote fonts button, JavaScript button from the bottom
6. Notice that for each tapped button a label is displayed
7. Observe that the labels contain desktop specific controls such as: “Click” and “Ctrl+Click”
### Expected behavior
Platform specific terms should be implemented, mainly tap.
### Actual behavior
Desktop specific controls are used in the mentioned labels.
### Device information
* Samsung Galaxy S7 (Android 8.0.0)
* Samsung Galaxy S7 Edge (Android 8.0.0)

* Fenix version: #20370605 02/06/2020

![desktop specific controls referenced in labels](https://user-images.githubusercontent.com/50236075/73952786-1343d500-4908-11ea-91a0-8056186bc688.jpg)

**Comment by csadilek** [comment]
Same in Fennec. This can only be addressed in the add-on itself. //cc @brampitoyo @kewisch

**Comment by csadilek** [comment]
I am closing after discussion with @softvision-miralobontiu as this needs to be improved by the add-on developer (Fennec has the same behaviour).
