### ISSUE TITLE
[Bug]The uBlock add-on can be installed multiple times

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#8167]
## Steps to reproduce
1. Navigate to the Add-on manager
2. Tap the '+' (Add button) and confirm the addition
3. While uBlock is downloaded and verified tap again the  '+' (Add button) and **`confirm`** the addition 
4. While uBlock is downloaded and verified tap again the  '+' (Add button) and **`confirm`** the addition
5. While uBlock is downloaded and verified tap again the  '+' (Add button) and **`confirm`** the addition
6. While uBlock is downloaded and verified tap again the  '+' (Add button) and **`cancel`** the addition
7. While uBlock is downloaded and verified tap again the  '+' (Add button) and **`confirm`** the addition
8. While uBlock is downloaded and verified tap again the  '+' (Add button) and **`confirm`** the addition
9. While uBlock is downloaded and verified tap again the  '+' (Add button) and **`cancel`**  the addition

### Expected behavior
The  '+' (Add button) should not be displayed while the Add-on is being installed and verified.

### Actual behavior
The user can launch the installation process several times.
Or even cancel in between the whole process resulting in failure (based on the confirmation snackbar)

### Device information

* Android device: 

• Google Pixel 3a XL (Android 10)
• Google Pixel 3a (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7.0.0)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

* Fenix version: Nightly #20370604 from 2/6

### Notes
► Video
![20200209_185509](https://user-images.githubusercontent.com/51314259/73952493-a4ff1280-4907-11ea-9a12-e71224dd0bfa.gif)

**Comment by AndiAJ** [comment]
Hi, this is **still reproducible** on the latest **`Nightly #20380605 from 2/7`** using the following devices:
• Google Pixel 3a XL (Android 10)
• Google Pixel 3a (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7.0.0)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

► Video
![20200207-152205](https://user-images.githubusercontent.com/51314259/74033107-1ef1d300-49be-11ea-9fe1-05f1f86eb03c.gif)

@gabrielluong - Please review. ☺️ 
**I'll remove the QA needed label and reopen the issue.**

**Comment by Amejia481** [comment]
@AndiAJ  @gabrielluong  put a patch for it, would you mind retesting? :)

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest `**Nightly #20410606 from 2/10**`using the following devices:
• Google Pixel 3a XL (Android 10)
• Google Pixel 3a (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Sony Xperia Z5 (Android 7.0.0)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

►Video
![20200210-122711](https://user-images.githubusercontent.com/51314259/74142755-35886c00-4c02-11ea-8299-85ff2857e61d.gif)
