### ISSUE TITLE
Create a Fenix Leanplum Attribute that tells us the app is Fenix

### ISSUE THREAD

**Issue by st3fan** [mozilla-mobile/fenix#8172]
### Why/User Benefit/User Problem

Because of the application migration, the application could be Fennec or Fenix. This is a request to add a simple `Fenix` attribute to Leanplum that will tell us that the app is Fenix.

### What/Requirements

A leanplum attribute `Fenix` that is always set to `true`.

**Comment by cbonacuse** [comment]
For additional context, adding the attribute will allow us in Leanplum to create an "event" which we can then track as a  "conversion event" for a campaign. i.e. when we roll out Fenix to the Android release app, we will want to know how many users we were able to convert to the Fenix version of the app and we cannot do this by simply filtering on app version.

By having the attribute of 'Fenix' set to 'true', we will set up a Leanplum event (i.e. E_Updated_To_Fenix) that will be triggered in a users profile and we can track conversions in a campaign.

**Comment by lwa-moz** [comment]
@st3fan after speaking with @cbonacuse, it sounds like the Marketing team will also need a Leanplum event that corresponds to a user updating from Fennec to Fenix.

"Events" are used by the Marketing team as a means of determining campaign success. In this instance, that they have successfully encouraged a user to update to Fenix.

Additionally, events can be used to trigger additional campaigns, for instance an onboarding message sent to users after they update to Fenix.

Unfortunately, attributes cannot be used in this way. We will therefore need to create an event that fires when a user updates from Fennec to Fenix. Perhaps this event could be instrumented at the conclusion of the data migration flow?

**Comment by AndiAJ** [comment]
Hi, **verified as fixed**.

✔️ Fenix Nightly - Fenix Leanplum Attribute set to TRUE (Device ID **5152fa49-fbd5-43ac-8f45-9c7cecf4bf9a** )
![FenixNight](https://user-images.githubusercontent.com/51314259/74852136-dda9dd80-5344-11ea-9d8c-d714a3dc852f.png)

✔️ Fenix Beta  v4.0.0-beta.1 -  Fenix Leanplum Attribute set to TRUE (Device ID **39ec97f9-7cbd-43eb-9466-0956119cefb7** )
![FeniBeta](https://user-images.githubusercontent.com/51314259/74852397-2a8db400-5345-11ea-8a35-0374748010a9.png)

 ✔️Performed manually a migration from Fennec to Fenix and the **E_Fennec_To_Fenix_Migrated** event was successfully created. (Device ID **ca28e3cc-82c2-49c3-bad5-5a81b62a7e15**)
![migos](https://user-images.githubusercontent.com/51314259/74853587-ce2b9400-5346-11ea-9720-dd474ee207c0.png)

Please note that this event was generated in the **Firefox Nightly section** of Leanplum.
![image](https://user-images.githubusercontent.com/51314259/74853478-a6d4c700-5346-11ea-91f4-c1f8d9f32723.png)

**Comment by cbonacuse** [comment]
Hello! I know this is now closed, but after looking in Leanplum at the Nightly users, it appears that the fenix attribute did _not_ get applied retroactively to users who were updated to Fenix prior to the attribute being created. Was this expected?

According to [this dashboard](https://www.leanplum.com/dashboard#/5094741967896576/report/userbase/0/total-users/iagyl_au_JTdCJTIyZiUyMiUzQSU3QiUyMmxvY2tlZCUyMiUzQWZhbHNlJTJDJTIyc2Vjb25kYXJ5VmVyYiUyMiUzQSUyMiUzRCUyMiUyQyUyMm9iamVjdHMlMjIlM0ElNUIlNUQlMkMlMjJjaGlsZHJlbiUyMiUzQSU1QiU3QiUyMmxvY2tlZCUyMiUzQWZhbHNlJTJDJTIyc3ViamVjdCUyMiUzQSUyMlRleHQlMjBwdXNoJTIwZW5hYmxlZCUyMiUyQyUyMnZlcmIlMjIlM0ElMjJ0JTIyJTJDJTIyc2Vjb25kYXJ5VmVyYiUyMiUzQSUyMiUzRCUyMiUyQyUyMm9iamVjdHMlMjIlM0ElNUIlNUQlMkMlMjJjaGlsZHJlbiUyMiUzQSU1QiU1RCU3RCUyQyU3QiUyMmxvY2tlZCUyMiUzQWZhbHNlJTJDJTIydmVyYiUyMiUzQSUyMk9SJTIyJTJDJTIyc2Vjb25kYXJ5VmVyYiUyMiUzQSUyMiUzRCUyMiUyQyUyMm9iamVjdHMlMjIlM0ElNUIlNUQlMkMlMjJjaGlsZHJlbiUyMiUzQSU1QiU3QiUyMmxvY2tlZCUyMiUzQWZhbHNlJTJDJTIyc3ViamVjdCUyMiUzQSUyMlVzZXIlMjBhdHRyaWJ1dGUlMjIlMkMlMjJ2ZXJiJTIyJTNBJTIyJTNEJTIyJTJDJTIyc2Vjb25kYXJ5VmVyYiUyMiUzQSUyMiUzRCUyMiUyQyUyMm9iamVjdHMlMjIlM0ElNUIlMjJUcnVlJTIyJTVEJTJDJTIyY2hpbGRyZW4lMjIlM0ElNUIlNUQlMkMlMjJub3VuJTIyJTNBJTIyZmVuaXglMjIlN0QlMkMlN0IlMjJsb2NrZWQlMjIlM0FmYWxzZSUyQyUyMnN1YmplY3QlMjIlM0ElMjJVc2VyJTIwYXR0cmlidXRlJTIyJTJDJTIydmVyYiUyMiUzQSUyMiUzRCUyMiUyQyUyMnNlY29uZGFyeVZlcmIlMjIlM0ElMjIlM0QlMjIlMkMlMjJvYmplY3RzJTIyJTNBJTVCJTIyVHJ1ZSUyMiU1RCUyQyUyMmNoaWxkcmVuJTIyJTNBJTVCJTVEJTJDJTIybm91biUyMiUzQSUyMkZlbml4JTIyJTdEJTVEJTdEJTVEJTdEJTJDJTIyZyUyMiUzQSU3QiUyMmxvY2tlZCUyMiUzQWZhbHNlJTJDJTIyc2Vjb25kYXJ5VmVyYiUyMiUzQSUyMiUzRCUyMiUyQyUyMm9iamVjdHMlMjIlM0ElNUIlNUQlMkMlMjJjaGlsZHJlbiUyMiUzQSU1QiU3QiUyMmxvY2tlZCUyMiUzQWZhbHNlJTJDJTIyc3ViamVjdCUyMiUzQSUyMkFwcCUyMHZlcnNpb24lMjIlMkMlMjJ2ZXJiJTIyJTNBJTIyJTNEJTIyJTJDJTIyc2Vjb25kYXJ5VmVyYiUyMiUzQSUyMiUzRCUyMiUyQyUyMm9iamVjdHMlMjIlM0ElNUIlMjIxLjAlMjIlNUQlMkMlMjJjaGlsZHJlbiUyMiUzQSU1QiU1RCU3RCU1RCU3RCU3RA==), the earliest version of Nightly (with the date/timestamp versioning) that shows fenix (or Fenix) is TRUE is 2/14.

**Comment by ValentinTimisica** [comment]
Yes, this is expected. We added a new attribute in code which only produces effects for the future.
