### ISSUE TITLE
[Bug] Opening Fenix loads wrong app (custom tabs)

### ISSUE THREAD

**Issue by lnicola** [mozilla-mobile/fenix#8179]
## Steps to reproduce

1. Enable Fenix custom tabs
2. Use them for a while (e.g. by clicking links in Gmail messages)

### Actual behavior

From time to time, after loading a custom tab and going back to Gmail, trying to open Fenix will instead start Gmail. Killing both apps doesn't solve it, but it starts working after a couple of tries.

### Device information

* Android device: OnePlus 6T / Android 10
* Fenix version: Nightly

**Comment by ekager** [comment]
Closing for #7939
