### ISSUE TITLE
As a user, I should have a way to easily dismiss the sign in success screen

### ISSUE THREAD

**Issue by Sdaswani** [mozilla-mobile/fenix#818]
### Why/User Benefit/User Problem
After a user signs in to a FF account, they are just left on this page: https://photos.app.goo.gl/YCwVLYqWfea1ueb49 It sort of leaves me confused about what to do next, and this page also goes into my session.

### What / Requirements
After I've signed in to my FF account, this page should be easily dismissed (maybe a toast?), and should not be in the web page history. It's just coincidental that the FF account flow takes me through the web, but it's really an _app_ flow

### Acceptance Criteria (how do I know when I’m done?)
The FF account sign in feels like an app experience.

**Comment by vesta0** [comment]
Dup of #3240

**Comment by vesta0** [comment]
Thanks @Sdaswani  :)
