### ISSUE TITLE
[Bug] Can't add private browsing shortcut

### ISSUE THREAD

**Issue by apbitner** [mozilla-mobile/fenix#8183]
## Steps to reproduce
In Settings, tap on 'Add private browsing shortcut'

### Expected behavior
Private browsing shortcut is added to home screen

### Actual behavior
Nothing happens, except the icons in the phone's status bar turn from black to white

### Device information

* Android device: Pixel 3, Android 10
* Fenix version: Nightly 200205 06:00

**Comment by apbitner** [comment]
This issue has also happened with a colleague, and some users during a usability test a couple of weeks ago

**Comment by Diana-Rus** [comment]
Hi, I can reproduce this issue with Google Pixel C (Android 8.0.0) on Firefox Preview Beta 4.0.0-beta.1.

Note: This issue seems to be related to ticket: https://github.com/mozilla-mobile/fenix/issues/8424 .
As for now not only for Android 8.0.0 bu also Android 10  from issue's description.

**Comment by mcarare** [comment]
@apbitner Do you know if they have a custom launcher installed?

**Comment by apbitner** [comment]
@mcarare I'm not sure. I can ask the user research if we have any video recordings. I did not have a custom launcher when it happened for me. I've since upgraded to the Pixel 4 on the stock launcher and still having the issue.

**Comment by mcarare** [comment]
I have a Pixel 4, I will try to reproduce the issue. Thanks for the update!
