### ISSUE TITLE
[Bug] Opening tab from extension popup does not close popup

### ISSUE THREAD

**Issue by freaktechnik** [mozilla-mobile/fenix#8184]
## Steps to reproduce

- install uBO
- Open uBO popup (click on uBO entry in browser menu)
- Click on the sliders button to the right below the enable/disable switch

### Expected behavior

Popup view is closed and newly opened tab is shown

### Actual behavior

Popup view stays open while tab is opened in the background

### Device information

* Android device: Nexus 5X
* Fenix version: Nigthly 200206 06:01 (Build #20370605), presumably based on commit 9399ba5f9

**Comment by csadilek** [comment]
@freaktechnik Thanks for filing! 

This will work once https://bugzilla.mozilla.org/show_bug.cgi?id=1612363 lands.

**Comment by csadilek** [comment]
@freaktechnik this works now in the latest Nightly from the play store: Nightly 200213 18:01.
