### ISSUE TITLE
Disable PWA install prompt/menu entry

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/fenix#8186]
From https://www.reddit.com/r/firefox/comments/f02ft6/how_to_disable_install_notification_in_the/

### Why/User Benefit/User Problem

As a user, I would like to not be prompted on every visit of a site that supports installation (via the blue dot on the menu) because I see it too often.

### What/Requirements

Add a preference/setting to disable the prompt (blue dot) or the menu entry for "Install" on PWA supported sites. 

### Acceptance Criteria (how do I know when I’m done?)

Two new preferences in settings:

1. Disable install prompt for PWA
2. Disable install menu item

There may be other strategies to deal with this as well - perhaps only showing the install prompt only on the first and second visits, for example. 

Disabling the menu entry might still be useful, almost akin to the same setting in desktop for disabling notifications or accessing VR devices.

**Comment by kbrosnan** [comment]
Dupe 7359
