### ISSUE TITLE
[Bug]Add-ons aren't fully translated

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#8188]
## Prerequisites
Change the device Language and input method to German (Deutsch)
or
Change the Language from Fenix settings.

## Steps to reproduce
1. Navigate to the add-ons manager
2. Tap the '+' (install button) and confirm the installation
3. Tap on Ublock and open each section (Settings, Details, Permissions)
4. Disable uBlock
5. Uninstall uBlock 

### Expected behavior
Everything should be translated as per the selected language ?

### Actual behavior
Most of the options, sections and subsections aren't translated.

### Device information

* Android device: 
• Google Pixel 3a XL (Android 10)
• Google Pixel 3a (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7.0.0)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

* Fenix version: Nightly #20380605 from 2/7

### Notes
► Sections that are/aren't translated after changing the Android Language and input settings
 
| Status | Section/Item|
| ------------- | ------------- |
| ❌  | Recommended/Installed subsection |
| ✔️  | The short description |
| ❌  | Add/Cancel installation context menu  |
| ❌  | Downloading and verifying add-on bar |
| ❌  | Installation confirmation snackbar |
| ❌  |  uBlock origin options and buttons (Settings, Details, Permissions, Remove button, ON/OFF) |
| ✔️  | Settings section  |
| ✔️  | Details section  |
| ❌  | Permissions section |
| ❌  | Disable/Enable confirmation snackbar |
| ❌  | Uninstall confirmation snackbar |

► Video 
![20200207_091426](https://user-images.githubusercontent.com/51314259/74011746-3b2b4b00-4991-11ea-9c58-738ef88125c4.gif)

► Sections that are/aren't translated after changing the language from Fenix settings.

| Status | Section/Item|
| ------------- | ------------- |
| ❌  | Recommended/Installed subsection |
| ✔️  | The short description |
| ❌  | Add/Cancel installation context menu  |
| ❌  | Downloading and verifying add-on bar |
| ❌  | Installation confirmation snackbar |
| ❌  |  uBlock origin options and buttons (Settings, Details, Permissions, Remove button, ON/OFF) |
| ❌  | Settings section  |
| ✔️  | Details section  |
| ❌  | Permissions section |
| ❌  | Disable/Enable confirmation snackbar |
| ❌  | Uninstall confirmation snackbar |

► Video change 
![20200207-091655-1](https://user-images.githubusercontent.com/51314259/74011985-d8867f00-4991-11ea-8396-ff96d3daa881.gif)

**Comment by csadilek** [comment]
@AndiAJ This was fixed by @Amejia481 today. Can you verify?

**Comment by AndiAJ** [comment]
Hi, I've re-checked this matter on the latest **Nightly #20430607 from 2/12** using the following devices:
• Google Pixel 3a XL (Android 10)
• Google Pixel 3a (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7.0.0)
• OnePlus A3 (Android 6.0.1)

## German:

### ► Sections that are/aren't translated on **`all of the above mentioned devices`** **after changing the Android Language** and input settings 
| Status | Section/Item|
| ------------- | ------------- |
| ✔️  | Recommended/Installed subsection |
| ✔️  | The short description |
| ✔️  | Add/Cancel installation context menu  |
| ✔️  | Downloading and verifying add-on bar |
| ✔️  | Installation confirmation snackbar |
| ❌  | Enabled/Disabled subsection |
| ❌  | uBlock origin options and buttons (Settings, **❌Details - is not translated**, Permissions, Remove button, ON/OFF) |
| ✔️  | Settings section  |
| ✔️  | Details section  |
| ✔️  | Permissions section |
| ✔️  | Disable/Enable confirmation snackbar |
| ✔️  | Uninstall confirmation snackbar |

### ► Sections that are/aren't translated on **`all of the above mentioned devices`** **after changing the language from Fenix** settings.

| Status | Section/Item|
| ------------- | ------------- |
| ✔️  | Recommended/Installed subsection |
| ✔️  | The short description |
| ✔️  | Add/Cancel installation context menu  |
| ✔️  | Downloading and verifying add-on bar |
| ✔️  | Installation confirmation snackbar |
| ❌  | Enabled/Disabled subsection |
| ❌  | uBlock origin options and buttons (Settings, **❌Details - is not translated**, Permissions, Remove button, ON/OFF) |
| ❌  | Settings section  |
| ✔️  | Details section  |
| ✔️  | Permissions section |
| ✔️  | Disable/Enable confirmation snackbar |
| ✔️  | Uninstall confirmation snackbar |

## Spanish

### ► Sections that are/aren't translated on **`all of the above mentioned devices`** after **changing the Android Language** and input settings
 
| Status | Section/Item|
| ------------- | ------------- |
| ✔️  | Recommended/Installed subsection |
| ✔️  | The short description |
| ✔️  | Add/Cancel installation context menu  |
| ✔️  | Downloading and verifying add-on bar |
| ✔️  | Installation confirmation snackbar |
| ❌  | Enabled/Disabled subsection |
| ✔️  | uBlock origin options and buttons (Settings, Details, Permissions, Remove button, ON/OFF) |
| ✔️  | Settings section  |
| ✔️  | Details section  |
| ✔️  | Permissions section |
| ✔️  | Disable/Enable confirmation snackbar |
| ✔️  | Uninstall confirmation snackbar |

### ► Sections that are/aren't translated **`on 4 of the above mentioned devices (Google Pixel 3a XL , Google Pixel 3a, Huawei Mate 20 Lite, Samsung Galaxy S7 )`** **after changing the language from Fenix** settings.

| Status | Section/Item|
| ------------- | ------------- |
| ✔️  | Recommended/Installed subsection |
| ✔️  | The short description |
| ✔️  | Add/Cancel installation context menu  |
| ✔️  | Downloading and verifying add-on bar |
| ✔️  | Installation confirmation snackbar |
| ❌  | Enabled/Disabled subsection |
| ✔️  | uBlock origin options and buttons (Settings, Details, Permissions, Remove button, ON/OFF) |
| ❌  | Settings section  |
| ✔️  | Details section  |
| ✔️  | Permissions section |
| ✔️  | Disable/Enable confirmation snackbar |
| ✔️  | Uninstall confirmation snackbar |

###  ❗ ► Sections that are/aren't translated **`on OnePlus A3`** **after changing the language from Fenix** settings.
| Status | Section/Item|
| ------------- | ------------- |
| ❌  | Recommended/Installed subsection |
| ✔️  | The short description |
| ❌  | Add/Cancel installation context menu  |
| ❌  | Downloading and verifying add-on bar |
| ❌  | Installation confirmation snackbar |
| ❌  | Enabled/Disabled subsection |
| ❌  | uBlock origin options and buttons (Settings, Details, Permissions, Remove button, ON/OFF) |
| ❌  | Settings section  |
| ✔️  | Details section  |
| ❌  | Permissions section |
| ❌  | Disable/Enable confirmation snackbar |
| ❌  | Uninstall confirmation snackbar |

@Amejia481 & @csadilek - I would kindly ask you to review the above findings.
Quite strange why the fix doesn't seem to be working on the OnePlus A3 when changing Fenix's language to Spanish.

**I'll remove the QA needed until further notice.**

**Comment by Amejia481** [comment]
Thank you, we are going to take a look!

**Comment by Amejia481** [comment]
Hi @AndiAJ 
Could you please take a look to the details below?

### All of the devices.
- **Enabled/Disabled subsection:** These are newly added strings, we don't have the translations yet.
- **uBlock origin options and buttons:** These are internals of the extension, we don't have control over them, the extension developer has to translate them //cc @brampitoyo @kewisch.

- **Settings section:** These are internals of the extension, we don't have control over them, the extension developer has to translate them //cc @brampitoyo @kewisch.

### on OnePlus A3
Looks pretty strange, would you mind testing just changing the OS language to German (The Fenix language settings should be **"Follow device language"**)? To see if any translations are applied over Fenix and add-on pages?

**Comment by brampitoyo** [comment]
@AndiAJ Correct. Everything in uBlock Origin, we don’t control. It will be up to the add-on developer to fix these issues. But thanks for listing these concerns. We will gather them (there have been other uBO issues filed) and email the developer.

**Comment by kewisch** [comment]
@Amejia481 Can you let me know what version of uBlock Origin you were testing? I've checked the translations and it seems that uBO is well translated into German.

**Comment by Amejia481** [comment]
You were right @kewisch, UBlock provides the translations for German, I realized that this is [GeckoView bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1615680), I included all the details on the bug

**Comment by AndiAJ** [comment]
Hi, I've re-checked this matter on **`Nightly #20470607 from 2/16`** by changing the following devices **Language & input settings** to German :

• Google Pixel 3a (Android 9)
• Samsung Galaxy S9 (Android 8.0.0)
• Samsung Galaxy S7 (Android 7.0.0)
• OnePlus A3 (Android 6.0.1)


| Status | Section/Item|
| ------------- | ------------- |
| ✔️  | Recommended/Installed subsection |
| ✔️  | The short description |
| ✔️  | Add/Cancel installation context menu  |
| ✔️  | Downloading and verifying add-on bar |
| ✔️  | Installation confirmation snackbar |
| ✔️  | Settings section  |
| ✔️  | Details section  |
| ✔️  | Permissions section |
| ✔️  | Disable/Enable confirmation snackbar |
| ✔️  | Uninstall confirmation snackbar |

As per Arturo's [remark](https://github.com/mozilla-mobile/fenix/issues/8188#issuecomment-585290196) the following sections either don't have a translation yet, either are internals of the extension, and we don't have control over them.

Enabled/Disabled subsection
![enabldis](https://user-images.githubusercontent.com/51314259/74642057-00889600-517b-11ea-93d7-8cb90d6a4797.png)

uBlock origin options and buttons (**Details button**)
![rsz_screenshot_20200217-113021](https://user-images.githubusercontent.com/51314259/74642042-f6669780-517a-11ea-936b-2acbc70249b6.png)

► Video from OnePlus A3
![20200217-112742](https://user-images.githubusercontent.com/51314259/74642166-26159f80-517b-11ea-9658-384ad6b22ee2.gif)

Based on this I'll mark this issue **verified as fixed** and close it.
@Amejia481 -  I would kindly ask you to review, and if I missed or overlooked something please re-open the issue. ☺️

**Comment by Amejia481** [comment]
Thanks for checking @AndiAJ! 
Let's keep this open until we can confirm if this is bug is from GeckoView https://github.com/mozilla-mobile/fenix/issues/8188#issuecomment-586420509

**Comment by Amejia481** [comment]
Closing this issue as the [geckoview](https://bugzilla.mozilla.org/show_bug.cgi?id=1615680#c7) bug mentioned the fix is out the scope of this issue as it will required further changes in the add-on itself and possibly [i18n api](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/i18n), the same behaviour can be seen on Fennec too.
