### ISSUE TITLE
[Bug ]UI elements temporarily shift position when tapping the “Refresh” button

### ISSUE THREAD

**Issue by acornestean** [mozilla-mobile/fenix#8189]
## Prerequisites
uBlock Origin is installed and enabled in Fenix
## Steps to reproduce
1. Access any webpage
2. Tap on the three-dot menu
3. Scroll to the top of the menu list and tap on the uBlock Origin icon
4. Notice that an options page will open
5. Tap on any of the gray banners (requests blocked or domains connected)
6. Notice that a list with blocked requests/connected domains will be displayed at the bottom
7. Tap on the On/Off button
8. Notice that a “Refresh” button appears on screen
9. Tap the “Refresh” button
10. Observe that the list with blocked requests/connected domains at the bottom will, temporarily, be displayed in the top left corner of the screen, while the rest of the UI will be shifted right, before all elements returning to their normal position
### Expected behavior
UI elements should keep their position on screen when interacting with them.
### Actual behavior
The list at the bottom is temporarily displayed in the top left corner, while the rest of the UI shifts position, when tapping on the “Refresh” button.
### Device information
* Samsung Galaxy S7 (Android 8.0.0)

* Fenix version: #20380606 02/07/2020

### Note 
This only occurs in portrait mode on smaller screen non-tablet devices. For example, the issue occurs on a Samsung Galaxy S7 (Android 8.0.0), however NOT on a Samsung Galaxy S7 Edge (Android 8.0.0) or a Galaxy Tab A (Android 9).

![Shifting UI elements](https://user-images.githubusercontent.com/50236075/74012808-cc032600-4993-11ea-81b2-48f2d87c1b65.gif)

**Comment by csadilek** [comment]
The refresh button should actually close the popup which will be fixed by https://github.com/mozilla-mobile/fenix/issues/8184 and https://bugzilla.mozilla.org/show_bug.cgi?id=1612363 respectively.

**Comment by csadilek** [comment]
I am closing this, as this needs would need be improved by the add-on developer.
