### ISSUE TITLE
[Bug][a11y] Increase text contrast for the "Remove" button from Add-ons page

### ISSUE THREAD

**Issue by softvision-miralobontiu** [mozilla-mobile/fenix#8191]
## Prerequisites
1. Make sure you have Accessibility Scanner installed and turned on.
2. Have uBlock Origin installed.

## Steps to reproduce
1. Go to Settings - Add-ons and tap on the uBlock Origin.
2. Using Accessibility Scanner scan the page.

### Expected behavior
No suggestions made.

### Actual behavior
Suggestion to increase the item's text foreground to background contrast ratio - see the screenshot below.

### Device information
* Android device: Google Pixel (Android 10)
* Fenix version: 2/7 Nightly build

![remove](https://user-images.githubusercontent.com/40694158/74013717-c7d80800-4995-11ea-8a87-a5b8d6091078.png)

**Comment by csadilek** [comment]
@softvision-miralobontiu @Amejia481 landed a fix for this today so this can be verified :).

**Comment by softvision-miralobontiu** [comment]
Verified as fixed on the latest build from 2/12 (#20430607) with Samsung Galaxy Note 8 (Android 9).
Accessibility Scanner displays no other suggestions.
Thank you!
