### ISSUE TITLE
[Bug][a11y] Menus from the add-on's settings page suggested to be larger

### ISSUE THREAD

**Issue by softvision-miralobontiu** [mozilla-mobile/fenix#8192]
## Prerequisites
1. Make sure you have Accessibility Scanner installed and turned on.
2. Have uBlock Origin installed.

## Steps to reproduce
1. Go to Settings - Add-ons and tap on the uBlock Origin.
2. Tap on Settings from the uBlock Origin's page.
3. Using Accessibility Scanner scan the page.

### Expected behavior
No suggestions are made.

### Actual behavior
All the menus (Filter lists, My filters, My rules, Whitelist, and About) are suggested to be made larger - see the screenshot below.

### Device information
* Android device: Google Pixel (Android 10)
* Fenix version: 2/7 Nightly build

![a11y scanner settings](https://user-images.githubusercontent.com/40694158/74014267-f7d3db00-4996-11ea-8531-d727740b7161.png)

**Comment by csadilek** [comment]
This would need to be addressed in the add-on itself //cc @brampitoyo @kewisch

**Comment by gabrielluong** [comment]
@softvision-miralobontiu can we close this bug? Since this is not something we can address in Fenix/AC, this has to do with the actual content of the addon which can only be manipulated by the author.

**Comment by softvision-miralobontiu** [comment]
Sure!
