### ISSUE TITLE
[Bug][a11y] Increase some item's sizes from the uBlock Origin page

### ISSUE THREAD

**Issue by softvision-miralobontiu** [mozilla-mobile/fenix#8193]
## Prerequisites
1. Make sure you have Accessibility Scanner installed and turned on.
2. Have uBlock Origin installed.

## Steps to reproduce
1. Open a page, tap on the three-dot meu, and tap on the uBlock Origin.
2. Using Accessibility Scanner scan the page.

### Expected behavior
No suggestions are made.

### Actual behavior
All 4 elements under the enable/disable blue button are suggested to be increased from 23dp x 17dp to 48dp x 48dp - like in the screenshot below.

### Device information
* Android device: Google Pixel (Android 10)
* Fenix version: 2/7 Nightly build

<img width="1082" alt="a11y scanner" src="https://user-images.githubusercontent.com/40694158/74014688-dde6c800-4997-11ea-8fb9-9e237c6366da.png">

**Comment by csadilek** [comment]
This would need to be addressed in the add-on itself //cc @brampitoyo @kewisch

**Comment by softvision-miralobontiu** [comment]
I will close this issue based on the fact that the actual content of the addon can only be manipulated by the author.
