### ISSUE TITLE
[Bug][a11y] 2 suggestions to increase some elements from the uBlock Origin page

### ISSUE THREAD

**Issue by softvision-miralobontiu** [mozilla-mobile/fenix#8194]
## Prerequisites
1. Make sure you have Accessibility Scanner installed and turned on.
2. Have uBlock Origin installed.

## Steps to reproduce
1. Open a page, tap on the three-dot meu, and tap on the uBlock Origin.
2. Using Accessibility Scanner scan the page.

### Expected behavior
No suggestions are made.

### Actual behavior
All the elements under the "domains connected" have 2 suggestions - screenshot below:
- to be increased from 20dp x 20dp to 48dp x 48dp , and
- to increase contrast ratio from 3.06 to 4.5.

### Device information
* Android device: Google Pixel (Android 10)
* Fenix version: 2/7 Nightly build

<img width="1082" alt="suggestion" src="https://user-images.githubusercontent.com/40694158/74015362-2488f200-4999-11ea-91f9-72955ec3dcbc.png">

**Comment by csadilek** [comment]
This would need to be addressed in the add-on itself //cc @brampitoyo @kewisch

**Comment by softvision-miralobontiu** [comment]
I will close this issue based on the fact that the actual content of the addon can only be manipulated by the author.
