### ISSUE TITLE
[Bug]Open tabs contour inconsistency  using the Dark theme

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#8195]
## Prerequisites
Have the Dark theme selected.
Have a couple of open tabs.

## Steps to reproduce
1. Exit to the Fenix Home screen by tapping the tabs couter.
2. Check the Open tabs section, focusing on the minimized tab.

### Expected behavior
No UI issues.

### Actual behavior
For a couple of seconds a contour is displayed on the lower part of the minimized tab.

### Device information
* Android device: OnePlus A3 (Android 6.0.1)

* Fenix version: Nightly #20380605 from 2/7

### Notes
❗ Doesn't occur on each attempt. (happens randomly)

Not reproducible on the following devices:
• Google Pixel 3a XL (Android 10)
• Google Pixel 3a (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7.0.0)
• LG Nexus 4 (Android 5.1.1)

► Video
![20200207_092012](https://user-images.githubusercontent.com/51314259/74016626-687cf680-499b-11ea-9d03-1439624cc625.gif)

**Comment by AndiAJ** [comment]
Reproducible on 4.0.0-beta.2 in **Private mode** using a  OnePlus A3 (Android 6.0.1)

**Comment by topotropic** [comment]
@AndiAJ is this still relevant with the dedicated tab tray? Thanks!

**Comment by AndiAJ** [comment]
Hi @topotropic , no, haven't seen this problem since the Tabs Tray got implemented. ☺️
