### ISSUE TITLE
[Bug] "Search privately" opens another browser

### ISSUE THREAD

**Issue by DivyanshLath** [mozilla-mobile/fenix#8199]
## Steps to reproduce
Select text on webpage and tap "Search privately"

### Expected behavior
New private tab should open in Firefox Preview Nightly (Same app) where the selected text should be searched

### Actual behavior
Opera Beta opens and selected text is searched in private browsing tab of Opera Beta. Basically "Search privately" open an entirely different browser. [Can't add opera screenshot because it disables screen capture in private tab]

### Device information
* Android device: Poco F1 MIUI 11 global stable based on android 9
* Fenix version: 200207 06:00 
![Screenshot_2020-02-07-16-54-31-590_org mozilla fenix nightly](https://user-images.githubusercontent.com/27262528/74026542-6b440f80-49cc-11ea-9fab-42d553115205.jpg)

**Comment by cadeyrn** [comment]
This comes from Opera, not from Firefox Preview. I don't have Opera installed, so there is no item for opening in Opera, but on my device there is one item for opening in Firefox Focus and another one for opening in Firefox Lite.

**Comment by DivyanshLath** [comment]
I have total of 3 browsers, Firefox, Firefox Preview Nightly and Opera Beta.
I uninstalled Opera beta and installed Chrome. "Search Privately" option is no longer shown in Firefox Preview Nightly. 
Based on current observation a "Search Privately" option is shown inside Firefox Preview if Opera is installed and tapping it opens Opera private tab.

**Comment by DivyanshLath** [comment]
I tried it after uninstalling Opera and installing Chrome, "Search Privately" is gone now. I understand it now , thank you.
