### ISSUE TITLE
about html select tag

### ISSUE THREAD

**Issue by cadenvip** [mozilla-mobile/fenix#82]
Hi, I clone fenix and run in my phone, I find the tag `<select></select>` can render ,but it cannot to select options.  I don't know if it is a bug, or how to deal with it.

**Comment by pocmo** [comment]
We have a `feature-prompts` component that implements most of those pickers/dialogs/etc.:
https://github.com/mozilla-mobile/android-components/tree/master/components/feature/prompts

**Comment by abodea** [comment]
Removing the `needs:STR` based on the comment from above.
