### ISSUE TITLE
Lockbox promotion in Fenix from identified UN/PW fields

### ISSUE THREAD

**Issue by sandysage** [mozilla-mobile/fenix#820]
When I'm using Fenix, and get to a login form for one of my online accounts, I want to know how to use my Firefox saved logins to fill in login forms.

For instance, when I go to Twitter in my new Fenix browser, and I'm already signed into my Firefox Account, my current expectation is that the credentials I saved in Firefox previously would automatically populate the username and password fields on the website. I don't yet know I need to find Library -> logins to troubleshoot why my saved credentials aren't working.

## Acceptance criteria
* Should behave similar to how we handle the identified UN/PW fields for autofill with "Search Firefox Lockbox"
* Should display some form of promotion for how to "use firefox saved login"

## Visual design
<img width="369" alt="53750181-53801500-3e66-11e9-986c-af5ae348f43f" src="https://user-images.githubusercontent.com/850418/53752156-208c5000-3e6b-11e9-8416-f939f3d3796c.png">

**Comment by vesta0** [comment]
@sandysage would you be able to confirm that this is working in Fenix as expected?

**Comment by vesta0** [comment]
This will be addressed by #821
