### ISSUE TITLE
Add icon for Switch to tab search suggestion description

### ISSUE THREAD

**Issue by ValentinTimisica** [mozilla-mobile/fenix#8200]
This is a follow up to #1500.

### What/Requirements
- Add the icon from [this comment](https://github.com/mozilla-mobile/fenix/issues/1500#issuecomment-484268831) next to "Switch to tab" search suggestion description.

### Acceptance Criteria (how do I know when I’m done?)
- If I start searching for a tab that is already opened and I see an entry for it with "Switch to tab" description and [icon](https://github.com/mozilla-mobile/fenix/issues/1500#issuecomment-484268831) that indicates that selecting it will switch me to that open tab.

**Comment by Poopooracoocoo** [comment]
It would also be really great if the "Switch to tab" text were coloured so you can discern it from other suggestions. Probably dark blue like other elements in Fenix are. Should I make a new issue suggesting this?

**Comment by AndiAJ** [comment]
Done in #13913
