### ISSUE TITLE
[Bug] Overlapping UI elements are both activated when one is tapped

### ISSUE THREAD

**Issue by acornestean** [mozilla-mobile/fenix#8205]
## Prerequisites
uBlock Origin is installed and enabled in Fenix
## Steps to reproduce
1. Access any website
2. Tap on the three-dot menu
3. Scroll to the top of the menu list and tap on the uBlock Origin icon
4. Notice that an options page will open
5. Tap the On/Off button to disable the add-on for that specific site
6. Tap the On/Off button again to re-enable the add-on for that specific site
7. Notice that a label will be displayed underneath the button, with two options: disable the add-on for this site & disable the add-on only on this page 
8. Notice that the second option will overlap the gray “Blocked Requests”  banner
9. Tap on the second option on the label, the one to disable the add-on on that page
10. Observe that tapping on the second option of the label will also activate the banner and display the list with blocked resources and connected domains
### Expected behavior
Tapping on the label should only activate the option stated on the label and then dismiss it.
### Actual behavior
The gray banner which displays the blocked resources/connected domains list when tapped activates when tapping on the label option displayed over it.

### Device information
*Samsung Galaxy S7 (Android 8.0.0)
*Samsung Galaxy S7 Edge (Android 8.0.0)

* Fenix version: #20380606 02/07/2020
### Note
The issue occurs in both Portrait and Landscape modes.

![Overlapping UI elements](https://user-images.githubusercontent.com/50236075/74035880-d3422800-49c3-11ea-8855-05797a78d8b9.gif)

**Comment by csadilek** [comment]
This would need to be addressed in the add-on itself //cc @brampitoyo @kewisch

**Comment by csadilek** [comment]
I am closing after discussion with @softvision-miralobontiu as this needs to be improved by the add-on developer (Fennec has the same behaviour).
