### ISSUE TITLE
[Bug] Site specific options are not fully displayed in Logger in landscape mode

### ISSUE THREAD

**Issue by acornestean** [mozilla-mobile/fenix#8207]
## Prerequisites
- uBlock Origin is installed and enabled in Fenix
- device is in landscape mode
## Steps to reproduce
1. Access any website
2. Tap on the three-dot menu
3. Scroll to the top of the menu list and tap on the uBlock Origin icon
4. Notice that an options page will open
5. Tap on the Logger option
6. Tap the back button on the top of the page to access the Logger
NOTE: The Logger page does not fit the screen of smaller devices in Portrait mode and the user must scroll to reveal the entire page
7. Tap the uBlock Origin icon at the top of the screen
8. Notice that the site specific options are not fully visible and the user cannot scroll to reveal them
9. Flip the device in portrait mode
10. Observe that the entire options are now visible
### Expected behavior
The options should be entirely visible or a method to scroll to reveal them all should be implemented in landscape mode.
### Actual behavior
The options are not fully visible and users cannot scroll to reveal them.
### Device information
*Samsung Galaxy S7 (Android 8.0.0)
*Samsung Galaxy S7 Edge (Android 8.0.0)

* Fenix version: #20380606 02/07/2020

![landscape options not visible](https://user-images.githubusercontent.com/50236075/74040508-87e04780-49cc-11ea-9dfd-155bc45bcb7a.gif)

**Comment by csadilek** [comment]
This would need to be addressed in the add-on itself //cc @brampitoyo @kewisch

**Comment by csadilek** [comment]
Closing this as well as it needs to be fixed in the add-on and is not actionable by us.
