### ISSUE TITLE
[Bug] "Tab closed" dialog doesn't go away if you leave Open Tabs 

### ISSUE THREAD

**Issue by yaomtc** [mozilla-mobile/fenix#8214]
## Steps to reproduce
Open a new tab, close it, and quickly switch to another tab before the "tab closed" popup goes away.

### Expected behavior
Prompt disappears.

### Actual behavior
Prompt does not disappear, it's stuck until you hit the Undo button.

### Device information

* Android device: Moto X4 (LineageOS 16 / Android 9.0)
* Fenix version: 3.2.0

**Comment by ekager** [comment]
Dupe of #7833 and it has been fixed in master.

**Comment by yaomtc** [comment]
Thanks, forgot to check closed issues first. Had only searched open ones.
