### ISSUE TITLE
[Bug] Make crash content page match new error style

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#8215]
Now that we have updated error page templates, we should have crash fragment match this styling. See here for more info: https://github.com/mozilla-mobile/fenix/issues/5892#issuecomment-582873882

**Comment by sblatz** [comment]
Curious what @brampitoyo thinks about this.

**Comment by brampitoyo** [comment]
@sblatz When I saw the Crash Content error on https://github.com/mozilla-mobile/fenix/issues/5892#issuecomment-582873882, my initial response was “Let’s file an issue to match the style of that page, to the rest of the error page”.

So it’s great that you’ve filed it here!

What’s required to match styling:

- Correct heading font size
- Update illustration (use the one for the Redirect Loop error page?)
- Un-anchor checkbox and 2 buttons, so they appear underneath the heading
- Stack the buttons
- Reorder the 2 buttons, so the preferred action (“Restore Tab”) appears first

So perhaps it’ll look like this (keep in mind that the illustration here still needs to be updated):

<img src="https://user-images.githubusercontent.com/51007/74123158-9039bc00-4c32-11ea-84ae-a2d14e76dddc.png" width="320">

**Comment by darkwing** [comment]
Note: `about:crashcontent` shows the contents of this page

**Comment by brampitoyo** [comment]
If the style of the page matches the spec above, we can close this issue. In the meantime, I’ll remove the `needs-ux` label.

**Comment by softvision-miralobontiu** [comment]
Hi all,
The about:crashcontent page doesn't display the new style. 
I'll remove the qa:needed label for now.

Tested on a created build version 1.0.2015 (39.0.20200409130114, 52ca085fb), with GV 77.0a1, with Google Pixel (Android 10), Sony Xperia Z5 Premium (Android 7.1.1), HTC 10 (Android 8), Samsung Galaxy Tab A6 (Android 5.1.1), and Motorola Moto G6 (Android 8).

![crash-report](https://user-images.githubusercontent.com/40694158/78987545-fcec0c80-7b36-11ea-8d50-b99e8947c0db.png)
