### ISSUE TITLE
Fenix app automatically connects to external servers at first startup without asking the user

### ISSUE THREAD

**Issue by ghost** [mozilla-mobile/fenix#8219]
## Description

I expect an app that respects the user's privacy to not connect to any external server when opening the browser. No matter how often I open the app, it must not connect to any external server automatically.

The user should decide what and when can be connected. It must not just be in the background

## Steps to reproduce

1. Install the Fenix app for the first time. You will immediately see that it connects to an extremely large number of external servers.

https://incoming.telemetry.mozilla.org
api.leanplum.com
firefox.settings.services.mozilla.com
content-signature-2.cdn.mozilla.net
app.adjust.com
android.clients.google.com
tracking-protection.cdn.mozilla.net
shavar.services.mozilla.com
http://detectportal.firefox.com/success.txt?ipv4 http://detectportal.firefox.com/success.txt?ipv6

2. Go to Settings -> Data collection -> Disable: Usage and technical data and Experiments

3. Quit Fenix and open Fenix app again The external servers have been reduced. But still it still connects to http://detectportal.firefox.com/success.txt?ipv4 or http://detectportal.firefox.com/success.txt?ipv6

### Fenix
* Fenix version: 3.2.1
https://github.com/mozilla-mobile/fenix/releases/tag/v3.2.1

**Comment by USB3-2-10Gbit** [comment]
It can't be like this when user runs the Fenix app for the first time. Nothing must be connected yet, a setup window must appear first and the user can decide which data is collected or not.

If the user deactivates everything in the setup window and completes the setup, it must be accepted that Fenix must not connect anything in the background. It may not connect until e.g. something has been entered in the "search" or activate the options under Settings -> Data collection

**Comment by USB3-2-10Gbit** [comment]
It can't be like this when user runs the Fenix app for the first time. Nothing must be connected yet, a setup window must appear first and the user can decide which data is collected or not.

If the user deactivates everything in the setup window and completes the setup, it must be accepted that Fenix must not connect anything in the background. It may not connect until e.g. something has been entered in the "search" or activate the options under Settings -> Data collection

**Comment by amedyne** [comment]
Closing this as we no longer integrate with Leanplum. See #19040.
