### ISSUE TITLE
[Bug] Performance issue: Main thread is blocked in onTitleChange, impacting Gecko page load performance

### ISSUE THREAD

**Issue by mstange** [mozilla-mobile/fenix#8238]
## Steps to reproduce

In an existing tab with a page loaded (such as about:blank), tap on the URL bar, enter google.com, and press Enter.

### Expected behavior

During page load (or really at all times), the UI thread should stay responsive and never be blocked for more than a few milliseconds.

### Actual behavior

There is a 400ms pause spent in this call stack:

```
com.android.internal.os.ZygoteInit.main()
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run()
java.lang.reflect.Method.invoke()
android.app.ActivityThread.main()
android.os.Looper.loop()
android.os.Handler.dispatchMessage()
android.os.Handler.handleCallback()
org.mozilla.gecko.EventDispatcher$3.run()
org.mozilla.geckoview.GeckoSessionHandler.handleMessage()
org.mozilla.geckoview.GeckoSession$2.handleMessage()
org.mozilla.geckoview.GeckoSession$2.handleMessage()
mozilla.components.browser.engine.gecko.GeckoEngineSession$createContentDelegate$1.onTitleChange()
androidx.transition.CanvasUtils.runBlocking$default()
androidx.transition.CanvasUtils.runBlocking()
java.util.concurrent.locks.LockSupport.parkNanos()
sun.misc.Unsafe.park()
java.lang.Thread.parkFor$()
java.lang.Object.wait()
```

Profile: https://perfht.ml/3bnXjSC

During this pause, [Gecko does not paint because it does not receive any Vsync notifications from the UI thread](https://bugzilla.mozilla.org/show_bug.cgi?id=1614063). This impacts page load performance, see [bug 1613205](https://bugzilla.mozilla.org/show_bug.cgi?id=1613205).

### Device information

* Android device: Moto G5
* Fenix version: Nightly 200205 06:00 (Build 20360606) 30.0.0, f42641b48 GV: 74.0a1-20200204095729

**Comment by pocmo** [comment]
@csadilek Looks like there are two options. Slow, blocking observers or the blocking history delegate call. I wonder why we decided to do the call blocking if the delegate has suspend methods. 🤔

**Comment by mstange** [comment]
Another thing I'd like to mention: I don't see as long a pause in my local (debug) Fenix build; I only see this problem in a Fenix build from the Google Play Store. I don't see `androidx.transition.CanvasUtils` in the stacks from my local build at all. I gathered two profiles from the two builds, with me typing google.com from the URL bar and pressing enter three times.

Local build, no 400ms pauses: https://perfht.ml/2vk9gZi
Google Play Store build, 400ms pauses: https://perfht.ml/38jHE4U

I'm aware of the following differences:
 - In the build from the play store, I'm logged in with my Firefox Sync account.
 - The Fenix source code is probably slightly different.
 - My local build does not have Leanplum / Adjust / Sentry.

**Comment by csadilek** [comment]
@mstange Thanks for filing and attaching the profile. We fixed this in Android Components and the latest "Firefox Preview Nightly" build (200212 06:01 Build 20430607) on the play store has the fix. Do you have time to verify as well?

**Comment by jrmuizel** [comment]
@csadilek how was it fixed?

**Comment by csadilek** [comment]
@jrmuizel the fix in A-C is linked above. We had a blocking write to the history storage executed in the `onTitleChange` callback. So, this would have blocked the main thread for the duration of the write, which we verified is gone now. This was an oversight and should have always been executed on an IO thread.

**Comment by mstange** [comment]
> @mstange Thanks for filing and attaching the profile. We fixed this in Android Components and the latest "Firefox Preview Nightly" build (200212 06:01 Build 20430607) on the play store has the fix. Do you have time to verify as well?

I just updated and the issue seems fixed, but my build ID is one lower than the one in your comment: I'm now on 200212 06:01 Build 20430606, with a 6 at the end. Is the fix in that build, too?
The profile looks good, no more 400ms pauses: https://perfht.ml/38osMlM

And, more generally, loading google.com now successfully paints early rather than late.
Before: https://perfht.ml/31xuTRU
After: https://perfht.ml/31xuTRU

**Comment by csadilek** [comment]
Thanks for confirming, @mstange. Yes, build is fine, same A-C commit.
