### ISSUE TITLE
[Bug] add search engine should allow substitution without a query parameter

### ISSUE THREAD

**Issue by akottr** [mozilla-mobile/fenix#8239]
## Steps to reproduce
Open settings -> search and add other search engine

### Expected behavior
%s in url path should work. e.g. https://dict.leo.org/englisch-deutsch/%s

### Actual behavior
%s works only in query strings

### Device information
Samsung S10
* Android device: Android Version 10
* Fenix version: 
Nightly 200207 18:00 (Build #20381806)
31.0.0, d612ed220
GV: 74.0a1-20200206093813

**Comment by loveless90** [comment]
https://www.duden.de/suchen/dudenonline/%s does work and the search string seems to have the same structure (words with spaces as delimiters), so fenix rather seems to have a problem with the url.

**Comment by loveless90** [comment]
I tested **leo.org** again out of curiosity and seems to work now. Don't know if it was an issue of the website or of fenix, but somehow it got fixed.

Tested with: Nightly 200426 06:10 (Build #21170608)

**Comment by akottr** [comment]
Can confirm. Seems to be fixed.
