### ISSUE TITLE
"Copy to Clipboard" Button on Smartphone Version

### ISSUE THREAD

**Issue by NineOutOfTen** [mozilla-mobile/fenix#8241]
Hello! I like using Firefox Preview very much! This is my first time posting so I apologize if this subject has already been brought up. However, I would like to suggest a "copy to clipboard" button or feature be put on the smartphone version of Fenix. There is one for the tablet version and I have to use a work around by opening another app that has the link in order to copy it on my smartphone so I can copy a link to my clipboard.

Please feel free to share if this is in the works or if someone has some insight as to what I can do in case I am missing something or incorrect in my conclusion. Thanks for your time and consideration!

**Comment by NineOutOfTen** [comment]
One other thing. Firefox Focus has a "Copy to Clipboard" button as well.

**Comment by kbrosnan** [comment]
You can copy the URL by long pressing on the address bar while in the website view.
