### ISSUE TITLE
[Bug] Firefox Preview does not remember device name

### ISSUE THREAD

**Issue by cadeyrn** [mozilla-mobile/fenix#8246]
### Steps to reproduce

1. Change your device name in the sync settings.

### Expected behavior

The device name does not change.

### Actual behavior

I already changed the device name a few times to "Firefox Preview auf OnePlus 7T Pro McLaren Edition". But every few days when I look in the sync settings the device name is "Firefox Preview auf OnePlus HD1913" again.

I don't have STR. After changing the name, removing Firefox Preview from the Android recent apps screen and having a look in the sync settings the new name is still displayed. So I don't know when exactly it happens that Firefox Preview forgets the new name.

I don't know if it's important but I don't use the Nightly builds from Google Play Store, I compile the latest version from master branch (almost) every day with Android Studio.

### Device information

* Android device: OnePlus 7T Pro McLaren Edition / Android 10
* Fenix version: master branch revision fe17e2acbdbd94018ad506d38542c5e5d2b0fa93

**Comment by ekager** [comment]
If you change the device name, wait a few seconds, and then sync, does the device name change back at that point? Or is it only after some time? 

On a new device name sync error/failure, we still update the UI with the "new name" but it will be lost on syncing.

**Comment by cadeyrn** [comment]
I waited a few minutes, triggered a sync, waited a few minutes again and Firefox Preview still has the new name. Unfortunately I don't have really useful information to reproduce the issue. I only know that I noticed this behaviour not for the first time. I am not very often in the sync settings. This makes it hard to find steps to reproduce.
