### ISSUE TITLE
[Bug] bad value for "verified by"

### ISSUE THREAD

**Issue by cadeyrn** [mozilla-mobile/fenix#8247]
### Steps to reproduce

1. open a website with HTTPS protocol
2. press on the padlock icon in the address bar

### Expected behavior

Human readable value for "Verified by", for example "DigiCert Inc" as seen in the screenshot in #8021.

### Actual behavior

With GitHub as an example the string ist:

"Verified By: CN=Digicert SHA2 Extended Validation Server CA,OU=www.digicert.com,O=DigiCert Inc,C=US"

![Screenshot_20200208-133006](https://user-images.githubusercontent.com/1100614/74085343-76547980-4a78-11ea-9dbd-d954c71f522d.jpg)

/cc @kglazko 

### Device information

* Android device: OnePlus 7T Pro McLaren Edition / Android 10
* Fenix version: master branch revision fe17e2acbdbd94018ad506d38542c5e5d2b0fa93

**Comment by kglazko** [comment]
Is this only happening on Github or other sites (at the time of the PR push I did not see this behavior on other sites like Reddit and BBC and Yahoo!). On the Fenix side we are only grabbing the value provided by Android Components for the verifier. I’m wondering if this was a change or only certain sites have this extended verifier?

**Comment by cadeyrn** [comment]
It also happened on other sites like kicker.de, camp-firefox.de, mozilla.org or microsoft.com. I also see this on the mentioned sites reddit.com, bbc.com and yahoo.com

**Comment by kglazko** [comment]
Sounds like a regression then because it wasn’t happening previously. Is there a commit or change to AC we can trace this back to?

**Comment by kglazko** [comment]
I noticed that this commit referenced certificate authorities that break into a new line https://github.com/mozilla-mobile/fenix/commit/a42ad7603bdc6ffb906bfb4fabfa2dcf275e53b8. Are long certificate names expected and known? @boek

**Comment by boek** [comment]
@kglazko the very first website I loaded had a certificate name that went off the edge of the screen. Not sure how common though maybe I just got unlucky 😹

**Comment by boek** [comment]
So I don’t think I changed the value of what was being displayed! I can take a look

**Comment by kglazko** [comment]
Confirmed that these values were changed in GV, waiting to find out if they will be parsed in AC or if a fix on our side will be needed to display them correctly.

**Comment by cadeyrn** [comment]
This is fixed. /cc @kglazko

(I don't see a commit referencing this issue. Was there another change in GV?)
