### ISSUE TITLE
[Bug] There should be no "Verified By:" string if there is no value

### ISSUE THREAD

**Issue by cadeyrn** [mozilla-mobile/fenix#8248]
### Steps to reproduce

1. open a website with HTTP and not HTTPS.

### Expected behavior

No "Verified By:" string

### Actual behavior

There is a "Verified By:" string and nothing else after the ":". This looks wrong. I guess we don't the line at all.

![Screenshot_20200208-133105](https://user-images.githubusercontent.com/1100614/74085483-a4868900-4a79-11ea-94bf-80b895fff471.jpg)

Also note the green icon. In the discussion of #8021 it was said that changing the icon for insecure connections will be a follow-up. But the screenshot in #8021 show a red icon, not the green icon for secure connections, so maybe there is still another bug? I am asking here before opening another issue because I am not sure if this expected at this point. Let me know if a new issue should be opened or not. Thanks!

/cc @kglazko 

### Device information

* Android device: OnePlus 7T Pro McLaren Edition / Android 10
* Fenix version: master branch revision fe17e2acbdbd94018ad506d38542c5e5d2b0fa93

**Comment by kglazko** [comment]
Yes @cadeyrn the green icon  is indeed a bug. I filed a PR for it.

**Comment by kglazko** [comment]
I referenced this ticket but please feel free to file another one and I can change my PR title.

**Comment by softvision-miralobontiu** [comment]
This is not fixed yet. Verified on the latest Nightly build from 2/14 (#20450606, #20450607) with OnePlus 5T (Android 9), and Sony Xperia Z2 (Android 6.0.1).
The Insecure Connection globe is now red, but the "Verified by:" text is still displayed.

![Screenshot_20200214-084914](https://user-images.githubusercontent.com/40694158/74508669-40941280-4f08-11ea-8882-be1d29fb6719.png)

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly Build #20830607 from 3/23`** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S6 (Android 7)
• OnePlus A3 (Android 6.0.1)

►Screenshots
![verif](https://user-images.githubusercontent.com/51314259/77290390-c4e66c00-6ce4-11ea-81bf-8a3f9bea4171.png)
