### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by dinesh0430** [mozilla-mobile/fenix#8253]
Firefox Preview 
## Expected behavior
Swipe to close the tab closed message, atleast disappear after few seconds.

### Actual behavior
We are forced to press undo button on tab closed message to close the tab closed message.

### Device information
* Firefox Preview: 3.2.1
* Android device: Xiaomi MI A3

**Comment by ekager** [comment]
This is fixed in master. Closing as dupe of #7825
