### ISSUE TITLE
Provide an option to close the tab when going back to the home screen

### ISSUE THREAD

**Issue by Standard8** [mozilla-mobile/fenix#8254]
### Why/User Benefit/User Problem

This was default for a while, until product decided to change it as [noted here](https://github.com/mozilla-mobile/fenix/issues/6620#issuecomment-571732037).

One of my frequent work flows is that I have items saved in a collection. As a result I:

* Click on an item in my collection.
* Read it
* Go back to the homepage (by pressing the back button)
* Click on the next item in the collection.

The current implementation of "saving" new tabs each time I go back to the home screen by pressing the back button, means I end up with various tabs I don't want.

The user benefit is that it does what I expect, and I don't have to manually scroll back up and close each of the tabs (there's also no easy close all button, unlike in private mode). That's extra swiping that I don't want to do.

I could leave those tabs open, and visit them later, but then I would have to reload them (which is even harder to do), and what would be the point of having a collection in that case?

Although I've mainly discussed about using collections here, I also want to do the same for when I use the address bar to enter a url or something and then go back - I want to have that tab closed - I've gone back, therefore I'm done, I don't want it any more.

### What/Requirements

* Provide a preference to allow closing of tabs when going back to the home screen.

### Acceptance Criteria (how do I know when I’m done?)

* An option is available for closing tab preferences.
* When it is turned on, after visiting a site from the address bar or a collection, and going back to the home screen, the tab is closed.
* When it is turned off, after visiting a site from the address bar or a collection, and going back to the home screen, the tab stays opened.

**Comment by Smaehtin** [comment]
Yes, please. The current behavior is really unintuitive and inconsistent.
Navigating back from a tab that was opened by the "Open link in new tab" action *does* close the tab, but navigating back from a tab that was opened from the homepage does not close the tab. This inconsistent behavior is really confusing and annoying.

**Comment by liuche** [comment]
I'm actually going to dupe this to #13775
