### ISSUE TITLE
[Bug]Top/bottom icons from the Onboarding screen are the same as theme modes

### ISSUE THREAD

**Issue by sv-sdeiac** [mozilla-mobile/fenix#8258]
### Prerequisites
Make sure that you have a fresh install or a clear data profile

## Steps to reproduce
1. Scroll the onboarding screen till you reach the "Take a position" card;
2. Watch the icons from the Top/Botton options.
 
### Expected behavior
There are suggestive icons for the top/bottom option for the toolbar.

### Actual behavior
There is an identical icon like on the Theme card.

### Device information

* Android device: Samsung Galaxy S8 (Android 9), Motorola Moto G6 (Android 8).
* Fenix version: Firefox Preview Nightly 2/10 #20410605.
![top](https://user-images.githubusercontent.com/40264165/74138459-52b93c80-4bfa-11ea-9c6d-89691a3eb5c8.png)

**Comment by ekager** [comment]
Should be fixed by #8260

**Comment by sv-sdeiac** [comment]
Verified as fixed using the latest version of Firefox Preview Nightly 2/11 #20420610.

Devices:
- Motorola Moto G6 (Android 8);
- Samsung Galaxy S8 (Android 9);
- Google Pixel 3 (Android Q).
