### ISSUE TITLE
[Bug]uBlock Origins Improperly displayed "Remove" button in landscape mode

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#8259]
## Prerequisites
Have uBlock Origins installed.

## Steps to reproduce
1. From the Add-ons manager tap and open uBlock.
2. Rotate the device in landscape mode.
3. Check the position of the "Remove" button

### Expected behavior
The "Remove" button should be properly displayed.

### Actual behavior
Depending on the device used, the "Remove" button is cut off or isn't displayed at all.

### Device information

* Android device: 
• Google Pixel 3XL (Android 9)
• Google Pixel 3a (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Sony Xperia Z5 (Android 7.0.0)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

* Fenix version: Nightly #20410606 from 2/10

### Notes
✔️ Not reproducible on Google Pixel 3a XL (Android 10)

►Screenshot Huawei Mate 20 Lite
![rsz_screenshot_20200210-114319](https://user-images.githubusercontent.com/51314259/74138810-edb21680-4bfa-11ea-90d9-48ebad5a388b.jpg)

►Screenshot OnePlus A3 
![rsz_screenshot_20200210-114303 (1)](https://user-images.githubusercontent.com/51314259/74138946-2ce06780-4bfb-11ea-9bb6-1f3686982cc5.png)

►Screenshot LG Nexus 4 (Android 5.1.1)
![rsz_screenshot_2020-02-13-13-13-13](https://user-images.githubusercontent.com/51314259/74138720-c3f8ef80-4bfa-11ea-94ba-8b0b81d55342.png)

**Comment by psymoon** [comment]
@AndiAJ This is now ready for QA.

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly #20420611 from 2/11`** using the following devices:
• Google Pixel 3a XL (Android 10)
• Google Pixel 3a (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7.0.0)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

On some devices when switching to landscape view the menu is :
✔️ Scrollable (Huawei Mate 20 Lite, OnePlus A3, LG Nexus 4)
✔️ Fits the screen ( Google Pixel 3a,  Samsung Galaxy S7)

► Video from Huawei Mate 20 Lite
![20200211-102608](https://user-images.githubusercontent.com/51314259/74221339-8fe50380-4cba-11ea-98b7-ae80c36d941c.gif)

► Video from Google Pixel 3a
![20200211-102743](https://user-images.githubusercontent.com/51314259/74221389-b145ef80-4cba-11ea-93cf-21d79b088891.gif)
