### ISSUE TITLE
[UX] Dark theme

### ISSUE THREAD

**Issue by lime124** [mozilla-mobile/fenix#826]
User Story:
As a user, I want to select a browser theme that is dark or light so that it can match my default dark or light Android theme or differ from my default theme. 

Acceptance Criteria
User will find enough visual contrast on both light and dark themes because they meet a11y standards
User can change themes between dark and light
User can allow Fenix to select the theme that matches their default Android theme

**Note - this feature is no longer part of Battery Saving. Please see below for placement of Theme in Settings**

**Settings Screen**
https://mozilla.invisionapp.com/d/#/console/16853870/350752852/comments

**Settings –> Theme Screen**
https://mozilla.invisionapp.com/d/#/console/16853870/354021506/comments

**Dark Theme Spec:**
https://mozilla.invisionapp.com/share/JUR46MDQRXF#/screens

**Note: View mock in Inspect Mode and scroll down to the "Components" section. Clicking on individual components will show the CSS.**

**Comment by AmyYLee** [comment]
Invision mock: https://mozilla.invisionapp.com/share/2HQU8SIBKWC

**Comment by lime124** [comment]
i'm not sure why shorlander's label isn't getting applied but he's given the thumbs up

**Comment by colintheshots** [comment]
This looks good!

The one thing I think we're missing is how should a user transition into dark mode and back. Where is the setting and how should the app animate into dark mode? By default, Android redraws everything unless we supply a transition animation like we do with private mode.

**Comment by lime124** [comment]
@AmyYLee

**Comment by AmyYLee** [comment]
@ekager Hi, I've started an invision doc with comments on dark theme edits. I'll keep adding to it tomorrow. Please check resolved for each item once you get to it so I know :-) Thanks!

Dark Theme Edits
https://mozilla.invisionapp.com/share/JYRD2QPUK8R

**Comment by colintheshots** [comment]
This looks good to me. Thanks @AmyYLee. I think we're good to close this ticket.
