### ISSUE TITLE
[Bug] The "Collection renamed" snackbar is set on the middle of the page with Top toolbar

### ISSUE THREAD

**Issue by sv-sdeiac** [mozilla-mobile/fenix#8262]
### Prerequisites
Make sure that you have the Toolbar set to the Top

## Steps to reproduce
1. Create a collection;
2. Rename the collection.

### Expected behavior
A snackbar is displayed on the bottom of the page

### Actual behavior
The snackbar is displayed on the middle of the page

### Device information

* Android device: Samsung Galaxy S8 (Android 9), Nokia 6 (Android 7.1.1).
* Fenix version: Firefox Preview Nightly 2/10 #20410605.
![Screenshot_20200210-141916_Firefox Nightly](https://user-images.githubusercontent.com/40264165/74149798-442a4f80-4c11-11ea-99fc-8b486fec3864.jpg)

**Comment by mcarare** [comment]
Note: Also, when toolbar is on top the snackbar with "tab/ tabs saved" does not appear at all.

**Comment by sv-sdeiac** [comment]
@mcarare There is a bug about your findings. https://github.com/mozilla-mobile/fenix/issues/8107

**Comment by mcarare** [comment]
@sv-sdeiac Thanks! This PR: https://github.com/mozilla-mobile/fenix/pull/8263 should fix them both.

**Comment by sv-sdeiac** [comment]
Hi, I can confirm that this issue is fixed using the latest version of Firefox Preview Nightly 2/13 #20440605.

Devices:
- Samsung Galaxy S8 (Android 9);
- Nokia 6 (Android 7.1.1).
