### ISSUE TITLE
[Bug]Selection circle is displayed behind of the toolbar ETP/security button

### ISSUE THREAD

**Issue by sv-sdeiac** [mozilla-mobile/fenix#8267]
## Steps to reproduce
1. Go to any page(e.g. wikipedia.com);
2. Tap on the ETP shield/lock icon from the toolbar;
3. Observe the selection circle.

### Expected behavior
There is a selection circle over the ETP/security button.

### Actual behavior
The selection circle is displayed behind the button and not in front of it.

### Device information
* Android device: Samsung Galaxy S8 (Android 9).
* Fenix version: Firefox Preview Nightly 2/10 #20410605.

![20200210_151356](https://user-images.githubusercontent.com/40264165/74153339-1812cc80-4c19-11ea-90b2-74571cbe19e1.gif)

**Comment by kbrosnan** [comment]
Similar to #7532.

**Comment by ekager** [comment]
Closing as dupe of https://github.com/mozilla-mobile/fenix/issues/1648
