### ISSUE TITLE
[Bug] Update snackbar for saving to top sites

### ISSUE THREAD

**Issue by topotropic** [mozilla-mobile/fenix#8268]
## Steps to reproduce
1. Open a page
2. Go to the menu and select "Add to top sites"

### Expected behavior
Snackbar says "Added to top sites"

### Actual behavior
Snackbar says "Added to Firefox Nightly home"

**Comment by gabrielluong** [comment]
Got the okay with "Add to top sites!" string from @topotropic via slack

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on **`Fenix Nightly #20500607 from 2/19`** & **`Fenix Beta 4.0.0-beta.1 Build #20500409 from 2/19`** using the following devices:
• Google Pixel 3a (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• OnePlus A3 (Android 6.0.1)

► Video
![20200219-123354](https://user-images.githubusercontent.com/51314259/74827039-598c3180-5315-11ea-81ce-1fef618f90db.gif)
