### ISSUE TITLE
[Bug]uBlock installation status not updated properly

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#8272]
## Steps to reproduce
1. From the Add-ons manager Tap the '+' button and approve the install
2. While the Add-on is downloaded and verified tap again the  '+' button and quickly tap the device back button.
3. Open again the Add-ons manager and wait a couple of seconds
4. Tap on uBlock Origins (the details section is opened)
5. Tap the back button

## Alternative Steps to reproduce
1. From the Add-ons manager Tap the '+' button and approve the install
2. While the Add-on is downloaded and verified tap again the  '+' button and quickly tap the device back button.
3. Open the Add-ons manager and tap again the '+' button and approve the **2nd installation**
4. Tap the device back button 
5. Open again the Add-ons manager

### Expected behavior
**1st scenario** - uBlock should be displayed as installed after re-visiting the Add-ons manager

**2nd scenario** - uBlock should be displayed as installed after re-visiting the Add-ons manager, shouldn't offer the possibility to tap again the '+' (install) button to perform a second install.

### Actual behavior
**1st scenario** - uBlock isn't displayed as installed after re-visiting the Add-ons manager (even if you wait a couple of seconds for an auto-update) 
Only after the user exits the "Details" section uBlock is displayed as installed.

**2nd scenario** - uBlock isn't displayed as installed after re-visiting the Add-ons manager, and offers the possibility to perform a second installation.

### Device information

* Android device: 
• Google Pixel 3XL (Android 9)
• Google Pixel 3a (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Sony Xperia XZ (Android 7.0.0)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

* Fenix version: Nightly #20410606 from 2/10

### Notes

► **1st scenario video**
![20200210-175329](https://user-images.githubusercontent.com/51314259/74169716-6f726600-4c34-11ea-8be9-029407ae2b29.gif)

► **2nd scenario video**
![20200210-175303](https://user-images.githubusercontent.com/51314259/74169646-4d78e380-4c34-11ea-801a-4af574d9a29a.gif)

**Comment by Amejia481** [comment]
@AndiAJ this should be fixed, could you re-test please? :)

**Comment by AndiAJ** [comment]
Hi, I've re-checked this issue on **`Nightly #20420611 from 2/11`** using the following devices:
• Google Pixel 3a XL (Android 10)
• Google Pixel 3a (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7.0.0)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

✔️ **Verified as fixed** for the **1st scenario** - uBlock should be displayed as installed after re-visiting the Add-ons manager

❗ For the **2nd scenario** I've filled #8304 which seems to be a regression of #8167 with a slightly different STR.

**Based on, this I'll close and mark this issue as verified.** 

► Video 1st scenario
![20200211_1138551](https://user-images.githubusercontent.com/51314259/74230915-03444080-4cce-11ea-93f9-17bb8eb5ae9b.gif)
