### ISSUE TITLE
Create shortcuts.xml override for fennecProduction build type 

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/fenix#8273]
Like https://github.com/mozilla-mobile/fenix/issues/7587 for Nightly and https://github.com/mozilla-mobile/fenix/issues/8162 for Beta.

We are overriding shortcuts.xml in different build types because it contains the package name. We need to do the same for the `fennecProduction` flavor.

**Comment by ebalazs-sv** [comment]
I had tested this on the Release Migration build 3/6 from https://github.com/mozilla-mobile/fenix/wiki/Fennec-Migration with Pixel 2 (Android 9) and the "New tab" and "New private tab" options are available when long pressing the Fenix Release icon. These can also be added to the home screen.

**Comment by ebalazs-sv** [comment]
Verified as fixed on Release Migration Build #2015738867 GV 77 from 5/7 with Pixel 2 (Android 9) and Motorola Moto G6 (Android 8). The "New tab" and "New private tab" options are available when long pressing the Fenix Release icon. These can also be added to the home screen.
I will move this to Done. Thanks!
