### ISSUE TITLE
[Bug] Page reload in Firefox preview doesn't remember reader mode

### ISSUE THREAD

**Issue by st3fan** [mozilla-mobile/fenix#8274]
> Taken from https://bugzilla.mozilla.org/show_bug.cgi?id=1612846

User Agent: Mozilla/5.0 (Android 10; Mobile; rv:68.0) Gecko/68.0 Firefox/68.0

Steps to reproduce:

I opened a page. Turned on reader mode. Reloaded the page.

Firefox Preview on Android 3.2.1

Actual results:

The page loaded in normal mode

Expected results:

The page should have loaded in reader mode

**Comment by sflorean** [comment]
This is not reproducible anymore on Firefox Nightly 7/3 with:
- Samsung Galaxy Note 10 (Android 10)
- Xiaomi Redmi Note 8T (Android 9)
- LG G7 FIT (Android 8).
