### ISSUE TITLE
Consider tightening up home screen header spacing

### ISSUE THREAD

**Issue by darkwing** [mozilla-mobile/fenix#8275]
Until we have a tab tray, the home screen is the main collection and tab list space.  To maximize the number of tabs and collections shown, we may want to tighten up the logo / private button space, as it's taking up roughly 1/4 to 1/3 of the space on my large Pixel 4.

![Screenshot_20200210-162030](https://user-images.githubusercontent.com/46655/74170072-f0f4d480-4bf1-11ea-95b8-1e2e9ab06f93.png)

### Device information

* Android device: Pixel 4

**Comment by kbrosnan** [comment]
I have a [Spice Mi-498](https://www.gsmarena.com/spice_mi_498_dream_uno-6683.php) with 480 x 854 pixels, 16:9 ratio (~218 ppi density). It gets 2 tabs on the screen before scrolling is needed to access more tabs.

![Screenshot_20200210-155809](https://user-images.githubusercontent.com/250273/74201511-de44c480-4c1e-11ea-8bd5-c8f56bdae132.png)
