### ISSUE TITLE
Update branding for fennecProduction build type before Release

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/fenix#8278]
Updating the icons in-app.
- [x] App name (should be called Firefox - make sure it doesn't say "Firefox Preview")
- [x] Launcher icons
- [x] Homescreen header
- [x] Widget logo
- [x] About screen (update logo, and references to "Firefox Preview" or "What's new in Firefox Preview")

**Comment by st3fan** [comment]
@liuche i assigned this one to you just to have an assignee on our board ... feel free to change of course.

**Comment by liuche** [comment]
@shorlander I checked the assets in #6610 where the original branding assets were added. However, since we made the branding smaller in #9682, I think we need an updated branding from you. Could you upload the new Firefox Release assets here, so we can update them before Release?

**Comment by liuche** [comment]
@pocmo App name doesn't need to be updated, right?

**Comment by liuche** [comment]
Talked to @shorlander on 5/28 and we'll get the new assets for one-line branding. Let him know our timing constraints as well, so @shorlander if you could get that to us within the next 2 weeks that would be ideal!

**Comment by liuche** [comment]
cc @lwa-moz here for branding visibility, and to correct anything I might be missing.

**Comment by pocmo** [comment]
> @pocmo App name doesn't need to be updated, right?

I'm not sure what is is on that release type. I think we need to make sure it is "Firefox" and does not contain "Preview" which I think was the case when I worked on the other build variants?

**Comment by shorlander** [comment]
[Branding-Firefox.zip](https://github.com/mozilla-mobile/fenix/files/4718098/Branding-Firefox.zip)

I included the stacked version of the logo lockup, but I am not actually sure we use it anymore? Should be able to use the single line version for the homescreen and the about screen (ic_logo_wordmark_normal-horizontal.png)

**Comment by ebalazs-sv** [comment]
I had tested this issue on Beta Migration 78.0.1-beta.1 (Build #2015748641) GV 78 from 6/27 with Motorola Moto G6 (Android 8) and the icons in-app are updated, as required in the description, for:
- App name, is called "Firefox";
- Launcher icons;
- Homescreen header;
- Widget logo;
- About screen (update logo, and references to "Firefox Preview" or "What's new in Firefox Preview");

I will leave the qa:needed until this will be tested on the next Release Migration Build.

**Comment by ebalazs-sv** [comment]
Verified as fixed on Release Migration Build 1, GV 79, from 7/3 with Huawei MediaPad M3 lite (Android 7), Motorola Moto G6 (Android 8).

All the in-app icons are updated as required in the issue description:
- App name ( called Firefox - make sure it doesn't say "Firefox Preview");
 - Launcher icons;
 - Homescreen header;
 - Widget logo;
 - About screen (update logo, and references to "Firefox Preview" or "What's new in Firefox Preview");

I will remove the qa:needed label. Thanks!
