### ISSUE TITLE
Setup tokens for fennecProduction builds

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/fenix#8279]
See beta issue: #6899 

- [x] Adjust
- [x] Leanplum
- [x] Sentry
- [x] Firebase
- [x] Digital Asset Links

**Comment by pocmo** [comment]
All tokens are in place now.

**Comment by ebalazs-sv** [comment]
I had tested this on Release Migration build 3/6 from https://github.com/mozilla-mobile/fenix/wiki/Fennec-Migration with Pixel 2 (Android 9) and Fennec Release is replaced by Fenix Release migration build.

**Comment by ebalazs-sv** [comment]
Verified as fixed on Release Migration Build #2015738867 GV 77 from 5/7 with Pixel 2 (Android 9) and Motorola Moto G6 (Android 8). Fennec Release is replaced by Fenix Release migration build. This was also verified in the issue https://github.com/mozilla-mobile/fenix/issues/4873.
I will move this to Done. Thanks!
