### ISSUE TITLE
[Bug] URL requests not returning the correct image path

### ISSUE THREAD

**Issue by GlenSatchwell** [mozilla-mobile/fenix#8280]
## Steps to reproduce
Visiting the following link will redirect you directly to the jpg file of the Instagram image for the size specified in the URL:

[https://instagram.com/p/fA9uwTtkSN/media/?size=t](https://instagram.com/p/fA9uwTtkSN/media/?size=t) 

### Expected behavior
When placed in an <img> tag like so:
`<img src="https://instagram.com/p/fA9uwTtkSN/media/?size=t">`
On page load should fetch the source from the redirected URL but only works when directly navigating to the URL.

### Actual behavior
The image tag fails and resorts to the alt text, whereas the stable Firefox app shows the correct source in the img tag.

This URL is used to avoid URL signature mismatch and will always deliver the most up-to-date version of Instagram post image. 

### Device information

* Android device: OnePlus 3T
* Fenix version: 3.2.1

Thanks!! 😄

**Comment by kbrosnan** [comment]
This is caused by strict tracking protection. Testcase at https://www.kevinbrosnan.net/testcases/8280.html

**Comment by GlenSatchwell** [comment]
Yep! That's it! I have also tested on my private project and works when Tracking Protection disabled. Only an issue for Fenix though as Desktop with TP enabled works fine.

**Comment by kbrosnan** [comment]
This URL is broken by Instagram changes. You now need to use a developer API to get the same behavior.
