### ISSUE TITLE
[Bug] Back navigation broken

### ISSUE THREAD

**Issue by MishterKirby** [mozilla-mobile/fenix#8282]
## Steps to reproduce
Press back button
### Expected behavior
Go back one page
### Actual behavior
Sometimes, it goes back two, sometimes #8180 happens, and sometimes it works properly
### Device information
* Android device: LG Stylo 2
* Fenix version: 3.2.0

**Comment by kbrosnan** [comment]
It would be helpful to know the specific sites you see this on. They may be using one of the [History APIs](https://developer.mozilla.org/en-US/docs/Web/API/History).

**Comment by MishterKirby** [comment]
IIRC, it sometimes happens in Wikipedia.

**Comment by MishterKirby** [comment]
IIRC, it sometimes happens in Wikipedia, and happens in Google when browsing images after you scroll down and tap a related image.

**Comment by sflorean** [comment]
I was able to reproduce this issue, on https://file-examples.com/index.php/sample-images-download/sample-jpg-download/ but only 2/3 times. I wasn't able with other images from Google (opened in new tab).

**Comment by MishterKirby** [comment]
Closing because it has been fixed (and I forgot about closing this issue for about half a year).
