### ISSUE TITLE
[Bug] Private browsing button gets focus on startup with bottom toolbar

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#8285]
When I launch Fenix, the private browsing button is what grabs focus form TalkBack instead of the search bar when I have the toolbar set to "bottom." When it's set to top, it properly focuses the toolbar on startup.

**Comment by sblatz** [comment]
I'm not able to reproduce this. Instead, nothing is grabbing focus. @eeejay can you please confirm this is still happening for you? And is it okay that nothing focuses by default?

**Comment by asadotzler** [comment]
This is still an issue but mitigated by the toolbar on top default for Talkback users. If you manually set the toolbar to be on the bottom and restart Fenix, you'll see the behavior that @eeejay notes. This is an accessibility P3. The feature is available and works in its default configuration but focus is inconsiderate for the alternative toolbar placement which is available in Settings UI.

**Comment by Diana-Rus** [comment]
Reproducible with Samsung Galaxy S9 (Android 8) on Nightly 9/7
