### ISSUE TITLE
Content process is created on demand, introducing a 180ms+ stall

### ISSUE THREAD

**Issue by acreskeyMoz** [mozilla-mobile/fenix#8291]
## Steps to reproduce
Launch Firefox Preview
Enter a search term or a URL in the URL bar, followed by the enter key

### Expected behavior
The Content process is created at some point during the url entry so that it is available when the url is finalized.

### Actual behavior
The Content process is created after the user hits enter.

In this profile from a Pixel 3, there was at least a 180ms delay after the key event:
https://perfht.ml/2H8gSkh

Bug originally logged against Geckoview:
https://bugzilla.mozilla.org/show_bug.cgi?id=1614486

### Device information
Profile is from  Pixel 3

* Android device: Seeing this on all devices (Pixel 3, Moto G5)
* Fenix version: 73.0b13 (PlayStore, Feb 10)

**Comment by mstange** [comment]
Snorp added info on the bug:
> The easiest solution here is for Fenix to create a `GeckoSession` as soon as it knows it needs one (e.g., entering the urlbar from the home screen). This will cause a content process to be created if there isn't one available.

**Comment by acreskeyMoz** [comment]
It looks like the content process used to be preloaded: https://github.com/mozilla-mobile/fenix/issues/3588

**Comment by snorp** [comment]
Right, preloading could also help, but it doesn't fully start the content process. It just starts the `Service` and loads the libraries, which is probably doesn't help *that* much.

**Comment by mcomella** [comment]
Triage: assign to Christian to hand-off to a-c & GV teams to optimize the implementation.

**Comment by csadilek** [comment]
@pocmo and I chatted about this more: We could create a `GeckoSession` right away when the engine is created and hold it there until it's first needed. This seems quite hackish though, as it makes assumptions on implementation details. Is doing this once enough i.e. is there ever only one content process and should we have to know about this?

@snorp is doing this once guaranteed to be enough? Any API call we could add/introduce to make this easier? When we introduce the speculative connect call (in https://github.com/mozilla-mobile/fenix/issues/7863) would that help here as well?

**Comment by snorp** [comment]
There will be more content processes, but you don't really need to care about that. It doesn't seem like as much of a hack if you think of it more as speculatively creating the `GeckoSession`.

Speculative connect doesn't help because that doesn't spin up all of the necessary bits to create a `GeckoSession`. I think we could probably add speculative `GeckoSession` creation in all of the places we do a speculative connect (so here in urlbar and also intents).

**Comment by csadilek** [comment]
> I think we could probably add speculative GeckoSession creation in all of the places we do a speculative connect...

OK, that sounds good, I will give this a try as I plan to work on https://github.com/mozilla-mobile/fenix/issues/7863 anyway.

**Comment by csadilek** [comment]
@acreskeyMoz The fixes for this landed in A-C and Fenix master now and should go out in next Nightly. I've verified that a gecko session is now being created before the user confirm the search terms or URL in the toolbar. Do you want to / have time to verify? I will leave this open for now.

**Comment by acreskeyMoz** [comment]
@csadilek this is looking really good:
https://perfht.ml/2ICbarq
Unfortunately we don't have URL bar performance tests yet, but I can see that the content process is up and ready. It certainly feels snappier to me.

**Comment by csadilek** [comment]
Thanks @acreskeyMoz for verifying!
