### ISSUE TITLE
Show the user's FxA profile picture in the settings menu

### ISSUE THREAD

**Issue by rfk** [mozilla-mobile/fenix#8296]
### Why/User Benefit/User Problem

So that the user has a more familiar and consistent connected experience when signed in on multiple Firefox products, we should show their account profile picture in the "account" section of the settings menu, rather than a generic placeholder image.

### What/Requirements

If the user has set a profile image on their Firefox Account, this info will be available from the account manager. We should use it to display said profile image in their account settings menu.

### Acceptance Criteria (how do I know when I’m done?)

* If the user has set a profile image on their Firefox Account, that image shows in the account settings menu.

* If the user changes the profile image on their Firefox Account, the image shown in the account settings menu updates in a timely manner.

**Comment by kbrosnan** [comment]
@brampitoyo had a new main menu design. Was this considered?

**Comment by brampitoyo** [comment]
@rfk @kbrosnan I totally agree.

If the user has selected a profile image on their Firefox Account –

Then we want to change this generic-avatar icon:
<img width="360" src="https://user-images.githubusercontent.com/51007/74623466-a226dc00-51a9-11ea-8de7-5c2e9743adb6.png">

Into the user’s own avatar:
<img width="360" src="https://user-images.githubusercontent.com/51007/74623491-b8349c80-51a9-11ea-8844-2163e8d80e20.png">

**Comment by sv-sdeiac** [comment]
Hello, I can confirm that the avatar is now displayed in the settings menu but it doesn't update after changing it. For this issue, I created a ticket #9097 to track this problem.

Devices:
- Google Pixel (Android Q);
- Samsung Galaxy Note 10 (Android 9);
- Nokia 6 (Android 7.1.1).

Build: Firefox Preview Nightly 3/11 #20710604.
