### ISSUE TITLE
[Bug] Restore tab popup doesn't close until browser restart

### ISSUE THREAD

**Issue by guillotjulien** [mozilla-mobile/fenix#8298]
## Steps to reproduce
Close à tab
### Expected behavior
Popup disapear after some time
### Actual behavior
Popup doesn't disapear even when switching tab. Need to fully close app in order to make popup disapear.

![Screenshot_2020-02-11-08-55-26-876_org mozilla fenix](https://user-images.githubusercontent.com/33655232/74219527-58bc2580-4cad-11ea-9d9e-d02fdb4ecc0c.jpg)

### Device information

* Android device: Xiaomi mi 9T (redmi k20)
* Fenix version: 3.2.1

**Comment by cadeyrn** [comment]
Duplicate of #7799 and already fixed in the Nightly version.

You can press the "ANNULER" button in the snackbar to close it. It won't undo the action and you don't have to restart the browser.

**Comment by guillotjulien** [comment]
Whops, sorry for the dup, I should have searched better than that. Thanks!
