### ISSUE TITLE
[Bug] Tracking protection option is not saved when changing theme/browsing toolbar

### ISSUE THREAD

**Issue by vladbencovici** [mozilla-mobile/fenix#8299]
Steps to reproduce
1. Install Fenix.
2. First launch the app.
3. Select 'Standard' option from Protect yourself card.
4. Change theme/browsing toolbar position.
5. Observe.

Expected behavior
The Tracking Protection setting should remain set to "Standard" after changing the theme/browsing toolbar position from the Onboarding screen

Actual behavior
The Tracking Protection setting is set back to "Strict" after changing the theme/browsing toolbar position from the Onboarding screen

Device information

* Android device: • Google Pixel 3a XL (Android 10)
• Google Pixel 3a (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7.0.0)
• OnePlus 2, (Android 6.0.1)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

* Fenix version: Fenix Nighltly #2042611 from 2/11

### Notes:

► Video

![20200211-123403](https://user-images.githubusercontent.com/51314259/74229721-9a5bc900-4ccb-11ea-8c40-5175edf94f79.gif)

**Comment by sv-sdeiac** [comment]
Verified as fixed using the latest version of Firefox Preview  2/12 @20430606.

Devices:
- Motorola Moto G6 (Android 8);
- Samsung Galaxy S8 (Android 9).
