### ISSUE TITLE
Bottom address bar covers floating bottom website content

### ISSUE THREAD

**Issue by kbrosnan** [mozilla-mobile/fenix#830]
## Steps to reproduce
* Open https://www.wunderground.com
* Tap full forecast
* Scroll up and down

### Expected behavior
* Address bar does not cover website bottom bar
* [Today | Hourly | 10-Day | Calendar |>]

### Actual behavior
* Address bar interacts poorly website content

### Device information

* Android device: All
* Fenix version: March 1

Websites with similar problems
* https://maps.google.com - quick actions bar
* https://www.tesla.com - when buillding a car

**Comment by pocmo** [comment]
Related: https://github.com/mozilla-mobile/reference-browser/issues/464

**Comment by vesta0** [comment]
Duplicate of #552
