### ISSUE TITLE
[Bug] The site certificate information is barely visible with dark theme

### ISSUE THREAD

**Issue by softvision-miralobontiu** [mozilla-mobile/fenix#8300]
## Steps to reproduce
1. Go to Settings - Theme and set the dark theme.
2. Exit Settings and open cnn.com.
3. Tap on the lock icon and observe the site certificate information.

### Expected behavior
The site certificate information is visible no matter which theme is used.

### Actual behavior
The site certificate information is barely visible when using dark theme.

### Device information
* Android device: Google Pixel (Android 10), and Huawei P9 Lite (Android 7)
* Fenix version: 2/11 Nightly build 

![connection](https://user-images.githubusercontent.com/40694158/74228544-55cf2e00-4cc9-11ea-889a-d6f83e546435.png)

**Comment by sv-sdeiac** [comment]
Hi, I can confirm that this issue is fixed using the latest version of Firefox Preview Nightly 5/4 #21251804.

Devices:
- Google Pixel 3 (Android 10);
- Samsung Galaxy Note 8 (Android 9);
- LG G7 fit (Android 8.1).
