### ISSUE TITLE
'Close app' clean history cookies by close app from 'App switcher'

### ISSUE THREAD

**Issue by macer22** [mozilla-mobile/fenix#8303]
There is an option inside the settings do delete history cookies by clicking the close button,
thats not fluid behauvior it should be a setting by closing the app from app switcher to clean evrything.
Not all close the app by clicking inside settings to close the app almost evrybody close a app by swiping up.

Firefox Preview Nightly Android

**Comment by ekager** [comment]
Unfortunately, we can't do this because we can't get reliable lifecycle callbacks to know when the user has swiped up to kill the app.
