### ISSUE TITLE
[Bug]The user can initiate multiple installations of Ublock Origins 

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#8304]
## Steps to reproduce
1. Navigate to the Add-ons manager
2. Tap the '+' (install button) and confirm the addition
3. While the installation and verification is performed, tap the device back button
4. Open again the Add-ons manager
5. Tap the '+' (install button) and confirm the addition

### Expected behavior
The user should not be able to initiate multiple installs of the same Add-on.

### Actual behavior
The user can initiate at least two installs of the same Add-on. (depending on the device used, for instance on the LG Nexus 4 the user can initiate 6 consecutive installs of uBlock )

### Device information

* Android device: 
• Google Pixel 3a XL (Android 10)
• Google Pixel 3a (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7.0.0)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

* Fenix version: Nightly #20420611 from 2/11

### Notes
Seems to be a regression of [#8167](https://github.com/mozilla-mobile/fenix/issues/8167) with a slightly different STR.

► Video from Huawei Mate 20 Lite 
![20200211_111821](https://user-images.githubusercontent.com/51314259/74227031-44385700-4cc6-11ea-9ced-433580a97684.gif)

► Video from LG Nexus 4
![20200214-134546](https://user-images.githubusercontent.com/51314259/74230220-9d0aee00-4ccc-11ea-993c-58bdfe154f15.gif)

**Comment by csadilek** [comment]
@AndiAJ we landed a fix for this today to make sure the add-ons screen always shows the correct state. Can you please verify again? 

Note that an ideal UI would have some persistent progress indicator of installation which we could show instead when coming back, but we don't have any support for that in GV/A-C and it's out of scope right now. I will discuss with UX and file a follow-up as needed.

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest `Nightly #20430607 from 2/12 `using the following devices:
• Google Pixel 3a XL (Android 10)
• Google Pixel 3a (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7.0.0)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

► Video from Huawei Mate 20 Lite
![20200212-111229](https://user-images.githubusercontent.com/51314259/74320202-df920080-4d88-11ea-94d5-96447cf75c70.gif)
