### ISSUE TITLE
Rearrange Top Sites items

### ISSUE THREAD

**Issue by macer22** [mozilla-mobile/fenix#8305]
### User Story
As a user, I want to be able to rearrange Top Sites, so that I can choose the order that best fits my browsing preference. 

### Acceptance Criteria
- I can rearrange the order of a top site.

Update from UX:
Order can be changed by long pressing (menu appears) and then moving the item (menu disappears, and item can be moved to a different spot)

**Comment by gabrielluong** [comment]
I am gonna break this down because this is blocked by a lot of AC work.

**Comment by kbrosnan** [comment]
https://github.com/mozilla-mobile/fenix/issues/20068 has more info.
