### ISSUE TITLE
[Logins] Editing email in Login capture panel crashes Fenix

### ISSUE THREAD

**Issue by AmyYLee** [mozilla-mobile/fenix#8307]
Steps to reproduce:

Go to ebay.com
Sign-in with credentials
When Fenix asks if you want to save login, tap in email text box to edit email address

Expected:
You're able to edit your email address in the text field 

Actual:
Fenix freezes (see below screenshot)

![image](https://user-images.githubusercontent.com/5992746/74244830-0cbeb000-4cb0-11ea-933b-ba312eed66e0.png)

**Comment by boek** [comment]
Freezes on a pixel 3.

**Comment by ekager** [comment]
Will be fixed by https://github.com/mozilla-mobile/android-components/pull/5898

**Comment by sv-sdeiac** [comment]
Verified as fixed using the latest version of Firefox Preview 2/12 @20430606.

Devices:
- Motorola Moto G6 (Android 8);
- Samsung Galaxy S8 (Android 9).
