### ISSUE TITLE
[Bug] The PB button from the onboarding card is not working

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/fenix#8309]
## Prerequisites
Have a fresh install.
## Steps to reproduce
1. Launch Fenix.
2. Scroll down until the `Browse privately` onboarding card.
3. Tap on the `PB` icon.
### Expected behavior
The PB button from the onboarding card should work.
### Actual behavior
The PB button from the onboarding card is not working.

### Device information
* Android device: **Samsung Galaxy S10+(Android 9)**
* Fenix version: **Latest Nightly from 2/11.**

### Notes
The PB button is at the top and if a new user will scroll down and reach the PB onboarding card(the default PB button will not be displayed) and some users might think that the PB button from the onboarding should work.
Note that the PB button from the top is working correctly.

![20200211-165006](https://user-images.githubusercontent.com/42831109/74247996-98a3fc80-4cef-11ea-849b-25ba9dba91a6.gif)

**Comment by liuche** [comment]
@mheubusch and @apbitner any thoughts on this?

**Comment by apbitner** [comment]
The icon in the onboarding card was never meant to be tappable, so this is not a bug. 

@mheubusch perhaps we should change the copy to "Tap the [mask] icon above." to avoid such confusion?

**Comment by AndiAJ** [comment]
**Not reproducible** anymore on the latest on the latest **`Nightly Build 201111`** using the following devices:
• Google Pixel 3a (Android 11)
• Huawei Mate 20 Lite (Android 10)
• OnePlus A3 (Android 6.0.1)
