### ISSUE TITLE
Sub-domain used for favicon tile

### ISSUE THREAD

**Issue by kbrosnan** [mozilla-mobile/fenix#831]
## Steps to reproduce
* Visit https://3.tesla.com/model3/design
* tap on the tabs button

### Expected behavior
* 'T' used for site icon

### Actual behavior
* '3' used for site icon

### Device information

* Android device: All
* Fenix version: March 1

**Comment by ekager** [comment]
In #745 we pulled in the browser-icons component in AC which will provide us with real favicons from the sites when completed on the AC side

**Comment by kbrosnan** [comment]
Will this current state be the fallback for when the site does not provide a favicon or we have discarded the favicon cache?

**Comment by ekager** [comment]
I believe this will be the fallback generator. It currently tries to find a representative letter but it only looks for the most common prefixes 
https://github.com/mozilla-mobile/android-components/blob/3ed043ccf5c61114cb19a674dcc397b818595321/components/support/ktx/src/main/java/mozilla/components/support/ktx/android/net/Uri.kt#L13-L23

**Comment by colintheshots** [comment]
We're still waiting for the component to load the actual Favicons. Then this will be moot.

**Comment by vesta0** [comment]
Won't change behaviour - will use what lands in components.
