### ISSUE TITLE
[Bug]Fail to remove or uninstall uBlock 

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#8310]
## Steps to reproduce
1. Install uBlock Origin
2. Right after the installation is completed open uBlock
3. Disable it globally and quickly tap "Remove"

### Expected behavior
Based on the confirmation snackbar uBlock should be successfully uninstalled.

### Actual behavior
The uninstall confirmation snackbar is displayed but in fact Ublock isn't actually removed.
The user can open uBlock, and when tries to enable/disable it or remove it a failed message is displayed.
If you close and re-open Fenix, uBlock's status is properly updated (removed)

### Device information

* Android device: 
• Google Pixel 3a XL (Android 10)
• Google Pixel 3a (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7.0.0)
• OnePlus A3 (Android 6.0.1)

* Fenix version: Fenix Nighltly #2042611 from 2/11

### Notes
❗ Wasn't able to reproduce it on LG Nexus 4 (Android 5.1.1)

► Video
![20200211-164305](https://user-images.githubusercontent.com/51314259/74251491-e53e0680-4cf4-11ea-9720-f5a28ddd7ed3.gif)

**Comment by csadilek** [comment]
@AndiAJ we landed a fix today to prevent this inconsistent state when quickly tapping enable and uninstall. Can you verify :)

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest `Nightly #20430607 from 2/12` using the following devices:
• Google Pixel 3a XL (Android 10)
• Google Pixel 3a (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7.0.0)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

► Video
![20200212_143234](https://user-images.githubusercontent.com/51314259/74335389-ca2acf80-4da4-11ea-8856-fb1bf41da354.gif)
