### ISSUE TITLE
Add the possibility to delete more top-sites at once

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/fenix#8311]
### Why/User Benefit/User Problem
As a Fenix user, I want to be able to remove more top-sites at once.
### What/Requirements
When a long tap is performed on a top-site it gives the option to multi-select other top-sites and then delete them.
### Acceptance Criteria (how do I know when I’m done?)
The possibility to delete more top-sites is implemented.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-15652)

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813924

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
