### ISSUE TITLE
[Bug] Flash of "THIS TIME, SEARCH WITH:" as the URL bar transitions from bottom to top when tapped

### ISSUE THREAD

**Issue by Cheap-Skate** [mozilla-mobile/fenix#8315]
## Steps to reproduce
Set bottom toolbar
In any tab, tap the URL to do a search
The toolbar moves to the top of the screen

### Expected behavior
No text appears in main part of screen.

### Actual behavior
The text "THIS TIME, SEARCH WITH:" flashes very briefly (a few frames?) just below the top toolbar.

### Device information
* Android device: Galaxy A40, Android 9.0.0
* Fenix version: Today's

**Comment by sv-sdeiac** [comment]
Verified as fixed using the latest version of Firefox Preview Nightly 2/24 #20550606.

Devices: 
- Motorola Moto G6 (Android 8);
- Samsung Galaxy S8 (Android 9).
