### ISSUE TITLE
Make bookmarks swipeable from the sites of the screen 

### ISSUE THREAD

**Issue by estUser1** [mozilla-mobile/fenix#8322]
Lightning browser does it and I think it's an easy way to access your bookmarks :)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-15658)

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812717

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
