### ISSUE TITLE
[Bug] Homescreen tabs favicons get applied to wrong tabs when scrolling quickly

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#8325]
## Steps to reproduce
- Load tabs tray with many tabs
- Scroll quickly and stop (this may take a few tries)

### Expected behavior
Favicons appear in the correct tabs

### Actual behavior
Favicons appear in incorrect tabs. In the attached screenshot, notice that The Economist has a Google favicon:

![Screenshot_20200205-145555](https://user-images.githubusercontent.com/759372/74287835-349f2980-4d2b-11ea-97f0-6c34fd9d8692.png)

### Device information

* Android device: P2
* Fenix version: Not sure, something before Nightly 200210

---

The cause may be that we're not cancelling our async favicon load jobs when the views inside the RecyclerView are recycled so in progress jobs end up inserting images into an outdated view.

**Comment by topotropic** [comment]
@mcomella is this still an issue with the dedicated tab tray? Thanks

**Comment by mcomella** [comment]
I can no longer reproduce in the new tray.
