### ISSUE TITLE
[Bug] "No internet connection" page is sometimes missing header icon

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#8328]
## Steps to reproduce
Unknown. I got the "No internet connection" page, maybe switched a tab or backgrounded/foregrounded the app and the icon was missing.

### Expected behavior
Header icon appears

### Actual behavior
Header icon is missing

![Screenshot_20200207-130324](https://user-images.githubusercontent.com/759372/74288099-d888d500-4d2b-11ea-8e79-6127917f24ab.png)

### Device information

* Android device: P2
* Fenix version: Unknown; something before Nightly 200212

**Comment by darkwing** [comment]
I turned off WiFi and I see the following screen, which does not display the Advanced button:

![Screenshot_20200212-023811](https://user-images.githubusercontent.com/46655/74298177-9a30ed00-4d0e-11ea-8aa2-59416d3b0ed0.png)

Am I missing any STR?

**Comment by TitanNano** [comment]
@darkwing the advanced button is actually only for SSL / TLS errors, but there was a bug and it showed on every error page. It has been fixed now, I think.
