### ISSUE TITLE
[Bug] "No internet connection" page "Advanced" menu unexpectedly contains SSL text

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#8329]
## Steps to reproduce
- Open a page without a network connection
- Open "Advanced" menu

### Expected behavior
Advanced menu text matches no internet connection

### Actual behavior
Advanced menu matches SSL error text

![Screenshot_20200207-130324](https://user-images.githubusercontent.com/759372/74288194-1259db80-4d2c-11ea-801d-63b146819155.png)

### Device information

* Android device: P2
* Fenix version: Unknown; something before Nightly 200212

**Comment by cadeyrn** [comment]
This should already be fixed. #8065

**Comment by mcomella** [comment]
I've seen the correct page appearing now so closing works for me.
