### ISSUE TITLE
[Bug] Google Maps shared links don't open

### ISSUE THREAD

**Issue by Baron-Severin** [mozilla-mobile/fenix#8332]
## Steps to reproduce
- Open a Google Maps shared link in Fenix (ex https://maps.app.goo.gl/Z6SG81kebpouBd878)

### Expected behavior
- If Maps is installed, it should launch and show the route
- If not, the route should be shown in Fenix

### Actual behavior
- "Unknown Protocol" error page is shown

### Device information

* Android device: Pixel 2
* Fenix version: v3.2.1

**Comment by sv-sdeiac** [comment]
Hi, I was not able to reproduce your issue using the latest version of Firefox Preview 3.2.1

Devices:
- Samsung Galaxy S8 (Android 9);
- Google Pixel 2 (Android 9).

**Comment by Baron-Severin** [comment]
@sv-sdeiac that's odd, we were able to reproduce on my Pixel 2 and @ekager's Pixel 2 (both of v3.2.1), plus an emulator on master.  Is it possible you used a normal Google Maps link, instead of one of the shorter ones generated using the share button in their app?

![cant-load-maps](https://user-images.githubusercontent.com/13170306/74396389-a8424480-4dc6-11ea-8d37-5beeec989e29.gif)

**Comment by Baron-Severin** [comment]
Closing as dup of https://github.com/mozilla-mobile/fenix/issues/7331
