### ISSUE TITLE
[Bug] Search query text in duckduckgo does not appear in tabs list

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#8333]
## Steps to reproduce
- Make DDG searches in multiple tabs
- Open tabs tray

### Expected behavior
I'm able to distinguish my tabs

### Actual behavior
I'm unable to distinguish my tabs because they have no titles. I expect the title to be the contents of the search, as they are in the desktop app.

![Screenshot_20200212-001425](https://user-images.githubusercontent.com/759372/74288600-1f2aff00-4d2d-11ea-8097-5952caeb4e69.png)

### Device information

* Android device: P2
* Fenix version: Unknown. Something before Nightly 200212

**Comment by kbrosnan** [comment]
This is resolved in the tabs rewrite. Not great but the full url is show for DDG searches.
