### ISSUE TITLE
The home page still has a line above the toolbar

### ISSUE THREAD

**Issue by 90du** [mozilla-mobile/fenix#8338]
![Screenshot_2020_0212_155936](https://user-images.githubusercontent.com/35375370/74318921-0cf6a280-4db9-11ea-9fc5-4f7cb6dc4d46.png)

The home page still has a line above the toolbar, and I want to move the Settings to the left to achieve left and right symmetry

**Comment by cadeyrn** [comment]
@90du: Could you please write in English so that other people can understand you? The translation from Google Translate doesn't make sense to me…

**Comment by sv-sdeiac** [comment]
I can confirm that this issue is reproducible using the latest version of Firefox Preview 2/12 @20430606.

Device: Samsung Galaxy S8 (Android 9).

**Comment by ekager** [comment]
I don't think this is reproducible anymore. #7266 is for removing the line below the toolbar on browser and I think that's the last remaining bug in this category

**Comment by ekager** [comment]
Actually yeah closing for #8212 we don't need to verify this.
