### ISSUE TITLE
[Bug] Dragging objects initially scrolls the window a bit

### ISSUE THREAD

**Issue by Diana-Rus** [mozilla-mobile/fenix#8339]
Issue was created after bugzilla ticket: https://bugzilla.mozilla.org/show_bug.cgi?id=1614736.
Pre-requisites:
- Set the toolbar to be on the top part of the device.

## Steps to reproduce
1. Go to lichess.org.
2. Hamburger menu -> Tools -> Analysis board.
3. Drag to move a piece.

### Expected behavior
Piece is dragged.

### Actual behavior
Screen scrolls for a short amount, then the drag starts.

Note:
- I see this on various other places where you're supposed to drag things.

### Device information
* Android device: Google Pixel 3 XL (Android 9)
* Fenix version: Firefox Preview Nightly 200212 (Build #20430606) GV: 74.0a1-20200210093912

Please check gif:
![20200212-100206](https://user-images.githubusercontent.com/49859863/74315310-d2bcdf00-4d7f-11ea-97c5-5d569a488171.gif)

**Comment by gcp** [comment]
Seems related (or perhaps a dupe) of issue #13422.

**Comment by Mugurell** [comment]
I think this was resolved by https://bugzilla.mozilla.org/show_bug.cgi?id=1633322
@Diana-Rus can you please confirm if this is still reproducing or not for you?

**Comment by gcp** [comment]
This indeed seems to be fixed.

**Comment by Diana-Rus** [comment]
Hello, I rechecked this and it's fixed on Nightly 9/7 with
- Samsung Galaxy S9 (Android 8)
- Google Pixel 3XL (Android 9)

<details closed><summary>GIF Samsung</summary>

![20200907-175945](https://user-images.githubusercontent.com/49859863/92442601-da7b1f80-f1b8-11ea-8685-41a76231d8f9.gif)
</details>
