### ISSUE TITLE
[Bug] Sync does not recognise other devices

### ISSUE THREAD

**Issue by maxcb97** [mozilla-mobile/fenix#8340]
## Steps to reproduce

Update Firefox Nightly on Android to Fenix.
Connect to Firefox Account.
Run a sync on all your devices.

### Expected behavior

Tap device to send tab to desktop.
Right click on tab on desktop to send to mobile.
Go into history window on mobile to see tabs on other devices.
Go into synced tabs sidebar on desktop to see tabs on mobile.

### Actual behavior

Mobile does not see desktops to send tabs to.
Desktop sees device to send tab, but device does not receive tab.
History window on mobile does not show other devices.
Desktop version does not see any of the tabs on the mobile device.

Not that history and bookmarks do still sync, it's just the tab syncing feature that does not work.

### Device information

* Android device: Samsung Galaxy S8, Android 9, Kernel 4.4.111
* Fenix version: Nightly 200210 10:05 Build #2015722195 31.0.0

### Desktop information

* Operating system: Windows 7, Windows 10, tried it on both
* Browser version: Waterfox Classic 2020.01 64-bit

**Comment by LaurentiuApahideanSV** [comment]
Hello,

Regarding synced tabs: this feature is not yet implemented in Fenix and therefore open tabs are not synced between devices. I also tried sending tabs from Firefox Nightly 75.0a1 (2020-02-12) (Desktop) to Firefox Preview Nightly 200210 (Build #2015722195) and vice versa without encountering any problems. Please note that Waterfox is not an official Mozilla product and therefore we don't offer support for it. @maxcb97 Could you please download an official Firefox build and see if you are still encountering problems?

**Comment by sflorean** [comment]
@maxcb97 open tabs are now available on Fenix. Could you please take a look, and check if the issue is still reproducible?

**Comment by maxcb97** [comment]
A part of the issue is fixed.

Currently using Waterfox Classic 2020.07 64-bit on desktop, and testing mobile version Firefox Nightly 200723 build #22050611.
Last version behaving as expected was Nightly 68.5a1.

The desktop can see and access the tabs that are currently open on the mobile device, and vice versa, so that part is now working as expected.

When sharing a tab from the mobile device with the latest nightly, it says that there are no other devices connected, despite there being two other desktops using Waterfox Classic, and one other Android using Firefox Nightly 68.5a1 2020-01-20.

When sharing a tab from another device (Either the other mobile using nightly 68.5a1, or the desktop running Waterfox Classic), they can see the device running the latest nightly, and act as if the tab has been sent, but the tab never shows up on the device.

Also, I notice that when using the standard Android sharing dialogue on a link in another app, and sharing with Nightly, it opens in the browser directly, instead of offering to open, bookmark, or send the link to another device, so sending to another device has to be done from within the app itself. I assume this is expected behaviour?
