### ISSUE TITLE
"Expire History By Days" Type Feature Suggestion

### ISSUE THREAD

**Issue by CharmCityCrab** [mozilla-mobile/fenix#8342]
### Why/User Benefit/User Problem

A poster on Reddit suggested I post this request here after he read a thread I started:

https://www.reddit.com/r/firefox/comments/f2nyx1/

Though an extension exists that does what I am suggesting on desktop and Fennec Firefox, it is not a Mozilla recommended extension and thus not likely to be ported, at least anytime soon, to Fenix, based on a recent announcement about extensions for the platform.

I am not sure how well maintained it is in any event.  There are some apparent bugs with its Fennec implentation, which aren't aren't worth getting into because Fennec in general is going away soon.

At least one other browser has integrated similar behavior into its core browser options (Desktop Vivaldi).  So, I thought it might make sense for Fenix to consider doing the same, perhaps even with an extra feature or two.

### What/Requirements

The desired behavior is to delete history entries on a rolling basis that fall before a user-specified number of days. For example, if you set it to 90 days, you get to keep the last 90 days of history (Calendar days, meaning days where you don't use the browser still count). Then, tomorrow, the history entries 91 days ago automatically get deleted. You can set it for any number of days.  The default would be unlimited. Users would go into the options GUI to enable it and set a desired number of days at that time.

Optionally, the same could be done with cookies, either as part of the same option, or as a separate option, which covers part of the behavior of another non-recommended unlikely to be ported extension.

The goal here is not so much privacy enhancement as to simply allow users to set a user defined time period for which they want history (and possibly more) to be retained and for old stuff to disappear on a rolling basis so it doesn't appear as a suggestion in the URL bar or when browsing through history.  Its a fresh start / live in the moment type optimization.  The user isn't unnecessarily reminded of old problems, etc., and is also able to set a time period limitation for this type of data that the user feels is manageable and makes it easiest to retain what needs to be retained without clutter.

Of course, users who suspect they won't go back to a site for longer than their defined period for deleting history but want it easily available would either bookmark the site or add it to a collection to preserve it that way.

Users who want to preserve all history as history indefinitely would simply not enable this potential option at all.

### Acceptance Criteria (how do I know when I’m done?)

Its done when Fenix has the same as, or more functionality than, the desktop "Expire History By Days" extension- optionally, but not necessarily, with a similar cookie management component.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-15674)

**Comment by kbrosnan** [comment]
Desktop Firefox does not have expire history by days exposed in the settings.

**Comment by manan025** [comment]
I want to work on this issue.

**Comment by SS1113** [comment]
It'd great if history cleared itself after a set period of time such as in a few hours/days/weeks or let them set a custom period.

**Comment by Dunexus** [comment]
As this feature is about history which can be synced with desktop, i think there will be some work needed on desktop to bring the same feature on it as having it activated on fenix will affect desktop history too.

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807111

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
