### ISSUE TITLE
[Bug] Consider changing the sign-in message from "on this phone" with "on this device"

### ISSUE THREAD

**Issue by softvision-miralobontiu** [mozilla-mobile/fenix#8343]
### Prerequisites
1. Use a tablet.
2. Sign-in on Fennec with a valid account.

## Steps to reproduce
1. Open Fenix Nightly with a clean profile.
2. Observe the "Sign-in" card.

### Expected behavior
"You are signed in as ... on another Firefox browser on this device." should be displayed.

### Actual behavior
"You are signed in as ... on another Firefox browser on this phone." is displayed.

### Device information
* Android device: Sony Xperia Z2 (Android 6.0.1)
* Fenix version: 2/12 Nightly build

![Untitled](https://user-images.githubusercontent.com/40694158/74321617-3c8eb600-4d8b-11ea-97b1-c4080b92b976.png)

**Comment by ekager** [comment]
CC @betsymi for feedback!

**Comment by betsymi** [comment]
Good catch! Let's update. Quick Q, will this sign them out from the other browser? Or, will they stay signed in, then ultimately be signed in in two places?

**Comment by cadeyrn** [comment]
@betsymi Could you also have a look at #9709, it's a very similar issue. Thanks!

**Comment by AmyYLee** [comment]
Sounds like UX is resolved. Removing label.

**Comment by sflorean** [comment]
Verified as fixed on Nightly 9/11 with Google Pixel 3 (Android 11).
On Beta 81.1.1-beta.3 the issue can't be verified due to #6521.
