### ISSUE TITLE
[Bug] There is a space below "Download completed" prompt

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/fenix#8344]
## Steps to reproduce
1. Launch Fenix.
2. Turn the device in landscape.
3. Download any file and wait for the download to be completed.

### Expected behavior
There should not be any space below `Download completed` prompt.
### Actual behavior
There is a space below "Download completed" prompt.
### Device information

* Android device: **Samsung Galaxy S7 (Android 7), Sony Xperia Z5 (Android 7)**
* Fenix version: **Nightly from 2/12**

### Notes
**I tried also to reproduce this issue on the following devices but I couldn't:**

• Google Pixel 3a XL (Android 10)
• Google Pixel 3a (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy Tab A (Android 9)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

![Screenshot_20200213-184020](https://user-images.githubusercontent.com/42831109/74321876-b030c300-4d8b-11ea-82f8-01e1bcd9f97e.png)

**Comment by AndiAJ** [comment]
**Not reproducible** anymore on the latest on the latest **`Nightly Build 201111`** using the following devices:
• Google Pixel 3a (Android 11)
• Huawei Mate 20 Lite (Android 10)
• OnePlus A3 (Android 6.0.1)
