### ISSUE TITLE
[Bug]Improperly displayed uBlock Permissions section 

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#8346]
## Prerequisites
uBlock Origins should be installed.

## Steps to reproduce
1. Open uBlocks "Permissions" section
2. Rotate the device in landscape view

### Expected behavior
"Permission" section should be properly displayed

### Actual behavior
Lower part of the "Permission" section is cut off.

### Device information
* Android device: 
• Huawei Mate 20 Lite (Android 8.1.0)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

* Fenix version:  Nightly #20430607 from 2/12

### Notes
❗ Not reproducible on the following devices:
• Google Pixel 3a XL (Android 10)
• Google Pixel 3a (Android 9)
• Samsung Galaxy S7 (Android 7.0.0)

► Video
![20200212-110837](https://user-images.githubusercontent.com/51314259/74325750-d6596180-4d91-11ea-9d57-d8d760719bec.gif)

**Comment by psymoon** [comment]
@AndiAJ This is now scrollable.

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly Build # 20440606 from 2/13`** using the following devices:
• Google Pixel 3a XL (Android 10)
• Google Pixel 3a (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7.0)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

► Video from Huawei Mate 20 Lite
![20200213-122756](https://user-images.githubusercontent.com/51314259/74425562-927f5e80-4e5c-11ea-9c5e-eed0112db35d.gif)
