### ISSUE TITLE
[Bug] No shadow for top toolbar

### ISSUE THREAD

**Issue by topotropic** [mozilla-mobile/fenix#8349]
## Steps to reproduce
Select top toolbar in settings, go to home

### Expected behavior
Toolbar has shadow

### Actual behavior
There's no shadow

**Comment by vesta0** [comment]
@topotropic I have been playing around with top/bottom toolbar but I can't see a shadow in either use case. Could you provide a screenshot?

**Comment by AmyYLee** [comment]
@topotropic to follow-up

**Comment by topotropic** [comment]
not sure what this was about, I'll close it
