### ISSUE TITLE
[Bug] apk files missing in latest release(-s)

### ISSUE THREAD

**Issue by rakshazi** [mozilla-mobile/fenix#8350]
## Steps to reproduce

1. Go to project releases page: https://github.com/mozilla-mobile/fenix/releases
2. Check assets for latest release(-s)

### Expected behavior

APK files should be attached to each release

### Actual behavior

No APK files attached to latest release(-s)

### Device information

N/A

### Comments

Hello, devs

thank you for amazing work!

Could you provide apks for each release, please? I use https://gitlab.com/rfc2822/fdroid-firefox f-droid repo which uses only released by developers apks, so I can't update from 3.2.0 to new version.

**Comment by AaronMT** [comment]
We do a staged roll-out before publishing APKs. As far as I'm aware neither are at 100% which is a requirement for posting the builds. The APK is available from automation in the meantime if you want: https://firefox-ci-tc.services.mozilla.com/tasks/index/project.mobile.fenix.v2.production/latest

**Comment by gaby2300** [comment]
I am sorry but some time ago there where .apks for every release, why not
now?


Many thanks!
Gabriela
QA Mozilla Hispano Team Responsible

**Comment by palbr** [comment]
If I understand https://bugzilla.mozilla.org/show_bug.cgi?id=1614762#c1 correct, pushing Firefox Fenix APKs to archive.mozilla.org is planned, but it depends on: https://bugzilla.mozilla.org/show_bug.cgi?id=1614763

So everybody, wanting Fenix APKs, please vote for https://bugzilla.mozilla.org/show_bug.cgi?id=1614763  ;)
