### ISSUE TITLE
[Bug] Opened tabs are not displayed when trying to share them in landscape mode

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/fenix#8353]
## Steps to reproduce
1. Launch Fenix.
2. Open 3 or more websites.
3. Rotate the device in landscape mode.
4. Tap on the 3 dot menu and select `share tabs`.
### Expected behavior
The share section is scrollable and the user can check what tabs are shared.
### Actual behavior
The opened tabs are not displayed when trying to share them in landscape mode.
### Device information

* Android device: **SamsungGalaxy S10+ (Android 9).**
* Fenix version: **Nightly from 2/12.**

![20200212-162457](https://user-images.githubusercontent.com/42831109/74344056-aff8ed80-4db4-11ea-9468-f52396957a2a.gif)

**Comment by AndiAJ** [comment]
**Reproducible** on the latest on the latest **`Nightly Build 201111`** using the following devices:
• Google Pixel 3a (Android 11)
• Huawei Mate 20 Lite (Android 10)
• OnePlus A3 (Android 6.0.1)
