### ISSUE TITLE
[Bug] Open links in private tab is not working

### ISSUE THREAD

**Issue by softvision-miralobontiu** [mozilla-mobile/fenix#8354]
## Steps to reproduce
1. Make Fenix your default browser.
2. Turn ON the toggle from Settings - Private browsing - Open links in a private tab.
3. Go to Gmail, open a custom tab, then select from the three-dot menu to open the tab in Fenix.
4. Observe where the app opens the tab.

### Expected behavior
The custom tab and the tab open in private mode.

### Actual behavior
Both the custom tab and tab open in normal mode.

### Device information
* Android devices: Sony Xperia Z2 (Android 6.0.1), Xiaomi Mi4i (Android 5.1.0), Nexus 5 (Android 6.0.1), Samsung Galaxy S10+ (Android 9), Google Pixel 3a XL (Android 10), Samsung Galaxy S8 (Android 8)
* Fenix version: 2/12 Nightly build

[text.txt](https://github.com/mozilla-mobile/fenix/files/4192954/text.txt)

![open-in-private-tab](https://user-images.githubusercontent.com/40694158/74346746-b38e7380-4db8-11ea-808c-6786b6c59a46.gif)

**Comment by sv-ohorvath** [comment]
@mcarare Found on Beta 4.0:
https://github.com/mozilla-mobile/fenix/issues/8534
https://github.com/mozilla-mobile/fenix/issues/8535

**Comment by mcarare** [comment]
Waiting to work on this after a fix for https://github.com/mozilla-mobile/fenix/issues/8535 is going to land. Thanks @sv-ohorvath for testing!

**Comment by sv-ohorvath** [comment]
@mcarare I've found the following 2 issues:
#1. The open link in PB toggle needs to be switched twice to have effect: if you switch it Off once, links will still open in PB. You need to turn it on & off again.

#2. Switching the toggle off once, then open a link from a custom tab will crash the app: https://github.com/mozilla-mobile/fenix/issues/8637 - possibly related to issue #1.

**Comment by boek** [comment]
@sv-ohorvath Both of these should be fixed with this change

https://github.com/mozilla-mobile/fenix/commit/dfde37baf523a505e220acd3d23b70bde0f1a568#diff-b86a934296a543d3dc118df07cf20cb5L42

**Comment by sv-ohorvath** [comment]
This has been fixed on Nightly 2/26. I found a new separate issue: https://github.com/mozilla-mobile/fenix/issues/8763
