### ISSUE TITLE
[Bug] The arrow  back button is smaller and misaligned in Settings section 

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/fenix#8356]
## Steps to reproduce
1. Launch Fenix and reach the settings section.
2. Observe the arrow back button size and position.
### Expected behavior
The arrow back button should be correctly aligned.
### Actual behavior
The arrow  back button is smaller and misaligned in the Settings section 
### Device information

* Android device: **Samsung Galaxy S10+ (Android 9).**
* Fenix version: **Nightly 2/12.**

![1](https://user-images.githubusercontent.com/42831109/74351971-8219a600-4dc0-11ea-9068-404e659e2885.jpg)

**Comment by seydouba95** [comment]
I would like  to build this bug and i'm ready to this bug

**Comment by seydouba95** [comment]
I would like to be assigned to this bug and I am ready to resolve it

**Comment by AndiAJ** [comment]
**Not reproducible** anymore on the latest on the latest **`Nightly Build 201111`** using the following devices:
• Google Pixel 3a (Android 11)
• Huawei Mate 20 Lite (Android 10)
• OnePlus A3 (Android 6.0.1)
