### ISSUE TITLE
[Bug] Tapping Android "Back button" while editing a URL takes me to Home screen, not back to page content

### ISSUE THREAD

**Issue by Cheap-Skate** [mozilla-mobile/fenix#8358]
## Steps to reproduce
On any web page, tap the URL bar
URL bar moves into "edit" mode and keyboard is brought up
Try to cancel edit mode by using the Android "Back" button at the bottom of the screen
(NOT the Fenix back button at the top of the screen)
(the "back" button on my device is a down arrow, to dismiss the keyboard. )

### Expected behavior
Tapping the Android back button returns me to the web page or dismisses the keyboard (or both)

### Actual behavior
Tapping the Android back button takes me to the Home screen / tabs tray

Related to #847?

### Device information

* Android device: Galaxy A40, Android 9.0.0
* Fenix version: Today's

**Comment by ekager** [comment]
This is incorrect behavior. Let's fix this ASAP.

**Comment by ekager** [comment]
If you scroll the awesomebar results first and then press back, it goes to back to browsing content correctly, so something must have changed in this logic

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly Build # 20450607 from 2/14`** using the following devices:
• Google Pixel XL (Android 10)
• Google Pixel 3a (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7.0)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

► Video
![20200214-160852](https://user-images.githubusercontent.com/51314259/74538745-83c0a680-4f45-11ea-97e5-007fb9c3ea73.gif)
