### ISSUE TITLE
"tab closed" popup doesn't go away [Bug]

### ISSUE THREAD

**Issue by axaith** [mozilla-mobile/fenix#8364]
## Steps to reproduce
if you go to any screen (such as settings, or a new tab) other than the home screen while the "tab closed" popup is still on screen, the popup remains indefinitely

### Expected behavior
the popup should go away

### Actual behavior
it doesn't

### Device information
this problem started with fenix version 3.2

**Comment by cadeyrn** [comment]
Duplicate of #7799.
