### ISSUE TITLE
[Bug] Fenix will not save Proxy Log-In Credentials

### ISSUE THREAD

**Issue by edo0** [mozilla-mobile/fenix#8373]
## Steps to reproduce
I set up my university proxy, allowing access to uni resources from external networks. These were the settings required in "about:config":
"network.proxy.autoconfig_url” = “http://siba.unipv.it/proxybib.pac“
“network.proxy.type” = "2"
### Expected behavior
In the old Firefox browser, after I inserted my credential once (on websites like sciencedirect.com, nature.com, etc.), they would be saved by the browser, in such a way that the proxy authentication dialogue will be pre-filled every time I stumble upon one such website in a new browsing session
### Actual behavior
The dialogue for proxy authentication is empty, and every new session I need to insert the lenghthy credentials of my uni account
### Device information

* Android device: Xiaomi Pocophone F1 running LineageOS 16 (based on Android 9.0)
* Fenix version: Nightly 200212 06:01 (Build #20430607)
32.0.0, d833485a8
GV: 74.0a1-20200210093912

### Picture
Empty Fenix Proxy log-in dialogue
![IMG_20200213_095454](https://user-images.githubusercontent.com/16632292/74418308-7a054900-4e48-11ea-9973-742defc5c200.jpg)

┆Issue is synchronized with this [Jira Story](https://mozilla-hub.atlassian.net/browse/FNXV2-15697)

**Comment by softvision-miralobontiu** [comment]
@edo0 could you, please, retry on a newer Firefox Nightly build?
Thank you!

**Comment by edo0** [comment]
Tested on Nightly 201117 20:41 (Build #2015776235), and unfortunately the problem persists unchanged
(tested on sciencedirect.com. As I end the session, once I open the browser again and return on the webpage, the login fields have been cleared and I need to re-enter username and password)

**Comment by edo0** [comment]
I can confirm this bug is still reprodicible to this day

**Comment by edo0** [comment]
Not stale, just forgotten by the devs

**Comment by plwt** [comment]
User feedback: https://support.mozilla.org/en-US/questions/1364728

**Comment by jjkssm** [comment]
I can confirm this bug is still in 91.* (in 98/101 the behavior has changed, now the prompt for storing the credentials will be shown and the credentials will be stored in "password manager", but they will not be autofilled when accessing the proxy again).
