### ISSUE TITLE
[Bug]Unexpected input event is fired when focus leaves the input element

### ISSUE THREAD

**Issue by Diana-Rus** [mozilla-mobile/fenix#8375]
Ticket created based on bugzilla issue: https://bugzilla.mozilla.org/show_bug.cgi?id=1610083 .

## Steps to reproduce
1. Go to "https://jsbin.com/xulahutumo/edit?output".
2. Tap on the input field.
3. Insert characters into the field.
4. Check the "Count of input events:" .
5. Tap outside the field.
6. Check again the "Count of input events:" .

### Expected behavior
The "Count of input events:" has the correct number of characters displayed. The unfocus event should not trigger an input event.
### Actual behavior
When tapping outside the input field the value from "Count of input events:" increases with 1.
### Device information

* Android device: Google Pixel 3 XL (Android 10), Samsung Galaxy S8+ (Android 8.0.0)
* Fenix version: Firefox Preview Nightly 200213 (Build #20440605) GV: 74.0a1-20200210093912

![20200213-111407](https://user-images.githubusercontent.com/49859863/74420967-f43bca80-4e54-11ea-9d67-d20d6af9a77c.gif)

**Comment by kbrosnan** [comment]
This is not something for the Fenix team to fix. The issue is Gecko behavior.
