### ISSUE TITLE
[Bug] default search engine is not migrated

### ISSUE THREAD

**Issue by nbp** [mozilla-mobile/fenix#8383]
## Steps to reproduce
Set a default search engine to Qwant.
Then migrate from Firefox for Android to Fenix.

### Expected behavior
I expect to see Qwant remain as the default search engine in Fenix.

### Actual behavior
Google is set as the default search engine in Fenix, without considering the default search engine in Firefox for Android.

### Device information

* Android device: 9
* Fenix version: Nightly 200210 10:05 (Build #2015722195)

**Comment by mcarare** [comment]
@nbp Do you still have Qwant in the search engines list? A default engine will not be migrated if it is not in the default list for your region.

**Comment by kbrosnan** [comment]
This is expected behavior as outlined in #5818

**Comment by boek** [comment]
Double checked with product and we are not migrating custom search engines
