### ISSUE TITLE
[Bug] migration from Firefox for Android to Fenix lose application locking (Huawei EMUI)

### ISSUE THREAD

**Issue by nbp** [mozilla-mobile/fenix#8384]
Huawei EMUI 9.1.0 parameters offer the ability to lock applications using fingerprint or facial recognition.

## Steps to reproduce
Lock Firefox for Android application using fingerprint/facial recognition.
Migrate from Firefox for Android to Fenix.

### Expected behavior
Opening Fenix should present the authentication screen.
Note: Huawei parameters show the application as still being secured, while it is not.

### Actual behavior
Fenix opens without requesting any authentication.

### Device information

* Android device: 9
* Fenix version: Nightly 200210 10:05 (Build #2015722195)
* Huawei EMUI: 9.1.0

Note, a work-around is to go in the Huawei parameter and toggle it off and back on, to re-enable application locking on Fenix.

**Comment by kbrosnan** [comment]
We are not changing any migration code. Users will need to unlock and relock the app.
