### ISSUE TITLE
[Bug] Launching the app with private shortcut will keep the PB theme on normal browsing too

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#8386]
## Steps to reproduce
1. Add the private browsing shortcut.
2. Launch the PB shortcut.
3. Tap the search bar's back button to dismiss the search layout.
4. Switch to normal browsing.
### Expected behavior
Normal browsing colors, the private icon is not selected.
### Actual behavior
PB theme colors in normal browsing, the private browsing icon is selected.
![PB theme](https://user-images.githubusercontent.com/4037709/74441482-902afd80-4e78-11ea-98d2-1eefed245248.png)

### Device information

* Android device: Pixel 2 (Android 9)
* Fenix version: Nightly 2/13

**Comment by abodea** [comment]
Note that when opening an external link(while Open links in a private tab option is ON) and changing to PB the normal browsing theme colors are displayed.
Might be related to #8354

![20200213-161706](https://user-images.githubusercontent.com/42831109/74443947-bfdc0480-4e7c-11ea-9d4b-390f5c35c6e9.gif)

**Comment by liuche** [comment]
Talked to @ekager and the root cause is probably the same as #8413 , so once that's fixed we should verify this one as well.

**Comment by liuche** [comment]
Actually, I'm not seeing this anymore on Nightly 2/25, and can toggle the PB/normal mode from both the shortcut and custom tabs.

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly Build #20570604 from 02/26`** using the following devices:
• Google Pixel 3a (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

► Video 
![20200226-091840](https://user-images.githubusercontent.com/51314259/75322927-74fabd80-587c-11ea-985b-2370d40513dc.gif)
