### ISSUE TITLE
Black screen when submitting a large file

### ISSUE THREAD

**Issue by Diana-Rus** [mozilla-mobile/fenix#8387]
Issue created based on ticket: https://bugzilla.mozilla.org/show_bug.cgi?id=1609934 

## Steps to reproduce
1. Go to "https://www.w3schools.com/tags/tryit.asp?filename=tryhtml5_input_type_file"
2. Tap on the "Browse" from the one file selection.
3. Choose a file that is of at least 1 Gb.

### Expected behavior
The input type file tag has the name of the imported file displayed.
### Actual behavior
Before having the file name displayed, a black screen is present.
### Device information

* Android device: Google Pixel 3 XL (Android 10), Samsung Galaxy S8+ (Android 8.0.0)
* Fenix version: Firefox Preview Nightly 200213 (Build #20440605) GV: 74.0a1-20200210093912

Please view gif.

![20200213-153346](https://user-images.githubusercontent.com/49859863/74442121-a1c0d500-4e79-11ea-844a-6c3c862b0979.gif)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-15708)

**Comment by mcomella** [comment]
@kbrosnan Can someone from QA check if this is reproducible on a 100 MB file? If so, it's like a P1 responsiveness issue we should address. If not, we can address it later.

**Comment by mcomella** [comment]
@AndiAJ Can someone from QA check if this is reproducible on a 100 MB file? It'll help us determine if this should be done now or later.

**Comment by AndiAJ** [comment]
Hi @mcomella , I've just re-checked this mater on the latest **`Nightly Build #200790605 from 3/19`** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 8.1.0)

**When uploading the 100 & 200 MB files no issues encountered**, on the other hand, **the black screen seems to be displayed when uploading the 512 MB file**. 

► Video from Google Pixel 3a uploading a 512MB file
![20200319-111854](https://user-images.githubusercontent.com/51314259/77051338-c86faf80-69d3-11ea-9372-cafae7942810.gif)

► Video from Google Pixel 3a uploading a 200 MB file
![20200319-111812](https://user-images.githubusercontent.com/51314259/77051414-ea693200-69d3-11ea-955d-ddf463033de3.gif)

► Video from Google Pixel 3a uploading a 100 MB file
![20200319-110055](https://user-images.githubusercontent.com/51314259/77051792-86933900-69d4-11ea-879b-cdd46a2c0b6b.gif)

Please review and share your thoughts. ☺️

**Comment by mcomella** [comment]
Triage: 100 MB flow doesn't look too bad and (with no supporting data) that's the largest reasonable file upload size so putting to Low Impact for now.

**Comment by mcomella** [comment]
Triage: I wanted to re-evaluate to see if this could be a good inter-team issue but we decided against it.

**Comment by softvision-miralobontiu** [comment]
I was able to reproduce this issue on the 11/18 Nightly build with Samsung Galaxy Tab S6 (Android 10) when I've uploaded a 1 GB file.

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807360

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
