### ISSUE TITLE
[Bug]Improperly displayed ⋮ Main menu (3dot menu) overlay in landscape mode

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#8388]
## Steps to reproduce
1. From the Home screen tap the ⋮ Main menu button.
2. Rotate the device to landscape view.

### Expected behavior
The ⋮ Main menu overlay should be properly displayed in landscape view.

### Actual behavior
The ⋮ Main menu overlay is shrunken.

### Device information

* Android device:  
•  LG Nexus 4 (Android 5.1.1)
•  Xiaomi Mi4i (Android 5.0.2)

* Fenix version: Nightly Build # 20440606 from 2/13

### Notes
✔ Not reproducible on the following devices:
• Google Pixel 3a (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7.0)
• OnePlus A3 (Android 6.0.1)

► Video
![20200213-162514](https://user-images.githubusercontent.com/51314259/74445360-ee5adf00-4e7e-11ea-9c51-b04c5bb9047f.gif)

► Screenshot from Xiaomi Mi4i 
![Screenshot_2020-02-13-16-56-05-256_org mozilla fenix nightly](https://user-images.githubusercontent.com/51314259/74447523-2fa0be00-4e82-11ea-893f-9bce237d88e1.png)

**Comment by AndiAJ** [comment]
Seems that the custom tabs overlay is also affected on both **`Nightly #20640607 from 3/4`** and **`Beta 4.0.0-beta.3`** using a OnePlus A3 (Android 6.0.1)

► Screenshot
![rsz_screenshot_20200304-110640](https://user-images.githubusercontent.com/51314259/75862996-742bd380-5e08-11ea-845f-084353b354a6.png)

**Comment by softvision-miralobontiu** [comment]
I was able to reproduce on the latest Nightly 201118. using an OnePlus A3 (Android 6.0.1).
Not reproducible anymore on Xiaomi mi4i (Android 5.0.2).
