### ISSUE TITLE
Add a better audible page loading indicator

### ISSUE THREAD

**Issue by MarcoZehe** [mozilla-mobile/fenix#8392]
### Why/User Benefit/User Problem

Blind or visually impaired users have no way of knowing how far or fast a page is being loaded into the browser.

### What/Requirements

When a page loads, indicate the progress either by intermittent announcements to TalkBack (the Android screen reader) or by emitting ascending unobtrusive beeps, or progress clicks (similar to what Safari on iOS does).

### Acceptance Criteria (how do I know when I’m done?)

Feature is implemented if one can hear a page being loaded without looking at the screen.

CC @eeejay

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-15712)

**Comment by jcsteh** [comment]
@eeejay [noted on Matrix](https://matrix.to/#/!jmuErVonajdNMbgdeY:mozilla.org/$6Qi86ho1G0Lh7hzFy-dtIBDg_5K78CStJBmifiToBJY?via=mozilla.org&via=delire.party):

> for the record, it works as much as it ever did. which is not great. what i tried to do is always have a 100% pulse at the end so you get a high pitch earcon to know its done.

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1810827

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
