### ISSUE TITLE
Add a hint for the Error pages/Unknown Protocol when trying to open links in apps(while the option is OFF)

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/fenix#8397]
### Why/User Benefit/User Problem
As a Fenix user, I wanna know/get a hint when the `Open links in apps` option are turned off and trying to open one, for example, `www.twitch.tv`.
### What/Requirements
Inform the user that `Open links in apps` option is turned off in settings.
### Acceptance Criteria (how do I know when I’m done?)
There is information regarding `Open links in apps` displayed on the returned error page.

### Notes
Maybe as a new user, if this option is off there is nothing to point to it and inform the user where to find it.
![Screenshot_20200213-175551_Firefox Nightly](https://user-images.githubusercontent.com/42831109/74453530-31bb4a80-4e8b-11ea-9891-8cadc9968593.jpg)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-15714)

**Comment by gnumoksha** [comment]
Also, I would add the protocol itself in the error message, instead of `wxyz:\\`.

Right now I'm unable to log in on GitHub app and I don't know how to solve the problem.
