### ISSUE TITLE
[Bug] When Set as the Default Browser App, Cannot sign into Expensify

### ISSUE THREAD

**Issue by tomrittervg** [mozilla-mobile/fenix#8398]
## Steps to reproduce

Fenix set as the Default browser app

Open Expensify, sign in with mozilla email, get sent to SSO page, put into email and then password, get duo push, approve it.

### Expected behavior

After approving Duo, I get signed into the app. (This happens with Chrome.)

### Actual behavior

Page goes to an unrecognized protocol error page. Do not get signed in. 

### Device information

* Android device: Pixel 3a Android 10
* Fenix version: 3.2.1 Saturday 1/25 @ 3:49 AM

**Comment by kbrosnan** [comment]
Dupe #7331
