### ISSUE TITLE
Fix regression on applink start up

### ISSUE THREAD

**Issue by MarcLeclair** [mozilla-mobile/fenix#8403]
Our current app-link start up has regressed by almost double. On 02/09 we had 500ms on the G5 and it increased to about 900ms on start up

Here's the graph:
https://github.com/mozilla-mobile/fenix-nightly-perftest-results/blob/master/al-results.png

**Comment by mcomella** [comment]
The PR for this issue does not appear to have affected performance, as of the 2/14 Nightly

**Comment by mcomella** [comment]
@MarcLeclair or @ekager: Can you update the bug title and description to describe what the suspected root cause of this regression is?

**Comment by mcomella** [comment]
> The PR for this issue does not appear to have affected performance, as of the 2/14 Nightly

Actually, it looks like FNPRMS stopped recording on 2/14 https://github.com/mozilla-mobile/perf-frontend-issues/issues/67 so we should resolve that issue before determining that this fix did not work.

**Comment by MarcLeclair** [comment]
@mcomella pr #8509  should be the fix for this, at least it was locally 😄

**Comment by MarcLeclair** [comment]
@mcomella  I'll close this since the AL is now back to around what we had few weeks ago.

**Comment by AndiAJ** [comment]
As per @MarcLeclair 's [comment](https://github.com/mozilla-mobile/fenix/issues/8403#issuecomment-589703995) I'll mark this matter as QA not needed.
