### ISSUE TITLE
[Bug] Sentry crash: IndexOutOfBoundsException in getProvidedDefaultSearchEngineAsync

### ISSUE THREAD

**Issue by Baron-Severin** [mozilla-mobile/fenix#8406]
https://sentry.prod.mozaws.net/operations/fenix-nightly/issues/6722820/?query=user:%22id:android:54379d95087eb479%22

```
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
    at java.util.ArrayList.get(ArrayList.java:437)
    at mozilla.components.browser.search.SearchEngineManager.getProvidedDefaultSearchEngineAsync(SearchEngineManager.kt:9)
    at mozilla.components.browser.search.SearchEngineManager.getDefaultSearchEngineAsync(SearchEngineManager.kt:7)
    at mozilla.components.browser.search.SearchEngineManager$getDefaultSearchEngineAsync$1.invokeSuspend
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:2)
    at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:15)
    at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:15)
```

**Comment by danielzgtg** [comment]
This started happening to me when `org.mozilla.fennec_aurora` updated to look like Firefox Preview and I deleted all search engines except Google.

The crash stopped occurring for me in a later update where it automatically added back any search engines I removed.

As of version `Nightly 200220 18:00`, this is completely fixed for me. I no longer get this crash and I am able to remove search engines normally.

**Comment by Baron-Severin** [comment]
> This started happening to me when `org.mozilla.fennec_aurora` updated to look like Firefox Preview and I deleted all search engines except Google.
> 
> The crash stopped occurring for me in a later update where it automatically added back any search engines I removed.
> 
> As of version `Nightly 200220 18:00`, this is completely fixed for me. I no longer get this crash and I am able to remove search engines normally.

Interesting, I think that will help us track this down.  Thanks for the report!

**Comment by danielzgtg** [comment]
@Baron-Severin I meant:

Based off the time of this issue, it was might have been created in response to me clicking report on the notification.

This bug doesn't affect me anymore. So, if it's not affecting anyone else either, then this issue can be closed.

**Comment by Baron-Severin** [comment]
Right, I should have clarified that our telemetry shows that it's still happening.  It's not super frequent, but still something it would be great to clean up.  But your comment might help point us towards a data migration issue, for example, or something similar.  Not sure, it'll take some more investigation.  In any case it's useful feedback.

**Comment by boek** [comment]
We did quite a few changes to the search engine manager a few weeks ago and haven't seen any crashes with this trace since. Going to close this for now and will re-open if it pops back up
