### ISSUE TITLE
[Crash] libfenix.so native code crash

### ISSUE THREAD

**Issue by boek** [mozilla-mobile/fenix#8409]
```
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
pid: 0, tid: 0 >>> org.mozilla.fenix <<<

backtrace:
 
  #00  pc 00000000000e1b90  /apex/com.android.runtime/lib64/bionic/libc.so (pthread_mutex_lock)
 
  #01  pc 00000000002eade0  /data/app/org.mozilla.fenix-ioT8Tz7q1OETMSJZvg0p5Q==/lib/arm64/libfenix.so
```

https://play.google.com/apps/publish/?account=7083182635971239206#AndroidMetricsErrorsPlace:p=org.mozilla.fenix&appid=4975374341268119750&appVersion=PRODUCTION&lastReportedRange=LAST_14_DAYS&clusterName=apps/org.mozilla.fenix/clusters/22badeee&detailsAppVersion=PRODUCTION&detailsSpan=14

**Comment by boek** [comment]
@grigoryk Is this a crash coming from application services? If so is there a way to actually get a stack trace somewhere? 🤔

**Comment by Baron-Severin** [comment]
> @grigoryk Is this a crash coming from application services? If so is there a way to actually get a stack trace somewhere? 🤔

@grigoryk bumping this

**Comment by boek** [comment]
Crash isn't showing up on google play anymore. Will re-open if we see it
