### ISSUE TITLE
make bookmark and share toolbar menu options more visible

### ISSUE THREAD

**Issue by lime124** [mozilla-mobile/fenix#8419]
Through the recent milestone test Elisabeth conducted, we learned that some people are not seeing the bookmark and share icons at the bottom making the feature less discoverable. How can we increase the visibility of those items.

Assigning to @AmyYLee for a solution before passing to polish team.

**Comment by AmyYLee** [comment]
Spoke to @topotropic and @apbitner about this. We would like to hold off on this until post migration.

**Comment by kbrosnan** [comment]
This sounds like QAB feedback. Can we close this?

**Comment by apbitner** [comment]
@kbrosnan it's about the toolbar menu, however, the last round of testing showed no issues with sharing and the bookmarks issue is covered [here](https://github.com/mozilla-mobile/fenix/issues/11987), so this one can be closed.

**Comment by softvision-miralobontiu** [comment]
I'll close this issue based on the last two comments.
