### ISSUE TITLE
[Bug] Firefox Preview (fenix?) doesn't support U2F tokens

### ISSUE THREAD

**Issue by maxamillion** [mozilla-mobile/fenix#8420]
## Steps to reproduce
Attempt to login to a site that requires a U2F token for second factor auth.

### Expected behavior
U2F tokens to work like current stable Firefox for Android

### Actual behavior
You are never prompted to insert the U2F token, but instead get an error message from the website.

### Device information

* Android device: Google Pixel 4
* Fenix version: Firefox Preview 3.2.1 (Build #20250350) 28.0.3, f0dc2cadd, GV: 73.0-20200123172213

**Comment by kbrosnan** [comment]
Dupe #1340. U2F is a Chrome protocol. The open standard is webauthn.
