### ISSUE TITLE
Search Keywords are not supported. 

### ISSUE THREAD

**Issue by kevincox** [mozilla-mobile/fenix#8421]
### Why/User Benefit/User Problem

Keywords and search keywords allow the user to assign shortcuts to webpages and searches. These sync across devices with regular bookmark sync. 

### What/Requirements

When I type the keyword (followed by an optional search query) and navigate it goes to the keyword. 

### Acceptance Criteria (how do I know when I’m done?)

Keywords work as they do in other Firefox versions. (AKA they can be used)

**Comment by kevincox** [comment]
Documentation: https://support.mozilla.org/en-US/kb/how-search-from-address-bar

**Comment by kbrosnan** [comment]
Dupe #2497
