### ISSUE TITLE
Fennec migration: The steps from the onboarding migration screen have the wrong text size, font and spacing

### ISSUE THREAD

**Issue by ebalazs-sv** [mozilla-mobile/fenix#8422]
## Preconditions:
Have Fennec installed.
## Steps to reproduce
1. Replace Fennec with Fenix with a build from https://github.com/mozilla-mobile/fenix/wiki/Fennec-Migration;
2. Launch Fenix;
3. Observe the steps from the onboarding migration screen.
### Expected behavior
The steps are displayed like in the [specs](https://miro.com/app/board/o9J_kw1CGow=/).
### Actual behavior
The space between the steps is too small, also the text size and font is wrong.
### Notes:
[Video](https://drive.google.com/file/d/1BaSscquYWcVp0bjpzdYf8CgbwRUPgWXm/view)
This is also reproducible on Nightly migration build 02/10.
### Device information

* Android device: OnePlus 5T (Android 9), Nexus 6P (Android 8.1.0), Huawei Honor 8 (Android 7.0);
* Fenix version: Beta migration build 02/12

**Comment by ebalazs-sv** [comment]
This is also reproducible on Nightly Migration Build 9, 02/14.

**Comment by Sparky93** [comment]
As said in https://github.com/mozilla-mobile/fenix/issues/7955 and as per Bram's [comment](https://github.com/mozilla-mobile/fenix/issues/7955#issuecomment-582188987), this is going to be fixed in #3687 and #8089.

**Comment by apbitner** [comment]
Those related tickets may fix the font family being used, but there are still issues with the spacing and layout of the page. Please see the spec in the issue details above.

**Comment by ebalazs-sv** [comment]
This is reproducible on Beta Migration Build #3 with Huawei P9 Lite (Android 7), Google Pixel 3 (Android 10).

**Comment by ebalazs-sv** [comment]
This is still reproducible on Beta Migration build 4, 3/24, with Huawei P9 Lite (Android 7).

**Comment by ebalazs-sv** [comment]
Since this is still reproducible I will move it from Ready for QA to Beta.

**Comment by jonalmeida** [comment]
This can be verified with on a nightly migration.

**Comment by ebalazs-sv** [comment]
Verified as fixed on the latest Nightly Migration build 200427 (Build #2015736947) with Pixel 2 (Android 9), Nexus 5 (Android 6.0.1), Samsung Galaxy Tab S3 (Android 8). 
I will remove the qa:needed label and close this issue. Thanks!
