### ISSUE TITLE
[Bug] Delete Login Action should have confirmation dialog

### ISSUE THREAD

**Issue by sv-sdeiac** [mozilla-mobile/fenix#8423]
### Prerequisites
Make sure that the Firefox Preview has some logins saved.

## Steps to reproduce
1. Go to the Settings;
2. Select "Logins and passwords";
3. Open the "Saved logins" section;
4. Select a saved login;
5. Delete the saved login.

### Expected behavior
A snackbar is displayed informing the user that the saved login is deleted with an "Undo" button.

### Actual behavior
There is no snackbar displayed and the deleted login it cannot be undone.

### Device information
* Android device: Nokia 6 (Android 7.1.1).
* Fenix version: 2/14 #20450606.

**Comment by ekager** [comment]
CC @AmyYLee . As discussed, we should have a dialog here like in other parts of the app.

Should the copy here follow our other dialog copy? ie for bookmarks we have
"Are you sure you want to delete this bookmark?"

So something like "Are you sure you want to delete this login?"

**Comment by AmyYLee** [comment]
> CC @AmyYLee and @mheubusch . As discussed, we should have a dialog here like in other parts of the app.
> 
> Should the copy here follow our other dialog copy? ie for bookmarks we have
> "Are you sure you want to delete this bookmark?"
> 
> So something like "Are you sure you want to delete this login?"

@betsymi

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly Build #20700607 from 03/10`** using the following devices:
• Google Pixel 3a (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

►Pic
![rsz_11rsz_00000img_00000_burst20200310105437462_cover](https://user-images.githubusercontent.com/51314259/76297004-cb75ec00-62bf-11ea-873f-5d75d285bec1.jpg)
