### ISSUE TITLE
[Bug]Missing "Add to Home screen" button from the ⋮ Main menu (3dot menu) overlay

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#8424]
## Steps to reproduce
1. Navigate to Cnet.com.
2. Tap the ⋮ Main menu (3dot menu)
3. Check the buttons from the overlay

### Expected behavior
The "Add to Home screen" button should be displayed in the overlay.

### Actual behavior
The "Add to Home screen" button is missing from the overlay.

### Device information

* Android device: Google Pixel C ( Android 8.0.0)
* Fenix version: Nightly Build # 20450607 from 2/14

### Notes
► Screenshot comparisons Google Pixel 3a (**left**) VS Google Pixel C (**right**)
![addhome](https://user-images.githubusercontent.com/51314259/74518996-88716480-4f1d-11ea-8eb5-7a158ecf4749.png)

❗ Not reproducible on the following devices:
• Google Pixel 3a XL (Android 10)
• Google Pixel 3a (Android 9)
• Google Pixel 3 XL (Android 9)
• Google Pixel 3 (Android 9)

**Comment by mcarare** [comment]
Google Pixel C in Android 8.0.0 has a launcher that does not support adding shortcuts.
That can be tested with other browsers like Chrome (although it shows the option, pinning does not really work).
Side note: Updating to 8.1 will change the launcher to the one from Pixel and adding shortcuts should work.

Closing this as it is not an issue we can fix in Fenix.

**Comment by AndiAJ** [comment]
Thx @mcarare good to know! ☺️
