### ISSUE TITLE
Search selection after a query

### ISSUE THREAD

**Issue by 532910** [mozilla-mobile/fenix#8425]
To search something in firefox for desktop and fennec you should type a query and then select and press the search action.
Fenix completely breaks this logics forcing you to select the search **before** typing a query.
Every time I'd like to search something in the alternate search engine the following happens, I:
1. type a query
2. see that only default search is available
3. say "F... Fenix designers"!
4. select typed query
5. press `cut`
6. select the search engine
7. paste the clipboard

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-15736)

**Comment by TitanNano** [comment]
@532910 pressing the "Shortcuts" button above the keyboard will show a list of available shortcuts to search with.

**Comment by 532910** [comment]
On the on hand I was wrong, it's possible to select search engine after a query.
On the other:
1. It's too untrivial (I was unable to find it myself)
2. It requires two actions more: (before pressing another search engine icon leads to this query execution, now it requires tree actions: press shortcuts, select engine, press enter.

**Comment by 532910** [comment]
Moreover, before it was a line, but now it takes the whole screen:

![image](https://user-images.githubusercontent.com/14617699/74954973-00a3c280-5415-11ea-854d-74e91b9025f1.png)
![image](https://user-images.githubusercontent.com/14617699/74955045-1a450a00-5415-11ea-81a0-65e0108507cb.png)

**Comment by madb1lly** [comment]
I completely agree with the bug report @532910, although thanks to @TitanNano for the tip about shortcuts.

I would like to know what the perceived benefit of the current workflow is? Why do t get team think this is better than the Fennec implementation?

Cheers 🙂

**Comment by softvision-miralobontiu** [comment]
@532910 you can eliminate some steps, by enabling the "Show search engines" from Settings - Search.
Now, your steps will be:
1. type a query
2. select the desired search engine
3. tap on "Go".

Does this help?

**Comment by 532910** [comment]
Nope, search engines hide as soon as I start typing a query.

**Comment by madb1lly** [comment]
Hi @532910,
I don't think the flow for this has changed has it? I've got used to it now but it's still pretty frustrating when I forget.
Cheers 🙂

**Comment by 532910** [comment]
Why the fact of inactivity is a reason to close an issue?

**Comment by cadeyrn** [comment]
> Why the fact of inactivity is a reason to close an issue?

It's explained in the linked issue #17373.

**Comment by madb1lly** [comment]
🥱
I think the current implementation addresses this bug. Anyone else agree?
Cheers 🙂

**Comment by SoftVision-LorandJanos** [comment]
The search engine is changeable after typing a query.
You can now go to secret settings and activate unified search, where you can change the search engine easier after typing a query, but the main behavior is the same.

**Comment by madb1lly** [comment]
I believe this is now fixed.

**Comment by cpeterso** [comment]
> I believe this is now fixed.

In that case, I'll close this bug for now. Thanks for testing!
