### ISSUE TITLE
About Firefox Nightly  page is not completely translated in some languages

### ISSUE THREAD

**Issue by lobontiumira** [mozilla-mobile/fenix#8428]
## Steps to reproduce
1. Change the language of the device to German / Deutsch, Spanish / Espanol, French / Francais, etc.
2. Open Fenix and go to Settings - About Firefox Nightly and observe the page.

### Expected behavior
The Firefox Nightly page is entirely translated.

### Actual behavior
The "Firefox Nightly is produced by Mozilla." text is not translated.

### Device information
* Android device: all
* Fenix version: 2/14 Nightly build

![Screenshot_20200214-115816](https://user-images.githubusercontent.com/40694158/74521512-2cf5a580-4f22-11ea-8d59-d0d8fe15015e.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-15738)

**Comment by cadeyrn** [comment]
The beta migration is almost finished. Could this be resolved before the final migration, please? There should really no untranslated strings in the stable release and it doesn't sound like a difficult problem. Thanks!

**Comment by Diana-Rus** [comment]
Hi, issue is reproducible with Google Pixel 3 XL (Android 9) and Samsung Galaxy S9 (Android 8) on Beta 4.3.0-beta.1.

**Comment by softvision-miralobontiu** [comment]
This is still reproducible on 12/31 Nightly build with Azerbaycan language:

<img src="https://user-images.githubusercontent.com/40694158/103400552-3560ca00-4b4e-11eb-9b37-4ae525d29dda.jpg" width="300" height="550" />

**Comment by lobontiumira** [comment]
The issue still reproduces with Azerbaycan language, on the 6/30 Nightly build, using a Google Pixel (Android 10).

**Comment by lobontiumira** [comment]
This is still reproducible on 11/2 Nightly build with Azerbaycan language, with Google Pixel (Android 10).

**Comment by sflorean** [comment]
This is still reproducible on Fenix versions.

**Comment by SoftVision-LorandJanos** [comment]
This issue is still reproducible on the latest Beta 108.0b3 with the Azerbaycan language:
![Screenshot_2022-11-24-13-55-03-90_ffb2f5e1b976ff98cfc94f359fbce8de](https://user-images.githubusercontent.com/48829350/203778950-73946ffb-6051-4ad7-a575-da034681ab65.jpg)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1810178

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
