### ISSUE TITLE
[Bug] The ublock icon is selected when is tapped

### ISSUE THREAD

**Issue by DanielOrban** [mozilla-mobile/fenix#8432]
## Prerequisites
- uBlock Origin is installed and enabled in Fenix
## Steps to reproduce
1. Navigate to a website with ads (eg. www.bbc.com)
2. Tap on the three-dot menu and tap on the uBlock Origin's icon.
3. Open the logger and tap on the ublock icon.
### Expected behavior
The ublock site specific option is displayed and the icon is not selected.
### Actual behavior
The ublock site specific option is opened but the icon is selected and the "Copy \ Select All" option appears.
### Device information
![The ublock icon is selected when is tapped](https://user-images.githubusercontent.com/43445968/74531197-a0a0ae00-4f34-11ea-9b3d-5c5fa592f193.gif)
* Android device: 
*Samsung Galaxy S7 (Android 8.0.0)
*Samsung Galaxy S7 Edge (Android 8.0.0)
* Fenix version: #20450607 2/14/2020

**Comment by csadilek** [comment]
Thanks for filing! This is also the case in Fennec and needs to be addressed in the add-on. We're relaying add-on specific UI improvements/issues to the add-on developers via @brampitoyo @kewisch. So, closing this here in line with other issues filed.
