### ISSUE TITLE
[Bug] The filter logger content bar is covered by the ublock site specific option

### ISSUE THREAD

**Issue by DanielOrban** [mozilla-mobile/fenix#8433]
## Prerequisites
- uBlock Origin is installed and enabled in Fenix
## Steps to reproduce
1. Navigate to a website with ads (eg. www.bbc.com).
2. Tap on the three-dot menu and tap on the uBlock Origin's icon.
3. Open the logger and tap on the ublock icon.
4. Tap on the "filter logger content" and type something.
### Expected behavior
The filter logger content bar is not covered by the ublock site specific option.
### Actual behavior
The filter logger content bar is covered by the ublock site specific option.
![The filter logger content bar is covered by the ublock site specific option](https://user-images.githubusercontent.com/43445968/74532556-2bcf7300-4f38-11ea-9888-a8ce0ec8db37.gif)

### Device information
 Android device:
    *Samsung Galaxy S7 (Android 8.0.0)
    *Samsung Galaxy S7 Edge (Android 8.0.0)
    Fenix version: #20450607 2/14/2020

**Comment by csadilek** [comment]
Thanks for filing! We're relaying add-on specific UI  improvements/issues to the add-on developers via @brampitoyo @kewisch. So, closing this here in line with other issues filed.
