### ISSUE TITLE
[Bug] Sync isnt syncing bookmarks correctly

### ISSUE THREAD

**Issue by IOI-655321** [mozilla-mobile/fenix#8436]
## Steps to reproduce
Change bookmarks on another device.  Add new ones, delete old or modify existing/

Sync on FF Preview

Bookmarks arent updated even though it says its synced.

Have tried signing out and signing in again.  after signing out bookmarks dissappear but after signing in again they re-appear as they were not fresh from sync.

### Expected behavior

Bookmarks should mirror the other device

### Actual behavior

Bookmarks are missing the new entires and no updates seem to have occurred.  After sync the desktop bookmarks then get updated incorrectly from FF preview alongside the changes.

### Device information

* Android device: Huawei P30 Android 10 (EMUI 10)
* Fenix version: Nightly 200214 06:01 (Build #20450607)

**Comment by GDXN** [comment]
This happened to me on the phone but loging-out and longing-in in the account and unselecting and then selecting again what I whant to sync fixed it.

**Comment by IOI-655321** [comment]
That didnt work for me, ive had to clear data from the app to get a correct sync going.

**Comment by softvision-miralobontiu** [comment]
I was able to reproduce it on Beta 4.0.0-beta.1 with Sony Xperia Z2 (Android 6.0.1).
Not reproducible on Nightly build from 2/20.

**Comment by softvision-miralobontiu** [comment]
I reproduced the issue today on the latest Nightly build from 3/11 (#20710605, AS 0.53.0) with Xiaomi Redmi Note 8T (Android 9), LG G7 Fit (Android 8.1), and Windows 10.
I bookmarked some pages on mobile, moved some folders on desktop, and triggered sync. The changes made on mobile were not visible on desktop, and vice-versa.

**Comment by Diana-Rus** [comment]
Hi, I reproduce the issue with Samsung Galaxy S8+ (Android 8) on Firefox Beta 4.1.0-beta.2.

**Comment by matfantinel** [comment]
I have the same happening on a Galaxy S10e, both on FF Preview 4.3 and Nightly. Any change in bookmarks does not get synced. Neither from desktop -> mobile neither mobile -> desktop

**Comment by sv-ohorvath** [comment]
This sounds similar to https://github.com/mozilla-mobile/fenix/issues/3525

**Comment by softvision-miralobontiu** [comment]
I was able to reproduce again this issue on the 7/28 Nightly build, using Samsung Galaxy Tab A6 (Android 5.1.1), and Windows 10.
