### ISSUE TITLE
[Bug] Using PIN backup access to Saved Logins doesn't work

### ISSUE THREAD

**Issue by ekager** [mozilla-mobile/fenix#8438]
## Steps to reproduce
1. Go to view saved logins with biometric set up
2. Say "Use Pin" on popup dialog
3. Enter PIN

### Expected behavior
Access to saved logins	

### Actual behavior
Returns to Logins and Passwords Screen

### Device information

* Android device: Pixel 3
* Fenix version: Master

**Comment by sv-sdeiac** [comment]
Hi, I can confirm that this issue is fixed using the latest version of Firefox Preview Nightly 2/16 #20470606.
Going to Saved logins using PIN as screen security will open the section.

Devices:
- Nokia 6 (Android 7.1.1);
- Samsung Galaxy S8 (Android 9);
- Google Pixel (Android Q).

**Comment by mcarare** [comment]
@eliserichards Does it work on the manage credit cards screen? 
Does it reproduce with 3 button navigation?
Thank you!
