### ISSUE TITLE
Taskcluster failures

### ISSUE THREAD

**Issue by boek** [mozilla-mobile/fenix#844]
Currently Taskcluster is failing on the scheduled task. I got it to the point it said it cannot find the task `assembleGreenfieldRelease` and told me I might mean `assembleArmGreenfieldRelease`. But we've never used that there. I was also confused as `assembleGreenfieldRelease` worked locally.

We tried the following PRs: #839 #840 to get it to build. 

cc: @mozilla-mobile/releng

**Comment by pocmo** [comment]
> I was also confused as assembleGreenfieldRelease worked locally.

It doesn't for me. This used to be just `assembleRelease`. We could specific the flavors we want to assemble explicitly (like `assembleArmGreenfieldRelease` or `assembleX86GreenfieldRelease`). But for #662 we want to build all release flavors soon anyways. Going back to `assembleRelease` may be the most straight-forward fix here.

**Comment by pocmo** [comment]
Looks like the Nightly build went out.

@boek I'm closing this... do we have a follow-up to re-activate adjust?
