### ISSUE TITLE
Add the option to disable all url suggestions in the address bar

### ISSUE THREAD

**Issue by matteocoder** [mozilla-mobile/fenix#8441]
### Why/User Benefit/User Problem
Avoid visiting a website that a user might select by mistake.
Currently, even when disabling all the toggles for search suggestions,
url suggestions for sites like ebay.com or netflix.com are still shown.
### What/Requirements
Add a toggle to disable url suggestions in the address bar section of the search page in the settings.
### Acceptance Criteria (how do I know when I’m done?)
url suggestions for sites like ebay.com or netflix.com should not appear in the address bar.

**Comment by kbrosnan** [comment]
Duplicate #5745
