### ISSUE TITLE
[Bug] Text inside form fields gets inflated and clipped

### ISSUE THREAD

**Issue by staktrace** [mozilla-mobile/fenix#8448]
## Steps to reproduce

Go to https://mozilla.staktrace.com/tmp/fields.html

### Expected behavior

Text in text fields is readable

### Actual behavior

Text is inflated but the text fields are not inflated. So the text in the fields gets clipped by the fields

### Device information

* Android device: Sony Xperia XZ1 Compact, android 9
* Fenix version: Nightly 200214 08:03 (Build #2015722947)
32.0.0, 9ff30b22e
GV: 75.0a1-20200213035745

**Comment by staktrace** [comment]
Not that this only started happening after my Fennec Nightly got upgraded to Fenix. It looks like Fenix enabled font inflation while Fennec didn't have it turned on.

**Comment by staktrace** [comment]
![Screenshot_20200215-202424](https://user-images.githubusercontent.com/485789/74597689-39b4ef00-5031-11ea-8dea-6c773c8fb0de.png)

Here's a screenshot too

**Comment by ekager** [comment]
Cc @buttercookie42 is this a known bug? Should I file in Bugzilla?

**Comment by buttercookie42** [comment]
Sounds like [bug 1604407](https://bugzilla.mozilla.org/show_bug.cgi?id=1604407).

**Comment by karlcow** [comment]
Another report https://github.com/webcompat/web-bugs/issues/48524

**Comment by buttercookie42** [comment]
Will be fixed in Gecko shortly.

**Comment by buttercookie42** [comment]
... and fixed now.

**Comment by karlcow** [comment]
@ekager  I wonder if this one is border line font inflation or if font-inflation has not happened in this case? see https://github.com/webcompat/web-bugs/issues/50660

what are the criteria for font inflation?
i wonder if there could be a message in the console saying `font inflation has been applied`

**Comment by buttercookie42** [comment]
Pages declaring themselves as mobile-friendly using the usual `<meta name="viewport" content="width=device-width, initial-scale=1">` (or similar) syntax are never inflated, and that WHO page *does* include that incantation.

**Comment by ekager** [comment]
Appears to be fixed in Nightly

**Comment by abodea** [comment]
I re-checked this on the latest **Nightly 4/16** with **Google Pixel 4 XL (10).**
It looks better but I think there is still something that needs to be fixed.
Removing the `eng:qa:needed` until further notice.
![Screenshot_20200416-150214](https://user-images.githubusercontent.com/42831109/79454701-5c915e80-7ff4-11ea-8bf1-14a654956a90.png)
![Screenshot_20200416-150220](https://user-images.githubusercontent.com/42831109/79454704-5e5b2200-7ff4-11ea-8463-055352ad28ac.png)

**Comment by staktrace** [comment]
The issue as I originally filed it is fixed.
