### ISSUE TITLE
[Bug] Delete browsing data UI clipping

### ISSUE THREAD

**Issue by lepiku** [mozilla-mobile/fenix#8449]
## Steps to reproduce
- Open Fenix nightly
- Go to settings
- Go to Delete browsing data
- Click on one of the options (ex: Browsing history and site data)
### Expected behavior
The UI not clipping
### Actual behavior
The UI circle is clipping, and the padding is very close to the text.
![Screenshot_20200216-113713_Firefox Nightly](https://user-images.githubusercontent.com/45702110/74599284-ecc52d00-50b1-11ea-88eb-bea1a1f978d5.jpg)
Very noticeable on "Site Permissions".
![Screenshot_20200216-113719_Firefox Nightly](https://user-images.githubusercontent.com/45702110/74599279-d3bc7c00-50b1-11ea-9bdc-23439290cfd5.jpg)

### Device information

* Android device: Samsung Galaxy A50 - Android 9 - One UI 1.1
* Fenix version: 200212 18:00 (Build #20431806)
    32.0.0, 747da16b0
    74.0a1-20200210093912

**Comment by lepiku** [comment]
this bug can also be seen on #5339

**Comment by lepiku** [comment]
This issue has been resolved in #8475

**Comment by ekager** [comment]
Hey @lepiku we keep our issues open for QA to verify and then close. Thanks! :)

**Comment by lepiku** [comment]
Ooh I see, sorry for closing too early. I didn't know about eng:qa:needed label because It is not in described in https://github.com/mozilla-mobile/fenix/wiki/Triage-Process

**Comment by LaurentiuApahideanSV** [comment]
Verified as fixed on Beta 4.0.0-beta.1 (Build #20500409) 2/19 using a Huawei MediaPad M3 (Android 7.0) and Samsung Galaxy S8+ (Android 8.0.0)
