### ISSUE TITLE
The progress bar makes page load feel slow

### ISSUE THREAD

**Issue by 90du** [mozilla-mobile/fenix#8451]
Progress bar is too big, feel the page load slow! The toolbar suggests adding a fixed switch

**Comment by mcomella** [comment]
@90du Thanks for filing – what do you mean by "the toolbar suggests adding a fixed switch"?

**Comment by 90du** [comment]
Visual problems. The progress bar should be as unobtrusive as possible！

**Comment by 90du** [comment]
A switch should be added to the Settings to control whether the toolbar is automatically hidden

**Comment by mcomella** [comment]
> A switch should be added to the Settings to control whether the toolbar is automatically hidden

I believe this is https://github.com/mozilla-mobile/fenix/issues/8801 – let me know if I am mistaken!

**Comment by mcomella** [comment]
I haven't heard of any other perceived progress bar problems and we don't have any specific actions we can take to improve it so I'm going to close this for now: please reopen if you think this is in error.
