### ISSUE TITLE
pdf.js support

### ISSUE THREAD

**Issue by 532910** [mozilla-mobile/fenix#8452]
Please make pdf files viewable in fenix.

Old issue for fennec in  mozilla/pdf.js 
https://github.com/mozilla/pdf.js/issues/6136

An extension than works with fennec:
https://github.com/M-Reimer/android-pdf-js/issues/6

**Comment by cadeyrn** [comment]
Duplicate of #4337.

**Comment by 532910** [comment]
OK.
