### ISSUE TITLE
[Bug] Some items under Settings, Main Menu and Site Security panel are not translated

### ISSUE THREAD

**Issue by brampitoyo** [mozilla-mobile/fenix#8453]
First reported by @AmyYLee.

## Steps to reproduce

1. Go to Settings → Languages
2. Select a non-English language
3. Observe items:
    - Settings → Customize
    - Settings → Privacy and security
    - Settings → Private browsing
    - Settings → Add-ons
    - Main menu → Add to top sites
    - Main menu → Add-ons Manager
    - Lock icon → Secure Connection

### Expected behavior

Items should be translated.

### Actual behavior

Items are not translated. They are set in English.

<img width="360" src="https://user-images.githubusercontent.com/51007/74621455-ee6e1e00-51a1-11ea-8963-a2fb1909ae79.png">
<img width="360" src="https://user-images.githubusercontent.com/51007/74621457-f0d07800-51a1-11ea-8654-1ec3dad18420.png">

### Device information

* Android device: all
* Fenix version: all

**Comment by darkwing** [comment]
@boek Are we frozen on strings?  Is this actionable?

**Comment by boek** [comment]
@darkwing Nope! They're marked for translation. Some locales are still working on translating all the new strings. You can see the status here: https://pontoon.mozilla.org/projects/android-l10n/

For extensions, is there anything that we have to do @csadilek?

**Comment by Amejia481** [comment]
@boek unfortunately this is a known issue https://github.com/mozilla-mobile/fenix/issues/8188#issuecomment-588300299, we need some changes on GV, for now the work around is to close the app and and open it again, then the extension should be translated if support the selected locale
