### ISSUE TITLE
Remove back button from search screen

### ISSUE THREAD

**Issue by brampitoyo** [mozilla-mobile/fenix#8454]
Adapted from https://github.com/mozilla-mobile/fenix/issues/7841#issuecomment-585428921.

We’ve decided against shipping the back button on the search screen (#6666) for a number of reasons:

- It introduces a list scanning issue by breaking icon and text alignment (ie. the search icon on the URL bar misalign with the search engines underneath).
- It’s internally inconsistent: we have recently removed the UI Back button from the menu, because we’ve decided to rely on the system back (whether that’s a visible button or a gesture).
- We have no other indicator besides #6666 that users struggle to get back from this screen.

**Comment by Cheap-Skate** [comment]
Could you instead change the behavior of the X button at the right hand side of the Fenix text bar to match Fennec's behavior?

Fennec:- X is a universal escape button from edit mode. It's always present whatever text is in the text box, and it always escapes from edit mode and takes me back to my Web content.

Fenix:- 
X just deletes the text in the text box
---> seems redundant, I can do this with my keyboard by overtyping or using the backspace key
X is not omnipresent, it disappears when there is no text in the text box
---> confusing, leads to limbo states like #6666 with no obvious escape

IMHO adopting the Fennec behavior has advantages
- obvious & omnipresent escape back to web content
- no confusing limbo state like #6666
- more Fennecesque behavior will please Luddite graybeards like me ;)

**Comment by brampitoyo** [comment]
@Cheap-Skate I still vote for removing the back button for behaviour consistency reason.

However, I agree with you that the behaviour of the “Clear text” ⊗ icon may be reconsidered further.

We should discuss this in a separate issue – let’s file one. In the meantime, here are some points to consider.

- In Fenix, ⊗ was designed to be a “Clear text” action
- In Fennec, ✖️ was designed to be a “Cancel” action
- Every time you see an ✖️ to the right of search bars in other Android apps (e.g. Contacts, Files, Google Calendar, Gmail, Settings), they always perform a “Clear text” action
- By choosing “Cancel” as an action, Fennec’s ✖️ didn’t behave like other Android apps

My challenge would be to think about how we might give users a clear and easy way to revert search decisions:

- If on the search screen, then how to go back to the homescreen
- If keyword/URL is already typed, then how to clear it

But as I wrote in comment 0, please note that “Cancel” can already be performed using:

- System back button (Android <9)
- Swipe back gesture (Android 10)
- Down button on the bottom of the keyboard (Android 9 & 10)

Also note: in Chrome, Edge and Brave, ✖️ means “Clear text” – same as us. One of the few exceptions, where ✖️ performs “Cancel”, seems to be Opera Touch.

**Comment by brampitoyo** [comment]
@sblatz My comment doesn’t impact this issue at all, so feel free to continue passing to QA :-)

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly Build #20550606 from 02/24`** using the following devices:
• Google Pixel 3a XL (Android 10)
• Google Pixel 3a (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

► Screenshot
![rsz_screenshot_20200224-102249](https://user-images.githubusercontent.com/51314259/75137421-3c2ddd80-56f0-11ea-94b5-e55f1b0c10df.png)
