### ISSUE TITLE
[Bug]Fast multiple tapping the back button from the Settings will close the app

### ISSUE THREAD

**Issue by sv-sdeiac** [mozilla-mobile/fenix#8460]
# Prerequisites
The Toolbar needs to be set to the bottom.

## Steps to reproduce
1. Go to Settings;
2. Fast double tap on the back button.

### Expected behavior
1. You are redirected to the Homepage.

### Actual behavior
2. The app is closing after fast tapping multiple times.

### Device information

* Android device: Samsung Galaxy S8 (Android 9).
* Fenix version: Firefox Preview Nightly 2/16 #20470606.
* Notes: This issue is reproducible for everywhere you fast tap multiple times the back button.
![20200217_144846](https://user-images.githubusercontent.com/40264165/74655324-de037680-5194-11ea-9bd6-42319c8a7a98.gif)

**Comment by mcarare** [comment]
Am I missing something? A double tap means two back button pressing, and it is normal that the app is closed.

**Comment by sv-sdeiac** [comment]
Hi @mcarare. 
I my opinion is that the actual behavior is not quite normal since the first tap of the back button leads you to the Homescreen of the app, the second tap is not an actual "back" action. 
I my opinion is that the application need to ignore the next "back" button tap since it is just a transition from a screen to another screen.

**Comment by mcarare** [comment]
> Also, please notice that I used the back button from the top left part of the app and not the android back button.

@sv-sdeiac That is a whole different story. I will investigate this, thank you for providing additional details!
