### ISSUE TITLE
[Bug] "Show in private sessions" selection square is out of place

### ISSUE THREAD

**Issue by Lululalu** [mozilla-mobile/fenix#8462]
### Expected behavior
It's supposed to be good looking and aligned to the rest of the interface, isn't it?

### Actual behavior
![Screenshot_20200217-101541_Firefox Preview](https://user-images.githubusercontent.com/32398857/74657669-7edf3b00-516f-11ea-8266-645a66385f3b.jpg)

### Device information

* Android device: Galaxy Tab S3 Android 9.0
* Fenix version: 3.2.0

**Comment by s-ankur** [comment]
Seems to be fixed now. Can be closed

**Comment by sflorean** [comment]
Closing as fixed. The issue isn't reproducible on Nightly 10/29.
