### ISSUE TITLE
[Bug]Improperly displayed Enhanced Tracking Protection CFR after rotation

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#8465]
## Prerequisites
Have a clean profile or a fresh install of Fenix. 

## Steps to reproduce
1. Navigate to Cnet.com
2. While the page is loading rotate the device to landscape view
3. After the page is loaded and the ETP CFR is displayed rotate the device back to portrait view

### Expected behavior
The ETP CFR is propely displayed, (above the ETP shield)

### Actual behavior
After rotating the device back to portrait view, the ETP CFR is misaligned.

### Device information
* Android device: 
• Samsung Galaxy S7 (Android 7.0.0)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

* Fenix version: Nightly Build #20470607 from 2/16
 
### Notes
❗ Not reproducible on the following devices:
• Google Pixel 3a (Android 9)
• Samsung Galaxy S9 (Android 8.0.0)

► Video
![20200218-225333](https://user-images.githubusercontent.com/51314259/74658964-0cd11b00-519c-11ea-864e-917800aa7c06.gif)

**Comment by abodea** [comment]
Verified as fixed in Nightly from **4/24** with **Google Pixel 4 XL (10).**
