### ISSUE TITLE
[Bug] The logger page does not redirect if it was previously opened

### ISSUE THREAD

**Issue by DanielOrban** [mozilla-mobile/fenix#8467]
## Prerequisites

- uBlock Origin is installed and enabled in Fenix

## Steps to reproduce
1. Navigate to a website with ads (eg. www.bbc.com).
2. Tap on the three-dot menu and tap on the uBlock Origin's icon.
3. Open the logger and navigate back to the previous tab (the website page).
4. Repeat step 2 and try to open the logger.
### Expected behavior
The page is redirected to the logger tab.
### Actual behavior
The current page is refreshed and does not redirect to the logger tab.
### Device information
* Android device:
-Samsung Galaxy S7 (Android 8.0.0)
-Samsung Galaxy S7 Edge (Android 8.0.0)

* Fenix version: 
Nightly 200216 (Build #20470607) 

![The logger page does not redirect if it was previously opened](https://user-images.githubusercontent.com/43445968/74664967-6c80f380-51a7-11ea-9fda-c80a1fcec545.gif)

**Comment by csadilek** [comment]
Blocked on: https://bugzilla.mozilla.org/show_bug.cgi?id=1616625

**Comment by sflorean** [comment]
Reproducible also with the uBlock dashboard in private browsing, only if is already opened in normal browsing. 
Devices: Sony Xperia Z2 (Android 6.0.1), Google Pixel (Android Q)

**Comment by csadilek** [comment]
@DanielOrban this is fixed now in the latest Nightly. Can you verify?

**Comment by DanielOrban** [comment]
@csadilek , I verified this issue. It is not reproducible anymore.
Issue tested and marked as fixed in Nightly 200311 (Build #20711809).

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly Build #20770606 from 3/17`** using the following devices:
• Google Pixel 3a (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S6 (Android 7)
• OnePlus A3 (Android 6.0.1)

► Video Normal Browsing
![20200317-111213](https://user-images.githubusercontent.com/51314259/76841863-0b9a1900-6842-11ea-8121-73dd57f05bd3.gif)


► Video Private Browsing
![20200317-111303](https://user-images.githubusercontent.com/51314259/76841998-3edca800-6842-11ea-85af-a5bf895a04be.gif)
