### ISSUE TITLE
Autocomplete in the URL bar - I find confusing

### ISSUE THREAD

**Issue by Cheap-Skate** [mozilla-mobile/fenix#8468]
I filed #6290 and I didn't realise that appending a search suggestion to the URL is normal behavior in Fenix.

For example if I have www.bbc.co.uk as my URL and I tap the URL bar, the URL bar moves to the top, but www.bbc.co.uk/news is shown in the URL.

I find it confusing because
- desktop and Fennec do not do it
- it feels broken because it does not occur on every URL. For example www.bbc.co.uk gets /news appended, but arstechnica.com gets nothing appended.

I understand where you're coming from but as you can see from #6290 it took me a long time to realise that this is not a Fenix bug, it's a feature!

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-15765)

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807743

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
