### ISSUE TITLE
[Bug][RTL] Radio buttons for the Theme selection on the welcome screen are overlapping the images

### ISSUE THREAD

**Issue by ItielMaN** [mozilla-mobile/fenix#8469]
Originally filed in [bug 1616101](https://bugzilla.mozilla.org/show_bug.cgi?id=1608218):
![תמונה](https://user-images.githubusercontent.com/18016656/74678958-2470c980-51c5-11ea-8653-cddfc44280f3.png)

The radio buttons should be placed in the punch holes.

**Comment by ekager** [comment]
CC @Mugurell if you wanted to take another look, otherwise anyone can pick this up, but we should definitely fix ASAP

**Comment by ekager** [comment]
As part of this ticket let's:
- Check if we can use `autoMirrored="true"` to truly adapt these layouts for RTL
- Verify that these radio buttons _work_ correctly for RTL
- and make sure that the onboarding toolbar position picker is consistent with the theme picker in layout and function

Thank you!

**Comment by sv-sdeiac** [comment]
Verified as fixed using the latest version of Firefox Preview Nightly 2/21 #20520606.
Device: Samsung Galaxy S8 (Android 9).
