### ISSUE TITLE
Change "back" button behavior from search bar so 1 press to go back to URL bar

### ISSUE THREAD

**Issue by Cheap-Skate** [mozilla-mobile/fenix#847]
Move to Search bar by tapping URL bar
Try to return to normal view with URL bar at the bottom of the screen. Fenix takes 2 presses of Android "back" button, Chrome takes only 1.

Fenix:-
- first press of Android "back" button hides keyboard
- second press of Android "back" button returns me to URL bar at bottom of screen

Chrome
- first press of Android "back" button does both (hides keyboard & returns to URL bar)

Chrome is easier to use & more intuitive, it would be great if Fenix did the same

**Comment by sblatz** [comment]
This seems like a nice usability change!

**Comment by sblatz** [comment]
I [created an a-c ticket for this](https://github.com/mozilla-mobile/android-components/issues/2255)

**Comment by bsurd** [comment]
Verified as fixed on: Samsung Galaxy Note 8 (Android 9), Google Pixel (Android 9) & Nexus 5 (Android 6.0.1). Build: 1.0.1911 (#10731207)

**Comment by Cheap-Skate** [comment]
Fixed for me too - nice - thanks!
