### ISSUE TITLE
Enhance browser toolbar

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/fenix#8474]
## User Story
- As a user, I want to easily find and understand available toolbar options and use them effectively, so I can have a fast and intuitive browsing experience. 

### Acceptance Criteria

- [ ] I know when reader mode is available without being confused or distracted (possible solution: reader mode badge in the nav bar once we are able to just show the clean URL)

It looks like users find the current behaviour either confusing or irritating, and overall not useful. Highlights of some user feedback:
- Some users assume blue dot is highlighting reader mode being either a new feature or notifying that we made changes to reader node. They expect the blue dot to go away after they interact with reader mode once, and they find it confusing when it doesn't.
- Many sites can be viewed in reader mode which means the blue dot does appear very often. Many users find that irritating and annoying and it has caused some users to drop off (self-reports).
- The frequency of showing the blue dot, also means that the blue dot is not accomplishing its objective of notifying users of the availability of reader mode, PWA, or open in app option, since users will begin to ignore it.

- [x] Page actions in a similar category are grouped together for easier interaction (add to collection, add to top sites,  add to bookmarks, add to homescreen) so they are faster to locate and use. 
- [x] Remove "Help" from browser toolbar as it is very rarely used. 

------

**UX designs** 
Updated Mar 5, 2020 by @topotropic 

- grouped page actions
- grouped site specific actions like “Reader mode” or “Open in app” and displayed them at the bottom (with app bar bottom) or at the top (with toolbar top)
- removed open “new site” and open “new private tab” to de-clutter the menu, assumption here is that opening a new tab is a quick endeavour anyway and de-cluttering the menu is valuable to more people because they don’t feel overwhelmed and disoriented by the menu
- increased menu width to 280dp
- removed "Help" from menu as it is very rarely used

Site menu with the minimal amount of menu entries:
- [design for bottom app bar](https://share.goabstract.com/6a1bcc22-bd3a-497a-bf7b-39ec63dd2ea5?mode=design&sha=f558afe550c8c271f9c1eb2292f096ba69ceecdb) 
- [design for top app bar](https://share.goabstract.com/21538152-fa26-4a7a-95d7-a75d220d1b25?mode=design&sha=f558afe550c8c271f9c1eb2292f096ba69ceecdb)

Site menu with site specific menu entries (like "Reader mode", "Open in app"):
- [design for bottom app bar](https://share.goabstract.com/93d2920c-7285-4ad2-b780-48dabf449396?mode=design&sha=2e3d383e7e4bf60ae0d1902418fb2416d2380380)
- [design for top app bar](https://share.goabstract.com/abf7218f-3f78-437a-8ed9-d5c707869319?mode=design&sha=2e3d383e7e4bf60ae0d1902418fb2416d2380380)

**Comment by topotropic** [comment]
this issue addresses some of the feedback around the blue dot notification https://github.com/mozilla-mobile/fenix/issues/7408

**Comment by sv-ohorvath** [comment]
Items removed and reordered, verified as fixed on Beta 4.1.
