### ISSUE TITLE
Private browsing explanation spannable broken

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#848]
Looks like this may have been introduced with https://github.com/mozilla-mobile/fenix/commit/7c3bc3a162d3d823ea0f328b3a269e93f9550faa

![screenshot_20190305-073154_fenix](https://user-images.githubusercontent.com/4400286/53816777-0ad56400-3f19-11e9-8f18-acc651ba5aea.jpg)

**Comment by sv-ohorvath** [comment]
Verified as fixed on a Nexus 5 and Pixel. Build: master 3/11.
