### ISSUE TITLE
Pocket Top Articles top site is present for locales different than EN

### ISSUE THREAD

**Issue by Diana-Rus** [mozilla-mobile/fenix#8480]
Pre-requisites:
- Have a different language set then EN locale, in my case I used Deutsch(German).

## Steps to reproduce
1. Open app.
2. Check the "Default Top Sites" list.

### Expected behavior
The Pocket Top Articles is not displayed for non EN-locales, only Wikipedia and YouTube default top sites are displayed.

### Actual behavior
The Pocket Top Articles top sites is displayed for non EN-locales.

Note:
- The actual result is the same for Shquip(Albanian) Cestina(Czech), Espanol(Spanish), Francais(French), Italiano(Italian), Pусский(Russian).
- The Default top site list is not updated
                                  * when the language is changed
                                  * nor when closing and opening the app 
                                  * neither when putting the app in background and bringing it in foregorund afterwards.

### Device information
* Android device: Samsung Galaxy Note9 (Android 9), Samsung Galaxy S8+ (Android 8.0.0), Sony Xperia Z5 (Android 7).
* Fenix version: Firefox Preview Nightly 200218 (Build #20490607) GV: 75.0a1-20200217095003

Ticket related to: https://github.com/mozilla-mobile/fenix/issues/8126

![20200218-133913](https://user-images.githubusercontent.com/49859863/74733269-a3f9a980-5254-11ea-94b2-fa09095e737a.gif)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-15775)

**Comment by abodea** [comment]
I was able to reproduce this on the latest Beta build 4.0.0-RC1 with Google Pixel 3a XL (Android 10).

**Comment by ekager** [comment]
Currently, the default top site list is not updated when changing locales. On first install, they are just added to the list. 

I opened #9286 to look into this more.

**Comment by Diana-Rus** [comment]
Hi, as an extra note this issue is also reproducible when interchanging device language, after the first install, not only in app language.

**Comment by AndiAJ** [comment]
**Still reproducible** on **`86.1.0 RC1`** using a OnePlus A3 (Android 6.0.1)

**Comment by amocirean** [comment]
Reopening as issue is still reproducible on Firefox Beta 109.0b1.
