### ISSUE TITLE
[Bug] Start browsing button background changed

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#8481]
## Steps to reproduce
1. Clear app data/ first run after install.
2. Scroll down the onboarding screen. Observe the Start browsing button.

### Actual behavior
![startbrowsingbutton](https://user-images.githubusercontent.com/4037709/74740468-9a2b7280-5263-11ea-96a5-ab2877bc1f35.png)
### Device information

* Android device: any
* Fenix version: Nightly 2/18

**Comment by brampitoyo** [comment]
We should follow the design of mocks that @apbitner had designed.

Keep in mind that Metropolis should be used as the button’s font (addressed in #6986).

**Comment by mcarare** [comment]
This looks fixed to me. QA please confirm!

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly Build 200625 from 6/25`** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)

► Screenshots
![rsz_screenshot_20200625-161551](https://user-images.githubusercontent.com/51314259/85727883-11847d80-b700-11ea-9066-58b2d37b75ad.png)
