### ISSUE TITLE
[Bug]Screen flickers after background/foreground or lock/unlock screen

### ISSUE THREAD

**Issue by vladbencovici** [mozilla-mobile/fenix#8484]
## Steps to reproduce
1. Open fenix app.
2. Navigate to a website.
3. Perform lock/unlock screen or background/foreground.
4. Check the screen after performing one of the actions from above.

### Expected behavior
The screen should load successfully.

### Actual behavior
The screen flickers after performing a lock/unlock or background/foreground action.

### Device information

* Android device: Google Pixel C (Android 8.0.0), Huawei MediaPad M3 Lite 10 (Android 7.0)
* Fenix version: Firefox Preview Nightly 200218 (Build #20490606) GV: 75.0a1-20200217095003

![device-2020-02-18-154049](https://user-images.githubusercontent.com/57618010/74745238-3bb6c200-526c-11ea-8b64-999dfea71722.gif)

**Comment by AndiAJ** [comment]
**Not reproducible** anymore on the latest on the latest **`Nightly Build 201111`** using the following devices:
• Google Pixel 3a (Android 11)
• Huawei Mate 20 Lite (Android 10)
• OnePlus A3 (Android 6.0.1)
