### ISSUE TITLE
[Bug] Add "Remote debugging via USB" and "LeakCanary" under Advance option in settings

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/fenix#8485]
## Steps to reproduce
1. Reach settings.
2. Observe the `Remote debugging via USB` and `LeakCanary`.
### Expected behavior
`Remote debugging via USB` and `LeakCanary` should belong under the `Advanced` based on this [comment.](https://github.com/mozilla-mobile/fenix/issues/5905#issuecomment-587237757)
### Actual behavior
`Remote debugging via USB` is under `Developer tools(it needs to be removed) and `LeakCanary` is under `Privacy and Security` in settings.
### Device information

* Android device: **All.**
* Fenix version: **Nightly 2/18.**

![Screenshot_20200218-164825_Firefox Nightly (1)](https://user-images.githubusercontent.com/42831109/74747683-fdbb9d00-526f-11ea-827b-b1f12407b771.jpg)

**Comment by vesta0** [comment]
The mocks should also include `LeakCanary`

**Comment by abodea** [comment]
Verified as fixed on the latest Nightly **3/30** with **Google Pixel 4 XL (10), Samsung Galaxy S7 (7).**
Note that The `Remote debugging via USB` and `LeakCanary` (only for debug builds) are displayed correctly under the Advance option in settings.
