### ISSUE TITLE
[Bug] "Start Firefox Nightly" Button tap crashes app

### ISSUE THREAD

**Issue by lwa-moz** [mozilla-mobile/fenix#8488]
## Steps to reproduce
Click on "Update Complete: Firefox is updated - and improved!" notification in notification bar. 
Firefox Nightly is opened to the "Welcome to the all-new Firefox Nightly" screen in the app. All browsing data check marks are checked.
Click "Start Firefox Nightly"
Video: https://mozilla.slack.com/files/UR8FN2MNZ/FU55V9X1A/20200218_120737.mp4

### Expected behavior
App homescreen is resolved.

### Actual behavior
App closes/crashes

### Device information
Google Pixel 3
* Android device: Android OS 10
* Fenix version: Nightly 200214 08:03

**Comment by Sparky93** [comment]
I think this should've been fixed by [#6003](https://github.com/mozilla-mobile/android-components/issues/6003)

**Comment by pocmo** [comment]
https://github.com/mozilla-mobile/fenix/commit/388c7017d8378500eb986e5473465572055d804a

**Comment by ebalazs-sv** [comment]
Verified as fixed on Fennec Beta Migration Build 2, 02/27 with LG G7 fit (Android 8.1). "Update complete" notification displays the onboarding screen.
I will move this to Done. Thanks.
