### ISSUE TITLE
[Bug] Can't log in to reddit.com

### ISSUE THREAD

**Issue by st3fan** [mozilla-mobile/fenix#8494]
> https://bugzilla.mozilla.org/show_bug.cgi?id=1615318

STR:

    Visit https://www.reddit.com/login

Expected:

Site loads.

Actual:

Brower hangs. (See screenshot on Bugzilla)

**Comment by kbrosnan** [comment]
This works for me using Nightly from Feb 14.

**Comment by abodea** [comment]
Verified as fixed on **Nightly 4/28** with **Google Pixel 4 XL (10), Samsung Galaxy S9 (9), Sony Xperia Z5 (7), OnePlus A3 (Android 6.0.1).**

Please note I did many logins + a sign-up and everything worked as expected, I was successfully logged in.
