### ISSUE TITLE
[Bug] Search bar in Firefox Preview is unusable with Japanese IME

### ISSUE THREAD

**Issue by st3fan** [mozilla-mobile/fenix#8495]
> https://bugzilla.mozilla.org/show_bug.cgi?id=1615353

User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:72.0) Gecko/20100101 Firefox/72.0

Steps to reproduce:

>Tap the "Search or enter address" bar
>Type 渋谷 ("shibuya") with a Japanese IME.
For those who are unfamiliar with japanese text input:
You type latin characters, for example "s" then "h" then "i".
This will then be automatically replaced by the IME with し which means "shi".
Continue typing then rest of "shibuya". Then hit space.

Actual results:

The entered text is: 
shしbうや

For information, this is equivalent to:
sh(shi)b(u)(ya)

Expected results:

The entered text should be:
渋谷 (shibuya)

I am very sure that this bug is because of WEBSITE AUTOCOMPLETION.
When I type the first latin character "s", the search bar starts suggesting "spiegel.de"
When I then type the "h", it starts autocompleting to "shutterfly.com".
When I then type the "i", the bar only says "sh" (this is already wrong, it should say し)
When I then type "b" it says shしb. It should say しb.
When I then type "u" it says "shしbう". This is another error, because "bu" should fuse into ぶ (bu), not into bう (u).
The final "ya" enters correctly as や (ya).
After that, hitting space should turn the previously written しぶや (shibuya) into 渋谷 (shibuya). However, this doesn't work, because the previously written stuff is not しぶや, it's the buggy input shしbうや.

**Comment by Negirno** [comment]
I have the same issue if I use the Japanese keyboard in Firefox Preview on my Samsung Galaxy 5 Mini and GalaxyTab S 8.4, although I can always convert kana to kanji, although with "garbage" characters before it like this: "sh渋谷". On rare occasions (maybe because I type fast enough) I don't get these garbage characters.

I'm getting this on all kinds of input boxes, not just with website autocomplete.

**Comment by softvision-miralobontiu** [comment]
I was able to reproduce on the 11/18 Nightly build with Samsung Galaxy Tab S6 (Android 10).

**Comment by lobontiumira** [comment]
I was not able to reproduce this issue anymore on the 5/24 Nightly build with Samsung Galaxy Note 8 (Android 9).
