### ISSUE TITLE
[Bug] Tab closed with Close all Tabs comes back from the dead

### ISSUE THREAD

**Issue by st3fan** [mozilla-mobile/fenix#8496]
> https://bugzilla.mozilla.org/show_bug.cgi?id=1615856

User Agent: Mozilla/5.0 (Android 9; Mobile; rv:75.0) Gecko/75.0 Firefox/75.0

Steps to reproduce:

- Firefox Nightly / Preview
- Opened tabs are explicitly cleared on quit
- Multiple tabs open
- Close all Tabs
- Quit Firefox
- Restart Firefox

Actual results:

Last tab opened in previous session gets restored

Expected results:

No tabs opened at all

**Comment by DrMcCoy** [comment]
Ah, my apologies, I didn't know that this is the correct place to report now

**Comment by ekager** [comment]
Closing because undo logic has changed with tabs tray
