### ISSUE TITLE
[Bug]  Muted or Audioless media pauses background apps

### ISSUE THREAD

**Issue by st3fan** [mozilla-mobile/fenix#8497]
> https://bugzilla.mozilla.org/show_bug.cgi?id=1615918

User Agent: Mozilla/5.0 (X11; Linux x86_64; rv:72.0) Gecko/20100101 Firefox/72.0

Steps to reproduce:

1. Play audio in another app E.G. Spotify, Podcast Addict
2. Browse reddit
3. View a muted/audioless video (gif, mp4, webm)
 - example post: https://www.reddit.com/r/sports/comments/f4r524/fastest_bowling_strike/
 - video link: https://external-preview.redd.it/Pimcs9GJ2bJn54kqRabr1vOxcGz_HUEbVf2n7VVKaxY.gif?format=mp4&s=8a531a46ccc842530dc1fcb6742f4ac584a3e084

Samsung s10e
Android 10
Firefox Preview 3.2.1 and Firefox Mobile 68.5.0

Actual results:

The background app (Spotify, Podcast Addict) pauses

Expected results:

The background app should have continued playing, a muted video should not request audio focus.

**Comment by kbrosnan** [comment]
https://github.com/mozilla-mobile/android-components/pull/6432

**Comment by ekager** [comment]
Closing for #6146 and this should be resolved now!

**Comment by fallaciousreasoning** [comment]
This is still occuring for me, as of build 22140616

**Comment by kbrosnan** [comment]
Please open a new issue describing the exact apps and websites where background media playback is paused.
