### ISSUE TITLE
[Private Browsing] Private Browsing Shortcut doesn't allow switching back to Normal mode

### ISSUE THREAD

**Issue by AmyYLee** [mozilla-mobile/fenix#8498]
Can switch between PBM and Normal mode, but the theme is not being applied correctly.

Steps to reproduce
1. Set a private browsing shortcut via Settings -> Private Browsing
2. Open PBM through the shortcut on homescreen
3. Open a Private tab
4. Go back to homescreen
5. Tap on the Private Browsing icon

Expected behavior
Toggles between regular and PBM when you tap on the PBM icon

Actual
Shows regular homescreen with PBM theme, when you toggle back to PBM your tabs are gone.

Screen recording: https://share.getcloudapp.com/wbumyonA

### Device information

* Android device: Pixel 3
* Fenix version: Nightly

**Comment by Lull3n** [comment]
I get the same issue with nightly if I close a private tab through trough the notification.

**Comment by liuche** [comment]
If you're in Private Mode, I'm also seeing that when you clear all your tabs from the notification, you get stuck in Normal mode theme.

**Comment by sblatz** [comment]
I think @boek was working on something with the way theme manager applied them based on the mode recently. Possible we have a regression here? I may have also caused this when changing "persistent" private mode, but I think we would've caught this a while ago 🤔

**Comment by psymoon** [comment]
@AmyYLee The fix was merged yesterday, can you please verify this?

**Comment by sv-sdeiac** [comment]
Verified as fixed using the latest version of Firefox Preview Nightly 2/24 #20550606.

Devices:
- Motorola Moto G6 (Android 8);
- Samsung Galaxy S8 (Android 9).
