### ISSUE TITLE
Make private browsing mode clear to TalkBack users

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#850]
Follow-up to #804:

From @eeejay
> We need to figure out a prominent way for TalkBack users to know they are in private browsing. Right now, they would need to check the state of this button or read the private browsing copy in the private browsing home screen.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-15791)

**Comment by mheubusch** [comment]
@eeejay do we need to have actual text present on the screen in the address bar area or can we handle by updating the alt text of the PB button to say Private Browsing Mode On or is there other alt text we deploy to show state change from normal to private mode?

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807556

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
