### ISSUE TITLE
[Bug] Video Playback Errors and GIF playback errors in Firefox for Android

### ISSUE THREAD

**Issue by st3fan** [mozilla-mobile/fenix#8503]
> https://bugzilla.mozilla.org/show_bug.cgi?id=1613446

*More details in the Bugzilla bug*

User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.3 Safari/605.1.15

Steps to reproduce:

Try to play any video or GIF on any web page. This happens on all of the latest Firefox releases, be it stable, beta, or preview editions. I am on Android 10 on a Samsung Note10+ phone. No add-ons are enabled. Clearing cache/data does not help. Reinstalling app does not help. It is not a connection problem, this happens on both WiFi and 5G data connection.
See video of this happening here:
https://www.youtube.com/watch?v=TXY2ukA6cRg

Actual results:

Videos end with all sorts of error messages and don't play the next video in the queue, or "glitch out" and flash randomly black colors.  GIFs do not loop as they are supposed to, or experience the same issues as the videos.
Please see the video of this happening here:
https://www.youtube.com/watch?v=TXY2ukA6cRg

Expected results:

Videos should play with no error messages, and start the next video in the playlist. GIFs should loop.

**Comment by Photogad** [comment]
+1 / follow

**Comment by liuche** [comment]
https://blog.elementary.io/appcenter-spotlight-planner/

**Comment by Amejia481** [comment]
This will be addressed on https://github.com/mozilla-mobile/android-components/pull/5953 and https://github.com/mozilla-mobile/fenix/pull/8618

**Comment by Baron-Severin** [comment]
@vesta0 we can allow/block audible autoplay (affects video and audio that is unmuted), and inaudible autoplay (affects muted videos).  Note that many things that look like GIFs are actually muted videos, **_and will be blocked under the second setting_** (also true on desktop).

Right now, we only expose this to users:
<img width="370" alt="Screen Shot 2020-02-26 at 3 02 09 PM" src="https://user-images.githubusercontent.com/13170306/75396280-fb2cf900-58a8-11ea-8a44-826f94644c05.png">



Should we:
1 - always allow inaudible autoplay: this means muted videos would always play regardless of the setting.

2 - have inaudible autoplay follow audible autoplay's setting: this means we would unexpectedly block some things that look like GIFs ([example](https://github.com/mozilla-mobile/fenix/issues/8503#issuecomment-588570686)).

3 - expose a third “Block audio” option to users, similar to desktop: this is [already on the roadmap](https://github.com/mozilla-mobile/fenix/issues/8017), but would need a new String.

**Comment by vesta0** [comment]
Hey @Baron-Severin I assume we don't have a way of differentiating between video files and GIFs or animations which makes sense, and also it seems like "block video autoplay" doesn't just stio the GIF from being animated but blocks it entirely. If that's all true, then I recommend option 3 (adding the "block audio only" as default). Although I thought we needed GV work for that and that's why it was scoped out initially - is that no longer the case?

If that works, then we can use the [original mocks](https://app.abstract.com/share/cdba1651-670e-4412-8721-4d70ca025ffd?collectionLayerId=35603d5c-263c-4c70-b3fe-1ae23bd449c8&mode=design&sha=49143c0fafdf6c2d01f7c0b665c92a9fb7c0ebec) for the string and ask Jeff to see if we can uplift it for localization for April?

**Comment by Baron-Severin** [comment]
> Although I thought we needed GV work for that and that's why it was scoped out initially - is that no longer the case?

That API was recently exposed, so we should be good to go.

> If that works, then we can use the original mocks for the string and ask Jeff to see if we can uplift it for localization for April?

Sounds good, I'll get started on it.

**Comment by liuche** [comment]
I think these commits are related to pre-work for this bug, but now that that PR is landed, this should be ready to work on. May require exposing some APIs from GV through AC.

**Comment by Amejia481** [comment]
This is a related pr that needs review https://github.com/mozilla-mobile/fenix/pull/9372

**Comment by ekager** [comment]
Sounds like the prework is done and merged so labeling as eng:ready again

**Comment by ekager** [comment]
> Hey @Baron-Severin I assume we don't have a way of differentiating between video files and GIFs or animations which makes sense, and also it seems like "block video autoplay" doesn't just stio the GIF from being animated but blocks it entirely. If that's all true, then I recommend option 3 (adding the "block audio only" as default). Although I thought we needed GV work for that and that's why it was scoped out initially - is that no longer the case?
> 
> If that works, then we can use the [original mocks](https://app.abstract.com/share/cdba1651-670e-4412-8721-4d70ca025ffd?collectionLayerId=35603d5c-263c-4c70-b3fe-1ae23bd449c8&mode=design&sha=49143c0fafdf6c2d01f7c0b665c92a9fb7c0ebec) for the string and ask Jeff to see if we can uplift it for localization for April?

cc @vesta0 there have been some updates here.

It looks like gifs *are* distinguishable if they are truly gifs and not just muted videos - ie on giphy.com gifs are now being played with default "block audio and video" option. 

With that being said, should we still revisit the current default state? Is "block audio and video" as the default still desired now that we have added the new "block audio only" option and we _can_ distinguish between audible or inaudible video? To test the two different behaviors go to [googlechrome.github.io/samples/muted-autoplay](googlechrome.github.io/samples/muted-autoplay) and change the Fenix setting between "block audio and video" and "block audio only" (and refresh the page). Both videos are blocked with the default "block audio and video", but the muted video is allowed with "block audio only". It looks like Chrome Android and Firefox Desktop allows the first inaudible video to autoplay.

**Comment by vesta0** [comment]
Thanks @ekager for the detailed description and example :) 

Since gifs will play with the "block audio and video" option then I think our default should be "block audio and video" due to its impact on pageload performance + potential data saving.

Although, it looks to me like "block audio and video" is already our default and perhaps we never changed it to "block audio only" ?

**Comment by ekager** [comment]
Yes, exactly, we never actually changed the default. If we want to keep it as "block audio and video" then I think we can close this ticket since the comment 0 issue has been resolved AFAICT.

**Comment by vesta0** [comment]
Please QA the comment 0 issue and close this ticket if verified.

**Comment by yoasif** [comment]
Not sure if this is the same issue, but the video on this page is not playing if I set Fenix to request the desktop site: https://i.imgur.com/5dS6Ni4.gifv

Should I open a new issue?

**Comment by softvision-miralobontiu** [comment]
Verified as fixed - videos and GIFs play with no error messages. 
Tested on the 5/27 Nightly build with Sony Xperia Z5 Premium (Android 7.1.1), Google Pixel (Android 10), and Samsung Galaxy Note 8 (Android 9). 

* Note: "Block audio and video" is selected by default.
