### ISSUE TITLE
[ETP] Light theme is using the dark theme ETP shield icon

### ISSUE THREAD

**Issue by AmyYLee** [mozilla-mobile/fenix#8504]
Light theme is using the dark theme ETP shield icon in the search bar

Not sure if it is a regression of https://github.com/mozilla-mobile/fenix/issues/7814.

Device: Pixel 3
Nightly 

![image](https://user-images.githubusercontent.com/5992746/74773167-62223080-525f-11ea-9599-02aff352e784.png)

**Comment by ekager** [comment]
@AmyYLee could you recheck in nightly to see if these icons look better now? 
Thank you! :)

**Comment by AmyYLee** [comment]
> @AmyYLee could you recheck in nightly to see if these icons look better now?
> Thank you! :)

Looks good. Thanks
