### ISSUE TITLE
[Search] Update "open tabs" icon

### ISSUE THREAD

**Issue by AmyYLee** [mozilla-mobile/fenix#8505]
I will be providing an updated icon shortly that should fix this issue. We will be using an icon that is more similar to what we have on iOS.

New icon: https://drive.google.com/open?id=1uMxp5LKFEI5mbIJ2Q30E47hRcYz9snvJ
<img width="96" alt="Screen Shot 2020-02-19 at 11 19 06 AM" src="https://user-images.githubusercontent.com/5992746/74852089-22fce980-530a-11ea-93bd-9ac78afa025e.png">

<img width="166" alt="Screen Shot 2020-02-18 at 3 00 26 PM" src="https://user-images.githubusercontent.com/5992746/74773980-ed4ff600-5260-11ea-99b0-57c16165396d.png">

**Comment by kbrosnan** [comment]
Previously https://github.com/mozilla-mobile/fenix/issues/1541#issuecomment-488817536

**Comment by abodea** [comment]
Verified as fixed on the latest **Nightly 2/27** and **Beta 4.0.0-Beta2** with Google Pixel 3 (Android 9).
The open tab's icon is correctly displayed.
Based on my comment I will close this issue.
Note that for the ∞ number is placed more to the bottom, I added a comment to the main issue regarding the position of the numbers here https://github.com/mozilla-mobile/fenix/issues/5346

**Comment by madb1lly** [comment]
I'm not sure what the object of this bug is anymore since the title keeps changing, but if it is the offset numbers of tabs in the tab icon then I still have this bug: https://github.com/mozilla-mobile/fenix/issues/5346#issuecomment-592964260
