### ISSUE TITLE
[Bug] Upgrade from Fennec loses tabs' session history

### ISSUE THREAD

**Issue by buttercookie42** [mozilla-mobile/fenix#8511]
## Steps to reproduce
1. Visit a few pages within the same tab in Fennec. (E.g. browse through Wikipedia and follow a few links through to different articles)
2. Upgrade to Fenix.
3. Open the tab you previously had open in Fennec.
4. Attempt to go back in order to retrace your steps through the pages you've been reading in that tab.

### Expected behavior
1. I can go back to the page(s) I had previously visited in that tab.

### Actual behavior
I can't go back and am simply returned to the tab list. This is annoying and a data-loss issue, because after finishing the current page, I had intended to eventually retrace my steps back to the previous page, finish reading that page, eventually go back one more step and so until reaching the start of that tab's session history.

### Device information

* Android device: Motorola G4 Play, Android 6.0.1
* Fenix version: 200214 08:03, upgrading from Fennec Nightly 68.5a1

**Comment by kbrosnan** [comment]
This is expected behavior on migration. @pocmo

**Comment by kbrosnan** [comment]
We are not making any changes to migration code.
