### ISSUE TITLE
[Bug] CWTS preferences should look disabled when disabled

### ISSUE THREAD

**Issue by ekager** [mozilla-mobile/fenix#8514]
## Steps to reproduce
1. Starting syncing

### Expected behavior
CWTS checkboxes and text are clearly disabled

### Actual behavior
Checkboxes are disabled, but text doesn't look disabled 

### Device information

* Android device: ?
* Fenix version: ?

**Comment by sv-sdeiac** [comment]
Verified as fixed using the latest version of Firefox Preview Beta 4.0.0-beta.1.
Now both(text and checkboxes) are grayed when the sync is performed.

Devices:
- Nokia 6 (Android 7.1.1);
- Samsung Galaxy S8 (Android 9).
