### ISSUE TITLE
"Enable Private Browsing" text is still displayed while being in private mode

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/fenix#852]
## Steps to reproduce
1. Install and launch Fenix.
2. With the **`S-Pen`** hover the **`Private button`**.
3. Observe that the `Enable Private Browsing` text is displayed.
4. Tap on the **`Private button`**.
5. With the **`S-Pen`** hover the **`Private button`**.

### Expected behavior
While being in Private Browsing when hovering with **`S-Pen`** the **`Private button`** the **`Enable Normal Browsing`** text should be displayed.
### Actual behavior
`Enable Private Browsing` text is displayed when hovering with S-Pen.
### Device information

* Android device:  **`Samsung Galaxy Note 9 (Android 8.1.0)`**
* Fenix version: **`1.0.1910 (Build #10641207 🦎 67.0a1-20190227104426)`**
### Notes
For more details please see the [video](https://drive.google.com/file/d/16lNqJPF20e0xt2N-Z5bA1031-tdNaYC0/view)

**Comment by sblatz** [comment]
Thanks for filing 😄 

This will be fixed by [https://github.com/mozilla-mobile/fenix/pull/851](https://github.com/mozilla-mobile/fenix/pull/851) and is a dup of #804.
