### ISSUE TITLE
[Bug] Add-ons Manager and add-on sub-pages have inconsistent style compared to the rest of Settings

### ISSUE THREAD

**Issue by brampitoyo** [mozilla-mobile/fenix#8520]
## Steps to reproduce

- Go to Settings → Add-ons
- Go to Settings → Add-ons → uBlock Origin

-----

1. Style/spacing of headers (“Recommended”, “Enabled”, “Disabled”) should be identical to style/spacing of Settings headers (“Account”, “General”, “Privacy and security”)

![heading@2x](https://user-images.githubusercontent.com/51007/74797411-eb089d00-532f-11ea-8e49-aa9971f9fcb3.png)

-----

2. Style/size/spacing of individual add-on name and description, should be identical to style/size/spacing of Site Permissions.

The colour of rating stars is already correct.

![list-item@2x](https://user-images.githubusercontent.com/51007/74797618-61a59a80-5330-11ea-8fb8-75d4a2012c70.png)

-----

3. Style/size/spacing of add-on submenu items, should be identical to style/size/spacing of Settings list items.

![sub-page@2x](https://user-images.githubusercontent.com/51007/74797970-5737d080-5331-11ea-8524-9a579776e6d5.png)

-----

4. “On/Enabled” should be spaced so that its label aligns with item labels underneath.

![ON@2x](https://user-images.githubusercontent.com/51007/74798212-01175d00-5332-11ea-9ed1-eb4e15a52bd9.png)

<img width="360" src="https://user-images.githubusercontent.com/51007/74798333-6703e480-5332-11ea-921c-4ff6adb3be18.png">

-----

5. The icon used for “Permissions” under add-ons, should match the icon used for “Site Permissions” under Settings.

![permissions-icon@2x](https://user-images.githubusercontent.com/51007/74798692-4daf6800-5333-11ea-9f2c-15c9f25ce224.png)

-----

6. Style/size/spacing used for “Details” and “Permissions”, should match style/size/spacing in “About Firefox”.
    - Remove underlines on links, and link icons to the right of “Homepage” and “Learn more about permissions”. We can use the same link colour as “About Firefox”, with no underline.
    - Colour/style of horizontal rulers should be identical to those found in “About Firefox”
    - “Details” already has the correct text-to-page margin of 16px. This value can be kept intact.
    - We can also keep using left-aligned text on both “Details” and “Permissions”, and keep the text regular-weight (some parts of “About Firefox” uses bold, and it’s not suitable for long body of information).

![details-about](https://user-images.githubusercontent.com/51007/74799711-21491b00-5336-11ea-9207-56f0fa165cfa.png)

![permissions-about@2x](https://user-images.githubusercontent.com/51007/74800032-19d64180-5337-11ea-9304-4c6ca65015ad.png)

**Comment by Amejia481** [comment]
@brampitoyo would you mind taking a look? This will be available in the next nightly update :)

**Comment by brampitoyo** [comment]
@Amejia481 Thanks heaps for tackling this issue. I can confirm that our styles now matches Settings for the most part. Colours seem to be consistent 100% of the time, and text sizes are correct except in one instance.

The remaining tweaks have to do with paddings and element sizes.

-----

1. The header “Recommended”, “Enabled”, etc. needs to be shifted down a bit, so it matches the padding of headers like “Account” in Settings.

Just to check: are we also using the same font weight?

<img width="320" src="https://user-images.githubusercontent.com/51007/78080902-b813f780-740b-11ea-9ae6-8490999af336.png"><img width="320" src="https://user-images.githubusercontent.com/51007/78080912-bfd39c00-740b-11ea-8ba3-6e57f8565ea7.png">

-----

2. Our add-on icon size is bigger than the size of favicons used elsewhere in the app, and our text padding doesn’t align with app bar header. Our text sizes are already correct, so that’s perfect.

If possible, we should follow the favicon specs outlined in #7992, where add-on icons is is 24x24dp centered in a 40x40dp box with 4dp corner radius. Sorry that it’s a moving target!

<img width="320" src="https://user-images.githubusercontent.com/51007/78081144-54d69500-740c-11ea-8166-009fd487bf57.png"><img width="320" src="https://user-images.githubusercontent.com/51007/78081147-5738ef00-740c-11ea-85af-135230d61513.png">

-----

3. On the “uBlock Origin” sub-page, the padding seems to be double the padding value of other Settings pages. Hopefully this is a fairly straightforward fix?

<img width="320" src="https://user-images.githubusercontent.com/51007/78081923-3a052000-740e-11ea-8dca-48186f460625.png"><img width="320" src="https://user-images.githubusercontent.com/51007/78081953-52753a80-740e-11ea-84a7-1ae34ca4649c.png">

-----

4. On the “Details” sub-page, the text size (14dp?) is smaller than one found under “About Firefox” (16dp?). Our text colour now matches and looks great.

<img width="320" src="https://user-images.githubusercontent.com/51007/78082652-0a571780-7410-11ea-9e53-e8df4b81edf7.png"><img width="320" src="https://user-images.githubusercontent.com/51007/78082676-1642d980-7410-11ea-9d97-26a0a458735f.png">

-----

5. If wonder if the vertical paddings of “Authors”, “Version”, “Last updated”, etc. can match the padding of items on the “Permissions” sub-page, and if the horizontal separator/ruler can stretch across the length of the page?

Both the horizontal paddings and text sizes are already correct.

<img width="320" src="https://user-images.githubusercontent.com/51007/78083418-e563a400-7411-11ea-9daf-c8612c88b504.png"><img width="320" src="https://user-images.githubusercontent.com/51007/78083420-e72d6780-7411-11ea-91a2-76117f8415a0.png">

-----

6 On the “Permissions” sub-page, I wonder if we can stretch the horizontal separator/ruler across the length of the page? Similar to how rulers appear in other Settings page.

<img width="320" src="https://user-images.githubusercontent.com/51007/78082346-450c8000-740f-11ea-9316-ac40f2b6a25b.png"><img width="320" src="https://user-images.githubusercontent.com/51007/78082360-50f84200-740f-11ea-975b-b83504048be4.png">

**Comment by brampitoyo** [comment]
@Amejia481 All our remaining issues – some are issues from before – have to do with paddings between elements.

All of our text sizes and colours are now perfect!

-----

1. This was an issue from before. Our text padding doesn’t align with app bar header.

I was also wondering whether it would be possible to change the colour of the circle containing the add-on icon, to be the same colour as ones used on Bookmarks and History items?

- Background colour value: Light Grey 30 `#e0e0e6`
- No drop shadow

![text-alignment@2x](https://user-images.githubusercontent.com/51007/78632871-38e35f80-78f4-11ea-8ccf-9ba6f63f829e.png)

-----

2. Our add/install (+) icon should have the same height (24dp), padding (16dp) and alignment as the three-dot icon used in Bookmarks and History.

![icon-padding@2x](https://user-images.githubusercontent.com/51007/78632868-36810580-78f4-11ea-9515-10ea64a1e147.png)

-----

3. The padding between add-ons header & list item should be the same as the padding between header & list item in Settings main page (I think it has no padding at all? I could be wrong).

![heading-padding@2x](https://user-images.githubusercontent.com/51007/78634387-f7ed4a00-78f7-11ea-8300-a32b64c3c7f2.png)


-----

4. On the “Details” sub-page, the top padding of add-on description should match text padding in other sections within Settings.

![add-on-description-top-padding@2x](https://user-images.githubusercontent.com/51007/78633185-0a19b900-78f5-11ea-8122-1bb716783cea.png)

-----

5. On the “Details” sub-page, the padding between add-on description & details (authors, version, last updated, etc.) should be identical to the padding in the “About Firefox” page.

![description-details-text-padding@2x](https://user-images.githubusercontent.com/51007/78633398-a217a280-78f5-11ea-96ef-9c59fdba4ed2.png)

-----

6. This was an issue from before. On the “uBlock Origin” sub-page, the padding seems to be double the padding value of other Settings pages.

<img width="318" src="https://user-images.githubusercontent.com/51007/78081923-3a052000-740e-11ea-8dca-48186f460625.png"><img width="318" src="https://user-images.githubusercontent.com/51007/78081953-52753a80-740e-11ea-84a7-1ae34ca4649c.png">

**Comment by brampitoyo** [comment]
@Amejia481 I’ve gone through all the changes and can confirm that nearly everything looks perfect. All major and minor layout issues have now been addressed. Thanks heaps for working on this!

There’s only one nit that remains: the plus icon we use isn’t the same as the plus icon used elsewhere in the app. Ours has flat/sharp edges, and the one used elsewhere has rounded edges. Ours is also smaller (20dp?) versus the other ones (24dp).

![icon-size@2x](https://user-images.githubusercontent.com/51007/78842580-77902b80-7a54-11ea-83a7-d9061c4644f7.png)

Otherwise, we’re ready to ship these changes!

**Comment by Amejia481** [comment]
The new changes are in nightly, we can close this one :)
