### ISSUE TITLE
[Bug] no context menu to download audio

### ISSUE THREAD

**Issue by emilio** [mozilla-mobile/fenix#8521]
## Steps to reproduce

Go to any page that uses `<audio>`, like https://feeds.transistor.fm/on-the-metal-0294649e-ec23-4eab-975a-9eb13fd94e06

Long-tap to download the audio (so as to listen to it off line for example).

### Expected behavior

On long tap, I have a context menu that allows to download the audio. This works on Fennec.

### Actual behavior

Nothing

### Device information

* Android device: Galaxy A20
* Fenix version: Nightly

**Comment by rocketsroger** [comment]
@emilio issue was fixed with mozilla-mobile/android-components#4021. I've confirmed nightly have this fix. Can you please confirm the fix is working as expected? Long press on the video you should see "Save file to device" option. Thanks,

Adding QA to verify as well.

**Comment by emilio** [comment]
Yeah, works for me, thank you!

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly Build #20940609 from 4/3`** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)

► Video
![20200403-093618](https://user-images.githubusercontent.com/51314259/78332194-326d8480-7590-11ea-84c9-5593cebc48be.gif)
