### ISSUE TITLE
[Bug] ETP options from onboarding screen can be selected when ETP is turned off

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/fenix#8523]
### Prerequisites
Have a fresh install.

## Steps to reproduce
1. Launch Fenix.
2. Go to the "Protect yourself" card;
3. Turn ETP off.
4. Tap on `Standard` or `Strict`.
### Expected behavior
The options should not change until turning ETP back on.
### Actual behavior
ETP options from the onboarding screen can be changed when ETP is turned off.
### Device information

* Android device: **Google Pixel 3a XL(Android 10), Samsung Galaxy S10+ (Android 9), OnePlus 6T (Android 9), Samsung Galaxy S7 (Android 7), OnePlus A3(Android 6),  Nexus 4, android 5.1.1.**
* Fenix version: **Nightly build 2/19, Beta 4.0.0.**

### Notes
When changing the ETP option while it's off, it remains saved when checking the settings' ETP menu.
![20200219-111205](https://user-images.githubusercontent.com/42831109/74819630-5ee37f00-5309-11ea-99dd-c508ea6a6766.gif)

**Comment by sv-sdeiac** [comment]
Verified as fixed using the latest version of Firefox Preview Nightly 2/24 #20550606.

Now the options are not selectable after disabling ETP from the onboarding screen. Also verified that the last change from the onboarding before the disable is saved and reflect also in the settings ETP menu.

Devices:
- Motorola Moto G6 (Android 8);
- Samsung Galaxy S8 (Android 9).
