### ISSUE TITLE
[Bug] Deleted search engines keeps coming back

### ISSUE THREAD

**Issue by neekless** [mozilla-mobile/fenix#8526]
## Steps to reproduce
1. Delete search engines
2. Go back
3. Go to search engines again

### Expected behavior
Deleted search engines should not return without changing locale. (assuming this is the correct behavior according to https://github.com/mozilla-mobile/fenix/commit/1ba64f955937f86d743e0e581595948cafa21de5) 

### Actual behavior
![ezgif com-gif-maker](https://user-images.githubusercontent.com/22426822/74821112-060cea00-52fb-11ea-9790-30a937228581.gif)

### Device information

* Android device: pixel2xl pie
* Fenix version: Nightly 200219 06:01 (Build #20500607)

**Comment by sv-ohorvath** [comment]
This is not reproducing anymore on the latest Nightly (2/24).
