### ISSUE TITLE
[Bug]Tracking content menu from Custom ETP is not displayed

### ISSUE THREAD

**Issue by sv-sdeiac** [mozilla-mobile/fenix#8529]
## Steps to reproduce
1. Tap on 3dot menu;
2. Select the "Settings" option;
3. Open "Enhance Tracking Protection";
4. Select the "Custom" option;
5. Check/uncheck the "Tracking content" option.

### Expected behavior
A drop-down list is displayed when the "Tracking content" option is enabled.

### Actual behavior
A drop-down list is displayed for a fraction of second and then it's disappeared.

### Device information

* Android device: Samsung Galaxy S8 (Android 9), Nokia 6 (Android 7.1.1).
* Fenix version: Firefox Preview Beta 4.0.0-beta.1, Firefox Preview Nightly 2/19 #20500607.
![20200219_152557](https://user-images.githubusercontent.com/40264165/74839115-674db100-532d-11ea-9b3d-ddc8655df2f4.gif)

**Comment by sv-sdeiac** [comment]
### Notes
- It seems that if you uncheck "Cookies" and "Tracking content" then check the "Cookies" back, the list is for " Tracking content" is displayed (which is not an intended behavior since the option is unchecked. And it will disappear if you will check back the "Tracking content".
![Screenshot_4](https://user-images.githubusercontent.com/40264165/74853586-ce2b9400-5346-11ea-9375-6e1a359f83cb.png)

**Comment by mcarare** [comment]
For QA: this should be retested in the next Nightly.

**Comment by sv-sdeiac** [comment]
Verified as fixed using the latest version of Firefox Preview Nightly 2/20 #20510607.
Now the Tacking content drop-down menu is displayed correctly when the option is enabled.

Device: Samsung Galaxy S8 (Android 9).
