### ISSUE TITLE
[Bug] Double-tap needed to switch the Open links in private tab toggle

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#8534]
## Steps to reproduce
On a Fenix restart
1. Go to Settings>private browsing. 
2. Tap the Open links in private tab toggle.
### Expected behavior
One tap switches it on/off.
### Actual behavior
It needs two taps to switch it.
### Device information

* Android device: Pixel 3 (android 10), Xiaomi Mi Pad 2 (Android 5.1), OnePlus 5T (Android 9.0)
* Fenix version: Beta 4.0

**Comment by mcarare** [comment]
Note: For me it happens just for the first click.

**Comment by sv-ohorvath** [comment]
Verified as fixed on Nightly 2/21.
