### ISSUE TITLE
[Bug]"Custom" option is not displayed on the ETP card from the onboarding screen

### ISSUE THREAD

**Issue by sv-sdeiac** [mozilla-mobile/fenix#8536]
### Prerequisites
Make sure that the Firefox Preview is a fresh install, or make a clear data from the android apps.

## Steps to reproduce
1. Open Firefox Preview;
2. Scroll to the "Protect yourself" card;
3. Pay attention to the displayed options.

### Expected behavior
There is "Standard", "Strict(recommended)" and "Custom" options displayed.

### Actual behavior
Only the "Standard" and "Strict(recommended)" options are displayed.

### Device information

* Android device: Samsung Galaxy S8 (Android 9).
* Fenix version: Firefox Preview Beta 4.0.0-beta.1
![Screenshot_20200219-172310_Firefox Preview](https://user-images.githubusercontent.com/40264165/74850230-61ae9600-5342-11ea-931d-cda904929cb2.jpg)

**Comment by mcarare** [comment]
@sv-sdeiac This was by design, the custom option is not supposed to show in the onboarding card.
For reference: https://github.com/mozilla-mobile/fenix/issues/6980#issuecomment-577256089
