### ISSUE TITLE
[Bug] Migration notification doesn't take you to the browser when complete

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/fenix#8537]
## Steps to reproduce
1. Start a migration from Fennec to Fenix and wait until it's complete.
2. Minimize the migration UI if it's visible.
3. Click on the notification.

### Expected behavior
 - The notification should go straight to the browser if the migration is complete.

### Actual behavior
 - The notification takes you back to the migration UI (where you have to press the 'Start Firefox Nightly' button to continue.

### Device information

* Android device: Android 10 (Pixel 4)
* Fenix version: 19/02/2020 nightly.

Related to https://github.com/mozilla-mobile/fenix/issues/8488.

**Comment by ebalazs-sv** [comment]
Hello! Similar issue: https://github.com/mozilla-mobile/android-components/issues/5996.

**Comment by jonalmeida** [comment]
Closing as duplicate. Will grab the other one if it isn't being worked on.

**Comment by ebalazs-sv** [comment]
Since this was closed as a Duplicate, I will move it to Done. Thanks!
