### ISSUE TITLE
Final version and configuration will be activated?

### ISSUE THREAD

**Issue by gallegonovato** [mozilla-mobile/fenix#8538]
Good afternoon:

First of all, thank you for all your time and effort.

I wanted to ask you a question that in no version of Phoenix so far I managed to get into about:config .

So I wanted to ask you if in the final version it will be activated to remove possible telemetries, and to be able to make changes as you can do in Mozilla for example.

In fdroid I know you can't put it officially. That we will be able to lower it of here, from github.

But about:config will be active and can be used in the final version?

A hug and sorry for any inconvenience and thanks for your time and patience.

**Comment by cadeyrn** [comment]
about:config for stable release is #7865.

> So I wanted to ask you if in the final version it will be activated to remove possible telemetries

You don't need about:config to disable telemetry, there is a visable option for doing that.

**Comment by kbrosnan** [comment]
Closing as dupe / multiple issues. Please keep issues to one specific topic.

**Comment by gallegonovato** [comment]
Good afternoon:

I mean, can you get in or use about:config so you can modify it, for example?

Telemetry to Google
Other privacy options
Cryptomonedas
Security
And other options and/or multiple variants 
Etc...

Which can be modified from the about:config as it happens in Mozilla.

I don't know if they could activate it for the final version of Fenix. It would be another point or better point to be different from Google and still be the best browser in the world as Mozilla is.

I would be very grateful if you could implement it in its final version and make it, as I said, the best browser in the world, Mozilla.

A hug and thanks for your help and time.
