### ISSUE TITLE
[Bug]Disabling all options from Custom ETP still track all your browser

### ISSUE THREAD

**Issue by sv-sdeiac** [mozilla-mobile/fenix#8540]
### Prerequisites
Make sure that ETP from the Firefox settings is set to "Custom" with all options unchecked
![Screenshot_20200219-180736_Firefox Preview](https://user-images.githubusercontent.com/40264165/74850549-ccf86800-5342-11ea-9a90-93cb72e18915.jpg)

## Steps to reproduce
1. Go to any test page for tracking protection(e.g. https://mozilla.github.io/tracking-test/social.html.);

### Expected behavior
A black cat is displayed informing the user that the Tracking Protection is disabled.

### Actual behavior
The Tracking Protection is enabled even if all options from the Custom submenu are disabled.

### Device information

* Android device: Samsung Galaxy S8 (Android 9)
* Fenix version: Firefox Preview Beta 4.0.0-beta.1
* Notes:
- Also, you can't browse if you want to login to a page(e.g. Twitter.com) with all options disabled from the Custom mode of ETP which is a second case that makes this an important issue.
![20200219_181730](https://user-images.githubusercontent.com/40264165/74852006-b2bf8980-5344-11ea-9ef4-da454cbf3b45.gif)

**Comment by mcarare** [comment]
@sv-sdeiac Please retest this in the next Nightly (it should be fixed after fixing https://github.com/mozilla-mobile/fenix/issues/8529)

**Comment by sv-sdeiac** [comment]
Hello, I am still able to reproduce the issue using the latest version of Firefox Preview Nightly 2/20 #20510607.
Now the only ETP who is disabled as in the settings is "Tracking content" and the other 3(Cross-site tracking cookies, fingerprinters, cryptominers) are still blocked by de browser even if in the settings
are disabled.
Device: Samsung Galaxy S8 (Android 9).

**Comment by liuche** [comment]
If we can't land this by EOD, then we should turn this off so we can start Beta Migration.

**Comment by liuche** [comment]
@Baron-Severin 👀

**Comment by liuche** [comment]
Was this a problem due to testing on an outdated site (rather than https://senglehardt.com/test/trackingprotection/test_pages/ )? Could you retest please, because we learned yesterday that the github site does not have the latest lists?

**Comment by Baron-Severin** [comment]
> Was this a problem due to testing on an outdated site (rather than https://senglehardt.com/test/trackingprotection/test_pages/ )? Could you retest please, because we learned yesterday that the github site does not have the latest lists?

I'm able to reproduce this bug on nightly on that link, but @mcarares PR fixes it.

**Comment by abodea** [comment]
Verified as fixed on the latest **Nightly 2/27** and **Beta 4.0.0-Beta2** with Google Pixel 3 (A 9), Google Pixel 3a XL (A 10).
Note that A black cat is displayed informing the user that the Tracking Protection is disabled when everything from `Custom` option is unselected.
And the trackers are blocked when enabling back the options from `Custom`.
I verified this issue with the following websites:
- https://senglehardt.com/test/trackingprotection/test_pages/ 
- https://mozilla.github.io/tracking-test/social.html

![20200227-172354 (1)](https://user-images.githubusercontent.com/42831109/75458547-a5c71980-5986-11ea-84e9-350c50b6c5e6.gif)
Options disabled
![20200227-173510](https://user-images.githubusercontent.com/42831109/75459792-48809780-5989-11ea-849a-ec51667e2e86.gif)
Options enabled
![20200227-173602](https://user-images.githubusercontent.com/42831109/75460195-d52b5580-5989-11ea-982f-f50a038d9e4f.gif)
