### ISSUE TITLE
[Bug] Find in page and address bar remain in fullscreen 

### ISSUE THREAD

**Issue by kbrosnan** [mozilla-mobile/fenix#8541]
## Steps to reproduce
* Go to Youtube
* Open a video page e.g. [Mushroom risotto](https://www.youtube.com/watch?v=rjQ65Lu1voU) 
* Open find in page search for mus
* Tap play
* Tap full screen

### Expected behavior
* No find bar covering the video

### Actual behavior
* Find bar covers the video
* tapping the x in the find bar shows the address bar
![Screenshot_20200219-082556](https://user-images.githubusercontent.com/250273/74852855-02289a00-52f2-11ea-9c7e-f818d0afb61b.png)

### Device information

* Android device: Pixel 3 Android 10
* Fenix version: 2/19 @ 6:06 AM

**Comment by sflorean** [comment]
Verified as fixed on Nightly build from 4/23. Devices: Nokia 6 (Android 7.1.1) and Samsung Galaxy Note 10 (Android 10).
