### ISSUE TITLE
[Logins] UI edits to login capture panel

### ISSUE THREAD

**Issue by AmyYLee** [mozilla-mobile/fenix#8546]
Fixing up UI elements in the login capture panel from Fenix fest. 

![Screen Shot 2020-02-19 at 2 35 52 PM](https://user-images.githubusercontent.com/5992746/74869132-6c0e6700-5325-11ea-903d-5f494b3e8ade.png)

**Comment by abodea** [comment]
Verified as fixed on the latest Nightly 4/22 with Google Pixel 4 XL (10).
Note that the colors are respected as described in the picture from the description.
