### ISSUE TITLE
[Bug] Search engine settings are not stored

### ISSUE THREAD

**Issue by concastinator** [mozilla-mobile/fenix#8552]
There are three misbehaviours in the "Settings > Search" menu item, but I believe them to be caused by a single bug, so I shall document all of them here.

## First issue:

I had customized the list of search engines to my needs. Installing Nightly 200219 (build 20500607) reverted it to the default one, without announcing me of it or asking for my permission, making me lose the customization.

## Second issue:

Delete some of the search engines. Go back to the "Settings" menu. Now enter the "Search" menu item again. The deleted engines are there again, they haven't really been deleted.

## Third issue:

Tap on "+ Add search engine" and add any of the search engines found there. Go back to the "Settings" menu. Now enter the "Search" menu item again. The added engines aren't there, they haven't really been added.

### Device information

* Android device: Nokia 5, model TA-1024 with Android 9 build 00WW_6_19B_SP01
* Fenix version: Nightly 200219 (build 20500607)

**Comment by kbrosnan** [comment]
In the future please make separate issues for each individual item. Having more than one problem per issue makes it harder to correctly resolve the issue.

The second item is #8526

**Comment by boek** [comment]
I agree, luckily the same fix should fix all three issues. I will verify that and explain what is ready to QA 👍

**Comment by sv-ohorvath** [comment]
All 3 issues, including the one in #8526 are verified as fixed on Nightly 2/24.
