### ISSUE TITLE
[Bug] Custom Tabs make Firefox open a completely different app for some apps

### ISSUE THREAD

**Issue by Manishearth** [mozilla-mobile/fenix#8554]
Probably the same underlying bug as #8553 

## Steps to reproduce
(Fenix must be the default browser)

 1. Open Discord
 2. Open some link in Discord, have it open up a custom tab
 3. Exit the app by hitting the home button
 4. Reopen the app. The custom tab will be gone
 5. Open Fenix from your home screen. Discord will open instead. Hitting back will bring up the custom tab, and hitting back again will exit the browser (this is https://github.com/mozilla-mobile/fenix/issues/8553)

(I have experienced this with other apps as well, but I can't find one off the top of my head)

### Expected behavior

In (4), the custom tab should still be present on revisiting the app. 

In (5), Fenix should open, not Discord. There should never be a situation where opening Fenix from the home screen opens some other app

### Actual behavior

In (4) the custom tab disappears. In (5), Discord opens instead of Fenix

### Device information

* Android device: Pixel 3
* Fenix version: 3.2.1 (Build #20250350) 28.0.3, f0dc2cadd, Saturday 1/25 @ 3:49 AM

**Comment by darkwing** [comment]
I just ran into this while debugging another bug, this is definitely an issue on current master.

**Comment by Manishearth** [comment]
HUH. I just tested this on a freshly installed Firefox Preview Nightly by @ekager's request, and I cannot reproduce this or #8553 anymore

(and yes, I did do the dance of closing all browsers so that custom tabs started opening in the new default browser)

**Comment by Manishearth** [comment]
@darkwing What precise version did you test on? I did `Fenix version: Nightly 200219 18:01 (Build #20501809) 34.0.0, ea4c0d310, Wednesday 2/19 @ 6:08 PM`, the bug seems to be gone there.

**Comment by softvision-miralobontiu** [comment]
@Manishearth can you reproduce this issue on the latest Firefox Nightly build?

**Comment by Manishearth** [comment]
I don't think so

**Comment by Manishearth** [comment]
I don't think so
