### ISSUE TITLE
[Bug] Unable to download files

### ISSUE THREAD

**Issue by staktrace** [mozilla-mobile/fenix#8559]
## Steps to reproduce

Click on links to a variety of file types such as PDFs, MS excel files, etc.
These files are attachments on an email, exposed on a webmail interface, so I can't provide a direct link, but I can try to make a standalone reproducer case if needed.

### Expected behavior

Files get downloaded

### Actual behavior

"Firefox Nightly can't download this file type" error message

### Device information

* Android device: Sony Xperia XZ1C, Android 9
* Fenix version: Nightly 200214 08:03 (Build #2015722947)
32.0.0, 9ff30b22e
GV: 75.0a1-20200213035745

Another report:
## Steps to reproduce

- Search using **Google Images**
- Long-press an image 
- Click **Save image**
- Open an image
- Long-press the image

### Expected behavior

- When a user opens and long-presses an image, a pop-up appears to download the image
- When the 'Save image' is selected from the pop-up, the image is downloaded

### Actual behavior

- When a user long presses an image and clicks ‘Save image’, the image is not saved/ downloaded and a pop-up is displayed ‘Firefox Preview can’t download this file type’.

<p align="center"><img src="https://user-images.githubusercontent.com/24654457/76316399-5ffe3f80-62fc-11ea-8004-74fcaf7eec5e.png" align="center" width="50%" height="50%"></p>

- If the user opens the image and long presses it, no pop-up to save/ download the image appears on the screen.

**Comment by mcomella** [comment]
I saw this today on send.firefox.com: I assumed it was https://github.com/mozilla-mobile/fenix/issues/3336 but maybe it's not.

**Comment by kbrosnan** [comment]
If they require a login to access #7531 applies.

**Comment by staktrace** [comment]
In my case, the login is not cookie-based, but HTTP authentication, so I don't think #7531 applies. I also have access to the server logs, and I verified that Fenix sends a single request to the server, which the server responds to with a 200 OK error code and valid response, so the problem is definitely on the Fenix side *after* it gets the response.

Also just to be explicit, the exact same download link works fine in Fennec.

**Comment by PandoraDay** [comment]
Trying to download the first Transparent PNG of this site, which requires no authentication, and the same problem happens: Firefox Preview can't download this file type.

https://onlinepngtools.com/create-transparent-png

I could download the same file on New Microsoft Edge with no problem.

Unrooted Nexus 6P with Android 8.1.0 and Firefox Preview 4.2.1

**Comment by kbrosnan** [comment]
@PandoraDay that is a different issue the files are blob: which is android-components/issues/1159

**Comment by PandoraDay** [comment]
> @PandoraDay that is a different issue the files are blob: which is android-components/issues/1159

I see. That is my bad, then. My apologies. 😅

**Comment by apkd** [comment]
How is it possible that Firefox doesn't work with Firefox Send? It's so annoying that Firefox requires me to keep Edge/Chrome installed on my phone *just in case I want to use Firefox services*. Aaargh

**Comment by staktrace** [comment]
The issue I originally filed seems to be resolved. I'll leave this open since the issue has been hijacked by others to cover other scenarios as well and I don't know if those are fixed too.

**Comment by cadeyrn** [comment]
@apkd The Firefox Send issue is #3336.

**Comment by Amejia481** [comment]
QA please help use to verify!

**Comment by sv-ohorvath** [comment]
I was able to download photos from google images, pdfs and other types. Except: https://github.com/mozilla-mobile/android-components/issues/1159
build: Nightly 4/28
devices: Pixel 4 (Android 10), HTC Desire 820 (Android 6.0.1)

**Comment by apkd** [comment]
I suggest a new issue is opened if this one describes a different problem than the one with Firefox Send. This is the only issue with the same exact error message that I'm getting (apart from #5601, which was also closed).
