### ISSUE TITLE
[Bug] Top sites does not appear on screen on cold start if many tabs are open

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#8561]
## Steps to reproduce
- Open many tabs (I have 7 on P2)
- Click app list and swipe Fenix closed
- Open Fenix

### Expected behavior
Top sites are visible

### Actual behavior
Top sites are not visible. If I scroll up, top sites are revealed. It seems they're being hidden by the scroll container for some reason.

### Device information

* Android device: P2
* Fenix version: Nightly 200219

**Comment by ecsmyth** [comment]
Reproduces for me

## Actual behavior
- 5+ open tabs, three rows of top sites are hidden
- 4 open tabs, two rows of top sites are hidden
- 3 open tabs, first row of top sites is hidden
- 1-2 open tabs, all three rows of top sites are visible
- With seven tabs open, three rows of top sites are hidden.

## Device information
- Android device: Samsung Galaxy S10 Int'l
- Fenix version: Nightly 200220

**Comment by codrut-topliceanu** [comment]
**Cause:**

Top sites are added to the recycleView from HomeFragment _after_ the view is created and populated at start, so the scroll position doesn't change, leaving the top sites outside the visible area.

**Comment by sflorean** [comment]
Verified as fixed on Fenix Nightly 200330 with Samsung Galaxy Note10 (Android 10) and Xiaomi Mi Pad 2 (Android 5.1).
