### ISSUE TITLE
[Bug] Bypass site certificate doesn't pass badssl.com "pinning-test"

### ISSUE THREAD

**Issue by liuche** [mozilla-mobile/fenix#8564]
## Steps to reproduce
Go to badssl.com and click pinning-test
Advanced > Accept Risk and Continue

### Expected behavior
Now that #6380 has landed, bypassing certificates should be allowed.

### Actual behavior
Nothing happens, cannot bypass

### Device information

* Android device: Pixel 3
* Fenix version: Nightly 2/19

**Comment by kbrosnan** [comment]
Not everything should be allowed to be bypassed. Desktop does not allow the user to bypass pinning failures.
