### ISSUE TITLE
[Bug]Cookie option from Custom is reset every time you close the ETP panel or enable/disable option

### ISSUE THREAD

**Issue by sv-sdeiac** [mozilla-mobile/fenix#8565]
### Prerequisites
The ETP from the settings is set to "Custom" mode;

## Steps to reproduce
1. Select an option for Cookies in the "Custom" mode;
2 Go to any page(e.g. youtube.com);
3. Tap on the ETP toolbar icon;

### Expected behavior
The Blocked cookie is the same as the selected one in the ETP setting.

### Actual behavior
The Blocked cookies are reset to the: "Cross-Site Tracking Cookie" anytime you close the ETP menu.

### Device information

* Android device: Samsung Galaxy S8 (Android 9).
* Fenix version: 4.0.0-beta.1.
* Also, this issue is reproducible even when you just close the ETP panel and reopen it.
![20200220_090640](https://user-images.githubusercontent.com/40264165/74909669-7b42f280-53c1-11ea-9290-d4a2e1d419f1.gif)

**Comment by liuche** [comment]
If we can't land this by EOD, then we should turn this off so we can start Beta Migration.

**Comment by liuche** [comment]
@Baron-Severin 👀

**Comment by mcarare** [comment]
> If we can't land this by EOD, then we should turn this off so we can start Beta Migration.

https://github.com/mozilla-mobile/fenix/pull/8688 & https://github.com/mozilla-mobile/fenix/pull/8687 should have been merged too.

**Comment by sv-sdeiac** [comment]
Verified that the option made in the ETP settings is saved and anytime you return to the ETP panel, you will see the last saved option for the Custom submenu.

Device: Samsung Galaxy S8 (Android 9).
Build: Firefox Preview Nightly 2/25 @20560606. 

Anyway, I see a difference between the ETP settings and the ETP menu from the toolbar since the cookies blocked it doesn't match, you can find the bug with this issue [here](https://github.com/mozilla-mobile/fenix/issues/8717).

**Comment by Baron-Severin** [comment]
> #8688 & #8687 should have been merged too.

🤦‍♂
