### ISSUE TITLE
[Bug] Search Fragment URL editText loses focus and selection on app resume

### ISSUE THREAD

**Issue by codrut-topliceanu** [mozilla-mobile/fenix#8568]
## Steps to reproduce
1. open a tab and navigate to a web page
2. click on URL bar to go to search fragment
3. send app to the background by pressing home button
4. bring app back to foreground by opening it
### Expected behavior
Search fragment should be in the same state as it was before pressing home. URL selected, keyboard open.
### Actual behavior
URL is not selected, keyboard is not being shown.
### Device information

* Android device: Pixel 4 & Pixel 3 (both Android 10), LG K4 (Android 6)
* Fenix version: Latest Nightly from 2/19th

_Notes:_
-bug similar to [#3175](https://github.com/mozilla-mobile/fenix/issues/3175), however that fix no longer exists
 -fix for this issue should not undo the fix for [#2870](https://github.com/mozilla-mobile/fenix/issues/2870)

**Comment by sv-sdeiac** [comment]
Verified as fixed using the latest version of Firefox Preview Nightly 3/29 #20891805.

Devices:

Google Pixel 3 (Android 10);
Samsung Galaxy Tab S6 (Android 9).

**Comment by codrut-topliceanu** [comment]
@sv-sdeiac 
I'm afraid it also adds another bug. https://github.com/mozilla-mobile/fenix/issues/9500 
I will revert the fix for this and create a duplicate issue.
