### ISSUE TITLE
[Bug]History isn't sorted chronologically

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#8571]
## Prerequisites
Have a couple of history items.

## Steps to reproduce
1. Force stop Fenix
2. Change the devices Date & Time (Future date and time)
3. Open Fenix and navigate to any website
4. Change back the devices Date & Time (Today's date and time)
5. Open Fenix and check the History items.

### Expected behavior
The History items should be properly sorted.

### Actual behavior
The history items are improperly sorted from a chronological point of view.
The first section is "Older" followed by the "Last 24 hours".

### Device information

* Android device: OnePlus A3 (android 6.0.1)
* Fenix version: 
• Beta 4.0.0-beta.1 from 2/19
• Nightly #20510607 from 2/20

### Notes

► Video
![20200220-125007 (1)](https://user-images.githubusercontent.com/51314259/74927996-5199c380-53e1-11ea-908e-d253046bc0a2.gif)

**Comment by sblatz** [comment]
This does not seem very critical to me. I'm downgrading its priority

**Comment by mcarare** [comment]
@AndiAJ , can you recheck this? I cannot reproduce it anymore. TY!

**Comment by AndiAJ** [comment]
Hi @mcarare , unfortunately this is still reproducible on both **`Fenix Nightly Build #20840606 from 3/24`**
and **`Fenix Beta 4.2.0-beta.1 from 3/24`** using a OnePlus A3 (android 6.0.1)
