### ISSUE TITLE
[Bug] `search.default_engine.submission_url` is cropped

### ISSUE THREAD

**Issue by Dexterp37** [mozilla-mobile/fenix#8572]
We're [seeing](https://sql.telemetry.mozilla.org/queries/65253) the [submission_url](https://github.com/mozilla-mobile/fenix/blob/cb7791d7edfd43d84c1a4b428c43742a804f0e1a/app/metrics.yaml#L422) reporting errors due to the reported strings being [too long](https://mozilla.github.io/glean/book/user/metrics/string.html#recorded-errors).

This means that sometimes the reported URLs are being cropped to 100 characters before submission, due to the length limit of the string metric type.

Strings either need to be sanitized/reduced before recording or a different metric type must be used.

There's currently an untriaged metric type request [at this bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1557299).

**Comment by softvision-miralobontiu** [comment]
@Dexterp37 could you retry on the latest Firefox Nightly build?
Thank you!

**Comment by Dexterp37** [comment]
According to [our dashboard](https://sql.telemetry.mozilla.org/dashboard/fenix-errors) this is still true.
