### ISSUE TITLE
[Bug] Add-on manager UI elements are misaligned in RTL languages

### ISSUE THREAD

**Issue by DanielOrban** [mozilla-mobile/fenix#8574]
## Prerequisites
- uBlock Origin is installed and enabled in Fenix
## Steps to reproduce
1. Change the device language to Hebrew (Israel) or Dari (Afghan) or other RTL languages.
2. Open the Fenix app.
3. Navigate to "Settings -> Add-ons".
### Expected behavior
The text is aligned from the right to left.
### Actual behavior
The text is not correctly aligned.
### Device information
* Android device:
-Samsung Galaxy S7 (Android 8.0.0)
-Samsung Galaxy S7 Edge (Android 8.0.0)
* Fenix version:
Nightly 200220 (Build #20510608)
Beta 4.0.0-beta.1 (Build #20500409)

![edited](https://user-images.githubusercontent.com/43445968/74931905-4cd90d80-53e9-11ea-8f95-68a96990e37e.jpg)

**Comment by softvision-miralobontiu** [comment]
I was not able to reproduce this anymore, the UI elements are now aligned when using RTL languages.
Tested on the 11/18 Nightly build with Samsung Galaxy Tab S6 (Android 10).
