### ISSUE TITLE
[Bug] Different size icons for "Not yet available" addons

### ISSUE THREAD

**Issue by sflorean** [mozilla-mobile/fenix#8578]
### Prerequisites
- On Fennec, various add-ons are installed (i.e. uBlock Origin, HTTPS Everywhere, Ghostery, etc).
- Replace Fennec with Fenix.

### Steps to reproduce
1. Go to Settings - Add-ons - "Not yet supported".
2. Check the icons.

### Expected behavior
The icons have the same size.

### Actual behavior
The addon logo and delete icons are different in size.

### Device information
* Android device: Google Pixel (Android Q)
* Fenix version: 4.0.0 - beta.1

![Screenshot_20200220-151528](https://user-images.githubusercontent.com/58466444/74938016-e7d7e480-53f5-11ea-8948-7c103d5c3dfb.png)

**Comment by gabrielluong** [comment]
@brampitoyo Can you point sizes for the icons?

**Comment by brampitoyo** [comment]
@gabrielluong It’s odd that the label text is aligned right and has the wrong colour.

The spacing + dimension + colour we use on this page, should match our History and Bookmarks pages. Both pages use the same large icon (left side) and normal-size icon (right side). Although we don’t have caption underneath each label like those pages, the text sizes they use are correct.

<img width="320" src="https://user-images.githubusercontent.com/51007/75385748-34b34200-5945-11ea-8b1c-c997b4b9ec43.png"> <img width="320" src="https://user-images.githubusercontent.com/51007/75385761-3c72e680-5945-11ea-9b93-d4f13d2ff8ab.png">

Inspectable mockup: https://share.goabstract.com/56dfcf1d-727e-4fc3-8f03-fafce051474b?mode=build&sha=03b8cfe173a9c20c08ef153bec6785dc399cb36b

After implementing, would you be able to check it against the History and Bookmark pages, to make sure that all the measurements match?

**Comment by mheubusch** [comment]
@brampitoyo Can you ensure that we have delivered the correct svg for the add-on icon so that it scales correctly?

**Comment by brampitoyo** [comment]
@mheubusch Thanks for checking in on this. I’ve gone through all the screens where the add-on icon appears, and it seems that we’ve used the right version everywhere – one that scales correctly.

<img width="360" src="https://user-images.githubusercontent.com/51007/86087934-6efe3d00-baf9-11ea-81fc-91296a47d912.png"> <img width="360" src="https://user-images.githubusercontent.com/51007/86088109-cac8c600-baf9-11ea-9a58-4a7f3bd18005.png">
<img width="360" src="https://user-images.githubusercontent.com/51007/86088132-d916e200-baf9-11ea-9c39-4b71e505b6c8.png"> <img width="360" src="https://user-images.githubusercontent.com/51007/86088154-e2a04a00-baf9-11ea-8129-def2919943df.png">
<img width="360" src="https://user-images.githubusercontent.com/51007/86088195-f2b82980-baf9-11ea-9919-8bae4847566a.png"> <img width="360" src="https://user-images.githubusercontent.com/51007/86088200-f51a8380-baf9-11ea-98f2-f9c9039d46a4.png">

It seems, from my end, that we’ve delivered the correct asset. Let’s double-check with @sflorean.

**Comment by sflorean** [comment]
@brampitoyo this issue is only reproducible if the Fennec is replaced by Fenix (migrated) and on Fennec we have some addons enabled that are not supported on Fenix. 

1. Install Fennec http://archive.mozilla.org/pub/mobile/candidates/68.7b1-candidates/build1/android-api-16/.
2. Enable add-ons that are not yet available on Fenix.
3. Install Fenix https://firefox-ci-tc.services.mozilla.com/tasks/index/mobile.v2.fenix.fennec-beta.2020.06.27.revision.e0fa1c0db4ff806c991b13906ef6a30ba4d6054d.
4. Check the addons settings -> Not yet available.

Here is a screenshot from 78.0.1-beta.1 build:
![Screenshot_2020-06-30-09-51-14](https://user-images.githubusercontent.com/58466444/86093469-ad730800-bab7-11ea-81d5-5a6c120c74cc.png)

**Comment by brampitoyo** [comment]
Hi @sflorean, our spec for the “Not yet supported” page can be viewed and inspected here:

https://share.goabstract.com/28d0811b-ffed-4863-89c8-8aaa10acb528?mode=design&sha=e00d4f002ecef58f001903d9111f95b864daa8ae

Compare the page above to the root Add-ons Manager page here:

https://share.goabstract.com/62fae84c-38fc-4b5f-a648-32e09b18ed36?mode=design&sha=31cd0fd41307935bad30f2cb0a009626db62007a

If we make the icons, frame, margins and separator on this “Not yet supported” page identical to the root Add-ons Manager page, we should be good to go.

<img width="360" src="https://user-images.githubusercontent.com/51007/86200018-c0690380-bbaf-11ea-943f-4de948c89e16.png"> <img width="360" src="https://user-images.githubusercontent.com/51007/86200019-c19a3080-bbaf-11ea-9250-ff0283e71c52.png">

Would you be able to post an example after making the change, so we can review one last time before the change lands?

Thanks!

**Comment by sflorean** [comment]
@brampitoyo, unfortunately, I can't make the changes given the fact that I'm not a developer, but a tester.

**Comment by brampitoyo** [comment]
@sflorean Understood. Ping @Amejia481 so that he can prioritise this issue in later sprints, when we have time.

**Comment by Mugurell** [comment]
Adding here also the update from Bram - "Our add-ons icon should follow the same guidelines as favicons (see mozilla-mobile/fenix#7992)." (https://github.com/mozilla-mobile/android-components/issues/8054#issuecomment-671750276)

**Comment by Mugurell** [comment]
With the merge of https://github.com/mozilla-mobile/android-components/issues/8054 (which contains updated specs from Bram) this should be ready to test in the next Nightly.

**Comment by softvision-miralobontiu** [comment]
Hi all,
This issue is not fixed yet. I've done the following migrations using Samsung Galaxy Tab S6 (Android 9), and Sony Xperia Z5 Premium (Android 7.1.1):
- Fennec RC 68.9.0 to Fenix RC 79.0.5 - the same display of the "Not yet available" page,
- Fennec beta 68.7b1 to Fenix beta 80.0.1-beta.2 - the same display of the "Not yet available" page.

<img src="https://user-images.githubusercontent.com/40694158/91283357-2b3f5100-e793-11ea-9c0c-984099566b4b.jpg" width="300" height="550" />

I'll remove the qa:needed label until further notice,

**Comment by Mugurell** [comment]
I see `Fenix beta 80.0.1-beta.2` being released on August 18th while the patch to resolve this was merged in AC on August 20th.
So it is expected for these builds to not contain the fix.

Also note that the patch to resolve this added an icon background, similar to what the other addons icons have that should be visible regardless of the size of icon.
![AddonsIcons](https://user-images.githubusercontent.com/11428869/90594410-0119ec00-e1f3-11ea-8442-a421558246ca.gif)
[video](https://drive.google.com/file/d/1TLgDuCx8BwCdoof3y0ZNCP5AYTR6G8DL/view?usp=sharing)

I'll readd the `qa:needed` label for this to be checked in later releases.

**Comment by ebalazs-sv** [comment]
Verified as fixed on Beta 81.1.0-beta.2 (Build #2015761657), GV 81.0, from 9/2 with Pixel 2 (Android 9) and Samsung Galaxy Tab S3 (Android 8).
