### ISSUE TITLE
[Bug] Crash when accessing about:crashcontent

### ISSUE THREAD

**Issue by softvision-miralobontiu** [mozilla-mobile/fenix#8583]
## Steps to reproduce
1. Open a page.
2. In the same tab, go to about:crashcontent.

### Expected behavior
The "Sorry. Firefox Preview can't load that page."
[] Send crash report to Mozilla - checkbox
[Close tab] button
[Restore tab] button" page is displayed and the user can select one option or the other.

### Actual behavior
The app crashes before the user can select an option.

### Device information
* Android device: all
* Fenix version: Beta 4.0.0-beta.1

[logcat.txt](https://github.com/mozilla-mobile/fenix/files/4231665/logcat.txt)

![20200220_174702_Trim](https://user-images.githubusercontent.com/40694158/74952764-67bb7a00-5409-11ea-85d5-b486414a5dd0.gif)

**Comment by BranescuMihai** [comment]
Is this still reproducible? For me it doesn't happen anymore

**Comment by softvision-miralobontiu** [comment]
I was not able to reproduce this crash anymore, neither on Beta 4.2.0-beta.1, nor on the latest Nightly from 3/25 with OnePlus 5T (Android 9).
I will close this issue.

**Comment by leela52452** [comment]
this is reproducible #2015746833 @ [Socorro](https://crash-stats.mozilla.org/report/index/c55ed964-ffde-4aec-aee5-652f30200618).

**Comment by leela52452** [comment]
hello @ekager
this is reproducible also on #2015747025
is it OK to reopen if i find in similar situations. reason: the bug history does not have commit or bmo number.

**Comment by leela52452** [comment]
reproducible: 5.2.0 @ [socorro](https://crash-stats.mozilla.org/report/index/a6a02408-4003-4b8f-9ea7-0a7200200619)
