### ISSUE TITLE
[Bug] Security info dropdown does not get read in TalkBack

### ISSUE THREAD

**Issue by eeejay** [mozilla-mobile/fenix#8591]
## Steps to reproduce

With TalkBack, activate site info button (padlock icon)

### Expected behavior

TalkBack cursor should land and read the dropdown title. Swiping right should reach all the other items.

### Actual behavior

TalkBack says "Quick Settings sheet"

**Comment by sv-sdeiac** [comment]
Verified as fixed using the latest version of Firefox Preview Nightly 3/20 #20800605.

Devices:
- Google Pixel 3a (Android Q);
- Google Pixel 3 (Android Q);
- LG g7 fit (Android 8.1).
