### ISSUE TITLE
[Bug] Device name should not apper under "Choose what to sync" header in Account page

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#8592]
Currently the device name appears under the "Choose what to sync" header in the account page, but is not really part of that section. It should appear above it. 

<img width="350" alt="image" src="https://user-images.githubusercontent.com/4400286/74964464-543bef00-53c8-11ea-9c21-812e95e05005.png">

**Comment by ekager** [comment]
As part of this ticket, we should make sure that the Device name field is still disabled while syncing (currently being done through the category IIRC)

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly Build #20830607 from 3/23`** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S6 (Android 7)
• OnePlus A3 (Android 6.0.1)

►Screenshot
![rsz_1screenshot_20200323-091207](https://user-images.githubusercontent.com/51314259/77291538-23ace500-6ce7-11ea-8531-52919bb8763f.png)
