### ISSUE TITLE
[Bug] Ublock origin "Add" button has wrong background color

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#8593]
This "add" button should have the same styling as our other buttons (i think "accent" should be the attribute we use)

<img width="350" alt="image" src="https://user-images.githubusercontent.com/4400286/74964615-9402d680-53c8-11ea-908d-f87b663d6837.png">

**Comment by Amejia481** [comment]
This should be fixed in the latest nightly!

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly Build #20650606 from 03/05`** using the following devices:
• Google Pixel 3a (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

►
![adds](https://user-images.githubusercontent.com/51314259/75955190-093cd400-5ebe-11ea-8b1d-5164f8521846.png)
Screenshot
