### ISSUE TITLE
[Bug] ETP settings information is incorrect

### ISSUE THREAD

**Issue by liuche** [mozilla-mobile/fenix#8594]
In Settings > Enhanced Tracking Protection menu:

- Standard (Recommended) is not correct (we recommend Strict)
- The "info" about what trackers are blocked in Standard and Strict are the same (but should be different) - this is a regression from Fenix 3.2 release

* Android device: P3
* Fenix version: 2/20 Nightly

![Screenshot_20200220-100348](https://user-images.githubusercontent.com/1082253/74965175-987bbf00-53c9-11ea-9afb-00a152c7b565.png)

**Comment by softvision-miralobontiu** [comment]
Verified as fixed on the latest Nightly build from 2/26 on HTC 10 (Android 8), and Google Pixel (Android 10).
