### ISSUE TITLE
[Bug] Browser menu does not show navigation buttons if on top toolbar and lots of items

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#8595]
## Steps to reproduce
1. Set the toolbar to top
2. Go to a site that has lots of buttons appear (like nytimes.com) with Ublock enabled, for example.

### Expected behavior
1. I can see the "forward/back" button, bookmark button, etc.

### Actual behavior
1. The menu is scrolled to the bottom so I cannot see these buttons

There is a bigger problem here too: this menu doesn't feel scrollable. This is something we should address by either moving items out of this list or making it more apparent to users? 

### Defaults
<img width="350" alt="image" src="https://user-images.githubusercontent.com/4400286/74964927-22775800-53c9-11ea-9ffb-256af3dd86b7.png">

### Should be
<img width="350" alt="image" src="https://user-images.githubusercontent.com/4400286/74964945-2a36fc80-53c9-11ea-8146-d21058985c70.png">

**Comment by sblatz** [comment]
I think we need to address this crowded menu sooner rather than later. Putting this in group triage. We should likely fix this during polish.

**Comment by sv-sdeiac** [comment]
Verified as fixed using the latest version of Firefox Preview Nightly 3/5 #20650606.
Now the focus of the main menu is on the forward, bookmark, share, reload buttons.

Devices:
- Nokia 6 (Android 7.1.1);
- Xiaomi Mi 8 Lite (Android 9);
- Google Pixel (Android Q).
