### ISSUE TITLE
[Bug] ETP shield icon not updated if Exception removed

### ISSUE THREAD

**Issue by liuche** [mozilla-mobile/fenix#8597]
## Steps to reproduce
Go to a site
Click shield icon
Turn off Tracking protection for this site
Go into ETP settings, clear exception (Tracking protection should be on for site now)
Go back to site

### Expected behavior
Shield icon matches tracking protection state (on)

### Actual behavior
Shield icon doesn't reflect that tracking protection is on for the site

### Device information

* Android device: P3
* Fenix version: 2/20 Nightly

![Screenshot_20200220-101232](https://user-images.githubusercontent.com/1082253/74966523-05905400-53cc-11ea-8882-621a0751d1d2.png)

**Comment by ValentinTimisica** [comment]
I filed an [issue](https://github.com/mozilla-mobile/android-components/issues/6269) in A-C and created a PR. Should be fixed by https://github.com/mozilla-mobile/android-components/pull/6270.

**Comment by sv-sdeiac** [comment]
Hi, I can confirm that this issue is fixed on the latest Nightly 3/19 #2079065 using Google Pixel 3 (Android Q) and LG g7 fit (Android 8.1).
