### ISSUE TITLE
[Bug] ETP Custom setting dropdown selections (Cookies and Tracking Content) get reset when enabling or disabling subsequent or previous fields

### ISSUE THREAD

**Issue by AaronMT** [mozilla-mobile/fenix#8598]
ae294c3fd8a7ef13ecf164ee214f25b25e8ee13f
Device: Pixel 2 (Android 10)

When making a selection of the drop-down fields in Custom ETP settings (e.g, Tracking Content in in all tabs vs: private tabs) or Cookes (e.g, All Cookies). Enabling or Disabling Cookies or Tracking Content fields will reset the values in the drop-downs that the user has made.

See video.

https://streamable.com/tgzf0

**Comment by mcarare** [comment]
Duplicate of https://github.com/mozilla-mobile/fenix/issues/8565
