### ISSUE TITLE
[Bug] ETP flicker / delay when changing status on certain sites

### ISSUE THREAD

**Issue by rpappalax** [mozilla-mobile/fenix#8599]
## Steps to reproduce
1. Open https://webcompat.com
2. Click on ETP shield
3. Status changes from Blocked to Allowed

### Expected behavior
Should change status smoothly

### Actual behavior
Flickering and delay for status to change every 2nd or 3rd time pressed

### Notes
This happens for me consistently on webcompat.com so seems to be site-specific.  On other sites
 I didn't observe this
### Device information

* Android device: Samsung Galaxy S8, Android 8.0.0
* Fenix version: 3.2.1 (Build #20250350)

![mygif](https://user-images.githubusercontent.com/3699494/74966522-05905400-53cc-11ea-8414-2bae0898fb45.gif)

**Comment by softvision-miralobontiu** [comment]
I was not able to reproduce this on Samsung Galaxy Note 8 (Android 9), nor on Samsung Galaxy Tab S6 (Android 10) on the 12/3 Nightly build.
@rpappalax could you retest on the latest Nightly build?
Thanks!
