### ISSUE TITLE
[Bug] show in private sessions button is too small 

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#8600]
<img width="350" alt="image" src="https://user-images.githubusercontent.com/4400286/74965805-b695ef00-53ca-11ea-92b2-e8560ba0701f.png">

**Comment by mcarare** [comment]
@AmyYLee This was intentional, because the smaller space between the preference above indicates the fact that this is dependant on that. An alternative would be make it the same size, but indent the checkbox. What is your suggestion?

**Comment by AmyYLee** [comment]
> @AmyYLee This was intentional, because the smaller space between the preference above indicates the fact that this is dependant on that. An alternative would be make it the same size, but indent the checkbox. What is your suggestion?

@mcarare Hi, the suggestion was to give more space to the padding under "Show in private sessions" because it's very close to the bottom navigation and not the space above it.

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly Build #20800605 from 3/20`** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S6 (Android 7)
• OnePlus A3 (Android 6.0.1)

<details>
    <summary> Comparison Nightly Build #20780606 3/18 VS Nightly Build #20800605 3/20 (Dropdown)</summary>

► ❌ Video Nightly Build from 3/18
![20200320-084037](https://user-images.githubusercontent.com/51314259/77144212-ed285d80-6a8d-11ea-95e7-72c1a6a0ed41.gif)


► ✔️  Video **latest** Nightly Build from 3/20
![20200320-083932](https://user-images.githubusercontent.com/51314259/77144137-bf431900-6a8d-11ea-9d17-ab690ac60c37.gif)



</details>
