### ISSUE TITLE
Add support for site specific autoplay permissions

### ISSUE THREAD

**Issue by severinrudie** [mozilla-mobile/fenix#8603]
### Why/User Benefit/User Problem
Currently, autoplay permissions can only be set globally.  Desktop FF allows these to be set per site, which allows users to (for example) block annoying sites while letting others work normally.

### What/Requirements
Add autoplay to site specific permissions.

### Acceptance Criteria (how do I know when I’m done?)
- Autoplay settings can be set for specific sites

**Comment by kbrosnan** [comment]
This is in Firefox now. Click on the lock icon and for pages with video elements there will be an `autoplay` entry.
