### ISSUE TITLE
[Logins] Saved Logins list UI edits

### ISSUE THREAD

**Issue by AmyYLee** [mozilla-mobile/fenix#8605]
The styling of the "Saved logins" list should be consistent with other screens that have similar lists (i.e same list height, left alignment, styling).

Please reference Bookmarks/History list style. Also the favicons are being updated in these screens https://github.com/mozilla-mobile/fenix/issues/7992 and this should also be reflected in Saved logins

<img width="757" alt="Screen Shot 2020-02-20 at 3 05 32 PM" src="https://user-images.githubusercontent.com/5992746/74974129-a85bc900-53f2-11ea-9a37-d00caad45d5d.png">

**Comment by Jmmxp** [comment]
Hi! I'd like to work on this. Please let me know if help is still wanted.

**Comment by abhi951990** [comment]
#17784 Addresses this issue
