### ISSUE TITLE
[Search] Reader mode toggle is wrong colour

### ISSUE THREAD

**Issue by AmyYLee** [mozilla-mobile/fenix#8606]
Hi, 

The reader mode toggle should match the colour of toggles in Fenix (light, dark, PBM themes)

<img width="380" alt="Screen Shot 2020-02-20 at 3 21 02 PM" src="https://user-images.githubusercontent.com/5992746/74975250-c4f90080-53f4-11ea-840b-fbfdc08f528a.png">

**Comment by softvision-miralobontiu** [comment]
Verified as fixed on the latest Nightly build from 3/16 with OnePlus 5T (Android 9), and Sony Xperia Z5 Premium (Android 7.1.1).
