### ISSUE TITLE
[Sync] Can't connect to homepage to sign into sync

### ISSUE THREAD

**Issue by AmyYLee** [mozilla-mobile/fenix#8607]
Steps to reproduce:

1. Disconnect from sync in Settings
2. Reconnect to sync via Settings -> Turn on Sync
3. Tap on "Use email instead" or use QR code

Expected:
Sync sign-in screen
or if using QR code, confirmation that it worked

Actual:

500 error screen

![image](https://user-images.githubusercontent.com/5992746/74976929-b2cc9180-53f7-11ea-94f3-614e1f412362.png)

Device: Pixel 3
Preview Nightly

**Comment by sv-ohorvath** [comment]
Can still reproduce this on Nightly 2/26

**Comment by abodea** [comment]
Verified as fixed on the latest **Nightly build from 3/16** with **Samsung Galaxy S10+ (A 9), Google Pixel 4 XL (A 10).**
Note that I tried more than 30 times to reproduce this on wi-fi and mobile data but everything worked as expected and I was able to log in via email or QR code.
