### ISSUE TITLE
"Unable to open PDF" message is unclear

### ISSUE THREAD

**Issue by severinrudie** [mozilla-mobile/fenix#8612]
### Steps to reproduce
- Disable / uninstall all apps for displaying PDFs
- Download PDF
- Select open

### Expected behavior
- PDF does not open
- Error message should explain why so that the user can can correct their problem

### Actual behavior
- A generic error message is shown

<img width="376" alt="Screen Shot 2020-02-20 at 2 11 56 PM" src="https://user-images.githubusercontent.com/13170306/74983815-f967bf00-53ea-11ea-99b8-c79fb6ce23b4.png">

**Comment by brampitoyo** [comment]
@Baron-Severin some clarifying questions:

1. Is it possible to detect filetype and show a unique message for each? PDF may not be the only un-openable file type.
2. Is it possible to deeplink to Google Play Store search containing the file extension as keyword?

For example:

> Could not open `file_extension` file
> [Open Play Store] button links to `play.google.com/store/search?c=apps&q=file_extension`

If possible, could this be a good solution?

I’ll label this issue `needs:strings` and assign it to @betsymi.

**Comment by Baron-Severin** [comment]
> Is it possible to detect filetype and show a unique message for each?

Should be.

> Is it possible to deeplink to Google Play Store search containing the file extension as keyword?

Definitely possible.

> If possible, could this be a good solution?

Sounds good to me!

**Comment by AmyYLee** [comment]
@betsymi to follow-up

**Comment by brampitoyo** [comment]
@Baron-Severin starting with these assumptions:

1. Many phones already come equipped with a PDF reader
    - Alternatively, the user would’ve already downloaded a PDF reader app
2. By default, Fenix has a way to open PDF, which uses on the system default reader
    - Unfortunately, when @betsymi and I tried opening, we kept being redirected back to Fenix
3. The only way to see this error message is by disabling or uninstalling the PDF reader app

Then this scenario is a corner case.

At Betsy’s recommendation, let’s make the error message a snackbar, and use this string:
> Unable to open file

**Comment by Amejia481** [comment]
This issue it's already addressed, now we are showing a clear message.
