### ISSUE TITLE
[Bug][a11y]Sign In-The description for Lockwise autofill popup search through app is incorrect

### ISSUE THREAD

**Issue by Diana-Rus** [mozilla-mobile/fenix#8623]
Pre-conditions:
- Have Lockwise installed with autofill option enabled for Lockwise and with an account signed in.
- Have TalkBack enabled.

## Steps to reproduce
1. Open Fenix app.
2. Go to "mobile.twitter.com".
4. Tap on "Login" button.
5. Tap on the "Email" field.
6. When the autofill pop is displayed choose option "Search Firefox Lockwise".
### Expected behavior
The description for "Search Firefox Lockwise" is correct. 
### Actual behavior
The description for "Search Firefox Lockwise" is incorrect, the following description is present: "Search percent one Singapore dollar".
### Device information

* Android device: Google Pixel C (Android 8.0.0)
* Fenix version: Fenix Preview Beta 4.0.0-beta.1

**Comment by ekager** [comment]
I believe this is an issue in Lockwise and have filed it with their team.
