### ISSUE TITLE
[Bug]Keyboard isn't dismissed after adding/editing a search engine

### ISSUE THREAD

**Issue by vladbencovici** [mozilla-mobile/fenix#8624]
## Steps to reproduce
1. Navigate to Settings>search section.
2. Add a new search engine or edit a previously added one.
3. Tap the "Confirm" button from the screen header while keyboard is still active.
4. Observe

### Expected behavior
Keyboard should be dismissed after tapping confirm button.

### Actual behavior
Keyboards is not dismissed after tapping confirm button.

### Device information

* Android device: all
* Fenix version: Firefox Preview Beta 4.0.0-beta.1

![device-2020-02-21-095424](https://user-images.githubusercontent.com/57618010/75015254-d859a980-5490-11ea-94e8-0c1c55dd47b1.gif)

**Comment by ebalazs-sv** [comment]
This is reproducible on Firefox Preview Nightly 200505 (Build #21260607) GV 77 with Huawei P9 Lite (Android 7).

**Comment by AndiAJ** [comment]
Reproducible on the latest Nightly Build 201103 using the following devices:
• Google Pixel 3a (Android 11)
• Huawei Mate 20 Lite (Android 10)
• OnePlus A3 (Android 6.0.1)

**Comment by yichiehc** [comment]
I tried to reproduce the bug but failed (keyboard is dismissed after I hit confirm button). Did I do anything wrong?

Device: Google Pixel 3a (Android 11) & Sony F8123 (Android 8)

https://user-images.githubusercontent.com/48332564/113479884-0a2aa580-94c4-11eb-84a9-b7e79ce84284.mp4


https://user-images.githubusercontent.com/48332564/113479893-1a428500-94c4-11eb-84f6-2e759d2baae2.mp4

**Comment by eliserichards** [comment]
Let's tag @AndiAJ to see if they are able to reproduce it again :) it could have been fixed in the meantime

**Comment by AndiAJ** [comment]
Hi @eliserichards , indeed **not reproducible anymore** on the latest **`Nightly 210406`** using the following devices:
• Google Pixel 3a (Android 11)
• Huawei Mate 20 Lite (Android 10)
• OnePlus A3 (Android 6.0.1)
