### ISSUE TITLE
[Bug] Camera & mic still running if you close a tab, until the undo snackbar is hidden

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#8626]
## Steps to reproduce
1. Join an audio-video chat room on talky.io on Fenix and desktop.
2. Close the tab on Fenix.
### Expected behavior
The audio-video streaming is stopped instantly.
### Actual behavior
Audio-video still going for a few seconds until the "tab closed" snackbar disappears.
### Device information

* Android device: Xiaomi Mi Pad 2 (Android 5.1), Galaxy Tab 3 (Android 8.0)
* Fenix version: Beta 4.0-build1

**Comment by ekager** [comment]
Very similar to #3194

**Comment by sv-ohorvath** [comment]
> Very similar to #3194

Yes, true, I knew there was a similar issue already logged, but I didn't find it. Do you want me to close this one?

**Comment by ekager** [comment]
Yeah let's close this for #3194

**Comment by ekager** [comment]
Reopening because this about the camera/video permission and not the audio coming from the tab

**Comment by ekager** [comment]
It looks like we need a way to "pause" the permissions here in the same way that we "pause" media. Not sure if this exists, but seems like a good thing to fix.

**Comment by liuche** [comment]
@ekager is this related to the Notifications work that's going on in the Media board, or something different? https://github.com/orgs/mozilla-mobile/projects/26

**Comment by ekager** [comment]
No, this is unrelated to media notifications (it's permissions + our tab undo) and might be made redundant by the tabs tray work.

**Comment by liuche** [comment]
The improvements in #11341 that handle the tab deletion flow should handle this, so we should test this when that's implemented.

**Comment by ekager** [comment]
Tabs Tray already has a new mechanism for "undo"-able tab deletion, and this should be fixed!

**Comment by LaurentiuApahideanSV** [comment]
Verified as fixed on the latest Firefox Preview Nightly Build200611 (Build #21630608).

### Device information
- OnePlus 6T (Android 9)
- Huawei MediaPad M3 lite (Android 7.0)

**Comment by mcarare** [comment]
Closing as per above comment.
