### ISSUE TITLE
[Bug]Not supported yet "Learn more" link should be underlined

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#8628]
## Prerequisites
Install a couple of Add-on's on a Fennec build.(besides uBlock)
Perform a migration.

## Steps to reproduce
1. From the Add-on's manager open the "Not yet supported" section
2. Check the "Learn more" link.

### Expected behavior
The "Learn more" link should be underlined, increasing the visibility and noticing the user that it's actually a hyperlink.

### Actual behavior
Not underlined, different design compared to other "Learn more" links.

### Device information

* Android device: OnePlus A3 (Android 6.0.1)
* Fenix version: • Beta Migration build 2/19

### Notes
► Add-on's 
![rsz_screenshot_20200221-115410](https://user-images.githubusercontent.com/51314259/75025087-35f6f180-54a3-11ea-9ba4-39b71220c7a6.png)

►ETP Exceptions section
![rsz_screenshot_20200221-115329](https://user-images.githubusercontent.com/51314259/75026417-a0a92c80-54a5-11ea-8244-23fba670c751.png)

**Comment by Amejia481** [comment]
Closing in favor of https://github.com/mozilla-mobile/fenix/issues/8520 see the last image where is shows how the learn more link show look like.
