### ISSUE TITLE
As a product owner, I would like to get product metrics inside Leanplum

### ISSUE THREAD

**Issue by boek** [mozilla-mobile/fenix#863]
### Acceptance Criteria (how do I know when I’m done?)
- I am able to see events inside LeanPlum

**Comment by kbrosnan** [comment]
I think this feature is better accepted by Product/Marketing as they know the Leanplum dashboards. Jessica O said that their team will be looking at the feature during their next sprint.

**Comment by bbinto** [comment]
@boek can you let me know please when the remainder of the events will be added? https://docs.google.com/spreadsheets/d/1vp3Km7qyyAvkDiUQ3b4lRQUFyA7DQixR8xP1VadA4iw/edit#gid=1742911874

It seems only 1 event has been added and we'll need the rest of the ones listed in that spreadsheet added as well.

**Comment by liuche** [comment]
(And data review too please! I took a glance at the LP pings and they seem reasonable though I'll have to ask about the PB telemetry.)

@bifleming also, let me know if there is an issue tracking documenting the Marketing campaigns tied to LeanPlum usage, which I think could be done async to this bug actually.

**Comment by bsurd** [comment]
Tested this as well while testing #864 

Metrics seem to register properly in the dashboard(number of times event has triggered, device information, time spent, location... etc). Marking as verified.
