### ISSUE TITLE
[Bug]Not supported Add-ons aren't updated if removed quickly

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#8630]
## Prerequisites
Install two Add-on's on a Fennec build. (besides uBlock)
Perform a migration.

## Steps to reproduce
1. From the Add-on's manager open the "Not yet supported" section
2. Quickly delete the listed unsupported Add-ons

### Expected behavior
The Add-ons should be removed from the list.

### Actual behavior
The second Add-on remains displayed.

### Device information

* Android device:  OnePlus A3 (Android 6.0.1)
* Fenix version:   Beta Migration build 2/19

### Notes
► Video
![20200221-122636](https://user-images.githubusercontent.com/51314259/75027091-ae12e680-54a6-11ea-946a-be9940861d72.gif)

**Comment by psymoon** [comment]
@AndiAJ the fix is uplifted in a-c and will be available in nightly later today. Please verify :).

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly Build #20550606 from 02/24`** using the following devices:

• Google Pixel 3a XL (Android 10)
• Google Pixel 3a (Android 9)
• Samsung Galaxy S7 (Android 7)
• OnePlus A 2005 (Android 6.0.1)

► Video (Time-lapsed)
![20200224-164750](https://user-images.githubusercontent.com/51314259/75163018-2be52500-5727-11ea-89b1-9b09c78fff44.gif)
