### ISSUE TITLE
[Bug] Crash on pressing back button after focusing on search bar suggestion list

### ISSUE THREAD

**Issue by SL-Lee** [mozilla-mobile/fenix#8633]
# Steps to reproduce

1. Tap on the search bar.
2. Focus on the search bar suggestion list by scrolling it (which should hide the keyboard).
3. Press the device back button.

# Expected behavior

Firefox Preview Nightly returns to the home screen.

# Actual behavior

Firefox Preview Nightly crashes.

![](https://user-images.githubusercontent.com/45960387/75034014-344f1d00-54e7-11ea-8d1a-4b6dfb98fe9c.gif)

# Device information

* Android device: Oppo Reno 2, Android 9
* Fenix version: Nightly 200221 06:00 (Build #20520607)

**Comment by sv-ohorvath** [comment]
Can also reproduce by just opening the Fenix homescreen and pressing back.
Or open a link from a custom tab in Fenix, and try to return to the custom tab app.

**Comment by rocketsroger** [comment]
Change that caused the crash is being reverted.  Please retest and confirm.

**Comment by rocketsroger** [comment]
Crash is caused by https://github.com/mozilla-mobile/fenix/issues/8460

**Comment by sv-sdeiac** [comment]
Verified as fixed using the latest version of Firefox Preview Nightly 2/24 #20550606.

I tested the following scenarios: 
- From the search bar focus;
- From the Homepage of the Firefox;
- By returning from the opened custom tab.

Device:
- Samsung Galaxy S8 (Android 9);
- Motorola Moto G6 (Android 8).
