### ISSUE TITLE
[Bug] [a11y] Downloads - Elements not recognized through TalkBack 

### ISSUE THREAD

**Issue by Diana-Rus** [mozilla-mobile/fenix#8636]
Pre-requisites
- Have TalkBack enabled.

## Steps to reproduce
1. Open Fenix and go to https://www.thinkbroadband.com/download.
2. Tap on the "1 Gb" button.

### Expected behavior
The TalkBack option recognizes the button element.
### Actual behavior
The TalkBack option does not recognize the button element. The user will not be able to download the file if it has the same type of button tag.
### Device information

* Android device: Google Pixel C (Android 8.0.0)
* Fenix version: Firefox Preview Beta 4.0.0-beta.1

Note:
The same actual result is encountered for the rest of the files that can be downloaded: 512 MB, 200 MB, 100 MB, 50 MB, 20 MB, 10 MB and 5 MB.

**Comment by asadotzler** [comment]
This works for me. I can swipe to the button (which is an image and a link, not an actual button) and doubletap to download the file. If there is an issue here, it's with the website and not with Fenix, IMO.

**Comment by Diana-Rus** [comment]
Hi, I will provide a gif maybe this will help, as when the talkback recognizes the element it highlights it.
Sony Xperia Z5 (Android 7) - Nightly 4/22
![20200422-183254](https://user-images.githubusercontent.com/49859863/80003498-cfee1100-84c9-11ea-8196-ff7e079dd676.gif)

Note: 
- It is possible to download through the links, but i did not manage through the image set as link for which the touch target area can be much wider.

**Comment by mcarare** [comment]
I'm closing this, as it is a problem within the website, and not something we could improve.
