### ISSUE TITLE
[Bug] Crash when opening link from custom tab in Fenix (open links in private previously set)

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#8637]
## Steps to reproduce
1. Install the Nightly build from 2/19.
2. Set Nightly as default browser.
3. Set open links in private On.
4. Update to the latest version from PlayStore (2/21).
5. Leave Fenix open in the background.
6. Open Gmail, open a custom tab, tap Open link in Firefox Nightly.
### Expected behavior
The link is opened in Fenix.
### Actual behavior
App crashes. Logcat: 
[open link crash log.txt](https://github.com/mozilla-mobile/fenix/files/4236659/open.link.crash.log.txt)

* If you clear app data or uninstall the previous build before installing the 2/21 build, the crash doesn't happen.
### Device information

* Android device: Pixel 3 (Android 10), Samsung Galaxy S8 (Android 9)
* Fenix version: Nightly 2/21

**Comment by sv-ohorvath** [comment]
Actually, it also happens on Beta 4.0-build1 by setting Fenix as default browser and Open link in private on.

**Comment by ekager** [comment]
> 2020-02-21 16:14:40.573 25454-25454/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.mozilla.fenix.nightly, PID: 25454
    java.lang.IllegalStateException: FragmentManager has been destroyed
        at androidx.fragment.app.FragmentManager.ensureExecReady(FragmentManager.java:4)
        at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1)
        at androidx.fragment.app.FragmentManager$4.run(FragmentManager.java:1)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)

**Comment by ekager** [comment]
Probably related to https://github.com/mozilla-mobile/fenix/issues/8580

**Comment by sv-ohorvath** [comment]
@ekager Still happening on Nightly 2/24 after #8580 was fixed.

**Comment by pocmo** [comment]
Looks like same crash as #8413.

**Comment by psymoon** [comment]
@sv-ohorvath The fix got merged last night, can you please retry?

**Comment by sv-ohorvath** [comment]
I can still reproduce this on Nightly build #20560607. 
Found some simpler steps:
1. Default browser is On.  "Open links in private" is **off** .
2. Fenix is opened on the **private browsing** homescreen.
3. From a custom tab (opens a private custom tab), open the link in Fenix. -  - should open it in normal mode.
=> App crashes.

Or, the reverse:
1. Default browser is On.  "Open links in private" is **on**.
2. Fenix is opened on the **normal browsing** homescreen.
3. From a custom tab (opens a private custom tab), open the link in Fenix. - should open it in private mode.
=> App crashes.

If  "Open links in private" is on and the browser is either not running, or set to PB homescreen, there is no crash.

**Comment by liuche** [comment]
Adding QA-needed, if it's the same as #8413

**Comment by sv-ohorvath** [comment]
This crash is verified as fixed on Nightly 2/26.
