### ISSUE TITLE
[Bug] [a11y] Addons - "Successfully enabled uBlock Origin" is not recognized by Talkback

### ISSUE THREAD

**Issue by Diana-Rus** [mozilla-mobile/fenix#8640]
Pre-conditions:
- Have TalkBack enabled.

## Steps to reproduce
1. Open app.
2. Go to "Menu"/"Settings"/"Add-ons Manager".
3. Tap on the plus icon.
4. Tap on the "Add" button from the pop-up.

### Expected behavior
The TalkBack functionality only says "Enabled".
### Actual behavior
The TalkBack functionality say "Successfully enabled uBlock Origin". As per the snackbar notification.
### Device information

* Android device: Google Pixel C (Android 8.0.0)
* Fenix version: Firefox Preview Beta 4.0.0-beta.1

**Comment by asadotzler** [comment]
I've tested this with a 4/3 Fenix build on a Galaxy S10e and it works as expected. When I double tap on "Add" ublock origin is downloaded and installed and Talkback announces "Successfully enabled uBlock Origin".

**Comment by sflorean** [comment]
Verified as fixed on Nightly 04/08 with Xiaomi Redmi Note 8T (Android 9). The TalkBack functionality says "Successfully enabled uBlock Origin". As per the snack bar notification.
