### ISSUE TITLE
[Bug][Add-ons] Red buttons and icon's on Android 5 devices

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#8641]
## Steps to reproduce
1. Open the Add-on Manager
2. Add uBlock
2. Tap and open uBlock 

### Expected behavior
Properly displayed icons and buttons

### Actual behavior
The button's and icons are red

### Device information
* Android device: LG Nexus 4 (Android 5.1.1)
* Fenix version: Nightly Build #20520607 from 2/21

### Notes
Similar issue #8524 

►White theme
![rsz_1rsz_screenshot_2020-02-21-17-18-55_1](https://user-images.githubusercontent.com/51314259/75049159-63a75f00-54d2-11ea-91f9-613fbfe39471.png)

![rsz_1rsz_screenshot_2020-02-21-17-27-14](https://user-images.githubusercontent.com/51314259/75049231-86397800-54d2-11ea-95e6-36d839e0ed85.png)

►Dark theme
![rsz_screenshot_2020-02-21-17-51-08](https://user-images.githubusercontent.com/51314259/75050276-5ab78d00-54d4-11ea-935e-2f34320716e8.png)

![rsz_screenshot_2020-02-21-17-54-31](https://user-images.githubusercontent.com/51314259/75050423-a0745580-54d4-11ea-94ea-7cd5ae6f8ba3.png)

**Comment by ekager** [comment]
Did my fixes for #8524 fix any of the text here?

**Comment by AndiAJ** [comment]
I've re-checked on the latest **`Nightly Build #20570604 from 02/26`** using the LG Nexus 4 and unfortunately, they look the same. 

![20200226-144311](https://user-images.githubusercontent.com/51314259/75346211-e2bbdf00-58a6-11ea-997a-c323dc5ccd86.gif)

**Comment by softvision-miralobontiu** [comment]
This is not entirely fixed on the latest Nightly build from 2/28, with Xiaomi Mi4i (Android 5.0.2): the icon of the add-on's permission pop-up is still red:

![1](https://user-images.githubusercontent.com/40694158/75558416-7974d100-5a4a-11ea-9aa3-6e5c14c8618c.png)

**Comment by Amejia481** [comment]
@ekager  Unfortunately this is going required some changes on AC to indicate these colors from Fenix.

- We need to expose an away to indicate the tint of title icon indicator, [similar to what we are doing with the add button tint.](https://github.com/mozilla-mobile/android-components/blob/27d632473b387343b092032d0ca81beff72b0886/components/feature/addons/src/main/java/mozilla/components/feature/addons/ui/PermissionsDialogFragment.kt#L249) 

- In [AddonsManagerAdapter](https://github.com/mozilla-mobile/android-components/blob/27d632473b387343b092032d0ca81beff72b0886/components/feature/addons/src/main/java/mozilla/components/feature/addons/ui/AddonsManagerAdapter.kt#L50) we will need to expose property to customize the tint of the plus in the constructor.

**Comment by ekager** [comment]
@Amejia481 I think this will fix it? https://github.com/mozilla-mobile/android-components/pull/6136

**Comment by Amejia481** [comment]
@ekager  Great 👍

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly Build #20630607 from 03/03`** using the following devices:

• LG Nexus 7 (Android 5.1.1)
• LG Nexus 4 (Android 5.1.1)

► Video
![20200303-093905](https://user-images.githubusercontent.com/51314259/75753375-4fb1f780-5d33-11ea-8ac9-797c510eb75c.gif)
