### ISSUE TITLE
[Bug] Three dot menu in browser does not animate

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#8644]
In the currently nightly if you select the three dot menu from the browser, it does not animate to display. In our current stable release (3.1) it does.

**Comment by sblatz** [comment]
So this happens because we have too many items in the menu. The same animation can be seen on the home screen when I make the menu have lots of items. So the solution here would be to reduce the number of items which we want to do anyway 😅

**Comment by sblatz** [comment]
See https://github.com/mozilla-mobile/fenix/issues/6350 for ongoing progress for this. I'm going to mark this blocked on #6350.

**Comment by Dunexus** [comment]
@sblatz When you say that it happens because we have too many items does it means that it happens because the menu becomes scrollable ? If so, don't forget Fenix can be used in split screen mode and have the menu scrollable even with fewer items.

**Comment by sblatz** [comment]
Ah, good point @Dunexus. This led me to investigate more and looks like an issue in AC. I'm submitting a patch now 😄 

https://github.com/mozilla-mobile/android-components/pull/6074

**Comment by sv-sdeiac** [comment]
Verified as fixed using the latest version of Firefox Preview Nightly 2/28 #20590606.

Devices:
- Xiaomi Mi 8 Lite (Android 9);
- Samsung Galaxy Note 8 (Android 9).
