### ISSUE TITLE
[Bookmarks] No bookmarks here strings are close to the top

### ISSUE THREAD

**Issue by AmyYLee** [mozilla-mobile/fenix#8649]
Please reference empty state in "History"
![image](https://user-images.githubusercontent.com/5992746/75061507-ddc5ec80-54ae-11ea-86f5-c4f88cc40bf8.png)

Please reference History screen below

![image](https://user-images.githubusercontent.com/5992746/75061691-385f4880-54af-11ea-945f-8289c31daa9d.png)

**Comment by darkwing** [comment]
@AmyYLee Where would the "Sign in" button go?  Same spot?  Middle of the screen?

**Comment by AmyYLee** [comment]
> @AmyYLee Where would the "Sign in" button go? Same spot? Middle of the screen?

yes can you move the copy and button to the middle of the screen. Thanks!

**Comment by vesta0** [comment]
@eliserichards what is the status of this issue?

**Comment by person808** [comment]
@ekager Seems like this fix makes the sign in button overlap the last row in landscape mode on my Pixel 3 emulator.

![Screenshot_1592858407](https://user-images.githubusercontent.com/6396431/85333243-19d58200-b48e-11ea-8b71-dd3b87d657de.png)

**Comment by ekager** [comment]
Good catch! Should be fixed by #11828

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly Build 200623 from 6/23`** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)

► Video
![20200623-133000](https://user-images.githubusercontent.com/51314259/85393795-40f78680-b556-11ea-9d4e-2fcdeaa54d83.gif)
