### ISSUE TITLE
As a data engineer, I would like good documentation for telemetry

### ISSUE THREAD

**Issue by boek** [mozilla-mobile/fenix#865]
### Acceptance Criteria (how do I know when I’m done?)
- Data engineering has an easy way to review current events
- Data engineering has an easy way to approve new events

**Comment by georgf** [comment]
I assume this would be covered through the Glean SDK?

There are two paths this can take from the Glean side:
- generating documentation from the metrics defined in metrics.yaml (viable short-term)
- listing the metrics in our [probe dictionary](https://telemetry.mozilla.org/probe-dictionary/) (not viable short-term, needs frontend work first)

**Comment by boek** [comment]
@georgf That is a good question. We also have some pings going into Leanplum so we may need something for that as well :)
