### ISSUE TITLE
[History] 3-dot menu should have more options

### ISSUE THREAD

**Issue by AmyYLee** [mozilla-mobile/fenix#8651]
History can be shared by long pressing -> selecting share from the top.  It should be available from the history 3-dot menu in the list item. 

Current 3-dot menu:
- Delete

Updated menu:
- Copy
- Share
- Open in new tab
- Open in private tab
- Delete

CC' @topotropic

**Comment by topotropic** [comment]
cc @KaairaGupta

**Comment by ekager** [comment]
Reopening to verify

**Comment by sv-sdeiac** [comment]
Verified as fixed using the latest version of Firefox Preview Nightly 3/29 #20891805.

Devices:
- Google Pixel 3 (Android 10);
- Samsung Galaxy Tab S6 (Android 9).
