### ISSUE TITLE
[Bookmarks] Can't share when more than one item selected

### ISSUE THREAD

**Issue by AmyYLee** [mozilla-mobile/fenix#8652]
Steps to reproduce:

1 Go to Bookmarks
2. Long press on 2 or more items to select

Expected:
The share icon is visible in the top header

Actual: 
The share icon disappears if you select more than 2 items

CC' @topotropic

**Comment by topotropic** [comment]
Thanks for filing! As a reference, sharing of multiple items is implemented for history view https://github.com/mozilla-mobile/fenix/issues/2377 

cc @KaairaGupta

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly Build #20830607 from 3/23`** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S6 (Android 7)
• OnePlus A3 (Android 6.0.1)

► Video
![20200323-084507](https://user-images.githubusercontent.com/51314259/77289737-3c1b0080-6ce3-11ea-92a7-a08eeb37d0bc.gif)
