### ISSUE TITLE
[Search] Menu captialization needs review

### ISSUE THREAD

**Issue by AmyYLee** [mozilla-mobile/fenix#8653]
@betsymi Can you review our capitalization to make sure this is correct? Thanks!

![Screenshot_20200221-140733](https://user-images.githubusercontent.com/5992746/75063921-ecfb6900-54b3-11ea-8304-7b6163f7ed07.png)

**Comment by betsymi** [comment]
Possible to provide edits at this stage to tighten things up? Met with Michelle to discuss and get extra context and recommendations are:

- Library (instead of Your Library)
- Add-ons (instead of Add-ons Manager)
- Save to collection (lowercase c)

Add to Home screen is correct.

**Comment by cadeyrn** [comment]
> Library (instead of Your Library)

FYI: The string was "Your Library", was then changed to "Library" (https://github.com/mozilla-mobile/fenix/issues/469#issuecomment-480400794) and then changend back to "Your Library" again (https://github.com/mozilla-mobile/fenix/issues/469#issuecomment-485878998). Maybe the UX feedback from last year is still valid, maybe not.

**Comment by Dunexus** [comment]
FWIW desktop version of Firefox uses "Library"

**Comment by cadeyrn** [comment]
And Firefox on iOS uses "Your Library" so there is no platform consistency either way. ;-)

**Comment by Dunexus** [comment]
@cadeyrn Did you notice any other platform inconsistency ? As we are reviewing Fenix menu entries, it may be a propitious moment to fix them globally.
Also, we should be careful to review capitalization for all supported locales.

**Comment by betsymi** [comment]
Valid point about the inconsistency across platforms. We are working to change that! It's in fact a reason I am getting more involved in these details on mobile. :) UX Content's preference is 'Library' in all cases. I will look at iOS and see if it makes sense to change it there, too.

**Comment by cadeyrn** [comment]
> @cadeyrn Did you notice any other platform inconsistency ?

No, I didn't notice other platform inconsistencies. :)

> Valid point about the inconsistency across platforms. We are working to change that!

Great! :)

**Comment by brampitoyo** [comment]
Assigning @betsymi to this issue, and removing `needs:ux` label.

**Comment by betsymi** [comment]
Menu should read as follows.

- Help
- Settings
- Library
- Desktop site
- Add to top sites
- Add to Home screen
- Add-ons
- Find in page
- Private tab
- New tab
- Report site issue
- Save to collection
- Quit

**Comment by AndiAJ** [comment]
Hi, I've just checked this on the latest **`Nightly Build #20830607 from 3/23`** using a Google Pixel 3a (Android 10)

►Screenshot
![rsz_screenshot_20200323-134823](https://user-images.githubusercontent.com/51314259/77315241-dbee8380-6d0f-11ea-92f6-082b554730b1.png)

| Status  | Description| Remark|
| ------------- | ------------- |  ------------- |
| ✔️  |  Library |   | 
| ✔️  | Add-ons  |   |
| ✔️  | Settings  |   |
| ✔️  | Quit |   |
| ✔️  | Report site issue  |   |
| ✔️  | Find in page |   |
| ✔️  | Add to top sites |   |
| ✔️  | Add to Home screen |   |
| ✔️  | Save to collection  |   |
| ✔️  | Desktop site |   |
| ❓  | Open in App | "App" - upper case 'A' ?  |
| ✔️  | Reader mode |   |
| 🚫 | New tab | Removed as per #8474  |
| 🚫 | New tab | Removed as per #8474  |
| 🚫 | Help | Removed as per #8474  |

@betsymi - Could you please review the above and share your thoughts regarding the "Open in App" matter? ☺️ 

**I'll remove the QA needed until further notice.**

**Comment by betsymi** [comment]
`Open in app`, please!

**Comment by AndiAJ** [comment]
Hi, in this case I'll mark this ticket **verified as fixed** on the latest **`Nightly Build #20840606 from 3/24`** and **`Fenix Beta 4.2.0-beta.1 from 3/24`** using the following devices:
• Google Pixel 3a (Android 10)
• OnePlus A3 (Android 6.0.1)

►Screenshots from both **`Nightly`** (left side) & **`Beta`** (right side)
![BetaNight](https://user-images.githubusercontent.com/51314259/77405968-99cf4b80-6dbc-11ea-8de6-de6ae2464568.png)

@liuche & @brampitoyo - I've filled #9352 to fix the remaining **Open in App** capitalization issue

**Comment by Poopooracoocoo** [comment]
Quit's the odd one out. I've seen quit buttons in games but not so much in apps.
