### ISSUE TITLE
[Top Sites] Context menu shouldn't cover top sites

### ISSUE THREAD

**Issue by AmyYLee** [mozilla-mobile/fenix#8655]
Steps to reproduce:
1. Long press on a top site in homescreen

Expected:
Context menu appears just below icon

Actual:
Context menu appears on top of icon

CC' @topotropic

**Comment by mcarare** [comment]
@AmyYLee Should we also consider showing a selection border for the pressed item?

**Comment by AmyYLee** [comment]
> @AmyYLee Should we also consider showing a selection border for the pressed item?

Hi, 
I don't think that solves for the menu being laid on top of the top sites favicons. We don't show a selection border anywhere else in the app so I would refrain from introducing a new modal.

**Comment by mcarare** [comment]
> > @AmyYLee Should we also consider showing a selection border for the pressed item?
> 
> Hi,
> I don't think that solves for the menu being laid on top of the top sites favicons. We don't show a selection border anywhere else in the app so I would refrain from introducing a new modal.

I already have a PR for placing it below, but after that it is still hard to know which favicon was pressed

**Comment by AndiAJ** [comment]
Hi, verified as fixed on the latest Nightly Build #20570604 from 02/26 using the following devices:
• Google Pixel 3a (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

► Video
![20200226-123212](https://user-images.githubusercontent.com/51314259/75337820-63beaa80-5896-11ea-8d0f-9308e198c8eb.gif)

**Comment by AmyYLee** [comment]
@mcarare FYI there is also a follow-up bug around the menu animating from the source of the long-press. https://github.com/mozilla-mobile/fenix/issues/8657. Thanks
