### ISSUE TITLE
[Top sites] Context menu should animate out from the source

### ISSUE THREAD

**Issue by AmyYLee** [mozilla-mobile/fenix#8657]
Steps to reproduce:

1. Long press on a top site on the homescreen

Expected:
Context menu animates (expands) from the source of the long press

Actual:
Menu always animates out from the top right corner

Please reference 3-dot menu animation - context menu expands from the source of the press.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-15909)

**Comment by softvision-miralobontiu** [comment]
Hi all,
This is a slow-motion video of the context menu animation recorded on Samsung Galaxy Note 8 (Android 9), on the 12/3 Nightly build:

<img src="https://user-images.githubusercontent.com/40694158/101020376-1420b400-3577-11eb-980a-c8b0b012f344.gif" width="300" height="550" />

As it can be seen in the short video, the context menu isn't animated from the source.
