### ISSUE TITLE
[Bug] Crash on device back button usage on S7

### ISSUE THREAD

**Issue by RKelln** [mozilla-mobile/fenix#8658]
## Steps to reproduce
* Open any tab, e.g. pocket top articles.
* Press device back button (right of physical home button)

### Expected behavior
Go to Fenix homescreen or hide browser and return to previous app (e.g. if article opened from Google assistant).

### Actual behavior
Crash to "Firefox Night keeps stopping". (Sent in 2 crash reports)

At first I thought it was because I installed uBlock Origin, but after disabling and removing it still crashes intermittently (80% or more though).

### Device information

* Android device: Samsung Galaxy S7 model #: SM-G930W8  Android: 8.0.0
* Fenix version: Nightly 200221, 34.0.0, 28fb30197
* Add-ons: with and without uBlock Origin

**Comment by LittleAngelwings** [comment]
Same happens here, using also 
Nightly 200221 06:00 (Build #20520606)
34.0.0, 28fb30197
GV: 75.0a1-20200220093508 
but on Huawei P smart with Android 9.1.0 and on Galaxy Tab A6 SM-T580 with Android 8.1.0

**Comment by ekager** [comment]
Will be fixed in next Nightly by https://github.com/mozilla-mobile/fenix/pull/8645
