### ISSUE TITLE
[ETP] Panel/toggle animation is janky

### ISSUE THREAD

**Issue by AmyYLee** [mozilla-mobile/fenix#8659]
Steps to reproduce:

1. Open a webpage and tap on the ETP shield icon
2. Tap on the toggle to enable and disable ETP

Expected:
There is a toggle animation (toggle slides), panel animation (smooth resize of panel)

Actual:
No toggle animation, panel jumps between different sizes with no transition

Screen recording
https://share.getcloudapp.com/L1ugzLY8

**Comment by softvision-miralobontiu** [comment]
I was able to reproduce the described behavior on the Samsung Galaxy Tab S6 (Android 10), on the 12/3 Nightly build.

<img src="https://user-images.githubusercontent.com/40694158/101021032-07e92680-3578-11eb-904f-49653217afac.gif" width="300" height="550" />
