### ISSUE TITLE
Allow Fenix to install unknown apps

### ISSUE THREAD

**Issue by mheubusch** [mozilla-mobile/fenix#866]
As a UX team member, I want to be able to install unknown apps in Fenix

Ensure Fenix is recognized in my device's Android settings as an application that can download and install Android apps
Set default to not allowed
Give users the ability to allow 

This will be done when I can successfully download apk files from outside of the GPS using Fenix and have them appear in Files with the Android robot icon and can be successfully installed from my device.

**Comment by buttercookie42** [comment]
Add `<uses-permission-sdk-23 android:name="android.permission.REQUEST_INSTALL_PACKAGES"/>` to the manifest, but as you specifically mention
> and have them appear in Files with the Android robot icon and can be successfully installed from my device.

shouldn't that particular flow already work today? AFAIK, the permission is relevant for *the app that is actually launching the install request*, which in that case would be your device's file explorer app.
With that understanding, the above permission is needed for triggering an install from *inside Firefox itself*, i.e. our own downloads library (if we have one?), from the "download completed" notification, or any other in-app download messaging (snackbar?).

**Comment by TitanNano** [comment]
> Add `<uses-permission-sdk-23 android:name="android.permission.REQUEST_INSTALL_PACKAGES"/>` to the manifest, but as you specifically mention
> 
> > and have them appear in Files with the Android robot icon and can be successfully installed from my device.
> 
> shouldn't that particular flow already work today? AFAIK, the permission is relevant for _the app that is actually launching the install request_, which in that case would be your device's file explorer app.
> With that understanding, the above permission is needed for triggering an install from _inside Firefox itself_, i.e. our own downloads library (if we have one?), from the "download completed" notification, or any other in-app download messaging (snackbar?).

I don't know if it should work, but it doesn't. APKs downloaded by Fenix can not be installed via the "Downloads" App, APKs downloaded by Fennec can be installed that way though.

**Comment by buttercookie42** [comment]
Interesting. I don't have a phone with Oreo, so I was going by the documentation, but maybe the downloads app behaves somewhat strangely there? In any case one more reason to add that permission to the manifest I guess.

**Comment by sv-ohorvath** [comment]
Verified as fixed on Pixel (android 9). App requests permission to install unknown apps and installs it.
