### ISSUE TITLE
Run one-off performance tests to identify P1 responsiveness issues

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#8662]
For example:
- What happens with many tabs open? Collections? Top sites?
- Many bookmarks, history? etc.

### Acceptance criteria
- Come up with a list of things to test (see my list in Cold Startup Notes document)
- Talk with Eric & team to identify P1 of those issues
- Run performance tests and file P1 responsiveness issues

**Comment by mcomella** [comment]
Triage: ecsmyth will determine which tests we want to run and prioritize accordingly. One test we may want to consider is cold startup with ublock – maybe @csadilek has already done this?

**Comment by ecsmyth** [comment]
List discussed in Slack is captured in this [doc](https://docs.google.com/document/d/1VKN5KsvFDIj-SooRcDLZ4FjRa1tzvfIeseW_CG9ZIII/edit?usp=sharing). I'll work on linking the specific items to the relevant release criteria in the requirements doc.

**Comment by mcomella** [comment]
Dupe #7380.
