### ISSUE TITLE
[Bug] Desktop Site does not work on Facebook

### ISSUE THREAD

**Issue by matejdro** [mozilla-mobile/fenix#8668]
## Steps to reproduce

1. Open https://facebook.com
2. Switch on "Desktop site"
3. Navigate to https://facebook.com again (to get rid of m prefix)

### Expected behavior

Desktop facebook site should open

### Actual behavior

Facebook still redirects to https://m.facebook.com and displays mobile site, albeit a bit stretched out one

### Device information

* Android device: OnePlus 7 Pro
* Fenix version: Nightly 200221 06:00

**Comment by kbrosnan** [comment]
Duplicate #8020

**Comment by matejdro** [comment]
@kbrosnan Can you please check the description of this ticket? It happens even when I manually remove `m.` prefix.
