### ISSUE TITLE
Selected browser language should be on top of languages

### ISSUE THREAD

**Issue by aha999** [mozilla-mobile/fenix#8670]
In the language select, the selected language should be on top of all languages options, unless it gets changed.
That way it would be more convenient to see which language is applied.

![](https://i.imgur.com/QOxzVw0.png)

![](https://i.imgur.com/Kq8gbBf.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-15918)

**Comment by fice-t** [comment]
There is now a summary under `Follow device language` that shows the current language, which seems good enough for this to be closed. CC @SoftVision-LorandJanos

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807112

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
