### ISSUE TITLE
[Bug] newly loaded pages have non zero scroll offset

### ISSUE THREAD

**Issue by Cheap-Skate** [mozilla-mobile/fenix#8671]
## Steps to reproduce
Navigate to any page eg mozilla.org
Ensure page is scrolled to top (so moz://a logo is visible)
hit 3 dot menu & reload
when page is loaded, page jumps so scroll offset is not zero, I see the second screenful of text not the moz://a logo)

I think this has been a problem for the last week or so

(Fennec does not show this behavior on mozilla.org)

### Device information

* Android device: Galaxy A40, Android 9.0.0
* Fenix version: Today's Nightly, 200222 06:01

**Comment by Cheap-Skate** [comment]
STR:
Open a new tab at www.mozilla.org
scroll to a non-zero scroll offset
kill Fenix in the Android task switcher
relaunch Fenix
tap on the mozilla.org tab to re-open it
wait while the tab loads
it (correctly?) moves back to the non-zero scroll offset of above
scroll to the top of the page ie zero scroll offset
reload the page using 3 dot menu -> reload
the tab reloads but moves to the non zero scroll offset
---> incorrect behavior, the tab should reload at zero scroll offset

I think Fenix has a scroll offset "memory" and keeps using the scroll offset the tab had last time Fenix was killed

**Comment by softvision-miralobontiu** [comment]
I was not able to reproduce this issue on the 12/3 Firefox Nightly build with Samsung Galaxy Tab S6 (Android 10), and Sony Xperia Z5 Premium (Android 7.1.1).
After force-closing and reopening Firefox, the page reloaded on the same scroll position I left it.
The same behavior when reloaded the page.

@Cheap-Skate could you retry on your device?
Thank you!

**Comment by Cheap-Skate** [comment]
Fixed I think. Thanks!
