### ISSUE TITLE
[Bug] White screen when opening Fenix from Recents

### ISSUE THREAD

**Issue by opusforlife2** [mozilla-mobile/fenix#8672]
## Steps to reproduce
- Make sure Fenix is swiped away from Recents.
- Open a link from any app in Fenix.
- Tap back. You're taken back to the other app. (You can see the animation of the number of tabs going from 1 to 0)
- Open Fenix from Recents.
### Expected behavior

Fenix should open to the homescreen. (This is what happens if you use the launcher icon to open it.) (The private browsing shortcut works normally too.)

### Actual behavior

Fenix displays a blank white screen.
### Device information

* Fenix version: 3.2.1

P.S.: I'm pretty sure I've seen this reported somewhere, but I can't find where it is. Maybe I'm just not getting the right keywords.

**Comment by kbrosnan** [comment]
Possible dupe of #5478 though 0 tabs is a different enough that this is worth keeping open.

**Comment by opusforlife2** [comment]
If you go from 2 tabs to 1 instead of 1 to 0, instead of a white screen, you go to the earlier tab, as expected. But it does look like Fenix 'struggles' with it a bit before going with the correct option.

**Comment by opusforlife2** [comment]
As of 5.1, this still happens sometimes, though it is _much_ rarer. When it _does_ happen, you can easily tap Back to go to the Fenix home screen.

**Comment by Mugurell** [comment]
I think this is actually https://github.com/mozilla-mobile/fenix/issues/9144 which is resolved in the latest Nightly.
@opusforlife2 Does this still reproduces for you? If not I think we can close this.

**Comment by opusforlife2** [comment]
Yeah, it's been a long time since I last saw this, especially since Fenix was merged into Nightly. I'm not sure the white screen problem is _completely_ gone, yet, but if so, I'll open another issue, since it's definitely not reproducible with _these_ steps anymore.
