### ISSUE TITLE
[Bug][RTL] The theme picker images on the onboarding screen are mirrored, making the Firefox logo mirrored as well

### ISSUE THREAD

**Issue by ItielMaN** [mozilla-mobile/fenix#8673]
This was introduced by #8469 .
See screenshot:
![תמונה](https://user-images.githubusercontent.com/18016656/75095948-c6682b80-55a2-11ea-9f6c-5dbe70339cf2.png)

There are 2 options on how to fix:
1. Create new images with the same mirrored layout, but with the a non-mirrored Firefox logo and a non-mirrored magnifying glass icon. As for the toolbar position picker, unmirror only the magnifying glass icon, all the rest is OK. This is the preferred solution in terms of RTL.
2. Un-mirror both theme picker and toolbar position images, and place the radio buttons on the left (to avoid inconsistencies between the 2 pickers). Not the preferred solution, but at least the layout won't be broken like in #8469 .

**Comment by ItielMaN** [comment]
cc @Mugurell @ekager

**Comment by Mugurell** [comment]
Thank you for reporting this issue!
Indeed I think we should avoid mirroring the images as a quick fix and then work with the UX team for getting the needed imagery.

**Comment by ekager** [comment]
@Mugurell I'm good with that solution! Thanks!

**Comment by softvision-miralobontiu** [comment]
Verified as fixed on the latest Nightly build from 2/26 with Google Pixel (Android 10), and HTC 10 (Android 8).

![RTL](https://user-images.githubusercontent.com/40694158/75333368-b5633700-588e-11ea-8f99-1a16f988c832.png)
