### ISSUE TITLE
[Bug] Videos don't autoplay in nytimes.com

### ISSUE THREAD

**Issue by emilio** [mozilla-mobile/fenix#8678]
## Steps to reproduce

Open https://www.nytimes.com/interactive/2018/11/27/style/what-is-inside-this-internet-rabbit-hole.html and scroll down towards the first image.

### Expected behavior

An image (well, really a video) that plays, or at least that I can play.

### Actual behavior

White.

### Device information

* Android device: Samsugin galaxy A20
* Fenix version: Both current stable and nightly.

**Comment by emilio** [comment]
Happens even with autoplay allowed :(

**Comment by emilio** [comment]
(cc https://github.com/webcompat/web-bugs/issues/48906, where I filed this originally)

**Comment by ekager** [comment]
Can repro on desktop with video + audio blocked, but definitely a bug that when autoplay is allowed it's not playing.

**Comment by ekager** [comment]
Filed https://bugzilla.mozilla.org/show_bug.cgi?id=1647779

**Comment by ekager** [comment]
Closing for #4002
