### ISSUE TITLE
[Bug] Muted videos pause music.

### ISSUE THREAD

**Issue by fallaciousreasoning** [mozilla-mobile/fenix#8679]
## Steps to reproduce
1. Play some music (i.e. through Spotify)
2. Disable tracking protection (the site I noticed this on doesn't work with it, but I can't imagine that this would be part of the problem).
2. Visit https://reddit.premii.com/#/r/AnimalTextGifs/comments/amexle
3. Play the video (if it doesn't autoplay).

### Expected behavior
The music continues to Play, because the video is muted. This is what used to happen in Fennec.

### Actual behavior
Music pauses, even though the video is silent.

Fiddling with Audio Autoplay settings doesn't fix this either.

### Device information

* Android device: Xiaomi Redmi K20 Pro (also repro'd on my work Pixel 3).
* Fenix version: Saturday 2020-02-22 (Build 2015724563)

**Comment by kbrosnan** [comment]
duplicate #8497

**Comment by fallaciousreasoning** [comment]
Whoops, didn't find that. Thanks for your work on this :)
