### ISSUE TITLE
The Fenix app icon has only half the size of all other app icons (in Android's default app settings)

### ISSUE THREAD

**Issue by cadeyrn** [mozilla-mobile/fenix#868]
## Steps to reproduce

1. open the default app settings of Android
2. select the browser app settings

### Expected behavior

The app icon of Fenix has the same size as all other app icons.

### Actual behavior

The app icon has only half the size.

![screenshot_20190306-115623](https://user-images.githubusercontent.com/1100614/53876759-cbd20c00-4007-11e9-9953-f3c01134d996.png)

### Device information

* Android device: HTC U11 / Android 8.0
* Fenix version: Fenix revision 8b793cd43ea0b816fece4266c2dbc990e24ceae1

**Comment by vesta0** [comment]
I can't reproduce this on Pixel 3.

**Comment by vesta0** [comment]
Require UX assets @lime124

**Comment by sv-ohorvath** [comment]
Still the same issue on HTC 10 (Android 8.0). 
Doesn't reproduce on Pixel (Android 9) or a Samsung Galaxy S8 (Android 8.0).

**Comment by lime124** [comment]
@shorlander can you get an asset to fix this issue

**Comment by mheubusch** [comment]
@shorlander please provide correctly sized app icon? will this be the logo for MVP?

**Comment by shorlander** [comment]
> @shorlander please provide correctly sized app icon? will this be the logo for MVP?

I need to make some adjustments and then I will provide all the right sized assets. The current plan is that this will be the logo for MVP.

**Comment by shorlander** [comment]
[firefox-preview-launcher-assets.zip](https://github.com/mozilla-mobile/fenix/files/3081691/firefox-preview-launcher-assets.zip)

**Comment by lime124** [comment]
This no longer seems to be an issue with the updated icons. Please file a new issue if it occurs again.
![Screenshot_20190424-114623](https://user-images.githubusercontent.com/287322/56686452-dbc1b000-6688-11e9-9c01-2171a96a48fa.png)
