### ISSUE TITLE
Do not capitalize THIS TIME, SEARCH WITH above alt search engines

### ISSUE THREAD

**Issue by Cheap-Skate** [mozilla-mobile/fenix#8685]
### Why/User Benefit/User Problem
- it's VERY SHOUTY
- it's inconsistent with Mozilla design which tends to use sentence case

(I also dislike the use of gray text, not that easy to read, but that's a nit)

**Comment by brampitoyo** [comment]
While I’m open to make this change, I also want to acknowledge the fact that we used the “Overline” text style deliberately, which following Material Design, is set in all caps.

See the “Overline” section here: https://material.io/design/typography/the-type-system.html#applying-the-type-scale

I would say that this isn’t an issue for now. What do you think?

**Comment by Cheap-Skate** [comment]
I agree.
