### ISSUE TITLE
Archive icon is missing

### ISSUE THREAD

**Issue by bsurd** [mozilla-mobile/fenix#869]
## Steps to reproduce
1.  Open Fenix and create a new session.
2. Tap on the tabs tray icon.
3. For the current session, tap on the 3 dot menu.

### Expected behavior
All icons are properly displayed for the available options.

### Actual behavior
The Archive icon is not displayed.

### Device information
* Android device:
     - HTC Desire 820 (Android 6.0.1)
* Fenix version:
     - 1.0.1910 (Build #10642115)
* Not reproducible on:
     - Google Pixel (9)
     - Nokia 6 (Android 7.1.1)

![screen](https://user-images.githubusercontent.com/17178945/53883209-0bf1b880-4021-11e9-925d-8a0eea9227bf.png)

**Comment by vesta0** [comment]
I see the Archive icon on Pixel 3.

**Comment by ekager** [comment]
Thanks for filing! This should have been fixed by #930, there was an issue with theming vectors on devices with API <24. @bsurd I'm closing this because I think it's fixed, but feel free to reopen/comment if that's not the case.

**Comment by sv-ohorvath** [comment]
Verified as fixed on Nexus 5 (Android 6).
