### ISSUE TITLE
Update ublock origin to the latest version

### ISSUE THREAD

**Issue by MF-Debug** [mozilla-mobile/fenix#8695]
the ublock origin bundled in the app is currently a bit outdated. it would be quite useful if it is updated to the latest version as it includes the new fenix UI support.

**Comment by kbrosnan** [comment]
Firefox Preview will check once a day for a new version.

**Comment by cadeyrn** [comment]
@kbrosnan 

Is there already an update mechanism within Firefox Preview?

uBlock Origin 1.25.0 was released five days ago, I use Firefox Preview Nightly every day and I still had uBlock Origin 1.24.4.

I had to uninstall and install uBlock Origin again to get the new version.

**Comment by agi90** [comment]
Looks like this was fixed in https://github.com/mozilla-mobile/fenix/pull/8734
