### ISSUE TITLE
[ETP] Changing Cookies and Tracking content in Custom ETP drop-down doesn't save

### ISSUE THREAD

**Issue by AmyYLee** [mozilla-mobile/fenix#8696]
Steps to reproduce:
1. Go to Settings -> Enhanced Tracking Protection
2. Select "Custom"
3. Change drop-down for Cookies to something besides "Cross-site and social media trackers"
4. Change drop-down for Tracking content to "Only in Private tabs"
5. Tap back arrow to Settings
6.  Go back to Enhanced Tracking Protection

Expected:
Last selected settings are saved for Custom ETP

Actual: 
Drop-down selection is reset to Cookies: Cross-site and social media trackers"
Tracking content: "In all tabs"

Related  #8565

**Comment by sv-sdeiac** [comment]
Verified as fixed using the latest version of Firefox Preview Nightly 2/25 #20560606.
Now the changes from the cookies and tracking content drop-down menus are saved when you return on the ETP menu.

Device: Google Pixel 3 (Android Q).
