### ISSUE TITLE
[Bug] Call forceExpand on `BottomBrowserToolbarBehavior` when entering fullscreen mode

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#8697]
When we enter full screen mode, verticalClipping needs to be set to 0, we can best achieve this by forceExpanding.

![vertical clipping wrong 2020-02-24 11_39_37](https://user-images.githubusercontent.com/4400286/75185083-58cf1300-56fa-11ea-8431-0ea4121e5be3.gif)

**Comment by sblatz** [comment]
Can fix this once https://github.com/mozilla-mobile/android-components/pull/6431 is merged :)

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly Build #20860605 from 3/26`** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)

► Video
![20200403-113419](https://user-images.githubusercontent.com/51314259/78341119-d3b00700-759f-11ea-990c-ab925ace4c49.gif)
