### ISSUE TITLE
[Bug] Weird highlight on long pressing UBO in 3 dot menu

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#8698]
## Steps to reproduce
open 3 dot menu
long press the UBO option
### Expected behavior
Normal highlighting as with other option
### Actual behavior
![Screenshot_20200225-012239](https://user-images.githubusercontent.com/33252312/75186273-88543e80-573f-11ea-87e0-ef98bc47d875.png)

### Device information

* Android device: Asus Zenfone
* Fenix version: Preview Nightly

**Comment by Amejia481** [comment]
This should be fixed in the latest nightly

**Comment by sv-sdeiac** [comment]
Verified as fixed using the latest version of Firefox Preview Nightly 2/28 #20590606.

Devices:
- Motorola Moto G6 (Android 8);
- Xiaomi Mi 8 Lite (Android 9).
