### ISSUE TITLE
Delete current private session from the overflow menu doesn't work

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#870]
## Steps to reproduce
1. Open a tab in private mode.
2. On the homescreen, tap the 3 dots button and select Delete.
### Expected behavior
The current session is deleted.
### Actual behavior
Nothing happens.
### Device information

* Android device: Pixel (Android 9)
* Fenix version: 3/5 build.

**Comment by vesta0** [comment]
Tapping on 3 dot menu doesn't do anything for me on Pixel 3.

**Comment by ekager** [comment]
I believe this was caused by https://github.com/mozilla-mobile/fenix/commit/e05f0894e872eb16f041705d34a232f4e4449106 @boek do you want to take a look?

**Comment by sv-ohorvath** [comment]
Verified as fixed on Pixel and Nexus 5 (Android 6). Build: master 3/12.
