### ISSUE TITLE
[ETP] Custom selection drop-down gets reset when you uncheck Cookies and Tracking content

### ISSUE THREAD

**Issue by AmyYLee** [mozilla-mobile/fenix#8702]
Steps to reproduce:

Go to Settings -> Enhanced Tracking Protection
1. Select "Custom"
2. Change drop-down for Cookies to something besides "Cross-site and social media trackers"
3. Change drop-down for Tracking content to "Only in Private tabs"
4. Uncheck/check Cookies and Tracking content

Expected:
Last selected settings are saved

Actual:
Drop-down selection is reset to default for both Cookies and Tracking content if you uncheck/check either category. 

Device: Pixel 3

**Comment by mcarare** [comment]
This seems to be a duplicate of https://github.com/mozilla-mobile/fenix/issues/8565#issuecomment-590749094. QA, can you confirm and test steps described here to confirm this is fixed? Thank you!

**Comment by sv-sdeiac** [comment]
Verified as fixed using the latest version of Firefox Preview Nightly 2/25 @20560606.
Now the drop-down section for Cookies and Tracking content is saving the latest changes after uncheck/check either category.

Devices:
- Samsung Galaxy S8 (Android 9);
- Google Pixel 3 (Android Q).
