### ISSUE TITLE
[Bug] missing padding in uBlock Origin menu item badge

### ISSUE THREAD

**Issue by cadeyrn** [mozilla-mobile/fenix#8706]
### Steps to reproduce

1. install uBlock Origin
2. open a website
3. open the menu

### Expected behavior

The badge with the number of blocked elements has some padding.

### Actual behavior

Have a look at the uBlock Origin menu item, there is no padding around the "1", this looks bad.

![Screenshot_20200224-222316](https://user-images.githubusercontent.com/1100614/75192724-171f8600-5755-11ea-9d6b-6bc7c8305175.jpg)

(I am not sure about the background color of the badge. Does this come from uBlock Origin or from Fenix/AC? Because it doesn't seem to be color which is used elsewhere in Fenix.)

### Device information

* Android device: OnePlus 7T Pro McLaren Edition / Android 10
* Fenix version: master branch revision 37b50e08eac9813ba8caff1a48be718babc110a3

**Comment by AndiAJ** [comment]
Reproducible on the latest Nightly Build #20560606 from 02/25 using the following devices:
• Google Pixel 3a XL (Android 10)
• Google Pixel 3a (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7.0.0)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

**Comment by psymoon** [comment]
@AndiAJ @cadeyrn The padding fix was merged last night, can you please verify?

**Comment by cadeyrn** [comment]
Maybe it could have even a bit more padding on the left and right side but it looks much better now, thanks.

**Comment by sv-sdeiac** [comment]
Verified as fixed using the latest version of Firefox Preview Nightly 2/28 #20590606.

Devices:
- Motorola Moto G6 (Android 8);
- Samsung Galaxy Note 8 (Android 9).
