### ISSUE TITLE
[ETP] Custom ETP drop-down menu faded out is too long

### ISSUE THREAD

**Issue by AmyYLee** [mozilla-mobile/fenix#8707]
Steps to reproduce:

1. Go to Settings -> Enhanced Tracking Protection
2. Select Custom
3. Tap on "Cookies" and "Tracking content" drop-down menu

Expected: 
Fade-out duration is the same as 3-dot menu on homescreen and in search bar

Actual: 
Fade-out duration is longer

**Comment by BranescuMihai** [comment]
From what I can see, we use the config_shortAnimTime (200ms) for the three-dot menu.
For the dropdowns in ETP, we use a default from Android of 220ms. 

Given the 20ms difference, for me is not visible. @AmyYLee on your device is it clearly perceivable? Maybe I'm looking at the wrong animations in code.

If anyone wants to investigate further, it looks like DropdownPreference uses com.android.internal.R.style.Animation_DropDownDown as animation style, which has @anim/grow_fade_in for entry, which has a duration of config_activityDefaultDur
