### ISSUE TITLE
[Search] No animation in 3-dot menu

### ISSUE THREAD

**Issue by AmyYLee** [mozilla-mobile/fenix#8708]
Steps to reproduce:
1. Open a new tab from homescreen and type in any URL
2. Tap on the 3-dot menu in the search bar next to the open tabs icon

Expected:
3-dot menu animates in (like the 3-dot menu on homescreen)

Actual:
No animation

**Comment by sblatz** [comment]
I have fixed this in the latest nightly :)

**Comment by sblatz** [comment]
Dupe of https://github.com/mozilla-mobile/fenix/issues/8644

**Comment by sv-sdeiac** [comment]
Verified as fixed using the latest version of Firefox Preview Nightly 2/28 #20590606.

Devices:
- Xiaomi Mi 8 Lite (Android 9);
- Samsung Galaxy Note 8 (Android 9).
