### ISSUE TITLE
Intermittent UI test failure - SettingsBasicsTest.toggleShowVisitedSitesAndBookmarks

### ISSUE THREAD

**Issue by rpappalax** [mozilla-mobile/fenix#8714]
```
toggleShowVisitedSitesAndBookmarks(org.mozilla.fenix.ui.SettingsBasicsTest)
02-24 18:42:05.201: E/TestRunner(8114): ----- begin exception -----
02-24 18:42:05.202: E/TestRunner(8114): androidx.test.espresso.PerformException: Error performing 'replace text(http://localhost:44970/pages/generic2.html)' on view 'with id: org.mozilla.fenix.debug:id/mozac_browser_toolbar_edit_url_view'.
```
[firebase log](
https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7483257809880685962/executions/bs.2a692234e65276ea/testcases/1/logs)

**Comment by AaronMT** [comment]
```Kotlin
androidx.test.espresso.PerformException: Error performing 'replace text(http://localhost:44970/pages/generic2.html)' on view 'with id: org.mozilla.fenix.debug:id/mozac_browser_toolbar_edit_url_view'.

Caused by: java.lang.RuntimeException: Action will not be performed because the target view does not match one or more of the following constraints:
02-24 18:42:05.202: E/TestRunner(8114): (is displayed on the screen to the user and is assignable from class: class android.widget.EditText)
```
`mozac_browser_toolbar_edit_url_view` is an InlineAutocompleteEditText.

https://developer.android.com/reference/android/support/test/espresso/action/ViewActions#replacetext

`replaceText` has a few View conditions:

- must be displayed on screen
- must be assignable from EditText

I'm thinking that we need to wait for the search fragment to load.

**Comment by ekager** [comment]
Ah sorry @AaronMT didn't realize you were looking at this, I actually just saw the trace on another test and took a guess with #8790

**Comment by AaronMT** [comment]
Thanks for taking it on. Let's see if it fixes this in the next few days.

**Comment by AaronMT** [comment]
See: https://github.com/mozilla-mobile/fenix/pull/8749

**Comment by rpappalax** [comment]
@sv-ohorvath @AaronMT re-test 50x successfully. shall we re-enable?
