### ISSUE TITLE
[Bug]The ETP cookies option doesn't match with the ETP info panel

### ISSUE THREAD

**Issue by sv-sdeiac** [mozilla-mobile/fenix#8717]
## Steps to reproduce
1. Go to ETP submenu from settings;
2. Choose the Custom option;
3. Change the Cookie option to a different than the default one;
4. Visit a site(e.g. youtube.com);
5. Tap on the ETP icon from the toolbar.

### Expected behavior
The Blocked cookies match with the last changed cookie option from the ETP menu.

### Actual behavior
The cookies blocked don't match with the change made in ETP menu.

### Device information

* Android device: Samsung Galaxy S8 (Android 9).
* Fenix version: Firefox Preview Nightly 2/25 @20560606.
![20200225_103031](https://user-images.githubusercontent.com/40264165/75229501-b0cd4e80-57ba-11ea-82e9-de4d1dc79c86.gif)

**Comment by mcarare** [comment]
For UX: Is this according to the mocks? Should we display this regardless of the type of cookies selected?
Or do we have updated mocks for this (and strings) that reflect the possible options regarding the cookies?
Thank you!

**Comment by brampitoyo** [comment]
Assigning @AmyYLee to this issue.

**Comment by AmyYLee** [comment]
@mcarare I think the strings in the ETP panel should reflect what was selected in ETP custom settings. @betsymi to make the final decision on strings.

**Comment by betsymi** [comment]
> @mcarare I think the strings in the ETP panel should reflect what was selected in ETP custom settings. @betsymi to make the final decision on strings.

I need to follow up with desktop engineering to better understand this. It might not be a simple matter of changing strings based on how it is implemented. Stay tuned.

**Comment by betsymi** [comment]
@mcarare or @sv-sdeiac Do we know how many Fenix users have selected this setting?

**Comment by AmyYLee** [comment]
@mcarare @sv-sdeiac Follow-up?

**Comment by mcarare** [comment]
@betsymi , @AmyYLee This is not an info I have access to.

**Comment by betsymi** [comment]
Leaving this one as a "won't fix" because I wasn't able to get a clear answer and the percentage of users who change their default settings to custom is low.

**Comment by AmyYLee** [comment]
@betsymi - I checked amplitude and wasn't able to find a probe for "custom". @vesta0 might be able to help find this data if we do have it.

**Comment by vesta0** [comment]
We don't data on "Custom" ETP. Why is this a blocker for fixing this bug? The setting should align to what we show users regardless.
