### ISSUE TITLE
[Bug]Spacing between top sites on homepage is too big

### ISSUE THREAD

**Issue by sv-sdeiac** [mozilla-mobile/fenix#8719]
## Steps to reproduce
1. Add some new Top Sites to the homescreen page;
2. Observe the Homescreen Top Sites list.

### Expected behavior
There is no visual defect displayed.

### Actual behavior
The spacing between the Top Sites options is too large.

### Device information

* Android device: Nexus 9 (Android 7.1.1) - 1536 x 2048 pixels, 4:3 ratio (~281 ppi pixel density);
* Fenix version: Firefox Preview Nightly 2/25 @20560606.
* Notes: The issue is displayed in both Landscape/Portrait mode.
![Screenshot_20200225-122058](https://user-images.githubusercontent.com/40264165/75238500-c5fda980-57c9-11ea-8675-a44997332f0d.png)
![Screenshot_20200225-122014](https://user-images.githubusercontent.com/40264165/75238519-cdbd4e00-57c9-11ea-9c50-1135ef5ae507.png)

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly Build #20570604 from 02/26`** using the following devices:
• Google Pixel 3a (Android 9)
• Samsung Galaxy Tab A (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Google Pixel C (Android 8.0.0)
• Samsung Galaxy S7 (Android 7)
• Huawei MediaPad M3 Lite 10 (Android 7)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

► Screenshot from Samsung Galaxy Tab A
![rsz_screenshot_20200226-142940_firefox_nightly](https://user-images.githubusercontent.com/51314259/75345247-04b46200-58a5-11ea-8dd3-288a32089a08.jpg)
