### ISSUE TITLE
[Bug] nightly startup tasks permafailing: need to be fixed or turned off

### ISSUE THREAD

**Issue by Archaeopteryx** [mozilla-mobile/fenix#8720]
The [nightly startup tasks](https://treeherder.mozilla.org/#/jobs?repo=fenix&group_state=expanded&resultStatus=testfailed%2Cbusted%2Cexception%2Cretry%2Cusercancel%2Crunning%2Cpending%2Crunnable&revision=0434e5391151e11b0c86bdcaf476f153a8c8bca7&searchStr=startup) are failing at least for the last 2 months.

They need to be fixed or turned off.

@sarentz can you drive this?

**Comment by st3fan** [comment]
I am not familiar with these tests, but it looks like these are UI Test (Firebase?) related. The failures can be seen here:

    https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.94bede6510a2f014/matrices/7201758589456773048

@rpappalax  is this something your team is aware of? I saw a discussion on Slack about Firebase failures, maybe that is the same as above?

**Comment by rpappalax** [comment]
@Archaeopteryx @st3fan we were looking into a fix for these in Berlin, but I haven't been able to follow-up on this.  they're broken but non-blocking.  I'll turn them off for now
