### ISSUE TITLE
[Fenix] Update complete notification is not routing to onboarding screen

### ISSUE THREAD

**Issue by Sparky93** [mozilla-mobile/fenix#8722]
Follow-up ticket for A-C [issue](https://github.com/mozilla-mobile/android-components/issues/5996) since work is needed on both of projects for this issue.

**Comment by ebalazs-sv** [comment]
Verified as fixed on Fennec Beta Migration Build 2, 02/27 with LG G7 fit (Android 8.1), Samsung Galaxy S5 (Android 6.0.1) and tapping the "Update complete" notification displays the onboarding screen.
I will move this to Done. Thanks.

**Comment by ebalazs-sv** [comment]
This was verified as fixed in the previous comment, so I will move it to Done.
