### ISSUE TITLE
[Bug] The name of the dashboard tabs is cropped in portrait mode

### ISSUE THREAD

**Issue by DanielOrban** [mozilla-mobile/fenix#8724]
## Prerequisites
- uBlock Origin is installed and enabled in Fenix
- The Fenix language is set to Romanian, Germany or other "long words languages".
## Steps to reproduce
1. Open the Fenix browser.
2. Navigate to "Settings ->Add-ons".
3. Open the uBlock Origin Settings.
### Expected behavior
The name of the dashboard tabs is not cropped in portrait mode. 
### Actual behavior
The name of the dashboard tabs is cropped in portrait mode.
### Device information
* Android device:
-Samsung Galaxy S7 (Android 8.0.0)
-Samsung Galaxy S7 Edge (Android 8.0.0)
* Fenix version: 
-Nightly 200225 (Build #20560607)
-Beta 74.0.0-beta.1 (Build #20551030)

![The name of the dashboard tabs is cropped in portrait mode](https://user-images.githubusercontent.com/43445968/75247602-fef24a00-57da-11ea-9cb4-559b583db788.jpg)

**Comment by csadilek** [comment]
I see this in Fennec too. It would need to be addressed as part of the UX work in uBlock. 

@brampitoyo @kewisch
