### ISSUE TITLE
[Bug] Autofill options does not always show up when interacting with login form

### ISSUE THREAD

**Issue by st3fan** [mozilla-mobile/fenix#8727]
> Taken from https://bugzilla.mozilla.org/show_bug.cgi?id=1616168 - More details on BZ including screenshots.

User Agent: Mozilla/5.0 (Android 10; Mobile; rv:75.0) Gecko/75.0 Firefox/75.0

Steps to reproduce:

Tapping on any login form.A typing cursor is shown.

Actual results:

No autofill dialog.

Expected results:

Some autofill dialog is shown if I have a password manager app. Or if I long press and select "autofill", some autofill workflow should be available.

**Comment by sv-ohorvath** [comment]
This also happened to me on Beta 4.0-build3 on a Huawei P9 (Android 7.0). 
Logged in to Sync.
No autofill for synced logins.
When I saved a new login for 9gag, for example, I got the new login auto-filled.
In cases where I have 2 or more logins synced, or one old, one new (e.g. on twitter) I don't get an auto-fill.

**Comment by yoasif** [comment]
See also https://github.com/mozilla-mobile/fenix/issues/8993

I was going to open this but found this issue.

I can see this if i have multiple Amazon or Google accounts - nothing is autofilled, and I see no way for me to select from a saved login. If I have Lockwise installed, I can actually select from the same logins present there that I have in Fenix (via Sync).

**Comment by mnoorenberghe** [comment]
Selecting from multiple logins is #5551
