### ISSUE TITLE
Add-ons - Both main and detailed descriptions don't follow the selected language

### ISSUE THREAD

**Issue by Diana-Rus** [mozilla-mobile/fenix#8729]
Taken from https://bugzilla.mozilla.org/show_bug.cgi?id=1617912

## Steps to reproduce
1. Menu > Settings > Language > Portuguese (Brasil)
2. Menu > Addon Manager > uBlock Origin > Details
Localized: [- Menu > Gerenciador de extensões > uBlock Origin > Detalhes]

### Expected behavior
uBlock Origin main description and detailed description are still in English, despite they are available in Portuguese (Brasil), as you can see on Firefox Desktop.

### Actual behavior
It should show the localized version of the descriptions.

### QA Device information

* Android device: OnePlus 6T (Android 9)
* Fenix version: Firefox Preview Nightly 200225 (Build #20560606) GV: 75.0a1-20200223093951

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-15964)

**Comment by Amejia481** [comment]
Unfortunately,  this is a known issue. Fixing it requires a lot of work on different layers more here  https://github.com/mozilla-mobile/fenix/issues/8188#issuecomment-588300299. The workaround  at the moment is to kill the app and re-open it :(

**Comment by softvision-miralobontiu** [comment]
I was able to reproduce this issue with OnePlus 5T (Android 9), and Samsung Galaxy Tab A6 (Android 5.1.1), on the latest Nightly build from 3/18.

Workaround: force stopping Fenix, fixes the issue.

**Comment by AndiAJ** [comment]
Still reproducible on Beta 90.0.0-beta.1 from 6/2 using a OnePlus A3 (Android 6.0.1)

**Comment by AndiAJ** [comment]
Still reproducible on Firefox 98.0.0 Beta 1

**Comment by amocirean** [comment]
Reopened as the issue is still Reproducible on Firefox 109.0b2.

**Comment by SoftVision-LorandJanos** [comment]
Still reproducible on 110.0b2 build.
Device used: Oppo Find X5 (Android 12).

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812835

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
