### ISSUE TITLE
Hard to read black font in the History menu in PB

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#873]
## Steps to reproduce
1. Open a few tabs to have some items in browser history.
2. Go to Private browsing> Library>History.
### Expected behavior
The websites are displayed in the theme's color (white?).
### Actual behavior
Websites are in black font.
### Device information

* Android device: Pixel (Android 9)
* Fenix version: 1.0.1910 (3/5 build)

**Comment by kbrosnan** [comment]
dupe of #860

**Comment by sv-ohorvath** [comment]
Verified as fixed on master build 3/13.
