### ISSUE TITLE
Fit text to width on non-mobile pages (wrap words like Opera)

### ISSUE THREAD

**Issue by andreymal** [mozilla-mobile/fenix#8736]
Firefox and Chrome are actually absolutely unusable on Android because the font size on desktop pages (when the "Desktop site" checkbox enables [consistent font-size](https://github.com/mozilla-mobile/fenix/issues/8735)) is too small.

At today Opera for Android is the best browser because it automatically wraps text according to the current zoom (best since Opera Mini 4 on J2ME!).

I want to have a option to enable this behavior in Firefox / Fenix, then I can migrate from Opera.

You can use any desktop website as an example.

Actual / expected behavior (Fenix / Opera) (click to view):

[![](https://i.imgur.com/9mMJdQWm.png)](https://i.imgur.com/9mMJdQW.png) [![](https://i.imgur.com/jWNys6em.png)](https://i.imgur.com/jWNys6e.png)

Good old Opera Mini:

![](https://i.imgur.com/d4vvtTa.png)

**Comment by kbrosnan** [comment]
Duplicate #808

**Comment by andreymal** [comment]
Weird, I could not find this issue using github search... But okay
