### ISSUE TITLE
Crash while loading a normal & a private tab in parallel

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#874]
[Logcat](https://github.com/mozilla-mobile/fenix/files/2936946/pb.vs.nb.tabs.txt)
## Steps to reproduce
1. In normal browsing, open a webpage.
2. Go to PB and load a webpage.
### Expected behavior
Both tabs are loaded.
### Actual behavior
Fenix crashes.
### Device information

* Android device: Pixel (Android 9)
* Fenix version: 1.0.1910 (3/6 build)

**Comment by sblatz** [comment]
I'm not able to reproduce this. Are you going to the home view or switching via "open new private tab" in the menu option? I'm trying to do it as quickly as possible but cannot trigger it.

**Comment by sv-ohorvath** [comment]
@sblatz This doesn't reproduce anymore (verified on master build 3/13). It was crashing just by loading a page in each mode, no other conditions.
