### ISSUE TITLE
Don't highlight PWA Install if already installed

### ISSUE THREAD

**Issue by NotWoods** [mozilla-mobile/fenix#8741]
### Why/User Benefit/User Problem
Thanks to @TitanNano we can now approximately detect if a PWA was already installed. If we navigate to an already installed PWA, we should show the "Install" option but not highlight it. This is similar to Chrome's behaviour.

We may want to wait until browser-menu2 is available before adding this feature.

### What/Requirements
Example usage:
- Navigate to Twitter website in browser
- "Install" menu option has a highlight that adds a blue dot to the menu
- Install Twitter PWA
- Navigate to Twitter again in browser
- "Install" menu option is still present but not highlighted, so no dot is added to the menu.

### Acceptance Criteria (how do I know when I’m done?)
Should not highlight already installed PWAs.

**Comment by ekager** [comment]
We are only highlighting once now, so I think this is irrelevant.
