### ISSUE TITLE
[Bug] dynamic bottom bar: truncated bottom content until you scroll (but not on all websites)

### ISSUE THREAD

**Issue by cadeyrn** [mozilla-mobile/fenix#8757]
### Steps to reproduce

1. open twitter.com

### Expected behavior

No truncated content.

### Actual behavior

Content which is fixed on the bottom is truncated until you scroll and the browser toolbar hides. Interestingly I can't reproduce on my own websites like soeren-hentzschel.at.

### Device information

* Android device: OnePlus 7T Pro McLaren Edition / Android 10
* Fenix version: master branch revision c87c8378658f8b04b647ec245d5b3b7c4fb2e027

**Comment by concastinator** [comment]
This seems to be related to the fact that social media buttons on a page are sometimes not displayed properly: an example is https://www.timesnewroman.ro/monden/panica-in-supermarket-dupa-ce-unui-barbat-i-s-a-facut-rau-cand-a-vazut-cate-a-cumparat-sotia - see the screenshot for what I mean.
![Screenshot_20200226-141147](https://user-images.githubusercontent.com/57685970/75344065-7212c380-58a2-11ea-8914-21bbb9c3798b.png)

**Comment by ekager** [comment]
Closing for #10043
