### ISSUE TITLE
[Bug] different behaviour with dynamic top and bottom toolbar on non-scrollable pages

### ISSUE THREAD

**Issue by cadeyrn** [mozilla-mobile/fenix#8758]
### Steps to reproduce

1. open a website which can't be scrolled, for example GitHub notifications without any unread notification.

### Actual behavior

The toolbar hides when you scroll.

### Expected behavior

Same behaviour with top and bottom toolbar (I prefer that the toolbar does not hide at all when you scroll on a non-scrollable page because it _feels_ wrong for me).

The toolbar also hides when you scroll with the top toolbar but the behaviour is different: With the top toolbar the toolbar hides and the whole websites moves, with the bottom toolbar only the toolbar hides, the website stays fixed.

### Device information

* Android device: OnePlus 7T Pro McLaren Edition / Android 10
* Fenix version: master branch revision c87c8378658f8b04b647ec245d5b3b7c4fb2e027

**Comment by TitanNano** [comment]
Maybe I'm misunderstanding you, but how should the page move when the bottom toolbar hides?

**Comment by cadeyrn** [comment]
Try it with https://github.com/notifications/beta?query=is%3Aunread (but make sure that you don't have a lot of unread notifications ;-) ) and compare the behaviour of the top and the bottom toolbar.

a) top toolbar: the toolbar hides and the page scrolls as well
b) bottom toolbar: the toolbar hides and the page stays fixed

The page should not scroll at all but it does because of the dynamic toolbar. Maybe this is okay but then the behaviour of the top and the bottom toolbar should still be the same. With the current implementation the behaviour of the bottom toolbar feels strange.

**Comment by TitanNano** [comment]
But the top toolbar does not want to cover the top of the page, that's why it's pushed down. Once the page is scrolled the toolbar hides and the top of the page moves up, allowing the page to occupy the entire screen space. 

For the bottom toolbar the page simply gets more space at the bottom of the screen once the toolbar hides so there is nothing to move.

**Comment by cadeyrn** [comment]
This issue no longer exists.
