### ISSUE TITLE
[Bug] "Recently Used" section in Share menu occupies too much space

### ISSUE THREAD

**Issue by SL-Lee** [mozilla-mobile/fenix#8759]
# Steps to reproduce

1. Open the share menu and tap on an icon. Repeat this step for several times.

# Expected behavior

The "Recently Used" section occupies only a small portion of the available space in the Share menu.

# Actual behavior

The "Recently Used" section occupies majority of the space, resulting in the "All Apps" section having a ridiculously little amount of space.

![](https://user-images.githubusercontent.com/45960387/75329800-43edad80-58bb-11ea-934b-0addb48c0924.png)

# Device information

* Android device: Oppo Reno 2, Android 9
* Fenix version: Nightly 200226 06:01 (Build #20570605)

**Comment by mcarare** [comment]
Question for UX: Should we limit the space for "Recently used "(while keeping it scrollable), or the current behaviour is the one expected? TY!

**Comment by dep-dt** [comment]
I'd love a simple long-press on a pinned share item to remove it. that'd help.

**Comment by ekager** [comment]
If I understand the problem correctly, I think the recently used app section should "scroll with" the other list? Does that make sense/is possible?

**Comment by brampitoyo** [comment]
Would it help if the amount of recent apps/actions are reduced to 6? That way, you’ll have space for at least 2 apps in the “All” list.

**Comment by dep-dt** [comment]
> Would it help if the amount of recent apps/actions are reduced to 6? That way, you’ll have space for at least 2 apps in the “All” list.

I think 6 is a good max. maybe even 4.  Max of 6 with longpress to remove would solve the problem for me.

**Comment by dep-dt** [comment]
> If I understand the problem correctly, I think the recently used app section should "scroll with" the other list? Does that make sense/is possible?

I like @ekager's idea as well, in addition to a sensible max.  👍

**Comment by brampitoyo** [comment]
Great. That behaviour works for me. Thanks @ekager @dep-dt for the ideas and inputs!

Let’s decide on:

- Having 6 recently used actions
- The “Recently used” section should be able to scroll horizontally, so “All apps” can be accessed

**Comment by DrCesar** [comment]
I like to give this a shot. Currently limited to 6 items and trying to make the section horizontally scrollable. Any tip is welcome.

**Comment by brampitoyo** [comment]
@mcarare @ekager Hmm. Apparently the Share sheet isn’t yet implemented according to spec. See #9332.

The spec doesn’t have “Recently used” or “All actions”. Instead, it calls for a section called “Share a link”.

**Comment by liuche** [comment]
Let's double check what the UX spec is in #9332 before continuing.

**Comment by BranescuMihai** [comment]
Regarding the 6 items limit, it's actually already implemented, just tested it on Android 10 OnePlus 7 and it worked as expected. We should investigate why this doesn't work on some devices

**Comment by SL-Lee** [comment]
This has been fixed for a while now, so closing this issue.
