### ISSUE TITLE
[Bug] www.resetera.com - Blank favicon created on Home Screen

### ISSUE THREAD

**Issue by softvision-sergiulogigan** [mozilla-mobile/fenix#8760]
Initially, reported here: https://github.com/webcompat/web-bugs/issues/48889

URL: https://www.resetera.com/forums/etcetera-forum.9/

Browser / Version: Firefox Mobile 75.0
Operating System: Android
Tested Another Browser: Yes

Problem type: Something else
Description: "Add to Homescreen" favicon is blank.
Steps to Reproduce:
"Add to Homescreen" favicon is blank. This issue does not happen with Chrome or Firefox non-Preview. Please refer to my screenshot.

![image](https://user-images.githubusercontent.com/16573771/75332006-556b9100-588c-11ea-91ba-d41ad44c3870.png)

**Comment by Fatalah** [comment]
Thanks for taking this issue on!

**Comment by Diana-Rus** [comment]
Hi, i'll close this issue as there is a different one that is more updated and has been triaged #9916.
@Fatalah , please monitor the process on the other ticket , we will take in consideration the mentioned site in this issues description 😊.
