### ISSUE TITLE
[Bug] Open in Fenix from a PWA custom tab, replaces the PWA with Fenix

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#8761]
## Steps to reproduce
1. Add pwa.rocks or starbucks.com as PWAs.
 *Not reproducing with twitter.com
2. Open the PWA, open an external link in a custom tab.
3. From the custom tab, open the link in Fenix.
### Expected behavior
Fenix is launched as a separate task.
### Actual behavior
Fenix replaces the PWA task.
![20200226-112100](https://user-images.githubusercontent.com/4037709/75332288-d165d900-588c-11ea-9fca-544d775742ea.gif)

### Device information

* Android device: Pixel 3 (Android 10), 
* Fenix version: Nightly 2/26

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-15986)

**Comment by AndiAJ** [comment]
**Reproducible** on the latest on the latest **`Nightly Build 201111`** using the following devices:
• Google Pixel 3a (Android 11)
• Huawei Mate 20 Lite (Android 10)
• OnePlus A3 (Android 6.0.1)

**Comment by sv-ohorvath** [comment]
Still reproducing on Nightly 5/12.
