### ISSUE TITLE
List element component

### ISSUE THREAD

**Issue by topotropic** [mozilla-mobile/fenix#8765]
The list element is used in 
- bookmarks, 
- history, 
- in a collection to list included sites

it should be a component with the below described spec that can be used in above listed places

<img width="420" alt="image" src="https://user-images.githubusercontent.com/353960/75345843-cbc4bf00-589d-11ea-8197-e9893dc061f7.png">

**Comment by NotWoods** [comment]
When items are being selected (i.e. multiple bookmarks, or creating a collection), where should the checkmark appear? In bookmarks the favicon turns into a checkmark, and in collections the checkmark appears in place of the close button.

**Comment by NotWoods** [comment]
Some other concerns:
- What is the color of the caption in dark mode?
- What should the layout be for a folder in bookmarks? Currently we hide the caption and center the label.

**Comment by AmyYLee** [comment]
@NotWoods Dark mode captions: Light grey 70 (#9F9FAD)
@topotropic for layout feedback.

**Comment by topotropic** [comment]
> When items are being selected (i.e. multiple bookmarks, or creating a collection), where should the checkmark appear? In bookmarks the favicon turns into a checkmark, and in collections the checkmark appears in place of the close button.

Follow the bookmark model for selection and turn the favicon into a checkmark. We'll revisit how select works for Collections as part of this issue https://github.com/mozilla-mobile/fenix/issues/10163.


>     * What should the layout be for a folder in bookmarks? Currently we hide the caption and center the label.
Yes, that's still correct. We should follow the material guidelines here https://material.io/components/lists#specs

Looking at this again, I also realized that the shared font size here is too small and we should use 16 for the label and 12 for caption. Thanks!
<img width="437" alt="image" src="https://user-images.githubusercontent.com/353960/87521941-4e032380-c685-11ea-9db9-ae6cd5d63c17.png">

**Comment by eliserichards** [comment]
Approved:
* https://github.com/mozilla-mobile/fenix/pull/13883 

Requested changes: 
* https://github.com/mozilla-mobile/fenix/pull/14114

Waiting:
* https://github.com/mozilla-mobile/fenix/pull/14316 waiting on #13883 to land
