### ISSUE TITLE
Don't show collection when no open tabs + no collection

### ISSUE THREAD

**Issue by topotropic** [mozilla-mobile/fenix#8766]
### Why/User Benefit/User Problem
When a users doesn't have open tabs or collections, don't show the empty state collections section.This helps to de-clutter the home screen. Also prevents the issue that when people open up Fenix for the first time, tap on collection empty state (w/o any open tabs) nothing happens.

### What/Requirements
- when a user has no open tabs AND no collections, hide the collections sections
- when a user has open tabs, show the collections sections
- when a user has collections, show the collections section

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly Build #20630607 from 03/03`** using the following devices:
• Google Pixel 3a (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

| Status  | Requirement|
| ------------- | ------------- |
| ✔️ | when a user has no open tabs AND no collections, hide the collections sections  |
| ✔️ | when a user has open tabs, show the collections sections  |
| ✔️ | when a user has collections, show the collections section  |


► Video
![20200303-095103](https://user-images.githubusercontent.com/51314259/75754444-6d805c00-5d35-11ea-8462-dbaaaff154a1.gif)
