### ISSUE TITLE
[Bug] Fenix is super crashy today

### ISSUE THREAD

**Issue by staktrace** [mozilla-mobile/fenix#8767]
## Steps to reproduce

Go to any of these urls:
- https://www.cbc.ca/news/politics/travel-coronavirus-champagne-advisories-1.5475003?cmp=rss
- https://mobile.twitter.com/elonmusk/status/1232566420006821888

Not having any sort of working about:crashes really really sucks.

### Expected behavior

- page loads

### Actual behavior

- Fenix crashes either instantly or after scrolling a bit

### Device information

* Android device: sony xz1c, andoid 9
* Fenix version: Nightly 200225 18:01 (Build #20561806)
34.0.0, ac78e22f1
GV: 75.0a1-20200223093951

**Comment by Screwtapello** [comment]
Dupe of #8739 ?

**Comment by concastinator** [comment]
@staktrace, could you please update to the latest Nightly and check if it works properly? For me it does, and I had encountered the same problems as you.

**Comment by staktrace** [comment]
Indeed updating fixes the crashes I was seeing, thanks!
