### ISSUE TITLE
[Bug]Downloads- Download pop-up cannot be dismissed

### ISSUE THREAD

**Issue by Diana-Rus** [mozilla-mobile/fenix#8770]
## Steps to reproduce
1. Open app and go to thinkbroadband.com/download.
2. Tap on the button for a file in order to start the download process.
3. Tap outside the pop up.
### Expected behavior
The pop up is dismissed.
### Actual behavior
The pop up cannot be dismissed.
### Device information

* Android device: OnePlus 6T (Android 9), Samsung Galaxy S9(Android 8.0.0), Sony Xperia Z5 (Android 7.0.0)
* Fenix version: Firefox Preview Nightly 200226 (Build #20570604) GV:75.0a1-20200225094028

<details open>
<summary>Gif</summary>
<br>

![20200226-151312](https://user-images.githubusercontent.com/49859863/75348135-e6516500-58aa-11ea-9e42-095522d08fe9.gif)
</details>

**Comment by mcarare** [comment]
This is the system permission dialog, that cannot be dismissed and there is nothing we can do about this behaviour. Due to this, I am going to close this.
