### ISSUE TITLE
[Bug] The "Back" button does not respond accordingly in the logger page

### ISSUE THREAD

**Issue by DanielOrban** [mozilla-mobile/fenix#8771]
## Prerequisites
- uBlock Origin is installed and enabled in Fenix
## Steps to reproduce
1. Navigate to a website (eg. www.bbc.com).
2. Tap on the three-dot menu and tap on the uBlock Origin's icon.
3. Open the logger and press the device back button.
### Expected behavior
Tapping the back button should return to the "Open tabs" page.
### Actual behavior
Nothing happens. If the screen is scrolled to the edge, tapping the back button only switches the screen from side to side. If the screen is scrolled out, the back button does nothing.
### Device information
* Android device:
-Samsung Galaxy S7 (Android 8.0.0)
-Samsung Galaxy S7 Edge (Android 8.0.0)
* Fenix version: 
-Nightly 200226 (Build #20570605)
-Beta 74.0.0-beta.1 (Build #20551030)

![The Back button does not respond accordingly in the logger page](https://user-images.githubusercontent.com/43445968/75351919-91651d00-58b1-11ea-9da1-6ff65ca90587.gif)

**Comment by agi90** [comment]
This is a GV bug, can reproduce on GVE too: https://bugzilla.mozilla.org/show_bug.cgi?id=1626117 probably something to do with popup windows.

**Comment by softvision-miralobontiu** [comment]
I was not able to reproduce this issue on the 12/3 Firefox Nightly build with Samsung Galaxy Tab S6 (Android 10), nor on Samsung Galaxy Note 8 (Android 9).
@DanielOrban could you retry on your devices?
Thank you!
