### ISSUE TITLE
[Bug] Load progress indicator hidden together with the navigation bar

### ISSUE THREAD

**Issue by concastinator** [mozilla-mobile/fenix#8774]
## Steps to reproduce

Configure the navigation bar to be at the bottom. Open any page.

### Expected behavior

The load progress indicator (a coloured line stretching from left to right as the page loads) should be visible, showing how much of the page is left to load.

### Actual behavior

The load progress indicator is automatically hidden together with the newly made-dynamic navigation bar.

### Comment

A fix for this is for the user to swipe up, making the navigation bar temporarily visible, and the load progress indicator with it. I believe that this is bad UI design, though, and that a more elegant solution should be found instead.

### Device information

* Android device: Nokia 5, Android 9
* Fenix version: every version of Nightly since the recent introduction of the dynamic navigation bar.

**Comment by jscher2000** [comment]
I hate to "+1" an issue, but this is a big problem for me: when I tap a link, I can't tell whether Firefox is starting to open the link, or I missed it, or it wasn't a link, or what the heck is going on.

(Fx Nightly with nav bar at the top)
