### ISSUE TITLE
[Bug] dynamic bottom bar hides the text field in Twitter DMs

### ISSUE THREAD

**Issue by bogas04** [mozilla-mobile/fenix#8777]
## Steps to reproduce
1. Open twitter.com direct messages
2. Scroll to hide bottom bar
3. Tap on text field.

### Expected behavior
Text field is hidden behind

### Actual behavior
text field should be visible

![Screencast](https://thumbs.gfycat.com/GreedyHappygoluckyEastrussiancoursinghounds-size_restricted.gif)

### Device information

* Android device: Realme X, Android 9
* Fenix version: Firefox Nightly 200226 10:12 (Build #2015725267)
34.0.0, 03451de2e
GV: 75.0a1-20200225094028

**Comment by softvision-miralobontiu** [comment]
Verified as fixed on the latest Nightly build from 4/22 with Sony Xperia Z5 Premium (Android 7.1.1), OnePlus 5T (Android 9), and Google Pixel (Android 10).
