### ISSUE TITLE
[Bug] On my first search, the urlbar/searchbar briefly skips across the screen, with "Search or enter address" placeholder text

### ISSUE THREAD

**Issue by dholbert** [mozilla-mobile/fenix#8781]
## Steps to reproduce
1. Quit Fenix if it's running.
2. Open Fenix.
3. Tap the location/search bar, type "test", and hit enter.

### Expected behavior
The top-of-screen search/location bar should disappear and be replaced with one at the bottom of the screen.

### Actual behavior
(1) The location/search bar (including the search engine icon) briefly snaps down to be above the keyboard (so, about 50% of the way down my screen), and it regains its placeholder text "Search or enter address" for a moment.
(2) Then the URL/search bar fades away, with the keyboard, and the search/location bar at the bottom of the screen comes back.

This happens for me ~100% of the time, on the first search that I do in a browsing session. If I then do another search via the same STR (without quitting Fenix), I don't see the issue. 

### Device information
* Android device: Pixel 3
* Fenix version: Nightly 200225 18:01, built Tuesday 2/25 @ 6:05pm

**Comment by dholbert** [comment]
Here's a screenshot of the URL/search bar at its brief buggy position atop the keyboard, just before it fades away:
![vlcsnap-2020-02-26-11h25m22s686](https://user-images.githubusercontent.com/426803/75379760-c611ae00-588a-11ea-9afb-8408653cfd79.png)

Here's a screencast, where the issue happens at around 4s (it's easier to see if you play it in slow-motion in a local video player): 
https://www.dropbox.com/s/diq59xeen79awun/fenix-searchbar-jump.mp4?dl=0

**Comment by dholbert** [comment]
Actually, I do see this on subsequent searches as well, but it's not quite as noticeable, because the searchbar is sized/positioned better, and it changes quickly to contain the correct contents. Below, I'll post some snapshots from the key moments in this animation (on the second time I've done a search for "test" via the URLbar).  I think my above-posted issue is just a jankier version of this more-fluid-yet-still-janky animation.

**Comment by dholbert** [comment]
(Sorry for the size of these screenshots)

So, for my second search for the word "test", here is:
(1) First frame of animation, after I've typed "test" and hit enter: the url/searchbar snaps halfway down the screen (and loses the search engine icon for some reason):
![vlcsnap-2020-02-26-11h36m33s979](https://user-images.githubusercontent.com/426803/75381136-138f1a80-588d-11ea-9673-99cb8c27bb14.png)

**Comment by dholbert** [comment]
(2) Second frame of animation: the search engine icon loads (rendering is otherwise unchanged from previous frame):
![vlcsnap-2020-02-26-11h37m24s927](https://user-images.githubusercontent.com/426803/75381278-551fc580-588d-11ea-8c5b-6428f333362c.png)

**Comment by dholbert** [comment]
(3) Third frame of animation: the search engine icon disappears, and the bar now looks the way it looks when it's at the bottom of the screen (even though it's still halfway down), with star/shield/tabcount/meatball-menu. The "Search or enter address" text is still present.
![vlcsnap-2020-02-26-11h37m30s372](https://user-images.githubusercontent.com/426803/75381376-80a2b000-588d-11ea-9051-0c384d99dce0.png)

**Comment by dholbert** [comment]
(4) Fourth frame of animation: the URL now appears in the location bar (no more placeholder text), the star disappears, and a broken lock icon appears (presumably broken just because we haven't completed the HTTPS connection yet):
![vlcsnap-2020-02-26-11h37m36s342](https://user-images.githubusercontent.com/426803/75381501-b6479900-588d-11ea-8dc2-89b30d80a6c0.png)

**Comment by dholbert** [comment]
(5) Fifth frame of animation: the same as the fourth, but now with a progress bar:
![vlcsnap-2020-02-26-11h37m41s618](https://user-images.githubusercontent.com/426803/75381570-cfe8e080-588d-11ea-8819-f93b0dae4fa3.png)

**Comment by dholbert** [comment]
(6) Sixth frame of animation: the URLbar snaps to the bottom behind the keyboard, and the keyboard starts to fade:
![vlcsnap-2020-02-26-11h37m59s675](https://user-images.githubusercontent.com/426803/75381610-e55e0a80-588d-11ea-90df-86d9a2d90019.png)

**Comment by dholbert** [comment]
Here's a screencast showing a first search (a bit more slideshow-feeling) and a second search (more frames of animation, though with more perhaps-unnecessary content changes between them):

https://www.dropbox.com/s/nkhmuwc5wof4t8b/fenix-searchbar-jump2.mp4?dl=0

The series of screenshots that I just attached are taken directly from around the 11-second mark in this screencast.

**Comment by dholbert** [comment]
So anyway, my takeaways/concerns here are:

 (1) in the first search, the brief time where the url/searchbar is at the center feels pretty jumpy and kind of like a floating popup briefly appeared/disappeared (which causes a bit of unease). This happens at around the 4s mark in the screencast that I just posted.

 (2) in the second search, the transition is a bit less obviously jumpy, but the 6 intermediate screenshots above suggest to me that perhaps we might want to reduce the number of intermediate states (or allow them to coalesce together in cases where we're progressing quickly between them?), since these adjacent states are noticeably different-looking, and we snap between them pretty rapidly which still makes things look a bit jumpy/jerky.

**Comment by mcarare** [comment]
@dholbert  Is this still reproducible for you? There have been some changes in animations lately. Thank you for the detailing of this issue!

**Comment by dholbert** [comment]
Yes, seems to be fixed in current Fenix nightly. Thanks!
