### ISSUE TITLE
[Bug] Planet mozilla content gets visibly clipped when dynamic toolbar is hidden

### ISSUE THREAD

**Issue by staktrace** [mozilla-mobile/fenix#8784]
## Steps to reproduce

Go to https://planet.mozilla.org
Scroll down slightly so that the toolbar hides

### Expected behavior

The content on the page is visible all the way down to where it touches the Android navbar

### Actual behavior

The content on the page is clipped halfway down the space the toolbar used to occupy. Note that the horizontal scrollbar is also misplaced, and that's tracked by [bug 1598978](https://bugzilla.mozilla.org/show_bug.cgi?id=1598978#c4)

### Device information

* Android device: Sony Xperia XZ1C, Android 9
* Fenix version: Nightly 200226 06:01 (Build #20570605) 34.0.0, 53f1356d7 GV: 75.0a1-20200225094028

**Comment by staktrace** [comment]
![_20200226_142438](https://user-images.githubusercontent.com/485789/75379702-d5e9bc00-58a3-11ea-8d27-e1e617dc56da.JPG)
Screenshot showing clipped area circled in red

**Comment by staktrace** [comment]
Turns out this only happens if WebRender is enabled (which it is by default on my device). If I set gfx.webrender.force-disabled to true and restart, WebRender is disabled and it no longer happens.

**Comment by hiikezoe** [comment]
Filed https://bugzilla.mozilla.org/show_bug.cgi?id=1619169 .

**Comment by hiikezoe** [comment]
Now the bug has been fixed in nightly.

**Comment by Diana-Rus** [comment]
Hi, i didn't reproduced the issue on Nightly 6/15 Sony Xperia Z5 (Android 7) with webrender manually enabled nor when the address bar is set at bottom and neither when is set at the top.
I also didn't reproduced it with Pixel 3 XL (Android 9) for which webrender is enabled by default.
**GIF - Sony Xperia Z5**
![20200615-141241](https://user-images.githubusercontent.com/49859863/84652232-f782b800-af13-11ea-85c0-11a159865c16.gif)

Verified sites:
- https://planet.mozilla.org/
- xkcd.com
- wikipedia.org
- theverge.com

Note: Managed to reproduce the issue with Sony Xperia Z5 (Android 7) on the build Nightly 2/26.
