### ISSUE TITLE
Test performance on alternate devices like OnePlus

### ISSUE THREAD

**Issue by emalysz** [mozilla-mobile/fenix#8785]
Following up from https://github.com/mozilla-mobile/fenix/issues/7880.

We should investigate if performance metrics are different on devices that we are not currently testing such as the OnePlus (McLaren). 

Points to investigate: 
- Does the system's placeholder frame take a long time to disappear? (is this because mismatched themes? system dark, fenix light https://github.com/mozilla-mobile/fenix/issues/6572)
- (Should no longer be an issue) Is there a pause before app launch when clicking home screen?

**Comment by mcomella** [comment]
Triage: csadilek & andreasbovens both have OnePlus test devices. Assigning csadilek to quickly check if this device is unreasonably slow (i.e. stays on the system's placeholder frame too long) when launching cold start from the homescreen. If so, please notify the team. If not, please unassign and put into low impact.

**Comment by mcomella** [comment]
Triage: andreasbovens tested and saw no change in perf of the placeholder frame between device configuration modes. ecsmyth notes that on the reference device refresh, we'll have multiple chipsets in automation so it'll be tested there.

Closing as nothing else to do.
