### ISSUE TITLE
[Bug] Can get into a situation where the displayed URL does not match the webpage content (possibly security issue?)

### ISSUE THREAD

**Issue by staktrace** [mozilla-mobile/fenix#8787]
## Steps to reproduce

(Note that the order in which you open the two tabs here is important, the hacker news tab should be above the treeherder tab in the tabs list)
1. Open a tab with https://treeherder.mozilla.org
2. Open a second tab and navigate to https://news.ycombinator.com
3. Switch back to the treeherder tab
4. Click on the log in button on the top-right. Follow the login flow and enter credentials as prompted.

### Expected behavior

URL displayed in URL bar always matches the content displayed in the content area

### Actual behavior

At some point during this process you will end up in a state where the URL bar shows the treeherder URL but the content is displaying the hacker news content.

Note: When exactly this happens may vary depending on whether you are logging in for the first time or this is a subsequent attempt. When I confirmed the STR just now I did it after filing #8786 and logging out of TH, but I guess I had cookies or something that streamlined the login flow and it pretty much jumped straight into the bad state. IIRC the first time I saw this (this morning) I didn't have those cookies and the login flow had more steps but I still saw the problem at some point.

### Device information

* Android device: Sony Xperia XZ1C, Android 9
* Fenix version: Nightly 200226 06:01 (Build #20570605) 34.0.0, 53f1356d7 GV: 75.0a1-20200225094028

**Comment by staktrace** [comment]
![Screenshot_20200226-143556](https://user-images.githubusercontent.com/485789/75381186-50b3d680-58a6-11ea-9cff-fe6af86d90a3.png)

**Comment by staktrace** [comment]
Note that this likely has to do with the fact that the login flow for TH opens and closes some windows.

**Comment by softvision-miralobontiu** [comment]
Hi, @staktrace 
Could you please verify on the latest Firefox Nightly?
Thanks!

**Comment by staktrace** [comment]
I don't see this anymore. Thanks!
