### ISSUE TITLE
Replace our TabCounter with the AC version

### ISSUE THREAD

**Issue by ekager** [mozilla-mobile/fenix#8791]
In #8505 we replaced our tab counter icon with a more centered one that doesn't require as much customization on top of the AC code. I think we could now use the AC version of TabCounter and delete the Fenix-unique files. This ticket will need a bit of investigation to figure out if we are doing anything else custom here, and if we need to add anything to AC to use the correct icon/tinting.

**Comment by eliserichards** [comment]
AC docs: https://github.com/mozilla-mobile/android-components/tree/master/components/ui/tabcounter
