### ISSUE TITLE
[Bug] (regression) tab icon is missing

### ISSUE THREAD

**Issue by cadeyrn** [mozilla-mobile/fenix#8792]
### Steps to reproduce

1. open a tab

### Expected behavior

The number of open tabs is within a tab icon.

### Actual behavior

The tab icon is missing. Probably a regression from #8505? /cc @darkwing 

![Screenshot_20200226-215046](https://user-images.githubusercontent.com/1100614/75386744-7f4fa280-58e2-11ea-98c9-9ff0839a8e13.jpg)

### Device information

* Android device: OnePlus 7T Pro McLaren Edition / Android 10
* Fenix version: master branch revision 9612c3f16d6ce11a32eae4c01b8ac0fb6008fc7f

**Comment by abodea** [comment]
Verified as fixed on the latest **Nightly 2/27** and **Beta 4.0.0-Beta2** with Google Pixel 3 (A 9), Google Pixel 3a XL (A 10).
The tab icon is displayed correctly.
