### ISSUE TITLE
[Bug] Scrolling on top top sites will expand/collapse top sites rather than scrolling entire parent container

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#8797]
## Steps to reproduce
- Place finger on top sites and try scroll gesture (may need multiple tabs open)

### Expected behavior
Top sites does not scroll, entire page does

### Actual behavior
Top sites scrolls instead of entire page

### Device information

* Android device: ?
* Fenix version: ?

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly Build #20630607 from 03/03`** using the following devices:
• Google Pixel 3a (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

► Video
![20200303-120828](https://user-images.githubusercontent.com/51314259/75766162-5fd4d180-5d49-11ea-8e5d-a46c07fde187.gif)
