### ISSUE TITLE
Migration Notifications

### ISSUE THREAD

**Issue by lime124** [mozilla-mobile/fenix#880]
### User Story

As a user I want to have a seamless experience as I transition from using Fennec to Fenix.

**[Known Scenarios](https://docs.google.com/presentation/d/1LkNh7BRUaTvzo46Dm1arzvw8t8OQPfHd1bp-f8K2v38/edit#slide=id.g73e266467b_0_467)**

### Acceptance Criteria

- As a Fennec user, I know that Fenix will replace Fennec (and when)
- As a Fennec user, I know what will happen to my data during migration, what data will be migrated, what to expect after the migration, and how to prepare. 

- As a Fennec beta user, I know what to expect before the migration.
- As a Fennec nightly user, I know what to expect before the migration. 
- As a Firefox Preview user, I know what to expect before the migration. 

**This is part of [Meta] Fennec -> Fenix Migration User Experience #879**

**Comment by lime124** [comment]
un-assigning Amy and Nicole - we'll see who is available when we get to this story for Q3 and re-assign. 

Also removing the ux label, I've added it to the migration UI ticket for consideration while we design for that issue.

**Comment by vesta0** [comment]
@athomasmoz I expect this work to happen in Fennec. @apbitner please include Ashley in design reviews :)

**Comment by apbitner** [comment]
cc: @mheubusch

**Comment by vesta0** [comment]
These scenarios are covered under #879
