### ISSUE TITLE
Clear browser menu highlights

### ISSUE THREAD

**Issue by Baron-Severin** [mozilla-mobile/fenix#8800]
Spun out of https://github.com/mozilla-mobile/fenix/issues/7408#issuecomment-587551828

### Why/User Benefit/User Problem
- Un-clearable highlights (blue dots) on menu options can be annoying to users
- We should clear these highlights after the user has seen them

### What/Requirements
For `reader view`, `open in app`, and `PWA`
- By default, show a highlight (already implemented)
- After the user has opened the menu with the highlight visible, never show it again after they either:
  - Select the option
  - Or close the menu

### Engineering investigation notes
- Menu close events in the BrowserFragment do not appear to be exposed to the client.  I asked about how to approach the problem [here](https://mozilla.slack.com/archives/CA4JKKLSG/p1582756729021100).  It may require updates to AC.
- If handling menu close events proves to be too difficult, this story would become mostly trivial from an engineering perspective if it were descoped to only clear highlights on option select.  Check with @apbitner if that's acceptable.

**Comment by Baron-Severin** [comment]
@vesta0 this seems important to me, are you ok with us pulling this in?  And to which board?

**Comment by Baron-Severin** [comment]
This partial implementation achieves the easier requirements described above (only clear on menu item clicked).  We can build on top of it when we hear back about how to respond to menu close events.

https://github.com/mozilla-mobile/fenix/pull/8805

**Comment by apbitner** [comment]
I don't think it would be a great experience for our users to force them to open reader view, open in app, or install a PWA simply to get the blue dot to go away. Hopefully we can get it to work on menu close, or find another event besides the user tapping on the menu item.

**Comment by Baron-Severin** [comment]
Whoops!  I misunderstood https://github.com/mozilla-mobile/fenix/issues/7408, this one didn't need to be spun out at all.  Closing as a dup of it.
