### ISSUE TITLE
[Bug] Tab's aren't sent/received when shared with another device

### ISSUE THREAD

**Issue by x2k13** [mozilla-mobile/fenix#8806]
## Steps to reproduce
Share tabs with another synced device.
### Expected behavior
Tabs are sent to the chosen device
### Actual behavior
Tabs aren't sent/received at all.
### Device information
Samsung Galaxy Tab A 10.5 LTE, Android Pie <-> Motorola Moto X Play, Android Nougat
* Android device: ✔
* Fenix version: latest, updated today: 200226

**Comment by sflorean** [comment]
@x2k13 is this still the case for you?
Tested on Nightly 7/20 and couldn't reproduce the issue.

**Comment by x2k13** [comment]
> @x2k13 is this still the case for you?
> Tested on Nightly 7/20 and couldn't reproduce the issue.

Yes it's working again. I'll close this issue. Thanks.
