### ISSUE TITLE
Make collections and contents sortable/drag 'n drop-able

### ISSUE THREAD

**Issue by x2k13** [mozilla-mobile/fenix#8807]
### Why/User Benefit/User Problem
Collections and their contents are sorted on a "added last" basis, making them sortable by different criteria would add a better handling of collections.
### What/Requirements
Add a function to sort collections and their contents, preferably making collections and their contents drag 'n drop-able (like Vivaldi or Opera already have it).
### Acceptance Criteria (how do I know when I’m done?)
When we can sort/drag'n drop collections and their contents freely.

**Comment by cadeyrn** [comment]
Duplicate of #8141.
