### ISSUE TITLE
[Bug]Navigation issues in Ublock Settings

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#8808]
## Prerequisites
Have Ublock Origins installed.

## Steps to reproduce
1. Open uBlock's settings
2. Tap on one of the 🛈 icon
3. Tap the back button 

### Expected behavior
The user should be redirected to uBlock's settings.

### Actual behavior
The user is redirected to uBlock's options screen.

### Device information

* Android device: • OnePlus A3 (Android 6.0.1)
* Fenix version: 4.0.0-beta.2

### Notes
❗ Not reproducible on the latest Nightly Build #20580605 from 2/27

► Video from Fenix 4.0.0-beta.2
![20200227-101204](https://user-images.githubusercontent.com/51314259/75425253-00428480-594b-11ea-9711-d7d6ebb3fccf.gif)

► Video from  Nightly Build #20580605
![20200227-101247](https://user-images.githubusercontent.com/51314259/75425304-1d775300-594b-11ea-9654-ba02b36d1fb4.gif)

**Comment by csadilek** [comment]
See https://github.com/mozilla-mobile/fenix/issues/9139#issuecomment-600113368

**Comment by csadilek** [comment]
@AndiAJ see comments in https://github.com/mozilla-mobile/fenix/issues/9139. This can be verified now as settings page is a tab and navigation should work. Thanks!

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly Build #20780606 from 3/18`** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S6 (Android 7)
• OnePlus A3 (Android 6.0.1)

► Video
![20200318-092533](https://user-images.githubusercontent.com/51314259/76936201-2d0b0b80-68fb-11ea-8e96-8ea7500861ab.gif)
