### ISSUE TITLE
[Bug] Navigation bar and/or top bar is white in PWA

### ISSUE THREAD

**Issue by FunctionalHacker** [mozilla-mobile/fenix#8812]
Right now, all PWA's have white top and/or bottom bars. This is the most apparent in Twitter:

![](https://i.imgur.com/UPdknLk.png)

My Gitea instance seems to set the top bar to green but the navigation bar is still white:
![](https://i.imgur.com/BHsra1O.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-16028)

**Comment by serovar** [comment]
Any news on this?

**Comment by NotWoods** [comment]
Currently we match the background color defined by the PWAs for the navigation bar. Both of these sites have a light background color in the installed PWA data, but change their appearance in dark mode. We may want to revisit this behaviour or find a way to track the background color dynamically.

**Comment by hakkikaancaliskan** [comment]
Status bar becomes completely white on dark mode with pwa
![Screenshot_20210119-212638_Firefox_Nightly](https://user-images.githubusercontent.com/17825767/105077248-480b5680-5a9d-11eb-954f-36f47def2878.png)
1/18 nightly, Xperia XZ1 Android 11

**Comment by astarq** [comment]
Any update on this?

**Comment by coxde** [comment]
Any updates?

**Comment by nyex** [comment]
![Screenshot_20211108-091351](https://user-images.githubusercontent.com/15344684/140740262-d382f82c-4d18-4583-ba9d-a7142ee2b5da.png)

Mobile Firefox 94.1.1 with dark theme (feedbin in theory follows the browser's theme but apparently that says nothing about the top bar)

Android 10 with dark theme.

I haven't found any PWA that actually sets the top bar in a way I can actually read its contents.

**Comment by AshenColors** [comment]
Still an issue in 98.1.1 (Build #2015866891). This prevents the use of the notification bar and Fenix PWA at the same time. I would definitely call this a bug--rather than something that would be "nice to have", it silently breaks for unclear reasons and leaves the user on the hook without any functional way to put a shortcut of a webpage on the home screen.

**Comment by math-GH** [comment]
Something changed. See: https://github.com/FreshRSS/FreshRSS/pull/4254#issuecomment-1082324547

**Comment by plwt** [comment]
User feedback: https://support.mozilla.org/en-US/questions/1381647

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807092

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
