### ISSUE TITLE
[Bug] There is no feedback response while tapping the uBlock dashboards option buttons

### ISSUE THREAD

**Issue by DanielOrban** [mozilla-mobile/fenix#8813]
## Prerequisites
- uBlock Origin is installed and enabled in Fenix
## Steps to reproduce
1. Navigate to a website with ads (eg. www.bbc.com).
2. Tap on the three-dot menu and tap on the uBlock Origin's icon.
3. Tap on any of the uBlock dashboards option buttons (eg. "element zapper", "element picker", "logger", "dashboard").
### Expected behavior
There is a feedback response that the button is tapped.
### Actual behavior
There is no feedback response that the button was tapped.
### Device information
* Android device: 
-Samsung Galaxy S7 (Android 8.0.0)
-Samsung Galaxy S7 Edge (Android 8.0.0)
* Fenix version:
-Beta 74.0.0-beta.2 (Build #20581013)

![There is no feedback response while tapping the uBlock dashboards option buttons](https://user-images.githubusercontent.com/43445968/75444974-2842df80-596d-11ea-880b-bbbf321c7dee.gif)

**Comment by psymoon** [comment]
@DanielOrban when you say feedback, do you mean like native android UI button feedback? Options-UI is an extension webpage, over which we have no control.

**Comment by DanielOrban** [comment]
@psymoon I was referring to the usage of a highlight so that users know if the option was selected and is now active. Maybe change the color of the button when the option is active. Something like this:

![20200228_093639](https://user-images.githubusercontent.com/43445968/75520337-00f01f00-5a0e-11ea-82c4-87e0491b1c7d.gif)

Since you don't have any control over the Options-UI Webpage, could you relay the suggestion to the add-on developers?

**Comment by csadilek** [comment]
Thanks @DanielOrban.

@kewisch @brampitoyo this is another UX issue which would need to be addressed in the add-on. Can you add this to the list?

Closing as not actionable by us.
