### ISSUE TITLE
Send collection to Pocket

### ISSUE THREAD

**Issue by madb1lly** [mozilla-mobile/fenix#8815]
### Why/User Benefit/User Problem
I frequently gather up collections of tabs which I want to read (they are articles, not websites to explore) and I realise that the best place for these is actually a read-it-later service, like Pocket. I tried to send a collection of tabs to Pocket but only one was added to Pocket, so it appears that I can only add tabs to Pocket one at a time, which is extremely laborious. 

### What/Requirements
When Sharing a collection to the Pocket app send each link in the collection, _or_ update Pocket to accept collections (I think the former solution is simpler, but I could be wrong).

### Acceptance Criteria (how do I know when I’m done?)
When I share a collection to the Pocket app, the Pocket app receives all of the links in the collection.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-16031)

**Comment by madb1lly** [comment]
Hi @eliserichards,
This is not necessarily direct Pocket integration, but that may be a solution. Alternatively if Pocket could accept a set of URLs rather than just one URL at a time then that could be a solution too.
Cheers 🙂

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807377

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
