### ISSUE TITLE
[Bug] Migration from Fennec Nightly lost custom about:config settings

### ISSUE THREAD

**Issue by madb1lly** [mozilla-mobile/fenix#8817]
## Steps to reproduce
Update Fennec Nightly to Fenix Nightly via the Play Store, when the migration build is available.

### Expected behavior
I was expecting some of my custom about:config settings to remain in place, e.g. referrer policy, first party isolation.

### Actual behavior
These settings were lost, I had to reenable them in about:config.

### Device information

* Android device: 9
* Fenix version: I can't remember the build at the time I upgraded.

**Comment by kbrosnan** [comment]
This is expected behavior. We are not making any modifications to the migration code.
