### ISSUE TITLE
[Bug] Accesibility-Extra element displayed on the page when font size for website is increased

### ISSUE THREAD

**Issue by Diana-Rus** [mozilla-mobile/fenix#8822]
Prerequisites:
- Have in "Settings"/"Accessibility"/"Automatic Font Sizing" disabled 
- Have "Font Size" size set to 105%

## Steps to reproduce
1. Go to amazon.com.
### Expected behavior
All the elements form the page are correctly displayed.
### Actual behavior
In the top right corner there is an extra gray box.
### Device information

* Android device: Google Pixel XL (Android 10), Google Pixel 3 XL (Android 9), Samsung Galaxy S9 (Android 8.0.0), Nexus 9 (Android 7.1.1)
* Fenix version: Firefox Preview Beta 4.0.0-beta.2 (Build #20581012), GV: 74.0-20200226031638

Notes:
- 100% screenshot
![Screenshot_20200227-154432](https://user-images.githubusercontent.com/49859863/75453125-187ec780-597c-11ea-9857-9f94996f62e0.png)

- 105% screenshot
![Screenshot_20200227-161106](https://user-images.githubusercontent.com/49859863/75453158-23395c80-597c-11ea-8fd6-59aa322f0d47.png)

- I haven't encountered an extra element with other pages.
- Nothing happens when the gray box is tapped.
- It's the same in both portrait and landscape mode.

**Comment by mcarare** [comment]
Similar to : https://github.com/mozilla-mobile/fenix/issues/4025  + the font size aspect.
