### ISSUE TITLE
Asynchronously inflate toolbar from within BrowserToolbarView

### ISSUE THREAD

**Issue by emalysz** [mozilla-mobile/fenix#8826]
Let's see if we can asynchronously inflate the toolbar to improve the performance BaseBrowserFragment.initializeUI. 

This seems like it could be a win for app link, and a breakdown of the time spent in this function can be found at https://github.com/mozilla-mobile/fenix/issues/8061#issuecomment-590584913

**Comment by mcomella** [comment]
@emalysz What's this waiting on again?

**Comment by emalysz** [comment]
@mcomella we were waiting to see if the perceived performance is worth the change cc @ecsmyth

**Comment by ecsmyth** [comment]
Still in a holding pattern. I'll hopefully have another update this week.

**Comment by ecsmyth** [comment]
[UR request filed](https://bugzilla.mozilla.org/show_bug.cgi?id=1633404). Waiting on triage.

**Comment by ecsmyth** [comment]
UR will not be able to study before the end of June. Assigning to UX for guidance.

**Comment by brampitoyo** [comment]
Have just caught up with @ecsmyth, and focusing particularly on this observation:

> The change, when measured locally with a simple test site, improves Fenix startup by roughly 270 milliseconds (i.e. a 25% improvement) […] However, to me, the original experience feels better, faster, possibly as a result of the animations that give a sense of progress.

Combining the fact that:

- Objective performance is measurably higher, but isn’t guaranteed to translate to subjective perceived performance (ie. time until users perceive Fenix as “finished loading” and take their first action within the app)
- Asynchronously inflated toolbar would’ve excised Android’s default app opening animation, which would’ve made Fenix go against system convention.

I think that we shouldn’t go ahead with this change.

We may still be able to do some things that could increase perceive performance around loading time. For example:

- Use transition time to pre-load UI elements and page content, so everything on the page can be shown all at once
- Shorten animation and duration scale (maybe scale to 0.5x?) so transitions look and feel faster

**Comment by mcomella** [comment]
> I think that we shouldn’t go ahead with this change.

@brampitoyo @ecsmyth Shall we close this issue then? Thanks for looking into it.

**Comment by mcomella** [comment]
Triage: we have no time to pass this through UR now so we'll move to low impact.

**Comment by mcomella** [comment]
I'm going to close this issue and link it from our "perceived performance" ticket https://jira.mozilla.com/browse/FXP-1264 on JIRA, given it seems unactionable and will likely continue to be so for a while.
