### ISSUE TITLE
Call shouldShowTrackingProtectionOnboarding after visual completeness

### ISSUE THREAD

**Issue by emalysz** [mozilla-mobile/fenix#8827]
shouldShowTrackingProtectionOnboarding is called multiple times during app link starts. It can even stall the loading of a page to check.

The method itself does not take a long time (~1.75-2ms on a Pixel2 performance build). However, I have seen it been called upwards of 4 times before the page is fully loaded and `TrackingProtectionOverlay.showTrackingProtectionOnboarding` is called. 

Let's see if we can reduce that to one check after the page has been loaded.

**Comment by mcomella** [comment]
Closing: we're addressing startup holistically.
