### ISSUE TITLE
Syncing between firefox preview (android) and firefox for osx (non-preview) doesn't work any more

### ISSUE THREAD

**Issue by avshyz** [mozilla-mobile/fenix#8831]
## Steps to reproduce
Open firefox preview, and firefox desktop for osx.
Register both devices.
Try to sync tab
### Expected behavior
For fenix' tabs to be shown on the desktop's shared tabs section.
### Actual behavior
It isn't shown.

I've tried to push tabs manually between devices - it did work.

It's worth mentioning that the sync used to work, and in fact, when I began this process I did manage to see fenix' tabs on the synced tabs section on my desktop but they weren't being updated no matter what I've tried.
### Device information
latest firefox preview (Build #2015722947) on Mi A2 (Android 10)
firefox 73.0.1 (64-bit) for osx

**Comment by avshyz** [comment]
Hi, it has been quite a while. Any update?

**Comment by softvision-miralobontiu** [comment]
@avshyz is this issue still reproducible for you?
Thanks!
