### ISSUE TITLE
Intermittent UI test failure - ContextMenusTest.verifyContextCopyLink

### ISSUE THREAD

**Issue by AaronMT** [mozilla-mobile/fenix#8832]
https://console.firebase.google.com/u/1/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6747611920893670992/executions/bs.467922f96259f08f/testcases/1/test-cases

> androidx.test.espresso.base.DefaultFailureHandler$AssertionFailedWithCauseError: 'with text: a string containing "http://localhost:36719/pages/generic3.html"' doesn't match the selected view.
Expected: with text: a string containing "http://localhost:36719/pages/generic3.html"
Got: "TextView{id=2131296964, res-name=mozac_browser_toolbar_url_view, visibility=VISIBLE, width=604, height=110, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=true, is-enabled=true, is-focused=false, is-focusable=true, is-layout-requested=false, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@9ae8c3f, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, text=http://localhost:36719/pages/generic4.html, hint=Search or enter address, input-type=0, ime-target=false, has-links=false}"

**Comment by rpappalax** [comment]
@sv-ohorvath @AaronMT  ran 50x, no longer failing. can be re-enabled

**Comment by AaronMT** [comment]
This is re-enabled.

**Comment by kbrosnan** [comment]
Failed once https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6730880792172924720/executions/bs.6bba384065e27dd0/testcases/2/test-cases

**Comment by AndiAJ** [comment]
See #18421
