### ISSUE TITLE
rearrange/change menu items to reduce clutter

### ISSUE THREAD

**Issue by Shaurya-Kalia** [mozilla-mobile/fenix#8834]
### Why/User Benefit/User Problem
With reader view being added to firefox menu, the menu has finally taken up my entire screen in 1920*1080 resolution (also have quit button) and will require scrolling with addons enabled. So thought maybe it was time to remove some reduntant items and rearrange the rest for better consistency and usability

### What/Requirements

1. Removal of new tab and private tab. There is a dedicated screen to see tabs. New tabs and private tabs can be opened from that screen. Both methods require 2 clicks. Both these options can be removed from menu.

2. First button is reader view followed by quit button when toolbar is on top. Idk its by habit, but seeing a quit button at top is very jarring. Instinctively, it feels it should be the last entry in menu, or atleast farthest from where the finger is after invoking the menu.

3. Actions involving site such as reader view, desktop view should be first, and there should be consistency in arrangement of items, with items of similar function together.

4. As someone who had many addons in fennec, i can confirm that the menu becomes very long when a bunch of them are enabled. Two solutions could be: 
      A) all addons be put into a category called addons in the menu, and all extensions be listed on clicking there (preferrably as sub menu). Clicking on an extension from that screen shows the extension specific action (like the ublock dashboard). Addon management be further accessible from that submenu as the top most entry.
      B) A seperate menu for extensions like the overflow menu in firefox desktop

5)A possible arrangement, assuming toolbar on top, could be:
  The 4 buttons(back, bookmark, share, reload)
  Reader view
  Desktop view
  Find in page
  Add to collections
  Add to top sites
  Install
  Library
  Addons*
  Settings
  Help
  Report site issue
  Quit

6) the reverse arrangement as given above, when toolbar is at bottom

### Acceptance Criteria (how do I know when I’m done?)
Menu is concise, systematically arranged and places most common actions to the user. New items when added should also be sanely placed accounting for the existing placement

**Comment by topotropic** [comment]
Thanks for your feedback. It will be addressed with https://github.com/mozilla-mobile/fenix/issues/8474 and https://github.com/mozilla-mobile/fenix/issues/8319. I'll close this issue.
