### ISSUE TITLE
[Bug] Awesomebar results hidden by keyboard 

### ISSUE THREAD

**Issue by tdaede** [mozilla-mobile/fenix#8837]
## Steps to reproduce
Use a phone with a sufficiently small screen or large keyboard. 
### Expected behavior
Awesomebar results appear and are tappable
### Actual behavior
![Screenshot_20200215-124355](https://user-images.githubusercontent.com/1308314/75489946-127eeb80-5968-11ea-8a58-e02dfae73a61.png)

Dismissing the keyboard makes all the results disappear. However dragging the list dismisses the keyboard in a way that it doesn't dissappear and reveals the results I want:
![Screenshot_20200215-124520](https://user-images.githubusercontent.com/1308314/75490084-540f9680-5968-11ea-8f08-6635824cde0d.png)

### Device information

* Android device: Xperia X Compact
* Fenix version: Nightly

**Comment by kbrosnan** [comment]
Dupe #1161
