### ISSUE TITLE
Odd Left Margin in Search Hairline

### ISSUE THREAD

**Issue by darkwing** [mozilla-mobile/fenix#8840]
## Steps to reproduce

Look at the search screen

### Expected behavior

Top grey hairline touches left side of the screen

### Actual behavior

Top grey hairline has a slight left margin

### Device information

* Android device: Pixel 4
* Fenix version: ?

![Screenshot_20200227-232848](https://user-images.githubusercontent.com/46655/75496796-ed01da00-5987-11ea-80fd-bfaa5008987d.png)

**Comment by ekager** [comment]
Looking at the abstract it looks like this is intentional?
https://share.goabstract.com/0d0a076c-1271-4832-9f91-92a64331afcf?mode=design&sha=39d561f9b4931571f0296bfb4bd5c44ffc77daef

@topotropic could you confirm? :)

**Comment by topotropic** [comment]
Yes, it's intentional. 

Looking at it, it's 8dp but should be 16dp – I'll create a follow up issue. Other things seem a little off here as well.
