### ISSUE TITLE
[Bug] Address not found page text doesn't show without JavaScript

### ISSUE THREAD

**Issue by danielzgtg** [mozilla-mobile/fenix#8843]
## Steps to reproduce

1. Navigate to `about:config`
2. Toggle `javascript.enabled` to `false`
3. Navigate to `http://nonexistentabcabcabc.com/`

### Expected behavior

![Screenshot_20200227-205222](https://user-images.githubusercontent.com/25646384/75503626-1fb9cb80-59a4-11ea-81f5-40e179e55ddf.jpg)

### Actual behavior

![Screenshot_20200227-205213](https://user-images.githubusercontent.com/25646384/75503631-247e7f80-59a4-11ea-8755-6e990a9d53b2.jpg)

### Device information

* Android device: OnePlus 7 Pro
* Fenix version: Nightly 200227 18:01

**Comment by AndiAJ** [comment]
Reproducible on the latest Nightly Build 201103 using the following devices:
• Google Pixel 3a (Android 11)
• Huawei Mate 20 Lite (Android 10)
• OnePlus A3 (Android 6.0.1)
