### ISSUE TITLE
Readd ability to force reader mode

### ISSUE THREAD

**Issue by danielzgtg** [mozilla-mobile/fenix#8844]
### Why/User Benefit/User Problem

Many sites, especially news sites, like to invade your privacy. They hold the article hostage behind a paywall when I disable cookies, disable JavaScript, or use private browsing.

Back in fennec, I used `about:reader` to solve this problem, but I can't anymore with fenix `Nightly 200227 18:01`.

### What/Requirements

Any of the following:

1. Implement `about:reader` (#5190). This issue is separate from that one because that issue suggest removing `about:reader` while it doesn't matter how this issue is implemented
2. Add an `about:config` setting. It would be like `reader.parse-on-load.force-enabled` except it would make the reader mode item in the overflow menu show all the time
3. Support 3rd party extensions that provide this feature. The [first search result](https://addons.mozilla.org/en-CA/firefox/addon/activate-reader-view/) isn't currently compatible with fenix

### Acceptance Criteria (how do I know when I’m done?)

Reader mode can be used on any site.

The reader mode item in the overflow menu should keep behaving how it currently is and continue to be hidden when no article is detected (unless forced in `about:config`).

**Comment by kbrosnan** [comment]
If a main section was not able to be found then forcing reader view won't help. If you have specific pages where reader mode fails to be offered then opening an [issue with the readability project](https://github.com/mozilla/readability/issues) is the way forward.

**Comment by danielzgtg** [comment]
@kbrosnan When the page loads, the main section DOES get found. However, JavaScript immediately deletes it and replaces it with a paywall. I was using reader mode as a way to quickly block JavaScript for a specific page and have the article easily readable at the same time.

**Comment by danielzgtg** [comment]
Actually, now I agree forcing reader mode isn't the root of the problem. I just realized Firefox's tracking protection is supposed to do what I wanted and the bug is there instead. However, having forceable reader mode would have be a nice fallback when the tracking protection doesn't work.
