### ISSUE TITLE
Suggested names for collections should be based on creation order

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#8848]
## Steps to reproduce
1. Create a New Collection and name it "A"
2. Create a New Collection and use the default suggested title
3. Create a New Collection and name it "B"
4. Create a New Collection and use the default suggested title

### Expected behavior
Fenix should suggest the following default titles:
for step 2 - "Collection 2"
for step 4 - "Collection 4"

### Actual behavior
Fenix  suggests the following default titles:
for step 2 - "Collection 1"
for step 4 - "Collection 2"

### Device information

* Android device: 
•  Google Pixel 3a (Android 9)
•  OnePlus A3 (Android 6.0.1)

* Fenix version: 
• Fenix 4.0.0-beta.2
• Nightly Build #20590607 from 2/28

### Notes
► Video from Nightly Build #20590607
![20200228-111615](https://user-images.githubusercontent.com/51314259/75529998-4fa4b580-5a1c-11ea-8724-941ef0dc0134.gif)

Related issue [#6330](https://github.com/mozilla-mobile/fenix/issues/6330)

@BranescuMihai & @brampitoyo  - Please review and share your thoughts. ☺️

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-16049)

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812755

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
