### ISSUE TITLE
[Bug][L10N] The "Cookies" word is not translated in Traditional and Simplified Chinese

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/fenix#8849]
## Steps to reproduce
1. Change the device language to Traditional or Simplified Chinese.
2. Launch Fenix and access settings.
3. Access the ETP menu, tap on Custom and observe the cookies menu.
### Expected behavior
The `Cookies` word should be translated in Traditional and Simplified Chinese.
### Actual behavior
 The "Cookie" word is not translated in Traditional and Simplified Chinese
### Device information

* Android device: **Google Pixel 3 (Android 9)**
* Fenix version: **Nightly 2/28 and Beta 4.0.0.beta.2**

![Screenshot_20200228-122153](https://user-images.githubusercontent.com/42831109/75541106-ffcaec00-5a25-11ea-8952-d118a90dcb46.png)

**Comment by danielzgtg** [comment]
What do you suggest to translate it to?

It is left as-is as "Cookie" by:
- fennec
- Firefox Quantum
- Chrome Desktop
- Chrome Android
- [Google Translate](https://translate.google.ca/#view=home&op=translate&sl=en&tl=zh-CN&text=browser%20cookie)
- [MDN](https://developer.mozilla.org/zh-CN/docs/Web/HTTP/Cookies)

**Comment by ekager** [comment]
Closing because this sounds like expected translation :)
