### ISSUE TITLE
[Bug] "All third-party and all cookies" options from ETP(cookies) menu are not fully displayed in other languages than English

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/fenix#8853]
## Steps to reproduce
1. Change the language to any of the following(German, Spanish, French, Italian, Swedish, Russian, Korean, Japanese)
2. On the cookies menu from ETP, select `All third-party cookies(may cause websites to break)`.

### Expected behavior
The text from the `All third-party cookies(may cause websites to break) or All cookies(will cause websites to break)` should be fully displayed on the menu frame.
### Actual behavior
 `All third-party cookies(may cause websites to break) or All cookies(will cause websites to break)` options from ETP(cookies) menu are not fully displayed as the menu frame is too small in other languages than English.
### Device information

* Android device: **Google Pixel 3 (Android 9)**
* Fenix version: **Nightly 2/28 and Beta 4.0.0.beta.2**

### Notes
There is a small `scroll` bar but it doesn't have functionality.
For the Traditional and Simplified Chinese, this issue doesn't occur but it's maybe because of the https://github.com/mozilla-mobile/fenix/issues/8849 as the `cookies` word is not translated.

![20200228-140924](https://user-images.githubusercontent.com/42831109/75548098-1298ed00-5a35-11ea-9e24-d7f446e64407.gif)

**Comment by Diana-Rus** [comment]
Hi, reproducible with Google Pixel 3 XL (Android 9) on Beta 4.3.0-beta.1.

**Comment by Diana-Rus** [comment]
Hi, reproducible with Google Pixel 3 XL (Android 9) on Beta 5.1.0-beta.3.
