### ISSUE TITLE
[Bug]The tab drawer number is not centered when open Top Sites pages

### ISSUE THREAD

**Issue by sv-sdeiac** [mozilla-mobile/fenix#8859]
## Steps to reproduce
1. Open the Homepage of the app;
2. Tap on a Top Site page;
3. Observe the tab drawer number.

### Expected behavior
The number is displayed without any issue.

### Actual behavior
The number is not centered.

### Device information

* Android device: Samsung Galaxy Note 8 (Android 9).
* Fenix version: Firefox Preview Nightly 2/28 #20590606.
![20200228_165903](https://user-images.githubusercontent.com/40264165/75559223-c0af9180-5a4b-11ea-91d1-4a3e7028820e.gif)

**Comment by darkwing** [comment]
We should revisit this when @gabrielluong has https://github.com/mozilla-mobile/fenix/issues/8791 ready.

**Comment by sblatz** [comment]
This is a pretty annoying visual bug and is not isolated to top sites.

**Comment by cadeyrn** [comment]
related: #8859.

**Comment by sv-sdeiac** [comment]
Verified as fixed using the latest version of Firefox Preview Nightly 3/3 @20630607).

Devices:
- Nokia 6 (Android 7.1.1);
- Samsung Galaxy Note 8 (Android 9);
- Google Pixel (Android Q).

**Comment by AndiAJ** [comment]
Reproducible on **`Beta 4.0.0-beta.3`** using a OnePlus A3 (Android 6.0.1)
► Screenshot
![rsz_screenshot_20200304-122217](https://user-images.githubusercontent.com/51314259/75870790-32088f00-5e14-11ea-85a0-063fdbdf2f0b.png)
