### ISSUE TITLE
[Meta] Site permissions

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/fenix#886]
As a user, I want to be able to configure and control site permissions, so I can have control over witch sites can access my information. 

Site permission flows: https://whimsical.co/QXGiB45gjs1iniprdrWdBG

### Dependencies:

UX designs: 
#188 

A-C breakdown: https://github.com/orgs/mozilla-mobile/projects/8

**Comment by mheubusch** [comment]
Engineering - please review the items on this spreadsheet - this is a punchlist showing fit and finish issues blocking feature completeness.

https://docs.google.com/spreadsheets/d/1EzH-orBzD0Kshizl-Ph34hrbtKlVdSiXhwvvQ_YI0L0/edit?usp=sharing
