### ISSUE TITLE
Instrument window.onLoad or DOMContentLoaded for short term app link measurement

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#8865]
FNPRMS time to first frame drawn is not represented so we need a better solution. acreskey suggested `window.onLoad` and `DOMContentLoaded` (preferred) as two possible points of comparison between the two browsers that will get us what we want.

There are two approaches:
- Instrument one of these events with `reportFullyDrawn` in both browsers; don't change FNPRMS
- Find existing logs (i.e. straight to logcat), or add your own, for one of these events; change FNPRMS to accommodate them

### Acceptance criteria
- Get instrumentation for one of these events in Fennec & Fenix
- Sync with Benjamin & Marc so they can update FNPRMS if necessary

**Comment by acreskeyMoz** [comment]
I don't see DomContentLoaded in the logs so 

For Fennec, the pageload stop will follow the load event and can be identified as:
`02-28 14:17:27.763 20465 20465 I GeckoTabs: zerdatime 857122194 - page load stop`

**Comment by acreskeyMoz** [comment]
For Fenix, I think the best logged end point is
```
02-28 14:04:25.634 18819 18819 D GeckoSession: handleMessage GeckoView:PageStop uri=null
that follows after GeckoView:PageStart uri=https://www.mozilla.org/en-US/
```

**Comment by mcomella** [comment]
I finished my patch series, currently under review by jimporter & smoke test by marcleclair: https://github.com/mozilla-mobile/FNPRMS/pull/11

**Comment by mcomella** [comment]
We instrumented PageStop for both on example.com and landed a bug fix in https://github.com/mozilla-mobile/FNPRMS/pull/12. I think this should be good to close now.
