### ISSUE TITLE
[Bug] Fenix does not remember when Tracking Protection is disabled

### ISSUE THREAD

**Issue by agi90** [mozilla-mobile/fenix#8868]
## Steps to reproduce
* Navigate to www.chase.com
* Disable tracking protection by clicking on the shield in the URL bar
* open a new tab and load www.chase.com

### Expected behavior
* Tracking protection is still disabled

### Actual behavior
* Tracking protection is enabled

### Device information

* Android device: Samsung S10e, Android 10
* Fenix version: Latest Fenix Nightly from playstore

**Comment by kbrosnan** [comment]
Going into the settings for tracking protection does not show Chase as being whitelisted.

**Comment by Baron-Severin** [comment]
What versions are you on @kbrosnan @agi90?  This is working for me on 200227.  I wonder if this might have been recently fixed as a side effect of https://github.com/mozilla-mobile/fenix/issues/8565?

<img src="https://user-images.githubusercontent.com/13170306/75588632-eaf25680-5a2d-11ea-8f64-a206b9e19da9.gif" width="350">

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Fenix Nightly Build 200713 from 7/13`** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)

► Video
![20200713-121640](https://user-images.githubusercontent.com/51314259/87287850-4582df80-c503-11ea-91a3-c934dcee963c.gif)
