### ISSUE TITLE
[Bug] On cold start, on search bar access, it's possible to get an entirely empty search fragment screen

### ISSUE THREAD

**Issue by AaronMT** [mozilla-mobile/fenix#8869]
https://console.firebase.google.com/u/1/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/5530136788603940548/executions/bs.232688d8091722da/videos

![Screen Shot 2020-02-28 at 3 12 17 PM](https://user-images.githubusercontent.com/102331/75583991-bdf97000-5a3c-11ea-9561-73323f2e5b85.png)

Pixel 2 28 (AVD)
Nexus 6 25 (AVD) 

Both devices accessing the search fragment screen on cold start, and seeing an entirely empty screen with no engine listing.

Ran against 0411233fc3203a5d3b924d0460b0b5721405df2f GeckoNightlyDebug

**Comment by AaronMT** [comment]
First occurrence from https://github.com/mozilla-mobile/fenix/pull/8866 so it might be fallout from that. Filed just in-case.

**Comment by abodea** [comment]
I tried to reproduce this issue but with not so much success using the latest Nightly from 3/17 with Google pixel 4 XL (Android 10)
Samsung Galaxy S7 (Android 7)
Note that I opened at least 100 tabs from the search widget.
@AaronMT is there something more that I can try to reproduce this issue?

**Comment by abodea** [comment]
Verified as fixed based on the comment from above.
I will also, remove the `needs:STR` label.
