### ISSUE TITLE
[Meta] Site Permissions Custom Settings

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/fenix#887]
### Why/User Benefit/User Problem
As a user, I want to see my custom site permissions and the given value of each one.

### Acceptance Criteria (how do I know when I’m done?)
-I can see a List all the permissions
-I can see the the value I have selected for each permission type.

![image](https://user-images.githubusercontent.com/773158/53929097-96a2d980-405a-11e9-9a3c-b28d6e9d249c.png)

**Comment by sv-ohorvath** [comment]
Verified the acceptance criteria. Marked as fixed.
devices: Huawei P20 lite (Android 8), Nexus 5 (Android 6), Galaxy Tab 3 (Android 8).
logged related bug: 1414
