### ISSUE TITLE
[Bug] "Your library" text is indented too much in the three dot menu

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#8870]
The "Your Library" text is indented too much in the browser menu. I think this will require changing the `BrowserMenuImageText` in AC.

<img width="350" alt="image" src="https://user-images.githubusercontent.com/4400286/75585355-c050cf80-5a26-11ea-9e41-d37c3a04aafe.png">

**Comment by mcarare** [comment]
AC Issue: https://github.com/mozilla-mobile/android-components/issues/6137

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly Build #20630607 from 03/03`** using the following devices:
• Google Pixel 3a (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

► Comparison Nightly from 03/02  VS  Nightly from 03/03
![lib](https://user-images.githubusercontent.com/51314259/75783722-af2afa00-5d69-11ea-8ead-703901a687a5.png)
