### ISSUE TITLE
[Topsites] Added to top sites snackbar appears too high on the screen

### ISSUE THREAD

**Issue by AmyYLee** [mozilla-mobile/fenix#8873]
Hi, the snackbar should be located just above the search bar like our other snackbar notifications.

![image](https://user-images.githubusercontent.com/5992746/75593936-edb47200-5a54-11ea-83fd-f29303fd87ae.png)

**Comment by cadeyrn** [comment]
looks like #8773.

**Comment by sv-sdeiac** [comment]
This issue is still reproducible after verifying #8773. 
Devices: 
- Samsung Galaxy Note 8(Android 9);
- Motorola Moto G6 (Android 8).

**Comment by sv-sdeiac** [comment]
Verified as fixed using the latest version of Firefox Preview Nightly 3/3  (#20630607).

Devices:
- Google Pixel (Android Q);
- Samsung Galaxy Note 8 (Android 9).
