### ISSUE TITLE
[Homescreen] Delete tab colours need updating

### ISSUE THREAD

**Issue by AmyYLee** [mozilla-mobile/fenix#8874]
I will provide correct colours here

![image](https://user-images.githubusercontent.com/5992746/75594051-63b8d900-5a55-11ea-8dab-f23a8f71c706.png)

**Comment by AmyYLee** [comment]
I've attached the correct colours. Thanks
<img width="845" alt="Screen Shot 2020-03-03 at 1 47 57 PM" src="https://user-images.githubusercontent.com/5992746/75808891-d11a8180-5d55-11ea-818b-997969559bb0.png">

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **Nightly Build #20690607 from 03/09** using the following devices:
• Google Pixel 3a (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

►Video
![20200309-084456](https://user-images.githubusercontent.com/51314259/76189359-24238700-61e3-11ea-94dc-deb9128d7f3d.gif)
