### ISSUE TITLE
UI element hang forever. memory leak?

### ISSUE THREAD

**Issue by oshanz** [mozilla-mobile/fenix#8876]
## Steps to reproduce
1. go to azure pricing calculator page
https://azure.microsoft.com/en-us/pricing/calculator/#virtual-machines

2. select any drop down. but don't select any option
![Screenshot_20200229-111049](https://user-images.githubusercontent.com/5364479/75602873-3456aa80-5aef-11ea-944f-bd8fc6b22a4d.png)

3. now click the address bar and just goto a any other page. 
and you can see the drop down is appearing again.
![Screenshot_20200229-122040](https://user-images.githubusercontent.com/5364479/75602889-6a942a00-5aef-11ea-9c77-4dfa96d9972f.png)

4. you can click background to hide this UI temporary.
but don't select any option.
![Screenshot_20200229-122100](https://user-images.githubusercontent.com/5364479/75603089-3d487b80-5af1-11ea-89bf-c0407b41b17a.png)

5. repeat the no:3, just move to anypage, that UI element is appearing again
![Screenshot_20200229-111422](https://user-images.githubusercontent.com/5364479/75603031-a8458280-5af0-11ea-8b3d-b72393cd1ee4.png)

### Expected behavior
UI elements should not be shared between web pages.
this can be a security issue and or a memory leak.

### Actual behavior
element hang forever until you select an option of close the tab.

### Device information

* Android device: 7.1.1
* Fenix version: 3.2.0

**Comment by ekager** [comment]
I believe this is a dupe of #7902 and is now resolved in master/nightly. Please reopen if you think this is incorrect.
