### ISSUE TITLE
[Bug] Respect `toolkit.cosmeticAnimations.enabled`

### ISSUE THREAD

**Issue by johnp** [mozilla-mobile/fenix#8877]
## Steps to reproduce

Set the `toolkit.cosmeticAnimations.enabled` pref to `false` like on desktop.

### Expected behavior

No cosmetic animations on tab switching.

### Actual behavior

Cosmetic (transition) animations are shown.

### Device information

* Android device: Mi 9T Pro (Android 10)
* Fenix version: Nightly 200229

**Comment by kbrosnan** [comment]
`about:config` is not going to be the place to set this. The OS settings are what should be respected here, #3597 tracks that.
