### ISSUE TITLE
[Meta] Site Permissions Recommended Settings

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/fenix#888]
### Why/User Benefit/User Problem
As a user, I want to see how my default permissions when "Use recommended settings" option is selected

### Acceptance Criteria (how do I know when I’m done?)
I can see a list of all permissions and their default value.

![image](https://user-images.githubusercontent.com/773158/53929557-17aea080-405c-11e9-88e6-50983f029ee8.png)

**Comment by sv-ohorvath** [comment]
Verified the acceptance criteria, the UI of recommended settings looks good.
devices: Huawei P20 lite (Android 8), Nexus 5 (Android 6), Galaxy Tab 3 (Android 8).
