### ISSUE TITLE
[Bug] "Unknown protocol" error instead of going back to app after payment

### ISSUE THREAD

**Issue by jandem** [mozilla-mobile/fenix#8880]
## Steps to reproduce
When I order pizza using the New York Pizza app (here in the Netherlands), I get an unknown protocol error after I finish my payment. I was hoping this would be fixed by #7331 but it seems to be a slightly different issue. This used to work perfectly with the old Fennec Nightly.

Looking at this in Firefox desktop, there's a 302 redirect to nypapp://success

### Expected behavior
Goes back to app.

### Actual behavior
Unknown protocol error.

### Device information
Samsung Galaxy S9, Android 10, Nightly 02/28

**Comment by jandem** [comment]
It seems like https://bugzilla.mozilla.org/show_bug.cgi?id=1600704 fixed this for intent:// URLs but not for other schemes like nypapp:// they appear to be using.

**Comment by rocketsroger** [comment]
Need fix from https://bugzilla.mozilla.org/show_bug.cgi?id=1619344

**Comment by rocketsroger** [comment]
@jandem Can you please verify the fix is working correctly for this use case?  Tomorrow's nightly should have the fix.

**Comment by jandem** [comment]
Hi @rocketsroger, thanks for fixing this so quickly! I just updated Nightly but the Gecko version is still too old, I'll try again later this week and let you know.

**Comment by jandem** [comment]
It works \o/
