### ISSUE TITLE
[Bug] Crash on long-pressing the bottom 4 buttons in the main menu (Page forward, Add to bookmarks, Share, Reload)

### ISSUE THREAD

**Issue by theFireProjet** [mozilla-mobile/fenix#8881]
## Steps to reproduce
Open the three dots main menu on the right side of the address bar. Hold down one f.e. the reload button or another of the 4 buttons at the bottom without description.

### Expected behavior
No action defined.

### Actual behavior
Browser crashes.
### Device information

* Android device: 8.0.0
* Fenix version: 3.2.0

**Comment by ekager** [comment]
I can't reproduce on master/nightly so it seems to have been fixed. If you want to test for yourself please download "Firefox Preview Nightly" in the play store, and reopen if this is still occurring.
