### ISSUE TITLE
Custom order of search engines

### ISSUE THREAD

**Issue by theFireProject** [mozilla-mobile/fenix#8882]
### Why/User Benefit/User Problem
It makes accessing your preferred search engines more convenient and looks better if you can sort the engines by your personal priority.
### What/Requirements
Make it possible that you can drag and drop the search engines in the search settings to change their order.
### Acceptance Criteria (how do I know when I’m done?)
The user can go into the search engines settings and change the default alphabetic order of the search engines to his preferred order. The search engines are shown in this order when the address bar is used to search the web.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-16074)

**Comment by crisalis2** [comment]
Up until like 1 or 2 months ago, the search engines at least were sorted alphabetically and you could workaround the problem of not having a custom order option by naming them like, say, "(1) Google", "(2) Wikipedia". But now the order is just completely random... Why?

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807741

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
