### ISSUE TITLE
Improve the order of items in the main menu

### ISSUE THREAD

**Issue by theFireProjet** [mozilla-mobile/fenix#8883]
### Why/User Benefit/User Problem
It makes it easier to find items at their known places and it looks better if options are sorted in a sensible way.
### Current order
(1) Save in collection
(2) Report website issue
(3) New tab
(4) Private tab
(5) Search on site
(6) Add to home screen
(7) Desktop website
(8) Library
(9) Settings
(10) Help

Usually you'd expect the new tabs (3), (4) to be on top.
The site related options could be sticked together: Search on site (5) and Desktop website (7).
All options to save the website should be sticked together: Add to home screen (6), Save in collection (1), Library (8).
Report an issue (2) belongs close to help or settings at the bottom. But that could be down to Fenix being in its preview state so maybe this option is supposed to be extra prominent.
### Expected order
(1) New tab
(2) Private Tab
(3) Search on site
(4) Desktop website
(5) Add to home screen
(6) Save in collection
(7) Library
(8) Settings
(9) Report website issue
(10) Help
That would be a more typical order of these options in a browser in my opinion. That's what I'd suggest.
You can see the categories: New tabs (1, 2), options that take place on the website (3, 4), save website/access saved websites (5, 6, 7), Settings and others.
### What/Requirements
Change the order.
### Acceptance Criteria (how do I know when I’m done?)
The order of the menu items is changed into a more typical order.

Browser version: 3.2.0

**Comment by sv-sdeiac** [comment]
Hi, please consider also the "Add to top sites", "Add-ons Manager" and "Open in App"(if the page can be open in the specific app) buttons on the order to have a clear change about the menu items and the full set of options.

**Comment by topotropic** [comment]
We are working on restructuring the menu. It's documented here https://github.com/mozilla-mobile/fenix/issues/8474. I'll close this issue. Thanks for your feedback!
