### ISSUE TITLE
[Bug] Tab closed pop up only goes away when you click undo

### ISSUE THREAD

**Issue by alexjohnchapman** [mozilla-mobile/fenix#8888]
## Steps to reproduce
Close a tab.

### Expected behavior
The "tab closed" pop up should leave after a few seconds. Clicking "undo" should reopen the closed tab.

### Actual behavior
The pop up doesn't leave until you press "undo". Pressing "undo" does not reopen the closed tab

### Device information

* Android device: Oneplus 3, Android 9
* Fenix version: 3.2.0 (Build #20250236)

**Comment by cadeyrn** [comment]
Duplicate of #7799, fixes with the next update.
