### ISSUE TITLE
Support installing OpenSearch search plugins

### ISSUE THREAD

**Issue by buttercookie42** [mozilla-mobile/fenix#8889]
## Steps to reproduce
1. Visit any page that offers an OpenSearch search plugin, e.g. https://mycroftproject.com/search-engines.html?author=Jan+Henning
2. Install the search engine and acknowledge the confirmation popup whether you actually want to install that search engine.

### Expected behavior
The search engine is installed and I can actually use it.

### Actual behavior
The search engine *doesn't* appear in the list of available search engines.
Curiously enough, attempting to install the same search engine again does yield an "engine with the same name already exists" install error, though.

While I know that you can also manually create a search engine,
1. typing out a query string on a mobile is cumbersome
2. this doesn't allow specifying an icon and
3. most importantly, this doesn't allow specifying usage of a POST query - the online catalogue of my local library *doesn't* accept GET queries for example

### Device information
* Android device: Moto G4 Play, Android 6.0.1
* Fenix version: Nightly 200301 18:00 (Build # 2015726097)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-16080)

**Comment by cousteaulecommandant** [comment]
Would it be possible to set up some sort of extension, feature, or import tool for importing OpenSearch engines (the old installed ones or new ones downloaded from e.g. Mycroft Project) into Firefox's new format?  Creating each search engine manually can be a bit annoying.

**Comment by B0pol** [comment]
BTW fennec supports opensearch. You can test with github on fennec: three dot menu -> page -> add a search engine.
Then you can set it default or remove it in settings, or use this search engine for once.

And as op mentioned, now you can only add search engine using GET. OpenSearch let you use POST.

**Comment by LinAGKar** [comment]
It doesn't support OpenSearch Auto-discovery either, which is still supported by desktop Firefox.

**Comment by Roy-Orbison** [comment]
They've nixed the API required to allow installing search engines with JS for both desktop and mobile, and it will not return. See [bug 1655653](https://bugzilla.mozilla.org/show_bug.cgi?id=1655653).

As @LinAGKar notes, Fenix is also not honouring the [autodiscovery tags](https://developer.mozilla.org/en-US/docs/Web/OpenSearch#Autodiscovery_of_search_plugins) and now the only obvious way to add custom engines is manually entering the search URL. This is far inferior to using a self-updating search plugin with an icon. I get the impression that Mozilla devs really don't (or aren't allowed to) care about the ongoing degradation of custom search. They'll cite low user usage of search addons, and parity with chrome, but people opt to use Firefox for reasons exactly like search personalisation. What little promotion of the feature they have has always been limited to engines listed on AMO, which have always been inferior to Mycroft Project's and sites' own engines. Those who do use custom engines are reasonably vocal when it doesn't work but we're being left in the dust.

**Comment by cousteaulecommandant** [comment]
That's unfortunate; if people wanted a browser that is identical to Chrome, they'd use Chrome.  I use Firefox precisely because I **don't** like Chrome.
Right now I have lost the ability to do some cool tricks such as "search Linguee or compute with WolframAlpha in one tap", which was something I really liked from Firefox and I'm going to miss.  (At least Wikipedia and YouTube are still available.)

Are there any possibilities that the devs will reconsider this, or at least make OpenSearch available via **an addon**?  Installing one browser extension per search engine doesn't seem like a good solution.

PS: at the very least, there could be a tool/addon that converts from installed OpenSearch engines to the new short link version.  Would that be possible?  Would Firefox developers be interested in doing that?

**Comment by KrasnayaPloshchad** [comment]
After I updated to Fenix, I got a shortcoming while I search with sogou.com

1. Open https://m.sogou.com with Fenix
2. Input 汪星人 to search

Then I saw sogou.com encrypted the search keyword in URL. It‘s impossible to add this search engine following [this instruction](https://support.mozilla.org/en-US/kb/manage-my-default-search-engines-firefox-android?as=u&utm_source=inproduct)
![Screenshot_20210201-213215](https://user-images.githubusercontent.com/10364351/106473249-89a8f200-64de-11eb-9969-21e74715f128.png). Press the lock icon on the URL bar to see the details.

**Comment by Roy-Orbison** [comment]
For those search engines you can usually still add them, but you have to look at the HTML form in the page's source. In this case, your engine URL would be `https://m.sogou.com/web/searchList.jsp?keyword=%s`. It would be trivial for Mozilla to make Fifirefox read OpenSearch description files and pull out the search URL, even if they didn't port over the entire icon, suggestion, and self-update portions.

I'm not hopeful. I've been a Firefox user for years and have watched search features slowly die deaths of a thousand cuts.

**Comment by KrasnayaPloshchad** [comment]
Yes, I can see that on Firefox Nightly, but I need to install View Page Source (Mobile) following instructions from Mozilla Add-ons Blog.

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807740

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
