### ISSUE TITLE
When "Dark" theme is chosen, Fenix switches languages[Bug]

### ISSUE THREAD

**Issue by mathiesenk** [mozilla-mobile/fenix#8890]
Choose Icelandic for Fenix language
Go into Settings - Theme
Choose Dark Theme (the choice before is "Follow device theme")

Expected results: theme color changes and language is still Icelandic

Actual results: theme color changes AND language of Fenix changes to English

When Light theme is chosen, the language does not change

Version of Fenix: Nightly 200228 06:00 (build # 20590607)

Device information: Motorola One Vision with Android 10

**Comment by cadeyrn** [comment]
Duplicate of #7559.
