### ISSUE TITLE
Selection window for logins is missing if you have more than one account

### ISSUE THREAD

**Issue by USB3-2-10Gbit** [mozilla-mobile/fenix#8891]
Hello,

I have 2 logins saved on protonmail.com

When I want to use the autofill function of Firefox Preview*, nothing is displayed. There is no selection window if the user has more than 1 login on the same website.
*https://github.com/mozilla-mobile/fenix/releases/tag/v3.2.0

On Firefox Desktop (version 73) has this function.

**Comment by ekager** [comment]
This is planned work as part of https://github.com/mozilla-mobile/fenix/issues/5774
