### ISSUE TITLE
建议去掉首页logo

### ISSUE THREAD

**Issue by 90du** [mozilla-mobile/fenix#8892]
建议去掉首页logo，太占地方！
收藏集模块添加移除开关！
搜索页面样式改为透明浮动！
开启超级缓存，返回不重载
开启网页预加载

**Comment by kbrosnan** [comment]
Via Google translate

> It is recommended to remove the homepage logo, it takes up too much space!  [#8275]
Collection module added and removed switch! [#3753]
Search page style changed to transparent floating! [Not sure?]
Enable super cache, return without reload [#810]
Enable web preloading [Gecko Networking feature does not make sense to track in Fenix]

Closing as this has multiple issues reported in one report.
