### ISSUE TITLE
[Bug]Pressing back key removes all tabs opened through third party apps

### ISSUE THREAD

**Issue by Scripterr** [mozilla-mobile/fenix#8897]
## Steps to reproduce
1. Open the links from other third party apps. Switch to other apps through multitasking only and again open links though it.
3. Firefox opens link in new tab and now press the back button from android back key.
4. Again open firefox preview and observe.
### Expected behavior
All previous tabs opened through third party apps are present, except the page where we back out is removed.
### Actual behavior
All previous tabs opened through third party apps are removed.
### Device information

* Android device: ?
* Fenix version: ?

**Comment by softvision-miralobontiu** [comment]
Verified as fixed on the latest Nightly build from 3/12, and on Beta v4.1.0-beta.1, with Samsung Galaxy Tab A6 (Android 9), and Nexus 5 (Android 6.0.1).
