### ISSUE TITLE
[Bug]Progress bar curved at starting point

### ISSUE THREAD

**Issue by Scripterr** [mozilla-mobile/fenix#8898]
Open a webpage and observe. You would see that the progress bar is curved in starting point. It should be rectangular in starting point.
Screenshot attached-
![Screenshot_20200302-163539_1](https://user-images.githubusercontent.com/42364681/75671082-e4eeb680-5c75-11ea-9dbc-5946023b6476.png)

**Comment by sv-sdeiac** [comment]
Verified as fixed using the latest version of Firefox Preview Nightly 3/3 @20630607).

Devices:
- Nokia 6 (Android 7.1.1);
- Xiaomi Mi 8 Lite (Android 9);
- Google Pixel (Android Q).
