### ISSUE TITLE
[Bug] Snackbar not showing in customTab with bottom toolbar

### ISSUE THREAD

**Issue by ValentinTimisica** [mozilla-mobile/fenix#8899]
### Steps to reproduce
- Set toolbar to bottom
- Go to `Settings` -> `About Firefox Preview` -> `What's new in Firefox Preview`
- Long tap on URL bar
- Press on `Copy`

### Expected behavior
- Snackbar with the message `URL copied to clipboard` should show
### Actual behavior
- Nothing happens

### Additional info
- [Video](https://drive.google.com/open?id=1qzGRUo6LTX_ulyM2kl3GIkD8YA9x8dm2) with the bug
- Note that if the toolbar is set to Top, the Snackbar is showing properly, as you can see in the video above.

### Device information
- Android device: Samsung Galaxy Note 10 (Android 10)
- Fenix version: Latest Nightly from store (Version: Nightly 200302 06:00)

**Comment by ekager** [comment]
We'll probably have to change the view that we're passing into the `FenixSnackbar`.

**Comment by sv-sdeiac** [comment]
Hi, I can confirm that this issue is fixed using the latest Firefox Preview Nightly 3/23 #20830607.

Devices:
- Google Pixel 3 (Android 10);
- Samsung Galaxy Tab S6 (Android 9);
- LG g7 fit (Android 8.1).
