### ISSUE TITLE
[Bug] Deleted logins on FF desktop are still auto-filled on Fenix if autofilled is enabled on Fenix

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/fenix#8905]
## Prerequisite
The user should be signed in to Sync with the same Account on both FF for Desktop and Fenix
The login credentials for E.g. Twitter should be saved 

## Steps to reproduce
1. Sync on Fenix and verify the saved logins(the twitter account is not displayed anymore).
2. On Fenix access `www.twitter.com`.
### Expected behavior
The `username` and `password` fields are empty and no autofill is made.
### Actual behavior
The deleted logins are not auto-filled when accessing a webpage.
### Device information

* Android device: **Samsung Galaxy S10+ (Android 9)**
* Fenix version: **Nightly 3/2.**

## Notes
If the autofill is disabled in Fenix `Saved Logins` the pre-fill is not made.
When enabling the autofill in Fenix `Saved Logins` the pre-fill is made even if that account was deleted from the account.
When the screen is black I tried to show that the twitter account is not in the saved logins.

![20200302-162849](https://user-images.githubusercontent.com/42831109/75686832-8b9e7b80-5ca5-11ea-9c3e-18216daaa007.gif)

**Comment by ekager** [comment]
cc @linacambridge it's kind of the opposite problem but is it possible that passwords sync needs a similar fix to #8531 / https://github.com/mozilla/application-services/pull/2694 ? After syncing passwords it seems like we know when trying to display all of the logins that a login has been deleted, but when we use `getByBaseDomain` a deleted login is still being displayed?

**Comment by linacambridge** [comment]
Yikes, that's not good; thanks for looping me in, @ekager! 👀 Here's what I've gathered so far, please let me know if I'm misunderstanding anything:

* `GeckoLoginStorageDelegate` is what's responsible for fetching logins for autofill (via [`onLoginFetch`](https://github.com/mozilla-mobile/android-components/blob/98db88f86394b5115058f99d4abeadf6f4caf5cc/components/service/sync-logins/src/main/java/mozilla/components/service/sync/logins/GeckoLoginStorageDelegate.kt#L78)), and updating them in response to user changes.
* `onLoginFetch` calls `loginStorage.getByBaseDomain`, which just [forwards the call to a-s](https://github.com/mozilla-mobile/android-components/blob/98db88f86394b5115058f99d4abeadf6f4caf5cc/components/service/sync-logins/src/main/java/mozilla/components/service/sync/logins/AsyncLoginsStorage.kt#L421-L423).
* An [FFI hop](https://github.com/mozilla/application-services/blob/1ce38c473236b927fe22ae095a574bb4730e77c5/components/logins/ffi/src/lib.rs#L307-L311) later, we end up in [`LoginDb::get_by_base_domain`](https://github.com/mozilla/application-services/blob/1ce38c473236b927fe22ae095a574bb4730e77c5/components/logins/src/db.rs#L417). 
* `get_by_base_domain` uses [this SQL](https://github.com/mozilla/application-services/blob/1ce38c473236b927fe22ae095a574bb4730e77c5/components/logins/src/db.rs#L1280-L1285) to fetch all logins, then pares them down in code. That query reads non-deleted logins from `loginsL`, and non-overridden (IOW, not existing in `loginsM`) logins from `loginsM`.
* Deleting a login sets `loginsM.is_overridden = 1`, so `GET_ALL_SQL` should exclude them. It also clears out usernames and passwords from `loginsL`, and sets `loginsL.is_deleted = 1`, so the tombstone should also be excluded from the query.
* ...But we still end up filling the username and password, even when it's deleted and doesn't show up in the list of saved logins. 😱

@abodea, would you mind pulling `logins.sqlite` from your test device, and sending it over for analysis? I'm curious what's in the two tables, and where it's pulling that login from if it's been deleted. Thanks!

**Comment by abodea** [comment]
Hello @linacambridge, unfortunately, I didn't have the save from yesterday...so in order to generate the `logins.sqlite` I created a debug build with the latest code from master and I tried to reproduce the issue.
Note that there is https://github.com/mozilla-mobile/fenix/issues/8727 and sometimes the autofill is not made at all..
[logins.zip](https://github.com/mozilla-mobile/fenix/files/4281970/logins.zip)

**Comment by linacambridge** [comment]
Hmm, I wonder if that autofill bug is bug is related...

Oh, bleh, I forgot this needs the encryption key as well 😅 (Ironically enough, reading [this](https://github.com/mozilla-mobile/fenix/blob/6a75d822ca5e723e4d29353ba5778e3641eb87f7/app/src/main/java/org/mozilla/fenix/components/Core.kt#L229-L250), it looks like that's only enabled on debug builds). Andrei, since you already have a debug build locally, any chance you could [change this line](https://github.com/mozilla-mobile/fenix/blob/6a75d822ca5e723e4d29353ba5778e3641eb87f7/app/src/main/java/org/mozilla/fenix/components/Core.kt#L225) to `CompletableDeferred("")`, then rebuild and repro? I can also try making my own build and reproing your steps in the emulator later today. Thanks so much, and sorry for the extra work!

**Comment by ekager** [comment]
@abodea I just tried to reproduce this and wasn't able to anymore. Could we test this again? Thanks!

**Comment by abodea** [comment]
@ekager I couldn't reproduce it on the latest Nightly build from 6/15 with Google Pixel 4 XL (10).
I will close this issue and in case I will reproduce it in the future, I will open a new bug.
