### ISSUE TITLE
Fenix integration: Notify users when previously unsupported addons become available

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/fenix#8908]
Related issue https://github.com/mozilla-mobile/android-components/issues/5434

**Comment by Amejia481** [comment]
Closed by https://github.com/mozilla-mobile/fenix/pull/9060/commits

**Comment by sv-ohorvath** [comment]
@Amejia481 should this notification be visible on the Fenix Beta 4.1 update, or is it meant only for the migration build? Asking for the new beta 4.1 build validation.

**Comment by sv-ohorvath** [comment]
Arturo's response for future reference: "I belive you have to be migrated from Fennec to Fenix, then some of your add-ons are going to be disabled as they are not supported, then when they become supported , the notification will show up"
