### ISSUE TITLE
Offer 1x1 as an additional search widget size

### ISSUE THREAD

**Issue by brampitoyo** [mozilla-mobile/fenix#8921]
How might we offer one-tap instant access to Fenix search while conserving home screen real estate?

- My homescreen may already be full of icons; this makes large widget an unattractive prospect
- I may not know that widgets are resizeable

Today, Fenix offers only one widget size.

<img width="360" src="https://user-images.githubusercontent.com/51007/75741327-21eaa400-5d6f-11ea-81cd-401bdbd07473.png">

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-16097)

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807579

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
