### ISSUE TITLE
Fennec migration: The "Start Firefox" button is not visible in split view on devices with a smaller resolution

### ISSUE THREAD

**Issue by ebalazs-sv** [mozilla-mobile/fenix#8924]
## Preconditions:
Have Fennec installed.
## Steps to reproduce
1. Replace Fennec with Fenix using a build from [here](https://firefox-ci-tc.services.mozilla.com/tasks/index/project.mobile.fenix.v2.fennec-nightly.2020.01.16.revision/9c25d274d0d3c6549f607ce1298471ca6627a8d4).
2. With the onboarding migration screen displayed, long tap the Recent apps button;
3. Observe the migration onboarding screen page;
### Expected behavior
All the elements from the migration onboarding page are visible.
### Actual behavior
The "Start Firefox" button is not visible in split view on devices with a smaller resolution.
### Notes:
[Screenshot in portrait mode](https://drive.google.com/open?id=1R4GBgsn3dU0-szMZBQHLsHNQnG02GBCG);
[Screenshot in landscape mode](https://drive.google.com/open?id=1R84sxMAc-uenGr4zkc-E-81aGI5zG44W);
Not reproducible on LG G7 fit (Android 8.1), 1440 x 3120 pixels, 19.5:9 ratio (~563 ppi density);
### Device information

* Android device: Huawei P9 Lite (Android 7), resolution 1080 x 1920 pixels;
* Fenix version: Beta migration build 2, 02/27.

**Comment by Sparky93** [comment]
Tested with this [PR](https://github.com/mozilla-mobile/fenix/pull/8819) from #7978 and it looks like a bottom anchored button is going to fix the problem.
![image](https://user-images.githubusercontent.com/20266431/75789576-92df8b00-5d72-11ea-96f6-e5a228f51b5a.png)

**Comment by ebalazs-sv** [comment]
This is reproducible on Beta Migration Build #3 with Huawei P9 Lite (Android 7).

**Comment by ebalazs-sv** [comment]
This is reproducible on Beta Migration build 4.0.0-beta.2, 3/10 with Huawei P9 Lite (Android 7).

**Comment by ebalazs-sv** [comment]
This is still reproducible on Beta Migration build 4, 3/24, with Huawei P9 Lite (Android 7).

**Comment by ebalazs-sv** [comment]
The "Start Firefox" button is visible in split mode, since the issue https://github.com/mozilla-mobile/fenix/issues/7978 is verified on Release migration build 4.0.0-beta.2 GV 76 4/8 with Motorola G6 (Android 8), Huawei P9 Lite (Android 7) and the entire migration screen page is scrollable.
I will also verify this on the next migration build.

**Comment by ebalazs-sv** [comment]
In the issue https://github.com/mozilla-mobile/fenix/issues/7978#issuecomment-591512513 it was decided that the "Start Firefox" button will remain fixed while the rest of the screen scrolls behind it.
This is verified as fixed and this issue is not reproducible anymore due to that.
I will close this issue and move it to Done.
Thanks!
