### ISSUE TITLE
[Bug] White stripe at the bottom when dark mode and bottom bar is activated

### ISSUE THREAD

**Issue by limuc** [mozilla-mobile/fenix#8926]
**Steps to reproduce**
- activate dark mode in Fenix + bottom bar
- visit website, that has a dark background
- scroll down until bottom bar is hidden
--> small white stripe/line at the bottom

**Expected behavior**
There should be no white stripe/line.

**Actual behavior**
There is a white stripe/line at the bottom.

**Device information**
- Xiaomi Mi 9 
- Android 10

**Screenshot (on grey background, so the stripe/line is visible, as it is at the bottom):**
![Screenshot (64)](https://user-images.githubusercontent.com/49267156/75763278-4b3e0c80-5d3c-11ea-9cdf-6ed4aac4924a.png)

**Comment by ekager** [comment]
Closing for #10598
