### ISSUE TITLE
Login in to firefox account or some sites make device reboot

### ISSUE THREAD

**Issue by Cartesson** [mozilla-mobile/fenix#8928]
**Steps to reproduce**
1. Try to login in to firefox account using email and password and a forum's site.

### Expected behavior
Just do the login.

### Actual behavior
When i type the password and click login button the device reboot itself

### Device information
* Android device: **Mi9t on MIUI 11 Android 10**
* Fenix version: **Nightly build #20630608 from 3/3.**

### Notes
Well i just came across this bug and didn't find a option to report so i came here. It's was a new phone and happened first time when i hit login in to firefox account, the only way to login was using the QR code because if i tried with account it rebooted the phone. Found it weird but kept using it so i go to some forum and when i tried to login same thing happened several times, just tried another browser and worked fine. But it's very strange because others sites is normal like facebook, reddit and etc. Don't know what caused it because i already used Firefox Preview on this miui version so nothing new here.

**Comment by abodea** [comment]
Thank you for this report @Cartesson!
I tried to reproduce this issue on the latest Nightly 3/3 with Google Pixel 3a XL(Android 10) and Samsung Galaxy S10+ (Android 10) - this one has the latest android version released.
Note that I was able to log in without problems.
Is this a new FF account or are there any other steps you did before trying to login?

**Comment by Cartesson** [comment]
> Thank you for this report @Cartesson!
> I tried to reproduce this issue on the latest Nightly 3/3 with **Google Pixel 3a XL(Android 10)** and **Samsung Galaxy S10+ (Android 10)** - this one has the latest android version released.
> Note that I was able to log in without problems.
> Is this a new FF account or are there any other steps you did before trying to log in?

Just installed and went to login. It's still happening, it makes no sense to me why, just happened a minute ago when I tried to log in a shop site but it didn't when I logged here to answer this. But I guess it has to be the system.

**Comment by abodea** [comment]
Can you please provide a few shops where you encountered the issue?
I will try to create a new account and login there.

**Comment by Cartesson** [comment]
> 
> 
> Can you please provide a few shops where you encountered the issue?
> I will try to create a new account and login there.

It's easier to just try to login firefox account it happens 100% of the time here, tried on preview and preview nightly. A friend said he'd test on his phone(same as mine) but don't know if he did.
But this one https://www.dafiti.com.br/ made it reboot too. Btw it's in portuguese

**Comment by Cartesson** [comment]
It's 100% a rom problem. Changed system and it was all ok, reverted back and the problem is here.
