### ISSUE TITLE
[Bug] Colors aren't managed

### ISSUE THREAD

**Issue by toastal** [mozilla-mobile/fenix#8932]
## Site with issue and any steps to reproduce

https://photographylife.com/is-your-browser-color-managed

### Expected behavior

I expect the color profile of the second, ProPhoto color spaced photo. Given that many high-end handhelds support wider-than-sRGB color spaces like DCI-P3, I believe this is a bug.

### Actual behavior

The colors are washed out/wrong

### Does toggling Tracking Protection fix the issue? (Press the lock icon in the toolbar while on the site to see toggle)

No

### Can you reproduce in [Firefox for Android](https://play.google.com/store/apps/details?id=org.mozilla.firefox)?

Yes, if I disable the color management through about:config

### Can you reproduce in Chrome (or other non-Mozilla browser)?

With the color management enabled in the about:config, Firefox for Android displays colors fine. Bromite shows colors fine too.

### Device information

* Android device: Xiaomi Redmi K20 Pro
* Fenix version: 3.2.020250236

**Comment by softvision-miralobontiu** [comment]
I was not able to reproduce the issue on the 12/4 Firefox Nightly build, with Samsung Galaxy Tab S6 (Android10):

<img src="https://user-images.githubusercontent.com/40694158/101166356-d25c4000-3640-11eb-9485-ebb2cbc25dcd.jpg" width="300" height="550" />
