### ISSUE TITLE
Maintain reader mode when following a link

### ISSUE THREAD

**Issue by st3fan** [mozilla-mobile/fenix#8938]
> From https://bugzilla.mozilla.org/show_bug.cgi?id=1618161

Steps to reproduce:

I'm reading content in websites in reader mode, the content is broken up into several pages (e.g. chapters). I follow a link in chapter 1 to chapter 2

Actual results:

Chapter 2 opens in normal mode

Expected results:

Firefox maintains reader mode when opening chapter 2.
Optional, press and hold on link to open next page in reader mode.

**Comment by kbrosnan** [comment]
We can't really do this with the current https://github.com/mozilla/readability it requires a fully loaded page to parse and check if it is readerable.

**Comment by csadilek** [comment]
Duping to same feature request in https://github.com/mozilla-mobile/fenix/issues/4797.
