### ISSUE TITLE
[Bug] Dark theme toolbar home screen regression

### ISSUE THREAD

**Issue by ekager** [mozilla-mobile/fenix#8949]
On my API 22 Emulator in Dark Theme:
<img width="418" alt="Screen Shot 2020-03-03 at 11 17 54 AM" src="https://user-images.githubusercontent.com/25442310/75812368-f81b8800-5d42-11ea-85e1-0e7a5891346b.png">

Likely regression from #8839 because I think this uses the `inset` attr

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on both **`Fenix Nightly Build #20711809 from 3/11`** & **`Fenix Beta 4.1.0-beta.1 from 3/12`** using the following devices:
• Google Pixel 4XL (Android 10)
• Google Pixel 3a (Android 9)
• OnePlus A3 (Android 6.0.1)

►Screenshot
![bzzz](https://user-images.githubusercontent.com/51314259/76537860-0bd39680-6487-11ea-9feb-16bbbfc07bce.png)
