### ISSUE TITLE
Library menu - easier use with thumb

### ISSUE THREAD

**Issue by Cheap-Skate** [mozilla-mobile/fenix#895]
Library menu is "top justified" with items near top of screen. Hard to reach one handed. If Fenix is going for "one handed" thumb use perhaps Library menu should be "bottom justified" with most frequently used items at bottom of screen (perhaps Favorites, History, Sessions but perhaps not Logins or Screenshots).

Perhaps also need to think how it behaves in future if there are more menu items than can fit on the screen. Does user have to drag **down** to get new items at the top of the screen?

In general (I said it somewhere else) if Fenix is going for maximum "one handed" use, think about how much of the UI gets turned upside down with important stuff at the bottom of the screen.  For example, the "Search" magnifying glass in the Library screen is at the top of the page. Should it be at the bottom?

see also #469 which is more of the same about the three dot menu.

How about..........

```
+--------------------+
| Library        o x |
|                    |
|                    |
|                    |
|                    |
| Logins             |
| Screenshots        |
| Downloads          |
| Sessions           |
| History            |
| Favorites          |
+--------------------+
```

**Comment by brampitoyo** [comment]
I agree that thumb-friendliness is something that we need to look at on every screen.

At the same time, there’s a fundamental conflict at play:

* We hold the device on the bottom, making everything on the bottom more reachable
* We read from top, making everything on top seem more important. And our reading direction is always “scroll down”.

So do we prioritise the thumb access, or the reading hierarchy/direction?

I’ve sized this issue on its own. I recommend us to look at the thumb-friendliness of this library menu as a starting point to assess every other screen on the app. Surveying all the screens will take a long time, and should be filed as a separate issue.

**Comment by vesta0** [comment]
We have removed Library so this is no longer relevant.
