### ISSUE TITLE
[Bug] Keyboard doesn't hide when going to Settings on some devices

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#8968]
## Steps to reproduce
1. Open google.com / twitter.com
2. Tap on a text field to trigger the keyboard.
3. Open the 3 dot menu and go to Settings while the keyboard is on.
### Expected behavior
The keyboard is hidden.
### Actual behavior
The keyboard stays on.
### Device information

* Android device: Huawei P9 Lite (Android 7.0), Xiaomi Mi Pad 2 (Android 5.1) , Nokia 6 (Android 7.1.1)
* Fenix version: 4.0-beta3, Nightly 3/3

**Comment by mcarare** [comment]
I can also confirm this happens on some pages on a Huawei P10 with Android 9 and SwiftKey as soft keyboard.

**Comment by ekager** [comment]
Reopening for verification

**Comment by sv-sdeiac** [comment]
Verified as fixed using the latest version of Firefox Preview Nightly  3/29 @20891805.
Now the keyboard is hidden when you open the Settings.

Devices:
- Google Pixel 3 (Android 10);
- Xiaomi Mi 8 Lite (Android 9);
- LG g7 fit (Android 8.1).
