### ISSUE TITLE
[Bug] Tab hangs while loading http-auth page after getting 401 from same page

### ISSUE THREAD

**Issue by staktrace** [mozilla-mobile/fenix#8969]
## Steps to reproduce
1. Open browser
2. Go to a page with HTTP authentication, e.g. https://bugmash.staktrace.com/dashboard.php
3. When you get the HTTP auth prompt, hit cancel. This will give you a 401 error page
4. Reload the page, or open the same URL in a new tab

### Expected behavior

Browser shows prompt for HTTP auth again

### Actual behavior

Tab goes into a "loading" state that never ends. Have to restart the browser to make it work again.

### Device information

* Android device: Sony Xperia XZ1C, Android 9
* Fenix version: Whatever the latest nightly is as of March 3

**Comment by snorp** [comment]
Filed GV Bug https://bugzilla.mozilla.org/show_bug.cgi?id=1643129 for this

**Comment by staktrace** [comment]
Fixed now
