### ISSUE TITLE
[Bug]Distorted and zoomed in transition from Instagram to the home screen

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#8970]
## Steps to reproduce
1. Navigate to https://www.instagram.com/accounts/login/
2. Tap on the tab counter

### Expected behavior
Properly perform the transition to the home screen

### Actual behavior
Seem to be zooming in and distorting instagram before the transition.

### Device information

* Android device: OnePlus A3 (Android 6.0.1)
* Fenix version: 
• Nightly #20640607 from 3/4
• Beta 4.0.0-beta.3

### Notes
► Video 
![20200304-155156](https://user-images.githubusercontent.com/51314259/75893818-05686d80-5e3c-11ea-9621-b6c250b39796.gif)

**Comment by sv-ohorvath** [comment]
Also seen on twitter.

**Comment by AndiAJ** [comment]
**Not reproducible** anymore on the latest on the latest **`Nightly Build 201111`** using the following devices:
• Google Pixel 3a (Android 11)
• Huawei Mate 20 Lite (Android 10)
• OnePlus A3 (Android 6.0.1)
