### ISSUE TITLE
[Edit Mode] Wrong colours for Dark/Private theme

### ISSUE THREAD

**Issue by AmyYLee** [mozilla-mobile/fenix#8972]
I've marked up colours for edit mode in Library (History/Bookmarks) and Collections. Dark theme colours when in Dark/Private Mode. 
![spec](https://user-images.githubusercontent.com/5992746/76462278-c98f5400-63b7-11ea-87dc-abcc4b1a2541.png)

**Comment by BranescuMihai** [comment]
@AmyYLee Let me check if I understood correctly what should be changed. Current dark colours:
- Library item checkmark + toolbar in edit mode: **#9059FF (light violet)**
- Collections checkbox: **#592ACB (dark violet)**
- Collections bottom snackbar: **#592ACB (dark violet)**

This should be changed to:
- Library item checkmark + toolbar in edit mode: **#AFAFBB (which is a blueish grey)**
- Collections checkbox: **#AFAFBB (blueish grey)**
- Collections bottom snackbar: **#9059FF (light violet)**

Is this right?

**Comment by AmyYLee** [comment]
> @AmyYLee Let me check if I understood correctly what should be changed. Current dark colours:
> 
>     * Library item checkmark + toolbar in edit mode: **#9059FF (light violet)**
> 
>     * Collections checkbox: **#592ACB (dark violet)**
> 
>     * Collections bottom snackbar: **#592ACB (dark violet)**
> 
> 
> This should be changed to:
> 
>     * Library item checkmark + toolbar in edit mode: **#AFAFBB (which is a blueish grey)**
> 
>     * Collections checkbox: **#AFAFBB (blueish grey)**
> 
>     * Collections bottom snackbar: **#9059FF (light violet)**
> 
> 
> Is this right?

@BranescuMihai 

Hi, thanks for confirming. I can see why there is confusion. I've updated the spec so it's correct. 

This should be changed to:

    Library item checkmark + toolbar in edit mode: #9059FF (light violet)
    Collections checkbox: #9059FF (light violet)
Collections checkbox: #9059FF (light violet)

    Collections bottom snackbar: #9059FF (light violet)

**Comment by sv-sdeiac** [comment]
Hi, I can confirm that this issue is fixed using the latest version of Firefox Preview Nightly 3/26 #20860605.

Devices:
- Samsung Galaxy Tab S6 (Android 9);
- LG g7 fit (Android 8.1).
