### ISSUE TITLE
Share to email puts subject in body of email [Bug]

### ISSUE THREAD

**Issue by JNavas2** [mozilla-mobile/fenix#8975]
## Steps to reproduce
Open a webpage. 
Touch Share, then Gmail.
### Expected behavior
Open new Gmail message with webpage title in subject and link in body (like Chrome).
### Actual behavior
Open new Gmail message with webpage title in subject _and also in body_ just before link (with only a space to separate them).
If the webpage title is to be included in the body, it should be on a _separate line_ from the link.
### Device information
Device model: Google Pixel 3a (sargo)
Android version: 10 (QQ2A.200305.002)
Carrier: T-Mobile USA
Fenix version: Nightly 200303 18:01 35.0.0

**Comment by sv-sdeiac** [comment]
I can confirm that the issue is reproducible using the latest version of Firefox Preview Nightly 3/5 #20650606.

Also, using Fennec RC 68.5.0 build is not reproducible.

Device:
- Google Pixel (Android Q).

**Comment by mcarare** [comment]
Firefox for Android shares to email without title in body. 
UX, can you confirm how to want to fix this?

**Comment by topotropic** [comment]
You can also share multiple URLs and in this case a title is helpful – let's keep it. 

We can have a line break after the title so that it looks like this:

Internet for people, not profit — Mozilla
https://www.mozilla.org/en-US/

**Comment by JNavas2** [comment]
Line break fix confirmed in Fenix Nightly #20660605. 
Thank you!

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly Build #20700607 from 03/10`** using the following devices:
• Google Pixel 3a (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

►Video
![20200310-151236-1](https://user-images.githubusercontent.com/51314259/76317303-ab0c5880-62e4-11ea-83d5-0e04b0f82879.gif)
