### ISSUE TITLE
[webcontent] Page elements with wrong placement in rawg.io

### ISSUE THREAD

**Issue by MechJM** [mozilla-mobile/fenix#8977]
## Site with issue and any steps to reproduce
The website is rawg.io and there are two issues. The steps to reproduce each one are the following:
- 1: Just go to the website
- 2: Go to the website, use the "install"  function in order to add to the home screen what I believe is a PWA, open it and scroll down
### Expected behavior
- 1: The "hamburger menu" icon (three horizontal lines) doesn't overlap the search bar
- 2: The bottom bar sticks to the bottom of the page
### Actual behavior
- 1: The "hamburger menu" icon (three horizontal lines) on the top right corner overlaps the search bar like you can see here:
![Screenshot_2020-03-04-20-46-08-687_org mozilla fennec_aurora](https://user-images.githubusercontent.com/56487084/75922856-c77b4180-5e5b-11ea-8f30-afd774fa73ea.jpg)
- 2: There's a gap between the bottom bar and the bottom of the screen like you can see here:
![IMG_20200304_204659](https://user-images.githubusercontent.com/56487084/75923611-576dbb00-5e5d-11ea-8285-28716a4d97ff.jpg)

### Does toggling Tracking Protection fix the issue? (Press the lock icon in the toolbar while on the site to see toggle)
- 1: No
- 2: No
### Can you reproduce in [Firefox for Android](https://play.google.com/store/apps/details?id=org.mozilla.firefox)?
- 1: Yes.
- 2: No.
### Can you reproduce in Chrome (or other non-Mozilla browser)?
- 1: No
- 2: No

### Device information

* Android device: Xiaomi Mi 9T
* Fenix version: Nightly 200303 06:01

**Comment by MechJM** [comment]
Issue 2 has been fixed.

**Comment by sflorean** [comment]
I am able to reproduce the issue on Nightly 20/10 but not on Chrome. 
Device: Pixel 3 (Android 11).

**Comment by Mugurell** [comment]
I think the issues here are resolved by now (tested on the latest Nightly):
- the searchbox sits at a safe distance from the hamburger menu
- the toolbar stays fixed in place and so causes no issues

@sflorean @MechJM can this be closed?

**Comment by MechJM** [comment]
I can confirm the issues are fixed in the latest Nightly.

**Comment by sflorean** [comment]
Closing based on the above comments.
