### ISSUE TITLE
Investigate slow createAppContext call relative to Fennec

### ISSUE THREAD

**Issue by csadilek** [mozilla-mobile/fenix#8979]
In the the following two profiles we're seeing a big difference in `createAppContext` and `handleBindApplication` total running times:

Fennec: https://profiler.firefox.com/public/327373a230b04f58d0936fb60478bb9a84d5ef30/
Fenix: https://profiler.firefox.com/public/c78aeffd46f820c8e7337c20b4e16bd104cd556e/

Let's investigate if this is consistently true and find out why.

**Comment by csadilek** [comment]
We decided to investigate this once https://github.com/mozilla-mobile/fenix/issues/8803 lands and we have real-world data from various devices.

**Comment by mcomella** [comment]
Triage: we are doing another telemetry analysis so we might as well do this with that one to reduce context switching cost.

**Comment by mcomella** [comment]
Dupe #10161 since that one has more information.
