### ISSUE TITLE
[Bug] Order of synced devices in Share should be be recently/frequently used

### ISSUE THREAD

**Issue by madb1lly** [mozilla-mobile/fenix#8981]
### Why/User Benefit/User Problem
Many people, like me, may have several synced devices to which we send tabs. I frequently send tabs between Fenix Nightly and a Windows 10 Firefox instance. However, the order in which the synced devices appear in the share list always shows this Win10 instance (my most common share destination) and the end of the list, so I have to sidescroll to get to it everytime.

### What/Requirements
In Fennec I believe the list of devices to send tabs to is shown based on either most frequently or most recently used (or a combination of both) - the order of the list changes when I send to less common devices, so I know there is some algorithm at work.

Please apply this algorithm in Fenix, it will save me and others a little bit of time every time we send a tab, and in total that will save a lot of time.

### Acceptance Criteria (how do I know when I’m done?)
When the order of the synced devices in the share menu is updated based on most frequently or most recently used (or a combination of both), like in Fennec.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-16132)

**Comment by sflorean** [comment]
Tested this on the latest Nightly build 5/8 and I can confirm that the win10 synced device is the first listed. 
However, if I share pages more than 3 times with Reference Browser synced device (displayed at the end of the list), win10 is still displayed first and RB doesn't change the position. 
@mcarare is this expected?

**Comment by mcarare** [comment]
@sflorean I think it will change position only after you navigate away and open share sheet next time. If it does not, it could be a problem on the a-s sync side. cc @ekager

**Comment by madb1lly** [comment]
Hi all,

The order of synced devices has remained the same since I started using Fenix daily in February. I've even reinstalled it a few times and the order has stayed the same. Nothing I have done appears to change this order.

Cheers 🙂

**Comment by sflorean** [comment]
Tested again on Xiaomi Redmi Note 8T (Android 9) and I followed the steps:
1. Open a page and share it with the second device listed from left to right (not Win).
2. Close Fenix/ or open other pages and share them. 
When the share dialog is displayed, the devices aren't updated based on the last shared selection.

**Comment by madb1lly** [comment]
Hi @ekager,

I can see something is now happening! The list is updated to show in the order I was last using synced devices, i.e. the synced device I last used is at the left-most end of the list. 

This is fine but is not as sophisticated as what is in Fennec, IIRC. I think that Fennec updates the list based on which devices were last _shared to_,  but my memory is a bit hazy and I don't use Fennec daily any more so can't really test it.

My preferred implementation would be based on a combination of most recent and most frequently shared to, i.e. if I share to device X frequently and Y very rarely but Y was the last device I shared to then X should probably still be first in the list.

Cheers 🙂

**Comment by ekager** [comment]
I think I've added a small improvement by sorting devices by `lastAccessTime` but AFAICT further improvements would need more AS work

**Comment by jonalmeida** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1810645

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
