### ISSUE TITLE
[Bug] Red items on Android 5 devices

### ISSUE THREAD

**Issue by softvision-miralobontiu** [mozilla-mobile/fenix#8982]
## Steps to reproduce
1. Make Firefox Preview Beta your default browser.
2. Go to Gmail, and open https://www.thinkbroadband.com/download in a custom tab.
3. Select to download any file, and observe the "download" prompt.
4. Tap back, and open https://daleharvey.github.io/testapp/ in a custom tab.
5. Tap on "Get location" and observe the permission prompt.

### Expected behavior
Black buttons are displayed.

### Actual behavior
Red buttons are displayed.

### Device information
* Android devices: Xiaomi Mi4i (Android 5.0.2), Xiaomi MiPad2 (Android 5.1), LG Nexus 4 (Android 5.1.1)
* Fenix version: Beta v 4.0.0-beta.3
* Not reproducible on Nightly build from 3/5

![red](https://user-images.githubusercontent.com/40694158/75963130-a5220c00-5ecd-11ea-8388-30d8b516e97b.png)

**Comment by softvision-miralobontiu** [comment]
I found another set of red items on an Android 5 device: when saving tabs in a collection.
Tested on the latest Nightly build from 4/6 with Samsung Galaxy Tab A6 (Android 5.1.1).
![red](https://user-images.githubusercontent.com/40694158/78565201-3a465680-7826-11ea-8030-465e35e065e2.png)

**Comment by softvision-miralobontiu** [comment]
Searching a language in Settings - Language displays the typed characters in red on Samsung Galaxy Tab A6 (Android 5.1.1) on both 4/21 Nightly build, and Beta 4.3.0-beta.2 build:

![red](https://user-images.githubusercontent.com/40694158/79866567-a22f9c00-83e5-11ea-84f5-d88085da13f5.png)

**Comment by softvision-miralobontiu** [comment]
On the latest Nightly build from 5/8, on Samsung Galaxy Tab A6 (Android 5.1.1), the "red items" are back on onboarding:

<img src="https://user-images.githubusercontent.com/40694158/81389177-18d8d300-9122-11ea-832a-8c27d7ef8709.gif" width="300" height="550" />  

<img src="https://user-images.githubusercontent.com/40694158/81389186-1c6c5a00-9122-11ea-98fa-35e006cc0b0a.gif" width="300" height="550" />

**Comment by softvision-miralobontiu** [comment]
On the 5/18 Nightly build, the red items from the onboarding tour are fixed (see #10501).
Searching a language in Settings - Language doesn't display the typed characters in red.
However, saving tabs in a collection still displays red items:

<img src="https://user-images.githubusercontent.com/40694158/82218530-b30bf880-9924-11ea-84bb-564ecdfcfb2a.png" width="300" height="550" />

**Comment by sflorean** [comment]
Onboarding screen on Huawei MediaPad M2(Android 5.1.1) - Nightly 7/24. Not reproducible on 79.1.0-beta.1.

![Screenshot_2020-07-24-16-35-16](https://user-images.githubusercontent.com/58466444/88408564-676e4300-cddc-11ea-8435-f1dc377a5202.png)

**Comment by ekager** [comment]
@mcarare looks like you updated the onboarding radio buttons in #12592 ?  Any idea why the colors aren't working here?

**Comment by softvision-miralobontiu** [comment]
This is no longer reproducible on the 12/31 Nightly with Samsung Galaxy Tab A6 (Android 5.1).
