### ISSUE TITLE
[Bug] testStrictVisitDisableExceptionToggle test possibly flaky on Firebase

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#8983]
Spotted testStrictVisitDisableExceptionToggle failing on Nexus 6: https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7727347515092753227/executions/bs.280da37d4a1af1ad
- if it keeps failing will need to be disabled

**Comment by AndiAJ** [comment]
Flaky 1x on Master 2/25:

`androidx.test.espresso.NoMatchingViewException: No views in hierarchy found matching: (with id: org.mozilla.fenix.debug:id/removeAllExceptions)`

[Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6745443436969410914/executions/bs.a6bdef8c910bd202/testcases/3/test-cases)

**Comment by sv-ohorvath** [comment]
Hasn't failed in more than a month, closing for now. Can be reopened if it happens again.
