### ISSUE TITLE
[Bug] 3-dot menu:- when vertically scrolled, icons at bottom of list should not scroll

### ISSUE THREAD

**Issue by Cheap-Skate** [mozilla-mobile/fenix#8986]
## Steps to reproduce
install uBlock Origin (to get an extra 3 dot menu item)
move to a page which has Reader View active (to get an extra 3 dot menu item)
open 3 dot menu
on my Galaxy A40 the menu list is now vertically scrollable because there are so many items
vertical scolling moves the bottom line of four icons (forward/bookmark/share/reload) off screen
**---> incorrect behavior**
I think the four icons should remain visible however I scroll the menu
![Screenshot_20200305-105956_Firefox Nightly](https://user-images.githubusercontent.com/40568887/75975593-b3bdf280-5ed0-11ea-9cec-9f71acb4d4ac.jpg)

* Android device: Galaxy A40, Android 9
* Fenix version: Today's

**Comment by mcarare** [comment]
Chrome and Firefox have the same behaviour on Android.
