### ISSUE TITLE
[Bug] Permission notification doesn't include permission name

### ISSUE THREAD

**Issue by caugner** [mozilla-mobile/fenix#8990]
## Steps to reproduce

1. Install old version of uBlock Origin
2. Update uBlock Origin to latest version
3. Wait for notification with title *uBlock Origin has a new update* and actions `Allow` and `Deny`

### Expected behavior

The notification should include the name of the permissions.

### Actual behavior

The notification only contains the text `1 new permission are required`:

![IMG_20200305_143104](https://user-images.githubusercontent.com/495429/75986323-27222d00-5eee-11ea-9b1f-f3c98e032bef.jpg)

### Device information

* Android device: Fairphone FP2
* Fenix version: `75.0a1-20200303...`

**Comment by Amejia481** [comment]
This will be fix with the new version of AC https://github.com/mozilla-mobile/android-components/pull/6262
