### ISSUE TITLE
[Bug] Login autofill / "Unlock Lockwise" button very unreliable

### ISSUE THREAD

**Issue by caugner** [mozilla-mobile/fenix#8993]
## Steps to reproduce

Visit a website for which Firefox/Lockwise have login data.

### Expected behavior

Firefox should:

1. (preferably) autofill the only login directly, or
2. (alternatively) show a select of available logins, or
3. (at least) always show a `Unlock Lockwise` button

### Actual behavior

1. Firefox almost *never* autofills logins directly.
2. Firefox *never* shows a select of available logins (except after unlocking Lockwise).
3. Firefox *often* doesn't show the `Unlock Lockwise` button (or maybe just not within the viewport).

### Device information

* Android device: Fairphone FP2
* Fenix version: `75.0a1-2020030408140`

**Comment by andrewshadura** [comment]
I think this is not specific to Firefox Preview, I observe the same behaviour in the stable Firefox and other apps too.

**Comment by maroonmoon13** [comment]
Saved logon info retrieval is pretty bad in ff. I have the same issue. I tried uninstalling Lockwise hoping the inbuilt password manager would work, but the is even worse. I never get prompted for any saved credentials

**Comment by ekager** [comment]
If there are multiple saved logins for a site we currently will not fill intentionally (see #5551 for future work on selecting logins)

Other issues with autofilling are possibly related to #12498 . Would help if you could check it out and let me know if you're seeing similar patterns!

**Comment by maroonmoon13** [comment]
Hi Emily,
These don't seem to cover what i am seeing. I never see ff populating any logins no matter if it's a mobile or desktop site. And I can verify the same behavior with single stored login sites too.
What I do see is that if a website has a login page with just email address to submit, I have to provide the email address. On the following page which requires password, that is auto filled. So I will say it works in some cases.

Cheers

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by ekager** [comment]
Gotcha! If you don't mind - when you get a chance, providing a list of some sites you can't autofill so someone could investigate further would be helpful. Thanks!

**Comment by maroonmoon13** [comment]
Hi Emily,
You want the list with lockwise disabled, correct?
My experience with login retrieval in general with FF has been sub par. The default system as well as Lockwise are very unreliable. ON top of that, with Lockwise, it is very confusing when you login and a prompt is shown to save.
Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by andrewshadura** [comment]
I’d not say anything improved much really — this still happens.

**Comment by andrewshadura** [comment]
Okay, it has — logins are often filled in when there’s only one option; when there are multiple, multiple taps and sometimes multiple unlocks are needed. E.g.:
* Tap the entry box. Nothing happens.
* Tap the entry box again. Nothing happens.
* Tap the entry box again, a menu shows with *Unlock Lockwise*.
* Unlocked Lockwise, the screen dims, nothing happens.
* Press back, back to the previous view, nothing happens.
* Tap the entry box. Nothing happens.
* Tap the entry box once more. A menu shows with *Unlock Lockwise*.
* Unlocked Lockwise, a list of logins appears in a menu attached to the original entry box.

**Comment by maroonmoon13** [comment]
Unfortunately the progress on Lockwise has been so slow, I was left with no choice but to move to bitwarden. The upside is that now I share a password manager across all browsers even on the desktop. I had high hopes and think I gave it a fair chance to improve.

**Comment by andrewshadura** [comment]
Well, none of the bugs in Lockwise are serious enough for me to move off something else.

**Comment by maroonmoon13** [comment]
@andrewshadura : How do you manage to sync them on desktop, if you don't mind answering. Its very cumbersome to sometimes to open firefox just to copy a stored password from lockwise.

**Comment by andrewshadura** [comment]
I always have Firefox open, so it’s not an issue for me.

**Comment by andrewshadura** [comment]
This bug is still valid, please reopen.

**Comment by maroonmoon13** [comment]
I have a feeling development on lockwise has been abandoned. I haven't received any app update since December. Begrudgingly i have moved to bitwarden . The upside is that now i can sync passwords across browsers and operating systems
