### ISSUE TITLE
[Bug] Lockwise suggested logins don't display logins "from this website" first

### ISSUE THREAD

**Issue by caugner** [mozilla-mobile/fenix#8994]
(Moved to: https://github.com/mozilla-lockwise/lockwise-android/issues/1184)

## Steps to reproduce

1. Have logins for `bar.example.com`, `foo.example.com` saved in Firefox/Lockwise.
2. Navigate to login form for `foo.example.com`.
3. Unlock Lockwise (if necessary, provided that the button is shown, cf. #8993).

### Expected behavior

The suggested logins should show the logins for the exact domain match first.

### Actual behavior

The logins seem to be alphabetically ordered and don't highlight logins "from this website" (as Firefox Desktop does).

### Device information

* Android device: Fairphone FP2
* Fenix version: `75.0a1-2020030408140`

**Comment by cadeyrn** [comment]
Wrong issues tracker? https://github.com/mozilla-lockwise/lockwise-android is for Lockwise issues…

**Comment by caugner** [comment]
@cadeyrn Does the order come from Lockwise?
