### ISSUE TITLE
[Bug]Keyboard is displayed after tapping second time the back button

### ISSUE THREAD

**Issue by sv-sdeiac** [mozilla-mobile/fenix#8997]
## Steps to reproduce
1. Open a page with a search bar(e.g. imdb.com);
2. Tap on the search button from the page to bring the keyboard;
3. Tap on the back button to hide the keyboard;
4. Tap again on the back button;

### Expected behavior
The homepage of the app is displayed.

### Actual behavior
The keyboard is displayed after the second back.

### Device information

* Android device: Google Pixel (Android Q).
* Fenix version: Firefox Preview Nightly 3/5 #20650606.
![20200305_165955](https://user-images.githubusercontent.com/40264165/75994182-3f507700-5f03-11ea-8404-795531c2f444.gif)

**Comment by AndiAJ** [comment]
Reproducible on the latest **`Nightly Build 201103`** using the following devices:
• Google Pixel 3a (Android 11)
• Huawei Mate 20 Lite (Android 10)
• OnePlus A3 (Android 6.0.1)
