### ISSUE TITLE
[Meta] Crash Reporting

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/fenix#9]
### User Story:
-As a user I can choose to submit a crash report when my browser crashes.
-As an engineer, I want to have sufficient data in the Crash Report to diagnose, reproduce, and solve an issue.

### Dependencies:
- [x] #267 - Integrate lib-crash component (and setup release build process)
- [x] Add Fenix as new product to Socorro ([Bug 1523284](https://bugzilla.mozilla.org/show_bug.cgi?id=1523284))

### Nice to have:
-Tooling/feature to make it easier for users to opt-in/help diagnose.

**Comment by pocmo** [comment]
The project is now listed in our sentry instance (mozilla mobile group) and I was able to send a test crash. Now I need to wire up all the build system stuff.

**Comment by pocmo** [comment]
Filed bug for creating product on Socorro:
https://bugzilla.mozilla.org/show_bug.cgi?id=1523284

**Comment by kbrosnan** [comment]
Is this on track? We need this to get crash data delivered to https://crash-stats.mozilla.com/home/product/Fenix
