### ISSUE TITLE
[Bug] Sites with anchored bottom bars will float when the toolbar is set to "Top"

### ISSUE THREAD

**Issue by colorsakura** [mozilla-mobile/fenix#9000]
## Steps to reproduce
设置工具栏为顶部
### Actual behavior
![Screenshot_2020-03-06-01-14-17-91_4f415facf3ad44f1a8c1a05936f33201](https://user-images.githubusercontent.com/32534829/76006824-0686c100-5f48-11ea-8a23-63d173730acc.jpg)
所有有底栏的网页，上滑时就会这样
### Device information

* Android device: ?Android10
* Fenix version: ?Build #2015726771

**Comment by AaronMT** [comment]
I see this on YouTube too. Re-summarizing.

**Comment by AaronMT** [comment]
(@snorp is this related to https://github.com/mozilla-mobile/fenix/issues/8768 ?)

**Comment by snorp** [comment]
Yes, I think it's the same problem.

**Comment by kbrosnan** [comment]
Closing as dupe
