### ISSUE TITLE
[Bug] Invisible address bar in Web App causes bottom elements to shift upwards

### ISSUE THREAD

**Issue by caugner** [mozilla-mobile/fenix#9001]
## Steps to reproduce

1. Configure Firefox Preview to show the address bar at the botom.
1. Open https://mobile.twitter.com/home and login.
2. Note how the Twitter tab bar is at the bottom of the page, above the Firefox address bar.
3. Open menu, select "Install" and add icon to the homescreen.
4. Open the web app from the homescreen icon.

### Expected behavior

There should be no Firefox address bar at all in the Web App, so the Twitter tab bar should be at the bottom of the page.

![Screenshot_20200305-181328_Firefox_Nightly](https://user-images.githubusercontent.com/495429/76007468-5fd1fe80-5f0e-11ea-8d53-dfcc3638ae99.png)

### Actual behavior

The Firefox address bar seems to be present (though transparent), and the Twitter tab bar is displayed above (instead of at the bottom).

![Screenshot_20200305-181229_Firefox_Nightly](https://user-images.githubusercontent.com/495429/76007499-6d878400-5f0e-11ea-84b2-77bded5ef35b.png)

### Device information

* Android device: Fairphone FP2
* Fenix version: `75.0a1-2020030408140`

**Comment by emilio** [comment]
cc @NotWoods

**Comment by andrewshadura** [comment]
The same (but even more visible?) happens with the bar placed on the top.
I think #9074 and #9004 may be dups of this.

**Comment by sivaraam** [comment]
> The same (but even more visible?) happens with the bar placed on the top

Exactly. I observed this issue recently. It's indeed more visible when the bar is placed at top.

**Comment by NotWoods** [comment]
I'm no longer able to reproduce this. Can QA double check if this issue still occurs?

**Comment by sivaraam** [comment]
FWIW, I'm unable to reproduce this too, in 5.0.0.

**Comment by caugner** [comment]
> I'm no longer able to reproduce this. Can QA double check if this issue still occurs?

Looks fixed to me, too, thanks!

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly Build 200622 from 6/22`** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)

► Video
![20200622-131919](https://user-images.githubusercontent.com/51314259/85278342-813f0200-b48d-11ea-92bc-4f025ef68590.gif)
