### ISSUE TITLE
[Bug] Floating scrollbar when dynamic adressbar disappears

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#9004]
## Steps to reproduce
goto github.com/mozilla-mobile/fenix
zoom in a little bit 
scroll down to hide adress bar
scroll sideways to make scrollbar appear
### Expected behavior
scrollbar appears at the bottom of the screen
### Actual behavior
![Screenshot_20200305-235328](https://user-images.githubusercontent.com/33252312/76012782-c7884980-5f0e-11ea-9b51-583cab0c99e5.png)

scrollbar appears floating, asif the adressbar never went away
### Device information

* Android device: Asus Zenfone
* Fenix version: Firefox nightly

**Comment by eliserichards** [comment]
Closing as duplicate of #9001
