### ISSUE TITLE
[Bug] xkcd.com rendered improperly on scroll

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#9005]
## Steps to reproduce
open xkcd.com
scroll up and down for a bit
### Expected behavior
![Screenshot_20200306-000019](https://user-images.githubusercontent.com/33252312/76013149-657c1400-5f0f-11ea-8e77-e56313973116.png)
[Chrome]

### Actual behavior
![Screenshot_20200306-000300](https://user-images.githubusercontent.com/33252312/76013450-cf94b900-5f0f-11ea-92c5-3fa8eb3f6a44.png)

The title is hidden due to a blue strip. infact, the rendering is very very different from chrome

### Device information

* Android device: Asus Zenfone
* Fenix version: Fenix Nightly

**Comment by hiikezoe** [comment]
I think this is another variant of https://github.com/mozilla-mobile/fenix/issues/8784.

**Comment by s-ankur** [comment]
@hiikezoe is it? that bug is about clipping at the bottom while this is about clipping at the top . maybe same though, idk

**Comment by hiikezoe** [comment]
I think so. If the clip size height is shorter than the correct one, it clips the top edge when user scrolls up the content.

**Comment by hiikezoe** [comment]
Confirmed this happens only with enabling WebRender, which means that this is a duplicate of https://github.com/mozilla-mobile/fenix/issues/8784.

**Comment by eliserichards** [comment]
Closing as dupe of #8784
