### ISSUE TITLE
[Bug] Vertical scrollbar misleading when bottom bar is hidden

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#9006]
## Steps to reproduce
releated to #9004
open any webpage
scroll to the bottom so that the bottom bar is hidden.
observe vertical scrollbar
### Expected behavior
scrollbar should be adjusted so that it propreely represents the percentage of page that has been scrolled
### Actual behavior
vertical scrollbar behaves as though the botton bar were still there and does not adjust to the changed dimensions of the screen
### Device information

* Android device: Asus Zenfone
* Fenix version: Fenix Nightly

**Comment by hiikezoe** [comment]
I believe this was fixed by https://bugzilla.mozilla.org/show_bug.cgi?id=1618432. 
@s-ankur, could you please paste the link in about:buildconfig?
Thanks!

**Comment by hiikezoe** [comment]
Oh I was misleading your comment. the vertical bar issue is https://bugzilla.mozilla.org/show_bug.cgi?id=1598978 which hasn't been fixed yet.
