### ISSUE TITLE
[Bug] Discord Links don't go to Discord App

### ISSUE THREAD

**Issue by Legionof7** [mozilla-mobile/fenix#9007]
## Steps to reproduce

If you go to a Discord link (i.e discord.gg/matrix) in preview and press Accept Invite, nothing happens.

### Expected behavior
This should open up Discord and send you to that Discord server.

### Actual behavior
Nothing happens.
### Device information

* Android device: Pixel 3a running Android 10
* Fenix version: 3.2.1

**Comment by kbrosnan** [comment]
This should work in Firefox Preview Nightly. 

#7331
https://bugzilla.mozilla.org/show_bug.cgi?id=1619344
https://bugzilla.mozilla.org/show_bug.cgi?id=1600704
