### ISSUE TITLE
Remind users that new add-ons are available

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/fenix#9010]
From @brampitoyo 

@betsymi and I had a meeting earlier today. Although our strings are not yet finalised – @betsymi will post them on this issue before the end of the week – we’ve decided on a few things to further simplify our notification system.

<img width="1680" alt="Screen Shot 2020-03-05 at 12 27 42 PM" src="https://user-images.githubusercontent.com/51007/75936667-ac561380-5ee7-11ea-870c-080ef1be2987.png">

1. To minimise interruption and distraction, we’ve decided not to show a snackbar or CFR bubble on the browser view. Just using the notification dot is enough.
2. Instead, we’ll show a CFR bubble inside the main menu. This is the first string that Betsy is working on.
    - If the user has zero add-ons, the main menu item doesn’t go through the submenu. It goes directly to Settings.
    - If the user has at least 1 add-ons installed, the main menu item will open the submenu. From here, the Add-ons Settings page can be reached easily
3. In the Add-ons Settings page, there’s a space for “Not yet supported” add-ons. This is the second string that will be posted on this issue.

_Originally posted by @brampitoyo in https://github.com/mozilla-mobile/android-components/issues/5434#issuecomment-594969808_

**Comment by opusforlife2** [comment]
Same as #11326?

**Comment by brampitoyo** [comment]
Thanks a lot, @opusforlife2. Yes, this issue is the same as #11326. Let’s close it in favour of that.
