### ISSUE TITLE
[Bug]Re-opening a page after Force closing Fenix automatically navigates back to the previous page

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#9020]
## Steps to reproduce
1. Navigate to theverge.com and swipe down the page content
2. Force close Fenix from the App manager tray
3. Re-open Fenix and from the same tab navigate to Cnet.com and swipe down the page content
4. Force close Fenix from the App manager tray
5. Re-open Fenix and open the tab

### Expected behavior
Opens the correct website (cnet.com)

### Actual behavior
Automatically navigates back and opens the previously visited website. (theverge.com)

### Device information

* Android device: 
• Google Pixel 3a XL(Android 10)
• Google Pixel 3a (Android 9)

* Fenix version: Nightly Build #20660604 from 3/6

### Notes
Noticed while testing #6726 

Note reproducible on:
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)

► Video 
![20200306-110056](https://user-images.githubusercontent.com/51314259/76072791-4332d680-5fa1-11ea-9ea8-190f90931950.gif)

**Comment by topotropic** [comment]
@AndiAJ I couldn't reproduce this. Is it still an issue? Thanks!

**Comment by AndiAJ** [comment]
Hi @topotropic , yes, I've managed to reproduce it on the latest **`Nightly Build 201007`** using a Google Pixel 3a (Android 11)

► Video
![20201007-170553](https://user-images.githubusercontent.com/51314259/95342354-04ab2480-08c0-11eb-96ea-760a68d75b4c.gif)

**Comment by sflorean** [comment]
I wasn't able to reproduce this issue on Nightly 12/15 with Pixel 3 (Android 11), following the steps available.
