### ISSUE TITLE
[Bug]Open tabs animation issue after re-opening Fenix

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#9021]
## Prerequisites
Have a couple of open tabs.

## Steps to reproduce
1. Force close Fenix from the app manager
2. Re-open Fenix
3. Check the "Opene tabs" section

### Expected behavior
No animation problems

### Actual behavior
Flicker in the "Open tabs" section

### Device information

* Android device: 
• Google Pixel 3a XL(Android 10)
• Google Pixel 3a (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

* Fenix version: Nightly Build #20660604 from 3/6

### Notes

► Video Dark theme

![20200306-120640](https://user-images.githubusercontent.com/51314259/76074325-d967fc00-5fa3-11ea-8b00-1c577a87016e.gif)

► Video Light theme
![20200306-120733](https://user-images.githubusercontent.com/51314259/76074383-f1d81680-5fa3-11ea-9b64-08f28f24d7c9.gif)

**Comment by topotropic** [comment]
@AndiAJ is this still an issue? Thanks!

**Comment by AndiAJ** [comment]
No @topotropic ,re-checked it on the latest **`Nightly Build 200708 from 7/8`** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)

► Video
![20200708-145940](https://user-images.githubusercontent.com/51314259/86919030-3a5d3780-c130-11ea-9af2-f2e693a3d872.gif)

► Video
![20200708-145758](https://user-images.githubusercontent.com/51314259/86918723-c0c54980-c12f-11ea-90c6-bc75c8f6bada.gif)
