### ISSUE TITLE
[Bug]Pocket default top site doesn't work

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#9023]
## Steps to reproduce
1. From the Home screen tap and open the ![rsz_1rsz_screenshot_20200306-143719](https://user-images.githubusercontent.com/51314259/76084617-f3600980-5fb8-11ea-917b-a7db5e5cee50.png)"Top Articles" default top site.

### Expected behavior
Pocket is properly opened

### Actual behavior
HTTP/1.1429 Too Many Requests error message

### Device information

* Android device: OnePlus A3 (Andoid 6.0.1)

* Fenix version: 
•  Nightly Build #20660604 from 3/6
•  Fenix Beta 4.0.0-beta.4

### Notes
 ► Video
![20200306-143513](https://user-images.githubusercontent.com/51314259/76084444-92d0cc80-5fb8-11ea-8de7-76d2b3375665.gif)

**Comment by darkwing** [comment]
Isn't this just a website error?  I don't think this is Fenix-specific.

**Comment by ekager** [comment]
Yeah this is just a website error and seems to be working now! Closing
