### ISSUE TITLE
[Bug] The "Restore from file.." button is not working on the second time

### ISSUE THREAD

**Issue by DanielOrban** [mozilla-mobile/fenix#9025]
## Prerequisites
* uBlock Origin is installed and enabled in Fenix
## Steps to reproduce
1. Open the Fenix.
2. Navigate to "Settings-> Add-ons-> uBlock Origin->Settings".
3. Tap the "Restore from file..." button.
4. Return to the Settings and tap again the "Restore from file..." button.
### Expected behavior
The "Restore from file.." allows selecting a file to upload.
### Actual behavior
The "Restore from file.." is not working the second time.
### Device information
* Android device:
Samsung Galaxy S7 (Android 8.0.0)
Samsung Galaxy S7 Edge (Android 8.0.0)
* Fenix version:
Nightly 200306 (Build #20660605)
Beta 74.0.0-beta.3 (Build #20640913)

![The Restore from file  button is not working on the second time](https://user-images.githubusercontent.com/43445968/76088564-e8a97280-5fc0-11ea-8130-c73455c033a4.gif)

**Comment by csadilek** [comment]
So, the problem here is that restore doesn't work reliably yet, and the UI ends up in a bad state. If it worked you'd see a confirmation dialog (after selecting the file) and then the window will close. Let's continue the work in https://github.com/mozilla-mobile/fenix/issues/8155.
