### ISSUE TITLE
[Bug] Phishing & malware pages are not always blocked

### ISSUE THREAD

**Issue by softvision-miralobontiu** [mozilla-mobile/fenix#9026]
## Steps to reproduce
1. Open Fenix, and access http://testsafebrowsing.appspot.com/s/phishing.html website.

### Expected behavior
A "deceptive site issue" page is opened.

### Actual behavior
The page is opened but without the warning message.

### Device information
* Android devices: Xiaomi MiPad2 (Android 5.1), LG Nexus 4 (Android 5.1.1)
* Fenix version: Fenix Beta v4.0.0-beta.4, and 3/6 Nightly build
* Not reproducible on Fennec Beta 68.6b5
* Reproducible with ETP OFF also

![123](https://user-images.githubusercontent.com/40694158/76095254-a38b3d80-5fcc-11ea-99ae-6965b11a8d87.png)

**Comment by sv-ohorvath** [comment]
I can also reproduce on Android 7, a Nexus 9 tablet. this phishing test page is not returning an error. Same thing on https://www.amtso.org/check-android-phishing-page/

**Comment by sv-ohorvath** [comment]
Still reproducing on 79.0.5

**Comment by softvision-miralobontiu** [comment]
I did not encounter this issue lately.
Tested it again on the 1/4 Nightly build with Samsung Galaxy Tab A6 (Android 5.1).
I'll close this issue.

**Comment by sv-ohorvath** [comment]
I was able to reproduce it on a debug build, on 1/21, so I suppose it would reproduce on Nightly as well.

**Comment by Amejia481** [comment]
> I was able to reproduce it on a debug build, on 1/21, so I suppose it would reproduce on Nightly as well.

Could you share which device you were using?

**Comment by Amejia481** [comment]
As we rely entirely on geckoview for detecting which pages are safe to visit I think It will be good for the team to take a look to this bug  https://bugzilla.mozilla.org/show_bug.cgi?id=1688103

**Comment by sv-ohorvath** [comment]
> > I was able to reproduce it on a debug build, on 1/21, so I suppose it would reproduce on Nightly as well.
> 
> Could you share which device you were using?

A Pixel 2 emulator from Android studio, with Android 9.

**Comment by DimiDL** [comment]
With Oana's help, I can confirm that we don't show the malware testing page is because Google doesn't include the url in the database for mobile platforms.
I think we can close this bug because this is the expected result. If we see a page sometimes is blocked but sometimes is not, please file or reopen the bug again. thanks

**Comment by Amejia481** [comment]
Thanks @DimiDL!
