### ISSUE TITLE
Remove white line at the buttom of the toolbar

### ISSUE THREAD

**Issue by Moderpach** [mozilla-mobile/fenix#9028]
### Why/User Benefit/User Problem
In dark mode, when you surfing the website, there is a white line at the buttom of the toolbar. This is not as the same style as one in home page.
It is hard to see at these pictures, because the github website's background is white. But It is easy to find the problem, when you actually use the browser.

![Screenshot_20200307-003413_Firefox_Nightly-01](https://user-images.githubusercontent.com/34941512/76102958-c5f07b80-600b-11ea-9827-c77e0a465516.jpeg)
![Screenshot_20200307-001720_Firefox_Nightly-01](https://user-images.githubusercontent.com/34941512/76102965-c8eb6c00-600b-11ea-87a2-64528afb877a.jpeg)

### What/Requirements
Remove the white line at the buttom of the toolbar.
### Acceptance Criteria (how do I know when I’m done?)
As same as "Requirements"

**Comment by Dunexus** [comment]
Highlighted in https://github.com/mozilla-mobile/fenix/issues/7456#issuecomment-582343877
Note that the top one has been removed as part of https://github.com/mozilla-mobile/fenix/issues/7456 but not the bottom one.

As noted by @Moderpach , it is *not* present on homescreen.

**Comment by ekager** [comment]
Closing for #7266
