### ISSUE TITLE
[Bug] Building with local GeckoView cumbersome

### ISSUE THREAD

**Issue by snorp** [mozilla-mobile/fenix#9030]
## Steps to reproduce
Use the steps here to use a local GeckoView with Fenix: https://mozilla.github.io/geckoview/contributor/geckoview-quick-start#dependency-substiting-your-local-geckoview-into-a-mozilla-project

Later, update the local GeckoView and try to build/run Fenix with the changes.

### Expected behavior
Fenix runs with the new GeckoView

### Actual behavior
Fenix crashes because of some kind of packaging error. It seems that the native libraries from GeckoView are missing in the final APK.

### Device information
Emulator

* Android device: Emulator
* Fenix version: master

**Comment by ncalexan** [comment]
For what it's worth, I dug deep into this, and it's a bug deep in the Android-Gradle plugin's `MergeSourceSets` implementation.  What happens is that the `merged_native_libs` directory gets (correctly, I think) purged after the SNAPSHOT version updates, but the merger only recognizes the changed-as-in-content-hash-differs as needing to be written.  That means in most cases one only gets `libxul.so`, leading to the mozglue-related crash -- but if you work hard you can arrange any subset of libraries to be present.

Even coming up with an example project that shows this is non-trivial 'cuz there are two projects, snapshots, and publications involved, although I'll try to do it to narrow down the issue.

I can think of a few ways to work around this but none of them have panned out yet.

**Comment by ncalexan** [comment]
This should be addressed with [Bug 1627796](https://bugzilla.mozilla.org/show_bug.cgi?id=1627796) and its follow-ups.  See also https://mail.mozilla.org/pipermail/mobile-firefox-dev/2020-August/002519.html.
