### ISSUE TITLE
[Bug] Navbar should be forced visible when a navigation occurs

### ISSUE THREAD

**Issue by snorp** [mozilla-mobile/fenix#9031]
## Steps to reproduce
1) Open any scrollable page
2) Scroll enough to hide the navbar
3) Click a link

### Expected behavior
Navbar becomes visible in order to show that a navigation is occurring.

### Actual behavior
Navbar remains hidden

### Dependencies
Needs this AC API to be implemented: https://github.com/mozilla-mobile/android-components/issues/6048

**Comment by mcarare** [comment]
@snorp I believe this happens with bottom navbar ? With top navbar there is another issue: https://github.com/mozilla-mobile/fenix/issues/6976. I think these issues should be handled together, to obtain the same behaviour.

**Comment by sblatz** [comment]
We'll need to implement: https://github.com/mozilla-mobile/android-components/issues/6048

Also see: https://github.com/mozilla-mobile/fenix/issues/8768#issuecomment-592718468

**Comment by sblatz** [comment]
Closing as I used #9472 as the issue number instead :)
