### ISSUE TITLE
[Bug] Custom tab styling doesn't respect the "Open links in a private tab" setting

### ISSUE THREAD

**Issue by SL-Lee** [mozilla-mobile/fenix#9037]
## Steps to reproduce

1. Switch on "Open links in a private tab".
2. Switch the browser mode to normal browsing mode.
3. Close Fenix.
4. Open a custom tab from another app.
5. From the custom tab, press "Open in Firefox Nightly" under the triple dot menu.

**Alternative STR:**

1. Switch off "Open links in a private tab".
2. Switch the browser mode to private browsing mode.
3. Close Fenix.
4. Open a custom tab from another app.
5. From the custom tab, press "Open in Firefox Nightly" under the triple dot menu.

### Expected behavior

The styling of the custom tab follow the "Open links in a private tab" setting.

### Actual behavior

The styling of the custom tab depends on whatever mode Fenix is in before it is closed, rather than the "Open links in a private tab" setting.

* **For STR:** Custom tabs appear as **normal** custom tabs, but pressing "Open in Firefox Nightly" opens a **private** tab (which means it DOES NOT record history).

  ![](https://user-images.githubusercontent.com/45960387/76143493-ddcf0a80-60b2-11ea-9822-05421ddf2d19.gif)

* **For Alternative STR**: Custom tabs appear as **private** custom tabs, but pressing "Open in Firefox Nightly" opens it in a **normal** tab (which means it DOES record history -- hence may be related to #8716).

  ![](https://user-images.githubusercontent.com/45960387/76143494-e1fb2800-60b2-11ea-83b6-5671b983a20c.gif)

### Device information

* Android device: Oppo Reno 2
* Fenix version: Nightly 200307 06:00 (Build #20670606)

**Comment by anuraaga** [comment]
I have also been noticing this, where custom tabs have the styling of Firefox when it was closed. I don't use the setting "Open links in a private tab" but find this to be confusing. In particular, is the custom tabs actually a private tab? If it's only the styling, then it's scary to see the purple color on a non private session.

**Comment by SL-Lee** [comment]
> In particular, is the custom tabs actually a private tab?

If the "Open links in a private tab" setting is off, it isn't.

That's what makes this so concerning -- if they didn't know about the "Open links in a private tab" setting or unknowingly switched it off and exited Fenix with private mode on, this misleads users into thinking that they are using a private custom tab when they are actually not (which results in unwanted history being saved).

**Comment by SL-Lee** [comment]
Closing this issue as it does not reproduce anymore on **Nightly 200929 17:11 (Build #2015766795)**.
