### ISSUE TITLE
[Bug] After opening a new tab from History, moving back to the tabs tray/home screen briefly shows History list

### ISSUE THREAD

**Issue by Cheap-Skate** [mozilla-mobile/fenix#9038]
## Steps to reproduce
Tap tabs counter to go to home screen/tabs tray
tap 3 dot menu & History
(the History page appears)
Open any page from History
(A new tab opens)
Tap the tabs counter
The History page flashes briefly on the screen before the home screen/tabs tray appears
**---> incorrect behavior, IMHO the flash of History page is not helpful**

### Expected behavior
tapping the tabs counter should always immediately show the tabs tray/home screen, no flashes of other screens (eg History)

### Device information

* Android device: Galaxy A40, Android 9.0.0
* Fenix version: Today's

**Comment by mcarare** [comment]
This should be taken into consideration when implementing a fix for https://github.com/mozilla-mobile/fenix/issues/7356.

**Comment by AndiAJ** [comment]
**Not reproducible** anymore on the latest on the latest **`Nightly Build 201111`** using the following devices:
• Google Pixel 3a (Android 11)
• Huawei Mate 20 Lite (Android 10)
• OnePlus A3 (Android 6.0.1)
