### ISSUE TITLE
The tab icon should have a number indicating how many tabs are open

### ISSUE THREAD

**Issue by Lululalu** [mozilla-mobile/fenix#904]
![Open Tabs Counter](https://user-images.githubusercontent.com/5992746/55352235-63533f00-548e-11e9-994e-a10d29d6d211.png)
As an user I find it very, very helpful.

**Comment by vesta0** [comment]
Decision by Michelle and Tiff to indicate # of open tabs. Will need UX design before it can be sized. @lime124

**Comment by lime124** [comment]
@AmyYLee can you take a look at this please? thanks!

**Comment by pocmo** [comment]
FYI: There's a `ui-tabcounter` component. It's similar to the tab counter button in Fennec and it is used in Firefox Lite and the Reference Browser.

**Comment by AmyYLee** [comment]
I've attached a spec for the tab counter in the bug description. Let me know if you need anything else.

**Comment by bsurd** [comment]
This has now been verified by QA, private and normal tabs counters are kept separate.
