### ISSUE TITLE
[Bug] Undo Closed Tab - does not disappear

### ISSUE THREAD

**Issue by fredderson** [mozilla-mobile/fenix#9040]
## Steps to reproduce

Close any tab.

### Expected behavior

Popup asking to undo closed tab should automatically disappear.

### Actual behavior

Pop-up stays on the screen until you tap "undo". As long as you wait long enough the tab remains closed even after tapping "undo".

### Device information

* Android device: Galaxy Note 10 Plus
* Fenix version: 3.2.1

**Comment by cadeyrn** [comment]
Duplicate of #7799, fixed in the next update.

**Comment by fredderson** [comment]
Thanks! Sorry for the duplicate. I'll look more thoroughly next time. Cheers! 

-----Original Message-----
