### ISSUE TITLE
[Bug] Horizontal Scrollbar is Asymmerical

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#9043]
## Steps to reproduce
Zoom in to the maximum possible level on any page
scroll to the maximum possible on the left side then do the same for right side
observe horizontal scroll bar
### Expected behavior
scrollbar should have symmetrical range on either side
### Actual behavior
On left side ,scrollbar touches the edge of the screen 
![Screenshot_20200308-144316](https://user-images.githubusercontent.com/33252312/76159911-2e7b4d80-611d-11ea-932b-e1120ee1c39d.png)
On the right side, there is a gap 
![Screenshot_20200308-144334](https://user-images.githubusercontent.com/33252312/76159927-697d8100-611d-11ea-8102-6839fd5f3a27.png)

This asymmetry is always present but it is more visible while zooming in

### Device information

* Android device: Asus Zenfone
* Fenix version: Fenix Nightly

**Comment by s-ankur** [comment]
There is prrobably a similar problem with the vertical scrollbar but i cant aay for sure while #9006 remains

**Comment by emilio** [comment]
I think this is because we only hide one of the scrollbar buttons depending on scroll direction

**Comment by s-ankur** [comment]
Hi @emilio .
Could you explain what you mean by a scrollbar button here?

**Comment by emilio** [comment]
Gecko scrollbars are made of multiple DOM elements, which look like:

```
<scrollbar>
  <scrollbarbutton sbattr=scrollbar-up-top></scrollbarbutton>
  <scrollbarbutton sbattr=scrollbar-down-top></scrollbarbutton>
  <slider>
    <thumb></thumb>
  </slider>
  <scrollbarbutton sbattr=scrollbar-up-bottom></scrollbarbutton>
  <scrollbarbutton sbattr=scrollbar-down-bottom></scrollbarbutton>
</scrollbar>
```

I think, reading [the scrollbars css in GeckoView](https://searchfox.org/mozilla-central/rev/070a000dd49aac4a26147e137efcd91a728d13b8/toolkit/themes/mobile/global/scrollbars.css#57) that only one of those buttons gets hidden, but the others take up space even though they're not visible.
