### ISSUE TITLE
[Bug] Download Completed Notification is too intrusive

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#9044]
## Steps to reproduce
Download any file
### Expected behavior
Small nonintrusive notification appears. It does not affect browsing in any way and user can continue to do what they were doing before .Notification automatically disabled after a while or after interaction with the webpage. 
### Actual behavior
Large notification and dark screen intruding on usability especially if you plan to download many images continuosly
### Device information

* Android device: Asus Zenfone
* Fenix version: Fenix Nightly

**Comment by test2a** [comment]
Yes. Came here to say this. The popup should fade away say after 2 seconds like it does on ff proper

**Comment by liuche** [comment]
cc-ing @brampitoyo here from UX, if you want to address these. Our snackbars tend to be standardized, so may also just be something we won't plan to address.

**Comment by brampitoyo** [comment]
@s-ankur @test2a I agree with part of your proposal.

Agree. Our dialog is currently blocking you from doing any other action until you dismiss it (tap “x”). We should make this dialog non-blocking. In other words, let’s not show any scrim. This way, you’d be able to select, scroll, long-press, etc. on the site. You can proceed downloading the next file, or perform any other action.

Disagree. We shouldn’t change the form of our dialog. It shouldn’t be a snackbar that fades away after 2 seconds. What if you want to view the image later on, but not right after it finishes downloading? The only way to do this would be to swipe down to the Notification Centre, then select the downloaded file – not impossible, but inconvenient. By keeping the notification as a non-blocking dialogue, you can easily open the file, dismiss it, or continue doing your current task.

Thoughts?

**Comment by s-ankur** [comment]
Yeah I agree. Non blocking is whats really important to me, since it really affects the ability to download things in quick succession. But also I would definitely prefer if the dialog takes up less screen-space. 
Secondly, the dialog disappearing by itself would really be counterproductive, as you point out. What I can suggest is that instead of it being on a timeout, you could have it be dynamic, like the dynamic addressbar that we have now.  At least that is the way chrome does it, and it does feel a lot less intrusive that way.

**Comment by brampitoyo** [comment]
@s-ankur Sounds good. Here’s an updated “Download completed” notification that’s non-interruptive.

<img width="360" src="https://user-images.githubusercontent.com/51007/78515569-7075dd00-780a-11ea-803d-2228144f9e8a.png">

**Comment by codrut-topliceanu** [comment]
Changes from https://github.com/mozilla-mobile/android-components/issues/7050 have made the fix for this unstable at the moment. I will open a new issue where those problems can be solved after 7050 is done.

**Comment by codrut-topliceanu** [comment]
Will be fixed by https://github.com/mozilla-mobile/fenix/issues/11371

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly Build #200619 from 6/19`** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)

► Video
![20200619-145000](https://user-images.githubusercontent.com/51314259/85129913-a12bb700-b23c-11ea-94bf-bf4980260dad.gif)
