### ISSUE TITLE
[Bug] Cant exit private mode with pending downloads

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#9045]
## Steps to reproduce
go to private mode
download a large file
exit private mode
### Expected behavior
Can exit private mode
### Actual behavior
Cant exit without cancelling downloads or force closing
### Device information

* Android device: Asus Zenfone
* Fenix version: Fenix Nightly

**Comment by kglazko** [comment]
Cannot reproduce on a Nexus 5. QA, can you please check and see what devices are affected?

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly Build #21060608 from 4/15`** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)

► Video
![20200415-142238](https://user-images.githubusercontent.com/51314259/79332409-757f0e80-7f25-11ea-8cd4-af3ea6ecc191.gif)
