### ISSUE TITLE
[Bug] download notification shown as "filename.extension (null)"

### ISSUE THREAD

**Issue by Archaeopteryx** [mozilla-mobile/fenix#9046]
## Steps to reproduce
Likely: Download a file from a server which doesn't send the file size. (The one I used is internal.)

### Expected behavior
After the file has been downloaded, the notification reads "Download complete (null)" (have Fenix in German)

### Actual behavior
Either "Download complete" or "Download complete (X.Y KB)" 

### Device information

* Android device: Sony Xperia XZ2 Compact
* Fenix version: Nightly 200308 06:00 (Build #20680607), Sunday 3/8 @ 6:06 AM

**Comment by ksy36** [comment]
There is a similar message recieved when trying to save an image on twitter in https://github.com/webcompat/web-bugs/issues/53602. Example file: https://pbs.twimg.com/media/EZhMjC4XsAU2KtD?format=jpg&name=900x900 

I've tried downloading images from other websites as well and expirience the same issue.

**Comment by sflorean** [comment]
I reproduced this also on Nightly 6/9 with Nokia 6 (Android 7.1.1) and LG G7 FIT (Android 8) when downloading files from file-example.com (images, audio, video).

**Comment by Amejia481** [comment]
This will be addressed after this pr lands on https://github.com/mozilla-mobile/android-components/pull/7309 and the subsequent new version of AC gets updated.

**Comment by sflorean** [comment]
Verified as fixed on Nightly 6/11 with the following devices:
- Huawei MediaPad M2 (Android 5.1.1) 
- Nokia 6(Android 7.1.1) 
- LG G7 FIT (Android 8)
