### ISSUE TITLE
[Bug]Websites that are available as PWAs on Nightly are not added to home screen on first try on Fenix Beta

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#9049]
## Steps to reproduce
1. Navigate to Twitter.com
2. From the  ⋮ Main menu tap on "Add to Home screen"

### Expected behavior
The website is properly added after the first attempt to the devices home screen

### Actual behavior
The Website is added only after the second attempt.

### Device information

* Android device: OnePlus A3 (Android 6.0.1)
* Fenix version: Beta4.0.0-beta.5

### Notes
❗️ In some cases it work only after the third attempt or **only after the shortcuts name is changed**.
►Video
![20200309-112521](https://user-images.githubusercontent.com/51314259/76204946-01549b00-6202-11ea-920d-957b305929bd.gif)

**Comment by Diana-Rus** [comment]
Hi, I can reproduce this issue with Samsung Galaxy S8+ (Android 8) on build Firefox Beta Preview 4.1.0-beta 1 (Build #20720029) GV: 75.0-20200309155231.
Sites:
- twitter.com 
- yahoo.com.

Note: What I noticed is that for yahoo.com, after adding the second time to home screen the favicon is different - there seems to be a new brand.

Please check GIF:
![20200312-114352](https://user-images.githubusercontent.com/49859863/76508901-ccda1c80-6457-11ea-88a2-e2f1bf252875.gif)
