### ISSUE TITLE
[Bug]The tab drawer number is not centered when open Top Sites in Private Browsing

### ISSUE THREAD

**Issue by sv-sdeiac** [mozilla-mobile/fenix#9051]
### Steps to reproduce
1. Open the Homepage of the app;
2. Long tap on a Top Site page;
3. Select "Open in Private tab" button;
4. Observe the tab drawer.

### Expected behavior
The number is displayed without any issue.

### Actual behavior
The number is not centered.

Device information
Android device: Samsung Galaxy Tab S3 (Android 8).
Fenix version: 
- Firefox Preview Beta 4.0.0-beta.5;
- Not reproducible on Firefox Preview Nightly 3/9 #20690608;
 ![20200309_143350](https://user-images.githubusercontent.com/40264165/76213883-4c77a980-6214-11ea-91bb-cee2202bb447.gif)

**Comment by opusforlife2** [comment]
This isn't exclusive to Top Sites. I've had it happen when opening bookmarked links as well.

**Comment by softvision-miralobontiu** [comment]
I was not able to reproduce this issue on the 11/17 Nightly build with Samsung Galaxy Tab S6 (Android 10).
