### ISSUE TITLE
[Bug] Page element from e-bay is incorrectly displayed

### ISSUE THREAD

**Issue by Diana-Rus** [mozilla-mobile/fenix#9055]
## Steps to reproduce
1. Go to https://cart.ebay.com/ .
2. Inspect the magnifying glass element.

### Expected behavior
The magnifying glass icon is correctly displayed besides the create an account and cart icon.
### Actual behavior
The magnifying glass icon is incorrectly displayed, it is not aligned with the rest of the icons.
### Device information

* Android device: Samsung Galaxy Note9(Android 9), Samsung Galaxy S8+(Android 8), Sony Xperia Z5 (Android 7.0.0)
* Fenix version: Firefox Preview Nightly 200309 (Build #20690607) GV: 75.0a1-20200306094739

Please check screen:
![Screenshot_20200309-160251](https://user-images.githubusercontent.com/49859863/76220853-d88fce00-6220-11ea-83d1-df1e538a7517.png)

**Comment by AndiAJ** [comment]
Not reproducible anymore on the latest Nightly Build 201103 using the following devices:
• Google Pixel 3a (Android 11)
• Huawei Mate 20 Lite (Android 10)
• OnePlus A3 (Android 6.0.1)
