### ISSUE TITLE
[Bug] Certain emojis become ridiculously small while zooming in

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#9058]
## Steps to reproduce
on the github issues page, zoom in while paying attention to the "bug" 🐞 emoji
### Expected behavior
icons zoom in proportion to rest of the webpage 
### Actual behavior
When im still pinching the screen:
![Screenshot_20200309-215650](https://user-images.githubusercontent.com/33252312/76236052-ff033880-6223-11ea-9e7b-cc7422b4d492.png)

When I let go
![Screenshot_20200309-215659](https://user-images.githubusercontent.com/33252312/76235850-9ae07480-6223-11ea-8064-55d09e9595f2.png)
### Device information

* Android device: Asus Zenfone
* Fenix version: Fenix Nightly

Note: while writing this bug report I notice that the 🐞 emoji randomly swiches between these two sizes within the textbox

**Comment by kbrosnan** [comment]
This behavior is from the Gecko engine. Need a Bugzilla bug to fix this.

**Comment by s-ankur** [comment]
Possibly fixed

**Comment by s-ankur** [comment]
Closing as fixed
