### ISSUE TITLE
Add WebPush integration to Engine

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/fenix#9059]
Parent: https://github.com/mozilla-mobile/fenix/issues/771

We should add the integration class for Fenix [similar to R-B](https://github.com/mozilla-mobile/reference-browser/blob/master/app/src/main/java/org/mozilla/reference/browser/push/WebPushEngineIntegration.kt).

This adds supports for WebPush to Fenix. Sites that can send web push messaging should now be able to do so.

A sample demo site as seen in the screenshots below: https://gauntface.github.io/simple-push-demo/

<img width="1018" alt="output" src="https://user-images.githubusercontent.com/1370580/76251227-13900280-621d-11ea-8883-fdb47cec531b.png">

Please file bugs for sites that do not work and link it to the parent ticket if possible: Parent: https://github.com/mozilla-mobile/fenix/issues/771

**Comment by sv-sdeiac** [comment]
Verified as fixed using the latest version of Firefox Preview Nightly 3/10 #20700606.
Now, the Firefox Preview allows sending web push messaging.

Devices:
- Nokia 6 (Android 7.1.1);
- Xiaomi Mi 8 Lite (Android 9);
- Google Pixel (Android Q).
