### ISSUE TITLE
[webcontent] TfNSW trip planner displaying incorrect time

### ISSUE THREAD

**Issue by KazaHesto** [mozilla-mobile/fenix#9063]
## Site with issue and any steps to reproduce
Go to https://transportnsw.info/trip
Type any "from" and "to" stations, e.g. Central Station to Town Hall Station

### Expected behavior
Times for travel information are displayed correctly

### Actual behavior
Relative times are displayed correctly (Leaving X minutes) but times displayed are off by an hour (Showing 8:01 instead of 9:01)

### Does toggling Tracking Protection fix the issue? (Press the lock icon in the toolbar while on the site to see toggle)
No

### Can you reproduce in [Firefox for Android](https://play.google.com/store/apps/details?id=org.mozilla.firefox)?
Yes

### Can you reproduce in Chrome (or other non-Mozilla browser)?
No

### Device information
Essential PH-1
* Android device: 10
* Fenix version: Nightly 200309 06:01 (Build #2015727539)

**Comment by kbrosnan** [comment]
Sounds like a website or Gecko bug then.

**Comment by softvision-miralobontiu** [comment]
@KazaHesto are you able to reproduce this issue on the latest Firefox build?
Thank you!
