### ISSUE TITLE
Shortcut to close the current displayed tab

### ISSUE THREAD

**Issue by ericliou** [mozilla-mobile/fenix#9064]
### Why/User Benefit/User Problem
As a user, closing the current tab after I'm done viewing is a very frequent operation. Currently, two operations are needed to do that:
1) press the tab switcher button
2) find the tab I was viewing and swipe it (or tab the X)

The 2nd step is particularly cumbersome, because the target can be in a random position depending  where the current tab is ranked in the tab list.

Having the 2nd step without needing to judge where your finger should land would be a great improvement. But I'd like to suggest reducing the 2-step operation to a single one.

An idea would be swiping up the tab switcher button (having the address configured in the bottom) to a certain threshold with animation suggesting the tab being closed. Another one could be long pressing the tab switcher. Or even an X button on the address bar.

### What/Requirements
One single action to close the tab that's currently being viewed with muscle memory. The action should work even if the current tab have a history (e.g. where one press of back button doesn't close it, only goes back).

### Acceptance Criteria (how do I know when I’m done?)
When I can close the current tab with a single action while viewing the tab.

**Comment by Poopooracoocoo** [comment]
Chrome has been experimenting with a menu when you tab and hold on the tab switcher button. It shows close, new tab, new incognito tab. Firefox could do something similar

**Comment by topotropic** [comment]
@ericliou latest nightly offers the experience @Poopooracoocoo described above: longpress on tab switchter button and you get the option to close the tab you're on. I'll go ahead and close the issue. Feel free to open a follow up one if there's something missing from the experience from your point of view. Thanks!
