### ISSUE TITLE
Re-add Experiments in performant way

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#9066]
In #8056, we determined that the Experiments framework was unused for GA. However, we'd like to emphasize Experiments going forward so we should add it back in. 

### Acceptance criteria
- Work with Experiments team to add Experiments framework back into Fenix
- `Experiments.initialize` and any other related code is performant
- Integration into Fenix is performant (initialized on a background thread after visual completeness)

**Comment by emalysz** [comment]
By using the VisualCompletenessQueue, I reintroduced the code I removed in https://github.com/mozilla-mobile/fenix/pull/8396/files and did not see a significant change. It was 1ms faster than the current implementation (no experiments) on GeckoBetaFenixBeta variant, which can be attributed to noise.

**Comment by emalysz** [comment]
Moving to low priority because Fenix team said they have no plans to add them in at the moment.

**Comment by travis79** [comment]
FYI: [I have a PR for the service-experiments lib in android-components](https://github.com/mozilla-mobile/android-components/pull/6371) that moves nearly all of the initialization for Experiments off of the calling thread. From my initial profiling, it looks like it's a significant improvement in the sample app.  I'm in the process now of testing this in Fenix with a local build to determine how much it improves things there.
