### ISSUE TITLE
Gather telemetry on representative user experiences for performance testing

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#9069]
We'd like to have telemetry to know what a typical user session looks like so we're able to create performance tests that are representative of user experiences. For example, how many tabs do users typically have open? Perhaps we should run our startup & page load tests with that number of tabs.

### Acceptance criteria
- Identify a list of criteria we'd like to know about (consult ecsmyth for specific criteria and bdekoz for what's been implemented already on the gecko side)
  - I see https://github.com/mozilla-mobile/fenix/issues/9029 for collections
  - Migration: https://github.com/mozilla-mobile/android-components/issues/6196
  - Top-sites: https://github.com/mozilla-mobile/fenix/issues/8125
  - Startup: https://github.com/mozilla-mobile/fenix/issues/8803 (this issue is getting scoped down so I may file another one)
- List of criteria is posted for future reference (either in bug or on Performance gdrive)
- Then, EITHER (based on scope):
  - Do it all now: add telemetry for any criteria that doesn't exist
  - Parallelize: file an issue for each criteria we need to implement. These issues should have the same priority in the backlog as this issue.

---

@ecsmyth Please update the description if this doesn't match your expectations! If you have a list of criteria we'd want implemented, it'd be great if you could post it too.

**Comment by mcomella** [comment]
@ecsmyth Migration telemetry landed in https://github.com/mozilla-mobile/android-components/issues/6196 – can you validate that it meets your needs?

**Comment by pslawless** [comment]
What's left for us to tackle is Startup Telemetry (all others are done or in progress with other teams).

What we should focus on for Startup Telemetry:
1. Aligns with how we measure startup in CI (as close as we can realistically make them)
2. At granularity Vesta has defined (home screen, applink, custom tab) with how often it is cold vs warm (vs hot? not as important)
-- P1: "how was the app opened?" (home screen, applink, custom tab)
-- P1: cold vs warm
-- P2: "how long did it take to open?"

**Comment by mcomella** [comment]
>     1. Aligns with how we measure startup in CI (as close as we can realistically make them)

Will be handled in https://github.com/mozilla-mobile/fenix/issues/10069

>     2. At granularity Vesta has defined (home screen, applink, custom tab) with how often it is cold vs warm (vs hot? not as important)
>        -- P1: "how was the app opened?" (home screen, applink, custom tab)
>        -- P1: cold vs warm
>        -- P2: "how long did it take to open?"

These are filed as separate issues: I think this can be closed.

**Comment by mcomella** [comment]
> I think this can be closed.

There's an equivalent JIRA task – https://jira.mozilla.com/browse/FXP-471 – so I think we can discuss there if a meta is still necessary or helpful.
