### ISSUE TITLE
Crash monitoring/diagnosis

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/fenix#907]
### Why/User Benefit/User Problem

As a product owner, I want to see all instances of Fenix crashes and have accurate stats on types and frequency of crashes, so I can create a baseline for measuring product stability.

We learned during preparation for Fenix MVP that we need a holistic accurate view of crashes.
We also have [similar learnings](https://docs.google.com/document/d/1IQIWMb6adKbLq_e_zDi5nPxEMsnF2sV0y1_Nj_34exo/edit?ts=5c496581#) from Focus.

### Dependencies
#304
(Telemetry team)

### Acceptance Criteria (how do I know when I’m done?)
-I can look at the crash dashboard to get a holistic view of crash landscape
-I can measure crashes per version

**Comment by bbinto** [comment]
@vesta0 - would this be a request for a data scientist?

**Comment by sblatz** [comment]
@vesta0 is Sentry sufficient for this or are we wanting a different dashboard?

**Comment by vesta0** [comment]
Sentry is sufficient for MVP. There is work that the telemetry team is doing that we will be able to integrate later on in order to get a more holistic view. Marking this Blocked for now and moving it to post MVP backlog.

**Comment by vesta0** [comment]
@st3fan let's chat about this next week and determine actionable next steps.

**Comment by sblatz** [comment]
Tagging Stefan's work github: @sarentz

**Comment by liuche** [comment]
@Dexterp37 does Glean have new Crash Reporting capabilities?

Next steps here are to work w/ @vesta0 to figure out what crash reporting capabilities in addition to Sentry is desired, so we can come up with a plan.

**Comment by st3fan** [comment]
@liuche The crash ping that is being worked on by the Glean team is not meant as  a replacement for Sentry or to even have full crash report capabilities.

The goal of this crash ping, which only contains a crash count,  is to be used in combination with our other telemetry so that we can establish a crash ratio based on active users or sessions. That part still has to be determined.

I think we are pretty happy with Sentry and I would strongly advice against rolling our own.

**Comment by Dexterp37** [comment]
> 
> 
> @Dexterp37 does Glean have new Crash Reporting capabilities?

Hey Chenxia! We have landed mozilla-mobile/android-components#3099 and [here's the readme](https://github.com/mozilla-mobile/android-components/tree/master/components/lib/crash#sending-crash-reports-to-glean) for what it does. @pocmo highlighted a problem with it and we're working hard to iron it out before mozilla-mobile/reference-browser#835 can happen.

The tl;dr is that we added support in `lib-crash` to report the number of native crashes and unhandled exceptions through the Glean SDK [metrics ping](https://mozilla.github.io/glean/book/user/pings/metrics.html).

> The goal of this crash ping, which only contains a crash count, is to be used in combination with our other telemetry so that we can establish a crash ratio based on active users or sessions. That part still has to be determined.

The above statement is correct, except that the metrics themselves are sent through the standard `metrics` ping.

**Comment by lime124** [comment]
oops mistake!

**Comment by vesta0** [comment]
@liuche can this be closed?

**Comment by sblatz** [comment]
@liuche I'm closing this as I believe it's already in use (through Sentry and Google Play). Please re-open if needed :)
