### ISSUE TITLE
Older version of Firefox Preview for arm64 is listed under assets of the latest build

### ISSUE THREAD

**Issue by plrao72** [mozilla-mobile/fenix#9071]
## Steps to reproduce
Go to the releases page. Check the assets of the latest release

### Expected behavior
All the asset files should be of the latest version

### Actual behavior
The arm64 apk is the older 3.21 version

### Device information

* Android device: ?
* Fenix version: ?

**Comment by liuche** [comment]
Thanks for filing, fixed this!
