### ISSUE TITLE
[Bug] when the url bar is hiding a gap seem visible for a position fixed item

### ISSUE THREAD

**Issue by karlcow** [mozilla-mobile/fenix#9074]
## Steps to reproduce
1. Account created
2. go to https://m.vk.com/feed
3. scroll down slowly and observe in between the url bar and the site bar at the bottom.

### Expected behavior
no gap visible.

### Actual behavior
the gap in between the url bar going into hiding and the site bar with a position fixed at the bottom
This is very subtle.

### Device information

* Android device: 10.0 pixel 2
* Fenix version: Firefox Preview Nightly 200309 (🦎: 75.0a1-20200306094739)

**Comment by ayushi1998** [comment]
Can I be assigned this?

**Comment by karlcow** [comment]
* https://github.com/webcompat/web-bugs/issues/49727
* https://github.com/webcompat/web-bugs/issues/49594

**Comment by karlcow** [comment]
https://github.com/webcompat/web-bugs/issues/49599

**Comment by karlcow** [comment]
Probably https://github.com/webcompat/web-bugs/issues/49603

**Comment by eliserichards** [comment]
Closing as dupe of #9001
