### ISSUE TITLE
Add the possibility to search(search bar) any login in Saved logins section

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/fenix#9075]
### Why/User Benefit/User Problem
As a Fenix user, I want to be able to find any login fast and not to scroll through all the saved logins.
### What/Requirements
Add a search bar to the `Saved logins` section.
### Acceptance Criteria (how do I know when I’m done?)
The search bar is implemented in `Saved logins` section.

**Comment by cadeyrn** [comment]
Duplicate of #7087.
