### ISSUE TITLE
Switch to Reader mode

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/fenix#908]
### Why/User Benefit/User Problem
As a user I want to be able to view a site in reader mode with one click.
As a user I want to be able to go back to browser mode with one click.

### Dependencies
-Quick Action Bar #961 

### Acceptance Criteria (how do I know when I’m done?)
-I can access Reader mode button by swiping up on the Quick Action Bar
-I can tap on the "Read" action to open the current page in Reader mode (Read icon should then turn into a _close_ button)
-I can tap on the _close_ button in the Quick Action Bar to go back to browser mode (and see the Read icon again)

**Comment by yoasif** [comment]
Did the AC here change at some point?

> -I can tap on the "Read" action to open the current page in Reader mode (Read icon should turn blue and inverted to indicate that it’s been selected)
> -I can tap on the "Read" action again to go back to browser mode (Read icon should turn back to red)

Right now, the read icon goes away and the entire quick actions bar becomes a dedicated UI for reader mode and has a close button to exit. 

FWIW, I like the current in-app behavior but wanted to understand whether that was going to stay.

**Comment by bsurd** [comment]
@vesta0 could you please confirm https://github.com/mozilla-mobile/fenix/issues/908#issuecomment-490743916 if this is the desired implementation so that QA can update the TC's accordingly, verify and close this. 

#912 also needs a slight update to the AC if this is the case. 

I've looked through other issues in Git but didn't manage to find anything regarding these changes.

Thanks!

**Comment by vesta0** [comment]
@bsurd and @yoasif I have updated the AC to indicate that the current behaviour is intended. Thanks!

**Comment by softvision-miralobontiu** [comment]
Verified that the read icon goes away and the entire quick actions bar becomes a dedicated UI for reader mode and has a close button to exit, on the latest build 1.0.1920 (#11360657), with Sony Xperia Z5 Premium (Android 7.1.1), Google Pixel (Android 9), and HTC 10 (Android 8).
