### ISSUE TITLE
[Bug] uBlock Origin is not working after automatic update

### ISSUE THREAD

**Issue by jawadalkassim** [mozilla-mobile/fenix#9082]
## Steps to reproduce
launch Firefox and open any website
### Expected behavior
uBlock Origin blocking ads and showing numbers of blocked ads as it was in previous relases
### Actual behavior
ads showing in websites 
### Device information
Huawei Gr3 2017
* Android device: 8.0 oreo
uBlock Version : 1.25.2
* Fenix version: 
Nightly 200310 06:01 (Build #20700607)
36.0.0, 6e1631e4f
GV: 75.0a1-20200309091841
AS: 0.53.0

**Comment by jawadalkassim** [comment]
![Screenshot_20200310-155404](https://user-images.githubusercontent.com/48631694/76319122-69c97800-62e7-11ea-94a8-e8018d593219.jpg)

**Comment by Amejia481** [comment]
@jawadalkassim would you mind share in which version of uBlock are you? You can find it under `Settings` -> `Add-ons Manager `-> tap on `uBlock Origin` ->  `Details` - > Scroll to the bottom -> `Version`

**Comment by jawadalkassim** [comment]
uBlock Version : 1.25.2

**Comment by Amejia481** [comment]
We tested on various devices and we are not able to reproduce the issue. Do you mind sharing which sites are visiting?

**Comment by jawadalkassim** [comment]
I've uninstalled FF and Reinstalled again and install Ublock Origin and everything is fine , I don't know how .

**Comment by jawadalkassim** [comment]
![Screenshot_20200310-174045](https://user-images.githubusercontent.com/48631694/76330572-a94b9080-62f6-11ea-92ff-e3378625f6d8.jpg)

**Comment by cadeyrn** [comment]
I was not able to reproduce the issue with uBlock Origin 1.25.0. Now, after I received uBlock Origin 1.25.2, I have exactly the same issue as the issue opener.

OnePlus 7T Pro McLaren Edition / Android 10
Fenix latest version from 4.0 branch (revision 3dc4582fe08e7f8f9c61f0c21b102ab52567bf75)

**Comment by Amejia481** [comment]
@cadeyrn would you mind to killing the app and open it again?

**Comment by cadeyrn** [comment]
Killing the app via the Android recent apps screen does _not_ solve the problem.

**Comment by jawadalkassim** [comment]
Try Uninstall uBlock and installing it again.
@cadeyrn

**Comment by Amejia481** [comment]
@cadeyrn before uninstalling could you try the "force stop" button on the "App info"?

**Comment by Amejia481** [comment]
@cadeyrn this is the button that I mentioned
![image](https://user-images.githubusercontent.com/773158/76332235-7db0b200-62c6-11ea-8c08-98f7ffa6d59f.png)

**Comment by cadeyrn** [comment]
> before uninstalling could you try the "force stop" button on the "App info"?

I tried the "force stop" button, but without success.

**Comment by Amejia481** [comment]
Thanks for the report will be work on finding the root of the issue, I think so far the work around will be to uninstall sorry about that.

**Comment by colorsakura** [comment]
![Screenshot_2020-03-11-00-57-54-36_4f415facf3ad44f1a8c1a05936f33201](https://user-images.githubusercontent.com/32534829/76338230-5c39df80-6333-11ea-8ff7-05c991938671.jpg)

me too

**Comment by Amejia481** [comment]
Looks like disabling and enabling the add-on back is another workaround.
`Settings` -> `Add-ons Manager` -> tap on `uBlock Origin` -> Switch button

**Comment by cadeyrn** [comment]
Yes, uBlock Origin works again after disabling and enabling again. Uninstalling and installing the add-on did not help (I tried this before).

**Comment by Amejia481** [comment]
It looks like the issue could be on the GeckoView layer, I opened the below bug to investigate
https://bugzilla.mozilla.org/show_bug.cgi?id=1621503

**Comment by LittleAngelwings** [comment]
On my two devices uBO 1.25.2 works fine with the latest nighty-builds.
The only thing I did was to refresh the filter lists on uBO a few days ago. 
My devices are:

Huawei P smart 2017 (Android 9.1.0, Stock)
Samsung Galaxy Tab A6  SM-T580 (Android 8.1.0, Stock)

**Comment by ebalazs-sv** [comment]
Hi! The issue that was opened for investigating this, https://bugzilla.mozilla.org/show_bug.cgi?id=1621503, is verified as fixed. Due to that, this issue can be closed. Thanks!

**Comment by ebalazs-sv** [comment]
This is verified as fixed on 75.0.0-beta.2 GV 75 from 3/25 with Pixel 2 (Android 9).
Details in this issue: https://bugzilla.mozilla.org/show_bug.cgi?id=1621503#c15
I will move this to Done.
