### ISSUE TITLE
[Bug] Page layout-Products thumbnails are not displayed per two columns

### ISSUE THREAD

**Issue by Diana-Rus** [mozilla-mobile/fenix#9084]
## Steps to reproduce
1. Go to main.m.taobao.com.
2. Scroll on the page.
### Expected behavior
The thumbnails of the products are correctly displayed.
### Actual behavior
From the third section of the page, instead of having 2 column of thumbnails with the products there is only one.
### Device information

* Android device: OnePlus7T Pro (Android10), Google Pixel 3XL (Android 9), Samsung Galaxy S8+ (Android 8), Sony Xperia Z5(Android 7)
* Fenix version: Firefox Preview Nightly 200310 (Build #20700606) GV: 75.0a1-20200309091841

Samsung Galaxy S8+ (Android 8)
![20200310-163217-1](https://user-images.githubusercontent.com/49859863/76324095-363e1c00-62ee-11ea-863f-3a305c496738.gif)

OnePlus7T Pro (Android10)
![20200310-163956](https://user-images.githubusercontent.com/49859863/76324039-29212d00-62ee-11ea-9913-a22dafbb5f77.gif)

Google Pixel 3XL (Android9)
![20200310-164750](https://user-images.githubusercontent.com/49859863/76324909-57ebd300-62ef-11ea-9c3f-10d67a1dafa3.gif)

Note: With Google Pixel 3XL the issue is not reproduced.

**Comment by AndiAJ** [comment]
Not reproducible anymore on the latest Nightly Build 201103 using the following devices:
• Google Pixel 3a (Android 11)
• Huawei Mate 20 Lite (Android 10)
• OnePlus A3 (Android 6.0.1)
