### ISSUE TITLE
[Bug] Firefox preview doesn't support Webauthn but PublicKeyCredential return true

### ISSUE THREAD

**Issue by MockinAeon** [mozilla-mobile/fenix#9090]
## Steps to reproduce
Attempt to login a website using security key(webauthn) as two factor
### Expected behavior
show not support webauthn message based on a javascript block checking `window.PublicKeyCredential` which should be null/undefined.
### Actual behavior
It's not null/undefined which makes the app think it supports webauthn.
### Device information

* Android device: Multiple
* Fenix version: 3.2.1

As we are implementing two factor security key using webauthn, we have tested many browser on different devices. We tried firefox preview on Android, it seems `window.PublicKeyCredential` is returning something but not undefined, then our app render the wrong information but not showing the popup, which is confusing.

**Comment by kbrosnan** [comment]
Dupe #1340

**Comment by kbrosnan** [comment]
Though maybe Gecko should not advertise support when the UI has not been implemented. Might be worth a bug at https://bugzilla.mozilla.org/enter_bug.cgi?product=GeckoView
