### ISSUE TITLE
[Bug] Tab closed toast can't be dismissed

### ISSUE THREAD

**Issue by anuvindbhat** [mozilla-mobile/fenix#9093]
## Steps to reproduce
Close a tab from the "Open tabs" menu. This will create a "Tab closed" toast. Tap or swipe the toast (in any direction).

### Expected behavior
The toast will be dismissed.

### Actual behavior
The toast is not dismissed (happens sometimes).
Navigating to another page (like settings) before trying to dismiss it might make the bug occur more often. The toast can only be dismissed by tapping "undo" at this point.

### Device information
OnePlus 6T

* Android device: Android 10, Oxygen 10.3.2
* Fenix version: 3.2.1 (Build #20250350)

**Comment by anuvindbhat** [comment]
Might be related to #9092

**Comment by kbrosnan** [comment]
Dupe #8472. Fixed in 4.0 which is in the process of being rolled out.
