### ISSUE TITLE
[Bug]The avatar is not updated after changing it

### ISSUE THREAD

**Issue by sv-sdeiac** [mozilla-mobile/fenix#9097]
### Prerequisites
Make sure that the account has an avatar set.

## Steps to reproduce
1. Log in into Firefox account;
2. From Desktop, change the avatar;
3. Sync on both Desktop/mobile devices;
4. Observe the mobile account avatar.

### Expected behavior
The avatar is updated with the last change.

### Actual behavior
The avatar is not updated.

### Device information
Android device:
- Google Pixel (Android Q);
- Samsung Galaxy Note 10 (Android 9);
- Nokia 6 (Android 7.1.1).

Fenix version:
- Firefox Preview Nightly 3/11 #20710604

Notes: 
- The issue disappears after a re-login.

**Comment by rfk** [comment]
There's probably some push-notification plumbing we'll need to do on the appservices side to make this happen smoothly.

**Comment by ekager** [comment]
Bumping it down to S3 because I don't think this is a very common user case :)
