### ISSUE TITLE
View page in Reader mode

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/fenix#910]
### Why/User Benefit/User Problem

As a user I want to be able to view a site in reader mode, without non-relevant text, images, and ads.

### Dependencies

-[A-C Reader mode component](https://github.com/mozilla-mobile/android-components/issues/1346)
-[A-C Components wrapping WebExtensions](https://github.com/mozilla-mobile/android-components/issues/2243) 

### Acceptance Criteria (how do I know when I’m done?)

-I can view a page in Reader Mode, free of ads and irrelevant images and text. 
-I don't see the top and bottom app bars as I scroll down the page
-I see the top and bottom app bars as I scroll up the page

**Comment by softvision-miralobontiu** [comment]
Verified that the user:
- can view a page in Reader Mode, free of ads and irrelevant images and text,
- doesn't see the top and bottom app bars  the page is scrolled down,
- see the top and bottom app bars as the page is scrolled up,

on the latest build 1.0.1920 (#11360657), with Sony Xperia Z5 Premium (Android 7.1.1), Google Pixel (Android 9), and HTC 10 (Android 8).
