### ISSUE TITLE
[Bug] outdated "What's new" article highlighted

### ISSUE THREAD

**Issue by cadeyrn** [mozilla-mobile/fenix#9107]
### Steps to reproduce

1. start Firefox Preview after the update from version 3.2 to 4.0

### Actual behavior

The "What's new" menu item was highlighted and linked to the article about the new features of Firefox Preview 3.0.

### Expected behavior

Either

a) highlight the new features of Firefox Preview 4.0 instead of 3.0 or
b) don't highlight the menu item at all

**Comment by cadeyrn** [comment]
@liuche The same happened after the update from Firefox Preview 4.3 to 5.0. This time the "What's new" article highlights the new features from **Firefox Preview 2.0** (!) instead of 5.0…

Please consider disabling the highlighting of tthe menu item if it's not possible to deliver current content. To show nothing is really better than showing wrong content…

**Comment by liuche** [comment]
Sorry about that! There was a bug on our end in updating the site, but it should be fixed now. Thank you for reporting it!

**Comment by cadeyrn** [comment]
@liuche I can confirm that it works correctly for en-US, but it still redirects to the "What's new" article for Firefox Preview 2.0 if the language is German ("de"). If it's a SUMO issue is there a better place to report this?

**Comment by jonichan** [comment]
> @liuche I can confirm that it works correctly for en-US, but it still redirects to the "What's new" article for Firefox Preview 2.0 if the language is German ("de"). If it's a SUMO issue is there a better place to report this?

Thanks for reporting this, @cadeyrn . It's showing up as 5.0 for me in German. Is it still showing up as 2.0 on your end?

**Comment by cadeyrn** [comment]
It works now, thanks!
