### ISSUE TITLE
[Menu] The notification dot is still visible in the 3-dot menu (faintly)

### ISSUE THREAD

**Issue by AmyYLee** [mozilla-mobile/fenix#9109]
The notification dot is still visible in the 3-dot menu (faintly) when sync account is disconnected. 

<img width="758" alt="Screen Shot 2020-03-11 at 16 30 34" src="https://user-images.githubusercontent.com/5992746/76461119-aa8fc280-63b5-11ea-9ed3-901b988fd6f7.png">

@softvision-miralobontiu wrote:

> …the three-dot icon, the yellow overlay + dot, it is not removed, on light theme is barely visible.

Let’s remove the yellow overlay and dot from all themes. @AmyYLee and I agreed that this issue doesn’t need a special notification dot. The yellow warning on its own will be enough.

_Originally posted by @brampitoyo in https://github.com/mozilla-mobile/fenix/issues/7504#issuecomment-593763767_

**Comment by abodea** [comment]
Verified as fixed on the latest Nightly 4/22 with Google Pixel 4 XL (10).
Note that the notification dot is not displayed anymore.
