### ISSUE TITLE
Know when reader mode is available

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/fenix#911]
### Why/User Benefit/User Problem
As a user I want to know when reader mode is available on a given page.

### Dependencies
-[Expose state (A-C)](https://github.com/mozilla-mobile/android-components/issues/1385)

### Acceptance Criteria (how do I know when I’m done?)
-I can see the "Read" action when reader mode is available

**Comment by AmyYLee** [comment]
@vesta0 Let me talk to Bram to see what his thoughts are on this when he gets back.

**Comment by AmyYLee** [comment]
Hi, I've attached a spec for a visual indicator for reader mode when it is available. let me know if you have any questions. @csadilek 

![Reader View - Web Page - New Item Indicator](https://user-images.githubusercontent.com/5992746/57241129-4c0ff000-6ffe-11e9-9e73-c593aac83194.png)

**Comment by vesta0** [comment]
@bifleming I re-opened this issue as @AmyYLee updated the specs for reader mode visual indicator (see above). Need to add it to the new sprint on Wednesday.

**Comment by mheubusch** [comment]
@AmyYLee Just to confirm, the reader mode signal animates in on every page that is supported, not every website. So, nytimes.com will not get the reader mode animation, but an article page does.

**Comment by AmyYLee** [comment]
> @AmyYLee Just to confirm, the reader mode signal animates in on every page that is supported, not every website. So, nytimes.com will not get the reader mode animation, but an article page does.

That's correct. Only pages that have reader mode available.

**Comment by yoasif** [comment]
> Hi, I've attached a spec for a visual indicator for reader mode when it is available. let me know if you have any questions. @csadilek
> 
> ![Reader View - Web Page - New Item Indicator](https://user-images.githubusercontent.com/5992746/57241129-4c0ff000-6ffe-11e9-9e73-c593aac83194.png)

Is this supposed to happen on every page load where reader view is available, or the first time a user encounters a page that supports it (or even the first time it is available on a per domain)? 

I could see this getting annoying if someone generally has QAB collapsed. 

Also, what is supposed to occur if a user goes to a new page that *doesn't* support reader view - is QAB supposed to remain in the halfway open state?

**Comment by cadeyrn** [comment]
> Also, what is supposed to occur if a user goes to a new page that doesn't support reader view - is QAB supposed to remain in the halfway open state?

There is an ongoing discussion: #2245

> I could see this getting annoying if someone generally has QAB collapsed.

I agree. On one side the QAB must be partially visible to see the suggested indicator, on the other side it can quickly become annoying if it happens on every page with reading mode available. So I am not sure if the suggested indicator works in practise. As much as I like the QAB as a quick access to page related features, as little is it suitable for displaying an indicator. Maybe the _Fennec way_ with an icon in the address bar is more practicable…

**Comment by sblatz** [comment]
Looping in @apbitner since we're no longer showing a half expanded state.

**Comment by sblatz** [comment]
From @apbitner:

> I agree we shouldn't pop it open every time the user visits a reader mode compatible page. So instead of completely going back to the drawing board on this, what if we just pop it open with the notification dot just the _first_ time a user visits a reader mode compatible page?

**Comment by csadilek** [comment]
I think it's fair to assume that the feature will see lower usage if we stop advertising reader mode on every (suitable) page load. We'll have telemetry and should be able to compare the data we get to Fennec. Personally, I think we should add a notification to the toolbar similar to Fennec or Safari etc.

**Comment by pocmo** [comment]
We will have this discussion more often going forward: Progressive Web Apps are in the pipeline for after the MVP and they will also need some "hey you can install this as an app" indicator that we probably do not want to bury somewhere.

**Comment by sv-ohorvath** [comment]
@vesta0 @sblatz I don't think this is ready for QA yet (based on https://github.com/mozilla-mobile/fenix/issues/911#issuecomment-492830765), or is it? :)

**Comment by sblatz** [comment]
@sv-ohorvath that's correct, this ticket is not ready for QA yet.

**Comment by sv-ohorvath** [comment]
The dot on the reader icon doesn't appear on Android <7 devices like:
Nexus 5 (Android 6.0.1)
Sony Xperia Z2 (Android 6.0.1)
Mi 4i (Android 5.0.2)

Appears on devices like:
Galaxy Note 8 (Android 9)
P20 lite (Android 8)
Sony Xperia Z5 Premium (Android 7.1.1)

**Comment by sblatz** [comment]
Since this is not an MVP blocker, I'm moving this back to ready for dev to be properly prioritized. @vesta0

**Comment by vesta0** [comment]
@sblatz sounds good

**Comment by vesta0** [comment]
@sv-ohorvath ^^ :)

**Comment by sv-ohorvath** [comment]
@vesta0 Sorry I didn't get the first message :) closed and logged: #2962.
