### ISSUE TITLE
[Bug] New Collection Is Not Created until New Tab Page Is Shown

### ISSUE THREAD

**Issue by JNavas2** [mozilla-mobile/fenix#9115]
## Steps to reproduce

1. Open [Google News](news.google.com)
2. Open 1st article
3. Save to Collection
4. Add new collection
5. Close 1st article
6. Open 2nd article
7. Save to Collection

### Expected behavior
New Created Collection (Step 4) appears in list of Collections.

### Actual behavior
New Created Collection (step 4) does **not** appears in list of Collections,
will not be created until New Tab Page is shown.

[Video demo](https://youtu.be/YFaL29DXzLI)

### Device information
Device model: Google Pixel 3a (sargo)
Android version: 10 (QQ2A.200305.002)
Carrier: T-Mobile USA
Fenix Nightly #20711809

**Comment by s-ankur** [comment]
Not repoducible on latest nightly for me

**Comment by AndiAJ** [comment]
Not reproducible anymore on the latest Nightly Build 201103 using the following devices:
• Google Pixel 3a (Android 11)
• Huawei Mate 20 Lite (Android 10)
• OnePlus A3 (Android 6.0.1)
