### ISSUE TITLE
show Top Sites when user taps URL or taps "New tab" (search suggestions view, address bar sheet)

### ISSUE THREAD

**Issue by willfs84** [mozilla-mobile/fenix#9118]
In other major competing browsers like Chrome, Edge, Safari etc., when the user taps the URL or they tap "New tab", their Top Sites are there. This is important for UX efficiency. Firefox should also do this.

There's 2 different ways it can be done: 1 way is to show the Top Sites in a list (this is what Chrome does when you tap the URL when you're on a website), the other way is to show them as "tiles" (this is what Edge does when you tap the URL when you're on a website).

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-16237)

**Comment by Yves-Be** [comment]
Agreed, this is also the behavior of the current version of Firefox on Android.
It can even be made in a toggle, alongside the shortcuts toggle. I made a quick mock-up of it.
![Screenshot_2020-03-20-19-22-56-704_org mozilla fenix](https://user-images.githubusercontent.com/1593717/77195574-24c0f500-6ae2-11ea-8531-a6479b0ccffb.jpg)

**Comment by yoasif** [comment]
As mentioned by the reporter, this exists in...

Edge:

![signal-attachment-2020-04-27-230104_001](https://user-images.githubusercontent.com/152493/80442520-13d28300-88db-11ea-97d9-71c899aa612f.png)

Samsung Internet:

![signal-attachment-2020-04-27-230104_002](https://user-images.githubusercontent.com/152493/80442533-19c86400-88db-11ea-885b-55db57789da2.png)

Opera:

![signal-attachment-2020-04-27-230104_003](https://user-images.githubusercontent.com/152493/80442545-1e8d1800-88db-11ea-955d-fdd48dae604c.png)

**Comment by Cheap-Skate** [comment]
I have this issue too, I really miss the Fennec behavior (tap URL, tap Top Site). 

Hopefully the new Tabs Tray (landing soon?) will bring this sometime

**Comment by willfs84** [comment]
@UX, to follow up, please choose the list method (what Chrome does) instead of the tile one because with the list method, you can tap the arrow at the end of the Top Site to get to what you want faster and easier. For example, I want to go to a certain twitter account, I tap the URL, I tap the arrow beside the twitter.com entry (twitter is my #1 top site) and I can just type in the account name. But with the tile UI, you would tap the twitter tile, it would go to twitter.com, then you would have to tap the URL again, then drag the cursor to the end, THEN type in the account name. That's poor UX efficiency and kind of defeats the purpose of this feature, which is why I think Chrome went with the list UI.

**Comment by Neikon** [comment]
> 
> 
> @ux, to follow up, please choose the list method (what Chrome does) instead of the tile one because with the list method, you can tap the arrow at the end of the Top Site to get to what you want faster and easier. For example, I want to go to a certain twitter account, I tap the URL, I tap the arrow beside the twitter.com entry (twitter is my #1 top site) and I can just type in the account name. But with the tile UI, you would tap the twitter tile, it would go to twitter.com, then you would have to tap the URL again, then drag the cursor to the end, THEN type in the account name. That's poor UX efficiency and kind of defeats the purpose of this feature, which is why I think Chrome went with the list UI.

If you type the account name directly, Firefox will recommend the url you want.
![Screenshot_20201023-092015](https://user-images.githubusercontent.com/1765319/96968329-24be2300-1511-11eb-8069-d3451c54cc56.jpg)

**Comment by violasong** [comment]
I'm not officially working on this at the moment, but I've been giving it a lot of thought since it relates to other work on the homescreen, etc. Here are some explorations I've done, inspired by Firefox Desktop.

<img width="1203" alt="image" src="https://user-images.githubusercontent.com/55994/98580586-0ed09200-2275-11eb-8cc6-c81d8153f54d.png">

Bonus idea not shown here: Tapping Bookmarks, Tabs, or History will toggle those buttons and show a preview of those items in list form.

**Comment by Yves-Be** [comment]
I'm liking you proposal a lot Victoria!
When a user taps the address bar, he or she indicates that they want to navigate away from the current site. Showing the users' top sites followed by bookmarks, etc. would make most sense to them.
An empty dark overlay on the current page as it is implemented right now, provides no real value to the user.

**Comment by Cheap-Skate** [comment]
I like the middle proposal a lot (Top Sites, Bookmarks / Tabs / History underneath, Scan & Voice in the URL bar).

**Comment by Neikon** [comment]
> 
> 
> I like the middle proposal a lot (Top Sites, Bookmarks / Tabs / History underneath, Scan & Voice in the URL bar).

+1

**Comment by willfs84** [comment]
I take back what I said a few comments up, I think the tile UI is actually better after thinking about it more. And one of the reasons is that, with the tile UI you see 8 top sites, with the list UI you only get 6. Also, with the tile UI, you're seeing the same UI/layout as when you tap the new tab button, which is more consistent and familiar to the user. This is important.

**Comment by violasong** [comment]
Re: scan & voice in URL bar, that part of the mockup is currently underway in this bug: https://github.com/mozilla-mobile/fenix/issues/15357#issuecomment-714648008

Potential MVP for the rest of the mockup could be just to show the grid of top sites initially. CC: @brampitoyo @topotropic @vesta0 in case y'all have time to take a look at this.


<img width="383" alt="image" src="https://user-images.githubusercontent.com/55994/98901947-89fa9980-2469-11eb-929f-93fa3cdab954.png">

**Comment by Cheap-Skate** [comment]
I like the tab tray style because it reinforces the idea that actions (tap a top site or search) will affect the current tab. But what would happen when I type search text? Would the tab tray be replaced by a full screen of suggestions? Or would the suggestions appear in the tray?

**Comment by troxler** [comment]
Has this feature request been challenged properly yet? Will there be a way to configure it? Personally, I don't care about top sites at all. Instead, I would like to be able to use one of the UI suggestions from above to show my *bookmarks*.

Related: https://github.com/mozilla-mobile/fenix/issues/14929

**Comment by irahsu** [comment]
> Has this feature request been challenged properly yet? Will there be a way to configure it? Personally, I don't care about top sites at all. Instead, I would like to be able to use one of the UI suggestions from above to show my _bookmarks_.
> 
> Related: #14929

Agree, with top sites I have no way of knowing I'm what order the suggestions appear. Just show me my bookmarks, which I can customize to be what I think should be displayed! And let me re-order the bookmarks!

**Comment by willfs84** [comment]
> Has this feature request been challenged properly yet? Will there be a way to configure it? Personally, I don't care about top sites at all. Instead, I would like to be able to use one of the UI suggestions from above to show my _bookmarks_.
> 
> Related: #14929

There's already an option. Settings > Customize > Show most visited sites

**Comment by troxler** [comment]
> There's already an option. Settings > Customize > Show most visited sites

I know, but that is not what I meant with "a way to configure it". I'm not interested in Top Sites. Instead I would like to see my bookmarks on the home screen.

**Comment by violasong** [comment]
This will be reconsidered along with homescreen work in the new year. [Update re: homescreen](https://github.com/mozilla-mobile/fenix/issues/12065#issuecomment-739444613)

**Comment by jesus2099** [comment]
> Oh, and Fennec:

And Fennec is showing a three page screen:

> Top sites (big icons) | Bookmarks | History

Which, very conveniently contains everything needed

**Comment by willfs84** [comment]
I don't mean to be a pest but can we please get an update on what's going on with this? It's not that _low_ priority, pretty much every other phone browser does this and it's absence is harming the user experience. Surely it's not a big undertaking?

**Comment by ale82to** [comment]
it's a shame this still has not been sorted out and really only 8 top sites per page come on!!!

**Comment by willfs84** [comment]
@ Fenix dev team, you said you were prioritizing features and functionality that we're missing from Fennec before you will add new features/functionality. Well, this is one of them! This should be next

**Comment by willfs84** [comment]
Just incase UX wanted more confidence in the list vs tiles decision, it looks like Google is now switching to tiles UI too, they won't show top sites as a list anymore. I think it's safe to go ahead on this one...
https://www.androidpolice.com/2021/07/02/chrome-for-android-starts-showing-most-visited-site-tiles-in-the-omnibox/

**Comment by topotropic** [comment]
> show Top Sites when user taps URL or taps "New tab" (search suggestions view, address bar sheet)

This has been addressed. I'll close this issue but please feel free to create follow-ups or hop over to [connect.mozilla.org](https://connect.mozilla.org/) to discuss any feature ideas you might have with product and UX people. Thanks!
