### ISSUE TITLE
Customize Reader mode experience

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/fenix#912]
### Why/User Benefit/User Problem
As a user I want to be able to customize my reading experience.

### Dependencies
-[A-C Add engine API for WebExtension messaging](https://github.com/mozilla-mobile/android-components/issues/2243)

### Acceptance Criteria (how do I know when I’m done?)
-I can tap on the Appearance button in the Quick Action Bar to access customization options
-I can change background colour scheme to Dark, Light, or Sepia
-I can increase or decrease text size
-I can change my font

**Comment by softvision-miralobontiu** [comment]
Verified that the dedicated UI for reader mode has options to:
- tap on the Appearance button in the Quick Action Bar to access customization options,
- change background color scheme to Dark, Light, or Sepia,
- increase or decrease the text size, 

on the latest build 1.0.1920 (#11360657), with Sony Xperia Z5 Premium (Android 7.1.1), Google Pixel (Android 9), and HTC 10 (Android 8).

@vesta0 is changing the font text still desired?

**Comment by vesta0** [comment]
@softvision-miralobontiu yes changing the font is desired :)
