### ISSUE TITLE
[Bug] Send Tab doesn't work after sign-out, sign-in then cold booting app

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/fenix#9120]
## Steps to reproduce
1. Sign-in to Sync.
2. Test Send Tab.
3. Sign-out.
4. Sign-in again (the same account is fine).
5. Swipe away the app.
6. Re-open the app.
7. Test Send Tab

### Expected behavior
 - A tab should be received at step 2 and 7.

### Actual behavior
 - A tab should be received **only** at step 2.

### Device information

* Android device: Android 10
* Fenix version: Nightly (2020-03-11)

**Comment by jonalmeida** [comment]
Note for self: this is caused by the caching of the `fxaScope` in memory after the scope saved in the prefs is removed.

When the app is cold booted, we then have a mismatch between the newly generated scope and the one that was already subscribed.

This is a bit of a rare issue that probably only be seen by users/testers that have multiple FxA accounts or you're just an app services engineer (😄).

It might also explain https://github.com/mozilla-mobile/fenix/issues/9033.

**Comment by jonalmeida** [comment]
This is fixed in a-c and can be verified now.

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly Build #20860605 from 3/26`** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)

► Video
![20200326-091946](https://user-images.githubusercontent.com/51314259/77620986-32440800-6f44-11ea-9e2e-e38d65a9f480.gif)
