### ISSUE TITLE
[Bug] "Video can't be played because the file is corrupt" on funnyjunk.com (SM-N975U1)

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/fenix#9121]
From: https://www.reddit.com/r/firefox/comments/fh4ss9/is_the_desktop_version_of_firefox_comparable_to/fk96dek/

## Steps to reproduce

1. Visit https://funnyjunk.com/Boom/fXjiMsK/

### Expected behavior

Video plays.

### Actual behavior

![image](https://user-images.githubusercontent.com/152493/76483009-3f151780-63ec-11ea-9c11-dc5fff3ee1fd.png)

### Device information

* Android device: SM-N975U1
* Fenix version: latest nightly

**Comment by AndiAJ** [comment]
**Not reproducible** anymore on the latest on the latest **`Nightly Build 201111`** using the following devices:
• Google Pixel 3a (Android 11)
• Huawei Mate 20 Lite (Android 10)
• OnePlus A3 (Android 6.0.1)
