### ISSUE TITLE
Top sites to the left of me, space to the right, (here I am...really liking GeckoView)

### ISSUE THREAD

**Issue by SeburoSUMO** [mozilla-mobile/fenix#9123]
## Steps to reproduce

Open Firefox Preview Nightly

### Expected behavior

Top sites equally spaced in the middle of the screen so that it is easier for both left and right hand use.

### Actual behavior
![Screenshot_20200311-200844](https://user-images.githubusercontent.com/31939113/76501168-b2914600-6439-11ea-80de-23ff14f8d8b1.png)

### Device information

* Android device: Motorola Moto E5
* Fenix version: Nightly 200311 18:01 (Build #20711808) - mozilla.fenix.nightly & Nightly 200311 18:01 (Build #2015728017) - mozilla.fennec_aurora (migrated Nightly from Fennec to Fenix)

**Comment by ekager** [comment]
Going to close for #10281
