### ISSUE TITLE
[Bug] Share Menu - Inconsistent "Share with" window

### ISSUE THREAD

**Issue by Diana-Rus** [mozilla-mobile/fenix#9126]
## Steps to reproduce
1. Open app and go to wikipedia.org .
2. Trigger the text selection toolbar.
3. Tap on the "Share" option in portrait.
4. Rotate screen in landscape mode.

### Expected behavior
The "Share with" window is different from the other.
### Actual behavior
Different format of the "Share with" window.
### Device information

* Android device: Samsung Galaxy S8+ (Android 8)
* Fenix version:
  - Firefox Preview Beta 4.1.0-beta.1 (Build #20720029) GV: 75.0-20200309155231
  - Firefox Preview Nightly 200312 (Build #20720606) GV: 76.0a1-20200311041149

GIF - Firefox Preview Beta
![20200312-135621](https://user-images.githubusercontent.com/49859863/76519417-9e653d00-6469-11ea-92cc-aa3a8c958fa9.gif)
Note:
- The dark theme for the "Share with" menu for that screen is not applied.
- The same interface is present when the share option for URL is triggered.
Related to ticket: https://github.com/mozilla-mobile/fenix/issues/8759

**Comment by wurstsemmel** [comment]
Samsung Galaxy S9 with Android 10 (stock); Fenix Preview 4.0.0

In portrait mode not all share icons are shown in the share menu, in landscape mode more (all?) share irons are shown. E.g. WhatsApp is not shown in portrait.

**Comment by reinhart1010** [comment]
I can see the “inconsistent” part here. By default, Firefox Preview have implemented their own Share Sheet for sharing to other apps as well as send between connected Firefox instances (via Firefox Sync). The Web Share API now also triggers the custom Share Sheet as they likely contain the URL data to be shared.

The Share Sheet on the text selection, however, uses the Android system Share UI which differs between devices and manufacturers. The behavior of this UI is totally different than the custom one implemented on Fenix.

**Via Menu > Share**

![image](https://user-images.githubusercontent.com/17312341/82720602-1c05be80-9cdf-11ea-93d1-07bd3ccf8271.jpeg)

**Via text selection > Share**

![image](https://user-images.githubusercontent.com/17312341/82720609-32ac1580-9cdf-11ea-86a3-08c0cd3c9876.jpeg)

**Via Web Share API**

![image](https://user-images.githubusercontent.com/17312341/82720587-fbd5ff80-9cde-11ea-916c-3601ec7903e0.jpeg)
