### ISSUE TITLE
[Bug] Some snackbars are overlapped by the URL bar

### ISSUE THREAD

**Issue by sflorean** [mozilla-mobile/fenix#9128]
## Steps to reproduce
1. Open a webpage.
2. Open 3 dot menu.
3. Tap the bookmark button (save).

### Expected behavior
The snackbar is displayed right above the URL bar. 

### Actual behavior
"Bookmark saved" snackbar is overlapped by the URL bar.

### Device information
* Android device: Google Pixel 4(Android 10), Samsung Galaxy Tab S6 (Android 9), Xiaomi MiPad2 (Android 5.1).
* Fenix version: 4.1.0-beta.1.

### Notes
- Reproducible also for:
**Open Image in New Tab** 
**Copy Image location** 
**Open link from other app/private browsing**

* Not reproducible on 4.0.0 Release or Nightly 76.0a1 #20711811.

**Comment by sflorean** [comment]
Reproducible also when the URL link is copied.

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly Build #20940609 from 4/3`** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)

► Video
![20200403-114431](https://user-images.githubusercontent.com/51314259/78341999-440b5800-75a1-11ea-95bd-c08a4b77d35f.gif)
