### ISSUE TITLE
Add to Reading List

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/fenix#913]
### Why/User Benefit/User Problem
As a user, I want to be able to add a page that is open in Reader mode to my Reading List, so I can go back to it later. 

### Dependencies
-Library UI #177 

### Acceptance Criteria (how do I know when I’m done?)
-I can see the Reading list icon at the top of the page when in Reader mode
-I can tap on Reading list icon to add the page I have open in Reader mode to Reading list in my Fenix Library

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-16246)

**Comment by pocmo** [comment]
Maybe some interesting history: Fennec used to have a reading list too. The separate reading list was later removed and migrated to bookmarks. Nowadays if you bookmark a page that is in reader mode then those get show up in a folder in your bookmarks panel AND are available offline (not easy to discover)! If I remember correctly that change happened roughly at the same time that the reading list was removed from the desktop product too (Afaik there was even a not really exposed way to sync the reading list).

* Migrating reading list to bookmarks: https://bugzilla.mozilla.org/show_bug.cgi?id=1234314
* SUMO: https://support.mozilla.org/en-US/kb/save-web-pages-your-reading-list-firefox-android
* https://bugzilla.mozilla.org/show_bug.cgi?id=1234316

**Comment by bifleming** [comment]
@vesta0 not sure what is blocking this?

**Comment by kbrosnan** [comment]
We don't have any plans to pursue this currently.
