### ISSUE TITLE
[Bug] Make Home -> Search & Browser -> Search animation play nicely with top toolbar

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#9132]
Currently when a user has a top toolbar enabled, the animation looks a bit odd. We should just do a cross fade in this case instead of doing "fade_in_up.xml"

![animation looks odd 2020-03-12 10_38_37](https://user-images.githubusercontent.com/4400286/76549427-a6af7f00-644d-11ea-91a3-79bf526313e3.gif)

**Comment by ahmedmamdouh13** [comment]
can i work on this issue?

**Comment by sblatz** [comment]
@ahmedmamdouh13 go for it 😄 please let me know if you run into any issues!

**Comment by ahmedmamdouh13** [comment]
Thank you for the opportunity 🙏

**Comment by ahmedmamdouh13** [comment]
hey, i made a PR but I'm not familiar with TaskMaster.yml.

should i do something for the message appearing in the end of the PR?

Thank you!

**Comment by sflorean** [comment]
Tested and verified, following the same steps as in the description, on Nightly build 200331 with Nokia 6 (Android 7.1.1), Xiaomi Mi Pad 2 (Android 5.1) and Samsung Galaxy Note 10 (Android 10). 

@sblatz @ahmedmamdouh13 could you please take a look at the video and confirm that the animation for "Search or enter address" is the expected one? Thank you. 

![20200331_164150](https://user-images.githubusercontent.com/58466444/78035280-8d756080-7371-11ea-8e5a-41af4d0e66ad.gif)

**Comment by ahmedmamdouh13** [comment]
@sflorean yes.

**Comment by sblatz** [comment]
Thanks for your help on this @ahmedmamdouh13! 😄

**Comment by ahmedmamdouh13** [comment]
@sblatz ohh, i mean thank you for letting me 😁, i would really like to be more involved if this is okay.
