### ISSUE TITLE
[Bug] Browser -> Home when keyboard expanded has a weird animation

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#9133]
The animation when the keyboard is showing and the user presses to go home from browser looks off because of how we animate the GV. An edge case so maybe not too big of an issue.

![weird animation 2020-03-12 12_37_15](https://user-images.githubusercontent.com/4400286/76560348-39581a00-645e-11ea-8ad8-69dd3f8cc2b3.gif)

**Comment by ekager** [comment]
Irrelevant with our new tabs setup
