### ISSUE TITLE
http://auborddufleuve.canalblog.com/ doesn't load Connexion is reinitialized

### ISSUE THREAD

**Issue by lhirlimann** [mozilla-mobile/fenix#914]
## Steps to reproduce
enter url http://auborddufleuve.canalblog.com/
site doesn't load.
### Expected behavior
Site loads
### Actual behavior
I get a connexion reset error - work on fennec  and desktop
### Device information

* Android device: Nexus LG 5x
* Fenix version: latest available as of now

**Comment by rpappalax** [comment]
Works for me
* Android device: Nexus 6P

**Comment by kbrosnan** [comment]
Works for me as well. Using a Pixel 3.

**Comment by lhirlimann** [comment]
Load properly over wifi. so I'll blame Orange my data provider.
