### ISSUE TITLE
Remove icons from tabs + collections empty state

### ISSUE THREAD

**Issue by topotropic** [mozilla-mobile/fenix#9140]
### Why/User Benefit/User Problem
Icons are used throughout the app as elements you can interact with, tap on and something happens. On home we use the multi-task icon and collection icon in the empty state but both are not interactive. This is potentially confusing.

### What/Requirements
- remove multitask icon from Open tabs empty state message
- remove collections icon from Collection empty state message

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly Build #20800605 from 3/20`** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S6 (Android 7)
• OnePlus A3 (Android 6.0.1)

► Comparison Nightly Build #20780606 3/18 (LEFT) VS Nightly Build #20800605 3/20 (RIGHT)
![rsz_okoktabz](https://user-images.githubusercontent.com/51314259/77142359-8785a280-6a88-11ea-827f-0471d5a2879e.png)
