### ISSUE TITLE
[Bug] Added search engine no longer displayed if it was previously undo and the browser was restarted

### ISSUE THREAD

**Issue by sflorean** [mozilla-mobile/fenix#9143]
### Prerequisites
IMDb is added as a custom search engine.

### Steps to reproduce
1. Delete IMDb (search engine settings).
2. Tap on UNDO.
3. Close and reopen the browser.
4. Perform a search.

### Expected behavior
IMDb is displayed in the list of engines available.

### Actual behavior
IMDb is not available. 

### Device information
* Android device: OnePlus A3 (Android 6.0.1), Xiaomi MiPad2 (Android 5.1), Huawei P9 Lite (Android 7).
* Fenix version: Fenix Beta 4.1.0-beta.2, Fenix Nightly Build #20730607 from 3/13.
### Notes
Reproducible also when IMDb is set as the default search engine after step 2 and with other sites.
 ![20200313-131218](https://user-images.githubusercontent.com/58466444/76616879-b2727280-652d-11ea-92db-1039510e2a58.gif)

**Comment by Diana-Rus** [comment]
HI, reproduce the issue with Google Pixel 3 XL (Android 9) on Beta 4/29.

**Comment by AndiAJ** [comment]
**Not reproducible** anymore on the latest **`Nightly Build 201117`** using the following devices:
• Google Pixel 3a (Android 11)
• Huawei Mate 20 Lite (Android 10)
• OnePlus A3 (Android 6.0.1)
