### ISSUE TITLE
[Bug] White screen when using back swipe to close Firefox Preview and reopening from 'Recents' 

### ISSUE THREAD

**Issue by adityamurugan** [mozilla-mobile/fenix#9144]
## Steps to reproduce
1. Close Firefox preview
2. Open external link in Firefox Preview
3. Use back button/back swipe to close Firefox Preview
4. Open Firefox Preview again from 'Recents'

### Expected behavior
Firefox Preview should open the home page without any white screens

### Actual behavior
Firefox preview shows a blank white screen and need to be closed and opened to fix

### Device information

* Android device: Pixel 3a
* Fenix version: Nightly 200312 18.01

**Comment by sblatz** [comment]
Video of the behavior: https://www.reddit.com/r/firefox/comments/fhsemk/bugfenix_white_screen_when_using_back_swipe_to/

**Comment by adityamurugan** [comment]
There has been a small change in behavior but the bug is still there.

-The first back swipe closes the external link tab and the home page is shown
-The second back swipe minimizes the app to recents
-Now, trying to reopen the app from the recents drawer shows a white screen. 

Version: Nightly 200416 08:30 (Build #21070840)

**Comment by sflorean** [comment]
Tested on Nightly 6/12 and I was able to reproduce the issue on the following devices, **only** if the page from step 2 is opened in the browser:
- Google Pixel 3 (Android 11-beta)
- LG G7 FIT (Android 8) 
If I have more than 1 open tabs, the previous open tab is displayed after I open Nightly from Recents.

**Comment by abodea** [comment]
Verified as fixed on the latest **Nightly 6/23** with **Google Pixel 4 XL (10).**
Note that the home page was displayed in both cases when I had 1 or more tabs open.

![20200623-115708](https://user-images.githubusercontent.com/42831109/85384734-1bfd1680-b54a-11ea-87b0-3528048eb252.gif)
