### ISSUE TITLE
[Bug] Unsupported extensions have been enabled automatically

### ISSUE THREAD

**Issue by madb1lly** [mozilla-mobile/fenix#9145]
## Steps to reproduce
Unknown, because this happened without my action. However, I suspect that the add-ons were installed but not enabled during migration from Fennec Nightly to Fenix Nightly a few weeks ago (I use org.mozilla.fennec_aurora). Now, somehow, they have become enabled.

### Expected behavior
I presume that the correct behaviour would be for these add-ons to not be enabled. However, are you actually testing this via phased rollout?

### Actual behavior
Unsupported add-ons are installed and enabled: HTTPS Everywhere (appears to be working fine), Privacy Badger (appears to be working fine), Snooze tab (not working as far as I can tell, I get the GUI but nothing happens, but I think it was the same on Fennec), Voice Fill (nothing happens when selected, but maybe this was the same on Fennec), Wayback Machine (seems to work fine). Other add-ons may be installed and enabled but they don't appear in the 3-dots menu. Note that in the add-ons manager no add-ons are shown as enabled. See screenshots below.
![Screenshot_1584084311094](https://user-images.githubusercontent.com/25123631/76629178-2fa5e380-653e-11ea-9ab8-ef4ae6a2431e.jpg)
![Screenshot_1584084323685](https://user-images.githubusercontent.com/25123631/76629191-33396a80-653e-11ea-9efb-c9ce3dd137ab.jpg)

### Device information

* Android device: Nokia 8 running Android 9.
* Fenix version: Nightly 200311 18:01 (Build #2015728019) 36.0.0, 10e9924df

**Comment by ebalazs-sv** [comment]
@madb1lly Hi and thank you for this report! There is a fix for this issue on another ticket: https://github.com/mozilla-mobile/android-components/issues/6255. Due to that I will close this issue.
