### ISSUE TITLE
[webcontent] dailymail.co.uk won't display popup to choose Mobile UI in Fenix Nightly.

### ISSUE THREAD

**Issue by smartfonreddit** [mozilla-mobile/fenix#9157]
## Site with issue and any steps to reproduce

Open dailymail.co.uk homepage.

### Expected behavior

It should show a popup box with a prompt to choose between Mobile and Desktop designs.

### Actual behavior

No prompt is displayed. Desktop UI is used by default.

### Does toggling Tracking Protection fix the issue? (Press the lock icon in the toolbar while on the site to see toggle)

No.

### Can you reproduce in [Firefox for Android](https://play.google.com/store/apps/details?id=org.mozilla.firefox)?

No. It cannot be reproduced in Fennec and Fenix Preview. Only reproducible in Fenix Nightly.

### Device information

* Android device: Galaxy S10e

* Fenix version: 200313 18:01 

First observed >1 month ago in Fenix Nightly. See relevant WebCompat: https://github.com/webcompat/web-bugs/issues/48015

**Comment by s-ankur** [comment]
Hi, this seems to be fixed now, can you confirm?

**Comment by smartfonreddit** [comment]
> Hi, this seems to be fixed now, can you confirm?

Confirmed fixed.

**Comment by s-ankur** [comment]
I think it can be closed then
