### ISSUE TITLE
[Bug] %1$s on SafeBrowsing error page

### ISSUE THREAD

**Issue by cadeyrn** [mozilla-mobile/fenix#9158]
### Steps to reproduce

1. open https://testsafebrowsing.appspot.com/s/phishing.html

### Expected behavior

%1$s should be replaced with something else.

### Actual behavior

![Screenshot_20200314-152848](https://user-images.githubusercontent.com/1100614/76685240-749b4a00-6612-11ea-8df1-a57e73c4958b.jpg)

### Device information

* Android device: OnePlus 7T Pro McLaren Edition
* Fenix version: Fenix 4.0

**Comment by sflorean** [comment]
Verified as fixed on Nightly 200331. 
Devices: Nokia 6 (Android 7.1.1) and Xiaomi Mi Pad 2 (Android 5.1).
