### ISSUE TITLE
[Bug] Unknown protocol error when trying to sign-in to another app

### ISSUE THREAD

**Issue by glawrence** [mozilla-mobile/fenix#9159]
## Steps to reproduce
Set Firefox Preview as default browser
Load another app, in my case this is the Volvo On Call app
Tap options to sign in (in other app) and a Firefox Preview window is opened
Login as normal
### Expected behavior
I was hoping to get redirected back to the app and hence logged in
### Actual behavior
I got an "unknown protocol" error, both launching in private tab and regular
![Screenshot_20200314-155826](https://user-images.githubusercontent.com/1067355/76685948-80d1d800-660f-11ea-8cdd-7688f5ad5a52.png)
![Screenshot_20200314-160249](https://user-images.githubusercontent.com/1067355/76685950-83343200-660f-11ea-9c6e-a50cf8e9a00c.png)

I found an option called "Open links in apps" but this did not seem to help.

I think it is this config in Android that is not working
![Screenshot_20200314-160327](https://user-images.githubusercontent.com/1067355/76685951-83ccc880-660f-11ea-9827-d9033825d039.png)

In the end I had to change the default browser to Chrome to get signed in, which felt very wrong.

### Device information

* Android device: Sony Xperia (F3111) with Android 7.0
* Fenix version: 4.0.0 (Build #20691754)

**Comment by pavi2410** [comment]
Same here. It does Firefox Preview can open deep links/Android app links which usually incorporates custom protocol.

**Comment by kbrosnan** [comment]
Can you please try with https://play.google.com/store/apps/details?id=org.mozilla.fenix.nightly we have fixed several issues around this that might not have been part of 4.0.

**Comment by glawrence** [comment]
Hi @kbrosnan you were right! I tried the Firefox Preview Nightly you gave me the link for, which was as below and it worked a treat. Thank you very much and hopefully these changes will get released soon.

![Screenshot_20200315-190922](https://user-images.githubusercontent.com/1067355/76708750-3d4f9a80-66f1-11ea-9fec-05d8c9791671.png)
