### ISSUE TITLE
Save bookmark

### ISSUE THREAD

**Issue by bbinto** [mozilla-mobile/fenix#916]
As a user, I want to bookmark a page so I can go back to it later

### Why/User Benefit/User Problem
- save a web page for future retrieval and quick lookup

### What / Requirements
- ability in UI to bookmark/save a webpage

### Acceptance Criteria (how do I know when I’m done?)
- bookmark is saved and can be viewed/retrieved after.

**Comment by colintheshots** [comment]
I don't see anywhere to enter points on this ticket. I'll T-shirt size it a non-meta Large.
