### ISSUE TITLE
"Flight" of the bottom panel in web applications.

### ISSUE THREAD

**Issue by M0nArX** [mozilla-mobile/fenix#9164]
### Steps to reproduce
1. Add a site with a bottom panel as an application (eg "Instagram").
2. Watch.
### Expected behavior
Static position.
### Actual behavior
The "fly" of the site bar at the height of the hidden address bar.
### Device information

* Android device: 9.0 (PE, Xiaomi Note 5)
* Fenix version: 76.0a1-20200313095322

![Screenshot_20200315-173812](https://user-images.githubusercontent.com/7840836/76701800-41c28600-66e6-11ea-8c41-36180ef38506.jpg)
![Screenshot_20200315-173907](https://user-images.githubusercontent.com/7840836/76701801-47b86700-66e6-11ea-9861-da4f20462719.jpg)

**Comment by sv-sdeiac** [comment]
Hello, thanks for your reporting. 
This issue is tracked on the #8768 so I will close this ticket.
Thank you for your time.
