### ISSUE TITLE
[Bug] Find in page blocks tab switching

### ISSUE THREAD

**Issue by 532910** [mozilla-mobile/fenix#9165]
When you search something on the page tab switching becomes inaccessible. To switch to another tab you need to cancel and loose the current search that requires more actions and very inconvenient.

![image](https://user-images.githubusercontent.com/14617699/76705254-b221d500-66ef-11ea-8d66-49dbbbb60f44.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-16272)

**Comment by kbrosnan** [comment]
This is currently the intended design.

**Comment by 532910** [comment]
So the intended design is very bad.
I'd prefer to loose vertical screen size for search bar, rather than loose time on tab switching.
Moreover, closing the search looses search position. So you can't search something, switch to another tab, switch back and continue to the current search result or a next one.

**Comment by brampitoyo** [comment]
@532910 Would you prefer this behaviour?

- “Find in” bar sits above address bar (if address bar on bottom) or on bottom of screen (if address bar on top)
- When closed, page position is preserved

**Comment by 532910** [comment]
Really we shouldn't rely on my preferences, but on reasonable facts. The fist place should take the number of actions and amount of the finger movement. (For example, compare what you need to open a new tab in firefox and chrome mobile. Firefox wins here!)

> “Find in” bar sits above address bar (if address bar on bottom) or on bottom of screen (if address bar on top)

Yes, it would be nice.

> When closed, page position is preserved

Definitely!

**Comment by brampitoyo** [comment]
@532910 Thanks for the confirmation!

I will just add two more behaviours:

---

1. If toolbar is on bottom, the “Find in” bar sits above it

<img width="360" src="https://user-images.githubusercontent.com/51007/78095229-e78a2a80-7432-11ea-8098-ef5c128ddf1d.png">

---

2. If toolbar is on top, the “Find in” bar sits on the bottom of the screen

<img width="360" src="https://user-images.githubusercontent.com/51007/78095267-f7a20a00-7432-11ea-93d8-021bd77d3821.png">

---

3. When the “Find in” bar is selected and the keyboard is up, it should appear above the keyboard.

This means that we won’t show the toolbar when it’s positioned on bottom:

<img width="360" src="https://user-images.githubusercontent.com/51007/78095298-10aabb00-7433-11ea-91f2-faf0b97f93db.png">

But we will show the toolbar if it’s positioned on top:

<img width="360" src="https://user-images.githubusercontent.com/51007/78095403-54052980-7433-11ea-90b3-98883d262b1b.png">

---

4. The “Find in ” bar should be kept open until manually closed, even if toolbars are hidden (ie. when scrolling down the page).

---

5. When closed, page position should be preserved.

**Comment by 532910** [comment]
> This means that we won’t show the toolbar when it’s positioned on bottom:

Agree

> But we will show the toolbar if it’s positioned on top:

Don't agree, what's wrong with hiding the addressbar in both cases?

**Comment by brampitoyo** [comment]
@532910 wrote:

> …what's wrong with hiding the addressbar in both cases?

If the address bar is hidden by default when the “Find in” bar is shown, then doing actions other than search would take an extra step.

Let’s take your scenario as an example:

> …search something, switch to another tab…

If the address bar is hidden, then switching tabs would involve you having to scroll up the page to re-show the address bar.

But if the search bar is already shown, then you can simply tab the multi-tasking button.

Unfortunately, we must hide the bottom address bar because users would see two text boxes: one for the address bar, one for the “Find in” bar – but only the “Find in” text box is active. To prevent confusion, we can only show one.

But when the address bar sits on top of the screen, the text box that appear above the keyboard would only be the “Find in” bar. No confusion there. So we show both.

**Comment by Dunexus** [comment]
> If the address bar is hidden by default when > Unfortunately, we must hide the bottom address bar because users would see two text boxes: one for the address bar, one for the “Find in” bar – but only the “Find in” text box is active. To prevent confusion, we can only show one.

With "Find in page" placeholder and clearly different layout, I don't think keeping the address bar would be really confusing.

**Comment by 532910** [comment]
> If the address bar is hidden by default when the “Find in” bar is shown, then doing actions other than search would take an extra step.

Clear. But this also means it should be shown in both cases.

I'm also don't think this will confuse and possibly putting the find bar at the bottom in both cases will make it less confusing.

**Comment by liuche** [comment]
(This isn't really a tabs tray bug, so I'm going to remove Skittle)

**Comment by 532910** [comment]
I believe the stale fact is not a reason to close issues.

**Comment by 532910** [comment]
I believe the stale fact is not a reason to close issues.

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807144

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
