### ISSUE TITLE
[Bug] When I rotate the screen to landscape mode, the webpage zoom it

### ISSUE THREAD

**Issue by joelocandol** [mozilla-mobile/fenix#9167]
## Steps to reproduce
Rotate the screen to landscape mode 

### Expected behavior
The screen rotate and the webpage shouldn't be altered 

### Actual behavior
The webpage zoom it

### Device information
Oukitel c5 

* Android device: 7.0 
* Fenix version: nightly 200315

**Comment by sv-sdeiac** [comment]
Hi @joelocandol, I was not able to reproduce your problem using the latest version of Firefox Preview Nightly 3/17 #20770605. I tried a couple of sites and still can't reproduce it.

Devices:
- LG g7 fit (Android 8);
- Samsung Galaxy Tab S6 (Android 9);
- Google Pixel 3 (Android Q).

Can you provide some pages where you encounter the issue? Also, watch the Accessibility option from the Firefox Preview Settings and tell me if you have the "Zoom on all websites" option enabled.
I'll wait for your updates, thanks.

**Comment by joelocandol** [comment]
YouTube is the only where the problem happen for me (I think so), and yes, I have enable "zoom on all websites"

**Comment by sflorean** [comment]
@joelocandol is this still reproducible for you? Wasn't able to reproduce it on Youtube with "zoom on all websites" enabled. Thank you!

**Comment by AndiAJ** [comment]
**Not reproducible** anymore on the latest on the latest **`Nightly Build 201111`** using the following devices:
• Google Pixel 3a (Android 11)
• Huawei Mate 20 Lite (Android 10)
• OnePlus A3 (Android 6.0.1)
