### ISSUE TITLE
Delete Bookmark

### ISSUE THREAD

**Issue by bbinto** [mozilla-mobile/fenix#917]
As a user, I want to delete a previously saved bookmark

### Why/User Benefit/User Problem
- when a bookmark is not needed anymore, user wants to delete/remove it from the bookmark list

### What / Requirements
- ability to delete, including message that is has been successfully removed

### Acceptance Criteria (how do I know when I’m done?)
- bookmark won't show up anymore

**Comment by colintheshots** [comment]
I don't see a place to enter point values. I'll T-shirt size this a non-meta Small, since it doesn't require that much extra work after completing #916 and the relevant Android Component.
