### ISSUE TITLE
[Bug]The outline for Top/Bottom buttons has no colors

### ISSUE THREAD

**Issue by sv-sdeiac** [mozilla-mobile/fenix#9173]
## Steps to reproduce
1. On the onboarding screen scroll to the "Take a position" card;
2. Observe the outline of the Top/Bottom buttons.

### Expected behavior
There is a colored outline like the Light/Dark theme buttons.

### Actual behavior
The outline has no colors.

### Device information
Android device:
- LG g7 fit (Android 8);
- Samsung Galaxy Tab S6 (Android 9);
- Google Pixel 3 (Android Q).

Fenix version: Firefox Preview Nightly 3/16 #20760606.

#### Notes
It seems that this issue is a regression from #8258 since I can't reproduce the problem with the build: 2/10 #20410605.
![Screenshot_4](https://user-images.githubusercontent.com/40264165/76766591-e86b5d00-67a0-11ea-8e3d-392bcf51ebce.png)

**Comment by Mugurell** [comment]
Should be fixed by https://github.com/mozilla-mobile/fenix/issues/7606

**Comment by AndiAJ** [comment]
Not reproducible anymore on the latest Nightly Build 201103 using the following devices:
• Google Pixel 3a (Android 11)
• Huawei Mate 20 Lite (Android 10)
• OnePlus A3 (Android 6.0.1)
