### ISSUE TITLE
[Bug] Empty "Verified by" in site info pane

### ISSUE THREAD

**Issue by darkwing** [mozilla-mobile/fenix#9177]
## Steps to reproduce

1. Go to "https://testsafebrowsing.appspot.com/s/phishing.html"
2. Tap the broken lock icon

### Expected behavior

1. No "Verified by" block

### Actual behavior

2.  An empty verified by block

### Device information

* Android device: ?
* Fenix version: ?

![Screenshot_20200316-131515](https://user-images.githubusercontent.com/46655/76788702-6facd680-6789-11ea-9de9-e4f94f2e74c6.png)

**Comment by cadeyrn** [comment]
Duplicate of #8248.

**Comment by darkwing** [comment]
Closing as dupe.
