### ISSUE TITLE
[Meta] Bookmark folder management

### ISSUE THREAD

**Issue by bbinto** [mozilla-mobile/fenix#918]
[UX issue](https://github.com/mozilla-mobile/fenix/issues/242)

As a user, I want to organize my saved bookmarks so I can better find them

### Why/User Benefit/User Problem
- organize, group bookmarks into categories / folders

### What / Requirements
- potential solution is to allow users to create folders, delete folders and move bookmarks into these folders

### Acceptance Criteria (how do I know when I’m done?)
- Can save bookmark in folder, can remove
- Can create folder
- Can delete folder

**Comment by bbinto** [comment]
@topotropic - we couldn't find mocks that describe behaviours / actions on folders. Could you please provide more details.

**Comment by bbinto** [comment]
@mheubusch mentioned she'll break this down into user stories

**Comment by vesta0** [comment]
All issues listed under this meta have been implemented.
