### ISSUE TITLE
[Bug] Nightly App Updating Even When Auto-Updates Are Off

### ISSUE THREAD

**Issue by cbonacuse** [mozilla-mobile/fenix#9181]
I downloaded the below file to my device so that I could have a Fennec version of Nightly (68.5a1) in order to QA Leanplum messages on my phone using the Fennec app. When I downloaded, I went to Settings > Automatic updates > changed to "Never".

https://archive.mozilla.org/pub/mobile/nightly/2020/01/2020-01-20-18-04-35-mozilla-esr68-android-aarch64/fennec-68.5a1.multi.android-aarch64.apk

Every night, my app ended up updating to Fenix, even with "Never" selected for automatic app updates.

### Device information

* Android device: Google Pixel 3 OS 10
* Fenix version: 68.5a1 updated to Fenix (I deleted the app before I saw that latest Fenix version)

**Comment by kbrosnan** [comment]
Not a Fenix bug. This is OS behavior. You would need to go into the Google Play settings and set the app to not update. If you need help with this please reach out to the team.
