### ISSUE TITLE
Update shard parameter logic in ui-test.sh

### ISSUE THREAD

**Issue by AaronMT** [mozilla-mobile/fenix#9185]
Found in an investigation as to why providing a custom shard value in individual Flank values is being overwritten. Not sure this logically is entirely correct.

https://github.com/mozilla-mobile/fenix/blob/85d222d2b19c515d42208bebbaee45c062367d09/automation/taskcluster/androidTest/ui-test.sh

`
if [[ ! -z "$4" ]]; then
    num_shards=$4
fi`

And here we hard code `-1` as a passed in value https://github.com/mozilla-mobile/fenix/blob/master/taskcluster/ci/ui-test/kind.yml#L31

We should always use the shard value provided by individual Flank templates.

**Comment by ekager** [comment]
@AaronMT can we close this issue?
