### ISSUE TITLE
Fix intermittent fail on ReaderViewTest.verifyReaderViewAppearanceFontToggle UI test 

### ISSUE THREAD

**Issue by rpappalax** [mozilla-mobile/fenix#9188]
This test passes on API 28 but not on API 25 

```
 androidx.test.espresso.base.DefaultFailureHandler$AssertionFailedWithCauseError
androidx.test.espresso.base.DefaultFailureHandler$AssertionFailedWithCauseError: 'view has effective visibility=VISIBLE' doesn't match the selected view.
Expected: view has effective visibility=VISIBLE
Got: "AppCompatImageView{id=2131297023, res-name=notification_dot, desc=Highlighted, visibility=GONE, width=0, height=0, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=true, is-selected=false, layout-params=android.widget.FrameLayout$LayoutParams@a1d4c6d, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0}" 
```
https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7649116021264846893/executions/bs.86d4d41684492d44/testcases/1/test-cases

**Comment by AaronMT** [comment]
I think `assertReaderViewDetected` needs to wait until the appearance of the blue dot on the 3 dot menu (if it's still part of the feature).

**Comment by AaronMT** [comment]
Reader Mode entry/exit is changed in product so the test would need to be updated. This might not be an issue anymore. Reader mode tests currently blocked by https://github.com/mozilla-mobile/fenix/issues/11191

**Comment by sv-ohorvath** [comment]
#11191 was fixed but this test is flaky now on API 28: https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/8528873179388097367/executions/bs.c4b507f8aa6ea73/testcases/2/test-cases

**Comment by sv-ohorvath** [comment]
verifyReaderViewAppearanceColorSchemeChange failed 1 out of 2 tries with the same error, on Master 1/27: https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/5053320726265191428/executions/bs.c2ae71640776911a/testcases/1/test-cases

**Comment by sv-ohorvath** [comment]
Flaky twice on 1/18 on master: https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/5168568564435830562/executions/bs.7a27d4a15f6dbf2e/testcases/1/test-cases
