### ISSUE TITLE
Implement the bookmark widget for the home screen

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/fenix#9193]
### Why/User Benefit/User Problem
As a Fenix user, I want to be able to add the bookmark menu on the background, like this I will be able to access my saved bookmarks faster without accessing the browser.
### What/Requirements
Implement a new bookmark widget for the home screen like the search widget.
### Acceptance Criteria (how do I know when I’m done?)
The bookmark widget can be added like the search widget.
The bookmark widget can be scrollable and the size can be changed.
I tried to create a preview of how it can look.
![1](https://user-images.githubusercontent.com/42831109/76848595-a3046980-684c-11ea-8d88-6add959c1bb8.png)
![2](https://user-images.githubusercontent.com/42831109/76848598-a4359680-684c-11ea-917c-62126b4e4dc3.png)
![3](https://user-images.githubusercontent.com/42831109/76848600-a4359680-684c-11ea-9b8c-285b1ad54520.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-16290)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1808752

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
