### ISSUE TITLE
[Bug]Add-ons uninstall confirmation snackbar covers the nav bar

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#9196]
## Prerequisites
Have an opened website.

## Steps to reproduce
1. From the website, tap ⋮ Main menu
2. Open the "Add-ons Manager"
3. Install uBlock 
4. As soon as the confirmation snackbar is displayed, quickly tap the device back button

### Expected behavior
The "Successfully installed uBlock" confirmation snackbar should be displayed above the nav bar.

### Actual behavior
The "Successfully installed uBlock" confirmation snackbar is displayed over the nav bar.

### Device information

* Android device: 
• Google Pixel 3a (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S6 (Android 7)
• OnePlus A3 (Android 6.0.1)

* Fenix version: Nightly Build #20770606 from 3/17

### Notes
►Video
![20200317-135438](https://user-images.githubusercontent.com/51314259/76854649-2c6d6900-6858-11ea-99d4-405037dd5779.gif)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-16292)

**Comment by eliserichards** [comment]
Closing as dupe of #9856

**Comment by AndiAJ** [comment]
Still **reproducible** on the latest **`Nightly Build Nightly build 200615 from 6/15`** using the followsing devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)

**Comment by AndiAJ** [comment]
Still reproducible on **`85.1.3`** using a OnePlus A3 (Android 6.0.1)

**Comment by AndiAJ** [comment]
Reproducible on 93.0.0-beta.1 using a Google Pixel 3a (Android 11)

**Comment by LaurentiuApahideanSV** [comment]
The issue still occurs on Firefox 100.0.0-Beta.1.
### Devices used:
- Huawei MediaPad M3 (Android 7)
- OnePlus 6T (Android 9)
