### ISSUE TITLE
[Bug]The animation for selecting automatic theme is not fully displayed

### ISSUE THREAD

**Issue by sv-sdeiac** [mozilla-mobile/fenix#9198]
### Prerequisites
The Onboarding screen needs to be displayed.
The device theme needs to be different than the app theme.

## Steps to reproduce
1. Go to the "Choose your theme" card;
2. Change between the "Automatic" theme and the opposite theme.

### Expected behavior
There is a smooth transition and animation select button.

### Actual behavior
The animation select button is interrupted when you change the theme.

### Device information
Android device:
- LG g7 fit (Android 8);
- Samsung Galaxy Tab S6 (Android 9);
- Google Pixel 3 (Android Q).

* Fenix version: Firefox Preview Nightly 3/17 #20770605.
![20200317_143834](https://user-images.githubusercontent.com/40264165/76858572-5d519c00-6860-11ea-80b1-85cc92ffbbf2.gif)

**Comment by mcarare** [comment]
@sv-ohorvath This is indeed not the prettiest animation, but as the activity recreates in order to change the theme, there is not much we can do. There wouldn't be a point in waiting for the animation to finish.
