### ISSUE TITLE
[Bug] The Preview for the Search Widget Icon is displayed with the RC one for Nightly/Beta builds

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/fenix#9199]
## Steps to reproduce
1. Install Nightly or Beta.
2. On the device home screen tap and hold.
3. Access the Widgets section.
4. Observe the Nightly or Beta Search Widget preview icons.
### Expected behavior
The Preview for the Search Widget Icon should be displayed for the installed build Rc/Nightly/Beta.
### Actual behavior
The Preview for the Search Widget Icon is displayed with the RC one for Nightly/Beta builds.
### Device information

* Android device: **Google Pixel 4 XL (10)**
* Fenix version: **Nightly** 

![Screenshot_20200317-150544](https://user-images.githubusercontent.com/42831109/76859985-f5508500-6862-11ea-923f-0341743ea93b.png)

**Comment by abodea** [comment]
Note that for Nightly now the smaller preview icon elements are not fully displayed.
![image](https://user-images.githubusercontent.com/42831109/77326816-0990f800-6d23-11ea-848d-0f63bbb60e5f.png)

**Comment by AndiAJ** [comment]
Hi, **still reproducible** on the latest **`Nightly 201218`** using the following devices:
• Google Pixel 3a (Android 11)
• Huawei Mate 20 Lite (Android 10)
• OnePlus A3 (Android 6.0.1)

► Screenshot
![rsz_screenshot_20201218-122508](https://user-images.githubusercontent.com/51314259/102604294-a48cf600-412c-11eb-8dd9-f1f4bdf1fdeb.png)
