### ISSUE TITLE
[Meta] Share Intent System

### ISSUE THREAD

**Issue by bbinto** [mozilla-mobile/fenix#92]
### Why/User Benefit/User Problem
Share tool: Share information on the web
- As a user, I want to share information I find on the web with myself so that I can retrieve it later
- As a user, I want to share information I find on the web with others so they can access it

### What / Requirements
- I don’t need to sign up for an account
- Reinforce and support through existing sharing behaviours (e.g. email)
- The share function (e.g., button) must be in a color that has high contrast with its background.
- The share function must have an accessible label.

### Acceptance Criteria (how do I know when I’m done?)
Phase 1: Android default intent share integration

**Comment by st3fan** [comment]
The only sharing that is feasible for MVP is:

- Standard Android Share Sheet to share the current page you are looking at (or the link you long press on)
- "Send Tab" functionality to send a tab to one of your other devices (requires FxA)

The first is done and ready to be integrated - see the Reference Browser for guidance. The latter is a stretch Q1 OKR for the A-C team and heavily depends on the work the App Services team is doing for this. Initial discussions to understand all the moving pieces and work to break it down has started.

**Comment by bbinto** [comment]
I am aware that this might have to be scoped down, and I'm ok with it (i.e. only sharing tab/sessions via standard Android intent system (and send tab))

Maybe we should make this first about integrating with the intent system and next step, in a later milestone, focus on Send Tab integration?

**Comment by shorlander** [comment]
I would like to discuss how we prioritize this because friction-less sharing of complete workflows is one of the key pillars of sessions.

**Comment by jdragojevic** [comment]
A-S team [send-tab component](https://github.com/orgs/mozilla/projects/56#card-16349893) high-level tracking.

**Comment by jonalmeida** [comment]
> Maybe we should make this first about integrating with the intent system and next step, in a later milestone, focus on Send Tab integration?

We have good integration with sharing tabs via Android intents already and we're currently working on send tab via FxA.

Along with the project board that Janet has linked to above, the A-C project board for send-tab is here: https://github.com/orgs/mozilla-mobile/projects/19

**Comment by mheubusch** [comment]
Engineering - please review the items on this spreadsheet - this is a punchlist showing fit and finish issues blocking feature completeness.

https://docs.google.com/spreadsheets/d/14VQEpCQ9cbj2sFL0PR0oGdg09KFiqU2kPAl-Opt9m7w/edit?usp=sharing
