### ISSUE TITLE
[Bug]Menu and Setting icons are not proportionate with other icons

### ISSUE THREAD

**Issue by Scripterr** [mozilla-mobile/fenix#9205]
## Steps to reproduce

Reproduce in menu-
1. open webpage.
2. click 3 dot menu and observe.

Reproduce in settings-

1. open settings and observe.
### Expected behavior

All menu icons in 3 dot menu and settings are proportionate with other icons.
### Actual behavior

Add-on manager and open in app menu item are bigger than other icons in menu and settings.

![Screenshot_20200315-184208_1_1](https://user-images.githubusercontent.com/42364681/76874594-4ebab300-6867-11ea-9d7c-6c2802a5ebd9.png)
![Screenshot_20200604-125206_1](https://user-images.githubusercontent.com/42364681/83727203-37a08b80-a634-11ea-96cc-0b5565a73540.png)

### Device information

* Android device: 8.0.0
* Fenix version: nightly

**Comment by ekager** [comment]
@brampitoyo could you help us get mobile-specific icons for these assets? I think they were likely pulled from design.firefox which makes them a bit out of proportion to other mobile icons

**Comment by brampitoyo** [comment]
I can confirm that our mobile-specific icon does look smaller and more in proportion. Sorry about that.

Posting the asset below:
https://dzwonsemrish7.cloudfront.net/items/1K1P0p0T0h1g1W2G1j1v/extensions.svg

**Comment by Scripterr** [comment]
Hello @brampitoyo , I also think that `open in app` also have unpropotionate size could you please check , cause I'm only seeing new icon for add-ons from the link you have provided above.

**Comment by brampitoyo** [comment]
@Scripterr I just rechecked our design repository, and found that the “Open in app” icon does look larger than the rest. It occupies the 24x24dp grid fully, whereas other icons seem to have 2dp untouchable inner margins.

**Comment by ValentinTimisica** [comment]
So @brampitoyo based on your above comment, considering that the "Open in app" icon is bigger than the others, can you give us the correct icon?

**Comment by brampitoyo** [comment]
Here’s a version of `app.svg` with slightly reduced outer frame. This make it look optically correct when seen alongside other icons, although the untouchable inner margins had to be odd-numbered (3dp instead of 2dp) as a result.

https://share.getcloudapp.com/QwulYPPm

**Comment by ekager** [comment]
Thanks Bram! This is ready for eng to pick up and update the assets 👍

**Comment by ValentinTimisica** [comment]
Reopening for QA.

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly Build 200623 from 6/23`** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)

► ⋮ Main menu 
Now ➡️ Before
![rrrrsz_screenshot_20200623-135100](https://user-images.githubusercontent.com/51314259/85397546-61c2da80-b55c-11ea-919a-7d3a0c954a8e.png)


► Settings section
Now  
⬇️ 
Before
![rssssz_screenshot_20200623-135002](https://user-images.githubusercontent.com/51314259/85397554-64bdcb00-b55c-11ea-874a-3109d3f0bffd.png)
