### ISSUE TITLE
[Private Browsing] Remove dark purple background in system status bar

### ISSUE THREAD

**Issue by AmyYLee** [mozilla-mobile/fenix#9207]
Please remove the dark purple background in the system status bar in private mode. We don't have it appearing in light and dark themes. Thanks

<img width="415" alt="Screen Shot 2020-03-17 at 13 23 01" src="https://user-images.githubusercontent.com/5992746/76883451-8d923e00-6852-11ea-914c-29cbc52e3b87.png">

**Comment by sv-sdeiac** [comment]
Verified as fixed using the latest version of Firefox Preview Nightly 4/24 #21150607.

Devices:
- Samsung Galaxy Note 8 (Android 9);
- Google Pixel (Android 10).
