### ISSUE TITLE
In-product prompt

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/fenix#9208]
## User Story
- As a user, I want to know that my app is changing, so I can continue having a smooth user experience. 

### Acceptance Criteria
- When I open the app, I see a persistent prompt directing me to the new app.

### UX
Mocks w/ copy - https://share.goabstract.com/917b9c45-0031-4042-8fed-789a6611e50e?mode=design

**Comment by betsymi** [comment]
Clarification question: Does this mean when user opens Fennec, we direct them to Fenix?

**Comment by liuche** [comment]
Related: #6610 for Nightly

**Comment by vesta0** [comment]
@betsymi @apbitner here is the sumo link for the message: https://support.mozilla.org/1/mobile/%VERSION%/%OS%/%LOCALE%/sync-delist

Once we have added the mocks and strings to this issue, please mark it as `eng:ready` Thank you.

**Comment by apbitner** [comment]
Added in comment 0; mocks have current copy.

**Comment by sblatz** [comment]
QA, You can verify this by changing the `build.gradle` `applicationSuffix` https://github.com/mozilla-mobile/fenix/blob/master/app/build.gradle#L55 to the variations `fennec_aurora_`, `fenix_nightly`, `fennec`. Please message me if you have questions 😄

**Comment by abodea** [comment]
@sblatz I created 2 builds:
```kotlin
fennec_aurora -> The Firefox Nightly has moved prompt was correctly displayed after onboarding
```
```Kotlin
fenix_nightly -> No prompt displayed after onboarding.
```
Is this the intended behavior? Is the `fennec_aurora` the only variation that needs to be verified here?
Note that the `Get the new Nightly` redirected me correctly to the Play Store, and as I had it installed it opened the newly Nightly.

![Screenshot_20200427-132639](https://user-images.githubusercontent.com/42831109/80374250-12836500-889f-11ea-8a68-38916417aab4.png)

**Comment by sblatz** [comment]
@abodea can you also please check for `fennec` and the fenix nightly one is actually supposed to be `fenix.nightly` sorry, had a typo in my original comment! Those two versions should also have prompts :)

Thanks!

**Comment by abodea** [comment]
I retested this issue for more details please check the following:

- `.fenix.nightly` I was able to install the build and the prompt was correctly displayed when I tapped on the `Get Mozilla Firefox Browser` I was redirected to the play store and `Firefox Nightly for Developers (Early access) was displayed.

![Screenshot_20200430-150721](https://user-images.githubusercontent.com/42831109/80712612-dfd5a880-8afa-11ea-913e-98d49eea240f.png)

- `.fenix` I was able to install the build and the prompt was correctly displayed when I tapped on the `Get Mozilla Firefox Browser` I was redirected to the play store and `Firefox for Android Beta` was displayed.

![1a](https://user-images.githubusercontent.com/42831109/80712466-b288fa80-8afa-11ea-95f6-a13cd40f8ffe.jpg)


- `fennec_aurora` I was able to install the build and the prompt was correctly displayed when I tapped on the `Get the new Nightly` I was redirected to the Play Store and the `Firefox Nightly for Developers (Early Access) was displayed, with the option to open the browser (being the recently installed build with fennec_aurora).

![Screenshot_20200430-145111](https://user-images.githubusercontent.com/42831109/80712514-bb79cc00-8afa-11ea-895a-fe6c36071720.png)

@sblatz thank you for the help!
Based on my comment do you consider that there is more testing needed for this bug? 
I will remove the `qa:needed` until further notice.

**Comment by apbitner** [comment]
@sblatz I noticed on the long header that the text is running into the 'X', can we add some padding there, like this?
<img width="790" alt="image" src="https://user-images.githubusercontent.com/22176302/80726704-5efeb880-8aca-11ea-820b-7a9f3d612133.png">

Also, I know 'Learn more' has to be on its own line but we should add a little spacing between it and the button, otherwise I'm afraid there could be some mis-taps.
<img width="904" alt="image" src="https://user-images.githubusercontent.com/22176302/80726756-7047c500-8aca-11ea-9566-dd36e879bd42.png">

**Comment by sblatz** [comment]
@AndiAJ please verify the padding has been updated. Other than that, this should be good to go 😄

**Comment by abodea** [comment]
Hello, I re-tested this for more details please check the following:

- `.fenix.nightly`
 
![fenixnightly](https://user-images.githubusercontent.com/42831109/81048867-ca2efd00-8ec5-11ea-8448-5dc3e687d751.png)

- `.fenix.`

![fenix](https://user-images.githubusercontent.com/42831109/81049236-7b359780-8ec6-11ea-9cab-df3f7a73733c.png)

- `.fennec.aurrora`

![fennecaurora](https://user-images.githubusercontent.com/42831109/81049344-b3d57100-8ec6-11ea-94e7-757df219e23f.png)

@sblatz I do believe this looks good now, the pictures are form Google Pixel 4 XL (10).
