### ISSUE TITLE
New option "Auto open software keyboard on new tab page"

### ISSUE THREAD

**Issue by st3fan** [mozilla-mobile/fenix#9209]
> Taken from https://bugzilla.mozilla.org/show_bug.cgi?id=1619973

When I open a new tab in Fennec I get the usual new tab page with Top sites/Bookmarks/History but without the soft keyboard.

As most of the time I want to load a specific webpage or search for something, I always (at least 99% of the time) tap on the URL bar to bring up the keyboard. Searching with 2-3 keys is almost always faster - even for frequently used websites - than trying to find them from bookmarks. So an automatically popping up keyboard would be a bless for me.

I understand that for some people this might be disturbing - I see that there were already complaints (#885353) about automatically opening keyboard on New tab page but also about the non-focused URL bar (#908719) - I would request an option to enable this if someone wants such feature.

An option named something along "Auto pop-up keyboard on New tab page".

**Comment by mcarare** [comment]
@st3fan Is this supposed to be a feature request for Fennec or for Fenix? In Fenix we currently open the keyboard by default when opening a new tab.

**Comment by tylla** [comment]
I'm the original reporter.
This is absolutely Fennec (as written in the first line ;-)) so this is kinda misplaced...

**Comment by ekager** [comment]
This should be solved by the new search dialog behavior
