### ISSUE TITLE
[Bug] The "Add to Home Screen" button doesn't work on Firefox Nightly for Android.

### ISSUE THREAD

**Issue by st3fan** [mozilla-mobile/fenix#9210]
> Taken from https://bugzilla.mozilla.org/show_bug.cgi?id=1620754

User Agent: Mozilla/5.0 (Android 10; Mobile; rv:75.0) Gecko/75.0 Firefox/75.0

Steps to reproduce:

•Go to any website.
•Tap the three dots at the top right to show the menu.
•Tap the "Add to Home Screen" button.
•When the pop-up appears, enter a name and press "add".

Actual results:

The pop-up disappears, but nothing is added to the home screen.

Expected results:

An icon linking to the relevant site should have appeared on the home screen.

**Comment by Screwtapello** [comment]
This happens to me too.

Firefox version info:

> Nightly 200705 06:01 (Build #21870613)
AC: 49.0.20200702190156, bafa9299b
GV: 80.0a1-20200702094606
AS: 61.0.7

On Android 10.

**Comment by AndiAJ** [comment]
Not reproducible anymore on the latest Nightly Build 201103 using the following devices:
• Google Pixel 3a (Android 11)
• Huawei Mate 20 Lite (Android 10)
• OnePlus A3 (Android 6.0.1)

**Comment by NooneXe** [comment]
@AndiAJ 
Its not working for me on Firefox Daylight 84.1.4 and Firefox Nightly 210108 on Android 10. Apparently google chrome is working

**Comment by AndiAJ** [comment]
Hi @NooneXe , thanks for the update.
Could you please give us more info's?

What device are you using?
What websites do you try to add to the homescreen?

**Comment by softvision-miralobontiu** [comment]
I was not able to reproduce this issue either with Google Pixel (Android 10), nor on 1/13 Nightly build, RC 84.1.4, or Beta 85.0.0-beta.7.

**Comment by NooneXe** [comment]
@AndiAJ sorry for delay,

I'm using [Moto E7](https://www.gsmarena.com/motorola_moto_e7_plus-10436.php)

I tested https://mdn.github.io/pwa-examples/js13kpwa/ and https://www.oyorooms.com. both worked fine with chrome. Also adding normal websites to home screen is also not working. When used chrome, I get notification that chrome is adding app to homescreen but none in case of firefox.

**Comment by lobontiumira** [comment]
@NooneXe are you able to reproduce this issue on your device?
I could add the two mentioned pages on the device's homescreen without issues. Tested with 6/30 Nightly with Samsung Galaxy Note 8 (Android 9), and Google Pixel (Android 10).

**Comment by NooneXe** [comment]
> @NooneXe are you able to reproduce this issue on your device?

I can't reproduce this issue now. it seems to works fine now

**Comment by lobontiumira** [comment]
Thank you!
Closing this issue, due to the above answer.

**Comment by dror3go** [comment]
On which version of Firefox Daylight should I expect to see this working? I'm on OnePlus 7T with Android 11 and Firefox 90.1.3 and the feature has been broken for quite some time now.
