### ISSUE TITLE
Unable to complete Yahoo OAuth2 signin using Firefox Preview

### ISSUE THREAD

**Issue by spocko** [mozilla-mobile/fenix#9214]
## Steps to reproduce
1. Set Firefox Preview as default browser in Android
2. Get AquaMail app from Google Play Store
3. Add Yahoo account using OAuth2
4. Enter credentials, and tap Agree on account access confirmation screen
5. Error screen is displayed saying "Unknown Protocol"

### Expected behavior
At step 5, return to AquaMail app and continue setting up the account.

### Actual behavior
Unknown Protocol error as noted in step 5.

### Device information
* Android device: 6.0.1
* Fenix version: 4.0.0 (Build#20691753)

### Other information
The error does not occur if the normal version of Firefox is set as the default browser (v68.6.0).
The error also does not occur if Brave is set as the default browser.

**Comment by kbrosnan** [comment]
Please try [Preview Nightly](https://play.google.com/store/apps/details?id=org.mozilla.fenix.nightly) we have fixed several cases of this in that build.

**Comment by spocko** [comment]
Thank you @kbrosnan.

The problem does not happen with Firefox Preview Nightly 200317 18:00 (Build 20771805).

I'll go ahead and close this issue.
