### ISSUE TITLE
[Bug] "The media could not be played" on Twitter after video plays once (does not loop)

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/fenix#9218]
Originally reported https://www.reddit.com/r/firefox/comments/f9ux5n/cant_replay_videos_on_firefox_android/fkt7oab/

## Steps to reproduce

1. Navigate to https://mobile.twitter.com/pawfectreview/status/1239479311935160322
2. Play video
3. Wait until video completes

### Expected behavior

The video should begin to replay in a loop.

### Actual behavior

Error appears saying "The media could not be played"

![image](https://user-images.githubusercontent.com/152493/76931276-b3edc300-68be-11ea-8e1e-c53b404055a3.png)

### Device information

* Android device: Samsung Galaxy S10
* Fenix version: release Fenix

**Comment by Amejia481** [comment]
Does disabling tracking protection fix the issue?

**Comment by yoasif** [comment]
@Amejia481 The user reports that disabling TP does not resolve the issue.

**Comment by ekager** [comment]
I can't repro this anymore. Let's QA it before closing out though.

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly 201218`** using the following devices:
• Google Pixel 3a (Android 11)
• Huawei Mate 20 Lite (Android 10)
• OnePlus A3 (Android 6.0.1)

► Video
![20201218-140607](https://user-images.githubusercontent.com/51314259/102613118-9c3bb780-413a-11eb-8c8d-ee53c279382e.gif)
