### ISSUE TITLE
[Meta] Firefox Sync Support for MVP

### ISSUE THREAD

**Issue by bbinto** [mozilla-mobile/fenix#922]
Confirmed with Application Services team that the following types will be available for sync in Fenix MVP

In Scope:
- History
- Bookmarks

## UX Designs
- @lime124's team to provide screen/UI for this part

## Dependencies
- https://github.com/mozilla-mobile/android-components/issues/1823

## Acceptance Criteria
- User, logged in to their account via Fenix will be able to de-select History and Bookmarks from a easily discoverable settings screen

**Comment by jdragojevic** [comment]
@bbinto  - based on the application services getting to beta doc: https://docs.google.com/document/d/1b_nkYw38Bc7Up4um4pg5qKBSrzPbnEe522SQqsVXAcg/edit#heading=h.um5nk445m88s there are 2 syncable data types planned for Fenix MVP:
* History
* Bookmarks

Can we please update the description of this issue to clarify that we are referring to those with this meta issue.

**Comment by bbinto** [comment]
@jdragojevic could you please give your approval stamp on the following then (could you also please add ETA for after MVP items where applicable)

In scope for MVP
- History
- Bookmarks

Out of scope for MVP, after 
- Open Tabs
- Logins
