### ISSUE TITLE
[Bug] Fenix closes without error message on this page

### ISSUE THREAD

**Issue by opusforlife2** [mozilla-mobile/fenix#9221]
## Steps to reproduce
Open this page https://marvelcinematicuniverse.fandom.com/wiki/Quake in Startpage's Anonymous Mode.
### Expected behavior
You can browse the page normally.
### Actual behavior
Fenix just closes without showing any error message.

On desktop Firefox it freezes the browser. Seems like a script going wild, but Fenix/Firefox should be able to handle this gracefully.
### Device information

* Android device: Xiaomi Mi 5 (3 GB RAM)
* Fenix version: 4.0

**Comment by mcarare** [comment]
I am not able to reproduce this on the latest master.

**Comment by abodea** [comment]
Thank you for this report @opusforlife2.
I tried to reproduce this issue on the latest **Nightly build from 18/3** with the following devices:
• Google Pixel 3a (Android 10)
• Google Pixel 4 XL (Android 10)
• OnePlus 6T (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S6 (Android 7)
• OnePlus A3 (Android 6.0.1)
• Nexus 4 (Android 5)

Note that I also tried to reproduce this issue on the latest RC but with no so much success.
Are there any other steps that you can provide?

**Comment by opusforlife2** [comment]
I did it again with uBlock Origin disabled from the Addon Manager. Now Fenix, instead of closing, goes to about:blank and then tries to open the URL again. This goes on in a loop once or twice more, then it closes. Again, without any error message.

Anything else I could try?

**Comment by darkwing** [comment]
I couldn't reproduce on my Pixel 4 either

**Comment by opusforlife2** [comment]
Can someone confirm if desktop Firefox memory usage skyrockets on this page?

**Comment by opusforlife2** [comment]
It's definitely a RAM issue. As I've mentioned in the OP, I have 3 GB RAM. I tried to open this page again just now and after loading and showing me the cookie prompt, my music app was stopped, which means the Android LMK killed the process.

Then Fenix reloaded the tab, and after reaching the cookie prompt, it closed, just like every other time.

**Comment by articlecat** [comment]
I'm able to reproduce this issue on an Android 9 device with 4 GB RAM. The issue appears when accessing the site through "Startpage's Anonymous Mode" and not directly.

## Steps to reproduce
1. Go to Startpage at https://startpage.com
2. Search for `https://marvelcinematicuniverse.fandom.com/wiki/Quake`
3. On the first search result, click "Anonymous View"

Fenix crashes while Anonymous View is loading, most likely because Fenix is consuming too much memory.

**Comment by opusforlife2** [comment]
This bug is gone for me in 5.1. If anyone can reproduce, please reopen.
