### ISSUE TITLE
[Bug] Save to Collection Snackbar is not displayed right above URL bar

### ISSUE THREAD

**Issue by bubi-luka** [mozilla-mobile/fenix#9222]
## Steps to reproduce
1. Visit a webpage
2. Menu (...) -> Save to Collection -> Add new collection -> enter new name

### Expected behavior
Snackbar "Tab saved" is displayed right above URL bar.

### Actual behavior
Snackbar is not displayed right above URL bar, but there is space for at least one snackbar in between.

![Screenshot_20200318_075801](https://user-images.githubusercontent.com/1206048/76937529-3e511980-68f5-11ea-8861-3e41e8f78dc0.jpg)

### Device information
* Android device: Huawei p20 lite, Android 9, EMUI 9.1
* Fenix version: Nightly 200317 18:00 (Build #20771806)

**Comment by bubi-luka** [comment]
As #8773 is marked as closed and fixed I am opening another issue for this option.

**Comment by abodea** [comment]
Thank you for this report @bubi-luka!
I was able to reproduce this issue too but only if saving a collection while a webpage is open on the latest Nightly 18/3 with Google Pixe 4XL (Android 10).
Adding this issue https://github.com/mozilla-mobile/fenix/issues/9196 as those two are the remaining ones.

**Comment by Diana-Rus** [comment]
Hello, reproduced with Samsung Galaxy S9 (Android 8.0.0) with build FIrefox Nightly 200320 (Build #20800605) GV: 76.0a1-20200318041411.

**Comment by sv-sdeiac** [comment]
Verified as fixed using the latest version of Firefox Preview Nightly 4/3 #20940609.
Now the snack bar notifications are displayed right above the toolbar menu.

Devices:
- Google Pixel 3 (Android 10);
- Samsung Galaxy Note 8 (Android 9);
- LG g7 fit (Android 8.1).
