### ISSUE TITLE
[Bug] The youtube navigation bar (home, trending and library) buttons are moving while scrolling

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/fenix#9226]
## Steps to reproduce
1. Launch Fenix
2. Access `www.youtube.com`.
3. Observe the youtube navigation bag `home, trending and library`.
### Expected behavior
The youtube navigation should be at the bottom and not expandable.
### Actual behavior
The youtube navigation bar is expandable.
### Device information

* Android device: **Google Pixel 4 XL (Android 10).**
* Fenix version: **Nightly 18/3.**

![20200318-145311](https://user-images.githubusercontent.com/42831109/76965583-34e3a380-692d-11ea-8be8-a757d0bd193e.gif)

**Comment by abodea** [comment]
@sblatz I re-checked this issue on Nightly 4/7 with Google Pixel 4 XL (10) but everything seems to work correctly.

**Comment by sblatz** [comment]
Okay, I will close this then. Please re-open if you run into it again @abodea 😄
