### ISSUE TITLE
[Bug]The floating text toolbar is cut when rotating the device. 

### ISSUE THREAD

**Issue by sflorean** [mozilla-mobile/fenix#9227]
### Steps to reproduce
1. Go to a website and long tap on any plain text (non-linked).
2. Rotate the device from portrait to landscape a couple of times.

### Expected behavior
The floating text toolbar is displayed without issues, all options are available.

### Actual behavior
The floating text toolbar is cut when rotating the device. 

### Device information
* Android device: Nexus 5 (Android 6.0.1)
* Fenix version: Nightly 18/03

![Screenshot_20200316-182529](https://user-images.githubusercontent.com/58466444/76978634-2d53d880-68f4-11ea-90f5-714ab1523323.png)
![Screenshot_20200316-182439](https://user-images.githubusercontent.com/58466444/76978677-38a70400-68f4-11ea-8119-1af86b916f2a.png)

**Comment by Mugurell** [comment]
@sflorean is this reproducing on in other apps also?
This seems like an Android platform issue.

**Comment by sflorean** [comment]
@Mugurell tested on latest Nightly (2/16) with the following devices and the issue is not reproducible anymore. Closing as worksforme.
- Nexus 5 (Android 6.0.1)
- Xiaomi Redmi Note 8T (Android 9)
- Nokia 6 (Android 7.1.1)
