### ISSUE TITLE
[Meta] Integrate Glean SDK (Event Ping)

### ISSUE THREAD

**Issue by bbinto** [mozilla-mobile/fenix#923]
Follow-up to #105 

This Epic is about enabling and hooking up Fenix with the Glean SDK event pings

## Dependencies
- Glean SDK / Georg's team has to have event ping infrastructure in place, this should be unblocked, as per Georg's email on March 11: https://github.com/mozilla-mobile/android-components/blob/master/components/service/glean/docs/metrics/adding-new-metrics.md 
- PM and data science provide useful events for Fenix team to implement, done here: https://github.com/mozilla-mobile/fenix/labels/Feature%3ATelemetry

**Comment by bbinto** [comment]
@st3fan could you please help break this into tasks/user stories? I'm not quite sure about the work that has to happen for the SDK integration piece. Thanks

**Comment by boek** [comment]
@bbinto I think I might have handled most of the work for this in https://github.com/mozilla-mobile/fenix/pull/1067

Though I'm not sure what is the best way to test it.

**Comment by bbinto** [comment]
@georgf - can @boek just send and hit a button and you wait on the other end to see if it came through to you ;) Clearly, I'm simplying this ;)

**Comment by georgf** [comment]
@boek I think the best way right now is to use [the debugging commands here](https://github.com/mozilla-mobile/android-components/blob/master/components/service/glean/README.md#debugging-products-using-glean).

You would first:
- enable logging of pings: `adb shell am start ... --ez logPings true`
- then trigger the event ping: `adb shell am start ...  --es sendPing events`
You should then see the JSON ping dumped to logcat and could check that it contains the events you recorded.

Let us know if that doesn't work out for you.

By April 15 we will have an easier testing solution in place: a web interface to see your data come in in soft realtime.
