### ISSUE TITLE
Allow easy Java/Kotlin profiling of production builds by shipping code that uses the Debug API

### ISSUE THREAD

**Issue by mstange** [mozilla-mobile/fenix#9231]
### Why/Developer Benefit/Developer Problem

Android Studio's built-in profiler only allows profiling debuggable builds. However, a debuggable Fenix is actually a lot slower than a production Fenix! My investigations show a difference of 3x to 4x on a Moto G5. This means that our Fenix performance engineers usually look at profiles with wildly-unrealistic timings. This can lead us to focus on the wrong issues and miss actual performance issues that affect our users.

Fenix has a `forPerformanceTest` configuration. This configuration uses `debuggable true` for the same reason: without it, it is currently impossible to do profiling. However, it also means that we can't use `forPerformanceTest` builds to run benchmarks, because the builds are unrealistically slow.

However, there is actually a way to profile production builds! The [Android `Debug` API](https://developer.android.com/studio/profile/cpu-profiler#debug-api) seems to be working as expected in production builds. You just need to call `Debug.startMethodTracingSampling` and `Debug.stopMethodTracing` manually from your app. Using these methods does not slow down the app! Not the way `debuggable` does. There's a small overhead to the sampling profiler, but the overhead is much much much lower than the overhead from `debuggable`.

### What/Requirements

I suggest shipping some functionality in our official builds that calls the respective `Debug` profiling methods in response to some trigger. At the very least it should be possible to obtain profiles for app startup. This will let users and developers obtain realistic profiles that fully reflect the performance of the code that we ship to our users. It'll also make profiling a little more approachable because we'll be able to profile the regular Play Store Fenix app that's already on our phones, without having to install a locally-built debuggable app.

I'm not sure what the trigger to kick off profiling should be. For startup profiling, ideally it'd be something that can be passed via `adb shell am start(-activity)`, so maybe an intent argument or an environment variable.

### Acceptance Criteria (how do I know when I’m done?)

The goal has been reached once the following is possible:

 1. As a developer, I connect my Android phone to my desktop machine.
 2. I run an `adb` command on my shell. This command should launch a fresh instance of the official Fenix nightly or release build from the Play Store, possibly with an "app link" intent so that it starts loading a website of my choosing immediately. It should also tell the app to start profiling itself as early as it can.
 3. Once startup has finished or the website has loaded, I perform some action to stop profiling.
 4. In the Device File Explorer in Android Studio, I find a `.trace` file somewhere on the device that contains a trace of the full application startup from the production build.

### Further Information

Here are two profiles that I obtained using the `Debug` API, with a local debuggable build and a local production build:

 - Debug: https://perfht.ml/38Lkbcr
 - Production: https://perfht.ml/39QBLgs

[Here's the hacky patch I applied locally in order to do this.](https://gist.github.com/mstange/f1dcb86e5caef78cd6ba9c0713c19198)
(These profiles were originally .trace files. I imported them into the Firefox profiler UI for easier sharing.)
If you compare the times of various methods between the two profiles, you see 3x to 4x differences.
You might ask yourself "Why does this matter? If everything's uniformly slowed down, aren't all the hot spots the same?" That's a valid question. However, things aren't uniformly slowed down: Fenix interacts with Gecko C++ code, which goes at its regular full speed, so whenever things race or interact in other ways between the two, things start to get unrealistic. And even if there are no such interactions, we don't know whether the slowdown really is uniform. In my experience, every time we collect data that's closer to reality, we learn valuable new things.

cc @mcomella @MarcLeclair @emalysz

**Comment by mcomella** [comment]
Thanks for filing this – this is really interesting. I filed https://jira.mozilla.com/browse/FXP-1266 to track it on JIRA (so closing this one) though this may not be necessary if we can get the Firefox Profiler to start getting traces earlier in the process.
