### ISSUE TITLE
Allow Gecko startup profiling with the Gecko Profiler in production builds

### ISSUE THREAD

**Issue by mstange** [mozilla-mobile/fenix#9234]
### Why/User Benefit/User Problem

The Gecko profiler allows [profiling Gecko startup](https://profiler.firefox.com/docs/#/./guide-remote-profiling?id=startup-profiling) with environment variables such as `MOZ_PROFILER_STARTUP`. However, as far as I know, this is currently only possible in debuggable builds:
The only way I'm aware of to set these environment variables is the yaml file, e.g. `/data/local/tmp/org.mozilla.fenix.debug-geckoview-config.yaml`, as described in the [Reading configuration from a file](https://mozilla.github.io/geckoview/consumer/docs/automation#reading-configuration-from-a-file) GeckoView docs. But this yaml file is only read in debuggable Fenix builds.

This means that we currently do not have a way to do Gecko startup profiling in Fenix production builds. This means we can't get accurate results in profiles.

This issue is similar to #9231 but scoped to the Gecko Profiler. This issue is not concerned with profiling Fenix itself or Java/Kotlin code - only with profiling Gecko.

### What/Requirements

Can we add a way to do this? For example, we could read the yaml file even in production builds. Or we could "propagate" the respective environment variables to Gecko when they're set from e.g. `adb shell am start --es env0 MOZ_PROFILER_STARTUP=1 [...]`.
Fennec seemed to do this, i.e. when Fennec was started with such a command, startup profiling would happen.

### Acceptance Criteria (how do I know when I’m done?)

It should be possible to obtain Gecko startup profiles with the Gecko profiler from Fenix production builds on the Play Store.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-16319)

**Comment by mstange** [comment]
> The only way I'm aware of to set these environment variables is the yaml file, e.g. `/data/local/tmp/org.mozilla.fenix.debug-geckoview-config.yaml`, as described in the [Reading configuration from a file](https://mozilla.github.io/geckoview/consumer/docs/automation#reading-configuration-from-a-file) GeckoView docs. But this yaml file is only read in debuggable Fenix builds.

After reading those docs it seems that `set-debug-app` provides a workaround for this. I'll try that.

**Comment by mstange** [comment]
Yes, that works. So this request is now less urgent.

**Comment by ekager** [comment]
@mstange do you still care about this issue?

**Comment by boek** [comment]
Going to close this for now, feel free to re-open in bugzilla if you still require this :)

**Comment by mstange** [comment]
Ah yeah this is not needed any more, the startup profiling docs are at https://profiler.firefox.com/docs/#/./guide-startup-shutdown?id=startup-profiling-fenix
