### ISSUE TITLE
DuckDuckGo Disappeared from search engines[Bug]

### ISSUE THREAD

**Issue by jawadalkassim** [mozilla-mobile/fenix#9235]
## Steps to reproduce
1-launch Fenix
2- Open Settings
3- then Search
4- Select default engine
### Expected behavior
Select DuckDuckGo as a default engine 
### Actual behavior
There's no option to choose DuckDuckGo unless i added it manually
### Device information
Huawei P8 2017
* Android device: 8.0 Oreo
* Fenix version: 
Nightly 200318 18:01 (Build #20781808)
37.0.20200317130045, 4b0491cf4
GV: 76.0a1-20200316092804
AS: 0.55.0

![Screenshot_20200319-001926](https://user-images.githubusercontent.com/48631694/77014894-f88b6400-697b-11ea-899c-3ff999957c22.jpg)

**Comment by EliasA** [comment]
This is still valid on 79.0.2

The problem from user point of view: using add search engine does not accept URL https://duckduck.com for a seach engine string. One has to know that a working URL string is https://duckduckgo.com/?q=%s

Finding this piece of information is not easy and you have to exit the settings to find the information.

Please bring DDG back to the selection.

**Comment by jawadalkassim** [comment]
@EliasA Can you Change the language in fenix settings to English/US ? then check for DDG 
 i've changed the language once by accident and DDG was gone so when cjanged it back  it appeared again

**Comment by EliasA** [comment]
I changed language to English/US and DDG apperared to selection of alternative search engines. I couldn't even imagine this kind of thing would be language dependent. What on earth is this?
