### ISSUE TITLE
BackgroundServices should not be initialized on startup

### ISSUE THREAD

**Issue by grigoryk** [mozilla-mobile/fenix#9236]
Currently we're initializing BackgroundServices (and kicking off FxaAccountManager's init) on startup. Strictly speaking, we don't need to do this so early on. Let's understand all of the touch points, and how we can defer this work.

**Comment by grigoryk** [comment]
Going to document each point at which we're initializing the account manager, as I'm working through them.

1) `HomeMenu` is initialized as part of `HomeFragment`. It's [eagerly initialized](https://github.com/mozilla-mobile/fenix/blob/030bd386317b8643e5e29ed502ddfd13334f155a/app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt#L314) to see if there are any highlight items present. To build a list of menu items, HomeMenu queries account manager to see if it needs to inject `reconnectToSyncItem` item.

**Comment by grigoryk** [comment]
What makes sense to me for the `HomeMenu` is to switch to observing account state (instead of just querying it once on startup), inject the menu item dynamically when necessary, and propagate this event change to HomeFragment so that it can re-trigger its `setHighlight` logic (or even better, the menu can _tell it_ to set a highlight, instead of telling it to go through every menu item).

This will also fix a bug that I'm assuming we have, not seeing any code that'll prevent it, when the highlight won't be correctly displayed if account manager runs into an auth problem anytime _after_ app startup.

But, this by itself will also trigger accountManager's init (in order to register with it!). Most of the time, for most users, we don't have an auth problem. And, even if we delay displaying the highlight by a little bit, that's not the end of the world. So, the missing conceptual piece here is a "when account manager is ready" task queue, that will let application pieces such as this one to perform non-startup-critical actions against the account manager.

**Comment by grigoryk** [comment]
Rest of the pieces were pretty straightforward - rewriting the "startup manager" to be more generic and useful for "run now or later" type of tasks, and adding a few `lazy` wrappers.
See https://github.com/mozilla-mobile/fenix/pull/9239/commits

**Comment by mcomella** [comment]
@grigoryk I see this is in a Done column: can this be closed?
