### ISSUE TITLE
As a user, I want to have the option to not be tracked by Firefox telemetry system

### ISSUE THREAD

**Issue by bbinto** [mozilla-mobile/fenix#924]
As a user, I want to have the option to not be tracked by Firefox telemetry system

### Why/User Benefit/User Problem
- transparency, choice for user to provide us their data

### What / Requirements
- Easy way to turn off/on telemetry and other data collecting service

Current services under Menu > Data Choices
- Telemetry (ON by default)
- Crash Reporter (Fennec parity)
- Mozilla Location service (Fennec parity)
- Fenix Health Report (Fennec parity)

### Acceptance Criteria (how do I know when I’m done?)
- All toggles work as expected and turn off or on data flow as toggled

**Comment by bbinto** [comment]
Question for @st3fan and @boek - how do you currently toggle Adjust and Leanplum data collection?

Should we/can we split them all up into own telemetry and 3rd party telemetry? I'll reach out to Marshall but wanted to first ask the engineers how the 3rd party SDKs can be turned off?

**Comment by boek** [comment]
@bbinto we could split them up! I wonder if there is a good way to communicate that though.

**Comment by bbinto** [comment]
Discussed with teams internally, we'll stick with having Leanplum and Adjust under same setting thant event ping.
