### ISSUE TITLE
[Bug] Gamepad API doesn't detect HID joystick

### ISSUE THREAD

**Issue by StefanHamminga** [mozilla-mobile/fenix#9241]
## Steps to reproduce
1. Plug joystick in phone USB (with adapter)
2. Load a test website: https://html5gamepad.com/
3. Move joystick

### Expected behavior
Joystick gets detected, axis data shows in site. This works in Chrome for Android on the same phone. Also works in Firefox desktop.

### Actual behavior
No joystick detected

### Device information

* Android device: Samsung S7 edge
* Android version: 8
* Joystick: SpaceMouse Module USB (HID compliant), plugged in USB port
* Fenix version: 76

**Comment by ekager** [comment]
@StefanHamminga are you still seeing this issue?
