### ISSUE TITLE
Hide home widget

### ISSUE THREAD

**Issue by 90du** [mozilla-mobile/fenix#9242]
![Screenshot_2020_0319_163925](https://user-images.githubusercontent.com/35375370/77047867-742ef480-6a00-11ea-9881-145c60b068e4.png)
The area marked on the picture hopes to add a hidden button in the settings. They take up too much space. I want to display only the web page labels.

**Comment by 90du** [comment]
![Uploading Screenshot_2020_0319_164839.png…]()
And here

**Comment by vesta0** [comment]
Thanks for your suggestion @90du ! We are considering changes to the homescreen that may address some of these issues.
