### ISSUE TITLE
[Bug] Animations not consistent for collections

### ISSUE THREAD

**Issue by ValentinTimisica** [mozilla-mobile/fenix#9243]
From #2359 - "** Pressing "Save to collection" should match the same animation as long pressing on an open tab. Currently it's different."

### Steps to reproduce & Actual behavior
- Press `Save to collection` -> tabs appear with a fade in animation.
- Long press on an open tab -> tabs appear with no animation

### Expected behavior
- `Save to collection`(wrong animation) should have the same animation as 'Long press on an open tab' (correct animation).

### Device information
- Samsung Galaxy Note 10 (Android 10)

**Comment by ValentinTimisica** [comment]
@AmyYLee, I attached a [video](https://drive.google.com/file/d/1oHzOe-ikXpPLrcPFxoOB6kA-OJjOUxYD/view?usp=sharing) with the issue.
As you can see, when you:
- Press on `Save to collection` a fade in animation appears for the tabs to select.
- Long press on an opened tab no animation shows.

Do you want me to remove the animation for pression on `Save to collection`, so both actions will not create any animations. Or do you want me to add that fade in animation for Long press on an opened tab action?

We have to choose from these two cases:
1) Both actions with no animations
2) Both actions with fade in animation

**Comment by AmyYLee** [comment]
> @AmyYLee, I attached a [video](https://drive.google.com/file/d/1oHzOe-ikXpPLrcPFxoOB6kA-OJjOUxYD/view?usp=sharing) with the issue.
> As you can see, when you:
> 
>     * Press on `Save to collection` a fade in animation appears for the tabs to select.
> 
>     * Long press on an opened tab no animation shows.
> 
> 
> Do you want me to remove the animation for pression on `Save to collection`, so both actions will not create any animations. Or do you want me to add that fade in animation for Long press on an opened tab action?
> 
> We have to choose from these two cases:
> 
>     1. Both actions with no animations
> 
>     2. Both actions with fade in animation

Hi, can you please set both with no animations. Thanks

**Comment by sv-sdeiac** [comment]
Hi, I can confirm that this issue is fixed using the latest Firefox Preview Nightly 3/23 #20830607.
Now for both long-press on an opened tab or pressing on the "Save to collection" button doesn't display the fade-in animation.

Devices:
- Google Pixel 3 (Android 10);
- Samsung Galaxy Tab S6 (Android 9);
- LG g7 fit (Android 8.1).
