### ISSUE TITLE
[Bug] www.bing.com - Missing Dropdown button symbol

### ISSUE THREAD

**Issue by softvision-sergiulogigan** [mozilla-mobile/fenix#9250]
Originaly logged here: https://github.com/webcompat/web-bugs/issues/50335

**URL**: https://www.bing.com

**Browser / Version**: Firefox Preview Nightly 200316 (🦎: 76.0a1-20200315093749)
**Operating System**: Samsung Galaxy S8 (Android 9) - 1440 x 2960 pixels, 18.5:9 ratio (~570 ppi density)
**Tested Another Browser**: Yes 

**Problem type**: Design is broken
**Description**: Missing Dropdown button symbol
**Steps to Reproduce**:
**Steps to reproduce:**
1. Go to https://www.bing.com
2. Tap on the Hamburger menu.
3. Tap on the "Settings"-"More" button.
4. Scroll to the "Results" section.
5. Observe the "Show this many results on each page" dropdown button.

**Expected Behavior:**
A dropdown symbol is displayed.

**Actual Behavior:**
Only the "Auto" string is displayed.

**Notes:**
1. Screenshot attached.

![image](https://user-images.githubusercontent.com/16573771/77071680-252f9200-69f5-11ea-9b38-d1d91fd9948b.png)

**Comment by ekager** [comment]
Can we retest this on a Samsung device? I can't repro on a Pixel 3

**Comment by abodea** [comment]
Verified as fixed on the latest Nightly **21/12** with **Google Pixel 4 XL (11), Samsung Galaxy S10+ (10), Samsung Galaxy S7 (7).**
The dropdown menu was displayed and worked as expected.
