### ISSUE TITLE
Core ping data shows up in redash

### ISSUE THREAD

**Issue by bbinto** [mozilla-mobile/fenix#926]
As a member of the Fenix team, I want to query core ping data in redash so I can see how the app is being used

### What / Requirements
- Can query redash for Fenix app core data
- Each release channel should be easily queried, e.g. channel = ''

### Acceptance Criteria (how do I know when I’m done?)
- Correct data can be accessed by release channel

**Comment by bbinto** [comment]
@bbinto to check with data science how to determine beta/release users assuming we will be using one single release pipeline

**Comment by bbinto** [comment]
@vesta0 to make sure this aligns with the latest Fennec transition plan

**Comment by bbinto** [comment]
superseded by all issues under epic: https://github.com/mozilla-mobile/fenix/issues/105.

A little background: https://github.com/mozilla-mobile/fenix/issues/1158#issuecomment-478563073

@vesta0 - I created a bunch of sub / user stories for all additional basic core ping probes that I thought we'd get for free. I have not moved them into a milestone / backlog because I wanted you to be aware of it first.

I think the following issues should all be flagged as P1 and moved into milestone 4.

https://github.com/mozilla-mobile/fenix/issues/1298
https://github.com/mozilla-mobile/fenix/issues/1299
https://github.com/mozilla-mobile/fenix/issues/1300
https://github.com/mozilla-mobile/fenix/issues/1158
https://github.com/mozilla-mobile/fenix/issues/960
https://github.com/mozilla-mobile/fenix/issues/1301
https://github.com/mozilla-mobile/fenix/issues/927
https://github.com/mozilla-mobile/fenix/issues/1302

**Comment by bbinto** [comment]
Feel free to close this issue once you've seen this comment, @vesta0

**Comment by vesta0** [comment]
Closing as discussed.
