### ISSUE TITLE
[Bug] gecko decision task failing after Plugin [id: 'org.gradle.kotlin.kotlin-dsl', version: '1.2.9'] was not found in any of the following sources:

### ISSUE THREAD

**Issue by Archaeopteryx** [mozilla-mobile/fenix#9264]
The gecko decision task which is supposed to schedule all tasks for a push failed once.

CC @pocmo 

Log: https://treeherder.mozilla.org/logviewer.html#?job_id=293962218&repo=fenix

[task 2020-03-19T23:12:54.421Z] FAILURE: Build failed with an exception.
[task 2020-03-19T23:12:54.421Z] 
[task 2020-03-19T23:12:54.422Z] * Where:
[task 2020-03-19T23:12:54.423Z] Build file '/builds/worker/checkouts/src/buildSrc/build.gradle.kts' line: 5
[task 2020-03-19T23:12:54.423Z] 
[task 2020-03-19T23:12:54.424Z] * What went wrong:
[task 2020-03-19T23:12:54.424Z] Plugin [id: 'org.gradle.kotlin.kotlin-dsl', version: '1.2.9'] was not found in any of the following sources:
[task 2020-03-19T23:12:54.424Z] 
[task 2020-03-19T23:12:54.425Z] - Gradle Core Plugins (plugin is not in 'org.gradle' namespace)
[task 2020-03-19T23:12:54.426Z] - Plugin Repositories (could not resolve plugin artifact 'org.gradle.kotlin.kotlin-dsl:org.gradle.kotlin.kotlin-dsl.gradle.plugin:1.2.9')
[task 2020-03-19T23:12:54.428Z]   Searched in the following repositories:
[task 2020-03-19T23:12:54.429Z]     Gradle Central Plugin Repository
[task 2020-03-19T23:12:54.429Z] 
[task 2020-03-19T23:12:54.429Z] * Try:
[task 2020-03-19T23:12:54.430Z] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

**Comment by ekager** [comment]
cc @pocmo @Archaeopteryx do we think we can close this issue?

**Comment by Archaeopteryx** [comment]
Closing the issue because it hasn't been observed in the last 120 days.
