### ISSUE TITLE
Add a confirmation dialog before quitting the browser

### ISSUE THREAD

**Issue by ghost** [mozilla-mobile/fenix#9266]
### Why/User Benefit/User 
If a confirmation dialog is added it will make sure the user really wants to quit the browser and not accidently clicked on the Quit button. It'll make sure the user doesn't accidentally lose the ongoing browsing session's data. 

### What/Requirements
1. A dialog for confirming if the user really wants to quit the browser.
2. A check box for making sure/remembering if the user wants the dialog to appear everytime or not.

### Acceptance Criteria (how do I know when I’m done?)
If the browser asks before quitting and a check box in the dialog box for remembering the the preferences of whether user wants the quit dialog box to appear everytime before the user quits the browser or not.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-16337)

**Comment by ShatteredPixel** [comment]
Hi, I am the reporter of this issue. Please let me know if I can provide you any more information.

Thank you! :)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807113

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
