### ISSUE TITLE
Search For tabs in the tabs tray

### ISSUE THREAD

**Issue by Poopooracoocoo** [mozilla-mobile/fenix#9268]
### Why/User Benefit/User Problem
You currently cannot search for tabs. Users expect this from Firefox for desktop. 

### What/Requirements

- Search button in tab switcher next to menu (that expands into a search bar when tapped on)
- Search only tabs in address bar by appending or prepending the query with % 
- Search only tabs in address bar with tabs shortcut

### Acceptance Criteria (how do I know when I’m done?)
When the above is completed and documentation is added. 

### Additional Information

https://support.mozilla.org/en-US/kb/search-open-tabs-firefox
https://blog.mozilla.org/theden/2012/04/30/firefox-tips-search-your-open-tabs/
https://support.mozilla.org/en-US/kb/search-firefox-address-bar#w_search-shortcuts
https://support.mozilla.org/en-US/kb/address-bar-autocomplete-firefox#w_changing-results-on-the-fly

P.S. the SUMO KB articles for desktop need some work.

Firefox 83 for desktop added three shortcuts to the "this time, search with" section so you can search only bookmarks, only tabs, or only history: 
![image](https://user-images.githubusercontent.com/51363864/99468796-8bf6b800-2995-11eb-8a88-bfb1f0c285d0.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-16339)

**Comment by s-ankur** [comment]
You can search for tabs now, although indirectly. Just write the url or title in the search bar and firefox will give you the option to switch to that tab.

**Comment by Poopooracoocoo** [comment]
On Firefox for desktop I think you can put % in the beginning of your query in the address bar to search only for tabs. You can also search only for tabs through the tab manager popup. 

Switch to tab isn't the same but I'm glad we have it.

**Comment by Poopooracoocoo** [comment]
@kbrosnan do you guys happen to be prioritising this anytime soon?

**Comment by Poopooracoocoo** [comment]
@Mugurell Any plans to bump the priority of this? I saw that searching bookmarks is in the works.

**Comment by gabrielluong** [comment]
This is interesting and I was not aware of this, but it doesn't seem to be on our immediate radar. @kbrosnan would still be the best contact for this.

**Comment by sflorean** [comment]
This was implemented here: #24300. Not all of the requirements from description, but maybe we could close this and file another one to reflect the ones that weren't implemented?

@Poopooracoocoo

**Comment by Poopooracoocoo** [comment]
Up to you. 🤷‍♂️
Main ones are being able to search for it in the address bar and being able to search from the tab switcher.

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812933

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
