### ISSUE TITLE
Add option in settings to disable "Switch to tab" search suggestions

### ISSUE THREAD

**Issue by Poopooracoocoo** [mozilla-mobile/fenix#9269]
### Why/User Benefit/User Problem
Now that #1500 was introduced, some users may not want tabs to appear as suggestions in search

### What/Requirements
Option in Settings> Search> Address bar called "Search open tabs"

### Acceptance Criteria (how do I know when I’m done?)
When the above is completed

Edit: this should match desktop

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-16340)

**Comment by Poopooracoocoo** [comment]
this is also available on desktop

**Comment by topotropic** [comment]
Yes, sounds good. We can add the option "Search open tabs" after the "Search bookmarks" option. Thanks!

**Comment by Poopooracoocoo** [comment]
i had completely forgotten about this issue i created. i was worried that all of my issues that i either created or supported would be closed by your new bot @topotropic

**Comment by Poopooracoocoo** [comment]
oh and @topotropic, a related issue is #9268. _Note that they are different_. The Chromium triagers had confused two of my issues one time and it took so so much annoying on my side. Took _months_ for them to fix that.

**Comment by Poopooracoocoo** [comment]
@topotropic hey hope you don't mind me bumping this. What's the status of this FR? Still not a priority?

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807114

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
