### ISSUE TITLE
[Bug] Delays during tab transition

### ISSUE THREAD

**Issue by J41319** [mozilla-mobile/fenix#9273]
## Steps to reproduce

Open a tab and click to change the current tab and enter into it again

### Expected behavior

The transition must be smooth and have no delays

### Actual behavior

A small delay occurs during the tab transition

### Device information

* Android device: Xiaomi Mi A3 (Android 9)
* Fenix version: 4.1.0

Video: https://1drv.ms/u/s!AhHaljE4bL52guYxIHCH2MJaTx2_ew?e=uVPRHN

**Comment by topotropic** [comment]
@J41319 is this still an issue for you? Thanks!

**Comment by J41319** [comment]
> @J41319 is this still an issue for you? Thanks!

No, after the last update after I reported the problem, the problem has been fixed.
