### ISSUE TITLE
[Bug] Regression - Back button closes PB shortcut instead of going to Fenix home screen

### ISSUE THREAD

**Issue by opusforlife2** [mozilla-mobile/fenix#9275]
## Steps to reproduce
1. Open Fenix using the PB shortcut.
2. Open any tab.
3. Tap back. Fenix 'minimizes' to home screen. (What is this behaviour called?)
4. Open from recents or by tapping the shortcut. Fenix opens to the search bar again.
5. Tap back.

### Expected behavior
In 4.0, this took you to either the already opened tab, or to the Fenix home page, letting you access the tab either way.
### Actual behavior
In 4.1, Fenix just minimizes to the home screen again. You have no choice but to open another tab to be able to access the earlier one(s).
### Device information

* Android device: Xiaomi Mi 5
* Fenix version: 4.1

**Comment by opusforlife2** [comment]
Also, simply opening the shortcut, then tapping back used to take you to the Fenix home page. Now it backs out of the app, forcing you to open at least one link to access the main browser UI.

**Comment by Hubfront** [comment]
In Fenix nightly, i cant find a back button at all, only a forward button. As a Samsung user, with one ui 2.0, i can can gesture backwards. With firefox mobile, this works as expected and the browser navigates to the previous page of the current tab, but with Fenix nightly, i just land on the "home screen" which only shows the opened tabs.

**Comment by opusforlife2** [comment]
Just updated to 4.2.0. This is fixed.

**Comment by opusforlife2** [comment]
Spoke too soon. Just encountered this again.

**Comment by opusforlife2** [comment]
Still present on 4.3.0.

**Comment by opusforlife2** [comment]
All the issues I mentioned here have been fixed by 5.0.0.
