### ISSUE TITLE
[Bug] When signed-in and accessing the accounts.firefox.com page from History, the page loads indefinitely

### ISSUE THREAD

**Issue by lobontiumira** [mozilla-mobile/fenix#9278]
## Steps to reproduce
1. Sign in with valid credentials.
2. Go to Library - History, and tap on one of the accounts.firefox.com/oauth entry.
3. When the accounts.firefox.com/oauth page opens, tap on the "Sign in" button.

### Expected behavior
A message is displayed that the user is already signed in.

### Actual behavior
The page loads indefinitely or crashes. The other tabs can be accessed. Returning to the accounts page, the user still sees the loading page.
I was able to reproduce the crash only once (1/8 tries) on OnePlus.

### Device information
* Android devices: OnePlus 5T (Android 9), Samsung Galaxy Tab A6 (Android 5.1.1)
* Fenix version: 3/20 Nightly build
* Fennec version: 68.6.0

Please see the attached logcat regarding the freeze:
[loading.txt](https://github.com/mozilla-mobile/fenix/files/4360454/anr.txt)

![loading](https://user-images.githubusercontent.com/40694158/77180032-018e4980-6ad2-11ea-9c75-ce3e8bfe828d.gif)

**Comment by softvision-miralobontiu** [comment]
I was able to reproduce this issue on the latest Nightly build from 1/4 with OnePlus 5T (Android 10).
