### ISSUE TITLE
[Bug] Wrong animation after pressing Add new collection

### ISSUE THREAD

**Issue by ValentinTimisica** [mozilla-mobile/fenix#9280]
From #2359 - "There's a lag where after tapping on "Add new collection", the control fades out leaving a blank space before the keyboard appears."

### Steps to reproduce
- On home screen press on `Save to collection`
- Select at least one tab and press `Save`
- Press `Add new collection`

### Expected behavior
- The keyboard should appear immediately on the screen

### Actual behavior
- The keyboard appears after a fade in animation (check [video](https://drive.google.com/open?id=1Y_4XLfJR_rhfZ4VXR_8KTfcu-GownF-g))

### Device information
- Samsung Galaxy Note 10 (Android 10)

Looks like right now there is a fade in animation with 200 ms of duration in Name collection (after pressing Add new collection). After this animation ends, then the keyboard is shown.

**Comment by ekager** [comment]
Reopening to verify

**Comment by sv-sdeiac** [comment]
Verified as fixed using the latest version of Firefox Preview Nightly 3/29 @20891805.

Devices:
- Google Pixel 3 (Android 10);
- Samsung Galaxy Note 10 (Android 10);
- Xiaomi Mi 8 Lite (Android 9);
- LG g7 fit (Android 8.1).
