### ISSUE TITLE
[Bug] Typing does not capitalize after new sentence starts.

### ISSUE THREAD

**Issue by quadriflax** [mozilla-mobile/fenix#9283]
## Steps to reproduce
Type in any box (e.g., text box on Reddit, Slickdeals), end a sentence, start new sentence.
### Expected behavior
After a period at the end of a new sentence, keyboard should automatically capitalize/"hold shift" for the first word of the next sentence.
### Actual behavior
The keyboard stays lowercase.
### Device information

* Android device: Moto G5+ (Android 8.1), Samsung Galaxy Tab A (2019, Android 9.0)
* Fenix version: multiple versions (do not recall when it started), but includes Nightly 200320 06:01 (Build #2015729649) 37.0.20200319130119... Friday 3/20 @ 6:06 AM

No other browser I've used (Edge, Chrome, Fennic) exhibits this behavior, including latest version of Fennic. This was not an issue on previous versions, though I don't know exactly when it started having this issue (maybe a couple weeks ago?). I use Google keyboard, latest version.

**Comment by Poopooracoocoo** [comment]
there are heaps of typing issues btw

**Comment by makotokato** [comment]
I guess that this might be regression by https://bugzilla.mozilla.org/show_bug.cgi?id=1509527, so I will file/handle/fix it next week.

**Comment by makotokato** [comment]
I filed as https://bugzilla.mozilla.org/show_bug.cgi?id=1625843

**Comment by quadriflax** [comment]
Resolved.
