### ISSUE TITLE
[Bug] Site icons disappear from Top Sites

### ISSUE THREAD

**Issue by quadriflax** [mozilla-mobile/fenix#9284]
## Steps to reproduce
Send link to Top Sites, close app, reload app.
### Expected behavior
Website icons would display upon reload.
### Actual behavior
Website icons disappear randomly, resorting to generic icons (i.e., first letter of website title).
### Device information

* Android device: Moto G5+ (Android 8.1), Samsung Galaxy Tab A (2019, Android 9.0)
* Fenix version: multiple versions (do not recall when it started), but includes Nightly 200320 06:01 (Build #2015729649) 37.0.20200319130119... Friday 3/20 @ 6:06 AM

Since I started using Nightlies, this bug has persisted. The icons will be there when I first add the link to Top Sites, but then when I close/reload the apps, the icons are gone (link remains with generic icon). It happens every time.

**Comment by ekager** [comment]
Likely related to https://github.com/mozilla-mobile/fenix/issues/8443

**Comment by quadriflax** [comment]
Does look similar. It seems to happen when I bookmark individual subforums from a main URL (e.g., https://slickdeals.net/forums/forumdisplay.php?f=9), but when I checked the main URL just now (i.e., https://slickdeals.net) the icon was still there.

**Comment by ekager** [comment]
@quadriflax are you still seeing this?

**Comment by quadriflax** [comment]
No, nothing seems to disappear anymore. Still have sites that don't load icons, but I know that's a separate issue.
