### ISSUE TITLE
Add isDefault Flag to default Top Site entries

### ISSUE THREAD

**Issue by ekager** [mozilla-mobile/fenix#9286]
### Why/User Benefit/User Problem
Currently, on first install, we check the current locale and then add default top sites to the generic top sites storage. With an impending deadline, this was kind of a hack. Adding a flag would allow us to have better telemetry, be able to position them where we want them, and edit/change/remove those default top sites if necessary, ie when the [locale](https://github.com/mozilla-mobile/fenix/issues/8480) or endpoint for these sites changes

### What/Requirements
Will require AC work to edit the DB entry to contain a boolean like `isDefault`, and then use that flag in Fenix when adding default top sites on first install.

### Acceptance Criteria (how do I know when I’m done?)
We can tell (for new users only :/ ) which are the default top sites for telemetry and for editing/changing those if needed

**Comment by ekager** [comment]
Opened https://github.com/mozilla-mobile/android-components/issues/6331 for AC changes required

**Comment by gabrielluong** [comment]
> Opened [mozilla-mobile/android-components#6331](https://github.com/mozilla-mobile/android-components/issues/6331) for AC changes required

Taking on the AC changes. 👍

**Comment by liuche** [comment]
Looks like the AC changes are ready.

**Comment by liuche** [comment]
This is the pre-req for updating the default top sites telemetry, and is done.

**Comment by liuche** [comment]
@ekager will add the bug tracking the remaining work to the sprint backlog.
