### ISSUE TITLE
[Bug] Fix intermittent UI test failure - libraryMenuItemsTest

### ISSUE THREAD

**Issue by Baron-Severin** [mozilla-mobile/fenix#9287]
Multiple PRs unrelated to this UI have been failing on it recently.  It also appears to be flaky (see screenshot).

Firebase: https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/5640171423850485622

<img width="947" alt="Screen Shot 2020-03-20 at 10 52 44 AM" src="https://user-images.githubusercontent.com/13170306/77192155-582b6180-6a99-11ea-9374-93b04af577db.png">

**Comment by AaronMT** [comment]
@Baron-Severin Did you rebase, because the Nexus 6 (25) is not in use anymore currently. I also submitted a possible fix this morning #9263

**Comment by Baron-Severin** [comment]
Strange. I haven't rebased since Wednesday, but this run was from this morning.  So it sounds like we can just remove the @ignore and close this.  Thanks @AaronMT!

**Comment by sv-ohorvath** [comment]
The library menu and test were removed. Can close this now.
