### ISSUE TITLE
Intermittent UI test failure - SettingsBasicsTest.toggleSearchSuggestions UI test

### ISSUE THREAD

**Issue by AaronMT** [mozilla-mobile/fenix#9293]
This test relies on network access to fetch search suggestions (e.g, "mozilla") which can be intermittent based on network. The test should wait for async background operations.

fails with the following error: `The suggestion count is less than or equal to the minimum suggestions`

firebase log: https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/5749887503750778646/executions/bs.6b67056cb14d27ab/testcases/1/test-cases

**Comment by rpappalax** [comment]
verified as still failing intermittently

**Comment by rpappalax** [comment]
fails with the following error: `https://github.com/mozilla-mobile/fenix/pull/12216/checks?check_run_id=832502452`
@sv-ohorvath @AaronMT is this perhaps a legit application bug?

**Comment by rpappalax** [comment]
> This test relies on network access to fetch search suggestions (e.g, "mozilla") which can be intermittent based on network. The test should wait for async background operations.

Can we add an idlingResource to do that?  "[Common use cases](https://medium.com/@humaira.pasha/espresso-idling-resource-and-network-calls-e8084fe901ff): Loading data from the internet"

**Comment by AaronMT** [comment]
Yeah I thought it already, or maybe I had a WIP at one point I remember looking at it. The search suggestion test relies on network to do search suggestions. I thought it maybe made use of an idling resource already, but that would be a good candidate to wait until the adapter has an item count.

**Comment by sv-ohorvath** [comment]
This was fixed and moved to the SmokeTest class.
