### ISSUE TITLE
[Bug] Sound lags

### ISSUE THREAD

**Issue by Paxani4you** [mozilla-mobile/fenix#9296]
## Steps to reproduce
Listen to music a browser, audio or radio is not important and  minimize browser or the lock phone screen, sound starts to lags, stutter. 

When you close the tab with sound, the sound disappears after 5 seconds, and not immediately.

This bugs only in all fenix versions, bugs not In other browsers and firefox standard

### Device information
Nokia 7.2 9Pie / 10Q
* Android device: Nokia 7.2
* Fenix version: 4.1.0 (Build #20771637) and all versions earlier

**Comment by ekager** [comment]
@Paxani4you are you still seeing this?
