### ISSUE TITLE
[Bug] Wrong website bottom bar position

### ISSUE THREAD

**Issue by jmue** [mozilla-mobile/fenix#9299]
## Steps to reproduce
- set toolbar to top
- open a webpage that displays a bottom bar like welt.de and open some article
- swipe up throurgh the article

### Expected behavior
- the website bottom bar should be show at the bottom of the app

### Actual behavior
- the website bottom bar is placed above the noexistent bottom toolbar

### Device information

* Android device: Nokia 7.1
* Fenix version: Nightly 200320, 4.1
![toolbar-bottom-wrong](https://user-images.githubusercontent.com/898577/77207314-5beed080-6af9-11ea-994f-763c70f401db.png)

![toolbar-top-ok](https://user-images.githubusercontent.com/898577/77207420-99535e00-6af9-11ea-9136-eb349e165b21.png)

**Comment by hiikezoe** [comment]
This is a dup of #6940.

**Comment by liuche** [comment]
Going to dupe this to #8765 because someone is already assigned there.
