### ISSUE TITLE
Option to disable Full-Screen mode and always show the Browser Toolbar without having to scroll.

### ISSUE THREAD

**Issue by smartfonreddit** [mozilla-mobile/fenix#9302]
### Why/User Benefit/User Problem

1. Devices are getting increasingly larger. It makes sense for some users to prefer the convenience of not having to scroll a page every time they want to switch tabs, over losing a small real estate on the bottom.

2. As devices get larger, more users use their phones for main browsing, more multitasking, more tabs, more serious work. Inability to permanently make the Bar visible introduces unnecessary scrolls to a) switch tabs b) find words on pages c) close tabs d) open news tabs, etc. all commonly used actions.

3. In the future, users who get automatically upgraded from Fennec to Fenix would lose this feature because Fennec has it but Fenix doesn't. 

4. Chromium browsers don't have this feature. Fenix could lead the pack.

### What/Requirements

Fennec has this feature. Please port it to Fenix as an optional toggle.

**Comment by Poopooracoocoo** [comment]
By "Status Bar" did you mean "Toolbar"?

**Comment by kbrosnan** [comment]
Dupe #8801
