### ISSUE TITLE
[Bug] Div with position:sticky doesn't respect its threshold

### ISSUE THREAD

**Issue by RadhiFadlillah** [mozilla-mobile/fenix#9303]
## Steps to reproduce

I'm not sure how to put it in words, so I've made a [pen](https://codepen.io/radhifadlillah/full/NWqBJzG) to reproduce my issue. Open it in Firefox Mobile, then scroll to bottom.

### Expected behavior

Sticky elements should be respecting its threshold and not jumping around. Here is [screencast](https://thumbs.gfycat.com/UnrulyDiligentCony-mobile.mp4) where it works perfectly in Brave.

### Actual behavior

Sticky elements ignore its threshold, as can be seen on this [screencast](https://thumbs.gfycat.com/ThatFlatInexpectatumpleco-mobile.mp4). By the way, this problem also happens in Firefox Stable for Android.

### Device information

* Android device: Lenovo Moto M running Android 7.0, kernel 3.18.35+
* Fenix version: Firefox Nightly 200320 18:01 (Build #2015729747)

**Comment by RadhiFadlillah** [comment]
Hi everyone,

I just want to report that `position: sticky` now works properly in Firefox Daylight 80.1.2 (Build 2015761283). Fortunately it keep working like this in future version.

**Comment by ekager** [comment]
Thanks for the update! Closing
