### ISSUE TITLE
Move Share in menu from an icon to a menu item 

### ISSUE THREAD

**Issue by Poopooracoocoo** [mozilla-mobile/fenix#9309]
### Why/User Benefit/User Problem
By moving Share to above the row of icons, you could place an icon to the most recently used app/device to share. This lets users share really quickly.

### What/Requirements
the above

### Acceptance Criteria (how do I know when I’m done?)
the above

**Comment by liuche** [comment]
Duping to #14926 where we'll address improvements to sharing.

**Comment by DragoCubed** [comment]
@liuche #14926 was closed without addressing this.
