### ISSUE TITLE
[Bug]Commonly used website icon left and right space is not the same

### ISSUE THREAD

**Issue by 90du** [mozilla-mobile/fenix#9310]
![Screenshot_2020_0321_205353](https://user-images.githubusercontent.com/35375370/77226897-bc901300-6bb6-11ea-9388-263cd5810cb7.png)

Commonly used website icon left and right space is not the same

**Comment by AndiAJ** [comment]
**Not reproducible** anymore on the latest on the latest **`Nightly Build 201111`** using the following devices:
• Google Pixel 3a (Android 11)
• Huawei Mate 20 Lite (Android 10)
• OnePlus A3 (Android 6.0.1)
