### ISSUE TITLE
[Bug] dailymail.co.uk takes twice as long to load as samsung browser

### ISSUE THREAD

**Issue by simonsteiner1984** [mozilla-mobile/fenix#9314]
## Steps to reproduce
Open dailymail.co.uk

### Expected behavior
Loads in same time as samsung browser

### Actual behavior
Takes twice as long

### Device information

* Android device: Samsung j3 2017
* Fenix version: 4.1

**Comment by ekager** [comment]
Hey @simonsteiner1984 are you still seeing a slow load on this page?

**Comment by simonsteiner1984** [comment]
Seems ok now

**Comment by ekager** [comment]
Thanks!
