### ISSUE TITLE
[Bug] Styles with height percents are working incorrectly

### ISSUE THREAD

**Issue by kadmil** [mozilla-mobile/fenix#9315]
## Steps to reproduce
open mobile.twitter.com, see bottom tabs exploding on half of the screen
![Screenshot_20200323-022150](https://user-images.githubusercontent.com/4445523/77265160-107d2380-6cad-11ea-89ce-208f42d601fe.png)
### Expected behavior
bottom tabs staying at the bottom of the page

### Actual behavior
tabs panel taking half of the screen

### Device information

* Android device: Pixel 2 xl
* Fenix version:
Firefox preview
4.1.0 (Build #20771637)
36.0.2, 6638a3365
GV: 75.0-20200309155231
AS: 0.53.3

**Comment by kadmil** [comment]
I've seen this on other sites as well, but I think Twitter is the easiest to reproduce on

**Comment by AndiAJ** [comment]
**Not reproducible** anymore on the latest on the latest **`Nightly Build 201111`** using the following devices:
• Google Pixel 3a (Android 11)
• Huawei Mate 20 Lite (Android 10)
• OnePlus A3 (Android 6.0.1)
