### ISSUE TITLE
[Bug] The Search Widget is not working as the "Problem loading widget" error is displayed (on Android 10)

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/fenix#9318]
## Steps to reproduce
1. Launch Fenix and then reach the device home screen.
2. Long tap on the home screen and reach the widget section.
3. Add the Nightly search widget to the home screen.
### Expected behavior
The search widget is correctly displayed and it can be accessed.
### Actual behavior
The Search Widget is not working as the "Problem loading widget" error is displayed
### Device information

* Android device: **Google Pixel 4 XL (Android 10), Google Pixel 3a XL (Android 10)**
* Fenix version: **Nightly 3/23.**

![Screenshot_20200323-143730](https://user-images.githubusercontent.com/42831109/77320159-b9ad3380-6d18-11ea-9fcf-355dfc136d8d.jpg)

### Notes 
I couldn't reproduce this issue on the following devices:
•  Samsung Galaxy s7 (Android 7)
• Samsung Galaxy S6 (Android 7)
• One Plus (Android 5)
• Samsung Galaxy S9 (Android 8)
• Google Pixel 3 (Android 9)

**Comment by AndiAJ** [comment]
**Not reproducible** anymore on the latest on the latest **`Nightly Build 201111`** using the following devices:
• Google Pixel 3a (Android 11)
• Huawei Mate 20 Lite (Android 10)
• OnePlus A3 (Android 6.0.1)
