### ISSUE TITLE
[Bug] https://tieba.baidu.com cannot switch to desktop mode view page.

### ISSUE THREAD

**Issue by lindongbin** [mozilla-mobile/fenix#9320]
## Steps to reproduce

1. open https://tieba.baidu.com
2. enable desktop view mode

### Expected behavior

![Screenshot_2020-03-23-21-46-11-236_org mozilla fenix nightly](https://user-images.githubusercontent.com/3154109/77323953-fd239400-6d50-11ea-8d48-ae2c15bee6c7.jpg)

### Actual behavior

firefox preview just change the width of viewport, not show the real desktop mode page

![Screenshot_2020-03-23-21-47-05-499_org mozilla fenix nightly](https://user-images.githubusercontent.com/3154109/77323914-f268ff00-6d50-11ea-9503-12313fa9ffae.jpg)

### Device information

tested on 3.23 nightly
it works on 3.10 nightly and before
not working on 3.11 nightly and later
https://zhidao.baidu.com desktop mode view does not work either

**Comment by lindongbin** [comment]
works on 3.10 nightly and before
not work on 3.12 nightly and later

**Comment by lindongbin** [comment]
https://zhidao.baidu.com does not work either

**Comment by sflorean** [comment]
Works on the latest Nightly with Google Pixel (Android Q) - both pages. @lindongbin what device do you have?

**Comment by lindongbin** [comment]
> Works on the latest Nightly with Google Pixel (Android Q) - both pages. @lindongbin what device do you have?

Changed description, not the site is not working, it is the desktop mode that is not working on a particular site

**Comment by lindongbin** [comment]
#10104
