### ISSUE TITLE
[Bug]The microphone icon for widget is not displayed on 2x1 size

### ISSUE THREAD

**Issue by sv-sdeiac** [mozilla-mobile/fenix#9323]
## Steps to reproduce
1. Long tap on the home screen of the android;
2. Set a widget for Firefox Preview Nightly;
3. Resize it to 2x1.

### Expected behavior
The widget has the Firefox Preview icon and the microphone icon displayed.

### Actual behavior
The widget has the Firefox Preview icon but doesn't display the microphone icon.

### Device information
Android device:
- LG g7 fit (Android 8.1);
- Samsung Galaxy Tab S6 (Android 9);
- Google Pixel 3 (Android 10).

Fenix version: Firefox Preview Nightly 3/23 #20830607.

### Notes
- It seems that the last good build was:2/27 #20581806 and the first bad build found was: 2/28 #20590606.
- Also, it seems that if you tap on the specific place where the mic icon should be, the app is opening and started the mic recorder.
![Screenshot_12](https://user-images.githubusercontent.com/40264165/77331010-cc2f6900-6d28-11ea-8ba3-639d01c51adc.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-16374)

**Comment by Diana-Rus** [comment]
Hi, issue reproducible with Google Pixel 3 XL (Android 9) on Firefox Preview Nightly 200506 (Build #21270609).

**Comment by Diana-Rus** [comment]
Still reproducible with Samsung Galaxy S9 (Android 8) and Google Pixel 3 XL (Android 9) with the latest Nightly 7/6

**Comment by ebalazs-sv** [comment]
This issue is still reproducible on Nightly 2/12 with Nexus 5 (Android 6.0.1).

**Comment by lobontiumira** [comment]
Reproducible on RC 88.1.4 with Samsung Galaxy Note 8 (Android 9).

**Comment by lobontiumira** [comment]
Reproducible on Beta 91.0.0-beta.6 with Sony Xperia Z5 Premium (Android 7.1.1).

**Comment by delia-pop** [comment]
This is still reproducible on Beta 96.0.0-beta.2 with LG G7 fit (Android 8.1.0).

**Comment by delia-pop** [comment]
Reproducible on Beta 100.0.0-beta.4 with Google Pixel 6 (Android 12).

**Comment by AdinaPetridean** [comment]
Verified as fixed on Nightly 108.0a1 from 10/25 with Xperia 10 (Android 12). The widget has the Firefox Preview icon and the microphone icon displayed.

<img src="https://user-images.githubusercontent.com/108326843/197693723-6e4a67e9-fa98-4717-a5fa-6b8417174ba7.JPEG" width="50%" />

**Comment by SoftVision-LorandJanos** [comment]
Verified as fixed on the latest Beta 108.0b1.
Device used: Oppo Find X5 (Android 12).

**Comment by SoftVision-LorandJanos** [comment]
Verified as fixed on the latest Release (RC108.1.0).
Device used: Oppo Find X5 (Android 12).
