### ISSUE TITLE
Add the possibility to filter the saved logins Alphabetically or after Recently used

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/fenix#9326]
### Why/User Benefit/User Problem
As a Fenix user, I want to be able to filter the saved logins Alphabetically or after Recently used
### What/Requirements
Implement the ability to filter the saved logins Alphabetically or after Recently used.
Add a drop-down with those 2 options when tapping on the `Saved Logins`.

**Comment by ekager** [comment]
Closing for #9505
