### ISSUE TITLE
[Meta] Add onboarding cards to homescreen as Tips

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#9328]
As a user, I'd like a non-intrusive way to learn more about features in the app. Having onboard styled cards on my homescreen when I enter the app could be a lightweight way to learn these features!

## Acceptance Criteria
* Tips display in a "smart" fashion... don't show tips for features users have already engaged with
* Tips should be short in text & provide calls to action, allowing users to directly affect the feature they're given a message about
* Tips should be able to be hidden if users do *not* want them
* Different levels of severity of tips (some dismissable some not)

Success for this feature would involve a small % of our users disabling them (as we saw only ~5% of users disable it in Focus), and users regularly engaging with the tips

**Comment by AmyYLee** [comment]
Assigned to @apbitner

**Comment by AmyYLee** [comment]
@apbitner for follow-up

**Comment by apbitner** [comment]
This work was descoped from feature discoverability and is to be considered as part of home screen redesign exploration
