### ISSUE TITLE
Sign in button appears momentarily when user is logged into Firefox account

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/fenix#933]
## Steps to reproduce

1. Sign into Firefox account
2. Leave Settings
3. Open settings

### Expected behavior

The signed in username appears below "account"

### Actual behavior

"Sign In" button appears for a second before signed in username appears. 

### Device information

* Android device: Pixel 2
* Fenix version: 1.0.1910 (Build #10671222 :lizard: 67.0a1-20190305092747)

[signal-attachment-2019-03-09-134724.zip](https://github.com/mozilla-mobile/fenix/files/2948740/signal-attachment-2019-03-09-134724.zip)

**Comment by bsurd** [comment]
The sign in button is no longer displayed, altho I would like to mention that a @ Firefox Account text is displayed before the actual account name.
