### ISSUE TITLE
[Share] Share sheet implemented not according to spec

### ISSUE THREAD

**Issue by AmyYLee** [mozilla-mobile/fenix#9332]
Hi, 

The share sheet has has horizontal scroll instead of a vertical scroll layout. Please reference original spec for guidance (@topotropic):

https://mozilla.invisionapp.com/share/PSQFWZ1Y4W8#/screens/346059768

1. "Recently Used" should be it's own row with no grey background
2. "All Actions" should be the next row under it separated by a hairline above with vertical scroll (like native android share sheet). 

<img width="417" alt="Screen Shot 2020-03-23 at 16 52 12" src="https://user-images.githubusercontent.com/5992746/77362181-e8320b00-6d26-11ea-810d-c6c8e571d2c7.png">

**Comment by brampitoyo** [comment]
Clarification question for @AmyYLee and @topotropic: does the “Share a link” section have a certain ordering of items?

For example, “Copy link” seems to be the first item. Is it always the first item in all situations?

The app icons that come after “Copy link”, do they get sorted by recently used, alphabetical, etc.?

**Comment by cadeyrn** [comment]
https://mozilla.invisionapp.com/share/PSQFWZ1Y4W8#/screens/346059768 is an outdated spec, no? It still shows the "sessions" concept which no longer exists in Fenix, so it's a very old mockup. This mockup does not have a section for "recently used" at all. This feature was added in #4231 and there is a much newer mockup: https://app.abstract.com/share/e1a39a6b-2c3e-4fc4-b46c-0c78ec491112?mode=design&sha=f3bcad9f449216555fbf5cc31c3b9933b6538a96

**Comment by AmyYLee** [comment]
> https://mozilla.invisionapp.com/share/PSQFWZ1Y4W8#/screens/346059768 is an outdated spec, no? It still shows the "sessions" concept which no longer exists in Fenix, so it's a very old mockup. And this mockup does not have a section for "recently used" at all. This feature was added in #4231 and there is a much newer mockup: https://app.abstract.com/share/e1a39a6b-2c3e-4fc4-b46c-0c78ec491112?mode=design&sha=f3bcad9f449216555fbf5cc31c3b9933b6538a96

@topotropic - Can you provide feedback/guidance? It looks like this was a temporary fix.

**Comment by mcarare** [comment]
@topotropic I think we should also consider having the option to remove apps from recent list.

**Comment by ekager** [comment]
Yeah and the "recently used apps" section was added very recently but maybe was based on an older spec?
https://github.com/mozilla-mobile/fenix/issues/4231

Could UX please chime in here with direction of what the share sheet should look like today before we jump into fixing bugs with different mocks for each 😅

**Comment by AmyYLee** [comment]
> Yeah, the "recently used apps" section was added very recently in #4231 but maybe was based on an older spec? I'm not sure
> 
> Could UX please chime in here with the "truth" of what the share sheet should look like today before we jump into fixing bugs with different mocks for each 😅

@topotropic Can you assist with this?

**Comment by AmyYLee** [comment]
@topotropic For follow-up

**Comment by AmyYLee** [comment]
@topotropic - Does this need further ux-investigation?

**Comment by topotropic** [comment]
Amy's suggestions sounds good to me:

> * "Recently Used" should be it's own row with no grey background
> * "All Actions" should be the next row under it separated by a hairline above with vertical scroll (like native android share sheet).

@mcarare can you open a github issue to track your request? Thanks!
