### ISSUE TITLE
[Bug] Fenix should specify `noCompress 'ja'`

### ISSUE THREAD

**Issue by agi90** [mozilla-mobile/fenix#9333]
The `omni.ja` file contains all the javascript code that GeckoView uses internally. Right now the `omni.ja` file is compressed in the APK. This causes GeckoView to uncompress the omni.ja file in memory before it can start doing anything else. This takes a long time, on some profiles it delays startup by about 400ms.

We should specify `noCompress 'ja'` in the `aaptOptions` to avoid that.

See also: https://bugzilla.mozilla.org/show_bug.cgi?id=1623758

**Comment by mstange** [comment]
I confirmed that this does the trick:

```diff
diff --git a/app/build.gradle b/app/build.gradle
index eb0e32bf..33161aab 100644
--- a/app/build.gradle
+++ b/app/build.gradle
@@ -164,16 +164,20 @@ android {
             setIgnore true
         }

         if (buildType.name == 'fennecNightly' && flavors.contains("geckobeta")) {
             setIgnore true
         }
     }

+    aaptOptions {
+        noCompress 'ja'
+    }
+
     testOptions {
         execution 'ANDROIDX_TEST_ORCHESTRATOR'
         unitTests.includeAndroidResources = true
         animationsDisabled = true
     }

     flavorDimensions "engine"
```

**Comment by mstange** [comment]
Profile: https://perfht.ml/2xWfiAq

(After this, the biggest remaining pieces are now https://bugzilla.mozilla.org/show_bug.cgi?id=1618391 (300ms) and https://bugzilla.mozilla.org/show_bug.cgi?id=1621340 (130ms).)

**Comment by csadilek** [comment]
Thanks @agi and @mstange! Opened a PR with you as authors :) https://github.com/mozilla-mobile/fenix/pull/9363

**Comment by mcomella** [comment]
@csadilek Any QA labels needed here?

**Comment by mstange** [comment]
Thanks Christian!

I've verified that the fix had an effect on today's Firefox Preview Nightly on the Play Store.
Before/after profiles: https://perfht.ml/2xNSt1O / https://bit.ly/2QKnEln
