### ISSUE TITLE
[Bug] Collections Padding

### ISSUE THREAD

**Issue by emalysz** [mozilla-mobile/fenix#9335]
## Steps to reproduce
Add a few different collections 
Start expanding and collapsing tabs

### Expected behavior
The padding will remain consistent

### Actual behavior
The padding changes somewhat randomly. Sometimes it will be a condensed version, other times the bottom and top will be padded, other times only one will have padding. 

### Device information
Pixel2

Here are two screenshots: 
![Screenshot_20200319-154531](https://user-images.githubusercontent.com/15795071/77366465-4e159700-6d15-11ea-80a8-2dbf2f2be545.png)
![Screenshot_20200319-154942](https://user-images.githubusercontent.com/15795071/77366470-5077f100-6d15-11ea-8b9a-9be51d21710f.png)

Notice how the collection 1 padding is different. 

Not the exact behavior described in https://github.com/mozilla-mobile/fenix/issues/3004, but I could also just add this to that issue if easier.

**Comment by eliserichards** [comment]
Closing in favor of #3004
