### ISSUE TITLE
DefaultSearchController navgraph crash

### ISSUE THREAD

**Issue by liuche** [mozilla-mobile/fenix#9336]
Filing from Sentry crash report: https://sentry.prod.mozaws.net/operations/fenix/issues/7566392/
```
IllegalArgumentException: navigation destination
org.mozilla.fenix:id/action_searchFragment_to_searchEngineFragment is
unknown to this NavController
```

* Android device: any
* Fenix version: first appears in 4.1

**Comment by softvision-miralobontiu** [comment]
I was not able to reproduce the crash on the latest Nightly build from 3/4 with Google Pixel (Android 10), OnePlus 5T (Android 9), and Sony Xperia Z5 Premium (Android 7.1.1).

STR:
* open Fenix, go to Settings - Search
* tap back really quickly
* repeat several times
