### ISSUE TITLE
Remove nightly-only feature flag for WebPush

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/fenix#9338]
Once [bug 1619778][0] lands in GeckoView beta (76+), we can remove [the feature flag][1] from Fenix and let it ride the trains.

The next GV beta is scheduled for April 7th.

[0]: https://bugzilla.mozilla.org/show_bug.cgi?id=1619778
[1]: https://github.com/mozilla-mobile/fenix/blob/9feb44852b3970d94de9acaccfb797c20e65ae95/app/src/main/java/org/mozilla/fenix/FeatureFlags.kt#L62-L69

**Comment by liuche** [comment]
Uplifted into GV 75, so if AC is going to take another GV update for Beta Migration, this could be turned on.

**Comment by jonalmeida** [comment]
I'd like to have https://github.com/mozilla-mobile/android-components/issues/6456 fixed first since it had a few (non-crash) errors we can fix.

**Comment by jonalmeida** [comment]
> I'd like to have https://github.com/mozilla-mobile/android-components/issues/6456 fixed first since it had a few (non-crash) errors we can fix.

The fix has landed, but we'd like to see the exception rates to go down before we enable it for our wider beta/release users. We could overload Sentry otherwise.

cc @liuche

**Comment by jonalmeida** [comment]
I'm fairly satisfied with the exception rates we're seeing in Sentry - no issues in new builds have occurred so far.
