### ISSUE TITLE
[Bug] Youtube full screen has nav bar flicker 

### ISSUE THREAD

**Issue by emalysz** [mozilla-mobile/fenix#9339]
## Steps to reproduce
Select a youtube video and click full screen

### Expected behavior
A seamless transition that happens as soon as possible.

### Actual behavior
The full screen video is shown, the nav bar then disappears and leaves a giant white gap. This causes a flicker that takes away from perceived performance. 

### Device information
Pixel 2, FF is in dark mode, device is using dark theme

Here's a video: 
[videoFlicker.mp4.zip](https://github.com/mozilla-mobile/fenix/files/4372385/videoFlicker.mp4.zip)

**Comment by mcomella** [comment]
Perf triage: this is a nice to have so we'd like the Fenix team to take a look if possible. For us, we're focused on "Must have"s at the moment so placing in Low Impact.

**Comment by mcomella** [comment]
We don't expect the perf team to address flickering anymore – removing perf tags.

**Comment by sflorean** [comment]
This issue is still reproducible (1/3 times) on latest Nightly with Pixel 3 (Android Beta 12).
