### ISSUE TITLE
[Bug] Full screen video causes entire UI to flicker

### ISSUE THREAD

**Issue by emalysz** [mozilla-mobile/fenix#9340]
## Steps to reproduce
Navigate to cnn.com, click on a video

### Expected behavior
Seamless transition to full screen video.

### Actual behavior
It will expand the video, then disappear, and then expand again. This is a very choppy experience and impacts perceived performance.

### Device information
Pixel2

[cnnFullScreen.mp4.zip](https://github.com/mozilla-mobile/fenix/files/4372416/cnnFullScreen.mp4.zip)

**Comment by mcomella** [comment]
Perf triage: this is a nice to have so we'd like the Fenix team to take a look if possible. For us, we're focused on "Must have"s at the moment so placing in Low Impact.

**Comment by mcomella** [comment]
We don't expect the perf team to address flickering anymore – removing perf tags.

**Comment by sflorean** [comment]
@emalysz I wasn't able to reproduce this issue on latest Nightly with Pixel 3 (Android beta 12) following your steps. After entering fullscreen mode, no visual issues were displayed. 
Is this still reproducible for you?
