### ISSUE TITLE
(Features) Bookmarking

### ISSUE THREAD

**Issue by andrecc-7** [mozilla-mobile/fenix#9345]
Just a list of features firefox lacks related to bookmarks:

- It's not part of firefox settings the default folder where bookmarks should go.
- There are too many top-level bookmark folders (Other Bookmarks, Bookmark Menu, Bookmark Bar, Mobile Bookmarks).
- There is no way to set if bookmarks should go on top or how they should be ordered by default (people may want them sorted by dates, but some may want a custom sort, it depends on usage and taste).
- Top sites are not linked at all to bookmarks. Why? Nobody thought about that? I'm sure they did! Why then let the feature be implemented that way some many times?

This are just my issues, but I'm sure if you ask users for what they expect from a bookmark feature they'll have way more ideas. I think firefox has a lot to improve there.

**Comment by cadeyrn** [comment]
Let's say they want to implement one of your requests but another request is a WONTFIX. How should they label this issue? You should file one feature request per issue.

**Comment by andrecc-7** [comment]
I'll separate each request.

**Comment by andrecc-7** [comment]
Should I post it somewhere related to desktop, because the bookmark system on mobile is more of a lite version of the system on desktop?

**Comment by MrAdam** [comment]
I just added one issue related to your third point: #9389

**Comment by MrAdam** [comment]
Added another issue somehow related to your first point: #9390
