### ISSUE TITLE
[Bug] Collections dependance on keyboard

### ISSUE THREAD

**Issue by andrecc-7** [mozilla-mobile/fenix#9348]
I use a keyboard app that doesn't have implemented the done button; so after writing the name of a collection I cannot create the collection. I think firefox shouldn't depend on a keyboard feature. But that's just an opinion. Could you solve this in a future update?

<img src="https://user-images.githubusercontent.com/56041659/77385007-ce241700-6d7e-11ea-988e-0313a17b6e7e.png" width=200>

**Comment by andrecc-7** [comment]
And then it remained forgotten... forever.

**Comment by ekager** [comment]
If you add collections through the tabs tray, the flow is now different. Does that solve your issue?

**Comment by andrecc-7** [comment]
Hei, yes the issue was solved with the new interface!

**Comment by sflorean** [comment]
Closing based on the above comment and based on the fact that the behavior had changed.
