### ISSUE TITLE
Add a "little diagonal arrow" button to apply the URL/search suggestion in the URL bar

### ISSUE THREAD

**Issue by pavi2410** [mozilla-mobile/fenix#9350]
### Why?
The Google Search, Chrome and YouTube apps have this icon and it serves as a good utility when one wants to "extend" or modify a suggestion.

https://ux.stackexchange.com/questions/112605/help-identifying-up-left-arrow-android-material-design-icon-usage

**Comment by pavi2410** [comment]
Related issues #8043

**Comment by sflorean** [comment]
This is implemented, closing as fixed.
