### ISSUE TITLE
[Bug]Confirmation snackbars aren't displayed on Beta 4.2.0-beta.1

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#9351]
## Steps to reproduce
1. Navigate to CNN.com
2. Long tap on the featured news image.
3. Tap on "Open link in new tab"

### Expected behavior
A "New tab opened" + "Switch" (button) confirmation snackbar is displayed.

### Actual behavior
No confirmation snackbar is displayed.

### Device information

* Android device: 
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)

* Fenix version: Beta 4.2.0-beta.1

### Notes
❗️ Not reproducible on the the latest Nightly Build #20840606 from 3/24
❗️ Happening if the user taps the following options from the context menu:
• "Open link in private tab"
• "Copy link"
• Open image in new tab
• Copy image location

► ❌ Video form Beta 4.2.0
![20200324-094629](https://user-images.githubusercontent.com/51314259/77401686-08f57180-6db6-11ea-8911-139b3ad3a53a.gif)

► ✔️ Video from latest Nightly
![20200324-094456](https://user-images.githubusercontent.com/51314259/77401594-df3c4a80-6db5-11ea-859a-e5ea8ca0d014.gif)

**Comment by softvision-miralobontiu** [comment]
Also, the "Added to top sites!" snackbar is not displayed on Beta 4.2.0-beta.1. Tested with Google Pixel (Android 10), OnePlus 5T (Android 9), and Sony Xperia Z5 Premium (Android 7.1.1).

**Comment by softvision-miralobontiu** [comment]
Verified as fixed on Beta 4.2.0-beta.2 with OnePlus 5T (Android 9), and Sony Xperia Z5 Premium (Android 7.1.1). 
The following snackbars are displayed again, as expected:
- "New tab opened SWITCH",
- "New private tab opened SWITCH",
- "Link copied to clipboard",
- "Added to top sites!".
