### ISSUE TITLE
[Bug] Cannot log in to (Microsoft) Mixer app

### ISSUE THREAD

**Issue by SyntaxErrol** [mozilla-mobile/fenix#9355]
## Steps to reproduce
1. Set Firefox Preview as the default browser
2. Download Mixer https://play.google.com/store/apps/details?id=com.mcprohosting.beam&hl=en
3. Open Mixer and try to log in with a Microsoft/Xbox Live accont

## Expected behavior
You are logged in to Mixer.

## Actual behavior
You are taken to the Goole Play store page of Mixer. Setting the device default browser temporarily to Chrome makes the login process work.

## Device information
* Android device: Nokia 6.1 on Android 10
* Fenix version: 4.1.0 (Build #20771637)

**Comment by ekager** [comment]
@SyntaxErrol is this still a problem for you?

**Comment by SyntaxErrol** [comment]
No, mainly because Microsoft has since shut down the platform. ;)

**Comment by ekager** [comment]
Cool! Works for me! Let's close this :)
