### ISSUE TITLE
Add pause and resume button for downloads

### ISSUE THREAD

**Issue by minutesinch** [mozilla-mobile/fenix#9357]
### Why/User Benefit/User Problem
users need pause and resume button in download mager part in browser
### What/Requirements
a pause and resume buttons and working well
### Acceptance Criteria (how do I know when I’m done?)
just try save a file near 100 mb and when download near 20mg or 50 mg try to pause, after a few second(at least 10 second) try to resume,
do this and replace with minutes and hours for better results

**Comment by liuche** [comment]
Going to dupe this to #8930 which is tracking some AC work.
