### ISSUE TITLE
[Bug] Menu not reversed if the toolbar position is changed to top (opened from Fenix homescreen)

### ISSUE THREAD

**Issue by sflorean** [mozilla-mobile/fenix#9365]
## Steps to reproduce
1. Open Fenix and go to Settings-> Customize - Toolbar.
2. Set to "Top".
3. Go to the home screen.
4. Tap on the three-dot menu. 

### Expected behavior
The menu is reversed. 

### Actual behavior
The menu is displayed the same as for toolbar position to bottom.

### Device information

* Android device: Samsung Galaxy Note10 (Android 9.0), Xiaomi Mi Pad 2 (Android 5.1).
* Fenix version: Beta v4.2.0-beta.1, Nightly 3/24.

![top](https://user-images.githubusercontent.com/58466444/77444420-09d3d680-6da9-11ea-9176-571ff1283c08.jpg)

**Comment by mcarare** [comment]
For UX: How should the reverse menu look, taking into account the "Library" section?

**Comment by brampitoyo** [comment]
@mcarare When toolbar is set to top, the main menu items should be ordered in reverse, like this:

### Main menu on homescreen (top to bottom)

Help
Settings

--

**Library**
Bookmarks
History

--

What’s new

### Main menu on sites (top to bottom)

Bookmark | Share | Forward | Refresh

--

Reader view
Desktop site
Save to collection
Add to home screen
Add to top sites
Find in page
Report site issue

--

Settings
Add-ons
Library

--

(Any add-on you have installed goes here)

**Comment by mcarare** [comment]
@brampitoyo , I suppose also, "Quit", if existing, will be on top.

**Comment by brampitoyo** [comment]
@mcarare I could be wrong, but I thought there’s no longer a “Quit” list item in the main menu?

If exists, “Quit” should be the last item on the list. Meaning: if the toolbar is on bottom, then “Quit” should sit on the very top of the list. If the toolbar is on top, then “Quit” should sit on the very bottom.

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly Build #20970607 from 4/6`** using a Google Pixel 3a (Android 10)

► Screenshot Home screen
![Screenshot_20200406-101655](https://user-images.githubusercontent.com/51314259/78533019-e2412d00-77f0-11ea-89b7-683d3368db5a.png)


► Screenshot Page view
![Screenshot_20200406-101546](https://user-images.githubusercontent.com/51314259/78533028-e4a38700-77f0-11ea-9617-9cc3e0a226fe.png)
