### ISSUE TITLE
[Bug] Device name is reset to default everytime I update the app

### ISSUE THREAD

**Issue by st3fan** [mozilla-mobile/fenix#9368]
> Taken from https://bugzilla.mozilla.org/show_bug.cgi?id=1623288

Steps to reproduce:

On Firefox Preview for Android I changed Device name in Account settings, then I updated the app.

Actual results:

Device name is reset to default.

Expected results:

Device name should've been kept the same as the last time I changed it.

**Comment by cadeyrn** [comment]
sounds like #8246.
