### ISSUE TITLE
[Bug] Unable to save/ download image

### ISSUE THREAD

**Issue by areeshatariq** [mozilla-mobile/fenix#9381]
## Steps to reproduce

- Search using **Google Images**
- Long-press an image 
- Click **Save image**
- Open an image
- Long-press the image

### Expected behavior

- When a user opens and long-presses an image, a pop-up appears to download the image
- When the 'Save image' is selected from the pop-up, the image is downloaded

### Actual behavior

- When a user long presses an image and clicks ‘Save image’, the image is not saved/ downloaded and a pop-up is displayed ‘Firefox Preview can’t download this file type’.

<p align="center"><img src="https://user-images.githubusercontent.com/24654457/76316399-5ffe3f80-62fc-11ea-8004-74fcaf7eec5e.png" align="center" width="50%" height="50%"></p>

- If the user opens the image and long presses it, no pop-up to save/ download the image appears on the screen.

### Device information

* Android device: Android 10
* Fenix version: 4.1.0

**Comment by liuche** [comment]
Duping this to #8559
