### ISSUE TITLE
[Bug] Button animations on address bar not working

### ISSUE THREAD

**Issue by theFireProjet** [mozilla-mobile/fenix#9385]
## Steps to reproduce
Hold down the 'New tab' and the 'Menu' button on the tabs page as well as the Enhanced Tracking Protection (shield) button and the website info (lock) button on a website to inspect their button animations.

### Expected behavior
Button animations should be visible underneath the button, but on top of the layer behind that button, so they should be **directly** behind the button. It's supposed to be the same way it looks for the 'Tabs' button and for the 'Menu' button when on a website instead of the tabs page:
![20200402_163532](https://user-images.githubusercontent.com/61639215/78261873-16220700-7500-11ea-82f8-658441be32dc.jpg)
![20200402_163547](https://user-images.githubusercontent.com/61639215/78261895-1f12d880-7500-11ea-9f6f-e5bcb6c6f600.jpg)

### Actual behavior
- Button animation of the 'New tab' button is not visible on the address bar, it's visible underneath the address bar as it sticks out on the background of the tabs page:
![20200325_043050](https://user-images.githubusercontent.com/61639215/77499252-e749c800-6e51-11ea-81f9-4c4577f8263e.jpg)
- Button animation of the 'Menu' button is missing when on the tabs page instead of a website:
![20200325_043112](https://user-images.githubusercontent.com/61639215/77499272-f3ce2080-6e51-11ea-9bc8-6b9c2dbfd9a5.jpg)
- Button animations of the Enhanced Tracking Protection button (shield) and the website info button (lock) don't appear **directly** underneath the button (which would be on top of the background of the address field), but instead they stick out underneath the background:
![20200402_162048](https://user-images.githubusercontent.com/61639215/78260398-35b83000-74fe-11ea-81c7-3c06d4694c9d.jpg)
![20200402_162119](https://user-images.githubusercontent.com/61639215/78260405-3781f380-74fe-11ea-8b40-39c05e4124a7.jpg)

### Device information

* Android device: Samsung Galaxy S9+ (Android 8.0.0)
* Fenix version: 4.2.0

**Comment by asavill** [comment]
I would be happy to look at this if it goes through triage and needs some help.

**Comment by theFireProjet** [comment]
That would be great! (I'm not yet a developer, only a user)
Small update: To be exact the animation of the 'Enhanced Tracking Protection' button (the shield) on the address bar is not correct either. (See above)

**Comment by sflorean** [comment]
@theFireProjet I wasn't able to reproduce this on latest Nightly. Could you please try if see if it works for you? thank you!

**Comment by ekager** [comment]
Closing
