### ISSUE TITLE
Shortcut on long-pressing 'Add new bookmark' button: Add and edit new bookmark in one step

### ISSUE THREAD

**Issue by theFireProject** [mozilla-mobile/fenix#9388]
### Why/User Benefit/User Problem
It's an much easier way to instantly edit a new bookmark f.e. to save it in a specific folder or to rename it.
Currently, doing this needs 4 screen interactions:
Touch to open the menu, touch the 'Add new bookmark' button, touch to open menu, touch the same button now represeting the saved bookmark to edit the bookmark.
The goal is an intuitive way of editing your new bookmark quickly requiring only half the steps:
Touch to open the menu, long-press the 'Add new bookmark' button.

### What/Requirements
New action that happens when long-pressing the not filled 'Bookmark' (star) button:
- Adding the current site to bookmarks as well as
- opening the 'Edit bookmark' view for that new bookmark.

### Acceptance Criteria (how do I know when I’m done?)
Long-pressing the 'Bookmark' (star) button in the menu will add the current website to your bookmarks (as it does when normally tapping that button) and the 'Edit bookmark' view will instantly appear to edit the new bookmark.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-16417)

**Comment by bigConifer** [comment]
Just press the bookmark snackbar "Edit" button, that's one simple step:

![20220526_150111](https://user-images.githubusercontent.com/64743731/170493304-f7eddeb3-c0d1-43e5-a3ee-d0c632511ada.jpg)
<br>

> The goal is an intuitive way of editing your new bookmark quickly requiring only half the steps:
Touch to open the menu, long-press the 'Add new bookmark' button.

Long pressing an item in the 3-dot Toolbar Menu is definitely not an intuitive way.

Therefore, I would suggest closing this ticket.

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812716

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
