### ISSUE TITLE
Bookmarks should be added to end of folder, as on desktop

### ISSUE THREAD

**Issue by MrAdam** [mozilla-mobile/fenix#9389]
### Why/User Benefit/User Problem
It's much more logical to have bookmark adding work the same way on desktop and on mobile.
I'm used to adding a bookmark in the bookmark toolbar folder for a site that I want to read later, which on desktop adds it to the end of the folder. On mobile however, it adds it to the front of the folder, pushing the folders I have in the beginning of my bookmark toolbar further towards the overflow meny.

### What/Requirements
Adding a bookmark should add it to the end of that folder.

### Acceptance Criteria (how do I know when I’m done?)
* Changing the folder on the "Edit bookmark" page and saving, results in the bookmark ending up at the end of the selected folder.

**Comment by apbitner** [comment]
@topotropic Thoughts on new bookmark placement?

**Comment by topotropic** [comment]
Thanks for filing the issue. The rational here is that you can access your most recently saved bookmarks quickly w/o having to scroll to the bottom of a list. So this is by design – feel free to re-open the issue if you feel strongly about it. 
Thanks again for your contribution!

**Comment by MrAdam** [comment]
@topotropic, the issue for me is the inconsistency between the desktop and mobile versions of Firefox.
I would assume that adding bookmarks to a folder that syncs between two versions of the app, would behave the same.
