### ISSUE TITLE
Switching sessions is laggy and has displaying issues

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#939]
## Steps to reproduce
1. Create a few saved sessions so you can scroll them to hide the current session.
2. Tap one from the bottom of the list to restore it.
3. Check the results in the current session view.

### Expected behavior
The page scrolls up and displays the restored tabs.
### Actual behavior
The scroll doesn't always happen instantly.
The restored tabs have no title bar, are not entirely displayed or don't refresh automatically until you drag the page to refresh. See screencaps & recording
![Screenshot_20190311-171705](https://user-images.githubusercontent.com/4037709/54135581-c23f0e80-4422-11e9-8ba1-baabcdff25dd.png)
![Screenshot_20190311-171919](https://user-images.githubusercontent.com/4037709/54135588-c3703b80-4422-11e9-9b3a-c553cc6ddb95.png)
[Recording](https://drive.google.com/file/d/1e2-p56BV3V1WNGNtirLrfI3v1xBKSwzh/view?usp=sharing)
### Device information

* Android device: Pixel (Android 9), Nexus 5 (Android 6).
* Fenix version: 3/11 master build.

**Comment by rpappalax** [comment]
I also noticed app freeze (intermittent) on swiping up and down on session view. 
* Android device: Nexus 6P

**Comment by vesta0** [comment]
The session restore stops working after attempts to restore more than 2-3 sessions (depending on number tabs?)

**Comment by ekager** [comment]
Are we still seeing the same issues? We've made some changes to the sessions/tabs on the home screen

**Comment by sv-ohorvath** [comment]
No these are not occurring anymore on the latest build. I'll close the ticket. thanks!
