### ISSUE TITLE
Allow setting/remembering folder for new bookmarks

### ISSUE THREAD

**Issue by MrAdam** [mozilla-mobile/fenix#9390]
### Why/User Benefit/User Problem
I'm used to adding a bookmark in the bookmark toolbar folder for a site that I want to read later, which at the moment requires me repeating the same steps of bookmarking, editing, changing folder and saving almost every time I add a bookmark, which becomes a PITA after a few bookmarks. In Chrome, it remembers the last used bookmark folder, which makes this a lot easier.

### What/Requirements
Adding a new bookmark should default to saving to the last used bookmark folder.

### Acceptance Criteria (how do I know when I’m done?)
Pressing the 'Bookmark' button in the menu will add the current page to your bookmarks, in the last used bookmark folder.

**Comment by yoasif** [comment]
Similar to https://github.com/mozilla-mobile/fenix/issues/9454.

I think this issue is more vital.

**Comment by apbitner** [comment]
@topotropic Another bookmark related consideration

**Comment by topotropic** [comment]
Thanks for the feedback, it's a valid point – we'll take this into account for future iterations.
