### ISSUE TITLE
[Bug] Accessing Settings without network connection causes Fenix to crash

### ISSUE THREAD

**Issue by SL-Lee** [mozilla-mobile/fenix#9391]
## Steps to reproduce

**Prerequisite: Firefox sync must be turned on.**

1. Make sure Fenix is closed (using the quit button in the menu), then disconnect the device from any network.
2. Open Fenix and access settings.

### Expected behavior

Fenix opens settings.

### Actual behavior

Fenix crashes.

**Other Notes**

* After performing the STR, restart Fenix and turn on the network connection. Go to settings > account. The device name is reset to the default value (might be related to #7199).

  ![](https://user-images.githubusercontent.com/45960387/77521657-0120f480-6ebe-11ea-8fe8-ddbf71d124fb.gif)

  Tapping on it will bring up a dialog box with the changed name, and performing a sync will change it back. But this doesn't work reliably -- I've seen occurrences where the device name resets to the default value.

### Device information

* Android device: Oppo Reno 2, Android 9
* Fenix version: Nightly 200325 06:01 (Build #20850609)

**Comment by grigoryk** [comment]
This is fixed by https://github.com/mozilla-mobile/fenix/pull/9532
