### ISSUE TITLE
[Bug]Fenix allows to create no name custom search engines

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#9395]
## Prerequisites
Have a custom search engine created in Fenix.
E.g. Name = `Ecosia` Search string to use: `ecosia.org/search?q=%s`

## Steps to reproduce
1.  Identify the custom search engine in the search section
2. Tap the ⋮ button next to the custom search engine and tap on "Edit"
3. Completely remove the Name ("Ecosia"), and afterwards tap the "space key" from your keyboard and confirm

### Expected behavior
"Enter search engine name" error message should be displayed.

### Actual behavior
A custom search engine without any name is created.
### Device information

* Android device: OnePlus A3 (Android 6.0.1)
* Fenix version: 
Fenix Nightly Build #20850609 from 3/25
Fenix Beta 4.2.0-beta.2

### Notes
► Video
![20200325-142648](https://user-images.githubusercontent.com/51314259/77537461-d4151780-6ea6-11ea-9170-e5de65791dce.gif)

**Comment by sv-sdeiac** [comment]
Hi, I can reproduce the issue using the latest version of Firefox Preview Nightly 3/26 #20860605.
@BranescuMihai can you take a look at this one?

Devices:
- Samsung Galaxy Tab S6 (Android 9);
- Xiaomi Mi 8 Lite (Android 9);
- LG g7 fit (Android 8.1).

**Comment by BranescuMihai** [comment]
@sv-sdeiac I think the issue was that it wasn't merged yet, I'm sorry for that. Can you please retest?

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly Build #21060608 from 4/15`** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)

► Video
![20200415-143134](https://user-images.githubusercontent.com/51314259/79333148-b0ce0d00-7f26-11ea-8607-3d216fd1fe98.gif)
