### ISSUE TITLE
[Bug] Wrong error on Edit custom search engine screen

### ISSUE THREAD

**Issue by BranescuMihai** [mozilla-mobile/fenix#9403]
## Steps to reproduce
Add a custom search engine
Go to edit custom search engine
Change 'String to use' to a string that doesn't contain `%s` (example: "www.aaa.com")

### Expected behavior
"Check that search string matches Example format" error is displayed below search string field

### Actual behavior
"Check that search string matches Example format" error is displayed below name field

### Device information

* Android device: Any
* Fenix version: 1.0.2013(Build#1) - latest develop

<img src="https://user-images.githubusercontent.com/1709373/77551394-f87aef00-6eba-11ea-8fd4-acd705ec3119.png" width="300px"/>

**Comment by sv-sdeiac** [comment]
Verified that this issue is fixed using the latest version of Firefox Preview Nightly 3/29 @20891805. 
The error message is displayed below the search string field.

Devices:
- Google Pixel 3 (Android 10);
- Xiaomi Mi 8 Lite (Android 9);
- LG g7 fit (Android 8.1).
