### ISSUE TITLE
Search suggestions seem slow (150 first time, 110-120 subsequent G5)

### ISSUE THREAD

**Issue by MarcLeclair** [mozilla-mobile/fenix#9406]
### Problem
Base on investigation from #9112, I found that typing in the url bar takes about 150ms after the first character to update the search suggestion. Every subsequent character entered will take 110-120ms)

The definition, in this case, of the final state was when the 
search suggestions were clickable by the user.

### Methodology Used

The time spent on entering the value in the url bar ( which was found in Android-Component) with `System.nanoTime()`.  

The `startTime` was added in the `update` in the recyclerview adapter.

The `endTime` was added in `onBindViewHolder` of the `SuggestionsAdapter` when the `adapterlist` binds its last element: 
 ***This class is found in Android Component

**Comment by mcomella** [comment]
https://github.com/mozilla-mobile/fenix/issues/9746 is a P1 responsiveness issue that may have a similar cause as this issue. I did some research there that you should look at before tackling this issue: https://github.com/mozilla-mobile/fenix/issues/9746#issuecomment-613696818

**Comment by MarcLeclair** [comment]
After some investigation, I noticed that we do have a "jankiness" interms of updating the recyclerview of suggestion. This means that once we enter a letter in the search bar, our `HistoryStorageProviders` will usually go through the rendering first, and we will update the recyclerview afterwards with the results from the search suggestions (i.e: `facebook` for `f` and so on). This means that we have this weird behavior seen in here https://streamable.com/4ftbdp 

However, each providers are relatively quick individually. The issue arises when we're drawing first and second. This means that we aren't blocking the Main Thread in between providers, but it just gives a janky feeling to the app. The TOTAL time from entering the letter to when we have all our providers rendered takes ~200-300ms when there's more than 1 provider. For a single provider, it would take ~80ms

**Comment by mcomella** [comment]
Triage: a lot has changed since this was opened and we haven't seen evidence this is still a problem. We will open a new issue if we decide to reinvestigate.
