### ISSUE TITLE
[Bug] No App Icon Assigned for Leanplum Push Notifications

### ISSUE THREAD

**Issue by cbonacuse** [mozilla-mobile/fenix#9409]
## Steps to reproduce
- When sending a notification using the Preview app, there is no icon set to display for the app.

### Expected behavior
- Should have the Preview icon

### Actual behavior
- A gray circle is instead displayed

### Device information

* Android device: Google Pixel 3 OS 10
* Fenix version: 4.1.0

This is the documentation provided by Leanplum to add an icon for the app: https://docs.leanplum.com/docs/customize-your-push-notifications-sample-android
![Screenshot_20200324-171447](https://user-images.githubusercontent.com/60749496/77583688-e64b8180-6eb7-11ea-9542-fdf794df25c8.png)

**Comment by lwa-moz** [comment]
@jonalmeida @st3fan for visibility

**Comment by jonalmeida** [comment]
This should be fixed when the linked PR lands:

<img width="520" alt="Screen Shot 2020-04-15 at 3 37 27 PM" src="https://user-images.githubusercontent.com/1370580/79380898-1a521980-7f2f-11ea-9bfd-a66323aa9aa0.png">

**Comment by jonalmeida** [comment]
Sending a test notification in the nightly app with an Android 10 device should no longer show this grey circle icon.

**Comment by lwa-moz** [comment]
@jonalmeida sounds good - to make 100% sure we're testing the right app. By "Nightly app" would that be Preview Nightly, Fennec Nightly, or both?

**Comment by jonalmeida** [comment]
Correct, both should work.

**Comment by cbonacuse** [comment]
@jonalmeida I just contacted Loren since I wasn't seeing the update in the Firefox Preview app yet. Just to confirm, I never experienced this issue in any Beta & Nightly tests I had done, just solely in Firefox Preview. Does this mean the fix won't be complete in Firefox Preview until the next update to that app?

**Comment by jonalmeida** [comment]
> Does this mean the fix won't be complete in Firefox Preview until the next update to that app?

@cbonacuse this has landed in Fenix and Fennec Nightly. There hasn't been a new fennec beta build since this landed so it would only make it for the next release.

**Comment by AndiAJ** [comment]
Hi, I've just checked this matter on:
• Fenix Nightly 200429 from 4/29
• Fenix Beta 5.0.0-beta.1 from 4/29
• Fennec Nightly 200429 from 4/29

using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)

✔️ **Fenix Nightly** 
![rsz_1rsz_1screenshot_20200429-184102](https://user-images.githubusercontent.com/51314259/80618077-8b272480-8a4b-11ea-93b1-e4c1f7110961.png)


❌ **Fenix Beta 5.0.0-beta.1** - **No push token got generated**
![rsz_allbeta](https://user-images.githubusercontent.com/51314259/80618999-c544f600-8a4c-11ea-9045-0690845eecc1.jpg)

✔️ **Fennec Nightly 200429**
![rsz_fennec](https://user-images.githubusercontent.com/51314259/80619796-de9a7200-8a4d-11ea-95a4-5d23eda2861d.png)

@jonalmeida - Please review and share your thoughts. ☺️ 
I'll remove the QA needed label until further notice

**Comment by jonalmeida** [comment]
> Fenix Beta 5.0.0-beta.1  No push token got generated

We should check if we want to switch from the GCM token to the FCM for beta now that we are considering it fully migrated.

**Comment by cbonacuse** [comment]
@jonalmeida please keep the token as-is - we have messages going out to users still on the Fennec code in Beta through next week. cc: @lwa-moz

**Comment by jonalmeida** [comment]
> @jonalmeida please keep the token as-is - we have messages going out to users still on the Fennec code in Beta through next week. cc: @lwa-moz 

Thank you for clarifying! We can close this as tested then since it works on nightly and should do the same when we switch the tokens over.

**Comment by cbonacuse** [comment]
Hi @jonalmeida, Liza tested this today for the first time in Beta Fenix and is not seeing the app icon. I ran a test in Firefox Preview and this _did_ work for me. Did the update somehow skip Beta even though the fix was in the Preview release on 4/30? Below is our device information:

**Liza's test that did not work as expected:**

- App: Firefox Beta
- Device: OnePlus ONEPLUS A6013
- OS: 10
- App version: 75.0.0-beta.6

**Caitlin's test that worked as expected:**

- App: Firefox Preview
- Device: Google Pixel 3
- OS: 10
- App version: 4.3.0

cc: @lwa-moz & @st3fan for visibility 
![Beta](https://user-images.githubusercontent.com/60749496/81853983-398e9780-952b-11ea-9bc7-427e766c4a51.jpg)

**Comment by vesta0** [comment]
@liuche this bug wasn't fixed in Firefox Beta as of last Friday but it works in Preview. Can we keep it open until it is fixed in Beta?

**Comment by liuche** [comment]
We're currently at 5% rollout for Firefox Beta: https://bugzilla.mozilla.org/show_bug.cgi?id=1639964

So once we hit 100% we can validate/close this, or you can also test on the builds here: https://firefox-ci-tc.services.mozilla.com/tasks/index/project.mobile.fenix.v2.beta.2020.06.02.revision

**Comment by cbonacuse** [comment]
Confirmed this is fixed in Beta ([QA campaign in LP here](https://www.leanplum.com/dashboard#/5200078867791872/messaging/6346484983136256)).

Thank you! This can be closed out.
![Screenshot_20200602-170145](https://user-images.githubusercontent.com/60749496/83570126-8397e700-a4f3-11ea-9cf2-2be8e0b779e5.png)

**Comment by AndiAJ** [comment]
Hi, I've just checked this matter on both **`Fenix Beta 5.2.0-beta.2 from 6/16`** and **`Firefox Migration Build 5.2.0-beta.2 from 6/16`**  from using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)

✔️ **`Firefox Migration Build 5.2.0-beta.2`**
![rsz_1rsz_screenshot_20200622-163345](https://user-images.githubusercontent.com/51314259/85294784-bf491f80-b4a7-11ea-8915-4f8251b89f51.png)

❌ **`Fenix Beta 5.2.0-beta.2 from 6/16`** - No push tokens 

@jonalmeida - Please review and advise. ☺️

**Comment by jonalmeida** [comment]
@AndiAJ 

>  Fenix Beta 5.2.0-beta.2 from 6/16- 
> No push tokens

This is expected. Fenix beta builds no longer have Leamplum enabled.
