### ISSUE TITLE
As a Developer I want to export strings that need to be translated

### ISSUE THREAD

**Issue by st3fan** [mozilla-mobile/fenix#941]
### Why/User Benefit/User Problem

As a Developer I want to export strings that need to be translated. Either via a documented process or through some form of automation.

### Acceptance Criteria (how do I know when I’m done?)

- When new strings are introduced, I know what to do to make these available to the team that translates these strings.

### Linked Issues

- https://github.com/mozilla-mobile/fenix/issues/217

**Comment by Pike** [comment]
Is https://github.com/mozilla-l10n/android-l10n-tooling#exporting the resolution to this bug?

Maybe that's for @pocmo to decide, as in, point out what's missing?

**Comment by Pike** [comment]
@Callek and I can do this, so we're marking this FIXED.
