### ISSUE TITLE
Change share menu to vertically-scrolling menu.

### ISSUE THREAD

**Issue by jc-wood** [mozilla-mobile/fenix#9411]
### Why/User Benefit/User Problem

Horizontally-scrolling menus that don't use the full-height of the screen is a user-hostile design on mobile devices. It takes more effort to horizontally scroll than to vertically scroll when the menu doesn't use full screen height. It also increases the cognitive burden of selecting an application to share to because the UX paradigm is too dissimilar from the norm (see below). 

Share menus on the Android platform are typically vertically-scrolling "bottomsheets", even when applications are using a custom menu rather than the native share menu. Users expect a similar menu when sharing in Firefox.

### What/Requirements

Change the menu to be vertically scrolling rather than horizontally scrolling.

### Acceptance Criteria (how do I know when I’m done?)

Self-explanatory.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-16435)

**Comment by apbitner** [comment]
@topotropic for feedback

**Comment by topotropic** [comment]
Yes, that's a very good point, thanks for the feedback. We'll address this as part of this bigger piece of work around sharing https://github.com/mozilla-mobile/fenix/issues/14926

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1809790

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
