### ISSUE TITLE
Investigate cold startup regression Feb 29/Mar 1

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#9415]
@MarcLeclair Please fill in the details.

Looking at [my notes on startup](https://docs.google.com/document/d/1Yw2_egQ_q1l4XJ0EZD8rxa2gwIx4HeTXKPFmG0C6d6Q/edit#), we started to measure top sites around Feb 29 or Mar 1 so this may have been the cause of the regression.

**Comment by MarcLeclair** [comment]
So looking at our [HANOOB results](https://github.com/mozilla-mobile/fenix-nightly-perftest-results/blob/master/hanoob-results.csv),  it seems as if we had 1.3sec then went to 1.2 then back to 1.3, which means that even before hand, we had a long start up, then had a regression. It needs more looking into imo, thoughts @mcomella ?

**Comment by mcomella** [comment]
Currently, the numbers are:
```
2020.02.27, 1.3485799999999994
2020.02.28, 1.1334300000000004
2020.02.29, 1.1201300000000003
2020.03.01, 1.13328
2020.03.02, 1.3535999999999992
```

So it looks like the current trend is improvement on 02.28 and regression back to the status quo on 03.02. Since we didn't really regress anymore, I'm not sure this is still worth looking into.

**Comment by mcomella** [comment]
Closing: we generally haven't found startup regression investigations fruitful so the tickets are low priority. They're are a lot of them and they're hard to manipulate/track in GH so we're tracking on this spreadsheet instead: https://docs.google.com/spreadsheets/d/1hiKe-1KCs8mbyFu9Fik5SIIe5I-XjEilnaIqkfcnvYo/edit#gid=0
