### ISSUE TITLE
Shortcut to the start page of selected search engine

### ISSUE THREAD

**Issue by theFireProject** [mozilla-mobile/fenix#9419]
### Why/User Benefit/User Problem
The user receives a nice little feature without changing the surface of the UI making it more complicate. The look of the UI is not affected, neither its design or clarity.
It enables to easily access the start page of the most used websites, allowing to get further functionality and services of that website. For example:
- on 'google.com' you can tap the apps icon to change to any of Google's services, like Maps, Translator, Drive... or you can just manage your accounts.
- Another good use is disabling search suggestions in the address bar but still having a quick way to receive search suggestions if needed in particular cases.

### What/Requirements
<img src="https://user-images.githubusercontent.com/61639215/77600043-f048a100-6f06-11ea-85dd-0f7ab07ec58e.jpg" width="40">
The icon of the selected search engine in the address bar should become a button that leads to the start page of that search engine.

**Details**
The icon of the currently selected search engine is displayed on the left side of the address bar whenever it acts as a search bar. That's the case in different scenarios:
- on the tabs page:
![20200326_021248](https://user-images.githubusercontent.com/61639215/77600395-1ae72980-6f08-11ea-9c3c-8471f1b0fa97.jpg)
- typing in the address bar to open a new tab from the tabs page (either by touching the address bar or the 'New tab' / '+' button):
![20200326_021703](https://user-images.githubusercontent.com/61639215/77600368-03a83c00-6f08-11ea-9f99-ecf8ef8dcaf3.jpg)

In both cases above tapping the icon should open the start page in a new tab.
- editing the address bar from the current tab in order to change to a different website:
![20200326_021955](https://user-images.githubusercontent.com/61639215/77600457-4e29b880-6f08-11ea-94e1-1ac14c5f1abd.jpg)

In the case above tapping the icon should open the start page in the current tab.
- In every other case, you are viewing a website and at the exact same position of the search engine icon is the 'Shield' icon from the 'Enhanced Tracking protection' button:
![20200326_022201](https://user-images.githubusercontent.com/61639215/77600572-9ea11600-6f08-11ea-8a5b-a2fdc95bca09.jpg)
The search engine icon as a button should receive the same animation when touching it as the 'Enhanced Tracking Protection' button has. Appart from the animation, it shouldn't look any different as to right now.

To get the address of the start page of a search engine the same link can be used as when searching, simply leaving the search query string "%s" empty:
![20200326_022629](https://user-images.githubusercontent.com/61639215/77600809-3b63b380-6f09-11ea-9852-57b7e1a82d4b.jpg)

### Acceptance Criteria (how do I know when I’m done?)
If tapping the website icon of your currently selected search engine in the address bar (see image) opens its start page exactly the way it's describe above.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-16439)

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807739

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
