### ISSUE TITLE
As a User I want websites to be rendered in the same language I use for my device

### ISSUE THREAD

**Issue by st3fan** [mozilla-mobile/fenix#942]
### Why/User Benefit/User Problem

As a User I want websites to be rendered in the same language I use for my device.

This is all about GeckoView sending the correct Language headers. This may already happen automatically, in which case this can simply be a story for the sake of requirements.

### Acceptance Criteria (how do I know when I’m done?)

Sites that I visit will pick up the system locale setting. For example, say the user's device language is set to Spanish, visiting google.com should render the Google website in Spanish. This should happen even when Fenix does not support that language.

**Comment by cpeterso** [comment]
Someone should confirm what `Accept-Language` HTTP header is currently sent by Fennec and Fenix+GV for non-en devices. As @st3fan noted, this probably already works as expected.

Note that sending the correct `Accept-Language` HTTP header does not mean that localized websites will actually use your preferred language. Many popular websites (including Google I hear) purposely ignore `Accept-Language` and instead use GeoIP to guess which language to serve based on whichever country you are in at the moment.

**Comment by Riajyuu** [comment]
> Many popular websites (including Google I hear) purposely ignore Accept-Language and instead use GeoIP to guess which language to serve based on whichever country you are in at the moment.

![image](https://user-images.githubusercontent.com/16912240/54184881-a26f1f80-44e2-11e9-8784-b185c3ded06c.png)

You are right about this. Some sites even use JavaScript API for Timezone. But at least we can test some sites who respect this, e.g. DuckDuckGo

**Comment by jhugman** [comment]
Current status of a few browsers, setting French as a system language, and Request Bin.

Chrome Android
```
User-Agent: Mozilla/5.0 (Linux; Android 9; Pixel) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.90 Mobile Safari/537.36
Accept-Language: en-US,en;q=0.9,fr;q=0.8
```

Fenix, GeckoView
```
User-Agent: Mozilla/5.0 (Android 9; Mobile; rv:67.0) Gecko/67.0 Firefox/67.0
Accept-Language: en-US,en;q=0.5
```

Chrome, Desktop
```
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36
Accept-Language: en-US,en;q=0.9
```

Safari Desktop
```
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_3) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.0.3 Safari/605.1.15
Accept-Language: fr-fr
```

Firefox Desktop
```
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:66.0) Gecko/20100101 Firefox/66.0
Accept-Language: en-US,en;q=0.5
```

Language is exposed in the settings, via `intl.accept_languages` on desktop, and via `GeckoRuntimeSettings.locales` in GV.

Suggest: setting engine `locales` setting when `Locale` is changed via

```kt
context.registerReceiver(localeChangedReceiver, IntentFilter(Intent.ACTION_LOCALE_CHANGED))
```
