### ISSUE TITLE
[Bug] Error adding a working search engine

### ISSUE THREAD

**Issue by theFireProjet** [mozilla-mobile/fenix#9420]
## Steps to reproduce
Trying to add this website "https://m.dict.cc/" as a search engine:
- Add a new search engine
- Give it any name
- Insert address in the following format: "https://m.dict.cc/deen/?s=%s"
- Press 'Add' / '✅' button

### Expected behavior
As you can see the address is correct and Firefox is able to connect to that website:
![Screenshot_20200326-025953_Firefox Preview](https://user-images.githubusercontent.com/61639215/77603069-62bd7f00-6f0f-11ea-9069-8833fc01580a.jpg)
So I expect the search engine to be added successfully.

### Actual behavior
Error:
![20200326_030007](https://user-images.githubusercontent.com/61639215/77603018-44578380-6f0f-11ea-959f-34399f1dff08.jpg)
Interestingly, it's working for the desktop version of the same website:
![20200326_031624](https://user-images.githubusercontent.com/61639215/77603444-64d40d80-6f10-11ea-9142-b221528ede4d.jpg)

### Device information

* Android device: Samsung Galaxy S9+ (Android 8.0.0)
* Fenix version: 4.1.0

**Comment by LaurentiuApahideanSV** [comment]
I have reproduced the issue on Preview 4.2.1 and 4.3.0-beta.1. But the is fixed on Preview Nightly (Build #21070840) 4/16.
