### ISSUE TITLE
[Bug] Browser behaviour when tapping on a top sites icon multiple times

### ISSUE THREAD

**Issue by mcarare** [mozilla-mobile/fenix#9421]
## Steps to reproduce
Add a website to Top sites. Tap on the icon to open it. Go to home screen and tap multiple times
### Expected behavior

The browser should open to the existing opened tab, if any, like the behaviour requested for home screen shortcuts: https://github.com/mozilla-mobile/fenix/issues/5201#issuecomment-537320821
### Actual behavior
Multiple new tabs are opened.

**Comment by mcarare** [comment]
CC @brampitoyo Do UX agrees to implementing the same requested behaviour as for home screen shortcuts? TY!

**Comment by brampitoyo** [comment]
My reflex is to not do this behaviour.

Users who open Top Sites are likely to know that the site already exists under “Open Tabs” (which is listed just below Top Sites). They may want to reopen the same site again for any number of reasons.

On the other hand, users who open Android homescreen site shortcuts are less likely know whether that site is already opened or not. The list of “Open Tabs” is not shown unless they open Firefox first.

When users are more likely to be uncertain, we help them by opening existing tab if it exists.

When users are more likely to be certain, we give them the flexibility to reopen the same site in multiple new tabs if they really want to.

I think our current behaviour is okay. What do you think @mcarare?

**Comment by mcarare** [comment]
Closing this, as it is considered expected behaviour. Thank you @brampitoyo for your input!
