### ISSUE TITLE
[Bug] Widget-"Search the web" text is incorrectly displayed

### ISSUE THREAD

**Issue by Diana-Rus** [mozilla-mobile/fenix#9422]
Pre-requisites:
- Have Firefox widget present on the home screen.
- Have device option "Force RTL layout direction" enabled.

## Steps to reproduce
1. Inspect the android homescreen.
### Expected behavior
The microphone and "Search the web" text are correctly displayed.
### Actual behavior
The microphone and "Search the web" text are overlapping each other.
### Device information

* Android device: Google Pixel 3 XL (Android 9)
* Fenix version: 200326 (Build #20860605) GV: 76.0a1-20200324093140

**Screenshot:**
- Google Pixel 3XL (Android 9)
![Screenshot_20200326-111832](https://user-images.githubusercontent.com/49859863/77632260-69231980-6f56-11ea-8210-059bb0dd89ef.png)

- Samsung Galaxy S9 (Android 8)
![Screenshot_20200326-112851_Samsung Experience Home](https://user-images.githubusercontent.com/49859863/77632238-61fc0b80-6f56-11ea-989b-e89987250b15.jpg)

- Sony Xperia Z5 (Android 7)
![Screenshot_20200326-113021](https://user-images.githubusercontent.com/49859863/77632271-6c1e0a00-6f56-11ea-9316-0bc69efe0033.png)

Similar issue:
- https://github.com/mozilla-mobile/fenix/issues/6269
- https://github.com/mozilla-mobile/fenix/issues/5497

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly Build #20970607 from 4/6`** using the following devices:
• Google Pixel 3a (Android 10)
• Samsung Galaxy S6 (Android 7)
• OnePlus A3 (Android 6.0.1)

►Screenshot
![rsz_screenshot_20200406-094039](https://user-images.githubusercontent.com/51314259/78530055-a3f53f00-77eb-11ea-9b1e-4d0d5785f94f.png)
