### ISSUE TITLE
[Bug] ETP Custom-Text placed too closed to the edge of the device

### ISSUE THREAD

**Issue by Diana-Rus** [mozilla-mobile/fenix#9423]
Pre-requisites:
- Have Firefox widget present on the home screen.

## Steps to reproduce
1. Open app and go to Menu/Settings/Privacy and Security-Enhanced Tracking Protection.
2. Choose "Custom" option.
3. Inspect the following text:
 - Cookies
 - Tracking Content
 - Cryptominers
 - Fingerprinters
### Expected behavior
The sections text is correctly aligned with other elements from of the page.
### Actual behavior
The text is to close to the left edge of the device.
- Google Pixel 3 XL (Android 9)
![Screenshot_20200326-134735](https://user-images.githubusercontent.com/49859863/77645371-49e2b700-6f6b-11ea-934c-a68d486397b9.png)

- Samsung Galaxy S9 (Android 8)
![Screenshot_20200326-134959_Firefox Nightly](https://user-images.githubusercontent.com/49859863/77644872-721de600-6f6a-11ea-8b77-b7ab40d7a6ab.jpg)

- Sony Xperia Z5 (Android 7)
![Sony](https://user-images.githubusercontent.com/49859863/77645332-3cc5c800-6f6b-11ea-88bb-e001f85c331d.PNG)

### Device information

* Android device: Google Pixel 3 XL (Android 9), Samsung Galaxy S9 (Android 8) and Sony Xperia Z5 (ANdroid 7)
* Fenix version: Firefox Preview Nightly 200326 (Build #20860605) GV: 76.0a1-20200324093140

The issue is related to: https://github.com/mozilla-mobile/fenix/issues/5497

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly Build #20970607 from 4/6`** using the following devices:
• Google Pixel 3a (Android 10)
• Samsung Galaxy S6 (Android 7)
• OnePlus A3 (Android 6.0.1)

►Screenshot
![rsz_screenshot_20200406-095415](https://user-images.githubusercontent.com/51314259/78530834-0c90eb80-77ed-11ea-99ce-463562fa3441.png)
