### ISSUE TITLE
[Bug]Undoing a deleted search engine makes "Edit" option unavailable

### ISSUE THREAD

**Issue by sv-sdeiac** [mozilla-mobile/fenix#9425]
### Prerequisites
A new search engine needs to be added manually.

## Steps to reproduce
1. Go to the 3dot menu;
2. Select the "Search" option;
3. Tap on the 3dot menu from the added search engine;
4. Delete the search engine then "Undo";
5. Tap on the 3dot menu from the same search engine.

### Expected behavior
The "Edit" and "Delete" options are displayed.

### Actual behavior
The "Edit" option is missing.

### Device information
Android device:
- LG g7 fit (Android 8.1);
- Samsung Galaxy Tab S6 (Android 9).

* Fenix version: Firefox Preview Nightly 3/26 #20860605.
![20200326_145706](https://user-images.githubusercontent.com/40264165/77650537-515a8e00-6f74-11ea-8473-32a62a9d7a22.gif)

**Comment by softvision-miralobontiu** [comment]
This issue still reproduces on the latest Nightly build from 4/28 with HTC 10 (Android 8).

**Comment by Diana-Rus** [comment]
Reproducible with Google Pixel 3 XL (Android 9) on Nightly 5/6 (Build #21270609).

**Comment by ebalazs-sv** [comment]
This issue is still reproducible on Fenix Nightly from 5/12 with Motorola Moto G6 (Android 8).

**Comment by ebalazs-sv** [comment]
This is reproducible on Fenix Nightly 200518 GV 78 from 5/18 with Nexus 5 (Android 6.0.1).

**Comment by ebalazs-sv** [comment]
This issue is reproducible on the latest Nightly Build #21460606 from 5/25 with Nexus 5 (Android 6.0.1).

**Comment by sflorean** [comment]
Verified as fixed on Nightly 6/29 and Beta 78.0.1-beta1 with LG G7 FIT (Android 8).
