### ISSUE TITLE
Add the possibility to modify the avatar/change the display name of the FF account in Fenix

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/fenix#9427]
### Why/User Benefit/User Problem
As a Fenix user, I want to be able to modify my account profile picture.
### What/Requirements
Add an option to modify the account profile picture.
### Acceptance Criteria (how do I know when I’m done?)

![Screenshot_20200326-154829](https://user-images.githubusercontent.com/42831109/77655604-4bb47680-6f7b-11ea-9eba-d58a2f85b2ed.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-16447)

**Comment by grigoryk** [comment]
Not very obviously, but this is https://github.com/mozilla-mobile/fenix/issues/5915.

Current work-around is to use https://accounts.firefox.com/ to modify the account picture and the display name.

**Comment by grigoryk** [comment]
I'll leave this issue open as opposed to duping it, to make it easier to find for others looking for "avatar".

**Comment by jonalmeida** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1810633

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
