### ISSUE TITLE
Loading a session duplicates the session, making it so that I can never really close tabs

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/fenix#943]
## Steps to reproduce

1. Start Fenix with at least one saved session, ideally a session with a single saved tab.
2. Load session.
3. Close tab in loaded session

### Expected behavior

The session loaded in step 2 above should be gone. 

### Actual behavior

The session loaded in step 2 remains behind; I can load that session and open the tab, and close the tab.

I have to manually delete the session before the tab I read and closed is actually gone. 

### Device information

* Android device: Pixel 2
* Fenix version: 1.0.1911 (Build #10701327 :lizard: 67.0a1-20190305092747)

**Comment by bbinto** [comment]
@hmcgaw this is a good issue for UR to confirm expectations of this feature.

**Comment by cadeyrn** [comment]
related issue: #741 because it's also about unexpected session duplicating.

**Comment by lime124** [comment]
Hello! We are currently looking at the designs for this concept. Once that is complete we can revist this and see if it's still an issue. Moving to the icebox for now. Thanks!

**Comment by mheubusch** [comment]
We are removing existing sessions user stories and issues and will add new stories with new designs.
