### ISSUE TITLE
Checkboxes are hard to select

### ISSUE THREAD

**Issue by officiallor** [mozilla-mobile/fenix#9430]
I'm using Firefox on Android for a little time since Chrome was hanging for no reason. I faced a little issue when I was trying to check a checkbox. I have to point it exactly in the middle of the box, otherwise it's like i did nothing. I don't have the ability to calculate precisely where my finger is going so I can check a checkbox. In chrome I can press even on top of the label of the box and everywhere else nearby to select it. It's much easier. 
Device: Mi8/Android 10/Latest Firefox

**Comment by cadeyrn** [comment]
What does "Latest Firefox" mean? Firefox 68? Firefox Preview 4.1? On which site can the behaviour be reproduced?

**Comment by officiallor** [comment]
**Firefox 68.6.0**
**Example page:** https://www.w3schools.com/tags/tryit.asp?filename=tryhtml5_input_type_checkbox

**Where is the issue: **
You'll notice that you can't check and uncheck the boxes fast enough and many of your taps will not be counted.

**What should be expected**
Faster check-uncheck like in other browsers like Chrome etc

**Comment by cadeyrn** [comment]
This is the issues tracker for Firefox Preview (current version: 4.x), not for the old Firefox (version 68.x). Do you have the same issue with Firefox Preview?

**Comment by officiallor** [comment]
Just tested it. They have the same annoying issue. You can reproduce it by trying to check **fast** and uncheck the checkboxes from the link that I provided earlier. You'll notice that it's not so smooth. Sometimes when you try to check using the label, you end up selecting some text from the label.

**Comment by sflorean** [comment]
Closing as duplicate of #5693.
