### ISSUE TITLE
Hold for right click takes too long to work

### ISSUE THREAD

**Issue by officiallor** [mozilla-mobile/fenix#9431]
I've tried right click on my Android in Firefox and it takes way too long to open the menu. First I thought it was not working but then I realized that you have to keep your finger down  longer.

**Comment by Diana-Rus** [comment]
Hi, when you say that it takes too long to open the menu, do you mean after selecting a word or a link?
Could you please have a look at the following issue #10618 and say whether it describes the same circumstances?

**Comment by officiallor** [comment]
It does. Double clicking to select is easier than tap&hold on text but on links and some other text you can't use double click. Even on URL bar you have to struggle with selecting. I mean it's not only this the issue but the whole select thing is kinda slow. For example, in Chrome you tap and hold and you can move your finger to select words without using the left or right "selectors"

**Comment by ekager** [comment]
Closing for https://github.com/mozilla-mobile/fenix/issues/10618
