### ISSUE TITLE
[Bug]Add to Home Screen-The pop up does not display the entire information

### ISSUE THREAD

**Issue by Diana-Rus** [mozilla-mobile/fenix#9435]
Pre-requisites:
- Have device option "Force RTL layout direction" enabled.

## Steps to reproduce
1. Open app go to a website.
2. Tap on the Menu/Add to Home screen.
### Expected behavior
The pop up displays the entire "Add to Home screen" text.
### Actual behavior
The "Add to Home screen" text is truncated.
### Device information

* Android device: Google Pixel 3 XL (Android 9), Samsung Galaxy S9 (Android 8) and Sony Xperia Z5 (ANdroid 7)
* Fenix version: Firefox Preview Nightly 200326 (Build #20860605) GV: 76.0a1-20200324093140

Note:
- The issue can be reproduced in private browsing as well.

GIF
![Screenshot_20200326-192038](https://user-images.githubusercontent.com/49859863/77677153-faff4680-6f97-11ea-8b1d-f1261477443f.png)

**Comment by mcarare** [comment]
Note: Also, the favicon is missing!

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly Build #20940609 from 4/3`** using the following devices:
• Google Pixel 3a (Android 10)
• Samsung Galaxy S6 (Android 7)
• OnePlus A3 (Android 6.0.1)

► Video
![20200403-101958](https://user-images.githubusercontent.com/51314259/78334932-5b444880-7595-11ea-98b7-82d9ab254a30.gif)
