### ISSUE TITLE
Unable to log into Zoom using SSO

### ISSUE THREAD

**Issue by kbrosnan** [mozilla-mobile/fenix#9438]
## Site with issue and any steps to reproduce
https://mozilla.zoom.com

### Expected behavior
Able to log in to Zoom App

### Actual behavior
Zoom not launched when tapping on the Zoom link
```
open the uri:zoomus://mozilla.zoom.us/sso?token=$TOKEN launch_sso.min.js:1:32

Content Security Policy: This site (https://mozilla.zoom.us) has a Report-Only policy without a report URI. CSP will not block and cannot report violations of this policy.
```

### Does toggling Tracking Protection fix the issue? (Press the lock icon in the toolbar while on the site to see toggle)
No

### Can you reproduce in [Firefox for Android](https://play.google.com/store/apps/details?id=org.mozilla.firefox)?
No.

### Device information

* Android device: Pixel 3 w/ Android 10
* Fenix version: 4.2.0-beta.3

**Comment by mcomella** [comment]
https://github.com/mozilla-mobile/fenix/issues/2970 was a previous issue on this and it was duped to https://github.com/mozilla-mobile/fenix/issues/3177.

**Comment by abodea** [comment]
Hello, @kbrosnan note that I investigated this issue for more details please check the following:
Following the steps from the description, I accessed `https://mozilla.zoom.us` and then I tapped on the `Sign in` I was able to successfully login but I was never redirected to the Zoom app. (**note that the same behavior is for Chrome, no redirection to the Zoom app**).
When I accessed `Download Client` from the `https://mozilla.zoom.us` I was redirected correctly to the Google Play Zoom Client.
Note that the same behavior is on [Firefox for Android](https://play.google.com/store/apps/details?id=org.mozilla.firefox) as the zoom app is not opened.
I saw this link with https://github.com/mozilla-mobile/fenix/issues/3177 as I wanna confirm it.
![good](https://user-images.githubusercontent.com/42831109/77912444-4026bf80-729b-11ea-995f-00d304a35fd1.jpg)

Note that this behavior is present on Fenix, Fennec, and Chrome.
![20200330-153256](https://user-images.githubusercontent.com/42831109/77913014-3f425d80-729c-11ea-9436-58d33a63a4e5.gif)
Are there other methods to test this bug? From what I saw this maybe is related to zoom implementation as there is no support for deep linking when tapping on the `Sign In` button. I remember we had an issue like this for lockwise in the Bento menu. (https://github.com/mozilla-lockwise/lockwise-android/issues/955 and https://github.com/mozilla/blurts-server/issues/1229)

**Comment by liuche** [comment]
@rocketsroger I took a look at #3177 but wasn't sure if that fix is in-progress, or the status of it?

**Comment by rocketsroger** [comment]
No fix in-progress for this one yet.  I'll investigate.

**Comment by rocketsroger** [comment]
This is related to https://bugzilla.mozilla.org/show_bug.cgi?id=1596825.  Will retest after the bug is fixed.

**Comment by rocketsroger** [comment]
New GV API requires A-C changes https://github.com/mozilla-mobile/android-components/issues/7047

**Comment by rocketsroger** [comment]
Nightly with A-C version 43.0.20200526130035 will have the fix. Please verify this is fixed. Thanks,

**Comment by abodea** [comment]
Verified as fixed on the latest Nightly 5/29 with Samsung Galaxy S10+ (10).
Note that I was able to log in without problems, and I was able to open the zoom app when I tapped on the new meeting.
