### ISSUE TITLE
Delete browsing data on exit without needing pressing the quit button

### ISSUE THREAD

**Issue by TheSorrow1** [mozilla-mobile/fenix#9446]
### Why/User Benefit/User Problem
This would make it alot easier for the user, as most are just used to closing the application without pressing the quit button.

### What/Requirements
Change how Firefox deletes the data on exit.

### Acceptance Criteria (how do I know when I’m done?)
When the user simply can close firefox from the applications meny on their phone (exit) all the data gets deleted presuming the user has chosen to do so.

**Comment by ClemGame** [comment]
Would be great! 👍

**Comment by Phenix-Feedback** [comment]
I agree with that request.
For me this is a major regression, I want to close my App with Android without clicking on "Quit" (more click and counter-intuitive).

**Comment by yoasif** [comment]
See also issue 11449

**Comment by ekager** [comment]
Closing for #11449
