### ISSUE TITLE
Option to use private mode permamently

### ISSUE THREAD

**Issue by TheSorrow1** [mozilla-mobile/fenix#9447]
### Why/User Benefit/User Problem
For privacy users who don't want any data to be saved, will improve privacy. Like your desktop version or mobile firefox focus
### What/Requirements
Add a option for this in the privacy settings.

**Comment by liuche** [comment]
The current workflow here is to add the Private Browsing shortcut, and use that instead. That should always open a private browsing tab. Please comment if that isn't fulfilling the use case!
