### ISSUE TITLE
Keep keyboard open while scrolling search engines

### ISSUE THREAD

**Issue by theFireProject** [mozilla-mobile/fenix#9448]
### Why/User Benefit/User Problem
Keeping the keyboard open is a more efficient and intuitive behaviour for the user. It saves one unnecessary step (reopening the keyboard) and looks better.
- Touching a search engine doesn't close the keyboard, only changing search engines by scrolling and then tapping the desired one does.
- This behaviour can be disturbing disturbing and doesn't look smooth. The fact that the keyboard closes in the middle of scrolling can cause the view to jump, in case it is possible to scroll search engines with the keyboard open but they will fit on the screen after it is closed. It will no more be possible to scroll and elements will be placed at their default positions.

### What/Requirements
Keep the keyboard open while scrolling search engines and don't lose focus of the address bar.

### Acceptance Criteria (how do I know when I’m done?)
If it is possible to pick a search engine and be ready to type only by touching the screen two times:
- scroll down
- tap desired search engine
- now type on your keyboard

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-16458)

**Comment by apbitner** [comment]
Agreed, I don't see the need to close the keyboard in this situation.

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807738

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
