### ISSUE TITLE
[Bug] Folder is displayed incorrectly when editing bookmarks/folders in the root folder

### ISSUE THREAD

**Issue by theFireProjet** [mozilla-mobile/fenix#9449]
## Steps to reproduce
- go to 'Your Library' > ' Bookmarks' (not a step deeper into a folder, only stay in the 'Bookmarks' root folder)
- **edit** a **bookmark or folder** that's saved here
- tap the folder in order to go to the folders view
- go back without changing the folder

### Expected behavior
Containing folder is displayed as "Bookmarks":
![20200327_035409](https://user-images.githubusercontent.com/61639215/77716890-6e787680-6fdf-11ea-8f5c-84a2b2963197.jpg)
![20200327_035422](https://user-images.githubusercontent.com/61639215/77716675-045fd180-6fdf-11ea-8312-374b270a6e1b.jpg)

### Actual behavior
- go to 'Your Library' > ' Bookmarks' (not a step deeper into a folder, only stay in the bookmarks root folder)
- edit a bookmark or folder that's saved here:
**Containing folder is displayed as "mobile"** for editing bookmarks as well as folders
![20200327_040325](https://user-images.githubusercontent.com/61639215/77717115-efd00900-6fdf-11ea-94b2-13adb7af0549.jpg)
- tap the folder in order to go to the folders view
- go back without changing the folder
**Containing folder now is displayed as "Bookmarks"**
![20200327_035409](https://user-images.githubusercontent.com/61639215/77717159-024a4280-6fe0-11ea-878b-4590edb87fe9.jpg)

### Device information

* Android device: Samsung Galaxy S9+ (Android 8.0.0)
* Fenix version: 4.1.0

**Comment by Diana-Rus** [comment]
Hi, i also reproduce this issue on Firefox Preview Nightly 200327 (Build #20870607) GV: 76.0a1-20200325093457 with Google Pixel 3 XL (Android 9) and Sony Xperia Z5 (Andorid 7)

**Comment by Diana-Rus** [comment]
Hi, reproduced this issue with Sony Xperia Z5 (Android 7) Beta 76.0.0-beta.1 5/1.

**Comment by grigoryk** [comment]
I think that's the same as https://github.com/mozilla-mobile/fenix/issues/11502? If so, this is fixed by https://github.com/mozilla-mobile/fenix/pull/15207.

Feel free to re-open if you think these are two distinct issues.
