### ISSUE TITLE
Fix inconsistent design (left alignment) in Settings

### ISSUE THREAD

**Issue by theFireProjet** [mozilla-mobile/fenix#9450]
### Why/User Benefit/User Problem
A consistent design language looks clearer and is more convenient for the user.

### What/Requirements
Remove the indentation on some settings pages to make the design equal on all pages. The indentation is only good for icons, but there are none. It looks off and decentred.
These sides need to be fixed:
- Logins and passwords
- Private browsing
- Delete browsing data on quit

### Acceptance Criteria (how do I know when I’m done?)
If the inversion on the settings pages mentioned above is removed and they look the same as all the other pages.

**Comment by s-ankur** [comment]
This is solved now. Can be closed

**Comment by cadeyrn** [comment]
Solved is maybe not the correct word because it was "solved" by doing the exact opposite. And "inconsistent design (left alignment) in Settings" is still true. Compare the main settings page with the sub pages.

**Comment by ekager** [comment]
Since the original issue is stale, please open a new issue with exactly what the remaining issues are.
