### ISSUE TITLE
[Bug] Dynamic nav bar animations prevent website scrolling

### ISSUE THREAD

**Issue by Mugurell** [mozilla-mobile/fenix#9451]
## Steps to reproduce
- use Firefox Nightly to have dynamic nav bar enabled
- access google.com/maps
- with a continuous touch on the screen swipe down and up

### Expected behavior 
- Both the nav bar and the website content should be scrolled at the same time, this indeed happening with most websites. (See video)

### Actual behavior
- On google.com/maps (and possibly other websites) once the dynamic nav bar starts to animate it prevents any scrolling inside the webpage. (See video)

### Video showcasing the issue
https://drive.google.com/file/d/1f7oq0WVBv6GoNMvG_JKBNtoYLIznL8iZ/view

**Comment by AndiAJ** [comment]
**Not reproducible** anymore on the latest on the latest **`Nightly Build 201111`** using the following devices:
• Google Pixel 3a (Android 11)
• Huawei Mate 20 Lite (Android 10)
• OnePlus A3 (Android 6.0.1)
