### ISSUE TITLE
[Bug]Flicker displayed when deleting the URL 

### ISSUE THREAD

**Issue by sv-sdeiac** [mozilla-mobile/fenix#9453]
## Steps to reproduce
1. Open Firefox Preview;
2. Go to any page;
3. Tap the URL bar;
4. Tap on the "x" button from the URL bar.

### Expected behavior
The URL is deleted and no visual defects are presented.

### Actual behavior
A flicker is displayed when deleting the URL

### Device information
Android device: 
- Google Pixel 3 (Android 10);
- Samsung Galaxy Note 8 (Android 9);
- LG g7 fit (Android 8.1).

* Fenix version: Firefox Preview Nightly 3/27 #20870607.
![20200327_101645](https://user-images.githubusercontent.com/40264165/77738606-d0a19d80-7018-11ea-9d32-6be97160b72c.gif)

**Comment by Diana-Rus** [comment]
Issue reproduces with Samsung galaxy S9 (Android 8) with Fenix Nightly 5/22.
Note: It can constantly be reproduced when option "Show clipboard suggestions" is disabled.

**Comment by Diana-Rus** [comment]
Reproducing on Nightly 6/19 and Beta 5.2.0-beta.2 with Sony Xperia Z5 (Android7).
