### ISSUE TITLE
Set default bookmark location

### ISSUE THREAD

**Issue by anotherus3r** [mozilla-mobile/fenix#9454]
### Why/User Benefit/User Problem
I use the desktop Firefox's bookmarks toolbar as the main folder for my bookmarks. This is fine for desktop Firefox, as it gives me quick access to my bookmarks, but creates unneeded steps (like navigating through a longer folder structure) in mobile Firefox, i.e. Fenix. Allowing users to set a default bookmarks folder when tapping the "Bookmarks" option in the Library would grant them quicker access to their bookmarks, in case they don't use the default folder in Fenix.

### What/Requirements
Add an option in the app settings or in the folder context menu to set it as the default location for bookmarks.

### Acceptance Criteria (how do I know when I’m done?)
When users are able to set a default bookmark location in Fenix.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-16464)

**Comment by vtronko** [comment]
Very well put, this feature is vital to me too, as I tend to use my desktop bookmarks folder as a main aggregator of bookmarks between multiple devices.
There's a desktop addon for that, but unluckily it doesn't support android platform.

**Comment by frozenxuan** [comment]
This feature is the only blocker for me to switch from chrome to firefox. I frequently access a subfolder under bookmarks toolbar on desktop, compare to chrome mobile which always open the last accessed folder(menu icon>bookmarks), firefox mobile requires much more unnecessarily redundant steps to open the folder (menu icon>library>bookmarks>bookmarks on desktop>bookmarks toolbar>folder), firefox current logic(for years) at treating bookmarks is so user-unfriendly IMO and has to improve.

**Comment by JNavas2** [comment]
It's a big deal to me too, but I think it would be better to have Fenix use the same behavior as Android Chrome, which opens the _last_ folder accessed when Bookmarks are opened.

**Comment by binocry** [comment]
please mozilla add this feature this is so important to me because i use bookmark heavily

**Comment by Koyomivamp01** [comment]
Still waiting..... 😅

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812715

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
