### ISSUE TITLE
[Bug]Context menu is displayed on the homepage

### ISSUE THREAD

**Issue by sv-sdeiac** [mozilla-mobile/fenix#9456]
## Steps to reproduce
1. Go to any page(e.g. Wikipedia.com);
2. Long tap to select a text;
3. Tap on the tab drawer icon.

### Expected behavior
The homepage of the app is displayed.

### Actual behavior
The context menu is displayed for a second on the homepage.

### Device information
Android device: 
- Samsung Galaxy Note 8 (Android 9);
- Google Pixel 3 (Android 10).

Fenix version: Firefox Preview Nightly 3/27 #20870607.
![20200327_152547](https://user-images.githubusercontent.com/40264165/77761171-4a994d00-7040-11ea-9fd4-238efa73d0ae.gif)

**Comment by AndiAJ** [comment]
Not reproducible anymore on the latest Nightly Build 201103 using the following devices:
• Google Pixel 3a (Android 11)
• Huawei Mate 20 Lite (Android 10)
• OnePlus A3 (Android 6.0.1)
