### ISSUE TITLE
[Bug] Firefox Preview/Nightly Search should appear immediately after "Copy" and "Select All"

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/fenix#9467]
## Steps to reproduce

1. Install Fenix
2. Install some apps that add context menu items, like Google Shopping, Lynket, Opera, Wikipedia
3. Open any web page
4. Select text

### Expected behavior

Context menu appears with options like "Copy", "Select All", "Firefox Preview Search"

### Actual behavior

Context menu appears with "Copy", "Select All", "Open/Search with Lynket". "Firefox Preview Search" appears inside of a meatball menu. 

![signal-attachment-2020-03-27-170519](https://user-images.githubusercontent.com/152493/77800445-34de5480-704d-11ea-89e8-e295277d47c1.png)

### Device information

* Android device: Pixel 2
* Fenix version: latest nightly

**Comment by Diana-Rus** [comment]
Hi, thank you for creating the issue, here is the bug in which this is going to be treated # 10466 - please check comment: https://github.com/mozilla-mobile/fenix/issues/10466#issuecomment-626445627 for the proposed solution.
You can follow the flow of the implementation and when it will be ready for use.
I am going to close this ticket, thanks.
