### ISSUE TITLE
[Bug] Call forceExpand when navigating in a session

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#9472]
This is a security risk as we do not currently forceExpand the bottom dynamic toolbar when navigating to a new page. 

Once we do this, we can probably un-feature flag this!

Waiting on my AC PR: https://github.com/mozilla-mobile/android-components/pull/6431

## Acceptance Criteria
* When I click on a link on a page, the toolbar is shown while the new page loads
* When I press back, the toolbar is shown
* When I press forward, the toolbar is shown

(please test with toolbar set to **bottom** and with it hidden by scrolling down the page a bit)

**Comment by abodea** [comment]
Verified as fixed on **Nightly 1/4** with **Google Pixel 4 XL (10).**
- When I click on a link on a page, the toolbar is shown while the new page loads
- When I press back, the toolbar is shown
- When I press forward, the toolbar is shown
- When I press refresh, the toolbar is shown

Everything works as expected and the toolbar is always shown.
