### ISSUE TITLE
[Bug] Google keyboard fails to auto-capitalize on inputs in Firefox Preview

### ISSUE THREAD

**Issue by kadmil** [mozilla-mobile/fenix#9475]
## Steps to reproduce
Focus on any input field while using both Firefox Preview & Google keyboard. First letter isn't capitalized, and there's no auto-capitalization after a dot.

### Expected behavior
Keyboard works just as in other apps.

### Actual behavior
All the letters are in lower case by default, even after Dot and in the beginning of the input

### Device information

* Android device: Pixel 2xl, Android 10, March security update
* Fenix version: 4.1.0 (Build #20771637)
36.0.2, 6638a3365
GV: 75.0-20200309155231
AS: 0.53.3
Google keyboard: 9.1.8.300404574-release-arm64-v8a

**Comment by makotokato** [comment]
dup of https://github.com/mozilla-mobile/fenix/issues/9283?

**Comment by kadmil** [comment]
yup, looks like it is. sorry for filing another one

**Comment by makotokato** [comment]
> yup, looks like it is. sorry for filing another one

Don't worry, Thank you for reporting!

**Comment by Diana-Rus** [comment]
Hi, I will close this as it's going to be monitored through the other issue #9283 .
