### ISSUE TITLE
[Bug] Clicking an Image in Google Search Engine Result Page results in Primitive UI

### ISSUE THREAD

**Issue by Rupali2412** [mozilla-mobile/fenix#9476]
## Steps to reproduce
Click on any image in  Google Search Engine Result Page (All page). It results in primitive design.

### Expected behavior
Google UI should not change and work like any other browser.
### Actual behavior
Google UI changes to the following picture. It is normal in google images.
![google all](https://user-images.githubusercontent.com/60149380/77822985-a08ff280-711d-11ea-9925-5f8dbc72ffae.jpeg)
### Device information

* Android device: Nokia 6 | Android version - 9
* Fenix version: Firefox Preview Nightly for developers

**Comment by Diana-Rus** [comment]
Hi, I can reproduce this issue with Google Pixel 3 XL (Android 9) and Sony Xperia Z5 (Android 7) on Nightly 5/12.
Note:
The format of the page should be the same as when navigating after the search to Images and then tapping on the image.
