### ISSUE TITLE
[Bug]The latest version cannot call the input method

### ISSUE THREAD

**Issue by 90du** [mozilla-mobile/fenix#9478]
## Steps to reproduce
The latest version cannot call the input method
### Expected behavior
Touch the search box to automatically call the input method
### Device information
Cannot enter text
* Android device: ?
* Fenix version: ?
Nightly 200328 06:01 (Build #20870608)

**Comment by shawnz** [comment]
I also can't see the keyboard after clicking the search box in the latest version. As a workaround, if I go to a different app, show the keyboard there, and then switch back to Firefox Preview using recent apps, then the keyboard still appears and I can type.

Also, if I click the "scan QR code", then click back, it temporarily fixes the issue.

The issue began with the second-last Play store update (not sure what version that was) and it continues with the latest Play store update. (Nightly 200328 18:00 Build #20881805)

**Comment by ekager** [comment]
Closing for #9500
