### ISSUE TITLE
Close tabs - open them by accident

### ISSUE THREAD

**Issue by swejuggalo** [mozilla-mobile/fenix#9480]
### Why/User Benefit/User Problem
The area of closing tabs may benefit from a wider area of the tab.
### Acceptance Criteria (how do I know when I’m done?)

Added screenshot of suggested area of touch. More centered and wider. Harder to miss the X. At the moment it can be easy to touch below the X and instead open the tab.
![Screenshot_20200328-162315__01](https://user-images.githubusercontent.com/25906311/77826960-2c505180-7113-11ea-983e-b7274281e899.jpg)

**Comment by swejuggalo** [comment]
It might even be beneficial to simply move the X to the middle right instead of the upper right. That alone probably decreases the risk of opening tab

**Comment by ekager** [comment]
Closing because tabs UI has changed significantly. Please open a new issue if you're still having a problem with tabs.
