### ISSUE TITLE
[Bug] When navigation bar is displayed at the top of the app, website bottom navigation menus are not adjusted to the bottom of the screen

### ISSUE THREAD

**Issue by joaoltf** [mozilla-mobile/fenix#9481]
## Steps to reproduce
By default, the Firefox Preview navigation bar displays at the bottom of the app. However, you can move it to the top of the app if desired
1. In Settings, move the Firefox Preview navigation bar to the top of the app.
2. When visiting a site with bottom navigation menus (Linkedin.com, for example), scroll down in the page.

### Expected behavior
When Firefox Preview navigation bar is on the top of the app, website bottom navigation menus are adjusted to the bottom  of screen.

### Actual behavior
If you scrooll down in that page, those menus are not adjusted to the limit of the screen.
They remain in the expected position, as if Firefox Preview navigation bar is set to bottom of the app, leaving a gap between the navigation menus and the limit of the screen.

![IMG_20200328_180019](https://user-images.githubusercontent.com/62778071/77830106-1eec9480-711e-11ea-8db1-ac0d27c8fd75.jpg)

### Device information

* Android device: Mi 9T Pro, running Android 10 QKQ1.190825.002
* Fenix version: 4.1.0 (Build #20771637)

**Comment by joaoltf** [comment]
Maybe it's related to #8768

**Comment by liuche** [comment]
Thanks for pointing to that issue @joaoltf! This is the same issue, so to keep issues concise going to dupe and close this one to #8768.
