### ISSUE TITLE
[Bug] Dynamic bottom Toolbar does not hide or show on scroll

### ISSUE THREAD

**Issue by bubi-luka** [mozilla-mobile/fenix#9482]
## Steps to reproduce
Visit a Website. Scroll down the page. Observe the status of the bottom toolbar.

### Expected behavior
On scroll down the page the toolbar should hide.
On scroll up the page should the toolbar show itself.

### Actual behavior
The toolbar does not hide every time. Nor does it show on scrolling up.
![dynamic-bottom-toolbox-scrolling](https://user-images.githubusercontent.com/1206048/77830603-e2269a80-7129-11ea-93a2-9104e43953cf.gif)
)

### Device information

- Android device: Huawei p20 lite, Android 9, EMUI 9.1
- Fenix version: Nightly 200328 6:01 (Build #20880607)

**Comment by liuche** [comment]
This looks like #9517, which will have a fix in AC soon, so I'm going to dupe and close this issue.
