### ISSUE TITLE
[Bug] Nightly Build 200327 crashing when opening webpage with ublock enabled

### ISSUE THREAD

**Issue by VandaLHJ** [mozilla-mobile/fenix#9483]
## Steps to reproduce
Build Nightly 200327
enable ublock origin (it's disabled on site in question)
open southfront.org (also on other sites, but on this one it crash all the time)
### Expected behavior
webpage opens

### Actual behavior
crash

### Device information
Xiaomi Redmi Note 3 (global) MIUI 10.2.1.0 Global

* Android device: 6.0.1 MMB29M
* Fenix version: 200327

**Comment by VandaLHJ** [comment]
On 200329 too

**Comment by VandaLHJ** [comment]
on 200330 also. Moreover, when i click on address bar, keyboard don't appear.

Concerning the crash, it's not instanteous, it fill 1/4 progress bar, then it crash to desktop (with system dialog if i want to report the issue and/or restart firefox)

**Comment by VandaLHJ** [comment]
2a54537e-f506-cfd1-5acc-eb60ab1daf41 02.04.2020, 12:02 778751ff-d1a5-4f74-6b93-b35fb48ffb20 02.04.2020, 07:46 6c94d1ae-f888-3133-15b6-e718ea29dd30 02.04.2020, 07:46 0e4ba57b-c4fb-6d30-7a13-ad7cb236ad66 01.04.2020, 08:27 6b9b31a6-2081-37a0-9e50-54747b2e8461 31.03.2020, 23:28 21e23c8d-d4c7-9373-23ba-a65f27a32f16 31.03.2020, 16:21 1e784024-c647-d3e0-31a9-7b46fb1e9c54 30.03.2020, 17:57 798462b8-8973-2c69-e5cf-ee5edf227351 30.03.2020, 14:51 43598983-55f8-538d-2a0f-ec680b7ecd62 30.03.2020, 14:50 44de69d4-25b9-ecc9-5e01-7226be789b49 30.03.2020, 14:44 263555da-e394-6db2-d3d5-09448e8d8c1f

**Comment by VandaLHJ** [comment]
Name | Firefox Nightly
-- | --
76.0a1
20200330094747
nightly
Mozilla/5.0 (Android 6.0.1; Mobile; rv:76.0) Gecko/76.0 Firefox/76.0
Linux 23
0/0               Enabled by default
1
Found
Found
Found
false

**Comment by kbrosnan** [comment]
Please provide a logcat of the crash. See https://github.com/mozilla-mobile/fenix/wiki/Logging-Crash-Information 

If you have any questions ask here or on https://chat.mozilla.org/#/room/#fenix:mozilla.org

**Comment by VandaLHJ** [comment]
https://gist.github.com/VandaLHJ/3a6d16b34dbb825cb206e471e9f61caa

**Comment by kbrosnan** [comment]
Group triage as I'm not sure how to classify that crash.

**Comment by boek** [comment]
The crash that you're seeing. Are you getting the "Application is not responding" dialog or the "Application has crashed dialog"?

**Comment by VandaLHJ** [comment]
Firefox Nightly uległ awarii.. 
Checkbox Zgłoś awarię organizacji Mozilla
And on the bottom is quit or start again.

All in pl PL locale, i guess it's application has crashed rather than application is not responding.

**Comment by mcarare** [comment]
@VandaLHJ Are you still able to reproduce this?

**Comment by Amejia481** [comment]
QA can help us to verify

**Comment by AndiAJ** [comment]
Hi, didn't manage to reproduce the issue on the latest Nightly 200430 from 4/30 using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)

► Video adding southfront.org to the uBlock's whitelist
![20200430-173101](https://user-images.githubusercontent.com/51314259/80725493-d4d74400-8b0b-11ea-91ff-308b009a53ce.gif)


► Video uBlock disabled manually for the southfront.org  
![20200430-172824](https://user-images.githubusercontent.com/51314259/80723309-23cfaa00-8b09-11ea-8e3e-0ca513036b93.gif)

❗ However, I've bumped today in a native code crash while using OnePlus A3 (Android 6.0.1), logged #10318 
And 3 days ago when I've tried to install some Add-ons  #10238 

Checked @VandaLHJ 's crash log's and seems that he also encountered the same crashes?

► @VandaLHJ 's crashes:
1st log
```kotlin
04-02 21:18:08.700 E/mozac/CrashReporter( 9953): CrashHandlerService received native code crash
04-02 21:18:08.701 I/mozac/CrashReporter( 9953): Received crash: NativeCodeCrash(minidumpPath=/data/user/0/org.mozilla.fennec_aurora/files/mozilla/yrknhref.default/minidumps/1df4f9ef-0dfa-17c7-a338-5727c41cbc75.dmp, minidumpSuccess=false, extrasPath=/data/user/0/org.mozilla.fennec_aurora/files/mozilla/yrknhref.default/minidumps/1df4f9ef-0dfa-17c7-a338-5727c41cbc75.extra, isFatal=true, breadcrumbs=[])
```


2nd log
```kotlin
04-02 21:27:15.109 E/mozac/CrashReporter(11850): CrashHandlerService received native code crash
04-02 21:27:15.110 I/mozac/CrashReporter(11850): Received crash: NativeCodeCrash(minidumpPath=/data/user/0/org.mozilla.fennec_aurora/files/mozilla/yrknhref.default/minidumps/30456906-b820-e88f-4373-320940883446.dmp, minidumpSuccess=false, extrasPath=/data/user/0/org.mozilla.fennec_aurora/files/mozilla/yrknhref.default/minidumps/30456906-b820-e88f-4373-320940883446.extra, isFatal=true, breadcrumbs=[])
```

► Crashes encountered by me:

Native code crash encountered today #10318 
```kotlin
04-30 13:43:34.837 2085-2101/? E/mozac/CrashReporter: CrashHandlerService received native code crash
04-30 13:43:34.838 2085-2101/? I/mozac/CrashReporter: Received crash: NativeCodeCrash(minidumpPath=/data/user/0/org.mozilla.fenix.nightly/files/mozilla/Crash Reports/pending/2ebc5aa3-0ee0-82a4-0ea9-a54a5d469a51.dmp, minidumpSuccess=false, extrasPath=/data/user/0/org.mozilla.fenix.nightly/files/mozilla/Crash Reports/pending/2ebc5aa3-0ee0-82a4-0ea9-a54a5d469a51.extra, isFatal=false, breadcrumbs=[], uuid=be0c9b02-d829-47ef-9cf9-6712ceed779f)
```

Native code crash encountered in #10238 
``` kotlin
04-27 16:26:47.715 15415-15428/? E/mozac/CrashReporter: CrashHandlerService received native code crash
04-27 16:26:47.715 15415-15428/? I/mozac/CrashReporter: Received crash: NativeCodeCrash(minidumpPath=/data/user/0/org.mozilla.fenix.nightly/files/mozilla/Crash Reports/pending/0c5f4ce3-bb01-fcb3-b225-861535c89d44.dmp, minidumpSuccess=false, extrasPath=/data/user/0/org.mozilla.fenix.nightly/files/mozilla/Crash Reports/pending/0c5f4ce3-bb01-fcb3-b225-861535c89d44.extra, isFatal=false, breadcrumbs=[])
```

@Amejia481 - Please review and share your thoughts. ☺️ 
I'll remove the QA needed label until further notice.

**Comment by Amejia481** [comment]
I think we can close this one, as it's not reproduce anymore, the native crash could be unrelated.
@VandaLHJ if you continue seen this issue please reopen!

**Comment by VandaLHJ** [comment]
https://gist.github.com/VandaLHJ/64ccd46a49a87c1a58d5304a44dfcf63

It's still happening reliably

**Comment by Amejia481** [comment]
Can you go to **Settings**-> **About Firefox Nightly** and share a print screen?

**Comment by VandaLHJ** [comment]
[Screenrecorder-2020-04-30-17-52-54-519.tar.gz](https://github.com/mozilla-mobile/fenix/files/4559462/Screenrecorder-2020-04-30-17-52-54-519.tar.gz)

Here is screencast in zip.
![Screenshot_2020-04-30-17-56-30-245_org mozilla fenix nightly](https://user-images.githubusercontent.com/28790923/80732163-3697ae00-8b0c-11ea-80f1-3f3d6adda5bf.png)

**Comment by Amejia481** [comment]
Thanks, let's re open and take a look.

**Comment by VandaLHJ** [comment]
On 200430 same issue.

**Comment by liuche** [comment]
Added this to the AC top 10, if you have time to look at it @Amejia481 please assign yourself! :)

**Comment by gh5645** [comment]
Got the same issue and managed to submit a crash dump.
First of all: From the look of the reports here it seems that Android versions 6 and 7 are affected, so to reproduce do not use Android 9, 10 (unsure about Android 8). From all the websites listed in this report and other bug reports, visiting southfront.org seems to cause the crash most reliably.

https://crash-stats.mozilla.org/report/index/826399d7-0f98-41e5-9ee5-bbec10200514

I can further confirm that the same stack trace is generated for #10318, #10385, #10517, so they all seem to be the same bug.

Digging a little bit deeper, on 2020-01-28 was the last time a change to ipc_channel_posix.cc was pushed, which is also around the time I first noticed the crashes.

The log does not say anything except it is a native code crash:
```
05-14 12:39:04.242 E/NotificationService( 1136): Suppressing notification from package by user request.
05-14 12:39:04.244 E/NotificationService( 1136): Suppressing notification from package by user request.
05-14 12:39:04.782 D/wpa_supplicant(12696): wlan0: Control interface command 'SIGNAL_POLL'
05-14 12:39:04.783 D/VideoCall_LowBattery( 4794): BatteryIntent received: android.intent.action.BATTERY_CHANGED
05-14 12:39:04.783 W/QCNEJ   ( 5806): |CORE| CNE received unexpected action: android.intent.action.BATTERY_CHANGED
05-14 12:39:04.791 E/NotificationService( 1136): Suppressing notification from package by user request.
05-14 12:39:04.792 D/wpa_supplicant(12696): CTRL-DEBUG: global_ctrl_sock-sendto: sock=9 sndbuf=212992 outq=0 send_len=49
05-14 12:39:04.805 I/IzatProviderEngine( 1136): LocTech-Label :: OSDC :: Position Report In
05-14 12:39:04.806 I/IzatProviderEngine( 1136): LocTech-Value :: UTC Time: 1589452740200, Elapsed Real Time Nanos: 857066215944662, Latitude: 51.59000015258789, Longitude: 10.390000343322752, Altitude: 0.0, Speed: 0.0, Bearing: 81.0, Accuracy: 256705.44
05-14 12:39:04.811 D/VideoCall_LowBattery( 4794):  allowVideoCallsInLowBattery: true isCarrierOneSupported: false mIsLowbattery: false
05-14 12:39:05.049 D/AndroidRuntime( 2825): >>>>>> START com.android.internal.os.RuntimeInit uid 10223 <<<<<<
05-14 12:39:05.054 D/AndroidRuntime( 2825): CheckJNI is OFF
05-14 12:39:05.055 E/cutils-trace( 2825): Error opening trace file: No such file or directory (2)
05-14 12:39:05.115 D/ICU     ( 2825): No timezone override file found: /data/misc/zoneinfo/current/icu/icu_tzdata.dat
05-14 12:39:05.190 I/Radio-JNI( 2825): register_android_hardware_Radio DONE
05-14 12:39:05.218 D/AndroidRuntime( 2825): Calling main entry com.android.commands.am.Am
05-14 12:39:05.237 I/ActivityManager( 1136): Start proc 2835:org.mozilla.fennec_aurora:mozilla.components.lib.crash.CrashHandler/u0a223 for service org.mozilla.fennec_aurora/mozilla.components.lib.crash.handler.CrashHandlerService
05-14 12:39:05.238 D/AndroidRuntime( 2825): Shutting down VM
05-14 12:39:05.367 I/WindowManager( 1136): WIN DEATH: Window{1a03df1 u0 SurfaceView - org.mozilla.fennec_aurora/org.mozilla.fenix.HomeActivity}
05-14 12:39:05.367 D/ConnectivityService( 1136): ConnectivityService NetworkRequestInfo binderDied(NetworkRequest [ LISTEN id=1852, [ Transports: WIFI Capabilities: NOT_RESTRICTED&TRUSTED&NOT_VPN&FOREGROUND] ], android.os.BinderProxy@269c82d)
05-14 12:39:05.367 D/GraphicsStats( 1136): Buffer count: 5
05-14 12:39:05.368 E/ConnectivityService( 1136): RemoteException caught trying to send a callback msg for NetworkRequest [ LISTEN id=1852, [ Transports: WIFI Capabilities: NOT_RESTRICTED&TRUSTED&NOT_VPN&FOREGROUND] ]
05-14 12:39:05.368 I/ActivityManager( 1136): Process org.mozilla.fennec_aurora (pid 2415) has died
05-14 12:39:05.368 D/ActivityManager( 1136): cleanUpApplicationRecord -- 2415
05-14 12:39:05.372 I/WindowManager( 1136): WIN DEATH: Window{485767c u0 org.mozilla.fennec_aurora/org.mozilla.fenix.HomeActivity}
05-14 12:39:05.373 I/Gecko   ( 2529): Exiting due to channel error.
05-14 12:39:05.377 I/Zygote  (  563): Process 2415 exited cleanly (11)
05-14 12:39:05.397 W/ActivityManager( 1136): Force removing ActivityRecord{393a420 u0 org.mozilla.fennec_aurora/org.mozilla.fenix.HomeActivity t784}: app died, no saved state
05-14 12:39:05.452 E/mozac/CrashReporter( 2835): CrashHandlerService received native code crash
05-14 12:39:05.455 I/mozac/CrashReporter( 2835): Received crash: NativeCodeCrash(minidumpPath=/data/user/0/org.mozilla.fennec_aurora/files/mozilla/93vzu7qg.default/minidumps/64294414-a65a-df8d-92f1-3b3a85df6967.dmp, minidumpSuccess=false, extrasPath=/data/user/0/org.mozilla.fennec_aurora/files/mozilla/93vzu7qg.default/minidumps/64294414-a65a-df8d-92f1-3b3a85df6967.extra, isFatal=true, breadcrumbs=[], uuid=f6e8b6f9-2864-4ed7-8bb3-16ab6d3eaf85)
05-14 12:39:05.498 I/ActivityManager( 1136): Process org.mozilla.fennec_aurora:tab0 (pid 2529) has died
05-14 12:39:05.498 D/ActivityManager( 1136): cleanUpApplicationRecord -- 2529
05-14 12:39:05.526 I/ActivityManager( 1136): Start proc 2858:org.mozilla.fennec_aurora/u0a223 for service org.mozilla.fennec_aurora/mozilla.components.lib.crash.service.SendCrashTelemetryService
05-14 12:39:05.529 I/mozac/CrashReporter( 2835): Showing prompt
```

Hope this helps.

**Comment by Amejia481** [comment]
I opened an Bugzilla bug for the geckoView team to take a look https://bugzilla.mozilla.org/show_bug.cgi?id=1638016

**Comment by liuche** [comment]
The change for this landed in Nightly and should be out to Firefox Beta and Firefox Preview. @gh5645 @VandaLHJ are you still seeing this?

**Comment by liuche** [comment]
Please reopen if you're still seeing this.

**Comment by gh7893** [comment]
@liuche Unfortunately still getting crashes, in a different/new assert.

Crash dump:
https://crash-stats.mozilla.org/report/index/1067aa50-8bde-4c53-a782-4f5690200612

**Comment by ekager** [comment]
@gh7893 to clarify - you're still seeing this in the latest Nightly, but with a slightly different dump you linked?

**Comment by gh7893** [comment]
@ekager Yes, exactly.

The assert was added in https://bugzilla.mozilla.org/show_bug.cgi?id=1635720#c22, which is the Bugzilla entry linked above.

**Comment by liuche** [comment]
I'm seeing 4 crashes total with this signature in the past 6mo, and the last one was from June 18, so I'm inclined to close this.
