### ISSUE TITLE
Show Undo snackbar when site from Collection is deleted

### ISSUE THREAD

**Issue by makabby** [mozilla-mobile/fenix#9485]
### Why/User Benefit/User Problem
When a user deletes a tab from a collection (sometimes by mistake), it will be helpful for the snackbar to pop up with the option to Undo the tab deletion. This currently happens when a tab is deleted/closed normally, so seeing this snackbar can be viewed as the expected behaviour whenever a tab is deleted anywhere.

### What/Requirements
Implement the snackbar trigger when a tab is deleted from a collection

### Acceptance Criteria (how do I know when I’m done?)
When users are able to undo tab deletion from a collection, as illustrated below:

![image](https://user-images.githubusercontent.com/57357223/77833263-510cef00-713c-11ea-9b56-621610dfedb5.png)

This feature request is based on [this UX review (see attached document in issue)](https://github.com/mozilla-mobile/outreachy-UX-2020/issues/2) conducted on the app.

**Comment by Diana-Rus** [comment]
HI, thank you for the report, there is already an issue reported for this. I'll close this as it is a duplicate.
Check issue:https://github.com/mozilla-mobile/fenix/issues/2725
Could you monitor the evolution of the issue there?

**Comment by makabby** [comment]
Sure. Thank you. @Diana-Rus
