### ISSUE TITLE
Search Widget Discoverability Experiment

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/fenix#9488]
We believe that by increasing the discoverability of our search widget, we can make search more accessible for our users while protecting them from privacy and security breaches. 

More details [here.](https://docs.google.com/document/d/12OT2lE192-jNgptpW_QzY3ieTg1H54Pq4pqbeskddPU/edit)

## CFR User Story
As a user, I want to know if there is a quicker way to search in Fenix by installing the search widget, so I can easily launch search from homescreen and get to my results quicker, while still being protected through Fenix privacy features + having all my search history in one place.

## Dependencies
- [ ] Design experiment (framework TBD)
- [ ] CFR to add search widget including a deep link to add search widget intent
- [ ] Telemetry to measure taps on the CFR

### Acceptance Criteria
- [ ]  If I am in the experiment cohort, after initiating n (tbd) searches I will see a toast including a deep link to install the search widget, and am able to successfully install the widget on my Android homescreen.
- [ ] Dashboard to show the correlation between the CFR and the search widget install event and retention. 

### Sprint plan
- [ ] First sprint: get Data Science signoff on what this experiment should look like
- [ ] 2nd sprint: Implement experiment based off of DS recommendations

**Comment by liuche** [comment]
Currently in UX feedback stage, should be ready for eng on Monday 4/27.

**Comment by brampitoyo** [comment]
@gabrielluong @sblatz – Betsy and I are meeting about it today, so we’re right on schedule.

**Comment by lime124** [comment]
@brampitoyo @betsymi can we remove the needs ux and strings labels?
@bifleming i'm not sure where to place this ticket while the experiment is running. i know there is a bit more work for Bram after the experiment runs.

**Comment by brampitoyo** [comment]
@lime124 Yep. Now that the design hand off has happened, this experiment doesn’t need `needs ux` and `needs strings` any more. We’re good to go and can move on to other projects.

Thanks @sblatz @gabrielluong for working on this!

**Comment by mcomella** [comment]
@sblatz @gabrielluong If you reintroduce the experiments framework, can you loop me into the discussion so I can help from a performance perspective? Ideally, ping me when you're deciding how to add it but if that's not possible, adding me to review is fine. Thank you!

**Comment by liuche** [comment]
Data Science should be ready with their part on Friday.

**Comment by liuche** [comment]
Megan from DS has been assigned here.

The next step is for DS, Eng, Product to figure out what the next steps for this experiment should be. (We should already have a Jira ticket, from @vesta0)

**Comment by vesta0** [comment]
Experiment JIRA request for DS: https://jira.mozilla.com/browse/DS-630

**Comment by gabrielluong** [comment]
@sblatz Busy with tabs tray things, won't have a chance to work with you on this 😞

**Comment by sblatz** [comment]
I'm starting work on this now! 😄

**Comment by sblatz** [comment]
QA: can we verify the search widget shows as expected in debug mode? It should have the following behavior:

* After a user does 3 searches and goes back to homescreen they should receive a popup asking them to install search widget
* If the user taps **outside** of the prompt, it should dismiss, and when the user returns to the homescreen next they'll receive it again. If a user dismisses second time, this will still happen. On a third outside tap, they'll **never see the prompt again**
* If the user taps "not now" they will **never see the prompt again**
* If the user taps "add search widget" (even if they do not actually do it) they will **never see the prompt again**
* If the user has a search widget installed already, they should not receive the prompt.
* The prompt should only be displayed in normal browsing home screen (not private browsing).

Please also verify the telemetry events added [here}(https://github.com/mozilla-mobile/fenix/pull/10958/files#diff-dcd3c2fb5158fcd99c56aa5b26b6de5dR1371-R1417) and [here}(https://github.com/mozilla-mobile/fenix/pull/10958/files#diff-dcd3c2fb5158fcd99c56aa5b26b6de5dR497-R510)

I know this is a lot so please ping me on slack or leave a comment here if there are any questions1 😄

**Comment by abodea** [comment]
Hello, Sawyer, I did some testing on this following the instruction from your comment here are my results:

* After a user does 3 searches and goes back to homescreen they should receive a popup asking them to install search widget - ✅ everything works as expected.

![20200603-122146](https://user-images.githubusercontent.com/42831109/83634224-d54f7880-a5aa-11ea-8995-bbfa891d85f2.gif)

* If the user taps **outside** of the prompt, it should dismiss, and when the user returns to the homescreen next they'll receive it again. If a user dismisses the second time, this will still happen. On a third outside tap, they'll **never see the prompt again** - ✅ everything works as expected.

![20200603-122225](https://user-images.githubusercontent.com/42831109/83635164-6a06a600-a5ac-11ea-8147-9c0bfe3fc453.gif)

* If the user taps "not now" they will **never see the prompt again** - ✅ everything works as expected.

![20200603-144743](https://user-images.githubusercontent.com/42831109/83636893-6294cc00-a5af-11ea-880c-2167b79ef7b7.gif)

* If the user taps "add search widget" (even if they do not actually do it) they will **never see the prompt again** ❌  The search widget is added but the user is not redirected to the home screen displayed the recently added search widget. I added this https://github.com/mozilla-mobile/fenix/issues/11183.

* If the user has a search widget installed already, they should not receive the prompt.  - ✅ everything works as expected.

![20200603-145115](https://user-images.githubusercontent.com/42831109/83638043-3a0dd180-a5b1-11ea-805f-b70968de6667.gif)

* The prompt should only be displayed in normal browsing home screen (not private browsing). - ✅ 
Note that the prompt is only displayed on the normal browsing, but after performing 3 searches on the PB, when I accessed the normal browsing, the prompt was triggered, I was not sure about the behavior, I added this bug https://github.com/mozilla-mobile/fenix/issues/11184

* Telemetry verification is in progress

**Comment by brampitoyo** [comment]
@sblatz All the behaviour you’ve outlined here matches what we’ve talked about in our last meeting, and what was documented in our InVision spec. Excellent, thanks!

**Comment by sblatz** [comment]
@abodea Are you able to test the telemetry portion again? You should be able to verify the behavior on this branch: https://github.com/mozilla-mobile/fenix/pull/11381

**Comment by abodea** [comment]
Hi, @sblatz did something changed in the debug build? Note that I'm not able to trigger the CFR anymore (maybe it is related to the new tabs tray?)

**Comment by sblatz** [comment]
@abodea You should be able to still trigger it by going to the home screen. (press tab tray, then press "new tab" button.

**Comment by abodea** [comment]
As I mentioned above and on slack, please note that I cannot trigger the CFR.
Removing the `eng:qa:needed` until further notice.

**Comment by sblatz** [comment]
This has launched!
