### ISSUE TITLE
[Bug] Clearing a site permissions exception does not immediately revoke that permission

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#9493]
## Steps to reproduce
Open webcamtests.com or any site that uses webcam
Allow the site to use the camera by "remember decision for this site" checkbox
Revoke the exceptions from Seeting -> Site Permissions -> Exceptions
### Expected behavior
The site can no longer use camera

### Actual behavior
The site can  use camera, up until refresh
### Device information

* Android device: Asus Zenfone
* Fenix version: Firefox Nightly

**Comment by liuche** [comment]
cc @Amejia481

**Comment by Amejia481** [comment]
> cc @Amejia481
We just need to reload after, changing anything on site permissions. What's is the priority on this issue? :)

**Comment by Amejia481** [comment]
This should be fixed in master, QA please, verify if the issue persist, thanks

**Comment by sv-ohorvath** [comment]
@Amejia481 This is fixed only if you clear *all* sites exceptions (Site permissions>Exceptions>Clear permissions on all site"). If you clear exceptions of a website only OR, if you got to Exceptions>[site exception]>Camera change to Block, return to website, it doesn't work in either case. You need to refresh. Do you think that could be fixed here as well?

**Comment by Amejia481** [comment]
> @Amejia481 This is fixed only if you clear _all_ sites exceptions (Site permissions>Exceptions>Clear permissions on all sites). If you clear exceptions of a website ( Exceptions>[website]>"Clear permission") only OR, if you got to Exceptions>[site exception]>Camera change to Block, return to website, it doesn't work in either case. You need to refresh. Do you think that could be fixed here as well?

I put a pr for address them https://github.com/mozilla-mobile/fenix/pull/10150, as soon it gets merged we can verify again thanks

**Comment by Amejia481** [comment]
@sv-ohorvath the fix was applied on master, would you mind re-testing? Thanks :)

**Comment by sv-ohorvath** [comment]
Thanks @Amejia481 . Verified as fixed on Nightly 4/27.
