### ISSUE TITLE
[Bug] Visual Bug in Site Permissions Exception UI

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#9494]
## Steps to reproduce
Set a site permissions exception on any site
Go to Settings-> Site Permission ->Exception -> Site  Name -> Any Option

### Actual behavior
There is a weird scrollbar that appears when you open this menu and it stays for a few secs before disappearing. it is not functional
![IMG-20200329-WA0000](https://user-images.githubusercontent.com/33252312/77850024-56f7e400-71bf-11ea-8e52-29df03724311.jpg)

### Device information

* Android device: Asus Zenfone 
* Fenix version: Fenix Nightly

**Comment by liuche** [comment]
@Amejia481 is this something in the AC site permissions code?

**Comment by Amejia481** [comment]
> @Amejia481 is this something in the AC site permissions code?

Not really, all the ui lives in Fenix, looks like an device specific issue.
