### ISSUE TITLE
[Bug] Crash on Sharing using uninstalled app

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#9495]
## Steps to reproduce
Open the Share Link menu from the three dot menu.
Press home button and Uninstall one of the apps shown within the menu
Return to fenix and as the app is still shown within the share sheet, click on that app.

### Expected behavior
The app should vanish from share sheet upon unsinstalling
### Actual behavior
Crash
### Device information

* Android device: Asus Zenfone
* Fenix version: Fenix Nightly

**Comment by ekager** [comment]
This seems like an edge case but we could fix this fairly easily! I took a look at what others apps do and it looks like they dismiss the share sheet on app pause. Let's do that.
In `ShareFragment`, let's `dismiss()` in `onPause`

**Comment by Benbyday** [comment]
This sounds like 4ish lines of code that I feel confident enough to work on. Is this issue still available? When I looked at the updated code it seems like this hadn't been closed yet.

**Comment by abhay379201** [comment]
I want to work on this issue. I have already created a PR for this issue.

**Comment by amo-ali** [comment]
what is PR??

**Comment by Benbyday** [comment]
Pull Request

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Fenix debug from master Build #21000923 39.0.20200408130125, 356eb1e87 GV: 77.0a1-20200407093520 AS: 0.55.0`** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)

►  Video
![20200409-105628](https://user-images.githubusercontent.com/51314259/78873026-d6ed3c00-7a52-11ea-807d-cfe852b54171.gif)
