### ISSUE TITLE
[Bug] Keyboard doesn't appear when clicking URL bar

### ISSUE THREAD

**Issue by moztcampbell** [mozilla-mobile/fenix#9497]
## Steps to reproduce
1) Visit a website (eg. mozilla.org)
2) Scroll down so URL bar auto-hides
3) Scroll up so URL bar reappears
4) Tap URL bar

### Expected behavior
Search view opens with cursor in search box and keyboard visible.

### Actual behavior
No keyboard appears. Tapping search box makes cursor appear but no keyboard still.

Workaround is to tap in dead space until text box unfocuses. Then clicking the search box causes keyboard to appear.

### Device information

* Android device: Pixel 3 / Android 10 (QQ2A.200305.002)
* Fenix version: Firefox Nightly 20200325093457

**Comment by quadriflax** [comment]
Same here. Sometimes it pops up, but frequently does not. Makes it almost impossible to use this browser now.

**Comment by ekager** [comment]
Closing for #9500

**Comment by StSav012** [comment]
@ekager, what's happened? You've just silently closed the issue.
