### ISSUE TITLE
Back Button at homescreen doesn't close Firefox Preview [Bug]

### ISSUE THREAD

**Issue by LittleAngelwings** [mozilla-mobile/fenix#9498]
## Steps to reproduce
Open at least one tab, than go back to Firefox Preview homescreen and close the app by pressing device back button. 

### Expected behavior

Firefox Preview is closing immediately 

### Actual behavior

Firefox will be closed only by more then two clicks on back button

### Device information

* Android device: Samsung Galaxy Tab A6 SM-T580 and Huawei P Smart 
* Fenix version: Nightly 200329 06:00 (Build #20890605)
38.0.20200326160141, d34bd466f
GV: 76.0a1-20200325093457
AS: 0.55.0

**Comment by ekager** [comment]
Can reproduce on Pixel 3

**Comment by ekager** [comment]
Cc @mcarare not sure if this is related to the new home fragment navigation / scrolling but worth a look?

**Comment by LittleAngelwings** [comment]
Issue is gone in this build via GP

Nightly 200330 18:00 (Build #20901803)
38.0.20200329190103, 1341d92fa
GV: 76.0a1-20200327094805
AS: 0.55.0

**Comment by abodea** [comment]
Verified as fixed on **Nightly 4/1** with **Google Pixel 4 XL (10), Samsung Galaxy S7 (7).**
Note that Fenix is closed immediately after tapping on the back button.
