### ISSUE TITLE
[Bug] "New tab opened" snackbar not displayed right above toolbar

### ISSUE THREAD

**Issue by SL-Lee** [mozilla-mobile/fenix#9499]
## Steps to reproduce

1. Visit a page and long press on any link.
2. Select "Open link in new tab".

### Expected behavior

The "new tab opened" snackbar is displayed right above the toolbar.

### Actual behavior

The "new tab opened" snackbar is displayed with additional space above the toolbar (might be related to #8773).

![](https://user-images.githubusercontent.com/45960387/77854454-175fe500-721d-11ea-918f-069e8d040eb0.png)

### Device information

* Android device: Oppo Reno 2, Android 9
* Fenix version: Nightly 200329 06:00 (Build #20890606)

**Comment by Diana-Rus** [comment]
Hi, i am also able to reproduce this issue with Google Pixel 3 Xl (Android 9) and Samsung Galaxy S9 (Android 8) besides this snack bar the following snack bars are also affected:
- "Tab saved" when saving from Menu/Save Collection.
- "Bookmark saved"when bookmarking a page
- "Added to top sites" from Menu/Add to top site option
Note: This seems a regression from bug #8773

**Comment by sv-sdeiac** [comment]
Verified as fixed using the latest version of Firefox Preview Nightly 4/3 #20940609.
Now the snack bar notifications are displayed right above the toolbar menu.

Devices:
- Google Pixel 3 (Android 10);
- Samsung Galaxy Note 8 (Android 9);
- LG g7 fit (Android 8.1).
