### ISSUE TITLE
Save Private Session

### ISSUE THREAD

**Issue by bbinto** [mozilla-mobile/fenix#95]
- one session only

**Comment by sblatz** [comment]
Can we confirm what we mean by this? I was under the impression that private sessions could not be saved. 

Looping in @shorlander for some clarification on the UX side of things.

**Comment by boek** [comment]
@sblatz We have since decided to not persist any private browsing sessions. Just the fact that we are in private browsing mode: 

https://github.com/mozilla-mobile/fenix/issues/181#issuecomment-461017913
