### ISSUE TITLE
[Bug] youtube bottom toolbar is not properly positioned when changing browser toolbar location

### ISSUE THREAD

**Issue by xiasongh** [mozilla-mobile/fenix#9501]
## Steps to reproduce
Settings -> Customize -> Toolbar Top -> Go on Youtube website

### Expected behavior
Youtube toolbar should be aligned at the bottom

### Actual behavior
Youtube toolbar floats and is not at the bottom

### Device information

* Android device: Samsung S8+

**Comment by liuche** [comment]
Thanks for filing! This is the same problem as #8768, so I'm going to close as a dupe.
