### ISSUE TITLE
Either UBO should not be active in Custom Tabs or there should be an option to disable it in the Custom Tab

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#9503]
### Why/User Benefit/User Problem
Many websites have implemented anti-adblock techniques that make that website unusable for those using UBO. While this can be circumvented using certain filterlists, for the average user the easiest way is to simply disable UBO for that website. Currently UBO is active on custom tabs but there is no option to disable it there. So if someone were to open such a page in custom tabs, they would be unable to access it and would have to open in Firefox and then disable UBO for it to work. 
### What/Requirements
Since such a method is needlessly time consuming (2x the load time + some links may be one time use only) a better method is to give the option to disable UBO,(and presumably other addons) within a custom tab
### Acceptance Criteria (how do I know when I’m done?)
Addons option in 3 dot menu in custom tab

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-16503)

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812845

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
