### ISSUE TITLE
Edit Logins

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/fenix#9504]
## User Story
As a user, I want to be able to edit my logins, so I have control over changing them manually. 

### Acceptance Criteria
I can edit my logins in Logins settings
   - [x] Add kebab (three dot) menu to login info toolbar with options to edit and delete
   - [x] Add fragment with editable fields
     * disable web address editing - YES
   - [ ] Error states
     * possibly break this out into a separate piece of work?
   - [x] Save enabled only when valid
     * Successful save routes to site info page
   - [ ] Cancel (`X`) button 
     * where does cancel route to - login info
     * do we want a confirmation dialog - no
   - [x] Feature flags

## Designs
[UX Mocks](https://share.goabstract.com/33afd8de-f90e-4504-90e3-ee2a3bcb1925?mode=design&sha=2b7a1bf44fa2c02a3b7e470075e94c587a491d3b
)

### SVG Icons
[checkmark](https://drive.google.com/open?id=16GAx-27bja-hxaKpgaRVNrzcsiS1gJ1p) 
[drop-down arrow](https://drive.google.com/open?id=16evm0KYF898lgt9UKqw8l-rrBFX9Z3gD) 
[warning](https://drive.google.com/open?id=182eby9q2g-vviWa1LfHcDXluQzUEIdmn) 
[clear text field ](https://drive.google.com/open?id=127i_O5i1wfREI170426Pz6WSQGh3heMe)

**Comment by eliserichards** [comment]
@jonichan Hey Joni! Just wanted to let you know that I will be starting this issue soon and I'll reach out to you about getting some help docs on the SUMO site! 😄

**Comment by ekager** [comment]
Reopening for QA

**Comment by ebalazs-sv** [comment]
Hi!
I tested this on Fenix Nightly Build 21420606 from 5/21 with Nexus 5 (Android 6.0.1), Motorola Moto G6 (Android 8), Google Pixel 2 (Android 9) and these are the results:

| Status  | Options/Settings  | Notes  |
| ------------- | ------------- | ------------- |
| ✔️  | Kebab ⋮ button| This button is displayed as in the UX Mocks |
| ❓  | Kebab ⋮ button  menu (Edit & Delete)| Different menu style compared to the one from the sort logins section|
| ✔️  | Fragment with editable fields  | The Username and Password fields are editable  |
| ✔️  | Fragment with editable fields - disable web address editing  | The Site is not editable |
| ❓  | Fragment with editable fields  | The show/hide button is actionable on the all Password field  |
| ❓  | Fragment with editable fields  | The password becomes uneditable if tapped anywhere else than the end of the password  |
| ❓  | Save enabled only when valid - Successful save routes to site info page | The edited login can be saved even if the username field is empty or left incomplete  |
| ❓  | Error states  | This is not available  |
| ❓  | Cancel (X) button  | This is not available  |

CC @eliserichards and @ekager Please review and advice the above findings.
Also the Error states and Cancel button are not implemented.

There is filed one issue related to this:
https://github.com/mozilla-mobile/fenix/issues/10725

I will remove the qa:needed until further notice. Thanks!

**Comment by eliserichards** [comment]
Moving this to "done" as the missing pieces haven't been implemented yet (#10173 and #10172)

**Comment by liuche** [comment]
Close this issue because the subsequent pieces will be in the follow-ups, that have been filed.
