### ISSUE TITLE
[Bug] "Open in app" text is not displayed when returning from GPlay on twitch

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/fenix#9508]
## Steps to reproduce
1. Launch Fenix.
2. Access `https://twitch.tv`.
3. Tap on the `Open in app` button (it doesn't matter if the app is installed or not).
4. Tap back twice to return to Fenix.
### Expected behavior
The text `open in-app` from the dedicated button should be displayed.
### Actual behavior
`Open in app` text is not displayed when returning from GPlay on twitch
### Device information

* Android device: **Google Pixel 4 XL (10).**
* Fenix version: **Nightly 3/30.**

![20200330-130921](https://user-images.githubusercontent.com/42831109/77901306-0c8e6a00-7288-11ea-9fb6-9a3d941684e1.gif)

**Comment by ValentinTimisica** [comment]
Seems like this bug is also replicated in Chrome.
Check [this video](https://drive.google.com/file/d/149kU_Wd1g5SetCuULYyUx-pzlRU73dax/view?usp=sharing).
