### ISSUE TITLE
Allow Pinning Navbar

### ISSUE THREAD

**Issue by NotAFile** [mozilla-mobile/fenix#9509]
### Why/User Benefit/User Problem

When I originally switched to Fenix, the static navbar bothered me. However, having used both for about equal amounts of time, I now prefer the wasted pixels of a static navbar to the "finnickyness" of a dynamic one on a larger device.

(This might also be good for accessibility. I know someone with a hand disability who has to change the grip on the phone between scrolling and typing. But that would have to be confirmed by anyone affected of course.)

### What/Requirements
An option to ensure that the navbar is always visible.

### Acceptance Criteria (how do I know when I’m done?)
I can scroll a page without the navbar disappearing.

**Comment by cadeyrn** [comment]
Duplicate of #8847.

**Comment by NotAFile** [comment]
ah, sorry, I hadn't hit the right keywords
