### ISSUE TITLE
[Feature request] Check open tabs for duplicates when opening from collection

### ISSUE THREAD

**Issue by sflorean** [mozilla-mobile/fenix#9511]
## Prerequisites
- Have Google, youtube, twitter pages added to the Collection A. 
- Have Google, youtube, twitter pages displayed in the "Open tabs" section. 

## Steps to reproduce
1. Go to collection A and open all the tabs.
2. Check the "Open tabs" section.

### Expected behavior
Open tabs are not duplicated, only one URL is displayed for one page (if the URL is exactly the same).

### Actual behavior
The open tabs are duplicated; reproducible every time the tabs from collection A are being opened. 

### Device information
* Android device: Nokia 6 (Android 7.1.1), Samsung Galaxy Note10 (Android 10).
* Fenix version: Nightly 3/30, Beta 4.2.0-beta.3.

ref #4987 

![Screenshot_20200330-152847_Firefox Nightly](https://user-images.githubusercontent.com/58466444/77912699-ad3a5500-729b-11ea-9f34-bec7b01f305c.jpg)

**Comment by cadeyrn** [comment]
To be honest I disagree with your proposed behaviour. For me "Open tabs" means "open tabs", not "open some tabs" or "do some deduplication magic in the background". It should not be depend on my already opened tabs.

Desktop Firefox does not have collections but bookmark folders. It's very similar. Let's say you have a open tab with "website A" and then you decide to open all bookmarks in your bookmarks folder and one of these bookmarks is "website A". Firefox on desktop will also open "website A" a second time and it would be unexpected (for me, at least) to have a different behaviour with collections on Android.

**Comment by BranescuMihai** [comment]
I feel the same as @cadeyrn here, maybe I want to add another Google search from the collections while another one is open. Let's see what UX proposes regarding this.

**Comment by sflorean** [comment]
Agree, if I have 2 different Google searches to be both opened. I think that it might be confusing for users to have the same URL opened twice or more, so just to be clear the issue is about the URLs that are exactly the same. @cadeyrn @BranescuMihai

**Comment by brampitoyo** [comment]
This is a great question for @topotropic, so I’ll assign this issue to her.

**Comment by AmyYLee** [comment]
@topotropic For follow-up

**Comment by topotropic** [comment]
Since we save the back stack for every site in a collection I'd suggest to open it as duplicate and keep the current behavior. Thanks for the feedback!
