### ISSUE TITLE
[Bug] Redundant Scroll Animation in Context Menus

### ISSUE THREAD

**Issue by theFireProject** [mozilla-mobile/fenix#9512]
## Steps to reproduce
- open a website
- long-press on a text link
- try to scroll down or up in the area of the available options in the context menu

### Expected behavior
It's not possible to scroll as all option are displayed on the screen, nothing should happen, no action should be performed and no visual indication for scrolling should be displayed:
![20200330_143754](https://user-images.githubusercontent.com/61639215/77913206-22a22780-7294-11ea-8fcd-257cd9321f82.jpg)

### Actual behavior
It's not possible to scroll as all option are displayed on the screen, no action is performed but visual indication for scrolling is displayed:
![20200330_143809](https://user-images.githubusercontent.com/61639215/77913187-1ae28300-7294-11ea-9b78-945704ed0a1b.jpg)

### Device information

* Android device: Samsung Galaxy S9+ (Android 8.0.0)
* Fenix version: 4.1.0

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-16511)

**Comment by Poopooracoocoo** [comment]
oof this is a common thing with Android Components. I've filed an issue like this before somewhere too.

**Comment by sv-sdeiac** [comment]
Hi, I can confirm that this issue is reproducible using the latest version of Firefox Preview Nightly 3/31 #20910606.

Devices:
- Google Pixel 3 (Android 10);
- Samsung Galaxy Note 8 (Android 9).

**Comment by sflorean** [comment]
This is still reproducible on latest versions of Fenix. 
Device: Samsung Note 10 (Android 11).

**Comment by SoftVision-LorandJanos** [comment]
This behavior is still reproducible on the:
- latest Nightly (2021-11-25).
- latest Beta (95.0.0beta5).
- latest Release (94.1.2).

Device used: Xiaomi Mi11 Lite (Android 11).
