### ISSUE TITLE
[a11y] Switch Talkback language based on html lang attribute

### ISSUE THREAD

**Issue by meldafert** [mozilla-mobile/fenix#9513]
### Why/User Benefit/User Problem
When using Firefox Preview with Talkback, the system voice/language is always used. This makes it unusable for websites that have a different language (reflected by the html lang attribute), as for example something in French (language of the website) is not understandable when interpreted as English (System language). Chrome on Android is able to do this.

### What/Requirements
Make Talkback read websites with a html lang attribute that is different from the system voice/language in that language. This appears to be possible with [LocaleSpan](https://stackoverflow.com/questions/44346134/change-talkback-language-dynamically), although I am not familiar with Android APIs.

### Acceptance Criteria (how do I know when I’m done?)
The html lang attribute is properly respected and Talkback uses an appropriate voice for the set language.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-16512)

**Comment by ekager** [comment]
@meldafert are you still seeing this issue?

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813609

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
