### ISSUE TITLE
[Bug] Misspelling in 'Delete browsing data' settings

### ISSUE THREAD

**Issue by theFireProjet** [mozilla-mobile/fenix#9519]
## Steps to reproduce
- go to 'Settings' > 'Delete browsing data'
- go to 'Settings' > 'Delete browsing data on quit'

### Expected behavior
"Open Tabs" should be "Open tabs" as for all other elements only the first letter of the line is capitalized.

### Actual behavior
"Tabs" is capitalized in "Open Tabs".

### Device information

* Android device: Samsung Galaxy S9+ (Android 8.0.0)
* Fenix version: 4.1.0

**Comment by sv-sdeiac** [comment]
Hi, the issue is reproducible using the latest version of Firefox Preview Nightly 3/31 #20910606.

Devices:
- Google Pixel 3 (Android 10);
- Samsung Galaxy Note 8 (Android 9).

**Comment by apbitner** [comment]
This has been fixed.
