### ISSUE TITLE
Remove the "save image" confirmation

### ISSUE THREAD

**Issue by test2a** [mozilla-mobile/fenix#952]
https://ibb.co/w7xtQFJ

This is not a good behaviour. If I clicked on save image, it should respect that decision and not ask me to confirm. The regular Firefox or even focus does not do that. NO browser does that

**Comment by pocmo** [comment]
Added the "qa needed" label. The fix should be in Nightly now.

**Comment by AndiAJ** [comment]
Hi, I've check on Nightly Build #12941811 from 21/10 and it looks like the **confirmation isn't displayed anymore**, but on the other hand I've noticed that after **the desired image is continuously downloaded.**

Used devices:
• Google Pixel 3a (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0) 
• Samsung Galaxy S7  (Android 7)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

► Video
![20191027_111922](https://user-images.githubusercontent.com/51314259/67291633-81e05c80-f4ea-11e9-9404-b1dc84a7e07f.gif)

@pocmo - I would kindly ask you to review. :)
I'll remove the QA needed label until further clarifications.

**Comment by pocmo** [comment]
Thanks, I'll debug!

**Comment by pocmo** [comment]
Follow-up fix in AC: https://github.com/mozilla-mobile/android-components/issues/4830

**Comment by liuche** [comment]
Looks like it got fixed, can we verify?

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **Nightly Build #13440604 from 12/10** using the following devices:
• Google Pixel 3a XL (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

►Video
![20191210_142701](https://user-images.githubusercontent.com/51314259/70529998-917b3980-1b5a-11ea-8272-8aa8df8813e7.gif)
