### ISSUE TITLE
[Bug] <select multiple> doesn't work on Fenix

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/fenix#9521]
## Steps to reproduce

1. Go to https://www.w3schools.com/tags/tryit.asp?filename=tryhtml_select_multiple
2. Tap the list of cars

### Expected behavior
A popup that allow to select multiple options should be shown.

### Actual behavior
Only one option is allow to be selected

**Comment by kbrosnan** [comment]
Worth mentioning that on Matrix Amejia481 said this worked in Reference Browser. So A-C/GeckoView supports this.

**Comment by kbrosnan** [comment]
Independently https://bugzilla.mozilla.org/show_bug.cgi?id=1625604 was filed

**Comment by Amejia481** [comment]
This is a regression on geckoView nightly, I described the issue on the Bugzilla bug https://bugzilla.mozilla.org/show_bug.cgi?id=1625604#c2

**Comment by fluffyemily** [comment]
This issue has been resolved in GeckoView

**Comment by Amejia481** [comment]
Lets QA help us to verified that the issue is fixed :)

**Comment by sflorean** [comment]
Verified as fixed on Nighly 4/22. Devices: Nokia 6 (Android 7.1.1), Samsung Galaxy Note 10 (Android 10) and Xiaomi Redmi Note 8T (Android 9).
