### ISSUE TITLE
[Bug] error downloading mov file type

### ISSUE THREAD

**Issue by fftracker** [mozilla-mobile/fenix#9522]
## Steps to reproduce go to:
 https://send.tresorit.com/a#uRDGVuiMsTcM8UOej9wJ5g
If you don't trust this link you can just download a random mov file type and send it to yourself using tresorit. It's free to use.

### Actual behavior: popup message saying "firefox nightly can't download this file type"

I have tried this successfully on both firefox browser and firefox beta(android). 

### Device information

* Android device: android 9
* Fenix version: Nightly 200330 06:01

**Comment by kbrosnan** [comment]
Uses blob: for downloads. Closing as a dupe https://github.com/mozilla-mobile/fenix/issues/2579#issuecomment-597365647
