### ISSUE TITLE
[Bug] missing space between "Top sites" caption and top sites

### ISSUE THREAD

**Issue by cadeyrn** [mozilla-mobile/fenix#9525]
### Steps to reproduce

1. open the Fenix start screen

### Expected behavior

The spacing between the "top sites" caption and top sites has the same height as for open tabs and collections.

### Actual behavior

The spacing between the "Top sites" caption and the top site is much smaller than for open tabs and collections.

![screenshot](https://user-images.githubusercontent.com/1100614/77946309-61e76d00-72c2-11ea-8341-12467d76c55e.png)

/cc @darkwing 

### Device information

* Android device: OnePlus 7T Pro McLaren Edition, OxygenOS 10.0.7 (Android 10)
* Fenix version: master branch revision e1187ebf31557528764a1e82615cd1446440f8f1

**Comment by sv-sdeiac** [comment]
This issue is still reproducible on the latest version of Firefox Preview Nightly 3/31 #20910606.

Devices:
- Google Pixel 3 (Android 10);
- Samsung Galaxy Note 8 (Android 9).

**Comment by cadeyrn** [comment]
To repeat what I already said in #9527: It's better now but it still has less spacing as open tabs and collections and this difference is noticeable.

**Comment by cadeyrn** [comment]
There is no longer a "Top sites" caption on the start screen, closing.
