### ISSUE TITLE
[Bug] minor style issues with permissions dialog

### ISSUE THREAD

**Issue by cadeyrn** [mozilla-mobile/fenix#9529]
### Steps to reproduce

1. open a website
2. click on the padlock icon in the address bar

### Expected behavior

1. site has no special permissions: no grey separator line below the identity row
2. site has special permissions: same top and bottom padding in the permissions section

### Actual behavior

1. site has no special permissions: there is a grey separator line below the identity row
2. site has special permissions: there is much less bottom than top padding in the permissions section

![screenshot](https://user-images.githubusercontent.com/1100614/77948732-22228480-72c6-11ea-8978-fca389fc2331.png)

### Device information

* Android device: OnePlus 7T Pro McLaren Edition, OxygenOS 10.0.7 (Android 10)
* Fenix version: master branch revision e1187ebf31557528764a1e82615cd1446440f8f1

**Comment by apoorv9990** [comment]
@cadeyrn Is this the intended behavior?
For image 1: There should be no space below the grey divider
For image 2: No grey divider

**Comment by cadeyrn** [comment]
@apoorv9990 No. But my original description was not correct. I corrected it a few moments ago. I hope it's clear now.

**Comment by apoorv9990** [comment]
@cadeyrn yes it is pretty clear now. Can I work on this?

**Comment by cadeyrn** [comment]
I am not in the Fenix team but since the issue has "eng:ready" and "help wanted" labels: yes, I think so! Thank you! :)

**Comment by apoorv9990** [comment]
I have created https://github.com/mozilla-mobile/fenix/pull/10227 that closes this issue.
