### ISSUE TITLE
[Bug] Sending string value for Library telemetry

### ISSUE THREAD

**Issue by ekager** [mozilla-mobile/fenix#9533]
We are sending the string of the selected item here but we should be sending an enum so we don't have translation issues/bad telemetry :/ 
https://github.com/mozilla-mobile/fenix/blob/master/app/src/main/java/org/mozilla/fenix/components/metrics/Metrics.kt#L239

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly Build #20970607 from 4/6`** using a Google Pixel 3a (Android 10).

✔️ The LibraryItem enum constants are properly displayed.
![image](https://user-images.githubusercontent.com/51314259/78551642-b3d24a80-780e-11ea-9e47-5e0e92a28811.png)

► Open Bookmarks from Library - Ping `596a6f93-9f3c-4520-9cbc-c0cf5ebcc803` 

**{
          "category": "library",
          "extra": {
            "item": "BOOKMARKS"
          },
          "name": "selected_item",**


► Open History from Library - Ping `f5df58ed-3769-4ea3-84dd-d1f0fa6f76f9`
 	**{
          "category": "library",
          "extra": {
            "item": "HISTORY"
          },
          "name": "selected_item",**


[Logcat](https://github.com/mozilla-mobile/fenix/files/4437961/enums.txt)
[Glean dashboard](https://debug-ping-preview.firebaseapp.com/pings/aj-t060400)

@ekager - Please review and let me know if anything else needs to be checked. ☺️
