### ISSUE TITLE
[Bug] URL Bar not visible on restored page

### ISSUE THREAD

**Issue by agi90** [mozilla-mobile/fenix#9534]
## Steps to reproduce

Launch page with fixed url bar (e.g. maps.google.com)
Background fenix
`adb kill` Fenix (to simulate Android killing the app)
Open fenix again

### Expected behavior

URL bar should be visible

### Actual behavior

URL bar is not visible, no way to make it appear again (scrolling doesn't do anything)

### Device information

* Android device: Samsung S10e, Android 10
* Fenix version: Latest Preview Nightly from Play Store

![Screenshot_20200330-222945_Firefox Nightly](https://user-images.githubusercontent.com/4297388/77990660-c280a500-72d6-11ea-80f4-ddfc089f531d.jpg)

**Comment by ekager** [comment]
@agi90 do you still see this? I tried to repro and couldn't
