### ISSUE TITLE
Link always opening Google Play (Twitter -> Medium)

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/fenix#9538]
## Steps to reproduce

* Click on medium.com link in Twitter

### Expected behavior

* Loading medium article in browser

### Actual behavior

* Browser opens and always immediatelly opens the Play store showing the medium app. I don't want the app and just read the article. I disabled "Open links in apps" and it still opens Google Play.

### Device information

* Android device: Pixel 3, Android 10
* Fenix version: Nightly

**Comment by pocmo** [comment]
@rocketsroger Should that be controlled by the setting or is there some other way to prevent that from happening?

**Comment by rocketsroger** [comment]
I will have to investigate.  The current design is if the site redirect us to a intent we will open that intent regardless of the user preference in "Open links in apps".

**Comment by rocketsroger** [comment]
@pocmo can't reproduce.  Can you try? maybe Medium have updated their site.

**Comment by pocmo** [comment]
Can't reproduce it anymore with the latest Nightly version.
