### ISSUE TITLE
current tab show implementation is not perfect

### ISSUE THREAD

**Issue by test2a** [mozilla-mobile/fenix#954]
### Why/User Benefit/User Problem
https://ibb.co/nQ4szFg
check this. this is the default view with multiple tabs open. see that there is a lot of unused space at the top around the name and search bar. this seems to me mimicking samsung's OneUI. this is not entirely productive.

second, 
https://ibb.co/s2D8Yvs

this shows up after you swipe up to check tabs. see the presence of search bar at the top. shouldnt the search bar dissolve upwards unless the user swipes down a bit to reveal it, as opposed to having it permanently there. The best example of it would be the browser chrome that vanishes once a page is open and only shows up if the user swipes down a bit.

**Comment by vesta0** [comment]
Thanks for the suggestions! We will take them into consideration. cc @lime124
