### ISSUE TITLE
[Bug] different shadow for tabs and collections

### ISSUE THREAD

**Issue by cadeyrn** [mozilla-mobile/fenix#9542]
### Steps to reproduce

1. open the Fenix start screen

### Expected behavior

Same shadow for open tabs and collections.

### Actual behavior

The shadow is noticeable different for open tabs and collections, the collections shadow seems to be "stronger", darker…

![Screenshot_20200330-235306](https://user-images.githubusercontent.com/1100614/78019015-3bbbde80-734f-11ea-983f-51b9b1ffb875.jpg)

### Device information

* Android device: OnePlus 7T Pro McLaren Edition, OxygenOS 10.0.7 (Android 10)
* Fenix version: master branch revision e1187ebf31557528764a1e82615cd1446440f8f1

**Comment by theFireProjet** [comment]
This might not be a bug.

The space inbetween multiple collections is bigger than the space inbetween tabs. There is more space for the shadow. Also it fits reality: Bigger objects throw bigger shadows.

Thinking about it, I feel it looks good they way it is.

**Comment by cadeyrn** [comment]
> Also it fits reality: Bigger objects throw bigger shadows.

This is not the case as you can see in my screenshot, the **opposite** is true. The collection box is much smaller and has the stronger shadow. 

> Your collection is much smaller than in my browser

This is the new collapsed collection design in the master branch. Firefox Preview 4.2 still has the old design.

> Thinking about it, I feel it looks good they way it is.

This is your opinion and that's fine. But I don't agree. There is a noticeable difference and this makes the start screen unbalanced. Also I don't think that your reasoning reflects the reality. Let me give you an example of a box-shadow of a website:

<img width="2340" alt="screen" src="https://user-images.githubusercontent.com/1100614/78025979-3795be00-735b-11ea-9cb5-0ee32c73257a.png">

On the left side you see the default look. On the right side I increased the height of the box. In both cases the shadow below the box is exactly the same, there is no difference at all. It's easy to check with a color picker that there are no color differences but in Fenix there are different colors on similar positions. So it's an unexpected result.

**Comment by theFireProjet** [comment]
Okay, I agree. I think you're right.

In case the shadows are adjusted to be the same between tabs and collections, is there a good reason for the different distance between two tabs and two collections? Or should the distance be adjusted as well?

**Comment by AmyYLee** [comment]
The introduction of tab tray will remove open tabs from the homescreen.
