### ISSUE TITLE
Rounded Corners for Icons in Top Sites

### ISSUE THREAD

**Issue by theFireProjet** [mozilla-mobile/fenix#9543]
### Why/User Benefit/User Problem
It's a visual improvement to the user interface that makes the top sites icons match the design of the tabs icons. Therefore it's a more consistent design that looks better and is more modern.

### What/Requirements
- Make the corners of the top sites icons round the same way they are for the tabs icons.

Currently, website icons are displayed in the top sites the way they are whether that's square or round. The auto created icon for websites without their own icon looks as it has rounded corners in the top sites but that's not real, actually it's simply an octagonal shape. At least for me, that's visible on my phone with the naked eye.

![20200331_131522](https://user-images.githubusercontent.com/61639215/78020481-d4535e00-7351-11ea-917b-87085a1758d8.jpg)

### Acceptance Criteria (how do I know when I’m done?)
If all icons in the top sites have rounded corners.

**Comment by gabrielluong** [comment]
I believe we have done some justice for this issue with the continual work on top sites design. See the latest at https://github.com/mozilla-mobile/fenix/issues/13765.

Closing this issue and will defer to #13765.
