### ISSUE TITLE
Restore tab tray 

### ISSUE THREAD

**Issue by topotropic** [mozilla-mobile/fenix#9544]
### Why/User Benefit/User Problem
Currently, open tabs, collections and top sites are on “Home”.  This leads to a feeling of clutter:   Collections are no longer at hand once you have a few open tabs and users experience tab switching as slow. By introducing a dedicated tab tray, we address above issues and also create dedicated space to improve a core browser experience and create a foundation for follow-up improvements.

We already started on the implementation but put it on hold. The goal here is to restore this work and create follow-up issues based on the current implementation.

### What/Requirements
- restore tab tray
- review current state
- create follow-up issues

**Comment by gabrielluong** [comment]
Closing this as WONTFIX since we already moved ahead with integrating the tabs tray from AC.
