### ISSUE TITLE
[Bug][a11y]Sharing the opened tabs doesn't differentiate the close button and Share title

### ISSUE THREAD

**Issue by sv-sdeiac** [mozilla-mobile/fenix#9545]
### Prerequisites
Talkback needs to be enabled.

## Steps to reproduce
1. Open any page;
2. Go to the homepage of the app;
3. Open the 3dot menu from the "Open tabs" section;
4. Tap on the "Share tabs" button;
5. Focus the Talkback to the "X" button.

### Expected behavior
The close button is read by the Talkback.

### Actual behavior
The "X" button with "Share" title are focused and read as "Share button"

### Device information
Android device:
- Google Pixel 3 (Android 10);
- Samsung Galaxy Note 8 (Android 9).

Fenix version: Firefox Preview Nightly 3/31 #20910606.
![Screenshot_20200331-135433_Firefox Nightly](https://user-images.githubusercontent.com/40264165/78021113-572ce680-735b-11ea-898d-709c66840116.jpg)

**Comment by theFireProjet** [comment]
It's the same for the 'Select Tabs' to save to collection view.

**Comment by asadotzler** [comment]
This is an accessibility P2. The feature is available and works but is difficult to use because of misleading button labeling. This kind of bug prevents Fenix from being a delightful experience for users with disabilities.

**Comment by mcarare** [comment]
@asadotzler Will a content description of "Close" suffice for both? The action is the same, closing that screen, even though one icon is close and the other is back. 
Maybe UX can clarify why there is a  difference?

**Comment by brampitoyo** [comment]
@mcarare Hmm. This is odd. We expected that only the close/back button would be highlighted. The page title should never be included in the selection, unless it’s highlighted separately.

**Comment by brampitoyo** [comment]
@mcarare I also see what you’re saying about why we sometimes have a back icon, and sometimes it’s close. I agree that it’s inconsistent. Let’s file a new issue for this – something that we want Content Strategy to be aware.

**Comment by brampitoyo** [comment]
@mcarare Filed #10105.

**Comment by sflorean** [comment]
Verified as fixed on the latest Nightly build 6/3 with Google Pixel 3 (Android 10) following the steps from the description.

 The issue described in [here](https://github.com/mozilla-mobile/fenix/issues/9545#issuecomment-606572629) is not fixed, the back button isn't highlighted. 
@mcarare this will be covered in a different bug?

**Comment by mcarare** [comment]
@sflorean Yes, in https://github.com/mozilla-mobile/fenix/issues/10105.
