### ISSUE TITLE
[Bug]Toolbar reacts to the up/down scroll over the context menu

### ISSUE THREAD

**Issue by sv-sdeiac** [mozilla-mobile/fenix#9546]
## Steps to reproduce
1. Open a page;
2. Long tap and hold on a hyperlink or image(don't release the tab);
3. Scroll up/down.

### Expected behavior
No movements are displayed while the long tap is still on hold.

### Actual behavior
The toolbar reacts to the up/down scroll over the context menu.

### Device information

Android device:
- Google Pixel 3 (Android 10);
- Samsung Galaxy Note 8 (Android 9).

Fenix version: Firefox Preview Nightly 3/31 #20910606.
![20200331_151400](https://user-images.githubusercontent.com/40264165/78025304-7aa75f80-7362-11ea-8b0e-f485ae6dc1ec.gif)

**Comment by AndiAJ** [comment]
Not reproducible anymore on the latest Nightly Build 201103 using the following devices:
• Google Pixel 3a (Android 11)
• Huawei Mate 20 Lite (Android 10)
• OnePlus A3 (Android 6.0.1)
