### ISSUE TITLE
Implement a quick access for delete browsing data on exit on the 3 dot menu (and move settings option last)

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/fenix#9547]
### Why/User Benefit/User Problem
As a Fenix user, I want to have a faster way to delete browsing data for a section from the 3 dot menu.
### What/Requirements
A `Turn Off` button is implemented on the Settings line in the 3 dot menu.
This option should also follow the general delete browsing data on quit from settings.
### Acceptance Criteria (how do I know when I’m done?)

![12x](https://user-images.githubusercontent.com/42831109/78026250-f9e96300-7363-11ea-9ff8-b820935c3967.jpg)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-16542)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1809229

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
