### ISSUE TITLE
[Bug] "Top sites" text is displayed partially when opening Fenix 

### ISSUE THREAD

**Issue by sflorean** [mozilla-mobile/fenix#9549]
## Steps to reproduce
1. Open 6-8 tabs.
2. Close Fenix.
3. Open Fenix and check the "Top sites" section.

### Expected behavior
"Top sites" text is also visible along with the sites added.

### Actual behavior
"Top sites" text is displayed partially.

### Device information
* Android device: Nokia 6 (Android 7.1.1).
* Fenix version: Nightly 200331. 

![Screenshot_20200331-154531](https://user-images.githubusercontent.com/58466444/78027888-c9ef8f00-7366-11ea-9cde-35a312b3d2a9.png)

**Comment by softvision-miralobontiu** [comment]
Verified as fixed on the latest Nightly build from 4/15 with Sony Xperia Z5 Premium (Android 7.1.1), and Google Pixel (android 10).
