### ISSUE TITLE
tab appearance not customisable

### ISSUE THREAD

**Issue by test2a** [mozilla-mobile/fenix#955]
firefox android has two options for tabs. 

1. [ ] compact tabs
2. [x] being able to swipe tabs to dismiss.

these two are missing here

**Comment by lime124** [comment]
hello! we are looking at gestures for the MVP here #176 . We're also in the process of revisiting the session/tab view on the home page so I'm going to move this to the icebox for now and when those designs are complete we can revisit and see if this is still an issue. Thanks!

**Comment by lime124** [comment]
removing ux label - this is already grouped with gestures.

**Comment by madb1lly** [comment]
Hi @lime124 why is this related to gestures? It's just about how tabs are arranged in the tab switching view.
Cheers :)

**Comment by lime124** [comment]
sorry i was refering  to the swiping to close portion of the comment 0. the first part of the comment we can revisit to see if it still needs to be addressed once we've done some of the planned iterations on the designs. thanks for asking me to be more clear! :)

**Comment by NotWoods** [comment]
Updated the main comment to reflect that swiping has been implemented.

**Comment by madb1lly** [comment]
In Fennec tabs can also be reordered by long press then moving, but not in Fenix.

**Comment by madb1lly** [comment]
Now I'm using Fenix Nightly as a daily driver I'm finding the absence of compact tabs option quite frustrating.

**Comment by topotropic** [comment]
Thanks for your feedback. Compact tabs are captured in this issue as well https://github.com/mozilla-mobile/fenix/issues/5805. I'm going to close it.
