### ISSUE TITLE
[Bug] The text is overlapping in private mode when allow search suggestion popup is displayed

### ISSUE THREAD

**Issue by ebalazs-sv** [mozilla-mobile/fenix#9550]
## Steps to reproduce
1. Launch Fenix and go to private mode;
2. Go to a page, www.twitter.com;
3. Tap on the URL bar;
4. Observe the behavior;
### Expected behavior
All the page elements are visible.
### Actual behavior
The text "This time search with:" is overlapping the Allow search suggestions popup.

### Notes
[Screenshot](https://drive.google.com/file/d/1-PvniQZ0MzMKhbjYWbZG6UTvYN_ECrWP/view)
### Device information

* Android device: Google Pixel 3 XL (Android 9), Samsung Galaxy S9 (Android 8), Sony Xperia Z5 (Android 7), Nexus 5 (Android 6.0.1).
* Fenix version: Nightly 200331, GV 76, 3/31 (Build #20910606).

As Diana mentioned in https://github.com/mozilla-mobile/fenix/issues/7059#issuecomment-606613018 this is a regression.

**Comment by sv-sdeiac** [comment]
Hi, I can confirm that this issue is not reproducible using the latest version of Firefox Preview Nightly 4/24 #21150607.

Devices:
- LG g7 fit (Android 8.1);
- Samsung Galaxy Note 8 (Android 9);
- Google Pixel (Android 10).
