### ISSUE TITLE
[Bug] No option to enable Autofill in Settings

### ISSUE THREAD

**Issue by maroonmoon13** [mozilla-mobile/fenix#9554]
## Steps to reproduce
Open Settings -> Logins and Passwords
### Expected behavior
Toggle to enable Autofill should be visible as explained here: https://support.mozilla.org/en-US/kb/logins-sync-autofill-saving-firefox-preview

### Actual behavior
No option to enable/disable Autofill visible

I do have lockwise installed, but even after disabling lockwise autofill, the option doesn't show up.

### Device information
* Android device: Pixel 3
* Fenix version: 4.2.0 (build # 20852112)

**Comment by cadeyrn** [comment]
The option was temporarily removed, see #8967 for context.

**Comment by maroonmoon13** [comment]
Thanks. Please close the issue.
