### ISSUE TITLE
[Process] Define engineering review process

### ISSUE THREAD

**Issue by eliserichards** [mozilla-mobile/fenix#9558]
[Engineering team OKRs](https://docs.google.com/document/d/18w_a5nSatAqL6TX6LinKsFY-93yU9u8E8cY8S5uCiiI/edit)

## Purpose
Investigate the current state of engineering reviews in Fenix. Identify pain points and opportunities for improvement, and define a new process to streamline the process moving forward. 

## Acceptance Criteria
- [ ] investigate previous review processes 
   - internal PRs from team members
   - contributor PRs
   - external team members (e.g. AC, softvision, etc)
- [ ] craft a "new" process based on pain points, requirements, and opportunities for improvement
- [ ] present "new" to the team and get feedback
- [ ] iterate on this approach and get feedback after 1-2 sprints (e.g. in retro)

### Process requirements
* Decrease ambiguity in internal and cross-team processes, and allows evolution in the process.
* Including Review
* Has a definition of “done” (testability?)
* Has a definition of success 
* Automation when possible
* Equitable/has roles: who owns engineering reviews?
* Frequency reduces risk of things that otherwise negatively impact the product.
* Work with Performance team: when should performance be involved in reviews?
* Open to evolution (retros)

### Pain points
* ...

### Opportunities for improvement
* ...

**Comment by eliserichards** [comment]
Tiger and I are going to start work on this.

**Comment by liuche** [comment]
Moving this out of the sprint as we get closer to release.
