### ISSUE TITLE
[Bug] Fenix crashes on start

### ISSUE THREAD

**Issue by LittleAngelwings** [mozilla-mobile/fenix#9561]
## Steps to reproduce
install latest nighty-build via GP, then start Fenix 

### Expected behavior

Fenix will start

### Actual behavior

Fenix crashes on startup immediately 

### Device information

* Android device: 
Samsung Galaxy Tab A6 SM-T580 with Android 8.1.0 
Huawei P Smart 2017 Android 9.1.0 
* Fenix version: Nightly 200331 18:01

Log from MatLog:

[2020-03-31-22-47-37.txt](https://github.com/mozilla-mobile/fenix/files/4411576/2020-03-31-22-47-37.txt)

**Comment by grigoryk** [comment]
Thanks for reporting, @LittleAngelwings. I was able to replicate this locally with a "delete data on exit" setting enabled, which adds a "Quit" item to the main three-dot menu. This should be now fixed.

**Comment by LittleAngelwings** [comment]
Thx, confirmed as fixed.
