### ISSUE TITLE
[Bug] “Select tabs” string is cut out in French

### ISSUE THREAD

**Issue by TheoChevalier** [mozilla-mobile/fenix#9565]
## Steps to reproduce

1. Switch language to French
2. Open some tabs
3. Tap on “Save to a collection” button

### Expected behavior

“Select tabs” string is displayed properly

### Actual behavior

String is cut out
Full string: Sélectionner des onglets
![Screenshot_20200331-234300](https://user-images.githubusercontent.com/1294206/78083189-af400900-73ac-11ea-908b-903ba9094a66.png)

### Device information

* Android device: Xperia Z3 Compact
* Fenix version: Nightly 200331

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly Build #21130610 from 4/22`** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)

► Screenshot
![rsz_screenshot_20200422-093425](https://user-images.githubusercontent.com/51314259/79948714-09e4f600-847d-11ea-90bb-3887f19370ad.png)
