### ISSUE TITLE
[Bug] HomeMenu button highlight colour isn't right High Priority items

### ISSUE THREAD

**Issue by grigoryk** [mozilla-mobile/fenix#9566]
STR:
- sign-in to FxA, trigger an account authentication problem (e.g. by changing account password on Firefox Desktop, and then syncing in Fenix)
- observe that home menu will now display a "reconnect to sync" item, but the highlight on the button itself is not really visible (or, visible only at a certain angle)

<del>I've verified that the highlight is being set correctly, but perhaps the background tint colour is too subtle to be visible? I've changed it (`sync_disconnected_background_light_theme`) to `#000000`, and I see that it's being picked up correctly:</del>
(indeed, the colour is there but very subtle!)

<img width="92" alt="Screen Shot 2020-03-31 at 4 45 15 PM" src="https://user-images.githubusercontent.com/465422/78085331-7d5c8180-736f-11ea-8fcb-e85c7c1628f9.png">

<img width="276" alt="Screen Shot 2020-03-31 at 4 45 20 PM" src="https://user-images.githubusercontent.com/465422/78085334-7f264500-736f-11ea-8c6b-943e73c42656.png">

The colour that's set now is `#FFFDE2`, and this is what it looks like:
<img width="116" alt="Screen Shot 2020-03-31 at 4 50 56 PM" src="https://user-images.githubusercontent.com/465422/78085429-d0363900-736f-11ea-80ef-d7730a3ae2fa.png">

<img width="252" alt="Screen Shot 2020-03-31 at 4 51 28 PM" src="https://user-images.githubusercontent.com/465422/78085465-e6dc9000-736f-11ea-9f28-7ce752f3e6ab.png">

**Comment by ekager** [comment]
If I'm understanding correctly you want the yellow background highlight to be stronger/more noticeable for high priority items? 
Colors were defined here: https://github.com/mozilla-mobile/fenix/issues/7504#issuecomment-588580859
CC @AmyYLee / @brampitoyo for feedback

**Comment by grigoryk** [comment]
Yup, otherwise it's not visible in a light theme. According to #7504 this is "to spec", but even in those screenshots it takes a very keen eye to spot that the button is highlighted when in a light theme.

**Comment by ekager** [comment]
Looks like we missed a followup comment here that this yellow overlay and dot should be removed from all themes https://github.com/mozilla-mobile/fenix/issues/7504#issuecomment-593763767

**Comment by grigoryk** [comment]
Not sure how to parse that comment. Is it saying that if there's a high priority item present in the menu, the three-dot menu button should not be highlighted?

**Comment by ekager** [comment]
That's how I am understanding it. cc @brampitoyo for followup on this. Do we still want the menu button highlighted for low priority, ie the What's New blue highlight?

**Comment by grigoryk** [comment]
Afaik, we're not using this highlight functionality anywhere else, right? If we don't want to highlight the three-dot menu, we can remove probably remove most of `BrowserMenuHighlight` from A-C...

**Comment by brampitoyo** [comment]
@ekager @grigoryk No. The menu icon itself doesn’t need to be highlighted in this scenario.

I understand that we use the blue dot when features like Reader Mode is available. However, in this particular sync error situation, we think that users who experience problems are likely to go inside the main menu to figure out what’s wrong, without needing to be prompted or notified.

Of course, when they tap on it, they’ll see the yellow highlight and warning icon. That alone will be enough.

**Comment by grigoryk** [comment]
> However, in this particular sync error situation, we think that users who experience problems are likely to go inside the main menu to figure out what’s wrong, without needing to be prompted or notified.

I'm not sure it'll be obvious to them that something is wrong. Failing to sync isn't immediately visible anywhere in the app.

**Comment by brampitoyo** [comment]
@grigoryk I agree that it won’t be obvious that something is wrong. In fact, almost all sync errors aren’t immediately visible.

Users might notice that:

- Main menu → Share → Send to device – my device isn’t shown
- Main menu → Library → History/Bookmarks – items from another device don’t appear
- Site → Sign in → Autofill – saved logins and passwords from another device aren’t suggested

And when those errors happen, what users might do are as follows:

- Share sheet: tap on “Sign in to Sync” → Reconnect to FxA → Problem solved
- History/Bookmarks: to go to these pages, users must first open the main menu, where they see that an item is highlighted yellow
- Autofill: “Maybe something is wrong with my logins, let me check [opens main menu]”. Users see that an item is highlighted yellow

Our argument: although failing to sync isn’t immediately visible anywhere in the app, when users realise that something isn’t quite right, they will check inside the main menu or find the link to fix it. But it’s entirely possible that sync errors get ignored for a long period of time.

The alternative, of course, is to simply show a yellow notification dot. But we worry that this will overlap with the blue dot and annoy users with too much signals (although you can argue that being annoying is exactly the point of a yellow dot).

In the end, between being verbose and quiet, we picked the latter: rely on users to open the main menu. We can argue that this is too passive, but we’re also hoping that our targets are so easy to reach, that users will open the main menu or the share sheet – for reasons that may or may not be related to sync – to then realise the problem and fix it?

**Comment by brampitoyo** [comment]
Related to #9109

**Comment by BranescuMihai** [comment]
I've just [merged a PR](https://github.com/mozilla-mobile/fenix/pull/9379) for #9109, the menu button shouldn't be highlighted anymore for sync errors

**Comment by ekager** [comment]
Closing for #9109
