### ISSUE TITLE
firefox_preview_v4.2.0_arm.apk.When i install it and i found this is a beta version,it's 4.2.0-beta.3  [Bug]

### ISSUE THREAD

**Issue by liuhqsir** [mozilla-mobile/fenix#9569]

**Comment by yaomtc** [comment]
Yeah something went wrong with that release, same thing happens with the arm64 version.

**Comment by yaomtc** [comment]
This also happened with the latest release on Github, 4.2.1. It identifies as 4.2.1-beta.1 and so will be a separate _Beta_, and will not be an update to Firefox Preview.

**Comment by pihug12** [comment]
FYI, you can get the last APKs here and they seem fine: https://firefox-ci-tc.services.mozilla.com/tasks/index/project.mobile.fenix.v2.production/latest

**Comment by yaomtc** [comment]
@pihug12 Thanks, that works. Since @kbrosnan said it should be fixed, I tried downgrading from 4.3 to 4.2.1 using the Github link, but it didn't work. I haven't tried downgrading Firefox before though, so maybe that's not always possible without breaking something.
