### ISSUE TITLE
[Bug] Enhanced Tracking Protection won't stay on

### ISSUE THREAD

**Issue by ffxsam** [mozilla-mobile/fenix#9570]
## Steps to reproduce
1. Visit any website
2. Enable ETP

### Expected behavior
ETP should remain on

### Actual behavior
ETP turns itself off

### Device information

* Android device: Google Pixel 4
* Fenix version: Nightly 200331 18:01 (Build #20911807) 38.0.20200331130030, 8bba0959d

![ScreenFlow](https://user-images.githubusercontent.com/12532733/78098677-689ae080-73a5-11ea-8466-51b0b760e255.gif)

**Comment by Amejia481** [comment]
@ffxsam thanks for filing this issue. I'm wasn't able to replicate it. Would you mind adding more details to the steps to reproduce? Or a detailed video as the one that you added above will be really appreciated

**Comment by ffxsam** [comment]
I cleared the app's storage on my device and reopened the browser. All is well now!
