### ISSUE TITLE
[Bug] Crash when enable "delete browsing data on quit"

### ISSUE THREAD

**Issue by lindongbin** [mozilla-mobile/fenix#9572]
* Fenix version: 
Nightly 200331 18:01 (Build #20911807)
38.0.20200331130030, 8bba0959d
GV: 76.0a1-20200330094747
AS: 0.55.0

**Comment by sv-sdeiac** [comment]
Hi @lindongbin, thanks for your report.
I tried to reproduce your issue and I can confirm that is reproducible on 3/31 #20910606.
Also, using 4/1 #20920607 build, I was not able to reproduce the crash.

Devices:
- Samsung Galaxy Note 8 (Android 9);
- Xiaomi Mi 8 Lite (Android 9);
- LG g7 fit (Android 8.1).
