### ISSUE TITLE
[Bug] (regression) LeakCanary toggle is broken

### ISSUE THREAD

**Issue by cadeyrn** [mozilla-mobile/fenix#9574]
### Steps to reproduce

0. use a debug build
1. open the settings

### Expected behavior

You can use the LeakCanary toggle.

### Actual behavior

The LeakCanary is broken. It looks like a category now. It's a regression from #6986. /cc @kglazko 

![Screenshot_20200401-082047](https://user-images.githubusercontent.com/1100614/78105597-d8cf5380-73f1-11ea-8ad4-3406222d7736.jpg)

### Device information

* Android device: OnePlus 7T Pro McLaren Edition, OxygenOS 10.0.7 (Android 10)
* Fenix version: master branch revision d9d5de98c9a6cda46199b92c1412739e8f04d8a4

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the **`debug build I've just created`** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)

► Video
![20200403-100012](https://user-images.githubusercontent.com/51314259/78333626-dc4e1080-7592-11ea-91cc-ef1b939c2b33.gif)
