### ISSUE TITLE
[Bug]Problem with toolbar display

### ISSUE THREAD

**Issue by 90du** [mozilla-mobile/fenix#9575]
## Steps to reproduce
Slide up webpage toolbar does not display
![Screenshot_2020_0401_183601](https://user-images.githubusercontent.com/35375370/78127990-b9fbac00-7447-11ea-9f7f-4588419d4df7.png)

### Expected behavior
Slide down to hide, slide up to show！If the toolbar problem cannot be solved for a short time, please set the toolbar to always display
### Actual behavior
After sliding down to hide the toolbar, sometimes sliding up cannot call out the toolbar
### Device information

* Fenix version: ?
Nightly 200401 06:01 (Build #20920608)

**Comment by s-ankur** [comment]
I've also been having the same problem but I don't know how exactly to reproduce it. Basically the dynamic address bar gets stuck and does not reappear no matter how much you slide it up or down. It only reappears a few seconds afterwards

**Comment by sv-sdeiac** [comment]
Hi, I tried to reproduce this issue using the latest version of Firefox Preview Nightly 4/1#20920607 but I wasn't able.
Devices:
- Samsung Galaxy Note 8(Android 9);
- LG g7 fit (Android 8.1).

@90du can you send a video with your problem, maybe some steps that trigger the bug?
I'll wait for your updates, thanks.

**Comment by 90du** [comment]
> 嗨，我尝试使用最新版本的Firefox Preview Nightly 4/1＃20920607重现此问题，但我无法。
> 设备：
> 
> * 三星Galaxy Note 8（Android 9）;
> * LG g7 fit（Android 8.1）。
> 
> @ 90du您可以发送有关您的问题的视频，也许是触发该错误的某些步骤？
> 我会等你的更新，谢谢。

I do n’t know how to reproduce it, but I feel it depends on the speed

**Comment by LittleAngelwings** [comment]
I observed this issue... STR:
Loading this site completely, then scroll to the end. Now scroll up, try to scroll with only one fast fade to the top. Now now toolbar won't appears. The toolbar will appears with some more slow fadings down and up.

**Comment by sv-sdeiac** [comment]
Hi, thank you for your updates, I can confirm that the toolbar is missing sometimes on that page.

### Steps to reproduce:
1. Go to: t.shuqi.com;
2. Fast scrolling up/down multiple times;
3. After the URL remain hidden, try to scroll down slowly.

### Expected result:
The Toolbar is displayed after scrolling down.

### Actual result
The toolbar doesn't react to the scrolling gesture and remains hidden for multiple scrolls.

Devices:
- Google Pixel 3 (Android 10).

#### Notes
- Not reproducible using other pages(Wikipedia, amazon, youtube, eBay, Twitter) 
![20200401_144355](https://user-images.githubusercontent.com/40264165/78134051-2ebeee00-7428-11ea-81bb-9ee3093453f9.gif)

**Comment by LittleAngelwings** [comment]
Now I remember this issue, cause actually the toolbar is completely gone while I'm looking issues for Fenix here on GitHub. No way to bring them back, had gone back and forward and reload pages new. Nothing I do will show the toolbar again. Only I can do, is leaving Fenix via the devices home button or via closing Fenix at the task list. 
BTW: I have activated the new tab tray.
