### ISSUE TITLE
[Bug] UBO stuck on whatever language is set after restart

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#9576]
## Steps to reproduce
Change language
restart Firefox
check UBO
change language 
check UBO
### Expected behavior
UBO changes language
### Actual behavior
UBO stuck in first language 
### Device information

* Android device: Asus Zenfone
* Fenix version: Firefox Nightly

**Comment by Diana-Rus** [comment]
Hi, are you still encountering the issue with the latest Nightly?
@s-ankur - Seems to me, that it's the same issue with #9413  it is only limited to the add-on's section, right?
With the latest nightly you should see that the languages are applied correctly without having to close and reopen browser. As far as i can see only the RTL languages are still affected.

**Comment by AndiAJ** [comment]
Closing in favour of #8729
