### ISSUE TITLE
Extend "Fill link from clipboard" to "replace" existing URLs

### ISSUE THREAD

**Issue by SpitFire-666** [mozilla-mobile/fenix#9584]
### Why/User Benefit/User Problem
- I have copied a URL to clipboard
- I open FF and an existing tab is open
- I decide to use the existing tab to open my URL in (instead of opening a new, blank tab)
- When clicking the existing URL, I have to manually delete, or paste my copied URL over the top

Ideally, when clicking the existing URL, FF would give me the option to "Fill link from clipboard

### Acceptance Criteria (how do I know when I’m done?)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-16571)

**Comment by pavi2410** [comment]
There should also be a clear button next to the URL bar. Currently, the button which is next to the URL bar closes the URL editing.

**Comment by alastor0325** [comment]
FYI, UX already gave [positive feedback](https://github.com/mozilla-mobile/fenix/issues/17109#issuecomment-766516031) on this issue before.

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813925

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
