### ISSUE TITLE
[Bug] Address bar searches internal errors/URLs

### ISSUE THREAD

**Issue by campbellkerr** [mozilla-mobile/fenix#9585]
## Steps to reproduce
Sorry, this may have already been reported - hard to search for.

- Visit www.theage.com.au (for example)
- Visit an invalid address - resulting page title will be "Problem loading page"
- From  now on, when typing "age" into the address bar, "Problem loading page" suggestions will show up, and appear to take precedence over the legitimate The Age website.

### Expected behavior
Only legit pages with "age" in the page title should be shown in address bar suggestions list

### Actual behavior
All my previous, invalid URLs (including my home network ones) that have timed out/been inaccessible ("Problem loading page") are suggested over the legitimate www.theage.com.au

### Device information

* Android device: ?
* Fenix version: 4.2.0

**Comment by kbrosnan** [comment]
dupe #2064
