### ISSUE TITLE
[Bug]Context menu overlays the notification bar

### ISSUE THREAD

**Issue by sv-sdeiac** [mozilla-mobile/fenix#9586]
## Steps to reproduce
1. Open a page with text(Wikipedia.com);
2. Select a word;
3. Zoom-in the page;
4. Scroll down to the page till the context menu overlays the notification bar.

### Expected behavior
The context menu is displayed correctly.

### Actual behavior
The context menu is displayed over the notification bar.

### Device information
Android device:
- Google Pixel 3 (Android 10);
- Xiaomi Mi 8 Lite (Android 9).

Fenix version: Firefox Preview Nightly 4/1 #20920607.

### Notes
- Not reproducible on Samsung Galaxy Note 8 (Android 9) and Lg g7 fit (Android 8.1).
![Screenshot_20200401-154702](https://user-images.githubusercontent.com/40264165/78140554-dfca8600-7432-11ea-9f81-1f683a29eb68.png)

**Comment by softvision-miralobontiu** [comment]
I wasn't able to reproduce this issue on the latest Nightly build from 10/20 using Google Pixel (Android 10), Samsung Galaxy tab S6 (Android 10), or HTC 10 (Android 8).
