### ISSUE TITLE
Navigation bar-Touch target-"Search or enter address" search bar needs to be larger

### ISSUE THREAD

**Issue by Diana-Rus** [mozilla-mobile/fenix#9588]
## Prerequisites:
- Have Google Accessibility Scanner installed.
- Have a clean firefox profile.

### Steps to reproduce
1. Open app and tap on "Start browsing" button from bottom of the page.
2. Tap on the back button of the device.
3. Scan the homescreen.
### Expected behavior
There are no suggestions to make any changes.
### Actual behavior
Navigation bar "Search or enter address" search bar
- org.mozilla.fenix.nightly:id/toolbar_wrapper
This item's height is 40dp. Consider making the height of this touch target 48dp or larger.
### Device information

* Android device: Samsung Galaxy S9 (Android 8)
* Fenix version: Nightly 4/1 (Build #20920607)

Screenshot:
![Screenshot_20200401-161920_Accessibility Scanner](https://user-images.githubusercontent.com/49859863/78144256-0a6b0d80-7438-11ea-98a9-df3aaeccaf60.jpg)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-16575)

**Comment by Diana-Rus** [comment]
Reproducible with Google Pixel 3XL (Android 9) nn Nightly 9/4

**Comment by sflorean** [comment]
Reproducible on Beta 86.0.0-beta.2 - Huawei P40 Lite (Android 11).

**Comment by lobontiumira** [comment]
Reproducible on Beta 88,0,0-beta,3 with Samsung Galaxy Note 8 (Android 9),

**Comment by sflorean** [comment]
This is still reproducible on 92.0.0-beta.6.

**Comment by LaurentiuApahideanSV** [comment]
The issue is still reproducible on 93.0.0-beta.4.

**Comment by lobontiumira** [comment]
This issue still reproduces on Beta 105.0b5 with Samsung Galaxy Note 8 (Android 9).

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1811629

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
