### ISSUE TITLE
Telemetry Address Bar + Search

### ISSUE THREAD

**Issue by bbinto** [mozilla-mobile/fenix#959]
Understand how (often) users perform searches

- As a product owner, I want to know what the most successful search access point is so we can optimize our search story 
- As a product owner, I want to know if people type in more domains or search keyword

### What questions will you answer with this data?
- What’s the most successful search access point (# of search queries), goal is to improve search access points

### Why does Mozilla need to answer these questions? Are there benefits for users? Do we need this information to address product or business requirements?
- Improve search and search counts
- Help users find the information they are searching for quicker

### What probes
- address bar: type in URL vs search keyword
- bottom address bar activity vs. homescreen search bar activity
- do users click on autocomplete
- do users click on search suggestions
- do users copy the URL bar (out of scope, [feature](https://github.com/mozilla-mobile/fenix/issues/1068) not implemented yet)
- do users copy of key word (out of scope, [feature](https://github.com/mozilla-mobile/fenix/issues/1068) not implemented yet)

### Dependencies (Added by PM and Eng)
- Glean SDK Event pings working in Android components

### Acceptance Criteria (Added by PM)
- Event pings can be queried via re:dash
- We are sending telemetry events for the actions listed in the requirements
- We have documented the telemetry
- We have asked a data steward to [review](https://github.com/mozilla/data-review/blob/master/request.md) the telemetry

**Comment by boek** [comment]
Hey @bbinto,

We currently don't have a method to copy the URL from the URL bar, but I created a story #1068
Secondly, what does `do users copy of key word` mean?

**Comment by bbinto** [comment]
Thanks @boek. 

> Secondly, what does do users copy of key word mean?

That'd be similar to copy the URL from the address bar, i.e. if somebody types in a search term / key word, how often do they copy it from the address bar?

Both, since the feature is not implemented yet, should be removed. I'll update the initial field.

**Comment by georgf** [comment]
> ### What probes
> 
>     * address bar: type in URL vs search keyword
> 
>     * bottom address bar activity vs. homescreen search bar activity
> 
>     * do users click on autocomplete
> 
>     * do users click on search suggestions
> 
>     * do users copy the URL bar (out of scope, [feature](https://github.com/mozilla-mobile/fenix/issues/1068) not implemented yet)
> 
>     * do users copy of key word (out of scope, [feature](https://github.com/mozilla-mobile/fenix/issues/1068) not implemented yet)

I think there are two (or more?) themes in here:
1) search counts, broken down by different dimensions
2) other UI actions like copying

For the search counts, i think it would be good to break this out for a spec on how we'll instrument search counts.
I think mconnor or others have requirements here too.

**Comment by georgf** [comment]
I assume for search instrumentation we'd need:
- Something comparable to Firefox Desktops search counts (in Glean these could be labeled counters, sent through the metrics ping).
- Search events, for usage in Amplitude & Redash.

**Comment by boek** [comment]
@georgf What do you mean by search events on your second point?

Also I did look into using `use_counter` to compare search counts over the different search engines, but it wasn't implemented yet in the SDK, Would we also want to add just a generic counter for all search events?

**Comment by georgf** [comment]
I think you already implemented the search events - i'm not sure which exactly are required :)

For other search instrumentation like counts...
On Desktop we have [`SEARCH_COUNTS`](https://telemetry.mozilla.org/probe-dictionary/?search=search_counts&detailView=histogram%2FSEARCH_COUNTS) as the most critical metric.

That is a keyed count histogram, the equivalent in Glean would be a labeled count. We're still backfilling documentation but basically:
- You add `labeled: true` in the [metrics.yaml](https://github.com/mozilla-mobile/android-components/blob/1f8442dbc060de814c292ff928a128b5d08c26df/components/service/glean/metrics.yaml#L191)
- Then use `yourMetric["some string"].add()`.

But this is just assuming we'd use the same approach.
The search team or assigned data scientist might have more current or additional requirements for this though.
Following up with them (mconnor, javaun, emily thompson?) might be good.
