### ISSUE TITLE
[Bug] [a11y]Search widget-Touch target items need to have the correct height and width

### ISSUE THREAD

**Issue by Diana-Rus** [mozilla-mobile/fenix#9590]
## Pre-requisites
- Have Google Accessibility Scanner installed.
- Have Firefox installed

### Steps to reproduce
1. On devices homescreen long tap.
2. From homescreen edit mode choose "Widget" option.
3. Search and select Firefox Preview Nightly widget.
### Expected behavior
There are no suggestions to make any changes.
### Actual behavior
Search widget - Firefox Preview Nightly - Open app/New tab
- org.mozilla.fenix.nightly:id/button_search_widget_new_tab
This item's height is 32dp. Consider making the height of this touch target 48dp or larger.
Note: The width of the touch target overlaps the microphone.

Search widget - Microphone icon
- org.mozilla.fenix.nightly:id/button_search_widget_voice
This item's size is 32dp x 32dp. Consider making this touch target 48dp wide and 48dp high or larger.

### Device information

* Android device: Samsung Galaxy S9 (Android 8)
* Fenix version: Nightly 4/1 (Build #20920607)

**Screenshot:**
**Search widget - Firefox Preview Nightly - Open app/New tab**
![Screenshot_20200401-172128_Accessibility Scanner](https://user-images.githubusercontent.com/49859863/78148662-ce3aab80-743d-11ea-91d1-0215b1d44602.jpg)

**Search widget - Microphone icon**
![Screenshot_20200401-172226_Accessibility Scanner](https://user-images.githubusercontent.com/49859863/78148644-c975f780-743d-11ea-8364-03536eb97615.jpg)

**Comment by asadotzler** [comment]
We should make the touch target fill the vertical space of the widget.

**Comment by sflorean** [comment]
Verified as fixed on Nightly 6/9 with LG G7 FIT (Android 8) and Google Pixel (Android 10).
