### ISSUE TITLE
[Bug] Name Collection-Touch target-The touch target for collection name field needs resizing

### ISSUE THREAD

**Issue by Diana-Rus** [mozilla-mobile/fenix#9593]
## Prerequisites:
- Have Google Accessibility Scanner installed.
### Steps to reproduce
1. Open app and make a search after a site.
2. Go back to homescreen by pressing tabs tray icon.
3. Long tap on the opened tab.
4. Tap on "Save" for the checked tab.
5. Scan the "Name Collection" screen.
### Expected behavior
There are no suggestions to make any changes.
### Actual behavior
Close "Select Tabs" section
- org.mozilla.fenix.nightly:id/name_collection_edittext
This item's height is 46dp. Consider making the height of this touch target 48dp or larger.
Small difference
### Device information

* Android device: Samsung Galaxy S9 (Android 8)
* Fenix version: Nightly 4/1 (Build #20920607)

Screenshot:
![20200401_185819](https://user-images.githubusercontent.com/49859863/78159276-04caf300-744b-11ea-80b2-506bd061fe14.jpg)

**Comment by Diana-Rus** [comment]
Issue still reproduces on the latest implementation for adding a new collection, on Nightly 9/6 with Google Pixel 3XL (Android 9)

**Touch target**
org.mozilla.fenix:id/collection_name
This item's height is 44dp. Consider making the height of this touch target 48dp or larger.

<details closed><summary>Screen</summary>

![Screenshot_20200904-163633](https://user-images.githubusercontent.com/49859863/92245166-9fcd6a80-eecc-11ea-8ee3-51688ec14f4a.png)
</details>

**Comment by softvision-miralobontiu** [comment]
The issue still reproduces on the 3/2 Nightly build with OnePlus 5T (Android 10):

<img src="https://user-images.githubusercontent.com/40694158/109662439-b995f480-7b73-11eb-8fd4-b6ea6d39af53.jpg" width="300" height="550" />

**Comment by AnishaSingh0118** [comment]
Hey, is this issue too hard to begin with ?
I really want to work on this.

**Comment by eliserichards** [comment]
Hi @AnishaSingh0118! I think this would be a great issue to start with. I will assign it to you 👍

**Comment by AnishaSingh0118** [comment]
Thank you for assigning 😊
