### ISSUE TITLE
[Bug] [a11y]Search screen-"Scan" and "Shortcuts" target touch need resizing

### ISSUE THREAD

**Issue by Diana-Rus** [mozilla-mobile/fenix#9595]
## Prerequisites:
- Have Google Accessibility Scanner installed.

### Steps to reproduce
1. Open app and from the homescreen, tap on "Search or enter address".
2. Scan the search screen.
### Expected behavior
There are no suggestions to make any changes.
### Actual behavior
**Search screen - "Scan" button**
- org.mozilla.fenix.nightly:id/search_scan_button
This item's height is 32dp. Consider making the height of this touch target 48dp or larger.

**Search screen - "Shortcuts" button**
- org.mozilla.fenix.nightly:id/search_shortcuts_button
This item's height is 32dp. Consider making the height of this touch target 48dp or larger.
### Device information

* Android device: Samsung Galaxy S9 (Android 8)
* Fenix version: Nightly 4/1 (Build #20920607)

Screenshots
**Search screen - "Scan" button**
![20200401_192130](https://user-images.githubusercontent.com/49859863/78162711-eddacf80-744f-11ea-93f1-e7f8c9f64e38.jpg)

**Search screen - "Shortcuts" button**
![20200401_192108](https://user-images.githubusercontent.com/49859863/78162723-f16e5680-744f-11ea-947f-7a3fa249264f.jpg)

**Comment by asadotzler** [comment]
At a minimum, could we make the touch target fill the vertical space that's currently available in that toolbar area? That would give us a few more pixels of coverage. Even better would be to increase the space some so we could hit the 48dp target.

**Comment by sflorean** [comment]
Tested on the latest Nightly build 6/3 and on an affected build, and here are my findings:
- Nightly: 40 dp
- affected build: 32 dp 
@mcarare this is expected and we could mark as verified?

**Comment by mcarare** [comment]
@sflorean This is expected.
