### ISSUE TITLE
[Logins] Empty password warning colour is wrong

### ISSUE THREAD

**Issue by AmyYLee** [mozilla-mobile/fenix#9596]
Hi, 
The red warning when a user leaves the password field empty is wrong. Here are the correct colours:

Light theme - Red 70 #C50042
Dark theme - Red 40 #FF6A75

![image](https://user-images.githubusercontent.com/5992746/78164956-98370080-7418-11ea-86c3-1d3fa6ff3491.png)

**Comment by codrut-topliceanu** [comment]
Sorry, but aren't these changes already specified in #8546?

**Comment by AmyYLee** [comment]
> Sorry, but aren't these changes already specified in #8546?

@codrut-topliceanu You're right. Closing bug.
