### ISSUE TITLE
Telemetry Default Browser

### ISSUE THREAD

**Issue by bbinto** [mozilla-mobile/fenix#960]
Understand how many users selected Fenix as their default browser

- As a product owner, I want to know how many users selected Fenix as their default browser, so I can track success of the product

### What questions will you answer with this data?
- How many people use Fenix as their default Browser, if this number grows, our main MAU and DAU KPIs will increase

### Why does Mozilla need to answer these questions? Are there benefits for users? Do we need this information to address product or business requirements?
- An increase/decrease will indicate happiness, stickiness and usefulness of the browser

### What probes
- maybe in core ping as part of browser_default: yes/no?

### Acceptance Criteria (Added by PM)
- Pings can be queried via re:dash
- We are sending telemetry events for the actions listed in the requirements
- We have documented the telemetry
- We have asked a data steward to [review](https://github.com/mozilla/data-review/blob/master/request.md) the telemetry

**Comment by georgf** [comment]
> ### What probes
> 
>     * maybe in core ping as part of browser_default: yes/no?

As a product metric, i would put this as a boolean metric into `metrics.yaml`.
This means it will be sent ~daily through the metrics ping, which should be sufficient for the requirements here.

If analysis in Amplitude is needed, adding an event instrumentation would be needed.
