### ISSUE TITLE
KotlinNullPointerException possibly when deleting/redownloading a download

### ISSUE THREAD

**Issue by liuche** [mozilla-mobile/fenix#9601]
## Steps to reproduce
(Not sure) Intermittent when deleting a downloaded file and re-downloading it. See @AaronMT's comment [here](https://github.com/mozilla-mobile/fenix/issues/7303#issuecomment-572705920).

### Expected behavior
Can delete and re-download without crash

### Actual behavior
Crashes as seen in Sentry, this is currently the 2nd top [crash](https://sentry.prod.mozaws.net/operations/fenix/issues/7488883/?query=release:org.mozilla.fenix-4.2.0) in 4.2 (but has shown up before).

### Device information

* Android device: ?
* Fenix version: 4.2 and before

**Comment by liuche** [comment]
@AaronMT if you have more specific STR, please update comment 0! This is just filed from Sentry and your previous comments on #7303

**Comment by liuche** [comment]
Raising for group triage since it's our #3 crash in 4.2.1

**Comment by AaronMT** [comment]
I'm not aware of any STR. The UI test (which is currently disabled) was simply deleting a file programatically.

**Comment by Amejia481** [comment]
We enabled the test some weeks ago. We haven seen any more occurrences. Otherwise please re open it again if need :)
