### ISSUE TITLE
[Bug] first paint is black when switching out of private mode

### ISSUE THREAD

**Issue by AaronMT** [mozilla-mobile/fenix#9602]
While probably better for dark mode, I have noticed that master will first paint a black background. This is happening for me on master (44432d281e822814cb3db74c8ff092144ca0d2b1) on GeckoNightlyDebug on my Pixel 2 (Android 10).

1. Swap to Private Mode
2. Swap out of Private Mode
3. Tap the Wikipedia top-site tile.

See black paint flicker before page loads. This continues to happen for all sites afterwards, and even after on browser restart.

**Edit**: This might be unrelated to PBM as now I'm seeing this everywhere.

**Comment by softvision-miralobontiu** [comment]
@AaronMT can you still reproduce this?
I wasn't able to on Google Pixel (Android 10) on the latest Nightly build from 10/20.
