### ISSUE TITLE
[Bug] Some characters are cut-out in the bookmark panel

### ISSUE THREAD

**Issue by TheoChevalier** [mozilla-mobile/fenix#9604]
## Steps to reproduce

1. Switch language to French
2. Get a profile without any bookmark
3. Open Menu > Bookmarks

The bottom part of some letters is cut out: q, p, g in the string below are not fully displayed.

![Screenshot_20200401-020136](https://user-images.githubusercontent.com/1294206/78187110-c42ca300-7465-11ea-9e08-3ef1878fce0c.png)

### Device information

* Android device: Xperia Z3 Compact
* Fenix version: Nightly 200401

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly Build #20970607 from 4/6`** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)

►Screenshot
![rsz_screenshot_20200406-093412](https://user-images.githubusercontent.com/51314259/78529333-077e6d00-77ea-11ea-98cf-7c94cb0d212c.png)
