### ISSUE TITLE
[Meta] Quick Action Bar

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/fenix#961]
### Why/User Benefit/User Problem

As a user I want easy access to common functionality for using the information I find on the web.

### Acceptance Criteria (Added by PM. For EPM to track when a Meta feature is done)

-UX completed
-User stories completed
-Strings written and approved
-QA completed
-Localization done

### What / Requirements (Added by PM and Eng Manager)

-UX Designs: #182 
-User stories (linked to epic)

**Comment by mheubusch** [comment]
Implementation review: https://docs.google.com/spreadsheets/d/1HvPFPQFtVVN0SDV97Qe6PBrDVhGQgxl8wBLpsXXvCm0/edit?usp=sharing

Engineering - please review the items on this spreadsheet - this is a punchlist showing fit and finish issues blocking feature completeness.

**Comment by vesta0** [comment]
This has been implemented.
