### ISSUE TITLE
[Bug] Stuck content process (?) caused all tabs in Fenix to stop responding

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/fenix#9614]
## Steps to reproduce

Not sure how this happened. 

1. I had https://news.google.com/topics/CAAqBwgKMJy5lwswj-KuAw?hl=en-US&gl=US&ceid=US%3Aenl open
2. Tapped on link https://news.google.com/articles/CAIiEFGzCzezxy-FiOqsbaSw4jUqFwgEKg8IACoHCAowraj2AjC5-iIwqYhb?hl=en-US&gl=US&ceid=US%3Aen

### Expected behavior

No freeze, page loads. 

### Actual behavior

The page stopped responding (appeared to be loading). Decided to switch to another tab to continue browsing. Pages showed up as black (no page content). Waited a while, decided to record a performance profile.

Performance profile: https://perfht.ml/2UUUd19

Captured the profile after the page loaded and Fenix began to respond normally. 

### Device information

* Android device: Pixel 2
* Fenix version: latest nightly from play store.

**Comment by ebalazs-sv** [comment]
I can reproduce this on Nightly 1.0.2015 from 4/10 with Motorola Moto G6 (Android 8) and Google Pixel 3 (Android 10) following the steps:
1. Launch Fenix;
2. Go to www.news.google.com;
3. Scroll down the page and tap on "Read more stories from Headlines";

The page is loaded but not responding. Also when accessing other pages in different tabs, a blank page is displayed.  
Only a clear data from Android settings solves the issue.
[video](https://drive.google.com/open?id=1p90dFJ0Dpu1GH6vW25CbdONYco7aZL1p)

**Comment by ekager** [comment]
Let's retest this and if it's still happening will need a Bugzilla ticket

**Comment by AndiAJ** [comment]
Hi, **still reproducible** on the latest **`Nightly 201218`** using the following devices:
• Google Pixel 3a (Android 11)
• Huawei Mate 20 Lite (Android 10)
• OnePlus A3 (Android 6.0.1)

❌ After opening : https://news.google.com/topics/CAAqBwgKMJy5lwswj-KuAw?hl=en-US&gl=US&ceid=US%3Aenl Fenix stopped responding.
❌  The same happened after tapping the " "Read more stories from Headlines"

**Comment by ekager** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1683347

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
