### ISSUE TITLE
[Bug] Small visual issues with shadows of collections

### ISSUE THREAD

**Issue by theFireProjet** [mozilla-mobile/fenix#9616]
### Prerequesites
- have a collection with more than one website saved

### Steps to reproduce
- expand the collection

### Expected behavior
Shadows at the side of the collection card should be constant.

### Actual behavior
Shadows are darker at multiple small parts where two website boxes are joined together:
![20200402_094055 (2)](https://user-images.githubusercontent.com/61639215/78229236-012d7f80-74d0-11ea-97c6-aba8c65f0fb8.png)

### Device information

* Android device: Samsung Galaxy S9+ (Android 8.0.0)
* Fenix version: 4.2.0

**Comment by partha2000** [comment]
Can I work on this issue? As it is a "good first issue" it would be motivating for me to get started.

**Comment by corneliuze** [comment]
Hi @eliserichards I couldn't replicate the bug on pixel 3 
![Screenshot_1589596718](https://user-images.githubusercontent.com/31808521/82108544-0ca6d400-9727-11ea-996f-cca7eba09340.png)

**Comment by kbrosnan** [comment]
I see them on a Note 9, a Galaxy S6 and your screenshot. Though on hi-resolution devices they are harder to notice, just some slight smudges where the items meet. On the S6 they are quite glaring.

**Comment by corneliuze** [comment]
okay, I think I didn't notice because of the high resolution of the mac screen.
I'll check it out on an handheld device.

**Comment by corneliuze** [comment]
Hi, @kbrosnan after checking through the codebase, the card view background color is consistent across all views I'm not sure if you would mind us checking it together?

**Comment by kbrosnan** [comment]
I'm not the right person to help you. Maybe @sblatz or @mcarare can.

**Comment by corneliuze** [comment]
Thanks, @kbrosnan.
Hi @sblatz  && @mcarare

**Comment by mcarare** [comment]
@corneliuze The problem here is not that the Cardview shadows are of different colors, but the fact that adjacent cards draw their own shadow, resulting in an overdraw and the slight changing of color. Hope this sets you on the right track!

**Comment by corneliuze** [comment]
Yes, It does, Thanks @mcarare

**Comment by corneliuze** [comment]
Hi @kbrosnan  && @mcarare  Forgive I think my eyes aren't capturing this well. I'd love if you can help me take a look at it.
This is a different screenshot after working on the issue, does the issue still persist?

![screenshot](https://user-images.githubusercontent.com/31808521/83183986-aa83a100-a120-11ea-8781-85085d9563ad.png)

**Comment by cadeyrn** [comment]
Yes, the issue is still to see in your screenshot.

**Comment by corneliuze** [comment]
wow, okay I'll go again :)
