### ISSUE TITLE
[Bug][regression] Overflow menu is hidden just for the selected history item

### ISSUE THREAD

**Issue by mcarare** [mozilla-mobile/fenix#9619]
In https://github.com/mozilla-mobile/fenix/issues/2570 was reqested to hide overflow menu for all items, when in select mode.
After https://github.com/mozilla-mobile/fenix/pull/9233 the menu is hidden just for the selected item.

**Comment by shen714** [comment]
Can I take this as my good first issue? And just to confirm, are we trying to hide all the three-dots menus when in selected mode in  history?

**Comment by shen714** [comment]
Hi @mcarare , I just created a [PR](https://github.com/mozilla-mobile/fenix/pull/13148) for this issue. Sorry if I did it wrong but it seems that I'm unbale to add reviewer to it.

**Comment by LaurentiuApahideanSV** [comment]
Verified as fixed on Firefox Preview Nightly 200803 (Build #22161810).
### Devices used:
- Huawei MediaPad M3 lite (Android 7)
- OnePlus 6T (Android 9)
