### ISSUE TITLE
[Bug] The homescreen is briefly visible when going to Settings

### ISSUE THREAD

**Issue by ebalazs-sv** [mozilla-mobile/fenix#9620]
## Steps to reproduce
1. Have the homescreen displayed;
2. Go to the main menu;
3. Tap on Settings;
4. Observe the Settings page;
### Expected behavior
The Settings page is displayed.
### Actual behavior
The homescreen is displayed briefly when going to Settings.
### Notes
[Video](https://drive.google.com/open?id=1r878qyxZJk7TV7Q4qaYt5_GUWyKrGFD8)
This is not reproducible on Nightly migration 200401 (Build #2015731955) and Firefox Preview Nightly 200402 (Build #20930610).
### Device information

* Android device: Pixel 2 (Android 9), Huawei P9 Lite (Android 7), HTC Desire 530 (Android 6.0.1), Samsung Galaxy Tab S6 (Android 9).
* Fenix version: 
Firefox Preview 4.2.0 (Build #20852112) 3/25;
Firefox Preview Beta 75.0.0-beta.3 (Build #20921517) 4/1;
Beta migration 75.0.0-beta.3 (Build #2015732027) 4/1

**Comment by sflorean** [comment]
This is no longer reproducible on latest Nightly 8/1 with the following devices:
- Pixel 2 (Android 9)
- Huawei P9 Lite (Android 7)
- Pixel 3 (Android 11)
- Samsung Galaxy Note10(Android 10)
