### ISSUE TITLE
[Telemetry] CFR message about Enhanced Tracking Protection panel

### ISSUE THREAD

**Issue by AmyYLee** [mozilla-mobile/fenix#9625]
**Description/User Story**

As a UX feature owner, I’d like to measure the effectiveness of CFR messaging in relation to user engagement with the Enhanced Tracking Protection panel in Fenix

**What questions will you answer with this data?**

- How many users tap on the shield icon to open the ETP panel right away after seeing the CFR message
- How many users tap “x” to close the CFR message and not open the ETP panel
- How many users tap on the shield icon to open the ETP panel without seeing the CFR message
- How many users tap “x” to close the CFR message and open the panel after 24hrs or more
- How many users tap on the shield icon to open the ETP panel without seeing the CFR message

**What probes (suggested, if applicable)**

- 1. An event that’s fired when the CFR message is displayed 
- 2. An event for tapping “x” to close CFR message 
- 3. An event for when the shield icon is tapped - I think we already have this (tracking_protection.etp_shield).

**Dependencies**

Accurate data is dependent on this issue being fixed: 
**Contextual Feature Recommender disappears right away while scrolling #7387**

**Acceptance Criteria**
- Event pings can be queried via re:dash
- We are sending telemetry events for the actions listed in the requirements
- We have asked a data steward to [review](https://github.com/mozilla/data-review/blob/master/request.md) the telemetry
- When the above questions are answered

**Comment by AmyYLee** [comment]
@vesta0 for visibility

**Comment by vesta0** [comment]
For dev: please fill out the methodology section [here.](https://docs.google.com/document/d/1x0vtkSsS03XSI8Grq738-Ikh3fmvHwnKFrfsWCA7Z-E/edit#heading=h.54m3agtapa2x)

**Comment by sblatz** [comment]
I am working on making these CFR messages generic (ui components). Would be nice to include telemetry generically in those so we always get it for each message (with some ID to identify which CFR it actually is). Would that work for you @vesta0?

**Comment by vesta0** [comment]
That would be amazing @sblatz 👍

**Comment by vesta0** [comment]
Next step is to create a JIRA request outlining the Dev proposal for DS review.

**Comment by betsymi** [comment]
Would like to add one more request for telemetry to measure when users tap outside the CFR message upon it appearing.

**Comment by sblatz** [comment]
[Jira ticket](https://jira.mozilla.com/browse/DS-762) filed with high (P1) priority.

**Comment by sblatz** [comment]
Marissa approved 😄

**Comment by sblatz** [comment]
## Notes
onboarding.order#.xxx, where xxx matches the other preference telemetry name
Use “onboarding” as the top most naming convention
Onboarding.whats_new_clicked
order# refers to the order on the screen
Events for
Onboarding finished (search or enter address && start browsing)
Onboarding started
Useful to track position in the list

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on both **`Nightly Build 200629 from 6/30`** and **`Fenix 79.0.1-beta.1 from 6/30`** using a Google Pixel 3a (Android 10)

✔️ The enhanced tracking protection contextual hint was displayed 
• **Nightly** Ping d8cf4360-f336-4cf1-80ff-8e1e6449464b
• **Beta** Ping c55839b6-edb9-4d3d-bad2-b1c1540ff65b

 ```
"category": "contextual_hint.tracking_protection",
          "name": "display"

```
✔️ The user tapped outside of the etp contextual hint - 
• **Nightly** Ping 1f6feec1-499a-4c94-ba94-ed1ad5a61809
• **Beta** Ping 0182157a-8bb2-42e2-aac7-68913ccb57bc

```
"events": [
        {
          "category": "contextual_hint.tracking_protection",
          "name": "outside_tap"
```
✔️ The user tapped inside of the ETP contextual hint (which brings up the etp panel for this site) - 
• **Nightly** Ping 46c09f49-e181-4fcd-a8e4-aec037caf0e5
• **Beta** Ping 37fe8035-4b5b-455a-918a-56773655a227

```
 "events": [
        {
          "category": "contextual_hint.tracking_protection",
          "name": "inside_tap"
```
✔️ The shield icon is tapped - 
• **Nightly** Ping 1fba4c85-9f43-4e0f-8095-3ee02759fd11
• **Beta** Ping dd05044f-673e-449b-bfb6-5fd294468782

```
"events": [
        {
          "category": "tracking_protection",
          "name": "etp_shield"
```
✔️ The enhanced tracking protection contextual hint was dismissed by pressing the close button 
• **Nightly** Ping 54e1d23a-837b-4977-b68c-b56876926e16
• **Beta** Ping fa9efbdf-92a5-400d-a539-14a603dccb46


```
events": [
        {
          "category": "contextual_hint.tracking_protection",
          "name": "dismiss"
```

**► Nightly**
[Logcat](https://github.com/mozilla-mobile/fenix/files/4851102/etpn1.txt)
[Glean dashboard](https://debug-ping-preview.firebaseapp.com/pings/aj-t300603)

[Logcat](https://github.com/mozilla-mobile/fenix/files/4851113/etpn2.txt)
[Glean dashboard](https://debug-ping-preview.firebaseapp.com/pings/aj-t300604)

**► Beta**
[Logcat](https://github.com/mozilla-mobile/fenix/files/4851140/etpn3.txt)
[Glean dashboard](https://debug-ping-preview.firebaseapp.com/pings/aj-testMig3006)

[Logcat](https://github.com/mozilla-mobile/fenix/files/4851176/etpn4.txt)
[Glean dashboard](https://debug-ping-preview.firebaseapp.com/pings/aj-testMig30066)
