### ISSUE TITLE
Optimize CollectionCreationView layout

### ISSUE THREAD

**Issue by emalysz** [mozilla-mobile/fenix#9626]
When we try adding a tab to a collection, we initialize the CollectionCreationView, which takes 83% of CollectionCreationFragment.onCreateView. 

I notice that we clone three times during our `init` call. This includes inflating the `component_collection_creation_name_collection,` which can take ~8-10ms on a Pixel2 (GeckoBetaFennecBeta variant). I suspect this may be even larger for G5. 

However, if the user has any collections, we do not immediately need this view. Let's see if we can clone and inflate the first time this view is actually needed, not just creating it everytime in `init`.

**Comment by emalysz** [comment]
The three times this is used is if the user is creating a collection, renaming a collection, or has no collections and attempts to "Save to collection." We can not navigate between these use cases, so I don't see a benefit to storing this as a variable. 

We should instead do this when it is needed, not every time we initialize this view.

**Comment by mcomella** [comment]
We haven't see any movement on this in a while so I'm unassigning and sending it back to triage. Please feel free to change it back if this is in error.

**Comment by mcomella** [comment]
Triage: we think this may be related to startup performance so we prioritized with other startup issues.

**Comment by mcomella** [comment]
Thank you @mcarare !
