### ISSUE TITLE
[Bug] Page refreshes unnecessarily when changing fenix theme

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#9627]
## Steps to reproduce
Open a webpage
go to settings-> customization
Change theme
### Expected behavior
No refresh 
Note: Changing Toolbar position does not refresh
### Actual behavior
Page refreshed unnecessarily
### Device information

* Android device: Asus Zenfone 
* Fenix version: Fenix Nightly

**Comment by ekager** [comment]
The page reloads because if the webpage itself supports light or dark theme, you would need to refresh to see these changes.

**Comment by s-ankur** [comment]
Oh, that makes sense. Closed
