### ISSUE TITLE
[Bug] Firefox Preview English French following the last update 4.2.0

### ISSUE THREAD

**Issue by xpwd-lab** [mozilla-mobile/fenix#9637]
Hello everyone!

![Screenshot_20200402-214055_Firefox Preview](https://user-images.githubusercontent.com/63072894/78294641-fd7b1680-752a-11ea-819a-70526dbdb18f.jpg)
![Screenshot_20200402-214105_Firefox Preview](https://user-images.githubusercontent.com/63072894/78294652-01a73400-752b-11ea-8e3f-4402219638f3.jpg)

Following the last update 4.2.0 of Firefox Preview published on the Google Play Store, I realized that part of the menus were in English, and part in French.

Is it possible to fix this?  Please do.

Thank you for your great work!

**Comment by kbrosnan** [comment]
@Delphine is there anything that needs to be tracked here?

**Comment by xpwd-lab** [comment]
> @Delphine is there anything that needs to be tracked here?

Hello @kbrosman
Unless I made a mistake, Firefox Preview is always in English French in the menus.  In spite of the last updates made.  ,
