### ISSUE TITLE
Add ability to disable all suggestion providers

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#964]
### Why/User Benefit/User Problem
I may not want to expose my clipboard, nor search my history (which tends to be rather crowded). It'd be great if we had a toggle to just disable all (or on a per provider basis) the suggestion providers of AwesomeBar.

### Acceptance Criteria (how do I know when I’m done?)
Users have the ability to toggle on/off which suggestion providers they want to use.

**InVision:** https://mozilla.invisionapp.com/share/M4SBYCLJPQG#/365634921_Settings_-_Search_Alt

**Comment by sblatz** [comment]
_Note: this would be pretty small engineering effort due to the way these are implemented_

**Comment by kbrosnan** [comment]
We have largely done this with the options in the search suggestion settings. Is there any other part that is blocking this @sblatz?

**Comment by sblatz** [comment]
@kbrosnan this is mainly a UX/product decision on if or how we want to do this. It'd be easy to add toggles for each type of suggestion in the search settings menu and allow users to enable as they'd prefer.

**Comment by vesta0** [comment]
I suggest creating a separate toggle for each type of suggestion (history, bookmarks)

We already have a toggle to turn off search provider suggestions.

**Comment by lime124** [comment]
removing the ux label - this is on our radar already as it's part of Q3 plans.

**Comment by apbitner** [comment]
@vesta0 @sblatz InVision link added to AC above, please let me know if you have any feedback.

**Comment by vesta0** [comment]
Thanks @apbitner :)

@jpfaller would you please review/approve the copy?

**Comment by sblatz** [comment]
@apbitner Are we able to add a toggle for hiding clipboard suggestions as well? This was a big reason for the creation of this ticket and was frequently requested by users.

We'll want copy for this too. @jpfaller.

**Comment by apbitner** [comment]
Ah, I was going off of @vesta0 's comment on Jul 2 that mentioned history and bookmarks. Let's add a third toggle then, pending copy.

**Comment by jpfaller** [comment]
Show clipboard suggestions

**Comment by sv-ohorvath** [comment]
Verified on Nightly 9/9. Devices: Google Pixel 3 (Android 9), HTC Desire 820 (Android 6.0.1)
