### ISSUE TITLE
[Bug] Focus not put on tabs list when selecting the tabs button with Talkback

### ISSUE THREAD

**Issue by asadotzler** [mozilla-mobile/fenix#9640]
## Steps to reproduce
Launch Fenix
Open several tabs
Focus the tabs button to the right of the addressbar
Activate the tabs button

### Expected behavior
The last selected tab in the home screen's tab gets focus

### Actual behavior
Focus moves to the top of the browser and a visual focus indicator is added to the last selected tab

### Device information
* Android device: Galaxy S10e
* Fenix version: latest nightly

**Comment by asadotzler** [comment]
This is an accessibility P2. The feature is available and works but is difficult to use because of inconsiderate focus/swipe behavior. This kind of bug prevents Fenix from being a delightful experience for users with disabilities.

**Comment by asadotzler** [comment]
Is this the same as #8588?

**Comment by mcarare** [comment]
Putting this on hold until the new tab tray is finished implementing.

**Comment by darkwing** [comment]
I spoke with Asa about this, he'll review our current implementation when it lands and is enabled by default.

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on both the latest **`Nightly 200617 from 6/17`** and **`Beta 5.2.0-beta.2 from 6/16`** using the following devices:
• Google Pixel 3a (Android 10)
• OnePlus A3 (Android 6.0.1)

► Video
![20200617-164938](https://user-images.githubusercontent.com/51314259/84906999-53d40c00-b0bb-11ea-90d8-eab675fa3467.gif)
