### ISSUE TITLE
Add Chromecast support to media content

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/fenix#9646]
As a user, I want to be able to "cast"/stream a video from my phone to my Chromecast-enabled devices.

This is a current feature for Chrome-based browsers and a feature that existed in Fennec too (albeit buggy).

## Acceptance Criteria

Having an option on video/audio content to be cast to Chromecast devices on my home network.

**Comment by boek** [comment]
Dup of #3068
