### ISSUE TITLE
The issue with switching the search engine while browsing.

### ISSUE THREAD

**Issue by sunidhi-kashyap** [mozilla-mobile/fenix#9650]
**Issue :** 

After selecting a search engine, the user needs to go back to the previous page to switch to another search engine.

![Group 89](https://user-images.githubusercontent.com/42182441/78318319-119e3280-7582-11ea-9ff8-06ce5a27be4e.jpg)

**Why it's an issue :** 

Going back and forth to the same page for switching is frustrating.

**How it can be improved :** 

There can be 2 possible solutions.
1) After selecting a search engine, the list of all the search engine remains there, so the user can switch.

This may solve our problem, but after selecting a search engine, the user may prefer to have as little disturbance as possible to focus on what he's typing. If he's constantly shown the search options, it would defeat the purpose.

2) Clicking the search engine icon triggers the list and then the user can switch between the different search engines.
![Group 95](https://user-images.githubusercontent.com/42182441/78319471-dfda9b00-7584-11ea-9ea5-b692132e1bb8.png)

**Effectiveness of the solution :** 

soln 1 : The user won't be frustrated easily as less clicks will be required to switch.

soln 2 : Will remove the cognitive load from the user, and it will be lesser in compared to solution 1. And also it's quite intuitive to the user.

The ability to switch search engines while browsing is a great feature of Fenix, because displaying different search engines gives the user option to use any search engine, without having to put an extra effort. Plus they won't just settle for a default search engine, which is a great plus here. So, making this experience better, tackling this issue will be effective.

**Comment by ekager** [comment]
you can click on the "Shortcuts" pill in search to reselect a new search engine to use. Closing
