### ISSUE TITLE
[Bug] Intermittent copyBookmarkURLTest androidx.test.espresso.NoMatchingViewException: No views in hierarchy found matching: (with content description text: is "Menu") 

### ISSUE THREAD

**Issue by Archaeopteryx** [mozilla-mobile/fenix#9653]
https://treeherder.mozilla.org/logviewer.html#?job_id=296020928&repo=fenix

androidx.test.espresso.NoMatchingViewException: No views in hierarchy found matching: (with content description text: is "Menu")

View Hierarchy:
+>PopupDecorView{id=-1, visibility=VISIBLE, width=747, height=1428, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params={(981,349)(wrapxwrap) gr=TOP START CENTER DISPLAY_CLIP_VERTICAL sim={state=unchanged} ty=APPLICATION_PANEL fmt=TRANSPARENT wanim=0x7f1400fd surfaceInsets=Rect(45, 45 - 45, 45) (manual)
fl=SPLIT_TOUCH HARDWARE_ACCELERATED FLAG_LAYOUT_ATTACHED_IN_DECOR
pfl=WILL_NOT_REPLACE_ON_RELAUNCH LAYOUT_CHILD_WINDOW_IN_PARENT_FRAME}, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, child-count=1}
|
+->PopupBackgroundView{id=-1, visibility=VISIBLE, width=747, height=1428, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.FrameLayout$LayoutParams@3cdff41, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, child-count=1}
|
+-->CardView{id=-1, visibility=VISIBLE, width=747, height=1428, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.FrameLayout$LayoutParams@fc1ace6, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, child-count=1}
|
+--->RecyclerView{id=2131362491, res-name=mozac_browser_menu_recyclerView, visibility=VISIBLE, width=689, height=1348, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=true, is-layout-requested=false, is-selected=false, layout-params=android.widget.FrameLayout$LayoutParams@808e227, tag=null, root-is-layout-requested=false, has-input-connection=false, x=29.0, y=40.0, child-count=12}
|
+---->LinearLayout{id=-1, visibility=VISIBLE, width=689, height=132, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=true, is-enabled=true, is-focused=false, is-focusable=true, is-layout-requested=false, is-selected=false, layout-params=androidx.recyclerview.widget.RecyclerView$LayoutParams@1da5cd4, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, child-count=2}
|
+----->AppCompatImageView{id=2131362364, res-name=image, visibility=VISIBLE, width=66, height=66, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@23a4e7d, tag=null, root-is-layout-requested=false, has-input-connection=false, x=44.0, y=33.0}
|
+----->AppCompatTextView{id=2131362823, res-name=text, visibility=VISIBLE, width=244, height=59, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@86bb172, tag=null, root-is-layout-requested=false, has-input-connection=false, x=110.0, y=36.0, text=Library, input-type=0, ime-target=false, has-links=false}
|
+---->LinearLayout{id=-1, visibility=VISIBLE, width=689, height=132, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=true, is-enabled=true, is-focused=false, is-focusable=true, is-layout-requested=false, is-selected=false, layout-params=androidx.recyclerview.widget.RecyclerView$LayoutParams@61779c3, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=132.0, child-count=2}
|
+----->AppCompatImageView{id=2131362364, res-name=image, visibility=VISIBLE, width=66, height=66, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@eea7240, tag=null, root-is-layout-requested=false, has-input-connection=false, x=44.0, y=33.0}
|
+----->AppCompatTextView{id=2131362823, res-name=text, visibility=VISIBLE, width=273, height=59, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@6225579, tag=null, root-is-layout-requested=false, has-input-connection=false, x=110.0, y=36.0, text=Add-ons, input-type=0, ime-target=false, has-links=false}
|
+---->ConstraintLayout{id=-1, visibility=VISIBLE, width=689, height=132, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=true, is-enabled=true, is-focused=false, is-focusable=true, is-layout-requested=false, is-selected=false, layout-params=androidx.recyclerview.widget.RecyclerView$LayoutParams@5e9d035, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=264.0, child-count=5}
|
+----->AppCompatImageView{id=2131362364, res-name=image, visibility=VISIBLE, width=66, height=66, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=androidx.constraintlayout.widget.ConstraintLayout$LayoutParams@ffbfcca, tag=null, root-is-layout-requested=false, has-input-connection=false, x=44.0, y=33.0}
|
+----->AppCompatImageView{id=2131362562, res-name=notification_dot, visibility=GONE, width=0, height=0, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=true, is-selected=false, layout-params=androidx.constraintlayout.widget.ConstraintLayout$LayoutParams@38c5e3b, tag=null, root-is-layout-requested=false, has-input-connection=false, x=11.025001, y=-11.025001}
|
+----->AppCompatTextView{id=2131362823, res-name=text, visibility=VISIBLE, width=270, height=59, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=androidx.constraintlayout.widget.ConstraintLayout$LayoutParams@41c4958, tag=null, root-is-layout-requested=false, has-input-connection=false, x=110.0, y=37.0, text=Settings, input-type=0, ime-target=false, has-links=false}
|
+----->AppCompatTextView{id=2131362337, res-name=highlight_text, visibility=INVISIBLE, width=270, height=59, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=androidx.constraintlayout.widget.ConstraintLayout$LayoutParams@743ab1, tag=null, root-is-layout-requested=false, has-input-connection=false, x=110.0, y=37.0, text=Settings, input-type=0, ime-target=false, has-links=false}
|
+----->AppCompatImageView{id=2131362266, res-name=end_image, visibility=GONE, width=0, height=0, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=true, is-selected=false, layout-params=androidx.constraintlayout.widget.ConstraintLayout$LayoutParams@1451b96, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0}
|
+---->View{id=-1, visibility=VISIBLE, width=689, height=3, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=androidx.recyclerview.widget.RecyclerView$LayoutParams@4d8a317, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=396.0}
|
+---->LinearLayout{id=-1, visibility=VISIBLE, width=689, height=132, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=true, is-enabled=true, is-focused=false, is-focusable=true, is-layout-requested=false, is-selected=false, layout-params=androidx.recyclerview.widget.RecyclerView$LayoutParams@cb8a304, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=399.0, child-count=2}
|
+----->AppCompatImageView{id=2131362364, res-name=image, visibility=VISIBLE, width=66, height=66, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@560d0ed, tag=null, root-is-layout-requested=false, has-input-connection=false, x=44.0, y=33.0}
|
+----->AppCompatTextView{id=2131362823, res-name=text, visibility=VISIBLE, width=437, height=59, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@e2f5b22, tag=null, root-is-layout-requested=false, has-input-connection=false, x=110.0, y=36.0, text=Report site issue, input-type=0, ime-target=false, has-links=false}
|
+---->LinearLayout{id=-1, visibility=VISIBLE, width=689, height=132, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=true, is-enabled=true, is-focused=false, is-focusable=true, is-layout-requested=false, is-selected=false, layout-params=androidx.recyclerview.widget.RecyclerView$LayoutParams@63a59b3, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=531.0, child-count=2}
|
+----->AppCompatImageView{id=2131362364, res-name=image, visibility=VISIBLE, width=66, height=66, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@19eeb70, tag=null, root-is-layout-requested=false, has-input-connection=false, x=44.0, y=33.0}
|
+----->AppCompatTextView{id=2131362823, res-name=text, visibility=VISIBLE, width=348, height=59, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@5068ee9, tag=null, root-is-layout-requested=false, has-input-connection=false, x=110.0, y=36.0, text=Find in page, input-type=0, ime-target=false, has-links=false}
|
+---->LinearLayout{id=-1, visibility=VISIBLE, width=689, height=132, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=true, is-enabled=true, is-focused=false, is-focusable=true, is-layout-requested=false, is-selected=false, layout-params=androidx.recyclerview.widget.RecyclerView$LayoutParams@48c076e, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=663.0, child-count=2}
|
+----->AppCompatImageView{id=2131362364, res-name=image, visibility=VISIBLE, width=66, height=66, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@6f6de0f, tag=null, root-is-layout-requested=false, has-input-connection=false, x=44.0, y=33.0}
|
+----->AppCompatTextView{id=2131362823, res-name=text, visibility=VISIBLE, width=419, height=59, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@d5f4e9c, tag=null, root-is-layout-requested=false, has-input-connection=false, x=110.0, y=36.0, text=Add to top sites, input-type=0, ime-target=false, has-links=false}
|
+---->ConstraintLayout{id=-1, visibility=VISIBLE, width=689, height=132, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=true, is-enabled=true, is-focused=false, is-focusable=true, is-layout-requested=false, is-selected=false, layout-params=androidx.recyclerview.widget.RecyclerView$LayoutParams@160b888, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=795.0, child-count=5}
|
+----->AppCompatImageView{id=2131362364, res-name=image, visibility=VISIBLE, width=66, height=66, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=androidx.constraintlayout.widget.ConstraintLayout$LayoutParams@f983221, tag=null, root-is-layout-requested=false, has-input-connection=false, x=44.0, y=33.0}
|
+----->AppCompatImageView{id=2131362562, res-name=notification_dot, visibility=GONE, width=0, height=0, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=true, is-selected=false, layout-params=androidx.constraintlayout.widget.ConstraintLayout$LayoutParams@9999646, tag=null, root-is-layout-requested=false, has-input-connection=false, x=11.025001, y=-11.025001}
|
+----->AppCompatTextView{id=2131362823, res-name=text, visibility=VISIBLE, width=510, height=59, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=androidx.constraintlayout.widget.ConstraintLayout$LayoutParams@2528007, tag=null, root-is-layout-requested=false, has-input-connection=false, x=110.0, y=37.0, text=Add to Home screen, input-type=0, ime-target=false, has-links=false}
|
+----->AppCompatTextView{id=2131362337, res-name=highlight_text, visibility=INVISIBLE, width=229, height=59, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=androidx.constraintlayout.widget.ConstraintLayout$LayoutParams@c8cd534, tag=null, root-is-layout-requested=false, has-input-connection=false, x=110.0, y=37.0, text=Install, input-type=0, ime-target=false, has-links=false}
|
+----->AppCompatImageView{id=2131362266, res-name=end_image, visibility=GONE, width=0, height=0, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=true, is-selected=false, layout-params=androidx.constraintlayout.widget.ConstraintLayout$LayoutParams@b24cf5d, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0}
|
+---->LinearLayout{id=-1, visibility=VISIBLE, width=689, height=132, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=true, is-enabled=true, is-focused=false, is-focusable=true, is-layout-requested=false, is-selected=false, layout-params=androidx.recyclerview.widget.RecyclerView$LayoutParams@4c8d0d2, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=927.0, child-count=2}
|
+----->AppCompatImageView{id=2131362364, res-name=image, visibility=VISIBLE, width=66, height=66, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@d8d15a3, tag=null, root-is-layout-requested=false, has-input-connection=false, x=44.0, y=33.0}
|
+----->AppCompatTextView{id=2131362823, res-name=text, visibility=VISIBLE, width=455, height=59, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@bc10a0, tag=null, root-is-layout-requested=false, has-input-connection=false, x=110.0, y=36.0, text=Save to collection, input-type=0, ime-target=false, has-links=false}
|
+---->LinearLayout{id=-1, visibility=VISIBLE, width=689, height=132, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=true, is-enabled=true, is-focused=false, is-focusable=true, is-layout-requested=false, is-selected=false, layout-params=androidx.recyclerview.widget.RecyclerView$LayoutParams@8e40459, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=1059.0, child-count=2}
|
+----->AppCompatImageView{id=2131362364, res-name=image, visibility=VISIBLE, width=66, height=66, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@83f281e, tag=null, root-is-layout-requested=false, has-input-connection=false, x=44.0, y=33.0}
|
+----->SwitchCompat{id=2131362805, res-name=switch_widget, visibility=VISIBLE, width=535, height=132, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=true, is-enabled=true, is-focused=false, is-focusable=true, is-layout-requested=false, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@65168ff, tag=null, root-is-layout-requested=false, has-input-connection=false, x=110.0, y=0.0, text=Desktop site, input-type=0, ime-target=false, has-links=false, is-checked=false}
|
+---->View{id=-1, visibility=VISIBLE, width=689, height=3, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=androidx.recyclerview.widget.RecyclerView$LayoutParams@2e196cc, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=1191.0}
|
+---->LinearLayout{id=-1, visibility=VISIBLE, width=689, height=154, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=androidx.recyclerview.widget.RecyclerView$LayoutParams@3c78d15, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=1194.0, child-count=4}
|
+----->AppCompatImageButton{id=-1, desc=Bookmark, visibility=VISIBLE, width=172, height=66, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=true, is-enabled=true, is-focused=false, is-focusable=true, is-layout-requested=false, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@c31a82a, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=44.0}
|
+----->AppCompatImageButton{id=-1, desc=Share, visibility=VISIBLE, width=172, height=66, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=true, is-enabled=true, is-focused=false, is-focusable=true, is-layout-requested=false, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@cdd961b, tag=null, root-is-layout-requested=false, has-input-connection=false, x=172.0, y=44.0}
|
+----->AppCompatImageButton{id=-1, desc=Forward, visibility=VISIBLE, width=172, height=66, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=true, is-enabled=false, is-focused=false, is-focusable=true, is-layout-requested=false, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@1f753b8, tag=null, root-is-layout-requested=false, has-input-connection=false, x=344.0, y=44.0}
|
+----->AppCompatImageButton{id=-1, desc=Refresh, visibility=VISIBLE, width=173, height=66, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=true, is-enabled=true, is-focused=false, is-focusable=true, is-layout-requested=false, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@a20e591, tag=null, root-is-layout-requested=false, has-input-connection=false, x=516.0, y=44.0}
|
at dalvik.system.VMStack.getThreadStackTrace(Native Method)
at java.lang.Thread.getStackTrace(Thread.java:1538)
at androidx.test.espresso.base.DefaultFailureHandler.getUserFriendlyError(DefaultFailureHandler.java:16)
at androidx.test.espresso.base.DefaultFailureHandler.handle(DefaultFailureHandler.java:36)
at androidx.test.espresso.ViewInteraction.waitForAndHandleInteractionResults(ViewInteraction.java:106)
at androidx.test.espresso.ViewInteraction.desugaredPerform(ViewInteraction.java:43)
at androidx.test.espresso.ViewInteraction.perform(ViewInteraction.java:94)
at org.mozilla.fenix.ui.robots.BrowserRobot$Transition.openThreeDotMenu(BrowserRobot.kt:331)
at org.mozilla.fenix.ui.BookmarksTest.copyBookmarkURLTest(BookmarksTest.kt:152)
at java.lang.reflect.Method.invoke(Native Method)
at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
at androidx.test.internal.runner.junit4.statement.RunBefores.evaluate(RunBefores.java:80)
at androidx.test.internal.runner.junit4.statement.RunAfters.evaluate(RunAfters.java:61)
at androidx.test.rule.ActivityTestRule$ActivityStatement.evaluate(ActivityTestRule.java:531)
at org.junit.rules.RunRules.evaluate(RunRules.java:20)
at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.junit.runners.Suite.runChild(Suite.java:128)
at org.junit.runners.Suite.runChild(Suite.java:27)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
at androidx.test.internal.runner.TestExecutor.execute(TestExecutor.java:56)
at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:395)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2145)

**Comment by sv-ohorvath** [comment]
I think this was fixed with https://github.com/mozilla-mobile/fenix/pull/10842
