### ISSUE TITLE
Preserve back stack history when "opening in fenix" from custom tab

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#966]
Per [discussion here](https://github.com/mozilla-mobile/fenix/pull/944#discussion_r264376285), we should simply set the customtabconfig to null and select the session [here](https://github.com/mozilla-mobile/fenix/pull/944/files#diff-be67937c9ab008d3e24460f813cc9b30R295).

Unfortunately when I tried to implement this it led to the [display already acquired crash](https://github.com/mozilla-mobile/fenix/issues/897). Once this bug is fixed we can implement this better solution.

**Comment by sblatz** [comment]
@vesta0 can you clarify what UX feedback are you wanting on this ticket?

**Comment by vesta0** [comment]
@sblatz @lime124 there is an example [here](https://github.com/mozilla-mobile/reference-browser/issues/69) from Firefox iOS of how this may look like. I will leave it to UX to decide.

**Comment by AmyYLee** [comment]
@sblatz @vesta0 This is the android version https://github.com/mozilla-mobile/android-components/issues/1275 Is this something that requires styling for Fenix? or are we using an android component? Do you need UX specs for this?

**Comment by sblatz** [comment]
I don't believe we actually need UX on this ticket. This ticket, as I filed, was to address this concern:
## STR

1. Open custom tab ('google.com')
2. Click a link (search 'hello')
3. Open in Fenix
4. Press back button

## Expected
Can navigate to back to 'google.com'

## Actual
Have no back stack history to navigate

**Comment by vesta0** [comment]
@AmyYLee I would like to build UI for this (similar to Fennec), we do need specs, and the work will be done in Android Components. However, for MVP we can go skip the UI and just preserve the back stack history as @sblatz mentioned. @lime124 can we open a UX issue for the post-MVP UX/UI work?

**Comment by sblatz** [comment]
UX ticket for post mvp work: https://github.com/mozilla-mobile/fenix/issues/2358

**Comment by ekager** [comment]
Hi @pocmo following up on your comment here:
https://github.com/mozilla-mobile/fenix/pull/944/files#r264376285
I'm still seeing a `java.lang.IllegalStateException: Display already acquired` crash when trying to view the custom tab, and wondering if you have any ideas. Do we need to release the engine? Can Fenix even do that? 

This is what I just tried:

```
                val intent = Intent(context, IntentReceiverActivity::class.java)
                intent.action = Intent.ACTION_VIEW
                getSessionById()?.customTabConfig = null
                getSessionById()?.let {
                    requireComponents.core.sessionManager.select(it)
                }
                startActivity(intent)
```

**Comment by sv-ohorvath** [comment]
Verified pressing back on a page sent from c.t. to Fenix goes through the links opened previously in custom tabs. build: 5/27
