### ISSUE TITLE
[Bug] The account name is bold in the settings section 

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/fenix#9662]
## Steps to reproduce
1. Launch Fenix.
2. Login with valid credentials.
3. Observe the account name.
### Expected behavior
The account name should be like the other sub-categories from each section in settings.
### Actual behavior
The account name is bold in the settings section after logging in
### Device information

* Android device: **Google Pixel 4 XL (10).**
* Fenix version: Nightly **4/3.**

![Screenshot_20200403-135633](https://user-images.githubusercontent.com/42831109/78355206-0238dc80-75b6-11ea-801e-9d0340dad603.png)

**Comment by mcarare** [comment]
@AmyYLee is account name supposed to use Metropolis? Looking at the specs I do not see that it should , but wanted to double check with you. TY!

**Comment by AmyYLee** [comment]
> @AmyYLee is account name supposed to use Metropolis? Looking at the specs I do not see that it should , but wanted to double check with you. TY!

Hi, no the account name shouldn't be in Metropolis. Can you update it to Inter UI? Thanks for bringing this to my attention.

**Comment by softvision-miralobontiu** [comment]
This issue no longer reproduces on the latest Nightly build from 10/21.
I'll close it.
