### ISSUE TITLE
[Bug] "What's New" onboarding card header is truncated

### ISSUE THREAD

**Issue by TheoChevalier** [mozilla-mobile/fenix#9663]
## Steps to reproduce

1. Switch to French
2. Get an app update on the Beta channel

### Expected behavior

The header wraps in multiple lines, fully displaying “Découvrez les nouveautés”

### Actual behavior

The header is truncated, only “Découvrez les” is visible

![Screenshot_20200403-021413](https://user-images.githubusercontent.com/1294206/78355680-04933a80-75a6-11ea-963c-4cc1ac12d187.jpeg)

### Device information

* Android device: Sony XZ2 compact
* Fenix version: latest Beta from the Play Store

**Comment by mcarare** [comment]
I cannot reproduce this.

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly Build #20970607 from 4/6`** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)

►Screenshot
![rsz_screenshot_20200406-092727](https://user-images.githubusercontent.com/51314259/78528994-5a0b5980-77e9-11ea-95b0-26792e6f7ab2.png)
