### ISSUE TITLE
[Bug]Can't log in to this forum

### ISSUE THREAD

**Issue by 90du** [mozilla-mobile/fenix#9668]
## Steps to reproduce
Did not log in to the forum after clicking login
bbs.deepin.org
### Expected behavior
Login to the forum

### Device information
* Fenix version: Nightly 200403 06:01 (Build #20940610)
* Device:

**Comment by abodea** [comment]
Thank you for this report @90du, did you tried to log in on any other forum?
Can you please specify your device and android version?

**Comment by 90du** [comment]
> 感谢您的@ 90du报告，您是否尝试过登录其他论坛？
> 您能指定您的设备和Android版本吗？

I didn't pay attention to other websites, but this website can log in normally with chrome, and there are problems with the password saving prompt.
Phone model v1818A 
android 8.1.0

**Comment by ekager** [comment]
Hi @90du would you mind checking if you're still seeing this?
