### ISSUE TITLE
[Bug] Not Receiving Leanplum Push Notifications in Preview

### ISSUE THREAD

**Issue by cbonacuse** [mozilla-mobile/fenix#9669]
## Steps to reproduce
- Log into [Leanplum Preview app](https://www.leanplum.com/dashboard#/4828751897952256/messaging). 
- Create push notification and target individual test device 
- Send push notification and wait to receive it

### Expected behavior
Push token is automatically created and notification is received within ~5 minutes to test device.

### Actual behavior
Push tokens are intermittently not being assigned (or delayed in being assigned) resulting in messages not being sent.

I had previously ran into this issue of not receiving a push with my device ID (38dd9ddc-03b6-4f40-87f0-9fb6d9d8ae69) and had opened a Leanplum support ticket. This was their response:

> The targeted device does not have a push token, which causes the system not to even attempt sending the message.
> The device is Android, so it should acquire a push token at the first launch of the app, if it is not happening, it means that the notifications for the app are explicitly disabled.
> Could you verify if the notifications are on for the app?

Notifications were on and as soon as support sent another notification to my device, a push token was created resulting in a message being received. They did not do anything differently but rather said there might be a delay in assigning.

### Device information
**Liza's Device**
1. Device ID: 3b647651-f55d-491b-b51d-dffc8b2becad
2. Device type: Android
App version: 3.2.1
OS version: OS 9
3. Campaign URL that you sent a test from: https://www.leanplum.com/dashboard2/4828751897952256/composer/893775026/summary
4. Outcome : I did not receive it.

**Isa's Device 1**
1. Device ID: 81158023-f118-42a9-bb87-fa8a1c2f9960
2. Device type, app version, OS version: Google Pixel 3, 4.0.0, Android OS 10
3. Campaign URL that you sent a test from:
March 26th: https://www.leanplum.com/dashboard2/4828751897952256/composer/881885001/summary
Today: https://www.leanplum.com/dashboard2/4828751897952256/composer/891795223/summary
4. Outcome (did you receive it?): No for all instances
Weird detail: on LP, it says my app version is 4.0.0 and on my phone, it says 4.1.0

**Isa's Device 2**
1. Device ID: 79411120-b1ea-4565-9e7a-70081adfff20
2. Device type, app version, OS version: Motorola Moto G (5S) Plus, 4.0.0, Android OS 7.1.1
3. Campaign URL that you sent a test from:
March 26th: https://www.leanplum.com/dashboard2/4828751897952256/composer/881885001/summary
Today: https://www.leanplum.com/dashboard2/4828751897952256/composer/891795223/summary
4. Outcome (did you receive it?): Yes on both
Same weird thing here, but it says 4.2.0 this time.

**Comment by cbonacuse** [comment]
@lwa-moz & @st3fan for visibility

**Comment by st3fan** [comment]
When LP support says _it should acquire a push token_ - that is something the SDK does when we initialize it. And we do that every time the app (cold) starts.

I think what we are seeing has more to do with the way we test. I definitely noticed that after uninstalling/reinstalling a test device, Leanplum needs some time to refresh the token. But for me this has always resolved itself after a little bit of time.

I'm not sure if there is anything in the app that we can do here. We are setting things up according to the documentation.

**Comment by cbonacuse** [comment]
@st3fan this is the only app we have experienced this issue with, and both 3b647651-f55d-491b-b51d-dffc8b2becad and 81158023-f118-42a9-bb87-fa8a1c2f9960 still do not have push tokens created even after the messages were sent hours ago. Both apps were installed weeks ago in March.

**Comment by st3fan** [comment]
I wonder if they were installed in the period where we had the incorrect Google API keys configured for Preview.

I just installed Firefox Preview, found myself in Leanplum, registered as a test device, and was able to send myself a notification.

**Comment by st3fan** [comment]
Device `3b647651-f55d-491b-b51d-dffc8b2becad` is running Firefox Preview 3.2.1, which definitely did not include Leanplum push support. 

Device `81158023-f118-42a9-bb87-fa8a1c2f9960` is on 4.1.0 - not entirely clear what the status of LP was in that version.

Would you mind updating them both to the latest release (4.2.0 or 4.2.1 tomorrow) and try again with those devices?

**Comment by kbrosnan** [comment]
Closing as there does not seem to be a bug here. Reopen or file a new one if needed.

**Comment by cbonacuse** [comment]
Thanks @kbrosnan & @st3fan for your help. We were able to all receive notifications yesterday.
