### ISSUE TITLE
Add the ability to create folders for the top sites

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/fenix#9674]
### Why/User Benefit/User Problem
As a Fenix user, I want to be able to create a folder with more top sites to save space
### What/Requirements
Implement a way to create folders with the top sites.
### Acceptance Criteria (how do I know when I’m done?)

![20200403-181231](https://user-images.githubusercontent.com/42831109/78377321-22799300-75d8-11ea-9cf5-7d323e6248cb.gif)

**Comment by vesta0** [comment]
Thanks @abodea although this level of advanced top site management seems redundant as it duplicates bookmark management. Perhaps we want to consider that if we decide to make changes to bookmarks in the future.
