### ISSUE TITLE
Add the ability to move the top sites 

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/fenix#9676]
### Why/User Benefit/User Problem
As a Fenix user, I want to be able to move the position of the top sites.
### What/Requirements
Implement a way to move the top sites.
### Acceptance Criteria (how do I know when I’m done?)

![20200403-181231](https://user-images.githubusercontent.com/42831109/78377321-22799300-75d8-11ea-9cf5-7d323e6248cb.gif)

**Comment by kbrosnan** [comment]
dupe #8305
