### ISSUE TITLE
Add a card on the onboarding screen for the default search engine selection

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/fenix#9681]
### Why/User Benefit/User Problem
As a Fenix user, I want to be able to pick my search engine at first launch on the onboarding screen.
### What/Requirements
Add a card on the onboarding screen for the default search engine selection
### Acceptance Criteria (how do I know when I’m done?)

![engine](https://user-images.githubusercontent.com/42831109/78381532-2c05f980-75de-11ea-8473-a38f6e8fd336.jpg)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-16637)

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807572

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
