### ISSUE TITLE
[Bug] Shortcuts and allow search suggestions message overlap in PBM

### ISSUE THREAD

**Issue by topotropic** [mozilla-mobile/fenix#9690]
## Steps to reproduce
Search in PBM so that you get the "Allow search suggestions" dialog.

### Expected behavior
"This time search with:" is below the "Allow search suggestions" dialog.

### Actual behavior
"This time search with:" overlaps with  "Allow search suggestions" dialog.

![Screenshot (Apr 3, 2020 9:26:17 PM)](https://user-images.githubusercontent.com/353960/78397872-4f3aa400-75f2-11ea-8d54-6efa7d722fe8.png)

### Device information

* Android device: ?
* Fenix version: ?

**Comment by sflorean** [comment]
dupe of #9550
