### ISSUE TITLE
[Bug]- When the user switches to the desktop site, the page doesn't fit on the screen of the mobile.

### ISSUE THREAD

**Issue by adi-1999** [mozilla-mobile/fenix#9694]
## Steps to reproduce
The following are the steps:-
1) Open a new tab and search up any web page.
2) In the kebab menu, turn on the "Desktop site" option.

### Expected behavior
The website should size accordingly to the screen of the mobile.(For eg, in google chrome-picture below)

<img src="https://user-images.githubusercontent.com/58343952/78403025-46a99400-7619-11ea-80be-55270caa135f.jpeg" alt="WhatsApp Image 2020-04-04 at 2 08 13 AM (1)" Width="300">

### Actual behavior
The website either maximizes on a random point or information is cut out from the page and the user has to scroll left or right to view it.(It does not replicate what the website looks on desktop).

<img src="https://user-images.githubusercontent.com/58343952/78403067-5fb24500-7619-11ea-8cca-e582b853fa7a.jpeg" alt="WhatsApp Image 2020-04-04 at 2 08 13 AM (2)" Width= "300">
 

### Device information

* Android device: Realme X2 (Android 9)
* Fenix version: Firefox Preview: 4.2.0 (Build #20852112) 37.0.0, 3536bce84 
 GV: 75.0-20200322132212 AS: 0.55.0

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-16648)

**Comment by sflorean** [comment]
I was able to reproduce on Nightly 04/08 with Nokia 6 (Android 7.1.1) and Xiaomi Redmi Note 8T (Android 9).

**Comment by Maxnor** [comment]
I'm experiencing the same on 4.2.1 (Build #20941431) and Nightly 200408 06:01 (Build #20990610). 
Samsung Note 10+ with Android 10.

**Comment by ekager** [comment]
Reopening because wrong issue was linked in a PR

**Comment by corneliuze** [comment]
yeah, that was a mistake.

**Comment by sflorean** [comment]
This is still reproducible on latest Nightly build with Pixel 3 (Android 11).

**Comment by SoftVision-LorandJanos** [comment]
This issue is still reproducible on the latest Nightly (2021-11-25).
Device used: Xiaomi Mi11 (Android 11).

**Comment by SoftVision-LorandJanos** [comment]
This issue is still reproducible on the latest Nightly 109.0a1 (2022-11-28) build.
Device used: Oppo Find X5 (Android 12).

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807155

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
