### ISSUE TITLE
[Bug] Invoking Fenix as default assist app doesn't focus on the search bar

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/fenix#9695]
## Steps to reproduce
1. Set Fenix as the default Assist App (Settings -> Apps -> Default apps).
2. Invoke the assistant.

### Expected behavior
- Fenix opens to the UI to focus on the search bar with the keyboard open.

### Actual behavior
- Fenix opens; does nothing else.

---

If this isn't a regression from a previous build, it would be a regression from Fennec and Focus which both do this.

### Device information

* Android device: Android 10
* Fenix version: 4.2.0 and nightly (2020-04-02)

**Comment by kbrosnan** [comment]
Sounds like a dupe of #7013
