### ISSUE TITLE
[Bug] Add-ons option not present on the home screen main menu

### ISSUE THREAD

**Issue by kbrosnan** [mozilla-mobile/fenix#9696]
It seems odd that reaching the add-ons screen requires a tab to be open or go through the settings. @topotropic was this intentional? If so then just close this issue.  

## Steps to reproduce
* Open Fenix and make sure the homescreen is displayed
* Tap on the 3 dot menu

### Expected behavior
* Add-ons listed

### Actual behavior
* Add-ons not listed

### Device information

* Android device: Any
* Fenix version: 4.2.1 and Nightly

**Comment by topotropic** [comment]
We can add a menu item "Add-ons" to the home menu – that said, if we introduce "new tab" with the dedicated tab tray, we have to revisit the menu anyway and align with site menu
