### ISSUE TITLE
[Bug] Remove help from the main menu in the home screen

### ISSUE THREAD

**Issue by kbrosnan** [mozilla-mobile/fenix#9697]
#8474 removed the help item from the menu options when a tab is open however it is still present in the Homescreen view. @topotropic please close if this is intended behavior.

## Steps to reproduce
* Open Fenix and make sure that the home screen is displayed
* Tap the 3 dot menu

### Expected behavior
* No help item listed

### Actual behavior
* Help item listed

### Device information

* Android device: Any
* Fenix version: 4.2.1 and Nightly

**Comment by topotropic** [comment]
We can leave it there for now – the home menu isn't as packed as the site menu and also not aligned in any other way. We should revisit in case we replace "home" with "new tab" as part of the tab tray work.
