### ISSUE TITLE
[Meta] Tracking Protection

### ISSUE THREAD

**Issue by bbinto** [mozilla-mobile/fenix#97]
### Why/User Benefit/User Problem
- As a user, I want to be protected from trackers so my browsing information stays private and ads don't follow me around on the web

### Acceptance Criteria (how do I know when I’m done?)
-UX completed
-User stories completed
-Strings written and approved
-QA completed
-Localization done

### What / Requirements
-UX designs: #1064

**Comment by sblatz** [comment]
What "policy" do we want for tracking protection on by default? Our choices include any combination of:

- ads
- analytics
- social media
- content

For reference: Focus had all but the last one on by default.

**Comment by bbinto** [comment]
I think we should make sure to align it as much to Fennec Android and Focus - so that list of default on/off looks good to me, especially as a start.

**Comment by vesta0** [comment]
We can also add 2 new tracking list categories that will be available in Geckoview by then ([bug 1530789](https://bugzilla.mozilla.org/show_bug.cgi?id=1530789)

**Comment by boek** [comment]
Once we have the controls we should verify the default settings are the ones we want to ship. We had an issue opened #872 that mentioned under the current settings some images didn't load.
