### ISSUE TITLE
[Bug] Logging into Firefox Sync never finishes

### ISSUE THREAD

**Issue by rpappalax** [mozilla-mobile/fenix#9700]
## Steps to reproduce
1. Open Settings
2. Sync
3. Enter email & password

### Expected behavior
4. Sign in screen should show successful login

### Actual behavior
4. Sign in screen gets stuck at "Working..."

NOTE:
Backing out of this screen, it appears that the login is successful but at login time just gets hung on the "working" screen

### Device information

* Android device: Nexus 6P, Android 8.0.0
* Fenix version: 4.2.1 (Build #20941431)

![Screenshot_20200403-151959](https://user-images.githubusercontent.com/3699494/78409882-b854f400-75bf-11ea-90ea-c783e102df25.png)

**Comment by sflorean** [comment]
Not reproducible with Nokia 6 (Android 7.1.1), Samsung Galaxy Note10 (Android 10), Xiaomi Mi Pad 2 (Android 5.1)- x86.
