### ISSUE TITLE
[Bug] App stuck in full screen mode after watching a video

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/fenix#9703]
## Steps to reproduce
1. Open YouTube and watch a video.
2. Put the video in full screen mode.
3. Press the home button.
4. Return to the app.

### Expected behavior
- The site should be on the same page.
- The app toolbar and controls are visible.

### Actual behavior
- Web content is in full screen and you can't leave it.
- The app toolbar and controls are missing.
- System status bar is missing.

### Device information

* Android device: Android 10, Pixel 4
* Fenix version: Nightly 200403 06:01

![Screenshot_20200403-191159](https://user-images.githubusercontent.com/1370580/78411979-c61a7180-75df-11ea-9ec7-4c87895758b6.png)

**Comment by jonalmeida** [comment]
Observe in the screenshot the overlap of the time and the web content in the top right corner, and the web content below half cut out at the bottom.

**Comment by jonalmeida** [comment]
Watching another video and toggling full screen mode let me see the browser UI again.

**Comment by AndiAJ** [comment]
Hi, I've re-checkd this on my Nightly debug Build #21040820 39.0.20200410130104, 464e3038d GV: 77.0a1-20200409095500 AS: 0.55.0 from Monday 4/13 using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)

❓ Looks like on the OnePlus A3 the video remains stuck in full screen after resume, and every time you hit the play button the video starts from the beginning. 
► Video Fenix
![20200413-103232](https://user-images.githubusercontent.com/51314259/79103797-eed7ff00-7d75-11ea-937a-fe553d9f4581.gif)

► Video Chrome
![20200413-103438](https://user-images.githubusercontent.com/51314259/79104033-6574fc80-7d76-11ea-8a59-6138be8bbd9c.gif)

✔️ Works properly on both Google Pixel 3a & Huawei Mate 20 Lite
► Video
![20200413-101040](https://user-images.githubusercontent.com/51314259/79103928-2e9ee680-7d76-11ea-8ec9-759186912593.gif)

@jonalmeida - Please review and share your thoughts. ☺️ 
I'll remove the QA needed label unil further notice.

**Comment by AndiAJ** [comment]
Hi, **still reproducible** on Fenix beta **`4.3.0-beta.1 (Build #21050021) `** using a OnePlus A3 (Android 6.0.1)

✔️ No issues encountered on:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)

► Video
![20200414-114415](https://user-images.githubusercontent.com/51314259/79204881-ea7b1700-7e45-11ea-82dd-d794cbc4357d.gif)

**Comment by ekager** [comment]
@AndiAJ in the video in the comment above it doesn't look like the video is stuck in full screen? Is the remaining issue that the video restarts on this device?

**Comment by AndiAJ** [comment]
@ekager  - No, the re-start issue seem to be fixed .

On the other hand, as described by @jonalmeida : 
• The android taskbar overlaps with the page content
• Fenix's toolbar is missing

► Video
![20200415-081441](https://user-images.githubusercontent.com/51314259/79301681-dccf9b00-7ef2-11ea-9abe-a434380809eb.gif)

Please share your thoughts. ☺️

**Comment by ekager** [comment]
Okay let's try this again :)

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly Build #21130610 from 4/22`** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)

► Video from OnePlus A3 
![20200422-120206](https://user-images.githubusercontent.com/51314259/79962997-7d90fe00-8491-11ea-8670-f16341f58ed2.gif)
