### ISSUE TITLE
Change prompt font size

### ISSUE THREAD

**Issue by 90du** [mozilla-mobile/fenix#9706]
### Why/User Benefit/User Problem
Prompt font looks bloated
### What/Requirements
Use slim fonts
### Acceptance Criteria (how do I know when I’m done?)
Home tips don't look bloated

**Comment by kbrosnan** [comment]
Material uses capital bold in many cases. See https://material.io/components/snackbars/ for some examples. Do you see specific areas where Material design is not being followed? Screenshots would be helpful.

**Comment by vesta0** [comment]
Closing for now until more input is provided.
