### ISSUE TITLE
[Bug]Sometimes clicking on the icon to enter the program will get stuck

### ISSUE THREAD

**Issue by 90du** [mozilla-mobile/fenix#9707]
## Steps to reproduce
Sometimes clicking on the icon to enter the program will get stuck
![1585977027973_341x719](https://user-images.githubusercontent.com/35375370/78419181-bfd6d480-7675-11ea-9952-8aa7323ce7ae.gif)

### Expected behavior
Won't get stuck every time you open the program
### Actual behavior
Sometimes it gets stuck and you have to re-enter the program
### Device information

* Android device: ?
* Fenix version: ?
Nightly 200403 18:00 (Build #20941805)

**Comment by ekager** [comment]
@90du are you still seeing this? I can't reproduce on my device on nightly.

**Comment by Diana-Rus** [comment]
Hi, this looks like the issue from bug: #10494 , it seems to be stuck on the same screen as well. The issue I am talking about it reproduces when you connect with a firefox account through the browser.

@90du - Can you please confirm that when the browser gets stuck, you are connected to a firefox account?
