### ISSUE TITLE
[Bug] pull to refresh does not work on GitHub

### ISSUE THREAD

**Issue by cadeyrn** [mozilla-mobile/fenix#9708]
### Steps to reproduce

1. open https://github.com/notifications/beta
2. pull down from the top to refresh the page

### Expected behavior

It works.

### Actual behavior

While the feature works on most websites it doesn't work at all on GitHub.

### Device information

* Android device: OnePlus 7T Pro McLaren Edition, OxygenOS 10.0.7 (Android 10)
* Fenix version: master branch revision b35704beed2ba48331d93485c499d7cf05fd9d82

**Comment by bubi-luka** [comment]
Verified with Nightly 200405 18:01 (Build #20961811) on Android 9 (Huawei p20 lite EMUI 9.1).

**Comment by cadeyrn** [comment]
This works now with pull to refresh enabled via feature flags.
