### ISSUE TITLE
[Bug] "phone" in translations

### ISSUE THREAD

**Issue by cadeyrn** [mozilla-mobile/fenix#9709]
Some translations contains the word "phone", for example:

`<string name="add_to_homescreen_description">You can easily add this website to your phone’s Home screen to have instant access and browse faster with an app-like experience.</string>`

`<string name="onboarding_firefox_account_auto_signin_header_2">You are signed in as %s on another Firefox browser on this phone. Would you like to sign in with this account?</string>`

(edit: the second one is already filed as #8343)

Maybe replace this with "device"? Because a tablet is not a phone and you can use Fenix on phones and tablets.

**Comment by sflorean** [comment]
Verified as fixed on Nightly 9/11 and 81.1.1-beta.3 with LG G7 Fit (Android 8.0).
