### ISSUE TITLE
No easy way to dismiss add-on's settings page

### ISSUE THREAD

**Issue by cadeyrn** [mozilla-mobile/fenix#9711]
### Steps to reproduce

1. open the add-ons manager
2. open uBlock Origin's settings
3. press back button
4. repeat step 3

### Expected behavior

You're back in the add-ons manager view after step 3.

![Screenshot_20200404-092813](https://user-images.githubusercontent.com/1100614/78421323-fbae7180-7656-11ea-834d-8525fc3750ef.jpg)

### Actual behavior

The settings screen is completly white after step 3, only the settings tabs are visible.

![Screenshot_20200404-092837](https://user-images.githubusercontent.com/1100614/78421334-197bd680-7657-11ea-8321-2449db86683e.jpg)

Pressing back again (step 4) closes Fenix.

![Screenshot_20200404-092843](https://user-images.githubusercontent.com/1100614/78421338-20a2e480-7657-11ea-9b2f-cdc93e34cd14.jpg)

You have to open Fenix again. In the tabs view you can find the settings page of uBlock Origin. It should be no longer there.

![Screenshot_20200404-093354](https://user-images.githubusercontent.com/1100614/78421404-927b2e00-7657-11ea-9c73-5a57b06036ba.jpg)

You can close the tab or open it, but it's still broken. You have to reload this tab to make it usable again.

### Device information

* Android device: OnePlus 7T Pro McLaren Edition, OxygenOS 10.0.7 (Android 10)
* Fenix version: master branch revision b35704beed2ba48331d93485c499d7cf05fd9d82

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-16663)

**Comment by ekager** [comment]
@cadeyrn is this still an issue?

**Comment by cadeyrn** [comment]
@ekager Sorry, I didn't see the question earlier.

In the original report I wrote as expected behaviour:
_You're back in the add-ons manager view after step 3._

This is still not the case. Instead you're on the Firefox start screen after pressing the back button. The settings page is still open and you can access it via the tabs tray.

When I reported the issue you got a broken settings page after pressing the back button and pressing the back button a second time closed Firefox. So it was quite difficult to dismiss the add-on's settings page. This is no longer the case.

So the behaviour is still different but much better now. I guess it's a UX question if there is still an issue or if we are okay with the current behaviour. I am okay with both possible answers to this question.

**Comment by cadeyrn** [comment]
Dear stale bot,

> So the behaviour is still different but much better now. I guess it's a UX question if there is still an issue or if we are okay with the current behaviour.

UX has to answer if this is done or not.

**Comment by cadeyrn** [comment]
(comment for bot)

> UX has to answer if this is done or not.

This is still true.

**Comment by cadeyrn** [comment]
UX has to answer if this is done or not.

**Comment by cadeyrn** [comment]
comment for bot:

UX has to answer if this is done or not.

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1811628

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
