### ISSUE TITLE
[Bug] Find in page finds something even after erasing query

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#9713]
## Steps to reproduce
open find in page
enter some query so that it matches something in the page
erase the query
tapping the up down arrows 

### Expected behavior
Nothing should happen
### Actual behavior
Firefox still finds the last letter deleted in the page

### Device information

* Android device: Asus zenfone
* Fenix version: Fenix Nightly

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-16665)

**Comment by Diana-Rus** [comment]
Hi, i can also reproduce the issue with Google Pixel 3 XL (Android 9), Samsung Galaxy S9 (Android 8) and Sony Xperia Z5 (Android 7) on Nightly 5/8.

**Comment by Diana-Rus** [comment]
Issue reproduces with Firefox Preview Beta 5.1.0-beta.1 with Sony Xperia Z5 (Android 7).

**Comment by Diana-Rus** [comment]
Reproducible on Beta 5.2.0-beta.1 with Samsung Galaxy S9 (Android 8)

**Comment by s-ankur** [comment]
Still reproducible in Nightly  210204 17:01

**Comment by softvision-miralobontiu** [comment]
I was **NOT** able to reproduce the issue on the 2/11 Nightly build, with Samsung Galaxy Note 8 (Android 9).

**Comment by s-ankur** [comment]
Still happening

**Comment by sflorean** [comment]
I was able to reproduce this on latest Nightly build, with OnePlus 9 (Android 11).
