### ISSUE TITLE
[Bug] Double Clicking on a word does not open a text selection in a textbox

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#9714]
## Steps to reproduce
Open a textbox
double tap on a word in the textbox

### Expected behavior
the word should be selected
### Actual behavior
only the paste/select all toolbar appears

### Device information

* Android device: Asus Zenfone
* Fenix version: Fenix Nightly

**Comment by makotokato** [comment]
This is known issue as https://bugzilla.mozilla.org/show_bug.cgi?id=1365119 etc.

**Comment by s-ankur** [comment]
Hi, can this be prioritised a bit? It blocks basic text editing functionality and the bugzilla issue has been open for 3 years now :/
