### ISSUE TITLE
Switch to newly opened background tab

### ISSUE THREAD

**Issue by msoose** [mozilla-mobile/fenix#9717]
### Why/User Benefit/User Problem
When opening a tab in the background the notification that pops up with the "SWITCH" option is justified to the right which makes it hard to reach depending on device size.

### What/Requirements
Set the entire notification as the "button" to register a request to switch instead of the right justified button.

**Comment by brampitoyo** [comment]
We want all our snackbars to work consistently, and consistently with all other snackbars in Android. For that reason, I don’t think we should make the entire snackbar tappable.

**Comment by ekager** [comment]
Closing because we got the UX feedback 👍
