### ISSUE TITLE
[Bug] Pull to refresh activates on Twitter home

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/fenix#9718]
## Steps to reproduce

1. Navigate to https://mobile.twitter.com/home
2. Login - hopefully you have followed some people
3. Scroll down a screen
4. Quickly scroll down 

### Expected behavior

Twitter's loading of more posts should activate. Fenix pull to refresh should not activate on Twitter home. 

### Actual behavior

There are a couple of undesired behaviors here. Sometimes, the Twitter pull down doesn't get activated, but Fenix's pull to refresh gets activated. Sometimes double pulling will cause the Twitter pull down to get activated, followed by the Fenix pull to refresh. 

### Device information

* Android device: pixel 2
* Fenix version: latest from play store

**Comment by softvision-miralobontiu** [comment]
I was able to reproduce the issue on the 10/20 Nightly build with Samsung Galaxy Tab S6 (Android 10).

**Comment by Mugurell** [comment]
If the "Suggested logins" dialog is shown also the toolbar will be animated.
