### ISSUE TITLE
Create a setting for Pull to refresh

### ISSUE THREAD

**Issue by Timvde** [mozilla-mobile/fenix#9719]
### Why/User Benefit/User Problem
There are multiple people on [/r/Firefox](https://www.reddit.com/r/firefox/comments/fumq24/pull_to_refresh_in_coming_in_next_update_of_fenix/) who dislike the new feature. It would be nice if there was a way to disable it.

### What/Requirements
Create a setting to disable pull to refresh.

### Acceptance Criteria (how do I know when I’m done?)
If there's a switch that I can toggle which disables pull to refresh.

**Comment by lindongbin** [comment]
It's easy to trigger when zooming

**Comment by danielzgtg** [comment]
On some websites, pull to refresh makes it easy to lose all your work

**Comment by Rodze** [comment]
> 
> 
> It's easy to trigger when zooming

It's easy to trigger doing anything. Extremely annoying. It should be disabled by default and anyone who wants to live dangerously can turn it on with the setting.

**Comment by cadeyrn** [comment]
It *is* already disabled by default in the latest master build. And for bugs with the current implementation please see #9766.

**Comment by Mugurell** [comment]
This was implemented and is currently available in Nightly and will follow the pull to refresh feature availability in beta / release builds.
