### ISSUE TITLE
[Bug] Pull to refresh doesn't work on Phonearena.com

### ISSUE THREAD

**Issue by Daplugg23** [mozilla-mobile/fenix#9720]
## Steps to reproduce
Go to Phonearena.com
### Expected behavior
To  work
### Actual behavior
Doesn't work
### Device information
Android 10 
* Androidvice: ?
Samsung Galaxy s9+
* Fenix version: ?

**Comment by kawaiiDango** [comment]
It also doesn't work on w3schools.com

**Comment by LittleAngelwings** [comment]
And also it doesn't work here.

**Comment by SS1113** [comment]
it also doesn't properly work on: https://bing.com/covid

**Comment by flomertens** [comment]
And at https://www.latribune.fr/ as well, same issue I presume.

**Comment by liuche** [comment]
Duping to #9766
