### ISSUE TITLE
[Bug] Replaced monospaced font won't be rendered

### ISSUE THREAD

**Issue by moposx** [mozilla-mobile/fenix#9723]
## Steps to reproduce
Using Magisk or some file managers, to replace the Android's default monospace font "Droid Sans Mono" to another monospace font. In my case, that will be Source Code Pro.
After replacing fonts and rebooting the phone, open any web pages containing source code or just applying monospace fonts, for example: https://github.com/torvalds/linux/blob/master/README
### Expected behavior
The README File should be rendered in monospace font, respecting the css properties.  
![expected behavior](https://user-images.githubusercontent.com/15135544/78469674-056ace80-7756-11ea-97f7-8d008a398d93.png)
### Actual behavior
Instead, the text is rendered in default sans-serif font, e.g. Roboto.  
![Screenshot_20200405-155502](https://user-images.githubusercontent.com/15135544/78469691-1fa4ac80-7756-11ea-8c6b-54c1293341bb.png)
### Device information

* Android device: Pixel 2 XL, android 10
* Fenix version: Nightly 200404 18:01

**Comment by moposx** [comment]
A simple workaround is to **restore Android's default monospaced font.** (I think this is also why I can hardly find a similar issue here.)  
This issue is also reproducible on Firefox 68 for Android.

**Comment by buttercookie42** [comment]
Gecko looks up fonts by meta data, *not* by file name, so
> Using Magisk or some file managers, to replace the Android's default monospace font "Droid Sans Mono" to another monospace font.

that kind of clever trick doesn't work for Firefox unless you update the font name list in about:config as well (or use a font file which spoofs not just the file name but the meta data as well).

See also [bug 1505650](https://bugzilla.mozilla.org/show_bug.cgi?id=1505650).

**Comment by moposx** [comment]
@buttercookie42 
Thanks for the explanation and now I know this is actually not a bug. I will close this issue since the problem is solved.
