### ISSUE TITLE
[Bug] pull to refresh shouldn't happen when pinch zooming

### ISSUE THREAD

**Issue by staktrace** [mozilla-mobile/fenix#9725]
## Steps to reproduce

pinch zoom on a page

### Expected behavior

no pull to refresh

### Actual behavior

easy to trigger pull to refresh

### Device information

* Android device: Sony xperia XZ1C
* Fenix version: Nightly 200404 06:01 (Build #20950612)
38.0.20200403130109, aa939e94e
GV: 76.0a1-20200403063228
AS: 0.55.0

**Comment by Mugurell** [comment]
Thank you for the report!
Looks like we need to separate between zooming and panning.

**Comment by staktrace** [comment]
There's lots of other conditions where you shouldn't trigger pull-to-refresh either, such as one the one-touch-pinch gesture is in effect, or if the user is scrolling a subframe. In general you should ensure the gecko code handles the scroll gesture and check the return code from gecko to determine whether or not the gesture was "unhandled" and can be used for pull-to-refresh.

**Comment by Mugurell** [comment]
Thank you!
Indeed most of the issues reported around pull to request are because of
- not differentiating if the scroll happens in an iframe/scrollable div or in a webpage. inner vs toplevel.
- not properly differentiating between panning / zooming.

**Comment by kawaiiDango** [comment]
I'd like to add that pull to refresh should only trigger on a vertical overscroll. 
On this page https://www.google.com/search?q=cats&ie=utf-8&oe=utf-8&client=firefox-b-m
pull to refresh triggers when scrolling the image list horizontally at a slight angle

**Comment by Mugurell** [comment]
Thank you @kawaiiDango !
This seems to be happening because we're not differentiating between inner/topLevel scrolls.
We are working on a better solution for all of the above.

**Comment by staktrace** [comment]
Blah blah blah

**Comment by Mugurell** [comment]
@staktrace I think these kind of issues are resolved by now.
Zooming (with one / more fingers) should not trigger pull to refresh anymore.
Do you still see this issue? On all pages / some particular ones?

**Comment by staktrace** [comment]
Ah, you're right. I can't reproduce these issues any more. Thanks!
