### ISSUE TITLE
Better UX for editing textareas

### ISSUE THREAD

**Issue by staktrace** [mozilla-mobile/fenix#9729]
### Why/User Benefit/User Problem

Text areas suck, inputting any nontrivial amount of text (such as filling in this "feature request" template on github) takes about 3x - 5x longer than it would on desktop. I find this is primarily because moving the cursor around to edit text often results in the text input scrolling belatedly and my taps end up going not where I expect them, etc.

### What/Requirements

Concrete suggestion I have to improve this is to provide a mechanism for the user to "pop out" the textarea into a fullscreen native Android text input widget, and allow them to do their edits there. Once done, they can "submit" to return to the webpage, and the stuff they inputted in the native widget gets pasted back into the textarea. The mechanism could be accessible by long-pressing the textarea, or maybe via an icon added in one of the corners or something.

### Acceptance Criteria (how do I know when I’m done?)

Inputting a nontrivial amount of text into a textarea is no worse in the browser than it is in other native apps.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-16679)

**Comment by kbrosnan** [comment]
A lot of this behavior is defined by Gecko. @makotokato might have some ideas

**Comment by staktrace** [comment]
I don't think this can be fixed on the Gecko side, because Gecko has to confirm to various web platform expectations (e.g. sizing to what the content author specifies) that is inherently user-unfriendly. The suggestion I made to fix this can and should be done entirely in the front end.

**Comment by makotokato** [comment]
Actually, device's screen size is narrow, we don't set `IME_FLAG_NO_FULLSCREEN` when creating `InputConnection`. If handling native control in a-c or Fenix, we may need a lot of APIs for focusin/focusout/key/composition event etc.

**Comment by staktrace** [comment]
> we may need a lot of APIs for focusin/focusout/key/composition event etc.

Why? The whole point of my suggestion is to bypass all of this and allow a super easy text entry mechanism, exactly as if the user wrote stuff in a native "notepad" type app and then pasted it in, which is what I'm forced to actually do sometimes.

**Comment by Poopooracoocoo** [comment]
I noticed that when you're editing a search query in the issues page of a GitHub repo, when you move the cursor of a long query Firefox doesn't automatically scroll the textbox. The cursor also scrolls vertically when it can only scroll horizontally. Pretty annoying.

**Comment by s-ankur** [comment]
@Poopooracoocoo please make this a seperate issue. I noticed this right now and I can never unnotice it now. 😔

**Comment by Poopooracoocoo** [comment]
@s-ankur #15485

**Comment by staktrace** [comment]
Having this "pop out text editor" would also solve issues like #4208; I'm seeing odd text entry input issues similar to that one that make it extremely frustrating to try and get work done.

**Comment by jonalmeida** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813746

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
