### ISSUE TITLE
[Bug] Undo in the snackbar on deleting a tab should be fixed

### ISSUE THREAD

**Issue by nitin10s** [mozilla-mobile/fenix#9732]
## Steps to reproduce
1. Delete a Tab
2. Observe the Snackbar 

### Actual behavior
1. Undo in all caps looks too emphasized unnecessarily [Signifiers like the font size, the contrast ratio are enough]
2. Text-color of "Undo" is the same as of the "Tab Closed", that can cause problems for users to understand that Undo is clickable

**Comment by apbitner** [comment]
The capitalization follows Material Design guidelines, however, we should look into using a different color for the link.

**Comment by nitin10s** [comment]
Oh, I see, but yes a different colour link would make it more intuitive.
