### ISSUE TITLE
[Bug] Onboarding flickers on Android 5

### ISSUE THREAD

**Issue by softvision-miralobontiu** [mozilla-mobile/fenix#9736]
## Steps to reproduce
1. Clean the Nightly build's profile.
2. Open Fenix.

### Expected behavior
Fenix opens without issues.

### Actual behavior
Fenix opens but flickers one.

### Device information
* Android device: Samsung Galaxy Tab A6 (Android 5.1.1)
* Fenix version: Nightly build 4/6, Beta build 4.2.1-beta.1, RC 4.2.1

![onboarding-flicker](https://user-images.githubusercontent.com/40694158/78544013-2db00700-7802-11ea-95f6-99305e03ddd3.gif)

**Comment by mcarare** [comment]
This is probably due to a workaround used for Android 5 & 6 where we submit an empty list to ListAdapter before populating it, otherwise the list would not update until it is scrolled. Maybe we could come up with another one, that does not cause flickering.

**Comment by softvision-miralobontiu** [comment]
I was not able to reproduce this flicker anymore on the 10/26 Nightly build with Samsung Galaxy Tab A6 (Android 5.1.1).
I'll close this issue.
