### ISSUE TITLE
Video Background Play fix adds on

### ISSUE THREAD

**Issue by ujjwl3** [mozilla-mobile/fenix#9739]
### Why/User Benefit/User Problem
I use it on my firefox for android.
I listen to my playlists often and would like to listen them without turning my phone on.
Currently only one adds on support on firefox preview.

### Acceptance Criteria (how do I know when I’m done?)
Support for the requested add on

**Comment by kbrosnan** [comment]
Closing as we don't need issues tracking each extension. This will be available when general extension support is enabled.
