### ISSUE TITLE
[Bug] Cannot install APK from download notification for files downloaded from uploadrar

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/fenix#9744]
Initially reported on https://www.reddit.com/r/firefox/comments/fw09rn/firefox_preview/

## Steps to reproduce

1. Navigate to: https://uploadrar.com/trraugrle1lm
2. Tap "Create Download Link"
3. Tap "Click Here To Download" in the newly loaded page
4. Tap Download in the snackbar that appears 
5. Wait for download to complete 
6. Tap "Open" in the snackbar that appears

### Expected behavior

Installation prompt, like when downloading from Bromite.

![signal-attachment-2020-04-06-131034](https://user-images.githubusercontent.com/152493/78585546-0c521980-7808-11ea-975f-544655973339.png)

### Actual behavior

Fenix asks me which app I would like to open the apk with:

![signal-attachment-2020-04-06-130931](https://user-images.githubusercontent.com/152493/78585601-20961680-7808-11ea-9cc6-cab354c37cc1.png)

### Device information

* Android device: Pixel 2
* Fenix version: latest from play store
FYI, I checked to ensure that "Install unknown apps" permission was granted to Fenix.

**Comment by yoasif** [comment]
Just tried this on https://f-droid.org/FDroid.apk and it doesn't work with that either - unsure if this is pervasive for all apks.

**Comment by bepvte** [comment]
This also occurs outside of the snackbar in the system notifications. I've noticed this behavior in fennec as well in any case where .apks were attempted to be opened.

**Comment by ekager** [comment]
Does it work if you grant the permissions in Android Settings -> Apps -> Firefox Preview -> Advanced -> Install Unknown Apps ?

**Comment by bepvte** [comment]
It does
