### ISSUE TITLE
[Bug] Pull refresh is triggered at any position on the page

### ISSUE THREAD

**Issue by miketaylr** [mozilla-mobile/fenix#9747]
## Steps to Reproduce:
the newly added feature pull down refresh should be active only at the top of the page, but it's active at any position. Samsung internet browser is fine with the same page, refresh only when it's at the top.

URL: https://d2l.ai/chapter_recurrent-modern/gru.html

(originally reported here https://github.com/webcompat/web-bugs/issues/51148)

**Comment by bananer** [comment]
I have observed this issue also on https://www.muenchen.de/dienstleistungsfinder/muenchen/1063441/n0/

**Comment by softvision-miralobontiu** [comment]
Please see also #9766.

**Comment by miketaylr** [comment]
ok

**Comment by miketaylr** [comment]
Pretty sure this is never getting fixed.

**Comment by miketaylr** [comment]
ok

**Comment by theres-waldo** [comment]
@miketaylr @bananer @kbrosnan Are any of you able to reproduce this issue in current Fenix? Hiro and I tried both URLs mentioned in this bug and we cannot reproduce it.

**Comment by bananer** [comment]
Works good now on https://www.muenchen.de/dienstleistungsfinder/muenchen/1063441/n0/

Pull refresh does not trigger at all on https://d2l.ai/chapter_recurrent-modern/gru.html

Latest Nightly 101.0a1 (Build #2015875851)

**Comment by theres-waldo** [comment]
> Pull refresh does not trigger at all on https://d2l.ai/chapter_recurrent-modern/gru.html

Confirmed, I see the same.

**Comment by theres-waldo** [comment]
> > Pull refresh does not trigger at all on https://d2l.ai/chapter_recurrent-modern/gru.html
> 
> Confirmed, I see the same.

It looks like the difference in pull-to-refresh behaviour between Chrome and Firefox on this site needs is potentially an issue on our side that needs further investigation.

It may be fairly subtle, in that on this page the scrollable element is a subframe, and pull-to-refresh activation is presumably intended to happen via hand-off to the root, **and** the site has a scroll event listener that may be interfering with things.

@kbrosnan please feel free to morph this remaining issue into a Gecko (Panning and Zooming) bug.

**Comment by hiikezoe** [comment]
I filed https://bugzilla.mozilla.org/show_bug.cgi?id=1766366 for the issue on our end.
