### ISSUE TITLE
[Bug] firefox preview can't download pdf file in some site.

### ISSUE THREAD

**Issue by uNouss** [mozilla-mobile/fenix#9748]
## Steps to reproduce
- go to https://media.interieur.gouv.fr/deplacement-covid-19/ 
- fill in the form
- click on the "generate my certificate" button
- firefox offers to download the file but the download fails
### Expected behavior
- To download the pdf file
### Actual behavior
![Screenshot_20200406_225233](https://user-images.githubusercontent.com/15982321/78604434-17ce3080-785a-11ea-8845-2c5f2864e38d.jpg)
![Screenshot_20200406_224847](https://user-images.githubusercontent.com/15982321/78604433-169d0380-785a-11ea-8837-0792fafaa096.jpg)
### Device information
* Android device: Huawei P20 EMUI 9.1.0
* Fenix version: 4.2.1

**Comment by kbrosnan** [comment]
dupe #9735
