### ISSUE TITLE
[Bug] Set as default browser should just be a toggle

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#9749]
Currently the "set as default browser" preference sends you to a fragment where the only option is to toggle it on. We should raise this toggle outside of this preference if it's the only one inside.

<img width="350" alt="image" src="https://user-images.githubusercontent.com/4400286/78603718-74572e80-780d-11ea-95c5-f9b4e9ed39fa.png">

**Comment by hakkikaancaliskan** [comment]
Also what about completely hiding it if Firefox is already default?

**Comment by nitin10s** [comment]
Yes, the toggle can be placed at the preference "Set as Default Browser itself" itself.

**Comment by sblatz** [comment]
@AmyYLee Can you please let me know if this was part of the settings redesign? We can also just pull it out to the main menu which is how it used to work? :)

**Comment by brampitoyo** [comment]
@sblatz Quoting @AmyYLee on https://github.com/mozilla-mobile/fenix/issues/5905#issuecomment-585427769, we’ve made a decision to put “Open links in apps” inside this “Set as default browser” section:

> The "Open links in apps" should be located here (see screenshot). This is part of issue #3177 and the full UX spec can be found in [comment 0](https://github.com/mozilla-mobile/fenix/issues/5905#issue-504909257).
> 
> <img width="1138" alt="Screen Shot 2020-02-12 at 12 01 11 PM" src="https://user-images.githubusercontent.com/5992746/74378968-e33b7c80-4db4-11ea-8060-650ca949ac0b.png">

This means that this section will contain two items, so it can’t be pulled out into the main Settings page.

**Comment by kbrosnan** [comment]
That sounds like a negative implementation of  `Open links in apps` how would those two prefs interact?

**Comment by brampitoyo** [comment]
@kbrosnan I think so. @AmyYLee, can you help confirm?

**Comment by AmyYLee** [comment]
> @kbrosnan I think so. @AmyYLee, can you help confirm?

Hi, 

@kbrosnan Yes it is. "Present websites from opening links in external apps" will be ON by default. These 2 items are separate and whether or not FF is set as default should not affect how we handle links.  

Looping in @betsymi to review strings. These were looked at by Michelle a while back FYI.
Betsy, basically the change is from "Open links in apps" (which can be found in settings top level) to "Prevent websites from opening links in external apps" that will live in "Set as default browser" section and this will be ON by default.

**Comment by apbitner** [comment]
Set as default browser is on the Settings top level.
