### ISSUE TITLE
Progressive Web App Support

### ISSUE THREAD

**Issue by aliglelo** [mozilla-mobile/fenix#9755]

**Comment by ekager** [comment]
On first run of a PWA-able website we show this dialog now (new in Nightly):
![Screenshot_20200406-221909](https://user-images.githubusercontent.com/25442310/78632773-c0799180-7854-11ea-9993-c27f2564a8de.png)

Otherwise, the "Install" option in the menu will appear for installable apps.

**Comment by aliglelo** [comment]
Okay, and when we will have this function in stable version?

**Comment by Rorschach1010** [comment]
> Okay, and when we will have this function in stable version?

I second that. Would be awesome to get PWA support for the stable Fenix app.

**Comment by aliglelo** [comment]
> > Okay, and when we will have this function in stable version?
> 
> I second that. Would be awesome to get PWA support for the stable Fenix app.
> 
> EDIT:
> looks like its planned for 1. Q.
> [mozilla-mobile/fenix/projects/23](https://github.com/mozilla-mobile/fenix/projects/23)

Yeah I can see that listed there.
But when it would be released?Do you have any idea?

**Comment by ekager** [comment]
Closing for #204
