### ISSUE TITLE
[Bug] Non-uniform sizes of Collection

### ISSUE THREAD

**Issue by nitin10s** [mozilla-mobile/fenix#9757]
![Screenshot_20200407-114235](https://user-images.githubusercontent.com/16988558/78637157-74b40000-78c7-11ea-9967-c327b084bcd6.png)

### Actual behavior
The first collection sometimes takes extra margins.

### Device information

* Android device: Samsung Galaxy S7 Edge
* Fenix version: 4.2.0

**Comment by cadeyrn** [comment]
Fenix Nightly has a different design for collapsed collections (without the section for the domains). So I don't think it's still an issue. But I never saw this problem, so I can't be sure. Maybe you could test with Fenix Nightly and verify if it's still an issue for you or not?

**Comment by nitin10s** [comment]
Ok I see, it's fine now. I am actually now concerned that why users can share or access collection options without opening the collection.
