### ISSUE TITLE
Improve Share Collection feature

### ISSUE THREAD

**Issue by nitin10s** [mozilla-mobile/fenix#9759]
## Steps to reproduce
1. Make a collection
2. Click on Share the collection button

![Screenshot_20200407-114301](https://user-images.githubusercontent.com/16988558/78638270-9c0bcc80-78c9-11ea-8e02-9d023ee22536.png)

### Actual behavior
1. According to the thumb zone, the close button on top-left is hard to reach. The button should instead be placed on the top-right.
2. The user should get a feedback of which collection is he going to share [Collection Title should be displayed]
3. Along with sharing links, the collection name should also be shared. [Discussion Needed]

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-16702)

**Comment by Poopooracoocoo** [comment]
>According to the thumb zone, the close button on top-left is hard to reach. The button should instead be placed on the top-right.

but back buttons

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812754

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
