### ISSUE TITLE
Telemetry for Library UI

### ISSUE THREAD

**Issue by bifleming** [mozilla-mobile/fenix#976]
@bbinto updated on March 27, 2019

#### Description & Product Manager / Data Scientiest User Story
Understand the usefulness of the library and how it fits into the users workflow

#### Hypothesis
Users may find it helpful to go through the library UI to access their history, bookmarks, sessions, downloads, etc. increasingly more over time

#### What questions will you answer with this data?
- Understand how often and when and what they access in the library

#### Why does Mozilla need to answer these questions? Are there benefits for users? Do we need this information to address product or business requirements?
- It will help us understand how useful the library concept is

#### What probes (suggested, if applicable)
- View library main view
- Hit the x to exit the library view
- Hit the browser back arrow to exit the library view
- Tap on bookmarks and history

### Dependencies (Added by PM and Eng)
- Glean SDK

### Acceptance Criteria (Added by PM)
- Event pings can be queried via re:dash
- We are sending telemetry events for the actions listed in the requirements
- We have documented the telemetry
- We have asked a data steward to [review](https://github.com/mozilla/data-review/blob/master/request.md) the telemetry

- NOT an AC: Data science to create dashboard or further graphs (this will be a separate issue, this issue is only about hooking up the events described and that they can be queried in re-dash)

**Comment by sblatz** [comment]
Do we only want to track users pressing the "x" to close the library or should we also track them navigating in other ways?

@vesta0

**Comment by vesta0** [comment]
Both, updated the description :)
