### ISSUE TITLE
Direct 'play' in external app?

### ISSUE THREAD

**Issue by francoism90** [mozilla-mobile/fenix#9760]
### Why/User Benefit/User Problem

In the current Firefox I'm able to open a video file directly (https://example.com/video.mp4) in an external app like VLC.

Doing the same in Firefox Preview results in the file always being download instead of opening/streaming in the video/external app.

### What/Requirements

Open in external app

### Acceptance Criteria (how do I know when I’m done?)

Opens in external app

**Comment by rocketsroger** [comment]
related https://github.com/mozilla-mobile/android-components/issues/6691.  Will confirm once Android Component version is updated to include this fix.
