### ISSUE TITLE
Track battery power regressions

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/fenix#9761]
### Why/User Benefit/User Problem

As a user, I would like to ensure that Fenix never uses more battery than a previous version.

### What/Requirements

* automated method of checking for performance regressions on  a variety of hardware, a la Talos or [Batterylab](https://batterylab.dev/)

### Acceptance Criteria (how do I know when I’m done?)

Successive Fenix releases use less battery power than previous versions, or stay stable.

Saw the reference to batterylab on the latest Brave release notes: 

>That is, each new version of Brave is tested against its predecessor to guarantee no performance regression. This is realized atop of Batterylab, https://batterylab.dev/ [3], a distributed platform for battery measurements we have realized in collaboration with Imperial College of London and Northwestern University.

**Comment by mcomella** [comment]
@ecsmyth Can you fill in details (or delegate it) on our current power testing situation?

**Comment by mcomella** [comment]
Sparky sent me some notes on current power testing: 

> (1) We haven't worked on battery/power testing in quite a while (since the summer IIRC), but we do have the infrastructure available in Raptor ("a la Talos"-ish) if needed. We also have mozpower that is used for mac power testing and could have andoird added to it quite easily (so we don't need to be restricted to raptor - I've got a patch for this somewhere). The number and diversity of tests we currently have running is very low though. We run an idle app-foregrounded test, idle app-backgrounded test, and speedometer. Speedometer tests the power usage over the course of the entire test for CPU, Network and the Screen through ADB - it doesn't last 20 minutes though. You can find all of our power testing data here, none of the browsers have shown regressions: https://health.graphics/power

---

Triage: in 2020, we have better "resource testing" in scope but right now we have higher priorities so setting to low impact.

**Comment by mcomella** [comment]
We're tracking high level tasks like this on JIRA: https://jira.mozilla.com/browse/FXP-468 so closing this issue.

Please file an issue if you're having a specific problem! (we filed an issue on your behalf from your notes on Matrix: https://github.com/mozilla-mobile/fenix/issues/12840)
