### ISSUE TITLE
[Bug] Refresh circle is still displayed after a recent apps button interrupt

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/fenix#9764]
## Steps to reproduce
1. Launch Fenix.
2. Access any page.
3. Scroll down in order to refresh the page and tap on the recent apps button.
4. Return to Fenix.
### Expected behavior
The Refresh circle disappears after returning to the app as the refresh will be done.
### Actual behavior
The refresh circle doesn't disappear after returning to the app.
### Device information

* Android device: **Google Pixel 4 XL (10).**
* Fenix version: **Nightly 4/7.**

![20200407-115224](https://user-images.githubusercontent.com/42831109/78651474-0d974b00-78c9-11ea-80b6-a346e9787f91.gif)

**Comment by amedyne** [comment]
@abodea Is this still a problem?

**Comment by abodea** [comment]
Hello, @amedyne please note that I tried to reproduce this issue on the latest Nightly 2/16 with Samsung Galaxy S10+ (10) and I was not able to.
Closing this as WFM and in case It will occurs again, I will re-open this bug or a new one.
