### ISSUE TITLE
[Bug][a11y] URL bar - "Cancel" & microphone buttons are recommended to be resized

### ISSUE THREAD

**Issue by Diana-Rus** [mozilla-mobile/fenix#9765]
## Prerequisites:
- Have Google Accessibility Scanner installed.
### Steps to reproduce
1. Open app and from the homescreen, tap on "Search or enter address".
2. Insert data at field level.
3. Scan the search screen.
### Expected behavior
There are no suggestions to make any changes.
### Actual behavior
The cancel button is recommended to have 48 dp wide and 48 dp high.
URL bar - "Cancel" button
- org.mozilla.fenix.nightly:id/mozac_browser_toolbar_clear_view
This item's size is 40dp x 40dp. Consider making this touch target 48dp wide and 48dp high or larger.
### Device information

* Android device: Samsung Galaxy S9 (Android 8)
* Fenix version: Firefox Preview Nightly 200407 (Build #20980610)

Screenshots:
**URL bar - "Cancel" button**
- org.mozilla.fenix.nightly:id/mozac_browser_toolbar_clear_view
![Screenshot_20200407-134132_Accessibility Scanner](https://user-images.githubusercontent.com/49859863/78662301-d3ce4080-78d8-11ea-8f23-d46e0c69cc33.jpg)

**Comment by softvision-miralobontiu** [comment]
This issue still reproduces on the 87.0.0-beta.2 with OnePlus 5T (Android 10), on both the microphone icon, and the close button:

<img src="https://user-images.githubusercontent.com/40694158/109770963-eba36700-7c04-11eb-81a4-8ae723d76bb7.jpg" width="300" height="550" />

**Comment by topotropic** [comment]
@eliserichards would it be possible to define a larger touch target for the cancel and mic icon?

**Comment by lobontiumira** [comment]
Still reproducible on the Beta 89.0.0-beta.1 build with OnePlus 5T (Android 10).

**Comment by LaurentiuApahideanSV** [comment]
The issue still occurs on Firefox Preview 93.0.0-Beta.4.

**Comment by Mugurell** [comment]
Seems like there are more issues on that screen.
Closing this in favor of https://github.com/mozilla-mobile/fenix/issues/24461.
