### ISSUE TITLE
[Bug][a11y] Error Page-Touch target-"No internet connection"page "Reload" button height needs to be increased

### ISSUE THREAD

**Issue by Diana-Rus** [mozilla-mobile/fenix#9768]
## Prerequisites:
Have Google Accessibility Scanner installed.
### Steps to reproduce
1. Open app and from the homescreen,
2. Search after a site through "Search or enter address" search bar.
3. Disable Wi-Fi connection.
4. Refresh page.
5. Scan the "No internet connection" page. 
### Expected behavior
There are no suggestions to make any changes.
### Actual behavior
**Portrait - "No internet connection" - "Reload" button**
- errorTryAgain
This item's height is 35dp. Consider making the height of this touch target 48dp or larger.

**Landscape - "No internet connection" - "Reload" button**
- errorTryAgain
The touch target area is misplaced in landscape mode as it's not placed over the "Reload" button.

### Device information

* Android device: Samsung Galaxy S9 (Android 8)
* Fenix version: Nightly 200407 (Build #20980610)

Screenshots:
**Portrait - "No internet connection" - "Reload" button**
![Screenshot_20200407-142250_Accessibility Scanner](https://user-images.githubusercontent.com/49859863/78664805-6c66bf80-78dd-11ea-8c28-61d960d2bea7.jpg)

**Landscape - "No internet connection" - "Reload" button**
![Screenshot_20200407-144400_Accessibility Scanner](https://user-images.githubusercontent.com/49859863/78665448-805ef100-78de-11ea-875d-8f78e9fb957e.jpg)

**Comment by sflorean** [comment]
Verified as fixed on Nightly 6/9 with LG G7 FIT (Android 8) and Google Pixel (Android 10).
