### ISSUE TITLE
[Bug][a11y] Error Page-Touch target-"Address not found" page "Try again" button's height needs to be increased

### ISSUE THREAD

**Issue by Diana-Rus** [mozilla-mobile/fenix#9769]
## Prerequisites
Have Google Accessibility Scanner installed.
### Steps to reproduce
1. Open app and from the homescreen,
2. Search after an invalid address through "Search or enter address" search bar.
3. Scan the "Address not found" page.
### Expected behavior
There are no suggestions to make any changes.
### Actual behavior
**Portrait - "Address not found" - "Try Again" button**
- errorTryAgain
This item's height is 35dp. Consider making the height of this touch target 48dp or larger.

**Landscape - "Address not found" - "Try Again" button**
- errorTryAgain
The touch target area is misplaced in landscape mode as it's not placed over the "Try Again" button.
### Device information

* Android device: Samsung Galaxy S9 (Android 8)
* Fenix version: Nightly 200407 (Build #20980610)

Screenshots:
**Portrait - "Address not found" - "Try Again" button**
![Screenshot_20200407-150007_Accessibility Scanner](https://user-images.githubusercontent.com/49859863/78667214-34fa1200-78e1-11ea-8c0a-715b8eae2054.jpg)

**Landscape - "Address not found" - "Try Again" button**
![Screenshot_20200407-150210_Accessibility Scanner](https://user-images.githubusercontent.com/49859863/78667222-388d9900-78e1-11ea-9677-7154c94fe152.jpg)

**Comment by mcarare** [comment]
Same issue as https://github.com/mozilla-mobile/fenix/issues/9768, related to the button in low and medium risk pages. Will be tracked there.
