### ISSUE TITLE
Disable pull down to refresh

### ISSUE THREAD

**Issue by Mugurell** [mozilla-mobile/fenix#9770]
After enabling "pull to refresh" in #3262 a number of issues were discovered - https://github.com/mozilla-mobile/fenix/issues/9766.

Thanks to all the reporters we now have a clear understanding of the few remaining issues.
Let's disable this feature until they will be addressed.

**Comment by abodea** [comment]
Verified as fixed on **Nightly 4/8** with **Google Pixel 4 XL (10).**
Note that everything works as expected and the pull-down to refresh is not displayed anymore.
