### ISSUE TITLE
[Bug][a11y] Error Page-Touch target-"Deceptive site issue" page "Go back" button's height needs to be increased

### ISSUE THREAD

**Issue by Diana-Rus** [mozilla-mobile/fenix#9771]
## Prerequisites
Have Google Accessibility Scanner installed.
### Steps to reproduce
1. Open app and go to "http://testsafebrowsing.appspot.com/s/phishing.html"
2. Scan the "Deceptive site issue" page.
### Expected behavior
There are no suggestions to make any changes.
### Actual behavior
**"Deceptive site issue" Page - "Go back" button**
- backButton
This item's height is 35dp. Consider making the height of this touch target 48dp or larger.

### Device information

* Android device: Samsung Galaxy S9 (Android 8)
* Fenix version: Nightly 200407 (Build #20980610)

Screenshot
**"Deceptive site issue" Page - "Go back" button**
![Screenshot_20200407-154236_Accessibility Scanner](https://user-images.githubusercontent.com/49859863/78670687-cf108900-78e6-11ea-9fc8-a6d86e9858cd.jpg)

**Comment by sflorean** [comment]
Verified as fixed on Nightly 6/9 with Google Pixel (Android 10).
