### ISSUE TITLE
[Bug][a11y] Search-Touch target-Elements from module need to have the touch target heightened

### ISSUE THREAD

**Issue by Diana-Rus** [mozilla-mobile/fenix#9775]
## Prerequisites
Have Google Accessibility Scanner installed.
### Steps to reproduce
1. Open app and tap on "Menu"/"Settings"/"Search"/"Add search engine"-"Other" enabled.
2. Scan the "Add search engine" module.
### Expected behavior
There are no suggestions to make any changes.
### Actual behavior
**Add Search Engine - "Other" option - "Name" field**
- org.mozilla.fenix.nightly:id/edit_engine_name
This item's height is 45dp. Consider making the height of this touch target 48dp or larger.

**Add Search Engine - "Other" option - "Search string to use"/path field**
- org.mozilla.fenix.nightly:id/edit_search_string
This item's height is 45dp. Consider making the height of this touch target 48dp or larger.

**Add Search Engine - "Other" option - "Learn more" link**
- org.mozilla.fenix.nightly:id/custom_search_engines_learn_more
This item's height is 19dp. Consider making the height of this touch target 48dp or larger.

### Device information

* Android device: Samsung Galaxy S9 (Android 8)
* Fenix version: Nightly 4/7 (Build #20980610)

Screenshot:
**Add Search Engine - "Other" option - "Name" field**
![20200407_171433](https://user-images.githubusercontent.com/49859863/78680608-5f08ff80-78f4-11ea-8e87-00971201aad1.jpg)

**Add Search Engine - "Other" option - "Learn more" link**
![Screenshot_20200407-171614_Accessibility Scanner](https://user-images.githubusercontent.com/49859863/78681011-e0f92880-78f4-11ea-881b-79891e53658d.jpg)

**Comment by sflorean** [comment]
Verified as fixed on Firefox Nightly 7/7 with Samsung Galaxy Note10 (Android 10).
