### ISSUE TITLE
[Bug][a11y] Search-Touch target-"Show in private sessions" need to have the touch target resized

### ISSUE THREAD

**Issue by Diana-Rus** [mozilla-mobile/fenix#9776]
## Prerequisites
Have Google Accessibility Scanner installed.
### Steps to reproduce
1. Open app and tap on "Menu"/"Settings"/"Search".
2. Scan the "Search" module.
### Expected behavior
There are no suggestions to make any changes.
### Actual behavior
"Show in private session" option.
[0,2601][1440,2702]
This item's height is 29dp. Consider making the height of this touch target 48dp or larger.

### Device information

* Android device: Samsung Galaxy S9 (Android 8)
* Fenix version: Nightly 4/7 (Build #20980610)

**Screen:**
"Show in private session" option.
![Screenshot_20200407-165837_Accessibility Scanner](https://user-images.githubusercontent.com/49859863/78681946-0f2b3800-78f6-11ea-975c-90a6fad39cec.jpg)

**Comment by mcarare** [comment]
This was fixed. Can QA please verify? TY!

**Comment by sflorean** [comment]
Verified as fixed on the latest Nightly build 6/3 with Google Pixel 3 (Android 10) and LG G7 FIT (Android 8).
