### ISSUE TITLE
[Bug][a11y] Language-Touch target-Elements from the page need touch target resized

### ISSUE THREAD

**Issue by Diana-Rus** [mozilla-mobile/fenix#9779]
## Prerequisites
Have Google Accessibility Scanner installed.
### Steps to reproduce
1. Open app and go to Menu/Settings/Language.
2. Insert characters into the field. 
3. Scan screen.
### Expected behavior
There are no suggestions to make any changes.
### Actual behavior
Language - "Search language" search bar
- android:id/search_src_text
This item's height is 36dp. Consider making the height of this touch target 48dp or larger.

Language - "Close" button
- android:id/search_close_btn
This item's width is 40dp. Consider making the width of this touch target 48dp or larger.

Language - "Follow device language" default option
- [55,520][1385,656]
This item's height is 40dp. Consider making the height of this touch target 48dp or larger.
### Device information

* Android device: Samsung Galaxy S9 (Android 8)
* Fenix version: Nightly 4/7 (Build #20980610)

**Screen:**
**Language - Affected elements: "Search language" search bar, "Cancel" button and default option - "Follow device language"**
![screenshot_Firefox Nightly_2020-04-07-19_21_49edit](https://user-images.githubusercontent.com/49859863/78694856-f4f95600-7905-11ea-84bf-f984717b321c.png)

**Comment by eliserichards** [comment]
@AnishaSingh0118 is working on this in #18682
