### ISSUE TITLE
[Bug][a11y] Snackbar-Touch target-From bookmark snackbar "Edit" button touch target needs resizing

### ISSUE THREAD

**Issue by Diana-Rus** [mozilla-mobile/fenix#9780]
## Prerequisites
Have Google Accessibility Scanner installed.
### Steps to reproduce
1. Launch Fenix and open a website.
2. From the three-dot menu select to bookmark the page.
3. Scan the screen with snackbar displayed.
### Expected behavior
There are no suggestions to make any changes.
### Actual behavior
Add bookmark snackbar - "Edit" button
org.mozilla.fenix.nightly:id/snackbar_btn
This item's size is 34dp x 18dp. Consider making this touch target 48dp wide and 48dp high or larger.
### Device information

* Android device: Samsung Galaxy S9 (Android 8)
* Fenix version: Nightly 4/7 (Build #20980610)

**Screen:**
**Add bookmark snackbar - "Edit" button**
![Screenshot_20200407-200121_Accessibility Scanner](https://user-images.githubusercontent.com/49859863/78698685-5f60c500-790b-11ea-9135-03e6bb90e1f5.jpg)

**Comment by mcarare** [comment]
Closing this, as it's the same issue as : https://github.com/mozilla-mobile/fenix/issues/9594 verified as fixed. Same button on snackbar, different texts.
