### ISSUE TITLE
[Bug][a11y] Edit Bookmark-Touch target-"Name" & "URL" fields need slight resizing of target touch area

### ISSUE THREAD

**Issue by Diana-Rus** [mozilla-mobile/fenix#9781]
## Prerequisites
Have Google Accessibility Scanner installed.
### Steps to reproduce
1. Launch Fenix and open a website.
2. From the three-dot menu select to bookmark the page.
3. Tap on "Edit" from the confirmation snackbar.
4. Scan the "Edit bookmark" page.
### Expected behavior
There are no suggestions to make any changes.
### Actual behavior
"Edit Bookmark" module-Bookmark "Name" field
- org.mozilla.fenix.nightly:id/bookmarkNameEdit
This item's height is 41dp. Consider making the height of this touch target 48dp or larger.

"Edit Bookmark" module-Bookmark "URL" field
- org.mozilla.fenix.nightly:id/bookmarkUrlEdit
This item's height is 41dp. Consider making the height of this touch target 48dp or larger.
### Device information

* Android device: Samsung Galaxy S9 (Android 8)
* Fenix version: Nightly 4/7 (Build #20980610)

**Screen**
![Screenshot_20200407-201114_Accessibility Scanner](https://user-images.githubusercontent.com/49859863/78700186-bd8ea780-790d-11ea-9ecd-ea970b464b63.jpg)

**Comment by mcarare** [comment]
This appears to be fixed (by other changes). Can QA please verify? TY!

**Comment by sflorean** [comment]
Verified as fixed on the latest Nightly build 6/3 with Google Pixel 3 (Android 10) and LG G7 FIT (Android 8).
