### ISSUE TITLE
[Bug] Clean up unused FeatureFlags

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#9782]
We currently have quite a few feature flags going unused. We should go through each of these and remove any there are no longer necessary.

**Comment by grigoryk** [comment]
#10017 removes one of the flags, `asFeatureFxAPairingDisabled`.

**Comment by hakkikaancaliskan** [comment]
Exactly which ones needed to remove? Looks like just one of them unused.
https://github.com/mozilla-mobile/fenix/blob/7e6116512c354eb1d8524f8922f7970fe155c65c/app/src/main/java/org/mozilla/fenix/FeatureFlags.kt#L30

**Comment by NotWoods** [comment]
Fixed by 87a65d2
