### ISSUE TITLE
[Bug] Reducing Unnecesary Clicks in Search Engine Settings

### ISSUE THREAD

**Issue by nitin10s** [mozilla-mobile/fenix#9785]
### Actual behavior
As seen in the image, the search engine has just one menu option i.e. Delete, so it'll be better we put the delete icon outside rather than putting it inside a menu thus avoiding no. of clicks.

![Screenshot_20200407-222239](https://user-images.githubusercontent.com/16988558/78719836-39a2e280-7942-11ea-9d7e-9a50e9d5353e.png)

**Comment by apbitner** [comment]
Agreed, this would be consistent with how we're handling the new Downloads section as well. The 3-dot icon should only be used when there are multiple actions.
