### ISSUE TITLE
Add Search Engine settings in Settings

### ISSUE THREAD

**Issue by nitin10s** [mozilla-mobile/fenix#9786]
### Why/User Benefit/User Problem
A typical user expects all types of settings listed in the "Settings" menu option. Currently, to access the Search Engine Settings, the user needs to tap on the + icon and then click on the "Search Engine Settings". One similar option should be made available under the "Settings" tab.

**Comment by kbrosnan** [comment]
This issue is not clear from the description. It does not make sense for a setting to exist in multiple places.

**Comment by nitin10s** [comment]
I meant the Search Engine Settings would make sense if they are located in the overall Settings.

**Comment by liuche** [comment]
We're updating the menu in #14320
