### ISSUE TITLE
Go back without reloading the page

### ISSUE THREAD

**Issue by 90du** [mozilla-mobile/fenix#9791]
### Why/User Benefit/User Problem
Go back without reloading the webpage
### What/Requirements
Speed ​​up browser response
### Acceptance Criteria (how do I know when I’m done?)
Click to return, the webpage uses cache display

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-16728)

**Comment by kbrosnan** [comment]
Firefox should already do this. Though a large number of websites explicitly tell Firefox to not cache the website. This would need specific examples where the site is not sending a no-cache header and Firefox is not using the cache.

**Comment by lindongbin** [comment]
Sometimes the switching tab is not displayed immediately, but reloaded slowly

**Comment by buttercookie42** [comment]
> Though a large number of websites explicitly tell Firefox to not cache the website. This would need specific examples where the site is not sending a no-cache header and Firefox is not using the cache.

This sounds more like a bfcache issue, and AFAIK `no-cache` alone shouldn't prevent a page from getting into the bfcache, though `no-store` will, as do a few things other than cache-control headers, e.g. probably most commonly having `beforeunload` event handlers.
On devices with < 4GB RAM, we also potentially store less bfcache entries than on desktop, and generally on Android we also expire them more quickly after only a few minutes.

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813611

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
