### ISSUE TITLE
[Bug][a11y] ETP-Touch target-Toggle accessibility need resizing of the touch target

### ISSUE THREAD

**Issue by Diana-Rus** [mozilla-mobile/fenix#9796]
## Prerequisites
Have Google Accessibility Scanner installed.
### Steps to reproduce
1. Open app and make a search after a website.
2. Tap on the "ETP" icon.
3. Scan the search screen.
### Expected behavior
There are no suggestions to make any changes.
### Actual behavior
Enhanced Tracking Protection-Toggle accessibility
- org.mozilla.fenix.nightly:id/switch_widget
This item's height is 27dp. Consider making the height of this touch target 48dp or larger.
### Device information

* Android device: Samsung Galaxy S9 (Android 8), Sony Xperia Z5 (Android 7)
* Fenix version: Nightly 4/8 (Build #20990609)

**Screen**
**Enhanced Tracking Protection-Toggle accessibility**
![Screenshot_20200408-101143_Accessibility Scanner-edit](https://user-images.githubusercontent.com/49859863/78757225-d5edd900-7984-11ea-8f77-9f51064b88f4.jpg)

**Comment by mcarare** [comment]
Fixed in : https://github.com/mozilla-mobile/fenix/pull/11133.

**Comment by sflorean** [comment]
Verified as fixed on the Nightly build 6/3. Devices: Google Pixel 3 (Android 10) and LG G7 FIT (Android 8).
