### ISSUE TITLE
[Bug][a11y] Account Settings-Touch target-The "Device name" field needs a slight resizing in height

### ISSUE THREAD

**Issue by Diana-Rus** [mozilla-mobile/fenix#9797]
## Prerequisites
There are no suggestions to make any changes.
### Steps to reproduce
1. Open app and go to Menu/Settings/Account.
2. Sign in with a firefox account.
3. Tap on the logged account from "Account" section.
4. Tap on "Device name".
5. Scan the screen.
### Expected behavior
There are no suggestions to make any changes.
### Actual behavior
"Account Settings" module - "Device Name" field
- android:id/edit
This item's height is 45dp. Consider making the height of this touch target 48dp or larger.
### Device information

* Android device: Samsung Galaxy S9 (Android 8)
* Fenix version: Nightly 4/8 (Build #20990609)

**Screen**
**"Account Settings" module - "Device Name" field**
![Screenshot_20200408-121058_Accessibility Scanner](https://user-images.githubusercontent.com/49859863/78767513-5c111c00-7993-11ea-855f-b0a9c6bd97b7.jpg)

**Comment by sv-sdeiac** [comment]
Hi, I can confirm that this issue is fixed using the latest Firefox Preview Nightly build from 4/9.

Devices:
- Google Pixel 3 (Android 10);
- Samsung Galaxy Note 8 (Android 9).
