### ISSUE TITLE
[Meta] Multitasking

### ISSUE THREAD

**Issue by bbinto** [mozilla-mobile/fenix#98]
### Why/User Benefit/User Problem
- As a user, I want to browse to different websites simultaneously without having to close the current website 

### What / Requirements
- Allow user to open new tab/website
- Allow user to view and select a tab from a list of tabs

**Comment by st3fan** [comment]
If this is about using multiple tabs, I think pretty much everything is in place except screenshots on tabs in the tab manager. That is an outstanding bug in A-C which depends on GexkoView work.

**Comment by ARoomWithAMoose** [comment]
The tab queue feature of Firefox for Android is the number one feature that has kept me from migrating. From what I have seen, it is the only browser to support this. Is this being considered for implementation inf Fenix as well?

**Comment by bbinto** [comment]
Thanks @ARoomWithAMoose for bringing this up here. We will consider this feature for future releases, but probably not for MVP
