### ISSUE TITLE
[UX] Delete browsing data

### ISSUE THREAD

**Issue by brampitoyo** [mozilla-mobile/fenix#980]
### User Story

As a user, I want to quickly delete my browsing data – history, cookies, cache, etc. – whether it’s recent or from a long time ago.

(Private Browsing data can easily be deleted using a Floating Action Button, so it’s irrelevant for this issue).

Invision Spec:
https://mozilla.invisionapp.com/share/HNRJ99EF3E6

**Comment by brampitoyo** [comment]
Question:

A session is a time-bounded collection of tabs. Each tab contains one or a few history items.

We don’t provide the ability to delete session. Instead, the user is able to delete:

* Open tabs: which will delete the current session
* History: which will delete _all_ sessions within a time range

Does separating the notion of open tabs (session that’s currently open) and history (sessions that are in the past) make sense, or is it confusing?

@mheubusch may have more questions, as well.

**Comment by mheubusch** [comment]
@brampitoyo You can delete a session - if you select the three dot menu on each session (kabob) you can Delete or Send and share 
I think the question is if you delete a session should you also remove the sites/pages in the session from your browsing history? If you delete some part of your history, will it also remove that part from your Sessions?

**Comment by hmcgaw** [comment]
@brampitoyo are users still able to delete the browsing history from Library or are you suggesting that is revised as well?

**Comment by brampitoyo** [comment]
> […] if you delete a session should you also remove the sites/pages in the session from your browsing history?

This sounds like a clear “yes” to me. If you delete a session, all history items associated with that session should also be deleted.

> If you delete some part of your history, will it also remove that part from your Sessions?

Hypothetical corner case (which may very well be superficial):

I have a session with many tabs. Some tabs are >60 minutes old. Some tabs are <60 minutes old. Let’s say that I’m erasing history within the time range of an hour ago?

Do I expect my set of tabs to stay either 100% kept or 100% deleted if it belongs to a session, or is it okay if some tabs within a session are deleted, and some are intact?

I think the “100%” answer is the more correct one, because it’s cleaner. But if that’s the case, when a session sits right in the time boundary, should we err towards keeping it, or deleting it?

**Comment by mheubusch** [comment]
@bbinto @vesta0 Is there a corresponding Meta for Deleting All Browsing Data?  I can't find it but do you think it belongs in an existing feature, like Settings?

**Comment by bbinto** [comment]
There is not, I'd say settings is the best epic to assign it to, @mheubusch

**Comment by mheubusch** [comment]
@cpeterso Here are revised (and ugly) wireframes for our propsal to clear different types of data.  https://docs.google.com/presentation/d/1ZQcGlkmt9c9FU4Rh_81GA8cz7ZVFJ-kkl3uEnVhyTRs/edit?usp=sharing

What we'd like to know is 1. can GV support these categories? and 2. if not, can we meet to discuss what our options are?

**Comment by cpeterso** [comment]
GV does not currently have an API to delete browsing history separately from "cookies and site data". The team has some plans, but nothing decided or in progress. I can schedule a meeting to discuss.

Deleting just site permissions is possible because site permissions are managed by Fenix, not GV.

**Comment by AmyYLee** [comment]
@mheubusch @shorlander posted updated spec in description up top and moved card to Design Review.

**Comment by mheubusch** [comment]
@AmyYLee I don't think you posted the correct link - it is the old spec that bram designed.

**Comment by AmyYLee** [comment]
@mheubusch I updated the spec. Let me know if there's any additional edits. Thanks

**Comment by mheubusch** [comment]
@shorlander pls review

**Comment by boek** [comment]
@shorlander @AmyYLee Do we want tab collections to be a part of this UI? They are the only item in this list that isn't "browsing data".. To me it would be akin to having Bookmarks, or a read it later list in this section as well. I think collection management would be better suited to the Library.

**Comment by vesta0** [comment]
@shorlander @mheubusch would you please share the latest mocks on this? The current implementation does not map to any of the existing mocks and I'd like to know if the mocks have changed or if the implementation is incomplete.

**Comment by shorlander** [comment]
> @shorlander @mheubusch would you please share the latest mocks on this? The current implementation does not map to any of the existing mocks and I'd like to know if the mocks have changed or if the implementation is incomplete.

https://mozilla.invisionapp.com/d/main#/console/16853870/358010183/preview

Looks right to me. Although it is missing Search History.

**Comment by vesta0** [comment]
@mheubusch can we close this issue? Any enhancements can be tracked in a new issue.

**Comment by sblatz** [comment]
This is implemented, let's file follow-up issues if necessary :)
