### ISSUE TITLE
[Bug] The 3 dot menu section order is mirrored for top/bottom Nav bar

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/fenix#9802]
## Steps to reproduce
1. Launch Fenix.
2. Open any webpage.
3. Open the 3 dot menu and observe the position of each section.
4. Change the Toolbar to top
5. Open the 3 dot menu and observe the position of each section.

### Expected behavior
The Toolbar menu section position is the same for the top and bottom Toolbar.
### Actual behavior
The 3 dot menu section order is mirrored for top/bottom Nav bar.
### Device information

* Android device: **Google Pixel 4 XL (10).**
* Fenix version: **Nightly 4/8.**

Note that with the ability to change the Toolbar from top to bot having a different position for the menus can be confusing for the users when trying the Toolbar to top or bot.

![1x](https://user-images.githubusercontent.com/42831109/78785742-57a72c00-79b0-11ea-9368-2961a4eaf231.jpg)

![2x](https://user-images.githubusercontent.com/42831109/78785745-5970ef80-79b0-11ea-8cae-b7804889f0e6.jpg)

**Comment by kbrosnan** [comment]
@mozilla-mobile/ux would need to review this

**Comment by topotropic** [comment]
Thanks for the feedback. This is expected behavior – the bottom app bar design is designed to be thumb-friendly, to reach frequently used actions easy. The assumption here is also that people choose top or bottom and then stick with it and not change between them regularly.
