### ISSUE TITLE
[Bug][a11y] About Firefox- "Build Date" touch target element needs resizing 

### ISSUE THREAD

**Issue by Diana-Rus** [mozilla-mobile/fenix#9805]
## Prerequisites
There are no suggestions to make any changes.
### Steps to reproduce
1. Open app and go to Menu/Settings/About Firefox Nightly
### Expected behavior
There are no suggestions to make any changes.
### Actual behavior
"About Firefox Nightly" - "Build Date"
org.mozilla.fenix.nightly:id/build_date
This item's height is 22dp. Consider making the height of this touch target 48dp or larger.
### Device information

* Android device: Samsung Galaxy S9 (Android 8)
* Fenix version: Nightly 4/8 (Build #20990609)

**Screen:**
**"About Firefox Nightly" - "Build Date"**
![Screenshot_20200408-162158_Accessibility Scanner](https://user-images.githubusercontent.com/49859863/78789075-51677e80-79b5-11ea-8cf9-904cef1a0055.jpg)

**Comment by sflorean** [comment]
Verified as fixed on the latest Nightly build 6/3 with Google Pixel 3 (Android 10) and LG G7 FIT (Android 8). No suggestions were made when the "About Firefox Nightly" page was scanned.
