### ISSUE TITLE
[Bug]The cut for scrolling down is made under the Firefox Preview branding logo/text

### ISSUE THREAD

**Issue by sv-sdeiac** [mozilla-mobile/fenix#9808]
## Steps to reproduce
1. Open Firefox Preview;
2. Scroll down till the branding logo/text starts to disappear.

### Expected behavior
The cut is made between the branding logo/text and notification bar.

### Actual behavior
The cut is made between the branding logo/text and Top sites list.

### Device information
Android device:
- Google Pixel 3 (Android 10);
- Samsung Galaxy Note 8 (Android 9).

Fenix version: 4/8 #20990609.

- Old UI
![Screenshot_20200408-171436](https://user-images.githubusercontent.com/40264165/78797495-731a3300-79c0-11ea-8a8c-cd6d246f1d8a.png)

- New UI
![Screenshot_20200408-171403](https://user-images.githubusercontent.com/40264165/78797466-6695da80-79c0-11ea-9974-a8f00c159d1c.png)

**Comment by sblatz** [comment]
@AmyYLee what's the correct behavior here? This is a quick fix :)

**Comment by AmyYLee** [comment]
> @AmyYLee what's the correct behavior here? This is a quick fix :)

Hi,

Can you shorten the logo fade out so it disappears when top sites overlaps it? The goal is to no look like the logo is getting sliced when top sites move up. Thanks!

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly Build #21130610 from 4/22`** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)

► Video
![20200422-092805](https://user-images.githubusercontent.com/51314259/79948057-c5a52600-847b-11ea-9bc4-097b3b9f971a.gif)
