### ISSUE TITLE
[Bug][a11y] Error Page-Text Contrast-"Go back" button needs to have the text ratio increased

### ISSUE THREAD

**Issue by Diana-Rus** [mozilla-mobile/fenix#9809]
## Prerequisites
Have Google Accessibility Scanner installed.
### Steps to reproduce
1. Open app and go to "http://testsafebrowsing.appspot.com/s/phishing.html"
2. Scan the "Deceptive site issue" page.
### Expected behavior
There are no suggestions to make any changes.
### Actual behavior
"Deceptive site issue" Page - "Go back" button
- backButton
The item's text contrast ratio is 2.34. This ratio is based on an estimated foreground color of #97979A and an estimated background color of #E6E6EB. Consider using colors that result in a contrast ratio greater than 4.50 for small text, or 3.00 for large text.
### Device information

* Android device: Samsung Galaxy S9 (Android 8)
* Fenix version: Firefox Preview Nightly 4/3 (Build #20940609)

Screen:
![Screenshot_20200408-175759_Accessibility Scanner](https://user-images.githubusercontent.com/49859863/78799441-cee5bb80-79c2-11ea-80ae-06cac66928e0.jpg)

**Comment by mcarare** [comment]
Can UX provide another color scheme for this issue? 
It's related to the button in screenshot below:
![Screenshot_20200407-154236_Accessibility Scanner](https://user-images.githubusercontent.com/49859863/78670687-cf108900-78e6-11ea-9fc8-a6d86e9858cd.jpg)
TY!

**Comment by AmyYLee** [comment]
@brampitoyo I remember you had worked on these screens? Is this according to spec?

**Comment by brampitoyo** [comment]
Hi @mcarare. This screen is according to spec, and matches our text contrast requirement.

- Page text: Light Grey 10 `#f9f9fb`
- Button text: Ink 80 `#20123a`
- Button background: Light Grey 30 `#e0e0e6`
- Page background: Red 70 `#c50042`

Let’s check these values’ contrast ratios:

- Checking the button text against its background, our contrast value is 13.21:1.
- Checking the button background against the page background, our contrast value is 4.62:1 – which exceeds the suggested ratio of 4.50:1.
- Lastly, checking the page text against its background, our contast value is 5.78:1.

It seems as if the Accessibility Scanner was scanning an incorrect colour value of `#97979a`, which we don’t use anywhere on this error page?

**Comment by mcarare** [comment]
@brampitoyo Thank you for the details. I have checked, and indeed now the page uses the colors in specs. I have scanned again the screen and it no longer shows suggestions for the button. I am closing this.
