### ISSUE TITLE
Add docs page for campaigns and data collection by LeanPlum

### ISSUE THREAD

**Issue by liuche** [mozilla-mobile/fenix#981]
This blocks release to the general user population.

### Why/User Benefit/User Problem
We need to be transparent with users what 3rd party tools we're using to collect data, how we're using that data in case they want to know why they are being targeted for campaigns, and document that in a publicly visible place.

Not sure if Marketing would prefer to use a Wiki (which we've used in the past), or if it's too heavyweight to have a docs file that Marketing could push changes to.

### What / Requirements
In using a 3rd party data collection tool, we need to clearly document what LeanPlum is, what we are collecting and what campaigns the data would be used in.

### Acceptance Criteria (how do I know when I’m done?)
Documentation page w/ explanation of LeanPlum and current marketing campaigns.

**Comment by bbinto** [comment]
@st3fan and @boek - based on today's planning, this should be done by an engineer, if not, please let me know who I need to chase.

**Comment by bbinto** [comment]
@liuche can you point us to where this has be done for Fennec/Firefox iOS so we can re-purpose.

**Comment by liuche** [comment]
Here are the docs from Firefox iOS on LeanPlum: https://github.com/mozilla-mobile/firefox-ios/blob/master/Docs/MMA.md

And here is the [campaigns wiki](https://wiki.mozilla.org/Leanplum_Contextual_Hints) from Firefox iOS - unfortunately this is very out of date. I had discussed this w/ Maria but I don't think she's had time to work with Marketing to update this, so I'll need to follow up with the new PM for that.

**Comment by liuche** [comment]
@st3fan I see you're listed as the responsible party for the LeanPlum integration and events it the MVP document - this documentation should also be done as part of the MVP. I can't tell if it's tracked as part of MVP so just wanted to verify that it has the correct labeling.

**Comment by bbinto** [comment]
@st3fan and @liuche - assigned to me and will be done before MVP (it's in the MVP blacklog).

Thanks for flagging this.

**Comment by bbinto** [comment]
@vesta0 feel free to move this into the next sprint, starting April 11.

**Comment by vesta0** [comment]
@bbinto I have moved this item to the current sprint.

**Comment by bbinto** [comment]
@boek or @colintheshots - I've started this document, but I would need one of you or @st3fan to verify some of the hard coded pieces (I added a note for each section I need a review from the engineer who implemented this)

https://github.com/mozilla-mobile/fenix/blob/master/docs/mma.md

**Comment by vesta0** [comment]
@mheubusch what is the status of this ticket?

**Comment by vesta0** [comment]
@st3fan please verify the hard coded pieces in the LeanPlum documentation: https://github.com/mozilla-mobile/fenix/blob/master/docs/mma.md

**Comment by sblatz** [comment]
Is this engineering work? If so is it ready to be worked on?


@vesta0, @sarentz

**Comment by liuche** [comment]
I also see a bunch of events in this [LeanPlumMetricsService file](https://github.com/mozilla-mobile/fenix/blob/master/app/src/main/java/org/mozilla/fenix/components/metrics/LeanplumMetricsService.kt#L15), but no documentation of them in `MMA.md` or `telemetry.md`. Are they being used?

This probably doesn't require a lot of cleanup, and just a little clarification in the docs, but it's not clear to me what LeanPlum data is being collected.

**Comment by liuche** [comment]
Just want to summarize a discussion that I had with Vesta and Jeff here:

1. Document the rest of the probes that are currently being collected. I believe these are:
* E_ADD_BOOKMARK
* E_OPENED_BOOKMARK
* E_REMOVED_BOOKMARK
* E_OPENED_APP
* Uninstall (which might just be automatic)

2. Continue adding probes from the [MVP list](https://docs.google.com/spreadsheets/d/1vp3Km7qyyAvkDiUQ3b4lRQUFyA7DQixR8xP1VadA4iw/edit#gid=1742911874)

I will send out an update for Data Steward sign-off, but since I'm going on PTO I will find another data steward to make sure 2 is properly documented.

**Comment by mmccorks** [comment]
All Leanplum events have corresponding entries in https://github.com/mozilla-mobile/fenix/blob/master/docs/mma.md
