### ISSUE TITLE
[Bug] Unable to connect Snackbar not showing in customTab with bottom toolbar

### ISSUE THREAD

**Issue by ValentinTimisica** [mozilla-mobile/fenix#9812]
First check #8412 steps to reproduce.

### Steps to reproduce
- Make Fenix default browser (`Settings`->`Set as default browser`)
- Set toolbar to bottom (`Settings`-> `Customize`).
- From the gmail app send a mail with this link: https://www.fonvirtual.com/en/international-phone-number/
- Go to gmail app and access that link. Should be opened in a Fenix custom tab.
- From the top of the screen tap on `Click to Speak`, near the phone number.

### Expected behavior
- Snackbar with the message `Unable to connect. Unrecognizable URL scheme` should show
### Actual behavior
- Nothing happens

### Additional info
- [Video](https://drive.google.com/file/d/1TRlzXKQjO4f9DMBRBlpFOkD1NBuaeSCs/view?usp=sharing) with the bug
- Note that if the toolbar is set to Top, the Snackbar is showing properly, as you can see in the video above.
- It may be related to #8899, so this bug should be checked and also re-tested.

### Device information
- Android device: Samsung Galaxy Note 10 (Android 10)

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly 201218`** using the following devices:
• Google Pixel 3a (Android 11)
• Huawei Mate 20 Lite (Android 10)
• OnePlus A3 (Android 6.0.1)

► Video
![20201218-123041](https://user-images.githubusercontent.com/51314259/102604794-604e2580-412d-11eb-8614-e74775279688.gif)
