### ISSUE TITLE
[Bug] Zooming in then zooming out causes some sites to scroll horizontally

### ISSUE THREAD

**Issue by SL-Lee** [mozilla-mobile/fenix#9813]
## Steps to reproduce

1. Visit certain sites like https://bugzilla.mozilla.org/show_bug.cgi?id=1628413.
2. Zoom in, then zoom out fully.

### Expected behavior

The site doesn't scroll horizontally after zooming out fully.

### Actual behavior

The site scrolls horizontally after zooming out fully.

This behavior doesn't reproduce with Firefox Preview (4.2.1), so this is likely caused by the dynamic toolbar.

So far, I have only observed this behavior in Bugzilla bug entries like https://bugzilla.mozilla.org/show_bug.cgi?id=1628413 and https://example.com.

* Firefox Preview Nightly:

  ![](https://user-images.githubusercontent.com/45960387/78821945-d6ca4d80-7a0c-11ea-8fc6-57c64695132b.gif)

* Firefox Preview:

  ![](https://user-images.githubusercontent.com/45960387/78821968-e34ea600-7a0c-11ea-9e7c-9b5e96863ad7.gif)

### Device information

* Android device: Oppo Reno 2, Android 9
* Fenix version: Nightly 200405 18:01 (Build #20961811)

**Comment by LaurentiuApahideanSV** [comment]
I can confirm that this issue is reproducible using the latest version of Firefox Preview Nightly 4/8 (Build #20990610).

Devices:
OnePlus 6T (Android 9);
Huawei MediaPad M3 lite 10 (Android 7.0)

**Comment by Diana-Rus** [comment]
Hello @SL-Lee , as mentioned in [comment](https://github.com/mozilla-mobile/fenix/issues/10479#issuecomment-656109914) i'll be closing this one as the other has been triaged, but thank you for reporting 😊.

**Comment by hiikezoe** [comment]
cc @karlcow, we may already have webcompat reports for this issue.

**Comment by brainard52** [comment]
I am experiencing this with Build #2015757667.

**Comment by patel-malav** [comment]
Other websites to test the same issues 

- [example.com](example.com)
- [svelte.dev](svelte.dev)
