### ISSUE TITLE
[Bug] "Open in Firefox Preview" from Custom Tab opens home page not tab

### ISSUE THREAD

**Issue by ekager** [mozilla-mobile/fenix#9815]
## Steps to reproduce
1. Open any website in custom tab
2. Open menu and click "Open in Firefox Preview"

### Expected behavior
Webpage opens in app

### Actual behavior
App opens to home screen

### Device information

* Android device: ?
* Fenix version: ?

**Comment by mcarare** [comment]
For me the tab is opened, but without navigating to it.

**Comment by ekager** [comment]
Right, it should navigate to it.

**Comment by ekager** [comment]
CC @pocmo I'm not positive, just started digging around, but could this be a regression from https://github.com/mozilla-mobile/fenix/pull/8823 ? It was the only recent change to intent processing I found (and nothing with the `OpenInFenixIntent` was changed).

Looks like it's being processed as an `OTHER` intent (with a `null` processor). Should we be adding another custom extra here for HomeActivity to process and open to the browser correctly?

**Comment by apoorv9990** [comment]
Hi, I would like to work on this. I tried to repro it but not sure how to open a custom tab on the Firefox app  :sweat_smile:. Any pointers would be helpful.

**Comment by linuxandria** [comment]
> Hi, I would like to work on this. I tried to repro it but not sure how to open a custom tab on the Firefox app 😅. Any pointers would be helpful.

Open a link in an app that uses custom tabs, eg Telegram

**Comment by liuche** [comment]
We'll add it to our sprint, and the eng work here is to shepherd it along and make sure it's making progress.

**Comment by pocmo** [comment]
Just landed a patch for this and it should get into the next Nightly build of Fenix.

**Comment by softvision-miralobontiu** [comment]
Verified as fixed on the latest Nightly build from 5/29 with:
* OnePlus 5T (Android 9),
* Google Pixel (Android 10), and
* Sony Xperia Z5 Premium (Android 7.1.1).
