### ISSUE TITLE
[Bug] UriOpenedObserver not registered for restored sessions

### ISSUE THREAD

**Issue by BranescuMihai** [mozilla-mobile/fenix#9816]
## Steps to reproduce
Add one or more tabs (sessions)
Close the app
Restart the app

### Expected behavior
The `UriOpenedObserver` registers itself for restored sessions

### Actual behavior
The `UriOpenedObserver` doesn't register itself for restored sessions. 

### Device information
* Android device: All
* Fenix version: Latest develop

### Engineering notes
This happens because the restoring is done in `Core.kt` -> init of `SessionManager` (lazy init, first called in `FenixApplication` - `setupInMainProcessOnly()`), while the `UriOpenedObserver` is initiated much later, when we go to the `BrowserFragment`.

**Comment by ekager** [comment]
Thanks for filing! We investigated and decided the core of this issue was that we aren't registering on selected sessions or the first selected session. So we've added those and this should be fixed!
