### ISSUE TITLE
[Bug] Different menus are displayed on a11y with "Allow screenshots in PB" disabled

### ISSUE THREAD

**Issue by sv-sdeiac** [mozilla-mobile/fenix#9819]
### Prerequisites
Accessibility scanner enabled.

## Steps to reproduce
1. Open Firefox Preview;
2. Disable the "Allow screenshots in private browsing" from the settings;
3. Open the Private Browsing mode;
4. Open the 3dot menu;
5. Make a screenshot using the Accessibility scanner.

### Expected behavior
A blank screenshot is made.

### Actual behavior
The 3dot menu is displayed.

### Device information
Android device:
- Google Pixel 3 (Android 10);
- Samsung Galaxy Note 8 (Android 9);
- LG g7 fit (Android 8.1).

Fenix version: Firefox Preview Nightly debug build 4/9 #21000923.

#### Notes:
- It seems that this issue is reproducible using different scenarios. Other places where the issue can be reproducible are: Add private browsing shortcut, 3dot menu on different pages, 3dot menu from the private custom tab.
![Screenshot_20200409-145502](https://user-images.githubusercontent.com/40264165/78895736-03677f00-7a78-11ea-90a5-e1ae70fbca74.png)
![Screenshot_20200409-150759](https://user-images.githubusercontent.com/40264165/78895855-3578e100-7a78-11ea-8ab1-eba09c5a0f3e.png)
![Screenshot_2020-04-09-15-29-45](https://user-images.githubusercontent.com/40264165/78895914-4b86a180-7a78-11ea-85b1-ad81ed839e1d.png)

**Comment by jcsteh** [comment]
I might be misunderstanding something here, but I'm not sure we should consider this a bug. I assume disabling "Allow screenshots in private browsing" is supposed to disable Android screenshot functionality. However, the Accessibility Scanner runs as an accessibility service and requests appropriate permissions when installed. An accessibility service inherently requires access that some other things don't. For example, a screen reader can read text on the screen for all apps. Preventing an accessibility service (again keeping in mind that it requests permissions when installed) from accessing things could break legitimate functionality for users who need that service.

CC @asadotzler for additional thoughts, if any.

**Comment by jcsteh** [comment]
Although I still think it's reasonable for an accessibility service to have this access, the [Accessibility Scanner documentation](https://support.google.com/accessibility/android/faq/6376582?hl=en-GB) notes that secure screens should be blank:

> If your app has a window that is declared 'secure' (using WindowManager.LayoutParams.FLAG_SECURE) Accessibility Scanner can't capture an image of the screen or check colour contrast. For these windows, Accessibility Scanner shows a black screen after scanning your app. However, you can still read the scan results for other opportunities.

I guess maybe the document content has this flag, but the UI doesn't somehow?

Either way, I think this is a p3, given the permissions requested by accessibility services and the fact that the actual private web page is not shown.

**Comment by mcarare** [comment]
Removing the a11y label, as this is not actually an a11y issue, because the same menu can be captured using any screen recorder. The problem was reported and fixed for other parts of the app: https://github.com/mozilla-mobile/fenix/issues/9987.
