### ISSUE TITLE
Onboarding - Action Card: Data Collection/Privacy Notice

### ISSUE THREAD

**Issue by boek** [mozilla-mobile/fenix#982]
As a user, I'd like to know what information I am sharing with my browser, so I can be in charge of my data.

### Requirements
-Notification to let users know about the default telemetry state and how to change it
-This will show once on first launch

### Acceptance Criteria:
-I see a notification that tells me what data I am sharing with Mozilla and how to change it. how to change what data I share with Mozilla

**Comment by AmyYLee** [comment]
Currently in Fennec, this is a system notification that appears after you open Firefox for the first time. Unless there is a reason why we want to change it and move it into onboarding (@shorlander), I think we can keep the same behaviour and the notification would take you to Fenix Settings -> Data choices screen.

**Comment by AmyYLee** [comment]
@boek Do you need strings for this?

**Comment by boek** [comment]
@AmyYLee That sounds good to me! I do 👍

**Comment by AmyYLee** [comment]
Hi Michelle, we need copy for the the Firefox stats & data permissions prompt when you first install Firefox. This is what we currently have in Fennec. Do we need to make changes for Fenix? @mheubusch 
![Screenshot_20190403-165225](https://user-images.githubusercontent.com/5992746/55512413-16f43480-5631-11e9-98de-8fecbd280be1.png)

**Comment by mheubusch** [comment]
@AmyYLee is this the Android prompt that includes granting permission for telemetry and mozilla location services?

**Comment by mheubusch** [comment]
@AmyYLee also, are we using leanplum to trigger this prompt?

**Comment by MeridelW** [comment]
@AmyYLee Do you know if the header copy can be changed? I looked through Android dev docs and Material Design and didn't see the "Data & Stats" notification as a pre-set message.

Assuming we CAN adjust the header, here's the proposal:

**Header:** [Fenix/Insert final product name] Data Collection
**Body:** To improve performance and stability for all users, [Fenix/final product name] collects information about how you use our product. 
**Link:** Choose what to share

**Comment by AmyYLee** [comment]
> @AmyYLee is this the Android prompt that includes granting permission for telemetry and mozilla location services?

I believe so. It should take the user to this page:
![Screenshot_20190405-172156](https://user-images.githubusercontent.com/5992746/55657416-248ff280-57c8-11e9-975b-3f218c3cac1e.png)

This is where the Fennec version currently takes the user to:
![Screenshot_20190405-172130](https://user-images.githubusercontent.com/5992746/55657428-307bb480-57c8-11e9-888a-d474e2bb7091.png)

**Comment by AmyYLee** [comment]
> @AmyYLee also, are we using leanplum to trigger this prompt?

I'm not sure. @boek - Are you able to answer this?

**Comment by boek** [comment]
No, we would be sending it ourselves locally through the app

**Comment by MeridelW** [comment]
Thanks, @AmyYLee, for the context and answers. I talked with Michelle and the content I provided will work for the permission prompt. Can you please update the designs with this copy?

Header: Data Collection
Body: To improve performance and stability for all users, [Fenix/final product name] collects information about how you use our product.
Link: Choose what to share

**Comment by AmyYLee** [comment]
This is a system notification so I don't think designs are needed, only string updates @boek correct me if I'm wrong. Please see above comment for the new strings. Thanks!

**Comment by georgf** [comment]
Note that the "health report" does not exist anymore - we moved over to Telemetry on mobile as well as Desktop.

FWIW, Firefox Desktop now doesn't mention "Telemetry" or "Healthreport" anymore, *"Allow Nightly to send technical and interaction data to Mozilla"* is what controls sending this data.

<img width="702" alt="Screen Shot 2019-04-10 at 19 01 28" src="https://user-images.githubusercontent.com/407696/55898605-42dc6080-5bc3-11e9-8c3c-ebd0c98829d5.png">

**Comment by mheubusch** [comment]
Updating this to change the feature to a panel in the onboarding tour:
<img width="246" alt="image" src="https://user-images.githubusercontent.com/20115914/57800783-d26fb480-7717-11e9-9877-c88048cac1c3.png">

**Comment by softvision-miralobontiu** [comment]
Verified as fixed on the latest build 1.0.1921 (11420606), with:
- Sony Xperia Z5 Premium (Android 7.1.1),
- Nexus 5 (Android 6.0.1),
- Sony Xperia Z2 tablet (Android 6.0.1),
- HTC 10 (Android 8).
