### ISSUE TITLE
Long Press Share

### ISSUE THREAD

**Issue by st3fan** [mozilla-mobile/fenix#9820]
> From https://bugzilla.mozilla.org/show_bug.cgi?id=1627647

Steps to reproduce:

When long pressing an image, there is not an option to 'share' on Preview, Preview Nightly, nor Firefox Nightly. Has this feature been 100% removed, or are there plans to bring it back it? I personally find this very hand to have in a browser when sharing content.

Actual results:

Long Press only gives option to open image in new tab, Save Image, and Copy Image Location

Expected results:

I expected to have an additional option to share the image 'as-is' directly

**Comment by Poopooracoocoo** [comment]
would be great if the title mentioned that it's about sharing _images_  :)

**Comment by cousteaulecommandant** [comment]
This option was very useful and convenient and one of the things I loved from Firefox; I hope it's just in the to-do list and not gone for good because it was very convenient to share images without having to save them first.

**Comment by kbrosnan** [comment]
Duplicate #7458
