### ISSUE TITLE
Change the height and color of the progress bar

### ISSUE THREAD

**Issue by 90du** [mozilla-mobile/fenix#9821]
### Why/User Benefit/User Problem
The color of the progress bar is too conspicuous and relatively high, giving me the illusion that the page is loading slowly
### What/Requirements
Change the color of the progress bar, reduce the height of the progress bar
### Acceptance Criteria (how do I know when I’m done?)
My eyes are no longer attracted by the progress bar

**Comment by eliserichards** [comment]
Closing as a duplicate
