### ISSUE TITLE
[Bug] Unable to zoom map on covid19.geo-spatial.org

### ISSUE THREAD

**Issue by denschub** [mozilla-mobile/fenix#9822]
## Steps to reproduce

1. Open https://covid19.geo-spatial.org/dashboard/main
2. Scroll down to the map
3. Attempt to zoom

### Expected behavior

1. Map is zoomed in.

### Actual behavior

1. The whole page appears to be zoomed in. Sometimes, nothing happens.

It's worth nothing that this site appears to be fine in Fennec.

### Device information

* Android device: (emulator)
* Fenix version: Firefox Preview Nightly 200401

**Comment by LaurentiuApahideanSV** [comment]
I can confirm that this issue is reproducible using the latest version of Firefox Preview Nightly 4/8 (Build #20990610).

Devices:
OnePlus 6T (Android 9);
Huawei MediaPad M3 lite 10 (Android 7.0)

**Comment by Juraj-Masiar** [comment]
Another example is Slovak weather radar map:
http://www.shmu.sk/sk/?page=1&id=meteo_radar&mt=5
Double-tap will zoom, but it's impossible to un-zoom using pinch-to-zoom.

**Comment by denschub** [comment]
This issue is still valid.
