### ISSUE TITLE
[Bug] PWA sites are not detected anymore 

### ISSUE THREAD

**Issue by klint** [mozilla-mobile/fenix#9824]
## Steps to reproduce
Navigate to www.lemonde.fr (or any other PWA-enabled site)

### Expected behavior
A blue dot is shown on the menu and the Install option is available

### Actual behavior
No blue dot is shown on the menu and the Install option is not available (but the Add to homescreen option is there)

### Device information
Remdi Note 6
* Android device: 9
* Fenix version:  #2015732819

**Comment by kbrosnan** [comment]
Dupe #9692
