### ISSUE TITLE
View Quick Action Bar

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/fenix#984]
## User Story (Added by PM)

As a user, I want easy to access shortcuts common browser actions on a site (Share, Download, Bookmark, Read)
As a user I want to see that there is a Quick Action Bar and easily view or hide it so I can be efficient in my browsing.
As a user, I want an indication or feedback that Fenix completed an action.

## Dependencies (Added by PM and Eng)
- [x] UX: #182 

## Next Steps 
- Engineers need to breakdown the user story, size all the individual tasks, and link the tasks to this user story (done by Eng on Sprint Planning day)

### Acceptance Criteria (Added by PM)

I have shortcuts to common browser actions on a site (Share, Download, Bookmark, Read)
I can see that the browser has a quick action bar hidden behind the primary toolbar.
I can swipe up to pull Quick Action Bar into view so I can choose an action.
I can swipe down to collapse the Quick Action bar so I can go back to browsing.
I can see relevant feedback from Fenix after I choose an action.

**Comment by bbinto** [comment]
- We've decided in the sprint planning to time-box this work to 12 hours 
- The goal of this ticket is to start iterating on this feature and use it as a prototype for further investigation and usability issues.

**Comment by sblatz** [comment]
Do we want telemetry for the quick action bar?

**Comment by bbinto** [comment]
Yes, @sblatz - added this: https://github.com/mozilla-mobile/fenix/issues/1195

**Comment by sv-ohorvath** [comment]
The UI of the quick action bar was verified on Fenix nightly.
Devices:
Pixel (Android 9)
Nexus 5 (Android 6) 

Can I close this issue?

**Comment by sblatz** [comment]
Thanks for verifying, @sv-ohorvath 😄
