### ISSUE TITLE
[Bug] Ublock origin, My filters, Export button do nothing

### ISSUE THREAD

**Issue by wijayafamily** [mozilla-mobile/fenix#9841]
## Steps to reproduce
1.Settings
2.Add-ons
3.uBlock origin
4.Settings
5.My filters
6.Click on the Export(it is on the middle top right, the one arrow up)
### Expected behavior
it will start downloading filters
### Actual behavior
nothing happened
### Device information

* Android device: SM-N960F Android 10 april patch.
* Fenix version: Nightly 200405 18:01

**Comment by csadilek** [comment]
@wijayafamily Thanks for filing! This should work now after the fixes for https://github.com/mozilla-mobile/fenix/issues/8155.

I just tried on Nightly 200422 16:13. If you have filters the button with "arrow up" allows you to download the filters as a file. The button with "arrow down" allows you to select a file and import filters.
