### ISSUE TITLE
[Bug] Unable to use Clean Share with latest version of Firefox Beta on Mobile

### ISSUE THREAD

**Issue by darshitpp** [mozilla-mobile/fenix#9848]
## Steps to reproduce
If you have the [Clean Share](https://play.google.com/store/apps/details?id=com.catchingnow.share) App installed, just select it while sharing a web page from the Share Menu
### Expected behavior
Clean Share App should open as some sort of overlay which would provide its internal sharing options
### Actual behavior
The expected overlay does not open, and trying it for the second time opens it just for a moment (which is not enough to take a screenshot)
### Device information

* Android device: Samsung Galaxy Note 9 `SM-N960F`
* Fenix version: Firefox Beta `75.0.0-beta.4`

Let me know if you require any more information

**Comment by xcffl** [comment]
Confirm here. But actually Clean Share doesn't provide a custom share overlay. It simply uses system's share sheet.

**Comment by softvision-miralobontiu** [comment]
I wasn't able to reproduce this issue anymore on 10/20 Nightly build, Beta 82.0.0-beta.6, nor on RC 82.1.0-RC.2 build, using a Samsung Galaxy Note 8 (Android 9).
Please feel free to file a new issue if you encounter this again.
Thank you!

**Comment by darshitpp** [comment]
The issue still persists for me.

I am using Firefox `Beta 82.0.0-beta.6` on Samsung Galaxy Note 9 with Android 10.
