### ISSUE TITLE
[Bug] Switching to a new tab, opens the "parent" page briefly

### ISSUE THREAD

**Issue by softvision-miralobontiu** [mozilla-mobile/fenix#9849]
## Steps to reproduce
1. Go to a website that has multiple links, like cnn.com, bbc.com, news.google.com, etc.
2. Long-tap on a link and select to open it in a new tab/new private tab.
3. Tap on the "Switch" option.
4. Observe the newly opened tab.

### Expected behavior
The newly opened tab displays the link from step 2.

### Actual behavior
The same page from step 1 is displayed shortly, then the page from step 2 is loading.
On yahoo.com, it opens yahoo.com again, the user isn't redirected to the new link at all.

### Device information
* Android devices: Google Pixel (Android 10), Nokia 6 (Android 7.1.1), HTC 10 (Android 8),
* Fenix version: a created build version 1.0.2015 (39.0.20200409130114, 52ca085fb), with GV 77.0a1,
* Not reproducible on wikipedia.org  
* Please see the attached GIF
![cnn_Trim](https://user-images.githubusercontent.com/40694158/78990928-599ff500-7b40-11ea-8cfe-201ac72b6b56.gif)

**Comment by softvision-miralobontiu** [comment]
Not reproducible on the 1.0.2015 (39.0.20200409130114, 52ca085fb) Beta debug build with GV 76.0-20200407205853.

**Comment by topotropic** [comment]
@softvision-miralobontiu can we close this? Thanks!

**Comment by softvision-miralobontiu** [comment]
I'll close this since I'm unable to reproduce it on the latest Nightly build from 7/8 with Xiaomi Mi 8 Lite (Android 9).
