### ISSUE TITLE
[Bug] 3rd party password manager app is not recognized only after opening a new tab/restarting Fenix (if setting it after launching fenix)

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/fenix#9854]
## Steps to reproduce
1. Launch Fenix.
2. Access twitter.com. (no 3rd party password manager pop-up is displayed).
3. Reach the device settings and set any 3rd party password manager app as default.
4. Resume Fenix and refresh the open webpage.
5. Tap on the username or password field in order to the 3rd party password manager app pop-up to be displayed.
### Expected behavior
The 3rd party password manager app pop-up to be displayed and the autofill for the desired account ca be done.
### Actual behavior
No pop-up is displayed until re-opening a new website.
### Device information

* Android device: **Google Pixel 4 XL (10)**
* Fenix version: **Debug from latest Master 4/10.**

![20200410-184027-1](https://user-images.githubusercontent.com/42831109/79004070-aa254b80-7b5c-11ea-8f2c-2dbc83e380a6.gif)

**Comment by hakkikaancaliskan** [comment]
This looks fixed on latest nightly.
