### ISSUE TITLE
[Bug] "Successfully installed uBlock Origin" is not aligned with the device navigation bar

### ISSUE THREAD

**Issue by Diana-Rus** [mozilla-mobile/fenix#9856]
## Steps to reproduce
1. Open Fenix and go to "Settings"/"Add-ons".
2. Install uBlock Origin addon by tapping on the "+" button .
3. From the "Add uBlock Origin" pop up tap on "Add".
### Expected behavior
The "Successfully installed uBlock Origin" snackbar is displayed correctly.
### Actual behavior
The snackbar is not aligned with the navigation bar.
### Device information

* Android device: Samsung Galaxy S9 (Android 8)
* Fenix version: debug build based on master with(39.0.20200409130114, 52ca085fb) -  GV: 77.0a1-20200408033650

GIF:
![20200410-191305](https://user-images.githubusercontent.com/49859863/79006766-8a912180-7b62-11ea-8259-0edc36671bbd.gif)

Note: It may impact https://github.com/mozilla-mobile/fenix/issues/9196

**Comment by csadilek** [comment]
Closing as we no longer have the "successfully installed" snackbar. It was replaced with this dialog: https://github.com/mozilla-mobile/fenix/issues/10398#issuecomment-624313139
