### ISSUE TITLE
[webcontent] Unable to toggle bootstrap menu at  www.mepz.gov.in 

### ISSUE THREAD

**Issue by miketaylr** [mozilla-mobile/fenix#9859]
Originally filed at https://github.com/webcompat/web-bugs/issues/51348

(TP doesn't make a difference here)

STR:

1. navigate to http://www.mepz.gov.in/#
2. click the hamburger menu
3. try to expand the SEZ menu item (you have to click on the chevron icon to the right)

Expected: the menu item toggles open, and some content is displayed
Actual: it doesn't open.

This works in Fennec, and Chrome Mobile.

It seems like the span with the click handler never gets the event, for some reason:

https://github.com/webcompat/web-bugs/issues/51348#issuecomment-612180140

**Comment by LaurentiuApahideanSV** [comment]
Using a OnePlus 6T (Android 9) I am unable to reproduce the issue on Firefox Preview Nightly 200505, however the issue does occur on Beta 76.0.0-beta.1 and Release 4.3.0.
