### ISSUE TITLE
Google AMP support

### ISSUE THREAD

**Issue by aliglelo** [mozilla-mobile/fenix#9862]
### Amp is faster
I wan to ask about Firefox's plans about [Google AMP](https://developers.google.com/amp) support for Firefox Preview.
### We want AMP Results in Google in Firefox Preview
I Used Firefox Lite Browser which does support Google Amp but when i used Firefox Preview I noticed that Amp Results are not being listed in google.
### When we will see AMP results in Google 
When we will see AMP results in Google we will be  very pleased to use preview with more efficiency and at a faster speed.

**Comment by kbrosnan** [comment]
AMP is something that websites/web servers support. If they want to send AMP pages to Firefox then that is up to them.
