### ISSUE TITLE
[Bug] Pull to refresh is too aggressive in some situations 

### ISSUE THREAD

**Issue by emilio** [mozilla-mobile/fenix#9863]
## Steps to reproduce

 * visit a desktop page like https://bugzilla.mozilla.org/show_bug.cgi?id=1528305
 * scroll down.
 * try to scroll up.

### Expected behavior

 * I can scroll up, and pull to refresh comes up only if I over scroll.

### Actual behavior

 * Pull to refresh shows up as soon as I try to scroll up, preventing me from scrolling.

### Device information

* Android device: Samsumg Galaxy A20
* Fenix version: Nightly 20200403063228

Drive-by, pull to refresh is also very aggressive when zooming out `about:support` for example.

**Comment by emilio** [comment]
ahh, apparently you need to zoom in in bugzilla for the bug to happen

**Comment by LaurentiuApahideanSV** [comment]
The issue has also been reported here: https://github.com/mozilla-mobile/fenix/issues/9766. I will close this issue as it will he handled there.
