### ISSUE TITLE
Websites extend past the screen size

### ISSUE THREAD

**Issue by Dimas-sc** [mozilla-mobile/fenix#9864]
With Firefox Preview and the new Firefox Beta 75 for Android some pages are broken.

## Site with issue and any steps to reproduce
espancid.com

### Expected behavior
Text fits inside the screen.

### Actual behavior
With the new Firefox the carousel at the top, the title, etc.. are bigger than it should be. The second and third sliders don't feed the screen.

### Does toggling Tracking Protection fix the issue? (Press the lock icon in the toolbar while on the site to see toggle)
No

### Can you reproduce in [Firefox for Android]?
No

### Can you reproduce in Chrome (or other non-Mozilla browser)?
No

### Device information
* Android device: LG G7 Android 9
* Fenix version: 75 beta 4

**Comment by sflorean** [comment]
@Dimas-sc tested on the latest Nightly and couldn't see any difference between Chrome and Fenix. Is this still an issue for you? Could you please take a screenshot Fenix vs Chrome?

**Comment by Dimas-sc** [comment]
At the left Firefox nightly, at right Chrome

El dl., 13 d’abr. 2020, 18:25, Sorina Florean <notifications@github.com> va
escriure:

**Comment by Dimas-sc** [comment]
Firefox Nightly 77a at left, Chrome at right
![20200413_185720-COLLAGE](https://user-images.githubusercontent.com/2415679/79140900-05537a00-7db9-11ea-8675-2d80c90837b8.jpg)

**Comment by Dimas-sc** [comment]
I checked with the new nightly 77.0a1-20200410 and same problem

**Comment by AndiAJ** [comment]
The above mentioned website is displayed the same way as on Chrome.
Checked it on the latest Nightly Build 201103 using the following devices:
• Google Pixel 3a (Android 11)
• Huawei Mate 20 Lite (Android 10)
• OnePlus A3 (Android 6.0.1)

**Comment by Dimas-sc** [comment]
That's not true @AndiAJ , reopen the issue please!

Tested again with Chrome 86.0.4240.110 with a LG G7 (Android 10), as before, it displays OK:
![imatge](https://user-images.githubusercontent.com/2415679/98028283-2ee3f980-1e0e-11eb-930b-81d2022e8b25.png)

With Firefox 83.0.0-beta.2 appears the same issue!

**Comment by Dunexus** [comment]
@Dimas-sc Could you re-test using nightly ? It is where fixes lands first before coming to beta and then release, maybe the fix isn't in beta yet.

**Comment by AndiAJ** [comment]
Thx @Dunexus ! 
@Dimas-sc I would kindly ask you to check this matter on the latest nightly build.

**Comment by Dimas-sc** [comment]
Same issue with latest Nightly (84.0a1-20201101):
![imatge](https://user-images.githubusercontent.com/2415679/98081969-52438e80-1e78-11eb-9390-fe9cfc985444.png)

![imatge](https://user-images.githubusercontent.com/2415679/98082052-6c7d6c80-1e78-11eb-924d-bfc256de3cc2.png)

**Comment by AndiAJ** [comment]
@Dimas-sc I've checked on Chrome and it **looks the same**.
Most likely it's a website related issue

![rsz_screenshot_20201104-095400](https://user-images.githubusercontent.com/51314259/98084135-0a2a6900-1e84-11eb-829f-23bfb4184c20.png)

**Comment by Dimas-sc** [comment]
It's strange that on the same device there's no issue with Chrome and the old Firefox, but with Fenix it doesn't look well. But I've tried on another device and it's true, it looks bad with Chrome too. It really seems a website issue, sorry for that.
