### ISSUE TITLE
[Bug] Can't download subtitles on opensubtitles (zip is html)

### ISSUE THREAD

**Issue by moronigranja** [mozilla-mobile/fenix#9866]
## Steps to reproduce

Go to opensubtitles.org, download any subtitle for a movie.

### Expected behavior

The zip should contain a subtitle (srt file)

### Actual behavior

The zip is actually an html file for the opensubtitle main page 

### Device information

* Android device: Lenovo Zuk z2
* Fenix version: Firefox Beta 75.0.4

**Comment by kbrosnan** [comment]
A am getting an XPI when trying to download in Firefox Preview Nightly. This seems like webcompat, they are sending garbage to Firefox. I get the same behavior in Firefox for Android 68. Closing.

**Comment by moronigranja** [comment]
Works fine for me on firefox 68, hence I rolled back the update. Still broken on 75.

**Comment by Ezio916** [comment]
> 
> 
> A am getting an XPI when trying to download in Firefox Preview Nightly. This seems like webcompat, they are sending garbage to Firefox. I get the same behavior in Firefox for Android 68. Closing.

I've tested this. Download works fine in FF 68 stable. Issue only persist in FF75/Preview.
