### ISSUE TITLE
Reduce number of taps to search on custom engine

### ISSUE THREAD

**Issue by cousteaulecommandant** [mozilla-mobile/fenix#9867]
Old behavior:
1. Type something on URL bar.
2. Tap a search engine icon.  This opened the search site query directly.

New behavior (75.0.0-beta.4):
1. Type something on URL bar.
2. Tap "Shortcuts" to show the search shortcuts (which get hidden for some reason).
3. Tap a search engine in the list.  This adds a search entry to the list of suggestions.
4. Tap the suggestion to open the search site query.

Could the old behavior be restored?  I.e., remove steps 2 and 4, so that I have a one-tap search again.

The old behavior was very useful because I could search YouTube videos, Wikipedia articles, Linguee translations, etc with a single tap, which was a feature I really liked from Firefox, and allowed me to use it as easily as site-specific apps such as the YouTube app.

**Comment by Diana-Rus** [comment]
Hi, thank you for the suggestion. It seems to me that is similar to the description from here, or at least similar idea:https://github.com/mozilla-mobile/fenix/issues/9867.
I am going to close this ticket. But please follow the mentioned ticket in order to check the evolution. Thanks

**Comment by loveless90** [comment]
> Hi, thank you for the suggestion. It seems to me that is similar to the description from here, or at least similar idea:#9867.

Did you mean another bug-report, because you linked the same.

**Comment by Diana-Rus** [comment]
Hi, yes sorry for that, this is the one: https://github.com/mozilla-mobile/fenix/issues/9650
Thank you ☺️

**Comment by cousteaulecommandant** [comment]
@Diana-Rus Nope, not quite the same issue.  That one proposes an easy way to _switch_ engines, whereas what I propose is for a one-time search with an alternative engine while the default one is kept.  Something similar to desktop Firefox's _"**This time,** search with"_ entry (which is what the previous mobile Firefox had).

Personally I find that behavior more convenient since I don't think I'll be switching the default search engine that often; it's just that sometimes I want to look up something on Wikipedia or YouTube directly rather than Googling it or (insert your favorite search engine)-ing it.

**Comment by cousteaulecommandant** [comment]
In fact, the "This time, search with" buttons used to perform a DOUBLE function: select the engine, and "press enter".  Now these are two separate steps.  And, additionally, search engine suggestions are now hidden as soon as you start typing, so you need one extra action to display them.

If there is a reason why being able to select a search engine is desirable, and UI suggestions are welcome, I would suggest reverting to the old behavior/appearance (buttons for each search engine), and using some kind of gesture to switch to them (e.g., tap icon to search, drag icon upwards to display search suggestions within engine).  What do you think?
