### ISSUE TITLE
[Bug] history page briefly flashes when navigating away from a tab 

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#9868]
## Steps to reproduce
Open overview
open a page from history in 3dot menu
open overview
### Expected behavior
overview opens
### Actual behavior
history page opens. then all icons load and the history page disapears and overview opens
### Device information

* Android device: Asus Zenfone
* Fenix version: Nightly

**Comment by s-ankur** [comment]
I am not seeing this anymore, can be closed

**Comment by softvision-miralobontiu** [comment]
I'll close this, as I cannot reproduce this either on the 10/20 Nightly build.
