### ISSUE TITLE
Add new tab and new private tab to main menu

### ISSUE THREAD

**Issue by Poopooracoocoo** [mozilla-mobile/fenix#9871]
### Why/User Benefit/User Problem
It was removed because it takes two taps whether you use the main menu or use the tab switcher/home page. **I imagine that Fenix will eventually allow you to drag on the menu button to open it like you can on Windows and in other Android apps.**

### What/Requirements
Add new tab and new private tab to main menu
### Acceptance Criteria (how do I know when I’m done?)
idk

**Comment by violasong** [comment]
Given how crowded the toolbar menu is, my preference would be to add the swipe/button gesture for easier creation of a new tab. For reference, what Android apps currently have this type of gesture?

**Comment by Poopooracoocoo** [comment]
Fenix has changed a lot since I created this issue.

**Comment by ekager** [comment]
Closing as stale. Let's open a new issue if you're still having an issue
