### ISSUE TITLE
[Bug] "Fill link from clipboard" is showing only last part

### ISSUE THREAD

**Issue by marcinwiacek** [mozilla-mobile/fenix#9872]
## Steps to reproduce

1. copy text "SKYACTIV-G 1.5" to the clipboard
2. switch to Firefox
3. click on the URL bar from main page -> there will be opened keyboard, URL bar and "Fill link from clipboard"

### Expected behavior

Link should show the whole part of copied text (or text with ellipsis)

### Actual behavior

Link "Fill link from clipboard" is showing only "1.5"

### Device information

* Android device: S7 Android 8
* Fenix version: Nightly 200320

**Comment by Diana-Rus** [comment]
Hi, I was able to reproduce the issue with Samsung Galaxy S9 (Android 8), Sony Xperia Z5 (Android 7) and Google Pixel 3 XL (Android 9) using a Nightly debug build 39.0.20200412130044,d433836f0 GV: 77.0a1-20200410095419 AS: 0.55.0.

Samsung Galaxy S9 (Android 8) - GIF
![20200413-142455](https://user-images.githubusercontent.com/49859863/79117411-b515f100-7d93-11ea-9525-332671cfe936.gif)
