### ISSUE TITLE
[Bug] Crash on "Add to Home Screen"

### ISSUE THREAD

**Issue by aliglelo** [mozilla-mobile/fenix#9873]
## Steps to reproduce
- open firefox preview on android device
- visit `https://news.google.com`
- click "Add to home screen"

### Expected behavior
- Website should be added to home screen

### Actual behavior
- Browser will crash

### Device information

* Android device: Android 9.0 (MIUI 11)
* Fenix version: Latest play store version

**Comment by mcarare** [comment]
I could not reproduce this on a device with Android 9.

**Comment by sflorean** [comment]
Tested with Xiaomi Redmi Note 8T (Android 9 - MIUI 11), and couldn't reproduce the issue.

**Comment by aliglelo** [comment]
But every time I do so 
The browser crashes and I have even sent data of crash for many times.
My device is Redmi 7 A

**Comment by aliglelo** [comment]
Make sure you are logged into your google account

**Comment by mcarare** [comment]
Still cannot reproduce the crash in latest master version.

**Comment by aliglelo** [comment]
> Still cannot reproduce the crash in latest master version.

Don't know then.
By the way I am using latest version of Firefox preview.
And Even checked it today but same thing happened again.
