### ISSUE TITLE
[Bug] Search icon is oversized in New Tab screen

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/fenix#9876]
## Steps to reproduce

1. Open Fenix
2. Tap + icon

### Expected behavior

Icon is smaller and fits into UI (like it does on my Pixel 2)

### Actual behavior

Search icon is too large and looks out of place. 

![signal-attachment-2020-04-12-152345](https://user-images.githubusercontent.com/152493/79078120-2db57880-7cd4-11ea-99fa-8834f17b4059.png)

### Device information

* Android device: LG G4 (H810), Android 6
* Fenix version: latest nightly from play store

**Comment by softvision-miralobontiu** [comment]
I wasn't able to reproduce this issue on the 10/20 Nightly build with Xiaomi Mi4i (Android 5.0.2).
@yoasif could you please retest on your device?
Thank you!

**Comment by yoasif** [comment]
@softvision-miralobontiu I can still reproduce the issue on my device.

**Comment by softvision-miralobontiu** [comment]
Could you provide us some more information, please?
- what device are you using?
- which version of Firefox?
- are there any additional steps that I missed?
Thank you!
