### ISSUE TITLE
[Bug] Bad kerning on start page on first launch

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/fenix#9877]
## Steps to reproduce

1. Install Fenix
2. Start Fenix

### Expected behavior

Text in action buttons like "Open settings" and "Read our privacy notice" should be easy to read and attractive. 

### Actual behavior

Letters are too close together.

![signal-attachment-2020-04-12-152350](https://user-images.githubusercontent.com/152493/79078285-5ab65b00-7cd5-11ea-8380-75ccb843d46b.png)

### Device information

* Android device: LG G4 (H810), Android 6
* Fenix version: latest nightly from play store

**Comment by sblatz** [comment]
Should be addressed by my style guide buttons: https://github.com/mozilla-mobile/fenix/pull/9858/files/a2dded086edc7518f88b5f532fd01c67839d78d3#diff-6f870d7e261f41dd3e52a2a129fa1fc5R196

**Comment by LaurentiuApahideanSV** [comment]
Verified as fixed on Preview Nightly (Build #21070840) 4/16 using a OnePlus 6T (Android 9) and Huwei MediaPad M3 lite (Android 7.0).
