### ISSUE TITLE
[Bug] undesired animation of device name in settings

### ISSUE THREAD

**Issue by cadeyrn** [mozilla-mobile/fenix#9879]
### Steps to reproduce

0. make sure you're connected to Sync
1. open the sync settings

### Expected behavior

No animation of the device name.

### Actual behavior

The device name slides from the top to the final position. No other row on this screen has this behaviour.

### Device information

* Android device: OnePlus 7T Pro McLaren Edition / Oxygen OS 10.0.8 (Android 10)
* Fenix version: master branch revision 52857b09d70c398fc1a5af81d0e271ec1b736601

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-16796)

**Comment by cadeyrn** [comment]
@sblatz Since you worked on settings animations in the past - do you know the reason for this animation / if this is something easy to fix?

**Comment by cadeyrn** [comment]
@ekager Since @sblatz is no longer working for Mozilla - Do you know who is the best person to ask about this issue these days?

It's not an important issue but it would still be nice to get this fixed. I looked at this some time ago thinking it's an easy issue and I could create a PR for it, but I didn't find where the animation came from.

**Comment by ekager** [comment]
This isn't a critical bug, so it's unlikely someone on the team will have time to look into this. Tagging as Help Wanted so contributors are welcome to take a look

**Comment by cadeyrn** [comment]
still an issue (comment for bot).

**Comment by geneukum** [comment]
@ekager I’d be happy to take a look at this issue.

**Comment by cadeyrn** [comment]
@geneukum: ekager no longer works for Mozilla. But since nobody worked on this issue in the last almost two years, I am sure that nobody will complain if you will have a look. 😊

**Comment by cadeyrn** [comment]
still an issue (comment for bot).

**Comment by cadeyrn** [comment]
still an issue (comment for bot).

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807129

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
