### ISSUE TITLE
Occasional crash on attempt to view running sessions

### ISSUE THREAD

**Issue by MickvdMeijde** [mozilla-mobile/fenix#988]
## Steps to reproduce

- Start Fenix and open a website
- tap the button to view your sessions

 

### Expected behavior
 The application shows the current running sessions

### Actual behavior
It goes to the main page which shows as if there are no sessions running and becomes unresponsive. after a little while it crashes 

### Device information

* Android device: Wileyfox Swift 2X, android 8.1.0
* Fenix version: 1.0.1911

**Comment by vesta0** [comment]
@kbrosnan will try to reproduce.

**Comment by vesta0** [comment]
This is fixed.
