### ISSUE TITLE
[Bug] PB-The effect of black screen when recording is cancelled by returning from "Saved Logins"

### ISSUE THREAD

**Issue by Diana-Rus** [mozilla-mobile/fenix#9887]
## Prerequisites
- Have a screen recorder turned on.
- Have the app opened in private browsing mode.
### Steps to reproduce
1. Go to "Menu"/"Settings"/"Private browsing".
2. Disable "Allow screenshots in private browsing" by tapping on the toggle.
3. Go back to "Settings".
4. Go to "Logins and Password".
5. Go to "Saved logins".
6. Go to the previous screen by tapping the back arrow from app or from device.
### Expected behavior
The "Allow screenshots in private browsing" is disabled. The screen recorder cannot capture the apps interface.
### Actual behavior
The "Allow screenshots in private browsing" is enabled. The app's interface is captured by the screen recorder.
### Device information

* Android device: Google Pixel 3 XL (Android 9), Samsung Galaxy S9 (Android 8), Sony Xperia Z5 (Android 7)
* Fenix version: Nightly Debug version 39.0.20200412130044, d433836f0 GV: 77.0a1-20200410095419 AS: 0.55.0

Samsung Galaxy S9 - Allow screenshots in private browsing - Disabled
![20200413-191341](https://user-images.githubusercontent.com/49859863/79137906-41d4a500-7dbc-11ea-9fca-ecd22b8ec3b4.gif)

**Comment by abodea** [comment]
Verified as fixed on the latest **Nightly 4/16** with **Google Pixel 4 XL (10).**
Note that everything is displayed as expected and the recording is dark.
I also added this issue https://github.com/mozilla-mobile/fenix/issues/9987 that is an edge case.
