### ISSUE TITLE
Create UI Style for contextual hints

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#9888]
### Acceptance Criteria (how do I know when I’m done?)
* There is a a context hint class engineers can utilize for contextual hints
* There is a living (and public) style guide that both engineers & UX can point to when discussing designs
* Every contextual hint in the app will adhere to a common pattern so we have consistency 

Stretch goal: This style lives in a library we can import separately from Fenix (like in AC)

### General Process
- [ ] UX identifies components we’re using
- [ ] Engineering finds usages
- [ ] UX & Engineering collaborate on “rules”
- [ ] Engineer implements the style
- [ ] UX & Engineering meet to do “final approval” of the component
	1. Walk through all affected screens
	2. Chat about remaining questions
- [ ] UX & Engineering place component in the library

**Comment by liuche** [comment]
Going to dupe this to #5499. At some point, we may want to do this for the banner (as used in #14920 )
