### ISSUE TITLE
improve discoverability of picture-in-picture feature

### ISSUE THREAD

**Issue by cadeyrn** [mozilla-mobile/fenix#9889]
### Why/User Benefit/User Problem

The picture-in-picture feature is an awesome feature but it's really hard to discover.

At the moment you have to start a video in the fullscreen mode and then you have to switch to your Android home screen to trigger the PiP feature. I noticed Chrome does the same so it's probably good enough for a first implementation.

But I, as a user, neither understand the relation between the fullscreen mode and picture-in-picture mode nor would I have ever thought of the idea that I have to switch to the Android home screen in combination with the previous step to enable this feature.

My hypothesis is that the feature would be much more discoverable if it wouldn't depend on the fullscreen feature.

### What/Requirements

There are different options. Firefox on desktop shows a small overlay over the video to enable the PiP feature. A similar solution would be great from a cross platform consistency POV. A context menu would be another option.

/cc @ekager because you worked on the feature.

### Acceptance Criteria (how do I know when I’m done?)

The feature has to be easier to discover.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-16804)

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813927

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
