### ISSUE TITLE
Keep the main menu displayed while switching to landscape

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#989]
## Steps to reproduce
1. Open the main menu
2. Turn the device in landscape.
### Expected behavior
The main menu stays on screen.
### Actual behavior
The menu is closed when turning the device.
### Device information

* Android device: Pixel (android 9), Galaxy Tab 3 (Android 8.0)
* Fenix version: 3/13 build.

**Comment by kbrosnan** [comment]
Fennec and Focus have this behavior. Chrome does not.

**Comment by softvision-miralobontiu** [comment]
This is fixed on the latest Nightly build 11/21.
