### ISSUE TITLE
[Bug] wrong position of fullscreen snackbar

### ISSUE THREAD

**Issue by cadeyrn** [mozilla-mobile/fenix#9890]
### Steps to reproduce

1. open a video in fullscreen mode

### Expected behavior

The snackbar appears on the bottom of the screen

### Actual behavior

The toolbar is displayed on the wrong position.

![Screenshot_20200413-185019](https://user-images.githubusercontent.com/1100614/79140124-ca9d1200-7db7-11ea-92c2-cd3aedb9eaf2.jpg)

### Device information

* Android device: OnePlus 7T Pro McLaren Edition / Oxygen OS 10.0.8 (Android 10)
* Fenix version: master branch revision 52857b09d70c398fc1a5af81d0e271ec1b736601

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on my Nightly debug **`4.3.0-beta.1 (Build #21050021) `** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)

► Video
![20200414-113014](https://user-images.githubusercontent.com/51314259/79203758-2a40ff00-7e44-11ea-900c-11a6f473e787.gif)

**Comment by cadeyrn** [comment]
@ekager: It looks not fixed on OnePlus 7T Pro McLaren Edition with Oxygen OS 10.0.8 (Android 10). This is a screenshot taken from a build from master branch revision 335642d4f452a802da2e83731137c88f79c1ba4c:

![Screenshot_20200416-210114](https://user-images.githubusercontent.com/1100614/79496119-f6bdca80-8025-11ea-8daa-9f200ee83b76.jpg)

It looks the same as in the original report but is a current screenshot.

**Comment by ekager** [comment]
cc @sblatz this doesn't happen when the toolbar is in the top position. Any ideas here or PRs in flight you think will help?

**Comment by ekager** [comment]
@cadeyrn are you still noticing this? Was trying to figure out if it's device dependent or has been resolved by some other work but haven't been able to reproduce locally

**Comment by cadeyrn** [comment]
Yes, it's still an issue.
