### ISSUE TITLE
[Bug] PWAs leave space with dynamic bottom toolbar

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#9892]
Example:

<img width=350 src=https://user-images.githubusercontent.com/172215/75379694-ad08fd00-588a-11ea-9ce3-19e910f7b0db.png>

Originally from #8768

**Comment by snorp** [comment]
For PWAs we need to set the max toolbar height to 0, since we're never going to show it.

**Comment by sblatz** [comment]
@snorp Yep! Have a patch almost ready to go 😄

**Comment by sblatz** [comment]
https://github.com/mozilla-mobile/fenix/pull/9893

**Comment by Diana-Rus** [comment]
Hi, verified the issue with Google Pixel 3 XL (Android 9), Sony Xperia Z5 (Android 7) and Samsung Galaxy S9 (Android 8) on a recent nightly debug build 39.0.20200413130047, d433836f0 GV: 77.0a1-20200410095419.

Note:
- The fix did not reach Beta 4.3.0-beta.1
- Verified with Twitter and Instagram set as PWA.

**Google Pixel 3 XL (Android 9) - Twitter - Nightly debug build - GIF**
![20200414-124156](https://user-images.githubusercontent.com/49859863/79224845-7a2fbe00-7e64-11ea-976e-f29e3cb6caf3.gif)

**Samsung Galaxy S9 (Android 8) - Instagram - Nightly debug build - GIF**
![20200414-151417](https://user-images.githubusercontent.com/49859863/79224995-ba8f3c00-7e64-11ea-84b5-96cde4c8604b.gif)
