### ISSUE TITLE
[Bug] Feedbin.com is not recognized as an installable PWA

### ISSUE THREAD

**Issue by serovar** [mozilla-mobile/fenix#9897]
## Steps to reproduce
1. Go to feedbin.com
2. Tap the three dots
3. Install/Add to home screen

### Expected behavior
Feedbin.com is recognized as a PWA and can be installed as a borderless app on the home screen, as it is with Chrome.

### Actual behavior
Feedbin.com is recognized as a shortcut and can only be added to the home screen as a link that open a full-fledged tab on Fenix.

Video:
![feedbin](https://user-images.githubusercontent.com/6732420/79165924-68a6d180-7de4-11ea-94b1-89d926a5b815.gif)

Chrome Lighthouse mobile PWA audit shows no web app manifest (I suppose the issue could be due to it, but I am not sure), but Chrome correctly installs it borderless nonetheless, as seen in the video above:
![feedbin lighthouse](https://user-images.githubusercontent.com/6732420/79165965-82e0af80-7de4-11ea-826b-783479ea2273.png)

### Device information

* Android device: Pixel 2 XL, Android 10
* Fenix version: Nightly 200408 06:01 (Build #20990610)

**Comment by serovar** [comment]
@ekager This is the issue I was talking about.

**Comment by NotWoods** [comment]
I think this is an issue with Chrome opening the site without borders, as the app doesn't count as a PWA without a web app manifest. I recommend opening an issue with Feedbin and requesting they add a manifest to their web app.

**Comment by serovar** [comment]
Thanks for the clarification, I will notify it to them.
