### ISSUE TITLE
Search Engine mismatch

### ISSUE THREAD

**Issue by anunaym14** [mozilla-mobile/fenix#990]
## Steps to reproduce

Change default search engine from settings.

### Expected behavior 

Search engine logo gets changed on main screen, browser actually uses the updated search engine and also shows search suggestions from the updated one.

### Actual behavior

The logo dies get changed but it still uses Google for searches and search suggestions.

### Device information

Xiaomi Redmi Note 5 Pro (whyred) 

* Android device: 9.0 
* Fenix version: 1.0.1911 from https://tools.taskcluster.net/index/project.mobile.fenix.signed-nightly.nightly/latest

**Comment by cadeyrn** [comment]
Dupe of #884. The taskcluster build is from 2019-03-11, the code landed on 2019-03-12.

**Comment by anunaym14** [comment]
Yeah just checked
