### ISSUE TITLE
[Bug] Files (public) don't download from Google Drive in Private browsing mode

### ISSUE THREAD

**Issue by ghost** [mozilla-mobile/fenix#9903]
## Steps to reproduce
1. Download any publicly available file from Google Drive while in private browsing mode (I was trying to download a PDF and a ZIP file, both failed)
2. Download fails. I haven't tested it on other sites but this is where the bug is reproducible 100% of the time.

Watch the video that I attached (which is a ZIP file) to get a clear understanding of what I'm saying. Extract the file to see the video.
[Video_1586845232334.zip](https://github.com/mozilla-mobile/fenix/files/4473510/Video_1586845232334.zip)

Visit the following Google Drive [link](https://drive.google.com/file/d/1FNmuJkUivTWbihkjepp6zEwKtE6JGfjU/view?usp=drivesdk) while in Private browsing mode and try to download the file; the download fails.

### Expected behavior
The file should download in Private browsing mode 

### Actual behavior
The file doesn't download in Private browsing mode 

### Device information

* Android device: Motorola One Power, Android 10
* Fenix version: Firefox Preview 4.2.1 (Build #20941431)
This Also happens on the latest beta released today i.e 
Firefox Preview beta:4.3.0-beta.1 (Build #21050022)

**Comment by kglazko** [comment]
I can reproduce this on my Samsung Galaxy Tab S5e running Android 9. I couldn't download a PDF from my Google Drive with Private Mode enabled, the download would always fail.

**Comment by Amejia481** [comment]
For some reason, when we try to download gv is returning us a HTTP 403 error

**Comment by Amejia481** [comment]
I opened a Bugzilla bug for the GV to take a look https://bugzilla.mozilla.org/show_bug.cgi?id=1641586

**Comment by liuche** [comment]
We should retest for public files.

**Comment by Amejia481** [comment]
> We should retest for public files (authenticated downloads is another issue).

Actually, the [example file](https://drive.google.com/file/d/1FNmuJkUivTWbihkjepp6zEwKtE6JGfjU/view?usp=drivesdk) in the STR is a public file it doesn't require authentication :)

**Comment by sflorean** [comment]
@kglazko I was able to reproduce this on Nightly 6/18 with **Samsung Galaxy Note 10 (Android 10)**, in private browsing. 
Wasn't able to replicate the issue for audio, video, docs, pdf files from file-examples, in private browsing. 

For **Nokia 6 (Android 7.1.1)** the issue is not reproducible.

For **Xiaomi Redmi Note 8T (Android 9)** - the issue is reproducible in private browsing and [crashes](https://bugzilla.mozilla.org/show_bug.cgi?id=1646246) when trying to download in normal browsing.

**Comment by owlishDeveloper** [comment]
@sflorean 

> For **Nokia 6 (Android 7.1.1)** the issue is not reproducible.

Have you tried Nightly or production build? For Samsung Galaxy Note 10 and Xiaomi Redmi Note 8T - was it reproducible on main build or only on Nightly?

I am able to reproduce on Nightly 6/30 on Samsung Galaxy S8 (Android 9), not able to reproduce on Preview 5.2.0

**Comment by SS1113** [comment]
@Amejia481 do you think this bug is somehow related: 
https://github.com/mozilla-mobile/fenix/issues/12297

I cannot reproduce the above mentioned bug on **`Nightly 200704 18:05`**.
 Device: **Motorola One Power, Android 10**.

**Comment by sflorean** [comment]
@owlishDeveloper 
> Have you tried Nightly or release build? For Samsung Galaxy Note 10 and Xiaomi Redmi Note 8T - was it reproducible on release build or only on Nightly?
> 
Only on Nightly build, tested again on latest release and Nightly.

**Comment by Amejia481** [comment]
> @Amejia481 do you think this bug is somehow related:
> #12297
> 
> I cannot reproduce the above mentioned bug on both Normal and Private Browsing Mode. Fenix: **`Nightly 200704 18:05`**.
> Device: **Motorola One Power, Android 10**.
> 
> And as for the Google Drive file download issue in Private Browsing Mode, the issue is still reproducible for me. See the screenshot.
> 
> Fenix: **`Nightly 200704 18:05`**.
> Device: **Motorola One Power, Android 10**.
> 
> ![Screenshot_20200706-094947](https://user-images.githubusercontent.com/42088907/86555522-205d0280-bf40-11ea-92ce-e60a05c9b762.png)

I think this is a separate issue

**Comment by owlishDeveloper** [comment]
@SS1113 I agree it's a separate issue

**Comment by owlishDeveloper** [comment]
@SS1113 are you still able to reproduce this bug on the latest release build? (I think it's Firefox Beta now)

**Comment by SS1113** [comment]
@owlishDeveloper yes, the issue still reproduces on the latest **`Nightly 200706 06:01`** on **Motorola One Power, Android 10**.

I still cannot download Google Drive files in Private Browsing Mode.

**Comment by SS1113** [comment]
@owlishDeveloper this also still reproduces on the **`Firefox Beta 79.0.0-beta.5`** as well. 

Device: **Motorola One Power, Android 10**.

**Comment by owlishDeveloper** [comment]
> @owlishDeveloper
> 
> > Have you tried Nightly or release build? For Samsung Galaxy Note 10 and Xiaomi Redmi Note 8T - was it reproducible on release build or only on Nightly?
> 
> Only on Nightly build, tested again on latest release and Nightly.

@sflorean  so I got the bug to reproduce on current latest Nightly (nee release build) - after re-install. May I ask you to re-install couple of apps where the bug wasn't reproducible (on Nokia 6 (Android 7.1.1), or latest release on Xiaomi Redmi etc) to see if it reproduces after the re-install?

**Comment by owlishDeveloper** [comment]
@SS1113 did you by any chance happen to install or re-install the app some time before seeing the bug?

**Comment by SS1113** [comment]
> @SS1113 did you by any chance happen to install or re-install the app some time before seeing the bug? (vs just updating)

@owlishDeveloper since there were lot of versions on the Play Store I moved from a lot of versions. 

But I can say that to test this;

**`null (Build #2015749827)
AC: 48.0.3, ce6247fb8
GV: 79.0-20200629163142
AS: 61.0.7`** --> Fennec migration build, updated from previous versions. Package name; **`org.mozilla.firefox`**


**`Firefox Beta 79.0.0-beta.5`** --> fresh install. Package name; **`org.mozilla.firefox_beta`**

**`Firefox Nightly 200706 06:01`** --> updated from previous versions. Package name; **`org.mozilla.fenix`**

On all three versions the issue reproduces.

**Comment by ShatteredPixel** [comment]
Hi, I am the reporter of this bug. Please let me know if I can provide you any more information.

Thank you! :)
