### ISSUE TITLE
[Bug] Screen flashes while switching between apps and returning to Fenix

### ISSUE THREAD

**Issue by ghost** [mozilla-mobile/fenix#9904]
## Steps to reproduce
1. launch Fenix, go to a webpage, preferably a webpage with a dark background
2. Navigate between apps and go back to Fenix. 
3. See the screen flashing immediately after getting back in to Fenix.

Please see the video to get a clear understanding of what I'm saying. Extract the file to see the video.
[20200414_121459.zip](https://github.com/mozilla-mobile/fenix/files/4473623/20200414_121459.zip)

### Expected behavior
The screen shouldn't flash while switching and coming back to Fenix

### Actual behavior
Screen flashes while returning to Fenix

### Device information

* Android device: Motorola One Power, Android 10
* Fenix version: Firefox Preview 4.2.1 (Build #20941431)

**Comment by Diana-Rus** [comment]
Hi, I can reproduce the issue with Google Pixel 3 Xl (Android 9), Samsung Galaxy S9 (Android 8) and Sony Xperia Z5 (Android 7) on Firefox Nightly 5/11.

**Comment by mcomella** [comment]
I wonder if this is related to the flash I see on startup: https://github.com/mozilla-mobile/fenix/issues/11616

**Comment by TitanNano** [comment]
I also See this on Android 10, Sony XPERIA 10

**Comment by ShatteredPixel** [comment]
Hi, I am the reporter of this issue. Please let me know if I can provide you any more information.

Thank you! :)
