### ISSUE TITLE
[Bug] Snackbar- "Bookmark saved" and "Edit" action are not aligned correctly

### ISSUE THREAD

**Issue by Diana-Rus** [mozilla-mobile/fenix#9907]
## Prerequisites:
- Change the language of the device to German
### Steps to reproduce
1. Open Fenix and make a search after a site.
2. Bookmark the site.
3. Check the bookmark snackbar.
### Expected behavior
The "Bookmark saved" and "Edit" button are correctly aligned.
### Actual behavior
The "Bookmark saved" and "Edit" button are not correctly aligned.
### Device information

* Android device: Google Pixel 3 XL (Android 9)
* Fenix version: Beta 4.3.0-beta.1
Note: 
- WIth Samsung Galaxy S9 (Android 8) and Sony Xperia Z5 (Android 7) the issue does not reproduce.
- I only reproduced with German language.

Screen:
![Screenshot_20200414-111604edit](https://user-images.githubusercontent.com/49859863/79204259-eef30000-7e44-11ea-87e0-8603fd362525.png)

**Comment by mcarare** [comment]
Can QA please retest this? (maybe for a couple other languages as well). Changes have been  there since this was reported. TY!

**Comment by sflorean** [comment]
Tested on Nightly 6/12 with Samsung Galaxy Note10 (Android 10),  Nokia 6 (Android 7.1.1), Google Pixel 3 (Android 11-beta) with different languages, including the one from the description and couldn't see any issues landscape/portrait.

**Comment by mcarare** [comment]
Closing, as per https://github.com/mozilla-mobile/fenix/issues/9907#issuecomment-643272039.
