### ISSUE TITLE
Display video in full-screen when returning from PiP mode

### ISSUE THREAD

**Issue by sv-sdeiac** [mozilla-mobile/fenix#9910]
## Steps to reproduce
1. Open a video in youtube.com;
2. Go to full-screen;
3. Go to picture-in-picture mode;
4. Tap on the video than on the full-screen icon.

### Expected behavior
The video is displayed in full-screen mode.

### Actual behavior
The video is not displayed in full-screen mode.

### Device information
Android device:
- Google Pixel 3 (Android 10);
- Samsung Galaxy Note 8 (Android 9);
- LG g7 fit (Android 8.1).

Fenix version: Firefox Preview Debug build from master 4/13 GV: 77.0a1.

#### Notes
- This issue is not reproducible using Firefox For Android RC build 68.7.0.
- Also, reproducible using Reference Browser build #20991207 GV: 77.0a1.
 - Meta of the bug: #2818.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-16818)

**Comment by jonalmeida** [comment]
This was done intentionally to make the UX of PiP in the browser to match that of YouTube, but we can change this.

Leaving for product to decide.

**Comment by softvision-miralobontiu** [comment]
This issue still reproduces on the latest RC 80.1.3 build with Samsung Galaxy Tab S6 (Android 9).
