### ISSUE TITLE
[Bug]Play/pause button is missing in PiP using Xiaomi Mi 8 Lite (Android 9)

### ISSUE THREAD

**Issue by sv-sdeiac** [mozilla-mobile/fenix#9911]
## Steps to reproduce
1. Open a video in youtube.com;
2. Go to full-screen;
3. Go to picture-in-picture mode;
4. Tap on the video to display the media control symbols;

### Expected behavior
The Play/pause button is displayed.

### Actual behavior
The play/pause button is missing.

### Device information
Android device: Xiaomi Mi 8 Lite (Android 9);

Fenix version: Firefox Preview Debug build from master 4/13 GV: 77.0a1.

#### Notes
- This issue is not reproducible using Firefox For Android RC build 68.7.0.
- Meta of the bug: #2818.

Not reproducible with:
- Google Pixel 3 (Android 10);
- Samsung Galaxy Note 8 (Android 9);
- LG g7 fit (Android 8.1).

![20200414_143107](https://user-images.githubusercontent.com/40264165/79220599-f45c4480-7e5c-11ea-8c43-988391c04643.gif)

**Comment by jonalmeida** [comment]
It looks like media support is missing from this device. I don't see an media notifications when a video is playing. PiP gets media controls for free when that works.
