### ISSUE TITLE
[Bug] WebPush is not working

### ISSUE THREAD

**Issue by softvision-miralobontiu** [mozilla-mobile/fenix#9912]
## Steps to reproduce
1. Go to https://gauntface.github.io/simple-push-demo/ and enable Push Notifications.

### Expected behavior
Push Notifications toggle can be enabled, and the user can send web push messages.

### Actual behavior
The page does nothing. The toggle cannot be enabled.

### Device information
* Android device: all
* Fenix version: Nightly debug build from 4/14, Beta 4.3.0-beta.1
* Works as expected on Fennec 68.7.0

[webpush.txt](https://github.com/mozilla-mobile/fenix/files/4475220/webpush.txt)

![push](https://user-images.githubusercontent.com/40694158/79225302-3093a300-7e65-11ea-8821-ff674c3136b2.png)

**Comment by liuche** [comment]
@jonalmeida can we re-enable webpush? AC 38 has GV 76.

**Comment by jonalmeida** [comment]
Push is already enabled in nightly. This is failed because the build is debug which has no Firebase API keys.

We can close this as invalid.

**Comment by softvision-miralobontiu** [comment]
@jonalmeida it is also reproducible on Beta 4.3.0-beta.1, and in 4.2.1 RC, that are not debug builds.

**Comment by jonalmeida** [comment]
> @jonalmeida it is also reproducible on Beta 4.3.0-beta.1, and in 4.2.1 RC, that are not debug builds.

Yes, it's only enabled on nightly right now. You can follow https://github.com/mozilla-mobile/fenix/issues/9338 to know when it will be enabled on beta/release. Thanks!
