### ISSUE TITLE
[Bug] Fenix flickers when backgrounded 

### ISSUE THREAD

**Issue by ebalazs-sv** [mozilla-mobile/fenix#9915]
## Steps to reproduce
1. Launch Fenix;
2. Tap the Home screen device button;
### Expected behavior
Fenix is backgrounded.
### Actual behavior
Fenix flickers when backgrounded.
### Notes
Not reproducible on Samsung Galaxy Tab S6 (Android 9), Samsung Galaxy A6 (Android 5.1.1);
[Video](https://drive.google.com/open?id=1s-eNnSCmB-yt38_t_lvNMlGTMd7i3lqx)
### Device information

* Android device: Motorola Moto G6 (Android 8); Huawei MediaPad M3 Lite 10 (Android 7.0);
* Fenix version: Beta 4.3.0-beta.1

**Comment by liuche** [comment]
Duping to #12642 where it's very visible.
