### ISSUE TITLE
Add automatic theme option to Android 9 and below

### ISSUE THREAD

**Issue by Poopooracoocoo** [mozilla-mobile/fenix#9919]
### Why/User Benefit/User Problem
Users can use an app like this to enable dark mode in apps: https://play.google.com/store/apps/details?id=systems.maju.darkmode&hl=en
The auto mode is pretty cool!

### What/Requirements
Add automatic theme option to Android 9 and below

### Acceptance Criteria (how do I know when I’m done?)
When you can use Dark Mode by Julian Eggers to change the theme of Fenix

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-16826)

**Comment by JVariance** [comment]
Would like to see that implemented as well.

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807086

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
