### ISSUE TITLE
[webcontent] Slow loading time on https://siasat.pk

### ISSUE THREAD

**Issue by miketaylr** [mozilla-mobile/fenix#9920]
https://github.com/webcompat/web-bugs/issues/50862

STR:

1. load https://siasat.pk

Expected:
It's about as fast as chrome

Actual: 
It seems to take much longer.

I don't perceive any real difference on desktop.

**Comment by Diana-Rus** [comment]
Hi, can we ask the user whether it reproduces with the latest Nightly build this inconvenience?
Seems that with the latest version of Nightly the loading time does not take as much. 

Verified with Samsung Galaxy S9 (Android 8) and Google Pixel 3 XL

I checked with android studio:
 ->[Samsung - Android Studio - Siasat loading page.txt](https://github.com/mozilla-mobile/fenix/files/4622928/Samsung.-.Android.Studio.-.Siasat.loading.page.txt)
-> [Pixel-Siasat page load.txt](https://github.com/mozilla-mobile/fenix/files/4622968/Pixel-Siasat.page.load.txt)
