### ISSUE TITLE
[Bug] Missing site name on the error pages

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/fenix#9922]
Tested on latest Nightly version.

![Screenshot_20200314-013931](https://user-images.githubusercontent.com/42752644/79254894-6e87cb80-7e53-11ea-9fbb-82c1fa953280.png)
![Screenshot_20200314-013915](https://user-images.githubusercontent.com/42752644/79254899-70518f00-7e53-11ea-8b2f-ac0cbe372050.png)

**Comment by ekager** [comment]
Looks like https://github.com/mozilla-mobile/android-components/issues/6384 was the same issue and an attempted fix was merged 20 days ago. If this is still happening in master/nightly then this probably requires a different fix.

**Comment by ekager** [comment]
cc @mcarare could you look into this?

**Comment by mcarare** [comment]
@vesta0 What site are you testing on? It works fine for me with the latest master on [https://testsafebrowsing.appspot.com/s/phishing.html](url)

![prtl](https://user-images.githubusercontent.com/48995920/79286066-1d65ef00-7ec8-11ea-9fc4-10cf2ccdb50b.png)

**Comment by ekager** [comment]
This is fixed in latest Nightly.
