### ISSUE TITLE
[Bug] Error Pages Aren't Working in Latest Nightly 

### ISSUE THREAD

**Issue by ekager** [mozilla-mobile/fenix#9924]
## Steps to reproduce
Go to https://testsafebrowsing.appspot.com/ to test error pages

### Expected behavior
See error pages

### Actual behavior
No error pages

### Device information

* Android device: Pixel 3
* Fenix version: Nightly 200408 Build #20990610

**Comment by ekager** [comment]
Weirdly I can't reproduce this now but was definitely able to the other day when I filed with the same Nightly version. 🤔

**Comment by ekager** [comment]
Okay I am able to reproduce again after clearing my cache in Nightly.

**Comment by jonalmeida** [comment]
I incorrectly linked this issue to different one.

**Comment by ekager** [comment]
Some of the links on the page show an error page correctly. Closing for https://github.com/mozilla-mobile/fenix/issues/9026
