### ISSUE TITLE
[Bug] Private tab homescreen-text isn't quite accurate (or at least is easy to misinterpret)

### ISSUE THREAD

**Issue by dholbert** [mozilla-mobile/fenix#9928]
## Steps to reproduce
1. Tap the mask at top right of Firefox Preview to switch to private-tabs mode. (I'm assuming you don't have any private tabs open.)
2. Look at the explanatory text.

### Actual behavior
The explanatory text begins: `Firefox Nightly clears your search and browsing history when you quit the app [...]`

Taken literally, this phrase is not true. Firefox Nightly does **not** clear my search/browsing history, (generally) when I quit the app.  It only clears search/browsing history *from private tabs*.

### Expected behavior
A qualifier of some sort to make this statement more precise. Maybe: "Firefox Nightly clears your **private tabs'** search and browsing history when you quit the app"

**Comment by dholbert** [comment]
screenshot:
![image](https://user-images.githubusercontent.com/426803/79270240-9a568180-7e52-11ea-8d79-ae942aec04c0.png)

**Comment by betsymi** [comment]
String update:

`Firefox Nightly clears your search and browsing history from private tabs when you close them or quit the app. While this doesn't make you anonymous to websites or your internet service provider, it makes it easier to keep what you do online from anyone else who uses this device. `

**Comment by betsymi** [comment]
This is closed, posting this comment for documentation it comes up again. String has slightly changed in l10n quarantine.

> Firefox Nightly clears your search and browsing history from private tabs when you close them or quit the app. While this doesn't make you anonymous to websites or your internet service provider, it makes it easier to keep what you do online private from anyone else who uses this device.
