### ISSUE TITLE
[Bug] Dark Reader "Settings" is displayed only after disable-enable

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#9930]
## Prerequisites
Have Dark Reader installed.

## Steps to reproduce
1. Disable Dark Reader globally
2. Re-enable Dark Reader  

### Expected behavior
.The "Settings" button should always be displayed.

### Actual behavior
The "Settings" button is displayed only after re-enabling Dark Reader.
It disappears after tapping it.

### Device information
* Android device: OnePlus A3 (Android 6.0.1)

* Fenix version: Custom Nightly(Build #20861010) 38.0.20200325130041, c580c2293
GV: 76.0a1-20200324093140 AS: 0.55.0

### Notes
► Video
![20200327-113201](https://user-images.githubusercontent.com/51314259/77757040-1c643f00-7039-11ea-8d40-b0be0d78f763.gif)

❓ I think it should re-direct us to this section of Dark Reader ?
► Video
![20200327-113423](https://user-images.githubusercontent.com/51314259/77758512-c3e27100-703b-11ea-856f-7b756cd1fb14.gif)

**Comment by Amejia481** [comment]
@AndiAJ  this is ready for QA :)

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly Build #21060608 from 4/15`** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)

► Video
![20200415-150840](https://user-images.githubusercontent.com/51314259/79335911-7dda4800-7f2b-11ea-9ba0-c666e391a6c7.gif)
