### ISSUE TITLE
[Bug] Consider adding pinch-out (i.e. zoom out) to unfullscreen fullscreen videos

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#9942]
### Why/User Benefit/User Problem
To unfullscreen a video, users have two options:
1. Click the fullscreen button provided by the video player
2. Swipe down from the very top of the screen and click the back button, which is provided by the Android system

However, 1 can be a problem if the website does not provide the controls or makes them difficult to use (e.g. https://github.com/mozilla-mobile/fenix/issues/9939). 2 is not very discoverable.

### What/Requirements
In Firefox for Echo Show, we implemented a "pinch-out" (i.e. zoom out)  to exit fullscreen. The video would shrink with the pinch gesture and when the user released, fullscreen would be exited. Here [is a video sample](https://github.com/mozilla-mobile-skunkworks/firefox-connect/files/2559634/device-2018-11-07-151630.mp4.zip) (note that the video is less smooth than on-device because video capture has overhead).

This is likely more discoverable than 2 and more convenient than 1. Users might actually prefer this way to exit fullscreen than existing functionality.

This may be difficult/impossible to implement because:
- GeckoView may not support resizing the video
- If a user is doing a fullscreen game rather than a video, the pinch gesture may override game functionality. We really can only do this on videos

Context: we implemented this in FFES https://github.com/mozilla-mobile/firefox-echo-show/issues/75 because system option 2 did not exist so sites could do a denial of service attack on Firefox users.

### Acceptance Criteria (how do I know when I’m done?)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-16844)

**Comment by Poopooracoocoo** [comment]
This sounds interesting. I haven't used a single app that does this.

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807050

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
