### ISSUE TITLE
Update Firefox Beta Branding

### ISSUE THREAD

**Issue by liuche** [mozilla-mobile/fenix#9946]
This is just for updating the [fennecBeta](https://github.com/mozilla-mobile/fenix/tree/master/app/src/fennecBeta/res) resources.

### Acceptance Criteria
- [ ] App launcher icon matches the Firefox Release (not beta) resources
- [ ] Other "Beta" references (like search widget, app name, etc) are updated to **not** say Firefox Beta, but reflect release branding

This is very similar to #8277.

The beta migration build shipping on the Fennec Beta channel is built from the fennec/beta branch, so the branding changes can **land on master** and do not need to wait.

(For context: to publish a beta build to the Fennec Beta channel, tag a build with `vX.0.0-beta.Y` and it will publish to the alpha channel and relman can promote it to our beta audience from there.)

@pocmo can help with any technical questions (about channels, flavors, etc).

**Comment by liuche** [comment]
@sblatz currently the earliest we'd need this is April 27 (so I can put it into a build and get it shipped).

**Comment by Diana-Rus** [comment]
Hi, verified the app's branding with a geckoBetaFennecBeta debug build from master on:
**-  Google Pixel 3 XL (Android 9) - Display Size: 640 dpi (xxxhdpi)**
- All scenarios have passed -> FIrefox Logo and wordmark are displayed.
**-  Google Pixel 3 XL (Android 9) - Display Size: 560 dpi (xxhdpi)**
- All scenarios have passed -> FIrefox Logo and wordmark are displayed.
**-  Google Pixel 3 XL (Android 9) - Display Size: 476 dpi (xhdpi)**
- All scenarios have passed -> FIrefox Logo and wordmark are displayed.
**- Huawei MediaPad M3 Lite (Anroid 7.0) - 272 dpi - hdpi**
- All scenarios have passed -> FIrefox Logo and wordmark are displayed.

**Scenarios:** 
**1. mipmap -> ic_launcher - round (default)**
 1.1 Homescreen - Firefox Release launcher icon is correctly displayed
 1.2 Device Settings/Apps  - Firefox Release launcher icon is correctly displayed
**2. mipmap -> ic_launcher - square**
 2.1 Homescreen - Firefox Release launcher icon is correctly displayed
 2.2 Device Settings/Apps  - Firefox Release launcher icon is correctly displayed
**3. drawable-xxxhdpi -> logo wordmark - normal browsing**
 3.1 Firefox Release - Logo & Wordmark on Onboarding Screen when using Normal Browsing are correctly displayed
 3.2 Firefox Release - Logo & Workmark when using Normal Browsing are correctly displayed
**4. drawable-xxxhdpi -> logo wordmark - private browsing**
 4.1 Firefox Release - Logo & Wordmark on Onboarding Screen when using Private Browsing are correctly displayed
 4.2 Firefox Release - Logo & Wordmark when using Browsing Browsing are correctly displayed

**Extra scenarios:**
- Check that Firefox Release launcher icon is correctly displayed in tear drop
- Check that apk installation file contains the Firefox Release logo
- Check that the Search Widget displays the Firefox Release logo
- Firefox Release banner/app icon is correctly displayed in a Sharing Window
- Check that about:firefox page displays the release Firefox logo and wordmark
- Check that when "Allow to Home Screens rotation" is enabled the Firefox Release launcher icon is correctly displayed
- Check that when "Allow to Home Screens rotation" is enabled the search widget displays the Firefox Release logo

**Video-Google Pixel 3 XL - Display Size: 640 dpi (xxxhdpi) - GIF**
![20200424-182632](https://user-images.githubusercontent.com/49859863/80232043-eaa4bf00-865c-11ea-9f02-57f16fe7524e.gif)


Notes:
- I will leave the ticket with qa needed until it reaches an official build.
- For hdpi contains the search widget only for drawable hdpi and not mipmap as in folder structure.

**Comment by liuche** [comment]
Leaving this out of 5.0, so that we can push the new addons to Fennec Beta (without the branding).

**Comment by sblatz** [comment]
I'm going to close this now :)

**Comment by ebalazs-sv** [comment]
Verified as fixed on Beta Migration 79.0.0-beta.2 GV 79 from 6/30 with Motorola Moto G6 (Android 8).
The branding is reverted back to Firefox Beta. Thanks!
