### ISSUE TITLE
Browse other webpages when picture-in-picture mode is enabled

### ISSUE THREAD

**Issue by lindongbin** [mozilla-mobile/fenix#9947]
### Why/User Benefit/User Problem

I have a mobile phone with a huge screen, I want to be able to browse other websites while watching videos in PIP mode

### Acceptance Criteria (how do I know when I’m done?)

Just like the desktop version of firefox

**Comment by jonalmeida** [comment]
This was already discussed during the initial feature request and should be part of the next iteration of PiP. See https://github.com/mozilla-mobile/fenix/issues/2818#issuecomment-553130876.

GV API needed: https://bugzilla.mozilla.org/show_bug.cgi?id=1625012

**Comment by anotherus3r** [comment]
Should we follow this issue or #6600 for this feature?

**Comment by kbrosnan** [comment]
Duplicate of https://github.com/mozilla-mobile/fenix/issues/6600
