### ISSUE TITLE
[Bug]Disabling TP in Strict mode doesn't work properly on Beta 4.3.1

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#9948]
## Prerequisites 
Have tracking protection set to **Strict**

## Steps to reproduce
1. Navigate to https://mozilla.github.io/tracking-test/ads.html
2. Disable tracking protection for this web 
3. Navigate to https://www.theverge.com/
4. Disable tracking protection for this web site
5. Tap the tracking protection shield and check the info shield

### Expected behavior
For **Step 2** a black cat should be displayed confirming the fact that TP is disabled.
For **Step 5** some of the previously blocked options should be allowed

### Actual behavior
It looks like even if the user disables tracking protection for a website Fenix Beta continues to block everything.

### Device information

* Android device: 
• Google Pixel 3a (Android 10)
• Google Pixel 3 XL (Android 9)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)

* Fenix version: Fenix Beta 4.3.0-beta.1 from 4/14

### Notes
✔️ Works on latest Nightly Build #21060608 from 4/15

► **Video Fenix Beta**
![20200415-110618](https://user-images.githubusercontent.com/51314259/79314811-e107b280-7f0a-11ea-8147-d0a93993ce24.gif)

► **Video Fenix Nightly**
![20200415-110834](https://user-images.githubusercontent.com/51314259/79315078-3b087800-7f0b-11ea-916f-1766e75a8954.gif)

**Comment by Amejia481** [comment]
To fix the issue we need some GeckoView work to happen, it can be tracked here https://bugzilla.mozilla.org/show_bug.cgi?id=1625585

**Comment by Amejia481** [comment]
More details https://github.com/mozilla-mobile/fenix/issues/9948

**Comment by liuche** [comment]
Looks like this might not be a GV problem - @fluffyemily how do we handle that handoff from GV to another Gecko team? This is something we'd like to have fixed for release. If you let me know the process, I'll also know for the future. (Do we wait for Ehsan and Johann to respond in bugzilla, and for how long? Do we need to re-prioritize to P1 if we want this for Fenix Release? etc)

**Comment by Amejia481** [comment]
From the **Expected behavior**,  **1** is working on nightly and **2** is partially as we still see some trackers being blocked  as described in https://bugzilla.mozilla.org/show_bug.cgi?id=1625585#c4

**Expected behavior**
1. For Step 2 a black cat should be displayed confirming the fact that TP is disabled.
2. For Step 5 some of the previously blocked options should be allowed

**Comment by liuche** [comment]
Hi @AndiAJ and @Amejia481 - I reached out to @englehardt who maintains this repo about the repo being out of date and not matching the ETP tracking. I'll reach out to him again to deprecate this page and redirect it to the correct testing page.
