### ISSUE TITLE
[Library] Possible inconsistencies between deleting history/bookmark items

### ISSUE THREAD

**Issue by BMEduard** [mozilla-mobile/fenix#9949]
After investigating #8648 I have come across some possible discrepancies between deleting history and bookmark items. These are:

1. Should we allow users to be able to undo the deletion of individual and/or multiple history items, as it is the case for bookmarks?
2. Should we also require the user to confirm the deletion of a folder/folders by adding a confirmation pop-up if he uses multiselect to delete multiple bookmark items and one (or more) of them happens to be a folder? 
This would make it consistent with the requested change (in #8648) to add a confirmation pop-up for deleting a folder. As for the confirmation message, it could be something along the lines of “You have selected one or more folders for deletion. Are you sure you want to delete these items?”. This way the user will be unable to delete a folder without having a confirmation pop up first.

@AmyYLee What are your thoughts regarding these two possible unintended inconsistencies?

**Comment by AmyYLee** [comment]
> After investigating #8648 I have come across some possible discrepancies between deleting history and bookmark items. These are:
> 
>     1. Should we allow users to be able to undo the deletion of individual and/or multiple history items, as it is the case for bookmarks?
> 
>     2. Should we also require the user to confirm the deletion of a folder/folders by adding a confirmation pop-up if he uses multiselect to delete multiple bookmark items and one (or more) of them happens to be a folder?
>        This would make it consistent with the requested change (in #8648) to add a confirmation pop-up for deleting a folder. As for the confirmation message, it could be something along the lines of “You have selected one or more folders for deletion. Are you sure you want to delete these items?”. This way the user will be unable to delete a folder without having a confirmation pop up first.
> 
> 
> @AmyYLee What are your thoughts regarding these two possible unintended inconsistencies?

@betsymi @topotropic What are your thoughts for the above?

**Comment by betsymi** [comment]
1. For deleting an individual history item/several history items, I see no issue with a snackbar where you could undo. For both: `History deleted UNDO`
2. Sure, the confirmation dialog can read the following. `[Browser name] will delete the selected items. CANCEL DELETE`
2a. I did this action myself and if possible would like to update the string on the snackbar that appears after to `Deleting selected folders UNDO`

**Comment by liuche** [comment]
We hit string freeze last Friday, so we can't land any more strings (per our agreement with the L10N team, so that they don't have strings coming in at the last minute).

It's unfortunate because this is such a small change, but we need to back this out and land it after July 20, which is our cut for the Release build (and when we can land strings again).

**Comment by ekager** [comment]
Unfortunately the PR for this #10738 broke string freeze, so we'll have to wait and reland it after code freeze

**Comment by mcarare** [comment]
Reopened for QA.

**Comment by sflorean** [comment]
Verified as fixed on 79.1.0-beta.1 with Samsung Galaxy Note 10(Android10). A confirmation dialog is displayed for selected folders, "undo" option is displayed for both history and bookmarks items, previously deleted.
