### ISSUE TITLE
[Bug] Authors not aligned correctly in Addon Details

### ISSUE THREAD

**Issue by ValentinTimisica** [mozilla-mobile/fenix#9951]
## Steps to reproduce
- `Settings`-> `Add-on`
- Select any item
- Scroll down to `Authors`

### Expected behavior
- Authors view should be aligned correctly with the divider

### Actual behavior
- Authors view has unwanted space below. Check screenshot:
<img src="https://user-images.githubusercontent.com/52956363/79331651-30a6a800-7f24-11ea-81d4-149f635f2511.png" width="400" />

### Device information
* Samsung Galaxy Note 10 (Android 10).
* Fenix version: Latest Nightly

**Comment by ekager** [comment]
Reopening for QA

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly Build #21120610 from 4/21`** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)

► Video
![20200421-092457](https://user-images.githubusercontent.com/51314259/79832888-071dce80-83b3-11ea-97ee-39f39fd465ae.gif)
