### ISSUE TITLE
[Bug] Fix intermittent test verifyAboutFirefoxPreview

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#9952]
Saw it a few times failing on branches:
https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7220210359741397057/executions/bs.f1667194d135dc8e/testcases/2/errors
 (cc: @KMaragh )

**Comment by AaronMT** [comment]
Unfortunately we are testing against live production sites (we should consider not) and they changed the title. Just a string fix.

**Comment by ekager** [comment]
I think I fixed the two failures in #9886
