### ISSUE TITLE
[Bug] False auto completion if entering web adresse

### ISSUE THREAD

**Issue by mikeGolf08** [mozilla-mobile/fenix#9961]
## Steps to reproduce

1. Open a web page you've get auto completions for articles
2. Hit the awesomebar to enter a new web page

### Expected behavior

It is possible to write down the web adresse just from the first hit of the keyboards key.

### Actual behavior

Because of the auto completion you habe to press any key first to get rid of the auto completion before you can write down a new adresse.

![SmartSelect_20200415-173559_Gallery](https://user-images.githubusercontent.com/52482050/79357442-50e46000-7f40-11ea-8c38-54bdb434334c.gif)

### Device information

Samsung Galaxy Note 10

* Android device: Android 10 One UI 2.1
* Fenix version: 75.0.0-beta.4 (Build #2015732379)
37.0.3, 09c298cd6
GV: 75.0-20200403064004
AS: 0.55.0

**Need to mention:** Old bug which has been fixed in Nightly and Preview but now makes a renaissance at Beta!

**Comment by ekager** [comment]
Closing for #6290
