### ISSUE TITLE
Switch tabs via swiping on awesome bar

### ISSUE THREAD

**Issue by mikeGolf08** [mozilla-mobile/fenix#9962]
### Why/User Benefit/User Problem

It'll be a great feature because it takes a lot less time to switch between tabs and will make workflow more efficient.

### What/Requirements

- A **setting to activate** swiping gestures.
- Swiping gestures: **To the left ->** Switch to next tab (down on the tab page) **To the right ->** Switch to preceding tab (tab list up)

### Acceptance Criteria (how do I know when I’m done?)

- Swipes on the awesomebar will switch tabs
- Similar to chrome

**Comment by ekager** [comment]
Closing for #3481
