### ISSUE TITLE
Suggest switch to open tab if inserted is the same

### ISSUE THREAD

**Issue by mikeGolf08** [mozilla-mobile/fenix#9963]
### Why/User Benefit/User Problem

The user will know if an inserted web page is already open.

### What/Requirements

- Check inserted addresse if already open

### Acceptance Criteria (how do I know when I’m done?)

Suggest switching to already open tab if inserted web addresse is the same as in that tab.

**Comment by ekager** [comment]
We do show open sessions as suggestions in the awesome bar currently but it can be difficult to distinguish between history/bookmark/session suggestions. See #482

**Comment by mikeGolf08** [comment]
> We do show open sessions as suggestions in the awesome bar currently but it can be difficult to distinguish between history/bookmark/session suggestions. See #482 

Is there a ticket to make it more obvious?

**Comment by ekager** [comment]
See the last suggestion. It will say "Open to tab", but a lot of history can conceal this. I've commented in #482  :/ 
![Screenshot_20200415-095825](https://user-images.githubusercontent.com/25442310/79365653-c1b75800-7eff-11ea-9d24-591b1f88617b.png)

**Comment by mikeGolf08** [comment]
> See the last suggestion. It will say "Open to tab", but a lot of history can conceal this. I've commented in #482  :/ 
> 

Is this from a version which has not been released via PlayStore because I don't get a "Switch to tab" message?  - I think a colour gradient applied to that message would be got.
