### ISSUE TITLE
Always show awesomebar

### ISSUE THREAD

**Issue by mikeGolf08** [mozilla-mobile/fenix#9966]
### Why/User Benefit/User Problem

For some people it is more convenient to have quick access to awesomebar instead of the need to scroll first.

### What/Requirements

- Setting to always show awesomebar just like in the actual Firefox Browser

### Acceptance Criteria (how do I know when I’m done?)

- Awesomebar won't go away and stays rendered in any case if setting is switched on

**Comment by kbrosnan** [comment]
dupe #8847
