### ISSUE TITLE
[webcontent] Font inflation issue on stackexchange.com

### ISSUE THREAD

**Issue by miketaylr** [mozilla-mobile/fenix#9969]
Originally reported @ https://github.com/webcompat/web-bugs/issues/51640

STR:

1. go to stackexchange.com

Expected: font size is consistent for all questions
Actual: some questions have a larger font size, despite being the same in terms of markup and style.

This does not reproduce in Fennec.

![Screenshot_20200415-132353](https://user-images.githubusercontent.com/67283/79373600-6ba4dd80-7f1c-11ea-8fce-e70ab5ffb7a7.png)

**Comment by ekager** [comment]
cc @buttercookie42 any idea what is causing the inconsistency here?

**Comment by kbrosnan** [comment]
Sounds related to https://bugzilla.mozilla.org/show_bug.cgi?id=707195

More or less text text that has the same parent can be inflated to different levels depending on the length of the text in the child element. example

```
<div id="a>
  <div id="a-1">foo foo foo</div>
  <div id="a-2">foo foo foo foo foo foo foo foo foo</div>
  <div id="a-3"> foo foo foo foo foo foo foo foo foo foo foo foo</div>
</div>
```

**Comment by buttercookie42** [comment]
Also https://bugzilla.mozilla.org/show_bug.cgi?id=786382#c11.

**Comment by ekager** [comment]
Thanks!
