### ISSUE TITLE
Fullscreening and unfullscreening video appears to have redundant layout/measure calls

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#9972]
While investigating potential perf issues of the fullscreen use case https://github.com/mozilla-mobile/fenix/issues/9341, I took a profile to sanity check what happens when opening and closing fullscreen mode on YouTube.com on my P2.

![Screen Shot 2020-04-15 at 13 38 00](https://user-images.githubusercontent.com/759372/79386016-58930d00-7f1e-11ea-92c3-957ee040d44c.png)

The profiler search filter is "performlayout" so the highlighted entries are layout passes.. The event on the left is the touch event and it's followed by `Session.setFullscreenMode` (green code block), which **is followed by 4 layout passes.** Some of the layout calls includes modifications to the decorView (i.e. system bars) that we don't control so this may be unavoidable – **we should take a profile of a standalone app to determine if this is a real problem at not.**

**I personally do not consider this to be a top priority:**
* The passes are fast (76ms for the largest performTraversals), at least on the P2 with debuggable enabled (which makes them slower)
* There is nothing else happening on the main thread at the time so we're not blocking other interactions
* Even if there are problems, fullscreening is probably a relatively infrequent long term modal switch so the time-to-switch doesn't need to be instant in our initial versions.

**Comment by mcomella** [comment]
Triage: we want to determine how long it actually takes to transition: please figure it out (should https://github.com/mozilla-mobile/fenix/issues/9975 suffice?). If it's a non-trivial amount of time, address the issue. If not, send to triage.

**Comment by jonalmeida** [comment]
I'd like to take a look into this since I have some familiarity in the code behind it. A learning experience! 🎉

**Comment by jonalmeida** [comment]
I can see the four layout passes coming from the following ViewGroups in this order: CoordinatorLayout, SwipeRefreshLayout, FrameLayout, FrameLayout.

- The CoordinatorLayout is the root view for the browser fragment, so I don't think there is much to do there.
- The SwipeRefreshLayout is from the androidx libraries to support Pull-to-refresh. While the feature isn't enabled right now, removing this temporarily until then doesn't gain anything. It seems unwise to re-implement the SwipeLayout as well.
- The first FrameLayout is from the [GeckoEngineView][0] in android components.
- The second FrameLayout is from [GeckoView][1] itself extending a FrameLayout that adds the [`SurfaceView`][2] as a child (which is where web content is drawn).


[0]: https://searchfox.org/mozilla-mobile/rev/21913c01c67d0274028cb7789dd01e62ba647f47/android-components/components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineView.kt#30 
[1]: https://searchfox.org/mozilla-central/rev/b8fbb6ead517720daf0b0211115f407b4b951c74/mobile/android/geckoview/src/main/java/org/mozilla/geckoview/GeckoView.java#62
[2]: https://searchfox.org/mozilla-central/rev/b8fbb6ead517720daf0b0211115f407b4b951c74/mobile/android/geckoview/src/main/java/org/mozilla/geckoview/GeckoView.java#254
