### ISSUE TITLE
Add telemetry for duration to enter/exit fullscreen

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#9975]
As part of my fullscreen performance investigation https://github.com/mozilla-mobile/fenix/issues/9341, we should add telemetry to:
1) determine how enter/exit fullscreen performs on all devices (by adding telemetry locally, we can test consistently on our own devices too)
2) potentially watch for regressions to this behavior, depending on how noisy the measurement is

**Comment by mcomella** [comment]
I need help from the Glean team: as far as I can tell, with the current Glean API, it's difficult to take this measurement. I'll reach out to them on Matrix.

**Comment by mcomella** [comment]
I got help from the glean team but I want to double-check with ecsmyth why we want telemetry before we invest more time in making a proper telemetry solution. My WIP with mostly functional telemetry is here: https://github.com/mcomella/fenix/tree/9975-fullscreen-telemetry

**Comment by mcomella** [comment]
> I want to double-check with ecsmyth why we want telemetry before we invest more time in making a proper telemetry solution. 

i.e. there are two thoughts:
1) Can we test locally on a low-end device to rule this out as a perf problem area? (if so, no telemetry needed)
2) Are we intending to use this telemetry to monitor for regressions? (if not, no telemetry needed)

**Comment by mcomella** [comment]
Copying my question from Matrix so it's less likely to get lost. @ecsmyth, please respond!

>  Relatedly, for our non-startup use cases, why do we want to record telemetry vs. just measuring locally? Is that to prevent regressions (rather than identifying if there's a problem to begin with)?

**Comment by ecsmyth** [comment]
My recommendation is that we close this issue as `won't fix`. IIUC the widespread use of MSE means this aspect of the UX is controlled by the JS player used by a particular site to play the video (i.e. largely out of our ability to control/impact).

**Comment by mcomella** [comment]
wfm. My WIP PR is here: https://github.com/mozilla-mobile/fenix/pull/10068
