### ISSUE TITLE
[webcontent] Embedded Twitter tweets fail to load

### ISSUE THREAD

**Issue by Flat** [mozilla-mobile/fenix#9977]
## Site with issue and any steps to reproduce
https://soranews24.com/

1. Browse to any article containing embedded Twitter tweets such as https://soranews24.com/2020/04/12/japanese-twitter-holds-nose-viewing-parties-instead-of-flower-viewing-parties-amid-quarantine/

### Expected behavior

The embedded tweets should load in the article where positioned.

### Actual behavior

No tweets are loaded and are completely missing from the webpage.

### Does toggling Tracking Protection fix the issue? (Press the lock icon in the toolbar while on the site to see toggle)

Tracking does not affect the loading of these embedded tweets.

### Can you reproduce in [Firefox for Android](https://play.google.com/store/apps/details?id=org.mozilla.firefox)?

Can not reproduce in Firefox.

### Can you reproduce in Chrome (or other non-Mozilla browser)?

Can not reproduce in Chrome.

### Device information

* Android device: Samsung Galaxy Note 10+
* Fenix version: Nightly 200408 06:01 (Build #20990610)

**Comment by ekager** [comment]
Turning off ETP in the Settings then displays the images so looks like something is wrong with the ETP panel toggle. Thanks for flagging this!

**Comment by ekager** [comment]
Filed https://github.com/mozilla-mobile/fenix/issues/9980

**Comment by ekager** [comment]
I'm actually going to close this for #9980 since the real issue is the ETP panel not actually toggling ETP. Again thanks so much for bringing this issue to light!! Hopefully this will be fixed soon.

**Comment by Flat** [comment]
Thanks for looking into this so quickly! I'll follow that new issue.
