### ISSUE TITLE
[Bug] After switching to another application, the background tab reloads

### ISSUE THREAD

**Issue by lindongbin** [mozilla-mobile/fenix#9978]
## Steps to reproduce

1. Open about:config,  type whatever you like in the search box
2. Open a second tab, such as Google
3. Switch to other applications, such as the system desktop
4. Re-enter Firefox and switch to the first tab about:config

### Expected behavior

the first tab about:config will not reload and the content of the search box will not disappear

### Actual behavior

Reload

### Device information

* Android device: ?
* Fenix version: ?

**Comment by ekager** [comment]
Closing for #9039
