### ISSUE TITLE
[Bug] After switching to other applications, the desktop mode fails

### ISSUE THREAD

**Issue by lindongbin** [mozilla-mobile/fenix#9979]
## Steps to reproduce

1. Open the first tab and enable desktop mode
2. Open the second tab
3. Switch to other applications
4. Re-enter Firefox, switch to the first tab, the desktop mode cannot be cancelled

### Device information

* Android device: ?
* Fenix version: ?

**Comment by eliserichards** [comment]
Hi @lindongbin! what do you mean by "the desktop mode cannot be cancelled"? Can you add some more info in the expected and actual behavior sections above?

**Comment by lindongbin** [comment]
> Hi @lindongbin! what do you mean by "the desktop mode cannot be cancelled"? Can you add some more info in the expected and actual behavior sections above?

https://i.imgur.com/WLvx2dh.mp4

**Comment by eliserichards** [comment]
@lindongbin I think you're right! That bug is being tracked in #9039, so I am going to close this bug in favor of that one 😄 Thank you!
