### ISSUE TITLE
[Bug] Created ETP Exceptions Via Panel Do Not Take Effect

### ISSUE THREAD

**Issue by ekager** [mozilla-mobile/fenix#9980]
## Steps to reproduce
1. Go to https://mozilla.github.io/tracking-test/
2. Click into panel and disable ETP (adds to exception list)

### Expected behavior
Fox turns to angry cat because site is now an exception

### Actual behavior
Fox remains and ETP remains on but site _is_ added to exception list 

### Device information

* Android device: ?
* Fenix version: ?

**Comment by ekager** [comment]
Can reproduce on master except for when swapping out `geckoBetaImplementation` for `browser_engine_gecko_release` :/ but reproducing with geckoNightly and geckoBeta. Cc @Amejia481 do you know if the GV API changed or if we need to file a new bug here for the exceptions list not working anymore?

**Comment by ekager** [comment]
Looks like https://bugzilla.mozilla.org/show_bug.cgi?id=1625585

**Comment by Amejia481** [comment]
Let's close this issue in favor of https://github.com/mozilla-mobile/fenix/issues/9948 as it more details on how to replicate the issue
