### ISSUE TITLE
[Bug] Bookmark Star Icon Not Updated in Browser Menu when Switching to Opened Tab via Snackbar

### ISSUE THREAD

**Issue by ekager** [mozilla-mobile/fenix#9981]
## Steps to reproduce
1. Search something novel
2. Bookmark search results page
3. Long press a link on search page and "open in new page"
4. Switch to newly opened tab via tab opened Snackbar
5. Click on browser menu

### Expected behavior
Star icon is empty, this page isn't bookmarked. Clicking star bookmarks page.

### Actual behavior
Star icon filled looking like it's already bookmarked. Clicking star bookmarks page.

### Device information

* Android device: ?
* Fenix version: ?

**Comment by ekager** [comment]
Looks like we only look to update the bookmark state when the session URL is changed. We should also be updating this if the session changes.
https://github.com/mozilla-mobile/fenix/blob/master/app/src/main/java/org/mozilla/fenix/components/toolbar/DefaultToolbarMenu.kt#L358

**Comment by AndiAJ** [comment]
Hi, verified as fixed on the latest Nightly Build #21120610 from 4/21 using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)

► Video
![20200421-094136](https://user-images.githubusercontent.com/51314259/79833992-fcfccf80-83b4-11ea-8d0c-5b4db9060320.gif)
