### ISSUE TITLE
[Bug]The Add-ons "Settings" aren't displayed after global disable/re-enable

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#9984]
## Steps to reproduce
1. Install one of the featured Add-ons
2. Open the Add-on
3. Disable and afterwards re-enable it globally

### Expected behavior
The Settings button should be displayed and re-enable.

### Actual behavior
The Settings button doesn't get displayed

### Device information

* Android device: 
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)

* Fenix version: Nightly Build #21070609 from 4/16

## Notes
❗ Not applicable for Dark Reader

► Video
![20200416-120036](https://user-images.githubusercontent.com/51314259/79437783-5347c800-7fdb-11ea-9bda-85311cf11396.gif)

@Amejia481 ❓ Could the fix for #9930 be the cause? ☺️

**Comment by Amejia481** [comment]
@AndiAJ  @mcarare  fixed it :). The fix is on master

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly Build #21130610 from 4/22`** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)

► Video
![20200422-100020](https://user-images.githubusercontent.com/51314259/79951239-fe93c980-8480-11ea-9f63-e1d26ea8c5e1.gif)
