### ISSUE TITLE
As a User I want Fenix to use Mozilla's HTTP Client

### ISSUE THREAD

**Issue by st3fan** [mozilla-mobile/fenix#999]
> TODO This is not a great story name. Come up with something better.

### Why/User Benefit/User Problem

Mozilla has put considerable effort in writing a robust and audited HTTP client that follows our best practices. Using our own stack gives us higher confidence in terms of privacy and security settings.

### What / Requirements

The top level requirement is that all HTTP requests need to go through GeckoView. Not just the requests thst GeckoView makes on its own, but also requests that are done in Kotlin or Rust code.

> TODO This needs to be a more extensive list.

Managed from Kotlin:

- Telemetry
- FavIcon fetching
- PWA Manifest fetching
- Downloads
- Socorro (May already be covered by Gecko?)

Managed from Rust:

- FxA Client
- Sync
- Send Tab

Ideally we also cover third party code that we include in Fenix. But it is unclear if this is something we can fully do. We do not own these libraries and they may not have the flexibility to use a different HTTP client.

- Leanplum
- Adjust
- Sentry

### Acceptance Criteria (how do I know when I’m done?)

All HTTP traffic originating from Fenix will go through Gecko(View). All data that we see on the wire can be accounted for, or at least can be tracked down to a specific HTTP client.

### Related work

- [android-components#348 Implement a shared HTTP API abstraction](https://github.com/mozilla/application-services/issues/348)

**Comment by NotWoods** [comment]
Should we close this issue? As far as I'm aware all non-third-party code goes through the fetch client now.

**Comment by NotWoods** [comment]
Closing since there hasn't been any updates here.
